### ISSUE TITLE
Runkeeper—GPS Running Tracker

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#1]
**App Name:** Runkeeper—GPS Running Tracker
**Bundle ID:** RunKeeperPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300235330">300235330</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runkeeper-gps-running-tracker/id300235330?mt=8&uo=4">https://itunes.apple.com/us/app/runkeeper-gps-running-tracker/id300235330?mt=8&uo=4</a>
**App Version:** 8.6
**Seller:** RunKeeper, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fitnesskeeper-inc/id300226026?uo=4">© FitnessKeeper, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/57/e8/90/57e89073-b469-a55d-5e4f-753e2525b6b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34389809-241757c0-eb3c-11e7-8345-0145129f6a65.png)

**Comment by Trubbel** [comment]
Icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10674789/20291f8a-78fd-11e5-8f8b-8d71f853f694.png)
https://cloud.githubusercontent.com/assets/10730122/10674789/20291f8a-78fd-11e5-8f8b-8d71f853f694.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10674780/1c8fc18a-78fd-11e5-9905-78f55c81604c.png

**Comment by Christian9901** [comment]
Uuhhh, somebody might want to update this, it's icon has updated.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34389809-241757c0-eb3c-11e7-8345-0145129f6a65.png)
https://user-images.githubusercontent.com/2068130/34389809-241757c0-eb3c-11e7-8345-0145129f6a65.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34389821-35358766-eb3c-11e7-990e-98a7f492b60c.png
