### ISSUE TITLE
Showpass

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10007]
**App Name:** Showpass
**Bundle ID:** com.showpass.swift
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1422040696">1422040696</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/showpass/id1422040696?mt=8&uo=4">https://itunes.apple.com/us/app/showpass/id1422040696?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Up In Code Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/up-in-code-inc/id570984178?uo=4">© Up In Code Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/a0/6c/60/a06c60fb-b4ff-65c6-f91e-3693698f94fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/48317772-69d43d80-e5f7-11e8-873f-0c9a31b9b222.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/48317772-69d43d80-e5f7-11e8-873f-0c9a31b9b222.png)
https://user-images.githubusercontent.com/20930745/48317772-69d43d80-e5f7-11e8-873f-0c9a31b9b222.png

Source:
https://user-images.githubusercontent.com/20930745/48317776-7bb5e080-e5f7-11e8-9487-3fde85dcd90b.png
