### ISSUE TITLE
Better Day: A Complication

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10009]
**App Name:** Better Day: A Complication
**Bundle ID:** net.panchromatic.BetterDay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1052023515">1052023515</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/better-day-a-complication/id1052023515?mt=8&uo=4">https://itunes.apple.com/us/app/better-day-a-complication/id1052023515?mt=8&uo=4</a>
**App Version:** 5.10
**Seller:** Panchromatic, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/panchromatic-llc/id324461458?uo=4">© Panchromatic, LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/ea/77/01/ea77019f-9cf6-414b-2e5e-affbc726b52f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/48662556-f3ff2480-ea83-11e8-863c-09b17f050914.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/48662556-f3ff2480-ea83-11e8-863c-09b17f050914.png)
https://user-images.githubusercontent.com/20930745/48662556-f3ff2480-ea83-11e8-863c-09b17f050914.png

Source:
https://user-images.githubusercontent.com/20930745/48662571-0c6f3f00-ea84-11e8-94ae-0fc0d293eb44.png
