### ISSUE TITLE
unc0ver

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#10015]
**App Name:** unc0ver
 **Bundle ID:** science.xnu.undecimus
 **Version:** 2.0.0
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://raw.githubusercontent.com/pwn20wndstuff/Undecimus/master/Undecimus/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60%403x.png" width="180" height="180" />
 **Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49683238-8f067f80-fac1-11e8-9aaf-84e417db574d.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49683238-8f067f80-fac1-11e8-9aaf-84e417db574d.png)
https://user-images.githubusercontent.com/2068130/49683238-8f067f80-fac1-11e8-9aaf-84e417db574d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/49683243-a04f8c00-fac1-11e8-933c-7b1b0908fec4.png
