### ISSUE TITLE
Monitor for Transmission

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#10016]
**App Name:** Monitor for Transmission
 **Bundle ID:** xyz.rnelson.Transmonitor
 **Version:** 3.0.5
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/3f/82/cc/3f82cc0f-b96a-0ef6-8622-eb9427248b0b/source/350x350bb.jpg" width="180" height="180" />
 **Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49683441-6b453880-fac5-11e8-8671-8b34dd37cbe4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49683441-6b453880-fac5-11e8-8671-8b34dd37cbe4.png)
https://user-images.githubusercontent.com/2068130/49683441-6b453880-fac5-11e8-8671-8b34dd37cbe4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/49683450-7ac48180-fac5-11e8-9d15-f9e7a932ecdc.png
