### ISSUE TITLE
Visits

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10018]
**App Name:** Visits
**Bundle ID:** com.fusionengineeringtech.Visits
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1404263866">1404263866</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/visits/id1404263866?mt=8&uo=4">https://itunes.apple.com/us/app/visits/id1404263866?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Rohan Merchant
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rohan-merchant/id1233002961?uo=4">© Rohan Merchant</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/ec/20/ac/ec20acdf-4a66-6343-d33a-9f4c4e16a5e9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49686959-6d76b980-fafc-11e8-825d-7db7fdff5695.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49686959-6d76b980-fafc-11e8-825d-7db7fdff5695.png)
https://user-images.githubusercontent.com/2068130/49686959-6d76b980-fafc-11e8-825d-7db7fdff5695.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/49686964-7d8e9900-fafc-11e8-9b28-5427321d4d72.png
