### ISSUE TITLE
GitHawk for GitHub

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10019]
**App Name:** GitHawk for GitHub
**Bundle ID:** com.whoisryannystrom.freetime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1252320249">1252320249</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/githawk-for-github/id1252320249?mt=8&uo=4">https://itunes.apple.com/us/app/githawk-for-github/id1252320249?mt=8&uo=4</a>
**App Version:** 1.25.0
**Seller:** Ryan Nystrom
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ryan-nystrom/id517642218?uo=4">© Ryan Nystrom</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/84/44/e4/8444e471-7b1a-f3a6-76c5-b0e5f9d5ab8c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49687513-47edae00-fb04-11e8-8a44-00a68172e9af.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49687513-47edae00-fb04-11e8-8a44-00a68172e9af.png)
https://user-images.githubusercontent.com/2068130/49687513-47edae00-fb04-11e8-8a44-00a68172e9af.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/49687521-5a67e780-fb04-11e8-8a23-bc508f644b10.png
