### ISSUE TITLE
QR Code Reader - QR Scanner

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#10017]
**App Name:** QR Code Reader - QR Scanner
**Bundle ID:** com.lzxapps.free.f2.Scanner6
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1107903948">1107903948</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qr-code-reader-qr-scanner/id1107903948?mt=8&uo=4">https://itunes.apple.com/us/app/qr-code-reader-qr-scanner/id1107903948?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** wang haiwen
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lzx-apps/id440669745?uo=4">© LZX Apps</a>
**Supported Devices:** iPhone4-iPhone4, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/10/7a/a2/107aa2de-8002-d1bd-037e-ef7f4160ae74/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49683039-caec1580-fabe-11e8-93cc-9b15540ff456.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49683039-caec1580-fabe-11e8-93cc-9b15540ff456.png)
https://user-images.githubusercontent.com/2068130/49683039-caec1580-fabe-11e8-93cc-9b15540ff456.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/49683042-df301280-fabe-11e8-84f9-8e20db19b735.png
