### ISSUE TITLE
SkyLab Photo Editor

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#10029]
**App Name:** SkyLab Photo Editor
**Bundle ID:** com.brainfevermedia.skylab
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1084234960">1084234960</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skylab-photo-editor/id1084234960?mt=8&uo=4">https://itunes.apple.com/us/app/skylab-photo-editor/id1084234960?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** James Grote
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/brainfevermedia/id338517204?uo=4">© BrainFeverMedia</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/f9/c3/a7/f9c3a742-f9b1-7c78-4719-501a7f47c89d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/49695277-078c3f80-fb99-11e8-91a5-38dc2d7b75cf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/49695277-078c3f80-fb99-11e8-91a5-38dc2d7b75cf.png)
https://user-images.githubusercontent.com/20930745/49695277-078c3f80-fb99-11e8-91a5-38dc2d7b75cf.png

Source:
https://user-images.githubusercontent.com/20930745/49695290-27236800-fb99-11e8-8e56-339b9c0cf025.png
