### ISSUE TITLE
i-bank pass

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#10022]
**App Name:** i-bank pass
**Bundle ID:** gr.ibank.ibankpass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1105809860">1105809860</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/i-bank-pass/id1105809860?mt=8&uo=4">https://itunes.apple.com/us/app/i-bank-pass/id1105809860?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** National Bank of Greece S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/national-bank-of-greece-s-a/id342152892?uo=4">© National Bank Of Greece S.A.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple127/v4/ec/21/2f/ec212f6f-3299-75b4-81bd-7d13ee731250/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/49695592-c0ed1400-fb9d-11e8-9d94-0d17c1a7b263.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/49695592-c0ed1400-fb9d-11e8-9d94-0d17c1a7b263.png)
https://user-images.githubusercontent.com/20930745/49695592-c0ed1400-fb9d-11e8-9d94-0d17c1a7b263.png

Source:
https://user-images.githubusercontent.com/20930745/49695595-c3e80480-fb9d-11e8-80e9-9540cd05ef7c.png)
