### ISSUE TITLE
Tela GBA

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#10026]
**App Name:** Tela GBA
 **Bundle ID:** com.telaaedifex.TELAGBA
 **Version:** 2.1.7
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://telaaedifex.com/apps/wp-content/uploads/2017/10/telagba-512-300x300.png" width="180" height="180" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/49695400-d01e9280-fb9a-11e8-9da0-2e8e3a270cde.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/49695400-d01e9280-fb9a-11e8-9da0-2e8e3a270cde.png)
https://user-images.githubusercontent.com/20930745/49695400-d01e9280-fb9a-11e8-9da0-2e8e3a270cde.png

Source:
https://user-images.githubusercontent.com/20930745/49695408-e62c5300-fb9a-11e8-843e-fb6ea0b27e8a.png

**Comment by 2Qt2beStr8** [comment]
with roundet corners (but i think it Looks better without)

![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/49695446-8edab280-fb9b-11e8-9a37-da7b87cdfe6b.png)
https://user-images.githubusercontent.com/20930745/49695446-8edab280-fb9b-11e8-9a37-da7b87cdfe6b.png

Source:
https://user-images.githubusercontent.com/20930745/49695455-a619a000-fb9b-11e8-8a51-b99cd05b17c6.png
