### ISSUE TITLE
Mobile Flight for Betaflight

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#10028]
**App Name:** Mobile Flight for Betaflight
**Bundle ID:** com.flyinghead.MobileCleanflight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1079191425">1079191425</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobile-flight-for-betaflight/id1079191425?mt=8&uo=4">https://itunes.apple.com/us/app/mobile-flight-for-betaflight/id1079191425?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** Raphael Jean-Leconte
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/raphael-jean-leconte/id1079191424?uo=4">© Raphael Jean-Leconte</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/c9/2e/b3/c92eb3dd-1a79-db90-0689-86aaca3694eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/54083003-4a87bb80-431e-11e9-9d15-247df25d07af.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/54083003-4a87bb80-431e-11e9-9d15-247df25d07af.png)
https://user-images.githubusercontent.com/2068130/54083003-4a87bb80-431e-11e9-9d15-247df25d07af.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/54083013-60957c00-431e-11e9-8a44-16987b489efa.png
