### ISSUE TITLE
TETRIS®[bv]

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1002]
**App Name:** TETRIS®
**Bundle ID:** com.ea.tetris2011.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=480807857">480807857</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/tetris/id480807857?mt=8&uo=4">https://itunes.apple.com/gb/app/tetris/id480807857?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/03/4e/3c/034e3c7d-b879-ab89-b81f-2162b5d0c838/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20276864/884d5dfa-aa9e-11e6-930c-5ff70ad26a72.png)

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8 .
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20276864/884d5dfa-aa9e-11e6-930c-5ff70ad26a72.png)
https://cloud.githubusercontent.com/assets/20930745/20276864/884d5dfa-aa9e-11e6-930c-5ff70ad26a72.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/20930745/20276881/93d4389c-aa9e-11e6-8814-47898a0a1a22.png
