### ISSUE TITLE
Coderx for GitHub

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10020]
**App Name:** Coderx for GitHub
**Bundle ID:** com.derekcoder.GithubClient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1371929193">1371929193</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/coderx-for-github/id1371929193?uo=4">https://apps.apple.com/us/app/coderx-for-github/id1371929193?uo=4</a>
**App Version:** 3.0
**Seller:** dengfeng zhou
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dengfeng-zhou/id1153535935?uo=4">© dengfeng zhou</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/0c/80/87/0c8087b1-c31f-1226-6f6f-be7230bc0c88/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59296130-7dc34900-8c85-11e9-9904-0d5a74c77868.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49687424-c0ec0600-fb02-11e8-9844-51575a6f6afc.png)
https://user-images.githubusercontent.com/2068130/49687424-c0ec0600-fb02-11e8-9844-51575a6f6afc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/49687432-cfd2b880-fb02-11e8-9b06-66615f4ab8ae.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Coderx for GitHub
**Bundle ID:** com.derekcoder.GithubClient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1371929193">1371929193</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/coderx-for-github/id1371929193?uo=4">https://apps.apple.com/us/app/coderx-for-github/id1371929193?uo=4</a>
**App Version:** 3.0
**Seller:** dengfeng zhou
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dengfeng-zhou/id1153535935?uo=4">© dengfeng zhou</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/0c/80/87/0c8087b1-c31f-1226-6f6f-be7230bc0c88/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59296130-7dc34900-8c85-11e9-9904-0d5a74c77868.png)
https://user-images.githubusercontent.com/20930745/59296130-7dc34900-8c85-11e9-9904-0d5a74c77868.png

Source:
https://user-images.githubusercontent.com/20930745/59296132-7f8d0c80-8c85-11e9-9aec-23d4e26b5de0.png
