### ISSUE TITLE
Superimpose Studio-Cut out,mix

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#10027]
**App Name:** Superimpose Studio-Cut out,mix
**Bundle ID:** net.kaleidoscope.superimpose
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=730280555">730280555</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/superimpose-studio-cut-out-mix/id730280555?mt=8&uo=4">https://itunes.apple.com/us/app/superimpose-studio-cut-out-mix/id730280555?mt=8&uo=4</a>
**App Version:** 2.5.9
**Seller:** KALEIDOSCOPE Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kaleidoscope-inc/id730280558?uo=4">© KALEIDOSCOPE Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/64/4d/81/644d81ec-625d-41ed-a502-9ee19e8268e9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/49695345-14f5f980-fb9a-11e8-87ca-a059e7452813.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/49695345-14f5f980-fb9a-11e8-87ca-a059e7452813.png)
https://user-images.githubusercontent.com/20930745/49695345-14f5f980-fb9a-11e8-87ca-a059e7452813.png

Source:
https://user-images.githubusercontent.com/20930745/49695360-2b03ba00-fb9a-11e8-99a2-3ba4b701a44e.png
