### ISSUE TITLE
Πρόγραμμα τηλεόρασης

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#10021]
**App Name:** Πρόγραμμα τηλεόρασης
**Bundle ID:** com.nop.TvGuide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1341326352">1341326352</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%CF%80%CF%81%CF%8C%CE%B3%CF%81%CE%B1%CE%BC%CE%BC%CE%B1-%CF%84%CE%B7%CE%BB%CE%B5%CF%8C%CF%81%CE%B1%CF%83%CE%B7%CF%82/id1341326352?mt=8&uo=4">https://itunes.apple.com/us/app/%CF%80%CF%81%CF%8C%CE%B3%CF%81%CE%B1%CE%BC%CE%BC%CE%B1-%CF%84%CE%B7%CE%BB%CE%B5%CF%8C%CF%81%CE%B1%CF%83%CE%B7%CF%82/id1341326352?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** CarrotBits IKE
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/carrotbits-ike/id476137372?uo=4">© CarrotBits IKE</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/c2/25/1a/c2251ad6-c738-2f6b-c222-ee579bba7ca4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50560746-2c8d5180-0d04-11e9-8f39-8b6331d6e2db.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50560746-2c8d5180-0d04-11e9-8f39-8b6331d6e2db.png)
https://user-images.githubusercontent.com/20930745/50560746-2c8d5180-0d04-11e9-8f39-8b6331d6e2db.png

Source:
![tvguide](https://user-images.githubusercontent.com/20930745/50560747-2e571500-0d04-11e9-84d4-12e4f55a2730.png)
