### ISSUE TITLE
20 Minuten (CH)

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1003]
**App Name:** 20 Minuten (CH)
**Bundle ID:** com.yourcompany.20minutes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=285688859">285688859</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/20-minuten-ch/id285688859?mt=8&uo=4">https://itunes.apple.com/us/app/20-minuten-ch/id285688859?mt=8&uo=4</a>
**App Version:** 11.0.4
**Seller:** streamboat
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/20-minuten/id285688862?uo=4>© 20 Minuten</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple42/v4/bf/29/9a/bf299aa6-bfa2-81b6-683b-ae741b57c85d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19286395/cc1596f8-8ffd-11e6-8c71-a48faecf3224.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19286195/0a7b70bc-8ffd-11e6-89d5-cd4622490d0b.png)
https://cloud.githubusercontent.com/assets/20930745/19286195/0a7b70bc-8ffd-11e6-89d5-cd4622490d0b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19286207/1baa211c-8ffd-11e6-9094-5dc912c1eb7b.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19286395/cc1596f8-8ffd-11e6-8c71-a48faecf3224.png)
https://cloud.githubusercontent.com/assets/20930745/19286395/cc1596f8-8ffd-11e6-8c71-a48faecf3224.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19286407/dc28f2e2-8ffd-11e6-85f4-7bdca300a4ff.png
