### ISSUE TITLE
bundleIQ

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10034]
**App Name:** bundleIQ
**Bundle ID:** co.bnotes.BNotesApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1348329777">1348329777</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bundleiq/id1348329777?uo=4">https://apps.apple.com/us/app/bundleiq/id1348329777?uo=4</a>
**App Version:** 2.4.0
**Seller:** BNotes LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bnotes-llc/id1348329776?uo=4">© BNotes LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/2d/e3/1a/2de31a7f-2265-2bf5-3a0c-db0fe5f1426d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73614631-38cb9880-4601-11ea-9e61-a1074432a6fb.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/50363668-ecdca200-056c-11e9-9d0c-ad5e5d7cdfcd.png)
https://user-images.githubusercontent.com/2068130/50363668-ecdca200-056c-11e9-9d0c-ad5e5d7cdfcd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/50363679-fbc35480-056c-11e9-8381-fdf6cfe52df2.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** bundleIQ
**Bundle ID:** co.bnotes.BNotesApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1348329777">1348329777</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bundleiq/id1348329777?uo=4">https://apps.apple.com/us/app/bundleiq/id1348329777?uo=4</a>
**App Version:** 2.4.0
**Seller:** BNotes LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bnotes-llc/id1348329776?uo=4">© BNotes LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/2d/e3/1a/2de31a7f-2265-2bf5-3a0c-db0fe5f1426d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73614631-38cb9880-4601-11ea-9e61-a1074432a6fb.png)
https://user-images.githubusercontent.com/2068130/73614631-38cb9880-4601-11ea-9e61-a1074432a6fb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73614636-4719b480-4601-11ea-85df-f6d5694e6535.png
