### ISSUE TITLE
Seated: Rewards for Dining Out

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10037]
**App Name:** Seated: Rewards for Dining Out
**Bundle ID:** com.voco
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1031760854">1031760854</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/seated-rewards-for-dining-out/id1031760854?mt=8&uo=4">https://itunes.apple.com/us/app/seated-rewards-for-dining-out/id1031760854?mt=8&uo=4</a>
**App Version:** 2.13.2
**Seller:** Youpik Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vocochat/id958588664?uo=4">© vocochat</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/9a/05/8c/9a058cef-ebe0-e797-866d-f91b6013bfb6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551776-dcbc7500-0c86-11e9-88ef-f7913261415c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551776-dcbc7500-0c86-11e9-88ef-f7913261415c.png)
https://user-images.githubusercontent.com/20930745/50551776-dcbc7500-0c86-11e9-88ef-f7913261415c.png

Source:
https://user-images.githubusercontent.com/20930745/50551777-df1ecf00-0c86-11e9-811d-bfc7e852d68e.png
