### ISSUE TITLE
Polar Beat: Run & Fitness

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#10031]
**App Name:** Polar Beat: Run & Fitness
**Bundle ID:** fi.polar.polarbeat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555252645">555252645</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/polar-beat-run-fitness/id555252645?mt=8&uo=4">https://itunes.apple.com/us/app/polar-beat-run-fitness/id555252645?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Polar Electro Oy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/polar-electro/id532468555?uo=4">© Polar Electro</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/dd/e9/4c/dde94cdb-902c-8c1a-d6b5-9deb27d28a0e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/50364478-5f02b600-0570-11e9-8d29-214476a90a5d.png)

**Comment by dreamnet** [comment]
@ivanov007 Can we use the same icon as for #10030 ?

**Comment by ivanov007** [comment]
@dreamnet sure, since they show each one's name they can have the same icon
