### ISSUE TITLE
WesternUnion US Money Transfer

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10036]
**App Name:** WesternUnion US Money Transfer
**Bundle ID:** com.westernunion.mtapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424716908">424716908</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/westernunion-us-money-transfer/id424716908?mt=8&uo=4">https://itunes.apple.com/us/app/westernunion-us-money-transfer/id424716908?mt=8&uo=4</a>
**App Version:** 5.8
**Seller:** The Western Union Company
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/western-union-holdings-inc/id424716911?uo=4">© Western Union Holdings, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/d1/05/bf/d105bfd6-83a3-cf43-e337-4df2c38e9af5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50561022-da99fb00-0d06-11e9-8685-9e1b931a800d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50561022-da99fb00-0d06-11e9-8685-9e1b931a800d.png)
https://user-images.githubusercontent.com/20930745/50561022-da99fb00-0d06-11e9-8685-9e1b931a800d.png

Source:
https://user-images.githubusercontent.com/20930745/50561024-dc63be80-0d06-11e9-92f0-98f0a53714f9.png
