### ISSUE TITLE
Tim Hortons

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10038]
**App Name:** Tim Hortons
**Bundle ID:** com.rbi.TimHortons
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1143883086">1143883086</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tim-hortons/id1143883086?mt=8&uo=4">https://itunes.apple.com/us/app/tim-hortons/id1143883086?mt=8&uo=4</a>
**App Version:** 2.0.6
**Seller:** Tim Hortons
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tim-hortons/id483413331?mt=8&uo=4">© Tim Hortons</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/d5/52/aa/d552aa2a-8df8-7e52-3b2b-7a34db3c2223/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58764119-e151c600-8563-11e9-8fd7-956e2109e006.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551750-4ee08a00-0c86-11e9-843e-61e2dafce044.png)
https://user-images.githubusercontent.com/20930745/50551750-4ee08a00-0c86-11e9-843e-61e2dafce044.png

https://user-images.githubusercontent.com/20930745/50551744-26f12680-0c86-11e9-8a0f-2e97d4fe1dc2.png

**Comment by XPEric** [comment]
Needs icon update.

[DUPLICATE of #10038]
**App Name:** Tim Hortons
**Bundle ID:** com.rbi.TimHortons
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1143883086">1143883086</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tim-hortons/id1143883086?mt=8&uo=4">https://itunes.apple.com/us/app/tim-hortons/id1143883086?mt=8&uo=4</a>
**App Version:** 2.0.6
**Seller:** Tim Hortons
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tim-hortons/id483413331?mt=8&uo=4">© Tim Hortons</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/d5/52/aa/d552aa2a-8df8-7e52-3b2b-7a34db3c2223/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment]
![tyt](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58762779-433d0c00-8521-11e9-8b83-c94dcb6d4ec0.png)
https://user-images.githubusercontent.com/2313873/58762779-433d0c00-8521-11e9-8b83-c94dcb6d4ec0.png

___
Source:
https://user-images.githubusercontent.com/2313873/58762777-3c15fe00-8521-11e9-9e55-13d4b3c6d339.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58764119-e151c600-8563-11e9-8fd7-956e2109e006.png)
https://user-images.githubusercontent.com/2068130/58764119-e151c600-8563-11e9-8fd7-956e2109e006.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58764128-f595c300-8563-11e9-8609-e0d7a84b037c.png
