### ISSUE TITLE
Plan - Organize your Life

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10035]
**App Name:** Plan - Organize your Life
**Bundle ID:** co.getplan.Plan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1021427351">1021427351</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/plan-organize-your-life/id1021427351?mt=8&uo=4">https://itunes.apple.com/us/app/plan-organize-your-life/id1021427351?mt=8&uo=4</a>
**App Version:** 1.8.1
**Seller:** Plan, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/plan-inc/id927107707?uo=4">© Plan, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/4a/1e/cb/4a1ecb68-1a84-c924-def7-2300e1ced158/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/50363528-5a3c0300-056c-11e9-98aa-9c8e17b3d758.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/50363528-5a3c0300-056c-11e9-98aa-9c8e17b3d758.png)
https://user-images.githubusercontent.com/2068130/50363528-5a3c0300-056c-11e9-98aa-9c8e17b3d758.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/50363547-6aec7900-056c-11e9-8e49-99e56d37f708.png
