### ISSUE TITLE
Saks Fifth Avenue

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10039]
**App Name:** Saks Fifth Avenue
**Bundle ID:** com.saksfifthavenue.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=491507258">491507258</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/saks-fifth-avenue/id491507258?mt=8&uo=4">https://itunes.apple.com/us/app/saks-fifth-avenue/id491507258?mt=8&uo=4</a>
**App Version:** 6.3.4
**Seller:** Saks Fifth Avenue
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/saks-fifth-avenue/id472419792?uo=4">© Saks Fifth Avenue</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/d6/23/6a/d6236a1c-67c9-7b43-309f-f33c5c758c86/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551703-75ea8c00-0c85-11e9-98f9-e39f92b19604.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551703-75ea8c00-0c85-11e9-98f9-e39f92b19604.png)
https://user-images.githubusercontent.com/20930745/50551703-75ea8c00-0c85-11e9-98f9-e39f92b19604.png

Source:
https://user-images.githubusercontent.com/20930745/50551704-77b44f80-0c85-11e9-89b7-fc8135d877fc.png
