### ISSUE TITLE
Minibar Delivery

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10040]
**App Name:** Minibar Delivery
**Bundle ID:** com.minibar.minibarapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=720850888">720850888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minibar-delivery/id720850888?mt=8&uo=4">https://itunes.apple.com/us/app/minibar-delivery/id720850888?mt=8&uo=4</a>
**App Version:** 3.3.9
**Seller:** LLJ Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/minibar/id720850891?uo=4">© Minibar</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/e4/2a/a9/e42aa960-8a52-0b85-6608-47c0189fd1ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551662-c7dee200-0c84-11e9-9afa-9b0031eef7c0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551662-c7dee200-0c84-11e9-9afa-9b0031eef7c0.png)
https://user-images.githubusercontent.com/20930745/50551662-c7dee200-0c84-11e9-9afa-9b0031eef7c0.png

Source:
https://user-images.githubusercontent.com/20930745/50551663-c9100f00-0c84-11e9-9750-d12bd440faa6.png
