### ISSUE TITLE
Verizon My Fios

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10042]
**App Name:** Verizon My Fios
**Bundle ID:** com.verizon.ams.myvzhomeacct
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476394945">476394945</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/verizon-my-fios/id476394945?mt=8&uo=4">https://itunes.apple.com/us/app/verizon-my-fios/id476394945?mt=8&uo=4</a>
**App Version:** 5.18.5
**Seller:** Verizon Services Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/verizon-services-corporation/id663838713?uo=4">© Verizon Services Corporation</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/4f/4f/cc/4f4fccc8-d557-3130-272d-4031529feafe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551564-ce6c5a00-0c82-11e9-84cd-cf9e329080df.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551564-ce6c5a00-0c82-11e9-84cd-cf9e329080df.png)
https://user-images.githubusercontent.com/20930745/50551564-ce6c5a00-0c82-11e9-84cd-cf9e329080df.png

Source:
https://user-images.githubusercontent.com/20930745/50551565-d0361d80-0c82-11e9-942d-114e899ca2b2.png
