### ISSUE TITLE
Home Chef: Meal Kit Delivery

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10046]
**App Name:** Home Chef: Meal Kit Delivery
**Bundle ID:** com.homechef.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=994918972">994918972</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/home-chef-meal-kit-delivery/id994918972?mt=8&uo=4">https://itunes.apple.com/us/app/home-chef-meal-kit-delivery/id994918972?mt=8&uo=4</a>
**App Version:** 3.6.0
**Seller:** Relish Labs LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/home-chef/id994918971?uo=4">© Home Chef</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/41/8e/b2/418eb207-a4b3-5d74-f593-dd6c039600eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50845517-53cfc880-136d-11e9-9c4b-1728140ed067.png)

**Comment by XPEric** [comment]
![homechef](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/50730196-46200600-1115-11e9-8576-069274725cd0.png)
https://user-images.githubusercontent.com/2313873/50730196-46200600-1115-11e9-8576-069274725cd0.png

___
Source:
https://user-images.githubusercontent.com/2313873/50730197-4fa96e00-1115-11e9-81aa-6597216c8e13.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50845517-53cfc880-136d-11e9-9c4b-1728140ed067.png)
https://user-images.githubusercontent.com/20930745/50845517-53cfc880-136d-11e9-9c4b-1728140ed067.png

Source:
https://user-images.githubusercontent.com/20930745/50845527-592d1300-136d-11e9-8546-215c79f3d147.png
