### ISSUE TITLE
Stop & Shop

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10041]
**App Name:** Stop & Shop
**Bundle ID:** com.stopandshop.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=423801622">423801622</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stop-shop/id423801622?mt=8&uo=4">https://itunes.apple.com/us/app/stop-shop/id423801622?mt=8&uo=4</a>
**App Version:** 6.7.0
**Seller:** The Stop & Shop Supermarket Company LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-stop-shop-supermarket-company/id423801625?uo=4">© The Stop & Shop Supermarket Company</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/6f/ea/13/6fea13a8-9e35-fd32-3d0a-c95767482a14/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551611-0d4edf80-0c84-11e9-8ba7-18d9d04cba68.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551589-91549780-0c83-11e9-81f9-23ec80794fb9.png)
https://user-images.githubusercontent.com/20930745/50551589-91549780-0c83-11e9-81f9-23ec80794fb9.png

Source:
https://user-images.githubusercontent.com/20930745/50551590-9285c480-0c83-11e9-8a41-7a4f50df9c73.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551611-0d4edf80-0c84-11e9-8ba7-18d9d04cba68.png)
https://user-images.githubusercontent.com/20930745/50551611-0d4edf80-0c84-11e9-8ba7-18d9d04cba68.png

Source:
https://user-images.githubusercontent.com/20930745/50551613-0fb13980-0c84-11e9-9c3b-ac7d49dedbb9.png
