### ISSUE TITLE
Shazam Encore

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1005]
**App Name:** Shazam Encore
**Bundle ID:** com.shazam.encore.Shazam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=337288863">337288863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shazam-encore/id337288863?mt=8&uo=4">https://itunes.apple.com/us/app/shazam-encore/id337288863?mt=8&uo=4</a>
**App Version:** 10.1.0
**Seller:** Shazam Entertainment Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shazam-entertainment-ltd./id284993479?uo=4>© Shazam Entertainment Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/a3/9c/ed/a39ced8a-ee83-383f-a43f-8778fe75b187/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19495239/de63859c-9582-11e6-8e40-e613aa6eb7fd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19495239/de63859c-9582-11e6-8e40-e613aa6eb7fd.png)
https://cloud.githubusercontent.com/assets/20930745/19495239/de63859c-9582-11e6-8e40-e613aa6eb7fd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19495300/1e8ae250-9583-11e6-8058-129a25ae5d41.png
