### ISSUE TITLE
9292

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1006]
**App Name:** 9292
**Bundle ID:** nl.9292.9292
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=556557690">556557690</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/9292/id556557690?mt=8&uo=4">https://itunes.apple.com/us/app/9292/id556557690?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** Reisinformatiegroep B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/9292/id556557693?uo=4>© 9292</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/7b/9b/a7/7b9ba763-ca51-d9d0-b8d4-a5b23723baee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19494760/dfbacd08-9580-11e6-84f6-f9ca43d45068.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19494760/dfbacd08-9580-11e6-84f6-f9ca43d45068.png)
https://cloud.githubusercontent.com/assets/20930745/19494760/dfbacd08-9580-11e6-84f6-f9ca43d45068.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19494822/2a051be8-9581-11e6-8b30-a47c2a0d9114.png
