### ISSUE TITLE
PayMaya

### ISSUE THREAD

**Issue by super-lurker** [glasklart/hd#10061]
**App Name:** PayMaya
**Bundle ID:** com.paymaya.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=991673877">991673877</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paymaya/id991673877?mt=8&uo=4">https://itunes.apple.com/us/app/paymaya/id991673877?mt=8&uo=4</a>
**App Version:** 1.25.1
**Seller:** PayMaya Philippines, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/paymaya-philippines-inc/id991673876?mt=8&uo=4">© PayMaya Philippines, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/84/c8/40/84c8409b-17f7-fe9e-d235-21748cd9462b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54087343-2b0a8600-4352-11e9-84e1-9b19ffeeb352.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54087343-2b0a8600-4352-11e9-84e1-9b19ffeeb352.png)
(https://user-images.githubusercontent.com/20930745/54087343-2b0a8600-4352-11e9-84e1-9b19ffeeb352.png

Source:
https://user-images.githubusercontent.com/20930745/54087344-2d6ce000-4352-11e9-8360-79e898964e78.png
