### ISSUE TITLE
lichess • Online Chess

### ISSUE THREAD

**Issue by super-lurker** [glasklart/hd#10062]
**App Name:** lichess • Online Chess
**Bundle ID:** org.lichess.mobileapp.official
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=968371784">968371784</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lichess-online-chess/id968371784?mt=8&uo=4">https://itunes.apple.com/us/app/lichess-online-chess/id968371784?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** thibault duplessis
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/thibault-duplessis/id968371783?mt=8&uo=4">© thibault duplessis</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple115/v4/6f/da/5d/6fda5df4-b1f5-3e0a-e17a-a35eecaa731f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54087422-09f66500-4353-11e9-9d5e-6d712a9ac583.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54087422-09f66500-4353-11e9-9d5e-6d712a9ac583.png)
https://user-images.githubusercontent.com/20930745/54087422-09f66500-4353-11e9-9d5e-6d712a9ac583.png

Source:
https://user-images.githubusercontent.com/20930745/54087425-0b279200-4353-11e9-8c4c-6135b93533ed.png
