### ISSUE TITLE
Death Road to Canada

### ISSUE THREAD

**Issue by super-lurker** [glasklart/hd#10067]
**App Name:** Death Road to Canada
**Bundle ID:** dr2c.rocketcat.com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1128464707">1128464707</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/death-road-to-canada/id1128464707?mt=8&uo=4">https://itunes.apple.com/us/app/death-road-to-canada/id1128464707?mt=8&uo=4</a>
**App Version:** 1.26
**Seller:** Rocketcat LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rocketcat-llc/id305576988?mt=8&uo=4">© Rocketcat LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/bb/c4/c2/bbc4c248-0977-58bf-7b38-38f160efc6a6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58735287-3a054f80-83fa-11e9-9759-22ceb8ae25cd.png)

**Comment by dreamnet** [comment]
❓ 

![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58735287-3a054f80-83fa-11e9-9759-22ceb8ae25cd.png)
https://user-images.githubusercontent.com/2068130/58735287-3a054f80-83fa-11e9-9759-22ceb8ae25cd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58735317-4f7a7980-83fa-11e9-9adc-8f7e06e80dfe.png
