### ISSUE TITLE
Igloo IRC

### ISSUE THREAD

**Issue by super-lurker** [glasklart/hd#10064]
**App Name:** Igloo IRC
**Bundle ID:** com.jordankoch.igloo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1331074069">1331074069</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/igloo-irc/id1331074069?mt=8&uo=4">https://itunes.apple.com/us/app/igloo-irc/id1331074069?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Jordan Koch
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jordan-koch/id1037652122?mt=8&uo=4">© Jordan Koch</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/e6/48/52/e64852b7-525e-3764-df02-f2c296cfdb85/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54087634-ff3ccf80-4354-11e9-9016-1955b54724ac.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54087634-ff3ccf80-4354-11e9-9016-1955b54724ac.png)
https://user-images.githubusercontent.com/20930745/54087634-ff3ccf80-4354-11e9-9016-1955b54724ac.png

Source:
https://user-images.githubusercontent.com/20930745/54087637-01069300-4355-11e9-9d72-be9ce733ad3f.png
