### ISSUE TITLE
Lazada - #1 Online Shopping

### ISSUE THREAD

**Issue by super-lurker** [glasklart/hd#10068]
**App Name:** Lazada - #1 Online Shopping
**Bundle ID:** com.LazadaSEA.Lazada
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=785385147">785385147</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lazada-1-online-shopping/id785385147?mt=8&uo=4">https://itunes.apple.com/us/app/lazada-1-online-shopping/id785385147?mt=8&uo=4</a>
**App Version:** 6.28.2
**Seller:** Lazada Group GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lazada-group-gmbh/id785385150?mt=8&uo=4">© Lazada Group GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/98/30/3b/98303b72-b5b8-a293-11a9-7ee7b50115f6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54423324-b1d3b000-4710-11e9-85b4-f9b7ec67b397.png)

**Comment by 2Qt2beStr8** [comment]
@super-lurker The App Name and the Title must be 100% identical. So please copy the complete App Name to Title

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54414507-a923af80-46f9-11e9-9f35-d0dc548fd2eb.png)
https://user-images.githubusercontent.com/20930745/54414507-a923af80-46f9-11e9-9f35-d0dc548fd2eb.png

Source:
https://user-images.githubusercontent.com/20930745/54414511-aa54dc80-46f9-11e9-9bc3-4a1296bbbe3e.png

**Comment by super-lurker** [comment]
> 
> 
> ![](https://camo.githubusercontent.com/1a85206f99a85bc8bb3f43e6178a8570b3cacfc6/68747470733a2f2f707265766965772e647265616d6e65742e61743f696d6167653d68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f32303933303734352f35343431343530372d61393233616638302d343666392d313165392d396633352d6430646335343866643265622e706e67)
> https://user-images.githubusercontent.com/20930745/54414507-a923af80-46f9-11e9-9f35-d0dc548fd2eb.png
> 
> Source:
> https://user-images.githubusercontent.com/20930745/54414511-aa54dc80-46f9-11e9-9bc3-4a1296bbbe3e.png

can you remove the border and the confetti? thanks 

> 
> 
> @super-lurker The App Name and the Title must be 100% identical. So please copy the complete App Name to Title

noted, thanks

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54423324-b1d3b000-4710-11e9-85b4-f9b7ec67b397.png)
https://user-images.githubusercontent.com/20930745/54423324-b1d3b000-4710-11e9-85b4-f9b7ec67b397.png

Source:
https://user-images.githubusercontent.com/20930745/54423325-b39d7380-4710-11e9-86d3-1eb78e0d55c4.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54423394-e2b3e500-4710-11e9-8ae4-19c50ec9efaa.png)
https://user-images.githubusercontent.com/20930745/54423394-e2b3e500-4710-11e9-8ae4-19c50ec9efaa.png

Source:
https://user-images.githubusercontent.com/20930745/54423398-e3e51200-4710-11e9-8a19-25add35139e2.png

**Comment by super-lurker** [comment]
> 
> 
> ![](https://camo.githubusercontent.com/89ab97ea055c8decdced965dfacdbc2a724001df/68747470733a2f2f707265766965772e647265616d6e65742e61743f696d6167653d68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f32303933303734352f35343432333332342d62316433623030302d343731302d313165392d383562342d6639623765633637623339372e706e67)
> https://user-images.githubusercontent.com/20930745/54423324-b1d3b000-4710-11e9-85b4-f9b7ec67b397.png
> 
> Source:
> https://user-images.githubusercontent.com/20930745/54423325-b39d7380-4710-11e9-86d3-1eb78e0d55c4.png

perfect, thanks
