### ISSUE TITLE
KyBook 3 Ebook Reader

### ISSUE THREAD

**Issue by super-lurker** [glasklart/hd#10063]
**App Name:** KyBook 3 Ebook Reader
**Bundle ID:** com.kolyvan.yar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1348198785">1348198785</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kybook-3-ebook-reader/id1348198785?mt=8&uo=4">https://itunes.apple.com/us/app/kybook-3-ebook-reader/id1348198785?mt=8&uo=4</a>
**App Version:** v0.7.8
**Seller:** Konstantin Bukreev
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/konstantin-bukreev/id547576207?mt=8&uo=4">© Konstantin Bukreev</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/e7/d3/90/e7d39090-eb7d-aa9f-2498-1504d83b8f1c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54087535-18914c00-4354-11e9-9065-23cbbbfc4deb.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54087535-18914c00-4354-11e9-9065-23cbbbfc4deb.png)
https://user-images.githubusercontent.com/20930745/54087535-18914c00-4354-11e9-9065-23cbbbfc4deb.png

Source:
https://user-images.githubusercontent.com/20930745/54087537-19c27900-4354-11e9-89bb-4ceaacba57ae.png
