### ISSUE TITLE
iFont: find, install any font!

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10060]
**App Name:** iFont: find, install any font!
**Bundle ID:** uk.co.codingcorner.iFont
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1173222289">1173222289</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ifont-find-install-any-font/id1173222289?mt=8&uo=4">https://itunes.apple.com/us/app/ifont-find-install-any-font/id1173222289?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** Coding Corner LLP
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/coding-corner-llp/id1161584321?mt=8&uo=4">© Coding Corner LLP</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/aa/4c/e3/aa4ce366-7fcd-d759-f487-61f1dfad5f6b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/54081815-633aa600-430b-11e9-9d13-becd92f62357.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/54081815-633aa600-430b-11e9-9d13-becd92f62357.png)
https://user-images.githubusercontent.com/2068130/54081815-633aa600-430b-11e9-9d13-becd92f62357.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/54081820-777ea300-430b-11e9-812c-27cb2e4a30e6.png
