### ISSUE TITLE
VPNHUB Unlimited Anonymous VPN

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10069]
**App Name:** VPNHUB Unlimited Anonymous VPN
**Bundle ID:** com.appatomic.vpnhub
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1353525004">1353525004</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vpnhub-unlimited-anonymous-vpn/id1353525004?mt=8&uo=4">https://itunes.apple.com/us/app/vpnhub-unlimited-anonymous-vpn/id1353525004?mt=8&uo=4</a>
**App Version:** 1.12
**Seller:** APPATOMIC LIMITED
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/appatomic/id901888718?mt=8&uo=4">© AppAtomic</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/07/75/30/07753080-c5b2-5af7-0582-2304370dc481/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54451189-8ffb1d00-4752-11e9-94ce-20a01e926020.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54451189-8ffb1d00-4752-11e9-94ce-20a01e926020.png)
https://user-images.githubusercontent.com/20930745/54451189-8ffb1d00-4752-11e9-94ce-20a01e926020.png

Source:
https://user-images.githubusercontent.com/20930745/54451190-912c4a00-4752-11e9-9af5-2832acdc0f91.png
