### ISSUE TITLE
Fortune 

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10065]
App Name: Fortune 
Bundle ID: com.nin9tyfour.fortune
Version: 1.4.4
iTunes ID: none (Cydia app)
Original Artwork:
<img src="https://user-images.githubusercontent.com/2068130/54863074-00520180-4d44-11e9-90ac-7f4cdfdfab04.png" width="180" height="180" />
Accepted Artwork:
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54087838-a589d480-4357-11e9-8fcf-5a230d595ead.png)

**Comment by 2Qt2beStr8** [comment]
![-large](https://user-images.githubusercontent.com/20930745/54087838-a589d480-4357-11e9-8fcf-5a230d595ead.png)
(https://user-images.githubusercontent.com/20930745/54087838-a589d480-4357-11e9-8fcf-5a230d595ead.png

Source:
https://user-images.githubusercontent.com/20930745/54087840-a884c500-4357-11e9-9734-cf972524576f.PNG

**Comment by 2Qt2beStr8** [comment]
i used a very bad artwork from the www. so the result is not perfekt

**Comment by super-lurker** [comment]
I've been lsearching in filza but i can find fortune icon, any tips on where to look?

**Comment by super-lurker** [comment]
![IMG_0085](https://user-images.githubusercontent.com/13076066/54099388-fc44ec00-43f3-11e9-8457-22f936289e28.PNG)

**Comment by dreamnet** [comment]
@super-lurker On your device... but I think for this one it's OK. @2Qt2beStr8 Good work! 👍
