### ISSUE TITLE
Yandex.Mail - Email App

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10078]
**App Name:** Yandex.Mail - Email App
**Bundle ID:** ru.yandex.mail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441785419">441785419</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex-mail-email-app/id441785419?mt=8&uo=4">https://itunes.apple.com/us/app/yandex-mail-email-app/id441785419?mt=8&uo=4</a>
**App Version:** 3.81.0
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yandex-llc/id308094652?mt=8&uo=4">© Yandex LLC</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/e4/68/25/e46825bf-b5a8-9ef3-203a-d6fdfd7ef378/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54535522-fbc9c980-498e-11e9-98b0-4e69c5d0d23c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54535522-fbc9c980-498e-11e9-98b0-4e69c5d0d23c.png)
https://user-images.githubusercontent.com/20930745/54535522-fbc9c980-498e-11e9-98b0-4e69c5d0d23c.png

Source:
https://user-images.githubusercontent.com/20930745/54535527-fd938d00-498e-11e9-87b6-54976f4d60e9.png
