### ISSUE TITLE
MUBI: Curated Cinema

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10071]
**App Name:** MUBI: Curated Cinema
**Bundle ID:** com.mubi.mubiapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=626148774">626148774</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mubi-curated-cinema/id626148774?mt=8&uo=4">https://itunes.apple.com/us/app/mubi-curated-cinema/id626148774?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** MUBI, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mubi-inc/id626148777?mt=8&uo=4">© MUBI, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/6c/9b/99/6c9b991e-29a0-4e41-b1e7-4c84a4e3c4e6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54452006-60e5ab00-4754-11e9-8ad7-94a61244b667.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54452006-60e5ab00-4754-11e9-8ad7-94a61244b667.png)
https://user-images.githubusercontent.com/20930745/54452006-60e5ab00-4754-11e9-8ad7-94a61244b667.png

Source:
https://user-images.githubusercontent.com/20930745/54452009-62af6e80-4754-11e9-9358-0bf46eaaea34.png
