### ISSUE TITLE
Turkish Airlines: Book Flights

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10073]
**App Name:** Turkish Airlines: Book Flights
**Bundle ID:** com.turkishairlines.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1283414961">1283414961</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/turkish-airlines-book-flights/id1283414961?mt=8&uo=4">https://itunes.apple.com/us/app/turkish-airlines-book-flights/id1283414961?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** Turkish Airlines
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/turkish-airlines/id436328805?mt=8&uo=4">© Turkish Airlines</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/7a/6e/53/7a6e537a-b775-2c75-c527-90af6c0d9176/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54511287-cf8f5800-4950-11e9-8190-2c1d14b8b64b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54511287-cf8f5800-4950-11e9-8190-2c1d14b8b64b.png)
https://user-images.githubusercontent.com/20930745/54511287-cf8f5800-4950-11e9-8190-2c1d14b8b64b.png

Source:
https://user-images.githubusercontent.com/20930745/54511292-d1591b80-4950-11e9-8e4b-30539baad5b6.png
