### ISSUE TITLE
Unroll.Me

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10074]
**App Name:** Unroll.Me
**Bundle ID:** com.unrollme.unrollapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1028103039">1028103039</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/unroll-me/id1028103039?mt=8&uo=4">https://itunes.apple.com/us/app/unroll-me/id1028103039?mt=8&uo=4</a>
**App Version:** 1.13.4
**Seller:** UNROLLME INC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/unroll-me/id1028103038?mt=8&uo=4">© Unroll.Me</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/4b/26/99/4b269975-47bc-38c2-c4f8-027fbdc193e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54536374-e5bd0880-4990-11e9-8524-b1a63a031a2f.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54536374-e5bd0880-4990-11e9-8524-b1a63a031a2f.png)
https://user-images.githubusercontent.com/20930745/54536374-e5bd0880-4990-11e9-8524-b1a63a031a2f.png

Source:
https://user-images.githubusercontent.com/20930745/54536388-ec4b8000-4990-11e9-8aa5-82658a83069a.png
