### ISSUE TITLE
MobilDeniz (DenizBank Mobil)

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10072]
**App Name:** MobilDeniz (DenizBank Mobil)
**Bundle ID:** com.denizbank.mobildeniz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1403334281">1403334281</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobildeniz-denizbank-mobil/id1403334281?mt=8&uo=4">https://itunes.apple.com/us/app/mobildeniz-denizbank-mobil/id1403334281?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Denizbank A.S.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/denizbank-a-%C5%9F/id434814150?mt=8&uo=4">© DenizBank A.Ş.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/95/b9/6f/95b96fd9-6f9c-94b9-601c-b6d152a6ebe2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54511083-0d3fb100-4950-11e9-96c2-8fd8de253744.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54511083-0d3fb100-4950-11e9-96c2-8fd8de253744.png)
https://user-images.githubusercontent.com/20930745/54511083-0d3fb100-4950-11e9-96c2-8fd8de253744.png

Source:
https://user-images.githubusercontent.com/20930745/54511086-0fa20b00-4950-11e9-8d3e-f021912fe036.png
