### ISSUE TITLE
Adobe Premiere Rush CC

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10079]
**App Name:** Adobe Premiere Rush CC
**Bundle ID:** com.adobe.rush
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1188753863">1188753863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-premiere-rush-cc/id1188753863?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-premiere-rush-cc/id1188753863?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/adobe/id331646274?mt=8&uo=4">© Adobe</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/66/db/86/66db862f-a4a7-95c1-ed69-86f810771c39/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54533660-fbc7ca80-498a-11e9-8c0d-02b722330d89.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54533660-fbc7ca80-498a-11e9-8c0d-02b722330d89.png)
(https://user-images.githubusercontent.com/20930745/54533660-fbc7ca80-498a-11e9-8c0d-02b722330d89.png

Source:
https://user-images.githubusercontent.com/20930745/54533663-fcf8f780-498a-11e9-9386-c51f57bf038e.png
