### ISSUE TITLE
puhutv

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10076]
**App Name:** puhutv
**Bundle ID:** com.vngrs.puhutvprod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1139761721">1139761721</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/puhutv/id1139761721?mt=8&uo=4">https://itunes.apple.com/us/app/puhutv/id1139761721?mt=8&uo=4</a>
**App Version:** 1.0.22
**Seller:** Dogus Dijital Hizmetler Anonim Sirketi
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/do%C4%9Fu%C5%9F-digital/id1137566906?mt=8&uo=4">© Doğuş Digital</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/2d/b4/08/2db40805-2b53-e327-8deb-53887b642bc4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54511848-850edb00-4952-11e9-9ef2-3f3826735d8e.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54511848-850edb00-4952-11e9-9ef2-3f3826735d8e.png)
https://user-images.githubusercontent.com/20930745/54511848-850edb00-4952-11e9-9ef2-3f3826735d8e.png

Source:
https://user-images.githubusercontent.com/20930745/54511849-86400800-4952-11e9-9c3f-624a6a9c14fb.png
