### ISSUE TITLE
99 reddits

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1007]
**App Name:** 99 reddits
**Bundle ID:** com.lensie.99reddits
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=474846610">474846610</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/99-reddits/id474846610?mt=8&uo=4">https://itunes.apple.com/us/app/99-reddits/id474846610?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** Amandeep Loomba
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lensie/id474846613?uo=4">© Lensie</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/eb/56/4a/eb564a40-07cd-9b92-5716-4e596537d668/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19964240/f672ba8c-a1c0-11e6-8154-6dabd2851891.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19964240/f672ba8c-a1c0-11e6-8154-6dabd2851891.png)
https://cloud.githubusercontent.com/assets/20930745/19964240/f672ba8c-a1c0-11e6-8154-6dabd2851891.png


Source:
https://cloud.githubusercontent.com/assets/20930745/19964267/17121eea-a1c1-11e6-90a9-e50e669d4b53.png
