### ISSUE TITLE
Yandex Browser

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10077]
**App Name:** Yandex Browser
**Bundle ID:** ru.yandex.mobile.search
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=483693909">483693909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex-browser/id483693909?mt=8&uo=4">https://itunes.apple.com/us/app/yandex-browser/id483693909?mt=8&uo=4</a>
**App Version:** 19.3.2.156
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yandex-llc/id308094652?mt=8&uo=4">© Yandex LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/d6/ae/75/d6ae750d-0a2e-d225-571a-19d7600fbccb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54512057-3b72c000-4953-11e9-946e-9ee61779cfa2.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54512057-3b72c000-4953-11e9-946e-9ee61779cfa2.png)
(https://user-images.githubusercontent.com/20930745/54512057-3b72c000-4953-11e9-946e-9ee61779cfa2.png

Source:
https://user-images.githubusercontent.com/20930745/54512061-3d3c8380-4953-11e9-9dcd-91c26b22d592.png
