### ISSUE TITLE
Skrill

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10070]
**App Name:** Skrill
**Bundle ID:** com.skrill.ios.SkrillPayments
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=718248239">718248239</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skrill/id718248239?mt=8&uo=4">https://itunes.apple.com/us/app/skrill/id718248239?mt=8&uo=4</a>
**App Version:** 3.7.0
**Seller:** Skrill Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/skrill-ltd/id718248242?mt=8&uo=4">© Skrill Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/97/bd/a5/97bda57c-0e8a-77c3-f0d5-17b3081d98d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54451557-5d055900-4753-11e9-8239-b2057cefb3a6.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54451557-5d055900-4753-11e9-8239-b2057cefb3a6.png)
https://user-images.githubusercontent.com/20930745/54451557-5d055900-4753-11e9-8239-b2057cefb3a6.png

Source:
https://user-images.githubusercontent.com/20930745/54451562-5e368600-4753-11e9-8617-13fd1bb3ba5a.png
