### ISSUE TITLE
バンドリ！ ガールズバンドパーティ！

### ISSUE THREAD

**Issue by randompasser** [glasklart/hd#10086]
**App Name:** バンドリ！ ガールズバンドパーティ！
**Bundle ID:** jp.co.craftegg.band
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1195834442">1195834442</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/jp/app/%E3%83%90%E3%83%B3%E3%83%89%E3%83%AA-%E3%82%AC%E3%83%BC%E3%83%AB%E3%82%BA%E3%83%90%E3%83%B3%E3%83%89%E3%83%91%E3%83%BC%E3%83%86%E3%82%A3/id1195834442?mt=8&uo=4">https://itunes.apple.com/jp/app/%E3%83%90%E3%83%B3%E3%83%89%E3%83%AA-%E3%82%AC%E3%83%BC%E3%83%AB%E3%82%BA%E3%83%90%E3%83%B3%E3%83%89%E3%83%91%E3%83%BC%E3%83%86%E3%82%A3/id1195834442?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Craft Egg, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/jp/developer/craft-egg-inc/id909199081?mt=8&uo=4">© Craft Egg Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/16/11/39/161139d9-ff9e-2324-c798-b938d1051955/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61594753-c4468480-abef-11e9-8b67-82dcf4beaba5.png)

**Comment by randompasser** [comment]
Bundle IDs for other regional versions
English: com.bushiroad.en.bangdreamgbp
Taiwanese: net.gamon.bdTW
Korean: com.kakaogames.bangdreamkr

**Comment by ivanov007** [comment]
@randompasser you need to get the iTunes ID for those and post them as separate issues

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/61170894-e9901e80-a56f-11e9-9b57-0a4ab11ebc39.png)
https://user-images.githubusercontent.com/20930745/61170894-e9901e80-a56f-11e9-9b57-0a4ab11ebc39.png

Source:
https://user-images.githubusercontent.com/20930745/61170895-eac14b80-a56f-11e9-8900-24dfcd45db20.png

**Comment by randompasser** [comment]
Don't want to be too picky, but I think the silhouette of the main protagonist's guitar would represent the game better than the publisher's logo.

For reference here's the notification icon from the Android version 
![notify](https://user-images.githubusercontent.com/33059426/61238133-9d5efd00-a76e-11e9-9372-6a5ccf4cb84d.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61594753-c4468480-abef-11e9-8b67-82dcf4beaba5.png)
https://user-images.githubusercontent.com/2068130/61594753-c4468480-abef-11e9-8b67-82dcf4beaba5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/61594760-d6c0be00-abef-11e9-8999-2430449e385e.png
