### ISSUE TITLE
Human Anatomy Atlas 2019

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10083]
**App Name:** Human Anatomy Atlas 2019
**Bundle ID:** com.argosy.vb.superatlas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1117998129">1117998129</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/human-anatomy-atlas-2019/id1117998129?mt=8&uo=4">https://itunes.apple.com/us/app/human-anatomy-atlas-2019/id1117998129?mt=8&uo=4</a>
**App Version:** 2019.2.48
**Seller:** Argosy Publishing
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/visible-body/id446207964?mt=8&uo=4">© Visible Body</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/c0/8f/2d/c08f2d69-576f-be47-57b6-b1237b5a5c1a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58697114-43aa9b00-8399-11e9-8913-18fcd553645f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58697114-43aa9b00-8399-11e9-8913-18fcd553645f.png)
https://user-images.githubusercontent.com/2068130/58697114-43aa9b00-8399-11e9-8913-18fcd553645f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58697152-53c27a80-8399-11e9-9f4e-8a82a30d1b72.png
