### ISSUE TITLE
NOS

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1008]
**App Name:** NOS
**Bundle ID:** nl.nos.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=516491461">516491461</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nos/id516491461?mt=8&uo=4">https://itunes.apple.com/us/app/nos/id516491461?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** Nederlandse Omroep Stichting
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nederlandse-omroep-stichting/id316584000?uo=4>© Nederlandse Omroep Stichting</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/39/1e/0e/391e0e67-0aab-e432-c175-c1295d3e4784/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617402/e37b2c88-982f-11e6-8076-d88d92e25bb1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617402/e37b2c88-982f-11e6-8076-d88d92e25bb1.png)
https://cloud.githubusercontent.com/assets/20930745/19617402/e37b2c88-982f-11e6-8076-d88d92e25bb1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617407/fec87d9c-982f-11e6-9154-b091f957ae50.png
