### ISSUE TITLE
StickerShelf for WhatsApp

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10084]
**App Name:** StickerShelf for WhatsApp
**Bundle ID:** com.stickershelf.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1453096830">1453096830</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stickershelf-for-whatsapp/id1453096830?mt=8&uo=4">https://itunes.apple.com/us/app/stickershelf-for-whatsapp/id1453096830?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** Yagiz Nizipli
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yagiz-nizipli/id969218833?mt=8&uo=4">© Yagiz Nizipli</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/d6/c7/0d/d6c70d8a-7157-41e6-7507-2c3a6555ccc6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/55288457-5b28d000-53b8-11e9-8d66-e067bf387dff.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/55288457-5b28d000-53b8-11e9-8d66-e067bf387dff.png)
https://user-images.githubusercontent.com/20930745/55288457-5b28d000-53b8-11e9-8d66-e067bf387dff.png

Source:
https://user-images.githubusercontent.com/20930745/55288458-5cf29380-53b8-11e9-8a62-6d0c44e078e7.png
