### ISSUE TITLE
Wizz Air

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#10088]
**App Name:** Wizz Air
**Bundle ID:** com.wizzair.WizzAirApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=583348801">583348801</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wizz-air/id583348801?mt=8&uo=4">https://itunes.apple.com/us/app/wizz-air/id583348801?mt=8&uo=4</a>
**App Version:** 6.3.1
**Seller:** Wizz Air Hungary Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wizz-air-hungary-ltd/id583348804?mt=8&uo=4">© Wizz Air Hungary Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/0b/c0/71/0bc07127-93bb-9ba1-bd64-522337371ccb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/56465908-cd656100-6408-11e9-905d-2752d0a18193.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/56465908-cd656100-6408-11e9-905d-2752d0a18193.png)
https://user-images.githubusercontent.com/2068130/56465908-cd656100-6408-11e9-905d-2752d0a18193.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/56465914-e0783100-6408-11e9-813e-161c27b31b9a.png
