### ISSUE TITLE
Disney Heroes: Battle Mode

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10089]
**App Name:** Disney Heroes: Battle Mode
**Bundle ID:** com.perblue.disneyheroes.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1327925104">1327925104</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/disney-heroes-battle-mode/id1327925104?mt=8&uo=4">https://itunes.apple.com/us/app/disney-heroes-battle-mode/id1327925104?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** PerBlue Entertainment, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/perblue-entertainment-inc/id1157992836?mt=8&uo=4">© PerBlue Entertainment, Inc</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/21/26/60/2126604c-5d5f-6247-f9b7-9f38a5b974e3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58701900-9047a380-83a4-11e9-9021-4237fe7aab4c.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58701900-9047a380-83a4-11e9-9021-4237fe7aab4c.png)
https://user-images.githubusercontent.com/2068130/58701900-9047a380-83a4-11e9-9021-4237fe7aab4c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58701923-a0f81980-83a4-11e9-88a7-bd07d3db0321.png
