### ISSUE TITLE
Hepsiburada

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10080]
**App Name:** Hepsiburada
**Bundle ID:** com.pozitron.hepsiburada
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=481035064">481035064</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hepsiburada/id481035064?mt=8&uo=4">https://itunes.apple.com/us/app/hepsiburada/id481035064?mt=8&uo=4</a>
**App Version:** 2.9.2
**Seller:** D-MARKET ELEKTRONIK HIZMETLER VE TICARET ANONIM SIRKETI
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/d-market-elektronik-hizmetler-ve-ticaret-anonim-sirketi/id1022820383?mt=8&uo=4">© D-MARKET ELEKTRONIK HIZMETLER VE TICARET ANONIM SIRKETI</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/06/cb/43/06cb43c3-7623-7f88-0b20-eac2600dc8cb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54533202-ec944d00-4989-11e9-9f9c-b1ded8cbc640.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54533202-ec944d00-4989-11e9-9f9c-b1ded8cbc640.png)
https://user-images.githubusercontent.com/20930745/54533202-ec944d00-4989-11e9-9f9c-b1ded8cbc640.png

Source:
https://user-images.githubusercontent.com/20930745/54533208-ef8f3d80-4989-11e9-87dd-46051ccb4da8.png
