### ISSUE TITLE
Rise of Kingdoms

### ISSUE THREAD

**Issue by gokmenecer** [glasklart/hd#10087]
**App Name:** Rise of Kingdoms
**Bundle ID:** com.lilithgame.roc.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1354260888">1354260888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rise-of-kingdoms/id1354260888?mt=8&uo=4">https://itunes.apple.com/us/app/rise-of-kingdoms/id1354260888?mt=8&uo=4</a>
**App Version:** 1.0.1729
**Seller:** LilithGame Co., Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lilith-games/id982119759?mt=8&uo=4">© Lilith Games</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/88/99/7d/88997dec-2155-a849-a5e9-c3220060ca94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/61170790-b1d4a700-a56e-11e9-86a1-42833a1986b5.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/61170790-b1d4a700-a56e-11e9-86a1-42833a1986b5.png)
https://user-images.githubusercontent.com/20930745/61170790-b1d4a700-a56e-11e9-86a1-42833a1986b5.png

Source:
https://user-images.githubusercontent.com/20930745/61170791-b39e6a80-a56e-11e9-81bb-d55860ef1846.png
