### ISSUE TITLE
Paint My Wall - Virtual Room Painting

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10085]
**App Name:** Paint My Wall - Virtual Room Painting
**Bundle ID:** com.changemystyle.paintmywallfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542998115">542998115</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paint-my-wall-virtual-room-painting/id542998115?mt=8&uo=4">https://itunes.apple.com/us/app/paint-my-wall-virtual-room-painting/id542998115?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Alexander Dr. Rieger
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alexander-dr-rieger/id464916737?mt=8&uo=4">© Alexander Dr. Rieger</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple122/v4/15/12/ab/1512ab96-38fe-fb7e-34ea-34d612955324/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/55288545-5f092200-53b9-11e9-882a-798f1f71b8a5.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/55288545-5f092200-53b9-11e9-882a-798f1f71b8a5.png)
https://user-images.githubusercontent.com/20930745/55288545-5f092200-53b9-11e9-882a-798f1f71b8a5.png

Source:
https://user-images.githubusercontent.com/20930745/55288549-616b7c00-53b9-11e9-9936-6959c3163d8d.png
