### ISSUE TITLE
EasyBBQ

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10091]
**App Name:** EasyBBQ
**Bundle ID:** qlnet.com.easybbq
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1023629163">1023629163</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/easybbq/id1023629163?mt=8&uo=4">https://itunes.apple.com/us/app/easybbq/id1023629163?mt=8&uo=4</a>
**App Version:** 1.7.5
**Seller:** Shenzhen Qilin Wanglian Information Technology Co., Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/shenzhen-qilin-wanglian-information-technology-co-ltd/id1020071838?mt=8&uo=4">© Shenzhen Qilin Wanglian Information Technology Co.,ltd</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple127/v4/b1/1c/ea/b11ceab4-3d70-a00a-6405-a42e412d0251/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/57175586-11675580-6e4e-11e9-9b01-2a04ff979a90.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/57175586-11675580-6e4e-11e9-9b01-2a04ff979a90.png)
https://user-images.githubusercontent.com/2068130/57175586-11675580-6e4e-11e9-9b01-2a04ff979a90.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/57175589-247a2580-6e4e-11e9-8963-96f4b13776e3.png
