### ISSUE TITLE
Gravity Defied Classic 

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10095]
**App Name:** Gravity Defied Classic
**Bundle ID:** JesusCodes.me.GravityDefied
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1121395217">1121395217</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gravity-defied-classic/id1121395217?mt=8&uo=4">https://itunes.apple.com/us/app/gravity-defied-classic/id1121395217?mt=8&uo=4</a>
**App Version:** 1.1.151
**Seller:** David Davidov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/david-davidov/id1121395216?mt=8&uo=4">© David Davidov</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/94/40/6b/94406be4-11c0-1fc5-7206-1e7d07d01c49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57580244-73a40400-74a7-11e9-8162-e6b9cd688f48.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57580244-73a40400-74a7-11e9-8162-e6b9cd688f48.png)
https://user-images.githubusercontent.com/20930745/57580244-73a40400-74a7-11e9-8162-e6b9cd688f48.png

Source:
https://user-images.githubusercontent.com/20930745/57580245-756dc780-74a7-11e9-91c5-9dc5c49a1038.png

**Comment by iPOSEiDON** [comment]
Awesome !
