### ISSUE TITLE
ParkNow - Parking

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10090]
**App Name:** ParkNow - Parking
**Bundle ID:** com.park-now.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1073446522">1073446522</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/parknow-parking/id1073446522?mt=8&uo=4">https://itunes.apple.com/gb/app/parknow-parking/id1073446522?mt=8&uo=4</a>
**App Version:** 4.4.1
**Seller:** Park-Now GMBH
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/parknow/id1073446521?mt=8&uo=4">© ParkNow</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/42/a6/b6/42a6b6c0-5fa2-55d6-4341-9c10875160b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57580350-a995b800-74a8-11e9-9e88-862d269e1aad.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57580350-a995b800-74a8-11e9-9e88-862d269e1aad.png)
https://user-images.githubusercontent.com/20930745/57580350-a995b800-74a8-11e9-9e88-862d269e1aad.png

Source:
https://user-images.githubusercontent.com/20930745/57580352-ab5f7b80-74a8-11e9-97f7-307ce4a77100.png
