### ISSUE TITLE
Pool

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10099]
**App Name:** Pool
**Bundle ID:** com.byterun.pool
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=332184886">332184886</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pool/id332184886?mt=8&uo=4">https://itunes.apple.com/us/app/pool/id332184886?mt=8&uo=4</a>
**App Version:** 5.4
**Seller:** Vintolo Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vintolo-ltd/id1453865533?mt=8&uo=4">© Vintolo Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/3c/a3/83/3ca38348-699f-2178-4fbf-8a5a0f895edc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58366001-7ef62700-7ecc-11e9-8eb6-d1dae1c28af2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58366001-7ef62700-7ecc-11e9-8eb6-d1dae1c28af2.png)
https://user-images.githubusercontent.com/2068130/58366001-7ef62700-7ecc-11e9-8eb6-d1dae1c28af2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58366013-903f3380-7ecc-11e9-8fa5-9c63cec588a5.png

**Comment by iPOSEiDON** [comment]
Thanks, looking great !
