### ISSUE TITLE
Clip2Comic & Caricature Maker

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10092]
**App Name:** Clip2Comic & Caricature Maker
**Bundle ID:** de.tag2me.toonsnap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=876328355">876328355</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clip2comic-caricature-maker/id876328355?mt=8&uo=4">https://itunes.apple.com/us/app/clip2comic-caricature-maker/id876328355?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** DigitalMasterpieces GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/digitalmasterpieces-gmbh/id874345609?mt=8&uo=4">© DigitalMasterpieces GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/0a/26/a5/0a26a5f0-a0ae-c9bf-039b-3111a1b4b53c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/57175367-7a010300-6e4b-11e9-9457-60c08edbb30c.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/57175367-7a010300-6e4b-11e9-9457-60c08edbb30c.png)
https://user-images.githubusercontent.com/2068130/57175367-7a010300-6e4b-11e9-9457-60c08edbb30c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/57175369-8ab17900-6e4b-11e9-8d31-ea20a347ac5f.png
