### ISSUE TITLE
Star Wars: The Old Republic Security Key 

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10093]
**App Name:** Star Wars: The Old Republic Security Key
**Bundle ID:** com.ea.ios.swtorsk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=996685033">996685033</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/star-wars-the-old-republic-security-key/id996685033?mt=8&uo=4">https://itunes.apple.com/us/app/star-wars-the-old-republic-security-key/id996685033?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple7/v4/17/d9/1f/17d91f31-a95d-e370-112a-49ac41aa3cd2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58366101-9eda1a80-7ecd-11e9-9066-5e1bab132a01.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58365933-81a44c80-7ecb-11e9-9669-59f5d8c7345f.png)
https://user-images.githubusercontent.com/20930745/58365933-81a44c80-7ecb-11e9-9669-59f5d8c7345f.png

Source:
https://user-images.githubusercontent.com/20930745/58365934-82d57980-7ecb-11e9-865e-f084bdc9b9a7.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet 
i made a better one :-)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58366101-9eda1a80-7ecd-11e9-9066-5e1bab132a01.png)
https://user-images.githubusercontent.com/20930745/58366101-9eda1a80-7ecd-11e9-9066-5e1bab132a01.png

Source:
https://user-images.githubusercontent.com/20930745/58366102-a0a3de00-7ecd-11e9-9e72-f97f47adb158.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Great! 👍

**Comment by iPOSEiDON** [comment]
Perfect !!
