### ISSUE TITLE
Can Knockdown 3 Lite

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10098]
**App Name:** Can Knockdown 3 Lite
**Bundle ID:** pl.idreams.CanKnockdown3Free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=651966498">651966498</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/can-knockdown-3-lite/id651966498?mt=8&uo=4">https://itunes.apple.com/us/app/can-knockdown-3-lite/id651966498?mt=8&uo=4</a>
**App Version:** 1.07
**Seller:** Infinite Dreams
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/infinite-dreams-inc/id306712040?mt=8&uo=4">© Infinite Dreams Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/84/16/84/84168421-1327-2788-58f7-85711c25c03e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58734457-c8c49d00-83f7-11e9-92e5-c882dcea9a80.png)

**Comment by dreamnet** [comment]
❓ 

![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58734457-c8c49d00-83f7-11e9-92e5-c882dcea9a80.png)
https://user-images.githubusercontent.com/2068130/58734457-c8c49d00-83f7-11e9-92e5-c882dcea9a80.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58734485-d8dc7c80-83f7-11e9-80ac-9c10251d8cfd.png

**Comment by iPOSEiDON** [comment]
perfect, thank you ! :)
