### ISSUE TITLE
ABV Mail

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10096]
**App Name:** ABV Mail
**Bundle ID:** bg.abv.Mail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1024988497">1024988497</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/abv-mail/id1024988497?mt=8&uo=4">https://itunes.apple.com/us/app/abv-mail/id1024988497?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Net Info.BG EAD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/net-info-bg-ead/id495932403?mt=8&uo=4">© Net Info.BG EAD</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/92/16/c3/9216c3c4-ada5-e9e6-7d40-9e9b42272c07/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57638408-ff07bd00-75ad-11e9-9afe-0c700030f6fa.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57580290-fdec6800-74a7-11e9-9c6c-9154937ae819.png)
https://user-images.githubusercontent.com/20930745/57580290-fdec6800-74a7-11e9-9c6c-9154937ae819.png

Source:
https://user-images.githubusercontent.com/20930745/57580293-004ec200-74a8-11e9-8b52-636549099e62.png

**Comment by iPOSEiDON** [comment]
Its perfect ! :)

**Comment by 2Qt2beStr8** [comment]
or this one:
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57638408-ff07bd00-75ad-11e9-9afe-0c700030f6fa.png)
https://user-images.githubusercontent.com/20930745/57638408-ff07bd00-75ad-11e9-9afe-0c700030f6fa.png

Source:
![abvmail1](https://user-images.githubusercontent.com/20930745/57638314-d54e9600-75ad-11e9-9211-f33cdddd4571.png)

**Comment by iPOSEiDON** [comment]
I would pick the second one thanks :)

**Comment by iPOSEiDON** [comment]
Got the second one and added it manually. thank you ! :)
