### ISSUE TITLE
iTorch Flashlight

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10097]
**App Name:** iTorch Flashlight
**Bundle ID:** com.pixelinlove.itorcia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=384365348">384365348</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/itorch-flashlight/id384365348?mt=8&uo=4">https://itunes.apple.com/us/app/itorch-flashlight/id384365348?mt=8&uo=4</a>
**App Version:** 4.1.6
**Seller:** Pixelinlove Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pixelinlove-ltd/id384365351?mt=8&uo=4">© Pixelinlove Ltd</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/a6/4c/48/a64c487a-95fc-9e6a-d38b-f3aee5a3fd43/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58694900-64bcbd00-8394-11e9-9ba6-80b90b2e90b0.png)

**Comment by dreamnet** [comment]
Using the icon from #5602
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58694900-64bcbd00-8394-11e9-9ba6-80b90b2e90b0.png)
https://user-images.githubusercontent.com/2068130/58694900-64bcbd00-8394-11e9-9ba6-80b90b2e90b0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58694957-7a31e700-8394-11e9-8e1d-c81730be68a1.png

**Comment by iPOSEiDON** [comment]
Umm ok, looks interesting, thanks
