### ISSUE TITLE
The Elder Scrolls: Blades

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10094]
**App Name:** The Elder Scrolls: Blades
**Bundle ID:** com.bethsoft.blade
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1358476597">1358476597</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-elder-scrolls-blades/id1358476597?mt=8&uo=4">https://itunes.apple.com/us/app/the-elder-scrolls-blades/id1358476597?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Bethesda Softworks LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bethesda/id547109759?mt=8&uo=4">© Bethesda</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/1d/f6/54/1df6547d-9e3a-0f2d-2952-6186c9ba6173/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57580189-c3360000-74a6-11e9-95bc-4cd127416c82.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57580189-c3360000-74a6-11e9-95bc-4cd127416c82.png)
https://user-images.githubusercontent.com/20930745/57580189-c3360000-74a6-11e9-95bc-4cd127416c82.png

Source:
https://user-images.githubusercontent.com/20930745/57580190-c4ffc380-74a6-11e9-9ed4-560b02692ca1.png)

**Comment by iPOSEiDON** [comment]
i love it  :)
