### ISSUE TITLE
Coyote : navigation, trafic, alertes

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#101]
**App Name:** Coyote : navigation, trafic, alertes
**Bundle ID:** com.moncoyote.icoyoteFR302
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=367345773">367345773</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/coyote-navigation-trafic-alertes/id367345773?mt=8&uo=4">https://itunes.apple.com/fr/app/coyote-navigation-trafic-alertes/id367345773?mt=8&uo=4</a>
**App Version:** 10.5.1
**Seller:** Coyote System
**Developer:** <a target="_blank" href="https://itunes.apple.com/fr/developer/coyote-system/id321050506?uo=4">© Coyote System</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/71/43/94/714394f8-1323-4ea2-9c1f-aa13ffac8525/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26125378/3bf8d640-3a82-11e7-9bfd-f1df7c65f899.png)

**Comment by iPhoneAddict** [comment]
I wanted to post an update for the Coyote application but things became more complex than i thought initially.

I must say that it was very difficult to understand what to do and i am still unsure after reading everything i could, that i did it well.

It is unclear for me if the image should be a full glyph of 1024x1024 Pixels or should be 118x118 pixels inside the 180x180 pixels from the template or both.
It is also unclear if the full sized glyph should be black (How to ...) or white (video tutorial) in the 1024 format.
It is unclear if i have to post one or both to be good, so i copied from other contributions in the end.

Anyway, trying to go to the end of the process  here is my contribution that i can adjust with some guidance.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2135171/26024078/6622ef10-37ca-11e7-9d2b-4a65324c83ea.png)

Source :
![com moncoyote icoyotefr302-large](https://cloud.githubusercontent.com/assets/2135171/26024061/b76f4ee6-37c9-11e7-85eb-098ce2392d56.png)

**Comment by dreamnet** [comment]
@iPhoneAddict You did everything right. 👍  The 1024x1024px source file represents the 118x118px area in the 180x180px Glasklart icon (shrink the source down and then apply the Glasklart style). The source file must be black and transparent. Black areas end up white and transparent end up - transparent.
For this icon I think we don't need the background, so I would do something like this:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26125378/3bf8d640-3a82-11e7-9bfd-f1df7c65f899.png)
https://cloud.githubusercontent.com/assets/2068130/26125378/3bf8d640-3a82-11e7-9bfd-f1df7c65f899.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26125400/51a1b9a8-3a82-11e7-8460-60fda6575f25.png
I hope I could clear some things out. If you have further questions, feel free to ask. 😉

**Comment by iPhoneAddict** [comment]
Great ! Thank you.
