### ISSUE TITLE
Injustice: Gods Among Us

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10101]
**App Name:** Injustice: Gods Among Us
**Bundle ID:** com.wb.Injustice.Brawler2013
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=575658129">575658129</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/injustice-gods-among-us/id575658129?mt=8&uo=4">https://itunes.apple.com/us/app/injustice-gods-among-us/id575658129?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Warner Bros. Entertainment
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/warner-bros/id298372283?mt=8&uo=4">© Warner Bros.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/53/0d/54/530d546f-a868-481a-b90a-3aa93d7c3826/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/61169736-3d473b80-a561-11e9-9234-5af3ee0eb01e.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/61169736-3d473b80-a561-11e9-9234-5af3ee0eb01e.png)
https://user-images.githubusercontent.com/20930745/61169736-3d473b80-a561-11e9-9234-5af3ee0eb01e.png

Source:
https://user-images.githubusercontent.com/20930745/61169738-3fa99580-a561-11e9-9aab-cae1d8e856ca.png

**Comment by iPOSEiDON** [comment]
Thank you !
