### ISSUE TITLE
Succession

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10103]
**App Name:** Succession
 **Bundle ID:** com.samgisaninja.SuccessionRestore
 **Version:** 1.3
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://user-images.githubusercontent.com/2068130/57596245-f67d9b00-7549-11e9-8b70-2ea77943e157.png" width="180" height="180" />
 **Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57639144-886bbf00-75af-11e9-9ff2-5e8ca5d54647.png)

**Comment by dreamnet** [comment]
@tarkan78 I corrected your request.
https://github.com/Samgisaninja/SuccessionRestore

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57639144-886bbf00-75af-11e9-9ff2-5e8ca5d54647.png)
https://user-images.githubusercontent.com/20930745/57639144-886bbf00-75af-11e9-9ff2-5e8ca5d54647.png

Source:
https://user-images.githubusercontent.com/20930745/57639149-8b66af80-75af-11e9-808d-156c0d803c01.png
