### ISSUE TITLE
LogMeIn

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1010]
**App Name:** LogMeIn
**Bundle ID:** com.logmein.logmein
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479229407">479229407</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/logmein/id479229407?mt=8&uo=4">https://itunes.apple.com/us/app/logmein/id479229407?mt=8&uo=4</a>
**App Version:** 4.1.5166
**Seller:** LogMeIn, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/logmein-inc./id299616804?uo=4>© LogMeIn, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/3b/57/60/3b5760d7-ce95-eeaf-01a2-09819b25ea44/mzl.plbhqzot.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10103015/fdc3e6b6-63a1-11e5-9440-fe490ca653e7.png)

**Comment by Trubbel** [comment]
Adding source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10103015/fdc3e6b6-63a1-11e5-9440-fe490ca653e7.png)
https://cloud.githubusercontent.com/assets/10730122/10103015/fdc3e6b6-63a1-11e5-9440-fe490ca653e7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10103012/f9eda004-63a1-11e5-8783-d667920909e0.png
