### ISSUE TITLE
iGun Pro

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10100]
**App Name:** iGun Pro
**Bundle ID:** com.avidionmedia.iGunHD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=574123647">574123647</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/igun-pro/id574123647?mt=8&uo=4">https://itunes.apple.com/us/app/igun-pro/id574123647?mt=8&uo=4</a>
**App Version:** 5.31
**Seller:** Crimson Moon Entertainment LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/crimson-moon-entertainment-llc/id301065733?mt=8&uo=4">© Crimson Moon Entertainment LLC</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/62/3a/5d/623a5d18-8d69-976f-8055-c2d7c31f98eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58370943-cb615700-7f0c-11e9-9814-f4a6caf057e0.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58370943-cb615700-7f0c-11e9-9814-f4a6caf057e0.png)
https://user-images.githubusercontent.com/2068130/58370943-cb615700-7f0c-11e9-9814-f4a6caf057e0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58370949-dc11cd00-7f0c-11e9-8ffc-9290fe5202b7.png

**Comment by iPOSEiDON** [comment]
awesome thanks !
