### ISSUE TITLE
Starcraft 2 Memory Game 

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10118]
**App Name:** Starcraft 2 Memory Game
**Bundle ID:** dot44.starcraft2memory
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=475211925">475211925</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/starcraft-2-memory-game/id475211925?mt=8&uo=4">https://itunes.apple.com/us/app/starcraft-2-memory-game/id475211925?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** ALEKSEJS VOLOVIKS
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alexey-volovik/id316367204?mt=8&uo=4">© Alexey Volovik</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/cc/b2/af/ccb2af13-3854-35b4-ecd1-81a56c3aa590/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58614420-92343880-82b8-11e9-93a2-333b4c62aa11.png)

**Comment by dreamnet** [comment]
❓ 

![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58614420-92343880-82b8-11e9-93a2-333b4c62aa11.png)
https://user-images.githubusercontent.com/2068130/58614420-92343880-82b8-11e9-93a2-333b4c62aa11.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58614441-a24c1800-82b8-11e9-9a7e-8e891af1f076.png

**Comment by iPOSEiDON** [comment]
Awesome ! thank you !
