### ISSUE TITLE
PixWords® - Picture Crosswords 

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10119]
**App Name:** PixWords® - Picture Crosswords
**Bundle ID:** com.dekovir.pixwords
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598439078">598439078</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pixwords-picture-crosswords/id598439078?mt=8&uo=4">https://itunes.apple.com/us/app/pixwords-picture-crosswords/id598439078?mt=8&uo=4</a>
**App Version:** 2.42
**Seller:** Dekovir, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dekovir-inc/id393062490?mt=8&uo=4">© Dekovir, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/51/c9/21/51c92197-b54d-8be8-ff7d-a7d7307b6195/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58376982-452e2a80-7f77-11e9-8b79-d9c96547880b.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58376982-452e2a80-7f77-11e9-8b79-d9c96547880b.png)
https://user-images.githubusercontent.com/20930745/58376982-452e2a80-7f77-11e9-8b79-d9c96547880b.png

Source:
https://user-images.githubusercontent.com/20930745/58376984-46f7ee00-7f77-11e9-948e-b6ccb6b5fa0b.png
