### ISSUE TITLE
FlixBus: Smart Bus Travel

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#10114]
**App Name:** FlixBus: Smart Bus Travel
**Bundle ID:** com.flixbus.ios.Flixbus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=778437357">778437357</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flixbus-smart-bus-travel/id778437357?mt=8&uo=4">https://itunes.apple.com/us/app/flixbus-smart-bus-travel/id778437357?mt=8&uo=4</a>
**App Version:** 6.0.3
**Seller:** FlixMobility GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/flixmobility-gmbh/id778437360?mt=8&uo=4">© FlixMobility GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/21/61/04/216104a6-0ae3-b0f2-f11a-25516f0cd155/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58371006-84279600-7f0d-11e9-888f-20470e7c836e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58371006-84279600-7f0d-11e9-888f-20470e7c836e.png)
https://user-images.githubusercontent.com/2068130/58371006-84279600-7f0d-11e9-888f-20470e7c836e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58371012-986b9300-7f0d-11e9-8817-1c53395d2924.png
