### ISSUE TITLE
KeePass Touch

### ISSUE THREAD

**Issue by Aatoz** [glasklart/hd#10112]
**App Name:** KeePass Touch
**Bundle ID:** de.pixel-paws.KeePass-Touch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=966759076">966759076</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/keepass-touch/id966759076?mt=8&uo=4">https://itunes.apple.com/us/app/keepass-touch/id966759076?mt=8&uo=4</a>
**App Version:** 1.9.3
**Seller:** Innervate UG(haftungsbeschraenkt) & Co. KG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/innervate/id1184312610?mt=8&uo=4">© Innervate</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/8b/40/a8/8b40a8fc-8b33-e09c-e0e4-3def1e78e386/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57781090-c4c32a80-7729-11e9-9141-a95d97e8f511.png)

**Comment by 2Qt2beStr8** [comment]
i can't do it with the original artwork, but maybe this is also ok?

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/57781090-c4c32a80-7729-11e9-9141-a95d97e8f511.png)
https://user-images.githubusercontent.com/20930745/57781090-c4c32a80-7729-11e9-9141-a95d97e8f511.png

Source:
https://user-images.githubusercontent.com/20930745/57781094-c68cee00-7729-11e9-98e2-458de9a8a3a2.png

**Comment by Aatoz** [comment]
Love it! Even better than original!
