### ISSUE TITLE
Bubble Witch 3 Saga

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10115]
**App Name:** Bubble Witch 3 Saga
**Bundle ID:** com.midasplayer.apps.bubblewitchsaga3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1095254858">1095254858</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bubble-witch-3-saga/id1095254858?mt=8&uo=4">https://itunes.apple.com/us/app/bubble-witch-3-saga/id1095254858?mt=8&uo=4</a>
**App Version:** 5.5.4
**Seller:** King.com Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/king/id526656015?mt=8&uo=4">© King</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/89/21/b7/8921b7ab-714a-399d-0ae7-b28d52d6d5c5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58690993-1fe05880-838b-11e9-8156-7325572a077f.png)

**Comment by dreamnet** [comment]
❓ 

![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58617378-42f20600-82c0-11e9-815d-92de71fb33b1.png)
https://user-images.githubusercontent.com/2068130/58617378-42f20600-82c0-11e9-815d-92de71fb33b1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58617406-51d8b880-82c0-11e9-92ae-d7aca8c56910.png

**Comment by iPOSEiDON** [comment]
Perfect !

**Comment by iPOSEiDON** [comment]
Btw i am very sorry, i just realised i posted the wrong one, i needed for the first Bubble Witch saga not the 3rd one....really sorry about that, hopefully someone will need it too :)

**Comment by dreamnet** [comment]
@iPOSEiDON That's OK, sometime someone will need ist. 😄

**Comment by dreamnet** [comment]
Small update:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58690993-1fe05880-838b-11e9-8156-7325572a077f.png)
https://user-images.githubusercontent.com/2068130/58690993-1fe05880-838b-11e9-8156-7325572a077f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58691031-325a9200-838b-11e9-9f26-df8754dea3e4.png
