### ISSUE TITLE
Galaxy on Fire 3 

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10116]
**App Name:** Galaxy on Fire 3
**Bundle ID:** com.dsfishlabs.gof3manticore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1039848719">1039848719</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/galaxy-on-fire-3/id1039848719?mt=8&uo=4">https://itunes.apple.com/us/app/galaxy-on-fire-3/id1039848719?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** FISHLABS
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fishlabs/id330298365?mt=8&uo=4">© FISHLABS</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/63/ce/78/63ce78bd-b058-7784-c50b-54b09edcbc9b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58377058-c3d79780-7f78-11e9-9e6e-1b78445f5a97.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58377058-c3d79780-7f78-11e9-9e6e-1b78445f5a97.png)
https://user-images.githubusercontent.com/20930745/58377058-c3d79780-7f78-11e9-9e6e-1b78445f5a97.png

Source:
https://user-images.githubusercontent.com/20930745/58377059-c508c480-7f78-11e9-8844-8f06f2889c61.png

**Comment by iPOSEiDON** [comment]
not bad, thank you
