### ISSUE TITLE
Wort Stapel

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10126]
**App Name:** Wort Stapel
**Bundle ID:** com.wordgame.puzzle.block.crush.de
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1454223370">1454223370</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/wort-stapel/id1454223370?mt=8&uo=4">https://itunes.apple.com/de/app/wort-stapel/id1454223370?mt=8&uo=4</a>
**App Version:** 1.0.9
**Seller:** Talefun Technologies Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/talefun/id1440135076?mt=8&uo=4">© Talefun</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/e0/3f/94/e03f94c2-153e-bf2f-41ac-cd0aa66ec192/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58634429-9594e780-82eb-11e9-848f-e3a24ba1fed6.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58633547-0686d000-82e9-11e9-8e52-695091124f8a.png)
https://user-images.githubusercontent.com/20930745/58633547-0686d000-82e9-11e9-8e52-695091124f8a.png

Source:
https://user-images.githubusercontent.com/20930745/58633551-08509380-82e9-11e9-9332-283bc369f614.png

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58634429-9594e780-82eb-11e9-848f-e3a24ba1fed6.png)
https://user-images.githubusercontent.com/20930745/58634429-9594e780-82eb-11e9-848f-e3a24ba1fed6.png

Source:
https://user-images.githubusercontent.com/20930745/58634433-975eab00-82eb-11e9-806a-b468d15b2980.png

**Comment by tarkan78** [comment]
The Second one looks Better.THx
