### ISSUE TITLE
Carb Manager: Keto Diet App

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10129]
**App Name:** Carb Manager: Keto Diet App
**Bundle ID:** com.wombatapps.carbtracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=410089731">410089731</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/carb-manager-keto-diet-app/id410089731?mt=8&uo=4">https://itunes.apple.com/us/app/carb-manager-keto-diet-app/id410089731?mt=8&uo=4</a>
**App Version:** 6.2.1
**Seller:** Wombat Apps LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wombat-apps-llc/id396778360?mt=8&uo=4">© Wombat Apps LLC</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/95/08/23/95082388-f614-8ff5-b87f-10781b2f51af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58752786-1f43e100-84b5-11e9-969c-7821c9ace1a9.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58752786-1f43e100-84b5-11e9-969c-7821c9ace1a9.png)
https://user-images.githubusercontent.com/20930745/58752786-1f43e100-84b5-11e9-969c-7821c9ace1a9.png

Source:
https://user-images.githubusercontent.com/20930745/58752787-210da480-84b5-11e9-855f-6bdc5fea0a79.png

**Comment by TheRyanKing** [comment]
Thanks!
