### ISSUE TITLE
AxisCare Mobile

### ISSUE THREAD

**Issue by CalTrask** [glasklart/hd#10124]
**App Name:** AxisCare Mobile
**Bundle ID:** com.axiscare
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1081635097">1081635097</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/axiscare-mobile/id1081635097?mt=8&uo=4">https://itunes.apple.com/us/app/axiscare-mobile/id1081635097?mt=8&uo=4</a>
**App Version:** 1.4.7
**Seller:** Centex Axiscare Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/axiscare/id1081635096?mt=8&uo=4">© AxisCare</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/b2/99/89/b2998986-3358-c8fe-59c7-3131e98458c0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58376864-a4d70680-7f74-11e9-99d5-c1d7edfcd31b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58376864-a4d70680-7f74-11e9-99d5-c1d7edfcd31b.png)
(https://user-images.githubusercontent.com/20930745/58376864-a4d70680-7f74-11e9-99d5-c1d7edfcd31b.png

Source:
https://user-images.githubusercontent.com/20930745/58376865-a6a0ca00-7f74-11e9-8832-1a7022251995.png

**Comment by CalTrask** [comment]
Thank you.

**Comment by 2Qt2beStr8** [comment]
You are welcome. Please don’t close the issue.
