### ISSUE TITLE
Онлайн радио България

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10122]
**App Name:** Онлайн радио България
**Bundle ID:** net.radioexpert.radio.bulgaria
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1265427255">1265427255</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD-%D1%80%D0%B0%D0%B4%D0%B8%D0%BE-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D0%B8%D1%8F/id1265427255?mt=8&uo=4">https://itunes.apple.com/us/app/%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD-%D1%80%D0%B0%D0%B4%D0%B8%D0%BE-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D0%B8%D1%8F/id1265427255?mt=8&uo=4</a>
**App Version:** 1.1.6
**Seller:** Srdjan Petrovic
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/srdjan-petrovic/id1283478349?mt=8&uo=4">© Srdjan Petrovic</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/7d/3b/55/7d3b5559-9ddb-02bd-a1f3-df1962668aea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58373159-d5de1980-7f29-11e9-93a1-843e0d056341.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58373159-d5de1980-7f29-11e9-93a1-843e0d056341.png)
https://user-images.githubusercontent.com/2068130/58373159-d5de1980-7f29-11e9-93a1-843e0d056341.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58373161-e7272600-7f29-11e9-957f-dfc52876733a.png

**Comment by iPOSEiDON** [comment]
thanks !
