### ISSUE TITLE
BulsatcomTV

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10123]
**App Name:** BulsatcomTV
**Bundle ID:** eu.smartxmedia.bulsatcomtv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=951451911">951451911</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bulsatcomtv/id951451911?mt=8&uo=4">https://itunes.apple.com/us/app/bulsatcomtv/id951451911?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** Smart X Media EOOD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/smart-x-media/id947543943?mt=8&uo=4">© Smart X Media</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple49/v4/b0/cd/ab/b0cdab3e-4600-d3ce-8560-b8bbba32a779/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58373261-8d276000-7f2b-11e9-91db-fddc0361291f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58373261-8d276000-7f2b-11e9-91db-fddc0361291f.png)
https://user-images.githubusercontent.com/2068130/58373261-8d276000-7f2b-11e9-91db-fddc0361291f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58373263-9ca6a900-7f2b-11e9-90fa-b65897936452.png

**Comment by iPOSEiDON** [comment]
thank you !
