### ISSUE TITLE
Bubble Witch Saga

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10127]
**App Name:** Bubble Witch Saga
**Bundle ID:** com.midasplayer.apps.bubblewitch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526656012">526656012</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bubble-witch-saga/id526656012?mt=8&uo=4">https://itunes.apple.com/us/app/bubble-witch-saga/id526656012?mt=8&uo=4</a>
**App Version:** 3.1.33
**Seller:** King.com Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/king/id526656015?mt=8&uo=4">© King</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/4d/36/94/4d36942f-956e-7c0a-46b8-0f9fdf92c3e9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58688643-531fe900-8385-11e9-87a7-01b4cc6f4b68.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58688643-531fe900-8385-11e9-87a7-01b4cc6f4b68.png)
https://user-images.githubusercontent.com/2068130/58688643-531fe900-8385-11e9-87a7-01b4cc6f4b68.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58688662-6337c880-8385-11e9-8702-3a6a16deaf89.png
