### ISSUE TITLE
IPTV-Smarters Player

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10139]
**App Name:** IPTV-Smarters Player
**Bundle ID:** com.smarters.smartiptv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1383614816">1383614816</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iptv-smarters-player/id1383614816?mt=8&uo=4">https://itunes.apple.com/us/app/iptv-smarters-player/id1383614816?mt=8&uo=4</a>
**App Version:** 1.4.9
**Seller:** Amanpreet Singh
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amanpreet-singh/id1327210459?mt=8&uo=4">© Amanpreet Singh</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/97/5b/b2/975bb274-ba35-c140-89c7-38380286bff4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753301-2d95fb00-84bd-11e9-88e0-01252ebf8258.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=![-large](https://user-images.githubusercontent.com/20930745/58753301-2d95fb00-84bd-11e9-88e0-01252ebf8258.png)
https://user-images.githubusercontent.com/20930745/58753301-2d95fb00-84bd-11e9-88e0-01252ebf8258.png

Source:
https://user-images.githubusercontent.com/20930745/58753302-325aaf00-84bd-11e9-92ec-7a565623bdf5.png

**Comment by TheRyanKing** [comment]
Thanks, I will continue to add more, ill get around to working on some of the “issues” too appreciate it
