### ISSUE TITLE
Tankerkönig

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10138]
**App Name:** Tankerkönig
**Bundle ID:** de.bb-applications.tankerkoenig
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=980576151">980576151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/tankerk%C3%B6nig/id980576151?mt=8&uo=4">https://itunes.apple.com/de/app/tankerk%C3%B6nig/id980576151?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** BRUNO BUEHRLEN
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/bruno-buehrlen/id785278211?mt=8&uo=4">© BRUNO BUEHRLEN</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple5/v4/15/8b/f5/158bf522-d3f4-bc86-56c7-b7bf3634411c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753022-e1e15280-84b8-11e9-8821-d9cd1b034e66.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753022-e1e15280-84b8-11e9-8821-d9cd1b034e66.png)
https://user-images.githubusercontent.com/20930745/58753022-e1e15280-84b8-11e9-8821-d9cd1b034e66.png

Source:
https://user-images.githubusercontent.com/20930745/58753024-e3ab1600-84b8-11e9-94a9-a8e4503d9287.png
