### ISSUE TITLE
Video Converter: Format Editor

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10134]
**App Name:** Video Converter: Format Editor
**Bundle ID:** com.james.j.killian.vcv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1440132475">1440132475</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/video-converter-format-editor/id1440132475?mt=8&uo=4">https://itunes.apple.com/us/app/video-converter-format-editor/id1440132475?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** James Killian
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/james-killian/id1440132474?mt=8&uo=4">© James Killian</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/ab/85/a9/ab85a9ec-d3c1-c632-7b27-71418db6f666/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753518-8a46e500-84c0-11e9-829e-1829d30b3e23.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753454-8c5c7400-84bf-11e9-9576-adef6af704be.png)
https://user-images.githubusercontent.com/20930745/58753454-8c5c7400-84bf-11e9-9576-adef6af704be.png

Source:
https://user-images.githubusercontent.com/20930745/58753455-8e263780-84bf-11e9-8d03-51cc7a108f54.png

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753518-8a46e500-84c0-11e9-829e-1829d30b3e23.png)
https://user-images.githubusercontent.com/20930745/58753518-8a46e500-84c0-11e9-829e-1829d30b3e23.png

Source:
https://user-images.githubusercontent.com/20930745/58753522-8d41d580-84c0-11e9-8ca8-d801d1efa155.png
