### ISSUE TITLE
DNSCloak • Secure DNS client

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10131]
**App Name:** DNSCloak • Secure DNS client
**Bundle ID:** org.techcultivation.dnscloak
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1452162351">1452162351</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dnscloak-secure-dns-client/id1452162351?mt=8&uo=4">https://itunes.apple.com/us/app/dnscloak-secure-dns-client/id1452162351?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** Center for the Cultivation of Technology gemeinnutzige GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/center-for-cultivation-technology-gemeinn%C3%BCtzige-gmbh/id1452162350?mt=8&uo=4">© Center for the Cultivation of Technology gemeinnützige GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/d2/40/3a/d2403ad5-d2aa-2455-1022-7459ed4ecb60/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58752843-0556ce00-84b6-11e9-89ca-a641a85c4e76.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58752843-0556ce00-84b6-11e9-89ca-a641a85c4e76.png)
https://user-images.githubusercontent.com/20930745/58752843-0556ce00-84b6-11e9-89ca-a641a85c4e76.png

Source:
https://user-images.githubusercontent.com/20930745/58752844-07209180-84b6-11e9-93d4-8ef2042008dc.png
