### ISSUE TITLE
Samsung Health

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10133]
**App Name:** Samsung Health
**Bundle ID:** com.samsung.health
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1224541484">1224541484</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/samsung-health/id1224541484?mt=8&uo=4">https://itunes.apple.com/us/app/samsung-health/id1224541484?mt=8&uo=4</a>
**App Version:** 1.10.0
**Seller:** Samsung Electronics
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/samsung-electronics-co-ltd/id359580642?mt=8&uo=4">© Samsung Electronics CO.LTD.</a>
**Supported Devices:** iPhone4S-iPhone4S, iPhone5-iPhone5, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/d4/bc/1b/d4bc1b8e-749b-f78e-8739-b247305815e9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58752898-cb39fc00-84b6-11e9-8e29-fbb693c8df2c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58752898-cb39fc00-84b6-11e9-8e29-fbb693c8df2c.png)
https://user-images.githubusercontent.com/20930745/58752898-cb39fc00-84b6-11e9-8e29-fbb693c8df2c.png

Source:
https://user-images.githubusercontent.com/20930745/58752899-cd03bf80-84b6-11e9-93f0-f64be25a708c.png
