### ISSUE TITLE
AnyFont

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10136]
**App Name:** AnyFont
**Bundle ID:** com.flappdev.ifonts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=821560738">821560738</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/anyfont/id821560738?mt=8&uo=4">https://itunes.apple.com/us/app/anyfont/id821560738?mt=8&uo=4</a>
**App Version:** 2.17
**Seller:** Florian Schimanke
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/florian-schimanke/id288399510?mt=8&uo=4">© Florian Schimanke</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/44/ce/90/44ce90fd-655e-691e-fc5f-bd9c496995ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753119-f3c3f500-84ba-11e9-92f8-1eac1414c350.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753119-f3c3f500-84ba-11e9-92f8-1eac1414c350.png)
https://user-images.githubusercontent.com/20930745/58753119-f3c3f500-84ba-11e9-92f8-1eac1414c350.png

Source:
https://user-images.githubusercontent.com/20930745/58753124-01797a80-84bb-11e9-9a1a-ebec6c5c0698.png
