### ISSUE TITLE
Merlin: Find Jobs & Work

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10145]
**App Name:** Merlin: Find Jobs & Work
**Bundle ID:** com.merlinJobs.merlin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1224653168">1224653168</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/merlin-find-jobs-work/id1224653168?mt=8&uo=4">https://itunes.apple.com/us/app/merlin-find-jobs-work/id1224653168?mt=8&uo=4</a>
**App Version:** 3.25.0
**Seller:** ClassifiedJobs, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/classifiedjobs-inc/id1224653167?mt=8&uo=4">© ClassifiedJobs, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/c4/5c/e5/c45ce5a4-5bba-c78d-0ad7-aa360e2f33e4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58757462-28609c80-850d-11e9-83c8-6d894b28ac4c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753728-435aee80-84c4-11e9-9ea6-480778fd4360.png)
https://user-images.githubusercontent.com/20930745/58753728-435aee80-84c4-11e9-9ea6-480778fd4360.png

Source:
https://user-images.githubusercontent.com/20930745/58753730-448c1b80-84c4-11e9-89ab-63203a36c225.png
