### ISSUE TITLE
IHG® Hotel Deals & Rewards

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10147]
**App Name:** IHG® Hotel Deals & Rewards
**Bundle ID:** com.ihg.priorityclubrewards
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368217298">368217298</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ihg-hotel-deals-rewards/id368217298?mt=8&uo=4">https://itunes.apple.com/us/app/ihg-hotel-deals-rewards/id368217298?mt=8&uo=4</a>
**App Version:** 4.28.1
**Seller:** Six Continents Hotels, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/intercontinental-hotels-group/id368217301?mt=8&uo=4">© InterContinental Hotels Group</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/10/f7/e5/10f7e5df-fbdd-99f0-516c-faf553293c67/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753638-b95e5600-84c2-11e9-849e-2dc9c36d19ca.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753638-b95e5600-84c2-11e9-849e-2dc9c36d19ca.png)
(https://user-images.githubusercontent.com/20930745/58753638-b95e5600-84c2-11e9-849e-2dc9c36d19ca.png

Source:
https://user-images.githubusercontent.com/20930745/58753639-ba8f8300-84c2-11e9-8c1b-3ae8fd3104c5.png
