### ISSUE TITLE
SpotHero - Find Parking Nearby

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10148]
**App Name:** SpotHero - Find Parking Nearby
**Bundle ID:** com.spothero.spothero
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=499097243">499097243</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spothero-find-parking-nearby/id499097243?mt=8&uo=4">https://itunes.apple.com/us/app/spothero-find-parking-nearby/id499097243?mt=8&uo=4</a>
**App Version:** 4.29.0
**Seller:** Spot Hero Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/spothero/id499097246?mt=8&uo=4">© SpotHero</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/62/28/67/62286702-8d5e-54ca-cdbf-01ea37fc505e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753600-ef4f0a80-84c1-11e9-8aa2-db0fb39aba85.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753600-ef4f0a80-84c1-11e9-8aa2-db0fb39aba85.png)
(https://user-images.githubusercontent.com/20930745/58753600-ef4f0a80-84c1-11e9-8aa2-db0fb39aba85.png

Source:
https://user-images.githubusercontent.com/20930745/58753602-f1b16480-84c1-11e9-83ac-dfcd69075e1d.png
