### ISSUE TITLE
Fios TV

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10141]
**App Name:** Fios TV
**Bundle ID:** com.verizon.fios.tv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1365137337">1365137337</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fios-tv/id1365137337?mt=8&uo=4">https://itunes.apple.com/us/app/fios-tv/id1365137337?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Verizon Services Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/verizon-services-corporation/id663838713?mt=8&uo=4">© Verizon Services Corporation</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/4b/21/71/4b217167-714e-01bd-2d02-9b0c352043a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753933-6dfa7680-84c7-11e9-9067-2667c56b2bd0.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753933-6dfa7680-84c7-11e9-9067-2667c56b2bd0.png)
https://user-images.githubusercontent.com/20930745/58753933-6dfa7680-84c7-11e9-9067-2667c56b2bd0.png

Source:
ttps://user-images.githubusercontent.com/20930745/58753934-72bf2a80-84c7-11e9-983e-3edaeb1a1852.png
