### ISSUE TITLE
Credit One Bank Mobile

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10146]
**App Name:** Credit One Bank Mobile
**Bundle ID:** com.creditonebank.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1128712763">1128712763</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/credit-one-bank-mobile/id1128712763?mt=8&uo=4">https://itunes.apple.com/us/app/credit-one-bank-mobile/id1128712763?mt=8&uo=4</a>
**App Version:** 2.16
**Seller:** Credit One Bank, National Association
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/credit-one-bank-n-a/id1128712762?mt=8&uo=4">© Credit One Bank, N.A.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/70/08/f7/7008f770-e688-e58c-edd9-8a90bc48165d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58757294-42e54680-850a-11e9-95b2-7ebfe87ec6a5.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753686-96807180-84c3-11e9-891c-df8abfbd7281.png)
https://user-images.githubusercontent.com/20930745/58753686-96807180-84c3-11e9-891c-df8abfbd7281.png

Source:
https://user-images.githubusercontent.com/20930745/58753687-9bddbc00-84c3-11e9-84c9-a7a285250704.png

**Comment by 2Qt2beStr8** [comment]
i made the word "bank" even thicker

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58757294-42e54680-850a-11e9-95b2-7ebfe87ec6a5.png)
(https://user-images.githubusercontent.com/20930745/58757294-42e54680-850a-11e9-95b2-7ebfe87ec6a5.png

Source:
https://user-images.githubusercontent.com/20930745/58757295-44167380-850a-11e9-9a4c-928013b38083.png
