### ISSUE TITLE
Watch NFL Network

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10140]
**App Name:** Watch NFL Network
**Bundle ID:** com.nfl.nflno
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=568543007">568543007</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watch-nfl-network/id568543007?mt=8&uo=4">https://itunes.apple.com/us/app/watch-nfl-network/id568543007?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** NFL Enterprises  LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nfl-enterprises-llc/id389781157?mt=8&uo=4">© NFL Enterprises LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/07/a6/df/07a6dfcf-9b4e-9e8d-7f64-a874011e20ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753990-70110500-84c8-11e9-8676-22db5f6666cf.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753990-70110500-84c8-11e9-8676-22db5f6666cf.png)
https://user-images.githubusercontent.com/20930745/58753990-70110500-84c8-11e9-8676-22db5f6666cf.png

Source:
https://user-images.githubusercontent.com/20930745/58753991-72735f00-84c8-11e9-86c3-61a4cd6c1ac2.png
