### ISSUE TITLE
Chimera

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10149]
**App Name:** Chimera
 **Bundle ID:** com.electrateam.chimera
 **Version:** 1.0.7
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://user-images.githubusercontent.com/2068130/58760339-b0a76780-8536-11e9-99e7-258a37d567cd.png" width="180" height="180" />
 **Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58757648-103e4c80-8510-11e9-9407-7a3bd753c5a6.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58757648-103e4c80-8510-11e9-9407-7a3bd753c5a6.png)
https://user-images.githubusercontent.com/20930745/58757648-103e4c80-8510-11e9-9407-7a3bd753c5a6.png

Source:
https://user-images.githubusercontent.com/20930745/58757649-12081000-8510-11e9-9277-d9b6881de845.png

**Comment by TheRyanKing** [comment]
We need the Sileo app icon as well

**Comment by TheRyanKing** [comment]
Nevermind, I see it
