### ISSUE TITLE
NETGEAR Orbi - WiFi System App

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10143]
**App Name:** NETGEAR Orbi - WiFi System App
**Bundle ID:** com.netgear.orbiprod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1182184397">1182184397</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/netgear-orbi-wifi-system-app/id1182184397?mt=8&uo=4">https://itunes.apple.com/us/app/netgear-orbi-wifi-system-app/id1182184397?mt=8&uo=4</a>
**App Version:** 2.3.6.7
**Seller:** NETGEAR, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/netgear/id394405580?mt=8&uo=4">© NETGEAR</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/6a/3c/c2/6a3cc2bd-e9e1-2dd5-be2d-083a680e2549/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753852-fe37bc00-84c5-11e9-940e-1bd72d347a13.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753852-fe37bc00-84c5-11e9-940e-1bd72d347a13.png)
https://user-images.githubusercontent.com/20930745/58753852-fe37bc00-84c5-11e9-940e-1bd72d347a13.png

Source:
https://user-images.githubusercontent.com/20930745/58753853-ff68e900-84c5-11e9-82e8-706f230545ff.png
