### ISSUE TITLE
Shift Days - Work Tracker

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10144]
**App Name:** Shift Days - Work Tracker
**Bundle ID:** com.limepresso.shiftworkcalendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1016565262">1016565262</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shift-days-work-tracker/id1016565262?mt=8&uo=4">https://itunes.apple.com/us/app/shift-days-work-tracker/id1016565262?mt=8&uo=4</a>
**App Version:** 1.81.7
**Seller:** PIXO Incorporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pixo-incorporation/id541568418?mt=8&uo=4">© PIXO Incorporation</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/03/e7/0e/03e70e6f-8963-58e8-40fb-a0dbafc1c1a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58757350-31506e80-850b-11e9-9cf5-9bd72ba81aaa.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753800-1529de80-84c5-11e9-8eb4-040b7b54b5df.png)
https://user-images.githubusercontent.com/20930745/58753800-1529de80-84c5-11e9-8eb4-040b7b54b5df.png

Source:
https://user-images.githubusercontent.com/20930745/58753801-165b0b80-84c5-11e9-909b-45a0056135b6.png

**Comment by TheRyanKing** [comment]
Perhaps the right part of the sun/moon could be transparent with just the outline

**Comment by 2Qt2beStr8** [comment]
like this?

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58757350-31506e80-850b-11e9-9cf5-9bd72ba81aaa.png)
https://user-images.githubusercontent.com/20930745/58757350-31506e80-850b-11e9-9cf5-9bd72ba81aaa.png

Source:
https://user-images.githubusercontent.com/20930745/58757351-32819b80-850b-11e9-829b-5380597e8c9d.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet which one shoule we take?

**Comment by dreamnet** [comment]
@2Qt2beStr8 Personally I like your first one better, but I think we should wait for @TheRyanKing .

**Comment by 2Qt2beStr8** [comment]
@dreamnet ok
