### ISSUE TITLE
GNC LiveWell

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#10142]
**App Name:** GNC LiveWell
**Bundle ID:** com.gnc.GNC
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=413258417">413258417</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gnc-livewell/id413258417?mt=8&uo=4">https://itunes.apple.com/us/app/gnc-livewell/id413258417?mt=8&uo=4</a>
**App Version:** 8.1.2
**Seller:** General Nutrition Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gnc/id413258420?mt=8&uo=4">© GNC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/b4/64/b1/b464b167-2b6a-a4d3-0c72-0c5ed0510d4e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58757546-264b0d80-850e-11e9-9edd-9ec87477951b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58753904-c2e9bd00-84c6-11e9-9a59-90cfdb7956c0.png)
https://user-images.githubusercontent.com/20930745/58753904-c2e9bd00-84c6-11e9-9a59-90cfdb7956c0.png

Source:
https://user-images.githubusercontent.com/20930745/58753906-ca10cb00-84c6-11e9-9a55-d07caa8188b1.png

**Comment by 2Qt2beStr8** [comment]
live well thicker looks better
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58757546-264b0d80-850e-11e9-9edd-9ec87477951b.png)
(https://user-images.githubusercontent.com/20930745/58757546-264b0d80-850e-11e9-9edd-9ec87477951b.png

Source:
https://user-images.githubusercontent.com/20930745/58757547-2814d100-850e-11e9-9486-43d14ef5440b.png
