### ISSUE TITLE
UnivisionNow En Vivo/On Demand

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10159]
**App Name:** UnivisionNow En Vivo/On Demand
**Bundle ID:** com.univision.univisionnow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049321283">1049321283</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/univisionnow-en-vivo-on-demand/id1049321283?mt=8&uo=4">https://itunes.apple.com/us/app/univisionnow-en-vivo-on-demand/id1049321283?mt=8&uo=4</a>
**App Version:** 3.9
**Seller:** Univision
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/univision-interactive-media-inc/id353665653?mt=8&uo=4">© Univision Interactive Media, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/97/05/ba/9705ba42-a3fa-5cea-b02e-8131ccf03c7f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58814825-b9776680-8626-11e9-89c1-5bba0e4446d9.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58814825-b9776680-8626-11e9-89c1-5bba0e4446d9.png)
https://user-images.githubusercontent.com/20930745/58814825-b9776680-8626-11e9-89c1-5bba0e4446d9.png

Source:
https://user-images.githubusercontent.com/20930745/58814830-bbd9c080-8626-11e9-87fb-d78264710507.png
