### ISSUE TITLE
Nationwide Mobile

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10155]
**App Name:** Nationwide Mobile
**Bundle ID:** com.nationwide.AccidentToolkit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=311627534">311627534</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nationwide-mobile/id311627534?mt=8&uo=4">https://itunes.apple.com/us/app/nationwide-mobile/id311627534?mt=8&uo=4</a>
**App Version:** 8.25
**Seller:** Nationwide Mutual Insurance Company
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nationwide-mutual-insurance/id1319471084?mt=8&uo=4">© Nationwide Mutual Insurance</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/bc/64/30/bc643055-da9d-6eeb-ca80-7004cd8a7034/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58812556-6a2f3700-8622-11e9-9a13-298b14be6cd5.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58812556-6a2f3700-8622-11e9-9a13-298b14be6cd5.png)
https://user-images.githubusercontent.com/20930745/58812556-6a2f3700-8622-11e9-9a13-298b14be6cd5.png

Source:
https://user-images.githubusercontent.com/20930745/58812554-6a2f3700-8622-11e9-8e41-ab9c45e9f3b6.png
