### ISSUE TITLE
Extreme Road Trip

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1015]
**App Name:** Extreme Road Trip
**Bundle ID:** ca.roofdog.roadtrip
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445060903">445060903</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/extreme-road-trip/id445060903?mt=8&uo=4">https://itunes.apple.com/us/app/extreme-road-trip/id445060903?mt=8&uo=4</a>
**App Version:** 1.18.1
**Seller:** Roofdog Games inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/roofdog-games/id445060906?uo=4">© Roofdog Games</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple71/v4/81/68/2c/81682ccd-7b8b-d079-211c-36f8e5441484/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41173894-c43f8366-6b58-11e8-934a-c9e8d7f8c7d6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41173894-c43f8366-6b58-11e8-934a-c9e8d7f8c7d6.png)
https://user-images.githubusercontent.com/2068130/41173894-c43f8366-6b58-11e8-934a-c9e8d7f8c7d6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41173913-d369be4c-6b58-11e8-94f7-250eab71efb7.png
