### ISSUE TITLE
Lennox iComfort Wi-Fi

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10151]
**App Name:** Lennox iComfort Wi-Fi
**Bundle ID:** com.lennox.icomfortwifi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527608198">527608198</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lennox-icomfort-wi-fi/id527608198?mt=8&uo=4">https://itunes.apple.com/us/app/lennox-icomfort-wi-fi/id527608198?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Lennox Industries
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lennox-industries/id355049651?mt=8&uo=4">© Lennox Industries</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple122/v4/a5/05/d7/a505d7e5-adbb-d185-7076-dd6e21adcbe1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58810994-49b1ad80-861f-11e9-82c2-799e8739bf9f.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58810994-49b1ad80-861f-11e9-82c2-799e8739bf9f.png)
https://user-images.githubusercontent.com/20930745/58810994-49b1ad80-861f-11e9-82c2-799e8739bf9f.png

Source:
https://user-images.githubusercontent.com/20930745/58810999-4b7b7100-861f-11e9-8c8b-6157ab6407ac.png
