### ISSUE TITLE
ADT Pulse ®

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10152]
**App Name:** ADT Pulse ®
**Bundle ID:** com.ADT.ADTDistribution
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=355736423">355736423</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adt-pulse/id355736423?mt=8&uo=4">https://itunes.apple.com/us/app/adt-pulse/id355736423?mt=8&uo=4</a>
**App Version:** 8.7.2
**Seller:** ADT LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/adt-llc/id355736426?mt=8&uo=4">© ADT LLC</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/bd/7b/b9/bd7bb909-f409-68fc-6b76-49d74de247a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58811420-13c0f900-8620-11e9-8842-a81c83063097.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58811420-13c0f900-8620-11e9-8842-a81c83063097.png)
https://user-images.githubusercontent.com/20930745/58811420-13c0f900-8620-11e9-8842-a81c83063097.png

Source:
https://user-images.githubusercontent.com/20930745/58811427-158abc80-8620-11e9-9798-1772c5f88b0a.png
