### ISSUE TITLE
Xoom Money Transfer

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10154]
**App Name:** Xoom Money Transfer
**Bundle ID:** com.xoom.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=529615515">529615515</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xoom-money-transfer/id529615515?mt=8&uo=4">https://itunes.apple.com/us/app/xoom-money-transfer/id529615515?mt=8&uo=4</a>
**App Version:** 6.7
**Seller:** Xoom Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/xoom-corporation/id529615518?mt=8&uo=4">© Xoom Corporation</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/5e/5a/ec/5e5aec02-d428-ebfb-f264-025d0a3316ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58812258-bf1e7d80-8621-11e9-9ba7-74ae548aa02b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58812258-bf1e7d80-8621-11e9-9ba7-74ae548aa02b.png)
https://user-images.githubusercontent.com/20930745/58812258-bf1e7d80-8621-11e9-9ba7-74ae548aa02b.png

Source:
https://user-images.githubusercontent.com/20930745/58812260-c04faa80-8621-11e9-9129-5163d1256b67.png
