### ISSUE TITLE
Nike SNKRS

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10157]
**App Name:** Nike SNKRS
**Bundle ID:** com.nike.onenikecommerce
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911130812">911130812</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nike-snkrs/id911130812?mt=8&uo=4">https://itunes.apple.com/us/app/nike-snkrs/id911130812?mt=8&uo=4</a>
**App Version:** 3.11.1
**Seller:** Nike, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nike-inc/id301521406?mt=8&uo=4">© Nike, Inc</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/5e/5a/2f/5e5a2f2b-8b8d-f7e1-d994-0e75e7146b10/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58813446-1a516f80-8624-11e9-9edb-7416f9cc1277.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58813446-1a516f80-8624-11e9-9edb-7416f9cc1277.png)
https://user-images.githubusercontent.com/20930745/58813446-1a516f80-8624-11e9-9edb-7416f9cc1277.png

Source:
https://user-images.githubusercontent.com/20930745/58813450-1cb3c980-8624-11e9-96a6-d2d40ebbe20e.png
