### ISSUE TITLE
Toyota Entune

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10158]
**App Name:** Toyota Entune
**Bundle ID:** com.toyota.entune
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=453140446">453140446</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/toyota-entune/id453140446?mt=8&uo=4">https://itunes.apple.com/us/app/toyota-entune/id453140446?mt=8&uo=4</a>
**App Version:** 1.27.770
**Seller:** Toyota Motor Sales, U.S.A., Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/toyota-motor-sales-u-s-a-inc/id327347182?mt=8&uo=4">© Toyota Motor Sales, U.S.A., Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/19/d5/20/19d520cf-6dc9-f18d-5abf-a6d1f7737d98/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58816641-2b9d7a80-862a-11e9-9711-8ff4d64fe0e1.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58816641-2b9d7a80-862a-11e9-9711-8ff4d64fe0e1.png)
https://user-images.githubusercontent.com/20930745/58816641-2b9d7a80-862a-11e9-9711-8ff4d64fe0e1.png

Source:
https://user-images.githubusercontent.com/20930745/58816643-2ccea780-862a-11e9-85c4-377c65de870e.png
