### ISSUE TITLE
Rachio

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10153]
**App Name:** Rachio
**Bundle ID:** com.rachio.Iro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=864325098">864325098</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rachio/id864325098?mt=8&uo=4">https://itunes.apple.com/us/app/rachio/id864325098?mt=8&uo=4</a>
**App Version:** 3.13.1
**Seller:** RACHIO, INC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rachio-inc/id864325101?mt=8&uo=4">© RACHIO, INC.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/3d/83/a9/3d83a912-3b07-760b-6f4a-f2f778095064/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58811865-e294f880-8620-11e9-902d-11f62fd6f6ca.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58811865-e294f880-8620-11e9-902d-11f62fd6f6ca.png)
https://user-images.githubusercontent.com/20930745/58811865-e294f880-8620-11e9-902d-11f62fd6f6ca.png

Source:
https://user-images.githubusercontent.com/20930745/58811867-e45ebc00-8620-11e9-8e25-34d981697f27.png
