### ISSUE TITLE
Drifty Race!

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10150]
**App Name:** Drifty Race!
**Bundle ID:** com.vm.drift
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1454780067">1454780067</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/drifty-race/id1454780067?mt=8&uo=4">https://itunes.apple.com/us/app/drifty-race/id1454780067?mt=8&uo=4</a>
**App Version:** 1.4.7
**Seller:** SEIGEIMS, OOO
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/saygames-llc/id1405039362?mt=8&uo=4">© SayGames LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/92/57/21/925721c1-a86c-319f-3190-bc233312f5d2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59568714-d415fa80-907e-11e9-8ede-1afcdcec3866.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59568714-d415fa80-907e-11e9-8ede-1afcdcec3866.png)
https://user-images.githubusercontent.com/2068130/59568714-d415fa80-907e-11e9-8ede-1afcdcec3866.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59568717-e3954380-907e-11e9-955d-30b90e9a50d5.png
