### ISSUE TITLE
MyADT: ADT Customer Service – Home and Small Business Security Monitoring

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10156]
**App Name:** MyADT: ADT Customer Service – Home and Small Business Security Monitoring
**Bundle ID:** com.adt.myadtmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=860107112">860107112</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myadt-adt-customer-service-home-small-business-security/id860107112?mt=8&uo=4">https://itunes.apple.com/us/app/myadt-adt-customer-service-home-small-business-security/id860107112?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** ADT LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/adt-llc/id355736426?mt=8&uo=4">© ADT LLC</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple6/v4/ab/46/80/ab468067-cedd-895f-ad8f-1a4442984731/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58813138-74056a00-8623-11e9-99b6-350d8ce157d3.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58813138-74056a00-8623-11e9-99b6-350d8ce157d3.png)
https://user-images.githubusercontent.com/20930745/58813138-74056a00-8623-11e9-99b6-350d8ce157d3.png

Source:
https://user-images.githubusercontent.com/20930745/58813141-75369700-8623-11e9-8922-e6f48d2f8ddf.png
