### ISSUE TITLE
UVO eServices

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10167]
**App Name:** UVO eServices
**Bundle ID:** com.kia.eservices
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=588729103">588729103</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/uvo-eservices/id588729103?mt=8&uo=4">https://itunes.apple.com/us/app/uvo-eservices/id588729103?mt=8&uo=4</a>
**App Version:** 3.5.0
**Seller:** Kia Motors America
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kia-motors-america-inc/id588729106?mt=8&uo=4">© Kia Motors America, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/33/d2/69/33d26965-4afb-db4a-5547-810b3ffdaa29/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58962551-c70a2900-87ab-11e9-8a70-c85e44225898.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58830089-81b4f280-8617-11e9-900a-b18d13abc10f.png)
https://user-images.githubusercontent.com/2313873/58830089-81b4f280-8617-11e9-900a-b18d13abc10f.png

___
Source:
https://user-images.githubusercontent.com/2313873/58830083-7cf03e80-8617-11e9-896a-c00b12c9b208.png

**Comment by 2Qt2beStr8** [comment]
i did some small corrections (roundet corners), but credits goes to @XPEric 

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58962551-c70a2900-87ab-11e9-8a70-c85e44225898.png)
https://user-images.githubusercontent.com/20930745/58962551-c70a2900-87ab-11e9-8a70-c85e44225898.png

Sources:
https://user-images.githubusercontent.com/20930745/58962555-c96c8300-87ab-11e9-8bbb-ffd87d9f1923.png
