### ISSUE TITLE
Privacy.com

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10162]
**App Name:** Privacy.com
**Bundle ID:** com.privacy.paybeta
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1040298266">1040298266</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/privacy-com/id1040298266?mt=8&uo=4">https://itunes.apple.com/us/app/privacy-com/id1040298266?mt=8&uo=4</a>
**App Version:** 2.11.1
**Seller:** Pay With Privacy, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pay-with-privacy-inc/id1040298265?mt=8&uo=4">© Pay With Privacy, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/66/e3/f5/66e3f5f3-676b-42b8-260f-da45bf258425/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58828446-c22b6500-8645-11e9-91ad-afb6ef9a6dca.png)

**Comment by XPEric** [comment]
![privacy](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58821010-16145a80-8602-11e9-858d-dd34596cf280.png)
https://user-images.githubusercontent.com/2313873/58821010-16145a80-8602-11e9-858d-dd34596cf280.png

___
Source:
https://user-images.githubusercontent.com/2313873/58820999-10b71000-8602-11e9-81f4-3aec399f3f63.png

**Comment by 2Qt2beStr8** [comment]
@XPEric nice, but you have to think highly to the right size

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58828446-c22b6500-8645-11e9-91ad-afb6ef9a6dca.png)
(https://user-images.githubusercontent.com/20930745/58828446-c22b6500-8645-11e9-91ad-afb6ef9a6dca.png

Source:
https://user-images.githubusercontent.com/20930745/58828449-c48dbf00-8645-11e9-9e88-60b0a705ba0a.png

**Comment by XPEric** [comment]
I originally made it larger, but I thought it looked strange that way.

**Comment by 2Qt2beStr8** [comment]
hmm … but it looks as the original one
