### ISSUE TITLE
Outback

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10164]
**App Name:** Outback
**Bundle ID:** com.outback.connectedcustomertampa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035361376">1035361376</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/outback/id1035361376?mt=8&uo=4">https://itunes.apple.com/us/app/outback/id1035361376?mt=8&uo=4</a>
**App Version:** 3.12.5
**Seller:** Outback Steakhouse of Florida, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/outback-steakhouse/id562307986?mt=8&uo=4">© Outback Steakhouse</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/96/fc/10/96fc1030-f092-8dd5-df72-06f0e5b25454/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59122725-c44e3600-895b-11e9-8423-8105bcdfdfc4.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58821746-bb7bfe00-8603-11e9-9ead-8148169c2d7b.png)
https://user-images.githubusercontent.com/2313873/58821746-bb7bfe00-8603-11e9-9ead-8148169c2d7b.png

___
Source:
https://user-images.githubusercontent.com/2313873/58821736-b6b74a00-8603-11e9-9140-4a241f115231.png

**Comment by 2Qt2beStr8** [comment]
@XPEric can you remove the ® and maybe make the Word Steakhouse a little bit thicker?

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58828618-d8203200-8613-11e9-8b01-2a960b01ba76.png)
https://user-images.githubusercontent.com/2313873/58828618-d8203200-8613-11e9-8b01-2a960b01ba76.png


___
Source:
https://user-images.githubusercontent.com/2313873/58828646-e53d2100-8613-11e9-8058-33629ea14495.png

**Comment by XPEric** [comment]
This better?

**Comment by 2Qt2beStr8** [comment]
yes it is
