### ISSUE TITLE
ChowNow

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10169]
**App Name:** ChowNow
**Bundle ID:** com.ChowNow.Marketplace
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1210943577">1210943577</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chownow/id1210943577?mt=8&uo=4">https://itunes.apple.com/us/app/chownow/id1210943577?mt=8&uo=4</a>
**App Version:** 1.2.4
**Seller:** ChowNow, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chownow/id553996348?mt=8&uo=4">© ChowNow</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/c8/04/f7/c804f7a0-1b8a-51fd-c9ab-9c0907ab31e4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58963198-0a18cc00-87ad-11e9-9299-4cf94f1ea228.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58831258-4e279780-861a-11e9-83cc-542dfec20894.png)
https://user-images.githubusercontent.com/2313873/58831258-4e279780-861a-11e9-83cc-542dfec20894.png

___
Source:
https://user-images.githubusercontent.com/2313873/58831252-4536c600-861a-11e9-85c3-3f1f1f8f86d0.png

**Comment by 2Qt2beStr8** [comment]
i did some small corrections, but credits goes to @XPEric 

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58963261-23ba1380-87ad-11e9-9a2f-eeaa1ea62b7e.png)
(https://user-images.githubusercontent.com/20930745/58963261-23ba1380-87ad-11e9-9a2f-eeaa1ea62b7e.png

Source:
https://user-images.githubusercontent.com/20930745/58963267-2583d700-87ad-11e9-83d8-e687aeddd2d8.png
