### ISSUE TITLE
ParkNYC Powered by Parkmobile

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10165]
**App Name:** ParkNYC Powered by Parkmobile
**Bundle ID:** us.parkmobile.nycdot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1135073877">1135073877</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parknyc-powered-by-parkmobile/id1135073877?mt=8&uo=4">https://itunes.apple.com/us/app/parknyc-powered-by-parkmobile/id1135073877?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Parkmobile USA, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/parkmobile-usa-inc/id365399302?mt=8&uo=4">© Parkmobile USA, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/b3/70/f6/b370f6fa-5eb4-80c7-15e4-438f8211c8b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58979672-d8186180-87ce-11e9-92e9-ea45382fa0ee.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58822145-cbe0a880-8604-11e9-9bff-1ce23a4c7ebf.png)
https://user-images.githubusercontent.com/2313873/58822145-cbe0a880-8604-11e9-9bff-1ce23a4c7ebf.png

___
Source:
https://user-images.githubusercontent.com/2313873/58822131-c4210400-8604-11e9-9fdc-4ad71021cc57.png

**Comment by 2Qt2beStr8** [comment]
i did some small corrections, but credits goes to @XPEric

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58979672-d8186180-87ce-11e9-92e9-ea45382fa0ee.png)
https://user-images.githubusercontent.com/20930745/58979672-d8186180-87ce-11e9-92e9-ea45382fa0ee.png

Source:
https://user-images.githubusercontent.com/20930745/58979675-da7abb80-87ce-11e9-85da-8aeb3e9c1dd6.png
