### ISSUE TITLE
USSFCU - Mobile

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10161]
**App Name:** USSFCU - Mobile
**Bundle ID:** com.fi6841.godough
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=865515852">865515852</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ussfcu-mobile/id865515852?mt=8&uo=4">https://itunes.apple.com/us/app/ussfcu-mobile/id865515852?mt=8&uo=4</a>
**App Version:** 4.31.90
**Seller:** United States Senate Federal Credit Union
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/united-states-senate-federal-credit-union/id594239139?mt=8&uo=4">© United States Senate Federal Credit Union</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/85/8c/5c/858c5cbb-a3d8-71eb-2006-f97d2e372239/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58959563-a6d76b80-87a5-11e9-9d1d-44a6321cfb8b.png)

**Comment by XPEric** [comment]
![ussfcu](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58820675-3c85c600-8601-11e9-9141-4a012cb7c94b.png)
https://user-images.githubusercontent.com/2313873/58820675-3c85c600-8601-11e9-9141-4a012cb7c94b.png

___
Source:
https://user-images.githubusercontent.com/2313873/58820690-45769780-8601-11e9-93b5-ea0075a33f54.png

**Comment by 2Qt2beStr8** [comment]
i did some small corrections, but credits goes to @XPEric 

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58959563-a6d76b80-87a5-11e9-9d1d-44a6321cfb8b.png)
https://user-images.githubusercontent.com/20930745/58959563-a6d76b80-87a5-11e9-9d1d-44a6321cfb8b.png

Source:
https://user-images.githubusercontent.com/20930745/58959571-a939c580-87a5-11e9-951a-ec6f5060ae09.png
