### ISSUE TITLE
Smart Remote - Samsung SmartTV

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10160]
**App Name:** Smart Remote - Samsung SmartTV
**Bundle ID:** com.tinacinc.samsungremote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1153897380">1153897380</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smart-remote-samsung-smarttv/id1153897380?mt=8&uo=4">https://itunes.apple.com/us/app/smart-remote-samsung-smarttv/id1153897380?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** TINAC Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tinac-inc/id539875795?mt=8&uo=4">© TINAC Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/74/b8/29/74b82940-b404-1c5d-93ab-661bcb37502c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58815642-45d65900-8628-11e9-8c78-b28fae16c077.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58815642-45d65900-8628-11e9-8c78-b28fae16c077.png)
https://user-images.githubusercontent.com/20930745/58815642-45d65900-8628-11e9-8c78-b28fae16c077.png

Source_
https://user-images.githubusercontent.com/20930745/58815645-47a01c80-8628-11e9-8e76-9760e531b3e3.png
