### ISSUE TITLE
freenet FUNK

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10176]
**App Name:** freenet FUNK
**Bundle ID:** de.freenet.funk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1457849693">1457849693</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/freenet-funk/id1457849693?mt=8&uo=4">https://itunes.apple.com/de/app/freenet-funk/id1457849693?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Freenet AG
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/mobilcom-debitel/id405954758?mt=8&uo=4">© mobilcom-debitel</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/3c/dd/b0/3cddb066-4246-a5e8-2ed0-2084b444de56/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59181069-c506e800-8b66-11e9-85cd-084d64ccacd2.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59181069-c506e800-8b66-11e9-85cd-084d64ccacd2.png)
https://user-images.githubusercontent.com/20930745/59181069-c506e800-8b66-11e9-85cd-084d64ccacd2.png

Source:
https://user-images.githubusercontent.com/20930745/59181079-c6d0ab80-8b66-11e9-938b-f601a8a87d0f.png
