### ISSUE TITLE
Wordscapes

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10175]
**App Name:** Wordscapes
**Bundle ID:** com.peoplefun.wordcross
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1207472156">1207472156</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wordscapes/id1207472156?mt=8&uo=4">https://itunes.apple.com/us/app/wordscapes/id1207472156?mt=8&uo=4</a>
**App Version:** 1.0.63
**Seller:** PeopleFun, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/peoplefun-inc/id517840947?mt=8&uo=4">© PeopleFun, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/21/9d/65/219d6548-2f56-6b58-17e5-79c414274a6e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59845249-3a3f9d80-935d-11e9-9b55-191e2520d996.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58843597-2f88c700-8641-11e9-9c15-281231dfa06a.png)
https://user-images.githubusercontent.com/2313873/58843597-2f88c700-8641-11e9-9c15-281231dfa06a.png

___
Source:
https://user-images.githubusercontent.com/2313873/58843594-2bf54000-8641-11e9-8b47-67e97f77fb79.png

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58843736-cc4b6480-8641-11e9-8622-e748a686a5f6.png)
https://user-images.githubusercontent.com/2313873/58843736-cc4b6480-8641-11e9-8622-e748a686a5f6.png

___
Source:
https://user-images.githubusercontent.com/2313873/58843732-c6ee1a00-8641-11e9-9e12-405fea5a6116.png

**Comment by dreamnet** [comment]
❓ 
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59845249-3a3f9d80-935d-11e9-9b55-191e2520d996.png)
https://user-images.githubusercontent.com/2068130/59845249-3a3f9d80-935d-11e9-9b55-191e2520d996.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59845287-49265000-935d-11e9-824b-3af000697711.png
