### ISSUE TITLE
PhotoPrint Pro

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10177]
**App Name:** PhotoPrint Pro
**Bundle ID:** com.palugu.photoprint
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=394141528">394141528</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photoprint-pro/id394141528?mt=8&uo=4">https://itunes.apple.com/us/app/photoprint-pro/id394141528?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** palugu Software
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/palugu-software/id332737629?mt=8&uo=4">© palugu Software</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/b6/08/ac/b608aceb-9946-8c37-aa44-7e234f3be7eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59301145-3773e700-8c91-11e9-8ee3-370e5e3e9759.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59301145-3773e700-8c91-11e9-8ee3-370e5e3e9759.png)
https://user-images.githubusercontent.com/2068130/59301145-3773e700-8c91-11e9-8ee3-370e5e3e9759.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59301174-4e1a3e00-8c91-11e9-9ab8-66dfd799df19.png
