### ISSUE TITLE
Postmates - Fleet

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10174]
**App Name:** Postmates - Fleet
**Bundle ID:** com.postmates.fleet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1173661815">1173661815</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/postmates-fleet/id1173661815?mt=8&uo=4">https://itunes.apple.com/us/app/postmates-fleet/id1173661815?mt=8&uo=4</a>
**App Version:** 4.26.9
**Seller:** Postmates Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/postmates-inc/id486092873?mt=8&uo=4">© Postmates Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/b3/f6/ba/b3f6bac1-024c-7a79-b1a0-2577bf1c2427/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58965213-7e08a380-87b0-11e9-8a3d-425e903bd463.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58842786-bf2c7680-863d-11e9-847f-4f9f172a2fda.png)
https://user-images.githubusercontent.com/2313873/58842786-bf2c7680-863d-11e9-847f-4f9f172a2fda.png

___
Source:
https://user-images.githubusercontent.com/2313873/58842782-bb005900-863d-11e9-8009-9c49233b7aa2.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58965213-7e08a380-87b0-11e9-8a3d-425e903bd463.png)
https://user-images.githubusercontent.com/20930745/58965213-7e08a380-87b0-11e9-8a3d-425e903bd463.png

Source:
https://user-images.githubusercontent.com/20930745/58965216-7f39d080-87b0-11e9-9335-21386151e5ea.png
