### ISSUE TITLE
CardioBot - Heart Rate Tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10179]
**App Name:** CardioBot - Heart Rate Tracker
**Bundle ID:** com.aaplab.CardioBot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1149412984">1149412984</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cardiobot-heart-rate-tracker/id1149412984?uo=4">https://apps.apple.com/us/app/cardiobot-heart-rate-tracker/id1149412984?uo=4</a>
**App Version:** 4.0.3
**Seller:** Majid Jabrayilov
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/majid-jabrayilov/id1149412983?uo=4">© Majid Jabrayilov</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/ae/81/d0/ae81d06c-de71-7f7a-c2cd-2f1fe30f9ea7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59284412-7e9bb100-8c6c-11e9-992a-91a84bda2b6d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59284412-7e9bb100-8c6c-11e9-992a-91a84bda2b6d.png)
https://user-images.githubusercontent.com/20930745/59284412-7e9bb100-8c6c-11e9-992a-91a84bda2b6d.png

Source:
https://user-images.githubusercontent.com/20930745/59284414-80657480-8c6c-11e9-8f0e-b391fff271c9.png
