### ISSUE TITLE
AncestryDNA

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10172]
**App Name:** AncestryDNA
**Bundle ID:** com.ancestry.dna
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=971585438">971585438</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ancestrydna/id971585438?mt=8&uo=4">https://itunes.apple.com/us/app/ancestrydna/id971585438?mt=8&uo=4</a>
**App Version:** 4.12
**Seller:** Ancestry.com Operations Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ancestry-com/id349554266?mt=8&uo=4">© Ancestry.com</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/74/9e/46/749e4644-3152-1f1d-e279-8aea900afcef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58964638-86141380-87af-11e9-9fee-cebf506886c2.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58842073-88089600-863a-11e9-882a-9aa68788dd69.png)
https://user-images.githubusercontent.com/2313873/58842073-88089600-863a-11e9-882a-9aa68788dd69.png

___
Source:
https://user-images.githubusercontent.com/2313873/58842066-8212b500-863a-11e9-904b-80528baf4837.png

**Comment by 2Qt2beStr8** [comment]
i did some small corrections (roundet corners), but credits goes to

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58964682-96c48980-87af-11e9-8d28-e42764eaf846.png)
https://user-images.githubusercontent.com/20930745/58964682-96c48980-87af-11e9-8d28-e42764eaf846.png

Source:
https://user-images.githubusercontent.com/20930745/58964686-988e4d00-87af-11e9-9bc3-9a35e8a592a9.png
