### ISSUE TITLE
Facebook Pages Manager

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#1017]
**App Name:** Facebook Pages Manager
**Bundle ID:** com.facebook.PageAdminApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514643583">514643583</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facebook-pages-manager/id514643583?mt=8&uo=4">https://itunes.apple.com/us/app/facebook-pages-manager/id514643583?mt=8&uo=4</a>
**App Version:** 26.0
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/facebook-inc./id284882218?uo=4>© Facebook, Inc.</a>
**Supported Devices:** iPodTouchFifthGen, iPadMini4G, iPhone5, iPadFourthGen4G, iPad23G, iPhone5c, iPadFourthGen, iPhone6Plus, iPadThirdGen4G, iPhone5s, iPhone4, iPadThirdGen, iPhone4S, iPad2Wifi, iPadMini, iPhone6
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/1c/3b/2e/1c3b2e7a-d16c-c62f-0dc0-e606151e844a/mzl.aorzszgt.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8535523/1bc91486-240c-11e5-90da-118c44bbf332.png)

**Comment by Trubbel** [comment]
Icon has been updated.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8535523/1bc91486-240c-11e5-90da-118c44bbf332.png)
https://cloud.githubusercontent.com/assets/3090247/8535523/1bc91486-240c-11e5-90da-118c44bbf332.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8535522/1bc8663a-240c-11e5-8d21-48e41bedf1ad.png)

**Comment by Trubbel** [comment]
@ivanov007 :+1:
