### ISSUE TITLE
DayCalc Pro - Note Calculator

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10178]
**App Name:** DayCalc Pro - Note Calculator
**Bundle ID:** com.hcsystem.calculator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=654444242">654444242</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/daycalc-pro-note-calculator/id654444242?uo=4">https://apps.apple.com/us/app/daycalc-pro-note-calculator/id654444242?uo=4</a>
**App Version:** 5.4
**Seller:** LingLing Chen
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lingling-chen/id654444245?uo=4">© LingLing Chen</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/7e/d0/a4/7ed0a4dc-8165-dcde-dfc4-80c1ae7ade07/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59296402-34272e00-8c86-11e9-9a55-537907b00e86.png)

**Comment by dreamnet** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59296402-34272e00-8c86-11e9-9a55-537907b00e86.png)
https://user-images.githubusercontent.com/20930745/59296402-34272e00-8c86-11e9-9a55-537907b00e86.png

Source:
https://user-images.githubusercontent.com/20930745/59296405-35585b00-8c86-11e9-920a-b25000eb1788.png
Icon by @2Qt2beStr8
