### ISSUE TITLE
corporate benefits

### ISSUE THREAD

**Issue by btc187** [glasklart/hd#10189]
**App Name:** corporate benefits
**Bundle ID:** de.mitarbeiterangebote.benefits
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1238117425">1238117425</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/corporate-benefits/id1238117425?uo=4">https://apps.apple.com/de/app/corporate-benefits/id1238117425?uo=4</a>
**App Version:** 2.0.1
**Seller:** Corporate Benefits GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/corporate-benefits-gmbh/id1238117424?uo=4">© corporate benefits GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/e9/30/42/e9304277-47f9-8dd1-cefc-8c0c26fdba70/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/6958830/59253729-31bad900-8c72-11e9-8627-d84717a7434c.png)

**Comment by cspadazzi** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/6958830/59253729-31bad900-8c72-11e9-8627-d84717a7434c.png)
Source:
https://user-images.githubusercontent.com/6958830/59253730-31bad900-8c72-11e9-95f6-baf92beca6b4.png
