### ISSUE TITLE
Nural - tasks, notes & chat

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10184]
**App Name:** Nural - tasks, notes & chat
**Bundle ID:** com.Nural-Technologies.iPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1436414249">1436414249</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/nural-tasks-notes-chat/id1436414249?uo=4">https://apps.apple.com/us/app/nural-tasks-notes-chat/id1436414249?uo=4</a>
**App Version:** 1.2.4
**Seller:** Nural Technologies W.L.L.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nural-technologies-w-l-l/id1436414248?uo=4">© Nural Technologies W.L.L.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/08/03/98/0803988c-47e2-06ea-9f4f-dc8ab8920c7c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/6958830/59253075-d4725800-8c70-11e9-89db-227bbea18140.png)

**Comment by cspadazzi** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/6958830/59253075-d4725800-8c70-11e9-89db-227bbea18140.png)
Source:
https://user-images.githubusercontent.com/6958830/59253086-db00cf80-8c70-11e9-85c1-c70f42beb57f.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet ich glaube die icons sind alle minimal zu klein. Oder täuscht mich das?

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59295402-e3aed100-8c83-11e9-8bc7-17038d72f926.png)
https://user-images.githubusercontent.com/20930745/59295402-e3aed100-8c83-11e9-8bc7-17038d72f926.png

Source:
![nuraltasksnotes](https://user-images.githubusercontent.com/20930745/59295406-e4dffe00-8c83-11e9-8337-cb141a7f46be.png)

**Comment by dreamnet** [comment]
@2Qt2beStr8 Du täuscht Dich nicht, ich habe in #5004 schon einen Kommentar hinterlassen.
