### ISSUE TITLE
MyQ Garage & Access Control

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10181]
**App Name:** MyQ Garage & Access Control
**Bundle ID:** com.myliftmaster.myq
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=456282559">456282559</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myq-garage-access-control/id456282559?uo=4">https://apps.apple.com/us/app/myq-garage-access-control/id456282559?uo=4</a>
**App Version:** 4.131.1
**Seller:** The Chamberlain Group, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-chamberlain-group-inc/id456282562?uo=4">© The Chamberlain Group, Inc.</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/4c/d5/35/4cd53571-df58-3cd8-fe52-9eaf5b0690bf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/6958830/59253329-4a76bf00-8c71-11e9-9cab-c2be3455da2c.png)

**Comment by cspadazzi** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/6958830/59253329-4a76bf00-8c71-11e9-9cab-c2be3455da2c.png)
Source:
https://user-images.githubusercontent.com/6958830/59253331-4a76bf00-8c71-11e9-9c96-1c59ab331a2c.png
