### ISSUE TITLE
Klarna - Shop now. Pay later

### ISSUE THREAD

**Issue by btc187** [glasklart/hd#10186]
**App Name:** Klarna - Shop now. Pay later
**Bundle ID:** com.klarna.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1115120118">1115120118</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/klarna-shop-now-pay-later/id1115120118?mt=8&uo=4">https://itunes.apple.com/us/app/klarna-shop-now-pay-later/id1115120118?mt=8&uo=4</a>
**App Version:** 19.23.1
**Seller:** Klarna Bank AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/klarna-bank-ab/id1075880092?mt=8&uo=4">© Klarna Bank AB</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/98/d3/0d/98d30df4-e4df-0661-225c-4b5c9925e86f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59285992-33cf6880-8c6f-11e9-9824-597b14e9bbb3.png)

**Comment by cspadazzi** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/6958830/59253172-fec41580-8c70-11e9-82a5-7ea3de3e6c6a.png)
Source:
https://user-images.githubusercontent.com/6958830/59253173-fec41580-8c70-11e9-81a2-ae1a6fea9bef.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59285992-33cf6880-8c6f-11e9-9824-597b14e9bbb3.png)
https://user-images.githubusercontent.com/20930745/59285992-33cf6880-8c6f-11e9-9824-597b14e9bbb3.png

Source:
https://user-images.githubusercontent.com/20930745/59285997-35009580-8c6f-11e9-83cf-aaf4976c0751.png
