### ISSUE TITLE
Strike Markdown Writer

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10185]
**App Name:** Strike Markdown Writer
**Bundle ID:** com.solaria.strikeios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1383011820">1383011820</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/strike-markdown-writer/id1383011820?uo=4">https://apps.apple.com/us/app/strike-markdown-writer/id1383011820?uo=4</a>
**App Version:** 1.2
**Seller:** Solaria SRL
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/solaria-srl/id1383011819?uo=4">© Solaria SRL</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/e3/3c/60/e33c604f-96ce-a0b9-551f-40b39289d92b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59299054-165cc780-8c8c-11e9-8c11-3a9e9f682334.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59297991-cf6dd280-8c89-11e9-90c1-8a4ab0a7a54b.png)
https://user-images.githubusercontent.com/20930745/59297991-cf6dd280-8c89-11e9-90c1-8a4ab0a7a54b.png

Source:
https://user-images.githubusercontent.com/20930745/59297993-d09eff80-8c89-11e9-9a9d-0fa44f1c8361.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Hm... I think it will be better without the background.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59299054-165cc780-8c8c-11e9-8c11-3a9e9f682334.png)
https://user-images.githubusercontent.com/20930745/59299054-165cc780-8c8c-11e9-8c11-3a9e9f682334.png

Source:
https://user-images.githubusercontent.com/20930745/59299061-19f04e80-8c8c-11e9-96e2-348052a5122b.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes, that's nice!
