### ISSUE TITLE
Yahoo - News, Mail, Sports

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10182]
**App Name:** Yahoo - News, Mail, Sports
**Bundle ID:** com.oath.yahooapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1434085655">1434085655</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/yahoo-news-mail-sports/id1434085655?uo=4">https://apps.apple.com/us/app/yahoo-news-mail-sports/id1434085655?uo=4</a>
**App Version:** 1.16.2
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yahoo/id281970157?uo=4">© Yahoo</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/2b/ca/89/2bca89b2-abc1-50d0-337b-5fd780adde8b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67293196-64a88f80-f4e4-11e9-93d5-0e6375d5a7d4.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59285519-69c01d00-8c6e-11e9-9ee3-d6be768309bb.png)
https://user-images.githubusercontent.com/20930745/59285519-69c01d00-8c6e-11e9-9ee3-d6be768309bb.png

Source:
https://user-images.githubusercontent.com/20930745/59285523-6b89e080-8c6e-11e9-8960-26546e7d47a8.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Yahoo - News, Mail, Sports
**Bundle ID:** com.oath.yahooapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1434085655">1434085655</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/yahoo-news-mail-sports/id1434085655?uo=4">https://apps.apple.com/us/app/yahoo-news-mail-sports/id1434085655?uo=4</a>
**App Version:** 1.16.2
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yahoo/id281970157?uo=4">© Yahoo</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/2b/ca/89/2bca89b2-abc1-50d0-337b-5fd780adde8b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67293196-64a88f80-f4e4-11e9-93d5-0e6375d5a7d4.png)
(https://user-images.githubusercontent.com/20930745/67293196-64a88f80-f4e4-11e9-93d5-0e6375d5a7d4.png

Source:
https://user-images.githubusercontent.com/20930745/67293198-65d9bc80-f4e4-11e9-89e2-7599d91507e6.png
