### ISSUE TITLE
Opera News: personalized news

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10183]
**App Name:** Opera News: personalized news
**Bundle ID:** com.opera.OperaNews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1444253126">1444253126</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/opera-news-personalized-news/id1444253126?uo=4">https://apps.apple.com/us/app/opera-news-personalized-news/id1444253126?uo=4</a>
**App Version:** 3.2.0
**Seller:** Opera Software AS
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/opera-software-as/id1282065940?uo=4">© Opera Software AS</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/1d/ad/f1/1dadf176-d3d4-1452-c339-bcbc710dff59/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59297198-f75c3680-8c87-11e9-9ce4-3b1eb48f881a.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59297198-f75c3680-8c87-11e9-9ce4-3b1eb48f881a.png)
https://user-images.githubusercontent.com/20930745/59297198-f75c3680-8c87-11e9-9ce4-3b1eb48f881a.png

Source:
https://user-images.githubusercontent.com/20930745/59297201-f925fa00-8c87-11e9-9858-58d32f574b61.png
