### ISSUE TITLE
Ready Steady Bang

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#1018]
**App Name:** Ready Steady Bang
**Bundle ID:** ReadySteadyBang
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447588618">447588618</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ready-steady-bang/id447588618?mt=8&uo=4">https://itunes.apple.com/us/app/ready-steady-bang/id447588618?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Cowboy Games Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cowboy-games/id914963192?uo=4>© Cowboy Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/db/65/38/db6538ba-525e-5867-b59c-9840ab41ce99/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18875021/553e7cbe-84c4-11e6-9cc5-b971521af05d.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18875021/553e7cbe-84c4-11e6-9cc5-b971521af05d.png)
https://cloud.githubusercontent.com/assets/20930745/18875021/553e7cbe-84c4-11e6-9cc5-b971521af05d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18875817/a46580a0-84c7-11e6-9b76-c5a9ec2c7b9b.png
