### ISSUE TITLE
klarmobil.de - Die Service App

### ISSUE THREAD

**Issue by btc187** [glasklart/hd#10187]
**App Name:** klarmobil.de - Die Service App
**Bundle ID:** de.klarmobil.kundenservice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1443939047">1443939047</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/klarmobil-de-die-service-app/id1443939047?uo=4">https://apps.apple.com/us/app/klarmobil-de-die-service-app/id1443939047?uo=4</a>
**App Version:** 1.1.1
**Seller:** klarmobil GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/klarmobil-gmbh/id1443939046?uo=4">© klarmobil GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/7e/ec/ef/7eecef31-d21a-c910-dc2f-6e5ca507fa3c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59286343-d687e700-8c6f-11e9-84ad-8560b4e0d46a.png)
https://user-images.githubusercontent.com/20930745/59286343-d687e700-8c6f-11e9-84ad-8560b4e0d46a.png

Source:
https://user-images.githubusercontent.com/20930745/59286351-d851aa80-8c6f-11e9-8bb4-e3b9bf8a2281.png
