### ISSUE TITLE
Google Fit – Activity Tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10180]
**App Name:** Google Fit – Activity Tracker
**Bundle ID:** com.google.fit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1433864494">1433864494</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-fit-activity-tracker/id1433864494?uo=4">https://apps.apple.com/us/app/google-fit-activity-tracker/id1433864494?uo=4</a>
**App Version:** 1.3
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/4e/d5/46/4ed546fb-b957-8c5b-b516-86c96d88c369/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59285089-b0f9de00-8c6d-11e9-8b3d-416dd4976984.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59285089-b0f9de00-8c6d-11e9-8b3d-416dd4976984.png)
https://user-images.githubusercontent.com/20930745/59285089-b0f9de00-8c6d-11e9-8b3d-416dd4976984.png

Source:
https://user-images.githubusercontent.com/20930745/59285092-b2c3a180-8c6d-11e9-8535-33f37d71ded0.png
