### ISSUE TITLE
PS4 Remote Play

### ISSUE THREAD

**Issue by btc187** [glasklart/hd#10188]
**App Name:** PS4 Remote Play
**Bundle ID:** com.playstation.psremoteplay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1436192460">1436192460</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ps4-remote-play/id1436192460?uo=4">https://apps.apple.com/us/app/ps4-remote-play/id1436192460?uo=4</a>
**App Version:** 1.0
**Seller:** PlayStation Mobile Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/playstation-mobile-inc/id912472174?uo=4">© PlayStation Mobile Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/61/fc/45/61fc4502-abab-143b-a0a7-cbbc30011a4f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59286717-88271800-8c70-11e9-9135-60c033ddf8bd.png)

**Comment by cspadazzi** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/6958830/59252356-4c3f8300-8c6f-11e9-905d-17d5d84efbac.png)

Source:
https://user-images.githubusercontent.com/6958830/59252371-55305480-8c6f-11e9-8922-1dfa95981449.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59286717-88271800-8c70-11e9-9135-60c033ddf8bd.png)
https://user-images.githubusercontent.com/20930745/59286717-88271800-8c70-11e9-9135-60c033ddf8bd.png

Source:
https://user-images.githubusercontent.com/20930745/59286723-89f0db80-8c70-11e9-8605-3f9cf80ed895.png
