### ISSUE TITLE
PENNY Coupons & Angebote

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10195]
**App Name:** PENNY Coupons & Angebote
**Bundle ID:** de.penny.ios.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1096204041">1096204041</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/penny-coupons-angebote/id1096204041?uo=4">https://apps.apple.com/de/app/penny-coupons-angebote/id1096204041?uo=4</a>
**App Version:** 2.1.6
**Seller:** Penny-Markt Gesellschaft mit beschraenkter Haftung
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/penny-markt-gmbh/id1096204040?uo=4">© PENNY Markt GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/0f/80/63/0f806343-de77-050f-cca1-5adf609e313f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59453179-9d867880-8e0f-11e9-89cf-428fdef1d513.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59453179-9d867880-8e0f-11e9-89cf-428fdef1d513.png)
(https://user-images.githubusercontent.com/20930745/59453179-9d867880-8e0f-11e9-89cf-428fdef1d513.png

Source:
https://user-images.githubusercontent.com/20930745/59453184-9f503c00-8e0f-11e9-85cc-0f0cbc4c1268.png
