### ISSUE TITLE
Chimera

### ISSUE THREAD

**Issue by eskimo** [glasklart/hd#10196]
Surprised nobody requested this, so I went ahead and just made it.

Bundle ID: com.electrateam.chimera

![Chimera](https://user-images.githubusercontent.com/12444228/59793426-88449a80-92a4-11e9-8ab8-cc84ec2cf9e5.png)

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/12444228/59793426-88449a80-92a4-11e9-8ab8-cc84ec2cf9e5.png)

https://user-images.githubusercontent.com/12444228/59793522-cb9f0900-92a4-11e9-9f8d-c06fcdc823c4.png

**Comment by 2Qt2beStr8** [comment]
#10149

**Comment by eskimo** [comment]
Hmmm I literally searched for Chimera and it showed no results. My bad.
