### ISSUE TITLE
File Hub by imoreapps

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#10192]
**App Name:** File Hub by imoreapps
**Bundle ID:** com.imoreapps.portablediskwithiap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=730843281">730843281</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/file-hub-by-imoreapps/id730843281?uo=4">https://apps.apple.com/us/app/file-hub-by-imoreapps/id730843281?uo=4</a>
**App Version:** 8.1.0
**Seller:** Gu Jing
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gu-jing/id504228387?uo=4">© Gu Jing</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/4c/d6/5d/4cd65dd5-de7f-29c1-e48b-60127786e3ca/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70941674-37441200-204d-11ea-85b8-e481d05aee38.png)

**Comment by dreamnet** [comment]
Refers to #3201

**Comment by cspadazzi** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/6958830/59252427-69745180-8c6f-11e9-9103-06e001d73b0a.png)
https://user-images.githubusercontent.com/6958830/59252428-69745180-8c6f-11e9-8fe0-f1e68c415c5d.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59283059-3aa7ac80-8c6a-11e9-9e6f-62a7624bd752.png)
(https://user-images.githubusercontent.com/20930745/59283059-3aa7ac80-8c6a-11e9-9e6f-62a7624bd752.png

Source:
https://user-images.githubusercontent.com/20930745/59283062-3bd8d980-8c6a-11e9-95ed-7acc7ad31923.png

**Comment by dreamnet** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70941674-37441200-204d-11ea-85b8-e481d05aee38.png)
https://user-images.githubusercontent.com/20930745/70941674-37441200-204d-11ea-85b8-e481d05aee38.png

Source:
https://user-images.githubusercontent.com/20930745/70941676-390dd580-204d-11ea-9a17-07bef4cf16b5.png
