### ISSUE TITLE
Azlo: Easy Business Banking

### ISSUE THREAD

**Issue by eskimo** [glasklart/hd#10197]
**App Name:** Azlo: Easy Business Banking
**Bundle ID:** com.azlo.main
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1266213406">1266213406</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/azlo-easy-business-banking/id1266213406?uo=4">https://apps.apple.com/us/app/azlo-easy-business-banking/id1266213406?uo=4</a>
**App Version:** 2.30.0
**Seller:** Azlo Business, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/azlo-business-inc/id1266213405?uo=4">© Azlo Business, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/b5/51/06/b5510609-2c9d-978e-8c1f-4373d0481f6a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59814362-56b7e780-9315-11e9-8b12-8ff40c5020d8.png)

**Comment by eskimo** [comment]
![Azlo](https://user-images.githubusercontent.com/12444228/59804653-fb5a0b00-92bc-11e9-9bb0-289d8b1c525c.png)

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/12444228/59804653-fb5a0b00-92bc-11e9-9bb0-289d8b1c525c.png)

https://user-images.githubusercontent.com/12444228/59804699-1af13380-92bd-11e9-80bf-c8f785743ebf.png

**Comment by dreamnet** [comment]
@eskimo I did some litte corrections - else: Very good! 👍

**Comment by eskimo** [comment]
Oops. I have a few more to submit later. I'll make sure I do them right :P
