### ISSUE TITLE
IGEL DISRUPT EUC

### ISSUE THREAD

**Issue by btc187** [glasklart/hd#10190]
**App Name:** IGEL DISRUPT EUC
**Bundle ID:** me.doubledutch.xhfjn.igel2017kickoff
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1179121885">1179121885</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/igel-disrupt-euc/id1179121885?uo=4">https://apps.apple.com/us/app/igel-disrupt-euc/id1179121885?uo=4</a>
**App Version:** 1.7
**Seller:** IGEL TECHNOLOGY
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/igel-technology/id1448998708?uo=4">© IGEL TECHNOLOGY</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/c1/74/f2/c174f2cd-ed6e-6fee-f5e3-6289f3e6696f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59284044-e1d91380-8c6b-11e9-8ca7-5f4b4dc81012.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59284044-e1d91380-8c6b-11e9-8ca7-5f4b4dc81012.png)
https://user-images.githubusercontent.com/20930745/59284044-e1d91380-8c6b-11e9-8ca7-5f4b4dc81012.png

Source:
https://user-images.githubusercontent.com/20930745/59284088-f3222000-8c6b-11e9-9ee1-e94002d11800.png
