### ISSUE TITLE
CINEMUR

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#1019]
**App Name:** CINEMUR
**Bundle ID:** com.cinemur.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=596346457">596346457</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cinemur/id596346457?uo=4">https://apps.apple.com/us/app/cinemur/id596346457?uo=4</a>
**App Version:** 5.1.4
**Seller:** CINEMUR
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cinemur-s-a/id596346460?uo=4">© CINEMUR S.A.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/17/a9/00/17a900aa-a4f5-175f-02cd-0c4cc9c86a2a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60371480-ac694f80-99f9-11e9-8bef-57545d51e158.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617274/0a02aad2-982d-11e6-9406-ec642c276bc9.png)
https://cloud.githubusercontent.com/assets/20930745/19617274/0a02aad2-982d-11e6-9406-ec642c276bc9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617302/25f8d9aa-982d-11e6-811d-5457f7bdcc64.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60371480-ac694f80-99f9-11e9-8bef-57545d51e158.png)
https://user-images.githubusercontent.com/20930745/60371480-ac694f80-99f9-11e9-8bef-57545d51e158.png

Source:
https://user-images.githubusercontent.com/20930745/60371484-aecba980-99f9-11e9-9b59-89016065a90c.png
