### ISSUE TITLE
DayCalc - Note Calculator

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#10193]
**App Name:** DayCalc - Note Calculator
**Bundle ID:** com.hcsystem.calculatorfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=661506264">661506264</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/daycalc-note-calculator/id661506264?uo=4">https://apps.apple.com/us/app/daycalc-note-calculator/id661506264?uo=4</a>
**App Version:** 5.4
**Seller:** LingLing Chen
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lingling-chen/id654444245?uo=4">© LingLing Chen</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/fe/8f/a3/fe8fa36d-352e-6acc-f219-6495e6a23c82/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59296402-34272e00-8c86-11e9-9a55-537907b00e86.png)

**Comment by dreamnet** [comment]
Refers to #10178

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59296402-34272e00-8c86-11e9-9a55-537907b00e86.png)
https://user-images.githubusercontent.com/20930745/59296402-34272e00-8c86-11e9-9a55-537907b00e86.png

Source:
https://user-images.githubusercontent.com/20930745/59296405-35585b00-8c86-11e9-920a-b25000eb1788.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes, good! 👍
