### ISSUE TITLE
Erste Hilfe DRK

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10194]
**App Name:** Erste Hilfe DRK
**Bundle ID:** com.drk-service.erstehilfe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404519165">404519165</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/erste-hilfe-drk/id404519165?uo=4">https://apps.apple.com/de/app/erste-hilfe-drk/id404519165?uo=4</a>
**App Version:** 1.23
**Seller:** DRK-Service GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/deutsches-rotes-kreuz/id404519168?uo=4">© Deutsches Rotes Kreuz</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/12/4b/ab/124bab52-5680-52a3-2c03-f92901c0f4fd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59374831-0b1da080-8d4d-11e9-9d48-422a53c979c6.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59374406-13291080-8d4c-11e9-920e-ec3093e0f775.png)
https://user-images.githubusercontent.com/20930745/59374406-13291080-8d4c-11e9-920e-ec3093e0f775.png

Source:
https://user-images.githubusercontent.com/20930745/59374407-14f2d400-8d4c-11e9-9bed-1632a14b6f2e.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59374831-0b1da080-8d4d-11e9-9d48-422a53c979c6.png)
https://user-images.githubusercontent.com/20930745/59374831-0b1da080-8d4d-11e9-9d48-422a53c979c6.png

Source:
https://user-images.githubusercontent.com/20930745/59374836-0ce76400-8d4d-11e9-89b4-372d5cb27992.png
