### ISSUE TITLE
Zebra

### ISSUE THREAD

**Issue by eskimo** [glasklart/hd#10199]
**App Name:** Zebra
 **Bundle ID:** xyz.willy.Zebra
 **Version:** 1.0~beta15
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://user-images.githubusercontent.com/2068130/59816717-75ba7780-931d-11e9-88b8-49807db74196.png" width="180" height="180" />
 **Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59865227-d337de00-9388-11e9-8907-841afacd74e0.png)

**Comment by dreamnet** [comment]
@eskimo wrote:
Jailbreak package manager

xyz.willy.Zebra

![xyz willy Zebra](https://user-images.githubusercontent.com/12444228/59805943-bf28a980-92c0-11e9-9054-5f481ec10403.png)

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/12444228/59805943-bf28a980-92c0-11e9-9054-5f481ec10403.png)

Source is rough cause of the initial icon size but looks decent scaled down.
https://user-images.githubusercontent.com/12444228/59806055-1dee2300-92c1-11e9-8c57-c25dc5e44dbe.png

**Comment by dreamnet** [comment]
@eskimo I corrected the issue to fit our [rules](https://github.com/glasklart/hd/wiki/How-to-submit-an-icon-request-for-a-Cydia-app).
Here is an overwoked icon and a good source:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59816838-e6619400-931d-11e9-8be9-4dab72a5c3ca.png)
https://user-images.githubusercontent.com/2068130/59816838-e6619400-931d-11e9-8be9-4dab72a5c3ca.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59816857-faa59100-931d-11e9-92da-f311cd2cd9af.png

**Comment by Sly-Fi** [comment]
Can this be updated with the new Zebra head icon?
![AppIcon60x60@3x](https://user-images.githubusercontent.com/11544849/64753202-8d9a3580-d4df-11e9-9e7b-7a9e93e24651.png)

**Comment by eskimo** [comment]
I chose this one because the zebra one is ugly and also difficult to theme this way. This is the best one of the zebra options for glasklart imo.

**Comment by dreamnet** [comment]
@eskimo I think you are right - we keep the actual Glasklart icon.
