### ISSUE TITLE
Stripe Dashboard

### ISSUE THREAD

**Issue by eskimo** [glasklart/hd#10201]
**App Name:** Stripe Dashboard
**Bundle ID:** com.stripe.dashboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=978516833">978516833</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stripe-dashboard/id978516833?uo=4">https://apps.apple.com/us/app/stripe-dashboard/id978516833?uo=4</a>
**App Version:** 2.3.1
**Seller:** Stripe Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/stripe-inc/id921766866?uo=4">© Stripe, Inc</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/78/bb/15/78bb158f-c895-a842-b793-cfba787bf7c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59866833-d3d27380-938c-11e9-8786-e0f9e989af68.png)

**Comment by eskimo** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/12444228/59856380-c85b5a00-9344-11e9-81ea-4ef4937a640c.png)

https://user-images.githubusercontent.com/12444228/59856380-c85b5a00-9344-11e9-81ea-4ef4937a640c.png

https://user-images.githubusercontent.com/12444228/59856407-da3cfd00-9344-11e9-9fef-c7ab2a61a8f5.png

**Comment by dreamnet** [comment]
@eskimo Also a bit too big...
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59866833-d3d27380-938c-11e9-8786-e0f9e989af68.png)
https://user-images.githubusercontent.com/2068130/59866833-d3d27380-938c-11e9-8786-e0f9e989af68.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59866851-e482e980-938c-11e9-808f-593bc1453134.png

**Comment by eskimo** [comment]
> @eskimo Also a bit too big...
> ![-large](https://camo.githubusercontent.com/7323e585a3961215c8e2ecbd227497a7735fa94b/68747470733a2f2f707265766965772e647265616d6e65742e61743f696d6167653d68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f323036383133302f35393836363833332d64336432373338302d393338632d313165392d383738362d6530663965393839616636382e706e67)
> https://user-images.githubusercontent.com/2068130/59866833-d3d27380-938c-11e9-8786-e0f9e989af68.png
> 
> Source:
> https://user-images.githubusercontent.com/2068130/59866851-e482e980-938c-11e9-808f-593bc1453134.png

You should really have a look at your contributing guidelines then and rewrite them.

**Comment by dreamnet** [comment]
@eskimo Yes, if we could find some time... 😉 ⌚️

**Comment by ivanov007** [comment]
@eskimo I don't think this can be added to the guide, maybe a side note, ultimately it comes down to pick the one that best match the original and have the best look if more than one is submitted
