### ISSUE TITLE
IRCCloud

### ISSUE THREAD

**Issue by eskimo** [glasklart/hd#10200]
**App Name:** IRCCloud
**Bundle ID:** com.irccloud.IRCCloud
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=672699103">672699103</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/irccloud/id672699103?uo=4">https://apps.apple.com/us/app/irccloud/id672699103?uo=4</a>
**App Version:** 4.9
**Seller:** IRCCloud Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/irccloud/id672699106?uo=4">© IRCCloud</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/8a/08/0a/8a080ac5-11e0-caba-a1dd-09d19c66f0b4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59866304-8e617680-938b-11e9-9699-822d1dc87279.png)

**Comment by eskimo** [comment]
![](https://user-images.githubusercontent.com/12444228/59855726-7fef6c80-9343-11e9-900e-c270191e272a.png)

https://user-images.githubusercontent.com/12444228/59855726-7fef6c80-9343-11e9-900e-c270191e272a.png

https://user-images.githubusercontent.com/12444228/59855758-909fe280-9343-11e9-8dda-15aff4da21e1.png

**Comment by dreamnet** [comment]
@eskimo Great, but a bit too big...
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59866304-8e617680-938b-11e9-9699-822d1dc87279.png)
https://user-images.githubusercontent.com/2068130/59866304-8e617680-938b-11e9-9699-822d1dc87279.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59866348-a638fa80-938b-11e9-9254-7ee27b4a310f.png

**Comment by eskimo** [comment]
Too big? I'm just following the guideline that says to expand it and then shrink it to 118.

**Comment by dreamnet** [comment]
@eskimo Just a bit - compare my and Your source....
I have a screencast how I do this with Illustrator somewhere...

**Comment by eskimo** [comment]
I can see the difference. But, The guidelines don't say have some padding, they say `and resize the pasted area to a with of 1024px.`

Otherwise I would've left some extra space had it said to.

**Comment by dreamnet** [comment]
@eskimo Yes, you are right. But some icons - like this icon or the "S" in #10201 are originally smaller than 118x118px. For these ones you have to shrink the source so the result has the same size as the original. That's hard to explain, I hope you understand what I mean. #10201 is a good example.

**Comment by eskimo** [comment]
I suppose. I mean, I agree, and thought it was a little weird to upscale like that and end up with a bigger icon than the original, but I figured that's just how it is ¯\_(ツ)_/¯

**Comment by dreamnet** [comment]
@eskimo 😄 About 90% of the icons are using the whole 118.118px area. Another good eyample why we make the "original smaller" icons in the original size ist #8916.

**Comment by eskimo** [comment]
Yeah #8916is a good example lol. I'm not much of a designer, just serious OCD of having all these unthemed icons on my homescreen. Been using Glasklart since like iOS 5 days, so figured I'd finally contribute a bit 😄

I did some others, but they are other JB apps with horrible horrible quality tiny AppIcons that ended up horrible or things like say the Matomo app like this (https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/b8/df/30/b8df3012-b980-23a5-c6ff-8ef95d32d673/AppIcon-0-1x_U007emarketing-0-0-GLES2_U002c0-512MB-sRGB-0-0-0-85-220-0-0-0-6.png/230x0w.jpg) which looks horrible afterwords. So while I'm using it on my device, I don't think it's acceptable to submit 😛

**Comment by dreamnet** [comment]
@eskimo We are happy if you want to help us and do some contributions 👍 - If you can't do the icon - like Matomo -  just open an Issue.

**Comment by eskimo** [comment]
I did the icon fine, it's just that it's ugly. Kinda like if you look at the AdWords one I submitted because the different color is what makes the icon look good, they just kinda look like a big blobby weird shape when you style it like this lol

**Comment by dreamnet** [comment]
@eskimo Yeah, some icons can be very hard. Matomo quick'n'dirty:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59870022-ec468c00-9394-11e9-8641-4d6761011b9b.png)

**Comment by eskimo** [comment]
Well that looks way better than what I was gonna do lol. Those separator lines make it actually usable.

**Comment by dreamnet** [comment]
Off-Topic, but here is the full Matomo Glasklart icon:
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59876345-a8a74e80-93a3-11e9-874b-4fc2ae026504.png)
https://user-images.githubusercontent.com/2068130/59876345-a8a74e80-93a3-11e9-874b-4fc2ae026504.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59876368-bd83e200-93a3-11e9-9e5a-5ebeb0457327.png
--- ---
@eskimo If you want this to be added to Glasklart, please open an issue.
