### ISSUE TITLE
Freewallet: Crypto Wallet

### ISSUE THREAD

**Issue by eskimo** [glasklart/hd#10203]
**App Name:** Freewallet: Crypto Wallet
**Bundle ID:** mw.org.freewallet.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1274003898">1274003898</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/freewallet-crypto-wallet/id1274003898?uo=4">https://apps.apple.com/us/app/freewallet-crypto-wallet/id1274003898?uo=4</a>
**App Version:** 1.0.38
**Seller:** Wallet services Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/freewallet/id1255224297?uo=4">© Freewallet</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/e2/74/4e/e2744ee7-a691-9c3b-cc86-ce699497e663/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59870381-bd7ce580-9395-11e9-98b3-6ac083d176dd.png)

**Comment by eskimo** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/12444228/59857022-0efd8400-9346-11e9-8059-4d54cae980cc.png)

https://user-images.githubusercontent.com/12444228/59857022-0efd8400-9346-11e9-8059-4d54cae980cc.png

https://user-images.githubusercontent.com/12444228/59857040-1ae94600-9346-11e9-9646-aa5f463a82dd.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59870381-bd7ce580-9395-11e9-98b3-6ac083d176dd.png)
https://user-images.githubusercontent.com/2068130/59870381-bd7ce580-9395-11e9-98b3-6ac083d176dd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59870416-ccfc2e80-9395-11e9-8313-d747e1c1d296.png
