### ISSUE TITLE
Travelers Mobile

### ISSUE THREAD

**Issue by eskimo** [glasklart/hd#10204]
**App Name:** Travelers Mobile
**Bundle ID:** com.travelers.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=354604876">354604876</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/travelers-mobile/id354604876?uo=4">https://apps.apple.com/us/app/travelers-mobile/id354604876?uo=4</a>
**App Version:** 3.4.5
**Seller:** The Travelers Indemnity Company
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-travelers-indemnity-company/id354604879?uo=4">© The Travelers Indemnity Company</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/9b/6d/d1/9b6dd1c0-f317-96f0-cd1a-f94204d807bd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59871083-02554c00-9397-11e9-8bf1-7f9fe275b21f.png)

**Comment by eskimo** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/12444228/59857300-a662d700-9346-11e9-8270-83aa78010401.png)

https://user-images.githubusercontent.com/12444228/59857300-a662d700-9346-11e9-8270-83aa78010401.png

https://user-images.githubusercontent.com/12444228/59857312-ae227b80-9346-11e9-9ff4-121feae9990f.png

**Comment by dreamnet** [comment]
With "cleaner" source:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59871083-02554c00-9397-11e9-8bf1-7f9fe275b21f.png)
https://user-images.githubusercontent.com/2068130/59871083-02554c00-9397-11e9-8bf1-7f9fe275b21f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59871110-113bfe80-9397-11e9-99bd-d60e08f80de5.png
