### ISSUE TITLE
Matomo Mobile 2

### ISSUE THREAD

**Issue by eskimo** [glasklart/hd#10207]
**App Name:** Matomo Mobile 2
**Bundle ID:** org.piwik.mobile2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=737216887">737216887</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/matomo-mobile-2/id737216887?uo=4">https://apps.apple.com/us/app/matomo-mobile-2/id737216887?uo=4</a>
**App Version:** 2.4.5
**Seller:** Thomas Steur
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/piwik/id385536445?uo=4">© Piwik</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/61/3b/5d/613b5da2-69b5-bbb8-92bc-50a452aa1fd6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59901952-1fbd0100-93fd-11e9-9a93-f224fba43bb2.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59901952-1fbd0100-93fd-11e9-9a93-f224fba43bb2.png)
https://user-images.githubusercontent.com/2068130/59901952-1fbd0100-93fd-11e9-9a93-f224fba43bb2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59901983-306d7700-93fd-11e9-8e5d-cfc54309e887.png
