### ISSUE TITLE
1.1.1.1: Faster Internet

### ISSUE THREAD

**Issue by eskimo** [glasklart/hd#10205]
**App Name:** 1.1.1.1: Faster Internet
**Bundle ID:** com.cloudflare.1dot1dot1dot1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1423538627">1423538627</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/1-1-1-1-faster-internet/id1423538627?uo=4">https://apps.apple.com/us/app/1-1-1-1-faster-internet/id1423538627?uo=4</a>
**App Version:** 2.0.9
**Seller:** Cloudflare Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cloudflare/id1315808068?uo=4">© Cloudflare</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/b2/24/51/b2245149-ee7d-a440-bb88-7ab400a1f11f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59871358-b0f98c80-9397-11e9-9960-b58b89235d50.png)

**Comment by eskimo** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/12444228/59857578-399c0c80-9347-11e9-80cf-2214b3d58297.png)

https://user-images.githubusercontent.com/12444228/59857578-399c0c80-9347-11e9-80cf-2214b3d58297.png

https://user-images.githubusercontent.com/12444228/59857606-4587ce80-9347-11e9-9643-b230249305bc.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59871358-b0f98c80-9397-11e9-9960-b58b89235d50.png)
https://user-images.githubusercontent.com/2068130/59871358-b0f98c80-9397-11e9-9960-b58b89235d50.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59871388-c078d580-9397-11e9-957d-101fd7d8d3d6.png
