### ISSUE TITLE
Google Ads: Grow Your Business

### ISSUE THREAD

**Issue by eskimo** [glasklart/hd#10206]
**App Name:** Google Ads: Grow Your Business
**Bundle ID:** com.google.AdWords
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1037457231">1037457231</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-ads-grow-your-business/id1037457231?uo=4">https://apps.apple.com/us/app/google-ads-grow-your-business/id1037457231?uo=4</a>
**App Version:** 2.8.20004201
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/07/5c/3c/075c3c59-c9c8-a6a9-0cdd-03d4b56a36aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59872034-2ade4580-9399-11e9-8b3a-4c47d2a27477.png)

**Comment by eskimo** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/12444228/59858044-33f2f680-9348-11e9-9082-b203321ecd43.png)

https://user-images.githubusercontent.com/12444228/59858044-33f2f680-9348-11e9-9082-b203321ecd43.png

https://user-images.githubusercontent.com/12444228/59858061-3fdeb880-9348-11e9-8a18-4cacf8ae2979.png

**Comment by dreamnet** [comment]
Hum...
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59872034-2ade4580-9399-11e9-8b3a-4c47d2a27477.png)
https://user-images.githubusercontent.com/2068130/59872034-2ade4580-9399-11e9-8b3a-4c47d2a27477.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59872068-39c4f800-9399-11e9-9da7-118f225445f4.png

**Comment by eskimo** [comment]
I think you're a little better at design than me :P
