### ISSUE TITLE
VGN Fahrplan & Tickets

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#10217]
**App Name:** VGN Fahrplan & Tickets
**Bundle ID:** com.mdv.VGNCompanion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=932422485">932422485</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/vgn-fahrplan-tickets/id932422485?uo=4">https://apps.apple.com/us/app/vgn-fahrplan-tickets/id932422485?uo=4</a>
**App Version:** 5.14.0
**Seller:** Verkehrsverbund Grossraum Nuernberg GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/verkehrsverbund-grossraum-nuernberg-gmbh/id1438093156?uo=4">© Verkehrsverbund Grossraum Nuernberg GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/33/64/3e/33643e91-09bc-828f-c1da-79e2442153b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60121463-660abb00-9783-11e9-9a57-8d82bf6fc51a.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60121463-660abb00-9783-11e9-9a57-8d82bf6fc51a.png)
https://user-images.githubusercontent.com/20930745/60121463-660abb00-9783-11e9-9a57-8d82bf6fc51a.png

Source:
https://user-images.githubusercontent.com/20930745/60121469-67d47e80-9783-11e9-91fc-d98a5029fd64.png
