### ISSUE TITLE
dplay – TV, serier och esport

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#10219]
**App Name:** dplay – TV, serier och esport
**Bundle ID:** com.kanal5.play
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395972146">395972146</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/se/app/dplay-tv-serier-och-esport/id395972146?uo=4">https://apps.apple.com/se/app/dplay-tv-serier-och-esport/id395972146?uo=4</a>
**App Version:** 6.1.0
**Seller:** DPlay Entertainment Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/se/developer/discovery-digital/id1412449523?uo=4">© Discovery Digital</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/bb/07/3e/bb073e32-0977-3b94-a926-e975226fcd55/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382856-33a1dc00-9a69-11e9-9386-033b409ada37.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382856-33a1dc00-9a69-11e9-9386-033b409ada37.png)
https://user-images.githubusercontent.com/20930745/60382856-33a1dc00-9a69-11e9-9386-033b409ada37.png

Source:
https://user-images.githubusercontent.com/20930745/60382857-356b9f80-9a69-11e9-81b5-5b01fed87eea.png
