### ISSUE TITLE
BVG FahrInfo Plus Berlin

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#10211]
**App Name:** BVG FahrInfo Plus Berlin
**Bundle ID:** de.metaquark.vbbquery
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284971745">284971745</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bvg-fahrinfo-plus-berlin/id284971745?uo=4">https://apps.apple.com/us/app/bvg-fahrinfo-plus-berlin/id284971745?uo=4</a>
**App Version:** 6.2.15
**Seller:** Berliner Verkehrsbetriebe (BVG) Anstalt des oeffentlichen Rechts
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/berliner-verkehrsbetriebe-bvg-a%C3%B6r/id1092074591?uo=4">© Berliner Verkehrsbetriebe (BVG) - AöR</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/73/a3/4c/73a34c81-0500-cf4e-e183-b51dbd3e29e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60121762-1973af80-9784-11e9-8a92-47c364c22b93.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60121762-1973af80-9784-11e9-8a92-47c364c22b93.png)
https://user-images.githubusercontent.com/20930745/60121762-1973af80-9784-11e9-8a92-47c364c22b93.png

Source:
https://user-images.githubusercontent.com/20930745/60121766-1aa4dc80-9784-11e9-8f8d-36b809ed669e.png
