### ISSUE TITLE
Brother SupportCenter

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10212]
**App Name:** Brother SupportCenter
**Bundle ID:** com.brother.product.SupportCenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953350007">953350007</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/brother-supportcenter/id953350007?uo=4">https://apps.apple.com/us/app/brother-supportcenter/id953350007?uo=4</a>
**App Version:** 1.2.7
**Seller:** Brother Industries, LTD.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/brother-industries-ltd/id382775645?uo=4">© Brother Industries, LTD.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/34/b0/f1/34b0f196-689c-4ff2-5532-8fd5b5f628a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59989636-4c148f80-9640-11e9-9faa-cac25a6b6161.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59989636-4c148f80-9640-11e9-9faa-cac25a6b6161.png)
https://user-images.githubusercontent.com/2068130/59989636-4c148f80-9640-11e9-9faa-cac25a6b6161.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59989647-5b93d880-9640-11e9-98b3-7fae728da7e8.png
