### ISSUE TITLE
engelbert strauss

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10214]
**App Name:** engelbert strauss
**Bundle ID:** de.engelbertstrauss.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1439457011">1439457011</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/engelbert-strauss/id1439457011?uo=4">https://apps.apple.com/de/app/engelbert-strauss/id1439457011?uo=4</a>
**App Version:** 1.0.2
**Seller:** engelbert strauss GmbH & Co. KG
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/engelbert-strauss-gmbh-co-kg/id427792490?uo=4">© engelbert strauss GmbH & Co. KG</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/a2/b5/b6/a2b5b6ee-2871-31d9-a08d-1051425a03bf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59989908-4ff4e180-9641-11e9-8a26-4da5679a4d63.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59989908-4ff4e180-9641-11e9-8a26-4da5679a4d63.png)
https://user-images.githubusercontent.com/2068130/59989908-4ff4e180-9641-11e9-8a26-4da5679a4d63.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59989915-5edb9400-9641-11e9-82dc-086e621b3213.png
