### ISSUE TITLE
NORDSEE Deutschland

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10213]
**App Name:** NORDSEE Deutschland
**Bundle ID:** com.nordsee.de.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1220781805">1220781805</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/nordsee-deutschland/id1220781805?uo=4">https://apps.apple.com/gb/app/nordsee-deutschland/id1220781805?uo=4</a>
**App Version:** 4.6
**Seller:** Nordsee Holding GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/nordsee-holding-gmbh/id1220781804?uo=4">© Nordsee Holding GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/8b/d0/5c/8bd05cbc-420a-4989-7469-86f9076f110a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59989769-d52bc680-9640-11e9-8bfd-1a37fc0d9914.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59989769-d52bc680-9640-11e9-8bfd-1a37fc0d9914.png)
https://user-images.githubusercontent.com/2068130/59989769-d52bc680-9640-11e9-8bfd-1a37fc0d9914.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59989785-e379e280-9640-11e9-8d32-e9f1f41319c9.png
