### ISSUE TITLE
DORIS

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#10218]
**App Name:** DORIS
**Bundle ID:** at.codepool.dorismobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=568898426">568898426</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/doris/id568898426?uo=4">https://apps.apple.com/de/app/doris/id568898426?uo=4</a>
**App Version:** 3.1
**Seller:** Amt der oberoesterreichischen Landesregierung
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/land-ober%C3%B6sterreich/id1295622818?uo=4">© Land Oberösterreich</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/97/22/7b/97227bf6-ac72-96ef-422b-19c74321f127/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382881-be82d680-9a69-11e9-8c97-5f5a3b95aaf6.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382881-be82d680-9a69-11e9-8c97-5f5a3b95aaf6.png)
https://user-images.githubusercontent.com/20930745/60382881-be82d680-9a69-11e9-8c97-5f5a3b95aaf6.png

Source:
https://user-images.githubusercontent.com/20930745/60382882-c04c9a00-9a69-11e9-93ed-6f8ff64a9a5d.png
