### ISSUE TITLE
Green Screen Studio

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#10228]
**App Name:** Green Screen Studio
**Bundle ID:** com.yourcompany.GreenScreenStudio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=323912556">323912556</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/green-screen-studio/id323912556?uo=4">https://apps.apple.com/us/app/green-screen-studio/id323912556?uo=4</a>
**App Version:** 3.3.1
**Seller:** Pocket Bits LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/pocket-bits-llc/id893305713?uo=4">© Pocket Bits LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/03/94/d4/0394d4b0-d110-0840-b387-acacf0870e65/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60540209-e9da1f80-9d0e-11e9-92e7-20c851f77447.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60540209-e9da1f80-9d0e-11e9-92e7-20c851f77447.png)
https://user-images.githubusercontent.com/20930745/60540209-e9da1f80-9d0e-11e9-92e7-20c851f77447.png

Source:
https://user-images.githubusercontent.com/20930745/60540211-eb0b4c80-9d0e-11e9-8435-2b8bf828fca0.png
