### ISSUE TITLE
GPS Utility

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#10227]
**App Name:** GPS Utility
**Bundle ID:** it.dimension.gpsutility
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=292815934">292815934</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gps-utility/id292815934?uo=4">https://apps.apple.com/us/app/gps-utility/id292815934?uo=4</a>
**App Version:** 2.0.2
**Seller:** DIMENSION S.r.l.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dimension-s-r-l/id292299554?uo=4">© DIMENSION S.r.l.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple122/v4/17/08/39/17083945-f3d5-5129-5858-46c78ea05dca/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60539856-f9a53400-9d0d-11e9-9883-b5012181b70a.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60539856-f9a53400-9d0d-11e9-9883-b5012181b70a.png)
https://user-images.githubusercontent.com/20930745/60539856-f9a53400-9d0d-11e9-9883-b5012181b70a.png

Source:
https://user-images.githubusercontent.com/20930745/60539857-fb6ef780-9d0d-11e9-979d-0e9adc684314.png
