### ISSUE TITLE
Filmstaden

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#10224]
**App Name:** Filmstaden
**Bundle ID:** se.sf.sfbio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479273432">479273432</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/filmstaden/id479273432?uo=4">https://apps.apple.com/us/app/filmstaden/id479273432?uo=4</a>
**App Version:** 8.2.0
**Seller:** Filmstaden AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/filmstaden-ab/id479273435?uo=4">© Filmstaden AB</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/68/78/5e/68785ec9-167f-8cdf-0e32-cfb35e3e85ff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393494-9ac99a00-9b16-11e9-8066-341b19ff50a4.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393494-9ac99a00-9b16-11e9-8066-341b19ff50a4.png)
https://user-images.githubusercontent.com/20930745/60393494-9ac99a00-9b16-11e9-8066-341b19ff50a4.png

Source:
https://user-images.githubusercontent.com/20930745/60393496-9bfac700-9b16-11e9-9d57-a958193a8e67.png
