### ISSUE TITLE
Filmstarts: Kino, Serien, News

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#10225]
**App Name:** Filmstarts: Kino, Serien, News
**Bundle ID:** de.filmstarts.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=367847618">367847618</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/filmstarts-kino-serien-news/id367847618?uo=4">https://apps.apple.com/us/app/filmstarts-kino-serien-news/id367847618?uo=4</a>
**App Version:** 5.0.1
**Seller:** Webedia
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/webedia/id369343094?uo=4">© Webedia</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/de/54/24/de5424de-26db-da71-09b6-ae85620a4fd2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393458-1545ea00-9b16-11e9-8539-dbb6e8a41f12.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393458-1545ea00-9b16-11e9-8539-dbb6e8a41f12.png)
https://user-images.githubusercontent.com/20930745/60393458-1545ea00-9b16-11e9-8539-dbb6e8a41f12.png

Source:
https://user-images.githubusercontent.com/20930745/60393459-16771700-9b16-11e9-9dc0-a6d1ae9d206a.png
