### ISSUE TITLE
Ringtones for iPhone! (music)

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10229]
**App Name:** Ringtones for iPhone! (music)
**Bundle ID:** mobi.byss.bbsoundfx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380908399">380908399</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ringtones-for-iphone-music/id380908399?uo=4">https://apps.apple.com/us/app/ringtones-for-iphone-music/id380908399?uo=4</a>
**App Version:** 8.21
**Seller:** BYSS mobile
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/byss-mobile/id327447624?uo=4">© byss mobile</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/fd/a6/fd/fda6fd01-733a-8bc3-1551-fb622a8d1363/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680245-d9e74a80-9e8a-11e9-930d-82586b297540.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680245-d9e74a80-9e8a-11e9-930d-82586b297540.png)
https://user-images.githubusercontent.com/20930745/60680245-d9e74a80-9e8a-11e9-930d-82586b297540.png

Source:
https://user-images.githubusercontent.com/20930745/60680248-dbb10e00-9e8a-11e9-9182-ab79aeeec9c8.png

**Comment by iPOSEiDON** [comment]
thanks allot ! :)
