### ISSUE TITLE
WebCast TV for Chromecast

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10230]
**App Name:** WebCast TV for Chromecast
**Bundle ID:** com.moobidigittech.WebCast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1248564076">1248564076</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/webcast-tv-for-chromecast/id1248564076?uo=4">https://apps.apple.com/us/app/webcast-tv-for-chromecast/id1248564076?uo=4</a>
**App Version:** 1.3.0
**Seller:** MoobiDigit Technologies Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/moobidigit/id1078507996?uo=4">© MoobiDigit</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/9b/64/84/9b64841d-5a51-a48b-9a9a-2691096573d1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680438-96d9a700-9e8b-11e9-98d2-2ab2dad4e956.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680438-96d9a700-9e8b-11e9-98d2-2ab2dad4e956.png)
https://user-images.githubusercontent.com/20930745/60680438-96d9a700-9e8b-11e9-98d2-2ab2dad4e956.png

Source:
https://user-images.githubusercontent.com/20930745/60680440-98a36a80-9e8b-11e9-87dd-18235a770485.png

**Comment by iPOSEiDON** [comment]
thank you very much !
