### ISSUE TITLE
GTribe

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10231]
**App Name:** GTribe
**Bundle ID:** com.gamingtribe.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1275905434">1275905434</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gtribe/id1275905434?uo=4">https://apps.apple.com/us/app/gtribe/id1275905434?uo=4</a>
**App Version:** 1.0.0
**Seller:** Mass Luminosity, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mass-luminosity/id1275905433?uo=4">© Mass Luminosity</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/ae/da/ee/aedaeefd-411b-a96c-7278-46016db6d5ac/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680613-3f880680-9e8c-11e9-8a46-0902171133d2.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680613-3f880680-9e8c-11e9-8a46-0902171133d2.png)
https://user-images.githubusercontent.com/20930745/60680613-3f880680-9e8c-11e9-8a46-0902171133d2.png

Source:
https://user-images.githubusercontent.com/20930745/60680615-40b93380-9e8c-11e9-8c54-56834fb0a484.png

**Comment by iPOSEiDON** [comment]
thanks !
