### ISSUE TITLE
Instant Gaming

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10232]
**App Name:** Instant Gaming
**Bundle ID:** com.instantgaming.igapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1199040135">1199040135</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/instant-gaming/id1199040135?uo=4">https://apps.apple.com/us/app/instant-gaming/id1199040135?uo=4</a>
**App Version:** 6.2
**Seller:** Instant Gaming Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/instant-gaming-ltd/id1199040134?uo=4">© Instant Gaming Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/6a/45/c6/6a45c626-4861-3a1e-3c34-eaca89f5cbf7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680807-187e0480-9e8d-11e9-9a80-fac01dece986.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680807-187e0480-9e8d-11e9-9a80-fac01dece986.png)
https://user-images.githubusercontent.com/20930745/60680807-187e0480-9e8d-11e9-9a80-fac01dece986.png

Source:
https://user-images.githubusercontent.com/20930745/60680809-19af3180-9e8d-11e9-8a07-43231f2bbe69.png

**Comment by iPOSEiDON** [comment]
thanks allot !
