### ISSUE TITLE
 Takeaway.com 

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10233]
**App Name:** Takeaway.com
**Bundle ID:** pizza.co.uk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=333214491">333214491</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/takeaway-com/id333214491?uo=4">https://apps.apple.com/us/app/takeaway-com/id333214491?uo=4</a>
**App Version:** 4.22.0
**Seller:** Takeaway.com
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/takeaway-com/id329472762?uo=4">© Takeaway.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/06/88/fc/0688fc52-803e-5a98-0a1f-299a4227f6f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680988-c093cd80-9e8d-11e9-9d18-93707a7fc508.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680988-c093cd80-9e8d-11e9-9d18-93707a7fc508.png)
https://user-images.githubusercontent.com/20930745/60680988-c093cd80-9e8d-11e9-9d18-93707a7fc508.png

Source:
https://user-images.githubusercontent.com/20930745/60680990-c1c4fa80-9e8d-11e9-9041-6507db6dfafe.png

**Comment by iPOSEiDON** [comment]
thanks !
