### ISSUE TITLE
Bazar.bg

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#10234]
**App Name:** Bazar.bg
**Bundle ID:** com.rezonmedia.bazar-bg
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1401952373">1401952373</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bazar-bg/id1401952373?uo=4">https://apps.apple.com/us/app/bazar-bg/id1401952373?uo=4</a>
**App Version:** 1.0.3
**Seller:** Rezon Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/rezon-ltd/id439575269?uo=4">© Rezon Ltd</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/93/46/32/9346324d-6952-67c0-c0da-22a83afbe9d8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60681325-2a60a700-9e8f-11e9-8fe8-fb252df96b74.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60681325-2a60a700-9e8f-11e9-8fe8-fb252df96b74.png)
https://user-images.githubusercontent.com/20930745/60681325-2a60a700-9e8f-11e9-8fe8-fb252df96b74.png

Source:
https://user-images.githubusercontent.com/20930745/60681330-2cc30100-9e8f-11e9-86b0-0bd926761a1f.png

**Comment by iPOSEiDON** [comment]
thank you !
