### ISSUE TITLE
CloudBBQ

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10245]
**App Name:** CloudBBQ
**Bundle ID:** com.EnjoyBBQ.EnjoyBBQ
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1455760390">1455760390</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cloudbbq/id1455760390?uo=4">https://apps.apple.com/us/app/cloudbbq/id1455760390?uo=4</a>
**App Version:** 1.0.4
**Seller:** peng liu
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/peng-liu/id1455760389?uo=4">© peng liu</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a0/64/27/a0642728-ac93-6446-0f5e-6f0390094017/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60764958-1ab1b000-a093-11e9-9d64-d2c8ebc09182.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60764958-1ab1b000-a093-11e9-9d64-d2c8ebc09182.png)
https://user-images.githubusercontent.com/20930745/60764958-1ab1b000-a093-11e9-9d64-d2c8ebc09182.png

Source:
https://user-images.githubusercontent.com/20930745/60764959-1be2dd00-a093-11e9-9dd3-f24987442ac4.png
