### ISSUE TITLE
JackThreads

### ISSUE THREAD

**Issue by nproberson** [glasklart/hd#1024]
**App Name:** JackThreads
**Bundle ID:** com.thrillist.jackthreadsapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=472078451">472078451</a>
**iPhone Icon Name:** Icon@2x.png
**Icon Names:** Icon.png | Icon@2x.png | Icon-72.png | Icon-Small-50.png | Icon-Small.png | Icon-Small@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/jackthreads/id472078451?mt=8&uo=4
**App Version:** 1.8.2
**Seller:** Thrillist
**Supported Devices:** iPodTouchThirdGen, iPhone5c, iPadMini4G, iPhone5, iPhone-3GS, iPadThirdGen4G, iPhone4, iPadThirdGen, iPadFourthGen4G, iPad3G, iPhone4S, iPadMini, iPad23G, iPhone5s, iPadWifi, iPadFourthGen, iPodTouchourthGen, iPad2Wifi, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a349.phobos.apple.com/us/r30/Purple/v4/63/d8/8a/63d88ae0-7249-a9df-a774-f51e918dc0b4/mzl.tlqnjcbw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=http://glasklarthd.dreamnet.at/theicons/3451/icon1/Icon@2x.png)
http://glasklarthd.dreamnet.at/index.php?id=3451

**Comment by Teekzilla** [comment]
Icon was recently updated! Would make it myself but currently can't get the Glasklart style from the PSD.
New Icon: <img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/35/7d/e4/357de4c7-c174-badb-4203-c1221f659005/mzl.avrofxkk.png/0x0ss-85.jpg" width="150" height="150" />

**Comment by dreamnet** [comment]
For some reason Github dont let me update the original post - so I mark this as duplicate and open an new one.
