### ISSUE TITLE
Mein-Deal: Schnäppchen & Deals

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10246]
**App Name:** Mein-Deal: Schnäppchen & Deals
**Bundle ID:** de.menschdanke.meindeal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=585537923">585537923</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mein-deal-schn%C3%A4ppchen-deals/id585537923?uo=4">https://apps.apple.com/us/app/mein-deal-schn%C3%A4ppchen-deals/id585537923?uo=4</a>
**App Version:** 7.2.2
**Seller:** Ralph Moeller
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ralph-moeller/id1044703622?uo=4">© Ralph Moeller</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/af/8f/e6/af8fe6dc-b090-1eec-61a5-16ca1eea3527/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60765027-e8ed1900-a093-11e9-828f-3da64b6ba6e4.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60765027-e8ed1900-a093-11e9-828f-3da64b6ba6e4.png)
https://user-images.githubusercontent.com/20930745/60765027-e8ed1900-a093-11e9-828f-3da64b6ba6e4.png

Source:
https://user-images.githubusercontent.com/20930745/60765029-ea1e4600-a093-11e9-9c12-9c51327f7728.png
