### ISSUE TITLE
Clue Period, Menstrual Tracker

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10259]
**App Name:** Clue Period, Menstrual Tracker
**Bundle ID:** com.helloclue.clue
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=657189652">657189652</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/clue-period-menstrual-tracker/id657189652?uo=4">https://apps.apple.com/us/app/clue-period-menstrual-tracker/id657189652?uo=4</a>
**App Version:** 5.20
**Seller:** BioWink GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/biowink-gmbh/id657189655?uo=4">© BioWink GmbH</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/fb/ec/1f/fbec1f69-1b49-8860-e1d5-97e2203d43ad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62133719-8fb58580-b2df-11e9-8579-e0e4a70e249b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62133719-8fb58580-b2df-11e9-8579-e0e4a70e249b.png)
https://user-images.githubusercontent.com/20930745/62133719-8fb58580-b2df-11e9-8579-e0e4a70e249b.png

Source:
https://user-images.githubusercontent.com/20930745/62133722-917f4900-b2df-11e9-825a-f72e05b243bf.png
