### ISSUE TITLE
momox – Bücher, CD, DVD Ankauf

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10252]
**App Name:** momox - sell books, CDs, DVDs
**Bundle ID:** com.momox.momox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=414543719">414543719</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/momox-sell-books-cds-dvds/id414543719?uo=4">https://apps.apple.com/gb/app/momox-sell-books-cds-dvds/id414543719?uo=4</a>
**App Version:** 3.9.6
**Seller:** MOMOX GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/momox-gmbh/id414543722?uo=4">© MOMOX GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/52/4d/9b/524d9bb9-b999-9932-6506-971979ec8e07/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60903623-f95aea80-a271-11e9-9dfc-714722882fbc.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60903623-f95aea80-a271-11e9-9dfc-714722882fbc.png)
https://user-images.githubusercontent.com/20930745/60903623-f95aea80-a271-11e9-9dfc-714722882fbc.png

Source:
https://user-images.githubusercontent.com/20930745/60903630-fb24ae00-a271-11e9-89ac-3da9d7698eb5.png
