### ISSUE TITLE
Flo Period & Ovulation Tracker

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10258]
**App Name:** Flo Period & Ovulation Tracker
**Bundle ID:** org.iggymedia.periodtracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1038369065">1038369065</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/flo-period-ovulation-tracker/id1038369065?uo=4">https://apps.apple.com/us/app/flo-period-ovulation-tracker/id1038369065?uo=4</a>
**App Version:** 4.41
**Seller:** FLO HEALTH, INC.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/flo-health-inc/id1149787531?uo=4">© FLO HEALTH, INC.</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/26/73/02/2673024b-e14a-594d-bcf8-509f4a9954b4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62133310-dce52780-b2de-11e9-991a-421af980e0c4.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62133310-dce52780-b2de-11e9-991a-421af980e0c4.png)
https://user-images.githubusercontent.com/20930745/62133310-dce52780-b2de-11e9-991a-421af980e0c4.png

Source:
(https://user-images.githubusercontent.com/20930745/62133321-deaeeb00-b2de-11e9-8b00-d4c11b37d192.png

**Comment by liavoid** [comment]
Thank you
