### ISSUE TITLE
UB Mobile: The University at Buffalo Mobile App

### ISSUE THREAD

**Issue by nproberson** [glasklart/hd#1025]
**App Name:** UB Mobile: The University at Buffalo Mobile App
**Bundle ID:** edu.buffalo.icampus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=457650145">457650145</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ub-mobile-university-at-buffalo/id457650145?mt=8&uo=4">https://itunes.apple.com/us/app/ub-mobile-university-at-buffalo/id457650145?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** University At Buffalo
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/university-at-buffalo/id457650148?uo=4>© University at Buffalo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/94/9d/78/949d7802-88bd-e966-3d17-ae9d01563a63/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19494010/75d37d16-957d-11e6-932c-e084c6b1b3be.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19494010/75d37d16-957d-11e6-932c-e084c6b1b3be.png)
https://cloud.githubusercontent.com/assets/20930745/19494010/75d37d16-957d-11e6-932c-e084c6b1b3be.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19494042/95f69b00-957d-11e6-8fd6-81f49ba4a4bf.png
