### ISSUE TITLE
reBuy

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10251]
**App Name:** reBuy
**Bundle ID:** com.rebuy.App
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=859123857">859123857</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/rebuy/id859123857?uo=4">https://apps.apple.com/de/app/rebuy/id859123857?uo=4</a>
**App Version:** 4.7.15
**Seller:** reBuy reCommerce GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/rebuy-recommerce-gmbh/id835119276?uo=4">© reBuy reCommerce GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/5b/b3/bf/5bb3bf94-32a0-d89f-ebf5-8340120d9c98/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60903392-7f2a6600-a271-11e9-93d9-64227e72254e.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60903392-7f2a6600-a271-11e9-93d9-64227e72254e.png)
https://user-images.githubusercontent.com/20930745/60903392-7f2a6600-a271-11e9-93d9-64227e72254e.png

Source:
https://user-images.githubusercontent.com/20930745/60903394-80f42980-a271-11e9-9e95-d0ea8ccfeda1.png
