### ISSUE TITLE
OptiGrill by T-fal

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10250]
**App Name:** OptiGrill by T-fal
**Bundle ID:** com.groupeseb.optigrill
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1073127623">1073127623</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/ca/app/optigrill-by-t-fal/id1073127623?uo=4">https://apps.apple.com/ca/app/optigrill-by-t-fal/id1073127623?uo=4</a>
**App Version:** 11.1
**Seller:** SEB Developpement
**Developer:** <a target="_blank" href="https://apps.apple.com/ca/developer/seb-developpement/id406163916?uo=4">© SEB Developpement</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/cd/df/a1/cddfa195-812b-f541-f3ce-9ad940b31e0d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60903032-ed225d80-a270-11e9-941d-4b8b08c3a903.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60903032-ed225d80-a270-11e9-941d-4b8b08c3a903.png)
https://user-images.githubusercontent.com/20930745/60903032-ed225d80-a270-11e9-941d-4b8b08c3a903.png

Source:
https://user-images.githubusercontent.com/20930745/60903035-ee538a80-a270-11e9-88ea-191bebe57ec6.png
