### ISSUE TITLE
Paste by WeTransfer

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10255]
**App Name:** Paste by WeTransfer
**Bundle ID:** com.fiftythree.paste
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1259981327">1259981327</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/paste-by-wetransfer/id1259981327?uo=4">https://apps.apple.com/us/app/paste-by-wetransfer/id1259981327?uo=4</a>
**App Version:** 1.7.5
**Seller:** WeTransfer BV
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wetransfer-bv/id485103881?uo=4">© WeTransfer BV</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/41/0a/ab/410aabcf-e061-ce77-d4f8-0c138be97bbc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85228176-29978c80-b3e2-11ea-8fd5-2c4d663ded93.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61992062-874c1900-b059-11e9-8f8e-f419f861082d.png)
https://user-images.githubusercontent.com/2068130/61992062-874c1900-b059-11e9-8f8e-f419f861082d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/61992073-96cb6200-b059-11e9-95b4-88bc8e4ecb6f.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Paste by WeTransfer
**Bundle ID:** com.fiftythree.paste
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1259981327">1259981327</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/paste-by-wetransfer/id1259981327?uo=4">https://apps.apple.com/us/app/paste-by-wetransfer/id1259981327?uo=4</a>
**App Version:** 1.7.5
**Seller:** WeTransfer BV
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wetransfer-bv/id485103881?uo=4">© WeTransfer BV</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/41/0a/ab/410aabcf-e061-ce77-d4f8-0c138be97bbc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85228176-29978c80-b3e2-11ea-8fd5-2c4d663ded93.png)
https://user-images.githubusercontent.com/2068130/85228176-29978c80-b3e2-11ea-8fd5-2c4d663ded93.png)
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85228186-3d42f300-b3e2-11ea-92e7-f4efa1f78026.png
