### ISSUE TITLE
SNOW - Beauty & makeup camera

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10260]
**App Name:** SNOW - Beauty & makeup camera
**Bundle ID:** com.campmobile.snow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1022267439">1022267439</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/snow-beauty-makeup-camera/id1022267439?uo=4">https://apps.apple.com/us/app/snow-beauty-makeup-camera/id1022267439?uo=4</a>
**App Version:** 8.6.5
**Seller:** SNOW INC.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/snow-inc/id1244624324?uo=4">© SNOW INC.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/26/49/13/264913d4-46c2-07a7-87d1-51564f710dcd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62135432-7e21ad00-b2e2-11e9-9e5d-47157821ba71.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62135432-7e21ad00-b2e2-11e9-9e5d-47157821ba71.png)
https://user-images.githubusercontent.com/20930745/62135432-7e21ad00-b2e2-11e9-9e5d-47157821ba71.png

Source:
https://user-images.githubusercontent.com/20930745/62135435-7f52da00-b2e2-11e9-89fa-9fe2a2f6b414.png
