### ISSUE TITLE
OsmAnd Maps Travel & Navigate

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10261]
**App Name:** OsmAnd Maps Travel & Navigate
**Bundle ID:** net.osmand.maps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=934850257">934850257</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/osmand-maps-travel-navigate/id934850257?uo=4">https://apps.apple.com/us/app/osmand-maps-travel-navigate/id934850257?uo=4</a>
**App Version:** 2.90
**Seller:** OsmAND B.V.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/osmand-b-v/id934850255?uo=4">© OsmAND B.V.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/9c/86/48/9c864828-b553-7757-c172-7370f025517e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62136485-824eca00-b2e4-11e9-81c5-3275ebcdcd32.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62136207-ea50e080-b2e3-11e9-80ea-759e8643798a.png)
(https://user-images.githubusercontent.com/20930745/62136207-ea50e080-b2e3-11e9-80ea-759e8643798a.png

Source:
https://user-images.githubusercontent.com/20930745/62136210-eae97700-b2e3-11e9-99dd-54ff28acf2e9.png

**Comment by 2Qt2beStr8** [comment]
or full size?

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62136485-824eca00-b2e4-11e9-81c5-3275ebcdcd32.png)
https://user-images.githubusercontent.com/20930745/62136485-824eca00-b2e4-11e9-81c5-3275ebcdcd32.png

Source:
https://user-images.githubusercontent.com/20930745/62136490-84188d80-b2e4-11e9-97ad-ed0d80a91d51.png

**Comment by liavoid** [comment]
Full size, please
