### ISSUE TITLE
NovelLoop

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10267]
**App Name:** NovelLoop
**Bundle ID:** com.culdesaq.novelloop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1170755867">1170755867</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/novelloop/id1170755867?uo=4">https://apps.apple.com/us/app/novelloop/id1170755867?uo=4</a>
**App Version:** 1.23.1
**Seller:** Cameron Jackson
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cameron-jackson/id1091923157?uo=4">© Cameron Jackson</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/41/1d/55/411d55a9-23c7-bb57-2769-462095471345/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62216856-d374c180-b3a9-11e9-8c74-d167b5f0ef5f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62216856-d374c180-b3a9-11e9-8c74-d167b5f0ef5f.png)
https://user-images.githubusercontent.com/2068130/62216856-d374c180-b3a9-11e9-8c74-d167b5f0ef5f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62216880-e2f40a80-b3a9-11e9-9e7d-f671f2d420bb.png
