### ISSUE TITLE
Day One Journal

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10264]
**App Name:** Day One Journal
**Bundle ID:** com.bloombuilt.dayone-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1044867788">1044867788</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/day-one-journal/id1044867788?uo=4">https://apps.apple.com/us/app/day-one-journal/id1044867788?uo=4</a>
**App Version:** 4.0
**Seller:** Bloom Built Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bloom-built-inc/id379561506?uo=4">© Bloom Built Inc</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/51/56/68/5156685c-faa9-4efb-440e-4be32deb021b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62227172-bb0da280-b3bb-11e9-9c61-4bda74cefa94.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62227172-bb0da280-b3bb-11e9-9c61-4bda74cefa94.png)
https://user-images.githubusercontent.com/2068130/62227172-bb0da280-b3bb-11e9-9c61-4bda74cefa94.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62227222-cc56af00-b3bb-11e9-8f3b-085deb0ae3c6.png
