### ISSUE TITLE
Slide for Reddit

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10262]
**App Name:** Slide for Reddit
**Bundle ID:** ccrama.me.redditslide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1260626828">1260626828</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/slide-for-reddit/id1260626828?uo=4">https://apps.apple.com/us/app/slide-for-reddit/id1260626828?uo=4</a>
**App Version:** 3.1
**Seller:** Carlos Crane
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/carlos-crane/id1260626827?uo=4">© Carlos Crane</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/29/1c/f1/291cf1bd-ae7e-48eb-ebce-a6678ab3817a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62137067-9e9f3680-b2e5-11e9-88de-2acaa9d4fb51.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62137067-9e9f3680-b2e5-11e9-88de-2acaa9d4fb51.png)
https://user-images.githubusercontent.com/20930745/62137067-9e9f3680-b2e5-11e9-88de-2acaa9d4fb51.png

Source:
https://user-images.githubusercontent.com/20930745/62137076-9fd06380-b2e5-11e9-979b-5cce86c2cfc9.png
