### ISSUE TITLE
Paprika Recipe Manager 3

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10263]
**App Name:** Paprika Recipe Manager 3
**Bundle ID:** com.hindsightlabs.paprika.ios.v3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1303222868">1303222868</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/paprika-recipe-manager-3/id1303222868?uo=4">https://apps.apple.com/us/app/paprika-recipe-manager-3/id1303222868?uo=4</a>
**App Version:** 3.3.6
**Seller:** Hindsight Labs LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hindsight-labs-llc/id392408031?uo=4">© Hindsight Labs LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/cc/3d/2d/cc3d2d64-8df4-b11e-8818-7419532667b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18095909/c799f010-6ed8-11e6-9858-1d06065e1578.png)

**Comment by dreamnet** [comment]
Same as #7587. 
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18095909/c799f010-6ed8-11e6-9858-1d06065e1578.png)
https://cloud.githubusercontent.com/assets/2068130/18095909/c799f010-6ed8-11e6-9858-1d06065e1578.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18095934/da103d9e-6ed8-11e6-82fc-54ec033ecb1b.png
