### ISSUE TITLE
Choice of Games

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10269]
**App Name:** Choice of Games
**Bundle ID:** com.choiceofgames.o
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1363309257">1363309257</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/choice-of-games/id1363309257?uo=4">https://apps.apple.com/us/app/choice-of-games/id1363309257?uo=4</a>
**App Version:** 1.12.0
**Seller:** Choice of Games LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/choice-of-games-llc/id348940935?uo=4">© Choice of Games LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/9c/65/44/9c654416-80d2-e74a-3f3e-22b0a72a3d4f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62215815-edada000-b3a7-11e9-9b18-a0bab52893fa.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62215815-edada000-b3a7-11e9-9b18-a0bab52893fa.png)
https://user-images.githubusercontent.com/2068130/62215815-edada000-b3a7-11e9-9b18-a0bab52893fa.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62215854-fd2ce900-b3a7-11e9-8a5d-d6b165dee7b8.png
