### ISSUE TITLE
Merriam-Webster Dictionary

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10271]
**App Name:** Merriam-Webster Dictionary
**Bundle ID:** com.m-w.dictionary
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=399452287">399452287</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/merriam-webster-dictionary/id399452287?uo=4">https://apps.apple.com/us/app/merriam-webster-dictionary/id399452287?uo=4</a>
**App Version:** 4.6.6
**Seller:** Merriam-Webster, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/merriam-webster-inc/id399452290?uo=4">© Merriam-Webster, Inc.</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/40/ab/84/40ab8403-cbbd-b161-e367-4400df6b3dfd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62215158-b2f73800-b3a6-11e9-9f88-599c328c9a8a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62215158-b2f73800-b3a6-11e9-9f88-599c328c9a8a.png)
https://user-images.githubusercontent.com/2068130/62215158-b2f73800-b3a6-11e9-9f88-599c328c9a8a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62215201-c3a7ae00-b3a6-11e9-87fb-288af17306ef.png
