### ISSUE TITLE
Keybase - Crypto for Everyone

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10274]
**App Name:** Keybase - Crypto for Everyone
**Bundle ID:** keybase.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1044461770">1044461770</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/keybase-crypto-for-everyone/id1044461770?uo=4">https://apps.apple.com/us/app/keybase-crypto-for-everyone/id1044461770?uo=4</a>
**App Version:** 4.2.0
**Seller:** Keybase, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/keybase/id1044460764?uo=4">© Keybase</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/cf/96/05/cf9605b3-f0e7-d537-0de9-bcc0f3f8c453/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62225716-4c2f4a00-b3b9-11e9-9fdd-73329aa11553.png)

**Comment by dreamnet** [comment]
?
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62225716-4c2f4a00-b3b9-11e9-9fdd-73329aa11553.png)
https://user-images.githubusercontent.com/2068130/62225716-4c2f4a00-b3b9-11e9-9fdd-73329aa11553.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62225752-5d785680-b3b9-11e9-8b3f-3cc53009cf9a.png
