### ISSUE TITLE
Joplin

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10270]
**App Name:** Joplin
**Bundle ID:** net.cozic.joplin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1315599797">1315599797</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/joplin/id1315599797?uo=4">https://apps.apple.com/us/app/joplin/id1315599797?uo=4</a>
**App Version:** 10.0.36
**Seller:** Laurent Cozic
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/laurent-cozic/id1315599796?uo=4">© Laurent Cozic</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/e2/44/70/e24470fe-d83e-50ce-a36f-7c8d4f9db6b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62215500-6102e200-b3a7-11e9-871a-a920b206061f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62215500-6102e200-b3a7-11e9-871a-a920b206061f.png)
https://user-images.githubusercontent.com/2068130/62215500-6102e200-b3a7-11e9-871a-a920b206061f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62215532-70822b00-b3a7-11e9-9ead-cef6f1647bba.png
