### ISSUE TITLE
EMERGENCY HQ

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10279]
**App Name:** EMERGENCY HQ
**Bundle ID:** com.sgs.emhq.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=859148736">859148736</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/emergency-hq/id859148736?uo=4">https://apps.apple.com/us/app/emergency-hq/id859148736?uo=4</a>
**App Version:** 1.4.4
**Seller:** Promotion Software GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/promotion-software-gmbh/id321227098?uo=4">© Promotion Software GmbH</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/07/48/23/07482328-70bc-6b99-fde4-4a6076955e7a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/70372527-700f1900-18e0-11ea-9b1e-7dada3f85b37.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70361828-3cea6c80-1883-11ea-9ce4-99ca6251c32c.png)
https://user-images.githubusercontent.com/20930745/70361828-3cea6c80-1883-11ea-9ce4-99ca6251c32c.png

Source:
https://user-images.githubusercontent.com/20930745/70361834-3fe55d00-1883-11ea-9377-3801bc157358.png

**Comment by dreamnet** [comment]
?
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/70372527-700f1900-18e0-11ea-9b1e-7dada3f85b37.png)
https://user-images.githubusercontent.com/2068130/70372527-700f1900-18e0-11ea-9b1e-7dada3f85b37.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/70372535-80bf8f00-18e0-11ea-9253-0612205b6de8.png
