### ISSUE TITLE
HuffPost - News & Politics

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#10275]
**App Name:** HuffPost - News & Politics
**Bundle ID:** com.huffingtonpost.HuffingtonPost
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306621789">306621789</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/huffpost-news-politics/id306621789?uo=4">https://apps.apple.com/us/app/huffpost-news-politics/id306621789?uo=4</a>
**App Version:** 16.1.4
**Seller:** The Huffington Post
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/huffpost/id306621792?uo=4">© HuffPost</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/b0/a6/16/b0a616e1-410a-8010-5b8d-cf6141692ebf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62392639-45930500-b568-11e9-9321-10a49ad70b52.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62392639-45930500-b568-11e9-9321-10a49ad70b52.png)
https://user-images.githubusercontent.com/20930745/62392639-45930500-b568-11e9-9321-10a49ad70b52.png

Source:
https://user-images.githubusercontent.com/20930745/62392642-46c43200-b568-11e9-8b8a-c57ed986bf5a.png
