### ISSUE TITLE
BatteryPhone

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10278]
**App Name:** BatteryPhone
**Bundle ID:** com.kyasusoft.batteryphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1191334332">1191334332</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/batteryphone/id1191334332?uo=4">https://apps.apple.com/us/app/batteryphone/id1191334332?uo=4</a>
**App Version:** 2.5
**Seller:** Keietsu Yasuhara
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/keietsu-yasuhara/id378538320?uo=4">© Keietsu Yasuhara</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/d1/a0/97/d1a09783-2d65-8af0-aaa7-6fe49292a1bb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62398909-68c6b000-b57a-11e9-9802-22073ba941e2.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62398909-68c6b000-b57a-11e9-9802-22073ba941e2.png)
https://user-images.githubusercontent.com/2068130/62398909-68c6b000-b57a-11e9-9802-22073ba941e2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62398940-7845f900-b57a-11e9-892d-5658f36556a6.png
