### ISSUE TITLE
FileBrowser - Access files on remote computers

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1027]
**App Name:** FileBrowser - Access files on remote computers
**Bundle ID:** com.stratospherix.filebrowser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364738545">364738545</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/filebrowser-access-files-on/id364738545?mt=8&uo=4">https://itunes.apple.com/us/app/filebrowser-access-files-on/id364738545?mt=8&uo=4</a>
**App Version:** 8.7
**Seller:** Stratospherix
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stratospherix-ltd/id323133606?uo=4>© Stratospherix Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/67/48/2d/67482d2e-bb0b-89b2-7e02-4a5c58a797c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416302/d5020d50-7810-11e6-849d-0c37ea6b0a27.png)

**Comment by 2Qt2beStr8** [comment]
Update

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18411212/98cbecea-7773-11e6-9b73-b4e5a7a742dd.png)
https://cloud.githubusercontent.com/assets/20930745/18411212/98cbecea-7773-11e6-9b73-b4e5a7a742dd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18411216/a644920a-7773-11e6-9a1a-b676fc3b46da.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416302/d5020d50-7810-11e6-849d-0c37ea6b0a27.png)
https://cloud.githubusercontent.com/assets/2068130/18416302/d5020d50-7810-11e6-849d-0c37ea6b0a27.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416303/e2a7749a-7810-11e6-971e-7037c39b2a73.png
