### ISSUE TITLE
Sid Meier's Civilization® VI

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10273]
**App Name:** Sid Meier's Civilization® VI
**Bundle ID:** com.aspyr.civilization6.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1235863443">1235863443</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sid-meiers-civilization-vi/id1235863443?uo=4">https://apps.apple.com/us/app/sid-meiers-civilization-vi/id1235863443?uo=4</a>
**App Version:** 1.1.0
**Seller:** Aspyr Media (iDP)
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/aspyr-media-inc/id296399696?uo=4">© Aspyr Media, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/0f/99/06/0f9906e4-6358-696c-97ca-45d53746f9af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62226718-e774ef00-b3ba-11e9-94c5-9345d2b24e8d.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62226718-e774ef00-b3ba-11e9-94c5-9345d2b24e8d.png)
https://user-images.githubusercontent.com/2068130/62226718-e774ef00-b3ba-11e9-94c5-9345d2b24e8d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62226747-f6f43800-b3ba-11e9-8ce7-2bde625e3318.png
