### ISSUE TITLE
Cookie Run: OvenBreak

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10281]
**App Name:** Cookie Run: OvenBreak
**Bundle ID:** com.devsisters.gb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=963067330">963067330</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cookie-run-ovenbreak/id963067330?uo=4">https://apps.apple.com/us/app/cookie-run-ovenbreak/id963067330?uo=4</a>
**App Version:** 4.62
**Seller:** Devsisters Corp.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/devsisters/id311464410?uo=4">© Devsisters</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/93/78/c0/9378c017-98d1-e836-732e-ef793c0822ff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65827746-e0bc0880-e293-11e9-99db-32e06178df36.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/65474408-50b83200-de41-11e9-80c0-8660557e314b.png)

Source:
https://user-images.githubusercontent.com/44279267/65474729-87427c80-de42-11e9-87f9-5645abe4b86c.png

**Comment by tlunmp** [comment]
no idea how to put image on the user issue

**Comment by dreamnet** [comment]
@tlunmp Jup, nice! 👍

**Comment by tlunmp** [comment]
I did change my settings on public email I'm not sure if I did right. thanks. I would like to help make more icons in the future
