### ISSUE TITLE
Bubble Wrap FREE

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10285]
**App Name:** Bubble Wrap FREE
**Bundle ID:** com.limasky.bubblewrapfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=466524746">466524746</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bubble-wrap-free/id466524746?uo=4">https://apps.apple.com/us/app/bubble-wrap-free/id466524746?uo=4</a>
**App Version:** 1.0.2
**Seller:** Lima Sky
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lima-sky/id285874818?uo=4">© Lima Sky</a>
**Supported Devices:** iPhoneFirstGen-iPhone, iPodTouchFirstGen-iPod-touch, iPodTouchSecondGen-iPod-touch-with-mic, iPhone3G-iPhone-3G, iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple/v4/d2/7c/69/d27c6954-0e28-ac03-87ff-37466eab9993/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62484387-605cb800-b7ba-11e9-8474-daaf535b4333.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62484387-605cb800-b7ba-11e9-8474-daaf535b4333.png)
https://user-images.githubusercontent.com/2068130/62484387-605cb800-b7ba-11e9-8474-daaf535b4333.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62484413-6f436a80-b7ba-11e9-9f85-42ff8fec1431.png
