### ISSUE TITLE
audioBoom

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1028]
**App Name:** audioBoom
**Bundle ID:** tv.bestbefore.AudioBoo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=305204540">305204540</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/audioboom/id305204540?mt=8&uo=4">https://itunes.apple.com/us/app/audioboom/id305204540?mt=8&uo=4</a>
**App Version:** 5.7.6
**Seller:** Audioboo Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/audioboo-ltd/id777565180?uo=4>© Audioboo Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/74/e0/0b/74e00b45-d37e-55ad-3d20-191d7102067d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19321067/3aef957c-90b4-11e6-949d-5f41b1209ad7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19321067/3aef957c-90b4-11e6-949d-5f41b1209ad7.png)
https://cloud.githubusercontent.com/assets/20930745/19321067/3aef957c-90b4-11e6-949d-5f41b1209ad7.png

https://cloud.githubusercontent.com/assets/20930745/19321081/4e3c1fb0-90b4-11e6-81f6-b802c9f2e7a3.png
