### ISSUE TITLE
Dr. Mario World

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10280]
**App Name:** Dr. Mario World
**Bundle ID:** com.nintendo.zama
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1440129313">1440129313</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dr-mario-world/id1440129313?uo=4">https://apps.apple.com/us/app/dr-mario-world/id1440129313?uo=4</a>
**App Version:** 1.0.3
**Seller:** Nintendo Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nintendo-co-ltd/id1062496488?uo=4">© Nintendo Co., Ltd.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/6a/72/d4/6a72d40c-2ac8-98dd-d8d1-f528f09b370d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62426600-21116700-b6e7-11e9-9111-506ea7bb3fbe.png)

**Comment by dreamnet** [comment]
?
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62426600-21116700-b6e7-11e9-9111-506ea7bb3fbe.png)
https://user-images.githubusercontent.com/2068130/62426600-21116700-b6e7-11e9-9111-506ea7bb3fbe.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62426604-371f2780-b6e7-11e9-83dd-46a93ed0c849.png
