### ISSUE TITLE
Sonic Dash

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10287]
**App Name:** Sonic Dash
**Bundle ID:** com.sega.sonicdash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=582654048">582654048</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sonic-dash/id582654048?uo=4">https://apps.apple.com/us/app/sonic-dash/id582654048?uo=4</a>
**App Version:** 4.3.1
**Seller:** Sega America
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sega/id281966698?uo=4">© SEGA</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/a6/d3/06/a6d30687-1f21-4166-4af4-09bdeb4a3710/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62481284-52a33480-b7b2-11e9-85a4-c3311370cc8a.png)

**Comment by dreamnet** [comment]
?
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62481284-52a33480-b7b2-11e9-85a4-c3311370cc8a.png)
https://user-images.githubusercontent.com/2068130/62481284-52a33480-b7b2-11e9-85a4-c3311370cc8a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62481308-651d6e00-b7b2-11e9-8677-6a11528d38b3.png
