### ISSUE TITLE
Kick the Buddy

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10289]
**App Name:** Kick the Buddy
**Bundle ID:** com.chillfleet.buddy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1278869953">1278869953</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/kick-the-buddy/id1278869953?uo=4">https://apps.apple.com/us/app/kick-the-buddy/id1278869953?uo=4</a>
**App Version:** 1.3.8
**Seller:** Chill Fleet GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/chill-fleet/id1191476886?uo=4">© Chill Fleet</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/18/09/d0/1809d061-a5d7-2b3e-47f6-cf67c7baa513/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63216549-fa1b5200-c136-11e9-9380-0baf5431c8e0.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63216549-fa1b5200-c136-11e9-9380-0baf5431c8e0.png)
https://user-images.githubusercontent.com/2068130/63216549-fa1b5200-c136-11e9-9380-0baf5431c8e0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/63216552-099a9b00-c137-11e9-9630-3989dda8fa45.png
