### ISSUE TITLE
Wayback Machine

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10284]
**App Name:** Wayback Machine
**Bundle ID:** com.mobile.waybackmachine
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1201888313">1201888313</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wayback-machine/id1201888313?uo=4">https://apps.apple.com/us/app/wayback-machine/id1201888313?uo=4</a>
**App Version:** 2.8.7
**Seller:** Internet Archive
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/internet-archive/id1197048903?uo=4">© Internet Archive</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/39/2a/68/392a68fc-7474-fd10-876f-06fd955442a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62442551-87829d80-b758-11e9-9dd4-923194f28863.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62442551-87829d80-b758-11e9-9dd4-923194f28863.png)
https://user-images.githubusercontent.com/2068130/62442551-87829d80-b758-11e9-9dd4-923194f28863.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62442571-979a7d00-b758-11e9-9cdf-07b07f8c1a88.png
