### ISSUE TITLE
Turbo Dismount®

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10283]
**App Name:** Turbo Dismount®
**Bundle ID:** com.secretexit.trdismount
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=881155044">881155044</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/turbo-dismount/id881155044?uo=4">https://apps.apple.com/us/app/turbo-dismount/id881155044?uo=4</a>
**App Version:** 1.33.0
**Seller:** Secret Exit Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/secret-exit-ltd/id294263406?uo=4">© Secret Exit Ltd.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/d5/e2/da/d5e2da5f-883a-81db-5c51-6d75d398c735/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71319723-34f51400-24a2-11ea-9523-9b34971a207e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71319723-34f51400-24a2-11ea-9523-9b34971a207e.png)
https://user-images.githubusercontent.com/2068130/71319723-34f51400-24a2-11ea-9523-9b34971a207e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71319728-44745d00-24a2-11ea-924e-b58b3fa7a404.png
