### ISSUE TITLE
Stair Dismount®

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10288]
**App Name:** Stair Dismount®
**Bundle ID:** com.secretexit.sdt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=326469137">326469137</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stair-dismount/id326469137?uo=4">https://apps.apple.com/us/app/stair-dismount/id326469137?uo=4</a>
**App Version:** 2.9.0
**Seller:** Secret Exit Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/secret-exit-ltd/id294263406?uo=4">© Secret Exit Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/af/c5/fc/afc5fcb2-21de-76f8-f3c4-dcd49b3a2033/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65371213-b8178b80-dc61-11e9-8a0c-ea04aea551cf.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65371213-b8178b80-dc61-11e9-8a0c-ea04aea551cf.png)
https://user-images.githubusercontent.com/2068130/65371213-b8178b80-dc61-11e9-8a0c-ea04aea551cf.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65371219-c6fe3e00-dc61-11e9-81c2-cacd0022937e.png
