### ISSUE TITLE
Rabbit – Watch Together

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10282]
**App Name:** Rabbit – Watch Together
**Bundle ID:** it.rabb.rabbitios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1034629715">1034629715</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/rabbit-watch-together/id1034629715?uo=4">https://apps.apple.com/us/app/rabbit-watch-together/id1034629715?uo=4</a>
**App Version:** 4.0.95
**Seller:** RABBIT, INC.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/rabbit-inc/id1034629714?uo=4">© Rabbit, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/95/8f/af/958faf29-11d1-bc3b-0436-6f37d17f5d83/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62442024-be57b400-b756-11e9-902e-1d10837dea43.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62442024-be57b400-b756-11e9-902e-1d10837dea43.png)
https://user-images.githubusercontent.com/2068130/62442024-be57b400-b756-11e9-902e-1d10837dea43.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62442040-cf082a00-b756-11e9-884b-fcd2c7c654ba.png
