### ISSUE TITLE
Sausage Flip

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10290]
**App Name:** Sausage Flip
**Bundle ID:** com.sausageflip.game
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1446456468">1446456468</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sausage-flip/id1446456468?uo=4">https://apps.apple.com/us/app/sausage-flip/id1446456468?uo=4</a>
**App Version:** 1.4.0
**Seller:** MADBOX
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/madbox/id981448700?uo=4">© MADBOX</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/f2/76/c9/f276c91a-47eb-8da0-2e94-d225ddb3ea7d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64920172-65972480-d7b4-11e9-8fad-af86ea7d01a1.png)

**Comment by tlunmp** [comment]
First one to make an icon. I tried

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/64919859-9c9a1580-d775-11e9-9349-5be072b5cb47.png)

source
![sausage-flip-source](https://user-images.githubusercontent.com/44279267/64919894-f00c6380-d775-11e9-94c8-d51e99a2f3f4.png)

**Comment by dreamnet** [comment]
@tlunmp Yes, I generally like it. Did some small changes only:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64920172-65972480-d7b4-11e9-8fad-af86ea7d01a1.png)
https://user-images.githubusercontent.com/2068130/64920172-65972480-d7b4-11e9-8fad-af86ea7d01a1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64920173-73e54080-d7b4-11e9-9c7c-15d8a139461d.png
