### ISSUE TITLE
aquapark.io

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10293]
**App Name:** aquapark.io
**Bundle ID:** com.cassette.aquapark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1453989822">1453989822</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/aquapark-io/id1453989822?uo=4">https://apps.apple.com/us/app/aquapark-io/id1453989822?uo=4</a>
**App Version:** 2.8
**Seller:** Voodoo
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/voodoo/id714804730?uo=4">© Voodoo</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/34/9f/d8/349fd805-a84b-d499-c923-cda2383d095d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64919768-22868280-d7af-11e9-8b22-91085df2d98a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64919768-22868280-d7af-11e9-8b22-91085df2d98a.png)
https://user-images.githubusercontent.com/2068130/64919768-22868280-d7af-11e9-8b22-91085df2d98a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64919783-3205cb80-d7af-11e9-93b0-4242f74380fe.png
