### ISSUE TITLE
The Zeus Network

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10299]
**App Name:** The Zeus Network
**Bundle ID:** com.thezeusnetwork.www
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1399446592">1399446592</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/the-zeus-network/id1399446592?uo=4">https://apps.apple.com/us/app/the-zeus-network/id1399446592?uo=4</a>
**App Version:** 4.951
**Seller:** Zeus Networks, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-zeus-networks/id1399446591?uo=4">© The Zeus Networks</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/fa/9f/9f/fa9f9f87-f875-2e1e-e8c1-a471c47032d1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838463-d6f72b00-bc7c-11e9-983a-642acf4e91da.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838463-d6f72b00-bc7c-11e9-983a-642acf4e91da.png)
https://user-images.githubusercontent.com/2068130/62838463-d6f72b00-bc7c-11e9-983a-642acf4e91da.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838468-e70f0a80-bc7c-11e9-84f0-8d2e336c170f.png
