### ISSUE TITLE
iPeng Classic

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1030]
**App Name:** iPeng Classic
**Bundle ID:** com.penguinlovesmusic.iPeng
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=296941576">296941576</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ipeng-classic/id296941576?mt=8&uo=4">https://itunes.apple.com/us/app/ipeng-classic/id296941576?mt=8&uo=4</a>
**App Version:** 2.0.17
**Seller:** Du!Business GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/penguinlovesmusic.com/id296941579?uo=4">© PenguinLovesMusic.com</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/67/99/b0/6799b01f-cd5b-f9fb-c8c8-11d48b950ac7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19919253/c49b2e44-a0d1-11e6-8ed1-3e9632c13b1c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19919253/c49b2e44-a0d1-11e6-8ed1-3e9632c13b1c.png)
https://cloud.githubusercontent.com/assets/20930745/19919253/c49b2e44-a0d1-11e6-8ed1-3e9632c13b1c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19919267/dde200d0-a0d1-11e6-9da9-706e4de978c0.png
