### ISSUE TITLE
MyFont - Myanmar Font

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10309]
**App Name:** MyFont - Myanmar Font
**Bundle ID:** com.myopenware.MyFont
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=855256130">855256130</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myfont-myanmar-font/id855256130?uo=4">https://apps.apple.com/us/app/myfont-myanmar-font/id855256130?uo=4</a>
**App Version:** 3.4
**Seller:** Hein thet Khin zaw
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hein-thet-khin-zaw/id541922144?uo=4">© Hein thet Khin zaw</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/06/3f/65/063f6513-d8f6-6c1b-4938-b8c3a0e02496/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838096-da3be800-bc77-11e9-85e0-166267c5764c.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838096-da3be800-bc77-11e9-85e0-166267c5764c.png)
https://user-images.githubusercontent.com/2068130/62838096-da3be800-bc77-11e9-85e0-166267c5764c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838102-ea53c780-bc77-11e9-8bf4-90e91a8ada65.png
