### ISSUE TITLE
KyPass - Keepass in sync

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10302]
**App Name:** KyPass - Keepass in sync
**Bundle ID:** be.kyuran.kypass4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1258708743">1258708743</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/kypass-keepass-in-sync/id1258708743?uo=4">https://apps.apple.com/us/app/kypass-keepass-in-sync/id1258708743?uo=4</a>
**App Version:** 4.5.2
**Seller:** Miguel Vanhove
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/miguel-vanhove/id317808074?uo=4">© Miguel Vanhove</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/87/3a/c5/873ac5ec-8122-4950-1cb0-cc4c7c366450/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838394-b7abce00-bc7b-11e9-9acb-1c24e3c892a8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838394-b7abce00-bc7b-11e9-9acb-1c24e3c892a8.png)
https://user-images.githubusercontent.com/2068130/62838394-b7abce00-bc7b-11e9-9acb-1c24e3c892a8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838400-c85c4400-bc7b-11e9-838c-aa7e192914d2.png
