### ISSUE TITLE
My Ooredoo

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10305]
**App Name:** My Ooredoo
**Bundle ID:** com.ooredoo.myooredoo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=976062898">976062898</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/my-ooredoo/id976062898?uo=4">https://apps.apple.com/us/app/my-ooredoo/id976062898?uo=4</a>
**App Version:** 7.1.0
**Seller:** OOREDOO MYANMAR LIMITED
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ooredoo-myanmar-limited/id975112424?uo=4">© Ooredoo Myanmar Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/5a/50/dc/5a50dced-7aa9-99f7-1ebd-5c231feceb55/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838308-9ac2cb00-bc7a-11e9-9d2f-6c60a32efea4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838308-9ac2cb00-bc7a-11e9-9d2f-6c60a32efea4.png)
https://user-images.githubusercontent.com/2068130/62838308-9ac2cb00-bc7a-11e9-9d2f-6c60a32efea4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838318-add59b00-bc7a-11e9-93a1-d132c7bd2ec8.png
