### ISSUE TITLE
Dave & Buster’s Charger

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10300]
**App Name:** Dave & Buster’s Charger
**Bundle ID:** com.daveandbusters.DaveAndBusters
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=548016454">548016454</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dave-busters-charger/id548016454?uo=4">https://apps.apple.com/us/app/dave-busters-charger/id548016454?uo=4</a>
**App Version:** 5.0.1
**Seller:** Apriva Systems, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apriva/id380025667?uo=4">© Apriva</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/6a/fe/c4/6afec4ae-0fb5-e69d-f39f-db13b2bbf5e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838503-787e7c80-bc7d-11e9-8624-6067c6cec5b2.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838503-787e7c80-bc7d-11e9-8624-6067c6cec5b2.png)
https://user-images.githubusercontent.com/2068130/62838503-787e7c80-bc7d-11e9-8624-6067c6cec5b2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838509-89c78900-bc7d-11e9-92f3-618208c34295.png
