### ISSUE TITLE
My Mytel

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10307]
**App Name:** My Mytel
**Bundle ID:** com.vtg.app.mymytel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1390434643">1390434643</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/my-mytel/id1390434643?uo=4">https://apps.apple.com/us/app/my-mytel/id1390434643?uo=4</a>
**App Version:** 1.3.0
**Seller:** TELECOM INTERNATIONAL MYANMAR CO.,LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mytel/id1368364879?uo=4">© MyTel</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/97/e0/c6/97e0c6b5-0778-3b65-869a-75f4404fa37a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838171-f1c7a080-bc78-11e9-8604-a7419a73e32e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838171-f1c7a080-bc78-11e9-8604-a7419a73e32e.png)
https://user-images.githubusercontent.com/2068130/62838171-f1c7a080-bc78-11e9-8604-a7419a73e32e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838180-0310ad00-bc79-11e9-9a54-5257e9f150ff.png
