### ISSUE TITLE
UniChar — Unicode Keyboard

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10303]
**App Name:** UniChar — Unicode Keyboard
**Bundle ID:** com.jordanhipwell.unichar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=880811847">880811847</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/unichar-unicode-keyboard/id880811847?uo=4">https://apps.apple.com/us/app/unichar-unicode-keyboard/id880811847?uo=4</a>
**App Version:** 6.2.4
**Seller:** Jordan Hipwell
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/jordan-hipwell/id880811850?uo=4">© Jordan Hipwell</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/53/03/b2/5303b25a-f7f0-3404-ba45-36ecde0e058f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838351-1b81c700-bc7b-11e9-820d-9c7b61533824.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838351-1b81c700-bc7b-11e9-820d-9c7b61533824.png)
https://user-images.githubusercontent.com/2068130/62838351-1b81c700-bc7b-11e9-820d-9c7b61533824.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838357-2fc5c400-bc7b-11e9-83d5-f6a550663594.png
