### ISSUE TITLE
MyTelenor, Myanmar

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10304]
**App Name:** MyTelenor, Myanmar
**Bundle ID:** mm.cws.telenor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=952597596">952597596</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mytelenor-myanmar/id952597596?uo=4">https://apps.apple.com/us/app/mytelenor-myanmar/id952597596?uo=4</a>
**App Version:** 3.7.0
**Seller:** Telenor Myanmar
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/telenor-myanmar/id952597595?uo=4">© Telenor Myanmar</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/da/f0/b4/daf0b45c-0d62-935e-a1b2-4f0b2ab15467/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838211-5b47af00-bc79-11e9-8aa6-97a60f357fe6.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838211-5b47af00-bc79-11e9-8aa6-97a60f357fe6.png)
https://user-images.githubusercontent.com/2068130/62838211-5b47af00-bc79-11e9-8aa6-97a60f357fe6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838213-6bf82500-bc79-11e9-9593-6861dcf122a3.png
