### ISSUE TITLE
TTKeyboard

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10308]
**App Name:** TTKeyboard
**Bundle ID:** com.myopenware.ttKeyboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=919884616">919884616</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ttkeyboard/id919884616?uo=4">https://apps.apple.com/us/app/ttkeyboard/id919884616?uo=4</a>
**App Version:** 3.6
**Seller:** Hein thet Khin zaw
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hein-thet-khin-zaw/id541922144?uo=4">© Hein thet Khin zaw</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/19/a7/04/19a7049c-e2d9-c991-f816-202a1baea4c1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838131-5df5d480-bc78-11e9-92cd-616f9cb95b59.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838131-5df5d480-bc78-11e9-92cd-616f9cb95b59.png)
https://user-images.githubusercontent.com/2068130/62838131-5df5d480-bc78-11e9-92cd-616f9cb95b59.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838134-70700e00-bc78-11e9-929e-7f60ffef784b.png
