### ISSUE TITLE
WebComics - Daily Manga

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10301]
**App Name:** WebComics - Daily Manga
**Bundle ID:** com.manga.webcomics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1337550955">1337550955</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/webcomics-daily-manga/id1337550955?uo=4">https://apps.apple.com/us/app/webcomics-daily-manga/id1337550955?uo=4</a>
**App Version:** 1.5.84
**Seller:** WEBCOMICS HOLDINGS HK LIMITED
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/webcomics-holdings/id1437232249?uo=4">© WEBCOMICS HOLDINGS</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/d1/eb/f2/d1ebf2df-481c-d3e4-1e93-2501aee06af8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63460319-96ef2f80-c456-11e9-81f8-bb03fdda3e9d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63460319-96ef2f80-c456-11e9-81f8-bb03fdda3e9d.png)
https://user-images.githubusercontent.com/20930745/63460319-96ef2f80-c456-11e9-81f8-bb03fdda3e9d.png

Source:
https://user-images.githubusercontent.com/20930745/63460322-98205c80-c456-11e9-9272-cecd7311332b.png
