### ISSUE TITLE
MPT 4 U

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10306]
**App Name:** MPT 4 U
**Bundle ID:** com.mptvasmm.app.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1117941776">1117941776</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mpt-4-u/id1117941776?uo=4">https://apps.apple.com/us/app/mpt-4-u/id1117941776?uo=4</a>
**App Version:** 1.3.13
**Seller:** Myanma Posts and Telecommunications
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mpt/id1117941775?uo=4">© MPT</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/1c/e0/14/1ce01439-df9d-0b5e-e8ac-683909e7db32/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63459882-ade15200-c455-11e9-9003-b32bb7e8afa1.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63459882-ade15200-c455-11e9-9003-b32bb7e8afa1.png)
https://user-images.githubusercontent.com/20930745/63459882-ade15200-c455-11e9-9003-b32bb7e8afa1.png

Source:
https://user-images.githubusercontent.com/20930745/63459885-af127f00-c455-11e9-917d-f17746236eea.png
