### ISSUE TITLE
JCPenney - Clothes Shopping

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10318]
**App Name:** JCPenney - Clothes Shopping
**Bundle ID:** com.jcpenney.jcpenney
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=925338276">925338276</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/jcpenney-clothes-shopping/id925338276?uo=4">https://apps.apple.com/us/app/jcpenney-clothes-shopping/id925338276?uo=4</a>
**App Version:** 9.7.1
**Seller:** JCPenney, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/jcp/id497798902?uo=4">© jcp</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/25/49/a1/2549a122-0746-ffee-8ec6-15e1d469d657/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63215581-eff25700-c128-11e9-9c91-be59f457f50c.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63215581-eff25700-c128-11e9-9c91-be59f457f50c.png)
https://user-images.githubusercontent.com/2068130/63215581-eff25700-c128-11e9-9c91-be59f457f50c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/63215586-fed90980-c128-11e9-9127-8c1369e7f34d.png
