### ISSUE TITLE
Saildrone Forecast - Weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10313]
**App Name:** Saildrone Forecast - Weather
**Bundle ID:** com.saildrone.forecast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1357833526">1357833526</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/saildrone-forecast-weather/id1357833526?uo=4">https://apps.apple.com/us/app/saildrone-forecast-weather/id1357833526?uo=4</a>
**App Version:** 1.4.8
**Seller:** Saildrone, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/saildrone-inc/id978797355?uo=4">© Saildrone, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/ff/66/9e/ff669ec4-929c-1048-32fa-5214d2648cc9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63271344-3a471580-c29a-11e9-9d00-4d8beb4cbf9e.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63271344-3a471580-c29a-11e9-9d00-4d8beb4cbf9e.png)
https://user-images.githubusercontent.com/20930745/63271344-3a471580-c29a-11e9-9d00-4d8beb4cbf9e.png

Source:
https://user-images.githubusercontent.com/20930745/63271350-3b784280-c29a-11e9-974c-649dadb07da1.png
