### ISSUE TITLE
Sephora: Makeup and Skincare

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10319]
**App Name:** Sephora: Makeup and Skincare
**Bundle ID:** com.sephora.sephoramobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393328150">393328150</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sephora-makeup-and-skincare/id393328150?uo=4">https://apps.apple.com/us/app/sephora-makeup-and-skincare/id393328150?uo=4</a>
**App Version:** 19.6
**Seller:** Sephora USA, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sephora-usa-inc/id370613550?uo=4">© Sephora USA, Inc</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/a1/90/43/a19043ed-c6c9-928c-afa3-b599da9fa279/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63215550-8a9e6600-c128-11e9-8766-39b3edc2ca72.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63215550-8a9e6600-c128-11e9-8766-39b3edc2ca72.png)
https://user-images.githubusercontent.com/2068130/63215550-8a9e6600-c128-11e9-8766-39b3edc2ca72.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/63215553-9853eb80-c128-11e9-9142-8081fba6c0b7.png
