### ISSUE TITLE
BeeCanvas: The Whiteboard

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10314]
**App Name:** BeeCanvas: The Whiteboard
**Bundle ID:** com.jokerpack.beecanvas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943284575">943284575</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/beecanvas-the-whiteboard/id943284575?uo=4">https://apps.apple.com/us/app/beecanvas-the-whiteboard/id943284575?uo=4</a>
**App Version:** 3.6
**Seller:** Osiris Systems Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/osiris-systems-inc/id943284574?uo=4">© Osiris Systems Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/c1/98/c9/c198c91a-0fa4-19ea-d84c-5cb85af48336/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838052-4407c200-bc77-11e9-94a7-c29c2ae29374.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838052-4407c200-bc77-11e9-94a7-c29c2ae29374.png)
https://user-images.githubusercontent.com/2068130/62838052-4407c200-bc77-11e9-94a7-c29c2ae29374.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838056-54b83800-bc77-11e9-8083-ca14e461a748.png
