### ISSUE TITLE
Family Dollar

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10317]
**App Name:** Family Dollar
**Bundle ID:** com.familydollar.consumer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1196434600">1196434600</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/family-dollar/id1196434600?uo=4">https://apps.apple.com/us/app/family-dollar/id1196434600?uo=4</a>
**App Version:** 3.3.0
**Seller:** Family Dollar Stores, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/family-dollar/id1196434599?uo=4">© Family Dollar</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/6f/16/1b/6f161bfb-e026-2020-2afd-22425b1b2c74/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63224796-98f08e80-c1c9-11e9-9108-d30a7a210b72.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63224796-98f08e80-c1c9-11e9-9108-d30a7a210b72.png)
https://user-images.githubusercontent.com/2068130/63224796-98f08e80-c1c9-11e9-9108-d30a7a210b72.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/63224800-a73eaa80-c1c9-11e9-8eed-99fca6bc5cc9.png
