### ISSUE TITLE
NoteLedge Ultimate

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10312]
**App Name:** NoteLedge Ultimate
**Bundle ID:** com.kdanmobile.universal.noteledge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914548793">914548793</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/noteledge-ultimate/id914548793?uo=4">https://apps.apple.com/us/app/noteledge-ultimate/id914548793?uo=4</a>
**App Version:** 3.3
**Seller:** Kdan Mobile Software LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kdan-mobile-software-ltd/id318936474?uo=4">© Kdan Mobile Software LTD</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/94/06/e1/9406e1c2-d804-41b8-ea85-d04d4d6ef97d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64013800-ef8e8e80-cb20-11e9-9c30-bdfdcf769ea1.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64013800-ef8e8e80-cb20-11e9-9c30-bdfdcf769ea1.png)
https://user-images.githubusercontent.com/2068130/64013800-ef8e8e80-cb20-11e9-9c30-bdfdcf769ea1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64013837-ff0dd780-cb20-11e9-9384-71035f644499.png
