### ISSUE TITLE
Microsoft Whiteboard

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10315]
**App Name:** Microsoft Whiteboard
**Bundle ID:** com.microsoft.whiteboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1352499399">1352499399</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/microsoft-whiteboard/id1352499399?uo=4">https://apps.apple.com/us/app/microsoft-whiteboard/id1352499399?uo=4</a>
**App Version:** 20.10224.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/microsoft-corporation/id298856275?uo=4">© Microsoft Corporation</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/01/66/28/016628a6-ca17-2ee4-b31f-2662979df043/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77443291-445e6300-6deb-11ea-8116-0ea2808c299e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62837846-90053780-bc74-11e9-94e0-6ea55d3c186e.png)
https://user-images.githubusercontent.com/2068130/62837846-90053780-bc74-11e9-94e0-6ea55d3c186e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62837851-a4493480-bc74-11e9-9985-36f073725d50.png

**Comment by l8er4now** [comment]
Needs an update

**App Name:** Microsoft Whiteboard
**Bundle ID:** com.microsoft.whiteboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1352499399">1352499399</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/microsoft-whiteboard/id1352499399?uo=4">https://apps.apple.com/us/app/microsoft-whiteboard/id1352499399?uo=4</a>
**App Version:** 20.10224.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/microsoft-corporation/id298856275?uo=4">© Microsoft Corporation</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/01/66/28/016628a6-ca17-2ee4-b31f-2662979df043/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77443291-445e6300-6deb-11ea-8116-0ea2808c299e.png)
https://user-images.githubusercontent.com/2068130/77443291-445e6300-6deb-11ea-8116-0ea2808c299e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/77443389-52ac7f00-6deb-11ea-9342-6d93491dee97.png
