### ISSUE TITLE
Video Crop – Trim & Cut Videos

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10310]
**App Name:** Video Crop – Trim & Cut Videos
**Bundle ID:** com.sunfun.cropvid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1309610014">1309610014</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/video-crop-trim-cut-videos/id1309610014?uo=4">https://apps.apple.com/us/app/video-crop-trim-cut-videos/id1309610014?uo=4</a>
**App Version:** 2.4
**Seller:** RAJIB SEN
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/rajib-sen/id1228055475?uo=4">© RAJIB SEN</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/11/4c/e0/114ce0f8-cc8f-a1a9-aa6a-ec595f1514e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63267118-a83b0f00-c291-11e9-81d8-c203b2535edf.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63267118-a83b0f00-c291-11e9-81d8-c203b2535edf.png)
(https://user-images.githubusercontent.com/20930745/63267118-a83b0f00-c291-11e9-81d8-c203b2535edf.png

Source:
https://user-images.githubusercontent.com/20930745/63267123-a96c3c00-c291-11e9-95df-3d833ca2707c.png
