### ISSUE TITLE
Video Cut - Video Editor & Trim Video

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10311]
**App Name:** Video Cut - Video Editor & Trim Video
**Bundle ID:** com.zwj.videocut
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1153154310">1153154310</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/video-cut-video-editor-trim-video/id1153154310?uo=4">https://apps.apple.com/us/app/video-cut-video-editor-trim-video/id1153154310?uo=4</a>
**App Version:** 1.3
**Seller:** Zheng Weijie
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/zheng-weijie/id1150649091?uo=4">© Zheng Weijie</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple71/v4/ec/bc/7a/ecbc7ade-d586-4596-1543-1449b489cb64/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63267462-5fd02100-c292-11e9-9907-4cdd01ed1705.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63267462-5fd02100-c292-11e9-9907-4cdd01ed1705.png)
https://user-images.githubusercontent.com/20930745/63267462-5fd02100-c292-11e9-9907-4cdd01ed1705.png

Source:
https://user-images.githubusercontent.com/20930745/63267464-6068b780-c292-11e9-9837-1b074f353cae.png
