### ISSUE TITLE
Michaels Stores

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10321]
**App Name:** Michaels Stores
**Bundle ID:** com.michaels.michaelsstores
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445458809">445458809</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/michaels-stores/id445458809?uo=4">https://apps.apple.com/us/app/michaels-stores/id445458809?uo=4</a>
**App Version:** 9.0
**Seller:** Michaels Stores, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/michaels-stores-inc/id445458812?uo=4">© Michaels Stores, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/e1/9d/e6/e19de649-f9e5-188c-5e50-5fb29bd35cf9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63215422-680b4d80-c126-11e9-8748-1e36b5ed39c8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63215422-680b4d80-c126-11e9-8748-1e36b5ed39c8.png)
https://user-images.githubusercontent.com/2068130/63215422-680b4d80-c126-11e9-8748-1e36b5ed39c8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/63215425-76596980-c126-11e9-943c-40816a4969ac.png
