### ISSUE TITLE
Miximum

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10323]
**App Name:** Miximum
**Bundle ID:** com.michaelclay.Miximum
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1456153507">1456153507</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/miximum/id1456153507?uo=4">https://apps.apple.com/us/app/miximum/id1456153507?uo=4</a>
**App Version:** 1.0.5
**Seller:** Mike Clay
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mike-clay/id924491990?uo=4">© Mike Clay</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/df/3e/95/df3e9527-7b53-9ac7-8e6e-19ce45bb1b2b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63215328-3e9df200-c125-11e9-9070-249ee456b8d8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63215328-3e9df200-c125-11e9-9070-249ee456b8d8.png)
https://user-images.githubusercontent.com/2068130/63215328-3e9df200-c125-11e9-9070-249ee456b8d8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/63215338-4e1d3b00-c125-11e9-9370-534753d849d0.png
