### ISSUE TITLE
Best Buy Assured Living

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10320]
**App Name:** Best Buy Assured Living
**Bundle ID:** com.bestbuy.BestBuyAlarm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1252849641">1252849641</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/best-buy-assured-living/id1252849641?uo=4">https://apps.apple.com/us/app/best-buy-assured-living/id1252849641?uo=4</a>
**App Version:** 4.7.4
**Seller:** Best Buy Co., Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/best-buy-co-inc/id314855258?uo=4">© Best Buy Co., Inc.</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/0d/51/d5/0d51d50d-5522-5827-cc1d-46263e15756c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64008430-64a89680-cb16-11e9-8635-414859bfccd2.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64008430-64a89680-cb16-11e9-8635-414859bfccd2.png)
https://user-images.githubusercontent.com/2068130/64008430-64a89680-cb16-11e9-8635-414859bfccd2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64008458-7427df80-cb16-11e9-92c9-9bdb09306f3d.png
