### ISSUE TITLE
PopBase

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10328]
**App Name:** PopBase
**Bundle ID:** com.BinaryBubbles.PopBase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1430910123">1430910123</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/popbase/id1430910123?uo=4">https://apps.apple.com/us/app/popbase/id1430910123?uo=4</a>
**App Version:** 1.0
**Seller:** Binary Bubbles, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/binary-bubbles-inc/id1194749190?uo=4">© Binary Bubbles, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/dd/25/4a/dd254a61-4969-9d6b-1930-a25906d7e1c1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63216711-c4c43380-c139-11e9-8921-1b91496acf9a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63216711-c4c43380-c139-11e9-8921-1b91496acf9a.png)
https://user-images.githubusercontent.com/2068130/63216711-c4c43380-c139-11e9-8921-1b91496acf9a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/63216714-d60d4000-c139-11e9-930a-8dc051898a2a.png
