### ISSUE TITLE
Notes Writer -Take Good Notes!

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10324]
**App Name:** Notes Writer -Take Good Notes!
**Bundle ID:** com.kairoos.noteswriterfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1423643723">1423643723</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/notes-writer-take-good-notes/id1423643723?uo=4">https://apps.apple.com/us/app/notes-writer-take-good-notes/id1423643723?uo=4</a>
**App Version:** 11.0.3
**Seller:** Kairoos Solutions S.L.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kairoos-solutions-sl/id978066434?uo=4">© Kairoos Solutions SL</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/f8/38/a7/f838a773-600a-00e5-b5d0-d2a3bfd27974/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64008155-d3392480-cb15-11e9-8bee-9c44890b9689.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64008155-d3392480-cb15-11e9-8bee-9c44890b9689.png)
https://user-images.githubusercontent.com/2068130/64008155-d3392480-cb15-11e9-8bee-9c44890b9689.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64008188-e2b86d80-cb15-11e9-9097-375d18bbbcbb.png
