### ISSUE TITLE
CycleStreets: UK cycle journey planner and photomap

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1032]
**App Name:** CycleStreets: UK cycle journey planner and photomap
**Bundle ID:** net.cyclestreets.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391984737">391984737</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cyclestreets-uk-cycle-journey/id391984737?mt=8&uo=4">https://itunes.apple.com/us/app/cyclestreets-uk-cycle-journey/id391984737?mt=8&uo=4</a>
**App Version:** 3.2.4
**Seller:** CycleStreets Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cyclestreets-ltd/id391984740?uo=4">© CycleStreets Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/54/01/29/540129c2-3ce1-69d4-7326-0ccd2365bdb1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19918999/37aedbf8-a0d0-11e6-9a6d-c0d1ab075488.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19918999/37aedbf8-a0d0-11e6-9a6d-c0d1ab075488.png)
https://cloud.githubusercontent.com/assets/20930745/19918999/37aedbf8-a0d0-11e6-9a6d-c0d1ab075488.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19919011/53aaa9cc-a0d0-11e6-96b9-c66437944e3c.png
