### ISSUE TITLE
Standard Notes

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10326]
**App Name:** Standard Notes
**Bundle ID:** com.standardnotes.standardnotes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1285392450">1285392450</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/standard-notes/id1285392450?uo=4">https://apps.apple.com/us/app/standard-notes/id1285392450?uo=4</a>
**App Version:** 3.0.10
**Seller:** progenius inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/progenius/id586976285?uo=4">© progenius</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/c4/d3/e7/c4d3e7e7-48d9-ba42-8788-1c0fe9e9173b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63213897-f75a3600-c111-11e9-8ae3-7149d60af605.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63213897-f75a3600-c111-11e9-8ae3-7149d60af605.png)
(https://user-images.githubusercontent.com/20930745/63213897-f75a3600-c111-11e9-8ae3-7149d60af605.png

Source:
https://user-images.githubusercontent.com/20930745/63213898-f7f2cc80-c111-11e9-86cc-9e46c66a8f42.png
