### ISSUE TITLE
News Explorer

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10325]
**App Name:** News Explorer
**Bundle ID:** betamagic.News-Explorer.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032668306">1032668306</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/news-explorer/id1032668306?uo=4">https://apps.apple.com/us/app/news-explorer/id1032668306?uo=4</a>
**App Version:** 1.9.5
**Seller:** Ron Elemans
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ron-elemans/id802165890?uo=4">© Ron Elemans</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/20/23/dd/2023ddb2-55a4-2583-0936-4534f87b0af0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63217073-c09b1480-c13f-11e9-9b18-6fa4caeeafbb.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63217073-c09b1480-c13f-11e9-9b18-6fa4caeeafbb.png)
https://user-images.githubusercontent.com/2068130/63217073-c09b1480-c13f-11e9-9b18-6fa4caeeafbb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/63217077-cf81c700-c13f-11e9-8179-c9b92e03388f.png
