### ISSUE TITLE
MovieList: Track Your Movies

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10327]
**App Name:** MovieList: Track Your Movies
**Bundle ID:** movies.movielist.movielist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1422653344">1422653344</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/movielist-track-your-movies/id1422653344?uo=4">https://apps.apple.com/us/app/movielist-track-your-movies/id1422653344?uo=4</a>
**App Version:** 1.0.3
**Seller:** Nathaniel Adams
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nathaniel-adams/id1399706006?uo=4">© Nathaniel Adams</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/78/57/c9/7857c9f4-20d9-38ed-bd60-aa23063f8632/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63213828-3cca3380-c111-11e9-88d2-2155853d0e5c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63213828-3cca3380-c111-11e9-88d2-2155853d0e5c.png)
https://user-images.githubusercontent.com/20930745/63213828-3cca3380-c111-11e9-88d2-2155853d0e5c.png

Source:
https://user-images.githubusercontent.com/20930745/63213830-3dfb6080-c111-11e9-9865-5865877cedea.png
