### ISSUE TITLE
Peaker: News AI

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10338]
**App Name:** Peaker: News AI
**Bundle ID:** com.newspeak.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1445006384">1445006384</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/peaker-news-ai/id1445006384?uo=4">https://apps.apple.com/us/app/peaker-news-ai/id1445006384?uo=4</a>
**App Version:** 2.1.0
**Seller:** Burak Tas
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/burak-tas/id1444996016?uo=4">© Burak Tas</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/5d/9f/4d/5d9f4d26-1412-c839-9b02-a47782d58615/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63568351-33a7ef00-c575-11e9-9f57-4aadaa4c2dba.png)

**Comment by 2Qt2beStr8** [comment]
it's not possible to upload the files
