### ISSUE TITLE
Fun Race 3D

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10334]
**App Name:** Fun Race 3D
**Bundle ID:** com.slippy.linerusher
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1462556579">1462556579</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fun-race-3d/id1462556579?uo=4">https://apps.apple.com/us/app/fun-race-3d/id1462556579?uo=4</a>
**App Version:** 1.1.9
**Seller:** Good Job Games Bilisim Yazilim ve Pazarlama AS
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/good-job-games/id1191495496?uo=4">© Good Job Games</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/d6/84/26/d68426ca-db32-7780-ea98-7c472787c708/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64919954-cc670e80-d7b1-11e9-82b7-1be4aaacbbbd.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64919954-cc670e80-d7b1-11e9-82b7-1be4aaacbbbd.png)
https://user-images.githubusercontent.com/2068130/64919954-cc670e80-d7b1-11e9-82b7-1be4aaacbbbd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64919956-dab52a80-d7b1-11e9-83ee-18c54f16a5f0.png
