### ISSUE TITLE
StickyStudy Chinese

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10335]
**App Name:** StickyStudy Chinese
**Bundle ID:** com.justinnightingale.stickystudychinese
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=451375935">451375935</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stickystudy-chinese/id451375935?uo=4">https://apps.apple.com/us/app/stickystudy-chinese/id451375935?uo=4</a>
**App Version:** 3.10
**Seller:** Justin Nightingale
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/stickystudy/id384039719?uo=4">© Stickystudy</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/cf/de/63/cfde6371-c5f2-dcc3-4b78-5773afe5365b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63269057-cefb4480-c295-11e9-8f34-775ea2a5335c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63269057-cefb4480-c295-11e9-8f34-775ea2a5335c.png)
https://user-images.githubusercontent.com/20930745/63269057-cefb4480-c295-11e9-8f34-775ea2a5335c.png

Source:
https://user-images.githubusercontent.com/20930745/63269059-d02c7180-c295-11e9-87be-edff0f876bd0.png
