### ISSUE TITLE
Rummy HD - The Card Game

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10332]
**App Name:** Rummy HD - The Card Game
**Bundle ID:** intentsoftware.rummylite-ipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547556877">547556877</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/rummy-hd-the-card-game/id547556877?uo=4">https://apps.apple.com/us/app/rummy-hd-the-card-game/id547556877?uo=4</a>
**App Version:** 3.1.33
**Seller:** LITE Games GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lite-games-gmbh/id943875563?uo=4">© LITE Games GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/71/35/63/71356339-72a1-13f8-1149-18e5563f530a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64006403-8f90eb80-cb12-11e9-8c6f-28269bf6f568.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64006403-8f90eb80-cb12-11e9-8c6f-28269bf6f568.png)
https://user-images.githubusercontent.com/2068130/64006403-8f90eb80-cb12-11e9-8c6f-28269bf6f568.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64006434-9f103480-cb12-11e9-9152-19cfeb12026d.png
