### ISSUE TITLE
Feelfit

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10330]
**App Name:** Feelfit
**Bundle ID:** com.qingniu.feelfit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1216588019">1216588019</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/feelfit/id1216588019?uo=4">https://apps.apple.com/us/app/feelfit/id1216588019?uo=4</a>
**App Version:** 2.2.6
**Seller:** Shenzhen QingNiu Software Co. Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shenzhen-qingniu-software-co-ltd/id1064285024?uo=4">© Shenzhen QingNiu Software Co. Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/c1/88/0a/c1880a3e-f8c8-efe2-8b3a-5cd578ea4c8d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63267942-6612cd00-c293-11e9-8f82-753c094d49c6.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63267942-6612cd00-c293-11e9-8f82-753c094d49c6.png)
https://user-images.githubusercontent.com/20930745/63267942-6612cd00-c293-11e9-8f82-753c094d49c6.png

Source:
https://user-images.githubusercontent.com/20930745/63267944-6743fa00-c293-11e9-829e-ddb83c8ee642.png
