### ISSUE TITLE
iPatente

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#10344]
**App Name:** iPatente
**Bundle ID:** gov.mit.ipatente
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417705371">417705371</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ipatente/id417705371?uo=4">https://apps.apple.com/us/app/ipatente/id417705371?uo=4</a>
**App Version:** 4.2.1
**Seller:** Ministero delle Infrastrutture e dei Trasporti
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ministero-delle-infrastrutture-e-dei-trasporti/id417705374?uo=4">© Ministero delle Infrastrutture e dei Trasporti</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/1c/35/b8/1c35b8e7-4fa9-3c78-9289-a9f419032522/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63868409-c05c0e00-c9b6-11e9-9231-668e90c7aa24.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63868409-c05c0e00-c9b6-11e9-9231-668e90c7aa24.png)
https://user-images.githubusercontent.com/20930745/63868409-c05c0e00-c9b6-11e9-9231-668e90c7aa24.png

Source:
https://user-images.githubusercontent.com/20930745/63868413-c18d3b00-c9b6-11e9-8905-26cb59696ea5.png
