### ISSUE TITLE
MyWind (App ufficiale Wind)

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#10347]
**App Name:** MyWind (App ufficiale Wind)
**Bundle ID:** it.wind.mywind
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492519547">492519547</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mywind-app-ufficiale-wind/id492519547?uo=4">https://apps.apple.com/us/app/mywind-app-ufficiale-wind/id492519547?uo=4</a>
**App Version:** 5.4.0
**Seller:** Wind Tre S.p.A.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wind-tre-s-p-a/id330773038?uo=4">© Wind Tre S.p.A.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/e3/98/ea/e398ea4a-61a9-d5b0-5d5e-4c3893c72b57/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63871791-d79dfa00-c9bc-11e9-876d-427ccd5e1ead.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63871791-d79dfa00-c9bc-11e9-876d-427ccd5e1ead.png)
https://user-images.githubusercontent.com/20930745/63871791-d79dfa00-c9bc-11e9-876d-427ccd5e1ead.png

Source:
https://user-images.githubusercontent.com/20930745/63871793-d967bd80-c9bc-11e9-97a0-3d72d3295372.png
