### ISSUE TITLE
Strides: Habit Tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10340]
**App Name:** Strides: Habit Tracker
**Bundle ID:** com.puresignal.strides
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=672401817">672401817</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/strides-habit-tracker/id672401817?uo=4">https://apps.apple.com/us/app/strides-habit-tracker/id672401817?uo=4</a>
**App Version:** 8.4
**Seller:** Goals LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/goals-llc/id507975203?uo=4">© Goals LLC</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/74/00/66/740066f5-7831-3bc4-3ee9-b7e596fc38cc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63568519-c2b50700-c575-11e9-93c9-6d8c79dd7970.png)

**Comment by 2Qt2beStr8** [comment]
it's not possible to upload the files
