### ISSUE TITLE
HYPE - Carta conto e app

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#10343]
**App Name:** HYPE - Carta conto e app
**Bundle ID:** com.hype.it
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943405905">943405905</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hype-carta-conto-e-app/id943405905?uo=4">https://apps.apple.com/us/app/hype-carta-conto-e-app/id943405905?uo=4</a>
**App Version:** 3.0.8
**Seller:** Banca Sella Holding
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/banca-sella-s-p-a/id296150386?uo=4">© Banca Sella S.p.A.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/35/d9/7c/35d97ce3-af18-cd78-2212-2b4065c4a6e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63867091-8e49ac80-c9b4-11e9-8050-a79c6502efba.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63867091-8e49ac80-c9b4-11e9-8050-a79c6502efba.png)
https://user-images.githubusercontent.com/20930745/63867091-8e49ac80-c9b4-11e9-8050-a79c6502efba.png

Source:
https://user-images.githubusercontent.com/20930745/63867095-8f7ad980-c9b4-11e9-8944-41c58c31b28c.png
