### ISSUE TITLE
Stella for Mastodon & Twitter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10341]
**App Name:** Stella for Mastodon & Twitter
**Bundle ID:** com.owletlab.Project-S
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=921372048">921372048</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stella-for-mastodon-twitter/id921372048?uo=4">https://apps.apple.com/us/app/stella-for-mastodon-twitter/id921372048?uo=4</a>
**App Version:** 1.0.15
**Seller:** OwletLabs LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/owletlabs-llc/id921372047?uo=4">© OwletLabs LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/da/68/bb/da68bb7f-c9b2-4d02-6446-92f0898c3c29/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63569126-538ce200-c578-11e9-8360-f85f0e9f313f.png)

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8 
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63569126-538ce200-c578-11e9-8360-f85f0e9f313f.png)
https://user-images.githubusercontent.com/2068130/63569126-538ce200-c578-11e9-8360-f85f0e9f313f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/63569145-6ef7ed00-c578-11e9-8a66-48976e9d1d9d.png
