### ISSUE TITLE
AutoWake. Smart Sleep Alarm

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10359]
**App Name:** AutoWake. Smart Sleep Alarm
**Bundle ID:** com.tantsissa.Haptick
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1279650551">1279650551</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/autowake-smart-sleep-alarm/id1279650551?uo=4">https://apps.apple.com/us/app/autowake-smart-sleep-alarm/id1279650551?uo=4</a>
**App Version:** 3.0
**Seller:** TANTSISSA HOLDINGS PTY LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tantsissa/id861650887?uo=4">© Tantsissa</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/16/9a/ba/169abac3-7833-4c06-196f-0caf73d94368/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64125986-49ef4f80-cdac-11e9-9d44-2e99ae4eaf0f.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64125986-49ef4f80-cdac-11e9-9d44-2e99ae4eaf0f.png)
https://user-images.githubusercontent.com/20930745/64125986-49ef4f80-cdac-11e9-9d44-2e99ae4eaf0f.png

Source:
https://user-images.githubusercontent.com/20930745/64125992-507dc700-cdac-11e9-8f45-212a0564c3ed.png
