### ISSUE TITLE
Logitech Squeezebox Controller

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1035]
**App Name:** Logitech Squeezebox Controller
**Bundle ID:** com.logitech.eastman
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431302899">431302899</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/logitech-squeezebox-controller/id431302899?mt=8&uo=4">https://itunes.apple.com/us/app/logitech-squeezebox-controller/id431302899?mt=8&uo=4</a>
**App Version:** 1.1.5
**Seller:** Logitech Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/logitech-inc/id332300071?mt=8&uo=4">© Logitech Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/25/e1/42/25e14201-ec51-e0f8-4cf1-22f4eb24ebde/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32985243-b76627ee-ccb6-11e7-8793-07429a159042.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32985243-b76627ee-ccb6-11e7-8793-07429a159042.png)
https://user-images.githubusercontent.com/2068130/32985243-b76627ee-ccb6-11e7-8793-07429a159042.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32985246-c6d07b08-ccb6-11e7-8b49-9949298bd8da.png
