### ISSUE TITLE
BeWeather 3

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10354]
**App Name:** BeWeather 3
**Bundle ID:** com.bellshareinc.BeWeather3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1454636337">1454636337</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/beweather-3/id1454636337?uo=4">https://apps.apple.com/us/app/beweather-3/id1454636337?uo=4</a>
**App Version:** 3.0.37
**Seller:** Bellshare Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bellshare-inc/id761415158?uo=4">© Bellshare Inc</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/6b/5c/04/6b5c042d-1d63-5eeb-947d-83c17091f08a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64487028-76381f80-d235-11e9-99f1-3fa8e736a412.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64487028-76381f80-d235-11e9-99f1-3fa8e736a412.png)
https://user-images.githubusercontent.com/20930745/64487028-76381f80-d235-11e9-99f1-3fa8e736a412.png

Source:
https://user-images.githubusercontent.com/20930745/64487029-76d0b600-d235-11e9-8f7a-e8ef6ce459f0.png
