### ISSUE TITLE
BAND - App for all groups

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10358]
**App Name:** BAND - App for all groups
**Bundle ID:** com.nhncorp.m2app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542613198">542613198</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/band-app-for-all-groups/id542613198?uo=4">https://apps.apple.com/us/app/band-app-for-all-groups/id542613198?uo=4</a>
**App Version:** 7.5.2
**Seller:** NAVER Corp.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/naver-corp/id311867731?uo=4">© NAVER Corp.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/17/7d/f5/177df516-6cb5-bd99-7631-d6994cdcc7ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64121529-5a4cfd80-cd9f-11e9-92e6-544848771df5.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64121529-5a4cfd80-cd9f-11e9-92e6-544848771df5.png)
https://user-images.githubusercontent.com/20930745/64121529-5a4cfd80-cd9f-11e9-92e6-544848771df5.png

Source:
https://user-images.githubusercontent.com/20930745/64121532-5b7e2a80-cd9f-11e9-8c0e-e75218e563a3.png
