### ISSUE TITLE
Tour - Trip Planning Made Easy

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10355]
**App Name:** Tour - Trip Planning Made Easy
**Bundle ID:** digital.monos.tour
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1447463787">1447463787</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tour-trip-planning-made-easy/id1447463787?uo=4">https://apps.apple.com/us/app/tour-trip-planning-made-easy/id1447463787?uo=4</a>
**App Version:** 1.8.1
**Seller:** Monos Digital, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/monos-digital/id1447463786?uo=4">© Monos Digital</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/4a/f1/84/4af18428-132b-248e-e009-3486a7aa37f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64121192-65ebf480-cd9e-11e9-8939-b258025db1d5.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64121192-65ebf480-cd9e-11e9-8939-b258025db1d5.png)
(https://user-images.githubusercontent.com/20930745/64121192-65ebf480-cd9e-11e9-8939-b258025db1d5.png

Source:
https://user-images.githubusercontent.com/20930745/64121194-671d2180-cd9e-11e9-84e4-3cee526f77e5.png
