### ISSUE TITLE
Skyfire Browser for Web Video

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10353]
**App Name:** Skyfire Browser for Web Video
**Bundle ID:** com.gplexdb.fire.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1387347094">1387347094</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/skyfire-browser-for-web-video/id1387347094?uo=4">https://apps.apple.com/us/app/skyfire-browser-for-web-video/id1387347094?uo=4</a>
**App Version:** 1.7
**Seller:** Ameen Mody
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ameen-mody/id1231983233?uo=4">© Ameen Mody</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/42/fb/2a/42fb2ab3-444c-a708-591a-a3072bff1ce3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64120890-b44cc380-cd9d-11e9-9f93-a19a73558205.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64120890-b44cc380-cd9d-11e9-9f93-a19a73558205.png)
https://user-images.githubusercontent.com/20930745/64120890-b44cc380-cd9d-11e9-9f93-a19a73558205.png

Source:
https://user-images.githubusercontent.com/20930745/64120892-b4e55a00-cd9d-11e9-885b-dc3aa3e43c4c.png
