### ISSUE TITLE
Fantasy Football Cheat Sheets

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10356]
**App Name:** Fantasy Football Cheat Sheets
**Bundle ID:** com.fantasypros.Cheat-Sheets
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1472349159">1472349159</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fantasy-football-cheat-sheets/id1472349159?uo=4">https://apps.apple.com/us/app/fantasy-football-cheat-sheets/id1472349159?uo=4</a>
**App Version:** 1.1.4
**Seller:** Marzen Media LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/marzen-media-llc/id892964104?uo=4">© Marzen Media LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/99/f6/ff/99f6ffe8-79be-ac12-2ff5-71cd05af0e90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64584596-abf41a00-d395-11e9-815b-eaa4eb991483.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64584596-abf41a00-d395-11e9-815b-eaa4eb991483.png)
https://user-images.githubusercontent.com/2068130/64584596-abf41a00-d395-11e9-815b-eaa4eb991483.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64584608-bb736300-d395-11e9-9f71-ffb1fc44f7a5.png
