### ISSUE TITLE
Birdie for Twitter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10352]
**App Name:** Birdie for Twitter
**Bundle ID:** app.birdie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1438965061">1438965061</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/birdie-for-twitter/id1438965061?uo=4">https://apps.apple.com/us/app/birdie-for-twitter/id1438965061?uo=4</a>
**App Version:** 1.8
**Seller:** Mailr Tech LLP
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mailr-tech-llp/id1137358501?uo=4">© Mailr Tech LLP</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/e4/84/e2/e484e2fe-cdeb-6a21-853a-708d57c754ed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64120666-1f49ca80-cd9d-11e9-85da-2ba0ed555b77.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64120666-1f49ca80-cd9d-11e9-85da-2ba0ed555b77.png)
https://user-images.githubusercontent.com/20930745/64120666-1f49ca80-cd9d-11e9-85da-2ba0ed555b77.png

Source:
https://user-images.githubusercontent.com/20930745/64120671-21138e00-cd9d-11e9-9d3f-a34ffb3b81b0.png
