### ISSUE TITLE
Gps Status - record your track

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#10357]
**App Name:** Gps Status - record your track
**Bundle ID:** com.54app.gpsstatus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=831152887">831152887</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gps-status-record-your-track/id831152887?uo=4">https://apps.apple.com/us/app/gps-status-record-your-track/id831152887?uo=4</a>
**App Version:** 1.5.40
**Seller:** Xiaowei Liang
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/xiaowei-liang/id601178370?uo=4">© Xiaowei Liang</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/9a/ef/1b/9aef1b03-a762-749e-281f-db4c69e689f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64670139-4753c080-d464-11e9-939a-3d6d6c3d1d1c.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64670139-4753c080-d464-11e9-939a-3d6d6c3d1d1c.png)
https://user-images.githubusercontent.com/2068130/64670139-4753c080-d464-11e9-939a-3d6d6c3d1d1c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64670147-576ba000-d464-11e9-80d5-4ddd00bf1a48.png
