### ISSUE TITLE
Sony | Headphones Connect

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10361]
**App Name:** Sony | Headphones Connect
**Bundle ID:** jp.co.sony.songpal.mdr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1168502924">1168502924</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sony-headphones-connect/id1168502924?uo=4">https://apps.apple.com/us/app/sony-headphones-connect/id1168502924?uo=4</a>
**App Version:** 5.2.0
**Seller:** Sony Home Entertainment & Sound Products Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sony-home-entertainment-sound-products-inc/id1315534741?uo=4">© Sony Home Entertainment & Sound Products Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/72/24/27/72242721-22dc-b32f-0434-22ae1deb47d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64122099-ed3a6780-cda0-11e9-8d29-4a2ace4804c3.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64122099-ed3a6780-cda0-11e9-8d29-4a2ace4804c3.png)
(https://user-images.githubusercontent.com/20930745/64122099-ed3a6780-cda0-11e9-8d29-4a2ace4804c3.png

Source:
https://user-images.githubusercontent.com/20930745/64122106-ef042b00-cda0-11e9-9ce0-3eeed12b0afd.png
