### ISSUE TITLE
TimmyMe™

### ISSUE THREAD

**Issue by Expliciate** [glasklart/hd#1036]
**App Name:** TimmyMe™
**Bundle ID:** com.timhortons.iphone.timmyme
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=483413328">483413328</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/timmyme/id483413328?mt=8&uo=4">https://itunes.apple.com/us/app/timmyme/id483413328?mt=8&uo=4</a>
**App Version:** 5.6
**Seller:** Tim Hortons
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tim-hortons/id483413331?uo=4>© Tim Hortons</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/49/a4/92/49a4921f-d284-ac1d-ee0c-639e5787b2f8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19221016/f0829f64-8e3a-11e6-8c81-2030cf230ad8.png)

**Comment by Trubbel** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19219586/641821c0-8e17-11e6-81ce-18d1df1beac6.png)
https://cloud.githubusercontent.com/assets/20930745/19219586/641821c0-8e17-11e6-81ce-18d1df1beac6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19219600/ad489b7c-8e17-11e6-8307-bd16d6609cb7.png

**Comment by LaCh0uine** [comment]
Maybe better without the lines for design

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19221016/f0829f64-8e3a-11e6-8c81-2030cf230ad8.png)
https://cloud.githubusercontent.com/assets/20930745/19221016/f0829f64-8e3a-11e6-8c81-2030cf230ad8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19221017/001c1cde-8e3b-11e6-976e-f4fe0e1ad9a9.png

**Comment by LaCh0uine** [comment]
Yeah look better thank you @DJ

**Comment by 2Qt2beStr8** [comment]
@LaCh0uine ... you are welcome :-)
