### ISSUE TITLE
Bose Connect

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10360]
**App Name:** Bose Connect
**Bundle ID:** com.bose.boseconnect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1046510029">1046510029</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bose-connect/id1046510029?uo=4">https://apps.apple.com/us/app/bose-connect/id1046510029?uo=4</a>
**App Version:** 9.0.1
**Seller:** Bose Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bose-corporation/id425230041?uo=4">© Bose Corporation</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/cd/3a/ea/cd3aea64-7a08-5b4a-1627-ea138ced5460/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64121837-31793800-cda0-11e9-9565-3f1078478b3b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64121837-31793800-cda0-11e9-9565-3f1078478b3b.png)
(https://user-images.githubusercontent.com/20930745/64121837-31793800-cda0-11e9-9565-3f1078478b3b.png

Source:
https://user-images.githubusercontent.com/20930745/64121842-3342fb80-cda0-11e9-9d29-297f3ca41ed9.png
