### ISSUE TITLE
Teachers Federal Credit Union

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10362]
**App Name:** Teachers Federal Credit Union
**Bundle ID:** com.digitalinsight.cma.01649
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1238285105">1238285105</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/teachers-federal-credit-union/id1238285105?uo=4">https://apps.apple.com/us/app/teachers-federal-credit-union/id1238285105?uo=4</a>
**App Version:** 6.0.22
**Seller:** Teachers Federal Credit Union
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/teachers-federal-credit-union/id542383251?uo=4">© Teachers Federal Credit Union</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/12/f6/f1/12f6f10c-c86a-46b1-5cc0-af8cc6ceb8ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618700/c7e56a86-eae3-11e6-85c0-2d8945ae6c26.png)

**Comment by Sly-Fi** [comment]
App is updated version from issue #8831 - use same icon :)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618700/c7e56a86-eae3-11e6-85c0-2d8945ae6c26.png)
https://cloud.githubusercontent.com/assets/20930745/22618700/c7e56a86-eae3-11e6-85c0-2d8945ae6c26.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618701/d4cfc32c-eae3-11e6-8964-7810bf73e403.png
