### ISSUE TITLE
Sp33dy - gps speedometer hud

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10368]
**App Name:** Sp33dy - gps speedometer hud
**Bundle ID:** com.Tomasz-Kusmierz.GPS-Speedometer-FREE
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1028887429">1028887429</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sp33dy-gps-speedometer-hud/id1028887429?uo=4">https://apps.apple.com/us/app/sp33dy-gps-speedometer-hud/id1028887429?uo=4</a>
**App Version:** 3.2
**Seller:** VONNLU LTD.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/vonnlu-ltd/id1028887428?uo=4">© VONNLU LTD.</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/6f/b2/eb/6fb2eb65-d918-c7d9-5fd1-b39d34c875a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64124879-83be5700-cda8-11e9-8f08-eb13f825db42.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64124879-83be5700-cda8-11e9-8f08-eb13f825db42.png)
https://user-images.githubusercontent.com/20930745/64124879-83be5700-cda8-11e9-8f08-eb13f825db42.png

Source:
https://user-images.githubusercontent.com/20930745/64124885-87ea7480-cda8-11e9-8498-b9fa7fc7d7eb.png
