### ISSUE TITLE
Julian - Quick Dates

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10363]
**App Name:** Julian - Quick Dates
**Bundle ID:** com.cpdigitaldarkroom.Julian
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1084251583">1084251583</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/julian-quick-dates/id1084251583?uo=4">https://apps.apple.com/us/app/julian-quick-dates/id1084251583?uo=4</a>
**App Version:** 3.0.1
**Seller:** Juan Carlos Perez
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/juan-carlos-perez/id931213788?uo=4">© Juan Carlos Perez</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/42/5e/6c/425e6c92-b1e3-1207-b81a-4fc798be9ddd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64123045-88344100-cda3-11e9-9a25-6cbb88790589.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64123045-88344100-cda3-11e9-9a25-6cbb88790589.png)
https://user-images.githubusercontent.com/20930745/64123045-88344100-cda3-11e9-9a25-6cbb88790589.png

Source:
https://user-images.githubusercontent.com/20930745/64123047-8a969b00-cda3-11e9-9a32-42d55f8547ce.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64123171-e6f9ba80-cda3-11e9-823e-23b2b90dfbba.png)
https://user-images.githubusercontent.com/20930745/64123171-e6f9ba80-cda3-11e9-823e-23b2b90dfbba.png

Source:
https://user-images.githubusercontent.com/20930745/64123174-e8c37e00-cda3-11e9-8e55-74806b0f9555.png
