### ISSUE TITLE
Manga Reader - Manga Viewer

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10369]
**App Name:** Manga Reader - Manga Viewer
**Bundle ID:** com.twyt.manhuawu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=647701066">647701066</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/manga-reader-manga-viewer/id647701066?uo=4">https://apps.apple.com/us/app/manga-reader-manga-viewer/id647701066?uo=4</a>
**App Version:** 1.300
**Seller:** Yubo Wang
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yubo-wang/id588344858?uo=4">© Yubo Wang</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/54/bb/6a/54bb6a60-0609-d59b-ed2a-a3cdaaf2f28b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64125138-473f2b00-cda9-11e9-8637-4af1ad59af1b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64125138-473f2b00-cda9-11e9-8637-4af1ad59af1b.png)
https://user-images.githubusercontent.com/20930745/64125138-473f2b00-cda9-11e9-8637-4af1ad59af1b.png

Source:
https://user-images.githubusercontent.com/20930745/64125140-48705800-cda9-11e9-8962-3862098378d5.png
