### ISSUE TITLE
AT&T WatchTV

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10365]
**App Name:** AT&T WatchTV
**Bundle ID:** com.att.WatchTV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1296362751">1296362751</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/at-t-watchtv/id1296362751?uo=4">https://apps.apple.com/us/app/at-t-watchtv/id1296362751?uo=4</a>
**App Version:** 3.0.1
**Seller:** AT&T Services, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/at-t-services-inc/id290854684?uo=4">© AT&T Services, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/77/a4/3a/77a43a95-33d0-f01b-bbdf-92418685cc53/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64124037-3c36cb80-cda6-11e9-90c0-8acb0ccfdf7d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64123796-984d2000-cda5-11e9-87ff-c3ff34f57ef7.png)
https://user-images.githubusercontent.com/20930745/64123796-984d2000-cda5-11e9-87ff-c3ff34f57ef7.png

Source:
https://user-images.githubusercontent.com/20930745/64123801-9be0a700-cda5-11e9-8770-4ebf97179d08.png
