### ISSUE TITLE
Zones for Training

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10366]
**App Name:** Zones for Training
**Bundle ID:** com.flaskapp.workout
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1139688415">1139688415</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/zones-for-training/id1139688415?uo=4">https://apps.apple.com/us/app/zones-for-training/id1139688415?uo=4</a>
**App Version:** 2.3.0
**Seller:** Flask LLP
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/flask-llp/id736602874?uo=4">© Flask LLP</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/70/88/ca/7088caa2-3d21-0b38-5caf-3675cef76bb5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64124292-ed3d6600-cda6-11e9-8b2e-d5e173b2d4b2.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64124292-ed3d6600-cda6-11e9-8b2e-d5e173b2d4b2.png)
https://user-images.githubusercontent.com/20930745/64124292-ed3d6600-cda6-11e9-8b2e-d5e173b2d4b2.png

Source:
https://user-images.githubusercontent.com/20930745/64124296-ef072980-cda6-11e9-986a-1b7859c1b57d.png
