### ISSUE TITLE
Chirp for Twitter

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10367]
**App Name:** Chirp for Twitter
**Bundle ID:** com.willbishop.ChirpTwitter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1397430041">1397430041</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/chirp-for-twitter/id1397430041?uo=4">https://apps.apple.com/us/app/chirp-for-twitter/id1397430041?uo=4</a>
**App Version:** 1.2.2
**Seller:** Will Bishop
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/will-bishop/id1344097184?uo=4">© Will Bishop</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/d5/8f/88/d58f88ad-d644-7ecb-5bf4-0eb0c39731aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64124660-dba88e00-cda7-11e9-83bf-3ec16d03fa74.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64124660-dba88e00-cda7-11e9-83bf-3ec16d03fa74.png)
https://user-images.githubusercontent.com/20930745/64124660-dba88e00-cda7-11e9-83bf-3ec16d03fa74.png

Source:
https://user-images.githubusercontent.com/20930745/64124676-e105d880-cda7-11e9-9621-d32b749f9448.png
