### ISSUE TITLE
GoodRx – Save On Prescriptions

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10375]
**App Name:** GoodRx – Save On Prescriptions
**Bundle ID:** com.goodrx.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=485357017">485357017</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/goodrx-save-on-prescriptions/id485357017?uo=4">https://apps.apple.com/us/app/goodrx-save-on-prescriptions/id485357017?uo=4</a>
**App Version:** 5.3.26
**Seller:** GoodRx, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/goodrx/id485357020?uo=4">© GoodRx</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/57/4b/89/574b8973-5271-47be-a342-c77457a337fb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64584841-ae0aa880-d396-11e9-99fa-49be55ea6ca8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64584841-ae0aa880-d396-11e9-99fa-49be55ea6ca8.png)
https://user-images.githubusercontent.com/2068130/64584841-ae0aa880-d396-11e9-99fa-49be55ea6ca8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64584854-bd89f180-d396-11e9-9d7e-6f3740256039.png
