### ISSUE TITLE
Whistle - Pet Tracker

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10372]
**App Name:** Whistle - Pet Tracker
**Bundle ID:** com.whistle.bob
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1182564185">1182564185</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/whistle-pet-tracker/id1182564185?uo=4">https://apps.apple.com/us/app/whistle-pet-tracker/id1182564185?uo=4</a>
**App Version:** 3.0.3
**Seller:** Whistle Labs, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/whistle/id708730943?uo=4">© Whistle</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/03/82/65/0382657d-b938-f3a1-5f78-b25e3450801f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64356780-b7e18400-d003-11e9-9135-77774a6f66b8.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64356780-b7e18400-d003-11e9-9135-77774a6f66b8.png)
https://user-images.githubusercontent.com/20930745/64356780-b7e18400-d003-11e9-9135-77774a6f66b8.png

Source:
https://user-images.githubusercontent.com/20930745/64356784-b912b100-d003-11e9-8edc-f539d4725579.png
