### ISSUE TITLE
Journey - Diary, Journal

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10371]
**App Name:** Journey - Diary, Journal
**Bundle ID:** com.journey.ios.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1300202543">1300202543</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/journey-diary-journal/id1300202543?uo=4">https://apps.apple.com/us/app/journey-diary-journal/id1300202543?uo=4</a>
**App Version:** 2.12.14
**Seller:** Two App Studio Pte. Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/two-app-studio-pte-ltd/id1130201870?uo=4">© Two App Studio Pte. Ltd.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/88/1d/09/881d095a-6ca4-c706-4fa0-54359fb6f15b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64356276-dd21c280-d002-11e9-8ab2-f23e2e24f67c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64356276-dd21c280-d002-11e9-8ab2-f23e2e24f67c.png)
https://user-images.githubusercontent.com/20930745/64356276-dd21c280-d002-11e9-8ab2-f23e2e24f67c.png

Source:
https://user-images.githubusercontent.com/20930745/64356278-de52ef80-d002-11e9-8c08-de2bd91e1a79.png
