### ISSUE TITLE
HealtheLife

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10376]
**App Name:** HealtheLife
**Bundle ID:** com.cerner.iris
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=912509516">912509516</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/healthelife/id912509516?uo=4">https://apps.apple.com/us/app/healthelife/id912509516?uo=4</a>
**App Version:** 3.6.4
**Seller:** Cerner Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cerner-corporation/id391140243?uo=4">© Cerner Corporation</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/9c/dc/48/9cdc48c5-359b-7162-243a-35bd7c57a2b5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64647693-c374e680-d419-11e9-9c8f-c49221637237.png)

**Comment by dreamnet** [comment]
??
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64647693-c374e680-d419-11e9-9c8f-c49221637237.png)
https://user-images.githubusercontent.com/2068130/64647693-c374e680-d419-11e9-9c8f-c49221637237.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64647724-d4bdf300-d419-11e9-81fe-52388398d73d.png
