### ISSUE TITLE
Embark NJ Rail

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#1037]
**App Name:** Embark NJ Rail
**Bundle ID:** us.pandav.ridenjt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446675774">446675774</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/app/id446675774">https://itunes.apple.com/app/id446675774</a>
**App Version:** 1.4.7
**Seller:** Embark, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/embark-inc./id288656963?uo=4>© Embark, Inc.</a>
**Supported Devices:** iPhone-3GS®, iPhone4®, iPhone4S®, iPhone5®, iPhone5c®, iPhone5s®, iPhone6®, iPhone6Plus®, iPodTouchFifthGen®, iPodTouchFourthGen®, iPodTouchSixthGen®, iPodTouchThirdGen®, iPad23G®, iPad2Wifi®, iPad3G®, iPadFourthGen®, iPadFourthGen4G®, iPadThirdGen®, iPadThirdGen4G®, iPadWifi®, iPadMini™, iPadMini4G™
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/18847335/1cf50fe8-842a-11e6-83da-905a8f2b783e.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18847353/35eb3a5e-842a-11e6-8914-0eb81f153b9b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18847353/35eb3a5e-842a-11e6-8914-0eb81f153b9b.png)
https://cloud.githubusercontent.com/assets/2068130/18847353/35eb3a5e-842a-11e6-8914-0eb81f153b9b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18847366/453b13e4-842a-11e6-873a-7867c1517e73.png
