### ISSUE TITLE
BundleIDXII

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10389]
**App Name:** BundleIDsXII
**Bundle ID:** de.mass1veerr0r.bundleidsxii
**Version:** 2.0.1
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/44279267/64915676-4d7ec100-d732-11e9-9dc8-edc5ba66d8a3.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64917276-b85de580-d78e-11e9-9402-c59602bf76a7.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64917276-b85de580-d78e-11e9-9402-c59602bf76a7.png)
https://user-images.githubusercontent.com/20930745/64917276-b85de580-d78e-11e9-9402-c59602bf76a7.png

Source:
https://user-images.githubusercontent.com/20930745/64917277-bac03f80-d78e-11e9-932a-c6f945e4f165.png
