### ISSUE TITLE
Contacts+ | Address Book

### ISSUE THREAD

**Issue by Crocmagnon** [glasklart/hd#1038]
**App Name:** Contacts+ | Address Book
**Bundle ID:** com.cobookapp.cobook.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=579616837">579616837</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/contacts-address-book/id579616837?uo=4">https://apps.apple.com/us/app/contacts-address-book/id579616837?uo=4</a>
**App Version:** 19.06.4
**Seller:** FullContact Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fullcontact-inc/id489685226?uo=4">© FullContact Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/c1/5e/a0/c15ea0ec-35b1-eb46-b260-fccc068fe0bb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60369902-627e6a80-99f5-11e9-85a6-a2e89688718d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19493638/dfe70f9e-957b-11e6-9492-a384cf9f5d0c.png)
https://cloud.githubusercontent.com/assets/20930745/19493638/dfe70f9e-957b-11e6-9492-a384cf9f5d0c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19493681/020061d4-957c-11e6-8e90-684b6bbfe64b.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60369902-627e6a80-99f5-11e9-85a6-a2e89688718d.png)
https://user-images.githubusercontent.com/2068130/60369902-627e6a80-99f5-11e9-85a6-a2e89688718d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60369926-71651d00-99f5-11e9-9829-0ef3b1538978.png
