### ISSUE TITLE
Litter-Robot Connect

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10392]
**App Name:** Litter-Robot Connect
**Bundle ID:** com.autopets.whisker.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1240404534">1240404534</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/litter-robot-connect/id1240404534?uo=4">https://apps.apple.com/us/app/litter-robot-connect/id1240404534?uo=4</a>
**App Version:** 1.3.0
**Seller:** Automated Pet Care Products Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/automated-pet-care-products-inc-dba-autopets/id1240404533?uo=4">© Automated Pet Care Products Inc. dba AutoPets</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/f8/f7/fa/f8f7faec-bb3c-824e-05fc-a55ea940ad61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64919304-64acc580-d7a9-11e9-9c8c-c79155615c75.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64919304-64acc580-d7a9-11e9-9c8c-c79155615c75.png)
(https://user-images.githubusercontent.com/20930745/64919304-64acc580-d7a9-11e9-9c8c-c79155615c75.png

Source:
https://user-images.githubusercontent.com/20930745/64919305-66768900-d7a9-11e9-9ac1-5e1230de4814.png
