### ISSUE TITLE
Banfield Pet Hospital

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10394]
**App Name:** Banfield Pet Hospital
**Bundle ID:** com.banfield.bpht
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=799061555">799061555</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/banfield-pet-hospital/id799061555?uo=4">https://apps.apple.com/us/app/banfield-pet-hospital/id799061555?uo=4</a>
**App Version:** 1.2.13
**Seller:** Medical Management International Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/banfield-pet-hospital/id799061558?uo=4">© Banfield Pet Hospital</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/c9/1f/4a/c91f4ae3-7238-9be0-7cfe-646c9245980e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64956004-ef64f180-d889-11e9-91ab-10448f636b3b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64956004-ef64f180-d889-11e9-91ab-10448f636b3b.png)
https://user-images.githubusercontent.com/20930745/64956004-ef64f180-d889-11e9-91ab-10448f636b3b.png

Source:
https://user-images.githubusercontent.com/20930745/64956008-f0961e80-d889-11e9-96f3-a6a75d08d932.png
