### ISSUE TITLE
Petnet Mobile

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10391]
**App Name:** Petnet Mobile
**Bundle ID:** io.petnet.Petnet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=962239016">962239016</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/petnet-mobile/id962239016?uo=4">https://apps.apple.com/us/app/petnet-mobile/id962239016?uo=4</a>
**App Version:** 5.7.5
**Seller:** Petnet Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/petnet-inc/id919258112?uo=4">© Petnet Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/b1/d5/11/b1d51188-647b-f868-66a2-96d3f46c9939/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64919253-9d986a80-d7a8-11e9-8486-cc064c604919.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64919253-9d986a80-d7a8-11e9-8486-cc064c604919.png)
(https://user-images.githubusercontent.com/20930745/64919253-9d986a80-d7a8-11e9-8486-cc064c604919.png

Source:
https://user-images.githubusercontent.com/20930745/64919257-9ec99780-d7a8-11e9-9c5b-d0cec58d90a4.png
