### ISSUE TITLE
SafeShutdown

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10390]
**App Name:** SafeShutdown
**Bundle ID:** com.kurrt.safeshutdownapp
**Version:** 1.54
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/64918913-d8989f00-d7a4-11e9-8f03-6b92e2de6fa9.png" width="180" height="180">
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64918886-98d1b780-d7a4-11e9-8e44-08b9157e38c3.png)

**Comment by 2Qt2beStr8** [comment]
@tlunmp to create a Icon i need a better artwork

**Comment by tlunmp** [comment]
sorry bout that do I need to make new issue or post it here?

**Comment by tlunmp** [comment]
updated it but the original icon is really blurry

**Comment by dreamnet** [comment]
I "reconstructed" the original icon (see above).
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64918886-98d1b780-d7a4-11e9-8e44-08b9157e38c3.png)
https://user-images.githubusercontent.com/2068130/64918886-98d1b780-d7a4-11e9-8e44-08b9157e38c3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64918894-a7b86a00-d7a4-11e9-9802-813d5594824b.png

**Comment by tlunmp** [comment]
thanks your icon is way better than the original one from the developer. the developer icon was blurry
