### ISSUE TITLE
Spotify Stations

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10399]
**App Name:** Spotify Stations
**Bundle ID:** com.spotify.stations
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1453043471">1453043471</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/spotify-stations/id1453043471?uo=4">https://apps.apple.com/us/app/spotify-stations/id1453043471?uo=4</a>
**App Version:** 1.16
**Seller:** Spotify
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/spotify-ltd/id324684583?uo=4">© Spotify Ltd.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/3a/be/83/3abe832f-9408-77a4-9dd5-373dd4c22f35/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/65438920-94ea0900-de26-11e9-9d26-908e2b84e583.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/65438920-94ea0900-de26-11e9-9d26-908e2b84e583.png)
https://user-images.githubusercontent.com/20930745/65438920-94ea0900-de26-11e9-9d26-908e2b84e583.png

Source:
https://user-images.githubusercontent.com/20930745/65438922-96b3cc80-de26-11e9-8059-21eb834b670c.png
