### ISSUE TITLE
myTuner Radio Pro

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10393]
**App Name:** myTuner Radio Pro
**Bundle ID:** mobi.digitalminds.itunerpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520511560">520511560</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mytuner-radio-pro/id520511560?uo=4">https://apps.apple.com/us/app/mytuner-radio-pro/id520511560?uo=4</a>
**App Version:** 7.1.2
**Seller:** Appgeneration, Software Technologies, Lda
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/appgeneration-software/id386316599?uo=4">© Appgeneration Software</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/44/4e/ec/444eecf0-4551-aa06-b615-7c158779d465/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64955661-1d960180-d889-11e9-9498-822de60773fd.png)

**Comment by 2Qt2beStr8** [comment]
@tlunmp please use always the complete App Name as issue title

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64955661-1d960180-d889-11e9-9498-822de60773fd.png)
https://user-images.githubusercontent.com/20930745/64955661-1d960180-d889-11e9-9498-822de60773fd.png

Source:
https://user-images.githubusercontent.com/20930745/64955663-1ec72e80-d889-11e9-9de0-b68586238a29.png
