### ISSUE TITLE
Wingstop 

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10395]
**App Name:** Wingstop
**Bundle ID:** com.mobilaurus.wingstopongroup2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454719277">454719277</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wingstop/id454719277?uo=4">https://apps.apple.com/us/app/wingstop/id454719277?uo=4</a>
**App Version:** 6.11.0
**Seller:** Wingstop Restaurants, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wingstop-restaurants-inc/id904949488?uo=4">© Wingstop Restaurants, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/2b/7e/7a/2b7e7ae5-0556-ae36-6580-c9db4ab4bab8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64956348-a82b3080-d88a-11e9-84da-f0653f405a90.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/64956348-a82b3080-d88a-11e9-84da-f0653f405a90.png)
https://user-images.githubusercontent.com/20930745/64956348-a82b3080-d88a-11e9-84da-f0653f405a90.png

Source:
https://user-images.githubusercontent.com/20930745/64956364-aa8d8a80-d88a-11e9-98c8-c62ccdf17f65.png
