### ISSUE TITLE
Grocery Gadget Shopping List

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#104]
**App Name:** Grocery Gadget Shopping List
**Bundle ID:** com.flixoft.grocerygadget
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=287932487">287932487</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grocery-gadget-shopping-list/id287932487?mt=8&uo=4">https://itunes.apple.com/us/app/grocery-gadget-shopping-list/id287932487?mt=8&uo=4</a>
**App Version:** 5.2.2
**Seller:** Pingwell Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pingwell-inc/id666075312?uo=4">© Pingwell Inc</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple127/v4/a7/25/00/a725002b-bf23-d614-6190-54e36984ee82/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692541-db4aa16e-c719-11e7-9b8d-9b6c02968eb1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692541-db4aa16e-c719-11e7-9b8d-9b6c02968eb1.png)
https://user-images.githubusercontent.com/2068130/32692541-db4aa16e-c719-11e7-9b8d-9b6c02968eb1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692543-ea056400-c719-11e7-8c5f-8f5b53c9c592.png
