### ISSUE TITLE
AudioShare

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10407]
**App Name:** AudioShare
**Bundle ID:** com.kymatica.AudioShare
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=543859300">543859300</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/audioshare/id543859300?uo=4">https://apps.apple.com/us/app/audioshare/id543859300?uo=4</a>
**App Version:** 2.7.8
**Seller:** Kymatica AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kymatica-ab/id522046659?uo=4">© Kymatica AB</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, Watch5-Watch5, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65391724-dd44f080-dd6c-11e9-8fe3-7b0a27e641a7.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828838-9476c580-e29f-11e9-8d9d-275492c917ff.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65391762-2ac15d80-dd6d-11e9-8efe-d96e62127a88.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65391762-2ac15d80-dd6d-11e9-8efe-d96e62127a88.png)

Source:

https://user-images.githubusercontent.com/28823252/65391745-13827000-dd6d-11e9-91ab-2f04332fcd6c.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828838-9476c580-e29f-11e9-8d9d-275492c917ff.png)
https://user-images.githubusercontent.com/2068130/65828838-9476c580-e29f-11e9-8d9d-275492c917ff.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65828843-a5273b80-e29f-11e9-8fdd-8528bd1f17de.png
Credits to @cassio299. 👍
