### ISSUE TITLE
AudioKit Synth One Synthesizer

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10404]
**App Name:** AudioKit Synth One Synthesizer
**Bundle ID:** com.audiokitpro.AudioKitSynthOne
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1371050497">1371050497</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/audiokit-synth-one-synthesizer/id1371050497?uo=4">https://apps.apple.com/us/app/audiokit-synth-one-synthesizer/id1371050497?uo=4</a>
**App Version:** 1.2
**Seller:** AudioKit Pro, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/audiokit-pro/id1307785645?uo=4">© AudioKit Pro</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65390883-d87b3f00-dd62-11e9-8155-b2414bef2350.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66017389-f1aa8b00-e4da-11e9-9952-db052f9b871f.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65390899-fcd71b80-dd62-11e9-8cad-7963b373f61c.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65390899-fcd71b80-dd62-11e9-8cad-7963b373f61c.png)

source:

https://user-images.githubusercontent.com/28823252/65390917-33149b00-dd63-11e9-8327-32a14b159632.png

**Comment by dreamnet** [comment]
@cassio299 Hmmmmm... that's way different than the original.

**Comment by cassio299** [comment]
@dreamnet I don't think that several smal objects in one color is visible for the eye when it comes to small icons, therefore I took two of the symbols from the icon and combined them.

**Comment by dreamnet** [comment]
@cassio299 OK - I take it because ist's your icon request. 👍 
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66017389-f1aa8b00-e4da-11e9-9952-db052f9b871f.png)
https://user-images.githubusercontent.com/2068130/66017389-f1aa8b00-e4da-11e9-9952-db052f9b871f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66017408-0129d400-e4db-11e9-9c4d-4265f1e272e3.png
