### ISSUE TITLE
AirSnap

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10401]
**App Name:** AirSnap
**Bundle ID:** org.cloudns.airsnap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1295680182">1295680182</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/airsnap/id1295680182?uo=4">https://apps.apple.com/us/app/airsnap/id1295680182?uo=4</a>
**App Version:** 1.8.3
**Seller:** Arash Afrasiabi
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/arash-afrasiabi/id1218026573?uo=4">© Arash Afrasiabi</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/4e/e1/8d/4ee18d0e-a133-df97-cb1f-11a9f4cbabdf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74556996-8203dc80-4f5f-11ea-941d-d576c254baaf.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/65441343-89004600-de2a-11e9-90bb-381c5d855fe0.png)
(https://user-images.githubusercontent.com/20930745/65441343-89004600-de2a-11e9-90bb-381c5d855fe0.png

Source:
https://user-images.githubusercontent.com/20930745/65441352-8b62a000-de2a-11e9-9419-1e18fe85091f.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** AirSnap
**Bundle ID:** org.cloudns.airsnap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1295680182">1295680182</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/airsnap/id1295680182?uo=4">https://apps.apple.com/us/app/airsnap/id1295680182?uo=4</a>
**App Version:** 1.8.3
**Seller:** Arash Afrasiabi
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/arash-afrasiabi/id1218026573?uo=4">© Arash Afrasiabi</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/4e/e1/8d/4ee18d0e-a133-df97-cb1f-11a9f4cbabdf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74556996-8203dc80-4f5f-11ea-941d-d576c254baaf.png)
https://user-images.githubusercontent.com/20930745/74556996-8203dc80-4f5f-11ea-941d-d576c254baaf.png

Source:
https://user-images.githubusercontent.com/20930745/74556998-83350980-4f5f-11ea-8ce4-ff2c8f1c3cb8.png

**Comment by 2Qt2beStr8** [comment]
or:
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74557070-acee3080-4f5f-11ea-9ee6-56baa9a04829.png)
https://user-images.githubusercontent.com/20930745/74557070-acee3080-4f5f-11ea-9ee6-56baa9a04829.png

Source:
https://user-images.githubusercontent.com/20930745/74557076-af508a80-4f5f-11ea-88f9-7c0edd029017.png
