### ISSUE TITLE
AUM - Audio Mixer 

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10408]
**App Name:** AUM - Audio Mixer
**Bundle ID:** com.kymatica.AUM
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1055636344">1055636344</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/aum-audio-mixer/id1055636344?uo=4">https://apps.apple.com/us/app/aum-audio-mixer/id1055636344?uo=4</a>
**App Version:** 1.3.1
**Seller:** Kymatica AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kymatica-ab/id522046659?uo=4">© Kymatica AB</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65391891-aff94200-dd6e-11e9-8e26-895d7bbc608d.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828788-f125b080-e29e-11e9-8b41-bcd1cd12fca0.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65391905-e59e2b00-dd6e-11e9-8101-0fbd41bbd637.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65391905-e59e2b00-dd6e-11e9-8101-0fbd41bbd637.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828788-f125b080-e29e-11e9-8b41-bcd1cd12fca0.png)
https://user-images.githubusercontent.com/2068130/65828788-f125b080-e29e-11e9-8b41-bcd1cd12fca0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65828792-000c6300-e29f-11e9-953a-6b31aecbed7c.png
Credits to @cassio299. 👍
