### ISSUE TITLE
Bike Repair

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10403]
**App Name:** Bike Repair
**Bundle ID:** com.atomicsoftwares.bikerepair
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382006079">382006079</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bike-repair/id382006079?uo=4">https://apps.apple.com/us/app/bike-repair/id382006079?uo=4</a>
**App Version:** 7.24
**Seller:** Atomic Softwares
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/atomic-softwares/id382006082?uo=4">© Atomic Softwares</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65390560-93eea400-dd60-11e9-8b96-357a03fa4985.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828004-56c16f00-e296-11e9-8077-2a5c01de4737.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65390579-c7313300-dd60-11e9-9ced-2f42a7e75799.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65390579-c7313300-dd60-11e9-9ced-2f42a7e75799.png
source:

https://user-images.githubusercontent.com/28823252/65390605-095a7480-dd61-11e9-8fa7-61a899954aae.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828004-56c16f00-e296-11e9-8077-2a5c01de4737.png)
https://user-images.githubusercontent.com/2068130/65828004-56c16f00-e296-11e9-8077-2a5c01de4737.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65828016-6771e500-e296-11e9-87ce-bdf1661572f3.png
Credits to @cassio299. 👍
