### ISSUE TITLE
SampleTank

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10406]
**App Name:** SampleTank
**Bundle ID:** com.ikmultimediaus.sampletankfull
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=464783893">464783893</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sampletank/id464783893?uo=4">https://apps.apple.com/us/app/sampletank/id464783893?uo=4</a>
**App Version:** 2.0.11
**Seller:** IK Multimedia US, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ik-multimedia/id323694278?uo=4">© IK Multimedia</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65391363-a40a8180-dd68-11e9-85c9-182364b4f6f2.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828913-53cb7c00-e2a0-11e9-878c-661bf9f1dce8.png)

**Comment by cassio299** [comment]
![com ikmultimediaus sampletankfull](https://user-images.githubusercontent.com/28823252/65391625-8ee32200-dd6b-11e9-8d56-54941ff01554.png)


source

https://user-images.githubusercontent.com/28823252/65391613-770b9e00-dd6b-11e9-9e49-76b63114d13f.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828913-53cb7c00-e2a0-11e9-878c-661bf9f1dce8.png)
https://user-images.githubusercontent.com/2068130/65828913-53cb7c00-e2a0-11e9-878c-661bf9f1dce8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65828918-63e35b80-e2a0-11e9-9f02-0216ba20ff65.png
