### ISSUE TITLE
Power Selector 

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10405]
**App Name:** Power Selector
**Bundle ID:** com.ichitaso.powerselectorapp
**Version:** 1.21
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65391097-72dc8200-dd65-11e9-9bf3-fe31a50a47b3.jpeg" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65829041-7f029b00-e2a1-11e9-83d8-fb21f791ed96.png)

**Comment by cassio299** [comment]
![com ichitaso powerselectorapp](https://user-images.githubusercontent.com/28823252/65391109-b7681d80-dd65-11e9-92b0-696c655ba0d3.png


source:

https://user-images.githubusercontent.com/28823252/65391119-d49cec00-dd65-11e9-9f8f-4a4070ae74d2.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65829041-7f029b00-e2a1-11e9-83d8-fb21f791ed96.png)
https://user-images.githubusercontent.com/2068130/65829041-7f029b00-e2a1-11e9-83d8-fb21f791ed96.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65829047-8de94d80-e2a1-11e9-85ea-ff8820ef6e9d.png
Credits to @cassio299. 👍
