### ISSUE TITLE
MediaBox HD

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10409]
**App Name:** MediaBox HD
**Bundle ID:** com.media.hdplayerhd
**Version:** 2.4.6
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65392421-1bdea900-dd75-11e9-96ba-92533eb50938.jpg" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828739-56c56d00-e29e-11e9-9685-8551cb2ed6e7.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65392440-4af51a80-dd75-11e9-934f-9722f458b16e.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65392440-4af51a80-dd75-11e9-934f-9722f458b16e.png)

Source:

https://user-images.githubusercontent.com/28823252/65392463-8394f400-dd75-11e9-9859-8609ab0c4dbb.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828739-56c56d00-e29e-11e9-9685-8551cb2ed6e7.png)
https://user-images.githubusercontent.com/2068130/65828739-56c56d00-e29e-11e9-9685-8551cb2ed6e7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65828744-66dd4c80-e29e-11e9-94e2-a46d4ecd2f54.png
Credits to @cassio299. 👍
