### ISSUE TITLE
iMPC for iPhone

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10402]
**App Name:** iMPC for iPhone
**Bundle ID:** com.akaipro.impciphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=677356259">677356259</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/impc-for-iphone/id677356259?uo=4">https://apps.apple.com/us/app/impc-for-iphone/id677356259?uo=4</a>
**App Version:** 1.4.7
**Seller:** Akai Professional
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/akai-professional/id373969727?uo=4">© Akai Professional</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/dd/da/05/ddda05cf-615c-de05-f307-c4a726675419/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65827926-a94e5b80-e295-11e9-94aa-e8090867becc.png)

**Comment by cassio299** [comment]
![com akaipro impciphone](https://user-images.githubusercontent.com/28823252/65390284-e4183700-dd5d-11e9-9592-cfc229c02e44.png)

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65390284-e4183700-dd5d-11e9-9592-cfc229c02e44.png)

source file:

![com akaipro impc](https://user-images.githubusercontent.com/28823252/65390407-b089dc80-dd5e-11e9-8385-806669ace7ca.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65827926-a94e5b80-e295-11e9-94aa-e8090867becc.png)
https://user-images.githubusercontent.com/2068130/65827926-a94e5b80-e295-11e9-94aa-e8090867becc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65827931-b8cda480-e295-11e9-899b-3c9a9a7f3d11.png
Credits to @cassio299. 👍
