### ISSUE TITLE
Super ToDo's

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10400]
**App Name:** Super ToDo's
**Bundle ID:** com.howlin.SuperToDos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1195333305">1195333305</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/super-todos/id1195333305?uo=4">https://apps.apple.com/us/app/super-todos/id1195333305?uo=4</a>
**App Version:** 3.0
**Seller:** Jason Howlin
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/howlin-interactive-inc/id543942517?uo=4">© Howlin Interactive, Inc.</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/c2/66/d3/c266d36c-f8dc-b0dd-65dd-6508b7f49cf2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/65439249-26f21180-de27-11e9-9a9d-13fb7f4b103b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/65439249-26f21180-de27-11e9-9a9d-13fb7f4b103b.png)
(https://user-images.githubusercontent.com/20930745/65439249-26f21180-de27-11e9-9a9d-13fb7f4b103b.png

Source:
https://user-images.githubusercontent.com/20930745/65439254-28233e80-de27-11e9-8070-23c1a7e57479.png
