### ISSUE TITLE
SoFlow

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10413]
**App Name:** SoFlow
**Bundle ID:** com.soflowapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1474365521">1474365521</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/soflow/id1474365521?uo=4">https://apps.apple.com/us/app/soflow/id1474365521?uo=4</a>
**App Version:** 1.1.3
**Seller:** SoFlow AG
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/soflow/id1340920215?uo=4">© SOFLOW</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/de/8d/07/de8d07d0-87e3-4a80-8e02-3803136121a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/65708403-cd8c1b80-e08e-11e9-8495-277a86252f1e.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/65708403-cd8c1b80-e08e-11e9-8495-277a86252f1e.png)
https://user-images.githubusercontent.com/20930745/65708403-cd8c1b80-e08e-11e9-8495-277a86252f1e.png

Source:
https://user-images.githubusercontent.com/20930745/65708408-cebd4880-e08e-11e9-918b-1bcd4cc441a2.png
