### ISSUE TITLE
Mario Kart Tour

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10416]
**App Name:** Mario Kart Tour
**Bundle ID:** com.nintendo.zaka
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1293634699">1293634699</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mario-kart-tour/id1293634699?uo=4">https://apps.apple.com/us/app/mario-kart-tour/id1293634699?uo=4</a>
**App Version:** 1.0.1
**Seller:** Nintendo Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nintendo-co-ltd/id1062496488?uo=4">© Nintendo Co., Ltd.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/31/de/bb/31debbb1-2507-55cd-99e4-7a407403bf13/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66272545-6bd86800-e86b-11e9-9eb7-f6647c450d70.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/66262766-ceb6fa00-e7ac-11e9-8119-01daffeba54b.png)

https://user-images.githubusercontent.com/44279267/66262766-ceb6fa00-e7ac-11e9-8119-01daffeba54b.png

Source:
https://user-images.githubusercontent.com/44279267/66262785-f7d78a80-e7ac-11e9-97fa-dec7e2f14002.png

**Comment by dreamnet** [comment]
❓ 
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66272545-6bd86800-e86b-11e9-9eb7-f6647c450d70.png)
https://user-images.githubusercontent.com/2068130/66272545-6bd86800-e86b-11e9-9eb7-f6647c450d70.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66272556-86124600-e86b-11e9-9d19-d111f561c4d0.png
