### ISSUE TITLE
Truede Ord

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10419]
**App Name:** Truede Ord
**Bundle ID:** com.miracleas.Extinctionary
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446665391">446665391</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/truede-ord/id446665391?uo=4">https://apps.apple.com/us/app/truede-ord/id446665391?uo=4</a>
**App Version:** 3.1
**Seller:** Gyldendalske Boghandel Nordisk Forlag A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gyldendal/id370340254?uo=4">© Gyldendal</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, Watch5-Watch5, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65840617-72bb2400-e31b-11e9-9a06-15ca21c6c8d0.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66264644-a1e50000-e809-11e9-96f4-5d3d1ae11d16.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65840636-9c744b00-e31b-11e9-9cc2-6b9ab56952f4.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65840636-9c744b00-e31b-11e9-9cc2-6b9ab56952f4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66264644-a1e50000-e809-11e9-96f4-5d3d1ae11d16.png)
https://user-images.githubusercontent.com/2068130/66264644-a1e50000-e809-11e9-96f4-5d3d1ae11d16.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66264646-b1fcdf80-e809-11e9-9bb2-b58541672258.png
