### ISSUE TITLE
Animoog for iPhone

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10410]
**App Name:** Animoog for iPhone
**Bundle ID:** com.moogmusic.animoogiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490169960">490169960</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/animoog-for-iphone/id490169960?uo=4">https://apps.apple.com/us/app/animoog-for-iphone/id490169960?uo=4</a>
**App Version:** 1.3.7
**Seller:** Moog Music Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/moog-music-inc/id396776421?uo=4">© Moog Music Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65392903-8a723580-dd7a-11e9-8d42-47c2d3e02ddf.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828624-26c99a00-e29d-11e9-846d-b70a5bb77b30.png)

**Comment by cassio299** [comment]
****. This is the iPhone version, iPad version already made *******

https://user-images.githubusercontent.com/28823252/65392933-d9b86600-dd7a-11e9-889d-ae02ef33c7ab.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65392933-d9b86600-dd7a-11e9-889d-ae02ef33c7ab.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828624-26c99a00-e29d-11e9-846d-b70a5bb77b30.png)
https://user-images.githubusercontent.com/2068130/65828624-26c99a00-e29d-11e9-846d-b70a5bb77b30.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65828628-347f1f80-e29d-11e9-9c34-5f6ba97ff443.png
Credits to @cassio299. 👍
