### ISSUE TITLE
Model 15

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10411]
**App Name:** Model 15
**Bundle ID:** com.moogmusic.model15
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1041465860">1041465860</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/model-15/id1041465860?uo=4">https://apps.apple.com/us/app/model-15/id1041465860?uo=4</a>
**App Version:** 2.1.7
**Seller:** Moog Music Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/moog-music-inc/id396776421?uo=4">© Moog Music Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65393017-c6f26100-dd7b-11e9-882a-f8898a92b794.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828539-32689100-e29c-11e9-8830-ceccf828d82d.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65393037-fdc87700-dd7b-11e9-9f99-ec0b3f8c9193.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65393037-fdc87700-dd7b-11e9-9f99-ec0b3f8c9193.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828539-32689100-e29c-11e9-8830-ceccf828d82d.png)
https://user-images.githubusercontent.com/2068130/65828539-32689100-e29c-11e9-8830-ceccf828d82d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65828542-43b19d80-e29c-11e9-8a42-ac98b68cb3b0.png
Credits to @cassio299. 👍
