### ISSUE TITLE
WhatsApp Business

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10415]
**App Name:** WhatsApp Business
**Bundle ID:** net.whatsapp.WhatsAppSMB
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1386412985">1386412985</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/whatsapp-business/id1386412985?uo=4">https://apps.apple.com/us/app/whatsapp-business/id1386412985?uo=4</a>
**App Version:** 2.19.92
**Seller:** WhatsApp Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/whatsapp-inc/id310634000?uo=4">© WhatsApp Inc.</a>
**Supported Devices:** iPhone4S-iPhone4S, iPhone5-iPhone5, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/3f/02/46/3f024615-35e6-e82d-c9ef-06869556507e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/65707598-28247800-e08d-11e9-8204-fc0ffce9a2c4.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/65707598-28247800-e08d-11e9-8204-fc0ffce9a2c4.png)
https://user-images.githubusercontent.com/20930745/65707598-28247800-e08d-11e9-8204-fc0ffce9a2c4.png

Source:
https://user-images.githubusercontent.com/20930745/65707601-2955a500-e08d-11e9-8e65-0881c79bdc86.png
