### ISSUE TITLE
Buffer - Schedule Posts for Twitter & Instagram

### ISSUE THREAD

**Issue by Crocmagnon** [glasklart/hd#1041]
**App Name:** Buffer - Schedule Posts for Twitter & Instagram
**Bundle ID:** com.buffer.buffer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490474324">490474324</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/buffer-schedule-posts-for/id490474324?mt=8&uo=4">https://itunes.apple.com/us/app/buffer-schedule-posts-for/id490474324?mt=8&uo=4</a>
**App Version:** 6.0.5
**Seller:** Buffer, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/buffer-inc./id490474327?uo=4>© Buffer, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/3b/54/13/3b54132b-c142-e2d6-c154-3b851e65a909/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19493288/54c664d8-957a-11e6-8c41-1e9aee8adaa2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19493288/54c664d8-957a-11e6-8c41-1e9aee8adaa2.png)
https://cloud.githubusercontent.com/assets/20930745/19493288/54c664d8-957a-11e6-8c41-1e9aee8adaa2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19493318/73910a9e-957a-11e6-8d1a-f34390335a7e.png
