### ISSUE TITLE
Minimoog Model D

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10412]
**App Name:** Minimoog Model D
**Bundle ID:** com.moogmusic.modeld
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1339418001">1339418001</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/minimoog-model-d/id1339418001?uo=4">https://apps.apple.com/us/app/minimoog-model-d/id1339418001?uo=4</a>
**App Version:** 1.2.0
**Seller:** Moog Music Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/moog-music-inc/id396776421?uo=4">© Moog Music Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65395713-0b432880-dd9f-11e9-8abf-b9810035cd79.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828398-d5b8a680-e29a-11e9-80ae-f4db3717ed85.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65395727-2c0b7e00-dd9f-11e9-9fbc-81b1807caab8.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65395727-2c0b7e00-dd9f-11e9-9fbc-81b1807caab8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65828398-d5b8a680-e29a-11e9-80ae-f4db3717ed85.png)
https://user-images.githubusercontent.com/2068130/65828398-d5b8a680-e29a-11e9-80ae-f4db3717ed85.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65828407-e406c280-e29a-11e9-936f-ba0ed02c504c.png
Credits to @cassio299. 👍
