### ISSUE TITLE
Ordbogi GL DK

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10426]
**App Name:** Ordbogi GL DK
**Bundle ID:** com.ordbogi.gldk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1277137753">1277137753</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ordbogi-gl-dk/id1277137753?uo=4">https://apps.apple.com/us/app/ordbogi-gl-dk/id1277137753?uo=4</a>
**App Version:** 2.1
**Seller:** Ulrik Motzfeldt-Skovgaard
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ulrik-motzfeldt-skovgaard/id1077048375?uo=4">© Ulrik Motzfeldt-Skovgaard</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/ec/94/b7/ec94b734-2907-2d9c-4fa7-551af9d2ab7b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66272318-85c47b80-e868-11e9-9bc6-0e91d124802f.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65841699-83709780-e325-11e9-9aea-0a2cc74fc2e0.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65841699-83709780-e325-11e9-9aea-0a2cc74fc2e0.png)

Source

https://user-images.githubusercontent.com/28823252/65841727-c6cb0600-e325-11e9-8123-0298dbbe1dae.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66272318-85c47b80-e868-11e9-9bc6-0e91d124802f.png)
https://user-images.githubusercontent.com/2068130/66272318-85c47b80-e868-11e9-9bc6-0e91d124802f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66272322-9674f180-e868-11e9-98b7-77af7c09fee6.png
