### ISSUE TITLE
Futurama: Worlds of Tomorrow

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10428]
**App Name:** Futurama: Worlds of Tomorrow
**Bundle ID:** com.tinycorp.futurama
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1207472130">1207472130</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/futurama-worlds-of-tomorrow/id1207472130?uo=4">https://apps.apple.com/us/app/futurama-worlds-of-tomorrow/id1207472130?uo=4</a>
**App Version:** 1.6.6
**Seller:** Jam City, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/jam-city-inc/id290671617?uo=4">© Jam City, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/9a/48/dc/9a48dc97-5865-dece-55f7-eb11a78fe69f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66266166-8d146680-e821-11e9-9f04-331f5b01fb82.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65842090-3989b080-e329-11e9-86e3-5970c2ea86e7.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65842090-3989b080-e329-11e9-86e3-5970c2ea86e7.png)

Source:

https://user-images.githubusercontent.com/28823252/65842151-e106e300-e329-11e9-98aa-96d414750eea.png

**Comment by cassio299** [comment]
Most drawing and photos of faces looks like the clown in Stephen Kings IT, So doing justice to Fry is   doing justice to the fans of Futurama, I therefore changed the icon to The Planet Express icon.

I might submit the Hypnotoad icon if The Planet Express icon will be rejected !! (All Power to the Hypnotoad)

**Comment by dreamnet** [comment]
@cassio299 I understand what you mean (we only have white/transparent), but I think doing Fry from the original icon dosent look too bad:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66266166-8d146680-e821-11e9-9f04-331f5b01fb82.png)
https://user-images.githubusercontent.com/2068130/66266166-8d146680-e821-11e9-9f04-331f5b01fb82.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66266174-a0bfcd00-e821-11e9-8650-0d2ef8a08247.png
It's also a "rule" for Glasklart to go with the original icon if possible. But in this case it's your request and decision. Your or my icon?
