### ISSUE TITLE
Lemma

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10425]
**App Name:** Lemma
**Bundle ID:** com.ordbogen.ordbogenapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409803876">409803876</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/lemma/id409803876?uo=4">https://apps.apple.com/us/app/lemma/id409803876?uo=4</a>
**App Version:** 3.1.1
**Seller:** Ordbogen A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ordbogen-a-s/id409803879?uo=4">© Ordbogen A/S</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/a3/b7/40/a3b74071-cd91-05e2-a51c-f62352e4d25f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66265896-fe521a80-e81d-11e9-90d0-90a9de8755a1.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65841611-87e88080-e324-11e9-839e-91a1bdcd2620.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65841611-87e88080-e324-11e9-839e-91a1bdcd2620.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66265896-fe521a80-e81d-11e9-90d0-90a9de8755a1.png)
https://user-images.githubusercontent.com/2068130/66265896-fe521a80-e81d-11e9-90d0-90a9de8755a1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66265902-0dd16380-e81e-11e9-8515-6096a898cded.png
