### ISSUE TITLE
BackupAZ3

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10427]
**App Name:** BackupAZ3
**Bundle ID:** com.synnyg.backupaz3i
**Version:** 3.0
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/28823252/65841922-ca5f8c80-e327-11e9-97b0-08be0d876ffd.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66695497-b66e4000-ecc2-11e9-8cdd-d96d7b8d7551.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65841966-1ad6ea00-e328-11e9-942e-0e27866e885e.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65841966-1ad6ea00-e328-11e9-942e-0e27866e885e.png)

Source:

com synnyg backupaz3](https://user-images.githubusercontent.com/28823252/65841983-507bd300-e328-11e9-99b8-dbfb1a90c0eb.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66695497-b66e4000-ecc2-11e9-8cdd-d96d7b8d7551.png)
https://user-images.githubusercontent.com/2068130/66695497-b66e4000-ecc2-11e9-8cdd-d96d7b8d7551.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66695508-c5ed8900-ecc2-11e9-8f9d-dacacabb8222.png
