### ISSUE TITLE
 iMaschine 2

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10424]
**App Name:** iMaschine 2
**Bundle ID:** com.native-instruments.imaschine2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989330818">989330818</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/imaschine-2/id989330818?uo=4">https://apps.apple.com/us/app/imaschine-2/id989330818?uo=4</a>
**App Version:** 2.2.2
**Seller:** Native Instruments GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/native-instruments-gmbh/id400432597?uo=4">© NATIVE INSTRUMENTS GmbH</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/c3/ad/08/c3ad0866-391a-ffa1-ee13-c8d759eb22a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66265756-dcf02f00-e81b-11e9-9b9e-db4cb709b370.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65841539-aac66500-e323-11e9-83e6-5ef6bc560870.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65841539-aac66500-e323-11e9-83e6-5ef6bc560870.png)

Source:

https://user-images.githubusercontent.com/28823252/65841563-e7925c00-e323-11e9-9646-d895a10cd909.png

**Comment by dreamnet** [comment]
We go with the original.
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66265756-dcf02f00-e81b-11e9-9b9e-db4cb709b370.png)
https://user-images.githubusercontent.com/2068130/66265756-dcf02f00-e81b-11e9-9b9e-db4cb709b370.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66265760-ebd6e180-e81b-11e9-9d38-f2a656d9f248.png
