### ISSUE TITLE
Gyldendal's German Danish Dictionary - Medium

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10422]
**App Name:** Gyldendal's German Danish Dictionary - Medium
**Bundle ID:** dk.letsoftware.GyldendalsTyskMedium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338921538">338921538</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gyldendals-german-danish-dictionary-medium/id338921538?uo=4">https://apps.apple.com/us/app/gyldendals-german-danish-dictionary-medium/id338921538?uo=4</a>
**App Version:** 2.4
**Seller:** Gyldendalske Boghandel Nordisk Forlag A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gyldendal/id370340254?uo=4">© Gyldendal</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, Watch5-Watch5, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/ad/42/8f/ad428f0d-e596-9e9c-88b4-1d1d28bbc7b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67155522-89004280-f311-11e9-94b5-d0fe2dc1fe3b.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65841313-2d99f080-e321-11e9-92e1-68947364255b.png

![](https://preview.dreamnet.at?image= https://user-images.githubusercontent.com/28823252/65841313-2d99f080-e321-11e9-92e1-68947364255b.png

Source:

https://user-images.githubusercontent.com/28823252/65841337-72be2280-e321-11e9-987a-5f18ae15fc4c.png

**Comment by dreamnet** [comment]
Same as #10421.
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66265219-05bff680-e813-11e9-812f-973b9da60b28.png)
https://user-images.githubusercontent.com/2068130/66265219-05bff680-e813-11e9-812f-973b9da60b28.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66265223-14a6a900-e813-11e9-9141-cfaa798cc55a.png

**Comment by dreamnet** [comment]
Same as #10421.
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67155522-89004280-f311-11e9-94b5-d0fe2dc1fe3b.png)
https://user-images.githubusercontent.com/2068130/67155522-89004280-f311-11e9-94b5-d0fe2dc1fe3b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/67155532-987f8b80-f311-11e9-8475-ead6c2a5682f.png
