### ISSUE TITLE
Cr4shed

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10420]
**App Name:** Cr4shed
**Bundle ID:** com.muirey03.cr4shedgui
**Version:** 1.0
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/66264730-795e0580-e80b-11e9-95a1-2dc2566773ab.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66265140-77974080-e811-11e9-8f4b-c4e967568f3e.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/65840888-5a003d80-e31e-11e9-97cb-fa636aee45c2.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/65840888-5a003d80-e31e-11e9-97cb-fa636aee45c2.png)

Source:

https://user-images.githubusercontent.com/28823252/65840958-f9253500-e31e-11e9-9005-88ee7bbbf8da.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/65901262-1eb24d00-e3b8-11e9-92f9-4008d2f55a4c.png)
https://user-images.githubusercontent.com/20930745/65901262-1eb24d00-e3b8-11e9-92f9-4008d2f55a4c.png

Source:
https://user-images.githubusercontent.com/20930745/65901264-2114a700-e3b8-11e9-922c-4ec2ac4ca5b1.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66265140-77974080-e811-11e9-8f4b-c4e967568f3e.png)
https://user-images.githubusercontent.com/2068130/66265140-77974080-e811-11e9-8f4b-c4e967568f3e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66265144-87168980-e811-11e9-9bef-d3800930c9b5.png
