### ISSUE TITLE
Watcht for Trakt

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10429]
**App Name:** Watcht for Trakt
**Bundle ID:** com.tysonkerridge.Watcht
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1396920723">1396920723</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/watcht-for-trakt/id1396920723?uo=4">https://apps.apple.com/us/app/watcht-for-trakt/id1396920723?uo=4</a>
**App Version:** 1.14
**Seller:** Tyson Kerridge
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tyson-kerridge/id1396920722?uo=4">© Tyson Kerridge</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/4c/ae/6d/4cae6d89-d209-a5af-0b5f-d33047e00508/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/66069468-ba29f600-e54f-11e9-8475-6c42eb9949cf.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/66069468-ba29f600-e54f-11e9-8475-6c42eb9949cf.png)
https://user-images.githubusercontent.com/20930745/66069468-ba29f600-e54f-11e9-8475-6c42eb9949cf.png

Source:
https://user-images.githubusercontent.com/20930745/66069475-bc8c5000-e54f-11e9-8089-606f141b8351.png
