### ISSUE TITLE
DR VR 360 video

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10436]
**App Name:** DR VR 360 video
**Bundle ID:** dk.dr.vr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1227747356">1227747356</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dr-vr-360-video/id1227747356?uo=4">https://apps.apple.com/us/app/dr-vr-360-video/id1227747356?uo=4</a>
**App Version:** 1.0.1
**Seller:** DR
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dr/id327331170?uo=4">© DR</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple91/v4/76/55/25/76552526-9147-3f8e-87d6-1a28fa8fd793/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66266518-81776e80-e826-11e9-8705-1e3a92f9f6c9.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/66262745-1fe3df80-e7e7-11e9-94d0-b681377e27da.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/66262745-1fe3df80-e7e7-11e9-94d0-b681377e27da.png)

Source

https://user-images.githubusercontent.com/28823252/66262782-9ed91800-e7e7-11e9-839b-7a03fcfa8266.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66266518-81776e80-e826-11e9-8705-1e3a92f9f6c9.png)
https://user-images.githubusercontent.com/2068130/66266518-81776e80-e826-11e9-8705-1e3a92f9f6c9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66266523-8fc58a80-e826-11e9-94cf-ef10d1b49a45.png
