### ISSUE TITLE
DRTV

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10435]
**App Name:** DRTV
**Bundle ID:** dk.dr.tv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=877604999">877604999</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/drtv/id877604999?uo=4">https://apps.apple.com/us/app/drtv/id877604999?uo=4</a>
**App Version:** 3.0.2
**Seller:** DR
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dr/id327331170?uo=4">© DR</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/79/18/dc/7918dc69-4836-aa36-106a-554110c533a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69478786-b485b980-0df6-11ea-8aeb-9f86b405c5d5.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/66262577-91ba2a00-e7e3-11e9-97b4-8a87a181d116.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/66262577-91ba2a00-e7e3-11e9-97b4-8a87a181d116.png)

Source:

https://user-images.githubusercontent.com/28823252/66262588-bca47e00-e7e3-11e9-84f4-0cdc5bc33508.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66266444-6eb06a00-e825-11e9-9950-c16cdfd3447f.png)
https://user-images.githubusercontent.com/2068130/66266444-6eb06a00-e825-11e9-9950-c16cdfd3447f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66266450-7cfe8600-e825-11e9-8131-8de5cf5c8702.png

**Comment by cassio299** [comment]
ff

**Comment by cassio299** [comment]
[DUPLICATE of #10435]
**App Name:** DRTV
**Bundle ID:** dk.dr.tv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=877604999">877604999</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/drtv/id877604999?uo=4">https://apps.apple.com/us/app/drtv/id877604999?uo=4</a>
**App Version:** 3.0.2
**Seller:** DR
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dr/id327331170?uo=4">© DR</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/79/18/dc/7918dc69-4836-aa36-106a-554110c533a5/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69478786-b485b980-0df6-11ea-8aeb-9f86b405c5d5.png)
https://user-images.githubusercontent.com/20930745/69478786-b485b980-0df6-11ea-8aeb-9f86b405c5d5.png

Source:
https://user-images.githubusercontent.com/20930745/69478788-b5b6e680-0df6-11ea-8083-1656237fae0c.png
