### ISSUE TITLE
TickTick: Things & Tasks To Do

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10430]
**App Name:** TickTick: Things & Tasks To Do
**Bundle ID:** com.TickTick.task
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=626144601">626144601</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ticktick-things-tasks-to-do/id626144601?uo=4">https://apps.apple.com/us/app/ticktick-things-tasks-to-do/id626144601?uo=4</a>
**App Version:** 5.2.51
**Seller:** Appest Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/appest-limited/id434073155?uo=4">© Appest Limited</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/52/e4/d2/52e4d201-8710-83bf-b2de-5508871aef33/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/66068788-86020580-e54e-11e9-99b6-62cd57aa0b1f.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/66068788-86020580-e54e-11e9-99b6-62cd57aa0b1f.png)
https://user-images.githubusercontent.com/20930745/66068788-86020580-e54e-11e9-99b6-62cd57aa0b1f.png

Source:
https://user-images.githubusercontent.com/20930745/66068795-87cbc900-e54e-11e9-8d22-b07cf316ff93.png
