### ISSUE TITLE
Gyldendal's English Danish Dictionary - Mini

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10439]
**App Name:** Gyldendal's English Danish Dictionary - Mini
**Bundle ID:** dk.letsoftware.GyldendalsEngelskMini
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338683872">338683872</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gyldendals-english-danish-dictionary-mini/id338683872?uo=4">https://apps.apple.com/us/app/gyldendals-english-danish-dictionary-mini/id338683872?uo=4</a>
**App Version:** 2.4.1
**Seller:** Gyldendalske Boghandel Nordisk Forlag A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gyldendal/id370340254?uo=4">© Gyldendal</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, Watch5-Watch5, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/b9/4d/61/b94d619f-873c-a8eb-cbac-cf4570bac4a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67155228-4fc4d400-f30b-11e9-842f-6ab056abd942.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/66263305-d4363380-e7f0-11e9-8181-3b16c6ff4022.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/66263305-d4363380-e7f0-11e9-8181-3b16c6ff4022.png)

Source

https://user-images.githubusercontent.com/28823252/66263328-25462780-e7f1-11e9-97dd-fe73c5433a49.png

**Comment by dreamnet** [comment]
Same as #10437.
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66266641-fbf4be00-e827-11e9-8425-3086ed403b4a.png)
https://user-images.githubusercontent.com/2068130/66266641-fbf4be00-e827-11e9-8425-3086ed403b4a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66266643-09aa4380-e828-11e9-9240-cd82721d20a4.png

**Comment by dreamnet** [comment]
Same as #10437.
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67155228-4fc4d400-f30b-11e9-842f-6ab056abd942.png)
https://user-images.githubusercontent.com/2068130/67155228-4fc4d400-f30b-11e9-842f-6ab056abd942.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/67155235-610de080-f30b-11e9-9d06-135fba152db9.png
