### ISSUE TITLE
DR Radio

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10434]
**App Name:** DR Radio
**Bundle ID:** dk.dr.radioapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=433155921">433155921</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dr-radio/id433155921?uo=4">https://apps.apple.com/us/app/dr-radio/id433155921?uo=4</a>
**App Version:** 6.4.0
**Seller:** DR
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dr/id327331170?uo=4">© DR</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/7e/82/a9/7e82a96d-b66b-f06e-71e2-a4be811fd327/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66266388-ba164880-e824-11e9-9832-bd8598b0a843.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/66262525-5d923980-e7e2-11e9-9c3b-1717bb89c650.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/66262525-5d923980-e7e2-11e9-9c3b-1717bb89c650.png)

Source:

https://user-images.githubusercontent.com/28823252/66262532-8ca8ab00-e7e2-11e9-8c31-385827a71e9f.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66266388-ba164880-e824-11e9-9832-bd8598b0a843.png)
https://user-images.githubusercontent.com/2068130/66266388-ba164880-e824-11e9-9832-bd8598b0a843.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66266389-c8646480-e824-11e9-9cc5-0fdd475e1c62.png
