### ISSUE TITLE
Mjam.at - Online Food Delivery

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#10433]
**App Name:** Mjam.at - Online Food Delivery
**Bundle ID:** net.mjam.iPhoneApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=488694956">488694956</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mjam-at-online-food-delivery/id488694956?uo=4">https://apps.apple.com/us/app/mjam-at-online-food-delivery/id488694956?uo=4</a>
**App Version:** 6.7.1
**Seller:** Mjam GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mjam-net/id315206539?uo=4">© Mjam.net</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/95/db/15/95db151d-f73b-d71a-fedb-c224919dd3b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/66069778-5227df80-e550-11e9-9220-66476b8677d3.png)

**Comment by 2Qt2beStr8** [comment]
![-large](https://user-images.githubusercontent.com/20930745/66069778-5227df80-e550-11e9-9220-66476b8677d3.png)
https://user-images.githubusercontent.com/20930745/66069778-5227df80-e550-11e9-9220-66476b8677d3.png

Source:
https://user-images.githubusercontent.com/20930745/66069781-53590c80-e550-11e9-9c57-da712cc73821.png
