### ISSUE TITLE
Allegory

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10431]
**App Name:** Allegory
**Bundle ID:** com.shi.Allegory
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1470828583">1470828583</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/allegory/id1470828583?uo=4">https://apps.apple.com/us/app/allegory/id1470828583?uo=4</a>
**App Version:** 1.0.3
**Seller:** Shihab Mehboob
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shihab-mehboob/id1012903170?uo=4">© Shihab Mehboob</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/32/1a/b1/321ab199-c890-7ac3-1092-f3374302a477/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/66068387-c7de7c00-e54d-11e9-882e-20e9b170b791.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/66068387-c7de7c00-e54d-11e9-882e-20e9b170b791.png)
https://user-images.githubusercontent.com/20930745/66068387-c7de7c00-e54d-11e9-882e-20e9b170b791.png

Source:
https://user-images.githubusercontent.com/20930745/66068390-c9a83f80-e54d-11e9-9596-ef73cf27efee.png
