### ISSUE TITLE
Ventusky: Weather Maps

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10432]
**App Name:** Ventusky: Weather Maps
**Bundle ID:** com.in-meteo.ventusky
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1280984498">1280984498</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ventusky-weather-maps/id1280984498?uo=4">https://apps.apple.com/us/app/ventusky-weather-maps/id1280984498?uo=4</a>
**App Version:** 8.3
**Seller:** InMeteo, s.r.o.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/inmeteo-s-r-o/id459397801?uo=4">© InMeteo, s.r.o.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/13/4c/ec/134cec54-a07f-c637-4c9f-071eab54329c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/66067962-fb6cd680-e54c-11e9-92e6-2604bce7cee0.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/66067962-fb6cd680-e54c-11e9-92e6-2604bce7cee0.png)
(https://user-images.githubusercontent.com/20930745/66067962-fb6cd680-e54c-11e9-92e6-2604bce7cee0.png

Source:
https://user-images.githubusercontent.com/20930745/66068010-16d7e180-e54d-11e9-9856-608476d43952.png
