### ISSUE TITLE
Gyldendal's Italian Danish Dictionary

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10448]
**App Name:** Gyldendal's Italian Danish Dictionary
**Bundle ID:** dk.gyldendal.ItalienskOrdbog
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476873771">476873771</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gyldendals-italian-danish-dictionary/id476873771?uo=4">https://apps.apple.com/us/app/gyldendals-italian-danish-dictionary/id476873771?uo=4</a>
**App Version:** 2.4
**Seller:** Gyldendalske Boghandel Nordisk Forlag A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gyldendal/id370340254?uo=4">© Gyldendal</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, Watch5-Watch5, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/f1/64/1d/f1641d49-7aa6-5c02-12dd-e768ea12f6ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67155600-c6b19b00-f312-11e9-89cc-2497eb2089f5.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67155600-c6b19b00-f312-11e9-89cc-2497eb2089f5.png)
https://user-images.githubusercontent.com/2068130/67155600-c6b19b00-f312-11e9-89cc-2497eb2089f5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/67155606-d630e400-f312-11e9-8e45-706eb6a37109.png
