### ISSUE TITLE
Ferrite Recording Studio

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10441]
**App Name:** Ferrite Recording Studio
**Bundle ID:** com.woojijuice.Ferrite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1018780185">1018780185</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ferrite-recording-studio/id1018780185?uo=4">https://apps.apple.com/us/app/ferrite-recording-studio/id1018780185?uo=4</a>
**App Version:** 2.3.2
**Seller:** Wooji Juice Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wooji-juice-ltd/id284937604?uo=4">© Wooji Juice Ltd</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/c2/df/80/c2df80bf-be2c-637a-26bf-30a5c649e600/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66269557-09bb3b00-e84a-11e9-88c6-09ec3b95f7f8.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/66263399-b2d64700-e7f2-11e9-8c9b-b593bceb37e2.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/66263399-b2d64700-e7f2-11e9-8c9b-b593bceb37e2.png)

Source

https://user-images.githubusercontent.com/28823252/66263446-1a8c9200-e7f3-11e9-8b73-34b7079ab38e.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66269557-09bb3b00-e84a-11e9-88c6-09ec3b95f7f8.png)
https://user-images.githubusercontent.com/2068130/66269557-09bb3b00-e84a-11e9-88c6-09ec3b95f7f8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66269571-1cce0b00-e84a-11e9-8fb7-d568453657a1.png
