### ISSUE TITLE
Poison-202 Vintage Synthesizer

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10442]
**App Name:** Poison-202 Vintage Synthesizer
**Bundle ID:** com.xpeerio.poison
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1145895278">1145895278</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/poison-202-vintage-synthesizer/id1145895278?uo=4">https://apps.apple.com/us/app/poison-202-vintage-synthesizer/id1145895278?uo=4</a>
**App Version:** 2.4.5
**Seller:** Dmitrij Pavlov
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dmitrij-pavlov/id478154322?uo=4">© Dmitrij Pavlov</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/f5/2c/a2/f52ca2b7-0382-a10a-f1fc-cbcec9a9b9d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66269617-d62ce080-e84a-11e9-943d-e51008554f36.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/66263535-ae129280-e7f4-11e9-924c-ad95ff1917ca.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/66263535-ae129280-e7f4-11e9-924c-ad95ff1917ca.png)

Source

https://user-images.githubusercontent.com/28823252/66263552-0ba6df00-e7f5-11e9-870c-091f4c66eae4.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66269617-d62ce080-e84a-11e9-943d-e51008554f36.png)
https://user-images.githubusercontent.com/2068130/66269617-d62ce080-e84a-11e9-943d-e51008554f36.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66269621-e5ac2980-e84a-11e9-81a0-fbb28353ef79.png
