### ISSUE TITLE
Volvo on Call

### ISSUE THREAD

**Issue by Swedie** [glasklart/hd#1044]
**App Name:** Volvo On Call
**Bundle ID:** com.volvocars.onCall
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=439635293">439635293</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/volvo-on-call/id439635293?mt=8&uo=4">https://itunes.apple.com/us/app/volvo-on-call/id439635293?mt=8&uo=4</a>
**App Version:** 4.1.4
**Seller:** Volvo Car Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/volvo-car-corporation/id408840552?uo=4">© Volvo Car Corporation</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/9a/49/25/9a492523-a8de-9cfd-5bbf-3b33cf132d85/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32392214-fc8da650-c0d4-11e7-9528-ddfdbe5874d6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32392214-fc8da650-c0d4-11e7-9528-ddfdbe5874d6.png)
https://user-images.githubusercontent.com/2068130/32392214-fc8da650-c0d4-11e7-9528-ddfdbe5874d6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32392222-0c0428a2-c0d5-11e7-9c41-80f8f066689b.png
