### ISSUE TITLE
Pro Metronome - Tempo,Beat,Subdivision,Polyrhythm

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10443]
**App Name:** Pro Metronome - Tempo,Beat,Subdivision,Polyrhythm
**Bundle ID:** com.xiaoyixiang.prometronome
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=477960671">477960671</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pro-metronome-tempo-beat-subdivision-polyrhythm/id477960671?uo=4">https://apps.apple.com/us/app/pro-metronome-tempo-beat-subdivision-polyrhythm/id477960671?uo=4</a>
**App Version:** 3.13.2
**Seller:** Xiao Yixiang
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/xiao-yixiang/id435417444?uo=4">© Xiao Yixiang</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple1/v4/76/90/7d/76907d68-a7bc-01b2-b360-65983c3296bb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66696139-93935a00-ecc9-11e9-81f8-9c5a4d837159.png)

**Comment by cassio299** [comment]
https://user-images.githubusercontent.com/28823252/66263762-88878800-e7f8-11e9-8966-4038ffe6daf0.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/66263762-88878800-e7f8-11e9-8966-4038ffe6daf0.png

Source:

https://user-images.githubusercontent.com/28823252/66263770-c5537f00-e7f8-11e9-8dcb-9e31a9760ecb.png

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/66695670-c1c26b00-ecc4-11e9-8fd7-2d0fc7a2ccbd.png)
https://user-images.githubusercontent.com/20930745/66695670-c1c26b00-ecc4-11e9-8fd7-2d0fc7a2ccbd.png

Source:
https://user-images.githubusercontent.com/20930745/66695672-c38c2e80-ecc4-11e9-8f12-589a235b4a3c.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Way better. 👍 Just did some small corrections/additions:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66696139-93935a00-ecc9-11e9-81f8-9c5a4d837159.png)
https://user-images.githubusercontent.com/2068130/66696139-93935a00-ecc9-11e9-81f8-9c5a4d837159.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66696145-a7d75700-ecc9-11e9-97e0-fcfad9c7574a.png
