### ISSUE TITLE
Gyldendal's Swedish Danish Dictionary

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10446]
**App Name:** Gyldendal's Swedish Danish Dictionary
**Bundle ID:** dk.gyldendal.SvenskOrdbog
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=645043720">645043720</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gyldendals-swedish-danish-dictionary/id645043720?uo=4">https://apps.apple.com/us/app/gyldendals-swedish-danish-dictionary/id645043720?uo=4</a>
**App Version:** 2.4
**Seller:** Gyldendalske Boghandel Nordisk Forlag A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gyldendal/id370340254?uo=4">© Gyldendal</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, Watch5-Watch5, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/24/35/7d/24357d53-5e5b-363a-e390-5556534b8c3a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67155660-b1893c00-f313-11e9-9e38-8e16c5d0ec9e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67155660-b1893c00-f313-11e9-9e38-8e16c5d0ec9e.png)
https://user-images.githubusercontent.com/2068130/67155660-b1893c00-f313-11e9-9e38-8e16c5d0ec9e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/67155666-c1a11b80-f313-11e9-9359-57420b6f95d5.png
