### ISSUE TITLE
TV 2 SPORT

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10444]
**App Name:** TV 2 SPORT
**Bundle ID:** dk.tv2.sportcenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525709403">525709403</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tv-2-sport/id525709403?uo=4">https://apps.apple.com/us/app/tv-2-sport/id525709403?uo=4</a>
**App Version:** 4.5.4
**Seller:** TV 2 Danmark A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tv-2-danmark-a-s/id431851124?uo=4">© TV 2 Danmark A/S</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/a9/3a/9d/a93a9dd5-4f0b-f8bf-2e94-c10c8f20ba18/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67156049-0def5a00-f31a-11e9-90da-7ddcf1ff259a.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67093011-f47ece80-f1b0-11e9-95c1-32dc4c3529ac.png)
https://user-images.githubusercontent.com/20930745/67093011-f47ece80-f1b0-11e9-95c1-32dc4c3529ac.png

Source:
https://user-images.githubusercontent.com/20930745/67093016-f6489200-f1b0-11e9-9178-c4a64aef0af8.png
