### ISSUE TITLE
Doodle Jump - Insanely Good!

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10459]
**App Name:** Doodle Jump - Insanely Good!
**Bundle ID:** com.limasky.doodlejumpfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=456355158">456355158</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/doodle-jump-insanely-good/id456355158?uo=4">https://apps.apple.com/us/app/doodle-jump-insanely-good/id456355158?uo=4</a>
**App Version:** 2.77.1
**Seller:** Lima Sky
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lima-sky/id285874818?uo=4">© Lima Sky</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/c6/a4/99/c6a49941-50e7-8414-d029-5a22bd4d9da5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70370236-ea31a480-18c4-11ea-9ab0-c683ef5ca00e.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70370236-ea31a480-18c4-11ea-9ab0-c683ef5ca00e.png)
https://user-images.githubusercontent.com/20930745/70370236-ea31a480-18c4-11ea-9ab0-c683ef5ca00e.png

Source:
https://user-images.githubusercontent.com/20930745/70370237-ebfb6800-18c4-11ea-9eec-4a3ea19e9b3d.png
