### ISSUE TITLE
Cut the Rope

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10458]
**App Name:** Cut the Rope
**Bundle ID:** com.zeptolab.cuttheropelite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1024506959">1024506959</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cut-the-rope/id1024506959?uo=4">https://apps.apple.com/us/app/cut-the-rope/id1024506959?uo=4</a>
**App Version:** 3.15.2
**Seller:** ZeptoLab UK Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/zeptolab-uk-limited/id450542236?uo=4">© ZeptoLab UK Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/c2/d1/40/c2d140eb-2420-e796-b896-8eb329a25517/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67147904-98dc4000-f299-11e9-8a73-fd078849b9bc.png)

**Comment by dreamnet** [comment]
Same as #7597. Icon by @ivanov007.
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67147904-98dc4000-f299-11e9-8a73-fd078849b9bc.png)
https://user-images.githubusercontent.com/2068130/67147904-98dc4000-f299-11e9-8a73-fd078849b9bc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/67147910-aabde300-f299-11e9-9555-675f3f1435bf.png
