### ISSUE TITLE
Pokémon Masters

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10457]
**App Name:** Pokémon Masters
**Bundle ID:** com.dena.12026418
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1442061397">1442061397</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pok%C3%A9mon-masters/id1442061397?uo=4">https://apps.apple.com/us/app/pok%C3%A9mon-masters/id1442061397?uo=4</a>
**App Version:** 1.2.1
**Seller:** DeNA Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dena-co-ltd/id431078943?uo=4">© DeNA Co., Ltd.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/82/34/3b/82343b07-7644-8692-6ce9-1ca771a1caa1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69911266-3ab68700-1419-11ea-8d26-11a686f74534.png)

**Comment by dreamnet** [comment]
❓ 
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69911266-3ab68700-1419-11ea-8d26-11a686f74534.png)
https://user-images.githubusercontent.com/2068130/69911266-3ab68700-1419-11ea-8d26-11a686f74534.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/69911269-4efa8400-1419-11ea-905e-4f38997b7ac9.png

**Comment by dreamnet** [comment]
or... ❓ 
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71320340-3cb8b680-24aa-11ea-8158-c6f6e8e42c9f.png)
https://user-images.githubusercontent.com/2068130/71320340-3cb8b680-24aa-11ea-8158-c6f6e8e42c9f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71320343-4b9f6900-24aa-11ea-8d7f-7310b3043e17.png

**Comment by Christian9901** [comment]
first
