### ISSUE TITLE
Flying Gorilla

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10456]
**App Name:** Flying Gorilla
**Bundle ID:** jp.pinbit.flygorilla
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1365028549">1365028549</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/flying-gorilla/id1365028549?uo=4">https://apps.apple.com/us/app/flying-gorilla/id1365028549?uo=4</a>
**App Version:** 2.82
**Seller:** Kazutaka Tottori
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kazutaka-tottori/id1054773329?uo=4">© Kazutaka Tottori</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/f2/3c/0b/f23c0bc7-a477-ab03-5319-5b6e867cd295/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67632064-9338b880-f89e-11e9-8fbd-e12985059aeb.png)

**Comment by dreamnet** [comment]
❓ 
![jp pinbit flygorilla-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67632064-9338b880-f89e-11e9-8fbd-e12985059aeb.png)
https://user-images.githubusercontent.com/2068130/67632064-9338b880-f89e-11e9-8fbd-e12985059aeb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/67632066-a8ade280-f89e-11e9-9ed5-232ff6d48ed4.png
