### ISSUE TITLE
Meyers Fremmedordbog

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10451]
**App Name:** Meyers Fremmedordbog
**Bundle ID:** dk.dsl.ordnet.Meyers-Fremmedordbog
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942659551">942659551</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/meyers-fremmedordbog/id942659551?uo=4">https://apps.apple.com/us/app/meyers-fremmedordbog/id942659551?uo=4</a>
**App Version:** 2.1.2
**Seller:** Det Danske Sprog- og Litteraturselskab
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/det-danske-sprog-og-litteraturselskab/id651992467?uo=4">© Det Danske Sprog- og Litteraturselskab</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/61/5f/94/615f94e6-18b6-57ee-e066-a4d44ad914ec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67095567-83dab080-f1b6-11e9-9232-6409661c7031.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67095567-83dab080-f1b6-11e9-9232-6409661c7031.png)
https://user-images.githubusercontent.com/20930745/67095567-83dab080-f1b6-11e9-9232-6409661c7031.png

Source:
https://user-images.githubusercontent.com/20930745/67095572-85a47400-f1b6-11e9-9b48-5a595cdb71dc.png
