### ISSUE TITLE
HealthFit

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10454]
**App Name:** HealthFit
**Bundle ID:** com.altifondo.HealthFit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1202650514">1202650514</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/healthfit/id1202650514?uo=4">https://apps.apple.com/us/app/healthfit/id1202650514?uo=4</a>
**App Version:** 5.0.4
**Seller:** Stephane Lizeray
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/stephane-lizeray/id617677771?uo=4">© Stephane Lizeray</a>
**Supported Devices:** iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/82/f3/d2/82f3d2e1-e9c9-5a1f-611f-0c405ee1dd93/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67096657-eb91fb00-f1b8-11e9-8dfb-f671af0541ea.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67096657-eb91fb00-f1b8-11e9-8dfb-f671af0541ea.png)
(https://user-images.githubusercontent.com/20930745/67096657-eb91fb00-f1b8-11e9-8dfb-f671af0541ea.png

Source:
https://user-images.githubusercontent.com/20930745/67096665-edf45500-f1b8-11e9-8d92-dc42329295df.png
