### ISSUE TITLE
SFO

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10453]
**App Name:** SFO
**Bundle ID:** com.sfo.appstore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1334003993">1334003993</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sfo/id1334003993?uo=4">https://apps.apple.com/us/app/sfo/id1334003993?uo=4</a>
**App Version:** 1.0
**Seller:** Shenzhen Quanshunda Electronic Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/%E6%B7%B1%E5%9C%B3%E5%B8%82%E5%85%A8%E9%A1%BA%E8%BE%BE%E7%94%B5%E5%AD%90%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/id1048838910?uo=4">© 深圳市全顺达电子有限公司</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/39/f7/f5/39f7f523-da9e-a39d-f025-081c60aa2d90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67096344-3cedba80-f1b8-11e9-9ee5-81def06ac687.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67096344-3cedba80-f1b8-11e9-9ee5-81def06ac687.png)
https://user-images.githubusercontent.com/20930745/67096344-3cedba80-f1b8-11e9-9ee5-81def06ac687.png

Source:
https://user-images.githubusercontent.com/20930745/67096346-3f501480-f1b8-11e9-80ff-ab7900544e0d.png
