### ISSUE TITLE
Noted․

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10461]
**App Name:** Noted․
**Bundle ID:** com.digitalworkroom.noted
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1149425482">1149425482</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/noted/id1149425482?uo=4">https://apps.apple.com/us/app/noted/id1149425482?uo=4</a>
**App Version:** 2.0.4
**Seller:** Digital Workroom Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/digital-workroom-ltd/id941209527?uo=4">© Digital Workroom Ltd</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/65/ad/8a/65ad8a8e-08d5-34bc-cc36-92f71c942c00/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67634306-55498d80-f8ba-11e9-9c27-1d650841c71c.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=(https://user-images.githubusercontent.com/20930745/67634306-55498d80-f8ba-11e9-9c27-1d650841c71c.png)
https://user-images.githubusercontent.com/20930745/67634306-55498d80-f8ba-11e9-9c27-1d650841c71c.png

Source:
https://user-images.githubusercontent.com/20930745/67634307-57135100-f8ba-11e9-9fe4-be468cfc9c2a.png
