### ISSUE TITLE
Pokémon Duel

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10460]
**App Name:** Pokémon Duel
**Bundle ID:** jp.pokemon.pokemoncomaster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1078819328">1078819328</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pok%C3%A9mon-duel/id1078819328?uo=4">https://apps.apple.com/us/app/pok%C3%A9mon-duel/id1078819328?uo=4</a>
**App Version:** 7.0.16
**Seller:** The Pokemon Company
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-pokemon-company/id446737235?uo=4">© The Pokemon Company</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/07/d0/16/07d016ce-84e2-73b1-d5d3-68b499fab8e7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73598676-bd53e380-453b-11ea-9a98-df9834e6b002.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73598676-bd53e380-453b-11ea-9a98-df9834e6b002.png)
https://user-images.githubusercontent.com/2068130/73598676-bd53e380-453b-11ea-9a98-df9834e6b002.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73598678-cb096900-453b-11ea-8d7a-51c7818f1b87.png
