### ISSUE TITLE
MyShake-UC Berkeley Seismology

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10463]
**App Name:** MyShake-UC Berkeley Seismology
**Bundle ID:** edu.berkeley.bsl.MyShake
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1467058529">1467058529</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myshake-uc-berkeley-seismology/id1467058529?uo=4">https://apps.apple.com/us/app/myshake-uc-berkeley-seismology/id1467058529?uo=4</a>
**App Version:** 3.0.102
**Seller:** University of California, Berkeley
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/university-of-california-berkeley/id413373017?uo=4">© University of California, Berkeley</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/2e/11/2c/2e112ca1-fe67-35ac-432d-1ddee3dfcea6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67156305-054c5300-f31d-11e9-8ffa-313688a8cf56.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67156305-054c5300-f31d-11e9-8ffa-313688a8cf56.png)
https://user-images.githubusercontent.com/2068130/67156305-054c5300-f31d-11e9-8ffa-313688a8cf56.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/67156312-15643280-f31d-11e9-91cd-6e245cf496f0.png
