### ISSUE TITLE
Rapid Ring

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10462]
**App Name:** Rapid Ring
**Bundle ID:** com.ring.answer.prod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1462775976">1462775976</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/rapid-ring/id1462775976?uo=4">https://apps.apple.com/us/app/rapid-ring/id1462775976?uo=4</a>
**App Version:** 1.4.5
**Seller:** Bot Home Automation, INC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ring-com/id926252660?uo=4">© Ring.com</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/bd/b7/1e/bdb71e56-07cc-29be-ec62-17a75ce77af4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67099131-a91eed00-f1bd-11e9-94b2-5eec740f6fb6.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67099131-a91eed00-f1bd-11e9-94b2-5eec740f6fb6.png)
https://user-images.githubusercontent.com/20930745/67099131-a91eed00-f1bd-11e9-94b2-5eec740f6fb6.png

Source:
https://user-images.githubusercontent.com/20930745/67099136-aae8b080-f1bd-11e9-840e-54ab83d594f3.png
