### ISSUE TITLE
Brusfri

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10479]
**App Name:** Brusfri
**Bundle ID:** com.klevgrand.Brusfri
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1289165912">1289165912</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/brusfri/id1289165912?uo=4">https://apps.apple.com/us/app/brusfri/id1289165912?uo=4</a>
**App Version:** 1.1.0
**Seller:** Klevgrand Produkter AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/klevgr%C3%A4nd-produkter-ab/id1118902192?uo=4">© Klevgränd produkter AB</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/54/69/be/5469be7a-cf98-417a-c829-8f36a6638fc1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67630715-7abfa280-f88c-11e9-9d0c-149ff36eea86.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67299320-cbca4200-f4ec-11e9-89e6-190d847525dc.png)
(https://user-images.githubusercontent.com/20930745/67299320-cbca4200-f4ec-11e9-89e6-190d847525dc.png

Source:
https://user-images.githubusercontent.com/20930745/67299347-d684d700-f4ec-11e9-833f-a22594a502c9.png

**Comment by 2Qt2beStr8** [comment]
second try ?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67630634-27992000-f88b-11e9-9d8d-072b99608dbd.png)
https://user-images.githubusercontent.com/20930745/67630634-27992000-f88b-11e9-9d8d-072b99608dbd.png

Source:
![brusfri1](https://user-images.githubusercontent.com/20930745/67630636-2c5dd400-f88b-11e9-9caa-d92f1bc5b119.png)
