### ISSUE TITLE
Wizibel - Audio Visualizer

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10475]
**App Name:** Wizibel - Audio Visualizer
**Bundle ID:** com.klevgrand.visualmusicexporter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1169944763">1169944763</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wizibel-audio-visualizer/id1169944763?uo=4">https://apps.apple.com/us/app/wizibel-audio-visualizer/id1169944763?uo=4</a>
**App Version:** 1.4.2
**Seller:** Klevgrand Produkter AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/klevgr%C3%A4nd-produkter-ab/id1118902192?uo=4">© Klevgränd produkter AB</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/cd/70/8d/cd708d2e-33ca-7900-f36f-f2f68f31da40/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67634168-c25c2380-f8b8-11e9-8c6d-bd61e4e11cb1.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67634168-c25c2380-f8b8-11e9-8c6d-bd61e4e11cb1.png)
https://user-images.githubusercontent.com/20930745/67634168-c25c2380-f8b8-11e9-8c6d-bd61e4e11cb1.png

Source:
https://user-images.githubusercontent.com/20930745/67634169-c425e700-f8b8-11e9-83c2-282b5bf869de.png
