### ISSUE TITLE
Jubal Flute

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10477]
**App Name:** Jubal Flute
**Bundle ID:** com.embertone.JubalFlute
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1264401321">1264401321</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/jubal-flute/id1264401321?uo=4">https://apps.apple.com/us/app/jubal-flute/id1264401321?uo=4</a>
**App Version:** 1.0.3
**Seller:** Embertone LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/embertone/id1186361515?uo=4">© Embertone</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/8d/9a/37/8d9a377a-15e0-f4b9-9fd0-ce2666113c02/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68083570-6ea68880-fe2a-11e9-8373-7cd778c95089.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68083570-6ea68880-fe2a-11e9-8373-7cd778c95089.png)
https://user-images.githubusercontent.com/2068130/68083570-6ea68880-fe2a-11e9-8373-7cd778c95089.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/68083575-7fef9500-fe2a-11e9-8c2b-6bad9056b9e1.png
