### ISSUE TITLE
Stylish Sprint

### ISSUE THREAD

**Issue by ianlegend** [glasklart/hd#1048]
**App Name:** Stylish Sprint
**Bundle ID:** us.kr.stylishdash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390141259">390141259</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stylish-sprint/id390141259?mt=8&uo=4">https://itunes.apple.com/us/app/stylish-sprint/id390141259?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** playus soft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/playus-soft/id385988579?uo=4>© playus soft</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/bb/3e/0b/bb3e0bcb-eb86-3038-97d6-3f6edd32be92/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19858588/57abb83a-9f82-11e6-908f-b9b1a7ea781c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19858588/57abb83a-9f82-11e6-908f-b9b1a7ea781c.png)
https://cloud.githubusercontent.com/assets/20930745/19858588/57abb83a-9f82-11e6-908f-b9b1a7ea781c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19858620/76265a68-9f82-11e6-9925-96e3e750d68c.png
