### ISSUE TITLE
Kleverb

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10480]
**App Name:** Kleverb
**Bundle ID:** com.klevgrand.kleverb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1438836422">1438836422</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/kleverb/id1438836422?uo=4">https://apps.apple.com/us/app/kleverb/id1438836422?uo=4</a>
**App Version:** 1.0.0
**Seller:** Klevgrand Produkter AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/klevgr%C3%A4nd-produkter-ab/id1118902192?uo=4">© Klevgränd produkter AB</a>
**Supported Devices:** iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPad75-iPad75, iPad76-iPad76, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/43/5c/3b/435c3bb2-82c1-5f3a-df34-e6f0fe481159/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67295379-514af380-f4e7-11e9-8c52-0f2bb57ec01c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67295379-514af380-f4e7-11e9-8c52-0f2bb57ec01c.png)
https://user-images.githubusercontent.com/20930745/67295379-514af380-f4e7-11e9-8c52-0f2bb57ec01c.png

Source:
https://user-images.githubusercontent.com/20930745/67295384-53ad4d80-f4e7-11e9-9ab9-5d82a3be9f7c.png
