### ISSUE TITLE
Ai Search 2 - Batch Browser

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10484]
**App Name:** Ai Search 2 - Batch Browser
**Bundle ID:** com.yuanjing.airsearch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1301128732">1301128732</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ai-search-2-batch-browser/id1301128732?uo=4">https://apps.apple.com/us/app/ai-search-2-batch-browser/id1301128732?uo=4</a>
**App Version:** 2.0.4
**Seller:** Suzhou YuanJing Information Technology Co.,LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yuanjing-co-ltd/id1113361349?uo=4">© YuanJing Co.,Ltd.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/be/86/33/be86331b-25b8-1e13-172e-dc09e45ad88b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67292402-3fffe800-f4e3-11e9-8b7b-4c6de9bfae1d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67292402-3fffe800-f4e3-11e9-8b7b-4c6de9bfae1d.png)
(https://user-images.githubusercontent.com/20930745/67292402-3fffe800-f4e3-11e9-8b7b-4c6de9bfae1d.png

Source:
https://user-images.githubusercontent.com/20930745/67292406-41311500-f4e3-11e9-96ff-4b0ebba7efc4.png
