### ISSUE TITLE
FlashScore - live scores

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10486]
**App Name:** FlashScore - live scores
**Bundle ID:** eu.livesport.FlashScore-com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=766443283">766443283</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/flashscore-live-scores/id766443283?uo=4">https://apps.apple.com/us/app/flashscore-live-scores/id766443283?uo=4</a>
**App Version:** 4.4.2
**Seller:** Livesport s.r.o.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/livesport-s-r-o/id722265281?uo=4">© Livesport s.r.o.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/de/32/fc/de32fc5e-b5e2-70af-d156-85e3bd8d0a49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67291480-e2b76700-f4e1-11e9-847e-51fb43cb16d9.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67291480-e2b76700-f4e1-11e9-847e-51fb43cb16d9.png)
https://user-images.githubusercontent.com/20930745/67291480-e2b76700-f4e1-11e9-847e-51fb43cb16d9.png

Source:
https://user-images.githubusercontent.com/20930745/67291490-e4812a80-f4e1-11e9-89f9-60519457bd9b.png
