### ISSUE TITLE
Feed Hawk

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10483]
**App Name:** Feed Hawk
**Bundle ID:** com.goldenhillsoftware.FeedHawk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1093873777">1093873777</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/feed-hawk/id1093873777?uo=4">https://apps.apple.com/us/app/feed-hawk/id1093873777?uo=4</a>
**App Version:** 1.7.4
**Seller:** John Brayton
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/golden-hill-software/id404445480?uo=4">© Golden Hill Software</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/f1/3e/25/f13e25e9-3237-94ae-3521-c940030fc0f1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67292778-c0264d80-f4e3-11e9-8c5b-817cb5448ab6.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67292778-c0264d80-f4e3-11e9-8c5b-817cb5448ab6.png)
https://user-images.githubusercontent.com/20930745/67292778-c0264d80-f4e3-11e9-8c5b-817cb5448ab6.png

Source:
https://user-images.githubusercontent.com/20930745/67292780-c1577a80-f4e3-11e9-9e21-0d127ba07bfa.png
