### ISSUE TITLE
Brother iPrint&Label

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10489]
**App Name:** Brother iPrint&Label
**Bundle ID:** com.brother.iPrint-Label
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=523047493">523047493</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/brother-iprint-label/id523047493?uo=4">https://apps.apple.com/us/app/brother-iprint-label/id523047493?uo=4</a>
**App Version:** 5.2.6
**Seller:** Brother Industries, LTD.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/brother-industries-ltd/id382775645?uo=4">© Brother Industries, LTD.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/e7/ad/64/e7ad64c9-b6a0-9074-42f4-06ac00607147/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67630390-13532400-f887-11e9-8c1f-8b8ad623208c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67630390-13532400-f887-11e9-8c1f-8b8ad623208c.png)
(https://user-images.githubusercontent.com/20930745/67630390-13532400-f887-11e9-8c1f-8b8ad623208c.png

Source:
https://user-images.githubusercontent.com/20930745/67630391-14845100-f887-11e9-84b3-fdc3a2562bd3.png
