### ISSUE TITLE
Hohem Gimbal

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10482]
**App Name:** Hohem Gimbal
**Bundle ID:** com.hohem-tech.hohemgimbal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1458730704">1458730704</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hohem-gimbal/id1458730704?uo=4">https://apps.apple.com/us/app/hohem-gimbal/id1458730704?uo=4</a>
**App Version:** 1.0.22
**Seller:** Shenzhen Hohem Technology Co.,ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shenzhen-hohem-technology-co-ltd/id1196615122?uo=4">© Shenzhen Hohem Technology Co.,Ltd</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/dc/f8/b2/dcf8b2ef-503f-1971-cd13-0e43eec93316/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67293830-455e3200-f4e5-11e9-90ff-f5492418534c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67293830-455e3200-f4e5-11e9-90ff-f5492418534c.png)
https://user-images.githubusercontent.com/20930745/67293830-455e3200-f4e5-11e9-90ff-f5492418534c.png

Source:
https://user-images.githubusercontent.com/20930745/67293834-468f5f00-f4e5-11e9-8140-f3834744129f.png
