### ISSUE TITLE
Big Chungus

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10487]
**App Name:** Big Chungus
**Bundle ID:** com.bigchungues
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1451380171">1451380171</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/big-chungus/id1451380171?uo=4">https://apps.apple.com/us/app/big-chungus/id1451380171?uo=4</a>
**App Version:** 1.3
**Seller:** granny baldi
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/granny-baldi/id1450404071?uo=4">© granny baldi</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/39/57/83/3957833d-cd73-21e3-0cbb-7ceb3cd560a6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73201009-492ecf80-4138-11ea-9400-f19540328e26.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73201009-492ecf80-4138-11ea-9400-f19540328e26.png)
https://user-images.githubusercontent.com/20930745/73201009-492ecf80-4138-11ea-9400-f19540328e26.png

Source:
https://user-images.githubusercontent.com/20930745/73201011-4a5ffc80-4138-11ea-8e24-43313757d6c5.png
