### ISSUE TITLE
Popcorn Movies

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10499]
**App Name:** Popcorn Movies
**Bundle ID:** com.pomanks.apps.popcorn-movies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1400768489">1400768489</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/popcorn-movies/id1400768489?uo=4">https://apps.apple.com/us/app/popcorn-movies/id1400768489?uo=4</a>
**App Version:** 1.1.1
**Seller:** Antoine Barre
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/antoine-barre/id1155673297?uo=4">© Antoine Barre</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/ac/8e/3b/ac8e3b4c-3f9d-5998-8681-13208cfab5ad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69912741-d2be6b80-142d-11ea-89ac-a5530edeb8b9.png)

**Comment by dreamnet** [comment]
❓ 
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69912741-d2be6b80-142d-11ea-89ac-a5530edeb8b9.png)
https://user-images.githubusercontent.com/2068130/69912741-d2be6b80-142d-11ea-89ac-a5530edeb8b9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/69912749-e79aff00-142d-11ea-8627-92acfacb310b.png
