### ISSUE TITLE
Svep - phaser, flanger, chorus

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10492]
**App Name:** Svep - phaser, flanger, chorus
**Bundle ID:** com.klevgrand.Svep
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=940079014">940079014</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/svep-phaser-flanger-chorus/id940079014?uo=4">https://apps.apple.com/us/app/svep-phaser-flanger-chorus/id940079014?uo=4</a>
**App Version:** 1.1.1
**Seller:** Klevgrand Produkter AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/klevgr%C3%A4nd-produkter-ab/id1118902192?uo=4">© Klevgränd produkter AB</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPad75-iPad75, iPad76-iPad76, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple122/v4/b9/9e/4f/b99e4f9e-e7e1-fe95-1c9a-63d7a9d2d6a3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67629882-de8e9f00-f87d-11e9-9be2-0ffa1120c43e.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67629882-de8e9f00-f87d-11e9-9be2-0ffa1120c43e.png)
https://user-images.githubusercontent.com/20930745/67629882-de8e9f00-f87d-11e9-9be2-0ffa1120c43e.png

Source:
https://user-images.githubusercontent.com/20930745/67629883-e0586280-f87d-11e9-9038-661b01cd9db2.png
