### ISSUE TITLE
Mobilvarsling

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10495]
**App Name:** Mobilvarsling
**Bundle ID:** dk.beredskabsstyrelsen.varsling
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1082667799">1082667799</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mobilvarsling/id1082667799?uo=4">https://apps.apple.com/us/app/mobilvarsling/id1082667799?uo=4</a>
**App Version:** 1.3.5
**Seller:** Beredskabsstyrelsen
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/beredskabsstyrelsen/id661077034?uo=4">© Beredskabsstyrelsen</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax

**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/ee/29/56/ee2956bb-8c38-6e84-7ba3-efb98ded4dc5/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67629972-b30cb400-f87f-11e9-8d2a-4a397c258dae.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67629972-b30cb400-f87f-11e9-8d2a-4a397c258dae.png)
https://user-images.githubusercontent.com/20930745/67629972-b30cb400-f87f-11e9-8d2a-4a397c258dae.png

Source:
https://user-images.githubusercontent.com/20930745/67629974-b4d67780-f87f-11e9-9d29-0735bf8042e2.png
