### ISSUE TITLE
Pirates : Sea Battle 2

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#105]
**App Name:** Pirates : Sea Battle 2
**Bundle ID:** ru.idigger.sb2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=303548806">303548806</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pirates-sea-battle-2/id303548806?mt=8&uo=4">https://itunes.apple.com/us/app/pirates-sea-battle-2/id303548806?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Rashid Nasibulin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rashid-nasibulin/id286142168?uo=4>© Rashid Nasibulin</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/69/5b/ac/695bacae-1bb8-cad8-f182-cb8b0552541f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19625564/771c8d82-991c-11e6-9744-623633e60dcc.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19625564/771c8d82-991c-11e6-9744-623633e60dcc.png)
https://cloud.githubusercontent.com/assets/2068130/19625564/771c8d82-991c-11e6-9744-623633e60dcc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19625565/85556478-991c-11e6-9b48-7095cb147c09.png
