### ISSUE TITLE
Karolines Køkken® Opskrifter

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10505]
**App Name:** Karolines Køkken® Opskrifter
**Bundle ID:** dk.arla.Opskrifter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=456971962">456971962</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/karolines-k%C3%B8kken-opskrifter/id456971962?uo=4">https://apps.apple.com/us/app/karolines-k%C3%B8kken-opskrifter/id456971962?uo=4</a>
**App Version:** 7.4.0
**Seller:** Arla foods amba.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/arla-foods-amba/id426898312?uo=4">© Arla foods amba</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, Watch5-Watch5, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/11/b2/7a/11b27aee-0e02-ee8b-584c-26fcbe0ad676/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68184363-2197f300-ff9f-11e9-85c8-7e00d214c36d.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68184363-2197f300-ff9f-11e9-85c8-7e00d214c36d.png)
https://user-images.githubusercontent.com/2068130/68184363-2197f300-ff9f-11e9-85c8-7e00d214c36d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/68184394-307ea580-ff9f-11e9-9e7f-0c627420eb3a.png
