### ISSUE TITLE
PULS 24

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#10501]
**App Name:** PULS 24
**Bundle ID:** at.puls4.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=385942785">385942785</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/puls-24/id385942785?uo=4">https://apps.apple.com/de/app/puls-24/id385942785?uo=4</a>
**App Version:** 8.0.3
**Seller:** ProSiebenSat.1 PULS 4 GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/prosiebensat-1-puls-4-gmbh/id385942788?uo=4">© ProSiebenSat.1 PULS 4 GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/9f/ac/a2/9faca2c6-9f40-32d6-fda7-609c884f6105/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68083886-98fa4500-fe2e-11e9-988b-60d61d040dab.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68083886-98fa4500-fe2e-11e9-988b-60d61d040dab.png)
https://user-images.githubusercontent.com/2068130/68083886-98fa4500-fe2e-11e9-988b-60d61d040dab.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/68083892-a7e0f780-fe2e-11e9-82c1-817be6f00010.png
