### ISSUE TITLE
Ordbog over det danske Sprog

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10508]
**App Name:** Ordbog over det danske Sprog
**Bundle ID:** dk.dsl.ordnet.Ordbog-over-det-danske-Sprog
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=760987916">760987916</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ordbog-over-det-danske-sprog/id760987916?uo=4">https://apps.apple.com/us/app/ordbog-over-det-danske-sprog/id760987916?uo=4</a>
**App Version:** 2.1.2
**Seller:** Det Danske Sprog- og Litteraturselskab
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/det-danske-sprog-og-litteraturselskab/id651992467?uo=4">© Det Danske Sprog- og Litteraturselskab</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/85/13/b9/8513b9e9-8cb3-6737-40fc-f98e0d58eebc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68227443-00adbd00-fff4-11e9-9548-f603de7711b4.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68227443-00adbd00-fff4-11e9-9548-f603de7711b4.png)
https://user-images.githubusercontent.com/20930745/68227443-00adbd00-fff4-11e9-9548-f603de7711b4.png

Source:
https://user-images.githubusercontent.com/20930745/68227449-02778080-fff4-11e9-99dc-5719756d431e.png

**Comment by ivanov007** [comment]
wow that lion is almost invisible on the original artwork, nice work
