### ISSUE TITLE
min.medicin.dk

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10503]
**App Name:** min.medicin.dk
**Bundle ID:** dk.dli.minmedicindkmedicin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=927847332">927847332</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/min-medicin-dk/id927847332?uo=4">https://apps.apple.com/us/app/min-medicin-dk/id927847332?uo=4</a>
**App Version:** 1.3
**Seller:** DLI - Dansk Laegemiddel Information A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dli-dansk-l%C3%A6gemiddel-information-a-s/id470236969?uo=4">© DLI - Dansk Lægemiddel Information A/S</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, Watch5-Watch5, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/6d/03/e5/6d03e599-df9d-8e2b-678f-e22dee080320/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68183218-04adf080-ff9c-11e9-8c82-5dae2308c661.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68183218-04adf080-ff9c-11e9-8c82-5dae2308c661.png)
https://user-images.githubusercontent.com/2068130/68183218-04adf080-ff9c-11e9-8c82-5dae2308c661.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/68183240-155e6680-ff9c-11e9-9258-3187dce96ace.png
