### ISSUE TITLE
 Moths Ordbog

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10509]
**App Name:** Moths Ordbog
**Bundle ID:** dk.dsl.ordnet.Moths-Ordbog
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=760994884">760994884</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/moths-ordbog/id760994884?uo=4">https://apps.apple.com/us/app/moths-ordbog/id760994884?uo=4</a>
**App Version:** 2.1.2
**Seller:** Det Danske Sprog- og Litteraturselskab
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/det-danske-sprog-og-litteraturselskab/id651992467?uo=4">© Det Danske Sprog- og Litteraturselskab</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/8b/fa/d5/8bfad589-4815-c4db-2db8-a5c4fd36460c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68226834-0525a600-fff3-11e9-9427-6ff30b07f8b5.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68226834-0525a600-fff3-11e9-9427-6ff30b07f8b5.png)
https://user-images.githubusercontent.com/20930745/68226834-0525a600-fff3-11e9-9427-6ff30b07f8b5.png

Source:
https://user-images.githubusercontent.com/20930745/68226839-0656d300-fff3-11e9-8633-714bfac9f9dd.png
