### ISSUE TITLE
Foodie - Camera for life

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10515]
**App Name:** Foodie - Camera for life
**Bundle ID:** com.linecorp.Foodie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1076859004">1076859004</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/foodie-camera-for-life/id1076859004?uo=4">https://apps.apple.com/us/app/foodie-camera-for-life/id1076859004?uo=4</a>
**App Version:** 3.0.6
**Seller:** SNOW INC.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/snow-inc/id1244624324?uo=4">© SNOW INC.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/7a/a2/a3/7aa2a3f6-a16b-65a4-c2a7-8950794dec38/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68527182-8c6d6500-02e4-11ea-86dc-1912c26f516b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68527182-8c6d6500-02e4-11ea-86dc-1912c26f516b.png)
https://user-images.githubusercontent.com/20930745/68527182-8c6d6500-02e4-11ea-86dc-1912c26f516b.png

Source:
https://user-images.githubusercontent.com/20930745/68527184-8e372880-02e4-11ea-8447-4ea37866d84f.png
