### ISSUE TITLE
Cryptomator

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10516]
**App Name:** Cryptomator
**Bundle ID:** com.setolabs.Cryptomator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953086535">953086535</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cryptomator/id953086535?uo=4">https://apps.apple.com/us/app/cryptomator/id953086535?uo=4</a>
**App Version:** 1.4.3
**Seller:** Skymatic GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/skymatic-gmbh/id516387682?uo=4">© Skymatic GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/a7/34/a5/a734a5c1-8993-85a0-ec45-e30180a51e15/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68527110-a2c6f100-02e3-11ea-9a5f-148ecc6833ac.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68527110-a2c6f100-02e3-11ea-9a5f-148ecc6833ac.png)
https://user-images.githubusercontent.com/20930745/68527110-a2c6f100-02e3-11ea-9a5f-148ecc6833ac.png

Source:
https://user-images.githubusercontent.com/20930745/68527111-a490b480-02e3-11ea-9888-482cea558b02.png
