### ISSUE TITLE
SODA - Natural Beauty Camera

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10514]
**App Name:** SODA - Natural Beauty Camera
**Bundle ID:** com.snowcorp.soda
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1437880869">1437880869</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/soda-natural-beauty-camera/id1437880869?uo=4">https://apps.apple.com/us/app/soda-natural-beauty-camera/id1437880869?uo=4</a>
**App Version:** 2.0.1
**Seller:** SNOW INC.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/snow-inc/id1244624324?uo=4">© SNOW INC.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/da/fe/81/dafe81ac-3bb6-9cb7-4a88-0b22e66be854/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68527253-3b11a580-02e5-11ea-9571-d056d161295d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68527253-3b11a580-02e5-11ea-9571-d056d161295d.png)
https://user-images.githubusercontent.com/20930745/68527253-3b11a580-02e5-11ea-9571-d056d161295d.png

Source:
https://user-images.githubusercontent.com/20930745/68527254-3cdb6900-02e5-11ea-9b2e-95e2467c5453.png
