### ISSUE TITLE
Mobilklinik

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10517]
**App Name:** Mobilklinik
**Bundle ID:** dk.sundhed.Schweizerkniv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979176477">979176477</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mobilklinik/id979176477?uo=4">https://apps.apple.com/us/app/mobilklinik/id979176477?uo=4</a>
**App Version:** 1.5
**Seller:** Sundhed.dk
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sundhed-dk-den-f%C3%A6lles-offentlige-sundhedsportal/id624707864?uo=4">© sundhed.dk - Den fælles offentlige sundhedsportal</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax

**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/e1/a5/97/e1a5972c-530d-1b02-77d1-71dd56e1607a/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68696713-c4430980-057d-11ea-9b5e-5f1fb2092486.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68696713-c4430980-057d-11ea-9b5e-5f1fb2092486.png)
https://user-images.githubusercontent.com/20930745/68696713-c4430980-057d-11ea-9b5e-5f1fb2092486.png

Source:
https://user-images.githubusercontent.com/20930745/68696716-c60ccd00-057d-11ea-8ff9-170ad465036b.png
