### ISSUE TITLE
 小米商城-智能产品好到不用挑

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10519]
**App Name:** 小米商城-智能产品好到不用挑
**Bundle ID:** com.xiaomi.mishop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1024958046">1024958046</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/%E5%B0%8F%E7%B1%B3%E5%95%86%E5%9F%8E-%E6%99%BA%E8%83%BD%E4%BA%A7%E5%93%81%E5%A5%BD%E5%88%B0%E4%B8%8D%E7%94%A8%E6%8C%91/id1024958046?uo=4">https://apps.apple.com/us/app/%E5%B0%8F%E7%B1%B3%E5%95%86%E5%9F%8E-%E6%99%BA%E8%83%BD%E4%BA%A7%E5%93%81%E5%A5%BD%E5%88%B0%E4%B8%8D%E7%94%A8%E6%8C%91/id1024958046?uo=4</a>
**App Version:** 5.0.38
**Seller:** Beijing Xiaomi Co., Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/beijing-xiaomi-co-ltd/id377175754?uo=4">© Beijing Xiaomi Co., Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, Watch5-Watch5, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax

**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/9b/e1/85/9be185ce-a2aa-369c-53c4-0d0f1bd09659/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68697424-12a4d800-057f-11ea-8294-c94a376bc305.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68697424-12a4d800-057f-11ea-8294-c94a376bc305.png)
https://user-images.githubusercontent.com/20930745/68697424-12a4d800-057f-11ea-8294-c94a376bc305.png

Source:
https://user-images.githubusercontent.com/20930745/68697429-133d6e80-057f-11ea-8b6b-c1487573fe2b.png
