### ISSUE TITLE
Akuthjælp til døve

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10510]
**App Name:** Akuthjælp til døve
**Bundle ID:** dk.ditmer.112app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=994428045">994428045</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/dk/app/akuthj%C3%A6lp-til-d%C3%B8ve/id994428045?uo=4">https://apps.apple.com/dk/app/akuthj%C3%A6lp-til-d%C3%B8ve/id994428045?uo=4</a>
**App Version:** 1.5
**Seller:** ditmer a/s
**Developer:** <a target="_blank" href="https://apps.apple.com/dk/developer/ditmer-a-s/id405464937?uo=4">© ditmer a/s</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple69/v4/2f/87/f5/2f87f50f-9f41-686b-0513-0b2444be4683/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68180865-9cf4a700-ff95-11e9-90e9-395500c0382f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68180865-9cf4a700-ff95-11e9-90e9-395500c0382f.png)
https://user-images.githubusercontent.com/2068130/68180865-9cf4a700-ff95-11e9-90e9-395500c0382f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/68180884-aed64a00-ff95-11e9-8b5c-b9dee2a362e6.png
