### ISSUE TITLE
YI Home

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10518]
**App Name:** YI Home
**Bundle ID:** com.xiaoyi.yihome.tw
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1011626777">1011626777</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/yi-home/id1011626777?uo=4">https://apps.apple.com/us/app/yi-home/id1011626777?uo=4</a>
**App Version:** 4.0.11
**Seller:** Shanghai Xiaoyi Technology Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shanghai-xiaoyi-technology-co-ltd/id1011626776?uo=4">© Shanghai Xiaoyi Technology Co., Ltd.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax

**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/29/3a/8d/293a8d6b-265a-ee71-e040-1c1a47affe52/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68697095-767ad100-057e-11ea-8ecd-b8708b5a3303.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68697095-767ad100-057e-11ea-8ecd-b8708b5a3303.png)
https://user-images.githubusercontent.com/20930745/68697095-767ad100-057e-11ea-8ecd-b8708b5a3303.png

Source:
https://user-images.githubusercontent.com/20930745/68697098-77abfe00-057e-11ea-92dd-fe215a6ff54b.png
