### ISSUE TITLE
Sejlguide til sikker sejlads

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10520]
**App Name:** Sejlguide til sikker sejlads
**Bundle ID:** dk.dkfx.sejlguide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1070753053">1070753053</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/dk/app/sejlguide-til-sikker-sejlads/id1070753053?uo=4">https://apps.apple.com/dk/app/sejlguide-til-sikker-sejlads/id1070753053?uo=4</a>
**App Version:** 2.1.3
**Seller:** Simon Thamsen
**Developer:** <a target="_blank" href="https://apps.apple.com/dk/developer/simon-thamsen/id1070753052?uo=4">© Simon Thamsen</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax

**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/e0/50/d8/e050d841-764e-341e-05da-5737e14f935b/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68697707-b098a280-057f-11ea-97d7-89daefbb62ac.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68697707-b098a280-057f-11ea-97d7-89daefbb62ac.png)
https://user-images.githubusercontent.com/20930745/68697707-b098a280-057f-11ea-97d7-89daefbb62ac.png

Source:
https://user-images.githubusercontent.com/20930745/68697709-b1c9cf80-057f-11ea-8a8b-4b8f401c70c2.png
