### ISSUE TITLE
Discovr - discover music

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#1052]
**App Name:** Discovr - discover music
**Bundle ID:** com.jammbox.discovr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=412768094">412768094</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/discovr-discover-music/id412768094?mt=8&uo=4">https://itunes.apple.com/us/app/discovr-discover-music/id412768094?mt=8&uo=4</a>
**App Version:** 6.1
**Seller:** David McKinney Pty Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/david-mckinney-pty-ltd/id1129070459?uo=4">© David McKinney Pty Ltd</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/66/7a/70/667a7045-37a0-3e64-1fde-75b39ee1a707/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32146969-697e33a0-bcdf-11e7-8e35-3676ed1c62c5.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32146969-697e33a0-bcdf-11e7-8e35-3676ed1c62c5.png)
https://user-images.githubusercontent.com/2068130/32146969-697e33a0-bcdf-11e7-8e35-3676ed1c62c5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32146973-78226fca-bcdf-11e7-9a59-f266d619d303.png
