### ISSUE TITLE
Minecraft Earth

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10527]
**App Name:** Minecraft Earth
**Bundle ID:** com.mojang.minecraftearthtf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1467316099">1467316099</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/minecraft-earth/id1467316099?uo=4">https://apps.apple.com/us/app/minecraft-earth/id1467316099?uo=4</a>
**App Version:** 0.7.0
**Seller:** Mojang AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mojang/id479516146?uo=4">© Mojang</a>
**Supported Devices:** iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/f7/23/58/f7235867-1d3f-21fe-c239-7c15213b9eec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69874012-3fb0f480-12ba-11ea-8470-ea5e584bd23f.png)

**Comment by dreamnet** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69874012-3fb0f480-12ba-11ea-8470-ea5e584bd23f.png)
https://user-images.githubusercontent.com/2068130/69874012-3fb0f480-12ba-11ea-8470-ea5e584bd23f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/69874064-5ce5c300-12ba-11ea-9edd-0f7ccf4a95b5.png
