### ISSUE TITLE
FitPro

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10525]
**App Name:** FitPro
**Bundle ID:** com.Leyizu.fitpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1455617149">1455617149</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fitpro/id1455617149?uo=4">https://apps.apple.com/us/app/fitpro/id1455617149?uo=4</a>
**App Version:** 2.1.3
**Seller:** Shenzhen Jusheng Intelligent Technology Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/%E6%B7%B1%E5%9C%B3%E5%B8%82%E8%81%9A%E7%9B%9B%E6%99%BA%E8%83%BD%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/id1418414994?uo=4">© 深圳市聚盛智能科技有限公司</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax

**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/11/01/7f/11017f54-22ab-16e7-912f-a190fc7de56f/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68699863-2ef74380-0584-11ea-8fe7-296ea46e4a85.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68699863-2ef74380-0584-11ea-8fe7-296ea46e4a85.png)
https://user-images.githubusercontent.com/20930745/68699863-2ef74380-0584-11ea-8fe7-296ea46e4a85.png

Source:
https://user-images.githubusercontent.com/20930745/68699865-2f8fda00-0584-11ea-829c-2916384e8705.png
