### ISSUE TITLE
GALERIA Karstadt Kaufhof

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10528]
**App Name:** GALERIA Karstadt Kaufhof
**Bundle ID:** de.karstadt.karstadtapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1219359184">1219359184</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/galeria-karstadt-kaufhof/id1219359184?uo=4">https://apps.apple.com/de/app/galeria-karstadt-kaufhof/id1219359184?uo=4</a>
**App Version:** 3.0.3
**Seller:** Karstadt Warenhaus GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/karstadt-warenhaus-gmbh/id529805325?uo=4">© Karstadt Warenhaus GmbH</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/ee/7a/da/ee7ada8c-e17e-ef72-4b0f-2273a1a2d25c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68786780-a8ed0280-0640-11ea-96d0-c16e303e5603.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68786780-a8ed0280-0640-11ea-96d0-c16e303e5603.png)
https://user-images.githubusercontent.com/20930745/68786780-a8ed0280-0640-11ea-96d0-c16e303e5603.png

Source:
https://user-images.githubusercontent.com/20930745/68786784-aa1e2f80-0640-11ea-8331-cb880baa4da3.png
