### ISSUE TITLE
Bubble Explode - Blast Bubbles

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#10532]
**App Name:** Bubble Explode - Blast Bubbles
**Bundle ID:** com.spookyhousetudios.bubbleexplode
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376098160">376098160</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bubble-explode-blast-bubbles/id376098160?uo=4">https://apps.apple.com/us/app/bubble-explode-blast-bubbles/id376098160?uo=4</a>
**App Version:** 3.5.4
**Seller:** Spooky House Studios UG (haftungsbeschraenkt)
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/spooky-house-studios-ug-haftungsbeschraenkt/id376098163?uo=4">© Spooky House Studios UG (haftungsbeschraenkt)</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/65/43/26/65432655-69b5-0f46-36cf-7e919498fafc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69910972-a5b18f00-1414-11ea-82f2-dc0d95882de6.png)

**Comment by dreamnet** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69910972-a5b18f00-1414-11ea-82f2-dc0d95882de6.png)
https://user-images.githubusercontent.com/2068130/69910972-a5b18f00-1414-11ea-82f2-dc0d95882de6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/69910973-b95cf580-1414-11ea-9a84-639c839fca64.png
