### ISSUE TITLE
ClasseViva Famiglia

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#10535]
**App Name:** ClasseViva Famiglia
**Bundle ID:** eu.spaggiari.classevivafamiglia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1276095353">1276095353</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/classeviva-famiglia/id1276095353?uo=4">https://apps.apple.com/us/app/classeviva-famiglia/id1276095353?uo=4</a>
**App Version:** 2.1.2
**Seller:** Gruppo Spaggiari Parma SpA
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gruppo-spaggiari-parma-spa/id646682684?uo=4">© Gruppo Spaggiari Parma SpA</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/2d/79/b2/2d79b2ec-2dee-e942-c082-a8067bb84c0f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69426875-8d63b500-0d2e-11ea-976e-2c740149ce91.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69426875-8d63b500-0d2e-11ea-976e-2c740149ce91.png)
https://user-images.githubusercontent.com/20930745/69426875-8d63b500-0d2e-11ea-976e-2c740149ce91.png

Source:
https://user-images.githubusercontent.com/20930745/69426878-8fc60f00-0d2e-11ea-800b-f690b60158c5.png
