### ISSUE TITLE
Wapo: Gay Dating

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#10531]
**App Name:** Wapo: Gay Dating
**Bundle ID:** uk.co.wapoapp.wapo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=964162797">964162797</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wapo-gay-dating/id964162797?uo=4">https://apps.apple.com/us/app/wapo-gay-dating/id964162797?uo=4</a>
**App Version:** 13.0.1
**Seller:** Wapo y Wapa Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wapo-y-wapa-limited/id964162796?uo=4">© Wapo y Wapa Limited</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/a0/f8/ab/a0f8ab50-f1c3-2a09-eecf-d6b54a984594/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69424270-77eb8c80-0d28-11ea-910b-27425ac01a66.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69424270-77eb8c80-0d28-11ea-910b-27425ac01a66.png)
https://user-images.githubusercontent.com/20930745/69424270-77eb8c80-0d28-11ea-910b-27425ac01a66.png

Source:
https://user-images.githubusercontent.com/20930745/69424272-79b55000-0d28-11ea-98ab-0fed6f5f8878.png
