### ISSUE TITLE
Disney+

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10530]
**App Name:** Disney+
**Bundle ID:** com.disney.disneyplus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1446075923">1446075923</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/disney/id1446075923?uo=4">https://apps.apple.com/us/app/disney/id1446075923?uo=4</a>
**App Version:** 1.1.5
**Seller:** Disney Electronic Content, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/disney/id284888248?uo=4">© Disney</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/77/75/a2/7775a252-2602-d0d2-b9e2-4f021640df3b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69423765-47efb980-0d27-11ea-941a-516f723486eb.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69423765-47efb980-0d27-11ea-941a-516f723486eb.png)
https://user-images.githubusercontent.com/20930745/69423765-47efb980-0d27-11ea-941a-516f723486eb.png

Source:
https://user-images.githubusercontent.com/20930745/69423768-49b97d00-0d27-11ea-86bb-1ae1c274106f.png
