### ISSUE TITLE
ClasseViva Docenti

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#10533]
**App Name:** ClasseViva Docenti
**Bundle ID:** eu.spaggiari.classevivadocente
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1295653000">1295653000</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/classeviva-docenti/id1295653000?uo=4">https://apps.apple.com/us/app/classeviva-docenti/id1295653000?uo=4</a>
**App Version:** 1.3.1
**Seller:** Gruppo Spaggiari Parma SpA
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gruppo-spaggiari-parma-spa/id646682684?uo=4">© Gruppo Spaggiari Parma SpA</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/03/03/69/03036947-5526-e37a-be5e-5cea9a83a2e6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69426491-a9b32200-0d2d-11ea-84cf-d6220d4edb99.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69424706-956d2600-0d29-11ea-890a-20c418d01be6.png)
https://user-images.githubusercontent.com/20930745/69424706-956d2600-0d29-11ea-890a-20c418d01be6.png

Source:
https://user-images.githubusercontent.com/20930745/69424708-9736e980-0d29-11ea-8b54-2184fcbd868d.png
