### ISSUE TITLE
Haze

### ISSUE THREAD

**Issue by q2r5** [glasklart/hd#1053]
**App Name:** Haze
**Bundle ID:** com.robocatapps.Haze
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=594476963">594476963</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/haze/id594476963?mt=8&uo=4">https://itunes.apple.com/us/app/haze/id594476963?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** icelantern
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/robocat/id333195279?uo=4>© Robocat</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/e0/06/5b/e0065b2d-d653-a4e0-aab0-af51b114ac87/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19384240/97334518-9208-11e6-8aa1-ab57aaf5239f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19384240/97334518-9208-11e6-8aa1-ab57aaf5239f.png)
https://cloud.githubusercontent.com/assets/20930745/19384240/97334518-9208-11e6-8aa1-ab57aaf5239f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19384320/fd39f064-9208-11e6-87f8-8ae2c65890c6.png)
