### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by ianlegend** [glasklart/hd#1054]
**App Name:** Facebook
**Bundle ID:** com.facebook.Facebook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284882215">284882215</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facebook/id284882215?mt=8&uo=4">https://itunes.apple.com/us/app/facebook/id284882215?mt=8&uo=4</a>
**App Version:** 34.0
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/facebook-inc./id284882218?uo=4>© Facebook, Inc.</a>
**Supported Devices:** iPad2Wifi, iPodTouchFifthGen, iPhone4, iPhone6Plus, iPhone5, iPadFourthGen, iPadThirdGen, iPhone5c, iPadFourthGen4G, iPad23G, iPadThirdGen4G, iPhone4S, iPadMini, iPadMini4G, iPhone6, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/d5/eb/65/d5eb6502-4a1b-05f2-13ff-5e354b249091/mzl.zbjetlwt.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8508605/68b539a4-223c-11e5-92fe-07e84ee6e7ff.png)

**Comment by ivanov007** [comment]
just updating this icon
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8508605/68b539a4-223c-11e5-92fe-07e84ee6e7ff.png)
https://cloud.githubusercontent.com/assets/3090247/8508605/68b539a4-223c-11e5-92fe-07e84ee6e7ff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8508606/68b8b246-223c-11e5-8304-b1e892a009b7.png
