### ISSUE TITLE
Traccar Client

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10548]
**App Name:** Traccar Client
**Bundle ID:** org.traccar.client.TraccarClient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=843156974">843156974</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/traccar-client/id843156974?uo=4">https://apps.apple.com/us/app/traccar-client/id843156974?uo=4</a>
**App Version:** v5.9
**Seller:** Anton Tananaev
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/anton-tananaev/id843156982?uo=4">© Anton Tananaev</a>

**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/0d/68/43/0d684357-e8d2-63e4-7ca9-9cd007706dbd/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474433-6aceac00-0dc1-11ea-9cc0-6ecd2f684e98.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474433-6aceac00-0dc1-11ea-9cc0-6ecd2f684e98.png)
https://user-images.githubusercontent.com/20930745/69474433-6aceac00-0dc1-11ea-9cc0-6ecd2f684e98.png

Source:
https://user-images.githubusercontent.com/20930745/69474435-6c986f80-0dc1-11ea-9d00-ce483a3fa088.png
