### ISSUE TITLE
Patienthåndbogen

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10546]
**App Name:** Patienthåndbogen
**Bundle ID:** dk.sundhed.ph
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=731968314">731968314</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/patienth%C3%A5ndbogen/id731968314?uo=4">https://apps.apple.com/us/app/patienth%C3%A5ndbogen/id731968314?uo=4</a>
**App Version:** 1.5.0
**Seller:** Danske Regioner
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/danske-regioner/id673071592?uo=4">© Danske Regioner</a>

**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/38/fa/4b/38fa4b20-1d07-9713-55f6-b07aea2216db/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474336-33abcb00-0dc0-11ea-94e0-9f2d8fe9c636.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474336-33abcb00-0dc0-11ea-94e0-9f2d8fe9c636.png)
https://user-images.githubusercontent.com/20930745/69474336-33abcb00-0dc0-11ea-94e0-9f2d8fe9c636.png

Source:
https://user-images.githubusercontent.com/20930745/69474337-35758e80-0dc0-11ea-9c48-165373f9909f.png
