### ISSUE TITLE
Lægehåndbogen

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10547]
**App Name:** Lægehåndbogen
**Bundle ID:** dk.sundhed.lh
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=731968626">731968626</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/l%C3%A6geh%C3%A5ndbogen/id731968626?uo=4">https://apps.apple.com/us/app/l%C3%A6geh%C3%A5ndbogen/id731968626?uo=4</a>
**App Version:** 1.5.0
**Seller:** Danske Regioner
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/danske-regioner/id673071592?uo=4">© Danske Regioner</a>

**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/7c/55/ba/7c55bae5-0aa8-7e36-fc56-db0cfc6599bd/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474367-aa48c880-0dc0-11ea-803b-cd0d155afc85.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474367-aa48c880-0dc0-11ea-803b-cd0d155afc85.png)
https://user-images.githubusercontent.com/20930745/69474367-aa48c880-0dc0-11ea-803b-cd0d155afc85.png

Source:
https://user-images.githubusercontent.com/20930745/69474369-ab79f580-0dc0-11ea-8f57-507fa8264078.png

**Comment by dreamnet** [comment]
Same as #10546.
