### ISSUE TITLE
Remote for Tautulli

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10553]
**App Name:** Remote for Tautulli
**Bundle ID:** de.tfonfara.tautulliremote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1343177312">1343177312</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/remote-for-tautulli/id1343177312?uo=4">https://apps.apple.com/us/app/remote-for-tautulli/id1343177312?uo=4</a>
**App Version:** 1.13.0
**Seller:** Tobias Fonfara
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tobias-fonfara/id429395867?uo=4">© Tobias Fonfara</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/c0/f1/a3/c0f1a335-4304-780c-130b-7e1ac068c8f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474759-11687c00-0dc5-11ea-8660-b46f1063ff8f.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474759-11687c00-0dc5-11ea-8660-b46f1063ff8f.png)
https://user-images.githubusercontent.com/20930745/69474759-11687c00-0dc5-11ea-8660-b46f1063ff8f.png

Source:
https://user-images.githubusercontent.com/20930745/69474760-1299a900-0dc5-11ea-8929-51eed2cd659f.png
