### ISSUE TITLE
Denver Transit • RTD Bus Times

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10559]
**App Name:** Denver Transit • RTD Bus Times
**Bundle ID:** com.busexpertapp.uswest.denver
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1176578705">1176578705</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/denver-transit-rtd-bus-times/id1176578705?uo=4">https://apps.apple.com/us/app/denver-transit-rtd-bus-times/id1176578705?uo=4</a>
**App Version:** 2019.12
**Seller:** Transit Now ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/transit-now-ltd/id1281251209?uo=4">© Transit Now ltd</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/2c/9c/85/2c9c852c-5426-3214-87de-c7edf2c36987/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70257017-d7ff1b80-1789-11ea-821c-6eb7d62c36b8.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70257017-d7ff1b80-1789-11ea-821c-6eb7d62c36b8.png)
https://user-images.githubusercontent.com/20930745/70257017-d7ff1b80-1789-11ea-821c-6eb7d62c36b8.png

Source:
https://user-images.githubusercontent.com/20930745/70257023-d9304880-1789-11ea-8658-181e62615fab.png
