### ISSUE TITLE
 Auxy - Music & Beat Maker

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10550]
**App Name:** Auxy - Music & Beat Maker
**Bundle ID:** co.auxy.auxy-phone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1034348186">1034348186</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/auxy-music-beat-maker/id1034348186?uo=4">https://apps.apple.com/us/app/auxy-music-beat-maker/id1034348186?uo=4</a>
**App Version:** 6.0.2
**Seller:** Auxy AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/auxy/id845148415?uo=4">© Auxy</a>

**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a5/5f/34/a55f3427-fc8c-8453-de24-15f6e96ce72e/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474519-7373b200-0dc2-11ea-9990-1b0e137de880.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474519-7373b200-0dc2-11ea-9990-1b0e137de880.png)
https://user-images.githubusercontent.com/20930745/69474519-7373b200-0dc2-11ea-9990-1b0e137de880.png

Source:
https://user-images.githubusercontent.com/20930745/69474520-753d7580-0dc2-11ea-9775-9b34e4c24d13.png
