### ISSUE TITLE
Crypto Disks & File Explorer

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10556]
**App Name:** Crypto Disks & File Explorer
**Bundle ID:** com.zyingp.PLFileManagement
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=889549308">889549308</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/crypto-disks-file-explorer/id889549308?uo=4">https://apps.apple.com/us/app/crypto-disks-file-explorer/id889549308?uo=4</a>
**App Version:** 2.5.9
**Seller:** Yingpei Zeng
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yingpei-zeng/id889549311?uo=4">© Yingpei Zeng</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/7e/84/2e/7e842ec0-8968-0bef-6d5a-5c1247a5c5e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69846562-b1664f80-1274-11ea-9760-05c0cb30d8ea.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69846562-b1664f80-1274-11ea-9760-05c0cb30d8ea.png)
https://user-images.githubusercontent.com/2068130/69846562-b1664f80-1274-11ea-9760-05c0cb30d8ea.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/69846581-c17e2f00-1274-11ea-9def-00f9ddaff6e8.png
