### ISSUE TITLE
IQ Test - With Solutions

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10557]
**App Name:** IQ Test - With Solutions
**Bundle ID:** com.diensa.pati.iqtest.001
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1161533290">1161533290</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/iq-test-with-solutions/id1161533290?uo=4">https://apps.apple.com/us/app/iq-test-with-solutions/id1161533290?uo=4</a>
**App Version:** 1.2
**Seller:** Patricia Romani
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/patricia-romani/id946550830?uo=4">© Patricia Romani</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple62/v4/28/01/53/2801538c-a9a3-953e-a9ee-4c147a1441c2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69898798-4a24ca00-135e-11ea-92e9-79e2aea8dfa4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69898798-4a24ca00-135e-11ea-92e9-79e2aea8dfa4.png)
https://user-images.githubusercontent.com/2068130/69898798-4a24ca00-135e-11ea-92e9-79e2aea8dfa4.png
--- ---
Source: 
https://user-images.githubusercontent.com/2068130/69898804-5c066d00-135e-11ea-8e3e-387c17c6e06b.png
