### ISSUE TITLE
Mi Drone - Explore & Record

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10551]
**App Name:** Mi Drone - Explore & Record
**Bundle ID:** com.fimi.ios-drone-overseas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1182281556">1182281556</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mi-drone-explore-record/id1182281556?uo=4">https://apps.apple.com/us/app/mi-drone-explore-record/id1182281556?uo=4</a>
**App Version:** 1.2.9
**Seller:** Beijing FIMI Technology CO.,LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/beijing-fimi-technology-co-ltd/id1112378743?uo=4">© Beijing FIMI Technology CO.,LTD</a>

**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/0f/1b/d1/0f1bd1f2-d0d2-33ab-2e6c-1a17432c38d6/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474586-55f31800-0dc3-11ea-9a86-dfe35d4cbb2c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474586-55f31800-0dc3-11ea-9a86-dfe35d4cbb2c.png)
https://user-images.githubusercontent.com/20930745/69474586-55f31800-0dc3-11ea-9a86-dfe35d4cbb2c.png

Source:
https://user-images.githubusercontent.com/20930745/69474587-57bcdb80-0dc3-11ea-809d-c4e53a2403cb.png
