### ISSUE TITLE
The Room: Old Sins

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10555]
**App Name:** The Room: Old Sins
**Bundle ID:** com.FireproofStudios.TheRoom4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1286676015">1286676015</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/the-room-old-sins/id1286676015?uo=4">https://apps.apple.com/us/app/the-room-old-sins/id1286676015?uo=4</a>
**App Version:** 1.0.4
**Seller:** Fireproof Studios Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fireproof-games/id552039499?uo=4">© Fireproof Games</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/90/4d/4d/904d4db8-4606-2dd5-43e6-16c73073d0dd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69478825-12b29c80-0df7-11ea-8e26-4fd787ece61a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69478825-12b29c80-0df7-11ea-8e26-4fd787ece61a.png)
https://user-images.githubusercontent.com/2068130/69478825-12b29c80-0df7-11ea-8e26-4fd787ece61a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/69478830-2100b880-0df7-11ea-9095-c2269dac61f6.png
