### ISSUE TITLE
Quizlet: Learn with Flashcards & Study Tools

### ISSUE THREAD

**Issue by liltim050** [glasklart/hd#1055]
**App Name:** Quizlet: Learn with Flashcards & Study Tools
**Bundle ID:** com.quizlet.quizlet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=546473125">546473125</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quizlet-learn-flashcards-study/id546473125?mt=8&uo=4">https://itunes.apple.com/us/app/quizlet-learn-flashcards-study/id546473125?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Quizlet LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/quizlet-llc/id546473128?uo=4>© Quizlet LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/4d/00/8d/4d008dc2-7dab-45ca-47cb-c6a0bc9fc66f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420215/eb1bc102-93e6-11e6-835f-91cede7dba63.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420215/eb1bc102-93e6-11e6-835f-91cede7dba63.png)
https://cloud.githubusercontent.com/assets/20930745/19420215/eb1bc102-93e6-11e6-835f-91cede7dba63.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19420225/0fc3b5c8-93e7-11e6-87d8-e0c222d6269c.png
