### ISSUE TITLE
DSB App

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10554]
**App Name:** DSB App
**Bundle ID:** dk.dsb.nda
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1438634111">1438634111</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dsb-app/id1438634111?uo=4">https://apps.apple.com/us/app/dsb-app/id1438634111?uo=4</a>
**App Version:** 1.7.0
**Seller:** DSB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dsb/id369894672?uo=4">© DSB</a>

**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/89/c1/9e/89c19e76-5d03-33fa-4bc7-eebdd40fb086/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474826-bc793580-0dc5-11ea-803c-48a651b95331.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474826-bc793580-0dc5-11ea-803c-48a651b95331.png)
https://user-images.githubusercontent.com/20930745/69474826-bc793580-0dc5-11ea-803c-48a651b95331.png

Source:
![dsbapp](https://user-images.githubusercontent.com/20930745/69474829-c0a55300-0dc5-11ea-9dfd-22ca51b75598.png)
