### ISSUE TITLE
TrygFonden Hjerteløber

### ISSUE THREAD

**Issue by cassio299** [glasklart/hd#10552]
**App Name:** TrygFonden Hjerteløber
**Bundle ID:** com.umsalert.hjertelober
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1206278199">1206278199</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/trygfonden-hjertel%C3%B8ber/id1206278199?uo=4">https://apps.apple.com/us/app/trygfonden-hjertel%C3%B8ber/id1206278199?uo=4</a>
**App Version:** 3.50
**Seller:** Heartrunner Sweden Ab
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/heartrunner-sweden-ab/id1445011181?uo=4">© Heartrunner Sweden AB</a>

**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/38/9a/f3/389af3f5-b81c-d652-837e-eb252044c277/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474658-052fef00-0dc4-11ea-9913-a08770e28b81.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/69474658-052fef00-0dc4-11ea-9913-a08770e28b81.png)
https://user-images.githubusercontent.com/20930745/69474658-052fef00-0dc4-11ea-9913-a08770e28b81.png

Source:
https://user-images.githubusercontent.com/20930745/69474659-07924900-0dc4-11ea-87de-97c438132768.png
