### ISSUE TITLE
DPD

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10565]
**App Name:** DPD
**Bundle ID:** com.dpd.dpdAllgemein
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=728428119">728428119</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/dpd/id728428119?uo=4">https://apps.apple.com/de/app/dpd/id728428119?uo=4</a>
**App Version:** 3.9.0
**Seller:** DPD Dynamic Parcel Distribution GmbH & Co. KG
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/dpd-dynamic-parcel-distribution-gmbh-co-kg/id728428122?uo=4">© DPD Dynamic Parcel Distribution GmbH & Co. KG</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/2c/e2/4f/2ce24f17-cd55-eb33-a7b0-38af27edd0b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70360474-f09d2d80-187e-11ea-9781-22b18b55fa1e.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70360474-f09d2d80-187e-11ea-9781-22b18b55fa1e.png)
(https://user-images.githubusercontent.com/20930745/70360474-f09d2d80-187e-11ea-9781-22b18b55fa1e.png

Source:
https://user-images.githubusercontent.com/20930745/70360475-f1ce5a80-187e-11ea-9277-a48f1282203e.png
