### ISSUE TITLE
Mirror for LG Smart TV

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10562]
**App Name:** Mirror for LG Smart TV
**Bundle ID:** tv.airbeam.mirrorforlgtvios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1249388425">1249388425</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mirror-for-lg-smart-tv/id1249388425?uo=4">https://apps.apple.com/us/app/mirror-for-lg-smart-tv/id1249388425?uo=4</a>
**App Version:** 3.3.7
**Seller:** AirBeamTV BV
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/airbeamtv-bv/id1107644798?uo=4">© AirBeamTV BV</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/26/28/61/262861fc-8f48-1bac-0e31-6567a6c94657/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/70371641-e6f2e480-18d5-11ea-9e77-c4dfc7327ef6.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70326941-0803f880-1836-11ea-9a80-82e437f425d6.png)
https://user-images.githubusercontent.com/20930745/70326941-0803f880-1836-11ea-9a80-82e437f425d6.png

Source:
https://user-images.githubusercontent.com/20930745/70326942-09cdbc00-1836-11ea-8a77-df88195d5ec5.png

**Comment by 2Qt2beStr8** [comment]
or this one:
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70327487-2fa79080-1837-11ea-87e8-06b77bd64958.png)
https://user-images.githubusercontent.com/20930745/70327487-2fa79080-1837-11ea-87e8-06b77bd64958.png

Source:
https://user-images.githubusercontent.com/20930745/70327490-31715400-1837-11ea-8695-70dfb91734c8.png

**Comment by dreamnet** [comment]
I think it's better without the border:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/70371641-e6f2e480-18d5-11ea-9e77-c4dfc7327ef6.png)
https://user-images.githubusercontent.com/2068130/70371641-e6f2e480-18d5-11ea-9e77-c4dfc7327ef6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/70371645-f6722d80-18d5-11ea-99ff-c2b0e6e9ec03.png
