### ISSUE TITLE
Smartify - LG TV Remote

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10560]
**App Name:** Smartify - LG TV Remote
**Bundle ID:** com.kraftwerk9.smartify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=991626968">991626968</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/smartify-lg-tv-remote/id991626968?uo=4">https://apps.apple.com/us/app/smartify-lg-tv-remote/id991626968?uo=4</a>
**App Version:** 1.11
**Seller:** KRAFTWERK 9 LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kraftwerk-9-llc/id1473954653?uo=4">© KRAFTWERK 9 LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/5f/62/09/5f62099f-3017-face-6a39-5e8a7498f495/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70326151-1224f780-1834-11ea-9731-5e5f15bf49af.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70326151-1224f780-1834-11ea-9731-5e5f15bf49af.png)
https://user-images.githubusercontent.com/20930745/70326151-1224f780-1834-11ea-9731-5e5f15bf49af.png

Source:
https://user-images.githubusercontent.com/20930745/70326157-13562480-1834-11ea-83ef-ea00573a0250.png
