### ISSUE TITLE
INTERSPORT

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10563]
**App Name:** INTERSPORT
**Bundle ID:** de.intersport.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1436980968">1436980968</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/intersport/id1436980968?uo=4">https://apps.apple.com/de/app/intersport/id1436980968?uo=4</a>
**App Version:** 1.3
**Seller:** Intersport Digital GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/intersport-digital-gmbh/id1365562997?uo=4">© Intersport Digital GmbH</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/3f/4f/d8/3f4fd85f-8949-4891-511b-4d0137a1336c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70360022-9d76ab00-187d-11ea-8216-8195c8597fe7.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70360022-9d76ab00-187d-11ea-8216-8195c8597fe7.png)
https://user-images.githubusercontent.com/20930745/70360022-9d76ab00-187d-11ea-8216-8195c8597fe7.png

Source:
https://user-images.githubusercontent.com/20930745/70360023-9f406e80-187d-11ea-84ca-3c4246a74c93.png
