### ISSUE TITLE
JACK & JONES: Men's Fashion

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10564]
**App Name:** JACK & JONES: Men's Fashion
**Bundle ID:** com.bestseller.jackjones.jjAppStore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=421765197">421765197</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/jack-jones-mens-fashion/id421765197?uo=4">https://apps.apple.com/gb/app/jack-jones-mens-fashion/id421765197?uo=4</a>
**App Version:** 7.1.10
**Seller:** BESTSELLER United AS
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/bestseller-united-as/id1466626083?uo=4">© BESTSELLER United AS</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/df/dd/d5/dfddd580-d09f-23c5-9de2-77ff32586a53/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70360300-563cea00-187e-11ea-9197-d41c0c66c5b5.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70360300-563cea00-187e-11ea-9197-d41c0c66c5b5.png)
https://user-images.githubusercontent.com/20930745/70360300-563cea00-187e-11ea-9197-d41c0c66c5b5.png

Source:
https://user-images.githubusercontent.com/20930745/70360302-576e1700-187e-11ea-8d8c-c6432f6bc905.png
