### ISSUE TITLE
tonies

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10566]
**App Name:** tonies
**Bundle ID:** de.boxine.tonies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1136264593">1136264593</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tonies/id1136264593?uo=4">https://apps.apple.com/us/app/tonies/id1136264593?uo=4</a>
**App Version:** 1.2.5
**Seller:** Boxine GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/boxine-gmbh/id1136264592?uo=4">© Boxine GmbH</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/08/a9/ce/08a9cef7-05cb-97e6-9f57-d719382ff3a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70387761-6b626780-19a9-11ea-977c-ffa10d7519a3.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70387761-6b626780-19a9-11ea-977c-ffa10d7519a3.png)
https://user-images.githubusercontent.com/20930745/70387761-6b626780-19a9-11ea-977c-ffa10d7519a3.png

Source:
https://user-images.githubusercontent.com/20930745/70387762-6c939480-19a9-11ea-8d6c-0cb087b18c44.png
