### ISSUE TITLE
Ship Finder

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10561]
**App Name:** Ship Finder
**Bundle ID:** com.pinkfroot.BIGSHIPS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=363360636">363360636</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ship-finder/id363360636?uo=4">https://apps.apple.com/us/app/ship-finder/id363360636?uo=4</a>
**App Version:** 9.2.2
**Seller:** pinkfroot limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/pinkfroot-limited/id319726822?uo=4">© pinkfroot limited</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/90/ae/3f/90ae3fe5-c179-8b57-051f-efc5ea4f609e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70326667-5d8bd580-1835-11ea-8e70-fdb919ce5458.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70326667-5d8bd580-1835-11ea-8e70-fdb919ce5458.png)
https://user-images.githubusercontent.com/20930745/70326667-5d8bd580-1835-11ea-8e70-fdb919ce5458.png

Source:
https://user-images.githubusercontent.com/20930745/70326668-5ebd0280-1835-11ea-9721-04d47aa449bf.png
