### ISSUE TITLE
Noteshelf

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10577]
**App Name:** Noteshelf
**Bundle ID:** com.fluidtouch.noteshelf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1271086060">1271086060</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/noteshelf/id1271086060?uo=4">https://apps.apple.com/us/app/noteshelf/id1271086060?uo=4</a>
**App Version:** 6.1.7
**Seller:** Fluid Touch Pte. Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fluid-touch-pte-ltd/id318004740?uo=4">© Fluid Touch Pte. Ltd.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/18/51/4d/18514dd2-9819-4be1-9c2f-2ca376e2be0b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70941309-73c33e00-204c-11ea-8776-b396e1f44a89.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70941309-73c33e00-204c-11ea-8776-b396e1f44a89.png)
https://user-images.githubusercontent.com/20930745/70941309-73c33e00-204c-11ea-8776-b396e1f44a89.png

Source:
https://user-images.githubusercontent.com/20930745/70941311-758d0180-204c-11ea-8262-18d011e10604.png
