### ISSUE TITLE
Pager: Alerts for Reddit

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10574]
**App Name:** Pager: Alerts for Reddit
**Bundle ID:** com.joshuat.pagerapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1439013829">1439013829</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pager-alerts-for-reddit/id1439013829?uo=4">https://apps.apple.com/us/app/pager-alerts-for-reddit/id1439013829?uo=4</a>
**App Version:** 1.0.1
**Seller:** Joshua Turner
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/joshua-turner/id1439013828?uo=4">© Joshua Turner</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/03/ac/e3/03ace3e3-7a60-57bf-ce52-60066361e124/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70939481-a79c6480-2048-11ea-9cfa-aff2e7ed424d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70939481-a79c6480-2048-11ea-9cfa-aff2e7ed424d.png)
https://user-images.githubusercontent.com/20930745/70939481-a79c6480-2048-11ea-9cfa-aff2e7ed424d.png

Source:
https://user-images.githubusercontent.com/20930745/70939489-aa975500-2048-11ea-8c21-f5ea10b9c61e.png
