### ISSUE TITLE
Noto - Elegant Note

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10575]
**App Name:** Noto - Elegant Note
**Bundle ID:** com.lkzhao.editor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1459055246">1459055246</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/noto-elegant-note/id1459055246?uo=4">https://apps.apple.com/us/app/noto-elegant-note/id1459055246?uo=4</a>
**App Version:** 2.2.0
**Seller:** Yi Lun Zhao
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yi-lun-zhao/id598496583?uo=4">© Yi Lun Zhao</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/ac/1e/ab/ac1eab62-d0ba-0540-34b6-52b03e8af0d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83336372-36c5cd80-a2b3-11ea-9dfd-eebc3ad368bb.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70939950-9a33aa00-2049-11ea-8e42-684cdfa53858.png)
https://user-images.githubusercontent.com/20930745/70939950-9a33aa00-2049-11ea-8e42-684cdfa53858.png

Source:
https://user-images.githubusercontent.com/20930745/70939953-9bfd6d80-2049-11ea-9b54-9dd549327261.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Noto - Elegant Note
**Bundle ID:** com.lkzhao.editor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1459055246">1459055246</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/noto-elegant-note/id1459055246?uo=4">https://apps.apple.com/us/app/noto-elegant-note/id1459055246?uo=4</a>
**App Version:** 2.2.0
**Seller:** Yi Lun Zhao
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yi-lun-zhao/id598496583?uo=4">© Yi Lun Zhao</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/ac/1e/ab/ac1eab62-d0ba-0540-34b6-52b03e8af0d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83336372-36c5cd80-a2b3-11ea-9dfd-eebc3ad368bb.png)
https://user-images.githubusercontent.com/2068130/83336372-36c5cd80-a2b3-11ea-9dfd-eebc3ad368bb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83336382-46451680-a2b3-11ea-8dc2-a7f704707392.png
