### ISSUE TITLE
Timeshifter

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10573]
**App Name:** Timeshifter
**Bundle ID:** com.timeshifter.timeshifter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1380684374">1380684374</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/timeshifter/id1380684374?uo=4">https://apps.apple.com/us/app/timeshifter/id1380684374?uo=4</a>
**App Version:** 2.0.8
**Seller:** Timeshifter Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/timeshifter-inc/id1380684373?uo=4">© Timeshifter Inc.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/c1/8a/37/c18a37e6-5b96-59dd-4203-fb7d9be6e809/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70858964-04decb80-1f0c-11ea-8405-ba74ffa2baed.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70858964-04decb80-1f0c-11ea-8405-ba74ffa2baed.png)
https://user-images.githubusercontent.com/20930745/70858964-04decb80-1f0c-11ea-8405-ba74ffa2baed.png

Source:
https://user-images.githubusercontent.com/20930745/70858965-06a88f00-1f0c-11ea-8dbf-5be7714a0512.png
