### ISSUE TITLE
Further: Get Things Done

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10576]
**App Name:** Further: Get Things Done
**Bundle ID:** com.mindgarner.furtherplanner.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1438367786">1438367786</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/further-get-things-done/id1438367786?uo=4">https://apps.apple.com/us/app/further-get-things-done/id1438367786?uo=4</a>
**App Version:** 1.12
**Seller:** Mind Garner LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mind-garner-llc/id1438367785?uo=4">© Mind Garner LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/16/a2/d7/16a2d730-6278-51a8-8162-b4fa3c5d771e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70940316-58573380-204a-11ea-933f-075a26b7b978.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70940316-58573380-204a-11ea-933f-075a26b7b978.png)
https://user-images.githubusercontent.com/20930745/70940316-58573380-204a-11ea-933f-075a26b7b978.png

Source:
https://user-images.githubusercontent.com/20930745/70940330-5beaba80-204a-11ea-81fb-88b11d2638b0.png
