### ISSUE TITLE
Heart's Choice

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10572]
**App Name:** Heart's Choice
**Bundle ID:** com.heartschoice.o
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1487052276">1487052276</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hearts-choice/id1487052276?uo=4">https://apps.apple.com/us/app/hearts-choice/id1487052276?uo=4</a>
**App Version:** 1.0.3
**Seller:** Hearts Choice LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hearts-choice-llc/id1487051045?uo=4">© Hearts Choice LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/8e/34/40/8e344018-261a-a069-6792-5eb3346822b7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70801368-034bc100-1daf-11ea-817f-a7784ae6995e.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70801368-034bc100-1daf-11ea-817f-a7784ae6995e.png)
https://user-images.githubusercontent.com/20930745/70801368-034bc100-1daf-11ea-817f-a7784ae6995e.png

Source:
https://user-images.githubusercontent.com/20930745/70801373-05158480-1daf-11ea-8bfe-7c6f2eadff20.png
