### ISSUE TITLE
Austrian Airlines

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#10579]
**App Name:** Austrian Airlines
**Bundle ID:** com.austrian.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=400224803">400224803</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/austrian-airlines/id400224803?uo=4">https://apps.apple.com/us/app/austrian-airlines/id400224803?uo=4</a>
**App Version:** 6.2.0
**Seller:** Austrian Airlines AG
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/austrian-airlines-ag/id385044057?uo=4">© Austrian Airlines AG</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/15/88/e8/1588e886-06d3-f2d0-b1e0-92641749422b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71314366-4d841080-2447-11ea-8fcf-006ce8d44d81.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71314366-4d841080-2447-11ea-8fcf-006ce8d44d81.png)
https://user-images.githubusercontent.com/2068130/71314366-4d841080-2447-11ea-8fcf-006ce8d44d81.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71314368-5bd22c80-2447-11ea-9f0c-d1211e8e927e.png
