### ISSUE TITLE
MiniWiki

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10587]
**App Name:** MiniWiki
**Bundle ID:** com.willbishop.MiniWiki
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1448143759">1448143759</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/miniwiki/id1448143759?uo=4">https://apps.apple.com/us/app/miniwiki/id1448143759?uo=4</a>
**App Version:** 1.1
**Seller:** Will Bishop
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/will-bishop/id1344097184?uo=4">© Will Bishop</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/d0/eb/14/d0eb1469-2f02-ea47-ddc4-6c817415c68e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/71448222-7eab5c00-2739-11ea-84c2-d8a7e983fe7b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/71448222-7eab5c00-2739-11ea-84c2-d8a7e983fe7b.png)
https://user-images.githubusercontent.com/20930745/71448222-7eab5c00-2739-11ea-84c2-d8a7e983fe7b.png

Source:
https://user-images.githubusercontent.com/20930745/71448223-810db600-2739-11ea-9e9b-57aa311bf42e.png
