### ISSUE TITLE
Five Nights at Freddy's

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10580]
**App Name:** Five Nights at Freddy's
**Bundle ID:** com.scottgames.fivenights
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=912536422">912536422</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/five-nights-at-freddys/id912536422?uo=4">https://apps.apple.com/us/app/five-nights-at-freddys/id912536422?uo=4</a>
**App Version:** 2.0.1
**Seller:** CLICKTEAM L.L.C.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/clickteam-llc/id1438432084?uo=4">© Clickteam, LLC</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/7c/60/eb/7c60eb01-be12-0971-63f7-c667354cf17d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643308-4f0bcf00-2cb8-11ea-9b45-8163805bab70.png)

**Comment by dreamnet** [comment]
Hmmm... no idea what to do with all this FNaF app's, beside this:
![Unbenannt-3](https://user-images.githubusercontent.com/2068130/71542709-d8926880-2969-11ea-9027-499b2e3a8a4c.png)
❓

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643308-4f0bcf00-2cb8-11ea-9b45-8163805bab70.png)
https://user-images.githubusercontent.com/2068130/71643308-4f0bcf00-2cb8-11ea-9b45-8163805bab70.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71643311-5e8b1800-2cb8-11ea-9112-75ba7ec90d57.png
