### ISSUE TITLE
Five Nights at Freddy's 2

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10581]
**App Name:** Five Nights at Freddy's 2
**Bundle ID:** com.scottgames.fnaf2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=941143328">941143328</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/five-nights-at-freddys-2/id941143328?uo=4">https://apps.apple.com/us/app/five-nights-at-freddys-2/id941143328?uo=4</a>
**App Version:** 2.0.1
**Seller:** CLICKTEAM L.L.C.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/clickteam-llc/id1438432084?uo=4">© Clickteam, LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/ad/84/f6/ad84f6b6-7e67-f6cb-c0be-79d92f5dd619/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643324-ad38b200-2cb8-11ea-8c51-03bfd27a4fd9.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643324-ad38b200-2cb8-11ea-8c51-03bfd27a4fd9.png)
https://user-images.githubusercontent.com/2068130/71643324-ad38b200-2cb8-11ea-8c51-03bfd27a4fd9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71643331-bd509180-2cb8-11ea-89aa-5220fcba69de.png
