### ISSUE TITLE
FNaF 6: Pizzeria Simulator

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10585]
**App Name:** FNaF 6: Pizzeria Simulator
**Bundle ID:** com.clickteam.freddyfazbearspizzeriasimulator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1455781522">1455781522</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fnaf-6-pizzeria-simulator/id1455781522?uo=4">https://apps.apple.com/us/app/fnaf-6-pizzeria-simulator/id1455781522?uo=4</a>
**App Version:** 1.0
**Seller:** CLICKTEAM L.L.C.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/clickteam-llc/id1438432084?uo=4">© Clickteam, LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/4a/bf/50/4abf5085-2561-b838-cbec-555f1a4a0d1d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643445-0fde7d80-2cba-11ea-93ba-8d673f47f3e9.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643445-0fde7d80-2cba-11ea-93ba-8d673f47f3e9.png)
https://user-images.githubusercontent.com/2068130/71643445-0fde7d80-2cba-11ea-93ba-8d673f47f3e9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71643448-1f5dc680-2cba-11ea-97b8-f08375848a65.png
