### ISSUE TITLE
Five Nights at Freddy's 3

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10582]
**App Name:** Five Nights at Freddy's 3
**Bundle ID:** com.scottgames.fivenights3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=973482987">973482987</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/five-nights-at-freddys-3/id973482987?uo=4">https://apps.apple.com/us/app/five-nights-at-freddys-3/id973482987?uo=4</a>
**App Version:** 1.3
**Seller:** Scott Cawthon
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/scott-cawthon/id777236428?uo=4">© Scott Cawthon</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple5/v4/9a/7a/be/9a7abef4-160c-2621-3126-97c3f6e0a566/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643348-030d5a00-2cb9-11ea-8787-de880ee0e935.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643348-030d5a00-2cb9-11ea-8787-de880ee0e935.png)
https://user-images.githubusercontent.com/2068130/71643348-030d5a00-2cb9-11ea-8787-de880ee0e935.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71643356-11f40c80-2cb9-11ea-9092-7db43e0700b1.png
