### ISSUE TITLE
Five Nights at Freddys 4

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10583]
**App Name:** Five Nights at Freddys 4
**Bundle ID:** com.scottgames.fnaf4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1023146677">1023146677</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/five-nights-at-freddys-4/id1023146677?uo=4">https://apps.apple.com/us/app/five-nights-at-freddys-4/id1023146677?uo=4</a>
**App Version:** 1.0
**Seller:** Scott Cawthon
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/scott-cawthon/id777236428?uo=4">© Scott Cawthon</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple1/v4/b7/c9/68/b7c96855-92a9-dad9-981f-e12c0733abc5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643385-65fef100-2cb9-11ea-97a3-1c3dd9a01164.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643385-65fef100-2cb9-11ea-97a3-1c3dd9a01164.png)
https://user-images.githubusercontent.com/2068130/71643385-65fef100-2cb9-11ea-97a3-1c3dd9a01164.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71643392-74e5a380-2cb9-11ea-9cdd-13013b73c57b.png
