### ISSUE TITLE
Five Nights at Freddy's: Sister Location

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10584]
**App Name:** Five Nights at Freddy's: Sister Location
**Bundle ID:** com.scottgames.sisterlocation
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1189781891">1189781891</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/five-nights-at-freddys-sister-location/id1189781891?uo=4">https://apps.apple.com/us/app/five-nights-at-freddys-sister-location/id1189781891?uo=4</a>
**App Version:** 1.0
**Seller:** Scott Cawthon
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/scott-cawthon/id777236428?uo=4">© Scott Cawthon</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple111/v4/11/48/53/114853d9-793f-89b9-fdf6-bb9de76f1694/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643415-c3933d80-2cb9-11ea-91d1-a2e129a8d212.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643415-c3933d80-2cb9-11ea-91d1-a2e129a8d212.png)
https://user-images.githubusercontent.com/2068130/71643415-c3933d80-2cb9-11ea-91d1-a2e129a8d212.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71643421-d60d7700-2cb9-11ea-98c7-b3204fc89a30.png
