### ISSUE TITLE
Wikiloc Outdoor Navigation GPS

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10588]
**App Name:** Wikiloc Outdoor Navigation GPS
**Bundle ID:** com.wikiloc.wikiloc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432102730">432102730</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wikiloc-outdoor-navigation-gps/id432102730?uo=4">https://apps.apple.com/us/app/wikiloc-outdoor-navigation-gps/id432102730?uo=4</a>
**App Version:** 3.8.6
**Seller:** Wikiloc Outdoor SL
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wikiloc-outdoor-sl/id432102733?uo=4">© Wikiloc Outdoor SL</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/cc/2c/e2/cc2ce2dc-452c-a539-5720-59ea96661286/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/71525345-856cd700-28d1-11ea-817d-8666ba8658aa.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/71525345-856cd700-28d1-11ea-817d-8666ba8658aa.png)
https://user-images.githubusercontent.com/20930745/71525345-856cd700-28d1-11ea-817d-8666ba8658aa.png

Source:
https://user-images.githubusercontent.com/20930745/71525346-869e0400-28d1-11ea-8182-ddf5b98249b9.png
