### ISSUE TITLE
Sesame Street

### ISSUE THREAD

**Issue by iCarlyga** [glasklart/hd#10589]
**App Name:** Sesame Street
**Bundle ID:** com.sesameworkshop.sesamegoapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=912435108">912435108</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sesame-street/id912435108?uo=4">https://apps.apple.com/us/app/sesame-street/id912435108?uo=4</a>
**App Version:** 3.1.6
**Seller:** Sesame Workshop Apps
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sesame-street/id339077104?uo=4">© Sesame Street</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/8d/c4/c0/8dc4c0c4-d82a-219c-4f16-791b683a3156/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71553538-83aa2d00-2a11-11ea-8a20-f780b4acce61.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71553538-83aa2d00-2a11-11ea-8a20-f780b4acce61.png)
https://user-images.githubusercontent.com/2068130/71553538-83aa2d00-2a11-11ea-8a20-f780b4acce61.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71553541-9290df80-2a11-11ea-8051-80886f50ae19.png
