### ISSUE TITLE
Five Nights at Freddy's AR

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#10586]
**App Name:** Five Nights at Freddy's AR
**Bundle ID:** com.illumix.fnafar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1473886685">1473886685</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/five-nights-at-freddys-ar/id1473886685?uo=4">https://apps.apple.com/us/app/five-nights-at-freddys-ar/id1473886685?uo=4</a>
**App Version:** 2.0.2
**Seller:** Illumix, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/illumix-inc/id1286558265?uo=4">© Illumix, Inc.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/8d/f6/aa/8df6aab8-5313-1b5f-2636-c110b7aea678/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643477-7c597c80-2cba-11ea-9a2f-5bb086cdd954.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71643477-7c597c80-2cba-11ea-9a2f-5bb086cdd954.png)
https://user-images.githubusercontent.com/2068130/71643477-7c597c80-2cba-11ea-9a2f-5bb086cdd954.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71643481-8bd8c580-2cba-11ea-8ea9-1c557c38f03a.png
