### ISSUE TITLE
s.Oliver | Mode & Styles

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10599]
**App Name:** s.Oliver | Mode & Styles
**Bundle ID:** com.soliver.inyourpocket
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=680660018">680660018</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/s-oliver-mode-styles/id680660018?uo=4">https://apps.apple.com/de/app/s-oliver-mode-styles/id680660018?uo=4</a>
**App Version:** 5.1.1
**Seller:** s.Oliver Bernd Freier GmbH & Co. KG
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/s-oliver/id680660021?uo=4">© s.Oliver</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/80/bb/45/80bb4581-a7b6-6eba-1404-4e39d1ccdae5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/72217839-f3510980-3533-11ea-9a55-3f5bb331931d.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/72217839-f3510980-3533-11ea-9a55-3f5bb331931d.png)
https://user-images.githubusercontent.com/2068130/72217839-f3510980-3533-11ea-9a55-3f5bb331931d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/72217842-0532ac80-3534-11ea-8bf8-3dcbe1e686cf.png
