### ISSUE TITLE
腾讯视频-庆余年热播

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10591]
**App Name:** 腾讯视频-庆余年热播
**Bundle ID:** com.tencent.live4iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=458318329">458318329</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/%E8%85%BE%E8%AE%AF%E8%A7%86%E9%A2%91-%E5%BA%86%E4%BD%99%E5%B9%B4%E7%83%AD%E6%92%AD/id458318329?uo=4">https://apps.apple.com/us/app/%E8%85%BE%E8%AE%AF%E8%A7%86%E9%A2%91-%E5%BA%86%E4%BD%99%E5%B9%B4%E7%83%AD%E6%92%AD/id458318329?uo=4</a>
**App Version:** 7.7.9
**Seller:** Tencent Technology (Shenzhen) Company Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tencent-technology-shenzhen-company-limited/id292374531?uo=4">© Tencent Technology (Shenzhen) Company Limited</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/05/b2/ea/05b2eaf4-bf1a-5841-848e-abad8cf5dec3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/71639400-409cc380-2c76-11ea-9ee1-91ef7d52bd8b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/71639400-409cc380-2c76-11ea-9ee1-91ef7d52bd8b.png)
https://user-images.githubusercontent.com/20930745/71639400-409cc380-2c76-11ea-9ee1-91ef7d52bd8b.png

Source:
https://user-images.githubusercontent.com/20930745/71639401-42668700-2c76-11ea-9d04-cefa79e591ec.png
