### ISSUE TITLE
PlayStation®App

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#106]
**App Name:** PlayStation®App
**Bundle ID:** com.playstation.eu.playstationadhoc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=410896080">410896080</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/playstation-app/id410896080?mt=8&uo=4">https://itunes.apple.com/us/app/playstation-app/id410896080?mt=8&uo=4</a>
**App Version:** 2.55.7
**Seller:** PlayStation Mobile Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/playstation-mobile-inc./id912472174?uo=4>© PlayStation Mobile Inc.</a>
**Supported Devices:** iPhone4, iPadThirdGen4G, iPadFourthGen4G, iPadThirdGen, iPadMini4G, iPhone6Plus, iPadFourthGen, iPad2Wifi, iPhone4S, iPodTouchFourthGen, iPodTouchFifthGen, iPhone-3GS, iPhone5, iPadMini, iPhone5s, iPhone6, iPhone5c, iPad23G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/75/3d/87/753d877b-edf7-904b-18d6-e536f64e2a48/mzl.ewfhinrd.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8521459/0a2ea24a-23e4-11e5-82ca-ece3e8ae3bae.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8521429/c3a9a8d8-23e3-11e5-9b6a-dc730e77244f.png)
https://cloud.githubusercontent.com/assets/10730122/8521429/c3a9a8d8-23e3-11e5-9b6a-dc730e77244f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8521427/c0ca0374-23e3-11e5-9bcd-f4f529ad39d0.png
