### ISSUE TITLE
TOM TAILOR: Finde deinen Look

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10602]
**App Name:** TOM TAILOR: Finde deinen Look
**Bundle ID:** com.tomtailor.shop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1461042986">1461042986</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tom-tailor-finde-deinen-look/id1461042986?uo=4">https://apps.apple.com/us/app/tom-tailor-finde-deinen-look/id1461042986?uo=4</a>
**App Version:** 1.3.1
**Seller:** TOM TAILOR E-Commerce GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tom-tailor-e-commerce-gmbh/id1461042115?uo=4">© TOM TAILOR E-Commerce GmbH</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/26/ac/e1/26ace1cc-4baa-b3ad-1eb6-9da2d58ccbe8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/72676687-5c84cf80-3a94-11ea-8162-cf36d6ca480a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/72676687-5c84cf80-3a94-11ea-8162-cf36d6ca480a.png)
https://user-images.githubusercontent.com/2068130/72676687-5c84cf80-3a94-11ea-8162-cf36d6ca480a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/72676704-71f9f980-3a94-11ea-819b-200f7c564d3e.png
