### ISSUE TITLE
Douglas - Parfüm & Kosmetik

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10600]
**App Name:** Douglas - Parfüm & Kosmetik
**Bundle ID:** de.douglas.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=394685685">394685685</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/douglas-parf%C3%BCm-kosmetik/id394685685?uo=4">https://apps.apple.com/de/app/douglas-parf%C3%BCm-kosmetik/id394685685?uo=4</a>
**App Version:** 7.3.9
**Seller:** Parfumerie Douglas GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/parf%C3%BCmerie-douglas-gmbh/id394685688?uo=4">© Parfümerie Douglas GmbH</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/02/f4/b4/02f4b4cd-be64-437f-7e2c-270cbf129c5f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/72218621-1e8c2680-353d-11ea-8564-080da628cbc8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/72218621-1e8c2680-353d-11ea-8564-080da628cbc8.png)
https://user-images.githubusercontent.com/2068130/72218621-1e8c2680-353d-11ea-8564-080da628cbc8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/72218625-2e0b6f80-353d-11ea-9aca-f2442e08194e.png
