### ISSUE TITLE
Never lose your phone: WatchIt

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10609]
**App Name:** Never lose your phone: WatchIt
**Bundle ID:** net.laertes.watchit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1450933233">1450933233</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/never-lose-your-phone-watchit/id1450933233?uo=4">https://apps.apple.com/us/app/never-lose-your-phone-watchit/id1450933233?uo=4</a>
**App Version:** 2.2
**Seller:** GL SQUARED SRLS
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gl-squared-srls/id1450933232?uo=4">© GL SQUARED SRLS</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/4b/2a/80/4b2a80f1-21a8-74a8-1e26-bfee1861e050/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73118898-c13f9e80-3f5a-11ea-8925-eb72f9eec4b8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73118898-c13f9e80-3f5a-11ea-8925-eb72f9eec4b8.png)
https://user-images.githubusercontent.com/2068130/73118898-c13f9e80-3f5a-11ea-8925-eb72f9eec4b8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73118904-d3214180-3f5a-11ea-9300-8eca176e7075.png
