### ISSUE TITLE
Boulder Area Trails

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10601]
**App Name:** Boulder Area Trails
**Bundle ID:** gov.co.bat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1456295463">1456295463</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/boulder-area-trails/id1456295463?uo=4">https://apps.apple.com/us/app/boulder-area-trails/id1456295463?uo=4</a>
**App Version:** 1.0
**Seller:** Boulder County
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/boulder-county/id442544778?uo=4">© Boulder County</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/a9/54/56/a9545650-daec-1fc9-0a69-858c0e8a4fea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/72219459-acb8da80-3546-11ea-832c-17bdcb1575cd.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/72219459-acb8da80-3546-11ea-832c-17bdcb1575cd.png)
https://user-images.githubusercontent.com/2068130/72219459-acb8da80-3546-11ea-832c-17bdcb1575cd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/72219465-be9a7d80-3546-11ea-979b-f4d89e2a9fe1.png
