### ISSUE TITLE
Spotbros

### ISSUE THREAD

**Issue by klauzy** [glasklart/hd#1060]
**App Name:** Spotbros
**Bundle ID:** com.spotbros.spotbros
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555289742">555289742</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spotbros/id555289742?mt=8&uo=4">https://itunes.apple.com/us/app/spotbros/id555289742?mt=8&uo=4</a>
**App Version:** 4.0.14
**Seller:** SPOTBROS TECHNOLOGIES S.L
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/spotbros-technologies-s.l./id555289745?uo=4>© SPOTBROS TECHNOLOGIES S.L.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/e7/6b/35/e76b3587-54ce-dccf-af09-f9ee6b40aef6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19288900/87b6fe9c-9008-11e6-8c51-19f41b80ee6a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19233267/c597bc30-8ee4-11e6-9a1d-bfb1b781ef76.png)
https://cloud.githubusercontent.com/assets/20930745/19233267/c597bc30-8ee4-11e6-9a1d-bfb1b781ef76.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19233282/d526eed2-8ee4-11e6-9cc6-2f022f28a8af.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19288900/87b6fe9c-9008-11e6-8c51-19f41b80ee6a.png)
https://cloud.githubusercontent.com/assets/20930745/19288900/87b6fe9c-9008-11e6-8c51-19f41b80ee6a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19288918/98b1e586-9008-11e6-8668-5a2b70f9e588.png
