### ISSUE TITLE
BlueBuzz Location Notification

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10608]
**App Name:** BlueBuzz Location Notification
**Bundle ID:** com.homeaidepi.bluebuzz1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1469760915">1469760915</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bluebuzz-location-notification/id1469760915?uo=4">https://apps.apple.com/us/app/bluebuzz-location-notification/id1469760915?uo=4</a>
**App Version:** 13.1
**Seller:** Matthew Vandergrift
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/matthew-vandergrift/id1461434350?uo=4">© Matthew Vandergrift</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/f3/e5/dd/f3e5dd12-63d0-5a90-f940-65571657c2ac/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73118747-a53afd80-3f58-11ea-83a5-5db976f74821.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73118747-a53afd80-3f58-11ea-83a5-5db976f74821.png)
https://user-images.githubusercontent.com/2068130/73118747-a53afd80-3f58-11ea-83a5-5db976f74821.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73118749-b4ba4680-3f58-11ea-9125-776eae31c332.png
