### ISSUE TITLE
抖音短视频

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10605]
**App Name:** 抖音短视频
**Bundle ID:** com.ss.iphone.ugc.Aweme
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1142110895">1142110895</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/cn/app/%E6%8A%96%E9%9F%B3%E7%9F%AD%E8%A7%86%E9%A2%91/id1142110895?uo=4">https://apps.apple.com/cn/app/%E6%8A%96%E9%9F%B3%E7%9F%AD%E8%A7%86%E9%A2%91/id1142110895?uo=4</a>
**App Version:** 9.6.0
**Seller:** Beijing Microlive Vision Technology Co., Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/cn/developer/beijing-microlive-vision-technology-co-ltd/id1170416082?uo=4">© Beijing Microlive Vision Technology Co., Ltd</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/44/9d/d1/449dd155-ce89-f199-3b7d-3c1966f2d297/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838007-b75d0400-bc76-11e9-8894-77633c8b1fa4.png)

**Comment by liavoid** [comment]
Can you please make the icon without 分20亿 at the bottom? Like tiktok app logo.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838007-b75d0400-bc76-11e9-8894-77633c8b1fa4.png)
https://user-images.githubusercontent.com/2068130/62838007-b75d0400-bc76-11e9-8894-77633c8b1fa4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838012-c9d73d80-bc76-11e9-9493-4681d9168510.png
