### ISSUE TITLE
Hangouts Meet by Google

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10606]
**App Name:** Hangouts Meet by Google
**Bundle ID:** com.google.meetings
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1013231476">1013231476</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hangouts-meet-by-google/id1013231476?uo=4">https://apps.apple.com/us/app/hangouts-meet-by-google/id1013231476?uo=4</a>
**App Version:** 36.5.0
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/8e/40/e1/8e40e130-45ff-282d-35bc-56edeba6ec8b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/72925207-9a168080-3d52-11ea-9310-0dd709f7e57b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/72925207-9a168080-3d52-11ea-9310-0dd709f7e57b.png)
https://user-images.githubusercontent.com/20930745/72925207-9a168080-3d52-11ea-9310-0dd709f7e57b.png

https://user-images.githubusercontent.com/20930745/72925212-9be04400-3d52-11ea-94f9-0842edf0e0f7.png
