### ISSUE TITLE
MOBELEASH

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10607]
**App Name:** MOBELEASH
**Bundle ID:** com.inquizie.mobeleash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1465806966">1465806966</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mobeleash/id1465806966?uo=4">https://apps.apple.com/us/app/mobeleash/id1465806966?uo=4</a>
**App Version:** 1.0.5
**Seller:** Inquizie Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/inquizie/id1084036916?uo=4">© INQUIZIE</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/0e/e3/d5/0ee3d5f9-fc51-d5eb-dcb3-7c03059dec99/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/72924783-d1386200-3d51-11ea-97f0-370af1e609ec.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/72924783-d1386200-3d51-11ea-97f0-370af1e609ec.png)
https://user-images.githubusercontent.com/20930745/72924783-d1386200-3d51-11ea-97f0-370af1e609ec.png

Source:
https://user-images.githubusercontent.com/20930745/72924788-d3022580-3d51-11ea-95fb-6c0968ab7293.png
