### ISSUE TITLE
2048 Balls 3D

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10617]
**App Name:** 2048 Balls 3D
**Bundle ID:** com.ilya.dropballs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1485247734">1485247734</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/2048-balls-3d/id1485247734?uo=4">https://apps.apple.com/us/app/2048-balls-3d/id1485247734?uo=4</a>
**App Version:** 1.6.1
**Seller:** Voodoo
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/voodoo/id714804730?uo=4">© Voodoo</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/96/81/f0/9681f08f-2531-2244-d097-69c856e0b43e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73138165-ecf87c80-405f-11ea-8bf6-3a0de9646747.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73138165-ecf87c80-405f-11ea-8bf6-3a0de9646747.png)
https://user-images.githubusercontent.com/2068130/73138165-ecf87c80-405f-11ea-8bf6-3a0de9646747.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73138168-fc77c580-405f-11ea-9542-e62b83194b10.png
