### ISSUE TITLE
crowdDJ

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10615]
**App Name:** crowdDJ
**Bundle ID:** com.Nightlife.crowdDJ
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911666442">911666442</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/crowddj/id911666442?uo=4">https://apps.apple.com/us/app/crowddj/id911666442?uo=4</a>
**App Version:** 2.40
**Seller:** Nightlife Music Pty Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nightlife-music-pty-ltd/id867370910?uo=4">© Nightlife Music Pty Ltd</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/9a/8d/6d/9a8d6de1-3028-de65-49e3-2b4f36170725/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73135241-320cb680-4040-11ea-8ad3-ec9cd323c55b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73135241-320cb680-4040-11ea-8ad3-ec9cd323c55b.png)
https://user-images.githubusercontent.com/20930745/73135241-320cb680-4040-11ea-8ad3-ec9cd323c55b.png

Source:
https://user-images.githubusercontent.com/20930745/73135243-333de380-4040-11ea-8ed7-d19bac2620de.png
