### ISSUE TITLE
Akinator

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10619]
**App Name:** Akinator
**Bundle ID:** com.elokence.akinator.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=933135994">933135994</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/akinator/id933135994?uo=4">https://apps.apple.com/us/app/akinator/id933135994?uo=4</a>
**App Version:** 7.0.7
**Seller:** Elokence.com
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/elokence/id484090404?uo=4">© Elokence</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/83/fc/d2/83fcd281-cc6a-ae19-bcab-1f2b7188f15d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73134394-4946a680-4036-11ea-9bbb-65c935d46cb5.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73134394-4946a680-4036-11ea-9bbb-65c935d46cb5.png)
https://user-images.githubusercontent.com/2068130/73134394-4946a680-4036-11ea-9bbb-65c935d46cb5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73134399-595e8600-4036-11ea-81a8-dac4f00c6814.png
