### ISSUE TITLE
Vintage Camera - Dazz

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10618]
**App Name:** Vintage Camera - Dazz
**Bundle ID:** dazz.camera.vintagecamera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1422471180">1422471180</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/vintage-camera-dazz/id1422471180?uo=4">https://apps.apple.com/us/app/vintage-camera-dazz/id1422471180?uo=4</a>
**App Version:** 1.7.8
**Seller:** haiyan wang
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/haiyan-wang/id1422471179?uo=4">© haiyan wang</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/7e/99/61/7e996128-3092-976d-2e3a-24fc2335eb9f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73134567-1bfaf800-4038-11ea-95be-1a4a67e2bd67.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73134567-1bfaf800-4038-11ea-95be-1a4a67e2bd67.png)
https://user-images.githubusercontent.com/2068130/73134567-1bfaf800-4038-11ea-95be-1a4a67e2bd67.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73134575-2ae1aa80-4038-11ea-9316-453f837c5c9c.png
