### ISSUE TITLE
VicEmergency

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10614]
**App Name:** VicEmergency
**Bundle ID:** com.collabforge.fireready
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=356559665">356559665</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/vicemergency/id356559665?uo=4">https://apps.apple.com/us/app/vicemergency/id356559665?uo=4</a>
**App Version:** 6.2.4
**Seller:** State of Victoria - Department of Justice
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/state-of-victoria-department-of-justice/id688084760?uo=4">© State of Victoria - Department of Justice</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/ab/32/54/ab32547e-2217-8006-1a0a-2b8ef6a6318c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73135499-38e8f880-4043-11ea-9016-eb3f8d59e6d9.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73135499-38e8f880-4043-11ea-9016-eb3f8d59e6d9.png)
https://user-images.githubusercontent.com/20930745/73135499-38e8f880-4043-11ea-9016-eb3f8d59e6d9.png

Source:
https://user-images.githubusercontent.com/20930745/73135500-3ab2bc00-4043-11ea-973c-af9ed7f774d8.png
