### ISSUE TITLE
Threads from Instagram

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10611]
**App Name:** Threads from Instagram
**Bundle ID:** com.burbn.threads
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1473867767">1473867767</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/threads-from-instagram/id1473867767?uo=4">https://apps.apple.com/us/app/threads-from-instagram/id1473867767?uo=4</a>
**App Version:** 1.1.3
**Seller:** Instagram, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/instagram-inc/id389801255?uo=4">© Instagram, Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/bf/b2/23/bfb22323-af6b-3ff6-c265-5bb48c9d19ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73134976-5f0b9a00-403d-11ea-9233-69140324c3d4.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73134976-5f0b9a00-403d-11ea-9233-69140324c3d4.png)
https://user-images.githubusercontent.com/20930745/73134976-5f0b9a00-403d-11ea-9233-69140324c3d4.png

Source:
https://user-images.githubusercontent.com/20930745/73134979-63d04e00-403d-11ea-88b7-c9e4602f2043.png
