### ISSUE TITLE
byte - creativity first

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10612]
**App Name:** byte - creativity first
**Bundle ID:** co.byte.video
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1441800002">1441800002</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/byte-creativity-first/id1441800002?uo=4">https://apps.apple.com/us/app/byte-creativity-first/id1441800002?uo=4</a>
**App Version:** 0.2
**Seller:** Byte Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/byte-inc/id1021378990?uo=4">© Byte Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/c9/52/03/c95203e4-2d70-4df8-5c32-04a96e971c94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73135081-c249fc00-403e-11ea-994c-b2c2c23f3fd1.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73135081-c249fc00-403e-11ea-994c-b2c2c23f3fd1.png)
https://user-images.githubusercontent.com/20930745/73135081-c249fc00-403e-11ea-994c-b2c2c23f3fd1.png

Source:
https://user-images.githubusercontent.com/20930745/73135083-c413bf80-403e-11ea-9a20-e00cb7fac69a.png
