### ISSUE TITLE
Public Transport Victoria app

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10616]
**App Name:** Public Transport Victoria app
**Bundle ID:** com.metlinkmelbourne.iphone.carrot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=318696180">318696180</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/public-transport-victoria-app/id318696180?uo=4">https://apps.apple.com/us/app/public-transport-victoria-app/id318696180?uo=4</a>
**App Version:** 3.5.0
**Seller:** Public Transport Development Authority
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/public-transport-victoria/id858229901?uo=4">© Public Transport Victoria</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/e7/9f/04/e79f04c3-bbad-8a31-5a2c-278a88c4b6bd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73134417-962a7d00-4036-11ea-8347-f5266161cbc6.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73134417-962a7d00-4036-11ea-8347-f5266161cbc6.png)
https://user-images.githubusercontent.com/2068130/73134417-962a7d00-4036-11ea-8347-f5266161cbc6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73134422-a9d5e380-4036-11ea-8003-878ddd56bcc4.png

**Comment by dreamnet** [comment]
Icon is [already themed](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.metlinkmelbourne.iphone.carrot-large.png) - no commit needed.
