### ISSUE TITLE
GameClub - a new way to play!

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10610]
**App Name:** GameClub - a new way to play!
**Bundle ID:** gameclub.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1339587140">1339587140</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gameclub-a-new-way-to-play/id1339587140?uo=4">https://apps.apple.com/us/app/gameclub-a-new-way-to-play/id1339587140?uo=4</a>
**App Version:** 1.0.18
**Seller:** GameClub Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gameclub/id1339587139?uo=4">© GameClub</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/9b/97/76/9b977634-c392-22ba-ce95-ae6c4c2e29a3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73135395-bc094f00-4041-11ea-8cbc-8ab3b4d85c92.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73135395-bc094f00-4041-11ea-8cbc-8ab3b4d85c92.png)
https://user-images.githubusercontent.com/20930745/73135395-bc094f00-4041-11ea-8cbc-8ab3b4d85c92.png

Source:
https://user-images.githubusercontent.com/20930745/73135397-bdd31280-4041-11ea-9e04-ab9acc9c0fd8.png
