### ISSUE TITLE
BusyCal: Calendar & Todos

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10637]
**App Name:** BusyCal: Calendar & Todos
**Bundle ID:** com.busymac.BusyCaliOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035689743">1035689743</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/busycal-calendar-todos/id1035689743?uo=4">https://apps.apple.com/us/app/busycal-calendar-todos/id1035689743?uo=4</a>
**App Version:** 3.5.95
**Seller:** Busy Apps FZE
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/busy-apps-fze/id409966805?uo=4">© Busy Apps FZE</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/10/74/79/107479dc-5281-ecfa-947a-6ad348c5f82f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73666695-797bee00-46a3-11ea-92b4-ba1ba78b075c.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73666695-797bee00-46a3-11ea-92b4-ba1ba78b075c.png)
https://user-images.githubusercontent.com/20930745/73666695-797bee00-46a3-11ea-92b4-ba1ba78b075c.png

Source:
https://user-images.githubusercontent.com/20930745/73666700-7bde4800-46a3-11ea-871f-4a80dce98a31.png
