### ISSUE TITLE
Doppi

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10634]
**App Name:** Doppi
**Bundle ID:** com.ondalabs.doppi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1002899671">1002899671</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/doppi/id1002899671?uo=4">https://apps.apple.com/us/app/doppi/id1002899671?uo=4</a>
**App Version:** 3.4
**Seller:** Radu Dutzan
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/radu-dutzan/id1090301223?uo=4">© Radu Dutzan</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/38/2f/d8/382fd8ab-8c0f-881f-a3f0-b804dad9f35b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73614459-8941f680-45ff-11ea-8dc8-3f3ebd497146.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73614459-8941f680-45ff-11ea-8dc8-3f3ebd497146.png)
https://user-images.githubusercontent.com/2068130/73614459-8941f680-45ff-11ea-8dc8-3f3ebd497146.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73614464-9828a900-45ff-11ea-88f6-23ebc27acdb5.png
