### ISSUE TITLE
UNATION - Find Events Near You

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10636]
**App Name:** UNATION - Find Events Near You
**Bundle ID:** com.unation.unation-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953269522">953269522</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/unation-find-events-near-you/id953269522?uo=4">https://apps.apple.com/us/app/unation-find-events-near-you/id953269522?uo=4</a>
**App Version:** 3.2
**Seller:** UNATION, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/unation-llc/id953269521?uo=4">© UNATION, LLC</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/45/95/80/459580ad-f389-c933-1fff-c9d08f99a5e9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73611964-d87c2d00-45e7-11ea-9440-7e87e5f6fcc3.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73611964-d87c2d00-45e7-11ea-9440-7e87e5f6fcc3.png)
https://user-images.githubusercontent.com/20930745/73611964-d87c2d00-45e7-11ea-9440-7e87e5f6fcc3.png

Source:
https://user-images.githubusercontent.com/20930745/73611966-da45f080-45e7-11ea-9ab0-95493355f403.png
