### ISSUE TITLE
MagentaTV Serien, TV Streaming

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10639]
**App Name:** MagentaTV Serien, TV Streaming
**Bundle ID:** de.telekom.entertaintv-iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1054468721">1054468721</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/magentatv-serien-tv-streaming/id1054468721?uo=4">https://apps.apple.com/us/app/magentatv-serien-tv-streaming/id1054468721?uo=4</a>
**App Version:** 2.11.55
**Seller:** Telekom Deutschland GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/telekom-deutschland-gmbh/id930125248?uo=4">© Telekom Deutschland GmbH</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/34/ac/d1/34acd191-9c9a-9485-dec6-6560c629c526/source/512x512bb.jpg" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74079787-66b73f80-4a3c-11ea-9148-e3e34304f4e0.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74079787-66b73f80-4a3c-11ea-9148-e3e34304f4e0.png)
https://user-images.githubusercontent.com/2068130/74079787-66b73f80-4a3c-11ea-9148-e3e34304f4e0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/74079792-78004c00-4a3c-11ea-88a7-d6413e9fafb9.png
