### ISSUE TITLE
Microsoft Math Solver

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10635]
**App Name:** Microsoft Math Solver
**Bundle ID:** com.microsoft.math
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1483962204">1483962204</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/microsoft-math-solver/id1483962204?uo=4">https://apps.apple.com/us/app/microsoft-math-solver/id1483962204?uo=4</a>
**App Version:** 1.0.6
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/microsoft-corporation/id298856275?uo=4">© Microsoft Corporation</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/e3/1b/b0/e31bb01a-1679-57ee-2187-f930ba911085/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73612179-a9ff5180-45e9-11ea-9f5a-7e7bfb8a8ca1.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73612179-a9ff5180-45e9-11ea-9f5a-7e7bfb8a8ca1.png)
https://user-images.githubusercontent.com/20930745/73612179-a9ff5180-45e9-11ea-9f5a-7e7bfb8a8ca1.png

Source:
https://user-images.githubusercontent.com/20930745/73612181-abc91500-45e9-11ea-8c3a-b4a452efcf5b.png
