### ISSUE TITLE
Axis Bank Mobile Banking

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10642]
**App Name:** Axis Bank Mobile Banking
**Bundle ID:** com.axisbank.axismobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=699582556">699582556</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/axis-bank-mobile-banking/id699582556?uo=4">https://apps.apple.com/us/app/axis-bank-mobile-banking/id699582556?uo=4</a>
**App Version:** 6.2
**Seller:** Axis Bank Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/axis-bank-ltd/id517259642?uo=4">© Axis Bank Ltd</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/65/67/73/656773c9-aadb-cc8f-3441-5fce5e5c3740/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74086738-24b2eb80-4a86-11ea-8e28-b134269ad7fc.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74086738-24b2eb80-4a86-11ea-8e28-b134269ad7fc.png)
https://user-images.githubusercontent.com/20930745/74086738-24b2eb80-4a86-11ea-8e28-b134269ad7fc.png

Source:
https://user-images.githubusercontent.com/20930745/74086739-267caf00-4a86-11ea-8c49-f359d1a6ef5f.png
