### ISSUE TITLE
AXS Tickets

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10641]
**App Name:** AXS Tickets
**Bundle ID:** com.axs.AXSMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=679805463">679805463</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/axs-tickets/id679805463?uo=4">https://apps.apple.com/us/app/axs-tickets/id679805463?uo=4</a>
**App Version:** 4.4.4
**Seller:** AXS Digital, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/axs/id679805466?uo=4">© AXS</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/f5/b6/39/f5b6390b-cda5-a4e5-50ea-59501a66aedc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74038179-0c789900-49c0-11ea-90ab-42c67b29f7a9.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74038179-0c789900-49c0-11ea-90ab-42c67b29f7a9.png)
https://user-images.githubusercontent.com/20930745/74038179-0c789900-49c0-11ea-90ab-42c67b29f7a9.png

Source:
https://user-images.githubusercontent.com/20930745/74038183-0e425c80-49c0-11ea-9e60-0d62641636b8.png
