### ISSUE TITLE
Mein Globus

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10640]
**App Name:** Mein Globus
**Bundle ID:** de.globus.meinglobus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1405626786">1405626786</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/mein-globus/id1405626786?uo=4">https://apps.apple.com/de/app/mein-globus/id1405626786?uo=4</a>
**App Version:** 2.0.6
**Seller:** Globus SB-Warenhaus Holding GmbH & Co. KG
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/globus-sb-warenhaus-holding-gmbh-co-kg/id1405626785?uo=4">© GLOBUS SB-Warenhaus Holding GmbH & Co. KG</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/c8/c6/1d/c8c61d45-5ef0-998e-513e-94708449ede5/source/512x512bb.jpg" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74079848-3e7c1080-4a3d-11ea-8c0f-64a4e6521460.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74079848-3e7c1080-4a3d-11ea-8c0f-64a4e6521460.png)
https://user-images.githubusercontent.com/2068130/74079848-3e7c1080-4a3d-11ea-8c0f-64a4e6521460.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/74079856-4f2c8680-4a3d-11ea-8bec-a19136fe73a0.png
