### ISSUE TITLE
BookMyShow Entertainment

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10648]
**App Name:** BookMyShow Entertainment
**Bundle ID:** BookMyShow.com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405894842">405894842</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bookmyshow-entertainment/id405894842?uo=4">https://apps.apple.com/us/app/bookmyshow-entertainment/id405894842?uo=4</a>
**App Version:** 4.8.8
**Seller:** Bigtree Entertainment Pvt. Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bigtree-entertainment-pvt-ltd/id405891629?uo=4">© Bigtree Entertainment Pvt. Ltd.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/c7/09/37/c709372c-6336-9cfd-184d-cbfd18c85a51/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74087224-86755480-4a8a-11ea-8895-afe632d43d5e.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74087224-86755480-4a8a-11ea-8895-afe632d43d5e.png)
https://user-images.githubusercontent.com/20930745/74087224-86755480-4a8a-11ea-8895-afe632d43d5e.png

Source:
https://user-images.githubusercontent.com/20930745/74087225-883f1800-4a8a-11ea-917f-73e550b571cb.png
