### ISSUE TITLE
Swiggy Food Order & Delivery

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10649]
**App Name:** Swiggy Food Order & Delivery
**Bundle ID:** bundl.swiggy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989540920">989540920</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/swiggy-food-order-delivery/id989540920?uo=4">https://apps.apple.com/us/app/swiggy-food-order-delivery/id989540920?uo=4</a>
**App Version:** 3.2.3
**Seller:** BUNDL TECHNOLOGIES PRIVATE LIMITED
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bundl-technologies-private-limited/id989540919?uo=4">© BUNDL TECHNOLOGIES PRIVATE LIMITED</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/7f/c2/09/7fc20971-3fa4-d1b0-9e42-c5f3b930ed36/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74087284-f5eb4400-4a8a-11ea-8db1-adda1a99ac46.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74087284-f5eb4400-4a8a-11ea-8db1-adda1a99ac46.png)
https://user-images.githubusercontent.com/20930745/74087284-f5eb4400-4a8a-11ea-8db1-adda1a99ac46.png

Source:
https://user-images.githubusercontent.com/20930745/74087285-f7b50780-4a8a-11ea-8a93-1affff857469.png
