### ISSUE TITLE
Wyze

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10644]
**App Name:** Wyze
**Bundle ID:** com.hualai.WyzeCam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1288415553">1288415553</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wyze/id1288415553?uo=4">https://apps.apple.com/us/app/wyze/id1288415553?uo=4</a>
**App Version:** 2.8.20
**Seller:** Wyze Labs, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wyze-labs/id1403960095?uo=4">© Wyze Labs</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/46/33/ae/4633ae35-b651-5f25-7076-e9ea8743e6ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74086843-334dd280-4a87-11ea-84a8-4f554b4e8108.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74086843-334dd280-4a87-11ea-84a8-4f554b4e8108.png)
https://user-images.githubusercontent.com/20930745/74086843-334dd280-4a87-11ea-84a8-4f554b4e8108.png

Source:
https://user-images.githubusercontent.com/20930745/74086844-35179600-4a87-11ea-953a-f2949664d380.png
