### ISSUE TITLE
Accounting app - Zoho Books

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10643]
**App Name:** Accounting app - Zoho Books
**Bundle ID:** com.zoho.zbooks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=710446064">710446064</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/accounting-app-zoho-books/id710446064?uo=4">https://apps.apple.com/us/app/accounting-app-zoho-books/id710446064?uo=4</a>
**App Version:** 4.6.9
**Seller:** Zoho Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/zoho-corporation/id388384807?uo=4">© Zoho Corporation</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/86/0c/2a/860c2a49-3de2-de95-bf6c-a067a5e23df6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74086796-adca2280-4a86-11ea-84bb-18834cc1585b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74086796-adca2280-4a86-11ea-84bb-18834cc1585b.png)
https://user-images.githubusercontent.com/20930745/74086796-adca2280-4a86-11ea-84bb-18834cc1585b.png

Source:
https://user-images.githubusercontent.com/20930745/74086798-b02c7c80-4a86-11ea-8539-fe472230f29d.png
