### ISSUE TITLE
Google Pay for India (Tez)

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10645]
**App Name:** Google Pay for India (Tez)
**Bundle ID:** com.google.paisa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1193357041">1193357041</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-pay-for-india-tez/id1193357041?uo=4">https://apps.apple.com/us/app/google-pay-for-india-tez/id1193357041?uo=4</a>
**App Version:** 50.0
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/c8/72/27/c87227e2-6bfd-708d-1e80-df3cab4deddf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74087467-da813880-4a8c-11ea-8251-d8d87a177c73.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74087467-da813880-4a8c-11ea-8251-d8d87a177c73.png)
https://user-images.githubusercontent.com/20930745/74087467-da813880-4a8c-11ea-8251-d8d87a177c73.png

Source:
https://user-images.githubusercontent.com/20930745/74087469-dce39280-4a8c-11ea-84f6-778340e365c7.png
