### ISSUE TITLE
Canara OTP

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10647]
**App Name:** Canara OTP
**Bundle ID:** com.canarabank.canaraotp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1411339341">1411339341</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/canara-otp/id1411339341?uo=4">https://apps.apple.com/us/app/canara-otp/id1411339341?uo=4</a>
**App Version:** 1.1
**Seller:** CANARA BANK
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/canara-bank/id854427899?uo=4">© Canara Bank</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/8d/f0/8f/8df08f39-4f6a-38fb-133f-7a673d36e6c5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74087164-00590e00-4a8a-11ea-852d-10948271ae90.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74087164-00590e00-4a8a-11ea-852d-10948271ae90.png)
https://user-images.githubusercontent.com/20930745/74087164-00590e00-4a8a-11ea-852d-10948271ae90.png

Source:
https://user-images.githubusercontent.com/20930745/74087165-0222d180-4a8a-11ea-9ced-bbc38ff8a35a.png
