### ISSUE TITLE
Surfline - Surf Report, Surf Forecast and News

### ISSUE THREAD

**Issue by kanelee** [glasklart/hd#1064]
**App Name:** Surfline - Surf Report, Surf Forecast and News
**Bundle ID:** com.surfline.surfapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393782096">393782096</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/surfline-surf-report-surf/id393782096?mt=8&uo=4">https://itunes.apple.com/us/app/surfline-surf-report-surf/id393782096?mt=8&uo=4</a>
**App Version:** 4.3.1
**Seller:** Surfline/Wavetrak
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/surfline-wavetrak/id329198084?uo=4>© Surfline/Wavetrak</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/ee/1d/4f/ee1d4fee-30a5-3277-0568-a3d5d72fc4fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411606/590ae59a-9305-11e6-8e00-6d1861c0f697.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411606/590ae59a-9305-11e6-8e00-6d1861c0f697.png)
https://cloud.githubusercontent.com/assets/20930745/19411606/590ae59a-9305-11e6-8e00-6d1861c0f697.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411612/685b0764-9305-11e6-87f8-837efc3f87cb.png
