### ISSUE TITLE
Portal Quest

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10654]
**App Name:** Portal Quest
**Bundle ID:** com.perblue.portalquest.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1194050611">1194050611</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/portal-quest/id1194050611?uo=4">https://apps.apple.com/us/app/portal-quest/id1194050611?uo=4</a>
**App Version:** 4.0
**Seller:** PerBlue Entertainment, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/perblue-entertainment-inc/id1157992836?uo=4">© PerBlue Entertainment, Inc</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/c2/a2/0e/c2a20e1b-2760-1350-e151-98687b57330e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74585086-47d72100-4fd9-11ea-975c-8ec8e1c1eb8c.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74585086-47d72100-4fd9-11ea-975c-8ec8e1c1eb8c.png)
https://user-images.githubusercontent.com/20930745/74585086-47d72100-4fd9-11ea-975c-8ec8e1c1eb8c.png

Source:
https://user-images.githubusercontent.com/20930745/74585087-49a0e480-4fd9-11ea-8d6b-e7a8d8733519.png

**Comment by Gwai** [comment]
👍
