### ISSUE TITLE
1&1 TV

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10653]
**App Name:** 1&1 TV
**Bundle ID:** de.1und1.iptv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1229042002">1229042002</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/1-1-tv/id1229042002?uo=4">https://apps.apple.com/de/app/1-1-tv/id1229042002?uo=4</a>
**App Version:** 3.1948.0
**Seller:** 1&1 Telecom GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/1-1-telecom-gmbh/id1229042001?uo=4">© 1&1 Telecom GmbH</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/11/5a/f5/115af51f-5b73-7bfa-ec0a-7c07f5a501d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74583925-ee68f500-4fcc-11ea-9ba9-b72e177a0dc0.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74583925-ee68f500-4fcc-11ea-9ba9-b72e177a0dc0.png)
https://user-images.githubusercontent.com/20930745/74583925-ee68f500-4fcc-11ea-9ba9-b72e177a0dc0.png

Source:
https://user-images.githubusercontent.com/20930745/74583926-f0cb4f00-4fcc-11ea-91de-0ea8bfa8432e.png
