### ISSUE TITLE
Flipkart - Online Shopping App

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10651]
**App Name:** Flipkart - Online Shopping App
**Bundle ID:** com.appflipkart.flipkart
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=742044692">742044692</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/flipkart-online-shopping-app/id742044692?uo=4">https://apps.apple.com/us/app/flipkart-online-shopping-app/id742044692?uo=4</a>
**App Version:** 9.1.0
**Seller:** Flipkart Online Services Pvt Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/flipkart-com/id530448087?uo=4">© Flipkart.com</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/39/e3/42/39e342fb-0cf1-a103-b360-e5af09b977fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74584688-676c4a80-4fd5-11ea-89c7-7b7e879dca06.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74584688-676c4a80-4fd5-11ea-89c7-7b7e879dca06.png)
https://user-images.githubusercontent.com/20930745/74584688-676c4a80-4fd5-11ea-89c7-7b7e879dca06.png

Source:
https://user-images.githubusercontent.com/20930745/74584690-69cea480-4fd5-11ea-88b1-ab180e135012.png
