### ISSUE TITLE
ZeroTier One

### ISSUE THREAD

**Issue by jq1106** [glasklart/hd#10659]
**App Name:** ZeroTier One
**Bundle ID:** com.zerotier.ZeroTier-One
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1084101492">1084101492</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/zerotier-one/id1084101492?uo=4">https://apps.apple.com/us/app/zerotier-one/id1084101492?uo=4</a>
**App Version:** 1.4.4-1
**Seller:** ZeroTier, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/zerotier-inc/id1084101491?uo=4">© ZeroTier, Inc</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/ec/22/6b/ec226bd2-c933-0581-0ccf-333f5fb27c1c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74660728-02605280-5197-11ea-9191-6dd9366717cb.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74660728-02605280-5197-11ea-9191-6dd9366717cb.png)
https://user-images.githubusercontent.com/20930745/74660728-02605280-5197-11ea-9191-6dd9366717cb.png

Source:
https://user-images.githubusercontent.com/20930745/74660732-03917f80-5197-11ea-9ee8-b8d541782897.png
