### ISSUE TITLE
Leberkas-Pepi

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#10652]
**App Name:** Leberkas-Pepi
**Bundle ID:** com.helloagain.leberkaspepi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1228377449">1228377449</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/leberkas-pepi/id1228377449?uo=4">https://apps.apple.com/us/app/leberkas-pepi/id1228377449?uo=4</a>
**App Version:** 1.5.1
**Seller:** hello again GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hello-again-gmbh/id1219689113?uo=4">© hello again GmbH</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/c2/b3/55/c2b35589-740b-7708-5be7-487de9c82053/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74593613-53543780-502d-11ea-894a-e16dd935f295.png)

**Comment by dreamnet** [comment]
Ha - that's the app of one of my business clients... 😄

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74593613-53543780-502d-11ea-894a-e16dd935f295.png)
https://user-images.githubusercontent.com/2068130/74593613-53543780-502d-11ea-894a-e16dd935f295.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/74593620-6404ad80-502d-11ea-87e6-f3a8b7cbe799.png
