### ISSUE TITLE
Baroda mPassbook

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10650]
**App Name:** Baroda mPassbook
**Bundle ID:** com.bob.mpassbook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1142562888">1142562888</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/baroda-mpassbook/id1142562888?uo=4">https://apps.apple.com/us/app/baroda-mpassbook/id1142562888?uo=4</a>
**App Version:** 1.5
**Seller:** Bank of Baroda
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bank-of-baroda/id1142562887?uo=4">© Bank of Baroda</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/87/97/95/87979521-8a91-8d5c-0981-0e0bc9071f09/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74087340-78740380-4a8b-11ea-86d3-b291b5cd79ce.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74087340-78740380-4a8b-11ea-86d3-b291b5cd79ce.png)
https://user-images.githubusercontent.com/20930745/74087340-78740380-4a8b-11ea-86d3-b291b5cd79ce.png

Source:
https://user-images.githubusercontent.com/20930745/74087342-7f9b1180-4a8b-11ea-81f0-b73d73a7e254.png
