### ISSUE TITLE
Soulver

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10665]
**App Name:** Soulver
**Bundle ID:** com.acqualia.soulver-iPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348142037">348142037</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/soulver/id348142037?uo=4">https://apps.apple.com/us/app/soulver/id348142037?uo=4</a>
**App Version:** 2.8.0
**Seller:** Acqualia Software
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/acqualia/id348142040?uo=4">© Acqualia</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/51/33/4b/51334bd3-1b84-84ef-f95b-f70c8f293558/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74664347-d399aa80-519d-11ea-975e-bfad29a3330d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74664347-d399aa80-519d-11ea-975e-bfad29a3330d.png)
https://user-images.githubusercontent.com/20930745/74664347-d399aa80-519d-11ea-975e-bfad29a3330d.png

Source:
https://user-images.githubusercontent.com/20930745/74664349-d5fc0480-519d-11ea-8866-a76ff86d200a.png
