### ISSUE TITLE
Recycle Coach

### ISSUE THREAD

**Issue by jq1106** [glasklart/hd#10663]
**App Name:** Recycle Coach
**Bundle ID:** com.recyclecoach
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1071714967">1071714967</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/recycle-coach/id1071714967?uo=4">https://apps.apple.com/us/app/recycle-coach/id1071714967?uo=4</a>
**App Version:** 9.9.2
**Seller:** Municipal Media Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/municipal-media-inc/id465486249?uo=4">© Municipal Media Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a5/90/52/a590523b-ed4a-76e8-c2ad-e8daec87f2b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74663601-5faad280-519c-11ea-8804-0e915ce63786.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74663601-5faad280-519c-11ea-8804-0e915ce63786.png)
https://user-images.githubusercontent.com/20930745/74663601-5faad280-519c-11ea-8804-0e915ce63786.png

Source:
https://user-images.githubusercontent.com/20930745/74663604-61749600-519c-11ea-95b8-3e05f51616e1.png
