### ISSUE TITLE
Obsidian - OTP Authenticator

### ISSUE THREAD

**Issue by jq1106** [glasklart/hd#10661]
**App Name:** Obsidian - OTP Authenticator
**Bundle ID:** com.r4id4.authenticator-vault
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1189922806">1189922806</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/obsidian-otp-authenticator/id1189922806?uo=4">https://apps.apple.com/us/app/obsidian-otp-authenticator/id1189922806?uo=4</a>
**App Version:** 5.4
**Seller:** tommaso carpi
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tommaso-carpi/id714996025?uo=4">© Tommaso Carpi</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/e9/c1/30/e9c130b7-4782-ac30-1a01-31fa6b0be9c4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74662787-e8287380-519a-11ea-872d-71f72fa99a63.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74662787-e8287380-519a-11ea-872d-71f72fa99a63.png)
https://user-images.githubusercontent.com/20930745/74662787-e8287380-519a-11ea-872d-71f72fa99a63.png

Source:
https://user-images.githubusercontent.com/20930745/74662789-e9f23700-519a-11ea-913c-a80bd8f7c6ae.png
