### ISSUE TITLE
Investing.com Stocks & Finance

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10668]
**App Name:** Investing.com Stocks & Finance
**Bundle ID:** com.investing.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=909998122">909998122</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/investing-com-stocks-finance/id909998122?uo=4">https://apps.apple.com/us/app/investing-com-stocks-finance/id909998122?uo=4</a>
**App Version:** 5.7.2
**Seller:** Fusion Media Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fusion-media-limited/id909998125?uo=4">© Fusion Media Limited</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/c4/b6/71/c4b671c4-f0d9-732e-edfb-e1146a6a98e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74666468-d5656d00-51a1-11ea-9d32-7f628467c47b.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74666468-d5656d00-51a1-11ea-9d32-7f628467c47b.png)
https://user-images.githubusercontent.com/20930745/74666468-d5656d00-51a1-11ea-9d32-7f628467c47b.png

Source:
https://user-images.githubusercontent.com/20930745/74666472-d72f3080-51a1-11ea-99e9-f7a5ee0a8879.png

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/75102994-96308500-55c2-11ea-8e53-de15522b73a6.png)
https://user-images.githubusercontent.com/2313873/75102994-96308500-55c2-11ea-8e53-de15522b73a6.png

___
Source:
https://user-images.githubusercontent.com/2313873/75102992-916bd100-55c2-11ea-90ed-10b238f08b9a.png
