### ISSUE TITLE
MSW Surf Forecast

### ISSUE THREAD

**Issue by kanelee** [glasklart/hd#1066]
**App Name:** MSW Surf Forecast
**Bundle ID:** com.magicseaweed
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=322103952">322103952</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/msw-surf-forecast/id322103952?mt=8&uo=4">https://itunes.apple.com/us/app/msw-surf-forecast/id322103952?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** METCENTRAL LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/magicseaweed/id322103955?uo=4">© Magicseaweed</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/ee/18/93/ee18935f-7417-6c45-bdf9-152c62ce2b08/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32146904-924a233a-bcde-11e7-9278-413cd9a03b70.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32146904-924a233a-bcde-11e7-9278-413cd9a03b70.png)
https://user-images.githubusercontent.com/2068130/32146904-924a233a-bcde-11e7-9278-413cd9a03b70.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32146908-a18b46f8-bcde-11e7-8c0f-d31716c7b363.png
