### ISSUE TITLE
WalletHub

### ISSUE THREAD

**Issue by jq1106** [glasklart/hd#10662]
**App Name:** WalletHub
**Bundle ID:** com.wallethub.mywallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1110552982">1110552982</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wallethub/id1110552982?uo=4">https://apps.apple.com/us/app/wallethub/id1110552982?uo=4</a>
**App Version:** 1.6.2
**Seller:** Evolution Finance, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wallethub/id1110552981?uo=4">© WalletHub</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/b6/2b/31/b62b3188-e543-b36f-d440-d457b8ca3b83/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74663240-ae0ba180-519b-11ea-8ea6-b86ac19c642b.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74663240-ae0ba180-519b-11ea-8ea6-b86ac19c642b.png)
https://user-images.githubusercontent.com/20930745/74663240-ae0ba180-519b-11ea-8ea6-b86ac19c642b.png

Source:
https://user-images.githubusercontent.com/20930745/74663245-afd56500-519b-11ea-9123-4c0bb0dd0fe6.png
