### ISSUE TITLE
YarnLIVE - Yarn Rates, Textile

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10667]
**App Name:** YarnLIVE - Yarn Rates, Textile
**Bundle ID:** com.globalservices.yarnlive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1181868423">1181868423</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/yarnlive-yarn-rates-textile/id1181868423?uo=4">https://apps.apple.com/us/app/yarnlive-yarn-rates-textile/id1181868423?uo=4</a>
**App Version:** 26
**Seller:** Deepak Periwal
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/deepak-periwal/id1181868422?uo=4">© Deepak Periwal</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/0c/32/e2/0c32e2bd-fcfb-f0bb-5ae2-d9b07f6ead7a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74665960-ec578f80-51a0-11ea-85d6-d7a7be1ed941.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74665960-ec578f80-51a0-11ea-85d6-d7a7be1ed941.png)
https://user-images.githubusercontent.com/20930745/74665960-ec578f80-51a0-11ea-85d6-d7a7be1ed941.png

Source:
https://user-images.githubusercontent.com/20930745/74665966-eeb9e980-51a0-11ea-8298-511b3c49a22a.png
