### ISSUE TITLE
Calzy

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10664]
**App Name:** Calzy
**Bundle ID:** com.waplestuff.calzy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=623690732">623690732</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/calzy/id623690732?uo=4">https://apps.apple.com/us/app/calzy/id623690732?uo=4</a>
**App Version:** 3.3.3
**Seller:** Raja V
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/waplestuff/id562575890?uo=4">© WapleStuff</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/2f/cc/56/2fcc5638-f0cd-4f37-a5d0-0ffebe6d06fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74663925-00998d80-519d-11ea-84ed-ee9ecb2c5f91.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74663925-00998d80-519d-11ea-84ed-ee9ecb2c5f91.png)
https://user-images.githubusercontent.com/20930745/74663925-00998d80-519d-11ea-84ed-ee9ecb2c5f91.png

Source:
https://user-images.githubusercontent.com/20930745/74663928-02fbe780-519d-11ea-9322-2e9574c6aba3.png
