### ISSUE TITLE
Blink Home Monitor

### ISSUE THREAD

**Issue by jq1106** [glasklart/hd#10660]
**App Name:** Blink Home Monitor
**Bundle ID:** com.immediasemi.ios.blink
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1013961111">1013961111</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/blink-home-monitor/id1013961111?uo=4">https://apps.apple.com/us/app/blink-home-monitor/id1013961111?uo=4</a>
**App Version:** 5.1.12
**Seller:** Immedia Semiconductor, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/immedia-semiconductor/id1013961110?uo=4">© Immedia Semiconductor</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/1d/95/f0/1d95f0e8-4bfa-83a9-ef3d-261af4b2cb87/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74661093-94685b00-5197-11ea-8768-32937f4fb6e7.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74661093-94685b00-5197-11ea-8768-32937f4fb6e7.png)
https://user-images.githubusercontent.com/20930745/74661093-94685b00-5197-11ea-8768-32937f4fb6e7.png

Source:
https://user-images.githubusercontent.com/20930745/74661096-96321e80-5197-11ea-87cf-d48e331b5bc7.png
