### ISSUE TITLE
MoneyWiz 3 - Personal Finance

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10666]
**App Name:** MoneyWiz 3 - Personal Finance
**Bundle ID:** com.moneywiz.ios.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1004710719">1004710719</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/moneywiz-3-personal-finance/id1004710719?uo=4">https://apps.apple.com/us/app/moneywiz-3-personal-finance/id1004710719?uo=4</a>
**App Version:** 3.7.2
**Seller:** SilverWiz Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/silverwiz-ltd/id380335247?uo=4">© SilverWiz Ltd</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/a2/ba/b3/a2bab391-c139-6f20-3cd6-bcfd5f47dbe9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76160673-6ccc3900-612c-11ea-9cdc-5d23bdf1c63e.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/74905658-5d9b6c00-5374-11ea-866f-018142293025.png)

https://user-images.githubusercontent.com/44279267/74905658-5d9b6c00-5374-11ea-866f-018142293025.png

Source:
https://user-images.githubusercontent.com/44279267/74905686-73a92c80-5374-11ea-9663-333a6acd9b4b.png

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76160673-6ccc3900-612c-11ea-9cdc-5d23bdf1c63e.png)
https://user-images.githubusercontent.com/20930745/76160673-6ccc3900-612c-11ea-9cdc-5d23bdf1c63e.png

Source:
https://user-images.githubusercontent.com/20930745/76160674-6e95fc80-612c-11ea-86dc-695c786ddd48.png
