### ISSUE TITLE
Citibank IN

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10669]
**App Name:** Citibank IN
**Bundle ID:** com.citi.citimobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467987820">467987820</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/citibank-in/id467987820?uo=4">https://apps.apple.com/us/app/citibank-in/id467987820?uo=4</a>
**App Version:** 16.1.1
**Seller:** Citibank, N.A. (India)
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/citibank-n-a-india/id467987825?uo=4">© Citibank N.A. (India)</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/8b/d9/b7/8bd9b73c-4472-c1c2-7aa4-9fb0919639a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74667338-66891380-51a3-11ea-94a3-bd0c826378e3.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74667338-66891380-51a3-11ea-94a3-bd0c826378e3.png)
https://user-images.githubusercontent.com/20930745/74667338-66891380-51a3-11ea-94a3-bd0c826378e3.png

Source:
https://user-images.githubusercontent.com/20930745/74667346-6a1c9a80-51a3-11ea-82d4-9a567795710d.png
