### ISSUE TITLE
Draw Climber

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10676]
**App Name:** Draw Climber
**Bundle ID:** com.appadvisory.drawclimber
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1495369374">1495369374</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/draw-climber/id1495369374?uo=4">https://apps.apple.com/us/app/draw-climber/id1495369374?uo=4</a>
**App Version:** 1.1.1
**Seller:** Voodoo
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/voodoo/id714804730?uo=4">© Voodoo</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/4e/49/57/4e4957e3-91ca-3151-cb50-36b43714ff0e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/76360496-7c49ae80-62f3-11ea-8b90-2bb192aeabba.png)

**Comment by XPEric** [comment]
?
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/76360496-7c49ae80-62f3-11ea-8b90-2bb192aeabba.png)
https://user-images.githubusercontent.com/2313873/76360496-7c49ae80-62f3-11ea-8b90-2bb192aeabba.png


___
Source:
https://user-images.githubusercontent.com/2313873/76360489-781d9100-62f3-11ea-81ad-b721372c9724.png

**Comment by Gwai** [comment]
👍
