### ISSUE TITLE
OLX: Buy & Sell near you

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10673]
**App Name:** OLX: Buy & Sell near you
**Bundle ID:** asia.olx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=913492792">913492792</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/in/app/olx-buy-sell-near-you/id913492792?uo=4">https://apps.apple.com/in/app/olx-buy-sell-near-you/id913492792?uo=4</a>
**App Version:** 11.31.0
**Seller:** OLX BV
**Developer:** <a target="_blank" href="https://apps.apple.com/in/developer/olx-bv/id913492795?uo=4">© OLX BV</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/79/15/ee/7915eea2-908a-66ab-3587-ecfe4c5db942/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74669480-7dca0000-51a7-11ea-83f9-dbf04321ca4f.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74669480-7dca0000-51a7-11ea-83f9-dbf04321ca4f.png)
https://user-images.githubusercontent.com/20930745/74669480-7dca0000-51a7-11ea-83f9-dbf04321ca4f.png

Source:
https://user-images.githubusercontent.com/20930745/74669488-7f93c380-51a7-11ea-8293-7549a978b37a.png
