### ISSUE TITLE
winSIM Servicewelt

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10679]
**App Name:** winSIM Servicewelt
**Bundle ID:** de.winsim.winSIM-Servicewelt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=852967037">852967037</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/winsim-servicewelt/id852967037?uo=4">https://apps.apple.com/us/app/winsim-servicewelt/id852967037?uo=4</a>
**App Version:** 1.5
**Seller:** Drillisch Aktiengesellschaft
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/drillisch-ag/id774775240?uo=4">© Drillisch AG</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/dd/94/e5/dd94e50c-3cad-fe60-b23b-36f09b5eff5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74670167-e796d980-51a8-11ea-99b5-a333a39e2d4e.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74670167-e796d980-51a8-11ea-99b5-a333a39e2d4e.png)
https://user-images.githubusercontent.com/20930745/74670167-e796d980-51a8-11ea-99b5-a333a39e2d4e.png

Source:
https://user-images.githubusercontent.com/20930745/74670174-e9609d00-51a8-11ea-87f4-3983c44d616e.png
