### ISSUE TITLE
Exif Metadata

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10671]
**App Name:** Exif Metadata
**Bundle ID:** com.newmarketinglab.ExifMetadata
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1455197364">1455197364</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/exif-metadata/id1455197364?uo=4">https://apps.apple.com/us/app/exif-metadata/id1455197364?uo=4</a>
**App Version:** 2.1
**Seller:** New Marketing Lab, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/new-marketing-lab-inc/id1080727702?uo=4">© New Marketing Lab, Inc</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/35/73/04/35730440-2d9d-f48c-73cc-bf279b0ca5ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74668680-05167400-51a6-11ea-8bcb-74435749b9e9.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74668680-05167400-51a6-11ea-8bcb-74435749b9e9.png)
https://user-images.githubusercontent.com/20930745/74668680-05167400-51a6-11ea-8bcb-74435749b9e9.png

Source:
https://user-images.githubusercontent.com/20930745/74668689-0b0c5500-51a6-11ea-939b-1133fa36cd14.png
