### ISSUE TITLE
Train Taxi

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10674]
**App Name:** Train Taxi
**Bundle ID:** com.train.taxi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1466292431">1466292431</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/train-taxi/id1466292431?uo=4">https://apps.apple.com/us/app/train-taxi/id1466292431?uo=4</a>
**App Version:** 1.4.2
**Seller:** SEIGEIMS, OOO
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/saygames-llc/id1405039362?uo=4">© SayGames LLC</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/f0/87/79/f08779c2-5c82-b390-a875-6c421110327e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/76689209-d61fe080-6633-11ea-8fdd-02745267be1d.png)

**Comment by XPEric** [comment]
?
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/76363764-157bc380-62fa-11ea-8b79-13b704f21a4f.png)
https://user-images.githubusercontent.com/2313873/76363764-157bc380-62fa-11ea-8b79-13b704f21a4f.png


___
Source:
https://user-images.githubusercontent.com/2313873/76363758-10b70f80-62fa-11ea-9cfa-d6aeb0ad4fa7.png

**Comment by dreamnet** [comment]
?
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/76689209-d61fe080-6633-11ea-8fdd-02745267be1d.png)
https://user-images.githubusercontent.com/2068130/76689209-d61fe080-6633-11ea-8fdd-02745267be1d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/76689217-ecc63780-6633-11ea-8d9d-237feaf349d7.png

**Comment by Gwai** [comment]
👍
