### ISSUE TITLE
DigiLocker

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10672]
**App Name:** DigiLocker
**Bundle ID:** com.negd.digilocker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1320618078">1320618078</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/in/app/digilocker/id1320618078?uo=4">https://apps.apple.com/in/app/digilocker/id1320618078?uo=4</a>
**App Version:** 2.0.1
**Seller:** National e-Governance Division
**Developer:** <a target="_blank" href="https://apps.apple.com/in/developer/national-e-governance-division/id1216162617?uo=4">© National e-Governance Division</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/a6/4c/39/a64c39e7-1413-5426-cb4a-133af4f6cefe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74669091-c2a16700-51a6-11ea-842d-4ef1edff74fd.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=(https://user-images.githubusercontent.com/20930745/74669091-c2a16700-51a6-11ea-842d-4ef1edff74fd.png)
https://user-images.githubusercontent.com/20930745/74669091-c2a16700-51a6-11ea-842d-4ef1edff74fd.png

Source:
https://user-images.githubusercontent.com/20930745/74669097-c59c5780-51a6-11ea-9b25-06a1f1588900.png
