### ISSUE TITLE
BHIM – Making India Cashless

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10670]
**App Name:** BHIM – Making India Cashless
**Bundle ID:** in.org.npci.ios.upiapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1200315258">1200315258</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bhim-making-india-cashless/id1200315258?uo=4">https://apps.apple.com/us/app/bhim-making-india-cashless/id1200315258?uo=4</a>
**App Version:** 2.0.1
**Seller:** National Payments Corporation of India
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/national-payments-corporation-of-india-npci/id1200315257?uo=4">© National Payments Corporation of India (NPCI)</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/48/8d/34/488d34c7-3f4f-02c2-8653-6d55eeb9fa3a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74668282-32aeed80-51a5-11ea-82a2-3d1470c0cafb.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74668282-32aeed80-51a5-11ea-82a2-3d1470c0cafb.png)
https://user-images.githubusercontent.com/20930745/74668282-32aeed80-51a5-11ea-82a2-3d1470c0cafb.png

Source:
https://user-images.githubusercontent.com/20930745/74668286-36db0b00-51a5-11ea-8970-e27a8b7c4daf.png
