### ISSUE TITLE
Color Fill 3D

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10678]
**App Name:** Color Fill 3D
**Bundle ID:** com.gjg.colorfill3d
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1473024868">1473024868</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/color-fill-3d/id1473024868?uo=4">https://apps.apple.com/us/app/color-fill-3d/id1473024868?uo=4</a>
**App Version:** 2.13
**Seller:** Good Job Games Bilisim Yazilim ve Pazarlama AS
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/good-job-games/id1191495496?uo=4">© Good Job Games</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/d4/20/d4/d420d4cc-1e21-2fbc-aaff-2493746ae292/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75553108-095d4f80-5a38-11ea-9877-ecbc2ac51408.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/74910128-69d8f680-537f-11ea-82bc-89b75ee8d6da.png)
https://user-images.githubusercontent.com/44279267/74910128-69d8f680-537f-11ea-82bc-89b75ee8d6da.png

Source:
https://user-images.githubusercontent.com/44279267/74910166-7f4e2080-537f-11ea-8587-6ae4eaf1722c.png

is my radius on box not correct size?

**Comment by 2Qt2beStr8** [comment]
@tlunmp the correct size from the radius is 180px - credits to @tlunmp 

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75553108-095d4f80-5a38-11ea-9877-ecbc2ac51408.png)
https://user-images.githubusercontent.com/20930745/75553108-095d4f80-5a38-11ea-9877-ecbc2ac51408.png

Source:
https://user-images.githubusercontent.com/20930745/75553112-0c584000-5a38-11ea-9cd4-26a694f3c2b5.png

**Comment by tlunmp** [comment]
on the corner of the icon that I made. sorry for the confusion.
