### ISSUE TITLE
Crash Landing 3D

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10675]
**App Name:** Crash Landing 3D
**Bundle ID:** com.fullfat.crashlanding
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1491883876">1491883876</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/crash-landing-3d/id1491883876?uo=4">https://apps.apple.com/us/app/crash-landing-3d/id1491883876?uo=4</a>
**App Version:** 0.8
**Seller:** Voodoo
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/voodoo/id714804730?uo=4">© Voodoo</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/1d/85/2a/1d852afc-0639-0ed1-1f61-ac1ced92bb13/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/76363934-786d5a80-62fa-11ea-8006-3f6e15642604.png)

**Comment by XPEric** [comment]
?
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/76346751-e35b6900-62db-11ea-9548-d7eba3735f65.png)
https://user-images.githubusercontent.com/2313873/76346751-e35b6900-62db-11ea-9548-d7eba3735f65.png


___
Source:
https://user-images.githubusercontent.com/2313873/76346747-e0607880-62db-11ea-98e2-121a235c80c1.png

**Comment by Gwai** [comment]
👍

**Comment by XPEric** [comment]
? (looks a bit better to me with more spacing)
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/76347825-9d070980-62dd-11ea-8d2c-ed34f8cf7252.png)
https://user-images.githubusercontent.com/2313873/76347825-9d070980-62dd-11ea-8d2c-ed34f8cf7252.png


___
Source:
https://user-images.githubusercontent.com/2313873/76347819-9aa4af80-62dd-11ea-9440-2058c5ef69a7.png
