### ISSUE TITLE
Shell US

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10683]
**App Name:** Shell US
**Bundle ID:** com.shell.sitibv.motorist.america
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1410234033">1410234033</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/shell-us/id1410234033?uo=4">https://apps.apple.com/us/app/shell-us/id1410234033?uo=4</a>
**App Version:** 3.0
**Seller:** Shell Information Technology International B.V.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shell-information-technology-international-b-v/id410842826?uo=4">© Shell Information Technology International B.V.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/69/f1/f4/69f1f434-0ec2-3949-388a-f112d81f1d61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75604447-05353e80-5ad9-11ea-81e2-799d562ce4ae.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/74906089-95ef7a00-5375-11ea-8c1b-d071353dd1c9.png)
https://user-images.githubusercontent.com/44279267/74906089-95ef7a00-5375-11ea-8c1b-d071353dd1c9.png

Source:
https://user-images.githubusercontent.com/44279267/74906105-a142a580-5375-11ea-899e-3ec839047c84.png

**Comment by 2Qt2beStr8** [comment]
@tlunmp some small corrections (a little bit to small) - but credits goes to you

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75604447-05353e80-5ad9-11ea-81e2-799d562ce4ae.png)
https://user-images.githubusercontent.com/20930745/75604447-05353e80-5ad9-11ea-81e2-799d562ce4ae.png

Source:
https://user-images.githubusercontent.com/20930745/75604449-06ff0200-5ad9-11ea-92c9-e09714df6a29.png
