### ISSUE TITLE
MyHyundai with Blue Link

### ISSUE THREAD

**Issue by jq1106** [glasklart/hd#10682]
**App Name:** MyHyundai with Blue Link
**Bundle ID:** com.hyundaiusa.bluelink2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=893514610">893514610</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myhyundai-with-blue-link/id893514610?uo=4">https://apps.apple.com/us/app/myhyundai-with-blue-link/id893514610?uo=4</a>
**App Version:** 4.2.11
**Seller:** Hyundai Motor America
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hyundai-motor-america/id396788762?uo=4">© Hyundai Motor America</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/e3/ab/cd/e3abcdbf-cd5f-8521-7f99-87b46141490d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74859325-0fbc3f00-5347-11ea-9624-8c7395b17a69.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74859325-0fbc3f00-5347-11ea-9624-8c7395b17a69.png)
https://user-images.githubusercontent.com/20930745/74859325-0fbc3f00-5347-11ea-9624-8c7395b17a69.png

Source:
https://user-images.githubusercontent.com/20930745/74859330-11860280-5347-11ea-8064-9d39992286aa.png
