### ISSUE TITLE
Mp3 Cutter - M4a, Music Cutter

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10680]
**App Name:** Mp3 Cutter - M4a, Music Cutter
**Bundle ID:** com.toh.app.music.cutter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1455601338">1455601338</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mp3-cutter-m4a-music-cutter/id1455601338?uo=4">https://apps.apple.com/us/app/mp3-cutter-m4a-music-cutter/id1455601338?uo=4</a>
**App Version:** 1.4
**Seller:** TOWER OF HANOI SOFTWARE COMPANY LIMITED
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/toh-co-ltd/id1125320041?uo=4">© TOH CO.,LTD</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/57/0e/71/570e7197-848b-31f4-0d2a-09b4238d0d41/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74670512-a0f5af00-51a9-11ea-97ed-1a3bc9accdf3.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74670512-a0f5af00-51a9-11ea-97ed-1a3bc9accdf3.png)
https://user-images.githubusercontent.com/20930745/74670512-a0f5af00-51a9-11ea-97ed-1a3bc9accdf3.png

Source:
https://user-images.githubusercontent.com/20930745/74670519-a3580900-51a9-11ea-84cb-c73b8ccd5456.png
