### ISSUE TITLE
XMEye

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10689]
**App Name:** XMEye
**Bundle ID:** com.xiongmai.XMeye
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=884006786">884006786</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/xmeye/id884006786?uo=4">https://apps.apple.com/us/app/xmeye/id884006786?uo=4</a>
**App Version:** 3.0.1
**Seller:** HangZhou XiongMai Technology CO.LTD.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hangzhou-xiongmai-technology/id1232128802?uo=4">© HangZhou XiongMai Technology</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/10/16/c3/1016c36b-cb40-25a7-9a63-3fba19ca99f8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75602582-05c4d980-5ac7-11ea-9eb8-e448b2d75ac7.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/75102452-de977500-55b9-11ea-9cfd-2e9b50e3c239.png)
https://user-images.githubusercontent.com/2313873/75102452-de977500-55b9-11ea-9cfd-2e9b50e3c239.png


___
Source:
https://user-images.githubusercontent.com/2313873/75102451-db9c8480-55b9-11ea-9736-8822bb581fbf.png

**Comment by 2Qt2beStr8** [comment]
some smallcorrections, bur credits goes to @XPEric 

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75602582-05c4d980-5ac7-11ea-9eb8-e448b2d75ac7.png)
https://user-images.githubusercontent.com/20930745/75602582-05c4d980-5ac7-11ea-9eb8-e448b2d75ac7.png

Source:
https://user-images.githubusercontent.com/20930745/75602584-06f60680-5ac7-11ea-9629-4ced28f62496.png
