### ISSUE TITLE
KATWARN

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10681]
**App Name:** KATWARN
**Bundle ID:** de.combirisk.KATWARN
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=566560753">566560753</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/katwarn/id566560753?uo=4">https://apps.apple.com/us/app/katwarn/id566560753?uo=4</a>
**App Version:** 2.3.4
**Seller:** CombiRisk - Riskmanagement GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/combirisk-gmbh/id566560756?uo=4">© CombiRisk GmbH</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/db/73/37/db7337ec-da8a-0bfd-ce52-a62bf4ef9f5f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74670922-68a2a080-51aa-11ea-83f9-bdd818bea037.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74670922-68a2a080-51aa-11ea-83f9-bdd818bea037.png)
https://user-images.githubusercontent.com/20930745/74670922-68a2a080-51aa-11ea-83f9-bdd818bea037.png

Source:
https://user-images.githubusercontent.com/20930745/74670926-6a6c6400-51aa-11ea-8a21-aaf30e66a921.png
