### ISSUE TITLE
ShopRite

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10686]
**App Name:** ShopRite
**Bundle ID:** com.wakefern.shoprite.shopriteapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1170573424">1170573424</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/shoprite/id1170573424?uo=4">https://apps.apple.com/us/app/shoprite/id1170573424?uo=4</a>
**App Version:** 4.1.0
**Seller:** Wakefern Food Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wakefern-food-corp/id592484336?uo=4">© Wakefern Food Corp</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/a8/1c/b8/a81cb830-5574-4e07-d570-af83f71f4e5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75604983-99ee6b00-5ade-11ea-9162-4a0c249705e8.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/75102356-1ac9d600-55b8-11ea-8f02-422c5003df54.png)
https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/75102356-1ac9d600-55b8-11ea-8f02-422c5003df54.png


___
Source:
https://user-images.githubusercontent.com/2313873/75102355-130a3180-55b8-11ea-840a-653e927fcd4a.png

**Comment by XPEric** [comment]
?
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/75110121-f261cc00-55f7-11ea-900c-f771ce416728.png)
https://user-images.githubusercontent.com/2313873/75110121-f261cc00-55f7-11ea-900c-f771ce416728.png


___
Source:
https://user-images.githubusercontent.com/2313873/75110120-ee35ae80-55f7-11ea-81bb-f50e4110f0de.png

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75604983-99ee6b00-5ade-11ea-9162-4a0c249705e8.png)
https://user-images.githubusercontent.com/20930745/75604983-99ee6b00-5ade-11ea-9162-4a0c249705e8.png

Source:
https://user-images.githubusercontent.com/20930745/75604984-9bb82e80-5ade-11ea-9ac6-2e471556a5b7.png
