### ISSUE TITLE
Cruise Norwegian - Plan & Chat

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10687]
**App Name:** Cruise Norwegian - Plan & Chat
**Bundle ID:** com.ncl.BGEApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1126094257">1126094257</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cruise-norwegian-plan-chat/id1126094257?uo=4">https://apps.apple.com/us/app/cruise-norwegian-plan-chat/id1126094257?uo=4</a>
**App Version:** 1.7.5
**Seller:** Norwegian Cruise Line Holdings LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/norwegian-cruise-line/id491935049?uo=4">© Norwegian Cruise Line®</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/49/da/29/49da29f4-0909-bd42-cd66-ee67a74f6bea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75109828-872fee00-5627-11ea-83db-87f6364351e5.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/75102407-f4f10100-55b8-11ea-8d20-4db95b943110.png)
https://user-images.githubusercontent.com/2313873/75102406-f02c4d00-55b8-11ea-8726-41de291ad48a.png


___
Source:
https://user-images.githubusercontent.com/2313873/75102405-eb679900-55b8-11ea-9c67-8aebee696dcb.png

**Comment by 2Qt2beStr8** [comment]
@XPEric nice, but to small

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75109828-872fee00-5627-11ea-83db-87f6364351e5.png)
https://user-images.githubusercontent.com/20930745/75109828-872fee00-5627-11ea-83db-87f6364351e5.png

Source:
https://user-images.githubusercontent.com/20930745/75109829-88f9b180-5627-11ea-86bb-fa9b8a01eb1f.png
