### ISSUE TITLE
UnitedHealthcare

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10684]
**App Name:** UnitedHealthcare
**Bundle ID:** com.uhg.mobile.uhc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1348316600">1348316600</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/unitedhealthcare/id1348316600?uo=4">https://apps.apple.com/us/app/unitedhealthcare/id1348316600?uo=4</a>
**App Version:** 1.6.11
**Seller:** UNITED HEALTHCARE SERVICES, INC.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/united-healthcare-services-inc/id1134060798?uo=4">© United HealthCare Services, Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/0b/69/ca/0b69ca4c-8385-e6ac-d0bc-b5550d78e9b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75552320-55a79000-5a36-11ea-8736-c25e228480d8.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/74902359-6fc4dc80-536b-11ea-9ca2-c6d671027fa2.png)

Source:
https://user-images.githubusercontent.com/44279267/74902393-94b94f80-536b-11ea-8cd5-84c2e2fc6530.png

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/74902567-0beee380-536c-11ea-8ecd-d7d0131925d3.png)

Source:
https://user-images.githubusercontent.com/44279267/74902578-14471e80-536c-11ea-8b42-338c1e29fe10.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75552320-55a79000-5a36-11ea-8736-c25e228480d8.png)
https://user-images.githubusercontent.com/20930745/75552320-55a79000-5a36-11ea-8736-c25e228480d8.png

Source:
https://user-images.githubusercontent.com/20930745/75552327-593b1700-5a36-11ea-936d-747cb52fb008.png
