### ISSUE TITLE
Floatplane

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10688]
**App Name:** Floatplane
**Bundle ID:** com.floatplane.floatplane
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1472071280">1472071280</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/floatplane/id1472071280?uo=4">https://apps.apple.com/us/app/floatplane/id1472071280?uo=4</a>
**App Version:** 0.1.27
**Seller:** Floatplane Media Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/floatplane-media-inc/id1472071279?uo=4">© Floatplane Media Inc</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/91/34/35/913435c5-f913-4cb7-fa95-e0caadc8e742/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75553919-a1a80400-5a39-11ea-9895-3cc8af2eaaf2.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/75102435-54e7a780-55b9-11ea-855d-97ad848fcec4.png)
https://user-images.githubusercontent.com/2313873/75102435-54e7a780-55b9-11ea-855d-97ad848fcec4.png


___
Source:
https://user-images.githubusercontent.com/2313873/75102433-51542080-55b9-11ea-886b-f5f1fad8c566.png

**Comment by 2Qt2beStr8** [comment]
some small corrections, but credits goes to @XPEric 

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75553919-a1a80400-5a39-11ea-9895-3cc8af2eaaf2.png)
https://user-images.githubusercontent.com/20930745/75553919-a1a80400-5a39-11ea-9895-3cc8af2eaaf2.png

Source:
https://user-images.githubusercontent.com/20930745/75553921-a371c780-5a39-11ea-89eb-d97ab856c400.png
