### ISSUE TITLE
Morse Code Keys

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10696]
**App Name:** Morse Code Keys
**Bundle ID:** com.zerosgamedesign.morsecode
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1098434617">1098434617</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/morse-code-keys/id1098434617?uo=4">https://apps.apple.com/us/app/morse-code-keys/id1098434617?uo=4</a>
**App Version:** 1.7
**Seller:** Caesar Salad Software LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/caesar-salad-software-llc/id1249587406?uo=4">© Caesar Salad Software LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/dd/85/d9/dd85d978-8719-e624-e6dc-2b26d7a203ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75602316-4707ba00-5ac4-11ea-9e3b-fcc5f771fce6.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/75126778-1b7a6f00-5681-11ea-8589-de6e9bd5341c.png)
https://user-images.githubusercontent.com/44279267/75126778-1b7a6f00-5681-11ea-8589-de6e9bd5341c.png

Source:
https://user-images.githubusercontent.com/44279267/75126787-259c6d80-5681-11ea-87d3-372269cb2a78.png

**Comment by 2Qt2beStr8** [comment]
some small corrections, but credits goes to @tlunmp 

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75602316-4707ba00-5ac4-11ea-9e3b-fcc5f771fce6.png)
https://user-images.githubusercontent.com/20930745/75602316-4707ba00-5ac4-11ea-9e3b-fcc5f771fce6.png

Source:
https://user-images.githubusercontent.com/20930745/75602338-7ae2df80-5ac4-11ea-8d15-d2cde5a79fe2.png
