### ISSUE TITLE
HPE iLO Mobile

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#10691]
**App Name:** HPE iLO Mobile
**Bundle ID:** com.hp.ilo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=497560256">497560256</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hpe-ilo-mobile/id497560256?uo=4">https://apps.apple.com/us/app/hpe-ilo-mobile/id497560256?uo=4</a>
**App Version:** 1.11
**Seller:** Hewlett Packard Enterprise Company
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hewlett-packard-enterprise-company/id1039583030?uo=4">© Hewlett Packard Enterprise Company</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/6e/65/0a/6e650a61-d395-4d66-5e3b-9281bcc073c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75604671-8ee60b80-5adb-11ea-84dc-fa6c61d5ebb6.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/75102607-4a7add00-55bc-11ea-9a15-eb9ab8011752.png)
https://user-images.githubusercontent.com/2313873/75102607-4a7add00-55bc-11ea-9a15-eb9ab8011752.png


___
Source:
https://user-images.githubusercontent.com/2313873/75102606-464ebf80-55bc-11ea-8837-6a967fd57cfa.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75604671-8ee60b80-5adb-11ea-84dc-fa6c61d5ebb6.png)
https://user-images.githubusercontent.com/20930745/75604671-8ee60b80-5adb-11ea-84dc-fa6c61d5ebb6.png

Source:
https://user-images.githubusercontent.com/20930745/75604682-a2917200-5adb-11ea-81f6-6ed68826acab.png
