### ISSUE TITLE
Drive Safe & Save™

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10695]
**App Name:** Drive Safe & Save™
**Bundle ID:** com.statefarm.DriveSafeAndSave
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1043246998">1043246998</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/drive-safe-save/id1043246998?uo=4">https://apps.apple.com/us/app/drive-safe-save/id1043246998?uo=4</a>
**App Version:** 3.3.1
**Seller:** State Farm Mutual Automobile Insurance Company
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/state-farm-mutual-automobile-insurance-company/id318142140?uo=4">© State Farm Mutual Automobile Insurance Company</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/d9/40/f8/d940f83b-a6fc-71d6-050b-a80a083e1223/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75279667-3cbb9680-580c-11ea-894d-1370b4c00b9e.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75279667-3cbb9680-580c-11ea-894d-1370b4c00b9e.png)
https://user-images.githubusercontent.com/20930745/75279667-3cbb9680-580c-11ea-894d-1370b4c00b9e.png

Source:
https://user-images.githubusercontent.com/20930745/75279670-3e855a00-580c-11ea-9b4a-3d45c39cf819.png
