### ISSUE TITLE
GitTouch

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10698]
**App Name:** GitTouch
**Bundle ID:** io.github.pd4d10.gitTouch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1452042346">1452042346</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gittouch/id1452042346?uo=4">https://apps.apple.com/us/app/gittouch/id1452042346?uo=4</a>
**App Version:** 1.4.0
**Seller:** Rongjian Zhang
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/rongjian-zhang/id1434285149?uo=4">© Rongjian Zhang</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/1d/4b/3b/1d4b3b8e-33a3-dbaf-e727-677f5fde0780/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75274255-d2522880-5802-11ea-80e5-c0bc613930fb.png)

**Comment by 2Qt2beStr8** [comment]
Upload currently not possible. I added the files directly to the database
