### ISSUE TITLE
Climacell: Weather Assistant

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10697]
**App Name:** Climacell: Weather Assistant
**Bundle ID:** co.climacell.climacell
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1443325509">1443325509</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/climacell-weather-assistant/id1443325509?uo=4">https://apps.apple.com/us/app/climacell-weather-assistant/id1443325509?uo=4</a>
**App Version:** 1.11.1
**Seller:** Climacell, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/climacell-inc/id1441447602?uo=4">© Climacell, Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/4a/53/e9/4a53e9d6-5ffc-80d2-46a3-5a7e2784f690/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75274083-78e9f980-5802-11ea-8055-965295006c68.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75274083-78e9f980-5802-11ea-8055-965295006c68.png)
https://user-images.githubusercontent.com/20930745/75274083-78e9f980-5802-11ea-8055-965295006c68.png

Source:
https://user-images.githubusercontent.com/20930745/75274089-7c7d8080-5802-11ea-929b-5cb274058c49.png
