### ISSUE TITLE
DISH Anywhere

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10705]
**App Name:** DISH Anywhere
**Bundle ID:** com.yourcompany.DISH
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327125649">327125649</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dish-anywhere/id327125649?uo=4">https://apps.apple.com/us/app/dish-anywhere/id327125649?uo=4</a>
**App Version:** 7.31.0
**Seller:** DISH Network LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dish-network-llc/id327125652?uo=4">© DISH Network LLC</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/42/51/8b/42518b3c-8232-5aec-7650-b303179acfad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75275825-602f1300-5805-11ea-9436-abb7011f3387.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75275825-602f1300-5805-11ea-9436-abb7011f3387.png)
https://user-images.githubusercontent.com/20930745/75275825-602f1300-5805-11ea-9436-abb7011f3387.png

Source:
https://user-images.githubusercontent.com/20930745/75275832-62916d00-5805-11ea-8a2a-ac05520e3273.png)
