### ISSUE TITLE
Private Photo Vault Pro

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10702]
**App Name:** Private Photo Vault Pro
**Bundle ID:** com.enchantedcloud.photovaultpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427701370">427701370</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/private-photo-vault-pro/id427701370?uo=4">https://apps.apple.com/us/app/private-photo-vault-pro/id427701370?uo=4</a>
**App Version:** 10.5
**Seller:** Legendary Software Labs LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/legendary-software-labs-llc/id456797862?uo=4">© Legendary Software Labs LLC</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/bb/9a/6d/bb9a6dcd-0800-ae5f-ffdc-9edc51b16635/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/75320514-786a5680-5834-11ea-9dac-a740a67a758a.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/75320514-786a5680-5834-11ea-9dac-a740a67a758a.png)
https://user-images.githubusercontent.com/44279267/75320514-786a5680-5834-11ea-9dac-a740a67a758a.png

Source:
https://user-images.githubusercontent.com/44279267/75320547-91730780-5834-11ea-9281-2ae47aec24dc.png

**Comment by PadrinoSant** [comment]
Beautiful icons. Thank you so much

**Comment by tlunmp** [comment]
@PadrinoSant thanks
