### ISSUE TITLE
Bose Music

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10708]
**App Name:** Bose Music
**Bundle ID:** com.bose.bosemusic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1364986984">1364986984</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bose-music/id1364986984?uo=4">https://apps.apple.com/us/app/bose-music/id1364986984?uo=4</a>
**App Version:** 3.1.6
**Seller:** Bose Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bose-corporation/id425230041?uo=4">© Bose Corporation</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/fe/21/3c/fe213c76-add0-fb7f-b481-9d03b893f5ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75468270-3e609800-598d-11ea-8073-d1a15db2f896.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75468270-3e609800-598d-11ea-8073-d1a15db2f896.png)
https://user-images.githubusercontent.com/20930745/75468270-3e609800-598d-11ea-8073-d1a15db2f896.png

Source:
https://user-images.githubusercontent.com/20930745/75468276-3f91c500-598d-11ea-9c3a-020f457bde7a.png
