### ISSUE TITLE
Theragun

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10707]
**App Name:** Theragun
**Bundle ID:** com.theragun.consumer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1445611295">1445611295</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/theragun/id1445611295?uo=4">https://apps.apple.com/us/app/theragun/id1445611295?uo=4</a>
**App Version:** 0.5.7
**Seller:** Theragun, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/theragun-llc/id1437768506?uo=4">© Theragun, LLC</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/71/9f/e7/719fe7e6-a9d5-e34d-6c48-b2d03d6c93e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75557280-0bc3a780-5a40-11ea-9d00-e63b4fd8e187.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75466051-d9f00980-5989-11ea-921f-310c72693b86.png)
https://user-images.githubusercontent.com/20930745/75466051-d9f00980-5989-11ea-921f-310c72693b86.png

Source:
https://user-images.githubusercontent.com/20930745/75466056-dbb9cd00-5989-11ea-8589-4add1735da0a.png
