### ISSUE TITLE
Sony | Music Center (SongPal)

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10706]
**App Name:** Sony | Music Center (SongPal)
**Bundle ID:** jp.co.sony.audio.companion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=724406878">724406878</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sony-music-center-songpal/id724406878?uo=4">https://apps.apple.com/us/app/sony-music-center-songpal/id724406878?uo=4</a>
**App Version:** 5.14.0
**Seller:** Sony Home Entertainment & Sound Products Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sony-home-entertainment-sound-products-inc/id1315534741?uo=4">© Sony Home Entertainment & Sound Products Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/e8/77/1b/e8771b42-f56e-c360-c796-f04494cef610/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75278414-1c8ad800-580a-11ea-93c6-08b479a985d5.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75276945-6920e400-5807-11ea-85a7-4a154740f034.png)
https://user-images.githubusercontent.com/20930745/75276945-6920e400-5807-11ea-85a7-4a154740f034.png

Source:
https://user-images.githubusercontent.com/20930745/75276954-6b833e00-5807-11ea-95df-ba25748678f4.png

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75278414-1c8ad800-580a-11ea-93c6-08b479a985d5.png)
https://user-images.githubusercontent.com/20930745/75278414-1c8ad800-580a-11ea-93c6-08b479a985d5.png

Source:
https://user-images.githubusercontent.com/20930745/75278418-1eed3200-580a-11ea-8fd5-846a7f8e876e.png
