### ISSUE TITLE
Remitly: Transfer Money Abroad

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10701]
**App Name:** Remitly: Transfer Money Abroad
**Bundle ID:** com.remitly.remitly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=674258465">674258465</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/remitly-transfer-money-abroad/id674258465?uo=4">https://apps.apple.com/us/app/remitly-transfer-money-abroad/id674258465?uo=4</a>
**App Version:** 5.6
**Seller:** Remitly Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/remitly-inc/id674258468?uo=4">© Remitly Inc</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/af/9a/e6/af9ae6de-8855-889c-112b-a67d6b528fd7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75274813-cd41a900-5803-11ea-8ee8-6d6200b27eec.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75274813-cd41a900-5803-11ea-8ee8-6d6200b27eec.png)
https://user-images.githubusercontent.com/20930745/75274813-cd41a900-5803-11ea-8ee8-6d6200b27eec.png

Source:
https://user-images.githubusercontent.com/20930745/75274818-cf0b6c80-5803-11ea-8902-e4194c92238c.png
