### ISSUE TITLE
OneFootball - Soccer News

### ISSUE THREAD

**Issue by bepebe** [glasklart/hd#1070]
**App Name:** OneFootball - Soccer News
**Bundle ID:** de.motain.iliga
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382002079">382002079</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/onefootball-soccer-news/id382002079?uo=4">https://apps.apple.com/us/app/onefootball-soccer-news/id382002079?uo=4</a>
**App Version:** 14.0.1
**Seller:** Onefootball GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/onefootball-gmbh/id331166454?uo=4">© Onefootball GmbH</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/36/9c/e0/369ce028-a7da-d72b-9bb8-e1e4027884c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86527651-77f86100-bea1-11ea-8175-9c44c1be4794.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8524532/23436334-23fc-11e5-8e82-440b51e99ae8.png)
https://cloud.githubusercontent.com/assets/10730122/8524532/23436334-23fc-11e5-8e82-440b51e99ae8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8524530/1efdb676-23fc-11e5-946f-8a5dde1a5c5e.png

**Comment by ivanov007** [comment]
icon changed

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86527651-77f86100-bea1-11ea-8175-9c44c1be4794.png)
https://user-images.githubusercontent.com/2068130/86527651-77f86100-bea1-11ea-8175-9c44c1be4794.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86527662-8a729a80-bea1-11ea-8984-02f4a79cded5.png
