### ISSUE TITLE
MyDISH Account

### ISSUE THREAD

**Issue by PadrinoSant** [glasklart/hd#10700]
**App Name:** MyDISH Account
**Bundle ID:** com.dish.mda
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1123102087">1123102087</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mydish-account/id1123102087?uo=4">https://apps.apple.com/us/app/mydish-account/id1123102087?uo=4</a>
**App Version:** 3.28
**Seller:** DISH Network LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dish-network-llc/id327125652?uo=4">© DISH Network LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/de/6f/ac/de6fac3e-1c9b-d378-5079-076187882b05/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75274559-54dae800-5803-11ea-9f36-c202f85edf9d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75274559-54dae800-5803-11ea-9f36-c202f85edf9d.png)
https://user-images.githubusercontent.com/20930745/75274559-54dae800-5803-11ea-9f36-c202f85edf9d.png

Source:
https://user-images.githubusercontent.com/20930745/75274565-573d4200-5803-11ea-88d4-c45a07019877.png
