### ISSUE TITLE
HonkMobile

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10709]
**App Name:** HonkMobile
**Bundle ID:** com.honkmobile.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=816255029">816255029</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/honkmobile/id816255029?uo=4">https://apps.apple.com/us/app/honkmobile/id816255029?uo=4</a>
**App Version:** 2.11.0
**Seller:** Honk Mobile Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/honk-mobile-inc/id816255032?uo=4">© Honk Mobile Inc.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/b3/49/ed/b349ed4f-0acf-3869-ff95-6811671988fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75469564-854f8d00-598f-11ea-81de-89d90ac345ea.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75469564-854f8d00-598f-11ea-81de-89d90ac345ea.png)
https://user-images.githubusercontent.com/20930745/75469564-854f8d00-598f-11ea-81de-89d90ac345ea.png

Source:
https://user-images.githubusercontent.com/20930745/75469567-87195080-598f-11ea-8263-838f203679a8.png

**Comment by 2Qt2beStr8** [comment]
or:
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75558428-1b43f000-5a42-11ea-89ef-52052d3259de.png)
https://user-images.githubusercontent.com/20930745/75558428-1b43f000-5a42-11ea-89ef-52052d3259de.png

Source:
https://user-images.githubusercontent.com/20930745/75558434-1c751d00-5a42-11ea-9187-36e1ef4200eb.png

**Comment by 2Qt2beStr8** [comment]
@StevenZwicker which one should we take? i like the first more :-)

**Comment by StevenZwicker** [comment]
I implemented the first one - but good work on both of them!
