### ISSUE TITLE
MR PORTER | Luxury Fashion

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10719]
**App Name:** MR PORTER | Luxury Fashion
**Bundle ID:** com.netaporter.mobile-mrp-style-guide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=481673241">481673241</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mr-porter-luxury-fashion/id481673241?uo=4">https://apps.apple.com/us/app/mr-porter-luxury-fashion/id481673241?uo=4</a>
**App Version:** 8.2.9
**Seller:** THE NET-A-PORTER GROUP LIMITED
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-net-a-porter-group-limited/id318597942?uo=4">© THE NET-A-PORTER GROUP LIMITED</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/55/62/71/556271a0-b777-6ea0-15f4-10b2781207a3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75574070-58b67680-5a5e-11ea-9266-a6bc6019170b.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75574070-58b67680-5a5e-11ea-9266-a6bc6019170b.png)
https://user-images.githubusercontent.com/20930745/75574070-58b67680-5a5e-11ea-9266-a6bc6019170b.png

Source:
https://user-images.githubusercontent.com/20930745/75574089-5a803a00-5a5e-11ea-89e2-36e87eae7dd7.png

**Comment by jochulo** [comment]
Lookd good!
