### ISSUE TITLE
Picolo drinking game

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10710]
**App Name:** Picolo drinking game
**Bundle ID:** com.picolo.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1001473964">1001473964</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/picolo-drinking-game/id1001473964?uo=4">https://apps.apple.com/us/app/picolo-drinking-game/id1001473964?uo=4</a>
**App Version:** 2.1.2
**Seller:** Marmelapp
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/marmelapp/id1001473963?uo=4">© Marmelapp</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/51/c5/1d/51c51d0a-9be1-cae4-4648-0467e022d2c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/76345411-b6a65200-62d9-11ea-98eb-0a7eab83c325.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/76345207-4b5c8000-62d9-11ea-9b7a-a420f396851b.png)
https://user-images.githubusercontent.com/2313873/76345207-4b5c8000-62d9-11ea-9b7a-a420f396851b.png


___
Source:
https://user-images.githubusercontent.com/2313873/76345215-4f889d80-62d9-11ea-879b-c73b965bad16.png
