### ISSUE TITLE
VIMpay - so wird bezahlt

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10715]
**App Name:** VIMpay – so wird bezahlt
**Bundle ID:** net.petafuel.mobile.bankingvimpay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049311425">1049311425</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/vimpay-so-wird-bezahlt/id1049311425?uo=4">https://apps.apple.com/de/app/vimpay-so-wird-bezahlt/id1049311425?uo=4</a>
**App Version:** 3.2.0
**Seller:** petaFuel GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/petafuel/id386788928?uo=4">© petaFuel</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/70/94/95/709495d7-5ec3-79de-be9a-cebf9644f411/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75571760-1be88080-5a5a-11ea-90de-ca153f5a4043.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75571760-1be88080-5a5a-11ea-90de-ca153f5a4043.png)
https://user-images.githubusercontent.com/20930745/75571760-1be88080-5a5a-11ea-90de-ca153f5a4043.png

Source:
https://user-images.githubusercontent.com/20930745/75571762-1db24400-5a5a-11ea-809b-1fac4b4484a7.png
