### ISSUE TITLE
ASOS

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10718]
**App Name:** ASOS
**Bundle ID:** com.asos.asos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=457876088">457876088</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/asos/id457876088?uo=4">https://apps.apple.com/us/app/asos/id457876088?uo=4</a>
**App Version:** 4.25.0
**Seller:** Asos.Com Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/asos/id448997824?uo=4">© ASOS</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/86/ff/75/86ff75c1-e775-52dd-7be0-687908c1d130/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75572916-01170b80-5a5c-11ea-8727-ad79357f0aa4.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75572916-01170b80-5a5c-11ea-8727-ad79357f0aa4.png)
https://user-images.githubusercontent.com/20930745/75572916-01170b80-5a5c-11ea-8727-ad79357f0aa4.png

Source:
https://user-images.githubusercontent.com/20930745/75572924-03796580-5a5c-11ea-8093-c7cc593ba2f4.png
