### ISSUE TITLE
Cengage Mobile

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10712]
**App Name:** Cengage Mobile
**Bundle ID:** com.cengage.mindtap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1008352704">1008352704</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cengage-mobile/id1008352704?uo=4">https://apps.apple.com/us/app/cengage-mobile/id1008352704?uo=4</a>
**App Version:** 4.0.139
**Seller:** Cengage Learning, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cengage-learning/id371168145?uo=4">© Cengage Learning</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/00/d5/9c/00d59c2e-579c-8098-1922-c766d34a2c8d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75471155-19225880-5992-11ea-89cb-ad091066bef6.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75471155-19225880-5992-11ea-89cb-ad091066bef6.png)
https://user-images.githubusercontent.com/20930745/75471155-19225880-5992-11ea-89cb-ad091066bef6.png

Source:
https://user-images.githubusercontent.com/20930745/75471162-1aec1c00-5992-11ea-9196-02b11f8baa05.png
