### ISSUE TITLE
my giffgaff

### ISSUE THREAD

**Issue by bepebe** [glasklart/hd#1071]
**App Name:** my giffgaff
**Bundle ID:** com.giffgaff.mygiffgaff
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571246020">571246020</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-giffgaff/id571246020?mt=8&uo=4">https://itunes.apple.com/us/app/my-giffgaff/id571246020?mt=8&uo=4</a>
**App Version:** 4.4.1
**Seller:** giffgaff ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/giffgaff/id571246023?uo=4>© giffgaff</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/09/30/e8/0930e8f7-bbc5-2332-69d9-bdf83816347e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617858/eb711ea0-983b-11e6-9979-0e44325222fb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617858/eb711ea0-983b-11e6-9979-0e44325222fb.png)
https://cloud.githubusercontent.com/assets/20930745/19617858/eb711ea0-983b-11e6-9979-0e44325222fb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617861/0bd5e25c-983c-11e6-83d4-d117bd88bc63.png
