### ISSUE TITLE
Philips Sonicare

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10711]
**App Name:** Philips Sonicare
**Bundle ID:** com.philips.ph.hw.ohc.sonicare
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1047099766">1047099766</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/philips-sonicare/id1047099766?uo=4">https://apps.apple.com/us/app/philips-sonicare/id1047099766?uo=4</a>
**App Version:** 7.4.0
**Seller:** Philips Consumer Lifestyle, B.V.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/philips/id355645429?uo=4">© Philips</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/70/39/73/7039738e-3527-31cf-4b0e-e23fd6fc7997/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75470279-b7adba00-5990-11ea-9f4f-5ce086fe825f.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75470077-63a2d580-5990-11ea-9e88-31aef2d63b79.png)
https://user-images.githubusercontent.com/20930745/75470077-63a2d580-5990-11ea-9e88-31aef2d63b79.png

Source:
https://user-images.githubusercontent.com/20930745/75470085-656c9900-5990-11ea-87a5-11f39b5f5278.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75470279-b7adba00-5990-11ea-9f4f-5ce086fe825f.png)
https://user-images.githubusercontent.com/20930745/75470279-b7adba00-5990-11ea-9f4f-5ce086fe825f.png

Source:
https://user-images.githubusercontent.com/20930745/75470289-b9777d80-5990-11ea-88ed-e340c4e57862.png

**Comment by 2Qt2beStr8** [comment]
or:
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75470586-2ee34e00-5991-11ea-96b6-177ad1607331.png)
https://user-images.githubusercontent.com/20930745/75470586-2ee34e00-5991-11ea-96b6-177ad1607331.png

Source:
https://user-images.githubusercontent.com/20930745/75470588-30ad1180-5991-11ea-9449-028db22d7bd7.png
