### ISSUE TITLE
Amex Deutschland

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10714]
**App Name:** Amex Deutschland
**Bundle ID:** de.co.americanexpress.amexservice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=560172227">560172227</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/amex-deutschland/id560172227?uo=4">https://apps.apple.com/de/app/amex-deutschland/id560172227?uo=4</a>
**App Version:** 6.28.0
**Seller:** American Express
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/american-express/id362348519?uo=4">© American Express</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/48/2c/65/482c65f5-665d-c590-640e-48c56ebbfb4d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75571435-7fbe7980-5a59-11ea-9bea-ab75d24b101c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75571190-fc048d00-5a58-11ea-8d50-af9b5f304516.png)
https://user-images.githubusercontent.com/20930745/75571190-fc048d00-5a58-11ea-8d50-af9b5f304516.png

Source:
https://user-images.githubusercontent.com/20930745/75571195-fdce5080-5a58-11ea-83d2-e04cc7eb7f66.png

**Comment by jochulo** [comment]
Thank you, will this be available in the next glasklart update?

**Comment by 2Qt2beStr8** [comment]
you are welcome. yes, all new icons will be available in the next update

**Comment by 2Qt2beStr8** [comment]
@jochulo  zur Info :-)
![info](https://user-images.githubusercontent.com/20930745/75576722-c2d01b00-5a60-11ea-83b9-43373d17e56b.png)
ich lass es diesmal aber ausnahmsweise mal durchgehen :)

**Comment by jochulo** [comment]
Ohje, entschuldige bitte! Vielen Dank für deine Arbeit 🙏🏼 Grüße

**Comment by dreamnet** [comment]
Same as #30.
