### ISSUE TITLE
Breuninger

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10717]
**App Name:** Breuninger
**Bundle ID:** de.breuninger.card
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=859122055">859122055</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/breuninger/id859122055?uo=4">https://apps.apple.com/de/app/breuninger/id859122055?uo=4</a>
**App Version:** 4.8.1
**Seller:** E. Breuninger GmbH & Co.
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/e-breuninger-gmbh-co/id859122058?uo=4">© E. Breuninger GmbH & Co.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/a0/14/62/a01462fc-7fcd-d8ba-23ff-a87009b3ca48/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75572584-5bfc3300-5a5b-11ea-9d75-253185007424.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75572584-5bfc3300-5a5b-11ea-9d75-253185007424.png)
https://user-images.githubusercontent.com/20930745/75572584-5bfc3300-5a5b-11ea-9d75-253185007424.png

Source:
(https://user-images.githubusercontent.com/20930745/75572587-5e5e8d00-5a5b-11ea-93a4-6ced87df8be9.png
