### ISSUE TITLE
Farfetch - Designer Fashion

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10716]
**App Name:** Farfetch - Designer Fashion
**Bundle ID:** com.farfetch.discover
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=906698760">906698760</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/farfetch-designer-fashion/id906698760?uo=4">https://apps.apple.com/us/app/farfetch-designer-fashion/id906698760?uo=4</a>
**App Version:** 2.51.0
**Seller:** FARFETCH.COM LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/farfetch/id906698763?uo=4">© Farfetch</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/28/fd/e5/28fde53e-c185-84b4-b6b4-be94335aa83e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75572064-b5179700-5a5a-11ea-8a89-8f98b8ada85c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75572064-b5179700-5a5a-11ea-8a89-8f98b8ada85c.png)
https://user-images.githubusercontent.com/20930745/75572064-b5179700-5a5a-11ea-8a89-8f98b8ada85c.png

Source:
https://user-images.githubusercontent.com/20930745/75572070-b6e15a80-5a5a-11ea-9f85-07a0dce41c5d.png
