### ISSUE TITLE
Dash Radio

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10713]
**App Name:** Dash Radio
**Bundle ID:** com.dashradio.dash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=907383542">907383542</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dash-radio/id907383542?uo=4">https://apps.apple.com/us/app/dash-radio/id907383542?uo=4</a>
**App Version:** 5.6
**Seller:** Dash Radio, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dash-radio-inc/id912267777?uo=4">© Dash Radio, Inc.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/e9/8e/19/e98e19c6-52a6-1e98-8bed-fea2e8013459/source/512x512bb.jpg" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75551377-5fc88f00-5a34-11ea-9181-3cad1f4259f3.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75551160-d0bb7700-5a33-11ea-8ffe-4c187b7b902b.png)
https://user-images.githubusercontent.com/20930745/75551160-d0bb7700-5a33-11ea-8ffe-4c187b7b902b.png

Source:
https://user-images.githubusercontent.com/20930745/75551163-d31dd100-5a33-11ea-99ca-869aa7041a73.png
