### ISSUE TITLE
FAZ.NET - Nachrichten

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10722]
**App Name:** FAZ.NET - Nachrichten
**Bundle ID:** net.faz.FAZ
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375948652">375948652</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/faz-net-nachrichten/id375948652?uo=4">https://apps.apple.com/us/app/faz-net-nachrichten/id375948652?uo=4</a>
**App Version:** 10.4.1
**Seller:** Frankfurter Allgemeine Zeitung GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/frankfurter-allgemeine-zeitung-gmbh/id375948655?uo=4">© Frankfurter Allgemeine Zeitung GmbH</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/fb/03/24/fb0324ea-504e-9671-4bf8-cadf6bce0d75/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75578851-ed23d780-5a64-11ea-850a-c5f7ec828bad.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=(https://user-images.githubusercontent.com/20930745/75578851-ed23d780-5a64-11ea-850a-c5f7ec828bad.png)
https://user-images.githubusercontent.com/20930745/75578851-ed23d780-5a64-11ea-850a-c5f7ec828bad.png

Source:
https://user-images.githubusercontent.com/20930745/75578855-ef863180-5a64-11ea-8779-fe72a7a19433.png
