### ISSUE TITLE
Lotto Baden-Württemberg

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10727]
**App Name:** Lotto Baden-Württemberg
**Bundle ID:** de.lottobadenwuerttemberg.lottobw
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=903035939">903035939</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/lotto-baden-w%C3%BCrttemberg/id903035939?uo=4">https://apps.apple.com/de/app/lotto-baden-w%C3%BCrttemberg/id903035939?uo=4</a>
**App Version:** 2.3.2
**Seller:** Staatliche Toto-Lotto GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/staatliche-toto-lotto-gmbh-baden-w%C3%BCrttemberg/id903035942?uo=4">© Staatliche Toto-Lotto GmbH Baden-Württemberg</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/a0/40/26/a04026dc-6690-f198-790f-240285233825/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75581113-30804500-5a69-11ea-9f12-8ae2d7fa6080.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75580737-93bda780-5a68-11ea-8848-81fe1e7735e2.png)
https://user-images.githubusercontent.com/20930745/75580737-93bda780-5a68-11ea-8848-81fe1e7735e2.png

Source:
https://user-images.githubusercontent.com/20930745/75580746-94eed480-5a68-11ea-9556-9335e121b658.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75581113-30804500-5a69-11ea-9f12-8ae2d7fa6080.png)
https://user-images.githubusercontent.com/20930745/75581113-30804500-5a69-11ea-9f12-8ae2d7fa6080.png

Source:
https://user-images.githubusercontent.com/20930745/75581116-31b17200-5a69-11ea-8e47-91c4f4934b07.png
