### ISSUE TITLE
Mobil in Düsseldorf

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10729]
**App Name:** Mobil in Düsseldorf
**Bundle ID:** com.moovel.rheinbahn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1437799008">1437799008</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mobil-in-d%C3%BCsseldorf/id1437799008?uo=4">https://apps.apple.com/us/app/mobil-in-d%C3%BCsseldorf/id1437799008?uo=4</a>
**App Version:** 1.9.0
**Seller:** moovel Group GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/moovel-group-gmbh/id1053558571?uo=4">© moovel Group GmbH</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/c4/87/ef/c487effb-5487-932c-cfed-4ac0198257f8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75582004-f44de400-5a6a-11ea-9f6e-e1230cece9dc.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75582004-f44de400-5a6a-11ea-9f6e-e1230cece9dc.png)
https://user-images.githubusercontent.com/20930745/75582004-f44de400-5a6a-11ea-9f6e-e1230cece9dc.png

Source:
https://user-images.githubusercontent.com/20930745/75582010-f6b03e00-5a6a-11ea-8107-2e1a81fae78b.png
