### ISSUE TITLE
SSB BestPreis

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10720]
**App Name:** SSB BestPreis
**Bundle ID:** com.moovel.ssb-bestprice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1308950548">1308950548</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ssb-bestpreis/id1308950548?uo=4">https://apps.apple.com/us/app/ssb-bestpreis/id1308950548?uo=4</a>
**App Version:** 2.6.0
**Seller:** moovel Group GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/moovel-group-gmbh/id1053558571?uo=4">© moovel Group GmbH</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/3d/88/86/3d888648-73cc-fd87-f106-d0dc5f8eefee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75577936-43901680-5a63-11ea-8f90-ccb2edd9e9cc.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75577936-43901680-5a63-11ea-8f90-ccb2edd9e9cc.png)
https://user-images.githubusercontent.com/20930745/75577936-43901680-5a63-11ea-8f90-ccb2edd9e9cc.png

Source:
https://user-images.githubusercontent.com/20930745/75577942-45f27080-5a63-11ea-9dce-674e13787393.png

**Comment by jochulo** [comment]
How does inverted look? Thank you again!!

**Comment by jochulo** [comment]
No, leave it like that. White part on the top!! Thanks!

**Comment by 2Qt2beStr8** [comment]
@jochulo deine Entscheidung :) welches soll ich nehmen?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75584144-61637880-5a6f-11ea-8187-b0d7e699a117.png)
https://user-images.githubusercontent.com/20930745/75584144-61637880-5a6f-11ea-8187-b0d7e699a117.png

Source:
https://user-images.githubusercontent.com/20930745/75584145-632d3c00-5a6f-11ea-824e-0ee9d394b676.png

**Comment by jochulo** [comment]
Die erste variante finde ich super! Danke :) !!!
