### ISSUE TITLE
VICE Media

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10726]
**App Name:** VICE Media
**Bundle ID:** com.vice.iphone.vicemagazine
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=591496838">591496838</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/vice-media/id591496838?uo=4">https://apps.apple.com/us/app/vice-media/id591496838?uo=4</a>
**App Version:** 2.2.16
**Seller:** VICE Media Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/vice-media-inc/id473560951?uo=4">© Vice Media, Inc.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/bc/6d/1e/bc6d1e05-bfcb-97c1-4ca9-997d5e90edee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75580254-b8654f80-5a67-11ea-933c-ed2c59dd20b6.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75580254-b8654f80-5a67-11ea-933c-ed2c59dd20b6.png)
(https://user-images.githubusercontent.com/20930745/75580254-b8654f80-5a67-11ea-933c-ed2c59dd20b6.png

Source:
https://user-images.githubusercontent.com/20930745/75580258-ba2f1300-5a67-11ea-8124-200827c40bf3.png
