### ISSUE TITLE
Louis Vuitton

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10728]
**App Name:** Louis Vuitton
**Bundle ID:** com.louisvuitton.lv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=709101942">709101942</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/louis-vuitton/id709101942?uo=4">https://apps.apple.com/us/app/louis-vuitton/id709101942?uo=4</a>
**App Version:** 5.8.4
**Seller:** Louis Vuitton Malletier SA
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/louis-vuitton-malletier/id709101945?uo=4">© Louis Vuitton Malletier</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/07/ad/ca/07adcae3-9457-e540-c6ca-fabaf05a818a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75581461-cf0ca600-5a69-11ea-9dd6-33906da4ebcd.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75581461-cf0ca600-5a69-11ea-9dd6-33906da4ebcd.png)
https://user-images.githubusercontent.com/20930745/75581461-cf0ca600-5a69-11ea-9dd6-33906da4ebcd.png

Source:
https://user-images.githubusercontent.com/20930745/75581466-d0d66980-5a69-11ea-89ae-fbc699489621.png
