### ISSUE TITLE
Taxfix – Easy tax declaration

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10725]
**App Name:** Taxfix – Easy tax declaration
**Bundle ID:** de.taxfix.Taxfix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1163776422">1163776422</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/taxfix-easy-tax-declaration/id1163776422?uo=4">https://apps.apple.com/us/app/taxfix-easy-tax-declaration/id1163776422?uo=4</a>
**App Version:** 1.68.0
**Seller:** Taxfix GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/taxfix-gmbh/id1163776421?uo=4">© Taxfix GmbH</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/46/34/75/463475a6-7056-fca1-3980-aea9985e91b5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75579932-1fcecf80-5a67-11ea-80d5-02bbce4aead3.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75579932-1fcecf80-5a67-11ea-80d5-02bbce4aead3.png)
https://user-images.githubusercontent.com/20930745/75579932-1fcecf80-5a67-11ea-80d5-02bbce4aead3.png

Source:
https://user-images.githubusercontent.com/20930745/75579935-21989300-5a67-11ea-9bdb-a13115165a0e.png
