### ISSUE TITLE
IKEA Place

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10724]
**App Name:** IKEA Place
**Bundle ID:** com.inter-ikea.place
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1279244498">1279244498</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ikea-place/id1279244498?uo=4">https://apps.apple.com/us/app/ikea-place/id1279244498?uo=4</a>
**App Version:** 4.2.0
**Seller:** Inter IKEA Systems B.V.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/inter-ikea-systems-b-v/id339722471?uo=4">© Inter IKEA Systems B.V.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/26/ea/41/26ea4101-4e8b-f2ee-43cf-1243b91dffe4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75579650-961f0200-5a66-11ea-9fd1-9dcc6cd0657a.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75579650-961f0200-5a66-11ea-9fd1-9dcc6cd0657a.png)
https://user-images.githubusercontent.com/20930745/75579650-961f0200-5a66-11ea-9fd1-9dcc6cd0657a.png

Source:
https://user-images.githubusercontent.com/20930745/75579657-98815c00-5a66-11ea-9632-8f6398a28480.png

**Comment by jochulo** [comment]
Perfect
