### ISSUE TITLE
SSB Flex

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10721]
**App Name:** SSB Flex
**Bundle ID:** com.moovel.ssbondemand
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1314326748">1314326748</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ssb-flex/id1314326748?uo=4">https://apps.apple.com/us/app/ssb-flex/id1314326748?uo=4</a>
**App Version:** 3.6.0
**Seller:** moovel Group GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/moovel-group-gmbh/id1053558571?uo=4">© moovel Group GmbH</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/7a/e0/0b/7ae00b9c-ea78-200f-d63c-14d31e43c34c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75578559-57884800-5a64-11ea-89c2-0f31b6790242.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75578559-57884800-5a64-11ea-89c2-0f31b6790242.png)
https://user-images.githubusercontent.com/20930745/75578559-57884800-5a64-11ea-89c2-0f31b6790242.png

Source:
https://user-images.githubusercontent.com/20930745/75578564-59520b80-5a64-11ea-8d8e-c65e80d66d05.png
