### ISSUE TITLE
HBX | Globally Curated Fashion

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10723]
**App Name:** HBX | Globally Curated Fashion
**Bundle ID:** com.store.hypebeast.HypebeastStore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=895353739">895353739</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hbx-globally-curated-fashion/id895353739?uo=4">https://apps.apple.com/us/app/hbx-globally-curated-fashion/id895353739?uo=4</a>
**App Version:** 4.7.15
**Seller:** 101 Media Lab Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/101-media-lab-ltd/id895353742?uo=4">© 101 Media Lab Ltd.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/83/04/c9/8304c93b-73bb-8f13-3fe8-ab904574da55/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75579163-8357fd80-5a65-11ea-8c30-31eb93ca24dc.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75579163-8357fd80-5a65-11ea-8c30-31eb93ca24dc.png)
https://user-images.githubusercontent.com/20930745/75579163-8357fd80-5a65-11ea-8c30-31eb93ca24dc.png

Source:
https://user-images.githubusercontent.com/20930745/75579167-8521c100-5a65-11ea-9ed4-0e527a2e4dc9.png
