### ISSUE TITLE
VOI Scooters: Get Magic Wheels

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10732]
**App Name:** VOI Scooters: Get Magic Wheels
**Bundle ID:** com.voiapp.voi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1395921017">1395921017</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/voi-scooters-get-magic-wheels/id1395921017?uo=4">https://apps.apple.com/us/app/voi-scooters-get-magic-wheels/id1395921017?uo=4</a>
**App Version:** 6.4.1
**Seller:** VOI Technology AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/voi-technology-ab/id1395921015?uo=4">© VOI Technology AB</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/f0/46/e0/f046e06c-1f45-fcfd-de6a-29fbcd664e7c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75582878-d1bcca80-5a6c-11ea-9614-c9f79fc230ce.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75582878-d1bcca80-5a6c-11ea-9614-c9f79fc230ce.png)
https://user-images.githubusercontent.com/20930745/75582878-d1bcca80-5a6c-11ea-9614-c9f79fc230ce.png

Source:
![voiscooters](https://user-images.githubusercontent.com/20930745/75582885-d41f2480-5a6c-11ea-955c-774a87c44c5c.png
