### ISSUE TITLE
Nike

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10730]
**App Name:** Nike
**Bundle ID:** com.nike.omega
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1095459556">1095459556</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/nike/id1095459556?uo=4">https://apps.apple.com/us/app/nike/id1095459556?uo=4</a>
**App Version:** 2.100.0
**Seller:** Nike, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nike-inc/id301521406?uo=4">© Nike, Inc</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/62/c1/12/62c112b9-278c-f109-ecbd-5526d28b7483/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75582303-91a91800-5a6b-11ea-90e4-e6ce769f79de.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75582303-91a91800-5a6b-11ea-90e4-e6ce769f79de.png)
https://user-images.githubusercontent.com/20930745/75582303-91a91800-5a6b-11ea-90e4-e6ce769f79de.png

Source:
https://user-images.githubusercontent.com/20930745/75582310-979ef900-5a6b-11ea-95d4-2c2f2ed68b86.png
