### ISSUE TITLE
Lime - Your Ride Anytime

### ISSUE THREAD

**Issue by jochulo** [glasklart/hd#10731]
**App Name:** Lime - Your Ride Anytime
**Bundle ID:** com.limebike
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1199780189">1199780189</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/lime-your-ride-anytime/id1199780189?uo=4">https://apps.apple.com/us/app/lime-your-ride-anytime/id1199780189?uo=4</a>
**App Version:** 2.81.0
**Seller:** Neutron Holdings. Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/neutron-holdings-inc/id1199780188?uo=4">© Neutron Holdings. Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/8a/8b/7e/8a8b7e18-df55-0e5b-170a-31756054f541/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75582568-2a3f9800-5a6c-11ea-81f4-48e8760d16da.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75582568-2a3f9800-5a6c-11ea-81f4-48e8760d16da.png)
https://user-images.githubusercontent.com/20930745/75582568-2a3f9800-5a6c-11ea-81f4-48e8760d16da.png

Source:
https://user-images.githubusercontent.com/20930745/75582571-2ca1f200-5a6c-11ea-942e-725bec20b622.png

**Comment by 2Qt2beStr8** [comment]
@jochulo  please do not close the issues. we will do this!
