### ISSUE TITLE
Goibibo Flight,Hotel & Travel

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10739]
**App Name:** Goibibo Flight,Hotel & Travel
**Bundle ID:** com.goibibo.Goibibo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=631927169">631927169</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/goibibo-flight-hotel-travel/id631927169?uo=4">https://apps.apple.com/us/app/goibibo-flight-hotel-travel/id631927169?uo=4</a>
**App Version:** 7.2.2
**Seller:** ibibo Web Pvt. Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ibibo-web-pvt-ltd/id379106835?uo=4">© ibibo Web Pvt. Ltd</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/5a/3e/64/5a3e6484-64f5-307c-4875-4aaa5cf8d248/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75607960-b351e000-5afb-11ea-86ff-7c624074b72c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75607960-b351e000-5afb-11ea-86ff-7c624074b72c.png)
https://user-images.githubusercontent.com/20930745/75607960-b351e000-5afb-11ea-86ff-7c624074b72c.png

Source:
https://user-images.githubusercontent.com/20930745/75607961-b51ba380-5afb-11ea-88f4-c1821c423b63.png
