### ISSUE TITLE
Ola Cabs

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10735]
**App Name:** Ola Cabs
**Bundle ID:** olacabs.OlaCabs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=539179365">539179365</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ola-cabs/id539179365?uo=4">https://apps.apple.com/us/app/ola-cabs/id539179365?uo=4</a>
**App Version:** 4.8.38
**Seller:** ANI Technologies Pvt. Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ani-technologies-pvt-ltd/id539179368?uo=4">© ANI Technologies Pvt. Ltd.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/b8/fa/26/b8fa26a0-5d02-b887-1dc2-93923c361d55/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76161006-74d9a800-612f-11ea-9bfd-4e39e9510b87.png)

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75608490-2198a180-5b00-11ea-9c85-36f08514c0a3.png)
https://user-images.githubusercontent.com/20930745/75608490-2198a180-5b00-11ea-9c85-36f08514c0a3.png

Source:
https://user-images.githubusercontent.com/20930745/75608493-252c2880-5b00-11ea-9279-82ac7687ecad.png

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76161006-74d9a800-612f-11ea-9bfd-4e39e9510b87.png)
https://user-images.githubusercontent.com/20930745/76161006-74d9a800-612f-11ea-9bfd-4e39e9510b87.png

Source:
https://user-images.githubusercontent.com/20930745/76161007-760ad500-612f-11ea-9ea2-bceb7b89fb3a.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 The Second one. 👍
