### ISSUE TITLE
redBus

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10736]
**App Name:** redBus
**Bundle ID:** in.redbus.redBus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=733712604">733712604</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/redbus/id733712604?uo=4">https://apps.apple.com/us/app/redbus/id733712604?uo=4</a>
**App Version:** 7.1.5
**Seller:** PILANI SOFT LABS PRIVATE LIMITED
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/pilani-soft-labs-pvt-ltd/id813517112?uo=4">© Pilani Soft Labs Pvt. Ltd</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/e2/9f/b6/e29fb68d-d209-6426-a475-b5a4a11ab43d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75608257-3aa05300-5afe-11ea-96f0-858a600bc608.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75608257-3aa05300-5afe-11ea-96f0-858a600bc608.png)
https://user-images.githubusercontent.com/20930745/75608257-3aa05300-5afe-11ea-96f0-858a600bc608.png

Source:
https://user-images.githubusercontent.com/20930745/75608258-3d9b4380-5afe-11ea-82bc-cff1bdeda492.png
