### ISSUE TITLE
OYO: Search & Book Hotel Rooms

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10737]
**App Name:** OYO: Search & Book Hotel Rooms
**Bundle ID:** com.oyo.oyo-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=988141624">988141624</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/oyo-search-book-hotel-rooms/id988141624?uo=4">https://apps.apple.com/us/app/oyo-search-book-hotel-rooms/id988141624?uo=4</a>
**App Version:** 6.6.1
**Seller:** Oravel Stays Private Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/oravel-stays-private-ltd/id988141623?uo=4">© Oravel Stays Private Ltd.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/80/57/ec/8057ecbf-fb04-c83d-8a73-4fac37dd903b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75608185-a0400f80-5afd-11ea-929e-220919e6e305.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75608185-a0400f80-5afd-11ea-929e-220919e6e305.png)
https://user-images.githubusercontent.com/20930745/75608185-a0400f80-5afd-11ea-929e-220919e6e305.png

Source:
https://user-images.githubusercontent.com/20930745/75608187-a2a26980-5afd-11ea-83a7-47944213f56e.png
