### ISSUE TITLE
MakeMyTrip - Flights, Hotels

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10738]
**App Name:** MakeMyTrip - Flights, Hotels
**Bundle ID:** com.Iphone.MMT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=530488359">530488359</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/makemytrip-flights-hotels/id530488359?uo=4">https://apps.apple.com/us/app/makemytrip-flights-hotels/id530488359?uo=4</a>
**App Version:** 6.5.6
**Seller:** MakeMyTrip India Pvt. Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/makemytrip-com/id530488362?uo=4">© MakeMyTrip.com</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/d2/96/63/d2966313-bc28-ba90-df74-2deb19523b4d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75608073-af728d80-5afc-11ea-9c6b-ea708e26c11d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75608073-af728d80-5afc-11ea-9c6b-ea708e26c11d.png)
https://user-images.githubusercontent.com/20930745/75608073-af728d80-5afc-11ea-9c6b-ea708e26c11d.png

Source:
https://user-images.githubusercontent.com/20930745/75608075-b13c5100-5afc-11ea-8319-89698ef8c8b9.png
