### ISSUE TITLE
Zoho OneAuth

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10734]
**App Name:** Zoho OneAuth
**Bundle ID:** com.zoho.iamlogin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1142928979">1142928979</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/zoho-oneauth/id1142928979?uo=4">https://apps.apple.com/us/app/zoho-oneauth/id1142928979?uo=4</a>
**App Version:** 1.2.6
**Seller:** Zoho Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/zoho-corporation/id388384807?uo=4">© Zoho Corporation</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/62/ef/38/62ef388c-62b4-7a19-8623-681e79722e44/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75608359-0a0ce900-5aff-11ea-9993-ddc8b9cfafc0.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75608359-0a0ce900-5aff-11ea-9993-ddc8b9cfafc0.png)
https://user-images.githubusercontent.com/20930745/75608359-0a0ce900-5aff-11ea-9993-ddc8b9cfafc0.png

Source:
https://user-images.githubusercontent.com/20930745/75608361-0bd6ac80-5aff-11ea-91dd-fefb4cd9dd9e.png
