### ISSUE TITLE
LIC Customer

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10748]
**App Name:** LIC Customer
**Bundle ID:** com.lic.liccustomer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1324159013">1324159013</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/lic-customer/id1324159013?uo=4">https://apps.apple.com/us/app/lic-customer/id1324159013?uo=4</a>
**App Version:** 1.1.3
**Seller:** Life Insurance Corporation of India
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/life-insurance-corporation-of-india/id1265071093?uo=4">© Life Insurance Corporation of India</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/9d/4e/b5/9d4eb5e1-9f08-3360-626f-8148d5e6227e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/76710134-2e72e300-6705-11ea-8b93-d90ae33941d4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/76710134-2e72e300-6705-11ea-8b93-d90ae33941d4.png)
https://user-images.githubusercontent.com/2068130/76710134-2e72e300-6705-11ea-8b93-d90ae33941d4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/76710141-40ed1c80-6705-11ea-8596-a130bb38a25b.png
