### ISSUE TITLE
RTO Vehicle Information India

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10747]
**App Name:** RTO Vehicle Information India
**Bundle ID:** com.cuvora.carinfoios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1146173741">1146173741</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/rto-vehicle-information-india/id1146173741?uo=4">https://apps.apple.com/us/app/rto-vehicle-information-india/id1146173741?uo=4</a>
**App Version:** 2.6.0
**Seller:** Cuvora
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cuvora/id1146172240?uo=4">© Cuvora</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/ed/1c/0f/ed1c0fa3-3de3-d365-9710-fc6691c921bd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78460478-65636580-76c1-11ea-87a1-90af9bfbfdce.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78460478-65636580-76c1-11ea-87a1-90af9bfbfdce.png)
https://user-images.githubusercontent.com/2068130/78460478-65636580-76c1-11ea-87a1-90af9bfbfdce.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/78460490-77450880-76c1-11ea-884a-5eb39b252020.png
