### ISSUE TITLE
DBS IDEAL Mobile

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10742]
**App Name:** DBS IDEAL Mobile
**Bundle ID:** com.dbs.ideal.m
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445770685">445770685</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dbs-ideal-mobile/id445770685?uo=4">https://apps.apple.com/us/app/dbs-ideal-mobile/id445770685?uo=4</a>
**App Version:** 2.17.1
**Seller:** DBS Bank Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dbs-bank-ltd/id362707070?uo=4">© DBS Bank Ltd.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/a6/f7/ab/a6f7ab8c-e907-5e20-0935-1805c776e665/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75607615-53f2d080-5af9-11ea-9adf-ec4ecf2aad69.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75607615-53f2d080-5af9-11ea-9adf-ec4ecf2aad69.png)
https://user-images.githubusercontent.com/20930745/75607615-53f2d080-5af9-11ea-9adf-ec4ecf2aad69.png

Source:
https://user-images.githubusercontent.com/20930745/75607618-56552a80-5af9-11ea-9321-d2275af7a33b.png
