### ISSUE TITLE
Detector

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10745]
App Name: Detector
Bundle ID: com.michelbarnich.Detector
Version: 1.3.5-j
iTunes ID: none (Cydia app)

Original Artwork:
![AppIcon83 5x83 5@2x~ipad](https://user-images.githubusercontent.com/20930745/75620354-49cbe300-5b88-11ea-83da-7e04c2470087.png)

Accepted Artwork:
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75620565-87317000-5b8a-11ea-8448-5c9e0f054544.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75620565-87317000-5b8a-11ea-8448-5c9e0f054544.png)
https://user-images.githubusercontent.com/20930745/75620565-87317000-5b8a-11ea-8448-5c9e0f054544.png

Source:
https://user-images.githubusercontent.com/20930745/75620567-88fb3380-5b8a-11ea-8a30-71056416b630.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Kannst Du das Original-Artwork in ein gültiges png konvertieren?

**Comment by 2Qt2beStr8** [comment]
@dreamnet erledigt
