### ISSUE TITLE
Picnic Supermarket

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10746]
**App Name:** Picnic Supermarket
**Bundle ID:** nl.picnic.picnic-supermarkt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1018175041">1018175041</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/picnic-supermarket/id1018175041?uo=4">https://apps.apple.com/us/app/picnic-supermarket/id1018175041?uo=4</a>
**App Version:** 1.15.43
**Seller:** Picnic B.V.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/picnic-bv/id1018175040?uo=4">© Picnic BV</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/4e/44/b7/4e44b7cc-705f-11b8-7096-e9162d7db8f9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/76687302-ebd8da00-6622-11ea-960f-835a8c9d4854.png)

**Comment by dreamnet** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/76687302-ebd8da00-6622-11ea-960f-835a8c9d4854.png)
https://user-images.githubusercontent.com/2068130/76687302-ebd8da00-6622-11ea-960f-835a8c9d4854.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/76687309-fe531380-6622-11ea-8ce6-9c153a3276ac.png
