### ISSUE TITLE
JetBlue

### ISSUE THREAD

**Issue by lshishido03** [glasklart/hd#1074]
**App Name:** JetBlue
**Bundle ID:** com.jetblue.jetBlueiPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=481370590">481370590</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jetblue/id481370590?mt=8&uo=4">https://itunes.apple.com/us/app/jetblue/id481370590?mt=8&uo=4</a>
**App Version:** 4.2.1
**Seller:** JetBlue Airways Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jetblue-airways/id481370593?uo=4">© JetBlue Airways</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/b3/57/ea/b357ea64-db5f-6e2c-a912-fbdf3be1a1eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39069174-3f200d12-44df-11e8-9a39-79276081f4c8.png)

**Comment by 2Qt2beStr8** [comment]
?
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39068936-568a8d84-44de-11e8-872b-8eb7479e8eec.png)
https://user-images.githubusercontent.com/20930745/39068936-568a8d84-44de-11e8-872b-8eb7479e8eec.png

Source:
https://user-images.githubusercontent.com/20930745/39068954-66af9a88-44de-11e8-94dc-89209c262418.png

**Comment by 2Qt2beStr8** [comment]
?
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39069174-3f200d12-44df-11e8-9a39-79276081f4c8.png)
https://user-images.githubusercontent.com/20930745/39069174-3f200d12-44df-11e8-9a39-79276081f4c8.png

Source:
https://user-images.githubusercontent.com/20930745/39069196-5285ef16-44df-11e8-9585-e9a58dc8cc33.png
