### ISSUE TITLE
Cleartrip

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10740]
**App Name:** Cleartrip
**Bundle ID:** com.cleartrip.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=531324961">531324961</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cleartrip/id531324961?uo=4">https://apps.apple.com/us/app/cleartrip/id531324961?uo=4</a>
**App Version:** 20.2.0
**Seller:** Cleartrip Travel Services Pvt. Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cleartrip/id531324964?uo=4">© Cleartrip</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/e2/41/d6/e241d608-afa6-1992-c1e9-831ded14d35c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75607830-33c41100-5afb-11ea-9771-44c2969ba78c.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75607830-33c41100-5afb-11ea-9771-44c2969ba78c.png)
https://user-images.githubusercontent.com/20930745/75607830-33c41100-5afb-11ea-9771-44c2969ba78c.png

Source:
https://user-images.githubusercontent.com/20930745/75607832-358dd480-5afb-11ea-88e3-597a823b828e.png
