### ISSUE TITLE
Paytm Money Mutual Funds App

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10741]
**App Name:** Paytm Money Mutual Funds App
**Bundle ID:** com.one97.paytmmoney
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1344431352">1344431352</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/paytm-money-mutual-funds-app/id1344431352?uo=4">https://apps.apple.com/us/app/paytm-money-mutual-funds-app/id1344431352?uo=4</a>
**App Version:** 1.21.2
**Seller:** PayTM Mobile Solutions Private Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/paytm-mobile-solutions/id473941637?uo=4">© Paytm Mobile Solutions</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/53/68/f6/5368f6aa-42dd-dd60-454b-9020234faa8b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75607723-66b9d500-5afa-11ea-976e-25d1e15246b8.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75607723-66b9d500-5afa-11ea-976e-25d1e15246b8.png)
https://user-images.githubusercontent.com/20930745/75607723-66b9d500-5afa-11ea-976e-25d1e15246b8.png

Source:
https://user-images.githubusercontent.com/20930745/75607728-6a4d5c00-5afa-11ea-8bdf-358c48fd2a2a.png
