### ISSUE TITLE
Stacks 2 - New Age Currency Converter

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10749]
**App Name:** Stacks 2 - New Age Currency Converter
**Bundle ID:** com.waplestuff.Stacks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=719162125">719162125</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stacks-2-new-age-currency-converter/id719162125?uo=4">https://apps.apple.com/us/app/stacks-2-new-age-currency-converter/id719162125?uo=4</a>
**App Version:** 2.7.4
**Seller:** Raja V
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/waplestuff/id562575890?uo=4">© WapleStuff</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/87/35/ea/8735ea64-9421-e5df-e004-3ae9f7208a6d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700063-d2cc3980-66b3-11ea-84c0-013fef1b3e80.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700063-d2cc3980-66b3-11ea-84c0-013fef1b3e80.png)
https://user-images.githubusercontent.com/20930745/76700063-d2cc3980-66b3-11ea-84c0-013fef1b3e80.png

Source:
https://user-images.githubusercontent.com/20930745/76700064-d495fd00-66b3-11ea-8474-3bfadfb10549.png
