### ISSUE TITLE
CRED - Pay credit card bills

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10743]
**App Name:** CRED - Pay credit card bills
**Bundle ID:** com.dreamplug.cred
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1428580080">1428580080</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cred-pay-credit-card-bills/id1428580080?uo=4">https://apps.apple.com/us/app/cred-pay-credit-card-bills/id1428580080?uo=4</a>
**App Version:** 2.2.2
**Seller:** Dreamplug Technologies Private Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dreamplug/id1428580079?uo=4">© Dreamplug</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/3c/13/5f/3c135f10-f10b-bfb5-95b6-a48c4fa5daf6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75607567-b4354280-5af8-11ea-9cbd-3ebeb7bbc2a1.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/75607567-b4354280-5af8-11ea-9cbd-3ebeb7bbc2a1.png)
https://user-images.githubusercontent.com/20930745/75607567-b4354280-5af8-11ea-9cbd-3ebeb7bbc2a1.png

Source:
https://user-images.githubusercontent.com/20930745/75607568-b5ff0600-5af8-11ea-953d-9f7124cf75fc.png
