### ISSUE TITLE
Urban Ladder

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10753]
**App Name:** Urban Ladder
**Bundle ID:** com.urbanladder.Catalog-App
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=959886087">959886087</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/urban-ladder/id959886087?uo=4">https://apps.apple.com/us/app/urban-ladder/id959886087?uo=4</a>
**App Version:** 5.4.1
**Seller:** Urban Ladder Home Decor Solutions Private Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/urban-ladder/id904520770?uo=4">© Urban Ladder</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/cb/b0/73/cbb073da-6aa9-ea1b-8110-f4c88feb918c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700346-e3ca7a00-66b6-11ea-8f9b-c3d1bd6f535d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700346-e3ca7a00-66b6-11ea-8f9b-c3d1bd6f535d.png)
https://user-images.githubusercontent.com/20930745/76700346-e3ca7a00-66b6-11ea-8f9b-c3d1bd6f535d.png

Source:
https://user-images.githubusercontent.com/20930745/76700347-e62cd400-66b6-11ea-8a37-d457eb8f2c85.png
