### ISSUE TITLE
SPI Cinemas Movie Tickets

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10754]
**App Name:** SPI Cinemas Movie Tickets
**Bundle ID:** in.spicinemas.iphoneappv1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=904927087">904927087</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/spi-cinemas-movie-tickets/id904927087?uo=4">https://apps.apple.com/us/app/spi-cinemas-movie-tickets/id904927087?uo=4</a>
**App Version:** 2.12
**Seller:** SPI CINEMAS PRIVATE LIMITED
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/spi-cinemas-pvt-ltd/id904927090?uo=4">© SPI Cinemas Pvt. Ltd.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/54/12/55/54125571-2fbb-b8f1-f109-0ec3a062b651/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700437-c21dc280-66b7-11ea-8899-29e0fdc4c9c1.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700437-c21dc280-66b7-11ea-8899-29e0fdc4c9c1.png)
https://user-images.githubusercontent.com/20930745/76700437-c21dc280-66b7-11ea-8899-29e0fdc4c9c1.png

Source:
https://user-images.githubusercontent.com/20930745/76700439-c3e78600-66b7-11ea-8b44-c262a0f07a8f.png
