### ISSUE TITLE
Myntra - Fashion Shopping App

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10751]
**App Name:** Myntra - Fashion Shopping App
**Bundle ID:** com.myntra.Myntra
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=907394059">907394059</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myntra-fashion-shopping-app/id907394059?uo=4">https://apps.apple.com/us/app/myntra-fashion-shopping-app/id907394059?uo=4</a>
**App Version:** 4.2002.0
**Seller:** Myntra Designs Private Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/myntra-com/id784440582?uo=4">© myntra.com</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/70/5d/e3/705de38d-a6ff-d8a2-5531-cf81574c83b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/76838421-7ba1a280-6834-11ea-904a-63cf2f022a48.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/76838421-7ba1a280-6834-11ea-904a-63cf2f022a48.png)
https://user-images.githubusercontent.com/2068130/76838421-7ba1a280-6834-11ea-904a-63cf2f022a48.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/76838577-8ceaaf00-6834-11ea-901a-667e8fbf8501.png
