### ISSUE TITLE
Dream11 Fantasy Sports

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10752]
**App Name:** Dream11 Fantasy Sports
**Bundle ID:** com.dream11.dream11app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1077286074">1077286074</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/in/app/dream11-fantasy-sports/id1077286074?uo=4">https://apps.apple.com/in/app/dream11-fantasy-sports/id1077286074?uo=4</a>
**App Version:** 3.56.0
**Seller:** DREAM11 FANTASY PRIVATE LIMITED
**Developer:** <a target="_blank" href="https://apps.apple.com/in/developer/dream11-fantasy-private-limited/id1241281789?uo=4">© DREAM11 FANTASY PRIVATE LIMITED</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/e5/60/68/e5606838-530e-7c24-973d-ec2a26e17cd7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700280-2f305880-66b6-11ea-832c-58f881c87f66.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700280-2f305880-66b6-11ea-832c-58f881c87f66.png)
(https://user-images.githubusercontent.com/20930745/76700280-2f305880-66b6-11ea-832c-58f881c87f66.png

Source:
https://user-images.githubusercontent.com/20930745/76700282-30fa1c00-66b6-11ea-89b4-b0fa214256da.png
