### ISSUE TITLE
Notebooks for iPhone

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10759]
**App Name:** Notebooks for iPhone
**Bundle ID:** com.aschmid.notebooks7-iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=780442075">780442075</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/notebooks-for-iphone/id780442075?uo=4">https://apps.apple.com/us/app/notebooks-for-iphone/id780442075?uo=4</a>
**App Version:** 8.11.5
**Seller:** Alfons Schmid
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/alfons-schmid/id297571754?uo=4">© Alfons Schmid</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/22/7b/57/227b5767-223e-b1e0-f59c-7da3c1d11f6e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78419276-80dc5b00-7644-11ea-9a82-37da11b5f6b1.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78419276-80dc5b00-7644-11ea-9a82-37da11b5f6b1.png)
https://user-images.githubusercontent.com/2068130/78419276-80dc5b00-7644-11ea-9a82-37da11b5f6b1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/78419280-93569480-7644-11ea-8f3e-1ec26922e760.png
