### ISSUE TITLE
Jabra Sound+

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10755]
**App Name:** Jabra Sound+
**Bundle ID:** com.jabra.moments
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1320805565">1320805565</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/jabra-sound/id1320805565?uo=4">https://apps.apple.com/us/app/jabra-sound/id1320805565?uo=4</a>
**App Version:** 4.0
**Seller:** GN Audio AS
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gn-audio-as/id410001694?uo=4">© GN Audio AS</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/3b/f4/54/3bf4542c-08e2-086d-bf88-f30c2f4be242/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700743-d1ead600-66ba-11ea-905f-001f8511b7e4.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700743-d1ead600-66ba-11ea-905f-001f8511b7e4.png)
https://user-images.githubusercontent.com/20930745/76700743-d1ead600-66ba-11ea-905f-001f8511b7e4.png

Source:
https://user-images.githubusercontent.com/20930745/76700746-d7482080-66ba-11ea-932f-0132f2a92059.png
