### ISSUE TITLE
Cashify - Sell Used Gadgets

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10750]
**App Name:** Cashify - Sell Used Gadgets
**Bundle ID:** in.cashify.user
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1133551195">1133551195</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cashify-sell-used-gadgets/id1133551195?uo=4">https://apps.apple.com/us/app/cashify-sell-used-gadgets/id1133551195?uo=4</a>
**App Version:** 3.7
**Seller:** Manak Waste Management Private Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/reglobe/id967368735?uo=4">© ReGlobe</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/3a/30/c1/3a30c1cb-2446-6f28-7ff2-eebe006f73a2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700163-3440d800-66b5-11ea-8489-465ba37aa393.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700163-3440d800-66b5-11ea-8489-465ba37aa393.png)
https://user-images.githubusercontent.com/20930745/76700163-3440d800-66b5-11ea-8489-465ba37aa393.png

Source:
https://user-images.githubusercontent.com/20930745/76700165-35720500-66b5-11ea-84cc-f05069c1ded3.png
