### ISSUE TITLE
NetNewsWire: RSS Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10758]
**App Name:** NetNewsWire: RSS Reader
**Bundle ID:** com.ranchero.NetNewsWire.iOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1480640210">1480640210</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/netnewswire-rss-reader/id1480640210?uo=4">https://apps.apple.com/us/app/netnewswire-rss-reader/id1480640210?uo=4</a>
**App Version:** 5.0
**Seller:** Brent Simmons
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/brent-simmons/id1480640209?uo=4">© Brent Simmons</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/37/88/ca/3788ca2d-e3bb-642f-597e-728104fe4f7d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77438964-ca2bdf80-6de6-11ea-94fd-2bb85db2a2bb.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77438964-ca2bdf80-6de6-11ea-94fd-2bb85db2a2bb.png)
https://user-images.githubusercontent.com/2068130/77438964-ca2bdf80-6de6-11ea-94fd-2bb85db2a2bb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/77439031-dadc5580-6de6-11ea-9ffd-7ff8c8d8874f.png
