### ISSUE TITLE
HIPBAR: The Drinks App

### ISSUE THREAD

**Issue by mahesh-kumars** [glasklart/hd#10756]
**App Name:** HIPBAR: The Drinks App
**Bundle ID:** com.hipbar.hipbar-pay-app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1297218847">1297218847</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hipbar-the-drinks-app/id1297218847?uo=4">https://apps.apple.com/us/app/hipbar-the-drinks-app/id1297218847?uo=4</a>
**App Version:** 2.1.4
**Seller:** Hip Bar Private Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hip-bar-private-limited/id1179371752?uo=4">© Hip Bar Private Limited</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/ae/99/3d/ae993d28-3a97-b972-16bf-fb9fa3495aa6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700826-b6cc9600-66bb-11ea-9744-38faa376bd02.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76700826-b6cc9600-66bb-11ea-9744-38faa376bd02.png)
https://user-images.githubusercontent.com/20930745/76700826-b6cc9600-66bb-11ea-9744-38faa376bd02.png

Source:
https://user-images.githubusercontent.com/20930745/76700829-b7fdc300-66bb-11ea-91c8-ca57ebb2fe46.png
