### ISSUE TITLE
24me Smart Personal Assistant - Automate Your Calendar, To-Do List, Tasks and Notes

### ISSUE THREAD

**Issue by lshishido03** [glasklart/hd#1076]
**App Name:** 24me Smart Personal Assistant - Automate Your Calendar, To-Do List, Tasks and Notes
**Bundle ID:** 24me
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=557745942">557745942</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/24me-smart-personal-assistant/id557745942?mt=8&uo=4">https://itunes.apple.com/us/app/24me-smart-personal-assistant/id557745942?mt=8&uo=4</a>
**App Version:** 4.0.3
**Seller:** 24me Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/24me/id557745945?uo=4>© 24me</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple18/v4/ef/b8/20/efb82027-0ec4-c790-4fa9-300723bfd6ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18239866/71e082d2-7348-11e6-9eb3-f30f64edc14b.png)

**Comment by l8er4now** [comment]
A little change, but needs to be resized.

**App Name:** 24me Smart Personal Assistant - Automate Your Calendar, To-Do List, Tasks and Notes
**Bundle ID:** 24me
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=557745942">557745942</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/24me-smart-personal-assistant/id557745942?mt=8&uo=4">https://itunes.apple.com/us/app/24me-smart-personal-assistant/id557745942?mt=8&uo=4</a>
**App Version:** 4.0.3
**Seller:** 24me Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/24me/id557745945?uo=4>© 24me</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple18/v4/ef/b8/20/efb82027-0ec4-c790-4fa9-300723bfd6ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18239866/71e082d2-7348-11e6-9eb3-f30f64edc14b.png)
https://cloud.githubusercontent.com/assets/20930745/18239866/71e082d2-7348-11e6-9eb3-f30f64edc14b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18239880/82ce9750-7348-11e6-9e1c-7db705a8d40a.png
