### ISSUE TITLE
Houseparty

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10763]
**App Name:** Houseparty
**Bundle ID:** com.herzick.houseparty
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1065781769">1065781769</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/houseparty/id1065781769?uo=4">https://apps.apple.com/us/app/houseparty/id1065781769?uo=4</a>
**App Version:** 1.34.1
**Seller:** Life On Air, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/life-on-air-inc/id1065781768?uo=4">© Life On Air, Inc</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/e3/91/28/e39128e6-cbc1-03c8-8db9-05db9bf6e5e1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78284177-4c22b380-751f-11ea-89aa-718093bc106c.png)

**Comment by kayjeiem** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2732955/78075601-83715300-73ad-11ea-85a4-5977e7ab98ec.png)

Source
![68747470733a2f2f6973342d73736c2e6d7a7374617469632e636f6d2f696d6167652f7468756d622f507572706c653132332f76342f65332f39312f32382f65333931323865362d636263312d303363382d386462392d3035646239626636653565312f736f757263652f31303234783130323462622e70](https://user-images.githubusercontent.com/2732955/78075689-ab60b680-73ad-11ea-95f6-b5c1c1522ff6.png)

**Comment by ivanov007** [comment]
@kayjeiem your source should be the b/w file before applying the gradient on 1024 x 1024 resolution

**Comment by kayjeiem** [comment]
> @kayjeiem your source should be the b/w file before applying the gradient on 1024 x 1024 resolution

Noted. Let me upload the right file. Thanks.

**Comment by dreamnet** [comment]
@kayjeiem Nice work, but we should go with the original size. Credits are going to you!
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78284177-4c22b380-751f-11ea-89aa-718093bc106c.png)
https://user-images.githubusercontent.com/2068130/78284177-4c22b380-751f-11ea-89aa-718093bc106c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/78284212-5ba1fc80-751f-11ea-80f4-d23967f95677.png
