### ISSUE TITLE
Senaptec: Sensory Performance

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10764]
**App Name:** Senaptec: Sensory Performance
**Bundle ID:** com.senaptex.sentraining
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1451224381">1451224381</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/senaptec-sensory-performance/id1451224381?uo=4">https://apps.apple.com/us/app/senaptec-sensory-performance/id1451224381?uo=4</a>
**App Version:** 1.0.6
**Seller:** Senaptec LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/senaptec/id1213524229?uo=4">© Senaptec</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/0b/b7/14/0bb7142e-5213-f4c0-6493-02ec62b359df/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77832155-333b8c00-7134-11ea-8882-04264805a2b1.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77832155-333b8c00-7134-11ea-8882-04264805a2b1.png)
https://user-images.githubusercontent.com/2068130/77832155-333b8c00-7134-11ea-8882-04264805a2b1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/77832164-44849880-7134-11ea-9926-102ec7456e5b.png
