### ISSUE TITLE
Google Duo

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10762]
**App Name:** Google Duo
**Bundle ID:** com.google.Tachyon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1096918571">1096918571</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-duo/id1096918571?uo=4">https://apps.apple.com/us/app/google-duo/id1096918571?uo=4</a>
**App Version:** 80.0
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/35/0c/e6/350ce6ff-2940-37b2-6935-a3bbde168bc4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77832540-2c624880-7137-11ea-860e-d4e07cf4a736.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77832540-2c624880-7137-11ea-860e-d4e07cf4a736.png)
https://user-images.githubusercontent.com/2068130/77832540-2c624880-7137-11ea-860e-d4e07cf4a736.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/77832551-413edc00-7137-11ea-9847-aa3f99319501.png
