### ISSUE TITLE
Senaptec Remote

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10765]
**App Name:** Senaptec Remote
**Bundle ID:** senaptec.senaptecremote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1420713938">1420713938</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/senaptec-remote/id1420713938?uo=4">https://apps.apple.com/us/app/senaptec-remote/id1420713938?uo=4</a>
**App Version:** 1.3.25
**Seller:** Senaptec LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/senaptec/id1213524229?uo=4">© Senaptec</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/ef/40/6c/ef406ce9-4204-544a-d4be-952fb287899f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77832264-0b98f380-7135-11ea-98a8-e357ab4389e1.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77832264-0b98f380-7135-11ea-98a8-e357ab4389e1.png)
https://user-images.githubusercontent.com/2068130/77832264-0b98f380-7135-11ea-98a8-e357ab4389e1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/77832272-1bb0d300-7135-11ea-9858-070e7b417844.png
