### ISSUE TITLE
Crave

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10768]
**App Name:** Crave
**Bundle ID:** ca.bellmedia.cravetv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942568279">942568279</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/ca/app/crave/id942568279?uo=4">https://apps.apple.com/ca/app/crave/id942568279?uo=4</a>
**App Version:** 3.28.0
**Seller:** Bell Media Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/ca/developer/bell-media-inc/id328082347?uo=4">© Bell Media Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/91/42/81/914281a2-1fec-bc38-aa35-bf0bbca0519c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77818027-8e876300-70cf-11ea-8836-b2e36c08f196.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/77818027-8e876300-70cf-11ea-8836-b2e36c08f196.png)
https://user-images.githubusercontent.com/2068130/77818027-8e876300-70cf-11ea-8836-b2e36c08f196.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/77818038-9f37d900-70cf-11ea-9a3e-1105c2e637de.png
