### ISSUE TITLE
Saviry - Deals, Freebies, Sales - best online shopping FREE

### ISSUE THREAD

**Issue by lshishido03** [glasklart/hd#1077]
**App Name:** Saviry - Deals, Freebies, Sales - best online shopping FREE
**Bundle ID:** com.islickapp.islick
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431491469">431491469</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/saviry-deals-freebies-sales/id431491469?mt=8&uo=4">https://itunes.apple.com/us/app/saviry-deals-freebies-sales/id431491469?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** Lanuta LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lanuta-llc/id431370572?uo=4>© Lanuta LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/f3/7c/2e/f37c2ee2-e466-f9f6-cccd-544ce53b24af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617506/b0a6fcda-9832-11e6-995d-442205d26d15.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617506/b0a6fcda-9832-11e6-995d-442205d26d15.png)
https://cloud.githubusercontent.com/assets/20930745/19617506/b0a6fcda-9832-11e6-995d-442205d26d15.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617513/d84499c8-9832-11e6-84ca-4edbee50e037.png
