### ISSUE TITLE
Watchsmith

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10779]
**App Name:** Watchsmith
**Bundle ID:** com.crossforward.projectgeneva
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1483088503">1483088503</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/watchsmith/id1483088503?uo=4">https://apps.apple.com/us/app/watchsmith/id1483088503?uo=4</a>
**App Version:** 1.0.1
**Seller:** Cross Forward Consulting, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cross-forward-consulting-llc/id295660206?uo=4">© Cross Forward Consulting, LLC</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/6f/7d/f3/6f7df352-60ad-1f9c-2c8c-7a8a5f3825a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79038128-307e7380-7bd7-11ea-9997-df5f43009f82.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/78965162-dc359f80-7ac1-11ea-9a8d-865fb50050e4.png)
https://user-images.githubusercontent.com/44279267/78965162-dc359f80-7ac1-11ea-9a8d-865fb50050e4.png

Data Source:
https://user-images.githubusercontent.com/44279267/78965165-dfc92680-7ac1-11ea-8fd0-43cdfc055ed7.png

**Comment by dreamnet** [comment]
@tlunmp Wrong source, but OK.
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79038128-307e7380-7bd7-11ea-9997-df5f43009f82.png)
https://user-images.githubusercontent.com/2068130/79038128-307e7380-7bd7-11ea-9997-df5f43009f82.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79038137-3ffdbc80-7bd7-11ea-8b19-ea8746cd001d.png
