### ISSUE TITLE
MarketWatch - News & Data

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10777]
**App Name:** MarketWatch - News & Data
**Bundle ID:** com.dowjones.mktw
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336693422">336693422</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/marketwatch-news-data/id336693422?uo=4">https://apps.apple.com/us/app/marketwatch-news-data/id336693422?uo=4</a>
**App Version:** 6.0.5
**Seller:** Dow Jones & Company, Inc., publisher of The Wall Street Journal.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dow-jones-company-inc-publisher-of-the-wall-street-journal/id311822186?uo=4">© Dow Jones & Company, Inc., publisher of The Wall Street Journal.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/1e/51/5f/1e515f81-006f-e232-1163-98cb043ecb3a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78795049-cd14fb80-79b4-11ea-9e37-42c065a68fac.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78795049-cd14fb80-79b4-11ea-9e37-42c065a68fac.png)
https://user-images.githubusercontent.com/2068130/78795049-cd14fb80-79b4-11ea-9e37-42c065a68fac.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/78795099-dbfbae00-79b4-11ea-8287-d0c969c65b24.png
