### ISSUE TITLE
Moe's Broadway Bagel

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10778]
**App Name:** Moe's Broadway Bagel
**Bundle ID:** com.ChowNow.MoesBroadwayBagel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1084069323">1084069323</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/moes-broadway-bagel/id1084069323?uo=4">https://apps.apple.com/us/app/moes-broadway-bagel/id1084069323?uo=4</a>
**App Version:** 2.6.5
**Seller:** ChowNow, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/chownow/id553996348?uo=4">© ChowNow</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/c5/3d/f0/c53df096-408e-b6a2-1ff9-ff471d520ce5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79038331-c23ab080-7bd8-11ea-8c65-78941d326308.png)

**Comment by tlunmp** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/78961918-a2ac6680-7ab8-11ea-8422-60d7bc2f96d5.png)
https://user-images.githubusercontent.com/44279267/78961918-a2ac6680-7ab8-11ea-8422-60d7bc2f96d5.png

Data Source:
https://user-images.githubusercontent.com/44279267/78962075-1b132780-7ab9-11ea-9d34-2b9e22c76d7f.png

**Comment by dreamnet** [comment]
?
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79038331-c23ab080-7bd8-11ea-8c65-78941d326308.png)
https://user-images.githubusercontent.com/2068130/79038331-c23ab080-7bd8-11ea-8c65-78941d326308.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79038345-d383bd00-7bd8-11ea-8a35-81462f836063.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 What do you think?

**Comment by 2Qt2beStr8** [comment]
@dreamnet  the second one
