### ISSUE TITLE
Magic Hour

### ISSUE THREAD

**Issue by kayjeiem** [glasklart/hd#10774]
**App Name:** Magic Hour
**Bundle ID:** com.elfinda.magichour
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=482426006">482426006</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/magic-hour/id482426006?uo=4">https://apps.apple.com/us/app/magic-hour/id482426006?uo=4</a>
**App Version:** 1.6.3
**Seller:** Linda Byrket
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/elfinda-apps/id482426309?uo=4">© elfinda apps</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/6b/31/46/6b3146a9-38a7-33ae-2597-968101782177/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78290602-3cf23480-7524-11ea-9e9f-1d2c7f3e774c.png)

**Comment by kayjeiem** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2732955/78074649-c4686800-73ab-11ea-8255-2272b0d7a08a.png)

Source

![](https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/6b/31/46/6b3146a9-38a7-33ae-2597-968101782177/source/1024x1024bb.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78290602-3cf23480-7524-11ea-9e9f-1d2c7f3e774c.png)
https://user-images.githubusercontent.com/2068130/78290602-3cf23480-7524-11ea-9e9f-1d2c7f3e774c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/78290641-4da2aa80-7524-11ea-8d80-c2ae4bd4138c.png
