### ISSUE TITLE
Brave Private Web Browser

### ISSUE THREAD

**Issue by kayjeiem** [glasklart/hd#10772]
**App Name:** Brave Private Web Browser
**Bundle ID:** com.brave.ios.browser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1052879175">1052879175</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/brave-private-web-browser/id1052879175?uo=4">https://apps.apple.com/us/app/brave-private-web-browser/id1052879175?uo=4</a>
**App Version:** 1.15
**Seller:** Brave Software, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/brave-software/id1052874328?uo=4">© Brave Software</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/ea/c4/ef/eac4ef2e-fa1e-3bad-188c-1677bc84d9f1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78288113-ad4b8680-7521-11ea-989e-674ef4745fdf.png)

**Comment by kayjeiem** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2732955/78073198-18258200-73a9-11ea-86c3-955b774dcaf7.png)

Source
![Brave_1024x1024bb](https://user-images.githubusercontent.com/2732955/78073213-207dbd00-73a9-11ea-9baf-83e4a3e65dba.png)

**Comment by dreamnet** [comment]
Good, but too small...
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78288113-ad4b8680-7521-11ea-989e-674ef4745fdf.png)
https://user-images.githubusercontent.com/2068130/78288113-ad4b8680-7521-11ea-989e-674ef4745fdf.png
--- --- 
Source:
https://user-images.githubusercontent.com/2068130/78288394-c3594700-7521-11ea-9919-e299b827e23b.png
