### ISSUE TITLE
NoiPA - MEF

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#10775]
**App Name:** NoiPA - MEF
**Bundle ID:** it.mef.noipa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1449271674">1449271674</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/noipa-mef/id1449271674?uo=4">https://apps.apple.com/us/app/noipa-mef/id1449271674?uo=4</a>
**App Version:** 2.4
**Seller:** Ministero dell'Economia e Finanze
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ministero-delleconomia-e-finanze/id1130864243?uo=4">© Ministero dell'Economia e Finanze</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/a0/84/6b/a0846ba9-1b5e-dfaf-f139-84faab2d39bc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78793674-0482a880-79b3-11ea-9362-43bbadafb1cb.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78793674-0482a880-79b3-11ea-9362-43bbadafb1cb.png)
https://user-images.githubusercontent.com/2068130/78793674-0482a880-79b3-11ea-9362-43bbadafb1cb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/78793718-15331e80-79b3-11ea-9420-0343533c2993.png
