### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10776]
**App Name:** GitHub
**Bundle ID:** com.github.stormbreaker.prod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1477376905">1477376905</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/github/id1477376905?uo=4">https://apps.apple.com/us/app/github/id1477376905?uo=4</a>
**App Version:** 1.0.1
**Seller:** GitHub
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/github/id429758986?uo=4">© GitHub</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/d4/75/68/d475684a-835d-483e-5981-738fdd8a7423/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78794599-42340100-79b4-11ea-8313-182b7b22e25a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78794599-42340100-79b4-11ea-8313-182b7b22e25a.png)
https://user-images.githubusercontent.com/2068130/78794599-42340100-79b4-11ea-8313-182b7b22e25a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/78794651-511ab380-79b4-11ea-9915-39718733f128.png
