### ISSUE TITLE
Bible App by Olive Tree

### ISSUE THREAD

**Issue by kayjeiem** [glasklart/hd#10770]
**App Name:** Bible App by Olive Tree
**Bundle ID:** com.olivetree.BR-Free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=332615624">332615624</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bible-app-by-olive-tree/id332615624?uo=4">https://apps.apple.com/us/app/bible-app-by-olive-tree/id332615624?uo=4</a>
**App Version:** 7.7.5
**Seller:** HarperCollins Christian Publishing, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/harpercollins-christian-publishing-inc/id444535393?uo=4">© HarperCollins Christian Publishing, Inc.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/11/ca/75/11ca7508-4c0b-099c-7f74-59237f6b302b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78284909-5b563100-7520-11ea-9350-ca80330f2c51.png)

**Comment by kayjeiem** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2732955/78067087-ca0b8100-739e-11ea-9e25-f54528230752.png)


Source 
![BibleStudy_1024x1024bb](https://user-images.githubusercontent.com/2732955/78066889-7305ac00-739e-11ea-99a8-de3dc7c8fac6.png)

**Comment by dreamnet** [comment]
@kayjeiem Too small - Check [this](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon) out.
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78284909-5b563100-7520-11ea-9350-ca80330f2c51.png)
https://user-images.githubusercontent.com/2068130/78284909-5b563100-7520-11ea-9350-ca80330f2c51.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/78284943-6a3ce380-7520-11ea-8129-a8f16d19da8f.png
