### ISSUE TITLE
Ligonier Ministries

### ISSUE THREAD

**Issue by kayjeiem** [glasklart/hd#10771]
**App Name:** Ligonier Ministries
**Bundle ID:** com.thechurchapp.Ligonier
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=371390152">371390152</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ligonier-ministries/id371390152?uo=4">https://apps.apple.com/us/app/ligonier-ministries/id371390152?uo=4</a>
**App Version:** 5.0.4
**Seller:** Ligonier
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ligonier/id537706475?uo=4">© Ligonier</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/56/c6/0c/56c60ce0-bbe8-e83b-fc27-c743dae2dbff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78285969-0bc43500-7521-11ea-85df-2f16bc0f67c3.png)

**Comment by kayjeiem** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2732955/78072698-3939a300-73a8-11ea-93a2-1c5b40f26c9d.png)


Source
![1024x1024bb](https://user-images.githubusercontent.com/2732955/78072725-42c30b00-73a8-11ea-8a2c-565a0c845f45.png)

**Comment by dreamnet** [comment]
@kayjeiem Too small - and we need the source file.
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78285969-0bc43500-7521-11ea-85df-2f16bc0f67c3.png)
https://user-images.githubusercontent.com/2068130/78285969-0bc43500-7521-11ea-85df-2f16bc0f67c3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/78286165-1aaae780-7521-11ea-92d3-14ed768735ed.png
