### ISSUE TITLE
WordMap: Interactive Thesaurus

### ISSUE THREAD

**Issue by kayjeiem** [glasklart/hd#10773]
**App Name:** WordMap: Interactive Thesaurus
**Bundle ID:** com.alextataurov.wordmap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1448580560">1448580560</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wordmap-interactive-thesaurus/id1448580560?uo=4">https://apps.apple.com/us/app/wordmap-interactive-thesaurus/id1448580560?uo=4</a>
**App Version:** 1.2.2
**Seller:** Alex Tataurov
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/alex-tataurov/id463319538?uo=4">© Alex Tataurov</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/8a/ef/c7/8aefc738-e419-fb5c-d08b-518a43e92102/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78290231-b3426700-7523-11ea-8ccd-54ea597b38e4.png)

**Comment by kayjeiem** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2732955/78073702-0bedf480-73aa-11ea-81b7-e1045a360f64.png)

Source
![Word_Map_1024x1024bb](https://user-images.githubusercontent.com/2732955/78073712-14dec600-73aa-11ea-9c27-720005aac969.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/78290231-b3426700-7523-11ea-8ccd-54ea597b38e4.png)
https://user-images.githubusercontent.com/2068130/78290231-b3426700-7523-11ea-8ccd-54ea597b38e4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/78290259-c3f2dd00-7523-11ea-8e7d-1a05e8ba3906.png
