### ISSUE TITLE
Corona-Datenspende

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10789]
**App Name:** Corona-Datenspende
**Bundle ID:** de.rki.coronadatenspende
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1504705422">1504705422</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/corona-datenspende/id1504705422?uo=4">https://apps.apple.com/de/app/corona-datenspende/id1504705422?uo=4</a>
**App Version:** 1.0.3
**Seller:** Robert Koch-Institut
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/robert-koch-institut/id1308350896?uo=4">© Robert Koch-Institut</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/1a/02/a5/1a02a5c0-b000-56fc-0d15-640eca605f14/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79053409-68b89d00-7c3d-11ea-83cc-082c10e24fe7.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79053409-68b89d00-7c3d-11ea-83cc-082c10e24fe7.png)
https://user-images.githubusercontent.com/2068130/79053409-68b89d00-7c3d-11ea-83cc-082c10e24fe7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79053415-779f4f80-7c3d-11ea-8598-2e375f4a99b1.png
