### ISSUE TITLE
LUV-Share

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10786]
**App Name:** LUV-Share
**Bundle ID:** com.luv-idea.app1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1072251659">1072251659</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/luv-share/id1072251659?uo=4">https://apps.apple.com/us/app/luv-share/id1072251659?uo=4</a>
**App Version:** 2.4
**Seller:** Shenzhen JIUYIDA Electronics Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shenzhen-jiuyida-electronics-co-ltd/id1441269277?uo=4">© Shenzhen JIUYIDA Electronics Co., Ltd.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/f3/95/5c/f3955cd2-53c0-ce28-1ddb-fb0a4c43fa10/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79053093-fa72db00-7c3a-11ea-87c7-32e4bf8c9dc4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79053093-fa72db00-7c3a-11ea-87c7-32e4bf8c9dc4.png)
https://user-images.githubusercontent.com/2068130/79053093-fa72db00-7c3a-11ea-87c7-32e4bf8c9dc4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79053103-09f22400-7c3b-11ea-97eb-56906b0993f3.png
