### ISSUE TITLE
Knighthood

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10780]
**App Name:** Knighthood
**Bundle ID:** com.midasplayer.apps.knightsrage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1458762050">1458762050</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/knighthood/id1458762050?uo=4">https://apps.apple.com/us/app/knighthood/id1458762050?uo=4</a>
**App Version:** 1.1.6
**Seller:** King.com Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/king/id526656015?uo=4">© King</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/ea/63/6a/ea636ad6-64f2-af76-52bd-03ee8accdb5e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79051610-59335700-7c31-11ea-8499-7f9b3e46d196.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/78963105-04220480-7abc-11ea-97a4-306c25c63052.png)
https://user-images.githubusercontent.com/44279267/78963105-04220480-7abc-11ea-97a4-306c25c63052.png

Data Source:
https://user-images.githubusercontent.com/44279267/78963204-6418ab00-7abc-11ea-99b2-4b79a29f318c.png

**Comment by dreamnet** [comment]
?
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79051610-59335700-7c31-11ea-8499-7f9b3e46d196.png)
https://user-images.githubusercontent.com/2068130/79051610-59335700-7c31-11ea-8499-7f9b3e46d196.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79051630-6b14fa00-7c31-11ea-9305-36c38ae247e0.png

**Comment by tlunmp** [comment]
look better dreamnet :D we can use that
