### ISSUE TITLE
Stop - Categories Word Game

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10784]
**App Name:** Stop - Categories Word Game
**Bundle ID:** com.fanatee.stop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=687877464">687877464</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stop-categories-word-game/id687877464?uo=4">https://apps.apple.com/us/app/stop-categories-word-game/id687877464?uo=4</a>
**App Version:** 3.13.4
**Seller:** Fanatee, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fanatee/id1231085076?uo=4">© Fanatee</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/d6/32/ba/d632baf9-bcb9-23d9-824a-d86074438736/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79052351-2cce0980-7c36-11ea-8c20-d4bea6a0af47.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/79032299-02fbe080-7b6b-11ea-8a0a-bd652d2625ec.png)
https://user-images.githubusercontent.com/44279267/79032299-02fbe080-7b6b-11ea-8a0a-bd652d2625ec.png

Data Source:
![stop](https://user-images.githubusercontent.com/44279267/79032302-042d0d80-7b6b-11ea-9df3-cf4c3af74c7e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79052351-2cce0980-7c36-11ea-8c20-d4bea6a0af47.png)
https://user-images.githubusercontent.com/2068130/79052351-2cce0980-7c36-11ea-8c20-d4bea6a0af47.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79052358-40797000-7c36-11ea-8394-9cb58d94b906.png
