### ISSUE TITLE
cewe photoworld

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10787]
**App Name:** cewe photoworld
**Bundle ID:** com.cewecolor.cewefotowelt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=583713833">583713833</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cewe-photoworld/id583713833?uo=4">https://apps.apple.com/us/app/cewe-photoworld/id583713833?uo=4</a>
**App Version:** 4.6.1
**Seller:** CEWE Stiftung & Co. KGaA
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cewe-stiftung-co-kgaa/id397728813?uo=4">© CEWE Stiftung & Co. KGaA</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/18/7b/e2/187be21d-0c29-2736-fbd4-1eb682f05f94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79053611-fea0f780-7c3e-11ea-8032-c8701460ce15.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79053611-fea0f780-7c3e-11ea-8032-c8701460ce15.png)
https://user-images.githubusercontent.com/2068130/79053611-fea0f780-7c3e-11ea-8032-c8701460ce15.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79053623-111b3100-7c3f-11ea-9ba7-452bf84c8e66.png
