### ISSUE TITLE
Scriptable

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10783]
**App Name:** Scriptable
**Bundle ID:** dk.simonbs.Scriptable
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1405459188">1405459188</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/scriptable/id1405459188?uo=4">https://apps.apple.com/us/app/scriptable/id1405459188?uo=4</a>
**App Version:** 1.4.9
**Seller:** Simon Stovring
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/simon-b-st%C3%B8vring/id423532907?uo=4">© Simon B. Støvring</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/2d/0c/d1/2d0cd1ad-cffa-b3d6-2796-f9bbadd5fa85/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79052180-f643bf00-7c34-11ea-952f-5c1b48ed1800.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/78965517-e3a97880-7ac2-11ea-89e9-251d95949836.png)
https://user-images.githubusercontent.com/44279267/78965517-e3a97880-7ac2-11ea-89e9-251d95949836.png

Data Source:
https://user-images.githubusercontent.com/44279267/78965522-e5733c00-7ac2-11ea-8ebb-d6bbf1924425.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79052180-f643bf00-7c34-11ea-952f-5c1b48ed1800.png)
https://user-images.githubusercontent.com/2068130/79052180-f643bf00-7c34-11ea-952f-5c1b48ed1800.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79052196-107d9d00-7c35-11ea-976a-5488b189e5b4.png
