### ISSUE TITLE
Fitness - build your body

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10788]
**App Name:** Fitness - build your body
**Bundle ID:** com.csdz.fitness
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1317677571">1317677571</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fitness-build-your-body/id1317677571?uo=4">https://apps.apple.com/us/app/fitness-build-your-body/id1317677571?uo=4</a>
**App Version:** 1.0.6
**Seller:** Yue Jin
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yue-jin/id1055315945?uo=4">© Yue Jin</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/d6/a0/a4/d6a0a4ba-e575-94c7-f34a-238a83e9d69d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79053219-fe532d00-7c3b-11ea-9ce9-545d4f3dd7ef.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79053219-fe532d00-7c3b-11ea-9ce9-545d4f3dd7ef.png)
https://user-images.githubusercontent.com/2068130/79053219-fe532d00-7c3b-11ea-9ce9-545d4f3dd7ef.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79053231-0f03a300-7c3c-11ea-9b77-86035964b9f2.png
