### ISSUE TITLE
Morse Code Reader and Decoder

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10782]
**App Name:** Morse Code Reader and Decoder
**Bundle ID:** everydayapps.morsecode.master
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1372696136">1372696136</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/morse-code-reader-and-decoder/id1372696136?uo=4">https://apps.apple.com/us/app/morse-code-reader-and-decoder/id1372696136?uo=4</a>
**App Version:** 1.5
**Seller:** Ivan Antic
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ivan-antic/id1367134411?uo=4">© Ivan Antic</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/17/f4/48/17f448aa-17cc-a70f-774b-1827a78146c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79051924-3f930f00-7c33-11ea-86c9-00d1e2215a6d.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/78964838-e905c380-7ac0-11ea-9fdf-bce4cff7cabc.png)
https://user-images.githubusercontent.com/44279267/78964838-e905c380-7ac0-11ea-9fdf-bce4cff7cabc.png

Data Source:
https://user-images.githubusercontent.com/44279267/78964853-f58a1c00-7ac0-11ea-9ad3-ee16710b167c.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79051924-3f930f00-7c33-11ea-86c9-00d1e2215a6d.png)
https://user-images.githubusercontent.com/2068130/79051924-3f930f00-7c33-11ea-86c9-00d1e2215a6d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79051934-4e79c180-7c33-11ea-8919-67cd22c71e82.png
