### ISSUE TITLE
Price Alert for Amazon

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10785]
**App Name:** Price Alert for Amazon
**Bundle ID:** net.amazonprices.AmazonPrices
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035665126">1035665126</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/price-alert-for-amazon/id1035665126?uo=4">https://apps.apple.com/us/app/price-alert-for-amazon/id1035665126?uo=4</a>
**App Version:** 2.4.5
**Seller:** Alexandros Koutsonasios
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/alexandros-koutsonasios/id1035665125?uo=4">© Alexandros Koutsonasios</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/e1/b3/81/e1b3813d-9995-c8d4-d73d-0936f271412e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79052934-11fd9400-7c3a-11ea-8b89-5f12e9147678.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79052934-11fd9400-7c3a-11ea-8b89-5f12e9147678.png)
https://user-images.githubusercontent.com/2068130/79052934-11fd9400-7c3a-11ea-8b89-5f12e9147678.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79052942-20e44680-7c3a-11ea-9c4b-d5b65c20d05a.png
