### ISSUE TITLE
Mercari: The Selling App

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10781]
**App Name:** Mercari: The Selling App
**Bundle ID:** com.mercariapp.ios.mercari
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=896130944">896130944</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mercari-the-selling-app/id896130944?uo=4">https://apps.apple.com/us/app/mercari-the-selling-app/id896130944?uo=4</a>
**App Version:** 6.89.0
**Seller:** Mercari, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mercari-inc/id667861052?uo=4">© Mercari, Inc.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/bf/54/42/bf544224-ecb7-c8da-0f2d-a95362789631/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79051753-3eadad80-7c32-11ea-8262-2822529f036b.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/78964238-25d0bb00-7abf-11ea-98b9-f8b1aeb4f614.png)
https://user-images.githubusercontent.com/44279267/78964238-25d0bb00-7abf-11ea-98b9-f8b1aeb4f614.png

Data Source:
https://user-images.githubusercontent.com/44279267/78964256-32551380-7abf-11ea-9669-bfed20dcb4bd.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79051753-3eadad80-7c32-11ea-8262-2822529f036b.png)
https://user-images.githubusercontent.com/2068130/79051753-3eadad80-7c32-11ea-8262-2822529f036b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79051761-4ec58d00-7c32-11ea-8026-71f905b6eca9.png
