### ISSUE TITLE
Myndlift

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10793]
**App Name:** Myndlift
**Bundle ID:** com.myndlift.myndlift
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1448710522">1448710522</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myndlift/id1448710522?uo=4">https://apps.apple.com/us/app/myndlift/id1448710522?uo=4</a>
**App Version:** 1.17
**Seller:** Myndlift Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/myndlift/id1448710521?uo=4">© Myndlift</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/61/0c/84/610c84ec-ae48-17d4-8ae3-1a86c23e3c32/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632125-98940300-815d-11ea-8789-1446468dff1f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632125-98940300-815d-11ea-8789-1446468dff1f.png)
https://user-images.githubusercontent.com/2068130/79632125-98940300-815d-11ea-8789-1446468dff1f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79632137-a9447900-815d-11ea-8bd7-5d5cb4ccc931.png
