### ISSUE TITLE
LS&Co. Partner Playbook

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10790]
**App Name:** LS&Co. Partner Playbook
**Bundle ID:** com.levi.partnerplaybook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1437327754">1437327754</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ls-co-partner-playbook/id1437327754?uo=4">https://apps.apple.com/us/app/ls-co-partner-playbook/id1437327754?uo=4</a>
**App Version:** 1.0.0
**Seller:** Levi Strauss & Co.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/levi-strauss-co/id445404948?uo=4">© LEVI STRAUSS & CO.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/9c/73/e5/9c73e58d-de3c-3bad-ff3b-98bb02a61f39/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79630880-523aa600-8155-11ea-91b8-e082579bfe15.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/79288263-deb24380-7e8b-11ea-9fa8-0590cf3c0e6f.png)
https://user-images.githubusercontent.com/44279267/79288263-deb24380-7e8b-11ea-9fa8-0590cf3c0e6f.png

Data Source:
https://user-images.githubusercontent.com/44279267/79288289-e83bab80-7e8b-11ea-97b6-03597d64a42d.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79630880-523aa600-8155-11ea-91b8-e082579bfe15.png)
https://user-images.githubusercontent.com/2068130/79630880-523aa600-8155-11ea-91b8-e082579bfe15.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79630891-641c4900-8155-11ea-8db1-03cf7f3ead8c.png
