### ISSUE TITLE
Scanbot Pro

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10796]
**App Name:** Scanbot Pro
**Bundle ID:** net.doo.scanbot.vpp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1007355333">1007355333</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/scanbot-pro/id1007355333?uo=4">https://apps.apple.com/us/app/scanbot-pro/id1007355333?uo=4</a>
**App Version:** 9.3.2
**Seller:** doo GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/doo-gmbh/id454738556?uo=4">© doo GmbH</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/ea/85/b4/ea85b418-e52f-963a-c22b-290687d6204e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632447-769b8000-815f-11ea-9ce9-58e8ef8a6932.png)

**Comment by tlunmp** [comment]
FYI this is not the same as https://github.com/glasklart/hd/issues/4261 as this icon has pro.

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/79495784-c3117f00-7fea-11ea-8cf1-c729518f955a.png)

https://user-images.githubusercontent.com/44279267/79495784-c3117f00-7fea-11ea-8cf1-c729518f955a.png)

Data Source:
https://user-images.githubusercontent.com/44279267/79495792-c442ac00-7fea-11ea-84fc-91b04867ce6f.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632447-769b8000-815f-11ea-9ce9-58e8ef8a6932.png)
https://user-images.githubusercontent.com/2068130/79632447-769b8000-815f-11ea-9ce9-58e8ef8a6932.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79632453-86b35f80-815f-11ea-88d7-664921d22afb.png
