### ISSUE TITLE
LingoDeer - Learn Languages

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10799]
**App Name:** LingoDeer - Learn Languages
**Bundle ID:** com.lingodeer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1261193709">1261193709</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/lingodeer-learn-languages/id1261193709?uo=4">https://apps.apple.com/us/app/lingodeer-learn-languages/id1261193709?uo=4</a>
**App Version:** 2.5.20
**Seller:** LingoDeer Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lingodeer-co-ltd/id1261193708?uo=4">© LingoDeer Co, Ltd.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/58/96/7b/58967b0b-4d15-9b9d-7eab-0f913dfcc041/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/80410703-542a0500-88cb-11ea-84eb-ad021987d149.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/79680312-febb6d00-81d3-11ea-9f6a-8642cae730f6.png)
https://user-images.githubusercontent.com/44279267/79680312-febb6d00-81d3-11ea-9f6a-8642cae730f6.png

Data Source:
https://user-images.githubusercontent.com/44279267/79680313-ffec9a00-81d3-11ea-95d3-efddbcc8f4d2.png

**Comment by dreamnet** [comment]
@tlunmp Your source is too small (the image should go to the edges in the source, just check my source to see the difference), else very good!
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/80410703-542a0500-88cb-11ea-84eb-ad021987d149.png)
https://user-images.githubusercontent.com/2068130/80410703-542a0500-88cb-11ea-84eb-ad021987d149.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/80410755-64da7b00-88cb-11ea-9043-e9307e3c9df1.png

**Comment by tlunmp** [comment]
@dreamnet  noted. Thanks for correcting my source. I will make it better. Next time :)
