### ISSUE TITLE
Remind Me Faster

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10798]
**App Name:** Remind Me Faster
**Bundle ID:** chojubo.addReminder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=985555908">985555908</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/remind-me-faster/id985555908?uo=4">https://apps.apple.com/us/app/remind-me-faster/id985555908?uo=4</a>
**App Version:** 2.1
**Seller:** Nick Leith
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nick-leith/id978034931?uo=4">© Nick Leith</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/1e/07/0c/1e070c89-f2cc-abf5-c3b4-a17655975457/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632638-e52d0d80-8160-11ea-829d-b8f939996ed8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632638-e52d0d80-8160-11ea-829d-b8f939996ed8.png)
https://user-images.githubusercontent.com/2068130/79632638-e52d0d80-8160-11ea-829d-b8f939996ed8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79632645-f6761a00-8160-11ea-9e5a-2733117c496b.png
