### ISSUE TITLE
ABOUT YOU Mode Online Shop

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10795]
**App Name:** ABOUT YOU Mode Online Shop
**Bundle ID:** de.aboutyou.mobile.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=985244644">985244644</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/about-you-mode-online-shop/id985244644?uo=4">https://apps.apple.com/de/app/about-you-mode-online-shop/id985244644?uo=4</a>
**App Version:** 6.5.1
**Seller:** ABOUT YOU GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/about-you-gmbh/id932416131?uo=4">© ABOUT YOU GmbH</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/77/ed/20/77ed2045-2a92-7388-9fe7-7df7b6aa3284/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632337-de050000-815e-11ea-9f84-9355b155bd24.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632337-de050000-815e-11ea-9f84-9355b155bd24.png)
https://user-images.githubusercontent.com/2068130/79632337-de050000-815e-11ea-9f84-9355b155bd24.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79632361-ec531c00-815e-11ea-9a7d-4399072274ef.png
