### ISSUE TITLE
Ameren Mobile

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10792]
**App Name:** Ameren Mobile
**Bundle ID:** com.ameren.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=874437332">874437332</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ameren-mobile/id874437332?uo=4">https://apps.apple.com/us/app/ameren-mobile/id874437332?uo=4</a>
**App Version:** 1.1.40
**Seller:** Ameren Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ameren-corporation/id874437335?uo=4">© Ameren Corporation</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/62/ac/7b/62ac7be5-c3a2-42a4-4304-8227a0929440/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79631125-4223c600-8157-11ea-8b84-27e692a073b0.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/79289599-5766cf00-7e8f-11ea-86cf-313fb5f752ee.png)
https://user-images.githubusercontent.com/44279267/79289599-5766cf00-7e8f-11ea-86cf-313fb5f752ee.png

Data Source:
https://user-images.githubusercontent.com/44279267/79289602-59309280-7e8f-11ea-9ee6-18eedba8e634.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79631125-4223c600-8157-11ea-8b84-27e692a073b0.png)
https://user-images.githubusercontent.com/2068130/79631125-4223c600-8157-11ea-8b84-27e692a073b0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79631133-51a30f00-8157-11ea-8d04-95a59b2c2ac6.png
