### ISSUE TITLE
Apple COVID-19

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10791]
**App Name:** Apple COVID-19
**Bundle ID:** com.apple.Symptom-Assessment.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1504132184">1504132184</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/apple-covid-19/id1504132184?uo=4">https://apps.apple.com/us/app/apple-covid-19/id1504132184?uo=4</a>
**App Version:** 2.0
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/4e/97/ae/4e97aea6-c41e-afa6-5c3a-5153f4941c64/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79630993-2966e080-8156-11ea-8dd7-f60e85393f29.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/79288887-8e3be580-7e8d-11ea-9326-13748e29c876.png)
https://user-images.githubusercontent.com/44279267/79288887-8e3be580-7e8d-11ea-9326-13748e29c876.png

Data Source:
https://user-images.githubusercontent.com/44279267/79288898-94ca5d00-7e8d-11ea-84ad-a034f25b7a67.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79630993-2966e080-8156-11ea-8dd7-f60e85393f29.png)
https://user-images.githubusercontent.com/2068130/79630993-2966e080-8156-11ea-8dd7-f60e85393f29.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79631011-3be11a00-8156-11ea-8a1c-4671b89065c1.png
