### ISSUE TITLE
Jitsi Meet

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#10794]
**App Name:** Jitsi Meet
**Bundle ID:** com.atlassian.JitsiMeet.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1165103905">1165103905</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/jitsi-meet/id1165103905?uo=4">https://apps.apple.com/us/app/jitsi-meet/id1165103905?uo=4</a>
**App Version:** 20.2.1
**Seller:** 8x8, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/8x8-inc/id348177451?uo=4">© 8x8, Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/9f/0f/8f/9f0f8fff-b6de-55b7-73a8-4376b7159cfb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632199-22dc6700-815e-11ea-974b-89d9dca7a98e.png)

**Comment by tlunmp** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/79493542-3d400480-7fe7-11ea-81bb-f45ab8049c6f.png)

https://user-images.githubusercontent.com/44279267/79493542-3d400480-7fe7-11ea-81bb-f45ab8049c6f.png

Data Source:
https://user-images.githubusercontent.com/44279267/79493546-3f09c800-7fe7-11ea-84b9-3e563f09b00f.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632199-22dc6700-815e-11ea-974b-89d9dca7a98e.png)
https://user-images.githubusercontent.com/2068130/79632199-22dc6700-815e-11ea-974b-89d9dca7a98e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79632205-338cdd00-815e-11ea-98aa-d9eb182ba763.png
