### ISSUE TITLE
soTV, programme TV

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#108]
**App Name:** soTV, programme TV
**Bundle ID:** com.degrange.soTV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300116772">300116772</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sotv-programme-tv/id300116772?mt=8&uo=4">https://itunes.apple.com/us/app/sotv-programme-tv/id300116772?mt=8&uo=4</a>
**App Version:** 8.8.1
**Seller:** Eric Degrange
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/eric-degrange/id288483454?uo=4">© Eric Degrange</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/85/5f/dd/855fdd09-216e-52b3-5fda-636d0bb4bc3e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692621-afe095cc-c71b-11e7-9d53-65f84512e9fa.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692621-afe095cc-c71b-11e7-9d53-65f84512e9fa.png)
https://user-images.githubusercontent.com/2068130/32692621-afe095cc-c71b-11e7-9d53-65f84512e9fa.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692628-bf000a24-c71b-11e7-9dbd-724f9d5014cb.png
