### ISSUE TITLE
The Daily Camera

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10808]
**App Name:** The Daily Camera
**Bundle ID:** com.spreednews.digitalfirstmedia-thedailycamera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=509007030">509007030</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/the-daily-camera/id509007030?uo=4">https://apps.apple.com/us/app/the-daily-camera/id509007030?uo=4</a>
**App Version:** 7.4.5
**Seller:** Prairie Mountain Publishing
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/prairie-mountain-publishing/id405275095?uo=4">© Prairie Mountain Publishing</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/72/5b/3d/725b3dbf-94d4-091a-d52c-e4cedbc06802/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83347664-b93ba500-a326-11ea-90f2-cbc2aa87c9c8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83347664-b93ba500-a326-11ea-90f2-cbc2aa87c9c8.png)
https://user-images.githubusercontent.com/2068130/83347664-b93ba500-a326-11ea-90f2-cbc2aa87c9c8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83347674-c9538480-a326-11ea-9e74-e01b2972d60d.png
