### ISSUE TITLE
Noodles and Company

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10805]
**App Name:** Noodles and Company
**Bundle ID:** com.olo.noodles
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=656377555">656377555</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/noodles-and-company/id656377555?uo=4">https://apps.apple.com/us/app/noodles-and-company/id656377555?uo=4</a>
**App Version:** 6.0.0
**Seller:** Noodles & Company
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/noodles-company/id1367992671?uo=4">© Noodles & Company</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/d7/aa/15/d7aa1543-e5a9-64b0-d4f0-0848946a338e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/81255583-4fcdbc80-902e-11ea-82d7-087947a02e0b.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/81255583-4fcdbc80-902e-11ea-82d7-087947a02e0b.png)
https://user-images.githubusercontent.com/2068130/81255583-4fcdbc80-902e-11ea-82d7-087947a02e0b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/81255609-61af5f80-902e-11ea-9d85-4248ade463bd.png
