### ISSUE TITLE
myAI®

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10806]
**App Name:** myAI®
**Bundle ID:** com.aquaillumination.aidirector
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=731463335">731463335</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myai/id731463335?uo=4">https://apps.apple.com/us/app/myai/id731463335?uo=4</a>
**App Version:** 3.7
**Seller:** C2 Development, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/c2-development-inc/id731463338?uo=4">© C2 Development, Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/df/e4/41/dfe44182-97e1-eb86-608d-431f1265ec17/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/82534654-c77b0b80-9b45-11ea-8dba-d7172bdca617.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/82534654-c77b0b80-9b45-11ea-8dba-d7172bdca617.png)
https://user-images.githubusercontent.com/2068130/82534654-c77b0b80-9b45-11ea-8dba-d7172bdca617.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/82534704-dc579f00-9b45-11ea-8bc7-11b437c123c7.png
