### ISSUE TITLE
Finlocker PFM

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10800]
**App Name:** Finlocker PFM
**Bundle ID:** com.finlocker.finlocker-pfm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1435921445">1435921445</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/finlocker-pfm/id1435921445?uo=4">https://apps.apple.com/us/app/finlocker-pfm/id1435921445?uo=4</a>
**App Version:** 2.06
**Seller:** FinLocker LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/finlocker-llc/id1357188723?uo=4">© Finlocker LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/a5/92/92/a5929243-9fc2-a69e-9eee-2ace61199a62/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/80412102-97857300-88cd-11ea-9d16-8553eaf9e6bb.png)

**Comment by tlunmp** [comment]
This is my real work app.  :D

**Comment by dreamnet** [comment]
@tlunmp Icon is fine!
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/80412102-97857300-88cd-11ea-9d16-8553eaf9e6bb.png)
https://user-images.githubusercontent.com/2068130/80412102-97857300-88cd-11ea-9d16-8553eaf9e6bb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/80412138-a9671600-88cd-11ea-985c-0e31e719eb16.png
