### ISSUE TITLE
Meine S-Direkt

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10809]
**App Name:** Meine S-Direkt
**Bundle ID:** de.sdirekt.carriertech.kundenportal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1462034058">1462034058</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/meine-s-direkt/id1462034058?uo=4">https://apps.apple.com/de/app/meine-s-direkt/id1462034058?uo=4</a>
**App Version:** 1.0.13
**Seller:** Sparkassen DirektVersicherung AG
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/sparkassen-direktversicherung-ag/id449592241?uo=4">© Sparkassen DirektVersicherung AG</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/f4/7d/52/f47d5262-ec7d-e575-ba50-2c2efa4438ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83347728-37984700-a327-11ea-9a5c-952be974d10c.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83347728-37984700-a327-11ea-9a5c-952be974d10c.png)
https://user-images.githubusercontent.com/2068130/83347728-37984700-a327-11ea-9a5c-952be974d10c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83347735-47b02680-a327-11ea-8859-ac51ecea9950.png
