### ISSUE TITLE
ROKC

### ISSUE THREAD

**Issue by tlunmp** [glasklart/hd#10801]
**App Name:** ROKC
**Bundle ID:** com.xutzgard.rokcompanion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1495745960">1495745960</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/rokc/id1495745960?uo=4">https://apps.apple.com/us/app/rokc/id1495745960?uo=4</a>
**App Version:** 3.3.3
**Seller:** Ted Anthony Uy
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ted-anthony-uy/id1495745959?uo=4">© Ted Anthony Uy</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/8f/70/74/8f707449-cada-ee07-7144-37425fce991a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/80416137-eb935600-88d3-11ea-90e2-aadcd7c3bccc.png)

**Comment by tlunmp** [comment]
App Developed by me 
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/44279267/79680891-5fe63f00-81da-11ea-8df5-1c8670345f4c.png)
https://user-images.githubusercontent.com/44279267/79680891-5fe63f00-81da-11ea-8df5-1c8670345f4c.png

Data Source:
https://user-images.githubusercontent.com/44279267/79680892-62e12f80-81da-11ea-876d-6274d84c7291.png

**Comment by dreamnet** [comment]
@tlunmp 👍 
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/80416137-eb935600-88d3-11ea-90e2-aadcd7c3bccc.png)
https://user-images.githubusercontent.com/2068130/80416137-eb935600-88d3-11ea-90e2-aadcd7c3bccc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/80416179-fbab3580-88d3-11ea-8089-bde6e7f72afc.png
