### ISSUE TITLE
Quickgets Geo: geodata widgets

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10803]
**App Name:** Quickgets Geo: geodata widgets
**Bundle ID:** macoa.self.Quickgets-Geo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916870034">916870034</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/quickgets-geo-geodata-widgets/id916870034?uo=4">https://apps.apple.com/us/app/quickgets-geo-geodata-widgets/id916870034?uo=4</a>
**App Version:** 3.0.9
**Seller:** Alvaro Maroto Conde
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/alvaro-maroto-conde/id707767270?uo=4">© Alvaro Maroto Conde</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/2e/67/98/2e67988c-71ec-4254-3921-2bda50f235f1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/81196592-89b3aa00-8fbf-11ea-9a7d-ca4b763026b4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/81196592-89b3aa00-8fbf-11ea-9a7d-ca4b763026b4.png)
https://user-images.githubusercontent.com/2068130/81196592-89b3aa00-8fbf-11ea-9a7d-ca4b763026b4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/81196650-99cb8980-8fbf-11ea-8c4d-4f181a475241.png
