### ISSUE TITLE
YI IoT

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10807]
**App Name:** YI IoT
**Bundle ID:** com.yunyi.smartcamera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1375812275">1375812275</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/yi-iot/id1375812275?uo=4">https://apps.apple.com/us/app/yi-iot/id1375812275?uo=4</a>
**App Version:** 1.6.2
**Seller:** YI Technologies, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yi-technologies-inc/id1375812274?uo=4">© YI Technologies, Inc.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/0b/ad/c0/0badc063-d5ad-b40a-8bb2-c307a1a20344/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83348458-23574880-a32d-11ea-8510-667ec4523cf9.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83348458-23574880-a32d-11ea-8510-667ec4523cf9.png)
https://user-images.githubusercontent.com/2068130/83348458-23574880-a32d-11ea-8510-667ec4523cf9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83348469-32d69180-a32d-11ea-8cb0-3a78886d7026.png
