### ISSUE TITLE
AppWish - Simple wishlist

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10802]
**App Name:** AppWish - Simple wishlist
**Bundle ID:** FN.WishAppList
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1291909819">1291909819</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/appwish-simple-wishlist/id1291909819?uo=4">https://apps.apple.com/us/app/appwish-simple-wishlist/id1291909819?uo=4</a>
**App Version:** 2.2.1
**Seller:** Filip Nemecek
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/filip-nemecek/id1291909818?uo=4">© Filip Nemecek</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/2b/7d/d2/2b7dd2b0-0f6f-e4e8-eb9e-7e803acbeb26/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/82207300-e3926900-9909-11ea-8c5b-67831d6a5b73.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/82207300-e3926900-9909-11ea-8c5b-67831d6a5b73.png)
https://user-images.githubusercontent.com/2068130/82207300-e3926900-9909-11ea-8c5b-67831d6a5b73.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/82207333-f3aa4880-9909-11ea-90b5-c63ef4c76b5b.png
