### ISSUE TITLE
Photo Collage – Frame Editor and Perfect Camera

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10817]
**App Name:** Photo Collage – Frame Editor and Perfect Camera
**Bundle ID:** com.flyman.picframepro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=508668322">508668322</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/photo-collage-frame-editor-and-perfect-camera/id508668322?uo=4">https://apps.apple.com/us/app/photo-collage-frame-editor-and-perfect-camera/id508668322?uo=4</a>
**App Version:** 3.1
**Seller:** JIANCAI HE
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/jiancai-he/id1018830539?uo=4">© JIANCAI HE</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple127/v4/2e/c7/eb/2ec7eb43-7776-03a2-1fd9-e7aa43b6e563/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83336808-c15bfc00-a2b6-11ea-8c8e-79b5771fac59.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83336808-c15bfc00-a2b6-11ea-8c8e-79b5771fac59.png)
https://user-images.githubusercontent.com/2068130/83336808-c15bfc00-a2b6-11ea-8c8e-79b5771fac59.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83336816-d042ae80-a2b6-11ea-85a4-2da32233a38b.png
