### ISSUE TITLE
paydirekt

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10814]
**App Name:** paydirekt
**Bundle ID:** com.gimb.paydirect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1004520295">1004520295</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/paydirekt/id1004520295?uo=4">https://apps.apple.com/us/app/paydirekt/id1004520295?uo=4</a>
**App Version:** 2.106.0
**Seller:** paydirekt GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/paydirekt-gmbh/id1004520294?uo=4">© paydirekt GmbH</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/33/f0/83/33f083d9-1abe-97a9-e5d8-5c4dd1e34b13/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83335399-d3d13800-a2ac-11ea-9d83-d15283499002.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83335399-d3d13800-a2ac-11ea-9d83-d15283499002.png)
https://user-images.githubusercontent.com/2068130/83335399-d3d13800-a2ac-11ea-9d83-d15283499002.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83335406-e2b7ea80-a2ac-11ea-8b8f-2452b6c48d1c.png
