### ISSUE TITLE
Shelly - SSH Client

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10813]
**App Name:** Shelly - SSH Client
**Bundle ID:** com.touchfoo.Shelly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989642999">989642999</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/shelly-ssh-client/id989642999?uo=4">https://apps.apple.com/us/app/shelly-ssh-client/id989642999?uo=4</a>
**App Version:** 1.3.2
**Seller:** Ville Makynen
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/touch-foo/id331891508?uo=4">© Touch Foo</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/c5/fe/c0/c5fec0ba-5456-67dc-6328-781539d24648/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337108-0ed96880-a2b9-11ea-86d8-cef6acb03684.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337108-0ed96880-a2b9-11ea-86d8-cef6acb03684.png)
https://user-images.githubusercontent.com/2068130/83337108-0ed96880-a2b9-11ea-86d8-cef6acb03684.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83337115-257fbf80-a2b9-11ea-9de1-bcb1d0744c7a.png
