### ISSUE TITLE
Camera+ 2

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10811]
**App Name:** Camera+ 2
**Bundle ID:** com.latenitesoft.CameraPlus2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1313580627">1313580627</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/camera-2/id1313580627?uo=4">https://apps.apple.com/us/app/camera-2/id1313580627?uo=4</a>
**App Version:** 3.9.1
**Seller:** LateNiteSoft S.L.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/latenitesoft-s-l/id283292600?uo=4">© LateNiteSoft S.L.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/d6/53/80/d6538040-5e70-64e1-0861-38dec356a869/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84353557-af842e00-abbf-11ea-8469-ec3b189b4afc.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84353557-af842e00-abbf-11ea-8469-ec3b189b4afc.png)
https://user-images.githubusercontent.com/2068130/84353557-af842e00-abbf-11ea-8469-ec3b189b4afc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84353591-bf9c0d80-abbf-11ea-8e56-9227762d728e.png
