### ISSUE TITLE
Kleine Löschmeister

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10815]
**App Name:** Kleine Löschmeister
**Bundle ID:** de.vkb.klhvkb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1507927556">1507927556</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/kleine-l%C3%B6schmeister/id1507927556?uo=4">https://apps.apple.com/de/app/kleine-l%C3%B6schmeister/id1507927556?uo=4</a>
**App Version:** 2
**Seller:** Versicherungskammer Bayern
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/versicherungskammer-bayern/id521714615?uo=4">© Versicherungskammer Bayern</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/94/ec/e6/94ece6a5-49e6-33b1-ad11-a497c168ba85/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84596522-90ef9280-ae5e-11ea-8a96-bb992b1c7af7.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84596522-90ef9280-ae5e-11ea-8a96-bb992b1c7af7.png)
https://user-images.githubusercontent.com/2068130/84596522-90ef9280-ae5e-11ea-8a96-bb992b1c7af7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84596534-a8c71680-ae5e-11ea-8714-ad3dfbe4a9b9.png
