### ISSUE TITLE
QR Code - QR Reader & Scanner

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10818]
**App Name:** QR Code - QR Reader & Scanner
**Bundle ID:** com.wenstudio.free.f3.Scanner6
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1180506724">1180506724</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/qr-code-qr-reader-scanner/id1180506724?uo=4">https://apps.apple.com/us/app/qr-code-qr-reader-scanner/id1180506724?uo=4</a>
**App Version:** 1.0.4
**Seller:** wang haiwen
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wen-studio/id380479150?uo=4">© Wen Studio</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/6e/b3/37/6eb337bf-a868-99c7-63de-cc683d3270a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83348190-7da2da00-a32a-11ea-900a-b9e970d9f705.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83348190-7da2da00-a32a-11ea-900a-b9e970d9f705.png)
https://user-images.githubusercontent.com/2068130/83348190-7da2da00-a32a-11ea-900a-b9e970d9f705.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83348197-914e4080-a32a-11ea-8a67-5ecd7b165cbf.png
