### ISSUE TITLE
S-pushTAN

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10810]
**App Name:** S-pushTAN
**Bundle ID:** de.starfinanz.pushTanApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=563488727">563488727</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/s-pushtan/id563488727?uo=4">https://apps.apple.com/us/app/s-pushtan/id563488727?uo=4</a>
**App Version:** 2.7.1
**Seller:** Star Finanz GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/star-finanz-gmbh/id320596875?uo=4">© Star Finanz GmbH</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/26/0b/fa/260bfab7-1457-c9a2-5ce3-75f03fe0822f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83347781-b0979e80-a327-11ea-88a3-1e9c33202c8f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83347781-b0979e80-a327-11ea-88a3-1e9c33202c8f.png)
https://user-images.githubusercontent.com/2068130/83347781-b0979e80-a327-11ea-88a3-1e9c33202c8f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83347790-c016e780-a327-11ea-8aa4-56e0aaa505ac.png
