### ISSUE TITLE
PiHelper

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10816]
**App Name:** PiHelper
**Bundle ID:** sha.PiHelper
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1369930932">1369930932</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pihelper/id1369930932?uo=4">https://apps.apple.com/us/app/pihelper/id1369930932?uo=4</a>
**App Version:** 1.5
**Seller:** Qian Sha
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/qian-sha/id1336462534?uo=4">© Qian Sha</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/e6/e8/00/e6e800d2-3835-96f4-69a6-ece1d7ea7e0a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84351613-06880400-abbc-11ea-88e3-3606eb22fd81.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84351613-06880400-abbc-11ea-88e3-3606eb22fd81.png)
https://user-images.githubusercontent.com/2068130/84351613-06880400-abbc-11ea-88e3-3606eb22fd81.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84351648-169fe380-abbc-11ea-9815-c96480c0878e.png
