### ISSUE TITLE
Lockdown Apps

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#10819]
**App Name:** Lockdown Apps
**Bundle ID:** com.confirmed.lockdown
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1469783711">1469783711</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/lockdown-apps/id1469783711?uo=4">https://apps.apple.com/us/app/lockdown-apps/id1469783711?uo=4</a>
**App Version:** 0.3.7
**Seller:** Confirmed, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/confirmed-inc/id1286896060?uo=4">© Confirmed, Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/ed/5d/d4/ed5dd49b-d30f-013b-7bfa-38b453eff985/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83303079-c197c100-a1fc-11ea-9716-ef053fb172ec.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83303079-c197c100-a1fc-11ea-9716-ef053fb172ec.png)
https://user-images.githubusercontent.com/2068130/83303079-c197c100-a1fc-11ea-9716-ef053fb172ec.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83303140-d1afa080-a1fc-11ea-998b-66d97aa054a5.png
