### ISSUE TITLE
Mixer - Interactive Streaming

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#10820]
**App Name:** Mixer - Interactive Streaming
**Bundle ID:** com.mcprohosting.Beam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937253977">937253977</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mixer-interactive-streaming/id937253977?uo=4">https://apps.apple.com/us/app/mixer-interactive-streaming/id937253977?uo=4</a>
**App Version:** 5.3.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/microsoft-corporation/id298856275?uo=4">© Microsoft Corporation</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/5e/99/9e/5e999e1e-b6a0-5479-2105-0a9f52eb31fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com mcprohosting Beam-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83302706-1a1a8e80-a1fc-11ea-95ea-681d76b2c90c.png)

**Comment by dreamnet** [comment]
![com mcprohosting Beam-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83302706-1a1a8e80-a1fc-11ea-95ea-681d76b2c90c.png)
https://user-images.githubusercontent.com/2068130/83302706-1a1a8e80-a1fc-11ea-95ea-681d76b2c90c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83302750-2868aa80-a1fc-11ea-9d8c-6bdd1ec634b5.png
