### ISSUE TITLE
foobar2000

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#10821]
**App Name:** foobar2000
**Bundle ID:** com.foobar2000.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1072807669">1072807669</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/foobar2000/id1072807669?uo=4">https://apps.apple.com/us/app/foobar2000/id1072807669?uo=4</a>
**App Version:** 1.2.0
**Seller:** Resolute Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/resolute-limited/id1072807668?uo=4">© Resolute Limited</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/f8/72/40/f87240e4-2c70-f900-b3e5-b799e6a5e6b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83302313-60232280-a1fb-11ea-8410-b6173a2ff1b8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83302313-60232280-a1fb-11ea-8410-b6173a2ff1b8.png)
https://user-images.githubusercontent.com/2068130/83302313-60232280-a1fb-11ea-8410-b6173a2ff1b8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83302338-7204c580-a1fb-11ea-8cfd-c0ec82de0723.png
