### ISSUE TITLE
Remote Battery & Connectivity

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10829]
**App Name:** Remote Battery & Connectivity
**Bundle ID:** com.caramba.batteryLevel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=954912200">954912200</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/remote-battery-connectivity/id954912200?uo=4">https://apps.apple.com/us/app/remote-battery-connectivity/id954912200?uo=4</a>
**App Version:** 5.22
**Seller:** Caramba App Development
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/caramba-app-development/id349530108?uo=4">© Caramba App Development</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/a8/94/9b/a8949be5-4943-2634-35d7-2096b63919fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83975136-7499a600-a8f2-11ea-825d-a9516b138bcb.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83975136-7499a600-a8f2-11ea-825d-a9516b138bcb.png)
https://user-images.githubusercontent.com/2068130/83975136-7499a600-a8f2-11ea-825d-a9516b138bcb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83975146-88450c80-a8f2-11ea-88b3-92da952f822f.png
