### ISSUE TITLE
Hiya: Spam Phone Call Blocker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10828]
**App Name:** Hiya: Spam Phone Call Blocker
**Bundle ID:** com.whitepages.callerid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=986999874">986999874</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hiya-spam-phone-call-blocker/id986999874?uo=4">https://apps.apple.com/us/app/hiya-spam-phone-call-blocker/id986999874?uo=4</a>
**App Version:** 6.16
**Seller:** Hiya Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hiya/id1112770081?uo=4">© Hiya</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/5e/db/40/5edb40b6-f530-7f81-5246-27b0c4402b39/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83336656-742b5a80-a2b5-11ea-9b72-aed33f5f2bf5.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83336656-742b5a80-a2b5-11ea-9b72-aed33f5f2bf5.png)
https://user-images.githubusercontent.com/2068130/83336656-742b5a80-a2b5-11ea-9b72-aed33f5f2bf5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83336671-860cfd80-a2b5-11ea-85a9-3d2e1a5c3b2f.png
