### ISSUE TITLE
BanG Dream! Girls Band Party!

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#10822]
**App Name:** BanG Dream! Girls Band Party!
**Bundle ID:** com.bushiroad.en.bangdreamgbp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1335529760">1335529760</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bang-dream-girls-band-party/id1335529760?uo=4">https://apps.apple.com/us/app/bang-dream-girls-band-party/id1335529760?uo=4</a>
**App Version:** 3.6.3
**Seller:** Bushiroad International Pte. Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bushiroad-international/id1313165317?uo=4">© Bushiroad International</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/c9/41/d0/c941d0ea-4d80-2d32-e963-7af7b58b74ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61594753-c4468480-abef-11e9-8b67-82dcf4beaba5.png)

**Comment by dreamnet** [comment]
Same as #10086.
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61594753-c4468480-abef-11e9-8b67-82dcf4beaba5.png)
https://user-images.githubusercontent.com/2068130/61594753-c4468480-abef-11e9-8b67-82dcf4beaba5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/61594760-d6c0be00-abef-11e9-8999-2430449e385e.png
