### ISSUE TITLE
Pokémon HOME

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#10824]
**App Name:** Pokémon HOME
**Bundle ID:** jp.pokemon.pokemonhome
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1485352913">1485352913</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pok%C3%A9mon-home/id1485352913?uo=4">https://apps.apple.com/us/app/pok%C3%A9mon-home/id1485352913?uo=4</a>
**App Version:** 1.1.0
**Seller:** The Pokemon Company
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-pokemon-company/id446737235?uo=4">© The Pokemon Company</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/e8/15/67/e81567ad-c816-7b39-12d7-32e17680de87/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83338874-a5f9ec80-a2c8-11ea-8cca-2c3a333cd3a6.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83338874-a5f9ec80-a2c8-11ea-8cca-2c3a333cd3a6.png)
https://user-images.githubusercontent.com/2068130/83338874-a5f9ec80-a2c8-11ea-8cca-2c3a333cd3a6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83338880-b611cc00-a2c8-11ea-9348-331db912a413.png
