### ISSUE TITLE
Philo

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10827]
**App Name:** Philo
**Bundle ID:** com.philo.tv.philo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1248646044">1248646044</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/philo/id1248646044?uo=4">https://apps.apple.com/us/app/philo/id1248646044?uo=4</a>
**App Version:** 1.7.0
**Seller:** Philo, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/philo/id834527962?uo=4">© Philo</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/43/d4/ee/43d4ee02-d5e7-4c7c-9e1a-e4faa377bb7e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83336935-a938ac80-a2b7-11ea-9497-aef6879a8708.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83336935-a938ac80-a2b7-11ea-9497-aef6879a8708.png)
https://user-images.githubusercontent.com/2068130/83336935-a938ac80-a2b7-11ea-9497-aef6879a8708.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83336946-b8b7f580-a2b7-11ea-870c-0e17b3eeebbb.png
