### ISSUE TITLE
Hobi Time - TV Shows Tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10825]
**App Name:** Hobi Time - TV Shows Tracker
**Bundle ID:** com.hobi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1387915223">1387915223</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hobi-time-tv-shows-tracker/id1387915223?uo=4">https://apps.apple.com/us/app/hobi-time-tv-shows-tracker/id1387915223?uo=4</a>
**App Version:** 2.0.93
**Seller:** Eran D
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/eran-d/id1387915222?uo=4">© Eran D</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/22/74/09/22740968-7c7a-23c6-ecef-1f7cb21b4d1f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83301622-3f0e0200-a1fa-11ea-9a13-12e54cf0f999.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83301622-3f0e0200-a1fa-11ea-9a13-12e54cf0f999.png)
https://user-images.githubusercontent.com/2068130/83301622-3f0e0200-a1fa-11ea-9a13-12e54cf0f999.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83301655-4e8d4b00-a1fa-11ea-8d09-a812a0c97a33.png
