### ISSUE TITLE
Nimbus Note

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10826]
**App Name:** Nimbus Note
**Bundle ID:** bvb.Nimbus-Notes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=828918459">828918459</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/nimbus-note/id828918459?uo=4">https://apps.apple.com/us/app/nimbus-note/id828918459?uo=4</a>
**App Version:** 6.8.2
**Seller:** Nimbus Web, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nimbus-web-inc/id938042715?uo=4">© Nimbus Web Inc</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/fd/b1/77/fdb17706-ce7c-7812-6554-fea4ab1213d7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83301320-ba22e880-a1f9-11ea-84de-cf258cbf3dc2.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83301320-ba22e880-a1f9-11ea-84de-cf258cbf3dc2.png)
https://user-images.githubusercontent.com/2068130/83301320-ba22e880-a1f9-11ea-84de-cf258cbf3dc2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83301356-c9099b00-a1f9-11ea-94a2-5f258f59f7dd.png
