### ISSUE TITLE
DJcity

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10833]
**App Name:** DJcity
**Bundle ID:** com.djcity.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=485534275">485534275</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/djcity/id485534275?uo=4">https://apps.apple.com/us/app/djcity/id485534275?uo=4</a>
**App Version:** 4.0
**Seller:** DJCity, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/djcity-inc/id485534278?uo=4">© DJCity, Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/ed/9e/bd/ed9ebd2c-d555-6e8d-d1ba-8493a0a25bab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83299583-c194c280-a1f6-11ea-932a-8e4d6928267e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83299583-c194c280-a1f6-11ea-932a-8e4d6928267e.png)
https://user-images.githubusercontent.com/2068130/83299583-c194c280-a1f6-11ea-932a-8e4d6928267e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83299615-d1140b80-a1f6-11ea-82b5-9867c60306ac.png
