### ISSUE TITLE
MileIQ: Mileage Tracker & Log

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10836]
**App Name:** MileIQ: Mileage Tracker & Log
**Bundle ID:** com.mobiledatalabs.goiq
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=578830929">578830929</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mileiq-mileage-tracker-log/id578830929?uo=4">https://apps.apple.com/us/app/mileiq-mileage-tracker-log/id578830929?uo=4</a>
**App Version:** 1.45.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/microsoft-corporation/id298856275?uo=4">© Microsoft Corporation</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/9b/f9/11/9bf911d6-c194-88fd-3087-bbe3f5e0c084/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83298488-d83a1a00-a1f4-11ea-9dad-31268e269c93.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83298488-d83a1a00-a1f4-11ea-9dad-31268e269c93.png)
https://user-images.githubusercontent.com/2068130/83298488-d83a1a00-a1f4-11ea-9dad-31268e269c93.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83298529-e7b96300-a1f4-11ea-90f4-0bdf2569c3a0.png
