### ISSUE TITLE
JB4 Mobile

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10837]
**App Name:** JB4 Mobile
**Bundle ID:** com.dmacpro91.jb4-mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=794841332">794841332</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/jb4-mobile/id794841332?uo=4">https://apps.apple.com/us/app/jb4-mobile/id794841332?uo=4</a>
**App Version:** 2.4.3
**Seller:** Dmac Mobile Developments, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dmac-mobile-developments-llc/id372235786?uo=4">© Dmac Mobile Developments, LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/b7/da/79/b7da79e7-fae2-a47d-1ed0-14f1f0c36436/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334796-42ac9200-a2a9-11ea-9dc8-a5f14ef00651.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334796-42ac9200-a2a9-11ea-9dc8-a5f14ef00651.png)
https://user-images.githubusercontent.com/2068130/83334796-42ac9200-a2a9-11ea-9dc8-a5f14ef00651.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83334810-522bdb00-a2a9-11ea-901f-78c76b3c8897.png
