### ISSUE TITLE
BPM Supreme

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10834]
**App Name:** BPM Supreme
**Bundle ID:** com.bpmsupreme.bpmmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1435624754">1435624754</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bpm-supreme/id1435624754?uo=4">https://apps.apple.com/us/app/bpm-supreme/id1435624754?uo=4</a>
**App Version:** 1.3
**Seller:** BPMSUPREME.COM LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bpm-supreme-llc/id1435624753?uo=4">© BPM Supreme LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/96/0b/3f/960b3f98-6a7b-5dc7-d415-cc15b922b985/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83299247-1e43ad80-a1f6-11ea-8735-3491d62805dd.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83299247-1e43ad80-a1f6-11ea-8735-3491d62805dd.png)
https://user-images.githubusercontent.com/2068130/83299247-1e43ad80-a1f6-11ea-8735-3491d62805dd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83299289-2dc2f680-a1f6-11ea-89ea-85725b9563cb.png
