### ISSUE TITLE
Camera for OBS Studio

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10831]
**App Name:** Camera for OBS Studio
**Bundle ID:** io.townsend.obs-iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1352834008">1352834008</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/camera-for-obs-studio/id1352834008?uo=4">https://apps.apple.com/us/app/camera-for-obs-studio/id1352834008?uo=4</a>
**App Version:** 3.0.1
**Seller:** Loft Labs Interactive Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/loft-labs-interactive-inc/id482491153?uo=4">© Loft Labs Interactive Inc</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/8d/04/47/8d044740-bf38-b932-b923-0ed602be03f2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83300891-16393d00-a1f9-11ea-9603-85be8c7f162a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83300891-16393d00-a1f9-11ea-9603-85be8c7f162a.png)
https://user-images.githubusercontent.com/2068130/83300891-16393d00-a1f9-11ea-9603-85be8c7f162a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83300946-281ae000-a1f9-11ea-867b-6f16ca87fb70.png
