### ISSUE TITLE
TELUS Business Connect™

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10835]
**App Name:** TELUS Business Connect™
**Bundle ID:** com.telus.businessconnect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=925058301">925058301</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/telus-business-connect/id925058301?uo=4">https://apps.apple.com/us/app/telus-business-connect/id925058301?uo=4</a>
**App Version:** 20.1.30
**Seller:** TELUS Communications Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/telus-communications-inc/id1351428851?uo=4">© TELUS Communications Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/e7/4b/1b/e74b1be4-a76c-0c3a-b695-ec26659a5cbb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83298869-7d54f280-a1f5-11ea-8944-255860b7d06f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83298869-7d54f280-a1f5-11ea-8944-255860b7d06f.png)
https://user-images.githubusercontent.com/2068130/83298869-7d54f280-a1f5-11ea-8944-255860b7d06f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83298909-8cd43b80-a1f5-11ea-8c59-53b6645cbd48.png
