### ISSUE TITLE
Bellhop - Find & compare rides

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10830]
**App Name:** Bellhop - Find & compare rides
**Bundle ID:** com.bellhop.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1081008679">1081008679</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bellhop-find-compare-rides/id1081008679?uo=4">https://apps.apple.com/us/app/bellhop-find-compare-rides/id1081008679?uo=4</a>
**App Version:** 2.71
**Seller:** Bellhop Technologies Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bellhop-technologies-inc/id1081008678?uo=4">© Bellhop Technologies Inc</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/a3/c6/cf/a3c6cf51-7fb9-d906-31e7-5992e3d3be4e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83318988-6258a180-a23a-11ea-99e9-2e9b4083f7d5.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83318988-6258a180-a23a-11ea-99e9-2e9b4083f7d5.png)
https://user-images.githubusercontent.com/2068130/83318988-6258a180-a23a-11ea-99e9-2e9b4083f7d5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83318993-743a4480-a23a-11ea-91ce-6396f92375b9.png
