### ISSUE TITLE
InShot - Video Editor

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10832]
**App Name:** InShot - Video Editor
**Bundle ID:** com.camerasideas.InstaShot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=997362197">997362197</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/inshot-video-editor/id997362197?uo=4">https://apps.apple.com/us/app/inshot-video-editor/id997362197?uo=4</a>
**App Version:** 1.43.2
**Seller:** InstaShot Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/instashot-inc/id867586329?uo=4">© InstaShot Inc.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/00/30/7b/00307b4e-77ba-d5b1-a460-d6d3bc22379a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83300260-ffdeb180-a1f7-11ea-814a-b1ebbf339c87.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83300260-ffdeb180-a1f7-11ea-814a-b1ebbf339c87.png)
https://user-images.githubusercontent.com/2068130/83300260-ffdeb180-a1f7-11ea-814a-b1ebbf339c87.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83300301-0ff69100-a1f8-11ea-98e3-1088f87f7f20.png
