### ISSUE TITLE
Text Editor.

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10847]
**App Name:** Text Editor.
**Bundle ID:** com.tapuniverse.texteditor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1483790257">1483790257</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/text-editor/id1483790257?uo=4">https://apps.apple.com/us/app/text-editor/id1483790257?uo=4</a>
**App Version:** 1.3.1
**Seller:** Nam Le
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nam-le/id1462862671?uo=4">© Nam Le</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/ff/ed/d1/ffedd139-6e60-9bcc-0536-973ace119df9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334153-d334a380-a2a4-11ea-9ac0-7f8bc2652c05.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334153-d334a380-a2a4-11ea-9ac0-7f8bc2652c05.png)
https://user-images.githubusercontent.com/2068130/83334153-d334a380-a2a4-11ea-9ac0-7f8bc2652c05.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83334168-e34c8300-a2a4-11ea-8e02-a232157a6caa.png
