### ISSUE TITLE
DreamScreenTV

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10840]
**App Name:** DreamScreenTV
**Bundle ID:** com.lab714.dreamscreenv2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1200901829">1200901829</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dreamscreentv/id1200901829?uo=4">https://apps.apple.com/us/app/dreamscreentv/id1200901829?uo=4</a>
**App Version:** 2.2.1
**Seller:** Rakesh Reddy
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/rakesh-reddy/id1033657441?uo=4">© Rakesh Reddy</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/4f/58/44/4f584409-f106-ee61-444a-33812f430e33/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334334-03307680-a2a6-11ea-8745-393aa550cd35.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334334-03307680-a2a6-11ea-8745-393aa550cd35.png)
https://user-images.githubusercontent.com/2068130/83334334-03307680-a2a6-11ea-8745-393aa550cd35.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83334339-14798300-a2a6-11ea-9ecb-9d5c9180ac50.png
