### ISSUE TITLE
Fiery Feeds: RSS Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10846]
**App Name:** Fiery Feeds: RSS Reader
**Bundle ID:** net.voidstern.fiery-feeds
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1158763303">1158763303</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fiery-feeds-rss-reader/id1158763303?uo=4">https://apps.apple.com/us/app/fiery-feeds-rss-reader/id1158763303?uo=4</a>
**App Version:** 2.3.12
**Seller:** Lukas Burgstaller
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lukas-burgstaller/id383916386?uo=4">© Lukas Burgstaller</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/36/5c/ee/365ceed6-afee-bac6-f00e-325325669b3a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83333686-09bcef00-a2a2-11ea-8e02-a9642de18e30.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83333686-09bcef00-a2a2-11ea-8e02-a9642de18e30.png)
https://user-images.githubusercontent.com/2068130/83333686-09bcef00-a2a2-11ea-8e02-a9642de18e30.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83333700-19d4ce80-a2a2-11ea-8d34-517696f126bf.png
