### ISSUE TITLE
PARENTS | TalkingPoints

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10843]
**App Name:** PARENTS | TalkingPoints
**Bundle ID:** app.talkingpts.parents
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1320244591">1320244591</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/parents-talkingpoints/id1320244591?uo=4">https://apps.apple.com/us/app/parents-talkingpoints/id1320244591?uo=4</a>
**App Version:** 3.0.80
**Seller:** TalkingPoints Corp
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/talkingpoints/id1205379491?uo=4">© TalkingPoints</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/ac/86/1b/ac861b2e-5ac4-bce8-2328-f2a1c3cb99ff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334011-ebf08980-a2a3-11ea-99da-d72a51def604.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334011-ebf08980-a2a3-11ea-99da-d72a51def604.png)
https://user-images.githubusercontent.com/2068130/83334011-ebf08980-a2a3-11ea-99da-d72a51def604.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83334025-fca0ff80-a2a3-11ea-8e96-482f1fb00d88.png
