### ISSUE TITLE
CVS Caremark

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10844]
**App Name:** CVS Caremark
**Bundle ID:** com.caremark.caremark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382300394">382300394</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cvs-caremark/id382300394?uo=4">https://apps.apple.com/us/app/cvs-caremark/id382300394?uo=4</a>
**App Version:** 4.67
**Seller:** CVS Caremark
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cvs-caremark/id382300397?uo=4">© CVS Caremark</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/12/d0/b0/12d0b0e5-01d0-e080-908f-273735d2c425/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83333891-39b8c200-a2a3-11ea-86a0-7f12a6a2ec6f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83333891-39b8c200-a2a3-11ea-86a0-7f12a6a2ec6f.png)
https://user-images.githubusercontent.com/2068130/83333891-39b8c200-a2a3-11ea-86a0-7f12a6a2ec6f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83333905-489f7480-a2a3-11ea-864e-2fadb6fe6b61.png
