### ISSUE TITLE
Citrix QuickEdit

### ISSUE THREAD

**Issue by DarkXess** [glasklart/hd#1084]
**App Name:** Citrix QuickEdit
**Bundle ID:** com.bytesquared.office2ipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364361728">364361728</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/citrix-quickedit/id364361728?mt=8&uo=4">https://itunes.apple.com/us/app/citrix-quickedit/id364361728?mt=8&uo=4</a>
**App Version:** 6.5
**Seller:** Byte Squared
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/byte2/id334652358?uo=4>© Byte²</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/43/80/09/43800975-a2e9-1b72-52ef-e9f06af54a96/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417200/0b8b0276-93a7-11e6-9aa1-a6cf92e4194e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417200/0b8b0276-93a7-11e6-9aa1-a6cf92e4194e.png)
https://cloud.githubusercontent.com/assets/20930745/19417200/0b8b0276-93a7-11e6-9aa1-a6cf92e4194e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19417206/295015ee-93a7-11e6-9182-09604c2c4f8e.png
