### ISSUE TITLE
The App List

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10842]
**App Name:** The App List
**Bundle ID:** me.fouquet.applist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1381108146">1381108146</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/the-app-list/id1381108146?uo=4">https://apps.apple.com/us/app/the-app-list/id1381108146?uo=4</a>
**App Version:** 1.0.1
**Seller:** Rene Fouquet
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/rene-fouquet/id383061334?uo=4">© Rene Fouquet</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/f3/c0/15/f3c015b0-8110-3101-258c-126946fdbc90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334711-9cf92300-a2a8-11ea-9abb-fa69c9d68528.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334711-9cf92300-a2a8-11ea-9abb-fa69c9d68528.png)
https://user-images.githubusercontent.com/2068130/83334711-9cf92300-a2a8-11ea-9abb-fa69c9d68528.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83334717-ad110280-a2a8-11ea-8243-1599f2ca6c76.png
