### ISSUE TITLE
Topgolf

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10849]
**App Name:** Topgolf
**Bundle ID:** com.TopGolf.TopGolfMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=646322524">646322524</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/topgolf/id646322524?uo=4">https://apps.apple.com/us/app/topgolf/id646322524?uo=4</a>
**App Version:** 3.29.1
**Seller:** TopGolf USA, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/topgolf-usa-inc/id646322527?uo=4">© TopGolf USA, Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/8c/aa/3a/8caa3af5-3a4d-0caa-67eb-c1982432415b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337999-34b63b80-a2c0-11ea-841d-2690ab5ce3da.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337999-34b63b80-a2c0-11ea-841d-2690ab5ce3da.png)
https://user-images.githubusercontent.com/2068130/83337999-34b63b80-a2c0-11ea-841d-2690ab5ce3da.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83338007-44358480-a2c0-11ea-8208-65b1bb74f010.png
