### ISSUE TITLE
Heart Analyzer

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10845]
**App Name:** Heart Analyzer
**Bundle ID:** Sim.HeartRate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1006420410">1006420410</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/heart-analyzer/id1006420410?uo=4">https://apps.apple.com/us/app/heart-analyzer/id1006420410?uo=4</a>
**App Version:** 8.0
**Seller:** Helix Apps LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/helix-apps-ltd/id1479527439?uo=4">© Helix Apps LTD</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/f0/1c/97/f01c974c-a24c-d68c-d079-e202c41fce49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83333780-9ebfe800-a2a2-11ea-8c74-9b4070dacb83.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83333780-9ebfe800-a2a2-11ea-8c74-9b4070dacb83.png)
https://user-images.githubusercontent.com/2068130/83333780-9ebfe800-a2a2-11ea-8c74-9b4070dacb83.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83333795-ada69a80-a2a2-11ea-92fc-c6aee4443bd2.png
