### ISSUE TITLE
Watchlist - Movies & TV Shows

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10858]
**App Name:** Watchlist - Movies & TV Shows
**Bundle ID:** com.getwatchlist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1231554707">1231554707</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/watchlist-movies-tv-shows/id1231554707?uo=4">https://apps.apple.com/us/app/watchlist-movies-tv-shows/id1231554707?uo=4</a>
**App Version:** 1.2.10
**Seller:** SGTM, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sgtm/id1231554706?uo=4">© SGTM</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/5c/77/ec/5c77ec69-c1e2-a6d7-b40c-b3f608c046af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339261-47367200-a2cc-11ea-9d2b-c6806e37ce46.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339261-47367200-a2cc-11ea-9d2b-c6806e37ce46.png)
https://user-images.githubusercontent.com/2068130/83339261-47367200-a2cc-11ea-9d2b-c6806e37ce46.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83339263-55848e00-a2cc-11ea-9a2e-01a572800e56.png
