### ISSUE TITLE
Zenkit

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10851]
**App Name:** Zenkit
**Bundle ID:** com.zenkit.Zenkit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=964755085">964755085</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/zenkit/id964755085?uo=4">https://apps.apple.com/us/app/zenkit/id964755085?uo=4</a>
**App Version:** 4.0.3
**Seller:** Axonic Informationssysteme GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/axonic/id481015819?uo=4">© axonic</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/ef/aa/b6/efaab64e-c174-4617-8f2c-477ad6255b38/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83338330-b5c30200-a2c3-11ea-8ab1-521877072d2d.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83338330-b5c30200-a2c3-11ea-8ab1-521877072d2d.png)
https://user-images.githubusercontent.com/2068130/83338330-b5c30200-a2c3-11ea-8ab1-521877072d2d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83338336-c70c0e80-a2c3-11ea-9707-a25211d28f60.png
