### ISSUE TITLE
Workday

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10854]
**App Name:** Workday
**Bundle ID:** com.workday.workdayapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=316800034">316800034</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/workday/id316800034?uo=4">https://apps.apple.com/us/app/workday/id316800034?uo=4</a>
**App Version:** 2020.21.0.201668
**Seller:** Workday, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/workday/id316800037?uo=4">© Workday</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/e4/84/f9/e484f902-7e1a-759a-00e9-e92705f935e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337801-8cec3e00-a2be-11ea-881b-984d0c1991e8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337801-8cec3e00-a2be-11ea-881b-984d0c1991e8.png)
https://user-images.githubusercontent.com/2068130/83337801-8cec3e00-a2be-11ea-881b-984d0c1991e8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83337811-9c6b8700-a2be-11ea-8094-e658b2791bb0.png
