### ISSUE TITLE
WikiTrip

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10852]
**App Name:** WikiTrip
**Bundle ID:** BOS.WikiTrip
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1438931523">1438931523</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wikitrip/id1438931523?uo=4">https://apps.apple.com/us/app/wikitrip/id1438931523?uo=4</a>
**App Version:** 1.4.1
**Seller:** Bjoern Schefzyk
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bj%C3%B6rn-schefzyk/id1207997124?uo=4">© Björn Schefzyk</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/02/13/e2/0213e237-ccec-4034-9761-f5f5b1d37b49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337859-1e5bb000-a2bf-11ea-9e26-e5958e152bce.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337859-1e5bb000-a2bf-11ea-9e26-e5958e152bce.png)
https://user-images.githubusercontent.com/2068130/83337859-1e5bb000-a2bf-11ea-9e26-e5958e152bce.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83337868-30d5e980-a2bf-11ea-98c6-dc26f67fb4f9.png
