### ISSUE TITLE
FLIO

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10853]
**App Name:** FLIO
**Bundle ID:** com.airmedia.FLIO
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=963836358">963836358</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/flio/id963836358?uo=4">https://apps.apple.com/us/app/flio/id963836358?uo=4</a>
**App Version:** 2.10.2
**Seller:** Flio GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/air-media-service/id963836357?uo=4">© Air Media Service</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/35/b0/45/35b04521-08e7-8e70-aa3b-62d35e363280/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337707-f455be00-a2bd-11ea-8b52-88ec0c01bf20.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337707-f455be00-a2bd-11ea-8b52-88ec0c01bf20.png)
https://user-images.githubusercontent.com/2068130/83337707-f455be00-a2bd-11ea-8b52-88ec0c01bf20.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83337724-046d9d80-a2be-11ea-8e1b-e7b00556cfeb.png
