### ISSUE TITLE
BetaSeries - TV Shows & Movies

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10857]
**App Name:** BetaSeries - TV Shows & Movies
**Bundle ID:** com.myluckyday.betaseries
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=874954616">874954616</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/betaseries-tv-shows-movies/id874954616?uo=4">https://apps.apple.com/us/app/betaseries-tv-shows-movies/id874954616?uo=4</a>
**App Version:** 2.15.3
**Seller:** Netcats
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/netcats/id1101648522?uo=4">© Netcats</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/96/6a/00/966a0062-e668-1794-3a07-80dac2de59c2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339002-e148eb00-a2c9-11ea-9908-fe2621f889ef.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339002-e148eb00-a2c9-11ea-9908-fe2621f889ef.png)
https://user-images.githubusercontent.com/2068130/83339002-e148eb00-a2c9-11ea-9908-fe2621f889ef.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83339007-f02f9d80-a2c9-11ea-873b-40ea7e0903da.png
