### ISSUE TITLE
Versus Sports Simulator

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10850]
**App Name:** Versus Sports Simulator
**Bundle ID:** com.compughterratings.versus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=658521240">658521240</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/versus-sports-simulator/id658521240?uo=4">https://apps.apple.com/us/app/versus-sports-simulator/id658521240?uo=4</a>
**App Version:** 1.20
**Seller:** Compughter Technologies, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/compughter-technologies-llc/id658521243?uo=4">© Compughter Technologies, LLC</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/b3/6a/8e/b36a8ed7-6bcd-959e-a23b-7e8463982344/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337922-a17d0600-a2bf-11ea-8faf-9c299c0ea6e5.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83337922-a17d0600-a2bf-11ea-8faf-9c299c0ea6e5.png)
https://user-images.githubusercontent.com/2068130/83337922-a17d0600-a2bf-11ea-8faf-9c299c0ea6e5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83337932-b0fc4f00-a2bf-11ea-9737-581dd9940eea.png
