### ISSUE TITLE
Southwest Airlines

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10856]
**App Name:** Southwest Airlines
**Bundle ID:** com.southwest.iphoneprod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=344542975">344542975</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/southwest-airlines/id344542975?uo=4">https://apps.apple.com/us/app/southwest-airlines/id344542975?uo=4</a>
**App Version:** 7.5.0
**Seller:** Southwest Airlines
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/southwest-airlines-co/id334693128?uo=4">© Southwest Airlines Co.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/7c/76/92/7c76923c-5c87-0a46-9ba9-957f6a1c609b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339352-46521000-a2cd-11ea-9a0e-9e9a6781847a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339352-46521000-a2cd-11ea-9a0e-9e9a6781847a.png)
https://user-images.githubusercontent.com/2068130/83339352-46521000-a2cd-11ea-9a0e-9e9a6781847a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83339362-579b1c80-a2cd-11ea-99dd-bb75e27518af.png
