### ISSUE TITLE
RapidIdentity

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10855]
**App Name:** RapidIdentity
**Bundle ID:** com.identityautomation.rapididentitymobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1230131130">1230131130</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/rapididentity/id1230131130?uo=4">https://apps.apple.com/us/app/rapididentity/id1230131130?uo=4</a>
**App Version:** 2.4.4
**Seller:** Identity Automation, LP
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/identity-automation-lp/id1230131129?uo=4">© Identity Automation, LP</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/77/de/e9/77dee95f-becb-87ec-28b5-490670b9c8fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83338242-8364d500-a2c2-11ea-9581-0079262d7868.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83338242-8364d500-a2c2-11ea-9581-0079262d7868.png)
https://user-images.githubusercontent.com/2068130/83338242-8364d500-a2c2-11ea-9581-0079262d7868.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83338246-937cb480-a2c2-11ea-97f0-e065b938cf6c.png
