### ISSUE TITLE
Happy Color™ – Paint by Number

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10859]
**App Name:** Happy Color™ – Paint by Number
**Bundle ID:** com.coloring.color.number.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1407852246">1407852246</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/happy-color-paint-by-number/id1407852246?uo=4">https://apps.apple.com/us/app/happy-color-paint-by-number/id1407852246?uo=4</a>
**App Version:** 1.6.6
**Seller:** X-FLOW LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/x-flow/id1404509981?uo=4">© X-Flow</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/86/68/a4/8668a406-9f7f-256a-19b3-9d48126c7277/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339093-9380b280-a2ca-11ea-8403-f120f9dbab24.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339093-9380b280-a2ca-11ea-8403-f120f9dbab24.png)
https://user-images.githubusercontent.com/2068130/83339093-9380b280-a2ca-11ea-8403-f120f9dbab24.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83339105-a72c1900-a2ca-11ea-8d48-ce90ba0f4772.png
