### ISSUE TITLE
Bricks n Balls

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10865]
**App Name:** Bricks n Balls
**Bundle ID:** com.cmplay.bricksballs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1331794412">1331794412</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bricks-n-balls/id1331794412?uo=4">https://apps.apple.com/us/app/bricks-n-balls/id1331794412?uo=4</a>
**App Version:** 2.0.10
**Seller:** cheetah technology corporation limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cheetah-technology-corporation-limited/id949821679?uo=4">© Cheetah Technology Corporation Limited</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/b5/1f/8d/b51f8d5f-6e65-acf0-1a45-443e104f3ce3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83351488-b354bc80-a344-11ea-8e47-f81c6ae02415.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83351488-b354bc80-a344-11ea-8e47-f81c6ae02415.png)
https://user-images.githubusercontent.com/2068130/83351488-b354bc80-a344-11ea-8e47-f81c6ae02415.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83351493-c2d40580-a344-11ea-9872-dde7b0565c27.png
