### ISSUE TITLE
Co–Star Personalized Astrology

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10869]
**App Name:** Co–Star Personalized Astrology
**Bundle ID:** com.costarastrology.costar-mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1264782561">1264782561</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/co-star-personalized-astrology/id1264782561?uo=4">https://apps.apple.com/us/app/co-star-personalized-astrology/id1264782561?uo=4</a>
**App Version:** 3.32
**Seller:** Co-Star Astrology Society
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/co-star-astrology-society/id1264782560?uo=4">© Co-Star Astrology Society</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/28/41/75/28417502-6e51-0ac1-223f-816583e7949d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974927-0ef8ea00-a8f1-11ea-83dd-3653c9b21daf.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974927-0ef8ea00-a8f1-11ea-83dd-3653c9b21daf.png)
https://user-images.githubusercontent.com/2068130/83974927-0ef8ea00-a8f1-11ea-83dd-3653c9b21daf.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83974935-1e783300-a8f1-11ea-9db1-86844f7e9d41.png
