### ISSUE TITLE
Pocket City

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10862]
**App Name:** Pocket City
**Bundle ID:** com.codebrewgames.pocketcity
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1330451888">1330451888</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pocket-city/id1330451888?uo=4">https://apps.apple.com/us/app/pocket-city/id1330451888?uo=4</a>
**App Version:** 1.0.32
**Seller:** Codebrew Games Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/codebrew-games-inc/id1330451887?uo=4">© Codebrew Games Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/20/8c/80/208c8089-9ff1-a124-d401-09886005f498/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339463-6504d680-a2ce-11ea-8b8f-f192d80df725.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339463-6504d680-a2ce-11ea-8b8f-f192d80df725.png)
https://user-images.githubusercontent.com/2068130/83339463-6504d680-a2ce-11ea-8b8f-f192d80df725.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83339471-751cb600-a2ce-11ea-8c68-806cb311919d.png
