### ISSUE TITLE
Golden Tee Golf

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10860]
**App Name:** Golden Tee Golf
**Bundle ID:** com.itsgames.goldenteegolf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1350928952">1350928952</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/golden-tee-golf/id1350928952?uo=4">https://apps.apple.com/us/app/golden-tee-golf/id1350928952?uo=4</a>
**App Version:** 2.33
**Seller:** Incredible Technologies
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/incredible-technologies-inc/id367655710?uo=4">© Incredible Technologies, Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/4d/2c/75/4d2c753c-f68b-63f6-ced5-b6a52a5c0a73/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89098904-cdb22180-d3eb-11ea-981d-a12106821ba4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89098904-cdb22180-d3eb-11ea-981d-a12106821ba4.png)
https://user-images.githubusercontent.com/2068130/89098904-cdb22180-d3eb-11ea-981d-a12106821ba4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/89098912-dacf1080-d3eb-11ea-817d-2f3bde9aa99b.png
