### ISSUE TITLE
Euchre 3D

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10866]
**App Name:** Euchre 3D
**Bundle ID:** com.astarsoftware.euchrelite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364909474">364909474</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/euchre-3d/id364909474?uo=4">https://apps.apple.com/us/app/euchre-3d/id364909474?uo=4</a>
**App Version:** 5.5
**Seller:** A Star Software LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/a-star-software-llc/id309679509?uo=4">© A Star Software LLC</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/c6/86/cb/c686cb5a-187a-4c2a-b59a-80f503e21bab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86558451-a3d71d80-bf59-11ea-93fc-4def7a29df98.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86558451-a3d71d80-bf59-11ea-93fc-4def7a29df98.png)
https://user-images.githubusercontent.com/2068130/86558451-a3d71d80-bf59-11ea-93fc-4def7a29df98.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86558472-b2253980-bf59-11ea-9ba1-41996a327a82.png
