### ISSUE TITLE
AOL: News Email Weather Video

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10868]
**App Name:** AOL: News Email Weather Video
**Bundle ID:** com.aol.mobile.aolclient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=646100661">646100661</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/aol-news-email-weather-video/id646100661?uo=4">https://apps.apple.com/us/app/aol-news-email-weather-video/id646100661?uo=4</a>
**App Version:** 5.14.1
**Seller:** AOL Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/aol-inc/id281704577?uo=4">© AOL Inc.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/a4/f7/7e/a4f77e2c-8e52-83f4-83b0-02069bbb3bb6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974749-e58b8e80-a8ef-11ea-8a14-7888038eb88a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974749-e58b8e80-a8ef-11ea-8a14-7888038eb88a.png)
https://user-images.githubusercontent.com/2068130/83974749-e58b8e80-a8ef-11ea-8a14-7888038eb88a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83974758-f63c0480-a8ef-11ea-8167-60cf9666105b.png
