### ISSUE TITLE
RainViewer: Weather Radar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10863]
**App Name:** RainViewer: Weather Radar
**Bundle ID:** com.lucky-apps.RainViewer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=980123924">980123924</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/rainviewer-weather-radar/id980123924?uo=4">https://apps.apple.com/us/app/rainviewer-weather-radar/id980123924?uo=4</a>
**App Version:** 1.11.4
**Seller:** Oleksii Schastlyvyi
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/oleksii-schastlyvyi/id980123923?uo=4">© Oleksii Schastlyvyi</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/a2/48/3d/a2483df8-ed9f-3de0-f2d7-8ad8ba0d156a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83348602-8b5a5e80-a32e-11ea-929b-75a98c4061f5.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83348602-8b5a5e80-a32e-11ea-929b-75a98c4061f5.png)
https://user-images.githubusercontent.com/2068130/83348602-8b5a5e80-a32e-11ea-929b-75a98c4061f5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83348613-9e6d2e80-a32e-11ea-9dfe-5bce0a2b38cf.png
