### ISSUE TITLE
Daily Themed Crossword Puzzle

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10861]
**App Name:** Daily Themed Crossword Puzzle
**Bundle ID:** com.littleengine.wordtrek-crossword
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1197354394">1197354394</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/daily-themed-crossword-puzzle/id1197354394?uo=4">https://apps.apple.com/us/app/daily-themed-crossword-puzzle/id1197354394?uo=4</a>
**App Version:** 1.332
**Seller:** PlaySimple Games Pte Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/playsimple-games-pte-ltd/id1189416142?uo=4">© PlaySimple Games Pte Ltd</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/85/4f/30/854f300f-665e-279f-8f2c-b7dfbf450614/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339411-cb3d2980-a2cd-11ea-9568-a9de702c0123.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83339411-cb3d2980-a2cd-11ea-9568-a9de702c0123.png)
https://user-images.githubusercontent.com/2068130/83339411-cb3d2980-a2cd-11ea-9568-a9de702c0123.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83339417-dd1ecc80-a2cd-11ea-9bae-fba425a80077.png
