### ISSUE TITLE
Quoted Replies

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10877]
**App Name:** Quoted Replies
**Bundle ID:** ng.sparkle.Quoted-Replies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1476940595">1476940595</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/quoted-replies/id1476940595?uo=4">https://apps.apple.com/us/app/quoted-replies/id1476940595?uo=4</a>
**App Version:** 1.0.2
**Seller:** Sagaya Abdul
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sagaya-abdul/id1244455982?uo=4">© Sagaya Abdul</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/3b/c7/12/3bc7127c-acd7-4715-93b7-52518bd275ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83351716-b9e43380-a346-11ea-9fdf-83c3547e9f9c.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83351716-b9e43380-a346-11ea-9fdf-83c3547e9f9c.png)
https://user-images.githubusercontent.com/2068130/83351716-b9e43380-a346-11ea-9fdf-83c3547e9f9c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83351724-c9637c80-a346-11ea-959b-26b7d549458b.png
