### ISSUE TITLE
fnbr.co — Tracker for Fortnite

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10871]
**App Name:** fnbr.co — Tracker for Fortnite
**Bundle ID:** co.fnbr.app.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1459133026">1459133026</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fnbr-co-tracker-for-fortnite/id1459133026?uo=4">https://apps.apple.com/us/app/fnbr-co-tracker-for-fortnite/id1459133026?uo=4</a>
**App Version:** 1.4.1
**Seller:** Kairu Media Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kairu-media-ltd/id1459133025?uo=4">© Kairu Media Ltd</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/cd/59/85/cd5985ee-0e1c-ca80-ec79-1a623b557c99/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974578-ba546f80-a8ee-11ea-8b4e-9822345de5f7.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974578-ba546f80-a8ee-11ea-8b4e-9822345de5f7.png)
https://user-images.githubusercontent.com/2068130/83974578-ba546f80-a8ee-11ea-8b4e-9822345de5f7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83974587-c9d3b880-a8ee-11ea-9b0e-13a1c4f19d4f.png
