### ISSUE TITLE
The Pattern

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10875]
**App Name:** The Pattern
**Bundle ID:** com.thepattern.thepattern
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1071085727">1071085727</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/the-pattern/id1071085727?uo=4">https://apps.apple.com/us/app/the-pattern/id1071085727?uo=4</a>
**App Version:** 3.2.17
**Seller:** Pattern Home, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/pattern-home-inc/id1071085726?uo=4">© Pattern Home, Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/75/82/42/75824288-3a09-fb19-6225-cbf9e601fe06/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83351863-eba9ca00-a347-11ea-9ef9-4227f8c9f239.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83351863-eba9ca00-a347-11ea-9ef9-4227f8c9f239.png)
https://user-images.githubusercontent.com/2068130/83351863-eba9ca00-a347-11ea-9ef9-4227f8c9f239.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83351869-fbc1a980-a347-11ea-85ed-7c945c4b9fbb.png
