### ISSUE TITLE
Trusted Contacts

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10872]
**App Name:** Trusted Contacts
**Bundle ID:** com.google.TrustedContacts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1225684042">1225684042</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/trusted-contacts/id1225684042?uo=4">https://apps.apple.com/us/app/trusted-contacts/id1225684042?uo=4</a>
**App Version:** 1.18
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/6a/8e/f1/6a8ef128-2255-0113-e63e-501e7a32594d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83352451-bacb9400-a34b-11ea-8f83-fc43a4c1e8fb.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83352451-bacb9400-a34b-11ea-8f83-fc43a4c1e8fb.png)
https://user-images.githubusercontent.com/2068130/83352451-bacb9400-a34b-11ea-8f83-fc43a4c1e8fb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83352460-c919b000-a34b-11ea-8121-75eb87de0135.png
