### ISSUE TITLE
Рамблер/почта

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10874]
**App Name:** Рамблер/почта
**Bundle ID:** ru.rambler.mail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=981598964">981598964</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/%D1%80%D0%B0%D0%BC%D0%B1%D0%BB%D0%B5%D1%80-%D0%BF%D0%BE%D1%87%D1%82%D0%B0/id981598964?uo=4">https://apps.apple.com/us/app/%D1%80%D0%B0%D0%BC%D0%B1%D0%BB%D0%B5%D1%80-%D0%BF%D0%BE%D1%87%D1%82%D0%B0/id981598964?uo=4</a>
**App Version:** 1.21.3
**Seller:** Rambler Internet Holdings LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/rambler-internet-holdings-llc/id395455934?uo=4">© Rambler Internet Holdings LLC</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/28/fa/86/28fa864a-aeb9-40df-e4db-93bc31399d94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86529539-a7af6500-beb1-11ea-9ccc-7fc63d160aa7.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86529539-a7af6500-beb1-11ea-9ccc-7fc63d160aa7.png)
https://user-images.githubusercontent.com/2068130/86529539-a7af6500-beb1-11ea-9ccc-7fc63d160aa7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86529548-b85fdb00-beb1-11ea-8d90-d3b3113cfb79.png
