### ISSUE TITLE
Google Podcasts

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10876]
**App Name:** Google Podcasts
**Bundle ID:** com.google.podcasts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1398000105">1398000105</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-podcasts/id1398000105?uo=4">https://apps.apple.com/us/app/google-podcasts/id1398000105?uo=4</a>
**App Version:** 2.0
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/6d/ae/6c/6dae6c3f-a435-9d87-f7b8-94f58af8eac3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83351801-60c8cf80-a347-11ea-899f-4fe4cf1269df.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83351801-60c8cf80-a347-11ea-899f-4fe4cf1269df.png)
https://user-images.githubusercontent.com/2068130/83351801-60c8cf80-a347-11ea-899f-4fe4cf1269df.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83351812-73430900-a347-11ea-9822-e331804fdb89.png
