### ISSUE TITLE
爱奇艺PPS

### ISSUE THREAD

**Issue by DarkXess** [glasklart/hd#1087]
**App Name:** 爱奇艺PPS
**Bundle ID:** com.pps.test
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445375097">445375097</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%E7%88%B1%E5%A5%87%E8%89%BApps/id445375097?mt=8&uo=4">https://itunes.apple.com/us/app/%E7%88%B1%E5%A5%87%E8%89%BApps/id445375097?mt=8&uo=4</a>
**App Version:** 6.3.6
**Seller:** Beijing IQIYI Science & Technology Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/iqiyi/id888236375?uo=4">© iQiYi</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/49/9e/38/499e38a0-0be0-d376-8cbc-c62be51da86d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32387758-c9122bc0-c0c5-11e7-963f-f3eedc26dc5c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32387758-c9122bc0-c0c5-11e7-963f-f3eedc26dc5c.png)
https://user-images.githubusercontent.com/2068130/32387758-c9122bc0-c0c5-11e7-963f-f3eedc26dc5c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32387780-d943646e-c0c5-11e7-8771-ffb3cbb9f018.png
