### ISSUE TITLE
FlickType Keyboard

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10878]
**App Name:** FlickType Keyboard
**Bundle ID:** com.kpaw.FlickType
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1359485719">1359485719</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/flicktype-keyboard/id1359485719?uo=4">https://apps.apple.com/us/app/flicktype-keyboard/id1359485719?uo=4</a>
**App Version:** 2000.6
**Seller:** Kpaw LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kpaw-llc/id1275307195?uo=4">© Kpaw, LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a3/a3/dc/a3a3dc80-8696-2543-686e-31b23b7ed361/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85230481-c6f9bd00-b3f0-11ea-9188-bd9de7bcbde3.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85230481-c6f9bd00-b3f0-11ea-9188-bd9de7bcbde3.png)
https://user-images.githubusercontent.com/2068130/85230481-c6f9bd00-b3f0-11ea-9188-bd9de7bcbde3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85230490-d7119c80-b3f0-11ea-9324-d42be50a7da1.png
