### ISSUE TITLE
Email App –  Mail.ru

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10873]
**App Name:** Email App –  Mail.ru
**Bundle ID:** ru.mail.mail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=511310430">511310430</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/email-app-mail-ru/id511310430?uo=4">https://apps.apple.com/us/app/email-app-mail-ru/id511310430?uo=4</a>
**App Version:** 12.1
**Seller:** Mail.Ru
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mail-ru/id335315533?uo=4">© Mail.Ru</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/41/0a/5d/410a5d0b-8b48-297a-2ae7-7734a02dfcdd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83351940-6d99f300-a348-11ea-8c2b-ab6b9ee4ec13.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83351940-6d99f300-a348-11ea-8c2b-ab6b9ee4ec13.png)
https://user-images.githubusercontent.com/2068130/83351940-6d99f300-a348-11ea-8c2b-ab6b9ee4ec13.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83351953-7e4a6900-a348-11ea-8719-153220c1d12c.png
