### ISSUE TITLE
Antidote Mobile – French

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10879]
**App Name:** Antidote Mobile – French
**Bundle ID:** com.druide.Antidote.AARD2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=797819487">797819487</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/antidote-mobile-french/id797819487?uo=4">https://apps.apple.com/us/app/antidote-mobile-french/id797819487?uo=4</a>
**App Version:** 3.2.5
**Seller:** Druide informatique inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/druide-informatique/id290965228?uo=4">© Druide informatique</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/bb/2f/6f/bb2f6fc6-798e-4bc4-e648-d190c7df4402/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85229467-1e485f00-b3ea-11ea-845b-a1f6e74bd59e.png)

**Comment by dreamnet** [comment]
Same as #4955 .
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85229467-1e485f00-b3ea-11ea-845b-a1f6e74bd59e.png)
https://user-images.githubusercontent.com/2068130/85229467-1e485f00-b3ea-11ea-845b-a1f6e74bd59e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85229492-391ad380-b3ea-11ea-8920-3f164996547b.png
