### ISSUE TITLE
Copper Branch

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10884]
**App Name:** Copper Branch
**Bundle ID:** io.ueat.copperBranchCan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1490266889">1490266889</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/ca/app/copper-branch/id1490266889?uo=4">https://apps.apple.com/ca/app/copper-branch/id1490266889?uo=4</a>
**App Version:** 1.0.2
**Seller:** Technologies UEAT Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/ca/developer/technologies-ueat-inc/id1458927580?uo=4">© Technologies UEAT Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/20/8b/26/208b263f-1fc0-e28f-0f7f-de419d349c0b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83967194-a04f6880-a8bf-11ea-91fc-90f2cc8d3618.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83967194-a04f6880-a8bf-11ea-91fc-90f2cc8d3618.png)
https://user-images.githubusercontent.com/2068130/83967194-a04f6880-a8bf-11ea-91fc-90f2cc8d3618.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83967202-afceb180-a8bf-11ea-9718-f1991fbed493.png
