### ISSUE TITLE
Schlage Home

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10881]
**App Name:** Schlage Home
**Bundle ID:** com.allegion.sense.store
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1038212933">1038212933</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/schlage-home/id1038212933?uo=4">https://apps.apple.com/us/app/schlage-home/id1038212933?uo=4</a>
**App Version:** 4.1.8
**Seller:** Schlage Lock Company, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/schlage-lock-company/id430327277?uo=4">© Schlage Lock Company</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/45/cc/30/45cc3062-6a48-544f-6ffa-44d69193fa6d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974527-271b3a00-a8ee-11ea-83ab-3a6648bf280f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974527-271b3a00-a8ee-11ea-83ab-3a6648bf280f.png)
https://user-images.githubusercontent.com/2068130/83974527-271b3a00-a8ee-11ea-83ab-3a6648bf280f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83974533-369a8300-a8ee-11ea-96f4-e1cb52514fb4.png
