### ISSUE TITLE
Moe Rewards

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10888]
**App Name:** Moe Rewards
**Bundle ID:** com.punchh.moes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1008719375">1008719375</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/moe-rewards/id1008719375?uo=4">https://apps.apple.com/us/app/moe-rewards/id1008719375?uo=4</a>
**App Version:** 3.1.1
**Seller:** Moe's Franchisor SPV LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/moes-southwest-grill/id1391126547?uo=4">© Moe's Southwest Grill</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/c2/0d/30/c20d30f5-f225-882d-47ec-a57ff604e105/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84350921-93ca5900-abba-11ea-81a0-2c90c5b0b648.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84350921-93ca5900-abba-11ea-81a0-2c90c5b0b648.png)
https://user-images.githubusercontent.com/2068130/84350921-93ca5900-abba-11ea-81a0-2c90c5b0b648.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84350943-a349a200-abba-11ea-9366-4f5b2ee9918b.png
