### ISSUE TITLE
PandaDoc - Track & eSign Docs

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10883]
**App Name:** PandaDoc - Track & eSign Docs
**Bundle ID:** com.pandadoc.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1210645479">1210645479</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pandadoc-track-esign-docs/id1210645479?uo=4">https://apps.apple.com/us/app/pandadoc-track-esign-docs/id1210645479?uo=4</a>
**App Version:** 1.49.0
**Seller:** Quote Roller Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/quote-roller-inc/id873627169?uo=4">© Quote Roller Inc.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/04/17/88/04178800-604c-4b41-7951-e151db5e712b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966999-15ba3980-a8be-11ea-8c4c-c710df1294fd.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966999-15ba3980-a8be-11ea-8c4c-c710df1294fd.png)
https://user-images.githubusercontent.com/2068130/83966999-15ba3980-a8be-11ea-8c4c-c710df1294fd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83967008-24085580-a8be-11ea-8805-35e33d470d7d.png
