### ISSUE TITLE
KOHLER Konnect

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10882]
**App Name:** KOHLER Konnect
**Bundle ID:** com.kohler.hermoth
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1332560665">1332560665</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/kohler-konnect/id1332560665?uo=4">https://apps.apple.com/us/app/kohler-konnect/id1332560665?uo=4</a>
**App Version:** 1.7.4
**Seller:** Kohler Co.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kohler-co/id433969499?uo=4">© Kohler Co.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/eb/08/f0/eb08f056-fd59-4c28-5269-627781ae043e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974443-9ba1a900-a8ed-11ea-8aa7-55ce7488d67e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974443-9ba1a900-a8ed-11ea-8aa7-55ce7488d67e.png)
https://user-images.githubusercontent.com/2068130/83974443-9ba1a900-a8ed-11ea-8aa7-55ce7488d67e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83974453-aa885b80-a8ed-11ea-90e1-f59fa515a0e3.png
