### ISSUE TITLE
Sex Tracker by Nice

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10886]
**App Name:** Sex Tracker by Nice
**Bundle ID:** com.scottjulian.naughtyapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1107291612">1107291612</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sex-tracker-by-nice/id1107291612?uo=4">https://apps.apple.com/us/app/sex-tracker-by-nice/id1107291612?uo=4</a>
**App Version:** 4.1.0
**Seller:** Scott Julian
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/scott-julian/id1107291611?uo=4">© Scott Julian</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/6e/1e/a8/6e1ea8aa-da2d-d2bf-cd7c-3fa7db450222/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83967083-b6a8f480-a8be-11ea-9890-87877f792b17.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83967083-b6a8f480-a8be-11ea-9890-87877f792b17.png)
https://user-images.githubusercontent.com/2068130/83967083-b6a8f480-a8be-11ea-9890-87877f792b17.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83967091-c58fa700-a8be-11ea-9632-8de311885e22.png
