### ISSUE TITLE
HockeyTracker

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10885]
**App Name:** HockeyTracker
**Bundle ID:** com.myndarc.HockeyTracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1297971760">1297971760</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hockeytracker/id1297971760?uo=4">https://apps.apple.com/us/app/hockeytracker/id1297971760?uo=4</a>
**App Version:** 2.9.2
**Seller:** MyndArc, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/myndarc-llc/id979588062?uo=4">© MyndArc, LLC</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/39/1f/6c/391f6ce6-1c7a-5f7d-f06e-52e5ec4624e7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974266-7c564c00-a8ec-11ea-995e-ccb8c3a42cf5.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974266-7c564c00-a8ec-11ea-995e-ccb8c3a42cf5.png)
https://user-images.githubusercontent.com/2068130/83974266-7c564c00-a8ec-11ea-995e-ccb8c3a42cf5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83974275-8aa46800-a8ec-11ea-8a7e-c398bd30b8dd.png
