### ISSUE TITLE
Lambus | Travel Planner

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10887]
**App Name:** Lambus | Travel Planner
**Bundle ID:** io.lambus.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1446178879">1446178879</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/lambus-travel-planner/id1446178879?uo=4">https://apps.apple.com/us/app/lambus-travel-planner/id1446178879?uo=4</a>
**App Version:** 3.4.0
**Seller:** Lambus GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lambus-gmbh/id497336140?uo=4">© Lambus GmbH</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/ca/00/74/ca00745e-dcb6-4339-f945-cf03d063b380/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84351204-266af800-abbb-11ea-916d-407f31f1c823.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84351204-266af800-abbb-11ea-916d-407f31f1c823.png)
https://user-images.githubusercontent.com/2068130/84351204-266af800-abbb-11ea-916d-407f31f1c823.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84351228-371b6e00-abbb-11ea-8ee9-a1011ffd4fc3.png
