### ISSUE TITLE
Tap Forms Organizer

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10880]
**App Name:** Tap Forms Organizer
**Bundle ID:** com.clickspace.tapforms
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=291405311">291405311</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tap-forms-organizer/id291405311?uo=4">https://apps.apple.com/us/app/tap-forms-organizer/id291405311?uo=4</a>
**App Version:** 4.0.9
**Seller:** Tap Zapp Software Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tap-zapp-software-inc/id291405314?uo=4">© Tap Zapp Software Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/77/45/b1/7745b1a9-8b4a-7b83-9f87-cf54462903b0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83967297-6763c380-a8c0-11ea-929d-89ef66fefdeb.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83967297-6763c380-a8c0-11ea-929d-89ef66fefdeb.png)
https://user-images.githubusercontent.com/2068130/83967297-6763c380-a8c0-11ea-929d-89ef66fefdeb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83967303-75b1df80-a8c0-11ea-8682-93b05c6d2225.png
