### ISSUE TITLE
Comet for reddit

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10889]
**App Name:** Comet for reddit
**Bundle ID:** AaronKovacs.Comet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1146204813">1146204813</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/comet-for-reddit/id1146204813?uo=4">https://apps.apple.com/us/app/comet-for-reddit/id1146204813?uo=4</a>
**App Version:** 2.1.0
**Seller:** Aaron Kovacs
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/aaron-kovacs/id1071984190?uo=4">© Aaron Kovacs</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/5d/72/d9/5d72d9b6-8c02-0550-eebc-533fdb5eb4aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84350455-95dfe800-abb9-11ea-8d82-2d380d116ea8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84350455-95dfe800-abb9-11ea-8d82-2d380d116ea8.png)
https://user-images.githubusercontent.com/2068130/84350455-95dfe800-abb9-11ea-8d82-2d380d116ea8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84350486-a5f7c780-abb9-11ea-99ea-37640afd785b.png
