### ISSUE TITLE
PillPack – Pharmacy Simplified

### ISSUE THREAD

**Issue by Archigos** [glasklart/hd#10895]
**App Name:** PillPack – Pharmacy Simplified
**Bundle ID:** com.pillpack.reminders
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955593437">955593437</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pillpack-pharmacy-simplified/id955593437?uo=4">https://apps.apple.com/us/app/pillpack-pharmacy-simplified/id955593437?uo=4</a>
**App Version:** 6.4.12
**Seller:** PILLPACK INC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/pillpack-inc/id955593436?uo=4">© PillPack, Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/80/1e/5a/801e5a8d-b724-37ae-53f2-8fbad5b553b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966829-eb1bb100-a8bc-11ea-8ae3-89fe54537aee.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966829-eb1bb100-a8bc-11ea-8ae3-89fe54537aee.png)
https://user-images.githubusercontent.com/2068130/83966829-eb1bb100-a8bc-11ea-8ae3-89fe54537aee.png
--- ---
https://user-images.githubusercontent.com/2068130/83966840-fa026380-a8bc-11ea-8902-7f9e64567455.png
