### ISSUE TITLE
HitLyst for Twitter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10891]
**App Name:** HitLyst for Twitter
**Bundle ID:** com.hitlyst.HitLyst
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1486082689">1486082689</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hitlyst-for-twitter/id1486082689?uo=4">https://apps.apple.com/us/app/hitlyst-for-twitter/id1486082689?uo=4</a>
**App Version:** 1.0.2
**Seller:** Srinivas Sri
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/srinivas-sri/id1265000864?uo=4">© Srinivas Sri</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/76/52/0f/76520f5d-ca45-de69-e6d7-f85f98e86728/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84361600-33dcae00-abcc-11ea-92c1-6fc6a298def9.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84361600-33dcae00-abcc-11ea-92c1-6fc6a298def9.png)
https://user-images.githubusercontent.com/2068130/84361600-33dcae00-abcc-11ea-92c1-6fc6a298def9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84361651-435bf700-abcc-11ea-8e95-5da33f7053d2.png
