### ISSUE TITLE
Genghis Grill

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10890]
**App Name:** Genghis Grill
**Bundle ID:** com.genghisgrill.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1438081841">1438081841</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/genghis-grill/id1438081841?uo=4">https://apps.apple.com/us/app/genghis-grill/id1438081841?uo=4</a>
**App Version:** 1.1
**Seller:** Mongolian Concepts, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/genghis-grill/id1438081750?uo=4">© Genghis Grill</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/64/54/53/64545316-3519-a647-61ea-59536d85604f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84350031-dee36c80-abb8-11ea-9e99-2efb81ff9df3.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84350031-dee36c80-abb8-11ea-9e99-2efb81ff9df3.png)
https://user-images.githubusercontent.com/2068130/84350031-dee36c80-abb8-11ea-9e99-2efb81ff9df3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84350064-f0c50f80-abb8-11ea-88c2-6f383f8f4726.png
