### ISSUE TITLE
MobileFamilyTree 9

### ISSUE THREAD

**Issue by Archigos** [glasklart/hd#10898]
**App Name:** MobileFamilyTree 9
**Bundle ID:** com.syniumsoftware.mobilefamilytree9
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1458867068">1458867068</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mobilefamilytree-9/id1458867068?uo=4">https://apps.apple.com/us/app/mobilefamilytree-9/id1458867068?uo=4</a>
**App Version:** 9.0.12
**Seller:** Synium Software GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/synium-software-gmbh/id284959715?uo=4">© Synium Software GmbH</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/35/20/f7/3520f73d-e81e-868a-295f-0c5a36f689e3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966525-ebb34800-a8ba-11ea-8015-4a9c1376482e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966525-ebb34800-a8ba-11ea-8015-4a9c1376482e.png)
https://user-images.githubusercontent.com/2068130/83966525-ebb34800-a8ba-11ea-8015-4a9c1376482e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83966537-fa016400-a8ba-11ea-9e86-9cdb46f2ab2a.png
