### ISSUE TITLE
Emby

### ISSUE THREAD

**Issue by Archigos** [glasklart/hd#10897]
**App Name:** Emby
**Bundle ID:** com.emby.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=992180193">992180193</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/emby/id992180193?uo=4">https://apps.apple.com/us/app/emby/id992180193?uo=4</a>
**App Version:** 1.9.7
**Seller:** Embi LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/emby-media/id992180192?uo=4">© Emby Media</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/6d/05/c3/6d05c36a-da9e-0bf3-79db-528434adaac1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84349249-2ff26100-abb7-11ea-9d04-5f1baabec432.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84349249-2ff26100-abb7-11ea-9d04-5f1baabec432.png)
https://user-images.githubusercontent.com/2068130/84349249-2ff26100-abb7-11ea-9d04-5f1baabec432.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84349280-41d40400-abb7-11ea-9772-b69b0310a00c.png
