### ISSUE TITLE
Renpho

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10896]
**App Name:** Renpho
**Bundle ID:** com.qnniu.renpho
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1219889310">1219889310</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/renpho/id1219889310?uo=4">https://apps.apple.com/us/app/renpho/id1219889310?uo=4</a>
**App Version:** 3.4.1
**Seller:** Joicom corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/joicom-corporation/id1366112776?uo=4">© Joicom corporation</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/f3/81/71/f38171d0-f5a3-f892-1e2e-02857a888965/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966614-72682500-a8bb-11ea-8da2-245c1132be68.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966614-72682500-a8bb-11ea-8da2-245c1132be68.png)
https://user-images.githubusercontent.com/2068130/83966614-72682500-a8bb-11ea-8da2-245c1132be68.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83966625-814ed780-a8bb-11ea-8a2a-83cda8ddcd93.png
