### ISSUE TITLE
LYNE

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10892]
**App Name:** LYNE
**Bundle ID:** com.thomasbowker.lynerelease
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=731753333">731753333</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/lyne/id731753333?uo=4">https://apps.apple.com/us/app/lyne/id731753333?uo=4</a>
**App Version:** 1.3.2
**Seller:** Thomas Bowker
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/thomas-bowker/id569404281?uo=4">© Thomas Bowker</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/60/d8/c2/60d8c293-a4a6-9704-894d-6ba6a718b7a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84349611-f3733500-abb7-11ea-8ba2-bc79378f7799.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84349611-f3733500-abb7-11ea-8ba2-bc79378f7799.png)
https://user-images.githubusercontent.com/2068130/84349611-f3733500-abb7-11ea-8ba2-bc79378f7799.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84349637-02f27e00-abb8-11ea-831d-28c452171e56.png
