### ISSUE TITLE
Sevn

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10893]
**App Name:** Sevn
**Bundle ID:** be.nextapps.paletto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1179097907">1179097907</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sevn/id1179097907?uo=4">https://apps.apple.com/us/app/sevn/id1179097907?uo=4</a>
**App Version:** 2.0.2
**Seller:** Next Apps BVBA
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/next-apps-bvba/id452162279?uo=4">© Next Apps BVBA</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/16/31/a7/1631a7ae-65f5-3d4c-60c0-2d14540f8fc6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86530963-a6843500-bebd-11ea-9a20-cfdf53fd1316.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86530963-a6843500-bebd-11ea-9a20-cfdf53fd1316.png)
https://user-images.githubusercontent.com/2068130/86530963-a6843500-bebd-11ea-9a20-cfdf53fd1316.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86530968-b69c1480-bebd-11ea-9a5e-d72902d0ade2.png
