### ISSUE TITLE
HUAWEI HiLink (Mobile WiFi)

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10899]
**App Name:** HUAWEI HiLink (Mobile WiFi)
**Bundle ID:** com.huawei.MobileControl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=546979875">546979875</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/huawei-hilink-mobile-wifi/id546979875?uo=4">https://apps.apple.com/us/app/huawei-hilink-mobile-wifi/id546979875?uo=4</a>
**App Version:** 9.0.1.309
**Seller:** Huawei Device Co,. LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/huawei-device-co-ltd/id1014329786?uo=4">© Huawei Device Co,. LTD</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/a1/14/99/a1149923-793e-a25b-5f93-b72d16ba044d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966693-f9b59880-a8bb-11ea-84d6-9be364446697.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966693-f9b59880-a8bb-11ea-84d6-9be364446697.png)
https://user-images.githubusercontent.com/2068130/83966693-f9b59880-a8bb-11ea-84d6-9be364446697.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83966702-0b973b80-a8bc-11ea-8569-5be33f7e5e0b.png
