### ISSUE TITLE
JD Sports

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10908]
**App Name:** JD Sports
**Bundle ID:** com.jd.jdsports
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=690602681">690602681</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/jd-sports/id690602681?uo=4">https://apps.apple.com/gb/app/jd-sports/id690602681?uo=4</a>
**App Version:** 6.6.3
**Seller:** JD Sports Fashion Plc.
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/jd-sports-fashion-plc/id690602684?uo=4">© JD Sports Fashion Plc</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/99/d8/61/99d8619e-3193-0bf0-e280-fef4c6af35a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84597230-de6dfe80-ae62-11ea-87e4-5732fdd835cc.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84597230-de6dfe80-ae62-11ea-87e4-5732fdd835cc.png)
https://user-images.githubusercontent.com/2068130/84597230-de6dfe80-ae62-11ea-87e4-5732fdd835cc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84597237-ef1e7480-ae62-11ea-8cf1-0a2cc697d477.png
