### ISSUE TITLE
Omlet Arcade: Livestream Games

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10900]
**App Name:** Omlet Arcade: Livestream Games
**Bundle ID:** mobisocial.arcade
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1152185878">1152185878</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/omlet-arcade-livestream-games/id1152185878?uo=4">https://apps.apple.com/us/app/omlet-arcade-livestream-games/id1152185878?uo=4</a>
**App Version:** 1.66.0
**Seller:** Mobisocial Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mobisocial-inc/id586030313?uo=4">© Mobisocial, Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/e4/29/5d/e4295df5-08cd-6752-439f-e30262fe40d0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83538599-50a32280-a4f6-11ea-8767-19891b44313e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83538599-50a32280-a4f6-11ea-8767-19891b44313e.png)
https://user-images.githubusercontent.com/2068130/83538599-50a32280-a4f6-11ea-8767-19891b44313e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83538644-5f89d500-a4f6-11ea-898b-5396b5bfcf78.png
