### ISSUE TITLE
Handy-Signatur App

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#10902]
**App Name:** Handy-Signatur App
**Bundle ID:** at.a-trust.Handy-Signatur
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1016945247">1016945247</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/handy-signatur-app/id1016945247?uo=4">https://apps.apple.com/us/app/handy-signatur-app/id1016945247?uo=4</a>
**App Version:** 3.0.2
**Seller:** A-Trust Gesellschaft fur Sicherheitssysteme im elektronischen Datenverkehr GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/a-trust-gmbh/id460404403?uo=4">© A-Trust GmbH</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/39/fe/29/39fe290e-579f-199b-1446-aca1b3513018/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83532790-08cccd00-a4ef-11ea-893a-353036ba9317.png)

**Comment by DerDoktor** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/8452321/83450366-69a7c700-a455-11ea-815f-b03d09ce768b.png)

Source:
https://user-images.githubusercontent.com/8452321/83450454-922fc100-a455-11ea-8bc9-eb1405d6eb11.png

**Comment by dreamnet** [comment]
@DerDoktor Good, but I think it looks better when inverted:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83532790-08cccd00-a4ef-11ea-893a-353036ba9317.png)
https://user-images.githubusercontent.com/2068130/83532790-08cccd00-a4ef-11ea-893a-353036ba9317.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83532838-1b470680-a4ef-11ea-9b54-c5ebbd081b12.png
