### ISSUE TITLE
PayByPhone - Parken per Handy

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10901]
**App Name:** PayByPhone - Parken per Handy
**Bundle ID:** com.sunhilltechnologies.TraviPay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=907171470">907171470</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/paybyphone-parken-per-handy/id907171470?uo=4">https://apps.apple.com/de/app/paybyphone-parken-per-handy/id907171470?uo=4</a>
**App Version:** 9.1.4
**Seller:** sunhill technologies GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/sunhill-technologies-gmbh/id417864778?uo=4">© sunhill technologies GmbH</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/9f/25/41/9f254106-58cb-f7e9-834b-547e1ca7af33/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83537494-e63db280-a4f4-11ea-98f9-2128f1b50bde.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83537494-e63db280-a4f4-11ea-98f9-2128f1b50bde.png)
https://user-images.githubusercontent.com/2068130/83537494-e63db280-a4f4-11ea-98f9-2128f1b50bde.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83537537-f81f5580-a4f4-11ea-931f-1aee91eebfda.png
