### ISSUE TITLE
World Clock — Time Zone Widget

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10909]
**App Name:** World Clock — Time Zone Widget
**Bundle ID:** com.overdesigned.WorldClock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=956377119">956377119</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/world-clock-time-zone-widget/id956377119?uo=4">https://apps.apple.com/us/app/world-clock-time-zone-widget/id956377119?uo=4</a>
**App Version:** 1.7.2
**Seller:** Overdesigned, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/overdesigned-llc/id914665832?uo=4">© Overdesigned, LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/b7/6c/8e/b76c8ed3-11f0-b05d-54f2-5160f9f1245e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84596932-dca33b80-ae60-11ea-80cb-cf18001325e6.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84596932-dca33b80-ae60-11ea-80cb-cf18001325e6.png)
https://user-images.githubusercontent.com/2068130/84596932-dca33b80-ae60-11ea-80cb-cf18001325e6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84596950-ed53b180-ae60-11ea-9cb0-1731ca818362.png
