### ISSUE TITLE
Streamlabs Deck

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#10904]
**App Name:** Streamlabs Deck
**Bundle ID:** com.streamlabs.slobsrc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1476615877">1476615877</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/streamlabs-deck/id1476615877?uo=4">https://apps.apple.com/us/app/streamlabs-deck/id1476615877?uo=4</a>
**App Version:** 3.1.7
**Seller:** Streamlabs LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/streamlabs/id1296663686?uo=4">© Streamlabs</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/ce/08/da/ce08da09-55fc-5cd7-79bf-8408517854ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85230380-de847600-b3ef-11ea-9c5f-0d7a88db36fd.png)

**Comment by DerDoktor** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/8452321/83451633-98bf3800-a457-11ea-9f2f-4d7e7fabbed9.png)

Source:
https://user-images.githubusercontent.com/8452321/83451691-ad033500-a457-11ea-83dd-714bf4fb0bc8.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85230380-de847600-b3ef-11ea-9c5f-0d7a88db36fd.png)
https://user-images.githubusercontent.com/2068130/85230380-de847600-b3ef-11ea-9c5f-0d7a88db36fd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85230384-ee03bf00-b3ef-11ea-8773-0a310c221a7b.png
