### ISSUE TITLE
HBO Max: Stream TV & Movies

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10907]
**App Name:** HBO Max: Stream TV & Movies
**Bundle ID:** com.hbo.hbonow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=971265422">971265422</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hbo-max-stream-tv-movies/id971265422?uo=4">https://apps.apple.com/us/app/hbo-max-stream-tv-movies/id971265422?uo=4</a>
**App Version:** 50.0.1
**Seller:** WarnerMedia Direct, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/warnermedia/id1514826633?uo=4">© WarnerMedia</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/43/4f/8e/434f8e52-9f62-e70b-0325-26d947a69b08/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966395-4dbf7d80-a8ba-11ea-901f-093ecde8c162.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83966395-4dbf7d80-a8ba-11ea-901f-093ecde8c162.png)
https://user-images.githubusercontent.com/2068130/83966395-4dbf7d80-a8ba-11ea-901f-093ecde8c162.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83966412-5dd75d00-a8ba-11ea-9d52-194a237ccb6e.png
