### ISSUE TITLE
Flow Free: Hexes

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#10905]
**App Name:** Flow Free: Hexes
**Bundle ID:** com.bigduckgames.flow.hexes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1145541321">1145541321</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/flow-free-hexes/id1145541321?uo=4">https://apps.apple.com/us/app/flow-free-hexes/id1145541321?uo=4</a>
**App Version:** 2.2
**Seller:** Big Duck Games LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/big-duck-games-llc/id435664937?uo=4">© Big Duck Games LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/a3/ab/c9/a3abc99a-d80a-16a5-9cb6-0beef8298346/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/8452321/83451809-dde36a00-a457-11ea-9f8f-9c08f502d632.png)

**Comment by DerDoktor** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/8452321/83451809-dde36a00-a457-11ea-9f8f-9c08f502d632.png)

Source:
https://user-images.githubusercontent.com/8452321/83451843-ecca1c80-a457-11ea-9c49-7bd3a42c6d88.png

**Comment by EmpDns** [comment]
here if you're looking for the file:

https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.bigduckgames.flow.hexes-large.png
