### ISSUE TITLE
Nuki Smart Lock

### ISSUE THREAD

**Issue by ThorstenG1974** [glasklart/hd#10906]
**App Name:** Nuki Smart Lock
**Bundle ID:** io.nuki.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1044998081">1044998081</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/nuki-smart-lock/id1044998081?uo=4">https://apps.apple.com/us/app/nuki-smart-lock/id1044998081?uo=4</a>
**App Version:** 2.6.3
**Seller:** Nuki Home Solutions GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nuki-home-solutions-gmbh/id966180578?uo=4">© Nuki Home Solutions GmbH</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/14/87/a3/1487a3f0-bf11-ab1c-9414-628770441797/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83534739-842f7e00-a4f1-11ea-9224-7656605bf6df.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83534739-842f7e00-a4f1-11ea-9224-7656605bf6df.png)
https://user-images.githubusercontent.com/2068130/83534739-842f7e00-a4f1-11ea-9224-7656605bf6df.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83534802-93aec700-a4f1-11ea-95be-41cc6e01bf79.png
