### ISSUE TITLE
iWish - Life Goals, Wishlist, Bucket List

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10918]
**App Name:** iWish - Life Goals, Wishlist, Bucket List
**Bundle ID:** com.gmail.firebird0001
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=558579262">558579262</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/iwish-life-goals-wishlist-bucket-list/id558579262?uo=4">https://apps.apple.com/us/app/iwish-life-goals-wishlist-bucket-list/id558579262?uo=4</a>
**App Version:** 2.3.4
**Seller:** Maryna Furmanchuk
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/highdream/id558579265?uo=4">© HighDream</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple71/v4/62/b4/68/62b468c6-d51d-2b94-5a11-564f444b6254/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84328792-48e11f00-ab83-11ea-8bdd-8cde971f2142.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84328792-48e11f00-ab83-11ea-8bdd-8cde971f2142.png)
https://user-images.githubusercontent.com/2068130/84328792-48e11f00-ab83-11ea-8bdd-8cde971f2142.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84328819-5ac2c200-ab83-11ea-9ecf-4016162872cd.png
