### ISSUE TITLE
TextExpander + Keyboard

### ISSUE THREAD

**Issue by Archigos** [glasklart/hd#10912]
**App Name:** TextExpander + Keyboard
**Bundle ID:** com.smileonmymac.tetouch4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1075927186">1075927186</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/textexpander-keyboard/id1075927186?uo=4">https://apps.apple.com/us/app/textexpander-keyboard/id1075927186?uo=4</a>
**App Version:** 4.6.1
**Seller:** SmileOnMyMac, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/smileonmymac-llc/id326180693?uo=4">© SmileOnMyMac, LLC</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/53/88/61/538861bf-f009-ff63-ffd4-0d083653f293/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974190-b541f100-a8eb-11ea-87b9-277e161aa24f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974190-b541f100-a8eb-11ea-87b9-277e161aa24f.png)
https://user-images.githubusercontent.com/2068130/83974190-b541f100-a8eb-11ea-87b9-277e161aa24f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83974194-c428a380-a8eb-11ea-9185-32288717e12a.png
