### ISSUE TITLE
World Clock.

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10910]
**App Name:** World Clock.
**Bundle ID:** com.worldclock.timewidget
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1453369651">1453369651</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/world-clock/id1453369651?uo=4">https://apps.apple.com/us/app/world-clock/id1453369651?uo=4</a>
**App Version:** 1.2
**Seller:** Scanner App, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/scannerapp/id1220194001?uo=4">© ScannerApp</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/d7/be/d1/d7bed1b2-86c1-42d3-1d89-4e52efdfe28b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84348811-3502e080-abb6-11ea-8a79-16f113f2024a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84348811-3502e080-abb6-11ea-8a79-16f113f2024a.png)
https://user-images.githubusercontent.com/2068130/84348811-3502e080-abb6-11ea-8a79-16f113f2024a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84348834-477d1a00-abb6-11ea-95cb-520e1804c6ba.png
