### ISSUE TITLE
Unlox

### ISSUE THREAD

**Issue by Archigos** [glasklart/hd#10913]
**App Name:** Unlox
**Bundle ID:** com.kanecheshire.macID-iOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1313188193">1313188193</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/unlox/id1313188193?uo=4">https://apps.apple.com/us/app/unlox/id1313188193?uo=4</a>
**App Version:** 3.0.4
**Seller:** Kane Cheshire
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kane-cheshire/id948478739?uo=4">© Kane Cheshire</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/aa/44/e5/aa44e558-650f-b0de-fa8a-2d381bf6997f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974133-406eb700-a8eb-11ea-9c4a-26f10a142230.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83974133-406eb700-a8eb-11ea-9c4a-26f10a142230.png)
https://user-images.githubusercontent.com/2068130/83974133-406eb700-a8eb-11ea-9c4a-26f10a142230.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83974145-4fee0000-a8eb-11ea-9cdf-23512654a909.png
