### ISSUE TITLE
Intact Insurance

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10917]
**App Name:** Intact Insurance
**Bundle ID:** com.intact
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1363223619">1363223619</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/intact-insurance/id1363223619?uo=4">https://apps.apple.com/us/app/intact-insurance/id1363223619?uo=4</a>
**App Version:** 3.32.1
**Seller:** Intact Insurance Company
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/intact-insurance/id1161513439?uo=4">© Intact Insurance</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/15/1f/91/151f9193-ed00-29f2-5a3b-b4237c9d0865/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84328968-c60c9400-ab83-11ea-959f-e6e50662bc95.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84328968-c60c9400-ab83-11ea-959f-e6e50662bc95.png)
https://user-images.githubusercontent.com/2068130/84328968-c60c9400-ab83-11ea-959f-e6e50662bc95.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84329002-d4f34680-ab83-11ea-99ed-30fdc797b2b7.png
