### ISSUE TITLE
Wayfair – Shop All Things Home

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10919]
**App Name:** Wayfair – Shop All Things Home
**Bundle ID:** com.wayfair.WayfairApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=836767708">836767708</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wayfair-shop-all-things-home/id836767708?uo=4">https://apps.apple.com/us/app/wayfair-shop-all-things-home/id836767708?uo=4</a>
**App Version:** 5.48
**Seller:** Wayfair LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wayfair-llc/id525522335?uo=4">© Wayfair LLC</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/25/d1/bf/25d1bf6d-6f6c-0dcc-57e4-909b9b0db0fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84347915-084dc980-abb4-11ea-83c0-1eb4b124bb67.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84347915-084dc980-abb4-11ea-83c0-1eb4b124bb67.png)
https://user-images.githubusercontent.com/2068130/84347915-084dc980-abb4-11ea-83c0-1eb4b124bb67.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84347936-1a2f6c80-abb4-11ea-8a66-eaa54bc134ae.png
