### ISSUE TITLE
Calendly Mobile

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10915]
**App Name:** Calendly Mobile
**Bundle ID:** com.calendly.Calendly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1451094657">1451094657</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/calendly-mobile/id1451094657?uo=4">https://apps.apple.com/us/app/calendly-mobile/id1451094657?uo=4</a>
**App Version:** 1.1.2
**Seller:** Calendly, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/calendly/id1447404048?uo=4">© Calendly</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/73/c6/3a/73c63a3b-c8b7-eea7-3a7b-14c54bcdc9f8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84348246-c6715300-abb4-11ea-9c35-11d4dc910b9a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84348246-c6715300-abb4-11ea-9c35-11d4dc910b9a.png)
https://user-images.githubusercontent.com/2068130/84348246-c6715300-abb4-11ea-9c35-11d4dc910b9a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84348272-d852f600-abb4-11ea-8fef-bb73756f5a07.png
