### ISSUE TITLE
UniFi Network

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10914]
**App Name:** UniFi Network
**Bundle ID:** com.ubnt.unifiac
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1057750338">1057750338</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/unifi-network/id1057750338?uo=4">https://apps.apple.com/us/app/unifi-network/id1057750338?uo=4</a>
**App Version:** 5.4.3
**Seller:** Ubiquiti Networks, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ubiquiti-networks/id683620863?uo=4">© Ubiquiti Networks</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/a4/0d/7a/a40d7ac2-bdb1-ad93-0f93-f8ffc71a1500/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84329365-d8d39880-ab84-11ea-9eb2-969a70fedc01.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84329365-d8d39880-ab84-11ea-9eb2-969a70fedc01.png)
https://user-images.githubusercontent.com/2068130/84329365-d8d39880-ab84-11ea-9eb2-969a70fedc01.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84329404-e8eb7800-ab84-11ea-9565-b4ee665177cc.png
