### ISSUE TITLE
Blokada

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10911]
**App Name:** Blokada
**Bundle ID:** net.blocka.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1508341781">1508341781</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/blokada/id1508341781?uo=4">https://apps.apple.com/us/app/blokada/id1508341781?uo=4</a>
**App Version:** 5.0.0
**Seller:** Blocka AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/blocka-ab/id1502773802?uo=4">© Blocka AB</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/c9/07/6c/c9076c94-8c43-e194-5b8e-3514117a0ad5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83975646-1de19b80-a8f5-11ea-863a-9d048745bafd.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83975646-1de19b80-a8f5-11ea-863a-9d048745bafd.png)
https://user-images.githubusercontent.com/2068130/83975646-1de19b80-a8f5-11ea-863a-9d048745bafd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83975652-2c2fb780-a8f5-11ea-9e2c-817d1d468a82.png
