### ISSUE TITLE
WooCommerce

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10916]
**App Name:** WooCommerce
**Bundle ID:** com.automattic.woocommerce
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1389130815">1389130815</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/woocommerce/id1389130815?uo=4">https://apps.apple.com/us/app/woocommerce/id1389130815?uo=4</a>
**App Version:** 4.3
**Seller:** Automattic, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/automattic/id335703883?uo=4">© Automattic</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/d8/9f/1d/d89f1d57-e82b-803b-ba1f-901af9835c65/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84329168-3e735500-ab84-11ea-8ace-ff7cfb60d0ba.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84329168-3e735500-ab84-11ea-8ace-ff7cfb60d0ba.png)
https://user-images.githubusercontent.com/2068130/84329168-3e735500-ab84-11ea-8ace-ff7cfb60d0ba.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84329184-4df29e00-ab84-11ea-911b-6e99f08976a3.png
