### ISSUE TITLE
GIF Maker - ImgPlay

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10921]
**App Name:** GIF Maker - ImgPlay
**Bundle ID:** me.imgbase.imgplay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989843523">989843523</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gif-maker-imgplay/id989843523?uo=4">https://apps.apple.com/us/app/gif-maker-imgplay/id989843523?uo=4</a>
**App Version:** 5.5.3
**Seller:** ImgBase, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/imgbase-inc/id903692682?uo=4">© ImgBase, Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/0e/76/eb/0e76eb4b-ef74-e04f-1116-0c72af15c9ed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84328344-01a65e80-ab82-11ea-8040-3d488ea0b605.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84328344-01a65e80-ab82-11ea-8040-3d488ea0b605.png)
https://user-images.githubusercontent.com/2068130/84328344-01a65e80-ab82-11ea-8040-3d488ea0b605.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84328371-1125a780-ab82-11ea-8dcb-2de820075df7.png
