### ISSUE TITLE
My AMP

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10925]
**App Name:** My AMP
**Bundle ID:** au.com.amp.myportfolio.PROD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=763144972">763144972</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/my-amp/id763144972?uo=4">https://apps.apple.com/us/app/my-amp/id763144972?uo=4</a>
**App Version:** 7.1.0
**Seller:** AMP Services Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/amp-limited/id382797555?uo=4">© AMP Limited</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/92/06/4c/92064ce4-a9a2-672b-8f3f-1511ef4dec52/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84590646-ab167a00-ae38-11ea-8834-cb8e4a83ba9f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84590646-ab167a00-ae38-11ea-8834-cb8e4a83ba9f.png)
https://user-images.githubusercontent.com/2068130/84590646-ab167a00-ae38-11ea-8834-cb8e4a83ba9f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84590659-bbc6f000-ae38-11ea-9e87-6e8f0e869306.png
