### ISSUE TITLE
Hoopla Digital

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10923]
**App Name:** Hoopla Digital
**Bundle ID:** com.hoopladigital.hoopla
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=580643740">580643740</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hoopla-digital/id580643740?uo=4">https://apps.apple.com/us/app/hoopla-digital/id580643740?uo=4</a>
**App Version:** 4.32
**Seller:** Midwest Tape LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/midwest-tape-llc/id580643743?uo=4">© Midwest Tape, LLC</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/a3/10/ed/a310edf4-e66c-251f-6762-66a1d8e5ac25/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84327846-b3dd2680-ab80-11ea-9af8-09ceea40be4f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84327846-b3dd2680-ab80-11ea-9af8-09ceea40be4f.png)
https://user-images.githubusercontent.com/2068130/84327846-b3dd2680-ab80-11ea-9af8-09ceea40be4f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84327872-c3f50600-ab80-11ea-8f49-f328c3981f92.png
