### ISSUE TITLE
iSmartgate Access

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10920]
**App Name:** iSmartgate Access
**Bundle ID:** com.gogogate.ismartgateaccess
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1277087476">1277087476</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ismartgate-access/id1277087476?uo=4">https://apps.apple.com/us/app/ismartgate-access/id1277087476?uo=4</a>
**App Version:** 1.7
**Seller:** Joan  Llopart Masana
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/v2fe/id525277631?uo=4">© V2FE</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/ac/73/4a/ac734ad4-0303-9cfc-779b-f02f1aa3a175/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84328613-bb9dca80-ab82-11ea-86b2-d1e1bcd26346.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84328613-bb9dca80-ab82-11ea-86b2-d1e1bcd26346.png)
https://user-images.githubusercontent.com/2068130/84328613-bb9dca80-ab82-11ea-86b2-d1e1bcd26346.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84328631-cce6d700-ab82-11ea-86fd-a969dc07571a.png
