### ISSUE TITLE
Sonos

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10924]
**App Name:** Sonos
**Bundle ID:** com.sonos.SonosController2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1488977981">1488977981</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sonos/id1488977981?uo=4">https://apps.apple.com/us/app/sonos/id1488977981?uo=4</a>
**App Version:** 12.0
**Seller:** Sonos, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sonos-inc/id293523034?uo=4">© Sonos, Inc.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/3d/52/38/3d5238e1-d579-d4e8-b304-a5435967e3a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84327414-8a6fcb00-ab7f-11ea-809a-fcdc7f22608b.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84327414-8a6fcb00-ab7f-11ea-809a-fcdc7f22608b.png)
https://user-images.githubusercontent.com/2068130/84327414-8a6fcb00-ab7f-11ea-809a-fcdc7f22608b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84327448-9eb3c800-ab7f-11ea-9889-46b31bdf7c57.png
