### ISSUE TITLE
Anytime Fitness

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10926]
**App Name:** Anytime Fitness
**Bundle ID:** com.anytimefitness.AnytimeFitness
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914150199">914150199</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/anytime-fitness/id914150199?uo=4">https://apps.apple.com/us/app/anytime-fitness/id914150199?uo=4</a>
**App Version:** 2.11.1
**Seller:** Anytime Fitness, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/anytime-fitness-llc/id307386667?uo=4">© Anytime Fitness, LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/3a/06/c5/3a06c5ad-a784-8086-68a3-b5bd4be17231/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84326368-07e60c00-ab7d-11ea-9a86-4ce7cc7ccdea.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84326368-07e60c00-ab7d-11ea-9a86-4ce7cc7ccdea.png)
https://user-images.githubusercontent.com/2068130/84326368-07e60c00-ab7d-11ea-9a86-4ce7cc7ccdea.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84326402-17655500-ab7d-11ea-9b40-95d7e2db884f.png
