### ISSUE TITLE
Xplor Home

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10929]
**App Name:** Xplor Home
**Bundle ID:** com.xplor.home
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1479657396">1479657396</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/xplor-home/id1479657396?uo=4">https://apps.apple.com/us/app/xplor-home/id1479657396?uo=4</a>
**App Version:** 1.1.1
**Seller:** MyXplor Pty Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/xplor/id1093323821?uo=4">© Xplor</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/7a/36/ac/7a36ac62-7a71-7544-bc55-57c84d3b218e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84359450-f296cf00-abc8-11ea-8725-7b374c475d04.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84359450-f296cf00-abc8-11ea-8725-7b374c475d04.png)
https://user-images.githubusercontent.com/2068130/84359450-f296cf00-abc8-11ea-8725-7b374c475d04.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84359485-02161800-abc9-11ea-8119-5eff5c9e6043.png
