### ISSUE TITLE
CountOnly - Countdown Days App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10922]
**App Name:** CountOnly - Countdown Days App
**Bundle ID:** com.rockmaze.CountOnly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=971737537">971737537</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/countonly-countdown-days-app/id971737537?uo=4">https://apps.apple.com/us/app/countonly-countdown-days-app/id971737537?uo=4</a>
**App Version:** 1.4.1
**Seller:** Cotton.sg Pte. Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cotton-sg/id1088265272?uo=4">© Cotton.sg</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/b3/9a/56/b39a5642-6fb8-da45-7f3d-7148a6a78df0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84328092-4bdb1000-ab81-11ea-855e-65f45e0d9d40.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84328092-4bdb1000-ab81-11ea-855e-65f45e0d9d40.png)
https://user-images.githubusercontent.com/2068130/84328092-4bdb1000-ab81-11ea-855e-65f45e0d9d40.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84328114-5e554980-ab81-11ea-8f51-ea99bc2c291b.png
