### ISSUE TITLE
CommSec Mobile

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10928]
**App Name:** CommSec Mobile
**Bundle ID:** au.com.commbank.commsec
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=880540304">880540304</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/commsec-mobile/id880540304?uo=4">https://apps.apple.com/us/app/commsec-mobile/id880540304?uo=4</a>
**App Version:** 4.21.1
**Seller:** Commonwealth Bank of Australia
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/commonwealth-bank-of-australia/id310251205?uo=4">© Commonwealth Bank of Australia</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/30/e8/5e/30e85ebb-ea61-5818-2792-e951216bf1a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84590773-9edeec80-ae39-11ea-8f63-e1f0a7bacdf4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84590773-9edeec80-ae39-11ea-8f63-e1f0a7bacdf4.png)
https://user-images.githubusercontent.com/2068130/84590773-9edeec80-ae39-11ea-8f63-e1f0a7bacdf4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84590780-b027f900-ae39-11ea-9ffc-fe10193fbcd2.png
