### ISSUE TITLE
The New Yorker Today

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10936]
**App Name:** The New Yorker Today
**Bundle ID:** com.condenet.newyorker.today
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1081530898">1081530898</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/the-new-yorker-today/id1081530898?uo=4">https://apps.apple.com/us/app/the-new-yorker-today/id1081530898?uo=4</a>
**App Version:** 5.1.0
**Seller:** CondeNet
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cond%C3%A9-nast-digital/id289380416?uo=4">© Condé Nast Digital</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/da/93/ba/da93ba6e-7f2c-920e-9ea6-d0651ae48cc5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84355566-1f47e800-abc3-11ea-8429-9bb3c3c91b31.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84355566-1f47e800-abc3-11ea-8429-9bb3c3c91b31.png)
https://user-images.githubusercontent.com/2068130/84355566-1f47e800-abc3-11ea-8429-9bb3c3c91b31.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84355609-2ec73100-abc3-11ea-993b-1620dee58a23.png
