### ISSUE TITLE
Oak - Meditation & Breathing

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10937]
**App Name:** Oak - Meditation & Breathing
**Bundle ID:** com.courtneycircle.MeditationMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1210209691">1210209691</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/oak-meditation-breathing/id1210209691?uo=4">https://apps.apple.com/us/app/oak-meditation-breathing/id1210209691?uo=4</a>
**App Version:** 2.5.2
**Seller:** Oak by Big Sky Health, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/big-sky-health/id1397458636?uo=4">© Big Sky Health</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/9d/34/ab/9d34abfd-ab48-2262-fc20-d3c5488d1be3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86530257-7fc30000-beb7-11ea-9470-97f55cf479bc.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86530257-7fc30000-beb7-11ea-9470-97f55cf479bc.png)
https://user-images.githubusercontent.com/2068130/86530257-7fc30000-beb7-11ea-9470-97f55cf479bc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86530264-910c0c80-beb7-11ea-8502-d586c4c11c29.png
