### ISSUE TITLE
the Lott

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10933]
**App Name:** the Lott
**Bundle ID:** com.tattsbet.tattsbet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465032804">465032804</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/au/app/the-lott/id465032804?uo=4">https://apps.apple.com/au/app/the-lott/id465032804?uo=4</a>
**App Version:** 6.3.2
**Seller:** Tatts Online Pty Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/au/developer/tatts-group/id465032807?uo=4">© Tatts Group</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/c0/7e/6a/c07e6a63-1ecc-55fa-dcb1-b9560cd09bb1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85229856-84ce7c80-b3ec-11ea-986e-dd315cfb5b60.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85229856-84ce7c80-b3ec-11ea-986e-dd315cfb5b60.png)
https://user-images.githubusercontent.com/2068130/85229856-84ce7c80-b3ec-11ea-986e-dd315cfb5b60.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85229866-931c9880-b3ec-11ea-9a9d-36cfeed50e54.png
