### ISSUE TITLE
NSW FuelCheck

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10932]
**App Name:** NSW FuelCheck
**Bundle ID:** au.gov.nsw.onegov.fuelcheckapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1266569551">1266569551</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/nsw-fuelcheck/id1266569551?uo=4">https://apps.apple.com/us/app/nsw-fuelcheck/id1266569551?uo=4</a>
**App Version:** 1.1.32
**Seller:** Department of Customer Service
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/department-of-customer-service/id1047394004?uo=4">© Department of Customer Service</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/97/af/c7/97afc747-0db9-3b80-2d9d-85a04360f6cb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84356895-207a1480-abc5-11ea-98b7-062bc5c5c940.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84356895-207a1480-abc5-11ea-98b7-062bc5c5c940.png)
https://user-images.githubusercontent.com/2068130/84356895-207a1480-abc5-11ea-98b7-062bc5c5c940.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84356953-2ff95d80-abc5-11ea-9450-75cf3e1dec95.png
