### ISSUE TITLE
lifebox-Ultimate storage place

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10934]
**App Name:** lifebox-Ultimate storage place
**Bundle ID:** com.turkcell.akillidepo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=665036334">665036334</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/lifebox-ultimate-storage-place/id665036334?uo=4">https://apps.apple.com/gb/app/lifebox-ultimate-storage-place/id665036334?uo=4</a>
**App Version:** 2.57
**Seller:** Turkcell Teknoloji
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/turkcell-iletisim-hizmetleri-a-s/id305642482?uo=4">© Turkcell Iletisim Hizmetleri A.S.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/f9/0a/31/f90a3142-2f83-ad06-08eb-5821b4bfe1c0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84355997-d80e2700-abc3-11ea-80c5-2df5721d4caf.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84355997-d80e2700-abc3-11ea-80c5-2df5721d4caf.png)
https://user-images.githubusercontent.com/2068130/84355997-d80e2700-abc3-11ea-80c5-2df5721d4caf.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84356038-e9573380-abc3-11ea-8a00-0f8402ff1ca8.png
