### ISSUE TITLE
Stats Royale for Clash Royale

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10939]
**App Name:** Stats Royale for Clash Royale
**Bundle ID:** com.overwolf.statsroyale
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1264722932">1264722932</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stats-royale-for-clash-royale/id1264722932?uo=4">https://apps.apple.com/us/app/stats-royale-for-clash-royale/id1264722932?uo=4</a>
**App Version:** 2.6.7
**Seller:** Overwolf Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/overwolf/id1264722931?uo=4">© Overwolf</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/de/26/af/de26afa0-e002-ee69-24ac-008dabe49ce9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89103676-d880ac80-d413-11ea-89f4-fa2f3eec430b.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89103676-d880ac80-d413-11ea-89f4-fa2f3eec430b.png)
https://user-images.githubusercontent.com/2068130/89103676-d880ac80-d413-11ea-89f4-fa2f3eec430b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/89103679-e6363200-d413-11ea-8fa1-5924e974243e.png
