### ISSUE TITLE
Sport Clips Haircuts Check In

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10949]
**App Name:** Sport Clips Haircuts Check In
**Bundle ID:** com.openspend.ultimatemvp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1403308360">1403308360</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sport-clips-haircuts-check-in/id1403308360?uo=4">https://apps.apple.com/us/app/sport-clips-haircuts-check-in/id1403308360?uo=4</a>
**App Version:** 1.31.5
**Seller:** Sport Clips, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sport-clips/id1438677364?uo=4">© Sport Clips</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/34/0c/95/340c9599-9c2f-05ec-cf9e-b2ef27e4d12c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85228907-b80e0d00-b3e6-11ea-81e0-088d00d2a169.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85228907-b80e0d00-b3e6-11ea-81e0-088d00d2a169.png)
https://user-images.githubusercontent.com/2068130/85228907-b80e0d00-b3e6-11ea-81e0-088d00d2a169.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85228921-cc520a00-b3e6-11ea-8e3d-608e1888edb1.png
