### ISSUE TITLE
Yahtzee® with Buddies Dice

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10948]
**App Name:** Yahtzee® with Buddies Dice
**Bundle ID:** com.scopely.yux
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1206967173">1206967173</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/yahtzee-with-buddies-dice/id1206967173?uo=4">https://apps.apple.com/us/app/yahtzee-with-buddies-dice/id1206967173?uo=4</a>
**App Version:** 7.3.1
**Seller:** Scopely - Top Free Apps and Games LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/scopely/id305003647?uo=4">© Scopely</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/9b/77/47/9b77473a-09d2-4ade-bf42-e39be89cae7b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85229051-d0325c00-b3e7-11ea-96d0-f4d978830ec8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85229051-d0325c00-b3e7-11ea-96d0-f4d978830ec8.png)
https://user-images.githubusercontent.com/2068130/85229051-d0325c00-b3e7-11ea-96d0-f4d978830ec8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85229063-dfb1a500-b3e7-11ea-8ed1-8f1e86f3788b.png
