### ISSUE TITLE
9to5Mac — Breaking Tech News

### ISSUE THREAD

**Issue by Archigos** [glasklart/hd#10947]
**App Name:** 9to5Mac — Breaking Tech News
**Bundle ID:** com.9to5mac.terminal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955138289">955138289</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/9to5mac-breaking-tech-news/id955138289?uo=4">https://apps.apple.com/us/app/9to5mac-breaking-tech-news/id955138289?uo=4</a>
**App Version:** 2.0.1
**Seller:** Seth Weintraub
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/seth-weintraub/id955138288?uo=4">© Seth Weintraub</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/79/88/62/79886263-7798-5df1-09ab-d8ab420453b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84588517-700c4a80-ae28-11ea-9deb-42c1c82c7a98.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84588517-700c4a80-ae28-11ea-9deb-42c1c82c7a98.png)
https://user-images.githubusercontent.com/2068130/84588517-700c4a80-ae28-11ea-9deb-42c1c82c7a98.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84588532-80242a00-ae28-11ea-9024-e720aa95e2d3.png
