### ISSUE TITLE
DriveEasy by GEICO

### ISSUE THREAD

**Issue by Archigos** [glasklart/hd#10946]
**App Name:** DriveEasy by GEICO
**Bundle ID:** com.geico.telematics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1462061920">1462061920</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/driveeasy-by-geico/id1462061920?uo=4">https://apps.apple.com/us/app/driveeasy-by-geico/id1462061920?uo=4</a>
**App Version:** 2.2.0
**Seller:** GEICO
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/geico/id331763099?uo=4">© GEICO</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/ff/7e/22/ff7e22a3-e53f-2bc0-c239-4c1ec1503caa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84588596-16f0e680-ae29-11ea-8549-dec4a33f51ea.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84588596-16f0e680-ae29-11ea-8549-dec4a33f51ea.png)
https://user-images.githubusercontent.com/2068130/84588596-16f0e680-ae29-11ea-8549-dec4a33f51ea.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84588605-26702f80-ae29-11ea-98ad-ea87a0c0b468.png
