### ISSUE TITLE
Boulder Daily Camera

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10945]
**App Name:** Boulder Daily Camera
**Bundle ID:** com.dailycamera.ipadedition
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405275092">405275092</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/boulder-daily-camera/id405275092?uo=4">https://apps.apple.com/us/app/boulder-daily-camera/id405275092?uo=4</a>
**App Version:** 2.6.93
**Seller:** Prairie Mountain Publishing
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/prairie-mountain-publishing/id405275095?uo=4">© Prairie Mountain Publishing</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/92/36/02/9236020c-149e-b043-3754-399018189f98/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84588939-b4e5b080-ae2b-11ea-92c8-5fc2fa612a4d.png)

**Comment by Sly-Fi** [comment]
Similar to issue #10808 but would be nice if there was a subtle difference as both apps are on my phone

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84588939-b4e5b080-ae2b-11ea-92c8-5fc2fa612a4d.png)
https://user-images.githubusercontent.com/2068130/84588939-b4e5b080-ae2b-11ea-92c8-5fc2fa612a4d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84588959-c6c75380-ae2b-11ea-87a5-e6bf790bc2fd.png
