### ISSUE TITLE
Days Matter Air - Countdown

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10950]
**App Name:** Days Matter Air - Countdown
**Bundle ID:** com.chii.idays.air
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1113365292">1113365292</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/days-matter-air-countdown/id1113365292?uo=4">https://apps.apple.com/us/app/days-matter-air-countdown/id1113365292?uo=4</a>
**App Version:** 0.5.1
**Seller:** iDaily Corp.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/idaily-corp/id364264742?uo=4">© iDaily Corp.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/a3/d8/73/a3d87304-a13b-342f-b0b5-7b3babc54a14/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85228416-a37c4580-b3e3-11ea-9227-bf5c4afa504f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85228416-a37c4580-b3e3-11ea-9227-bf5c4afa504f.png)
https://user-images.githubusercontent.com/2068130/85228416-a37c4580-b3e3-11ea-9227-bf5c4afa504f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85228425-b2fb8e80-b3e3-11ea-8c71-d00b62ac1cd5.png
