### ISSUE TITLE
Synology Drive

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10955]
**App Name:** Synology Drive
**Bundle ID:** com.synology.DSdrive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1267275421">1267275421</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/synology-drive/id1267275421?uo=4">https://apps.apple.com/us/app/synology-drive/id1267275421?uo=4</a>
**App Version:** 2.2.0
**Seller:** Synology Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/synology-inc/id321493109?uo=4">© Synology Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/5a/2d/ea/5a2dea62-7ca5-e7e5-cee1-ac928ba0e5b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85193467-12b14700-b2c9-11ea-850d-2828d9b7728a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85193467-12b14700-b2c9-11ea-850d-2828d9b7728a.png)
https://user-images.githubusercontent.com/2068130/85193467-12b14700-b2c9-11ea-850d-2828d9b7728a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85193472-2361bd00-b2c9-11ea-8663-4cb4d4d12def.png
