### ISSUE TITLE
剪映 - 轻而易剪

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10952]
**App Name:** 剪映 - 轻而易剪
**Bundle ID:** com.lemon.lv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1458072671">1458072671</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/cn/app/%E5%89%AA%E6%98%A0-%E8%BD%BB%E8%80%8C%E6%98%93%E5%89%AA/id1458072671?uo=4">https://apps.apple.com/cn/app/%E5%89%AA%E6%98%A0-%E8%BD%BB%E8%80%8C%E6%98%93%E5%89%AA/id1458072671?uo=4</a>
**App Version:** 3.3.0
**Seller:** Shenzhen Lianmeng Technology Co.Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/cn/developer/%E6%B7%B1%E5%9C%B3%E5%B8%82%E8%84%B8%E8%90%8C%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/id764976186?uo=4">© 深圳市脸萌科技有限公司</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/75/31/00/75310014-bbd5-c5b5-e278-ca6c15afe819/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85212083-87c75f80-b34f-11ea-9eba-6d062101a3e0.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85212083-87c75f80-b34f-11ea-9eba-6d062101a3e0.png)
https://user-images.githubusercontent.com/2068130/85212083-87c75f80-b34f-11ea-9eba-6d062101a3e0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85212089-9a419900-b34f-11ea-9efc-a1262bf7e436.png
