### ISSUE TITLE
Corona-Warn-App

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10954]
**App Name:** Corona-Warn-App
**Bundle ID:** de.rki.coronawarnapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1512595757">1512595757</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/corona-warn-app/id1512595757?uo=4">https://apps.apple.com/de/app/corona-warn-app/id1512595757?uo=4</a>
**App Version:** 1.0.2
**Seller:** Robert Koch-Institut
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/robert-koch-institut/id1308350896?uo=4">© Robert Koch-Institut</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/7e/4c/1d/7e4c1d03-20b9-8720-64a4-1f771b8df085/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85211486-1b962d00-b34a-11ea-821e-a59bd193c134.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85211486-1b962d00-b34a-11ea-821e-a59bd193c134.png)
https://user-images.githubusercontent.com/2068130/85211486-1b962d00-b34a-11ea-821e-a59bd193c134.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85211493-2fda2a00-b34a-11ea-93f3-75068ba91226.png
