### ISSUE TITLE
Woolworths

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10958]
**App Name:** Woolworths
**Bundle ID:** com.woolworths.supers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=975089690">975089690</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/au/app/woolworths/id975089690?uo=4">https://apps.apple.com/au/app/woolworths/id975089690?uo=4</a>
**App Version:** 5.7
**Seller:** Woolworths Group Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/au/developer/woolworths-group-limited/id382011091?uo=4">© Woolworths Group Limited</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/a1/5c/75/a15c75dc-fb2b-2b0d-366b-0db68192854e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85193261-22c82700-b2c7-11ea-8337-e6e2e80930a0.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85193261-22c82700-b2c7-11ea-8337-e6e2e80930a0.png)
https://user-images.githubusercontent.com/2068130/85193261-22c82700-b2c7-11ea-8337-e6e2e80930a0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85193272-32477000-b2c7-11ea-82d8-06c0ce868ab0.png

**Comment by EmpDns** [comment]
Awesome. Thanks!
