### ISSUE TITLE
Caltex Australia

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10959]
**App Name:** Caltex Australia
**Bundle ID:** au.com.caltex.flagship
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1314768594">1314768594</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/caltex-australia/id1314768594?uo=4">https://apps.apple.com/us/app/caltex-australia/id1314768594?uo=4</a>
**App Version:** 2.0
**Seller:** Caltex Australia Petroleum Pty Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/caltex/id425095618?uo=4">© Caltex</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/ed/c0/87/edc08773-9d00-1daa-ebad-085edc5f8ff6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85192936-fb705a80-b2c4-11ea-8ce4-55349b5602af.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85192936-fb705a80-b2c4-11ea-8ce4-55349b5602af.png)
https://user-images.githubusercontent.com/2068130/85192936-fb705a80-b2c4-11ea-8ce4-55349b5602af.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85192941-0aefa380-b2c5-11ea-90c5-402317934955.png

**Comment by EmpDns** [comment]
Awesome. Thanks!
