### ISSUE TITLE
Ulike - Define trendy selfie

### ISSUE THREAD

**Issue by liavoid** [glasklart/hd#10951]
**App Name:** Ulike - Define trendy selfie
**Bundle ID:** com.light.beautyabroad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1398796436">1398796436</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ulike-define-trendy-selfie/id1398796436?uo=4">https://apps.apple.com/us/app/ulike-define-trendy-selfie/id1398796436?uo=4</a>
**App Version:** 2.9.8
**Seller:** BYTEDANCE PTE. LTD.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bytedance-pte-ltd/id1497663561?uo=4">© Bytedance Pte. Ltd</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/5b/2e/31/5b2e3107-87b2-9c71-a2ce-50e4fae8f616/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85212196-ae39ca80-b350-11ea-96d4-d194af74302e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85212196-ae39ca80-b350-11ea-96d4-d194af74302e.png)
https://user-images.githubusercontent.com/2068130/85212196-ae39ca80-b350-11ea-96d4-d194af74302e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85212206-c578b800-b350-11ea-871b-2c29274e2cca.png
