### ISSUE TITLE
Jebao Aqua

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10953]
**App Name:** Jebao Aqua
**Bundle ID:** com.jebao.appstore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1433499852">1433499852</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/jebao-aqua/id1433499852?uo=4">https://apps.apple.com/us/app/jebao-aqua/id1433499852?uo=4</a>
**App Version:** 2.1.0
**Seller:** Jebao Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/%E4%B8%AD%E5%B1%B1%E5%B8%82%E6%8D%B7%E5%AE%9D%E7%94%B5%E5%AD%90%E7%94%B5%E5%99%A8%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/id1433499851?uo=4">© 中山市捷宝电子电器有限公司</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/4e/27/86/4e278660-0d1c-438f-e7d3-00d6557ff71a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85211943-323e8300-b34e-11ea-857a-d22f48867faa.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85211943-323e8300-b34e-11ea-857a-d22f48867faa.png)
https://user-images.githubusercontent.com/2068130/85211943-323e8300-b34e-11ea-857a-d22f48867faa.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85211951-44b8bc80-b34e-11ea-9e54-95e7fb0d034d.png
