### ISSUE TITLE
Inquire Boulder

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10956]
**App Name:** Inquire Boulder
**Bundle ID:** com.govoutreach.inquireboulder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=669330860">669330860</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/inquire-boulder/id669330860?uo=4">https://apps.apple.com/us/app/inquire-boulder/id669330860?uo=4</a>
**App Version:** 4.8.5
**Seller:** City of Boulder
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/city-of-boulder/id917690353?uo=4">© City of Boulder</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/ba/be/29/babe29f7-d117-9d43-0385-bbd3a0d14604/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85193376-4c358280-b2c8-11ea-9edc-a10a9e72c42a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85193376-4c358280-b2c8-11ea-9edc-a10a9e72c42a.png)
https://user-images.githubusercontent.com/2068130/85193376-4c358280-b2c8-11ea-9edc-a10a9e72c42a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85193383-5bb4cb80-b2c8-11ea-834e-afe1aa65dad8.png
