### ISSUE TITLE
Menulog AU - Food Delivery

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10962]
**App Name:** Menulog AU - Food Delivery
**Bundle ID:** au.com.menulog.m
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327982905">327982905</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/menulog-au-food-delivery/id327982905?uo=4">https://apps.apple.com/us/app/menulog-au-food-delivery/id327982905?uo=4</a>
**App Version:** 33.2.0
**Seller:** Just-Eat Holdings Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/just-eat-com/id383091095?uo=4">© Just-Eat.com</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/8e/f3/ff/8ef3fff4-c8bf-0c0d-3d8e-a7b3b4a04008/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85191680-04aaf880-b2c0-11ea-93c1-8ca5166103a6.png)

**Comment by dreamnet** [comment]
Same as #8357 
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85191680-04aaf880-b2c0-11ea-93c1-8ca5166103a6.png)
https://user-images.githubusercontent.com/2068130/85191680-04aaf880-b2c0-11ea-93c1-8ca5166103a6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85191704-1be9e600-b2c0-11ea-8b94-d48e4c293ea4.png

**Comment by EmpDns** [comment]
Awesome. Thanks!
