### ISSUE TITLE
Deliveroo: Food delivery

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10961]
**App Name:** Deliveroo: Food delivery
**Bundle ID:** com.deliveroo.orderapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1001501844">1001501844</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/deliveroo-food-delivery/id1001501844?uo=4">https://apps.apple.com/us/app/deliveroo-food-delivery/id1001501844?uo=4</a>
**App Version:** 3.48.0
**Seller:** ROOFOODS LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/deliveroo/id1001501843?uo=4">© Deliveroo</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/53/89/43/538943b4-c425-479f-5fd9-230114cc7265/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85192147-bdbe0280-b2c1-11ea-865e-779b447c8a16.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85192147-bdbe0280-b2c1-11ea-865e-779b447c8a16.png)
https://user-images.githubusercontent.com/2068130/85192147-bdbe0280-b2c1-11ea-865e-779b447c8a16.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85192167-ce6e7880-b2c1-11ea-8e9e-7936301ca19f.png

**Comment by EmpDns** [comment]
Awesome. Thanks!
