### ISSUE TITLE
Matchbook - Save and Remember Great Restaurants and Bars

### ISSUE THREAD

**Issue by Tenkir** [glasklart/hd#1096]
**App Name:** Matchbook - Save and Remember Great Restaurants and Bars
**Bundle ID:** com.matchbookit.matchbook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427740544">427740544</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/matchbook-save-remember-great/id427740544?mt=8&uo=4">https://itunes.apple.com/us/app/matchbook-save-remember-great/id427740544?mt=8&uo=4</a>
**App Version:** 3.0.149
**Seller:** Matchbook FTW, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/matchbook-ftw-inc./id427740547?uo=4>© Matchbook FTW, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/c8/03/e5/c803e520-ab4e-3304-2809-4d186661d2c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19737479/ee3544ec-9bb3-11e6-8f28-a4949ab3501c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19737479/ee3544ec-9bb3-11e6-8f28-a4949ab3501c.png)
https://cloud.githubusercontent.com/assets/2068130/19737479/ee3544ec-9bb3-11e6-8f28-a4949ab3501c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19737497/fcbfb13c-9bb3-11e6-8911-ab21cded9d21.png
