### ISSUE TITLE
DS Manager Pro

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10969]
**App Name:** DS Manager Pro
**Bundle ID:** sk.pulik.jaroslav.DS-Manager-Pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1435876433">1435876433</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ds-manager-pro/id1435876433?uo=4">https://apps.apple.com/us/app/ds-manager-pro/id1435876433?uo=4</a>
**App Version:** 3.1.2
**Seller:** Jaroslav Pulik
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/jaroslav-pulik/id1274203159?uo=4">© Jaroslav Pulik</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/01/1f/d1/011fd175-4b18-ea6b-a60f-bdfa1be007df/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85191977-1d67de00-b2c1-11ea-97bd-41ee6e1bec5f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85191977-1d67de00-b2c1-11ea-97bd-41ee6e1bec5f.png)
https://user-images.githubusercontent.com/2068130/85191977-1d67de00-b2c1-11ea-97bd-41ee6e1bec5f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85192005-35d7f880-b2c1-11ea-87f0-c4f69ac0e19d.png
