### ISSUE TITLE
SolarWatch Sunrise Sunset Time

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#10968]
**App Name:** SolarWatch Sunrise Sunset Time
**Bundle ID:** com.fifteenjugglers.solarwatch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1191365122">1191365122</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/solarwatch-sunrise-sunset-time/id1191365122?uo=4">https://apps.apple.com/us/app/solarwatch-sunrise-sunset-time/id1191365122?uo=4</a>
**App Version:** 1.13.1
**Seller:** Fifteen Jugglers Software UG
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fifteen-jugglers-software-ug/id292972357?uo=4">© Fifteen Jugglers Software UG</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/59/09/ba/5909ba77-a4f3-42e7-3857-8a9e580e4198/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85190720-80567680-b2bb-11ea-83cb-9e25ace55988.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85190720-80567680-b2bb-11ea-83cb-9e25ace55988.png)
https://user-images.githubusercontent.com/2068130/85190720-80567680-b2bb-11ea-83cb-9e25ace55988.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85190730-95cba080-b2bb-11ea-8ff0-e3f2882babb6.png
