### ISSUE TITLE
Origin Energy

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10964]
**App Name:** Origin Energy
**Bundle ID:** com.originenergy.account
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1201586468">1201586468</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/origin-energy/id1201586468?uo=4">https://apps.apple.com/us/app/origin-energy/id1201586468?uo=4</a>
**App Version:** 2.7.10
**Seller:** Origin Energy Retail Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/origin-energy/id1201586467?uo=4">© Origin Energy</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/6f/ee/f7/6feef745-b344-ce05-4a02-4ff81e8b3f2c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85191344-c8c36380-b2be-11ea-9670-80c02ae07e60.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85191344-c8c36380-b2be-11ea-9670-80c02ae07e60.png)
https://user-images.githubusercontent.com/2068130/85191344-c8c36380-b2be-11ea-9670-80c02ae07e60.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85191364-dbd63380-b2be-11ea-9044-e75713add2aa.png

**Comment by EmpDns** [comment]
Awesome. Thanks!
