### ISSUE TITLE
Linkt

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10965]
**App Name:** Linkt
**Bundle ID:** com.transurban.linkt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1166823295">1166823295</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/linkt/id1166823295?uo=4">https://apps.apple.com/us/app/linkt/id1166823295?uo=4</a>
**App Version:** 2.21.0
**Seller:** TRANSURBAN LIMITED
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/transurban-limited/id1091477734?uo=4">© Transurban Limited</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/be/c0/92/bec09253-1c4e-e72d-a8a6-af8f61a22cc9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85190790-1a1e2380-b2bc-11ea-8e1a-a69655c1188e.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85190790-1a1e2380-b2bc-11ea-8e1a-a69655c1188e.png)
https://user-images.githubusercontent.com/2068130/85190790-1a1e2380-b2bc-11ea-8e1a-a69655c1188e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85190797-2d30f380-b2bc-11ea-9715-5f75a6c61fe6.png

**Comment by EmpDns** [comment]
Awesome. Thanks!
