### ISSUE TITLE
HOYTS Australia

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10960]
**App Name:** HOYTS Australia
**Bundle ID:** nz.co.vista.VistaAppHoyts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441151000">441151000</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hoyts-australia/id441151000?uo=4">https://apps.apple.com/us/app/hoyts-australia/id441151000?uo=4</a>
**App Version:** 5.06.100
**Seller:** The Hoyts Corporation Pty. Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-hoyts-corporation-pty-ltd/id441151003?uo=4">© The Hoyts Corporation Pty. Ltd.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/cf/e0/46/cfe046ae-35f0-feb8-f2e0-3257dc4f9d4e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85192462-e5fa3100-b2c2-11ea-8b13-f1df034dccfa.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85192462-e5fa3100-b2c2-11ea-8b13-f1df034dccfa.png)
https://user-images.githubusercontent.com/2068130/85192462-e5fa3100-b2c2-11ea-8b13-f1df034dccfa.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85192482-f6aaa700-b2c2-11ea-87e5-e0c3506aa8cc.png

**Comment by EmpDns** [comment]
Awesome. Thanks!

**Comment by EmpDns** [comment]
Awesome. Thanks!
