### ISSUE TITLE
Oporto

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10963]
**App Name:** Oporto
**Bundle ID:** com.oporto.rewards
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=920675672">920675672</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/au/app/oporto/id920675672?uo=4">https://apps.apple.com/au/app/oporto/id920675672?uo=4</a>
**App Version:** 3.1.9
**Seller:** Oporto Franchising Pty Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/au/developer/oporto/id920675671?uo=4">© Oporto</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/4a/d8/ba/4ad8ba1e-05f1-3837-38c3-658f77ff7176/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85191511-746cb380-b2bf-11ea-98aa-85e289b28f55.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85191511-746cb380-b2bf-11ea-98aa-85e289b28f55.png)
https://user-images.githubusercontent.com/2068130/85191511-746cb380-b2bf-11ea-98aa-85e289b28f55.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85191533-864e5680-b2bf-11ea-9d12-49da8faf1bf1.png

**Comment by EmpDns** [comment]
Awesome. Thanks!
