### ISSUE TITLE
Jetstar

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10966]
**App Name:** Jetstar
**Bundle ID:** com.jetstar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=821234247">821234247</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/jetstar/id821234247?uo=4">https://apps.apple.com/gb/app/jetstar/id821234247?uo=4</a>
**App Version:** 5.28.0
**Seller:** Jetstar Airways
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/jetstar-airways-pty-ltd/id821234250?uo=4">© Jetstar Airways Pty Ltd</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/d9/6e/06/d96e0669-3637-6c25-f9ec-931f4c24fbb4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85191074-ce6c7980-b2bd-11ea-9637-34b55dcce8fc.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85191074-ce6c7980-b2bd-11ea-9637-34b55dcce8fc.png)
https://user-images.githubusercontent.com/2068130/85191074-ce6c7980-b2bd-11ea-9637-34b55dcce8fc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85191094-de845900-b2bd-11ea-9a0a-ecb06fc1212a.png

**Comment by EmpDns** [comment]
Awesome. Thanks!
