### ISSUE TITLE
myBupa

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#10967]
**App Name:** myBupa
**Bundle ID:** com.bupa.fap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=475542225">475542225</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/au/app/mybupa/id475542225?uo=4">https://apps.apple.com/au/app/mybupa/id475542225?uo=4</a>
**App Version:** 2.11.0
**Seller:** Bupa Australia Health Pty Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/au/developer/bupa-australia-health-pty-ltd/id310663970?uo=4">© Bupa Australia Health Pty Ltd</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/c6/e8/4e/c6e84ece-7f1f-69fb-3f38-253d590339a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85190893-1d65df00-b2bd-11ea-952f-c9936293c2ce.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85190893-1d65df00-b2bd-11ea-952f-c9936293c2ce.png)
https://user-images.githubusercontent.com/2068130/85190893-1d65df00-b2bd-11ea-952f-c9936293c2ce.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85190901-2e165500-b2bd-11ea-8057-b59fc573e5ae.png

**Comment by EmpDns** [comment]
Awesome. Thanks!
