### ISSUE TITLE
Stopp Corona

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#10973]
**App Name:** Stopp Corona
**Bundle ID:** at.roteskreuz.stopcorona
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1503717224">1503717224</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stopp-corona/id1503717224?uo=4">https://apps.apple.com/us/app/stopp-corona/id1503717224?uo=4</a>
**App Version:** 2.0.2
**Seller:** Osterreichisches Rotes Kreuz
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/%C3%B6sterreichisches-rotes-kreuz/id542363111?uo=4">© Österreichisches Rotes Kreuz</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/15/22/92/152292dc-c807-4fa7-3821-21e1a3a395cb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86527925-d7577080-bea3-11ea-825b-25f0ad42e1af.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86527925-d7577080-bea3-11ea-825b-25f0ad42e1af.png)
https://user-images.githubusercontent.com/2068130/86527925-d7577080-bea3-11ea-825b-25f0ad42e1af.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86527932-e76f5000-bea3-11ea-95f5-0139df2b4d18.png
