### ISSUE TITLE
Line Color 3D

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10977]
**App Name:** Line Color 3D
**Bundle ID:** com.hambastudio.linecolor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1462582860">1462582860</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/line-color-3d/id1462582860?uo=4">https://apps.apple.com/us/app/line-color-3d/id1462582860?uo=4</a>
**App Version:** 1.13
**Seller:** Tastypill LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tastypill/id1022434729?uo=4">© tastypill</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/e6/da/84/e6da8406-ffcd-f878-81db-582119582f82/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89098319-c0deff00-d3e6-11ea-8739-a31034fdbc51.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89098319-c0deff00-d3e6-11ea-8739-a31034fdbc51.png)
https://user-images.githubusercontent.com/2068130/89098319-c0deff00-d3e6-11ea-8739-a31034fdbc51.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/89098326-cfc5b180-d3e6-11ea-83fe-47ae90c5f7cf.png
