### ISSUE TITLE
GGMM-E series

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10975]
**App Name:** GGMM-E series
**Bundle ID:** com.ggmm.muzo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049225684">1049225684</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ggmm-e-series/id1049225684?uo=4">https://apps.apple.com/us/app/ggmm-e-series/id1049225684?uo=4</a>
**App Version:** 2.8.8202
**Seller:** GGMM International Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ggmm/id792995699?uo=4">© GGMM</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/82/20/d4/8220d4ba-67a3-d251-93a7-e9a019b6b2df/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86529203-0fb07c00-beaf-11ea-91b5-88575a3de24c.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86529203-0fb07c00-beaf-11ea-91b5-88575a3de24c.png)
https://user-images.githubusercontent.com/2068130/86529203-0fb07c00-beaf-11ea-91b5-88575a3de24c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86529209-248d0f80-beaf-11ea-80f7-49ca65bc6c0f.png
