### ISSUE TITLE
Smart Life - Smart Living

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10976]
**App Name:** Smart Life - Smart Living
**Bundle ID:** com.tuya.smartlife
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1115101477">1115101477</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/smart-life-smart-living/id1115101477?uo=4">https://apps.apple.com/us/app/smart-life-smart-living/id1115101477?uo=4</a>
**App Version:** 3.18.0
**Seller:** Yu xiang
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yu-xiang/id1115101476?uo=4">© Yu xiang</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/4f/92/2b/4f922bb4-41f7-0342-af25-6fbf26f25d01/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88093196-f3d8f580-cb91-11ea-8a3e-5c571319eba1.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88093196-f3d8f580-cb91-11ea-8a3e-5c571319eba1.png)
https://user-images.githubusercontent.com/2068130/88093196-f3d8f580-cb91-11ea-8a3e-5c571319eba1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/88093246-094e1f80-cb92-11ea-917b-f1c19a1c061d.png
