### ISSUE TITLE
Adobe Scan Digital PDF Scanner

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10971]
**App Name:** Adobe Scan Digital PDF Scanner
**Bundle ID:** com.adobe.scan.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1199564834">1199564834</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/adobe-scan-digital-pdf-scanner/id1199564834?uo=4">https://apps.apple.com/us/app/adobe-scan-digital-pdf-scanner/id1199564834?uo=4</a>
**App Version:** 20.06.18
**Seller:** Adobe Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/adobe-inc/id331646274?uo=4">© Adobe Inc.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/45/41/5a/45415a2a-ab53-31f3-f089-1616907296e4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86528356-7b8ee680-bea7-11ea-9653-68e5456a0fa7.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86528356-7b8ee680-bea7-11ea-9653-68e5456a0fa7.png)
https://user-images.githubusercontent.com/2068130/86528356-7b8ee680-bea7-11ea-9653-68e5456a0fa7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86528370-8b0e2f80-bea7-11ea-9e4f-6e059b2bc135.png
