### ISSUE TITLE
Philips Hue Sync

### ISSUE THREAD

**Issue by popitre** [glasklart/hd#10970]
**App Name:** Philips Hue Sync
**Bundle ID:** com.signify.hue.tv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1470980341">1470980341</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/philips-hue-sync/id1470980341?uo=4">https://apps.apple.com/us/app/philips-hue-sync/id1470980341?uo=4</a>
**App Version:** 1.11.0
**Seller:** Signify Netherlands B.V.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/signify-netherlands-b-v/id979064009?uo=4">© Signify Netherlands B.V.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/a3/48/ec/a348ec8d-5059-6829-1c95-232a53531077/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86528762-7764c800-beab-11ea-97c0-57f3d23a3fa4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86528762-7764c800-beab-11ea-97c0-57f3d23a3fa4.png)
https://user-images.githubusercontent.com/2068130/86528762-7764c800-beab-11ea-97c0-57f3d23a3fa4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86528768-8e0b1f00-beab-11ea-8420-35a3b6cb8af6.png
