### ISSUE TITLE
Aqamai

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10979]
**App Name:** Aqamai
**Bundle ID:** com.aqamai.hydorgroup
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1210378346">1210378346</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/aqamai/id1210378346?uo=4">https://apps.apple.com/us/app/aqamai/id1210378346?uo=4</a>
**App Version:** 3.0.7
**Seller:** Hydor srl
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hydor-group/id1182463874?uo=4">© Hydor Group</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/f6/0a/dc/f60adc0b-b05d-6099-4d1f-eac81e0df374/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88094560-11a75a00-cb94-11ea-90c2-c7a31e1504a2.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88094560-11a75a00-cb94-11ea-90c2-c7a31e1504a2.png)
https://user-images.githubusercontent.com/2068130/88094560-11a75a00-cb94-11ea-90c2-c7a31e1504a2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/88094602-24219380-cb94-11ea-906d-734ceef3c9cb.png
