### ISSUE TITLE
Adobe Photoshop Mix - Cut out, combine, create

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#10972]
**App Name:** Adobe Photoshop Mix - Cut out, combine, create
**Bundle ID:** com.adobe.photoshop.mix.ipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=885271158">885271158</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/adobe-photoshop-mix-cut-out-combine-create/id885271158?uo=4">https://apps.apple.com/us/app/adobe-photoshop-mix-cut-out-combine-create/id885271158?uo=4</a>
**App Version:** 2.8.1
**Seller:** Adobe Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/adobe-inc/id331646274?uo=4">© Adobe Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/69/a2/01/69a2017d-a349-64ba-e2e6-4e1836e2729c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com adobe photoshop mix ipad-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86527410-c7895d80-be9e-11ea-82c7-a12ea69c10ef.png)

**Comment by dreamnet** [comment]
![com adobe photoshop mix ipad-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86527410-c7895d80-be9e-11ea-82c7-a12ea69c10ef.png)
https://user-images.githubusercontent.com/2068130/86527410-c7895d80-be9e-11ea-82c7-a12ea69c10ef.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86527424-da9c2d80-be9e-11ea-9e98-9f319f453db0.png

**Comment by dreamnet** [comment]
Already in te repo - no action needed.
