### ISSUE TITLE
Shoop.de - Cashback&Gutscheine

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10985]
**App Name:** Shoop.de - Cashback&Gutscheine
**Bundle ID:** de.shoop.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1263935619">1263935619</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/shoop-de-cashback-gutscheine/id1263935619?uo=4">https://apps.apple.com/gb/app/shoop-de-cashback-gutscheine/id1263935619?uo=4</a>
**App Version:** 2.1.5
**Seller:** Shoop Germany GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/shoop-germany-gmbh/id1263935618?uo=4">© Shoop Germany GmbH</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/b8/70/e8/b870e8c0-06f4-1e63-0a1d-8e9aeb252f6b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89097606-aa35a980-d3e0-11ea-9dca-2a71b863c9a1.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89097606-aa35a980-d3e0-11ea-9dca-2a71b863c9a1.png)
https://user-images.githubusercontent.com/2068130/89097606-aa35a980-d3e0-11ea-9dca-2a71b863c9a1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/89097614-ba4d8900-d3e0-11ea-98fb-5554bdfa45d3.png
