### ISSUE TITLE
DLive · Live Stream Community

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#10980]
**App Name:** DLive · Live Stream Community
**Bundle ID:** tv.dlive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1446969385">1446969385</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dlive-live-stream-community/id1446969385?uo=4">https://apps.apple.com/us/app/dlive-live-stream-community/id1446969385?uo=4</a>
**App Version:** 1.8.8
**Seller:** DLive Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dlive-inc/id1446969384?uo=4">© DLive Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/e3/fa/6d/e3fa6d8c-199d-fbfb-b2f0-fe46ff5c51be/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![tv dlive-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88096501-073a8f80-cb97-11ea-87db-808b5bbcd5c5.png)

**Comment by dreamnet** [comment]
![tv dlive-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88096501-073a8f80-cb97-11ea-87db-808b5bbcd5c5.png)
https://user-images.githubusercontent.com/2068130/88096501-073a8f80-cb97-11ea-87db-808b5bbcd5c5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/88096537-16b9d880-cb97-11ea-8cbb-6701353f2290.png
