### ISSUE TITLE
ChargePoint®

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10988]
**App Name:** ChargePoint®
**Bundle ID:** com.coulomb.ChargePoint
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=356866743">356866743</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/chargepoint/id356866743?uo=4">https://apps.apple.com/us/app/chargepoint/id356866743?uo=4</a>
**App Version:** 5.67.2
**Seller:** ChargePoint, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/chargepoint-inc/id356866746?uo=4">© ChargePoint, Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/b3/ae/c1/b3aec1dd-0c9b-4022-6c11-cd88ff485de6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89097082-dbf84180-d3db-11ea-8831-5131cb4be91a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89097082-dbf84180-d3db-11ea-8831-5131cb4be91a.png)
https://user-images.githubusercontent.com/2068130/89097082-dbf84180-d3db-11ea-8831-5131cb4be91a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/89097085-ea465d80-d3db-11ea-932d-0021a0f01eb8.png
