### ISSUE TITLE
ARD Quiz

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10982]
**App Name:** ARD Quiz
**Bundle ID:** de.ppa.ard.quiz.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1247878626">1247878626</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/ard-quiz/id1247878626?uo=4">https://apps.apple.com/de/app/ard-quiz/id1247878626?uo=4</a>
**App Version:** 1.7.11
**Seller:** Erstes Deutsches Fernsehen
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/erstes-deutsches-fernsehen/id610313722?uo=4">© Erstes Deutsches Fernsehen</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/1b/80/4b/1b804b67-5c63-9484-1175-fe0a57a8b399/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88093550-72ce2e00-cb92-11ea-8c91-7fce0609dd5f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88093550-72ce2e00-cb92-11ea-8c91-7fce0609dd5f.png)
https://user-images.githubusercontent.com/2068130/88093550-72ce2e00-cb92-11ea-8c91-7fce0609dd5f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/88093584-824d7700-cb92-11ea-82aa-f733c8d5d4d0.png
