### ISSUE TITLE
[DUPLICATE of #10980]

### ISSUE THREAD

**Issue by jackel198905** [glasklart/hd#10983]
**App Name:** DLive · Live Stream Community
**Bundle ID:** tv.dlive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1446969385">1446969385</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dlive-live-stream-community/id1446969385?uo=4">https://apps.apple.com/us/app/dlive-live-stream-community/id1446969385?uo=4</a>
**App Version:** 1.8.8
**Seller:** DLive Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dlive-inc/id1446969384?uo=4">© DLive Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/e3/fa/6d/e3fa6d8c-199d-fbfb-b2f0-fe46ff5c51be/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
you need to read the [icon request instructions](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request)
