### ISSUE TITLE
KFC

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#10981]
**App Name:** KFC
**Bundle ID:** com.kfc.de.mobileapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1459881659">1459881659</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/kfc/id1459881659?uo=4">https://apps.apple.com/de/app/kfc/id1459881659?uo=4</a>
**App Version:** 6.1.8
**Seller:** Kentucky Fried Chicken (Great Britain) Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/kentucky-fried-chicken-great-britain-limited/id497713503?uo=4">© Kentucky Fried Chicken (Great Britain) Limited</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a6/6a/02/a66a0255-ee1a-286f-36fc-cec33975a9b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88093886-f1c36680-cb92-11ea-9ff4-96422869472d.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88093886-f1c36680-cb92-11ea-9ff4-96422869472d.png)
https://user-images.githubusercontent.com/2068130/88093886-f1c36680-cb92-11ea-9ff4-96422869472d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/88093922-00aa1900-cb93-11ea-9b74-756cc7dbdb91.png
