### ISSUE TITLE
Müller Deutschland

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10984]
**App Name:** Müller Deutschland
**Bundle ID:** at.helloagain.muellerde
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1516484066">1516484066</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/m%C3%BCller-deutschland/id1516484066?uo=4">https://apps.apple.com/de/app/m%C3%BCller-deutschland/id1516484066?uo=4</a>
**App Version:** 1.9.2
**Seller:** Mueller Grosshandels Ltd. & Co. KG
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/mueller-grosshandels-ltd-co-kg/id1157953992?uo=4">© Mueller Grosshandels Ltd. & Co. KG</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/5b/4a/1d/5b4a1d60-c56c-e864-33c8-05fc7f114ed4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88094232-88902300-cb93-11ea-9e37-a8166d9482b7.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/88094232-88902300-cb93-11ea-9e37-a8166d9482b7.png)
https://user-images.githubusercontent.com/2068130/88094232-88902300-cb93-11ea-9e37-a8166d9482b7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/88094263-9776d580-cb93-11ea-8ef3-639c1a0938bb.png
