### ISSUE TITLE
TIER-A better way to get there

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#10987]
**App Name:** TIER-A better way to get there
**Bundle ID:** app.tier.sharing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1436140272">1436140272</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tier-a-better-way-to-get-there/id1436140272?uo=4">https://apps.apple.com/us/app/tier-a-better-way-to-get-there/id1436140272?uo=4</a>
**App Version:** 3.8.6.
**Seller:** Tier Mobility GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tier-mobility-gmbh/id1435293589?uo=4">© Tier Mobility GmbH</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/d4/1d/0a/d41d0a3f-36f1-ba71-fe02-054c9c9526eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89097122-6640a580-d3dc-11ea-9ebd-ccc4c15366b6.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89097122-6640a580-d3dc-11ea-9ebd-ccc4c15366b6.png)
https://user-images.githubusercontent.com/2068130/89097122-6640a580-d3dc-11ea-9ebd-ccc4c15366b6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/89097128-75bfee80-d3dc-11ea-86df-3b56c0c925f7.png
