### ISSUE TITLE
Photo Scanner: Scan old Albums

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10986]
**App Name:** Photo Scanner: Scan old Albums
**Bundle ID:** net.doo.kolibri-free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1178554831">1178554831</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/photo-scanner-scan-old-albums/id1178554831?uo=4">https://apps.apple.com/us/app/photo-scanner-scan-old-albums/id1178554831?uo=4</a>
**App Version:** 2.3.3
**Seller:** doo GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/doo-gmbh/id454738556?uo=4">© doo GmbH</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/6d/75/19/6d7519b0-1784-2b96-72d1-715825590ebc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89097496-a6555780-d3df-11ea-9360-47ac1f9c3099.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89097496-a6555780-d3df-11ea-9360-47ac1f9c3099.png)
https://user-images.githubusercontent.com/2068130/89097496-a6555780-d3df-11ea-9360-47ac1f9c3099.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/89097502-b53c0a00-d3df-11ea-8243-63d8b2507985.png
