### ISSUE TITLE
PlugShare - Tesla & EV Map

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#10989]
**App Name:** PlugShare - Tesla & EV Map
**Bundle ID:** com.xatori.plugshare
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=421788217">421788217</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/plugshare-tesla-ev-map/id421788217?uo=4">https://apps.apple.com/us/app/plugshare-tesla-ev-map/id421788217?uo=4</a>
**App Version:** 5.8
**Seller:** Recargo, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/recargo-inc/id405168587?uo=4">© Recargo, Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/ee/19/c4/ee19c48b-4e77-c736-8ac1-d43d624bf3e0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89096950-d3ebd200-d3da-11ea-86de-3c4ff8bd1983.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/89096950-d3ebd200-d3da-11ea-86de-3c4ff8bd1983.png)
https://user-images.githubusercontent.com/2068130/89096950-d3ebd200-d3da-11ea-86de-3c4ff8bd1983.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/89096958-e2d28480-d3da-11ea-803e-5529b4d07bc2.png
