### ISSUE TITLE
Azarton

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10994]
**App Name:** Azarton
**Bundle ID:** com.azarton.cam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1511916231">1511916231</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/azarton/id1511916231?uo=4">https://apps.apple.com/us/app/azarton/id1511916231?uo=4</a>
**App Version:** 1.2.20
**Seller:** Shenzhen Yuanmusen Technology Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shenzhen-yuanmusen-technology-co-ltd/id1511916230?uo=4">© Shenzhen Yuanmusen Technology Co., Ltd</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/40/98/f8/4098f838-a3d2-b4ac-4443-8d2c999a08f4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102438225-e2353600-3fe9-11eb-8fb1-ff6d1b9a99dd.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102438225-e2353600-3fe9-11eb-8fb1-ff6d1b9a99dd.png)
https://user-images.githubusercontent.com/2313873/102438225-e2353600-3fe9-11eb-8fb1-ff6d1b9a99dd.png

___
Source:
https://user-images.githubusercontent.com/2313873/102438208-de091880-3fe9-11eb-925b-e23f99701d04.png
