### ISSUE TITLE
Muse: Meditation & Sleep

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10992]
**App Name:** Muse: Meditation & Sleep
**Bundle ID:** com.interaxon.muse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=849841170">849841170</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/muse-meditation-sleep/id849841170?uo=4">https://apps.apple.com/us/app/muse-meditation-sleep/id849841170?uo=4</a>
**App Version:** 23.7
**Seller:** InteraXon Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/interaxon/id849841173?uo=4">© InteraXon</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/eb/7f/bd/eb7fbd43-f833-a6a2-68a8-1eb84b9ec18b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102438414-42c47300-3fea-11eb-90ec-dc515e39ed2d.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102438414-42c47300-3fea-11eb-90ec-dc515e39ed2d.png)
https://user-images.githubusercontent.com/2313873/102438414-42c47300-3fea-11eb-90ec-dc515e39ed2d.png

___
Source:
https://user-images.githubusercontent.com/2313873/102438408-40621900-3fea-11eb-84d3-93993583c939.png
