### ISSUE TITLE
Reflexion: Neuro-Fitness Coach

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#10993]
**App Name:** Reflexion: Neuro-Fitness Coach
**Bundle ID:** com.reflexioninteractive.Reflexion-Edge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1451350200">1451350200</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/reflexion-neuro-fitness-coach/id1451350200?uo=4">https://apps.apple.com/us/app/reflexion-neuro-fitness-coach/id1451350200?uo=4</a>
**App Version:** 2.0.2
**Seller:** Reflexion Interactive Technologies LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/reflexion/id1451350199?uo=4">© Reflexion</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/e9/56/a4/e956a48a-dd7d-5638-ec36-cf08080a3d5c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/105622072-1ddad100-5ddc-11eb-9269-10d932999590.png)

**Comment by zmathiasz** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/105622072-1ddad100-5ddc-11eb-9269-10d932999590.png)
https://user-images.githubusercontent.com/10950389/105622072-1ddad100-5ddc-11eb-9269-10d932999590.png
***
Source:
https://user-images.githubusercontent.com/10950389/105622076-2df2b080-5ddc-11eb-86d5-c8e6fedbeb7a.png
