### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10997]
**App Name:** Translate
**Bundle ID:** com.apple.Translate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1514844618">1514844618</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/translate/id1514844618?uo=4">https://apps.apple.com/us/app/translate/id1514844618?uo=4</a>
**App Version:** 1.1
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/ab/7a/68/ab7a68e0-83a7-3080-a294-0999eb38357e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102438002-823e8f80-3fe9-11eb-85b0-927c0d4d4eff.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102438002-823e8f80-3fe9-11eb-85b0-927c0d4d4eff.png)
https://user-images.githubusercontent.com/2313873/102438002-823e8f80-3fe9-11eb-85b0-927c0d4d4eff.png

___
Source:
https://user-images.githubusercontent.com/2313873/102437996-7f439f00-3fe9-11eb-81a6-e5e60e5c0506.png
