### ISSUE TITLE
Binge

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10999]
**App Name:** Binge
**Bundle ID:** au.com.streamotion.ares.prod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1486598248">1486598248</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/au/app/binge/id1486598248?uo=4">https://apps.apple.com/au/app/binge/id1486598248?uo=4</a>
**App Version:** 1.0.6
**Seller:** STREAMOTION PTY LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/au/developer/streamotion-pty-ltd/id1434518366?uo=4">© Streamotion Pty Ltd</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/96/44/07/964407c5-dcc6-3945-c949-078635324692/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102437576-bcf3f800-3fe8-11eb-9b18-7f4b0082f229.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102437576-bcf3f800-3fe8-11eb-9b18-7f4b0082f229.png)
https://user-images.githubusercontent.com/2313873/102437576-bcf3f800-3fe8-11eb-9b18-7f4b0082f229.png

___
Source:
https://user-images.githubusercontent.com/2313873/102437572-ba919e00-3fe8-11eb-8c88-49c7b882ac79.png
