### ISSUE TITLE
Stan.

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#10998]
**App Name:** Stan.
**Bundle ID:** au.com.stan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=948095331">948095331</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/au/app/stan/id948095331?uo=4">https://apps.apple.com/au/app/stan/id948095331?uo=4</a>
**App Version:** 3.13
**Seller:** Stan Entertainment Pty Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/au/developer/stan-entertainment-pty-ltd/id948095330?uo=4">© Stan Entertainment Pty Ltd</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/8b/dd/03/8bdd030a-f1d1-2a44-c4a2-ad048422d6b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102437730-03495700-3fe9-11eb-9b8a-283384ec77bc.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102437730-03495700-3fe9-11eb-9b8a-283384ec77bc.png)
https://user-images.githubusercontent.com/2313873/102437730-03495700-3fe9-11eb-9b8a-283384ec77bc.png

___
Source:
https://user-images.githubusercontent.com/2313873/102437721-ffb5d000-3fe8-11eb-9070-137a5dac994d.png
