### ISSUE TITLE
Video Editor .

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#10991]
**App Name:** Video Editor .
**Bundle ID:** com.wenjie.VideoEditor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1253802769">1253802769</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/video-editor/id1253802769?uo=4">https://apps.apple.com/us/app/video-editor/id1253802769?uo=4</a>
**App Version:** 2.4.4
**Seller:** Wenjie Qiu
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wenjie-qiu/id1250752300?uo=4">© Wenjie Qiu</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/0f/3e/57/0f3e57f9-b9cf-9391-42e8-98a470a2c152/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/90490113-81324a00-e13e-11ea-9841-52213ca0bf84.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/90490113-81324a00-e13e-11ea-9841-52213ca0bf84.png)
https://user-images.githubusercontent.com/2068130/90490113-81324a00-e13e-11ea-9841-52213ca0bf84.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/90490158-90b19300-e13e-11ea-809a-bc484137be20.png
