### ISSUE TITLE
YAZIO Fasting & Food Tracker

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#10995]
**App Name:** YAZIO Fasting & Food Tracker
**Bundle ID:** com.yazio.ios.YAZIO
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=946099227">946099227</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/yazio-fasting-food-tracker/id946099227?uo=4">https://apps.apple.com/us/app/yazio-fasting-food-tracker/id946099227?uo=4</a>
**App Version:** 6.8.4
**Seller:** YAZIO GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yazio/id775747960?uo=4">© YAZIO</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/e3/6c/15/e36c1579-519e-e0f2-822d-34e5fd69237b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/105621923-a2c4eb00-5dda-11eb-85ef-d64c2531e14a.png)

**Comment by zmathiasz** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/105621923-a2c4eb00-5dda-11eb-85ef-d64c2531e14a.png
)
https://user-images.githubusercontent.com/10950389/105621867-1ca8a480-5dda-11eb-9bbf-ac8723d58462.png
***
Source:
https://user-images.githubusercontent.com/10950389/105621906-83c65900-5dda-11eb-82a0-03ce9b212940.png

**Comment by Gwai** [comment]
When will you push the update with the new icons?

**Comment by dreamnet** [comment]
https://github.com/glasklart/hd/issues/11025
