### ISSUE TITLE
Figure - Make Music & Beats

### ISSUE THREAD

**Issue by braindeadrebel** [glasklart/hd#11]
**App Name:** Figure - Make Music & Beats
**Bundle ID:** se.propellerheads.figure
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=511269223">511269223</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/figure-make-music-beats/id511269223?uo=4">https://apps.apple.com/us/app/figure-make-music-beats/id511269223?uo=4</a>
**App Version:** 3.1
**Seller:** Propellerhead Software AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/propellerhead-software-ab/id368199128?uo=4">© Propellerhead Software AB</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/07/dc/43/07dc4321-8e72-7d7a-483d-cd5d3b7bccb3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393777-d23a4580-9b1a-11e9-8448-06091db0d282.png)

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12766546/be8bb612-ca04-11e5-8e43-981323cd63e1.png)
https://cloud.githubusercontent.com/assets/10730122/12766546/be8bb612-ca04-11e5-8e43-981323cd63e1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12766547/be942540-ca04-11e5-8a5b-5856647db5e8.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12766566/d9ab9890-ca04-11e5-854a-494b92d90935.png)
https://cloud.githubusercontent.com/assets/10730122/12766566/d9ab9890-ca04-11e5-854a-494b92d90935.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12766567/d9ae143a-ca04-11e5-8108-b4df2a4e145f.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393777-d23a4580-9b1a-11e9-8448-06091db0d282.png)
https://user-images.githubusercontent.com/20930745/60393777-d23a4580-9b1a-11e9-8448-06091db0d282.png

Source:
https://user-images.githubusercontent.com/20930745/60393779-d4040900-9b1a-11e9-9c79-310faadc525a.png
