### ISSUE TITLE
McDo France

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#110]
**App Name:** McDo France
**Bundle ID:** com.mcdonalds.mcdo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324887734">324887734</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mcdo-france/id324887734?mt=8&uo=4">https://itunes.apple.com/us/app/mcdo-france/id324887734?mt=8&uo=4</a>
**App Version:** 3.18.0
**Seller:** GIE McDonald's Force
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mcdonalds-france/id324887737?uo=4>© McDonald's France</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone5, iPhone4, iPhone5c, iPadThirdGen4G, iPodTouchFifthGen, iPadFourthGen4G, iPad23G, iPad2Wifi, iPadMini, iPodTouchSixthGen, iPadMini4G, iPadThirdGen, iPadFourthGen, iPhone6Plus, iPhone4S
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/0a/e1/a1/0ae1a1f4-f99d-6a22-17a5-b17745467ff2/mzl.whlvtedi.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png)

**Comment by Trubbel** [comment]
Updating the icon and source - using same icon as #6021,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png)
https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8761834/c42be2c6-2d66-11e5-99cf-e8c30451ac47.png

**Comment by dreamnet** [comment]
Icon is alread in the repo - no further action needed.
