### ISSUE TITLE
MOTOR-TALK 

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#11001]
**App Name:** MOTOR-TALK
**Bundle ID:** net.motortalk.ForumApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943938624">943938624</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/motor-talk/id943938624?uo=4">https://apps.apple.com/us/app/motor-talk/id943938624?uo=4</a>
**App Version:** 1.8.3
**Seller:** mobile.de GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mobile-de-gmbh/id378563361?uo=4">© mobile.de GmbH</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/39/e9/dc/39e9dc22-aa68-5fe8-6037-017d30d22480/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102437187-21628780-3fe8-11eb-9a70-d2a839c89f59.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102437187-21628780-3fe8-11eb-9a70-d2a839c89f59.png)
https://user-images.githubusercontent.com/2313873/102437187-21628780-3fe8-11eb-9a70-d2a839c89f59.png

___
Source:
https://user-images.githubusercontent.com/2313873/102437181-1f002d80-3fe8-11eb-8416-61c08286dbae.png
