### ISSUE TITLE
My Champlain

### ISSUE THREAD

**Issue by Tenkir** [glasklart/hd#1100]
**App Name:** My Champlain
**Bundle ID:** edu.champlain.champshuttle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526112520">526112520</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-champlain/id526112520?mt=8&uo=4">https://itunes.apple.com/us/app/my-champlain/id526112520?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** Matt Huwiler
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/champlain-college/id526112523?uo=4">© Champlain College</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/ac/7e/ca/ac7ecafd-f419-12fb-90bc-6d5959cc1b65/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19964521/78c5a76e-a1c2-11e6-9063-db216874e225.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19964521/78c5a76e-a1c2-11e6-9063-db216874e225.png)
https://cloud.githubusercontent.com/assets/20930745/19964521/78c5a76e-a1c2-11e6-9063-db216874e225.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19964544/91d218f0-a1c2-11e6-9b28-2ed14db1c260.png
