### ISSUE TITLE
RoadReady

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11002]
**App Name:** RoadReady
**Bundle ID:** com.SafeRoadsAlliance.RoadReady
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=699534935">699534935</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/roadready/id699534935?uo=4">https://apps.apple.com/us/app/roadready/id699534935?uo=4</a>
**App Version:** 3.1.0
**Seller:** Safe Roads Alliance, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/safe-roads-alliance-inc/id733912117?uo=4">© Safe Roads Alliance, Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/72/c1/0e/72c10e6e-b6e9-aa54-cd65-6eb81a3d7dfc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/105621548-84f58700-5dd6-11eb-9ed9-08c78c201806.png)

**Comment by zmathiasz** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/105621251-9be6aa00-5dd3-11eb-95bc-bc936fe33bc2.png)
https://user-images.githubusercontent.com/10950389/105621251-9be6aa00-5dd3-11eb-95bc-bc936fe33bc2.png)
***
Source:
https://user-images.githubusercontent.com/10950389/105621300-144d6b00-5dd4-11eb-8839-30485f6234a0.png
