### ISSUE TITLE
ZDFheute - Nachrichten

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#11000]
**App Name:** ZDFheute - Nachrichten
**Bundle ID:** de.zdf.heute
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=605390815">605390815</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/zdfheute-nachrichten/id605390815?uo=4">https://apps.apple.com/us/app/zdfheute-nachrichten/id605390815?uo=4</a>
**App Version:** 3.3
**Seller:** ZDFonline
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/zdf/id437025416?uo=4">© ZDF</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/bf/5a/d6/bf5ad611-c52e-4643-6a49-df28939afe71/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102437397-77cfc600-3fe8-11eb-96e5-1bc45b946a61.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102437397-77cfc600-3fe8-11eb-96e5-1bc45b946a61.png)
https://user-images.githubusercontent.com/2313873/102437397-77cfc600-3fe8-11eb-96e5-1bc45b946a61.png

___
Source:
https://user-images.githubusercontent.com/2313873/102437384-74d4d580-3fe8-11eb-9f97-81ea56db0cbf.png
