### ISSUE TITLE
St.George Mobile Banking

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#11006]
**App Name:** St.George Mobile Banking
**Bundle ID:** au.com.stgeorge.Consult
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=294380705">294380705</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/st-george-mobile-banking/id294380705?uo=4">https://apps.apple.com/us/app/st-george-mobile-banking/id294380705?uo=4</a>
**App Version:** 9.29
**Seller:** St.George Bank Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/st-george-bank-limited/id294380708?uo=4">© St.George Bank Limited</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/75/f6/da/75f6daab-addd-7128-9d9f-26eade4abd25/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102419398-a8eecd00-3fcd-11eb-9498-e6cd8a8c09c6.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102419398-a8eecd00-3fcd-11eb-9498-e6cd8a8c09c6.png)
https://user-images.githubusercontent.com/2313873/102419398-a8eecd00-3fcd-11eb-9498-e6cd8a8c09c6.png

___
Source:
https://user-images.githubusercontent.com/2313873/102419389-a3918280-3fcd-11eb-82e5-181f56d202d6.png

**Comment by EmpDns** [comment]
Awesome. Thanks!
