### ISSUE TITLE
Lexus Enform

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#11007]
**App Name:** Lexus Enform
**Bundle ID:** au.com.intelematics.EntuneLexus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=652682175">652682175</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/au/app/lexus-enform/id652682175?uo=4">https://apps.apple.com/au/app/lexus-enform/id652682175?uo=4</a>
**App Version:** 5.0.21
**Seller:** Toyota Motor Corporation Australia Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/au/developer/toyota-motor-corporation-australia-ltd/id1178726916?uo=4">© Toyota Motor Corporation Australia Ltd</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/26/a9/ea/26a9ea47-b649-4edc-4ba4-3378aa190de2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/105621714-84f68680-5dd8-11eb-9061-a0f48ebc8d3c.png)

**Comment by zmathiasz** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/105621714-84f68680-5dd8-11eb-9061-a0f48ebc8d3c.png)
https://user-images.githubusercontent.com/10950389/105621714-84f68680-5dd8-11eb-9061-a0f48ebc8d3c.png
***
Source:
https://user-images.githubusercontent.com/10950389/105621707-65f7f480-5dd8-11eb-8b48-619e10da72ef.png
