### ISSUE TITLE
McFIT

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#11003]
**App Name:** McFIT
**Bundle ID:** com.mysports.branded.mcfit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1515523496">1515523496</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/mcfit/id1515523496?uo=4">https://apps.apple.com/de/app/mcfit/id1515523496?uo=4</a>
**App Version:** 3.0.51
**Seller:** RSG Group GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/rsg-group-gmbh/id1515523495?uo=4">© RSG Group GmbH</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/48/0d/cf/480dcff2-a114-4f28-e4ae-831f0212f1f7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102436990-b7e27900-3fe7-11eb-89e6-a93d8dbd7d7f.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102436769-49052000-3fe7-11eb-9c6a-5bbe3c792d4e.png)
https://user-images.githubusercontent.com/2313873/102436769-49052000-3fe7-11eb-9c6a-5bbe3c792d4e.png

___
Source:
https://user-images.githubusercontent.com/2313873/102436761-45719900-3fe7-11eb-9c15-57ac059ac1bf.png
