### ISSUE TITLE
Everyday Rewards

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#11009]
**App Name:** Everyday Rewards
**Bundle ID:** com.woolworths.Rewards
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1489403660">1489403660</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/au/app/everyday-rewards/id1489403660?uo=4">https://apps.apple.com/au/app/everyday-rewards/id1489403660?uo=4</a>
**App Version:** 2.10
**Seller:** Woolworths Group Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/au/developer/woolworths-group-limited/id382011091?uo=4">© Woolworths Group Limited</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/93/54/96/93549639-745e-3d3a-bd49-0206b906d42d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102418719-4943f200-3fcc-11eb-8d02-c692a2bc1bea.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102418719-4943f200-3fcc-11eb-8d02-c692a2bc1bea.png)
https://user-images.githubusercontent.com/2313873/102418719-4943f200-3fcc-11eb-8d02-c692a2bc1bea.png

___
Source:
https://user-images.githubusercontent.com/2313873/102418709-45b06b00-3fcc-11eb-96a5-1ddf683052a7.png

**Comment by EmpDns** [comment]
Awesome. Thanks.
