### ISSUE TITLE
DiDi-Rider

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#11011]
**App Name:** DiDi-Rider
**Bundle ID:** com.didi.global.passenger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1362398401">1362398401</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/didi-rider/id1362398401?uo=4">https://apps.apple.com/us/app/didi-rider/id1362398401?uo=4</a>
**App Version:** 7.2.18
**Seller:** DIDI MOBILITY INFORMATION TECHNOLOGY PTE. LTD.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/didi/id1360238536?uo=4">© DiDi</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/cc/a8/19/cca81998-fbd9-6b61-76cd-fe5c01903ec9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102418152-2bc25880-3fcb-11eb-951f-a667d830b6c2.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102418152-2bc25880-3fcb-11eb-951f-a667d830b6c2.png)
https://user-images.githubusercontent.com/2313873/102418152-2bc25880-3fcb-11eb-951f-a667d830b6c2.png

___
Source:
https://user-images.githubusercontent.com/2313873/102418141-26fda480-3fcb-11eb-85a4-9483664a5c9f.png

**Comment by EmpDns** [comment]
Awesome. Thanks.
