### ISSUE TITLE
Catch - Online Shopping Deals

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#11010]
**App Name:** Catch - Online Shopping Deals
**Bundle ID:** au.com.catchoftheday.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=505027211">505027211</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/au/app/catch-online-shopping-deals/id505027211?uo=4">https://apps.apple.com/au/app/catch-online-shopping-deals/id505027211?uo=4</a>
**App Version:** 2.34.1
**Seller:** CATCH.COM.AU PTY LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/au/developer/catch-com-au-pty-ltd/id322518651?uo=4">© CATCH.COM.AU PTY LTD</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/ab/a2/77/aba2779a-b94a-2087-7319-6b82b4ef326e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102418415-adb28180-3fcb-11eb-9520-8f4cdba03e6b.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/102418415-adb28180-3fcb-11eb-9520-8f4cdba03e6b.png)
https://user-images.githubusercontent.com/2313873/102418415-adb28180-3fcb-11eb-9520-8f4cdba03e6b.png

___
Source:
https://user-images.githubusercontent.com/2313873/102418400-a8553700-3fcb-11eb-80f3-8696c529e1ea.png

**Comment by EmpDns** [comment]
Awesome. Thanks.
