### ISSUE TITLE
Among Us!

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#11012]
**App Name:** Among Us!
**Bundle ID:** com.innersloth.amongus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1351168404">1351168404</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/among-us/id1351168404?uo=4">https://apps.apple.com/us/app/among-us/id1351168404?uo=4</a>
**App Version:** 2020.11.17
**Seller:** InnerSloth LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/innersloth-llc/id957995279?uo=4">© InnerSloth LLC</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/b6/85/b6/b685b60d-62c7-aae5-4cd4-257e8d90b4ff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/105643529-65a23c80-5e5e-11eb-9cea-154a82bb569d.png)

**Comment by zmathiasz** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/105643529-65a23c80-5e5e-11eb-9cea-154a82bb569d.png)
https://user-images.githubusercontent.com/10950389/105643529-65a23c80-5e5e-11eb-9cea-154a82bb569d.png
***
Source:
https://user-images.githubusercontent.com/10950389/105644788-71ddc800-5e65-11eb-8a0a-b56e7f94cd65.png
