### ISSUE TITLE
PlantSnap - identify plant

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#11029]
**App Name:** PlantSnap - identify plant
**Bundle ID:** net.plantsnap.freemium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1451054346">1451054346</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/plantsnap-identify-plant/id1451054346?uo=4">https://apps.apple.com/us/app/plantsnap-identify-plant/id1451054346?uo=4</a>
**App Version:** 4.00.15
**Seller:** PlantSnap, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/plantsnap-inc/id1234702271?uo=4">© PlantSnap, Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/66/34/7d/66347d69-8f30-cf8c-6543-f3c095e79fa4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/106362139-887e9600-6321-11eb-94a2-3745e7786932.png)

**Comment by zmathiasz** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/106345934-777e4800-6281-11eb-8f00-c57fc178ebdd.png)
https://user-images.githubusercontent.com/10950389/106345934-777e4800-6281-11eb-8f00-c57fc178ebdd.png
***
Source:
https://user-images.githubusercontent.com/10950389/106345950-849b3700-6281-11eb-8602-2e5e8c80c6be.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/106362139-887e9600-6321-11eb-94a2-3745e7786932.png)
https://user-images.githubusercontent.com/2068130/106362139-887e9600-6321-11eb-94a2-3745e7786932.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/106362181-b6fc7100-6321-11eb-9674-46a3e0b42f31.png
