### ISSUE TITLE
myLearners

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#11023]
**App Name:** myLearners
**Bundle ID:** au.gov.vic.vicroads.dlk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1436550381">1436550381</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/mylearners/id1436550381?uo=4">https://apps.apple.com/us/app/mylearners/id1436550381?uo=4</a>
**App Version:** 1.5.1
**Seller:** Roads Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/vicroads/id389511269?uo=4">© VicRoads</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/92/22/14/922214b7-1193-be78-3b49-41c5e6c5eb6b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/103471702-504f5c00-4d51-11eb-84db-b640c7f03af1.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/103471702-504f5c00-4d51-11eb-84db-b640c7f03af1.png)
https://user-images.githubusercontent.com/2313873/103471702-504f5c00-4d51-11eb-84db-b640c7f03af1.png

___
Source:
https://user-images.githubusercontent.com/2313873/103471697-4c233e80-4d51-11eb-849e-756a8d3cafd5.png
