### ISSUE TITLE
Wave Wave - GameClub

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#11024]
**App Name:** Wave Wave - GameClub
**Bundle ID:** com.thomasjanson.wavewaveiOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=717990207">717990207</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/wave-wave-gameclub/id717990207?uo=4">https://apps.apple.com/us/app/wave-wave-gameclub/id717990207?uo=4</a>
**App Version:** 2.3.26
**Seller:** GameClub Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gameclub/id1339587139?uo=4">© GameClub</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/a8/c2/8e/a8c28e75-b227-a6d2-ce89-2ea8d8884b3e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/103471640-9e179480-4d50-11eb-9f8a-44fb39dad4c5.png)

**Comment by Mitchdog27** [comment]
[here](https://pbs.twimg.com/profile_images/537492631354241024/IZ1hduaE.png) is an image of the app logo without border 👍

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/103471640-9e179480-4d50-11eb-9f8a-44fb39dad4c5.png)
https://user-images.githubusercontent.com/2313873/103471640-9e179480-4d50-11eb-9f8a-44fb39dad4c5.png

___
Source:
https://user-images.githubusercontent.com/2313873/103471638-9657f000-4d50-11eb-8b07-4aa551ac93a8.png
