### ISSUE TITLE
LevelUp .: Skip the line, every time

### ISSUE THREAD

**Issue by Tenkir** [glasklart/hd#1102]
**App Name:** LevelUp .: Skip the line, every time
**Bundle ID:** com.scvngr.LevelUp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424121785">424121785</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/levelup-.-skip-line-every/id424121785?mt=8&uo=4">https://itunes.apple.com/us/app/levelup-.-skip-line-every/id424121785?mt=8&uo=4</a>
**App Version:** 2.9.3
**Seller:** SCVNGR
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/scvngr/id323248987?uo=4">© SCVNGR</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/86/cb/69/86cb69c9-e8ad-e3e1-e89a-b29c939f2233/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19964687/8b608bc2-a1c3-11e6-9d85-a108cd425a21.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19964687/8b608bc2-a1c3-11e6-9d85-a108cd425a21.png)
https://cloud.githubusercontent.com/assets/20930745/19964687/8b608bc2-a1c3-11e6-9d85-a108cd425a21.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19964701/9fddd5c8-a1c3-11e6-80eb-5f1ad6e33e26.png
