### ISSUE TITLE
Where is Xur? - for Destiny 2

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#11037]
**App Name:** Where is Xur? - for Destiny 2
**Bundle ID:** com.crocusgames.whereisxur
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955286784">955286784</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/where-is-xur-for-destiny-2/id955286784?uo=4">https://apps.apple.com/us/app/where-is-xur-for-destiny-2/id955286784?uo=4</a>
**App Version:** 2.0.615
**Seller:** Serkan Bal
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/serkan-bal/id955286783?uo=4">© Serkan Bal</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/b5/e6/05/b5e60599-ea5f-c54c-8931-d1ce8e2ef83c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/106501537-94a25900-64c3-11eb-8270-5b6b38dd3405.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/106501537-94a25900-64c3-11eb-8270-5b6b38dd3405.png)
https://user-images.githubusercontent.com/2068130/106501537-94a25900-64c3-11eb-8270-5b6b38dd3405.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/106501596-a421a200-64c3-11eb-8540-c5e2eb7b2796.png
