### ISSUE TITLE
Vault Manager for Destiny 2

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#11035]
**App Name:** Vault Manager for Destiny 2
**Bundle ID:** com.crocusgames.thevault
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1330143510">1330143510</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/vault-manager-for-destiny-2/id1330143510?uo=4">https://apps.apple.com/us/app/vault-manager-for-destiny-2/id1330143510?uo=4</a>
**App Version:** 1.0.021
**Seller:** Serkan Bal
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/serkan-bal/id955286783?uo=4">© Serkan Bal</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/8f/7d/4b/8f7d4b5d-d2ab-ca7f-bfe5-0127397f07f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/106504556-61fa5f80-64c7-11eb-870b-9bd947443b56.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/106504556-61fa5f80-64c7-11eb-870b-9bd947443b56.png)
https://user-images.githubusercontent.com/2068130/106504556-61fa5f80-64c7-11eb-870b-9bd947443b56.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/106504596-73436c00-64c7-11eb-8eb9-3dcd9d5d5de1.png
