### ISSUE TITLE
PlantSnap Pro: Identify Plants

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#11030]
**App Name:** PlantSnap Pro: Identify Plants
**Bundle ID:** net.plantsnap.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1234702272">1234702272</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/plantsnap-pro-identify-plants/id1234702272?uo=4">https://apps.apple.com/us/app/plantsnap-pro-identify-plants/id1234702272?uo=4</a>
**App Version:** 4.00.15
**Seller:** PlantSnap, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/plantsnap-inc/id1234702271?uo=4">© PlantSnap, Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/29/53/3c/29533ce5-3fd3-6f2e-d4e2-cd5088dfb344/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/106362139-887e9600-6321-11eb-94a2-3745e7786932.png)

**Comment by zmathiasz** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/10950389/106345842-06d72b80-6281-11eb-8111-f99d58407943.png)
https://user-images.githubusercontent.com/10950389/106345842-06d72b80-6281-11eb-8111-f99d58407943.png
***
Source:
https://user-images.githubusercontent.com/10950389/106345846-135b8400-6281-11eb-9d1c-6070c849ee77.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/106362139-887e9600-6321-11eb-94a2-3745e7786932.png)
https://user-images.githubusercontent.com/2068130/106362139-887e9600-6321-11eb-94a2-3745e7786932.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/106362181-b6fc7100-6321-11eb-9674-46a3e0b42f31.png
