### ISSUE TITLE
Scripts Pro - Screenwriting on the Go

### ISSUE THREAD

**Issue by Tenkir** [glasklart/hd#1103]
**App Name:** Scripts Pro - Screenwriting on the Go
**Bundle ID:** com.yourcompany.screenplay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348543183">348543183</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scripts-pro-screenwriting-on-the-go/id348543183?mt=8&uo=4">https://itunes.apple.com/us/app/scripts-pro-screenwriting-on-the-go/id348543183?mt=8&uo=4</a>
**App Version:** 4.0.4
**Seller:** Inkless Ideas LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inkless-ideas-llc/id348543186?uo=4">© Inkless Ideas LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/e8/c6/69/e8c66901-d043-8183-d8c0-baa0410eef15/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33231692-ddac3a36-d1f9-11e7-8b35-e291ee1a3647.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33231674-a67dc58e-d1f9-11e7-90c9-f0b3edd8c6fc.png)
https://user-images.githubusercontent.com/2068130/33231674-a67dc58e-d1f9-11e7-90c9-f0b3edd8c6fc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33231681-b6688d26-d1f9-11e7-9ac3-acb3649834d9.png
