### ISSUE TITLE
Ishtar Commander for Destiny 2

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#11036]
**App Name:** Ishtar Commander for Destiny 2
**Bundle ID:** com.designker.ishtar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1030835428">1030835428</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ishtar-commander-for-destiny-2/id1030835428?uo=4">https://apps.apple.com/us/app/ishtar-commander-for-destiny-2/id1030835428?uo=4</a>
**App Version:** 4.0.1
**Seller:** Nigel Hietala
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nigel-hietala/id1030835427?uo=4">© Nigel Hietala</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/bb/a7/49/bba749d5-a1e1-1dcc-5717-1d00b995d998/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120082623-37f72980-c0c4-11eb-91e4-b581e626f80f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120082623-37f72980-c0c4-11eb-91e4-b581e626f80f.png)
https://user-images.githubusercontent.com/2068130/120082623-37f72980-c0c4-11eb-91e4-b581e626f80f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/120082635-49403600-c0c4-11eb-9e14-c14bcb4a2476.png
