### ISSUE TITLE
food with love

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#11049]
**App Name:** food with love
**Bundle ID:** de.foodwithlove.foodwithloveDev
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1496402756">1496402756</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/food-with-love/id1496402756?uo=4">https://apps.apple.com/us/app/food-with-love/id1496402756?uo=4</a>
**App Version:** 1.7.0
**Seller:** Manuela Herzfeld und Joelle Herzfeld
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/food-with-love/id1496369314?uo=4">© Food with love</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/31/60/16/316016a1-fc6e-8d8b-6d52-7a759bc645e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111040923-eb417200-8435-11eb-96cb-ab4515ee65b4.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111040923-eb417200-8435-11eb-96cb-ab4515ee65b4.png)
https://user-images.githubusercontent.com/2068130/111040923-eb417200-8435-11eb-96cb-ab4515ee65b4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111040935-fbf1e800-8435-11eb-8b50-613af4bd6ab7.png
