### ISSUE TITLE
TuyaSmart

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#11047]
**App Name:** TuyaSmart
**Bundle ID:** com.tuya.smart
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1034649547">1034649547</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tuyasmart/id1034649547?uo=4">https://apps.apple.com/us/app/tuyasmart/id1034649547?uo=4</a>
**App Version:** 3.24.5
**Seller:** Tuya Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tuya-inc/id551919025?uo=4">© Tuya Inc.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/52/57/8b/52578ba5-b76b-8b4e-bddf-09ffeded6606/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111042153-33639300-843c-11eb-8c50-18595908de44.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111042153-33639300-843c-11eb-8c50-18595908de44.png)
https://user-images.githubusercontent.com/2068130/111042153-33639300-843c-11eb-8c50-18595908de44.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111042161-437b7280-843c-11eb-8d66-2bb7b52f253a.png
