### ISSUE TITLE
UCHealth

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11042]
**App Name:** UCHealth
**Bundle ID:** com.uchealth.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1190643586">1190643586</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/uchealth/id1190643586?uo=4">https://apps.apple.com/us/app/uchealth/id1190643586?uo=4</a>
**App Version:** 4.8.482
**Seller:** University of Colorado Health
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/uchealth/id1190643585?uo=4">© UCHealth</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/5e/d6/83/5ed6833e-30d2-51c9-ae93-191fd9fa1808/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/114508581-89c21e00-9c02-11eb-9b88-87b05c4b9f1b.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/114508239-220bd300-9c02-11eb-851e-ebcc2fddf8e2.png)
https://user-images.githubusercontent.com/2313873/114508239-220bd300-9c02-11eb-851e-ebcc2fddf8e2.png
___
Source:
https://user-images.githubusercontent.com/2313873/114508222-1d471f00-9c02-11eb-9deb-8e2fad2f867d.png
