### ISSUE TITLE
Shot Lister - Film set schedule tool for Directors

### ISSUE THREAD

**Issue by Tenkir** [glasklart/hd#1104]
**App Name:** Shot Lister - Film set schedule tool for Directors
**Bundle ID:** com.reelapps.RAShotLister
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=529436218">529436218</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shot-lister-film-set-schedule/id529436218?mt=8&uo=4">https://itunes.apple.com/us/app/shot-lister-film-set-schedule/id529436218?mt=8&uo=4</a>
**App Version:** 3.3.4
**Seller:** Reel Apps Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/reel-apps-inc./id529436221?uo=4">© Reel Apps Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/e5/49/f1/e549f1a2-2cf3-4c1f-46c8-288c87ca13c4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19965134/d7b16cd8-a1c5-11e6-889e-16df83966909.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19965134/d7b16cd8-a1c5-11e6-889e-16df83966909.png)
https://cloud.githubusercontent.com/assets/20930745/19965134/d7b16cd8-a1c5-11e6-889e-16df83966909.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19965164/fe243f6c-a1c5-11e6-9aa7-5451cdb988d9.png
