### ISSUE TITLE
GoToWebinar

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11045]
**App Name:** GoToWebinar
**Bundle ID:** com.logmein.gotowebinar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1244921300">1244921300</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gotowebinar/id1244921300?uo=4">https://apps.apple.com/us/app/gotowebinar/id1244921300?uo=4</a>
**App Version:** 7.5.3
**Seller:** LogMeIn, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/logmein-inc/id299616804?uo=4">© LogMeIn, Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/42/89/66/42896604-9f3e-a8dc-429c-64edb719b169/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111040797-30b16f80-8435-11eb-82cc-1289955f23c9.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111040797-30b16f80-8435-11eb-82cc-1289955f23c9.png)
https://user-images.githubusercontent.com/2068130/111040797-30b16f80-8435-11eb-82cc-1289955f23c9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111040810-4161e580-8435-11eb-8c31-161276b64b15.png
