### ISSUE TITLE
Telehealth by SimplePractice

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11044]
**App Name:** Telehealth by SimplePractice
**Bundle ID:** com.simplepractice.video
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1351373906">1351373906</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/telehealth-by-simplepractice/id1351373906?uo=4">https://apps.apple.com/us/app/telehealth-by-simplepractice/id1351373906?uo=4</a>
**App Version:** 2.5.5
**Seller:** SimplePractice LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/simplepractice-llc/id738207607?uo=4">© SimplePractice, LLC.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/1b/19/d7/1b19d7f5-ed20-9cfc-b022-1ec1d07ad0c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111042266-d7e5d500-843c-11eb-80ff-424e48f58980.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111042266-d7e5d500-843c-11eb-80ff-424e48f58980.png)
https://user-images.githubusercontent.com/2068130/111042266-d7e5d500-843c-11eb-80ff-424e48f58980.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111042280-e9c77800-843c-11eb-9f90-ceb741bcfd4a.png
