### ISSUE TITLE
Smashburger Rewards

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11041]
**App Name:** Smashburger Rewards
**Bundle ID:** com.punchh.smashburger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1207759409">1207759409</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/smashburger-rewards/id1207759409?uo=4">https://apps.apple.com/us/app/smashburger-rewards/id1207759409?uo=4</a>
**App Version:** 21.1.0
**Seller:** Smashburger AFT Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/smashburger/id1368016988?uo=4">© Smashburger</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/e1/b5/8a/e1b58a35-340e-1a69-57fd-55754c86255b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111041140-15dffa80-8437-11eb-9a0f-dae10427bfbf.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111041140-15dffa80-8437-11eb-9a0f-dae10427bfbf.png)
https://user-images.githubusercontent.com/2068130/111041140-15dffa80-8437-11eb-9a0f-dae10427bfbf.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111041159-27c19d80-8437-11eb-8860-dc4443238d47.png
