### ISSUE TITLE
Trade Republic

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#11040]
**App Name:** Trade Republic
**Bundle ID:** de.traderepublic.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1410703839">1410703839</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/trade-republic/id1410703839?uo=4">https://apps.apple.com/us/app/trade-republic/id1410703839?uo=4</a>
**App Version:** 1.80
**Seller:** Trade Republic Bank GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/trade-republic-bank-gmbh/id1273602510?uo=4">© Trade Republic Bank GmbH</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/c3/11/25/c311259c-f7b9-e947-dcb9-492b8aa26d24/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/107144257-53ce9800-693a-11eb-9e4e-0e3075222258.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/107144257-53ce9800-693a-11eb-9e4e-0e3075222258.png)
https://user-images.githubusercontent.com/2068130/107144257-53ce9800-693a-11eb-9e4e-0e3075222258.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/107144268-621cb400-693a-11eb-882e-c17fbe1db513.png
