### ISSUE TITLE
eToro Cryptocurrency Trading

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#11046]
**App Name:** eToro Cryptocurrency Trading
**Bundle ID:** com.etoro.openbook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=674984916">674984916</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/etoro-cryptocurrency-trading/id674984916?uo=4">https://apps.apple.com/us/app/etoro-cryptocurrency-trading/id674984916?uo=4</a>
**App Version:** 296.0.0
**Seller:** eToro Group Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/etoro/id491658374?uo=4">© eToro</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/2a/71/5d/2a715d0a-699c-0c0e-e46f-bc8deef15665/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111042409-8853d900-843d-11eb-981a-c641f8ecb1df.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111042409-8853d900-843d-11eb-981a-c641f8ecb1df.png)
https://user-images.githubusercontent.com/2068130/111042409-8853d900-843d-11eb-981a-c641f8ecb1df.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111042419-99044f00-843d-11eb-80c6-b73bb2412c16.png
