### ISSUE TITLE
Xcel Energy

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11043]
**App Name:** Xcel Energy
**Bundle ID:** com.ifactor.xcel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1232821763">1232821763</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/xcel-energy/id1232821763?uo=4">https://apps.apple.com/us/app/xcel-energy/id1232821763?uo=4</a>
**App Version:** 1.6.3
**Seller:** Xcel Energy Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/xcel-energy-inc/id1257181582?uo=4">© Xcel Energy Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/fc/4a/7f/fc4a7f28-c3b4-499f-f552-08ad90e0b2a2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111041030-791d5d00-8436-11eb-82d3-3e25802fb80b.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111041030-791d5d00-8436-11eb-82d3-3e25802fb80b.png)
https://user-images.githubusercontent.com/2068130/111041030-791d5d00-8436-11eb-82d3-3e25802fb80b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111041044-8cc8c380-8436-11eb-80d3-57f816c10276.png
