### ISSUE TITLE
FileBrowser Professional

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#11048]
**App Name:** FileBrowser Professional
**Bundle ID:** com.stratospherix.filebrowserbiz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=854618029">854618029</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/filebrowser-professional/id854618029?uo=4">https://apps.apple.com/us/app/filebrowser-professional/id854618029?uo=4</a>
**App Version:** 20.17
**Seller:** Stratospherix
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/stratospherix-ltd/id323133606?uo=4">© Stratospherix Ltd</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/d2/0c/78/d20c7841-8a72-6a57-9bf9-4d4c3baacb83/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111040700-9bae7680-8434-11eb-9c59-99a06aa449a2.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111040700-9bae7680-8434-11eb-9c59-99a06aa449a2.png)
https://user-images.githubusercontent.com/2068130/111040700-9bae7680-8434-11eb-9c59-99a06aa449a2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111040713-abc65600-8434-11eb-81cd-b501091bcd44.png
