### ISSUE TITLE
Skip Solitaire

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#11057]
**App Name:** Skip Solitaire
**Bundle ID:** com.skippo.game
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1462607979">1462607979</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/skip-solitaire/id1462607979?uo=4">https://apps.apple.com/us/app/skip-solitaire/id1462607979?uo=4</a>
**App Version:** 2.10
**Seller:** Goutam Shetty
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/goutam-shetty/id1315520482?uo=4">© Goutam Shetty</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/eb/6b/22/eb6b22d1-f4b7-87ea-a17b-3947acbb1433/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118389835-24f84a00-b62c-11eb-94e9-0b3810d0bf44.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118389835-24f84a00-b62c-11eb-94e9-0b3810d0bf44.png)
https://user-images.githubusercontent.com/2068130/118389835-24f84a00-b62c-11eb-94e9-0b3810d0bf44.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/118389843-36415680-b62c-11eb-878f-cd39cdb3d5bb.png
