### ISSUE TITLE
Confluence Cloud

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11054]
**App Name:** Confluence Cloud
**Bundle ID:** com.atlassian.confluence.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1006971684">1006971684</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/confluence-cloud/id1006971684?uo=4">https://apps.apple.com/us/app/confluence-cloud/id1006971684?uo=4</a>
**App Version:** 2.81.0
**Seller:** Atlassian Pty Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/atlassian/id528455733?uo=4">© Atlassian</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/07/76/0b/07760b3c-4616-b911-fa42-1822f6271ffb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111042001-63f6fd00-843b-11eb-8c01-52d5f181a21a.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111042001-63f6fd00-843b-11eb-8c01-52d5f181a21a.png)
https://user-images.githubusercontent.com/2068130/111042001-63f6fd00-843b-11eb-8c01-52d5f181a21a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111042016-740edc80-843b-11eb-8946-1c47b6e13fd4.png
