### ISSUE TITLE
Hype Machine

### ISSUE THREAD

**Issue by xLemonBeanx** [glasklart/hd#1105]
**App Name:** Hype Machine
**Bundle ID:** com.hypem.hyperadio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=414315986">414315986</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hype-machine/id414315986?mt=8&uo=4">https://itunes.apple.com/us/app/hype-machine/id414315986?mt=8&uo=4</a>
**App Version:** 2.6.13
**Seller:** The Hype Machine, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-hype-machine-inc/id414315989?uo=4">© The Hype Machine, Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/e9/db/f2/e9dbf284-8857-90a3-9d98-ca4f547e2117/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19965326/c0f15566-a1c6-11e6-87d3-158eb3bf3db1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19965326/c0f15566-a1c6-11e6-87d3-158eb3bf3db1.png)
https://cloud.githubusercontent.com/assets/20930745/19965326/c0f15566-a1c6-11e6-87d3-158eb3bf3db1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19965349/e0aaa240-a1c6-11e6-93f3-d1eccb93aa4e.png
