### ISSUE TITLE
bebird

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#11053]
**App Name:** bebird
**Bundle ID:** com.hfzzkj.bebird
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1444627859">1444627859</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bebird/id1444627859?uo=4">https://apps.apple.com/us/app/bebird/id1444627859?uo=4</a>
**App Version:** 4.3.20
**Seller:** Black Bee Intelligent Manufacturing (Shenzhen) Technology Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/black-bee-intelligent-manufacturing-shenzhen-technology/id1456594404?uo=4">© Black Bee Intelligent Manufacturing (Shenzhen) Technology Co., Ltd.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/59/05/3c/59053c83-a509-cf6c-c158-58935d48e64f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111043881-665e5480-8445-11eb-9253-9df3e89c36c9.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111043881-665e5480-8445-11eb-9253-9df3e89c36c9.png)
https://user-images.githubusercontent.com/2068130/111043881-665e5480-8445-11eb-9253-9df3e89c36c9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111043889-770eca80-8445-11eb-8d4a-47cb59fd2ce8.png
