### ISSUE TITLE
SYNA-G CLOUD

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#11059]
**App Name:** SYNA-G CLOUD
**Bundle ID:** com.maxspect.wifilight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1472134425">1472134425</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/syna-g-cloud/id1472134425?uo=4">https://apps.apple.com/us/app/syna-g-cloud/id1472134425?uo=4</a>
**App Version:** 1.0.9
**Seller:** Guangzhou Maxspect Electronic Technology Co., LTD
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/maxspect/id1080917074?uo=4">© Maxspect</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/27/ff/51/27ff519c-ef77-1deb-6bc4-992db60df162/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/114507563-4c10c580-9c01-11eb-944e-a2e7e55790a3.png)

**Comment by XPEric** [comment]
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/114507563-4c10c580-9c01-11eb-944e-a2e7e55790a3.png)
https://user-images.githubusercontent.com/2313873/114507563-4c10c580-9c01-11eb-944e-a2e7e55790a3.png
___
Source:
https://user-images.githubusercontent.com/2313873/114507502-37ccc880-9c01-11eb-8c9a-2ce6391139e0.png
