### ISSUE TITLE
Gymondo: Fitness & Yoga

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#11052]
**App Name:** Gymondo: Fitness & Yoga
**Bundle ID:** de.gymondo.Gymondo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1011796416">1011796416</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gymondo-fitness-yoga/id1011796416?uo=4">https://apps.apple.com/us/app/gymondo-fitness-yoga/id1011796416?uo=4</a>
**App Version:** 5.4.0
**Seller:** Gymondo GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gymondo/id1011796415?uo=4">© Gymondo</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/1f/c1/92/1fc19226-3308-5397-f981-c24889a0f80b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111040583-d95ecf80-8433-11eb-93f8-614945accbc5.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/111040583-d95ecf80-8433-11eb-93f8-614945accbc5.png)
https://user-images.githubusercontent.com/2068130/111040583-d95ecf80-8433-11eb-93f8-614945accbc5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/111040594-ef6c9000-8433-11eb-814d-2d4eae236f85.png
