### ISSUE TITLE
GoodNotes 5

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#11051]
**App Name:** GoodNotes 5
**Bundle ID:** com.goodnotesapp.x
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1444383602">1444383602</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/goodnotes-5/id1444383602?uo=4">https://apps.apple.com/us/app/goodnotes-5/id1444383602?uo=4</a>
**App Version:** 5.6.40
**Seller:** Time Base Technology Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/time-base-technology-limited/id424587624?uo=4">© Time Base Technology Limited</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/77/11/8f/77118f0d-1af9-912a-ed4d-bffd1a1c9939/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118390004-1a8a8000-b62d-11eb-9d26-ad8d69e957be.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118390004-1a8a8000-b62d-11eb-9d26-ad8d69e957be.png)
https://user-images.githubusercontent.com/2068130/118390004-1a8a8000-b62d-11eb-9d26-ad8d69e957be.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/118390010-28d89c00-b62d-11eb-88d2-c864cb30b105.png
