### ISSUE TITLE
MotoGP™

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#11067]
**App Name:** MotoGP™
**Bundle ID:** com.dorna.officialMotoGP
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1157573265">1157573265</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/motogp/id1157573265?uo=4">https://apps.apple.com/us/app/motogp/id1157573265?uo=4</a>
**App Version:** 1.15.4
**Seller:** Dorna Sports S.L.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dorna-sports-s-l/id484039864?uo=4">© Dorna Sports S.L.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/77/09/77/770977e7-aa73-13cf-cf20-3f614839bbf9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118390555-009e6c80-b630-11eb-9960-1375eb140277.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118390555-009e6c80-b630-11eb-9960-1375eb140277.png)
https://user-images.githubusercontent.com/2068130/118390555-009e6c80-b630-11eb-9960-1375eb140277.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/118390567-114ee280-b630-11eb-9399-df33e4eca4a5.png
