### ISSUE TITLE
Formula 1®

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#11066]
**App Name:** Formula 1®
**Bundle ID:** com.fodmltd.OfficialF1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=835022598">835022598</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/formula-1/id835022598?uo=4">https://apps.apple.com/us/app/formula-1/id835022598?uo=4</a>
**App Version:** 11.20.2
**Seller:** Formula One Digital Media Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/formula-one-digital-media-limited/id835022601?uo=4">© Formula One Digital Media Limited</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/ec/ff/ef/ecffefce-d181-cf17-bc74-dde85fea40ec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118390682-ac47bc80-b630-11eb-8667-555069217db8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118390682-ac47bc80-b630-11eb-8667-555069217db8.png)
https://user-images.githubusercontent.com/2068130/118390682-ac47bc80-b630-11eb-8667-555069217db8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/118390697-bc5f9c00-b630-11eb-97f0-779d019ed20f.png
