### ISSUE TITLE
Smart Reef

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#11060]
**App Name:** Smart Reef
**Bundle ID:** com.reeffactory.smartreef
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1480355166">1480355166</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/smart-reef/id1480355166?uo=4">https://apps.apple.com/us/app/smart-reef/id1480355166?uo=4</a>
**App Version:** 1.0
**Seller:** Reef Factory sp. z o.o.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/reef-factory-sp-z-o-o/id1367901113?uo=4">© Reef Factory sp. z o.o.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/92/18/a8/9218a8c3-4410-b5ad-a0da-2488ae882203/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120081755-75a58380-c0bf-11eb-9f0c-f18a9310589f.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120081755-75a58380-c0bf-11eb-9f0c-f18a9310589f.png)
https://user-images.githubusercontent.com/2068130/120081755-75a58380-c0bf-11eb-9f0c-f18a9310589f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/120081763-848c3600-c0bf-11eb-9e26-ebc7fc9c826a.png
