### ISSUE TITLE
Meross

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11069]
**App Name:** Meross
**Bundle ID:** com.meross.Meross
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1260842951">1260842951</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/meross/id1260842951?uo=4">https://apps.apple.com/us/app/meross/id1260842951?uo=4</a>
**App Version:** 2.26.0
**Seller:** Chengdu Meross Technology Co.,Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/chengdu-meross-technology-co-ltd/id1260842710?uo=4">© Chengdu Meross Technology Co.,Ltd.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple125/v4/23/43/83/23438364-796d-2618-5ae8-308d6e6538c7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118391595-5d505600-b635-11eb-831e-127f808647bc.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118391595-5d505600-b635-11eb-831e-127f808647bc.png)
https://user-images.githubusercontent.com/2068130/118391595-5d505600-b635-11eb-831e-127f808647bc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/118391601-6b9e7200-b635-11eb-9c23-1bf60dba12be.png
