### ISSUE TITLE
Stats: For Model S/X/3/Y

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11073]
**App Name:** Stats: For Model S/X/3/Y
**Bundle ID:** maadotaa.TeslaSwift
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1191100729">1191100729</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stats-for-model-s-x-3-y/id1191100729?uo=4">https://apps.apple.com/us/app/stats-for-model-s-x-3-y/id1191100729?uo=4</a>
**App Version:** 5.3
**Seller:** Popak Roshan
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/maadotaa/id488542017?uo=4">© MaaDoTaa</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/d6/03/a3/d603a3a5-f8d9-3046-cc14-a3c7de07d882/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120080344-b9e15580-c0b8-11eb-873b-f8eaf9e1763d.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120080344-b9e15580-c0b8-11eb-873b-f8eaf9e1763d.png)
https://user-images.githubusercontent.com/2068130/120080344-b9e15580-c0b8-11eb-873b-f8eaf9e1763d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/120080351-c9f93500-c0b8-11eb-9bcd-fe28553dcb1c.png
