### ISSUE TITLE
Cam Viewer for Tesla

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11072]
**App Name:** Cam Viewer for Tesla
**Bundle ID:** com.cgbits.teslacam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1476197999">1476197999</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cam-viewer-for-tesla/id1476197999?uo=4">https://apps.apple.com/us/app/cam-viewer-for-tesla/id1476197999?uo=4</a>
**App Version:** 1.2
**Seller:** cgBits  LLC (UT)
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cgbits/id793604295?uo=4">© cgBits</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/89/a5/cc/89a5cc48-df0f-f460-f0d2-f79b27268e79/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120080210-1d1eb800-c0b8-11eb-8b5c-b40fb63145bd.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120080210-1d1eb800-c0b8-11eb-8b5c-b40fb63145bd.png)
https://user-images.githubusercontent.com/2068130/120080210-1d1eb800-c0b8-11eb-8b5c-b40fb63145bd.png
--- ---
Source:
![com cgbits teslacam_orig_big-01](https://user-images.githubusercontent.com/2068130/120080231-2dcf2e00-c0b8-11eb-8d28-d9f90e33cd65.png)
