### ISSUE TITLE
RingCentral - Glip and Office

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11070]
**App Name:** RingCentral - Glip and Office
**Bundle ID:** com.glip.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=715886894">715886894</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ringcentral-glip-and-office/id715886894?uo=4">https://apps.apple.com/us/app/ringcentral-glip-and-office/id715886894?uo=4</a>
**App Version:** 21.2.15
**Seller:** RingCentral, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ringcentral-inc/id293305987?uo=4">© RingCentral, Inc</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple115/v4/98/5a/4d/985a4d46-9661-c6c2-79f1-b112382dab00/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118390825-7eaf4300-b631-11eb-9f23-ed6f04232bd8.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118390825-7eaf4300-b631-11eb-9f23-ed6f04232bd8.png)
https://user-images.githubusercontent.com/2068130/118390825-7eaf4300-b631-11eb-9f23-ed6f04232bd8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/118390843-8ec72280-b631-11eb-9de9-ee2292775ece.png
