### ISSUE TITLE
Accounts 2 Checkbook

### ISSUE THREAD

**Issue by xLemonBeanx** [glasklart/hd#1107]
**App Name:** Accounts 2 Checkbook
**Bundle ID:** com.SVTSoftware.Accounts2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=494333145">494333145</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/accounts-2-checkbook/id494333145?mt=8&uo=4">https://itunes.apple.com/us/app/accounts-2-checkbook/id494333145?mt=8&uo=4</a>
**App Version:** 5.5
**Seller:** Steve Tran
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/svt-software/id286029963?uo=4>© SVT Software</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/d2/6f/64/d26f647c-287d-d5fe-7fa6-0b77a6c88494/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617572/032b9af0-9834-11e6-90db-f7e02a1e2b11.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617572/032b9af0-9834-11e6-90db-f7e02a1e2b11.png)
https://cloud.githubusercontent.com/assets/20930745/19617572/032b9af0-9834-11e6-90db-f7e02a1e2b11.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617577/1c5577f8-9834-11e6-9fd4-fcd37f10394c.png
