### ISSUE TITLE
AutoMate for Tesla

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11075]
**App Name:** AutoMate for Tesla
**Bundle ID:** com.HamblinSoft.TeslaApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1382111619">1382111619</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/automate-for-tesla/id1382111619?uo=4">https://apps.apple.com/us/app/automate-for-tesla/id1382111619?uo=4</a>
**App Version:** 2.6.2
**Seller:** Jaren Hamblin
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/jaren-hamblin/id1382111618?uo=4">© Jaren Hamblin</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/33/a5/7e/33a57e94-ad02-cb62-bc98-40648d5f0169/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120079962-c795db80-c0b6-11eb-825d-45b9f5368e57.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120079962-c795db80-c0b6-11eb-825d-45b9f5368e57.png)
https://user-images.githubusercontent.com/2068130/120079962-c795db80-c0b6-11eb-825d-45b9f5368e57.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/120079976-d7152480-c0b6-11eb-8b4a-2e2d0912d453.png
