### ISSUE TITLE
ADP Mobile Solutions

### ISSUE THREAD

**Issue by xLemonBeanx** [glasklart/hd#1108]
**App Name:** ADP Mobile Solutions
**Bundle ID:** com.adp.adpmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444553167">444553167</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adp-mobile-solutions/id444553167?mt=8&uo=4">https://itunes.apple.com/us/app/adp-mobile-solutions/id444553167?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** ADP, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adp-inc/id363884520?uo=4>© ADP, Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/f4/41/cd/f441cda9-e1fe-2fae-d422-e6f96cee6ce2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18892127/93587902-8508-11e6-9110-9541cc9bd2e1.png)

**Comment by illinikev** [comment]
Icon needs update

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18892127/93587902-8508-11e6-9110-9541cc9bd2e1.png)
https://cloud.githubusercontent.com/assets/22012363/18892127/93587902-8508-11e6-9110-9541cc9bd2e1.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18892130/96fd7b16-8508-11e6-9536-e58ba8680f37.png
