### ISSUE TITLE
Angry Birds Reloaded

### ISSUE THREAD

**Issue by melongirl** [glasklart/hd#11088]
**App Name:** Angry Birds Reloaded
**Bundle ID:** com.rovio.abreloaded
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1539172625">1539172625</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/angry-birds-reloaded/id1539172625?uo=4">https://apps.apple.com/us/app/angry-birds-reloaded/id1539172625?uo=4</a>
**App Version:** 1.2
**Seller:** Rovio Entertainment Oyj
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/rovio-entertainment-oyj/id298910979?uo=4">© Rovio Entertainment Oyj</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/13/56/0d/13560df7-dd30-21e5-a2dc-b4196e88728c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18983976/33e652b6-86f0-11e6-8876-5933115c005a.png)

**Comment by dreamnet** [comment]
Same as #6126
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18983976/33e652b6-86f0-11e6-8876-5933115c005a.png)
https://cloud.githubusercontent.com/assets/20930745/18983976/33e652b6-86f0-11e6-8876-5933115c005a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/20930745/18984001/4b4262ba-86f0-11e6-8528-eafdf304ef36.png
