### ISSUE TITLE
Afterpay: Shop now. Pay later.

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#11084]
**App Name:** Afterpay: Shop now. Pay later.
**Bundle ID:** com.afterpay.afterpay-consumer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1230286588">1230286588</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/au/app/afterpay-shop-now-pay-later/id1230286588?uo=4">https://apps.apple.com/au/app/afterpay-shop-now-pay-later/id1230286588?uo=4</a>
**App Version:** 1.38.0
**Seller:** Afterpay Holdings Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/au/developer/afterpay/id1221203041?uo=4">© Afterpay</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/3e/03/25/3e032599-6c53-304a-411f-209fa0788c77/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/139575657-bed8d018-2948-4a73-b014-2746945e2348.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/139575657-bed8d018-2948-4a73-b014-2746945e2348.png)
https://user-images.githubusercontent.com/2068130/139575657-bed8d018-2948-4a73-b014-2746945e2348.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/139575674-714ed3bb-f97c-42e0-a24b-ab3030ab3f3f.png)
