### ISSUE TITLE
Luxury Escapes: Travel Deals

### ISSUE THREAD

**Issue by EmpDns** [glasklart/hd#11083]
**App Name:** Luxury Escapes: Travel Deals
**Bundle ID:** au.com.aussiecommerce.luxuryescapes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1052970346">1052970346</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/luxury-escapes-travel-deals/id1052970346?uo=4">https://apps.apple.com/us/app/luxury-escapes-travel-deals/id1052970346?uo=4</a>
**App Version:** 8.5.3
**Seller:** Lux Group Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lux-group-limited/id975898870?uo=4">© Lux Group Limited</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/ea/47/de/ea47de43-882d-e00d-cab3-f9963186ec01/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/139575843-2f34b875-b9ff-4e43-bfde-81bb4b1379c7.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/139575843-2f34b875-b9ff-4e43-bfde-81bb4b1379c7.png)
https://user-images.githubusercontent.com/2068130/139575843-2f34b875-b9ff-4e43-bfde-81bb4b1379c7.png
--- ---
Source:
![au com aussiecommerce luxuryescapes_orig_big-01](https://user-images.githubusercontent.com/2068130/139575858-1b209f76-cd1c-49d7-add3-20cb1e47ef1b.png)
