### ISSUE TITLE
TIAA

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#11092]
**App Name:** TIAA
**Bundle ID:** org.tiaa-cref.invest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=341447597">341447597</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tiaa/id341447597?uo=4">https://apps.apple.com/us/app/tiaa/id341447597?uo=4</a>
**App Version:** 21.07.1
**Seller:** Teachers Insurance and Annuity Association America
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tiaa/id341447600?uo=4">© TIAA</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/49/ef/24/49ef241b-c0b5-16b3-0326-7cd149256204/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/139575395-5b0cc199-69b3-4d68-baa9-9ff8e2f305c5.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/139575395-5b0cc199-69b3-4d68-baa9-9ff8e2f305c5.png)
https://user-images.githubusercontent.com/2068130/139575395-5b0cc199-69b3-4d68-baa9-9ff8e2f305c5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/139575427-d96bd3d8-2d04-4e99-a17a-441fa9b1ec70.png
