### ISSUE TITLE
TouchTunes

### ISSUE THREAD

**Issue by xLemonBeanx** [glasklart/hd#1109]
**App Name:** TouchTunes
**Bundle ID:** com.touchtunes.mytouchtunesRD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378351144">378351144</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touchtunes/id378351144?mt=8&uo=4">https://itunes.apple.com/us/app/touchtunes/id378351144?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** TouchTunes
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/touchtunes-interactive-network/id378351147?uo=4>© TouchTunes Interactive Network</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/e4/c6/fe/e4c6feaf-206b-e231-7769-e01ccf190be0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617602/161cd5c4-9835-11e6-9ed0-1335ba1c19d1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617602/161cd5c4-9835-11e6-9ed0-1335ba1c19d1.png)
https://cloud.githubusercontent.com/assets/20930745/19617602/161cd5c4-9835-11e6-9ed0-1335ba1c19d1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617604/2af104a2-9835-11e6-9460-03fa3ea677c6.png
