### ISSUE TITLE
Northwest Federal's Mobile Banking

### ISSUE THREAD

**Issue by xLemonBeanx** [glasklart/hd#1110]
**App Name:** Northwest Federal’s Mobile Banking
**Bundle ID:** com.nwfcu.mfm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=576019232">576019232</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/northwest-federals-mobile-banking/id576019232?mt=8&uo=4">https://itunes.apple.com/us/app/northwest-federals-mobile-banking/id576019232?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** Northwest Federal Credit Union
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/northwest-federal-credit-union/id576019235?uo=4">© Northwest Federal Credit Union</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/b6/66/ca/b666ca1d-e2a8-b822-cbf3-81199089be00/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688281-17c76f42-c6ce-11e7-8683-6f70a63a21f1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688281-17c76f42-c6ce-11e7-8683-6f70a63a21f1.png)
https://user-images.githubusercontent.com/2068130/32688281-17c76f42-c6ce-11e7-8683-6f70a63a21f1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32688284-2715658a-c6ce-11e7-8cb5-768067b7b54f.png
