### ISSUE TITLE
Mail+ for Outlook

### ISSUE THREAD

**Issue by xLemonBeanx** [glasklart/hd#1111]
**App Name:** Mail+ for Outlook
**Bundle ID:** com.mspecht.OWA
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=428974099">428974099</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mail-for-outlook/id428974099?mt=8&uo=4">https://itunes.apple.com/us/app/mail-for-outlook/id428974099?mt=8&uo=4</a>
**App Version:** 3.6.6
**Seller:** iKonic Apps LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ikonic-apps-llc/id359873852?uo=4">© iKonic Apps LLC</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple22/v4/14/73/ad/1473ad4c-d702-fbe6-05de-a0eec32ff459/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39070082-4217e8ca-44e2-11e8-914c-dd94a5f7b35f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39070082-4217e8ca-44e2-11e8-914c-dd94a5f7b35f.png)
https://user-images.githubusercontent.com/20930745/39070082-4217e8ca-44e2-11e8-914c-dd94a5f7b35f.png

Source:
https://user-images.githubusercontent.com/20930745/39070106-561ec30c-44e2-11e8-8c0e-ba1b0ff87d9e.png
