### ISSUE TITLE
AlloCiné : Cinéma et Séries

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#112]
**App Name:** AlloCiné : Cinéma et Séries
**Bundle ID:** com.allocine.applifrance
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=351184863">351184863</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/allocin%C3%A9-cin%C3%A9ma-et-s%C3%A9ries/id351184863?uo=4">https://apps.apple.com/us/app/allocin%C3%A9-cin%C3%A9ma-et-s%C3%A9ries/id351184863?uo=4</a>
**App Version:** 7.6.3
**Seller:** AlloCine
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/allocin%C3%A9/id351184866?uo=4">© AlloCiné</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/fd/e5/9a/fde59a6b-b566-ec67-9142-1ddc743debab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979270-cbc14080-95e5-11e9-8677-a3decfc8be33.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20110327/41ae1056-a5e4-11e6-9cf8-fbde5235a4bc.png)
https://cloud.githubusercontent.com/assets/20930745/20110327/41ae1056-a5e4-11e6-9cf8-fbde5235a4bc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20110352/5715e400-a5e4-11e6-9fca-8cbce6a5122c.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979270-cbc14080-95e5-11e9-8677-a3decfc8be33.png)
https://user-images.githubusercontent.com/2068130/59979270-cbc14080-95e5-11e9-8677-a3decfc8be33.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979272-db408980-95e5-11e9-9471-9ac7d3b07d45.png
