### ISSUE TITLE
System Status - battery, memory, CPU & data usage

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#1124]
**App Name:** System Status - battery, memory, CPU & data usage
**Bundle ID:** net.techet.sysstat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401457165">401457165</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/system-status-battery-memory/id401457165?mt=8&uo=4">https://itunes.apple.com/us/app/system-status-battery-memory/id401457165?mt=8&uo=4</a>
**App Version:** 5.5
**Seller:** Jiri Techet
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/techet/id401457168?uo=4">© Techet</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/36/0c/b3/360cb3c3-d983-c13f-3be2-b984d5fb951e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19919475/5e23d04c-a0d3-11e6-81b4-ec984bb131e0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19919475/5e23d04c-a0d3-11e6-81b4-ec984bb131e0.png)
https://cloud.githubusercontent.com/assets/20930745/19919475/5e23d04c-a0d3-11e6-81b4-ec984bb131e0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19919494/7968c8c6-a0d3-11e6-838f-93ece597dd50.png
