### ISSUE TITLE
QR Reader for iPhone (Premium)

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#1126]
**App Name:** QR Reader for iPhone (Premium)
**Bundle ID:** com.TapMediaLtd.QRReaderPremium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=429671513">429671513</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qr-reader-for-iphone-premium/id429671513?mt=8&uo=4">https://itunes.apple.com/us/app/qr-reader-for-iphone-premium/id429671513?mt=8&uo=4</a>
**App Version:** 5.9
**Seller:** TapMedia Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tapmedia-ltd/id359632753?uo=4>© TapMedia Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/2f/29/11/2f29112b-48bd-588d-221e-555452c2e40e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617649/6d485cbe-9836-11e6-9f5a-58e3c56568b8.png)

**Comment by 2Qt2beStr8** [comment]
same as #7928 .. icon by @2Qt2beStr8

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617649/6d485cbe-9836-11e6-9f5a-58e3c56568b8.png)
https://cloud.githubusercontent.com/assets/20930745/19617649/6d485cbe-9836-11e6-9f5a-58e3c56568b8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617654/8a655888-9836-11e6-89cf-953a9b458716.png
