### ISSUE TITLE
NRK P3

### ISSUE THREAD

**Issue by Hawri84** [glasklart/hd#1127]
**App Name:** NRK P3
**Bundle ID:** no.nrk.nrkp3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401931240">401931240</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nrk-p3/id401931240?mt=8&uo=4">https://itunes.apple.com/us/app/nrk-p3/id401931240?mt=8&uo=4</a>
**App Version:** 3.04
**Seller:** Norsk Rikskringkasting As
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nrk/id385114901?uo=4>© NRK</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/4c/17/78/4c17785d-7b24-45c1-ce98-18479719a1b7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617716/06ca346a-9838-11e6-9a4f-1dd63c56264f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617716/06ca346a-9838-11e6-9a4f-1dd63c56264f.png)
https://cloud.githubusercontent.com/assets/20930745/19617716/06ca346a-9838-11e6-9a4f-1dd63c56264f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617723/37325ab0-9838-11e6-9cb2-5575dc37b797.png
