### ISSUE TITLE
MinStrøm

### ISSUE THREAD

**Issue by Hawri84** [glasklart/hd#1129]
**App Name:** MinStrøm
**Bundle ID:** no.kraftinor.Kraftinor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=560980673">560980673</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minstr%C3%B8m/id560980673?mt=8&uo=4">https://itunes.apple.com/us/app/minstr%C3%B8m/id560980673?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Kraftinor AS
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kraftinor-as/id560980676?uo=4">© Kraftinor AS</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple3/v4/e3/b6/3d/e3b63dc1-a024-8e86-943a-56b4a15a3a76/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39381291-e71f070c-4a61-11e8-8050-d5c10ce3adcf.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39381291-e71f070c-4a61-11e8-8050-d5c10ce3adcf.png)
https://user-images.githubusercontent.com/2068130/39381291-e71f070c-4a61-11e8-8050-d5c10ce3adcf.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39381313-f611fa26-4a61-11e8-9b37-0abd245c29e0.png
