### ISSUE TITLE
Altimeter+

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#1130]
**App Name:** Altimeter+
**Bundle ID:** sichtwerk.com.altimeter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417204570">417204570</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/altimeter+/id417204570?mt=8&uo=4">https://itunes.apple.com/us/app/altimeter+/id417204570?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Sichtwerk AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sichtwerk-ag/id410851296?uo=4>© Sichtwerk AG</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/64/8a/98/648a9837-1812-8b33-6f23-5b159f730a32/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18740979/d7403c50-80ac-11e6-8dba-9b2ee8457542.png)

**Comment by Sly-Fi** [comment]
This icon is missing from 5.0.0 release

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18740979/d7403c50-80ac-11e6-8dba-9b2ee8457542.png)
https://cloud.githubusercontent.com/assets/20930745/18740979/d7403c50-80ac-11e6-8dba-9b2ee8457542.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18740988/e89b7b68-80ac-11e6-87e9-d38af985d390.png
