### ISSUE TITLE
Avinor

### ISSUE THREAD

**Issue by Hawri84** [glasklart/hd#1131]
**App Name:** Avinor
**Bundle ID:** no.avinor.AvinorFlights
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=399221622">399221622</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/avinor/id399221622?mt=8&uo=4">https://itunes.apple.com/us/app/avinor/id399221622?mt=8&uo=4</a>
**App Version:** 5.2.1
**Seller:** Avinor AS
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/avinor-as/id399221625?uo=4">© Avinor AS</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/82/52/d1/8252d189-337e-bf05-e9f4-fbaca102246e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38456666-61182b3c-3a87-11e8-94b5-25bd578aaeb6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19965739/b9502e3e-a1c8-11e6-94c1-6c3c386edf52.png)
https://cloud.githubusercontent.com/assets/20930745/19965739/b9502e3e-a1c8-11e6-94c1-6c3c386edf52.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19965771/cfd75d94-a1c8-11e6-92d5-81c692f6b9a7.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38456666-61182b3c-3a87-11e8-94b5-25bd578aaeb6.png)
https://user-images.githubusercontent.com/20930745/38456666-61182b3c-3a87-11e8-94b5-25bd578aaeb6.png

Source:
https://user-images.githubusercontent.com/20930745/38456675-73e7ab2a-3a87-11e8-89d2-e6a4f99c09d1.png
