### ISSUE TITLE
iRega

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#1132]
**App Name:** iRega
**Bundle ID:** ch.rega.Rega
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=415358154">415358154</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ch/app/irega/id415358154?mt=8&uo=4">https://itunes.apple.com/ch/app/irega/id415358154?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Schweizerische Rettungflugwacht, Rega
**Developer:** <a target="_blank" href="https://itunes.apple.com/ch/developer/schweizerische-rettungsflugwacht/id415358158?uo=4">© Schweizerische Rettungsflugwacht Rega</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/a4/1c/9e/a41c9e39-3e0e-f28d-24e6-7b848413f231/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19965662/67bdcd1a-a1c8-11e6-8b1f-59bb6a25552e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19965662/67bdcd1a-a1c8-11e6-8b1f-59bb6a25552e.png)
https://cloud.githubusercontent.com/assets/20930745/19965662/67bdcd1a-a1c8-11e6-8b1f-59bb6a25552e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19965682/7f0ddd66-a1c8-11e6-8fe0-655e5cddd21f.png
