### ISSUE TITLE
SBB Mobile

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#1133]
**App Name:** SBB Mobile
**Bundle ID:** 5Q4J53EFRC.com.sbb.ch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=294855237">294855237</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sbb-mobile/id294855237?mt=8&uo=4">https://itunes.apple.com/us/app/sbb-mobile/id294855237?mt=8&uo=4</a>
**App Version:** 5.3.2
**Seller:** SBB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sbb-ag/id294855240?uo=4>© SBB AG</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/73/f4/c1/73f4c12f-3d3e-541c-a598-839c8c5f8357/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19400469/a5b59d72-9256-11e6-871d-e25a95dbdcca.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19400469/a5b59d72-9256-11e6-871d-e25a95dbdcca.png)
https://cloud.githubusercontent.com/assets/20930745/19400469/a5b59d72-9256-11e6-871d-e25a95dbdcca.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19400484/b2fa3754-9256-11e6-8b5d-389582bcd753.png
