### ISSUE TITLE
Way of Life - The Ultimate Habit Maker & Breaker

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1134]
**App Name:** Way of Life - The Ultimate Habit Maker & Breaker
**Bundle ID:** com.larsparendt.wayoflife
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393159800">393159800</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/way-life-ultimate-habit-maker/id393159800?mt=8&uo=4">https://itunes.apple.com/us/app/way-life-ultimate-habit-maker/id393159800?mt=8&uo=4</a>
**App Version:** 3.4.5
**Seller:** Way of Life ApS
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/way-of-life-aps/id1019100462?uo=4">© Way of Life ApS</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/a6/cc/a0/a6cca0a3-5155-4250-b742-dfcd591db700/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19965892/706914a0-a1c9-11e6-9ded-b775535449be.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19965892/706914a0-a1c9-11e6-9ded-b775535449be.png)
https://cloud.githubusercontent.com/assets/20930745/19965892/706914a0-a1c9-11e6-9ded-b775535449be.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19965905/87b56fb4-a1c9-11e6-8cdc-7406dc67877b.png
