### ISSUE TITLE
Any.do - To-Do List, Task Manager, Daily Reminders & Checklist Organizer

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1137]
**App Name:** Any.do - To-Do List, Task Manager, Daily Reminders & Checklist Organizer
**Bundle ID:** com.anydo.AnyDO
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=497328576">497328576</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/any.do-to-do-list-task-manager/id497328576?mt=8&uo=4">https://itunes.apple.com/us/app/any.do-to-do-list-task-manager/id497328576?mt=8&uo=4</a>
**App Version:** 2.3.0
**Seller:** Any.DO inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/any.do/id497328579?uo=4>© Any.DO</a>
**Supported Devices:** iPadThirdGen4G, iPadFourthGen, iPhone6Plus, iPadMini, iPad23G, iPadThirdGen, iPhone5, iPhone5c, iPhone5s, iPhone4S, iPhone6, iPhone4, iPodTouchFifthGen, iPad2Wifi, iPadFourthGen4G, iPadMini4G
**Original Artwork:**
<img src="http://a282.phobos.apple.com/us/r30/Purple3/v4/76/f5/df/76f5df95-7097-b493-b178-bc417156eb6d/mzl.ynywmzqs.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6769585/4122e156-d0a3-11e4-80e5-b01fe5a14a5a.png)

**Comment by dreamnet** [comment]
Icon update:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6769585/4122e156-d0a3-11e4-80e5-b01fe5a14a5a.png)
https://cloud.githubusercontent.com/assets/2068130/6769585/4122e156-d0a3-11e4-80e5-b01fe5a14a5a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6769587/4fdbffde-d0a3-11e4-9e69-a4e60ebde1b6.png
