### ISSUE TITLE
Glasklart HD Wiki

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#1138]
/cc @jfelchner @dreamnet @vinstic 

So we're going to start using the wiki feature of github to break down the readme into more accessible (and linkable) sections.

Everybody (maintainers) is welcome to have a go. I'll start with the "getting artwork" section, but I might not be able to do that for a few days. We should aim to have a complete wiki that we can use to educate newcomer contributors on any foreseeable questions they have.

**Comment by PolarisBeaver** [comment]
@MagnaMike Yes I can see the New Page button. I'll work on a guide a little later, will be out for the week starting tomorrow!

**Comment by MagnaMike** [comment]
@PolarisBeaver Sounds good. No rush :+1:

**Comment by MagnaMike** [comment]
Closing for now.

**Comment by ivanov007** [comment]
added a [new method to find the iTunes ID] (https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request#finding-the-itunes-id-on-the-itunes-app-store-pc) can someone check if it make sense (English is not my home language so I might have an error or two :wink:)

**Comment by jfelchner** [comment]
@ivanov007 and as far as I've found, AppInfo no longer even works on iOS 8 😥

**Comment by ivanov007** [comment]
@jfelchner it works just for cydia apps

**Comment by ivanov007** [comment]
I've removed the reference for AppInfo from the app store icon request, and added some AppInfo instructions to the cydia request

**Comment by dreamnet** [comment]
@ivanov007 Good, makes sense to me. :+1:

**Comment by jfelchner** [comment]
@ivanov007 👍🏻😄

**Comment by ivanov007** [comment]
ok, closing this until something new comes up

**Comment by ivanov007** [comment]
Hi @dreamnet , just noticed the wiki [references to a guide ](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#guidelines)on [your site](http://glasklarthd.dreamnet.at/how-to-make-an-icon) but the link is broken, do you know if the link changed or something?

**Comment by dreamnet** [comment]
@ivanov007 I deactivated the page some time ago, because in my thoughts it was outdatet - didn't remeber that the Glasklart WIKI point's to this page. Anyway, I have re-activated the page.

**Comment by ivanov007** [comment]
not a problem, I just copied the guide to a new wiki page so if you decide to remove it won't be a problem
