### ISSUE TITLE
Dailymotion

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#114]
**App Name:** Dailymotion
**Bundle ID:** com.dailymotion.dailymotion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336978041">336978041</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dailymotion/id336978041?mt=8&uo=4">https://itunes.apple.com/us/app/dailymotion/id336978041?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** Dailymotion
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dailymotion-s.a./id336978044?uo=4>© Dailymotion S.A.</a>
**Supported Devices:** iPhone6, iPad23G, iPhone5, iPhone5s, iPadThirdGen4G, iPhone6Plus, iPhone4S, iPad2Wifi, iPadThirdGen, iPadMini, iPadFourthGen, iPadMini4G, iPhone5c, iPhone4, iPodTouchFifthGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/36/8d/42/368d42df-057a-c72e-7e59-b857d36478ed/mzl.yintwzlm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8386975/30b0f6b6-1c55-11e5-8c4f-7309c3bf571a.png)

**Comment by Trubbel** [comment]
Icon need to be updated.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8386975/30b0f6b6-1c55-11e5-8c4f-7309c3bf571a.png)
https://cloud.githubusercontent.com/assets/2068130/8386975/30b0f6b6-1c55-11e5-8c4f-7309c3bf571a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8386982/3e59e11a-1c55-11e5-85de-6086aa9a09e5.png
