### ISSUE TITLE
Slender Rising

### ISSUE THREAD

**Issue by PaulBanks** [glasklart/hd#1141]
**App Name:** Slender Rising
**Bundle ID:** com.hegi.scaregame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571640421">571640421</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slender-rising/id571640421?mt=8&uo=4">https://itunes.apple.com/us/app/slender-rising/id571640421?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Michael Hegemann
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/michael-hegemann/id425842032?uo=4">© Michael Hegemann</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/0a/c8/56/0ac856bc-ddad-e217-120b-378fc5c56c3c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21752820/79d3ba46-d5df-11e6-9f1f-42946d8cdcf0.png)

**Comment by MenaceInc** [comment]
This doesn't appear to work in 5.42

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21752820/79d3ba46-d5df-11e6-9f1f-42946d8cdcf0.png)
https://cloud.githubusercontent.com/assets/2068130/21752820/79d3ba46-d5df-11e6-9f1f-42946d8cdcf0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21752825/88ee6a94-d5df-11e6-980e-1eb788c7c2ae.png
