### ISSUE TITLE
Enscripted

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#1147]
**App Name:** Enscripted
**Bundle ID:** com.duncanacampbell.enscripted
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454136479">454136479</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/enscripted/id454136479?mt=8&uo=4">https://itunes.apple.com/us/app/enscripted/id454136479?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Gorilla Arm Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gorilla-arm-ltd./id431230403?uo=4">© Gorilla Arm Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/d9/36/21/d93621ce-bb2c-b493-d0f1-f4fe6ee455bc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19966109/a1c7db8e-a1ca-11e6-8325-dcb3fe2532bf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19966109/a1c7db8e-a1ca-11e6-8325-dcb3fe2532bf.png)
https://cloud.githubusercontent.com/assets/20930745/19966109/a1c7db8e-a1ca-11e6-8325-dcb3fe2532bf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19966141/c2ba3ecc-a1ca-11e6-90be-ed7375a48546.png
