### ISSUE TITLE
4 Pics 1 Word

### ISSUE THREAD

**Issue by Swedie** [glasklart/hd#1150]
**App Name:** 4 Pics 1 Word
**Bundle ID:** de.lotum.4pics1worden
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=595558452">595558452</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/4-pics-1-word/id595558452?mt=8&uo=4">https://itunes.apple.com/us/app/4-pics-1-word/id595558452?mt=8&uo=4</a>
**App Version:** 7.3.3
**Seller:** LOTUM GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lotum-gmbh/id459029666?uo=4">© LOTUM GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/90/9e/db/909edbe2-6741-3aef-25ed-fa0746b8a071/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/26374196/bf49953e-4004-11e7-881b-79bf05891979.png)

**Comment by dreamnet** [comment]
Same as #8130. Icon by @2Qt2beStr8.
