### ISSUE TITLE
Loopcam HD – Make Videos with Emojis & Filters

### ISSUE THREAD

**Issue by steelmunkey** [glasklart/hd#1154]
**App Name:** Loopcam HD – Make Videos with Emojis & Filters
**Bundle ID:** com.loopcam.loopcam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478624474">478624474</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/loopcam-hd-make-videos-emojis/id478624474?mt=8&uo=4">https://itunes.apple.com/us/app/loopcam-hd-make-videos-emojis/id478624474?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Tor Rauden
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tor-rauden/id478624477?uo=4>© Tor Rauden</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple4/v4/bc/8b/c0/bc8bc01c-d86f-3b0e-3ad5-08c178666428/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617818/f1036356-983a-11e6-8682-c417da95b2b2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617818/f1036356-983a-11e6-8682-c417da95b2b2.png)
https://cloud.githubusercontent.com/assets/20930745/19617818/f1036356-983a-11e6-8682-c417da95b2b2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617822/06a43654-983b-11e6-9742-5f38fdec56ec.png
