### ISSUE TITLE
FiLMiC Pro

### ISSUE THREAD

**Issue by danielyi22** [glasklart/hd#1155]
**App Name:** FiLMiC Pro
**Bundle ID:** com.cinegenix.filmic.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=436577167">436577167</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/filmic-pro/id436577167?mt=8&uo=4">https://itunes.apple.com/us/app/filmic-pro/id436577167?mt=8&uo=4</a>
**App Version:** 5.4.1
**Seller:** FiLMiC Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/filmic-inc/id436577170?uo=4>© FiLMiC Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/5d/17/8a/5d178a5b-09cd-2a59-4e7e-f324989c970a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418741/b8c84f84-93ca-11e6-92d6-5aca2208ac34.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418741/b8c84f84-93ca-11e6-92d6-5aca2208ac34.png)
https://cloud.githubusercontent.com/assets/20930745/19418741/b8c84f84-93ca-11e6-92d6-5aca2208ac34.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19418749/dd752bcc-93ca-11e6-8e84-944087e39b8e.png
