### ISSUE TITLE
France Football

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#116]
**App Name:** France Football
**Bundle ID:** fr.lequipe.francefoot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=325208077">325208077</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/france-football/id325208077?uo=4">https://apps.apple.com/us/app/france-football/id325208077?uo=4</a>
**App Version:** 2.3.3
**Seller:** L'Equipe 24/24
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lequipe-24-24/id318133986?uo=4">© L'Equipe 24/24</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/87/3a/c7/873ac7fd-a2d1-f379-e350-6e8df1b080d7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60395067-34507600-9b2e-11e9-8aae-c735bf6c91c6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20133054/31a92646-a666-11e6-9821-8225287ff92a.png)
https://cloud.githubusercontent.com/assets/20930745/20133054/31a92646-a666-11e6-9821-8225287ff92a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20133076/4da474e0-a666-11e6-9d9f-3c9b729d9b96.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60395067-34507600-9b2e-11e9-8aae-c735bf6c91c6.png)
https://user-images.githubusercontent.com/2068130/60395067-34507600-9b2e-11e9-8aae-c735bf6c91c6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60395072-44685580-9b2e-11e9-851f-cb88e25b0ae9.png
