### ISSUE TITLE
PAC-MAN

### ISSUE THREAD

**Issue by PaulBanks** [glasklart/hd#1160]
**App Name:** PAC-MAN
**Bundle ID:** com.namconetworks.pacman
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=281656475">281656475</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pac-man/id281656475?mt=8&uo=4">https://itunes.apple.com/us/app/pac-man/id281656475?mt=8&uo=4</a>
**App Version:** 6.1.0
**Seller:** BANDAI NAMCO Entertainment America Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bandai-namco-entertainment/id281656478?mt=8&uo=4>© BANDAI NAMCO Entertainment America Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/b3/5e/5d/b35e5dbc-38b4-efc7-24a4-fb9168ab35d4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14963083/aa31bfb4-1067-11e6-8eb3-5c57eb98b713.png)

**Comment by Anuskuss** [comment]
Needs update.

**Comment by Anuskuss** [comment]
Needs update and remove *needs-removal* label.

Also it seems like I have a different icon than above on my phone?
<img src="https://cloud.githubusercontent.com/assets/7157389/14924852/b491089a-0e44-11e6-9d8c-ae463a094520.png" width="150" height="150" />

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14962873/91d06b42-1066-11e6-8a1a-086ddc4a6a65.png)
https://cloud.githubusercontent.com/assets/3090247/14962873/91d06b42-1066-11e6-8a1a-086ddc4a6a65.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14962874/91d42890-1066-11e6-8663-52105f5c8228.png
