### ISSUE TITLE
Ilta-Sanomat

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1162]
**App Name:** Ilta-Sanomat
**Bundle ID:** com.is.ismainapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368549037">368549037</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ilta-sanomat/id368549037?mt=8&uo=4">https://itunes.apple.com/us/app/ilta-sanomat/id368549037?mt=8&uo=4</a>
**App Version:** 4.5.3
**Seller:** Sanoma Media Finland
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sanoma-media-finland/id368549040?uo=4>© Sanoma Media Finland</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/50/3e/ad/503eadec-e8bb-eb77-3944-25300d221482/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18798752/49b7ee54-81d4-11e6-830f-8aa815719779.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18798752/49b7ee54-81d4-11e6-830f-8aa815719779.png)
https://cloud.githubusercontent.com/assets/20930745/18798752/49b7ee54-81d4-11e6-830f-8aa815719779.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18798798/8592cbb0-81d4-11e6-931a-4e1a01ce7792.png
