### ISSUE TITLE
Iltalehti.fi

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1163]
**App Name:** Iltalehti.fi
**Bundle ID:** fi.iltalehti.iltalehti
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406613023">406613023</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iltalehti.fi/id406613023?mt=8&uo=4">https://itunes.apple.com/us/app/iltalehti.fi/id406613023?mt=8&uo=4</a>
**App Version:** 3.7.17
**Seller:** Kustannusosakeyhtio Iltalehti Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iltalehti.fi/id403688090?uo=4>© Iltalehti.fi</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/a8/f9/1d/a8f91d0a-9845-8a60-2669-82f584eb5b10/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18798215/b6f32ac2-81d1-11e6-902c-ea863aa0d839.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18798215/b6f32ac2-81d1-11e6-902c-ea863aa0d839.png)
https://cloud.githubusercontent.com/assets/20930745/18798215/b6f32ac2-81d1-11e6-902c-ea863aa0d839.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18798299/1822cf1e-81d2-11e6-89ac-68bb277adbd8.png
