### ISSUE TITLE
Sonera Viihde, Kake

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1164]
**App Name:** Sonera Viihde, Kake
**Bundle ID:** com.teliasonera.zappa.sonera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504835530">504835530</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fi/app/sonera-viihde-kake/id504835530?mt=8&uo=4">https://itunes.apple.com/fi/app/sonera-viihde-kake/id504835530?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** TeliaSonera Mobile Networks AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/fi/developer/teliasonera/id309706080?uo=4>© TeliaSonera</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple2/v4/23/17/14/23171467-8a73-4136-2729-84c9e6a19c16/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18799977/e1dd6956-81da-11e6-8452-38ce0344bf9f.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18799977/e1dd6956-81da-11e6-8452-38ce0344bf9f.png)
https://cloud.githubusercontent.com/assets/2068130/18799977/e1dd6956-81da-11e6-8452-38ce0344bf9f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18799994/efcea9a8-81da-11e6-9efa-46e1325097ad.png
