### ISSUE TITLE
Cross Fingers

### ISSUE THREAD

**Issue by Hawri84** [glasklart/hd#1166]
**App Name:** Cross Fingers
**Bundle ID:** net.mobigame.CrossFinger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=337490369">337490369</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cross-fingers/id337490369?mt=8&uo=4">https://itunes.apple.com/us/app/cross-fingers/id337490369?mt=8&uo=4</a>
**App Version:** 3.2.0
**Seller:** Mobigame
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mobigame/id300896021?uo=4">© Mobigame</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple20/v4/c5/26/7b/c5267b96-57a3-18cd-fe8f-5e43a070de68/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39443466-01c4ae4a-4cb5-11e8-9373-e246c950628f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39443466-01c4ae4a-4cb5-11e8-9373-e246c950628f.png)
https://user-images.githubusercontent.com/2068130/39443466-01c4ae4a-4cb5-11e8-9373-e246c950628f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39443490-15665b88-4cb5-11e8-97de-e5b6dfa086c9.png
