### ISSUE TITLE
KaleidaCam

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1168]
**App Name:** KaleidaCam
**Bundle ID:** com.dapperowl.KaleidaCam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=439614152">439614152</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kaleidacam/id439614152?mt=8&uo=4">https://itunes.apple.com/us/app/kaleidacam/id439614152?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Brett Gibson
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dapper-owl/id439614155?uo=4">© Dapper Owl</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/5e/0a/2c/5e0a2c31-9e84-59a8-a270-e19a69db62cb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32985612-41dede18-ccbf-11e7-9d67-c8cbdadc4ad1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32985612-41dede18-ccbf-11e7-9d67-c8cbdadc4ad1.png)
https://user-images.githubusercontent.com/2068130/32985612-41dede18-ccbf-11e7-9d67-c8cbdadc4ad1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32985617-55fb1a2e-ccbf-11e7-9f81-007faa8ec8c6.png
