### ISSUE TITLE
Radionomy

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1169]
**App Name:** Radionomy
**Bundle ID:** com.radionomy.mobileplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465042448">465042448</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/radionomy/id465042448?mt=8&uo=4">https://itunes.apple.com/gb/app/radionomy/id465042448?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Radionomy SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/radionomy-sa/id946012454?uo=4>© Radionomy SA</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/e1/88/31/e18831cb-58da-66df-ccb5-8f6937833fd5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617455/288ffca8-9831-11e6-848c-3337a2d330e7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617455/288ffca8-9831-11e6-848c-3337a2d330e7.png)
https://cloud.githubusercontent.com/assets/20930745/19617455/288ffca8-9831-11e6-848c-3337a2d330e7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617457/40cd3060-9831-11e6-80f1-dbafea218364.png
