### ISSUE TITLE
Europe1 Sports - votre appli sport

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#117]
**App Name:** Europe1 Sports - votre appli sport
**Bundle ID:** fr.newsweb.sports
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=308333134">308333134</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/europe1-sports-votre-appli/id308333134?mt=8&uo=4">https://itunes.apple.com/us/app/europe1-sports-votre-appli/id308333134?mt=8&uo=4</a>
**App Version:** 2.2.3
**Seller:** Newsweb
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/newsweb/id308333141?uo=4">© Newsweb</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/57/30/e5/5730e5cc-0de8-c12e-5203-44b01c3d3ab3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20132868/46358876-a665-11e6-9b33-314e40464f5d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20132868/46358876-a665-11e6-9b33-314e40464f5d.png)
https://cloud.githubusercontent.com/assets/20930745/20132868/46358876-a665-11e6-9b33-314e40464f5d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20132890/6029cf44-a665-11e6-99ae-ffe19b3b98b1.png
