### ISSUE TITLE
iStunt 2 - Snowboard

### ISSUE THREAD

**Issue by DerHimmelsreiter** [glasklart/hd#1176]
**App Name:** iStunt 2 - Snowboard
**Bundle ID:** com.miniclip.istunt2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407775125">407775125</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/istunt-2-snowboard/id407775125?mt=8&uo=4">https://itunes.apple.com/us/app/istunt-2-snowboard/id407775125?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Miniclip SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/miniclip.com/id337457683?uo=4>© Miniclip.com</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/2e/4f/da/2e4fdaca-0c50-f854-8200-131ede144272/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874627/613b430c-cdd7-11e5-832a-1734ad1e9fe6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874627/613b430c-cdd7-11e5-832a-1734ad1e9fe6.png)
https://cloud.githubusercontent.com/assets/2068130/12874627/613b430c-cdd7-11e5-832a-1734ad1e9fe6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12874635/736c5c00-cdd7-11e5-8f41-b8e78b34e646.png
