### ISSUE TITLE
TouchRummy

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1178]
**App Name:** Touch Rummy
**Bundle ID:** nl.alwintroost.touchrummy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=317635320">317635320</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touch-rummy/id317635320?mt=8&uo=4">https://itunes.apple.com/us/app/touch-rummy/id317635320?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Alwin Troost
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alwin-troost-nl/id296075625?uo=4">© Alwin Troost .nl</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/03/2e/8e/032e8ec7-4b0c-501f-c723-917db3382901/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40589694-3ce1a09e-61f2-11e8-9701-9a7318e5eb7d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40589694-3ce1a09e-61f2-11e8-9701-9a7318e5eb7d.png)
https://user-images.githubusercontent.com/2068130/40589694-3ce1a09e-61f2-11e8-9701-9a7318e5eb7d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/40589696-4bda89c6-61f2-11e8-8039-c36671db8002.png
