### ISSUE TITLE
Map My Fitness - GPS Workout Trainer & Tracker

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1183]
**App Name:** Map My Fitness - GPS Workout Trainer & Tracker
**Bundle ID:** Q5AWL8WCY6.iMapMyFitness
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=298903147">298903147</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/map-my-fitness-gps-workout/id298903147?mt=8&uo=4">https://itunes.apple.com/us/app/map-my-fitness-gps-workout/id298903147?mt=8&uo=4</a>
**App Version:** 16.10.1
**Seller:** MapMyFitness
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/under-armour/id291890423?uo=4>© Under Armour</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple19/v4/46/5c/ce/465cce8c-2ada-3ef2-6d0f-3fc3a483f4d0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19763074/dcf33bf6-9c3c-11e6-97e8-70e0ccbb5c19.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19763074/dcf33bf6-9c3c-11e6-97e8-70e0ccbb5c19.png)
https://cloud.githubusercontent.com/assets/2068130/19763074/dcf33bf6-9c3c-11e6-97e8-70e0ccbb5c19.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19763095/eac28bc4-9c3c-11e6-8245-22418d2c71cb.png
