### ISSUE TITLE
Photon Flash Player for iPhone - Flash Video & Games plus Private Web Browser

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1184]
**App Name:** Photon Flash Player for iPhone - Flash Video & Games plus Private Web Browser
**Bundle ID:** com.appsverse.browseriphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=453546382">453546382</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photon-flash-player-for-iphone-flash-video-games-plus/id453546382?mt=8&uo=4">https://itunes.apple.com/us/app/photon-flash-player-for-iphone-flash-video-games-plus/id453546382?mt=8&uo=4</a>
**App Version:** 6.2
**Seller:** Appsverse Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/appsverse-inc/id430200227?uo=4">© Appsverse Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple62/v4/f0/e2/9f/f0e29f49-b095-ed23-f9e6-73a33ac30d0e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41806525-00cbd916-76c0-11e8-9c87-8d1223430a00.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41806525-00cbd916-76c0-11e8-9c87-8d1223430a00.png)
https://user-images.githubusercontent.com/2068130/41806525-00cbd916-76c0-11e8-9c87-8d1223430a00.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41806531-11a9e926-76c0-11e8-87ef-fff22058384c.png
