### ISSUE TITLE
The Walking Dead: Dead Yourself

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1185]
**App Name:** The Walking Dead: Dead Yourself
**Bundle ID:** com.amctv.thewalkingdead.deadyourself
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=587842308">587842308</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/walking-dead-dead-yourself/id587842308?mt=8&uo=4">https://itunes.apple.com/us/app/walking-dead-dead-yourself/id587842308?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** AMC Network Entertainment LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/amc-network-entertainment/id309385037?uo=4>© AMC Network Entertainment LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/4a/ca/7c/4aca7cdc-4bbf-1fc5-2b99-d9dee58f3258/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/19412819/6941fc36-92e3-11e6-8b9b-c2ff6803caf7.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/19412765/5e82c0ba-92e2-11e6-99c0-d514a19de258.png
https://cloud.githubusercontent.com/assets/3090247/19412765/5e82c0ba-92e2-11e6-99c0-d514a19de258.png)
Source:
https://cloud.githubusercontent.com/assets/3090247/19412766/5e840b00-92e2-11e6-8436-c7e23dfec56c.png

**Comment by dreamnet** [comment]
Hum... taking the clean one.
