### ISSUE TITLE
Shellrazer

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1188]
**App Name:** Shellrazer
**Bundle ID:** com.slickentertainment.ShellRazer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=512290900">512290900</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shellrazer/id512290900?mt=8&uo=4">https://itunes.apple.com/us/app/shellrazer/id512290900?mt=8&uo=4</a>
**App Version:** 1.16
**Seller:** Slick Entertainment Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/slick-entertainment-inc/id403330236?uo=4">© Slick Entertainment Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/aa/57/52/aa575273-72a7-0cc1-2c93-20763ccf5000/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32678427-96905814-c662-11e7-8977-5ebaff9f9b59.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32678427-96905814-c662-11e7-8977-5ebaff9f9b59.png)
https://user-images.githubusercontent.com/2068130/32678427-96905814-c662-11e7-8977-5ebaff9f9b59.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32678448-a91ef580-c662-11e7-99ee-590dd3408702.png
