### ISSUE TITLE
Frequency ~ Watch Videos like TV

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1191]
**App Name:** Frequency ~ Watch Videos like TV
**Bundle ID:** com.frequency.Frequency-com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465034728">465034728</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/frequency-watch-videos-like/id465034728?mt=8&uo=4">https://itunes.apple.com/us/app/frequency-watch-videos-like/id465034728?mt=8&uo=4</a>
**App Version:** 2.4.240
**Seller:** Freqency Networks, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/frequency/id465034731?uo=4>© Frequency</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/78/9e/6d/789e6d4e-9bbf-c27e-f598-7a5639e3179d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18399941/ef314760-76d3-11e6-95bb-0e87cdd2d56e.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** Frequency ~ Watch Videos like TV
**Bundle ID:** com.frequency.Frequency-com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465034728">465034728</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/frequency-watch-videos-like/id465034728?mt=8&uo=4">https://itunes.apple.com/us/app/frequency-watch-videos-like/id465034728?mt=8&uo=4</a>
**App Version:** 2.4.240
**Seller:** Freqency Networks, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/frequency/id465034731?uo=4>© Frequency</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/78/9e/6d/789e6d4e-9bbf-c27e-f598-7a5639e3179d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18394830/dde57ac0-7689-11e6-8930-b96889717412.png)

https://cloud.githubusercontent.com/assets/3704186/18394830/dde57ac0-7689-11e6-8930-b96889717412.png

https://cloud.githubusercontent.com/assets/3704186/18394841/e4875d76-7689-11e6-8aa4-df11b86f6264.png
