### ISSUE TITLE
Camera360 - Selfie Photo Editor & Funny Filters

### ISSUE THREAD

**Issue by danielyi22** [glasklart/hd#1197]
**App Name:** Camera360 - Selfie Photo Editor & Funny Filters
**Bundle ID:** com.vstudio.camera360
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=443354861">443354861</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camera360-selfie-photo-editor/id443354861?mt=8&uo=4">https://itunes.apple.com/us/app/camera360-selfie-photo-editor/id443354861?mt=8&uo=4</a>
**App Version:** 8.0.1
**Seller:** Xu Hao
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pinguo-inc./id443138015?uo=4">© PinGuo Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/eb/c7/72/ebc772cf-8ec3-aadf-2f24-340168e75339/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19985532/5f344cc8-a213-11e6-89f2-134fd298ef9a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19985532/5f344cc8-a213-11e6-89f2-134fd298ef9a.png)
https://cloud.githubusercontent.com/assets/20930745/19985532/5f344cc8-a213-11e6-89f2-134fd298ef9a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19985603/ad9b9aec-a213-11e6-8ad4-be2bb216c19d.png
