### ISSUE TITLE
Cisco Legacy AnyConnect

### ISSUE THREAD

**Issue by BrianMitchL** [glasklart/hd#1200]
**App Name:** Cisco Legacy AnyConnect
**Bundle ID:** com.cisco.anyconnect.gui
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=392790924">392790924</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cisco-legacy-anyconnect/id392790924?mt=8&uo=4">https://itunes.apple.com/us/app/cisco-legacy-anyconnect/id392790924?mt=8&uo=4</a>
**App Version:** 4.0.05072
**Seller:** Cisco Systems, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cisco-systems-inc/id302425941?uo=4">© Cisco Systems, Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/62/e9/74/62e974f1-c600-4347-f195-899dab45677b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39398310-27ed072a-4b0c-11e8-8db6-944aaebcc09a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39398310-27ed072a-4b0c-11e8-8db6-944aaebcc09a.png)
https://user-images.githubusercontent.com/20930745/39398310-27ed072a-4b0c-11e8-8db6-944aaebcc09a.png

Source:
https://user-images.githubusercontent.com/20930745/39398317-46b7ee4a-4b0c-11e8-9196-268b2571ac59.png
