### ISSUE TITLE
Decibel 10th: Professional Noise Meter

### ISSUE THREAD

**Issue by BrianMitchL** [glasklart/hd#1202]
**App Name:** Decibel 10th: Professional Noise Meter
**Bundle ID:** com.skypaw.decibel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448155923">448155923</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/decibel-10th-professional/id448155923?mt=8&uo=4">https://itunes.apple.com/us/app/decibel-10th-professional/id448155923?mt=8&uo=4</a>
**App Version:** 4.3.6
**Seller:** SkyPaw Co. Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/skypaw-co.-ltd/id331027154?uo=4>© SkyPaw Co. Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/c3/d7/83/c3d78364-4bd2-e6a4-7beb-4ddeb0353586/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809847/594ce49c-8287-11e6-9e9f-dbf1a97db228.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809817/943cb6c8-8286-11e6-8ff2-daade6aeeeae.png)
https://cloud.githubusercontent.com/assets/20930745/18809817/943cb6c8-8286-11e6-8ff2-daade6aeeeae.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18809822/a8ec84f4-8286-11e6-92b0-a77f01688c33.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809847/594ce49c-8287-11e6-9e9f-dbf1a97db228.png)
https://cloud.githubusercontent.com/assets/20930745/18809847/594ce49c-8287-11e6-9e9f-dbf1a97db228.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18809851/6ce7a1a4-8287-11e6-955a-8ab6f9375371.png
