### ISSUE TITLE
Radiant

### ISSUE THREAD

**Issue by BrianMitchL** [glasklart/hd#1208]
**App Name:** Radiant
**Bundle ID:** net.hexage.radiant
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335989815">335989815</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radiant/id335989815?mt=8&uo=4">https://itunes.apple.com/us/app/radiant/id335989815?mt=8&uo=4</a>
**App Version:** 3.19.7
**Seller:** David Peroutka
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/david-peroutka/id317379085?uo=4">© David Peroutka</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/94/12/6f/94126f2b-db7e-7ca6-7f4a-2c150dea166e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32677821-43fc87fa-c660-11e7-96c7-94b08d21df4c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32677821-43fc87fa-c660-11e7-96c7-94b08d21df4c.png)
https://user-images.githubusercontent.com/2068130/32677821-43fc87fa-c660-11e7-96c7-94b08d21df4c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32677834-52fcb3f6-c660-11e7-9d64-f4c7e0c47006.png
