### ISSUE TITLE
POF Dating

### ISSUE THREAD

**Issue by richmFTW** [glasklart/hd#121]
**App Name:** POF Dating
**Bundle ID:** com.pof.mobileapp.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389638243">389638243</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pof-dating/id389638243?mt=8&uo=4">https://itunes.apple.com/us/app/pof-dating/id389638243?mt=8&uo=4</a>
**App Version:** 6.70
**Seller:** Plentyoffish Media Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/plentyoffish/id389638246?uo=4">© PlentyOfFish</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/f6/c9/61/f6c9613d-0c3d-0455-a694-84c880f4739e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692501-5a1cc932-c719-11e7-9513-d3cdc62edc43.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692501-5a1cc932-c719-11e7-9513-d3cdc62edc43.png)
https://user-images.githubusercontent.com/2068130/32692501-5a1cc932-c719-11e7-9513-d3cdc62edc43.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692511-693b14be-c719-11e7-9c74-44c472d000a8.png
