### ISSUE TITLE
National Geographic World Atlas

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1214]
**App Name:** National Geographic World Atlas
**Bundle ID:** com.natgeomobile.worldatlashd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364733950">364733950</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/national-geographic-world/id364733950?mt=8&uo=4">https://itunes.apple.com/us/app/national-geographic-world/id364733950?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** National Geographic Society
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/national-geographic-society/id315268468?uo=4>© National Geographic Society</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/e2/8a/e6/e28ae6fe-9dda-5290-99eb-e3dc4d6da117/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18810805/8159915c-829f-11e6-9ba0-648dbba36f55.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18810805/8159915c-829f-11e6-9ba0-648dbba36f55.png)
https://cloud.githubusercontent.com/assets/20930745/18810805/8159915c-829f-11e6-9ba0-648dbba36f55.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18810810/93421f38-829f-11e6-8b64-a9156fc687db.png
