### ISSUE TITLE
Serve

### ISSUE THREAD

**Issue by q2r5** [glasklart/hd#1217]
**App Name:** Serve
**Bundle ID:** com.americanexpress.revolutionmoney.serve
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=425685843">425685843</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/serve/id425685843?mt=8&uo=4">https://itunes.apple.com/us/app/serve/id425685843?mt=8&uo=4</a>
**App Version:** 4.1.0.0
**Seller:** American Express
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/american-express/id362348519?uo=4>© American Express</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/17/ba/dd/17baddc6-3a5b-1e61-1cf2-6607d93bf87b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19317390/2870ddc0-90a5-11e6-9de5-0f1c4db025b3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19317390/2870ddc0-90a5-11e6-9de5-0f1c4db025b3.png)
https://cloud.githubusercontent.com/assets/20930745/19317390/2870ddc0-90a5-11e6-9de5-0f1c4db025b3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19317406/3697fef6-90a5-11e6-8189-1890fb7d66e2.png
