### ISSUE TITLE
Swish payments

### ISSUE THREAD

**Issue by Swedie** [glasklart/hd#1218]
**App Name:** Swish payments
**Bundle ID:** se.bankgirot.swish
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=563204724">563204724</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swish-payments/id563204724?mt=8&uo=4">https://itunes.apple.com/us/app/swish-payments/id563204724?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Bankgirocentralen BGC AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bankgirot/id563204727?uo=4>© Bankgirot</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/19/6e/56/196e5643-0455-171f-01d5-9ced0f6da56f/mzl.gntjacog.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10537884/189457ba-73f5-11e5-8737-4dedb9553e95.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10537884/189457ba-73f5-11e5-8737-4dedb9553e95.png)
https://cloud.githubusercontent.com/assets/10730122/10537884/189457ba-73f5-11e5-8737-4dedb9553e95.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10537880/152cae2e-73f5-11e5-877a-409c4a417b0a.png
