### ISSUE TITLE
Detroit Free Press

### ISSUE THREAD

**Issue by lostinthe4th** [glasklart/hd#1223]
Name: Detroit Free Press
Bundle ID: com.doapps.fac245c0cd451a91e8fa12de5db066de
iTunes ID: 388953042
PNG Icon Names: Icon.png | Icon@2x.png | Icon-72.png | Icon-Small-50.png | Icon-Small.png | Icon-Small@2x.png
![Detroit-Free-Press-big-icon_3461](https://f.cloud.github.com/assets/3672720/189942/90a5988a-7ebc-11e2-8f90-13a0c0f1d269.jpg)

**Comment by illinikev** [comment]
iTunes ID changed to 904023476

**App Name:** Detroit Free Press for iPhone
**Bundle ID:** com.gannett.news.local.freep
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=904023476">904023476</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/detroit-free-press-for-iphone/id904023476?mt=8&uo=4">https://itunes.apple.com/us/app/detroit-free-press-for-iphone/id904023476?mt=8&uo=4</a>
**App Version:** 2.5.7
**Seller:** Gannett
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gannett/id404843797?uo=4>© Gannett</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/0d/e6/fc/0de6fcf7-b6c4-8894-fe7d-41b662815b72/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![image](https://cloud.githubusercontent.com/assets/16004373/11377286/b0b65c0e-92aa-11e5-82fe-222e826a6e32.png)

**Comment by ivanov007** [comment]
@illinikev also a different app, you need to open a new issue
