### ISSUE TITLE
Instashare Air Drop - Transfer files the easy way

### ISSUE THREAD

**Issue by lxsdr** [glasklart/hd#1226]
**App Name:** Instashare Air Drop - Transfer files the easy way
**Bundle ID:** com.arat.Vacuum
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=576220851">576220851</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instashare-air-drop-transfer-files-the-easy-way/id576220851?mt=8&uo=4">https://itunes.apple.com/us/app/instashare-air-drop-transfer-files-the-easy-way/id576220851?mt=8&uo=4</a>
**App Version:** 2.4.0
**Seller:** Lukas Foldyna
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lukas-foldyna/id288917602?uo=4">© Lukas Foldyna</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple127/v4/de/f7/21/def721c3-937b-dc39-db8c-25118168b2b7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39465998-c7382834-4d26-11e8-94ab-7a6fae089de0.png)

**Comment by 2Qt2beStr8** [comment]
?
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39463997-622a05b2-4d1b-11e8-9ceb-b5a067e4b5a5.png)
https://user-images.githubusercontent.com/20930745/39463997-622a05b2-4d1b-11e8-9ceb-b5a067e4b5a5.png

Source:
https://user-images.githubusercontent.com/20930745/39464014-725877d4-4d1b-11e8-8979-0648a6fcf55c.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39465998-c7382834-4d26-11e8-94ab-7a6fae089de0.png)
https://user-images.githubusercontent.com/2068130/39465998-c7382834-4d26-11e8-94ab-7a6fae089de0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39466012-d62a66a4-4d26-11e8-8888-648813edf22d.png
