### ISSUE TITLE
Klout for iPhone

### ISSUE THREAD

**Issue by BTG2013** [glasklart/hd#1227]
**App Name:** Klout for iPhone
**Bundle ID:** com.klout.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=517089691">517089691</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/klout-for-iphone/id517089691?mt=8&uo=4">https://itunes.apple.com/us/app/klout-for-iphone/id517089691?mt=8&uo=4</a>
**App Version:** 2.3.3
**Seller:** Klout Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/klout/id428325504?uo=4>© Klout</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/c2/51/68/c251688d-cfe4-4942-adcd-55d60a632ddc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617245/19d3ab42-982c-11e6-9c3f-cb30cfff127c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617245/19d3ab42-982c-11e6-9c3f-cb30cfff127c.png)
https://cloud.githubusercontent.com/assets/20930745/19617245/19d3ab42-982c-11e6-9c3f-cb30cfff127c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617247/38a8f5f4-982c-11e6-92b0-4a6db5d76d57.png
