### ISSUE TITLE
PITFALL!™

### ISSUE THREAD

**Issue by jlndk** [glasklart/hd#1230]
**App Name:** PITFALL!™
**Bundle ID:** com.activision.pitfall
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547291263">547291263</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pitfall/id547291263?mt=8&uo=4">https://itunes.apple.com/us/app/pitfall/id547291263?mt=8&uo=4</a>
**App Version:** 1.7.0
**Seller:** Activision Publishing, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/activision-publishing-inc/id285005466?mt=8&uo=4">© Activision Publishing, Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/aa/c0/ad/aac0ad35-d292-4926-26dd-f7a3f7b8dc78/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32678188-b1362dc0-c661-11e7-8509-b3ece47cfa23.png)
https://user-images.githubusercontent.com/2068130/32678188-b1362dc0-c661-11e7-8509-b3ece47cfa23.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32678216-c0b4444e-c661-11e7-8b22-815cf999c26d.png
