### ISSUE TITLE
SHADOWGUN

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1232]
**App Name:** SHADOWGUN
**Bundle ID:** com.madfingergames.shadowgun
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=440141669">440141669</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shadowgun/id440141669?mt=8&uo=4">https://itunes.apple.com/us/app/shadowgun/id440141669?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** MADFINGER Games, a.s.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/madfinger-games-a.s./id313220894?uo=4">© MADFINGER Games, a.s.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/8d/58/57/8d5857af-3ebe-fc63-2cee-765a4f318405/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19963934/23aa5ba6-a1bf-11e6-8f9a-4b31db834466.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19963934/23aa5ba6-a1bf-11e6-8f9a-4b31db834466.png)
https://cloud.githubusercontent.com/assets/20930745/19963934/23aa5ba6-a1bf-11e6-8f9a-4b31db834466.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19963954/38685bec-a1bf-11e6-9e12-f13b10912a07.png
