### ISSUE TITLE
PLNDR

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#1236]
**App Name:** PLNDR
**Bundle ID:** com.plndr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547974560">547974560</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/plndr/id547974560?mt=8&uo=4">https://itunes.apple.com/us/app/plndr/id547974560?mt=8&uo=4</a>
**App Version:** 2.1.5
**Seller:** Karmaloop Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/karmaloop/id542775455?uo=4>© Karmaloop</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/15/54/b8/1554b8a2-c3ee-965e-277f-3476093f18fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19602741/b44a73a0-97ae-11e6-9324-e60fae713053.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19602741/b44a73a0-97ae-11e6-9324-e60fae713053.png)
https://cloud.githubusercontent.com/assets/20930745/19602741/b44a73a0-97ae-11e6-9324-e60fae713053.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19602764/c7ea344a-97ae-11e6-96cf-fb453866ed63.png
