### ISSUE TITLE
Fancy

### ISSUE THREAD

**Issue by HoboAM** [glasklart/hd#1237]
**App Name:** Fancy
**Bundle ID:** com.thefancy.fancy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407324335">407324335</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fancy/id407324335?mt=8&uo=4">https://itunes.apple.com/us/app/fancy/id407324335?mt=8&uo=4</a>
**App Version:** 6.2.1
**Seller:** Thing Daemon, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/thing-daemon-inc./id333198480?uo=4>© Thing Daemon, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple22/v4/da/f4/32/daf4329a-ae03-26f3-dbe8-418e798c0054/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18231427/92decb7c-7287-11e6-90f7-1c9d9ca26333.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** Fancy
**Bundle ID:** com.thefancy.fancy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407324335">407324335</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fancy/id407324335?mt=8&uo=4">https://itunes.apple.com/us/app/fancy/id407324335?mt=8&uo=4</a>
**App Version:** 6.2.1
**Seller:** Thing Daemon, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/thing-daemon-inc./id333198480?uo=4>© Thing Daemon, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple22/v4/da/f4/32/daf4329a-ae03-26f3-dbe8-418e798c0054/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18231427/92decb7c-7287-11e6-90f7-1c9d9ca26333.png)

https://cloud.githubusercontent.com/assets/3704186/18231427/92decb7c-7287-11e6-90f7-1c9d9ca26333.png

https://cloud.githubusercontent.com/assets/3704186/18231433/a15892a0-7287-11e6-8db6-590d557d2c70.png
