### ISSUE TITLE
Tinder

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#1238]
**App Name:** Tinder
**Bundle ID:** com.cardify.tinder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547702041">547702041</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tinder/id547702041?mt=8&uo=4">https://itunes.apple.com/us/app/tinder/id547702041?mt=8&uo=4</a>
**App Version:** 4.6.1
**Seller:** Tinder Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tinder-inc./id725634363?uo=4>© Tinder Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/b1/dc/a6/b1dca6ea-77c1-346b-754b-1c1d33d6918e/mzl.gsegzdnv.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10269866/563998f8-6ae2-11e5-9875-d974b7817c82.png)

**Comment by dreamnet** [comment]
Adding source:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10269866/563998f8-6ae2-11e5-9875-d974b7817c82.png)
https://cloud.githubusercontent.com/assets/2068130/10269866/563998f8-6ae2-11e5-9875-d974b7817c82.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10269872/662680a0-6ae2-11e5-99d4-4c1915f3189c.png
