### ISSUE TITLE
Karmaloop.com

### ISSUE THREAD

**Issue by HoboAM** [glasklart/hd#1239]
**App Name:** Karmaloop.com
**Bundle ID:** com.karmaloop.karmaloop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542775452">542775452</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/karmaloop.com/id542775452?mt=8&uo=4">https://itunes.apple.com/us/app/karmaloop.com/id542775452?mt=8&uo=4</a>
**App Version:** 4.0.13
**Seller:** Karmaloop Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/karmaloop/id542775455?uo=4>© Karmaloop</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/8c/06/0b/8c060b6f-7517-02b1-d1e2-d4e736b26d95/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19382035/b68ba78e-91fe-11e6-82cc-304dad377864.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19382035/b68ba78e-91fe-11e6-82cc-304dad377864.png)
https://cloud.githubusercontent.com/assets/20930745/19382035/b68ba78e-91fe-11e6-82cc-304dad377864.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19382049/c58a5168-91fe-11e6-8ddf-04837091035f.png
