### ISSUE TITLE
SparkNotes

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1240]
**App Name:** SparkNotes
**Bundle ID:** com.sparknotes.sparknotes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506427167">506427167</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sparknotes/id506427167?mt=8&uo=4">https://itunes.apple.com/us/app/sparknotes/id506427167?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** SparkNotes LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sparknotes-llc/id329377979?uo=4">© SparkNotes LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/99/7d/53/997d53de-c3fa-f7e4-2092-d1c3150bb1b7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32676699-dff50a92-c65b-11e7-9fb3-ab6625b2e0ca.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32676699-dff50a92-c65b-11e7-9fb3-ab6625b2e0ca.png)
https://user-images.githubusercontent.com/2068130/32676699-dff50a92-c65b-11e7-9fb3-ab6625b2e0ca.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32676713-f0823696-c65b-11e7-829c-d6a59fa7ebdb.png
