### ISSUE TITLE
theCHIVE

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#1242]
**App Name:** theCHIVE
**Bundle ID:** com.thechive.Chive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448999087">448999087</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/thechive/id448999087?mt=8&uo=4">https://itunes.apple.com/us/app/thechive/id448999087?mt=8&uo=4</a>
**App Version:** 2.1.30
**Seller:** Resignation Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/resignation-media-llc/id448999090?uo=4>© Resignation Media, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/ea/04/83/ea048357-d4e8-e40f-8f17-e10225d8b1e4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19603001/c6c4c408-97af-11e6-8cd1-9f8fe78cbe04.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19603001/c6c4c408-97af-11e6-8cd1-9f8fe78cbe04.png)
https://cloud.githubusercontent.com/assets/20930745/19603001/c6c4c408-97af-11e6-8cd1-9f8fe78cbe04.png

https://cloud.githubusercontent.com/assets/20930745/19603030/dc9deebc-97af-11e6-8113-5d5ac1655d3b.png
