### ISSUE TITLE
Super QuickHook

### ISSUE THREAD

**Issue by HoboAM** [glasklart/hd#1243]
**App Name:** Super QuickHook
**Bundle ID:** com.rocketcat.QuickHook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375941471">375941471</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-quickhook/id375941471?mt=8&uo=4">https://itunes.apple.com/us/app/super-quickhook/id375941471?mt=8&uo=4</a>
**App Version:** 1.40
**Seller:** Rocketcat LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rocketcat-llc/id305576988?uo=4">© Rocketcat LLC</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/7b/49/5f/7b495fbc-72c7-6af5-54c9-105c42ea1cf5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23163656/942bf90a-f833-11e6-9f59-35fdb626e0fd.png)

**Comment by ukhf-jm** [comment]
This icon doesn't appear to be working on iOS 9.3.3 with version 5.42. I'm guessing it was lost in the transition to Anemone?

**Comment by dreamnet** [comment]
@ukhf-jm Jup!

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23163656/942bf90a-f833-11e6-9f59-35fdb626e0fd.png)
https://cloud.githubusercontent.com/assets/2068130/23163656/942bf90a-f833-11e6-9f59-35fdb626e0fd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23163666/a257303a-f833-11e6-902b-8942144a2266.png
❓
