### ISSUE TITLE
SayHi Translate

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#1247]
**App Name:** SayHi Translate
**Bundle ID:** com.sayhi.client
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=437818260">437818260</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sayhi-translate/id437818260?mt=8&uo=4">https://itunes.apple.com/us/app/sayhi-translate/id437818260?mt=8&uo=4</a>
**App Version:** 3.9.8
**Seller:** SayHI, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sayhi/id437818263?uo=4>© SayHi</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/66/d1/d9/66d1d921-bb86-b2e4-d43f-094581eec986/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19604397/5e474a4e-97b5-11e6-98e2-a410669fee62.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19604397/5e474a4e-97b5-11e6-98e2-a410669fee62.png)
https://cloud.githubusercontent.com/assets/20930745/19604397/5e474a4e-97b5-11e6-98e2-a410669fee62.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19604417/751bd384-97b5-11e6-8bff-e92e56a139e2.png
