### ISSUE TITLE
OSnap! Pro • Time-Lapse & Stop Motion Camera

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#1248]
**App Name:** OSnap! Pro • Time-Lapse & Stop Motion Camera
**Bundle ID:** com.headofthemule.OSnap-
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=457402095">457402095</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/osnap!-pro-time-lapse-stop/id457402095?mt=8&uo=4">https://itunes.apple.com/us/app/osnap!-pro-time-lapse-stop/id457402095?mt=8&uo=4</a>
**App Version:** 3.3.3
**Seller:** Justin Cegnar
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/justin-cegnar/id457402098?uo=4>© Justin Cegnar</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/71/74/02/71740223-bbfa-21f8-17b5-acf34e517f1a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19604074/fdc0ba8a-97b3-11e6-85af-124fbda5968a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19604074/fdc0ba8a-97b3-11e6-85af-124fbda5968a.png)
https://cloud.githubusercontent.com/assets/20930745/19604074/fdc0ba8a-97b3-11e6-85af-124fbda5968a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19604101/1c30a8e0-97b4-11e6-8578-ee6f466d2614.png
