### ISSUE TITLE
Triplog - Track your Gas Mileage (mpg), Trips and Costs - Get your Tax Deductions correct!

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#1249]
**App Name:** Triplog - Track your Gas Mileage (mpg), Trips and Costs - Get your Tax Deductions correct!
**Bundle ID:** Island-Software.CarBook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445267455">445267455</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/triplog-track-your-gas-mileage/id445267455?mt=8&uo=4">https://itunes.apple.com/us/app/triplog-track-your-gas-mileage/id445267455?mt=8&uo=4</a>
**App Version:** 2.8.2
**Seller:** Christian Falch
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/islands-software/id426523101?uo=4>© Islands Software</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/bb/fe/fd/bbfefd5a-684c-36cb-6847-5d64addce403/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19603354/24a6188c-97b1-11e6-9250-46b3e55583ce.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19603354/24a6188c-97b1-11e6-9250-46b3e55583ce.png)
https://cloud.githubusercontent.com/assets/20930745/19603354/24a6188c-97b1-11e6-9250-46b3e55583ce.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19603390/3b03784a-97b1-11e6-9e38-422bc4827e90.png
