### ISSUE TITLE
Fuelly: MPG & Service Tracker

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#1250]
**App Name:** Fuelly: MPG & Service Tracker
**Bundle ID:** com.appcubby.gascubby
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=295905460">295905460</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fuelly-mpg-service-tracker/id295905460?uo=4">https://apps.apple.com/us/app/fuelly-mpg-service-tracker/id295905460?uo=4</a>
**App Version:** 3.3.4
**Seller:** Fuelly, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fuelly-llc/id666506117?uo=4">© Fuelly, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/0f/a5/aa/0fa5aa3c-f67a-4988-6512-b348376eccd6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400813-8ec2f400-9b79-11e9-880b-3a54a01a87ca.png)

**Comment by ivanov007** [comment]
update needed

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18811085/137f07a8-826c-11e6-904c-0c40a2cd7e1d.png)
https://cloud.githubusercontent.com/assets/3090247/18811085/137f07a8-826c-11e6-904c-0c40a2cd7e1d.png
Source:
https://cloud.githubusercontent.com/assets/3090247/18811086/13812b6e-826c-11e6-8814-d438895c4a7b.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400813-8ec2f400-9b79-11e9-880b-3a54a01a87ca.png)
https://user-images.githubusercontent.com/20930745/60400813-8ec2f400-9b79-11e9-880b-3a54a01a87ca.png

Source:
https://user-images.githubusercontent.com/20930745/60400815-908cb780-9b79-11e9-87d0-a89952be3787.png
