### ISSUE TITLE
New Relic

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#1251]
**App Name:** New Relic
**Bundle ID:** com.newrelic.NRApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=594038638">594038638</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-relic/id594038638?mt=8&uo=4">https://itunes.apple.com/us/app/new-relic/id594038638?mt=8&uo=4</a>
**App Version:** 3.26
**Seller:** New Relic Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/new-relic-inc./id594038641?uo=4>© New Relic, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/5a/1d/a7/5a1da785-3243-7635-9857-a63d09acf24a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19233066/7e5630e6-8ee3-11e6-8e27-ce87c423f305.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19233066/7e5630e6-8ee3-11e6-8e27-ce87c423f305.png)
https://cloud.githubusercontent.com/assets/20930745/19233066/7e5630e6-8ee3-11e6-8e27-ce87c423f305.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19233078/8c0a4ba0-8ee3-11e6-992f-6599b97135a9.png
