### ISSUE TITLE
Scientific Graphing Calculator

### ISSUE THREAD

**Issue by lostinthe4th** [glasklart/hd#1252]
**App Name:** Scientific Graphing Calculator
**Bundle ID:** com.jockusch.calculator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=369480853">369480853</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scientific-graphing-calculator/id369480853?mt=8&uo=4">https://itunes.apple.com/us/app/scientific-graphing-calculator/id369480853?mt=8&uo=4</a>
**App Version:** 8.2
**Seller:** William Jockusch
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/william-jockusch/id342126227?uo=4">© William Jockusch</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple22/v4/a7/65/c8/a765c878-12a6-c0b9-56c8-3e9df436c3a2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31399995-62346a4c-adee-11e7-9412-9c2f2e00745c.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31339974-e6add370-ad04-11e7-9d75-8a7822fcf1e7.png)
https://user-images.githubusercontent.com/20930745/31339974-e6add370-ad04-11e7-9d75-8a7822fcf1e7.png

Source:
https://user-images.githubusercontent.com/20930745/31339993-fd2eb11e-ad04-11e7-90a1-eb915db5f780.png

**Comment by dreamnet** [comment]
Hm. Maybe with some small grid lines in the background?

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31399995-62346a4c-adee-11e7-9412-9c2f2e00745c.png)
https://user-images.githubusercontent.com/20930745/31399995-62346a4c-adee-11e7-9412-9c2f2e00745c.png

Source:
https://user-images.githubusercontent.com/20930745/31400017-770e3786-adee-11e7-9dce-69191d702051.png
