### ISSUE TITLE
Night Sky 4

### ISSUE THREAD

**Issue by lostinthe4th** [glasklart/hd#1253]
**App Name:** Night Sky 4
**Bundle ID:** com.icandiapps.nightsky
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=475772902">475772902</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/night-sky-4/id475772902?mt=8&uo=4">https://itunes.apple.com/us/app/night-sky-4/id475772902?mt=8&uo=4</a>
**App Version:** 4.0.4
**Seller:** iCandi Apps
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/icandi-apps/id305827577?uo=4>© iCandi Apps</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/79/39/0d/79390df8-2290-4c0d-99f2-cd8e9b41c97b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19596551/8c17e850-978f-11e6-8321-f7dfebf5ebcd.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19588382/b5f37434-9765-11e6-8c46-48a0e36b4370.png)
https://cloud.githubusercontent.com/assets/10730122/19588382/b5f37434-9765-11e6-8c46-48a0e36b4370.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19588383/b5f39bb2-9765-11e6-8d9b-ae791f37ade1.png

**Comment by 2Qt2beStr8** [comment]
some small corretions .. but credits to @Trubbel 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19596551/8c17e850-978f-11e6-8321-f7dfebf5ebcd.png)
https://cloud.githubusercontent.com/assets/20930745/19596551/8c17e850-978f-11e6-8321-f7dfebf5ebcd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19596577/aec5f298-978f-11e6-9cd0-cc5f6d3d5cc9.png
