### ISSUE TITLE
Picup

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#1254]
**App Name:** Picup
**Bundle ID:** com.wdlindmeier.picup
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=354101378">354101378</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/picup/id354101378?mt=8&uo=4">https://itunes.apple.com/us/app/picup/id354101378?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** william LINDMEIER
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/william-lindmeier/id327885331?uo=4>© william LINDMEIER</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/41/29/f9/4129f959-9365-0517-0550-9cc49917a023/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19603580/00305552-97b2-11e6-9409-88726a13898a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19603580/00305552-97b2-11e6-9409-88726a13898a.png)
https://cloud.githubusercontent.com/assets/20930745/19603580/00305552-97b2-11e6-9409-88726a13898a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19603602/1650dd34-97b2-11e6-83c1-2035e0ce64d7.png
