### ISSUE TITLE
Uncrate

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#1255]
**App Name:** Uncrate
**Bundle ID:** com.uncrate.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=450084793">450084793</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/uncrate/id450084793?mt=8&uo=4">https://itunes.apple.com/us/app/uncrate/id450084793?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** ZOMBIECORP LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/uncrate-llc/id450084796?uo=4>© Uncrate LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/71/06/f6/7106f690-760f-9882-137c-116a6f0da806/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19616970/60c3216c-9823-11e6-887f-4b56d2c3be8d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19616970/60c3216c-9823-11e6-887f-4b56d2c3be8d.png)
https://cloud.githubusercontent.com/assets/20930745/19616970/60c3216c-9823-11e6-887f-4b56d2c3be8d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19616974/77e95a28-9823-11e6-9a03-8adcf7f16be2.png
