### ISSUE TITLE
Parcel - Delivery Tracking

### ISSUE THREAD

**Issue by HoboAM** [glasklart/hd#1256]
**App Name:** Parcel - Delivery Tracking
**Bundle ID:** com.mr-brightside.myParcel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375589283">375589283</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parcel-delivery-tracking/id375589283?mt=8&uo=4">https://itunes.apple.com/us/app/parcel-delivery-tracking/id375589283?mt=8&uo=4</a>
**App Version:** 4.0.4
**Seller:** Ivan Pavlov Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ivan-pavlov-pty-ltd/id375311513?uo=4>© Ivan Pavlov Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple49/v4/a0/36/01/a036018d-209b-fcf1-9e50-2fe6a022de61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18216230/251b8bb0-711b-11e6-8305-6e39d4dea019.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Parcel - Delivery Tracking
**Bundle ID:** com.mr-brightside.myParcel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375589283">375589283</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parcel-delivery-tracking/id375589283?mt=8&uo=4">https://itunes.apple.com/us/app/parcel-delivery-tracking/id375589283?mt=8&uo=4</a>
**App Version:** 4.0.4
**Seller:** Ivan Pavlov Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ivan-pavlov-pty-ltd/id375311513?uo=4>© Ivan Pavlov Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple49/v4/a0/36/01/a036018d-209b-fcf1-9e50-2fe6a022de61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18216230/251b8bb0-711b-11e6-8305-6e39d4dea019.png)
https://cloud.githubusercontent.com/assets/3090247/18216230/251b8bb0-711b-11e6-8305-6e39d4dea019.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18216231/251c4a1e-711b-11e6-8142-8418095718d5.png
