### ISSUE TITLE
TED

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#1257]
**App Name:** TED
**Bundle ID:** com.ted.TED
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376183339">376183339</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ted/id376183339?mt=8&uo=4">https://itunes.apple.com/us/app/ted/id376183339?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** TED Conferences
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ted-conferences/id376183342?uo=4>© TED Conferences</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple20/v4/41/73/ea/4173ea51-ed6c-1b2f-23b3-e38ecb5c18ca/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18036024/fd655f2c-6d61-11e6-8399-24534b359171.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18036024/fd655f2c-6d61-11e6-8399-24534b359171.png)
https://cloud.githubusercontent.com/assets/10730122/18036024/fd655f2c-6d61-11e6-8399-24534b359171.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18036023/fd64ce36-6d61-11e6-916b-88963c6888fa.png
