### ISSUE TITLE
DUCO - SHAPE EFFECTS CAMERA ▲

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#1262]
**App Name:** DUCO - SHAPE EFFECTS CAMERA ▲
**Bundle ID:** com.99centbrains.duco
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=581781676">581781676</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/duco-shape-effects-camera/id581781676?mt=8&uo=4">https://itunes.apple.com/us/app/duco-shape-effects-camera/id581781676?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** 99centbrains Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/99centbrains-inc./id367542352?uo=4>© 99centbrains Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/cc/ed/ee/ccedee2c-f39e-de09-dc1d-570db0247a19/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19604657/83272bbc-97b6-11e6-9879-d3ef582c85a8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19604657/83272bbc-97b6-11e6-9879-d3ef582c85a8.png)
https://cloud.githubusercontent.com/assets/20930745/19604657/83272bbc-97b6-11e6-9879-d3ef582c85a8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19604676/99933c10-97b6-11e6-868e-2f4b99050297.png
