### ISSUE TITLE
TouchRetouch

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#1266]
**App Name:** TouchRetouch
**Bundle ID:** com.advasoft.touchretouch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=373311252">373311252</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touchretouch/id373311252?mt=8&uo=4">https://itunes.apple.com/us/app/touchretouch/id373311252?mt=8&uo=4</a>
**App Version:** 4.1.7
**Seller:** Maksym Davydov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/adva-soft/id373311255?uo=4">© Adva-Soft</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/f4/2c/a1/f42ca17b-59ab-b248-b424-483047aef632/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32371331-bb7612e0-c090-11e7-809d-82e69832816c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32371331-bb7612e0-c090-11e7-809d-82e69832816c.png)
https://user-images.githubusercontent.com/2068130/32371331-bb7612e0-c090-11e7-809d-82e69832816c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32371349-caea8404-c090-11e7-84bf-8dd1f75d5df5.png
