### ISSUE TITLE
DS audio

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1267]
**App Name:** DS audio
**Bundle ID:** com.synology.DSaudio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=321495303">321495303</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ds-audio/id321495303?mt=8&uo=4">https://itunes.apple.com/us/app/ds-audio/id321495303?mt=8&uo=4</a>
**App Version:** 5.12.0
**Seller:** Synology Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/synology-inc./id321493109?uo=4>© Synology Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/58/15/73/58157352-875c-5ea9-3b00-22e1dff47adc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416478/a5e16524-7816-11e6-83a9-b91203526123.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416478/a5e16524-7816-11e6-83a9-b91203526123.png)
https://cloud.githubusercontent.com/assets/2068130/18416478/a5e16524-7816-11e6-83a9-b91203526123.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416483/b6e35c4c-7816-11e6-958a-3398188c2a84.png
