### ISSUE TITLE
Deko — Beautiful, Unique Wallpapers and Patterns

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#1270]
**App Name:** Deko — Beautiful, Unique Wallpapers and Patterns
**Bundle ID:** com.aerodeko.deko
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=582647344">582647344</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deko-beautiful-unique-wallpapers/id582647344?mt=8&uo=4">https://itunes.apple.com/us/app/deko-beautiful-unique-wallpapers/id582647344?mt=8&uo=4</a>
**App Version:** 1.1.6
**Seller:** Johan Halin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aero-deko/id507882387?uo=4>© Aero Deko</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/6e/6e/c6/6e6ec66e-658b-ffca-a4b7-0b1c1ee50ea0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617133/7b5de0fc-9828-11e6-9006-9a6ed4234eef.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617133/7b5de0fc-9828-11e6-9006-9a6ed4234eef.png)
https://cloud.githubusercontent.com/assets/20930745/19617133/7b5de0fc-9828-11e6-9006-9a6ed4234eef.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617137/97cf4d20-9828-11e6-8208-f47a09b0b4eb.png
