### ISSUE TITLE
Phonto - Text on Photos

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#1272]
**App Name:** Phonto - Text on Photos
**Bundle ID:** com.youthhr.Phonto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438429273">438429273</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/phonto-text-on-photos/id438429273?mt=8&uo=4">https://itunes.apple.com/us/app/phonto-text-on-photos/id438429273?mt=8&uo=4</a>
**App Version:** 4.7.1
**Seller:** Yusuke Horie
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/youthhr/id368416996?uo=4>© youthhr</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/05/93/c1/0593c1e1-e8c0-0999-c54e-ec4e1e4c47af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617158/a1816d16-9829-11e6-937d-22ffd8ef2a3b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617158/a1816d16-9829-11e6-937d-22ffd8ef2a3b.png)
https://cloud.githubusercontent.com/assets/20930745/19617158/a1816d16-9829-11e6-937d-22ffd8ef2a3b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617174/fae90d0a-9829-11e6-9a25-797d3aaa2cb7.png
