### ISSUE TITLE
City Bank

### ISSUE THREAD

**Issue by BTG2013** [glasklart/hd#1273]
**App Name:** City Bank
**Bundle ID:** com.citybank.iOSCBOT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476686881">476686881</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/city-bank/id476686881?mt=8&uo=4">https://itunes.apple.com/us/app/city-bank/id476686881?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** City Bank
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/city-bank/id476686884?uo=4>© City Bank</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/a9/20/82/a9208230-14f2-d908-b51e-a82045998c68/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617200/e174c854-982a-11e6-9b53-b28758aacd99.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617200/e174c854-982a-11e6-9b53-b28758aacd99.png)
https://cloud.githubusercontent.com/assets/20930745/19617200/e174c854-982a-11e6-9b53-b28758aacd99.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617208/fc1c6266-982a-11e6-9202-adc5e3197778.png
