### ISSUE TITLE
Rhapsody

### ISSUE THREAD

**Issue by SirTaiger** [glasklart/hd#1276]
**App Name:** Rhapsody
**Bundle ID:** com.rhapsody.iphone.Rhapsody
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=366725701">366725701</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/app/levelgas/id366725701?mt=8&uo=4">https://itunes.apple.com/app/levelgas/id366725701?mt=8&uo=4</a>
**App Version:** ?.?
**Seller:** ?
**Developer:** ?
**Supported Devices:** ?
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/32037441-9eab5ca4-ba25-11e7-87fd-b23f8fc12286.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32037295-f913837a-ba24-11e7-9bb8-808bd68af483.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32037295-f913837a-ba24-11e7-9bb8-808bd68af483.png)
https://user-images.githubusercontent.com/2068130/32037295-f913837a-ba24-11e7-9bb8-808bd68af483.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32037308-095b76e8-ba25-11e7-8c6f-674daeb94bce.png
