### ISSUE TITLE
Mild EleMints: Free Periodic Table

### ISSUE THREAD

**Issue by BenChaimberg** [glasklart/hd#1279]
**App Name:** Mild EleMints: Free Periodic Table
**Bundle ID:** com.appkainime.MildEleMints
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=303806618">303806618</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mild-elemints-free-periodic-table/id303806618?mt=8&uo=4">https://itunes.apple.com/us/app/mild-elemints-free-periodic-table/id303806618?mt=8&uo=4</a>
**App Version:** 2.2.2
**Seller:** Mochi Development, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mochi-development-inc/id292771260?uo=4">© Mochi Development, Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/74/ec/ce/74ecceb0-6fb1-de7f-8d42-0fc6f3889f68/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26386620/1bdc9858-4048-11e7-9402-a5c09cb04884.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26386620/1bdc9858-4048-11e7-9402-a5c09cb04884.png)
https://cloud.githubusercontent.com/assets/2068130/26386620/1bdc9858-4048-11e7-9402-a5c09cb04884.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26386633/2b748b40-4048-11e7-96c8-9b720595c0d7.png
