### ISSUE TITLE
Tribal Wars

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#1285]
**App Name:** Tribal Wars
**Bundle ID:** com.innogames.tribalwars
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=435365767">435365767</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tribal-wars/id435365767?mt=8&uo=4">https://itunes.apple.com/us/app/tribal-wars/id435365767?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** InnoGames GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/innogames/id435365770?uo=4>© InnoGames</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/74/63/84/746384b2-c759-20df-5b38-be76fd5f5dbb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18811136/aefa641c-82a7-11e6-87c7-5ffa421f00df.png)

**Comment by Anuskuss** [comment]
Needs update.

**Comment by dreamnet** [comment]
Another one hand drawn...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18811136/aefa641c-82a7-11e6-87c7-5ffa421f00df.png)
https://cloud.githubusercontent.com/assets/2068130/18811136/aefa641c-82a7-11e6-87c7-5ffa421f00df.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18811137/c07bcd98-82a7-11e6-9230-e1e91ff5d6b3.png
