### ISSUE TITLE
My3G

### ISSUE THREAD

**Issue by aidanharris** [glasklart/hd#1287]
**App Name:** My3G
**Bundle ID:** com.intelliborn.my3g
**iTunes ID:** none (Cydia app)
**Original Artwork:** 
<img src="https://f.cloud.github.com/assets/3090247/2084048/1d69b842-8e15-11e3-8ec7-89b7573705de.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7199975/54883cd0-e4be-11e4-9f28-0a4e5fa917ac.png)

**Comment by Trubbel** [comment]
The **CFBundleIdentifier** has changed, it is no longer **com.my3g** - now it's **com.intelliborn.my3g**
-- --
It would also be great if someone could update the icon as well, this was the highest resolution/quality I could find in it's own folder.

https://cloud.githubusercontent.com/assets/10730122/7180378/709f514c-e441-11e4-9ee8-cfef0ccf4e66.png

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7199975/54883cd0-e4be-11e4-9f28-0a4e5fa917ac.png)
https://cloud.githubusercontent.com/assets/3090247/7199975/54883cd0-e4be-11e4-9f28-0a4e5fa917ac.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7199976/54900c94-e4be-11e4-8597-4e1c39ff7365.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
