### ISSUE TITLE
NinJump™ Deluxe

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#1288]
**App Name:** NinJump™ Deluxe
**Bundle ID:** com.backflipstudios.ninjumpdeluxefree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=516761043">516761043</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ninjump-deluxe/id516761043?mt=8&uo=4">https://itunes.apple.com/us/app/ninjump-deluxe/id516761043?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Backflip Studios
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/backflip-studios/id315282170?uo=4">© Backflip Studios</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/1b/64/ef/1b64eff1-7685-cd9c-bac6-da40cdc020cc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38139755-1bafad4c-3431-11e8-92d2-c44430b10fe4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38139755-1bafad4c-3431-11e8-92d2-c44430b10fe4.png)
https://user-images.githubusercontent.com/2068130/38139755-1bafad4c-3431-11e8-92d2-c44430b10fe4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38139770-2ad798ac-3431-11e8-837b-bbf91f7e9a97.png
