### ISSUE TITLE
Basecamp 2 for iPhone

### ISSUE THREAD

**Issue by joshuaswilcox** [glasklart/hd#1296]
**App Name:** Basecamp 2 for iPhone
**Bundle ID:** com.37signals.basecamp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=599139477">599139477</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/basecamp-2-for-iphone/id599139477?mt=8&uo=4">https://itunes.apple.com/us/app/basecamp-2-for-iphone/id599139477?mt=8&uo=4</a>
**App Version:** 2.1.3
**Seller:** Basecamp, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/basecamp-llc/id363576304?uo=4">© Basecamp, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/02/71/a7/0271a705-453b-e073-1de4-fa057350fe24/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32676513-33e7c30c-c65b-11e7-9487-c77ecd8b3cf1.png)
https://user-images.githubusercontent.com/2068130/32676513-33e7c30c-c65b-11e7-9487-c77ecd8b3cf1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32676527-42ff3708-c65b-11e7-88a7-fa1d5e5079de.png
