### ISSUE TITLE
DS photo

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1302]
**App Name:** DS photo
**Bundle ID:** com.synology.DSphoto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=321493106">321493106</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ds-photo/id321493106?mt=8&uo=4">https://itunes.apple.com/us/app/ds-photo/id321493106?mt=8&uo=4</a>
**App Version:** 4.12.1
**Seller:** Synology Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/synology-inc./id321493109?uo=4>© Synology Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/1f/06/c8/1f06c847-ce93-6efb-4006-c30b42e70059/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416427/d25872e8-7814-11e6-81b6-498a867c6f92.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416427/d25872e8-7814-11e6-81b6-498a867c6f92.png)
https://cloud.githubusercontent.com/assets/2068130/18416427/d25872e8-7814-11e6-81b6-498a867c6f92.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416430/e0aa9d9e-7814-11e6-81eb-4268e309d5a5.png
