### ISSUE TITLE
Flitsmeister

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1303]
**App Name:** Flitsmeister
**Bundle ID:** rw.sp.flitsmeister
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=354936286">354936286</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flitsmeister/id354936286?mt=8&uo=4">https://itunes.apple.com/us/app/flitsmeister/id354936286?mt=8&uo=4</a>
**App Version:** 6.12.0
**Seller:** Rick Waalders
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rick-waalders-sjoerd-perfors/id354936289?uo=4">© Rick Waalders, Sjoerd Perfors</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/9f/a8/39/9fa83964-70e7-bbf5-650c-e28832d50223/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417497-0517526c-c25b-11e7-91da-88b7dbff2a7d.png)
https://user-images.githubusercontent.com/2068130/32417497-0517526c-c25b-11e7-91da-88b7dbff2a7d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32417500-14ab6dee-c25b-11e7-81e1-bd616920f0e7.png
