### ISSUE TITLE
Thuisbezorgd.nl

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1304]
**App Name:** Thuisbezorgd.nl
**Bundle ID:** citymealprofile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=329472759">329472759</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/thuisbezorgd-nl/id329472759?uo=4">https://apps.apple.com/us/app/thuisbezorgd-nl/id329472759?uo=4</a>
**App Version:** 6.2.1
**Seller:** Takeaway.com
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/takeaway-com/id329472762?uo=4">© Takeaway.com</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/0c/24/db/0c24dbbe-2688-ffa4-69a4-9c95352faa91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680988-c093cd80-9e8d-11e9-9d18-93707a7fc508.png)

**Comment by 2Qt2beStr8** [comment]
same as #6113 ... icon from @Trubbel 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19601454/b2f94a3a-97a9-11e6-86ae-0f19c2a71a6f.png)
https://cloud.githubusercontent.com/assets/20930745/19601454/b2f94a3a-97a9-11e6-86ae-0f19c2a71a6f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19601538/0bf808ba-97aa-11e6-89fc-390fabbd9b5e.png

**Comment by dreamnet** [comment]
Small update.
Icon by @2Qt2beStr8 
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680988-c093cd80-9e8d-11e9-9d18-93707a7fc508.png)
https://user-images.githubusercontent.com/20930745/60680988-c093cd80-9e8d-11e9-9d18-93707a7fc508.png

Source:
https://user-images.githubusercontent.com/20930745/60680990-c1c4fa80-9e8d-11e9-9041-6507db6dfafe.png
