### ISSUE TITLE
Yellowbrick

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1305]
**App Name:** Yellowbrick
**Bundle ID:** nl.yellowbrick.YBparking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=394867179">394867179</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yellowbrick/id394867179?mt=8&uo=4">https://itunes.apple.com/us/app/yellowbrick/id394867179?mt=8&uo=4</a>
**App Version:** 4.2.12
**Seller:** Yellowbrick bv
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yellowbrick-bv/id394867182?uo=4">© Yellowbrick bv</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/4e/f3/fa/4ef3fa3c-66be-5f34-568c-a211715497a2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32675235-83e68352-c656-11e7-9b17-8726d9b89648.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32675235-83e68352-c656-11e7-9b17-8726d9b89648.png)
https://user-images.githubusercontent.com/2068130/32675235-83e68352-c656-11e7-9b17-8726d9b89648.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32675260-93ab2928-c656-11e7-9857-c433e639fcea.png
