### ISSUE TITLE
Buienradar

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1306]
**App Name:** Buienradar
**Bundle ID:** nl.rtl.buienradar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=621542526">621542526</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/buienradar/id621542526?mt=8&uo=4">https://itunes.apple.com/us/app/buienradar/id621542526?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** RTL Nederland Interactief B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/rtl-nederland/id398467676?uo=4>© RTL Nederland</a>
**Supported Devices:** iPhone6, iPhone5s, iPhone6Plus, iPadMini4G, iPhone4, iPhone5c, iPadThirdGen4G, iPhone4S, iPadFourthGen, iPadFourthGen4G, iPadMini, iPad23G, iPodTouchFifthGen, iPhone5, iPodTouchSixthGen, iPad2Wifi, iPadThirdGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/2f/bc/1d/2fbc1de7-7545-0daf-6ff1-10d52b144225/mzl.fwafzcma.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8889908/f9f3e9a8-32ed-11e5-9452-5297572d4087.png)

**Comment by MagnaMike** [comment]
Updated original post with new info from @dreamnet's script. Bundle ID needs to be updated.

**Comment by MagnaMike** [comment]
[2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/8889705/70792362-32b3-11e5-821f-dd8e9d421141.png)
https://cloud.githubusercontent.com/assets/2236254/8889705/70792362-32b3-11e5-821f-dd8e9d421141.png

---

No source. Icon courtesy of @scottbuckley.

**Comment by dreamnet** [comment]
Complete:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8889908/f9f3e9a8-32ed-11e5-9452-5297572d4087.png)
https://cloud.githubusercontent.com/assets/2068130/8889908/f9f3e9a8-32ed-11e5-9452-5297572d4087.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8889914/08db5ca8-32ee-11e5-9558-9bc443336a41.png
