### ISSUE TITLE
Diamond Dash: Gem Puzzle Game

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1307]
**App Name:** Diamond Dash: Gem Puzzle Game
**Bundle ID:** net.wooga.diamonddash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=461402734">461402734</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/diamond-dash-gem-puzzle-game/id461402734?mt=8&uo=4">https://itunes.apple.com/us/app/diamond-dash-gem-puzzle-game/id461402734?mt=8&uo=4</a>
**App Version:** 7.0.95
**Seller:** wooga gmbh
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wooga/id461402737?uo=4">© wooga</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/d1/9f/8b/d19f8b65-d861-c9d3-a2bd-1d87fe4fd884/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39393286-b7cd7e7c-4ac3-11e8-9386-78a6eec1d2e7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39393286-b7cd7e7c-4ac3-11e8-9386-78a6eec1d2e7.png)
https://user-images.githubusercontent.com/2068130/39393286-b7cd7e7c-4ac3-11e8-9386-78a6eec1d2e7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39393289-c5c27df2-4ac3-11e8-99ee-e5f0ff196e2f.png
