### ISSUE TITLE
SABmini

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1309]
**App Name:** SABmini
**Bundle ID:** com.sabmini.sabmini
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=422294057">422294057</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sabmini/id422294057?mt=8&uo=4">https://itunes.apple.com/us/app/sabmini/id422294057?mt=8&uo=4</a>
**App Version:** 2.9
**Seller:** Stefan Klein Nulent
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/stefan-klein-nulent/id388944888?uo=4">© Stefan Klein Nulent</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/3b/12/7a/3b127a67-06a3-e423-a00c-8644de41f69b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19963125/55832594-a1bb-11e6-8082-a8b6f1de2ac4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19963125/55832594-a1bb-11e6-8082-a8b6f1de2ac4.png)
https://cloud.githubusercontent.com/assets/20930745/19963125/55832594-a1bb-11e6-8082-a8b6f1de2ac4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19963161/7316176a-a1bb-11e6-9740-08b5e3c71fa7.png
