### ISSUE TITLE
Dumpert

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1313]
**App Name:** Dumpert
**Bundle ID:** nl.geenstijl.dumpert
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=434815056">434815056</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dumpert/id434815056?uo=4">https://apps.apple.com/us/app/dumpert/id434815056?uo=4</a>
**App Version:** 2.13.2
**Seller:** DT Media B.V.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dt-media-b-v/id373529872?uo=4">© DT Media B.V.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/5e/f1/94/5ef19450-773b-2bf6-e19a-d22306aa6013/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60383049-5aaddd00-9a6c-11e9-906f-d137b7bc8bfb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19963465/d74ffd08-a1bc-11e6-97ec-17afe5153b7a.png)
https://cloud.githubusercontent.com/assets/20930745/19963465/d74ffd08-a1bc-11e6-97ec-17afe5153b7a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19963498/f71dcf3e-a1bc-11e6-9835-d05a69a143ff.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60383049-5aaddd00-9a6c-11e9-906f-d137b7bc8bfb.png)
https://user-images.githubusercontent.com/20930745/60383049-5aaddd00-9a6c-11e9-906f-d137b7bc8bfb.png

Source:
https://user-images.githubusercontent.com/20930745/60383050-5bdf0a00-9a6c-11e9-8a93-e1837ae933b6.png
