### ISSUE TITLE
DS get

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1314]
**App Name:** DS get
**Bundle ID:** com.synology.DSdownload
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540948028">540948028</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ds-get/id540948028?mt=8&uo=4">https://itunes.apple.com/us/app/ds-get/id540948028?mt=8&uo=4</a>
**App Version:** 2.12.2
**Seller:** Synology Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/synology-inc/id321493109?uo=4">© Synology Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/7b/89/77/7b897709-30e9-8a50-54a6-8928f810d367/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36602014-1e999ba2-18b7-11e8-9b84-02a8ec41cd29.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416405/2d0d7bb2-7814-11e6-833a-2953784f1674.png)
https://cloud.githubusercontent.com/assets/2068130/18416405/2d0d7bb2-7814-11e6-833a-2953784f1674.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416406/3cb851c2-7814-11e6-88a4-27a35dfb158f.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36602014-1e999ba2-18b7-11e8-9b84-02a8ec41cd29.png)
https://user-images.githubusercontent.com/20930745/36602014-1e999ba2-18b7-11e8-9b84-02a8ec41cd29.png

Source:
https://user-images.githubusercontent.com/20930745/36602042-3231637a-18b7-11e8-8973-18f1f06f9a4d.png
