### ISSUE TITLE
Marktplaats - Voor tweedehands en nieuwe spullen

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1316]
**App Name:** Marktplaats - Voor tweedehands en nieuwe spullen
**Bundle ID:** com.marktplaats.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=373963365">373963365</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/marktplaats-voor-tweedehands/id373963365?mt=8&uo=4">https://itunes.apple.com/us/app/marktplaats-voor-tweedehands/id373963365?mt=8&uo=4</a>
**App Version:** 5.10.1
**Seller:** Marktplaats BV
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marktplaats-bv/id318979525?uo=4">© Marktplaats BV</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/03/96/83/03968302-b84a-536e-6a57-13eb3c1a2127/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19963694/d48f4fc8-a1bd-11e6-868e-8d159ac0636b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19963694/d48f4fc8-a1bd-11e6-868e-8d159ac0636b.png)
https://cloud.githubusercontent.com/assets/20930745/19963694/d48f4fc8-a1bd-11e6-868e-8d159ac0636b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19963713/f21702ac-a1bd-11e6-9ffe-00fa12a0ad93.png
