### ISSUE TITLE
WordOn HD

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1317]
**App Name:** WordOn HD
**Bundle ID:** com.flaregames.wordon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=565881351">565881351</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wordon-hd/id565881351?mt=8&uo=4">https://itunes.apple.com/us/app/wordon-hd/id565881351?mt=8&uo=4</a>
**App Version:** 2.1.17
**Seller:** Huckleberry BV
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/huckleberry-bv/id674061215?uo=4">© Huckleberry BV</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/1f/a6/4a/1fa64ac1-8906-1feb-cce0-02df03597df6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32675147-31718b76-c656-11e7-90c9-fcce50c91550.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32675147-31718b76-c656-11e7-90c9-fcce50c91550.png)
https://user-images.githubusercontent.com/2068130/32675147-31718b76-c656-11e7-90c9-fcce50c91550.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32675169-427689f8-c656-11e7-88cf-eb535f7e7f8c.png
