### ISSUE TITLE
My T-Mobile

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1318]
**App Name:** My T-Mobile
**Bundle ID:** nl.tmobile.mytmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484504034">484504034</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/my-t-mobile/id484504034?mt=8&uo=4">https://itunes.apple.com/de/app/my-t-mobile/id484504034?mt=8&uo=4</a>
**App Version:** 3.9
**Seller:** T-Mobile Netherlands Holding BV
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/t-mobile-netherlands-holding/id467376975?uo=4>© T-Mobile Netherlands Holding BV</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/e7/ee/11/e7ee113d-73cb-f965-cb41-799cc91f17e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19602233/c9403a44-97ac-11e6-9d44-f89118f5b3b6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19602233/c9403a44-97ac-11e6-9d44-f89118f5b3b6.png)
https://cloud.githubusercontent.com/assets/20930745/19602233/c9403a44-97ac-11e6-9d44-f89118f5b3b6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19602249/de6c73ec-97ac-11e6-8b82-0c94b3ae4634.png
