### ISSUE TITLE
VakantieVeilingen - Dagje uit

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1319]
**App Name:** VakantieVeilingen - Dagje uit
**Bundle ID:** nl.emesa.vv-mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389598075">389598075</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vakantieveilingen-dagje-uit/id389598075?mt=8&uo=4">https://itunes.apple.com/us/app/vakantieveilingen-dagje-uit/id389598075?mt=8&uo=4</a>
**App Version:** 6.11.0
**Seller:** Emesa B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/emesa-b.v./id389598078?uo=4>© Emesa B.V.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/e5/20/3c/e5203c13-1692-197f-bf53-94b8c1c7cf09/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19602488/b2c37370-97ad-11e6-84d7-fde28e48a04c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19602488/b2c37370-97ad-11e6-84d7-fde28e48a04c.png)
https://cloud.githubusercontent.com/assets/20930745/19602488/b2c37370-97ad-11e6-84d7-fde28e48a04c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19602513/ca38b1b4-97ad-11e6-9b1b-40ff9473a28d.png
