### ISSUE TITLE
Air France

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#132]
**App Name:** Air France
**Bundle ID:** com.airfrance.mobile.iphone.afmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391968627">391968627</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/air-france/id391968627?mt=8&uo=4">https://itunes.apple.com/us/app/air-france/id391968627?mt=8&uo=4</a>
**App Version:** 7.2.1
**Seller:** AIR FRANCE
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/societe-air-france-s-a/id391968630?uo=4">© Societe Air France S.A.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/1a/83/8a/1a838af5-6b74-f058-5aa3-335e724fb6c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692435-3065119a-c718-11e7-9a66-78fba0140480.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692435-3065119a-c718-11e7-9a66-78fba0140480.png)
https://user-images.githubusercontent.com/2068130/32692435-3065119a-c718-11e7-9a66-78fba0140480.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692438-40e93460-c718-11e7-8305-1c6a9f7072f3.png
