### ISSUE TITLE
RitMeter

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1320]
**App Name:** RitMeter
**Bundle ID:** com.Simoso.RitMeter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507873425">507873425</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ritmeter/id507873425?mt=8&uo=4">https://itunes.apple.com/us/app/ritmeter/id507873425?mt=8&uo=4</a>
**App Version:** 2.3.16
**Seller:** Simoso
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/simoso/id507873428?uo=4">© Simoso</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/f4/9c/da/f49cda04-50b8-24ca-2aae-65f8f0a1f7a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417549-8a79db14-c25b-11e7-8e6e-0d12c958c4e8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417549-8a79db14-c25b-11e7-8e6e-0d12c958c4e8.png)
https://user-images.githubusercontent.com/2068130/32417549-8a79db14-c25b-11e7-8e6e-0d12c958c4e8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32417554-9a06a27e-c25b-11e7-980c-5f18a82602a7.png
