### ISSUE TITLE
Blue Letter Bible

### ISSUE THREAD

**Issue by wellflint** [glasklart/hd#1321]
**App Name:** Blue Letter Bible
**Bundle ID:** com.BlueLetterBible.BLB
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=365547505">365547505</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blue-letter-bible/id365547505?mt=8&uo=4">https://itunes.apple.com/us/app/blue-letter-bible/id365547505?mt=8&uo=4</a>
**App Version:** 2.65
**Seller:** Blue Letter Bible
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/blue-letter-bible/id365547508?uo=4">© Blue Letter Bible</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/8b/0c/ca/8b0cca11-c943-5140-3301-80dcb1a92a84/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32675052-cfe42044-c655-11e7-8172-64d44a685bf8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32675052-cfe42044-c655-11e7-8172-64d44a685bf8.png)
https://user-images.githubusercontent.com/2068130/32675052-cfe42044-c655-11e7-8172-64d44a685bf8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32675066-dffd6ae4-c655-11e7-893a-1c83b841a1cf.png
