### ISSUE TITLE
Boost 2

### ISSUE THREAD

**Issue by bhillinger** [glasklart/hd#1322]
**App Name:** Boost 2
**Bundle ID:** com.jonathanlanis.boost
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=333191476">333191476</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boost-2/id333191476?mt=8&uo=4">https://itunes.apple.com/us/app/boost-2/id333191476?mt=8&uo=4</a>
**App Version:** 2.5.3
**Seller:** Jonathan Lanis
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jonathan-lanis/id333191479?uo=4>© Jonathan Lanis</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/19/0a/26/190a26e0-ac78-6e75-30fd-9696301296a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18942310/5e795c72-8618-11e6-9c8f-479701e53907.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18885169/c9b1f5f0-84ea-11e6-923f-feab5027988d.png)
https://cloud.githubusercontent.com/assets/20930745/18885169/c9b1f5f0-84ea-11e6-923f-feab5027988d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18885408/cfd9879e-84eb-11e6-98d3-37b951bd93fc.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Fine, but I think we don't need the shadow on the bottom of the icon:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18942310/5e795c72-8618-11e6-9c8f-479701e53907.png)
https://cloud.githubusercontent.com/assets/2068130/18942310/5e795c72-8618-11e6-9c8f-479701e53907.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18942319/6ccb6d92-8618-11e6-9fed-b00e3647e77a.png
