### ISSUE TITLE
FLAC Player

### ISSUE THREAD

**Issue by Gokshura** [glasklart/hd#1326]
**App Name:** FLAC Player
**Bundle ID:** com.hammockdistrict.flacplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390532592">390532592</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flac-player/id390532592?mt=8&uo=4">https://itunes.apple.com/us/app/flac-player/id390532592?mt=8&uo=4</a>
**App Version:** 2.1.3
**Seller:** Dan Leehr L.L.C.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dan-leehr-l.l.c./id318884767?uo=4>© Dan Leehr L.L.C.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/ac/b7/e0/acb7e032-04b7-ff44-7f96-3900ad28b3f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19601251/cd8097a6-97a8-11e6-95fe-3b02d9fc5dbe.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19601251/cd8097a6-97a8-11e6-95fe-3b02d9fc5dbe.png)
https://cloud.githubusercontent.com/assets/20930745/19601251/cd8097a6-97a8-11e6-95fe-3b02d9fc5dbe.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19601268/e38042cc-97a8-11e6-8dc7-1d223642ac7a.png
