### ISSUE TITLE
Avertinoo

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#133]
**App Name:** Avertinoo
**Bundle ID:** fr.visialis.iWarning
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=293573778">293573778</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/avertinoo/id293573778?mt=8&uo=4">https://itunes.apple.com/us/app/avertinoo/id293573778?mt=8&uo=4</a>
**App Version:** 3.9.2
**Seller:** Sebastien Poulet-Mathis
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/visialis/id291816597?uo=4">© Visialis</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/94/1b/9a/941b9a94-e92a-609f-f628-566cffb5d300/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692401-a7036316-c717-11e7-9fb1-4daefd1ae54a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692401-a7036316-c717-11e7-9fb1-4daefd1ae54a.png)
https://user-images.githubusercontent.com/2068130/32692401-a7036316-c717-11e7-9fb1-4daefd1ae54a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692406-b6f3777a-c717-11e7-9f7f-8d02b6278221.png
