### ISSUE TITLE
Digits, the calculator for humans

### ISSUE THREAD

**Issue by tonearmed** [glasklart/hd#1330]
**App Name:** Digits, the calculator for humans
**Bundle ID:** Shift.DigitsCalculator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364500115">364500115</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/digits-calculator-for-humans/id364500115?mt=8&uo=4">https://itunes.apple.com/us/app/digits-calculator-for-humans/id364500115?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Shift
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shift/id364500118?uo=4>© Shift</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/f1/97/92/f19792ca-17f4-b743-0fef-0d105447194b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18737363/9c333c00-8090-11e6-82c2-1bbb6a4fc74d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18737363/9c333c00-8090-11e6-82c2-1bbb6a4fc74d.png)
https://cloud.githubusercontent.com/assets/2068130/18737363/9c333c00-8090-11e6-82c2-1bbb6a4fc74d.png
--- ---
https://cloud.githubusercontent.com/assets/2068130/18737370/ab73fe98-8090-11e6-80c7-323fe7f7267d.png
