### ISSUE TITLE
H&M

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#1331]
**App Name:** H&M
**Bundle ID:** com.hm.mcom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589351740">589351740</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/h-m/id589351740?mt=8&uo=4">https://itunes.apple.com/us/app/h-m/id589351740?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** H & M Hennes & Mauritz AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/h-m/id380487412?uo=4>© H&M</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/1e/60/90/1e6090dd-eb28-22cb-4fc3-8d764bf64094/mzl.jatbbnyl.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231170/a038ce0a-6881-11e5-9751-4f9fc81e5ae6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231170/a038ce0a-6881-11e5-9751-4f9fc81e5ae6.png)
https://cloud.githubusercontent.com/assets/2068130/10231170/a038ce0a-6881-11e5-9751-4f9fc81e5ae6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10231187/b118ad12-6881-11e5-8c81-32f270ac9458.png
