### ISSUE TITLE
NU.nl

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1337]
**App Name:** NU.nl
**Bundle ID:** nl.sanomadigital.nuhd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382059927">382059927</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nu.nl/id382059927?mt=8&uo=4">https://itunes.apple.com/us/app/nu.nl/id382059927?mt=8&uo=4</a>
**App Version:** 5.10.4
**Seller:** Sanoma Digital The Netherlands B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sanoma-digital/id314922053?mt=8&uo=4>© Sanoma Digital</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/8d/93/a2/8d93a261-9240-2361-704e-61f73a5fe3c5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19276695/801fca28-8fd7-11e6-9089-e5f34a21433d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19276695/801fca28-8fd7-11e6-9089-e5f34a21433d.png)
https://cloud.githubusercontent.com/assets/20930745/19276695/801fca28-8fd7-11e6-9089-e5f34a21433d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19276708/8d69b91e-8fd7-11e6-8f51-114ad5322463.png
