### ISSUE TITLE
Snapguide - How-tos, Recipes, Fashion, Crafts, iPhone Tips and Lifehacks

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1339]
**App Name:** Snapguide - How-tos, Recipes, Fashion, Crafts, iPhone Tips and Lifehacks
**Bundle ID:** com.heavybits.snapguide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=421477397">421477397</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snapguide-how-tos-recipes/id421477397?mt=8&uo=4">https://itunes.apple.com/us/app/snapguide-how-tos-recipes/id421477397?mt=8&uo=4</a>
**App Version:** 1.8.4
**Seller:** Brit Media, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brit-media-inc./id418035913?uo=4>© Brit Media, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple5/v4/3c/0f/db/3c0fdb84-ed35-5508-c218-8a5c748971b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18192526/94657d82-70d5-11e6-9ba0-7157ada0d3b9.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** Snapguide - How-tos, Recipes, Fashion, Crafts, iPhone Tips and Lifehacks
**Bundle ID:** com.heavybits.snapguide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=421477397">421477397</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snapguide-how-tos-recipes/id421477397?mt=8&uo=4">https://itunes.apple.com/us/app/snapguide-how-tos-recipes/id421477397?mt=8&uo=4</a>
**App Version:** 1.8.4
**Seller:** Brit Media, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brit-media-inc./id418035913?uo=4>© Brit Media, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple5/v4/3c/0f/db/3c0fdb84-ed35-5508-c218-8a5c748971b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18192526/94657d82-70d5-11e6-9ba0-7157ada0d3b9.png)
https://cloud.githubusercontent.com/assets/2068130/18192526/94657d82-70d5-11e6-9ba0-7157ada0d3b9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18192534/a3ca19ea-70d5-11e6-8519-323164af1547.png
