### ISSUE TITLE
Onion Browser

### ISSUE THREAD

**Issue by odysseydla** [glasklart/hd#1342]
**App Name:** Onion Browser
**Bundle ID:** com.miketigas.OnionBrowser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519296448">519296448</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/onion-browser/id519296448?mt=8&uo=4">https://itunes.apple.com/us/app/onion-browser/id519296448?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** Mike Tigas
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mike-tigas/id519296451?uo=4">© Mike Tigas</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/85/d4/6b/85d46b14-b262-dc80-ec39-3aadb6f3fac3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39393530-a1ddaf12-4ac6-11e8-8208-aae0b7ba00f0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39393530-a1ddaf12-4ac6-11e8-8208-aae0b7ba00f0.png)
https://user-images.githubusercontent.com/2068130/39393530-a1ddaf12-4ac6-11e8-8208-aae0b7ba00f0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39393535-b3dc70cc-4ac6-11e8-8983-6bfac85884e9.png
