### ISSUE TITLE
Fing - Network Scanner

### ISSUE THREAD

**Issue by odysseydla** [glasklart/hd#1343]
**App Name:** Fing - Network Scanner
**Bundle ID:** overlook.fing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=430921107">430921107</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fing-network-scanner/id430921107?mt=8&uo=4">https://itunes.apple.com/us/app/fing-network-scanner/id430921107?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Nives Vanzo
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/overlook-soft/id430921110?uo=4>© Overlook Soft</a>
**Supported Devices:** iPadThirdGen, iPodTouchFifthGen, iPadFourthGen4G, iPhone-3GS, iPhone5s, iPhone6, iPodTouchFourthGen, iPhone5c, iPhone5, iPad23G, iPhone4S, iPhone6Plus, iPadThirdGen4G, iPadFourthGen, iPad2Wifi, iPadMini, iPhone4, iPadMini4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/3f/c1/5b/3fc15b9b-327a-426a-b307-a2b329b5eabc/mzl.ehewuryu.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7785202/f86143be-0184-11e5-80b4-ea68efdfdf15.png)

**Comment by Trubbel** [comment]
The icon seems to have been updated.

Here's my take,
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7785202/f86143be-0184-11e5-80b4-ea68efdfdf15.png)
https://cloud.githubusercontent.com/assets/10730122/7785202/f86143be-0184-11e5-80b4-ea68efdfdf15.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7785190/c9c2e2e2-0184-11e5-980c-8385191ccb00.png

**Comment by dreamnet** [comment]
@Trubbel Jup, good! :+1:
