### ISSUE TITLE
iXpenselt

### ISSUE THREAD

**Issue by Gtech202** [glasklart/hd#1344]
**App Name:** iXpenseIt
**Bundle ID:** iXpenseIt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284947174">284947174</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ixpenseit/id284947174?mt=8&uo=4">https://itunes.apple.com/us/app/ixpenseit/id284947174?mt=8&uo=4</a>
**App Version:** 9.2.3
**Seller:** FYI Mobileware, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fyi-mobileware-inc/id284947177?uo=4">© FYI Mobileware, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/dc/40/dc/dc40dc04-35eb-4a05-91a6-aae981158c38/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417087-32f36182-c254-11e7-8829-3969f244fa4d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417087-32f36182-c254-11e7-8829-3969f244fa4d.png)
https://user-images.githubusercontent.com/2068130/32417087-32f36182-c254-11e7-8829-3969f244fa4d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32417097-42953098-c254-11e7-8b41-0a5e84e8815a.png
