### ISSUE TITLE
DC Rider

### ISSUE THREAD

**Issue by Gtech202** [glasklart/hd#1346]
**App Name:** DC Rider
**Bundle ID:** com.wapo.washopedia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382298536">382298536</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dc-rider/id382298536?mt=8&uo=4">https://itunes.apple.com/us/app/dc-rider/id382298536?mt=8&uo=4</a>
**App Version:** 5.2.1
**Seller:** The Washington Post Company
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-washington-post/id352509420?uo=4">© The Washington Post</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/5a/f8/3e/5af83e61-7973-13ab-a8d5-1c72ecab827e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417169-ae6b0db4-c255-11e7-9057-6d691f67f160.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417169-ae6b0db4-c255-11e7-9057-6d691f67f160.png)
https://user-images.githubusercontent.com/2068130/32417169-ae6b0db4-c255-11e7-9057-6d691f67f160.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32417175-be52486e-c255-11e7-8a23-bde8d2c49b4e.png
