### ISSUE TITLE
SMS Rage Faces - 3000+ Faces and Memes

### ISSUE THREAD

**Issue by Gtech202** [glasklart/hd#1349]
**App Name:** SMS Rage Faces - 3000+ Faces and Memes
**Bundle ID:** com.toucheapps.smsragefaces
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478755973">478755973</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sms-rage-faces-3000-faces-and-memes/id478755973?mt=8&uo=4">https://itunes.apple.com/us/app/sms-rage-faces-3000-faces-and-memes/id478755973?mt=8&uo=4</a>
**App Version:** 8.6.1
**Seller:** Robert Lemoine
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/robert-lemoine/id453626272?uo=4">© Robert Lemoine</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/b3/62/d3/b362d3be-86e8-de5e-36c1-0b62dc694eed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32674945-74012038-c655-11e7-9a62-8fff959142c1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32674945-74012038-c655-11e7-9a62-8fff959142c1.png)
https://user-images.githubusercontent.com/2068130/32674945-74012038-c655-11e7-9a62-8fff959142c1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32674965-86b849d6-c655-11e7-8c76-1c36c16eede0.png
