### ISSUE TITLE
Ride On Real Time

### ISSUE THREAD

**Issue by Gtech202** [glasklart/hd#1351]
**App Name:** Ride On Real Time
**Bundle ID:** com.mcdot.rideon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514123179">514123179</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ride-on-real-time/id514123179?mt=8&uo=4">https://itunes.apple.com/us/app/ride-on-real-time/id514123179?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Network Engineering & Resources Development Specialists, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-nerds-group-llc/id514123182?uo=4">© The NERDS Group, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/18/ab/cb/18abcb36-4d2e-5125-1d7d-e8d29b0ee166/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39839323-0e24b346-53dc-11e8-8803-4fce6032ebc7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39839323-0e24b346-53dc-11e8-8803-4fce6032ebc7.png)
https://user-images.githubusercontent.com/2068130/39839323-0e24b346-53dc-11e8-8803-4fce6032ebc7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39839344-1de6aa3c-53dc-11e8-92c2-2af88ea95d4e.png
