### ISSUE TITLE
Cinépolis

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1352]
**App Name:** Cinépolis
**Bundle ID:** mx.com.cinepolis.Cinepolis
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=352134875">352134875</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cin%C3%A9polis/id352134875?uo=4">https://apps.apple.com/us/app/cin%C3%A9polis/id352134875?uo=4</a>
**App Version:** 4.2.8
**Seller:** Internet Architects Consulting
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ia-interactive/id352134878?uo=4">© IA interactive</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/93/f1/1f/93f11f0f-58f9-e715-d62e-d30f865ffd72/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60920433-7731ec80-a298-11e9-8407-202263c42a69.png)

**Comment by ivanov007** [comment]
needs update

**Comment by dreamnet** [comment]
@ivanov007 All done. 😁

**Comment by ivanov007** [comment]
@dreamnet :open_mouth: did you remade it?

**Comment by dreamnet** [comment]
@ivanov007 Jup! 😁

**Comment by ivanov007** [comment]
needs update

**Comment by ivanov007** [comment]
I made the source file but at the moment I don't have photoshop to create the icon version, can someone help me with that?
source: 
https://user-images.githubusercontent.com/3090247/60910609-e54dc380-a246-11e9-8416-72e46490ca2f.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60920433-7731ec80-a298-11e9-8407-202263c42a69.png)
https://user-images.githubusercontent.com/2068130/60920433-7731ec80-a298-11e9-8407-202263c42a69.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60920466-87e26280-a298-11e9-9aca-b50161cf2b11.png
