### ISSUE TITLE
Aworded Crack (Apalabrados)

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1353]
**App Name:** Aworded Crack (Apalabrados)
**Bundle ID:** com.apalabrados.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441092257">441092257</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aworded-crack-apalabrados/id441092257?mt=8&uo=4">https://itunes.apple.com/us/app/aworded-crack-apalabrados/id441092257?mt=8&uo=4</a>
**App Version:** 3.3.3
**Seller:** Etermax
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/etermax/id286461525?uo=4>© Etermax</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/d5/76/f3/d576f395-f8fd-01f2-d8aa-cd2648a08157/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18629915/431adcfa-7e69-11e6-80cd-b9e4efc44459.png)

**Comment by grkka** [comment]
Needs upadte to v 5.00.0

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18629915/431adcfa-7e69-11e6-80cd-b9e4efc44459.png)
https://cloud.githubusercontent.com/assets/10730122/18629915/431adcfa-7e69-11e6-80cd-b9e4efc44459.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18629916/431b320e-7e69-11e6-90b1-cb113366f23f.png
