### ISSUE TITLE
Sizer – Clothes That Fits

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#1357]
**App Name:** Sizer – Clothes That Fits
**Bundle ID:** com.factory.sizer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424569529">424569529</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sizer-clothes-that-fits/id424569529?mt=8&uo=4">https://itunes.apple.com/us/app/sizer-clothes-that-fits/id424569529?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Dmitry Provotorov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/manufactura/id424569532?uo=4">© Manufactura</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/33/9a/07/339a0731-eadf-1f19-7ada-51f0c88a7b01/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39393054-b1e07602-4ac0-11e8-9f7a-141b263f2e45.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39393054-b1e07602-4ac0-11e8-9f7a-141b263f2e45.png)
https://user-images.githubusercontent.com/2068130/39393054-b1e07602-4ac0-11e8-9f7a-141b263f2e45.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39393060-c242de9a-4ac0-11e8-9de4-903af9ed7a5d.png
