### ISSUE TITLE
Tiles Puzzle (15 puzzle)

### ISSUE THREAD

**Issue by chrismallow** [glasklart/hd#1358]
**App Name:** Tiles Puzzle (15 puzzle)
**Bundle ID:** com.yourcompany.tilespuzzle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=328598205">328598205</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tiles-puzzle-15-puzzle/id328598205?mt=8&uo=4">https://itunes.apple.com/us/app/tiles-puzzle-15-puzzle/id328598205?mt=8&uo=4</a>
**App Version:** 6.1.0
**Seller:** Felipe Tumonis
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/felipe-tumonis/id1145138848?uo=4">© Felipe Tumonis</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/03/f0/97/03f0976f-ab26-911c-73c7-2c56c8c404dd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417129-05ae2b20-c255-11e7-9827-9c1de06a2b06.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417129-05ae2b20-c255-11e7-9827-9c1de06a2b06.png)
https://user-images.githubusercontent.com/2068130/32417129-05ae2b20-c255-11e7-9827-9c1de06a2b06.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32417136-169c2d6a-c255-11e7-80e6-cac4633384d5.png
