### ISSUE TITLE
Sub FM

### ISSUE THREAD

**Issue by Gokshura** [glasklart/hd#1359]
**App Name:** Sub FM
**Bundle ID:** com.codearmy.subfm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431510233">431510233</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sub-fm/id431510233?mt=8&uo=4">https://itunes.apple.com/us/app/sub-fm/id431510233?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Phil Greenway
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/phil-greenway/id321492275?uo=4>© Phil Greenway</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/b9/11/81/b91181a1-8709-685e-f000-5cb592802b9d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19600995/ab705210-97a7-11e6-8218-ef1330011dce.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19600995/ab705210-97a7-11e6-8218-ef1330011dce.png)
https://cloud.githubusercontent.com/assets/20930745/19600995/ab705210-97a7-11e6-8218-ef1330011dce.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19601019/c0a6aada-97a7-11e6-8e7e-d5f8e4b6ac6f.png
