### ISSUE TITLE
HotelForYou, hotel booking

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#136]
**App Name:** HotelForYou, hotel booking
**Bundle ID:** com.louvrehotels
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307367287">307367287</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hotelforyou-hotel-booking/id307367287?mt=8&uo=4">https://itunes.apple.com/us/app/hotelforyou-hotel-booking/id307367287?mt=8&uo=4</a>
**App Version:** 2.8.1
**Seller:** Louvre Hotels
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/louvre-hotels/id307367290?uo=4">© Louvre Hotels</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/7b/88/ec/7b88ecad-0170-1333-d18d-9753b5d60393/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692350-be1fe62e-c716-11e7-8d41-ff120b134f7a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692350-be1fe62e-c716-11e7-8d41-ff120b134f7a.png)
https://user-images.githubusercontent.com/2068130/32692350-be1fe62e-c716-11e7-8d41-ff120b134f7a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692351-cf5ae114-c716-11e7-926d-354ea626d36e.png
