### ISSUE TITLE
NetwerkRadar

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1360]
**App Name:** NetwerkRadar
**Bundle ID:** nl.oberon.NetwerkRadar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376641329">376641329</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/nl/app/netwerkradar/id376641329?mt=8&uo=4">https://itunes.apple.com/nl/app/netwerkradar/id376641329?mt=8&uo=4</a>
**App Version:** 2.8
**Seller:** Oberon Interactive
**Developer:** <a target="_blank" href=https://itunes.apple.com/nl/developer/oberon-interactive/id317065437?uo=4>© Oberon Interactive</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/12/6a/b6/126ab6fe-4e6a-6142-0f0c-2a9879979b21/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19600779/cbb75a6a-97a6-11e6-8d0e-6f8ccbd8933e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19600779/cbb75a6a-97a6-11e6-8d0e-6f8ccbd8933e.png)
https://cloud.githubusercontent.com/assets/20930745/19600779/cbb75a6a-97a6-11e6-8d0e-6f8ccbd8933e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19600793/e30bb4e0-97a6-11e6-9c3a-c146f8e58ae5.png
