### ISSUE TITLE
iCulture

### ISSUE THREAD

**Issue by pvdochtend** [glasklart/hd#1361]
**App Name:** iCulture
**Bundle ID:** nl.iculture.iCulture
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504842981">504842981</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iculture/id504842981?mt=8&uo=4">https://itunes.apple.com/us/app/iculture/id504842981?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** iCltr VOF
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/icltr-vof/id504842984?uo=4">© iCltr VOF</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/ef/1e/fa/ef1efa8e-47e2-2c32-19a5-fe7b4d0b9ecb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039591/ea7d0420-a446-11e6-9ee8-e34cf8835bb2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039591/ea7d0420-a446-11e6-9ee8-e34cf8835bb2.png)
https://cloud.githubusercontent.com/assets/20930745/20039591/ea7d0420-a446-11e6-9ee8-e34cf8835bb2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20039603/00a5d81c-a447-11e6-9bae-c37f559deca6.png
