### ISSUE TITLE
Pangolin

### ISSUE THREAD

**Issue by q2r5** [glasklart/hd#1362]
**App Name:** Pangolin
**Bundle ID:** com.feedtank.Pangolin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514959471">514959471</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pangolin/id514959471?mt=8&uo=4">https://itunes.apple.com/us/app/pangolin/id514959471?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Feedtank LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/feedtank-llc/id466448127?uo=4">© Feedtank LLC</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple2/v4/c9/83/93/c98393ce-5359-b133-b1c4-ef8c923a1943/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40585000-7cf2d79e-61ab-11e8-9e34-7733b9f56e33.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40585000-7cf2d79e-61ab-11e8-9e34-7733b9f56e33.png)
https://user-images.githubusercontent.com/2068130/40585000-7cf2d79e-61ab-11e8-9e34-7733b9f56e33.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/40585008-8c595050-61ab-11e8-94c9-09c97ca209ce.png
