### ISSUE TITLE
ESPN Tournament Challenge

### ISSUE THREAD

**Issue by q2r5** [glasklart/hd#1363]
**App Name:** ESPN Tournament Challenge
**Bundle ID:** com.espn.tcmen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=359891723">359891723</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/espn-tournament-challenge/id359891723?mt=8&uo=4">https://itunes.apple.com/us/app/espn-tournament-challenge/id359891723?mt=8&uo=4</a>
**App Version:** 5.5.3
**Seller:** ESPN Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/espn/id317469187?uo=4">© ESPN</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/05/f9/a1/05f9a1aa-c5fb-657c-e6e7-c9253ab68dbb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417047-8af28c7e-c253-11e7-880c-52a71724d243.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417047-8af28c7e-c253-11e7-880c-52a71724d243.png)
https://user-images.githubusercontent.com/2068130/32417047-8af28c7e-c253-11e7-880c-52a71724d243.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32417052-a1cb5246-c253-11e7-8e58-1a488b62d13d.png
