### ISSUE TITLE
NHL

### ISSUE THREAD

**Issue by q2r5** [glasklart/hd#1364]
**App Name:** NHL
**Bundle ID:** com.nhl.gc1112.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465092669">465092669</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nhl/id465092669?mt=8&uo=4">https://itunes.apple.com/us/app/nhl/id465092669?mt=8&uo=4</a>
**App Version:** 7.0.0
**Seller:** Major League Baseball Advanced Media
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mlbam/id1080404161?uo=4>© mlbam</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/74/67/f0/7467f0be-34b0-a8b6-4312-dd397de737e9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12737036/92052f74-c955-11e5-9117-3d4a9d53d77b.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12737036/92052f74-c955-11e5-9117-3d4a9d53d77b.png)
https://cloud.githubusercontent.com/assets/10730122/12737036/92052f74-c955-11e5-9117-3d4a9d53d77b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12737035/92043b14-c955-11e5-8be9-7a8cc4ef7308.png
