### ISSUE TITLE
TV 2 Nyheder

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#1369]
**App Name:** TV 2 Nyheder
**Bundle ID:** dk.tv2.nyhederne
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=459099763">459099763</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/tv-2-nyheder/id459099763?uo=4">https://apps.apple.com/gb/app/tv-2-nyheder/id459099763?uo=4</a>
**App Version:** 7.3.4
**Seller:** TV 2 Danmark A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/tv-2-danmark-a-s/id431851124?uo=4">© TV 2 Danmark A/S</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/fd/97/2b/fd972b31-6e98-375d-471c-653f4ce3a886/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67156049-0def5a00-f31a-11e9-90da-7ddcf1ff259a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19962815/b4453286-a1b9-11e6-8fe5-b6eb8f73309c.png)
https://cloud.githubusercontent.com/assets/20930745/19962815/b4453286-a1b9-11e6-8fe5-b6eb8f73309c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19962833/cfc57318-a1b9-11e6-8b12-c21f607a892c.png

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8.
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67156049-0def5a00-f31a-11e9-90da-7ddcf1ff259a.png)
https://user-images.githubusercontent.com/2068130/67156049-0def5a00-f31a-11e9-90da-7ddcf1ff259a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/67156059-1f386680-f31a-11e9-98b9-7d75f34b8c6a.png
