### ISSUE TITLE
Spotify Music

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#137]
**App Name:** Spotify Music
**Bundle ID:** com.spotify.client
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324684580">324684580</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spotify-music/id324684580?mt=8&uo=4">https://itunes.apple.com/us/app/spotify-music/id324684580?mt=8&uo=4</a>
**App Version:** 3.4.0
**Seller:** Spotify
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/spotify-ltd./id324684583?uo=4>© Spotify Ltd.</a>
**Supported Devices:** iPadThirdGen4G, iPodTouchFifthGen, iPhone4S, iPhone5, iPad2Wifi, iPhone5c, iPad23G, iPadMini, iPadThirdGen, iPadFourthGen, iPhone4, iPhone6Plus, iPhone5s, iPadFourthGen4G, iPadMini4G, iPhone6
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/87/8c/44/878c4451-835b-f01b-8847-af04a5b83f4b/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8523771/7d45174c-23f7-11e5-8679-28683566776d.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8523771/7d45174c-23f7-11e5-8679-28683566776d.png)
https://cloud.githubusercontent.com/assets/10730122/8523771/7d45174c-23f7-11e5-8679-28683566776d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8523767/7a2149d2-23f7-11e5-9db9-87e0003c4d52.png
