### ISSUE TITLE
O2Jam U

### ISSUE THREAD

**Issue by Gokshura** [glasklart/hd#1370]
**App Name:** O2Jam U
**Bundle ID:** com.momocorp.o2jamu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=524927135">524927135</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/o2jam-u/id524927135?mt=8&uo=4">https://itunes.apple.com/us/app/o2jam-u/id524927135?mt=8&uo=4</a>
**App Version:** 1.6.0.11
**Seller:** MOMO Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/momo-corporation/id524927138?uo=4">© MOMO Corporation</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/19/02/f5/1902f553-1fad-f5a3-aa3d-abcdc99c290e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698302-8f741ccc-c7a3-11e7-9bc5-4af64c9f37d7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698302-8f741ccc-c7a3-11e7-9bc5-4af64c9f37d7.png)
https://user-images.githubusercontent.com/2068130/32698302-8f741ccc-c7a3-11e7-9bc5-4af64c9f37d7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32698303-9d876b52-c7a3-11e7-8803-c0459402d8e3.png
