### ISSUE TITLE
Mercado Libre

### ISSUE THREAD

**Issue by Gokshura** [glasklart/hd#1371]
**App Name:** Mercado Libre
**Bundle ID:** com.3mosquitos.MercadoLibre
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=463624852">463624852</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mercado-libre/id463624852?mt=8&uo=4">https://itunes.apple.com/us/app/mercado-libre/id463624852?mt=8&uo=4</a>
**App Version:** 8.1.0
**Seller:** MercadoLibre S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mercadolibre/id463624855?uo=4">© MercadoLibre</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/5a/40/72/5a40727a-6494-38e5-df32-e4c42b128b11/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19962634/ebf9dfca-a1b8-11e6-9fd9-df08bae7d8c4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19962634/ebf9dfca-a1b8-11e6-9fd9-df08bae7d8c4.png)
https://cloud.githubusercontent.com/assets/20930745/19962634/ebf9dfca-a1b8-11e6-9fd9-df08bae7d8c4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19962660/0b25666c-a1b9-11e6-89d6-f2f8c764e0c9.png
