### ISSUE TITLE
101 WRIF

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1372]
**App Name:** 101 WRIF
**Bundle ID:** com.greatermediaradio.wrif
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520140927">520140927</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/101-wrif/id520140927?mt=8&uo=4">https://itunes.apple.com/us/app/101-wrif/id520140927?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Greater Media Radio, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/greater-media-radio-inc/id520126086?uo=4">© Greater Media Radio, Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/f2/fd/2a/f2fd2a38-d075-b39a-405c-50991b20be6d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19962180/c782d77a-a1b6-11e6-9dd0-c35ef9743dea.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19962180/c782d77a-a1b6-11e6-9dd0-c35ef9743dea.png)
https://cloud.githubusercontent.com/assets/20930745/19962180/c782d77a-a1b6-11e6-9dd0-c35ef9743dea.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19962207/e4960792-a1b6-11e6-8fba-fc3135e1d81b.png
