### ISSUE TITLE
Wemlin

### ISSUE THREAD

**Issue by tonearmed** [glasklart/hd#1373]
**App Name:** Wemlin
**Bundle ID:** ch.netcetera.iphone-tramdroid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=293648832">293648832</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wemlin/id293648832?mt=8&uo=4">https://itunes.apple.com/us/app/wemlin/id293648832?mt=8&uo=4</a>
**App Version:** 2.1.16
**Seller:** Netcetera AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/netcetera-ag/id293648835?uo=4>© Netcetera AG</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/46/02/eb/4602eb8c-d38f-5b2e-3c32-ab671e89cd4d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19600365/f8deecc6-97a4-11e6-968d-fe935725ab1f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19600365/f8deecc6-97a4-11e6-968d-fe935725ab1f.png)
https://cloud.githubusercontent.com/assets/20930745/19600365/f8deecc6-97a4-11e6-968d-fe935725ab1f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19600386/112f1e18-97a5-11e6-9c52-51c3919fffd9.png
