### ISSUE TITLE
UBS Mobile Banking

### ISSUE THREAD

**Issue by tonearmed** [glasklart/hd#1375]
**App Name:** UBS Mobile Banking
**Bundle ID:** com.ubs.mobileBanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441068021">441068021</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/ubs-mobile-banking/id441068021?mt=8&uo=4">https://itunes.apple.com/gb/app/ubs-mobile-banking/id441068021?mt=8&uo=4</a>
**App Version:** 6.5.0
**Seller:** UBS AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/ubs-ag/id369153318?uo=4>© UBS AG</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/e5/34/42/e534420e-a94e-6ed8-939a-58160a839e92/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19737119/7667ec72-9bb2-11e6-8f3a-085f83a51029.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19737119/7667ec72-9bb2-11e6-8f3a-085f83a51029.png)
https://cloud.githubusercontent.com/assets/2068130/19737119/7667ec72-9bb2-11e6-8f3a-085f83a51029.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19737136/8e999b92-9bb2-11e6-873b-2dc418048498.png
