### ISSUE TITLE
2018-19 NBA App

### ISSUE THREAD

**Issue by tonearmed** [glasklart/hd#1376]
**App Name:** 2018-19 NBA App
**Bundle ID:** com.nbaimd.gametime.universal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484672289">484672289</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/2018-19-nba-app/id484672289?uo=4">https://apps.apple.com/gb/app/2018-19-nba-app/id484672289?uo=4</a>
**App Version:** 1905.1
**Seller:** NBA Properties, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/nba/id398083945?uo=4">© NBA</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/57/78/84/577884d2-49e8-3e13-46fc-b5a123b9acf0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973608-4d8f7a80-95a2-11e9-8ad4-65da7a023bda.png)

**Comment by 2Qt2beStr8** [comment]
same as #3526

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19579040/eda2e1c2-971e-11e6-899e-ad2121efb7b5.png)
https://cloud.githubusercontent.com/assets/20930745/19579040/eda2e1c2-971e-11e6-899e-ad2121efb7b5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19579079/0808727a-971f-11e6-9006-4ff8f8401e39.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973608-4d8f7a80-95a2-11e9-8ad4-65da7a023bda.png)
e=https://user-images.githubusercontent.com/20930745/59973608-4d8f7a80-95a2-11e9-8ad4-65da7a023bda.png

Source:
https://user-images.githubusercontent.com/20930745/59973609-4ec0a780-95a2-11e9-98e9-eb51100625a1.png
