### ISSUE TITLE
Swiss Forex

### ISSUE THREAD

**Issue by tonearmed** [glasklart/hd#1378]
**App Name:** Swiss Forex
**Bundle ID:** com.dukascopy.iswfx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=333209903">333209903</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swiss-forex/id333209903?mt=8&uo=4">https://itunes.apple.com/us/app/swiss-forex/id333209903?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Dukascopy Bank SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dukascopy-bank-sa/id333209906?uo=4>© Dukascopy Bank SA</a>
**Supported Devices:** iPhone6, iPadFourthGen, iPad23G, iPhone4, iPad3G, iPhone5s, iPadThirdGen, iPhone-3GS, iPhone5, iPad2Wifi, iPhone6Plus, iPadWifi, iPadFourthGen4G, iPodTouchFifthGen, iPhone5c, iPodTouchThirdGen, iPadThirdGen4G, iPodTouchFourthGen, iPadMini4G, iPhone4S, iPadMini
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/99/f9/53/99f95349-2be5-6c44-0725-e13318080c65/mzl.ilflhydp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8393541/356e7786-1d14-11e5-8786-bd85518b00c7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8393541/356e7786-1d14-11e5-8786-bd85518b00c7.png)
https://cloud.githubusercontent.com/assets/2068130/8393541/356e7786-1d14-11e5-8786-bd85518b00c7.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8393543/451dfa9e-1d14-11e5-81ef-efa275fa961e.png
