### ISSUE TITLE
Stocard - Rewards Cards Wallet

### ISSUE THREAD

**Issue by tonearmed** [glasklart/hd#1380]
**App Name:** Stocard - Rewards Cards Wallet
**Bundle ID:** Stocard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444578884">444578884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stocard-rewards-cards-wallet/id444578884?mt=8&uo=4">https://itunes.apple.com/us/app/stocard-rewards-cards-wallet/id444578884?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** Stocard UG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stocard/id444578887?uo=4>© Stocard</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/ba/6a/bc/ba6abc10-3cd1-8756-7e0e-139d98031269/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18104000/5b96c908-6ef9-11e6-90c5-6135482e17d3.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Stocard - Rewards Cards Wallet
**Bundle ID:** Stocard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444578884">444578884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stocard-rewards-cards-wallet/id444578884?mt=8&uo=4">https://itunes.apple.com/us/app/stocard-rewards-cards-wallet/id444578884?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** Stocard UG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stocard/id444578887?uo=4>© Stocard</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/ba/6a/bc/ba6abc10-3cd1-8756-7e0e-139d98031269/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by alpcinar** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13483942/18027106/dcdd87c0-6c62-11e6-8b53-c163633268f1.png)
https://cloud.githubusercontent.com/assets/13483942/18027106/dcdd87c0-6c62-11e6-8b53-c163633268f1.png
Source:
https://cloud.githubusercontent.com/assets/13483942/18027109/ece6e0ee-6c62-11e6-957d-c3c181fbb13e.png

**Comment by dreamnet** [comment]
@alpcinar Yes! :+1:
