### ISSUE TITLE
tvtid

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#1387]
**App Name:** tvtid
**Bundle ID:** dk.tv2.tvtid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=485261551">485261551</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tvtid/id485261551?mt=8&uo=4">https://itunes.apple.com/us/app/tvtid/id485261551?mt=8&uo=4</a>
**App Version:** 2.41
**Seller:** TV 2 Danmark A/S
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tv-2-danmark-a-s/id431851124?uo=4>© TV 2 Danmark A/S</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/35/17/51/35175190-c106-c6d7-acd5-1cb4bf21413b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626895/76e11f4e-993b-11e6-8b4b-63bcddc42f97.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626895/76e11f4e-993b-11e6-8b4b-63bcddc42f97.png)
https://cloud.githubusercontent.com/assets/20930745/19626895/76e11f4e-993b-11e6-8b4b-63bcddc42f97.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626899/90a884da-993b-11e6-8f6d-e342a3d4e38b.png
