### ISSUE TITLE
WeatherMap+

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#1389]
**App Name:** WeatherMap+
**Bundle ID:** se.weathermap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=471629622">471629622</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weathermap+/id471629622?mt=8&uo=4">https://itunes.apple.com/us/app/weathermap+/id471629622?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Michal Frankowski
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/michal-frankowski/id330935779?uo=4>© Michal Frankowski</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/c0/f6/05/c0f605e4-0241-3f11-7725-1404c3b328ee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18794666/e0aaf162-81c0-11e6-8651-4ba194b443cf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18794666/e0aaf162-81c0-11e6-8651-4ba194b443cf.png)
https://cloud.githubusercontent.com/assets/20930745/18794666/e0aaf162-81c0-11e6-8651-4ba194b443cf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18794676/f2128866-81c0-11e6-9987-7fc774c2f33a.png
