### ISSUE TITLE
eWeather HD - Accurate 10 Day Weather Forecast with Severe Alerts, NOAA Hi-Res Radar and Storm Tracking

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#1391]
**App Name:** eWeather HD - Accurate 10 Day Weather Forecast with Severe Alerts, NOAA Hi-Res Radar and Storm Tracking
**Bundle ID:** com.elecont.EWeatherClock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401533966">401533966</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/eweather-hd-accurate-10-day/id401533966?mt=8&uo=4">https://itunes.apple.com/us/app/eweather-hd-accurate-10-day/id401533966?mt=8&uo=4</a>
**App Version:** 3.6
**Seller:** Elecont LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/elecont-llc/id401533969?uo=4>© Elecont LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/5b/77/f0/5b77f061-6957-ae95-adc1-2b2445176ab3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808336/87479694-825f-11e6-9df9-5b2934fbf69f.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** eWeather HD - Accurate 10 Day Weather Forecast with Severe Alerts, NOAA Hi-Res Radar and Storm Tracking
**Bundle ID:** com.elecont.EWeatherClock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401533966">401533966</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/eweather-hd-accurate-10-day/id401533966?mt=8&uo=4">https://itunes.apple.com/us/app/eweather-hd-accurate-10-day/id401533966?mt=8&uo=4</a>
**App Version:** 3.6
**Seller:** Elecont LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/elecont-llc/id401533969?uo=4>© Elecont LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/5b/77/f0/5b77f061-6957-ae95-adc1-2b2445176ab3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808336/87479694-825f-11e6-9df9-5b2934fbf69f.png)
https://cloud.githubusercontent.com/assets/20930745/18808336/87479694-825f-11e6-9df9-5b2934fbf69f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18808341/b5edcc66-825f-11e6-94f8-406ebb48a268.png
