### ISSUE TITLE
Swissquote - Mobile Banking and Trading Solution

### ISSUE THREAD

**Issue by tonearmed** [glasklart/hd#1393]
**App Name:** Swissquote - Mobile Banking and Trading Solution
**Bundle ID:** com.swissquote.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=285691076">285691076</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swissquote-mobile-banking/id285691076?mt=8&uo=4">https://itunes.apple.com/us/app/swissquote-mobile-banking/id285691076?mt=8&uo=4</a>
**App Version:** 6.1.1
**Seller:** Swissquote
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/swissquote/id285691079?uo=4">© Swissquote</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple22/v4/bb/6f/58/bb6f58cc-6ee8-93eb-03b8-5dc095b7769f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19961997/cd8e40f6-a1b5-11e6-8abd-8be32c44075e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19961997/cd8e40f6-a1b5-11e6-8abd-8be32c44075e.png)
https://cloud.githubusercontent.com/assets/20930745/19961997/cd8e40f6-a1b5-11e6-8abd-8be32c44075e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19962009/eb8f36fa-a1b5-11e6-82b8-516f6fc62d2b.png
