### ISSUE TITLE
iHotel – Hotel Search

### ISSUE THREAD

**Issue by Hawri84** [glasklart/hd#1396]
**App Name:** iHotel – Hotel Search
**Bundle ID:** com.hrs.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=332193586">332193586</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ihotel-hotel-search/id332193586?mt=8&uo=4">https://itunes.apple.com/us/app/ihotel-hotel-search/id332193586?mt=8&uo=4</a>
**App Version:** 6.3.0
**Seller:** HRS Hotel Reservation Service Robert Ragge GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hrs-hotel-reservation-service/id332193589?uo=4>© HRS-Hotel Reservation Service - Robert Ragge GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/cf/5f/06/cf5f0671-b028-c380-b093-05a9a95d9d88/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419231/aa838f72-df7c-11e5-848a-ea0ce62b3b53.png)

**Comment by Trubbel** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419231/aa838f72-df7c-11e5-848a-ea0ce62b3b53.png)
https://cloud.githubusercontent.com/assets/2068130/13419231/aa838f72-df7c-11e5-848a-ea0ce62b3b53.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13419242/ba45865e-df7c-11e5-913f-c693bedcfa26.png
