### ISSUE TITLE
Norsk Tipping

### ISSUE THREAD

**Issue by Hawri84** [glasklart/hd#1397]
**App Name:** Norsk Tipping
**Bundle ID:** no.norsktipping.mainiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418533267">418533267</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/no/app/norsk-tipping/id418533267?mt=8&uo=4">https://itunes.apple.com/no/app/norsk-tipping/id418533267?mt=8&uo=4</a>
**App Version:** 2.14.3
**Seller:** Norsk Tipping AS
**Developer:** <a target="_blank" href=https://itunes.apple.com/no/developer/norsk-tipping-as/id418334550?uo=4>© Norsk Tipping AS</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/e5/ee/51/e5ee51ac-9c4a-0019-1687-86ac2ae5d0e3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19578497/3672bb82-971c-11e6-9ccb-bb056fad3509.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19578497/3672bb82-971c-11e6-9ccb-bb056fad3509.png)
https://cloud.githubusercontent.com/assets/20930745/19578497/3672bb82-971c-11e6-9ccb-bb056fad3509.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19578518/51049e02-971c-11e6-8994-294a8ec30d78.png
