### ISSUE TITLE
Ventrilode

### ISSUE THREAD

**Issue by RonaldFanta** [glasklart/hd#1399]
**App Name:** Ventrilode
**Bundle ID:** com.pandaris.ventrilode
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=486115720">486115720</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ventrilode/id486115720?mt=8&uo=4">https://itunes.apple.com/us/app/ventrilode/id486115720?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Flamethrower plc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/flamethrower/id1110459680?uo=4>© Flamethrower</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/5f/47/af/5f47afd2-321e-2aed-41ca-3c2e4704ed60/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19578250/2fd1f7da-971b-11e6-8c10-b319e62003b6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19578250/2fd1f7da-971b-11e6-8c10-b319e62003b6.png)
https://cloud.githubusercontent.com/assets/20930745/19578250/2fd1f7da-971b-11e6-8c10-b319e62003b6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19578263/459880f2-971b-11e6-8c90-45b49c44966d.png
