### ISSUE TITLE
SF Bio

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#140]
**App Name:** SF Bio
**Bundle ID:** se.sf.sfbio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479273432">479273432</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sf-bio/id479273432?mt=8&uo=4">https://itunes.apple.com/us/app/sf-bio/id479273432?mt=8&uo=4</a>
**App Version:** 5.0.0
**Seller:** SF Bio AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sf-bio-ab/id479273435?uo=4>© SF Bio AB</a>
**Supported Devices:** iPhone4, iPadFourthGen4G, iPhone4S, iPhone5, iPhone5s, iPadMini, iPadThirdGen, iPad2Wifi, iPodTouchFifthGen, iPhone-3GS, iPadMini4G, iPadFourthGen, iPhone6Plus, iPadThirdGen4G, iPhone6, iPhone5c, iPad23G, iPodTouchFourthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/74/aa/17/74aa1708-4cfc-423c-fd48-5d796a859baf/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8374501/2de2917e-1bf6-11e5-9ba9-f3b6862cad1b.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8374501/2de2917e-1bf6-11e5-9ba9-f3b6862cad1b.png)
https://cloud.githubusercontent.com/assets/10730122/8374501/2de2917e-1bf6-11e5-9ba9-f3b6862cad1b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8374498/2a711a06-1bf6-11e5-9357-a23fd0e5418a.png
