### ISSUE TITLE
MyTIM Mobile

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1402]
**App Name:** MyTIM Mobile
**Bundle ID:** it.telecomitalia.119SelfService
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378783815">378783815</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/it/app/mytim-mobile/id378783815?mt=8&uo=4">https://itunes.apple.com/it/app/mytim-mobile/id378783815?mt=8&uo=4</a>
**App Version:** 4.2.4
**Seller:** Telecom Italia spa
**Developer:** <a target="_blank" href=https://itunes.apple.com/it/developer/telecom-italia-s.p.a./id294344675?uo=4>© Telecom Italia S.p.A.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/f0/e3/7d/f0e37d7e-c832-d6d9-4203-3b84e2145ead/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19578005/014bf362-971a-11e6-89ec-f48d87300fab.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19578005/014bf362-971a-11e6-89ec-f48d87300fab.png)
https://cloud.githubusercontent.com/assets/20930745/19578005/014bf362-971a-11e6-89ec-f48d87300fab.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19578027/1cc936e0-971a-11e6-9a5f-426b169052c6.png
