### ISSUE TITLE
Remote Mouse

### ISSUE THREAD

**Issue by gartentisch** [glasklart/hd#1407]
**App Name:** Remote Mouse
**Bundle ID:** com.remotemouse.remoteMouse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380450781">380450781</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/remote-mouse/id380450781?mt=8&uo=4">https://itunes.apple.com/us/app/remote-mouse/id380450781?mt=8&uo=4</a>
**App Version:** 3.12
**Seller:** YANG TIAN JIAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/yang-tian-jiao/id715503947?uo=4>© YANG TIAN JIAO</a>
**Supported Devices:** iPadMini, iPad2Wifi, iPadThirdGen, iPhone5c, iPodTouchFifthGen, iPhone6, iPhone6Plus, iPhone4, iPhone5, iPhone5s, iPhone4S, iPadFourthGen, iPadThirdGen4G, iPad23G, iPadFourthGen4G, iPadMini4G
**Original Artwork:**
<img src="http://a1320.phobos.apple.com/us/r30/Purple3/v4/7a/84/cf/7a84cfda-3cfb-6371-3a97-f7f6e667105d/mzl.zlngtlud.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6971693/4fec6f16-d94c-11e4-8934-c8bbc275e8fa.png)

**Comment by zmathiasz** [comment]
@dreamnet 

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6971693/4fec6f16-d94c-11e4-8934-c8bbc275e8fa.png)
https://cloud.githubusercontent.com/assets/10950389/6971693/4fec6f16-d94c-11e4-8934-c8bbc275e8fa.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6971703/614b6d7a-d94c-11e4-84b9-87f7a6f9887c.png
