### ISSUE TITLE
WifiAmp

### ISSUE THREAD

**Issue by gartentisch** [glasklart/hd#1408]
**App Name:** WifiAmp
**Bundle ID:** de.socialbit.wifiAmp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404170021">404170021</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wifiamp/id404170021?mt=8&uo=4">https://itunes.apple.com/us/app/wifiamp/id404170021?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Socialbit GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/socialbit-gmbh/id372603335?uo=4>© Socialbit GmbH</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/16/93/ff/1693ff9f-5006-a583-0f68-98fe512ab6da/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19577775/ec6ad0ea-9718-11e6-89cc-c3a885ae69de.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19577775/ec6ad0ea-9718-11e6-89cc-c3a885ae69de.png)
https://cloud.githubusercontent.com/assets/20930745/19577775/ec6ad0ea-9718-11e6-89cc-c3a885ae69de.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19577800/06792342-9719-11e6-9836-d8c5a1fe345b.png
