### ISSUE TITLE
ActMonitor 

### ISSUE THREAD

**Issue by CuByK** [glasklart/hd#1410]
**App Name:** ActMonitor
**Bundle ID:** ru.aeonika.AMonitor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519572740">519572740</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/actmonitor/id519572740?mt=8&uo=4">https://itunes.apple.com/us/app/actmonitor/id519572740?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Aeonika
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/aeonika/id446197827?uo=4">© Aeonika</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/16/e2/79/16e279cf-b5bf-bb9e-fcfd-8b90484a6b9a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417007-d3a3f1ac-c252-11e7-88d8-ef1b9f816c5d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32417007-d3a3f1ac-c252-11e7-88d8-ef1b9f816c5d.png)
https://user-images.githubusercontent.com/2068130/32417007-d3a3f1ac-c252-11e7-88d8-ef1b9f816c5d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32417010-e6505f5c-c252-11e7-80a9-72f4687ab849.png
