### ISSUE TITLE
Flashcode Barcode scanner & QR Reader & Generator

### ISSUE THREAD

**Issue by CuByK** [glasklart/hd#1412]
**App Name:** Flashcode Barcode scanner & QR Reader & Generator
**Bundle ID:** com.afmm.flashcode
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=329168540">329168540</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flashcode-barcode-scanner/id329168540?mt=8&uo=4">https://itunes.apple.com/us/app/flashcode-barcode-scanner/id329168540?mt=8&uo=4</a>
**App Version:** 7.7.3
**Seller:** Extenso Telecom
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/extenso/id750877913?uo=4">© Extenso</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/eb/c3/cf/ebc3cf79-1adc-734a-655d-029808521d91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19961835/0b12934c-a1b5-11e6-87df-b5364f72f388.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19961835/0b12934c-a1b5-11e6-87df-b5364f72f388.png)
https://cloud.githubusercontent.com/assets/20930745/19961835/0b12934c-a1b5-11e6-87df-b5364f72f388.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19961852/2ce013d2-a1b5-11e6-90fc-9e5f1b817142.png
