### ISSUE TITLE
SFR Mon Compte

### ISSUE THREAD

**Issue by CuByK** [glasklart/hd#1413]
**App Name:** SFR Mon Compte
**Bundle ID:** fr.sfr.SFRMonCompte
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=326161564">326161564</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sfr-mon-compte/id326161564?mt=8&uo=4">https://itunes.apple.com/us/app/sfr-mon-compte/id326161564?mt=8&uo=4</a>
**App Version:** 6.1.1
**Seller:** SFR
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sfr/id309172115?uo=4>© SFR</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/11/a2/23/11a223dc-2616-a55f-16b7-d589b3babffc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19577508/f9508616-9717-11e6-97ca-5543c898d533.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19577508/f9508616-9717-11e6-97ca-5543c898d533.png)
https://cloud.githubusercontent.com/assets/20930745/19577508/f9508616-9717-11e6-97ca-5543c898d533.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19577523/119a94a0-9718-11e6-98d3-5d3c8f46d8c9.png
