### ISSUE TITLE
SFR WiFi

### ISSUE THREAD

**Issue by CuByK** [glasklart/hd#1415]
**App Name:** SFR WiFi
**Bundle ID:** fr.sfr.sfrwifi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=309172112">309172112</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sfr-wifi/id309172112?mt=8&uo=4">https://itunes.apple.com/us/app/sfr-wifi/id309172112?mt=8&uo=4</a>
**App Version:** 4.1.0
**Seller:** SFR
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sfr/id309172115?uo=4>© SFR</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/8a/63/4e/8a634e38-c8a1-04a6-ffe6-20cd7abbf81b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19577286/f5ae22e4-9716-11e6-8b5a-3ebd351049d6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19577286/f5ae22e4-9716-11e6-8b5a-3ebd351049d6.png)
https://cloud.githubusercontent.com/assets/20930745/19577286/f5ae22e4-9716-11e6-8b5a-3ebd351049d6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19577302/0d02832c-9717-11e6-9e23-ef73eabff49b.png
