### ISSUE TITLE
Programme TV Télé 7 Jours - Guide TV et replay

### ISSUE THREAD

**Issue by CuByK** [glasklart/hd#1417]
**App Name:** Programme TV Télé 7 Jours - Guide TV et replay
**Bundle ID:** com.lagardere.Tele7
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=313386235">313386235</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/programme-tv-t%C3%A9l%C3%A9-7-jours-guide-tv-et-replay/id313386235?mt=8&uo=4">https://itunes.apple.com/us/app/programme-tv-t%C3%A9l%C3%A9-7-jours-guide-tv-et-replay/id313386235?mt=8&uo=4</a>
**App Version:** 4.3.5
**Seller:** LAGARDERE ACTIVE DIGITAL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lagard%C3%A8re-active-digital/id308310134?uo=4">© Lagardère Active Digital</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/6d/b6/31/6db63120-16f8-8d2b-2f41-04864ab672ee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32416602-2c35daf8-c24c-11e7-9509-c3282009522b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32416602-2c35daf8-c24c-11e7-9509-c3282009522b.png)
https://user-images.githubusercontent.com/2068130/32416602-2c35daf8-c24c-11e7-9509-c3282009522b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32416605-3bf8ed7c-c24c-11e7-9008-a2fd00bd12cc.png
