### ISSUE TITLE
Picfx

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#1422]
**App Name:** Picfx
**Bundle ID:** nz.co.activedevelopment.picfx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417563413">417563413</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/picfx/id417563413?mt=8&uo=4">https://itunes.apple.com/us/app/picfx/id417563413?mt=8&uo=4</a>
**App Version:** 6.8.2
**Seller:** David Boyes
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/activedevelopment/id417563416?uo=4>© ActiveDevelopment</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/23/55/66/23556664-403f-af24-66e4-2816e5986789/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892992/b8d9f702-4b27-11e6-9420-43ac85a52f52.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Picfx
**Bundle ID:** nz.co.activedevelopment.picfx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417563413">417563413</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/picfx/id417563413?mt=8&uo=4">https://itunes.apple.com/us/app/picfx/id417563413?mt=8&uo=4</a>
**App Version:** 6.8.2
**Seller:** David Boyes
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/activedevelopment/id417563416?uo=4>© ActiveDevelopment</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/23/55/66/23556664-403f-af24-66e4-2816e5986789/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892992/b8d9f702-4b27-11e6-9420-43ac85a52f52.png)
https://cloud.githubusercontent.com/assets/2068130/16892992/b8d9f702-4b27-11e6-9420-43ac85a52f52.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892993/c6c6bba2-4b27-11e6-8385-09757e4087ef.png
