### ISSUE TITLE
Media Markt Nederland

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#1423]
**App Name:** Media Markt Nederland
**Bundle ID:** hybrid.mediamarkt.com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=573907448">573907448</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/nl/app/media-markt-nederland/id573907448?mt=8&uo=4">https://itunes.apple.com/nl/app/media-markt-nederland/id573907448?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Media Markt E-Business GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/nl/artist/media-markt-e-business-gmbh/id386304607?uo=4>© Media Markt E-Business GmbH</a>
**Supported Devices:** iPodTouchFifthGen, iPadMini4G, iPhone6Plus, iPhone5, iPadFourthGen, iPhone6, iPadThirdGen, iPhone5s, iPadMini, iPadFourthGen4G, iPadThirdGen4G, iPad2Wifi, iPhone5c, iPad23G, iPhone4, iPhone4S
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/00/8b/8f/008b8fd9-9c1d-7161-2acc-d65f5eae2e15/mzl.ksjfeavm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7899800/06d7f876-0733-11e5-937e-f53201d96da3.png)

**Comment by Trubbel** [comment]
Icon is updated, using same icon as #5710

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7899800/06d7f876-0733-11e5-937e-f53201d96da3.png)
https://cloud.githubusercontent.com/assets/10730122/7899800/06d7f876-0733-11e5-937e-f53201d96da3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7899797/f98adbca-0732-11e5-9468-6023e9df378e.png
