### ISSUE TITLE
iSafe Pro

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#1424]
**App Name:** iSafe Pro
**Bundle ID:** net.fanship.iSafePod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=402012828">402012828</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/isafe-pro/id402012828?mt=8&uo=4">https://itunes.apple.com/us/app/isafe-pro/id402012828?mt=8&uo=4</a>
**App Version:** 9.3
**Seller:** Fung Kam Keung
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fanship/id327802296?uo=4>© Fanship</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple19/v4/e7/42/90/e742904e-c703-9091-02f4-fa5154a5d121/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19575825/c2bd8966-9710-11e6-91c2-ab8f107a8661.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19575825/c2bd8966-9710-11e6-91c2-ab8f107a8661.png)
https://cloud.githubusercontent.com/assets/20930745/19575825/c2bd8966-9710-11e6-91c2-ab8f107a8661.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19575842/d7deb4c8-9710-11e6-8c04-2a0b1f55e1f2.png
