### ISSUE TITLE
GAME ONE

### ISSUE THREAD

**Issue by CuByK** [glasklart/hd#1429]
**App Name:** GAME ONE
**Bundle ID:** com.mobiclip.gameone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=379070614">379070614</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/game-one/id379070614?mt=8&uo=4">https://itunes.apple.com/fr/app/game-one/id379070614?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** GAME ONE
**Developer:** <a target="_blank" href="https://itunes.apple.com/fr/developer/game-one-mobiclip/id379070617?uo=4">© GAME ONE / MOBICLIP</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/7d/9c/11/7d9c11b7-037f-9070-def1-1f3062d54510/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19960978/6b62d87e-a1b0-11e6-8490-f78778d63c84.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19960978/6b62d87e-a1b0-11e6-8490-f78778d63c84.png)
https://cloud.githubusercontent.com/assets/20930745/19960978/6b62d87e-a1b0-11e6-8490-f78778d63c84.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19960997/841b9f4a-a1b0-11e6-9c43-9cff160ae895.png
