### ISSUE TITLE
@bordeaux

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#143]
**App Name:** @bordeaux
**Bundle ID:** fr.bordeaux.agenda
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=481627729">481627729</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bordeaux/id481627729?mt=8&uo=4">https://itunes.apple.com/us/app/bordeaux/id481627729?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Mairie de Bordeaux
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mairie-de-bordeaux/id481627732?uo=4">© Mairie de Bordeaux</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/f6/ec/5c/f6ec5c99-c8c5-cd01-8f4a-f33a6c124d76/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692466-c12bef32-c718-11e7-8f8f-331ec879f56f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692466-c12bef32-c718-11e7-8f8f-331ec879f56f.png)
https://user-images.githubusercontent.com/2068130/32692466-c12bef32-c718-11e7-8f8f-331ec879f56f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692470-d074cd74-c718-11e7-99c3-b869a4c7dc1d.png
