### ISSUE TITLE
Telia Selvbetjening

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#1431]
**App Name:** Telia Selvbetjening
**Bundle ID:** com.teliasonera.selfservice.teliadenmark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=435181952">435181952</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/dk/app/telia-selvbetjening/id435181952?mt=8&uo=4">https://itunes.apple.com/dk/app/telia-selvbetjening/id435181952?mt=8&uo=4</a>
**App Version:** 4.2.5
**Seller:** TeliaSonera Mobile Networks AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/dk/developer/teliasonera/id309706080?uo=4>© TeliaSonera</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/b9/03/2f/b9032f4e-234a-f4ae-ea72-c68fc0cc4881/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19576713/5a70ed40-9714-11e6-98a9-19511cee739f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19576713/5a70ed40-9714-11e6-98a9-19511cee739f.png)
https://cloud.githubusercontent.com/assets/20930745/19576713/5a70ed40-9714-11e6-98a9-19511cee739f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19576738/712778d8-9714-11e6-8339-3271dc1a1490.png
