### ISSUE TITLE
Weathercube - Gestural Weather

### ISSUE THREAD

**Issue by bimpaats** [glasklart/hd#1433]
**App Name:** Weathercube - Gestural Weather
**Bundle ID:** com.appsuperb.weathercube
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555306679">555306679</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weathercube-gestural-weather/id555306679?mt=8&uo=4">https://itunes.apple.com/us/app/weathercube-gestural-weather/id555306679?mt=8&uo=4</a>
**App Version:** 1.5.4
**Seller:** V2 Digital Media B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appsuperb/id555306682?uo=4>© Appsuperb</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/e3/4e/80/e34e80a1-5990-d0d9-439e-c7bfd5052be7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19576934/51865e8a-9715-11e6-9327-ba145445c89e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19576934/51865e8a-9715-11e6-9327-ba145445c89e.png)
https://cloud.githubusercontent.com/assets/20930745/19576934/51865e8a-9715-11e6-9327-ba145445c89e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19576951/68c49abc-9715-11e6-81af-4f7f51570980.png
