### ISSUE TITLE
Jyske Mobilbank

### ISSUE THREAD

**Issue by hidii** [glasklart/hd#1434]
**App Name:** Jyske Mobilbank
**Bundle ID:** dk.jyskebank.jyskemobilbank
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418816320">418816320</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jyske-mobilbank/id418816320?mt=8&uo=4">https://itunes.apple.com/us/app/jyske-mobilbank/id418816320?mt=8&uo=4</a>
**App Version:** 3.2.0
**Seller:** Jyske Bank A/S
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jyske-bank/id412864294?uo=4>© Jyske Bank</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/56/e7/f7/56e7f74b-3a28-3cc6-3d5c-12ea57bfcd71/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19577126/20cac636-9716-11e6-954e-9f678a7205d4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19577126/20cac636-9716-11e6-954e-9f678a7205d4.png)
https://cloud.githubusercontent.com/assets/20930745/19577126/20cac636-9716-11e6-954e-9f678a7205d4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19577147/3970a84a-9716-11e6-847a-9896155cf2be.png
