### ISSUE TITLE
imiwa? (Japanese dictionary)

### ISSUE THREAD

**Issue by Cflo** [glasklart/hd#1436]
**App Name:** imiwa? (Japanese dictionary)
**Bundle ID:** net.pierrephi.kotoba
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288499125">288499125</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/imiwa-japanese-dictionary/id288499125?mt=8&uo=4">https://itunes.apple.com/us/app/imiwa-japanese-dictionary/id288499125?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** Pierre-Philipp di Costanzo
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pierre-phi-di-costanzo/id288499128?uo=4">© Pierre-Phi di Costanzo</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/31/f5/55/31f5554e-109c-4d6f-d2bc-5382f2203fb5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19961445/fa192dbe-a1b2-11e6-96f9-be43f848d465.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19961445/fa192dbe-a1b2-11e6-96f9-be43f848d465.png)
https://cloud.githubusercontent.com/assets/20930745/19961445/fa192dbe-a1b2-11e6-96f9-be43f848d465.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19961465/13d85ae0-a1b3-11e6-91d0-fd80503de963.png
