### ISSUE TITLE
PrintCentral for iPhone/iPod Touch

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1437]
**App Name:** PrintCentral for iPhone/iPod Touch
**Bundle ID:** com.eurosmartz.mobile.printcentraliphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=367455861">367455861</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/printcentral-for-iphone-ipod/id367455861?mt=8&uo=4">https://itunes.apple.com/us/app/printcentral-for-iphone-ipod/id367455861?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** EuroSmartz Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eurosmartz-ltd/id299105918?uo=4>© EuroSmartz Ltd</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/08/cf/ba/08cfba55-0573-2dd0-a463-90bc01d02a7f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18671208/7c0e1c68-7f43-11e6-94bf-fa45e54e4619.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18671208/7c0e1c68-7f43-11e6-94bf-fa45e54e4619.png)
https://cloud.githubusercontent.com/assets/20930745/18671208/7c0e1c68-7f43-11e6-94bf-fa45e54e4619.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18671233/94d051bc-7f43-11e6-9038-d92d7a73d0d0.png
