### ISSUE TITLE
Followers + for Instagram - Follow Management Tool for iPhone, iPad, iPod

### ISSUE THREAD

**Issue by hidii** [glasklart/hd#1441]
**App Name:** Followers + for Instagram - Follow Management Tool for iPhone, iPad, iPod
**Bundle ID:** com.tappple.ListTracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=566223681">566223681</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/followers-+-for-instagram/id566223681?mt=8&uo=4">https://itunes.apple.com/us/app/followers-+-for-instagram/id566223681?mt=8&uo=4</a>
**App Version:** 2.0.9
**Seller:** Joshua Smith
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tappple/id566223684?uo=4>© Tappple</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple22/v4/e4/f1/c8/e4f1c852-bf78-9a50-b0ec-705bb46f6a27/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19576174/47c3c066-9712-11e6-9d53-fc770497b9ab.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19576174/47c3c066-9712-11e6-9d53-fc770497b9ab.png)
https://cloud.githubusercontent.com/assets/20930745/19576174/47c3c066-9712-11e6-9d53-fc770497b9ab.png

https://cloud.githubusercontent.com/assets/20930745/19576211/66009d9c-9712-11e6-972f-5121e8d65cda.png
