### ISSUE TITLE
Breeze: Realistic wind chimes

### ISSUE THREAD

**Issue by Gokshura** [glasklart/hd#1442]
**App Name:** Breeze: Realistic wind chimes
**Bundle ID:** com.breeze-app.breeze
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427567418">427567418</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/breeze-realistic-wind-chimes/id427567418?mt=8&uo=4">https://itunes.apple.com/us/app/breeze-realistic-wind-chimes/id427567418?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** clinton downs
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/clinton-downs/id427567421?uo=4">© clinton downs</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple42/v4/fc/0b/75/fc0b7508-8516-28ce-6311-d6a4bcb5a4ad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34637195-e948893a-f2b0-11e7-9467-b80e9f8e0e4f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34637195-e948893a-f2b0-11e7-9467-b80e9f8e0e4f.png)
https://user-images.githubusercontent.com/2068130/34637195-e948893a-f2b0-11e7-9467-b80e9f8e0e4f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34637199-f91530a2-f2b0-11e7-850e-f1008a6ab534.png
