### ISSUE TITLE
Commerce Bank for iPhone

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1443]
**App Name:** Commerce Bank for iPhone
**Bundle ID:** iosapp.commercebank.com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=535981874">535981874</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/commerce-bank-for-iphone/id535981874?mt=8&uo=4">https://itunes.apple.com/us/app/commerce-bank-for-iphone/id535981874?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Commerce Bank
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/commerce-bank/id535981877?uo=4>© Commerce Bank</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/83/0f/b5/830fb590-f39e-b08b-0417-44500a4a4a91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19553955/b4231844-96b6-11e6-9343-e8faaf267bc8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19553955/b4231844-96b6-11e6-9343-e8faaf267bc8.png)
https://cloud.githubusercontent.com/assets/20930745/19553955/b4231844-96b6-11e6-9343-e8faaf267bc8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19553979/cdcb7af2-96b6-11e6-9277-44b97027ae4e.png
