### ISSUE TITLE
EasyShift

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1446]
**App Name:** EasyShift
**Bundle ID:** com.wise-view.easyshift
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=436826239">436826239</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/easyshift/id436826239?mt=8&uo=4">https://itunes.apple.com/us/app/easyshift/id436826239?mt=8&uo=4</a>
**App Version:** 6.8
**Seller:** Quri, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/quri-inc./id436826242?uo=4>© Quri, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/fa/69/0a/fa690ad0-73fa-6ac9-6fce-beb7a296bb91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19552760/83ebf47a-96b1-11e6-9cdb-64e865841b4b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19552760/83ebf47a-96b1-11e6-9cdb-64e865841b4b.png)
https://cloud.githubusercontent.com/assets/20930745/19552760/83ebf47a-96b1-11e6-9cdb-64e865841b4b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19552776/9f428bc6-96b1-11e6-8418-cd31ada06146.png
