### ISSUE TITLE
Guidebook

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1448]
**App Name:** Guidebook
**Bundle ID:** com.guidebook.guidebook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=428713847">428713847</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/guidebook/id428713847?mt=8&uo=4">https://itunes.apple.com/us/app/guidebook/id428713847?mt=8&uo=4</a>
**App Version:** 4.19.0
**Seller:** Guidebook Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/guidebook-inc/id428713850?uo=4>© Guidebook Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/80/94/9f/80949fa1-3216-1d6b-b8db-7bdde9401981/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19552974/8eb6b11e-96b2-11e6-8ca9-b75b0a13827e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19552974/8eb6b11e-96b2-11e6-8ca9-b75b0a13827e.png)
https://cloud.githubusercontent.com/assets/20930745/19552974/8eb6b11e-96b2-11e6-8ca9-b75b0a13827e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19553001/a8cb8ca0-96b2-11e6-9d16-1343b3d916c2.png
