### ISSUE TITLE
Mecenat

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#145]
**App Name:** Mecenat
**Bundle ID:** mecenat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416451110">416451110</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mecenat/id416451110?mt=8&uo=4">https://itunes.apple.com/us/app/mecenat/id416451110?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Mecenat AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mecenat-ab/id416451113?uo=4>© Mecenat AB</a>
**Supported Devices:** iPadFourthGen, iPhone5c, iPadFourthGen4G, iPadThirdGen, iPhone5, iPodTouchFifthGen, iPhone6, iPad2Wifi, iPadThirdGen4G, iPadMini4G, iPad23G, iPodTouchFourthGen, iPhone-3GS, iPhone4S, iPhone5s, iPhone4, iPhone6Plus, iPadMini
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/91/ba/07/91ba077f-6d98-428e-adfb-eccc012e29d2/mzl.clhcxbdh.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8727597/d9bf2e0e-2be0-11e5-8ea3-7358605dfb41.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8727597/d9bf2e0e-2be0-11e5-8ea3-7358605dfb41.png)
https://cloud.githubusercontent.com/assets/10730122/8727597/d9bf2e0e-2be0-11e5-8ea3-7358605dfb41.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8727595/d3c278a8-2be0-11e5-945a-3f3bdb09ea32.png
