### ISSUE TITLE
BigOven 350,000+ Recipes and Grocery List

### ISSUE THREAD

**Issue by kennatken** [glasklart/hd#1451]
**App Name:** BigOven 350,000+ Recipes and Grocery List
**Bundle ID:** com.bigoven.
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=294363034">294363034</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bigoven-350-000+-recipes-grocery/id294363034?mt=8&uo=4">https://itunes.apple.com/us/app/bigoven-350-000+-recipes-grocery/id294363034?mt=8&uo=4</a>
**App Version:** 10.6
**Seller:** Lakefront Software, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bigoven.com/id294363037?uo=4">© BigOven.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/6a/42/3c/6a423c1a-8747-379e-3698-23895b738989/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19960182/7951dc14-a1ab-11e6-93e3-266dcf9e3b33.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19960182/7951dc14-a1ab-11e6-93e3-266dcf9e3b33.png)
https://cloud.githubusercontent.com/assets/20930745/19960182/7951dc14-a1ab-11e6-93e3-266dcf9e3b33.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19960199/978f8b5e-a1ab-11e6-9e8b-666da5d9afed.png
