### ISSUE TITLE
LA Fitness Mobile

### ISSUE THREAD

**Issue by kennatken** [glasklart/hd#1452]
**App Name:** LA Fitness Mobile
**Bundle ID:** com.lafitness.lafitness
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376098999">376098999</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/la-fitness-mobile/id376098999?mt=8&uo=4">https://itunes.apple.com/us/app/la-fitness-mobile/id376098999?mt=8&uo=4</a>
**App Version:** 3.5.4
**Seller:** Fitness International, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fitness-international-llc/id376099002?uo=4">© Fitness International, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/67/a9/d5/67a9d5a4-6655-4c61-9371-c13ddd47c411/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19960545/d05229ea-a1ad-11e6-8a51-9855df1a7190.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19960545/d05229ea-a1ad-11e6-8a51-9855df1a7190.png)
https://cloud.githubusercontent.com/assets/20930745/19960545/d05229ea-a1ad-11e6-8a51-9855df1a7190.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19960560/e6b25796-a1ad-11e6-8df4-eb07badaf952.png
