### ISSUE TITLE
10K Runner: 0 to 5K to 10K Trainer, Run 10K.

### ISSUE THREAD

**Issue by kennatken** [glasklart/hd#1453]
**App Name:** 10K Runner: 0 to 5K to 10K Trainer, Run 10K.
**Bundle ID:** com.heavydutyapps.RunC210K
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=456591673">456591673</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/10k-runner-0-to-5k-to-10k/id456591673?mt=8&uo=4">https://itunes.apple.com/us/app/10k-runner-0-to-5k-to-10k/id456591673?mt=8&uo=4</a>
**App Version:** 7.3
**Seller:** FITNESS22 LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fitness22-ltd/id383171664?uo=4">© FITNESS22 LTD</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/6e/e1/a0/6ee1a027-40f3-6b19-f54a-fadd9e6bcf8e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19960426/0251fbb0-a1ad-11e6-81a1-ddc60ebe0537.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19960426/0251fbb0-a1ad-11e6-81a1-ddc60ebe0537.png)
https://cloud.githubusercontent.com/assets/20930745/19960426/0251fbb0-a1ad-11e6-81a1-ddc60ebe0537.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19960449/289a7df6-a1ad-11e6-81a8-3613d533757c.png
