### ISSUE TITLE
Harvest Time & Expense Tracker

### ISSUE THREAD

**Issue by kennatken** [glasklart/hd#1459]
**App Name:** Harvest Time & Expense Tracker
**Bundle ID:** com.getharvest.Harvest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=355395846">355395846</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/harvest-time-expense-tracker/id355395846?mt=8&uo=4">https://itunes.apple.com/us/app/harvest-time-expense-tracker/id355395846?mt=8&uo=4</a>
**App Version:** 4.4
**Seller:** Iridesco, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/harvest/id355395849?uo=4>© Harvest</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/07/79/fe/0779fe78-e433-adc4-f251-e8828ba70f6f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19552556/93d234fe-96b0-11e6-9332-41b4e52aa5f0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19552556/93d234fe-96b0-11e6-9332-41b4e52aa5f0.png)
https://cloud.githubusercontent.com/assets/20930745/19552556/93d234fe-96b0-11e6-9332-41b4e52aa5f0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19552573/ab297b62-96b0-11e6-9e9e-f643a3da5ce0.png
