### ISSUE TITLE
Aftonbladet

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#146]
**App Name:** Aftonbladet
**Bundle ID:** se.aftonbladet.Aftonbladet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284962281">284962281</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aftonbladet/id284962281?mt=8&uo=4">https://itunes.apple.com/us/app/aftonbladet/id284962281?mt=8&uo=4</a>
**App Version:** 4.1.2
**Seller:** Aftonbladet Hierta AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/aftonbladet-hierta-ab/id284962284?uo=4>© Aftonbladet Hierta AB</a>
**Supported Devices:** iPhone5, iPodTouchFifthGen, iPad2Wifi, iPadFourthGen, iPhone6, iPadThirdGen4G, iPadMini, iPhone5c, iPad23G, iPadFourthGen4G, iPhone-3GS, iPhone5s, iPhone4S, iPodTouchSixthGen, iPhone6Plus, iPodTouchFourthGen, iPadThirdGen, iPhone4, iPadMini4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/fa/4a/b5/fa4ab52e-dcbc-a885-4f14-cf0469ee60ca/mzl.mqyprzms.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8882444/3a9c87c8-3247-11e5-9a0f-624aa3b719fe.png)

**Comment by Trubbel** [comment]
@dreamnet The icon has been updated, however, the new icon cuts out the T from the icon. I have found an .svg-file and I tried to use Adobe Illustrator to upscale it, but it only comes out pixelated.
(http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/fa/4a/b5/fa4ab52e-dcbc-a885-4f14-cf0469ee60ca/mzl.mqyprzms.png)

It would look so much better if the icon just had the "AFT" centered without the T cutting out, could you give it a try?

Here's the SVG, https://upload.wikimedia.org/wikipedia/commons/0/02/Aftonbladet_wordmark.svg

**Comment by Trubbel** [comment]
This is how it looks like when I tried to upscale it, 
https://cloud.githubusercontent.com/assets/10730122/8880934/7706d872-323c-11e5-9c89-36d607645dd1.png :laughing:

**Comment by dreamnet** [comment]
@Trubbel Jup, no problem:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8882444/3a9c87c8-3247-11e5-9a0f-624aa3b719fe.png)
https://cloud.githubusercontent.com/assets/2068130/8882444/3a9c87c8-3247-11e5-9a0f-624aa3b719fe.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8882452/495e2e2e-3247-11e5-832b-eb0a40ba3d53.png

**Comment by Trubbel** [comment]
@dreamnet Thanks! :beers:

**Comment by dreamnet** [comment]
@Trubbel Well, you are right - I get myself a cold one. :beers:
