### ISSUE TITLE
Zendesk

### ISSUE THREAD

**Issue by kennatken** [glasklart/hd#1460]
**App Name:** Zendesk
**Bundle ID:** 392BDZ89DJ.Zendesk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368796007">368796007</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zendesk/id368796007?mt=8&uo=4">https://itunes.apple.com/us/app/zendesk/id368796007?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Zendesk, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/zendesk/id368796010?uo=4>© Zendesk</a>
**Supported Devices:** iPadThirdGen, iPad23G, iPhone5c, iPodTouchSixthGen, iPadFourthGen4G, iPadMini4G, iPadFourthGen, iPhone6, iPhone-3GS, iPodTouchFifthGen, iPhone4S, iPhone5s, iPhone5, iPhone4, iPadMini, iPhone6Plus, iPodTouchFourthGen, iPadThirdGen4G, iPad2Wifi
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/9e/ea/4e/9eea4efa-0572-8771-7b6f-12dda3578682/mzl.wcaixejk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8859825/11c6367c-3180-11e5-88c9-a2ee9290e83c.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8859825/11c6367c-3180-11e5-88c9-a2ee9290e83c.png)
https://cloud.githubusercontent.com/assets/10730122/8859825/11c6367c-3180-11e5-88c9-a2ee9290e83c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8859823/0e45b4aa-3180-11e5-908d-5b56db6e0bfc.png

**Comment by Trubbel** [comment]
That old icon... I have no words, haha. :smile:

**Comment by dreamnet** [comment]
Ohhhh... no more nipples.... :cry:
