### ISSUE TITLE
Head Soccer

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1465]
**App Name:** Head Soccer
**Bundle ID:** com.dnddream.headsoccer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487119327">487119327</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/head-soccer/id487119327?mt=8&uo=4">https://itunes.apple.com/us/app/head-soccer/id487119327?mt=8&uo=4</a>
**App Version:** 5.2.1
**Seller:** D&D Dream Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/d-d-dream-corp./id338533084?uo=4>© D&D Dream Corp.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/60/da/0b/60da0bd1-013b-bed0-c43f-b76a69e6bf84/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18957645/295b2e9c-8660-11e6-9ac6-b4a17d7bdc1d.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18957645/295b2e9c-8660-11e6-9ac6-b4a17d7bdc1d.png)
https://cloud.githubusercontent.com/assets/20930745/18957645/295b2e9c-8660-11e6-9ac6-b4a17d7bdc1d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18957713/667ccc90-8660-11e6-8841-f07dfd9ecc6d.png
