### ISSUE TITLE
OldBooth

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1466]
**App Name:** OldBooth
**Bundle ID:** pl.twopixels.OldBooth
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=298007500">298007500</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/oldbooth/id298007500?mt=8&uo=4">https://itunes.apple.com/us/app/oldbooth/id298007500?mt=8&uo=4</a>
**App Version:** 7.6.1
**Seller:** Piotr Bialkowski
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/getapp/id288363306?mt=8&uo=4>© GetApp</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/e6/0d/7d/e60d7d1b-e678-5293-ffd6-cc6993468216/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18603831/4b4cfef8-7c75-11e6-9edc-6129e3af8afd.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by Trubbel** [comment]
Not sure how to replicate the things on each side of the camera...

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18603487/33ff7968-7c72-11e6-835c-83d208bc2f5b.png)
https://cloud.githubusercontent.com/assets/10730122/18603487/33ff7968-7c72-11e6-835c-83d208bc2f5b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18603488/341c06be-7c72-11e6-8eb7-dee8713637e5.png

Here's the [source](https://cloud.githubusercontent.com/assets/10730122/18603497/4d2caf96-7c72-11e6-8f4d-cc7e77546040.png) if anyone else can do it.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18603831/4b4cfef8-7c75-11e6-9edc-6129e3af8afd.png)
https://cloud.githubusercontent.com/assets/2068130/18603831/4b4cfef8-7c75-11e6-9edc-6129e3af8afd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18603840/5a106ac4-7c75-11e6-87e8-163a64cf4eec.png

**Comment by Trubbel** [comment]
@dreamnet I like it. :smiley:
