### ISSUE TITLE
kicker - Fußball Transfermarkt, 1. Bundesliga und 2. Liga mit Live Ticker und Sport Ergebnissen

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1467]
**App Name:** kicker - Fußball Transfermarkt, 1. Bundesliga und 2. Liga mit Live Ticker und Sport Ergebnissen
**Bundle ID:** de.olympiaverlag.kicker.kickeronline
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=367342259">367342259</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kicker-fu-ball-transfermarkt/id367342259?mt=8&uo=4">https://itunes.apple.com/us/app/kicker-fu-ball-transfermarkt/id367342259?mt=8&uo=4</a>
**App Version:** 4.6.1
**Seller:** kicker online - Olympia Verlag GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kicker-online-olympia-verlag/id367342262?uo=4>© kicker online - Olympia Verlag GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/95/73/e8/9573e81a-2677-72bf-2fb3-abde1d5c03ff/source/1024x1024bb.jpg" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18601362/b5ad6868-7c62-11e6-9b5c-b9f5d6a35d09.png)

**Comment by Checkit23** [comment]
Updated for the new icon template:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18598292/53b275fa-7c52-11e6-9ae6-96e131e31144.png)

https://cloud.githubusercontent.com/assets/16171251/18598292/53b275fa-7c52-11e6-9ae6-96e131e31144.png

https://cloud.githubusercontent.com/assets/16171251/18598297/5e1c5a9c-7c52-11e6-85be-95a06bca3ad6.png

**Comment by dreamnet** [comment]
Keep original size:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18601362/b5ad6868-7c62-11e6-9b5c-b9f5d6a35d09.png)
https://cloud.githubusercontent.com/assets/2068130/18601362/b5ad6868-7c62-11e6-9b5c-b9f5d6a35d09.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18601403/e841d340-7c62-11e6-8679-f6c3adab5562.png
