### ISSUE TITLE
TV SPIELFILM - TV Programm mit Live TV

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1468]
**App Name:** TV SPIELFILM - TV Programm mit Live TV
**Bundle ID:** de.cellular.TVSpielfilm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=346997126">346997126</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tv-spielfilm-tv-programm-mit/id346997126?mt=8&uo=4">https://itunes.apple.com/us/app/tv-spielfilm-tv-programm-mit/id346997126?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** TV Spielfilm Verlag GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tv-spielfilm-verlag-gmbh/id494860570?uo=4>© TV Spielfilm Verlag GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/58/52/e6/5852e655-4646-b485-5f34-be7b06ff1589/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18450331/d93c6b90-7932-11e6-9205-df076f946b2f.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18450331/d93c6b90-7932-11e6-9205-df076f946b2f.png)
https://cloud.githubusercontent.com/assets/20930745/18450331/d93c6b90-7932-11e6-9205-df076f946b2f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18450346/ecb608f2-7932-11e6-9069-7e0413e0cf25.png
