### ISSUE TITLE
Toilet Finder

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#147]
**App Name:** Toilet Finder
**Bundle ID:** com.betomorrow.ToiletFinder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=311896604">311896604</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/toilet-finder/id311896604?mt=8&uo=4">https://itunes.apple.com/us/app/toilet-finder/id311896604?mt=8&uo=4</a>
**App Version:** 2.8
**Seller:** BETOMORROW
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/betomorrow/id303956224?uo=4">© BETOMORROW</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/aa/d5/41/aad54192-093c-e693-c3d3-973416565f0e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20145448/7576f99a-a6a0-11e6-9166-dbc834095a8d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20145448/7576f99a-a6a0-11e6-9166-dbc834095a8d.png)
https://cloud.githubusercontent.com/assets/20930745/20145448/7576f99a-a6a0-11e6-9166-dbc834095a8d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20145477/8ce4a848-a6a0-11e6-9339-b587480c4000.png
