### ISSUE TITLE
FahrInfo Nürnberg

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1470]
**App Name:** FahrInfo Nürnberg
**Bundle ID:** de.eos-uptrade.fahrinfo.vgn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=582623425">582623425</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fahrinfo-n%C3%BCrnberg/id582623425?mt=8&uo=4">https://itunes.apple.com/us/app/fahrinfo-n%C3%BCrnberg/id582623425?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** eos.uptrade GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/eos-uptrade-gmbh/id392900580?uo=4">© eos.uptrade GmbH</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple111/v4/ff/58/a0/ff58a0c0-6848-a421-09d4-d83c6b17b8fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![de eos-uptrade fahrinfo vgn-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39442936-3d2962a2-4cb3-11e8-8660-f885363f868c.png)

**Comment by dreamnet** [comment]
![de eos-uptrade fahrinfo vgn-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39442936-3d2962a2-4cb3-11e8-8660-f885363f868c.png)
https://user-images.githubusercontent.com/2068130/39442936-3d2962a2-4cb3-11e8-8660-f885363f868c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39442946-4e0c3c2a-4cb3-11e8-9a12-6d85272deece.png
