### ISSUE TITLE
simyo - Die wichtigsten Mein simyo Funktionen für Kunden in einer App

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1471]
**App Name:** simyo - Die wichtigsten Mein simyo Funktionen für Kunden in einer App
**Bundle ID:** de.simyo.app.ios.meinsimyo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=408883640">408883640</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/simyo-die-wichtigsten-mein/id408883640?mt=8&uo=4">https://itunes.apple.com/de/app/simyo-die-wichtigsten-mein/id408883640?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Telefonica Germany GmbH & Co. OHG
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/telefonica-germany-gmbh-co./id371338352?uo=4>© Telefonica Germany GmbH & Co. OHG</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/d6/a0/3e/d6a03efa-a01d-9ef6-9d2d-9bc39b82d286/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19552203/2afc1f72-96af-11e6-86e1-8e353d04edc0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19552203/2afc1f72-96af-11e6-86e1-8e353d04edc0.png)
https://cloud.githubusercontent.com/assets/20930745/19552203/2afc1f72-96af-11e6-86e1-8e353d04edc0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19552230/423ca3aa-96af-11e6-8b5b-e2f9c0ba2324.png
