### ISSUE TITLE
Whitagram

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#1478]
**App Name:** Whitagram
**Bundle ID:** com.undefinedunit.whitagram
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=523481129">523481129</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/whitagram/id523481129?mt=8&uo=4">https://itunes.apple.com/us/app/whitagram/id523481129?mt=8&uo=4</a>
**App Version:** 3.6.1
**Seller:** Sangmook Lee
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sangmook-lee/id979959391?uo=4>© Sangmook Lee</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/ea/13/a9/ea13a9cb-2d8a-444c-fd93-6380c1e456a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19761103/ce4abf32-9c34-11e6-831a-b58f0352d4b2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19761103/ce4abf32-9c34-11e6-831a-b58f0352d4b2.png)
https://cloud.githubusercontent.com/assets/2068130/19761103/ce4abf32-9c34-11e6-831a-b58f0352d4b2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19761122/de4e207c-9c34-11e6-883b-7008efdc782c.png
