### ISSUE TITLE
Departement

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#148]
**App Name:** Departement
**Bundle ID:** com.dpc.interactive.Departement
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=293000627">293000627</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/departement/id293000627?mt=8&uo=4">https://itunes.apple.com/us/app/departement/id293000627?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Luc Plancon
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dpc-interactive/id292186422?uo=4">© DPC Interactive</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/ce/e2/d1/cee2d108-05bf-b76b-dc83-928c93821895/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33799291-dfc0968e-dd28-11e7-847e-6e50af710d5b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33799291-dfc0968e-dd28-11e7-847e-6e50af710d5b.png)
https://user-images.githubusercontent.com/2068130/33799291-dfc0968e-dd28-11e7-847e-6e50af710d5b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33799295-f1c6d636-dd28-11e7-85d1-7696c5b1efde.png
