### ISSUE TITLE
FML Official

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#1481]
**App Name:** FML Official
**Bundle ID:** fr.alkeo.fmylife.3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=585213935">585213935</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fml-official/id585213935?mt=8&uo=4">https://itunes.apple.com/us/app/fml-official/id585213935?mt=8&uo=4</a>
**App Version:** 3.9.4
**Seller:** Ouiche Lorraine
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ouiche-lorraine/id585213938?uo=4>© Ouiche lorraine</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/99/4b/62/994b6218-1827-a75f-a4e3-3f69117c919b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19551792/44e25660-96ad-11e6-9460-157c3b10c385.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19551792/44e25660-96ad-11e6-9460-157c3b10c385.png)
https://cloud.githubusercontent.com/assets/20930745/19551792/44e25660-96ad-11e6-9460-157c3b10c385.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19551845/80697aa6-96ad-11e6-9d99-8c8e9a1e6ee9.png
