### ISSUE TITLE
Musixmatch Lyrics Finder

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#1482]
**App Name:** Musixmatch Lyrics Finder
**Bundle ID:** com.musixmatch.lyrics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448278467">448278467</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/musixmatch-lyrics-finder/id448278467?mt=8&uo=4">https://itunes.apple.com/us/app/musixmatch-lyrics-finder/id448278467?mt=8&uo=4</a>
**App Version:** 5.0.4
**Seller:** musiXmatch srl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/musixmatch-srl/id448278470?uo=4>© musiXmatch srl</a>
**Supported Devices:** iPadThirdGen, iPhone6, iPad23G, iPodTouchFifthGen, iPad2Wifi, iPadMini4G, iPhone4S, iPhone5, iPhone5s, iPadFourthGen, iPodTouchSixthGen, iPhone4, iPadFourthGen4G, iPhone5c, iPadThirdGen4G, iPadMini, iPhone6Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/b9/ec/ed/b9eceda1-ffe7-ebd0-3ff9-00b4d508f0b1/mzl.ubtowmew.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8893006/7036f6da-337c-11e5-87a0-9405b1138bf8.png)

**Comment by l8er4now** [comment]
Can we get an updated icon?

**App Name:** Musixmatch Lyrics Finder
**Bundle ID:** com.musixmatch.lyrics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448278467">448278467</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/musixmatch-lyrics-finder/id448278467?mt=8&uo=4">https://itunes.apple.com/us/app/musixmatch-lyrics-finder/id448278467?mt=8&uo=4</a>
**App Version:** 5.0.4
**Seller:** musiXmatch srl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/musixmatch-srl/id448278470?uo=4>© musiXmatch srl</a>
**Supported Devices:** iPodTouchSixthGen, iPhone4S, iPadFourthGen, iPhone6, iPadFourthGen4G, iPhone5, iPadThirdGen, iPhone5s, iPodTouchFifthGen, iPad23G, iPad2Wifi, iPhone6Plus, iPhone4, iPhone5c, iPadMini, iPadMini4G, iPadThirdGen4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/b9/ec/ed/b9eceda1-ffe7-ebd0-3ff9-00b4d508f0b1/mzl.ubtowmew.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8893006/7036f6da-337c-11e5-87a0-9405b1138bf8.png)
https://cloud.githubusercontent.com/assets/2068130/8893006/7036f6da-337c-11e5-87a0-9405b1138bf8.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8893010/81efd144-337c-11e5-9433-edf597c29e38.png
