### ISSUE TITLE
MetroLyrics

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#1483]
**App Name:** MetroLyrics
**Bundle ID:** com.metrolyrics.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547825550">547825550</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/metrolyrics/id547825550?mt=8&uo=4">https://itunes.apple.com/us/app/metrolyrics/id547825550?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** CBS Mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cbs-interactive/id295669712?mt=8&uo=4>© CBS Interactive</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/43/93/a1/4393a13b-62fd-aa1b-af0e-95de331ca94f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19760851/dec36400-9c33-11e6-8525-e8701bb60399.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19760851/dec36400-9c33-11e6-8525-e8701bb60399.png)
https://cloud.githubusercontent.com/assets/2068130/19760851/dec36400-9c33-11e6-8525-e8701bb60399.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19760865/ed0229f2-9c33-11e6-8cc0-f514f35a43ba.png
