### ISSUE TITLE
RL Classic

### ISSUE THREAD

**Issue by BTG2013** [glasklart/hd#1485]
**App Name:** RL Classic
**Bundle ID:** com.occipital.RedLaser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=312720263">312720263</a>
**iTunes URL:** https://itunes.apple.com/us/app/rl-classic/id312720263?mt=8&uo=4
**App Version:** 2.9.10
**Seller:** Occipital, LLC
**Supported Devices:** iPhone-3GS, iPodTouchourthGen, iPhone4, iPad23G, iPhone-3G, iPad2Wifi, iPhone
**Original Artwork:**
<img src="http://a1544.phobos.apple.com/us/r1000/098/Purple/v4/e7/26/38/e7263881-d02e-6fb2-04a1-e726efaaf125/mzl.ejcgdhci.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18955141/5ab9d1d2-8656-11e6-9fef-748fa241a0e7.png)

**Comment by illinikev** [comment]
update needed

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18955141/5ab9d1d2-8656-11e6-9fef-748fa241a0e7.png)
https://cloud.githubusercontent.com/assets/20930745/18955141/5ab9d1d2-8656-11e6-9fef-748fa241a0e7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18955152/68c065c0-8656-11e6-8c98-07a6787d436f.png
