### ISSUE TITLE
Great Clips Online Check-in

### ISSUE THREAD

**Issue by BTG2013** [glasklart/hd#1489]
**App Name:** Great Clips Online Check-in
**Bundle ID:** com.greatclips.greatclipsapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=414012602">414012602</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/great-clips-online-check-in/id414012602?mt=8&uo=4">https://itunes.apple.com/us/app/great-clips-online-check-in/id414012602?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** Great Clips
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/great-clips/id414012605?uo=4>© Great Clips</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/46/db/af/46dbaf25-ff88-a57a-7e5f-7f8bb27abd0a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19551503/c3eea23a-96ab-11e6-9f0a-9793bbf1e34d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19551503/c3eea23a-96ab-11e6-9f0a-9793bbf1e34d.png)
https://cloud.githubusercontent.com/assets/20930745/19551503/c3eea23a-96ab-11e6-9f0a-9793bbf1e34d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19551538/e7f8543c-96ab-11e6-8183-23fe54608b9f.png
