### ISSUE TITLE
Yr.no

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#149]
**App Name:** Yr.no
**Bundle ID:** no.nrk.yr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490989206">490989206</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yr.no/id490989206?mt=8&uo=4">https://itunes.apple.com/us/app/yr.no/id490989206?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Norsk Rikskringkasting As
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nrk/id385114901?uo=4>© NRK</a>
**Supported Devices:** iPadMini4G, iPhone6, iPodTouchFifthGen, iPhone5, iPadFourthGen, iPad23G, iPadMini, iPhone5c, iPhone5s, iPadThirdGen4G, iPadFourthGen4G, iPhone4, iPadThirdGen, iPad2Wifi, iPhone4S, iPhone6Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/cf/68/0d/cf680dd6-4eec-cd2b-91c7-3bb695562081/mzl.vmcdechc.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8655591/6675d6fa-2992-11e5-8b16-9ebae0b8bc0c.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8655569/4efddf9a-2992-11e5-8a9f-b404428cb2d5.png)
https://cloud.githubusercontent.com/assets/10730122/8655569/4efddf9a-2992-11e5-8a9f-b404428cb2d5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8655567/4aa8583a-2992-11e5-966c-0ba0a3f179e4.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8655591/6675d6fa-2992-11e5-8b16-9ebae0b8bc0c.png)
https://cloud.githubusercontent.com/assets/10730122/8655591/6675d6fa-2992-11e5-8b16-9ebae0b8bc0c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8655581/61c0a04a-2992-11e5-897c-fdf9a90a7250.png
