### ISSUE TITLE
Prey Anti Theft – Tracking and Find your Devices

### ISSUE THREAD

**Issue by BTG2013** [glasklart/hd#1490]
**App Name:** Prey Anti Theft – Tracking and Find your Devices
**Bundle ID:** com.prey
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=456755037">456755037</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/prey-anti-theft-tracking-find/id456755037?mt=8&uo=4">https://itunes.apple.com/us/app/prey-anti-theft-tracking-find/id456755037?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** Fork Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fork-ltd./id456755040?uo=4>© Fork Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/9c/8d/07/9c8d07be-4ceb-6989-3d8c-ac50e3dda045/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626339/b6546b4c-992f-11e6-9c0f-579c9ec249d3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626339/b6546b4c-992f-11e6-9c0f-579c9ec249d3.png)
https://cloud.githubusercontent.com/assets/20930745/19626339/b6546b4c-992f-11e6-9c0f-579c9ec249d3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626346/d231ca12-992f-11e6-928b-d75ce2a0a850.png
