### ISSUE TITLE
My Secret Folder™

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1493]
**App Name:** My Secret Folder™
**Bundle ID:** com.red.msf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489803044">489803044</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-secret-folder/id489803044?mt=8&uo=4">https://itunes.apple.com/us/app/my-secret-folder/id489803044?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Red Knight
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/red-knight-interactive/id489801654?uo=4">© Red Knight Interactive</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/c3/68/26/c36826a5-744f-0a5f-0a92-9231782e1c2e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39463098-42fc745e-4d16-11e8-81fc-b6fd39c90300.png)

**Comment by 2Qt2beStr8** [comment]
?
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39463098-42fc745e-4d16-11e8-81fc-b6fd39c90300.png)
https://user-images.githubusercontent.com/20930745/39463098-42fc745e-4d16-11e8-81fc-b6fd39c90300.png

Source:
https://user-images.githubusercontent.com/20930745/39463112-5a42dd38-4d16-11e8-9c35-5cb2124b98d4.png
