### ISSUE TITLE
Byvejret

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#1495]
**App Name:** Byvejret
**Bundle ID:** dk.woerk.dmi.byvejret
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=357576498">357576498</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/byvejret/id357576498?mt=8&uo=4">https://itunes.apple.com/us/app/byvejret/id357576498?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Woerk
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/woerk-aps/id357576501?uo=4>© Woerk ApS</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/31/5b/a8/315ba8fd-0557-932c-3fc0-5cc54aa34292/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418046/2b0d513e-93bc-11e6-9820-410867d84b86.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418046/2b0d513e-93bc-11e6-9820-410867d84b86.png)
https://cloud.githubusercontent.com/assets/20930745/19418046/2b0d513e-93bc-11e6-9820-410867d84b86.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19418053/4fad9ec2-93bc-11e6-8829-f8d33a5a5fc4.png
