### ISSUE TITLE
pxl.

### ISSUE THREAD

**Issue by ianebaldwin** [glasklart/hd#1499]
**App Name:** pxl.
**Bundle ID:** com.rainerkohlberger.pxl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=499620829">499620829</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pxl./id499620829?mt=8&uo=4">https://itunes.apple.com/us/app/pxl./id499620829?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Rainer Kohlberger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rainer-kohlberger/id364248993?uo=4>© Rainer Kohlberger</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/79/42/33/794233f3-ca1b-549f-bdb3-a1bf7cc4ccd1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18844931/c03ab6c2-841f-11e6-985e-dabda64c5af2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18844931/c03ab6c2-841f-11e6-985e-dabda64c5af2.png)
https://cloud.githubusercontent.com/assets/2068130/18844931/c03ab6c2-841f-11e6-985e-dabda64c5af2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18844938/cdc67b28-841f-11e6-9aea-96e809bf6f5b.png
