### ISSUE TITLE
Piction App

### ISSUE THREAD

**Issue by ianebaldwin** [glasklart/hd#1500]
**App Name:** Piction App
**Bundle ID:** com.awpny.Piction
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=588430226">588430226</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/piction-app/id588430226?mt=8&uo=4">https://itunes.apple.com/us/app/piction-app/id588430226?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** Ancient Wisdom Productions, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ancient-wisdom-productions/id588430309?uo=4>© Ancient Wisdom Productions, Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/47/73/7d/47737dfa-443b-ac2c-2dc5-eb995e0d0a52/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19629037/d56efdbc-996b-11e6-86ec-c45d17afa3ab.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19629037/d56efdbc-996b-11e6-86ec-c45d17afa3ab.png)
https://cloud.githubusercontent.com/assets/2068130/19629037/d56efdbc-996b-11e6-86ec-c45d17afa3ab.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19629043/e30c7d0a-996b-11e6-8a25-66f65b0f199b.png
