### ISSUE TITLE
IDG.se

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#151]
**App Name:** IDG.se
**Bundle ID:** se.idg.IDGse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=330193793">330193793</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/idg.se/id330193793?mt=8&uo=4">https://itunes.apple.com/us/app/idg.se/id330193793?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** IDG International Data Group AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/idg/id315437202?uo=4>© IDG</a>
**Supported Devices:** iPadMini4G, iPadWifi, iPhone4S, iPhone4, iPhone5, iPodTouchFifthGen, iPodTouchThirdGen, iPad23G, iPhone6Plus, iPhone5c, iPadMini, iPodTouchFourthGen, iPadThirdGen, iPhone5s, iPad2Wifi, iPadThirdGen4G, iPhone-3GS, iPad3G, iPhone6, iPadFourthGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple4/v4/5b/0c/29/5b0c29ff-08ff-df4c-8000-34c1dd095a8b/mzl.iqkutwcw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8521787/89b91510-23e7-11e5-85c9-57e0c1155f06.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8521787/89b91510-23e7-11e5-85c9-57e0c1155f06.png)
https://cloud.githubusercontent.com/assets/10730122/8521787/89b91510-23e7-11e5-85c9-57e0c1155f06.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8521783/7baca9be-23e7-11e5-92ac-fa9d66de7ec3.png
