### ISSUE TITLE
Tic Tac Toe Pro

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#1514]
**App Name:** Tic Tac Toe Pro
**Bundle ID:** com.yourcompany.TicTacPremium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=294293446">294293446</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tic-tac-toe-pro/id294293446?mt=8&uo=4">https://itunes.apple.com/us/app/tic-tac-toe-pro/id294293446?mt=8&uo=4</a>
**App Version:** 2.30
**Seller:** Optime Software LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/optime-software-llc/id289278460?uo=4>© Optime Software LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/6f/e2/d7/6fe2d71a-05c6-1f6e-aa38-fd0bc03e60db/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18528847/f4295852-7aca-11e6-81f1-2f22efeae779.png)

**Comment by Anuskuss** [comment]
Can someone remake this icon like the newly updated #270 (solid lines)?

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17198584/1da0baa0-543c-11e6-9520-8bb39fd02683.png)
https://cloud.githubusercontent.com/assets/3090247/17198584/1da0baa0-543c-11e6-9520-8bb39fd02683.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17198583/1da0cf7c-543c-11e6-8858-ff1927b690ea.png

**Comment by Anuskuss** [comment]
@ivanov007 Could you also make the grid solid? Or does it change the icon too much?

**Comment by ivanov007** [comment]
I don't think it change the icon too much, but it will take away the blackboard effect

**Comment by Anuskuss** [comment]
I'm okay with that.

**Comment by 2Qt2beStr8** [comment]
@ivanov007 why is this issue still open? is anything wrong with your icon?

**Comment by Anuskuss** [comment]
I like it :smiley:

**Comment by 2Qt2beStr8** [comment]
little correction from the boarder ;-)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18528847/f4295852-7aca-11e6-81f1-2f22efeae779.png)
https://cloud.githubusercontent.com/assets/20930745/18528847/f4295852-7aca-11e6-81f1-2f22efeae779.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18528872/0cc64e42-7acb-11e6-9e36-8d64e09392ba.png
