### ISSUE TITLE
Expedia Hotel, Flights, Car Rental & Activities

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1515]
**App Name:** Expedia Hotel, Flights, Car Rental & Activities
**Bundle ID:** com.expedia.booking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427916203">427916203</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/expedia-hotel-flights-car/id427916203?mt=8&uo=4">https://itunes.apple.com/us/app/expedia-hotel-flights-car/id427916203?mt=8&uo=4</a>
**App Version:** 6.14
**Seller:** Expedia, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/expedia-inc./id314063735?uo=4>© Expedia, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple71/v4/34/0f/70/340f70c6-7ce1-5b49-a605-bc8ca510ad8a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18226021/b524cec8-71c6-11e6-8b7d-93254d50802b.png)

**Comment by boxermansr** [comment]
Please update for new (updated) -large icons.
Thank you.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18226021/b524cec8-71c6-11e6-8b7d-93254d50802b.png)
https://cloud.githubusercontent.com/assets/3090247/18226021/b524cec8-71c6-11e6-8b7d-93254d50802b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18226020/b5249d2c-71c6-11e6-9784-4a166c27b4ad.png
