### ISSUE TITLE
Lost Cities

### ISSUE THREAD

**Issue by jaywigley** [glasklart/hd#1517]
**App Name:** Lost Cities
**Bundle ID:** de.codingmonkeys.LostCities
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465062454">465062454</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lost-cities/id465062454?mt=8&uo=4">https://itunes.apple.com/us/app/lost-cities/id465062454?mt=8&uo=4</a>
**App Version:** 1.80
**Seller:** TheCodingMonkeys
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/thecodingmonkeys/id284181889?uo=4">© TheCodingMonkeys</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple19/v4/af/71/69/af716915-d5f6-7bd1-2959-e45cb021f71e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32413822-d7a78130-c219-11e7-8ddd-87fa1d5ffee0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32413822-d7a78130-c219-11e7-8ddd-87fa1d5ffee0.png)
https://user-images.githubusercontent.com/2068130/32413822-d7a78130-c219-11e7-8ddd-87fa1d5ffee0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32413827-e738b1e6-c219-11e7-8a4b-ad6c943fac1b.png
