### ISSUE TITLE
REI – Shop Outdoor Gear

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1518]
**App Name:** REI – Shop Outdoor Gear
**Bundle ID:** com.rei.eCommerce
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404849387">404849387</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rei-shop-outdoor-gear/id404849387?mt=8&uo=4">https://itunes.apple.com/us/app/rei-shop-outdoor-gear/id404849387?mt=8&uo=4</a>
**App Version:** 4.7
**Seller:** Recreational Equipment, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/recreational-equipment-inc/id404849390?uo=4">© Recreational Equipment, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/8a/f1/56/8af156f4-b53b-750d-583f-59086256da22/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19959012/b591ab26-a1a3-11e6-8201-84d3735ff323.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19959012/b591ab26-a1a3-11e6-8201-84d3735ff323.png)
https://cloud.githubusercontent.com/assets/20930745/19959012/b591ab26-a1a3-11e6-8201-84d3735ff323.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19959018/cb03a860-a1a3-11e6-82f2-9076c8d999d4.png
