### ISSUE TITLE
GP

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#152]
**App Name:** GP
**Bundle ID:** se.gp.GP
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376990843">376990843</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gp/id376990843?mt=8&uo=4">https://itunes.apple.com/us/app/gp/id376990843?mt=8&uo=4</a>
**App Version:** 4.1.6
**Seller:** Stampen Local Media AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/stampen-local-media-ab/id376990846?uo=4>© Stampen Local Media AB</a>
**Supported Devices:** iPhone4, iPhone6, iPadMini4G, iPadMini, iPadFourthGen4G, iPhone5c, iPhone5, iPhone4S, iPadFourthGen, iPhone5s, iPad23G, iPodTouchFifthGen, iPhone6Plus, iPadThirdGen, iPadThirdGen4G, iPad2Wifi
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/1d/70/f3/1d70f351-413e-ef96-d035-6b9872bd1441/mzl.phpikabp.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8727708/72b860d0-2be1-11e5-8bb2-e6656c00044c.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8727708/72b860d0-2be1-11e5-8bb2-e6656c00044c.png)
https://cloud.githubusercontent.com/assets/10730122/8727708/72b860d0-2be1-11e5-8bb2-e6656c00044c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8727704/6f0ad710-2be1-11e5-9643-775b2925c57c.png
