### ISSUE TITLE
Chess Genius

### ISSUE THREAD

**Issue by jaywigley** [glasklart/hd#1520]
**App Name:** Chess Genius
**Bundle ID:** com.LangSoftwareLtd.ChessGenius
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=294631172">294631172</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chess-genius/id294631172?mt=8&uo=4">https://itunes.apple.com/us/app/chess-genius/id294631172?mt=8&uo=4</a>
**App Version:** 4.1.00
**Seller:** Lang Software Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lang-software-limited/id294631175?uo=4>© Lang Software Limited</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/38/7b/1b/387b1b35-5afb-6c93-af1e-1b73e483f30e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222794/c839b7a6-8e60-11e6-8591-1ef10de1a726.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222794/c839b7a6-8e60-11e6-8591-1ef10de1a726.png)
https://cloud.githubusercontent.com/assets/2068130/19222794/c839b7a6-8e60-11e6-8591-1ef10de1a726.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19222795/d6d1e2a2-8e60-11e6-9ff0-cd97fb415439.png
