### ISSUE TITLE
SpellTower

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1521]
**App Name:** SpellTower
**Bundle ID:** net.stfj.SpellTower
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476500832">476500832</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spelltower/id476500832?mt=8&uo=4">https://itunes.apple.com/us/app/spelltower/id476500832?mt=8&uo=4</a>
**App Version:** 4.0.4
**Seller:** Zach Gage
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zach-gage/id294263418?uo=4">© Zach Gage</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/75/3e/c4/753ec4a4-dd51-7415-8f27-921da01bd103/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32413967-952748d8-c21c-11e7-9946-a2b99340c525.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32413967-952748d8-c21c-11e7-9946-a2b99340c525.png)
https://user-images.githubusercontent.com/2068130/32413967-952748d8-c21c-11e7-9946-a2b99340c525.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32413970-a3d2bb1a-c21c-11e7-8a99-18b31947ca63.png
