### ISSUE TITLE
Ticketmaster－Buy, Sell Tickets

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1523]
**App Name:** Ticketmaster－Buy, Sell Tickets
**Bundle ID:** com.ticketmaster.ios.TicketmasterApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=500003565">500003565</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ticketmaster-buy-sell-tickets/id500003565?uo=4">https://apps.apple.com/us/app/ticketmaster-buy-sell-tickets/id500003565?uo=4</a>
**App Version:** 207.0
**Seller:** Ticketmaster L.L.C
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ticketmaster/id500003568?uo=4">© Ticketmaster</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/ec/87/7e/ec877e2d-27a9-2416-78a8-863fd267b8b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85190535-906d5680-b2b9-11ea-82d6-5413eca844bf.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19760527/6e5ab6ec-9c32-11e6-9102-08d03f0b4f4d.png)
https://cloud.githubusercontent.com/assets/2068130/19760527/6e5ab6ec-9c32-11e6-9102-08d03f0b4f4d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19760543/7be5d742-9c32-11e6-8110-0fe1f549168a.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Ticketmaster－Buy, Sell Tickets
**Bundle ID:** com.ticketmaster.ios.TicketmasterApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=500003565">500003565</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ticketmaster-buy-sell-tickets/id500003565?uo=4">https://apps.apple.com/us/app/ticketmaster-buy-sell-tickets/id500003565?uo=4</a>
**App Version:** 207.0
**Seller:** Ticketmaster L.L.C
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ticketmaster/id500003568?uo=4">© Ticketmaster</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/ec/87/7e/ec877e2d-27a9-2416-78a8-863fd267b8b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85190535-906d5680-b2b9-11ea-82d6-5413eca844bf.png)
https://user-images.githubusercontent.com/2068130/85190535-906d5680-b2b9-11ea-82d6-5413eca844bf.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85190544-a11dcc80-b2b9-11ea-8e85-e68cf3b7ae20.png
