### ISSUE TITLE
The North Face

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1524]
**App Name:** The North Face
**Bundle ID:** com.northface.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=522990206">522990206</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-north-face/id522990206?mt=8&uo=4">https://itunes.apple.com/us/app/the-north-face/id522990206?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** The North Face, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-north-face-inc./id297613774?uo=4">© The North Face, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/10/77/01/107701b8-db1d-fa64-7749-cbc2205f308a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19959202/3108fda8-a1a5-11e6-9e66-a35bbc25f203.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19959202/3108fda8-a1a5-11e6-9e66-a35bbc25f203.png)
https://cloud.githubusercontent.com/assets/20930745/19959202/3108fda8-a1a5-11e6-9e66-a35bbc25f203.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19959208/48c0efd2-a1a5-11e6-8cba-b66b8ad7b22a.png
