### ISSUE TITLE
Denon Audio

### ISSUE THREAD

**Issue by TheMQGuy** [glasklart/hd#1525]
**App Name:** Denon Audio
**Bundle ID:** com.dm-holdings.denon-audio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520604518">520604518</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/denon-audio/id520604518?mt=8&uo=4">https://itunes.apple.com/us/app/denon-audio/id520604518?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** D&M Holdings Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/d-m-holdings/id388608883?uo=4">© D&M Holdings</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/bd/24/f6/bd24f63b-2d18-561e-0bda-6019a1292287/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32413902-302426fa-c21b-11e7-91d3-c0283f1f2b9b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32413902-302426fa-c21b-11e7-91d3-c0283f1f2b9b.png)
https://user-images.githubusercontent.com/2068130/32413902-302426fa-c21b-11e7-91d3-c0283f1f2b9b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32413905-3e616ea8-c21b-11e7-988f-83b759509a0f.png
