### ISSUE TITLE
Banorte Movil

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1528]
**App Name:** Banorte Movil
**Bundle ID:** com.banorte.Banorte-Movil
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=374817863">374817863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/banorte-movil/id374817863?mt=8&uo=4">https://itunes.apple.com/us/app/banorte-movil/id374817863?mt=8&uo=4</a>
**App Version:** 7.2
**Seller:** Grupo Financiero Banorte, S.A.B. de C.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/grupo-financiero-banorte/id374817866?uo=4>© Grupo Financiero Banorte</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/43/a3/f0/43a3f06a-986c-94b6-c133-1906c36eb720/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18797721/80f2db0e-81cf-11e6-9124-81532161dd9d.png)

**Comment by ivanov007** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18797721/80f2db0e-81cf-11e6-9124-81532161dd9d.png)
https://cloud.githubusercontent.com/assets/2068130/18797721/80f2db0e-81cf-11e6-9124-81532161dd9d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18797734/8f523f0a-81cf-11e6-9378-0f439630cd69.png
