### ISSUE TITLE
Dalton - THE AWESOME!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1529]
**App Name:** Dalton - THE AWESOME!
**Bundle ID:** Dalton.colorbox.com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417358959">417358959</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dalton-the-awesome/id417358959?mt=8&uo=4">https://itunes.apple.com/us/app/dalton-the-awesome/id417358959?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** Color Box Software Company Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/colorbox/id346192960?uo=4">© Colorbox</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/ed/9f/46/ed9f46a0-c08c-26ca-07c9-787c55c62bba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33231996-13c98c72-d1ff-11e7-8be9-926ae7df2203.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33231996-13c98c72-d1ff-11e7-8be9-926ae7df2203.png)
https://user-images.githubusercontent.com/2068130/33231996-13c98c72-d1ff-11e7-8be9-926ae7df2203.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33231997-2291fa1e-d1ff-11e7-97ad-36241d55465e.png
