### ISSUE TITLE
tv.nu

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#153]
**App Name:** tv.nu
**Bundle ID:** se.aftonbladet.tvnu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284963557">284963557</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tv.nu/id284963557?mt=8&uo=4">https://itunes.apple.com/us/app/tv.nu/id284963557?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Aftonbladet Hierta AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/aftonbladet-hierta-ab/id284962284?uo=4>© Aftonbladet Hierta AB</a>
**Supported Devices:** iPadFourthGen4G, iPhone5c, iPad2Wifi, iPhone6, iPadMini, iPhone4S, iPhone5s, iPhone6Plus, iPodTouchFifthGen, iPhone5, iPad23G, iPadMini4G, iPadFourthGen, iPadThirdGen, iPhone4, iPadThirdGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/9f/08/2a/9f082ad4-57e7-926e-62e7-19ea28acc4e0/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8346857/e741041a-1b02-11e5-8731-03e296399fb7.png)

**Comment by Trubbel** [comment]
Icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8346857/e741041a-1b02-11e5-8731-03e296399fb7.png)
https://cloud.githubusercontent.com/assets/10730122/8346857/e741041a-1b02-11e5-8731-03e296399fb7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8346844/d8a428b0-1b02-11e5-96a8-535e0cb6510e.png
