### ISSUE TITLE
Sección Amarilla

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1531]
**App Name:** Sección Amarilla
**Bundle ID:** com.seccionamarilla.seccionamarillamexico
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=402003747">402003747</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/seccion-amarilla/id402003747?mt=8&uo=4">https://itunes.apple.com/us/app/seccion-amarilla/id402003747?mt=8&uo=4</a>
**App Version:** 4.9.3
**Seller:** Anuncios en Directorios, S.A. de C.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/anuncios-en-directorios-s.a./id402003750?uo=4">© Anuncios en Directorios, S.A. de C.V.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/7e/4a/65/7e4a653b-8b88-cac8-bebb-38017bbe4822/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20146218/480aaada-a6a3-11e6-9e4e-83b894b1964c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20146218/480aaada-a6a3-11e6-9e4e-83b894b1964c.png)
https://cloud.githubusercontent.com/assets/20930745/20146218/480aaada-a6a3-11e6-9e4e-83b894b1964c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20146239/60c78e9e-a6a3-11e6-85f9-ab397b01a859.png
