### ISSUE TITLE
TonePrint

### ISSUE THREAD

**Issue by veetoe** [glasklart/hd#1532]
**App Name:** TonePrint
**Bundle ID:** com.tcelectronic.toneprint
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432767616">432767616</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/toneprint/id432767616?mt=8&uo=4">https://itunes.apple.com/us/app/toneprint/id432767616?mt=8&uo=4</a>
**App Version:** 3.1.01
**Seller:** TC Electronic A/S
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tc-electronic/id364009206?uo=4">© TC Electronic</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/a9/bf/69/a9bf696f-ff67-e4da-a919-60b59508508a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19959925/230dc72e-a1aa-11e6-85ba-90c03bc40d86.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19959925/230dc72e-a1aa-11e6-85ba-90c03bc40d86.png)
https://cloud.githubusercontent.com/assets/20930745/19959925/230dc72e-a1aa-11e6-85ba-90c03bc40d86.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19959943/373fdcfa-a1aa-11e6-9389-51d8a82e3c31.png
