### ISSUE TITLE
TouchBanking

### ISSUE THREAD

**Issue by veetoe** [glasklart/hd#1533]
**App Name:** TouchBanking
**Bundle ID:** com.fiserv.touchbankingasp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386678211">386678211</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touchbanking/id386678211?mt=8&uo=4">https://itunes.apple.com/us/app/touchbanking/id386678211?mt=8&uo=4</a>
**App Version:** 17.3.173
**Seller:** Fiserv, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fiserv-inc/id386678214?uo=4">© Fiserv, Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/a0/b5/12/a0b5121f-e0ed-26a8-9470-fdca8fbbecc7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39397917-08ee0b58-4b07-11e8-8a59-4162c3da5da0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39397917-08ee0b58-4b07-11e8-8a59-4162c3da5da0.png)
https://user-images.githubusercontent.com/20930745/39397917-08ee0b58-4b07-11e8-8a59-4162c3da5da0.png

Source:
https://user-images.githubusercontent.com/20930745/39397922-1a25d478-4b07-11e8-8ab7-e7691007aa06.png
