### ISSUE TITLE
Snapseed

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#1534]
**App Name:** Snapseed
**Bundle ID:** com.niksoftware.snapseedforipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=439438619">439438619</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snapseed/id439438619?mt=8&uo=4">https://itunes.apple.com/us/app/snapseed/id439438619?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/01/cf/6b/01cf6bfc-e19f-715c-fa46-7fbfc6a25121/mzl.zwehvnqe.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10271145/6c270e04-6acc-11e5-918b-2bbcc85ee3b9.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10271145/6c270e04-6acc-11e5-918b-2bbcc85ee3b9.png)
https://cloud.githubusercontent.com/assets/3090247/10271145/6c270e04-6acc-11e5-918b-2bbcc85ee3b9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10271146/6c27effe-6acc-11e5-9f8e-b3dbce83c7f8.png
