### ISSUE TITLE
Skitch - Snap. Mark Up. Send.

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#1535]
**App Name:** Skitch - Snap. Mark Up. Send.
**Bundle ID:** com.evernote.Skitch.iPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490505997">490505997</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skitch-snap.-mark-up.-send./id490505997?mt=8&uo=4">https://itunes.apple.com/us/app/skitch-snap.-mark-up.-send./id490505997?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Evernote
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/evernote/id281796111?uo=4>© Evernote</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/7d/83/e4/7d83e432-cc86-30f1-c6aa-885c4ccc54fc/mzl.omxohvey.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10104014/b85effb0-63a7-11e5-913b-615f805251d7.png)

**Comment by Trubbel** [comment]
The icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10104014/b85effb0-63a7-11e5-913b-615f805251d7.png)
https://cloud.githubusercontent.com/assets/10730122/10104014/b85effb0-63a7-11e5-913b-615f805251d7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10104013/b433faa8-63a7-11e5-86bf-0155cdc25677.png
