### ISSUE TITLE
Launch Center Pro

### ISSUE THREAD

**Issue by bman4789** [glasklart/hd#1537]
**App Name:** Launch Center Pro
**Bundle ID:** com.appcubby.launchpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=532016360">532016360</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/launch-center-pro/id532016360?mt=8&uo=4">https://itunes.apple.com/us/app/launch-center-pro/id532016360?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** Contrast Apps LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/contrast/id286751431?uo=4>© Contrast</a>
**Supported Devices:** iPhone5c, iPadThirdGen, iPadFourthGen, iPhone5, iPadFourthGen4G, iPhone6, iPad23G, iPadMini, iPhone5s, iPhone6Plus, iPad2Wifi, iPodTouchFifthGen, iPhone4S, iPadThirdGen4G, iPadMini4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/71/3c/9e/713c9e8a-7461-5737-ded5-04f851182f44/mzl.reiudacl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8415751/5b481de8-1ea1-11e5-8541-4dce852fcc50.png)

**Comment by dreamnet** [comment]
Icon changed - new icon:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8415751/5b481de8-1ea1-11e5-8541-4dce852fcc50.png)
https://cloud.githubusercontent.com/assets/2068130/8415751/5b481de8-1ea1-11e5-8541-4dce852fcc50.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8415759/6c9c6400-1ea1-11e5-82e2-e83c91106f71.png
