### ISSUE TITLE
Lighty — The no–nonsense flashlight app

### ISSUE THREAD

**Issue by BrianMitchL** [glasklart/hd#1538]
**App Name:** Lighty — The no–nonsense flashlight app
**Bundle ID:** nl.studio-dp.Lamp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391503046">391503046</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lighty-the-no-nonsense-flashlight-app/id391503046?mt=8&uo=4">https://itunes.apple.com/us/app/lighty-the-no-nonsense-flashlight-app/id391503046?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** StudioDalton
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/studiodalton/id391503049?uo=4">© StudioDalton</a>
**Supported Devices:** iPhone4-iPhone4, iPhone4S-iPhone4S, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/6a/73/82/6a738261-ee25-91c4-04a1-3d36e1fcf8cf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688200-d300e376-c6cc-11e7-89d8-d77b494e1f33.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688200-d300e376-c6cc-11e7-89d8-d77b494e1f33.png)
https://user-images.githubusercontent.com/2068130/32688200-d300e376-c6cc-11e7-89d8-d77b494e1f33.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32688202-e202527e-c6cc-11e7-92c6-da31f42ad0fd.png
