### ISSUE TITLE
Mon Réseau

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#154]
**App Name:** Mon Réseau
**Bundle ID:** com.orange.fr.hotspots
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=286597170">286597170</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/mon-reseau/id286597170?mt=8&uo=4">https://itunes.apple.com/fr/app/mon-reseau/id286597170?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** Orange
**Developer:** <a target="_blank" href="https://itunes.apple.com/fr/developer/orange/id286449796?uo=4">© Orange</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/8c/35/22/8c35222e-d306-b93a-4026-502a692d2f3a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20145716/7060267e-a6a1-11e6-95a5-01fbe6acfe16.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20145716/7060267e-a6a1-11e6-95a5-01fbe6acfe16.png)
https://cloud.githubusercontent.com/assets/20930745/20145716/7060267e-a6a1-11e6-95a5-01fbe6acfe16.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20145765/9a955766-a6a1-11e6-96cf-1ecd326bb51f.png
