### ISSUE TITLE
Mactracker

### ISSUE THREAD

**Issue by BrianMitchL** [glasklart/hd#1540]
**App Name:** Mactracker
**Bundle ID:** ca.ianpage.Mactracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=311421597">311421597</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mactracker/id311421597?mt=8&uo=4">https://itunes.apple.com/us/app/mactracker/id311421597?mt=8&uo=4</a>
**App Version:** 4.0.5
**Seller:** Ian Page
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ian-page/id311421600?uo=4>© Ian Page</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/4d/8d/91/4d8d91de-ef1e-fc69-8c09-f1528c838348/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18748660/9d32d438-80d3-11e6-9fd0-9c081d63154d.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18748660/9d32d438-80d3-11e6-9fd0-9c081d63154d.png)
https://cloud.githubusercontent.com/assets/20930745/18748660/9d32d438-80d3-11e6-9fd0-9c081d63154d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18748678/ad6e68c6-80d3-11e6-985c-ff4420d8b867.png
