### ISSUE TITLE
Quell+

### ISSUE THREAD

**Issue by jaywigley** [glasklart/hd#1542]
**App Name:** Quell+
**Bundle ID:** com.fallentreegames.Quell
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=383027157">383027157</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quell/id383027157?mt=8&uo=4">https://itunes.apple.com/us/app/quell/id383027157?mt=8&uo=4</a>
**App Version:** 1.80
**Seller:** Fallen Tree Games Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fallen-tree-games-ltd/id383027160?uo=4">© Fallen Tree Games Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple2/v4/b0/f8/5c/b0f85cf1-c6fc-bdf4-a09a-c20690ed4aa5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38151775-f4a178b4-3464-11e8-88d5-76256c175a0e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38151775-f4a178b4-3464-11e8-88d5-76256c175a0e.png)
https://user-images.githubusercontent.com/2068130/38151775-f4a178b4-3464-11e8-88d5-76256c175a0e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38151789-042086fe-3465-11e8-9b88-0b2fc5eb24b0.png
