### ISSUE TITLE
Quell Reflect+

### ISSUE THREAD

**Issue by jaywigley** [glasklart/hd#1543]
**App Name:** Quell Reflect+
**Bundle ID:** com.fallentreegames.QuellReflect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=455533949">455533949</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quell-reflect/id455533949?mt=8&uo=4">https://itunes.apple.com/us/app/quell-reflect/id455533949?mt=8&uo=4</a>
**App Version:** 1.80
**Seller:** Fallen Tree Games Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fallen-tree-games-ltd/id383027160?uo=4">© Fallen Tree Games Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/b4/1d/20/b41d20a9-e6d1-0c71-6877-da3428672c27/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38151600-3ca52c1a-3464-11e8-9e72-a66cee3cc096.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38151600-3ca52c1a-3464-11e8-9e72-a66cee3cc096.png)
https://user-images.githubusercontent.com/2068130/38151600-3ca52c1a-3464-11e8-9e72-a66cee3cc096.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38151619-4c508a24-3464-11e8-8c1e-3f083d2dd47f.png
