### ISSUE TITLE
Quento

### ISSUE THREAD

**Issue by jaywigley** [glasklart/hd#1545]
**App Name:** Quento
**Bundle ID:** com.q42.quento
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=583954698">583954698</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quento/id583954698?mt=8&uo=4">https://itunes.apple.com/us/app/quento/id583954698?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Q42
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/q42-b.v./id385525157?uo=4">© Q42 B.V.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/59/cc/04/59cc04c3-54de-2949-3631-65b9849cba90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19958864/bb1ca9ca-a1a2-11e6-8497-c699616b90d8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19958864/bb1ca9ca-a1a2-11e6-8497-c699616b90d8.png)
https://cloud.githubusercontent.com/assets/20930745/19958864/bb1ca9ca-a1a2-11e6-8497-c699616b90d8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19958879/d258c7c2-a1a2-11e6-9146-75bd4138e4a6.png
