### ISSUE TITLE
TV Guide Australia ON AIR - EPG and program app for movies and series

### ISSUE THREAD

**Issue by bhillinger** [glasklart/hd#1547]
**App Name:** TV Guide Australia ON AIR - EPG and program app for movies and series
**Bundle ID:** stanwood.de.onair
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336137568">336137568</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/hk/app/tv-guide-australia-on-air/id336137568?mt=8&uo=4">https://itunes.apple.com/hk/app/tv-guide-australia-on-air/id336137568?mt=8&uo=4</a>
**App Version:** 6.2.6
**Seller:** stanwood GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/hk/developer/stanwood-gmbh/id321160694?uo=4>© stanwood GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple41/v4/97/ba/52/97ba5253-c336-79a2-1d6a-bdc88f75ad8d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18909784/412d1698-8575-11e6-8c59-ba74946c653f.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18881621/4e6e17e2-84dc-11e6-94a0-15c987e6af15.png)
https://cloud.githubusercontent.com/assets/20930745/18881621/4e6e17e2-84dc-11e6-94a0-15c987e6af15.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18881639/5cf29e46-84dc-11e6-8afe-1bf7a73e43df.png
