### ISSUE TITLE
Ingenious

### ISSUE THREAD

**Issue by jaywigley** [glasklart/hd#1549]
**App Name:** Ingenious
**Bundle ID:** ps.usm.ingenious
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=344523873">344523873</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ingenious/id344523873?mt=8&uo=4">https://itunes.apple.com/us/app/ingenious/id344523873?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** United Soft Media Verlag GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/usm/id330111789?uo=4">© USM</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/c6/e5/24/c6e524e4-67bd-1426-354d-51f9f6fcfcc4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20183332/3ab21bc6-a765-11e6-81c1-999535becc56.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20183332/3ab21bc6-a765-11e6-81c1-999535becc56.png)
https://cloud.githubusercontent.com/assets/20930745/20183332/3ab21bc6-a765-11e6-81c1-999535becc56.png


Source:
https://cloud.githubusercontent.com/assets/20930745/20183365/5865b646-a765-11e6-8efb-628347c4aef9.png
