### ISSUE TITLE
Trenitalia

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1552]
**App Name:** Trenitalia
**Bundle ID:** com.promptu.ProntoTreno
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=331050847">331050847</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/trenitalia/id331050847?mt=8&uo=4">https://itunes.apple.com/gb/app/trenitalia/id331050847?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** Trenitalia S.p.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/trenitalia-s.p.a./id331050850?uo=4">© Trenitalia S.p.A.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/5d/51/21/5d51210c-92f8-be59-55a3-eb5f7d7fe7e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19958465/b9efb310-a19f-11e6-9ccf-f2ca544d6bd7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19958465/b9efb310-a19f-11e6-9ccf-f2ca544d6bd7.png)
https://cloud.githubusercontent.com/assets/20930745/19958465/b9efb310-a19f-11e6-9ccf-f2ca544d6bd7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19958476/d346b728-a19f-11e6-9550-0e1947156be5.png
