### ISSUE TITLE
Destiny 2 Companion

### ISSUE THREAD

**Issue by q2r5** [glasklart/hd#1553]
**App Name:** Destiny 2 Companion
**Bundle ID:** com.bungieinc.bungie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441444902">441444902</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/destiny-2-companion/id441444902?uo=4">https://apps.apple.com/us/app/destiny-2-companion/id441444902?uo=4</a>
**App Version:** 5.7.6
**Seller:** Bungie, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bungie-inc/id441444905?uo=4">© Bungie, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/0d/22/c3/0d22c3db-3ce0-402f-59ce-971264a5de84/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382333-ed954a00-9a61-11e9-8efa-de65bc62b605.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19958545/6cfc6b2e-a1a0-11e6-87d7-052f171d280a.png)
https://cloud.githubusercontent.com/assets/20930745/19958545/6cfc6b2e-a1a0-11e6-87d7-052f171d280a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19958558/81a78572-a1a0-11e6-9f1a-edb531303dda.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382333-ed954a00-9a61-11e9-8efa-de65bc62b605.png)
https://user-images.githubusercontent.com/20930745/60382333-ed954a00-9a61-11e9-8efa-de65bc62b605.png

Source:
https://user-images.githubusercontent.com/20930745/60382335-eec67700-9a61-11e9-9ad1-7841147c607c.png
