### ISSUE TITLE
Scott Miller Salon And Spa

### ISSUE THREAD

**Issue by jaywigley** [glasklart/hd#1554]
**App Name:** Scott Miller Salon And Spa
**Bundle ID:** com.webappclouds.franks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=513554248">513554248</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scott-miller-salon-and-spa/id513554248?mt=8&uo=4">https://itunes.apple.com/us/app/scott-miller-salon-and-spa/id513554248?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Webappclouds, llc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/webappclouds-com/id492545410?uo=4">© Webappclouds.com</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/dd/3a/50/dd3a50f0-42b3-11a6-77fc-04808e17983f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32194644-43ebfe1a-bdbb-11e7-9bc7-3ae4e659a6d1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32194644-43ebfe1a-bdbb-11e7-9bc7-3ae4e659a6d1.png)
https://user-images.githubusercontent.com/2068130/32194644-43ebfe1a-bdbb-11e7-9bc7-3ae4e659a6d1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32194669-534d681c-bdbb-11e7-81a0-f85d5532511f.png
