### ISSUE TITLE
Slacker Radio

### ISSUE THREAD

**Issue by rafiks** [glasklart/hd#1556]
**App Name:** Slacker Radio
**Bundle ID:** com.slacker.radio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=298307011">298307011</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slacker-radio/id298307011?mt=8&uo=4">https://itunes.apple.com/us/app/slacker-radio/id298307011?mt=8&uo=4</a>
**App Version:** 7.4.0
**Seller:** Slacker, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/slacker-inc./id298307014?uo=4>© Slacker, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/3b/2a/43/3b2a435c-1a9a-e79e-3bb8-16f789027de6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417949/e1a47060-93b9-11e6-80da-1f2ece5d70f4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417949/e1a47060-93b9-11e6-80da-1f2ece5d70f4.png)
https://cloud.githubusercontent.com/assets/20930745/19417949/e1a47060-93b9-11e6-80da-1f2ece5d70f4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19417959/fbeae4ea-93b9-11e6-8b2b-ed3a91590bf8.png
