### ISSUE TITLE
Seamless - Free Food Delivery & Takeout Service

### ISSUE THREAD

**Issue by kanelee** [glasklart/hd#1557]
**App Name:** Seamless - Free Food Delivery & Takeout Service
**Bundle ID:** com.seamlessweb.aramarkCustomer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=381840917">381840917</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/seamless-free-food-delivery/id381840917?mt=8&uo=4">https://itunes.apple.com/us/app/seamless-free-food-delivery/id381840917?mt=8&uo=4</a>
**App Version:** 4.17
**Seller:** Seamless North America, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/seamless-north-america-llc/id381840920?uo=4">© Seamless North America, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/51/5f/a8/515fa82e-5814-17a1-0adc-5c408d4eb990/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19958655/3f4ec9f0-a1a1-11e6-9d95-af767ccdb03f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19958655/3f4ec9f0-a1a1-11e6-9d95-af767ccdb03f.png)
https://cloud.githubusercontent.com/assets/20930745/19958655/3f4ec9f0-a1a1-11e6-9d95-af767ccdb03f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19958663/57835a4a-a1a1-11e6-86c0-2cff4a2f760a.png
