### ISSUE TITLE
Real Estate by Zillow – Search Homes for Sale or Apartments for Rent

### ISSUE THREAD

**Issue by jaywigley** [glasklart/hd#1561]
**App Name:** Real Estate by Zillow – Search Homes for Sale or Apartments for Rent
**Bundle ID:** com.zillow.ZillowMap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=310738695">310738695</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/real-estate-by-zillow-search/id310738695?mt=8&uo=4">https://itunes.apple.com/us/app/real-estate-by-zillow-search/id310738695?mt=8&uo=4</a>
**App Version:** 9.8.48
**Seller:** Zillow, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zillow.com/id310738698?uo=4>© Zillow.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/70/c2/5a/70c25a09-1e20-a04f-ecdf-f1b4ff74b1a6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/16324474/6d15d8d6-397a-11e6-87ab-1d489ecb58dd.png)

**Comment by l8er4now** [comment]
Needs a bit of an update.

**App Name:** Real Estate by Zillow – Search Homes for Sale or Apartments for Rent
**Bundle ID:** com.zillow.ZillowMap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=310738695">310738695</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/real-estate-by-zillow-search/id310738695?mt=8&uo=4">https://itunes.apple.com/us/app/real-estate-by-zillow-search/id310738695?mt=8&uo=4</a>
**App Version:** 9.8.48
**Seller:** Zillow, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zillow.com/id310738698?uo=4>© Zillow.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/70/c2/5a/70c25a09-1e20-a04f-ecdf-f1b4ff74b1a6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/16324465/4c02f8ae-397a-11e6-862d-2ad31733bb0e.png)
https://cloud.githubusercontent.com/assets/3090247/16324465/4c02f8ae-397a-11e6-862d-2ad31733bb0e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/16324466/4c0768a8-397a-11e6-8f25-25b1a300d9ab.png
