### ISSUE TITLE
ING Bankieren

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1564]
**App Name:** ING Bankieren
**Bundle ID:** nl.ing.iphone.app.Bankieren
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=474495017">474495017</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ing-bankieren/id474495017?mt=8&uo=4">https://itunes.apple.com/us/app/ing-bankieren/id474495017?mt=8&uo=4</a>
**App Version:** 3.6.4
**Seller:** ING Groep NV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ing/id358382956?uo=4>© ING</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/4e/46/07/4e46071f-f85b-c976-0162-7bf305c7edfd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19230482/05c4526a-8ed5-11e6-8bda-3394b2c17eb9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19230482/05c4526a-8ed5-11e6-8bda-3394b2c17eb9.png)
https://cloud.githubusercontent.com/assets/20930745/19230482/05c4526a-8ed5-11e6-8bda-3394b2c17eb9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19230493/13c084ec-8ed5-11e6-95bb-2d2bdef44248.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19230523/488ed944-8ed5-11e6-98f1-05dcc8ba6e24.png)
https://cloud.githubusercontent.com/assets/20930745/19230523/488ed944-8ed5-11e6-98f1-05dcc8ba6e24.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19230532/55db0118-8ed5-11e6-8454-6ca6f2ab322b.png
