### ISSUE TITLE
GECU Mobile

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#1573]
**App Name:** GECU Mobile
**Bundle ID:** com.intuit.mobilebanking03500
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401072043">401072043</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gecu-mobile/id401072043?mt=8&uo=4">https://itunes.apple.com/us/app/gecu-mobile/id401072043?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** GECU
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gecu/id401072046?uo=4>© GECU</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple42/v4/01/9c/3d/019c3d1d-6b0e-4038-190a-618b1673b89a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18252469/3e137ca0-7354-11e6-8247-c17f5cab7890.png)

**Comment by boxermansr** [comment]
Please update for new (updated) -large icons.
Thank you.

**Comment by boxermansr** [comment]
Please update for new (updated) -large icons.
Thank you.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18240041/9587e86e-7349-11e6-9923-157e6dfb4c85.png)
https://cloud.githubusercontent.com/assets/20930745/18240041/9587e86e-7349-11e6-9923-157e6dfb4c85.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18240063/b1dade72-7349-11e6-8e20-c8746a77e639.png

**Comment by ivanov007** [comment]
an alternative:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18252469/3e137ca0-7354-11e6-8247-c17f5cab7890.png)
https://cloud.githubusercontent.com/assets/3090247/18252469/3e137ca0-7354-11e6-8247-c17f5cab7890.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18252468/3e119822-7354-11e6-8a8f-97b1bf2df922.png

**Comment by boxermansr** [comment]
Both are great, and much appreciated, however, to me I prefer the second one as it more matches the original with the varied colors.
