### ISSUE TITLE
Hootsuite: Schedule Posts for Twitter & Instagram

### ISSUE THREAD

**Issue by croozee** [glasklart/hd#1574]
**App Name:** Hootsuite: Schedule Posts for Twitter & Instagram
**Bundle ID:** com.hootsuite.hootsuite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=341249709">341249709</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hootsuite-schedule-posts-for/id341249709?mt=8&uo=4">https://itunes.apple.com/us/app/hootsuite-schedule-posts-for/id341249709?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Hootsuite Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hootsuite-media-inc./id341249712?uo=4>© Hootsuite Media Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/d1/aa/7d/d1aa7dfe-ef01-77e5-3a1c-2bdccb47b834/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420265/dfd7d834-93e7-11e6-9d45-c748cb0b73d5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420265/dfd7d834-93e7-11e6-9d45-c748cb0b73d5.png)
https://cloud.githubusercontent.com/assets/20930745/19420265/dfd7d834-93e7-11e6-9d45-c748cb0b73d5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19420269/f95a1510-93e7-11e6-956a-6d762f151406.png
