### ISSUE TITLE
Cell Phone Coverage Map

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#1576]
**App Name:** Cell Phone Coverage Map
**Bundle ID:** com.rootmetrics.map
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=399701910">399701910</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cell-phone-coverage-map/id399701910?uo=4">https://apps.apple.com/us/app/cell-phone-coverage-map/id399701910?uo=4</a>
**App Version:** 3.1.3
**Seller:** Root Wireless, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/rootmetrics/id399701913?uo=4">© RootMetrics</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/d7/3a/6b/d73a6b03-ff65-7e8e-10ba-72a4cc45b792/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60380678-bca91b00-9a49-11e9-8e6b-8cbb79b28cd3.png)

**Comment by boxermansr** [comment]
Please update for new (updated) -large icons. Also, the icon on this one has changed quite a bit since this one.
Thank you.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18245152/f5981868-7363-11e6-9f05-fd124578f5ca.png)
https://cloud.githubusercontent.com/assets/20930745/18245152/f5981868-7363-11e6-9f05-fd124578f5ca.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18245163/098f71c2-7364-11e6-85d6-e2cc41c07805.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Um... can you keep aspect ratio?

**Comment by 2Qt2beStr8** [comment]
@dreamnet better?

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes! :+1:

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60380678-bca91b00-9a49-11e9-8e6b-8cbb79b28cd3.png)
https://user-images.githubusercontent.com/2068130/60380678-bca91b00-9a49-11e9-8e6b-8cbb79b28cd3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60380686-ccc0fa80-9a49-11e9-9431-a8752ab4a235.png
