### ISSUE TITLE
iStroboSoft

### ISSUE THREAD

**Issue by croozee** [glasklart/hd#1581]
**App Name:** iStroboSoft
**Bundle ID:** com.peterson.iStroboSoft
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=308296029">308296029</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/istrobosoft/id308296029?mt=8&uo=4">https://itunes.apple.com/us/app/istrobosoft/id308296029?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** Peterson Strobe Tuners
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/peterson-tuners/id308296032?uo=4">© Peterson Tuners</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/20/6c/b7/206cb7c7-aac6-2349-4175-06ced57f1880/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19958220/ad014756-a19d-11e6-8961-ea61b1f43029.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19958220/ad014756-a19d-11e6-8961-ea61b1f43029.png)
https://cloud.githubusercontent.com/assets/20930745/19958220/ad014756-a19d-11e6-8961-ea61b1f43029.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19958231/c849bf16-a19d-11e6-9bb9-fac53cf72fb7.png
