### ISSUE TITLE
TiVo

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#1584]
**App Name:** TiVo
**Bundle ID:** com.tivo.quicksilver
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401673976">401673976</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tivo/id401673976?mt=8&uo=4">https://itunes.apple.com/us/app/tivo/id401673976?mt=8&uo=4</a>
**App Version:** 3.6
**Seller:** TiVo, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tivo-inc./id401673979?uo=4>© TiVo Inc.</a>
**Supported Devices:** iPadFourthGen, iPadMini4G, iPhone5, iPadFourthGen4G, iPadThirdGen, iPhone6Plus, iPad23G, iPhone5s, iPhone4, iPadThirdGen4G, iPhone4S, iPodTouchFifthGen, iPadMini, iPad2Wifi, iPhone6, iPhone5c
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/89/e0/de/89e0dee4-e505-581c-f7ca-2cc9778439cc/mzl.qzusgrbk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8674818/875383be-2a40-11e5-832c-21293f187441.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8674818/875383be-2a40-11e5-832c-21293f187441.png)
https://cloud.githubusercontent.com/assets/10730122/8674818/875383be-2a40-11e5-832c-21293f187441.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8674814/7fe84222-2a40-11e5-8c72-8cbe636cfa6b.png
