### ISSUE TITLE
Scout GPS Navigation, ETA, Maps & Traffic

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#1585]
**App Name:** Scout GPS Navigation, ETA, Maps & Traffic
**Bundle ID:** com.telenav.scout
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467816643">467816643</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scout-gps-navigation-eta-maps/id467816643?mt=8&uo=4">https://itunes.apple.com/us/app/scout-gps-navigation-eta-maps/id467816643?mt=8&uo=4</a>
**App Version:** 3.9.0
**Seller:** Telenav, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/telenav-inc./id331527274?uo=4>© Telenav, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple20/v4/e3/fc/a8/e3fca8fc-5574-90b3-0657-2a7e13207549/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193154/0cb187c2-70db-11e6-8043-0ea48ee1cab9.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** Scout GPS Navigation, ETA, Maps & Traffic
**Bundle ID:** com.telenav.scout
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467816643">467816643</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scout-gps-navigation-eta-maps/id467816643?mt=8&uo=4">https://itunes.apple.com/us/app/scout-gps-navigation-eta-maps/id467816643?mt=8&uo=4</a>
**App Version:** 3.9.0
**Seller:** Telenav, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/telenav-inc./id331527274?uo=4>© Telenav, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple20/v4/e3/fc/a8/e3fca8fc-5574-90b3-0657-2a7e13207549/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193154/0cb187c2-70db-11e6-8043-0ea48ee1cab9.png)
https://cloud.githubusercontent.com/assets/2068130/18193154/0cb187c2-70db-11e6-8043-0ea48ee1cab9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18193162/1b4de99c-70db-11e6-8b5d-7e8690d8c185.png
