### ISSUE TITLE
TonalEnergy Tuner & Metronome

### ISSUE THREAD

**Issue by croozee** [glasklart/hd#1586]
**App Name:** TonalEnergy Tuner & Metronome
**Bundle ID:** com.sonosaurus.TETuner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=497716362">497716362</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tonalenergy-tuner-metronome/id497716362?mt=8&uo=4">https://itunes.apple.com/us/app/tonalenergy-tuner-metronome/id497716362?mt=8&uo=4</a>
**App Version:** 1.5.4
**Seller:** Sonosaurus LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sonosaurus-llc/id338977569?uo=4">© Sonosaurus LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/e5/df/a8/e5dfa816-5ed4-424b-70c0-30e8c1b60d20/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468614-201ebc28-0322-11e8-9704-4707c078d0a8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468614-201ebc28-0322-11e8-9704-4707c078d0a8.png)
https://user-images.githubusercontent.com/2068130/35468614-201ebc28-0322-11e8-9704-4707c078d0a8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/35468618-2f24085e-0322-11e8-9379-1d0e14b9748d.png
