### ISSUE TITLE
Tempo - Metronome with Setlists

### ISSUE THREAD

**Issue by croozee** [glasklart/hd#1587]
**App Name:** Tempo - Metronome with Setlists
**Bundle ID:** com.frozenape.tempo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=304731501">304731501</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tempo-metronome-setlists/id304731501?mt=8&uo=4">https://itunes.apple.com/us/app/tempo-metronome-setlists/id304731501?mt=8&uo=4</a>
**App Version:** 3.8.4
**Seller:** Frozen Ape Pte. Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/frozen-ape-pte.-ltd./id304731504?uo=4">© Frozen Ape Pte. Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/46/87/7e/46877e5f-bc5a-11aa-df2e-cbd1da0d6709/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19853196/308676f6-9f68-11e6-89a0-5e3d8214e623.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19853196/308676f6-9f68-11e6-89a0-5e3d8214e623.png)
https://cloud.githubusercontent.com/assets/20930745/19853196/308676f6-9f68-11e6-89a0-5e3d8214e623.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19853219/48dd4f22-9f68-11e6-97c1-0bdfd42132ad.png
