### ISSUE TITLE
Afterlight

### ISSUE THREAD

**Issue by johnnyhundreds** [glasklart/hd#1590]
**App Name:** Afterlight
**Bundle ID:** com.simonfilip.AfterGlow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=573116090">573116090</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/afterlight/id573116090?mt=8&uo=4">https://itunes.apple.com/us/app/afterlight/id573116090?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Afterlight Collective, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/afterlight-collective-inc/id573116093?uo=4>© Afterlight Collective, Inc</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple22/v4/7f/fc/1c/7ffc1ca0-b665-0c62-8477-773ad5f235b0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18730718/10733720-8058-11e6-95b6-b23262f6ebcd.png)

**Comment by alpcinar** [comment]
Not themed after 5.0

**App Name:** Afterlight

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18730718/10733720-8058-11e6-95b6-b23262f6ebcd.png)
https://cloud.githubusercontent.com/assets/2068130/18730718/10733720-8058-11e6-95b6-b23262f6ebcd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18730728/1f03a32e-8058-11e6-9156-d60889656678.png
