### ISSUE TITLE
Codeanywhere

### ISSUE THREAD

**Issue by BenChaimberg** [glasklart/hd#1593]
**App Name:** Codeanywhere
**Bundle ID:** com.ademptio.ca
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=436736239">436736239</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/codeanywhere/id436736239?mt=8&uo=4">https://itunes.apple.com/us/app/codeanywhere/id436736239?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** Ademptio d.o.o.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ademptio-d.o.o./id436736242?uo=4">© Ademptio d.o.o.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/9f/f1/3b/9ff13b3c-37ba-9ffb-6309-940edc80f8a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19852556/55b4fb18-9f64-11e6-8126-e722bec42eef.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19852556/55b4fb18-9f64-11e6-8126-e722bec42eef.png)
https://cloud.githubusercontent.com/assets/20930745/19852556/55b4fb18-9f64-11e6-8126-e722bec42eef.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19852570/72a68c32-9f64-11e6-9aba-55f7ee9c983b.png
