### ISSUE TITLE
xkcd

### ISSUE THREAD

**Issue by BenChaimberg** [glasklart/hd#1594]
**App Name:** xkcd
**Bundle ID:** com.joshapp.xkcd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=303688284">303688284</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xkcd/id303688284?mt=8&uo=4">https://itunes.apple.com/us/app/xkcd/id303688284?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Paul Rehkugler, III
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/paul-rehkugler-iii/id913818021?uo=4>© Paul Rehkugler, III</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/9a/cb/5e/9acb5e00-77b4-ddae-cc6d-46441678c590/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417912/ff117766-93b8-11e6-89d5-0b8d6f809638.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417912/ff117766-93b8-11e6-89d5-0b8d6f809638.png)
https://cloud.githubusercontent.com/assets/20930745/19417912/ff117766-93b8-11e6-89d5-0b8d6f809638.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19417918/1d1982c6-93b9-11e6-8c58-9086d7736ee8.png
