### ISSUE TITLE
TripIt: Travel Planner

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#16]
**App Name:** TripIt: Travel Planner
**Bundle ID:** com.tripit.tripitmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=311035142">311035142</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tripit-travel-planner/id311035142?uo=4">https://apps.apple.com/us/app/tripit-travel-planner/id311035142?uo=4</a>
**App Version:** 12.2.1
**Seller:** TripIt Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tripit/id311035145?uo=4">© TripIt</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/12/72/16/127216ee-5dc5-12b9-2b38-aba2394465b0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74266572-cb0c2480-4d04-11ea-97ef-8f273cad2826.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18746020/4d9c5ede-80c5-11e6-99ad-18705b8b4347.png)
https://cloud.githubusercontent.com/assets/20930745/18746020/4d9c5ede-80c5-11e6-99ad-18705b8b4347.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18746035/5c951caa-80c5-11e6-8559-bd7dbe337af3.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74266572-cb0c2480-4d04-11ea-97ef-8f273cad2826.png)
https://user-images.githubusercontent.com/2068130/74266572-cb0c2480-4d04-11ea-97ef-8f273cad2826.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/74266612-db240400-4d04-11ea-8795-c271cdfb7009.png
