### ISSUE TITLE
Planning Center Services

### ISSUE THREAD

**Issue by techrmurphy** [glasklart/hd#1603]
**App Name:** Planning Center Services
**Bundle ID:** com.ministrycentered.PlanningCenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327370808">327370808</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/planning-center-services/id327370808?mt=8&uo=4">https://itunes.apple.com/us/app/planning-center-services/id327370808?mt=8&uo=4</a>
**App Version:** 3.3.6
**Seller:** Ministry Centered Technologies
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ministry-centered-technologies/id327370811?uo=4">© Ministry Centered Technologies</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/6d/bf/a0/6dbfa0d4-16bd-7295-d1d3-f77426ae2e7e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32990586-3b06b134-cd2c-11e7-8741-281c4fc17354.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32990586-3b06b134-cd2c-11e7-8741-281c4fc17354.png)
https://user-images.githubusercontent.com/2068130/32990586-3b06b134-cd2c-11e7-8741-281c4fc17354.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32990592-4a68d940-cd2c-11e7-92be-bd355b8163a2.png
