### ISSUE TITLE
KGW 8 News - Portland

### ISSUE THREAD

**Issue by techrmurphy** [glasklart/hd#1604]
**App Name:** KGW 8 News - Portland
**Bundle ID:** com.doapps.8c5165635f296ffa679ce03e5d00682a
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404245042">404245042</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kgw-8-news-portland/id404245042?mt=8&uo=4">https://itunes.apple.com/us/app/kgw-8-news-portland/id404245042?mt=8&uo=4</a>
**App Version:** 4.20.140021861
**Seller:** doapp, inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/doapp-inc/id284819107?uo=4">© doapp, inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/03/95/d5/0395d515-5824-54df-a882-3f451c64946d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19853994/d86ae4ca-9f6c-11e6-97ef-88f2ab6d54ad.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19853994/d86ae4ca-9f6c-11e6-97ef-88f2ab6d54ad.png)
https://cloud.githubusercontent.com/assets/20930745/19853994/d86ae4ca-9f6c-11e6-97ef-88f2ab6d54ad.png

https://cloud.githubusercontent.com/assets/20930745/19854018/f77bc9ba-9f6c-11e6-94ea-00514ee0ef65.png
