### ISSUE TITLE
Seconds - Interval Timer

### ISSUE THREAD

**Issue by kanelee** [glasklart/hd#1607]
**App Name:** Seconds - Interval Timer
**Bundle ID:** com.runloop.seconds.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=475816966">475816966</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/seconds-interval-timer/id475816966?mt=8&uo=4">https://itunes.apple.com/us/app/seconds-interval-timer/id475816966?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Runloop Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/runloop-ltd/id325563420?uo=4>© Runloop Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/50/62/9e/50629e64-be51-616a-4a75-546c1bd9e804/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418679/16d36070-93c9-11e6-881a-85bc94f9e38d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418679/16d36070-93c9-11e6-881a-85bc94f9e38d.png)
https://cloud.githubusercontent.com/assets/20930745/19418679/16d36070-93c9-11e6-881a-85bc94f9e38d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19418688/35e72a46-93c9-11e6-84ff-09f3dfc5f116.png
