### ISSUE TITLE
LiveScore

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1608]
**App Name:** LiveScore
**Bundle ID:** LiveScore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=356928178">356928178</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/livescore/id356928178?mt=8&uo=4">https://itunes.apple.com/us/app/livescore/id356928178?mt=8&uo=4</a>
**App Version:** 3.0.3
**Seller:** LiveScore Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/livescore-ltd/id356928181?uo=4">© LiveScore Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/af/bc/fc/afbcfc15-0ebb-4076-7f01-b568c1a318a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39488835-d225d7ac-4d83-11e8-9c6f-f55cd6942139.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39488835-d225d7ac-4d83-11e8-9c6f-f55cd6942139.png)
https://user-images.githubusercontent.com/2068130/39488835-d225d7ac-4d83-11e8-9c6f-f55cd6942139.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39488852-e3175cc0-4d83-11e8-9b72-cef44b1b5ec9.png
