### ISSUE TITLE
Flashlight ∎

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1610]
**App Name:** Flashlight ∎
**Bundle ID:** apptures.flashlight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404181268">404181268</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flashlight/id404181268?mt=8&uo=4">https://itunes.apple.com/us/app/flashlight/id404181268?mt=8&uo=4</a>
**App Version:** 4.4
**Seller:** Apptures Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apptures/id399549516?uo=4>© Apptures</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/e6/1b/bd/e61bbd77-4ca3-910a-3ea6-541f0d41b258/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18576187/8d56f2d6-7bdf-11e6-8649-2407f00d6252.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18576187/8d56f2d6-7bdf-11e6-8649-2407f00d6252.png)
https://cloud.githubusercontent.com/assets/2068130/18576187/8d56f2d6-7bdf-11e6-8649-2407f00d6252.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18576197/9d5dd4f6-7bdf-11e6-8a54-a4bcaeaa9fe8.png
