### ISSUE TITLE
NRJ Finland

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1611]
**App Name:** NRJ Finland
**Bundle ID:** com.liquidairlab.nrjfinland
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=340849624">340849624</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nrj-finland/id340849624?mt=8&uo=4">https://itunes.apple.com/us/app/nrj-finland/id340849624?mt=8&uo=4</a>
**App Version:** 5.1.6
**Seller:** NRJ Finland Oy Ab
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nrj-finland/id1137868211?uo=4">© NRJ Finland</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/11/35/63/11356329-a578-fb13-8007-6e62b419adad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32316873-43262034-bfb2-11e7-8b8b-da5da03850ab.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32316873-43262034-bfb2-11e7-8b8b-da5da03850ab.png)
https://user-images.githubusercontent.com/2068130/32316873-43262034-bfb2-11e7-8b8b-da5da03850ab.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32316889-54bd74f0-bfb2-11e7-88f4-d53f454c21b1.png
