### ISSUE TITLE
Posti

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1612]
**App Name:** Posti
**Bundle ID:** fi.itella.posti
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=410789057">410789057</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/posti/id410789057?mt=8&uo=4">https://itunes.apple.com/us/app/posti/id410789057?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Posti Group Oyj
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/posti-group-oyj/id410789060?uo=4>© Posti Group Oyj</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/65/49/24/654924da-bf4b-214d-af56-277f980fca00/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18799872/64e58154-81da-11e6-9e4a-c85b2dcb4149.png)

**Comment by nekholm** [comment]
Icon missing in 5.0, icon has been renewed

<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/65/49/24/654924da-bf4b-214d-af56-277f980fca00/source/1024x1024bb.png" width="180" height="180" />

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18799872/64e58154-81da-11e6-9e4a-c85b2dcb4149.png)
https://cloud.githubusercontent.com/assets/20930745/18799872/64e58154-81da-11e6-9e4a-c85b2dcb4149.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18799885/73d030f6-81da-11e6-845d-bc384b0d4f7f.png
