### ISSUE TITLE
Fonecta Caller

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1613]
**App Name:** Fonecta Caller
**Bundle ID:** fi.fonecta.fonectacaller
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=491692344">491692344</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fi/app/fonecta-caller/id491692344?mt=8&uo=4">https://itunes.apple.com/fi/app/fonecta-caller/id491692344?mt=8&uo=4</a>
**App Version:** 4.9.6
**Seller:** Fonecta Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/fi/developer/fonecta/id442932399?uo=4>© Fonecta</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/67/c1/2a/67c12acd-be0c-948b-dacf-95834d5f8337/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18797587/e36029be-81ce-11e6-8871-0f936d5cf557.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18797502/80dff4cc-81ce-11e6-9fbf-3272880420f2.png)
https://cloud.githubusercontent.com/assets/20930745/18797502/80dff4cc-81ce-11e6-9fbf-3272880420f2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18797528/9bab0486-81ce-11e6-81e8-c163068d2933.png
