### ISSUE TITLE
Nettiauto

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1614]
**App Name:** Nettiauto
**Bundle ID:** com.nettixoy.Nettiauto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=475649383">475649383</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nettiauto/id475649383?mt=8&uo=4">https://itunes.apple.com/us/app/nettiauto/id475649383?mt=8&uo=4</a>
**App Version:** 2.3.0
**Seller:** NettiX Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nettix-oy/id475649386?uo=4>© NettiX Oy</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/04/62/e0/0462e09f-f661-44a6-b92b-d8c9d2d60e38/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18800267/5d892c42-81dc-11e6-9c45-2d0aa802d811.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=
Source:

**Comment by dreamnet** [comment]
Keeping original size:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18800267/5d892c42-81dc-11e6-9c45-2d0aa802d811.png)
https://cloud.githubusercontent.com/assets/2068130/18800267/5d892c42-81dc-11e6-9c45-2d0aa802d811.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18800269/6b3c04a4-81dc-11e6-94eb-e3358b78aa4d.png
