### ISSUE TITLE
Veikkaus

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1615]
**App Name:** Veikkaus
**Bundle ID:** veikkaus.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=523567129">523567129</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fi/app/veikkaus/id523567129?mt=8&uo=4">https://itunes.apple.com/fi/app/veikkaus/id523567129?mt=8&uo=4</a>
**App Version:** 6.0.3
**Seller:** Veikkaus Oy
**Developer:** <a target="_blank" href="https://itunes.apple.com/fi/developer/veikkaus/id380465459?uo=4">© Veikkaus</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/ab/90/5a/ab905a10-3187-843e-1aca-eaa326f40e30/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21897359/a8de008c-d8e9-11e6-8fa3-f17d1bcd6312.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18797815/0c683346-81d0-11e6-98d7-767a9f27c41d.png)
https://cloud.githubusercontent.com/assets/20930745/18797815/0c683346-81d0-11e6-98d7-767a9f27c41d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18797891/4bb08062-81d0-11e6-8022-ad6064537a47.png

**Comment by nekholm** [comment]
Icon needs to be updated.

<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/07/77/fb/0777fb5f-7dda-11e3-805d-022b972146e3/source/1024x1024bb.png" width="180" height="180" />

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21897359/a8de008c-d8e9-11e6-8fa3-f17d1bcd6312.png)
https://cloud.githubusercontent.com/assets/20930745/21897359/a8de008c-d8e9-11e6-8fa3-f17d1bcd6312.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21897379/b4bed912-d8e9-11e6-94be-0fa581f4ad10.png
