### ISSUE TITLE
NHG Standaarden

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1627]
**App Name:** NHG Standaarden
**Bundle ID:** com.4net.mobile.nhgapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=531685211">531685211</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nhg-standaarden/id531685211?mt=8&uo=4">https://itunes.apple.com/us/app/nhg-standaarden/id531685211?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** Springer Media B.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bsl-onderdeel-van-springer/id550998398?uo=4">© BSL, onderdeel van Springer Media</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/ae/4a/fb/ae4afb62-cb47-590c-f0ef-f1de9cf17a58/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19859679/72804f5a-9f86-11e6-9e31-de241dfd3ddf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19859679/72804f5a-9f86-11e6-9e31-de241dfd3ddf.png)
https://cloud.githubusercontent.com/assets/20930745/19859679/72804f5a-9f86-11e6-9e31-de241dfd3ddf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19859709/8ebfe086-9f86-11e6-89ae-6676803f63f6.png
