### ISSUE TITLE
MiniKeePass - Secure Password Manager

### ISSUE THREAD

**Issue by rafiks** [glasklart/hd#1629]
[DUPLICATE of #1629]
**App Name:** MiniKeePass — Secure Password Manager
**Bundle ID:** com.jflan.MiniKeePass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=451661808">451661808</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minikeepass-secure-password/id451661808?mt=8&uo=4">https://itunes.apple.com/us/app/minikeepass-secure-password/id451661808?mt=8&uo=4</a>
**App Version:** 1.6.3
**Seller:** Flush Software, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/flush-software-llc/id450531313?uo=4>© Flush Software, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/3a/9e/c0/3a9ec0b1-d34e-7163-55f3-4e8bd800accd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17302307/e4c2639e-581b-11e6-9ca5-91b11387c0f6.png)

**Comment by dreamnet** [comment]
Needs an update.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17302307/e4c2639e-581b-11e6-9ca5-91b11387c0f6.png)
https://cloud.githubusercontent.com/assets/2068130/17302307/e4c2639e-581b-11e6-9ca5-91b11387c0f6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17302319/f4166b42-581b-11e6-93ca-c3fcaa768b98.png
