### ISSUE TITLE
MLB.com At Bat

### ISSUE THREAD

**Issue by rafiks** [glasklart/hd#1630]
**App Name:** MLB.com At Bat
**Bundle ID:** com.mlb.AtBatUniversal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493619333">493619333</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mlb.com-at-bat/id493619333?mt=8&uo=4">https://itunes.apple.com/us/app/mlb.com-at-bat/id493619333?mt=8&uo=4</a>
**App Version:** 9.5.3
**Seller:** Major League Baseball Advanced Media
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mlb.com/id281969992?uo=4">© MLB.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/89/d8/b7/89d8b790-859b-d4dc-f160-9e7ef4c0a967/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19852348/1a98777c-9f63-11e6-8565-83cbd5aed51d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19852348/1a98777c-9f63-11e6-8565-83cbd5aed51d.png)
https://cloud.githubusercontent.com/assets/20930745/19852348/1a98777c-9f63-11e6-8565-83cbd5aed51d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19852388/581354b4-9f63-11e6-827f-5646b5d9d251.png
