### ISSUE TITLE
Ichi

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#1632]
**App Name:** Ichi
**Bundle ID:** com.stolencouchgames.ichi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507985242">507985242</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ichi/id507985242?mt=8&uo=4">https://itunes.apple.com/us/app/ichi/id507985242?mt=8&uo=4</a>
**App Version:** 2.23
**Seller:** Stolen Couch Games V.O.F.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/stolen-couch-games/id507985245?uo=4">© Stolen Couch Games</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple4/v4/2b/a3/0e/2ba30e51-f2b7-45aa-e432-904c545c1ae9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25572541/6b2a9b58-2e3c-11e7-8ac3-201348b3c136.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25572541/6b2a9b58-2e3c-11e7-8ac3-201348b3c136.png)
https://cloud.githubusercontent.com/assets/2068130/25572541/6b2a9b58-2e3c-11e7-8ac3-201348b3c136.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25572545/7ab4f69a-2e3c-11e7-89f8-336df075d790.png
