### ISSUE TITLE
My Days - Period & Ovulation ™

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1634]
**App Name:** My Days - Period & Ovulation ™
**Bundle ID:** com.chris.ios.mydays
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=470179308">470179308</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-days-period-ovulation/id470179308?mt=8&uo=4">https://itunes.apple.com/us/app/my-days-period-ovulation/id470179308?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Christian Mueller
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/christian-mueller/id346546766?uo=4">© Christian Mueller</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/f6/ef/6f/f6ef6fbc-7fd6-b9a8-c962-6dd85b78c5a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19852135/d5488208-9f61-11e6-8b05-a2f2ba33ce8b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19852135/d5488208-9f61-11e6-8b05-a2f2ba33ce8b.png)
https://cloud.githubusercontent.com/assets/20930745/19852135/d5488208-9f61-11e6-8b05-a2f2ba33ce8b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19852157/f0c8e70c-9f61-11e6-8f06-42d3d9c26266.png
