### ISSUE TITLE
Keep Calm Creator

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#1636]
**App Name:** Keep Calm Creator
**Bundle ID:** com.programmingthomas.Keep-Calm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=553182846">553182846</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/keep-calm-creator/id553182846?mt=8&uo=4">https://itunes.apple.com/us/app/keep-calm-creator/id553182846?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** Thomas W Denney
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/thomas-w-denney/id553182869?uo=4>© Thomas W Denney</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/58/3f/7c/583f7c98-0115-5b8c-3569-941d005e25ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417852/4319d4b4-93b7-11e6-83cb-0a7a789494a5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417852/4319d4b4-93b7-11e6-83cb-0a7a789494a5.png)
https://cloud.githubusercontent.com/assets/20930745/19417852/4319d4b4-93b7-11e6-83cb-0a7a789494a5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19417855/5efb9d52-93b7-11e6-8eb2-31efab12ee10.png
