### ISSUE TITLE
Blot

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#1637]
**App Name:** Blot
**Bundle ID:** com.majesticsoftware.blot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479818571">479818571</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blot/id479818571?mt=8&uo=4">https://itunes.apple.com/us/app/blot/id479818571?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Majestic Software Pty Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/majestic-software/id418846465?uo=4">© Majestic Software</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/30/57/3f/30573f3f-74eb-b333-8d68-ff1c5e82e40d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19855618/d626e868-9f75-11e6-96e4-7b5927d03cdf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19855618/d626e868-9f75-11e6-96e4-7b5927d03cdf.png)
https://cloud.githubusercontent.com/assets/20930745/19855618/d626e868-9f75-11e6-96e4-7b5927d03cdf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19855641/f280419e-9f75-11e6-94d1-73b52ab39b42.png
