### ISSUE TITLE
ChefsFeed

### ISSUE THREAD

**Issue by kanelee** [glasklart/hd#1639]
**App Name:** ChefsFeed
**Bundle ID:** com.credibleinc.chefsfeed
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=466211510">466211510</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/chefsfeed/id466211510?uo=4">https://apps.apple.com/us/app/chefsfeed/id466211510?uo=4</a>
**App Version:** 4.6.17
**Seller:** Credible, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/credible-inc/id466211515?uo=4">© Credible, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/70/ee/36/70ee3687-c8d4-4104-be5c-049923e01317/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60371695-51842800-99fa-11e9-81d1-1d8e266a0144.png)

**Comment by zmathiasz** [comment]
@dreamnet 

Updated Icon:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8714556/856508ac-2b44-11e5-97ea-df3b92cfe0c5.png)
https://cloud.githubusercontent.com/assets/10950389/8714556/856508ac-2b44-11e5-97ea-df3b92cfe0c5.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8714563/90456794-2b44-11e5-8123-cd1a9538e458.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60371695-51842800-99fa-11e9-81d1-1d8e266a0144.png)
https://user-images.githubusercontent.com/20930745/60371695-51842800-99fa-11e9-81d1-1d8e266a0144.png

Source:
https://user-images.githubusercontent.com/20930745/60371700-547f1880-99fa-11e9-8a14-f95fcc468284.png
