### ISSUE TITLE
Poynt

### ISSUE THREAD

**Issue by Brazuca87** [glasklart/hd#1640]
**App Name:** Poynt
**Bundle ID:** com.multiplied.poynt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348780264">348780264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/poynt/id348780264?mt=8&uo=4">https://itunes.apple.com/us/app/poynt/id348780264?mt=8&uo=4</a>
**App Version:** 2.5.8
**Seller:** Poynt Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/poynt-corporation/id348780267?uo=4>© Poynt Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple49/v4/d3/e2/90/d3e2902b-2f8c-69b0-7d69-8e8d62ad135a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18231765/6127281a-728f-11e6-88e5-d0f23feceaaf.png)

**Comment by l8er4now** [comment]
Needs resizing and redone.

**App Name:** Poynt
**Bundle ID:** com.multiplied.poynt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348780264">348780264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/poynt/id348780264?mt=8&uo=4">https://itunes.apple.com/us/app/poynt/id348780264?mt=8&uo=4</a>
**App Version:** 2.5.8
**Seller:** Poynt Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/poynt-corporation/id348780267?uo=4>© Poynt Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple49/v4/d3/e2/90/d3e2902b-2f8c-69b0-7d69-8e8d62ad135a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18231765/6127281a-728f-11e6-88e5-d0f23feceaaf.png)

https://cloud.githubusercontent.com/assets/3704186/18231765/6127281a-728f-11e6-88e5-d0f23feceaaf.png

https://cloud.githubusercontent.com/assets/3704186/18231768/77610894-728f-11e6-95de-6526a5abed8d.png
