### ISSUE TITLE
Mixcloud - Radio & DJ mixes

### ISSUE THREAD

**Issue by kanelee** [glasklart/hd#1641]
**App Name:** Mixcloud - Radio & DJ mixes
**Bundle ID:** com.mixcloud.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401206431">401206431</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mixcloud-radio-dj-mixes/id401206431?mt=8&uo=4">https://itunes.apple.com/us/app/mixcloud-radio-dj-mixes/id401206431?mt=8&uo=4</a>
**App Version:** 9.4.3
**Seller:** Mixcloud Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mixcloud/id401206434?uo=4>© Mixcloud</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/8f/09/0b/8f090b6c-0db7-6860-86d7-6d5775a87f19/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18748351/2828868e-80d2-11e6-98b2-3d346b51bb68.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18748351/2828868e-80d2-11e6-98b2-3d346b51bb68.png)
https://cloud.githubusercontent.com/assets/20930745/18748351/2828868e-80d2-11e6-98b2-3d346b51bb68.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18748418/6633b7be-80d2-11e6-9400-2b2010cc655d.png
