### ISSUE TITLE
AMC Theaters

### ISSUE THREAD

**Issue by kanelee** [glasklart/hd#1649]
**App Name:** AMC Theatres
**Bundle ID:** com.vmbc.amc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=509199715">509199715</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amc-theatres/id509199715?mt=8&uo=4">https://itunes.apple.com/us/app/amc-theatres/id509199715?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** American Multi-Cinema, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/american-multi-cinema-inc/id396622308?uo=4">© American Multi-Cinema, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/25/4c/2e/254c2e60-dd66-0287-1aaa-a32b4392cfde/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21014929/28d55eb6-bd60-11e6-9e0b-be3e3676c485.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18618919/45aaa6cc-7dbe-11e6-8e9f-7ee6320d9b25.png)

https://cloud.githubusercontent.com/assets/3704186/18618919/45aaa6cc-7dbe-11e6-8e9f-7ee6320d9b25.png

https://cloud.githubusercontent.com/assets/3704186/18618922/4b9a0e92-7dbe-11e6-935e-3d926a04bb01.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18626965/8e8f0582-7e58-11e6-9fa1-302320574d73.png)
https://cloud.githubusercontent.com/assets/20930745/18626965/8e8f0582-7e58-11e6-9fa1-302320574d73.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18626983/a4e8ca16-7e58-11e6-8697-009d597a1d01.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** AMC Theatres
**Bundle ID:** com.vmbc.amc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=509199715">509199715</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amc-theatres/id509199715?mt=8&uo=4">https://itunes.apple.com/us/app/amc-theatres/id509199715?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** American Multi-Cinema, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/american-multi-cinema-inc/id396622308?uo=4">© American Multi-Cinema, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/25/4c/2e/254c2e60-dd66-0287-1aaa-a32b4392cfde/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21014929/28d55eb6-bd60-11e6-9e0b-be3e3676c485.png)
https://cloud.githubusercontent.com/assets/20930745/21014929/28d55eb6-bd60-11e6-9e0b-be3e3676c485.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21014939/381a8590-bd60-11e6-9a85-6c3f6d33d45a.png
