### ISSUE TITLE
Al Jazeera English

### ISSUE THREAD

**Issue by kanelee** [glasklart/hd#1650]
**App Name:** Al Jazeera English
**Bundle ID:** ajenglishiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504847776">504847776</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/al-jazeera-english/id504847776?mt=8&uo=4">https://itunes.apple.com/us/app/al-jazeera-english/id504847776?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Al Jazeera Network
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/al-jazeera-network/id415467856?uo=4>© Al Jazeera Network</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/e0/2b/e0/e02be03e-0da0-9acc-860e-3e6eca249179/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18892825/72b5567c-850b-11e6-9f26-5701069a5349.png)

**Comment by illinikev** [comment]
Icon needs update

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=#GLAS#)
https://cloud.githubusercontent.com/assets/22012363/18892825/72b5567c-850b-11e6-9f26-5701069a5349.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18892828/75263dcc-850b-11e6-9f8d-29bda36aa3ca.png
