### ISSUE TITLE
Blogger

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1653]
**App Name:** Blogger
**Bundle ID:** com.google.Blogger
**iTunes ID:** 459407288
**iTunes URL:** https://itunes.apple.com/us/app/blogger/id459407288?mt=8&uo=4
**App Version:** 2.1.7.2
**Seller:** Google, Inc.
**Supported Devices:** all
**Original Artwork:**
<img src="http://a1918.phobos.apple.com/us/r1000/106/Purple/v4/df/ba/2f/dfba2f13-d395-5495-f75f-d6cc322f66fb/mzl.ixyfsyxc.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18799296/2c674554-81d7-11e6-8e39-70dc7c4dc48a.png)

**Comment by ivanov007** [comment]
this needs update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18794322/443f87a8-81bf-11e6-8db1-49c364bd50bd.png)
https://cloud.githubusercontent.com/assets/20930745/18794322/443f87a8-81bf-11e6-8db1-49c364bd50bd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18794456/e93adfdc-81bf-11e6-950c-81be63a34409.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Why so small?
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18799296/2c674554-81d7-11e6-8e39-70dc7c4dc48a.png)
https://cloud.githubusercontent.com/assets/2068130/18799296/2c674554-81d7-11e6-8e39-70dc7c4dc48a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18799305/3abb8c78-81d7-11e6-86ee-d8f5fb08d89e.png
