### ISSUE TITLE
Pudding Monsters

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1656]
**App Name:** Pudding Monsters
**Bundle ID:** com.zeptolab.monsters
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=569185650">569185650</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pudding-monsters/id569185650?mt=8&uo=4">https://itunes.apple.com/us/app/pudding-monsters/id569185650?mt=8&uo=4</a>
**App Version:** 1.2.7
**Seller:** ZeptoLab UK Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zeptolab-uk-limited/id450542236?uo=4">© ZeptoLab UK Limited</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/28/c5/1d/28c51d0a-dda9-94b7-e26b-6cdd81256fdb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19855950/86176a1c-9f77-11e6-9b88-639241ed317a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19855950/86176a1c-9f77-11e6-9b88-639241ed317a.png)
https://cloud.githubusercontent.com/assets/20930745/19855950/86176a1c-9f77-11e6-9b88-639241ed317a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19855965/9cfb0b9e-9f77-11e6-89c1-c77ffe908966.png
