### ISSUE TITLE
Real Racing 3 [bv]

### ISSUE THREAD

**Issue by DerHimmelsreiter** [glasklart/hd#1657]
**App Name:** Real Racing 3
**Bundle ID:** com.ea.realracing3.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=556164350">556164350</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/real-racing-3/id556164350?mt=8&uo=4">https://itunes.apple.com/gb/app/real-racing-3/id556164350?mt=8&uo=4</a>
**App Version:** 4.5.2
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/electronic-arts/id284800461?mt=8&uo=4>© Electronic Arts</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/e5/13/40/e51340aa-7d88-19ae-b044-8f4e2e125e38/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18699177/dd2efed6-7fcf-11e6-86dc-68e6e79e0929.png)

**Comment by Checkit23** [comment]
Does anybody have an updated icon for the new method?

**Comment by dreamnet** [comment]
Can't do the original...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18699177/dd2efed6-7fcf-11e6-86dc-68e6e79e0929.png)
https://cloud.githubusercontent.com/assets/2068130/18699177/dd2efed6-7fcf-11e6-86dc-68e6e79e0929.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18699183/eb423b8c-7fcf-11e6-80cb-1451e6092f02.png
