### ISSUE TITLE
Voetbal International

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1658]
**App Name:** Voetbal International
**Bundle ID:** nl.vi.viwk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=371698999">371698999</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/voetbal-international/id371698999?mt=8&uo=4">https://itunes.apple.com/us/app/voetbal-international/id371698999?mt=8&uo=4</a>
**App Version:** 7.5
**Seller:** Voetbal International
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/voetbal-international/id331134619?uo=4>© Voetbal International</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/65/05/91/6505911a-3f03-f9c9-6504-9924a63b8d6d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417472/391a2882-93ae-11e6-81fb-6c9fc0cd46a6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417472/391a2882-93ae-11e6-81fb-6c9fc0cd46a6.png)
https://cloud.githubusercontent.com/assets/20930745/19417472/391a2882-93ae-11e6-81fb-6c9fc0cd46a6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19417477/5516f33a-93ae-11e6-88bf-f18f49b53207.png
