### ISSUE TITLE
Trenches II

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1659]
**App Name:** Trenches II
**Bundle ID:** com.ThunderGameWorks.Trenches2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=593658634">593658634</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trenches-ii/id593658634?mt=8&uo=4">https://itunes.apple.com/us/app/trenches-ii/id593658634?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Catapult Consulting, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/catapult-consulting-llc/id394756963?uo=4">© Catapult Consulting, LLC</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/70/b7/27/70b72799-e25d-3008-73b5-a589dc185777/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23332192/db9387dc-fb75-11e6-93c8-3329b4bac6cb.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23332192/db9387dc-fb75-11e6-93c8-3329b4bac6cb.png)
https://cloud.githubusercontent.com/assets/2068130/23332192/db9387dc-fb75-11e6-93c8-3329b4bac6cb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23332197/ed0fd1dc-fb75-11e6-9052-4e293f1d9ce2.png
