### ISSUE TITLE
Respawnables

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1660]
**App Name:** Respawnables
**Bundle ID:** com.zynga.digitallegends.respawnables
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=575684686">575684686</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/respawnables/id575684686?mt=8&uo=4">https://itunes.apple.com/us/app/respawnables/id575684686?mt=8&uo=4</a>
**App Version:** 4.5.0
**Seller:** Digital Legends Entertainment SL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/digital-legends-entertainment/id291972002?uo=4>© Digital Legends Entertainment</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/62/bd/f6/62bdf681-6fb8-3c15-84cb-c851e8355308/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19084139/93f5bc82-8a65-11e6-8f0b-946b1dd4fa9e.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19084139/93f5bc82-8a65-11e6-8f0b-946b1dd4fa9e.png)
https://cloud.githubusercontent.com/assets/20930745/19084139/93f5bc82-8a65-11e6-8f0b-946b1dd4fa9e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19084148/9f335636-8a65-11e6-875e-543b1a6d1aad.png
