### ISSUE TITLE
MobileDay One-Touch Dialer for Conference Calls & Online Meetings

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1661]
**App Name:** MobileDay One-Touch Dialer for Conference Calls & Online Meetings
**Bundle ID:** com.mobileday.MobileDay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=509842900">509842900</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobileday-one-touch-dialer/id509842900?mt=8&uo=4">https://itunes.apple.com/us/app/mobileday-one-touch-dialer/id509842900?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** MobileDay Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobileday-inc./id509842903?uo=4>© MobileDay Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/df/41/cc/df41cc43-7fd1-4e4b-e35c-1e8a7d9ee1ac/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417425/19f834c2-93ad-11e6-92c6-ed2faf3eb5c3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417425/19f834c2-93ad-11e6-92c6-ed2faf3eb5c3.png)
https://cloud.githubusercontent.com/assets/20930745/19417425/19f834c2-93ad-11e6-92c6-ed2faf3eb5c3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19417433/3dea6fee-93ad-11e6-84ca-55d6f6724bb5.png
