### ISSUE TITLE
Dictionary! by Wordset

### ISSUE THREAD

**Issue by johnnyhundreds** [glasklart/hd#1669]
**App Name:** Dictionary! by Wordset
**Bundle ID:** hamptoncatlin.dictionary
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=293283136">293283136</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dictionary!-by-wordset/id293283136?mt=8&uo=4">https://itunes.apple.com/us/app/dictionary!-by-wordset/id293283136?mt=8&uo=4</a>
**App Version:** 7.1.1
**Seller:** Wordset, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wordset/id1040641904?uo=4>© Wordset</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/9d/42/46/9d4246ae-fe84-f7af-4d45-5795ee551480/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418156/a9def8f8-93be-11e6-8760-63043bbbf7f8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418156/a9def8f8-93be-11e6-8760-63043bbbf7f8.png)
https://cloud.githubusercontent.com/assets/20930745/19418156/a9def8f8-93be-11e6-8760-63043bbbf7f8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19418162/c4df6dc2-93be-11e6-8586-65d02cd7f5f7.png
