### ISSUE TITLE
Epson iPrint

### ISSUE THREAD

**Issue by johnnyhundreds** [glasklart/hd#1670]
**App Name:** Epson iPrint
**Bundle ID:** com.epson.ESCPR01
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=326876192">326876192</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/epson-iprint/id326876192?mt=8&uo=4">https://itunes.apple.com/us/app/epson-iprint/id326876192?mt=8&uo=4</a>
**App Version:** 6.1.1
**Seller:** Seiko Epson Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/seiko-epson-corporation/id326876195?uo=4">© Seiko Epson Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/99/76/14/99761457-027f-9056-1399-a8e36b262330/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19900670/a547b872-a064-11e6-8d5c-207b9bb5e1e8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19900670/a547b872-a064-11e6-8d5c-207b9bb5e1e8.png)
https://cloud.githubusercontent.com/assets/20930745/19900670/a547b872-a064-11e6-8d5c-207b9bb5e1e8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19900695/bb3a4ece-a064-11e6-8ac8-6ab1dc800168.png
