### ISSUE TITLE
Followers For Instagram - Followers and Unfollowers Tracker

### ISSUE THREAD

**Issue by johnnyhundreds** [glasklart/hd#1671]
**App Name:** Followers For Instagram - Followers and Unfollowers Tracker
**Bundle ID:** com.noapostroph3s.followers.instagram
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=552208596">552208596</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/followers-for-instagram-followers/id552208596?mt=8&uo=4">https://itunes.apple.com/us/app/followers-for-instagram-followers/id552208596?mt=8&uo=4</a>
**App Version:** 6.3.2
**Seller:** NoApostroph3s LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/noapostroph3s-llc/id381960770?uo=4>© NoApostroph3s LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/84/2a/5a/842a5af8-bbda-8abd-a497-2723fd9beb7c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19358716/3593933a-9177-11e6-9740-a6ac78e98b40.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19358716/3593933a-9177-11e6-9740-a6ac78e98b40.png)
https://cloud.githubusercontent.com/assets/20930745/19358716/3593933a-9177-11e6-9740-a6ac78e98b40.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19358731/45f24488-9177-11e6-91a8-5ef200500b85.png
