### ISSUE TITLE
Kruidvat mobiele app

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#1674]
**App Name:** Kruidvat mobiele app
**Bundle ID:** nl.kruidvat.voordeelkaart
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=531631058">531631058</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/nl/app/kruidvat-mobiele-app/id531631058?mt=8&uo=4">https://itunes.apple.com/nl/app/kruidvat-mobiele-app/id531631058?mt=8&uo=4</a>
**App Version:** 1.4.6
**Seller:** Kruidvat Retail BV
**Developer:** <a target="_blank" href=https://itunes.apple.com/nl/developer/kruidvat-retail-bv/id531631061?uo=4>© Kruidvat Retail BV</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple42/v4/81/67/b3/8167b3c9-5726-86ed-a2aa-6c892961ce63/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419025/b02a8cd4-93cf-11e6-8dd7-a94a5a7ff11d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419025/b02a8cd4-93cf-11e6-8dd7-a94a5a7ff11d.png)
https://cloud.githubusercontent.com/assets/20930745/19419025/b02a8cd4-93cf-11e6-8dd7-a94a5a7ff11d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19419057/ca9c3018-93cf-11e6-9110-4e2acba19012.png
