### ISSUE TITLE
Horizon Go

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#1675]
**App Name:** Horizon Go
**Bundle ID:** com.upc.horizon.UPCTV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=549148968">549148968</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ie/app/horizon-go/id549148968?mt=8&uo=4">https://itunes.apple.com/ie/app/horizon-go/id549148968?mt=8&uo=4</a>
**App Version:** 2.3.9
**Seller:** Liberty Global Operations BV
**Developer:** <a target="_blank" href="https://itunes.apple.com/ie/developer/liberty-global-operations-bv/id403998620?uo=4">© Liberty Global Operations BV</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/5e/1f/fe/5e1ffe30-5575-47a4-9d37-38a105faa87e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19960802/4ab89dc6-a1af-11e6-8963-795ae1d13b97.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19960802/4ab89dc6-a1af-11e6-8963-795ae1d13b97.png)
https://cloud.githubusercontent.com/assets/20930745/19960802/4ab89dc6-a1af-11e6-8963-795ae1d13b97.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19960817/6503aca2-a1af-11e6-8950-41aa76b0a033.png
