### ISSUE TITLE
DScan for iPhone

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1677]
**App Name:** DScan for iPhone
**Bundle ID:** com.thedofl.DScan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=549855472">549855472</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dscan-for-iphone/id549855472?mt=8&uo=4">https://itunes.apple.com/us/app/dscan-for-iphone/id549855472?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Yong  Ho YUN
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yong-ho-yun/id376256040?uo=4>© Yong Ho YUN</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/0c/a4/59/0ca45921-fb95-9bad-ca91-305b6b7752aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417384/ad2073ec-93ab-11e6-90c8-47706a907de9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417384/ad2073ec-93ab-11e6-90c8-47706a907de9.png)
https://cloud.githubusercontent.com/assets/20930745/19417384/ad2073ec-93ab-11e6-90c8-47706a907de9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19417386/c4584bc0-93ab-11e6-9266-2c1f0a2cc0e0.png
