### ISSUE TITLE
dict.cc Dictionary

### ISSUE THREAD

**Issue by jerrysfiance** [glasklart/hd#1678]
**App Name:** dict.cc Dictionary
**Bundle ID:** cc.dict.dictcc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327732352">327732352</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dict.cc-dictionary/id327732352?mt=8&uo=4">https://itunes.apple.com/us/app/dict.cc-dictionary/id327732352?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** dict.cc GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dict.cc-gmbh/id327732355?uo=4>© dict.cc GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/2c/01/0b/2c010b97-12cc-0aec-8c3d-a1173eda98bc/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13266134/e0c93a56-da76-11e5-8f80-c4fda3eab310.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13266134/e0c93a56-da76-11e5-8f80-c4fda3eab310.png)
https://cloud.githubusercontent.com/assets/2068130/13266134/e0c93a56-da76-11e5-8f80-c4fda3eab310.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13266148/eefc2bb0-da76-11e5-953e-bc9b56766514.png
