### ISSUE TITLE
Kanal 5 Play

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#169]
**App Name:** Kanal 5 Play
**Bundle ID:** com.kanal5.play
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395972146">395972146</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/kanal-5-play/id395972146?mt=8&uo=4">https://itunes.apple.com/se/app/kanal-5-play/id395972146?mt=8&uo=4</a>
**App Version:** 2.3.4
**Seller:** SBS Broadcasting Networks Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/artist/sbs-broadcasting-networks/id395972149?uo=4>© SBS Broadcasting Networks Ltd</a>
**Supported Devices:** iPhone5, iPadMini4G, iPodTouchFifthGen, iPadThirdGen4G, iPadThirdGen, iPhone-3GS, iPad3G, iPhone4, iPhone5s, iPadWifi, iPodTouchThirdGen, iPadMini, iPhone6, iPad23G, iPhone4S, iPhone5c, iPad2Wifi, iPadFourthGen, iPhone6Plus, iPadFourthGen4G, iPodTouchFourthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/e1/da/ac/e1daac67-2aa5-afc3-cc92-e55e994fc227/mzl.rapeadlt.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8581613/2d639312-25c2-11e5-8e0c-673f461115c0.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8581613/2d639312-25c2-11e5-8e0c-673f461115c0.png)
https://cloud.githubusercontent.com/assets/10730122/8581613/2d639312-25c2-11e5-8e0c-673f461115c0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8581611/29dc3c30-25c2-11e5-8abb-42a7888ee22c.png
