### ISSUE TITLE
94 Seconds

### ISSUE THREAD

**Issue by MasteerG33k** [glasklart/hd#1697]
**App Name:** 94 Seconds
**Bundle ID:** com.scimob.94seconds
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=567138796">567138796</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/94-seconds/id567138796?mt=8&uo=4">https://itunes.apple.com/us/app/94-seconds/id567138796?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** SCIMOB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/scimob/id325822885?uo=4>© Scimob</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/9b/f3/1a/9bf31ade-966a-6aff-845e-4afb7a9132ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18909043/5e4f29da-8572-11e6-9a28-c3531adc3b1a.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18881373/50a3bc16-84db-11e6-8746-eedc8cb30e55.png)
https://cloud.githubusercontent.com/assets/20930745/18881373/50a3bc16-84db-11e6-8746-eedc8cb30e55.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18881335/2de918ba-84db-11e6-9285-9be7807a567f.png
