### ISSUE TITLE
Chrome - web browser by Google

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#17]
**App Name:** Chrome - web browser by Google
**Bundle ID:** com.google.chrome.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=535886823">535886823</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chrome-web-browser-by-google/id535886823?mt=8&uo=4">https://itunes.apple.com/us/app/chrome-web-browser-by-google/id535886823?mt=8&uo=4</a>
**App Version:** 43.0.2357.56
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone4S, iPodTouchFifthGen, iPadFourthGen, iPad23G, iPhone5c, iPhone5, iPadMini4G, iPhone4, iPhone5s, iPad2Wifi, iPadThirdGen, iPadThirdGen4G, iPadFourthGen4G, iPhone6Plus, iPhone6, iPadMini
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/41/95/e5/4195e546-10ff-8992-ed61-199b78b2cced/mzl.phxeaojs.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8271231/5a175eca-180c-11e5-9a0e-5b48864fb177.png)

**Comment by dreamnet** [comment]
Icon update:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8271231/5a175eca-180c-11e5-9a0e-5b48864fb177.png)
https://cloud.githubusercontent.com/assets/2068130/8271231/5a175eca-180c-11e5-9a0e-5b48864fb177.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8271232/6d8f3d10-180c-11e5-82c5-b85403b2a355.png
