### ISSUE TITLE
VDM Officiel

### ISSUE THREAD

**Issue by MasteerG33k** [glasklart/hd#1700]
**App Name:** VDM Officiel
**Bundle ID:** fr.alkeo.vdm.3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=585215254">585215254</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vdm-officiel/id585215254?mt=8&uo=4">https://itunes.apple.com/us/app/vdm-officiel/id585215254?mt=8&uo=4</a>
**App Version:** 3.9.2
**Seller:** Beta et Compagnie
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/beta-cie/id354145358?uo=4>© Beta&Cie</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/02/84/6d/02846de4-fda5-f57d-3f74-d3d483ba5eb9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419207/d3f381b8-93d2-11e6-8fd7-d4df602a5a54.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419207/d3f381b8-93d2-11e6-8fd7-d4df602a5a54.png)
https://cloud.githubusercontent.com/assets/20930745/19419207/d3f381b8-93d2-11e6-8fd7-d4df602a5a54.png)

Source:
https://cloud.githubusercontent.com/assets/20930745/19419210/e1c1c624-93d2-11e6-8158-d0447ad6bd92.png
