### ISSUE TITLE
mobile.de - mobile Auto Börse

### ISSUE THREAD

**Issue by forsterino** [glasklart/hd#1701]
**App Name:** mobile.de - mobile Auto Börse
**Bundle ID:** de.mobile.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378563358">378563358</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/mobile.de-mobile-auto-borse/id378563358?mt=8&uo=4">https://itunes.apple.com/de/app/mobile.de-mobile-auto-borse/id378563358?mt=8&uo=4</a>
**App Version:** 4.6.1
**Seller:** mobile.de GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/mobile.de-gmbh/id378563361?uo=4>© mobile.de GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/fa/ca/2b/faca2b2f-4b3a-3a9b-e236-dcbe28a7de4a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416900/235cc5b0-7822-11e6-931f-fd13ec7f1610.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416900/235cc5b0-7822-11e6-931f-fd13ec7f1610.png)
https://cloud.githubusercontent.com/assets/2068130/18416900/235cc5b0-7822-11e6-931f-fd13ec7f1610.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416903/31f753e2-7822-11e6-967f-0035265780ec.png
