### ISSUE TITLE
Zen Pinball

### ISSUE THREAD

**Issue by Gokshura** [glasklart/hd#1705]
**App Name:** Zen Pinball
**Bundle ID:** com.zenstudios.newzenpinball
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465694275">465694275</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zen-pinball/id465694275?mt=8&uo=4">https://itunes.apple.com/us/app/zen-pinball/id465694275?mt=8&uo=4</a>
**App Version:** 1.42.1
**Seller:** ZEN Studios Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zen-studios-ltd/id413501788?uo=4">© ZEN Studios Ltd.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/07/1b/5e/071b5e39-21b2-06c9-9c44-ff3424f75e1d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25074174/b97cfb40-22f5-11e7-9079-742200ef9f44.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25074174/b97cfb40-22f5-11e7-9079-742200ef9f44.png)
https://cloud.githubusercontent.com/assets/2068130/25074174/b97cfb40-22f5-11e7-9079-742200ef9f44.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25074182/cb270dcc-22f5-11e7-8b33-5fbe0c32cdbc.png
