### ISSUE TITLE
Trollolol

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1706]
**App Name:** Trollolol
**Bundle ID:** com.yomba.troll
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416325085">416325085</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trollolol/id416325085?mt=8&uo=4">https://itunes.apple.com/us/app/trollolol/id416325085?mt=8&uo=4</a>
**App Version:** 1.8.7
**Seller:** Gabor Detari
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yomba/id383059129?uo=4>© Yomba</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/88/a5/89/88a5898d-3776-8f48-58cc-78a41452eb3a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418242/61c06cf8-93c0-11e6-9816-aded7cc9dcdf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418242/61c06cf8-93c0-11e6-9816-aded7cc9dcdf.png)
https://cloud.githubusercontent.com/assets/20930745/19418242/61c06cf8-93c0-11e6-9816-aded7cc9dcdf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19418244/7fed0862-93c0-11e6-9663-4acf136eea75.png
