### ISSUE TITLE
Sveriges Radio Play

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#171]
**App Name:** Sveriges Radio Play
**Bundle ID:** se.sr.podcastspelare
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300548244">300548244</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sveriges-radio-play/id300548244?mt=8&uo=4">https://itunes.apple.com/us/app/sveriges-radio-play/id300548244?mt=8&uo=4</a>
**App Version:** 6.4
**Seller:** Sveriges Radio AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sveriges-radio/id300548247?uo=4>© Sveriges Radio</a>
**Supported Devices:** iPadFourthGen, iPad2Wifi, iPadMini, iPadFourthGen4G, iPodTouchFourthGen, iPhone6, iPhone5, iPhone4, iPhone6Plus, iPodTouchFifthGen, iPhone4S, iPhone5s, iPadThirdGen4G, iPadMini4G, iPad23G, iPhone5c, iPhone-3GS, iPadThirdGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/8b/54/b5/8b54b5b6-a2aa-2829-27f5-0f2f944bed9a/mzl.qcbxhfaa.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8727968/e649f210-2be2-11e5-9bbd-5e66620d32a6.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8727968/e649f210-2be2-11e5-9bbd-5e66620d32a6.png)
https://cloud.githubusercontent.com/assets/10730122/8727968/e649f210-2be2-11e5-9bbd-5e66620d32a6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8727965/e342ba0c-2be2-11e5-8886-557786cf482d.png
