### ISSUE TITLE
Midway Arcade

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1710]
**App Name:** Midway Arcade
**Bundle ID:** com.wb.MidwayArcade
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476467441">476467441</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/midway-arcade/id476467441?mt=8&uo=4">https://itunes.apple.com/us/app/midway-arcade/id476467441?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Warner Bros. Entertainment
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/warner-bros/id298372283?uo=4">© Warner Bros.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/f5/bc/be/f5bcbe92-cc3d-81f1-cb53-59d8d28cb613/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32171257-d551f182-bd77-11e7-80e6-b14fec9cc61c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32171257-d551f182-bd77-11e7-80e6-b14fec9cc61c.png)
https://user-images.githubusercontent.com/2068130/32171257-d551f182-bd77-11e7-80e6-b14fec9cc61c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32171281-eafe7064-bd77-11e7-8eb0-4b7aa3207d02.png
