### ISSUE TITLE
LeclercDrive

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#1712]
**App Name:** LeclercDrive
**Bundle ID:** com.infomil.leclercdrive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=387709274">387709274</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/leclercdrive/id387709274?mt=8&uo=4">https://itunes.apple.com/de/app/leclercdrive/id387709274?mt=8&uo=4</a>
**App Version:** 7.1.1
**Seller:** Infomil
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/e.leclerc-infomil/id387709277?uo=4">© E.Leclerc - Infomil</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/df/c7/b4/dfc7b490-190e-d116-39a4-79d9d85e2790/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19901396/4dbb3342-a067-11e6-8e04-40a365fccda4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19901396/4dbb3342-a067-11e6-8e04-40a365fccda4.png)
https://cloud.githubusercontent.com/assets/20930745/19901396/4dbb3342-a067-11e6-8e04-40a365fccda4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19901421/6768eae6-a067-11e6-9514-84da475ccbfe.png
