### ISSUE TITLE
Skype Wifi

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1713]
**App Name:** Skype WiFi
**Bundle ID:** com.skype.SkypeAccessWiFi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444529922">444529922</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skype-wifi/id444529922?mt=8&uo=4">https://itunes.apple.com/us/app/skype-wifi/id444529922?mt=8&uo=4</a>
**App Version:** 1.4.4
**Seller:** Skype Communications S.a.r.l
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/skype-communications-s.a.r.l/id304219585?mt=8&uo=4>© Skype Communications S.a.r.l</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/7e/53/d1/7e53d12a-e206-9d9f-40b5-76f53a7b644c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419945/ed952540-93e1-11e6-9692-e4789ed924d6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419945/ed952540-93e1-11e6-9692-e4789ed924d6.png)
https://cloud.githubusercontent.com/assets/20930745/19419945/ed952540-93e1-11e6-9692-e4789ed924d6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19419952/06e73556-93e2-11e6-9c84-f069c1babf42.png
