### ISSUE TITLE
Медитация

### ISSUE THREAD

**Issue by breathful** [glasklart/hd#1714]
**App Name:** Медитация
**Bundle ID:** oberon.meditation
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=564252410">564252410</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/meditacia/id564252410?mt=8&uo=4">https://itunes.apple.com/us/app/meditacia/id564252410?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Alexandr Demin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/oberon-prod./id564252413?uo=4>© Oberon prod.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/4f/c5/b0/4fc5b017-dd13-2780-155b-8fe46e918984/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419153/89e9b2f0-93d1-11e6-90bf-5505bda569c8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419153/89e9b2f0-93d1-11e6-90bf-5505bda569c8.png)
https://cloud.githubusercontent.com/assets/20930745/19419153/89e9b2f0-93d1-11e6-90bf-5505bda569c8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19419156/a7e1fb50-93d1-11e6-9213-ac6f95a47a14.png
