### ISSUE TITLE
Lingvo Dictionary Pack: German <-> English, French, Italian, Russian, Spanish

### ISSUE THREAD

**Issue by breathful** [glasklart/hd#1717]
**App Name:** Lingvo Dictionary Pack: German <-> English, French, Italian, Russian, Spanish
**Bundle ID:** com.abbyy.lingvomobile.pack.german1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492199881">492199881</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lingvo-dictionary-pack-german/id492199881?mt=8&uo=4">https://itunes.apple.com/us/app/lingvo-dictionary-pack-german/id492199881?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** ABBYY USA Software House Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/abbyy/id347345477?uo=4">© ABBYY</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/2b/a3/da/2ba3dac1-e1c2-39b6-3af7-9c94252f8acb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19899698/51839cea-a061-11e6-93e1-55a3bc67b85f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19899698/51839cea-a061-11e6-93e1-55a3bc67b85f.png)
https://cloud.githubusercontent.com/assets/20930745/19899698/51839cea-a061-11e6-93e1-55a3bc67b85f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19899736/7297dd74-a061-11e6-9426-6417b9e05b22.png
