### ISSUE TITLE
finanzblick - Onlinebanking

### ISSUE THREAD

**Issue by breathful** [glasklart/hd#1720]
**App Name:** finanzblick - Onlinebanking
**Bundle ID:** com.BuhlData.Finanzblick
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401912744">401912744</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/finanzblick-onlinebanking/id401912744?mt=8&uo=4">https://itunes.apple.com/us/app/finanzblick-onlinebanking/id401912744?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** Buhl Data Service GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/buhl-data-service-gmbh/id366800332?uo=4>© Buhl Data Service GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/4a/ce/8d/4ace8d1f-8e56-a40d-5622-f1cd29d0482e/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11017117/78472fb4-8595-11e5-8d71-a77544497d68.png)

**Comment by Anuskuss** [comment]
I think this icon needs to be updated.

**New Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/4a/ce/8d/4ace8d1f-8e56-a40d-5622-f1cd29d0482e/source/512x512bb.jpg" width="150" height="150" />

The first one would fit perfectly.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11016923/729f6636-858f-11e5-8bff-4c69cd27ec68.png)
https://cloud.githubusercontent.com/assets/10730122/11016923/729f6636-858f-11e5-8bff-4c69cd27ec68.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11016922/6ed2fffe-858f-11e5-8216-1abb9e6cac69.png

**Comment by Anuskuss** [comment]
Round corners maaybe?

**Comment by Trubbel** [comment]
@Anuskuss 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11017117/78472fb4-8595-11e5-8d71-a77544497d68.png)
https://cloud.githubusercontent.com/assets/10730122/11017117/78472fb4-8595-11e5-8d71-a77544497d68.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11017116/74df3826-8595-11e5-925f-9efe30a74a05.png

**Comment by Anuskuss** [comment]
Definitely second one :+1:

**Comment by ivanov007** [comment]
lol at first I thought it was a facebook app

**Comment by dreamnet** [comment]
Yeah, I'm wondering if there are any copyright problems... :laughing:
