### ISSUE TITLE
Runtastic Timer App for Workouts, Tabata & Fitness Training

### ISSUE THREAD

**Issue by breathful** [glasklart/hd#1721]
**App Name:** Runtastic Timer App for Workouts, Tabata & Fitness Training
**Bundle ID:** com.runtastic.iphone.timer.lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=583313558">583313558</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-timer-app-for-workouts/id583313558?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-timer-app-for-workouts/id583313558?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** runtastic
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/runtastic/id336599885?uo=4">© runtastic</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/6e/f4/f9/6ef4f9ec-bba9-716f-d4af-54d830031c95/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20237506/88452d4a-a8d4-11e6-8385-05f87a0cc293.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20237506/88452d4a-a8d4-11e6-8385-05f87a0cc293.png)
https://cloud.githubusercontent.com/assets/20930745/20237506/88452d4a-a8d4-11e6-8385-05f87a0cc293.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20237509/9e985f40-a8d4-11e6-8b5e-3894752cad10.png
