### ISSUE TITLE
Sparkasse - Your mobile branch

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1726]
**App Name:** Sparkasse - Your mobile branch
**Bundle ID:** de.starfinanz.Finanzstatus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=320599923">320599923</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sparkasse-your-mobile-branch/id320599923?mt=8&uo=4">https://itunes.apple.com/us/app/sparkasse-your-mobile-branch/id320599923?mt=8&uo=4</a>
**App Version:** 2.11.1
**Seller:** Star Finanz GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/star-finanz-gmbh/id320596875?uo=4>© Star Finanz GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/78/c2/c9/78c2c9af-c035-12a3-7036-a947a2b40bb5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418296/5d501f96-93c1-11e6-9b4c-a853f1b35f4f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418296/5d501f96-93c1-11e6-9b4c-a853f1b35f4f.png)
https://cloud.githubusercontent.com/assets/20930745/19418296/5d501f96-93c1-11e6-9b4c-a853f1b35f4f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19418303/7fee171a-93c1-11e6-9203-ff0d55a4900c.png
