### ISSUE TITLE
iBlacklist

### ISSUE THREAD

**Issue by johnnyhundreds** [glasklart/hd#1728]
**App Name:** iBlacklist
 **Bundle ID:** com.iDevBrTeam.iBlacklist
 **Version:** 10.2
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://user-images.githubusercontent.com/2068130/38188124-bed77f60-365a-11e8-8093-30aaa8de437a.png" width="180" height="180" />
 **Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38188148-cdeab120-365a-11e8-88a6-f202f8fbe90c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38188148-cdeab120-365a-11e8-88a6-f202f8fbe90c.png)
https://user-images.githubusercontent.com/2068130/38188148-cdeab120-365a-11e8-88a6-f202f8fbe90c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38188157-dc909af0-365a-11e8-85a8-9e612f9b3c7e.png
