### ISSUE TITLE
Ruzzle

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#173]
**App Name:** Ruzzle
**Bundle ID:** se.maginteractive.Rumble
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504265646">504265646</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ruzzle/id504265646?mt=8&uo=4">https://itunes.apple.com/us/app/ruzzle/id504265646?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Mobile Access Group AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mag-interactive/id307343213?uo=4>© MAG Interactive</a>
**Supported Devices:** iPodTouchFourthGen, iPhone4S, iPhone5, iPad23G, iPadMini, iPhone-3GS, iPhone5s, iPhone6Plus, iPhone4, iPadMini4G, iPad2Wifi, iPadFourthGen4G, iPadFourthGen, iPadThirdGen4G, iPodTouchFifthGen, iPadThirdGen, iPhone5c, iPhone6
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/55/b1/e2/55b1e2b6-cb2b-b69c-9d31-286319817046/mzl.qjwgwrlh.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8728141/d2ae7202-2be3-11e5-9e98-d46dd0830502.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8728141/d2ae7202-2be3-11e5-9e98-d46dd0830502.png)
https://cloud.githubusercontent.com/assets/10730122/8728141/d2ae7202-2be3-11e5-9e98-d46dd0830502.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8728136/cddb4d9a-2be3-11e5-9350-ca36041f5152.png
