### ISSUE TITLE
Field Trip

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1734]
**App Name:** Field Trip
**Bundle ID:** com.google.Scout
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=567841460">567841460</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/field-trip/id567841460?mt=8&uo=4">https://itunes.apple.com/us/app/field-trip/id567841460?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** Niantic, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/niantic-inc./id1037205060?uo=4">© Niantic, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/fd/27/b9/fd27b938-0abf-e4b2-e64d-9fd5c4fc5893/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19883920/286db0a6-a017-11e6-92eb-b77b6312b1ed.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19883920/286db0a6-a017-11e6-92eb-b77b6312b1ed.png)
https://cloud.githubusercontent.com/assets/20930745/19883920/286db0a6-a017-11e6-92eb-b77b6312b1ed.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19883951/4e1e5a12-a017-11e6-9d63-d5d53a314c6b.png
