### ISSUE TITLE
Safeway

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1735]
**App Name:** Safeway
**Bundle ID:** com.safeway.j4u
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=521487551">521487551</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/safeway/id521487551?mt=8&uo=4">https://itunes.apple.com/us/app/safeway/id521487551?mt=8&uo=4</a>
**App Version:** 4.7.2
**Seller:** Safeway Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/safeway-inc./id469532552?uo=4>© Safeway Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple22/v4/df/11/d4/df11d488-296a-354a-9c3f-43494521b5e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419984/b0ed2376-93e2-11e6-8d69-56f952b07188.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419984/b0ed2376-93e2-11e6-8d69-56f952b07188.png)
https://cloud.githubusercontent.com/assets/20930745/19419984/b0ed2376-93e2-11e6-8d69-56f952b07188.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19419992/cb01b4c0-93e2-11e6-95c6-2c8050cd4076.png
