### ISSUE TITLE
Walmart App: Shopping, Savings Catcher, & More

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1736]
**App Name:** Walmart App: Shopping, Savings Catcher, & More
**Bundle ID:** com.walmart.electronics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338137227">338137227</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/walmart-app-shopping-savings/id338137227?mt=8&uo=4">https://itunes.apple.com/us/app/walmart-app-shopping-savings/id338137227?mt=8&uo=4</a>
**App Version:** 7.1
**Seller:** Walmart
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/walmart/id338137230?uo=4>© Walmart</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple71/v4/cc/be/49/ccbe495b-ab63-5d59-230f-f086ae8af4f6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18225919/ccb416a4-71c4-11e6-9ab5-139a3d05291a.png)

**Comment by boxermansr** [comment]
Please update for new (updated) -large icons.
Thank you.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18225919/ccb416a4-71c4-11e6-9ab5-139a3d05291a.png)
https://cloud.githubusercontent.com/assets/3090247/18225919/ccb416a4-71c4-11e6-9ab5-139a3d05291a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18225920/ccbb0c8e-71c4-11e6-8500-6ae4bd97196d.png
