### ISSUE TITLE
Regal Cinemas

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1737]
**App Name:** Regal Cinemas
**Bundle ID:** com.regalcinemas.regalmovietheatersapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=502912815">502912815</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/regal-cinemas/id502912815?uo=4">https://apps.apple.com/us/app/regal-cinemas/id502912815?uo=4</a>
**App Version:** 6.0.1
**Seller:** Regal Cinemas, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/regal-cinemas/id502912818?uo=4">© Regal Cinemas</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/f5/3d/6f/f53d6f31-4253-6811-f636-8c84cdf0aa09/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62675025-534fec80-b9a5-11e9-93af-c3d75a90e7b3.png)

**Comment by Christian9901** [comment]
needs an update

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62675025-534fec80-b9a5-11e9-93af-c3d75a90e7b3.png)
https://user-images.githubusercontent.com/2068130/62675025-534fec80-b9a5-11e9-93af-c3d75a90e7b3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62675041-62cf3580-b9a5-11e9-82c6-d98bcdc623c6.png
