### ISSUE TITLE
iDocs Pro for Google Docs™ and Google Drive™

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1740]
**App Name:** iDocs Pro for Google Docs™ and Google Drive™
**Bundle ID:** com.icsoft.idocs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=502206895">502206895</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/idocs-pro-for-google-docs-and-google-drive/id502206895?mt=8&uo=4">https://itunes.apple.com/us/app/idocs-pro-for-google-docs-and-google-drive/id502206895?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** International Comercial Software Co.,Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/icsoft/id498653444?uo=4">© ICSOFT</a>
**Supported Devices:** iPodTouchSecondGen-iPod-touch-with-mic, iPhone3G-iPhone-3G, iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/af/ab/06/afab0634-16ff-a1a3-3f64-de1f4c86a5e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32212979-9d6cd050-be19-11e7-9dbf-a5e8ac2827e5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32212979-9d6cd050-be19-11e7-9dbf-a5e8ac2827e5.png)
https://user-images.githubusercontent.com/20930745/32212979-9d6cd050-be19-11e7-9dbf-a5e8ac2827e5.png

Source:
https://user-images.githubusercontent.com/20930745/32212995-b463d5e2-be19-11e7-97f7-34c4a320734e.png
