### ISSUE TITLE
Make a Meme+

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1741]
**App Name:** Make a Meme+
**Bundle ID:** com.SlayterDevelopment.MakeAMemePlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=513930217">513930217</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/make-a-meme/id513930217?mt=8&uo=4">https://itunes.apple.com/us/app/make-a-meme/id513930217?mt=8&uo=4</a>
**App Version:** 1.9.6
**Seller:** Bradley Slayter
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/slayter-development/id493706889?uo=4">© Slayter Development</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/0f/71/e8/0f71e8e2-fe6d-0a15-d764-42e5fe355529/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33232114-911babfa-d200-11e7-8a4a-069ce1a51e52.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33232114-911babfa-d200-11e7-8a4a-069ce1a51e52.png)
https://user-images.githubusercontent.com/2068130/33232114-911babfa-d200-11e7-8a4a-069ce1a51e52.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33232120-a0a59982-d200-11e7-8a4e-787bb5ffe70b.png
