### ISSUE TITLE
Instant Buttons

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1742]
**App Name:** Instant Buttons
**Bundle ID:** com.cremagames.InstantButtons
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=482166012">482166012</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instant-buttons/id482166012?mt=8&uo=4">https://itunes.apple.com/us/app/instant-buttons/id482166012?mt=8&uo=4</a>
**App Version:** 1.4.68
**Seller:** CremaGames S.L.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cremagames-s.l./id482166015?uo=4>© CremaGames S.L.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/e5/3f/b3/e53fb371-eb3a-2978-e159-0af4abbbe5ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18815760/1592e72e-82ff-11e6-8390-43f2da06e3a2.png)

**Comment by Anuskuss** [comment]
Does anyone want to remake this one? I don't like it that much...

**Comment by 2Qt2beStr8** [comment]
@Anuskuss  can you explain what you not like?

i tryed also to create this icon .. but i can't do it better

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18814988/1abedf86-8323-11e6-8c2b-aa95a05285f8.png)
https://cloud.githubusercontent.com/assets/20930745/18814988/1abedf86-8323-11e6-8c2b-aa95a05285f8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18814990/2f6f431c-8323-11e6-9e4a-2ba4b181a3d3.png

**Comment by ivanov007** [comment]
looking at the source I see the backkground is white, also the image is not resized at the full 1204x1024
here's the corrected version:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18815760/1592e72e-82ff-11e6-8390-43f2da06e3a2.png)
https://cloud.githubusercontent.com/assets/3090247/18815760/1592e72e-82ff-11e6-8390-43f2da06e3a2.png
Source:
https://cloud.githubusercontent.com/assets/3090247/18815761/1595bc4c-82ff-11e6-8146-f108918dd212.png
also I made a little cleanup

**Comment by 2Qt2beStr8** [comment]
Thank you @ivanov007 ... i uploaded the wrong file 😊

**Comment by dreamnet** [comment]
This is a very hard icon and I think it cannot be done better, so I'm adding the last one.
@Anuskuss You can always check back if you have an idea what we can make better.

**Comment by Anuskuss** [comment]
@2Qt2beStr8 @dreamnet Yeah even the original icon is bulky. I hope it gets a new one some day.
