### ISSUE TITLE
Cartoon Network App – Watch Videos, Clips and Full Episodes of Your Favorite Shows

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1745]
**App Name:** Cartoon Network App – Watch Videos, Clips and Full Episodes of Your Favorite Shows
**Bundle ID:** com.turner.cnvideoapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404593641">404593641</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cartoon-network-app-watch/id404593641?mt=8&uo=4">https://itunes.apple.com/us/app/cartoon-network-app-watch/id404593641?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Turner Broadcasting System, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/cartoon-network/id300726272?mt=8&uo=4>© Cartoon Network</a>
**Supported Devices:** iPhone6, iPodTouchFifthGen, iPad23G, iPadFourthGen4G, iPhone4, iPhone4S, iPad2Wifi, iPadThirdGen4G, iPhone5c, iPadMini4G, iPadMini, iPadThirdGen, iPhone5s, iPhone5, iPadFourthGen, iPhone6Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/c5/b2/8f/c5b28f5c-eaf9-10db-a711-b423cd927a8c/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8714524/19da68ac-2b44-11e5-9b20-8ce9825b89f4.png)

**Comment by zmathiasz** [comment]
@dreamnet 

Updated Icon:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8714524/19da68ac-2b44-11e5-9b20-8ce9825b89f4.png)
https://cloud.githubusercontent.com/assets/10950389/8714524/19da68ac-2b44-11e5-9b20-8ce9825b89f4.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8714527/26a1765c-2b44-11e5-8c62-25e0e46655be.png
