### ISSUE TITLE
DisneyNOW – Episodes & Live TV

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1746]
**App Name:** DisneyNOW – Episodes & Live TV
**Bundle ID:** com.disney.WATCHDisneyChannel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=529997671">529997671</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/disneynow-episodes-live-tv/id529997671?uo=4">https://apps.apple.com/us/app/disneynow-episodes-live-tv/id529997671?uo=4</a>
**App Version:** 7.4.0
**Seller:** Disney Electronic Content, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/disney/id284888248?uo=4">© Disney</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/4d/d1/64/4dd16471-d4ca-c9bb-b21f-0e9d4e421520/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com disney WATCHDisneyChannel-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60383138-8382a200-9a6d-11e9-9693-55d9b6533d14.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19358114/eeecc174-9174-11e6-91db-38e47784c772.png)
https://cloud.githubusercontent.com/assets/20930745/19358114/eeecc174-9174-11e6-91db-38e47784c772.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19358126/fe430b60-9174-11e6-8e26-e1cd7609d72e.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![com disney WATCHDisneyChannel-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60383138-8382a200-9a6d-11e9-9693-55d9b6533d14.png)
https://user-images.githubusercontent.com/2068130/60383138-8382a200-9a6d-11e9-9693-55d9b6533d14.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60383142-9301eb00-9a6d-11e9-9a97-8c26d80c903c.png
