### ISSUE TITLE
Zappos

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1748]
**App Name:** Zappos
**Bundle ID:** com.zappos.ipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=392988420">392988420</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zappos/id392988420?mt=8&uo=4">https://itunes.apple.com/us/app/zappos/id392988420?mt=8&uo=4</a>
**App Version:** 3.8.0
**Seller:** Zappos IP, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zappos-ip-inc./id392988423?uo=4">© Zappos IP, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/87/b5/70/87b5706c-4029-c92a-bf65-0060391f424f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20222822/17f54450-a837-11e6-9f5d-a4d665dbf5c3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20222822/17f54450-a837-11e6-9f5d-a4d665dbf5c3.png)
https://cloud.githubusercontent.com/assets/20930745/20222822/17f54450-a837-11e6-9f5d-a4d665dbf5c3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20222846/32820fe2-a837-11e6-89e5-4256d787c0d7.png
