### ISSUE TITLE
TagsForLikes

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#1749]
**App Name:** TagsForLikes - Copy and Paste Tags for Instagram - Hashtags Helper
**Bundle ID:** com.tfl.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=566662729">566662729</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tagsforlikes-copy-paste-tags/id566662729?mt=8&uo=4">https://itunes.apple.com/us/app/tagsforlikes-copy-paste-tags/id566662729?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Zaheer Mohiuddin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zaheer-mohiuddin/id566262346?uo=4>© Zaheer Mohiuddin</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/d6/7d/b0/d67db04b-86bb-2b27-8ab4-a55a62dbf3a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621066/30532880-988a-11e6-815a-2007c39d8056.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621066/30532880-988a-11e6-815a-2007c39d8056.png)
https://cloud.githubusercontent.com/assets/20930745/19621066/30532880-988a-11e6-815a-2007c39d8056.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19621071/4bcd374a-988a-11e6-8af5-489e30638385.png
