### ISSUE TITLE
DOOORS

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#175]
**App Name:** DOOORS - room escape game -
**Bundle ID:** com.58works.DOOORS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490611105">490611105</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dooors-room-escape-game/id490611105?mt=8&uo=4">https://itunes.apple.com/us/app/dooors-room-escape-game/id490611105?mt=8&uo=4</a>
**App Version:** 4.9
**Seller:** ODAKO Co.,Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/58works/id475571546?uo=4>© 58works</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/8c/03/d0/8c03d0f3-ad64-2384-b25d-5333be2b3ed7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12164429/cb9b9c90-b515-11e5-8d43-42785e3fd9e4.png)

**Comment by dreamnet** [comment]
Existing icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12164429/cb9b9c90-b515-11e5-8d43-42785e3fd9e4.png)
https://cloud.githubusercontent.com/assets/2068130/12164429/cb9b9c90-b515-11e5-8d43-42785e3fd9e4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12164441/d9a23600-b515-11e5-9cbf-942ef31d36a0.png
