### ISSUE TITLE
500px

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#1751]
**App Name:** 500px
**Bundle ID:** com.500px
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=471965292">471965292</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/500px/id471965292?mt=8&uo=4">https://itunes.apple.com/us/app/500px/id471965292?mt=8&uo=4</a>
**App Version:** 5.0.6
**Seller:** 500px Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/500px/id471965295?uo=4">© 500px</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/2b/82/20/2b82207a-299c-fced-4275-889c33b50d88/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32122676-7b07532e-bb61-11e7-875d-f140e5872106.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** 500px - Discover photos from the world's best photography community
**Bundle ID:** com.500px
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=471965292">471965292</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/500px-discover-photos-from/id471965292?mt=8&uo=4">https://itunes.apple.com/us/app/500px-discover-photos-from/id471965292?mt=8&uo=4</a>
**App Version:** 4.6.1
**Seller:** 500px Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/500px/id471965295?uo=4>© 500px</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/44/19/dd/4419dd69-0d9c-f80e-a3bc-7c1223bc77c3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16364424/d1ff2342-3be6-11e6-8056-4903693995ef.png)
https://cloud.githubusercontent.com/assets/2068130/16364424/d1ff2342-3be6-11e6-8056-4903693995ef.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16364431/e15ad836-3be6-11e6-87c4-3aef38e29e34.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** 500px
**Bundle ID:** com.500px
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=471965292">471965292</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/500px/id471965292?mt=8&uo=4">https://itunes.apple.com/us/app/500px/id471965292?mt=8&uo=4</a>
**App Version:** 5.0.6
**Seller:** 500px Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/500px/id471965295?uo=4">© 500px</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/2b/82/20/2b82207a-299c-fced-4275-889c33b50d88/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32122676-7b07532e-bb61-11e7-875d-f140e5872106.png)
https://user-images.githubusercontent.com/20930745/32122676-7b07532e-bb61-11e7-875d-f140e5872106.png

Source:
https://user-images.githubusercontent.com/20930745/32122701-8f6e2e3c-bb61-11e7-82c9-30ffecdcc369.png
