### ISSUE TITLE
SecurEnvoy Soft Token

### ISSUE THREAD

**Issue by geethreeforce** [glasklart/hd#1752]
**App Name:** SecurEnvoy Soft Token
**Bundle ID:** com.securenvoy.www.softtoken
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446939587">446939587</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/securenvoy-soft-token/id446939587?mt=8&uo=4">https://itunes.apple.com/us/app/securenvoy-soft-token/id446939587?mt=8&uo=4</a>
**App Version:** 81509
**Seller:** SecurEnvoy Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/securenvoy/id446939590?uo=4>© SecurEnvoy</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/31/bf/91/31bf91f4-18dd-a21e-bc9d-39037437a4a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19490647/460a7c90-9570-11e6-926f-c57f19c201fd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19490647/460a7c90-9570-11e6-926f-c57f19c201fd.png)
https://cloud.githubusercontent.com/assets/20930745/19490647/460a7c90-9570-11e6-926f-c57f19c201fd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19490688/6a435686-9570-11e6-96dc-eff7955de768.png
