### ISSUE TITLE
Cheats for SR - for all Saints Row games

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1755]
**App Name:** Cheats for SR - for all Saints Row games
**Bundle ID:** com.chrisjp.srcheats
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=480102438">480102438</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cheats-for-sr-for-all-saints/id480102438?mt=8&uo=4">https://itunes.apple.com/us/app/cheats-for-sr-for-all-saints/id480102438?mt=8&uo=4</a>
**App Version:** 1.5.4
**Seller:** Midnight Labs Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/midnight-labs-ltd/id433349453?uo=4>© Midnight Labs Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/9a/07/de/9a07dee1-ca0b-245a-a73a-72abda454baf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418854/0525d4e4-93cd-11e6-8470-e8fba3b32b00.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418854/0525d4e4-93cd-11e6-8470-e8fba3b32b00.png)
https://cloud.githubusercontent.com/assets/20930745/19418854/0525d4e4-93cd-11e6-8470-e8fba3b32b00.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19418857/2146caa2-93cd-11e6-9201-84b8efd0a3d8.png
