### ISSUE TITLE
Cheats for GTA - for all Grand Theft Auto games

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1756]
**App Name:** Cheats for GTA - for all Grand Theft Auto games
**Bundle ID:** com.tgtap.gtacheats
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=433349450">433349450</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cheats-for-gta-for-all-grand/id433349450?mt=8&uo=4">https://itunes.apple.com/us/app/cheats-for-gta-for-all-grand/id433349450?mt=8&uo=4</a>
**App Version:** 2.1.14
**Seller:** Midnight Labs Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/midnight-labs-ltd/id433349453?uo=4>© Midnight Labs Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/7a/df/f9/7adff91b-9712-0374-a941-4c917c4f89f8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18798269/f7bd82a0-81d1-11e6-8465-c95de5d77414.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18798269/f7bd82a0-81d1-11e6-8465-c95de5d77414.png)
https://cloud.githubusercontent.com/assets/2068130/18798269/f7bd82a0-81d1-11e6-8465-c95de5d77414.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18798282/0612f79a-81d2-11e6-986e-c96894b8e2b2.png
