### ISSUE TITLE
Westfield UK

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1759]
**App Name:** Westfield UK
**Bundle ID:** com.ibltd.westfield
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409824812">409824812</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/westfield-uk/id409824812?mt=8&uo=4">https://itunes.apple.com/us/app/westfield-uk/id409824812?mt=8&uo=4</a>
**App Version:** 7.2
**Seller:** Westfield Labs Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/westfield-labs-corporation/id744325978?uo=4>© Westfield Labs Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple22/v4/28/47/bc/2847bca6-0d62-a32d-741b-6705822962a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420310/1efdc04a-93e9-11e6-85f9-67d51148e356.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420310/1efdc04a-93e9-11e6-85f9-67d51148e356.png)
https://cloud.githubusercontent.com/assets/20930745/19420310/1efdc04a-93e9-11e6-85f9-67d51148e356.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19420317/42fa1156-93e9-11e6-873f-2b38ec30976e.png
