### ISSUE TITLE
Moonpig - Send Personalised Cards, Gifts & Flowers

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1760]
**App Name:** Moonpig - Send Personalised Cards, Gifts & Flowers
**Bundle ID:** com.commonagency.moonpig
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393730279">393730279</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/moonpig-send-personalised/id393730279?mt=8&uo=4">https://itunes.apple.com/gb/app/moonpig-send-personalised/id393730279?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** Moonpig.com Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/moonpig.com/id895116922?uo=4>© Moonpig.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/98/96/f4/9896f479-f74c-6a97-4746-7ede7c527911/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19289351/9a9db53a-900a-11e6-948c-d302c09a007b.png)

**Comment by 2Qt2beStr8** [comment]
same as #8293

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19289351/9a9db53a-900a-11e6-948c-d302c09a007b.png)
https://cloud.githubusercontent.com/assets/20930745/19289351/9a9db53a-900a-11e6-948c-d302c09a007b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19289368/aa5316be-900a-11e6-8801-151be831b5ac.png

**Comment by ivanov007** [comment]
I think this will look better without the background

**Comment by 2Qt2beStr8** [comment]
I like it with the background ... without background the eyebrowes does not fit to the rest

**Comment by ivanov007** [comment]
yeah good point
