### ISSUE TITLE
John Lewis

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1761]
**App Name:** John Lewis
**Bundle ID:** com.johnlewis.John-Lewis
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=486502369">486502369</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/john-lewis/id486502369?mt=8&uo=4">https://itunes.apple.com/us/app/john-lewis/id486502369?mt=8&uo=4</a>
**App Version:** 3.7.1
**Seller:** John Lewis plc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/john-lewis-partnership/id486502372?uo=4">© John Lewis Partnership</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/5c/b3/bf/5cb3bf93-8ddd-cadc-bd0b-2673a7cf6232/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19851729/b7ed71ca-9f5f-11e6-981a-1132c86069ab.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19851729/b7ed71ca-9f5f-11e6-981a-1132c86069ab.png)
https://cloud.githubusercontent.com/assets/20930745/19851729/b7ed71ca-9f5f-11e6-981a-1132c86069ab.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19851748/ce97a968-9f5f-11e6-8ec0-6ba496bab5c5.png
