### ISSUE TITLE
Fido My Account

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1762]
**App Name:** Fido My Account
**Bundle ID:** com.fido.fivemobile.myaccount
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=337632423">337632423</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/fido-my-account/id337632423?mt=8&uo=4">https://itunes.apple.com/ca/app/fido-my-account/id337632423?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Fido Solutions Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/artist/fido-solutions-inc./id337632426?uo=4>© Fido Solutions Inc.</a>
**Supported Devices:** iPadThirdGen, iPadMini, iPhone4, iPhone6, iPadFourthGen4G, iPad2Wifi, iPadThirdGen4G, iPadMini4G, iPhone5s, iPodTouchFifthGen, iPhone4S, iPhone5, iPhone-3GS, iPhone6Plus, iPad23G, iPodTouchFourthGen, iPhone5c, iPodTouchSixthGen, iPadFourthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/f1/92/85/f1928585-62b2-e395-ee23-98194782c445/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9269154/c090c874-4266-11e5-92b7-72c3c866a026.png)

**Comment by LaCh0uine** [comment]
Icon need to be updated 

Thank you for your work

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9269154/c090c874-4266-11e5-92b7-72c3c866a026.png)
https://cloud.githubusercontent.com/assets/2068130/9269154/c090c874-4266-11e5-92b7-72c3c866a026.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9269161/d41eb180-4266-11e5-883c-6a85c143ffa4.png
