### ISSUE TITLE
Edmodo

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1768]
**App Name:** Edmodo
**Bundle ID:** com.fusionprojects.edmodo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378352300">378352300</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/edmodo/id378352300?mt=8&uo=4">https://itunes.apple.com/us/app/edmodo/id378352300?mt=8&uo=4</a>
**App Version:** 5.7
**Seller:** Edmodo, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/edmodo-inc./id378352303?uo=4>© Edmodo, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/24/c7/eb/24c7eb8a-52b3-dbd1-8e1c-c110f360001b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411985/f9c0763e-930b-11e6-97e5-f795e834c0cf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411985/f9c0763e-930b-11e6-97e5-f795e834c0cf.png)
https://cloud.githubusercontent.com/assets/20930745/19411985/f9c0763e-930b-11e6-97e5-f795e834c0cf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411988/0d4df028-930c-11e6-855a-eacd1ddc299f.png
