### ISSUE TITLE
Gett (GetTaxi) - NYC Black Car Service & Taxi app

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1773]
**App Name:** Gett (GetTaxi) - NYC Black Car Service & Taxi app
**Bundle ID:** gettaxi.co.uk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=449655162">449655162</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gett-gettaxi-nyc-black-car/id449655162?mt=8&uo=4">https://itunes.apple.com/us/app/gett-gettaxi-nyc-black-car/id449655162?mt=8&uo=4</a>
**App Version:** 6.10
**Seller:** GT Get Taxi Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gt-get-taxi-ltd./id449655165?uo=4>© GT Get Taxi Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/55/11/59/551159b6-2d06-731e-9435-306d2b3bbcca/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11248611/4b52a408-8e22-11e5-81b0-34702878f2ae.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11248611/4b52a408-8e22-11e5-81b0-34702878f2ae.png)
https://cloud.githubusercontent.com/assets/10730122/11248611/4b52a408-8e22-11e5-81b0-34702878f2ae.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11248608/47f076b4-8e22-11e5-99dc-9e52dcf189dc.png
