### ISSUE TITLE
Nyan Cat: JUMP!

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1774]
**App Name:** Nyan Cat: JUMP!
**Bundle ID:** com.istomgames.nyanjump
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476023307">476023307</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nyan-cat-jump!/id476023307?mt=8&uo=4">https://itunes.apple.com/us/app/nyan-cat-jump!/id476023307?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Istom Games Kft.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/istom-games-kft./id333561719?uo=4">© Istom Games Kft.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/34/9a/c4/349ac46d-97d2-fd42-2426-9fa210f48434/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23135220/073eacae-f798-11e6-8990-ecff86be9c9e.png)

**Comment by dengler9** [comment]
## Update needed

**App Name:** Nyan Cat: JUMP!
**Bundle ID:** com.istomgames.nyanjump
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476023307">476023307</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nyan-cat-jump!/id476023307?mt=8&uo=4">https://itunes.apple.com/us/app/nyan-cat-jump!/id476023307?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Istom Games Kft.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/istom-games-kft./id333561719?uo=4">© Istom Games Kft.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/34/9a/c4/349ac46d-97d2-fd42-2426-9fa210f48434/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23135220/073eacae-f798-11e6-8990-ecff86be9c9e.png)
https://cloud.githubusercontent.com/assets/2068130/23135220/073eacae-f798-11e6-8990-ecff86be9c9e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23135240/191b8302-f798-11e6-8f55-48624f27ddc3.png
