### ISSUE TITLE
PolisNytt

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#178]
**App Name:** PolisNytt
**Bundle ID:** se.dotunited.polisnytt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401900062">401900062</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/polisnytt/id401900062?mt=8&uo=4">https://itunes.apple.com/us/app/polisnytt/id401900062?mt=8&uo=4</a>
**App Version:** 2.02
**Seller:** DOT UNITED AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dot-united-ab/id398465000?uo=4>© Dot United AB</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/8d/d8/23/8dd823ba-9639-7e0e-0a9c-b7f8a64786af/mzl.vphxgdeh.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10388758/eff3c8c8-6e6c-11e5-9c00-f3fb582b3c2f.png)

**Comment by Trubbel** [comment]
Updating icon plus source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10388758/eff3c8c8-6e6c-11e5-9c00-f3fb582b3c2f.png)
https://cloud.githubusercontent.com/assets/10730122/10388758/eff3c8c8-6e6c-11e5-9c00-f3fb582b3c2f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10388757/ecae0bec-6e6c-11e5-9593-32cf093a09d7.png
