### ISSUE TITLE
Edenred MX

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1784]
**App Name:** Edenred MX
**Bundle ID:** com.smartthinking.edenred
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=414418591">414418591</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/edenred-mx/id414418591?mt=8&uo=4">https://itunes.apple.com/fr/app/edenred-mx/id414418591?mt=8&uo=4</a>
**App Version:** 2.8.0
**Seller:** Edenred
**Developer:** <a target="_blank" href="https://itunes.apple.com/fr/developer/edenred/id579555174?uo=4">© Edenred</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/7d/f2/c5/7df2c554-9c92-c45b-f469-acf6c97bbef5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19901034/f3ef0ee8-a065-11e6-8f3a-fa7edd966e8e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19901034/f3ef0ee8-a065-11e6-8f3a-fa7edd966e8e.png)
https://cloud.githubusercontent.com/assets/20930745/19901034/f3ef0ee8-a065-11e6-8f3a-fa7edd966e8e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19901061/0e049fa0-a066-11e6-9a3b-e2c01d2f38e4.png
