### ISSUE TITLE
Slide ►

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#1785]
**App Name:** Slide ►
**Bundle ID:** com.thefalcoinitiative.slidetounlock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=359315994">359315994</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slide/id359315994?mt=8&uo=4">https://itunes.apple.com/us/app/slide/id359315994?mt=8&uo=4</a>
**App Version:** 2.2.4
**Seller:** Arman Dezfuli-Arjomandi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/arman-dezfuli-arjomandi/id351543656?uo=4>© Arman Dezfuli-Arjomandi</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/ce/fd/e3/cefde30a-cd21-2187-ddbe-4649dac82aed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18909702/e144dae0-8574-11e6-8b70-0540bbc58cfe.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18882019/d9e89ca6-84dd-11e6-8653-231f07312353.png)
https://cloud.githubusercontent.com/assets/20930745/18882019/d9e89ca6-84dd-11e6-8653-231f07312353.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18882038/e9a2a66e-84dd-11e6-802f-955d3dc3dcf0.png
