### ISSUE TITLE
Image Blender

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#1787]
**App Name:** Image Blender
**Bundle ID:** com.jhnd.blender
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=414544492">414544492</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/image-blender/id414544492?mt=8&uo=4">https://itunes.apple.com/us/app/image-blender/id414544492?mt=8&uo=4</a>
**App Version:** 2.5.3
**Seller:** Johan Andersson
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/johan-andersson/id309687330?uo=4">© Johan Andersson</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/cf/5c/81/cf5c8172-2afb-0c52-6989-9b9245938db8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19903210/16351030-a06e-11e6-8ff2-55bcc10479dd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19903210/16351030-a06e-11e6-8ff2-55bcc10479dd.png)
https://cloud.githubusercontent.com/assets/20930745/19903210/16351030-a06e-11e6-8ff2-55bcc10479dd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19903224/2b5ebb8c-a06e-11e6-9535-a6ceef7e1977.png
