### ISSUE TITLE
GoToMeeting

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1789]
**App Name:** GoToMeeting
**Bundle ID:** com.citrixonline.iOS.GoToMeeting
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424104128">424104128</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gotomeeting/id424104128?mt=8&uo=4">https://itunes.apple.com/us/app/gotomeeting/id424104128?mt=8&uo=4</a>
**App Version:** 6.6.4.1127
**Seller:** Citrix Online LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/citrix/id417742730?uo=4>© Citrix</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/a6/e4/53/a6e45354-fe29-646e-1bae-1b79b30006dc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420556/2204e8ea-93ee-11e6-867f-5a0f9f11d291.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420556/2204e8ea-93ee-11e6-867f-5a0f9f11d291.png)
https://cloud.githubusercontent.com/assets/20930745/19420556/2204e8ea-93ee-11e6-867f-5a0f9f11d291.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19420565/478e4688-93ee-11e6-9242-537f8f47857a.png
