### ISSUE TITLE
Flashlight •

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#179]
**App Name:** Flashlight •
**Bundle ID:** com.7thg.flashlight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380248105">380248105</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flashlight/id380248105?mt=8&uo=4">https://itunes.apple.com/us/app/flashlight/id380248105?mt=8&uo=4</a>
**App Version:** 3.23
**Seller:** 7th Gear
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/7th-gear/id321178305?uo=4>© 7th Gear</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/87/63/21/87632154-81ee-a8a8-4307-69d3d4412d7b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18546363/d9393d6e-7b3d-11e6-9b22-e70faee693bc.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**App Name:** Flashlight •
**Bundle ID:** com.7thg.flashlight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380248105">380248105</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flashlight/id380248105?mt=8&uo=4">https://itunes.apple.com/us/app/flashlight/id380248105?mt=8&uo=4</a>
**App Version:** 3.23
**Seller:** 7th Gear
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/7th-gear/id321178305?uo=4>© 7th Gear</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/87/63/21/87632154-81ee-a8a8-4307-69d3d4412d7b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18469403/61d6633c-79a8-11e6-9746-eadff1d658f1.png)
https://cloud.githubusercontent.com/assets/20930745/18469403/61d6633c-79a8-11e6-9746-eadff1d658f1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18469421/70388928-79a8-11e6-9310-dc6152115ec1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18469565/f3375926-79a8-11e6-9974-1de9f77fcac6.png)
https://cloud.githubusercontent.com/assets/20930745/18469565/f3375926-79a8-11e6-9974-1de9f77fcac6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18469586/090f2706-79a9-11e6-940d-5044111f0046.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet .. can we use this icon? i like it more than the original

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18546363/d9393d6e-7b3d-11e6-9b22-e70faee693bc.png)
https://cloud.githubusercontent.com/assets/20930745/18546363/d9393d6e-7b3d-11e6-9b22-e70faee693bc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18546672/720db7f8-7b3f-11e6-832a-5136310b4238.png

**Comment by Trubbel** [comment]
I like it better as well.

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes, I think it's fine.
