### ISSUE TITLE
Facetune

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1791]
**App Name:** Facetune
**Bundle ID:** com.lightricks.Facetune
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606310581">606310581</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facetune/id606310581?mt=8&uo=4">https://itunes.apple.com/us/app/facetune/id606310581?mt=8&uo=4</a>
**App Version:** 2.5.4
**Seller:** Lightricks Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lightricks-ltd./id606310584?uo=4>© Lightricks Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/c1/f8/d6/c1f8d65e-24fa-7aac-92fd-ff7125fa6fbd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18632160/54f3b688-7e76-11e6-8b8a-a7ea2bc23a3a.png)

**Comment by grkka** [comment]
Needs update to v 5.00.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18632160/54f3b688-7e76-11e6-8b8a-a7ea2bc23a3a.png)
https://cloud.githubusercontent.com/assets/20930745/18632160/54f3b688-7e76-11e6-8b8a-a7ea2bc23a3a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18632175/681198de-7e76-11e6-8fa1-283e223a51ad.png
