### ISSUE TITLE
Alarm Clock HD

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1792]
**App Name:** Alarm Clock HD
**Bundle ID:** com.alarmclockcompany.alarmclockhd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441922503">441922503</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alarm-clock-hd/id441922503?mt=8&uo=4">https://itunes.apple.com/us/app/alarm-clock-hd/id441922503?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Impala Studios B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/impala-studios/id1063279743?uo=4>© Impala Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/f9/58/bb/f958bb9c-017d-eb97-9ac9-4d92dfd5f104/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18610997/529a9816-7d2c-11e6-95bb-e5fd38281bbc.png)

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18610997/529a9816-7d2c-11e6-95bb-e5fd38281bbc.png)
https://cloud.githubusercontent.com/assets/20930745/18610997/529a9816-7d2c-11e6-95bb-e5fd38281bbc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/20930745/18610998/639e99f0-7d2c-11e6-8545-d53cdcef655e.png
