### ISSUE TITLE
Boldomatic - Express Yourself with Words

### ISSUE THREAD

**Issue by brodyhoskins** [glasklart/hd#1795]
**App Name:** Boldomatic - Express Yourself with Words
**Bundle ID:** ch.nerves.boldomatic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=573250776">573250776</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boldomatic-express-yourself/id573250776?mt=8&uo=4">https://itunes.apple.com/us/app/boldomatic-express-yourself/id573250776?mt=8&uo=4</a>
**App Version:** 2.6.1
**Seller:** Nerves GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nerves-design-engineering/id573250779?uo=4>© Nerves Design & Engineering</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/33/77/c7/3377c772-650b-0114-45ce-a336b0229ee5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411825/1b5de7a2-9309-11e6-8df9-b643736417a3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411825/1b5de7a2-9309-11e6-8df9-b643736417a3.png)
https://cloud.githubusercontent.com/assets/20930745/19411825/1b5de7a2-9309-11e6-8df9-b643736417a3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411829/344b2720-9309-11e6-861c-d6a0595f035e.png
