### ISSUE TITLE
eBaum's Daily Digest

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1798]
**App Name:** eBaum's Daily Digest
**Bundle ID:** com.viumbe.ebaumsworld
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542557029">542557029</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ebaums-daily-digest/id542557029?mt=8&uo=4">https://itunes.apple.com/us/app/ebaums-daily-digest/id542557029?mt=8&uo=4</a>
**App Version:** 1.6.7
**Seller:** Viumbe, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/viumbe-llc/id542557032?uo=4>© Viumbe, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/1d/53/67/1d536744-9138-77cb-728a-2c63b9283948/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19455791/bced0556-94be-11e6-92c4-5c193382b84c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19455791/bced0556-94be-11e6-92c4-5c193382b84c.png)
https://cloud.githubusercontent.com/assets/20930745/19455791/bced0556-94be-11e6-92c4-5c193382b84c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19455810/da8c6e26-94be-11e6-85c5-777339dd3e27.png
