### ISSUE TITLE
Giffer - Animated GIF Maker App

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1799]
**App Name:** Giffer - Animated GIF Maker App
**Bundle ID:** com.taberbuhl.Giffer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416952536">416952536</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/giffer-animated-gif-maker-app/id416952536?mt=8&uo=4">https://itunes.apple.com/us/app/giffer-animated-gif-maker-app/id416952536?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Taber Buhl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/taber-buhl/id317530003?uo=4>© Taber Buhl</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/33/4c/a2/334ca200-7497-d088-a367-536c2a81bf55/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411945/3d601396-930b-11e6-9d3b-0a10ce4580fc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411945/3d601396-930b-11e6-9d3b-0a10ce4580fc.png)
https://cloud.githubusercontent.com/assets/20930745/19411945/3d601396-930b-11e6-9d3b-0a10ce4580fc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411947/4cad30cc-930b-11e6-9ced-9fa9d68738c0.png
