### ISSUE TITLE
Formelsamlingen

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#180]
**App Name:** Formelsamlingen
**Bundle ID:** se.mattecentrum.Formelsamlingen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406652995">406652995</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/formelsamlingen/id406652995?mt=8&uo=4">https://itunes.apple.com/us/app/formelsamlingen/id406652995?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Johan Wendt
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mattecentrum/id406652998?uo=4>© Mattecentrum</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple22/v4/69/c7/50/69c75059-1c75-3a36-0833-7568835fa0a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19401462/c5f5bb62-925b-11e6-9251-e7b3237b87ec.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19401462/c5f5bb62-925b-11e6-9251-e7b3237b87ec.png)
https://cloud.githubusercontent.com/assets/20930745/19401462/c5f5bb62-925b-11e6-9251-e7b3237b87ec.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19401474/d7dfd9de-925b-11e6-8b3d-ed19ddcffaee.png
