### ISSUE TITLE
Tangled

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1800]
**App Name:** Tangled
**Bundle ID:** com.myfocusphotos.tangled
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=309543858">309543858</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tangled/id309543858?mt=8&uo=4">https://itunes.apple.com/us/app/tangled/id309543858?mt=8&uo=4</a>
**App Version:** 5.0.2
**Seller:** West Code Studios
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/west-code-studios/id309543861?uo=4">© West Code Studios</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/19/21/1d/19211d34-1808-3e45-fe1e-1c4390198f80/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33231795-9dd0f6ac-d1fb-11e7-808e-122fdbf494b8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33231795-9dd0f6ac-d1fb-11e7-808e-122fdbf494b8.png)
https://user-images.githubusercontent.com/2068130/33231795-9dd0f6ac-d1fb-11e7-808e-122fdbf494b8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33231800-ac1f33f4-d1fb-11e7-81a1-8e805758b6ec.png
