### ISSUE TITLE
iSwap Faces

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1801]
**App Name:** iSwap Faces
**Bundle ID:** com.blackfrogindustries.iswapfaces
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=305557780">305557780</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iswap-faces/id305557780?mt=8&uo=4">https://itunes.apple.com/us/app/iswap-faces/id305557780?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** Black Frog Industries, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/black-frog-industries-llc/id303102762?uo=4">© Black Frog Industries, LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple117/v4/72/fa/ef/72faef44-6895-8778-6a4d-5ffc38ca8642/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39469572-2bdcf334-4d39-11e8-9c1e-27551b4ff4cc.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39469572-2bdcf334-4d39-11e8-9c1e-27551b4ff4cc.png)
https://user-images.githubusercontent.com/2068130/39469572-2bdcf334-4d39-11e8-9c1e-27551b4ff4cc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39469583-399c353e-4d39-11e8-9f31-bca0d234ed28.png
