### ISSUE TITLE
Dblcam

### ISSUE THREAD

**Issue by johnnyhundreds** [glasklart/hd#1804]
**App Name:** Dblcam
**Bundle ID:** com.socialprintstudio.doublecam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=605269890">605269890</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dblcam/id605269890?mt=8&uo=4">https://itunes.apple.com/us/app/dblcam/id605269890?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Toad Murphy Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/social-print-studio/id495249026?uo=4>© Social Print Studio</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/8e/a6/eb/8ea6eb8f-9512-7d1e-c33e-1147e8ac87b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418934/763c3a1e-93ce-11e6-8fd4-0499f2ce710d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418934/763c3a1e-93ce-11e6-8fd4-0499f2ce710d.png)
https://cloud.githubusercontent.com/assets/20930745/19418934/763c3a1e-93ce-11e6-8fd4-0499f2ce710d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19418941/87ef8248-93ce-11e6-82e8-4b8be7a26874.png
