### ISSUE TITLE
iCleaner Pro

### ISSUE THREAD

**Issue by HoboAM** [glasklart/hd#1806]
**App Name:** iCleaner Pro
**Bundle ID:** com.exile90.icleanerpro
**Version:** 7.5.0
**Repo:** https://ib-soft.net/cydia
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/10920515/c274f9ea-8270-11e5-8630-6eb59f98f534.png" width="150" height="150">
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/10920526/d2b1dc74-8270-11e5-9d59-8ebc0b4e3f39.png)

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by dreamnet** [comment]
@Trubbel I think this needs to be removed, because we have #235...

**Comment by dreamnet** [comment]
Woops, found out that this app aleready exists on the repo `https://ib-soft.net/cydia`. I'm re-adding the icon.
