### ISSUE TITLE
OPB News

### ISSUE THREAD

**Issue by ericlo** [glasklart/hd#1807]
**App Name:** OPB News
**Bundle ID:** org.opb.OPBNews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=596183142">596183142</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/opb-news/id596183142?mt=8&uo=4">https://itunes.apple.com/us/app/opb-news/id596183142?mt=8&uo=4</a>
**App Version:** 3.1.10
**Seller:** Oregon Public Broadcasting
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/oregon-public-broadcasting/id456011220?uo=4">© Oregon Public Broadcasting</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/da/83/0e/da830e1c-80a2-5c29-47b1-0a02a24d8d8f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19898472/6a3d6d24-a05c-11e6-8ada-030d5d933317.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19898472/6a3d6d24-a05c-11e6-8ada-030d5d933317.png)
https://cloud.githubusercontent.com/assets/20930745/19898472/6a3d6d24-a05c-11e6-8ada-030d5d933317.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19898500/848a0af2-a05c-11e6-89e6-a8a7f4b73b52.png
