### ISSUE TITLE
Abfahrtsmonitor

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1811]
**App Name:** Abfahrtsmonitor
**Bundle ID:** de.avwprojects.abfahrtsmonitor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=412811098">412811098</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/abfahrtsmonitor/id412811098?mt=8&uo=4">https://itunes.apple.com/de/app/abfahrtsmonitor/id412811098?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Witali Aswolinskiy
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/witali-aswolinskiy/id370769025?uo=4>© Witali Aswolinskiy</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/3e/0b/9c/3e0b9c5d-7989-7657-639b-46294bce2b6a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18455124/5d79f692-7948-11e6-837a-a7d5b3f47047.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18455124/5d79f692-7948-11e6-837a-a7d5b3f47047.png)
https://cloud.githubusercontent.com/assets/20930745/18455124/5d79f692-7948-11e6-837a-a7d5b3f47047.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18455136/718ac92c-7948-11e6-87af-f76de404c35f.png
