### ISSUE TITLE
Audio Memos - The Voice Recorder

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1812]
**App Name:** Audio Memos - The Voice Recorder
**Bundle ID:** com.imesart.AudioMemos2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338550388">338550388</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/audio-memos-voice-recorder/id338550388?mt=8&uo=4">https://itunes.apple.com/us/app/audio-memos-voice-recorder/id338550388?mt=8&uo=4</a>
**App Version:** 4.6.1
**Seller:** Imesart S.a.r.l.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/imesart-s.a.r.l./id290160983?uo=4>© Imesart S.a.r.l.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/4d/29/53/4d295329-37d3-ed81-3c70-76f8f4bf70a4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10923281/70972778-8280-11e5-833f-bf6dfabb3665.png)

**Comment by Trubbel** [comment]
Needs an update.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13527702/a2493724-e1d6-11e5-8cd0-32dd54b7b3a9.png)
https://cloud.githubusercontent.com/assets/3090247/13527702/a2493724-e1d6-11e5-8cd0-32dd54b7b3a9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13527691/8de2446a-e1d6-11e5-986a-72edd3543ae4.png

**Comment by dreamnet** [comment]
@ivanov007 @Trubbel What about leaving out the background and making the mic and the jagged line a bit bigger ?

**Comment by ivanov007** [comment]
yeah maybe something like this
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13724566/3f9f0c78-e84f-11e5-9545-6929fec6d52b.png)
https://cloud.githubusercontent.com/assets/3090247/13724566/3f9f0c78-e84f-11e5-9545-6929fec6d52b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13724567/3fa1b608-e84f-11e5-8413-630add94abd8.png

**Comment by Anuskuss** [comment]
@ivanov007 I think he meant the icon should only consist the mic (bigger) and the audio wave line (thicker).

**Comment by dreamnet** [comment]
Maybe we can use the one from #6753 ?

**Comment by ivanov007** [comment]
@dreamnet sure, is the same icon

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10923281/70972778-8280-11e5-833f-bf6dfabb3665.png)
https://cloud.githubusercontent.com/assets/2068130/10923281/70972778-8280-11e5-833f-bf6dfabb3665.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10923289/7f99ffd4-8280-11e5-9aa3-cbdf933ec2ac.png

**Comment by Anuskuss** [comment]
@dreamnet Do you really want to keep the background?

**Comment by dreamnet** [comment]
@Anuskuss Yes.

**Comment by Anuskuss** [comment]
@dreamnet How about removing the lines (and add the top again)?
