### ISSUE TITLE
iamTravelr - Lightroom Presets

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1814]
**App Name:** iamTravelr - Lightroom Presets
**Bundle ID:** com.umityoruk.deluxefx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520664855">520664855</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iamtravelr-lightroom-presets/id520664855?mt=8&uo=4">https://itunes.apple.com/us/app/iamtravelr-lightroom-presets/id520664855?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** Ümit Yörük
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pictuts/id520664858?uo=4">© Pictuts</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/29/66/41/29664106-be49-9581-60b4-e5004d60fdf2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38161940-8bb07994-34d8-11e8-95ac-889eba431618.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19739588/cf2da50a-9bbb-11e6-911b-d073b1d869cc.png)
https://cloud.githubusercontent.com/assets/2068130/19739588/cf2da50a-9bbb-11e6-911b-d073b1d869cc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19739597/dd4c8f7a-9bbb-11e6-9865-dcaaee73a66a.png

**Comment by Christian9901** [comment]
needs an update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38161940-8bb07994-34d8-11e8-95ac-889eba431618.png)
https://user-images.githubusercontent.com/2068130/38161940-8bb07994-34d8-11e8-95ac-889eba431618.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38161944-99c6c1dc-34d8-11e8-9f95-4f25b4cf8774.png
