### ISSUE TITLE
Metronome Ϟ

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1816]
**App Name:** Metronome Ϟ
**Bundle ID:** com.onyx3.metrotimer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416443133">416443133</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/metronome/id416443133?mt=8&uo=4">https://itunes.apple.com/us/app/metronome/id416443133?mt=8&uo=4</a>
**App Version:** 3.3.2
**Seller:** ONYX 3
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/onyx-apps/id356553882?uo=4">© ONYX Apps</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/80/f5/89/80f58980-fd12-e778-8680-f7789ef9317f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20237865/b0f0e86a-a8de-11e6-8e57-ef901c867732.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20237865/b0f0e86a-a8de-11e6-8e57-ef901c867732.png)
https://cloud.githubusercontent.com/assets/20930745/20237865/b0f0e86a-a8de-11e6-8e57-ef901c867732.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20237871/cdd36b4c-a8de-11e6-8eee-fd53e6e8809a.png
