### ISSUE TITLE
komoot

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#1817]
**App Name:** komoot
**Bundle ID:** de.komoot.berlinbikeapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447374873">447374873</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/komoot/id447374873?mt=8&uo=4">https://itunes.apple.com/us/app/komoot/id447374873?mt=8&uo=4</a>
**App Version:** 8.4.1
**Seller:** komoot GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/komoot-gmbh/id365019076?uo=4>© komoot GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/1a/d4/1d/1ad41d81-7e24-0909-85fa-4de65deb5e21/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19496319/3eba3cf2-9587-11e6-9539-4e4ecab59a8e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19496319/3eba3cf2-9587-11e6-9539-4e4ecab59a8e.png)
https://cloud.githubusercontent.com/assets/20930745/19496319/3eba3cf2-9587-11e6-9539-4e4ecab59a8e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19496339/5c552452-9587-11e6-9657-a19b8b3ebf43.png
