### ISSUE TITLE
Kingdom Rush

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#182]
**App Name:** Kingdom Rush
**Bundle ID:** com.armorgames.kingdomrushiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=516378985">516378985</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kingdom-rush/id516378985?mt=8&uo=4">https://itunes.apple.com/us/app/kingdom-rush/id516378985?mt=8&uo=4</a>
**App Version:** 2.8.2
**Seller:** Ironhide S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ironhide-s.a./id558612918?uo=4>© Ironhide S.A.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/e0/a1/9a/e0a19a48-1278-53e0-93f6-42eb7e9e6fef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18916210/ef9952c8-8593-11e6-82a7-1af9d131c629.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18869102/21118670-84ab-11e6-9a21-45e79e4092e0.png)
https://cloud.githubusercontent.com/assets/20930745/18869102/21118670-84ab-11e6-9a21-45e79e4092e0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18869133/40ee41d6-84ab-11e6-9fc7-413de696370b.png

**Comment by 2Qt2beStr8** [comment]
@ivanov007 ... can you please use this file .... a little detail in the helmet was missing

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18916210/ef9952c8-8593-11e6-82a7-1af9d131c629.png)
https://cloud.githubusercontent.com/assets/20930745/18916210/ef9952c8-8593-11e6-82a7-1af9d131c629.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18916221/030fa5fa-8594-11e6-8fe2-10dd4dc07a56.png

**Comment by ivanov007** [comment]
@2Qt2beStr8 sure, I see it now :+1:
