### ISSUE TITLE
NederLogo

### ISSUE THREAD

**Issue by Richard100** [glasklart/hd#1824]
**App Name:** NederLogo
**Bundle ID:** com.TomFreijsen.LogoQuiz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=534983174">534983174</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nederlogo/id534983174?mt=8&uo=4">https://itunes.apple.com/us/app/nederlogo/id534983174?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Stichting Christelijk Voortgezet Onderwijs Zeeland
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ostrea-lyceum/id473933351?uo=4">© Ostrea Lyceum</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/eb/9f/fa/eb9ffaf7-5971-e9ee-7e18-f7b240d5d872/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19920487/2f2549e6-a0d9-11e6-81ac-86dc82f6a925.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19920487/2f2549e6-a0d9-11e6-81ac-86dc82f6a925.png)
https://cloud.githubusercontent.com/assets/20930745/19920487/2f2549e6-a0d9-11e6-81ac-86dc82f6a925.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19920496/4349055c-a0d9-11e6-9319-fa4074ad0843.png
