### ISSUE TITLE
Fieldrunners 2

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#183]
**App Name:** Fieldrunners 2
**Bundle ID:** fieldrunners2.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527358348">527358348</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fieldrunners-2/id527358348?mt=8&uo=4">https://itunes.apple.com/us/app/fieldrunners-2/id527358348?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Subatomic Studios, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/subatomic-studios-llc/id292421274?uo=4>© Subatomic Studios, LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/39/a2/74/39a27465-65fa-1c22-65b2-76b944e5f187/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19019088/91ce1b7c-8879-11e6-9004-78f1a95cc766.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
... not perfect ... but i can't do it better

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19016625/e29a291a-881f-11e6-82fa-cba61b61672b.png)
https://cloud.githubusercontent.com/assets/20930745/19016625/e29a291a-881f-11e6-82fa-cba61b61672b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19016626/f0169e48-881f-11e6-8c89-782a92afcbac.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 That's not so bad... I just made a few seperation lines a bit thicker so things came out clearer... and you missed the "2".
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19019088/91ce1b7c-8879-11e6-9004-78f1a95cc766.png)
https://cloud.githubusercontent.com/assets/2068130/19019088/91ce1b7c-8879-11e6-9004-78f1a95cc766.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19019091/a053c214-8879-11e6-9e83-7b2331be3295.png
I take this icon untils someone makes a better one. Credit so @2Qt2beStr8.
