### ISSUE TITLE
Forever 21

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1834]
**App Name:** Forever 21
**Bundle ID:** com.forever21.Forever21
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=365886172">365886172</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/forever-21/id365886172?mt=8&uo=4">https://itunes.apple.com/us/app/forever-21/id365886172?mt=8&uo=4</a>
**App Version:** 4.3.4
**Seller:** Forever 21, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/forever-21-inc./id365886175?uo=4>© Forever 21, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/ee/96/6d/ee966d31-374c-7534-1cd0-dcb2f9544e3b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19514609/7a054ce4-95f4-11e6-9024-da11df06beda.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19514609/7a054ce4-95f4-11e6-9024-da11df06beda.png)
https://cloud.githubusercontent.com/assets/20930745/19514609/7a054ce4-95f4-11e6-9024-da11df06beda.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19514650/9938629a-95f4-11e6-80ad-aad8d6ccf81d.png
