### ISSUE TITLE
Rage Comics

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1837]
**App Name:** Rage Comics
**Bundle ID:** com.albertogh.RageComics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431553898">431553898</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rage-comics/id431553898?mt=8&uo=4">https://itunes.apple.com/us/app/rage-comics/id431553898?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** Alberto Garcia Hierro
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alberto-garcia-hierro/id294218713?uo=4>© Alberto Garcia Hierro</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/d4/75/f3/d475f38f-3c5c-f34f-debe-abebaf024334/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19515026/162f9ad8-95f6-11e6-8c58-0c671b7d0cb2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19515026/162f9ad8-95f6-11e6-8c58-0c671b7d0cb2.png)
https://cloud.githubusercontent.com/assets/20930745/19515026/162f9ad8-95f6-11e6-8c58-0c671b7d0cb2.png

https://cloud.githubusercontent.com/assets/20930745/19515026/162f9ad8-95f6-11e6-8c58-0c671b7d0cb2.pnghttps://cloud.githubusercontent.com/assets/20930745/19515055/35f0b852-95f6-11e6-9d83-b2423ea0d9c1.png
