### ISSUE TITLE
Rage Comics : BOX of RAGE

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1838]
**App Name:** Rage Comics : BOX of RAGE
**Bundle ID:** com.them.rage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=470136438">470136438</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rage-comics-box-of-rage/id470136438?mt=8&uo=4">https://itunes.apple.com/us/app/rage-comics-box-of-rage/id470136438?mt=8&uo=4</a>
**App Version:** 7.0
**Seller:** Lukasz Matablewski
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/them-dev/id297991824?uo=4">© theM Dev</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/bc/7e/5c/bc7e5c78-0273-51dd-db9d-10cba83c39a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32397060-38d44ee4-c0e8-11e7-9c44-0a514ad5018a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32397060-38d44ee4-c0e8-11e7-9c44-0a514ad5018a.png)
https://user-images.githubusercontent.com/2068130/32397060-38d44ee4-c0e8-11e7-9c44-0a514ad5018a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32397076-4a00fc62-c0e8-11e7-9319-7982559982b5.png
