### ISSUE TITLE
Cyanide and Happiness : Daily web comics, news, and videos

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1839]
**App Name:** Cyanide and Happiness : Daily web comics, news, and videos
**Bundle ID:** net.explosm.CyanideAndHappiness
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368088267">368088267</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cyanide-happiness-daily-web/id368088267?mt=8&uo=4">https://itunes.apple.com/us/app/cyanide-happiness-daily-web/id368088267?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Derek Miller
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/derek-miller/id682264412?uo=4">© Derek Miller</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/db/37/fe/db37fe0e-64ce-8e7d-251b-01c219041fc7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078463/5cf9bbbc-bf70-11e6-93c3-d0a74c6da740.png)

**Comment by alpcinar** [comment]
Needs update.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078463/5cf9bbbc-bf70-11e6-93c3-d0a74c6da740.png)
https://cloud.githubusercontent.com/assets/2068130/21078463/5cf9bbbc-bf70-11e6-93c3-d0a74c6da740.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21078466/6dad5dce-bf70-11e6-8a7f-f480b495904c.png
