### ISSUE TITLE
PushUps for Beginners - 0 to 100+ Pushups Training

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1840]
**App Name:** PushUps for Beginners - 0 to 100+ Pushups Training
**Bundle ID:** com.Fitnesity.Pushups100
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=573082479">573082479</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pushups-for-beginners-0-to/id573082479?mt=8&uo=4">https://itunes.apple.com/us/app/pushups-for-beginners-0-to/id573082479?mt=8&uo=4</a>
**App Version:** 1.6.1
**Seller:** XIAO DAN LIN
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/xiao-dan-lin/id571827489?uo=4">© XIAO DAN LIN</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/f9/7c/1c/f97c1c88-25ef-65c8-c1d4-311d28797b67/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19920699/9d3733f8-a0da-11e6-97c5-ac3c0b21e48f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19920699/9d3733f8-a0da-11e6-97c5-ac3c0b21e48f.png)
https://cloud.githubusercontent.com/assets/20930745/19920699/9d3733f8-a0da-11e6-97c5-ac3c0b21e48f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19920723/c27ac22e-a0da-11e6-832d-577f1d0daa75.png
