### ISSUE TITLE
Terveystalo Oma Terveys

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1842]
**App Name:** Terveystalo Oma Terveys
**Bundle ID:** com.terveystalo.com.terveystalo.ajanvaraus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438441318">438441318</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/terveystalo-oma-terveys/id438441318?mt=8&uo=4">https://itunes.apple.com/us/app/terveystalo-oma-terveys/id438441318?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Suomen Terveystalo Oy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/suomen-terveystalo-oy/id438441321?uo=4">© Suomen Terveystalo Oy</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/86/4d/81/864d811a-6bf1-7155-f107-0b8b5d1a3ad6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19927036/44f92af2-a0f8-11e6-9969-350648e81eb1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19927036/44f92af2-a0f8-11e6-9969-350648e81eb1.png)
https://cloud.githubusercontent.com/assets/20930745/19927036/44f92af2-a0f8-11e6-9969-350648e81eb1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19927112/9f72f602-a0f8-11e6-9d9f-62e1b18775b7.png
