### ISSUE TITLE
Sit ups: 200 situps abs workout trainer

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1843]
**App Name:** Sit ups: 200 situps abs workout trainer
**Bundle ID:** com.heavydutyapps.SitupsLite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=558505114">558505114</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sit-ups-200-situps-abs-workout-trainer/id558505114?mt=8&uo=4">https://itunes.apple.com/us/app/sit-ups-200-situps-abs-workout-trainer/id558505114?mt=8&uo=4</a>
**App Version:** 7.2
**Seller:** FITNESS22 LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fitness22-ltd/id383171664?uo=4">© FITNESS22 LTD</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/28/3f/ee/283fee63-f7d8-e57f-218e-ba64f1ec7d46/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23334359/e367aae8-fb9c-11e6-8b0f-ff9fe7ebf5c1.png)

**Comment by dreamnet** [comment]
Same as #3834.
