### ISSUE TITLE
McDonald’s Suomi

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1844]
**App Name:** McDonald’s Suomi
**Bundle ID:** com.mcdonaldssuomi.mcdonalds
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=485001525">485001525</a>
**iPhone Icon Name:** McNavigator_114.png
**Icon Names:** McNavigator_57.png | McNavigator_114.png | McNavigator_512.png
**iTunes URL:** https://itunes.apple.com/us/app/mcdonalds-suomi/id485001525?mt=8&uo=4
**App Version:** 2.1.0
**Seller:** McDonald's Oy
**Supported Devices:** iPad3G, iPad2Wifi, iPad23G, iPhone-3GS, iPodTouchThirdGen, iPodTouchourthGen, iPhone4, iPadWifi
**Original Artwork:**
<img src="http://a773.phobos.apple.com/us/r1000/095/Purple/v4/4c/34/c9/4c34c9e1-a069-1b1c-5fb3-b98fd7ebdd31/mzl.einxvegt.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png)

**Comment by Trubbel** [comment]
Updating the icon and source - using same icon as #6021,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png)
https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8761834/c42be2c6-2d66-11e5-99cf-e8c30451ac47.png

**Comment by dreamnet** [comment]
Icon is alread in the repo - no further action needed.
