### ISSUE TITLE
Icomania

### ISSUE THREAD

**Issue by cr0w-69** [glasklart/hd#1845]
**App Name:** Icomania
**Bundle ID:** com.gamesforfriends.icomania
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=608197113">608197113</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/icomania/id608197113?mt=8&uo=4">https://itunes.apple.com/us/app/icomania/id608197113?mt=8&uo=4</a>
**App Version:** 1.8.1
**Seller:** LOTUM media GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lotum-media-gmbh/id515063185?uo=4>© LOTUM media GmbH</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/c5/2a/33/c52a3396-9492-2cff-19b5-baf423160074/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18889888/516ebcf8-84ff-11e6-8275-8641c7132345.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18889888/516ebcf8-84ff-11e6-8275-8641c7132345.png)
https://cloud.githubusercontent.com/assets/20930745/18889888/516ebcf8-84ff-11e6-8275-8641c7132345.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18889907/64115aa0-84ff-11e6-9ea9-92c748ce762a.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18890393/3c11b9b2-8501-11e6-8c7b-4b0e86459192.png)
https://cloud.githubusercontent.com/assets/20930745/18890393/3c11b9b2-8501-11e6-8c7b-4b0e86459192.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18890409/5070be26-8501-11e6-8bdc-dead8f0a1506.png
