### ISSUE TITLE
Easy Note + To Do

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1847]
**App Name:** Easy Note + To Do
**Bundle ID:** com.orangeorapple.notes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382828566">382828566</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/easy-note-+-to-do/id382828566?mt=8&uo=4">https://itunes.apple.com/us/app/easy-note-+-to-do/id382828566?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Ernest Thomason
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/orangeorapple.com/id307840673?uo=4>© OrangeOrApple.com</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/22/60/d8/2260d83c-d6c9-a344-a936-e7212533f73a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411891/34a9b514-930a-11e6-80be-83053095efa2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411891/34a9b514-930a-11e6-80be-83053095efa2.png)
https://cloud.githubusercontent.com/assets/20930745/19411891/34a9b514-930a-11e6-80be-83053095efa2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411892/45006200-930a-11e6-9015-9ebdba998d3e.png
