### ISSUE TITLE
Movie Box 3

### ISSUE THREAD

**Issue by richmFTW** [glasklart/hd#1848]
**App Name:** Movie Box 3
**Bundle ID:** `com.trendico.moviebox3` or `com.sull.videofun`?
**App Version:** 3.6
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/5154986/64ffddfe-7275-11e4-8d54-697277540636.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15083434/6c6a1b68-13cd-11e6-8b6f-0920e0aa8635.png)

**Comment by slipko** [comment]
Looks like this icon name has changed again. Not sure if its AppIcon40x40@2x.png or AppIcon60x60@2x.png

**Comment by dreamnet** [comment]
@slipko Since we are using the IconBundles-method, we don't need the icon name anymore. I need the repo and the version of the app to check.

**Comment by Anuskuss** [comment]
I think the "official" way to download Movie Box is through [vShare](http://www.vshare.com/).

**App Name:** Movie Box
**Bundle ID:** com.sull.videofun
**Version:** 3.6
**iTunes ID:** none (vShare)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/7157389/14944402/4758a1a2-0ff2-11e6-8b2c-86e20dcc1120.PNG" width="150" height="150" />

[@moviebox_app](https://twitter.com/moviebox_app) (official?) says to use the [dtathemes Repo](http://cydia.dtathemes.com/repo), which also provides 3.6 and also uses `com.sull.videofun`.

Lastly I checked the [insanelyi Repository](http://repo.insanelyi.com), which also provides 3.6 and also uses `com.sull.videofun`.

**Comment by Anuskuss** [comment]
I think the "official" (and probably the safest) way to download Movie Box is through [vShare](http://www.vshare.com/).

**App Name:** Movie Box
**Bundle ID:** com.sull.videofun
**Version:** 3.6
**iTunes ID:** none (vShare)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/7157389/14944402/4758a1a2-0ff2-11e6-8b2c-86e20dcc1120.PNG" width="150" height="150" />

[@moviebox_app](https://twitter.com/moviebox_app) (official?) says to use the [dtathemes Repo](http://cydia.dtathemes.com/repo), which also provides 3.6 and also uses `com.sull.videofun`.

Lastly I checked the [insanelyi Repository](http://repo.insanelyi.com), which also provides 3.6 and also uses `com.sull.videofun`.

**Comment by slipko** [comment]
Repo: cydia.dtathemes.com/repo 
Package name: movie box 3
Version: 3.6

**Comment by dreamnet** [comment]
....really not shure about the right bundle ID...

**Comment by Anuskuss** [comment]
@dreamnet Check my comment, I covered all possibilities.
