### ISSUE TITLE
Dialvetica Contacts

### ISSUE THREAD

**Issue by perlagloria** [glasklart/hd#1850]
**App Name:** Dialvetica Contacts
**Bundle ID:** com.mysterioustrousers.dialvetica
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404074258">404074258</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dialvetica-contacts/id404074258?mt=8&uo=4">https://itunes.apple.com/us/app/dialvetica-contacts/id404074258?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** Martin Barnard
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/martin-barnard/id935282476?uo=4>© Martin Barnard</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/8f/7d/ba/8f7dbaf6-60ae-26b6-2a01-73ad2d405b2f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19384034/80064d96-9207-11e6-8c0c-6d4c179fd0ce.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19384034/80064d96-9207-11e6-8c0c-6d4c179fd0ce.png)
https://cloud.githubusercontent.com/assets/20930745/19384034/80064d96-9207-11e6-8c0c-6d4c179fd0ce.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19384052/90fcb37e-9207-11e6-80d2-a25b628ed4e0.png
