### ISSUE TITLE
TimePlay

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1855]
**App Name:** TimePlay
**Bundle ID:** com.timeplay.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=462974334">462974334</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/timeplay/id462974334?mt=8&uo=4">https://itunes.apple.com/us/app/timeplay/id462974334?mt=8&uo=4</a>
**App Version:** 3.5.15616
**Seller:** Big Deal Games Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/timeplay-entertainment/id462974337?uo=4">© TimePlay Entertainment</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/8b/aa/d1/8baad1fc-d169-738f-45c4-9dbbdb0f8759/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19884436/0cea60f6-a01a-11e6-85ae-f030f400273f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19884436/0cea60f6-a01a-11e6-85ae-f030f400273f.png)
https://cloud.githubusercontent.com/assets/20930745/19884436/0cea60f6-a01a-11e6-85ae-f030f400273f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19884462/22c83970-a01a-11e6-826a-32ae0897d4d3.png
