### ISSUE TITLE
Office² Plus

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1858]
**App Name:** Office² Plus
**Bundle ID:** com.bytesquared.office2free
**iTunes ID:** <a href="http://getart.dreamnet.at/?id=353971085">353971085</a>
**iTunes URL:** https://itunes.apple.com/us/app/office2-plus/id353971085?mt=8&uo=4
**App Version:** 5.3.1
**Developer:** <a href="https://itunes.apple.com/us/developer/byte2/id334652358?uo=4">© Byte²</a>
**Seller:** <a href="http://www.quickedit.com/">Byte Squared</a>
**Supported Devices:** all
**Original Artwork:**
<img src="http://a1963.phobos.apple.com/us/r1000/068/Purple/v4/4d/73/2c/4d732cbe-d4dc-bda1-d2cd-52a53209f175/mzm.epvrbzqj.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19013537/ec3b8b7c-87d3-11e6-9a2b-a855d2a9492a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19013537/ec3b8b7c-87d3-11e6-9a2b-a855d2a9492a.png)
https://cloud.githubusercontent.com/assets/20930745/19013537/ec3b8b7c-87d3-11e6-9a2b-a855d2a9492a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19013543/fc76e388-87d3-11e6-8df0-dff60c5fd0da.png
