### ISSUE TITLE
AT&T Connect Mobile

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1859]
**App Name:** AT&T Connect Mobile
**Bundle ID:** com.att.attconnect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=318798264">318798264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/at-t-connect-mobile/id318798264?mt=8&uo=4">https://itunes.apple.com/us/app/at-t-connect-mobile/id318798264?mt=8&uo=4</a>
**App Version:** 11.5.227.2300
**Seller:** AT&T Services, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/at-t-services-inc./id290854684?uo=4>© AT&T Services, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/05/45/81/05458157-cdd9-96a4-30e2-1b7612707133/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19756657/93d09054-9c1e-11e6-9571-b3001a85f5a6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19756657/93d09054-9c1e-11e6-9571-b3001a85f5a6.png)
https://cloud.githubusercontent.com/assets/2068130/19756657/93d09054-9c1e-11e6-9571-b3001a85f5a6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19756669/a1c5602c-9c1e-11e6-957b-cef82dd1d2cc.png
