### ISSUE TITLE
Adobe® Content Viewer

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1860]
**App Name:** Adobe® Content Viewer
**Bundle ID:** com.adobe.digitalContentPreviewTool
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389067418">389067418</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-content-viewer/id389067418?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-content-viewer/id389067418?mt=8&uo=4</a>
**App Version:** 32.6.2
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/f0/0a/58/f00a58b1-284b-d56c-6586-4828ceeeec90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19757703/8fe00cd0-9c24-11e6-93c3-30bf002d3ef1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19757703/8fe00cd0-9c24-11e6-93c3-30bf002d3ef1.png)
https://cloud.githubusercontent.com/assets/2068130/19757703/8fe00cd0-9c24-11e6-93c3-30bf002d3ef1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19757712/9f0476ce-9c24-11e6-9c32-bd1e623190c7.png
