### ISSUE TITLE
Cisco WebEx Meetings

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1861]
**App Name:** Cisco WebEx Meetings
**Bundle ID:** com.webex.meeting
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=298844386">298844386</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cisco-webex-meetings/id298844386?mt=8&uo=4">https://itunes.apple.com/us/app/cisco-webex-meetings/id298844386?mt=8&uo=4</a>
**App Version:** 9.1.3
**Seller:** Cisco
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cisco/id298844389?uo=4>© Cisco</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/cd/45/6d/cd456dbb-7baf-97fe-0c6a-410be7d0f85b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18768428/58b40ad2-8125-11e6-90e2-a3a47589df22.png)

**Comment by Sly-Fi** [comment]
Missing from 5.0.0 release

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18768428/58b40ad2-8125-11e6-90e2-a3a47589df22.png)
https://cloud.githubusercontent.com/assets/20930745/18768428/58b40ad2-8125-11e6-90e2-a3a47589df22.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18768471/a09e120c-8125-11e6-857a-17df070385e7.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Hmmm... OK. 👍
