### ISSUE TITLE
Photo Crop

### ISSUE THREAD

**Issue by bjvivs** [glasklart/hd#1863]
**App Name:** Photo Crop
**Bundle ID:** com.limit-point.Photo-Crop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431136934">431136934</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photo-crop/id431136934?mt=8&uo=4">https://itunes.apple.com/us/app/photo-crop/id431136934?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Limit Point Software
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/limit-point-software/id377981570?uo=4">© Limit Point Software</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/1d/a0/5c/1da05c0b-97f2-3604-2415-8a9027128ff4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19897920/4ef5e6e2-a05a-11e6-8d71-a0c1b467d6df.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19897920/4ef5e6e2-a05a-11e6-8d71-a0c1b467d6df.png)
https://cloud.githubusercontent.com/assets/20930745/19897920/4ef5e6e2-a05a-11e6-8d71-a0c1b467d6df.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19897958/6d9c0a9a-a05a-11e6-9d70-7f9b84c10537.png
