### ISSUE TITLE
Quilt

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1867]
**App Name:** Quilt
**Bundle ID:** com.nerdswaggerinc.quillt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=473933362">473933362</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quilt/id473933362?mt=8&uo=4">https://itunes.apple.com/us/app/quilt/id473933362?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Nerd Swagger, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nerd-swagger-inc./id473933365?uo=4>© Nerd Swagger Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/99/50/c5/9950c54e-9cf0-09e2-db80-7c262baa04b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19857499/28791cc8-9f7e-11e6-9cbd-c5d6954a5705.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19857499/28791cc8-9f7e-11e6-9cbd-c5d6954a5705.png)
https://cloud.githubusercontent.com/assets/20930745/19857499/28791cc8-9f7e-11e6-9cbd-c5d6954a5705.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19857524/435a74ba-9f7e-11e6-97af-92fcaf509812.png
