### ISSUE TITLE
AppTrailers

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1868]
**App Name:** AppTrailers
**Bundle ID:** com.apptrailers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469489347">469489347</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/apptrailers/id469489347?mt=8&uo=4">https://itunes.apple.com/us/app/apptrailers/id469489347?mt=8&uo=4</a>
**App Version:** 5.9
**Seller:** AppRedeem, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appredeem-inc./id416894674?uo=4>© AppRedeem, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/d0/c1/16/d0c11679-7c9d-43fe-ca71-c0204a6ee019/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19738255/fcab1648-9bb6-11e6-860c-813b3b8f232e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19738255/fcab1648-9bb6-11e6-860c-813b3b8f232e.png)
https://cloud.githubusercontent.com/assets/2068130/19738255/fcab1648-9bb6-11e6-860c-813b3b8f232e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19738263/0c6e0f22-9bb7-11e6-986f-30423279ad2b.png
