### ISSUE TITLE
iKörkort

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#187]
**App Name:** iKörkort
**Bundle ID:** com.boboshi.ikorkort
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=356462130">356462130</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ikorkort/id356462130?mt=8&uo=4">https://itunes.apple.com/us/app/ikorkort/id356462130?mt=8&uo=4</a>
**App Version:** 3.2.7
**Seller:** Boboshi Applikationer & Import Handelsbolag
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/boboshi/id356462133?uo=4>© Boboshi</a>
**Supported Devices:** iPhone5c, iPodTouchFourthGen, iPadThirdGen4G, iPhone5s, iPhone-3GS, iPhone4S, iPadFourthGen4G, iPadMini, iPadThirdGen, iPhone6Plus, iPad2Wifi, iPhone6, iPad23G, iPadFourthGen, iPadMini4G, iPhone4, iPhone5, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/00/da/45/00da45c8-9a6a-16d4-d30d-df2061f49440/mzl.fmxixqkf.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8729083/47e09816-2be9-11e5-8f9d-968fd9008cfd.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8729083/47e09816-2be9-11e5-8f9d-968fd9008cfd.png)
https://cloud.githubusercontent.com/assets/10730122/8729083/47e09816-2be9-11e5-8f9d-968fd9008cfd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8729072/3f7d699c-2be9-11e5-8570-f68418399d15.png
