### ISSUE TITLE
PhotoShake!

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1870]
**App Name:** PhotoShake!
**Bundle ID:** com.motion1.photoshake
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389104355">389104355</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photoshake/id389104355?mt=8&uo=4">https://itunes.apple.com/us/app/photoshake/id389104355?mt=8&uo=4</a>
**App Version:** 3.2.5
**Seller:** MotionOne.co.Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/motionone-co-ltd/id389104358?uo=4">© MotionOne.co.Ltd</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple62/v4/9d/ee/11/9dee119d-6598-db55-cd22-58eded7d2390/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38434886-43dba204-39d0-11e8-8ab7-139b3d7eeb7d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38434886-43dba204-39d0-11e8-8ab7-139b3d7eeb7d.png)
https://user-images.githubusercontent.com/2068130/38434886-43dba204-39d0-11e8-8ab7-139b3d7eeb7d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38434903-530271c2-39d0-11e8-8c20-cd837592689f.png
