### ISSUE TITLE
City Video

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1871]
**App Name:** City Video
**Bundle ID:** com.rogers.CitytvVideo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390492092">390492092</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/city-video/id390492092?mt=8&uo=4">https://itunes.apple.com/ca/app/city-video/id390492092?mt=8&uo=4</a>
**App Version:** 3.6
**Seller:** Rogers Media
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/developer/rogers-media/id313847071?uo=4>© Rogers Media</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/68/4f/94/684f9407-15b0-1f65-f6ff-b5b5ebd70e49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420657/67225488-93f0-11e6-8cb7-b49df6421043.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420657/67225488-93f0-11e6-8cb7-b49df6421043.png)
https://cloud.githubusercontent.com/assets/20930745/19420657/67225488-93f0-11e6-8cb7-b49df6421043.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19420663/83a840ae-93f0-11e6-81e6-e28eb059559e.png
