### ISSUE TITLE
CTV

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1872]
**App Name:** CTV
**Bundle ID:** ca.ctv.ctvipadapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=461749483">461749483</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/ca/app/ctv/id461749483?uo=4">https://apps.apple.com/ca/app/ctv/id461749483?uo=4</a>
**App Version:** 3.11.25
**Seller:** Bell Media Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/ca/developer/bell-media-inc/id328082347?uo=4">© Bell Media Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/2b/92/7a/2b927a97-6786-b9a8-d34e-00f3711d4d94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60371881-00286880-99fb-11e9-88b7-6cdc40114086.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23334039/352da9a0-fb97-11e6-818b-46a2b493005b.png)
https://cloud.githubusercontent.com/assets/2068130/23334039/352da9a0-fb97-11e6-818b-46a2b493005b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23334046/43dea29c-fb97-11e6-93e5-9d757d33b870.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60371881-00286880-99fb-11e9-88b7-6cdc40114086.png)
https://user-images.githubusercontent.com/20930745/60371881-00286880-99fb-11e9-88b7-6cdc40114086.png

Source:
https://user-images.githubusercontent.com/20930745/60371882-01599580-99fb-11e9-9756-5197f1035b84.png
