### ISSUE TITLE
Map My Tracks -GPS cycling walking running tracker

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1873]
**App Name:** Map My Tracks -GPS cycling walking running tracker
**Bundle ID:** com.mapmytracks.outfrontfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=396649707">396649707</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/map-my-tracks-gps-cycling/id396649707?mt=8&uo=4">https://itunes.apple.com/us/app/map-my-tracks-gps-cycling/id396649707?mt=8&uo=4</a>
**App Version:** 4.7.1
**Seller:** Tinderhouse
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tinderhouse/id347858533?uo=4>© Tinderhouse</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/13/d5/99/13d5992f-726e-55b4-a353-be17e9a1847e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418621/f9dfb7d0-93c7-11e6-8918-5a34bc204835.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418621/f9dfb7d0-93c7-11e6-8918-5a34bc204835.png)
https://cloud.githubusercontent.com/assets/20930745/19418621/f9dfb7d0-93c7-11e6-8918-5a34bc204835.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19418623/085b0f80-93c8-11e6-81a1-c4879be12795.png
