### ISSUE TITLE
Heart Rate Zones by Runners Ally

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1874]
**App Name:** Heart Rate Zones by Runners Ally
**Bundle ID:** HZXJKKPCU6
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=400167924">400167924</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/heart-rate-zones-by-runners/id400167924?mt=8&uo=4">https://itunes.apple.com/us/app/heart-rate-zones-by-runners/id400167924?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Andrew Wayman
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/andrew-wayman/id377593147?uo=4">© Andrew Wayman</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/7f/8f/59/7f8f59cd-22f7-842c-7948-52cb6a787a5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20222213/b9d3ba70-a834-11e6-950b-8b4dde5225f9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20222213/b9d3ba70-a834-11e6-950b-8b4dde5225f9.png)
https://cloud.githubusercontent.com/assets/20930745/20222213/b9d3ba70-a834-11e6-950b-8b4dde5225f9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20222247/d195425a-a834-11e6-9823-20fff4e0263c.png
