### ISSUE TITLE
CoachMyRide : a cycling training coach in your pocket

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1875]
**App Name:** CoachMyRide : a cycling training coach in your pocket
**Bundle ID:** com.domsware.coachmyride
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431480256">431480256</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/coachmyride-a-cycling-training-coach-in-your-pocket/id431480256?mt=8&uo=4">https://itunes.apple.com/us/app/coachmyride-a-cycling-training-coach-in-your-pocket/id431480256?mt=8&uo=4</a>
**App Version:** 1.4.4
**Seller:** Dominique Vial
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/domsware/id431480259?uo=4">© Domsware</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/93/26/74/932674b1-a66e-4e98-144c-95bbe0ae5363/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25782915/2ce4cf0a-3353-11e7-8acb-6e6c196f8669.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25782915/2ce4cf0a-3353-11e7-8acb-6e6c196f8669.png)
https://cloud.githubusercontent.com/assets/2068130/25782915/2ce4cf0a-3353-11e7-8acb-6e6c196f8669.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25782916/3b7fa850-3353-11e7-90f6-d34dfc1dff50.png
