### ISSUE TITLE
Bike Hub Cycle Journey planner

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1879]
**App Name:** Bike Hub Cycle Journey planner
**Bundle ID:** com.bikehub.journeyplanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391782662">391782662</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bike-hub-cycle-journey-planner/id391782662?mt=8&uo=4">https://itunes.apple.com/us/app/bike-hub-cycle-journey-planner/id391782662?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** BICYCLE ASSOCIATION OF GREAT BRITAIN LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bike-hub/id391446268?uo=4>© Bike Hub</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/d2/c5/c1/d2c5c148-21bf-402d-057f-3fd9fa401245/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19855003/720ea972-9f72-11e6-882a-a5a36abe9515.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19855003/720ea972-9f72-11e6-882a-a5a36abe9515.png)
https://cloud.githubusercontent.com/assets/20930745/19855003/720ea972-9f72-11e6-882a-a5a36abe9515.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19855024/8f876d54-9f72-11e6-8021-416fdacb2b04.png
