### ISSUE TITLE
Cycle Hire London for Santander Cycles

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1881]
**App Name:** Cycle Hire London for Santander Cycles
**Bundle ID:** com.cyclehireapp.CycleHire
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=362285538">362285538</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cycle-hire-london-for-santander/id362285538?mt=8&uo=4">https://itunes.apple.com/us/app/cycle-hire-london-for-santander/id362285538?mt=8&uo=4</a>
**App Version:** 7.1
**Seller:** Alexandros Baxevanis
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alexander-baxevanis/id362285541?uo=4>© Alexander Baxevanis</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/cf/48/e4/cf48e40d-e1dd-5e64-eab6-eba103a09de9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420608/07bf7cb0-93ef-11e6-93b1-17e95bd81e05.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420608/07bf7cb0-93ef-11e6-93b1-17e95bd81e05.png)
https://cloud.githubusercontent.com/assets/20930745/19420608/07bf7cb0-93ef-11e6-93b1-17e95bd81e05.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19420614/29023872-93ef-11e6-82bb-13df85f06955.png
