### ISSUE TITLE
myCols

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1882]
**App Name:** myCols
**Bundle ID:** com.hardfietsen.icols
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327326925">327326925</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mycols/id327326925?mt=8&uo=4">https://itunes.apple.com/us/app/mycols/id327326925?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** G Brugmans
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sander-brugmans/id304127042?uo=4">© Sander Brugmans</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/d2/d5/52/d2d55248-316e-89e3-501e-ca121423ed04/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35765312-558e9bae-08c1-11e8-97b6-8aefe8cc8216.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35765312-558e9bae-08c1-11e8-97b6-8aefe8cc8216.png)
https://user-images.githubusercontent.com/20930745/35765312-558e9bae-08c1-11e8-97b6-8aefe8cc8216.png

Source:
https://user-images.githubusercontent.com/20930745/35765320-706f990a-08c1-11e8-8005-daa69c696dec.png
