### ISSUE TITLE
TideApp

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#1884]
**App Name:** TideApp
**Bundle ID:** com.atlantistech.TideApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288399415">288399415</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tideapp/id288399415?mt=8&uo=4">https://itunes.apple.com/us/app/tideapp/id288399415?mt=8&uo=4</a>
**App Version:** 4.1.3
**Seller:** Atlantis Technology
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/atlantis-technology/id288399418?uo=4>© Atlantis Technology</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/d9/10/51/d91051ca-b93a-e02e-f4dd-dec20da3e0fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419524/c980b62c-93d9-11e6-8f20-db4ddea4e2f2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419524/c980b62c-93d9-11e6-8f20-db4ddea4e2f2.png)
https://cloud.githubusercontent.com/assets/20930745/19419524/c980b62c-93d9-11e6-8f20-db4ddea4e2f2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19419535/ffd31f12-93d9-11e6-8d51-4b25f0636ec8.png
