### ISSUE TITLE
Temple Run: Oz

### ISSUE THREAD

**Issue by montring** [glasklart/hd#1885]
**App Name:** Temple Run: Oz
**Bundle ID:** com.disney.TempleRunOz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=595831580">595831580</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/temple-run-oz/id595831580?mt=8&uo=4">https://itunes.apple.com/us/app/temple-run-oz/id595831580?mt=8&uo=4</a>
**App Version:** 1.7.0
**Seller:** Disney Electronic Content, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/disney/id284888248?mt=8&uo=4">© Disney</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/f5/11/ef/f511efe6-5b67-62c7-2604-030509742831/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23332338/815505ae-fb78-11e6-82a3-2a91776597ac.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23332338/815505ae-fb78-11e6-82a3-2a91776597ac.png)
https://cloud.githubusercontent.com/assets/2068130/23332338/815505ae-fb78-11e6-82a3-2a91776597ac.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23332344/8fc46440-fb78-11e6-80a6-bbe99fe176c8.png
