### ISSUE TITLE
Wordox The Word Snatcher

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1890]
**App Name:** Wordox The Word Snatcher
**Bundle ID:** com.iscoolentertainment.wordoxfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=582340397">582340397</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wordox-the-word-snatcher/id582340397?mt=8&uo=4">https://itunes.apple.com/us/app/wordox-the-word-snatcher/id582340397?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** IsCool Entertainment
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iscool-entertainment/id567562644?uo=4>© IsCool Entertainment</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/3f/41/91/3f41916c-dc34-1434-5064-f9ac2c7b9ff7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19357168/b791ba6c-9170-11e6-846a-1c0ad0f9e8d3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19357168/b791ba6c-9170-11e6-846a-1c0ad0f9e8d3.png)
https://cloud.githubusercontent.com/assets/20930745/19357168/b791ba6c-9170-11e6-846a-1c0ad0f9e8d3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19357179/c5eae232-9170-11e6-966d-3094617c6e55.png
