### ISSUE TITLE
Mad Libs

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1895]
**App Name:** Mad Libs
**Bundle ID:** com.pearson.penguin.youngreaders.madlibs.Lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=326885152">326885152</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mad-libs/id326885152?mt=8&uo=4">https://itunes.apple.com/us/app/mad-libs/id326885152?mt=8&uo=4</a>
**App Version:** 3.2.1
**Seller:** Pearson PLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/penguin-group-usa/id297541127?uo=4>© Penguin Group USA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/c8/bc/71/c8bc7174-de2f-0576-4af0-88d9d3cb9877/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19898884/2d501978-a05e-11e6-83ce-9afd81793dd9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19898884/2d501978-a05e-11e6-83ce-9afd81793dd9.png)
https://cloud.githubusercontent.com/assets/20930745/19898884/2d501978-a05e-11e6-83ce-9afd81793dd9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19898915/469908ae-a05e-11e6-8c7d-38bd54ac1c19.png
