### ISSUE TITLE
imo free video calls and chat

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#19]
**App Name:** imo free video calls and chat
**Bundle ID:** imoimiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336435697">336435697</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/imo-free-video-calls-and-chat/id336435697?mt=8&uo=4">https://itunes.apple.com/us/app/imo-free-video-calls-and-chat/id336435697?mt=8&uo=4</a>
**App Version:** 6.8.4
**Seller:** imo.im
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/imo.im/id336435700?uo=4>© imo.im</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/83/3a/3d/833a3d7d-054f-0a80-00ad-4ead4c510c8a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12767278/95e1df3a-ca08-11e5-9cc6-4f4e24bbe26d.png)

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12767278/95e1df3a-ca08-11e5-9cc6-4f4e24bbe26d.png)
https://cloud.githubusercontent.com/assets/10730122/12767278/95e1df3a-ca08-11e5-9cc6-4f4e24bbe26d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12767277/95dfd046-ca08-11e5-8c2e-6a31eaab96e4.png
