### ISSUE TITLE
FlickPig

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1900]
**App Name:** FlickPig
**Bundle ID:** com.iprope.3Pigs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=463249899">463249899</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flickpig/id463249899?mt=8&uo=4">https://itunes.apple.com/us/app/flickpig/id463249899?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** PROPE Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/prope/id317081659?uo=4">© PROPE</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple4/v4/11/4d/a0/114da0ca-8392-873a-0e8a-e4327b3bdd9b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39489517-17c30a08-4d86-11e8-8f2b-d86bf171abe0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39489517-17c30a08-4d86-11e8-8f2b-d86bf171abe0.png)
https://user-images.githubusercontent.com/2068130/39489517-17c30a08-4d86-11e8-8f2b-d86bf171abe0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39489532-27e721a8-4d86-11e8-9998-984cf00568c4.png
