### ISSUE TITLE
OLO game

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1902]
**App Name:** OLO game
**Bundle ID:** com.Sennep.OLOgame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=529826126">529826126</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/olo-game/id529826126?mt=8&uo=4">https://itunes.apple.com/us/app/olo-game/id529826126?mt=8&uo=4</a>
**App Version:** 1.65
**Seller:** Sennep
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sennep/id476538073?uo=4>© Sennep</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/14/85/25/14852515-5910-4fd2-0590-812908703f16/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19383169/670b7b3a-9203-11e6-862e-f14eccfd78be.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19383169/670b7b3a-9203-11e6-862e-f14eccfd78be.png)
https://cloud.githubusercontent.com/assets/20930745/19383169/670b7b3a-9203-11e6-862e-f14eccfd78be.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19383214/875e9480-9203-11e6-9d8a-25a22f71a685.png
