### ISSUE TITLE
Wordament

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1904]
**App Name:** Wordament
**Bundle ID:** com.microsoft.wordament
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=580935508">580935508</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wordament/id580935508?mt=8&uo=4">https://itunes.apple.com/us/app/wordament/id580935508?mt=8&uo=4</a>
**App Version:** 2.8.3
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4">© Microsoft Corporation</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/89/a9/8f/89a98fd5-8fa5-2271-c11c-bd76024afa43/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19855272/e6e58968-9f73-11e6-8ffb-d5c8b0c891b8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19855272/e6e58968-9f73-11e6-8ffb-d5c8b0c891b8.png)
https://cloud.githubusercontent.com/assets/20930745/19855272/e6e58968-9f73-11e6-8ffb-d5c8b0c891b8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19855290/03b4cd06-9f74-11e6-95b6-e577e94df216.png
