### ISSUE TITLE
Caisse d'Epargne

### ISSUE THREAD

**Issue by Achell** [glasklart/hd#1908]
**App Name:** Caisse d'Epargne
**Bundle ID:** fr.caisse-epargne.dem
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=402753249">402753249</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/caisse-depargne/id402753249?mt=8&uo=4">https://itunes.apple.com/us/app/caisse-depargne/id402753249?mt=8&uo=4</a>
**App Version:** 3.8.7
**Seller:** BPCE
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bpce/id393823359?uo=4>© BPCE</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/25/4c/9a/254c9aef-036a-b53b-683f-e67001d812c0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19287137/cfc29e10-9000-11e6-84ca-bbecab08909a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19287137/cfc29e10-9000-11e6-84ca-bbecab08909a.png)
https://cloud.githubusercontent.com/assets/20930745/19287137/cfc29e10-9000-11e6-84ca-bbecab08909a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19287152/df993330-9000-11e6-97ff-b8fe175c3324.png
