### ISSUE TITLE
Full Fitness : Exercise Workout Trainer

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#191]
**App Name:** Full Fitness : Exercise Workout Trainer
**Bundle ID:** net.healthxperts.ifitness.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=536049508">536049508</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/full-fitness-exercise-workout/id536049508?mt=8&uo=4">https://itunes.apple.com/us/app/full-fitness-exercise-workout/id536049508?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Mehrdad Mehrain
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mehrdad-mehrain/id536049511?uo=4>© Mehrdad Mehrain</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/88/34/e8/8834e8be-f1b0-28e7-c502-1fc4fa4401d4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19401644/b6c94ca2-925c-11e6-8918-164016d514d5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19401644/b6c94ca2-925c-11e6-8918-164016d514d5.png)
https://cloud.githubusercontent.com/assets/20930745/19401644/b6c94ca2-925c-11e6-8918-164016d514d5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19401650/c4f0f474-925c-11e6-9ff7-8bfd6dda3864.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19401644/b6c94ca2-925c-11e6-8918-164016d514d5.png)
https://cloud.githubusercontent.com/assets/20930745/19401644/b6c94ca2-925c-11e6-8918-164016d514d5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19401650/c4f0f474-925c-11e6-9ff7-8bfd6dda3864.png
