### ISSUE TITLE
Garfield's Defense: Attack of the Food Invaders

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1911]
**App Name:** Garfield's Defense: Attack of the Food Invaders
**Bundle ID:** com.webprancer.itunes.garfieldDefense
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540660863">540660863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/garfields-defense-attack-of-the-food-invaders/id540660863?mt=8&uo=4">https://itunes.apple.com/us/app/garfields-defense-attack-of-the-food-invaders/id540660863?mt=8&uo=4</a>
**App Version:** 1.9.1
**Seller:** Cosmos Epoch Investments Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/web-prancer/id503762845?uo=4">© Web Prancer</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple127/v4/fc/c9/9c/fcc99cec-b6dc-d73a-4043-9b165e3e0892/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32985419-9f9e4354-ccba-11e7-9359-7923857aaf77.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32985419-9f9e4354-ccba-11e7-9359-7923857aaf77.png)
https://user-images.githubusercontent.com/2068130/32985419-9f9e4354-ccba-11e7-9359-7923857aaf77.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32985423-ae8ffc72-ccba-11e7-8f10-3c9967381eb6.png
