### ISSUE TITLE
AdopteUnMec

### ISSUE THREAD

**Issue by Achell** [glasklart/hd#1919]
**App Name:** AdopteUnMec
**Bundle ID:** com.adopteunmec.iphonefr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405049280">405049280</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ch/app/adopteunmec/id405049280?mt=8&uo=4">https://itunes.apple.com/ch/app/adopteunmec/id405049280?mt=8&uo=4</a>
**App Version:** 3.7.2
**Seller:** AdopteUnMec
**Developer:** <a target="_blank" href=https://itunes.apple.com/ch/developer/geb-adoptaguy/id405049283?uo=4>© GEB AdoptAGuy</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/93/4e/c6/934ec6cb-738e-6c60-4060-abbedc91cb35/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19491795/91faee9c-9574-11e6-8b12-bf51b04c63f2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19491795/91faee9c-9574-11e6-8b12-bf51b04c63f2.png)
https://cloud.githubusercontent.com/assets/20930745/19491795/91faee9c-9574-11e6-8b12-bf51b04c63f2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19491842/b250757c-9574-11e6-8666-3492b299f279.png
