### ISSUE TITLE
Cap'Cinéma

### ISSUE THREAD

**Issue by Achell** [glasklart/hd#1920]
**App Name:** Cap'Cinéma
**Bundle ID:** fr.cotecine.capcinema
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406943420">406943420</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/capcinema/id406943420?mt=8&uo=4">https://itunes.apple.com/us/app/capcinema/id406943420?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** cote cine
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cote-cine/id379252479?uo=4>© Côté Ciné</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/c5/87/72/c5877244-79bd-3dac-d31b-67e0c425b885/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19625189/075688fe-9912-11e6-9da8-105d2044d447.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19625189/075688fe-9912-11e6-9da8-105d2044d447.png)
https://cloud.githubusercontent.com/assets/2068130/19625189/075688fe-9912-11e6-9da8-105d2044d447.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19625193/1578904e-9912-11e6-948a-97416ffdf783.png
