### ISSUE TITLE
L’EQUIPE, toute l’actualité du sport en direct.

### ISSUE THREAD

**Issue by Achell** [glasklart/hd#1922]
**App Name:** L’EQUIPE, toute l’actualité du sport en direct.
**Bundle ID:** fr.airweb.EFR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=318133983">318133983</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lequipe-toute-lactualite-du/id318133983?mt=8&uo=4">https://itunes.apple.com/us/app/lequipe-toute-lactualite-du/id318133983?mt=8&uo=4</a>
**App Version:** 7.1.6
**Seller:** L'Equipe 24/24
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lequipe-24-24/id318133986?uo=4>© L'Equipe 24/24</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/91/cd/bd/91cdbdce-8413-77db-1aae-c2dfa8417160/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19456649/c631ff46-94c2-11e6-8532-dba01c6232ce.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19456649/c631ff46-94c2-11e6-8532-dba01c6232ce.png)
https://cloud.githubusercontent.com/assets/20930745/19456649/c631ff46-94c2-11e6-8532-dba01c6232ce.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19456702/f1ba84a8-94c2-11e6-80a0-140bf2604504.png
