### ISSUE TITLE
Infinity Field

### ISSUE THREAD

**Issue by thethomaszhou** [glasklart/hd#1923]
**App Name:** Infinity Field
**Bundle ID:** com.chillingo.infinityfieldiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444451242">444451242</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/infinity-field/id444451242?mt=8&uo=4">https://itunes.apple.com/us/app/infinity-field/id444451242?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Chillingo Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chillingo-ltd/id286038741?uo=4">© Chillingo Ltd</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/ab/d9/52/abd9528c-db69-7f45-e56c-531013020688/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19859111/6df1feea-9f84-11e6-999f-123c0e39e8b9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19859111/6df1feea-9f84-11e6-999f-123c0e39e8b9.png)
https://cloud.githubusercontent.com/assets/20930745/19859111/6df1feea-9f84-11e6-999f-123c0e39e8b9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19859128/85cb28ca-9f84-11e6-88b6-9713c9086a76.png
