### ISSUE TITLE
Programme TV Télé Loisirs

### ISSUE THREAD

**Issue by Achell** [glasklart/hd#1924]
**App Name:** Programme TV Télé Loisirs
**Bundle ID:** com.prisma-presse.teleloisirs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454988262">454988262</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/programme-tv-tele-loisirs/id454988262?mt=8&uo=4">https://itunes.apple.com/us/app/programme-tv-tele-loisirs/id454988262?mt=8&uo=4</a>
**App Version:** 7.0.1
**Seller:** Prisma Presse
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/prisma-media/id371682181?uo=4>© Prisma Media</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/54/ca/23/54ca2371-ad14-e5b2-5ab4-4a7e3d79beef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19897253/a3cef922-a057-11e6-9fbd-f14472894c92.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19897253/a3cef922-a057-11e6-9fbd-f14472894c92.png)
https://cloud.githubusercontent.com/assets/20930745/19897253/a3cef922-a057-11e6-9fbd-f14472894c92.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19897267/b9513f12-a057-11e6-99b3-a917dc21eeb3.png
