### ISSUE TITLE
Logos Bible: Designed for deeper Bible study

### ISSUE THREAD

**Issue by DavidMorton** [glasklart/hd#1928]
**App Name:** Logos Bible: Designed for deeper Bible study
**Bundle ID:** com.logos.ilogos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336400266">336400266</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/logos-bible-designed-for-deeper/id336400266?mt=8&uo=4">https://itunes.apple.com/us/app/logos-bible-designed-for-deeper/id336400266?mt=8&uo=4</a>
**App Version:** 5.6.2
**Seller:** Faithlife Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/faithlife-corporation/id336400269?uo=4>© Faithlife Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/86/e4/48/86e448f0-d06a-b928-ff3d-9d5adbd51dd1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19230181/68a8bbc0-8ed3-11e6-9d93-355e8a257148.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19230181/68a8bbc0-8ed3-11e6-9d93-355e8a257148.png)
https://cloud.githubusercontent.com/assets/20930745/19230181/68a8bbc0-8ed3-11e6-9d93-355e8a257148.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19230195/804cc258-8ed3-11e6-8de7-6a1739fbdf81.png
