### ISSUE TITLE
Alarm.com

### ISSUE THREAD

**Issue by DavidMorton** [glasklart/hd#1931]
**App Name:** Alarm.com
**Bundle ID:** com.alarm.Alarm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=315010649">315010649</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alarm.com/id315010649?mt=8&uo=4">https://itunes.apple.com/us/app/alarm.com/id315010649?mt=8&uo=4</a>
**App Version:** 3.2.6
**Seller:** Alarm.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alarm.com/id315010652?uo=4>© Alarm.com</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/f0/8e/78/f08e780b-c4f2-5ed6-3e9f-b3a60147feb7/mzl.obganniw.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10083655/b7f471b6-62ff-11e5-8c1c-fdca288a6347.png)

**Comment by l8er4now** [comment]
Can we do an updated icon? The one that is in the current inventory still has the background glow.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10083655/b7f471b6-62ff-11e5-8c1c-fdca288a6347.png)
https://cloud.githubusercontent.com/assets/2068130/10083655/b7f471b6-62ff-11e5-8c1c-fdca288a6347.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10083671/c6ba6dcc-62ff-11e5-861b-fac8f1f865a6.png
