### ISSUE TITLE
HAR.com Texas Real Estate - Houston

### ISSUE THREAD

**Issue by DavidMorton** [glasklart/hd#1932]
**App Name:** HAR.com Texas Real Estate - Houston
**Bundle ID:** com.har.houstonrealestate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386981161">386981161</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/har.com-texas-real-estate/id386981161?mt=8&uo=4">https://itunes.apple.com/us/app/har.com-texas-real-estate/id386981161?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** Houston Association of Realtors
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/houston-association-realtors/id386981164?uo=4>© Houston Association of Realtors®</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/21/71/05/21710514-3a22-9c1b-f505-1060a0624f91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18847828/f122c278-842b-11e6-9eee-21b720a69f9d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18847828/f122c278-842b-11e6-9eee-21b720a69f9d.png)
https://cloud.githubusercontent.com/assets/2068130/18847828/f122c278-842b-11e6-9eee-21b720a69f9d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18847844/0032a9e0-842c-11e6-961c-8f43c778c2cf.png
