### ISSUE TITLE
Battery Doctor - Master of Battery Maintenance

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#1940]
**App Name:** Battery Doctor - Master of Battery Maintenance
**Bundle ID:** com.ijinshan.beijing.kbatterydoctor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446751279">446751279</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/battery-doctor-master-battery/id446751279?mt=8&uo=4">https://itunes.apple.com/us/app/battery-doctor-master-battery/id446751279?mt=8&uo=4</a>
**App Version:** 7.4.3
**Seller:** Beijing Kingsoft Internet Security software Co.Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/beijing-kingsoft-internet/id438883151?uo=4>© Beijing Kingsoft Internet Security software Co.Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/45/8a/9d/458a9d4d-fa86-04ee-b3af-01bc62e6f57d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18721178/9131622a-802f-11e6-83b2-3290b201ab12.png)

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18721178/9131622a-802f-11e6-83b2-3290b201ab12.png)
https://cloud.githubusercontent.com/assets/20930745/18721178/9131622a-802f-11e6-83b2-3290b201ab12.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18721214/bb29d224-802f-11e6-9491-511a58e6187a.png
