### ISSUE TITLE
THX tune-up™

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1950]
**App Name:** THX tune-up™
**Bundle ID:** com.thx.app.ios.tuneup
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=592624594">592624594</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/thx-tune-up/id592624594?mt=8&uo=4">https://itunes.apple.com/us/app/thx-tune-up/id592624594?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** THX Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/thx-ltd/id592624597?uo=4">© THX Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple122/v4/e1/b2/05/e1b205b2-804c-2cfc-d54e-4c4e6a84942b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39956980-63251708-55eb-11e8-9b7d-dfec1fa84151.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39956980-63251708-55eb-11e8-9b7d-dfec1fa84151.png)
https://user-images.githubusercontent.com/2068130/39956980-63251708-55eb-11e8-9b7d-dfec1fa84151.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39956986-71a1808c-55eb-11e8-978c-0ba852589fa1.png
