### ISSUE TITLE
ReittiGPS (Reittiopas Journey Planner)

### ISSUE THREAD

**Issue by mrsmiggins** [glasklart/hd#1955]
**App Name:** ReittiGPS (Reittiopas Journey Planner)
**Bundle ID:** fi.iki.mhalttu.ReittiGPS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=290859824">290859824</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reittigps-reittiopas-journey/id290859824?mt=8&uo=4">https://itunes.apple.com/us/app/reittigps-reittiopas-journey/id290859824?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** Essentia Solutions Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/essentia-solutions-oy/id290859827?uo=4>© Essentia Solutions Oy</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/7d/5b/92/7d5b9255-599f-1906-f734-f8400486e92f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411789/43bbdfe8-9308-11e6-9af9-6a2a649dcf92.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411789/43bbdfe8-9308-11e6-9af9-6a2a649dcf92.png)
https://cloud.githubusercontent.com/assets/20930745/19411789/43bbdfe8-9308-11e6-9af9-6a2a649dcf92.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411797/53975208-9308-11e6-87d4-8046d98199ba.png
