### ISSUE TITLE
ARTE.tv

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#196]
**App Name:** ARTE.tv
**Bundle ID:** tv.arte.plus7
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405028510">405028510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/arte.tv/id405028510?mt=8&uo=4">https://itunes.apple.com/us/app/arte.tv/id405028510?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** ARTE G.E.I.E.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/arte.tv/id379981515?uo=4>© ARTE.TV</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/10/83/5a/10835a88-9938-f31b-6ead-3d128447ebf5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18450826/e19f9c6a-7934-11e6-88ad-efd6763fc2d5.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**App Name:** ARTE.tv
**Bundle ID:** tv.arte.plus7
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405028510">405028510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/arte.tv/id405028510?mt=8&uo=4">https://itunes.apple.com/us/app/arte.tv/id405028510?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** ARTE G.E.I.E.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/arte.tv/id379981515?uo=4>© ARTE.TV</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/10/83/5a/10835a88-9938-f31b-6ead-3d128447ebf5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18450826/e19f9c6a-7934-11e6-88ad-efd6763fc2d5.png)
https://cloud.githubusercontent.com/assets/20930745/18450826/e19f9c6a-7934-11e6-88ad-efd6763fc2d5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18450857/032e87a6-7935-11e6-8841-8456a5e93002.png
