### ISSUE TITLE
Shanghai Mahjong Lite

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#1963]
**App Name:** Shanghai Mahjong Lite
**Bundle ID:** com.mobileage.shanghai.demo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288963447">288963447</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shanghai-mahjong-lite/id288963447?mt=8&uo=4">https://itunes.apple.com/us/app/shanghai-mahjong-lite/id288963447?mt=8&uo=4</a>
**App Version:** 1.6.4
**Seller:** MobileAge, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mobileage/id283619402?uo=4>© MobileAge</a>
**Supported Devices:** iPhone6Plus, iPhone4, iPadWifi, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPad2Wifi, iPad3G, iPad23G, iPod-touch, iPadThirdGen4G, iPadMini, iPodTouchThirdGen, iPadMini4G, iPhone-3GS, iPadThirdGen, iPhone5s, iPhone, iPod-touch-with-mic, iPhone4S, iPhone5, iPhone-3G, iPhone5c, iPhone6, iPodTouchFourthGen
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/7334775/6f001c5a-eb9d-11e4-86d1-31795eb6b205.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7334768/0b0be170-eb9d-11e4-81ee-bb5f7d1228b9.png)

**Comment by ivanov007** [comment]
@dreamnet this one needs to be updated too

**Comment by dreamnet** [comment]
@ivanov007 Oh yeah, I missed that. THX!
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7334768/0b0be170-eb9d-11e4-81ee-bb5f7d1228b9.png)
https://cloud.githubusercontent.com/assets/2068130/7334768/0b0be170-eb9d-11e4-81ee-bb5f7d1228b9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7334769/1f0d799a-eb9d-11e4-86bd-bf88125b6256.png
