### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#1964]
**App Name:** Bridge
**Bundle ID:**  de.j-gessner.bridge
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://f.cloud.github.com/assets/2068964/294170/0fdaa140-93da-11e2-8b47-000891d197cb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11011106/29bec79a-84e5-11e5-89e8-b4e9c50954d7.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11011106/29bec79a-84e5-11e5-89e8-b4e9c50954d7.png)
https://cloud.githubusercontent.com/assets/10730122/11011106/29bec79a-84e5-11e5-89e8-b4e9c50954d7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11011103/26bf6c48-84e5-11e5-954d-6c1ec281ef78.png
