### ISSUE TITLE
Green Day's Official App

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#1965]
**App Name:** Green Day's Official App
**Bundle ID:** com.wbr.greendaymr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=546871577">546871577</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/green-days-official-app/id546871577?mt=8&uo=4">https://itunes.apple.com/us/app/green-days-official-app/id546871577?mt=8&uo=4</a>
**App Version:** 5.4.2
**Seller:** Warner Music Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/warner-music-group/id320700137?uo=4">© Warner Music Group</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/cd/46/55/cd465599-0182-e337-6a4b-4f2ffbda68eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19854262/689860f8-9f6e-11e6-8f95-1e680e0b49d2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19854262/689860f8-9f6e-11e6-8f95-1e680e0b49d2.png)
https://cloud.githubusercontent.com/assets/20930745/19854262/689860f8-9f6e-11e6-8f95-1e680e0b49d2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19854289/83fe9d4e-9f6e-11e6-9116-b3c24970196c.png
