### ISSUE TITLE
Pixlr - Photo Collages, Effect

### ISSUE THREAD

**Issue by AjMedina04** [glasklart/hd#1974]
**App Name:** Pixlr - Photo Collages, Effect
**Bundle ID:** com.autodesk.ios.pixlrexpressplus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526783584">526783584</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pixlr-photo-collages-effect/id526783584?mt=8&uo=4">https://itunes.apple.com/us/app/pixlr-photo-collages-effect/id526783584?mt=8&uo=4</a>
**App Version:** 3.3.4
**Seller:** 123RF Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/123rf-limited/id570913810?uo=4">© 123RF Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/3f/c6/cb/3fc6cb4a-d76b-bdbb-d797-2ed0c2609052/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39385860-541b3b7c-4a72-11e8-9424-d9697b79ed62.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39385860-541b3b7c-4a72-11e8-9424-d9697b79ed62.png)
https://user-images.githubusercontent.com/2068130/39385860-541b3b7c-4a72-11e8-9424-d9697b79ed62.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39385892-63f0763e-4a72-11e8-9927-883f33f11414.png
