### ISSUE TITLE
Lapse It Pro • Time Lapse & Stop Motion Camera • Professional HD

### ISSUE THREAD

**Issue by AjMedina04** [glasklart/hd#1975]
**App Name:** Lapse It Pro • Time Lapse & Stop Motion Camera • Professional HD
**Bundle ID:** net.interactiveuniverse.LapseItPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=536495161">536495161</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lapse-it-pro-time-lapse-stop/id536495161?mt=8&uo=4">https://itunes.apple.com/us/app/lapse-it-pro-time-lapse-stop/id536495161?mt=8&uo=4</a>
**App Version:** 2.52
**Seller:** Mauricio Rubio
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/interactive-universe/id536495164?uo=4">© Interactive Universe</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/6b/5c/2f/6b5c2fa2-20b4-5e48-25f6-50b902a63022/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19883311/e8e353ee-a013-11e6-99e0-995ca4adae26.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19883311/e8e353ee-a013-11e6-99e0-995ca4adae26.png)
https://cloud.githubusercontent.com/assets/20930745/19883311/e8e353ee-a013-11e6-99e0-995ca4adae26.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19883330/ffe99f08-a013-11e6-9a88-dc34cf268db2.png
