### ISSUE TITLE
Mina fordon

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#1976]
**App Name:** Mina fordon
**Bundle ID:** se.Transportstyrelsen.minafordon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=518582338">518582338</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mina-fordon/id518582338?mt=8&uo=4">https://itunes.apple.com/us/app/mina-fordon/id518582338?mt=8&uo=4</a>
**App Version:** 1.93.1662
**Seller:** Transportstyrelsen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/transportstyrelsen/id518582341?uo=4>© Transportstyrelsen</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/a7/2a/80/a72a80fa-33ac-3943-44d1-36f562100253/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420507/016a08e6-93ed-11e6-9ffd-0848333ae39b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420507/016a08e6-93ed-11e6-9ffd-0848333ae39b.png)
https://cloud.githubusercontent.com/assets/20930745/19420507/016a08e6-93ed-11e6-9ffd-0848333ae39b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19420511/22fc720a-93ed-11e6-8575-f2d6f3e131d8.png
