### ISSUE TITLE
McDonald’s Germany

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#1980]
**App Name:** McDonald’s Germany
**Bundle ID:** de.mcdonalds.McDonaldsInfoApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=524943492">524943492</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mcdonalds-germany/id524943492?mt=8&uo=4">https://itunes.apple.com/us/app/mcdonalds-germany/id524943492?mt=8&uo=4</a>
**App Version:** 1.5.3
**Seller:** McDonald's Deutschland Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mcdonalds-deutschland/id524943495?uo=4>© McDonald's Deutschland</a>
**Supported Devices:** iPad2Wifi, iPodTouchSixthGen, iPodTouchFourthGen, iPhone6Plus, iPadFourthGen4G, iPadMini, iPadThirdGen4G, iPad23G, iPhone4S, iPodTouchFifthGen, iPhone6, iPadMini4G, iPadFourthGen, iPhone-3GS, iPhone4, iPadThirdGen, iPhone5s, iPhone5c, iPhone5
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/56/69/06/56690632-3ccc-b073-465f-6eaf7baf9504/mzl.zqxpqwcx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png)

**Comment by Trubbel** [comment]
Updating the icon and source - using same icon as #6021,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png)
https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8761834/c42be2c6-2d66-11e5-99cf-e8c30451ac47.png

**Comment by dreamnet** [comment]
Icon is alread in the repo - no further action needed.
