### ISSUE TITLE
Strut

### ISSUE THREAD

**Issue by q2r5** [glasklart/hd#1981]
**App Name:** Strut
**Bundle ID:** com.thickpolicy.strut
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606686716">606686716</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/strut/id606686716?mt=8&uo=4">https://itunes.apple.com/us/app/strut/id606686716?mt=8&uo=4</a>
**App Version:** 3.3.0
**Seller:** Thickpolicy LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/thickpolicy-llc/id374216102?uo=4">© Thickpolicy LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple19/v4/2f/cc/e9/2fcce967-702c-670e-0443-7f59aa0b1eb4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20465099/f8e0160a-af55-11e6-8a3a-3500ae99205f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20465099/f8e0160a-af55-11e6-8a3a-3500ae99205f.png)
https://cloud.githubusercontent.com/assets/2068130/20465099/f8e0160a-af55-11e6-8a3a-3500ae99205f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20465104/06a84e42-af56-11e6-8f54-42629fc45f8d.png
