### ISSUE TITLE
Mango Lite - Free IRC Chat client

### ISSUE THREAD

**Issue by q2r5** [glasklart/hd#1982]
**App Name:** Mango Lite - Free IRC Chat client
**Bundle ID:** sk.mediaware.mangolite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=449136259">449136259</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mango-lite-free-irc-chat-client/id449136259?mt=8&uo=4">https://itunes.apple.com/us/app/mango-lite-free-irc-chat-client/id449136259?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** Pavel Kanzelsberger
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pavel-kanzelsberger/id399288546?uo=4">© Pavel Kanzelsberger</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/10/a9/cf/10a9cf02-07ec-d0ba-967b-965e082dd5e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19903496/34fd7a1a-a06f-11e6-89fc-17ad11a3a16f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19903496/34fd7a1a-a06f-11e6-89fc-17ad11a3a16f.png)
https://cloud.githubusercontent.com/assets/20930745/19903496/34fd7a1a-a06f-11e6-89fc-17ad11a3a16f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19903550/4b91286c-a06f-11e6-85d4-69e9291b0969.png
