### ISSUE TITLE
SitUps to Six Pack - 0 to 200+ SitUps Training

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1986]
**App Name:** SitUps to Six Pack - 0 to 200+ SitUps Training
**Bundle ID:** com.Fitnesity.Situps200
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=573084863">573084863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/situps-to-six-pack-0-to-200+/id573084863?mt=8&uo=4">https://itunes.apple.com/us/app/situps-to-six-pack-0-to-200+/id573084863?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** XIAO DAN LIN
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/xiao-dan-lin/id571827489?uo=4>© XIAO DAN LIN</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple4/v4/45/a7/35/45a73514-8f93-afcf-c190-fdce1206cce7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19896016/3256a1ea-a053-11e6-90a3-01aa5be3e441.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19896016/3256a1ea-a053-11e6-90a3-01aa5be3e441.png)
https://cloud.githubusercontent.com/assets/20930745/19896016/3256a1ea-a053-11e6-90a3-01aa5be3e441.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19896054/4f241b36-a053-11e6-82bb-c617ad53b114.png
