### ISSUE TITLE
Alkometri

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1989]
**App Name:** Alkometri
**Bundle ID:** com.didstopia.alkometri
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469353148">469353148</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alkometri/id469353148?mt=8&uo=4">https://itunes.apple.com/us/app/alkometri/id469353148?mt=8&uo=4</a>
**App Version:** 2.0.4
**Seller:** Didstopia
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/didstopia/id379028611?uo=4>© Didstopia</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/09/e6/35/09e6356f-64b8-303d-db17-af1543fcdbb5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411162/96bcdc62-92fc-11e6-8d87-2e8fccce5a83.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411162/96bcdc62-92fc-11e6-8d87-2e8fccce5a83.png)
https://cloud.githubusercontent.com/assets/20930745/19411162/96bcdc62-92fc-11e6-8d87-2e8fccce5a83.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411165/a7cfedf0-92fc-11e6-82c9-7a86246e0032.png
