### ISSUE TITLE
france.tv : direct et replay

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#199]
**App Name:** france.tv : direct et replay
**Bundle ID:** fr.francetv.apps.pluzz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=428835098">428835098</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/fr/app/france-tv-direct-et-replay/id428835098?uo=4">https://apps.apple.com/fr/app/france-tv-direct-et-replay/id428835098?uo=4</a>
**App Version:** 8.6.1
**Seller:** FRANCE TELEVISIONS
**Developer:** <a target="_blank" href="https://apps.apple.com/fr/developer/france-t%C3%A9l%C3%A9visions/id348684700?uo=4">© France Télévisions</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/86/30/ec/8630ecee-b424-30c6-eec8-0bb5ad116436/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60395035-ae342f80-9b2d-11e9-88f1-503945ce83c7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19838642/42414dc4-9ed4-11e6-9af6-1ff6092365b5.png)
https://cloud.githubusercontent.com/assets/20930745/19838642/42414dc4-9ed4-11e6-9af6-1ff6092365b5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19838644/56ef5b80-9ed4-11e6-898d-597ecff7d970.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60395035-ae342f80-9b2d-11e9-88f1-503945ce83c7.png)
https://user-images.githubusercontent.com/2068130/60395035-ae342f80-9b2d-11e9-88f1-503945ce83c7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60395037-bbe9b500-9b2d-11e9-9558-e1064fe1869f.png
