### ISSUE TITLE
Kotikokki

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1991]
**App Name:** Kotikokki
**Bundle ID:** net.kotikokki.kotikokkiclient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=460923610">460923610</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kotikokki/id460923610?mt=8&uo=4">https://itunes.apple.com/us/app/kotikokki/id460923610?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Kustannusosakeyhtio Iltalehti Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iltalehti.fi/id403688090?uo=4>© Iltalehti.fi</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/a9/b2/ba/a9b2ba21-37bb-3cbc-835d-4a009a3f5711/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19491005/b9dd1d2a-9571-11e6-813a-3ddf34ce84e4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19491005/b9dd1d2a-9571-11e6-813a-3ddf34ce84e4.png)
https://cloud.githubusercontent.com/assets/20930745/19491005/b9dd1d2a-9571-11e6-813a-3ddf34ce84e4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19491052/d93a4094-9571-11e6-86b5-a5ceca9f14c8.png
