### ISSUE TITLE
Promillekoll

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1992]
**App Name:** Promillekoll
**Bundle ID:** com.systembolaget.promillekoll
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=560080672">560080672</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/promillekoll/id560080672?mt=8&uo=4">https://itunes.apple.com/us/app/promillekoll/id560080672?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Systembolaget AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/systembolaget-ab/id486802431?uo=4>© Systembolaget AB</a>
**Supported Devices:** iPhone-3GS, iPadThirdGen4G, iPhone5, iPhone4, iPadFourthGen4G, iPodTouchSixthGen, iPhone5c, iPadMini, iPhone6, iPadFourthGen, iPad23G, iPadMini4G, iPodTouchFifthGen, iPodTouchFourthGen, iPhone4S, iPhone5s, iPadThirdGen, iPad2Wifi, iPhone6Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/30/69/fd/3069fda3-c45b-b950-d139-600e1cab4f37/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9570801/d3547fac-4f93-11e5-833f-fba214b5b981.png)

**Comment by Trubbel** [comment]
Updating the icon plus source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9570801/d3547fac-4f93-11e5-833f-fba214b5b981.png)
https://cloud.githubusercontent.com/assets/10730122/9570801/d3547fac-4f93-11e5-833f-fba214b5b981.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9570800/d03e70e8-4f93-11e5-81a8-a05315590c95.png
