### ISSUE TITLE
Viiniopas

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1993]
**App Name:** Viiniopas
**Bundle ID:** com.monexp.viiniopas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=356413800">356413800</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/viiniopas/id356413800?mt=8&uo=4">https://itunes.apple.com/us/app/viiniopas/id356413800?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Monkey Experience Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/monkey-experience-oy/id356413804?uo=4>© Monkey Experience Oy</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/58/6e/ef/586eefcb-09bf-c329-9c78-bfbf979009c5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411318/c9c91dc0-92ff-11e6-9adb-59c73d42ed05.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411318/c9c91dc0-92ff-11e6-9adb-59c73d42ed05.png)
https://cloud.githubusercontent.com/assets/20930745/19411318/c9c91dc0-92ff-11e6-9adb-59c73d42ed05.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411322/d8949f82-92ff-11e6-81bb-fd6b0b320fe3.png
