### ISSUE TITLE
Valio Reseptit

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#1994]
**App Name:** Valio Reseptit
**Bundle ID:** fi.valio.ValioReseptit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=449564341">449564341</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/valio-reseptit/id449564341?mt=8&uo=4">https://itunes.apple.com/us/app/valio-reseptit/id449564341?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Valio Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/valio/id449564344?uo=4>© Valio</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/37/62/35/37623596-7528-b4e6-b4b4-70306d52bdef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19310834/50f60e64-908c-11e6-8042-4a47595ae927.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19310834/50f60e64-908c-11e6-8042-4a47595ae927.png)
https://cloud.githubusercontent.com/assets/20930745/19310834/50f60e64-908c-11e6-8042-4a47595ae927.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19310881/83ba1d5e-908c-11e6-99ab-5c7587819cd9.png
