### ISSUE TITLE
SHARE NOW (car2go & DriveNow)

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#1996]
**App Name:** SHARE NOW (car2go & DriveNow)
**Bundle ID:** com.car2go.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514921710">514921710</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/share-now-car2go-drivenow/id514921710?uo=4">https://apps.apple.com/us/app/share-now-car2go-drivenow/id514921710?uo=4</a>
**App Version:** 4.38.1
**Seller:** car2go Group GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/car2go-group-gmbh/id1090349369?uo=4">© car2go Group GmbH</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple115/v4/21/ad/d4/21add4d9-a2de-2405-44ed-2a3c5ffb1f53/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120079786-d29c3c00-c0b5-11eb-8526-092b09557153.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18845930/f7b5aaea-8423-11e6-9575-a0640917bbad.png)
https://cloud.githubusercontent.com/assets/2068130/18845930/f7b5aaea-8423-11e6-9575-a0640917bbad.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18845944/072d262e-8424-11e6-907b-027360be7659.png

**Comment by chrismarino84** [comment]
**App Name:** SHARE NOW (car2go & DriveNow)
**Bundle ID:** com.car2go.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514921710">514921710</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/share-now-car2go-drivenow/id514921710?uo=4">https://apps.apple.com/us/app/share-now-car2go-drivenow/id514921710?uo=4</a>
**App Version:** 4.37.0
**Seller:** car2go Group GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/car2go-group-gmbh/id1090349369?uo=4">© car2go Group GmbH</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/aa/eb/30/aaeb300d-9e29-378f-0f07-7f72bd21e534/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

new logo

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/120079786-d29c3c00-c0b5-11eb-8526-092b09557153.png)
https://user-images.githubusercontent.com/2068130/120079786-d29c3c00-c0b5-11eb-8526-092b09557153.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/120079801-e6e03900-c0b5-11eb-9f77-72576df0997a.png
