### ISSUE TITLE
Minecraft – Pocket Edition

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#1998]
**App Name:** Minecraft: Pocket Edition
**Bundle ID:** com.mojang.minecraftpe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479516143">479516143</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minecraft-pocket-edition/id479516143?mt=8&uo=4">https://itunes.apple.com/us/app/minecraft-pocket-edition/id479516143?mt=8&uo=4</a>
**App Version:** 0.15.2
**Seller:** Mojang AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mojang/id479516146?uo=4>© Mojang</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/72/23/a6/7223a6e6-a0e8-6d62-caa1-16d15b524858/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18409820/4a330f5e-7751-11e6-9be1-22314cf7dfee.png)

**Comment by Anuskuss** [comment]
Remake?

**Comment by 2Qt2beStr8** [comment]
... only a try .. i used a better icon from the www

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18409820/4a330f5e-7751-11e6-9be1-22314cf7dfee.png)
https://cloud.githubusercontent.com/assets/20930745/18409820/4a330f5e-7751-11e6-9be1-22314cf7dfee.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18409809/0d992fec-7751-11e6-8311-acea298af886.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Taken!
