### ISSUE TITLE
Find My Friends

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#2]
**App Name:** Find My Friends
**Bundle ID:** com.apple.mobileme.fmf1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=466122094">466122094</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/find-my-friends/id466122094?mt=8&uo=4">https://itunes.apple.com/us/app/find-my-friends/id466122094?mt=8&uo=4</a>
**App Version:** 7.0
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/75/87/3d/75873d24-3a62-9fbe-4196-4e16289adc17/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31318852-faf2ca86-ac58-11e7-9bfe-87f85373e7ec.png)

**Comment by Anuskuss** [comment]
@no0mar Could you make the border a bit thicker?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14769581/f66d7484-0a5b-11e6-9a7a-d8d8977cff96.png)
https://cloud.githubusercontent.com/assets/2068130/14769581/f66d7484-0a5b-11e6-9a7a-d8d8977cff96.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14769587/07907ba8-0a5c-11e6-9d09-f0a2bce50e4a.png

**Comment by Anuskuss** [comment]
@dreamnet Thanks :wink:

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31318852-faf2ca86-ac58-11e7-9bfe-87f85373e7ec.png)
https://user-images.githubusercontent.com/2068130/31318852-faf2ca86-ac58-11e7-9bfe-87f85373e7ec.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31318857-0a5311de-ac59-11e7-8eac-509ff3efd00e.png
