### ISSUE TITLE
TeamViewer for Remote Control

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#20]
**App Name:** TeamViewer for Remote Control
**Bundle ID:** com.teamviewer.teamviewer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=357069581">357069581</a>
**iPhone Icon Name:** Icon@2x.png
**Icon Names:** Icon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/teamviewer-for-remote-control/id357069581?mt=8&uo=4
**App Version:** 8.0.10095
**Seller:** TeamViewer GmbH
**Supported Devices:** all
**Original Artwork:**
<img src="http://a1717.phobos.apple.com/us/r1000/075/Purple2/v4/37/2b/27/372b27c2-d251-2ce2-a95c-9e0168f10226/mzl.bbynhjya.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://f.cloud.github.com/assets/3090247/405982/0c0a06e6-aa37-11e2-8c1d-43c163e4ccc0.png)

**Comment by PolarisBeaver** [comment]
I think the duplicate issue "detector" is not picking this up, but I'll add it here anyway just in case since I know there was a previous icon. Might want to take a look into whether Teamviewer changed any app IDs or anything, and if a new issue needs to be opened, let me know.

**Comment by PolarisBeaver** [comment]
**App Name:** TeamViewer: Remote Control
**Bundle ID:** com.teamviewer.rc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=692035811">692035811</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/teamviewer-remote-control/id692035811?mt=8&uo=4">https://itunes.apple.com/us/app/teamviewer-remote-control/id692035811?mt=8&uo=4</a>
**App Version:** 10.0.37492
**Seller:** TeamViewer GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/teamviewer/id357051969?uo=4>© TeamViewer</a>
**Supported Devices:** iPad2Wifi, iPodTouchThirdGen, iPodTouchFourthGen, iPhone-3GS, iPadMini4G, iPadThirdGen, iPadFourthGen4G, iPad3G, iPhone5c, iPadFourthGen, iPadThirdGen4G, iPadWifi, iPadMini, iPodTouchFifthGen, iPad23G, iPhone5s, iPhone6, iPhone4, iPhone5, iPhone4S, iPhone6Plus
**Original Artwork:**
<img src="http://a612.phobos.apple.com/us/r30/Purple3/v4/c5/db/2a/c5db2a17-9f5b-31f6-36ba-cfe1c4f3a565/mzl.lbddtebp.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6072526/96129464-ad57-11e4-962a-36f19ca38403.png)
https://cloud.githubusercontent.com/assets/10394552/6072526/96129464-ad57-11e4-962a-36f19ca38403.png


Source File: https://cloud.githubusercontent.com/assets/10394552/6072523/8da4c6a8-ad57-11e4-95c2-8ee24f99c8ec.png

**Comment by ivanov007** [comment]
@PolarisBeaver thaks for noticing :+1:

**Comment by dreamnet** [comment]
This app dosen't seem to exist anymore. I remove the icon.
