### ISSUE TITLE
NRJ Radio

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#200]
**App Name:** NRJ Radio
**Bundle ID:** fr.nrj.NRJ
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=298596830">298596830</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nrj-radio/id298596830?mt=8&uo=4">https://itunes.apple.com/us/app/nrj-radio/id298596830?mt=8&uo=4</a>
**App Version:** 5.2.1
**Seller:** E-NRJ
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/e-nrj/id298596833?uo=4>© E-NRJ</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/e3/71/d6/e371d671-f558-75d2-2d43-4124b5ccb08a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19838736/a9201754-9ed5-11e6-9571-e30639bbe46e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19838736/a9201754-9ed5-11e6-9571-e30639bbe46e.png)
https://cloud.githubusercontent.com/assets/20930745/19838736/a9201754-9ed5-11e6-9571-e30639bbe46e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19838745/d036fc68-9ed5-11e6-9620-f46cd46011a0.png
