### ISSUE TITLE
Sleep Time : Sleep Cycle Smart Alarm Clock Tracker, Insights Analysis, Better Soundscape

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2001]
**App Name:** Sleep Time : Sleep Cycle Smart Alarm Clock Tracker, Insights Analysis, Better Soundscape
**Bundle ID:** com.azumio.iphone.sleepcycle.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555564825">555564825</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sleep-time-sleep-cycle-smart/id555564825?mt=8&uo=4">https://itunes.apple.com/us/app/sleep-time-sleep-cycle-smart/id555564825?mt=8&uo=4</a>
**App Version:** 5.28
**Seller:** Azumio Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/azumio-inc./id439290207?mt=8&uo=4>© Azumio Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/9e/b4/7d/9eb47dbb-f9c4-a9b4-60a4-3c1087d50cce/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19012841/d96e2ac6-87c0-11e6-8045-3e27caf970ca.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19012841/d96e2ac6-87c0-11e6-8045-3e27caf970ca.png)
https://cloud.githubusercontent.com/assets/2068130/19012841/d96e2ac6-87c0-11e6-8045-3e27caf970ca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19012845/e78a8bae-87c0-11e6-874d-3a14292ef91f.png
