### ISSUE TITLE
Sleep Time+ : Sleep Cycle Smart Alarm Clock, Sleep Tracker with Sleep Cycle Analysis and Soundscapes for Better Sleep

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2002]
**App Name:** Sleep Time+ : Sleep Cycle Smart Alarm Clock, Sleep Tracker with Sleep Cycle Analysis and Soundscapes for Better Sleep
**Bundle ID:** com.azumio.iphone.sleepcycle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498360026">498360026</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sleep-time+-sleep-cycle-smart/id498360026?mt=8&uo=4">https://itunes.apple.com/us/app/sleep-time+-sleep-cycle-smart/id498360026?mt=8&uo=4</a>
**App Version:** 5.28
**Seller:** Azumio Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/azumio-inc./id439290207?mt=8&uo=4>© Azumio Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/52/a7/27/52a72781-ca87-2f33-7f1e-051e7c044a8a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19012841/d96e2ac6-87c0-11e6-8045-3e27caf970ca.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19012841/d96e2ac6-87c0-11e6-8045-3e27caf970ca.png)
https://cloud.githubusercontent.com/assets/2068130/19012841/d96e2ac6-87c0-11e6-8045-3e27caf970ca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19012845/e78a8bae-87c0-11e6-874d-3a14292ef91f.png
