### ISSUE TITLE
Choice Hotels

### ISSUE THREAD

**Issue by kennatken** [glasklart/hd#2006]
**App Name:** Choice Hotels
**Bundle ID:** com.choicehotels.iosapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=509342785">509342785</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/choice-hotels/id509342785?uo=4">https://apps.apple.com/us/app/choice-hotels/id509342785?uo=4</a>
**App Version:** 4.52.2
**Seller:** Choice Hotels International, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/choice-hotels-international/id509342788?uo=4">© Choice Hotels International</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a1/0d/c7/a10dc7d5-9a17-deac-d056-31271ca26346/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60372057-9b214280-99fb-11e9-82b8-225850062b8f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19850832/f2278556-9f5a-11e6-9077-18a3a3882966.png)
https://cloud.githubusercontent.com/assets/20930745/19850832/f2278556-9f5a-11e6-9077-18a3a3882966.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19850849/0ce817e8-9f5b-11e6-8d57-cf20922b72a9.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60372057-9b214280-99fb-11e9-82b8-225850062b8f.png)
https://user-images.githubusercontent.com/20930745/60372057-9b214280-99fb-11e9-82b8-225850062b8f.png

Source:
https://user-images.githubusercontent.com/20930745/60372088-b429f380-99fb-11e9-9565-d6477b9a7c0b.png
