### ISSUE TITLE
Interlocked

### ISSUE THREAD

**Issue by kennatken** [glasklart/hd#2007]
**App Name:** Interlocked
**Bundle ID:** com.wecreatestuff.ag.Interlocked
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=554072547">554072547</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/interlocked/id554072547?mt=8&uo=4">https://itunes.apple.com/us/app/interlocked/id554072547?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Armor Games Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/armor-games-inc/id286413135?uo=4">© Armor Games Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/ce/10/49/ce104948-752e-05be-e6e0-8bac4ad3b16a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23334206/5050e078-fb9a-11e6-99c6-984facae9c8b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23334206/5050e078-fb9a-11e6-99c6-984facae9c8b.png)
https://cloud.githubusercontent.com/assets/2068130/23334206/5050e078-fb9a-11e6-99c6-984facae9c8b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23334210/5fcba8f8-fb9a-11e6-9df1-2aa3f452c7cc.png
