### ISSUE TITLE
PNC Finder

### ISSUE THREAD

**Issue by kennatken** [glasklart/hd#2009]
**App Name:** PNC Finder
**Bundle ID:** com.pnc.finder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=474763805">474763805</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pnc-finder/id474763805?mt=8&uo=4">https://itunes.apple.com/us/app/pnc-finder/id474763805?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** PNC Bank, N.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pnc-bank-n.a./id303113130?uo=4>© PNC Bank, N.A.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/3f/36/e6/3f36e67c-ebbf-fcc4-ad81-299bdf16839f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19739317/cc75eda0-9bba-11e6-902c-bc99583fc741.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19739317/cc75eda0-9bba-11e6-902c-bc99583fc741.png)
https://cloud.githubusercontent.com/assets/2068130/19739317/cc75eda0-9bba-11e6-902c-bc99583fc741.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19739339/dac0766e-9bba-11e6-8875-6749523b2a3c.png
