### ISSUE TITLE
Jungle Disk

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2010]
**App Name:** Jungle Disk
**Bundle ID:** com.jungledisk.jdtouch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=359523081">359523081</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jungle-disk/id359523081?mt=8&uo=4">https://itunes.apple.com/us/app/jungle-disk/id359523081?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Jungle Disk, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jungle-disk-llc/id359523084?uo=4">© Jungle Disk, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/0f/87/58/0f8758ab-da76-24ed-a961-9820cddc3ff1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19883617/92104cf0-a015-11e6-9576-fd57bca22a2c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19883617/92104cf0-a015-11e6-9576-fd57bca22a2c.png)
https://cloud.githubusercontent.com/assets/20930745/19883617/92104cf0-a015-11e6-9576-fd57bca22a2c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19883636/aa31b530-a015-11e6-82a4-6494fed7a63c.png
