### ISSUE TITLE
Livedrive Mobile

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2012]
**App Name:** Livedrive Mobile
**Bundle ID:** com.livedrive.navldrive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338236137">338236137</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/livedrive-mobile/id338236137?mt=8&uo=4">https://itunes.apple.com/us/app/livedrive-mobile/id338236137?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Livedrive Internet Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/livedrive/id338236140?uo=4">© Livedrive</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/ed/d2/43/edd243ca-0a1e-8271-7549-b84a6971beed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20109546/d806aa1c-a5e0-11e6-8e10-3affd5c8fa9c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20109546/d806aa1c-a5e0-11e6-8e10-3affd5c8fa9c.png)
https://cloud.githubusercontent.com/assets/20930745/20109546/d806aa1c-a5e0-11e6-8e10-3affd5c8fa9c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20109586/06a9c886-a5e1-11e6-90e4-1b47c81c22f3.png
