### ISSUE TITLE
Motivo Cycling - Turbo Training and Indoor Cycling Workouts

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2015]
**App Name:** Motivo Cycling - Turbo Training and Indoor Cycling Workouts
**Bundle ID:** MotivoLimited.Motivo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=578208463">578208463</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/motivo-cycling-turbo-training/id578208463?mt=8&uo=4">https://itunes.apple.com/us/app/motivo-cycling-turbo-training/id578208463?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Motivo Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/motivo/id578208466?uo=4>© Motivo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/e8/8c/62/e88c623d-5e3f-cec8-d39c-b700040b0c98/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19455079/f2e53d66-94bb-11e6-97f5-4b366ae86d5f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19455079/f2e53d66-94bb-11e6-97f5-4b366ae86d5f.png)
https://cloud.githubusercontent.com/assets/20930745/19455079/f2e53d66-94bb-11e6-97f5-4b366ae86d5f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19455113/18134f24-94bc-11e6-9c53-d871b291935c.png
