### ISSUE TITLE
IMB Magazine

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2017]
**App Name:** IMB Magazine
**Bundle ID:** IMBIKEMAG
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=531377640">531377640</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/imb-magazine/id531377640?uo=4">https://apps.apple.com/us/app/imb-magazine/id531377640?uo=4</a>
**App Version:** 2.4.2
**Seller:** Next Element Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/next-element-ltd/id521813792?uo=4">© Next Element Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/96/05/f7/9605f7e8-dfef-dc13-bcb0-abd806433a80/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62399584-9d3b6b80-b57c-11e9-9888-0b964b3fc49b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19455431/499d10ec-94bd-11e6-8fb7-0c94f8991481.png)
https://cloud.githubusercontent.com/assets/20930745/19455431/499d10ec-94bd-11e6-8fb7-0c94f8991481.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19455466/6bf0073a-94bd-11e6-9bad-2ab860c85700.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62399584-9d3b6b80-b57c-11e9-9888-0b964b3fc49b.png)
https://user-images.githubusercontent.com/2068130/62399584-9d3b6b80-b57c-11e9-9888-0b964b3fc49b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62399607-adebe180-b57c-11e9-9504-85f2d1aded27.png
