### ISSUE TITLE
Lloyds TSB Mobile Banking

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2019]
**App Name:** Lloyds Bank Mobile Banking
**Bundle ID:** com.lloydstsb.LloydsTSB
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469964520">469964520</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lloyds-bank-mobile-banking/id469964520?mt=8&uo=4">https://itunes.apple.com/us/app/lloyds-bank-mobile-banking/id469964520?mt=8&uo=4</a>
**App Version:** 13.2
**Seller:** Lloyds TSB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lloyds-banking-group/id469964523?uo=4>© Lloyds Banking Group</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/10/6f/cf/106fcfe2-8765-dea5-44f6-1aec7c04409f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18814683/4a9726ee-831b-11e6-89c2-3dab5c37dc73.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18814683/4a9726ee-831b-11e6-89c2-3dab5c37dc73.png)
https://cloud.githubusercontent.com/assets/2068130/18814683/4a9726ee-831b-11e6-89c2-3dab5c37dc73.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18814687/5875b9ba-831b-11e6-803f-3fd107ed3fe3.png
