### ISSUE TITLE
BUDGT - monthly finances, day by day

### ISSUE THREAD

**Issue by Mobilpadde** [glasklart/hd#2022]
**App Name:** BUDGT - monthly finances, day by day
**Bundle ID:** ch.sflueckiger.BUDGT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=580812126">580812126</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/budgt-monthly-finances-day/id580812126?mt=8&uo=4">https://itunes.apple.com/us/app/budgt-monthly-finances-day/id580812126?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** Sebastian Flückiger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/s.-fluckiger/id427419066?uo=4>© S. Flückiger</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/e8/15/60/e8156039-2c56-cfbf-00fc-4ec1b9822682/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411136/a8fda2d6-92fb-11e6-88f2-94f055337b67.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411136/a8fda2d6-92fb-11e6-88f2-94f055337b67.png)
https://cloud.githubusercontent.com/assets/20930745/19411136/a8fda2d6-92fb-11e6-88f2-94f055337b67.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411143/bed1af26-92fb-11e6-88c3-683c575fd3f3.png
