### ISSUE TITLE
Mobilbank DK - Danske Bank

### ISSUE THREAD

**Issue by Mobilpadde** [glasklart/hd#2023]
**App Name:** Mobilbank DK - Danske Bank
**Bundle ID:** danskebankgroup.mobilebank.danskebank
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388423462">388423462</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobilbank-dk-danske-bank/id388423462?mt=8&uo=4">https://itunes.apple.com/us/app/mobilbank-dk-danske-bank/id388423462?mt=8&uo=4</a>
**App Version:** 3.14.1
**Seller:** Danske Bank Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/danske-bank-group/id388423465?uo=4>© Danske Bank Group</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/69/f1/02/69f1021c-cb85-e8a8-e024-d5ed0b2ad4d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411725/2e8c26e2-9307-11e6-8246-7089ab598046.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411725/2e8c26e2-9307-11e6-8246-7089ab598046.png)
https://cloud.githubusercontent.com/assets/20930745/19411725/2e8c26e2-9307-11e6-8246-7089ab598046.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411734/3ccaf0bc-9307-11e6-839d-f055e3eef559.png
