### ISSUE TITLE
gTar

### ISSUE THREAD

**Issue by Mobilpadde** [glasklart/hd#2024]
**App Name:** gTar
**Bundle ID:** com.incidenttech.gtarplay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438739702">438739702</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gtar/id438739702?mt=8&uo=4">https://itunes.apple.com/us/app/gtar/id438739702?mt=8&uo=4</a>
**App Version:** 1.5.8
**Seller:** Incident Technologies Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/incident-technologies/id438739705?uo=4>© Incident Technologies</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/dc/85/02/dc85024c-7031-67d1-f9c5-d2292f0f6b91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411267/c522864a-92fe-11e6-8297-71d7e42ebdf9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411267/c522864a-92fe-11e6-8297-71d7e42ebdf9.png)
https://cloud.githubusercontent.com/assets/20930745/19411267/c522864a-92fe-11e6-8297-71d7e42ebdf9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411272/d69e7ab4-92fe-11e6-8242-3bc6afa92822.png
