### ISSUE TITLE
Mein A1

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2027]
**App Name:** Mein A1
**Bundle ID:** at.a1telekom.meina1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=410017894">410017894</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/mein-a1/id410017894?mt=8&uo=4">https://itunes.apple.com/gb/app/mein-a1/id410017894?mt=8&uo=4</a>
**App Version:** 5.0.11
**Seller:** A1 Telekom Austria AG
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/a1-telekom-austria-ag/id365712725?uo=4">© A1 Telekom Austria AG</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/dd/73/f3/dd73f382-3a84-b6f5-8760-194fe0ac818b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39468831-5545ff1c-4d35-11e8-9fb9-3e5bbc081726.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39468831-5545ff1c-4d35-11e8-9fb9-3e5bbc081726.png)
https://user-images.githubusercontent.com/2068130/39468831-5545ff1c-4d35-11e8-9fb9-3e5bbc081726.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39468842-63cb751c-4d35-11e8-91b0-4a9527c50f83.png
