### ISSUE TITLE
SD78 Fraser-Cascade School District

### ISSUE THREAD

**Issue by yojoemamma** [glasklart/hd#2030]
**App Name:** SD78 Fraser-Cascade School District
**Bundle ID:** com.appazur.sd78
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=556838635">556838635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sd78-fraser-cascade-school-district/id556838635?mt=8&uo=4">https://itunes.apple.com/us/app/sd78-fraser-cascade-school-district/id556838635?mt=8&uo=4</a>
**App Version:** 2.3.8
**Seller:** Appazur Solutions Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/appazur-solutions-inc/id556838638?uo=4">© Appazur Solutions Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple117/v4/ae/8b/5c/ae8b5c59-4f49-8c54-afd3-9f596736c1b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32391779-9e4dc4d6-c0d3-11e7-9c5a-3842e36c68ac.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32391779-9e4dc4d6-c0d3-11e7-9c5a-3842e36c68ac.png)
https://user-images.githubusercontent.com/2068130/32391779-9e4dc4d6-c0d3-11e7-9c5a-3842e36c68ac.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32391797-aded5ed8-c0d3-11e7-9a7c-bc882940b29f.png
