### ISSUE TITLE
SYSTEM UTIL Dashboard - Battery, Memory, Network

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2032]
**App Name:** SYSTEM UTIL Dashboard - Battery, Memory, Network
**Bundle ID:** apphome.com.systemutility
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=578119993">578119993</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/system-util-dashboard-battery-memory-network/id578119993?mt=8&uo=4">https://itunes.apple.com/us/app/system-util-dashboard-battery-memory-network/id578119993?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Zakia Mahzabin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apphome/id337483091?uo=4">© AppHome</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/aa/00/57/aa005708-9751-dfde-cf86-e706044cd173/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32391199-79786320-c0d1-11e7-9be3-c38410f37eb6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32391199-79786320-c0d1-11e7-9be3-c38410f37eb6.png)
https://user-images.githubusercontent.com/2068130/32391199-79786320-c0d1-11e7-9be3-c38410f37eb6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32391221-8865148c-c0d1-11e7-8f74-d4a93d1807f6.png
