### ISSUE TITLE
Fifth Third Mobile Banking

### ISSUE THREAD

**Issue by khattakr** [glasklart/hd#2034]
**App Name:** Fifth Third Mobile Banking
**Bundle ID:** com.clairmail.fth.client
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=468738585">468738585</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fifth-third-mobile-banking/id468738585?mt=8&uo=4">https://itunes.apple.com/us/app/fifth-third-mobile-banking/id468738585?mt=8&uo=4</a>
**App Version:** 3.11.2
**Seller:** FifthThird Bank
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fifththird-bank/id468738588?uo=4>© FifthThird Bank</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple71/v4/0b/f4/80/0bf4809d-7083-5900-c731-792efdb23926/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18244921/b9f64f4c-7362-11e6-9946-fa4f228279fb.png)

**Comment by l8er4now** [comment]
Needs an update, not proportioned correctly.

**App Name:** Fifth Third Mobile Banking
**Bundle ID:** com.clairmail.fth.client
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=468738585">468738585</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fifth-third-mobile-banking/id468738585?mt=8&uo=4">https://itunes.apple.com/us/app/fifth-third-mobile-banking/id468738585?mt=8&uo=4</a>
**App Version:** 3.11.2
**Seller:** FifthThird Bank
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fifththird-bank/id468738588?uo=4>© FifthThird Bank</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple71/v4/0b/f4/80/0bf4809d-7083-5900-c731-792efdb23926/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18244921/b9f64f4c-7362-11e6-9946-fa4f228279fb.png)
https://cloud.githubusercontent.com/assets/20930745/18244921/b9f64f4c-7362-11e6-9946-fa4f228279fb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18244934/cfdeece2-7362-11e6-85a6-fa7bd4ea29bb.png
