### ISSUE TITLE
AT&T MicroCell

### ISSUE THREAD

**Issue by khattakr** [glasklart/hd#2035]
**App Name:** AT&T MicroCell
**Bundle ID:** com.att.MicroCell
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=462844091">462844091</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/at-t-microcell/id462844091?mt=8&uo=4">https://itunes.apple.com/us/app/at-t-microcell/id462844091?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** AT&T Services, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/at-t-services-inc./id290854684?uo=4">© AT&T Services, Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple2/v4/8c/78/bd/8c78bd0a-5fe4-27c6-c799-15559f515225/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039733/257726e4-a449-11e6-8e5c-8d1e6ed1f050.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039733/257726e4-a449-11e6-8e5c-8d1e6ed1f050.png)
https://cloud.githubusercontent.com/assets/20930745/20039733/257726e4-a449-11e6-8e5c-8d1e6ed1f050.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20039736/3bce9148-a449-11e6-9953-24fafa47656b.png
