### ISSUE TITLE
Erste Bank / Sparkasse Österreich - netbanking

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2038]
**App Name:** Erste Bank / Sparkasse Österreich - netbanking
**Bundle ID:** at.s-itsolutions.netbanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=437840915">437840915</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/erste-bank-sparkasse-osterreich/id437840915?mt=8&uo=4">https://itunes.apple.com/us/app/erste-bank-sparkasse-osterreich/id437840915?mt=8&uo=4</a>
**App Version:** 1.8.5
**Seller:** Erste Bank der oesterreichischen Sparkassen AG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/erste-bank-und-sparkassen/id921349454?uo=4">© Erste Bank und Sparkassen</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/ae/1d/cb/ae1dcb5f-d22e-6bbb-d184-a350c3e29bbf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19882403/c4034ad0-a00d-11e6-92fc-e6f7ad04621b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19882403/c4034ad0-a00d-11e6-92fc-e6f7ad04621b.png)
https://cloud.githubusercontent.com/assets/20930745/19882403/c4034ad0-a00d-11e6-92fc-e6f7ad04621b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19882425/f2c672de-a00d-11e6-8d34-da20903dd011.png
