### ISSUE TITLE
Canucks

### ISSUE THREAD

**Issue by yojoemamma** [glasklart/hd#2040]
**App Name:** Canucks
**Bundle ID:** com.vancouvercanucks.Canucks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=354539557">354539557</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/canucks/id354539557?mt=8&uo=4">https://itunes.apple.com/us/app/canucks/id354539557?mt=8&uo=4</a>
**App Version:** 17.0.0
**Seller:** Canucks Sports & Entertainment
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vancouver-canucks/id354539560?uo=4">© Vancouver Canucks</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/2e/88/f5/2e88f505-30b5-87cc-c527-a63537f578ca/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688234-7673ead0-c6cd-11e7-8e9a-1c9a3431323e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688234-7673ead0-c6cd-11e7-8e9a-1c9a3431323e.png)
https://user-images.githubusercontent.com/2068130/32688234-7673ead0-c6cd-11e7-8e9a-1c9a3431323e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32688239-8780c50a-c6cd-11e7-967c-728797412cb5.png
