### ISSUE TITLE
TechCrunch

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#2049]
**App Name:** TechCrunch
**Bundle ID:** com.aol.mobile.techcrunch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526058642">526058642</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/techcrunch/id526058642?mt=8&uo=4">https://itunes.apple.com/us/app/techcrunch/id526058642?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** AOL Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/aol-inc./id281704577?uo=4">© AOL Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/28/40/e9/2840e984-ab1f-5b50-4f1d-6967af3ab9eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19850965/c46f6e2a-9f5b-11e6-8fc1-1c67e3bf8503.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19850965/c46f6e2a-9f5b-11e6-8fc1-1c67e3bf8503.png)
https://cloud.githubusercontent.com/assets/20930745/19850965/c46f6e2a-9f5b-11e6-8fc1-1c67e3bf8503.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19850987/e0329380-9f5b-11e6-9fe2-2888745ba834.png
