### ISSUE TITLE
CNEWS info Tv France et Monde

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#205]
**App Name:** CNEWS info Tv France et Monde
**Bundle ID:** com.canalplus.itele
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=411438424">411438424</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cnews-info-tv-france-et-monde/id411438424?uo=4">https://apps.apple.com/us/app/cnews-info-tv-france-et-monde/id411438424?uo=4</a>
**App Version:** 6.3
**Seller:** GROUPE CANAL+
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/groupe-canal/id694580819?uo=4">© GROUPE CANAL+</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/1f/cc/c0/1fccc0e2-b06a-458b-3825-4f3b2156db2d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60371268-0fa6b200-99f9-11e9-8886-5bf9cc528684.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19838788/c9a0057e-9ed6-11e6-9f03-8ec0f1e266b8.png)
https://cloud.githubusercontent.com/assets/20930745/19838788/c9a0057e-9ed6-11e6-9f03-8ec0f1e266b8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19838796/f54a8cf8-9ed6-11e6-8b95-76af2921b023.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60371268-0fa6b200-99f9-11e9-8886-5bf9cc528684.png)
https://user-images.githubusercontent.com/20930745/60371268-0fa6b200-99f9-11e9-8886-5bf9cc528684.png

Source:
https://user-images.githubusercontent.com/20930745/60371275-12a1a280-99f9-11e9-8168-95a197b9546e.png
