### ISSUE TITLE
Bitly

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#2050]
**App Name:** Bitly
**Bundle ID:** com.bitly.Bitly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525106063">525106063</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bitly/id525106063?mt=8&uo=4">https://itunes.apple.com/us/app/bitly/id525106063?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Bitly, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bitly-inc./id420744919?uo=4>© Bitly, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/a4/58/ab/a458ab29-7083-8334-217e-d70db5cc313d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420051/af3650e2-93e3-11e6-8f35-29d37b2a13fe.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420051/af3650e2-93e3-11e6-8f35-29d37b2a13fe.png)
https://cloud.githubusercontent.com/assets/20930745/19420051/af3650e2-93e3-11e6-8f35-29d37b2a13fe.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19420060/d6a4ec1a-93e3-11e6-8924-01e30aba23e2.png
