### ISSUE TITLE
ICA

### ISSUE THREAD

**Issue by chrstrvs** [glasklart/hd#2051]
**App Name:** ICA
**Bundle ID:** se.ica.shoppinglista
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=458324110">458324110</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/se/app/ica/id458324110?uo=4">https://apps.apple.com/se/app/ica/id458324110?uo=4</a>
**App Version:** 4.9.0
**Seller:** ICA AB
**Developer:** <a target="_blank" href="https://apps.apple.com/se/developer/ica-sverige-ab/id438413087?uo=4">© ICA Sverige AB</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/2d/fd/56/2dfd5638-3177-aa2b-21b9-108eeff22188/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62396409-72004e80-b573-11e9-8963-66373935c7ff.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11011217/27c58ae0-84e6-11e5-8b24-e98224a1a088.png)
https://cloud.githubusercontent.com/assets/10730122/11011217/27c58ae0-84e6-11e5-8b24-e98224a1a088.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11011210/22170fce-84e6-11e5-8242-95e9e4359c98.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62396409-72004e80-b573-11e9-8963-66373935c7ff.png)
https://user-images.githubusercontent.com/2068130/62396409-72004e80-b573-11e9-8963-66373935c7ff.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62396445-817f9780-b573-11e9-9d1c-f276abb6f4cb.png
