### ISSUE TITLE
Amount - Unit and Currency Converter

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2053]
**App Name:** Amount - Unit and Currency Converter
**Bundle ID:** Amount
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=560750783">560750783</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amount-unit-currency-converter/id560750783?mt=8&uo=4">https://itunes.apple.com/us/app/amount-unit-currency-converter/id560750783?mt=8&uo=4</a>
**App Version:** 3.9.92
**Seller:** Marco Torretta
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/marco-torretta/id560750786?uo=4>© Marco Torretta</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/4b/15/34/4b1534be-3f09-3393-634b-fe4a3edfd5b4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13135308/beb7806e-d60f-11e5-8c56-f2992ed21915.png)

**Comment by Anuskuss** [comment]
Needs update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13135308/beb7806e-d60f-11e5-8c56-f2992ed21915.png)
https://cloud.githubusercontent.com/assets/2068130/13135308/beb7806e-d60f-11e5-8c56-f2992ed21915.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13135321/ce2d37d2-d60f-11e5-85ee-e37717fcecb9.png
