### ISSUE TITLE
GoBank

### ISSUE THREAD

**Issue by woitalla** [glasklart/hd#2055]
**App Name:** GoBank
**Bundle ID:** com.greendotcorp.gobank
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=535272164">535272164</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gobank/id535272164?mt=8&uo=4">https://itunes.apple.com/us/app/gobank/id535272164?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Green Dot Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/green-dot-corporation/id437092811?uo=4>© Green Dot Corporation</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/7a/13/47/7a1347f3-08b8-0a22-b7c8-c4b8c36af01f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411205/70290534-92fd-11e6-9b5f-47a199598054.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411205/70290534-92fd-11e6-9b5f-47a199598054.png)
https://cloud.githubusercontent.com/assets/20930745/19411205/70290534-92fd-11e6-9b5f-47a199598054.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411208/825190fa-92fd-11e6-912f-5ed308a5acb2.png
