### ISSUE TITLE
CARROT To-Do - Talking Task List

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#2056]
**App Name:** CARROT To-Do - Talking Task List
**Bundle ID:** com.grailr.CARROT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=591840203">591840203</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/carrot-to-do-talking-task-list/id591840203?mt=8&uo=4">https://itunes.apple.com/us/app/carrot-to-do-talking-task-list/id591840203?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** Grailr LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/grailr-llc/id556706923?uo=4>© Grailr LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/3a/e7/2e/3ae72e25-3d8c-5546-de93-c8a0c2353949/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19382891/65e3342e-9202-11e6-8f55-dc83371ec31b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19382891/65e3342e-9202-11e6-8f55-dc83371ec31b.png)
https://cloud.githubusercontent.com/assets/20930745/19382891/65e3342e-9202-11e6-8f55-dc83371ec31b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19382905/75a4fd34-9202-11e6-9cec-cd518759aca4.png
