### ISSUE TITLE
SongPop

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2058]
**App Name:** SongPop
**Bundle ID:** com.freshplanet.games.WaM
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=518042655">518042655</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/songpop/id518042655?mt=8&uo=4">https://itunes.apple.com/us/app/songpop/id518042655?mt=8&uo=4</a>
**App Version:** 1.26.27
**Seller:** FreshPlanet, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/freshplanet-inc./id364257025?uo=4">© FreshPlanet Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/fe/33/84/fe338409-5ca2-1e0e-55ad-577b2b9567ca/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20221083/3d448b96-a830-11e6-98ad-f09329d3c723.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20221083/3d448b96-a830-11e6-98ad-f09329d3c723.png)
https://cloud.githubusercontent.com/assets/20930745/20221083/3d448b96-a830-11e6-98ad-f09329d3c723.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20221115/62514668-a830-11e6-9680-b5c3043498f2.png
