### ISSUE TITLE
Hello Vino - Wine Recommendations, Label Scanner and Ratings Guide

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2061]
**App Name:** Hello Vino - Wine Recommendations, Label Scanner and Ratings Guide
**Bundle ID:** com.HalcyonInnovation.HelloVino
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=318447346">318447346</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hello-vino-wine-recommendations/id318447346?mt=8&uo=4">https://itunes.apple.com/us/app/hello-vino-wine-recommendations/id318447346?mt=8&uo=4</a>
**App Version:** 4.9.9
**Seller:** Hello Vino, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hello-vino/id318447349?uo=4>© Hello Vino</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/a7/c1/65/a7c16504-4b82-04cc-1f0a-fa446118f4f8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420148/e9af81ce-93e5-11e6-800c-4d17c60f9048.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420148/e9af81ce-93e5-11e6-800c-4d17c60f9048.png)
https://cloud.githubusercontent.com/assets/20930745/19420148/e9af81ce-93e5-11e6-800c-4d17c60f9048.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19420161/0a6d3c12-93e6-11e6-9bad-2c5f5b43337f.png
