### ISSUE TITLE
SigFig Investing – The smartest way to manage & improve your portfolio, 401k, and brokerage accounts

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#2066]
**App Name:** SigFig Investing – The smartest way to manage & improve your portfolio, 401k, and brokerage accounts
**Bundle ID:** com.sigfig.sigfig
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=524027365">524027365</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sigfig-investing-smartest/id524027365?mt=8&uo=4">https://itunes.apple.com/us/app/sigfig-investing-smartest/id524027365?mt=8&uo=4</a>
**App Version:** 4.1.2
**Seller:** Nvest, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sigfig/id524027368?uo=4>© SigFig</a>
**Supported Devices:** iPhone4, iPhone5, iPad23G, iPadFourthGen, iPadMini, iPhone6, iPadMini4G, iPadThirdGen4G, iPadThirdGen, iPad2Wifi, iPodTouchFifthGen, iPadFourthGen4G, iPhone6Plus, iPhone4S, iPhone5c, iPhone5s
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/ca/22/4c/ca224ca8-89e6-fe2e-ce10-e92979997345/mzl.arjzlhrv.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8375040/4d43df56-1bfa-11e5-9172-94102e8ddeea.png)

**Comment by Trubbel** [comment]
Icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8375040/4d43df56-1bfa-11e5-9172-94102e8ddeea.png)
https://cloud.githubusercontent.com/assets/10730122/8375040/4d43df56-1bfa-11e5-9172-94102e8ddeea.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8375038/4862574c-1bfa-11e5-86ce-e74d009a446f.png
