### ISSUE TITLE
ImmobilienScout24: Real Estate

### ISSUE THREAD

**Issue by askarl** [glasklart/hd#2068]
**App Name:** ImmobilienScout24: Real Estate
**Bundle ID:** de.immoscout.immoscout
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=344176018">344176018</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/immobilienscout24-real-estate/id344176018?uo=4">https://apps.apple.com/us/app/immobilienscout24-real-estate/id344176018?uo=4</a>
**App Version:** 20.0.1
**Seller:** ImmobilienScout GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/immobilienscout-gmbh/id344176021?uo=4">© ImmobilienScout GmbH</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/da/4a/5c/da4a5c25-8903-5ae7-7083-848d970c7a67/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76148017-888afd00-60a2-11ea-98b1-835102f686aa.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18478357/345d347a-79d1-11e6-9512-ba6022e83604.png)
https://cloud.githubusercontent.com/assets/20930745/18478357/345d347a-79d1-11e6-9512-ba6022e83604.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18478377/4a50bdce-79d1-11e6-8931-70be2eeb6823.png

**Comment by 2Qt2beStr8** [comment]
Needs update

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/76148017-888afd00-60a2-11ea-98b1-835102f686aa.png)
https://user-images.githubusercontent.com/20930745/76148017-888afd00-60a2-11ea-98b1-835102f686aa.png

Source:
https://user-images.githubusercontent.com/20930745/76148019-8a54c080-60a2-11ea-8681-d0dc3f26395e.png
