### ISSUE TITLE
ÖBB Tickets

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2070]
**App Name:** ÖBB Tickets
**Bundle ID:** at.oebb.ticket4all
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542368013">542368013</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/obb-tickets/id542368013?mt=8&uo=4">https://itunes.apple.com/us/app/obb-tickets/id542368013?mt=8&uo=4</a>
**App Version:** 3.98
**Seller:** OBB-Personenverkehr AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/obb-personenverkehr-ag/id542368016?uo=4>© ÖBB-Personenverkehr AG</a>
**Supported Devices:** iPhone4S, iPadMini4G, iPhone5c, iPadMini, iPad2Wifi, iPadThirdGen, iPhone6Plus, iPhone5s, iPodTouchFifthGen, iPadFourthGen, iPad23G, iPhone5, iPadThirdGen4G, iPadFourthGen4G, iPhone6, iPhone4
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/42/ea/e9/42eae909-0b9a-d3fb-b570-2d2da6613048/mzl.csnfwkxx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8270583/fe2416ce-17e5-11e5-9bb4-ebdb83058d48.png)

**Comment by dreamnet** [comment]
Icon update:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8270583/fe2416ce-17e5-11e5-9bb4-ebdb83058d48.png)
https://cloud.githubusercontent.com/assets/2068130/8270583/fe2416ce-17e5-11e5-9bb4-ebdb83058d48.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8270586/12e1dcfe-17e6-11e5-9062-4ddf7b11ee5a.png
