### ISSUE TITLE
beIN SPORTS TR

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2071]
**App Name:** beIN SPORTS TR
**Bundle ID:** com.digiturk.ligtv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=434619978">434619978</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bein-sports-tr/id434619978?mt=8&uo=4">https://itunes.apple.com/us/app/bein-sports-tr/id434619978?mt=8&uo=4</a>
**App Version:** 1.18.8
**Seller:** Digital Platform Iletisim Hizmetleri A.S
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/digiturk/id376177281?uo=4">© DIGITURK</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/4b/49/c3/4b49c36f-ab59-0cb4-bc34-c8c0b684b115/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626407-eb330280-a91b-11e8-8437-74229daad463.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19738567/32911d88-9bb8-11e6-9ab7-512aba7241a4.png)
https://cloud.githubusercontent.com/assets/2068130/19738567/32911d88-9bb8-11e6-9ab7-512aba7241a4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19738581/4142bcb0-9bb8-11e6-9de2-db4f1561944b.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626407-eb330280-a91b-11e8-8437-74229daad463.png)
https://user-images.githubusercontent.com/2068130/44626407-eb330280-a91b-11e8-8437-74229daad463.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44626410-fab24b80-a91b-11e8-9898-e762a1e499d6.png
