### ISSUE TITLE
myGigs

### ISSUE THREAD

**Issue by askarl** [glasklart/hd#2072]
**App Name:** myGigs
**Bundle ID:** de.tapwork.myGigs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=472250595">472250595</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mygigs/id472250595?mt=8&uo=4">https://itunes.apple.com/us/app/mygigs/id472250595?mt=8&uo=4</a>
**App Version:** 3.1.6
**Seller:** TAPWORK GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tapwork-gmbh/id319575727?uo=4">© TAPWORK GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/94/12/c9/9412c9a2-3c85-abf9-4bc0-43285544e1f1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32389447-ea528b86-c0ca-11e7-8062-d9eb3ce35580.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32389447-ea528b86-c0ca-11e7-8062-d9eb3ce35580.png)
https://user-images.githubusercontent.com/2068130/32389447-ea528b86-c0ca-11e7-8062-d9eb3ce35580.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32389468-f9b6e892-c0ca-11e7-9487-5a1a356eb9c7.png
