### ISSUE TITLE
Bluebird by American Express

### ISSUE THREAD

**Issue by woitalla** [glasklart/hd#2073]
**App Name:** Bluebird by American Express
**Bundle ID:** com.americanexpress.bluebird
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=566645291">566645291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bluebird-by-american-express/id566645291?mt=8&uo=4">https://itunes.apple.com/us/app/bluebird-by-american-express/id566645291?mt=8&uo=4</a>
**App Version:** 3.1.0.0
**Seller:** American Express
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/american-express/id362348519?uo=4>© American Express</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple42/v4/38/e0/cb/38e0cb09-e15e-735e-f8f8-d19bf255bef5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19756762/2f6c0700-9c1f-11e6-8bc9-b49ce919ae0d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19756762/2f6c0700-9c1f-11e6-8bc9-b49ce919ae0d.png)
https://cloud.githubusercontent.com/assets/2068130/19756762/2f6c0700-9c1f-11e6-8bc9-b49ce919ae0d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19756775/3dd3168a-9c1f-11e6-81be-de49a8b40f3b.png
