### ISSUE TITLE
Printer Pro Classic - wirelessly print documents, photos, web pages and emails

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2075]
**App Name:** Printer Pro Classic - wirelessly print documents, photos, web pages and emails
**Bundle ID:** com.readdle.PrinterProiPhone
**iTunes ID:** 410011612
**iPhone Icon Name:** iPhone-4_114x114.png
**Icon Names:** iPhone_57x57.png | iPhone-4_58x58.png | iPhone-4_114x114.png | iPad_29x29.png | iPad_48x48.png | iPad_72x72.png 
**iTunes URL:** https://itunes.apple.com/us/app/printer-pro-for-iphone/id410011612?mt=8&uo=4
**App Version:** 3.2.4
**Seller:** Igor Zhadanov
**Supported Devices:** all
**Original Artwork:**
<img src="http://a106.phobos.apple.com/us/r1000/115/Purple/v4/46/a1/b6/46a1b64a-ec83-4e65-83a3-a1f2623c16eb/mzl.iyjifilc.png" width="150" height="150" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33751271-12a044a0-dbda-11e7-9a18-8593a00348a9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33751271-12a044a0-dbda-11e7-9a18-8593a00348a9.png)
https://user-images.githubusercontent.com/2068130/33751271-12a044a0-dbda-11e7-9a18-8593a00348a9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33751283-25bb0278-dbda-11e7-94cb-2bb520281da9.png
