### ISSUE TITLE
NextBus-Official

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2077]
**App Name:** NextBus-Official
**Bundle ID:** com.NextBus.NextBus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1009534692">1009534692</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nextbus-official/id1009534692?mt=8&uo=4">https://itunes.apple.com/us/app/nextbus-official/id1009534692?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** NextBus, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nextbus-inc/id1008981388?uo=4">© NextBus, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/6c/3f/60/6c3f6026-86ba-21b4-264e-f945b3b0db7e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33752023-46647068-dbdf-11e7-9bb8-3aa929646cfa.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33752023-46647068-dbdf-11e7-9bb8-3aa929646cfa.png)
https://user-images.githubusercontent.com/2068130/33752023-46647068-dbdf-11e7-9bb8-3aa929646cfa.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33752029-5616a24c-dbdf-11e7-8f05-0d9d968bdab2.png
