### ISSUE TITLE
HotUKDeals – Voucher Codes

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2079]
**App Name:** HotUKDeals – Voucher Codes
**Bundle ID:** com.tippingcanoeug.hotukdeals
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570702323">570702323</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hotukdeals-voucher-codes/id570702323?mt=8&uo=4">https://itunes.apple.com/us/app/hotukdeals-voucher-codes/id570702323?mt=8&uo=4</a>
**App Version:** 5.8.0
**Seller:** Tipping Canoe UG (haftungsbeschränkt) & Co. KG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hotukdeals/id570702326?uo=4">© HotUKDeals</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/3d/6a/d5/3d6ad598-15b6-b892-c622-23cd651d5ded/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160377-0514a786-34bd-11e8-89e7-dcf9e5bf1227.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160377-0514a786-34bd-11e8-89e7-dcf9e5bf1227.png)
https://user-images.githubusercontent.com/2068130/38160377-0514a786-34bd-11e8-89e7-dcf9e5bf1227.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38160381-15b6efe0-34bd-11e8-994d-e6df60c1d5c6.png
