### ISSUE TITLE
JUST EAT - Takeaway food delivery

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2080]
**App Name:** JUST EAT - Takeaway food delivery
**Bundle ID:** com.justeat.JUSTEAT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=566347057">566347057</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/just-eat-takeaway-food-delivery/id566347057?mt=8&uo=4">https://itunes.apple.com/us/app/just-eat-takeaway-food-delivery/id566347057?mt=8&uo=4</a>
**App Version:** 13.3
**Seller:** Just-Eat Holdings Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/just-eat.com/id383091095?uo=4>© Just-Eat.com</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/13/1a/b3/131ab354-53ed-9317-d920-f59b01bb2772/mzl.znpqqvia.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10038821/8136c578-61cb-11e5-9caa-35489731c90f.png)

**Comment by dreamnet** [comment]
Artwork has changed.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10038821/8136c578-61cb-11e5-9caa-35489731c90f.png)
https://cloud.githubusercontent.com/assets/2068130/10038821/8136c578-61cb-11e5-9caa-35489731c90f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10038825/8f5e8a5a-61cb-11e5-969b-c91ac95fc646.png
