### ISSUE TITLE
Bokeh Lens

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2086]
**App Name:** Bokeh Lens
**Bundle ID:** com.studiotimo.bokehlicious
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=587849880">587849880</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bokeh-lens/id587849880?mt=8&uo=4">https://itunes.apple.com/us/app/bokeh-lens/id587849880?mt=8&uo=4</a>
**App Version:** 1.3.5
**Seller:** Gicheol Lee
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/studiotimo/id506594965?uo=4>© StudioTIMO</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/9d/c2/fb/9dc2fb7a-3b53-0dcd-0c56-7ae9f34b569a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19456049/ff92d22c-94bf-11e6-948f-0d410b924762.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19456049/ff92d22c-94bf-11e6-948f-0d410b924762.png)
https://cloud.githubusercontent.com/assets/20930745/19456049/ff92d22c-94bf-11e6-948f-0d410b924762.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19456081/22e7d13c-94c0-11e6-8d6b-9c2db0c354d6.png
