### ISSUE TITLE
National Rail Enquiries

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2089]
**App Name:** National Rail Enquiries
**Bundle ID:** uk.co.nationalrail.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519094154">519094154</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/national-rail-enquiries/id519094154?mt=8&uo=4">https://itunes.apple.com/us/app/national-rail-enquiries/id519094154?mt=8&uo=4</a>
**App Version:** 8.11.1
**Seller:** Train Information Services Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/national-rail/id512167281?uo=4>© National Rail</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/2a/35/57/2a355712-f0a8-a6dd-61ac-1b1ca28da252/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19456413/99e36e80-94c1-11e6-88d3-2d31616e0a4f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19456413/99e36e80-94c1-11e6-88d3-2d31616e0a4f.png)
https://cloud.githubusercontent.com/assets/20930745/19456413/99e36e80-94c1-11e6-88d3-2d31616e0a4f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19456443/b8c51c4a-94c1-11e6-8a62-9cab518563f7.png
