### ISSUE TITLE
Frametastic

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2090]
**App Name:** Frametastic
**Bundle ID:** com.imaginaryfeet.frametastic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427063436">427063436</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/frametastic/id427063436?mt=8&uo=4">https://itunes.apple.com/us/app/frametastic/id427063436?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Imaginary Feet, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/imaginary-feet-llc/id292363934?uo=4">© Imaginary Feet, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/8f/fa/a4/8ffaa438-2fa3-913f-fe1c-e7b83997b3c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19900444/d5cc5616-a063-11e6-9012-a68309be6253.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19900444/d5cc5616-a063-11e6-9012-a68309be6253.png)
https://cloud.githubusercontent.com/assets/20930745/19900444/d5cc5616-a063-11e6-9012-a68309be6253.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19900471/ec412dae-a063-11e6-90b2-1a7a0736861b.png
