### ISSUE TITLE
TitleFx - Write on Pictures, add Text Captions to Photos

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2092]
**App Name:** TitleFx - Write on Pictures, add Text Captions to Photos
**Bundle ID:** com.eastcoastpixels.titlefx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=585663626">585663626</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/titlefx-write-on-pictures/id585663626?mt=8&uo=4">https://itunes.apple.com/us/app/titlefx-write-on-pictures/id585663626?mt=8&uo=4</a>
**App Version:** 2.6.8
**Seller:** East Coast Pixels, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/east-coast-pixels-inc./id380588089?uo=4">© East Coast Pixels, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/ea/ea/a0/eaeaa051-86a9-5318-f9a3-79328050edc9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19902091/c76631ea-a069-11e6-8c7c-2a0bfc630cd1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19902091/c76631ea-a069-11e6-8c7c-2a0bfc630cd1.png)
https://cloud.githubusercontent.com/assets/20930745/19902091/c76631ea-a069-11e6-8c7c-2a0bfc630cd1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19902121/dde0b814-a069-11e6-8fa2-a0ce881049f0.png
