### ISSUE TITLE
Status Shuffle for Facebook

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2093]
**App Name:** Status Shuffle for Facebook
**Bundle ID:** com.sgstudios.statusshuffle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=415888970">415888970</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/status-shuffle-for-facebook/id415888970?mt=8&uo=4">https://itunes.apple.com/us/app/status-shuffle-for-facebook/id415888970?mt=8&uo=4</a>
**App Version:** 3.6.3
**Seller:** Social Graph Studios Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/social-graph-studios/id415888973?uo=4>© Social Graph Studios</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/a1/ac/71/a1ac71f8-f5d5-8f16-905e-da85f4826116/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19757049/0471ed88-9c21-11e6-839d-451323b11e2b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19757049/0471ed88-9c21-11e6-839d-451323b11e2b.png)
https://cloud.githubusercontent.com/assets/2068130/19757049/0471ed88-9c21-11e6-839d-451323b11e2b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19757061/13b8bd12-9c21-11e6-864f-b8695fd0ad2c.png
