### ISSUE TITLE
Skyscanner - Flights, Hotels & Cars

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2094]
**App Name:** Skyscanner - Flights, Hotels & Cars
**Bundle ID:** net.skyscanner.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=415458524">415458524</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skyscanner-flights-hotels/id415458524?mt=8&uo=4">https://itunes.apple.com/us/app/skyscanner-flights-hotels/id415458524?mt=8&uo=4</a>
**App Version:** 5.3
**Seller:** Skyscanner Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/skyscanner/id415458528?uo=4>© Skyscanner</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/cf/8f/36/cf8f36c8-ca06-bdb6-f02d-60d93640d275/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19074673/9a094f9a-8a41-11e6-81fd-4c14bfc1a447.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19074673/9a094f9a-8a41-11e6-81fd-4c14bfc1a447.png)

Source:
https://cloud.githubusercontent.com/assets/20930745/19074682/a2efb2b6-8a41-11e6-903a-4e10bc8fc068.png
