### ISSUE TITLE
Sky Bet: Sports Betting on Football & Horse Racing

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2095]
**App Name:** Sky Bet: Sports Betting on Football & Horse Racing
**Bundle ID:** com.bskyb.mobenga.skybet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=428237841">428237841</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/sky-bet-sports-betting-on/id428237841?mt=8&uo=4">https://itunes.apple.com/gb/app/sky-bet-sports-betting-on/id428237841?mt=8&uo=4</a>
**App Version:** 5.11
**Seller:** Bonne Terre Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/sky-betting-gaming/id577438411?uo=4>© Sky Betting & Gaming</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/2d/ea/ec/2deaec93-6582-368a-ac21-58b8cf70790e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19454549/d4489b52-94b9-11e6-8f6a-85c3a2f640bf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19454549/d4489b52-94b9-11e6-8f6a-85c3a2f640bf.png)
![](https://cloud.githubusercontent.com/assets/20930745/19454549/d4489b52-94b9-11e6-8f6a-85c3a2f640bf.png)

Source:
(https://cloud.githubusercontent.com/assets/20930745/19454577/fc267de2-94b9-11e6-8be6-cea7cf4084c7.png
