### ISSUE TITLE
HMRC

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2099]
**App Name:** HMRC
**Bundle ID:** uk.gov.hmrc.TaxCalc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514561561">514561561</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/hmrc/id514561561?mt=8&uo=4">https://itunes.apple.com/gb/app/hmrc/id514561561?mt=8&uo=4</a>
**App Version:** 3.2.1
**Seller:** HMRC
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/hmrc/id514561564?uo=4">© HMRC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/78/b2/d4/78b2d44a-2245-cd66-0815-3793ece71831/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20237587/3887eede-a8d7-11e6-958b-e2c81fb6d402.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20237587/3887eede-a8d7-11e6-958b-e2c81fb6d402.png)
https://cloud.githubusercontent.com/assets/20930745/20237587/3887eede-a8d7-11e6-958b-e2c81fb6d402.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20237594/58c8b566-a8d7-11e6-87d0-98a0918e6bec.png
