### ISSUE TITLE
Navmii GPS Australia & NZ: Offline Navigation

### ISSUE THREAD

**Issue by darkxst** [glasklart/hd#210]
**App Name:** Navmii GPS Australia & NZ: Offline Navigation
**Bundle ID:** com.navfree.ios.ANZ
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=422816006">422816006</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/navmii-gps-australia-nz-offline-navigation/id422816006?mt=8&uo=4">https://itunes.apple.com/us/app/navmii-gps-australia-nz-offline-navigation/id422816006?mt=8&uo=4</a>
**App Version:** 3.6.13
**Seller:** Navmii Publishing Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/navmii-publishing-ltd/id345881276?uo=4">© Navmii Publishing Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple127/v4/2c/87/a1/2c87a11c-2541-d1a4-866a-680435bf6a08/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32142724-5a37dc26-bc9d-11e7-906e-a21f22d0865a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32142724-5a37dc26-bc9d-11e7-906e-a21f22d0865a.png)
https://user-images.githubusercontent.com/2068130/32142724-5a37dc26-bc9d-11e7-906e-a21f22d0865a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32142729-6b5d10fc-bc9d-11e7-9752-cdffff9ac94f.png

**Comment by dreamnet** [comment]
😆
