### ISSUE TITLE
Manchester Airport

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2104]
**App Name:** Manchester Airport
**Bundle ID:** com.kmp.MAG
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368706348">368706348</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/manchester-airport/id368706348?mt=8&uo=4">https://itunes.apple.com/us/app/manchester-airport/id368706348?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Manchester Airport plc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/manchester-airports-group/id1006632022?uo=4>© Manchester Airports Group</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/44/d2/dd/44d2dd9f-cbce-c8bf-d957-8742b7822cd2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411077/b3e7ce70-92fa-11e6-9554-d13e2e0ce405.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411077/b3e7ce70-92fa-11e6-9554-d13e2e0ce405.png)
https://cloud.githubusercontent.com/assets/20930745/19411077/b3e7ce70-92fa-11e6-9554-d13e2e0ce405.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411090/d499eac2-92fa-11e6-95ca-d2f267232dba.png
