### ISSUE TITLE
Rightmove Property Search

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2106]
**App Name:** Rightmove Property Search
**Bundle ID:** uk.co.rightmove.rightmove
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=323822803">323822803</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rightmove-property-search/id323822803?mt=8&uo=4">https://itunes.apple.com/us/app/rightmove-property-search/id323822803?mt=8&uo=4</a>
**App Version:** 4.16
**Seller:** Rightmove
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rightmove/id323822806?uo=4>© Rightmove</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple22/v4/96/79/19/96791913-7007-e85c-6114-bbb3ba776e14/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19229811/a0730338-8ed0-11e6-8553-3c734d052a05.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19229811/a0730338-8ed0-11e6-8553-3c734d052a05.png)
https://cloud.githubusercontent.com/assets/20930745/19229811/a0730338-8ed0-11e6-8553-3c734d052a05.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19229845/dd4af3a6-8ed0-11e6-8e6c-df54e23a2ba2.png
