### ISSUE TITLE
Trainline UK - Live train times & tickets

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2108]
**App Name:** Trainline UK - Live train times & tickets
**Bundle ID:** com.thetrainline.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=334235181">334235181</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trainline-uk-live-train-times/id334235181?mt=8&uo=4">https://itunes.apple.com/us/app/trainline-uk-live-train-times/id334235181?mt=8&uo=4</a>
**App Version:** 13
**Seller:** thetrainline
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/thetrainline/id334235184?uo=4>© thetrainline</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/39/2e/b3/392eb38f-deb3-764b-3803-98307c35cc22/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19884910/3bb15668-a01c-11e6-8958-af40da1b2143.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19884910/3bb15668-a01c-11e6-8958-af40da1b2143.png)
https://cloud.githubusercontent.com/assets/20930745/19884910/3bb15668-a01c-11e6-8958-af40da1b2143.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19884942/50ad616a-a01c-11e6-9cb9-5127e6bb0495.png
