### ISSUE TITLE
Ticketmaster UK - Tickets for Concerts, Sports, Broadway, Shows & Games

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2109]
**App Name:** Ticketmaster UK - Tickets for Concerts, Sports, Broadway, Shows & Games
**Bundle ID:** com.ticketmaster.ios.uk.TicketmasterApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=523775368">523775368</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/ticketmaster-uk-tickets-for/id523775368?mt=8&uo=4">https://itunes.apple.com/gb/app/ticketmaster-uk-tickets-for/id523775368?mt=8&uo=4</a>
**App Version:** 1.8.7
**Seller:** Ticketmaster L.L.C
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/ticketmaster/id500003568?uo=4>© Ticketmaster</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/01/61/ba/0161ba2a-e8bd-a8b3-bbc9-04f55748381f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19884717/598c562a-a01b-11e6-862c-134516f5071d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19884717/598c562a-a01b-11e6-862c-134516f5071d.png)
https://cloud.githubusercontent.com/assets/20930745/19884717/598c562a-a01b-11e6-862c-134516f5071d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19884743/74295d5c-a01b-11e6-9694-09e5db8e56b5.png
