### ISSUE TITLE
SeatGuru by TripAdvisor

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2113]
**App Name:** SeatGuru by TripAdvisor
**Bundle ID:** com.tripadvisor.SeatGuru
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=508487044">508487044</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/seatguru-by-tripadvisor/id508487044?mt=8&uo=4">https://itunes.apple.com/us/app/seatguru-by-tripadvisor/id508487044?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** TripAdvisor
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tripadvisor-llc/id284876798?uo=4>© TripAdvisor LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/b6/d7/9f/b6d79fec-b123-6968-7f6d-337d6b772b0f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19022594/f1954ed8-88db-11e6-871e-281db97a6f08.png)

**Comment by Sly-Fi** [comment]
Icon missing from version 5

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19022594/f1954ed8-88db-11e6-871e-281db97a6f08.png)
https://cloud.githubusercontent.com/assets/2068130/19022594/f1954ed8-88db-11e6-871e-281db97a6f08.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19022597/ff9e5ae2-88db-11e6-9617-c6fdb6815838.png
