### ISSUE TITLE
Vapemate

### ISSUE THREAD

**Issue by Papichulo1767** [glasklart/hd#2116]
**App Name:** Vapemate
**Bundle ID:** com.theserve.vapem
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=545961166">545961166</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vapemate/id545961166?mt=8&uo=4">https://itunes.apple.com/us/app/vapemate/id545961166?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Andrew Rayner
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/theserve/id545961329?uo=4">© Theserve</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/17/e5/5e/17e55e92-8b52-b783-2a02-5930414e19f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19884190/d6cd2c5c-a018-11e6-982f-59096c23f370.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19884190/d6cd2c5c-a018-11e6-982f-59096c23f370.png)
https://cloud.githubusercontent.com/assets/20930745/19884190/d6cd2c5c-a018-11e6-982f-59096c23f370.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19884213/f0268496-a018-11e6-98a9-d7ec74f91c6a.png
