### ISSUE TITLE
Car Buying

### ISSUE THREAD

**Issue by Papichulo1767** [glasklart/hd#2117]
**App Name:** Car Buying
**Bundle ID:** com.kbb.valuesapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=367353324">367353324</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/car-buying/id367353324?mt=8&uo=4">https://itunes.apple.com/us/app/car-buying/id367353324?mt=8&uo=4</a>
**App Version:** 1.1.17
**Seller:** Kelley Blue Book Co., Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kelley-blue-book/id367353327?uo=4">© Kelley Blue Book</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/91/34/88/9134883f-f7ba-8af0-108b-16cb5bdf1cd2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32390777-043a21d0-c0d0-11e7-8793-c78da60903fa.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32390777-043a21d0-c0d0-11e7-8793-c78da60903fa.png)
https://user-images.githubusercontent.com/2068130/32390777-043a21d0-c0d0-11e7-8793-c78da60903fa.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32390791-1379427a-c0d0-11e7-939b-22d4e35778e2.png
