### ISSUE TITLE
GroupMe

### ISSUE THREAD

**Issue by jeremyblake** [glasklart/hd#2121]
**App Name:** GroupMe
**Bundle ID:** com.groupme.iphone-app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=392796698">392796698</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/groupme/id392796698?mt=8&uo=4">https://itunes.apple.com/us/app/groupme/id392796698?mt=8&uo=4</a>
**App Version:** 5.6.1
**Seller:** Skype Communications S.a.r.l
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/skype-communications-s.a.r.l/id304219585?mt=8&uo=4>© Skype Communications S.a.r.l</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/48/31/39/483139b0-7fc1-4ac0-0b0d-93b448c3d359/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18888863/74f77822-84fa-11e6-9d4f-ad898f2ad33a.png)

**Comment by illinikev** [comment]
Icon needs update

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18888847/5cea71e4-84fa-11e6-9e27-09736a37d5b7.png)
https://cloud.githubusercontent.com/assets/22012363/18888847/5cea71e4-84fa-11e6-9e27-09736a37d5b7.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18888842/57cb6ba0-84fa-11e6-81bb-039148f9f3cc.png

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18888863/74f77822-84fa-11e6-9d4f-ad898f2ad33a.png)
https://cloud.githubusercontent.com/assets/22012363/18888863/74f77822-84fa-11e6-9d4f-ad898f2ad33a.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18888862/726d4d66-84fa-11e6-9124-8034adc4d579.png

**Comment by ivanov007** [comment]
@BrokenCommander I think the second one will do it :+1:
