### ISSUE TITLE
Field Tools

### ISSUE THREAD

**Issue by jeremyblake** [glasklart/hd#2125]
**App Name:** Field Tools
**Bundle ID:** net.sourceforge.iphonefieldtools
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=305817254">305817254</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/field-tools/id305817254?mt=8&uo=4">https://itunes.apple.com/us/app/field-tools/id305817254?mt=8&uo=4</a>
**App Version:** 2.3.3
**Seller:** Brad Sokol
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brad-sokol/id305817257?uo=4>© Brad Sokol</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/99/c3/95/99c395dc-e225-0565-e0cd-3f17c39fac84/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18811539/6005b544-82b3-11e6-95a0-4d6002f291a9.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18811539/6005b544-82b3-11e6-95a0-4d6002f291a9.png)
https://cloud.githubusercontent.com/assets/20930745/18811539/6005b544-82b3-11e6-95a0-4d6002f291a9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18811535/25da3a16-82b3-11e6-83ae-6a7e6c2a2390.png
