### ISSUE TITLE
ShowTool LD

### ISSUE THREAD

**Issue by BrianMitchL** [glasklart/hd#2128]
**App Name:** ShowTool LD
**Bundle ID:** com.danielmurfin.showtoolld
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=319523749">319523749</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/showtool-ld/id319523749?mt=8&uo=4">https://itunes.apple.com/us/app/showtool-ld/id319523749?mt=8&uo=4</a>
**App Version:** 3.0.3
**Seller:** Daniel Murfin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/daniel-murfin/id319523752?uo=4>© Daniel Murfin</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/9f/1b/66/9f1b66b2-a94a-27cc-6f5c-f73836a4b6dd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19896965/74fc07f8-a056-11e6-9580-edb4e97661b7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19896965/74fc07f8-a056-11e6-9580-edb4e97661b7.png)
https://cloud.githubusercontent.com/assets/20930745/19896965/74fc07f8-a056-11e6-9580-edb4e97661b7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19896992/8c1e5bc0-a056-11e6-9538-0c6c67e4db41.png
