### ISSUE TITLE
ZEDGE™ Ringtones & Wallpapers

### ISSUE THREAD

**Issue by glasklartFan93** [glasklart/hd#2129]
**App Name:** ZEDGE™ Ringtones & Wallpapers
**Bundle ID:** com.zedge.Zedge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=584485870">584485870</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zedge-ringtones-wallpapers/id584485870?mt=8&uo=4">https://itunes.apple.com/us/app/zedge-ringtones-wallpapers/id584485870?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Zedge Holdings Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zedge/id584485874?uo=4>© ZEDGE</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/b8/c4/13/b8c4130d-ce48-86a0-fc18-09b68a6cec09/mzl.shdoicvd.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10384355/49e0e90c-6e3a-11e5-857e-9dfa9b27f650.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10384355/49e0e90c-6e3a-11e5-857e-9dfa9b27f650.png)
https://cloud.githubusercontent.com/assets/10730122/10384355/49e0e90c-6e3a-11e5-857e-9dfa9b27f650.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10384354/4776a7e2-6e3a-11e5-9b11-5b1c41a21652.png
