### ISSUE TITLE
GeoDrop HD

### ISSUE THREAD

**Issue by glasklartFan93** [glasklart/hd#2130]
**App Name:** GeoDrop HD
**Bundle ID:** de.chronocore.geodrop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478344246">478344246</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/geodrop-hd/id478344246?mt=8&uo=4">https://itunes.apple.com/us/app/geodrop-hd/id478344246?mt=8&uo=4</a>
**App Version:** 1.50
**Seller:** Stefan Kogler
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stefan-kogler/id327939697?uo=4>© Stefan Kogler</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/72/bb/66/72bb6698-7969-6c3a-7874-f8c618b00cfa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19900214/070850dc-a063-11e6-9490-82b48cd65e23.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19900214/070850dc-a063-11e6-9490-82b48cd65e23.png)
https://cloud.githubusercontent.com/assets/20930745/19900214/070850dc-a063-11e6-9490-82b48cd65e23.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19900261/27243732-a063-11e6-9a7c-940c4b04663c.png
