### ISSUE TITLE
Little Things® Forever

### ISSUE THREAD

**Issue by glasklartFan93** [glasklart/hd#2131]
**App Name:** Little Things® Forever
**Bundle ID:** com.klicktock.littlethings2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520762327">520762327</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/little-things-forever/id520762327?mt=8&uo=4">https://itunes.apple.com/us/app/little-things-forever/id520762327?mt=8&uo=4</a>
**App Version:** 1.7.0
**Seller:** KlickTock Pty Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/klicktock/id348840966?uo=4">© KLICKTOCK</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple127/v4/62/ff/f8/62fff85a-1618-3b40-264e-08062783a61c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com klicktock littlethings2-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38596613-d55d23e4-3d52-11e8-9be3-fef750baf0d7.png)

**Comment by dreamnet** [comment]
![com klicktock littlethings2-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38596613-d55d23e4-3d52-11e8-9be3-fef750baf0d7.png)
https://user-images.githubusercontent.com/2068130/38596613-d55d23e4-3d52-11e8-9be3-fef750baf0d7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38596631-e584e00e-3d52-11e8-868f-7e5ab5ab3ff1.png
