### ISSUE TITLE
Huntington Mobile

### ISSUE THREAD

**Issue by jeremyblake** [glasklart/hd#2135]
**App Name:** Huntington Mobile
**Bundle ID:** com.huntington.m
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441599004">441599004</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/huntington-mobile/id441599004?mt=8&uo=4">https://itunes.apple.com/us/app/huntington-mobile/id441599004?mt=8&uo=4</a>
**App Version:** 3.2.105
**Seller:** Brian Knickle
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/huntington-national-bank/id441599007?uo=4>© Huntington National Bank</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/35/2d/67/352d679c-cefb-728e-831f-e7b280af6efc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19738779/f1acdd1a-9bb8-11e6-9ffa-0df017c282fa.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19738779/f1acdd1a-9bb8-11e6-9ffa-0df017c282fa.png)
https://cloud.githubusercontent.com/assets/2068130/19738779/f1acdd1a-9bb8-11e6-9ffa-0df017c282fa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19738794/0289bd60-9bb9-11e6-8f16-6a565f759cae.png
