### ISSUE TITLE
Posing App

### ISSUE THREAD

**Issue by jeremyblake** [glasklart/hd#2136]
**App Name:** Posing App
**Bundle ID:** lv.mendo.posing-app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492085243">492085243</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/posing-app/id492085243?mt=8&uo=4">https://itunes.apple.com/us/app/posing-app/id492085243?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** SIA MENDO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sia-mendo/id492085246?uo=4>© SIA MENDO</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/f3/d2/be/f3d2bee1-0016-c8e4-dd3a-98ecaa9d2bda/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19860492/2bb0cb9c-9f89-11e6-9f39-4b676988e7e5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19860492/2bb0cb9c-9f89-11e6-9f39-4b676988e7e5.png)
https://cloud.githubusercontent.com/assets/20930745/19860492/2bb0cb9c-9f89-11e6-9f39-4b676988e7e5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19860559/6ebd53c4-9f89-11e6-9330-bfcd3e2b7d0b.png
