### ISSUE TITLE
Name The Meme

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2137]
**App Name:** Name The Meme
**Bundle ID:** it.ff.namethememe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542053362">542053362</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/name-the-meme/id542053362?mt=8&uo=4">https://itunes.apple.com/us/app/name-the-meme/id542053362?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** APPSTYX SRL SEMPLIFICATA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/appstyx/id1025725393?uo=4">© Appstyx</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/46/aa/b0/46aab0f9-c8a3-95a6-b1d5-ca8f9b49fff2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19860895/cb075638-9f8a-11e6-9422-097e537eaeae.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19860895/cb075638-9f8a-11e6-9422-097e537eaeae.png)
https://cloud.githubusercontent.com/assets/20930745/19860895/cb075638-9f8a-11e6-9422-097e537eaeae.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19860927/eb81c074-9f8a-11e6-84f2-63b68e1b3a80.png
