### ISSUE TITLE
GS Match Zone

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2141]
**App Name:** GS Match Zone
**Bundle ID:** com.crenno.gsmatchzone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=600610430">600610430</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gs-match-zone/id600610430?mt=8&uo=4">https://itunes.apple.com/us/app/gs-match-zone/id600610430?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** CRENNO Bilisim Hizmetleri Ar-Ge Sanayi ve Ticaret Ltd. Sti.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/crenno-technologies/id403505972?uo=4">© CRENNO Technologies</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple2/v4/6f/b0/3a/6fb03a7a-ddce-668a-ee67-c159546587bc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19861410/bcc06d9c-9f8c-11e6-80cc-efa4af3ac33f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19861410/bcc06d9c-9f8c-11e6-80cc-efa4af3ac33f.png)
https://cloud.githubusercontent.com/assets/20930745/19861410/bcc06d9c-9f8c-11e6-80cc-efa4af3ac33f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19861488/ffeaa6c8-9f8c-11e6-8efc-e0afe85f8f7b.png
