### ISSUE TITLE
bwin Sports – live streaming, betting & scores

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2143]
**App Name:** bwin Sports – live streaming, betting & scores
**Bundle ID:** com.bwin.sportsbook.at
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393760245">393760245</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/bwin-sports-live-streaming/id393760245?mt=8&uo=4">https://itunes.apple.com/gb/app/bwin-sports-live-streaming/id393760245?mt=8&uo=4</a>
**App Version:** 16.10.1
**Seller:** ElectraWorks Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/electraworks-limited/id681785892?uo=4>© ElectraWorks Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/65/79/85/65798538-d7a6-39d2-6988-38a10bdf6b91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19882557/d01b0bcc-a00e-11e6-90df-ba781465c420.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19882557/d01b0bcc-a00e-11e6-90df-ba781465c420.png)
https://cloud.githubusercontent.com/assets/20930745/19882557/d01b0bcc-a00e-11e6-90df-ba781465c420.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19882577/ea64a8bc-a00e-11e6-9769-89212eb58de0.png
