### ISSUE TITLE
WESTbahn App

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2146]
**App Name:** WESTbahn App
**Bundle ID:** at.westbahn.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1289155633">1289155633</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/westbahn-app/id1289155633?mt=8&uo=4">https://itunes.apple.com/us/app/westbahn-app/id1289155633?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** WESTbahn Management GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/westbahn-management-gmbh/id514013342?uo=4">© WESTbahn Management GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/b8/ae/97/b8ae9737-02f5-b053-9775-f1139d172dc6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32388824-320fa2e4-c0c9-11e7-9bce-f7b4bc497659.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32388824-320fa2e4-c0c9-11e7-9bce-f7b4bc497659.png)
https://user-images.githubusercontent.com/2068130/32388824-320fa2e4-c0c9-11e7-9bce-f7b4bc497659.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32388846-427058fe-c0c9-11e7-89fc-b528cca8133b.png
