### ISSUE TITLE
MouthOff™

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2151]
**App Name:** MouthOff™
**Bundle ID:** com.ustwo.MouthOff
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306588353">306588353</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mouthoff/id306588353?mt=8&uo=4">https://itunes.apple.com/us/app/mouthoff/id306588353?mt=8&uo=4</a>
**App Version:** 3.1.4
**Seller:** ustwo Fampany Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ustwo/id1101244271?uo=4">© ustwo</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/dc/53/b3/dc53b3f5-f3ab-a11c-bb70-f119963ade1f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41506903-fdb0d92c-7226-11e8-81db-d25f62431beb.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41506903-fdb0d92c-7226-11e8-81db-d25f62431beb.png)
https://user-images.githubusercontent.com/2068130/41506903-fdb0d92c-7226-11e8-81db-d25f62431beb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41506906-0c566276-7227-11e8-92f1-3aba19fad2db.png
