### ISSUE TITLE
OnTheSnow Ski & Snow Report

### ISSUE THREAD

**Issue by igogreen** [glasklart/hd#2158]
**App Name:** OnTheSnow Ski & Snow Report
**Bundle ID:** com.skireport.SkiApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300412347">300412347</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/onthesnow-ski-snow-report/id300412347?mt=8&uo=4">https://itunes.apple.com/us/app/onthesnow-ski-snow-report/id300412347?mt=8&uo=4</a>
**App Version:** 6.1
**Seller:** SkiReport.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/skireport.com/id300412350?uo=4>© SkiReport.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/46/05/d1/4605d13f-94c3-d2fc-8cd1-a464009fd088/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19739195/443b83e6-9bba-11e6-863b-02098344f802.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19739195/443b83e6-9bba-11e6-863b-02098344f802.png)
https://cloud.githubusercontent.com/assets/2068130/19739195/443b83e6-9bba-11e6-863b-02098344f802.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19739202/51fffb9c-9bba-11e6-9261-51eb4451034c.png
