### ISSUE TITLE
Hungry Shark Evolution

### ISSUE THREAD

**Issue by igogreen** [glasklart/hd#2160]
**App Name:** Hungry Shark Evolution
**Bundle ID:** com.fgol.HungrySharkEvolution
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=535500008">535500008</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hungry-shark-evolution/id535500008?mt=8&uo=4">https://itunes.apple.com/us/app/hungry-shark-evolution/id535500008?mt=8&uo=4</a>
**App Version:** 4.7.0
**Seller:** Ubisoft
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ubisoft/id317644720?uo=4">© Ubisoft</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/72/3b/c1/723bc120-526e-57f3-68cb-a7f63824894c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/25048427/175c5774-2102-11e7-9502-f6753be40cd8.png)

**Comment by ivanov007** [comment]
needs update

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/25048427/175c5774-2102-11e7-9502-f6753be40cd8.png)
https://cloud.githubusercontent.com/assets/3090247/25048427/175c5774-2102-11e7-9502-f6753be40cd8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/25048428/175f8dea-2102-11e7-84b4-fc40480b5f1e.png
