### ISSUE TITLE
Inbox Pro, Outlook Edition

### ISSUE THREAD

**Issue by alex810158** [glasklart/hd#2162]
**App Name:** Inbox Pro, Outlook Edition
**Bundle ID:** com.codebeforedawn.lookout
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=434458848">434458848</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inbox-pro-outlook-edition/id434458848?mt=8&uo=4">https://itunes.apple.com/us/app/inbox-pro-outlook-edition/id434458848?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** Code Before Dawn, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/code-before-dawn-inc/id434458851?uo=4>© Code Before Dawn, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/48/ae/ca/48aeca55-84da-923a-59a5-2647388eae65/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19490286/d907a34e-956e-11e6-9c91-4150e012fef6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19490286/d907a34e-956e-11e6-9c91-4150e012fef6.png)
https://cloud.githubusercontent.com/assets/20930745/19490286/d907a34e-956e-11e6-9c91-4150e012fef6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19490317/f7d38126-956e-11e6-99fd-2aae90608048.png
