### ISSUE TITLE
Personal Banking

### ISSUE THREAD

**Issue by alex810158** [glasklart/hd#2163]
**App Name:** Personal Banking
**Bundle ID:** uk.co.santander.santanderUK
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=482973524">482973524</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/personal-banking/id482973524?mt=8&uo=4">https://itunes.apple.com/us/app/personal-banking/id482973524?mt=8&uo=4</a>
**App Version:** 3.9
**Seller:** Santander UK plc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/santander-uk-plc/id482973527?uo=4>© Santander UK plc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/56/ed/b4/56edb4bc-b5ed-121e-e668-8a0b40aea9ec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19850689/1537d3b2-9f5a-11e6-8930-7d163408377f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19850689/1537d3b2-9f5a-11e6-8930-7d163408377f.png)
https://cloud.githubusercontent.com/assets/20930745/19850689/1537d3b2-9f5a-11e6-8930-7d163408377f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19850704/2dd14a48-9f5a-11e6-8dd8-b9554267148b.png
