### ISSUE TITLE
RetailMeNot Shopping Deals, Coupons, Savings

### ISSUE THREAD

**Issue by khattakr** [glasklart/hd#2169]
**App Name:** RetailMeNot Shopping Deals, Coupons, Savings
**Bundle ID:** com.whaleshark.retailmenot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=521207075">521207075</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/retailmenot-shopping-deals/id521207075?mt=8&uo=4">https://itunes.apple.com/us/app/retailmenot-shopping-deals/id521207075?mt=8&uo=4</a>
**App Version:** 4.18.1
**Seller:** RetailMeNot, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/retailmenot-inc./id521207078?uo=4>© RetailMeNot, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/3b/7f/25/3b7f250f-6244-c26e-155f-3d0104c7e3f9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19454850/f9ab9092-94ba-11e6-894e-ec592b7e0e1f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19454850/f9ab9092-94ba-11e6-894e-ec592b7e0e1f.png)
https://cloud.githubusercontent.com/assets/20930745/19454850/f9ab9092-94ba-11e6-894e-ec592b7e0e1f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19454868/16b41650-94bb-11e6-9da6-b6319babae98.png
