### ISSUE TITLE
Cadremploi : offres d'emploi cadre et dirigeant

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#217]
**App Name:** Cadremploi : offres d'emploi cadre et dirigeant
**Bundle ID:** com.adenclassifieds.Cadremploi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=383089648">383089648</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cadremploi-offres-demploi/id383089648?mt=8&uo=4">https://itunes.apple.com/us/app/cadremploi-offres-demploi/id383089648?mt=8&uo=4</a>
**App Version:** 4.5.5
**Seller:** Figaro Classifieds
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/figaro-classifieds/id358085434?uo=4>© Figaro Classifieds</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/cc/bf/60/ccbf6055-42c2-6fbb-96f4-4c52f8c500ad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19735491/1bb70304-9bac-11e6-8246-2deb445506bd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19735491/1bb70304-9bac-11e6-8246-2deb445506bd.png)
https://cloud.githubusercontent.com/assets/2068130/19735491/1bb70304-9bac-11e6-8246-2deb445506bd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19735507/2f89e75c-9bac-11e6-8415-d03ae047ee55.png
