### ISSUE TITLE
Reuters

### ISSUE THREAD

**Issue by khattakr** [glasklart/hd#2170]
**App Name:** Reuters
**Bundle ID:** com.thomsonreuters.Reuters
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=602660809">602660809</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reuters/id602660809?mt=8&uo=4">https://itunes.apple.com/us/app/reuters/id602660809?mt=8&uo=4</a>
**App Version:** 2.6.4
**Seller:** Thomson Reuters
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/thomson-reuters/id314213170?uo=4>© Thomson Reuters</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/b2/0e/0c/b20e0c7d-83dd-0d08-f421-d32f59e99ed6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618130/58092f0c-9842-11e6-80e8-005906d0482b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618130/58092f0c-9842-11e6-80e8-005906d0482b.png)
https://cloud.githubusercontent.com/assets/20930745/19618130/58092f0c-9842-11e6-80e8-005906d0482b.png

Source:
(https://cloud.githubusercontent.com/assets/20930745/19618142/6e5dbe94-9842-11e6-8a39-9421d6120bef.png
