### ISSUE TITLE
Angry Birds Free

### ISSUE THREAD

**Issue by devilwings** [glasklart/hd#2172]
**App Name:** Angry Birds Free
**Bundle ID:** com.rovio.angrybirdsfree
**iTunes ID:** 409807569
**iTunes URL:** https://itunes.apple.com/us/app/angry-birds-free/id409807569?mt=8&uo=4
**App Version:** 1.5.0
**Seller:** Rovio Entertainment Ltd
**Supported Devices:** iPodTouchThirdGen, iPodTouchourthGen, iPadWifi, iPhone-3GS, iPad2Wifi, iPhone4, iPad23G, iPad3G
**Original Artwork:**
<img src="http://a1271.phobos.apple.com/us/r1000/070/Purple/v4/d7/43/22/d7432219-5579-4a4c-2998-c47834b54c00/mzl.lzdwjtbo.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18808571/1cba1a70-8266-11e6-9b66-27c91955a326.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18808571/1cba1a70-8266-11e6-9b66-27c91955a326.png)
https://cloud.githubusercontent.com/assets/2068130/18808571/1cba1a70-8266-11e6-9b66-27c91955a326.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18808576/2b3154ce-8266-11e6-8b21-586b8f8de587.png
