### ISSUE TITLE
FallDown!

### ISSUE THREAD

**Issue by devilwings** [glasklart/hd#2175]
**App Name:** FallDown!
**Bundle ID:** FallDown
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=323493586">323493586</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/falldown!/id323493586?mt=8&uo=4">https://itunes.apple.com/us/app/falldown!/id323493586?mt=8&uo=4</a>
**App Version:** 1.17
**Seller:** Hannes Jensen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hannes-jensen/id323493589?uo=4>© Hannes Jensen</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/d8/46/eb/d846eb72-0e71-d628-ebec-8ee7aa6a046f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13372437/0c0d9ba2-dd43-11e5-9a4b-37bf979e20b6.png)

**Comment by Anuskuss** [comment]
Someone should assimilate [Falldown!](https://github.com/glasklart/hd/issues/2175) and [Falldown! 2](https://github.com/glasklart/hd/issues/2918)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13372437/0c0d9ba2-dd43-11e5-9a4b-37bf979e20b6.png)
https://cloud.githubusercontent.com/assets/2068130/13372437/0c0d9ba2-dd43-11e5-9a4b-37bf979e20b6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13372438/19506f92-dd43-11e5-8a78-f2bfacbd8227.png
