### ISSUE TITLE
Apec : offres d’emploi cadres

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#218]
**App Name:** Apec : offres d’emploi cadres
**Bundle ID:** fr.apec.cadres
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=387689033">387689033</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/apec-offres-demploi-cadres/id387689033?mt=8&uo=4">https://itunes.apple.com/us/app/apec-offres-demploi-cadres/id387689033?mt=8&uo=4</a>
**App Version:** 3.3.3
**Seller:** APEC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apec/id387689036?uo=4>© Apec</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/53/12/88/531288b9-4d14-9e5d-64ef-e8ef10cfbe1f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19401998/c97906f6-925e-11e6-9555-e765e248b867.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19401998/c97906f6-925e-11e6-9555-e765e248b867.png)
https://cloud.githubusercontent.com/assets/20930745/19401998/c97906f6-925e-11e6-9555-e765e248b867.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19402006/d905b376-925e-11e6-98cb-3b4880a40da2.png
