### ISSUE TITLE
WallFive Retina Wallpapers for iPhone5

### ISSUE THREAD

**Issue by devilwings** [glasklart/hd#2180]
**App Name:** WallFive Retina Wallpapers for iPhone5
**Bundle ID:** com.zero1infinity.wallfive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=573728388">573728388</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wallfive-retina-wallpapers/id573728388?mt=8&uo=4">https://itunes.apple.com/us/app/wallfive-retina-wallpapers/id573728388?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Oguz Karadeniz
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/oguz-karadeniz/id475152583?uo=4>© Oguz Karadeniz</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/c2/00/bc/c200bcba-ed3b-d0f2-cbf1-3d1a100e016e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420373/a6e0080a-93ea-11e6-8808-896ffd9bef4b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420373/a6e0080a-93ea-11e6-8808-896ffd9bef4b.png)
https://cloud.githubusercontent.com/assets/20930745/19420373/a6e0080a-93ea-11e6-8808-896ffd9bef4b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19420383/c38883ec-93ea-11e6-99a6-49736d1c3490.png
