### ISSUE TITLE
Wallpapers HD : New themes and backgrounds

### ISSUE THREAD

**Issue by devilwings** [glasklart/hd#2182]
**App Name:** Wallpapers HD : New themes and backgrounds
**Bundle ID:** com.apptao.retinawallpapers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=384922950">384922950</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wallpapers-hd-new-themes-backgrounds/id384922950?mt=8&uo=4">https://itunes.apple.com/us/app/wallpapers-hd-new-themes-backgrounds/id384922950?mt=8&uo=4</a>
**App Version:** 5.6
**Seller:** Yin Yu
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yin-yu/id941591823?uo=4>© Yin Yu</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/69/e0/a7/69e0a7e7-d462-baa0-d1af-c7eee0ee8d68/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19628853/bce5b23a-9967-11e6-90bb-45f98ac3530c.png)

**Comment by Anonyymikko** [comment]
Hi guys, this one doesn't theme the app icon for me.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19628853/bce5b23a-9967-11e6-90bb-45f98ac3530c.png)
https://cloud.githubusercontent.com/assets/20930745/19628853/bce5b23a-9967-11e6-90bb-45f98ac3530c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19628856/d59034d6-9967-11e6-994e-bb56def8dbf9.png
