### ISSUE TITLE
Halifax Mobile Banking

### ISSUE THREAD

**Issue by hotwheelz** [glasklart/hd#2186]
**App Name:** Halifax Mobile Banking
**Bundle ID:** com.halifax.mobilebank
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=486355738">486355738</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/halifax-mobile-banking/id486355738?uo=4">https://apps.apple.com/us/app/halifax-mobile-banking/id486355738?uo=4</a>
**App Version:** 48.05
**Seller:** Lloyds Banking Group
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lloyds-banking-group/id469964523?uo=4">© Lloyds Banking Group</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/2f/16/5f/2f165f3e-14d9-aacf-2480-2d9f88883975/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60640302-c904ed80-9e26-11e9-899b-9865b5d1fe89.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20109809/03c06dd6-a5e2-11e6-8380-5185ba94ffd9.png)
https://cloud.githubusercontent.com/assets/20930745/20109809/03c06dd6-a5e2-11e6-8380-5185ba94ffd9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20109872/41e9a9e2-a5e2-11e6-8c38-5dc480f6c407.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60640302-c904ed80-9e26-11e9-899b-9865b5d1fe89.png)
https://user-images.githubusercontent.com/2068130/60640302-c904ed80-9e26-11e9-899b-9865b5d1fe89.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60640321-d9b56380-9e26-11e9-887b-90789054fb5b.png
