### ISSUE TITLE
La Banque Postale

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#219]
**App Name:** La Banque Postale
**Bundle ID:** fr.labanquepostale.moncompte
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409362880">409362880</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/la-banque-postale/id409362880?mt=8&uo=4">https://itunes.apple.com/us/app/la-banque-postale/id409362880?mt=8&uo=4</a>
**App Version:** 5.7.0
**Seller:** La Banque Postale
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/la-banque-postale/id315665011?uo=4">© La Banque Postale</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/e8/2d/18/e82d18c7-6e5e-4562-715a-2071edeba23c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32396680-9177b650-c0e6-11e7-8a40-338cfd6cd680.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32396680-9177b650-c0e6-11e7-8a40-338cfd6cd680.png)
https://user-images.githubusercontent.com/2068130/32396680-9177b650-c0e6-11e7-8a40-338cfd6cd680.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32396699-a4070b22-c0e6-11e7-8d97-ac60b6ad69eb.png
