### ISSUE TITLE
LOVEFiLM By Post UK for iPhone

### ISSUE THREAD

**Issue by hotwheelz** [glasklart/hd#2191]
**App Name:** LOVEFiLM By Post UK for iPhone
**Bundle ID:** com.lovefilm.lovefilmuk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=353141812">353141812</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/lovefilm-by-post-uk-for-iphone/id353141812?mt=8&uo=4">https://itunes.apple.com/gb/app/lovefilm-by-post-uk-for-iphone/id353141812?mt=8&uo=4</a>
**App Version:** 3.0.3
**Seller:** LOVEFiLM
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/lovefilm/id353141815?uo=4>© LOVEFiLM</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/21/c6/43/21c643c7-2536-7f34-9ee6-af333ded65f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19899175/5d94b07a-a05f-11e6-9898-e35a801d86f9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19899175/5d94b07a-a05f-11e6-9898-e35a801d86f9.png)
https://cloud.githubusercontent.com/assets/20930745/19899175/5d94b07a-a05f-11e6-9898-e35a801d86f9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19899195/745b39e6-a05f-11e6-98ba-4c971e3bdc20.png
