### ISSUE TITLE
Manchester Evening News

### ISSUE THREAD

**Issue by hotwheelz** [glasklart/hd#2193]
**App Name:** Manchester Evening News
**Bundle ID:** com.spreednews.manchesteren
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=334456452">334456452</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/manchester-evening-news/id334456452?mt=8&uo=4">https://itunes.apple.com/us/app/manchester-evening-news/id334456452?mt=8&uo=4</a>
**App Version:** 2.75
**Seller:** Trinity Mirror Digital Media Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/trinity-mirror-digital-media/id360153141?uo=4">© Trinity Mirror Digital Media Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/fc/3c/0e/fc3c0e35-e68f-78cc-f187-381826b82d3a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20237561/5025abcc-a8d6-11e6-82b7-ecb45a742705.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20237561/5025abcc-a8d6-11e6-82b7-ecb45a742705.png)
https://cloud.githubusercontent.com/assets/20930745/20237561/5025abcc-a8d6-11e6-82b7-ecb45a742705.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20237562/69f6088a-a8d6-11e6-8ebc-50e063eebc85.png
