### ISSUE TITLE
BBC Sport

### ISSUE THREAD

**Issue by YouDontKnow** [glasklart/hd#2194]
**App Name:** BBC Sport
**Bundle ID:** uk.co.bbc.sport
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377388936">377388936</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/bbc-sport/id377388936?mt=8&uo=4">https://itunes.apple.com/gb/app/bbc-sport/id377388936?mt=8&uo=4</a>
**App Version:** 1.8.1
**Seller:** Media Applications Technologies Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/media-applications-technologies/id377382258?uo=4>© Media Applications Technologies Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/b0/90/ec/b090ec3f-aaeb-5b07-69a6-9cefc7a1e95f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11389815/5f867964-9344-11e5-8ace-417d0fa80e85.png)

**Comment by illinikev** [comment]
iTunes ID changed to 594842980.

https://itunes.apple.com/us/app/bbc-sport/id594842980?mt=8

**App Name:** BBC Sport
**Bundle ID:** uk.co.bbc.sportww
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=594842980">594842980</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bbc-sport/id594842980?mt=8&uo=4">https://itunes.apple.com/us/app/bbc-sport/id594842980?mt=8&uo=4</a>
**App Version:** 1.7.2
**Seller:** BBC Worldwide LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bbc-worldwide/id344138454?uo=4>© BBC Worldwide</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/dc/ec/fa/dcecfa9e-9cf0-91a1-1d5e-5f8825f32a17/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**

**Comment by ivanov007** [comment]
@illinikev it's a different app, you need to open a new issue

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11389815/5f867964-9344-11e5-8ace-417d0fa80e85.png)
https://cloud.githubusercontent.com/assets/2068130/11389815/5f867964-9344-11e5-8ace-417d0fa80e85.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11389824/70533d4a-9344-11e5-8749-2dbfce1105d1.png
