### ISSUE TITLE
Sky Sports for iPhone

### ISSUE THREAD

**Issue by YouDontKnow** [glasklart/hd#2195]
**App Name:** Sky Sports for iPhone
**Bundle ID:** com.bskyb.ssniphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=500102120">500102120</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/sky-sports-for-iphone/id500102120?mt=8&uo=4">https://itunes.apple.com/gb/app/sky-sports-for-iphone/id500102120?mt=8&uo=4</a>
**App Version:** 7.3
**Seller:** Sky UK Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/sky-uk-limited/id301250228?uo=4">© Sky UK Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/87/c2/c9/87c2c9b3-d474-ff21-3804-0aeb4f0363c1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19902390/e4187996-a06a-11e6-9cd6-ea490dec097c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19902390/e4187996-a06a-11e6-9cd6-ea490dec097c.png)
https://cloud.githubusercontent.com/assets/20930745/19902390/e4187996-a06a-11e6-9cd6-ea490dec097c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19902409/fdebe70e-a06a-11e6-9247-b374d2274600.png
