### ISSUE TITLE
Geo Walk: World Factbook & Natural Science for Kid

### ISSUE THREAD

**Issue by YouDontKnow** [glasklart/hd#2196]
**App Name:** Geo Walk: World Factbook & Natural Science for Kid
**Bundle ID:** com.vitotechnology.GEOWalkHD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=379602269">379602269</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/geo-walk-world-factbook-natural-science-for-kid/id379602269?mt=8&uo=4">https://itunes.apple.com/us/app/geo-walk-world-factbook-natural-science-for-kid/id379602269?mt=8&uo=4</a>
**App Version:** 2.6.2
**Seller:** Vito Technology Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vito-technology-inc/id289641503?uo=4">© Vito Technology Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/a3/01/60/a3016079-0e29-6546-c765-31cf8208f37c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38184897-37d66418-364b-11e8-9778-5559b49bd8c8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38184897-37d66418-364b-11e8-9778-5559b49bd8c8.png)
https://user-images.githubusercontent.com/2068130/38184897-37d66418-364b-11e8-9778-5559b49bd8c8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38184905-47452d3a-364b-11e8-911f-e4616de16184.png
