### ISSUE TITLE
Sky Sports Live Football Score Centre

### ISSUE THREAD

**Issue by YouDontKnow** [glasklart/hd#2197]
**App Name:** Sky Sports Live Football Score Centre
**Bundle ID:** com.bskyb.football
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=325185696">325185696</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/sky-sports-live-football-score/id325185696?mt=8&uo=4">https://itunes.apple.com/gb/app/sky-sports-live-football-score/id325185696?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** Sky UK Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/sky-uk-limited/id301250228?uo=4">© Sky UK Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/64/76/8c/64768ca5-3e47-aba4-ccce-eace29f9c525/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19902653/dee4def0-a06b-11e6-81b4-ee1e8b935ebc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19902653/dee4def0-a06b-11e6-81b4-ee1e8b935ebc.png)
https://cloud.githubusercontent.com/assets/20930745/19902653/dee4def0-a06b-11e6-81b4-ee1e8b935ebc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19902675/f55ecd6c-a06b-11e6-8786-315a85146449.png
