### ISSUE TITLE
PagesJaunes – Trouvez plus que des coordonnées

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#220]
**App Name:** PagesJaunes – Trouvez plus que des coordonnées
**Bundle ID:** com.pagesjaunes.widgetiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=299618546">299618546</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pagesjaunes-trouvez-plus-que/id299618546?mt=8&uo=4">https://itunes.apple.com/us/app/pagesjaunes-trouvez-plus-que/id299618546?mt=8&uo=4</a>
**App Version:** 8.0.1
**Seller:** PagesJaunes SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pagesjaunes-sa/id299618549?uo=4>© PagesJaunes SA</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/10/98/f4/1098f4c0-cedc-1dac-4941-4d6851e8df04/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625394/89f733e4-9917-11e6-9fac-6b95bc975eef.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625394/89f733e4-9917-11e6-9fac-6b95bc975eef.png)
https://cloud.githubusercontent.com/assets/20930745/19625394/89f733e4-9917-11e6-9fac-6b95bc975eef.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625401/a4bcd490-9917-11e6-8272-481147d3c1d2.png
