### ISSUE TITLE
08 Wizard

### ISSUE THREAD

**Issue by YouDontKnow** [glasklart/hd#2203]
**App Name:** 08 Wizard
**Bundle ID:** com.skycom.08Wizard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=420396078">420396078</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/08-wizard/id420396078?mt=8&uo=4">https://itunes.apple.com/gb/app/08-wizard/id420396078?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Barritel Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/barritel-ltd/id414662093?uo=4>© Barritel Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/de/d6/b1/ded6b18f-0fad-a6f4-2f1e-92fb76446122/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621424/d309fd36-9891-11e6-8e87-e65167d2fee1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621424/d309fd36-9891-11e6-8e87-e65167d2fee1.png)
https://cloud.githubusercontent.com/assets/20930745/19621424/d309fd36-9891-11e6-8e87-e65167d2fee1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19621426/e9325662-9891-11e6-96f2-d47ef86efaa5.png
