### ISSUE TITLE
TV Programm App Fernsehprogramm und TV-Zeitung mit Live TV und Online TV Tipps für heute

### ISSUE THREAD

**Issue by askarl** [glasklart/hd#2207]
**App Name:** TV Programm App Fernsehprogramm und TV-Zeitung mit Live TV und Online TV Tipps für heute
**Bundle ID:** de.couchfunk.TV-Programm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=587337688">587337688</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/tv-programm-app-fernsehprogramm/id587337688?mt=8&uo=4">https://itunes.apple.com/de/app/tv-programm-app-fernsehprogramm/id587337688?mt=8&uo=4</a>
**App Version:** 4.1.2
**Seller:** Couchfunk GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/couchfunk-gmbh/id470915736?uo=4>© Couchfunk GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/2f/95/d6/2f95d635-f92e-ad03-1df5-3ad7fc33dd15/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18725227/b0661ec8-803f-11e6-9f78-af86ec593ee7.png)

**Comment by Checkit23** [comment]
Updated for 5.0.0:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18725227/b0661ec8-803f-11e6-9f78-af86ec593ee7.png)

https://cloud.githubusercontent.com/assets/16171251/18725227/b0661ec8-803f-11e6-9f78-af86ec593ee7.png

Source: 
https://cloud.githubusercontent.com/assets/16171251/18725244/c54b4822-803f-11e6-8e38-32af6b6301ef.png
