### ISSUE TITLE
Leboncoin

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#221]
**App Name:** Leboncoin
**Bundle ID:** fr.leboncoin.Leboncoin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484115113">484115113</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/leboncoin/id484115113?mt=8&uo=4">https://itunes.apple.com/fr/app/leboncoin/id484115113?mt=8&uo=4</a>
**App Version:** 3.19.1
**Seller:** Schibsted France
**Developer:** <a target="_blank" href=https://itunes.apple.com/fr/developer/schibsted-france/id484115116?uo=4>© Schibsted France</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/55/91/4a/55914a88-f1f9-dfea-7ea6-644e8be7ca56/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625438/c333e462-9918-11e6-9969-f587f5e2106a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625438/c333e462-9918-11e6-9969-f587f5e2106a.png)
https://cloud.githubusercontent.com/assets/20930745/19625438/c333e462-9918-11e6-9969-f587f5e2106a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625439/d80f3706-9918-11e6-8012-507bdf1602c6.png
