### ISSUE TITLE
PhotoFunia

### ISSUE THREAD

**Issue by alex810158** [glasklart/hd#2215]
**App Name:** PhotoFunia
**Bundle ID:** com.photofunia.photofunia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=321240709">321240709</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photofunia/id321240709?mt=8&uo=4">https://itunes.apple.com/us/app/photofunia/id321240709?mt=8&uo=4</a>
**App Version:** 4.0.3
**Seller:** Capsule Digital Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/capsule-digital-ltd/id843867021?uo=4>© Capsule Digital Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/97/be/8a/97be8a59-9cd1-1632-27f1-d9fb66f27611/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626378/ab6ec5e6-9930-11e6-8d80-eafffbea36c8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626378/ab6ec5e6-9930-11e6-8d80-eafffbea36c8.png)
https://cloud.githubusercontent.com/assets/20930745/19626378/ab6ec5e6-9930-11e6-8d80-eafffbea36c8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626383/bf2ec310-9930-11e6-9d80-1c578e513f52.png
