### ISSUE TITLE
Flags Quiz - Guess flags around the world!

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#2218]
**App Name:** Flags Quiz - Guess flags around the world!
**Bundle ID:** com.aticod.flagsquizgame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525321680">525321680</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flags-quiz-guess-flags-around/id525321680?mt=8&uo=4">https://itunes.apple.com/us/app/flags-quiz-guess-flags-around/id525321680?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** AticoD Entertainment S.L.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aticod-entertainment-s.l./id425000230?uo=4>© AticoD Entertainment S.L.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/d7/11/64/d71164a4-fdb8-20ea-e43c-335d9eb54446/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18793875/1406d4f8-81bd-11e6-9162-d34d18923eb2.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18793875/1406d4f8-81bd-11e6-9162-d34d18923eb2.png)
https://cloud.githubusercontent.com/assets/20930745/18793875/1406d4f8-81bd-11e6-9162-d34d18923eb2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18793888/217982d4-81bd-11e6-9498-dcdc817e0058.png
