### ISSUE TITLE
chronodrive : courses drive de produits frais

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#222]
**App Name:** chronodrive : courses drive de produits frais
**Bundle ID:** fr.chronodrive.vad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=397935048">397935048</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chronodrive-courses-drive/id397935048?mt=8&uo=4">https://itunes.apple.com/us/app/chronodrive-courses-drive/id397935048?mt=8&uo=4</a>
**App Version:** 5.9.0
**Seller:** chronodrive
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chronodrive.com/id397935051?uo=4>© Chronodrive.com</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/68/e8/d5/68e8d53f-af02-bb20-780a-f37a84d3928e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625467/c2512c8e-9919-11e6-9dad-9e080b42f20c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625467/c2512c8e-9919-11e6-9dad-9e080b42f20c.png)
https://cloud.githubusercontent.com/assets/20930745/19625467/c2512c8e-9919-11e6-9dad-9e080b42f20c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625473/e96cb7fc-9919-11e6-8ecc-072da98ecce9.png
