### ISSUE TITLE
F18 Carrier Landing

### ISSUE THREAD

**Issue by alex810158** [glasklart/hd#2222]
**App Name:** F18 Carrier Landing
**Bundle ID:** it.rortos.f18carrierlanding
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454802329">454802329</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/f18-carrier-landing/id454802329?mt=8&uo=4">https://itunes.apple.com/us/app/f18-carrier-landing/id454802329?mt=8&uo=4</a>
**App Version:** 7.2
**Seller:** RORTOS SRL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rortos-srl/id454802333?uo=4">© RORTOS SRL</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/9c/b5/1c/9cb51cbe-04ca-97c4-60c4-45fc66638358/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26386258/dbe46192-4045-11e7-98e7-e7f68e0c0091.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26386258/dbe46192-4045-11e7-98e7-e7f68e0c0091.png)
https://cloud.githubusercontent.com/assets/2068130/26386258/dbe46192-4045-11e7-98e7-e7f68e0c0091.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26386266/ebd2a596-4045-11e7-9c0b-fc658ac89f5a.png
