### ISSUE TITLE
Recorder Pro

### ISSUE THREAD

**Issue by shredward** [glasklart/hd#2230]
**App Name:** Recorder Pro
**Bundle ID:** com.victorbajada.Recorder-Pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=503031635">503031635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/recorder-pro/id503031635?mt=8&uo=4">https://itunes.apple.com/us/app/recorder-pro/id503031635?mt=8&uo=4</a>
**App Version:** 10
**Seller:** David Bajada
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/david-bajada/id466246609?uo=4">© David Bajada</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple6/v4/8d/e5/79/8de57900-618d-fc04-05ea-a9fd727ca6c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41189393-72a8f864-6bcd-11e8-836f-852d7e757551.png)

**Comment by Christian9901** [comment]
**App Name:** Recorder Pro
**Bundle ID:** com.victorbajada.Recorder-Pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=503031635">503031635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/recorder-pro/id503031635?mt=8&uo=4">https://itunes.apple.com/us/app/recorder-pro/id503031635?mt=8&uo=4</a>
**App Version:** 10
**Seller:** David Bajada
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/david-bajada/id466246609?uo=4">© David Bajada</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple6/v4/8d/e5/79/8de57900-618d-fc04-05ea-a9fd727ca6c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41189393-72a8f864-6bcd-11e8-836f-852d7e757551.png)
https://user-images.githubusercontent.com/2068130/41189393-72a8f864-6bcd-11e8-836f-852d7e757551.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41189396-81c68c44-6bcd-11e8-9f46-efbd3bbfbb6b.png
