### ISSUE TITLE
D'Tools

### ISSUE THREAD

**Issue by shredward** [glasklart/hd#2232]
**App Name:** D'Tools
**Bundle ID:** com.planetwaves.guitartools
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375703586">375703586</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dtools/id375703586?uo=4">https://apps.apple.com/us/app/dtools/id375703586?uo=4</a>
**App Version:** 2.0.4
**Seller:** D'Addario & Company, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/daddario-company-inc/id308730620?uo=4">© D'Addario & Company, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/3a/e8/01/3ae8017a-c958-39ba-568f-fdd854296d82/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60386034-bc803e00-9a90-11e9-898d-6ad137439275.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60386034-bc803e00-9a90-11e9-898d-6ad137439275.png)
https://user-images.githubusercontent.com/2068130/60386034-bc803e00-9a90-11e9-898d-6ad137439275.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60386044-cb66f080-9a90-11e9-9f1c-c72f2dec5a8b.png
