### ISSUE TITLE
Yellow Pages

### ISSUE THREAD

**Issue by BenChaimberg** [glasklart/hd#2238]
**App Name:** Yellow Pages
**Bundle ID:** com.yourcompany.Earthquake
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284809790">284809790</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yellow-pages/id284809790?mt=8&uo=4">https://itunes.apple.com/us/app/yellow-pages/id284809790?mt=8&uo=4</a>
**App Version:** 7.10.5
**Seller:** Avantar LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/avantar-llc/id284249448?uo=4>© Avantar LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/10/a4/1c/10a41c2a-e700-2267-931b-bd51ee917f2f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621541/5e7cc720-9894-11e6-8ef3-a8e8bdcffc15.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621541/5e7cc720-9894-11e6-8ef3-a8e8bdcffc15.png)
https://cloud.githubusercontent.com/assets/20930745/19621541/5e7cc720-9894-11e6-8ef3-a8e8bdcffc15.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19621547/77761164-9894-11e6-8417-897f2136feb9.png
