### ISSUE TITLE
Arvest Mobile Banking App

### ISSUE THREAD

**Issue by HarshTrooth** [glasklart/hd#2239]
**App Name:** Arvest Mobile Banking App
**Bundle ID:** com.arvest.mbanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=458686055">458686055</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/arvest-mobile-banking-app/id458686055?mt=8&uo=4">https://itunes.apple.com/us/app/arvest-mobile-banking-app/id458686055?mt=8&uo=4</a>
**App Version:** 5.4.0
**Seller:** Arvest
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/arvest/id337997680?uo=4>© Arvest</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/e4/cf/9d/e4cf9d22-f7bb-2e33-eaba-8d9af4f04243/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19735967/029ebd7e-9bae-11e6-9fe8-8d8a63439b46.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19735967/029ebd7e-9bae-11e6-9fe8-8d8a63439b46.png)
https://cloud.githubusercontent.com/assets/2068130/19735967/029ebd7e-9bae-11e6-9fe8-8d8a63439b46.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19735978/11974e0e-9bae-11e6-999b-7461d8e24d28.png
