### ISSUE TITLE
Mobile Playmaker

### ISSUE THREAD

**Issue by HarshTrooth** [glasklart/hd#2242]
**App Name:** Mobile Playmaker
**Bundle ID:** com.buzztime.mobileplaymaker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=329676014">329676014</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobile-playmaker/id329676014?mt=8&uo=4">https://itunes.apple.com/us/app/mobile-playmaker/id329676014?mt=8&uo=4</a>
**App Version:** 1.6.8
**Seller:** Buzztime, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/buzztime-inc./id329676017?uo=4">© Buzztime, Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/9f/40/c9/9f40c935-04e1-8c6c-eb4e-6ec77e3f0975/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030513/0bd2177c-a367-11e6-8d87-a2604407dd2f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030513/0bd2177c-a367-11e6-8d87-a2604407dd2f.png)
https://cloud.githubusercontent.com/assets/20930745/20030513/0bd2177c-a367-11e6-8d87-a2604407dd2f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20030516/233e0182-a367-11e6-9118-6c844a76259c.png
