### ISSUE TITLE
GPS Kit - Offline GPS Tracker

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2247]
**App Name:** GPS Kit - Offline GPS Tracker
**Bundle ID:** com.garafa.GPSKit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=287909017">287909017</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gps-kit-offline-gps-tracker/id287909017?mt=8&uo=4">https://itunes.apple.com/us/app/gps-kit-offline-gps-tracker/id287909017?mt=8&uo=4</a>
**App Version:** 7.0.1
**Seller:** Garafa, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/garafa-llc/id284829377?uo=4>© Garafa, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/86/98/5d/86985d83-3438-6567-e951-0407c1e8483d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18818106/79e1bc4c-8371-11e6-9814-773d64bb5f2b.png)

**Comment by Sly-Fi** [comment]
This icon is missing from 5.0 release

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18818106/79e1bc4c-8371-11e6-9814-773d64bb5f2b.png)
https://cloud.githubusercontent.com/assets/2068130/18818106/79e1bc4c-8371-11e6-9814-773d64bb5f2b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18818110/88a54b40-8371-11e6-9431-1899705c4935.png
