### ISSUE TITLE
Rain Alarm - Rain Alerts and Live Doppler Radar Images

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2248]
**App Name:** Rain Alarm - Rain Alerts and Live Doppler Radar Images
**Bundle ID:** com.avilessoftware.RainAlarm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=397676100">397676100</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rain-alarm-rain-alerts-live/id397676100?mt=8&uo=4">https://itunes.apple.com/us/app/rain-alarm-rain-alerts-live/id397676100?mt=8&uo=4</a>
**App Version:** 1.9.32
**Seller:** Carlos Aviles
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/carlos-aviles-software/id397676103?uo=4>© Carlos Aviles Software</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/40/59/d4/4059d410-9c99-6c33-c8ed-fb9d248d4824/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18648333/2ccf4f20-7e88-11e6-8eb7-b870a6b18768.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18648333/2ccf4f20-7e88-11e6-8eb7-b870a6b18768.png)

https://cloud.githubusercontent.com/assets/3704186/18648333/2ccf4f20-7e88-11e6-8eb7-b870a6b18768.png

https://cloud.githubusercontent.com/assets/3704186/18648340/33e2a794-7e88-11e6-9c02-0cf5f2c80777.png
