### ISSUE TITLE
AcePlayer Plus

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#225]
**App Name:** AcePlayer Plus
**Bundle ID:** com.ranysoft.airav
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=480962404">480962404</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aceplayer-plus/id480962404?mt=8&uo=4">https://itunes.apple.com/us/app/aceplayer-plus/id480962404?mt=8&uo=4</a>
**App Version:** 6.1.3
**Seller:** Rany Yuen
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ranysoft/id454422860?uo=4">© Ranysoft</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/bd/63/b5/bd63b575-a7d9-9e97-dca0-e9be74e278fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38154534-bb36f154-3472-11e8-80bf-11acb7534e42.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38154534-bb36f154-3472-11e8-80bf-11acb7534e42.png)
https://user-images.githubusercontent.com/2068130/38154534-bb36f154-3472-11e8-80bf-11acb7534e42.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38154544-cae57904-3472-11e8-8759-a37a2f34aec2.png
