### ISSUE TITLE
Interflora – Flowers & Gifts Delivered

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2253]
**App Name:** Interflora – Flowers & Gifts Delivered
**Bundle ID:** com.somoagency.Interflora
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404179854">404179854</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/interflora-flowers-gifts-delivered/id404179854?mt=8&uo=4">https://itunes.apple.com/gb/app/interflora-flowers-gifts-delivered/id404179854?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Interflora British Unit
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/interflora-british-unit/id404179857?uo=4>© Interflora British Unit</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/29/79/00/29790079-7451-1827-65d5-36922b1405d8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625182/e0bd07e0-9911-11e6-9baf-a43e7fa4d5fc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625182/e0bd07e0-9911-11e6-9baf-a43e7fa4d5fc.png)
https://cloud.githubusercontent.com/assets/20930745/19625182/e0bd07e0-9911-11e6-9baf-a43e7fa4d5fc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625185/fab3c26a-9911-11e6-9d92-7e2909c1749c.png
