### ISSUE TITLE
iTranslate Voice

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2254]
**App Name:** iTranslate Voice
**Bundle ID:** com.sonicomobile.itranslatevoice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=522626820">522626820</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/itranslate-voice/id522626820?uo=4">https://apps.apple.com/us/app/itranslate-voice/id522626820?uo=4</a>
**App Version:** 4.0.10
**Seller:** iTranslate GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/itranslate/id288113406?uo=4">© iTranslate</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/e9/5c/bf/e95cbf5d-b3fe-26fa-2688-dbb6764e8a57/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62396859-842ebc80-b574-11e9-8f39-94c577612d0a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625242/5435382c-9913-11e6-8c65-2cdffe8003af.png)
https://cloud.githubusercontent.com/assets/20930745/19625242/5435382c-9913-11e6-8c65-2cdffe8003af.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625252/79fe7dfc-9913-11e6-8135-f7d9aa6dcb82.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62396859-842ebc80-b574-11e9-8f39-94c577612d0a.png)
https://user-images.githubusercontent.com/2068130/62396859-842ebc80-b574-11e9-8f39-94c577612d0a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62396874-9577c900-b574-11e9-8813-77be80d6617d.png
