### ISSUE TITLE
Roster Free

### ISSUE THREAD

**Issue by mscallie** [glasklart/hd#2255]
**App Name:** Roster Free
**Bundle ID:** com.offlinesoftware.rosterfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382412209">382412209</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/roster-free/id382412209?mt=8&uo=4">https://itunes.apple.com/us/app/roster-free/id382412209?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Brent Spencer
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/offline-software/id337651584?uo=4">© Offline Software</a>
**Supported Devices:** iPodTouchSecondGen-iPod-touch-with-mic, iPhone3G-iPhone-3G, iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple/v4/af/36/ac/af36ac02-999b-bb98-b660-4867cab50aa1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39838540-f4407fca-53d9-11e8-9452-496147b781f3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39838540-f4407fca-53d9-11e8-9452-496147b781f3.png)
https://user-images.githubusercontent.com/20930745/39838540-f4407fca-53d9-11e8-9452-496147b781f3.png

Source:
https://user-images.githubusercontent.com/20930745/39838570-08747262-53da-11e8-84f4-d44b0f164d95.png
