### ISSUE TITLE
PanoPerfect

### ISSUE THREAD

**Issue by mscallie** [glasklart/hd#2257]
**App Name:** PanoPerfect
**Bundle ID:** com.NateChiger.PanoramaApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=564643903">564643903</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/panoperfect/id564643903?mt=8&uo=4">https://itunes.apple.com/us/app/panoperfect/id564643903?mt=8&uo=4</a>
**App Version:** 3.4.2
**Seller:** HalfPeeled LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/halfpeeled-llc/id342073800?uo=4">© HalfPeeled LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple22/v4/7d/d0/ef/7dd0effe-0f34-0dc9-a885-2ef970944134/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39852748-7fc81aa0-541e-11e8-9824-959201d6f595.png)

**Comment by dreamnet** [comment]
?
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39852748-7fc81aa0-541e-11e8-9824-959201d6f595.png)
https://user-images.githubusercontent.com/2068130/39852748-7fc81aa0-541e-11e8-9824-959201d6f595.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39852757-951a0544-541e-11e8-90bc-0083e9d2e111.png
