### ISSUE TITLE
Fitness Buddy: Gym Workouts

### ISSUE THREAD

**Issue by mscallie** [glasklart/hd#2259]
**App Name:** Fitness Buddy: Gym Workouts
**Bundle ID:** com.skyhealth.fitnessbuddyfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514780106">514780106</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fitness-buddy-gym-workouts/id514780106?mt=8&uo=4">https://itunes.apple.com/us/app/fitness-buddy-gym-workouts/id514780106?mt=8&uo=4</a>
**App Version:** 5.136
**Seller:** Tom Xu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/azumio-inc/id439290207?mt=8&uo=4">© Azumio Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/61/e7/6f/61e76fb9-8891-aab7-0741-ea39d74bbdda/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37567480-ee93b082-2ac7-11e8-8ba0-4dfb772b9939.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37567480-ee93b082-2ac7-11e8-8ba0-4dfb772b9939.png)
https://user-images.githubusercontent.com/2068130/37567480-ee93b082-2ac7-11e8-8ba0-4dfb772b9939.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37567483-fe0e0a8a-2ac7-11e8-8330-175d71c99a0a.png
