### ISSUE TITLE
TV Magazine : Programme TV Gratuit, Actu Télé et People

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#226]
**App Name:** TV Magazine : Programme TV Gratuit, Actu Télé et People
**Bundle ID:** com.lefigaro.tvmag
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448925571">448925571</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tv-magazine-programme-tv-gratuit/id448925571?mt=8&uo=4">https://itunes.apple.com/us/app/tv-magazine-programme-tv-gratuit/id448925571?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** Societe du Figaro
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/societe-du-figaro/id302962544?uo=4>© Société du Figaro</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/86/02/82/8602824b-b709-ec6c-0877-d18b4cfa5d3c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625500/c9845278-991a-11e6-980f-2125308d198f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625500/c9845278-991a-11e6-980f-2125308d198f.png)
https://cloud.githubusercontent.com/assets/20930745/19625500/c9845278-991a-11e6-980f-2125308d198f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625506/df10183e-991a-11e6-8005-8b0d4a93cce7.png
