### ISSUE TITLE
U.S. Bank

### ISSUE THREAD

**Issue by mfcmflem** [glasklart/hd#2262]
**App Name:** U.S. Bank
**Bundle ID:** com.usbank.icmobilebanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=458734623">458734623</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/u.s.-bank/id458734623?mt=8&uo=4">https://itunes.apple.com/us/app/u.s.-bank/id458734623?mt=8&uo=4</a>
**App Version:** 2.11.31
**Seller:** U.S. Bancorp
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/u.s.-bancorp/id458734630?uo=4>© U.S. Bancorp</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/0e/05/9d/0e059d84-e933-b841-00b3-605e58d75d90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18722247/71fdf94a-8034-11e6-8d0a-398b1946c235.png)

**Comment by Sly-Fi** [comment]
This icon is missing from version  5.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18721606/80fcd0e0-8031-11e6-850a-de07b154cd7e.png)
https://cloud.githubusercontent.com/assets/20930745/18721606/80fcd0e0-8031-11e6-850a-de07b154cd7e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18721624/92876528-8031-11e6-88c8-5b3ac517baed.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18722247/71fdf94a-8034-11e6-8d0a-398b1946c235.png)
https://cloud.githubusercontent.com/assets/20930745/18722247/71fdf94a-8034-11e6-8d0a-398b1946c235.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18722272/87766d34-8034-11e6-839e-c74e8b43fda2.png

**Comment by ivanov007** [comment]
both are good, I'm taking the second one, but if someone thinks different can change my decision
