### ISSUE TITLE
Real Racing 3 [inc]

### ISSUE THREAD

**Issue by mfcmflem** [glasklart/hd#2264]
**App Name:** Real Racing 3
**Bundle ID:** com.ea.realracing3.inc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=556164008">556164008</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/real-racing-3/id556164008?mt=8&uo=4">https://itunes.apple.com/us/app/real-racing-3/id556164008?mt=8&uo=4</a>
**App Version:** 4.5.2
**Seller:** Electronic Arts Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4>© Electronic Arts</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/a2/fe/4a/a2fe4ac8-32cc-f876-3d52-2f743b3af029/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18699177/dd2efed6-7fcf-11e6-86dc-68e6e79e0929.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18699177/dd2efed6-7fcf-11e6-86dc-68e6e79e0929.png)
https://cloud.githubusercontent.com/assets/2068130/18699177/dd2efed6-7fcf-11e6-86dc-68e6e79e0929.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18699183/eb423b8c-7fcf-11e6-80cb-1451e6092f02.png
