### ISSUE TITLE
Hover Biker

### ISSUE THREAD

**Issue by mfcmflem** [glasklart/hd#2267]
**App Name:** Hover Biker
**Bundle ID:** com.steenriver.hover
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=477766521">477766521</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hover-biker/id477766521?mt=8&uo=4">https://itunes.apple.com/us/app/hover-biker/id477766521?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Abraham Stolk
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/abraham-stolk/id303320757?uo=4">© Abraham Stolk</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/0d/69/97/0d699723-700f-5e16-b21d-c0d9aa6fc884/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38173037-9d9d2834-35b7-11e8-96a6-f5d0dbfa0b8c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38173037-9d9d2834-35b7-11e8-96a6-f5d0dbfa0b8c.png)
https://user-images.githubusercontent.com/2068130/38173037-9d9d2834-35b7-11e8-96a6-f5d0dbfa0b8c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38173042-abfea358-35b7-11e8-9866-b3a3273fd91c.png
