### ISSUE TITLE
Philips MyRemote

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#227]
**App Name:** Philips MyRemote
**Bundle ID:** com.philips.avremote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426883783">426883783</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/philips-myremote/id426883783?mt=8&uo=4">https://itunes.apple.com/gb/app/philips-myremote/id426883783?mt=8&uo=4</a>
**App Version:** 4.40
**Seller:** Philips Consumer Lifestyle, B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/philips/id355645429?uo=4>© Philips</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/28/00/0d/28000d81-1d7f-789e-960e-309a885d8f98/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18471112/86d490c0-79b0-11e6-8027-45dec58144ff.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**App Name:** Philips MyRemote
**Bundle ID:** com.philips.avremote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426883783">426883783</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/philips-myremote/id426883783?mt=8&uo=4">https://itunes.apple.com/gb/app/philips-myremote/id426883783?mt=8&uo=4</a>
**App Version:** 4.40
**Seller:** Philips Consumer Lifestyle, B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/philips/id355645429?uo=4>© Philips</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/28/00/0d/28000d81-1d7f-789e-960e-309a885d8f98/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18471112/86d490c0-79b0-11e6-8027-45dec58144ff.png)
https://cloud.githubusercontent.com/assets/20930745/18471112/86d490c0-79b0-11e6-8027-45dec58144ff.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18471146/b8f9c480-79b0-11e6-8fe4-19dc42e73077.png
