### ISSUE TITLE
Sportbootführerschein See

### ISSUE THREAD

**Issue by askarl** [glasklart/hd#2273]
**App Name:** Sportbootführerschein See
**Bundle ID:** com.beckfish.SBFSee
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324456819">324456819</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sportbootfuhrerschein-see/id324456819?mt=8&uo=4">https://itunes.apple.com/us/app/sportbootfuhrerschein-see/id324456819?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Janis Beckedorf
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/janis-beckedorf/id1080187211?uo=4>© Janis Beckedorf</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/2e/0c/9d/2e0c9d3e-bff7-9d82-ed3e-ec779b6a75dc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626302/a9e5408a-992e-11e6-9826-50cb9a31372e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626302/a9e5408a-992e-11e6-9826-50cb9a31372e.png)
https://cloud.githubusercontent.com/assets/20930745/19626302/a9e5408a-992e-11e6-9826-50cb9a31372e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626311/cb5c9b0a-992e-11e6-8e67-be6dbc6749c9.png
