### ISSUE TITLE
Radio 24syv – dansk netradio og podcast

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#2278]
**App Name:** Radio 24syv – dansk netradio og podcast
**Bundle ID:** dk.radio24syv.radio24syv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=474717812">474717812</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radio-24syv-dansk-netradio/id474717812?mt=8&uo=4">https://itunes.apple.com/us/app/radio-24syv-dansk-netradio/id474717812?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Berlingske People A/S
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/radio24syv/id474717815?uo=4">© Radio24syv</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/3f/a4/0e/3fa40e92-0294-d9a7-0427-764030b97da3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028657/256f5f2a-a338-11e6-9403-f5bf856c81a1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028657/256f5f2a-a338-11e6-9403-f5bf856c81a1.png)
https://cloud.githubusercontent.com/assets/20930745/20028657/256f5f2a-a338-11e6-9403-f5bf856c81a1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20028662/3fd8f4fc-a338-11e6-8fae-38df0f838bba.png
