### ISSUE TITLE
RadioPlay DK

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#2279]
**App Name:** RadioPlay DK
**Bundle ID:** dk.releaze.radiovoice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492664619">492664619</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/dk/app/radioplay-dk/id492664619?mt=8&uo=4">https://itunes.apple.com/dk/app/radioplay-dk/id492664619?mt=8&uo=4</a>
**App Version:** 3.0.16
**Seller:** SBS Media
**Developer:** <a target="_blank" href=https://itunes.apple.com/dk/developer/sbs-media/id492664622?uo=4>© SBS Media</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/4b/3e/20/4b3e20f0-0c8b-ebe6-9740-e34309f4d12d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626404/788693f6-9931-11e6-9ef6-c63a5a50f793.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626404/788693f6-9931-11e6-9ef6-c63a5a50f793.png)
https://cloud.githubusercontent.com/assets/20930745/19626404/788693f6-9931-11e6-9ef6-c63a5a50f793.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626408/8e511756-9931-11e6-8b87-e8518996427b.png
