### ISSUE TITLE
Carlton Official App

### ISSUE THREAD

**Issue by darkxst** [glasklart/hd#228]
**App Name:** Carlton Official App
**Bundle ID:** au.com.afl.carl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=510337970">510337970</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/carlton-official-app/id510337970?mt=8&uo=4">https://itunes.apple.com/us/app/carlton-official-app/id510337970?mt=8&uo=4</a>
**App Version:** 3.3.2
**Seller:** Telstra Corporation Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/telstra-corporation-limited/id327529523?uo=4">© Telstra Corporation Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/9d/23/ef/9d23ef85-5b08-3ade-efe3-302e8161ce81/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030258/e3b0b262-a361-11e6-85e3-12fa86b22b23.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030258/e3b0b262-a361-11e6-85e3-12fa86b22b23.png)
https://cloud.githubusercontent.com/assets/20930745/20030258/e3b0b262-a361-11e6-85e3-12fa86b22b23.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20030260/f90013b0-a361-11e6-8257-9afde10a395c.png
