### ISSUE TITLE
IGN: Video Game News, Reviews, Guides

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#2283]
**App Name:** IGN: Video Game News, Reviews, Guides
**Bundle ID:** 68RX859ZF4.com.fox.ign.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284819997">284819997</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ign-video-game-news-reviews/id284819997?mt=8&uo=4">https://itunes.apple.com/us/app/ign-video-game-news-reviews/id284819997?mt=8&uo=4</a>
**App Version:** 4.5.11
**Seller:** IGN Entertainment, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ign-entertainment-inc./id508074893?uo=4>© IGN Entertainment, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/53/03/9f/53039fe0-580f-d36e-369e-86e411fcd677/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626233/5125b886-992d-11e6-8436-f4e8c5c817c7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626233/5125b886-992d-11e6-8436-f4e8c5c817c7.png)
https://cloud.githubusercontent.com/assets/20930745/19626233/5125b886-992d-11e6-8436-f4e8c5c817c7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626241/69ff1b18-992d-11e6-8e3c-521c7fcc3cc2.png
