### ISSUE TITLE
Rated People - Homes

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2285]
**App Name:** Rated People - Homes
**Bundle ID:** com.ratedpeople.nativeapp.homeowner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=553594818">553594818</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/rated-people-homes/id553594818?mt=8&uo=4">https://itunes.apple.com/gb/app/rated-people-homes/id553594818?mt=8&uo=4</a>
**App Version:** 1.6.1
**Seller:** Rated People Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/rated-people/id553594821?uo=4>© Rated People</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/73/e6/00/73e6009d-99ca-0c0e-3535-5d78b6a3afe5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626456/066dae6a-9933-11e6-94b4-94e5e20e951e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626456/066dae6a-9933-11e6-94b4-94e5e20e951e.png)
https://cloud.githubusercontent.com/assets/20930745/19626456/066dae6a-9933-11e6-94b4-94e5e20e951e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626460/1eb8ad58-9933-11e6-9063-1657da1cbfe7.png
