### ISSUE TITLE
Oakley Snow Report 

### ISSUE THREAD

**Issue by darkxst** [glasklart/hd#229]
**Bundle ID:** com.mountainwatch.SnowQS
PNG Icon Name: Icon@2x.png
Fulfillment URL:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/24826050/97859ac0-1c2d-11e7-8ead-da16d2d0d23b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/24826050/97859ac0-1c2d-11e7-8ead-da16d2d0d23b.png)
https://cloud.githubusercontent.com/assets/2068130/24826050/97859ac0-1c2d-11e7-8ead-da16d2d0d23b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/24826054/a7b7b842-1c2d-11e7-8eeb-1eac53a46d37.png
