### ISSUE TITLE
IP Cam

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2290]
**App Name:** IP Cam
**Bundle ID:** com.yourcompany.IPCam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=333208495">333208495</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ip-cam/id333208495?mt=8&uo=4">https://itunes.apple.com/us/app/ip-cam/id333208495?mt=8&uo=4</a>
**App Version:** 4.4
**Seller:** Senstic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/senstic/id287765002?uo=4>© Senstic</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/4d/71/58/4d7158df-8c8c-559d-bab1-2e3767e0eefc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626561/29362d62-9935-11e6-9543-3c0820c94048.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626561/29362d62-9935-11e6-9543-3c0820c94048.png)
https://cloud.githubusercontent.com/assets/20930745/19626561/29362d62-9935-11e6-9543-3c0820c94048.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626564/42590db4-9935-11e6-82d4-d9efdb091b07.png
