### ISSUE TITLE
Disk Decipher

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2292]
**App Name:** Disk Decipher
**Bundle ID:** nl.hekkihek.disk-decipher
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=516538625">516538625</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/disk-decipher/id516538625?mt=8&uo=4">https://itunes.apple.com/us/app/disk-decipher/id516538625?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Richard Huveneers
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/richard-huveneers/id516538628?uo=4>© Richard Huveneers</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/d4/c0/c8/d4c0c885-0138-7c2a-4cbe-94d1b501c127/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626626/3ddc81f2-9936-11e6-90d3-54917a3acec7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626626/3ddc81f2-9936-11e6-90d3-54917a3acec7.png)
https://cloud.githubusercontent.com/assets/20930745/19626626/3ddc81f2-9936-11e6-90d3-54917a3acec7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626630/5237ee34-9936-11e6-8ad1-89b6853799dd.png
