### ISSUE TITLE
Battery HD+

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2293]
**App Name:** Battery HD+
**Bundle ID:** com.slema.BatteryFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=331453283">331453283</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/battery-hd/id331453283?mt=8&uo=4">https://itunes.apple.com/us/app/battery-hd/id331453283?mt=8&uo=4</a>
**App Version:** 3.34
**Seller:** smalltech sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/smalltech-sarl/id289934568?uo=4">© smalltech sarl</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/09/2a/53/092a53b9-dcfa-e245-1aa5-39b4760d1852/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41506394-3d93ee62-721d-11e8-8899-d51f2c1725f3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41506394-3d93ee62-721d-11e8-8899-d51f2c1725f3.png)
https://user-images.githubusercontent.com/2068130/41506394-3d93ee62-721d-11e8-8899-d51f2c1725f3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41506399-4ca67b5e-721d-11e8-86ec-5d8858e6aecb.png
