### ISSUE TITLE
Pocket Zen

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#2295]
**App Name:** Pocket Zen
**Bundle ID:** com.FSDigital.DailyEnlightenment
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335784040">335784040</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-zen/id335784040?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-zen/id335784040?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** PLS Productions Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pls-productions/id717009651?uo=4">© PLS Productions</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/0a/05/c4/0a05c4f2-50b8-828d-177e-b7ffc70b527d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25575258/f80fb58a-2e55-11e7-8070-2357797ad7e1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25575258/f80fb58a-2e55-11e7-8070-2357797ad7e1.png)
https://cloud.githubusercontent.com/assets/2068130/25575258/f80fb58a-2e55-11e7-8070-2357797ad7e1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25575262/056b9640-2e56-11e7-86bf-8715b71785af.png
