### ISSUE TITLE
iUnit - Unit and Currency Converter

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#2296]
**App Name:** iUnit 2 - Unit and Currency Converter
**Bundle ID:** com.denioworx.iunit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=482354286">482354286</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iunit-2-unit-currency-converter/id482354286?mt=8&uo=4">https://itunes.apple.com/us/app/iunit-2-unit-currency-converter/id482354286?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Dennis Wittke
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dennis-wittke/id482354289?uo=4>© Dennis Wittke</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/20/9d/a8/209da81f-36e2-e69b-d0fb-fb6cfb09223d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626762/47646e18-9938-11e6-9ec7-8477c2816f78.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626762/47646e18-9938-11e6-9ec7-8477c2816f78.png)
https://cloud.githubusercontent.com/assets/20930745/19626762/47646e18-9938-11e6-9ec7-8477c2816f78.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626767/63fff1dc-9938-11e6-9f56-1f91648768c2.png
