### ISSUE TITLE
Audyssey Music Player

### ISSUE THREAD

**Issue by yojoemamma** [glasklart/hd#2303]
**App Name:** Audyssey Music Player
**Bundle ID:** com.audyssey.mediaplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=569331902">569331902</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/audyssey-music-player/id569331902?mt=8&uo=4">https://itunes.apple.com/us/app/audyssey-music-player/id569331902?mt=8&uo=4</a>
**App Version:** 1.5.4
**Seller:** Audyssey Laboratories, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/audyssey-laboratories/id399249166?uo=4>© Audyssey Laboratories</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/d0/bc/69/d0bc6974-3d1b-7e02-5304-cd6bf4271c0d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626674/1a2a1a20-9937-11e6-8cec-ae3bfd8e490b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626674/1a2a1a20-9937-11e6-8cec-ae3bfd8e490b.png)
https://cloud.githubusercontent.com/assets/20930745/19626674/1a2a1a20-9937-11e6-8cec-ae3bfd8e490b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626679/2fa6a1d4-9937-11e6-8bd4-115d0cf4c96c.png
