### ISSUE TITLE
Totalbanken Mobilbank

### ISSUE THREAD

**Issue by messcrew** [glasklart/hd#2304]
**App Name:** Totalbanken Mobilbank
**Bundle ID:** dk.bec.mb1.b00093.prod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=421363809">421363809</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/totalbanken-mobilbank/id421363809?mt=8&uo=4">https://itunes.apple.com/us/app/totalbanken-mobilbank/id421363809?mt=8&uo=4</a>
**App Version:** 4.6.7
**Seller:** Bankernes EDB Central
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bankernes-edb-central/id421233825?uo=4>© Bankernes EDB Central</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/5d/ea/69/5dea6948-5b12-24bf-f0f9-380852c48b92/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626154/20fceb7c-992b-11e6-9b6e-96a329b11cab.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626154/20fceb7c-992b-11e6-9b6e-96a329b11cab.png)
https://cloud.githubusercontent.com/assets/20930745/19626154/20fceb7c-992b-11e6-9b6e-96a329b11cab.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626166/398798cc-992b-11e6-8e6c-5bac03c2ba6c.png
