### ISSUE TITLE
kino.dk - biografoversigt

### ISSUE THREAD

**Issue by messcrew** [glasklart/hd#2305]
**App Name:** kino.dk - biografoversigt
**Bundle ID:** dk.kino.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=483570597">483570597</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kino.dk-biografoversigt/id483570597?mt=8&uo=4">https://itunes.apple.com/us/app/kino.dk-biografoversigt/id483570597?mt=8&uo=4</a>
**App Version:** 2.2.3
**Seller:** Kino.dk
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kino.dk/id413646168?uo=4">© kino.dk</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/14/00/81/140081f6-af24-2059-34a4-a4679c8cb110/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028823/11e34332-a33c-11e6-9c74-48c5af8b7ac1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028823/11e34332-a33c-11e6-9c74-48c5af8b7ac1.png)
https://cloud.githubusercontent.com/assets/20930745/20028823/11e34332-a33c-11e6-9c74-48c5af8b7ac1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20028831/28c2782a-a33c-11e6-9c92-c002ded5b31e.png
