### ISSUE TITLE
Libratone

### ISSUE THREAD

**Issue by messcrew** [glasklart/hd#2306]
**App Name:** Libratone
**Bundle ID:** com.libratone.libratone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=461374277">461374277</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/libratone/id461374277?mt=8&uo=4">https://itunes.apple.com/us/app/libratone/id461374277?mt=8&uo=4</a>
**App Version:** 4.2.0
**Seller:** LIbratone A/S
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/libratone/id461374280?uo=4>© Libratone</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/7c/13/20/7c13206a-1d6a-f3bd-3a1c-19da982f2d92/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626109/fa7347c2-9929-11e6-9b97-4ae7c4ebee63.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626109/fa7347c2-9929-11e6-9b97-4ae7c4ebee63.png)
https://cloud.githubusercontent.com/assets/20930745/19626109/fa7347c2-9929-11e6-9b97-4ae7c4ebee63.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626114/13dbd7f6-992a-11e6-9bf2-c9c205fd07e0.png
