### ISSUE TITLE
Vivint Classic

### ISSUE THREAD

**Issue by woitalla** [glasklart/hd#2308]
**App Name:** Vivint Classic
**Bundle ID:** com.onabridgetech.Vivint
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469231040">469231040</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vivint-classic/id469231040?mt=8&uo=4">https://itunes.apple.com/us/app/vivint-classic/id469231040?mt=8&uo=4</a>
**App Version:** 3.2.9
**Seller:** Vivint, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vivint/id469231043?uo=4>© Vivint</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/df/8e/7c/df8e7cc1-d950-bd6d-7485-3015e7d290df/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626082/54169a50-9929-11e6-8cf1-fcbbb36c1f50.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626082/54169a50-9929-11e6-8cf1-fcbbb36c1f50.png)
https://cloud.githubusercontent.com/assets/20930745/19626082/54169a50-9929-11e6-8cf1-fcbbb36c1f50.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626087/6a8ebb5a-9929-11e6-8331-f11b52ac0db3.png
