### ISSUE TITLE
Vonage Mobile – Voice, Text, and Video

### ISSUE THREAD

**Issue by woitalla** [glasklart/hd#2309]
**App Name:** Vonage Mobile – Voice, Text, and Video
**Bundle ID:** com.vonage.kudzo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=491391564">491391564</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vonage-mobile-voice-text-video/id491391564?mt=8&uo=4">https://itunes.apple.com/us/app/vonage-mobile-voice-text-video/id491391564?mt=8&uo=4</a>
**App Version:** 3.0.6
**Seller:** Vonage
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vonage/id327012900?uo=4">© Vonage</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple19/v4/af/4a/7c/af4a7cf8-1756-8045-97f0-2dbd518d30dd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028770/d6c6cf22-a33a-11e6-9e0f-b0cf31222f8b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028770/d6c6cf22-a33a-11e6-9e0f-b0cf31222f8b.png)
https://cloud.githubusercontent.com/assets/20930745/20028770/d6c6cf22-a33a-11e6-9e0f-b0cf31222f8b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20028775/f0dbe8a2-a33a-11e6-8cff-c7876acd351c.png
