### ISSUE TITLE
Melbourne Water

### ISSUE THREAD

**Issue by darkxst** [glasklart/hd#231]
**App Name:** Melbourne Water
**Bundle ID:** au.com.melbournewater.MelbourneWater
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368664047">368664047</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/melbourne-water/id368664047?mt=8&uo=4">https://itunes.apple.com/us/app/melbourne-water/id368664047?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** Melbourne Water Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/melbourne-water/id368664050?uo=4>© Melbourne Water</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/bd/83/7d/bd837d7d-d8da-dc23-675e-15f70c4b5052/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19401829/cc7dd65c-925d-11e6-846c-2d0805ab59f8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19401829/cc7dd65c-925d-11e6-846c-2d0805ab59f8.png)
https://cloud.githubusercontent.com/assets/20930745/19401829/cc7dd65c-925d-11e6-846c-2d0805ab59f8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19401841/dc3a5a2a-925d-11e6-886d-1ef6d69323f0.png
