### ISSUE TITLE
Cubby

### ISSUE THREAD

**Issue by mscallie** [glasklart/hd#2310]
**App Name:** Cubby
**Bundle ID:** com.logmein.cubby
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=512952416">512952416</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cubby/id512952416?mt=8&uo=4">https://itunes.apple.com/us/app/cubby/id512952416?mt=8&uo=4</a>
**App Version:** 1.0.12653
**Seller:** LogMeIn, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/logmein-inc./id299616804?uo=4>© LogMeIn, Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/ad/22/36/ad223686-b9b6-fc4b-be1c-5444c8ee8647/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626045/7e92b0b2-9928-11e6-9a53-c3c93739538e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626045/7e92b0b2-9928-11e6-9a53-c3c93739538e.png)
https://cloud.githubusercontent.com/assets/20930745/19626045/7e92b0b2-9928-11e6-9a53-c3c93739538e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626050/92e06bcc-9928-11e6-8743-cc966a490674.png
