### ISSUE TITLE
BT Wi-fi

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2311]
**App Name:** BT Wi-fi
**Bundle ID:** com.bt.btfon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=384404559">384404559</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/bt-wi-fi/id384404559?uo=4">https://apps.apple.com/gb/app/bt-wi-fi/id384404559?uo=4</a>
**App Version:** 6.6.24
**Seller:** British Telecommunications plc
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/british-telecommunications-plc/id373567642?uo=4">© British Telecommunications plc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/58/48/15/58481598-ddf9-e3b1-1333-876c08c6c05e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981369-9119d100-9602-11e9-8c03-a439e951cd3e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626802/0307ac84-9939-11e6-8499-6c50f9dcafef.png)
https://cloud.githubusercontent.com/assets/20930745/19626802/0307ac84-9939-11e6-8499-6c50f9dcafef.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626811/1d172ce4-9939-11e6-9a23-690aa1ba2e1d.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981369-9119d100-9602-11e9-8c03-a439e951cd3e.png)
https://user-images.githubusercontent.com/2068130/59981369-9119d100-9602-11e9-8c03-a439e951cd3e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59981375-a0008380-9602-11e9-9339-6929fecb316d.png
