### ISSUE TITLE
Burpple - Find Good Food & Restaurants To Enjoy

### ISSUE THREAD

**Issue by Romeo0119** [glasklart/hd#2313]
**App Name:** Burpple - Find Good Food & Restaurants To Enjoy
**Bundle ID:** com.burpple.getbeta
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=511999255">511999255</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/burpple-find-good-food-restaurants/id511999255?mt=8&uo=4">https://itunes.apple.com/us/app/burpple-find-good-food-restaurants/id511999255?mt=8&uo=4</a>
**App Version:** 4.2.8
**Seller:** Burpple Pte. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/burpple/id511999258?uo=4>© Burpple</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/20/78/a4/2078a410-e5d2-d9b2-b813-ea9967204aee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626828/b7a7c714-9939-11e6-81a6-298a65caedce.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626828/b7a7c714-9939-11e6-81a6-298a65caedce.png)
https://cloud.githubusercontent.com/assets/20930745/19626828/b7a7c714-9939-11e6-81a6-298a65caedce.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626830/ce8b6d0a-9939-11e6-91f4-7fac45f44d74.png
