### ISSUE TITLE
Aemula Oldies S

### ISSUE THREAD

**Issue by sddevstudio** [glasklart/hd#2315]
**App Name:** Aemula Oldies S
**Bundle ID:** com.litchie.aemula-oldies-s
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490466764">490466764</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aemula-oldies-s/id490466764?mt=8&uo=4">https://itunes.apple.com/us/app/aemula-oldies-s/id490466764?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Chaoji Li
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chaoji-li/id342075158?uo=4">© Chaoji Li</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/01/7b/c3/017bc32d-bbe2-9be5-7407-34bf5e5d4816/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634381-de505eb2-19a3-11e8-9def-b24bd9a38902.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634381-de505eb2-19a3-11e8-9def-b24bd9a38902.png)
https://user-images.githubusercontent.com/20930745/36634381-de505eb2-19a3-11e8-9def-b24bd9a38902.png

Source:
https://user-images.githubusercontent.com/20930745/36634386-f2bf0006-19a3-11e8-934f-1822c584d165.png)
