### ISSUE TITLE
Today Weather

### ISSUE THREAD

**Issue by iratcliff1** [glasklart/hd#2320]
**App Name:** Today Weather
**Bundle ID:** com.savvyapps.today
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=556002847">556002847</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/today-weather/id556002847?mt=8&uo=4">https://itunes.apple.com/us/app/today-weather/id556002847?mt=8&uo=4</a>
**App Version:** 2.0.4
**Seller:** savvy apps, llc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/savvy-apps-llc/id394819297?uo=4>© savvy apps, llc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/1e/38/b2/1e38b296-226a-83b9-2db0-40bce4e85d05/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18750876/3d04df2a-80dd-11e6-965f-867a7eae2aa6.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18750876/3d04df2a-80dd-11e6-965f-867a7eae2aa6.png)
https://cloud.githubusercontent.com/assets/20930745/18750876/3d04df2a-80dd-11e6-965f-867a7eae2aa6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18750900/5228e22a-80dd-11e6-8721-837aa467515b.png
