### ISSUE TITLE
Paperless Post: Invitations and eCards

### ISSUE THREAD

**Issue by yakintosh** [glasklart/hd#2322]
**App Name:** Paperless Post: Invitations and eCards
**Bundle ID:** com.paperless.paperlesspost
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489940389">489940389</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paperless-post-invitations/id489940389?mt=8&uo=4">https://itunes.apple.com/us/app/paperless-post-invitations/id489940389?mt=8&uo=4</a>
**App Version:** 5.30.1
**Seller:** Paperless Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/paperless-post/id489940392?uo=4>© Paperless Post</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/0b/2a/f6/0b2af64a-5768-7082-ef16-5ca24a30e416/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625956/1061a2b6-9927-11e6-9bf7-73c95b2bf6df.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625956/1061a2b6-9927-11e6-9bf7-73c95b2bf6df.png)
https://cloud.githubusercontent.com/assets/20930745/19625956/1061a2b6-9927-11e6-9bf7-73c95b2bf6df.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625976/4aed39b8-9927-11e6-837f-a9f1b9e7ba8f.png
