### ISSUE TITLE
ByPost Postcard Maker

### ISSUE THREAD

**Issue by yakintosh** [glasklart/hd#2323]
**App Name:** ByPost Postcard Maker
**Bundle ID:** com.bypost.opcl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418116963">418116963</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bypost-postcard-maker/id418116963?mt=8&uo=4">https://itunes.apple.com/us/app/bypost-postcard-maker/id418116963?mt=8&uo=4</a>
**App Version:** 4.7
**Seller:** Online Postal Communications Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/online-postal-communications/id417948630?uo=4">© Online Postal Communications</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/cb/7b/a7/cb7ba74b-22ef-3599-d981-161c3e19c233/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028727/d95a6d12-a339-11e6-8904-a424fe49de0a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028727/d95a6d12-a339-11e6-8904-a424fe49de0a.png)
https://cloud.githubusercontent.com/assets/20930745/20028727/d95a6d12-a339-11e6-8904-a424fe49de0a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20028736/f60de556-a339-11e6-98ac-fb1c3fa27958.png
