### ISSUE TITLE
Farm Up

### ISSUE THREAD

**Issue by ethan22** [glasklart/hd#2325]
**App Name:** Farm Up
**Bundle ID:** com.realore.farmup.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514573343">514573343</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/farm-up/id514573343?mt=8&uo=4">https://itunes.apple.com/us/app/farm-up/id514573343?mt=8&uo=4</a>
**App Version:** 6.0.2
**Seller:** Realore, JSC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/realore/id431046342?uo=4>© Realore</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/f7/26/68/f7266897-d90a-f38f-7ddf-dc1e307b0905/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19627026/8bccc964-993e-11e6-9d38-e43656b423b1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19627026/8bccc964-993e-11e6-9d38-e43656b423b1.png)
https://cloud.githubusercontent.com/assets/20930745/19627026/8bccc964-993e-11e6-9d38-e43656b423b1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19627033/ac88a2d6-993e-11e6-8776-b8c9ee063dd1.png
