### ISSUE TITLE
Ski Tracks

### ISSUE THREAD

**Issue by yakintosh** [glasklart/hd#2326]
**App Name:** Ski Tracks
**Bundle ID:** com.corecoders.SkiTracks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=365724094">365724094</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ski-tracks/id365724094?mt=8&uo=4">https://itunes.apple.com/us/app/ski-tracks/id365724094?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Core Coders Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/core-coders-ltd/id294178619?uo=4>© Core Coders Ltd</a>
**Supported Devices:** iPhone4, iPad23G, iPhone4S, iPadThirdGen4G, iPhone5, iPadFourthGen4G, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/2f/d2/f3/2fd2f3fd-1fc0-72e5-f7bb-0be65819f8df/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625925/30b60878-9926-11e6-9de4-7180e198d460.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625925/30b60878-9926-11e6-9de4-7180e198d460.png)
https://cloud.githubusercontent.com/assets/20930745/19625925/30b60878-9926-11e6-9de4-7180e198d460.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625928/42afcf46-9926-11e6-9a0b-b10692b03ad2.png
