### ISSUE TITLE
Angry Birds Space

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#2329]
**App Name:** Angry Birds Space
**Bundle ID:** com.rovio.AngryBirdsSpace
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=499511971">499511971</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds-space/id499511971?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds-space/id499511971?mt=8&uo=4</a>
**App Version:** 2.2.12
**Seller:** Rovio Entertainment Oyj
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rovio-entertainment-oyj/id298910979?uo=4">© Rovio Entertainment Oyj</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple127/v4/a7/c4/1c/a7c41cff-cda3-397d-6c98-2828f7b7711c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39286460-5cc201f2-491e-11e8-8407-0b48b747a306.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Angry Birds Space
**Bundle ID:** com.rovio.AngryBirdsSpace
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=499511971">499511971</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds-space/id499511971?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds-space/id499511971?mt=8&uo=4</a>
**App Version:** 2.2.12
**Seller:** Rovio Entertainment Oyj
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rovio-entertainment-oyj/id298910979?uo=4">© Rovio Entertainment Oyj</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple127/v4/a7/c4/1c/a7c41cff-cda3-397d-6c98-2828f7b7711c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39286460-5cc201f2-491e-11e8-8407-0b48b747a306.png)
https://user-images.githubusercontent.com/2068130/39286460-5cc201f2-491e-11e8-8407-0b48b747a306.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39286473-6bec2d60-491e-11e8-9203-6df5a002d865.png
