### ISSUE TITLE
MultiLevel

### ISSUE THREAD

**Issue by darkxst** [glasklart/hd#233]
**App Name:** MultiLevel
**Bundle ID:** com.yourcompany.MultiLevel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=287219655">287219655</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/multilevel/id287219655?mt=8&uo=4">https://itunes.apple.com/us/app/multilevel/id287219655?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** Tee Caddy LLC. (dba Teego)
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/iapps/id286548834?mt=8&uo=4">© iApps</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/ef/eb/3a/efeb3a84-18ee-175b-ef51-b7ced6404f79/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36950410-cb5abb92-1ff5-11e8-9abd-b6d7adced1b9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36950410-cb5abb92-1ff5-11e8-9abd-b6d7adced1b9.png)
https://user-images.githubusercontent.com/2068130/36950410-cb5abb92-1ff5-11e8-9abd-b6d7adced1b9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36950414-d9fd5dc6-1ff5-11e8-891c-fb120ae59886.png
