### ISSUE TITLE
Nordstrom – Shopping, Fashion, Clothing & Style

### ISSUE THREAD

**Issue by Romeo0119** [glasklart/hd#2330]
**App Name:** Nordstrom – Shopping, Fashion, Clothing & Style
**Bundle ID:** com.nordstrom.shopping
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=474349412">474349412</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nordstrom-shopping-fashion/id474349412?mt=8&uo=4">https://itunes.apple.com/us/app/nordstrom-shopping-fashion/id474349412?mt=8&uo=4</a>
**App Version:** 6.0
**Seller:** Nordstrom, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nordstrom-inc./id474349415?uo=4>© Nordstrom, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/89/50/95/89509518-bad6-dfd8-6b26-8533c89eb808/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626852/97e44456-993a-11e6-850a-8aab0c9d9fd7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626852/97e44456-993a-11e6-850a-8aab0c9d9fd7.png)
https://cloud.githubusercontent.com/assets/20930745/19626852/97e44456-993a-11e6-850a-8aab0c9d9fd7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626856/ad6ffaa4-993a-11e6-8d19-99a20a26a1bb.png
