### ISSUE TITLE
Felix (iPhone Edition)

### ISSUE THREAD

**Issue by mscallie** [glasklart/hd#2332]
**App Name:** Felix (iPhone Edition)
**Bundle ID:** com.tigerbears.Felix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=562447652">562447652</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/al/app/felix-iphone-edition/id562447652?mt=8&uo=4">https://itunes.apple.com/al/app/felix-iphone-edition/id562447652?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** tigerbears, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/al/developer/tigerbears-llc/id312213327?uo=4">© tigerbears, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/b5/45/30/b5453047-8a71-e4f4-cf8c-705313fd8327/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028601/9dddda74-a336-11e6-9da7-fca53a3289a4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028601/9dddda74-a336-11e6-9da7-fca53a3289a4.png)
https://cloud.githubusercontent.com/assets/20930745/20028601/9dddda74-a336-11e6-9da7-fca53a3289a4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20028606/b4e820f8-a336-11e6-87db-919ba9188f43.png
