### ISSUE TITLE
GPS on ski map by Maprika

### ISSUE THREAD

**Issue by yakintosh** [glasklart/hd#2336]
**App Name:** GPS on ski map by Maprika
**Bundle ID:** com.maprika.maprika
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404686699">404686699</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gps-on-ski-map-by-maprika/id404686699?mt=8&uo=4">https://itunes.apple.com/us/app/gps-on-ski-map-by-maprika/id404686699?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** Sergey Petrov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/maprika/id404686702?uo=4">© Maprika</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/d3/9e/fb/d39efbbb-72c0-310c-e803-1741463403a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38171546-f7efc966-359b-11e8-8b27-12f9638d14a1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38171546-f7efc966-359b-11e8-8b27-12f9638d14a1.png)
https://user-images.githubusercontent.com/2068130/38171546-f7efc966-359b-11e8-8b27-12f9638d14a1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38171553-061e3bbc-359c-11e8-9df7-5ef4ba48adf3.png
