### ISSUE TITLE
CSN Philly

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#234]
**App Name:** CSN Philly
**Bundle ID:** com.comcastsports.csnphilly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427783832">427783832</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/csn-philly/id427783832?mt=8&uo=4">https://itunes.apple.com/us/app/csn-philly/id427783832?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Comcast Sport Management Services, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/comcast-sportsnet/id427649384?uo=4>© Comcast SportsNet</a>
**Supported Devices:** iPhone6Plus, iPad2Wifi, iPodTouchSixthGen, iPadFourthGen4G, iPhone5c, iPadThirdGen, iPhone5, iPodTouchFifthGen, iPhone5s, iPadFourthGen, iPhone4, iPadMini, iPhone6, iPad23G, iPhone4S, iPadMini4G, iPadThirdGen4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/ca/40/c8/ca40c83b-c98d-48c3-3ff4-de7c5a316dff/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9838408/439c3362-5a5d-11e5-889c-6aeb7c353c6f.png)

**Comment by dreamnet** [comment]
Icon has changed:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9838408/439c3362-5a5d-11e5-889c-6aeb7c353c6f.png)
https://cloud.githubusercontent.com/assets/2068130/9838408/439c3362-5a5d-11e5-889c-6aeb7c353c6f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9838412/53db55a0-5a5d-11e5-8b40-2827ed19edee.png
