### ISSUE TITLE
Jet Scanner | Photo to PDF, scan image documents

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#2340]
**App Name:** Jet Scanner | Photo to PDF, scan image documents
**Bundle ID:** com.digiset.jetscan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=592276641">592276641</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jet-scanner-photo-to-pdf-scan-image-documents/id592276641?mt=8&uo=4">https://itunes.apple.com/us/app/jet-scanner-photo-to-pdf-scan-image-documents/id592276641?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** DIGISET LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/digiset-llc/id944123342?uo=4">© DIGISET LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/cc/23/14/cc2314fd-6739-8b10-bae4-e2527e1b996c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31314835-dfe8d9cc-ac0a-11e7-828d-56bb8126292a.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** JetScanner: Camera to PDF, scan multipage documents to PDF
**Bundle ID:** com.digiset.jetscan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=592276641">592276641</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jetscanner-camera-to-pdf-scan/id592276641?mt=8&uo=4">https://itunes.apple.com/us/app/jetscanner-camera-to-pdf-scan/id592276641?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** DIGISET LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/digiset-llc/id944123342?uo=4>© DIGISET LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple42/v4/32/36/b0/3236b048-2c9a-f7d5-7db4-483f17241fa4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18348639/d566d3ca-75cc-11e6-9621-f285a40810f1.png)
https://cloud.githubusercontent.com/assets/20930745/18348639/d566d3ca-75cc-11e6-9621-f285a40810f1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18348663/f61cbe90-75cc-11e6-8438-c7ed58a182aa.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18362766/690a921c-7607-11e6-96fe-c29418738bf7.png)
https://cloud.githubusercontent.com/assets/20930745/18362766/690a921c-7607-11e6-96fe-c29418738bf7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18362793/85cbad32-7607-11e6-9e65-28e03cfd3fb0.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18401839/de10e978-76dc-11e6-891a-bffa2b117b3d.png)
https://cloud.githubusercontent.com/assets/2068130/18401839/de10e978-76dc-11e6-891a-bffa2b117b3d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18401855/f0a1c92c-76dc-11e6-9f69-8b0cc42a39a7.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Jet Scanner | Photo to PDF, scan image documents
**Bundle ID:** com.digiset.jetscan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=592276641">592276641</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jet-scanner-photo-to-pdf-scan-image-documents/id592276641?mt=8&uo=4">https://itunes.apple.com/us/app/jet-scanner-photo-to-pdf-scan-image-documents/id592276641?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** DIGISET LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/digiset-llc/id944123342?uo=4">© DIGISET LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/cc/23/14/cc2314fd-6739-8b10-bae4-e2527e1b996c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31314808-42bcc3de-ac0a-11e7-8f89-b75a61964cb7.png)
https://user-images.githubusercontent.com/2068130/31314808-42bcc3de-ac0a-11e7-8f89-b75a61964cb7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31314812-523eb538-ac0a-11e7-8150-4ff33e4b3371.png
