### ISSUE TITLE
Partners 1st FCU Mobile

### ISSUE THREAD

**Issue by woitalla** [glasklart/hd#2347]
**App Name:** Partners 1st FCU Mobile
**Bundle ID:** com.partnersfirst.mobilebanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1147212210">1147212210</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/partners-1st-fcu-mobile/id1147212210?mt=8&uo=4">https://itunes.apple.com/us/app/partners-1st-fcu-mobile/id1147212210?mt=8&uo=4</a>
**App Version:** 31.0.9
**Seller:** PARTNERS 1ST FEDERAL CREDIT UNION
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/partners-1st-federal-credit-union/id566472130?uo=4">© Partners 1st Federal Credit Union</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/33/ac/8c/33ac8c19-716c-52bb-10e4-179ae5c3a185/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38172174-9a76fbea-35a7-11e8-8695-0e61b78dff01.png)

**Comment by dreamnet** [comment]
Leaving out the "MOBILE"...
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38172174-9a76fbea-35a7-11e8-8695-0e61b78dff01.png)
https://user-images.githubusercontent.com/2068130/38172174-9a76fbea-35a7-11e8-8695-0e61b78dff01.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38172180-aa4cf11e-35a7-11e8-8762-548ea7e371f8.png
