### ISSUE TITLE
Werdsmith

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2348]
**App Name:** Werdsmith
**Bundle ID:** com.werdsmith.new
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489746330">489746330</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/werdsmith/id489746330?mt=8&uo=4">https://itunes.apple.com/us/app/werdsmith/id489746330?mt=8&uo=4</a>
**App Version:** 3.6.2
**Seller:** Nathan Tesler
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nathan-tesler/id469842974?uo=4>© Nathan Tesler</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/18/65/9c/18659c3a-12b9-08d4-0d23-0d19e1184d52/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18697776/d844ffac-7fc4-11e6-8d59-9d2c6bc1bbe5.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18697776/d844ffac-7fc4-11e6-8d59-9d2c6bc1bbe5.png)
https://cloud.githubusercontent.com/assets/2068130/18697776/d844ffac-7fc4-11e6-8d59-9d2c6bc1bbe5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18697781/e71b92de-7fc4-11e6-9ede-0a876f4117c8.png
