### ISSUE TITLE
iCleaner 

### ISSUE THREAD

**Issue by DarkXess** [glasklart/hd#235]
**App Name:** iCleaner
**Bundle ID:** org.altervista.exilecom.icleaner
**Version:** 7.5.0
**Repo:** BigBoss
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/10920515/c274f9ea-8270-11e5-8630-6eb59f98f534.png" width="150" height="150">
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/10920526/d2b1dc74-8270-11e5-9d59-8ebc0b4e3f39.png)

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/10920526/d2b1dc74-8270-11e5-9d59-8ebc0b4e3f39.png)
https://cloud.githubusercontent.com/assets/2068130/10920526/d2b1dc74-8270-11e5-9d59-8ebc0b4e3f39.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10920554/f7d0380c-8270-11e5-90c7-635356eba6fe.png
