### ISSUE TITLE
e-Boks.dk

### ISSUE THREAD

**Issue by messcrew** [glasklart/hd#2352]
**App Name:** e-Boks.dk
**Bundle ID:** dk.eboks.eboks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=482926022">482926022</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/e-boks.dk/id482926022?mt=8&uo=4">https://itunes.apple.com/us/app/e-boks.dk/id482926022?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** e-Boks A/S
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/e-boks/id482926025?uo=4>© e-Boks</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/0e/15/cb/0e15cbde-5468-80c9-4224-6e0c84a30786/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19627137/70dfd75c-9940-11e6-9872-653ea14f7000.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19627137/70dfd75c-9940-11e6-9872-653ea14f7000.png)
https://cloud.githubusercontent.com/assets/20930745/19627137/70dfd75c-9940-11e6-9872-653ea14f7000.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19627140/85a18884-9940-11e6-9f1a-ee24e3f8ca48.png
