### ISSUE TITLE
Top Eleven 2018 Soccer Manager

### ISSUE THREAD

**Issue by messcrew** [glasklart/hd#2355]
**App Name:** Top Eleven 2018 Soccer Manager
**Bundle ID:** eu.nordeus.TopEleven
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=459035295">459035295</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/top-eleven-2018-soccer-manager/id459035295?mt=8&uo=4">https://itunes.apple.com/us/app/top-eleven-2018-soccer-manager/id459035295?mt=8&uo=4</a>
**App Version:** 6.7
**Seller:** Nordeus Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nordeus/id664666426?uo=4">© Nordeus</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/53/62/42/53624204-0fcc-8b53-1e6d-01cdafe4f6ed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38171623-44291912-359d-11e8-82d3-f43d72ecb64b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38171623-44291912-359d-11e8-82d3-f43d72ecb64b.png)
https://user-images.githubusercontent.com/2068130/38171623-44291912-359d-11e8-82d3-f43d72ecb64b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38171627-54c895a4-359d-11e8-98c4-5cac2e65d017.png
