### ISSUE TITLE
多米音乐Pro

### ISSUE THREAD

**Issue by asoksevil** [glasklart/hd#2358]
**App Name:** 多米音乐Pro
**Bundle ID:** com.duomi.duomimusicpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=987221267">987221267</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/cn/app/%E5%A4%9A%E7%B1%B3%E9%9F%B3%E4%B9%90pro/id987221267?mt=8&uo=4">https://itunes.apple.com/cn/app/%E5%A4%9A%E7%B1%B3%E9%9F%B3%E4%B9%90pro/id987221267?mt=8&uo=4</a>
**App Version:** 6.8.0
**Seller:** Zhou Yi
**Developer:** <a target="_blank" href="https://itunes.apple.com/cn/developer/duomi/id412148992?uo=4">© DuoMi</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/bc/59/c5/bc59c56d-d950-a19d-5634-00acb3dc8404/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38172059-89555020-35a5-11e8-9e43-c33dd9409f09.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38172059-89555020-35a5-11e8-9e43-c33dd9409f09.png)
https://user-images.githubusercontent.com/2068130/38172059-89555020-35a5-11e8-9e43-c33dd9409f09.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38172062-98c33112-35a5-11e8-8d3f-fd14aa9ba799.png
