### ISSUE TITLE
InstaSize – Photo Editor, Photo Collage Maker

### ISSUE THREAD

**Issue by echominor** [glasklart/hd#2359]
**App Name:** InstaSize – Photo Editor, Photo Collage Maker
**Bundle ID:** InstaSize
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=576649830">576649830</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instasize-photo-editor-photo/id576649830?mt=8&uo=4">https://itunes.apple.com/us/app/instasize-photo-editor-photo/id576649830?mt=8&uo=4</a>
**App Version:** 4.1.32
**Seller:** Munkee Apps L.L.C.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/munkee-apps-l.l.c./id576649833?uo=4">© Munkee Apps L.L.C.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/00/a8/69/00a86959-1d39-30a9-a899-e1dcc37655af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20038655/99c7858c-a437-11e6-8dcd-d1c98094215e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20038655/99c7858c-a437-11e6-8dcd-d1c98094215e.png)
https://cloud.githubusercontent.com/assets/20930745/20038655/99c7858c-a437-11e6-8dcd-d1c98094215e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20038664/d82b5dee-a437-11e6-83d5-acbbf43253ea.png
