### ISSUE TITLE
Pandora 

### ISSUE THREAD

**Issue by echominor** [glasklart/hd#2360]
**App Name:** Pandora
**Bundle ID:** com.pandora.pandora
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404588425">404588425</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pandora/id404588425?mt=8&uo=4">https://itunes.apple.com/us/app/pandora/id404588425?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** PANDORA A/S
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pandora-a-s/id404588428?uo=4">© Pandora A/S</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/0a/c2/43/0ac24338-531b-cfef-3e48-128c4329ac6f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028495/a9e127e8-a333-11e6-8bc3-b3623f49e316.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028495/a9e127e8-a333-11e6-8bc3-b3623f49e316.png)
https://cloud.githubusercontent.com/assets/20930745/20028495/a9e127e8-a333-11e6-8bc3-b3623f49e316.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20028497/c0730986-a333-11e6-8adb-81bca2089a7e.png
