### ISSUE TITLE
Pic Collage - Photo Editor

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#2361]
**App Name:** Pic Collage - Photo Editor
**Bundle ID:** com.cardinalblue.PicCollage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448639966">448639966</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pic-collage-photo-editor/id448639966?mt=8&uo=4">https://itunes.apple.com/us/app/pic-collage-photo-editor/id448639966?mt=8&uo=4</a>
**App Version:** 7.25.8
**Seller:** Cardinal Blue Software, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cardinal-blue/id381057842?uo=4">© Cardinal Blue</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/8d/1e/7a/8d1e7a1e-76eb-435e-9ce0-3376d4fe67c4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33753376-45afffcc-dbe7-11e7-8ac6-4f0539946409.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33753376-45afffcc-dbe7-11e7-8ac6-4f0539946409.png)
https://user-images.githubusercontent.com/2068130/33753376-45afffcc-dbe7-11e7-8ac6-4f0539946409.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33753385-548a89c2-dbe7-11e7-8fc3-a2eb16b65583.png
