### ISSUE TITLE
Synesthetic

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#2363]
**App Name:** Synesthetic
**Bundle ID:** com.alexdantis.Synesthetic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=483688788">483688788</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/synesthetic/id483688788?mt=8&uo=4">https://itunes.apple.com/us/app/synesthetic/id483688788?mt=8&uo=4</a>
**App Version:** 1.08
**Seller:** Alexandru Eugen Dantis
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alex-dantis/id430169756?uo=4">© Alex Dantis</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/56/7b/c5/567bc5a7-5c2d-1e11-94fd-726e2fe7fb99/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33753777-5adc84fe-dbe9-11e7-9a9f-f493272a40a1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33753777-5adc84fe-dbe9-11e7-9a9f-f493272a40a1.png)
https://user-images.githubusercontent.com/2068130/33753777-5adc84fe-dbe9-11e7-9a9f-f493272a40a1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33753786-6c210d52-dbe9-11e7-8b31-2ed088bba8fe.png
