### ISSUE TITLE
Tap the Frog

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#2364]
**App Name:** Tap the Frog
**Bundle ID:** com.playmous.ttf2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=483353496">483353496</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tap-the-frog/id483353496?mt=8&uo=4">https://itunes.apple.com/us/app/tap-the-frog/id483353496?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Playmous, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/playmous/id483353499?uo=4">© Playmous</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/60/05/3a/60053a03-7a71-e0bc-3a88-5875b5cc120e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26373429/d3890b86-4001-11e7-8150-79f98059b736.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26373429/d3890b86-4001-11e7-8150-79f98059b736.png)
https://cloud.githubusercontent.com/assets/2068130/26373429/d3890b86-4001-11e7-8150-79f98059b736.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26373449/e243636a-4001-11e7-8048-8654cec7a825.png
