### ISSUE TITLE
Fragger

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#2366]
**App Name:** Fragger
**Bundle ID:** com.miniclip.Fragger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=373046496">373046496</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fragger/id373046496?mt=8&uo=4">https://itunes.apple.com/us/app/fragger/id373046496?mt=8&uo=4</a>
**App Version:** 1.11.4
**Seller:** Miniclip SA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/miniclip-com/id337457683?uo=4">© Miniclip.com</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/67/12/7a/67127a2c-eb0e-f558-fb06-ccd56384fbb5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26750509/e2b9d916-4824-11e7-9022-3f2972a882a4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26750509/e2b9d916-4824-11e7-9022-3f2972a882a4.png)
https://cloud.githubusercontent.com/assets/2068130/26750509/e2b9d916-4824-11e7-9022-3f2972a882a4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26750512/f3256342-4824-11e7-9192-531c28cf1f78.png
