### ISSUE TITLE
WeChat

### ISSUE THREAD

**Issue by DarkXess** [glasklart/hd#237]
**App Name:** WeChat
**Bundle ID:** com.tencent.xin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=414478124">414478124</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wechat/id414478124?mt=8&uo=4">https://itunes.apple.com/us/app/wechat/id414478124?mt=8&uo=4</a>
**App Version:** 6.3.27
**Seller:** Tencent Technology (Shenzhen) Company Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wechat/id614694882?uo=4>© WeChat</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/2d/ae/9e/2dae9e53-9855-558f-464e-cf4324198989/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402110/68b2fcb8-925f-11e6-8019-95325866d7be.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402110/68b2fcb8-925f-11e6-8019-95325866d7be.png)
https://cloud.githubusercontent.com/assets/20930745/19402110/68b2fcb8-925f-11e6-8019-95325866d7be.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19402118/7892ab42-925f-11e6-8dbe-2259846e5e3e.png
