### ISSUE TITLE
EMD PTE

### ISSUE THREAD

**Issue by AmbassadorThroz** [glasklart/hd#2372]
**App Name:** EMD PTE
**Bundle ID:** com.mwaysolutions.emdpse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377393859">377393859</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/emd-pte/id377393859?mt=8&uo=4">https://itunes.apple.com/us/app/emd-pte/id377393859?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Merck KGaA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/merck-kgaa/id370548001?uo=4>© Merck KGaA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/34/2b/1b/342b1b64-081b-9f22-0f2a-9a73b1eeb1ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626949/fcf5f0ea-993c-11e6-94f7-53e82e628f23.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626949/fcf5f0ea-993c-11e6-94f7-53e82e628f23.png)
https://cloud.githubusercontent.com/assets/20930745/19626949/fcf5f0ea-993c-11e6-94f7-53e82e628f23.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626954/1b3ba45a-993d-11e6-9254-461a07457305.png
