### ISSUE TITLE
CamWow: Free photo booth effects live on camera!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2374]
**App Name:** CamWow: Free photo booth effects live on camera!
**Bundle ID:** com.jollydream.camwow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418368641">418368641</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camwow-free-photo-booth-effects/id418368641?mt=8&uo=4">https://itunes.apple.com/us/app/camwow-free-photo-booth-effects/id418368641?mt=8&uo=4</a>
**App Version:** 2.8
**Seller:** Jing Chan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jing-chan/id418368644?uo=4>© Jing Chan</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/91/4f/5e/914f5ecc-0a33-e912-de62-e044afd3af1e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18811648/ca3c769c-82b7-11e6-8b80-a7c94cf9a24c.png)

**Comment by ivanov007** [comment]
needs update

**Comment by dreamnet** [comment]
The lens is from @2Qt2beStr8 
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18811648/ca3c769c-82b7-11e6-8b80-a7c94cf9a24c.png)
https://cloud.githubusercontent.com/assets/2068130/18811648/ca3c769c-82b7-11e6-8b80-a7c94cf9a24c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18811653/df4264e8-82b7-11e6-9e25-b0e443809d7c.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18811736/33a13cd8-82ba-11e6-9d12-fd33ef691238.png)
https://cloud.githubusercontent.com/assets/20930745/18811736/33a13cd8-82ba-11e6-9d12-fd33ef691238.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18811737/5e33bf84-82ba-11e6-84c4-ce1bf9415e90.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Should I change it?

**Comment by 2Qt2beStr8** [comment]
.... you are the boss :-) ... i don't know ... you can take this one you like more :-)

**Comment by dreamnet** [comment]
@2Qt2beStr8 I leave it as it is to look similar as #2382.

**Comment by 2Qt2beStr8** [comment]
yes .. is ok ... the only different is the lens
