### ISSUE TITLE
My Optus

### ISSUE THREAD

**Issue by JamesMinaj** [glasklart/hd#2375]
**App Name:** My Optus
**Bundle ID:** au.com.optus.selfserviceapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=503716230">503716230</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-optus/id503716230?mt=8&uo=4">https://itunes.apple.com/us/app/my-optus/id503716230?mt=8&uo=4</a>
**App Version:** 3.62
**Seller:** Optus Mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/optus-mobile/id330227157?uo=4>© Optus Mobile</a>
**Supported Devices:** iPhone4S, iPhone5, iPhone5c, iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/0b/ff/ae/0bffae8c-d08f-9879-b8f9-2dfac7a0fec4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625890/31fc353c-9925-11e6-9d6c-8046cf4d789e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625890/31fc353c-9925-11e6-9d6c-8046cf4d789e.png)
https://cloud.githubusercontent.com/assets/20930745/19625890/31fc353c-9925-11e6-9d6c-8046cf4d789e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625897/4587b090-9925-11e6-9925-bbcd48202e4d.png
