### ISSUE TITLE
Baby Names™

### ISSUE THREAD

**Issue by AmbassadorThroz** [glasklart/hd#2376]
**App Name:** Baby Names™
**Bundle ID:** com.schatzisoft.babynamesplusfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=353938652">353938652</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/baby-names/id353938652?mt=8&uo=4">https://itunes.apple.com/us/app/baby-names/id353938652?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** Schatzisoft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/schatzisoft/id326144701?uo=4>© Schatzisoft</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/0d/bf/cc/0dbfcc01-c598-4f80-1e77-be8630fc0158/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626919/2e4e256e-993c-11e6-854a-d4188c463e34.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19626919/2e4e256e-993c-11e6-854a-d4188c463e34.png)
https://cloud.githubusercontent.com/assets/20930745/19626919/2e4e256e-993c-11e6-854a-d4188c463e34.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19626921/445d014a-993c-11e6-813d-1d7601297d23.png
