### ISSUE TITLE
Despair

### ISSUE THREAD

**Issue by echominor** [glasklart/hd#2379]
**App Name:** Despair
**Bundle ID:** ru.gria.despair
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=621652778">621652778</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/despair/id621652778?mt=8&uo=4">https://itunes.apple.com/us/app/despair/id621652778?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Anton Grishin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/anton-grishin/id490480668?uo=4>© Anton Grishin</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/1d/49/f0/1d49f0a4-4293-efae-ec1b-920ad704efa5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19382271/bcd11592-91ff-11e6-9e03-65d1f2b6afd2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19382271/bcd11592-91ff-11e6-9e03-65d1f2b6afd2.png)
https://cloud.githubusercontent.com/assets/20930745/19382271/bcd11592-91ff-11e6-9e03-65d1f2b6afd2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19382288/d36ec02e-91ff-11e6-99f8-87dfa2aad8c0.png
