### ISSUE TITLE
Converter - Universal Conversions incl. Hardness, Units, Timezone and Currency

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2380]
**App Name:** Converter - Universal Conversions incl. Hardness, Units, Timezone and Currency
**Bundle ID:** com.trelleborg.tss.converter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=423521445">423521445</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/converter-universal-conversions/id423521445?mt=8&uo=4">https://itunes.apple.com/us/app/converter-universal-conversions/id423521445?mt=8&uo=4</a>
**App Version:** 3.9
**Seller:** Trelleborg Sealing Solutions Germany GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/trelleborg-sealing-solutions/id396863758?uo=4>© Trelleborg Sealing Solutions</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/c1/fd/30/c1fd307d-7151-3069-ac3c-4dedcf72308f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19356890/a1179f64-916f-11e6-81ab-1b958c34438b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19356890/a1179f64-916f-11e6-81ab-1b958c34438b.png)
https://cloud.githubusercontent.com/assets/20930745/19356890/a1179f64-916f-11e6-81ab-1b958c34438b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19356922/b7ff48ee-916f-11e6-8bb6-fbc58983c5a0.png
