### ISSUE TITLE
CamWow Retro: Vintage photo booth effects live on camera!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2382]
**App Name:** CamWow Retro: Vintage photo booth effects live on camera!
**Bundle ID:** com.jollydream.camwowretro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498639341">498639341</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camwow-retro-vintage-photo/id498639341?mt=8&uo=4">https://itunes.apple.com/us/app/camwow-retro-vintage-photo/id498639341?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Jing Chan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jing-chan/id418368644?uo=4>© Jing Chan</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/04/d5/9d/04d59d1e-4e53-a88d-09d9-39b0ffa964a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18811392/61e3b3de-82ae-11e6-8859-e52689e8fb0f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18811392/61e3b3de-82ae-11e6-8859-e52689e8fb0f.png)
https://cloud.githubusercontent.com/assets/20930745/18811392/61e3b3de-82ae-11e6-8859-e52689e8fb0f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18811398/8e4647ca-82ae-11e6-84e2-8003f00c15e0.png
