### ISSUE TITLE
AnachB|VOR

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2383]
**App Name:** AnachB|VOR
**Bundle ID:** com.fluidtime.anachb1.1.7
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=371295078">371295078</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/anachb-vor/id371295078?mt=8&uo=4">https://itunes.apple.com/us/app/anachb-vor/id371295078?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** ASFINAG Maut-Service GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/verkehrsauskunft-%C3%B6sterreich/id879339413?uo=4">© Verkehrsauskunft Österreich</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/39/a5/f8/39a5f8a8-8975-ed04-39c3-58fa269dbe8d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33753019-73669234-dbe5-11e7-9bef-ca9151ab33e3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33753019-73669234-dbe5-11e7-9bef-ca9151ab33e3.png)
https://user-images.githubusercontent.com/2068130/33753019-73669234-dbe5-11e7-9bef-ca9151ab33e3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33753043-8c62cf46-dbe5-11e7-93a0-59879ba3c0b0.png
