### ISSUE TITLE
LateRooms - Low cost, last minute hotels

### ISSUE THREAD

**Issue by alex810158** [glasklart/hd#2386]
**App Name:** LateRooms - Low cost, last minute hotels
**Bundle ID:** A2472GEPBL
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=334701579">334701579</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/laterooms-low-cost-last-minute/id334701579?mt=8&uo=4">https://itunes.apple.com/us/app/laterooms-low-cost-last-minute/id334701579?mt=8&uo=4</a>
**App Version:** 5.5.2
**Seller:** LATEROOMS LIMITED
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/late-rooms-limited/id742800903?uo=4">© LATE ROOMS LIMITED</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/a3/d4/41/a3d4413d-439f-834c-2fd2-352807d0c4c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040694/16655618-a45c-11e6-82fa-0a4eb4503f55.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040694/16655618-a45c-11e6-82fa-0a4eb4503f55.png)
https://cloud.githubusercontent.com/assets/20930745/20040694/16655618-a45c-11e6-82fa-0a4eb4503f55.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20040704/2def7e9e-a45c-11e6-83a9-3706508a10d2.png
