### ISSUE TITLE
Advanced Password Creator

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2389]
**App Name:** Advanced Password Creator
**Bundle ID:** dk.devlix.Pronounceable-Password-Generator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389598577">389598577</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/advanced-password-creator/id389598577?mt=8&uo=4">https://itunes.apple.com/us/app/advanced-password-creator/id389598577?mt=8&uo=4</a>
**App Version:** 1.6.4
**Seller:** Jimmy Selgen
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jimmy-selgen-nielsen/id389593762?uo=4">© Jimmy Selgen Nielsen</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple18/v4/ca/a0/fb/caa0fb38-6300-3bce-1e7d-f9cb3e7f7e10/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030216/a2e7eb70-a360-11e6-863d-da3e68fcd2dc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030216/a2e7eb70-a360-11e6-863d-da3e68fcd2dc.png)
https://cloud.githubusercontent.com/assets/20930745/20030216/a2e7eb70-a360-11e6-863d-da3e68fcd2dc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20030225/b933d2d6-a360-11e6-83f3-f999f47dfd9e.png
