### ISSUE TITLE
QQ

### ISSUE THREAD

**Issue by DarkXess** [glasklart/hd#239]
**App Name:** QQ
**Bundle ID:** com.tencent.mqq
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444934666">444934666</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qq/id444934666?mt=8&uo=4">https://itunes.apple.com/us/app/qq/id444934666?mt=8&uo=4</a>
**App Version:** 7.9.9
**Seller:** Tencent Technology (Shenzhen) Company Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tencent-technology-shenzhen-company-limited/id292374531?mt=8&uo=4">© Tencent Technology (Shenzhen) Company Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/7d/0e/8e/7d0e8ee0-fb12-3a10-0597-718764c5e6ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/54864020-b9b6d400-4d50-11e9-840f-ed9e18b2821b.png)

**Comment by Christian9901** [comment]
update please

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/54864020-b9b6d400-4d50-11e9-840f-ed9e18b2821b.png)
https://user-images.githubusercontent.com/2068130/54864020-b9b6d400-4d50-11e9-840f-ed9e18b2821b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/54864025-cb987700-4d50-11e9-985e-d1f789dc9fca.png
