### ISSUE TITLE
Tivizen

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2390]
**App Name:** Tivizen
**Bundle ID:** com.elgato.tivizen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424641905">424641905</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/tivizen/id424641905?mt=8&uo=4">https://itunes.apple.com/gb/app/tivizen/id424641905?mt=8&uo=4</a>
**App Version:** 2.0.4
**Seller:** SHENZHEN GENIATECH INC.,LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/shenzhen-geniatech-inc.-ltd/id542603014?uo=4">© SHENZHEN GENIATECH INC.,LTD</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/f3/a4/ac/f3a4ac19-325e-6c9a-3b0f-8e0b4265b6b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030106/5a81d4d8-a35e-11e6-95db-75b5435d6f78.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030106/5a81d4d8-a35e-11e6-95db-75b5435d6f78.png)
https://cloud.githubusercontent.com/assets/20930745/20030106/5a81d4d8-a35e-11e6-95db-75b5435d6f78.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20030111/721448f6-a35e-11e6-8a4d-2ab4d8e58adf.png

**Comment by babamkakis** [comment]
I know this is out of the blue, but does anyone have the .ipa file or this app in their purchased history, I have the tuner receiver and this app has been removed from the app store.. Please help.
