### ISSUE TITLE
PhotoMagic - Photo Effect Studio & Photo Editor

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2394]
**App Name:** PhotoMagic - Photo Effect Studio & Photo Editor
**Bundle ID:** softease.photomagicios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=579230672">579230672</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photomagic-photo-effect-studio/id579230672?mt=8&uo=4">https://itunes.apple.com/us/app/photomagic-photo-effect-studio/id579230672?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** SOFTEASE TECH CO., LIMITED
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/softease-tech-co.-limited/id422246654?uo=4">© SOFTEASE TECH CO., LIMITED</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/0c/b7/b4/0cb7b4be-9b95-4724-aa44-6457487d8987/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20648697/42c63c7e-b4ae-11e6-9759-63e861d8a946.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20648697/42c63c7e-b4ae-11e6-9759-63e861d8a946.png)
https://cloud.githubusercontent.com/assets/20930745/20648697/42c63c7e-b4ae-11e6-9759-63e861d8a946.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20648709/7cbf65fe-b4ae-11e6-8599-dc6c8a71209c.png
