### ISSUE TITLE
Outdoor Navigation ape@map

### ISSUE THREAD

**Issue by praschi** [glasklart/hd#2398]
**App Name:** Outdoor Navigation ape@map
**Bundle ID:** com.apemap.tour
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454550868">454550868</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/outdoor-navigation-ape-map/id454550868?mt=8&uo=4">https://itunes.apple.com/us/app/outdoor-navigation-ape-map/id454550868?mt=8&uo=4</a>
**App Version:** 3.2.0
**Seller:** Onyx Technologie OG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/onyx-technologie-og/id454550871?uo=4">© Onyx Technologie OG</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/dc/81/80/dc818043-b70e-98ab-46a6-5565d58c1f8d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39778638-27cc3cc2-5307-11e8-88fb-40ad9a4a659a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39778638-27cc3cc2-5307-11e8-88fb-40ad9a4a659a.png)
https://user-images.githubusercontent.com/2068130/39778638-27cc3cc2-5307-11e8-88fb-40ad9a4a659a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39778661-36315d7e-5307-11e8-886f-0c2c8b7ad300.png
