### ISSUE TITLE
Downcast

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#24]
**App Name:** Downcast
**Bundle ID:** com.jamawkinaw.downcast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393858566">393858566</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/downcast/id393858566?mt=8&uo=4">https://itunes.apple.com/us/app/downcast/id393858566?mt=8&uo=4</a>
**App Version:** 2.9.9
**Seller:** Jamawkinaw Enterprises LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jamawkinaw-enterprises-llc/id393858569?uo=4>© Jamawkinaw Enterprises LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/c2/d7/6e/c2d76e65-6807-0025-80b6-5f34ad37f16b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12767674/d9346d82-ca0a-11e5-89e4-eb5c762ffbb5.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12767674/d9346d82-ca0a-11e5-89e4-eb5c762ffbb5.png)
https://cloud.githubusercontent.com/assets/10730122/12767674/d9346d82-ca0a-11e5-89e4-eb5c762ffbb5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12767673/d91a5d0c-ca0a-11e5-8ee9-987e76869da0.png
