### ISSUE TITLE
Numeracion de Mexico

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2400]
**App Name:** Numeracion de Mexico
**Bundle ID:** com.desarrollos.numeracion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388833548">388833548</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/numeracion-de-mexico/id388833548?mt=8&uo=4">https://itunes.apple.com/us/app/numeracion-de-mexico/id388833548?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Omar Garcia Sanchez
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/omar-garcia-sanchez/id388833551?uo=4">© Omar Garcia Sanchez</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/62/a9/ae/62a9aea6-ab90-c1cf-0ebc-8b3af938d1f6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030039/f2232fb4-a35c-11e6-8835-c2713e8a9e0e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030039/f2232fb4-a35c-11e6-8835-c2713e8a9e0e.png)
https://cloud.githubusercontent.com/assets/20930745/20030039/f2232fb4-a35c-11e6-8835-c2713e8a9e0e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20030051/256b1aee-a35d-11e6-9d24-2e7851dbc454.png
