### ISSUE TITLE
FINAL FANTASY III

### ISSUE THREAD

**Issue by SuperRipped** [glasklart/hd#2402]
**App Name:** FINAL FANTASY III
**Bundle ID:** com.square-enix.FinalFantasy3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424591347">424591347</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/final-fantasy-iii/id424591347?mt=8&uo=4">https://itunes.apple.com/us/app/final-fantasy-iii/id424591347?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPad23G, iPadWifi, iPodTouchFifthGen, iPadMini4G, iPad3G, iPhone5s, iPodTouchThirdGen, iPadFourthGen, iPadThirdGen, iPad2Wifi, iPhone6, iPhone5c, iPadFourthGen4G, iPhone6Plus, iPadMini, iPhone4, iPhone-3GS, iPadThirdGen4G, iPhone5, iPhone4S, iPodTouchFourthGen
**Original Artwork:**
<img src="http://a289.phobos.apple.com/us/r30/Purple2/v4/cc/6c/2d/cc6c2d20-7d3b-d691-e469-3bdd5305933c/mzl.spzhzeoh.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997272/3c0fc2a6-db84-11e4-8f88-3b6810cde05b.png)

**Comment by zmathiasz** [comment]
@dreamnet 

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997272/3c0fc2a6-db84-11e4-8f88-3b6810cde05b.png)
https://cloud.githubusercontent.com/assets/10950389/6997272/3c0fc2a6-db84-11e4-8f88-3b6810cde05b.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6997274/4c4f86ec-db84-11e4-98be-f2512208c439.png
