### ISSUE TITLE
FINAL FANTASY IV

### ISSUE THREAD

**Issue by SuperRipped** [glasklart/hd#2403]
**App Name:** FINAL FANTASY IV
**Bundle ID:** com.square-enix.FinalFantasy4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=575119311">575119311</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/final-fantasy-iv/id575119311?mt=8&uo=4">https://itunes.apple.com/us/app/final-fantasy-iv/id575119311?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone4S, iPadFourthGen, iPadMini4G, iPhone5s, iPadMini, iPhone5, iPad2Wifi, iPadThirdGen4G, iPad23G, iPhone6, iPodTouchThirdGen, iPhone-3GS, iPhone5c, iPodTouchFifthGen, iPhone4, iPad3G, iPodTouchFourthGen, iPadThirdGen, iPhone6Plus, iPadFourthGen4G, iPadWifi
**Original Artwork:**
<img src="http://a1274.phobos.apple.com/us/r30/Purple3/v4/0d/64/94/0d649423-0e3c-ec0a-cfad-902fa096c791/mzl.fmlhjmdi.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997172/1714f052-db7f-11e4-9d2a-c4331a080260.png)

**Comment by zmathiasz** [comment]
@dreamnet I don't need any credit for the icons I am updating for iPhone 6+ :smiley: 

Updated icon w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997172/1714f052-db7f-11e4-9d2a-c4331a080260.png)
https://cloud.githubusercontent.com/assets/10950389/6997172/1714f052-db7f-11e4-9d2a-c4331a080260.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6997176/28624c60-db7f-11e4-9ce1-8158d9c27a43.png

**Comment by dreamnet** [comment]
@zmathiasz Ah, that's OK, why not? You are doing good work. :+1:
