### ISSUE TITLE
FINAL FANTASY V

### ISSUE THREAD

**Issue by SuperRipped** [glasklart/hd#2404]
**App Name:** FINAL FANTASY V
**Bundle ID:** com.square-enix.FinalFantasy5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=609577016">609577016</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/final-fantasy-v/id609577016?mt=8&uo=4">https://itunes.apple.com/us/app/final-fantasy-v/id609577016?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone4S, iPadWifi, iPhone-3GS, iPadMini, iPadThirdGen4G, iPadMini4G, iPad23G, iPodTouchFifthGen, iPad3G, iPhone4, iPhone5, iPadFourthGen, iPadThirdGen, iPad2Wifi, iPhone6Plus, iPodTouchFourthGen, iPodTouchThirdGen, iPadFourthGen4G, iPhone5c
**Original Artwork:**
<img src="http://a363.phobos.apple.com/us/r30/Purple5/v4/d0/b7/6b/d0b76bba-6adb-0ded-3ef0-095be7d5c070/mzl.bdkiukjp.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997374/0c735a46-db87-11e4-9504-0a932a94b6af.png)

**Comment by zmathiasz** [comment]
@dreamnet 

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997374/0c735a46-db87-11e4-9504-0a932a94b6af.png)
https://cloud.githubusercontent.com/assets/10950389/6997374/0c735a46-db87-11e4-9504-0a932a94b6af.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6997377/2889ca44-db87-11e4-9560-a5c37787f0b2.png
