### ISSUE TITLE
Radio Record

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#241]
**App Name:** Radio Record
**Bundle ID:** com.cronos.recordplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=396869519">396869519</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radio-record/id396869519?mt=8&uo=4">https://itunes.apple.com/us/app/radio-record/id396869519?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** Radio Record, ZAO
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/radio-record-zao/id1107622023?uo=4">© Radio Record, ZAO</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/54/46/66/54466612-708d-60dd-0cee-facf1c51bd13/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32371435-1eca942e-c091-11e7-84e1-52a35a5afb83.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32371435-1eca942e-c091-11e7-84e1-52a35a5afb83.png)
https://user-images.githubusercontent.com/2068130/32371435-1eca942e-c091-11e7-84e1-52a35a5afb83.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32371444-2dc81816-c091-11e7-9a6b-5b53d7296706.png
