### ISSUE TITLE
Multiplayer for Minecraft PE

### ISSUE THREAD

**Issue by vinsounet** [glasklart/hd#2410]
**App Name:** Multiplayer for Minecraft PE
**Bundle ID:** com.innovativedevs.multiplayerPE
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=609704981">609704981</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/multiplayer-for-minecraft-pe/id609704981?mt=8&uo=4">https://itunes.apple.com/us/app/multiplayer-for-minecraft-pe/id609704981?mt=8&uo=4</a>
**App Version:** 3.31
**Seller:** Innovative Devices UK Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/innovative-devs/id513315144?uo=4">© Innovative Devs</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/b3/ab/30/b3ab3068-1a04-34e6-83cf-42d27d9810fb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38166530-505f15e2-3525-11e8-9988-84b9447405b5.png)

**Comment by Christian9901** [comment]
**App Name:** Multiplayer for Minecraft PE
**Bundle ID:** com.innovativedevs.multiplayerPE
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=609704981">609704981</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/multiplayer-for-minecraft-pe/id609704981?mt=8&uo=4">https://itunes.apple.com/us/app/multiplayer-for-minecraft-pe/id609704981?mt=8&uo=4</a>
**App Version:** 3.31
**Seller:** Innovative Devices UK Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/innovative-devs/id513315144?uo=4">© Innovative Devs</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/b3/ab/30/b3ab3068-1a04-34e6-83cf-42d27d9810fb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38166530-505f15e2-3525-11e8-9988-84b9447405b5.png)
https://user-images.githubusercontent.com/2068130/38166530-505f15e2-3525-11e8-9988-84b9447405b5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38166531-5ed12a52-3525-11e8-953d-12448ed43ba3.png
