### ISSUE TITLE
Boligsiden

### ISSUE THREAD

**Issue by messcrew** [glasklart/hd#2418]
**App Name:** Boligsiden
**Bundle ID:** dk.boligsiden
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=385702418">385702418</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boligsiden/id385702418?mt=8&uo=4">https://itunes.apple.com/us/app/boligsiden/id385702418?mt=8&uo=4</a>
**App Version:** 2.5.3
**Seller:** Boligsiden A/S
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/boligsiden-a-s/id385702421?uo=4">© Boligsiden A/S</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/66/b4/aa/66b4aa1d-e210-12bc-1e1b-53f147891447/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25073707/410c2fb8-22ec-11e7-8062-f878d8a34e5d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25073707/410c2fb8-22ec-11e7-8062-f878d8a34e5d.png)
https://cloud.githubusercontent.com/assets/2068130/25073707/410c2fb8-22ec-11e7-8062-f878d8a34e5d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25073710/4f4505c8-22ec-11e7-8dda-ee6aa1289ad5.png
