### ISSUE TITLE
Bluefire Reader

### ISSUE THREAD

**Issue by AmbassadorThroz** [glasklart/hd#2419]
**App Name:** Bluefire Reader
**Bundle ID:** tv.bluefire.bluefirereader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=394275498">394275498</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bluefire-reader/id394275498?mt=8&uo=4">https://itunes.apple.com/us/app/bluefire-reader/id394275498?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Bluefire Productions
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bluefire-productions/id394275501?uo=4>© Bluefire Productions</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/b8/a3/9f/b8a39fb1-eb8c-166f-8a4b-8321a32df158/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625844/09f43fea-9924-11e6-985a-d9593cff7c9a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625844/09f43fea-9924-11e6-985a-d9593cff7c9a.png)
https://cloud.githubusercontent.com/assets/20930745/19625844/09f43fea-9924-11e6-985a-d9593cff7c9a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625848/24a35448-9924-11e6-80ec-ffcfe526428e.png
