### ISSUE TITLE
Flow Free

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#242]
**App Name:** Flow Free
**Bundle ID:** com.bigduckgames.flow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526641427">526641427</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flow-free/id526641427?mt=8&uo=4">https://itunes.apple.com/us/app/flow-free/id526641427?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Big Duck Games LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/big-duck-games-llc/id435664937?uo=4>© Big Duck Games LLC</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen4G, iPodTouchThirdGen, iPadMini, iPhone4, iPhone4S, iPhone5s, iPadMini4G, iPhone6Plus, iPhone6, iPadThirdGen, iPadFourthGen, iPadWifi, iPhone-3GS, iPad23G, iPadFourthGen4G, iPodTouchFifthGen, iPhone5, iPad3G, iPodTouchFourthGen, iPhone5c
**Original Artwork:**
<img src="http://a1440.phobos.apple.com/us/r30/Purple1/v4/9e/ba/6c/9eba6c05-03ef-20f3-0475-d8f2a069569f/mzl.yqioiwzu.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6995406/8b991194-db14-11e4-89d6-101e46405283.png)

**Comment by zmathiasz** [comment]
**App Name:** Flow Free
**Bundle ID:** com.bigduckgames.flow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526641427">526641427</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flow-free/id526641427?mt=8&uo=4">https://itunes.apple.com/us/app/flow-free/id526641427?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Big Duck Games LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/big-duck-games-llc/id435664937?uo=4>© Big Duck Games LLC</a>
**Supported Devices:** iPadMini, iPadMini4G, iPadThirdGen4G, iPadFourthGen4G, iPadThirdGen, iPad3G, iPhone5c, iPhone4, iPodTouchFourthGen, iPadFourthGen, iPhone6Plus, iPad23G, iPhone6, iPodTouchFifthGen, iPhone5, iPodTouchThirdGen, iPhone5s, iPhone4S, iPad2Wifi, iPhone-3GS, iPadWifi
**Original Artwork:**
<img src="http://a1440.phobos.apple.com/us/r30/Purple1/v4/9e/ba/6c/9eba6c05-03ef-20f3-0475-d8f2a069569f/mzl.yqioiwzu.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by zmathiasz** [comment]
@dreamnet 

Icon update w/source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6995406/8b991194-db14-11e4-89d6-101e46405283.png)
https://cloud.githubusercontent.com/assets/10950389/6995406/8b991194-db14-11e4-89d6-101e46405283.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6995408/9e427880-db14-11e4-9e90-4900e69dca61.png
