### ISSUE TITLE
Mahjong Classic :)

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#2421]
**App Name:** Mahjong Classic :)
**Bundle ID:** com.ticbits.Mahjong
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=455650659">455650659</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mahjong-classic/id455650659?mt=8&uo=4">https://itunes.apple.com/us/app/mahjong-classic/id455650659?mt=8&uo=4</a>
**App Version:** 1.8.4
**Seller:** The Solitaire, Mahjong and Sudoku Company, LLC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/solitaire-mahjong-and-sudoku-company/id1289801633?uo=4">© Solitaire, Mahjong and Sudoku Company</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/a0/f6/0a/a0f60a01-95d7-2806-e07e-f2855f6eb50b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39851842-a5ebcec0-5419-11e8-8dc5-f0091c7b139c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39851842-a5ebcec0-5419-11e8-8dc5-f0091c7b139c.png)
https://user-images.githubusercontent.com/2068130/39851842-a5ebcec0-5419-11e8-8dc5-f0091c7b139c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39851854-b5eed452-5419-11e8-9b32-86292de25b24.png
