### ISSUE TITLE
Snake '97

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#2424]
**App Name:** Snake '97
**Bundle ID:** nl.wmit.snake
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431054645">431054645</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snake-97/id431054645?mt=8&uo=4">https://itunes.apple.com/us/app/snake-97/id431054645?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** dsd 164 B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dsd-164/id489465257?uo=4>© dsd 164</a>
**Supported Devices:** iPhone5, iPhone4, iPadMini4G, iPhone6, iPadThirdGen, iPadFourthGen4G, iPhone6Plus, iPadMini, iPhone4S, iPhone5s, iPodTouchFifthGen, iPad2Wifi, iPad23G, iPadThirdGen4G, iPadFourthGen, iPhone5c
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple/v4/f3/10/d5/f310d522-43e1-54ed-ecc4-8fc764b23dce/mzl.mocdcryj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7903918/f8ddccec-07ea-11e5-8f9c-9de12ff4234e.png)

**Comment by dreamnet** [comment]
Same as for #5717 .
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7903918/f8ddccec-07ea-11e5-8f9c-9de12ff4234e.png)
https://cloud.githubusercontent.com/assets/2068130/7903918/f8ddccec-07ea-11e5-8f9c-9de12ff4234e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7903923/088b2ef0-07eb-11e5-9b2f-6635c4e4b77c.png
