### ISSUE TITLE
Solid Joys | Daily Devotional

### ISSUE THREAD

**Issue by 4ndysmith** [glasklart/hd#2426]
**App Name:** Solid Joys | Daily Devotional
**Bundle ID:** com.desiringgod.Piper-Daily-Devotional
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=553049864">553049864</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/solid-joys-daily-devotional/id553049864?mt=8&uo=4">https://itunes.apple.com/us/app/solid-joys-daily-devotional/id553049864?mt=8&uo=4</a>
**App Version:** 2.8.4
**Seller:** Desiring God
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/desiring-god/id463863592?uo=4">© Desiring God</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/ac/9a/0f/ac9a0f41-8f1d-58cc-1ee3-33495ac9ff9c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160304-c07a7336-34bb-11e8-8910-e792f1326cec.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160304-c07a7336-34bb-11e8-8910-e792f1326cec.png)
https://user-images.githubusercontent.com/2068130/38160304-c07a7336-34bb-11e8-8910-e792f1326cec.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38160307-d0f13f92-34bb-11e8-861f-f5c7b95a28ae.png
