### ISSUE TITLE
Ask Pastor John

### ISSUE THREAD

**Issue by 4ndysmith** [glasklart/hd#2427]
**App Name:** Ask Pastor John
**Bundle ID:** org.desiringgod.askpastorjohn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606284215">606284215</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ask-pastor-john/id606284215?mt=8&uo=4">https://itunes.apple.com/us/app/ask-pastor-john/id606284215?mt=8&uo=4</a>
**App Version:** 1.6.2
**Seller:** Desiring God
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/desiring-god/id463863592?uo=4>© Desiring God</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/d1/2d/3b/d12d3ba9-34d5-fdf1-bd4b-789431dca566/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625700/36cbdb12-9920-11e6-8a5f-7b81253d81b1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625700/36cbdb12-9920-11e6-8a5f-7b81253d81b1.png)
https://cloud.githubusercontent.com/assets/20930745/19625700/36cbdb12-9920-11e6-8a5f-7b81253d81b1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625705/5a9e2c98-9920-11e6-80d1-6a65df26755b.png
