### ISSUE TITLE
Faithlife Study Bible

### ISSUE THREAD

**Issue by 4ndysmith** [glasklart/hd#2428]
**App Name:** Faithlife Study Bible
**Bundle ID:** com.logos.faithlifestudybible
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=485998842">485998842</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/faithlife-study-bible/id485998842?uo=4">https://apps.apple.com/us/app/faithlife-study-bible/id485998842?uo=4</a>
**App Version:** 8.4.0
**Seller:** Faithlife Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/faithlife-corporation/id336400269?uo=4">© Faithlife Corporation</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/00/1e/3b/001e3b33-c411-9992-f7e6-ae92b7f9d2cf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393827-d74bc480-9b1b-11e9-8180-47ab03976770.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19229678/a926e5d6-8ecf-11e6-9ab2-f5018255d811.png)
https://cloud.githubusercontent.com/assets/20930745/19229678/a926e5d6-8ecf-11e6-9ab2-f5018255d811.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19229686/b95db38a-8ecf-11e6-82ac-83ce2eb67516.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393827-d74bc480-9b1b-11e9-8180-47ab03976770.png)
https://user-images.githubusercontent.com/20930745/60393827-d74bc480-9b1b-11e9-8180-47ab03976770.png

Source:
https://user-images.githubusercontent.com/20930745/60393838-ee8ab200-9b1b-11e9-827c-469aa93693de.png
