### ISSUE TITLE
Solitaire Classic :)

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#2431]
**App Name:** Solitaire Classic :)
**Bundle ID:** com.ticbits.solitaire
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426438823">426438823</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/solitaire-classic/id426438823?mt=8&uo=4">https://itunes.apple.com/us/app/solitaire-classic/id426438823?mt=8&uo=4</a>
**App Version:** 1.4.7
**Seller:** The Solitaire, Mahjong and Sudoku Company, LLC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/solitaire-mahjong-and-sudoku-company/id1289801633?uo=4">© Solitaire, Mahjong and Sudoku Company</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/bd/c9/3d/bdc93d70-e09e-37f0-9786-23809a473545/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38154970-4b94023a-3475-11e8-85c1-410d100d7fac.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38154970-4b94023a-3475-11e8-85c1-410d100d7fac.png)
https://user-images.githubusercontent.com/2068130/38154970-4b94023a-3475-11e8-85c1-410d100d7fac.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38154977-5a61d95e-3475-11e8-92a8-bf92c75d2ca6.png
