### ISSUE TITLE
Sudoku :)

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#2432]
**App Name:** Sudoku :)
**Bundle ID:** com.ticbits.sudoku
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398990729">398990729</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sudoku/id398990729?mt=8&uo=4">https://itunes.apple.com/us/app/sudoku/id398990729?mt=8&uo=4</a>
**App Version:** 1.7.4
**Seller:** TicBits Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ticbits-ltd/id370423113?uo=4">© TicBits Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/ca/16/17/ca1617c0-4c3e-879e-552a-9ed208fe9ca4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25574554/da0984c2-2e4f-11e7-9370-7bbd2c6d7bbb.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25574554/da0984c2-2e4f-11e7-9370-7bbd2c6d7bbb.png)
https://cloud.githubusercontent.com/assets/2068130/25574554/da0984c2-2e4f-11e7-9370-7bbd2c6d7bbb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25574564/e815a9ec-2e4f-11e7-8c99-e2c7be4d93a8.png
