### ISSUE TITLE
ByssWeather : best Weather app

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2433]
**App Name:** ByssWeather : best Weather app
**Bundle ID:** mobi.byss.temperature
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=500182129">500182129</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/byssweather-best-weather-app/id500182129?uo=4">https://apps.apple.com/us/app/byssweather-best-weather-app/id500182129?uo=4</a>
**App Version:** 5.0.5
**Seller:** BYSS mobile
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/byss-mobile/id327447624?uo=4">© byss mobile</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/3f/bb/ed/3fbbed92-7f6d-a168-fd02-986c1485f40d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83347524-de7be380-a325-11ea-952b-1560e5c97ad7.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Easy Weather with awesome Widget
**Bundle ID:** mobi.byss.temperature
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=500182129">500182129</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/easy-weather-awesome-widget/id500182129?mt=8&uo=4">https://itunes.apple.com/us/app/easy-weather-awesome-widget/id500182129?mt=8&uo=4</a>
**App Version:** 3.1.22
**Seller:** BYSS mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/byss-mobile/id327447624?uo=4>© byss mobile</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/fe/60/70/fe607091-1649-b456-cb17-b93ef73e1d67/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18690108/dbdb7d2c-7f8c-11e6-9f3c-1c1926437036.png)
https://cloud.githubusercontent.com/assets/20930745/18690108/dbdb7d2c-7f8c-11e6-9f3c-1c1926437036.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18690127/f0466024-7f8c-11e6-9ec6-ad7e3fbe05a2.png

**Comment by dreamnet** [comment]
Just some corner rounding:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18698034/17a38d1a-7fc7-11e6-9770-113fd7d530f9.png)
https://cloud.githubusercontent.com/assets/2068130/18698034/17a38d1a-7fc7-11e6-9770-113fd7d530f9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18698041/26182b3a-7fc7-11e6-9286-c6a9456e5e6b.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** ByssWeather : best Weather app
**Bundle ID:** mobi.byss.temperature
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=500182129">500182129</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/byssweather-best-weather-app/id500182129?uo=4">https://apps.apple.com/us/app/byssweather-best-weather-app/id500182129?uo=4</a>
**App Version:** 5.0.5
**Seller:** BYSS mobile
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/byss-mobile/id327447624?uo=4">© byss mobile</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/3f/bb/ed/3fbbed92-7f6d-a168-fd02-986c1485f40d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83347524-de7be380-a325-11ea-952b-1560e5c97ad7.png)
https://user-images.githubusercontent.com/2068130/83347524-de7be380-a325-11ea-952b-1560e5c97ad7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83347531-f05d8680-a325-11ea-8146-052041740afb.png
