### ISSUE TITLE
iiSitter Baby Monitor - WiFi / Bluetooth / LTE

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2435]
**App Name:** iSitter Baby Monitor - WiFi / Bluetooth / LTE
**Bundle ID:** uk.co.dorada.isitter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=439592371">439592371</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/isitter-baby-monitor-wifi/id439592371?mt=8&uo=4">https://itunes.apple.com/us/app/isitter-baby-monitor-wifi/id439592371?mt=8&uo=4</a>
**App Version:** 4.2.1
**Seller:** Dorada App Software Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dorada-app-software-ltd/id382552900?uo=4>© Dorada App Software Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/15/d3/7d/15d37d47-9eb4-21e2-0429-1175af1fd7fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625808/a0265108-9922-11e6-91d7-5fc7d60abc67.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625808/a0265108-9922-11e6-91d7-5fc7d60abc67.png)
https://cloud.githubusercontent.com/assets/20930745/19625808/a0265108-9922-11e6-91d7-5fc7d60abc67.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625814/b74bf518-9922-11e6-909e-89898446e0f6.png
