### ISSUE TITLE
Baby Monitor 3G

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2436]
**App Name:** Baby Monitor 3G
**Bundle ID:** com.tappytaps.Baby-Monitor-3G
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490077681">490077681</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/baby-monitor-3g/id490077681?mt=8&uo=4">https://itunes.apple.com/us/app/baby-monitor-3g/id490077681?mt=8&uo=4</a>
**App Version:** 4.5.7
**Seller:** TappyTaps s.r.o.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tappytaps-s.r.o./id326082490?uo=4>© TappyTaps s.r.o.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/d8/c3/d9/d8c3d9e5-8baa-dd97-9ad2-3f4fce7f5e44/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625660/0bfb1660-991f-11e6-90ad-bc5f169ca0bf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625660/0bfb1660-991f-11e6-90ad-bc5f169ca0bf.png)
https://cloud.githubusercontent.com/assets/20930745/19625660/0bfb1660-991f-11e6-90ad-bc5f169ca0bf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625667/23c57b1e-991f-11e6-8682-93fef26c028c.png
