### ISSUE TITLE
CALPOL®

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2437]
**App Name:** CALPOL®
**Bundle ID:** com.jnj.calpol
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519071291">519071291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/calpol/id519071291?mt=8&uo=4">https://itunes.apple.com/gb/app/calpol/id519071291?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** McNeil Healthcare (UK) Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/mcneil-healthcare-uk-ltd/id371065338?uo=4">© McNeil Healthcare UK Ltd</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/64/56/88/64568810-5b43-8538-f7e3-7ede1d3b8ff3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26750656/5c3c56a8-4828-11e7-9b28-75c457434566.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26750656/5c3c56a8-4828-11e7-9b28-75c457434566.png)
https://cloud.githubusercontent.com/assets/2068130/26750656/5c3c56a8-4828-11e7-9b28-75c457434566.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26750659/6c580d8e-4828-11e7-8ff9-a5de3fa25b6b.png
