### ISSUE TITLE
Mortgage Repayment Calculator

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2438]
**App Name:** Mortgage Repayment Calculator
**Bundle ID:** sublimedsoft.mort
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=397230570">397230570</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mortgage-repayment-calculator/id397230570?mt=8&uo=4">https://itunes.apple.com/us/app/mortgage-repayment-calculator/id397230570?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** James Still
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/james-still/id366872444?uo=4">© James Still</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple6/v4/7d/c8/f7/7dc8f7ff-0263-125c-21ad-1121feaa6350/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39836951-51a61f76-53d5-11e8-93bc-789018ec1dd8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39836882-23984820-53d5-11e8-8aa3-5cd7f5118713.png)
https://user-images.githubusercontent.com/20930745/39836882-23984820-53d5-11e8-8aa3-5cd7f5118713.png
