### ISSUE TITLE
LIVESTRONG MyQuit Coach - Dare to Quit Smoking

### ISSUE THREAD

**Issue by HarshTrooth** [glasklart/hd#2442]
**App Name:** LIVESTRONG MyQuit Coach - Dare to Quit Smoking
**Bundle ID:** com.demandmedia.quitcoach
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=383122255">383122255</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/livestrong-myquit-coach-dare/id383122255?mt=8&uo=4">https://itunes.apple.com/us/app/livestrong-myquit-coach-dare/id383122255?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Demand Media, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/demand-media-inc./id295305244?mt=8&uo=4>© Demand Media, Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/e7/18/51/e718517e-49a0-e610-40bc-f6f5712aa037/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625636/247ed6c8-991e-11e6-936b-32360fa2ed14.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625636/247ed6c8-991e-11e6-936b-32360fa2ed14.png)
https://cloud.githubusercontent.com/assets/20930745/19625636/247ed6c8-991e-11e6-936b-32360fa2ed14.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625638/3e0ed9bc-991e-11e6-90d7-f0f6e4198cae.png
