### ISSUE TITLE
Applauze - Concerts, Sports & Theatre Tickets

### ISSUE THREAD

**Issue by johnnyhundreds** [glasklart/hd#2444]
**App Name:** Applauze - Concerts, Sports & Theatre Tickets
**Bundle ID:** com.955dreams.ApplauzeProduction
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=608609424">608609424</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/applauze-concerts-sports-theatre/id608609424?mt=8&uo=4">https://itunes.apple.com/us/app/applauze-concerts-sports-theatre/id608609424?mt=8&uo=4</a>
**App Version:** 2.7.8
**Seller:** Amped, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/amped-inc./id411521462?uo=4>© Amped, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/30/48/9e/30489e87-fdf2-187c-2af8-9b2b812057f3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625598/2d63c592-991d-11e6-8950-1aaef50cae4e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625598/2d63c592-991d-11e6-8950-1aaef50cae4e.png)
https://cloud.githubusercontent.com/assets/20930745/19625598/2d63c592-991d-11e6-8950-1aaef50cae4e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625600/45d1730e-991d-11e6-9f72-8d8718a03159.png
