### ISSUE TITLE
Listia: Buy, Sell & Get Free Stuff on Sale Locally

### ISSUE THREAD

**Issue by johnnyhundreds** [glasklart/hd#2445]
**App Name:** Listia: Buy, Sell & Get Free Stuff on Sale Locally
**Bundle ID:** com.listia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=429870253">429870253</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/listia-buy-sell-get-free-stuff/id429870253?mt=8&uo=4">https://itunes.apple.com/us/app/listia-buy-sell-get-free-stuff/id429870253?mt=8&uo=4</a>
**App Version:** 2.38
**Seller:** Listia Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/listia-inc./id429870256?uo=4>© Listia Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/cc/2b/93/cc2b93d1-be98-ff55-13bf-8d4deabb8730/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625549/086fea6e-991c-11e6-9b4a-9a24b16c6fce.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625549/086fea6e-991c-11e6-9b4a-9a24b16c6fce.png)
https://cloud.githubusercontent.com/assets/20930745/19625549/086fea6e-991c-11e6-9b4a-9a24b16c6fce.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625550/1ec07982-991c-11e6-9889-be7ba1ae1eb8.png
