### ISSUE TITLE
Scotiabank

### ISSUE THREAD

**Issue by MagnaMike** [glasklart/hd#2446]
**App Name:** Scotiabank
**Bundle ID:** com.scotiabank.locator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=341151570">341151570</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scotiabank/id341151570?mt=8&uo=4">https://itunes.apple.com/us/app/scotiabank/id341151570?mt=8&uo=4</a>
**App Version:** 16.9.0
**Seller:** The Bank of Nova Scotia
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/scotiabank/id341151577?uo=4>© Scotiabank</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/bc/4b/cf/bc4bcfd2-c139-a4fd-2f66-3e5309031181/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19736350/2dff8006-9baf-11e6-972b-9f2b9875e240.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19736350/2dff8006-9baf-11e6-972b-9f2b9875e240.png)
https://cloud.githubusercontent.com/assets/2068130/19736350/2dff8006-9baf-11e6-972b-9f2b9875e240.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19736366/3c761d98-9baf-11e6-9ede-abdabaf2826d.png
