### ISSUE TITLE
VPN Express - Free Mobile VPN

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2449]
**App Name:** VPN Express - Free Mobile VPN
**Bundle ID:** com.bestsparks.vpnclient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375584677">375584677</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vpn-express-free-mobile-vpn/id375584677?mt=8&uo=4">https://itunes.apple.com/us/app/vpn-express-free-mobile-vpn/id375584677?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** Express Network Solutions Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/express-network-solutions-limited/id367346409?uo=4">© Express Network Solutions Limited</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/ff/1e/f3/ff1ef3fd-22d8-9bf1-f699-aee8c72b97ce/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33752879-92debaa2-dbe4-11e7-8c42-d85356dcfd32.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33752879-92debaa2-dbe4-11e7-8c42-d85356dcfd32.png)
https://user-images.githubusercontent.com/2068130/33752879-92debaa2-dbe4-11e7-8c42-d85356dcfd32.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33752896-a2b55648-dbe4-11e7-9c25-dc2fa0e8ac69.png
