### ISSUE TITLE
CSR Racing

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#245]
**App Name:** CSR Racing
**Bundle ID:** com.naturalmotion.csr4c3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469369175">469369175</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/csr-racing/id469369175?mt=8&uo=4">https://itunes.apple.com/us/app/csr-racing/id469369175?mt=8&uo=4</a>
**App Version:** 3.6.0
**Seller:** NaturalMotion Games Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/naturalmotion/id330281898?uo=4>© NaturalMotion</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/f6/c5/0b/f6c50b18-3dd5-366a-55ad-d39f34464fcd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16523968/59a9ea26-3fa6-11e6-8ee0-a2121ff29ba3.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16523968/59a9ea26-3fa6-11e6-8ee0-a2121ff29ba3.png)
https://cloud.githubusercontent.com/assets/10730122/16523968/59a9ea26-3fa6-11e6-8ee0-a2121ff29ba3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16523969/59aa809e-3fa6-11e6-8e4b-ab98d3c49044.png
