### ISSUE TITLE
Champion Architect - Builds for League of Legends

### ISSUE THREAD

**Issue by CherryLax** [glasklart/hd#2451]
**App Name:** Champion Architect - Builds for League of Legends
**Bundle ID:** com.gravitycoreapps.Architect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=564937128">564937128</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/champion-architect-builds/id564937128?mt=8&uo=4">https://itunes.apple.com/us/app/champion-architect-builds/id564937128?mt=8&uo=4</a>
**App Version:** 1.8.4
**Seller:** Grant Davis
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/grant-davis/id564937171?uo=4>© Grant Davis</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/04/b4/53/04b4534e-306c-6937-3668-e0f23c62982d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625347/4eef861c-9916-11e6-9d08-444e8031597d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625347/4eef861c-9916-11e6-9d08-444e8031597d.png)
https://cloud.githubusercontent.com/assets/20930745/19625347/4eef861c-9916-11e6-9d08-444e8031597d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625351/67da6750-9916-11e6-93f9-c54fd7570712.png
