### ISSUE TITLE
Stealth Sound Grenade

### ISSUE THREAD

**Issue by CherryLax** [glasklart/hd#2452]
**App Name:** Stealth Sound Grenade
**Bundle ID:** com.highgloss.TimesTables
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=317063171">317063171</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stealth-sound-grenade/id317063171?mt=8&uo=4">https://itunes.apple.com/us/app/stealth-sound-grenade/id317063171?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Reuben Bijl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/high-gloss/id301565170?uo=4>© High Gloss</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/8c/14/98/8c149863-b32b-6630-e6b8-01f5cd53695d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19229390/72d5be00-8ecd-11e6-8c15-de0c7540bb8a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19229390/72d5be00-8ecd-11e6-8c15-de0c7540bb8a.png)
https://cloud.githubusercontent.com/assets/20930745/19229390/72d5be00-8ecd-11e6-8c15-de0c7540bb8a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19229417/a48b56da-8ecd-11e6-8a60-a60a81ffb0b9.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19229545/a3b0f89a-8ece-11e6-8bff-4adf8f4659fc.png)
https://cloud.githubusercontent.com/assets/20930745/19229545/a3b0f89a-8ece-11e6-8bff-4adf8f4659fc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19229560/c31375e6-8ece-11e6-9c77-b0d091ca659e.png
