### ISSUE TITLE
Signal Generator: Audio Test Tone Utility

### ISSUE THREAD

**Issue by CherryLax** [glasklart/hd#2453]
**App Name:** Signal Generator: Audio Test Tone Utility
**Bundle ID:** net.mpunk.signal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=543661843">543661843</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/signal-generator-audio-test/id543661843?mt=8&uo=4">https://itunes.apple.com/us/app/signal-generator-audio-test/id543661843?mt=8&uo=4</a>
**App Version:** 1.7.3
**Seller:** Media Punk Studios LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/media-punk-studios/id432317871?uo=4">© Media Punk Studios</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/59/84/6e/59846eda-15d4-0f91-bf8d-de8c6cb82f63/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030309/b6e7c01c-a362-11e6-9285-a39aadd2ab45.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030309/b6e7c01c-a362-11e6-9285-a39aadd2ab45.png)
https://cloud.githubusercontent.com/assets/20930745/20030309/b6e7c01c-a362-11e6-9285-a39aadd2ab45.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20030313/cb35a75a-a362-11e6-8d8c-01cc6280b290.png
