### ISSUE TITLE
Dream Team - be your own fantasy football manager

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2459]
**App Name:** Dream Team - be your own fantasy football manager
**Bundle ID:** com.nidigitalsolutions.dreamteam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=337710261">337710261</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dream-team-be-your-own-fantasy/id337710261?mt=8&uo=4">https://itunes.apple.com/us/app/dream-team-be-your-own-fantasy/id337710261?mt=8&uo=4</a>
**App Version:** 12.3
**Seller:** News UK & Ireland Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/news-uk-ireland-limited/id319496075?mt=8&uo=4">© News UK & Ireland Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/aa/f9/66/aaf9661d-547b-ed8f-9cdb-0d7045d7adf9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030463/cf8d9486-a365-11e6-9966-64c611a052b4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030463/cf8d9486-a365-11e6-9966-64c611a052b4.png)
https://cloud.githubusercontent.com/assets/20930745/20030463/cf8d9486-a365-11e6-9966-64c611a052b4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20030469/e3da7e22-a365-11e6-9cbf-b2d37b5b44a2.png
