### ISSUE TITLE
Translate Professional

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2465]
**App Name:** Translate Professional
**Bundle ID:** se.traduko.translatepro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=359354972">359354972</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/translate-professional/id359354972?mt=8&uo=4">https://itunes.apple.com/us/app/translate-professional/id359354972?mt=8&uo=4</a>
**App Version:** 6.0.4
**Seller:** Traduko AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/traduko-ab/id306582365?uo=4>© Traduko AB</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/ca/0b/4d/ca0b4db2-e5e2-16ab-85fb-539f6e3557d8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19287398/db885298-9001-11e6-8218-e41cd9f846e4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19287398/db885298-9001-11e6-8218-e41cd9f846e4.png)
https://cloud.githubusercontent.com/assets/20930745/19287398/db885298-9001-11e6-8218-e41cd9f846e4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19287409/eb65b0b6-9001-11e6-8444-1d9656d552b8.png
