### ISSUE TITLE
Bash Reader

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#247]
**App Name:** Bash Reader
**Bundle ID:** com.websiteforge.bashreader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=297200401">297200401</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bash-reader/id297200401?mt=8&uo=4">https://itunes.apple.com/us/app/bash-reader/id297200401?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** WebsiteForge, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/websiteforge-llc/id293566269?mt=8&uo=4>© WebsiteForge, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/66/0a/58/660a58d1-73b2-ebd8-43f6-a2ea4a20f7f9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402206/166612aa-9260-11e6-9d34-e5cfd8b5fc95.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402206/166612aa-9260-11e6-9d34-e5cfd8b5fc95.png)
https://cloud.githubusercontent.com/assets/20930745/19402206/166612aa-9260-11e6-9d34-e5cfd8b5fc95.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19402218/254403b8-9260-11e6-9a4b-a76c319a981a.png
