### ISSUE TITLE
I Hear Ewe - Animal Sounds for Toddlers

### ISSUE THREAD

**Issue by yakintosh** [glasklart/hd#2471]
**App Name:** I Hear Ewe - Animal Sounds for Toddlers
**Bundle ID:** com.claireware.ihearewe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=304093970">304093970</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/i-hear-ewe-animal-sounds-for/id304093970?mt=8&uo=4">https://itunes.apple.com/us/app/i-hear-ewe-animal-sounds-for/id304093970?mt=8&uo=4</a>
**App Version:** 1.7.4
**Seller:** Michael Kamprath
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/claireware-software/id298640015?uo=4">© Claireware Software</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/69/c6/e4/69c6e487-d8cd-0ca7-1290-b4717ea46643/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20038578/6298a9c0-a436-11e6-89e2-cda7065ae510.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20038578/6298a9c0-a436-11e6-89e2-cda7065ae510.png)
https://cloud.githubusercontent.com/assets/20930745/20038578/6298a9c0-a436-11e6-89e2-cda7065ae510.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20038590/af0e3a22-a436-11e6-8588-c42c1b60d39e.png
