### ISSUE TITLE
Tozzle - Toddler's favorite puzzle

### ISSUE THREAD

**Issue by yakintosh** [glasklart/hd#2473]
**App Name:** Tozzle - Toddler's favorite puzzle
**Bundle ID:** com.nodeflexion.Tozzle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306169895">306169895</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tozzle-toddlers-favorite-puzzle/id306169895?mt=8&uo=4">https://itunes.apple.com/us/app/tozzle-toddlers-favorite-puzzle/id306169895?mt=8&uo=4</a>
**App Version:** 5.0.1
**Seller:** Benjamin Riegler
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nodeflexion.com/id290609910?uo=4>© nodeflexion.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/61/96/5d/61965d3a-8db0-48e5-e916-00f0bdac24b5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19625164/47f84b6e-9911-11e6-8e8d-7b434a92486f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19625164/47f84b6e-9911-11e6-8e8d-7b434a92486f.png)
https://cloud.githubusercontent.com/assets/2068130/19625164/47f84b6e-9911-11e6-8e8d-7b434a92486f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19625167/55ac8c20-9911-11e6-9f7b-8a6e072c4583.png
