### ISSUE TITLE
Pro Pool 2015

### ISSUE THREAD

**Issue by iPOSEiDON** [glasklart/hd#2477]
**App Name:** Pro Pool 2015
**Bundle ID:** com.iwaredesigns.propool2012
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=556429076">556429076</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pro-pool-2015/id556429076?mt=8&uo=4">https://itunes.apple.com/us/app/pro-pool-2015/id556429076?mt=8&uo=4</a>
**App Version:** 1.11
**Seller:** iWare Designs Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iware-designs-ltd./id443800612?uo=4>© iWare Designs Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple18/v4/22/a5/fc/22a5fcac-42c0-e21c-e2f7-d569611d68b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19629217/e5478ade-996f-11e6-97db-9b527918fb43.png)

**Comment by Checkit23** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19187144/19e6feac-8c8a-11e6-9154-97f2dca9490b.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19187834/24cd0196-8c8e-11e6-9dae-7332d2702af2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19188074/a5a90872-8c8f-11e6-887f-93d175f4e451.png)
https://cloud.githubusercontent.com/assets/20930745/19188074/a5a90872-8c8f-11e6-887f-93d175f4e451.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19188084/b7b7d1c4-8c8f-11e6-9344-f640236141f8.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... i have tried your method ... i think it is the best way to create icons which are very realistic

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19629217/e5478ade-996f-11e6-97db-9b527918fb43.png)
https://cloud.githubusercontent.com/assets/2068130/19629217/e5478ade-996f-11e6-97db-9b527918fb43.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19629221/f5f4f934-996f-11e6-990a-75017f4bbe29.png
