### ISSUE TITLE
Peers.TV

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#248]
**App Name:** Peers.TV
**Bundle ID:** ru.inetra.cn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540754699">540754699</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/peers-tv/id540754699?mt=8&uo=4">https://itunes.apple.com/us/app/peers-tv/id540754699?mt=8&uo=4</a>
**App Version:** 3.8.6
**Seller:** Limited Liability Company Inetra
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inetra/id540754702?uo=4">© Inetra</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/40/de/92/40de9270-6246-7166-9954-4d761c04a2e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634077-7efac988-199f-11e8-9c1b-3b0f3e90c1a0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634077-7efac988-199f-11e8-9c1b-3b0f3e90c1a0.png)
https://user-images.githubusercontent.com/20930745/36634077-7efac988-199f-11e8-9c1b-3b0f3e90c1a0.png

Source:
https://user-images.githubusercontent.com/20930745/36634079-9743f316-199f-11e8-9187-83a9f552d922.png
