### ISSUE TITLE
ArcherCat

### ISSUE THREAD

**Issue by deadpool18** [glasklart/hd#2482]
**App Name:** ArcherCat
**Bundle ID:** net.cravemob.arrowandbird
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=524019484">524019484</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/archercat/id524019484?mt=8&uo=4">https://itunes.apple.com/us/app/archercat/id524019484?mt=8&uo=4</a>
**App Version:** 2.2.4
**Seller:** CraveMob Co.,Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cravemob-co.-ltd/id454135926?uo=4>© Cravemob Co.,Ltd</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/05/d5/08/05d508a1-9850-281d-0221-bf8712143a76/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19316507/f68474aa-90a1-11e6-895d-43f83fbd5fdf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19316507/f68474aa-90a1-11e6-895d-43f83fbd5fdf.png)
https://cloud.githubusercontent.com/assets/20930745/19316507/f68474aa-90a1-11e6-895d-43f83fbd5fdf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19316523/05c27476-90a2-11e6-892a-eec98735002d.png
