### ISSUE TITLE
Upvote - Reddit Client for iPhone

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2486]
**App Name:** Upvote - Reddit Client for iPhone
**Bundle ID:** com.nicholasleedesigns.upvote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=626595701">626595701</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/upvote-reddit-client-for-iphone/id626595701?mt=8&uo=4">https://itunes.apple.com/us/app/upvote-reddit-client-for-iphone/id626595701?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Nicholas Lee Designs, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nicholas-lee-designs-llc/id421895545?uo=4>© Nicholas Lee Designs, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/2f/bc/ea/2fbcea8b-662f-d7d1-d736-1905d34b98a2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
!![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621360/7a9f8392-9890-11e6-8498-91d42d0f8fe7.png)

**Comment by 2Qt2beStr8** [comment]
!![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621360/7a9f8392-9890-11e6-8498-91d42d0f8fe7.png)
https://cloud.githubusercontent.com/assets/20930745/19621360/7a9f8392-9890-11e6-8498-91d42d0f8fe7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19621363/93118c5e-9890-11e6-9ce7-adc3e7424d37.png
