### ISSUE TITLE
Dot Line

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2488]
**App Name:** Dot Line
**Bundle ID:** com.sharpapp.dotline
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=485538133">485538133</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dot-line/id485538133?mt=8&uo=4">https://itunes.apple.com/us/app/dot-line/id485538133?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** SharpApp
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/app/id377755013?uo=4">© #App</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/94/ac/3e/94ac3e92-b8cd-d786-9e29-dabde4408132/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25583778/9f2f3bfa-2e93-11e7-87ca-e452d3868d8a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25583778/9f2f3bfa-2e93-11e7-87ca-e452d3868d8a.png)
https://cloud.githubusercontent.com/assets/2068130/25583778/9f2f3bfa-2e93-11e7-87ca-e452d3868d8a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25583790/aebe9f34-2e93-11e7-9310-bcbf0359800b.png
