### ISSUE TITLE
Slingshot Racing

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#249]
**App Name:** Slingshot Racing
**Bundle ID:** com.crescentmoongames.slingshotracing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=516349924">516349924</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slingshot-racing/id516349924?mt=8&uo=4">https://itunes.apple.com/us/app/slingshot-racing/id516349924?mt=8&uo=4</a>
**App Version:** 1.3.2.0
**Seller:** Crescent Moon Games LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/crescent-moon-games/id370521012?uo=4">© Crescent Moon Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/54/20/7c/54207c90-365e-014a-9cca-1720317438aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563108/a6de400a-ce7e-11e6-9c9a-a1c19e74b4c6.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/20419471/3dcd465c-ad1c-11e6-8439-d7b2fc561b60.png)
https://cloud.githubusercontent.com/assets/3090247/20419471/3dcd465c-ad1c-11e6-8439-d7b2fc561b60.png
Source:
https://cloud.githubusercontent.com/assets/3090247/20419470/3dca2f58-ad1c-11e6-9e29-c5286de1660f.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563108/a6de400a-ce7e-11e6-9c9a-a1c19e74b4c6.png)
https://cloud.githubusercontent.com/assets/2068130/21563108/a6de400a-ce7e-11e6-9c9a-a1c19e74b4c6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21563114/b5b7a4a4-ce7e-11e6-8370-e8bf455b1f06.png
