### ISSUE TITLE
Runtastic Sit Ups – Workouts + Trainer

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2492]
**App Name:** Runtastic Sit Ups – Workouts + Trainer
**Bundle ID:** com.runtastic.iphone.situp.lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570183110">570183110</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-sit-ups-workouts/id570183110?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-sit-ups-workouts/id570183110?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPadFourthGen4G, iPodTouchFifthGen, iPhone5, iPadThirdGen, iPadMini4G, iPhone6Plus, iPad23G, iPadMini, iPhone6, iPhone5s, iPadThirdGen4G, iPhone4, iPadFourthGen, iPhone5c, iPhone4S, iPad2Wifi
**Original Artwork:**
<img src="http://a1914.phobos.apple.com/us/r30/Purple3/v4/43/a4/37/43a43775-5982-77eb-f7a4-067d19e7cc78/mzl.kexesukf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202739/0e28fae2-b4fb-11e4-9139-a78970c51124.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202739/0e28fae2-b4fb-11e4-9139-a78970c51124.png)
https://cloud.githubusercontent.com/assets/2068130/6202739/0e28fae2-b4fb-11e4-9139-a78970c51124.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6202742/1c567536-b4fb-11e4-8f14-4df90dd7f9e6.png
