### ISSUE TITLE
Runtastic Sit Ups PRO – Workouts + Trainer

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2493]
**App Name:** Runtastic Sit Ups PRO – Workouts + Trainer
**Bundle ID:** com.runtastic.iphone.situp.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570183057">570183057</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-sit-ups-pro-workouts/id570183057?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-sit-ups-pro-workouts/id570183057?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPhone5c, iPad23G, iPadFourthGen, iPhone6Plus, iPhone5s, iPhone5, iPadFourthGen4G, iPhone4S, iPadThirdGen4G, iPadMini, iPhone4, iPad2Wifi, iPadThirdGen, iPodTouchFifthGen, iPadMini4G, iPhone6
**Original Artwork:**
<img src="http://a1411.phobos.apple.com/us/r30/Purple3/v4/9e/7c/47/9e7c476b-b5b3-9c43-99e0-4b06a1b1b2bd/mzl.oeeylath.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202757/a18f1d0c-b4fb-11e4-9b55-939a04cd3e48.png)

**Comment by kieman** [comment]
is it possible to change the icon to the Pro Version? :)

Greez

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202757/a18f1d0c-b4fb-11e4-9b55-939a04cd3e48.png)
https://cloud.githubusercontent.com/assets/2068130/6202757/a18f1d0c-b4fb-11e4-9b55-939a04cd3e48.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6202761/af0dab9c-b4fb-11e4-80ed-8f12fd16fdb7.png

**Comment by ivanov007** [comment]
@kieman @dreamnet it's really needed the ´pro´ logo? you really have installed both paid and free version? normally you have installed just one at a time so I think the pro version should be the same as the free version

**Comment by kieman** [comment]
the problem, the runtastic running and mountainbiking app already has the "pro" in the icon and i feel its better all have the same style. maybe you shoud kill in these 2 icons kill the pro and all icons should be clean?

**Comment by dreamnet** [comment]
@ivanov007 @kieman I think the 'PRO' is not really needed, but it's also OK if we add it. You can get an overview of all the runtastic apps we have in the theme by going to my website and search for `Runtastic`.
