### ISSUE TITLE
Beyond Ynth

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2494]
**App Name:** Beyond Ynth
**Bundle ID:** com.FDGMobileGamesGbR.Beyond-Ynth
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386303262">386303262</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beyond-ynth/id386303262?mt=8&uo=4">https://itunes.apple.com/us/app/beyond-ynth/id386303262?mt=8&uo=4</a>
**App Version:** 1.9.1
**Seller:** FDG Mobile Games GbR
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fdg-mobile-games-gbr/id302980375?uo=4">© FDG Mobile Games GbR</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple82/v4/fa/7f/7b/fa7f7bd1-8acb-7a65-8f10-226f6fb045e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25584712/6683ed7e-2e97-11e7-805f-b8aa275cdf66.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25584712/6683ed7e-2e97-11e7-805f-b8aa275cdf66.png)
https://cloud.githubusercontent.com/assets/2068130/25584712/6683ed7e-2e97-11e7-805f-b8aa275cdf66.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25584722/75e2a0f8-2e97-11e7-8880-de0cc7110c2e.png
