### ISSUE TITLE
Hypotheticals

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2495]
**App Name:** Hypotheticals
**Bundle ID:** com.dfloyd.hypotheticals
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=472097242">472097242</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hypotheticals/id472097242?mt=8&uo=4">https://itunes.apple.com/us/app/hypotheticals/id472097242?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** Daniel Floyd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/daniel-floyd/id337998487?uo=4">© Daniel Floyd</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/de/92/5d/de925d3c-3814-59a0-90df-15e83e01286e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25584362/f7bb1332-2e95-11e7-9d94-bf0dc0c67f87.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25584362/f7bb1332-2e95-11e7-9d94-bf0dc0c67f87.png)
https://cloud.githubusercontent.com/assets/2068130/25584362/f7bb1332-2e95-11e7-9d94-bf0dc0c67f87.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25584377/073bad4e-2e96-11e7-82a6-0be221bc20aa.png
