### ISSUE TITLE
PAC-MAN Championship Edition

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2499]
**App Name:** PAC-MAN Championship Edition
**Bundle ID:** com.namconetworks.pacmance
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=326133287">326133287</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pac-man-championship-edition/id326133287?mt=8&uo=4">https://itunes.apple.com/us/app/pac-man-championship-edition/id326133287?mt=8&uo=4</a>
**App Version:** 1.2.3
**Seller:** BANDAI NAMCO Entertainment America Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bandai-namco-entertainment/id281656478?mt=8&uo=4">© BANDAI NAMCO Entertainment America Inc.</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/45/e6/b2/45e6b240-e270-83d3-9666-43dee124e5b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22989288/99619eac-f3b5-11e6-8f0b-a2f448418e7f.png)

**Comment by MenaceInc** [comment]
Doesn't work on 5.42, ios 9.3.3

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22989288/99619eac-f3b5-11e6-8f0b-a2f448418e7f.png)
https://cloud.githubusercontent.com/assets/2068130/22989288/99619eac-f3b5-11e6-8f0b-a2f448418e7f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22989305/a8e3e65a-f3b5-11e6-809d-1460fa35eb96.png
