### ISSUE TITLE
ATracker - Daily Task and Time Tracking Lite

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2500]
**App Name:** ATracker - Daily Task and Time Tracking Lite
**Bundle ID:** com.Jian.ATrackerLite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=522008611">522008611</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/atracker-daily-task-time-tracking/id522008611?mt=8&uo=4">https://itunes.apple.com/us/app/atracker-daily-task-time-tracking/id522008611?mt=8&uo=4</a>
**App Version:** 8.61
**Seller:** WonderApps AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wonderapps-ab/id519561369?uo=4">© WonderApps AB</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple19/v4/cb/1a/ab/cb1aabd7-67a8-e12e-b5c1-ae047d7bcb90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20038819/4225a036-a43a-11e6-9d7e-2021e959caf7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20038819/4225a036-a43a-11e6-9d7e-2021e959caf7.png)
https://cloud.githubusercontent.com/assets/20930745/20038819/4225a036-a43a-11e6-9d7e-2021e959caf7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20038826/5ef34fba-a43a-11e6-9c26-0e01cd6213a8.png
