### ISSUE TITLE
The Straits Times STOMP

### ISSUE THREAD

**Issue by ualnibor** [glasklart/hd#2502]
**App Name:** The Straits Times STOMP
**Bundle ID:** com.sph.stomp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=354084847">354084847</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-straits-times-stomp/id354084847?mt=8&uo=4">https://itunes.apple.com/us/app/the-straits-times-stomp/id354084847?mt=8&uo=4</a>
**App Version:** 3.11
**Seller:** Singapore Press Holdings
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/singapore-press-holdings/id301065360?uo=4>© Singapore Press Holdings</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/f1/7a/a0/f17aa042-d808-2f16-2a72-b7862b8cf58e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621110/1b0bd7f0-988b-11e6-9bc3-95c40e34ab26.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621110/1b0bd7f0-988b-11e6-9bc3-95c40e34ab26.png)
https://cloud.githubusercontent.com/assets/20930745/19621110/1b0bd7f0-988b-11e6-9bc3-95c40e34ab26.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19621116/3b60de60-988b-11e6-9267-8554e848b24e.png
