### ISSUE TITLE
Telia Tirsdag

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#2505]
**App Name:** Telia Tirsdag
**Bundle ID:** dk.telia.teliafilm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=436311409">436311409</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/telia-tirsdag/id436311409?mt=8&uo=4">https://itunes.apple.com/us/app/telia-tirsdag/id436311409?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Telia Danmark
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/telia-danmark/id436311412?uo=4">© Telia Danmark</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/56/e9/2a/56e92aeb-1370-3d3d-6723-dd194880239a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20038880/538db484-a43b-11e6-8f00-b5d31b1091c4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20038880/538db484-a43b-11e6-8f00-b5d31b1091c4.png)
https://cloud.githubusercontent.com/assets/20930745/20038880/538db484-a43b-11e6-8f00-b5d31b1091c4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20038888/6f78ab90-a43b-11e6-82d9-428279bf0376.png
