### ISSUE TITLE
SCRABBLE

### ISSUE THREAD

**Issue by Tizmaster** [glasklart/hd#251]
**App Name:** SCRABBLE
**Bundle ID:** com.ea.scrabble
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284815117">284815117</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scrabble/id284815117?mt=8&uo=4">https://itunes.apple.com/us/app/scrabble/id284815117?mt=8&uo=4</a>
**App Version:** 5.13.0
**Seller:** Electronic Arts Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4>© Electronic Arts</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/a8/9a/7a/a89a7aec-0fde-f681-96da-0b0c7c61a9ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18761655/1f794d46-8106-11e6-82c7-e915e3b5bbab.png)

**Comment by Sly-Fi** [comment]
This icon is missing from 5.0.0. release

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18740808/f0f1f662-80ab-11e6-84bb-c387364d74c6.png)
https://cloud.githubusercontent.com/assets/20930745/18740808/f0f1f662-80ab-11e6-84bb-c387364d74c6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18740825/087a32fe-80ac-11e6-9383-e6d226ca7bbb.png

**Comment by ivanov007** [comment]
it looks good :+1: but can you make a version without the EA logo to see witch one looks better?

**Comment by 2Qt2beStr8** [comment]
yes i can :-)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18761655/1f794d46-8106-11e6-82c7-e915e3b5bbab.png)
https://cloud.githubusercontent.com/assets/20930745/18761655/1f794d46-8106-11e6-82c7-e915e3b5bbab.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18761671/332bcdbe-8106-11e6-9a06-1a9f0bda7cf2.png

**Comment by ivanov007** [comment]
there you go, as I guessed it looks better :+1:
