### ISSUE TITLE
Viaplay

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#2510]
**App Name:** Viaplay
**Bundle ID:** se.harbourfront.viasatondemand
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409702778">409702778</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/viaplay/id409702778?mt=8&uo=4">https://itunes.apple.com/se/app/viaplay/id409702778?mt=8&uo=4</a>
**App Version:** 4.10
**Seller:** Viaplay AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/developer/viaplay/id720156431?uo=4>© Viaplay</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/e3/87/7a/e3877aaa-f540-dec1-e8aa-8075ac2feb50/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18617976/c1195bdc-7ddc-11e6-984d-1b35d091a45d.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8582651/81b04612-25c8-11e5-8f04-057a586c36bb.png)
https://cloud.githubusercontent.com/assets/10730122/8582651/81b04612-25c8-11e5-8f04-057a586c36bb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8582648/7e5a8ce8-25c8-11e5-8e70-ac304ec4199a.png

**Comment by Trubbel** [comment]
Using same as #8009,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18617976/c1195bdc-7ddc-11e6-984d-1b35d091a45d.png)
https://cloud.githubusercontent.com/assets/10730122/18617976/c1195bdc-7ddc-11e6-984d-1b35d091a45d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18617975/c101aaf0-7ddc-11e6-8d3d-390775fe0345.png

**Comment by dreamnet** [comment]
Already in the master, but i'm updating it.
