### ISSUE TITLE
Runtastic Pull Ups PRO – Workouts + Trainer

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#2511]
**App Name:** Runtastic Pull Ups PRO – Workouts + Trainer
**Bundle ID:** com.runtastic.iphone.pullup.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570181507">570181507</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-pull-ups-pro-workouts/id570181507?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-pull-ups-pro-workouts/id570181507?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPhone4, iPadThirdGen, iPhone5c, iPhone6Plus, iPhone5s, iPadThirdGen4G, iPhone4S, iPhone6, iPadMini4G, iPadFourthGen4G, iPhone5, iPodTouchFifthGen, iPadMini, iPadFourthGen, iPad2Wifi, iPad23G
**Original Artwork:**
<img src="http://a1048.phobos.apple.com/us/r30/Purple5/v4/35/5e/bb/355ebb5b-45d4-7632-1014-24a64249db40/mzl.rlblmwpq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202713/04b6c1f2-b4fa-11e4-8d0c-5e6aaeeec923.png)

**Comment by kieman** [comment]
is it possible to change the icon to the Pro Version? :)

Greez

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202713/04b6c1f2-b4fa-11e4-8d0c-5e6aaeeec923.png)
https://cloud.githubusercontent.com/assets/2068130/6202713/04b6c1f2-b4fa-11e4-8d0c-5e6aaeeec923.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6202715/13f1bdf2-b4fa-11e4-83d6-55f647fedbe2.png
