### ISSUE TITLE
Runtastic Push Ups PRO – Workouts + Trainer

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#2512]
**App Name:** Runtastic Push Ups PRO – Workouts + Trainer
**Bundle ID:** com.runtastic.iphone.pushup.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570180361">570180361</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-push-ups-pro-workouts/id570180361?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-push-ups-pro-workouts/id570180361?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPodTouchFifthGen, iPadFourthGen4G, iPadThirdGen4G, iPhone5, iPhone4, iPad2Wifi, iPadThirdGen, iPadMini4G, iPhone4S, iPhone6Plus, iPhone6, iPhone5c, iPad23G, iPhone5s, iPadFourthGen, iPadMini
**Original Artwork:**
<img src="http://a793.phobos.apple.com/us/r30/Purple1/v4/79/69/95/79699516-b6ab-6774-abe3-b44d070ddca1/mzl.jqafqfow.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202672/9fefd2e6-b4f8-11e4-9cf5-86e1f5a8bb49.png)

**Comment by kieman** [comment]
is it possible to change the icon to the Pro Version? :)

Greez

**Comment by dreamnet** [comment]
@kieman Yes, it is.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202672/9fefd2e6-b4f8-11e4-9cf5-86e1f5a8bb49.png)
https://cloud.githubusercontent.com/assets/2068130/6202672/9fefd2e6-b4f8-11e4-9cf5-86e1f5a8bb49.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6202675/aea1530a-b4f8-11e4-8a6a-64223c89ee6e.png

**Comment by kieman** [comment]
THX :)))))

**Comment by dreamnet** [comment]
@kieman No problem! :wink:
