### ISSUE TITLE
Runtastic Squats PRO – Workouts + Trainer

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#2513]
**App Name:** Runtastic Squats PRO – Workouts + Trainer
**Bundle ID:** com.runtastic.iphone.squats.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570182662">570182662</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-squats-pro-workouts/id570182662?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-squats-pro-workouts/id570182662?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPhone6, iPhone4, iPadMini4G, iPadMini, iPodTouchFifthGen, iPhone5s, iPad23G, iPhone4S, iPadFourthGen4G, iPad2Wifi, iPhone5c, iPadThirdGen4G, iPhone5, iPhone6Plus, iPadThirdGen, iPadFourthGen
**Original Artwork:**
<img src="http://a504.phobos.apple.com/us/r30/Purple1/v4/dd/8c/25/dd8c257d-d138-0e9e-1b22-485eaaae05e0/mzl.pkpqkrsp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202787/43099ac6-b4fd-11e4-9458-0194059ed1ab.png)

**Comment by kieman** [comment]
is it possible to change the icon to the Pro Version? :)

Greez

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202787/43099ac6-b4fd-11e4-9458-0194059ed1ab.png)
https://cloud.githubusercontent.com/assets/2068130/6202787/43099ac6-b4fd-11e4-9458-0194059ed1ab.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6202789/4fbc0cae-b4fd-11e4-83f3-01d2967af344.png
