### ISSUE TITLE
4iiii

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2515]
**App Name:** 4iiii
**Bundle ID:** com.4iiii.configurator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=600704389">600704389</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/4iiii/id600704389?mt=8&uo=4">https://itunes.apple.com/us/app/4iiii/id600704389?mt=8&uo=4</a>
**App Version:** 1.22.0
**Seller:** 4iiii Innovations Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/4iiii-innovations-inc./id600704392?uo=4>© 4iiii Innovations Inc.</a>
**Supported Devices:** iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/d0/af/d6/d0afd636-6c47-fc31-ddd8-95412f6b0ad5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621250/0ff33950-988e-11e6-8428-908200361184.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621250/0ff33950-988e-11e6-8428-908200361184.png)
https://cloud.githubusercontent.com/assets/20930745/19621250/0ff33950-988e-11e6-8428-908200361184.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19621253/25b7a5fa-988e-11e6-9476-9f3bb8c22f2e.png
