### ISSUE TITLE
Ski Deals

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2519]
**App Name:** Ski Deals
**Bundle ID:** com.iglu.search.ski
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405505694">405505694</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/ski-deals/id405505694?mt=8&uo=4">https://itunes.apple.com/gb/app/ski-deals/id405505694?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Iglu.com Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/iglu.com/id405505700?uo=4>© Iglu.com</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/79/eb/fe/79ebfe28-f4bd-b31a-5eb4-c959422a4165/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621209/32f39d2e-988d-11e6-87a3-ed546b2e5df8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621209/32f39d2e-988d-11e6-87a3-ed546b2e5df8.png)
https://cloud.githubusercontent.com/assets/20930745/19621209/32f39d2e-988d-11e6-87a3-ed546b2e5df8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19621217/4a013364-988d-11e6-80f5-85259e40715f.png
