### ISSUE TITLE
Cardiograph Classic

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2522]
**App Name:** Cardiograph Classic
**Bundle ID:** com.macropinch.cardiograph
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441079429">441079429</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cardiograph-classic/id441079429?mt=8&uo=4">https://itunes.apple.com/us/app/cardiograph-classic/id441079429?mt=8&uo=4</a>
**App Version:** 2.9.8
**Seller:** MacroPinch ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/macropinch-ltd/id441079432?uo=4">© MacroPinch Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/00/96/d9/0096d91a-b990-9223-1929-6d2425c2d1ed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33768490-865a2c0c-dc26-11e7-9ca1-0e974ffefe0e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33768490-865a2c0c-dc26-11e7-9ca1-0e974ffefe0e.png)
https://user-images.githubusercontent.com/2068130/33768490-865a2c0c-dc26-11e7-9ca1-0e974ffefe0e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33768504-95e75c1c-dc26-11e7-9ff1-da93318b25fb.png
