### ISSUE TITLE
Calculator ∞

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2523]
**App Name:** Calculator ∞
**Bundle ID:** com.incpt.mobis.CalculatorInfinite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=458535809">458535809</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calculator/id458535809?mt=8&uo=4">https://itunes.apple.com/us/app/calculator/id458535809?mt=8&uo=4</a>
**App Version:** 4.8
**Seller:** An Truong
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/incpt-mobis/id445261166?uo=4">© Incpt.Mobis</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/78/04/98/780498e4-a85e-eeef-2b1f-b7f8376222a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39862439-1bf066ce-5444-11e8-9aaf-c4fcd1a47339.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39862439-1bf066ce-5444-11e8-9aaf-c4fcd1a47339.png)
https://user-images.githubusercontent.com/2068130/39862439-1bf066ce-5444-11e8-9aaf-c4fcd1a47339.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39862457-2a2aef98-5444-11e8-82b6-e62408658cd9.png
