### ISSUE TITLE
Draw Rider

### ISSUE THREAD

**Issue by trevormeiss** [glasklart/hd#2524]
**App Name:** Draw Rider
**Bundle ID:** com.Studio17.drawrider
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=629065073">629065073</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/draw-rider/id629065073?mt=8&uo=4">https://itunes.apple.com/us/app/draw-rider/id629065073?mt=8&uo=4</a>
**App Version:** 6.3
**Seller:** Anton Vazhinsky
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/anton-vazhinsky/id629059034?uo=4>© Anton Vazhinsky</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/bd/e6/bf/bde6bf16-18fa-6ab2-7570-83ec403b0bbe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18898410/ce5e83b0-8531-11e6-897b-eb17de9a7088.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18911273/67946cd0-857c-11e6-98fc-28393e486620.png)
https://cloud.githubusercontent.com/assets/20930745/18911273/67946cd0-857c-11e6-98fc-28393e486620.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18911286/8accdeb2-857c-11e6-8b55-2bb683303293.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18911772/403f99fe-857f-11e6-88c0-84e83990de11.png)
https://cloud.githubusercontent.com/assets/20930745/18911772/403f99fe-857f-11e6-88c0-84e83990de11.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18911790/52cc3e56-857f-11e6-9a1f-6d550e3034a7.png

**Comment by BrokenCommander** [comment]
Whoops, didn't saw that you already made it. Anyway, here's my try:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18898409/ce4d0888-8531-11e6-9720-6e458d13f82b.png)
https://cloud.githubusercontent.com/assets/22012363/18898409/ce4d0888-8531-11e6-9720-6e458d13f82b.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18898401/c95a19ba-8531-11e6-970e-7e2a23039597.png

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18898410/ce5e83b0-8531-11e6-897b-eb17de9a7088.png)
https://cloud.githubusercontent.com/assets/22012363/18898410/ce5e83b0-8531-11e6-897b-eb17de9a7088.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18898408/ce32d274-8531-11e6-9a21-68b2d58ef1dc.png

**Comment by dreamnet** [comment]
Hard to decide... I think I'm taking the last one from @BrokenCommander.
@2Qt2beStr8 & @BrokenCommander Good work! 👍
