### ISSUE TITLE
YouPlayer - Video Player for YouTube

### ISSUE THREAD

**Issue by ianspryn** [glasklart/hd#2526]
**App Name:** YouPlayer - Video Player for YouTube
**Bundle ID:** com.homegrownsw.YT-Player
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561921453">561921453</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/youplayer-video-player-for/id561921453?mt=8&uo=4">https://itunes.apple.com/us/app/youplayer-video-player-for/id561921453?mt=8&uo=4</a>
**App Version:** 1.7.2
**Seller:** Homegrown Software Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/homegrown-software-ltd/id406645730?uo=4>© Homegrown Software Ltd</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/42/68/1f/42681f7b-3568-bafc-8aea-fe4a281e2775/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19108271/6f9dcfce-8af0-11e6-80bd-2e9071b20698.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19108271/6f9dcfce-8af0-11e6-80bd-2e9071b20698.png)
https://cloud.githubusercontent.com/assets/2068130/19108271/6f9dcfce-8af0-11e6-80bd-2e9071b20698.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19108287/7d90325c-8af0-11e6-8efc-06b882374cda.png
