### ISSUE TITLE
Blackboard Collaborate™ Mobile

### ISSUE THREAD

**Issue by ianspryn** [glasklart/hd#2527]
**App Name:** Blackboard Collaborate™ Mobile
**Bundle ID:** com.bbcollaborate.Collaborate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=546742528">546742528</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/blackboard-collaborate-mobile/id546742528?uo=4">https://apps.apple.com/us/app/blackboard-collaborate-mobile/id546742528?uo=4</a>
**App Version:** 1.2.5
**Seller:** Blackboard Collaborate, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/blackboard-collaborate-inc/id546743031?uo=4">© Blackboard Collaborate Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/db/01/5d/db015d69-958b-05c1-5247-ee5543ce6c8a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981518-db9c4d00-9604-11e9-9284-5805406ab12a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20038981/db5f09a2-a43c-11e6-97bb-11545b68faaa.png)
https://cloud.githubusercontent.com/assets/20930745/20038981/db5f09a2-a43c-11e6-97bb-11545b68faaa.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20038985/f7a95f04-a43c-11e6-94c5-32c486453546.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981518-db9c4d00-9604-11e9-9284-5805406ab12a.png)
https://user-images.githubusercontent.com/2068130/59981518-db9c4d00-9604-11e9-9284-5805406ab12a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59981526-ea82ff80-9604-11e9-9605-8c924ff46183.png
