### ISSUE TITLE
Garfield Daily

### ISSUE THREAD

**Issue by ianspryn** [glasklart/hd#2529]
**App Name:** Garfield Daily
**Bundle ID:** com.pawsinc.garfielddailyplus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405320958">405320958</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/garfield-daily/id405320958?mt=8&uo=4">https://itunes.apple.com/us/app/garfield-daily/id405320958?mt=8&uo=4</a>
**App Version:** 1.0.11
**Seller:** Paws Incorporated
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/paws-incorporated/id369161718?uo=4">© Paws Incorporated</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/7f/58/b5/7f58b5e0-2afe-75bc-22fb-6c00f15c0627/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25074343/f5463936-22f8-11e7-9b77-b0e48af55a7e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25074343/f5463936-22f8-11e7-9b77-b0e48af55a7e.png)
https://cloud.githubusercontent.com/assets/2068130/25074343/f5463936-22f8-11e7-9b77-b0e48af55a7e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25074347/092a8448-22f9-11e7-95d7-22ee20eab189.png
