### ISSUE TITLE
Planets

### ISSUE THREAD

**Issue by ianspryn** [glasklart/hd#2531]
**App Name:** Planets
**Bundle ID:** org.qcontinuum.planets
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=305793334">305793334</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/planets/id305793334?mt=8&uo=4">https://itunes.apple.com/us/app/planets/id305793334?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Dana Peters
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/q-continuum/id305793337?uo=4">© Q Continuum</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple6/v4/ed/89/bd/ed89bd48-e2ed-eaa8-6fa1-f5d6a2b0a57e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39778371-640b59e4-5306-11e8-846e-3544e809151d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39778371-640b59e4-5306-11e8-846e-3544e809151d.png)
https://user-images.githubusercontent.com/2068130/39778371-640b59e4-5306-11e8-846e-3544e809151d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39778390-72010a1c-5306-11e8-9686-a0cc26514111.png
