### ISSUE TITLE
Bible.is - Dramatized Audio Bibles

### ISSUE THREAD

**Issue by ianspryn** [glasklart/hd#2532]
**App Name:** Bible.is - Dramatized Audio Bibles
**Bundle ID:** com.fcbh.bibleis
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378075859">378075859</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bible.is-dramatized-audio/id378075859?mt=8&uo=4">https://itunes.apple.com/us/app/bible.is-dramatized-audio/id378075859?mt=8&uo=4</a>
**App Version:** 2.9.8
**Seller:** Faith Comes By Hearing
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/faith-comes-by-hearing/id378075862?uo=4>© Faith Comes by Hearing</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/98/a9/d1/98a9d1ed-eff3-cdc9-0e77-919b314e3d91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621153/f92067c2-988b-11e6-83c1-2130dc3beba1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19621153/f92067c2-988b-11e6-83c1-2130dc3beba1.png)
https://cloud.githubusercontent.com/assets/20930745/19621153/f92067c2-988b-11e6-83c1-2130dc3beba1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19621156/0fb06712-988c-11e6-96cf-733c2c02f35e.png
