### ISSUE TITLE
Jesus Calling Devotional

### ISSUE THREAD

**Issue by ianspryn** [glasklart/hd#2533]
**App Name:** Jesus Calling Devotional
**Bundle ID:** com.thomasnelson.jesuscalling
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444553118">444553118</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jesus-calling-devotional/id444553118?mt=8&uo=4">https://itunes.apple.com/us/app/jesus-calling-devotional/id444553118?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** HarperCollins Christian Publishing, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/harpercollins-christian-publishing-inc/id444535393?uo=4">© HarperCollins Christian Publishing, Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/90/b0/ea/90b0ea7e-439c-f367-aa80-130eb2614074/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39782548-cf5a504a-5312-11e8-972e-ecda098f50d7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39782548-cf5a504a-5312-11e8-972e-ecda098f50d7.png)
https://user-images.githubusercontent.com/2068130/39782548-cf5a504a-5312-11e8-972e-ecda098f50d7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39782582-de300bfa-5312-11e8-9886-758c5eed1b54.png
