### ISSUE TITLE
The Room Pocket

### ISSUE THREAD

**Issue by Firebirdflame** [glasklart/hd#2537]
**App Name:** The Room Pocket
**Bundle ID:** com.FireproofStudios.TheRoomiPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=573156739">573156739</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-room-pocket/id573156739?mt=8&uo=4">https://itunes.apple.com/us/app/the-room-pocket/id573156739?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Fireproof Studios Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fireproof-games/id552039499?uo=4>© Fireproof Games</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/51/ad/ea/51adeaa6-7161-53ad-f1c0-06a1cd298866/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12138333/5f047df8-b458-11e5-8f9e-aaa0edea045e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12138333/5f047df8-b458-11e5-8f9e-aaa0edea045e.png)
https://cloud.githubusercontent.com/assets/2068130/12138333/5f047df8-b458-11e5-8f9e-aaa0edea045e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12138344/70f759d6-b458-11e5-89db-9c8f0fcf8ab2.png
