### ISSUE TITLE
Where's My Water? Lite

### ISSUE THREAD

**Issue by ianspryn** [glasklart/hd#2538]
**App Name:** Where's My Water? Lite
**Bundle ID:** com.disney.SwampyGameLite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467810884">467810884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wheres-my-water-lite/id467810884?mt=8&uo=4">https://itunes.apple.com/us/app/wheres-my-water-lite/id467810884?mt=8&uo=4</a>
**App Version:** 1.9.4
**Seller:** Disney Electronic Content, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/disney/id284888248?mt=8&uo=4">© Disney</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/f0/5a/26/f05a26ed-fa0b-f78e-2a50-54f76b81b90c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26751046/bcb08506-4830-11e7-9422-a3a62a924170.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26751046/bcb08506-4830-11e7-9422-a3a62a924170.png)
https://cloud.githubusercontent.com/assets/2068130/26751046/bcb08506-4830-11e7-9422-a3a62a924170.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26751049/ca79be32-4830-11e7-8a1f-68e56a72c329.png
