### ISSUE TITLE
CommBank

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#254]
**App Name:** CommBank
**Bundle ID:** au.com.commbank.commbank
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=310251202">310251202</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/commbank/id310251202?mt=8&uo=4">https://itunes.apple.com/us/app/commbank/id310251202?mt=8&uo=4</a>
**App Version:** 3.15.1
**Seller:** Commonwealth Bank of Australia
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/commonwealth-bank-australia/id310251205?uo=4>© Commonwealth Bank of Australia</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/3d/e3/cd/3de3cd06-d557-8c19-7e77-50db6013945b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809095/5b8ee150-8274-11e6-8e4a-2f51e2515300.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809095/5b8ee150-8274-11e6-8e4a-2f51e2515300.png)
https://cloud.githubusercontent.com/assets/20930745/18809095/5b8ee150-8274-11e6-8e4a-2f51e2515300.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18809097/6acdfaa2-8274-11e6-9db2-6c5b6bb73743.png
