### ISSUE TITLE
Leafsnap

### ISSUE THREAD

**Issue by ianspryn** [glasklart/hd#2540]
**App Name:** Leafsnap
**Bundle ID:** com.leafsnap.leafsnap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=430649829">430649829</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/leafsnap/id430649829?mt=8&uo=4">https://itunes.apple.com/us/app/leafsnap/id430649829?mt=8&uo=4</a>
**App Version:** 1.07
**Seller:** Peter Belhumeur
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/columbia-university-university/id430649832?uo=4>© Columbia University, University of Maryland, and Smithsonian Institution</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/c3/33/f0/c333f016-a145-9c26-3927-2832a9c80d57/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19314464/80bc42e0-909a-11e6-823f-3447a47fe1d0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19314464/80bc42e0-909a-11e6-823f-3447a47fe1d0.png)
https://cloud.githubusercontent.com/assets/20930745/19314464/80bc42e0-909a-11e6-823f-3447a47fe1d0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19314487/933d3bd6-909a-11e6-953b-515c1dfa29fd.png
