### ISSUE TITLE
AccuWeather - Weather for Life

### ISSUE THREAD

**Issue by Firebirdflame** [glasklart/hd#2543]
**App Name:** AccuWeather - Weather for Life
**Bundle ID:** com.yourcompany.TestWithCustomTabs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300048137">300048137</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/accuweather-weather-for-life/id300048137?mt=8&uo=4">https://itunes.apple.com/us/app/accuweather-weather-for-life/id300048137?mt=8&uo=4</a>
**App Version:** 9.5.2
**Seller:** AccuWeather International, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/accuweather-international/id300048140?uo=4>© AccuWeather International, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/41/3f/8f/413f8f7c-6f0d-381b-f712-79f7e39ab0dc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18247793/8e80062a-7342-11e6-9859-3c6610545a2f.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** AccuWeather - Weather for Life
**Bundle ID:** com.yourcompany.TestWithCustomTabs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300048137">300048137</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/accuweather-weather-for-life/id300048137?mt=8&uo=4">https://itunes.apple.com/us/app/accuweather-weather-for-life/id300048137?mt=8&uo=4</a>
**App Version:** 9.5.2
**Seller:** AccuWeather International, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/accuweather-international/id300048140?uo=4>© AccuWeather International, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/41/3f/8f/413f8f7c-6f0d-381b-f712-79f7e39ab0dc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18247793/8e80062a-7342-11e6-9859-3c6610545a2f.png)

https://cloud.githubusercontent.com/assets/3704186/18247793/8e80062a-7342-11e6-9859-3c6610545a2f.png)

https://cloud.githubusercontent.com/assets/3704186/18247797/969e0618-7342-11e6-9562-e9ed757efe3a.png
