### ISSUE TITLE
Yahoo Weather

### ISSUE THREAD

**Issue by sddevstudio** [glasklart/hd#2555]
**App Name:** Yahoo Weather
**Bundle ID:** com.yahoo.weather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=628677149">628677149</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahoo-weather/id628677149?mt=8&uo=4">https://itunes.apple.com/us/app/yahoo-weather/id628677149?mt=8&uo=4</a>
**App Version:** 1.9.0
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4>© Yahoo</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/5d/d7/21/5dd72101-e8cf-b900-9303-6418969f242a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12551163/c390a386-c368-11e5-85d6-822e70a12bcb.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12551163/c390a386-c368-11e5-85d6-822e70a12bcb.png)
https://cloud.githubusercontent.com/assets/10730122/12551163/c390a386-c368-11e5-85d6-822e70a12bcb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12551164/c392f2b2-c368-11e5-8267-8403b5997e23.png
