### ISSUE TITLE
TouchPad

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#256]
**App Name:** TouchPad
**Bundle ID:** com.edovia.touchpad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=297623931">297623931</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touchpad/id297623931?mt=8&uo=4">https://itunes.apple.com/us/app/touchpad/id297623931?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** MartianCraft LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/martiancraft/id734171052?uo=4>© MartianCraft</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/d2/9c/85/d29c8540-82c9-d350-d709-f5e30079174f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402318/d7bda6d4-9260-11e6-9223-93ed69cff845.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402318/d7bda6d4-9260-11e6-9223-93ed69cff845.png)
https://cloud.githubusercontent.com/assets/20930745/19402318/d7bda6d4-9260-11e6-9223-93ed69cff845.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19402328/e8d6c6e4-9260-11e6-9dd9-82da5d622540.png
