### ISSUE TITLE
Cut the Rope: Time Travel

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#2567]
**App Name:** Cut the Rope: Time Travel
**Bundle ID:** com.zeptolab.timetravel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=608899141">608899141</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cut-the-rope-time-travel/id608899141?mt=8&uo=4">https://itunes.apple.com/us/app/cut-the-rope-time-travel/id608899141?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** ZeptoLab UK Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zeptolab-uk-limited/id450542236?uo=4>© ZeptoLab UK Limited</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/73/1c/19/731c1908-cfff-a3dd-b4f9-68623e0f304b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085912/c1d6ab52-51e4-11e6-87d5-0fe23a533e54.png)

**Comment by Anuskuss** [comment]
Needs update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085912/c1d6ab52-51e4-11e6-87d5-0fe23a533e54.png)
https://cloud.githubusercontent.com/assets/2068130/17085912/c1d6ab52-51e4-11e6-87d5-0fe23a533e54.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17085915/d55e33d4-51e4-11e6-8b49-0b001a4cdd59.png
