### ISSUE TITLE
ffgolf

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#257]
**App Name:** ffgolf
**Bundle ID:** org.ffgolf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406495505">406495505</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ffgolf/id406495505?mt=8&uo=4">https://itunes.apple.com/us/app/ffgolf/id406495505?mt=8&uo=4</a>
**App Version:** 2.7.0
**Seller:** ffgolf
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ffgolf/id406495508?uo=4>© ffgolf</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/1a/e8/76/1ae87689-730a-9333-e515-2dd16867e76d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19242543/f12fb0a8-8f13-11e6-85ad-494b9d30e1dc.png)

**Comment by 2Qt2beStr8** [comment]
... i have used a better artwork (Logo) from the www

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19242543/f12fb0a8-8f13-11e6-85ad-494b9d30e1dc.png)
https://cloud.githubusercontent.com/assets/20930745/19242543/f12fb0a8-8f13-11e6-85ad-494b9d30e1dc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19242559/0038e2cc-8f14-11e6-8ba1-d652da20859e.png
