### ISSUE TITLE
Pizza Vs. Skeletons

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#2572]
**App Name:** Pizza Vs. Skeletons
**Bundle ID:** com.paulstevens.pizzavsskeletons
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=475212472">475212472</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pizza-vs-skeletons/id475212472?mt=8&uo=4">https://itunes.apple.com/us/app/pizza-vs-skeletons/id475212472?mt=8&uo=4</a>
**App Version:** 1.8.0
**Seller:** Riverman Media LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/riverman-media-llc/id396772114?uo=4">© Riverman Media LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/5f/3d/79/5f3d7982-fa65-2818-3dec-20db307ee39d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38150319-a4aa1f92-345e-11e8-82e7-4f4e34428c1c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38150319-a4aa1f92-345e-11e8-82e7-4f4e34428c1c.png)
https://user-images.githubusercontent.com/2068130/38150319-a4aa1f92-345e-11e8-82e7-4f4e34428c1c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38150333-b3f684b8-345e-11e8-8d23-9f60cddc3dcb.png
