### ISSUE TITLE
Glassdoor Job Search: Jobs, Salaries & Reviews

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#2573]
**App Name:** Glassdoor Job Search: Jobs, Salaries & Reviews
**Bundle ID:** com.glassdoor.glassdoor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589698942">589698942</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glassdoor-job-search-jobs-salaries-reviews/id589698942?mt=8&uo=4">https://itunes.apple.com/us/app/glassdoor-job-search-jobs-salaries-reviews/id589698942?mt=8&uo=4</a>
**App Version:** 5.0.2
**Seller:** Glassdoor, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/glassdoor/id528708125?uo=4">© Glassdoor</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/4d/f3/bf/4df3bf92-7c38-5088-1335-0a7dd56772b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25746081/1d9e4eac-31a2-11e7-8e36-26c128366539.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** Glassdoor Job Search: Jobs, Salaries & Reviews
**Bundle ID:** com.glassdoor.glassdoor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589698942">589698942</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glassdoor-job-search-jobs/id589698942?mt=8&uo=4">https://itunes.apple.com/us/app/glassdoor-job-search-jobs/id589698942?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** Glassdoor, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/glassdoor/id528708125?uo=4>© Glassdoor</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple42/v4/f2/8b/5a/f28b5a1d-a72e-fa79-deca-264fe434983f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18192484/fe7711a0-70d4-11e6-97bc-2106c6635d2f.png)
https://cloud.githubusercontent.com/assets/2068130/18192484/fe7711a0-70d4-11e6-97bc-2106c6635d2f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18192490/0cf6a204-70d5-11e6-8aaa-c457104e2bd8.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Glassdoor Job Search: Jobs, Salaries & Reviews
**Bundle ID:** com.glassdoor.glassdoor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589698942">589698942</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glassdoor-job-search-jobs-salaries-reviews/id589698942?mt=8&uo=4">https://itunes.apple.com/us/app/glassdoor-job-search-jobs-salaries-reviews/id589698942?mt=8&uo=4</a>
**App Version:** 5.0.2
**Seller:** Glassdoor, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/glassdoor/id528708125?uo=4">© Glassdoor</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/4d/f3/bf/4df3bf92-7c38-5088-1335-0a7dd56772b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25746081/1d9e4eac-31a2-11e7-8e36-26c128366539.png)
https://cloud.githubusercontent.com/assets/20930745/25746081/1d9e4eac-31a2-11e7-8e36-26c128366539.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25746102/31fc86e8-31a2-11e7-8e16-57bc8a0efdcb.png
