### ISSUE TITLE
SmartPlayer - Music Player and Scrobbler for Last.fm

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2576]
**App Name:** SmartPlayer - Music Player and Scrobbler for Last.fm
**Bundle ID:** com.shaddeen.SmartPlayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492333520">492333520</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartplayer-music-player-scrobbler/id492333520?mt=8&uo=4">https://itunes.apple.com/us/app/smartplayer-music-player-scrobbler/id492333520?mt=8&uo=4</a>
**App Version:** 4.1.7
**Seller:** Shad DEEN
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/shad-deen/id492333523?uo=4">© Shad Deen</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/7c/10/0e/7c100e94-6398-86a4-3667-3af4910f49f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039038/ce8242a2-a43d-11e6-962a-f94ea5cded7d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039038/ce8242a2-a43d-11e6-962a-f94ea5cded7d.png)
https://cloud.githubusercontent.com/assets/20930745/20039038/ce8242a2-a43d-11e6-962a-f94ea5cded7d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20039043/e5c78774-a43d-11e6-9910-dcf665f1d7b9.png
