### ISSUE TITLE
PetFetch

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2579]
**App Name:** PetFetch
**Bundle ID:** com.blinkloop.pet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=590313331">590313331</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/petfetch/id590313331?mt=8&uo=4">https://itunes.apple.com/us/app/petfetch/id590313331?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** Michael Peterson
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/michael-peterson/id293068574?uo=4>© Michael Peterson</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/83/f1/e2/83f1e21e-c9bf-66d8-8fba-748c9fb9cf11/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620999/d529f804-9888-11e6-9757-b200dfa20e58.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620999/d529f804-9888-11e6-9757-b200dfa20e58.png)
https://cloud.githubusercontent.com/assets/20930745/19620999/d529f804-9888-11e6-9757-b200dfa20e58.png

https://cloud.githubusercontent.com/assets/20930745/19621001/fd38f64c-9888-11e6-9279-bd0a241c6893.png
