### ISSUE TITLE
French dictionary DIXEL Mobile

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#258]
**App Name:** French dictionary DIXEL Mobile
**Bundle ID:** com.rainero.DicoMalin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324277188">324277188</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/french-dictionary-dixel-mobile/id324277188?mt=8&uo=4">https://itunes.apple.com/us/app/french-dictionary-dixel-mobile/id324277188?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** Roger Rainero
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/diagonal/id324277191?uo=4">© Diagonal</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/a6/55/57/a6555745-b99e-c1ad-7383-279bf0c874b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634191-f89790cc-19a0-11e8-9c8a-b47cfcb856b9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634191-f89790cc-19a0-11e8-9c8a-b47cfcb856b9.png)
https://user-images.githubusercontent.com/20930745/36634191-f89790cc-19a0-11e8-9c8a-b47cfcb856b9.png

Source:
https://user-images.githubusercontent.com/20930745/36634193-10910596-19a1-11e8-8fe7-c1a187ab4763.png
