### ISSUE TITLE
League of Evil

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2582]
**App Name:** League of Evil
**Bundle ID:** com.ravenousgames.leagueofevil
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405552598">405552598</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/league-of-evil/id405552598?mt=8&uo=4">https://itunes.apple.com/us/app/league-of-evil/id405552598?mt=8&uo=4</a>
**App Version:** 1.60
**Seller:** Ravenous Games Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ravenous-games-inc./id344310480?uo=4">© Ravenous Games Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/a5/4c/eb/a54cebf0-6b5d-41f1-78c2-671135e9313a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21817968/5406ca0a-d766-11e6-859b-444fad666da5.png)

**Comment by MenaceInc** [comment]
Doesn't work in 5.42 on 9.3.3

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21817816/cc6e45c8-d765-11e6-8438-f7b8ac4c8c3f.png)
https://cloud.githubusercontent.com/assets/20930745/21817816/cc6e45c8-d765-11e6-8438-f7b8ac4c8c3f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21817851/f26c31f4-d765-11e6-9b2b-11d3fa1bdfbc.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21817968/5406ca0a-d766-11e6-859b-444fad666da5.png)
https://cloud.githubusercontent.com/assets/20930745/21817968/5406ca0a-d766-11e6-859b-444fad666da5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21817978/5f194f30-d766-11e6-8f96-d58744b8368e.png
