### ISSUE TITLE
Red Clock - The Minimal Alarm Clock

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2583]
**App Name:** Red Clock - The Minimal Alarm Clock
**Bundle ID:** net.morethan.Red-Clock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=473001837">473001837</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/red-clock-minimal-alarm-clock/id473001837?mt=8&uo=4">https://itunes.apple.com/us/app/red-clock-minimal-alarm-clock/id473001837?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** KYU TAE PARK
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/morethan-apps/id473001840?uo=4>© morethan Apps</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/17/43/2f/17432f0c-3471-07a0-78c6-06bb407b702b/mzl.otcckclh.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10864616/3c37ed98-7ff4-11e5-862c-b904cf4f437b.png)

**Comment by l8er4now** [comment]
This bad boy has been updated.

**App Name:** Red Clock - The Minimal Alarm Clock
**Bundle ID:** net.morethan.Red-Clock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=473001837">473001837</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/red-clock-minimal-alarm-clock/id473001837?mt=8&uo=4">https://itunes.apple.com/us/app/red-clock-minimal-alarm-clock/id473001837?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** KYU TAE PARK
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/morethan-apps/id473001840?uo=4>© morethan Apps</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/17/43/2f/17432f0c-3471-07a0-78c6-06bb407b702b/mzl.otcckclh.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10864616/3c37ed98-7ff4-11e5-862c-b904cf4f437b.png)
https://cloud.githubusercontent.com/assets/2068130/10864616/3c37ed98-7ff4-11e5-862c-b904cf4f437b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10864618/4dfc924a-7ff4-11e5-8df1-02bd609ce280.png
