### ISSUE TITLE
RONA

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2588]
**App Name:** RONA
**Bundle ID:** ca.rona.storelocator1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407834180">407834180</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/rona/id407834180?mt=8&uo=4">https://itunes.apple.com/ca/app/rona/id407834180?mt=8&uo=4</a>
**App Version:** 4.0.5
**Seller:** RONA Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/developer/rona-inc./id407619882?uo=4>© RONA Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/5f/7d/28/5f7d28c8-bb2e-096b-1b46-0dde7f02b0e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18925089/c30f3910-85b2-11e6-8d7b-8172f847055e.png)

**Comment by LaCh0uine** [comment]
Don't work on 5.0 need update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18925089/c30f3910-85b2-11e6-8d7b-8172f847055e.png)
https://cloud.githubusercontent.com/assets/20930745/18925089/c30f3910-85b2-11e6-8d7b-8172f847055e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18925102/d3df74d0-85b2-11e6-8db6-bc614168be63.png
