### ISSUE TITLE
The Home Depot Canada

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2590]
**App Name:** The Home Depot Canada
**Bundle ID:** ca.thehomedepot.homedepotCanada
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391916059">391916059</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/the-home-depot-canada/id391916059?mt=8&uo=4">https://itunes.apple.com/ca/app/the-home-depot-canada/id391916059?mt=8&uo=4</a>
**App Version:** 5.5
**Seller:** The Home Depot, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/ca/developer/the-home-depot-inc./id342527642?uo=4">© The Home Depot, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/f2/b3/4d/f2b34db0-defe-b9ac-9cc4-c85376df6f2f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040596/701bd4ae-a45a-11e6-9741-06e8aa6f57ae.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040596/701bd4ae-a45a-11e6-9741-06e8aa6f57ae.png)
https://cloud.githubusercontent.com/assets/20930745/20040596/701bd4ae-a45a-11e6-9741-06e8aa6f57ae.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20040602/8b3b12e0-a45a-11e6-9fc9-7997ec5b4200.png
