### ISSUE TITLE
I'd Cap That® 2 With Animated GIF Camera

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2591]
**App Name:** I'd Cap That® 2 With Animated GIF Camera
**Bundle ID:** com.iddiction.ict2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=578337829">578337829</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/id-cap-that-2-with-animated-gif-camera/id578337829?mt=8&uo=4">https://itunes.apple.com/us/app/id-cap-that-2-with-animated-gif-camera/id578337829?mt=8&uo=4</a>
**App Version:** 1.5.4
**Seller:** Iddiction, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/iddiction/id492105100?uo=4">© Iddiction</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/9d/a3/4d/9da34d55-52de-2d8f-9afd-de78f877e873/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25585488/0bbd3b30-2e9b-11e7-9b9b-c37399cadcfd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25585488/0bbd3b30-2e9b-11e7-9b9b-c37399cadcfd.png)
https://cloud.githubusercontent.com/assets/2068130/25585488/0bbd3b30-2e9b-11e7-9b9b-c37399cadcfd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25585495/1a29a1fe-2e9b-11e7-9f55-6f926b659071.png
