### ISSUE TITLE
TeamViewer Pro for Remote Control

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2595]
**App Name:** TeamViewer Pro for Remote Control
**Bundle ID:** com.teamviewer.teamviewerpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=357051966">357051966</a>
**iPhone Icon Name:** Icon@2x.png
**Icon Names:** Icon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/teamviewer-pro-for-remote/id357051966?mt=8&uo=4
**App Version:** 8.0.10095
**Seller:** TeamViewer GmbH
**Supported Devices:** all
**Original Artwork:**
<img src="http://a952.phobos.apple.com/us/r1000/119/Purple/v4/c6/0c/46/c60c4654-ca79-8266-a15c-9ffd8f7d290e/mzl.bfsnfyva.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://f.cloud.github.com/assets/3090247/405982/0c0a06e6-aa37-11e2-8c1d-43c163e4ccc0.png)

**Comment by PolarisBeaver** [comment]
Icon needs to be updated again.

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6072526/96129464-ad57-11e4-962a-36f19ca38403.png)
https://cloud.githubusercontent.com/assets/10394552/6072526/96129464-ad57-11e4-962a-36f19ca38403.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6072523/8da4c6a8-ad57-11e4-95c2-8ee24f99c8ec.png

**Comment by PolarisBeaver** [comment]
Actually come to think of it, the "pro" version doesn't even exist anymore in the App Store... should this be removed?

**Comment by ivanov007** [comment]
@PolarisBeaver it doesnt exist any more on the app store but if you bought it you can use it so the icon have not changed since there's no actualization for this app what you are posting is a new app and needs a new request, you can check it on the itunes ID :smile:

**Comment by dreamnet** [comment]
@PolarisBeaver @ivanov007 I think nobody uses the old versions of this app anymore. I remove the icon.
