### ISSUE TITLE
Fat Birds Build a Bridge!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2599]
**App Name:** Fat Birds Build a Bridge!
**Bundle ID:** com.estelion.FatBirds
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=468639171">468639171</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fat-birds-build-a-bridge/id468639171?mt=8&uo=4">https://itunes.apple.com/us/app/fat-birds-build-a-bridge/id468639171?mt=8&uo=4</a>
**App Version:** 1.2.6
**Seller:** Przemyslaw Perkowski
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/przemyslaw-perkowski/id566320619?uo=4">© Przemyslaw Perkowski</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/cf/49/ff/cf49fffb-41c7-61f4-3bdb-fe2a0dcdafc8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38197227-903e4fc6-3687-11e8-87f5-a68f28c9e48d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38197227-903e4fc6-3687-11e8-87f5-a68f28c9e48d.png)
https://user-images.githubusercontent.com/2068130/38197227-903e4fc6-3687-11e8-87f5-a68f28c9e48d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38197244-9ee1434e-3687-11e8-84ec-af20eba502e7.png
