### ISSUE TITLE
Estafeta móvil

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2600]
**App Name:** Estafeta móvil
**Bundle ID:** com.estafeta.estafetamovil
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586035594">586035594</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/estafeta-m%C3%B3vil/id586035594?mt=8&uo=4">https://itunes.apple.com/us/app/estafeta-m%C3%B3vil/id586035594?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Estafeta Mexicana S.A. de C.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/estafeta/id586035597?uo=4">© Estafeta</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/71/0f/eb/710febdc-bd95-e16e-8e04-9189954e9328/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25575164/fd8e463a-2e54-11e7-9dcb-5e9ab26de68f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25575164/fd8e463a-2e54-11e7-9dcb-5e9ab26de68f.png)
https://cloud.githubusercontent.com/assets/2068130/25575164/fd8e463a-2e54-11e7-9dcb-5e9ab26de68f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25575170/0ad09cb2-2e55-11e7-98df-606944542a62.png
