### ISSUE TITLE
Las tablas de multiplicar lite

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2601]
**App Name:** Las tablas de multiplicar lite
**Bundle ID:** MultiplicationSpanishlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478370303">478370303</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/las-tablas-multiplicar-lite/id478370303?mt=8&uo=4">https://itunes.apple.com/us/app/las-tablas-multiplicar-lite/id478370303?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** rana nir
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rana-nir/id456155882?uo=4">© rana nir</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/c3/ce/80/c3ce8018-8299-8118-5391-420a60a30724/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039284/875d1ea2-a441-11e6-862d-874891e01663.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039284/875d1ea2-a441-11e6-862d-874891e01663.png)
https://cloud.githubusercontent.com/assets/20930745/20039284/875d1ea2-a441-11e6-862d-874891e01663.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20039290/9c61b920-a441-11e6-9674-e9c77e984967.png
