### ISSUE TITLE
Rise Alarm Clock

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2602]
**App Name:** Rise Alarm Clock
**Bundle ID:** com.kellenstyler.rise
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=577221529">577221529</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rise-alarm-clock/id577221529?mt=8&uo=4">https://itunes.apple.com/us/app/rise-alarm-clock/id577221529?mt=8&uo=4</a>
**App Version:** 5.3
**Seller:** Kellen Styler
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kellen-styler/id442165163?uo=4">© Kellen Styler</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple19/v4/5f/c9/6e/5fc96ec2-9aad-ea99-cad6-4c45bffc554c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039368/e385af0e-a442-11e6-882d-f0533d7e1288.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039368/e385af0e-a442-11e6-882d-f0533d7e1288.png)
https://cloud.githubusercontent.com/assets/20930745/20039368/e385af0e-a442-11e6-882d-f0533d7e1288.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20039373/fa0e89d0-a442-11e6-985b-fa36ea014582.png
