### ISSUE TITLE
Data Buddy

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2608]
**App Name:** Data Buddy
**Bundle ID:** com.jeremybassett.iDataMonitor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409224517">409224517</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/data-buddy/id409224517?mt=8&uo=4">https://itunes.apple.com/us/app/data-buddy/id409224517?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Jeremy Bassett
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jeremy-bassett/id335962740?uo=4">© Jeremy Bassett</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/94/02/52/940252af-ea03-f487-6767-01ef1f341c30/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039198/52361f86-a440-11e6-8c1e-f0b9da90542a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039198/52361f86-a440-11e6-8c1e-f0b9da90542a.png)
https://cloud.githubusercontent.com/assets/20930745/20039198/52361f86-a440-11e6-8c1e-f0b9da90542a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20039202/6ad22db4-a440-11e6-8140-7baad73a3865.png
