### ISSUE TITLE
ON/OFF

### ISSUE THREAD

**Issue by tanmaster** [glasklart/hd#2613]
**App Name:** ON/OFF
**Bundle ID:** com.nuagetouch.onoff
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=574723132">574723132</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/on-off/id574723132?mt=8&uo=4">https://itunes.apple.com/us/app/on-off/id574723132?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** 1Button SARL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/1button-sarl/id388888785?uo=4>© 1Button SARL</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/e2/59/9b/e2599b21-49d9-8c3e-bc73-c890b0dc608d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19223211/9d1044a0-8e6a-11e6-8bce-a64155353d8e.png)

**Comment by LaCh0uine** [comment]
@dreamnet Need updated for -large method

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19223211/9d1044a0-8e6a-11e6-8bce-a64155353d8e.png)
https://cloud.githubusercontent.com/assets/20930745/19223211/9d1044a0-8e6a-11e6-8bce-a64155353d8e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19223214/b306ff56-8e6a-11e6-9a84-30a0fd0168f5.png

**Comment by LaCh0uine** [comment]
@2Qt2beStr8 good and fast 👍🏻
