### ISSUE TITLE
minube

### ISSUE THREAD

**Issue by Poca90** [glasklart/hd#2615]
**App Name:** minube
**Bundle ID:** com.minube.appstore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=440277010">440277010</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minube/id440277010?mt=8&uo=4">https://itunes.apple.com/us/app/minube/id440277010?mt=8&uo=4</a>
**App Version:** 5.1.5
**Seller:** PRS Marketing Services SL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/minube/id375444946?uo=4>© Minube</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/11/2c/bc/112cbcd8-4798-9faf-d7d9-d6ecb99a7ad5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19624947/e923b610-990a-11e6-810f-1bedc6438810.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620776/36977d6e-9884-11e6-9fba-c883ff35678e.png)
https://cloud.githubusercontent.com/assets/20930745/19620776/36977d6e-9884-11e6-9fba-c883ff35678e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19620796/7a38b056-9884-11e6-8ac1-d5443b45f57e.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620859/ddf8e664-9885-11e6-8c5d-a13a18543b37.png)
https://cloud.githubusercontent.com/assets/20930745/19620859/ddf8e664-9885-11e6-8c5d-a13a18543b37.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19620861/e9e93302-9885-11e6-8637-31e3c92dc210.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19624947/e923b610-990a-11e6-810f-1bedc6438810.png)
https://cloud.githubusercontent.com/assets/20930745/19624947/e923b610-990a-11e6-810f-1bedc6438810.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19624949/f5b393b4-990a-11e6-84f6-c3fc385ae41f.png
