### ISSUE TITLE
The Great Wines of Bordeaux

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#262]
**App Name:** The Great Wines of Bordeaux
**Bundle ID:** jp.co.wspace.MedocWines
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=323034147">323034147</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-great-wines-of-bordeaux/id323034147?mt=8&uo=4">https://itunes.apple.com/us/app/the-great-wines-of-bordeaux/id323034147?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** WineSpace inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/winespace-inc/id322320166?uo=4">© WineSpace inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple/v4/f6/42/8a/f6428afc-4cee-df17-9cb1-247e31a51ec4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41507042-498db498-722a-11e8-9eef-81f74b8fef93.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41507042-498db498-722a-11e8-9eef-81f74b8fef93.png)
https://user-images.githubusercontent.com/2068130/41507042-498db498-722a-11e8-9eef-81f74b8fef93.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41507047-5765b4ee-722a-11e8-87cf-382f48642993.png
