### ISSUE TITLE
+1

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2620]
**App Name:** +1
**Bundle ID:** com.nuagetouch.plus1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=605426487">605426487</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/+1/id605426487?mt=8&uo=4">https://itunes.apple.com/us/app/+1/id605426487?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** 1Button SARL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/1button-sarl/id388888785?uo=4>© 1Button SARL</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/eb/4d/32/eb4d32a4-c061-89b9-14c6-e1eb243f1f82/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18924581/ff71bf1a-85b0-11e6-8cbd-51a6c460e169.png)

**Comment by LaCh0uine** [comment]
Don't work on 5.0 need update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18924581/ff71bf1a-85b0-11e6-8cbd-51a6c460e169.png)
https://cloud.githubusercontent.com/assets/20930745/18924581/ff71bf1a-85b0-11e6-8cbd-51a6c460e169.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18924606/11b3b598-85b1-11e6-8f54-d3bbe91904cb.png
