### ISSUE TITLE
Futureshop

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2621]
**App Name:** Future Shop
**Bundle ID:** com.bestbuy.FutureShop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386973913">386973913</a>
**iPhone Icon Name:** Icon@2x.png
**Icon Names:** Icon.png | Icon@2x.png
**iTunes URL:** https://itunes.apple.com/ca/app/future-shop/id386973913?mt=8&uo=4
**App Version:** 2.3.1
**Seller:** Future Shop
**Supported Devices:** all
**Original Artwork:**
<img src="http://a464.phobos.apple.com/us/r1000/098/Purple/v4/c5/8a/8e/c58a8e5e-8751-7939-86dc-106e0e50023d/mzl.egofxech.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://f.cloud.github.com/assets/2068130/412976/0952502e-abdc-11e2-81bb-808f34cb6143.png)

**Comment by LaCh0uine** [comment]
You can remove this icon future shop is close now ;)

**Comment by dreamnet** [comment]
Removed.
