### ISSUE TITLE
LesPAC Petites annonces locales au Québec

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2622]
**App Name:** LesPAC Petites annonces locales au Québec
**Bundle ID:** com.lespac.lespacapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=550467528">550467528</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lespac-petites-annonces-locales-au-qu%C3%A9bec/id550467528?mt=8&uo=4">https://itunes.apple.com/us/app/lespac-petites-annonces-locales-au-qu%C3%A9bec/id550467528?mt=8&uo=4</a>
**App Version:** 2.9.1
**Seller:** LesPAC.com
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lespac/id550467931?uo=4">© LesPAC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/85/e2/61/85e26141-3455-0d8d-22a4-5a8b0ce9e94f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25585320/3b6a7fb0-2e9a-11e7-9644-591687be2afd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25585320/3b6a7fb0-2e9a-11e7-9644-591687be2afd.png)
https://cloud.githubusercontent.com/assets/2068130/25585320/3b6a7fb0-2e9a-11e7-9644-591687be2afd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25585337/49558ac0-2e9a-11e7-81c1-e5b8b8b7a879.png
