### ISSUE TITLE
Aeroplan

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2623]
**App Name:** Aeroplan
**Bundle ID:** com.aeroplan.iosapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=501052434">501052434</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aeroplan/id501052434?mt=8&uo=4">https://itunes.apple.com/us/app/aeroplan/id501052434?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** Aimia Canada Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aimia-canada-inc./id501052437?uo=4>© Aimia Canada Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/98/37/c4/9837c4c0-d09d-e3a6-2063-ad781fd20e9a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620711/3f38c28a-9883-11e6-9825-945f5cc9b264.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620711/3f38c28a-9883-11e6-9825-945f5cc9b264.png)
https://cloud.githubusercontent.com/assets/20930745/19620711/3f38c28a-9883-11e6-9825-945f5cc9b264.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19620726/59cea36c-9883-11e6-8fbc-d858bd28f3c8.png
