### ISSUE TITLE
Canadian Tire Retail

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2624]
**App Name:** Canadian Tire Retail
**Bundle ID:** com.canadiantire.com.canadiantire.canadiantireapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=403884878">403884878</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/canadian-tire-retail/id403884878?mt=8&uo=4">https://itunes.apple.com/ca/app/canadian-tire-retail/id403884878?mt=8&uo=4</a>
**App Version:** 5.7.0
**Seller:** Canadian Tire Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/developer/canadian-tire-corporation/id403884882?uo=4>© Canadian Tire Corporation, Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/44/6a/07/446a07fc-4a24-57ee-cd61-92e443e2b87f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18842569/c2a7ce68-8415-11e6-862d-016fa48034de.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18842569/c2a7ce68-8415-11e6-862d-016fa48034de.png)
https://cloud.githubusercontent.com/assets/2068130/18842569/c2a7ce68-8415-11e6-862d-016fa48034de.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18842594/d13df86c-8415-11e6-8cbf-e0da6271ad79.png
