### ISSUE TITLE
Flash Reader: Reading Reimagined

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2627]
**App Name:** Flash Reader: Reading Reimagined
**Bundle ID:** .com.didstopia.flashreader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=402491178">402491178</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flash-reader-reading-reimagined/id402491178?mt=8&uo=4">https://itunes.apple.com/us/app/flash-reader-reading-reimagined/id402491178?mt=8&uo=4</a>
**App Version:** 3.2.3
**Seller:** Didstopia
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/didstopia/id379028611?uo=4>© Didstopia</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/4b/b7/58/4bb75863-4618-6d10-53ff-be15b3fb0832/mzl.vtjqzalj.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10564890/db7fff52-75c3-11e5-9aa1-e0ced5a74360.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10564890/db7fff52-75c3-11e5-9aa1-e0ced5a74360.png)
https://cloud.githubusercontent.com/assets/2068130/10564890/db7fff52-75c3-11e5-9aa1-e0ced5a74360.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10564899/ea38733a-75c3-11e5-82ee-e32c64b460d6.png
