### ISSUE TITLE
MX5 Cloud Browser - notes & passwords manager

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2628]
**App Name:** MX5 Cloud Browser - notes & passwords manager
**Bundle ID:** com.mx.MxBrowser-iPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=541052011">541052011</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mx5-cloud-browser-notes-passwords/id541052011?mt=8&uo=4">https://itunes.apple.com/us/app/mx5-cloud-browser-notes-passwords/id541052011?mt=8&uo=4</a>
**App Version:** 5.0.4
**Seller:** Maxthon Technology Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/maxthon-technology-limited/id473194919?uo=4">© Maxthon Technology Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/34/b5/16/34b5163a-7712-ebae-8d64-1bcb4d66bd39/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21041472/73874452-bdeb-11e6-8ef5-89351d89c86f.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** Maxthon Cloud Web Browser - Best Internet Explore Experience
**Bundle ID:** com.mx.MxBrowser-iPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=541052011">541052011</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/maxthon-cloud-web-browser/id541052011?mt=8&uo=4">https://itunes.apple.com/us/app/maxthon-cloud-web-browser/id541052011?mt=8&uo=4</a>
**App Version:** 4.9.0
**Seller:** Maxthon Technology Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/maxthon-technology-limited/id473194919?uo=4>© Maxthon Technology Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple30/v4/46/59/62/46596221-61f7-abc0-9ea0-8ea228efd6a8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18255100/e4af3d3c-73a5-11e6-9a35-43737b7c1a5f.png)
https://cloud.githubusercontent.com/assets/20930745/18255100/e4af3d3c-73a5-11e6-9a35-43737b7c1a5f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18255106/fb066de4-73a5-11e6-8ea3-c980d87580f4.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Well, yes, but it needs to be pushed down...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18256520/c7534c7c-73b6-11e6-92ff-b6cc182cb140.png)
https://cloud.githubusercontent.com/assets/2068130/18256520/c7534c7c-73b6-11e6-92ff-b6cc182cb140.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18256531/d51694ea-73b6-11e6-91ef-1c2598abbf0d.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** MX5 Cloud Browser - notes & passwords manager
**Bundle ID:** com.mx.MxBrowser-iPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=541052011">541052011</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/mx5-cloud-browser-notes-passwords/id541052011?mt=8&uo=4">https://itunes.apple.com/gb/app/mx5-cloud-browser-notes-passwords/id541052011?mt=8&uo=4</a>
**App Version:** 5.0.3
**Seller:** Maxthon Technology Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/maxthon-technology-limited/id473194919?uo=4">© Maxthon Technology Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/08/32/74/083274db-e4a3-5492-b5ca-2f53626bf2ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21041472/73874452-bdeb-11e6-8ef5-89351d89c86f.png)
https://cloud.githubusercontent.com/assets/2068130/21041472/73874452-bdeb-11e6-8ef5-89351d89c86f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21041480/81b2e856-bdeb-11e6-8115-e24e135e5392.png
