### ISSUE TITLE
Cheaper Vacations

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2629]
**App Name:** Cheaper Vacations
**Bundle ID:** com.voyagesarabais.var
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=563318436">563318436</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cheaper-vacations/id563318436?mt=8&uo=4">https://itunes.apple.com/us/app/cheaper-vacations/id563318436?mt=8&uo=4</a>
**App Version:** 1.5.3
**Seller:** VoyagesARabais Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/voyagesarabais-com/id563318439?uo=4">© VoyagesARabais.com</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/67/0c/2b/670c2b9b-f7e7-23bf-04e0-38a7d60f1b8c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25585167/9a70f904-2e99-11e7-9c1d-7a680dbb5538.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25585167/9a70f904-2e99-11e7-9c1d-7a680dbb5538.png)
https://cloud.githubusercontent.com/assets/2068130/25585167/9a70f904-2e99-11e7-9c1d-7a680dbb5538.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25585178/a8677de4-2e99-11e7-9d20-ddad9d93579e.png
