### ISSUE TITLE
YP Shopwise | Flyers and deals to save on groceries and shopping

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2630]
**App Name:** YP Shopwise | Flyers and deals to save on groceries and shopping
**Bundle ID:** com.ypg.shopwise
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476353338">476353338</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/yp-shopwise-flyers-deals-to-save-on-groceries-shopping/id476353338?mt=8&uo=4">https://itunes.apple.com/ca/app/yp-shopwise-flyers-deals-to-save-on-groceries-shopping/id476353338?mt=8&uo=4</a>
**App Version:** 3.6.1
**Seller:** Yellow Pages Digital & Media Solutions Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/ca/developer/yellow-pages-digital-media-solutions-limited/id310063420?uo=4">© Yellow Pages Digital & Media Solutions Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/4b/92/fd/4b92fd28-628a-fb29-419a-cb0598671490/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25586355/499e9184-2e9f-11e7-8f5d-4ecb9aee3d49.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25586355/499e9184-2e9f-11e7-8f5d-4ecb9aee3d49.png)
https://cloud.githubusercontent.com/assets/2068130/25586355/499e9184-2e9f-11e7-8f5d-4ecb9aee3d49.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25586369/5c428bce-2e9f-11e7-831e-f8940c553060.png
