### ISSUE TITLE
Fontastic - Add beautiful text to your pictures

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2632]
**App Name:** Fontastic - Add beautiful text to your pictures
**Bundle ID:** com.melonlabapps.fontastic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589320495">589320495</a>
**iPhone Icon Name:** Icon@2x.png
**Icon Names:** Icon-72.png | Icon-72@2x.png | Icon.png | Icon@2x.png | Icon-Small-50.png | Icon-Small.png | Icon-Small@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/font-astic-add-beautiful-text/id589320495?mt=8&uo=4
**App Version:** 1.7.6
**Seller:** Paul Li
**Supported Devices:** iPhone4S, iPadThirdGen4G, iPadWifi, iPodTouchThirdGen, iPadThirdGen, iPodTouchFifthGen, iPadMini, iPhone4, iPhone-3GS, iPadMini4G, iPad23G, iPad2Wifi, iPhone5, iPadFourthGen4G, iPodTouchourthGen, iPadFourthGen, iPad3G
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60393799-542a6e80-9b1b-11e9-90ca-c4825ece00a8.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393804-63112100-9b1b-11e9-964f-a3abf490b824.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393804-63112100-9b1b-11e9-964f-a3abf490b824.png)
https://user-images.githubusercontent.com/2068130/60393804-63112100-9b1b-11e9-964f-a3abf490b824.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60393806-71f7d380-9b1b-11e9-9324-10c343d7854b.png
