### ISSUE TITLE
FunBox - Instants of fun

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#2633]
**App Name:** FunBox - Instants of fun
**Bundle ID:** com.ktssc.FunBox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368043740">368043740</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/funbox-instants-of-fun/id368043740?mt=8&uo=4">https://itunes.apple.com/us/app/funbox-instants-of-fun/id368043740?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Antonio Cabezuelo Vivo
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/taps-and-swipes/id300548459?uo=4">© Taps and Swipes</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple2/v4/e9/66/3b/e9663bfd-12d5-2eeb-cd96-8cfa0220bbee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25585621/cb722634-2e9b-11e7-97b2-b3c7f85d3a3f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25585621/cb722634-2e9b-11e7-97b2-b3c7f85d3a3f.png)
https://cloud.githubusercontent.com/assets/2068130/25585621/cb722634-2e9b-11e7-97b2-b3c7f85d3a3f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25585631/da5433ea-2e9b-11e7-99e6-3ea1ba8cc11b.png
