### ISSUE TITLE
Linksys Connect

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#2635]
**App Name:** Linksys Connect
**Bundle ID:** com.cisco.hnbu.connectexpress
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=470936137">470936137</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/linksys-connect/id470936137?mt=8&uo=4">https://itunes.apple.com/us/app/linksys-connect/id470936137?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Linksys LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/linksys-llc/id470936140?uo=4">© Linksys LLC</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple4/v4/23/dc/11/23dc1196-ae0a-9b05-4383-2b39dd12f842/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39782316-18fdc944-5312-11e8-9310-7814e166d850.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39782316-18fdc944-5312-11e8-9310-7814e166d850.png)
https://user-images.githubusercontent.com/2068130/39782316-18fdc944-5312-11e8-9310-7814e166d850.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39782335-27703962-5312-11e8-9885-03b18ebb6aaf.png
