### ISSUE TITLE
NOS Teletekst

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#2638]
**App Name:** NOS Teletekst
**Bundle ID:** com.eoffice.Teletekst
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=289246732">289246732</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nos-teletekst/id289246732?mt=8&uo=4">https://itunes.apple.com/us/app/nos-teletekst/id289246732?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Nederlandse Omroep Stichting
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nederlandse-omroep-stichting/id316584000?uo=4">© Nederlandse Omroep Stichting</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/95/97/ac/9597ac75-cb55-3993-3448-69a48a7b228f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25586506/e2aba718-2e9f-11e7-82ef-28dab14deea9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25586506/e2aba718-2e9f-11e7-82ef-28dab14deea9.png)
https://cloud.githubusercontent.com/assets/2068130/25586506/e2aba718-2e9f-11e7-82ef-28dab14deea9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25586523/f47ba8e4-2e9f-11e7-9d61-4470c924f8c2.png
