### ISSUE TITLE
EDGE Extended

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2639]
**App Name:** EDGE Extended
**Bundle ID:** net.mobigame.EdgeEX
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=455112100">455112100</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/edge-extended/id455112100?mt=8&uo=4">https://itunes.apple.com/us/app/edge-extended/id455112100?mt=8&uo=4</a>
**App Version:** 2.20
**Seller:** Mobigame
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobigame/id300896021?uo=4>© Mobigame</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/17/6f/1b/176f1b23-2e35-a74e-8926-20cd80142c06/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19838059/4192c39c-9ec7-11e6-83e3-102b30ce697b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19838059/4192c39c-9ec7-11e6-83e3-102b30ce697b.png)
https://cloud.githubusercontent.com/assets/20930745/19838059/4192c39c-9ec7-11e6-83e3-102b30ce697b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19838060/4cdf8cee-9ec7-11e6-9ffc-d2841a023e35.png
