### ISSUE TITLE
4 Images 1 Mot

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2641]
**App Name:** 4 Images 1 Mot
**Bundle ID:** de.lotum.4pics1wordfr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=596006531">596006531</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/4-images-1-mot/id596006531?mt=8&uo=4">https://itunes.apple.com/us/app/4-images-1-mot/id596006531?mt=8&uo=4</a>
**App Version:** 7.2.4
**Seller:** LOTUM GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lotum-gmbh/id459029666?uo=4">© LOTUM GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/0d/cd/82/0dcd82bf-9dff-18c3-b2d3-c2261001d25a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26374381/7488639e-4005-11e7-8ee8-e754e4c90bfd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25586064/f0889d52-2e9d-11e7-9e96-dc8942bf17b0.png)
https://cloud.githubusercontent.com/assets/2068130/25586064/f0889d52-2e9d-11e7-9e96-dc8942bf17b0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25586082/0256d9ae-2e9e-11e7-93ea-bcb4fcfcb653.png

**Comment by dreamnet** [comment]
Update:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26374381/7488639e-4005-11e7-8ee8-e754e4c90bfd.png)
https://cloud.githubusercontent.com/assets/2068130/26374381/7488639e-4005-11e7-8ee8-e754e4c90bfd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26374394/83a56d90-4005-11e7-9ad8-0bcf1469b779.png
