### ISSUE TITLE
String Wars: Fun Guitar Learning Game - Play with a real guitar, Compete with friends and Share the music

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2643]
**App Name:** String Wars: Fun Guitar Learning Game - Play with a real guitar, Compete with friends and Share the music
**Bundle ID:** com.aynur.shifu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=580707138">580707138</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/string-wars-fun-guitar-learning/id580707138?mt=8&uo=4">https://itunes.apple.com/us/app/string-wars-fun-guitar-learning/id580707138?mt=8&uo=4</a>
**App Version:** 2.6.2
**Seller:** Aynur Tech LLP
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aynur-tech-llp/id580707141?uo=4>© Aynur Tech LLP</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/55/66/3d/55663d14-c598-aa7f-b3d4-680610b26e78/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620652/4accfe5a-9882-11e6-82a1-61e6031e9712.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620652/4accfe5a-9882-11e6-82a1-61e6031e9712.png)
https://cloud.githubusercontent.com/assets/20930745/19620652/4accfe5a-9882-11e6-82a1-61e6031e9712.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19620665/63511fc4-9882-11e6-8133-3ec7fcfceba9.png
