### ISSUE TITLE
Solve That Puzzle!

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2645]
**App Name:** Solve That Puzzle!
**Bundle ID:** com.gearsprout.rebusgame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=624161291">624161291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/solve-that-puzzle/id624161291?mt=8&uo=4">https://itunes.apple.com/us/app/solve-that-puzzle/id624161291?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** GearSprout LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gearsprout/id525882008?uo=4">© GearSprout</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/ae/45/74/ae4574ec-9bb0-30d7-832c-2bcc9c534972/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26750860/5617f1a2-482c-11e7-96cf-6add7268a39b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26750860/5617f1a2-482c-11e7-96cf-6add7268a39b.png)
https://cloud.githubusercontent.com/assets/2068130/26750860/5617f1a2-482c-11e7-96cf-6add7268a39b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26750864/656a1e64-482c-11e7-9224-8ff10cd898a4.png
