### ISSUE TITLE
Notes&Order

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2648]
**App Name:** Notes&Order
**Bundle ID:** com.rugoso.NotesAndOrder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526945046">526945046</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/notes-order/id526945046?mt=8&uo=4">https://itunes.apple.com/us/app/notes-order/id526945046?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Rodrigo Yanez
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rodrigo-yanez/id330051413?uo=4">© Rodrigo Yanez</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple2/v4/01/bf/4e/01bf4ef2-5218-0d3a-bd8d-3ceb091f4f0d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039451/7a90f420-a444-11e6-936d-61c473f8effb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039451/7a90f420-a444-11e6-936d-61c473f8effb.png)
https://cloud.githubusercontent.com/assets/20930745/20039451/7a90f420-a444-11e6-936d-61c473f8effb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20039457/8fb4816e-a444-11e6-9816-ddc1d6258a23.png
