### ISSUE TITLE
Better Tube - Streaming Music & Videos for YouTube

### ISSUE THREAD

**Issue by cinnamennen** [glasklart/hd#2650]
**App Name:** Better Tube - Streaming Music & Videos for YouTube
**Bundle ID:** com.zgx.mediaburner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=411372503">411372503</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/better-tube-streaming-music/id411372503?mt=8&uo=4">https://itunes.apple.com/us/app/better-tube-streaming-music/id411372503?mt=8&uo=4</a>
**App Version:** 3.5.3
**Seller:** zhu guangxin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zgx/id411372506?uo=4">© zgx</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/2b/31/8b/2b318b74-f0ea-5b28-c188-c4fcf6f431e1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039534/ed484076-a445-11e6-86f7-7cf9585e098c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039534/ed484076-a445-11e6-86f7-7cf9585e098c.png)
https://cloud.githubusercontent.com/assets/20930745/20039534/ed484076-a445-11e6-86f7-7cf9585e098c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20039538/03cf666c-a446-11e6-91d6-6ae8bc0b9147.png
