### ISSUE TITLE
They Need To Be Fed 2

### ISSUE THREAD

**Issue by nikosaggelou** [glasklart/hd#2657]
**App Name:** They Need To Be Fed 2
**Bundle ID:** com.venbrux.tntbf2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=629297621">629297621</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/they-need-to-be-fed-2/id629297621?mt=8&uo=4">https://itunes.apple.com/us/app/they-need-to-be-fed-2/id629297621?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Jesse Venbrux
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jesse-venbrux/id541790697?uo=4">© Jesse Venbrux</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/c9/27/8f/c9278f91-fd6b-e1e6-f61e-2901238644ec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32990648-7607cf24-cd2d-11e7-94f1-9fdf11dce9dd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32990648-7607cf24-cd2d-11e7-94f1-9fdf11dce9dd.png)
https://user-images.githubusercontent.com/2068130/32990648-7607cf24-cd2d-11e7-94f1-9fdf11dce9dd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32990652-83b771a6-cd2d-11e7-8265-892cb87abdcc.png
