### ISSUE TITLE
Between - Relationship App for Couples

### ISSUE THREAD

**Issue by straypacket** [glasklart/hd#2658]
**App Name:** Between - Relationship App for Couples
**Bundle ID:** kr.co.vcnc.couple
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=458035189">458035189</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/between-relationship-app-for/id458035189?mt=8&uo=4">https://itunes.apple.com/us/app/between-relationship-app-for/id458035189?mt=8&uo=4</a>
**App Version:** 3.6.0
**Seller:** VCNC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vcnc/id422893216?uo=4>© VCNC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/38/69/1b/38691bb0-c446-63f7-7d5a-00518fd7ea71/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620573/c1bd5caa-9880-11e6-8569-ac62eab86261.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620573/c1bd5caa-9880-11e6-8569-ac62eab86261.png)
https://cloud.githubusercontent.com/assets/20930745/19620573/c1bd5caa-9880-11e6-8569-ac62eab86261.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19620580/d8bf1b3c-9880-11e6-8e40-1b7fbad123e7.png
