### ISSUE TITLE
Foodspotting

### ISSUE THREAD

**Issue by nikosaggelou** [glasklart/hd#2659]
**App Name:** Foodspotting
**Bundle ID:** com.foodspotting.iphone.lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=350727118">350727118</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/foodspotting/id350727118?mt=8&uo=4">https://itunes.apple.com/us/app/foodspotting/id350727118?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** Foodspotting, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/foodspotting-inc/id350727121?uo=4>© Foodspotting, Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/2e/ca/65/2eca65b1-d249-3ee9-ef21-e355067d137a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620521/b85c0a2c-987f-11e6-8879-84d4fde7cece.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620521/b85c0a2c-987f-11e6-8879-84d4fde7cece.png)
https://cloud.githubusercontent.com/assets/20930745/19620521/b85c0a2c-987f-11e6-8879-84d4fde7cece.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19620528/e19f0c54-987f-11e6-917d-fb5c4aa69a85.png
