### ISSUE TITLE
Das Erste

### ISSUE THREAD

**Issue by p3ep** [glasklart/hd#2662]
**App Name:** Das Erste
**Bundle ID:** com.daserste.daserste
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=610313719">610313719</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/das-erste/id610313719?mt=8&uo=4">https://itunes.apple.com/us/app/das-erste/id610313719?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Erstes Deutsches Fernsehen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/erstes-deutsches-fernsehen/id610313722?uo=4>© Erstes Deutsches Fernsehen</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/87/b4/42/87b44283-bd96-c004-7ea0-4aa0e4c6cb30/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620438/c83b107a-987d-11e6-99e7-e1ba4a1aaecb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620438/c83b107a-987d-11e6-99e7-e1ba4a1aaecb.png)
https://cloud.githubusercontent.com/assets/20930745/19620438/c83b107a-987d-11e6-99e7-e1ba4a1aaecb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19620445/defaecea-987d-11e6-8a20-97a02921c4d0.png
