### ISSUE TITLE
ZDF-App

### ISSUE THREAD

**Issue by p3ep** [glasklart/hd#2663]
**App Name:** ZDF-App
**Bundle ID:** de.zdf.mediathek.universal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=437025413">437025413</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zdf-app/id437025413?mt=8&uo=4">https://itunes.apple.com/us/app/zdf-app/id437025413?mt=8&uo=4</a>
**App Version:** 3.6
**Seller:** ZDFonline
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zdf/id437025416?uo=4>© ZDF</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/10/9b/e2/109be291-5886-78e3-cc1e-6659b8ee0e78/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18452102/f4215a04-7939-11e6-8b9c-caee327c8e4f.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18452102/f4215a04-7939-11e6-8b9c-caee327c8e4f.png)
https://cloud.githubusercontent.com/assets/20930745/18452102/f4215a04-7939-11e6-8b9c-caee327c8e4f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18452146/14bf53b0-793a-11e6-9f5d-aeec4bacc354.png
