### ISSUE TITLE
Khan Academy

### ISSUE THREAD

**Issue by abumpadump** [glasklart/hd#2667]
**App Name:** Khan Academy
**Bundle ID:** org.khanacademy.Khan-Academy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469863705">469863705</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/khan-academy/id469863705?mt=8&uo=4">https://itunes.apple.com/us/app/khan-academy/id469863705?mt=8&uo=4</a>
**App Version:** 5.2.5
**Seller:** Khan Academy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/khan-academy/id469863708?mt=8&uo=4">© Khan Academy</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/2e/d7/a5/2ed7a51f-69cb-421e-58f9-3470933176f1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54821795-8f5b0d00-4ca3-11e9-8b05-0639e0e51f98.png)

**Comment by ivanov007** [comment]
icon changed
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11980104/e8e3e96a-a95d-11e5-94df-6596379a84af.png)
https://cloud.githubusercontent.com/assets/3090247/11980104/e8e3e96a-a95d-11e5-94df-6596379a84af.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11980115/03270366-a95e-11e5-809e-75cac8f12d34.png

**Comment by alpcinar** [comment]
Needs update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54821795-8f5b0d00-4ca3-11e9-8b05-0639e0e51f98.png)
https://user-images.githubusercontent.com/20930745/54821795-8f5b0d00-4ca3-11e9-8b05-0639e0e51f98.png

Source:
https://user-images.githubusercontent.com/20930745/54821798-9124d080-4ca3-11e9-8c79-21f6e467bf39.png
