### ISSUE TITLE
BADLAND

### ISSUE THREAD

**Issue by ugleking** [glasklart/hd#2673]
**App Name:** BADLAND
**Bundle ID:** com.frogmindgames.dodge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=535176909">535176909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/badland/id535176909?mt=8&uo=4">https://itunes.apple.com/us/app/badland/id535176909?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Frogmind Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/frogmind/id535176912?uo=4>© Frogmind</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/56/55/10/5655100f-d5eb-65b1-e284-78086c254625/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18385185/4f53c48c-768f-11e6-86e9-3865d8cd3e41.png)

**Comment by Anuskuss** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18385166/2429009c-768f-11e6-9856-6f2b53bf0661.png)
https://cloud.githubusercontent.com/assets/20930745/18385166/2429009c-768f-11e6-9856-6f2b53bf0661.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18385178/3ef35ee0-768f-11e6-83db-206f4cbbf5dc.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18385185/4f53c48c-768f-11e6-86e9-3865d8cd3e41.png)
https://cloud.githubusercontent.com/assets/20930745/18385185/4f53c48c-768f-11e6-86e9-3865d8cd3e41.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18385191/5f56fd5e-768f-11e6-8763-7bed092b8cff.png)
