### ISSUE TITLE
Ringtonium Pro - a remarkable ringtone maker with free music library inside. Cut and edit unlimited ringtones, create unique tones and alerts!

### ISSUE THREAD

**Issue by purpleyarn** [glasklart/hd#2676]
**App Name:** Ringtonium Pro - a remarkable ringtone maker with free music library inside. Cut and edit unlimited ringtones, create unique tones and alerts!
**Bundle ID:** mobi.bam-boo.RingtoneMaker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=430832944">430832944</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ringtonium-pro-remarkable/id430832944?mt=8&uo=4">https://itunes.apple.com/us/app/ringtonium-pro-remarkable/id430832944?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** OU Bamboo Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bamboo-group/id341771597?uo=4>© Bamboo Group</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/cf/d2/40/cfd2405b-22c9-2b46-8e9e-73142f3e023c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620386/b2038e1e-987c-11e6-90c2-f9604f91e511.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19620386/b2038e1e-987c-11e6-90c2-f9604f91e511.png)
https://cloud.githubusercontent.com/assets/20930745/19620386/b2038e1e-987c-11e6-90c2-f9604f91e511.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19620402/f2f5d332-987c-11e6-9f95-e25b826c78a9.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/mobi.bam-boo.RingtoneMaker-large.png). No action needed.
