### ISSUE TITLE
Learn French with 7 jours sur la planète - Lite

### ISSUE THREAD

**Issue by BenChaimberg** [glasklart/hd#2678]
**App Name:** Learn French with 7 jours sur la planète - Lite
**Bundle ID:** com.tv5monde.7jourslite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=359321870">359321870</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/learn-french-with-7-jours-sur-la-plan%C3%A8te-lite/id359321870?mt=8&uo=4">https://itunes.apple.com/us/app/learn-french-with-7-jours-sur-la-plan%C3%A8te-lite/id359321870?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** TV5MONDE
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tv5monde/id359264756?uo=4">© TV5MONDE</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/9d/cd/a7/9dcda7cc-37a9-5aae-daf6-9521ce4dbb0b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25587173/2819ddee-2ea3-11e7-96fa-03553c4e713c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25587173/2819ddee-2ea3-11e7-96fa-03553c4e713c.png)
https://cloud.githubusercontent.com/assets/2068130/25587173/2819ddee-2ea3-11e7-96fa-03553c4e713c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25587187/36ac153e-2ea3-11e7-98f3-061e9500cd62.png
