### ISSUE TITLE
Suggester - Chord Progression Tool and Musical Scale Reference

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2682]
**App Name:** Suggester - Chord Progression Tool and Musical Scale Reference
**Bundle ID:** com.mathieurouthier.Suggester
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504740787">504740787</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/suggester-chord-progression/id504740787?mt=8&uo=4">https://itunes.apple.com/us/app/suggester-chord-progression/id504740787?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** Mathieu Routhier
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mathieu-routhier/id369283978?uo=4">© Mathieu Routhier</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/38/b7/69/38b769c4-c7a1-a333-5813-e03d02da14d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039663/e160e586-a447-11e6-849d-fe3ed94894fe.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039663/e160e586-a447-11e6-849d-fe3ed94894fe.png)
https://cloud.githubusercontent.com/assets/20930745/20039663/e160e586-a447-11e6-849d-fe3ed94894fe.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20039670/fb9daed4-a447-11e6-94a9-4622aa1369c4.png
