### ISSUE TITLE
CSTAR, la chaîne gratuite des clips, de la musique et du top streaming sur la TNT

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2684]
**App Name:** CSTAR, la chaîne gratuite des clips, de la musique et du top streaming sur la TNT
**Bundle ID:** com.canalplus.D17.prod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=583935854">583935854</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/cstar-la-chaine-gratuite-des/id583935854?mt=8&uo=4">https://itunes.apple.com/fr/app/cstar-la-chaine-gratuite-des/id583935854?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** GROUPE CANAL+
**Developer:** <a target="_blank" href=https://itunes.apple.com/fr/developer/groupe-canal+/id694580819?uo=4>© GROUPE CANAL+</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/d2/99/c0/d299c042-f222-5790-fc86-b57dee7b7a4b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19811396/83a8866e-9d31-11e6-9bd8-bf483975a668.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19811396/83a8866e-9d31-11e6-9bd8-bf483975a668.png)
https://cloud.githubusercontent.com/assets/20930745/19811396/83a8866e-9d31-11e6-9bd8-bf483975a668.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19811434/9d3a80aa-9d31-11e6-8ae9-b72888007a1c.png
