### ISSUE TITLE
i-nfo.fr - Actu !Phone,app gratuite,promos,tests

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2685]
**App Name:** i-nfo.fr - Actu !Phone,app gratuite,promos,tests
**Bundle ID:** com.ilgmedia.iphonfr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589408207">589408207</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/i-nfo.fr-actu-!phone-app-gratuite/id589408207?mt=8&uo=4">https://itunes.apple.com/us/app/i-nfo.fr-actu-!phone-app-gratuite/id589408207?mt=8&uo=4</a>
**App Version:** 6.1
**Seller:** iLGMedia
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ilgmedia/id472070052?uo=4>© iLGMedia</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/cf/4c/16/cf4c1662-0ff5-a24c-37a6-637a1904178b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618458/0d99f18c-984b-11e6-957d-33b20d1fac60.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618458/0d99f18c-984b-11e6-957d-33b20d1fac60.png)
https://cloud.githubusercontent.com/assets/20930745/19618458/0d99f18c-984b-11e6-957d-33b20d1fac60.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19618460/27bb95a2-984b-11e6-88f7-a45e318e13af.png
