### ISSUE TITLE
Closer - Actu des Stars, News People & Télé

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2687]
**App Name:** Closer - Actu des Stars, News People & Télé
**Bundle ID:** fr.mondadori.closer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=317547865">317547865</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/closer-actu-des-stars-news-people-t%C3%A9l%C3%A9/id317547865?mt=8&uo=4">https://itunes.apple.com/us/app/closer-actu-des-stars-news-people-t%C3%A9l%C3%A9/id317547865?mt=8&uo=4</a>
**App Version:** 4.0.6
**Seller:** Mondadori France Digital
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mondadori-france-digital/id313699833?uo=4">© Mondadori France Digital</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/8f/2e/09/8f2e099d-ac04-9945-908b-850eef901fbe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25587372/106711ac-2ea4-11e7-9a65-ec4b97766ac0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25587372/106711ac-2ea4-11e7-9a65-ec4b97766ac0.png)
https://cloud.githubusercontent.com/assets/2068130/25587372/106711ac-2ea4-11e7-9a65-ec4b97766ac0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25587385/1f2ff078-2ea4-11e7-8f90-c078e5cebe84.png
