### ISSUE TITLE
Food Reporter : restaurants, recettes, plats

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2688]
**App Name:** Food Reporter : restaurants, recettes, plats
**Bundle ID:** com.cbinnovation.notifood
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404530397">404530397</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/food-reporter-restaurants-recettes-plats/id404530397?mt=8&uo=4">https://itunes.apple.com/us/app/food-reporter-restaurants-recettes-plats/id404530397?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** Prisma Presse
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/prisma-media/id371682181?uo=4">© Prisma Media</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/c0/e1/fc/c0e1fc05-7aef-6702-2e15-231663dea918/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26387147/88d16fda-404b-11e7-8add-d452870aecc7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26387147/88d16fda-404b-11e7-8add-d452870aecc7.png)
https://cloud.githubusercontent.com/assets/2068130/26387147/88d16fda-404b-11e7-8add-d452870aecc7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26387157/9b2fc956-404b-11e7-9682-7949f8c3dcdc.png
