### ISSUE TITLE
La Tribune - l'actualité économie et finance

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2689]
**App Name:** La Tribune - l'actualité économie et finance
**Bundle ID:** fr.latribune.iphone.premium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335760795">335760795</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/la-tribune-lactualite-economie/id335760795?mt=8&uo=4">https://itunes.apple.com/us/app/la-tribune-lactualite-economie/id335760795?mt=8&uo=4</a>
**App Version:** 5.0.2
**Seller:** La Tribune
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/la-tribune/id335760798?uo=4">© La Tribune</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/cd/d5/5d/cdd55db2-ae3d-5df8-d3b4-8f73c0f15603/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20065239/b172a208-a50d-11e6-9745-0181e24711c3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20065239/b172a208-a50d-11e6-9745-0181e24711c3.png)
https://cloud.githubusercontent.com/assets/20930745/20065239/b172a208-a50d-11e6-9745-0181e24711c3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20065270/c88bdad6-a50d-11e6-9519-dc5140473f8b.png
