### ISSUE TITLE
Sports Car Challenge

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#269]
**App Name:** Sports Car Challenge
**Bundle ID:** com.vw.sportscar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=477469043">477469043</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sports-car-challenge/id477469043?mt=8&uo=4">https://itunes.apple.com/us/app/sports-car-challenge/id477469043?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Volkswagen (China) Investment Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/volkswagen-china-investment/id428518935?uo=4>© Volkswagen (China) Investment Co., Ltd.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/3a/1b/eb/3a1beb41-7bd9-9a27-7bf7-bcab7685bf2f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19416888/3d849c74-939d-11e6-97c2-5a8003a119b9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19416888/3d849c74-939d-11e6-97c2-5a8003a119b9.png)
https://cloud.githubusercontent.com/assets/20930745/19416888/3d849c74-939d-11e6-97c2-5a8003a119b9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19416894/5dcff5a0-939d-11e6-9c55-3e33dadafa8f.png
