### ISSUE TITLE
League of Evil 2

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2692]
**App Name:** League of Evil 2
**Bundle ID:** com.ravenousgames.loe2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493832593">493832593</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/league-of-evil-2/id493832593?mt=8&uo=4">https://itunes.apple.com/us/app/league-of-evil-2/id493832593?mt=8&uo=4</a>
**App Version:** 1.50
**Seller:** Ravenous Games Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ravenous-games-inc/id344310480?uo=4">© Ravenous Games Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple22/v4/ef/d5/49/efd54954-51e4-e437-952a-77f7434e0ab5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33243391-d57dd684-d2e5-11e7-902a-706fa28ec3a4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33243391-d57dd684-d2e5-11e7-902a-706fa28ec3a4.png)
https://user-images.githubusercontent.com/2068130/33243391-d57dd684-d2e5-11e7-902a-706fa28ec3a4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33243401-e8062554-d2e5-11e7-9e19-693512f941f0.png
