### ISSUE TITLE
Scribd - Books, audiobooks, documents and more

### ISSUE THREAD

**Issue by nikosaggelou** [glasklart/hd#2694]
**App Name:** Scribd - Books, audiobooks, documents and more
**Bundle ID:** com.scribd.iscribd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542557212">542557212</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scribd-books-audiobooks-documents/id542557212?mt=8&uo=4">https://itunes.apple.com/us/app/scribd-books-audiobooks-documents/id542557212?mt=8&uo=4</a>
**App Version:** 4.6.2
**Seller:** Scribd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/scribd/id332135353?uo=4>© Scribd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/2e/28/d5/2e28d523-6d59-f946-5c5a-e7c6221e00f3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18809472/7c54e0e4-827c-11e6-80fa-49bd6428bc6b.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18809472/7c54e0e4-827c-11e6-80fa-49bd6428bc6b.png)
https://cloud.githubusercontent.com/assets/2068130/18809472/7c54e0e4-827c-11e6-80fa-49bd6428bc6b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18809477/89d38766-827c-11e6-941a-331adeb10d53.png
