### ISSUE TITLE
Clipfish - Musikvideos, Filme, Anime, Serien, TV und vieles mehr

### ISSUE THREAD

**Issue by p3ep** [glasklart/hd#2695]
**App Name:** Clipfish - Musikvideos, Filme, Anime, Serien, TV und vieles mehr
**Bundle ID:** com.rtlinteractive.clipfishiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=402493202">402493202</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/clipfish-musikvideos-filme/id402493202?mt=8&uo=4">https://itunes.apple.com/de/app/clipfish-musikvideos-filme/id402493202?mt=8&uo=4</a>
**App Version:** 3.8.1
**Seller:** RTL interactive
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/rtl-interactive/id310266588?uo=4>© RTL interactive</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/67/72/36/67723660-8465-7cde-93df-838a456c88bc/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13030253/56192346-d2a4-11e5-98c8-6743c093a9da.png)

**Comment by Anuskuss** [comment]
Icon needs update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13030253/56192346-d2a4-11e5-98c8-6743c093a9da.png)
https://cloud.githubusercontent.com/assets/2068130/13030253/56192346-d2a4-11e5-98c8-6743c093a9da.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13030255/6754311e-d2a4-11e5-9204-9542d6dba16c.png
