### ISSUE TITLE
FidMe - Loyalty Cards & Deals

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2698]
**App Name:** FidMe - Loyalty Cards & Deals
**Bundle ID:** fr.snapp.fidmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391329324">391329324</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fidme-loyalty-cards-deals/id391329324?uo=4">https://apps.apple.com/us/app/fidme-loyalty-cards-deals/id391329324?uo=4</a>
**App Version:** 6.9.1
**Seller:** Snapp
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/snapp/id328059786?uo=4">© Snapp</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/de/60/19/de6019a7-904e-7ef7-3508-45a1410581a6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400769-f167c000-9b78-11e9-9b3e-b44e3c54c3d0.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400769-f167c000-9b78-11e9-9b3e-b44e3c54c3d0.png)
https://user-images.githubusercontent.com/20930745/60400769-f167c000-9b78-11e9-9b3e-b44e3c54c3d0.png

Source:
https://user-images.githubusercontent.com/20930745/60400770-f3ca1a00-9b78-11e9-9bb3-74b3516d44fe.png
