### ISSUE TITLE
Instaflash

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2699]
**App Name:** Instaflash
**Bundle ID:** com.eikonsoft.acdsee.cameraflash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467939077">467939077</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instaflash/id467939077?mt=8&uo=4">https://itunes.apple.com/us/app/instaflash/id467939077?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** Anlei Technology Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/anlei-technology-inc./id670111877?uo=4>© Anlei Technology Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/9b/3d/27/9b3d27bb-8441-9acf-6659-8a410dbcf9b0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618361/85d86672-9848-11e6-8f59-a1014748a7f4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618361/85d86672-9848-11e6-8f59-a1014748a7f4.png)
https://cloud.githubusercontent.com/assets/20930745/19618361/85d86672-9848-11e6-8f59-a1014748a7f4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19618365/9a2bde74-9848-11e6-870b-88a27936f3e3.png
