### ISSUE TITLE
Minesweeper Q

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#270]
**App Name:** Minesweeper Q
**Bundle ID:** com.spica.minesweeperq
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=421576027">421576027</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minesweeper-q/id421576027?mt=8&uo=4">https://itunes.apple.com/us/app/minesweeper-q/id421576027?mt=8&uo=4</a>
**App Version:** 1.42
**Seller:** Yi-Lun Lin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/spica/id376815594?uo=4>© Spica</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/3d/8c/65/3d8c659f-74fa-63dd-64a4-937ad7e6ccea/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/14661562/902f9d2e-067c-11e6-896a-89052b0cb7ff.png)

**Comment by Anuskuss** [comment]
I don't want to be that guy but the icon doesn't seem to fit perfectly in the glasklart theme and I don't have an idea how to change it. It think it has some grey parts aswell.

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/14661562/902f9d2e-067c-11e6-896a-89052b0cb7ff.png)
https://cloud.githubusercontent.com/assets/10950389/14661562/902f9d2e-067c-11e6-896a-89052b0cb7ff.png
***
Source:
https://cloud.githubusercontent.com/assets/10950389/14661569/9a22556a-067c-11e6-896e-5b5786f324a3.png

**Comment by ivanov007** [comment]
great, just one thing, for the source I can see you are using white on some parts, all those white parts needs to be transparent

**Comment by zmathiasz** [comment]
Oup!  Now that you point it out I can see it.  Yes..definitely not planned, just missed.  :smile:
