### ISSUE TITLE
Gulli

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2708]
**App Name:** Gulli
**Bundle ID:** com.lagardere.gulli
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=400922307">400922307</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/ch/app/gulli/id400922307?uo=4">https://apps.apple.com/ch/app/gulli/id400922307?uo=4</a>
**App Version:** 3.1.6
**Seller:** Jeunesse TV
**Developer:** <a target="_blank" href="https://apps.apple.com/ch/developer/jeunesse-tv/id1450267008?uo=4">© Jeunesse TV</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/9f/d5/fc/9fd5fc8e-4b0e-876d-7ea9-d86bfff5707c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60535805-3b7dac80-9d05-11e9-89f3-a5552324aafd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26751209/7ed877d0-4834-11e7-97f1-6a01439a180a.png)
https://cloud.githubusercontent.com/assets/2068130/26751209/7ed877d0-4834-11e7-97f1-6a01439a180a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26751213/8d2aee4e-4834-11e7-8acb-2a171e3e851c.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60535805-3b7dac80-9d05-11e9-89f3-a5552324aafd.png)
https://user-images.githubusercontent.com/20930745/60535805-3b7dac80-9d05-11e9-89f3-a5552324aafd.png

Source:
https://user-images.githubusercontent.com/20930745/60535817-3d477000-9d05-11e9-8e4e-3b4dcd537f9a.png
