### ISSUE TITLE
FRANCE 24 - International News

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2712]
**App Name:** FRANCE 24 - International News
**Bundle ID:** com.france24.application
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364379394">364379394</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/france-24-international-news/id364379394?mt=8&uo=4">https://itunes.apple.com/us/app/france-24-international-news/id364379394?mt=8&uo=4</a>
**App Version:** 3.5.1
**Seller:** France Medias Monde
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/france-medias-monde/id649289502?uo=4>© France Medias Monde</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple22/v4/7a/3c/32/7a3c3291-da0f-659e-2b55-716cab728431/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18955451/d7ac12a8-8657-11e6-8105-3558ee5b1dac.png)

**Comment by illinikev** [comment]
Icon needs update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18955451/d7ac12a8-8657-11e6-8105-3558ee5b1dac.png)
https://cloud.githubusercontent.com/assets/20930745/18955451/d7ac12a8-8657-11e6-8105-3558ee5b1dac.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18955514/129c8e1a-8658-11e6-86e0-8edb75c9bc23.png
