### ISSUE TITLE
TV5MONDE chaîne culturelle francophone

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2714]
**App Name:** TV5MONDE chaîne culturelle francophone
**Bundle ID:** com.tv5monde.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378282309">378282309</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tv5monde-cha%C3%AEne-culturelle-francophone/id378282309?mt=8&uo=4">https://itunes.apple.com/us/app/tv5monde-cha%C3%AEne-culturelle-francophone/id378282309?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** TV5MONDE
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tv5monde/id359264756?uo=4">© TV5MONDE</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/de/bb/cd/debbcd9b-c266-3b55-eda5-5655198ba9fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26751162/0a26e8b4-4833-11e7-91f6-85929bda81b9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26751162/0a26e8b4-4833-11e7-91f6-85929bda81b9.png)
https://cloud.githubusercontent.com/assets/2068130/26751162/0a26e8b4-4833-11e7-91f6-85929bda81b9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26751165/1c4c3170-4833-11e7-9d53-689019ee5f87.png
