### ISSUE TITLE
Song-Writer Lite: Write Lyrics

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2723]
**App Name:** Song-Writer Lite: Write Lyrics
**Bundle ID:** com.simonsapps.songwriterlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447771549">447771549</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/song-writer-lite-write-lyrics/id447771549?mt=8&uo=4">https://itunes.apple.com/us/app/song-writer-lite-write-lyrics/id447771549?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** WL Online Marketing LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/app-holdings/id808581339?uo=4">© App Holdings</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/1b/3c/e5/1b3ce5fa-fa68-935d-9ca1-ebc372747edf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39780339-49b66592-530c-11e8-9234-729102dd9d3c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39780339-49b66592-530c-11e8-9234-729102dd9d3c.png)
https://user-images.githubusercontent.com/2068130/39780339-49b66592-530c-11e8-9234-729102dd9d3c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39780373-5a209b00-530c-11e8-9ec5-d5be049f6daa.png
