### ISSUE TITLE
OpenSignal - Speed Test & Maps

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2725]
**App Name:** OpenSignal - Speed Test & Maps
**Bundle ID:** com.opensignal.OpenSignalMaps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598298030">598298030</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/opensignal-speed-test-maps/id598298030?mt=8&uo=4">https://itunes.apple.com/us/app/opensignal-speed-test-maps/id598298030?mt=8&uo=4</a>
**App Version:** 4.0.13
**Seller:** OpenSignal Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/opensignal-inc/id598298033?uo=4">© OpenSignal, Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple62/v4/99/67/aa/9967aacc-2201-bbef-21b3-8f82650265af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39378571-10a15002-4a59-11e8-9dc1-dbd02e9c2536.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** OpenSignal - Speed Test & Maps
**Bundle ID:** com.opensignal.OpenSignalMaps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598298030">598298030</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/opensignal-speed-test-maps/id598298030?mt=8&uo=4">https://itunes.apple.com/us/app/opensignal-speed-test-maps/id598298030?mt=8&uo=4</a>
**App Version:** 4.0.13
**Seller:** OpenSignal Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/opensignal-inc/id598298033?uo=4">© OpenSignal, Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple62/v4/99/67/aa/9967aacc-2201-bbef-21b3-8f82650265af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39378571-10a15002-4a59-11e8-9dc1-dbd02e9c2536.png)
https://user-images.githubusercontent.com/2068130/39378571-10a15002-4a59-11e8-9dc1-dbd02e9c2536.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39378586-22de1a3e-4a59-11e8-867f-2ae7edb5f39b.png
