### ISSUE TITLE
Mots Croisés HD

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2729]
**App Name:** Mots Croisés HD
**Bundle ID:** com.earthmanapps.motcroises
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=533932239">533932239</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mots-croises-hd/id533932239?mt=8&uo=4">https://itunes.apple.com/us/app/mots-croises-hd/id533932239?mt=8&uo=4</a>
**App Version:** 2.30
**Seller:** Joueur 2 studios Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/joueur-2-studios-inc./id961499040?uo=4">© Joueur 2 studios Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/b7/1b/c4/b71bc43b-81b4-d9db-3cbe-fdd651a27a33/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039785/66cf3b76-a44a-11e6-862c-d8448c949720.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20039785/66cf3b76-a44a-11e6-862c-d8448c949720.png)
https://cloud.githubusercontent.com/assets/20930745/20039785/66cf3b76-a44a-11e6-862c-d8448c949720.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20039790/7e0236fe-a44a-11e6-8345-2ec9a1eaefa8.png
