### ISSUE TITLE
Remote Mouse FREE - wireless keyboard, trackpad, best remote for computer

### ISSUE THREAD

**Issue by Firebirdflame** [glasklart/hd#2730]
**App Name:** Remote Mouse FREE - wireless keyboard, trackpad, best remote for computer
**Bundle ID:** com.remotemouse.remotemouse4free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=385894596">385894596</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/remote-mouse-free-wireless/id385894596?mt=8&uo=4">https://itunes.apple.com/us/app/remote-mouse-free-wireless/id385894596?mt=8&uo=4</a>
**App Version:** 3.12
**Seller:** YANG TIAN JIAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/yang-tian-jiao/id715503947?uo=4>© YANG TIAN JIAO</a>
**Supported Devices:** iPhone5, iPadThirdGen4G, iPhone4S, iPadThirdGen, iPad23G, iPhone5s, iPadFourthGen, iPhone6, iPhone5c, iPadMini4G, iPodTouchFifthGen, iPadMini, iPad2Wifi, iPhone6Plus, iPhone4, iPadFourthGen4G
**Original Artwork:**
<img src="http://a1922.phobos.apple.com/us/r30/Purple3/v4/63/83/38/6383380a-42f0-5319-e83e-f52e60a2055d/mzl.lrfpuugo.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6971693/4fec6f16-d94c-11e4-8934-c8bbc275e8fa.png)

**Comment by zmathiasz** [comment]
@dreamnet Same as issue #1407 

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6971693/4fec6f16-d94c-11e4-8934-c8bbc275e8fa.png)
https://cloud.githubusercontent.com/assets/10950389/6971693/4fec6f16-d94c-11e4-8934-c8bbc275e8fa.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6971703/614b6d7a-d94c-11e4-84b9-87f7a6f9887c.png
