### ISSUE TITLE
MagicPlan

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#2731]
**App Name:** MagicPlan
**Bundle ID:** com.sensopia.magicplan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427424432">427424432</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/magicplan/id427424432?mt=8&uo=4">https://itunes.apple.com/us/app/magicplan/id427424432?mt=8&uo=4</a>
**App Version:** 5.7
**Seller:** Sensopia Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sensopia/id402516206?uo=4>© Sensopia</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/82/33/c6/8233c673-38f2-aacb-26a0-7f72ff29d6a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18687236/6eb2e198-7f7f-11e6-883f-e8e7741138e2.png)

**Comment by grkka** [comment]
Needs update to v 5.00.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18687236/6eb2e198-7f7f-11e6-883f-e8e7741138e2.png)
https://cloud.githubusercontent.com/assets/20930745/18687236/6eb2e198-7f7f-11e6-883f-e8e7741138e2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18687265/8da4aafa-7f7f-11e6-8e86-7c7d6cefde95.png
