### ISSUE TITLE
GalaxyPic - Star & Space Photo Effects

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#2743]
**App Name:** GalaxyPic - Star & Space Photo Effects
**Bundle ID:** kr.co.noonus.GalaxyPic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=594099643">594099643</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/galaxypic-star-space-photo-effects/id594099643?mt=8&uo=4">https://itunes.apple.com/us/app/galaxypic-star-space-photo-effects/id594099643?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** SUNWOONG JANG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sunwoong-jang/id515224445?uo=4">© SUNWOONG JANG</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/44/e2/21/44e2214d-539f-dc74-a071-7ab7b7c54dfd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33232299-fe2a9d34-d203-11e7-9d1e-f8d5c9af036f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33232299-fe2a9d34-d203-11e7-9d1e-f8d5c9af036f.png)
https://user-images.githubusercontent.com/2068130/33232299-fe2a9d34-d203-11e7-9d1e-f8d5c9af036f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33232302-0dca91c2-d204-11e7-8b3f-596258ae1af2.png
