### ISSUE TITLE
Google

### ISSUE THREAD

**Issue by Youppi3** [glasklart/hd#2751]
**App Name:** Google
**Bundle ID:** com.google.GoogleMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284815942">284815942</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google/id284815942?mt=8&uo=4">https://itunes.apple.com/us/app/google/id284815942?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPadThirdGen4G, iPhone6Plus, iPhone5s, iPodTouchSixthGen, iPadMini4G, iPadFourthGen, iPad23G, iPadFourthGen4G, iPhone4S, iPad2Wifi, iPhone5, iPadMini, iPodTouchFifthGen, iPhone6, iPhone4, iPhone5c, iPadThirdGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/96/5a/68/965a68b3-75a0-1d32-1cba-6b24bf0a3c4f/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9780801/08ddb104-5753-11e5-8d8b-67da37d3e2af.png)

**Comment by zmathiasz** [comment]
@dreamnet 

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997464/10054cac-db8a-11e4-8855-ed5196cdc06e.png)
https://cloud.githubusercontent.com/assets/10950389/6997464/10054cac-db8a-11e4-8855-ed5196cdc06e.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6997465/1a2868f4-db8a-11e4-819a-9d85b2153326.png

**Comment by ivanov007** [comment]
icon changed
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9780801/08ddb104-5753-11e5-8d8b-67da37d3e2af.png)
https://cloud.githubusercontent.com/assets/3090247/9780801/08ddb104-5753-11e5-8d8b-67da37d3e2af.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9780802/08e63d56-5753-11e5-89a7-60903b94f57a.png
