### ISSUE TITLE
Barrel

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#276]
**App Name:** Barrel
 **Bundle ID:** com.aaronash.BarrelSettings
 **Version:** 1.8.1.1-1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://user-images.githubusercontent.com/2068130/36643896-19beff68-1a52-11e8-9190-700508a695fc.png" width="180" height="180" />
 **Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36643898-28b286fc-1a52-11e8-953f-289b9692b408.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36643898-28b286fc-1a52-11e8-953f-289b9692b408.png)
https://user-images.githubusercontent.com/2068130/36643898-28b286fc-1a52-11e8-953f-289b9692b408.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36643901-371da2b2-1a52-11e8-9210-b815f90fc0ec.png
