### ISSUE TITLE
Garmin Connect™

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#2760]
**App Name:** Garmin Connect™
**Bundle ID:** com.garmin.connect.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=583446403">583446403</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/garmin-connect/id583446403?mt=8&uo=4">https://itunes.apple.com/us/app/garmin-connect/id583446403?mt=8&uo=4</a>
**App Version:** 4.7
**Seller:** Garmin International
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/garmin/id411046952?uo=4">© Garmin</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/6c/b9/45/6cb945f8-6fdf-a6e1-ac55-f2b6ac743514/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41806229-36612c76-76ba-11e8-8306-c5bdae303165.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41806229-36612c76-76ba-11e8-8306-c5bdae303165.png)
https://user-images.githubusercontent.com/2068130/41806229-36612c76-76ba-11e8-8306-c5bdae303165.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41806233-47f6277a-76ba-11e8-83b0-34c6a5484868.png
