### ISSUE TITLE
8tracks playlist radio - Free music app

### ISSUE THREAD

**Issue by kyewei** [glasklart/hd#2765]
**App Name:** 8tracks playlist radio - Free music app
**Bundle ID:** com.8tracks.etracksapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=346194763">346194763</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/8tracks-playlist-radio-free/id346194763?mt=8&uo=4">https://itunes.apple.com/us/app/8tracks-playlist-radio-free/id346194763?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** 8tracks Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/8tracks-inc./id346194766?uo=4>© 8tracks Inc.</a>
**Supported Devices:** iPhone5, iPodTouchFifthGen, iPad23G, iPadFourthGen, iPhone5c, iPhone4, iPad2Wifi, iPadThirdGen4G, iPadMini, iPhone6, iPadMini4G, iPhone6Plus, iPhone4S, iPhone5s, iPadThirdGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/40/ef/12/40ef1284-a615-388c-0424-1d060292b16f/mzl.tltjpock.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8374204/dedb46c2-1bf3-11e5-810b-7b4d124c94d4.png)

**Comment by Trubbel** [comment]
Icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8374204/dedb46c2-1bf3-11e5-810b-7b4d124c94d4.png)
https://cloud.githubusercontent.com/assets/10730122/8374204/dedb46c2-1bf3-11e5-810b-7b4d124c94d4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8374201/db7d79c8-1bf3-11e5-97b2-adc1d65441a5.png
