### ISSUE TITLE
Antenna client for reddit

### ISSUE THREAD

**Issue by kyewei** [glasklart/hd#2768]
**App Name:** Antenna client for reddit
**Bundle ID:** com.amleszk.amrc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=572391252">572391252</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/antenna-client-for-reddit/id572391252?mt=8&uo=4">https://itunes.apple.com/us/app/antenna-client-for-reddit/id572391252?mt=8&uo=4</a>
**App Version:** 8.18
**Seller:** Alistair Leszkiewicz
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alistair-leszkiewicz/id320973148?uo=4">© Alistair Leszkiewicz</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/8b/6a/54/8b6a548f-3cca-e979-709d-73625dee2b8d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38456519-d2594710-3a85-11e8-9621-5e815773d391.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38456519-d2594710-3a85-11e8-9621-5e815773d391.png)
https://user-images.githubusercontent.com/20930745/38456519-d2594710-3a85-11e8-9621-5e815773d391.png

Source:
https://user-images.githubusercontent.com/20930745/38456526-e64b71da-3a85-11e8-8357-e9cce7e52564.png
