### ISSUE TITLE
AppStart for iPhone

### ISSUE THREAD

**Issue by stevendo** [glasklart/hd#2774]
**App Name:** AppStart for iPhone
**Bundle ID:** com.appadvice.appstartiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=488613223">488613223</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appstart-for-iphone/id488613223?mt=8&uo=4">https://itunes.apple.com/us/app/appstart-for-iphone/id488613223?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** App Advice
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/appadvice-com/id305663481?uo=4">© AppAdvice.com</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/ab/1e/f8/ab1ef8a2-b852-91f7-ec66-37b582edc8cc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32985485-7c7fe65a-ccbc-11e7-9240-f3a781ce3740.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32985485-7c7fe65a-ccbc-11e7-9240-f3a781ce3740.png)
https://user-images.githubusercontent.com/2068130/32985485-7c7fe65a-ccbc-11e7-9240-f3a781ce3740.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32985487-8eab8690-ccbc-11e7-98e0-6aa96640d7e9.png
