### ISSUE TITLE
Manga Storm - The Ultimate Manga Reader

### ISSUE THREAD

**Issue by Darkiee** [glasklart/hd#2777]
**App Name:** Manga Storm - The Ultimate Manga Reader
**Bundle ID:** com.wayudaorerk.mangastormall
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417341160">417341160</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/manga-storm-the-ultimate-manga-reader/id417341160?mt=8&uo=4">https://itunes.apple.com/us/app/manga-storm-the-ultimate-manga-reader/id417341160?mt=8&uo=4</a>
**App Version:** 3.1.7
**Seller:** Work Corner Company Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/work-corner-company-limited/id366621315?uo=4">© Work Corner Company Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/e3/3f/3a/e33f3a74-6524-fae1-79a2-469d79407dd3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29175644-34c8e296-7daf-11e7-9d57-e4e29fb308c3.png)

**Comment by ivanov007** [comment]
needs update

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29175644-34c8e296-7daf-11e7-9d57-e4e29fb308c3.png)
https://user-images.githubusercontent.com/3090247/29175644-34c8e296-7daf-11e7-9d57-e4e29fb308c3.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29175643-34c562a6-7daf-11e7-8e75-9fe408343a93.png
