### ISSUE TITLE
Simpler Contacts Pro - Smart address book manager with groups, backup & duplicate cleanup

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2781]
**App Name:** Simpler Contacts Pro - Smart address book manager with groups, backup & duplicate cleanup
**Bundle ID:** ytdevelopments.multiedit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476148613">476148613</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/simpler-contacts-pro-smart/id476148613?mt=8&uo=4">https://itunes.apple.com/us/app/simpler-contacts-pro-smart/id476148613?mt=8&uo=4</a>
**App Version:** 7.1
**Seller:** YT Development Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yt-development-ltd/id476148616?uo=4>© YT Development Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/fa/64/07/fa640794-a380-4c36-1ad2-e5fb954a758f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16276320/1beacfec-38ae-11e6-8eb7-6565afada121.png)

**Comment by ivanov007** [comment]
icon changed

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16276320/1beacfec-38ae-11e6-8eb7-6565afada121.png)
https://cloud.githubusercontent.com/assets/2068130/16276320/1beacfec-38ae-11e6-8eb7-6565afada121.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16276335/2dfaac70-38ae-11e6-9327-3cd25f8f280f.png
