### ISSUE TITLE
MOLDIV - Photo Editor, Collage & Beauty Camera

### ISSUE THREAD

**Issue by egriego24** [glasklart/hd#2788]
**App Name:** MOLDIV - Photo Editor, Collage & Beauty Camera
**Bundle ID:** com.jellybus.Moldiv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=608188610">608188610</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moldiv-photo-editor-collage/id608188610?mt=8&uo=4">https://itunes.apple.com/us/app/moldiv-photo-editor-collage/id608188610?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** JellyBus Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jellybus-inc./id421117479?uo=4">© JellyBus Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/92/ca/2c/92ca2c49-2b4b-f161-4d46-28d5dc95d508/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040397/e59b7aee-a456-11e6-9f1c-56c2a2cb96c1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040397/e59b7aee-a456-11e6-9f1c-56c2a2cb96c1.png)
https://cloud.githubusercontent.com/assets/20930745/20040397/e59b7aee-a456-11e6-9f1c-56c2a2cb96c1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20040402/03d18530-a457-11e6-940b-ab5043d8767d.png
