### ISSUE TITLE
Photo Lab: Art Photography & Xmas pic blender. Photo booth with color drawing filters

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2789]
**App Name:** Photo Lab: Art Photography & Xmas pic blender. Photo booth with color drawing filters
**Bundle ID:** com.photo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441457218">441457218</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photo-lab-art-photography/id441457218?mt=8&uo=4">https://itunes.apple.com/us/app/photo-lab-art-photography/id441457218?mt=8&uo=4</a>
**App Version:** 2.4.5
**Seller:** VicMan LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vicman-llc/id441457221?uo=4>© VicMan LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/86/da/43/86da431e-b4a5-8ce4-28a5-4ad55892f6a3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11883507/c6832514-a513-11e5-9c65-85162af7f74b.png)

**Comment by ivanov007** [comment]
icon changed

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11883507/c6832514-a513-11e5-9c65-85162af7f74b.png)
https://cloud.githubusercontent.com/assets/2068130/11883507/c6832514-a513-11e5-9c65-85162af7f74b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11883515/d4b0d352-a513-11e5-87ab-ffe312563083.png
