### ISSUE TITLE
TVShow Time, the TV guide for TV show addicts

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#2791]
**App Name:** TVShow Time, the TV guide for TV show addicts
**Bundle ID:** com.tozelabs.tvshowtime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431065232">431065232</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tvshow-time-tv-guide-for-tv/id431065232?mt=8&uo=4">https://itunes.apple.com/us/app/tvshow-time-tv-guide-for-tv/id431065232?mt=8&uo=4</a>
**App Version:** 5.0.0
**Seller:** Toze Labs
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/toze-labs/id382584234?uo=4>© Toze Labs</a>
**Supported Devices:** iPadThirdGen4G, iPodTouchFifthGen, iPadMini, iPhone5, iPadFourthGen, iPad23G, iPodTouchSixthGen, iPhone4, iPhone4S, iPhone6, iPadMini4G, iPhone6Plus, iPadFourthGen4G, iPadThirdGen, iPhone5c, iPhone5s, iPad2Wifi
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/ee/83/94/ee8394a0-a8a5-a8b6-690f-25c17a352b00/mzl.myghrzhf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8895400/79016c34-33d9-11e5-839a-13f6a5874dcb.png)

**Comment by l8er4now** [comment]
Can we get an updated icon?

**App Name:** TVShow Time, the TV guide for TV show addicts
**Bundle ID:** com.tozelabs.tvshowtime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431065232">431065232</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tvshow-time-tv-guide-for-tv/id431065232?mt=8&uo=4">https://itunes.apple.com/us/app/tvshow-time-tv-guide-for-tv/id431065232?mt=8&uo=4</a>
**App Version:** 5.0.0
**Seller:** Toze Labs
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/toze-labs/id382584234?uo=4>© Toze Labs</a>
**Supported Devices:** iPadThirdGen, iPhone5c, iPadFourthGen4G, iPhone6, iPodTouchSixthGen, iPad23G, iPadMini, iPadThirdGen4G, iPhone4, iPhone5, iPhone6Plus, iPhone4S, iPodTouchFifthGen, iPadMini4G, iPhone5s, iPadFourthGen, iPad2Wifi
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/ee/83/94/ee8394a0-a8a5-a8b6-690f-25c17a352b00/mzl.myghrzhf.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8895400/79016c34-33d9-11e5-839a-13f6a5874dcb.png)
https://cloud.githubusercontent.com/assets/2068130/8895400/79016c34-33d9-11e5-839a-13f6a5874dcb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8895402/875b0cae-33d9-11e5-87e0-0df62a36199d.png
