### ISSUE TITLE
France Agenda

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#2794]
**App Name:** France Agenda
**Bundle ID:** L949F63GMJ.FrHolidays
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347121138">347121138</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/france-agenda/id347121138?uo=4">https://apps.apple.com/us/app/france-agenda/id347121138?uo=4</a>
**App Version:** 5.2
**Seller:** Paris Logic
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/paris-logic/id1245400567?uo=4">© Paris Logic</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/82/14/c3/8214c3f0-f26e-19a1-0063-8fbe8ff8f2ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400716-3ccd9e80-9b78-11e9-8856-c5f9086e9483.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400716-3ccd9e80-9b78-11e9-8856-c5f9086e9483.png)
https://user-images.githubusercontent.com/20930745/60400716-3ccd9e80-9b78-11e9-8856-c5f9086e9483.png

Source:
https://user-images.githubusercontent.com/20930745/60400717-3fc88f00-9b78-11e9-868c-787d14f17461.png
