### ISSUE TITLE
Luxylight

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#28]
**App Name:** Luxylight
**Bundle ID:** com.sylion.luxylight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=392102668">392102668</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/luxylight/id392102668?mt=8&uo=4">https://itunes.apple.com/us/app/luxylight/id392102668?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Fernando Torcelly
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fernando-torcelly/id977610201?uo=4">© Fernando Torcelly</a>
**Supported Devices:** iPhone4, iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/67/aa/d3/67aad3b4-85fd-d86e-6a6a-95bd7da88854/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030427/1374ddc2-a365-11e6-81ee-772cee10e120.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030427/1374ddc2-a365-11e6-81ee-772cee10e120.png)
https://cloud.githubusercontent.com/assets/20930745/20030427/1374ddc2-a365-11e6-81ee-772cee10e120.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20030433/2bdbcc5e-a365-11e6-9784-f49c51428033.png
