### ISSUE TITLE
Boursorama Banque

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#2802]
**App Name:** Boursorama Banque
**Bundle ID:** com.boursorama.boursoclient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=425368900">425368900</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/boursorama-banque/id425368900?uo=4">https://apps.apple.com/us/app/boursorama-banque/id425368900?uo=4</a>
**App Version:** 6.2.8
**Seller:** Boursorama
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/boursorama/id371340628?uo=4">© Boursorama</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/49/29/79/4929792e-bc07-dffb-5daa-7e6c08c91800/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60126221-ca327c80-978d-11e9-9563-73da1ceac89f.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60126226-cc94d680-978d-11e9-8f23-41145054b7e2.png)
https://user-images.githubusercontent.com/20930745/60126226-cc94d680-978d-11e9-8f23-41145054b7e2.png

Source:
https://user-images.githubusercontent.com/20930745/60126221-ca327c80-978d-11e9-9563-73da1ceac89f.png
