### ISSUE TITLE
Subway Surfers

### ISSUE THREAD

**Issue by me12345** [glasklart/hd#281]
**App Name:** Subway Surfers
**Bundle ID:** com.kiloo.subwaysurfers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=512939461">512939461</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/subway-surfers/id512939461?mt=8&uo=4">https://itunes.apple.com/us/app/subway-surfers/id512939461?mt=8&uo=4</a>
**App Version:** 1.61.0
**Seller:** Kiloo
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kiloo/id330629809?uo=4>© Kiloo</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/9b/fd/84/9bfd8402-7de0-4981-3cb5-096d6480d67c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19006701/3f274dda-8761-11e6-82ab-f9c69fb9843f.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
... only a try ... i don't like it 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18950690/5a7697c4-8641-11e6-8489-386a09bafb07.png)

https://cloud.githubusercontent.com/assets/20930745/18950690/5a7697c4-8641-11e6-8489-386a09bafb07.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18950734/9e3e1ec8-8641-11e6-989d-f9ed41f053de.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Will look better it the outside lines are removed.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18969732/aea9d4a8-868e-11e6-97b8-281229147d08.png)
https://cloud.githubusercontent.com/assets/2068130/18969732/aea9d4a8-868e-11e6-97b8-281229147d08.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18969751/bdd4b402-868e-11e6-9f07-663ac6c3f288.png
