### ISSUE TITLE
Character Pad – Special Characters Paste Board

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#2814]
**App Name:** Character Pad – Special Characters Paste Board
**Bundle ID:** com.davidcaddy.specialcharacters
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418874651">418874651</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/character-pad-special-characters/id418874651?mt=8&uo=4">https://itunes.apple.com/us/app/character-pad-special-characters/id418874651?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** David Caddy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/david-caddy/id398901339?uo=4">© David Caddy</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/7d/bb/5b/7dbb5b0c-089c-b037-f796-ec333d3ed570/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040461/54d0605e-a458-11e6-9b85-d18b7899c457.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040461/54d0605e-a458-11e6-9b85-d18b7899c457.png)
https://cloud.githubusercontent.com/assets/20930745/20040461/54d0605e-a458-11e6-9b85-d18b7899c457.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20040466/69e61326-a458-11e6-81bd-c3b8efa0d304.png
