### ISSUE TITLE
Write for iPhone - A Note Taking and Markdown Writing App

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#2815]
**App Name:** Write for iPhone - A Note Taking and Markdown Writing App
**Bundle ID:** me.tanmay.Write
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=587363157">587363157</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/write-for-iphone-note-taking/id587363157?mt=8&uo=4">https://itunes.apple.com/us/app/write-for-iphone-note-taking/id587363157?mt=8&uo=4</a>
**App Version:** 2.6.2
**Seller:** Tanmay Sonawane
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tanmay-sonawane/id507744776?uo=4">© Tanmay Sonawane</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/95/bf/23/95bf23ea-2809-bd91-2ede-245a824ff7a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040431/b1d41ddc-a457-11e6-8581-7e9509cf8cfd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040431/b1d41ddc-a457-11e6-8581-7e9509cf8cfd.png)
https://cloud.githubusercontent.com/assets/20930745/20040431/b1d41ddc-a457-11e6-8581-7e9509cf8cfd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20040434/c9ab7edc-a457-11e6-889f-5faad54d03ba.png
