### ISSUE TITLE
ProTube HD

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2816]
**App Name:** ProTube HD
 **Bundle ID:** de.j-gessner.ProTubeHD
 **Version:** 1.12.1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/10730122/20821247/43e9cbac-b841-11e6-8f99-214b9406a14a.png" width="180" height="180" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/20820984/7e2605da-b83f-11e6-90d7-598e50dc1f28.png)

**Comment by grkka** [comment]
@dreamnet @ivanov007 Needs update. Please.

**Comment by ivanov007** [comment]
@grkka do you have the new bundle id? I haven't bought this app

**Comment by Trubbel** [comment]
The Bundle ID seems to be the same (`de.j-gessner.ProTubeHD`),

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/20820984/7e2605da-b83f-11e6-90d7-598e50dc1f28.png)
https://cloud.githubusercontent.com/assets/10730122/20820984/7e2605da-b83f-11e6-90d7-598e50dc1f28.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/20820983/7e253876-b83f-11e6-905d-ab2ac8374b2b.png
