### ISSUE TITLE
FioWriter - Productive text editor for iPhone & iPad with command keys and cloud sync

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2819]
**App Name:** FioWriter - Productive text editor for iPhone & iPad with command keys and cloud sync
**Bundle ID:** com.nokisoft.FioWriter.01
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542394038">542394038</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fiowriter-productive-text-editor-for-iphone-ipad-command/id542394038?mt=8&uo=4">https://itunes.apple.com/us/app/fiowriter-productive-text-editor-for-iphone-ipad-command/id542394038?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Han Zhao
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/han-zhao/id426331585?uo=4">© Han Zhao</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/87/0e/8b/870e8b57-c5a1-c056-fe39-f4af4d558213/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26751341/21688f4c-4837-11e7-8086-03806ab79a1c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26751341/21688f4c-4837-11e7-8086-03806ab79a1c.png)
https://cloud.githubusercontent.com/assets/2068130/26751341/21688f4c-4837-11e7-8086-03806ab79a1c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26751342/32a48144-4837-11e7-802a-1f41acb411ab.png
