### ISSUE TITLE
Split Pic Collage Maker Layout

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2821]
**App Name:** Split Pic Collage Maker Layout
**Bundle ID:** com.aaronray.splitcamera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570748340">570748340</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/split-pic-collage-maker-layout/id570748340?mt=8&uo=4">https://itunes.apple.com/us/app/split-pic-collage-maker-layout/id570748340?mt=8&uo=4</a>
**App Version:** 5.9.6
**Seller:** Easy Tiger Apps, LLC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/easy-tiger-apps-llc/id570748343?uo=4">© Easy Tiger Apps, LLC.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/41/2e/fc/412efc9e-5140-64d5-5ba8-ea677c1c9e89/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38148916-a901f82c-3458-11e8-90ff-b307b56bacd3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38148916-a901f82c-3458-11e8-90ff-b307b56bacd3.png)
https://user-images.githubusercontent.com/2068130/38148916-a901f82c-3458-11e8-90ff-b307b56bacd3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38148924-b8856c0c-3458-11e8-955a-2ca739ced185.png
