### ISSUE TITLE
App.net - Broadcast With Push

### ISSUE THREAD

**Issue by jeremyblake** [glasklart/hd#2828]
**App Name:** App.net - Broadcast With Push
**Bundle ID:** net.app.moana
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=534414475">534414475</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/app.net-broadcast-with-push/id534414475?mt=8&uo=4">https://itunes.apple.com/us/app/app.net-broadcast-with-push/id534414475?mt=8&uo=4</a>
**App Version:** 2.3.945
**Seller:** Mixed Media Labs, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mixed-media-labs-inc./id382339386?uo=4">© Mixed Media Labs, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/c1/19/0f/c1190f27-243a-4b9f-aba6-edf2706e14a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19919952/0de51e94-a0d6-11e6-9af5-c3ea21d63f03.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19919952/0de51e94-a0d6-11e6-9af5-c3ea21d63f03.png)
https://cloud.githubusercontent.com/assets/20930745/19919952/0de51e94-a0d6-11e6-9af5-c3ea21d63f03.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19919969/24086370-a0d6-11e6-8509-39c7d1a58f9c.png
