### ISSUE TITLE
Move the Box

### ISSUE THREAD

**Issue by me12345** [glasklart/hd#283]
**App Name:** Move the Box
**Bundle ID:** com.bitchingames.movethebox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=491113310">491113310</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/move-the-box/id491113310?mt=8&uo=4">https://itunes.apple.com/us/app/move-the-box/id491113310?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Pavlo Shelyazhenko
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pavlo-shelyazhenko/id1090245154?uo=4">© Pavlo Shelyazhenko</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/08/61/47/0861479d-6b14-0030-2109-e974e11be0ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38535749-64d828da-3c85-11e8-9730-5cdfff8331d0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38535749-64d828da-3c85-11e8-9730-5cdfff8331d0.png)
https://user-images.githubusercontent.com/2068130/38535749-64d828da-3c85-11e8-9730-5cdfff8331d0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38535759-74683240-3c85-11e8-9128-1a27f64351af.png
