### ISSUE TITLE
FINAL FANTASY DIMENSIONS

### ISSUE THREAD

**Issue by justoned420** [glasklart/hd#2832]
**App Name:** FINAL FANTASY DIMENSIONS
**Bundle ID:** com.square-enix.fflegends
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540992837">540992837</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/final-fantasy-dimensions/id540992837?mt=8&uo=4">https://itunes.apple.com/us/app/final-fantasy-dimensions/id540992837?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/79/29/a0/7929a04f-673e-a44d-6b22-2c29e7054a0e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14406689/e9de3912-fe74-11e5-9545-df65b34ffc3c.png)

**Comment by ivanov007** [comment]
adding source
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14406689/e9de3912-fe74-11e5-9545-df65b34ffc3c.png)
https://cloud.githubusercontent.com/assets/3090247/14406689/e9de3912-fe74-11e5-9545-df65b34ffc3c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14406690/e9e457c0-fe74-11e5-95fa-636baaa7350c.png)
