### ISSUE TITLE
Amazon Photos

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#2834]
**App Name:** Amazon Photos
**Bundle ID:** com.amazon.CloudDrivePhotos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=621574163">621574163</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/amazon-photos/id621574163?uo=4">https://apps.apple.com/us/app/amazon-photos/id621574163?uo=4</a>
**App Version:** 6.3.0
**Seller:** AMZN Mobile LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/amzn-mobile-llc/id297606954?uo=4">© AMZN Mobile LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/7a/a7/0b/7aa70b74-0cf3-036f-329d-27524cd21c4e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59979550-b3532500-95e9-11e9-84a2-9cd09bc4a4a8.png)

**Comment by Trubbel** [comment]
Icon has been updated.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495829/df326f42-2170-11e5-868d-ba67e42268d3.png)
https://cloud.githubusercontent.com/assets/2068130/8495829/df326f42-2170-11e5-868d-ba67e42268d3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8495837/ec3f218a-2170-11e5-9bea-5e422b09f810.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59979550-b3532500-95e9-11e9-84a2-9cd09bc4a4a8.png)
https://user-images.githubusercontent.com/20930745/59979550-b3532500-95e9-11e9-84a2-9cd09bc4a4a8.png

Source:
https://user-images.githubusercontent.com/20930745/59979551-b4845200-95e9-11e9-9391-fb9b15b020c9.png
