### ISSUE TITLE
GoPro

### ISSUE THREAD

**Issue by Hawri84** [glasklart/hd#2844]
**App Name:** GoPro
**Bundle ID:** com.gopro.GoPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561350520">561350520</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gopro/id561350520?uo=4">https://apps.apple.com/us/app/gopro/id561350520?uo=4</a>
**App Version:** 5.2.4
**Seller:** GoPro, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gopro-inc/id561350523?uo=4">© GoPro, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/66/b5/29/66b52902-ebd8-a097-6c52-2bb693cf6f80/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60681968-8af0e380-9e91-11e9-98c6-0f60536c8c06.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60681968-8af0e380-9e91-11e9-98c6-0f60536c8c06.png)
https://user-images.githubusercontent.com/20930745/60681968-8af0e380-9e91-11e9-98c6-0f60536c8c06.png

Source:
https://user-images.githubusercontent.com/20930745/60681970-8fb59780-9e91-11e9-9e6a-d5656d2b449e.png
