### ISSUE TITLE
KRONEHIT Online Radio Charts

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#2852]
**App Name:** KRONEHIT Online Radio Charts
**Bundle ID:** com.mira4.kronehitplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324558085">324558085</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/kronehit-online-radio-charts/id324558085?mt=8&uo=4">https://itunes.apple.com/de/app/kronehit-online-radio-charts/id324558085?mt=8&uo=4</a>
**App Version:** 3.7.0
**Seller:** wunderweiss GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/wunderweiss-design-und-technik/id493932286?uo=4">© wunderweiss – Design und Technik</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/16/47/f5/1647f5ad-e9fb-a1d5-ef34-306d0a1809ee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20065882/08fa22ba-a510-11e6-9f4c-ce313f707a07.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20065882/08fa22ba-a510-11e6-9f4c-ce313f707a07.png)
https://cloud.githubusercontent.com/assets/20930745/20065882/08fa22ba-a510-11e6-9f4c-ce313f707a07.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20065922/2452f58c-a510-11e6-868c-a197efac7ba9.png
