### ISSUE TITLE
Touch of Modern: Shopping

### ISSUE THREAD

**Issue by Romeo0119** [glasklart/hd#2855]
**App Name:** Touch of Modern: Shopping
**Bundle ID:** com.touchofmodern.tomo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=567647280">567647280</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touch-of-modern-shopping/id567647280?mt=8&uo=4">https://itunes.apple.com/us/app/touch-of-modern-shopping/id567647280?mt=8&uo=4</a>
**App Version:** 3.3.23
**Seller:** Whitehawk Ventures, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/whitehawk-ventures-inc/id494201765?uo=4">© Whitehawk Ventures, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/25/a1/d8/25a1d88f-c88c-8d70-798b-78dd9ba4fbf5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285289/a46be448-c434-11e6-8681-e3137ca1c79e.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Touch of Modern: Shopping
**Bundle ID:** com.touchofmodern.tomo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=567647280">567647280</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touch-of-modern-shopping/id567647280?mt=8&uo=4">https://itunes.apple.com/us/app/touch-of-modern-shopping/id567647280?mt=8&uo=4</a>
**App Version:** 3.3.23
**Seller:** Whitehawk Ventures, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/whitehawk-ventures-inc/id494201765?uo=4">© Whitehawk Ventures, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/25/a1/d8/25a1d88f-c88c-8d70-798b-78dd9ba4fbf5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285289/a46be448-c434-11e6-8681-e3137ca1c79e.png)
https://cloud.githubusercontent.com/assets/20930745/21285289/a46be448-c434-11e6-8681-e3137ca1c79e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21285291/afac19ea-c434-11e6-80e5-bcfb73401760.png
