### ISSUE TITLE
Giro d'Italia

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2862]
**App Name:** Giro d'Italia
**Bundle ID:** com.rcs.giroditalia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=522688460">522688460</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/giro-ditalia/id522688460?mt=8&uo=4">https://itunes.apple.com/us/app/giro-ditalia/id522688460?mt=8&uo=4</a>
**App Version:** 2.2.8
**Seller:** RCS MediaGroup S.p.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rcs-mediagroup-s-p-a/id326634019?uo=4">© RCS MediaGroup S.p.A.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/f5/cd/ef/f5cdefb0-413e-12ec-ae58-0c9b33afce70/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698397-7bc91216-c7a5-11e7-8e68-6f65f54a887e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698397-7bc91216-c7a5-11e7-8e68-6f65f54a887e.png)
https://user-images.githubusercontent.com/2068130/32698397-7bc91216-c7a5-11e7-8e68-6f65f54a887e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32698401-8b9f82ba-c7a5-11e7-8302-bed9db31792b.png
