### ISSUE TITLE
Private Pal (Lite) - Versatile Data Protector

### ISSUE THREAD

**Issue by penguinrouge** [glasklart/hd#2864]
**App Name:** Private Pal (Lite) - Versatile Data Protector
**Bundle ID:** com.miocool.PrivatePalFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490410369">490410369</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/private-pal-lite-versatile-data-protector/id490410369?mt=8&uo=4">https://itunes.apple.com/us/app/private-pal-lite-versatile-data-protector/id490410369?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Miocool Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/miocool-inc/id438868203?uo=4">© Miocool Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/b5/7a/09/b57a0918-764d-3695-2e4e-a1f26c86f062/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32702048-0be6a2c4-c7e1-11e7-9a9a-92a1c24a5fef.png)
https://user-images.githubusercontent.com/2068130/32702048-0be6a2c4-c7e1-11e7-9a9a-92a1c24a5fef.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32702051-19f794ae-c7e1-11e7-8ff5-184156115a23.png
