### ISSUE TITLE
Blockchain Wallet: Bitcoin

### ISSUE THREAD

**Issue by BenChaimberg** [glasklart/hd#2868]
**App Name:** Blockchain Wallet: Bitcoin
**Bundle ID:** com.rainydayapps.Blockchain
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493253309">493253309</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/blockchain-wallet-bitcoin/id493253309?uo=4">https://apps.apple.com/us/app/blockchain-wallet-bitcoin/id493253309?uo=4</a>
**App Version:** 2.14.1
**Seller:** Blockchain-UK Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/blockchain/id838387371?uo=4">© Blockchain</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/94/96/40/94964068-40de-91f6-29b0-0550122cc316/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60124532-17acea80-978a-11e9-8207-b7f8ed2ccb24.png)

**Comment by ethansinjin** [comment]
Icon has changed.
https://itunes.apple.com/us/app/blockchain/id493253309?mt=8&uo=4

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6988625/8d7483fc-da53-11e4-8cf3-91dd8f31b688.png)
https://cloud.githubusercontent.com/assets/2068130/6988625/8d7483fc-da53-11e4-8cf3-91dd8f31b688.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6988632/9f2afbe4-da53-11e4-8fcd-eecebf2cf7e7.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![-large](https://user-images.githubusercontent.com/20930745/60124532-17acea80-978a-11e9-8207-b7f8e![](https://preview.dreamnet.at?image=d2ccb24.png)
https://user-images.githubusercontent.com/20930745/60124532-17acea80-978a-11e9-8207-b7f8ed2ccb24.png

Source:
https://user-images.githubusercontent.com/20930745/60124535-1976ae00-978a-11e9-99c5-633b26e6704e.png
