### ISSUE TITLE
Holy Bible

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#2875]
**App Name:** Holy Bible
**Bundle ID:** com.PeejStudio.HolyBible
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=291877741">291877741</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/holy-bible/id291877741?mt=8&uo=4">https://itunes.apple.com/us/app/holy-bible/id291877741?mt=8&uo=4</a>
**App Version:** 10.0.2
**Seller:** Paul Avery
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/paul-avery/id291864162?uo=4>© Paul Avery</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/99/b9/4d/99b94d49-73de-9cb8-29f2-51b4a8030b69/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19356369/e3a491e0-916d-11e6-9c13-6aea71539e6c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19356369/e3a491e0-916d-11e6-9c13-6aea71539e6c.png)
https://cloud.githubusercontent.com/assets/20930745/19356369/e3a491e0-916d-11e6-9c13-6aea71539e6c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19356385/f3036f80-916d-11e6-8112-10d47aa73301.png
