### ISSUE TITLE
Radio FM, web radio and podcast (info, news, sport, music) - USA and International

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#288]
**App Name:** Radio FM, web radio and podcast (info, news, sport, music) - USA and International
**Bundle ID:** com.orange.fr.LiveRadio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=287955524">287955524</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radio-fm-web-radio-podcast/id287955524?mt=8&uo=4">https://itunes.apple.com/us/app/radio-fm-web-radio-podcast/id287955524?mt=8&uo=4</a>
**App Version:** 3.91
**Seller:** RADIOLINE
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/radioline/id317580246?uo=4>© RADIOLINE</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/a1/15/ea/a115ea77-71bb-cd99-cb20-1d29ea1132cc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19416938/ca5469c6-939e-11e6-9eb0-02e5111b1f7d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19416938/ca5469c6-939e-11e6-9eb0-02e5111b1f7d.png)
https://cloud.githubusercontent.com/assets/20930745/19416938/ca5469c6-939e-11e6-9eb0-02e5111b1f7d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19416942/d865546c-939e-11e6-8a29-9cda7133db12.png
