### ISSUE TITLE
Hangouts

### ISSUE THREAD

**Issue by Expliciate** [glasklart/hd#2883]
**App Name:** Hangouts
**Bundle ID:** com.google.hangouts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=643496868">643496868</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hangouts/id643496868?mt=8&uo=4">https://itunes.apple.com/us/app/hangouts/id643496868?mt=8&uo=4</a>
**App Version:** 5.0.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/03/08/60/03086028-14d5-ade0-482c-da2f0594d2a8/mzl.unojwqgy.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10273195/00c1b73e-6b2d-11e5-8e0f-208ac4234e51.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10273195/00c1b73e-6b2d-11e5-8e0f-208ac4234e51.png)
https://cloud.githubusercontent.com/assets/2068130/10273195/00c1b73e-6b2d-11e5-8e0f-208ac4234e51.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10273202/0f55fad0-6b2d-11e5-9a5e-0bc3ccd03ca1.png
