### ISSUE TITLE
easyJet mobile

### ISSUE THREAD

**Issue by Scalamoosh** [glasklart/hd#2885]
**App Name:** easyJet mobile
**Bundle ID:** com.mttnow.iphone.easyjet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=483568103">483568103</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/easyjet-mobile/id483568103?mt=8&uo=4">https://itunes.apple.com/us/app/easyjet-mobile/id483568103?mt=8&uo=4</a>
**App Version:** 3.9
**Seller:** easyJet plc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/easyjet/id370545896?uo=4>© easyJet</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/04/24/3f/04243f3b-9da5-f132-9e32-8169dbfdc53c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19454152/43a1e19a-94b8-11e6-96f7-489027b9611a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19454152/43a1e19a-94b8-11e6-96f7-489027b9611a.png)
https://cloud.githubusercontent.com/assets/20930745/19454152/43a1e19a-94b8-11e6-96f7-489027b9611a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19454177/610be00a-94b8-11e6-9fee-84096b6b2b7a.png
