### ISSUE TITLE
Fongo - talk and text freely

### ISSUE THREAD

**Issue by Expliciate** [glasklart/hd#2887]
**App Name:** Fongo - talk and text freely
**Bundle ID:** com.fongo.dellvoice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=473770452">473770452</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/fongo-talk-and-text-freely/id473770452?mt=8&uo=4">https://itunes.apple.com/ca/app/fongo-talk-and-text-freely/id473770452?mt=8&uo=4</a>
**App Version:** 3.9.25
**Seller:** Fongo Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/ca/developer/fongo-inc/id473770455?uo=4">© Fongo Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/a9/bc/ff/a9bcff63-9784-7a17-788e-c8de9dca363e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698100-2e636aae-c79f-11e7-9455-bbc3da6a8a44.png)
https://user-images.githubusercontent.com/2068130/32698100-2e636aae-c79f-11e7-9455-bbc3da6a8a44.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32698104-3cc388ae-c79f-11e7-9855-cd37f31b4316.png
