### ISSUE TITLE
IMPOSSIBLE ROAD

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#2893]
**App Name:** IMPOSSIBLE ROAD
**Bundle ID:** com.pixelsontoast.impossibleroad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=608707318">608707318</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/impossible-road/id608707318?mt=8&uo=4">https://itunes.apple.com/us/app/impossible-road/id608707318?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** WONDERFUL LASERS Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wonderful-lasers/id1035355624?uo=4>© WONDERFUL LASERS</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/d4/49/a9/d449a928-8b0d-0bd5-0994-2a571c8fe5e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19628885/7467b250-9968-11e6-8d83-768423066a6d.png)

**Comment by Anonyymikko** [comment]
Hi guys, this one doesn't theme the app icon for me.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19628885/7467b250-9968-11e6-8d83-768423066a6d.png)
https://cloud.githubusercontent.com/assets/20930745/19628885/7467b250-9968-11e6-8d83-768423066a6d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19628889/85bc5a60-9968-11e6-8168-df0797e715dc.png
