### ISSUE TITLE
Gyft - Buy, Send, Upload & Manage Gift Cards

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#2894]
**App Name:** Gyft - Buy, Send, Upload & Manage Gift Cards
**Bundle ID:** com.gyft.gyft
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=558314921">558314921</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gyft-buy-send-upload-manage/id558314921?mt=8&uo=4">https://itunes.apple.com/us/app/gyft-buy-send-upload-manage/id558314921?mt=8&uo=4</a>
**App Version:** 2.2.93
**Seller:** Gyft Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gyft-inc./id558314924?uo=4">© Gyft Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/ba/b5/18/bab518eb-b375-83a0-d470-dac08c516be7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20068739/165fadc6-a51a-11e6-8844-d0de4c07134b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20068739/165fadc6-a51a-11e6-8844-d0de4c07134b.png)
https://cloud.githubusercontent.com/assets/20930745/20068739/165fadc6-a51a-11e6-8844-d0de4c07134b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20068770/3339303e-a51a-11e6-9728-b0f6f9368d03.png
