### ISSUE TITLE
AirPort Utility

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#29]
**App Name:** AirPort Utility
**Bundle ID:** com.apple.airport.mobileairportutility
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427276530">427276530</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/airport-utility/id427276530?mt=8&uo=4">https://itunes.apple.com/us/app/airport-utility/id427276530?mt=8&uo=4</a>
**App Version:** 1.3.4
**Seller:** ITUNES
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/75/92/a4/7592a476-a29c-d747-aea3-8b4122b7b00f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030352/b0739c1e-a363-11e6-9e22-b231c1e4c0d0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20030352/b0739c1e-a363-11e6-9e22-b231c1e4c0d0.png)
https://cloud.githubusercontent.com/assets/20930745/20030352/b0739c1e-a363-11e6-9e22-b231c1e4c0d0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20030359/c5aabcf2-a363-11e6-95c2-50a83fb5b25b.png
