### ISSUE TITLE
Livestream

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#290]
**App Name:** Livestream
**Bundle ID:** com.livestream.new
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493086499">493086499</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/livestream/id493086499?mt=8&uo=4">https://itunes.apple.com/us/app/livestream/id493086499?mt=8&uo=4</a>
**App Version:** 3.8.10
**Seller:** Livestream LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/livestream/id379623632?uo=4>© Livestream</a>
**Supported Devices:** iPhone6, iPhone4, iPadThirdGen, iPadThirdGen4G, iPadMini, iPhone5s, iPhone5c, iPhone6Plus, iPadFourthGen, iPhone5, iPadFourthGen4G, iPadMini4G, iPad23G, iPad2Wifi, iPhone4S, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/a8/9c/16/a89c165e-aa4a-6272-4980-ff7c6c958026/mzl.qlcnjrlx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8729923/40399cfc-2bee-11e5-8bad-732b893db2b2.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8729923/40399cfc-2bee-11e5-8bad-732b893db2b2.png)
https://cloud.githubusercontent.com/assets/10730122/8729923/40399cfc-2bee-11e5-8bad-732b893db2b2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8729919/3d2810f2-2bee-11e5-9960-677bf5f8d482.png

**Comment by dreamnet** [comment]
Seems that this app dosen't exist anymore - trying the rebuild the data above. We leave it in the IconBundles.

**Comment by Trubbel** [comment]
@dreamnet I'm sorry, I forgot to mention that the bundle ID has changed to `com.livestream.new`.

**Comment by dreamnet** [comment]
@Trubbel Ah, OK, the we need to rename this too.

**Comment by ivanov007** [comment]
hold on, I've found that bundle ID is for 493086499

**Comment by dreamnet** [comment]
Alright, then I remove `379623629` and add `493086499`.
