### ISSUE TITLE
VR Mobiili

### ISSUE THREAD

**Issue by mrsmiggins** [glasklart/hd#2900]
**App Name:** VR Mobiili
**Bundle ID:** com.accenture.VRMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=623736563">623736563</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vr-mobiili/id623736563?mt=8&uo=4">https://itunes.apple.com/us/app/vr-mobiili/id623736563?mt=8&uo=4</a>
**App Version:** 1.5.5
**Seller:** VR-Yhtyma Oy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vr/id480147979?uo=4">© VR</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/d3/10/ba/d310ba30-1f88-e89e-063e-c8374f4199d0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20068072/b62c4ccc-a517-11e6-9774-95e20e00889c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20068072/b62c4ccc-a517-11e6-9774-95e20e00889c.png)
https://cloud.githubusercontent.com/assets/20930745/20068072/b62c4ccc-a517-11e6-9774-95e20e00889c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20068098/cd5f1dd4-a517-11e6-8bea-794b62166995.png
