### ISSUE TITLE
Tiki Totems Premium

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#2901]
**App Name:** Tiki Totems Premium
**Bundle ID:** com.spokko.TikiPremium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=360807592">360807592</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tiki-totems-premium/id360807592?mt=8&uo=4">https://itunes.apple.com/us/app/tiki-totems-premium/id360807592?mt=8&uo=4</a>
**App Version:** 1.5.3
**Seller:** Rafal Staszewski
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rafal-staszewski/id298685318?uo=4">© Rafal Staszewski</a>
**Supported Devices:** iPhoneFirstGen-iPhone, iPodTouchFirstGen-iPod-touch, iPodTouchSecondGen-iPod-touch-with-mic, iPhone3G-iPhone-3G, iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple/v4/ab/b2/c8/abb2c806-a5b2-a7e5-ee79-709cd1527cac/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39346343-f059d26c-49ed-11e8-9a29-04b81170881b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39346343-f059d26c-49ed-11e8-9a29-04b81170881b.png)
https://user-images.githubusercontent.com/2068130/39346343-f059d26c-49ed-11e8-9a29-04b81170881b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39346355-fe5815a4-49ed-11e8-8c4b-943335fc2a85.png
