### ISSUE TITLE
ClipBook - BookMarker & Sentence Collector

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2904]
**App Name:** ClipBook - BookMarker & Sentence Collector
**Bundle ID:** com.theclipbookapp.ClipBook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=593243819">593243819</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clipbook-bookmarker-sentence/id593243819?mt=8&uo=4">https://itunes.apple.com/us/app/clipbook-bookmarker-sentence/id593243819?mt=8&uo=4</a>
**App Version:** 1.99.1
**Seller:** JUNG EUI HYUNG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jung-eui-hyung/id627733674?uo=4">© JUNG EUI HYUNG</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/6c/52/08/6c520812-95c4-45af-5f6a-a84ed4ff4a4f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20068969/f63e763e-a51a-11e6-9555-ffca9ba6e3a4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20068969/f63e763e-a51a-11e6-9555-ffca9ba6e3a4.png)
https://cloud.githubusercontent.com/assets/20930745/20068969/f63e763e-a51a-11e6-9555-ffca9ba6e3a4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20068993/0f71e8f2-a51b-11e6-890a-88ab141dd828.png
