### ISSUE TITLE
Dots (Pixel Art)

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2905]
**App Name:** Dots (Pixel Art)
**Bundle ID:** com.kobaltlab.Dots
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=582232939">582232939</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dots-pixel-art/id582232939?mt=8&uo=4">https://itunes.apple.com/us/app/dots-pixel-art/id582232939?mt=8&uo=4</a>
**App Version:** 2.2.2
**Seller:** kobaltlab Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/beyondf/id500633325?uo=4">© beyondf</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/ce/65/73/ce6573fe-adde-ba45-e7b1-890ae7cb2668/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698196-57e29948-c7a1-11e7-83f1-0d68f1831864.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698196-57e29948-c7a1-11e7-83f1-0d68f1831864.png)
https://user-images.githubusercontent.com/2068130/32698196-57e29948-c7a1-11e7-83f1-0d68f1831864.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32698198-66b0caa8-c7a1-11e7-8f7a-9e571f5b3991.png
