### ISSUE TITLE
Lick of the Day

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2906]
**App Name:** Lick of the Day
**Bundle ID:** com.agilepartners.gwlod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=371728474">371728474</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lick-of-the-day/id371728474?mt=8&uo=4">https://itunes.apple.com/us/app/lick-of-the-day/id371728474?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Agile Partners Technologies, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/agile-partners/id284962371?uo=4">© Agile Partners</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/e0/39/f2/e039f219-afc7-1dee-bbc4-8975ec01ef18/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20069273/3ab1f0f6-a51c-11e6-9934-302fe17a33ce.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20069273/3ab1f0f6-a51c-11e6-9934-302fe17a33ce.png)
https://cloud.githubusercontent.com/assets/20930745/20069273/3ab1f0f6-a51c-11e6-9934-302fe17a33ce.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20069309/5632085c-a51c-11e6-87bd-4002ebb29333.png
