### ISSUE TITLE
HandyTicket Deutschland

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#2911]
**App Name:** HandyTicket Deutschland
**Bundle ID:** de.handyticket.HTDeutschland
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=397986271">397986271</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/handyticket-deutschland/id397986271?uo=4">https://apps.apple.com/us/app/handyticket-deutschland/id397986271?uo=4</a>
**App Version:** 2.7.11
**Seller:** HanseCom GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hansecom-gmbh/id397986274?uo=4">© HanseCom GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/a6/23/3c/a6233c71-1c5a-064b-9a5c-abce0d814df9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772860-a57ac500-a0fc-11e9-9165-b8297fe04d29.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772860-a57ac500-a0fc-11e9-9165-b8297fe04d29.png)
https://user-images.githubusercontent.com/2068130/60772860-a57ac500-a0fc-11e9-9165-b8297fe04d29.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60772863-b62b3b00-a0fc-11e9-9e21-1d5bba1cf0b0.png
