### ISSUE TITLE
Horn™

### ISSUE THREAD

**Issue by justoned420** [glasklart/hd#2914]
**App Name:** Horn™
**Bundle ID:** com.zynga.phosphor.horn.1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=549350579">549350579</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/horn/id549350579?mt=8&uo=4">https://itunes.apple.com/us/app/horn/id549350579?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Phosphor Games, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/phosphor-games-studio-llc/id452823335?uo=4">© Phosphor Games Studio, LLC</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/3e/dc/fc/3edcfc34-95b2-6b2f-4ba4-940c21f02cd9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32697650-8f01c888-c795-11e7-9e50-c922ade0768b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32697650-8f01c888-c795-11e7-9e50-c922ade0768b.png)
https://user-images.githubusercontent.com/2068130/32697650-8f01c888-c795-11e7-9e50-c922ade0768b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32697651-a2d3d63a-c795-11e7-8daa-26679bba9fd9.png
