### ISSUE TITLE
FallDown! 2

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#2918]
**App Name:** FallDown! 2
**Bundle ID:** com.hannesjensen.FallDown2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=624777107">624777107</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/falldown!-2/id624777107?mt=8&uo=4">https://itunes.apple.com/us/app/falldown!-2/id624777107?mt=8&uo=4</a>
**App Version:** 1.81
**Seller:** Hannes Jensen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hannes-jensen/id323493589?uo=4>© Hannes Jensen</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/b3/47/bd/b347bdd4-f7ef-2389-cdf4-0cb5926eff4c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13372442/40c9926a-dd43-11e5-98df-3eb79abd5a48.png)

**Comment by Anuskuss** [comment]
Could someone make this icon more like the first installment of [FallDown!](https://github.com/glasklart/hd/issues/2175)?

**Comment by ivanov007** [comment]
I think #2175 Falldown! is the one that should be modifyed

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13372442/40c9926a-dd43-11e5-98df-3eb79abd5a48.png)
https://cloud.githubusercontent.com/assets/2068130/13372442/40c9926a-dd43-11e5-98df-3eb79abd5a48.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13372443/509efda6-dd43-11e5-8006-30791302b02d.png
