### ISSUE TITLE
Wikia Game Guides - Walkthroughs, Tips, and Cheats

### ISSUE THREAD

**Issue by josephis5** [glasklart/hd#2919]
**App Name:** Wikia Game Guides - Walkthroughs, Tips, and Cheats
**Bundle ID:** com.wikia.app.GameGuides
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=422467074">422467074</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wikia-game-guides-walkthroughs-tips-and-cheats/id422467074?mt=8&uo=4">https://itunes.apple.com/us/app/wikia-game-guides-walkthroughs-tips-and-cheats/id422467074?mt=8&uo=4</a>
**App Version:** 3.0.4
**Seller:** Wikia Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wikia-inc/id422467077?uo=4">© Wikia, Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/62/9a/7b/629a7bcd-947a-7482-5927-f32b224d1284/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698271-e6330a4c-c7a2-11e7-9c45-a3e25a7d44bc.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698271-e6330a4c-c7a2-11e7-9c45-a3e25a7d44bc.png)
https://user-images.githubusercontent.com/2068130/32698271-e6330a4c-c7a2-11e7-9c45-a3e25a7d44bc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32698274-f468009a-c7a2-11e7-93d3-b58880dd2146.png
