### ISSUE TITLE
Visa QIWI Wallet

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#292]
**App Name:** Visa QIWI Wallet
**Bundle ID:** ru.qiwi.QIWI
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=350905609">350905609</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/visa-qiwi-wallet/id350905609?mt=8&uo=4">https://itunes.apple.com/us/app/visa-qiwi-wallet/id350905609?mt=8&uo=4</a>
**App Version:** 5.8.4
**Seller:** "QIWI wallet" Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/qiwi-wallet-ltd/id315776023?uo=4>© "QIWI wallet" Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/ff/30/55/ff3055e9-d9c2-fc58-c530-f89dcf640296/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19074786/35ac37be-8a42-11e6-8e40-67dcb9d6fdbc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19074786/35ac37be-8a42-11e6-8e40-67dcb9d6fdbc.png)
https://cloud.githubusercontent.com/assets/20930745/19074786/35ac37be-8a42-11e6-8e40-67dcb9d6fdbc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19074795/4383dc5c-8a42-11e6-9003-16e5215923aa.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19074988/340beb1a-8a43-11e6-850f-c7bc99f649ba.png)
https://cloud.githubusercontent.com/assets/20930745/19074988/340beb1a-8a43-11e6-850f-c7bc99f649ba.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19075001/4425f98c-8a43-11e6-9a5a-70bdc676caab.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19075051/7acda6b0-8a43-11e6-8f6f-32b85b09d903.png)
https://cloud.githubusercontent.com/assets/20930745/19075051/7acda6b0-8a43-11e6-8f6f-32b85b09d903.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19075064/911c2e78-8a43-11e6-8678-f99824b250e1.png
