### ISSUE TITLE
Chrono24

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#2922]
**App Name:** Chrono24
**Bundle ID:** com.chrono24.Chrono24
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=472912032">472912032</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chrono24/id472912032?mt=8&uo=4">https://itunes.apple.com/us/app/chrono24/id472912032?mt=8&uo=4</a>
**App Version:** 3.7.1
**Seller:** Chrono24 GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chrono24-gmbh/id472912035?uo=4">© Chrono24 GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/92/8d/8f/928d8f9b-1fb8-e1c5-4e38-0121eda0973c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20067247/ae7c67b2-a514-11e6-8014-5666f10e6d4c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20067247/ae7c67b2-a514-11e6-8014-5666f10e6d4c.png)
https://cloud.githubusercontent.com/assets/20930745/20067247/ae7c67b2-a514-11e6-8014-5666f10e6d4c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20067276/cbf45f0c-a514-11e6-9b13-a2ea26abfa8d.png
