### ISSUE TITLE
Runtastic Road Bike GPS Cycling Computer, Ride and Route Tracker

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#2923]
**App Name:** Runtastic Road Bike GPS Cycling Computer, Ride and Route Tracker
**Bundle ID:** com.runtastic.iphone.roadbike.lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467567868">467567868</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-road-bike-gps-cycling/id467567868?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-road-bike-gps-cycling/id467567868?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPhone4, iPhone5, iPodTouchFifthGen, iPadMini, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen4G, iPodTouchSixthGen, iPadFourthGen4G, iPhone6, iPadFourthGen, iPadThirdGen, iPhone6Plus, iPadMini4G, iPhone5s, iPhone5c
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/db/9a/39/db9a3994-da59-3699-65d3-5b2ac10756d8/mzl.aniovdtw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9273157/181aff92-428a-11e5-9d98-cc85ae7904af.png)

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9273157/181aff92-428a-11e5-9d98-cc85ae7904af.png)
https://cloud.githubusercontent.com/assets/2068130/9273157/181aff92-428a-11e5-9d98-cc85ae7904af.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9273165/2a2aff98-428a-11e5-9097-bea55b0569f6.png
