### ISSUE TITLE
Grand Theft Auto III

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#293]
**App Name:** Grand Theft Auto III
**Bundle ID:** com.rockstargames.gta3ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479662730">479662730</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grand-theft-auto-iii/id479662730?mt=8&uo=4">https://itunes.apple.com/us/app/grand-theft-auto-iii/id479662730?mt=8&uo=4</a>
**App Version:** 1.3.5
**Seller:** Rockstar Games, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rockstar-games/id330049731?uo=4">© Rockstar Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/23/38/34/233834ef-88f5-9122-7f21-50913b6a4995/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20013389/3aa95e7a-a2b3-11e6-9af0-af6d5b20cac9.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10508662/ba4a6842-7328-11e5-8ea0-d88e7b8ac65a.png)
https://cloud.githubusercontent.com/assets/10730122/10508662/ba4a6842-7328-11e5-8ea0-d88e7b8ac65a.png

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10508654/aefa8206-7328-11e5-89b9-6aa23ddc46e5.png)
https://cloud.githubusercontent.com/assets/10730122/10508654/aefa8206-7328-11e5-89b9-6aa23ddc46e5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10508643/a1db673e-7328-11e5-839a-36dc2dcb1a0d.png

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20013389/3aa95e7a-a2b3-11e6-9af0-af6d5b20cac9.png)
https://cloud.githubusercontent.com/assets/20930745/20013389/3aa95e7a-a2b3-11e6-9af0-af6d5b20cac9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/20930745/20013400/46a56af2-a2b3-11e6-84c9-52901d9d3a05.png
