### ISSUE TITLE
Mushroom Wars Mini

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2935]
**App Name:** Mushroom Wars Mini
**Bundle ID:** com.i-free.mushroom.wars.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=628431624">628431624</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mushroom-wars-mini/id628431624?mt=8&uo=4">https://itunes.apple.com/us/app/mushroom-wars-mini/id628431624?mt=8&uo=4</a>
**App Version:** 1.14
**Seller:** Zillion Whales Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zillion-whales/id828362722?uo=4>© Zillion Whales</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/57/e7/90/57e790fb-43c6-f0dd-b695-84dbb5548b6b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18912376/670394ca-8582-11e6-86eb-4e9d9a3f3a33.png)

**Comment by Anuskuss** [comment]
Needs update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18912376/670394ca-8582-11e6-86eb-4e9d9a3f3a33.png)
https://cloud.githubusercontent.com/assets/20930745/18912376/670394ca-8582-11e6-86eb-4e9d9a3f3a33.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18912405/82e7c53a-8582-11e6-9668-1228f3b756ef.png
