### ISSUE TITLE
Last Call

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#2937]
**App Name:** Last Call
**Bundle ID:** com.avvo.LastCall
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288841503">288841503</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/last-call/id288841503?mt=8&uo=4">https://itunes.apple.com/us/app/last-call/id288841503?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Avvo, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/avvo-inc/id288841506?uo=4">© Avvo, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/b3/d6/0e/b3d60e9b-f4a7-b1fd-d6d7-5d85366ee560/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698227-1c7efc88-c7a2-11e7-8867-6e65ff2dd3ed.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32698227-1c7efc88-c7a2-11e7-8867-6e65ff2dd3ed.png)
https://user-images.githubusercontent.com/2068130/32698227-1c7efc88-c7a2-11e7-8867-6e65ff2dd3ed.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32698229-2ac74368-c7a2-11e7-8e7b-23ebd22859d4.png
