### ISSUE TITLE
Coach.me - Goal Tracking, Habits & Motivation

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#2940]
**App Name:** Coach.me - Goal Tracking, Habits & Motivation
**Bundle ID:** com.liftworldwide.Lift
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=530911645">530911645</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/coach-me-goal-tracking-habits-motivation/id530911645?mt=8&uo=4">https://itunes.apple.com/us/app/coach-me-goal-tracking-habits-motivation/id530911645?mt=8&uo=4</a>
**App Version:** 2017.7.16
**Seller:** Lift Worldwide, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lift-worldwide/id530911648?uo=4">© Lift Worldwide</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/07/22/4d/07224d16-e460-a313-de34-0036560505aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32697701-d4a9e98c-c796-11e7-95c0-219319ea43d7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32697701-d4a9e98c-c796-11e7-95c0-219319ea43d7.png)
https://user-images.githubusercontent.com/2068130/32697701-d4a9e98c-c796-11e7-95c0-219319ea43d7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32697707-e738f9a8-c796-11e7-885b-b9b03ebef465.png
