### ISSUE TITLE
Headspace.com - meditation & mindfulness

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#2941]
**App Name:** Headspace.com - meditation & mindfulness
**Bundle ID:** com.getsomeheadspace.headspace
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493145008">493145008</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/headspace.com-meditation-mindfulness/id493145008?mt=8&uo=4">https://itunes.apple.com/us/app/headspace.com-meditation-mindfulness/id493145008?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Headspace meditation limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/headspace-meditation-limited/id384434796?uo=4>© Headspace meditation limited</a>
**Supported Devices:** iPadThirdGen4G, iPadFourthGen, iPadMini4G, iPhone5, iPad2Wifi, iPhone6Plus, iPadThirdGen, iPodTouchFifthGen, iPhone5c, iPhone4S, iPhone6, iPadFourthGen4G, iPhone5s, iPhone4, iPad23G, iPadMini
**Original Artwork:**
<img src="http://a149.phobos.apple.com/us/r30/Purple5/v4/84/86/e1/8486e11e-8c36-1ff7-9997-02c9e2759029/mzl.rtzgjqzo.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6991592/0c5ec93a-da9e-11e4-9315-b3de344ea56b.png)

**Comment by ethansinjin** [comment]
App Icon has been updated.
https://itunes.apple.com/us/app/headspace.com-meditation-mindfulness/id493145008?mt=8

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6991592/0c5ec93a-da9e-11e4-9315-b3de344ea56b.png)
https://cloud.githubusercontent.com/assets/2068130/6991592/0c5ec93a-da9e-11e4-9315-b3de344ea56b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6991597/1dc337d8-da9e-11e4-99a8-e7dbf1684cad.png
