### ISSUE TITLE
Buycott

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#2942]
**App Name:** Buycott - Barcode Scanner & QR Bar Code Scanner
**Bundle ID:** com.buycott
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=585933440">585933440</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/buycott-barcode-scanner-qr/id585933440?mt=8&uo=4">https://itunes.apple.com/us/app/buycott-barcode-scanner-qr/id585933440?mt=8&uo=4</a>
**App Version:** 3.1.3
**Seller:** Buycott Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/buycott-inc./id585933443?uo=4>© Buycott Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple18/v4/75/4b/f9/754bf98c-aabc-7235-cda1-b45e9def935e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19224004/6d32ea78-8e7c-11e6-9c20-cb6e3ed67abc.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19224004/6d32ea78-8e7c-11e6-9c20-cb6e3ed67abc.png)
https://cloud.githubusercontent.com/assets/10730122/19224004/6d32ea78-8e7c-11e6-9c20-cb6e3ed67abc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19224003/6d318b74-8e7c-11e6-86e7-0690b08826bd.png
