### ISSUE TITLE
Wikiweb: Visual Wikipedia™ Reader

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#2944]
**App Name:** Wikiweb: Visual Wikipedia™ Reader
**Bundle ID:** com.friendsoftheweb.wikiweb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=499345601">499345601</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wikiweb-visual-wikipedia-reader/id499345601?mt=8&uo=4">https://itunes.apple.com/us/app/wikiweb-visual-wikipedia-reader/id499345601?mt=8&uo=4</a>
**App Version:** 1.4.3
**Seller:** Friends of The Web, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/friends-of-the-web-llc/id466112187?uo=4>© Friends of The Web, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/1c/8f/c9/1c8fc90e-067a-25c4-7bb1-83db713a38a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18658493/e52bed28-7f03-11e6-9823-a986f78d8e09.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** Wikiweb: Visual Wikipedia™ Reader
**Bundle ID:** com.friendsoftheweb.wikiweb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=499345601">499345601</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wikiweb-visual-wikipedia-reader/id499345601?mt=8&uo=4">https://itunes.apple.com/us/app/wikiweb-visual-wikipedia-reader/id499345601?mt=8&uo=4</a>
**App Version:** 1.4.3
**Seller:** Friends of The Web, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/friends-of-the-web-llc/id466112187?uo=4>© Friends of The Web, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/1c/8f/c9/1c8fc90e-067a-25c4-7bb1-83db713a38a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18658493/e52bed28-7f03-11e6-9823-a986f78d8e09.png)
https://cloud.githubusercontent.com/assets/2068130/18658493/e52bed28-7f03-11e6-9823-a986f78d8e09.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18658501/f4434838-7f03-11e6-97ff-56c98f3db2d5.png
