### ISSUE TITLE
Circles Memory Game

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#2947]
**App Name:** Circles Memory Game
**Bundle ID:** com.snowman.game.circles
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586168287">586168287</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/circles-memory-game/id586168287?mt=8&uo=4">https://itunes.apple.com/us/app/circles-memory-game/id586168287?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Snowman
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/snowman/id524873456?uo=4">© Snowman</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple2/v4/c5/d2/7d/c5d27d8b-c624-051a-8a6e-078220b16ff5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20069713/fbe486e8-a51d-11e6-8a90-b75bada4ce11.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20069713/fbe486e8-a51d-11e6-8a90-b75bada4ce11.png)
https://cloud.githubusercontent.com/assets/20930745/20069713/fbe486e8-a51d-11e6-8a90-b75bada4ce11.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20069750/1fdfe7e0-a51e-11e6-84c1-a78e9061491e.png
