### ISSUE TITLE
Clever Clues

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#2948]
**App Name:** Clever Clues
**Bundle ID:** com.dexagogo.cleverclues
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=552781624">552781624</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clever-clues/id552781624?mt=8&uo=4">https://itunes.apple.com/us/app/clever-clues/id552781624?mt=8&uo=4</a>
**App Version:** 1.3.6
**Seller:** Andrew Tetlaw
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/andrew-tetlaw/id552781627?uo=4">© Andrew Tetlaw</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/1b/c5/c7/1bc5c7ef-70da-dc62-55be-9a256709897b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32697947-db39e75c-c79b-11e7-893d-b3d8e3ab14aa.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32697947-db39e75c-c79b-11e7-893d-b3d8e3ab14aa.png)
https://user-images.githubusercontent.com/2068130/32697947-db39e75c-c79b-11e7-893d-b3d8e3ab14aa.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32697949-e9724f44-c79b-11e7-96e5-26ebfec18958.png
