### ISSUE TITLE
ownCloud

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#2949]
**App Name:** ownCloud
**Bundle ID:** com.owncloud.iOSmobileapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=543672169">543672169</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/owncloud/id543672169?mt=8&uo=4">https://itunes.apple.com/us/app/owncloud/id543672169?mt=8&uo=4</a>
**App Version:** 3.6.2
**Seller:** ownCloud Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/owncloud-inc/id543672172?uo=4">© ownCloud, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple127/v4/08/76/23/087623d6-3d7e-c6ff-b666-235d27a189ac/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32697985-58ae66e0-c79c-11e7-8217-b67ad1ca81c3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32697985-58ae66e0-c79c-11e7-8217-b67ad1ca81c3.png)
https://user-images.githubusercontent.com/2068130/32697985-58ae66e0-c79c-11e7-8217-b67ad1ca81c3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32697990-67d418a4-c79c-11e7-9102-e55f8e37a924.png
