### ISSUE TITLE
Meme Producer - FREE Meme Maker/Generator

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#2957]
**App Name:** Meme Producer - FREE Meme Maker/Generator
**Bundle ID:** com.halfmagnet.memeproducer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=560797323">560797323</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/meme-producer-free-meme-maker-generator/id560797323?mt=8&uo=4">https://itunes.apple.com/us/app/meme-producer-free-meme-maker-generator/id560797323?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Jairo A. Cepeda
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/halfmagnet/id542717896?uo=4">© HalfMagnet</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/ae/35/71/ae3571de-eed0-bd8c-5027-58b26587dc0c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32697513-4756bd8e-c792-11e7-96ad-2bbbada870b4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32697513-4756bd8e-c792-11e7-96ad-2bbbada870b4.png)
https://user-images.githubusercontent.com/2068130/32697513-4756bd8e-c792-11e7-96ad-2bbbada870b4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32697515-5804a93e-c792-11e7-9248-2d619d7408df.png
