### ISSUE TITLE
Fitocracy - Workout Exercise Log and personal fitness coach for weight loss

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#296]
**App Name:** Fitocracy - Workout Exercise Log and personal fitness coach for weight loss
**Bundle ID:** com.release.fitocracy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=509253726">509253726</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fitocracy-workout-exercise/id509253726?mt=8&uo=4">https://itunes.apple.com/us/app/fitocracy-workout-exercise/id509253726?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Fitocracy Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fitocracy-inc./id509253949?uo=4>© Fitocracy, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/fb/7d/e2/fb7de2a4-ca73-5048-5f2d-435631e591ff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402487/a0ccf912-9261-11e6-8ff5-9e5aeffe5ff6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402487/a0ccf912-9261-11e6-8ff5-9e5aeffe5ff6.png)
https://cloud.githubusercontent.com/assets/20930745/19402487/a0ccf912-9261-11e6-8ff5-9e5aeffe5ff6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19402500/b2ccd2e0-9261-11e6-993e-8cf055a8e59f.png
