### ISSUE TITLE
Dumb Ways to Die

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2964]
**App Name:** Dumb Ways to Die
**Bundle ID:** au.com.metro.DumbWaysToDie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=639930688">639930688</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dumb-ways-to-die/id639930688?mt=8&uo=4">https://itunes.apple.com/us/app/dumb-ways-to-die/id639930688?mt=8&uo=4</a>
**App Version:** 2.4.0
**Seller:** Metro Trains Melbourne Pty Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/metro-trains-melbourne-pty-ltd/id608701664?uo=4">© Metro Trains Melbourne Pty Ltd</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/2e/63/d1/2e63d1a1-184b-9fa6-60cb-c63115315f80/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29579589-48bb893e-8741-11e7-80ff-ba3c7698c03b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29579531-1a5949be-8741-11e7-828c-48766d4e563c.png)
https://user-images.githubusercontent.com/3090247/29579531-1a5949be-8741-11e7-828c-48766d4e563c.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29579532-1a5c5d0c-8741-11e7-9008-2ee1cc6bed7e.png

**Comment by ivanov007** [comment]
needs update

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29579589-48bb893e-8741-11e7-80ff-ba3c7698c03b.png)
https://user-images.githubusercontent.com/3090247/29579589-48bb893e-8741-11e7-80ff-ba3c7698c03b.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29579590-48e62df6-8741-11e7-8c50-3092dd7ab07c.png
