### ISSUE TITLE
ASKfm: Ask Anonymous Questions

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#2966]
**App Name:** ASKfm: Ask Anonymous Questions
**Bundle ID:** fm.ask.askfm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=635896473">635896473</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/askfm-ask-anonymous-questions/id635896473?mt=8&uo=4">https://itunes.apple.com/us/app/askfm-ask-anonymous-questions/id635896473?mt=8&uo=4</a>
**App Version:** 4.15
**Seller:** Ask.fm SIA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ask-fm/id635896476?uo=4">© Ask.fm</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/0d/57/9d/0d579d29-f71d-b1bc-3d3a-3ab16be137c4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38456433-0bb5b742-3a85-11e8-96aa-65d044208704.png)

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12333969/971b9186-baf7-11e5-9885-dd7a111df002.png)
https://cloud.githubusercontent.com/assets/10730122/12333969/971b9186-baf7-11e5-9885-dd7a111df002.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12333970/971ec61c-baf7-11e5-8710-b8efff650f3d.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38456433-0bb5b742-3a85-11e8-96aa-65d044208704.png)
https://user-images.githubusercontent.com/20930745/38456433-0bb5b742-3a85-11e8-96aa-65d044208704.png

Source:
https://user-images.githubusercontent.com/20930745/38456440-1b54c044-3a85-11e8-8b44-c2abdf4f53ce.png
