### ISSUE TITLE
Yell - Yellow Pages UK

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#2980]
**App Name:** Yell - Yellow Pages UK
**Bundle ID:** com.mobilepeople.YellHybrid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=329334877">329334877</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yell-yellow-pages-uk/id329334877?mt=8&uo=4">https://itunes.apple.com/us/app/yell-yellow-pages-uk/id329334877?mt=8&uo=4</a>
**App Version:** 5.1.0
**Seller:** hibu (UK) Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hibu-uk-limited/id329334880?uo=4">© hibu (UK) Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/9d/18/f3/9d18f34d-0b1f-0224-d21e-68d15fb5c4e7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20109240/6f507d1e-a5df-11e6-818e-4a37e8dd013b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20109240/6f507d1e-a5df-11e6-818e-4a37e8dd013b.png)
https://cloud.githubusercontent.com/assets/20930745/20109240/6f507d1e-a5df-11e6-818e-4a37e8dd013b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20109254/88395710-a5df-11e6-99c0-e61af391f54d.png
