### ISSUE TITLE
Gliph

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#299]
**App Name:** Gliph
**Bundle ID:** ph.gli.gliph
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=501269250">501269250</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gliph/id501269250?mt=8&uo=4">https://itunes.apple.com/us/app/gliph/id501269250?mt=8&uo=4</a>
**App Version:** 2.04
**Seller:** Gliph, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gliph-inc./id501269253?uo=4>© Gliph, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/5c/33/c7/5c33c749-0d95-a93f-a10c-017e4a640ea0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19075210/33a51268-8a44-11e6-96e3-6465113a580e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19075210/33a51268-8a44-11e6-96e3-6465113a580e.png)
https://cloud.githubusercontent.com/assets/20930745/19075210/33a51268-8a44-11e6-96e3-6465113a580e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19075229/452a262c-8a44-11e6-9d93-d44a35efd643.png
