### ISSUE TITLE
Calcbot — The Intelligent Calculator and Unit Converter

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#3]
**App Name:** Calcbot — The Intelligent Calculator and Unit Converter
**Bundle ID:** com.tapbots.Calcbot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376694347">376694347</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calcbot-intelligent-calculator/id376694347?mt=8&uo=4">https://itunes.apple.com/us/app/calcbot-intelligent-calculator/id376694347?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Tapbots
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tapbots/id293642940?uo=4>© Tapbots</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/93/a8/9f/93a89f0b-e2ff-0886-0080-653ea5d260e9/mzl.seisjckr.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10789462/e180cdd4-7d7d-11e5-8261-47fea87c4c46.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10789462/e180cdd4-7d7d-11e5-8261-47fea87c4c46.png)
https://cloud.githubusercontent.com/assets/10730122/10789462/e180cdd4-7d7d-11e5-8261-47fea87c4c46.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10789459/dec18ca0-7d7d-11e5-8f83-3913820eb239.png
