### ISSUE TITLE
My Smoothie

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#300]
**App Name:** My Smoothie
**Bundle ID:** com.appsmyth.mobile.smoothieking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448122894">448122894</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-smoothie/id448122894?mt=8&uo=4">https://itunes.apple.com/us/app/my-smoothie/id448122894?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Relevant Mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/relevant/id475337047?uo=4>© Relevant</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/9e/41/69/9e416941-82f3-6b2b-3a02-83af16a05cfb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402631/4f5747e4-9262-11e6-8904-9c1bbe04713a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402631/4f5747e4-9262-11e6-8904-9c1bbe04713a.png)
https://cloud.githubusercontent.com/assets/20930745/19402631/4f5747e4-9262-11e6-8904-9c1bbe04713a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19402638/60b7359e-9262-11e6-9750-721c268899e6.png
