### ISSUE TITLE
Run Training Pro

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#301]
**App Name:** Run Training Pro
**Bundle ID:** com.dworks.runtraining
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426918491">426918491</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/run-training-pro/id426918491?mt=8&uo=4">https://itunes.apple.com/us/app/run-training-pro/id426918491?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Deltaworks Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/deltaworks/id361115219?uo=4>© Deltaworks</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/fa/66/35/fa6635c2-95e2-5f8e-98ff-db93593f922f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19416997/2ada4b9c-93a1-11e6-8f45-b6151991c80d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19416997/2ada4b9c-93a1-11e6-8f45-b6151991c80d.png)
https://cloud.githubusercontent.com/assets/20930745/19416997/2ada4b9c-93a1-11e6-8f45-b6151991c80d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19417004/42feae84-93a1-11e6-8ce0-0db26432e3ac.png
