### ISSUE TITLE
Auchan Drive

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#3023]
**App Name:** Auchan Drive
**Bundle ID:** fr.auchandrive.vad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=399777219">399777219</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/auchan-drive/id399777219?mt=8&uo=4">https://itunes.apple.com/gb/app/auchan-drive/id399777219?mt=8&uo=4</a>
**App Version:** 3.20.1
**Seller:** AUCHAN FRANCE
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/auchan/id342888608?uo=4">© Auchan</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/8b/b9/8c/8bb98c00-2286-cc81-a574-9f8cc07f6293/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38456373-7cc0a43e-3a84-11e8-934f-635100bc9fd2.png)

**Comment by dreamnet** [comment]
Icon needs an update.
