### ISSUE TITLE
Apple Developer

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#3032]
**App Name:** Apple Developer
**Bundle ID:** developer.apple.wwdc-Release
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=640199958">640199958</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/apple-developer/id640199958?uo=4">https://apps.apple.com/us/app/apple-developer/id640199958?uo=4</a>
**App Version:** 8.0
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/96/e9/de/96e9dea6-de5a-835e-de4a-c71124f03430/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69478024-abdcb580-0ded-11ea-8f64-4848599071c2.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69478024-abdcb580-0ded-11ea-8f64-4848599071c2.png)
https://user-images.githubusercontent.com/2068130/69478024-abdcb580-0ded-11ea-8f64-4848599071c2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/69478031-bbf49500-0ded-11ea-82d9-ae04186639fb.png
