### ISSUE TITLE
oneSafe - Premium password manager

### ISSUE THREAD

**Issue by lshishido03** [glasklart/hd#3043]
**App Name:** oneSafe - Premium password manager
**Bundle ID:** com.lunabee.sg.onesafe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=455190486">455190486</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/onesafe-premium-password-manager/id455190486?mt=8&uo=4">https://itunes.apple.com/us/app/onesafe-premium-password-manager/id455190486?mt=8&uo=4</a>
**App Version:** 3.2.3
**Seller:** Lunabee Pte. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lunabee-pte.-ltd./id455190489?uo=4>© Lunabee Pte. Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/bc/22/65/bc2265e9-5e80-fea8-e88c-238749e87070/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11019393/ad2f3e76-85f7-11e5-8167-6b5756c46341.png)

**Comment by Anuskuss** [comment]
**New Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/bc/22/65/bc2265e9-5e80-fea8-e88c-238749e87070/source/512x512bb.jpg" width="150" height="150" />

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11019393/ad2f3e76-85f7-11e5-8167-6b5756c46341.png)
https://cloud.githubusercontent.com/assets/2068130/11019393/ad2f3e76-85f7-11e5-8167-6b5756c46341.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11019396/bbf7f790-85f7-11e5-89d5-2df5c5e07c15.png
