### ISSUE TITLE
VSCO

### ISSUE THREAD

**Issue by johnnyhundreds** [glasklart/hd#3046]
**App Name:** VSCO
**Bundle ID:** co.visualsupply.cam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=588013838">588013838</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vsco/id588013838?mt=8&uo=4">https://itunes.apple.com/us/app/vsco/id588013838?mt=8&uo=4</a>
**App Version:** 7.0
**Seller:** Visual Supply Company
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/visual-supply-company/id513526768?uo=4>© Visual Supply Company</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/8c/7f/8d/8c7f8d69-d0fc-46e4-eeb6-94d0fc483aaf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18722793/5c0bff72-8036-11e6-9a44-60b19f882fb0.png)

**Comment by alpcinar** [comment]
Not themed after 5.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18722793/5c0bff72-8036-11e6-9a44-60b19f882fb0.png)
https://cloud.githubusercontent.com/assets/20930745/18722793/5c0bff72-8036-11e6-9a44-60b19f882fb0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18722815/6b4f303a-8036-11e6-9a35-8cac97896016.png
