### ISSUE TITLE
WatchESPN

### ISSUE THREAD

**Issue by justoned420** [glasklart/hd#3048]
**App Name:** WatchESPN
**Bundle ID:** com.espn.WatchESPN
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=429009175">429009175</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watchespn/id429009175?mt=8&uo=4">https://itunes.apple.com/us/app/watchespn/id429009175?mt=8&uo=4</a>
**App Version:** 1.9.6
**Seller:** ESPN Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/espn/id317469187?uo=4>© ESPN</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/07/3f/f5/073ff5f1-d499-a295-551a-248e53caf05b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18768049/09b0c918-8123-11e6-9d60-cbffe067f16f.png)

**Comment by Sly-Fi** [comment]
Icon is missing from 5.0.0 release

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18768049/09b0c918-8123-11e6-9d60-cbffe067f16f.png)
https://cloud.githubusercontent.com/assets/20930745/18768049/09b0c918-8123-11e6-9d60-cbffe067f16f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18768067/1aa049d8-8123-11e6-8874-07ea9c81058d.png
