### ISSUE TITLE
Bouncy! Trampoline

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#3051]
**App Name:** Bouncy! Trampoline
**Bundle ID:** com.monogames.bouncy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=579914750">579914750</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bouncy-trampoline/id579914750?mt=8&uo=4">https://itunes.apple.com/us/app/bouncy-trampoline/id579914750?mt=8&uo=4</a>
**App Version:** 3.11
**Seller:** Joel Blanco Berg
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marcel-blanco/id523162915?uo=4">© Marcel Blanco</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/f3/5f/5b/f35f5b43-d21d-7724-981e-a710b0fc172b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/34463389-d7576eca-ee1f-11e7-945e-f760cefca13b.png)

**Comment by Christian9901** [comment]
Icon needs update

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/34463389-d7576eca-ee1f-11e7-945e-f760cefca13b.png)
https://user-images.githubusercontent.com/3090247/34463389-d7576eca-ee1f-11e7-945e-f760cefca13b.png
Source:
https://user-images.githubusercontent.com/3090247/34463390-d771d2ce-ee1f-11e7-9c71-67f6234cd736.png
