### ISSUE TITLE
The Silent Age

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3057]
**App Name:** The Silent Age
**Bundle ID:** dk.houseonfire.ios.thesilentage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=580991034">580991034</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-silent-age/id580991034?mt=8&uo=4">https://itunes.apple.com/us/app/the-silent-age/id580991034?mt=8&uo=4</a>
**App Version:** 2.15
**Seller:** House on Fire ApS
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/house-on-fire/id465072852?uo=4>© House on Fire</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/44/5d/86/445d861f-ba9e-37a5-2c05-32130ebada39/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17826185/815f7c40-666e-11e6-8427-9f04ca7a68de.png)

**Comment by Anuskuss** [comment]
Small update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17826185/815f7c40-666e-11e6-8427-9f04ca7a68de.png)
https://cloud.githubusercontent.com/assets/2068130/17826185/815f7c40-666e-11e6-8427-9f04ca7a68de.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17826193/92029834-666e-11e6-8307-0283cf5a5365.png

**Comment by Anuskuss** [comment]
@dreamnet Could you make the seperation from hair to face "borderless"?

**Comment by dreamnet** [comment]
Oh, man... :anguished:

**Comment by Anuskuss** [comment]
*Ich bins wieder (^o^)/*

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17836383/90a90e82-6790-11e6-8e72-d7f5f7b05b55.png)
https://cloud.githubusercontent.com/assets/2068130/17836383/90a90e82-6790-11e6-8e72-d7f5f7b05b55.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17836386/a0df7c28-6790-11e6-8008-ec39904baabe.png
Hm. I dont really like it.

**Comment by dreamnet** [comment]
No reaction from @Anuskuss. Closing.

**Comment by Anuskuss** [comment]
@dreamnet Sorry for that, I had a busy week.

How do you like this approach?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18153979/2108e02e-7001-11e6-917d-15e6cea2529e.png)

**Comment by dreamnet** [comment]
@Anuskuss Hm, not really. It looks like he has an open mouth. Nice try anyway.

**Comment by ivanov007** [comment]
@Anuskuss yeah kind of toothless and the game title doesn't help :smile:
