### ISSUE TITLE
Sydney Uni

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#307]
**App Name:** Sydney Uni
**Bundle ID:** edu.sydney.sydneyuni
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542003075">542003075</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sydney-uni/id542003075?mt=8&uo=4">https://itunes.apple.com/us/app/sydney-uni/id542003075?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** University of Sydney
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-university-of-sydney/id542003078?uo=4">© The University of Sydney</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/08/91/17/08911742-9a91-0bd9-e0b0-738cdea87db5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23325572/ab0ec204-faf6-11e6-811f-09d0707be6e1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23325572/ab0ec204-faf6-11e6-811f-09d0707be6e1.png)
https://cloud.githubusercontent.com/assets/2068130/23325572/ab0ec204-faf6-11e6-811f-09d0707be6e1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23325583/bbb54556-faf6-11e6-93b4-5db0f751161b.png
