### ISSUE TITLE
영어 한방 검색

### ISSUE THREAD

**Issue by jlloyd96** [glasklart/hd#3070]
**App Name:** 영어 한방 검색
**Bundle ID:** com.copyharuki.enkrwebdics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406772787">406772787</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%EC%98%81%EC%96%B4-%ED%95%9C%EB%B0%A9-%EA%B2%80%EC%83%89/id406772787?mt=8&uo=4">https://itunes.apple.com/us/app/%EC%98%81%EC%96%B4-%ED%95%9C%EB%B0%A9-%EA%B2%80%EC%83%89/id406772787?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** ILHWAN CHO
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/coha-corp/id418790017?uo=4">© COHA Corp.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/de/f4/b1/def4b19c-d658-a200-0762-60c2fb25b63a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455483-35cb9f3a-3a79-11e8-89cc-1b675e0deb65.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455483-35cb9f3a-3a79-11e8-89cc-1b675e0deb65.png)
https://user-images.githubusercontent.com/20930745/38455483-35cb9f3a-3a79-11e8-89cc-1b675e0deb65.png

Source:
https://user-images.githubusercontent.com/20930745/38455485-45990f74-3a79-11e8-9264-79662d4687ee.png
