### ISSUE TITLE
IBM Traveler Companion

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3085]
**App Name:** IBM Traveler Companion
**Bundle ID:** com.ibm.lotus.travelercompanion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=346633404">346633404</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ibm-traveler-companion/id346633404?uo=4">https://apps.apple.com/us/app/ibm-traveler-companion/id346633404?uo=4</a>
**App Version:** 10.0.2
**Seller:** HCL America
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hcl-america-inc/id392909135?uo=4">© HCL America Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/e6/91/68/e69168d6-0e32-7459-3b5b-7eac020208db/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62396644-f783fe80-b573-11e9-9298-661a1a92f76e.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62396644-f783fe80-b573-11e9-9298-661a1a92f76e.png)
https://user-images.githubusercontent.com/2068130/62396644-f783fe80-b573-11e9-9298-661a1a92f76e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62396664-079bde00-b574-11e9-8b07-8f0832e52307.png
