### ISSUE TITLE
Print Utility

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#3089]
**App Name:** Print Utility
**Bundle ID:** com.dar-soft.PrintUtilityiPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=422858586">422858586</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/print-utility/id422858586?mt=8&uo=4">https://itunes.apple.com/us/app/print-utility/id422858586?mt=8&uo=4</a>
**App Version:** 2.9.1
**Seller:** Darsoft Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/darsoft-inc/id417954209?uo=4">© Darsoft Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/57/1f/f2/571ff2ac-8b66-857b-8fdd-5424cf36b6fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692270-24d83f94-c715-11e7-97d3-17c436aa3299.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692270-24d83f94-c715-11e7-97d3-17c436aa3299.png)
https://user-images.githubusercontent.com/2068130/32692270-24d83f94-c715-11e7-97d3-17c436aa3299.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692273-37b35586-c715-11e7-9dae-e7ed1d86d80a.png
