### ISSUE TITLE
xtBus transit browser for your next bus arrivals

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#3091]
**App Name:** xtBus transit browser for your next bus arrivals
**Bundle ID:** com.idemfactor.NextBus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=451379202">451379202</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xtbus-transit-browser-for-your-next-bus-arrivals/id451379202?mt=8&uo=4">https://itunes.apple.com/us/app/xtbus-transit-browser-for-your-next-bus-arrivals/id451379202?mt=8&uo=4</a>
**App Version:** 2.6.1
**Seller:** Idemfactor Solutions Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/idemfactor-solutions/id301061386?uo=4">© Idemfactor Solutions</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/5e/e8/f9/5ee8f90f-c1e2-f64f-debb-bbb29f1adc05/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32691420-9999425a-c707-11e7-8370-958835514f66.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32691420-9999425a-c707-11e7-8370-958835514f66.png)
https://user-images.githubusercontent.com/2068130/32691420-9999425a-c707-11e7-8370-958835514f66.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32691429-a90e9d0c-c707-11e7-863e-f0d8016defe2.png
