### ISSUE TITLE
EasilyDo Smart Assistant

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#3092]
**App Name:** EasilyDo Assistant for Contacts, Calendar, Email, Travel and Receipts
**Bundle ID:** com.easilydo.Easilydo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=481881465">481881465</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/easilydo-assistant-for-contacts/id481881465?mt=8&uo=4">https://itunes.apple.com/us/app/easilydo-assistant-for-contacts/id481881465?mt=8&uo=4</a>
**App Version:** 3.9.1
**Seller:** Easilydo Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/easilydo-inc./id481881468?uo=4>© Easilydo Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/6e/4e/b2/6e4eb2ec-1e0c-d6b2-9d17-7bd6c154a996/mzl.jbrqlkfc.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10857623/74c9cf46-7f4f-11e5-8de9-501977b22155.png)

**Comment by l8er4now** [comment]
Could use an updated icon.

**App Name:** EasilyDo Assistant for Contacts, Calendar, Email, Travel and Receipts
**Bundle ID:** com.easilydo.Easilydo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=481881465">481881465</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/easilydo-assistant-for-contacts/id481881465?mt=8&uo=4">https://itunes.apple.com/us/app/easilydo-assistant-for-contacts/id481881465?mt=8&uo=4</a>
**App Version:** 3.9.1
**Seller:** Easilydo Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/easilydo-inc./id481881468?uo=4>© Easilydo Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/6e/4e/b2/6e4eb2ec-1e0c-d6b2-9d17-7bd6c154a996/mzl.jbrqlkfc.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10857623/74c9cf46-7f4f-11e5-8de9-501977b22155.png)
https://cloud.githubusercontent.com/assets/2068130/10857623/74c9cf46-7f4f-11e5-8de9-501977b22155.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10857629/838c2aec-7f4f-11e5-83db-aacd64b03d62.png
