### ISSUE TITLE
Analytics Pro

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#31]
**App Name:** Analytics Pro
**Bundle ID:** com.blackburninternet.analyticspro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=352409235">352409235</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/analytics-pro/id352409235?mt=8&uo=4">https://itunes.apple.com/us/app/analytics-pro/id352409235?mt=8&uo=4</a>
**App Version:** 1.6.5
**Seller:** Thomas Blackburn
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/thomas-blackburn/id326488861?uo=4">© Thomas Blackburn</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/11/ce/cd/11cecd4d-a68c-f2e0-061a-97fe13d03f0e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32693249-e6477f66-c727-11e7-96ac-91ae938eee0b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32693249-e6477f66-c727-11e7-96ac-91ae938eee0b.png)
https://user-images.githubusercontent.com/2068130/32693249-e6477f66-c727-11e7-96ac-91ae938eee0b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32693251-f50dfa84-c727-11e7-8a4d-c9062b042d71.png
