### ISSUE TITLE
CamCard Free - Business card scanner & Business card reader & scan card

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#3106]
**App Name:** CamCard Free - Business card scanner & Business card reader & scan card
**Bundle ID:** com.intsig.camcard.lite.eng
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=355472887">355472887</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camcard-free-business-card/id355472887?mt=8&uo=4">https://itunes.apple.com/us/app/camcard-free-business-card/id355472887?mt=8&uo=4</a>
**App Version:** 5.5.2
**Seller:** INTSIG Information Co.,Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/intsig-information-co.-ltd/id344077850?uo=4>© INTSIG Information Co.,Ltd</a>
**Supported Devices:** iPadFourthGen, iPhone4, iPodTouchSixthGen, iPad2Wifi, iPodTouchFifthGen, iPadMini, iPadMini4G, iPhone5s, iPadFourthGen4G, iPhone4S, iPhone6, iPhone6Plus, iPhone5, iPhone5c, iPadThirdGen, iPad23G, iPadThirdGen4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/97/2e/6a/972e6a47-16f7-241e-55ea-d8d49d50889f/mzl.rhldzase.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8858759/8866e9b8-3179-11e5-8444-f5de2bb8c3af.png)

**Comment by Trubbel** [comment]
Icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8858759/8866e9b8-3179-11e5-8444-f5de2bb8c3af.png)
https://cloud.githubusercontent.com/assets/10730122/8858759/8866e9b8-3179-11e5-8444-f5de2bb8c3af.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8858758/83a107f6-3179-11e5-8f7c-efe43c03224d.png
