### ISSUE TITLE
Achording - Guitar Tabs and Chords

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#3109]
**App Name:** Achording - Guitar Tabs and Chords
**Bundle ID:** com.jamonapps.Achording
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=397781926">397781926</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/achording-guitar-tabs-chords/id397781926?mt=8&uo=4">https://itunes.apple.com/us/app/achording-guitar-tabs-chords/id397781926?mt=8&uo=4</a>
**App Version:** 3.3.0
**Seller:** Ramon Arguello Flores
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jamonapps/id397781929?uo=4">© JamonApps</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/fa/68/1f/fa681f03-873c-149b-f1f9-69d1998d2b42/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20178716/be3b0f4c-a752-11e6-8b74-1df02bdfd284.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20178716/be3b0f4c-a752-11e6-8b74-1df02bdfd284.png)
https://cloud.githubusercontent.com/assets/20930745/20178716/be3b0f4c-a752-11e6-8b74-1df02bdfd284.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20178755/f5728724-a752-11e6-9ece-263e074a4e69.png
