### ISSUE TITLE
ExpenSense (Budget + Expense + Income + Account)

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#3110]
**App Name:** ExpenSense (Budget + Expense + Income + Account)
**Bundle ID:** com.on2sol.ExpenSense
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386285268">386285268</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/expensense-budget-expense-income-account/id386285268?mt=8&uo=4">https://itunes.apple.com/us/app/expensense-budget-expense-income-account/id386285268?mt=8&uo=4</a>
**App Version:** 2.24
**Seller:** On2Sol (Pvt) Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/on2sol-pvt-limited/id386285271?uo=4">© On2Sol (Pvt) Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/7c/78/c4/7c78c4eb-6851-6858-b4a0-297f008180f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32691363-ca034054-c706-11e7-8e51-094463ddd03c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32691363-ca034054-c706-11e7-8e51-094463ddd03c.png)
https://user-images.githubusercontent.com/2068130/32691363-ca034054-c706-11e7-8e51-094463ddd03c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32691368-d948c26e-c706-11e7-8316-ae556c870a66.png
