### ISSUE TITLE
Fitness Point - Workout Exercise Journal & Personal Trainer + Body Tracker

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#3111]
**App Name:** Fitness Point - Workout Exercise Journal & Personal Trainer + Body Tracker
**Bundle ID:** com.mosesyan.ilya.fitnesspoint
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525094310">525094310</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fitness-point-workout-exercise/id525094310?mt=8&uo=4">https://itunes.apple.com/us/app/fitness-point-workout-exercise/id525094310?mt=8&uo=4</a>
**App Version:** 6.4.4
**Seller:** ZERO ONE GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zero-one-gmbh/id467595016?uo=4>© ZERO ONE GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple18/v4/90/d5/76/90d576db-4ebb-0651-c83d-a6677953ec83/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17995023/511b3782-6b5e-11e6-9ec2-573739319e58.png)

**Comment by dreamnet** [comment]
Icon needs an update. Refers to #7752.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17995023/511b3782-6b5e-11e6-9ec2-573739319e58.png)
https://cloud.githubusercontent.com/assets/2068130/17995023/511b3782-6b5e-11e6-9ec2-573739319e58.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17995030/60a6d1f2-6b5e-11e6-9a5f-2d507ef8b53f.png
