### ISSUE TITLE
VLC Streamer

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#313]
**App Name:** VLC Streamer
**Bundle ID:** com.HobbyistSoftware.VLCStreamer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=410031728">410031728</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vlc-streamer/id410031728?mt=8&uo=4">https://itunes.apple.com/us/app/vlc-streamer/id410031728?mt=8&uo=4</a>
**App Version:** 4.12
**Seller:** Hobbyist Software Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hobbyist-software-limited/id291218199?uo=4>© Hobbyist Software Limited</a>
**Supported Devices:** iPad23G, iPhone-3GS, iPhone4, iPadFourthGen4G, iPhone5c, iPadMini, iPad2Wifi, iPadFourthGen, iPhone5, iPadThirdGen, iPodTouchFifthGen, iPadMini4G, iPhone4S, iPhone5s, iPadThirdGen4G, iPodTouchourthGen
**Original Artwork:**
<img src="http://a1324.phobos.apple.com/us/r30/Purple3/v4/f9/a8/f9/f9a8f91a-6ead-d8b6-0d56-9b5a22b5438b/pr_source.png?downloadKey=1420127587_37132865027a414236155ec506e2132e" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5592194/9faca4f2-91bd-11e4-8bcc-670b2c118d69.png)

**Comment by dreamnet** [comment]
@dominicPereira Please check if it works with this data. Icon name should be `com.HobbyistSoftware.VLCStreamer@2x.png`.

**Comment by dominicPereira** [comment]
Yup tried that also and still does not work....

**Comment by dreamnet** [comment]
@dominicPereira That's interesting. Can you please post the `CFBundleIdentifier` from the `Info.plist` of this app?

**Comment by dominicPereira** [comment]
I have just send it to your webmaster@dreamnet.at

**Comment by dominicPereira** [comment]
Is this correct ??

<key>CFBundleIdentifier</key>
  <string>com.javier.vlc</string>

**Comment by dreamnet** [comment]
@dominicPereira Jup. - I checked it. Seems you have [this app](http://getart.dreamnet.at?id=914805314) istalled. I open a new issue.
