### ISSUE TITLE
TouchPal Keyboard

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3148]
**App Name:** TouchPal Keyboard
**Bundle ID:** com.cootek.TouchPalIME
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=577705038">577705038</a>
**iPhone Icon Name:** icon@2x.png
**Icon Names:**  icon.png | icon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/touchpal-keyboard/id577705038?mt=8&uo=4
**App Version:** 1.0.1
**Seller:** CooTek
**Supported Devices:** iPadMini, iPadThirdGen, iPadWifi, iPodTouchThirdGen, iPadFourthGen, iPadFourthGen4G, iPhone-3GS, iPhone4S, iPodTouchFifthGen, iPadMini4G, iPhone5, iPad23G, iPad3G, iPhone4, iPad2Wifi, iPadThirdGen4G, iPodTouchourthGen
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/3090247/11979582/1c7cb8fa-a95a-11e5-8157-9dcf907b163c.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11979494/73abcff4-a959-11e5-9ad7-5013ee57d4c7.png)

**Comment by grkka** [comment]
Update icon, please.

**Comment by grkka** [comment]
**App Name:** TouchPal Keyboard - Type Fun With Emoji & Themes & Fonts
**Bundle ID:** com.cootek.smartinput
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=909654683">909654683</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touchpal-keyboard-type-fun/id909654683?mt=8&uo=4">https://itunes.apple.com/us/app/touchpal-keyboard-type-fun/id909654683?mt=8&uo=4</a>
**App Version:** 2.8.0
**Seller:** TouchPal HK Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/touchpal-hk-co.-ltd./id945259429?uo=4>© TouchPal HK Co., Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/1b/ff/08/1bff0895-6a70-7671-a83b-15f7aeb2d8f9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
yes it's the same app, it changed a little bit, I think they are using the holiday icon right now, but google can give us a "neutral" icon

**Comment by dreamnet** [comment]
@ivanov007 Why should we update this? This app seems to be removed from iTunes...

**Comment by ivanov007** [comment]
yup I still have it on my purchased apps

**Comment by dreamnet** [comment]
@ivanov007 Ah, OK. :+1:

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11972217/7f5a76c6-a949-11e5-9c92-bfa6046188d5.png)
https://cloud.githubusercontent.com/assets/2068130/11972217/7f5a76c6-a949-11e5-9c92-bfa6046188d5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11972221/8dd255fc-a949-11e5-90cd-03b6dc909a92.png

**Comment by ivanov007** [comment]
the old icon is still the same, this issue just need the source... @dreamnet do you still have the old original Icon? on the app folder there's just the 114x114 icon
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11979494/73abcff4-a959-11e5-9ad7-5013ee57d4c7.png)
https://cloud.githubusercontent.com/assets/3090247/11979494/73abcff4-a959-11e5-9ad7-5013ee57d4c7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11979495/73ae9694-a959-11e5-8bed-262c6c0d67b4.png

**Comment by ivanov007** [comment]
@dreamnet nevermind, I found it :smile:

**Comment by dreamnet** [comment]
@ivanov007 Ups, sorry... now I got it. :bulb:
