### ISSUE TITLE
The Sandbox - Building & Crafting a Pixel World!

### ISSUE THREAD

**Issue by me12345** [glasklart/hd#316]
**App Name:** The Sandbox - Building & Crafting a Pixel World!
**Bundle ID:** com.bulkypix.thesandbox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520777858">520777858</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-sandbox-building-crafting-a-pixel-world/id520777858?mt=8&uo=4">https://itunes.apple.com/us/app/the-sandbox-building-crafting-a-pixel-world/id520777858?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** PIXOWL INC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pixowl-inc/id436959453?uo=4">© PIXOWL INC.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/6c/66/cd/6c66cd92-8d08-2853-38a4-f7ca1c367e51/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35765210-b1322450-08bf-11e8-9648-bb65e48c18d6.png)

**Comment by Christian9901** [comment]
I think this should be updated to it's new icon.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35765210-b1322450-08bf-11e8-9648-bb65e48c18d6.png)
https://user-images.githubusercontent.com/20930745/35765210-b1322450-08bf-11e8-9648-bb65e48c18d6.png

Source:
https://user-images.githubusercontent.com/20930745/35765216-c5ef29e2-08bf-11e8-94fe-8585fcead653.png

**Comment by dreamnet** [comment]
@Christian9901 ❓
