### ISSUE TITLE
CamCard Free - 名刺認識管理

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3167]
**App Name:** CamCard Free - 名刺認識管理
**Bundle ID:** com.intsig.camcard.ja
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348368056">348368056</a>
**iPhone Icon Name:** icon@2x.png
**Icon Names:** icon.png | icon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/camcard-free-ming-ci-ren-shi/id348368056?mt=8&uo=4
**App Version:** 4.1.0.0
**Seller:** IntSig Information Co.,Ltd
**Supported Devices:** all
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60361893-bbdb9f00-99df-11e9-84b8-df9cbf57c744.png" width="150" height="150" />
**Accepted Artwork:**
![com intsig camcard eng-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60361902-c7c76100-99df-11e9-9e61-ab9bb56ed88c.png)

**Comment by dreamnet** [comment]
![com intsig camcard eng-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60361902-c7c76100-99df-11e9-9e61-ab9bb56ed88c.png)
https://user-images.githubusercontent.com/2068130/60361902-c7c76100-99df-11e9-9e61-ab9bb56ed88c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60361925-d6157d00-99df-11e9-999a-a70115c7682e.png
