### ISSUE TITLE
CamCard -Business Card Scanner

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3168]
**App Name:** CamCard -Business Card Scanner
**Bundle ID:** com.intsig.camcard.lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=349447615">349447615</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/camcard-business-card-scanner/id349447615?uo=4">https://apps.apple.com/us/app/camcard-business-card-scanner/id349447615?uo=4</a>
**App Version:** 7.59.2
**Seller:** INTSIG Information Co.,Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/intsig-information-co-ltd/id344077850?uo=4">© INTSIG Information Co.,Ltd</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/7e/09/28/7e09286c-008d-2c80-8669-5d1348732590/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com intsig camcard lite-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60361393-5c30c400-99de-11e9-9357-73c26c39612d.png)

**Comment by dreamnet** [comment]
![com intsig camcard lite-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60361393-5c30c400-99de-11e9-9357-73c26c39612d.png)
https://user-images.githubusercontent.com/2068130/60361393-5c30c400-99de-11e9-9357-73c26c39612d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60361422-6b177680-99de-11e9-941e-cfb007b507c0.png
