### ISSUE TITLE
CamCard - 名刺認識管理

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3169]
**App Name:** CamCard - 名刺認識管理
**Bundle ID:** com.intsig.camcard.ja2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364543737">364543737</a>
**iPhone Icon Name:** icon@2x.png
**Icon Names:** icon.png | icon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/camcard-ming-ci-ren-shi-guan-li/id364543737?mt=8&uo=4
**App Version:** 4.1.0.2
**Seller:** IntSig Information Co.,Ltd
**Supported Devices:** all
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60361988-05c48500-99e0-11e9-8919-702c6e0f2daa.png" width="150" height="150" />
**Accepted Artwork:**
![com intsig camcard eng-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60362010-11b04700-99e0-11e9-85c7-b1db86eabeb0.png)

**Comment by dreamnet** [comment]
![com intsig camcard eng-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60362010-11b04700-99e0-11e9-85c7-b1db86eabeb0.png)
https://user-images.githubusercontent.com/2068130/60362010-11b04700-99e0-11e9-85c7-b1db86eabeb0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60362024-2096f980-99e0-11e9-9153-c7bb81efd63e.png
