### ISSUE TITLE
CamCard - Business card scanner & Business card reader & scan card

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3170]
**App Name:** CamCard - Business card scanner & Business card reader & scan card
**Bundle ID:** com.intsig.camcard.eng
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347803339">347803339</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camcard-business-card-scanner/id347803339?mt=8&uo=4">https://itunes.apple.com/us/app/camcard-business-card-scanner/id347803339?mt=8&uo=4</a>
**App Version:** 5.5.2
**Seller:** INTSIG Information Co.,Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/intsig-information-co.-ltd/id344077850?uo=4>© INTSIG Information Co.,Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/fc/38/32/fc38325e-d791-6fb3-88ef-d1466143e1fc/mzl.rpmkcgyb.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8858759/8866e9b8-3179-11e5-8444-f5de2bb8c3af.png)

**Comment by l8er4now** [comment]
This icon has changed to match the other app variations. 

http://glasklarthd.dreamnet.at/index.php?id=8152

**Comment by dreamnet** [comment]
Same icon as #3106. Icon by @Trubbel.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8858759/8866e9b8-3179-11e5-8444-f5de2bb8c3af.png)
https://cloud.githubusercontent.com/assets/10730122/8858759/8866e9b8-3179-11e5-8444-f5de2bb8c3af.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8858758/83a107f6-3179-11e5-8f7c-efe43c03224d.png
