### ISSUE TITLE
CamCard - 명함스캐너

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3171]
**App Name:** CamCard - 명함스캐너
**Bundle ID:** com.intsig.camcard.ko
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364189959">364189959</a>
**iPhone Icon Name:** icon@2x.png
**Icon Names:** icon.png | icon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/camcard-myeonghamseukaeneo/id364189959?mt=8&uo=4
**App Version:** 4.1.0.0
**Seller:** IntSig Information Co.,Ltd
**Supported Devices:** all
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60361093-9f3e6780-99dd-11e9-9862-176c8d116e96.png" width="150" height="150" />
**Accepted Artwork:**
![com intsig camcard ko-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60361112-aa919300-99dd-11e9-914a-35f3c08eeba7.png)

**Comment by dreamnet** [comment]
![com intsig camcard ko-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60361112-aa919300-99dd-11e9-914a-35f3c08eeba7.png)
https://user-images.githubusercontent.com/2068130/60361112-aa919300-99dd-11e9-914a-35f3c08eeba7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60361131-ba10dc00-99dd-11e9-84e2-3a8e58ea5de5.png
