### ISSUE TITLE
CamCard Free - 명함스캐너

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3172]
**App Name:** CamCard Free - 명함스캐너
**Bundle ID:** com.intsig.camcard.ko.lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364514190">364514190</a>
**iPhone Icon Name:** icon@2x.png
**Icon Names:** icon.png | icon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/camcard-free-myeonghamseukaeneo/id364514190?mt=8&uo=4
**App Version:** 4.1.0.0
**Seller:** IntSig Information Co.,Ltd
**Supported Devices:** all
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60361768-643d3380-99df-11e9-81f8-3e8bbc536318.png" width="150" height="150" />
**Accepted Artwork:**
![com intsig camcard eng-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60361787-71f2b900-99df-11e9-9c72-ecbbd46a4d82.png)

**Comment by dreamnet** [comment]
![com intsig camcard eng-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60361787-71f2b900-99df-11e9-9c72-ecbbd46a4d82.png)
https://user-images.githubusercontent.com/2068130/60361787-71f2b900-99df-11e9-9c72-ecbbd46a4d82.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60361805-80d96b80-99df-11e9-94ed-ac58ee8ea6aa.png
