### ISSUE TITLE
ibisMail - Filtering Mail

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3173]
**App Name:** ibisMail - Filtering Mail
**Bundle ID:** jp.ne.ibis.ibisMail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300834416">300834416</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ibismail-filtering-mail/id300834416?mt=8&uo=4">https://itunes.apple.com/us/app/ibismail-filtering-mail/id300834416?mt=8&uo=4</a>
**App Version:** 4.0.9
**Seller:** ibis inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ibis-inc./id300834419?uo=4">© ibis inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/c3/e8/97/c3e897c0-97d2-d5ac-30a3-cb4f290d3be7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20443259/6d673ce6-adcc-11e6-9e32-a69e670f9fd0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20443259/6d673ce6-adcc-11e6-9e32-a69e670f9fd0.png)
https://cloud.githubusercontent.com/assets/2068130/20443259/6d673ce6-adcc-11e6-9e32-a69e670f9fd0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20443275/8086a00a-adcc-11e6-9e94-3211803bfb80.png
