### ISSUE TITLE
Beat - Ride app

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#3191]
**App Name:** Beat - Ride app
**Bundle ID:** com.taxibeat.passenger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=436031420">436031420</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beat-ride-app/id436031420?mt=8&uo=4">https://itunes.apple.com/us/app/beat-ride-app/id436031420?mt=8&uo=4</a>
**App Version:** 10.25
**Seller:** Taxibeat Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/taxibeat-ltd/id435590190?uo=4">© Taxibeat Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/fe/f6/8d/fef68d0e-03e4-0f9d-8d2e-6842f080bc3b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626044-2d594580-a916-11e8-8906-326e63263eff.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626016-cb98db80-a915-11e8-8e19-9463edf6f0a1.png)
https://user-images.githubusercontent.com/2068130/44626016-cb98db80-a915-11e8-8e19-9463edf6f0a1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44626024-dbb0bb00-a915-11e8-9fe9-2621ce195d3a.png
