### ISSUE TITLE
8,500+ Drink & Cocktail Recipes Free

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#320]
**App Name:** 8,500+ Drink & Cocktail Recipes Free
**Bundle ID:** com.webworks.drinksfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=297650041">297650041</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/8-500+-drink-cocktail-recipes/id297650041?mt=8&uo=4">https://itunes.apple.com/us/app/8-500+-drink-cocktail-recipes/id297650041?mt=8&uo=4</a>
**App Version:** 3.4.0
**Seller:** Webworks
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/webworks/id291830682?uo=4>© Webworks</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/10/3f/50/103f508d-ccf8-6b90-6f72-bcf9d23b0cd9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18985792/0afc20ce-86fa-11e6-92fa-aa06bcf10bff.png)

**Comment by illinikev** [comment]
update needed

**Comment by 2Qt2beStr8** [comment]
... for this app i use this icon .. i don't like the original

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18985792/0afc20ce-86fa-11e6-92fa-aa06bcf10bff.png)
https://cloud.githubusercontent.com/assets/20930745/18985792/0afc20ce-86fa-11e6-92fa-aa06bcf10bff.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18985813/1d0a8076-86fa-11e6-9e56-85dd41a36754.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Jup, fine! 👍
