### ISSUE TITLE
File Hub Pro by imoreapps

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#3201]
**App Name:** File Hub Pro by imoreapps
**Bundle ID:** com.imoreapps.portabledisk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520299954">520299954</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/file-hub-pro-by-imoreapps/id520299954?uo=4">https://apps.apple.com/us/app/file-hub-pro-by-imoreapps/id520299954?uo=4</a>
**App Version:** 8.0.0
**Seller:** Gu Jing
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gu-jing/id504228387?uo=4">© Gu Jing</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/b4/8e/f5/b48ef52c-d339-5030-bdc3-11198dd889bf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70941674-37441200-204d-11ea-85b8-e481d05aee38.png)

**Comment by l8er4now** [comment]
Could use an update.

**App Name:** File Hub (Powerful & Intuitive File Manager)
**Bundle ID:** com.imoreapps.portabledisk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520299954">520299954</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/file-hub-powerful-intuitive/id520299954?mt=8&uo=4">https://itunes.apple.com/us/app/file-hub-powerful-intuitive/id520299954?mt=8&uo=4</a>
**App Version:** 3.8
**Seller:** Gu Jing
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gu-jing/id504228387?uo=4>© Gu Jing</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/93/81/f6/9381f608-30fc-f24c-3fa0-5174accfbaf2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/14850416/2cd15922-0c79-11e6-81a9-ea8a395e276f.png)
https://cloud.githubusercontent.com/assets/10730122/14850416/2cd15922-0c79-11e6-81a9-ea8a395e276f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/14850417/2cd37d6a-0c79-11e6-8873-6c31cd614a63.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** File Hub Pro by imoreapps
**Bundle ID:** com.imoreapps.portabledisk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520299954">520299954</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/file-hub-pro-by-imoreapps/id520299954?uo=4">https://apps.apple.com/us/app/file-hub-pro-by-imoreapps/id520299954?uo=4</a>
**App Version:** 7.1
**Seller:** Gu Jing
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gu-jing/id504228387?uo=4">© Gu Jing</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/9f/3c/9b/9f3c9b8b-4734-3a29-fa58-4c7a308e6368/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59283059-3aa7ac80-8c6a-11e9-9e6f-62a7624bd752.png)
https://user-images.githubusercontent.com/20930745/59283059-3aa7ac80-8c6a-11e9-9e6f-62a7624bd752.png

Source:
https://user-images.githubusercontent.com/20930745/59283062-3bd8d980-8c6a-11e9-95ed-7acc7ad31923.png
Icon by @2Qt2beStr8

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** File Hub Pro by imoreapps
**Bundle ID:** com.imoreapps.portabledisk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520299954">520299954</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/file-hub-pro-by-imoreapps/id520299954?uo=4">https://apps.apple.com/us/app/file-hub-pro-by-imoreapps/id520299954?uo=4</a>
**App Version:** 8.0.0
**Seller:** Gu Jing
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gu-jing/id504228387?uo=4">© Gu Jing</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/b4/8e/f5/b48ef52c-d339-5030-bdc3-11198dd889bf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/70941674-37441200-204d-11ea-85b8-e481d05aee38.png)
https://user-images.githubusercontent.com/20930745/70941674-37441200-204d-11ea-85b8-e481d05aee38.png

Source:
https://user-images.githubusercontent.com/20930745/70941676-390dd580-204d-11ea-9a17-07bef4cf16b5.png
