### ISSUE TITLE
Active911

### ISSUE THREAD

**Issue by cryan0927** [glasklart/hd#3214]
**App Name:** Active911
**Bundle ID:** com.active911.universal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525979138">525979138</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/active911/id525979138?mt=8&uo=4">https://itunes.apple.com/us/app/active911/id525979138?mt=8&uo=4</a>
**App Version:** 1.5.22
**Seller:** Active911, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/active911/id525979141?uo=4">© Active911</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/23/07/c8/2307c847-67d2-d3cc-c7fc-2c5c45a6e1b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455448-775a164e-3a78-11e8-8364-e8237a8f05b6.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455448-775a164e-3a78-11e8-8364-e8237a8f05b6.png)
https://user-images.githubusercontent.com/20930745/38455448-775a164e-3a78-11e8-8364-e8237a8f05b6.png)

Source:
https://user-images.githubusercontent.com/20930745/38455449-8cb4c340-3a78-11e8-87e3-fb2cb062b7f4.png
