### ISSUE TITLE
Picture Safe - Secure Photo Vault and Private Safe for your Privacy

### ISSUE THREAD

**Issue by cryan0927** [glasklart/hd#3216]
[DUPLICATE of #3216]
**App Name:** Picture Safe - Secure Photo Vault and Private Safe for your Privacy.
**Bundle ID:** com.collect3.picturesafe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=303740913">303740913</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/picture-safe-secure-photo/id303740913?mt=8&uo=4">https://itunes.apple.com/us/app/picture-safe-secure-photo/id303740913?mt=8&uo=4</a>
**App Version:** 2.9.2
**Seller:** David Fumberger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/collect3/id289316919?uo=4>© collect3</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple2/v4/ae/6a/1b/ae6a1b9b-3cdd-93c0-2b66-b834a3d04e6a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12015533/057924bc-ad3e-11e5-8c27-d7077864e996.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12015533/057924bc-ad3e-11e5-8c27-d7077864e996.png)
https://cloud.githubusercontent.com/assets/2068130/12015533/057924bc-ad3e-11e5-8c27-d7077864e996.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12015536/147963b4-ad3e-11e5-8d9d-32054405d35b.png
