### ISSUE TITLE
LunaSolCal

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#3229]
**App Name:** LunaSolCal
**Bundle ID:** com.vvse.LunaSolCal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390175338">390175338</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lunasolcal/id390175338?mt=8&uo=4">https://itunes.apple.com/us/app/lunasolcal/id390175338?mt=8&uo=4</a>
**App Version:** 6.2
**Seller:** Volker Vocking
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/volker-voecking-software-engineering/id390175341?uo=4">© Volker Voecking Software Engineering</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/97/48/a3/9748a3cf-f56e-aab3-d5bf-1e30aa1bc517/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32690892-094bdb0c-c6ff-11e7-91df-98caafaba223.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32690892-094bdb0c-c6ff-11e7-91df-98caafaba223.png)
https://user-images.githubusercontent.com/2068130/32690892-094bdb0c-c6ff-11e7-91df-98caafaba223.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32690896-1a365cd0-c6ff-11e7-816f-0465fb2e57e0.png
