### ISSUE TITLE
Ab Workouts Pro

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#323]
**App Name:** Ab Workouts Pro
**Bundle ID:** com.abworkoutsapp.abworkoutspro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438441351">438441351</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ab-workouts-pro/id438441351?mt=8&uo=4">https://itunes.apple.com/us/app/ab-workouts-pro/id438441351?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Feel Free Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/feel-free-apps/id419496074?uo=4>© Feel Free Apps</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/e5/07/b8/e507b823-cc43-9ba9-24b3-9272313c9ce7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19493019/3c0c4ed6-9579-11e6-9eab-34320fd45055.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19493019/3c0c4ed6-9579-11e6-9eab-34320fd45055.png)
https://cloud.githubusercontent.com/assets/20930745/19493019/3c0c4ed6-9579-11e6-9eab-34320fd45055.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19493048/6001c74e-9579-11e6-9d8e-0a0aab16d66f.png
