### ISSUE TITLE
SCRABBLE™

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#3231]
**App Name:** SCRABBLE™
**Bundle ID:** com.ea.scrabblefreemattel.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=623367437">623367437</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/scrabble/id623367437?mt=8&uo=4">https://itunes.apple.com/gb/app/scrabble/id623367437?mt=8&uo=4</a>
**App Version:** 5.24.0
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/fd/21/a7/fd21a7e4-1afd-7cb7-f62e-cfa91d41fb09/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39471376-2e5275b2-4d43-11e8-96f4-6911d23abcd7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39471376-2e5275b2-4d43-11e8-96f4-6911d23abcd7.png)
https://user-images.githubusercontent.com/2068130/39471376-2e5275b2-4d43-11e8-96f4-6911d23abcd7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39471389-3d5f5a84-4d43-11e8-855b-d21139e8bbe5.png
