### ISSUE TITLE
GMX - Mail & Cloud

### ISSUE THREAD

**Issue by gibLaut** [glasklart/hd#3238]
**App Name:** GMX - Mail & Cloud
**Bundle ID:** com.unitedinternet.mmc.mobile.gmx.iosmailer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417352269">417352269</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gmx-mail-cloud/id417352269?uo=4">https://apps.apple.com/us/app/gmx-mail-cloud/id417352269?uo=4</a>
**App Version:** 7.4
**Seller:** GMX GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/gmx-gmbh/id343575377?uo=4">© GMX GmbH</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/23/65/d3/2365d3ce-cef4-106d-5bb7-d0544d26bd4e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60536155-f4dc8200-9d05-11e9-9cce-b41b70056180.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60536155-f4dc8200-9d05-11e9-9cce-b41b70056180.png)
https://user-images.githubusercontent.com/20930745/60536155-f4dc8200-9d05-11e9-9cce-b41b70056180.png

Source:
https://user-images.githubusercontent.com/20930745/60536162-f6a64580-9d05-11e9-88c7-5c5f5e34a4e1.png
