### ISSUE TITLE
FLSM

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#324]
**App Name:** FLSM
**Bundle ID:** com.imageline.FLStudioMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432850144">432850144</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/flsm/id432850144?uo=4">https://apps.apple.com/us/app/flsm/id432850144?uo=4</a>
**App Version:** 3.2.23
**Seller:** image-line
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/image-line-software/id432850147?uo=4">© Image Line Software</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/69/9a/94/699a94ff-da40-c584-1f80-4dc74d43b2e6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60395166-c9a03a00-9b2f-11e9-9fda-f80a46611a77.png)

**Comment by dreamnet** [comment]
New icon from @Trubbel:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6725280/6912f622-ce07-11e4-94e2-2ccd7541bc45.png)
https://cloud.githubusercontent.com/assets/2068130/6725280/6912f622-ce07-11e4-94e2-2ccd7541bc45.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6725283/76497a8c-ce07-11e4-9641-645805c64252.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60395166-c9a03a00-9b2f-11e9-9fda-f80a46611a77.png)
https://user-images.githubusercontent.com/2068130/60395166-c9a03a00-9b2f-11e9-9fda-f80a46611a77.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60395172-d7ee5600-9b2f-11e9-93f5-b033a77f76ca.png
