### ISSUE TITLE
SPIEGEL ONLINE - Nachrichten

### ISSUE THREAD

**Issue by gibLaut** [glasklart/hd#3242]
**App Name:** SPIEGEL ONLINE - Nachrichten
**Bundle ID:** de.spiegel.spon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424881832">424881832</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spiegel-online-nachrichten/id424881832?mt=8&uo=4">https://itunes.apple.com/us/app/spiegel-online-nachrichten/id424881832?mt=8&uo=4</a>
**App Version:** 3.0.4
**Seller:** SPIEGEL ONLINE GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/spiegel-online-gmbh/id424881840?uo=4>© SPIEGEL ONLINE GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/1e/49/20/1e4920e0-685d-c4f6-3739-ae1ef7abd012/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18893546/ae441bc6-850e-11e6-9c80-e97a4992967f.png)

**Comment by Anuskuss** [comment]
@gibLaut Can you remove the upper border (like #7422) or make it thicker?

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17198987/31c704be-543f-11e6-9c91-10afc8b68e2f.png)
https://cloud.githubusercontent.com/assets/3090247/17198987/31c704be-543f-11e6-9c91-10afc8b68e2f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17198988/31c88fc8-543f-11e6-987f-b991ebaccd2d.png

**Comment by Anuskuss** [comment]
Needs update.

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18893546/ae441bc6-850e-11e6-9c80-e97a4992967f.png)
https://cloud.githubusercontent.com/assets/22012363/18893546/ae441bc6-850e-11e6-9c80-e97a4992967f.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18893541/aa4bd216-850e-11e6-98fe-0c13c08fe0a5.png
