### ISSUE TITLE
IFTTT

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3246]
**App Name:** IFTTT
**Bundle ID:** com.ifttt.ifttt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=660944635">660944635</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ifttt/id660944635?uo=4">https://apps.apple.com/us/app/ifttt/id660944635?uo=4</a>
**App Version:** 4.0.3
**Seller:** IFTTT Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ifttt/id660944638?uo=4">© IFTTT</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/a5/ef/2e/a5ef2e25-176d-384e-5795-909044460564/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62837796-0b1a1e00-bc74-11e9-8660-ae5729833ce0.png)

**Comment by djnightlife** [comment]
App has been renamed "IF" and new icon:

https://itunes.apple.com/us/app/if-by-ifttt/id660944635

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6472117/5bdf433e-c1f0-11e4-84ee-aef6c624eed7.png)
https://cloud.githubusercontent.com/assets/2068130/6472117/5bdf433e-c1f0-11e4-84ee-aef6c624eed7.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6472127/6be38074-c1f0-11e4-962e-e98560aa12ed.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** IFTTT
**Bundle ID:** com.ifttt.ifttt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=660944635">660944635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ifttt/id660944635?mt=8&uo=4">https://itunes.apple.com/us/app/ifttt/id660944635?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** IFTTT Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ifttt/id660944638?uo=4">© IFTTT</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/a7/18/1f/a7181f5c-28cb-4ea4-ccce-751d518a10f1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Anuskuss** [comment]
Not really a fan of the new icon.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20147685/6cee4a86-a6a9-11e6-83eb-df260be8ca08.png)
https://cloud.githubusercontent.com/assets/20930745/20147685/6cee4a86-a6a9-11e6-83eb-df260be8ca08.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20147696/78833690-a6a9-11e6-992f-deba275f878b.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** IFTTT
**Bundle ID:** com.ifttt.ifttt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=660944635">660944635</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ifttt/id660944635?uo=4">https://apps.apple.com/us/app/ifttt/id660944635?uo=4</a>
**App Version:** 3.7.8
**Seller:** IFTTT Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ifttt/id660944638?uo=4">© IFTTT</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/42/3d/fb/423dfb2e-dd8d-f9cd-f3ef-2a2cdc050460/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
Needs an update

**App Name:** IFTTT
**Bundle ID:** com.ifttt.ifttt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=660944635">660944635</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ifttt/id660944635?uo=4">https://apps.apple.com/us/app/ifttt/id660944635?uo=4</a>
**App Version:** 4.0.3
**Seller:** IFTTT Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ifttt/id660944638?uo=4">© IFTTT</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/a5/ef/2e/a5ef2e25-176d-384e-5795-909044460564/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62837796-0b1a1e00-bc74-11e9-8660-ae5729833ce0.png)
https://user-images.githubusercontent.com/2068130/62837796-0b1a1e00-bc74-11e9-8660-ae5729833ce0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62837803-1b31fd80-bc74-11e9-90e9-faef25cebb18.png
