### ISSUE TITLE
Instant Heart Rate - Heart Rate Monitor Free & Gym Workout Plans

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3247]
**App Name:** Instant Heart Rate - Heart Rate Monitor Free & Gym Workout Plans
**Bundle ID:** si.modula.instantheartrate.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409625068">409625068</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instant-heart-rate-heart-rate/id409625068?mt=8&uo=4">https://itunes.apple.com/us/app/instant-heart-rate-heart-rate/id409625068?mt=8&uo=4</a>
**App Version:** 5.32
**Seller:** AZUMIO, inovacije v elektroniki in informacijskih tehnologijah d.o.o.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/azumio-inc./id439290207?mt=8&uo=4>© Azumio Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/a7/a7/dd/a7a7dd21-92a7-790e-2c11-c893db9bdce1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18766582/3a72df76-811b-11e6-9e9a-3bb038d02841.png)

**Comment by Sly-Fi** [comment]
missing from 5.0.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18764045/18fe11e0-8110-11e6-9e99-9a990d0d572f.png)
https://cloud.githubusercontent.com/assets/20930745/18764045/18fe11e0-8110-11e6-9e99-9a990d0d572f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18764059/296996ee-8110-11e6-8d30-d10206ef8e08.png

**Comment by dreamnet** [comment]
Added some details:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18766582/3a72df76-811b-11e6-9e9a-3bb038d02841.png)
https://cloud.githubusercontent.com/assets/2068130/18766582/3a72df76-811b-11e6-9e9a-3bb038d02841.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18766593/4999980a-811b-11e6-8b51-2e782720b46b.png
