### ISSUE TITLE
iNet - Network scanner

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3248]
**App Name:** iNet - Network Scanner
**Bundle ID:** com.bananaglue.inetlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=340793353">340793353</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inet-network-scanner/id340793353?mt=8&uo=4">https://itunes.apple.com/us/app/inet-network-scanner/id340793353?mt=8&uo=4</a>
**App Version:** 2.2.10
**Seller:** BananaGlue GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bananaglue-gmbh/id298348769?uo=4>© BananaGlue GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/9e/fe/66/9efe6611-e1e7-d450-9b2b-96975b13ff2b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18618086/6c45908c-7ddf-11e6-8707-c2df026d96b0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18618086/6c45908c-7ddf-11e6-8707-c2df026d96b0.png)
https://cloud.githubusercontent.com/assets/2068130/18618086/6c45908c-7ddf-11e6-8707-c2df026d96b0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18618090/7a4e8986-7ddf-11e6-9de5-d6c4b209e3d8.png
