### ISSUE TITLE
VLC for Mobile

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3250]
**App Name:** VLC for Mobile
**Bundle ID:** org.videolan.vlc-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=650377962">650377962</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vlc-for-mobile/id650377962?mt=8&uo=4">https://itunes.apple.com/us/app/vlc-for-mobile/id650377962?mt=8&uo=4</a>
**App Version:** 2.7.8
**Seller:** VideoLAN
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/videolan/id599606329?uo=4>© VideoLAN</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/a8/8a/e5/a88ae52b-9b52-0197-3795-10d85b81910d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19621205/1342f84e-988d-11e6-9392-a1bd5eb91d46.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19621205/1342f84e-988d-11e6-9392-a1bd5eb91d46.png)
https://cloud.githubusercontent.com/assets/10730122/19621205/1342f84e-988d-11e6-9392-a1bd5eb91d46.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19621206/135c8494-988d-11e6-88e3-adb2a7e77d41.png

**Comment by dreamnet** [comment]
@Trubbel Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/org.videolan.vlc-ios-large.png). Is the icon not themed on your device?

**Comment by Trubbel** [comment]
@dreamnet Hm, strange it wasn't earlier but it is now. I guess it's all good now.
