### ISSUE TITLE
trivago The Hotel Search – Compare + 1 million hotels over 250 booking sites worldwide

### ISSUE THREAD

**Issue by gibLaut** [glasklart/hd#3255]
**App Name:** trivago The Hotel Search – Compare + 1 million hotels over 250 booking sites worldwide
**Bundle ID:** com.trivago.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376888389">376888389</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trivago-hotel-search-compare/id376888389?mt=8&uo=4">https://itunes.apple.com/us/app/trivago-hotel-search-compare/id376888389?mt=8&uo=4</a>
**App Version:** 3.5.0
**Seller:** trivago GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/trivago-gmbh/id376888392?uo=4>© trivago GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/7e/95/bb/7e95bbdd-7659-aaf0-3934-139b6568e735/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416862/39997f22-7821-11e6-8498-6229b7c6e83b.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416862/39997f22-7821-11e6-8498-6229b7c6e83b.png)
https://cloud.githubusercontent.com/assets/2068130/18416862/39997f22-7821-11e6-8498-6229b7c6e83b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416864/47ebfd2a-7821-11e6-983c-71cbeb4a42dd.png
