### ISSUE TITLE
DataMonitor

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3263]
**App Name:** DataMonitor
**Bundle ID:** com.moritz.eyeoz.DataMonitor
**Version:** 2.3
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://f.cloud.github.com/assets/3090247/830053/0e45c260-f127-11e2-9542-0adb9df7335f.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18703584/c39461e8-7fe6-11e6-8611-d36265388027.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18703584/c39461e8-7fe6-11e6-8611-d36265388027.png)
https://cloud.githubusercontent.com/assets/20930745/18703584/c39461e8-7fe6-11e6-8611-d36265388027.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18703601/dc15c694-7fe6-11e6-96c0-58606e89a46f.png
