### ISSUE TITLE
Argus: Calorie Counter & Step

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3265]
**App Name:** Argus: Calorie Counter & Step
**Bundle ID:** com.azumio.iphone.argus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=624329444">624329444</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/argus-calorie-counter-step/id624329444?uo=4">https://apps.apple.com/us/app/argus-calorie-counter-step/id624329444?uo=4</a>
**App Version:** 5.196
**Seller:** Azumio Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/azumio-inc/id439290207?uo=4">© Azumio Inc.</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/ce/23/16/ce231640-c968-9566-03b5-8b647c891484/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979109-93b8fe00-95e3-11e9-9b24-b59e8ba5b168.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979109-93b8fe00-95e3-11e9-9b24-b59e8ba5b168.png)
https://user-images.githubusercontent.com/2068130/59979109-93b8fe00-95e3-11e9-9b24-b59e8ba5b168.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979116-a3384700-95e3-11e9-8f72-ba1e11bac3c0.png
