### ISSUE TITLE
dailyme TV, Serien, Filme und Fernsehen mit deinem Unterwegs - TV

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#3271]
**App Name:** dailyme TV, Serien, Filme und Fernsehen mit deinem Unterwegs - TV
**Bundle ID:** player.tv.dailyme.
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=325400933">325400933</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/dailyme-tv-serien-filme-und/id325400933?mt=8&uo=4">https://itunes.apple.com/de/app/dailyme-tv-serien-filme-und/id325400933?mt=8&uo=4</a>
**App Version:** 3.16
**Seller:** Self Loading Content GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/self-loading-content-gmbh/id309861143?uo=4>© Self Loading Content GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/45/68/dd/4568dd05-fd61-8f17-7748-ad92fba7f0d6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12637476/fdcca84a-c595-11e5-88b0-bb04cebd51b8.png)

**Comment by Anuskuss** [comment]
###### Icon needs an update ######
**App Name:** dailyme TV, Serien, Filme und Fernsehen mit deinem Unterwegs - TV
**Bundle ID:** player.tv.dailyme.
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=325400933">325400933</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/dailyme-tv-serien-filme-und/id325400933?mt=8&uo=4">https://itunes.apple.com/de/app/dailyme-tv-serien-filme-und/id325400933?mt=8&uo=4</a>
**App Version:** 3.16
**Seller:** Self Loading Content GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/self-loading-content-gmbh/id309861143?uo=4>© Self Loading Content GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/45/68/dd/4568dd05-fd61-8f17-7748-ad92fba7f0d6/source/1024x1024bb.png" width="150" height="150" />

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12637476/fdcca84a-c595-11e5-88b0-bb04cebd51b8.png)
https://cloud.githubusercontent.com/assets/2068130/12637476/fdcca84a-c595-11e5-88b0-bb04cebd51b8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12637487/0d165fa8-c596-11e5-8252-088f3047f97e.png
