### ISSUE TITLE
mehr-tanken - Finde die günstigste Tankstelle in Deiner Nähe!

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#3272]
**App Name:** mehr-tanken - Finde die günstigste Tankstelle in Deiner Nähe!
**Bundle ID:** de.webfactor.MehrTankenApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395965464">395965464</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/mehr-tanken-finde-die-gunstigste/id395965464?mt=8&uo=4">https://itunes.apple.com/de/app/mehr-tanken-finde-die-gunstigste/id395965464?mt=8&uo=4</a>
**App Version:** 3.5.0
**Seller:** webfactor media GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/webfactor-media-gmbh/id395965467?uo=4>© webfactor media GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple20/v4/74/e4/f9/74e4f996-b019-8ea6-550e-4650a5f673b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/16171251/18246082/784a0532-7369-11e6-9bab-67f7cf5e47c1.png)

**Comment by Checkit23** [comment]
I've recreated the icon for the -large method used in Glasklart 5.0+

![de webfactor mehrtankenapp](https://cloud.githubusercontent.com/assets/16171251/18245129/d3d11d60-7363-11e6-8397-e086a31a8857.png)

![de webfactor mehrtankenapp-large](https://cloud.githubusercontent.com/assets/16171251/18245140/dd34ebb6-7363-11e6-869c-54f603c6d385.png)

**Comment by ivanov007** [comment]
@Checkit23 nice job, I've updated your post with the preview template `![](http://preview.dreamnet.at?image=`
