### ISSUE TITLE
Frontback - Social Photos

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#3275]
**App Name:** Frontback - Social Photos
**Bundle ID:** me.frontback.production
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=673566671">673566671</a>
**iPhone Icon Name:** icon@2x.png
**Icon Names:** icon.png | icon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/frontback/id673566671?mt=8&uo=4
**App Version:** 3.4.0
**Seller:** checkthis corporation
**Supported Devices:** all
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60394277-111fc980-9b22-11e9-8213-cf2a36068415.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60394305-58a65580-9b22-11e9-874e-cbb7516653cf.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60394305-58a65580-9b22-11e9-874e-cbb7516653cf.png)
https://user-images.githubusercontent.com/2068130/60394305-58a65580-9b22-11e9-874e-cbb7516653cf.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60394311-68259e80-9b22-11e9-8e04-df5092d9d741.png
