### ISSUE TITLE
YouMail - Intelligent Call Management

### ISSUE THREAD

**Issue by bowla800** [glasklart/hd#328]
**App Name:** YouMail - Intelligent Call Management
**Bundle ID:** RH8QQ5UXC8.youmail.
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=308331524">308331524</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/youmail-intelligent-call-management/id308331524?mt=8&uo=4">https://itunes.apple.com/us/app/youmail-intelligent-call-management/id308331524?mt=8&uo=4</a>
**App Version:** 4.0.33
**Seller:** YouMail
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/youmail-inc./id308331527?uo=4>© YouMail, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/5f/f5/2f/5ff52f6e-d716-a51f-3ba6-480a6ff053ad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19106496/ee4d529e-8ae7-11e6-93fa-3e67c20206fd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19106496/ee4d529e-8ae7-11e6-93fa-3e67c20206fd.png)
https://cloud.githubusercontent.com/assets/2068130/19106496/ee4d529e-8ae7-11e6-93fa-3e67c20206fd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19106503/f8e8995c-8ae7-11e6-945f-ff529fd18aa3.png
