### ISSUE TITLE
Sports Scores & Alerts

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#3283]
**App Name:** Sports Scores & Alerts
**Bundle ID:** lunosoftware.sportsalerts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432450349">432450349</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sports-scores-alerts/id432450349?mt=8&uo=4">https://itunes.apple.com/us/app/sports-scores-alerts/id432450349?mt=8&uo=4</a>
**App Version:** 3.16
**Seller:** Luno Software, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/luno-software-inc/id362314431?uo=4">© Luno Software, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/46/b9/44/46b94434-d9cb-fae3-8f3f-60702cbaa9a2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29675925-a1c513ae-88c4-11e7-9025-856de6b695bc.png)

**Comment by l8er4now** [comment]
Bit of an update needed.

**App Name:** Sports Scores & Alerts
**Bundle ID:** lunosoftware.sportsalerts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432450349">432450349</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sports-scores-alerts/id432450349?mt=8&uo=4">https://itunes.apple.com/us/app/sports-scores-alerts/id432450349?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Luno Software, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/luno-software-inc./id362314431?uo=4>© Luno Software, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/ac/1d/59/ac1d5974-79bd-70ee-3ccc-d21cc012aab7/mzl.sfxuchqm.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10870607/40e89aa0-80cf-11e5-86dd-37f85e3640e6.png)
https://cloud.githubusercontent.com/assets/10730122/10870607/40e89aa0-80cf-11e5-86dd-37f85e3640e6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10870606/3d6092b6-80cf-11e5-9a2c-185558d5c7c9.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Sports Scores & Alerts
**Bundle ID:** lunosoftware.sportsalerts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432450349">432450349</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sports-scores-alerts/id432450349?mt=8&uo=4">https://itunes.apple.com/us/app/sports-scores-alerts/id432450349?mt=8&uo=4</a>
**App Version:** 3.16
**Seller:** Luno Software, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/luno-software-inc/id362314431?uo=4">© Luno Software, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/46/b9/44/46b94434-d9cb-fae3-8f3f-60702cbaa9a2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29675925-a1c513ae-88c4-11e7-9025-856de6b695bc.png)
https://user-images.githubusercontent.com/3090247/29675925-a1c513ae-88c4-11e7-9025-856de6b695bc.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29675924-a1243b50-88c4-11e7-8703-ce15c239b8ef.png
