### ISSUE TITLE
Splyce - fancy music player with automix. Pulselocker Edition!

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#3286]
**App Name:** Splyce - fancy music player with automix. Pulselocker Edition!
**Bundle ID:** com.inqbarna.splice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=648339800">648339800</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/splyce-fancy-music-player/id648339800?mt=8&uo=4">https://itunes.apple.com/us/app/splyce-fancy-music-player/id648339800?mt=8&uo=4</a>
**App Version:** 2.6.1
**Seller:** InQBarna
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inqbarna/id341556077?uo=4">© InQBarna</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/1a/74/3e/1a743e30-db63-895e-ebd0-5bf489d922d4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19967930/8fe5c892-a1d2-11e6-9076-9dcb8a01f9b0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19967930/8fe5c892-a1d2-11e6-9076-9dcb8a01f9b0.png)
https://cloud.githubusercontent.com/assets/20930745/19967930/8fe5c892-a1d2-11e6-9076-9dcb8a01f9b0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19967952/a6cd8f04-a1d2-11e6-9efd-c03ba64d0f51.png
