### ISSUE TITLE
TV Gids Pro

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#3292]
**App Name:** TV Gids Pro
**Bundle ID:** com.mobilepioneers.tvgidspro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=332640275">332640275</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tv-gids-pro/id332640275?mt=8&uo=4">https://itunes.apple.com/us/app/tv-gids-pro/id332640275?mt=8&uo=4</a>
**App Version:** 1.10.20
**Seller:** MobilePioneers
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobilepioneers/id332625575?uo=4>© MobilePioneers</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/0c/aa/4b/0caa4b9f-4eeb-378c-e014-95e107370e0e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19621271/86722cee-988e-11e6-915b-d5c815a68150.png)

**Comment by dreamnet** [comment]
Same as #3294. Icon by @Trubbel.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19621271/86722cee-988e-11e6-915b-d5c815a68150.png)
https://cloud.githubusercontent.com/assets/10730122/19621271/86722cee-988e-11e6-915b-d5c815a68150.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19621272/867326b2-988e-11e6-9db4-bf786d46d9c8.png
