### ISSUE TITLE
TVGiDS.tv: De 1e TV Gids - voor iPhone

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3294]
**App Name:** TVGiDS.tv: De 1e TV Gids - voor iPhone
**Bundle ID:** com.mobilepioneers.tvgidslite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=332625572">332625572</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tvgids.tv-1e-tv-gids-voor/id332625572?mt=8&uo=4">https://itunes.apple.com/us/app/tvgids.tv-1e-tv-gids-voor/id332625572?mt=8&uo=4</a>
**App Version:** 1.10.21
**Seller:** MobilePioneers
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobilepioneers/id332625575?uo=4>© MobilePioneers</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/34/fb/a7/34fba700-4ba2-0ef5-40eb-31a638f300f2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19621271/86722cee-988e-11e6-915b-d5c815a68150.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19621271/86722cee-988e-11e6-915b-d5c815a68150.png)
https://cloud.githubusercontent.com/assets/10730122/19621271/86722cee-988e-11e6-915b-d5c815a68150.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19621272/867326b2-988e-11e6-9db4-bf786d46d9c8.png
