### ISSUE TITLE
DIY App – Creative Community for Kids

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3297]
**App Name:** DIY App – Creative Community for Kids
**Bundle ID:** com.diy.fieldrecorder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519308960">519308960</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/diy-app-creative-community-for-kids/id519308960?uo=4">https://apps.apple.com/us/app/diy-app-creative-community-for-kids/id519308960?uo=4</a>
**App Version:** 2.6.5
**Seller:** DIY, Co
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/diy/id519308963?uo=4">© DIY</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple69/v4/56/1f/97/561f9772-76f1-adc6-d7d1-997fc05bdd4c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382519-5d0c3900-9a64-11e9-9efa-1d726c182b3e.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382519-5d0c3900-9a64-11e9-9efa-1d726c182b3e.png)
https://user-images.githubusercontent.com/20930745/60382519-5d0c3900-9a64-11e9-9efa-1d726c182b3e.png

Source:
https://user-images.githubusercontent.com/20930745/60382521-5ed5fc80-9a64-11e9-9b91-1f460c04cec5.png
