### ISSUE TITLE
Chirrpy

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#33]
**App Name:** Chirrpy
**Bundle ID:** com.chirrpy.chirrpyapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=422892348">422892348</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chirrpy/id422892348?mt=8&uo=4">https://itunes.apple.com/us/app/chirrpy/id422892348?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Chrrpy LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chirrpy/id422892351?uo=4">© Chirrpy</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/9f/4a/59/9f4a5969-d28b-d28f-8e9b-a430367c7760/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692732-a438235a-c71d-11e7-8bf4-75340245b869.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692732-a438235a-c71d-11e7-8bf4-75340245b869.png)
https://user-images.githubusercontent.com/2068130/32692732-a438235a-c71d-11e7-8bf4-75340245b869.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692734-b5e45f10-c71d-11e7-9d09-d8b1a4a75d2d.png
