### ISSUE TITLE
Vevo - Watch Music Videos

### ISSUE THREAD

**Issue by righi** [glasklart/hd#330]
**App Name:** Vevo - Watch Music Videos
**Bundle ID:** com.vevo.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=385815082">385815082</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vevo-watch-music-videos/id385815082?mt=8&uo=4">https://itunes.apple.com/us/app/vevo-watch-music-videos/id385815082?mt=8&uo=4</a>
**App Version:** 5.2.3
**Seller:** VEVO LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vevo/id385815085?uo=4>© VEVO</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/85/64/d7/8564d74a-e8c0-75d0-210c-478f5b706e99/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18886119/e19efc18-84ee-11e6-9d1e-b342ea83bdcc.png)

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18886086/c1b21f84-84ee-11e6-903b-4ed35f2e9c70.png)
https://cloud.githubusercontent.com/assets/22012363/18886086/c1b21f84-84ee-11e6-903b-4ed35f2e9c70.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18886080/b8b277c6-84ee-11e6-9c92-cb55cf7fb17e.png

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18886119/e19efc18-84ee-11e6-9d1e-b342ea83bdcc.png)
https://cloud.githubusercontent.com/assets/22012363/18886119/e19efc18-84ee-11e6-9d1e-b342ea83bdcc.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18886133/ecd63664-84ee-11e6-82b4-6bafca9ccd08.png
