### ISSUE TITLE
Reclamefolder: Alle Folders en Aanbiedingen

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#3303]
**App Name:** Reclamefolder: Alle Folders en Aanbiedingen
**Bundle ID:** nl.aquilasoft.reclamefolder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=443400242">443400242</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reclamefolder-alle-folders/id443400242?mt=8&uo=4">https://itunes.apple.com/us/app/reclamefolder-alle-folders/id443400242?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** Online Retail Service BV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/online-retail-service-bv/id443400245?uo=4>© Online Retail Service BV</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/82/5e/81/825e81b8-7dbd-027e-8e63-76f59f03a0d7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618090/8c2591e6-9841-11e6-83bf-89b48bf114e6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618090/8c2591e6-9841-11e6-83bf-89b48bf114e6.png)
https://cloud.githubusercontent.com/assets/20930745/19618090/8c2591e6-9841-11e6-83bf-89b48bf114e6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19618096/a23ade5a-9841-11e6-8c72-24d435486abc.png
