### ISSUE TITLE
Albert

### ISSUE THREAD

**Issue by linuc** [glasklart/hd#3305]
**App Name:** Albert
**Bundle ID:** net.fingerlab.albertadayinthelife
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=412786607">412786607</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/albert/id412786607?mt=8&uo=4">https://itunes.apple.com/us/app/albert/id412786607?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Fingerlab SARL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fingerlab/id412786610?uo=4">© Fingerlab</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/36/42/d7/3642d730-c51a-008f-0ed7-338338befad3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688253-c6be408a-c6cd-11e7-8111-4f42b78e98c1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688253-c6be408a-c6cd-11e7-8111-4f42b78e98c1.png)
https://user-images.githubusercontent.com/2068130/32688253-c6be408a-c6cd-11e7-8111-4f42b78e98c1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32688255-d7431962-c6cd-11e7-9978-a65774b5fb21.png
