### ISSUE TITLE
Pressbyrån

### ISSUE THREAD

**Issue by linuc** [glasklart/hd#3309]
**App Name:** Pressbyrån
**Bundle ID:** se.pressbyran.namnsdag
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375767061">375767061</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/pressbyr%C3%A5n/id375767061?mt=8&uo=4">https://itunes.apple.com/se/app/pressbyr%C3%A5n/id375767061?mt=8&uo=4</a>
**App Version:** 4.3.0
**Seller:** Reitan Servicehandel Sverige AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/se/developer/reitan-servicehandel-sverige-ab/id375767064?uo=4">© Reitan Servicehandel Sverige AB</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/08/49/c8/0849c836-7702-6ca7-a918-bc7ec6b56b25/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39935828-a2b06c2a-554a-11e8-8ec6-34cd6d8f270f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39935828-a2b06c2a-554a-11e8-8ec6-34cd6d8f270f.png)
https://user-images.githubusercontent.com/2068130/39935828-a2b06c2a-554a-11e8-8ec6-34cd6d8f270f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39935852-b1dae946-554a-11e8-969e-bf6ab2f454dd.png
