### ISSUE TITLE
TUmobile

### ISSUE THREAD

**Issue by lolololololloll** [glasklart/hd#3310]
**App Name:** TUmobile
**Bundle ID:** edu.temple.tumobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431446994">431446994</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tumobile/id431446994?mt=8&uo=4">https://itunes.apple.com/us/app/tumobile/id431446994?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Temple University
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/temple-university/id431446997?uo=4>© Temple University</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/c0/3c/5b/c03c5b2a-6e9d-eb6e-4b4a-7ee7acbab3de/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618061/a819c2ec-9840-11e6-8ce5-30ed60343385.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618061/a819c2ec-9840-11e6-8ce5-30ed60343385.png)
https://cloud.githubusercontent.com/assets/20930745/19618061/a819c2ec-9840-11e6-8ce5-30ed60343385.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19618065/bcce7e12-9840-11e6-942b-7b49a32459a5.png
