### ISSUE TITLE
Ecoute

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#3326]
**App Name:** Ecoute - Beautiful Music Player
**Bundle ID:** com.pixiapps.ecoutemobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=536882653">536882653</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ecoute-beautiful-music-player/id536882653?mt=8&uo=4">https://itunes.apple.com/us/app/ecoute-beautiful-music-player/id536882653?mt=8&uo=4</a>
**App Version:** 2.3.4
**Seller:** Louka Desroziers
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pixiapps/id376915393?uo=4>© PixiApps</a>
**Supported Devices:** iPadFourthGen, iPhone4S, iPodTouchFifthGen, iPadMini4G, iPadThirdGen4G, iPhone5, iPhone4, iPadThirdGen, iPhone6, iPodTouchFourthGen, iPadFourthGen4G, iPad2Wifi, iPad23G, iPadMini, iPhone-3GS, iPhone6Plus, iPhone5c, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/71/97/61/71976115-1a2e-93f2-933f-0c551cbbf36d/mzl.cuiyvfok.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8584376/3510e7cc-25d6-11e5-8174-e925bc150d5d.png)

**Comment by LaCh0uine** [comment]
Icon need to be updated thank you

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8584376/3510e7cc-25d6-11e5-8174-e925bc150d5d.png)
https://cloud.githubusercontent.com/assets/2068130/8584376/3510e7cc-25d6-11e5-8174-e925bc150d5d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8584379/43ddeffc-25d6-11e5-85c4-82d5fc004cdc.png

**Comment by LaCh0uine** [comment]
@dreamnet 👍🏻
