### ISSUE TITLE
Echo112 – Pocket Lifesaver

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#3327]
**App Name:** Echo112 – Pocket Lifesaver
**Bundle ID:** ch.mobilemed.echo112
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=613058743">613058743</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/echo112-pocket-lifesaver/id613058743?uo=4">https://apps.apple.com/us/app/echo112-pocket-lifesaver/id613058743?uo=4</a>
**App Version:** 2.4.5
**Seller:** MobileMed Sarl
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mobilemed-sarl/id376858373?uo=4">© MobileMed Sarl</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/1c/ce/bc/1ccebc7b-2209-c6c8-dca8-3bba19588633/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387489-3968e300-9aa4-11e9-9e51-7a74be18ad8f.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387489-3968e300-9aa4-11e9-9e51-7a74be18ad8f.png)
https://user-images.githubusercontent.com/20930745/60387489-3968e300-9aa4-11e9-9e51-7a74be18ad8f.png

Source:
https://user-images.githubusercontent.com/20930745/60387490-3b32a680-9aa4-11e9-8cab-4a74a58516b6.png
