### ISSUE TITLE
djay 2 for iPhone

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#3328]
**App Name:** djay 2 for iPhone
**Bundle ID:** com.algoriddim.djay2-iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=669198374">669198374</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/djay-2-for-iphone/id669198374?mt=8&uo=4">https://itunes.apple.com/us/app/djay-2-for-iphone/id669198374?mt=8&uo=4</a>
**App Version:** 2.8.10
**Seller:** algoriddim GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/algoriddim-gmbh/id355721993?uo=4">© algoriddim GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/33/d4/0e/33d40e14-02fc-e542-85d6-693cd39d59b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34915643-1650fc12-f92a-11e7-9dbc-3065f08c8774.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34915643-1650fc12-f92a-11e7-9dbc-3065f08c8774.png)
https://user-images.githubusercontent.com/2068130/34915643-1650fc12-f92a-11e7-9dbc-3065f08c8774.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34915646-237c89f6-f92a-11e7-8493-b698710c9985.png
