### ISSUE TITLE
FedEx

### ISSUE THREAD

**Issue by DamonBleetch** [glasklart/hd#3336]
**App Name:** FedEx
**Bundle ID:** com.fedex.mobile.home
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1010729050">1010729050</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fedex/id1010729050?mt=8&uo=4">https://itunes.apple.com/us/app/fedex/id1010729050?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** FedEx Corporate Services, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fedex/id304462052?uo=4">© FedEx</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/51/16/4c/51164c66-d0b2-89d8-c5c9-e3901d038d37/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/50572097-48066400-0db9-11e9-85a7-988322f13939.png)

**Comment by XPEric** [comment]
**App Name:** FedEx
**Bundle ID:** com.fedex.mobile.home
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1010729050">1010729050</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fedex/id1010729050?mt=8&uo=4">https://itunes.apple.com/us/app/fedex/id1010729050?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** FedEx Corporate Services, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fedex/id304462052?uo=4">© FedEx</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/51/16/4c/51164c66-d0b2-89d8-c5c9-e3901d038d37/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment]
Bundle ID needs to be updated.

**Comment by dreamnet** [comment]
@XPEric No, this is a different app - but the old app seems to be outdated, so i'm updating the issue.

**Comment by dreamnet** [comment]
Icon by @ivanov007 
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/50572097-48066400-0db9-11e9-85a7-988322f13939.png)
https://user-images.githubusercontent.com/2068130/50572097-48066400-0db9-11e9-85a7-988322f13939.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/50572101-5a809d80-0db9-11e9-8d21-6f962a180cc7.png
