### ISSUE TITLE
Fitness Buddy+: Gym Workouts

### ISSUE THREAD

**Issue by rubyrod7** [glasklart/hd#334]
**App Name:** Fitness Buddy+: Gym Workouts
**Bundle ID:** com.skyhealth.fitnessbuddy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=443646748">443646748</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fitness-buddy-gym-workouts/id443646748?mt=8&uo=4">https://itunes.apple.com/us/app/fitness-buddy-gym-workouts/id443646748?mt=8&uo=4</a>
**App Version:** 5.138
**Seller:** Tom Xu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/azumio-inc/id439290207?mt=8&uo=4">© Azumio Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/d5/35/9d/d5359d3e-6e2d-9478-a79d-10e2a66d3db2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37567407-eaa9ee1a-2ac6-11e8-80ee-10f9719c5837.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37567407-eaa9ee1a-2ac6-11e8-80ee-10f9719c5837.png)
https://user-images.githubusercontent.com/2068130/37567407-eaa9ee1a-2ac6-11e8-80ee-10f9719c5837.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37567420-fa301134-2ac6-11e8-8b5a-986f52aac727.png
