### ISSUE TITLE
Kingdom Rush Frontiers

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#3345]
**App Name:** Kingdom Rush Frontiers
**Bundle ID:** com.ironhidegames.frontiers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598581396">598581396</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kingdom-rush-frontiers/id598581396?mt=8&uo=4">https://itunes.apple.com/us/app/kingdom-rush-frontiers/id598581396?mt=8&uo=4</a>
**App Version:** 1.9.2
**Seller:** Ironhide S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ironhide-s.a./id558612918?uo=4>© Ironhide S.A.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/92/53/b2/9253b22f-e249-abe9-687f-73ef4117399d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18942259/dabd0da2-8617-11e6-872b-10d2502d799e.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by dreamnet** [comment]
Already in [the repo](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.ironhidegames.frontiers-large.png). No action needed.

**Comment by Anuskuss** [comment]
@dreamnet Oops, wasn't the right game,
