### ISSUE TITLE
7 Minute Workout

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#3354]
**App Name:** 7 Minute Workout
**Bundle ID:** com.stuartkhall.7minuteworkout
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=650762525">650762525</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/7-minute-workout/id650762525?uo=4">https://apps.apple.com/us/app/7-minute-workout/id650762525?uo=4</a>
**App Version:** 3.7.2
**Seller:** Wahoo Fitness L.L.C.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wahoo-fitness/id359225354?uo=4">© Wahoo Fitness</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/ef/a8/65/efa8657e-a655-e054-390d-8355e6655c63/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973662-e9b98180-95a2-11e9-84d0-208da004c7b3.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973662-e9b98180-95a2-11e9-84d0-208da004c7b3.png)
https://user-images.githubusercontent.com/20930745/59973662-e9b98180-95a2-11e9-84d0-208da004c7b3.png

Source:
https://user-images.githubusercontent.com/20930745/59973664-eb834500-95a2-11e9-934e-9c9a485c4346.png
