### ISSUE TITLE
Major Mayhem

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3369]
**App Name:** Major Mayhem
**Bundle ID:** com.turner.asmajormayhem
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=470272134">470272134</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/major-mayhem/id470272134?mt=8&uo=4">https://itunes.apple.com/us/app/major-mayhem/id470272134?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** Turner Broadcasting System, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adult-swim/id398288427?uo=4>© [adult swim]</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/e3/8f/1f/e38f1f03-b72b-bc80-d672-07d411f11b9b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13513994/7e35da70-e16a-11e5-997a-3d98232d28e9.png)

**Comment by Anuskuss** [comment]
@ivanov007 Could you remove the fire maybe?

**Comment by ivanov007** [comment]
well, since it's being a long time I've remade both versions
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13513995/7e36bf44-e16a-11e5-8007-4e720fc03e46.png)
https://cloud.githubusercontent.com/assets/3090247/13513995/7e36bf44-e16a-11e5-8007-4e720fc03e46.png
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13513994/7e35da70-e16a-11e5-997a-3d98232d28e9.png)
https://cloud.githubusercontent.com/assets/3090247/13513994/7e35da70-e16a-11e5-997a-3d98232d28e9.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/13513996/7e37810e-e16a-11e5-990a-3f7f10719ef7.png
https://cloud.githubusercontent.com/assets/3090247/13513997/7e3a7724-e16a-11e5-92b1-8c837dbc2112.png

**Comment by dreamnet** [comment]
Wow, great, I like both versions.

**Comment by Anuskuss** [comment]
I think the fire makes the icon to "blown up" (pun not intended). But it's up so you @ivanov007
