### ISSUE TITLE
Optical Illusions!

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#337]
**App Name:** Optical Illusions!
**Bundle ID:** com.max.Illusions
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=366458366">366458366</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/optical-illusions!/id366458366?mt=8&uo=4">https://itunes.apple.com/us/app/optical-illusions!/id366458366?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** Max Soderstrom
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/max-soderstrom/id311497961?uo=4>© Max Soderstrom</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple2/v4/bf/4a/0b/bf4a0b4c-01cf-012c-b8b4-f4f02f415184/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402846/d129780e-9263-11e6-92d4-b57521799bfe.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402846/d129780e-9263-11e6-92d4-b57521799bfe.png)
https://cloud.githubusercontent.com/assets/20930745/19402846/d129780e-9263-11e6-92d4-b57521799bfe.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19402857/ee2bfd46-9263-11e6-8115-43b291a264a6.png
