### ISSUE TITLE
Infinity Blade

### ISSUE THREAD

**Issue by MagnaMike** [glasklart/hd#3384]
**App Name:** Infinity Blade
**Bundle ID:** com.chairentertainment.birthright
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=387428400">387428400</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/infinity-blade/id387428400?mt=8&uo=4">https://itunes.apple.com/us/app/infinity-blade/id387428400?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Chair Entertainment Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chair-entertainment-group/id387428403?uo=4>© Chair Entertainment Group, LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/cb/0e/f3/cb0ef324-9b07-3c40-e687-fe34c1908b44/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12768782/79e9e6a6-ca12-11e5-85a9-c339e6bcc47c.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12768782/79e9e6a6-ca12-11e5-85a9-c339e6bcc47c.png)
https://cloud.githubusercontent.com/assets/10730122/12768782/79e9e6a6-ca12-11e5-85a9-c339e6bcc47c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12768781/79e9ad1c-ca12-11e5-813f-f460e71f59dd.png
