### ISSUE TITLE
Draw Something

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#339]
**App Name:** Draw Something
**Bundle ID:** com.omgpop.dmtmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=488627858">488627858</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/draw-something/id488627858?mt=8&uo=4">https://itunes.apple.com/us/app/draw-something/id488627858?mt=8&uo=4</a>
**App Version:** 2.9.1
**Seller:** OMGPOP, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/omgpop/id422679887?uo=4">© OMGPOP</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/14/5c/c5/145cc5d2-0c44-d6ec-6440-8cc85d1c0c09/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20465252/6ef15ebe-af59-11e6-9c5c-719bfdc1777f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20465252/6ef15ebe-af59-11e6-9c5c-719bfdc1777f.png)
https://cloud.githubusercontent.com/assets/2068130/20465252/6ef15ebe-af59-11e6-9c5c-719bfdc1777f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20465255/80120c5c-af59-11e6-9775-7344b3bcc01e.png
