### ISSUE TITLE
XING

### ISSUE THREAD

**Issue by gibLaut** [glasklart/hd#3393]
**App Name:** XING
**Bundle ID:** com.xing.XING
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=297625850">297625850</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xing/id297625850?mt=8&uo=4">https://itunes.apple.com/us/app/xing/id297625850?mt=8&uo=4</a>
**App Version:** 5.35.0
**Seller:** XING AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/xing-ag/id297625853?uo=4>© XING AG</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/94/9f/dc/949fdc9d-9728-202f-cdb3-56c2ce0d67e3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222956/9af287c4-8e64-11e6-82ca-9967cba97dba.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222956/9af287c4-8e64-11e6-82ca-9967cba97dba.png)
https://cloud.githubusercontent.com/assets/2068130/19222956/9af287c4-8e64-11e6-82ca-9967cba97dba.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19222963/a8f6ffee-8e64-11e6-902d-dec7a8482845.png
