### ISSUE TITLE
Threema

### ISSUE THREAD

**Issue by gibLaut** [glasklart/hd#3394]
**App Name:** Threema
**Bundle ID:** ch.threema.iapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=578665578">578665578</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/threema/id578665578?mt=8&uo=4">https://itunes.apple.com/us/app/threema/id578665578?mt=8&uo=4</a>
**App Version:** 2.7.3
**Seller:** Threema GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/threema-gmbh/id535112011?uo=4>© Threema GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/6a/08/0c/6a080ce8-f41b-1c41-9d2e-0f16804e995e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18761169/2c5e9b9e-8104-11e6-8f64-6b220cdf2b69.png)

**Comment by Checkit23** [comment]
Updated:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18761169/2c5e9b9e-8104-11e6-8f64-6b220cdf2b69.png)

https://cloud.githubusercontent.com/assets/16171251/18761169/2c5e9b9e-8104-11e6-8f64-6b220cdf2b69.png

Source:
https://cloud.githubusercontent.com/assets/16171251/18761152/1c4407e4-8104-11e6-8921-90a89bc92e6a.png
