### ISSUE TITLE
SkySafari 3

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#3397]
**App Name:** SkySafari 3
**Bundle ID:** com.southernstars.SkySafariLite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=437108143">437108143</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skysafari-3/id437108143?mt=8&uo=4">https://itunes.apple.com/us/app/skysafari-3/id437108143?mt=8&uo=4</a>
**App Version:** 3.8.5
**Seller:** Simulation Curriculum Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/simulation-curriculum-corp./id791341744?uo=4>© Simulation Curriculum Corp.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/ca/db/b5/cadbb515-e9de-03e2-fd71-2faf7b01e805/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18816386/6ea951cc-830e-11e6-84ec-ff085d771ad2.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18816386/6ea951cc-830e-11e6-84ec-ff085d771ad2.png)
https://cloud.githubusercontent.com/assets/3090247/18816386/6ea951cc-830e-11e6-84ec-ff085d771ad2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18816385/6ea82856-830e-11e6-82f8-50c0d4d765e7.png

**Comment by dreamnet** [comment]
@ivanov007 Jup! 🎩
