### ISSUE TITLE
Studio Design

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#3412]
**App Name:** Studio Design
**Bundle ID:** com.madewithstudio.studio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=671866502">671866502</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/studio-design/id671866502?mt=8&uo=4">https://itunes.apple.com/us/app/studio-design/id671866502?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Overlay Studio INC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/overlay-studio-inc/id671866505?uo=4">© Overlay Studio Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/1a/cc/0a/1acc0a8a-5100-728c-4cc0-082896dd09c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20183703/8973bd22-a766-11e6-962a-7970be40716c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20183703/8973bd22-a766-11e6-962a-7970be40716c.png)
https://cloud.githubusercontent.com/assets/20930745/20183703/8973bd22-a766-11e6-962a-7970be40716c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20183751/aa305502-a766-11e6-9d9f-bd92d1355eeb.png
