### ISSUE TITLE
Sudoku (Full Version)

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#342]
**App Name:** Sudoku (Full Version)
**Bundle ID:** com.icenta.MobileSudoku
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307466242">307466242</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sudoku-full-version/id307466242?mt=8&uo=4">https://itunes.apple.com/us/app/sudoku-full-version/id307466242?mt=8&uo=4</a>
**App Version:** 9.0.2
**Seller:** Icenta, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/genina.com/id307466245?uo=4>© genina.com</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple2/v4/9c/61/c3/9c61c3cf-d8df-418b-e3c8-3aa913f607f3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19885433/d25ed318-a01e-11e6-897d-1c697c5622a4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19885433/d25ed318-a01e-11e6-897d-1c697c5622a4.png)
https://cloud.githubusercontent.com/assets/20930745/19885433/d25ed318-a01e-11e6-897d-1c697c5622a4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19885453/f0e1f2e8-a01e-11e6-8b43-a4f305bf17d2.png
