### ISSUE TITLE
Smart Alarm Clock : sleep cycle & snoring recorder

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3420]
**App Name:** Smart Alarm Clock : sleep cycle & snoring recorder
**Bundle ID:** com.plussports.smartalarm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586910133">586910133</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smart-alarm-clock-sleep-cycle/id586910133?mt=8&uo=4">https://itunes.apple.com/us/app/smart-alarm-clock-sleep-cycle/id586910133?mt=8&uo=4</a>
**App Version:** 8.3
**Seller:** NELURRA HOLDINGS LIMITED
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/plus-sports/id571227998?uo=4">© Plus Sports</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/d2/69/e6/d269e639-d8ed-a674-703d-bcc0a4cd4d71/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22215659/74bd65d4-e19c-11e6-95c7-40fa9bc8763c.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Smart Alarm Clock : sleep cycle & snoring recorder
**Bundle ID:** com.plussports.smartalarm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586910133">586910133</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smart-alarm-clock-sleep-cycle/id586910133?mt=8&uo=4">https://itunes.apple.com/us/app/smart-alarm-clock-sleep-cycle/id586910133?mt=8&uo=4</a>
**App Version:** 8.3
**Seller:** NELURRA HOLDINGS LIMITED
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/plus-sports/id571227998?uo=4">© Plus Sports</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/d2/69/e6/d269e639-d8ed-a674-703d-bcc0a4cd4d71/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22215659/74bd65d4-e19c-11e6-95c7-40fa9bc8763c.png)
https://cloud.githubusercontent.com/assets/20930745/22215659/74bd65d4-e19c-11e6-95c7-40fa9bc8763c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22215669/7f566fae-e19c-11e6-9f87-650068f6ec37.png
