### ISSUE TITLE
NFL

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3436]
**App Name:** NFL
**Bundle ID:** com.nfl.gamecenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389781154">389781154</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nfl/id389781154?mt=8&uo=4">https://itunes.apple.com/us/app/nfl/id389781154?mt=8&uo=4</a>
**App Version:** 12.4.2
**Seller:** NFL Enterprises  LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nfl-enterprises-llc/id389781157?uo=4>© NFL Enterprises LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/68/b9/50/68b95006-b0f5-9ef7-2bbe-5e253f0f8108/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10730122/12875350/7a8de506-cde8-11e5-8742-073971194530.png)

**Comment by Trubbel** [comment]
Updating the icon,

![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10730122/12875350/7a8de506-cde8-11e5-8742-073971194530.png)
https://cloud.githubusercontent.com/assets/10730122/12875350/7a8de506-cde8-11e5-8742-073971194530.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12875349/7a8ccc16-cde8-11e5-8d3f-4d68dc77af41.png

**Comment by Trubbel** [comment]
Updating the icon,

![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10730122/12875350/7a8de506-cde8-11e5-8742-073971194530.png)
https://cloud.githubusercontent.com/assets/10730122/12875350/7a8de506-cde8-11e5-8742-073971194530.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12875349/7a8ccc16-cde8-11e5-8d3f-4d68dc77af41.png
