### ISSUE TITLE
Dots Free

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#344]
**App Name:** Dots Free
**Bundle ID:** R6WLZBVJLW.DotsFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=296312126">296312126</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dots-free/id296312126?mt=8&uo=4">https://itunes.apple.com/us/app/dots-free/id296312126?mt=8&uo=4</a>
**App Version:** 1.55
**Seller:** Optime Software LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/optime-software-llc/id289278460?uo=4>© Optime Software LLC</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/05/dd/fd/05ddfd5e-e2be-7a92-7eb1-f4c30fb9fbb7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408610/229323a8-92c2-11e6-89e5-717ebb61ddc4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408610/229323a8-92c2-11e6-89e5-717ebb61ddc4.png)
https://cloud.githubusercontent.com/assets/20930745/19408610/229323a8-92c2-11e6-89e5-717ebb61ddc4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19408612/316283e2-92c2-11e6-9927-2b8004584312.png
