### ISSUE TITLE
Color Accent

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3444]
**App Name:** Color Accent
**Bundle ID:** ColorAccent
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=453170202">453170202</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/color-accent/id453170202?mt=8&uo=4">https://itunes.apple.com/us/app/color-accent/id453170202?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Awais Choudhary
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/205l-studio/id453170205?uo=4>© 205L Studio</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/7d/76/84/7d7684b3-7ff8-bd35-90b3-af5bff07d364/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19527192/63b63862-9627-11e6-8a64-c4d0a0b2e76e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19527192/63b63862-9627-11e6-8a64-c4d0a0b2e76e.png)
https://cloud.githubusercontent.com/assets/20930745/19527192/63b63862-9627-11e6-8a64-c4d0a0b2e76e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19527207/7badc930-9627-11e6-9ac6-a470e38266d7.png
