### ISSUE TITLE
Funny Call with Voice Changer by Voicemod

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3445]
**App Name:** Funny Call with Voice Changer by Voicemod
**Bundle ID:** com.2taptap.voicemod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=392640258">392640258</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/funny-call-with-voice-changer-by-voicemod/id392640258?mt=8&uo=4">https://itunes.apple.com/us/app/funny-call-with-voice-changer-by-voicemod/id392640258?mt=8&uo=4</a>
**App Version:** 4.9.0
**Seller:** Voicemod Sociedad Limitada.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/voicemod/id931416970?uo=4">© Voicemod</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/c1/fd/a5/c1fda56e-7740-9ad1-bffd-299e888c99f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23334457/2d0e05f0-fb9f-11e6-87ca-aff1a70b7262.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23334457/2d0e05f0-fb9f-11e6-87ca-aff1a70b7262.png)
https://cloud.githubusercontent.com/assets/2068130/23334457/2d0e05f0-fb9f-11e6-87ca-aff1a70b7262.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23334460/3d72298a-fb9f-11e6-971f-37c4c19dde28.png
