### ISSUE TITLE
ABC – Watch live TV and stream full episodes! (formerly WATCH ABC)

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3446]
**App Name:** ABC – Watch live TV and stream full episodes! (formerly WATCH ABC)
**Bundle ID:** com.abcdigital.abc.videoplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364191819">364191819</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/abc-watch-live-tv-stream-full/id364191819?mt=8&uo=4">https://itunes.apple.com/us/app/abc-watch-live-tv-stream-full/id364191819?mt=8&uo=4</a>
**App Version:** 5.0.4
**Seller:** ABC Digital
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/abc-digital/id333236255?uo=4>© ABC Digital</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/c3/80/9c/c3809c95-d361-e4d8-d707-c3ab90453a99/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18618717/83dda0f6-7dec-11e6-8bfc-5264b4bf9430.png)

**Comment by l8er4now** [comment]
Needs an update and resized.

**App Name:** ABC – Watch live TV and stream full episodes! (formerly WATCH ABC)
**Bundle ID:** com.abcdigital.abc.videoplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364191819">364191819</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/abc-watch-live-tv-stream-full/id364191819?mt=8&uo=4">https://itunes.apple.com/us/app/abc-watch-live-tv-stream-full/id364191819?mt=8&uo=4</a>
**App Version:** 5.0.4
**Seller:** ABC Digital
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/abc-digital/id333236255?uo=4>© ABC Digital</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/c3/80/9c/c3809c95-d361-e4d8-d707-c3ab90453a99/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18618717/83dda0f6-7dec-11e6-8bfc-5264b4bf9430.png)
https://cloud.githubusercontent.com/assets/2068130/18618717/83dda0f6-7dec-11e6-8bfc-5264b4bf9430.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18618727/a079b506-7dec-11e6-8412-64015cd7b6f3.png
