### ISSUE TITLE
Plague Inc.

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#345]
**App Name:** Plague Inc.
**Bundle ID:** com.ndemiccreations.plagueinc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525818839">525818839</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/plague-inc./id525818839?mt=8&uo=4">https://itunes.apple.com/us/app/plague-inc./id525818839?mt=8&uo=4</a>
**App Version:** 1.10.3
**Seller:** Ndemic Creations LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ndemic-creations/id525818842?uo=4>© Ndemic Creations</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/c6/ad/c1/c6adc1d5-c809-b9e3-7463-cd2183f39d9b/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10981171/6034e834-8406-11e5-80a7-96e9316a8ad8.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10981171/6034e834-8406-11e5-80a7-96e9316a8ad8.png)
https://cloud.githubusercontent.com/assets/10730122/10981171/6034e834-8406-11e5-80a7-96e9316a8ad8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10981170/5e20f5d8-8406-11e5-86a2-006d3dab0785.png
