### ISSUE TITLE
AOL Radio

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3452]
**App Name:** AOL Radio
**Bundle ID:** com.aol.radio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=281913144">281913144</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aol-radio/id281913144?mt=8&uo=4">https://itunes.apple.com/us/app/aol-radio/id281913144?mt=8&uo=4</a>
**App Version:** 5.0.1
**Seller:** AOL Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/aol-inc./id281704577?uo=4">© AOL Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/a0/ff/3e/a0ff3e88-b964-bfb9-7047-a4d40d266cb0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19933868/1f61db8c-a115-11e6-801c-5b80a23a239a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19933868/1f61db8c-a115-11e6-801c-5b80a23a239a.png)
https://cloud.githubusercontent.com/assets/20930745/19933868/1f61db8c-a115-11e6-801c-5b80a23a239a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19933901/38fbcfb2-a115-11e6-9b81-7a415868cdcd.png
