### ISSUE TITLE
Localscope - Find places and people around you

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3455]
**App Name:** Localscope - Find places and people around you
**Bundle ID:** com.cynapse.localscope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409869453">409869453</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/localscope-find-places-people/id409869453?mt=8&uo=4">https://itunes.apple.com/us/app/localscope-find-places-people/id409869453?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** Cynapse India Pvt. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cynapse/id409869457?uo=4>© Cynapse</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/ab/05/1a/ab051a70-819b-c6d3-44e0-9254ab428ff7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18624803/977d68a4-7e4a-11e6-8055-e739d8690d31.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Localscope - Find places and people around you
**Bundle ID:** com.cynapse.localscope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409869453">409869453</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/localscope-find-places-people/id409869453?mt=8&uo=4">https://itunes.apple.com/us/app/localscope-find-places-people/id409869453?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** Cynapse India Pvt. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cynapse/id409869457?uo=4>© Cynapse</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/ab/05/1a/ab051a70-819b-c6d3-44e0-9254ab428ff7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18624803/977d68a4-7e4a-11e6-8055-e739d8690d31.png)
https://cloud.githubusercontent.com/assets/20930745/18624803/977d68a4-7e4a-11e6-8055-e739d8690d31.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18624820/ad14eb56-7e4a-11e6-81bf-091e28f54bf2.png
