### ISSUE TITLE
CamBox

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3456]
**App Name:** CamBox
**Bundle ID:** com.billaboop.cambox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=430357708">430357708</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cambox/id430357708?mt=8&uo=4">https://itunes.apple.com/us/app/cambox/id430357708?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** amaury hazan
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/billaboop-studio/id376382257?uo=4">© Billaboop Studio</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/5a/96/49/5a964982-ae66-2bbc-6adf-7c3a1e6f21d0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19933414/87d3c362-a113-11e6-903d-45770aaa91d2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19933414/87d3c362-a113-11e6-903d-45770aaa91d2.png)
https://cloud.githubusercontent.com/assets/20930745/19933414/87d3c362-a113-11e6-903d-45770aaa91d2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19933441/a2c5a6a4-a113-11e6-8ea4-a2e8b9bb4ed2.png
