### ISSUE TITLE
GPlayer

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3460]
**App Name:** GPlayer
**Bundle ID:** com.ginkgo.gplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438402174">438402174</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gplayer/id438402174?mt=8&uo=4">https://itunes.apple.com/us/app/gplayer/id438402174?mt=8&uo=4</a>
**App Version:** 2.1.03
**Seller:** John Smith
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ginkgo-tech/id438402177?uo=4>© Ginkgo Tech</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/22/2e/61/222e61a4-ee55-c1ee-d422-fe52a3f9fe5f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19524799/3da0e8f0-961f-11e6-9ce1-ecece961f490.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19524799/3da0e8f0-961f-11e6-9ce1-ecece961f490.png)
https://cloud.githubusercontent.com/assets/20930745/19524799/3da0e8f0-961f-11e6-9ce1-ecece961f490.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19524840/57ca0f68-961f-11e6-9125-08e43291e7d8.png
