### ISSUE TITLE
Learn Spanish - Brainscape

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3463]
**App Name:** Learn Spanish - Brainscape
**Bundle ID:** com.brain-scape.sa.c109
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=435124768">435124768</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/learn-spanish-brainscape/id435124768?mt=8&uo=4">https://itunes.apple.com/us/app/learn-spanish-brainscape/id435124768?mt=8&uo=4</a>
**App Version:** 2.20150710
**Seller:** Bold Learning Solutions, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brainscape/id380833754?uo=4>© Brainscape</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/92/f0/ff/92f0ffbc-607a-380a-e30b-cb2e12e43075/mzl.ashiqzqe.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10387119/dee33aa4-6e5e-11e5-9ae4-5a730ea25df3.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10387119/dee33aa4-6e5e-11e5-9ae4-5a730ea25df3.png)
https://cloud.githubusercontent.com/assets/10730122/10387119/dee33aa4-6e5e-11e5-9ae4-5a730ea25df3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10387117/db7de7ba-6e5e-11e5-874e-57ce7a2006dd.png
