### ISSUE TITLE
Learn Spanish Vocabulary *

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3464]
**App Name:** Learn Spanish Vocabulary *
**Bundle ID:** com.brain-scape.sa.c123
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398598510">398598510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/learn-spanish-vocabulary-*/id398598510?mt=8&uo=4">https://itunes.apple.com/us/app/learn-spanish-vocabulary-*/id398598510?mt=8&uo=4</a>
**App Version:** 2.20141126
**Seller:** Bold Learning Solutions, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brainscape/id380833754?uo=4>© Brainscape</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/65/98/d3/6598d3f1-50d5-f943-6cc7-5908859ace5b/mzl.hiirxtpu.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10387119/dee33aa4-6e5e-11e5-9ae4-5a730ea25df3.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10387119/dee33aa4-6e5e-11e5-9ae4-5a730ea25df3.png)
https://cloud.githubusercontent.com/assets/10730122/10387119/dee33aa4-6e5e-11e5-9ae4-5a730ea25df3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10387117/db7de7ba-6e5e-11e5-874e-57ce7a2006dd.png
