### ISSUE TITLE
Vocab Genius

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3465]
**App Name:** Vocab Genius
**Bundle ID:** com.brain-scape.sa.c153
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=408288733">408288733</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vocab-genius/id408288733?mt=8&uo=4">https://itunes.apple.com/us/app/vocab-genius/id408288733?mt=8&uo=4</a>
**App Version:** 2.20141029
**Seller:** Bold Learning Solutions, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brainscape/id380833754?uo=4>© Brainscape</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/23/c0/59/23c05992-7265-697a-4f34-58a900dacd64/mzl.pbzeimcq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10388162/e4c0c82a-6e67-11e5-985a-486067d34618.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10388162/e4c0c82a-6e67-11e5-985a-486067d34618.png)
https://cloud.githubusercontent.com/assets/10730122/10388162/e4c0c82a-6e67-11e5-985a-486067d34618.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10388159/e15b5f10-6e67-11e5-85ad-9933638d7896.png
