### ISSUE TITLE
U.S. Geography

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3466]
**App Name:** U.S. Geography
**Bundle ID:** com.brain-scape.sa.c175
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445457137">445457137</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/u.s.-geography/id445457137?mt=8&uo=4">https://itunes.apple.com/us/app/u.s.-geography/id445457137?mt=8&uo=4</a>
**App Version:** 2.20141028
**Seller:** Bold Learning Solutions, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brainscape/id380833754?uo=4>© Brainscape</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/c5/9c/81/c59c8167-d1de-b41a-cbbc-9b2520a7d7b4/mzl.xkawxsgx.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10387870/3e2942be-6e65-11e5-8b01-21285f78ecb5.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10387870/3e2942be-6e65-11e5-8b01-21285f78ecb5.png)
https://cloud.githubusercontent.com/assets/10730122/10387870/3e2942be-6e65-11e5-8b01-21285f78ecb5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10387869/3a5e1e02-6e65-11e5-8aa9-3d7f69782a10.png
