### ISSUE TITLE
Yoga Studio

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3468]
**App Name:** Yoga Studio
**Bundle ID:** com.cluelesspenguin.YogaDatabase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=567767430">567767430</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yoga-studio/id567767430?mt=8&uo=4">https://itunes.apple.com/us/app/yoga-studio/id567767430?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** Gaiam, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gaiam-inc./id567767433?uo=4>© Gaiam, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/1a/9e/19/1a9e196b-872c-c6b2-3cb2-1e555c40b404/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19524442/092f2416-961e-11e6-89a9-17dda935e0bd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19524442/092f2416-961e-11e6-89a9-17dda935e0bd.png)
https://cloud.githubusercontent.com/assets/20930745/19524442/092f2416-961e-11e6-89a9-17dda935e0bd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19524460/227a3aa0-961e-11e6-8559-43dd12e12279.png
