### ISSUE TITLE
Pronto

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3469]
**App Name:** Pronto
**Bundle ID:** com.createful.pronto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=534514324">534514324</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pronto/id534514324?mt=8&uo=4">https://itunes.apple.com/us/app/pronto/id534514324?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Createful Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/createful-ltd/id371472060?uo=4>© Createful Ltd</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/45/cb/cd/45cbcdc1-2082-6e99-b6ab-e94b57be56bd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19524104/ec701ea8-961c-11e6-9191-adb459d9b163.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19524104/ec701ea8-961c-11e6-9191-adb459d9b163.png)
https://cloud.githubusercontent.com/assets/20930745/19524104/ec701ea8-961c-11e6-9191-adb459d9b163.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19524139/02f5f9f4-961d-11e6-9295-0de0e8d200b1.png
