### ISSUE TITLE
Math Ref Free

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#347]
**App Name:** Math Ref Free
**Bundle ID:** com.happymaau.mathRefFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=312756358">312756358</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/math-ref-free/id312756358?mt=8&uo=4">https://itunes.apple.com/us/app/math-ref-free/id312756358?mt=8&uo=4</a>
**App Version:** 3.0.6
**Seller:** Happy Maau Studios, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/happy-maau-studios-llc/id301384060?uo=4>© Happy Maau Studios, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/78/2b/6d/782b6d16-5c47-5fb6-3612-9f250c515be1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222542/2755fdae-8e5b-11e6-9aad-74b27dfa20e6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222542/2755fdae-8e5b-11e6-9aad-74b27dfa20e6.png)
https://cloud.githubusercontent.com/assets/2068130/19222542/2755fdae-8e5b-11e6-9aad-74b27dfa20e6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19222544/3501a3e0-8e5b-11e6-849a-945382a48e5f.png
