### ISSUE TITLE
Mirror's Edge™ (inc)

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3472]
**App Name:** Mirror's Edge™
**Bundle ID:** com.ea.mirrorsedge.inc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378977849">378977849</a>
**iTunes URL:** https://itunes.apple.com/us/app/mirrors-edge/id378977849?mt=8&uo=4
**App Version:** 1.5.6
**Seller:** Electronic Arts Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/electronic-arts/id284800461?mt=8&uo=4>Electronic Arts Inc.</a>
**Supported Devices:** all
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/18867066/066e3082-84a3-11e6-90e9-e15cbe10b5dc.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18971167/5820967a-8694-11e6-8eaf-87da4c6fdae2.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by dreamnet** [comment]
Icon by @BrokenCommander 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18971167/5820967a-8694-11e6-8eaf-87da4c6fdae2.png)
https://cloud.githubusercontent.com/assets/2068130/18971167/5820967a-8694-11e6-8eaf-87da4c6fdae2.png
___
Source:
https://cloud.githubusercontent.com/assets/2068130/18971187/67ccaa0a-8694-11e6-8593-937dbb4f2a7f.png
