### ISSUE TITLE
Mirror's Edge™ (bv)

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3473]
**App Name:** Mirror's Edge™
**Bundle ID:** com.ea.mirrorsedge.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378976547">378976547</a>
**iTunes URL:** https://itunes.apple.com/gb/app/mirrors-edge/id378976547?mt=8&uo=4
**App Version:** 1.5.7
**Seller:** EA Swiss Sarl
**Developer:** <a href="https://itunes.apple.com/gb/artist/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** all
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/18867316/0f3b0252-84a4-11e6-8df9-fad697530856.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18971167/5820967a-8694-11e6-8eaf-87da4c6fdae2.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18896656/b48cfb64-8523-11e6-9b0d-228b4c8d2745.png)
https://cloud.githubusercontent.com/assets/22012363/18896656/b48cfb64-8523-11e6-9b0d-228b4c8d2745.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18896654/b192d294-8523-11e6-812e-5403f33568f5.png

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18896686/f1ec306a-8523-11e6-87a0-d75794a586ca.png)
https://cloud.githubusercontent.com/assets/22012363/18896686/f1ec306a-8523-11e6-87a0-d75794a586ca.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18896683/eeb33916-8523-11e6-9ca6-e5f08d17b76d.png

**Comment by BrokenCommander** [comment]
@dreamnet You sure you want to take the logo? I don't like it - at all. Maybe someday someone tries to recreate Faith (the girl on the icon) :smiley:

**Comment by dreamnet** [comment]
@BrokenCommander Yes, but in the meanwhile I take the logo... 😉

**Comment by BrokenCommander** [comment]
@dreamnet I meant why didn't you choose the one with the text? It looks better in my opinion but you're the boss :sunglasses: 

I may try it when I have a boring day - maybe I can create something decent :smile:

**Comment by dreamnet** [comment]
@BrokenCommander I didn't choose the one with the text, because I think the text is too small.
