### ISSUE TITLE
My Measures + AR Measure

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#348]
**App Name:** My Measures + AR Measure
**Bundle ID:** com.sis.si.mymeasuresfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=628109928">628109928</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-measures-ar-measure/id628109928?mt=8&uo=4">https://itunes.apple.com/us/app/my-measures-ar-measure/id628109928?mt=8&uo=4</a>
**App Version:** 6.08
**Seller:** TOP APP d.o.o.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/top-app-d-o-o/id987048778?uo=4">© TOP APP d.o.o.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/c3/f7/48/c3f748ba-be88-f735-dff6-e13d92e60809/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32146539-610d9748-bcd9-11e7-987b-f655cc07a977.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32146539-610d9748-bcd9-11e7-987b-f655cc07a977.png)
https://user-images.githubusercontent.com/2068130/32146539-610d9748-bcd9-11e7-987b-f655cc07a977.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32146550-6fc05f32-bcd9-11e7-9778-3e37508e3962.png
