### ISSUE TITLE
TextCrafter 2 ~ Craft & Share Text

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3480]
**App Name:** TextCrafter 2 ~ Craft & Share Text
**Bundle ID:** TextCrafter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=394912961">394912961</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/textcrafter-2-craft-share/id394912961?mt=8&uo=4">https://itunes.apple.com/us/app/textcrafter-2-craft-share/id394912961?mt=8&uo=4</a>
**App Version:** 2.5.0
**Seller:** Talal Haj Bakry
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mysk/id394912964?uo=4>© Mysk</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/54/d5/b6/54d5b6a2-8c44-45dc-6d49-719cd6d3adfa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19523845/0dc684da-961c-11e6-9744-3d31f5338e23.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19523845/0dc684da-961c-11e6-9744-3d31f5338e23.png)
https://cloud.githubusercontent.com/assets/20930745/19523845/0dc684da-961c-11e6-9744-3d31f5338e23.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19523867/239a3964-961c-11e6-8c64-ec2c55258050.png
