### ISSUE TITLE
E! News

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3482]
**App Name:** E! News
**Bundle ID:** com.eonline.E
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=313624917">313624917</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/e-news/id313624917?uo=4">https://apps.apple.com/us/app/e-news/id313624917?uo=4</a>
**App Version:** 5.0.15
**Seller:** E! Entertainment Television, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/e-entertainment-television-inc/id313624920?uo=4">© E! Entertainment Television, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/97/38/10/9738101e-59c5-1ec9-4808-d5e2cc8cf85c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387522-d62b8080-9aa4-11e9-8c67-8bd3855a770e.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387522-d62b8080-9aa4-11e9-8c67-8bd3855a770e.png)
https://user-images.githubusercontent.com/20930745/60387522-d62b8080-9aa4-11e9-8c67-8bd3855a770e.png

Source:
https://user-images.githubusercontent.com/20930745/60387523-d7f54400-9aa4-11e9-840b-fd73fdccf88c.png
