### ISSUE TITLE
PicPlayPost

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3486]
**App Name:** PicPlayPost
**Bundle ID:** com.flambestudios.videoinframe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498127541">498127541</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/picplaypost/id498127541?mt=8&uo=4">https://itunes.apple.com/us/app/picplaypost/id498127541?mt=8&uo=4</a>
**App Version:** 6.18
**Seller:** Mixcord Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mixcord-inc./id336456537?uo=4>© Mixcord Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/f2/54/08/f2540821-1cf4-061b-17b2-9481eca99df3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19523308/6482f274-961a-11e6-9122-a61a0284f3b2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19523308/6482f274-961a-11e6-9122-a61a0284f3b2.png)
https://cloud.githubusercontent.com/assets/20930745/19523308/6482f274-961a-11e6-9122-a61a0284f3b2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19523364/8ed8f08c-961a-11e6-8a9d-7f83f8b17320.png
