### ISSUE TITLE
DailyCost － Personal Finance

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3487]
**App Name:** DailyCost － Personal Finance
**Bundle ID:** com.gpl.dailycost
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=566587079">566587079</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dailycost-personal-finance/id566587079?mt=8&uo=4">https://itunes.apple.com/us/app/dailycost-personal-finance/id566587079?mt=8&uo=4</a>
**App Version:** 1.8.1
**Seller:** Guopeng Liang
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/guopeng-liang/id566587082?uo=4">© Guopeng Liang</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/18/ad/89/18ad89d2-c96d-0cce-48a3-3f5508d8ea51/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19932916/fc3ab906-a111-11e6-8729-d842cd2f5fa2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19932916/fc3ab906-a111-11e6-8729-d842cd2f5fa2.png)
https://cloud.githubusercontent.com/assets/20930745/19932916/fc3ab906-a111-11e6-8729-d842cd2f5fa2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19932939/16abe382-a112-11e6-9d67-949fa69bbdc5.png)
