### ISSUE TITLE
MAX GO

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3488]
**App Name:** MAX GO
**Bundle ID:** com.hbo.maxgo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=453560335">453560335</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/max-go/id453560335?mt=8&uo=4">https://itunes.apple.com/us/app/max-go/id453560335?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** Home Box Office Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hbo/id300988148?uo=4>© HBO</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/fa/3e/54/fa3e5474-d548-8dc3-7068-4e97b63c7d57/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18616496/cb0c6b7c-7d8a-11e6-85c0-c81b719262f4.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18616496/cb0c6b7c-7d8a-11e6-85c0-c81b719262f4.png)

https://cloud.githubusercontent.com/assets/3704186/18616496/cb0c6b7c-7d8a-11e6-85c0-c81b719262f4.png

https://cloud.githubusercontent.com/assets/3704186/18616497/d1d44fb0-7d8a-11e6-83b7-2bc470449bab.png
