### ISSUE TITLE
myTifi remote for Samsung TV

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3490]
**App Name:** myTifi remote for Samsung TV
**Bundle ID:** com.iMKapps.TifiRemote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441912305">441912305</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mytifi-remote-for-samsung-tv/id441912305?mt=8&uo=4">https://itunes.apple.com/us/app/mytifi-remote-for-samsung-tv/id441912305?mt=8&uo=4</a>
**App Version:** 6.5.0
**Seller:** Martijn Koopman
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/imkapps/id329600973?uo=4>© iMKapps</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/be/3a/7c/be3a7c4e-7c11-c898-5cfc-e692ae9c3713/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18478043/21aa53c2-79d0-11e6-9111-4e830ee8721f.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18478043/21aa53c2-79d0-11e6-9111-4e830ee8721f.png)
https://cloud.githubusercontent.com/assets/20930745/18478043/21aa53c2-79d0-11e6-9111-4e830ee8721f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18478063/33375400-79d0-11e6-9f8e-a1d04f6ff906.png
