### ISSUE TITLE
Unit Converter ∞

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3491]
**App Name:** Unit Converter ∞
**Bundle ID:** com.incpt.mobis.ConverterInfinity
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=539102182">539102182</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/unit-converter/id539102182?mt=8&uo=4">https://itunes.apple.com/us/app/unit-converter/id539102182?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** An Truong
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/incpt-mobis/id445261166?uo=4">© Incpt.Mobis</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/3b/15/bf/3b15bfc0-29e2-14e3-2e71-8eefb8d07caa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39955482-88390f7a-55cf-11e8-969c-f9dc0f578cdc.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39955482-88390f7a-55cf-11e8-969c-f9dc0f578cdc.png)
https://user-images.githubusercontent.com/2068130/39955482-88390f7a-55cf-11e8-969c-f9dc0f578cdc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39955486-983c8456-55cf-11e8-8c3b-cad0b6e05bd8.png
