### ISSUE TITLE
Recordium Pro - voice recorder, record memos and note taking

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3492]
**App Name:** Recordium Pro - voice recorder, record memos and note taking
**Bundle ID:** com.ivysoft.powerrecord
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=637494062">637494062</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/recordium-pro-voice-recorder/id637494062?mt=8&uo=4">https://itunes.apple.com/us/app/recordium-pro-voice-recorder/id637494062?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Mohammad Divband
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pichak-co./id500480095?uo=4">© Pichak co.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/37/11/50/37115032-3e7e-9915-6ec9-ef97ffc5b46b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19932453/806b640c-a110-11e6-8f40-169f4d21689b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19932453/806b640c-a110-11e6-8f40-169f4d21689b.png)
https://cloud.githubusercontent.com/assets/20930745/19932453/806b640c-a110-11e6-8f40-169f4d21689b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19932479/9cac13d2-a110-11e6-9bd3-bfe71fabaeec.png
