### ISSUE TITLE
ZappoTV

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3494]
**App Name:** ZappoTV
**Bundle ID:** tv.zappo.appstore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406973397">406973397</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zappotv/id406973397?mt=8&uo=4">https://itunes.apple.com/us/app/zappotv/id406973397?mt=8&uo=4</a>
**App Version:** 2.6.4
**Seller:** ZappoTV, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zappotv-inc./id406973400?uo=4>© ZappoTV, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/6c/63/e9/6c63e95e-c9d2-7c88-7387-3b03cb12339e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19521999/f2b0cecc-9615-11e6-8bad-212af6f0fe27.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19521999/f2b0cecc-9615-11e6-8bad-212af6f0fe27.png)
https://cloud.githubusercontent.com/assets/20930745/19521999/f2b0cecc-9615-11e6-8bad-212af6f0fe27.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19522037/0bb4ddaa-9616-11e6-9001-dcba3bfc72e1.png
