### ISSUE TITLE
Map My Run - GPS Running & Workout Tracker

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3497]
**App Name:** Map My Run - GPS Running & Workout Tracker
**Bundle ID:** Q5AWL8WCY6.iMapMyRun
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=291890420">291890420</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/map-my-run-gps-running-workout/id291890420?mt=8&uo=4">https://itunes.apple.com/us/app/map-my-run-gps-running-workout/id291890420?mt=8&uo=4</a>
**App Version:** 16.9.0
**Seller:** MapMyFitness
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/under-armour/id291890423?uo=4>© Under Armour</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/c0/4b/f6/c04bf679-8ea3-4564-2ed3-682bd88db8f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19311132/4b0b08d2-908d-11e6-9d5b-e220b99b5b33.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19311132/4b0b08d2-908d-11e6-9d5b-e220b99b5b33.png)
https://cloud.githubusercontent.com/assets/20930745/19311132/4b0b08d2-908d-11e6-9d5b-e220b99b5b33.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19311154/624af368-908d-11e6-9080-ea9c389b0d83.png
