### ISSUE TITLE
ProPhotos

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3498]
**App Name:** ProPhotos
**Bundle ID:** ProPhotos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=658928627">658928627</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/prophotos/id658928627?mt=8&uo=4">https://itunes.apple.com/us/app/prophotos/id658928627?mt=8&uo=4</a>
**App Version:** 1.30
**Seller:** Hubert Gostomski
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hubert-gostomski/id658928630?uo=4">© Hubert Gostomski</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/a7/9a/ed/a79aed86-d857-6083-8a11-b53b59297613/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23338048/9b52ecea-fc00-11e6-87fa-12d9a18181db.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23338048/9b52ecea-fc00-11e6-87fa-12d9a18181db.png)
https://cloud.githubusercontent.com/assets/2068130/23338048/9b52ecea-fc00-11e6-87fa-12d9a18181db.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23338054/a997fd22-fc00-11e6-8048-b0b40ac1fc56.png
