### ISSUE TITLE
OneTuner Pro Radio Player for iPhone, iPad, iPod Touch - tunein to 65 genre stream!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3499]
**App Name:** OneTuner Pro Radio Player for iPhone, iPad, iPod Touch - tunein to 65 genre stream!
**Bundle ID:** pro.onetuner.radio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=541578140">541578140</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/onetuner-pro-radio-player/id541578140?mt=8&uo=4">https://itunes.apple.com/us/app/onetuner-pro-radio-player/id541578140?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** VT1 Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vt1-media-inc./id892076113?uo=4>© VT1 Media Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/0d/c6/7b/0dc67bff-b2e8-35e9-9666-d19e7c84e23f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19521466/130b6684-9614-11e6-9c7a-66f48b50f5dc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19521091/cb654738-9612-11e6-9ab7-72ce1fda8422.png)
https://cloud.githubusercontent.com/assets/20930745/19521091/cb654738-9612-11e6-9ab7-72ce1fda8422.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19521137/f0872c8e-9612-11e6-8f9f-a43455683858.png
