### ISSUE TITLE
Tipulator

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#35]
**App Name:** Tipulator
**Bundle ID:** com.taptaptap.Tipulator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284935446">284935446</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tipulator/id284935446?mt=8&uo=4">https://itunes.apple.com/us/app/tipulator/id284935446?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Sophia Teutschler
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sophia-teutschler/id284935449?mt=8&uo=4>© Sophia Teutschler</a>
**Supported Devices:** iPhone6, iPadMini4G, iPhone4, iPodTouchFourthGen, iPodTouchFifthGen, iPadFourthGen, iPhone6Plus, iPodTouchSixthGen, iPhone5c, iPad23G, iPad2Wifi, iPadMini, iPhone-3GS, iPhone5, iPhone5s, iPadThirdGen4G, iPhone4S, iPadThirdGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/42/b7/00/42b700a1-c0cf-6653-d94e-4972f87e014b/mzl.jfljnsxd.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9677223/e2e76c8e-529c-11e5-8e58-79a3dab07b74.png)

**Comment by ivanov007** [comment]
icon was updated
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9677223/e2e76c8e-529c-11e5-8e58-79a3dab07b74.png)
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9677224/e34bcf62-529c-11e5-84ff-89feb6cd1c2e.png
