### ISSUE TITLE
Move - Daily activity to stay healthy

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3500]
**App Name:** Move - Daily activity to stay healthy
**Bundle ID:** com.kevinholesh.Move
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555994760">555994760</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/move-daily-activity-to-stay/id555994760?mt=8&uo=4">https://itunes.apple.com/us/app/move-daily-activity-to-stay/id555994760?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Kevin Holesh
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kevin-holesh/id418948953?uo=4>© Kevin Holesh</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/34/ca/80/34ca802a-9b5e-cae8-9952-f65725e7c139/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19520518/cea77cf6-9610-11e6-9239-ebd29336316a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19520518/cea77cf6-9610-11e6-9239-ebd29336316a.png)
https://cloud.githubusercontent.com/assets/20930745/19520518/cea77cf6-9610-11e6-9239-ebd29336316a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19520554/ea5ffe1e-9610-11e6-96ae-41c853b3cb5d.png
