### ISSUE TITLE
LeechTunes

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3501]
**App Name:** LeechTunes
**Bundle ID:** com.leechbiteapps.leechtunes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=345439314">345439314</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/leechtunes/id345439314?mt=8&uo=4">https://itunes.apple.com/us/app/leechtunes/id345439314?mt=8&uo=4</a>
**App Version:** 4.3.2
**Seller:** Jory Compendio
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/leechbite-apps/id345439319?uo=4">© Leechbite Apps</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/6d/5c/86/6d5c86d5-f5ee-b862-c1d9-9a8429d5b5d1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32192063-5fd433fc-bdb3-11e7-8e3d-9cbce39b1727.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32192063-5fd433fc-bdb3-11e7-8e3d-9cbce39b1727.png)
https://user-images.githubusercontent.com/2068130/32192063-5fd433fc-bdb3-11e7-8e3d-9cbce39b1727.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32192083-6f152326-bdb3-11e7-9c56-1bf69d610364.png
