### ISSUE TITLE
Phone for Google Voice & GTalk

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3509]
**App Name:** Phone for Google Voice & GTalk
**Bundle ID:** com.moplus.monkey.gv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=541829441">541829441</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/phone-for-google-voice-gtalk/id541829441?mt=8&uo=4">https://itunes.apple.com/us/app/phone-for-google-voice-gtalk/id541829441?mt=8&uo=4</a>
**App Version:** 3.0.6
**Seller:** MoPlus Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mo/id534524379?uo=4">© Mo+</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/7c/27/8c/7c278c23-725c-9bc3-4af5-ae608c215163/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36638566-c9d080b6-19f8-11e8-9a81-3dcb6c1a170c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36638566-c9d080b6-19f8-11e8-9a81-3dcb6c1a170c.png)
https://user-images.githubusercontent.com/2068130/36638566-c9d080b6-19f8-11e8-9a81-3dcb6c1a170c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36638572-d9bd8e56-19f8-11e8-892d-252feb4085e1.png
