### ISSUE TITLE
3G Unrestrictor 5 (iOS 10/9/8/7)

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#351]
**App Name:** 3G Unrestrictor 5 (iOS 10/9/8/7)
**BundleID:** com.kstreich-dev.3gunrestrictor.configapp
**iTunes ID:** none (Cydia app)
**Version:** 5.9.10
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/23517341/5d99e4bc-ff70-11e6-8eeb-cc5076c9fb4f.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23517574/1103ebba-ff71-11e6-9ab4-813ddd2dbe02.png)

**Comment by nekholm** [comment]
Needs an update; it's now known as **3G Unrestrictor 5 (iOS 10/9/8/7)**, and the bundle ID is `com.kstreich-dev.3gunrestrictor5` (I think). 

![](https://1.bp.blogspot.com/-KzDuGyntyks/UfVjl1BCxmI/AAAAAAAAl6E/PCWO9HGEotk/s1600/Icon@2x.png)

**Comment by dreamnet** [comment]
@nekholm No, the right bundle ID is `com.kstreich-dev.3gunrestrictor.configapp`, but for some reasons the icon in the master has a wrong bundle ID (com.kstreich-dev.3gunrestrictor5) - I correct it.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23517574/1103ebba-ff71-11e6-9ab4-813ddd2dbe02.png)
https://cloud.githubusercontent.com/assets/2068130/23517574/1103ebba-ff71-11e6-9ab4-813ddd2dbe02.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23517607/25049cae-ff71-11e6-8bba-f19475226fce.png
