### ISSUE TITLE
New York Knicks Official App

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3511]
**App Name:** New York Knicks Official App
**Bundle ID:** com.MSGI.Knicks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498010853">498010853</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-york-knicks-official-app/id498010853?mt=8&uo=4">https://itunes.apple.com/us/app/new-york-knicks-official-app/id498010853?mt=8&uo=4</a>
**App Version:** 16.2.4
**Seller:** Madison Square Garden
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/madison-square-garden/id405349099?uo=4">© Madison Square Garden</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/6c/c7/68/6cc768b0-4e8a-700e-c18c-a9b35147cfed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23334414/44b0aab0-fb9e-11e6-9144-a5bd48bad840.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23334414/44b0aab0-fb9e-11e6-9144-a5bd48bad840.png)
https://cloud.githubusercontent.com/assets/2068130/23334414/44b0aab0-fb9e-11e6-9144-a5bd48bad840.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23334415/52f16b64-fb9e-11e6-9e7b-e9df9c187bde.png
