### ISSUE TITLE
Google Translate

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3515]
**App Name:** Google Translate
**Bundle ID:** com.google.Translate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=414706506">414706506</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-translate/id414706506?mt=8&uo=4">https://itunes.apple.com/us/app/google-translate/id414706506?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple18/v4/94/08/8f/94088fe1-539f-42e1-2136-60178fc517f1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17994323/bb0d3aac-6b57-11e6-9dec-dd11372ad2da.png)

**Comment by PolarisBeaver** [comment]
Icon will need an update
**Original Artwork:**
<img src="http://a403.phobos.apple.com/us/r30/Purple3/v4/bd/f3/8f/bdf38fca-b287-9be9-4fd1-b861c8bf1dcf/pr_source.png?downloadKey=1423547170_96a984ed9b19990298d0c7c038219348" width="150" height="150" />

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6137567/056fd36e-b148-11e4-8e3f-cf64c2581873.png)
https://cloud.githubusercontent.com/assets/2236254/6137567/056fd36e-b148-11e4-8e3f-cf64c2581873.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6137565/01903d6a-b148-11e4-9f07-44ae4e93277d.png

**Comment by PolarisBeaver** [comment]
Looks good :thumbsup:

**Comment by MagnaMike** [comment]
@PolarisBeaver Great!

**Comment by alpcinar** [comment]
Icon updated with "G" instead of A.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17994323/bb0d3aac-6b57-11e6-9dec-dd11372ad2da.png)
https://cloud.githubusercontent.com/assets/2068130/17994323/bb0d3aac-6b57-11e6-9dec-dd11372ad2da.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17994330/c8f56374-6b57-11e6-9d60-95359455404b.png
