### ISSUE TITLE
New York Post iPhone Edition

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3517]
**App Name:** New York Post iPhone Edition
**Bundle ID:** com.nypost.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=410094240">410094240</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-york-post-iphone-edition/id410094240?mt=8&uo=4">https://itunes.apple.com/us/app/new-york-post-iphone-edition/id410094240?mt=8&uo=4</a>
**App Version:** 1.6.6
**Seller:** NYP Holdings, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nyp-holdings-inc./id375478784?uo=4">© NYP Holdings, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/ca/a7/8a/caa78a3d-a4f8-99f4-d57b-1597d3418920/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19931645/9478615a-a10d-11e6-9ebe-3c9ea7098cf6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19931645/9478615a-a10d-11e6-9ebe-3c9ea7098cf6.png)
https://cloud.githubusercontent.com/assets/20930745/19931645/9478615a-a10d-11e6-9ebe-3c9ea7098cf6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19931675/aeee9b08-a10d-11e6-93cf-5b1b9138b6c0.png
