### ISSUE TITLE
Angle Meter PRO

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#3520]
**App Name:** Angle Meter PRO
**Bundle ID:** com.iYOK.AngleMeter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386312253">386312253</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angle-meter-pro/id386312253?mt=8&uo=4">https://itunes.apple.com/us/app/angle-meter-pro/id386312253?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** nakhon phagdeechat
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nakhon-phagdeechat/id386312256?uo=4">© nakhon phagdeechat</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/8c/c3/40/8cc34015-b9e9-7460-7f8c-ef319eba6668/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32397366-c08ec4bc-c0e9-11e7-90a2-b5909a8f7eae.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32397366-c08ec4bc-c0e9-11e7-90a2-b5909a8f7eae.png)
https://user-images.githubusercontent.com/2068130/32397366-c08ec4bc-c0e9-11e7-90a2-b5909a8f7eae.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32397381-d2033ce6-c0e9-11e7-9b03-68e12fcc4f26.png
