### ISSUE TITLE
Deep Whois

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3524]
**App Name:** Deep Whois
**Bundle ID:** com.paully.deepwhois
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=328895000">328895000</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deep-whois/id328895000?mt=8&uo=4">https://itunes.apple.com/us/app/deep-whois/id328895000?mt=8&uo=4</a>
**App Version:** 1.9.11
**Seller:** Pavel Ahafonau
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pavel-ahafonau/id319585607?uo=4>© Pavel Ahafonau</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/31/fb/3e/31fb3ef7-b03f-519e-67ec-5526c18121bf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19520261/e76cd08e-960f-11e6-8c00-963950620f73.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19520261/e76cd08e-960f-11e6-8c00-963950620f73.png)https://cloud.githubusercontent.com/assets/20930745/19520261/e76cd08e-960f-11e6-8c00-963950620f73.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19520286/ff6e603a-960f-11e6-8f0c-6bd8cecb78a7.png
