### ISSUE TITLE
NBA: Official App

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3526]
**App Name:** NBA: Official App
**Bundle ID:** com.nbadigital.gametimelt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335744614">335744614</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/nba-official-app/id335744614?uo=4">https://apps.apple.com/us/app/nba-official-app/id335744614?uo=4</a>
**App Version:** 2018.8.0
**Seller:** NBA Digital
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nba-digital/id335744617?uo=4">© NBA Digital</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/42/f2/e1/42f2e1b4-234b-79f3-88c5-b3be650016eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973608-4d8f7a80-95a2-11e9-8ad4-65da7a023bda.png)

**Comment by spiroscc** [comment]
The icon has been updated and is different now

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19228831/3234dc2c-8ec9-11e6-90c0-d1a6aeece24f.png)
https://cloud.githubusercontent.com/assets/20930745/19228831/3234dc2c-8ec9-11e6-90c0-d1a6aeece24f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19228840/404d22e2-8ec9-11e6-9c5f-4d06db4e7c9b.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973608-4d8f7a80-95a2-11e9-8ad4-65da7a023bda.png)
https://user-images.githubusercontent.com/20930745/59973608-4d8f7a80-95a2-11e9-8ad4-65da7a023bda.png

Source:
https://user-images.githubusercontent.com/20930745/59973609-4ec0a780-95a2-11e9-98e9-eb51100625a1.png
