### ISSUE TITLE
 All-in Fitness: 1200 Exercises, Workouts, Calorie Counter, BMI calculator by Sport.com

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3527]
**App Name:** All-in Fitness: 1200 Exercises, Workouts, Calorie Counter, BMI calculator by Sport.com
**Bundle ID:** com.plussports.fitness
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571227995">571227995</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/all-in-fitness-1200-exercises/id571227995?mt=8&uo=4">https://itunes.apple.com/us/app/all-in-fitness-1200-exercises/id571227995?mt=8&uo=4</a>
**App Version:** 1.9.1
**Seller:** NELURRA HOLDINGS LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/plus-sports/id571227998?uo=4>© Plus Sports</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/0f/19/68/0f1968ae-7cc2-93d3-b346-b7ff79d04fff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19520035/de19e09a-960e-11e6-9b5a-5e6e212750ec.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19520035/de19e09a-960e-11e6-9b5a-5e6e212750ec.png)
https://cloud.githubusercontent.com/assets/20930745/19520035/de19e09a-960e-11e6-9b5a-5e6e212750ec.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19520051/faedec5c-960e-11e6-83f2-463acc3e0cd3.png
