### ISSUE TITLE
Free VPN - Onavo Protect

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3528]
**App Name:** Free VPN - Onavo Protect
**Bundle ID:** com.onavo.protect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=577491499">577491499</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/free-vpn-onavo-protect/id577491499?mt=8&uo=4">https://itunes.apple.com/us/app/free-vpn-onavo-protect/id577491499?mt=8&uo=4</a>
**App Version:** 1.11
**Seller:** Onavo, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/onavo-inc./id718147442?uo=4>© Onavo, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/2c/69/6d/2c696d09-a81f-8b6a-4856-b69ac6fbcd3e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18721335/4538c254-8030-11e6-9ca4-fce0d20eb458.png)

**Comment by alpcinar** [comment]
Not themed after 5.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18721335/4538c254-8030-11e6-9ca4-fce0d20eb458.png)
https://cloud.githubusercontent.com/assets/20930745/18721335/4538c254-8030-11e6-9ca4-fce0d20eb458.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18721343/53efda4e-8030-11e6-9d80-229d34b91d0f.png
