### ISSUE TITLE
Clue Word

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3532]
**App Name:** Clue Word
**Bundle ID:** com.pokami.clueword
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=578528512">578528512</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clue-word/id578528512?mt=8&uo=4">https://itunes.apple.com/us/app/clue-word/id578528512?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Sonali Patel
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pokami/id545016446?uo=4">© Pokami</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/aa/d9/2e/aad92e3b-637f-6474-1d1a-4586ebaf7b1f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19930084/1094fdd6-a107-11e6-96de-b2d7d26c528f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19930084/1094fdd6-a107-11e6-96de-b2d7d26c528f.png)
https://cloud.githubusercontent.com/assets/20930745/19930084/1094fdd6-a107-11e6-96de-b2d7d26c528f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19930106/2f2ba498-a107-11e6-9bba-a9d8755d830b.png
