### ISSUE TITLE
SiriusXM-Music, Comedy, Sports

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3538]
**App Name:** SiriusXM-Music, Comedy, Sports
**Bundle ID:** com.siriusxm.siriusxmonline
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=317951436">317951436</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/siriusxm-music-comedy-sports/id317951436?uo=4">https://apps.apple.com/us/app/siriusxm-music-comedy-sports/id317951436?uo=4</a>
**App Version:** 5.5.1
**Seller:** SIRIUS XM Radio Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sirius-xm-radio-inc/id317951439?uo=4">© SIRIUS XM Radio Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/79/c1/ec/79c1ec1a-abba-b5ba-4150-424e6d08c96d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61991634-418c5200-b053-11e9-9e66-2a74925cb311.png)

**Comment by boxermansr** [comment]
This one needs updating, please, for the -larger format. :) (I won't post on every app that I have that needs re-themed, unless that's what we're supposed to do), but figured I'd start with this one, if that is the protocol.

Thanks.

**Comment by dreamnet** [comment]
@boxermansr That's fine.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18238023/c8dd2208-7338-11e6-94f0-0b40ec46e208.png)
https://cloud.githubusercontent.com/assets/2068130/18238023/c8dd2208-7338-11e6-94f0-0b40ec46e208.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18238026/d848e092-7338-11e6-9614-9f2ba31711df.png

**Comment by XPEric** [comment]
Needs update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61991634-418c5200-b053-11e9-9e66-2a74925cb311.png)
https://user-images.githubusercontent.com/2068130/61991634-418c5200-b053-11e9-9e66-2a74925cb311.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/61991642-55d04f00-b053-11e9-95ca-65f4a79cdb53.png
