### ISSUE TITLE
Napster - Top Music & Radio

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3543]
**App Name:** Napster - Top Music & Radio
**Bundle ID:** com.rhapsody.iphone.Rhapsody3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=584557117">584557117</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/napster-top-music-radio/id584557117?mt=8&uo=4">https://itunes.apple.com/us/app/napster-top-music-radio/id584557117?mt=8&uo=4</a>
**App Version:** 5.5.4
**Seller:** Rhapsody International Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rhapsody-international-inc./id366725704?uo=4>© Rhapsody International Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/5d/d0/ce/5dd0ce83-9dcc-cf1f-b356-2b21914ea3b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19519680/5089923a-960d-11e6-8461-e559fc8fb7ec.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19519680/5089923a-960d-11e6-8461-e559fc8fb7ec.png)
https://cloud.githubusercontent.com/assets/20930745/19519680/5089923a-960d-11e6-8461-e559fc8fb7ec.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19519703/68df77b4-960d-11e6-953e-7665bd099fd8.png
