### ISSUE TITLE
PureVPN - Complete Online Privacy & Protection

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3544]
**App Name:** PureVPN - Complete Online Privacy & Protection
**Bundle ID:** com.purevpn.ios.PureVPN
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=594506418">594506418</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/purevpn-complete-online-privacy/id594506418?mt=8&uo=4">https://itunes.apple.com/us/app/purevpn-complete-online-privacy/id594506418?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** GZ Systems Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/purevpn/id594506421?uo=4>© PureVPN</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/7e/07/5f/7e075f1f-cc8f-8bfc-f621-11ffc6ef5679/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19519400/26a4dda4-960c-11e6-8cea-5214d14ece72.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19519400/26a4dda4-960c-11e6-8cea-5214d14ece72.png)
https://cloud.githubusercontent.com/assets/20930745/19519400/26a4dda4-960c-11e6-8cea-5214d14ece72.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19519415/3c9dc544-960c-11e6-9177-d051a217e9c8.png
