### ISSUE TITLE
Battery Manager Pro - Best Battery App

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3546]
**App Name:** Battery Manager Pro - Best Battery App
**Bundle ID:** com.ritesh.batterapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=353995401">353995401</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/battery-manager-pro-best-battery/id353995401?mt=8&uo=4">https://itunes.apple.com/us/app/battery-manager-pro-best-battery/id353995401?mt=8&uo=4</a>
**App Version:** 4.2.5
**Seller:** RITESH RANJAN
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tap-is-fun/id353995404?uo=4>© Tap is Fun</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/a4/22/7d/a4227d5f-a315-b67a-5f22-be966978ad08/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19519210/3d8a4d98-960b-11e6-86a5-eb25e0c39a17.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19519210/3d8a4d98-960b-11e6-86a5-eb25e0c39a17.png)
https://cloud.githubusercontent.com/assets/20930745/19519210/3d8a4d98-960b-11e6-86a5-eb25e0c39a17.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19519233/55273ba0-960b-11e6-9c42-0930b4cd7934.png
