### ISSUE TITLE
SpeakToSnooze Pro - Alarm clock with voice control commands to snooze and turn off your alarm!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3553]
**App Name:** SpeakToSnooze Pro - Alarm clock with voice control commands to snooze and turn off your alarm!
**Bundle ID:** com.speaktosnooze.speaktosnoozepro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598902849">598902849</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/speaktosnooze-pro-alarm-clock/id598902849?mt=8&uo=4">https://itunes.apple.com/us/app/speaktosnooze-pro-alarm-clock/id598902849?mt=8&uo=4</a>
**App Version:** 4.8
**Seller:** Jason Tongbai
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/j-labs/id529000775?uo=4">© j labs</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/df/ac/67/dfac67d9-b8cc-25a7-054e-943772d39d31/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19929485/e14c0658-a103-11e6-8b02-7d1428ee9bb5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19929485/e14c0658-a103-11e6-8b02-7d1428ee9bb5.png)
https://cloud.githubusercontent.com/assets/20930745/19929485/e14c0658-a103-11e6-8b02-7d1428ee9bb5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19929535/20fd48e8-a104-11e6-8f0e-3c16a9440c4f.png
