### ISSUE TITLE
Text Free: Free Calling, Texting now with Textfree

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3554]
**App Name:** Text Free: Free Calling, Texting now with Textfree
**Bundle ID:** com.pinger.textfreeVoiceWithVoicemail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=470580739">470580739</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/text-free-free-calling-texting/id470580739?mt=8&uo=4">https://itunes.apple.com/us/app/text-free-free-calling-texting/id470580739?mt=8&uo=4</a>
**App Version:** 9.11
**Seller:** Pinger, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pinger-inc./id299102705?uo=4">© Pinger, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/0a/17/7e/0a177ece-2aba-982a-2871-19081193db8e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19928952/3cc89a1c-a101-11e6-95d1-fb26ca12f996.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19928952/3cc89a1c-a101-11e6-95d1-fb26ca12f996.png)
https://cloud.githubusercontent.com/assets/20930745/19928952/3cc89a1c-a101-11e6-95d1-fb26ca12f996.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19928971/5478733a-a101-11e6-9b79-41b6dfc35838.png
