### ISSUE TITLE
Budget 101

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3555]
**App Name:** Budget 101
**Bundle ID:** com.SimpleSimonApps.Budget101
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=513666432">513666432</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/budget-101/id513666432?mt=8&uo=4">https://itunes.apple.com/us/app/budget-101/id513666432?mt=8&uo=4</a>
**App Version:** 6.2
**Seller:** Shimon Hochman
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/simplesimonapps/id513666435?uo=4>© SimpleSimonApps</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/bb/4e/1d/bb4e1d93-4095-4b75-1876-446567265db3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19518884/b6440352-9609-11e6-8e12-35ca2e858ddb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19518884/b6440352-9609-11e6-8e12-35ca2e858ddb.png)
https://cloud.githubusercontent.com/assets/20930745/19518884/b6440352-9609-11e6-8e12-35ca2e858ddb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19518922/defd3e4e-9609-11e6-83f8-b545ba435d34.png
