### ISSUE TITLE
Ergonomics

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3558]
**App Name:** Ergonomics
**Bundle ID:** com.swanmobile.ergoapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547689680">547689680</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ergonomics/id547689680?mt=8&uo=4">https://itunes.apple.com/us/app/ergonomics/id547689680?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Stand Up Apps, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stand-up-apps-inc./id344006549?uo=4>© Stand Up Apps, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/a7/73/f6/a773f679-d721-d0ae-2f30-68bc9b0a07fb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19518560/33d35590-9608-11e6-86fc-fba11443580e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19518560/33d35590-9608-11e6-86fc-fba11443580e.png)
https://cloud.githubusercontent.com/assets/20930745/19518560/33d35590-9608-11e6-86fc-fba11443580e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19518596/51db52fe-9608-11e6-8c6d-708dca0b861c.png
