### ISSUE TITLE
iBomber Defense Pacific

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#356]
**App Name:** iBomber Defense Pacific
**Bundle ID:** com.chillingo.ibomberpacific
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498249308">498249308</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ibomber-defense-pacific/id498249308?mt=8&uo=4">https://itunes.apple.com/us/app/ibomber-defense-pacific/id498249308?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Cobra Mobile Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cobra-mobile-limited/id290142990?uo=4">© Cobra Mobile Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/c9/e0/27/c9e02716-fe1d-01df-5a4d-956390f2501c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23330791/b6bb7d98-fb57-11e6-855d-f99addb23ce9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23330791/b6bb7d98-fb57-11e6-855d-f99addb23ce9.png)
https://cloud.githubusercontent.com/assets/2068130/23330791/b6bb7d98-fb57-11e6-855d-f99addb23ce9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23330793/c3c5e988-fb57-11e6-89af-062705ae2d6e.png
