### ISSUE TITLE
eDrops Classic - Classical Music Pinball

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3562]
**App Name:** eDrops Classic - Classical Music Pinball
**Bundle ID:** noe.guerrero.edropsc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=515254842">515254842</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/edrops-classic-classical-music/id515254842?mt=8&uo=4">https://itunes.apple.com/us/app/edrops-classic-classical-music/id515254842?mt=8&uo=4</a>
**App Version:** 3.71
**Seller:** NOE GUERRERO
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/noe-guerrero/id440992372?uo=4">© NOE GUERRERO</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple18/v4/0b/4c/6b/0b4c6b90-b3ab-db0a-991b-a3db1b686a91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19928754/3d334c0a-a100-11e6-9f38-bd3247224d39.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19928754/3d334c0a-a100-11e6-9f38-bd3247224d39.png)
https://cloud.githubusercontent.com/assets/20930745/19928754/3d334c0a-a100-11e6-9f38-bd3247224d39.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19928773/55524ade-a100-11e6-9430-8c4fa6c3035a.png
