### ISSUE TITLE
ESPN Fantasy Sports - Play Football, Baseball, Basketball, Hockey and More Games

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3563]
**App Name:** ESPN Fantasy Sports - Play Football, Baseball, Basketball, Hockey and More Games
**Bundle ID:** com.espn.fantasyFootball
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555376968">555376968</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/espn-fantasy-sports-play-football/id555376968?mt=8&uo=4">https://itunes.apple.com/us/app/espn-fantasy-sports-play-football/id555376968?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** ESPN Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/espn/id317469187?uo=4>© ESPN</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple32/v4/25/f0/ab/25f0ab66-701c-1b53-ed65-f163f053c40a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17552004/6ea81c9c-5efd-11e6-987f-cdfda37077cb.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** ESPN Fantasy Sports - Play Football, Baseball, Basketball, Hockey and More Games
**Bundle ID:** com.espn.fantasyFootball
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555376968">555376968</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/espn-fantasy-sports-play-football/id555376968?mt=8&uo=4">https://itunes.apple.com/us/app/espn-fantasy-sports-play-football/id555376968?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** ESPN Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/espn/id317469187?uo=4>© ESPN</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple32/v4/25/f0/ab/25f0ab66-701c-1b53-ed65-f163f053c40a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17552004/6ea81c9c-5efd-11e6-987f-cdfda37077cb.png)
https://cloud.githubusercontent.com/assets/2068130/17552004/6ea81c9c-5efd-11e6-987f-cdfda37077cb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17552009/7b9ad2dc-5efd-11e6-9a55-5348ed1e4ada.png
