### ISSUE TITLE
XBMC

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3574]
**App Name:** XBMC
**Bundle ID:** org.xbmc.xbmc-ios
**iTunes ID:** none (Cydia app)
**iPhone Icon Name:** 
**Icon Names:** XBMC.png
**Original Artwork:** XBMC.png
<img src="https://f.cloud.github.com/assets/3090247/1143540/b72d0462-1d44-11e3-9e44-800d713c0331.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://f.cloud.github.com/assets/2239299/1143882/947a21c8-1d5f-11e3-9c3a-e923d4055d4a.png)

**Comment by Trubbel** [comment]
It has come to my attention that XBMC changed their name to [Kodi (#5938)](https://github.com/glasklart/hd/issues/5938) and this application doesn't exist anymore.
It could probably get removed from the theme.
