### ISSUE TITLE
Photoshop Express Photo Editor

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#3580]
**App Name:** Photoshop Express Photo Editor
**Bundle ID:** com.adobe.PSMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=331975235">331975235</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/photoshop-express-photo-editor/id331975235?uo=4">https://apps.apple.com/us/app/photoshop-express-photo-editor/id331975235?uo=4</a>
**App Version:** 20.22.3
**Seller:** Adobe Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/adobe-inc/id331646274?uo=4">© Adobe Inc.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/b8/7a/ab/b87aab16-368c-b8b6-a900-193fe5c84575/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86527767-62d00200-bea2-11ea-9350-158bd7743287.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19587497/fa29536e-975e-11e6-9d2e-f28accad7b45.png)
https://cloud.githubusercontent.com/assets/10730122/19587497/fa29536e-975e-11e6-9d2e-f28accad7b45.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19587498/fa29d2ee-975e-11e6-96ea-cb84f48b0f01.png

**Comment by alpcinar** [comment]
Needs to be updated.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86527767-62d00200-bea2-11ea-9350-158bd7743287.png)
https://user-images.githubusercontent.com/2068130/86527767-62d00200-bea2-11ea-9350-158bd7743287.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86527776-72e7e180-bea2-11ea-8363-715836f36a8e.png
