### ISSUE TITLE
Pivvot

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#3581]
**App Name:** Pivvot
**Bundle ID:** com.whitakr.Pivvot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=664416929">664416929</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pivvot/id664416929?mt=8&uo=4">https://itunes.apple.com/us/app/pivvot/id664416929?mt=8&uo=4</a>
**App Version:** 1.61
**Seller:** Fixpoint Productions Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fixpoint-productions-ltd./id454091053?uo=4>© Fixpoint Productions Ltd.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/9f/f6/b3/9ff6b35b-15e0-2e91-e253-76222f325623/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18932960/d8cc4f70-85d2-11e6-9b83-1867019e5272.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18932960/d8cc4f70-85d2-11e6-9b83-1867019e5272.png)
https://cloud.githubusercontent.com/assets/20930745/18932960/d8cc4f70-85d2-11e6-9b83-1867019e5272.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18932967/e2dd9e74-85d2-11e6-8d0d-669e3880c66b.png

**Comment by BrokenCommander** [comment]
Or original size;
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18894341/aa8329c4-8512-11e6-90a6-8a065a8ee59b.png)
https://cloud.githubusercontent.com/assets/22012363/18894341/aa8329c4-8512-11e6-90a6-8a065a8ee59b.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18894337/a7a04930-8512-11e6-8a8e-f6503e63c430.png

**Comment by dreamnet** [comment]
@BrokenCommander First one is fine. 👍
