### ISSUE TITLE
Wake Alarm Clock

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3588]
**App Name:** Wake Alarm Clock
**Bundle ID:** com.tinyhearts.wake
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=616764635">616764635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wake-alarm-clock/id616764635?mt=8&uo=4">https://itunes.apple.com/us/app/wake-alarm-clock/id616764635?mt=8&uo=4</a>
**App Version:** 4.3.5
**Seller:** Tiny Hearts Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tiny-hearts-limited/id371273285?uo=4">© Tiny Hearts Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/8d/d7/48/8dd748c9-84f3-8039-26e0-5d57a94fb93f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19928337/52fc6c9e-a0fe-11e6-88f2-57bc29b3dbb8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19928337/52fc6c9e-a0fe-11e6-88f2-57bc29b3dbb8.png)
https://cloud.githubusercontent.com/assets/20930745/19928337/52fc6c9e-a0fe-11e6-88f2-57bc29b3dbb8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19928364/6e9ec212-a0fe-11e6-8647-509ef5c58242.png
