### ISSUE TITLE
T-Mobile TV

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3590]
**App Name:** T-Mobile TV
**Bundle ID:** com.tmobile.tmobiletv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=601102108">601102108</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/t-mobile-tv/id601102108?mt=8&uo=4">https://itunes.apple.com/us/app/t-mobile-tv/id601102108?mt=8&uo=4</a>
**App Version:** 7.7.49
**Seller:** T-Mobile USA, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/t-mobile/id525560781?uo=4>© T-Mobile</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/15/1e/a5/151ea5b0-39c1-5c1f-a9de-ad0486bc2799/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19518232/5c2a24bc-9606-11e6-8174-5d09de78ab8c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19518232/5c2a24bc-9606-11e6-8174-5d09de78ab8c.png)
https://cloud.githubusercontent.com/assets/20930745/19518232/5c2a24bc-9606-11e6-8174-5d09de78ab8c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19518257/7b792fb6-9606-11e6-9156-e6701ac10ce2.png
