### ISSUE TITLE
The New Jersey Lottery

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3591]
**App Name:** New Jersey Lottery
**Bundle ID:** net.njlottery.njlottery
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493036278">493036278</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-jersey-lottery/id493036278?mt=8&uo=4">https://itunes.apple.com/us/app/new-jersey-lottery/id493036278?mt=8&uo=4</a>
**App Version:** 3.9.1
**Seller:** New Jersey State Lottery Commission
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/new-jersey-state-lottery-commission/id493036281?uo=4">© New Jersey State Lottery Commission</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/91/9a/06/919a06ac-07c0-26f1-a2d2-925709c81673/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19928160/8a2cc476-a0fd-11e6-92df-8ba640586f88.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19928160/8a2cc476-a0fd-11e6-92df-8ba640586f88.png)
https://cloud.githubusercontent.com/assets/20930745/19928160/8a2cc476-a0fd-11e6-92df-8ba640586f88.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19928177/a372078e-a0fd-11e6-9713-374775dfb439.png
