### ISSUE TITLE
DataMan Next - simply track your data usage

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3596]
**App Name:** DataMan Next - simply track your data usage
**Bundle ID:** com.xvision.datamannext
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=592962356">592962356</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dataman-next-simply-track/id592962356?mt=8&uo=4">https://itunes.apple.com/us/app/dataman-next-simply-track/id592962356?mt=8&uo=4</a>
**App Version:** 10.0
**Seller:** Johnny Ixe
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/johnny-ixe/id326568233?uo=4>© Johnny Ixe</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/84/62/50/8462506d-24c2-1180-69d0-2d117ee455a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18797829/18dee3ae-81d0-11e6-8d38-c2535ed7945d.png)

**Comment by ivanov007** [comment]
needs update

**Comment by dreamnet** [comment]
Same as #5911.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18797829/18dee3ae-81d0-11e6-8d38-c2535ed7945d.png)
https://cloud.githubusercontent.com/assets/2068130/18797829/18dee3ae-81d0-11e6-8d38-c2535ed7945d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18797853/29db8612-81d0-11e6-8354-c7ddc7653f83.png
