### ISSUE TITLE
YP - Yellow Pages local search

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3597]
**App Name:** YP - Yellow Pages local search
**Bundle ID:** com.yellowpages.ypmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284806204">284806204</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yp-yellow-pages-local-search/id284806204?mt=8&uo=4">https://itunes.apple.com/us/app/yp-yellow-pages-local-search/id284806204?mt=8&uo=4</a>
**App Version:** 5.11.1
**Seller:** Yellowpages.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yellowpages.com-llc/id281970042?uo=4>© YELLOWPAGES.COM LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/f0/c8/e3/f0c8e3d5-643b-f38f-9542-fd78207e9331/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19236380/5209ce44-8ef7-11e6-9b08-3944df504ae1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19236380/5209ce44-8ef7-11e6-9b08-3944df504ae1.png)
https://cloud.githubusercontent.com/assets/20930745/19236380/5209ce44-8ef7-11e6-9b08-3944df504ae1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19236393/62dcd91e-8ef7-11e6-9ba0-6fb9a99c5268.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... i think it is to big .. but Illustrator give me this at the right size? but i don't know why? :-/

**Comment by dreamnet** [comment]
@2Qt2beStr8 ? Looks fine to me...

**Comment by 2Qt2beStr8** [comment]
.... yes, if i look today it looks also fine to me :-)
