### ISSUE TITLE
Last.fm

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3598]
**App Name:** Last.fm
**Bundle ID:** fm.last.MobileLastFM
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284916679">284916679</a>
**iPhone Icon Name:** Icon@2x.png
**Icon Names:** Icon@2x.png | Icon.png
**iTunes URL:** https://itunes.apple.com/us/app/last.fm/id284916679?mt=8&uo=4
**App Version:** 3.2.2
**Seller:** Last.fm
**Supported Devices:** iPod-touch-with-mic, iPhone, iPhone4, iPadFourthGen4G, iPodTouchThirdGen, iPadFourthGen, iPhone-3GS, iPad2Wifi, iPodTouchourthGen, iPad23G, iPadMini, iPhone5, iPadThirdGen4G, iPodTouchFifthGen, iPadMini4G, iPadThirdGen, iPhone-3G, iPad3G, iPhone5s, iPod-touch, iPhone4S, iPhone5c, iPadWifi
**Original Artwork:**
<img src="http://a690.phobos.apple.com/us/r30/Purple/v4/65/02/43/6502435a-9e60-e645-01bb-42bb051460b5/mzl.uzessmxq.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18454745/67a9908e-7946-11e6-90bd-6eab1ce5b9f4.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18454745/67a9908e-7946-11e6-90bd-6eab1ce5b9f4.png)
https://cloud.githubusercontent.com/assets/20930745/18454745/67a9908e-7946-11e6-90bd-6eab1ce5b9f4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18454769/82f13a7c-7946-11e6-8780-435f51777db1.png
