### ISSUE TITLE
Amerigo - File Manager

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3602]
**App Name:** Amerigo - File Manager
**Bundle ID:** it.ideasolutions.amerigo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=531198828">531198828</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/amerigo-file-manager/id531198828?uo=4">https://apps.apple.com/us/app/amerigo-file-manager/id531198828?uo=4</a>
**App Version:** 3.3.2
**Seller:** IdeaSolutions S.r.l.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ideasolutions-s-r-l/id412793024?uo=4">© IdeaSolutions S.r.l.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/e1/b3/5a/e1b35a50-370c-104c-e82c-16b89386c4f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979234-36be4780-95e5-11e9-80f8-6581ecfacb60.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19517884/1f303abc-9604-11e6-97cc-a2957971c5ee.png)
https://cloud.githubusercontent.com/assets/20930745/19517884/1f303abc-9604-11e6-97cc-a2957971c5ee.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19517909/444dcf44-9604-11e6-8261-54efd2070446.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979234-36be4780-95e5-11e9-80f8-6581ecfacb60.png)
https://user-images.githubusercontent.com/2068130/59979234-36be4780-95e5-11e9-80f8-6581ecfacb60.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979237-463d9080-95e5-11e9-9594-ecf57025a5b0.png
