### ISSUE TITLE
Video 2 Photo - extract still pictures from movies

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3603]
**App Name:** Video 2 Photo - extract still pictures from movies
**Bundle ID:** francis.bonnin.Video2Photo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487353844">487353844</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/video-2-photo-extract-still/id487353844?mt=8&uo=4">https://itunes.apple.com/us/app/video-2-photo-extract-still/id487353844?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Francis Bonnin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/francis-bonnin/id284043095?uo=4>© Francis Bonnin</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/e9/c3/0a/e9c30aea-078d-2922-98ef-9f44830c8597/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19517565/4d298baa-9602-11e6-9636-65402d9c017b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19517565/4d298baa-9602-11e6-9636-65402d9c017b.png)
https://cloud.githubusercontent.com/assets/20930745/19517565/4d298baa-9602-11e6-9636-65402d9c017b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19517592/686200e6-9602-11e6-9586-7bee6cb63848.png
