### ISSUE TITLE
ASE A-Series Exam Prep 2016 Edition

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3607]
**App Name:** ASE A-Series Exam Prep 2016 Edition
**Bundle ID:** com.tesolutions.ase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=594079701">594079701</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ase-series-exam-prep-2016/id594079701?mt=8&uo=4">https://itunes.apple.com/us/app/ase-series-exam-prep-2016/id594079701?mt=8&uo=4</a>
**App Version:** 6.0.9
**Seller:** Pocket Prep, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pocket-prep-inc./id478383132?uo=4>© Pocket Prep, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple22/v4/19/5b/63/195b6342-794b-917f-b25d-c0519adb9b93/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19517268/87198a2e-9600-11e6-8408-6706a79bf8e7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19517268/87198a2e-9600-11e6-8408-6706a79bf8e7.png)
https://cloud.githubusercontent.com/assets/20930745/19517268/87198a2e-9600-11e6-8408-6706a79bf8e7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19517293/a50e66c6-9600-11e6-8789-eaf263bb3d22.png
