### ISSUE TITLE
Nike+ Run Club

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3614]
**App Name:** Nike+ Run Club
**Bundle ID:** com.nike.nikeplus-gps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=387771637">387771637</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nike+-run-club/id387771637?mt=8&uo=4">https://itunes.apple.com/us/app/nike+-run-club/id387771637?mt=8&uo=4</a>
**App Version:** 5.0.3
**Seller:** Nike, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nike-inc/id301521406?uo=4>© Nike, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/06/5e/9e/065e9ed0-71f8-a218-4684-29db46901d90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18632517/14bdde16-7e78-11e6-893d-c17755c05874.png)

**Comment by grkka** [comment]
Needs update to v 5.00.0 and icon
**App Name:** Nike+ Run Club
**Bundle ID:** com.nike.nikeplus-gps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=387771637">387771637</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nike+-run-club/id387771637?mt=8&uo=4">https://itunes.apple.com/us/app/nike+-run-club/id387771637?mt=8&uo=4</a>
**App Version:** 5.0.3
**Seller:** Nike, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nike-inc/id301521406?uo=4>© Nike, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/06/5e/9e/065e9ed0-71f8-a218-4684-29db46901d90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18632517/14bdde16-7e78-11e6-893d-c17755c05874.png)
https://cloud.githubusercontent.com/assets/20930745/18632517/14bdde16-7e78-11e6-893d-c17755c05874.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18632569/6040f404-7e78-11e6-9915-142547f6e430.png
