### ISSUE TITLE
Bloons Super Monkey

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#362]
**App Name:** Bloons Super Monkey
**Bundle ID:** com.ninjakiwi.bsm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386241770">386241770</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bloons-super-monkey/id386241770?mt=8&uo=4">https://itunes.apple.com/us/app/bloons-super-monkey/id386241770?mt=8&uo=4</a>
**App Version:** 1.5.4
**Seller:** Kaiparasoft Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ninja-kiwi/id386241773?uo=4">© Ninja Kiwi</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/bd/63/f8/bd63f809-028e-1860-ed47-c7eede52d6f9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36949145-abd737b6-1fe4-11e8-902d-646f546a7907.png)
https://user-images.githubusercontent.com/2068130/36949145-abd737b6-1fe4-11e8-902d-646f546a7907.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36949155-bdea55f0-1fe4-11e8-9c77-fabf1c974a8b.png
