### ISSUE TITLE
Pixter Scanner OCR Document

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3622]
**App Name:** Pixter Scanner OCR Document
**Bundle ID:** QuanticApps.Pixter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=622615952">622615952</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pixter-scanner-ocr-document/id622615952?mt=8&uo=4">https://itunes.apple.com/us/app/pixter-scanner-ocr-document/id622615952?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Quanticapps
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/quanticapps/id378465660?uo=4">© Quanticapps</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/17/98/d4/1798d43c-6cfc-af11-4f13-529b6ccba70a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32141545-a84d4dfc-bc83-11e7-8f54-175ead0b880a.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Pixter Scanner OCR Document
**Bundle ID:** QuanticApps.Pixter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=622615952">622615952</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pixter-scanner-ocr-document/id622615952?mt=8&uo=4">https://itunes.apple.com/us/app/pixter-scanner-ocr-document/id622615952?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Quanticapps
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/quanticapps/id378465660?uo=4">© Quanticapps</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/17/98/d4/1798d43c-6cfc-af11-4f13-529b6ccba70a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32141545-a84d4dfc-bc83-11e7-8f54-175ead0b880a.png)
https://user-images.githubusercontent.com/2068130/32141545-a84d4dfc-bc83-11e7-8f54-175ead0b880a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32141547-b8b7fcc8-bc83-11e7-8c93-9e781d844c05.png
