### ISSUE TITLE
Total Cashflow HD

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3624]
**App Name:** Total Cashflow HD
**Bundle ID:** MyCashflowHD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=443987802">443987802</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/total-cashflow-hd/id443987802?mt=8&uo=4">https://itunes.apple.com/us/app/total-cashflow-hd/id443987802?mt=8&uo=4</a>
**App Version:** 1.53
**Seller:** SKYDALE DESIGNS LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/skydale-designs/id427344829?uo=4>© Skydale Designs</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/77/e6/9b/77e69b65-ddd3-3754-c988-44f58e12f322/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19516026/59bdc4a6-95fa-11e6-9775-f2daf3ff40bb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19516026/59bdc4a6-95fa-11e6-9775-f2daf3ff40bb.png)
