### ISSUE TITLE
LTE Finder

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3625]
**App Name:** LTE Finder
**Bundle ID:** lte-finder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=509600075">509600075</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lte-finder/id509600075?mt=8&uo=4">https://itunes.apple.com/us/app/lte-finder/id509600075?mt=8&uo=4</a>
**App Version:** 2015.5
**Seller:** Two Steps Beyond
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/two-steps-beyond/id371852083?uo=4">© Two Steps Beyond</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/43/4f/36/434f3661-62a0-ba42-37cc-02845b99ecef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32387989-8777f5d6-c0c6-11e7-8623-60669dc39bb6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32387989-8777f5d6-c0c6-11e7-8623-60669dc39bb6.png)
https://user-images.githubusercontent.com/2068130/32387989-8777f5d6-c0c6-11e7-8623-60669dc39bb6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32388008-96d5302a-c0c6-11e7-920a-46f8d60bfd4c.png
