### ISSUE TITLE
Texas Holdem Poker VIP

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3627]
**App Name:** Texas Holdem Poker VIP
**Bundle ID:** com.viaden.texaspokervip
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571930908">571930908</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/texas-holdem-poker-vip/id571930908?mt=8&uo=4">https://itunes.apple.com/us/app/texas-holdem-poker-vip/id571930908?mt=8&uo=4</a>
**App Version:** 2.7.5
**Seller:** Skywind Services Cyprus Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/skywind-services-cyprus-ltd/id571865686?uo=4">© Skywind Services Cyprus Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/02/a7/85/02a785ea-3a0d-bb75-2ffc-110528b9828d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40585392-43263464-61b2-11e8-86da-77898b1f9f85.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40585392-43263464-61b2-11e8-86da-77898b1f9f85.png)
https://user-images.githubusercontent.com/2068130/40585392-43263464-61b2-11e8-86da-77898b1f9f85.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/40585398-55c1c3cc-61b2-11e8-96ba-9b040ad290b5.png
