### ISSUE TITLE
Citrix Receiver

### ISSUE THREAD

**Issue by hfcm** [glasklart/hd#3630]
**App Name:** Citrix Receiver
**Bundle ID:** com.citrix.ReceiveriPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=363501921">363501921</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/citrix-receiver/id363501921?mt=8&uo=4">https://itunes.apple.com/us/app/citrix-receiver/id363501921?mt=8&uo=4</a>
**App Version:** 7.1.1
**Seller:** Citrix Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/citrix-systems-inc./id308708536?uo=4>© Citrix Systems, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/55/1a/8c/551a8ccc-1e8b-51e4-1182-0899bbc73027/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18793303/13d92902-8188-11e6-8219-383a13fcd9fb.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Citrix Receiver
**Bundle ID:** com.citrix.ReceiveriPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=363501921">363501921</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/citrix-receiver/id363501921?mt=8&uo=4">https://itunes.apple.com/us/app/citrix-receiver/id363501921?mt=8&uo=4</a>
**App Version:** 7.1.1
**Seller:** Citrix Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/citrix-systems-inc./id308708536?uo=4>© Citrix Systems, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/55/1a/8c/551a8ccc-1e8b-51e4-1182-0899bbc73027/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18793303/13d92902-8188-11e6-8219-383a13fcd9fb.png)

https://cloud.githubusercontent.com/assets/3704186/18793303/13d92902-8188-11e6-8219-383a13fcd9fb.png

https://cloud.githubusercontent.com/assets/3704186/18793307/18e9445e-8188-11e6-96a1-cd538603a1d5.png
