### ISSUE TITLE
SpinCam

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3640]
**App Name:** SpinCam
**Bundle ID:** net.spincam.app1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=503987242">503987242</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spincam/id503987242?mt=8&uo=4">https://itunes.apple.com/us/app/spincam/id503987242?mt=8&uo=4</a>
**App Version:** 1.5.3
**Seller:** Spot Metrix Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/spot-metrix-inc./id503987245?uo=4">© Spot Metrix, Inc.</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/2d/cf/ab/2dcfabc8-f455-d7c1-182b-5a796eefd779/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20237933/15875ede-a8e0-11e6-8978-e1c5781cb916.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20237933/15875ede-a8e0-11e6-8978-e1c5781cb916.png)
https://cloud.githubusercontent.com/assets/20930745/20237933/15875ede-a8e0-11e6-8978-e1c5781cb916.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20237937/2d58d7b8-a8e0-11e6-993e-e0df1c0da258.png
