### ISSUE TITLE
flinc - Ridesharing

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#3641]
**App Name:** flinc - Ridesharing
**Bundle ID:** org.flinc.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=430305307">430305307</a>
**iPhone Icon Name:** flinc_appicon@2x.png
**Icon Names:** flinc_appicon.png | flinc_appicon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/flinc-social-mobility-network/id430305307?mt=8&uo=4
**App Version:** 5.8.1
**Seller:** flinc AG
**Supported Devices:** iPad3G, iPhone-3GS, iPadFourthGen4G, iPad2Wifi, iPhone5c, iPadWifi, iPadThirdGen4G, iPadMini, iPadFourthGen, iPhone5s, iPadThirdGen, iPadMini4G, iPhone4, iPad23G, iPodTouchFifthGen, iPodTouchourthGen, iPhone5, iPhone4S, iPodTouchThirdGen
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60393624-b5047780-9b18-11e9-8328-93cf75abaf53.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393634-c3529380-9b18-11e9-8676-baebe687cc50.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393634-c3529380-9b18-11e9-8676-baebe687cc50.png)
https://user-images.githubusercontent.com/2068130/60393634-c3529380-9b18-11e9-8676-baebe687cc50.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60393640-d8c7bd80-9b18-11e9-9d72-77e15b80582c.png
