### ISSUE TITLE
Pocket: Save Articles and Videos to View Later

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#3643]
**App Name:** Pocket: Save Articles and Videos to View Later
**Bundle ID:** com.ideashower.ReadItLaterPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=309601447">309601447</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-save-articles-videos/id309601447?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-save-articles-videos/id309601447?mt=8&uo=4</a>
**App Version:** 6.3.2
**Seller:** Read It Later, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/read-it-later-inc/id848647407?uo=4>© Read It Later, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple30/v4/44/ea/7a/44ea7ad5-0db4-c48b-17bc-ee953b78aad9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18238114/b5f87c68-7339-11e6-99f5-58244b97d425.png)

**Comment by l8er4now** [comment]
Collection version needs resizing.

**App Name:** Pocket: Save Articles and Videos to View Later
**Bundle ID:** com.ideashower.ReadItLaterPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=309601447">309601447</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-save-articles-videos/id309601447?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-save-articles-videos/id309601447?mt=8&uo=4</a>
**App Version:** 6.3.2
**Seller:** Read It Later, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/read-it-later-inc/id848647407?uo=4>© Read It Later, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple30/v4/44/ea/7a/44ea7ad5-0db4-c48b-17bc-ee953b78aad9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18238114/b5f87c68-7339-11e6-99f5-58244b97d425.png)
https://cloud.githubusercontent.com/assets/2068130/18238114/b5f87c68-7339-11e6-99f5-58244b97d425.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18238116/c52e7656-7339-11e6-936b-61750c21d91b.png
