### ISSUE TITLE
Apple Store

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#3644]
**App Name:** Apple Store
**Bundle ID:** com.apple.store.Jolly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375380948">375380948</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/apple-store/id375380948?mt=8&uo=4">https://itunes.apple.com/us/app/apple-store/id375380948?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/apple/id284417353?mt=12&uo=4>© Apple</a>
**Supported Devices:** iPadThirdGen, iPadFourthGen4G, iPhone5c, iPadMini, iPhone4S, iPadFourthGen, iPad2Wifi, iPadThirdGen4G, iPhone4, iPodTouchFifthGen, iPhone5s, iPhone6, iPhone6Plus, iPadMini4G, iPad23G, iPhone5
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/82/bd/90/82bd90c7-f673-718c-7c32-ad9db7591ea6/mzl.hfuxogmw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8296124/412dd216-1912-11e5-9095-a81006db28c9.png)

**Comment by Trubbel** [comment]
The icon has been updated.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8296124/412dd216-1912-11e5-9095-a81006db28c9.png)
https://cloud.githubusercontent.com/assets/3090247/8296124/412dd216-1912-11e5-9095-a81006db28c9.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/8296123/412d87fc-1912-11e5-9ccc-94e85fab4ac4.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
