### ISSUE TITLE
Asana: organize tasks & work

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#3649]
**App Name:** Asana: organize tasks & work
**Bundle ID:** com.asana.Asana
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489969512">489969512</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/asana-organize-tasks-work/id489969512?mt=8&uo=4">https://itunes.apple.com/us/app/asana-organize-tasks-work/id489969512?mt=8&uo=4</a>
**App Version:** 6.3.0
**Seller:** Asana, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/asana-inc/id489969515?uo=4">© Asana, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/3b/26/94/3b2694e0-1acd-1bf4-ccb9-d226633c73b5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32094208-3fdf6230-baff-11e7-8c1c-6f48bc1e0058.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8522608/09b4d5ee-23f0-11e5-9d83-ade38d2c2e2a.png)
https://cloud.githubusercontent.com/assets/10730122/8522608/09b4d5ee-23f0-11e5-9d83-ade38d2c2e2a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8522604/06b20de4-23f0-11e5-8096-4a26512cd383.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Asana: organize tasks & work
**Bundle ID:** com.asana.Asana
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489969512">489969512</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/asana-organize-tasks-work/id489969512?mt=8&uo=4">https://itunes.apple.com/us/app/asana-organize-tasks-work/id489969512?mt=8&uo=4</a>
**App Version:** 6.3.0
**Seller:** Asana, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/asana-inc/id489969515?uo=4">© Asana, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/3b/26/94/3b2694e0-1acd-1bf4-ccb9-d226633c73b5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32094208-3fdf6230-baff-11e7-8c1c-6f48bc1e0058.png)
https://user-images.githubusercontent.com/2068130/32094208-3fdf6230-baff-11e7-8c1c-6f48bc1e0058.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32094225-4efb9734-baff-11e7-898d-ddc9415046bd.png
