### ISSUE TITLE
Cookpad - Recipe Sharing

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#3651]
**App Name:** Cookpad - Recipe Sharing
**Bundle ID:** com.allthecooks.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=585332633">585332633</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cookpad-recipe-sharing/id585332633?uo=4">https://apps.apple.com/us/app/cookpad-recipe-sharing/id585332633?uo=4</a>
**App Version:** 9.39.0
**Seller:** COOKPAD INC. (CA)
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cookpad-inc-ca/id793282416?uo=4">© COOKPAD INC. (CA)</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/9f/88/0d/9f880d72-07ed-c66c-56e7-2389606da154/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60380755-fa5a7380-9a4a-11e9-844a-4e9c4b8ce911.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60380755-fa5a7380-9a4a-11e9-844a-4e9c4b8ce911.png)
https://user-images.githubusercontent.com/2068130/60380755-fa5a7380-9a4a-11e9-844a-4e9c4b8ce911.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60380763-08a88f80-9a4b-11e9-961b-829f98f24de7.png
