### ISSUE TITLE
Flightradar24 - Flight Tracker

### ISSUE THREAD

**Issue by gperbost** [glasklart/hd#3654]
**App Name:** Flightradar24 - Flight Tracker
**Bundle ID:** se.resenatverket.FlightRadar24
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382069612">382069612</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flightradar24-flight-tracker/id382069612?mt=8&uo=4">https://itunes.apple.com/us/app/flightradar24-flight-tracker/id382069612?mt=8&uo=4</a>
**App Version:** 6.6.2
**Seller:** Flightradar24 AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/flightradar24-ab/id726928879?uo=4>© Flightradar24 AB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/da/87/3b/da873b37-8cd7-eb31-f6df-4788d4bdc48f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13418738/7321e320-df78-11e5-8aeb-8d884d6827d4.png)

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13418738/7321e320-df78-11e5-8aeb-8d884d6827d4.png)
https://cloud.githubusercontent.com/assets/2068130/13418738/7321e320-df78-11e5-8aeb-8d884d6827d4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13418749/8893f1d0-df78-11e5-9d8c-85b7d4e0cfdc.png

**Comment by dreamnet** [comment]
Icon is [already in the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/se.resenatverket.FlightRadar24@2x.png). No further action needed.
