### ISSUE TITLE
Prosper Daily - Money Tracking, Free Credit Score & ID Protection

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3656]
**App Name:** Prosper Daily - Money Tracking, Free Credit Score & ID Protection
**Bundle ID:** com.BillGuard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=602710567">602710567</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/prosper-daily-money-tracking/id602710567?mt=8&uo=4">https://itunes.apple.com/us/app/prosper-daily-money-tracking/id602710567?mt=8&uo=4</a>
**App Version:** 4.6.3
**Seller:** BillGuard Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/billguard-inc./id602710650?uo=4>© BillGuard, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/ea/63/99/ea639923-5104-f67b-0aa7-54b018b303e6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13722070/4ef4e6cc-e839-11e5-9792-199943de5af9.png)

**Comment by l8er4now** [comment]
Need an update.

**App Name:** Prosper Daily - Money Tracking, Free Credit Score & ID Protection
**Bundle ID:** com.BillGuard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=602710567">602710567</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/prosper-daily-money-tracking/id602710567?mt=8&uo=4">https://itunes.apple.com/us/app/prosper-daily-money-tracking/id602710567?mt=8&uo=4</a>
**App Version:** 4.6.3
**Seller:** BillGuard Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/billguard-inc./id602710650?uo=4>© BillGuard, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/ea/63/99/ea639923-5104-f67b-0aa7-54b018b303e6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13722070/4ef4e6cc-e839-11e5-9792-199943de5af9.png)
https://cloud.githubusercontent.com/assets/2068130/13722070/4ef4e6cc-e839-11e5-9792-199943de5af9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13722073/5ca8e41c-e839-11e5-9546-b6e0ad69f400.png
