### ISSUE TITLE
Reeder 3

### ISSUE THREAD

**Issue by King-Flo** [glasklart/hd#3663]
**App Name:** Reeder 3
**Bundle ID:** com.reederapp.rkit2.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=697846300">697846300</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reeder-3/id697846300?mt=8&uo=4">https://itunes.apple.com/us/app/reeder-3/id697846300?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Silvio Rizzi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/silvio-rizzi/id325502382?uo=4>© Silvio Rizzi</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/9f/f8/c6/9ff8c6f3-76cd-b0c3-2791-e6713b825a94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18808976/00150dc0-8271-11e6-90ff-2496e147df6e.png)

**Comment by Checkit23** [comment]
Now that Reeder 3 is the current version, shouldn't we remove the 2 from the icon? Or replace it with a 3, whatever you guys think is best.

**Comment by dreamnet** [comment]
@Checkit23 Yes, the 2 needs to be removed.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18808976/00150dc0-8271-11e6-90ff-2496e147df6e.png)
https://cloud.githubusercontent.com/assets/2068130/18808976/00150dc0-8271-11e6-90ff-2496e147df6e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18808980/0e3ea4c4-8271-11e6-944a-e8a901c0583d.png
