### ISSUE TITLE
MyWi

### ISSUE THREAD

**Issue by sinfool** [glasklart/hd#3679]
**App Name:** MyWi
 **Bundle ID:** com.intelliborn.MyWi
 **Version:** ???
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/2068130/18738179/a154bd2c-8099-11e6-9f71-868d4f9f264e.png" width="180" height="180" />
 **Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18738186/afd40858-8099-11e6-84fb-149bbb534559.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18738186/afd40858-8099-11e6-84fb-149bbb534559.png)
https://cloud.githubusercontent.com/assets/2068130/18738186/afd40858-8099-11e6-84fb-149bbb534559.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18738193/bd844f9e-8099-11e6-93d2-8f1c3adfa44d.png

**Comment by Trubbel** [comment]
@dreamnet I can find these bundle IDs,

**MyWi 7.0 (iOS 7 Library)**
`com.intelliborn.mywi7`

**MyWi 8.0 (iOS 8 Library)**
`com.intelliborn.mywi8`

**MyWi 9.0 (iOS 9 Library)**
`com.intelliborn.mywi9`

**MyWi9**
`com.mywi4`

Everyone of these have the same artwork as well, should we open separate issues for them all?

**Comment by dreamnet** [comment]
@Trubbel I also [found these bundle ID's](http://modmyi.com/cydia/search.php?search=mywi&where=Name&repo=all). And yes, I think we should open a seperate issue for every MyWi app.
