### ISSUE TITLE
Forms by LegalShield

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3682]
**App Name:** Forms by LegalShield
**Bundle ID:** com.shakelaw.shake
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=601561998">601561998</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/forms-by-legalshield/id601561998?uo=4">https://apps.apple.com/us/app/forms-by-legalshield/id601561998?uo=4</a>
**App Version:** 4.0.1
**Seller:** Pre-Paid Legal Services, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/pre-paid-legal-services-inc/id429918007?uo=4">© Pre-Paid Legal Services, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/42/72/fa/4272fa43-8404-f910-6a1d-d1bab3aa34ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60442909-5de6cb80-9c1a-11e9-83e4-3ea138f8cf36.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60442909-5de6cb80-9c1a-11e9-83e4-3ea138f8cf36.png)
https://user-images.githubusercontent.com/20930745/60442909-5de6cb80-9c1a-11e9-83e4-3ea138f8cf36.png

Source:
https://user-images.githubusercontent.com/20930745/60442912-5f17f880-9c1a-11e9-8cd2-b1387ec975ec.png
