### ISSUE TITLE
Instamail Photos and Videos

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3685]
**App Name:** Instamail Photos and Videos
**Bundle ID:** AppSimo.MediaAttach
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=553743855">553743855</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/instamail-photos-and-videos/id553743855?uo=4">https://apps.apple.com/us/app/instamail-photos-and-videos/id553743855?uo=4</a>
**App Version:** 3.2
**Seller:** Quanticapps
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/quanticapps/id378465660?uo=4">© Quanticapps</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/88/cb/6e/88cb6e35-f83e-99b5-b910-3e4f008f69ce/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62399863-95c89200-b57d-11e9-957c-83a5d5a5afec.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62399863-95c89200-b57d-11e9-957c-83a5d5a5afec.png)
https://user-images.githubusercontent.com/2068130/62399863-95c89200-b57d-11e9-957c-83a5d5a5afec.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62399881-a547db00-b57d-11e9-8de6-fadc8a1071ff.png
