### ISSUE TITLE
IBM MaaS360

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3688]
**App Name:** IBM MaaS360
**Bundle ID:** com.fiberlink.maas360forios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=459732007">459732007</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ibm-maas360/id459732007?uo=4">https://apps.apple.com/us/app/ibm-maas360/id459732007?uo=4</a>
**App Version:** 3.91.5
**Seller:** Fiberlink Communications Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fiberlink-communications-corporation/id435877591?uo=4">© Fiberlink Communications Corporation</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/a6/17/6b/a6176b4a-e1b8-6122-16aa-bcb1be1e0533/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62398646-96f7c000-b579-11e9-82b1-516b9bfbf459.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62398646-96f7c000-b579-11e9-82b1-516b9bfbf459.png)
https://user-images.githubusercontent.com/2068130/62398646-96f7c000-b579-11e9-82b1-516b9bfbf459.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62398662-a6770900-b579-11e9-8d9a-b07e20d8d451.png
