### ISSUE TITLE
MyFitnessPal

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3690]
**App Name:** MyFitnessPal
**Bundle ID:** com.myfitnesspal.mfp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=341232718">341232718</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myfitnesspal/id341232718?uo=4">https://apps.apple.com/us/app/myfitnesspal/id341232718?uo=4</a>
**App Version:** 19.6.10
**Seller:** MyFitnessPal LLc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/myfitnesspal-com/id341232721?uo=4">© MyFitnessPal.com</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/87/48/70/87487061-e51c-1d2a-c556-e8a9eb92ec4d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61991578-561c1a80-b052-11e9-8e9f-f3cb92109bc4.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61991578-561c1a80-b052-11e9-8e9f-f3cb92109bc4.png)
https://user-images.githubusercontent.com/2068130/61991578-561c1a80-b052-11e9-8e9f-f3cb92109bc4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/61991586-659b6380-b052-11e9-9394-ad34477d5da3.png
