### ISSUE TITLE
Shazam - Discover music, artists, videos & lyrics

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3697]
**App Name:** Shazam - Discover music, artists, videos & lyrics
**Bundle ID:** com.shazam.Shazam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284993459">284993459</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shazam-discover-music-artists/id284993459?mt=8&uo=4">https://itunes.apple.com/us/app/shazam-discover-music-artists/id284993459?mt=8&uo=4</a>
**App Version:** 9.0.1
**Seller:** Shazam Entertainment Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shazam-entertainment-ltd./id284993479?uo=4>© Shazam Entertainment Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/87/db/3c/87db3cdb-3f86-8fab-f2cb-6be88d0798d2/mzl.mehdqqus.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10543891/0f9e34fa-73e6-11e5-9c1f-00011f16d98a.png)

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10543891/0f9e34fa-73e6-11e5-9c1f-00011f16d98a.png)
https://cloud.githubusercontent.com/assets/3090247/10543891/0f9e34fa-73e6-11e5-9c1f-00011f16d98a.png
--- ---

**Comment by Trubbel** [comment]
@ivanov007 :+1: :smile:
