### ISSUE TITLE
DS file

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#37]
**App Name:** DS file
**Bundle ID:** com.synology.DSfile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416751772">416751772</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ds-file/id416751772?mt=8&uo=4">https://itunes.apple.com/us/app/ds-file/id416751772?mt=8&uo=4</a>
**App Version:** 5.9.2
**Seller:** Synology Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/synology-inc./id321493109?uo=4>© Synology Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/c1/c2/78/c1c27843-4b16-276c-9015-4ee4ba13d930/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416437/70558d28-7815-11e6-9551-1c833afa545e.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416437/70558d28-7815-11e6-9551-1c833afa545e.png)
https://cloud.githubusercontent.com/assets/2068130/18416437/70558d28-7815-11e6-9551-1c833afa545e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416444/8003a746-7815-11e6-9411-d806ea4e8137.png
