### ISSUE TITLE
Blood & Glory 2: Legend

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#371]
**App Name:** Blood & Glory 2: Legend
**Bundle ID:** com.glu.gladiator2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=496748308">496748308</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blood-glory-2-legend/id496748308?mt=8&uo=4">https://itunes.apple.com/us/app/blood-glory-2-legend/id496748308?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** Glu Games Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/glu-games-inc/id284419051?uo=4">© Glu Games Inc</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/84/98/9c/84989cfe-5ebc-a990-0531-2b1b5542c771/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40590431-07d274ca-61ff-11e8-8597-ab26365720e2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40590431-07d274ca-61ff-11e8-8597-ab26365720e2.png)
https://user-images.githubusercontent.com/2068130/40590431-07d274ca-61ff-11e8-8597-ab26365720e2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/40590436-171b25ee-61ff-11e8-8420-08e741287a0d.png
