### ISSUE TITLE
Fandango Movies – Times & Tickets

### ISSUE THREAD

**Issue by lolololololloll** [glasklart/hd#3712]
**App Name:** Fandango Movies - Times + Tickets
**Bundle ID:** com.fandango.fandango
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307906541">307906541</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fandango-movies-times-+-tickets/id307906541?mt=8&uo=4">https://itunes.apple.com/us/app/fandango-movies-times-+-tickets/id307906541?mt=8&uo=4</a>
**App Version:** 7.7
**Seller:** Fandango
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fandango/id307906544?uo=4>© Fandango</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/05/ba/17/05ba1753-6f68-764c-581b-d458ab823aa4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18400056/7dd6785a-76d4-11e6-8a57-fde3d3384c09.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Fandango Movies - Times + Tickets
**Bundle ID:** com.fandango.fandango
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307906541">307906541</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fandango-movies-times-+-tickets/id307906541?mt=8&uo=4">https://itunes.apple.com/us/app/fandango-movies-times-+-tickets/id307906541?mt=8&uo=4</a>
**App Version:** 7.7
**Seller:** Fandango
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fandango/id307906544?uo=4>© Fandango</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/05/ba/17/05ba1753-6f68-764c-581b-d458ab823aa4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18394768/8f49e54a-7689-11e6-806c-c9af5c06eeff.png)

https://cloud.githubusercontent.com/assets/3704186/18394768/8f49e54a-7689-11e6-806c-c9af5c06eeff.png

https://cloud.githubusercontent.com/assets/3704186/18394771/958561be-7689-11e6-895b-c54e403e9a46.png
