### ISSUE TITLE
TVSMILES

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#3715]
**App Name:** TVSMILES – Quiz, Cash, Prämien, Gewinnspiele & Fun
**Bundle ID:** de.tvsmiles.tvsmiles
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=637481386">637481386</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/tvsmiles-quiz-cash-pramien/id637481386?mt=8&uo=4">https://itunes.apple.com/de/app/tvsmiles-quiz-cash-pramien/id637481386?mt=8&uo=4</a>
**App Version:** 1.5.4
**Seller:** TVSMILES GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/tvsmiles-gmbh/id637481389?uo=4>© TVSMILES GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/35/8a/8a/358a8a96-b3fd-333e-2ad8-b586a71451c0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17036685/9f733142-4f8d-11e6-9eef-57ca65c90594.png)

**Comment by Anuskuss** [comment]
@dreamnet Could you create an icon with only the "smiley"?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16966524/3a9d4bce-4e05-11e6-8b63-5133e6efc35f.png)
https://cloud.githubusercontent.com/assets/2068130/16966524/3a9d4bce-4e05-11e6-8b63-5133e6efc35f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16966536/48539264-4e05-11e6-91fe-420650f9c912.png

**Comment by Anuskuss** [comment]
@dreamnet Could you make the smiley a little bit smaller (without changing the circle)?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17036685/9f733142-4f8d-11e6-9eef-57ca65c90594.png)
https://cloud.githubusercontent.com/assets/2068130/17036685/9f733142-4f8d-11e6-9eef-57ca65c90594.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17036696/adce8674-4f8d-11e6-9426-71b86666ba62.png
