### ISSUE TITLE
Coowl

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3730]
**App Name:** Coowl
**Bundle ID:** com.nostalgika.Coowl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=657397623">657397623</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/coowl/id657397623?uo=4">https://apps.apple.com/us/app/coowl/id657397623?uo=4</a>
**App Version:** 2.2
**Seller:** Nostalgika LTDA - ME
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nostalgika-ltda-me/id512781212?uo=4">© Nostalgika LTDA - ME</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/8b/ed/c9/8bedc9ac-b7b3-b3a4-9841-7c3cdab63151/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60380553-ec572380-9a47-11e9-9dd1-471301c2e0e4.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60380553-ec572380-9a47-11e9-9dd1-471301c2e0e4.png)
https://user-images.githubusercontent.com/2068130/60380553-ec572380-9a47-11e9-9dd1-471301c2e0e4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60380556-fb3dd600-9a47-11e9-89ea-e7a68e545675.png
