### ISSUE TITLE
Deliveries: a package tracker

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#3734]
**App Name:** Deliveries: a package tracker
**Bundle ID:** com.junecloud.Deliveries
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=290986013">290986013</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deliveries-a-package-tracker/id290986013?mt=8&uo=4">https://itunes.apple.com/us/app/deliveries-a-package-tracker/id290986013?mt=8&uo=4</a>
**App Version:** 6.2
**Seller:** Junecloud LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/junecloud-llc/id290986016?uo=4>© Junecloud LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple2/v4/5e/1d/e2/5e1de239-cca9-90e4-9bd5-4ba1985aa25d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12550867/b7690154-c366-11e5-8ce3-2f2bf2215391.png)

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12550867/b7690154-c366-11e5-8ce3-2f2bf2215391.png)
https://cloud.githubusercontent.com/assets/10730122/12550867/b7690154-c366-11e5-8ce3-2f2bf2215391.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12550866/b764885e-c366-11e5-8477-70abea908cad.png
