### ISSUE TITLE
Domain Real Estate & Property

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#3747]
**App Name:** Domain Real Estate & Property
**Bundle ID:** au.com.fairfaxdigital.Domain
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=319908646">319908646</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/domain-real-estate-property/id319908646?uo=4">https://apps.apple.com/us/app/domain-real-estate-property/id319908646?uo=4</a>
**App Version:** 9.4.7
**Seller:** Fairfax Media Management Pty Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fairfax-digital-australia-new-zealand-pty-limited/id319908649?uo=4">© Fairfax Digital Australia & New Zealand Pty Limited</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/b5/c1/92/b5c19226-7bdc-51e1-3396-8cbcaf815e91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382565-0fdc9700-9a65-11e9-9681-e47c6b958fd7.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382565-0fdc9700-9a65-11e9-9681-e47c6b958fd7.png)
https://user-images.githubusercontent.com/20930745/60382565-0fdc9700-9a65-11e9-9681-e47c6b958fd7.png

Source:
https://user-images.githubusercontent.com/20930745/60382566-110dc400-9a65-11e9-8eac-aaaa17c40d03.png
