### ISSUE TITLE
Ease into 5K: run walk interval training program

### ISSUE THREAD

**Issue by pcasey83** [glasklart/hd#376]
**App Name:** Ease into 5K: run walk interval training program
**Bundle ID:** com.auctioncontact.C25K
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=301233668">301233668</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ease-into-5k-run-walk-interval-training-program/id301233668?mt=8&uo=4">https://itunes.apple.com/us/app/ease-into-5k-run-walk-interval-training-program/id301233668?mt=8&uo=4</a>
**App Version:** 3.5.8
**Seller:** Bluefin Software, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bluefin-software-llc/id301233671?uo=4">© Bluefin Software, LLC</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/3a/02/a8/3a02a8c3-3421-c72f-8007-57da3aa57f06/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23326116/06f60f92-fafb-11e6-9b12-c159c08e7305.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23326116/06f60f92-fafb-11e6-9b12-c159c08e7305.png)
https://cloud.githubusercontent.com/assets/2068130/23326116/06f60f92-fafb-11e6-9b12-c159c08e7305.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23326121/1868312e-fafb-11e6-986e-1aedfd4c1200.png
