### ISSUE TITLE
TuneIn Radio: NFL & Podcasts

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3771]
**App Name:** TuneIn Radio: NFL & Podcasts
**Bundle ID:** com.tunein.TuneInRadio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418987775">418987775</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tunein-radio-nfl-podcasts/id418987775?mt=8&uo=4">https://itunes.apple.com/us/app/tunein-radio-nfl-podcasts/id418987775?mt=8&uo=4</a>
**App Version:** 13.0.2
**Seller:** TuneIn
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tunein/id319295335?uo=4">© TuneIn</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/10/c4/69/10c4699e-b239-ada2-1b96-1dc24ab6e0b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34392093-72889ae6-eb4a-11e7-9c85-17e26441d5ae.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17309652/2c6fdbbc-5840-11e6-8975-3247e9ac4328.png)
https://cloud.githubusercontent.com/assets/2068130/17309652/2c6fdbbc-5840-11e6-8975-3247e9ac4328.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17309668/3c73a520-5840-11e6-95bd-b5a2694131cf.png

**Comment by l8er4now** [comment]
Need an update (Pro version as well)

**App Name:** TuneIn Radio: NFL & Podcasts
**Bundle ID:** com.tunein.TuneInRadio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418987775">418987775</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tunein-radio-nfl-podcasts/id418987775?mt=8&uo=4">https://itunes.apple.com/us/app/tunein-radio-nfl-podcasts/id418987775?mt=8&uo=4</a>
**App Version:** 13.0.2
**Seller:** TuneIn
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tunein/id319295335?uo=4">© TuneIn</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/10/c4/69/10c4699e-b239-ada2-1b96-1dc24ab6e0b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34392093-72889ae6-eb4a-11e7-9c85-17e26441d5ae.png)
https://user-images.githubusercontent.com/2068130/34392093-72889ae6-eb4a-11e7-9c85-17e26441d5ae.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34392110-8135e666-eb4a-11e7-8781-6d76fb40b5e4.png
