### ISSUE TITLE
Angry Birds Go!

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#3778]
**App Name:** Angry Birds Go!
**Bundle ID:** com.rovio.angrybirdsgo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=642821482">642821482</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds-go!/id642821482?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds-go!/id642821482?mt=8&uo=4</a>
**App Version:** 1.13.9
**Seller:** Rovio Entertainment Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rovio-entertainment-ltd/id298910979?uo=4>© Rovio Entertainment Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/c1/88/f0/c188f052-5d89-1519-65bd-fe988628ed21/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Anuskuss** [comment]
Needs update.

**Comment by ivanov007** [comment]
mmhh I don't know, they made the icon change to match and promote the new movie so I don't know if this one worth to be changed, personally I don't like the new icon

**Comment by dreamnet** [comment]
Yeah, I also think it's not worth the change. We leave it as it is.

**Comment by Anuskuss** [comment]
This icon hasn't changed since 4th of april so I think we should reopen.

**Comment by dreamnet** [comment]
I think the existing icon is already fine.
