### ISSUE TITLE
Amazon Kindle

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#3782]
**App Name:** Amazon Kindle
**Bundle ID:** com.amazon.Lassen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=302584613">302584613</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amazon-kindle/id302584613?mt=8&uo=4">https://itunes.apple.com/us/app/amazon-kindle/id302584613?mt=8&uo=4</a>
**App Version:** 6.5
**Seller:** AMZN Mobile LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amzn-mobile-llc/id297606954?uo=4">© AMZN Mobile LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/1c/fb/8a/1cfb8af8-76a6-e3f1-f33b-e51bdc14b139/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38456301-84e961d8-3a83-11e8-8744-5fae6ec93ea7.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38456301-84e961d8-3a83-11e8-8744-5fae6ec93ea7.png)
https://user-images.githubusercontent.com/20930745/38456301-84e961d8-3a83-11e8-8744-5fae6ec93ea7.png

Source:
https://user-images.githubusercontent.com/20930745/38456307-962146dc-3a83-11e8-8dc4-0411e4a80292.png
