### ISSUE TITLE
MediaFire - Cloud Storage and Photo Backup

### ISSUE THREAD

**Issue by rimistri** [glasklart/hd#3784]
**App Name:** MediaFire - Cloud Storage and Photo Backup
**Bundle ID:** com.mediafire.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555646196">555646196</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mediafire-cloud-storage-photo/id555646196?mt=8&uo=4">https://itunes.apple.com/us/app/mediafire-cloud-storage-photo/id555646196?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** MediaFire, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mediafire/id555646199?uo=4>© MediaFire</a>
**Supported Devices:** iPhone4S, iPadFourthGen, iPadMini4G, iPad2Wifi, iPadThirdGen4G, iPhone5s, iPadThirdGen, iPodTouchFifthGen, iPhone4, iPhone6Plus, iPad23G, iPhone5c, iPhone5, iPhone6, iPadMini, iPadFourthGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/6d/f6/c7/6df6c75d-0a24-7a20-0678-80a95a6821e4/mzl.rimyjsnt.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8347713/eacc8ecc-1b09-11e5-9152-e8cbf03f2d51.png)

**Comment by Trubbel** [comment]
Icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8347713/eacc8ecc-1b09-11e5-9152-e8cbf03f2d51.png)
https://cloud.githubusercontent.com/assets/10730122/8347713/eacc8ecc-1b09-11e5-9152-e8cbf03f2d51.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8347711/e4d2793c-1b09-11e5-953c-b1e5ad16b91d.png
