### ISSUE TITLE
HP Reveal

### ISSUE THREAD

**Issue by Starsam80** [glasklart/hd#3785]
**App Name:** HP Reveal
**Bundle ID:** com.aurasma.aurasmalite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432526396">432526396</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hp-reveal/id432526396?uo=4">https://apps.apple.com/us/app/hp-reveal/id432526396?uo=4</a>
**App Version:** 6.0.1
**Seller:** Aurasma
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/aurasma/id432295054?uo=4">© Aurasma</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/34/a5/d0/34a5d014-d3ea-1d3a-2031-e0035a7d0930/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60773213-9b5bc500-a102-11e9-9b3d-2e0db7f766f6.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60773213-9b5bc500-a102-11e9-9b3d-2e0db7f766f6.png)
https://user-images.githubusercontent.com/2068130/60773213-9b5bc500-a102-11e9-9b3d-2e0db7f766f6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60773217-aa427780-a102-11e9-8033-5b2d80ae3af1.png
