### ISSUE TITLE
Battery Saver - Improve the Battery Life

### ISSUE THREAD

**Issue by Starsam80** [glasklart/hd#3787]
**App Name:** Battery Saver - Improve the Battery Life
**Bundle ID:** com.ksmobile.batterydoctor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=615987910">615987910</a>
**iPhone Icon Name:** icon@2x.png
**Icon Names:** icon.png | icon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/battery-saver-improve-battery/id615987910?mt=8&uo=4
**App Version:** 1.5
**Seller:** KS Mobile, Inc.
**Supported Devices:** iPhone5c, iPhone4, iPodTouchourthGen, iPhone-3GS, iPodTouchThirdGen, iPodTouchFifthGen, iPadWifi, iPhone5, iPad3G, iPadThirdGen, iPadMini4G, iPadThirdGen4G, iPad2Wifi, iPad23G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPhone4S, iPhone5s
**Original Artwork:**
<img src="http://a392.phobos.apple.com/us/r30/Purple4/v4/f2/0e/d4/f20ed441-c900-a3f5-c185-2a7d5a10a183/mzl.zgxoksar.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18721178/9131622a-802f-11e6-83b2-3290b201ab12.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by 2Qt2beStr8** [comment]
can't do it better :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18721178/9131622a-802f-11e6-83b2-3290b201ab12.png)
https://cloud.githubusercontent.com/assets/20930745/18721178/9131622a-802f-11e6-83b2-3290b201ab12.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18721214/bb29d224-802f-11e6-9491-511a58e6187a.png

**Comment by ivanov007** [comment]
looks good to me :+1:
