### ISSUE TITLE
Glasklart folders

### ISSUE THREAD

**Issue by rubyrod7** [glasklart/hd#379]
hey guys, i was wondering if any of you had a copy of the theme that makes your folders transparent. Normally, the folders on your springboard have a black background, this theme used to turn that background transparent so it fit with the rest o the theme. It was posted on macthemes about a year ago but the link that was provided seems to have expired since it sent you to a file sharing site and you guys know how those things work (not downloaded in 30days the file is removed). Anyways, if anyone knows where i could find it could you please let me know? Thanks

**Comment by Teekzilla** [comment]
Quick question, is there currently a folder icon available?
The links to the 2 in this thread seem to be broken.

I'm using Anemone for theming, and it supports folder icons on iOS 8.4 so I would like to have those.
I checked through the repository as @jfelchner said it was there, but came out empty handed.

**Comment by MagnaMike** [comment]
Wow this is old... Yeah let me dig them up for you. They'll probably have to be modified a bit because iOS 6 to iOS 7 changed a lot of things.

**Comment by Teekzilla** [comment]
Yeah, I was looking for them. I'll try and change it up if its required! And thank you!

**Comment by MagnaMike** [comment]
![folder icon](https://cloud.githubusercontent.com/assets/2236254/8861357/01995b3a-3158-11e5-8ef6-5eae13183448.png)

Please note the image dimensions (118x124). I'm not sure how Anenome works (and I haven't actually used an iDevice since iOS 6) but you'll likely need a 120x120 image so you'll have to crop the edges off. Watch out for the positioning of the icon or it will likely look misaligned on your screen. Is this the only image you need? Before we needed two images for themeing but that was on iOS 6 before folders were redesigned. I was only able to find this one image but I might be able to find the other if you need it.

**Comment by Teekzilla** [comment]
Thank you, and yup just need this one! Please do let me know if you find the other one as well 😊

**Comment by MagnaMike** [comment]
![folder drop](https://cloud.githubusercontent.com/assets/2236254/8861916/2044d070-315b-11e5-826d-d24795d45492.png)
 This was used for when the folder expanded when about to drop in another icon.

**Comment by MagnaMike** [comment]
It might almost just look nicer if you make a new folder icon though. Take a blank glasklart icon and remove the middle bit. Just a thought.

**Comment by Teekzilla** [comment]
Ohh I was referring to the dark one and the transparent, not the expanded form, and I'll try this real quick just to see what it looks like, if not I'll start a new one

**Comment by MagnaMike** [comment]
Oh okay. I think I have that one too

**Comment by MagnaMike** [comment]
Doesn't look like I have it. But I never liked the look of it anyway, haha :smile:

**Comment by Teekzilla** [comment]
Haha all good, let me try the transparent one real quick

**Comment by Teekzilla** [comment]
Preview:
![](http://i.imgur.com/2Od6LYL.jpg)
http://i.imgur.com/eFoedzu.jpg

Icon:
ANEMFolderIconBG@2x
Goes in SpringBoard Bundle...
![](http://i.imgur.com/E8TQKi7.jpg)
http://i.imgur.com/u510osL.jpg

**Comment by Teekzilla** [comment]
Might just redo it, seems a bit pixelated on the inside corners... Or could just be me...

**Comment by MagnaMike** [comment]
Cool! Yeah it wasn't my best work, but I didn't have a good source to go off of.

**Comment by MagnaMike** [comment]
@dreamnet Is this something that can be added to the main theme?

**Comment by dreamnet** [comment]
@MagnaMike It is only possible to change the shape of an open folder, but it is not possible to change the apperance of a closed folder.

**Comment by dreamnet** [comment]
There is nothing that can be done at the moment :cry: - closing.
