### ISSUE TITLE
Best Buy

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3795]
**App Name:** Best Buy
**Bundle ID:** com.bestbuy.buyphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=314855255">314855255</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/best-buy/id314855255?mt=8&uo=4">https://itunes.apple.com/us/app/best-buy/id314855255?mt=8&uo=4</a>
**App Version:** 11.1.0
**Seller:** Best Buy Co., Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/best-buy-co-inc/id314855258?uo=4">© Best Buy Co., Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/5c/fc/80/5cfc80c4-db96-aa01-da25-5d660d70e0e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41167590-a8e2663e-6b43-11e8-8ac9-a7a8659b1222.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Best Buy
**Bundle ID:** com.bestbuy.buyphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=314855255">314855255</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/best-buy/id314855255?mt=8&uo=4">https://itunes.apple.com/us/app/best-buy/id314855255?mt=8&uo=4</a>
**App Version:** 11.1.0
**Seller:** Best Buy Co., Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/best-buy-co-inc/id314855258?uo=4">© Best Buy Co., Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/5c/fc/80/5cfc80c4-db96-aa01-da25-5d660d70e0e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41167590-a8e2663e-6b43-11e8-8ac9-a7a8659b1222.png)
https://user-images.githubusercontent.com/2068130/41167590-a8e2663e-6b43-11e8-8ac9-a7a8659b1222.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41167606-b82a18c6-6b43-11e8-8cb2-1b7f667b3dd0.png
