### ISSUE TITLE
App in the Air

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3797]
**App Name:** App in the Air
**Bundle ID:** com.aita.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527299553">527299553</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/app-in-the-air/id527299553?uo=4">https://apps.apple.com/us/app/app-in-the-air/id527299553?uo=4</a>
**App Version:** 7.5.4
**Seller:** AITA LIMITED
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/aita-limited/id527299556?uo=4">© AITA LIMITED</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/73/b1/5a/73b15afd-b0dc-569c-7c68-33decc9e30a6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59979653-b4388680-95ea-11e9-8837-bc46d91476d4.png)

**Comment by l8er4now** [comment]
Needs an update, another one that has gone more flat.

**App Name:** App in the Air - Personal travel assistant
**Bundle ID:** com.aita.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527299553">527299553</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/app-in-air-personal-travel/id527299553?mt=8&uo=4">https://itunes.apple.com/us/app/app-in-air-personal-travel/id527299553?mt=8&uo=4</a>
**App Version:** 5.7.0
**Seller:** AITA LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aita-limited/id527299556?uo=4>© AITA LIMITED</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple18/v4/d3/25/30/d3253038-2340-0e6a-c08f-58cca9bc15b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18030850/2674abc4-6cc8-11e6-8a14-482b13f5ab9f.png)
https://cloud.githubusercontent.com/assets/10730122/18030850/2674abc4-6cc8-11e6-8a14-482b13f5ab9f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18030849/267465c4-6cc8-11e6-8616-123b0656253d.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59979653-b4388680-95ea-11e9-8837-bc46d91476d4.png)
https://user-images.githubusercontent.com/20930745/59979653-b4388680-95ea-11e9-8837-bc46d91476d4.png

Source:
https://user-images.githubusercontent.com/20930745/59979654-b569b380-95ea-11e9-8f97-625cddc4b604.png
