### ISSUE TITLE
Craftsy

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3798]
**App Name:** Craftsy
**Bundle ID:** com.sympoz.craftsy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540872054">540872054</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/craftsy/id540872054?uo=4">https://apps.apple.com/us/app/craftsy/id540872054?uo=4</a>
**App Version:** 4.3.5
**Seller:** Sympoz Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sympoz-inc/id540872057?uo=4">© Sympoz Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple125/v4/4d/f3/2f/4df32f84-520b-7b28-0ce1-e05e0f9168c8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60369599-6cec3480-99f4-11e9-9bfe-9e5912821432.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60369599-6cec3480-99f4-11e9-9bfe-9e5912821432.png)
https://user-images.githubusercontent.com/2068130/60369599-6cec3480-99f4-11e9-9bfe-9e5912821432.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60369612-7bd2e700-99f4-11e9-8a10-8544dd9dd2da.png
