### ISSUE TITLE
DS finder

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#38]
**App Name:** DS finder
**Bundle ID:** com.synology.DSfinder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=429865523">429865523</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ds-finder/id429865523?mt=8&uo=4">https://itunes.apple.com/us/app/ds-finder/id429865523?mt=8&uo=4</a>
**App Version:** 2.11.0
**Seller:** Synology Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/synology-inc./id321493109?uo=4>© Synology Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple18/v4/d5/c2/0e/d5c20e35-2404-04dc-a2df-64438a96695e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416463/142b2cc8-7816-11e6-926f-4e2ce7a30cbe.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416463/142b2cc8-7816-11e6-926f-4e2ce7a30cbe.png)
https://cloud.githubusercontent.com/assets/2068130/18416463/142b2cc8-7816-11e6-926f-4e2ce7a30cbe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416464/246cd230-7816-11e6-8428-c4a4ff291bb1.png
