### ISSUE TITLE
Lep's World 3 - Free

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3803]
**App Name:** Lep's World 3 - Free
**Bundle ID:** at.ner.LepsWorld3Free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=724816878">724816878</a>
**iPhone Icon Name:** Icon@2x.png
**Icon Names:** Icon-80.png | Icon-120.png | Icon.png | Icon-72.png | Icon-Small.png | Icon-Small-50.png | Icon@2x.png
**iTunes URL:** https://itunes.apple.com/us/app/leps-world-3-free/id724816878?mt=8&uo=4
**App Version:** 1.1
**Seller:** nerByte GmbH
**Supported Devices:** iPadMini4G, iPadThirdGen4G, iPhone5, iPad2Wifi, iPhone5s, iPhone5c, iPadFourthGen4G, iPhone-3GS, iPodTouchFifthGen, iPad23G, iPhone4S, iPadFourthGen, iPodTouchourthGen, iPadWifi, iPodTouchThirdGen, iPhone4, iPadMini, iPad3G, iPadThirdGen
**Original Artwork:**
<img src="http://a1559.phobos.apple.com/us/r30/Purple4/v4/2b/05/e0/2b05e00b-cbdb-6a93-6df7-2ba9402e43fe/mzl.enupufzr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12217833/658c67f0-b70d-11e5-805d-3149064e88b3.png)

**Comment by dreamnet** [comment]
Small update to go with the other Lep's World apps...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12217833/658c67f0-b70d-11e5-805d-3149064e88b3.png)
https://cloud.githubusercontent.com/assets/2068130/12217833/658c67f0-b70d-11e5-805d-3149064e88b3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12217835/748534e4-b70d-11e5-8311-51ba1b3c4db6.png
Icon by @ivanov007.

**Comment by ivanov007** [comment]
@dreamnet but you remade it with source and all, I think the credit is all yours

**Comment by dreamnet** [comment]
@ivanov007 I had the source on my server, so I think it's from you. Anyway, too late... :wink: :stuck_out_tongue_winking_eye:

**Comment by ivanov007** [comment]
@dreamnet oooh, right I totally forgot about that
