### ISSUE TITLE
Tango Remote with Up Next Queue

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3806]
**App Name:** Tango Remote with Up Next Queue
**Bundle ID:** com.tangoremote.tangoremote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=345279970">345279970</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tango-remote-up-next-queue/id345279970?mt=8&uo=4">https://itunes.apple.com/us/app/tango-remote-up-next-queue/id345279970?mt=8&uo=4</a>
**App Version:** 9.1.1
**Seller:** Blue Atlas Technology, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/blue-atlas-technology-llc/id300695407?uo=4>© Blue Atlas Technology, LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/ff/da/7d/ffda7d03-456d-b413-9d0c-8ade1612eb0e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12006870/b28f8c4a-abae-11e5-998e-88a3461b20f5.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12006870/b28f8c4a-abae-11e5-998e-88a3461b20f5.png)
https://cloud.githubusercontent.com/assets/3090247/12006870/b28f8c4a-abae-11e5-998e-88a3461b20f5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/12006873/cb949794-abae-11e5-88bd-af5d92822d20.png
