### ISSUE TITLE
Google Play Music

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3825]
**App Name:** Google Play Music
**Bundle ID:** com.google.PlayMusic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=691797987">691797987</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-play-music/id691797987?mt=8&uo=4">https://itunes.apple.com/us/app/google-play-music/id691797987?mt=8&uo=4</a>
**App Version:** 3.9.109
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/60/19/c2/6019c22a-e584-bc77-711b-db8ef4d3c7e9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14962190/2cbfb31e-1063-11e6-94d6-ef88d3c14655.png)

**Comment by Trubbel** [comment]
The icon has been updated.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8248513/3a41fdce-1660-11e5-81cb-ca5ad467fb3a.png)
https://cloud.githubusercontent.com/assets/2068130/8248513/3a41fdce-1660-11e5-81cb-ca5ad467fb3a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8248518/48fe533a-1660-11e5-9035-ecb2aff51305.png

**Comment by l8er4now** [comment]
Need an update.

**App Name:** Google Play Music
**Bundle ID:** com.google.PlayMusic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=691797987">691797987</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-play-music/id691797987?mt=8&uo=4">https://itunes.apple.com/us/app/google-play-music/id691797987?mt=8&uo=4</a>
**App Version:** 3.9.109
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/60/19/c2/6019c22a-e584-bc77-711b-db8ef4d3c7e9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14962146/f0277a9a-1062-11e6-929f-9f8daf146fe9.png)
https://cloud.githubusercontent.com/assets/3090247/14962146/f0277a9a-1062-11e6-929f-9f8daf146fe9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14962147/f0290ed2-1062-11e6-83ce-fa7c8378598d.png

**Comment by dreamnet** [comment]
@ivanov007 I take the second one.
