### ISSUE TITLE
Weekly Ads, Coupons and Shopping Deals - Retale App for Local Sales and Discounts

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3827]
**App Name:** Weekly Ads, Coupons and Shopping Deals - Retale App for Local Sales and Discounts
**Bundle ID:** com.retale.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=665873523">665873523</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weekly-ads-coupons-shopping/id665873523?mt=8&uo=4">https://itunes.apple.com/us/app/weekly-ads-coupons-shopping/id665873523?mt=8&uo=4</a>
**App Version:** 3.17.0
**Seller:** BONIAL ENTERPRISES NORTH AMERICA INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bonial-enterprises-north-america/id665873526?uo=4>© Bonial Enterprises North America Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/d8/a4/47/d8a44789-99e7-0521-5f4d-9c48179eb1c2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18289499/a3b089dc-744d-11e6-9368-3758a0abd0bb.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Weekly Ads, Coupons and Shopping Deals - Retale App for Local Sales and Discounts
**Bundle ID:** com.retale.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=665873523">665873523</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weekly-ads-coupons-shopping/id665873523?mt=8&uo=4">https://itunes.apple.com/us/app/weekly-ads-coupons-shopping/id665873523?mt=8&uo=4</a>
**App Version:** 3.17.0
**Seller:** BONIAL ENTERPRISES NORTH AMERICA INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bonial-enterprises-north-america/id665873526?uo=4>© Bonial Enterprises North America Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/d8/a4/47/d8a44789-99e7-0521-5f4d-9c48179eb1c2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18289499/a3b089dc-744d-11e6-9368-3758a0abd0bb.png)

https://cloud.githubusercontent.com/assets/3704186/18289499/a3b089dc-744d-11e6-9368-3758a0abd0bb.png

https://cloud.githubusercontent.com/assets/3704186/18289507/abafe7ea-744d-11e6-935e-a395c17fec0e.png)
