### ISSUE TITLE
Black Friday 2018 Ads Shopping

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3837]
**App Name:** Black Friday 2018 Ads Shopping
**Bundle ID:** fm.blackfriday
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=397533889">397533889</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/black-friday-2018-ads-shopping/id397533889?uo=4">https://apps.apple.com/us/app/black-friday-2018-ads-shopping/id397533889?uo=4</a>
**App Version:** 3.1.18
**Seller:** Sazze Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sazze-inc/id397533892?uo=4">© Sazze, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/5c/24/f5/5c24f5f8-3265-160e-6be1-733a6ec820ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60122202-ff869c80-9784-11e9-9deb-01add18a7cf9.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60122202-ff869c80-9784-11e9-9deb-01add18a7cf9.png)
https://user-images.githubusercontent.com/20930745/60122202-ff869c80-9784-11e9-9deb-01add18a7cf9.png

Source:
https://user-images.githubusercontent.com/20930745/60122206-01e8f680-9785-11e9-9a22-9276cdc6618c.png
