### ISSUE TITLE
Battlefield™ Companion

### ISSUE THREAD

**Issue by DarkXess** [glasklart/hd#384]
**App Name:** Battlefield™ Companion
**Bundle ID:** com.ea.bf3bl.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=505311207">505311207</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/battlefield-companion/id505311207?mt=8&uo=4">https://itunes.apple.com/us/app/battlefield-companion/id505311207?mt=8&uo=4</a>
**App Version:** 3.0.4
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/62/5c/7d/625c7dd4-3609-b55f-12a0-1ed342c522ee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32387903-354469ca-c0c6-11e7-90a4-760cbb32a8db.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32387903-354469ca-c0c6-11e7-90a4-760cbb32a8db.png)
https://user-images.githubusercontent.com/2068130/32387903-354469ca-c0c6-11e7-90a4-760cbb32a8db.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32387926-44a7fa4e-c0c6-11e7-951d-e591a283c062.png
