### ISSUE TITLE
Dictionary & Translator

### ISSUE THREAD

**Issue by Slapey10** [glasklart/hd#3850]
**App Name:** Dictionary & Translator
**Bundle ID:** com.bravolol.bravoLang.chineseDictionary
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=475211454">475211454</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dictionary-translator/id475211454?uo=4">https://apps.apple.com/us/app/dictionary-translator/id475211454?uo=4</a>
**App Version:** 19.11
**Seller:** Bravolol Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bravolol-limited/id449112802?uo=4">© Bravolol Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/96/ae/c3/96aec3e8-654f-7a99-4a25-d63ca6fd1dba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382594-a90bad80-9a65-11e9-8112-260abb870a4b.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382594-a90bad80-9a65-11e9-8112-260abb870a4b.png)
https://user-images.githubusercontent.com/20930745/60382594-a90bad80-9a65-11e9-8112-260abb870a4b.png

Source:
https://user-images.githubusercontent.com/20930745/60382595-aad57100-9a65-11e9-9b4b-bb07ab1a448f.png
