### ISSUE TITLE
L1

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#3862]
**App Name:** L1
**Bundle ID:** nl.peperzaken.l1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=523101249">523101249</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/l1/id523101249?mt=8&uo=4">https://itunes.apple.com/us/app/l1/id523101249?mt=8&uo=4</a>
**App Version:** 5.1.7
**Seller:** Omroepbedrijf Limburg B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/l1-limburg/id523101252?uo=4>© L1 Limburg</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/7c/e4/37/7ce437fc-9e2f-fb7d-5867-f814b0a8cc57/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19400114/fc805176-9254-11e6-9127-c7830ef04190.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19400114/fc805176-9254-11e6-9127-c7830ef04190.png)
https://cloud.githubusercontent.com/assets/20930745/19400114/fc805176-9254-11e6-9127-c7830ef04190.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19400133/0a9af1b2-9255-11e6-8f3b-75f7a93329d5.png
