### ISSUE TITLE
FlitsLimburg

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#3864]
**App Name:** FlitsLimburg
**Bundle ID:** nl.dwain.lb-alert
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=622543887">622543887</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flitslimburg/id622543887?mt=8&uo=4">https://itunes.apple.com/us/app/flitslimburg/id622543887?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Dwain Scheeren
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dwain-scheeren/id622544190?uo=4">© Dwain Scheeren</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/a7/18/c9/a718c964-4330-a882-931f-b5a6e697d00e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33798875-f640d3d6-dd20-11e7-859b-3bef8a7eed08.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33798875-f640d3d6-dd20-11e7-859b-3bef8a7eed08.png)
https://user-images.githubusercontent.com/2068130/33798875-f640d3d6-dd20-11e7-859b-3bef8a7eed08.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33798882-0826512a-dd21-11e7-8f83-7d12cff7f90b.png
