### ISSUE TITLE
Finnik iKenteken

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#3866]
**App Name:** Finnik iKenteken
**Bundle ID:** nl.vwe.ikenteken
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=451526873">451526873</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/finnik-ikenteken/id451526873?mt=8&uo=4">https://itunes.apple.com/gb/app/finnik-ikenteken/id451526873?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** VWE Bureau voor Voertuigdocumentatie en -informatie B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/vwe/id451526876?uo=4>© VWE</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/32/59/fe/3259fe21-e394-2bb5-66d3-0a3fcf7830b0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/19407560/399f15be-92a6-11e6-80e4-c3f42aaef876.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19399745/52ed322e-9253-11e6-9ca5-a174a637daaa.png)
https://cloud.githubusercontent.com/assets/20930745/19399745/52ed322e-9253-11e6-9ca5-a174a637daaa.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19399766/60b9b396-9253-11e6-9fa7-7adec7fca2c8.png
