### ISSUE TITLE
Blur - Create Custom Wallpapers

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#3869]
**App Name:** Blur - Create Custom Wallpapers
**Bundle ID:** com.enormous.blur
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=637855838">637855838</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blur-create-custom-wallpapers/id637855838?mt=8&uo=4">https://itunes.apple.com/us/app/blur-create-custom-wallpapers/id637855838?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Enormo.us LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/enormous/id637855841?uo=4>© Enormous</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/c9/33/25/c93325b4-18ad-e85a-4870-3194bbbff576/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13027736/3f646078-d25b-11e5-8784-d19cef82c712.png)

**Comment by Trubbel** [comment]
Icon is the same - adding source and support for **@3x**,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13027736/3f646078-d25b-11e5-8784-d19cef82c712.png)
https://cloud.githubusercontent.com/assets/10730122/13027736/3f646078-d25b-11e5-8784-d19cef82c712.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13027735/3f6115b2-d25b-11e5-8daa-b82d9d22c30a.png
