### ISSUE TITLE
Bubble Shooter! Free

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#3870]
**App Name:** Bubble Shooter - Pop Bubbles
**Bundle ID:** com.ilyondynamics.bubbleShooterClassic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=604044220">604044220</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bubble-shooter-pop-bubbles/id604044220?mt=8&uo=4">https://itunes.apple.com/us/app/bubble-shooter-pop-bubbles/id604044220?mt=8&uo=4</a>
**App Version:** 2.0.4
**Seller:** Ilyon Dynamics Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ilyon-dynamics-ltd/id604044223?uo=4">© Ilyon Dynamics Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/26/18/8a/26188a37-43cd-a99c-33a1-599de02f9ee5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33793034-fa6a28e8-dcaf-11e7-8d32-aceb09719d9b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/33793034-fa6a28e8-dcaf-11e7-8d32-aceb09719d9b.png)
https://user-images.githubusercontent.com/2068130/33793034-fa6a28e8-dcaf-11e7-8d32-aceb09719d9b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/33793037-0c207c0e-dcb0-11e7-8852-87748bb36e46.png
