### ISSUE TITLE
Zuyd Info App

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#3874]
**App Name:** Zuyd Info App
**Bundle ID:** nl.zuyd.Zuyd-Info
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=708347511">708347511</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zuyd-info-app/id708347511?mt=8&uo=4">https://itunes.apple.com/us/app/zuyd-info-app/id708347511?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Stichting Hogeschool Zuyd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zuyd-hogeschool/id708347514?uo=4>© Zuyd Hogeschool</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/67/d2/3d/67d23d01-9827-50b3-8e90-e62f54e17c4f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19320703/ab9cdca0-90b2-11e6-90e3-a0d2652f36af.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19320703/ab9cdca0-90b2-11e6-90e3-a0d2652f36af.png)
https://cloud.githubusercontent.com/assets/20930745/19320703/ab9cdca0-90b2-11e6-90e3-a0d2652f36af.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19320719/badb6dbc-90b2-11e6-8ebd-32b9e5f08f54.png
