### ISSUE TITLE
・MEGA・

### ISSUE THREAD

**Issue by aidanharris** [glasklart/hd#3881]
**App Name:** ・MEGA・
**Bundle ID:** mega.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=706857885">706857885</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mega/id706857885?mt=8&uo=4">https://itunes.apple.com/us/app/mega/id706857885?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Mega Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mega-limited/id706857888?uo=4>© Mega Limited</a>
**Supported Devices:** iPad23G, iPadMini4G, iPhone6Plus, iPadThirdGen4G, iPodTouchFifthGen, iPhone4, iPad2Wifi, iPhone5c, iPhone4S, iPadThirdGen, iPadFourthGen, iPhone5s, iPhone5, iPadFourthGen4G, iPhone6, iPadMini
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/ea/94/6c/ea946c29-45ba-6059-1387-3b86072769e5/mzl.irshttwu.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8347744/78e718d0-1b0a-11e5-9f84-fce19947a456.png)

**Comment by Trubbel** [comment]
Icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8347744/78e718d0-1b0a-11e5-9f84-fce19947a456.png)
https://cloud.githubusercontent.com/assets/10730122/8347744/78e718d0-1b0a-11e5-9f84-fce19947a456.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8347743/74e88034-1b0a-11e5-8731-9f1400b70594.png
