### ISSUE TITLE
Flex 2 Beta

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#3888]
**App Name:** Flex 2 Beta
**Bundle ID:** com.johncoates.Flex
**Version:** 1.981
**iTunes ID:** none (Cydia app)
**Repo:** http://getdelta.co/
**Original Artwork:**
<img src="https://f.cloud.github.com/assets/3734562/2074208/41e49d28-8d74-11e3-9eaa-1b4dda921cdf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10681560/a16cd01e-792a-11e5-9372-5f546ac8baa9.png)

**Comment by Trubbel** [comment]
Could anyone possibly update this for @3x?

**Comment by dreamnet** [comment]
@Trubbel Bundle ID for [Flex 2](http://modmyi.com/cydia/package.php?id=68322) is actually `com.fuyuchi.flex2` - right?

**Comment by Trubbel** [comment]
@dreamnet Thanks for updating and the **CFBundleIdentifier** is `com.johncoates.Flex`

**Comment by dreamnet** [comment]
@Trubbel No problem - what repo?

**Comment by Trubbel** [comment]
@dreamnet 
Repo; http://getdelta.co/
Version; 1.981

**Comment by dreamnet** [comment]
@Trubbel Ah, thank you, so that's the (older, but free) Beta version of Flex 2 - I open a new issue for the official version on BigBoss repo.

**Comment by Trubbel** [comment]
@dreamnet Not that it really matters but you have had to purchase Flex 2 before you can use the beta. And yeah, I didn't really realize that I had the beta installed haha. Good job noticing! :smile:

**Comment by dreamnet** [comment]
@Trubbel No problem, I added for both versions icons to the master. :+1:
