### ISSUE TITLE
BatteryLife

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#3890]
**App Name:** BatteryLife
**Bundle ID:** com.rbtdigital.BatteryLife
**App Version:** 1.7.0
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/23271504/ee05fe38-f9f7-11e6-8126-592bbe596dfb.png" width="180" height="180" />
**Accepted Artwork:**
![com rbt batterylifeapp-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23271522/029126e8-f9f8-11e6-9b14-f05efe8726c1.png)

**Comment by boxermansr** [comment]
bundle ID for this seems to have changed to com.rbt.batteryLifeApp as of the latest update for BatteryLife (02/28/2015).

**Comment by dreamnet** [comment]
@boxermansr Thanks for telling!

**Comment by sern19** [comment]
Looks like bundle ID changed again. Now its com.rbtdigital.BatteryLife (v 1.7.0)

**Comment by dreamnet** [comment]
![com rbt batterylifeapp-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23271522/029126e8-f9f8-11e6-9b14-f05efe8726c1.png)
https://cloud.githubusercontent.com/assets/2068130/23271522/029126e8-f9f8-11e6-9b14-f05efe8726c1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23271541/164bbd9c-f9f8-11e6-96f0-78afac50265d.png
