### ISSUE TITLE
CamFind

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#3893]
**App Name:** CamFind
**Bundle ID:** com.msearcher.CamFind
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=595857716">595857716</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camfind/id595857716?mt=8&uo=4">https://itunes.apple.com/us/app/camfind/id595857716?mt=8&uo=4</a>
**App Version:** 5.0.3
**Seller:** Cloudsight, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cloudsight-inc/id578866469?uo=4">© Cloudsight, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/be/a9/42/bea942ec-97f8-78d6-da60-05735afc9b49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45231335-f72fa480-b2cb-11e8-95ce-43e8dfb27c8c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45231335-f72fa480-b2cb-11e8-95ce-43e8dfb27c8c.png)
https://user-images.githubusercontent.com/2068130/45231335-f72fa480-b2cb-11e8-95ce-43e8dfb27c8c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45231354-0878b100-b2cc-11e8-8cda-bf9f3516ae36.png
