### ISSUE TITLE
Imgur: Memes, GIFs, and More

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#3904]
**App Name:** Imgur: Memes, GIFs, and More
**Bundle ID:** imgurmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=639881495">639881495</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/imgur-memes-gifs-and-more/id639881495?mt=8&uo=4">https://itunes.apple.com/us/app/imgur-memes-gifs-and-more/id639881495?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** Imgur, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/imgur-inc/id639881498?uo=4">© Imgur, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/0c/04/1e/0c041ef4-0e28-e33d-09d5-64f054f50b74/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34393257-7f81e070-eb51-11e7-8f1f-b74272bbdebd.png)

**Comment by zmathiasz** [comment]
Icon has been updated. :)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9020777/05e3233c-3820-11e5-9894-40c45d2aedc7.png)
https://cloud.githubusercontent.com/assets/2068130/9020777/05e3233c-3820-11e5-9894-40c45d2aedc7.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9020778/14a5d360-3820-11e5-9bc3-72b2d51b5cba.png

**Comment by zmathiasz** [comment]
Looks good. :)

**Comment by zmathiasz** [comment]
@dreamnet Hmm, this icon is not updated in the latest release for the 3x Icons.

**Comment by dreamnet** [comment]
@zmathiasz I definitly have updated it. - Glasklart @3x icons are not included in the official Glasklart theme on Cydia, they are only avaliable [here](http://glasklarthd.dreamnet.at/download.php). If we include the @3x icons into the official theme, it would be blown up to over 120MB (so far)....

**Comment by zmathiasz** [comment]
Perfect.  That is what I was thinking after I posted.  DOH!

**Comment by Trubbel** [comment]
I honestly though they were indeed included with the official theme. I guess I'll have to download the @3x-theme as well haha.

**Comment by Trubbel** [comment]
The icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10759865/21abd288-7cba-11e5-9d5a-86938e412af3.png)
https://cloud.githubusercontent.com/assets/10730122/10759865/21abd288-7cba-11e5-9d5a-86938e412af3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10759862/1f32f4fa-7cba-11e5-81b5-2463be9ed067.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Imgur: Memes, GIFs, and More
**Bundle ID:** imgurmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=639881495">639881495</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/imgur-memes-gifs-and-more/id639881495?mt=8&uo=4">https://itunes.apple.com/us/app/imgur-memes-gifs-and-more/id639881495?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** Imgur, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/imgur-inc/id639881498?uo=4">© Imgur, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/0c/04/1e/0c041ef4-0e28-e33d-09d5-64f054f50b74/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34393257-7f81e070-eb51-11e7-8f1f-b74272bbdebd.png)
=https://user-images.githubusercontent.com/20930745/34393257-7f81e070-eb51-11e7-8f1f-b74272bbdebd.png

Source:
https://user-images.githubusercontent.com/20930745/34393277-94074abc-eb51-11e7-93ae-42b39dcb369d.png
