### ISSUE TITLE
SoundHound ∞ hands-free with “OK Hound” | Search, Discover and Play Music

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#3909]
**App Name:** SoundHound ∞ hands-free with “OK Hound” | Search, Discover and Play Music
**Bundle ID:** com.melodis.midomi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284972998">284972998</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/soundhound-hands-free-ok-hound/id284972998?mt=8&uo=4">https://itunes.apple.com/us/app/soundhound-hands-free-ok-hound/id284972998?mt=8&uo=4</a>
**App Version:** 7.1.3
**Seller:** SoundHound, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/soundhound-inc./id284973001?uo=4>© SoundHound, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/a4/d8/46/a4d84682-f94a-6a42-0dcf-8f4012329d3f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17319837/c640f19a-5890-11e6-9eb2-7c964e5fba19.png)

**Comment by ivanov007** [comment]
icon changed
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10413020/9dd63b76-6f60-11e5-9b96-6c6c3aa86ca5.png)
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10413028/28497d68-6f61-11e5-85e2-8933881a0073.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** SoundHound ∞ hands-free with “OK Hound” | Search, Discover and Play Music
**Bundle ID:** com.melodis.midomi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284972998">284972998</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/soundhound-hands-free-ok-hound/id284972998?mt=8&uo=4">https://itunes.apple.com/us/app/soundhound-hands-free-ok-hound/id284972998?mt=8&uo=4</a>
**App Version:** 7.1.3
**Seller:** SoundHound, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/soundhound-inc./id284973001?uo=4>© SoundHound, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/a4/d8/46/a4d84682-f94a-6a42-0dcf-8f4012329d3f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17319837/c640f19a-5890-11e6-9eb2-7c964e5fba19.png)
https://cloud.githubusercontent.com/assets/2068130/17319837/c640f19a-5890-11e6-9eb2-7c964e5fba19.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17319854/d4adc5c8-5890-11e6-8d91-8fa510880d43.png
