### ISSUE TITLE
Anobii Mobile

### ISSUE THREAD

**Issue by tho64** [glasklart/hd#391]
**App Name:** Anobii Mobile
**Bundle ID:** com.anobii.search.aNobii-Search
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327440393">327440393</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/anobii-mobile/id327440393?mt=8&uo=4">https://itunes.apple.com/us/app/anobii-mobile/id327440393?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** Mondadori Libri SPA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mondadori-libri-spa/id987986834?uo=4">© Mondadori Libri SPA</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple71/v4/87/fd/3d/87fd3d6e-35ff-54fc-df5b-89a63b8b4674/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38456777-a077a1bc-3a88-11e8-9fba-179e01fee425.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38456777-a077a1bc-3a88-11e8-9fba-179e01fee425.png)
https://user-images.githubusercontent.com/20930745/38456777-a077a1bc-3a88-11e8-9fba-179e01fee425.png

Source:
https://user-images.githubusercontent.com/20930745/38456782-b1594f1c-3a88-11e8-92b7-73b0575d909d.png
