### ISSUE TITLE
SoundHound + hands-free with “OK Hound” | Search, Discover and Play Music

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#3913]
**App Name:** SoundHound + hands-free with “OK Hound” | Search, Discover and Play Music
**Bundle ID:** com.melodis.soundhound.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=355554941">355554941</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/soundhound-+-hands-free-ok/id355554941?mt=8&uo=4">https://itunes.apple.com/us/app/soundhound-+-hands-free-ok/id355554941?mt=8&uo=4</a>
**App Version:** 7.1.3
**Seller:** SoundHound, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/soundhound-inc./id284973001?uo=4>© SoundHound, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/eb/c7/f5/ebc7f571-ce0a-6d3b-be33-ce6c9af27765/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17321382/9dc15400-5898-11e6-8a67-22958fe1de4b.png)

**Comment by ivanov007** [comment]
icon changed
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10413034/6b3e0c6a-6f61-11e5-9972-f526e1d59c49.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17321382/9dc15400-5898-11e6-8a67-22958fe1de4b.png)
https://cloud.githubusercontent.com/assets/2068130/17321382/9dc15400-5898-11e6-8a67-22958fe1de4b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17321392/ac0ae738-5898-11e6-8604-77d296baadb8.png
