### ISSUE TITLE
Briefcase Pro - File manager, cloud drive, document & pdf reader and file sharing App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#3923]
**App Name:** Briefcase Pro - File manager, cloud drive, document & pdf reader and file sharing App
**Bundle ID:** com.gungyi.PocketBriefcase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=579224808">579224808</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/briefcase-pro-file-manager/id579224808?mt=8&uo=4">https://itunes.apple.com/us/app/briefcase-pro-file-manager/id579224808?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** Qiwen Zhang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/qiwen-zhang/id473538614?uo=4>© Qiwen Zhang</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/fb/f6/e0/fbf6e0d5-0cbb-7445-4ca4-4c16011bceba/mzl.nsvseiyk.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10118715/c07b90d6-647f-11e5-9c3c-2684afc76a82.png)

**Comment by l8er4now** [comment]
Can we do an updated icon?

**App Name:** Briefcase Pro - File manager, cloud drive, document & pdf reader and file sharing App
**Bundle ID:** com.gungyi.PocketBriefcase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=579224808">579224808</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/briefcase-pro-file-manager/id579224808?mt=8&uo=4">https://itunes.apple.com/us/app/briefcase-pro-file-manager/id579224808?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** Qiwen Zhang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/qiwen-zhang/id473538614?uo=4>© Qiwen Zhang</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/fb/f6/e0/fbf6e0d5-0cbb-7445-4ca4-4c16011bceba/mzl.nsvseiyk.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10118715/c07b90d6-647f-11e5-9c3c-2684afc76a82.png)
https://cloud.githubusercontent.com/assets/2068130/10118715/c07b90d6-647f-11e5-9c3c-2684afc76a82.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10118718/d219a8c8-647f-11e5-8f8a-be10e30c39de.png
