### ISSUE TITLE
myWOD — #1 WOD Log for XF Style Workouts

### ISSUE THREAD

**Issue by lauwaet** [glasklart/hd#3934]
**App Name:** myWOD — #1 WOD Log for XF Style Workouts
**Bundle ID:** com.domainname.myWOD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=413025213">413025213</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mywod-1-wod-log-for-xf-style/id413025213?mt=8&uo=4">https://itunes.apple.com/us/app/mywod-1-wod-log-for-xf-style/id413025213?mt=8&uo=4</a>
**App Version:** 5.1.5
**Seller:** MettaBot, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mettabot-llc/id413025216?uo=4>© MettaBot, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/3e/ab/af/3eabaffa-2ad3-e333-88eb-7ad31eb3365e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19319983/b8eb443a-90af-11e6-8847-0e025d6f15ac.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19319983/b8eb443a-90af-11e6-8847-0e025d6f15ac.png)
https://cloud.githubusercontent.com/assets/20930745/19319983/b8eb443a-90af-11e6-8847-0e025d6f15ac.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19319999/c86e7684-90af-11e6-9e8f-a3752bf72269.png
