### ISSUE TITLE
CamScanner +| PDF Document Scanner and OCR

### ISSUE THREAD

**Issue by lauwaet** [glasklart/hd#3936]
**App Name:** CamScanner +| PDF Document Scanner and OCR
**Bundle ID:** com.intsig.CamScanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388624839">388624839</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camscanner-+-pdf-document/id388624839?mt=8&uo=4">https://itunes.apple.com/us/app/camscanner-+-pdf-document/id388624839?mt=8&uo=4</a>
**App Version:** 3.9.15
**Seller:** INTSIG Information Co.,Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/intsig-information-co.-ltd/id344077850?uo=4>© INTSIG Information Co.,Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/4e/9a/63/4e9a6359-4158-a450-ebb6-fefa8aed1657/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19320296/ecc67aee-90b0-11e6-9c16-5bc7ecac8e5b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19320296/ecc67aee-90b0-11e6-9c16-5bc7ecac8e5b.png)
https://cloud.githubusercontent.com/assets/20930745/19320296/ecc67aee-90b0-11e6-9c16-5bc7ecac8e5b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19320317/fe8a2f5a-90b0-11e6-93f0-382f0eda0578.png
