### ISSUE TITLE
BytaFont 2

### ISSUE THREAD

**Issue by lauwaet** [glasklart/hd#3937]
**App Name:** BytaFont 2
**Bundle ID:** com.bytafont.BytaFont2
**iTunes ID:** none (Cydia app)
**Original Artwork:** 
<img src="https://f.cloud.github.com/assets/6720245/2202547/98c259ae-9905-11e3-88e7-b30344c1ab1d.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://f.cloud.github.com/assets/6720245/2202557/d997b37a-9905-11e3-84e7-2f84a160d41f.png)

**Comment by slipko** [comment]
There is now a Bytafont three. Interestingly enough, the icon is the same

**Comment by Trubbel** [comment]
Updating/adding source for **@3x**,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11016589/226c6e5a-8587-11e5-835d-c5a8687f8efe.png)
https://cloud.githubusercontent.com/assets/10730122/11016589/226c6e5a-8587-11e5-835d-c5a8687f8efe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11016587/1eaae21a-8587-11e5-98fd-a9bbf01d747d.png
