### ISSUE TITLE
Simply North

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#394]
**App Name:** Simply North
**Bundle ID:** com.busybytes.simplynorth
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=545173570">545173570</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/simply-north/id545173570?mt=8&uo=4">https://itunes.apple.com/us/app/simply-north/id545173570?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Frank Roch
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/busybytes/id445221797?uo=4">© BusyBytes</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/fa/d3/47/fad34768-c312-89bd-2ad6-666011912905/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20216402/a4e8b738-a81a-11e6-8924-5b048f450297.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20216402/a4e8b738-a81a-11e6-8924-5b048f450297.png)
https://cloud.githubusercontent.com/assets/20930745/20216402/a4e8b738-a81a-11e6-8924-5b048f450297.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20216416/be160ea4-a81a-11e6-90c8-1d9f2e1152c4.png
