### ISSUE TITLE
Comunio

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#3945]
**App Name:** Comunio
**Bundle ID:** de.comunio.comunio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504120424">504120424</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/comunio/id504120424?uo=4">https://apps.apple.com/us/app/comunio/id504120424?uo=4</a>
**App Version:** 8.4.3
**Seller:** Marko Fritzsche
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/comunio-gmbh/id504120427?uo=4">© Comunio GmbH</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/8a/c1/f5/8ac1f5ba-f804-b362-549d-4b79736f6d0e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60370062-d7ea3b00-99f5-11e9-9ff3-0e19b84be67a.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60370062-d7ea3b00-99f5-11e9-9ff3-0e19b84be67a.png)
https://user-images.githubusercontent.com/2068130/60370062-d7ea3b00-99f5-11e9-9ff3-0e19b84be67a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60370076-e59fc080-99f5-11e9-94ea-37513d7e8f18.png
