### ISSUE TITLE
Sky Go

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#3954]
**App Name:** Sky Go
**Bundle ID:** de.sky.skysportapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375667763">375667763</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/sky-go/id375667763?mt=8&uo=4">https://itunes.apple.com/de/app/sky-go/id375667763?mt=8&uo=4</a>
**App Version:** 6.0.7
**Seller:** Sky Deutschland AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/sky/id375667766?uo=4>© Sky</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/7a/e4/d1/7ae4d1f1-a602-f1b3-b92d-d1548125d0de/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18933257/31619b62-85d4-11e6-9f77-6b1f9f4de9c8.png)

**Comment by Anuskuss** [comment]
Needs update (but looks worse).

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18933257/31619b62-85d4-11e6-9f77-6b1f9f4de9c8.png)
https://cloud.githubusercontent.com/assets/20930745/18933257/31619b62-85d4-11e6-9f77-6b1f9f4de9c8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18933275/45c08e6a-85d4-11e6-9d53-9753ffa09573.png
