### ISSUE TITLE
Runtastic GPS Running, Walking, Jogging, Fitness Distance Tracker and Marathon Training

### ISSUE THREAD

**Issue by lauwaet** [glasklart/hd#3956]
**App Name:** Runtastic GPS Running, Walking, Jogging, Fitness Distance Tracker and Marathon Training
**Bundle ID:** at.runtastic.gpssportapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336599882">336599882</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-gps-running-walking/id336599882?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-gps-running-walking/id336599882?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPadMini, iPadMini4G, iPadThirdGen4G, iPhone5, iPhone5s, iPhone4, iPhone6, iPad23G, iPadFourthGen, iPodTouchSixthGen, iPhone4S, iPadThirdGen, iPodTouchFifthGen, iPad2Wifi, iPhone5c, iPhone6Plus, iPadFourthGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple69/v4/1b/a0/0e/1ba00eac-638f-7d5a-388b-fc4bb37cf7db/mzl.ijweqmqx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9272984/067d681c-4288-11e5-895a-08a327c4e539.png)

**Comment by dreamnet** [comment]
Just updating to make the Runtastic apps look the same.
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9272984/067d681c-4288-11e5-895a-08a327c4e539.png)
https://cloud.githubusercontent.com/assets/2068130/9272984/067d681c-4288-11e5-895a-08a327c4e539.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9273002/323ecb4e-4288-11e5-90c5-e2fee34e3db7.png
