### ISSUE TITLE
Runtastic Road Bike PRO GPS Cycling Computer, Ride and Route Tracker

### ISSUE THREAD

**Issue by lauwaet** [glasklart/hd#3957]
**App Name:** Runtastic Road Bike PRO GPS Cycling Computer, Ride and Route Tracker
**Bundle ID:** com.runtastic.iphone.roadbike.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=468429333">468429333</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-road-bike-pro-gps/id468429333?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-road-bike-pro-gps/id468429333?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPadMini, iPadFourthGen4G, iPad2Wifi, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6Plus, iPhone4, iPadThirdGen, iPadMini4G, iPadThirdGen4G, iPhone5, iPhone4S, iPhone6, iPadFourthGen, iPad23G, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/ad/40/08/ad4008b2-840d-40ad-7328-34039b57e531/mzl.tlzehjyj.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9273215/b60f5644-428a-11e5-9595-c15bf20505e7.png)

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9273215/b60f5644-428a-11e5-9595-c15bf20505e7.png)
https://cloud.githubusercontent.com/assets/2068130/9273215/b60f5644-428a-11e5-9595-c15bf20505e7.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9273226/c6d33aae-428a-11e5-92b0-3d290dd9402a.png
