### ISSUE TITLE
Groopic

### ISSUE THREAD

**Issue by lauwaet** [glasklart/hd#3958]
**App Name:** Groopic
**Bundle ID:** com.eyedeuslabs.groopic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=584710005">584710005</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/groopic/id584710005?mt=8&uo=4">https://itunes.apple.com/us/app/groopic/id584710005?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Ingrain Media Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ingrain/id1109287587?uo=4>© Ingrain</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/d6/f6/86/d6f6863a-3841-7d32-9545-65099ee0e02a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19387342/f799b372-9219-11e6-893a-268c0f49d428.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19387342/f799b372-9219-11e6-893a-268c0f49d428.png)
https://cloud.githubusercontent.com/assets/20930745/19387342/f799b372-9219-11e6-893a-268c0f49d428.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19387360/0af04b0c-921a-11e6-910e-087c3664909b.png
