### ISSUE TITLE
Voxer Walkie Talkie Messenger

### ISSUE THREAD

**Issue by richmFTW** [glasklart/hd#396]
**App Name:** Voxer Walkie Talkie Messenger
**Bundle ID:** com.rebelvox.voxer-lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377304531">377304531</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/voxer-walkie-talkie-messenger/id377304531?mt=8&uo=4">https://itunes.apple.com/us/app/voxer-walkie-talkie-messenger/id377304531?mt=8&uo=4</a>
**App Version:** 3.13.0
**Seller:** Voxer LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/voxer-llc/id377304534?uo=4>© Voxer LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/42/d2/42/42d24291-24c8-dac5-30de-f64c3cf02744/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12225248/a20beb5c-b806-11e5-90e1-6c2e2cb9e1e0.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8523514/1e5626aa-23f6-11e5-8c20-be20ac201bb8.png)
https://cloud.githubusercontent.com/assets/10730122/8523514/1e5626aa-23f6-11e5-8c20-be20ac201bb8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8523511/1adb39de-23f6-11e5-91b3-8a5013d9a189.png

**Comment by Trubbel** [comment]
Another update,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12225248/a20beb5c-b806-11e5-90e1-6c2e2cb9e1e0.png)
https://cloud.githubusercontent.com/assets/10730122/12225248/a20beb5c-b806-11e5-90e1-6c2e2cb9e1e0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12225247/a20b6ce0-b806-11e5-9a05-c500020967c3.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
