### ISSUE TITLE
Telegram Messenger

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3960]
**App Name:** Telegram Messenger
**Bundle ID:** ph.telegra.Telegraph
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=686449807">686449807</a>
**iTunes URL:** https://itunes.apple.com/us/app/telegram-messenger/id686449807?mt=8&uo=4
**App Version:** 2.0.1
**Seller:** Digital Fortress LLC
**Supported Devices:** iPodTouchourthGen, iPad2Wifi, iPodTouchFifthGen, iPadThirdGen4G, iPadFourthGen, iPhone4S, iPadMini4G, iPadThirdGen, iPadMini, iPad23G, iPhone5s, iPhone5, iPhone-3GS, iPadFourthGen4G, iPhone4, iPhone5c
**Original Artwork:**
<img src="http://a263.phobos.apple.com/us/r30/Purple4/v4/34/00/55/3400555c-992a-7c18-6bbb-85aa421a0e3c/mzl.qrowsbef.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://f.cloud.github.com/assets/3090247/2224768/e2806242-9a82-11e3-94b8-23b1cb96558c.png)

**Comment by coolstar** [comment]
Is this icon not included in the latest Glasklart? My Telegram icon isn't themed here...

**Comment by dreamnet** [comment]
@coolstar We - or better modmyi - had [a problem with Glasklart release 4.39](https://github.com/glasklart/hd/issues/7738). Please wait for 4.40 or download the actual master and copy the files over the existing ones.
