### ISSUE TITLE
Cloudy Exporter

### ISSUE THREAD

**Issue by lauwaet** [glasklart/hd#3962]
**App Name:** Cloudy Exporter
**Bundle ID:** Walker-Solutions.CloudyExporter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484626424">484626424</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cloudy-exporter/id484626424?mt=8&uo=4">https://itunes.apple.com/us/app/cloudy-exporter/id484626424?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Rebecca Collins
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/walker-solutions/id484626427?uo=4>© Walker Solutions</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/7e/1c/b3/7e1cb3c5-1033-717b-1f4d-6934d4769d30/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19416423/16e60be6-9390-11e6-8b58-67ba0c0834d0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19416410/c638a730-938f-11e6-99a1-8939be4fb657.png)
https://cloud.githubusercontent.com/assets/20930745/19416410/c638a730-938f-11e6-99a1-8939be4fb657.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19416413/d5270192-938f-11e6-89b7-207f7f914f49.png
