### ISSUE TITLE
Proportion Solver

### ISSUE THREAD

**Issue by lauwaet** [glasklart/hd#3967]
**App Name:** Proportion Solver
**Bundle ID:** com.ashcraftmedia.proportionsolver
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=325357198">325357198</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/proportion-solver/id325357198?mt=8&uo=4">https://itunes.apple.com/us/app/proportion-solver/id325357198?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Ryan Ashcraft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ryan-ashcraft/id322118384?uo=4>© Ryan Ashcraft</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple32/v4/08/07/19/08071982-ce3e-b911-153d-7ad4260f9787/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19319760/a051d714-90ae-11e6-8524-c8aad7b8ed3e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19319760/a051d714-90ae-11e6-8524-c8aad7b8ed3e.png)
https://cloud.githubusercontent.com/assets/20930745/19319760/a051d714-90ae-11e6-8524-c8aad7b8ed3e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19319778/b0c78e86-90ae-11e6-861c-fe725c28d700.png
