### ISSUE TITLE
Hokusai Audio Editor

### ISSUE THREAD

**Issue by winkelement** [glasklart/hd#3969]
**App Name:** Hokusai Audio Editor
**Bundle ID:** com.woojijuice.Hokusai
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432079746">432079746</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hokusai-audio-editor/id432079746?mt=8&uo=4">https://itunes.apple.com/us/app/hokusai-audio-editor/id432079746?mt=8&uo=4</a>
**App Version:** 2.0.6
**Seller:** Wooji Juice Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wooji-juice-ltd/id284937604?uo=4>© Wooji Juice Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/f0/92/74/f0927464-0768-c92a-076c-c1a9efe7dacc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18959422/6649db04-8666-11e6-9fba-c844cfcb3348.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18947264/a051a608-8632-11e6-9447-0c854eb2d898.png)
https://cloud.githubusercontent.com/assets/20930745/18947264/a051a608-8632-11e6-9447-0c854eb2d898.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18947272/ab45799a-8632-11e6-8d2c-7534a7caeb96.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18959422/6649db04-8666-11e6-9fba-c844cfcb3348.png)
https://cloud.githubusercontent.com/assets/20930745/18959422/6649db04-8666-11e6-9fba-c844cfcb3348.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18959443/7953ea64-8666-11e6-88f6-fcf3382bec44.png
