### ISSUE TITLE
iSzene HD+

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#3978]
**App Name:** iSzene HD+
**Bundle ID:** com.iszenehdapp.iszeneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=595580409">595580409</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/iszene-hd/id595580409?uo=4">https://apps.apple.com/de/app/iszene-hd/id595580409?uo=4</a>
**App Version:** 5.0
**Seller:** smartlive GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/smartlive-gmbh/id783009884?uo=4">© smartlive GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/e9/e4/32/e9e43258-6833-049a-b3ae-01da2be2a1ad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62397231-86454b00-b575-11e9-9fa3-70c7b21fd8a5.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62397231-86454b00-b575-11e9-9fa3-70c7b21fd8a5.png)
https://user-images.githubusercontent.com/2068130/62397231-86454b00-b575-11e9-9fa3-70c7b21fd8a5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62397246-95c49400-b575-11e9-8c31-98fbe2685a98.png
