### ISSUE TITLE
Cloze - Relationship Management, Inbox & Contacts

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#3980]
**App Name:** Cloze - Relationship Management, Inbox & Contacts
**Bundle ID:** com.cloze.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=596927802">596927802</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cloze-relationship-management/id596927802?mt=8&uo=4">https://itunes.apple.com/us/app/cloze-relationship-management/id596927802?mt=8&uo=4</a>
**App Version:** 4.7.1
**Seller:** Cloze, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cloze/id596927805?uo=4>© Cloze</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/0c/15/65/0c1565bd-3710-8697-76aa-0c062b68b001/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19838358/d85cad6e-9ecd-11e6-9c9f-98b300e331e9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19838358/d85cad6e-9ecd-11e6-9c9f-98b300e331e9.png)
https://cloud.githubusercontent.com/assets/20930745/19838358/d85cad6e-9ecd-11e6-9c9f-98b300e331e9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19838361/e510a10a-9ecd-11e6-942e-045ca6fcb26b.png
