### ISSUE TITLE
Endomondo

### ISSUE THREAD

**Issue by winkelement** [glasklart/hd#3983]
**App Name:** Endomondo
**Bundle ID:** com.endomondo.Endomondo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=333210180">333210180</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/endomondo/id333210180?uo=4">https://apps.apple.com/us/app/endomondo/id333210180?uo=4</a>
**App Version:** 18.10.1
**Seller:** Endomondo LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/endomondo-com/id333210183?uo=4">© Endomondo.com</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/b9/ec/82/b9ec82fa-8d42-e6ee-7e89-7b74480c6a67/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387569-7d101c80-9aa5-11e9-9162-0f545b03aa56.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19387159/b03c6db8-9218-11e6-877a-86b250abfda3.png)
https://cloud.githubusercontent.com/assets/20930745/19387159/b03c6db8-9218-11e6-877a-86b250abfda3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19387167/be219994-9218-11e6-84d8-3175c11e80ba.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387569-7d101c80-9aa5-11e9-9162-0f545b03aa56.png)
https://user-images.githubusercontent.com/20930745/60387569-7d101c80-9aa5-11e9-9162-0f545b03aa56.png

Source:
https://user-images.githubusercontent.com/20930745/60387572-7ed9e000-9aa5-11e9-94f0-eaa13b36263a.png
