### ISSUE TITLE
Endomondo Sports Tracker PRO – GPS Track Running Cycling Walking & More

### ISSUE THREAD

**Issue by winkelement** [glasklart/hd#3984]
**App Name:** Endomondo Sports Tracker PRO – GPS Track Running Cycling Walking & More
**Bundle ID:** com.endomondo.EndomondoPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416797509">416797509</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/tt/app/endomondo-sports-tracker-pro/id416797509?mt=8&uo=4">https://itunes.apple.com/tt/app/endomondo-sports-tracker-pro/id416797509?mt=8&uo=4</a>
**App Version:** 8.9.2
**Seller:** Endomondo LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/tt/developer/endomondo.com/id333210183?uo=4>© Endomondo.com</a>
**Supported Devices:** iPhone-3GS, iPad3G, iPhone4, iPad23G, iPhone4S, iPadThirdGen4G, iPhone5, iPadFourthGen4G, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/3d/13/d1/3d13d11b-ded0-b1f5-31e5-f40431f05475/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19387074/398f6e0e-9218-11e6-9ee7-70723934e067.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19387024/f19026b6-9217-11e6-95fc-faa158857daf.png)
https://cloud.githubusercontent.com/assets/20930745/19387024/f19026b6-9217-11e6-95fc-faa158857daf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19387031/02956ade-9218-11e6-805f-e62251431cce.png
