### ISSUE TITLE
CL-WiFi

### ISSUE THREAD

**Issue by winkelement** [glasklart/hd#3985]
**App Name:** CL-WiFi
**Bundle ID:** com.sounddevices.CL-WiFi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=419268431">419268431</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cl-wifi/id419268431?mt=8&uo=4">https://itunes.apple.com/us/app/cl-wifi/id419268431?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Sound Devices, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sound-devices-llc/id418450388?uo=4>© Sound Devices, LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/77/9a/08/779a081d-9faa-e02e-a5df-5103b7ee3d88/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19386419/5ff369be-9214-11e6-9e4d-236c1e192713.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19386419/5ff369be-9214-11e6-9e4d-236c1e192713.png)
https://cloud.githubusercontent.com/assets/20930745/19386419/5ff369be-9214-11e6-9e4d-236c1e192713.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19386429/705e0d2c-9214-11e6-84e0-9114eb6db78a.png
