### ISSUE TITLE
BLEND - Overlay your pics

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3987]
**App Name:** BLEND - Overlay your pics
**Bundle ID:** it.printzel.Blend
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=694244902">694244902</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blend-overlay-your-pics/id694244902?mt=8&uo=4">https://itunes.apple.com/us/app/blend-overlay-your-pics/id694244902?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Printzel LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/printzel/id620028940?uo=4>© Printzel</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/4e/ac/cb/4eaccbdc-78b9-8fdc-eebe-1927495c9df1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19386660/ce1f0636-9215-11e6-91a0-f40dd5882279.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19386660/ce1f0636-9215-11e6-91a0-f40dd5882279.png)
https://cloud.githubusercontent.com/assets/20930745/19386660/ce1f0636-9215-11e6-91a0-f40dd5882279.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19386674/dc69d7ca-9215-11e6-9043-937795a9d469.png
