### ISSUE TITLE
Move to measure - Flying Ruler

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3994]
**App Name:** Move to measure - Flying Ruler
**Bundle ID:** Alexey-Brilev.Flying-Ruler
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=667579844">667579844</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/move-to-measure-flying-ruler/id667579844?mt=8&uo=4">https://itunes.apple.com/us/app/move-to-measure-flying-ruler/id667579844?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** ALEXEY BRILEV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alexey-brilev/id667579847?uo=4>© ALEXEY BRILEV</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/22/ca/0f/22ca0fc4-e8d7-8d8e-c622-92eb8b2532aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19386294/a53ecb22-9213-11e6-8018-c0f5e21c9c81.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19386294/a53ecb22-9213-11e6-8018-c0f5e21c9c81.png)
https://cloud.githubusercontent.com/assets/20930745/19386294/a53ecb22-9213-11e6-8018-c0f5e21c9c81.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19386308/b6849240-9213-11e6-832e-9098d2ea3a17.png
