### ISSUE TITLE
FOX Sports GO

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3995]
**App Name:** FOX Sports GO
**Bundle ID:** com.uie.foxsports.foxsportsgo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=711074743">711074743</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fox-sports-go/id711074743?mt=8&uo=4">https://itunes.apple.com/us/app/fox-sports-go/id711074743?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** FOX Sports Interactive
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fox-sports-interactive/id294056626?uo=4>© FOX Sports Interactive</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/a2/56/91/a25691f0-99b8-7c46-5ddc-9a84b850e14d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18719899/a20b5160-8029-11e6-9373-08934d818cba.png)

**Comment by Sly-Fi** [comment]
This icon is missing from 5.0 release

**Comment by Trubbel** [comment]
Yep, no source on this one - reopening.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18719899/a20b5160-8029-11e6-9373-08934d818cba.png)
https://cloud.githubusercontent.com/assets/2068130/18719899/a20b5160-8029-11e6-9373-08934d818cba.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18719909/b05b2eac-8029-11e6-9036-476fcae00fe8.png
