### ISSUE TITLE
Infuse 3 ~ an elegant video player for all your media

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#4001]
**App Name:** Infuse 3 ~ an elegant video player for all your media
**Bundle ID:** com.firecore.fuse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=577130046">577130046</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/infuse-3-elegant-video-player/id577130046?mt=8&uo=4">https://itunes.apple.com/us/app/infuse-3-elegant-video-player/id577130046?mt=8&uo=4</a>
**App Version:** 3.6.2
**Seller:** FireCore, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/firecore-llc/id577130089?uo=4>© FireCore, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/40/1f/e7/401fe769-08b0-61dd-56b4-60eb7bd248ae/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22629628/b8da8c5e-ebe9-11e6-8477-158338f30103.png)

**Comment by Anuskuss** [comment]
This icon is the same for **com.firecore.infuse.pro**

**Comment by dreamnet** [comment]
@Anuskuss Please open a new issue for `com.firecore.infuse.pro`. We need the iTunes ID.
