### ISSUE TITLE
Oxford American English

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#4015]
**App Name:** Oxford American English
**Bundle ID:** com.mobisystems.OxfordAmericanDictAndThes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=679562156">679562156</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/oxford-american-english/id679562156?mt=8&uo=4">https://itunes.apple.com/us/app/oxford-american-english/id679562156?mt=8&uo=4</a>
**App Version:** 10.0.3
**Seller:** MobiSystems, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mobisystems-inc/id289579214?uo=4">© MobiSystems, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/b7/fa/98/b7fa9894-3d3a-5c0a-9397-7dd4774cd9c7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468830-2964a25c-0327-11e8-8e11-6614d1282b7c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468830-2964a25c-0327-11e8-8e11-6614d1282b7c.png)
https://user-images.githubusercontent.com/2068130/35468830-2964a25c-0327-11e8-8e11-6614d1282b7c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/35468835-38aff5b8-0327-11e8-9ae7-5a7831cbe359.png
