### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4019]
**App Name:** RTL
**Bundle ID:** fr.rtl.rtl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=556668009">556668009</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rtl/id556668009?mt=8&uo=4">https://itunes.apple.com/us/app/rtl/id556668009?mt=8&uo=4</a>
**App Version:** 5.0.2
**Seller:** RTL Net
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rtl-net/id385107051?uo=4>© RTL NET</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/d4/2b/a4/d42ba492-8fff-9662-87e3-8272f110ed10/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19319570/bb141ff4-90ad-11e6-902e-de0b93aaeccd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19319570/bb141ff4-90ad-11e6-902e-de0b93aaeccd.png)
https://cloud.githubusercontent.com/assets/20930745/19319570/bb141ff4-90ad-11e6-902e-de0b93aaeccd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19319600/d3f6b432-90ad-11e6-9ad2-b442c5911c75.png
