### ISSUE TITLE
Europe 1 - radio, replay, actu

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4021]
**App Name:** Europe 1 - radio, replay, actu
**Bundle ID:** com.lagardere.Europe1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=345872583">345872583</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/europe-1-radio-replay-actu/id345872583?uo=4">https://apps.apple.com/us/app/europe-1-radio-replay-actu/id345872583?uo=4</a>
**App Version:** 5.0
**Seller:** Lagardere Media News
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lagardere-media-news/id1452555903?uo=4">© Lagardere Media News</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/1e/cb/d3/1ecbd32a-19a9-a2b7-19dc-e95bec2148c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387612-1ccdaa80-9aa6-11e9-9689-df48c6f5c906.png)

**Comment by dreamnet** [comment]
Needs an update (too big).

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387612-1ccdaa80-9aa6-11e9-9689-df48c6f5c906.png)
https://user-images.githubusercontent.com/20930745/60387612-1ccdaa80-9aa6-11e9-9689-df48c6f5c906.png

Source:
https://user-images.githubusercontent.com/20930745/60387613-1dfed780-9aa6-11e9-8289-d67a78dc60d5.png
