### ISSUE TITLE
Mooncast - The Phases of the Moon

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4027]
**App Name:** Mooncast - The Phases of the Moon
**Bundle ID:** com.mathieurouthier.Mooncast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=473165402">473165402</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mooncast-phases-moon/id473165402?mt=8&uo=4">https://itunes.apple.com/us/app/mooncast-phases-moon/id473165402?mt=8&uo=4</a>
**App Version:** 4.6
**Seller:** Mathieu Routhier
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mathieu-routhier/id369283978?uo=4>© Mathieu Routhier</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple4/v4/8d/87/bc/8d87bcae-3d0d-23e1-195b-b69c376be8e6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18958694/c0867e9a-8663-11e6-8101-341a7af8dc94.png)

**Comment by Sly-Fi** [comment]
This icon is missing from 5.0.0 release

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18958694/c0867e9a-8663-11e6-8101-341a7af8dc94.png)
https://cloud.githubusercontent.com/assets/20930745/18958694/c0867e9a-8663-11e6-8101-341a7af8dc94.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18958726/e3cc4146-8663-11e6-8ed3-dcff91c46d4b.png
