### ISSUE TITLE
RNN Companion

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4033]
**App Name:** RNN Companion
**Bundle ID:** com.mdv.RNNCompanion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=503089633">503089633</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rnn-companion/id503089633?mt=8&uo=4">https://itunes.apple.com/us/app/rnn-companion/id503089633?mt=8&uo=4</a>
**App Version:** v3.2.20160225
**Seller:** Mentz Datenverarbeitung GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mentz-datenverarbeitung-gmbh/id388686731?uo=4>© Mentz Datenverarbeitung GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/94/2e/4d/942e4d23-23f4-c9dc-ecf4-c3081289db83/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19838167/e03ed696-9ec9-11e6-9ad7-347b8251f483.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19838167/e03ed696-9ec9-11e6-9ad7-347b8251f483.png)
https://cloud.githubusercontent.com/assets/20930745/19838167/e03ed696-9ec9-11e6-9ad7-347b8251f483.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19838175/f8c1ca98-9ec9-11e6-857c-dac418410fc6.png
