### ISSUE TITLE
Halftone - Turn Photos Into Comics!

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4040]
**App Name:** Halftone - Turn Photos Into Comics!
**Bundle ID:** com.juicybitssoftware.Halftone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=419957803">419957803</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/halftone-turn-photos-into/id419957803?mt=8&uo=4">https://itunes.apple.com/us/app/halftone-turn-photos-into/id419957803?mt=8&uo=4</a>
**App Version:** 1.9.9
**Seller:** Juicy Bits
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/juicy-bits/id316966273?uo=4>© Juicy Bits</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple32/v4/3f/86/c9/3f86c97d-f8a8-1b11-e85b-f0716ffcb0ca/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19318961/010e1148-90ab-11e6-8cfb-d670e7af563a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19318961/010e1148-90ab-11e6-8cfb-d670e7af563a.png)
https://cloud.githubusercontent.com/assets/20930745/19318961/010e1148-90ab-11e6-8cfb-d670e7af563a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19318982/125301ca-90ab-11e6-8c3d-53b06ffcb4e7.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19319330/c6c2ebf6-90ac-11e6-94ff-7ec1ee661294.png)
https://cloud.githubusercontent.com/assets/20930745/19319330/c6c2ebf6-90ac-11e6-94ff-7ec1ee661294.png

Source;
https://cloud.githubusercontent.com/assets/20930745/19319347/d5e3ab0c-90ac-11e6-8001-4dd9d574a8da.png
