### ISSUE TITLE
iMovie

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#4042]
**App Name:** iMovie
**Bundle ID:** com.apple.iMovie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377298193">377298193</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/imovie/id377298193?mt=8&uo=4">https://itunes.apple.com/us/app/imovie/id377298193?mt=8&uo=4</a>
**App Version:** 2.2.4
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/da/82/98/da82980d-51e8-5e37-bc0b-3a3dde7ac1b4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31316103-aaca8c06-ac26-11e7-8862-16757d06518b.png)

**Comment by LaCh0uine** [comment]
Need to be updated

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8894731/a4aca4b0-33c1-11e5-969c-beb3db9f1f6c.png)
https://cloud.githubusercontent.com/assets/10730122/8894731/a4aca4b0-33c1-11e5-969c-beb3db9f1f6c.png
--- ---
Source (@n0mar):
https://cloud.githubusercontent.com/assets/10730122/8894729/a0fb569a-33c1-11e5-9574-e7319427761c.png

**Comment by LaCh0uine** [comment]
No circle now ;)
http://51ec5c0d06ef68842cbd-eb61d9770b9e4a1d2dacebe5287fbc1d.r85.cf2.rackcdn.com/37A14B39-9BC2-4462-823F-0976017399EB.jpg

**Comment by Trubbel** [comment]
@LaCh0uine Ah, slipped my mind, thanks for letting me know!

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8895053/8d9f8656-33cc-11e5-81aa-b9837a562313.png)
https://cloud.githubusercontent.com/assets/10730122/8895053/8d9f8656-33cc-11e5-81aa-b9837a562313.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8895051/89d3639e-33cc-11e5-8de8-f6c4b80fb71b.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31316103-aaca8c06-ac26-11e7-8862-16757d06518b.png)
https://user-images.githubusercontent.com/2068130/31316103-aaca8c06-ac26-11e7-8862-16757d06518b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31316107-bcb878ec-ac26-11e7-812f-887d2c409984.png
