### ISSUE TITLE
iBooks

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#4046]
**App Name:** iBooks
**Bundle ID:** com.apple.iBooks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364709193">364709193</a>
**iTunes URL:** https://itunes.apple.com/us/app/ibooks/id364709193?mt=8&uo=4
**App Version:** 3.2
**Seller:** Apple Inc.
**Supported Devices:** iPhone5s, iPadMini, iPadFourthGen4G, iPodTouchFifthGen, iPhone4, iPad2Wifi, iPadThirdGen4G, iPad23G, iPhone5c, iPadMini4G, iPhone5, iPadFourthGen, iPadThirdGen, iPhone4S
**Original Artwork:**
<img src="http://a179.phobos.apple.com/us/r30/Purple4/v4/4b/fc/7a/4bfc7a77-8e2b-99f3-d674-849bdab3e419/mzl.ieoleulw.png" width="150" height="150" />
**Accepted Artwork:**
![com apple ibooks 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10704545/d2eae4a2-79d7-11e5-96d3-19b06cdb0af6.png)

**Comment by dreamnet** [comment]
Updating to the iOS9 version of the app....
![com apple ibooks 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10704545/d2eae4a2-79d7-11e5-96d3-19b06cdb0af6.png)
https://cloud.githubusercontent.com/assets/2068130/10704545/d2eae4a2-79d7-11e5-96d3-19b06cdb0af6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10704553/e24ca156-79d7-11e5-87a2-b9bca7c409e9.png
