### ISSUE TITLE
DS cam

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4053]
**App Name:** DS cam
**Bundle ID:** com.synology.SurveillanceStation
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=349087111">349087111</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ds-cam/id349087111?mt=8&uo=4">https://itunes.apple.com/us/app/ds-cam/id349087111?mt=8&uo=4</a>
**App Version:** 4.6.5
**Seller:** Synology Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/synology-inc./id321493109?uo=4>© Synology Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/12/7e/31/127e319a-db9c-086a-c948-33907517beea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416841/bcbf82b2-7820-11e6-8806-0b83ba6f386e.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416841/bcbf82b2-7820-11e6-8806-0b83ba6f386e.png)
https://cloud.githubusercontent.com/assets/2068130/18416841/bcbf82b2-7820-11e6-8806-0b83ba6f386e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416842/c9ea2816-7820-11e6-9562-6d0d4d8950b1.png
