### ISSUE TITLE
Ds cloud

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4054]
**App Name:** DS cloud
**Bundle ID:** com.synology.DScloud
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=590216612">590216612</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ds-cloud/id590216612?mt=8&uo=4">https://itunes.apple.com/us/app/ds-cloud/id590216612?mt=8&uo=4</a>
**App Version:** 2.9.2
**Seller:** Synology Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/synology-inc./id321493109?uo=4>© Synology Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/26/58/4f/26584f2a-1f16-917d-5253-eb9ffc57d507/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416340/088544fc-7812-11e6-975f-bf83928c5e72.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416340/088544fc-7812-11e6-975f-bf83928c5e72.png)
https://cloud.githubusercontent.com/assets/2068130/18416340/088544fc-7812-11e6-975f-bf83928c5e72.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416343/18bcd844-7812-11e6-9c72-558ae79c72c7.png
