### ISSUE TITLE
Ds video

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4055]
**App Name:** DS video
**Bundle ID:** com.synology.DSvideo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540949418">540949418</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ds-video/id540949418?mt=8&uo=4">https://itunes.apple.com/us/app/ds-video/id540949418?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Synology Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/synology-inc./id321493109?uo=4>© Synology Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/a5/b6/bb/a5b6bb17-ccce-7bec-4cfb-5ce4f212a98a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416365/c6736cc8-7812-11e6-9920-f27fe0cd1624.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416365/c6736cc8-7812-11e6-9920-f27fe0cd1624.png)
https://cloud.githubusercontent.com/assets/2068130/18416365/c6736cc8-7812-11e6-9920-f27fe0cd1624.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416368/d7265486-7812-11e6-88df-4cc256237f92.png
