### ISSUE TITLE
Air Keyboard: Free wireless Mouse, Touch Pad and Keyboard for your PC, Mac or Android

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4057]
**App Name:** Air Keyboard: Free wireless Mouse, Touch Pad and Keyboard for your PC, Mac or Android
**Bundle ID:** com.skygears.airkeyboardiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=541873446">541873446</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/air-keyboard-free-wireless/id541873446?mt=8&uo=4">https://itunes.apple.com/us/app/air-keyboard-free-wireless/id541873446?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** Alexey Filatov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alexey-filatov/id446643465?uo=4>© Alexey Filatov</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple4/v4/8c/1c/4e/8c1c4eda-8e70-a4c7-21c7-632c0565da98/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19318426/f3850bd2-90a8-11e6-9d16-144c0ab817c0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19318426/f3850bd2-90a8-11e6-9d16-144c0ab817c0.png)
https://cloud.githubusercontent.com/assets/20930745/19318426/f3850bd2-90a8-11e6-9d16-144c0ab817c0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19318437/045ac082-90a9-11e6-87d7-435ab4a56505.png
