### ISSUE TITLE
Evenium ConnexMe

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4058]
**App Name:** Evenium ConnexMe
**Bundle ID:** com.evenium.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=411494318">411494318</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/evenium-connexme/id411494318?mt=8&uo=4">https://itunes.apple.com/us/app/evenium-connexme/id411494318?mt=8&uo=4</a>
**App Version:** 7.0
**Seller:** EVENIUM
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/evenium/id411494321?uo=4>© Evenium</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/27/07/99/27079944-1229-6b2e-625a-7eee93a0f234/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19385927/d378b6f8-9211-11e6-99fb-9c7600ab82b7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19385927/d378b6f8-9211-11e6-99fb-9c7600ab82b7.png)
https://cloud.githubusercontent.com/assets/20930745/19385927/d378b6f8-9211-11e6-99fb-9c7600ab82b7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19385941/e7f1019e-9211-11e6-9576-cb9f92712559.png
