### ISSUE TITLE
100+ Pushups - Getting in Shape in Six Weeks

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4059]
**App Name:** 100+ Pushups - Getting in Shape in Six Weeks
**Bundle ID:** com.weedo.Pushups
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571934210">571934210</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/100+-pushups-getting-in-shape/id571934210?mt=8&uo=4">https://itunes.apple.com/us/app/100+-pushups-getting-in-shape/id571934210?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Weedo Technology Co., Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/weedo-technology-co.-limited/id524058483?uo=4>© Weedo Technology Co., Limited</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/fa/1d/6e/fa1d6e34-fa6c-d714-6763-46c5f3835742/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19385689/45918e4c-9210-11e6-98b9-3cd012def08e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19385689/45918e4c-9210-11e6-98b9-3cd012def08e.png)
https://cloud.githubusercontent.com/assets/20930745/19385689/45918e4c-9210-11e6-98b9-3cd012def08e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19385707/5814b814-9210-11e6-9a0a-ac3e237530e6.png
