### ISSUE TITLE
200+ Squats - Striking A Perfect Lower Body Curve in Six Weeks

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4060]
**App Name:** 200+ Squats - Striking A Perfect Lower Body Curve in Six Weeks
**Bundle ID:** com.weedo.Squats
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=572230466">572230466</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/200+-squats-striking-perfect/id572230466?mt=8&uo=4">https://itunes.apple.com/us/app/200+-squats-striking-perfect/id572230466?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Weedo Technology Co., Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/weedo-technology-co.-limited/id524058483?uo=4>© Weedo Technology Co., Limited</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/f8/4d/f5/f84df517-a342-6a02-e9e4-45322f1fd412/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19385329/3c30dbd4-920e-11e6-854b-18c0aa70362f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19385329/3c30dbd4-920e-11e6-854b-18c0aa70362f.png)
https://cloud.githubusercontent.com/assets/20930745/19385329/3c30dbd4-920e-11e6-854b-18c0aa70362f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19385350/4faeedb8-920e-11e6-801d-9968fc4dafd2.png
