### ISSUE TITLE
Living Earth - Clock & Weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#4061]
**App Name:** Living Earth - Clock & Weather
**Bundle ID:** com.liability.Earth-Clock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=379869627">379869627</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/living-earth-clock-weather/id379869627?mt=8&uo=4">https://itunes.apple.com/us/app/living-earth-clock-weather/id379869627?mt=8&uo=4</a>
**App Version:** 3.71
**Seller:** Radiantlabs, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/radiantlabs-llc/id379869630?uo=4>© Radiantlabs, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/51/ba/5e/51ba5e04-e8db-4f56-585e-e199693c124a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13447356/392c3b86-e01b-11e5-91f6-62cb64d3ef72.png)

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13447356/392c3b86-e01b-11e5-91f6-62cb64d3ef72.png)
https://cloud.githubusercontent.com/assets/10730122/13447356/392c3b86-e01b-11e5-91f6-62cb64d3ef72.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13447357/392d5494-e01b-11e5-9056-6f2727d49ae0.png
