### ISSUE TITLE
Last Time - track your important events

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4065]
**App Name:** Last Time - track your important events
**Bundle ID:** com.sarunw.lasttime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=534982023">534982023</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/last-time-track-your-important/id534982023?mt=8&uo=4">https://itunes.apple.com/us/app/last-time-track-your-important/id534982023?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Sarun Wongpatcharapakorn
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sarun-wongpatcharapakorn/id469774500?uo=4>© Sarun Wongpatcharapakorn</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/33/99/a4/3399a478-e3b0-0bcb-6011-4cf556e98288/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19318015/3ed3599c-90a7-11e6-981c-5d3c48154ce1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19318015/3ed3599c-90a7-11e6-981c-5d3c48154ce1.png)
https://cloud.githubusercontent.com/assets/20930745/19318015/3ed3599c-90a7-11e6-981c-5d3c48154ce1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19318027/4e297a0c-90a7-11e6-84a7-8c2534a5756f.png
