### ISSUE TITLE
TCL

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4067]
**App Name:** TCL
**Bundle ID:** fr.tcl.apptcl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=579379606">579379606</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tcl/id579379606?mt=8&uo=4">https://itunes.apple.com/us/app/tcl/id579379606?mt=8&uo=4</a>
**App Version:** 4.4
**Seller:** SM TRANSPORT AGGLOMERATION LYONNAISE
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tcl-sytral/id579379609?uo=4>© TCL SYTRAL</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/aa/9c/4d/aa9c4def-c206-556b-9965-e43f8a7a2231/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19385062/017ee8ec-920d-11e6-89f3-920a21baf6ac.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19385062/017ee8ec-920d-11e6-89f3-920a21baf6ac.png)
https://cloud.githubusercontent.com/assets/20930745/19385062/017ee8ec-920d-11e6-89f3-920a21baf6ac.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19385072/127e20d6-920d-11e6-940b-7ae8a508fc63.png
