### ISSUE TITLE
tori.fi

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#4069]
**App Name:** tori.fi
**Bundle ID:** com.tori.tori
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=505943449">505943449</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/tori.fi/id505943449?mt=8&uo=4">https://itunes.apple.com/se/app/tori.fi/id505943449?mt=8&uo=4</a>
**App Version:** 10.8.3
**Seller:** SCM Suomi Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/artist/tori.fi/id505943452?uo=4>© tori.fi</a>
**Supported Devices:** iPadFourthGen4G, iPhone6Plus, iPadMini4G, iPhone4S, iPad2Wifi, iPadThirdGen, iPhone6, iPodTouchFifthGen, iPadMini, iPhone4, iPad23G, iPadFourthGen, iPhone5s, iPhone5, iPhone5c, iPadThirdGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/c0/28/89/c0288913-188e-2ab7-c8a8-963df3af4c0a/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7461338/cd5b78cc-f2a9-11e4-8d99-9dcfa6a328e2.png)

**Comment by nekholm** [comment]
The app has been updated and has a new icon, anyone feel like making it Glasklart style?

<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/c0/28/89/c0288913-188e-2ab7-c8a8-963df3af4c0a/pr_source.png" width="150" height="150" />

**Comment by dreamnet** [comment]
Had to move the ".fi" to the bottom, else it looks ugly.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7461338/cd5b78cc-f2a9-11e4-8d99-9dcfa6a328e2.png)
https://cloud.githubusercontent.com/assets/2068130/7461338/cd5b78cc-f2a9-11e4-8d99-9dcfa6a328e2.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7461362/eaae7280-f2a9-11e4-8c7f-65828b2baccb.png
