### ISSUE TITLE
Glasses.com

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#4073]
**App Name:** Glasses.com
**Bundle ID:** com.glasses.glassesPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=738159996">738159996</a>
**iTunes URL:** https://itunes.apple.com/us/app/glasses.com-for-iphone/id738159996?mt=8&uo=4
**App Version:** 2.0.2
**Seller:** 1-800 CONTACTS, Inc.
**Supported Devices:** iPhone5c, iPhone5s, iPhone4, iPhone-3GS, iPad23G, iPadMini4G, iPadThirdGen4G, iPadFourthGen, iPadThirdGen, iPhone5, iPad2Wifi, iPadMini, iPhone4S, iPodTouchFifthGen, iPodTouchourthGen, iPadFourthGen4G
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60463017-22182a00-9c4b-11e9-8148-fe9f3bfe3bb7.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60463046-32c8a000-9c4b-11e9-8bdd-233fbd7ee157.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60463046-32c8a000-9c4b-11e9-8bdd-233fbd7ee157.png)
https://user-images.githubusercontent.com/2068130/60463046-32c8a000-9c4b-11e9-8bdd-233fbd7ee157.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60463066-44aa4300-9c4b-11e9-83a1-34a110a34dd0.png
