### ISSUE TITLE
Horoscope Astrocenter

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4074]
**App Name:** Horoscope Astrocenter
**Bundle ID:** com.wengo.astrocenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=513222076">513222076</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/horoscope-astrocenter/id513222076?mt=8&uo=4">https://itunes.apple.com/us/app/horoscope-astrocenter/id513222076?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** wengo
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wengo/id444490090?uo=4>© Wengo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/94/fa/1e/94fa1e92-5e09-65fb-a2ac-891272f11058/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19625227/fec63242-9912-11e6-9814-5ac338624dbf.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19625227/fec63242-9912-11e6-9814-5ac338624dbf.png)
https://cloud.githubusercontent.com/assets/2068130/19625227/fec63242-9912-11e6-9814-5ac338624dbf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19625230/0c20f54e-9913-11e6-97bb-ef5f5e704012.png
