### ISSUE TITLE
Media Markt Deutschland

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4081]
**App Name:** Media Markt Deutschland
**Bundle ID:** de.mediamarkt.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386304604">386304604</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/media-markt-deutschland/id386304604?mt=8&uo=4">https://itunes.apple.com/de/app/media-markt-deutschland/id386304604?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Media Markt E-Business GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/media-markt-e-business-gmbh/id386304607?uo=4>© Media Markt E-Business GmbH</a>
**Supported Devices:** iPadThirdGen4G, iPhone6Plus, iPhone6, iPhone5, iPhone5c, iPodTouchFifthGen, iPhone4, iPad23G, iPadThirdGen, iPadMini, iPad2Wifi, iPadFourthGen, iPhone5s, iPhone4S, iPadMini4G, iPadFourthGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple2/v4/e1/84/e8/e184e8ac-25a1-cb70-f372-a333a36e53e0/mzl.dcdxujae.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7899800/06d7f876-0733-11e5-937e-f53201d96da3.png)

**Comment by Trubbel** [comment]
Icon is updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7899800/06d7f876-0733-11e5-937e-f53201d96da3.png)
https://cloud.githubusercontent.com/assets/10730122/7899800/06d7f876-0733-11e5-937e-f53201d96da3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7899797/f98adbca-0732-11e5-9468-6023e9df378e.png
