### ISSUE TITLE
Cut the Rope 2

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4085]
**App Name:** Cut the Rope 2
**Bundle ID:** com.zeptolab.ctr2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=681814050">681814050</a>
**iTunes URL:** https://itunes.apple.com/us/app/cut-the-rope-2/id681814050?mt=8&uo=4
**App Version:** 1.0.1
**Seller:** ZeptoLab UK Limited
**Supported Devices:** iPadFourthGen, iPhone4, iPad23G, iPhone-3GS, iPadFourthGen4G, iPodTouchFifthGen, iPhone5s, iPadWifi, iPhone4S, iPodTouchThirdGen, iPadThirdGen4G, iPhone5, iPad3G, iPadMini4G, iPad2Wifi, iPadThirdGen, iPhone5c, iPadMini, iPodTouchourthGen
**Original Artwork:**
<img src="http://a1441.phobos.apple.com/us/r30/Purple/v4/32/f5/01/32f501ac-af3c-e6e8-8fde-9c14d4d87f04/mzl.fgxnspry.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16901678/9976bb06-4c4a-11e6-9327-0dd6109ce5e9.png)

**Comment by Anuskuss** [comment]
@dreamnet Could you make the **2** solid and remove the mark on his left foot?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16901678/9976bb06-4c4a-11e6-9327-0dd6109ce5e9.png)
https://cloud.githubusercontent.com/assets/2068130/16901678/9976bb06-4c4a-11e6-9327-0dd6109ce5e9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16901681/a99d0bd4-4c4a-11e6-9292-9380ca94a400.png

**Comment by ivanov007** [comment]
I agree with the number two but the mark on the foot gave him volume, now it look plain

**Comment by Anuskuss** [comment]
@ivanov007 Well I don't like too much 3D on the icons but I think everyone has different preferences.
