### ISSUE TITLE
My Horoscope Free

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4088]
**App Name:** My Horoscope Free
**Bundle ID:** ch.mogo.horonewlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=361728765">361728765</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-horoscope-free/id361728765?mt=8&uo=4">https://itunes.apple.com/us/app/my-horoscope-free/id361728765?mt=8&uo=4</a>
**App Version:** 3.3.7
**Seller:** ID Mobile SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mogo.ch/id300173692?uo=4>© mogo.ch</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/3a/5b/82/3a5b82ae-29f2-bfea-332a-d4071c4eea6f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18841688/cf27880c-8412-11e6-9d17-189c1e23dc2a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18841688/cf27880c-8412-11e6-9d17-189c1e23dc2a.png)
https://cloud.githubusercontent.com/assets/2068130/18841688/cf27880c-8412-11e6-9d17-189c1e23dc2a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18841703/e1a42350-8412-11e6-9d29-89158a5dfb9d.png
