### ISSUE TITLE
jubeat plus

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#4093]
**App Name:** jubeat plus
**Bundle ID:** jp.konami.jubeatplus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395192484">395192484</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/jp/app/jubeat-plus/id395192484?mt=8&uo=4">https://itunes.apple.com/jp/app/jubeat-plus/id395192484?mt=8&uo=4</a>
**App Version:** 3.9.2
**Seller:** Konami Digital Entertainment Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/jp/developer/konami/id299580230?mt=8&uo=4>© KONAMI</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/2b/14/fa/2b14fa26-7f37-b81e-53bc-b2b685fd0b73/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19380723/b8e88e08-91f8-11e6-85ab-2a7a52071695.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19380723/b8e88e08-91f8-11e6-85ab-2a7a52071695.png)
https://cloud.githubusercontent.com/assets/20930745/19380723/b8e88e08-91f8-11e6-85ab-2a7a52071695.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19380739/c8daac38-91f8-11e6-9c7d-8e8265fd8a10.png
