### ISSUE TITLE
書き取り漢字練習

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#4096]
**App Name:** 書き取り漢字練習
**Bundle ID:** jp.co.nowpro.KanjiRensyu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=366952273">366952273</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/jp/app/%E6%9B%B8%E3%81%8D%E5%8F%96%E3%82%8A%E6%BC%A2%E5%AD%97%E7%B7%B4%E7%BF%92/id366952273?mt=8&uo=4">https://itunes.apple.com/jp/app/%E6%9B%B8%E3%81%8D%E5%8F%96%E3%82%8A%E6%BC%A2%E5%AD%97%E7%B7%B4%E7%BF%92/id366952273?mt=8&uo=4</a>
**App Version:** 2.3.6
**Seller:** NOWPRODUCTION CO.,LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/jp/developer/nowproduction-co-ltd/id306269845?uo=4">© NOWPRODUCTION, CO.,LTD</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/9c/07/0a/9c070aa0-1315-748d-c304-d0e0cbc043c5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32387631-5f1a5ae4-c0c5-11e7-81db-0be5968f4846.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32387631-5f1a5ae4-c0c5-11e7-81db-0be5968f4846.png)
https://user-images.githubusercontent.com/2068130/32387631-5f1a5ae4-c0c5-11e7-81db-0be5968f4846.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32387648-6fcc0108-c0c5-11e7-8974-53d50c3ce248.png
