### ISSUE TITLE
beat gather 動画×音楽×音ゲー

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#4097]
**App Name:** beat gather 動画×音楽×音ゲー
**Bundle ID:** jp.konami.beatgather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467027855">467027855</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/jp/app/beat-gather-dong-hua-yin-le/id467027855?mt=8&uo=4">https://itunes.apple.com/jp/app/beat-gather-dong-hua-yin-le/id467027855?mt=8&uo=4</a>
**App Version:** 2.6.0
**Seller:** Konami Digital Entertainment Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/jp/developer/konami/id299580230?mt=8&uo=4>© KONAMI</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/67/79/53/6779538e-369e-87a8-3b45-6faa3cc729e7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13448011/f032b342-e01f-11e5-8006-96c0843ae5b3.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13448011/f032b342-e01f-11e5-8006-96c0843ae5b3.png)
https://cloud.githubusercontent.com/assets/10730122/13448011/f032b342-e01f-11e5-8006-96c0843ae5b3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13448012/f036c50e-e01f-11e5-9a19-29cbee539faa.png
