### ISSUE TITLE
myHomework Student Planner

### ISSUE THREAD

**Issue by AppleLover233** [glasklart/hd#4102]
**App Name:** myHomework Student Planner
**Bundle ID:** com.rigoneri.myhomework
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=303490844">303490844</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myhomework-student-planner/id303490844?mt=8&uo=4">https://itunes.apple.com/us/app/myhomework-student-planner/id303490844?mt=8&uo=4</a>
**App Version:** 6.4.0
**Seller:** Rodrigo Neri
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rodrigo-neri/id303490847?uo=4>© Rodrigo Neri</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/53/3d/dd/533ddd22-3add-143f-3045-467a7f9e2852/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13448434/83ce82d6-e023-11e5-93d8-ed56ece3c1d8.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13448422/6e233da0-e023-11e5-86fc-b0e82b015fb2.png)
https://cloud.githubusercontent.com/assets/10730122/13448422/6e233da0-e023-11e5-86fc-b0e82b015fb2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13448421/6e224544-e023-11e5-8002-e713c677382b.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13448434/83ce82d6-e023-11e5-93d8-ed56ece3c1d8.png)
https://cloud.githubusercontent.com/assets/10730122/13448434/83ce82d6-e023-11e5-93d8-ed56ece3c1d8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13448433/83ce6ec2-e023-11e5-8ede-d53798060044.png
