### ISSUE TITLE
EVENTIM DE

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4122]
**App Name:** EVENTIM DE
**Bundle ID:** de.eventim.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=408601891">408601891</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/eventim-de/id408601891?uo=4">https://apps.apple.com/us/app/eventim-de/id408601891?uo=4</a>
**App Version:** 4.9
**Seller:** CTS EVENTIM AG
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cts-eventim-ag/id355668753?uo=4">© CTS EVENTIM AG</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/7d/eb/f5/7debf5b6-9e61-c238-ce10-0a0dafa93e33/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387654-9d8ca680-9aa6-11e9-99b4-b10dfbadbf04.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387654-9d8ca680-9aa6-11e9-99b4-b10dfbadbf04.png)
https://user-images.githubusercontent.com/20930745/60387654-9d8ca680-9aa6-11e9-99b4-b10dfbadbf04.png

Source:
https://user-images.githubusercontent.com/20930745/60387656-9ebdd380-9aa6-11e9-9b30-0944d8dd1d54.png
