### ISSUE TITLE
NASCAR Mobile

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4127]
**App Name:** NASCAR MOBILE
**Bundle ID:** com.nascar.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=552764013">552764013</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nascar-mobile/id552764013?mt=8&uo=4">https://itunes.apple.com/us/app/nascar-mobile/id552764013?mt=8&uo=4</a>
**App Version:** 5.5.1
**Seller:** NASCAR Digital Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nascar-digital-media-llc/id551680834?uo=4>© NASCAR Digital Media, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/0e/1d/54/0e1d54ab-9812-81d1-7b2d-ef4006f8b9cd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19814161/5d3551ea-9d3d-11e6-9692-0033a5f4d303.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19812699/edb289ba-9d36-11e6-8750-340849d7d523.png)
https://cloud.githubusercontent.com/assets/20930745/19812699/edb289ba-9d36-11e6-8750-340849d7d523.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19812749/1c19087e-9d37-11e6-9251-f442115ce637.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Ummm... what about inverting?
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19814161/5d3551ea-9d3d-11e6-9692-0033a5f4d303.png)
https://cloud.githubusercontent.com/assets/2068130/19814161/5d3551ea-9d3d-11e6-9692-0033a5f4d303.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19814192/7d1738ca-9d3d-11e6-8372-0c4e02a3bec7.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... yes, it's also possible ... I oriented me to the previous icon

**Comment by dreamnet** [comment]
@2Qt2beStr8 Hm, OK. What version do you like more?

**Comment by 2Qt2beStr8** [comment]
... i think your icon looks better ...
