### ISSUE TITLE
Gamekult Jeux Vidéo

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4129]
**App Name:** Gamekult Jeux Vidéo
**Bundle ID:** com.gamekult.gamekult
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380268743">380268743</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gamekult-jeux-video/id380268743?mt=8&uo=4">https://itunes.apple.com/us/app/gamekult-jeux-video/id380268743?mt=8&uo=4</a>
**App Version:** 3.4.2
**Seller:** CUP Interactive
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cup-interactive/id350775136?uo=4>© CUP Interactive</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/08/9c/7e/089c7ebb-6ffd-d5dd-77cd-cad07637a042/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19239753/cb538d0c-8f07-11e6-8859-59d6a5ba85ea.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19239753/cb538d0c-8f07-11e6-8859-59d6a5ba85ea.png)
https://cloud.githubusercontent.com/assets/20930745/19239753/cb538d0c-8f07-11e6-8859-59d6a5ba85ea.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19239771/dca04370-8f07-11e6-804a-c56ddec8003f.png
