### ISSUE TITLE
MBA, Musée des Beaux-Arts de Lyon, official application

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4130]
**App Name:** MBA, Musée des Beaux-Arts de Lyon, official application
**Bundle ID:** com.myluckyday.mba
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=433645173">433645173</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mba-musee-des-beaux-arts-lyon/id433645173?mt=8&uo=4">https://itunes.apple.com/us/app/mba-musee-des-beaux-arts-lyon/id433645173?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** MY LUCKY DAY
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/my-lucky-day/id366064712?uo=4>© MY LUCKY DAY</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/a7/6a/0a/a76a0a44-ff90-0f84-dce2-a6c0e40d81be/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19242995/0649114e-8f16-11e6-8756-050d1df7e61f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19242995/0649114e-8f16-11e6-8756-050d1df7e61f.png)
https://cloud.githubusercontent.com/assets/20930745/19242995/0649114e-8f16-11e6-8756-050d1df7e61f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19243010/1913fbae-8f16-11e6-9cbe-296aa554c05c.png
