### ISSUE TITLE
Grains de Sel

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4131]
**App Name:** Grains de Sel
**Bundle ID:** com.bipmee.grainsdesel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=358778560">358778560</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grains-de-sel/id358778560?mt=8&uo=4">https://itunes.apple.com/us/app/grains-de-sel/id358778560?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** MY LUCKY DAY
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/my-lucky-day/id366064712?uo=4>© MY LUCKY DAY</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/60/82/da/6082da31-76b2-496f-63b3-0c73801dce40/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222821/6b9793b4-8e61-11e6-8990-029a73160163.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222821/6b9793b4-8e61-11e6-8990-029a73160163.png)
https://cloud.githubusercontent.com/assets/2068130/19222821/6b9793b4-8e61-11e6-8990-029a73160163.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19222823/79a47af8-8e61-11e6-939c-4351e8803d80.png
