### ISSUE TITLE
Quote of the Day: Share Inspirational Quotes Daily

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4134]
**App Name:** Quote of the Day: Share Inspirational Quotes Daily
**Bundle ID:** com.bluepandaapps.quoteoftheday
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=622629806">622629806</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quote-day-share-inspirational/id622629806?mt=8&uo=4">https://itunes.apple.com/us/app/quote-day-share-inspirational/id622629806?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Blue Panda Apps Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/blue-panda-apps-limited/id569904138?uo=4>© Blue Panda Apps Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/f5/e5/22/f5e5226e-017b-c914-100b-f54c3b969792/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222844/11206310-8e62-11e6-85aa-29c0712ea080.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222844/11206310-8e62-11e6-85aa-29c0712ea080.png)
https://cloud.githubusercontent.com/assets/2068130/19222844/11206310-8e62-11e6-85aa-29c0712ea080.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19222846/1f2363ea-8e62-11e6-82ff-85b8d6ef06d4.png
