### ISSUE TITLE
Oxford French Dictionary

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4136]
**App Name:** Oxford French Dictionary
**Bundle ID:** com.mobisystems.OxfordFrench3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=679624485">679624485</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/oxford-french-dictionary/id679624485?mt=8&uo=4">https://itunes.apple.com/us/app/oxford-french-dictionary/id679624485?mt=8&uo=4</a>
**App Version:** 10.0.5
**Seller:** MobiSystems, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mobisystems-inc/id289579214?uo=4">© MobiSystems, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/62/d5/a2/62d5a248-60d5-3d18-6035-a0b0b0939ad6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468915-812fbfc4-0329-11e8-907e-a888bca2a9a7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468915-812fbfc4-0329-11e8-907e-a888bca2a9a7.png)
https://user-images.githubusercontent.com/2068130/35468915-812fbfc4-0329-11e8-907e-a888bca2a9a7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/35468919-90648e8e-0329-11e8-85dd-55ded5f3421f.png
