### ISSUE TITLE
EDF & MOI

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4137]
**App Name:** EDF & MOI
**Bundle ID:** com.EDF.EdfetMoi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=563799142">563799142</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/edf-moi/id563799142?mt=8&uo=4">https://itunes.apple.com/de/app/edf-moi/id563799142?mt=8&uo=4</a>
**App Version:** 6.1.2
**Seller:** EDF
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/edf/id401110261?uo=4>© EDF</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/a7/32/29/a73229fb-dab7-aa33-ee7f-02b883a077f2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18841498/43cac97c-8412-11e6-9946-b2d34c0072fb.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18841498/43cac97c-8412-11e6-9946-b2d34c0072fb.png)
https://cloud.githubusercontent.com/assets/2068130/18841498/43cac97c-8412-11e6-9946-b2d34c0072fb.pnghttps://cloud.githubusercontent.com/assets/2068130/18841498/43cac97c-8412-11e6-9946-b2d34c0072fb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18841517/560a4c02-8412-11e6-8737-272367f861db.png
