### ISSUE TITLE
Horoscope gratuit du jour

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4139]
**App Name:** Horoscope gratuit du jour
**Bundle ID:** com.alienweb.horoscope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=496505035">496505035</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/horoscope-gratuit-du-jour/id496505035?mt=8&uo=4">https://itunes.apple.com/us/app/horoscope-gratuit-du-jour/id496505035?mt=8&uo=4</a>
**App Version:** 2
**Seller:** alienweb
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alienweb/id456217194?uo=4">© alienweb</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/60/93/aa/6093aafd-74aa-750b-4c59-bd255ca462bb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20465842/6cd764d0-af67-11e6-9f0f-d1934422dc3f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20465842/6cd764d0-af67-11e6-9f0f-d1934422dc3f.png)
https://cloud.githubusercontent.com/assets/20930745/20465842/6cd764d0-af67-11e6-9f0f-d1934422dc3f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20465860/b324f628-af67-11e6-9eb4-3842cd548672.png
