### ISSUE TITLE
Free Horoscope ®

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4140]
**App Name:** Free Horoscope ®
**Bundle ID:** com.mon-horoscope-du-jour.horoscope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=323235598">323235598</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/free-horoscope/id323235598?mt=8&uo=4">https://itunes.apple.com/us/app/free-horoscope/id323235598?mt=8&uo=4</a>
**App Version:** 6.8.1
**Seller:** SF Factory
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sf-factory/id323235601?uo=4>© SF Factory</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/e1/94/cf/e194cfd3-03cc-5ad7-299b-6b83d60c0e26/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19239362/f6f40862-8f05-11e6-8a15-f3fffd974c91.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19239362/f6f40862-8f05-11e6-8a15-f3fffd974c91.png)
https://cloud.githubusercontent.com/assets/20930745/19239362/f6f40862-8f05-11e6-8a15-f3fffd974c91.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19239376/05cfd046-8f06-11e6-9e24-db758b899662.png
