### ISSUE TITLE
Cash App

### ISSUE THREAD

**Issue by kylebshr** [glasklart/hd#4145]
**App Name:** Cash App
**Bundle ID:** com.squareup.cash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=711923939">711923939</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cash-app/id711923939?uo=4">https://apps.apple.com/us/app/cash-app/id711923939?uo=4</a>
**App Version:** 2.52.1
**Seller:** Square, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/square-inc/id335393791?uo=4">© Square, Inc.</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/b7/b8/d1/b7b8d192-0f40-83e8-ad17-dfc5b947423c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60372307-885b3d80-99fc-11e9-81f2-7e5de632bf84.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60372307-885b3d80-99fc-11e9-81f2-7e5de632bf84.png)
https://user-images.githubusercontent.com/20930745/60372307-885b3d80-99fc-11e9-81f2-7e5de632bf84.png

Source:
https://user-images.githubusercontent.com/20930745/60372310-8abd9780-99fc-11e9-8cde-a03abd58ccbd.png
