### ISSUE TITLE
GBA4iOS

### ISSUE THREAD

**Issue by kylebshr** [glasklart/hd#4150]
**App Name:** GBA4iOS
 **Bundle ID:** com.rileytestut.GBA4iOS
 **Version:** 2.1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/3090247/10578286/d20d5938-7636-11e5-87ab-6d905fe0bb84.png" width="150" height="150" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/10578045/97cd10f4-763d-11e5-87e3-530c1a468896.png)

**Comment by zmathiasz** [comment]
@dreamnet Updated BundleID:

 **App Name:** GBA4iOS
 **Bundle ID:** com.rileytestut.GBA4iOS
 **Version:** 2.1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://camo.githubusercontent.com/5155d96d883b2e757fcba7f256714653ff41caea/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333532363738332f323530303235372f63373163343738362d623336302d313165332d386238612d6263383366393736323639372e706e67" width="150" height="150" />
 **Accepted Artwork:**
 \#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by zmathiasz** [comment]
Updated Icon and Source:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/10578045/97cd10f4-763d-11e5-87e3-530c1a468896.png)
https://cloud.githubusercontent.com/assets/10950389/10578045/97cd10f4-763d-11e5-87e3-530c1a468896.png

Source:
https://cloud.githubusercontent.com/assets/10950389/10578051/a1118a96-763d-11e5-8abc-abbb2ff2a014.png

**Comment by dreamnet** [comment]
@ivanov007 What was the old Bundle ID? - I need it else I can't update the icon....

**Comment by Anuskuss** [comment]
Since you updated the BundleID, my copy of GBA4IOS doesn't get themed anymore. My BundleID is **com.rileytestut.enterprise.GBA4IOS**

I don't know if there was a need for a new BundleID, but you could create a symlink to cover both ID's.

**Comment by dreamnet** [comment]
Don't know how to label this, so I use the `nees-renaming` label. :wink:

**Comment by Anuskuss** [comment]
Come on guys, make a hard link already :smile:

**Comment by Anuskuss** [comment]
Small mistake by myself, delete `com.rileytestut.enterprise.GBA4IOS` and add `com.rileytestut.enterprise.GBA4iOS`.

Also, why don't you create a symlink?

**Comment by dreamnet** [comment]
@Anuskuss Symlinks are good, because they can save some space, but they can also be very confusing  when handling thousands of files....

**Comment by Anuskuss** [comment]
Where is my renaming :laughing: 
`com.rileytestut.enterprise.GBA4iOS`

**Comment by dreamnet** [comment]
I'm perfectly confused about this... this issue is for `com.rileytestut.GBA4iOS`. If we need to keep `com.rileytestut.GBA4iOS` then please, @Anuskuss open a new issue for `com.rileytestut.enterprise.GBA4iOS`.
