### ISSUE TITLE
Perk TV - Get Rewards for Watching Videos

### ISSUE THREAD

**Issue by kylebshr** [glasklart/hd#4152]
**App Name:** Perk TV - Get Rewards for Watching Videos
**Bundle ID:** com.jutera.perktv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=706630901">706630901</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/perk-tv-get-rewards-for-watching/id706630901?mt=8&uo=4">https://itunes.apple.com/us/app/perk-tv-get-rewards-for-watching/id706630901?mt=8&uo=4</a>
**App Version:** 4.0.5
**Seller:** Jutera Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jutera/id350411562?uo=4>© Jutera</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/81/19/9a/81199a4c-b039-df0e-5ab9-76dd6aa26c5a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19812214/f0c0be58-9d34-11e6-96ef-71603d96db04.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19812214/f0c0be58-9d34-11e6-96ef-71603d96db04.png)
https://cloud.githubusercontent.com/assets/20930745/19812214/f0c0be58-9d34-11e6-96ef-71603d96db04.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19812313/54610cec-9d35-11e6-9aa7-ba3a7b317c86.png
