### ISSUE TITLE
Соционика

### ISSUE THREAD

**Issue by echominor** [glasklart/hd#416]
**App Name:** Соционика
**Bundle ID:** Socio1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=533393257">533393257</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/socionika/id533393257?mt=8&uo=4">https://itunes.apple.com/us/app/socionika/id533393257?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Evgeniy Ostrovskiy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/evgeniy-ostrovskiy/id493908258?uo=4">© Evgeniy Ostrovskiy</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/59/0e/a0/590ea0e0-7365-d0a8-825c-7e450033066d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20216553/a18d8a72-a81b-11e6-9124-519391cfbc98.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20216553/a18d8a72-a81b-11e6-9124-519391cfbc98.png)
https://cloud.githubusercontent.com/assets/20930745/20216553/a18d8a72-a81b-11e6-9124-519391cfbc98.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20216578/b9432e92-a81b-11e6-8f61-4f3006f02626.png
