### ISSUE TITLE
PlainText 2

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#4161]
**App Name:** PlainText 2
**Bundle ID:** com.433labs.PlainText
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=769101727">769101727</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/plaintext-2/id769101727?mt=8&uo=4">https://itunes.apple.com/us/app/plaintext-2/id769101727?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Jonathan Jordan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/433-labs/id423129678?uo=4>© 433 Labs</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/6e/ca/a4/6ecaa4ad-9d70-b50c-17c3-5a4446af6fd7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222655/33c3a1b0-8e5e-11e6-9789-d0e28879c9e3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222655/33c3a1b0-8e5e-11e6-9789-d0e28879c9e3.png)
https://cloud.githubusercontent.com/assets/2068130/19222655/33c3a1b0-8e5e-11e6-9789-d0e28879c9e3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19222659/410c5664-8e5e-11e6-89e6-8160dbcb98a7.png

**Comment by 2Qt2beStr8** [comment]
.... @dreamnet ... only a question .. have you made it thicker?
if i create this icon it look like this:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19222716/53fb8b68-8e5f-11e6-8436-20368a7e8ff0.png)

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes, I did. I used the Arial font for this, because the source is very blurry.

**Comment by 2Qt2beStr8** [comment]
... ah ok ... i understand ... it should not be criticism .. I just want to get better and learn more and more
