### ISSUE TITLE
Twitterrific: Tweet Your Way

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4169]
**App Name:** Twitterrific: Tweet Your Way
**Bundle ID:** com.iconfactory.Blackbird
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=580311103">580311103</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/twitterrific-tweet-your-way/id580311103?uo=4">https://apps.apple.com/us/app/twitterrific-tweet-your-way/id580311103?uo=4</a>
**App Version:** 6.1.6
**Seller:** The Iconfactory
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-iconfactory/id281795483?uo=4">© The Iconfactory</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/d7/a8/7e/d7a87e0b-ce0a-e02f-7c4d-9c9a55f91b5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84714845-2a0dce80-af6f-11ea-8469-f0a6dc07b3dc.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Twitterrific: Tweet Your Way
**Bundle ID:** com.iconfactory.Blackbird
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=580311103">580311103</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/twitterrific-tweet-your-way/id580311103?uo=4">https://apps.apple.com/us/app/twitterrific-tweet-your-way/id580311103?uo=4</a>
**App Version:** 6.1.6
**Seller:** The Iconfactory
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-iconfactory/id281795483?uo=4">© The Iconfactory</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/d7/a8/7e/d7a87e0b-ce0a-e02f-7c4d-9c9a55f91b5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84714845-2a0dce80-af6f-11ea-8469-f0a6dc07b3dc.png)
https://user-images.githubusercontent.com/2068130/84714845-2a0dce80-af6f-11ea-8469-f0a6dc07b3dc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84714877-385bea80-af6f-11ea-9ccf-5aba85108d9e.png
