### ISSUE TITLE
Mercury Browser Pro - The best web browser for iOS

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4172]
**App Name:** Mercury Browser Pro - The best web browser for iOS
**Bundle ID:** com.ilegendsoft.MBrowserPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348701575">348701575</a>
**iTunes URL:** https://itunes.apple.com/us/app/mercury-browser-pro-best-web/id348701575?mt=8&uo=4
**App Version:** 8.4.1
**Seller:** iLegendSoft Inc
**Supported Devices:** iPodTouchourthGen, iPhone4S, iPadThirdGen4G, iPhone5c, iPad2Wifi, iPad23G, iPadThirdGen, iPodTouchFifthGen, iPhone5, iPadMini, iPhone-3GS, iPadFourthGen, iPadMini4G, iPadFourthGen4G, iPhone5s, iPhone4
**Original Artwork:**
<img src="http://a695.phobos.apple.com/us/r30/Purple/v4/f4/a3/0f/f4a30fb0-9425-aaf6-638d-80ffe1e2ca38/mzl.xsbxkoul.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/3134868/1304e60e-e82b-11e3-93fd-b0b86297040f.png)

**Comment by l8er4now** [comment]
The current app in this post has been discontinued and replaced with the below. Icon is the same, buddle id has changed.

**App Name:** Mercury Web Browser Pro - with powerful Ad Block extension
**Bundle ID:** com.bsn.mercurypro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1000610117">1000610117</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mercury-web-browser-pro-powerful/id1000610117?mt=8&uo=4">https://itunes.apple.com/us/app/mercury-web-browser-pro-powerful/id1000610117?mt=8&uo=4</a>
**App Version:** 10.0.1
**Seller:** Lucy Ding
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lucy-ding/id999772834?uo=4>© Lucy Ding</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/5c/f8/be/5cf8be1b-3b8f-57bc-1914-983b0647025a/mzl.yzgdkmjb.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
I'm opening a new one since the itunes ID is also different
