### ISSUE TITLE
Sleep Cycle alarm clock

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#418]
**App Name:** Sleep Cycle alarm clock
**Bundle ID:** com.lexwarelabs.goodmorning
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=320606217">320606217</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sleep-cycle-alarm-clock/id320606217?mt=8&uo=4">https://itunes.apple.com/us/app/sleep-cycle-alarm-clock/id320606217?mt=8&uo=4</a>
**App Version:** 4.8.1
**Seller:** Northcube AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/northcube-ab/id320606220?uo=4>© Northcube AB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/09/1e/7f/091e7f4a-9105-f973-3eba-a6b2f6c96379/mzl.xhasmotr.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10789031/5cfd04e4-7d7b-11e5-999e-c20cff71fc06.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10789031/5cfd04e4-7d7b-11e5-999e-c20cff71fc06.png)
https://cloud.githubusercontent.com/assets/10730122/10789031/5cfd04e4-7d7b-11e5-999e-c20cff71fc06.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10789027/593ddb94-7d7b-11e5-894c-a5c07a2e1bf8.png
