### ISSUE TITLE
idealo - Price Comparison

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#419]
**App Name:** idealo - Price Comparison
**Bundle ID:** de.idealo.Idealo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454415640">454415640</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/idealo-price-comparison/id454415640?uo=4">https://apps.apple.com/us/app/idealo-price-comparison/id454415640?uo=4</a>
**App Version:** 13.3.0
**Seller:** idealo internet GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/idealo-internet-gmbh/id454415644?uo=4">© idealo internet GmbH</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/7b/7a/f4/7b7af4b2-24fb-bff3-a7a0-4d53171e5001/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62399729-1aff7700-b57d-11e9-8cd9-5c45b57c16de.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417093/e5927908-93a3-11e6-9429-85549230300e.png)
https://cloud.githubusercontent.com/assets/20930745/19417093/e5927908-93a3-11e6-9429-85549230300e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19417095/0459b7de-93a4-11e6-9cfd-4e29a0fe77e1.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62399729-1aff7700-b57d-11e9-8cd9-5c45b57c16de.png)
https://user-images.githubusercontent.com/2068130/62399729-1aff7700-b57d-11e9-8cd9-5c45b57c16de.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62399747-2a7ec000-b57d-11e9-8973-11f0c9cb1f7a.png
