### ISSUE TITLE
Bloglovin’ – The best app to discover and read blogs.

### ISSUE THREAD

**Issue by ookkerpak** [glasklart/hd#4190]
**App Name:** Bloglovin’ – The best app to discover and read blogs.
**Bundle ID:** se.flavourofthemonth.bloglovin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=421818340">421818340</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bloglovin-best-app-to-discover/id421818340?mt=8&uo=4">https://itunes.apple.com/us/app/bloglovin-best-app-to-discover/id421818340?mt=8&uo=4</a>
**App Version:** 3.7
**Seller:** Bloglovin AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bloglovin-ab/id421818343?uo=4>© Bloglovin AB</a>
**Supported Devices:** iPad23G, iPadThirdGen, iPhone5, iPad2Wifi, iPadThirdGen4G, iPodTouchFifthGen, iPadFourthGen, iPhone6, iPhone5s, iPadMini, iPadFourthGen4G, iPadMini4G, iPodTouchSixthGen, iPhone4, iPhone6Plus, iPhone5c, iPhone4S
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/bb/07/3b/bb073ba7-228a-2862-51f7-7d94ed4845c8/mzl.otnoeqkf.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9573224/05d5750a-4fba-11e5-87b7-560694bce63d.png)

**Comment by Trubbel** [comment]
The icon has been updated.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9573224/05d5750a-4fba-11e5-87b7-560694bce63d.png)
https://cloud.githubusercontent.com/assets/2068130/9573224/05d5750a-4fba-11e5-87b7-560694bce63d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9573232/13d3ed9e-4fba-11e5-848e-6aa05be1ae8f.png
