### ISSUE TITLE
F-Secure KEY Password manager

### ISSUE THREAD

**Issue by ookkerpak** [glasklart/hd#4194]
**App Name:** F-Secure KEY Password manager
**Bundle ID:** com.f-secure.dc.key
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=627417660">627417660</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/f-secure-key-password-manager/id627417660?uo=4">https://apps.apple.com/us/app/f-secure-key-password-manager/id627417660?uo=4</a>
**App Version:** 4.9.2
**Seller:** F-Secure Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/f-secure-corporation/id425351654?uo=4">© F-Secure Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/68/fc/c5/68fcc5f0-8059-864a-25e8-24fffcb5fd02/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60392856-3570ab80-9b0c-11e9-8c6a-02f0d637dac9.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60392856-3570ab80-9b0c-11e9-8c6a-02f0d637dac9.png)
https://user-images.githubusercontent.com/20930745/60392856-3570ab80-9b0c-11e9-8c6a-02f0d637dac9.png

Source
https://user-images.githubusercontent.com/20930745/60392857-37d30580-9b0c-11e9-98ff-24e52f80106d.png
