### ISSUE TITLE
Namecheap

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#42]
**App Name:** Namecheap
**Bundle ID:** com.namecheap.iosapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=482604032">482604032</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/namecheap/id482604032?mt=8&uo=4">https://itunes.apple.com/us/app/namecheap/id482604032?mt=8&uo=4</a>
**App Version:** 3.8.1
**Seller:** Namecheap, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/namecheap-inc/id482604035?uo=4">© Namecheap, Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/35/46/00/3546000c-0ac2-85ad-1827-c94a4f6af430/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32693192-f6b85ea2-c726-11e7-9596-448095da88a0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32693192-f6b85ea2-c726-11e7-9596-448095da88a0.png)
https://user-images.githubusercontent.com/2068130/32693192-f6b85ea2-c726-11e7-9596-448095da88a0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32693196-066720b8-c727-11e7-96de-f28c601cd0c5.png
