### ISSUE TITLE
Swedbank private

### ISSUE THREAD

**Issue by Mirthel** [glasklart/hd#420]
**App Name:** Swedbank private
**Bundle ID:** se.swedbank.iphonebanken
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=344161302">344161302</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swedbank-private/id344161302?mt=8&uo=4">https://itunes.apple.com/us/app/swedbank-private/id344161302?mt=8&uo=4</a>
**App Version:** 5.4.0
**Seller:** Swedbank AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/swedbank-ab-publ/id344161306?uo=4">© Swedbank AB (publ)</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/34/71/0a/34710a31-141d-54d6-e70d-0cfb5f6b01e9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32371551-9c084eb8-c091-11e7-8bf0-7e61f620d829.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32371551-9c084eb8-c091-11e7-8bf0-7e61f620d829.png)
https://user-images.githubusercontent.com/2068130/32371551-9c084eb8-c091-11e7-8bf0-7e61f620d829.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32371567-a0f53bc0-c091-11e7-8189-ec2683a5a6d3.png
