### ISSUE TITLE
MocaDeco - Visual Creator

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#4201]
**App Name:** MocaDeco - Visual Creator
**Bundle ID:** com.mocalab.mocadeco
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834163162">834163162</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mocadeco-visual-creator/id834163162?mt=8&uo=4">https://itunes.apple.com/us/app/mocadeco-visual-creator/id834163162?mt=8&uo=4</a>
**App Version:** 1.62
**Seller:** Seohyeon Lee
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/seohyeon-lee/id834163166?uo=4>© Seohyeon Lee</a>
**Supported Devices:** iPhone4S, iPhone5, iPadMini4G, iPadMini, iPodTouchSixthGen, iPadFourthGen4G, iPhone5s, iPad2Wifi, iPhone5c, iPhone6Plus, iPadThirdGen, iPadFourthGen, iPad23G, iPadThirdGen4G, iPodTouchFifthGen, iPhone6
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/6a/fd/54/6afd5484-5b21-84b0-f744-239cecfe166c/mzl.cilkstgr.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9570386/66a2a608-4f8a-11e5-8dc0-b695e3bcd2e3.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9570381/460b9b48-4f8a-11e5-95e1-0092b9afb14e.png)
https://cloud.githubusercontent.com/assets/10730122/9570381/460b9b48-4f8a-11e5-95e1-0092b9afb14e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9570380/42c2d1cc-4f8a-11e5-8420-9a0b39d03860.png

**Comment by Trubbel** [comment]
Alternate,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9570386/66a2a608-4f8a-11e5-8dc0-b695e3bcd2e3.png)
https://cloud.githubusercontent.com/assets/10730122/9570386/66a2a608-4f8a-11e5-8dc0-b695e3bcd2e3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9570385/63702ff0-4f8a-11e5-9dca-f6b180cf8b61.png

**Comment by dreamnet** [comment]
@Trubbel Taking the alternate. :+1:
