### ISSUE TITLE
Two Dots

### ISSUE THREAD

**Issue by GaHub** [glasklart/hd#4231]
**App Name:** Two Dots
**Bundle ID:** com.weplaydots.twodots
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=880178264">880178264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/two-dots/id880178264?mt=8&uo=4">https://itunes.apple.com/us/app/two-dots/id880178264?mt=8&uo=4</a>
**App Version:** 1.10.1
**Seller:** Playdots, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/playdots-inc./id948362568?uo=4>© Playdots, Inc.</a>
**Supported Devices:** iPadMini, iPadFourthGen, iPad23G, iPhone6Plus, iPhone5c, iPad2Wifi, iPhone6, iPadMini4G, iPhone5s, iPadThirdGen, iPhone5, iPadFourthGen4G, iPodTouchSixthGen, iPhone4, iPadThirdGen4G, iPodTouchFifthGen, iPhone4S
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/10/53/e8/1053e824-7441-4f07-79b1-31871925c163/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8893144/9327a524-3384-11e5-88fd-7231c0e169f3.png)

**Comment by LaCh0uine** [comment]
Icon need to be updated

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8891248/7f10861c-3322-11e5-8a1c-86b2caf45419.png)
https://cloud.githubusercontent.com/assets/2068130/8891248/7f10861c-3322-11e5-8a1c-86b2caf45419.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8891252/9097e9de-3322-11e5-8d74-aa9a5506321c.png

**Comment by LaCh0uine** [comment]
I find look strange :/

**Comment by dreamnet** [comment]
@LaCh0uine Me too... Maybe someone will make a better one.

**Comment by dreamnet** [comment]
Is this better? :
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8893144/9327a524-3384-11e5-88fd-7231c0e169f3.png)
https://cloud.githubusercontent.com/assets/2068130/8893144/9327a524-3384-11e5-88fd-7231c0e169f3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8893146/a2cc2c20-3384-11e5-87ef-2552cbd65f91.png

**Comment by LaCh0uine** [comment]
I think yes :)

**Comment by dreamnet** [comment]
@LaCh0uine OK, I take it.
