### ISSUE TITLE
Nyan Cat!

### ISSUE THREAD

**Issue by Bonfi97** [glasklart/hd#4243]
**App Name:** Nyan Cat!
**Bundle ID:** com.ante.nyancat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432805198">432805198</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nyan-cat/id432805198?mt=8&uo=4">https://itunes.apple.com/us/app/nyan-cat/id432805198?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Marc Ellis
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marc-ellis/id408415544?uo=4">© Marc Ellis</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/36/55/26/36552610-9e25-91f4-2a26-18dbb59567bf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23178552/26d88cb4-f86b-11e6-8d89-d6066731155c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23178552/26d88cb4-f86b-11e6-8d89-d6066731155c.png)
https://cloud.githubusercontent.com/assets/2068130/23178552/26d88cb4-f86b-11e6-8d89-d6066731155c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23178565/36c4d934-f86b-11e6-8947-f78950048831.png
