### ISSUE TITLE
Clever Lotto & EuroJackpot

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4253]
**App Name:** Clever Lotto & EuroJackpot
**Bundle ID:** lotto6aus49
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390946943">390946943</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/clever-lotto-eurojackpot/id390946943?uo=4">https://apps.apple.com/de/app/clever-lotto-eurojackpot/id390946943?uo=4</a>
**App Version:** 5.4.6
**Seller:** Formigas GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/formigas-gmbh/id668613926?uo=4">© Formigas GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/08/64/a7/0864a772-e548-5d4b-01c8-68d1f91b76d0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60371139-a1fa8600-99f8-11e9-9727-fbae4b333e87.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60371139-a1fa8600-99f8-11e9-9727-fbae4b333e87.png)
https://user-images.githubusercontent.com/2068130/60371139-a1fa8600-99f8-11e9-9727-fbae4b333e87.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60371156-b2126580-99f8-11e9-800a-96e828f9419e.png
