### ISSUE TITLE
Forza Football - Soccer live scores, highlights

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#426]
**App Name:** Forza Football - Soccer live scores, highlights
**Bundle ID:** com.footballaddicts.livescoreaddicts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=500138120">500138120</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/forza-football-soccer-live/id500138120?mt=8&uo=4">https://itunes.apple.com/us/app/forza-football-soccer-live/id500138120?mt=8&uo=4</a>
**App Version:** 3.8.3
**Seller:** FootballAddicts AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/footballaddicts/id500138123?uo=4>© FootballAddicts</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/c1/24/fe/c124fe9c-84a2-66f6-dcf8-9a790be540fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19715127/651826bc-9b53-11e6-80f5-e70517629d98.png)

**Comment by Anonyymikko** [comment]
Icon needs an update

**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/c1/24/fe/c124fe9c-84a2-66f6-dcf8-9a790be540fc/source/1024x1024bb.png" width="180" height="180" />

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19684002/35c4f51e-9ab5-11e6-89b4-005d100806bb.png)
https://cloud.githubusercontent.com/assets/20930745/19684002/35c4f51e-9ab5-11e6-89b4-005d100806bb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19684041/66531e04-9ab5-11e6-83df-d564f6d7b86a.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19715127/651826bc-9b53-11e6-80f5-e70517629d98.png)
https://cloud.githubusercontent.com/assets/2068130/19715127/651826bc-9b53-11e6-80f5-e70517629d98.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19715141/7503bc26-9b53-11e6-929d-142597e00be7.png
❓
