### ISSUE TITLE
Scanbot 6 - PDF Document & QR-Code Scanner

### ISSUE THREAD

**Issue by Romeo0119** [glasklart/hd#4261]
**App Name:** Scanbot 6 - PDF Document & QR-Code Scanner
**Bundle ID:** net.doo.scanbot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834854351">834854351</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scanbot-6-pdf-document-qr/id834854351?mt=8&uo=4">https://itunes.apple.com/us/app/scanbot-6-pdf-document-qr/id834854351?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** doo GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/doo-gmbh/id454738556?uo=4>© doo GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/2f/5c/a9/2f5ca90e-d676-5016-0867-21b9c072e923/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19620817/fcf2e1e2-9884-11e6-8205-7d1d3c1ec3e0.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Scanbot 6 - PDF Document & QR-Code Scanner
**Bundle ID:** net.doo.scanbot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834854351">834854351</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scanbot-6-pdf-document-qr/id834854351?mt=8&uo=4">https://itunes.apple.com/us/app/scanbot-6-pdf-document-qr/id834854351?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** doo GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/doo-gmbh/id454738556?uo=4>© doo GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/2f/5c/a9/2f5ca90e-d676-5016-0867-21b9c072e923/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19620817/fcf2e1e2-9884-11e6-8205-7d1d3c1ec3e0.png)
https://cloud.githubusercontent.com/assets/2068130/19620817/fcf2e1e2-9884-11e6-8205-7d1d3c1ec3e0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19620819/0b091436-9885-11e6-89fc-6553ebe89d7e.png
