### ISSUE TITLE
Maps+

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#427]
**App Name:** Maps+
**Bundle ID:** com.ize.mapsplus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416753449">416753449</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/maps+/id416753449?mt=8&uo=4">https://itunes.apple.com/us/app/maps+/id416753449?mt=8&uo=4</a>
**App Version:** 2.0.4
**Seller:** IZE, Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ize-ltd./id323114550?uo=4>© IZE, Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple30/v4/ec/fc/a0/ecfca09c-cb66-250c-0583-9c04a3efcc9f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18256607/d1c9c1d0-73b7-11e6-98d1-56b7eefdbc4a.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Maps+
**Bundle ID:** com.ize.mapsplus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416753449">416753449</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/maps+/id416753449?mt=8&uo=4">https://itunes.apple.com/us/app/maps+/id416753449?mt=8&uo=4</a>
**App Version:** 2.0.4
**Seller:** IZE, Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ize-ltd./id323114550?uo=4>© IZE, Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple30/v4/ec/fc/a0/ecfca09c-cb66-250c-0583-9c04a3efcc9f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18254960/e9ed3814-73a3-11e6-888b-fd71f759caf5.png)
https://cloud.githubusercontent.com/assets/20930745/18254960/e9ed3814-73a3-11e6-888b-fd71f759caf5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18254968/01134876-73a4-11e6-9eae-ea07db8f7253.png
