### ISSUE TITLE
Love Live! School idol festival

### ISSUE THREAD

**Issue by taigaak** [glasklart/hd#4287]
**App Name:** Love Live! School idol festival
**Bundle ID:** jp.klab.lovelive-en
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834030294">834030294</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/love-live!-school-idol-festival/id834030294?mt=8&uo=4">https://itunes.apple.com/us/app/love-live!-school-idol-festival/id834030294?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** KLab Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/klab-inc./id302647750?uo=4">© KLab Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/f4/86/2b/f4862b4d-a377-c5ed-4ca6-95e270444eef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22971990/094d0a00-f378-11e6-9de5-df24c65dbe5f.png)

**Comment by dengler9** [comment]
## **This needs an update**

**App Name:** Love Live! School idol festival
**Bundle ID:** jp.klab.lovelive-en
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834030294">834030294</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/love-live!-school-idol-festival/id834030294?mt=8&uo=4">https://itunes.apple.com/us/app/love-live!-school-idol-festival/id834030294?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** KLab Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/klab-inc./id302647750?uo=4">© KLab Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/f4/86/2b/f4862b4d-a377-c5ed-4ca6-95e270444eef/source/1024x1024bb.png" width="180" height="180" />

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22971990/094d0a00-f378-11e6-9de5-df24c65dbe5f.png)
https://cloud.githubusercontent.com/assets/2068130/22971990/094d0a00-f378-11e6-9de5-df24c65dbe5f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22972003/179c68f8-f378-11e6-8a28-22478abde818.png
