### ISSUE TITLE
My M1

### ISSUE THREAD

**Issue by taigaak** [glasklart/hd#4288]
**App Name:** My M1
**Bundle ID:** sg.com.m1.mym1usagetracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380634275">380634275</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-m1/id380634275?mt=8&uo=4">https://itunes.apple.com/us/app/my-m1/id380634275?mt=8&uo=4</a>
**App Version:** 5.0.1
**Seller:** M1 Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/m1-limited/id380634278?uo=4>© M1 Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/d0/e3/41/d0e341e3-cefd-3554-34d8-34d774cfab3f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19237172/c981bd34-8efb-11e6-8860-34b9c7eabef6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19237172/c981bd34-8efb-11e6-8860-34b9c7eabef6.png)
https://cloud.githubusercontent.com/assets/20930745/19237172/c981bd34-8efb-11e6-8860-34b9c7eabef6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19237182/d8b9e498-8efb-11e6-8ea7-e78b56cd513f.png
