### ISSUE TITLE
Pivotal Tracker

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#43]
**App Name:** Pivotal Tracker
**Bundle ID:** com.pivotallabs.pivotaltracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444623375">444623375</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pivotal-tracker/id444623375?mt=8&uo=4">https://itunes.apple.com/us/app/pivotal-tracker/id444623375?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** Pivotal Labs, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pivotal-labs/id444623379?uo=4>© Pivotal Labs</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/cc/18/b7/cc18b7ab-bc03-2be7-c83d-51dd2bb68772/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19105812/5058d228-8ae4-11e6-8f06-87c21a13fa39.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19105812/5058d228-8ae4-11e6-8f06-87c21a13fa39.png)
https://cloud.githubusercontent.com/assets/2068130/19105812/5058d228-8ae4-11e6-8f06-87c21a13fa39.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19105817/5ada37aa-8ae4-11e6-90b7-ac1dd718693c.png
