### ISSUE TITLE
Apps Gone Free & Daily Tips

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#430]
**App Name:** Apps Gone Free & Daily Tips
**Bundle ID:** com.appadvice.appsgonefree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=470693788">470693788</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/apps-gone-free-daily-tips/id470693788?mt=8&uo=4">https://itunes.apple.com/us/app/apps-gone-free-daily-tips/id470693788?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** App Advice
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/appadvice-com/id305663481?uo=4">© AppAdvice.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/86/3d/30/863d3078-5a22-8d94-bab2-8bc72ec135b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38598112-5f1adf6a-3d5b-11e8-8718-aeb176e4b4f6.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10388965/8899fd4e-6e6e-11e5-938d-588e0943c87e.png)
https://cloud.githubusercontent.com/assets/10730122/10388965/8899fd4e-6e6e-11e5-938d-588e0943c87e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10388963/85481c7a-6e6e-11e5-9e46-d7897a02a83c.png

 
Alternate,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10388978/9da7e89a-6e6e-11e5-806f-bb137517ae02.png)
https://cloud.githubusercontent.com/assets/10730122/10388978/9da7e89a-6e6e-11e5-806f-bb137517ae02.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10388972/99117030-6e6e-11e5-97b9-b535bf0fce7f.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38598112-5f1adf6a-3d5b-11e8-8718-aeb176e4b4f6.png)
https://user-images.githubusercontent.com/2068130/38598112-5f1adf6a-3d5b-11e8-8718-aeb176e4b4f6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38598125-6d43c5a2-3d5b-11e8-8645-fce14b872f06.png
