### ISSUE TITLE
Grab App

### ISSUE THREAD

**Issue by taigaak** [glasklart/hd#4328]
**App Name:** Grab App
**Bundle ID:** com.grabtaxi.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=647268330">647268330</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/grab-app/id647268330?uo=4">https://apps.apple.com/us/app/grab-app/id647268330?uo=4</a>
**App Version:** v5.51.0
**Seller:** GRABTAXI HOLDINGS PTE. LTD.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/grab-com/id1136548164?uo=4">© Grab.com</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/09/44/84/09448430-fd3a-2e71-2aab-400d9bab2090/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60536432-864bf400-9d06-11e9-8c64-5e70b0c204a9.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60536432-864bf400-9d06-11e9-8c64-5e70b0c204a9.png)
https://user-images.githubusercontent.com/20930745/60536432-864bf400-9d06-11e9-8c64-5e70b0c204a9.png

Source:
https://user-images.githubusercontent.com/20930745/60536436-877d2100-9d06-11e9-8712-2986e3458a7c.png
