### ISSUE TITLE
Key Ring Reward Cards

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#433]
**App Name:** Key Ring Reward Cards
**Bundle ID:** com.mobestream.keyring
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=372547556">372547556</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/key-ring-reward-cards/id372547556?mt=8&uo=4">https://itunes.apple.com/us/app/key-ring-reward-cards/id372547556?mt=8&uo=4</a>
**App Version:** 10.12
**Seller:** Mobestream Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobestream-media/id372547559?uo=4>© Mobestream Media</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/60/ee/8c/60ee8c0c-dfb6-b6b8-bffa-cf32e193523b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18762152/ebb48bcc-8107-11e6-853b-adac3df1f91d.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18746168/372ad8fa-80c6-11e6-943d-ea3325cda4d7.png)
https://cloud.githubusercontent.com/assets/20930745/18746168/372ad8fa-80c6-11e6-943d-ea3325cda4d7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18746180/45b0928e-80c6-11e6-89ad-c68d146fe9e8.png

**Comment by ivanov007** [comment]
it looks good, but do you think you can invert just the tags?

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18762152/ebb48bcc-8107-11e6-853b-adac3df1f91d.png)
https://cloud.githubusercontent.com/assets/20930745/18762152/ebb48bcc-8107-11e6-853b-adac3df1f91d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18762171/fe2c17fc-8107-11e6-8b52-8c5df88bc747.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18762396/e32cdf58-8108-11e6-9ad5-00e1afae1ee8.png)
https://cloud.githubusercontent.com/assets/20930745/18762396/e32cdf58-8108-11e6-9ad5-00e1afae1ee8.png

Source:
(https://cloud.githubusercontent.com/assets/20930745/18762412/f1e618a2-8108-11e6-945e-70e743d6dccc.png
