### ISSUE TITLE
Due — Reminders, Countdown Timers

### ISSUE THREAD

**Issue by lejos25** [glasklart/hd#4330]
**App Name:** Due — Reminders, Countdown Timers
**Bundle ID:** com.phocusllp.due
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390017969">390017969</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/due-reminders-countdown-timers/id390017969?mt=8&uo=4">https://itunes.apple.com/us/app/due-reminders-countdown-timers/id390017969?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Due Apps LLP
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/due-apps-llp/id387681526?uo=4>© Due Apps LLP</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple62/v4/6d/2b/46/6d2b469d-b576-0c16-cdba-e2bb8ac51a5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18245280/9cfde39e-7364-11e6-81d7-65831d7bcc77.png)

**Comment by l8er4now** [comment]
Needs an update?

**App Name:** Due — Reminders, Countdown Timers
**Bundle ID:** com.phocusllp.due
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390017969">390017969</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/due-reminders-countdown-timers/id390017969?mt=8&uo=4">https://itunes.apple.com/us/app/due-reminders-countdown-timers/id390017969?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Due Apps LLP
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/due-apps-llp/id387681526?uo=4>© Due Apps LLP</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple62/v4/6d/2b/46/6d2b469d-b576-0c16-cdba-e2bb8ac51a5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18245280/9cfde39e-7364-11e6-81d7-65831d7bcc77.png)
https://cloud.githubusercontent.com/assets/20930745/18245280/9cfde39e-7364-11e6-81d7-65831d7bcc77.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18245295/b051ce9c-7364-11e6-9c6e-37b597de4ee8.png

**Comment by 2Qt2beStr8** [comment]
... or this one ...

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18245383/2c90b4e6-7365-11e6-9ea1-a2dc0756ee15.png)
https://cloud.githubusercontent.com/assets/20930745/18245383/2c90b4e6-7365-11e6-9ea1-a2dc0756ee15.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18245398/47ae82f8-7365-11e6-8fac-5a74b3f47da1.png

**Comment by dreamnet** [comment]
I like mine better... :stuck_out_tongue_winking_eye:

**Comment by dreamnet** [comment]
Already in the master... closing.
