### ISSUE TITLE
Yammer

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#434]
**App Name:** Yammer
**Bundle ID:** wefwef
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=289559439">289559439</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yammer/id289559439?mt=8&uo=4">https://itunes.apple.com/us/app/yammer/id289559439?mt=8&uo=4</a>
**App Version:** 6.6.21
**Seller:** Yammer by Microsoft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yammer-by-microsoft/id289559442?uo=4>© Yammer by Microsoft</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/2d/25/9f/2d259f51-bd7a-a94e-e289-3fc203b8f02d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19022965/7c41d0ea-88e3-11e6-86b1-9b4ac710feee.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19022965/7c41d0ea-88e3-11e6-86b1-9b4ac710feee.png)
https://cloud.githubusercontent.com/assets/2068130/19022965/7c41d0ea-88e3-11e6-86b1-9b4ac710feee.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19022968/8ba5a53e-88e3-11e6-9f50-ff777731dfa1.png
