### ISSUE TITLE
Die Presse

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#4344]
**App Name:** Die Presse
**Bundle ID:** com.diepresse.iapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=394872877">394872877</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/die-presse/id394872877?uo=4">https://apps.apple.com/us/app/die-presse/id394872877?uo=4</a>
**App Version:** 4.4.7
**Seller:** DiePresse Digital GmbH &Co KG
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/die-presse-digital-gmbh-co-kg/id394872880?uo=4">© "Die Presse" Digital GmbH & Co KG</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/2e/a2/40/2ea24019-d90a-45c8-68f9-2a487159a113/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382432-40233600-9a63-11e9-8da8-08c4aca3610a.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382432-40233600-9a63-11e9-8da8-08c4aca3610a.png)
https://user-images.githubusercontent.com/20930745/60382432-40233600-9a63-11e9-8da8-08c4aca3610a.png

Source:
https://user-images.githubusercontent.com/20930745/60382433-41ecf980-9a63-11e9-9285-e9b17ebe4fc1.png
