### ISSUE TITLE
Newton Mail (previously CloudMagic Email)

### ISSUE THREAD

**Issue by alxbrmdz** [glasklart/hd#4354]
**App Name:** Newton Mail (previously CloudMagic Email)
**Bundle ID:** com.CloudMagic.Mail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=721677994">721677994</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newton-mail-previously-cloudmagic/id721677994?mt=8&uo=4">https://itunes.apple.com/us/app/newton-mail-previously-cloudmagic/id721677994?mt=8&uo=4</a>
**App Version:** 9.0.33
**Seller:** CloudMagic, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cloudmagic-inc./id721677997?uo=4>© CloudMagic, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/8d/20/6e/8d206ee8-43ac-3d85-3c61-5e8f2665ddd6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18625119/b3c09750-7e4c-11e6-8df2-1c3e5b5105fd.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Newton Mail (previously CloudMagic Email)
**Bundle ID:** com.CloudMagic.Mail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=721677994">721677994</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newton-mail-previously-cloudmagic/id721677994?mt=8&uo=4">https://itunes.apple.com/us/app/newton-mail-previously-cloudmagic/id721677994?mt=8&uo=4</a>
**App Version:** 9.0.33
**Seller:** CloudMagic, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cloudmagic-inc./id721677997?uo=4>© CloudMagic, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/8d/20/6e/8d206ee8-43ac-3d85-3c61-5e8f2665ddd6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18625119/b3c09750-7e4c-11e6-8df2-1c3e5b5105fd.png)
https://cloud.githubusercontent.com/assets/20930745/18625119/b3c09750-7e4c-11e6-8df2-1c3e5b5105fd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18625137/d94972f8-7e4c-11e6-9001-80697f309844.png
