### ISSUE TITLE
Timer 7 - Multiple timers for time management, kitchen, gym, errands and gtd

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#4359]
**App Name:** Timer 7 - Multiple timers for time management, kitchen, gym, errands and gtd
**Bundle ID:** com.mencphoto.timer7
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=713174884">713174884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/timer-7-multiple-timers-for/id713174884?mt=8&uo=4">https://itunes.apple.com/us/app/timer-7-multiple-timers-for/id713174884?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** Sasa Mencinger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sasa-mencinger/id605758275?uo=4>© Sasa Mencinger</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/f5/ee/0e/f5ee0ee0-3964-1531-2883-35ba8a8c7173/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17546120/e0d1fb16-5ee0-11e6-8d18-18cae92e4faa.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Timer 7 - Multiple timers for time management, kitchen, gym, errands and gtd
**Bundle ID:** com.mencphoto.timer7
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=713174884">713174884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/timer-7-multiple-timers-for/id713174884?mt=8&uo=4">https://itunes.apple.com/us/app/timer-7-multiple-timers-for/id713174884?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** Sasa Mencinger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sasa-mencinger/id605758275?uo=4>© Sasa Mencinger</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/f5/ee/0e/f5ee0ee0-3964-1531-2883-35ba8a8c7173/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17546120/e0d1fb16-5ee0-11e6-8d18-18cae92e4faa.png)
https://cloud.githubusercontent.com/assets/2068130/17546120/e0d1fb16-5ee0-11e6-8d18-18cae92e4faa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17546131/f0659da8-5ee0-11e6-9f82-0258a0115197.png
