### ISSUE TITLE
Pic Stitch - #1 Photo and Video Collage Maker

### ISSUE THREAD

**Issue by richmFTW** [glasklart/hd#436]
**App Name:** Pic Stitch - #1 Photo and Video Collage Maker
**Bundle ID:** com.bigblueclip.picstitch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454768104">454768104</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pic-stitch-1-photo-video-collage/id454768104?mt=8&uo=4">https://itunes.apple.com/us/app/pic-stitch-1-photo-video-collage/id454768104?mt=8&uo=4</a>
**App Version:** 6.5
**Seller:** Big Blue Clip, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/big-blue-clip-llc/id307083557?uo=4>© Big Blue Clip, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/42/2d/9b/422d9be5-dbcd-bace-d5ba-92e0cb82c407/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417252/5876f490-93a8-11e6-91b3-9c7502c788b9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19417252/5876f490-93a8-11e6-91b3-9c7502c788b9.png)
https://cloud.githubusercontent.com/assets/20930745/19417252/5876f490-93a8-11e6-91b3-9c7502c788b9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19417253/73d4561a-93a8-11e6-9561-2a8633604d91.png
