### ISSUE TITLE
Farlige stoffer

### ISSUE THREAD

**Issue by andersmogensen** [glasklart/hd#4375]
**App Name:** Farlige stoffer
**Bundle ID:** dk.brs.fs1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=661077031">661077031</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/farlige-stoffer/id661077031?uo=4">https://apps.apple.com/us/app/farlige-stoffer/id661077031?uo=4</a>
**App Version:** 2.1.1
**Seller:** Beredskabsstyrelsen
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/beredskabsstyrelsen/id661077034?uo=4">© Beredskabsstyrelsen</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/f5/e5/8d/f5e58d30-accf-c183-79f1-463b364fd461/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393888-6fe24480-9b1c-11e9-9e0c-8de464051bfd.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393888-6fe24480-9b1c-11e9-9e0c-8de464051bfd.png)
https://user-images.githubusercontent.com/20930745/60393888-6fe24480-9b1c-11e9-9e0c-8de464051bfd.png

Source:
https://user-images.githubusercontent.com/20930745/60393890-71ac0800-9b1c-11e9-9022-144fcba73360.png
