### ISSUE TITLE
Video & TV SideView: Quick Remote

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#4380]
**App Name:** Video & TV SideView: Quick Remote
**Bundle ID:** jp.co.sony.tvsideview
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=594171390">594171390</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/video-tv-sideview-quick-remote/id594171390?mt=8&uo=4">https://itunes.apple.com/us/app/video-tv-sideview-quick-remote/id594171390?mt=8&uo=4</a>
**App Version:** 4.4.0
**Seller:** Sony Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sony-corporation/id371425038?uo=4>© Sony Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple71/v4/f8/c6/db/f8c6dbfa-1e41-5a17-c196-97eecc77a21e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18232303/dc900854-729a-11e6-8458-9df1dc96b1f1.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Video & TV SideView: Quick Remote
**Bundle ID:** jp.co.sony.tvsideview
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=594171390">594171390</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/video-tv-sideview-quick-remote/id594171390?mt=8&uo=4">https://itunes.apple.com/us/app/video-tv-sideview-quick-remote/id594171390?mt=8&uo=4</a>
**App Version:** 4.4.0
**Seller:** Sony Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sony-corporation/id371425038?uo=4>© Sony Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple71/v4/f8/c6/db/f8c6dbfa-1e41-5a17-c196-97eecc77a21e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18232303/dc900854-729a-11e6-8458-9df1dc96b1f1.png)

https://cloud.githubusercontent.com/assets/3704186/18232303/dc900854-729a-11e6-8458-9df1dc96b1f1.png

https://cloud.githubusercontent.com/assets/3704186/18232304/e76f965e-729a-11e6-9004-2b5a74c044e6.png
