### ISSUE TITLE
TripCase

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#4389]
**App Name:** TripCase
**Bundle ID:** com.sabre.tripcase.prod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=309620151">309620151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tripcase/id309620151?mt=8&uo=4">https://itunes.apple.com/us/app/tripcase/id309620151?mt=8&uo=4</a>
**App Version:** 4.7.1
**Seller:** Sabre Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sabre-inc./id309620154?uo=4>© Sabre Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple71/v4/cc/00/95/cc00950d-0375-e336-e2d6-9cbe07731bea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18030868/aaeb1fdc-6cc8-11e6-8c8a-1c98b8bbb90e.png)

**Comment by l8er4now** [comment]
Needs an update, more flat of an icon now.

**App Name:** TripCase
**Bundle ID:** com.sabre.tripcase.prod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=309620151">309620151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tripcase/id309620151?mt=8&uo=4">https://itunes.apple.com/us/app/tripcase/id309620151?mt=8&uo=4</a>
**App Version:** 4.7.1
**Seller:** Sabre Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sabre-inc./id309620154?uo=4>© Sabre Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple71/v4/cc/00/95/cc00950d-0375-e336-e2d6-9cbe07731bea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18030868/aaeb1fdc-6cc8-11e6-8c8a-1c98b8bbb90e.png)
https://cloud.githubusercontent.com/assets/10730122/18030868/aaeb1fdc-6cc8-11e6-8c8a-1c98b8bbb90e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18030867/aae93ad2-6cc8-11e6-8713-b1329531a276.png
