### ISSUE TITLE
Genius: Song Lyrics + Music Knowledge

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#4392]
**App Name:** Genius: Song Lyrics + Music Knowledge
**Bundle ID:** com.rapgenius.RapGenius
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=709482991">709482991</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/genius-song-lyrics-+-music/id709482991?mt=8&uo=4">https://itunes.apple.com/us/app/genius-song-lyrics-+-music/id709482991?mt=8&uo=4</a>
**App Version:** 3.5.0
**Seller:** Genius Media Group Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/genius-media-group/id709482994?uo=4>© Genius Media Group</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple71/v4/32/6a/16/326a167e-7d75-2731-ffa6-45aff19a97c4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17994176/c152732e-6b56-11e6-9e94-4fe27397690f.png)

**Comment by alpcinar** [comment]
Needs update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17994176/c152732e-6b56-11e6-9e94-4fe27397690f.png)
https://cloud.githubusercontent.com/assets/2068130/17994176/c152732e-6b56-11e6-9e94-4fe27397690f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17994214/d0a6d9dc-6b56-11e6-9d81-4a9993e7ee2b.png
