### ISSUE TITLE
Recorder

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#44]
**App Name:** Recorder
**Bundle ID:** com.retronyms.Recorder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284428991">284428991</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/recorder/id284428991?mt=8&uo=4">https://itunes.apple.com/us/app/recorder/id284428991?mt=8&uo=4</a>
**App Version:** 12.0.1
**Seller:** dan walton
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/retronyms/id284428994?uo=4">© Retronyms</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple117/v4/05/06/e4/0506e4bf-998e-b796-c7bd-3902ffd6f2ed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692834-91cb91a0-c71f-11e7-9cd6-36adb51480e4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692834-91cb91a0-c71f-11e7-9cd6-36adb51480e4.png)
https://user-images.githubusercontent.com/2068130/32692834-91cb91a0-c71f-11e7-9cd6-36adb51480e4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692839-a14525ba-c71f-11e7-89d9-a87d7cd8a163.png
