### ISSUE TITLE
AE + Aerie

### ISSUE THREAD

**Issue by miso-honei** [glasklart/hd#4423]
**App Name:** AE + Aerie
**Bundle ID:** com.ae.ae
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467738064">467738064</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ae-aerie/id467738064?mt=8&uo=4">https://itunes.apple.com/us/app/ae-aerie/id467738064?mt=8&uo=4</a>
**App Version:** 5.5.0
**Seller:** American Eagle Outfitters
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/american-eagle-outfitters/id450661097?uo=4">© American Eagle Outfitters</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/73/87/45/738745f7-8dcb-cf75-d8f9-d104da0eae7f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455392-c09ef9c4-3a77-11e8-937c-562f3b2afe18.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455392-c09ef9c4-3a77-11e8-937c-562f3b2afe18.png)
https://user-images.githubusercontent.com/20930745/38455392-c09ef9c4-3a77-11e8-937c-562f3b2afe18.png

Source:
https://user-images.githubusercontent.com/20930745/38455397-d44c3720-3a77-11e8-81f5-ebde64d5242e.png
