### ISSUE TITLE
Macy's

### ISSUE THREAD

**Issue by richmFTW** [glasklart/hd#443]
**App Name:** Macy's
**Bundle ID:** macys.ishop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=341036067">341036067</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/macys/id341036067?mt=8&uo=4">https://itunes.apple.com/us/app/macys/id341036067?mt=8&uo=4</a>
**App Version:** 5.4.1
**Seller:** Macys Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/macys-inc/id341036070?uo=4>© Macys Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/b4/8f/98/b48f9818-3207-d345-705d-8d62f723fd5e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18927427/2aa3bd72-85bc-11e6-8be7-12dec2aa4499.png)

**Comment by illinikev** [comment]
Update needed

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18927427/2aa3bd72-85bc-11e6-8be7-12dec2aa4499.png)
https://cloud.githubusercontent.com/assets/20930745/18927427/2aa3bd72-85bc-11e6-8be7-12dec2aa4499.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18927444/378476a8-85bc-11e6-9d4d-56bc5f647cef.png
