### ISSUE TITLE
Develop!

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4431]
**App Name:** Develop!
**Bundle ID:** com.toddbreslow.trix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=568421864">568421864</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/develop/id568421864?uo=4">https://apps.apple.com/us/app/develop/id568421864?uo=4</a>
**App Version:** 3.0.1
**Seller:** Todd Breslow
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/todd-breslow/id568421867?uo=4">© Todd Breslow</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/08/a5/cb/08a5cb7e-c1e1-88c6-1396-6cd788d2a669/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382477-cd668a80-9a63-11e9-9793-a299d10cecb5.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382477-cd668a80-9a63-11e9-9793-a299d10cecb5.png)
https://user-images.githubusercontent.com/20930745/60382477-cd668a80-9a63-11e9-9793-a299d10cecb5.png

Source:
https://user-images.githubusercontent.com/20930745/60382479-ce97b780-9a63-11e9-8f85-7951202dfce8.png
