### ISSUE TITLE
happn — Dating app

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4432]
**App Name:** happn — Dating app
**Bundle ID:** fr.ftw-and-co.whoozer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489185828">489185828</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/happn-dating-app/id489185828?uo=4">https://apps.apple.com/us/app/happn-dating-app/id489185828?uo=4</a>
**App Version:** 9.4.5
**Seller:** HAPPN SAS
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/happn-sas/id489185851?uo=4">© HAPPN SAS</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/9b/ea/1d/9bea1d81-1a9f-f20f-f8f1-47625fad259e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60773150-5e430300-a101-11e9-8399-0190b10fa5ea.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60773150-5e430300-a101-11e9-8399-0190b10fa5ea.png)
https://user-images.githubusercontent.com/2068130/60773150-5e430300-a101-11e9-8399-0190b10fa5ea.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60773152-6e5ae280-a101-11e9-9b41-cbd8d5029de7.png
