### ISSUE TITLE
iAliens for Reddit

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#4458]
**App Name:** iAliens for Reddit
**Bundle ID:** com.appseedinc.aliens
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=802676924">802676924</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aliens-for-reddit/id802676924?mt=8&uo=4">https://itunes.apple.com/us/app/aliens-for-reddit/id802676924?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** AppSeed Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/appseed-inc./id689558375?uo=4>© AppSeed Inc.</a>
**Supported Devices:** iPhone5, iPhone5c, iPadMini, iPadFourthGen4G, iPhone4S, iPhone5s, iPad23G, iPhone4, iPad2Wifi, iPadThirdGen4G, iPadThirdGen, iPadMini4G, iPadFourthGen, iPodTouchFifthGen
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/62393440-770cd000-b56a-11e9-926d-21be06da92d7.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62395649-382e4880-b571-11e9-9cdb-9b5dca63c873.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62395649-382e4880-b571-11e9-9cdb-9b5dca63c873.png)
https://user-images.githubusercontent.com/2068130/62395649-382e4880-b571-11e9-9cdb-9b5dca63c873.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62395680-48debe80-b571-11e9-8aba-94eae6cf98be.png
