### ISSUE TITLE
Shopping Cart Hero 3

### ISSUE THREAD

**Issue by mistaeast** [glasklart/hd#446]
**App Name:** Shopping Cart Hero 3
**Bundle ID:** com.mwb.sch3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484590523">484590523</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shopping-cart-hero-3/id484590523?mt=8&uo=4">https://itunes.apple.com/us/app/shopping-cart-hero-3/id484590523?mt=8&uo=4</a>
**App Version:** 1.02
**Seller:** MonkeyWantBanana
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/monkeywantbanana/id328610461?uo=4>© MonkeyWantBanana</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/7c/a6/5a/7ca65aef-87c6-d85b-253b-2bad3c90ad22/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18846557/d0164c08-8426-11e6-895b-62b2560b7878.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18846557/d0164c08-8426-11e6-895b-62b2560b7878.png)
https://cloud.githubusercontent.com/assets/2068130/18846557/d0164c08-8426-11e6-895b-62b2560b7878.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18846565/e010a860-8426-11e6-8617-f45189f05852.png
