### ISSUE TITLE
Todoist: To-Do List & Tasks

### ISSUE THREAD

**Issue by euphony** [glasklart/hd#4465]
**App Name:** Todoist: To-Do List & Tasks
**Bundle ID:** com.todoist.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=572688855">572688855</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/todoist-to-do-list-tasks/id572688855?uo=4">https://apps.apple.com/us/app/todoist-to-do-list-tasks/id572688855?uo=4</a>
**App Version:** 12.3
**Seller:** Doist Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/doist-inc/id572688858?uo=4">© Doist Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/ba/46/4f/ba464faf-5c93-3ad3-427e-ff15c1adacd2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84352602-eeb17f80-abbd-11ea-980a-b326f6936d80.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Todoist: To-Do List & Tasks
**Bundle ID:** com.todoist.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=572688855">572688855</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/todoist-to-do-list-tasks/id572688855?uo=4">https://apps.apple.com/us/app/todoist-to-do-list-tasks/id572688855?uo=4</a>
**App Version:** 12.3
**Seller:** Doist Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/doist-inc/id572688858?uo=4">© Doist Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/ba/46/4f/ba464faf-5c93-3ad3-427e-ff15c1adacd2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84352602-eeb17f80-abbd-11ea-980a-b326f6936d80.png)
https://user-images.githubusercontent.com/2068130/84352602-eeb17f80-abbd-11ea-980a-b326f6936d80.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84352640-fe30c880-abbd-11ea-85cb-aff5a9db71e3.png
