### ISSUE TITLE
VK

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#447]
**App Name:** VK
**Bundle ID:** com.vk.vkclient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=564177498">564177498</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vk/id564177498?mt=8&uo=4">https://itunes.apple.com/us/app/vk/id564177498?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** VKontakte
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/vkontakte/id427948433?uo=4>© VKontakte</a>
**Supported Devices:** iPodTouchFifthGen, iPad23G, iPhone5, iPhone5s, iPhone-3GS, iPodTouchFourthGen, iPhone6, iPad2Wifi, iPadFourthGen4G, iPhone4, iPadThirdGen4G, iPadFourthGen, iPhone5c, iPadMini4G, iPhone4S, iPadThirdGen, iPadMini, iPodTouchSixthGen, iPhone6Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/3d/d6/57/3dd6572b-2d6f-40f2-27e4-a0147f316bfa/mzl.pvieqogz.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8832004/81f8700c-30a6-11e5-89e7-1de6de056463.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8832004/81f8700c-30a6-11e5-89e7-1de6de056463.png)
https://cloud.githubusercontent.com/assets/10730122/8832004/81f8700c-30a6-11e5-89e7-1de6de056463.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8832002/7d34ad38-30a6-11e5-8061-9eafacec26a3.png
