### ISSUE TITLE
NCAA Sports

### ISSUE THREAD

**Issue by csterno** [glasklart/hd#4486]
**App Name:** NCAA Sports
**Bundle ID:** com.xtremelabs.ncaasports
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478396998">478396998</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ncaa-sports/id478396998?mt=8&uo=4">https://itunes.apple.com/us/app/ncaa-sports/id478396998?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Turner Sports
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/turner-sports/id358570327?uo=4>© Turner Sports</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/e8/c4/85/e8c4850b-d34f-e0ea-4841-b791bdec80d8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19677919/e7aa2976-9a9b-11e6-89a1-a778f9e2b28a.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** NCAA Sports
**Bundle ID:** com.xtremelabs.ncaasports
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478396998">478396998</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ncaa-sports/id478396998?mt=8&uo=4">https://itunes.apple.com/us/app/ncaa-sports/id478396998?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Turner Sports
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/turner-sports/id358570327?uo=4>© Turner Sports</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/e8/c4/85/e8c4850b-d34f-e0ea-4841-b791bdec80d8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19677919/e7aa2976-9a9b-11e6-89a1-a778f9e2b28a.png)
https://cloud.githubusercontent.com/assets/20930745/19677919/e7aa2976-9a9b-11e6-89a1-a778f9e2b28a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19677949/0339acb6-9a9c-11e6-9bcb-3432d5970a6b.png
