### ISSUE TITLE
Inotia 3: Eternity

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#449]
**App Name:** Inotia 3: Eternity
**Bundle ID:** com.com2us.inotia3.freemium.freefull.apple.global.ios.universal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at/?id=493200949">493200949</a>
**iTunes URL:** <a target="_blank" href="http://itunes.apple.com/app/id493200949">http://itunes.apple.com/app/id493200949</a>
**App Version:** 1.4.6
**Seller:** Com2uS USA, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/com2us-usa-inc./id355472980?mt=8&uo=4">© Com2uS USA, Inc.</a>
**Supported Devices:** iPhone4, iPhone4S, iPhone5, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, 
iPodTouchFifthGen, iPodTouchSixthGen, iPad23G, iPad2Wifi®iPadFourthGen, iPadFourthGen4G, iPadThirdGen, iPadThirdGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/23329423/57aa48da-fb38-11e6-853c-5834e6867ff4.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23329349/edc13aa6-fb36-11e6-81e8-62fbe719e25f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23329349/edc13aa6-fb36-11e6-81e8-62fbe719e25f.png)
https://cloud.githubusercontent.com/assets/2068130/23329349/edc13aa6-fb36-11e6-81e8-62fbe719e25f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23329355/fd31e184-fb36-11e6-983e-5287cb62e607.png
