### ISSUE TITLE
Trulia Real Estate: Find Homes

### ISSUE THREAD

**Issue by miso-honei** [glasklart/hd#4493]
**App Name:** Trulia Real Estate: Find Homes
**Bundle ID:** com.trulia.Trulia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288487321">288487321</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/trulia-real-estate-find-homes/id288487321?uo=4">https://apps.apple.com/us/app/trulia-real-estate-find-homes/id288487321?uo=4</a>
**App Version:** 12.2.1
**Seller:** Trulia, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/trulia-inc/id288487324?uo=4">© Trulia, Inc</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/fd/af/d6/fdafd60d-3405-ccaf-188e-21ce21ffd97e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63873103-42503500-c9bf-11e9-9bbd-457ebdccf1fd.png)

**Comment by l8er4now** [comment]
Needs an update

**App Name:** Trulia Real Estate: Find Homes
**Bundle ID:** com.trulia.Trulia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288487321">288487321</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/trulia-real-estate-find-homes/id288487321?uo=4">https://apps.apple.com/us/app/trulia-real-estate-find-homes/id288487321?uo=4</a>
**App Version:** 12.2.1
**Seller:** Trulia, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/trulia-inc/id288487324?uo=4">© Trulia, Inc</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/fd/af/d6/fdafd60d-3405-ccaf-188e-21ce21ffd97e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63873103-42503500-c9bf-11e9-9bbd-457ebdccf1fd.png)
https://user-images.githubusercontent.com/20930745/63873103-42503500-c9bf-11e9-9bbd-457ebdccf1fd.png

Source:
https://user-images.githubusercontent.com/20930745/63873109-4419f880-c9bf-11e9-8df1-02e353b64caf.png
