### ISSUE TITLE
FreePrints – Photos Delivered

### ISSUE THREAD

**Issue by miso-honei** [glasklart/hd#4494]
**App Name:** FreePrints – Photos Delivered
**Bundle ID:** com.novadevelopment.freeprints
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=518158653">518158653</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/freeprints-photos-delivered/id518158653?uo=4">https://apps.apple.com/us/app/freeprints-photos-delivered/id518158653?uo=4</a>
**App Version:** 2.42.1
**Seller:** PlanetArt, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/planetart/id911528758?uo=4">© PlanetArt</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/d9/b8/49/d9b849c3-c2ba-27e4-fd59-c09c6f9235c4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60395015-3e25a980-9b2d-11e9-8a4c-11319dea82f4.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60395015-3e25a980-9b2d-11e9-8a4c-11319dea82f4.png)
https://user-images.githubusercontent.com/2068130/60395015-3e25a980-9b2d-11e9-8a4c-11319dea82f4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60395017-4d0c5c00-9b2d-11e9-8fc8-49b7a7e18fb3.png
