### ISSUE TITLE
Papa John's Pizza

### ISSUE THREAD

**Issue by miso-honei** [glasklart/hd#4498]
**App Name:** Papa John's Pizza
**Bundle ID:** com.papajohns.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407517450">407517450</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/papa-johns-pizza/id407517450?uo=4">https://apps.apple.com/us/app/papa-johns-pizza/id407517450?uo=4</a>
**App Version:** 4.38.1
**Seller:** Papa John's International Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/papa-johns-international-inc/id407517453?uo=4">© Papa John's International Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/83/43/0f/83430fe4-b311-f158-152b-aa01a6f71f2f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73614068-1d11c380-45fc-11ea-836d-b739f5bf867d.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Papa John's Pizza
**Bundle ID:** com.papajohns.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407517450">407517450</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/papa-johns-pizza/id407517450?uo=4">https://apps.apple.com/us/app/papa-johns-pizza/id407517450?uo=4</a>
**App Version:** 4.38.1
**Seller:** Papa John's International Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/papa-johns-international-inc/id407517453?uo=4">© Papa John's International Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/83/43/0f/83430fe4-b311-f158-152b-aa01a6f71f2f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73614068-1d11c380-45fc-11ea-836d-b739f5bf867d.png)
https://user-images.githubusercontent.com/2068130/73614068-1d11c380-45fc-11ea-836d-b739f5bf867d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73614074-2bf87600-45fc-11ea-9f23-31052c0fc6b4.png
