### ISSUE TITLE
FanDuel - Fantasy Sports

### ISSUE THREAD

**Issue by miso-honei** [glasklart/hd#4503]
**App Name:** FanDuel - Fantasy Sports
**Bundle ID:** com.fanduel.fd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=599664106">599664106</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fanduel-fantasy-sports/id599664106?uo=4">https://apps.apple.com/us/app/fanduel-fantasy-sports/id599664106?uo=4</a>
**App Version:** 2.70
**Seller:** FanDuel Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fanduel-inc/id599664829?uo=4">© FanDuel, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/54/6f/35/546f356b-a771-93fb-4b75-85ceaca53626/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400677-7baf2480-9b77-11e9-8faa-50cc17e0e553.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400677-7baf2480-9b77-11e9-8faa-50cc17e0e553.png)
https://user-images.githubusercontent.com/20930745/60400677-7baf2480-9b77-11e9-8faa-50cc17e0e553.png

Source:
https://user-images.githubusercontent.com/20930745/60400678-7eaa1500-9b77-11e9-9463-a22660cad08c.png
