### ISSUE TITLE
Inotia 4

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#451]
**App Name:** Inotia 4
**Bundle ID:** com.com2us.inotia4.normal.freefull.apple.global.ios.universal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504785794">504785794</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inotia-4/id504785794?mt=8&uo=4">https://itunes.apple.com/us/app/inotia-4/id504785794?mt=8&uo=4</a>
**App Version:** 1.2.6
**Seller:** Com2uS USA, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/com2us-usa-inc/id355472980?mt=8&uo=4">© Com2uS USA, Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/2b/a0/8f/2ba08f3a-4aa7-bcc4-8b6c-fe626bcf0a71/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688140-b079082a-c6cb-11e7-9c19-1ffcd40dee0f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688140-b079082a-c6cb-11e7-9c19-1ffcd40dee0f.png)
https://user-images.githubusercontent.com/2068130/32688140-b079082a-c6cb-11e7-9c19-1ffcd40dee0f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32688143-c043411c-c6cb-11e7-83f7-c49a5ce45101.png
