### ISSUE TITLE
Pulseway

### ISSUE THREAD

**Issue by Geofferey** [glasklart/hd#4527]
**App Name:** Pulseway
**Bundle ID:** ro.mmsoft.pcmonitor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405566169">405566169</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pulseway/id405566169?mt=8&uo=4">https://itunes.apple.com/us/app/pulseway/id405566169?mt=8&uo=4</a>
**App Version:** 5.4
**Seller:** MMSOFT Design Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mmsoft-design-ltd/id351848430?uo=4">© MMSOFT Design Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/4d/16/7c/4d167ca3-9182-a8ad-fbc5-5a16802b41dc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38288640-38ea053e-37d2-11e8-8215-babef93a694e.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Pulseway
**Bundle ID:** ro.mmsoft.pcmonitor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405566169">405566169</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pulseway/id405566169?mt=8&uo=4">https://itunes.apple.com/us/app/pulseway/id405566169?mt=8&uo=4</a>
**App Version:** 5.4
**Seller:** MMSOFT Design Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mmsoft-design-ltd/id351848430?uo=4">© MMSOFT Design Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/4d/16/7c/4d167ca3-9182-a8ad-fbc5-5a16802b41dc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38288640-38ea053e-37d2-11e8-8215-babef93a694e.png)
https://user-images.githubusercontent.com/2068130/38288640-38ea053e-37d2-11e8-8215-babef93a694e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38288654-4787822e-37d2-11e8-8d01-4c373f464e0a.png
