### ISSUE TITLE
WeatherBug - Weather Forecasts & Alerts

### ISSUE THREAD

**Issue by Geofferey** [glasklart/hd#4529]
**App Name:** WeatherBug - Weather Forecasts & Alerts
**Bundle ID:** com.aws.weatherbug.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=281940292">281940292</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weatherbug-weather-forecasts/id281940292?mt=8&uo=4">https://itunes.apple.com/us/app/weatherbug-weather-forecasts/id281940292?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** Earth Networks, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/earth-networks-inc./id281940295?uo=4>© Earth Networks, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/aa/a7/46/aaa74620-27e2-69ad-e867-d869edfad0de/mzl.yypztaxb.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10871117/da24f5dc-80a3-11e5-94c6-05d0d27a8316.png)

**Comment by l8er4now** [comment]
A bit of a tweak is needed for this one.

**App Name:** WeatherBug - Weather Forecasts & Alerts
**Bundle ID:** com.aws.weatherbug.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=281940292">281940292</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weatherbug-weather-forecasts/id281940292?mt=8&uo=4">https://itunes.apple.com/us/app/weatherbug-weather-forecasts/id281940292?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** Earth Networks, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/earth-networks-inc./id281940295?uo=4>© Earth Networks, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/aa/a7/46/aaa74620-27e2-69ad-e867-d869edfad0de/mzl.yypztaxb.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10871117/da24f5dc-80a3-11e5-94c6-05d0d27a8316.png)
https://cloud.githubusercontent.com/assets/3090247/10871117/da24f5dc-80a3-11e5-94c6-05d0d27a8316.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10871118/da25c908-80a3-11e5-92a5-1f7d98f24d9d.png
