### ISSUE TITLE
Spice Bandits

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#453]
**App Name:** Spice Bandits
**Bundle ID:** com.chillingo.spicepirateshd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467338170">467338170</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spice-bandits/id467338170?mt=8&uo=4">https://itunes.apple.com/us/app/spice-bandits/id467338170?mt=8&uo=4</a>
**App Version:** 1.27
**Seller:** Jordic Invest ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/on5/id345571672?uo=4">© On5</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/dd/e8/fa/dde8face-9e27-3101-f21e-fcbf04b26a41/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32693340-9bbf6150-c729-11e7-8190-09049423f2cd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32693340-9bbf6150-c729-11e7-8190-09049423f2cd.png)
https://user-images.githubusercontent.com/2068130/32693340-9bbf6150-c729-11e7-8190-09049423f2cd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32693346-ac10dc28-c729-11e7-9d89-26127c57b148.png
