### ISSUE TITLE
Super Hexagon

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#454]
**App Name:** Super Hexagon
**Bundle ID:** com.distractionware.superhexagon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=549027629">549027629</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-hexagon/id549027629?mt=8&uo=4">https://itunes.apple.com/us/app/super-hexagon/id549027629?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Terry Cavanagh
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/terry-cavanagh/id413794996?uo=4>© Terry Cavanagh</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/e1/6f/30/e16f30dd-af0d-7062-ba81-cede2841dcd7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12278521/ec18e6c4-b981-11e5-8d10-56d2b951958b.png)

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12278521/ec18e6c4-b981-11e5-8d10-56d2b951958b.png)
https://cloud.githubusercontent.com/assets/2068130/12278521/ec18e6c4-b981-11e5-8d10-56d2b951958b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12278528/fa5fb7f8-b981-11e5-9816-0bf058895e1e.png
