### ISSUE TITLE
Arizona DMV Permit Test

### ISSUE THREAD

**Issue by Geofferey** [glasklart/hd#4544]
**App Name:** Arizona DMV Permit Test
**Bundle ID:** ArizonaDMVPaid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=436937222">436937222</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/arizona-dmv-permit-test/id436937222?mt=8&uo=4">https://itunes.apple.com/us/app/arizona-dmv-permit-test/id436937222?mt=8&uo=4</a>
**App Version:** 4.92
**Seller:** Deedal Studios Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/deedal-studios-inc/id411285839?uo=4">© Deedal Studios Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/7d/d5/23/7dd52336-3961-220a-c0d0-d1504d9a0c90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38456166-968dca3e-3a81-11e8-959b-87824bcc8ca7.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38456166-968dca3e-3a81-11e8-959b-87824bcc8ca7.png)
https://user-images.githubusercontent.com/20930745/38456166-968dca3e-3a81-11e8-959b-87824bcc8ca7.png

Source:
https://user-images.githubusercontent.com/20930745/38456174-aa52e3b0-3a81-11e8-87a6-b0b73e078b53.png
