### ISSUE TITLE
DMV Hub - Permit Practice Test

### ISSUE THREAD

**Issue by Geofferey** [glasklart/hd#4548]
**App Name:** DMV Hub - Permit Practice Test
**Bundle ID:** USDMV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444873616">444873616</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dmv-hub-permit-practice-test/id444873616?uo=4">https://apps.apple.com/us/app/dmv-hub-permit-practice-test/id444873616?uo=4</a>
**App Version:** 5.44
**Seller:** Deedal Studios Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/deedal-studios-inc/id411285839?uo=4">© Deedal Studios Inc</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/49/1a/9d/491a9d05-12a9-679f-c538-9510440c62f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382674-e7ee3300-9a66-11e9-9407-a5a2ba41016f.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382674-e7ee3300-9a66-11e9-9407-a5a2ba41016f.png)
https://user-images.githubusercontent.com/20930745/60382674-e7ee3300-9a66-11e9-9407-a5a2ba41016f.png

Source:
https://user-images.githubusercontent.com/20930745/60382675-e9b7f680-9a66-11e9-8225-d12907f2c2a9.png
