### ISSUE TITLE
Hatchi - A retro virtual pet

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#455]
**App Name:** Hatchi - A retro virtual pet
**Bundle ID:** com.portablepixels.hatchi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489479624">489479624</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hatchi-a-retro-virtual-pet/id489479624?mt=8&uo=4">https://itunes.apple.com/us/app/hatchi-a-retro-virtual-pet/id489479624?mt=8&uo=4</a>
**App Version:** 7.6
**Seller:** Portable Pixels Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/portable-pixels/id361966030?uo=4">© Portable Pixels</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple117/v4/e1/6e/c4/e16ec46b-8500-a0c9-b8fb-4d5cb98c5277/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38735452-21a9c7de-3f29-11e8-911b-9bb860b505d7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38735452-21a9c7de-3f29-11e8-911b-9bb860b505d7.png)
https://user-images.githubusercontent.com/20930745/38735452-21a9c7de-3f29-11e8-911b-9bb860b505d7.png

Source:
https://user-images.githubusercontent.com/20930745/38735488-358b4f98-3f29-11e8-8e21-8c73276f52cc.png
