### ISSUE TITLE
Aqueduct

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#457]
**App Name:** Aqueduct
**Bundle ID:** com.kiefferbros.mallard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377544857">377544857</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aqueduct/id377544857?mt=8&uo=4">https://itunes.apple.com/us/app/aqueduct/id377544857?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Kieffer Bros., LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kieffer-bros./id293702721?uo=4>© Kieffer Bros.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/d5/40/fa/d540fabf-558b-7f11-384c-3469f91d3ae2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19625091/376fb9f0-990f-11e6-8e42-9c205cf39404.png)

**Comment by dreamnet** [comment]
Icon by @scottbuckley.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19625091/376fb9f0-990f-11e6-8e42-9c205cf39404.png)
https://cloud.githubusercontent.com/assets/2068130/19625091/376fb9f0-990f-11e6-8e42-9c205cf39404.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19625099/4bfddf5a-990f-11e6-9c93-48c3cda88103.png
