### ISSUE TITLE
mobile-pocket loyalty cards

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#4584]
**App Name:** mobile-pocket loyalty cards
**Bundle ID:** at.bluesource.mobile-pocket
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=384619059">384619059</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobile-pocket-loyalty-cards/id384619059?mt=8&uo=4">https://itunes.apple.com/us/app/mobile-pocket-loyalty-cards/id384619059?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** bluesource - mobile solutions gmbh
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bluesource-mobile-solutions-gmbh/id384616919?uo=4">© bluesource - mobile solutions gmbh</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/6a/14/91/6a1491d8-17d8-af0d-574b-9f35e7392d75/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/28534937-de4a337a-70a2-11e7-859a-3a6e249f287d.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** mobile-pocket loyalty cards
**Bundle ID:** at.bluesource.mobile-pocket
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=384619059">384619059</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobile-pocket-loyalty-cards/id384619059?mt=8&uo=4">https://itunes.apple.com/us/app/mobile-pocket-loyalty-cards/id384619059?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** bluesource - mobile solutions gmbh
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bluesource-mobile-solutions-gmbh/id384616919?uo=4">© bluesource - mobile solutions gmbh</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/6a/14/91/6a1491d8-17d8-af0d-574b-9f35e7392d75/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/28534937-de4a337a-70a2-11e7-859a-3a6e249f287d.png)
https://user-images.githubusercontent.com/20930745/28534937-de4a337a-70a2-11e7-859a-3a6e249f287d.png

Source:
https://user-images.githubusercontent.com/20930745/28534957-f398bcba-70a2-11e7-96ec-e2228d2515d1.png
