### ISSUE TITLE
BuzzFeed

### ISSUE THREAD

**Issue by Geofferey** [glasklart/hd#4591]
**App Name:** BuzzFeed
**Bundle ID:** com.buzzfeed.buzzfeed
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=352969997">352969997</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/buzzfeed/id352969997?mt=8&uo=4">https://itunes.apple.com/us/app/buzzfeed/id352969997?mt=8&uo=4</a>
**App Version:** 4.8
**Seller:** BuzzFeed
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/buzzfeed/id352970000?uo=4>© BuzzFeed</a>
**Supported Devices:** iPhone4S, iPhone4, iPhone5c, iPad2Wifi, iPhone5, iPadFourthGen, iPodTouchFifthGen, iPadThirdGen, iPhone5s, iPhone6Plus, iPadFourthGen4G, iPad23G, iPadThirdGen4G, iPadMini, iPadMini4G, iPhone6
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/d7/74/b6/d774b698-5269-9355-b66d-62d4dccc79a2/mzl.qvaencie.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8347931/f44213b6-1b0c-11e5-8603-b76dfb66fec7.png)

**Comment by Trubbel** [comment]
Icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8347931/f44213b6-1b0c-11e5-8603-b76dfb66fec7.png)
https://cloud.githubusercontent.com/assets/10730122/8347931/f44213b6-1b0c-11e5-8603-b76dfb66fec7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8347929/f003b30e-1b0c-11e5-9f4b-dce0b45d4965.png
