### ISSUE TITLE
eharmony - Online Dating App

### ISSUE THREAD

**Issue by Geofferey** [glasklart/hd#4592]
**App Name:** eharmony - Online Dating App
**Bundle ID:** com.eharmony.singles.SinglesRelease
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=458272450">458272450</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/eharmony-online-dating-app/id458272450?uo=4">https://apps.apple.com/us/app/eharmony-online-dating-app/id458272450?uo=4</a>
**App Version:** 7.1.7
**Seller:** eHarmony.com
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/eharmony-com/id387084488?uo=4">© eHarmony.com</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/4d/8a/40/4d8a4038-c7f7-05ba-923e-0a9007b48314/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60389786-a4c4ac00-9ac8-11e9-975a-32d90540605b.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60389786-a4c4ac00-9ac8-11e9-975a-32d90540605b.png)
https://user-images.githubusercontent.com/2068130/60389786-a4c4ac00-9ac8-11e9-975a-32d90540605b.png
Source:
https://user-images.githubusercontent.com/2068130/60389794-b5752200-9ac8-11e9-97f2-89ef602b3d92.png
