### ISSUE TITLE
Xero

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#46]
**App Name:** Xero
**Bundle ID:** JEC2FK53N4.com.xero.XeroTouch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441880705">441880705</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xero/id441880705?mt=8&uo=4">https://itunes.apple.com/us/app/xero/id441880705?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** Xero Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/xero-ltd/id441878596?uo=4>© Xero Ltd</a>
**Supported Devices:** iPhone4S, iPadMini4G, iPadThirdGen4G, iPhone5, iPhone6, iPadThirdGen, iPad2Wifi, iPodTouchFifthGen, iPhone4, iPhone6Plus, iPhone5s, iPad23G, iPadFourthGen4G, iPhone5c, iPadFourthGen, iPadMini
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/0d/ee/39/0dee399f-3e2a-f594-b8a1-282880f8da3a/mzl.ypfezsac.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8522471/c4dcbcbc-23ee-11e5-83ac-3704a48dd540.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8522471/c4dcbcbc-23ee-11e5-83ac-3704a48dd540.png)
https://cloud.githubusercontent.com/assets/10730122/8522471/c4dcbcbc-23ee-11e5-83ac-3704a48dd540.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8522469/c1eece14-23ee-11e5-9c98-1a72dedbca08.png
