### ISSUE TITLE
Lost On Campus by StudentVIP

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#460]
**App Name:** Lost On Campus by StudentVIP
**Bundle ID:** com.student-services.lost-on-campus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=488598630">488598630</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lost-on-campus-by-studentvip/id488598630?mt=8&uo=4">https://itunes.apple.com/us/app/lost-on-campus-by-studentvip/id488598630?mt=8&uo=4</a>
**App Version:** 4.2.0
**Seller:** Student Services Australia Pty Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/student-services-australia/id488598633?uo=4">© Student Services Australia</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/02/65/1a/02651a82-d364-cae0-262a-47962f328d16/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688218-291fa210-c6cd-11e7-8b59-857c14043085.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32688218-291fa210-c6cd-11e7-8b59-857c14043085.png)
https://user-images.githubusercontent.com/2068130/32688218-291fa210-c6cd-11e7-8b59-857c14043085.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32688219-377fdbcc-c6cd-11e7-9f1d-7d863fbfcfa7.png
