### ISSUE TITLE
Fancy Wallpapers & Backgrounds

### ISSUE THREAD

**Issue by Geofferey** [glasklart/hd#4600]
**App Name:** Fancy Wallpapers & Backgrounds
**Bundle ID:** dk.bendingspoons.FancyLock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=789446892">789446892</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fancy-wallpapers-backgrounds/id789446892?uo=4">https://apps.apple.com/us/app/fancy-wallpapers-backgrounds/id789446892?uo=4</a>
**App Version:** 3.0.57
**Seller:** Bending Spoons Apps IVS
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bending-spoons-apps-ivs/id1280299077?uo=4">© Bending Spoons Apps IVS</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a7/cd/b1/a7cdb18a-6b99-ca6a-2ec2-7e751de13400/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60411685-30743080-9bce-11e9-9fb9-e9775b49c2e2.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60411685-30743080-9bce-11e9-9fb9-e9775b49c2e2.png)
https://user-images.githubusercontent.com/2068130/60411685-30743080-9bce-11e9-9fb9-e9775b49c2e2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60411694-3f5ae300-9bce-11e9-9629-b7aee3d76ab8.png
