### ISSUE TITLE
Google Home

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#4618]
**App Name:** Google Home
**Bundle ID:** com.google.Chromecast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=680819774">680819774</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-home/id680819774?mt=8&uo=4">https://itunes.apple.com/us/app/google-home/id680819774?mt=8&uo=4</a>
**App Version:** 1.19.1603
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/e6/5e/0d/e65e0d6e-87dc-cea9-9477-cf09c57a56ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19756500/6be86630-9c1d-11e6-8876-0f884982386d.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10271267/cd909234-6acf-11e5-80b2-03739644a60a.png)
https://cloud.githubusercontent.com/assets/3090247/10271267/cd909234-6acf-11e5-80b2-03739644a60a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10271268/cda909a4-6acf-11e5-9db8-54897c14523d.png

**Comment by l8er4now** [comment]
Needs an update. 

**App Name:** Google Home
**Bundle ID:** com.google.Chromecast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=680819774">680819774</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-home/id680819774?mt=8&uo=4">https://itunes.apple.com/us/app/google-home/id680819774?mt=8&uo=4</a>
**App Version:** 1.19.1603
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/e6/5e/0d/e65e0d6e-87dc-cea9-9477-cf09c57a56ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19756500/6be86630-9c1d-11e6-8876-0f884982386d.png)
https://cloud.githubusercontent.com/assets/20930745/19756500/6be86630-9c1d-11e6-8876-0f884982386d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19756507/7bbd78a2-9c1d-11e6-804d-28c1f1ba0bf2.png
