### ISSUE TITLE
Behance Display

### ISSUE THREAD

**Issue by klozecorus** [glasklart/hd#4627]
**App Name:** Behance Display
**Bundle ID:** com.behance.portfolio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=594579744">594579744</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/behance-display/id594579744?mt=8&uo=4">https://itunes.apple.com/us/app/behance-display/id594579744?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Behance LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/behance/id305796274?uo=4">© Behance</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/f9/6d/09/f96d0954-654e-deb9-bcca-d8241d0825b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626324-7e6b3880-a91a-11e8-8332-cf26f13332ed.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626324-7e6b3880-a91a-11e8-8332-cf26f13332ed.png)
https://user-images.githubusercontent.com/2068130/44626324-7e6b3880-a91a-11e8-8332-cf26f13332ed.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44626330-8dea8180-a91a-11e8-8ca5-64e44ccdddd2.png
