### ISSUE TITLE
Devil's Attorney

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#463]
**App Name:** Devil's Attorney
**Bundle ID:** com.senri.da
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=562772514">562772514</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/devils-attorney/id562772514?mt=8&uo=4">https://itunes.apple.com/us/app/devils-attorney/id562772514?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Anders Hejdenberg
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/1337-game-design-ab/id562772517?uo=4">© 1337 Game Design AB</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/27/e9/e2/27e9e248-9e2d-11a0-6099-a75248eb6d54/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32680980-97d03bc6-c66d-11e7-94cf-cf4fe1518bfb.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32680980-97d03bc6-c66d-11e7-94cf-cf4fe1518bfb.png)
https://user-images.githubusercontent.com/2068130/32680980-97d03bc6-c66d-11e7-94cf-cf4fe1518bfb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32680998-a70df6dc-c66d-11e7-9a07-c2ef85bae549.png
