### ISSUE TITLE
Alien Blue - reddit official client

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#4653]
**App Name:** Alien Blue - reddit official client
**Bundle ID:** com.reddit.alienblue
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923187241">923187241</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alien-blue-reddit-official/id923187241?mt=8&uo=4">https://itunes.apple.com/us/app/alien-blue-reddit-official/id923187241?mt=8&uo=4</a>
**App Version:** 2.9.1
**Seller:** REDDIT, INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/reddit/id808295587?uo=4>© reddit</a>
**Supported Devices:** iPhone5, iPadThirdGen, iPhone4S, iPadFourthGen, iPadThirdGen4G, iPadFourthGen4G, iPad2Wifi, iPadMini4G, iPodTouchFifthGen, iPadMini, iPad23G, iPhone4, iPhone5c, iPhone5s
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/10730122/16897613/0eca7aa8-4bb7-11e6-92bd-f7ea688248c3.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899797/eea84430-4c10-11e6-8a1d-26c5d3c2014b.png)

**Comment by Anuskuss** [comment]
@dreamnet Can you make the border just a tad bit thicker?

**Comment by Trubbel** [comment]
@Anuskuss They actually updated the artwork for this application before it was removed from the App Store.

**Old**                                  **New**
<img src="http://a583.phobos.apple.com/us/r30/Purple5/v4/48/70/d2/4870d2c5-1b74-90b0-ee24-f9a4e00d42ef/pr_source.png?downloadKey=1413457279_56182452c9595a7446d783f48c37a3fb" width="150" height="150" /> <img src="https://cloud.githubusercontent.com/assets/10730122/16897613/0eca7aa8-4bb7-11e6-92bd-f7ea688248c3.png" width="150" height="150" />

So we can either use the more recent artwork or change the old one to a thicker border.

**Comment by Anuskuss** [comment]
I'm so used to Alien Blue that I can't :smile: 
I didn't noticed the updated artwork since I don't update Alien Blue (the latest version was so buggy). So I'd say we (yeah you) create the latest one.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899797/eea84430-4c10-11e6-8a1d-26c5d3c2014b.png)
https://cloud.githubusercontent.com/assets/2068130/16899797/eea84430-4c10-11e6-8a1d-26c5d3c2014b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16899799/fda7e27e-4c10-11e6-97d5-88bdf52360f5.png

**Comment by Anuskuss** [comment]
@dreamnet Or invert? I mean I like it, but I want to see which looks better on my device.

**Comment by Anuskuss** [comment]
@dreamnet I think I might overstrain your nerves but I really like Glasklart and would like to be part of making it perfect.

**Comment by dreamnet** [comment]
@Anuskuss I appreciate that, but I can only spend about 4-5 hours a week to Glasklart. And at the moment, it seems that I am the last one who is doing some work here...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16967222/3d5dda60-4e08-11e6-82a1-550d9f68ccd8.png)
https://cloud.githubusercontent.com/assets/2068130/16967222/3d5dda60-4e08-11e6-82a1-550d9f68ccd8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16967232/4aea3548-4e08-11e6-8f90-163aba0be866.png
Looks bad to me... :thought_balloon:

**Comment by Anuskuss** [comment]
@dreamnet Thank you for taking the time to deal with my endless requests. I appreciated your work and with every step we take, we make sure that Glasklart is and will remain the best theme on Cydia.

Btw you were absolutely right. The non inverted version looks better (so sorry for wasting your time :disappointed:)
