### ISSUE TITLE
Pic Collage Maker PerfectImage

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#4665]
**App Name:** Pic Collage Maker PerfectImage
**Bundle ID:** iFocus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=464660903">464660903</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pic-collage-maker-perfectimage/id464660903?uo=4">https://apps.apple.com/us/app/pic-collage-maker-perfectimage/id464660903?uo=4</a>
**App Version:** 4.5.1
**Seller:** Hao Li
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tongshuo/id455501705?uo=4">© TongShuo</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/c0/3b/1f/c03b1fd6-7054-4fbb-4508-791114bbb7c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83335322-4392f300-a2ac-11ea-8cc3-cb17db7ded34.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83335322-4392f300-a2ac-11ea-8cc3-cb17db7ded34.png)
https://user-images.githubusercontent.com/2068130/83335322-4392f300-a2ac-11ea-8cc3-cb17db7ded34.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83335327-54dbff80-a2ac-11ea-89ee-03c93d9f2a55.png
