### ISSUE TITLE
Emoticons

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#467]
**App Name:** Emoticons
**Bundle ID:** com.trilliarden.emoticons
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=354870264">354870264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/emoticons/id354870264?mt=8&uo=4">https://itunes.apple.com/us/app/emoticons/id354870264?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Theodor Mueller
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/trilliarden/id305627633?uo=4">© Trilliarden</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/56/6a/a2/566aa2ff-0edb-c647-3a2a-751815651913/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25586912/e26d632a-2ea1-11e7-9056-3ccc8ab92e10.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25586912/e26d632a-2ea1-11e7-9056-3ccc8ab92e10.png)
https://cloud.githubusercontent.com/assets/2068130/25586912/e26d632a-2ea1-11e7-9056-3ccc8ab92e10.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25586922/f1110cba-2ea1-11e7-95d3-251578bae0b3.png
