### ISSUE TITLE
Heapo - Copy, Paste & Sync Clipboard with iOS8 widget & Google Chrome Extension

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#4680]
**App Name:** Heapo Clipboard Management Widget - an universal copy and paste app to access your clips from anywhere
**Bundle ID:** com.booltinteam.heap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=921961118">921961118</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/heapo-clipboard-management/id921961118?mt=8&uo=4">https://itunes.apple.com/us/app/heapo-clipboard-management/id921961118?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Mohammad Khoman
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mohammad-khoman/id921961117?uo=4>© Mohammad Khoman</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/d7/04/9c/d7049c16-1c93-c7e7-19ad-cc1efdc9c9fa/mzl.vfkvkhcx.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10857950/90d0a406-7f51-11e5-82da-f304d50be673.png)

**Comment by l8er4now** [comment]
Could use an updated icon.

**App Name:** Heapo Clipboard Management Widget - an universal copy and paste app to access your clips from anywhere
**Bundle ID:** com.booltinteam.heap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=921961118">921961118</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/heapo-clipboard-management/id921961118?mt=8&uo=4">https://itunes.apple.com/us/app/heapo-clipboard-management/id921961118?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Mohammad Khoman
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mohammad-khoman/id921961117?uo=4>© Mohammad Khoman</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/d7/04/9c/d7049c16-1c93-c7e7-19ad-cc1efdc9c9fa/mzl.vfkvkhcx.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10857950/90d0a406-7f51-11e5-82da-f304d50be673.png)
https://cloud.githubusercontent.com/assets/2068130/10857950/90d0a406-7f51-11e5-82da-f304d50be673.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10857955/a01b528a-7f51-11e5-9c76-9eaca7bdedf7.png
