### ISSUE TITLE
Pangu

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#4683]
**App Name:** Pangu
**Bundle ID('s):**
`io.pangu.loader`
`io.pangu.nvwastone`
`com.e4bf058461-1-42`
`com.wanmei.mini.condorpp-532-8`
**App Version:** 1.1.0
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/4871113/32f9c2e4-619e-11e4-9c4d-616515823c0f.png" width="180" height="180" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18807470/5c0af3a2-8248-11e6-803b-d55d2c915593.png)

**Comment by boxermansr** [comment]
Any chance to get this updated for the new iOS 9 Pangu jailbreak? I know there are probably two different "icon" versions (one for the English release, and one for the Chinese/PP).
Thanks.

**Comment by ivanov007** [comment]
well my PP icon (chinese version) is theming with the bundleid `com.e4bf058461-1-42`, but I don't know if this name is based on the certificate, @boxermansr do you have the chinese jailbreak? can you check appster to see if it's the same identifier?

**Comment by boxermansr** [comment]
I'm actually using the English one that you drag into Saurik's Cydia Impactor too. Was a bit weary about the Chinese version :/

**Comment by ivanov007** [comment]
ok, so maybe someone can confirmm and we can theme all 9.x and 8.x with the same icon

**Comment by CouleeApps** [comment]
iOS 9.3.3: My bundle identifier is also `com.e4bf058461-1-42`.

**Comment by dreamnet** [comment]
iOS 9.3.3, iPad Pro: Also `com.e4bf058461-1-42`.

**Comment by boxermansr** [comment]
Mine is io.pangu.nvwastone

**Comment by ivanov007** [comment]
this looks weird on 5.00, I guess it still has the baseplate?

**Comment by dreamnet** [comment]
@ivanov007 Ähhh... [no](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/io.pangu.loader-large.png).

**Comment by ivanov007** [comment]
Then something is happening because it looks different from the others

**Comment by dreamnet** [comment]
@ivanov007 Do you have a screenshot?

**Comment by ivanov007** [comment]
yeah sorry it seems it was stripped from my mail
![image1](https://cloud.githubusercontent.com/assets/3090247/18766938/3bcf07a2-80e2-11e6-8965-1b4c9eea0c14.PNG)

**Comment by dreamnet** [comment]
@ivanov007 That's strange. Try to uninstall Glasklart, go to Library/Themes and delete all maybe left "Glasklart" folders and reinstall Glasklart from Cydia.
Also try to use iCleaner. No other idea.

**Comment by grkka** [comment]
@ivanov007 porque se ve el icono de Activator de ese modo? Yo ahora he eliminado el fondo "blur" de las carpetas con el tweak "NoBlur" y mira como se ve el icono de Activator
![asset](https://cloud.githubusercontent.com/assets/14794477/18767406/3bbf172e-811f-11e6-8154-51e9ba02bc14.PNG)

**Comment by dreamnet** [comment]
@grkka I dont speak spanish, but this is completly off-topic. Read [here](https://github.com/glasklart/hd/issues/58).

**Comment by grkka** [comment]
@dreamnet Thanks! You are in everything.

**Comment by quantum8** [comment]
Looks like there may be quite a few different bundle names. I've got the english version with the 12 month cert have the bundle ID as com.wanmei.mini.condorpp-532-8

**Comment by dreamnet** [comment]
OK, normally I don't do this, but I'm going to add this icon with all (so far) known bundle ID's. Else this issue would stay open forever...
