### ISSUE TITLE
Letterpress – Word Game

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#469]
**App Name:** Letterpress – Word Game
**Bundle ID:** com.atebits.ios.Letterpress
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526619424">526619424</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/letterpress-word-game/id526619424?mt=8&uo=4">https://itunes.apple.com/us/app/letterpress-word-game/id526619424?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Solebon LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/solebon-llc/id836906903?uo=4>© Solebon LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/d8/cb/a5/d8cba5b4-21e7-5e29-2f3c-89d1b90da211/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19400657/71fc3418-9257-11e6-8543-6c554a408733.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19400657/71fc3418-9257-11e6-8543-6c554a408733.png)
https://cloud.githubusercontent.com/assets/20930745/19400657/71fc3418-9257-11e6-8543-6c554a408733.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19400668/80246844-9257-11e6-849c-a968b24b42d8.png
