### ISSUE TITLE
CTV News

### ISSUE THREAD

**Issue by ali-1991** [glasklart/hd#4695]
**App Name:** CTV News
**Bundle ID:** com.indusblue.ctvn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427789951">427789951</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ctv-news/id427789951?uo=4">https://apps.apple.com/us/app/ctv-news/id427789951?uo=4</a>
**App Version:** 7.0.1
**Seller:** Bell Media Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bell-media-inc/id328082347?uo=4">© Bell Media Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/35/8f/a2/358fa2e3-44a4-90d4-8763-fbfb1f2c6a77/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60372543-349d2400-99fd-11e9-8341-8f852da2bb82.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60372543-349d2400-99fd-11e9-8341-8f852da2bb82.png)
https://user-images.githubusercontent.com/20930745/60372543-349d2400-99fd-11e9-8341-8f852da2bb82.png

Source:
https://user-images.githubusercontent.com/20930745/60372546-3666e780-99fd-11e9-8e53-cabc00ae0a9d.png
