### ISSUE TITLE
Whisper - Share, Express, Meet

### ISSUE THREAD

**Issue by ali-1991** [glasklart/hd#4697]
**App Name:** Whisper - Share, Express, Meet
**Bundle ID:** sh.whisper.whisperapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506141837">506141837</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/whisper-share-express-meet/id506141837?mt=8&uo=4">https://itunes.apple.com/us/app/whisper-share-express-meet/id506141837?mt=8&uo=4</a>
**App Version:** 4.3.3
**Seller:** WhisperText LLC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/whispertext-llc./id506141840?uo=4>© WhisperText LLC.</a>
**Supported Devices:** iPhone4S, iPad2Wifi, iPadFourthGen4G, iPodTouchFifthGen, iPadMini4G, iPadThirdGen, iPhone4, iPad23G, iPhone5, iPadFourthGen, iPadThirdGen4G, iPadMini, iPhone5c, iPhone5s
**Original Artwork:**
<img src="http://a243.phobos.apple.com/us/r30/Purple1/v4/4f/08/19/4f081994-e4c0-62d5-bca5-9f2a3c3be5f8/mzl.ushtenux.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/4909600/ed6fdbee-6474-11e4-8c35-abac8f0d7ea5.png)

**Comment by quantum8** [comment]
Anyone having any issues getting this app to show properly? I've tried respringing/restarting, and the file looks to be in the right place in ifile...

**Comment by Trubbel** [comment]
@quantum8 I just downloaded the application and it seems to work for me. Have you tried reinstalling?

**Comment by quantum8** [comment]
@trubbel, Finally got around to reinstalling glasklart. Same deal, it's strange.

**Comment by dreamnet** [comment]
Also installed it and the app icon is themed normally on my device (iPhone 6, iOS 8.3, Glasklart 4.24.1). @quantum8 Can't imagine what's going wrong - can you please post a screenshot?
Anyone else having problems with this icon?

**Comment by Trubbel** [comment]
@dreamnet, @quantum8 I checked again and it's themed for me as well. (iPhone 6 Plus, 8.4, Glasklart 4.24.1)

Reinstalling the application itself didn't help either?

**Comment by dreamnet** [comment]
@quantum8 Can you please post the content of the `Info.plist` of the app?

**Comment by ivanov007** [comment]
it's themed for me too (iPhone 5, 8.4, Glasklart 4.24.1)

**Comment by quantum8** [comment]
@dreamnet was on the money here, checked the itunes ID and I had the Australian one even though I used my US account. Renamed the icon name in ifile and it worked.

I've submitted a new issue for it [here] (https://github.com/glasklart/hd/issues/6386).

**Comment by dreamnet** [comment]
Ahhhhhh... solved. :laughing:
