### ISSUE TITLE
Weather Neue

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#47]
**App Name:** Weather Neue
**Bundle ID:** com.switch.weatherneue
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527856624">527856624</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-neue/id527856624?mt=8&uo=4">https://itunes.apple.com/us/app/weather-neue/id527856624?mt=8&uo=4</a>
**App Version:** 1.08
**Seller:** Switch Soft Technologies Pvt Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/switch-soft-technologies-pvt/id506649855?uo=4">© Switch Soft Technologies Pvt Ltd</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple2/v4/e3/25/8c/e3258c2f-65d8-a271-9026-66ba0a6c3eae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20110083/364ce4c2-a5e3-11e6-8748-24d31d2f33df.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20110083/364ce4c2-a5e3-11e6-8748-24d31d2f33df.png)
https://cloud.githubusercontent.com/assets/20930745/20110083/364ce4c2-a5e3-11e6-8748-24d31d2f33df.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20110105/4bff4026-a5e3-11e6-9632-26bbc913e0e3.png
