### ISSUE TITLE
Microsoft Word

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#4701]
**App Name:** Microsoft Word
**Bundle ID:** com.microsoft.Office.Word
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586447913">586447913</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-word/id586447913?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-word/id586447913?mt=8&uo=4</a>
**App Version:** 2.25
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?mt=8&uo=4">© Microsoft Corporation</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/ff/ff/28/ffff28c2-56e2-55c2-c950-e708d741af8b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com microsoft Office Word-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58776948-8bfdcf00-85cc-11e9-8d39-4670a31243ec.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58765418-30ebbe00-8573-11e9-9292-6f5fbfa66bed.png)
https://user-images.githubusercontent.com/20930745/58765418-30ebbe00-8573-11e9-9292-6f5fbfa66bed.png

Source:
https://user-images.githubusercontent.com/20930745/58765416-2f21fa80-8573-11e9-8e77-3f1b756b52f5.png

**Comment by dreamnet** [comment]
![com microsoft Office Word-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58776948-8bfdcf00-85cc-11e9-8d39-4670a31243ec.png)
https://user-images.githubusercontent.com/2068130/58776948-8bfdcf00-85cc-11e9-8d39-4670a31243ec.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58777020-9a4beb00-85cc-11e9-8a9c-b60a328e3eac.png
