### ISSUE TITLE
Microsoft Excel

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#4702]
**App Name:** Microsoft Excel
**Bundle ID:** com.microsoft.Office.Excel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586683407">586683407</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-excel/id586683407?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-excel/id586683407?mt=8&uo=4</a>
**App Version:** 2.25
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?mt=8&uo=4">© Microsoft Corporation</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/69/d4/19/69d419d5-d3b8-ab78-1963-5f696019676d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com microsoft Office Excel-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58777057-bf405e00-85cc-11e9-9aca-e5a0ac597471.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58765815-29c6af00-8577-11e9-8cd7-a72148fec5fd.png)
https://user-images.githubusercontent.com/20930745/58765815-29c6af00-8577-11e9-8cd7-a72148fec5fd.png

Source:
https://user-images.githubusercontent.com/20930745/58765821-2e8b6300-8577-11e9-9c69-3d322451e37f.png

**Comment by dreamnet** [comment]
![com microsoft Office Excel-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58777057-bf405e00-85cc-11e9-9aca-e5a0ac597471.png)
https://user-images.githubusercontent.com/2068130/58777057-bf405e00-85cc-11e9-9aca-e5a0ac597471.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58777067-cebfa700-85cc-11e9-9aeb-bb3273c7401e.png
