### ISSUE TITLE
Microsoft PowerPoint

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#4703]
**App Name:** Microsoft PowerPoint
**Bundle ID:** com.microsoft.Office.Powerpoint
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586449534">586449534</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-powerpoint/id586449534?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-powerpoint/id586449534?mt=8&uo=4</a>
**App Version:** 2.25
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?mt=8&uo=4">© Microsoft Corporation</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/46/55/a2/4655a2f6-89ee-ff04-4750-c993daa5a395/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com microsoft Office Powerpoint-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58777090-ec8d0c00-85cc-11e9-9b05-686bf45b0d25.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58765670-8f19a080-8575-11e9-9a81-e649a9c2ba79.png)
https://user-images.githubusercontent.com/20930745/58765670-8f19a080-8575-11e9-9a81-e649a9c2ba79.png

Source:
https://user-images.githubusercontent.com/20930745/58765672-92149100-8575-11e9-9200-75937d2ffb8b.png

**Comment by dreamnet** [comment]
![com microsoft Office Powerpoint-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58777090-ec8d0c00-85cc-11e9-9b05-686bf45b0d25.png)
https://user-images.githubusercontent.com/2068130/58777090-ec8d0c00-85cc-11e9-9b05-686bf45b0d25.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58777110-fadb2800-85cc-11e9-99e4-709369ecdce4.png
