### ISSUE TITLE
Billionaire – Business Capitalist Tycoon!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#4709]
**App Name:** Billionaire – Business Capitalist Tycoon!
**Bundle ID:** com.alegrium.billionaire
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=881342787">881342787</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/billionaire-business-capitalist/id881342787?mt=8&uo=4">https://itunes.apple.com/us/app/billionaire-business-capitalist/id881342787?mt=8&uo=4</a>
**App Version:** 1.8.0
**Seller:** indra budiman
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alegrium/id424474164?uo=4>© Alegrium</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/14/e9/07/14e9078f-34e4-d91f-c706-d1699b556e91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19012673/ec73a56e-87bc-11e6-8a67-416fe4a64c37.png)

**Comment by Anuskuss** [comment]
Needs update.

**Comment by dreamnet** [comment]
Can't do the original...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19012673/ec73a56e-87bc-11e6-8a67-416fe4a64c37.png)
https://cloud.githubusercontent.com/assets/2068130/19012673/ec73a56e-87bc-11e6-8a67-416fe4a64c37.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19012682/fa9782be-87bc-11e6-9d9c-b76df214968e.png
