### ISSUE TITLE
10000000

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#471]
**App Name:** 10000000
**Bundle ID:** com.eightyeightgames.soletest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=544385071">544385071</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/10000000/id544385071?mt=8&uo=4">https://itunes.apple.com/us/app/10000000/id544385071?mt=8&uo=4</a>
**App Version:** 1.6.1
**Seller:** EightyEight Games LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/eightyeight-games-ltd/id421396889?uo=4">© EightyEight Games LTD</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/6f/5b/59/6f5b5900-ecc0-8dd7-3919-0710336d8edf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19957889/d220044e-a19a-11e6-8b74-0a4638a5588c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19957889/d220044e-a19a-11e6-8b74-0a4638a5588c.png)
https://cloud.githubusercontent.com/assets/20930745/19957889/d220044e-a19a-11e6-8b74-0a4638a5588c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19957894/e5105e5a-a19a-11e6-9b16-75f3ea46c2db.png
