### ISSUE TITLE
Assassin’s Creed - Identity

### ISSUE THREAD

**Issue by lollan85** [glasklart/hd#4713]
**App Name:** Assassin’s Creed - Identity
**Bundle ID:** com.ubisoft.assassin.identity
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=880971164">880971164</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/assassins-creed-identity/id880971164?mt=8&uo=4">https://itunes.apple.com/au/app/assassins-creed-identity/id880971164?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Ubisoft
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/artist/ubisoft/id317644720?uo=4>© Ubisoft</a>
**Supported Devices:** iPad2Wifi, iPadFourthGen4G, iPhone4, iPad23G, iPadMini, iPadThirdGen4G, iPhone5, iPhone5c, iPhone4S, iPodTouchFifthGen, iPhone5s, iPadThirdGen, iPadMini4G, iPadFourthGen
**Original Artwork:**
<img src="http://a1899.phobos.apple.com/us/r30/Purple4/v4/04/c9/14/04c91439-c6de-2463-8d0f-be2e3013e9e1/pr_source.png?downloadKey=1415556768_24834768c41d559eeb2b7d6a70042c94" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5052824/7baa8f54-6c44-11e4-9f0f-f209a2972a10.png)

**Comment by Anuskuss** [comment]
@dreamnet I know this icon may was hard to create, but it has changed :worried: 
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/c7/ea/11/c7ea1124-6f2d-8fd4-463d-969d1a5a54c1/source/1024x1024bb.png" width="150" height="150" />

**Comment by ivanov007** [comment]
is a very small change, I don't think it worth the time, but is up to @dreamnet

**Comment by dreamnet** [comment]
Hmm... no. I like it as it is.

**Comment by Anuskuss** [comment]
How about the new one?

**Comment by ivanov007** [comment]
same thing, not worth it
