### ISSUE TITLE
PlayerXtreme Media Player

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4715]
**App Name:** PlayerXtreme Media Player
**Bundle ID:** com.pentaloop.playerxipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=456584471">456584471</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/playerxtreme-media-player/id456584471?mt=8&uo=4">https://itunes.apple.com/us/app/playerxtreme-media-player/id456584471?mt=8&uo=4</a>
**App Version:** 7.3.3
**Seller:** Xtreme Media Works
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/xtreme-media-works/id1086518850?uo=4">© Xtreme Media Works</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/fc/1e/15/fc1e153d-c912-c11a-4b05-07ab3dd1791d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32175514-7ba3a712-bd85-11e7-860d-969bccad12b4.png)

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8.
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32175514-7ba3a712-bd85-11e7-860d-969bccad12b4.png)
https://user-images.githubusercontent.com/20930745/32175514-7ba3a712-bd85-11e7-860d-969bccad12b4.png
--- ---
Source:
https://user-images.githubusercontent.com/20930745/32175532-8bfe57c4-bd85-11e7-915a-b7edd5b77d27.png
