### ISSUE TITLE
MyFRITZ!App

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4716]
**App Name:** MyFRITZ!App
**Bundle ID:** de.avm.MyFRITZ
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=620435371">620435371</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myfritz-app/id620435371?uo=4">https://apps.apple.com/us/app/myfritz-app/id620435371?uo=4</a>
**App Version:** 2.0.3
**Seller:** AVM GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/avm-gmbh/id372184478?uo=4">© AVM GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/03/4a/9c/034a9c3f-fb22-c38d-d608-e1d9481190a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60396132-d75cbc00-9b3d-11e9-9ac3-ef070126a6c7.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60396132-d75cbc00-9b3d-11e9-9ac3-ef070126a6c7.png)
https://user-images.githubusercontent.com/2068130/60396132-d75cbc00-9b3d-11e9-9ac3-ef070126a6c7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60396137-e5aad800-9b3d-11e9-8121-d37a06471566.png
