### ISSUE TITLE
Songify by Smule

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#472]
**App Name:** Songify by Smule
**Bundle ID:** sh.khu.songify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438735719">438735719</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/songify-by-smule/id438735719?mt=8&uo=4">https://itunes.apple.com/us/app/songify-by-smule/id438735719?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** Smule
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/smule/id290596339?mt=8&uo=4>© Smule</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/0e/dd/2e/0edd2e42-47a4-7b1b-c007-becceabb7820/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408655/131a7e52-92c3-11e6-8b8a-8524814bd0f7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408655/131a7e52-92c3-11e6-8b8a-8524814bd0f7.png)
https://cloud.githubusercontent.com/assets/20930745/19408655/131a7e52-92c3-11e6-8b8a-8524814bd0f7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19408663/21d5c924-92c3-11e6-9577-d4c48b8f616f.png
