### ISSUE TITLE
Age of Zombies™

### ISSUE THREAD

**Issue by cr0w-69** [glasklart/hd#4727]
**App Name:** Age of Zombies™
**Bundle ID:** com.halfbrick.AoZ
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395627741">395627741</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/age-of-zombies/id395627741?mt=8&uo=4">https://itunes.apple.com/us/app/age-of-zombies/id395627741?mt=8&uo=4</a>
**App Version:** 1.2.81
**Seller:** Halfbrick
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/halfbrick-studios/id356994313?uo=4>© Halfbrick Studios</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/29/5b/23/295b2305-cb35-fc35-e0c2-3692ea8404a0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15055722/6f8d0a4a-130e-11e6-99d2-a3391555002a.png)

**Comment by Anuskuss** [comment]
Needs update.
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/29/5b/23/295b2305-cb35-fc35-e0c2-3692ea8404a0/source/1024x1024bb.png" width="150" height="150" />

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15055722/6f8d0a4a-130e-11e6-99d2-a3391555002a.png)
https://cloud.githubusercontent.com/assets/2068130/15055722/6f8d0a4a-130e-11e6-99d2-a3391555002a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15055742/81599950-130e-11e6-93e1-59b8ec417c08.png
Omg... hard one.
