### ISSUE TITLE
Google Street View

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#4729]
**App Name:** Google Street View
**Bundle ID:** com.google.LightCycle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=904418768">904418768</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-street-view/id904418768?mt=8&uo=4">https://itunes.apple.com/us/app/google-street-view/id904418768?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/35/d1/41/35d1414e-b9a7-1612-09c3-489d34b8f516/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10358585/226c89da-6d90-11e5-8221-349c7e15703d.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10358585/226c89da-6d90-11e5-8221-349c7e15703d.png)
https://cloud.githubusercontent.com/assets/2068130/10358585/226c89da-6d90-11e5-8221-349c7e15703d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10358587/30afb6c0-6d90-11e5-918a-9753e7f3a998.png
