### ISSUE TITLE
300! | AmbiScience™ :: White Noise, Brainwaves, Relaxing Music and Sound Effects!

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#473]
**App Name:** 300! | AmbiScience™ :: White Noise, Brainwaves, Relaxing Music and Sound Effects!
**Bundle ID:** com.teslasoftware.AmbiSci300
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547484593">547484593</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/300-ambiscience-white-noise-brainwaves-relaxing-music/id547484593?mt=8&uo=4">https://itunes.apple.com/us/app/300-ambiscience-white-noise-brainwaves-relaxing-music/id547484593?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Tesla Software, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tesla-audio-sciences/id300108407?uo=4">© Tesla Audio Sciences</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/bd/f7/ea/bdf7eacd-a2c3-7790-183d-23e94f84bef4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38782030-e9b65bd2-40ed-11e8-8b30-bedb5c92aed2.png)

**Comment by Christian9901** [comment]
**App Name:** 300! | AmbiScience™ :: White Noise, Brainwaves, Relaxing Music and Sound Effects!
**Bundle ID:** com.teslasoftware.AmbiSci300
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547484593">547484593</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/300-ambiscience-white-noise-brainwaves-relaxing-music/id547484593?mt=8&uo=4">https://itunes.apple.com/us/app/300-ambiscience-white-noise-brainwaves-relaxing-music/id547484593?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Tesla Software, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tesla-audio-sciences/id300108407?uo=4">© Tesla Audio Sciences</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/bd/f7/ea/bdf7eacd-a2c3-7790-183d-23e94f84bef4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38782030-e9b65bd2-40ed-11e8-8b30-bedb5c92aed2.png)
https://user-images.githubusercontent.com/2068130/38782030-e9b65bd2-40ed-11e8-8b30-bedb5c92aed2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38782035-fa22efee-40ed-11e8-9199-9ae751c5c365.png
