### ISSUE TITLE
Vainglory for iPhone

### ISSUE THREAD

**Issue by lollan85** [glasklart/hd#4730]
**App Name:** Vainglory for iPhone
**Bundle ID:** com.superevilmegacorp.vainglory.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935032373">935032373</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/vainglory-for-iphone/id935032373?mt=8&uo=4">https://itunes.apple.com/gb/app/vainglory-for-iphone/id935032373?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** Super Evil Mega Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/artist/super-evil-megacorp/id671464707?uo=4>© Super Evil Megacorp</a>
**Supported Devices:** iPhone5s
**Original Artwork:**
<img src="http://a65.phobos.apple.com/us/r30/Purple3/v4/3f/d5/74/3fd57474-ca2e-416e-cc6e-e0716259d402/mzl.pekhrpgw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5051927/27ccdf48-6c3c-11e4-820f-5cf83624d773.png)

**Comment by dreamnet** [comment]
App dosen't seem to exist anymore - removing.
