### ISSUE TITLE
Handelsbanken SE – Privat

### ISSUE THREAD

**Issue by raptorjr** [glasklart/hd#4732]
**App Name:** Handelsbanken SE – Privat
**Bundle ID:** se.handelsbanken.TelesvarIBilder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378393286">378393286</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/handelsbanken-se-privat/id378393286?uo=4">https://apps.apple.com/us/app/handelsbanken-se-privat/id378393286?uo=4</a>
**App Version:** 9.3.0
**Seller:** Svenska Handelsbanken AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/svenska-handelsbanken-publ/id378075618?uo=4">© Svenska Handelsbanken (publ)</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/ed/f6/5a/edf65a18-d248-e82b-0510-828a4c17bd65/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60773181-153f7e80-a102-11e9-92dc-247c42da6079.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60773181-153f7e80-a102-11e9-92dc-247c42da6079.png)
https://user-images.githubusercontent.com/2068130/60773181-153f7e80-a102-11e9-92dc-247c42da6079.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60773184-24bec780-a102-11e9-9007-a533596b63f6.png
