### ISSUE TITLE
ABC iview

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#4737]
**App Name:** ABC iview
**Bundle ID:** au.net.abc.ABCiView
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401778175">401778175</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/abc-iview/id401778175?mt=8&uo=4">https://itunes.apple.com/au/app/abc-iview/id401778175?mt=8&uo=4</a>
**App Version:** 3.20
**Seller:** Australian Broadcasting Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/au/developer/australian-broadcasting-corporation/id306583232?uo=4">© Australian Broadcasting Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/79/93/0f/79930fe1-438b-a425-8583-5346cd57339b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455347-3624cb8e-3a77-11e8-829e-6c583ec4e312.png)

**Comment by dreamnet** [comment]
Icon needs an update.
