### ISSUE TITLE
Files Pro : Document Viewer

### ISSUE THREAD

**Issue by splitsskulls** [glasklart/hd#4752]
**App Name:** Files Pro : Document Viewer
**Bundle ID:** com.olivetoast.files
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=285578660">285578660</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/files-pro-document-viewer/id285578660?uo=4">https://apps.apple.com/us/app/files-pro-document-viewer/id285578660?uo=4</a>
**App Version:** 2.3.1
**Seller:** Olive Toast Software Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/olive-toast-software-ltd/id285578663?uo=4">© Olive Toast Software Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/2a/81/b5/2a81b581-93cd-5ddb-601f-05f312ce4746/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400637-ddbb5a00-9b76-11e9-84ae-5702deebcd6f.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400637-ddbb5a00-9b76-11e9-84ae-5702deebcd6f.png)
https://user-images.githubusercontent.com/20930745/60400637-ddbb5a00-9b76-11e9-84ae-5702deebcd6f.png

Source:
https://user-images.githubusercontent.com/20930745/60400640-e0b64a80-9b76-11e9-936c-48eb4751ff43.png
