### ISSUE TITLE
CarTunes Music Player

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#476]
**App Name:** CarTunes Music Player
**Bundle ID:** com.NickAndRyan.eyeDrive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=415408192">415408192</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cartunes-music-player/id415408192?mt=8&uo=4">https://itunes.apple.com/us/app/cartunes-music-player/id415408192?mt=8&uo=4</a>
**App Version:** 6.3.1
**Seller:** Ryan Oksenhorn
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ryan-oksenhorn/id366196417?uo=4">© Ryan Oksenhorn</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/e0/99/9c/e0999c2e-97dc-b5d6-8b68-c9fc69dde4a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19957767/e5d8ca08-a199-11e6-9115-87dae3c434fb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19957767/e5d8ca08-a199-11e6-9115-87dae3c434fb.png)
https://cloud.githubusercontent.com/assets/20930745/19957767/e5d8ca08-a199-11e6-9115-87dae3c434fb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19957777/fdd1f5da-a199-11e6-89b6-297ed034a8e6.png
