### ISSUE TITLE
SwiftKey Keyboard

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#4766]
**App Name:** SwiftKey Keyboard
**Bundle ID:** com.swiftkey.SwiftKeyApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911813648">911813648</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/swiftkey-keyboard/id911813648?uo=4">https://apps.apple.com/us/app/swiftkey-keyboard/id911813648?uo=4</a>
**App Version:** 2.5.4
**Seller:** TouchType Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/swiftkey/id773299904?uo=4">© SwiftKey</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/0a/48/8b/0a488b47-f0e9-f89f-dbd7-a880f7818672/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61992002-a72f0d00-b058-11e9-8b7e-863475a84d35.png)

**Comment by XPEric** [comment]
Needs update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61991986-718a2400-b058-11e9-8e19-5e125ef70fb7.png)
https://user-images.githubusercontent.com/2068130/61991986-718a2400-b058-11e9-8e19-5e125ef70fb7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/61991992-8070d680-b058-11e9-84ee-37d2eb5bcfcf.png
