### ISSUE TITLE
Squarespace Note

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#477]
**App Name:** Squarespace Note
**Bundle ID:** com.squarespace.note
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561237934">561237934</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/squarespace-note/id561237934?mt=8&uo=4">https://itunes.apple.com/us/app/squarespace-note/id561237934?mt=8&uo=4</a>
**App Version:** 2.0.7
**Seller:** Squarespace, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/squarespace-inc./id318590877?uo=4">© Squarespace, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/09/9a/0b/099a0bd9-d3bf-34e8-ae0c-028ebc8789b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19957696/39a68022-a199-11e6-9376-c9b139d05000.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19957696/39a68022-a199-11e6-9376-c9b139d05000.png)
https://cloud.githubusercontent.com/assets/20930745/19957696/39a68022-a199-11e6-9376-c9b139d05000.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19957704/4f05e53e-a199-11e6-9c8d-2a11d4664d9e.png
