### ISSUE TITLE
ProCamera.

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#4779]
**App Name:** ProCamera.
**Bundle ID:** com.cocologics.ProCamera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=694647259">694647259</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/procamera/id694647259?uo=4">https://apps.apple.com/us/app/procamera/id694647259?uo=4</a>
**App Version:** 13.1.1
**Seller:** Cocologics GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cocologics/id490969165?uo=4">© Cocologics</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/e1/ff/26/e1ff265e-d14c-c1c9-9d28-27ff2488189d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67159922-49eee300-f34b-11e9-9063-e7ef6df0f2bb.png)

**Comment by Gwai** [comment]
Can you please update the icon?

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67159922-49eee300-f34b-11e9-9063-e7ef6df0f2bb.png)
https://user-images.githubusercontent.com/20930745/67159922-49eee300-f34b-11e9-9063-e7ef6df0f2bb.png

Source:
![procamera](https://user-images.githubusercontent.com/20930745/67159923-4b201000-f34b-11e9-83fc-3617d25cb561.png)
