### ISSUE TITLE
StockTouch

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#478]
**App Name:** StockTouch
**Bundle ID:** com.stocktouch.stocktouch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445170859">445170859</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stocktouch/id445170859?mt=8&uo=4">https://itunes.apple.com/us/app/stocktouch/id445170859?mt=8&uo=4</a>
**App Version:** 5.4
**Seller:** Related Market LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/visible-market-inc./id445170862?uo=4>© Visible Market Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/e2/39/86/e2398672-a0fc-b62b-93b8-31c89b992896/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19006416/9debbe98-875f-11e6-9167-8ac9e36c4121.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** StockTouch
**Bundle ID:** com.stocktouch.stocktouch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445170859">445170859</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stocktouch/id445170859?mt=8&uo=4">https://itunes.apple.com/us/app/stocktouch/id445170859?mt=8&uo=4</a>
**App Version:** 5.4
**Seller:** Related Market LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/visible-market-inc./id445170862?uo=4>© Visible Market Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/e2/39/86/e2398672-a0fc-b62b-93b8-31c89b992896/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19006416/9debbe98-875f-11e6-9167-8ac9e36c4121.png)
https://cloud.githubusercontent.com/assets/20930745/19006416/9debbe98-875f-11e6-9167-8ac9e36c4121.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19006426/ae90fa38-875f-11e6-8f0f-9d432eb6c70d.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Jup. 👍
