### ISSUE TITLE
iA Writer

### ISSUE THREAD

**Issue by crecentmoons** [glasklart/hd#4783]
**App Name:** iA Writer
**Bundle ID:** pro.writer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=775737172">775737172</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ia-writer/id775737172?mt=8&uo=4">https://itunes.apple.com/us/app/ia-writer/id775737172?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** iA Labs GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ia-labs-gmbh/id775737175?uo=4>© iA Labs GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/1b/6c/75/1b6c7599-e391-1e2c-dc18-1a91e61dbe8f/mzl.arvfxbwu.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270015/e7d9d630-6ae5-11e5-9dea-9ce0178d7d15.png)

**Comment by dreamnet** [comment]
Updating icon:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270015/e7d9d630-6ae5-11e5-9dea-9ce0178d7d15.png)
https://cloud.githubusercontent.com/assets/2068130/10270015/e7d9d630-6ae5-11e5-9dea-9ce0178d7d15.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10270018/f6a50cfc-6ae5-11e5-8e3d-4cca53012de8.png
