### ISSUE TITLE
Hearthstone: Heroes of Warcraft

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#4799]
**App Name:** Hearthstone: Heroes of Warcraft
**Bundle ID:** com.blizzard.wtcg.hearthstone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=625257520">625257520</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hearthstone-heroes-warcraft/id625257520?mt=8&uo=4">https://itunes.apple.com/us/app/hearthstone-heroes-warcraft/id625257520?mt=8&uo=4</a>
**App Version:** 2.5.8416
**Seller:** Blizzard Entertainment, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/blizzard-entertainment-inc./id306862900?uo=4>© Blizzard Entertainment, Inc.</a>
**Supported Devices:** iPadThirdGen, iPadMini4G, iPadFourthGen4G, iPhone6, iPodTouchFourthGen, iPadThirdGen4G, iPhone5c, iPad23G, iPadFourthGen, iPodTouchThirdGen, iPhone5s, iPad2Wifi, iPhone6Plus, iPodTouchFifthGen, iPad3G, iPadMini, iPadWifi, iPhone4S, iPhone-3GS, iPhone5, iPhone4
**Original Artwork:**
<img src="http://a1818.phobos.apple.com/us/r30/Purple3/v4/b8/b5/20/b8b5201a-eade-6c21-05b8-12384e39b070/mzl.cwyjzhpr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7210252/9ed12d50-e550-11e4-8d6b-43f29c3aeff2.png)

**Comment by dreamnet** [comment]
This is also for iPhone now. Re-opening.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7210252/9ed12d50-e550-11e4-8d6b-43f29c3aeff2.png)
https://cloud.githubusercontent.com/assets/2068130/7210252/9ed12d50-e550-11e4-8d6b-43f29c3aeff2.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7210258/ae569846-e550-11e4-8feb-fc043feaf8d9.png
