### ISSUE TITLE
Ticketleap

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#48]
**App Name:** Ticketleap
**Bundle ID:** com.ticketleap.iosApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=468457026">468457026</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ticketleap/id468457026?mt=8&uo=4">https://itunes.apple.com/us/app/ticketleap/id468457026?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** TicketLeap, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ticketleap/id468457029?uo=4">© TicketLeap</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/50/54/4f/50544f22-4727-4630-1cea-aaf06f961630/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32693067-904188b2-c724-11e7-98e0-92442718445c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32693067-904188b2-c724-11e7-98e0-92442718445c.png)
https://user-images.githubusercontent.com/2068130/32693067-904188b2-c724-11e7-98e0-92442718445c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32693076-9f06b82c-c724-11e7-8569-b23d1d240c52.png
