### ISSUE TITLE
Waze - GPS, Maps & Social Traffic

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#480]
**App Name:** Waze - GPS, Maps & Social Traffic
**Bundle ID:** com.waze.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=323229106">323229106</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/waze-gps-maps-social-traffic/id323229106?mt=8&uo=4">https://itunes.apple.com/us/app/waze-gps-maps-social-traffic/id323229106?mt=8&uo=4</a>
**App Version:** 3.9.6
**Seller:** waze
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/waze-inc./id323229109?uo=4>© Waze Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/90/28/42/9028427e-6960-b6b1-0032-62751fd7e61a/mzl.obpbkxry.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10384203/71c93c32-6e38-11e5-84eb-3e6903b38e76.png)

**Comment by Trubbel** [comment]
Updating the icon plus source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10384203/71c93c32-6e38-11e5-84eb-3e6903b38e76.png)
https://cloud.githubusercontent.com/assets/10730122/10384203/71c93c32-6e38-11e5-84eb-3e6903b38e76.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10384200/6ef9bb1c-6e38-11e5-9854-809df1f3b1c9.png
