### ISSUE TITLE
Xbox

### ISSUE THREAD

**Issue by iNfeCtGFX** [glasklart/hd#4811]
**App Name:** Xbox
**Bundle ID:** com.microsoft.smartglass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=736179781">736179781</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xbox/id736179781?mt=8&uo=4">https://itunes.apple.com/us/app/xbox/id736179781?mt=8&uo=4</a>
**App Version:** 3.1606
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/d7/32/ec/d732ecb6-3f9c-86bb-d025-8208b7ea7d0c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16247576/aa2e8aea-380a-11e6-8135-55c8a435bedb.png)

**Comment by l8er4now** [comment]
Need an update.

**App Name:** Xbox
**Bundle ID:** com.microsoft.smartglass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=736179781">736179781</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xbox/id736179781?mt=8&uo=4">https://itunes.apple.com/us/app/xbox/id736179781?mt=8&uo=4</a>
**App Version:** 3.1606
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/d7/32/ec/d732ecb6-3f9c-86bb-d025-8208b7ea7d0c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16247576/aa2e8aea-380a-11e6-8135-55c8a435bedb.png)
https://cloud.githubusercontent.com/assets/2068130/16247576/aa2e8aea-380a-11e6-8135-55c8a435bedb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16247592/bcb5f7f2-380a-11e6-8bce-50ef173cfada.png
