### ISSUE TITLE
iAppLock

### ISSUE THREAD

**Issue by iNfeCtGFX** [glasklart/hd#4814]
**App Name:** iAppLock
**Bundle ID:** com.thinkyeah.iAppLock
**iTunes ID:** none (Cydia app)
**Original Artwork**
<img src="https://cloud.githubusercontent.com/assets/2068130/5340355/0f121e38-7eec-11e4-9b05-cef86a7e9194.png" width="150" height="150">
**Accepted Artwork**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/5340359/32726944-7f2f-11e4-9c76-311ee43c3353.png)

**Comment by Trubbel** [comment]
For some reason this icon doesn't get themed *(for me at least?).* Is it possible that **CFBundleIdentifier** is case-sensitive?

**Comment by dreamnet** [comment]
@Trubbel Yes, the BundleID is case sensitive. Can you check the Info.plist of this app following [this guide](https://github.com/glasklart/hd/wiki/How-to-Request-a-Cydia-Icon)?

**Comment by Trubbel** [comment]
Okay, it's suppose to be like this > com.thinkyeah.i**A**pp**L**ock

**Comment by dreamnet** [comment]
@Trubbel Jup. I rename the icon.

**Comment by Trubbel** [comment]
@dreamnet Great! Thank you.
