### ISSUE TITLE
BlaBlaCar - Trusted Carpooling

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#4827]
**App Name:** BlaBlaCar - Trusted Carpooling
**Bundle ID:** com.comuto.comuto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=341329033">341329033</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/blablacar-trusted-carpooling/id341329033?uo=4">https://apps.apple.com/us/app/blablacar-trusted-carpooling/id341329033?uo=4</a>
**App Version:** 5.42.1
**Seller:** Comuto
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/comuto/id341329036?uo=4">© Comuto</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/06/d0/e1/06d0e1c8-3c50-de17-d1f3-3130e9b0661b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60123099-f1398000-9786-11e9-827a-84d28cfb749c.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60123099-f1398000-9786-11e9-827a-84d28cfb749c.png)
https://user-images.githubusercontent.com/20930745/60123099-f1398000-9786-11e9-827a-84d28cfb749c.png

Source:
https://user-images.githubusercontent.com/20930745/60123101-f26aad00-9786-11e9-9c8e-8e0aa03b81b6.png
