### ISSUE TITLE
Touch Hockey: FS5

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#4832]
**App Name:** Touch Hockey: FS5
**Bundle ID:** com.flipside5.games.touchhockeypaid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=296232471">296232471</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touch-hockey-fs5/id296232471?mt=8&uo=4">https://itunes.apple.com/us/app/touch-hockey-fs5/id296232471?mt=8&uo=4</a>
**App Version:** 5.0.0
**Seller:** FlipSide5, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/flipside5-inc./id283490538?uo=4>© FlipSide5, Inc.</a>
**Supported Devices:** iPodTouchFifthGen, iPadThirdGen, iPhone4S, iPhone5, iPadMini, iPhone4, iPodTouchThirdGen, iPadThirdGen4G, iPhone5s, iPodTouchourthGen, iPhone-3GS, iPad23G, iPadWifi, iPad3G, iPadFourthGen4G, iPad2Wifi, iPadFourthGen, iPadMini4G, iPhone5c
**Original Artwork:**
<img src="http://a1628.phobos.apple.com/us/r30/Purple/v4/9a/6d/3f/9a6d3f9a-341f-abe6-199a-28e50f0f6860/mzl.cftxjnrg.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16967554/caf16f3a-4e09-11e6-83f2-0c7ea6c4f2be.png)

**Comment by Anuskuss** [comment]
@dreamnet Could you remove the lines?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16967554/caf16f3a-4e09-11e6-83f2-0c7ea6c4f2be.png)
https://cloud.githubusercontent.com/assets/2068130/16967554/caf16f3a-4e09-11e6-83f2-0c7ea6c4f2be.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16967570/d98a1920-4e09-11e6-8f73-57fe998cbcda.png

**Comment by Anuskuss** [comment]
:+1:
