### ISSUE TITLE
Cardiio - Heart Rate Monitor + 7 Minute Workout Exercise Routine for Cardio Health and Fitness

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#484]
**App Name:** Cardiio - Heart Rate Monitor + 7 Minute Workout Exercise Routine for Cardio Health and Fitness
**Bundle ID:** com.cardiio.cardiio.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542891434">542891434</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cardiio-heart-rate-monitor/id542891434?mt=8&uo=4">https://itunes.apple.com/us/app/cardiio-heart-rate-monitor/id542891434?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** Cardiio, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cardiio-inc./id534956039?uo=4">© Cardiio, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/8f/04/63/8f0463c1-64de-1447-c429-b86a7cf5751a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19957619/7993cb00-a198-11e6-98eb-9891a957af24.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19957619/7993cb00-a198-11e6-98eb-9891a957af24.png)
https://cloud.githubusercontent.com/assets/20930745/19957619/7993cb00-a198-11e6-98eb-9891a957af24.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19957630/8fe637a8-a198-11e6-954b-4cf164d18ac3.png
