### ISSUE TITLE
WebMD

### ISSUE THREAD

**Issue by gingkobilobar** [glasklart/hd#4845]
**App Name:** WebMD
**Bundle ID:** com.webmd.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=295076329">295076329</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/webmd/id295076329?mt=8&uo=4">https://itunes.apple.com/us/app/webmd/id295076329?mt=8&uo=4</a>
**App Version:** 6.3
**Seller:** WebMD Health Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/webmd/id295076332?mt=8&uo=4">© WebMD</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/ac/59/a3/ac59a378-93fb-c2a6-a47f-768ac493fb4f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32122848-3c729c8a-bb62-11e7-9ddf-6d3b8658f6c0.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** WebMD
**Bundle ID:** com.webmd.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=295076329">295076329</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/webmd/id295076329?mt=8&uo=4">https://itunes.apple.com/us/app/webmd/id295076329?mt=8&uo=4</a>
**App Version:** 6.3
**Seller:** WebMD Health Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/webmd/id295076332?mt=8&uo=4">© WebMD</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/ac/59/a3/ac59a378-93fb-c2a6-a47f-768ac493fb4f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32122848-3c729c8a-bb62-11e7-9ddf-6d3b8658f6c0.png)
https://user-images.githubusercontent.com/20930745/32122848-3c729c8a-bb62-11e7-9ddf-6d3b8658f6c0.png

Source:
https://user-images.githubusercontent.com/20930745/32122861-52000538-bb62-11e7-8fb0-bbd2cdf5296c.png
