### ISSUE TITLE
Photo Editor - Fotolr

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#4849]
**App Name:** Photo Editor - Fotolr
**Bundle ID:** com.tinypiece.PSFotolr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424445937">424445937</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photo-editor-fotolr/id424445937?mt=8&uo=4">https://itunes.apple.com/us/app/photo-editor-fotolr/id424445937?mt=8&uo=4</a>
**App Version:** 3.1.4
**Seller:** Tiny Piece Co., Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tiny-piece-co.-ltd/id421120865?uo=4>© Tiny Piece Co., Ltd</a>
**Supported Devices:** iPodTouchThirdGen, iPhone5, iPodTouchFifthGen, iPhone4, iPadFourthGen4G, iPad3G, iPadThirdGen4G, iPodTouchourthGen, iPadWifi, iPadThirdGen, iPhone-3GS, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPad2Wifi, iPhone4S, iPadFourthGen, iPad23G
**Original Artwork:**
<img src="http://a888.phobos.apple.com/us/r30/Purple4/v4/9d/15/ec/9d15ec19-86b7-de86-d9b3-7f80eebcdbfa/mzl.qcltdokq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5873868/90d46e3e-a2fb-11e4-9f32-7c880834f871.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/5869091/3cd56862-a281-11e4-9009-0cf786381e48.png)
https://cloud.githubusercontent.com/assets/2236254/5869091/3cd56862-a281-11e4-9009-0cf786381e48.png
Source:
https://cloud.githubusercontent.com/assets/2236254/5869088/39828fc8-a281-11e4-8ea6-76c0b0171baa.png

**Comment by dreamnet** [comment]
@MagnaMike Yes! :+1:

**Comment by MagnaMike** [comment]
@dreamnet Good call. :+1:
