### ISSUE TITLE
Aurora Forecast.

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#4850]
**App Name:** Aurora Forecast.
**Bundle ID:** com.tinacinc.auroraforecast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=539875792">539875792</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aurora-forecast./id539875792?mt=8&uo=4">https://itunes.apple.com/us/app/aurora-forecast./id539875792?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** TINAC Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tinac-inc./id539875795?uo=4>© TINAC Inc.</a>
**Supported Devices:** iPadWifi, iPhone5, iPadMini, iPad23G, iPodTouchThirdGen, iPhone4S, iPadThirdGen, iPadFourthGen, iPad3G, iPadFourthGen4G, iPhone5c, iPhone5s, iPhone4, iPodTouchourthGen, iPadThirdGen4G, iPodTouchFifthGen, iPhone-3GS, iPadMini4G, iPad2Wifi
**Original Artwork:**
<img src="http://a875.phobos.apple.com/us/r30/Purple3/v4/3a/c4/4b/3ac44b80-8388-5bbd-74d7-bdcdebb943fb/mzl.yjgzvriq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5625742/fbf984e8-9580-11e4-9de7-d30c3e84f689.png)

**Comment by dreamnet** [comment]
???
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5625742/fbf984e8-9580-11e4-9de7-d30c3e84f689.png)
https://cloud.githubusercontent.com/assets/2068130/5625742/fbf984e8-9580-11e4-9de7-d30c3e84f689.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5625745/0b92b1e0-9581-11e4-9a45-544e89bced9a.png
