### ISSUE TITLE
Crossy Road - Endless Arcade Hopper

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#4868]
**App Name:** Crossy Road - Endless Arcade Hopper
**Bundle ID:** com.hipsterwhale.crossy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=924373886">924373886</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/crossy-road-endless-arcade/id924373886?mt=8&uo=4">https://itunes.apple.com/us/app/crossy-road-endless-arcade/id924373886?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Hipster Whale Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hipster-whale/id924373885?uo=4>© HIPSTER WHALE</a>
**Supported Devices:** iPhone4S, iPadFourthGen, iPadMini4G, iPad2Wifi, iPad23G, iPadMini, iPodTouchFifthGen, iPadThirdGen4G, iPhone5, iPadFourthGen4G, iPhone4, iPadThirdGen, iPhone5c, iPhone5s
**Original Artwork:**
<img src="http://a827.phobos.apple.com/us/r30/Purple1/v4/66/50/87/66508786-7e50-05d6-c340-8a0348920313/mzl.kubclpgf.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5540436/eeea4f0e-8acb-11e4-8e64-3c9e81092ac2.png)

**Comment by ivamsis** [comment]
Icon not working on ios 8.1.2, crossy road version 1.1.1

**Comment by dreamnet** [comment]
@ivamsis Please double check the icon name you entered - should be `com.hipsterwhale.crossy@2x.png` for this app.
