### ISSUE TITLE
Leo's Fortune

### ISSUE THREAD

**Issue by xtrem123** [glasklart/hd#4869]
**App Name:** Leo's Fortune
**Bundle ID:** com.leosfortune
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=830544402">830544402</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/leos-fortune/id830544402?mt=8&uo=4">https://itunes.apple.com/us/app/leos-fortune/id830544402?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** 1337 & Senri LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/1337-senri-llc/id830544405?uo=4>© 1337 & Senri LLC</a>
**Supported Devices:** iPadMini, iPadThirdGen4G, iPadFourthGen4G, iPhone5c, iPad2Wifi, iPadFourthGen, iPhone5, iPodTouchFifthGen, iPadThirdGen, iPhone5s, iPadMini4G, iPhone4S, iPhone4, iPad23G
**Original Artwork:**
<img src="http://a704.phobos.apple.com/us/r30/Purple3/v4/7e/17/2e/7e172e2f-438d-e4e4-78e9-1f49de7c31cc/mzl.geooehix.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5626525/20983a72-958d-11e4-874e-9916f47a14fc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5626525/20983a72-958d-11e4-874e-9916f47a14fc.png)
https://cloud.githubusercontent.com/assets/2068130/5626525/20983a72-958d-11e4-874e-9916f47a14fc.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5626530/2f7a81d0-958d-11e4-8150-0b557f3fe8bd.png
