### ISSUE TITLE
Elevate - Brain Training

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#4875]
**App Name:** Elevate - Brain Training
**Bundle ID:** com.elevateapp.elevate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=875063456">875063456</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/elevate-brain-training/id875063456?uo=4">https://apps.apple.com/us/app/elevate-brain-training/id875063456?uo=4</a>
**App Version:** 5.11
**Seller:** Elevate Labs, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/elevate-inc/id875063459?uo=4">© Elevate, Inc.</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/ce/49/86/ce4986b1-a258-3e5a-fb63-d2cb416d0b10/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387734-0aed0700-9aa8-11e9-8f37-d4c18eb8c0ed.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387707-a5991600-9aa7-11e9-9e48-ee706a8c4fdd.png)
https://user-images.githubusercontent.com/20930745/60387707-a5991600-9aa7-11e9-9e48-ee706a8c4fdd.png

Source:
https://user-images.githubusercontent.com/20930745/60387712-adf15100-9aa7-11e9-9d00-59769263a28e.png
