### ISSUE TITLE
ROCKI

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#4878]
**App Name:** ROCKI
**Bundle ID:** com.myrocki.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=884100956">884100956</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rocki/id884100956?mt=8&uo=4">https://itunes.apple.com/us/app/rocki/id884100956?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** ROCKI LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/rocki/id884100959?uo=4>© ROCKI</a>
**Supported Devices:** iPadThirdGen, iPhone5, iPhone5c, iPad23G, iPhone4, iPodTouchFifthGen, iPadMini, iPhone4S, iPadThirdGen4G, iPadMini4G, iPadFourthGen4G, iPhone5s, iPad2Wifi, iPadFourthGen
**Original Artwork:**
<img src="http://a298.phobos.apple.com/us/r30/Purple3/v4/a7/c9/02/a7c9022c-720b-19b8-1c46-4677bd4a5da9/mzl.mrvfuuim.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5625872/8bc0c29c-9583-11e4-9913-4d3ae70fdfe6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5625872/8bc0c29c-9583-11e4-9913-4d3ae70fdfe6.png)
https://cloud.githubusercontent.com/assets/2068130/5625872/8bc0c29c-9583-11e4-9913-4d3ae70fdfe6.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5625877/9de7707e-9583-11e4-96b0-0b5de6879a78.png
