### ISSUE TITLE
Duet Display

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#4879]
**App Name:** Duet Display
**Bundle ID:** com.kairos.duet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935754064">935754064</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/duet-display/id935754064?uo=4">https://apps.apple.com/us/app/duet-display/id935754064?uo=4</a>
**App Version:** 2.1.7
**Seller:** Duet, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/duet-inc/id935754063?uo=4">© Duet, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/44/1d/a7/441da7c7-a1d0-5356-0f80-1cce3cc2b1c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382954-00f8e300-9a6b-11e9-80e3-74643bf9f25d.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382954-00f8e300-9a6b-11e9-80e3-74643bf9f25d.png)
https://user-images.githubusercontent.com/20930745/60382954-00f8e300-9a6b-11e9-80e3-74643bf9f25d.png

Source:
https://user-images.githubusercontent.com/20930745/60382955-022a1000-9a6b-11e9-9021-ffaac3f96ffb.png
