### ISSUE TITLE
FileExplorer: File Manager

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#488]
**App Name:** FileExplorer: File Manager
**Bundle ID:** com.skyjos.fileexplorerfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=510282524">510282524</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fileexplorer-file-manager/id510282524?mt=8&uo=4">https://itunes.apple.com/us/app/fileexplorer-file-manager/id510282524?mt=8&uo=4</a>
**App Version:** 7.1.2
**Seller:** Skyjos Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/skyjos-co-ltd/id499470116?uo=4">© Skyjos Co., Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/7e/24/4d/7e244d16-f374-fd8a-6957-f0b8301a2703/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/36601148-a4991f50-18b4-11e8-82bf-dea2f5257d53.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416954/abe307e0-7823-11e6-93c6-10d3d952cf67.png)
https://cloud.githubusercontent.com/assets/2068130/18416954/abe307e0-7823-11e6-93c6-10d3d952cf67.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416956/bcfc26e2-7823-11e6-9669-2616dbdb85fa.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36601148-a4991f50-18b4-11e8-82bf-dea2f5257d53.png)
https://user-images.githubusercontent.com/20930745/36601148-a4991f50-18b4-11e8-82bf-dea2f5257d53.png

Source:
https://user-images.githubusercontent.com/20930745/36601175-ba3a435c-18b4-11e8-8e41-314b724cfac8.png
