### ISSUE TITLE
Farm Heroes Saga

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#4881]
**App Name:** Farm Heroes Saga
**Bundle ID:** com.midasplayer.apps.farmheroessaga
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=608206510">608206510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/farm-heroes-saga/id608206510?mt=8&uo=4">https://itunes.apple.com/us/app/farm-heroes-saga/id608206510?mt=8&uo=4</a>
**App Version:** 2.16.14
**Seller:** King.com Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/king.com-limited/id526656015?uo=4>© King.com Limited</a>
**Supported Devices:** iPadMini, iPhone4, iPhone-3GS, iPodTouchThirdGen, iPhone5, iPad2Wifi, iPad3G, iPhone5c, iPad23G, iPadFourthGen, iPadFourthGen4G, iPhone4S, iPodTouchFifthGen, iPhone5s, iPadThirdGen, iPadWifi, iPadThirdGen4G, iPodTouchourthGen, iPadMini4G
**Original Artwork:**
<img src="http://a96.phobos.apple.com/us/r30/Purple3/v4/5f/9c/65/5f9c6558-92d3-7797-f320-11eb1b771d1b/pr_source.png?downloadKey=1419299196_7092870ff9ceaae4f6dbd13081f84637" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5622522/14c2b026-9545-11e4-925a-d8bc25c1d59c.png)

**Comment by dreamnet** [comment]
Best I can do:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5622522/14c2b026-9545-11e4-925a-d8bc25c1d59c.png)
https://cloud.githubusercontent.com/assets/2068130/5622522/14c2b026-9545-11e4-925a-d8bc25c1d59c.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5622528/290176b2-9545-11e4-9a60-b35725608b8f.png
