### ISSUE TITLE
Facebook Groups

### ISSUE THREAD

**Issue by xtrem123** [glasklart/hd#4902]
**App Name:** Facebook Groups
**Bundle ID:** com.facebook.Groups
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=931735837">931735837</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facebook-groups/id931735837?mt=8&uo=4">https://itunes.apple.com/us/app/facebook-groups/id931735837?mt=8&uo=4</a>
**App Version:** 40.0
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/facebook-inc./id284882218?uo=4>© Facebook, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/c6/cf/15/c6cf15e8-7249-52a8-28a7-5a7a02eccf1b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356833/942a6592-3ae5-11e6-84a6-5a3b42d8cfd5.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Facebook Groups
**Bundle ID:** com.facebook.Groups
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=931735837">931735837</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facebook-groups/id931735837?mt=8&uo=4">https://itunes.apple.com/us/app/facebook-groups/id931735837?mt=8&uo=4</a>
**App Version:** 40.0
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/facebook-inc./id284882218?uo=4>© Facebook, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/c6/cf/15/c6cf15e8-7249-52a8-28a7-5a7a02eccf1b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356833/942a6592-3ae5-11e6-84a6-5a3b42d8cfd5.png)
https://cloud.githubusercontent.com/assets/10730122/16356833/942a6592-3ae5-11e6-84a6-5a3b42d8cfd5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16356832/942961c4-3ae5-11e6-8566-41adc884475b.png
