### ISSUE TITLE
Amazon Fire TV Remote

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#4908]
**App Name:** Amazon Fire TV Remote
**Bundle ID:** com.amazon.firetv.remote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=947984433">947984433</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amazon-fire-tv-remote/id947984433?mt=8&uo=4">https://itunes.apple.com/us/app/amazon-fire-tv-remote/id947984433?mt=8&uo=4</a>
**App Version:** 1.0.16
**Seller:** AMZN Mobile LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amzn-mobile-llc/id297606954?uo=4">© AMZN Mobile LLC</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/d1/e3/b0/d1e3b00e-6c4d-ae96-0737-e4ca118130aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160961-855bd3fc-34c6-11e8-8fc5-3668753d722b.png)

**Comment by Christian9901** [comment]
needs an update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160961-855bd3fc-34c6-11e8-8fc5-3668753d722b.png)
https://user-images.githubusercontent.com/2068130/38160961-855bd3fc-34c6-11e8-8fc5-3668753d722b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38160962-95a9f5e0-34c6-11e8-93e4-f26dff806f4f.png
