### ISSUE TITLE
Filza File Manager

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#4909]
App Name: Filza File Manager
Bundle ID: com.tigisoftware.Filza
iTunes ID: none (Cydia app)
Original Artwork:
 <img src="http://cydia.saurik.com/icon/com.tigisoftware.filza.png" width="150" height="150" />
Accepted Artwork:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5565294/5e40b2e8-8ef1-11e4-9789-637b862e9375.png)

**Comment by boxermansr** [comment]
It seems this isn't working with the latest version of Filza. No idea if the name changed or whatever, and no idea how to tell. Any help would be appreciated. Thanks.

**Comment by boxermansr** [comment]
Got it. its com.tigisoftware.Filza now (capital F instead of lowercase) for the current version.

**Comment by MagnaMike** [comment]
@boxermansr Great!
