### ISSUE TITLE
Dropcam

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#4918]
**App Name:** Dropcam
**Bundle ID:** com.dropcam.Dropcam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=351175162">351175162</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dropcam/id351175162?mt=8&uo=4">https://itunes.apple.com/us/app/dropcam/id351175162?mt=8&uo=4</a>
**App Version:** 3.4.4
**Seller:** Dropcam, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dropcam-inc./id351175165?uo=4>© Dropcam, Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone5, iPadFourthGen4G, iPadFourthGen, iPodTouchFifthGen, iPadMini, iPhone5s, iPhone4, iPhone5c, iPadThirdGen, iPhone4S, iPad2Wifi, iPadMini4G, iPadThirdGen4G, iPad23G, iPodTouchourthGen
**Original Artwork:**
<img src="http://a1522.phobos.apple.com/us/r30/Purple3/v4/6a/62/c9/6a62c9c4-7bc7-dec1-de75-17b3ff0cc490/mzl.kzvfnhoa.png" width="150" height="150" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60382625-0bfd4480-9a66-11e9-81b7-4ebb703d1462.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60382625-0bfd4480-9a66-11e9-81b7-4ebb703d1462.png)
https://user-images.githubusercontent.com/2068130/60382625-0bfd4480-9a66-11e9-81b7-4ebb703d1462.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60382628-1b7c8d80-9a66-11e9-987d-4c83d1d562ca.png
