### ISSUE TITLE
ZOOKEEPER　DX

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#492]
**App Name:** ZOOKEEPER　DX
**Bundle ID:** jp.kiteretsu.ZOOKEEPERDX
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=433596395">433596395</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zookeeper-dx/id433596395?mt=8&uo=4">https://itunes.apple.com/us/app/zookeeper-dx/id433596395?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** KITERETSU.INC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kiteretsu-inc/id400412887?uo=4">© KITERETSU INC.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple41/v4/79/80/8d/79808dd7-4526-b551-e340-0862e6d58c8f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32413412-4e7d0266-c211-11e7-96d7-7b27ff1fa0f5.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32413412-4e7d0266-c211-11e7-96d7-7b27ff1fa0f5.png)
https://user-images.githubusercontent.com/2068130/32413412-4e7d0266-c211-11e7-96d7-7b27ff1fa0f5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32413415-5e9e64b4-c211-11e7-9df3-d02c9d5d9a60.png
