### ISSUE TITLE
MeinVodafone

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#4925]
**App Name:** MeinVodafone
**Bundle ID:** MeinVodafone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398195347">398195347</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/meinvodafone/id398195347?mt=8&uo=4">https://itunes.apple.com/de/app/meinvodafone/id398195347?mt=8&uo=4</a>
**App Version:** 8.9
**Seller:** Vodafone GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/vodafone-gmbh/id396865570?mt=8&uo=4">© Vodafone GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/74/51/45/745145e0-b5ed-140c-d99f-97fc689d6145/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59123368-5a369080-895d-11e9-99c9-c505447c2c80.png)

**Comment by 2Qt2beStr8** [comment]
Needs update

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59123368-5a369080-895d-11e9-99c9-c505447c2c80.png)
https://user-images.githubusercontent.com/20930745/59123368-5a369080-895d-11e9-99c9-c505447c2c80.png

Source:
https://user-images.githubusercontent.com/20930745/59123372-5c005400-895d-11e9-9d86-4d546c303de9.png
