### ISSUE TITLE
appJobber

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#4933]
**App Name:** appJobber
**Bundle ID:** de.werdenktwas.AppJobber
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519088472">519088472</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appjobber/id519088472?mt=8&uo=4">https://itunes.apple.com/us/app/appjobber/id519088472?mt=8&uo=4</a>
**App Version:** 2.0.6
**Seller:** wer denkt was GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wer-denkt-was-gmbh/id587932445?uo=4">© wer denkt was GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAirCellular-iPadAirCellular, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2Cellular-iPadAir2Cellular, iPadMini3Cellular-iPadMini3Cellular, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4Cellular-iPadMini4Cellular, iPadProCellular-iPadProCellular, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad612-iPad612, iPad72-iPad72, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/54/92/19/549219c3-4524-95eb-2e92-193665ec2ab0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38456100-ccf9670a-3a80-11e8-965b-db016aa413f1.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38456100-ccf9670a-3a80-11e8-965b-db016aa413f1.png)
https://user-images.githubusercontent.com/20930745/38456100-ccf9670a-3a80-11e8-965b-db016aa413f1.png

Source:
https://user-images.githubusercontent.com/20930745/38456109-dcb4a290-3a80-11e8-88e8-e3d8ea0cf0a1.png
