### ISSUE TITLE
Runtastic Mountain Bike PRO GPS Biking Computer, Ride and Route Tracker

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#4938]
**App Name:** Runtastic Mountain Bike PRO GPS Biking Computer, Ride and Route Tracker
**Bundle ID:** com.runtastic.iphone.mountainbike.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478862935">478862935</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-mountain-bike-pro/id478862935?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-mountain-bike-pro/id478862935?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPhone5s, iPad23G, iPadFourthGen, iPhone5c, iPadThirdGen4G, iPodTouchSixthGen, iPhone5, iPadMini, iPhone4, iPhone6, iPadThirdGen, iPhone6Plus, iPad2Wifi, iPadMini4G, iPadFourthGen4G, iPodTouchFifthGen, iPhone4S
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/a3/92/3c/a3923c96-21d8-f06b-eb6f-db2d2d1f30f3/mzl.fonkimxe.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9273512/b1a196aa-428d-11e5-8a02-56ba73ab1339.png)

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9273512/b1a196aa-428d-11e5-8a02-56ba73ab1339.png)
https://cloud.githubusercontent.com/assets/2068130/9273512/b1a196aa-428d-11e5-8a02-56ba73ab1339.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9273516/bfecab0a-428d-11e5-921b-173386f7cf6d.png
