### ISSUE TITLE
Brothers in Arms® 3: Sons of War

### ISSUE THREAD

**Issue by dominicPereira** [glasklart/hd#4939]
**App Name:** Brothers in Arms® 3: Sons of War
**Bundle ID:** com.gameloft.bia3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=656124384">656124384</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/brothers-in-arms-3-sons-of-war/id656124384?mt=8&uo=4">https://itunes.apple.com/us/app/brothers-in-arms-3-sons-of-war/id656124384?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Gameloft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/gameloft/id282764297?mt=8&uo=4>© Gameloft</a>
**Supported Devices:** iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPhone5c, iPodTouchFifthGen, iPhone4, iPodTouchourthGen, iPadMini4G, iPhone5, iPadThirdGen, iPhone5s, iPad2Wifi, iPhone4S, iPad23G
**Original Artwork:**
<img src="http://a497.phobos.apple.com/us/r30/Purple3/v4/ae/75/09/ae7509e8-4306-e87a-fb2b-b5dd771d7f8e/pr_source.jpg?downloadKey=1419864831_e0eb4460f111aabca906e6beff853e1e" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5620284/b6c48360-952a-11e4-98a8-09db193d3e37.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5620284/b6c48360-952a-11e4-98a8-09db193d3e37.png)
https://cloud.githubusercontent.com/assets/2068130/5620284/b6c48360-952a-11e4-98a8-09db193d3e37.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5620292/cbd365c8-952a-11e4-8f2b-5bcc53b6e5a3.png
