### ISSUE TITLE
Punch Quest

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#494]
**App Name:** Punch Quest
**Bundle ID:** com.rocketcat.PunchQuest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=554223561">554223561</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/punch-quest/id554223561?mt=8&uo=4">https://itunes.apple.com/us/app/punch-quest/id554223561?mt=8&uo=4</a>
**App Version:** 1.4.4
**Seller:** Rocketcat LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rocketcat-llc/id305576988?uo=4">© Rocketcat LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/c0/01/d9/c001d996-8f66-a92a-3cd2-93b6d634bd9f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21752942/3a117044-d5e2-11e6-8d22-a7814fcf089d.png)

**Comment by MenaceInc** [comment]
Doesn't work in 5.42 on 9.3.3

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21752942/3a117044-d5e2-11e6-8d22-a7814fcf089d.png)
https://cloud.githubusercontent.com/assets/2068130/21752942/3a117044-d5e2-11e6-8d22-a7814fcf089d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21752948/477e84f6-d5e2-11e6-9ccc-db1b86687d89.png
