### ISSUE TITLE
NYP Mobile (for student)

### ISSUE THREAD

**Issue by dominicPereira** [glasklart/hd#4940]
**App Name:** NYP Mobile (for student)
**Bundle ID:** sg.edu.nyp.cnc.NYPMobileForStudent
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=662804748">662804748</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nyp-mobile-for-student/id662804748?mt=8&uo=4">https://itunes.apple.com/us/app/nyp-mobile-for-student/id662804748?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Nanyang Polytechnic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nanyang-polytechnic/id370531175?uo=4>© Nanyang Polytechnic</a>
**Supported Devices:** iPadFourthGen4G, iPodTouchourthGen, iPodTouchFifthGen, iPadFourthGen, iPad23G, iPad3G, iPhone5s, iPadWifi, iPadMini, iPadThirdGen4G, iPadMini4G, iPad2Wifi, iPhone4, iPhone-3GS, iPodTouchThirdGen, iPadThirdGen, iPhone4S, iPhone5, iPhone5c
**Original Artwork:**
<img src="http://a1235.phobos.apple.com/us/r30/Purple2/v4/d2/43/12/d24312da-2fa6-8e66-7e9a-97dd38860ca0/mzl.wmxaznsm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5617961/54390b82-9514-11e4-86b8-60e57759aa4d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5617961/54390b82-9514-11e4-86b8-60e57759aa4d.png)
https://cloud.githubusercontent.com/assets/2068130/5617939/122f11fa-9514-11e4-9596-c539f7d68817.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5617946/2319baba-9514-11e4-8f19-10373f0648e8.png
