### ISSUE TITLE
BMO Mobile Banking

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#4947]
**App Name:** BMO Mobile Banking
**Bundle ID:** com.bmo.mbanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=429080319">429080319</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/hk/app/bmo-mobile-banking/id429080319?uo=4">https://apps.apple.com/hk/app/bmo-mobile-banking/id429080319?uo=4</a>
**App Version:** 5.10.0
**Seller:** Bank of Montreal
**Developer:** <a target="_blank" href="https://apps.apple.com/hk/developer/bmo-financial-group/id408070810?uo=4">© BMO Financial Group</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/93/35/c3/9335c336-3c60-fd7f-2cce-9e527f3535fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60123376-a2d8b100-9787-11e9-9831-f88801c180e3.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60123376-a2d8b100-9787-11e9-9831-f88801c180e3.png)
https://user-images.githubusercontent.com/20930745/60123376-a2d8b100-9787-11e9-9831-f88801c180e3.png

Source:
https://user-images.githubusercontent.com/20930745/60123382-a53b0b00-9787-11e9-9bba-e0710fafc0ed.png
