### ISSUE TITLE
Samsung Smart Washer

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#4949]
**App Name:** Samsung Smart Washer
**Bundle ID:** com.samsung.wmdryer1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606131806">606131806</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/samsung-smart-washer/id606131806?mt=8&uo=4">https://itunes.apple.com/us/app/samsung-smart-washer/id606131806?mt=8&uo=4</a>
**App Version:** 2.1.11
**Seller:** Samsung Electronics
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/samsung-electronics-co.ltd./id359580642?uo=4>© Samsung Electronics CO.LTD.</a>
**Supported Devices:** iPadThirdGen4G, iPhone-3GS, iPadMini, iPad23G, iPodTouchourthGen, iPadMini4G, iPadFourthGen, iPhone4, iPhone5s, iPadThirdGen, iPhone4S, iPhone5c, iPadFourthGen4G, iPodTouchFifthGen, iPad2Wifi, iPhone5
**Original Artwork:**
<img src="http://a1453.phobos.apple.com/us/r30/Purple3/v4/d7/8f/fc/d78ffcc6-2595-e8db-ca84-2ca536ef919b/pr_source.png?downloadKey=1419898828_a85ae070a42c447ed64c11aff6cf9346" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5618768/6ad27880-951c-11e4-981e-f9aa868f1bc8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5618768/6ad27880-951c-11e4-981e-f9aa868f1bc8.png)
https://cloud.githubusercontent.com/assets/2068130/5618768/6ad27880-951c-11e4-981e-f9aa868f1bc8.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5618773/7ac52620-951c-11e4-831f-27a6be6b51f3.png
