### ISSUE TITLE
Snapchat

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#495]
**App Name:** Snapchat
**Bundle ID:** com.toyopagroup.picaboo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447188370">447188370</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snapchat/id447188370?mt=8&uo=4">https://itunes.apple.com/us/app/snapchat/id447188370?mt=8&uo=4</a>
**App Version:** 9.11.0
**Seller:** Snapchat, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/snapchat-inc./id446889612?uo=4>© Snapchat, Inc.</a>
**Supported Devices:** iPhone5s, iPhone5, iPodTouchFifthGen, iPadMini, iPhone6, iPadMini4G, iPad2Wifi, iPad23G, iPadThirdGen, iPhone4S, iPadThirdGen4G, iPhone4, iPhone6Plus, iPadFourthGen4G, iPhone5c, iPadFourthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/6d/87/dd/6d87ddf9-af12-a079-3883-26e7cf2b4cb2/mzl.ezkkzffi.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8542694/7aa557a4-2465-11e5-8c96-a777cf19806f.png)

**Comment by zmathiasz** [comment]
@dreamnet 
Icon has been updated:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8542694/7aa557a4-2465-11e5-8c96-a777cf19806f.png)
https://cloud.githubusercontent.com/assets/10950389/8542694/7aa557a4-2465-11e5-8c96-a777cf19806f.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8542698/83d89e12-2465-11e5-8838-2b6cde2369c7.png

Alternate:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8542795/17f22c62-2466-11e5-8bfc-f9c7e828c27a.png)
https://cloud.githubusercontent.com/assets/10950389/8542795/17f22c62-2466-11e5-8bfc-f9c7e828c27a.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8542798/20895f4e-2466-11e5-80d6-a63e34b8fc79.png

**Comment by dreamnet** [comment]
Taking the first one.

**Comment by redblinkconsulting** [comment]
Hi,

Does anybody know, what is the bundle id of Scapchat for android.?
