### ISSUE TITLE
eSelect plus

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#4953]
**App Name:** eSelect plus
**Bundle ID:** com.moneris.eSelect-plus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=477538489">477538489</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/ca/app/eselect-plus/id477538489?uo=4">https://apps.apple.com/ca/app/eselect-plus/id477538489?uo=4</a>
**App Version:** 3.0.0
**Seller:** Moneris Solutions Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/ca/developer/moneris-solutions-corporation/id477538492?uo=4">© Moneris Solutions Corporation</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple30/v4/91/db/cd/91dbcdc4-4160-0536-0a27-aa430ad987ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387781-d3328f00-9aa8-11e9-857c-6927611aa243.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387781-d3328f00-9aa8-11e9-857c-6927611aa243.png)
https://user-images.githubusercontent.com/20930745/60387781-d3328f00-9aa8-11e9-857c-6927611aa243.png

Source:
https://user-images.githubusercontent.com/20930745/60387782-d4fc5280-9aa8-11e9-8a84-574610119ac6.png
