### ISSUE TITLE
Extreme Road Trip 2

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#496]
**App Name:** Extreme Road Trip 2
**Bundle ID:** ca.roofdog.roadtrip2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526814842">526814842</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/extreme-road-trip-2/id526814842?mt=8&uo=4">https://itunes.apple.com/us/app/extreme-road-trip-2/id526814842?mt=8&uo=4</a>
**App Version:** 3.18.0
**Seller:** Roofdog Games inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/roofdog-games/id445060906?uo=4">© Roofdog Games</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple115/v4/41/09/e3/4109e33c-f18e-e594-feaf-9f0fdf35efd0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41188966-36811f48-6bc7-11e8-940e-7c8171acf962.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41188966-36811f48-6bc7-11e8-940e-7c8171acf962.png)
https://user-images.githubusercontent.com/2068130/41188966-36811f48-6bc7-11e8-940e-7c8171acf962.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41188972-4551fc9a-6bc7-11e8-9ecd-1e67b84a8419.png
