### ISSUE TITLE
Bad Piggies

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#497]
**App Name:** Bad Piggies
**Bundle ID:** com.rovio.BadPiggies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=533451786">533451786</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bad-piggies/id533451786?mt=8&uo=4">https://itunes.apple.com/us/app/bad-piggies/id533451786?mt=8&uo=4</a>
**App Version:** 2.3.3
**Seller:** Rovio Entertainment Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rovio-entertainment-ltd/id298910979?uo=4">© Rovio Entertainment Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/99/58/a1/9958a11e-5fef-648e-4e78-ab4094ccdd8f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32194139-c71dc608-bdb9-11e7-88b5-857e785fe1fd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32194139-c71dc608-bdb9-11e7-88b5-857e785fe1fd.png)
https://user-images.githubusercontent.com/2068130/32194139-c71dc608-bdb9-11e7-88b5-857e785fe1fd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32194157-d66fb9f4-bdb9-11e7-8e30-deed255bc94f.png
