### ISSUE TITLE
Receipt Hog - Snap Receipts. Earn Cash.

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#4978]
**App Name:** Receipt Hog - Snap Receipts. Earn Cash.
**Bundle ID:** com.infoscoutinc.receipthog
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525373618">525373618</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/receipt-hog-snap-receipts./id525373618?mt=8&uo=4">https://itunes.apple.com/us/app/receipt-hog-snap-receipts./id525373618?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** ScoutIt, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/infoscout/id525373621?uo=4>© InfoScout</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/3e/12/02/3e120256-fbbe-7de5-aa4a-0306a36b7bb2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222683/c408c714-8e5e-11e6-81f1-ba5a71f8ef1e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222683/c408c714-8e5e-11e6-81f1-ba5a71f8ef1e.png)
https://cloud.githubusercontent.com/assets/2068130/19222683/c408c714-8e5e-11e6-81f1-ba5a71f8ef1e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19222689/d21073d4-8e5e-11e6-857c-59cd0fa2f5d3.png
