### ISSUE TITLE
Fjuul

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#4979]
**App Name:** Fjuul
**Bundle ID:** com.fjuul.fjuul
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=663780818">663780818</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fjuul/id663780818?mt=8&uo=4">https://itunes.apple.com/us/app/fjuul/id663780818?mt=8&uo=4</a>
**App Version:** 3.1.2
**Seller:** FJUUL CAPITAL OY
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fjuul/id663780821?uo=4">© Fjuul</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/c1/39/dc/c139dcaa-51eb-98b4-79b0-e294e5b32b14/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20464186/58233592-af43-11e6-9497-b2dd1a870652.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20464186/58233592-af43-11e6-9497-b2dd1a870652.png)
https://cloud.githubusercontent.com/assets/20930745/20464186/58233592-af43-11e6-9497-b2dd1a870652.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20464187/6a3e4816-af43-11e6-8959-34505bba504f.png
