### ISSUE TITLE
Super Crate Box

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#498]
**App Name:** Super Crate Box
**Bundle ID:** com.vlambeer.supercratebox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=483025428">483025428</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-crate-box/id483025428?mt=8&uo=4">https://itunes.apple.com/us/app/super-crate-box/id483025428?mt=8&uo=4</a>
**App Version:** 1.1.6
**Seller:** Vlambeer vof
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vlambeer/id483025971?uo=4">© Vlambeer</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/c8/fa/3e/c8fa3e17-88c6-98ac-2de6-a001299bf0c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22992766/f942b03a-f3c0-11e6-8bba-329227f538f9.png)

**Comment by MenaceInc** [comment]
Doesn't work in 5.42, ios 9.3.3

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22992766/f942b03a-f3c0-11e6-8bba-329227f538f9.png)
https://cloud.githubusercontent.com/assets/2068130/22992766/f942b03a-f3c0-11e6-8bba-329227f538f9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22992776/08f44d0e-f3c1-11e6-9add-4d6558c1c79c.png
