### ISSUE TITLE
Hue Disco

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#4982]
**App Name:** Hue Disco
**Bundle ID:** com.imakestuff.Huedisco
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=581258186">581258186</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hue-disco/id581258186?mt=8&uo=4">https://itunes.apple.com/us/app/hue-disco/id581258186?mt=8&uo=4</a>
**App Version:** 1.63
**Seller:** iMakeStuff
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/imakestuff/id317796293?uo=4>© iMakeStuff</a>
**Supported Devices:** iPhone5s, iPodTouchFifthGen, iPodTouchourthGen, iPadMini, iPhone5, iPadFourthGen, iPhone5c, iPhone-3GS, iPadFourthGen4G, iPadThirdGen, iPad23G, iPad2Wifi, iPadMini4G, iPhone4, iPadThirdGen4G, iPhone4S
**Original Artwork:**
<img src="http://a633.phobos.apple.com/us/r30/Purple4/v4/84/31/f6/8431f61d-533b-0a15-9577-80250d1575d7/mzl.msjmrptq.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5672977/970ad9d4-9796-11e4-8685-69e2656d4efa.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5672977/970ad9d4-9796-11e4-8685-69e2656d4efa.png)
https://cloud.githubusercontent.com/assets/2068130/5672977/970ad9d4-9796-11e4-8685-69e2656d4efa.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5672980/a3a39686-9796-11e4-8b4c-59f9861d4ed1.png

**Comment by ivanov007** [comment]
@dreamnet looks great :+1:
