### ISSUE TITLE
Hue Party for Philips Hue

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#4984]
**App Name:** Hue Party for Philips Hue
**Bundle ID:** com.alexbuzov.hueparty
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=630956426">630956426</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hue-party-for-philips-hue/id630956426?uo=4">https://apps.apple.com/us/app/hue-party-for-philips-hue/id630956426?uo=4</a>
**App Version:** 5.4.4
**Seller:** SpaceNation Inc. CA
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/spacenation-inc-ca/id492209073?uo=4">© SpaceNation Inc. CA</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/ac/05/90/ac059096-5229-5976-ca1c-a6805ab2ff76/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772829-1b326100-a0fc-11e9-8411-31f492eb687d.png)

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772829-1b326100-a0fc-11e9-8411-31f492eb687d.png)
https://user-images.githubusercontent.com/2068130/60772829-1b326100-a0fc-11e9-8411-31f492eb687d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60772833-2dac9a80-a0fc-11e9-9428-8005be73e08a.png
