### ISSUE TITLE
Smart Air Conditioner

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#4988]
**App Name:** Smart Air Conditioner
**Bundle ID:** com.samsung.2012RACAirconditioner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519988681">519988681</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smart-air-conditioner/id519988681?mt=8&uo=4">https://itunes.apple.com/us/app/smart-air-conditioner/id519988681?mt=8&uo=4</a>
**App Version:** 1.6.09
**Seller:** Samsung Electronics
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/samsung-electronics-co.ltd./id359580642?uo=4>© Samsung Electronics CO.LTD.</a>
**Supported Devices:** iPad23G, iPhone-3GS, iPad2Wifi, iPhone5c, iPadMini, iPadFourthGen4G, iPhone4, iPhone5s, iPodTouchourthGen, iPadThirdGen4G, iPhone5, iPadFourthGen, iPodTouchFifthGen, iPadThirdGen, iPhone4S, iPadMini4G
**Original Artwork:**
<img src="http://a436.phobos.apple.com/us/r30/Purple5/v4/c4/24/38/c424383f-3699-2b17-c0c2-de94379f792e/mzl.jgnohijj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5618304/e8af5a02-9517-11e4-8f11-c9d5aa98b63b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5618304/e8af5a02-9517-11e4-8f11-c9d5aa98b63b.png)
https://cloud.githubusercontent.com/assets/2068130/5618304/e8af5a02-9517-11e4-8f11-c9d5aa98b63b.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5618311/fa382df8-9517-11e4-80a8-24c426d1070d.png
