### ISSUE TITLE
КиноПоиск: кино и сериалы

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#499]
**App Name:** КиноПоиск: кино и сериалы
**Bundle ID:** ru.kinopoisk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=477718890">477718890</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/%D0%BA%D0%B8%D0%BD%D0%BE%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%BA%D0%B8%D0%BD%D0%BE-%D0%B8-%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8B/id477718890?uo=4">https://apps.apple.com/us/app/%D0%BA%D0%B8%D0%BD%D0%BE%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%BA%D0%B8%D0%BD%D0%BE-%D0%B8-%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8B/id477718890?uo=4</a>
**App Version:** 4.7.10
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yandex-llc/id308094652?uo=4">© Yandex LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/1e/c7/ad/1ec7ad2d-7906-8407-42f1-6ae04df213e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973536-8bd86a00-95a1-11e9-8d65-629271431279.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20184006/88fa220e-a767-11e6-8fb9-630b4615b29e.png)
https://cloud.githubusercontent.com/assets/20930745/20184006/88fa220e-a767-11e6-8fb9-630b4615b29e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20184042/a28908d4-a767-11e6-984d-2bcb38c9fcbc.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973536-8bd86a00-95a1-11e9-8d65-629271431279.png)
https://user-images.githubusercontent.com/20930745/59973536-8bd86a00-95a1-11e9-8d65-629271431279.png

Source:
https://user-images.githubusercontent.com/20930745/59973538-8d099700-95a1-11e9-8eab-dfbc4277e6a3.png
