### ISSUE TITLE
Copy My Data

### ISSUE THREAD

**Issue by dominicPereira** [glasklart/hd#4991]
**App Name:** Copy My Data
**Bundle ID:** com.mediamushroom.copymydata2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=870099476">870099476</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/copy-my-data/id870099476?mt=8&uo=4">https://itunes.apple.com/us/app/copy-my-data/id870099476?mt=8&uo=4</a>
**App Version:** 1.23
**Seller:** Media Mushroom Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/media-mushroom-limited/id635064634?uo=4>© Media Mushroom Limited</a>
**Supported Devices:** iPhone4S, iPadFourthGen, iPadThirdGen, iPadMini4G, iPodTouchFifthGen, iPad23G, iPadThirdGen4G, iPadMini, iPhone5s, iPhone-3GS, iPhone5, iPad2Wifi, iPhone5c, iPodTouchourthGen, iPhone4, iPadFourthGen4G
**Original Artwork:**
<img src="http://a1573.phobos.apple.com/us/r30/Purple3/v4/04/da/de/04dade15-4cd1-53e1-d5c1-9843981477ae/mzl.cwfdqreu.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5608373/1b624230-94d6-11e4-8277-92fe7128b489.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5608249/833f0c26-94d1-11e4-8dbe-f0e594e2c914.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5608250/8bc65c96-94d1-11e4-9282-b7085153d512.png

**Comment by cspadazzi** [comment]
Source file updated.

**Comment by dreamnet** [comment]
@cspadazzi :+1:
