### ISSUE TITLE
 InstaMag-Magazine Collage

### ISSUE THREAD

**Issue by dominicPereira** [glasklart/hd#4992]
**App Name:** InstaMag-Magazine Collage
**Bundle ID:** com.fotoable.instamag
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=615187629">615187629</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instamag-magazine-collage/id615187629?mt=8&uo=4">https://itunes.apple.com/us/app/instamag-magazine-collage/id615187629?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** Fotoable, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fotoable-inc./id433373211?uo=4>© Fotoable, Inc.</a>
**Supported Devices:** iPad23G, iPhone5, iPad2Wifi, iPadFourthGen4G, iPadMini4G, iPhone-3GS, iPhone4S, iPad3G, iPadWifi, iPhone4, iPodTouchourthGen, iPhone5s, iPadMini, iPhone5c, iPodTouchThirdGen, iPadFourthGen, iPodTouchFifthGen, iPadThirdGen4G, iPadThirdGen
**Original Artwork:**
<img src="http://a952.phobos.apple.com/us/r30/Purple3/v4/2a/fc/c1/2afcc1a9-a74f-1121-14b5-fa70fe3ef52c/mzl.ogbecofd.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5608262/1ee9c778-947e-11e4-81aa-1bde6cc9c9df.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5608223/c1a9c66e-94d0-11e4-8a73-d7de7934ee0a.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5608224/cb850afe-94d0-11e4-9582-601cedca4d5e.png

**Comment by dreamnet** [comment]
@cspadazzi Very good, the source file is not correct, so here is a little correction:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5608262/1ee9c778-947e-11e4-81aa-1bde6cc9c9df.png)
https://cloud.githubusercontent.com/assets/2068130/5608262/1ee9c778-947e-11e4-81aa-1bde6cc9c9df.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5608263/2e573f1a-947e-11e4-9d76-b28292a64cdb.png
If you add a public Mailadress to your Gihub profile, I give you credits for this anyway.

**Comment by cspadazzi** [comment]
Hmm, fair enough, So I take it you require the centre part to fill the entire 78x78px space? 
If that's the case I can update the rest of mine later on.

**Comment by dreamnet** [comment]
@cspadazzi For the source files - yes, the 1024x1024px source goes in the 78x78px area in the Glasklart icon - and the background must be transparent (not white), just check my source file and it should be clear what I mean.

**Comment by cspadazzi** [comment]
@dreamnet yeah no problems, I'll fix mine later this evening. Not a problem.

**Comment by dreamnet** [comment]
@cspadazzi OK, I look trough them in a view hours.
