### ISSUE TITLE
Mahjong 13 tiles

### ISSUE THREAD

**Issue by dominicPereira** [glasklart/hd#4993]
**App Name:** Mahjong 13 tiles
**Bundle ID:** com.poesysoul.mj13
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=551252620">551252620</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mahjong-13-tiles/id551252620?mt=8&uo=4">https://itunes.apple.com/us/app/mahjong-13-tiles/id551252620?mt=8&uo=4</a>
**App Version:** 3.0.4
**Seller:** poesy soul
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/poesy-soul/id322418812?uo=4>© poesy soul</a>
**Supported Devices:** iPhone4, iPadThirdGen, iPhone5c, iPadFourthGen, iPhone-3GS, iPhone4S, iPad23G, iPhone5s, iPhone5, iPadFourthGen4G, iPadThirdGen4G, iPodTouchourthGen, iPadMini4G, iPodTouchFifthGen, iPadMini, iPad2Wifi
**Original Artwork:**
<img src="http://a1616.phobos.apple.com/us/r30/Purple3/v4/b0/26/1a/b0261aa7-009f-0592-726c-fb08c6dc3711/mzl.bleskjkr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5615159/ce75d964-94f8-11e4-83cd-0a2fe04eb996.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5615159/ce75d964-94f8-11e4-83cd-0a2fe04eb996.png)
https://cloud.githubusercontent.com/assets/2068130/5615159/ce75d964-94f8-11e4-83cd-0a2fe04eb996.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5615169/e14e391e-94f8-11e4-8ef6-d77957f39ab3.png
