### ISSUE TITLE
VLC streamer Pro

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#4994]
**App Name:** VLC streamer Pro
**Bundle ID:** com.javier.vlc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914805314">914805314</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vlc-streamer-pro/id914805314?mt=8&uo=4">https://itunes.apple.com/us/app/vlc-streamer-pro/id914805314?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** javier bou
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/javier-bou/id914805317?uo=4>© javier bou</a>
**Supported Devices:** iPodTouchFifthGen, iPad23G, iPhone5s, iPodTouchourthGen, iPad2Wifi, iPadThirdGen4G, iPhone4, iPhone5c, iPhone4S, iPhone-3GS, iPadFourthGen4G, iPadFourthGen, iPadThirdGen, iPadMini, iPhone5, iPadMini4G
**Original Artwork:**
<img src="http://a1177.phobos.apple.com/us/r30/Purple4/v4/3c/ca/c6/3ccac690-6786-8252-8fe7-abf95e838a9f/mzl.bywoxazw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5592267/d523b898-91c5-11e4-9fce-73a37a78f83c.png)

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5592267/d523b898-91c5-11e4-9fce-73a37a78f83c.png)
https://cloud.githubusercontent.com/assets/2068130/5592267/d523b898-91c5-11e4-9fce-73a37a78f83c.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5592268/e87c407c-91c5-11e4-81d3-3b27f55fb176.png
Same icon as for #313 and #899.

**Comment by dominicPereira** [comment]
Thanks for your help ^_^

**Comment by dreamnet** [comment]
@dominicPereira No problem, Dominic! :smile:

**Comment by dominicPereira** [comment]
Yup it works already thanks ^_^
