### ISSUE TITLE
Overcast: Podcast Player

### ISSUE THREAD

**Issue by ivamsis** [glasklart/hd#4996]
**App Name:** Overcast: Podcast Player
**Bundle ID:** fm.overcast.overcast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=888422857">888422857</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/overcast-podcast-player/id888422857?mt=8&uo=4">https://itunes.apple.com/us/app/overcast-podcast-player/id888422857?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Overcast Radio, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/overcast-radio-llc/id888422860?uo=4>© Overcast Radio, LLC</a>
**Supported Devices:** iPhone5, iPhone5c, iPhone5s, iPadMini4G, iPodTouchFifthGen, iPadThirdGen4G, iPad2Wifi, iPadFourthGen4G, iPadThirdGen, iPhone4S, iPad23G, iPadFourthGen, iPadMini
**Original Artwork:**
<img src="http://a1059.phobos.apple.com/us/r30/Purple3/v4/ec/d6/1c/ecd61c8e-7ad4-b7ce-3844-566097e36825/mzl.ywtehoyx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611149/d7266352-94c2-11e4-81fe-523d1d3d3ffe.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5605723/6f383fc0-9460-11e4-9620-181108287973.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5605725/91cad6c4-9460-11e4-9aa6-3a5e3a223898.png

**Comment by ivamsis** [comment]
Thanks

**Comment by ivamsis** [comment]
Icon is loading as white square with image how do I import the icon

**Comment by dreamnet** [comment]
@ivamsis Please read [here](https://github.com/glasklart/hd/wiki/How-to-manually-add-icons).

**Comment by cspadazzi** [comment]
Source file updated.

**Comment by dreamnet** [comment]
@cspadazzi The icon is good, but in the source file you have missed something in the antenna.... So here is mine:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611149/d7266352-94c2-11e4-81fe-523d1d3d3ffe.png)
https://cloud.githubusercontent.com/assets/2068130/5611149/d7266352-94c2-11e4-81fe-523d1d3d3ffe.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5611157/e5022d80-94c2-11e4-93f3-dcb037416311.png
