### ISSUE TITLE
Skala View

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#4997]
**App Name:** Skala View
**Bundle ID:** com.bjango.skalaview
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498876303">498876303</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skala-view/id498876303?mt=8&uo=4">https://itunes.apple.com/us/app/skala-view/id498876303?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Marc Edwards
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/marc-edwards/id290155421?uo=4>© Marc Edwards</a>
**Supported Devices:** iPadFourthGen, iPhone5c, iPhone4, iPhone5s, iPhone4S, iPodTouchFifthGen, iPhone5, iPadThirdGen4G, iPadMini4G, iPadMini, iPadFourthGen4G, iPad2Wifi, iPadThirdGen, iPad23G
**Original Artwork:**
<img src="http://a1421.phobos.apple.com/us/r30/Purple3/v4/3f/16/1b/3f161b13-a97e-19fe-eb80-ee58dcb4936a/pr_source.png?downloadKey=1420314046_4867189ae9402602bdcc27cb9f85de5d" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611194/7b84e054-94c3-11e4-9e26-eb70796254cc.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5602981/bcf3dd2a-93c3-11e4-8c9e-c69014842feb.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5602986/f34c337c-93c3-11e4-82c5-23515e5f9ba7.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi Great! :+1:
