### ISSUE TITLE
ING DIRECT Australia Banking

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#4998]
**App Name:** ING DIRECT Australia Banking
**Bundle ID:** com.ingdirect.bankAtPost
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427100193">427100193</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/ing-direct-australia-banking/id427100193?mt=8&uo=4">https://itunes.apple.com/au/app/ing-direct-australia-banking/id427100193?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** ING Bank (Australia) Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/artist/ing-direct/id349621761?uo=4>© ING DIRECT</a>
**Supported Devices:** iPhone5c, iPhone5, iPodTouchFifthGen, iPhone4S, iPhone5s, iPad2Wifi, iPadThirdGen4G, iPadFourthGen4G, iPadThirdGen, iPadMini4G, iPhone4, iPad23G, iPadFourthGen, iPadMini
**Original Artwork:**
<img src="http://a378.phobos.apple.com/us/r30/Purple3/v4/99/a0/93/99a093cd-962c-f48b-c562-c9acbe72d3a0/mzl.sbraxnoq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611259/a0519cbe-94c4-11e4-8ad8-75bf9035aa63.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603000/5e6d24cc-93c4-11e4-83e4-6bc197fbbda1.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603002/6d453e94-93c4-11e4-8a16-89145cf292e5.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi Jup. :+1:
