### ISSUE TITLE
Find ANZ

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#4999]
**App Name:** Find ANZ
**Bundle ID:** com.anz.FindANZ
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=530006262">530006262</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/find-anz/id530006262?mt=8&uo=4">https://itunes.apple.com/us/app/find-anz/id530006262?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** ANZ Banking Group Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/anz-banking-group-limited/id351748977?uo=4>© ANZ Banking Group Limited</a>
**Supported Devices:** iPhone5, iPadThirdGen, iPodTouchFifthGen, iPadMini, iPodTouchourthGen, iPadWifi, iPhone5s, iPadThirdGen4G, iPad23G, iPhone4, iPhone5c, iPadFourthGen4G, iPodTouchThirdGen, iPadMini4G, iPad2Wifi, iPad3G, iPhone-3GS, iPhone4S, iPadFourthGen
**Original Artwork:**
<img src="http://a1314.phobos.apple.com/us/r30/Purple2/v4/46/eb/ab/46ebab66-5534-c8e2-e983-78ee1059c32d/mzl.akqbwhka.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611400/7e327eee-94c6-11e4-96d5-2c19b3b02015.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603003/9aef4204-93c4-11e4-8e8b-ef4277dd3f20.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603004/a6e6d126-93c4-11e4-9888-2e893cc2768e.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
I made the source a bit smoother, else - good! :+1:
