### ISSUE TITLE
Telstra 24x7 for iPhone

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5000]
**App Name:** Telstra 24x7 for iPhone
**Bundle ID:** com.telstra.telstra24x7iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=543829966">543829966</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/telstra-24x7-for-iphone/id543829966?mt=8&uo=4">https://itunes.apple.com/us/app/telstra-24x7-for-iphone/id543829966?mt=8&uo=4</a>
**App Version:** 8.1.2
**Seller:** Telstra Corporation Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/telstra-corporation-ltd/id315429741?uo=4>© Telstra Corporation Ltd</a>
**Supported Devices:** iPadMini4G, iPadThirdGen, iPhone4S, iPadFourthGen, iPad2Wifi, iPadMini, iPadThirdGen4G, iPhone5c, iPodTouchFifthGen, iPadFourthGen4G, iPhone4, iPad23G, iPhone5s, iPhone5
**Original Artwork:**
<img src="http://a1156.phobos.apple.com/us/r30/Purple5/v4/19/80/4b/19804bce-3f0e-51ff-4c0b-752d38a1a60b/mzl.tglckcca.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611449/227184dc-94c7-11e4-9d28-4b5072c50e78.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603008/db27e524-93c4-11e4-94df-2319b076f40a.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603009/e3d36d4c-93c4-11e4-9afe-e8cffa93ff2e.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi Yessir! :+1:
