### ISSUE TITLE
Metacritic Reviews

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5001]
**App Name:** Metacritic Reviews
**Bundle ID:** metacritic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=682730657">682730657</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/metacritic-reviews/id682730657?mt=8&uo=4">https://itunes.apple.com/us/app/metacritic-reviews/id682730657?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Greg STONE
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jack-stone/id480850944?uo=4>© Jack Stone</a>
**Supported Devices:** iPhone4, iPadFourthGen4G, iPadMini, iPad2Wifi, iPhone4S, iPodTouchFifthGen, iPhone5c, iPadMini4G, iPhone5, iPad23G, iPadThirdGen, iPhone5s, iPadThirdGen4G, iPadFourthGen
**Original Artwork:**
<img src="http://a698.phobos.apple.com/us/r30/Purple5/v4/ad/4d/bc/ad4dbc72-f5c6-2658-4a9f-0f5273bb5d3f/mzl.cfwcifii.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611503/bad5bcd4-94c7-11e4-8956-c33afbff9653.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603012/14560a56-93c5-11e4-9590-5775c0c723ad.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603014/2de9ba44-93c5-11e4-804f-b92e70ddeee6.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi The Glasklart icon is just one px to the right, so I remade it:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611503/bad5bcd4-94c7-11e4-8956-c33afbff9653.png)
https://cloud.githubusercontent.com/assets/2068130/5611503/bad5bcd4-94c7-11e4-8956-c33afbff9653.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5611507/cba35c42-94c7-11e4-9e3d-bdd566a1f2f1.png
