### ISSUE TITLE
Cinemas

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5002]
**App Name:** Cinemas
**Bundle ID:** com.neteffective.palacecinemas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=717072842">717072842</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cinemas/id717072842?mt=8&uo=4">https://itunes.apple.com/us/app/cinemas/id717072842?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** Lens & Shutter Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nmg/id330598648?uo=4>© NMG</a>
**Supported Devices:** iPhone5s, iPhone5, iPhone5c, iPadFourthGen, iPhone4, iPadMini4G, iPodTouchFifthGen, iPadThirdGen, iPadFourthGen4G, iPodTouchourthGen, iPadThirdGen4G, iPhone-3GS, iPad23G, iPad2Wifi, iPhone4S, iPadMini
**Original Artwork:**
<img src="http://a1392.phobos.apple.com/us/r30/Purple4/v4/df/b1/06/dfb10628-17ac-954a-d36b-bd155740bee9/mzl.uhbmlgjz.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611565/76e090e8-94c8-11e4-94b4-a74a4c656396.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603021/64925e16-93c5-11e4-9871-fed4bdcf6b59.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603023/6f32aede-93c5-11e4-8800-64013d05d6ec.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi :+1:
