### ISSUE TITLE
The Astor Theatre

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5003]
**App Name:** The Astor Theatre
**Bundle ID:** com.pinionsystems.astor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=563731022">563731022</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-astor-theatre/id563731022?mt=8&uo=4">https://itunes.apple.com/us/app/the-astor-theatre/id563731022?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Nick Randall
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pinion-systems/id414453123?uo=4>© Pinion Systems</a>
**Supported Devices:** iPadFourthGen4G, iPadThirdGen, iPhone5s, iPhone5, iPhone5c, iPadThirdGen4G, iPodTouchFifthGen, iPhone4, iPad2Wifi, iPadMini, iPadMini4G, iPad23G, iPodTouchourthGen, iPhone4S, iPadFourthGen, iPhone-3GS
**Original Artwork:**
<img src="http://a379.phobos.apple.com/us/r30/Purple3/v4/17/6b/16/176b16a9-7e99-74e3-76ce-6644f352cd86/mzl.ckilwcuk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611639/65c9a6ea-94c9-11e4-9d66-ee41f5b1970b.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603029/a5979098-93c5-11e4-8026-003798bd507c.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603032/b3528bac-93c5-11e4-85e4-34dadc8c610b.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi Great one! :+1:
