### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5004]
**App Name:** Slack
**Bundle ID:** com.tinyspeck.chatlyio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=618783545">618783545</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slack/id618783545?mt=8&uo=4">https://itunes.apple.com/us/app/slack/id618783545?mt=8&uo=4</a>
**App Version:** 19.06.10
**Seller:** Slack Technologies, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/slack-technologies-inc/id453420243?mt=8&uo=4">© Slack Technologies, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/92/5d/8d/925d8d30-ed13-f398-567b-8a08f590f1dd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59294514-ef999380-8c81-11e9-8bca-85af5fe6cda3.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603051/2f87a3ba-93c6-11e4-8916-861f6ef9889c.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603040/f3e98a08-93c5-11e4-8479-38498c037820.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi Hum, I think it's better to do something like this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611924/65348372-94cd-11e4-880e-45b3de7802d0.png)
https://cloud.githubusercontent.com/assets/2068130/5611924/65348372-94cd-11e4-880e-45b3de7802d0.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5611932/75440576-94cd-11e4-8e9a-afa82373553f.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Slack
**Bundle ID:** com.tinyspeck.chatlyio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=618783545">618783545</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slack/id618783545?mt=8&uo=4">https://itunes.apple.com/us/app/slack/id618783545?mt=8&uo=4</a>
**App Version:** 19.06.10
**Seller:** Slack Technologies, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/slack-technologies-inc/id453420243?mt=8&uo=4">© Slack Technologies, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/92/5d/8d/925d8d30-ed13-f398-567b-8a08f590f1dd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by cspadazzi** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/6958830/59247197-e8628d80-8c61-11e9-991d-f6be0457844e.png)
Source:
https://user-images.githubusercontent.com/6958830/59247230-003a1180-8c62-11e9-8d5b-b7c8b92baba1.png

**Comment by cspadazzi** [comment]
Been a while, let me know if any issues.

**Comment by dreamnet** [comment]
@cspadazzi Your source is a bit too small, else good work!
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59294514-ef999380-8c81-11e9-8bca-85af5fe6cda3.png)
https://user-images.githubusercontent.com/2068130/59294514-ef999380-8c81-11e9-8bca-85af5fe6cda3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59294551-0344fa00-8c82-11e9-9abe-539b7c7eae7c.png
