### ISSUE TITLE
Photo Guard: protect your private photos from prying eyes!

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5005]
**App Name:** Photo Guard: protect your private photos from prying eyes!
**Bundle ID:** com.synapticwave.photoguard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=488125473">488125473</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photo-guard-protect-your-private/id488125473?mt=8&uo=4">https://itunes.apple.com/us/app/photo-guard-protect-your-private/id488125473?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Pavel Tarabrin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pavel-tarabrin/id331623741?uo=4>© Pavel Tarabrin</a>
**Supported Devices:** iPadThirdGen, iPadMini, iPhone4, iPadFourthGen4G, iPhone4S, iPad23G, iPadFourthGen, iPodTouchFifthGen, iPodTouchourthGen, iPhone5, iPad2Wifi, iPadMini4G, iPhone5c, iPhone5s, iPadThirdGen4G
**Original Artwork:**
<img src="http://a1607.phobos.apple.com/us/r30/Purple4/v4/b0/24/80/b02480bb-2124-38a5-12ef-9d829bcfc07b/mzl.wknvdibw.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5611968/08302a54-94ce-11e4-9527-34fdc98999f4.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603057/77feb6c4-93c6-11e4-9d8b-525828981b69.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603060/87ae179a-93c6-11e4-9eb3-602cd7f347a7.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi Jep, good. :+1:
