### ISSUE TITLE
Quick Scan - QR Code Reader

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5006]
**App Name:** Quick Scan - QR Code Reader
**Bundle ID:** com.ihandysoft.barcode.qr.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=483336864">483336864</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quick-scan-qr-code-reader/id483336864?mt=8&uo=4">https://itunes.apple.com/us/app/quick-scan-qr-code-reader/id483336864?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** iHandy Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ihandy-inc./id291242250?mt=8&uo=4>© iHandy Inc.</a>
**Supported Devices:** iPhone4S, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPhone5, iPad23G, iPodTouchFifthGen, iPhone5c, iPhone5s, iPodTouchourthGen, iPadMini4G, iPhone-3GS, iPhone4, iPadThirdGen, iPadMini, iPad2Wifi
**Original Artwork:**
<img src="http://a374.phobos.apple.com/us/r30/Purple/v4/9a/f5/57/9af5573a-0118-c699-15d2-01b8e0416a1b/mzl.luankdjw.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612019/a6a2e690-94ce-11e4-8cbe-212614365e01.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603071/b314c06e-93c6-11e4-92de-18e0f3699d88.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603073/bbf8ecd2-93c6-11e4-8563-21c2be93c0f8.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi :+1:
