### ISSUE TITLE
Situps Trainer

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5007]
**App Name:** Situps Trainer
**Bundle ID:** com.tomasdelucca.situpstrainer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=523733367">523733367</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/situps-trainer/id523733367?mt=8&uo=4">https://itunes.apple.com/us/app/situps-trainer/id523733367?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Tomas De Lucca
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tomas-de-lucca/id507895155?uo=4>© Tomas De Lucca</a>
**Supported Devices:** iPadThirdGen, iPhone5c, iPad23G, iPadFourthGen4G, iPadMini4G, iPadFourthGen, iPhone5s, iPadMini, iPhone4S, iPhone4, iPodTouchFifthGen, iPhone5, iPadThirdGen4G, iPad2Wifi
**Original Artwork:**
<img src="http://a1234.phobos.apple.com/us/r30/Purple/v4/f6/17/5e/f6175e8b-c56f-4ffc-8e50-ea33144bc658/mzl.fhmlahtr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612066/59e0bafc-94cf-11e4-9190-0bbc974fe7f5.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603079/fe8569cc-93c6-11e4-9e2c-2f55806475d7.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603080/0c00f4cc-93c7-11e4-9f3a-ee70f2f2edb4.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
Just made the source a bit smoother and all the way to the edges:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612066/59e0bafc-94cf-11e4-9190-0bbc974fe7f5.png)
https://cloud.githubusercontent.com/assets/2068130/5612066/59e0bafc-94cf-11e4-9190-0bbc974fe7f5.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5612074/6831eebe-94cf-11e4-881a-a2f8c747a513.png
