### ISSUE TITLE
Pushups Trainer

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5008]
**App Name:** Pushups Trainer
**Bundle ID:** com.tomasdelucca.pushupstrainer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507895152">507895152</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pushups-trainer/id507895152?mt=8&uo=4">https://itunes.apple.com/us/app/pushups-trainer/id507895152?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Tomas De Lucca
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tomas-de-lucca/id507895155?uo=4>© Tomas De Lucca</a>
**Supported Devices:** iPadMini4G, iPad23G, iPhone5s, iPhone5c, iPadThirdGen4G, iPhone4, iPhone5, iPad2Wifi, iPadFourthGen, iPadMini, iPadFourthGen4G, iPadThirdGen, iPodTouchFifthGen, iPhone4S
**Original Artwork:**
<img src="http://a919.phobos.apple.com/us/r30/Purple3/v4/87/73/69/877369bf-6f6f-90f3-e2e0-f07b36794dd9/mzl.mmfepylo.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612124/3a575ab4-94d0-11e4-8ad6-bbaa71150443.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603087/32709cde-93c7-11e4-9673-5b8e61e2a3c0.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603091/5e86c802-93c7-11e4-9085-21723361c249.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi :+1:
