### ISSUE TITLE
Bikesales - Australia's No.1 site for New & Used Bikes

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5009]
**App Name:** Bikesales - Australia's No.1 site for New & Used Bikes
**Bundle ID:** com.carsales.bikesales
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=433070395">433070395</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/bikesales-australias-no.1/id433070395?mt=8&uo=4">https://itunes.apple.com/au/app/bikesales-australias-no.1/id433070395?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Carsales.com Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/artist/carsales.com-ltd./id389044212?uo=4>© carsales.com Ltd.</a>
**Supported Devices:** iPadFourthGen4G, iPadMini4G, iPhone4, iPodTouchFifthGen, iPad23G, iPodTouchourthGen, iPhone4S, iPhone5c, iPad2Wifi, iPadThirdGen, iPhone-3GS, iPadMini, iPhone5, iPadFourthGen, iPadThirdGen4G, iPhone5s
**Original Artwork:**
<img src="http://a1398.phobos.apple.com/us/r30/Purple4/v4/a6/a1/83/a6a18320-552a-5136-87cd-ac8f96d2f28d/mzl.tuxojxjg.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612179/052244b6-94d1-11e4-8536-dbea79409c25.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603096/935299f8-93c7-11e4-9f8a-baa5d3c0fdce.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603097/9c748924-93c7-11e4-9153-a86e45017be5.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi :+1:
