### ISSUE TITLE
Carsales New & Used Cars For Sale

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5010]
**App Name:** Carsales New & Used Cars For Sale
**Bundle ID:** com.carsales.Carsales
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389044209">389044209</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/carsales-new-used-cars-for/id389044209?mt=8&uo=4">https://itunes.apple.com/au/app/carsales-new-used-cars-for/id389044209?mt=8&uo=4</a>
**App Version:** 2.7.3
**Seller:** Carsales.com Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/artist/carsales.com-ltd./id389044212?uo=4>© carsales.com Ltd.</a>
**Supported Devices:** iPodTouchourthGen, iPodTouchFifthGen, iPadFourthGen, iPhone5, iPadFourthGen4G, iPad23G, iPhone5s, iPadThirdGen4G, iPhone4, iPadMini, iPad2Wifi, iPhone-3GS, iPhone5c, iPhone4S, iPadThirdGen, iPadMini4G
**Original Artwork:**
<img src="http://a1593.phobos.apple.com/us/r30/Purple1/v4/fa/e4/cc/fae4cc1d-e5cb-a810-32dd-fb80babcee0f/mzl.zhgskktu.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612240/e8604ca0-94d1-11e4-9def-c7198818691d.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5603101/c5899eda-93c7-11e4-83a2-3e2818b71b40.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5603104/cfc01ab4-93c7-11e4-9ca9-b6f274409d36.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi :+1:
