### ISSUE TITLE
Nintype

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5011]
**App Name:** Nintype
**Bundle ID:** com.jormy.nintype
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=796959534">796959534</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nintype/id796959534?mt=8&uo=4">https://itunes.apple.com/us/app/nintype/id796959534?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Jormy Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jormy-games/id301040524?uo=4>© Jormy Games</a>
**Supported Devices:** iPadThirdGen, iPadMini, iPad23G, iPad2Wifi, iPhone5, iPadFourthGen, iPadThirdGen4G, iPhone5c, iPadMini4G, iPhone4S, iPodTouchFifthGen, iPadFourthGen4G, iPhone5s
**Original Artwork:**
<img src="http://a286.phobos.apple.com/us/r30/Purple1/v4/ff/6d/a1/ff6da1b1-f96e-3df7-a952-8f556e780913/mzl.bgsxbdbr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612320/36b26cd4-94d3-11e4-87ae-871ddf3e0a4b.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5605683/5495e868-945e-11e4-81d7-2b33b71a8291.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5605688/920198b4-945e-11e4-8117-3a82ad6fb636.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi :+1:
