### ISSUE TITLE
triple j

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5012]
**App Name:** triple j
**Bundle ID:** au.net.abc.triplej
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=458003957">458003957</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/triple-j/id458003957?mt=8&uo=4">https://itunes.apple.com/us/app/triple-j/id458003957?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Australian Broadcasting Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/australian-broadcasting-corporation/id306583232?uo=4>© Australian Broadcasting Corporation</a>
**Supported Devices:** iPhone4, iPodTouchourthGen, iPhone5c, iPad2Wifi, iPadFourthGen4G, iPad3G, iPodTouchFifthGen, iPhone-3GS, iPhone5s, iPhone4S, iPad23G, iPadMini4G, iPadMini, iPadThirdGen4G, iPadWifi, iPhone5, iPodTouchThirdGen, iPadFourthGen, iPadThirdGen
**Original Artwork:**
<img src="http://a1859.phobos.apple.com/us/r30/Purple6/v4/59/cf/dc/59cfdc03-bbe9-62cf-ebd4-efaec13c88d9/mzl.zajfewra.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612361/ceab6aa4-94d3-11e4-9cc3-b46e01f8c051.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5605698/c2ff76f2-945e-11e4-9a7f-eb052fc14812.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5605699/d33fad66-945e-11e4-9559-7874225ba860.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
@cspadazzi Jup. :+1:
