### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by cspadazzi** [glasklart/hd#5013]
**App Name:** Google Docs
**Bundle ID:** com.google.Docs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=842842640">842842640</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-docs/id842842640?mt=8&uo=4">https://itunes.apple.com/us/app/google-docs/id842842640?mt=8&uo=4</a>
**App Version:** 1.1.6
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPhone5s, iPadThirdGen4G, iPad23G, iPadMini4G, iPhone5, iPadThirdGen, iPodTouchFifthGen, iPadFourthGen4G, iPadMini, iPhone4S, iPhone5c, iPadFourthGen, iPhone4
**Original Artwork:**
<img src="http://a1364.phobos.apple.com/us/r30/Purple3/v4/c1/89/33/c1893393-5c41-7f71-5449-3e8db7a1756d/mzl.itbagdhw.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612434/473e1902-94d5-11e4-9b92-f09667cbb1d8.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5605703/f7e997f8-945e-11e4-990d-2c91f7d5e9b6.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5605704/0e85551a-945f-11e4-87c3-c36cb867ea7c.png

**Comment by cspadazzi** [comment]
Source & Preview updated.

Thanks.

**Comment by dreamnet** [comment]
Hm, I would prefer this one:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612434/473e1902-94d5-11e4-9b92-f09667cbb1d8.png)
https://cloud.githubusercontent.com/assets/2068130/5612434/473e1902-94d5-11e4-9b92-f09667cbb1d8.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5612436/56b3541a-94d5-11e4-9f20-d57d21a70ffe.png
