### ISSUE TITLE
UE BOOM

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5015]
**App Name:** UE BOOM
**Bundle ID:** com.logitech.ue.ueboom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=632344648">632344648</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ue-boom/id632344648?mt=8&uo=4">https://itunes.apple.com/us/app/ue-boom/id632344648?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** Logitech Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/logitech-inc./id332300071?mt=8&uo=4>© Logitech Inc.</a>
**Supported Devices:** iPhone5c, iPhone4S, iPadMini4G, iPhone-3GS, iPadFourthGen4G, iPad2Wifi, iPadMini, iPhone4, iPodTouchFifthGen, iPhone5, iPhone5s, iPad23G, iPadFourthGen, iPadThirdGen4G, iPodTouchourthGen, iPadThirdGen
**Original Artwork:**
<img src="http://a23.phobos.apple.com/us/r30/Purple3/v4/8a/4e/01/8a4e010a-97a2-8b64-198b-5405d2cb4863/mzl.uyzdhorm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5612766/51c25a5a-94da-11e4-8c64-96073b2f50e9.png)

**Comment by cspadazzi** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6958830/5610950/97bb1e50-9513-11e4-8f55-ddce2420e13e.png)
Source:
https://cloud.githubusercontent.com/assets/6958830/5610963/b88e697a-9513-11e4-8eb4-b6fe132b4c32.png

**Comment by dreamnet** [comment]
@cspadazzi Hm.. OK. :+1:
