### ISSUE TITLE
iON Bond

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5016]
**App Name:** iON Bond
**Bundle ID:** com.SmilingBag.Particle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=877613755">877613755</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ion-bond/id877613755?mt=8&uo=4">https://itunes.apple.com/us/app/ion-bond/id877613755?mt=8&uo=4</a>
**App Version:** 1.02
**Seller:** Stewart Hogarth
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/stewart-hogarth/id699125059?uo=4>© Stewart Hogarth</a>
**Supported Devices:** iPodTouchThirdGen, iPad2Wifi, iPad3G, iPhone5c, iPodTouchFifthGen, iPadThirdGen, iPadMini4G, iPhone4S, iPhone5s, iPadFourthGen, iPodTouchourthGen, iPadFourthGen4G, iPhone-3GS, iPhone4, iPadThirdGen4G, iPadWifi, iPhone5, iPadMini, iPad23G
**Original Artwork:**
<img src="http://a149.phobos.apple.com/us/r30/Purple4/v4/c6/90/ef/c690efda-dd42-534b-c178-e4068d17b405/mzl.reemcgyc.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5614822/30cd6054-94f5-11e4-93f1-9b2a9e07964f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5614822/30cd6054-94f5-11e4-93f1-9b2a9e07964f.png)
https://cloud.githubusercontent.com/assets/2068130/5614822/30cd6054-94f5-11e4-93f1-9b2a9e07964f.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5614833/3e15a49c-94f5-11e4-8fdf-381ed871f5b8.png
