### ISSUE TITLE
Production Calculator 1404

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#5020]
**App Name:** Production Calculator 1404
**Bundle ID:** VyaxWare.Anno-1404-Production-Calculator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527047840">527047840</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/production-calculator-1404/id527047840?mt=8&uo=4">https://itunes.apple.com/us/app/production-calculator-1404/id527047840?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Max Hartwig
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/max-hartwig/id494965291?uo=4>© Max Hartwig</a>
**Supported Devices:** iPadThirdGen4G, iPhone5s, iPadThirdGen, iPodTouchFifthGen, iPhone5, iPhone5c, iPhone4S, iPadFourthGen, iPadMini, iPadFourthGen4G, iPadMini4G, iPad2Wifi, iPhone4, iPad23G
**Original Artwork:**
<img src="http://a1094.phobos.apple.com/us/r30/Purple1/v4/32/16/68/321668a2-7f37-d984-1652-1c284b202b47/mzl.ciaiteth.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5671725/896acd86-978a-11e4-8de9-f9b4217a356f.png)

**Comment by RemiDeluxe** [comment]
We have to find a solution because this app looks the same: https://itunes.apple.com/de/app/warenrechner-2070/id504578852?mt=8

**Comment by dreamnet** [comment]
@RemiDeluxe Thanks for noticing!
Here is an idea:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5671725/896acd86-978a-11e4-8de9-f9b4217a356f.png)
https://cloud.githubusercontent.com/assets/2068130/5671725/896acd86-978a-11e4-8de9-f9b4217a356f.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5671729/94e4e930-978a-11e4-85f2-077d5604b6ca.png

**Comment by dreamnet** [comment]
OK. I'm doing it that way.

**Comment by RemiDeluxe** [comment]
Perfect! Thanks :)
