### ISSUE TITLE
Simpler Contacts - Smart address book manager for iCloud, Gmail, Yahoo & Outlook contacts

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#5021]
**App Name:** Simpler Contacts - Smart address book manager for iCloud, Gmail, Yahoo & Outlook contacts
**Bundle ID:** ytdevelopments.multiedit-free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=665856919">665856919</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/simpler-contacts-smart-address/id665856919?mt=8&uo=4">https://itunes.apple.com/us/app/simpler-contacts-smart-address/id665856919?mt=8&uo=4</a>
**App Version:** 7.0.3
**Seller:** YT Development Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yt-development-ltd/id476148616?uo=4>© YT Development Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/e1/40/43/e14043b1-fefb-1be1-fe12-351f26f0504f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16276320/1beacfec-38ae-11e6-8eb7-6565afada121.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5670967/ee33447e-9784-11e4-8dde-0ac846c3f36b.png)
https://cloud.githubusercontent.com/assets/2068130/5670967/ee33447e-9784-11e4-8dde-0ac846c3f36b.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5670983/020be424-9785-11e4-80c0-62500f37a945.png

**Comment by ivanov007** [comment]
shouldn't this be as the pro version? #2781

**Comment by dreamnet** [comment]
@ivanov007 Yes, you are right, I've missed that.

**Comment by RemiDeluxe** [comment]
Looks very good, thank you :)

**Comment by ivanov007** [comment]
icon changed

**Comment by Trubbel** [comment]
Ehh..

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16248702/06a4b758-3811-11e6-8657-cb4a0043cb55.png)
https://cloud.githubusercontent.com/assets/10730122/16248702/06a4b758-3811-11e6-8657-cb4a0043cb55.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16248701/06a45114-3811-11e6-8638-f1cf6dbb3445.png

**Comment by dreamnet** [comment]
Ehh..

![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16276320/1beacfec-38ae-11e6-8eb7-6565afada121.png)
https://cloud.githubusercontent.com/assets/2068130/16276320/1beacfec-38ae-11e6-8eb7-6565afada121.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16276335/2dfaac70-38ae-11e6-9327-3cd25f8f280f.png

**Comment by Trubbel** [comment]
@dreamnet Yeah yours look better, I think we should go with it!

**Comment by dreamnet** [comment]
@Trubbel OK, I just wanted to be closer to the original.
