### ISSUE TITLE
SuperSlo - Slow Motion Video Editor and Camera

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5025]
**App Name:** SuperSlo - Slow Motion Video Editor and Camera
**Bundle ID:** com.magicappfactory.superslo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=892139752">892139752</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/superslo-slow-motion-video/id892139752?mt=8&uo=4">https://itunes.apple.com/us/app/superslo-slow-motion-video/id892139752?mt=8&uo=4</a>
**App Version:** 1.1.7
**Seller:** Magic App Factory LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/magic-app-factory-llc/id626609660?uo=4>© Magic App Factory LLC</a>
**Supported Devices:** iPadMini4G, iPadThirdGen4G, iPhone4, iPhone5, iPad23G, iPadFourthGen4G, iPhone5c, iPadThirdGen, iPad2Wifi, iPodTouchFifthGen, iPhone4S, iPhone5s, iPadFourthGen, iPadMini
**Original Artwork:**
<img src="http://a1895.phobos.apple.com/us/r30/Purple1/v4/61/ac/5e/61ac5e43-b9e2-3482-2353-6d15f98a1e79/mzl.mzwhqhbb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5676909/ce403a22-97a3-11e4-9ec9-a57e2e82c6cd.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5676909/ce403a22-97a3-11e4-9ec9-a57e2e82c6cd.png)
https://cloud.githubusercontent.com/assets/3090247/5676909/ce403a22-97a3-11e4-9ec9-a57e2e82c6cd.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5676910/ce409954-97a3-11e4-83bc-646d4df6ec5c.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
