### ISSUE TITLE
myWork - Time tracking

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#5026]
**App Name:** myWork - Time tracking
**Bundle ID:** com.marcelruss.myWorkv1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487617582">487617582</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mywork-time-tracking/id487617582?mt=8&uo=4">https://itunes.apple.com/us/app/mywork-time-tracking/id487617582?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** Marcel Russ
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/marcel-russ/id487617585?uo=4>© Marcel Russ</a>
**Supported Devices:** iPadThirdGen4G, iPadThirdGen, iPhone5c, iPad2Wifi, iPadMini, iPhone4, iPhone5, iPadFourthGen, iPadFourthGen4G, iPad23G, iPhone5s, iPodTouchFifthGen, iPadMini4G, iPhone4S
**Original Artwork:**
<img src="http://a1344.phobos.apple.com/us/r30/Purple5/v4/19/b0/19/19b019ba-adfb-c2bb-5e2d-26afb44b195d/mzl.kspsualq.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5676497/557a35b8-979c-11e4-9bb9-e667617520fd.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5676497/557a35b8-979c-11e4-9bb9-e667617520fd.png)
https://cloud.githubusercontent.com/assets/3090247/5676497/557a35b8-979c-11e4-9bb9-e667617520fd.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5676498/557c74c2-979c-11e4-8046-3ea3d2cbfb7e.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
