### ISSUE TITLE
eBay

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#504]
**App Name:** eBay
**Bundle ID:** com.ebay.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=282614216">282614216</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ebay/id282614216?mt=8&uo=4">https://itunes.apple.com/us/app/ebay/id282614216?mt=8&uo=4</a>
**App Version:** 3.5.2
**Seller:** eBay Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ebay-inc./id282614219?uo=4>© eBay Inc.</a>
**Supported Devices:** iPad2Wifi, iPhone6Plus, iPadThirdGen, iPhone5c, iPhone5s, iPadThirdGen4G, iPadMini4G, iPhone4S, iPadFourthGen4G, iPhone5, iPhone6, iPadFourthGen, iPhone4, iPadMini, iPad23G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a1114.phobos.apple.com/us/r30/Purple5/v4/fe/0e/22/fe0e22a9-e015-fbb9-0007-145b6ad8d89a/mzl.xbjogdkn.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6986416/08b5d49c-da0b-11e4-8ca8-c2fb7ef24f6a.png)

**Comment by zmathiasz** [comment]
**App Name:** eBay
**Bundle ID:** com.ebay.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=282614216">282614216</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ebay/id282614216?mt=8&uo=4">https://itunes.apple.com/us/app/ebay/id282614216?mt=8&uo=4</a>
**App Version:** 3.5.2
**Seller:** eBay Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ebay-inc./id282614219?uo=4>© eBay Inc.</a>
**Supported Devices:** iPad2Wifi, iPhone4S, iPadMini, iPhone5, iPadMini4G, iPhone6Plus, iPhone4, iPodTouchFifthGen, iPhone5c, iPhone6, iPhone5s, iPadFourthGen4G, iPadThirdGen, iPad23G, iPadThirdGen4G, iPadFourthGen
**Original Artwork:**
<img src="http://a1114.phobos.apple.com/us/r30/Purple5/v4/fe/0e/22/fe0e22a9-e015-fbb9-0007-145b6ad8d89a/mzl.xbjogdkn.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by zmathiasz** [comment]
@dreamnet 

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6986416/08b5d49c-da0b-11e4-8ca8-c2fb7ef24f6a.png)
https://cloud.githubusercontent.com/assets/10950389/6986416/08b5d49c-da0b-11e4-8ca8-c2fb7ef24f6a.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6986427/14d283e2-da0b-11e4-83c3-54e93222d14b.png
