### ISSUE TITLE
Duck Life

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5044]
**App Name:** Duck Life
**Bundle ID:** com.mad.ducklife
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=611071723">611071723</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/duck-life/id611071723?mt=8&uo=4">https://itunes.apple.com/us/app/duck-life/id611071723?mt=8&uo=4</a>
**App Version:** 1.05
**Seller:** MoFunZone Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mofunzone-inc/id611071726?uo=4>© MoFunZone Inc</a>
**Supported Devices:** iPad3G, iPhone4S, iPadFourthGen, iPhone5, iPodTouchourthGen, iPhone-3GS, iPhone4, iPadWifi, iPad23G, iPad2Wifi, iPhone5c, iPhone5s, iPadThirdGen4G, iPodTouchThirdGen, iPadMini4G, iPodTouchFifthGen, iPadMini, iPadFourthGen4G, iPadThirdGen
**Original Artwork:**
<img src="http://a489.phobos.apple.com/us/r30/Purple2/v4/39/64/c4/3964c480-2179-60ca-7238-8618f15600eb/mzl.synxrakl.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5717502/4f8da7a6-9ac7-11e4-94fa-f75daca58d24.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=![com mad ducklife 2x](https://cloud.githubusercontent.com/assets/3090247/5717502/4f8da7a6-9ac7-11e4-94fa-f75daca58d24.png)
![com mad ducklife 2x](https://cloud.githubusercontent.com/assets/3090247/5717502/4f8da7a6-9ac7-11e4-94fa-f75daca58d24.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5717501/4f875932-9ac7-11e4-8b9c-b52c276b9c46.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
