### ISSUE TITLE
Trivia Crack

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5045]
**App Name:** Trivia Crack
**Bundle ID:** com.etermax.preguntados
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=651510680">651510680</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trivia-crack/id651510680?mt=8&uo=4">https://itunes.apple.com/us/app/trivia-crack/id651510680?mt=8&uo=4</a>
**App Version:** 1.9.2
**Seller:** Etermax
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/etermax/id286461525?uo=4>© Etermax</a>
**Supported Devices:** iPhone5s, iPad2Wifi, iPadMini4G, iPadFourthGen, iPhone-3GS, iPadFourthGen4G, iPodTouchourthGen, iPadMini, iPhone4S, iPodTouchFifthGen, iPad23G, iPhone5, iPhone4, iPadThirdGen, iPhone5c, iPadThirdGen4G
**Original Artwork:**
<img src="http://a1640.phobos.apple.com/us/r30/Purple3/v4/7c/d0/a2/7cd0a202-ddc2-12ac-f28a-6ca13ea25280/mzl.pqqploiy.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5746463/1ccd1882-9c30-11e4-8b44-004fb4a60fe4.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5740617/40178820-9c05-11e4-8433-b5b7484b15cc.png)

Source
https://cloud.githubusercontent.com/assets/10515074/5740628/567f29c4-9c05-11e4-9e50-3adc80d0e3b3.png

**Comment by dreamnet** [comment]
@andreolidavide Well done icon - can't say what it is, but there's something that bothers me, so here is my icon for this: 
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5746463/1ccd1882-9c30-11e4-8b44-004fb4a60fe4.png)
https://cloud.githubusercontent.com/assets/2068130/5746463/1ccd1882-9c30-11e4-8b44-004fb4a60fe4.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5746486/451510c4-9c30-11e4-8c46-ce030f504f4c.png
P.S.: Please always post the direct link to the icon like I do. And the icon in your source file is too small.
