### ISSUE TITLE
Zombie Highway 2

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5046]
**App Name:** Zombie Highway 2
**Bundle ID:** com.auxbrain.zh2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=892092770">892092770</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zombie-highway-2/id892092770?mt=8&uo=4">https://itunes.apple.com/us/app/zombie-highway-2/id892092770?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Auxbrain, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/auxbrain-inc./id302520821?uo=4>© Auxbrain, Inc.</a>
**Supported Devices:** iPhone5c, iPadFourthGen, iPadFourthGen4G, iPhone5s, iPhone4S, iPadThirdGen, iPad23G, iPad2Wifi, iPadThirdGen4G, iPhone5, iPadMini, iPadMini4G, iPhone4, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a596.phobos.apple.com/us/r30/Purple1/v4/48/54/a6/4854a6cc-8d45-372d-7c88-78b60a5c2771/mzl.imbecsxr.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5717586/dd023970-9ac8-11e4-975c-ef741f9a43e2.png)

**Comment by ivanov007** [comment]
not sure witch one will looks better maybe the firs one to match the prequel
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5717586/dd023970-9ac8-11e4-975c-ef741f9a43e2.png)
https://cloud.githubusercontent.com/assets/3090247/5717586/dd023970-9ac8-11e4-975c-ef741f9a43e2.png

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5717585/dcf1be42-9ac8-11e4-903a-3fcf79127195.png)
https://cloud.githubusercontent.com/assets/3090247/5717585/dcf1be42-9ac8-11e4-903a-3fcf79127195.png

**Comment by dreamnet** [comment]
@ivanov007 Yeah, I took the first one. :+1:
