### ISSUE TITLE
Credit Karma: Free Credit Scores, Reports & Alerts

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5049]
**App Name:** Credit Karma: Free Credit Scores, Reports & Alerts
**Bundle ID:** com.creditkarma.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519817714">519817714</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/credit-karma-free-credit-scores/id519817714?mt=8&uo=4">https://itunes.apple.com/us/app/credit-karma-free-credit-scores/id519817714?mt=8&uo=4</a>
**App Version:** 4.4.2
**Seller:** Credit Karma, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/credit-karma-inc./id519816000?uo=4">© Credit Karma, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/31/24/51/312451c9-5053-760c-b92c-f81120510356/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21015065/c22712ee-bd60-11e6-8a8d-991707a72efe.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5717646/f5c38b2a-9ac9-11e4-82b5-518da2236f7a.png)
https://cloud.githubusercontent.com/assets/3090247/5717646/f5c38b2a-9ac9-11e4-82b5-518da2236f7a.png
Source:
![com creditkarma mobile](https://cloud.githubusercontent.com/assets/3090247/5717647/f5c39f5c-9ac9-11e4-9985-5b34a10bde36.png)

**Comment by dreamnet** [comment]
@ivanov007 Perfect!

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Credit Karma: Free Credit Scores, Reports & Alerts
**Bundle ID:** com.creditkarma.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519817714">519817714</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/credit-karma-free-credit-scores/id519817714?mt=8&uo=4">https://itunes.apple.com/us/app/credit-karma-free-credit-scores/id519817714?mt=8&uo=4</a>
**App Version:** 4.4.2
**Seller:** Credit Karma, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/credit-karma-inc./id519816000?uo=4">© Credit Karma, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/31/24/51/312451c9-5053-760c-b92c-f81120510356/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21015065/c22712ee-bd60-11e6-8a8d-991707a72efe.png)
https://cloud.githubusercontent.com/assets/20930745/21015065/c22712ee-bd60-11e6-8a8d-991707a72efe.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21015076/d3f258c6-bd60-11e6-84cd-c2ad54ef9e6f.png
