### ISSUE TITLE
TriMet Tickets

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5052]
**App Name:** TriMet Tickets
**Bundle ID:** org.trimet.mt.mobiletickets
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=687943985">687943985</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trimet-tickets/id687943985?mt=8&uo=4">https://itunes.apple.com/us/app/trimet-tickets/id687943985?mt=8&uo=4</a>
**App Version:** 1.3.5
**Seller:** TRI-COUNTY METROPOLITAN TRANSPORTATION DISTRICT OF OREGON
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/trimet/id687943988?uo=4>© TriMet</a>
**Supported Devices:** iPadThirdGen4G, iPadFourthGen, iPodTouchFifthGen, iPhone4, iPad2Wifi, iPhone4S, iPadFourthGen4G, iPadThirdGen, iPadMini, iPhone5, iPad23G, iPhone5c, iPadMini4G, iPhone5s
**Original Artwork:**
<img src="http://a1378.phobos.apple.com/us/r30/Purple4/v4/d8/8d/c9/d88dc916-e729-a959-2a29-e9eec3bd3c2c/mzl.dxbczfki.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5715944/4e60d112-9a97-11e4-8313-616f81f4ded7.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5715944/4e60d112-9a97-11e4-8313-616f81f4ded7.png)

**Comment by PolarisBeaver** [comment]
Source Image: https://cloud.githubusercontent.com/assets/10394552/5715945/584aaae0-9a97-11e4-8277-40e78abc59f2.png

**Comment by ivanov007** [comment]
@PolarisBeaver :+1:

**Comment by dreamnet** [comment]
@PolarisBeaver Good work! :+1:
