### ISSUE TITLE
PDX Bus, MAX, Streetcar and WES

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5053]
**App Name:** PDX Bus, MAX, Streetcar and WES
**Bundle ID:** org.teleportaloo.PDXBus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=289814055">289814055</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pdx-bus-max-streetcar-and-wes/id289814055?mt=8&uo=4">https://itunes.apple.com/us/app/pdx-bus-max-streetcar-and-wes/id289814055?mt=8&uo=4</a>
**App Version:** 7.2
**Seller:** Andrew Wallace
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/teleportaloo/id289814058?uo=4>© Teleportaloo</a>
**Supported Devices:** iPodTouchThirdGen, iPadWifi, iPhone5c, iPad2Wifi, iPadMini, iPhone5s, iPhone-3GS, iPadThirdGen, iPodTouchFifthGen, iPadThirdGen4G, iPhone4S, iPadFourthGen4G, iPodTouchourthGen, iPadFourthGen, iPhone5, iPad3G, iPhone4, iPad23G, iPadMini4G
**Original Artwork:**
<img src="http://a467.phobos.apple.com/us/r30/Purple3/v4/9f/01/c0/9f01c0d3-d67a-a646-9e8b-3391903283d7/mzl.ofvcuzaz.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716046/6d5c486a-9a99-11e4-9e33-3b3f7b679e51.png)

**Comment by PolarisBeaver** [comment]
Unfortunately, due to the nature of this icon looking like "train doors", the way Glasklart icons are formatted would not allow for the icon to translate in a manner consistent with the icon, and it would end up just looking like a couple awkward geometric shapes.

Quick backstory, this application is specifically targeted at the Portland Oregon demographic exclusively and it is pertaining to the Transit Tracker service which provided by Trimet.

Trimet's logo would be a very appropriate substitute in this case, and people with the theme from Portland will easily recognize it without so much as a second glance considering the logo is very prominent in all Trimet related services, ads, apps, etc. Please understand this when considering this request even though my submission might appear to look very different from the original icon

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716046/6d5c486a-9a99-11e4-9e33-3b3f7b679e51.png)

Source Image: https://cloud.githubusercontent.com/assets/10394552/5716048/7cf7af8a-9a99-11e4-877f-2e2662c52866.png

**Comment by dreamnet** [comment]
@PolarisBeaver Yeah, I think that's OK. I take your icon. :+1:
