### ISSUE TITLE
pixiv

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5054]
**App Name:** pixiv
**Bundle ID:** net.pxv.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=337248563">337248563</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pixiv/id337248563?mt=8&uo=4">https://itunes.apple.com/us/app/pixiv/id337248563?mt=8&uo=4</a>
**App Version:** 5.3.1
**Seller:** Pixiv Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pixiv-inc./id337248566?uo=4>© pixiv Inc.</a>
**Supported Devices:** iPad23G, iPodTouchFifthGen, iPadThirdGen4G, iPhone4S, iPhone5, iPadFourthGen4G, iPhone5c, iPadFourthGen, iPhone4, iPad2Wifi, iPadMini, iPhone5s, iPadThirdGen, iPadMini4G
**Original Artwork:**
<img src="http://a944.phobos.apple.com/us/r30/Purple1/v4/99/e9/e7/99e9e77f-3c6d-5577-339c-c65b5d1f64de/pr_source.png?downloadKey=1421134271_9b1c7ce743c372e682eee11fd95b63a0" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716185/cd4e808c-9a9c-11e4-977d-2ff319254080.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716185/cd4e808c-9a9c-11e4-977d-2ff319254080.png)

Source Image: https://cloud.githubusercontent.com/assets/10394552/5716187/d9baa152-9a9c-11e4-9d1e-eaaf7a6e246b.png

**Comment by ivanov007** [comment]
@PolarisBeaver :+1:
