### ISSUE TITLE
MyWater

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5055]
**App Name:** MyWater
**Bundle ID:** com.demandmedia.watertracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=665244736">665244736</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mywater/id665244736?mt=8&uo=4">https://itunes.apple.com/us/app/mywater/id665244736?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Demand Media, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/demand-media-inc./id295305244?mt=8&uo=4>© Demand Media, Inc.</a>
**Supported Devices:** iPadThirdGen4G, iPhone4S, iPhone5, iPhone5c, iPhone4, iPadFourthGen, iPhone5s, iPad23G, iPhone-3GS, iPadMini, iPodTouchFifthGen, iPadThirdGen, iPodTouchourthGen, iPad2Wifi, iPadFourthGen4G, iPadMini4G
**Original Artwork:**
<img src="http://a1343.phobos.apple.com/us/r30/Purple4/v4/5c/96/25/5c96250a-ee38-7877-0341-f265edf0263e/mzl.yibczyzf.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716247/eb4a08f2-9a9e-11e4-92fc-d591ed514475.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716247/eb4a08f2-9a9e-11e4-92fc-d591ed514475.png)

Image Source: https://cloud.githubusercontent.com/assets/10394552/5716249/f5b941f4-9a9e-11e4-8924-343898c50cbf.png

**Comment by ivanov007** [comment]
@PolarisBeaver :+1:
