### ISSUE TITLE
MyPlate Calorie Tracker - Your Diet and Fitness Calorie Counter for Better Health by LIVESTRONG.COM -

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5056]
**App Name:** MyPlate Calorie Tracker - Your Diet and Fitness Calorie Counter for Better Health by LIVESTRONG.COM -
**Bundle ID:** com.demandmedia.calorietrackerlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=502317923">502317923</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myplate-calorie-tracker-your/id502317923?mt=8&uo=4">https://itunes.apple.com/us/app/myplate-calorie-tracker-your/id502317923?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** Demand Media, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/demand-media-inc./id295305244?mt=8&uo=4>© Demand Media, Inc.</a>
**Supported Devices:** iPad23G, iPhone5c, iPadMini, iPodTouchFifthGen, iPad2Wifi, iPadThirdGen, iPhone5s, iPhone5, iPadFourthGen4G, iPadMini4G, iPhone4S, iPadFourthGen, iPadThirdGen4G, iPhone4
**Original Artwork:**
<img src="http://a1047.phobos.apple.com/us/r30/Purple5/v4/57/d4/7e/57d47ea6-d569-0a70-945e-ea8643e8febd/pr_source.png?downloadKey=1421136683_759e5e61073a4660aa8d4bbcb0f4ccbc" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716430/25bd47c0-9aa3-11e4-90d7-36f57bcc9ebd.png)

**Comment by PolarisBeaver** [comment]
BEFORE considering this icon submission, I really am not sure how to go about improving this, the cut-off silverware is a little odd-looking, what do you suggest I do to make this more... natural for the lack of a better word.

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716430/25bd47c0-9aa3-11e4-90d7-36f57bcc9ebd.png)

Source Image: https://cloud.githubusercontent.com/assets/10394552/5716431/2ea33db8-9aa3-11e4-852b-85c98690dd30.png

**Comment by PolarisBeaver** [comment]
Again, before approving, read above the icon submission

**Comment by ivanov007** [comment]
@PolarisBeaver I know it loos kind of odd but that's the way the icon is so I say it's a ggo :+1:

**Comment by PolarisBeaver** [comment]
Will do for my future submissions
