### ISSUE TITLE
IP Network Scanner Lite

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5057]
**App Name:** IP Network Scanner Lite
**Bundle ID:** com.10baseT.IPScannerLite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335517828">335517828</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ip-network-scanner-lite/id335517828?mt=8&uo=4">https://itunes.apple.com/us/app/ip-network-scanner-lite/id335517828?mt=8&uo=4</a>
**App Version:** 3.26
**Seller:** Eric Redlinger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/10base-t-interactive/id288454707?uo=4>© 10base-t Interactive</a>
**Supported Devices:** iPadThirdGen4G, iPodTouchFifthGen, iPhone4, iPadThirdGen, iPhone5, iPad2Wifi, iPhone4S, iPhone5s, iPad23G, iPadMini4G, iPhone5c, iPadFourthGen4G, iPadMini, iPadFourthGen
**Original Artwork:**
<img src="http://a1716.phobos.apple.com/us/r30/Purple1/v4/f2/be/8a/f2be8ab8-6fe8-3a4e-0736-c2c79d4a26b5/mzl.lsorgmpk.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716728/d35aa1fc-9aa8-11e4-9b91-f010e3e298b4.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716689/30259802-9aa8-11e4-822c-b20e38b6d48a.png)
https://cloud.githubusercontent.com/assets/10394552/5716689/30259802-9aa8-11e4-822c-b20e38b6d48a.png

Source Image: https://cloud.githubusercontent.com/assets/10394552/5716696/4ca799e4-9aa8-11e4-978f-bf31b4d6c781.png

**Comment by ivanov007** [comment]
@PolarisBeaver :+1:

**Comment by dreamnet** [comment]
The source file it too small on this one, here is a correct one:
https://cloud.githubusercontent.com/assets/2068130/5723727/79ad0caa-9b46-11e4-89f7-73c87cf92295.png

**Comment by PolarisBeaver** [comment]
Oh weird, how did you tell it was the wrong DPI and what can I do to ensure I have the right DPI in the future?

**Comment by dreamnet** [comment]
@PolarisBeaver This is not a big problem. You can open your source file and mine in photoshop and compare them. I don't know how you make the sourcefiles (I make almost everything in Adobe Illustrator as a vector file and then export it as png), just make sure that the source has 1024x1024px and 72 dpi.

**Comment by PolarisBeaver** [comment]
I was using Inkscape for some of them, and Illustrator for others, though I wasn't paying close enough attention to the DPI settings, but now I know!

Also slightly off topic but how do I go about collecting the proper info for Cydia apps? There's no iTunes IDs to generate the opening issue with.

**Comment by dreamnet** [comment]
@PolarisBeaver Please check our [WIKI](https://github.com/glasklart/hd/wiki/How-to-Request-a-Cydia-Icon) and if you have any questions about this, feel free to ask.
