### ISSUE TITLE
IP Network Scanner

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5058]
**App Name:** IP Network Scanner
**Bundle ID:** com.10baseT.Scanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335517657">335517657</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ip-network-scanner/id335517657?mt=8&uo=4">https://itunes.apple.com/us/app/ip-network-scanner/id335517657?mt=8&uo=4</a>
**App Version:** 3.26
**Seller:** Eric Redlinger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/10base-t-interactive/id288454707?uo=4>© 10base-t Interactive</a>
**Supported Devices:** iPhone4, iPadFourthGen, iPad2Wifi, iPhone5, iPad23G, iPadFourthGen4G, iPhone4S, iPadThirdGen4G, iPhone5c, iPadMini, iPodTouchFifthGen, iPadMini4G, iPadThirdGen, iPhone5s
**Original Artwork:**
<img src="http://a205.phobos.apple.com/us/r30/Purple3/v4/76/66/20/76662067-2be9-fa3c-48fc-7ce9862e2671/mzl.dunawiqs.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716728/d35aa1fc-9aa8-11e4-9b91-f010e3e298b4.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716728/d35aa1fc-9aa8-11e4-9b91-f010e3e298b4.png)
https://cloud.githubusercontent.com/assets/10394552/5716728/d35aa1fc-9aa8-11e4-9b91-f010e3e298b4.png

Source Image: https://cloud.githubusercontent.com/assets/10394552/5716733/e5c85dc0-9aa8-11e4-8dad-605b10f1a5fe.png

**Comment by ivanov007** [comment]
@PolarisBeaver great :+1:
