### ISSUE TITLE
McD App

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5059]
**App Name:** McD App
**Bundle ID:** com.gaaf.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=562542654">562542654</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mcd-app/id562542654?mt=8&uo=4">https://itunes.apple.com/us/app/mcd-app/id562542654?mt=8&uo=4</a>
**App Version:** 1.81
**Seller:** Mowingo Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mowingo-inc./id452700021?uo=4>© Mowingo, Inc.</a>
**Supported Devices:** iPad23G, iPhone4S, iPhone-3GS, iPadFourthGen, iPadFourthGen4G, iPadThirdGen, iPodTouchFifthGen, iPhone5s, iPadMini, iPadThirdGen4G, iPhone5c, iPhone5, iPodTouchourthGen, iPad2Wifi, iPhone4, iPadMini4G
**Original Artwork:**
<img src="http://a1428.phobos.apple.com/us/r30/Purple5/v4/57/63/d3/5763d3c3-3695-6c39-1674-81acd2c15703/mzl.cypurnll.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716952/04f3a7e6-9aad-11e4-9a1e-f795cce72397.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5716952/04f3a7e6-9aad-11e4-9a1e-f795cce72397.png)
https://cloud.githubusercontent.com/assets/10394552/5716952/04f3a7e6-9aad-11e4-9a1e-f795cce72397.png

Source Image: https://cloud.githubusercontent.com/assets/10394552/5716954/1584fc86-9aad-11e4-9a1e-a8cb43900fea.png

**Comment by ivanov007** [comment]
mhhh is this the same a special app or just a regular McDonalds App like #1844?

**Comment by PolarisBeaver** [comment]
It is an official McDonalds app (for coupons), and is used in the U.S.

The other app you linked is different.

**Comment by ivanov007** [comment]
ok then i think it's ok the text to make it different :+1:

**Comment by dreamnet** [comment]
@PolarisBeaver Compliment, good work on all your last contributions!! We always need talented graphic artists like you. Thank's a lot. :+1: :+1: :+1:
