### ISSUE TITLE
Alerts for Warframe

### ISSUE THREAD

**Issue by andreolidavide** [glasklart/hd#5061]
**App Name:** Alerts for Warframe
**Bundle ID:** com.skiesoft.warframealerts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=775981113">775981113</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alerts-for-warframe/id775981113?mt=8&uo=4">https://itunes.apple.com/us/app/alerts-for-warframe/id775981113?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** Viktor Gubriienko
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/viktor-gubriienko/id775981117?uo=4>© Viktor Gubriienko</a>
**Supported Devices:** iPad23G, iPadMini4G, iPhone5, iPadThirdGen4G, iPodTouchFifthGen, iPadFourthGen, iPadThirdGen, iPhone4S, iPhone-3GS, iPhone5c, iPhone5s, iPadMini, iPhone4, iPodTouchourthGen, iPad2Wifi, iPadFourthGen4G
**Original Artwork:**
<img src="http://a1203.phobos.apple.com/us/r30/Purple1/v4/1b/e5/4d/1be54dde-7baf-ff7b-3560-a1e54cfa9d5e/pr_source.png?downloadKey=1421162250_be56a1923fe258caa816571283b95f4a" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5731463/f496c568-9b83-11e4-8b17-7bc178d264bb.png)

**Comment by andreolidavide** [comment]
![com skiesoft warframealerts 2x](https://cloud.githubusercontent.com/assets/10515074/5720671/a1ee1750-9b27-11e4-8dc2-a4a5aa486ba5.png)

**Comment by PolarisBeaver** [comment]
Try adding some thin lines for the leaves.

**Comment by andreolidavide** [comment]
Something like this? 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5722059/10069b8e-9b39-11e4-988b-7c7d3ced7cf1.png)

**Comment by dreamnet** [comment]
@andreolidavide Yes, you are getting close, good work! Can you please try to make the lines a bit thicker? - and we always need the source file.

**Comment by andreolidavide** [comment]
Is this any better?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5727838/4c2d4ec8-9b66-11e4-939a-b11084765fb5.png)

Source
https://cloud.githubusercontent.com/assets/10515074/5727870/78d4049e-9b66-11e4-8e55-a766e2e66459.png

**Comment by dreamnet** [comment]
@andreolidavide Yes this looks good, but you have forgotten to apply the Glasklart style and the icon in the source file is too small - Here is a correct one:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5731463/f496c568-9b83-11e4-8b17-7bc178d264bb.png)
https://cloud.githubusercontent.com/assets/2068130/5731463/f496c568-9b83-11e4-8b17-7bc178d264bb.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5731467/03b8c848-9b84-11e4-8735-17bba20ab0e6.png
You have done good work anyway - if you add a public mailadress to your Github account I give you credits for this icon.

**Comment by andreolidavide** [comment]
@dreamnet
Added.
I think that's because I was using GIMP, I will figure this out and continue contributing to the community

**Comment by ivanov007** [comment]
@dreamnet wow I once tried to do the icons with GIMP and I simply couldn't, well at the end I think you have to do the layer thing on photoshop, I think there's a free version you can use, CS2 if I'm not mistaken, let me see if I can get you the link

**Comment by andreolidavide** [comment]
@ivanov007 you're great, I didn't know this, I'm downloading it right now.
Thanks man, it will help me!
