### ISSUE TITLE
Cookie Jam

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5063]
**App Name:** Cookie Jam
**Bundle ID:** com.sgn.cookiejam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=727296976">727296976</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cookie-jam/id727296976?mt=8&uo=4">https://itunes.apple.com/us/app/cookie-jam/id727296976?mt=8&uo=4</a>
**App Version:** 3.0.108
**Seller:** SGN
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sgn/id290671617?uo=4>© SGN</a>
**Supported Devices:** iPodTouchFifthGen, iPad2Wifi, iPhone4S, iPadMini4G, iPhone5s, iPadThirdGen4G, iPhone5c, iPadMini, iPhone-3GS, iPodTouchourthGen, iPadFourthGen4G, iPhone5, iPad23G, iPhone4, iPadThirdGen, iPadFourthGen
**Original Artwork:**
<img src="http://a1645.phobos.apple.com/us/r30/Purple5/v4/0f/f3/1f/0ff31fe2-c723-1d98-49c9-add46b7c042a/mzl.gluojqwp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5768377/9ef1c1f6-9d10-11e4-81f2-a40e2750a758.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5768377/9ef1c1f6-9d10-11e4-81f2-a40e2750a758.png)
https://cloud.githubusercontent.com/assets/2068130/5768377/9ef1c1f6-9d10-11e4-81f2-a40e2750a758.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5768386/adc0e34c-9d10-11e4-84ea-53b0153eaa27.png
