### ISSUE TITLE
iBlank for iOS 7 and iOS8

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5064]
**App Name:** iBlank for iOS 7 and iOS8
**Bundle ID:** com.microseconds.iBlank5
**Version:** 5.1 
**iTunes ID:** none (Cydia app)
**Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/2068130/5743543/3ae12ec8-9c1a-11e4-847c-822d8cfff692.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5788686/3c0514c2-9e45-11e4-89a2-cf39504b0aac.png)

**Comment by dreamnet** [comment]
What about adding a complete transparent (only the baseplate) icon for this?

**Comment by PolarisBeaver** [comment]
A plain faceplate would probably be appropriate for this, yes.

**Comment by dreamnet** [comment]
...or something like this:...?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5788686/3c0514c2-9e45-11e4-89a2-cf39504b0aac.png)
https://cloud.githubusercontent.com/assets/2068130/5788686/3c0514c2-9e45-11e4-89a2-cf39504b0aac.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5788689/4a6f29b2-9e45-11e4-9568-a21dc0b1bfbb.png

**Comment by boxermansr** [comment]
@dreamnet That's perfect in my opinion. Copied it to my device and it looks great as well.

**Comment by dreamnet** [comment]
Yes, on secont thought I also think it's better than a blank icon.

**Comment by Anuskuss** [comment]
Do we still need the old version of iBlank (just noticed there are two versions)?
