### ISSUE TITLE
MUJO

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5065]
**App Name:** MUJO
**Bundle ID:** com.oinkgms.um
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=882416288">882416288</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mujo/id882416288?mt=8&uo=4">https://itunes.apple.com/us/app/mujo/id882416288?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Oink Games Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/oink-games-inc./id532425963?uo=4>© Oink Games Inc.</a>
**Supported Devices:** iPadThirdGen, iPhone-3GS, iPodTouchFifthGen, iPhone5, iPadThirdGen4G, iPad2Wifi, iPhone4S, iPhone5s, iPhone5c, iPhone4, iPadFourthGen, iPodTouchourthGen, iPadMini, iPadFourthGen4G, iPad23G, iPadMini4G
**Original Artwork:**
<img src="http://a1913.phobos.apple.com/us/r30/Purple1/v4/7a/e6/db/7ae6dbd4-9061-f5b6-f7f3-45bda77c8ba5/mzl.ksayodal.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5855921/1ed1a49a-a23e-11e4-87a9-48d4525ebf1d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5773539/47773564-9d29-11e4-84e2-e39d8e620ee8.png)
https://cloud.githubusercontent.com/assets/3090247/5773539/47773564-9d29-11e4-84e2-e39d8e620ee8.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5773540/4779d5f8-9d29-11e4-9f79-3fece67a4e49.png

**Comment by dreamnet** [comment]
@ivanov007 Hm, what about this?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5788431/62b0ee9e-9e35-11e4-9059-e0e8ae45c68e.png)
https://cloud.githubusercontent.com/assets/2068130/5788431/62b0ee9e-9e35-11e4-9059-e0e8ae45c68e.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5788432/718f7b42-9e35-11e4-9bfd-eee100cdcb56.png

**Comment by ivanov007** [comment]
@dreamnet mhh I don't know, maybe if the hair were black... I'm really not sure

**Comment by dreamnet** [comment]
@ivanov007 Well, it's your issue... Whatever you like is OK for me. :wink:

**Comment by MagnaMike** [comment]
Another choice
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/5849069/1eee9e64-a1ae-11e4-8109-b63eb6b52d15.png)
https://cloud.githubusercontent.com/assets/2236254/5849069/1eee9e64-a1ae-11e4-8109-b63eb6b52d15.png
Source:
https://cloud.githubusercontent.com/assets/2236254/5849079/353908e4-a1ae-11e4-8888-d8b07e953c9d.png

**Comment by dreamnet** [comment]
@MagnaMike Yes, that's also good, I like this most - only the source file is not correct, here is a correct one:
https://cloud.githubusercontent.com/assets/2068130/5855505/569ff6f6-a239-11e4-84a8-5b48d956b1a4.png
Just compare your source file and mine and you will see what I mean. The 1024x1024px of the source file "represents" the 78x78px area in the Glasklart icon.

**Comment by MagnaMike** [comment]
@dreamnet Ah, that makes sense. :+1:

**Comment by dreamnet** [comment]
@MagnaMike Yeah, the sense of this is, that if we can easily make bigger icons in the future if needed.
