### ISSUE TITLE
Ruben is sleepy

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5066]
**App Name:** Ruben is sleepy
**Bundle ID:** net.tvndra.ruben
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=867507085">867507085</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ruben-is-sleepy/id867507085?mt=8&uo=4">https://itunes.apple.com/us/app/ruben-is-sleepy/id867507085?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Tvndra Producties
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tvndra-producties/id514399822?uo=4>© Tvndra Producties</a>
**Supported Devices:** iPadFourthGen4G, iPodTouchThirdGen, iPad3G, iPadMini4G, iPhone5s, iPodTouchourthGen, iPhone5c, iPadFourthGen, iPhone-3GS, iPodTouchFifthGen, iPadThirdGen4G, iPadWifi, iPad23G, iPhone5, iPhone4S, iPadThirdGen, iPad2Wifi, iPadMini, iPhone4
**Original Artwork:**
<img src="http://a479.phobos.apple.com/us/r30/Purple3/v4/e5/09/e5/e509e5d9-d0f9-27af-1a7b-5d26d9bffd35/pr_source.png?downloadKey=1421409779_f455e8261dd9f3982a0958481caf89bc" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5773931/e5df8072-9d2d-11e4-9408-c06cbab9bc5a.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5773931/e5df8072-9d2d-11e4-9408-c06cbab9bc5a.png)
https://cloud.githubusercontent.com/assets/3090247/5773931/e5df8072-9d2d-11e4-9408-c06cbab9bc5a.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5773932/e5eb77f6-9d2d-11e4-8f53-6a8e3fbf2305.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
