### ISSUE TITLE
Ruben is sleepy Free

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5067]
**App Name:** Ruben is sleepy Free
**Bundle ID:** net.tvndra.rubenf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=947905960">947905960</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ruben-is-sleepy-free/id947905960?mt=8&uo=4">https://itunes.apple.com/us/app/ruben-is-sleepy-free/id947905960?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Tvndra Producties
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tvndra-producties/id514399822?uo=4>© Tvndra Producties</a>
**Supported Devices:** iPadThirdGen, iPhone-3GS, iPhone4, iPad23G, iPhone5c, iPodTouchThirdGen, iPadWifi, iPhone5s, iPadFourthGen4G, iPad2Wifi, iPad3G, iPadThirdGen4G, iPodTouchFifthGen, iPodTouchourthGen, iPhone5, iPadMini4G, iPhone4S, iPadFourthGen, iPadMini
**Original Artwork:**
<img src="http://a1398.phobos.apple.com/us/r30/Purple5/v4/a9/24/f4/a924f42c-f723-911b-5e98-529d2a46c9c3/pr_source.png?downloadKey=1421410573_7c832da512fc3ec0f80ed7c1ecad6248" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5773931/e5df8072-9d2d-11e4-9408-c06cbab9bc5a.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5773931/e5df8072-9d2d-11e4-9408-c06cbab9bc5a.png)
https://cloud.githubusercontent.com/assets/3090247/5773931/e5df8072-9d2d-11e4-9408-c06cbab9bc5a.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5773932/e5eb77f6-9d2d-11e4-8f53-6a8e3fbf2305.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
