### ISSUE TITLE
WWE Immortals

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#5069]
**App Name:** WWE Immortals
**Bundle ID:** com.wb.WWE.Brawler2014
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=941421328">941421328</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wwe-immortals/id941421328?mt=8&uo=4">https://itunes.apple.com/us/app/wwe-immortals/id941421328?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Warner Bros. Entertainment
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/warner-bros./id298372283?uo=4>© Warner Bros.</a>
**Supported Devices:** iPodTouchFifthGen, iPhone5c, iPadFourthGen, iPhone6Plus, iPad23G, iPhone4S, iPadThirdGen4G, iPhone4, iPhone5s, iPodTouchFourthGen, iPadFourthGen4G, iPad2Wifi, iPadMini, iPadThirdGen, iPhone5, iPhone6, iPadMini4G
**Original Artwork:**
<img src="http://a541.phobos.apple.com/us/r30/Purple3/v4/48/df/51/48df518c-0e90-75aa-7685-0f6897da8d41/pr_source.png?downloadKey=1421516041_6b900fcdc2eaa4622eea2affc70a40de" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5819529/e8e31984-a0be-11e4-92b5-02d0b632386e.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5819529/e8e31984-a0be-11e4-92b5-02d0b632386e.png)
https://cloud.githubusercontent.com/assets/10515074/5819529/e8e31984-a0be-11e4-92b5-02d0b632386e.png

Source
https://cloud.githubusercontent.com/assets/10515074/5819539/fa6b372c-a0be-11e4-9dff-bb81437a9923.png

**Comment by dreamnet** [comment]
@andreolidavide Yes, that's good! :+1: P.S.: I corrected your source.
