### ISSUE TITLE
Zombies, Run! 5k Training

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#507]
**App Name:** Zombies, Run! 5k Training
**Bundle ID:** com.sixtostart.zombies5k
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=566596422">566596422</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zombies-run-5k-training/id566596422?mt=8&uo=4">https://itunes.apple.com/us/app/zombies-run-5k-training/id566596422?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Six to Start
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/six-to-start/id323684916?uo=4">© Six to Start</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/57/b2/03/57b2036f-f985-fb11-53ed-a8d76467e9f8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26435534/1ee420fc-4110-11e7-9872-286eccc1558a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26435534/1ee420fc-4110-11e7-9872-286eccc1558a.png)
https://cloud.githubusercontent.com/assets/2068130/26435534/1ee420fc-4110-11e7-9872-286eccc1558a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26435547/2f326e1e-4110-11e7-816d-5d396eb43249.png
