### ISSUE TITLE
Hermes Paketversand

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#5070]
**App Name:** Hermes Paketversand
**Bundle ID:** de.hermes-europe.hermes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=359428628">359428628</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hermes-paketversand/id359428628?uo=4">https://apps.apple.com/us/app/hermes-paketversand/id359428628?uo=4</a>
**App Version:** 6.8.3
**Seller:** Hermes Germany GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hermes-germany-gmbh/id359428631?uo=4">© Hermes Germany GmbH</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/77/01/66/770166d3-bd70-b955-7cf5-2a663a2d275c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60773027-e7a50600-a0fe-11e9-9fe0-a998933206b9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5791874/2851a6cc-9ef7-11e4-925b-50f934b69d54.png)
https://cloud.githubusercontent.com/assets/2068130/5791874/2851a6cc-9ef7-11e4-925b-50f934b69d54.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5791875/3635cafc-9ef7-11e4-8757-63da0a4002fc.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60773027-e7a50600-a0fe-11e9-9fe0-a998933206b9.png)
https://user-images.githubusercontent.com/2068130/60773027-e7a50600-a0fe-11e9-9fe0-a998933206b9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60773030-f8557c00-a0fe-11e9-9903-ee721f2e308e.png
