### ISSUE TITLE
L’ORÉAL PARiS privée – Die Treue-App für L’ORÉAL PARiS Kunden

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#5071]
**App Name:** L’ORÉAL PARiS privée – Die Treue-App für L’ORÉAL PARiS Kunden
**Bundle ID:** com.loreal.privee
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=774812886">774812886</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/loreal-paris-privee-die-treue/id774812886?mt=8&uo=4">https://itunes.apple.com/de/app/loreal-paris-privee-die-treue/id774812886?mt=8&uo=4</a>
**App Version:** 1.20
**Seller:** L'Oreal
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/loreal/id522002181?uo=4>© L'Oreal</a>
**Supported Devices:** iPadFourthGen, iPhone5, iPhone6, iPhone4, iPadThirdGen, iPodTouchFourthGen, iPhone5c, iPadMini4G, iPhone6Plus, iPhone-3GS, iPadFourthGen4G, iPad23G, iPodTouchFifthGen, iPad2Wifi, iPadMini, iPhone5s, iPadThirdGen4G, iPhone4S
**Original Artwork:**
<img src="http://a51.phobos.apple.com/us/r30/Purple5/v4/bb/c9/d1/bbc9d12c-3e64-f3a2-601e-28a79e7a4272/mzl.zawvakbp.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5791902/a7da9d20-9ef9-11e4-8cfd-9ea6b9ca2a39.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5791902/a7da9d20-9ef9-11e4-8cfd-9ea6b9ca2a39.png)
https://cloud.githubusercontent.com/assets/2068130/5791902/a7da9d20-9ef9-11e4-8cfd-9ea6b9ca2a39.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5791903/b5646aa2-9ef9-11e4-8f65-ae954ba2a9ac.png
