### ISSUE TITLE
Tenderfoot

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5072]
**App Name:** Tenderfoot
**Bundle ID:** com.tenderfootapp.Tenderfoot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=888563467">888563467</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tenderfoot/id888563467?mt=8&uo=4">https://itunes.apple.com/us/app/tenderfoot/id888563467?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Tenderfoot Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tenderfoot-pty-ltd/id888563470?uo=4>© Tenderfoot Pty Ltd</a>
**Supported Devices:** iPhone5, iPadThirdGen, iPhone4S, iPadFourthGen4G, iPodTouchFifthGen, iPhone5c, iPad2Wifi, iPhone6, iPhone5s, iPad23G, iPhone4, iPadThirdGen4G, iPadFourthGen, iPhone6Plus, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://a1065.phobos.apple.com/us/r30/Purple1/v4/04/ca/13/04ca13a8-9b03-ba28-37f6-b12793bb1655/pr_source.png?downloadKey=1421639856_feb3d2dc287a7aa394133f45c9f514e1" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/5800407/6876df26-a021-11e4-8de8-aba6e71a1a86.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/5800407/6876df26-a021-11e4-8de8-aba6e71a1a86.png)
https://cloud.githubusercontent.com/assets/10008202/5800407/6876df26-a021-11e4-8de8-aba6e71a1a86.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/5800432/ce9aec2a-a021-11e4-8fec-28415e79bf70.png

**Comment by dreamnet** [comment]
@iNfeCtGFX Jup, good one. :+1:
