### ISSUE TITLE
Cash Passport

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5073]
**App Name:** Cash Passport
**Bundle ID:** com.accessprepaid.chameleon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=663429657">663429657</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/cash-passport/id663429657?mt=8&uo=4">https://itunes.apple.com/gb/app/cash-passport/id663429657?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** ACCESS PREPAID WORLDWIDE LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/artist/access-prepaid-worldwide-ltd/id663429660?uo=4>© Access Prepaid Worldwide Ltd</a>
**Supported Devices:** iPadMini, iPadFourthGen4G, iPhone4, iPhone6Plus, iPadFourthGen, iPodTouchFifthGen, iPad2Wifi, iPad23G, iPhone6, iPhone5s, iPhone5, iPadThirdGen4G, iPadMini4G, iPadThirdGen, iPhone4S, iPhone5c
**Original Artwork:**
<img src="http://a354.phobos.apple.com/us/r30/Purple4/v4/66/1b/f6/661bf6d8-3731-18d8-7f29-7522f394575c/mzl.ndfkrcst.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/5800701/8bd0b344-a025-11e4-9296-1a5fc923bb21.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/5800701/8bd0b344-a025-11e4-9296-1a5fc923bb21.png)
https://cloud.githubusercontent.com/assets/10008202/5800701/8bd0b344-a025-11e4-9296-1a5fc923bb21.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/5800712/a4fc69e4-a025-11e4-97c5-c24a0db691b4.png

**Comment by dreamnet** [comment]
@iNfeCtGFX Yessir! :+1:
