### ISSUE TITLE
How to Tie a Tie Free - animated guide for necktie, scarves, bowtie, ascots...

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#5074]
**App Name:** How to Tie a Tie Free - animated guide for necktie, scarves, bowtie, ascots...
**Bundle ID:** com.artelplus.howtotie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378478530">378478530</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/how-to-tie-tie-free-animated/id378478530?mt=8&uo=4">https://itunes.apple.com/us/app/how-to-tie-tie-free-animated/id378478530?mt=8&uo=4</a>
**App Version:** 7.3
**Seller:** Damir Nigomedyanov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/damir-nigomedyanov/id378478533?uo=4>© Damir Nigomedyanov</a>
**Supported Devices:** iPodTouchFifthGen, iPhone4S, iPhone5s, iPhone5, iPad2Wifi, iPhone6Plus, iPhone4, iPad23G, iPadThirdGen4G, iPadMini4G, iPhone6, iPadFourthGen, iPhone5c, iPadFourthGen4G, iPadThirdGen, iPadMini
**Original Artwork:**
<img src="http://a1342.phobos.apple.com/us/r30/Purple5/v4/cc/c0/91/ccc09169-629c-edb2-3fbe-b1392921e6c0/mzl.anqahqiu.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/5834803/9ab33048-a161-11e4-8a73-c49de98046d5.png)

**Comment by andreolidavide** [comment]
Something like this?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5817480/90e30f4e-a0ac-11e4-9f7a-755db44df503.png)
https://cloud.githubusercontent.com/assets/10515074/5817480/90e30f4e-a0ac-11e4-9f7a-755db44df503.png

Source
https://cloud.githubusercontent.com/assets/10515074/5817502/c7a0b1b2-a0ac-11e4-87fd-8d45eff91700.png

**Comment by dreamnet** [comment]
@andreolidavide Jup, I like it. :+1:
