### ISSUE TITLE
Strong - Workout Tracker and Training Log for Bodybuilding, Weightlifting, Fitness and Strength Routines

### ISSUE THREAD

**Issue by grigsby** [glasklart/hd#5075]
**App Name:** Strong - Workout Tracker and Training Log for Bodybuilding, Weightlifting, Fitness and Strength Routines
**Bundle ID:** com.cameronchow.Strong
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=464254577">464254577</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/strong-workout-tracker-training/id464254577?mt=8&uo=4">https://itunes.apple.com/us/app/strong-workout-tracker-training/id464254577?mt=8&uo=4</a>
**App Version:** 2.9.3
**Seller:** Cameron Chow
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/cameron-chow/id380916999?uo=4>© Cameron Chow</a>
**Supported Devices:** iPhone4S, iPadThirdGen, iPadMini, iPhone5s, iPadThirdGen4G, iPhone5, iPhone5c, iPhone4, iPadFourthGen4G, iPhone6, iPhone6Plus, iPadFourthGen, iPodTouchFifthGen, iPad2Wifi, iPad23G, iPadMini4G
**Original Artwork:**
<img src="http://a254.phobos.apple.com/us/r30/Purple3/v4/05/c3/ac/05c3ac22-a0bf-063e-1f24-5717c3f09126/mzl.daeswxoj.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5835193/431d7144-a12b-11e4-9a12-8c4fafc03e40.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5835193/431d7144-a12b-11e4-9a12-8c4fafc03e40.png)
https://cloud.githubusercontent.com/assets/3090247/5835193/431d7144-a12b-11e4-9a12-8c4fafc03e40.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5835192/43171146-a12b-11e4-83e3-046147e0ac75.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:

**Comment by grigsby** [comment]
Yay! Thank you!

**Comment by dreamnet** [comment]
@grigsby Well... we are sorry... :cry: :wink: :laughing:

**Comment by ivanov007** [comment]
@grigsby just to let you know, when you're fulfilling your own issues you donn't have to wait for the valid tag, you can post the icon right away on the first comment :smile:
