### ISSUE TITLE
Pampers

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5076]
**App Name:** Pampers
**Bundle ID:** com.pampers.de.PampersMobilie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506648489">506648489</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/pampers/id506648489?mt=8&uo=4">https://itunes.apple.com/de/app/pampers/id506648489?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Procter & Gamble Service GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/procter-gamble/id419356792?uo=4>© Procter & Gamble</a>
**Supported Devices:** iPhone5c, iPhone6, iPadThirdGen4G, iPodTouchFourthGen, iPhone5, iPadThirdGen, iPad23G, iPadMini4G, iPadFourthGen, iPhone6Plus, iPhone5s, iPhone4S, iPadMini, iPad2Wifi, iPodTouchFifthGen, iPhone-3GS, iPadFourthGen4G, iPhone4
**Original Artwork:**
<img src="http://a653.phobos.apple.com/us/r30/Purple5/v4/81/90/17/8190174d-2b3c-0d4e-900e-7ad89c7989ef/pr_source.png?downloadKey=1421836232_c31c8d38575e456b55aa277e6ea71282" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5835126/7ceb4956-a12a-11e4-9512-1bc8108ad0c6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5835126/7ceb4956-a12a-11e4-9512-1bc8108ad0c6.png)
https://cloud.githubusercontent.com/assets/3090247/5835126/7ceb4956-a12a-11e4-9512-1bc8108ad0c6.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5835125/7cbed470-a12a-11e4-9457-0616e919bfbe.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
