### ISSUE TITLE
Looney Tunes Dash!

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5077]
**App Name:** Looney Tunes Dash!
**Bundle ID:** com.zynga.looneytunes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=852801667">852801667</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/looney-tunes-dash!/id852801667?mt=8&uo=4">https://itunes.apple.com/us/app/looney-tunes-dash!/id852801667?mt=8&uo=4</a>
**App Version:** 1.46.2
**Seller:** Zynga Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/zynga-inc./id295913422?mt=8&uo=4>© Zynga Inc.</a>
**Supported Devices:** iPadThirdGen4G, iPhone5s, iPad2Wifi, iPadFourthGen, iPodTouchFourthGen, iPadMini4G, iPadFourthGen4G, iPhone4S, iPhone6, iPhone5c, iPadMini, iPhone4, iPhone6Plus, iPodTouchFifthGen, iPadThirdGen, iPad23G, iPhone5
**Original Artwork:**
<img src="http://a1129.phobos.apple.com/us/r30/Purple3/v4/bf/e4/22/bfe42269-247e-11c8-2cee-3d873ea61358/mzl.velgjvef.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5856687/a9abf672-a245-11e4-8944-98761ba694d2.png)

**Comment by dreamnet** [comment]
Not the original, but...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5835747/6cca3054-a16c-11e4-8f75-e3dc7c407cf9.png)
https://cloud.githubusercontent.com/assets/2068130/5835747/6cca3054-a16c-11e4-8f75-e3dc7c407cf9.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5835754/7c1be0c0-a16c-11e4-983a-792fd9c441f4.png
