### ISSUE TITLE
Candy Crush Soda Saga

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5078]
**App Name:** Candy Crush Soda Saga
**Bundle ID:** com.midasplayer.apps.candycrushsodasaga
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=850417475">850417475</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/candy-crush-soda-saga/id850417475?mt=8&uo=4">https://itunes.apple.com/us/app/candy-crush-soda-saga/id850417475?mt=8&uo=4</a>
**App Version:** 1.34.27
**Seller:** King.com Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/king.com-limited/id526656015?uo=4>© King.com Limited</a>
**Supported Devices:** iPadThirdGen4G, iPhone4, iPad3G, iPhone6Plus, iPhone4S, iPhone6, iPadMini, iPadFourthGen4G, iPadWifi, iPhone5c, iPodTouchThirdGen, iPadThirdGen, iPad23G, iPodTouchFifthGen, iPhone-3GS, iPad2Wifi, iPhone5s, iPhone5, iPodTouchFourthGen, iPadFourthGen, iPadMini4G
**Original Artwork:**
<img src="http://a426.phobos.apple.com/us/r30/Purple3/v4/b3/dc/6b/b3dc6b49-772b-c176-8f5b-b061e4bb5fe5/pr_source.png?downloadKey=1422006548_271293348d8a84ccb344f83b0887b938" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/5869279/8d8ffb3e-a284-11e4-8866-82c82c9e39ef.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/5863230/e87a35bc-a245-11e4-818b-54112e01ed05.png)
https://cloud.githubusercontent.com/assets/2236254/5863230/e87a35bc-a245-11e4-818b-54112e01ed05.png
Source:
https://cloud.githubusercontent.com/assets/2236254/5863227/de8612ce-a245-11e4-9030-fa21fd277b95.png

**Comment by dreamnet** [comment]
@MagnaMike I don't want to be pesky, but if it's possbible - yes. The original icon seems to be for a "winter edition", I think tis is the normal icon:
https://cloud.githubusercontent.com/assets/2068130/5863558/a85ee4b6-a27a-11e4-80a6-4c642b4151f5.jpg

**Comment by MagnaMike** [comment]
@dreamnet No worries. This is the best I can do with what I know of illustrator so far. 
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/5869279/8d8ffb3e-a284-11e4-8866-82c82c9e39ef.png)
https://cloud.githubusercontent.com/assets/2236254/5869279/8d8ffb3e-a284-11e4-8866-82c82c9e39ef.png
Source:
https://cloud.githubusercontent.com/assets/2236254/5869287/b58b8d1a-a284-11e4-8314-639661a95e75.png

**Comment by ivanov007** [comment]
@dreamnet just updated the first post with the "normal" icon

**Comment by dreamnet** [comment]
@MagnaMike @ivanov007 Jup, THX!
