### ISSUE TITLE
Knots 3D

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5079]
**App Name:** Knots 3D
**Bundle ID:** com.nynix.animatedknots3d
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=453571750">453571750</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/knots-3d/id453571750?mt=8&uo=4">https://itunes.apple.com/us/app/knots-3d/id453571750?mt=8&uo=4</a>
**App Version:** 4.2.2
**Seller:** David Boren
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nynix/id425939481?uo=4>© Nynix</a>
**Supported Devices:** iPadMini4G, iPadThirdGen, iPhone5s, iPadFourthGen4G, iPad2Wifi, iPhone5, iPad23G, iPadThirdGen4G, iPhone6, iPhone4S, iPhone6Plus, iPhone4, iPhone-3GS, iPadMini, iPodTouchFourthGen, iPhone5c, iPodTouchFifthGen, iPadFourthGen
**Original Artwork:**
<img src="http://a121.phobos.apple.com/us/r30/Purple3/v4/49/07/82/490782f3-60ae-0e82-1ce2-88ecffd54016/pr_source.png?downloadKey=1421836671_1b7d527a9f7c1e0eb92c0839ec93ad5a" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5837408/41765104-a17f-11e4-8d87-0abd0d00b092.png)

**Comment by andreolidavide** [comment]
Should I remove 3D or do you like it?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5836416/abaa6b0a-a175-11e4-93a5-f0676142f3dd.png)
https://cloud.githubusercontent.com/assets/10515074/5836416/abaa6b0a-a175-11e4-93a5-f0676142f3dd.png

Source
https://cloud.githubusercontent.com/assets/10515074/5836370/1619e732-a175-11e4-8d58-06ac0da7e365.png

**Comment by dreamnet** [comment]
@andreolidavide No, all good. :+1:
