### ISSUE TITLE
PicsArt Photo Studio

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5080]
**App Name:** PicsArt Photo Studio
**Bundle ID:** com.picsart.studio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=587366035">587366035</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/picsart-photo-studio/id587366035?mt=8&uo=4">https://itunes.apple.com/us/app/picsart-photo-studio/id587366035?mt=8&uo=4</a>
**App Version:** 5.0.1
**Seller:** Socialin Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/picsart/id587366038?uo=4>© PicsArt</a>
**Supported Devices:** iPhone6Plus, iPadFourthGen, iPhone6, iPhone4, iPadFourthGen4G, iPhone5c, iPhone4S, iPadThirdGen4G, iPhone5s, iPadThirdGen, iPadMini, iPad2Wifi, iPhone5, iPodTouchFifthGen, iPad23G, iPadMini4G
**Original Artwork:**
<img src="http://a1041.phobos.apple.com/us/r30/Purple3/v4/a0/a8/9b/a0a89bca-9c0e-25d1-c68e-dbe97d9c5a70/mzl.zwidinfz.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5837470/d5558a84-a17f-11e4-8b15-5382e78c6570.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5836159/dbfced2c-a171-11e4-838e-f3f67b6aea21.png)
https://cloud.githubusercontent.com/assets/10515074/5836159/dbfced2c-a171-11e4-838e-f3f67b6aea21.png

Source
https://cloud.githubusercontent.com/assets/10515074/5836176/05a19312-a172-11e4-8199-4db362288643.png

Is the source ok this time?

**Comment by dreamnet** [comment]
@andreolidavide Yes, it is! Good work! :+1:
