### ISSUE TITLE
Forecast+ | Weather & Forecast Widget

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5081]
**App Name:** Forecast+ | Weather & Forecast Widget
**Bundle ID:** com.avaniolabs.forecastplus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916416931">916416931</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/forecast+-weather-forecast/id916416931?mt=8&uo=4">https://itunes.apple.com/us/app/forecast+-weather-forecast/id916416931?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Avanio Labs Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/avanio-labs/id916415257?uo=4>© Avanio Labs</a>
**Supported Devices:** iPhone5, iPodTouchFifthGen, iPad2Wifi, iPadMini4G, iPadThirdGen, iPadFourthGen4G, iPadMini, iPadThirdGen4G, iPhone5c, iPhone4S, iPhone6Plus, iPadFourthGen, iPhone6, iPad23G, iPhone5s
**Original Artwork:**
<img src="http://a1606.phobos.apple.com/us/r30/Purple3/v4/21/5f/a2/215fa230-6a42-2cfe-0ff9-2bd5b5e1a493/pr_source.png?downloadKey=1421836897_ffc7ffdf8e9856c5dfe86fd856187ccd" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5834997/ff152cb4-a128-11e4-8b8c-f5158e516694.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5834997/ff152cb4-a128-11e4-8b8c-f5158e516694.png)
https://cloud.githubusercontent.com/assets/3090247/5834997/ff152cb4-a128-11e4-8b8c-f5158e516694.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5834998/ff167b0a-a128-11e4-9b1a-9d577aeb8403.png

**Comment by dreamnet** [comment]
@ivanov007 Jup! :+1:
