### ISSUE TITLE
WEB to PDF

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5082]
**App Name:** WEB To PDF
**Bundle ID:** com.dar-soft.WebToPDFiPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=439658054">439658054</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/web-to-pdf/id439658054?mt=8&uo=4">https://itunes.apple.com/us/app/web-to-pdf/id439658054?mt=8&uo=4</a>
**App Version:** 2.9.0
**Seller:** Darsoft Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/darsoft-inc./id417954209?uo=4>© Darsoft Inc.</a>
**Supported Devices:** iPadWifi, iPad3G, iPhone5s, iPadMini, iPhone6Plus, iPadMini4G, iPodTouchFifthGen, iPadThirdGen, iPhone-3GS, iPhone5, iPad2Wifi, iPad23G, iPadFourthGen4G, iPodTouchFourthGen, iPhone4, iPhone4S, iPadThirdGen4G, iPadFourthGen, iPhone5c, iPodTouchThirdGen, iPhone6
**Original Artwork:**
<img src="http://a614.phobos.apple.com/us/r30/Purple4/v4/11/33/bb/1133bb14-e833-1413-790b-f0d2ba6a68fd/mzl.vmsdnegm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5842976/764a3f92-a1a9-11e4-8530-817abdc83a42.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5842976/764a3f92-a1a9-11e4-8530-817abdc83a42.png)
https://cloud.githubusercontent.com/assets/2068130/5842976/764a3f92-a1a9-11e4-8530-817abdc83a42.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5842989/845dfac4-a1a9-11e4-9531-75fc5cb86f9d.png
