### ISSUE TITLE
[DUPLICATE of #2456]

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5083]
**App Name:** AIRBLUE SHARING
 **Bundle ID:**  com.ericday.blued-obex
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="###PLEASE FILL THIS OUT###" width="150" height="150" />
 **Accepted Artwork:**
 \#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
@Gwai  the original artwork is needed

**Comment by dreamnet** [comment]
Is this the same as #2456?

**Comment by Gwai** [comment]
Yes, it is ggf same like #2456

**Comment by dreamnet** [comment]
@Gwai If it is the same app as #2456, then we don't need to add another icon, we just need to rename the existiing icon, so I mark this issue as duplicate, close it and reopen #2456.
