### ISSUE TITLE
oO

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5084]
**App Name:** oO
**Bundle ID:** com.rainbowtrain.oo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834240887">834240887</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/oo/id834240887?mt=8&uo=4">https://itunes.apple.com/us/app/oo/id834240887?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Maciej Targoni
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/maciej-targoni/id495165602?uo=4>© Maciej Targoni</a>
**Supported Devices:** iPadWifi, iPadFourthGen, iPhone6, iPadThirdGen, iPhone5c, iPad2Wifi, iPad3G, iPhone4, iPhone6Plus, iPad23G, iPadFourthGen4G, iPodTouchFourthGen, iPodTouchFifthGen, iPadMini4G, iPhone5s, iPadThirdGen4G, iPodTouchThirdGen, iPhone-3GS, iPhone5, iPhone4S, iPadMini
**Original Artwork:**
<img src="http://a54.phobos.apple.com/us/r30/Purple/v4/6b/c7/5d/6bc75d61-fc4b-dff1-692e-5b12eb317ab1/mzl.mmokdbwj.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5847813/84027d7a-a19f-11e4-9f20-a3fd7fecd6fd.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5847813/84027d7a-a19f-11e4-9f20-a3fd7fecd6fd.png)

https://cloud.githubusercontent.com/assets/2236254/5847813/84027d7a-a19f-11e4-9f20-a3fd7fecd6fd.png

**Comment by MagnaMike** [comment]
I started off easy @dreamnet :wink:

**Comment by ivanov007** [comment]
@MagnaMike hey long time no see, glad you're back, I see you cached up with the new fulfill templates, great work :+1:

**Comment by MagnaMike** [comment]
@ivanov007 Long time no see indeed. Thanks, I'm trying to learn illustrator so I'll be sticking to the easier icons for a bit at least!

**Comment by dreamnet** [comment]
@MagnaMike Great! :+1:
