### ISSUE TITLE
JELLIES!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5085]
**App Name:** JELLIES!
**Bundle ID:** com.52hwgames.JELLIES
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=853087982">853087982</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jellies!/id853087982?mt=8&uo=4">https://itunes.apple.com/us/app/jellies!/id853087982?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Aleksei Kalinin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/aleksei-kalinin/id853087985?uo=4>© Aleksei Kalinin</a>
**Supported Devices:** iPhone6Plus, iPadFourthGen4G, iPadMini, iPhone5, iPadMini4G, iPodTouchFifthGen, iPodTouchFourthGen, iPad2Wifi, iPhone5c, iPhone-3GS, iPadThirdGen4G, iPadFourthGen, iPadThirdGen, iPad23G, iPhone5s, iPhone4S, iPhone4, iPhone6
**Original Artwork:**
<img src="http://a1497.phobos.apple.com/us/r30/Purple1/v4/23/15/5e/23155eba-4f6f-3162-00b5-d116f0ee8e90/mzl.gszytfel.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5851082/2d97544c-a1c7-11e4-8dfe-19871a82aaec.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5851082/2d97544c-a1c7-11e4-8dfe-19871a82aaec.png)
https://cloud.githubusercontent.com/assets/3090247/5851082/2d97544c-a1c7-11e4-8dfe-19871a82aaec.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5851089/463489a2-a1c7-11e4-975f-7e96981a3a8e.png

**Comment by dreamnet** [comment]
@ivanov007 Great one! :+1:
