### ISSUE TITLE
Fake Email

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#5087]
**App Name:** Fake Email
 **Bundle ID:**  com.kobisnir.New-Message
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="http://www.ioslinks.com/icons/newmessage.png" width="150" height="150" />
 **Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5863396/9176d82c-a279-11e4-959e-7754d76d04dd.png)

**Comment by dreamnet** [comment]
@kieman We need the original artwork.

**Comment by kieman** [comment]
Here it is :) sorry

**Comment by dreamnet** [comment]
@kieman OK, and here is the icon:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5863396/9176d82c-a279-11e4-959e-7754d76d04dd.png)
https://cloud.githubusercontent.com/assets/2068130/5863396/9176d82c-a279-11e4-959e-7754d76d04dd.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5863364/5e29bc8c-a279-11e4-8719-61bd28e5e61b.png

**Comment by kieman** [comment]
THX :)
