### ISSUE TITLE
Anemone

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5088]
**App Name:** Anemone
**Bundle ID:** com.anemonetheming.anemone
**iTunes ID:** none (Cydia app)
**App Version:** 0.1~nightly-279
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/9430052/c4dbdb62-49e6-11e5-93d8-2b1314f3fb03.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9430201/5de04a6e-49ec-11e5-8bec-33285bac2e68.png)

**Comment by dreamnet** [comment]
Note: This app is still in beta. Maybe we will use it for Glasklart, if released.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5864394/02461b3c-a282-11e4-9d1e-21ab717842a7.png)
https://cloud.githubusercontent.com/assets/2068130/5864394/02461b3c-a282-11e4-9d1e-21ab717842a7.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5864406/1188b442-a282-11e4-9dcc-0dcfd0745405.png

**Comment by ivanov007** [comment]
@dreamnet have you tried it? do you have the repo?

**Comment by dreamnet** [comment]
@ivanov007 Yes, I am currently on it. It's in alpha (not beta) state, but it runs stable on my iPad 3 and my iPhone 4. The repo is `anemonetheming.com/nightly/`. You have to remove IconBundles and ThemeLib. The only bug i noticed is, that the icons themed with the IconBundles method are still displayed 2px too big, everything else looks good.
P.S.: I don't want to discuss Anemone itself here, this isssue is only for the icon.

**Comment by dreamnet** [comment]
Icon has updated.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9430201/5de04a6e-49ec-11e5-8bec-33285bac2e68.png)
https://cloud.githubusercontent.com/assets/2068130/9430201/5de04a6e-49ec-11e5-8bec-33285bac2e68.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9430202/6d9450ea-49ec-11e5-9abe-8428ea3b2627.png
