### ISSUE TITLE
Using Anemone for Glasklart?

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5091]
There is a new theme engine out here, called [Anemone](https://twitter.com/Anemone_iOS). As I write this, Anemone is still in an ALPHA state. Anemone supports the IconBundles method and a view other tweaks, witch Winterboard does not. By installing Anemone, the IconBundles plugin and ThemeLib are not needed anymore. Glasklart DOES NOT run with Anemone out-of -the-box, it needs a view tweaks.
Here is a Screenshot of what I get unsing Anemone (0.1~nightly-7) on my old iPhone4 (with iOS7.1.2) with a view, small changes (especially to the Info.plist files) in Glasklart:
<img src="https://cloud.githubusercontent.com/assets/2068130/5875615/89cc4922-a30f-11e4-9054-e405f51276c3.PNG" width="150">
It dosen't look bad, but I realized some old bugs (witch we have already using IconBundles and ThemeLib):
- Icons themed with the IconBundles Method are displayed too big and not as sharp, as they should be
- The Clock icon will not be themed anymore in the closed folder preview

Currently, I have not fond a way to move the Calendar icon text - I have not played around with the font settings Anemone offers so far.

These bugs are also present on my iPad 3, using iOS 8.1.2.

There are a some discussions about Anemone in general, for example found [here](http://www.reddit.com/r/jailbreak/comments/2sri4o/anemone_public_nightly_beta_builds/) and it seems that there is some kind of - lets say - "communication problems" between saurik and coolstar. I have absolutley no feelings about his and I will not comment it - and I don't want a discussion about this here. I only want a stable, good, long living and free theming platform for iOS, witch we can use in the future to make Glasklart as good as it was in the old iOS6 times. It just would make me happy, if we could clear out the bugs I mentioned above.
A documentation of using Anemone can be found [here](https://github.com/AnemoneTeam/Anemone/wiki) and if someone wants to try it out, add the repo `anemonetheming.com/nightly/` to Cydia. But be warned, it's **ALPHA**!

So the question is: Should we count on Anemone if it will be released? Any thoughts about that?

**Comment by coolstar** [comment]
There's a small error in this post. Anemone isn't a "Winterboard plugin". It's a separate theme engine that doesn't depend on and actually replaces WinterBoard.

**Comment by dreamnet** [comment]
@coolstar Thank's for the correction! :+1:

**Comment by coolstar** [comment]
Anyways, I've installed Glasklart on my device and I'll take a look at this issue this weekend.

**Comment by dreamnet** [comment]
@coolstar Great too see you are reading this (Twitter is not "my" platform :grin:) - here is a screenshot with some blank "Testicons" and a background with helplines, where you can see, that some icons have the right size (Uhr, Kalender, Zeitungskiosk - Sorry, I forgot to switch to english befor making the screenshot, the apps are Clock, Calendar and Newsstand) and all other icons are too big (they are displayed with 124x124px instead of 120x120px).
<img src="https://cloud.githubusercontent.com/assets/2068130/5882605/4669cbe6-a34b-11e4-802a-825d0e571d83.PNG" width="150">
Uhr, Kalender, Zeitungskiosk are themed with the Bundles-Method (OK), all other icons with the IconBundles-Method (too big).
Maybe this helps you checking what's going wrong. This problem also appears when using ThemeLib.
Thank's a lot!

**Comment by andreolidavide** [comment]
I'm fairly new here but I think that if the stable version of Anemone will offer what Winterboard offers in term of stability and "theming capabilities" you should give it a shot.
Since iOS 7 I got the feeling that Winterboard's development stopped, a part from iOS 8 support nothing has come; I know that iOS 7 is difficult to theme, but I feel like saurik isn't even trying. I maybe wrong, and probably I am, but this is a new project and I think we can expect a lot from it.
By the way I think that Anemone is graphically better than Winterboard; this isn't crucial but it's a thing ;)

**Comment by dreamnet** [comment]
@coolstar Any news on the icons-displayed-too-big with themelib and Anemone issue?

**Comment by coolstar** [comment]
@dreamnet we've decided to rewrite the IconBundles component built into Anemone as IconBundles really wasn't implemented correctly in the first place

**Comment by dreamnet** [comment]
@coolstar OK, thank's for the feedback!

**Comment by ivanov007** [comment]
since nightly 40 my springboard it's being crashing, had to remove anemone @dreamnet are you still using it? I don't know if the issues is that I'm using both anemone and winterboard
I just tried nightly 72 and same thing

**Comment by dreamnet** [comment]
@ivanov007 This als happened to me on my iPad and also had to remove it - it crashes springboard on my iPad everythime I locked it. I think we have to wait until anemone is more stable. :cry:

**Comment by ivanov007** [comment]
yup same behavior happens with me, when it locks it resprings in safe mode :disappointed: and yes I tried to submit my crashlog to the link shared on a tweet but the page doesn't work and I had no response to the tweets I send either...

**Comment by dreamnet** [comment]
Hopefully @coolstar is reading this thread again... :question:

**Comment by dreamnet** [comment]
@ivanov007 Haven't testet much, but anemone seems stable to me since the release of nightly 74...

**Comment by ivanov007** [comment]
:smile: yeeeah I'll give it another try thanks

**Comment by coolstar** [comment]
It's nightly 74 running fine for you guys so far? The issues should be fixed now. Please feel free to let me know if you're having issues with Anemone.

**Comment by ivanov007** [comment]
@coolstar yes it's working very smooth :smile: , no more crashes when my device locks, I just noticed something, when I tap the edit button inside the app my device resprings just like that (no safe mode no crash log), I don't know if this has something to do with the fact that I just have one theme installed

**Comment by coolstar** [comment]
We haven't implemented the functionality of the edit button yet, hence why it does that.

**Comment by dreamnet** [comment]
@coolstar Thank you for your answers! I am using Anemone on my iPad 3 with iOS 8.1.2 (no Winterboard, IconBundles or themelib installed, only Anemone) and it seems to be stable since nightly 74. No crashes so far. :+1: 
Theming the normal app icons with the IconBundles method works fine if I use `bundleID~ipad.png` as icon name.
But now I have a problem theming the Clock and the Newsstand icon, have tryed almost every icon name in `Bundles/com.apple.springboard` I could imagine, for example `ClockIconBackgroundSquare~ipad.png`, `ClockIconBackgroundSquare~iphone.png`, `ClockIconBackgroundSquare@2x~ipad.png` and so on.... ...no chance to get this icons themed.
Theming the clock hands works without a problem.
Here is a screenshot, so you can see what I mean:
https://cloud.githubusercontent.com/assets/2068130/6857707/037d07aa-d409-11e4-9829-b3879ecb94bd.PNG
Any ideas, or is iPad not supported yet:question:

**Comment by coolstar** [comment]
Can you use this cardump tool to list the files in the SpringBoard Assets.car on iPad? https://mega.co.nz/#!WRYFWSQZ!6PvYUjr2nqqhee5OLAL7F9fJPa-br93NqCmpRE21VoI

Usage: "/path/to/cardump --list /System/Library/CoreServices/SpringBoard.app/Assets.car"

**Comment by dreamnet** [comment]
@coolstar Sure, here is the output:

```
Car-Dump Version 1.0 for ThemeLib
© 2014, CoolStar. All Rights Reserved
Listing contents of car file with name: Assets 
Bundle Path: /System/Library/CoreServices/SpringBoard.app

BannerGrabber
BannerVIPAccessory
BulletinListCriticalIcon
BulletinListSystemIcon
BulletinModalAlertVIPAccessory
CarBannerAlertGlyph
CarDisplayCanvasIcon-com.apple.cardisplay.OEM
CarDisplayCanvasIcon-com.apple.cardisplay.nowplaying
CarDisplayChevronBanner
CarDisplayIconBadge
CarDisplayLeftArrow
CarDisplayRightArrow
CarDisplayThermometer
CarPlayRelockUIGlyph
ClockIconBackgroundSquare
ControlCenterGlyphAirPlay
ControlCenterGlyphAirplane
ControlCenterGlyphBluetooth
ControlCenterGlyphCalculator
ControlCenterGlyphCamera
ControlCenterGlyphClock
ControlCenterGlyphFlashlight
ControlCenterGlyphFlashlightOn
ControlCenterGlyphHotspot
ControlCenterGlyphLessBright
ControlCenterGlyphMoon
ControlCenterGlyphMoreBright
ControlCenterGlyphMute
ControlCenterGlyphOrientationLocked
ControlCenterGlyphOrientationUnlocked
ControlCenterGlyphWifi
EmptyNewsstandEnglish
EmptyNewsstandInternational
FolderMask
FolderTitleClearButton
FolderTitleEditBG
IconBadgeAndCloseBox
IconCloseBoxX
IconNewDot
LockScreenChargingBatteryMask
NewsstandIconEnglish
NewsstandIconInternational
NewsstandTopGradient
PowerDownCancel
PowerDownCancel-Small
PowerDownKnob
SBLockScreenTimerDial
SBLockScreenTimerDial-XL
SBNotificationsClearButtonStrokedCircleX
SFT_AppStore
SFT_Maps
SFT_Movies
SFT_Restaurants
SFT_Safari
SFT_iTunes
Search-BingLogo
Search-rating-star
Search-star
Search-unread
Temperature
apple-logo
apple-logo-black
brightness
calculator-lockscreen
camera-lockscreen
clock-lockscreen
locked
mute
people-facetime
people-imessage
people-phone
ringer
ringer-silence
siri-lockscreen
siri-switcher
speaker
unlocked
```

**Comment by coolstar** [comment]
hmm, looks like you have to name your files ClockIconBackgroundSquare, NewsstandIconEnglish, and EmptyNewsstandInternational (you can add the @2x or @3x extensions but not ~iphone or ~ipad). This is due to a limitation of car files. However, you can avoid it by having 2 separate themes listed for iPhone and iPad for just those 2 icons.

**Comment by dreamnet** [comment]
@coolstar We have two sepaerate themes for iPhone and iPad. On iPhone theming the Clock icon background is working with `ClockIconBackgroundSquare@2x~iphone.png`. On iPad the Clock icon background is not themable with Anemone, I tryed every file name I could imagine in `com.apple.springboard`....
```
ClockIconBackgroundSquare.png
ClockIconBackgroundSquare@2x.png
ClockIconBackgroundSquare@2x~ipad.png
ClockIconBackgroundSquare@2x~iphone.png
ClockIconBackgroundSquare@3x.png
ClockIconBackgroundSquare@3x~ipad.png
ClockIconBackgroundSquare@3x~iphone.png
ClockIconBackgroundSquare~ipad.png
ClockIconBackgroundSquare~ipad@2x.png
ClockIconBackgroundSquare~ipad@3x.png
ClockIconBackgroundSquare~iphone.png
ClockIconBackgroundSquare~iphone@2x.png
ClockIconBackgroundSquare~iphone@3x.png
...
```
None of this file names are working for the Clock icon. :cry: 
Same for the Newsstand icon.

**Comment by coolstar** [comment]
Are you sure you cleared the cache by tapping "Apply Changes" inside anemone when updating your theme? SpringBoard caches icons that are themed by the bundles method.

**Comment by dreamnet** [comment]
@coolstar Yes, completly sure. Anyway, found out that the problem was caused by `AppIconMask@2x~ipad.png` in `com.apple.mobileicons.framework`.
This was a completly transparent image, if I change it to opaque black, this is the result:
https://cloud.githubusercontent.com/assets/2068130/6906850/98507508-d731-11e4-8893-6622a524f60f.PNG
The Newsstand icon is now shown correct, but the Clock icon has a black background....
P.S.: There is already a problem with the icon sizes, all icons themed with the IconBundles method are shown 2px too big.

**Comment by Mxthieu** [comment]
Hello !
Can send an example of the file Info.plist for the calendar icon please ?

**Comment by dreamnet** [comment]
@Mxthieu It's aleady [here](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/Info.plist).

**Comment by Mxthieu** [comment]
Oh Thanks :)

**Comment by Mxthieu** [comment]
Hey ! If we use the way like IconBundles, AppMask works or not ?

**Comment by dreamnet** [comment]
I just want to mention, that I cold solve the above problem with the `AppIconMask@2x~ipad.png` by adding a 0-byte text file in `com.apple.mobileicons.framework` and rename it to `AppIconMask@2x~ipad.png`. With this file the Glasklart theme for iPad with retina display on [my website](http://glasklarthd.dreamnet.at/ipad3) is compatibe with the current Alpha version of Anemone **and** it also works fine if you use a combination of Winterboard+IconBundles+themelib.

**Comment by coolstar** [comment]
@dreamnet hi, just wanted to let you know we have changed a lot of the IconBundles support recently (we now recommend ~ipad@2x.png for retina ipad although we still support @2x~ipad.png for backwards compatibility). Please try out the latest nightly and let me know how it works for you.

**Comment by LaCh0uine** [comment]
Hi,
Since the build 243 I don't have folder background with Anemone
https://pbs.twimg.com/media/CLJ3-aBUAAA8_aM.jpg:large

**Comment by dreamnet** [comment]
@LaCh0uine Yes I noticed that - seems the problem with the `AppIconMask` from above is back again. Currently I have no working fix for this - you can delete the `AppIconMask`-Files from `com.apple.mobileicons.framework`, but then the Clock Icon gets a black background. Can't find out why.

@coolstar As I mentioned above, when using Anemone nightly-250 and a 0-byte file for the `AppIconMask`, folder backgrounds will not displayed anymore. When adding a complete black `AppIconMask`-image, the folders will be displayed again, but then the Clock icon gets a black background. Tryed to solve this with the new Folder Icons method, but had no luck.
The problem that all icons themed with the IconBundles-Method are displayed too big already exists.

**Comment by LaCh0uine** [comment]
What is weird.. On preview the background is ok ;)

**Comment by dreamnet** [comment]
@coolstar Tryed out IconBundles names with nightly-252 on retina iPad, as you suggest above:
Using `~ipad.png` - works.
Using `@2x~ipad.png` - works.
Using `~ipad@2x.png` - does **not** work.

**Comment by dreamnet** [comment]
@coolstar Ill try to show you what's going wrong with Anemone in my oppinion (using nightly-252).
Here is a screenshot from my iPad3 on iOS 8.4, using a [very simple Anemone-Test theme](http://glasklarthd.dreamnet.at/download/Anemone_iPad3_Test.zip) and a 75% black test background with white helplines, the parallax function is turned off on the iPad - this test theme does not contain a `Info.plist`, the `AppIconMask@2x~ipad.png` is a complete black, opaque 152x152px png:

---
![](https://cloud.githubusercontent.com/assets/2068130/9070882/4ae251ea-3af2-11e5-8db4-c52a59116c50.png)
From left top to right bottom:
- Closed Folder - OK
- Clock icon, themed with `Bundles/com.apple.springboard/ClockIconBackgroundSquare@2x.png`, icon size OK, but seems to have a black background.
- Calendar icon, themed with `IconBundles/com.apple.mobilecal@2x~ipad.png`, displayed 4px too big, else OK.
- Reminders icon, themed with `IconBundles/com.apple.reminders@2x~ipad.png`, displayed 4px too big, else OK.
- Anemone icon, themed with `Bundles/com.anemonetheming.anemone/icon@2x~ipad.png`, size OK, but seems to have a black background.
- iBooks icon, not themed at all (only here for comparing).

---

If I change the `AppIconMask@2x~ipad.png` from completly opaque black to completly transparent, this is happening:
![](https://cloud.githubusercontent.com/assets/2068130/9071769/7d60e1ae-3af7-11e5-8b42-cf6cdab55a8a.png)
Weird, all icons themed with the Bundles method, the Clock icon and the unthemed iBooks icon are now 100% transparent, only the icons themed with the IconBundles-method are displayed.

---
If I use a "dummy"-`AppIconMask@2x~ipad.png` (0-byte-file), I get this:
![](https://cloud.githubusercontent.com/assets/2068130/9072233/4fa3d4b2-3afa-11e5-861e-821c0964dab4.png)

---
If I completly remove the `AppIconMask@2x~ipad.png` (so that the native one from iOS is used), I get this:
![](https://cloud.githubusercontent.com/assets/2068130/9072322/c72d28b2-3afa-11e5-8a50-432bda5012ff.png)

---
I used the same, 50% transparent, 152x152px (ugly :laughing:) magenta image for all icons: 
![](https://cloud.githubusercontent.com/assets/2068130/9070931/97525458-3af2-11e5-8083-f17487a02340.png)

---
No Winterboard, IconBundles, themelib or something else is installed, pure Anemone. Chaches are always cleared between the screenshots btw. using the Apply-Button in Anemone.
I hope, this helps solving some problems!

**Comment by coolstar** [comment]
The IconBundles issue has been fixed in Anemone nightly 268.

**Comment by LaCh0uine** [comment]
Are you sure ?? For me it's bad no folder and no background of the clock too .. But my anemone crash when I open :( 
I hope the problem fix soon

**Comment by coolstar** [comment]
@LaCh0uine delete the icon masks from the glasklart theme and the background issue will be gone

**Comment by coolstar** [comment]
@LaCh0uine please update to the latest version of Anemone and send a syslog from the crash to coolstarorganization@gmail.com

**Comment by LaCh0uine** [comment]
The build 271 fix the crash .. I try later for the icon masks

**Comment by dreamnet** [comment]
@LaCh0uine Glasklart dosen't officially support Anemone at this time. I am currently checking how I can make Glasklart compatible with the currently used combination of WinterBoard/IconBundles/ThemeLib and Anemone. I hope I can fix the current issues with (missing folder background, clock icon) in the next release. In the meanwhile you can fix this by deleting all files in `Library/Themes/Glasklart Icons.theme/Bundles/com.apple.mobileicons.framework/`.
I am pretty sure we will switch over to Anemone when it's stable and released, but I have to discuss this first with the other @glasklart/maintainers.

**Comment by LaCh0uine** [comment]
@coolstar I remove AppIconMask.. folder and clock work now thank you

@dreamnet yeah i know i need to install winterboard anyway because the package have a dependence ;)

**Comment by dreamnet** [comment]
@LaCh0uine I think I made all changes I can do so far to the master - so that Glasklart looks good with Winterboard/IconBundles/Themlib and Anemone. P.S.: If you have Anemone installed, please remove themelib. Also fixed the problem when the Clock icon is moved to a closed folder.

**Comment by LaCh0uine** [comment]
I never installed themelib;)

**Comment by dreamnet** [comment]
@glasklart/maintainers After trying every combination of .png's I know and a thousands of resprings, I really think Glasklart is on a point now where it will be necessary to decide if we stay on the current configuration of `Winterboard, IconBundles and ThemeLib` or if we should switch over to [`Anemone`](https://twitter.com/anemone_ios). I can't find a way to make Glasklart good looking on both "Theming-Platforms" anymore.
The point for Anemone is that we can theme a lot more things with it than with the current combination and the developers are already adding more features - but that's also the bad point, Anemone is in "Alpha" state since months and it is currently not on available from a default Cydia repo. 
I am also thinking of all the Winterboard users out there we maybe lose when we switch to Anemone, but personally I think there will be no way around Anemone, since Winterboard hasent changed for months :cry:, IconBundles is no longer maintained :sob:, and ThemeLib  is no longer supported :disappointed:. iOS9 is also on it's way.
So, @glasklart/maintainers what's your thoughts?

@coolstar I know I should not ask this, but **is there any timeline for the release of Anemone?**

**Comment by coolstar** [comment]
@dreamnet we are ramping up for release currently and hope to release Anemone within 1-2 weeks.

**Comment by MagnaMike** [comment]
@dreamnet I haven't really been following the technical state of theming on iOS as you probably know, but it sounds to me from what you have said is that Anenome is the way to go. Would this trigger a new release of the theme (a new download) or would the current theme just be updated?

**Comment by dreamnet** [comment]
@MagnaMike The current theme will be updatet and I remove all dependencys (currently Winterboard and IconBundles) and - maybe if this is possible - add a new dependency to Anemone if it is released.

**Comment by MagnaMike** [comment]
@dreamnet :+1:

**Comment by dreamnet** [comment]
Actual look with Anemone (0.1~nightly-285):
![img_0016](https://cloud.githubusercontent.com/assets/2068130/9452621/92cde690-4ab5-11e5-972c-1742fce43f7c.PNG)

**Comment by LaCh0uine** [comment]
Nice everything work for you I wait the next version ;)

**Comment by dreamnet** [comment]
@LaCh0uine I am currently not sure if I should push out a new release until Anemone is ready... :confused:

**Comment by LaCh0uine** [comment]
Ok ok 
What your solution for the clock work ?

**Comment by dreamnet** [comment]
@LaCh0uine Well, to get the above you can uninstall Glasklart from your device, [download the actual master](https://github.com/glasklart/hd/archive/master.zip) and copy all `Glasklart...` folders in it to `Library/Themes/` on your device.

**Comment by LaCh0uine** [comment]
I finally find the missing file ;)
ClockIconBackgroundSquare@2x.png

**Comment by dreamnet** [comment]
@LaCh0uine Yes, but you also have to put [`com.apple.mobiletimer@2x.png`](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.mobiletimer%402x.png) and [`com.apple.mobiletimer@3x.png`](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.mobiletimer%403x.png) to IconBundles (for the non-live-view of the clock).

**Comment by LaCh0uine** [comment]
When need non-live-view ??

**Comment by dreamnet** [comment]
@LaCh0uine When you move the clock icon to a closed folder, for spotlight, ... [Click](https://github.com/AnemoneTeam/Anemone/issues/5)

**Comment by coolstar** [comment]
Anemone and Glasklart HD both work on iOS 9 ;)

https://www.youtube.com/watch?v=BtBqkj7RsFo

**Comment by Trubbel** [comment]
Most impressive. However the un-themed News application bothers me haha. :smile:

**Comment by dreamnet** [comment]
@coolstar Nice! :grin:

**Comment by dreamnet** [comment]
@coolstar Release 4.24.0 of Glasklart is using Anemone. Available on Cydia in two or three days.

**Comment by coolstar** [comment]
@dreamnet alright cool. Anemone seems to be pretty stable now so we'll push out the release candidate in a few.

**Comment by Trubbel** [comment]
@dreamnet :+1:

**Comment by dreamnet** [comment]
@coolstar OK, thanks! Can't wait for Anemone to be released! :heart_eyes:

**Comment by nekholm** [comment]
Does Anemone work in the same way as WinterBoard, as in are themes still stored in /Library/Themes, and are they applied in a similar way to WB?

**Comment by dreamnet** [comment]
@nekholm Anemone mostly works in the same way as Winterboard and also uses Library/Themes/. Documentation is [here](https://github.com/AnemoneTeam/Anemone/wiki).

**Comment by dreamnet** [comment]
[Good news.](https://twitter.com/Anemone_iOS/status/648011229101879300)

**Comment by dreamnet** [comment]
OK, it's done - we are using Anemone. Closing.
