### ISSUE TITLE
OnSwitch for Philips Hue / LIFX: Lights & Effects

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#5092]
**App Name:** OnSwitch for Philips Hue / LIFX: Lights & Effects
**Bundle ID:** com.getonswitch.OnSwitch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=853520339">853520339</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/onswitch-for-philips-hue-lifx/id853520339?mt=8&uo=4">https://itunes.apple.com/us/app/onswitch-for-philips-hue-lifx/id853520339?mt=8&uo=4</a>
**App Version:** 1.1.11
**Seller:** David Pewzner
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/david-pewzner/id853520342?uo=4>© David Pewzner</a>
**Supported Devices:** iPhone6, iPhone5c, iPadThirdGen4G, iPodTouchFifthGen, iPadFourthGen, iPhone5, iPadMini, iPad23G, iPadMini4G, iPhone4S, iPadThirdGen, iPadFourthGen4G, iPhone4, iPhone5s, iPhone6Plus, iPad2Wifi
**Original Artwork:**
<img src="http://a557.phobos.apple.com/us/r30/Purple3/v4/28/9d/6c/289d6c2a-0885-2f0d-78a7-0295369dbef7/pr_source.png?downloadKey=1422153463_8476919c5d815c27fd265fc39a0149a6" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5892228/99194a66-a4b7-11e4-92f9-4980307d25ce.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5892228/99194a66-a4b7-11e4-92f9-4980307d25ce.png)
https://cloud.githubusercontent.com/assets/2068130/5892228/99194a66-a4b7-11e4-92f9-4980307d25ce.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5892232/a8d4a4dc-a4b7-11e4-9472-f41ef5c57b68.png
