### ISSUE TITLE
Hero Emblems

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5093]
**App Name:** Hero Emblems
**Bundle ID:** com.amazinpot.projectzero
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=645797558">645797558</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hero-emblems/id645797558?mt=8&uo=4">https://itunes.apple.com/us/app/hero-emblems/id645797558?mt=8&uo=4</a>
**App Version:** 1.01
**Seller:** CHUN LUNG KUO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/chun-lung-kuo/id645797561?uo=4>© CHUN LUNG KUO</a>
**Supported Devices:** iPhone5s, iPhone6Plus, iPadThirdGen, iPadFourthGen, iPad23G, iPadFourthGen4G, iPadMini4G, iPadMini, iPhone4, iPhone-3GS, iPhone5c, iPhone4S, iPhone6, iPodTouchFifthGen, iPhone5, iPad2Wifi, iPadThirdGen4G, iPodTouchFourthGen
**Original Artwork:**
<img src="http://a647.phobos.apple.com/us/r30/Purple1/v4/c3/3b/64/c33b64e1-810f-e78f-a13c-0fea93bb1933/mzl.xoejkqfy.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5891499/4bbe36dc-a499-11e4-9d98-3b4a3b34210d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5891499/4bbe36dc-a499-11e4-9d98-3b4a3b34210d.png)
https://cloud.githubusercontent.com/assets/2068130/5891499/4bbe36dc-a499-11e4-9d98-3b4a3b34210d.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5891501/5b1d18a0-a499-11e4-9401-afadbd8fbc53.png
