### ISSUE TITLE
Goblin Sword

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5094]
**App Name:** Goblin Sword
**Bundle ID:** com.gelatogames.goblinsword
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905488045">905488045</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/goblin-sword/id905488045?mt=8&uo=4">https://itunes.apple.com/us/app/goblin-sword/id905488045?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Eleftherios Christodoulatos
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/eleftherios-christodoulatos/id434837970?uo=4>© Eleftherios Christodoulatos</a>
**Supported Devices:** iPad3G, iPadFourthGen4G, iPhone6, iPhone6Plus, iPadMini, iPodTouchThirdGen, iPhone5, iPhone5c, iPad23G, iPadWifi, iPhone5s, iPad2Wifi, iPodTouchFifthGen, iPadThirdGen, iPadThirdGen4G, iPhone4, iPodTouchFourthGen, iPadFourthGen, iPhone-3GS, iPadMini4G, iPhone4S
**Original Artwork:**
<img src="http://a1137.phobos.apple.com/us/r30/Purple4/v4/44/6d/86/446d8626-8fdc-48fd-6c06-490b1185ecd4/mzl.qzvekmzq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5892426/c675060c-a4bd-11e4-9fdd-496230e1cdb3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5892426/c675060c-a4bd-11e4-9fdd-496230e1cdb3.png)
https://cloud.githubusercontent.com/assets/2068130/5892426/c675060c-a4bd-11e4-9fdd-496230e1cdb3.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5892427/d20d68ce-a4bd-11e4-810e-e34730db660c.png

**Comment by MagnaMike** [comment]
@dreamnet I like the style you did this icon with, I usually found pixel icons difficult to do. This way is a good idea. :+1:
