### ISSUE TITLE
Themes, including Glasklart, don't affect Clock icon (iPhone 6+; iOS 8.1.2; TaiG)

### ISSUE THREAD

**Issue by Pokeclipse** [glasklart/hd#5096]
Ok, so I'm trying to apply the Glasklart theme to my iPhone 6+ running iOS 8.1.2. It worked for every one of my apps (including Newsstand) except for the stock Clock app. I installed Themelib like the instructions said, and have tried other themes, but to no avail. The Clock icon - and only the Clock icon - never gets changed no matter which theme I use. I've been pulling my hair out over this for the past day and would really appreciate some assistance. I've read through the "iOS 8.x compatibility" and "iPhone 6+" issues here but nothing in them helped. Here's a list of the tweaks I have installed; let me know if you need any further information:

Adblocker 2
Alkaline
Android KitKat Status Bar
AppsList
BattSaver
BigBoss Icon Set
Browser Changer
Custom Clock Icon
CustomClock Example
Cydia Installer
Cydia Substrate
Cydia Translations
flux
Glasklart
HomescreenDesigner
IconBundles
iWidgets
MapsOpener
mikoto
Nitrous
Notate
Opener
Protean
SBHTML
Search Widget
Springtomize 3
Substrate Safe Mode
SwipeSelection Pro
ThemeLib
WinterBoard

**Comment by dreamnet** [comment]
@Pokeclipse Hm... Remove Custom Clock Icon, it's not needed for Glasklart. Maybe this helps.

**Comment by Pokeclipse** [comment]
@dreamnet Alright, I uninstalled Custom Clock Icon. Unfortunately that didn't seem to fix the problem (I reinstalled Glasklart and ThemeLib just to be sure).

Interestingly, a recently-released clock theming tweak called Circulate seems to work just fine for me. I'm leaving it disabled for now in hopes that I can get the Glasklart clock icon to show up (and also because I don't really like the limited customizations that Circulate offers).

**Comment by dreamnet** [comment]
@Pokeclipse I't s hard to say what causes the problem, you have a lot ot tweaks installed... Have you tried to unselect everyting in Winterboard except the Glasklart Icons theme?
You can also try to install iCleaner from Cydia and run it once.

**Comment by dreamnet** [comment]
@Pokeclipse Could you solve the problem?

**Comment by Pokeclipse** [comment]
Unfortunately I wasn't able to solve the problem. I ended up just using the Circulate tweak. Thanks for your help though.
