### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5097]
**App Name:** Google Slides
**Bundle ID:** com.google.Slides
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=879478102">879478102</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-slides/id879478102?mt=8&uo=4">https://itunes.apple.com/us/app/google-slides/id879478102?mt=8&uo=4</a>
**App Version:** 1.0.5754
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPadThirdGen4G, iPhone6Plus, iPhone5s, iPadFourthGen4G, iPadMini, iPad23G, iPodTouchFifthGen, iPad2Wifi, iPhone4, iPadThirdGen, iPhone5c, iPhone5, iPadFourthGen, iPadMini4G, iPhone4S, iPhone6
**Original Artwork:**
<img src="http://a472.phobos.apple.com/us/r30/Purple1/v4/f5/7d/55/f57d5504-5a0d-dca7-2eb7-6b7598512271/pr_source.png?downloadKey=1422313740_cc98678da9a91b09d633fb899c74dbda" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5907951/908f56f0-a5a3-11e4-8aee-df8b565cbe32.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5907951/908f56f0-a5a3-11e4-8aee-df8b565cbe32.png)
https://cloud.githubusercontent.com/assets/2068130/5907951/908f56f0-a5a3-11e4-8aee-df8b565cbe32.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5907961/a1a56632-a5a3-11e4-8cb9-b7a7fceba97a.png
