### ISSUE TITLE
GSN Casino - Slots, Bingo, Video Poker and more!

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5098]
**App Name:** GSN Casino - Slots, Bingo, Video Poker and more!
**Bundle ID:** com.gsn.gsncasino
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469231420">469231420</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gsn-casino-slots-bingo-video/id469231420?mt=8&uo=4">https://itunes.apple.com/us/app/gsn-casino-slots-bingo-video/id469231420?mt=8&uo=4</a>
**App Version:** 3.10.0
**Seller:** Game Show Network
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/game-show-network/id342254535?uo=4>© Game Show Network</a>
**Supported Devices:** iPhone6, iPad23G, iPhone5s, iPadThirdGen4G, iPadMini, iPad3G, iPhone5, iPodTouchFourthGen, iPhone5c, iPadFourthGen, iPad2Wifi, iPadThirdGen, iPodTouchThirdGen, iPadMini4G, iPhone-3GS, iPhone4, iPodTouchFifthGen, iPhone6Plus, iPadFourthGen4G, iPadWifi, iPhone4S
**Original Artwork:**
<img src="http://a245.phobos.apple.com/us/r30/Purple5/v4/57/53/fe/5753fe16-3e27-731b-5f1d-2631aa817642/pr_source.png?downloadKey=1422319721_42f4459c4a5ba13970587598fc01a869" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5951867/263a6562-a73b-11e4-8a96-5204eb9a4b52.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5935269/3f8847e4-a6d9-11e4-82d5-24c46d6df214.png)
https://cloud.githubusercontent.com/assets/10515074/5935269/3f8847e4-a6d9-11e4-82d5-24c46d6df214.png

Source
https://cloud.githubusercontent.com/assets/10515074/5935291/84de95aa-a6d9-11e4-976e-93237af2d95e.png

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5951587/67528524-a737-11e4-8c91-6a5105b92f3a.png)
https://cloud.githubusercontent.com/assets/2236254/5951587/67528524-a737-11e4-8c91-6a5105b92f3a.png
Source:
https://cloud.githubusercontent.com/assets/2236254/5951584/623d3b9c-a737-11e4-9ab3-d4993ce78fee.png

**Comment by dreamnet** [comment]
@MagnaMike :+1:
