### ISSUE TITLE
Hit it Rich! Free Casino Slots

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5099]
**App Name:** Hit it Rich! Free Casino Slots
**Bundle ID:** com.zynga.hititrich
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=694876905">694876905</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hit-it-rich!-free-casino-slots/id694876905?mt=8&uo=4">https://itunes.apple.com/us/app/hit-it-rich!-free-casino-slots/id694876905?mt=8&uo=4</a>
**App Version:** 1.4.5297
**Seller:** Zynga Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/zynga-inc./id295913422?mt=8&uo=4>© Zynga Inc.</a>
**Supported Devices:** iPad2Wifi, iPhone6, iPhone6Plus, iPadThirdGen, iPhone4, iPhone4S, iPadMini, iPadThirdGen4G, iPhone5c, iPadFourthGen4G, iPhone5, iPadMini4G, iPadFourthGen, iPad23G, iPodTouchFourthGen, iPodTouchFifthGen, iPhone5s
**Original Artwork:**
<img src="http://a388.phobos.apple.com/us/r30/Purple1/v4/38/13/5a/38135a21-2ae9-e75d-fed6-a476a9f0c040/mzl.hgtrgggr.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6086699/32af9e2e-ae44-11e4-91d9-a104ef39b823.png)

**Comment by MagnaMike** [comment]
Well, I tired.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6070934/dd6d34e8-ad5e-11e4-9599-e1794b55e964.png)
https://cloud.githubusercontent.com/assets/2236254/6070934/dd6d34e8-ad5e-11e4-9599-e1794b55e964.png
---
Source: (Cover your eyes, it looks so ugly :scream:) 
https://cloud.githubusercontent.com/assets/2236254/6070933/daaa45b6-ad5e-11e4-93f6-07e9da57d7b8.png
![com zynga hititrich](https://cloud.githubusercontent.com/assets/2236254/6070934/dd6d34e8-ad5e-11e4-9599-e1794b55e964.png)

**Comment by MagnaMike** [comment]
**Alternate**

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6071162/e27edffc-ad60-11e4-87e1-810166f07498.png)
https://cloud.githubusercontent.com/assets/2236254/6071162/e27edffc-ad60-11e4-87e1-810166f07498.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6071158/dd35321c-ad60-11e4-85f0-75405dd4a10d.png

**Comment by ivanov007** [comment]
@MagnaMike the second one looks good maybe de zynga dog can be removed?

**Comment by MagnaMike** [comment]
@ivanov007 Yeah, I'll have a go at that later. :+1:

**Comment by dreamnet** [comment]
Just edited the source from @MagnaMike a bit:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6086699/32af9e2e-ae44-11e4-91d9-a104ef39b823.png)
https://cloud.githubusercontent.com/assets/2068130/6086699/32af9e2e-ae44-11e4-91d9-a104ef39b823.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6086734/402a5c9c-ae44-11e4-9677-e85aab2eb840.png

**Comment by MagnaMike** [comment]
@dreamnet Looks good!
