### ISSUE TITLE
Week Calendar

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#510]
**App Name:** Week Calendar
**Bundle ID:** com.wasabi-apps.WeekCal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=381059732">381059732</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/week-calendar/id381059732?mt=8&uo=4">https://itunes.apple.com/us/app/week-calendar/id381059732?mt=8&uo=4</a>
**App Version:** 9.6
**Seller:** WeekCal B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/weekcal-b.v./id318729104?uo=4>© WeekCal B.V.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/b8/0b/76/b80b76cb-5744-86c7-85f8-af506ae7200a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18256486/518a4856-73b6-11e6-866c-feeacdd642e8.png)

**Comment by l8er4now** [comment]
Needs an update and resizing.

**App Name:** Week Calendar
**Bundle ID:** com.wasabi-apps.WeekCal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=381059732">381059732</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/week-calendar/id381059732?mt=8&uo=4">https://itunes.apple.com/us/app/week-calendar/id381059732?mt=8&uo=4</a>
**App Version:** 9.6
**Seller:** WeekCal B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/weekcal-b.v./id318729104?uo=4>© WeekCal B.V.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/b8/0b/76/b80b76cb-5744-86c7-85f8-af506ae7200a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18239666/135261c8-7347-11e6-9804-0779d46a79f6.png)
https://cloud.githubusercontent.com/assets/20930745/18239666/135261c8-7347-11e6-9804-0779d46a79f6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18239685/2f4fb934-7347-11e6-99f2-eb23fdf89511.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18256486/518a4856-73b6-11e6-866c-feeacdd642e8.png)
https://cloud.githubusercontent.com/assets/2068130/18256486/518a4856-73b6-11e6-866c-feeacdd642e8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18256491/60cc28c0-73b6-11e6-8065-524ffe196a0e.png
