### ISSUE TITLE
Alfred Remote

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#5101]
**App Name:** Alfred Remote
**Bundle ID:** com.runningwithcrayons.AlfredRemote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=927944141">927944141</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alfred-remote/id927944141?mt=8&uo=4">https://itunes.apple.com/us/app/alfred-remote/id927944141?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Running with Crayons Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/running-with-crayons-ltd/id405843585?uo=4>© Running with Crayons Ltd</a>
**Supported Devices:** iPhone5s, iPhone5, iPadThirdGen4G, iPhone4S, iPhone6Plus, iPadFourthGen4G, iPad2Wifi, iPodTouchFifthGen, iPadFourthGen, iPhone5c, iPadMini4G, iPadThirdGen, iPad23G, iPhone6, iPhone4, iPadMini
**Original Artwork:**
<img src="http://a1670.phobos.apple.com/us/r30/Purple5/v4/a1/f6/bb/a1f6bb5b-e154-1549-6ff5-7ed7e30006e8/pr_source.jpg?downloadKey=1422383616_22d84d7d6d3d91f52beede3db4dbbeb4" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/5922684/a6583790-a61b-11e4-8536-23e89ef513e4.png)

**Comment by MagnaMike** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/5922684/a6583790-a61b-11e4-8536-23e89ef513e4.png)
https://cloud.githubusercontent.com/assets/2236254/5922684/a6583790-a61b-11e4-8536-23e89ef513e4.png

Source:
https://cloud.githubusercontent.com/assets/2236254/5922699/b6ebaa10-a61b-11e4-98b6-b9707ca3a645.png)

**Comment by dreamnet** [comment]
@MagnaMike :+1:

**Comment by dreamnet** [comment]
@MagnaMike I need a public mailadress added to your Github account to make commits in your name. Seems you removed your mailadress, please add it back. THX!

**Comment by MagnaMike** [comment]
@dreamnet Ah, that's why I had my email address attached. Fixed!

**Comment by dreamnet** [comment]
@MagnaMike :laughing:
