### ISSUE TITLE
OnlinePizza - Beställ mat enkelt, snabbt & bekvämt online

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5102]
**App Name:** OnlinePizza - Beställ mat enkelt, snabbt & bekvämt online
**Bundle ID:** se.onlinepizza.iPhone.OnlinePizza
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=421369701">421369701</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/onlinepizza-bestall-mat-enkelt/id421369701?mt=8&uo=4">https://itunes.apple.com/us/app/onlinepizza-bestall-mat-enkelt/id421369701?mt=8&uo=4</a>
**App Version:** 2.6.1
**Seller:** OnlinePizza Norden AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/onlinepizza-norden-ab/id421369704?uo=4>© OnlinePizza Norden AB</a>
**Supported Devices:** iPadFourthGen4G, iPadWifi, iPodTouchFifthGen, iPadFourthGen, iPad2Wifi, iPad3G, iPhone6, iPodTouchThirdGen, iPhone5s, iPad23G, iPhone5c, iPhone4, iPhone-3GS, iPodTouchFourthGen, iPhone4S, iPadMini, iPhone5, iPhone6Plus, iPadThirdGen4G, iPadMini4G, iPadThirdGen
**Original Artwork:**
<img src="http://a242.phobos.apple.com/us/r30/Purple1/v4/45/c4/ed/45c4ed89-d22d-ceb6-af14-2d9787d8256c/pr_source.png?downloadKey=1422399369_6e601acccc3f26569efb2885c3d1521e" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5927049/40fae87a-a670-11e4-9e6f-e66800d47ea7.png)

**Comment by Trubbel** [comment]
I wasn't entirely sure if I should have made my issue and contribution in the same post or in a new one.. (Either way, please let me know)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5926311/739f4768-a66a-11e4-83dd-3e660c606d07.png)
https://cloud.githubusercontent.com/assets/10730122/5926311/739f4768-a66a-11e4-83dd-3e660c606d07.png

**Comment by dreamnet** [comment]
@Trubbel Contributions must always be done in a new comment, so you are done this right.
Your Icon also looks good and I will give you credits for this, but we also need the 1024x1024px icon source, so a correct contribution would look like this:

---
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5927049/40fae87a-a670-11e4-9e6f-e66800d47ea7.png)
https://cloud.githubusercontent.com/assets/2068130/5927049/40fae87a-a670-11e4-9e6f-e66800d47ea7.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5927056/53f5271a-a670-11e4-85cd-01eb448d5f6d.png

---
We have also a [WIKI](https://github.com/glasklart/hd/wiki) that should you give any information you need. If not, feel free to ask. Good work, keep on! :+1:

**Comment by Trubbel** [comment]
@dreamnet Thank you, I wasn't sure about the source either. One question though, when I use the Quick Selection Tool to make a source image, it always ends up with blurry edges and not as sharp as your source above. I'm sure it really simple and all yet I can't figure it out...

**Here's an example how it looks like for me:**
https://cloud.githubusercontent.com/assets/10730122/5927686/a4d8b5ee-a674-11e4-8417-9e274dd4447b.png

**Comment by dreamnet** [comment]
@Trubbel No problem. About the blurry edges: I don't use Photoshop for the sources, I use Illustrator so I don't have this problem. As I know, @ivanov007 uses Photoshop for the sources, maybe he can help you with this.

**Comment by Trubbel** [comment]
Okay, that would be really helpful - I'll wait and see if he replies. Thanks.

**Comment by MagnaMike** [comment]
@Trubbel I would suggest using the magic wand tool instead of the quick selection tool if you are going to use Photoshop. This is what I got using the magic wand tool:
![1](https://cloud.githubusercontent.com/assets/2236254/5930863/894a3f66-a663-11e4-95fe-efe273258744.png)

This turned out worse then your icon but this is me using the quick selection tool:
![2](https://cloud.githubusercontent.com/assets/2236254/5930861/8528a6c0-a663-11e4-97ed-3b0ef8f0a800.png)

**Comment by Trubbel** [comment]
Never thought about using the Magic Want Tool, it's actually really convenient. Thank you very much for the suggestion!

I guess I can close this then, got everything answered and the icon is done.

**Comment by MagnaMike** [comment]
No problem at all, glad to help! :smile: 

I'm going to re-open the issue, we like to keep them open until the icons have been actually added to the theme so they don't get forgotten about.

**Comment by ivanov007** [comment]
@Trubbel just one more tip you can also convert the image to shape (you can find it as vectorize on youtube) this will make the image even sharper and also easier to scale, what I do after having the b/w image is select all (Ctrl+A) select move tool (V), with the direction keys move one side and move it back, this will make the selection fit on the image you completed, then pick any marquee tool (M) right click -> Make Work Path... -> Tolerance = 2.0 (this is the default setting and works for most cases)and there you have the path for the shapes, just check everything is in it's place (usually the circles needs to be corrected a little), finally pick Pen Tool and click on the toolbar button "Shape" and there you are :smile:
