### ISSUE TITLE
Nordea Mobile Bank – Sweden

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5103]
**App Name:** Nordea Mobile Bank – Sweden
**Bundle ID:** com.nordea.mobilebank.se
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571239441">571239441</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nordea-mobile-bank-sweden/id571239441?mt=8&uo=4">https://itunes.apple.com/us/app/nordea-mobile-bank-sweden/id571239441?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Nordea Bank AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nordea-bank/id570926673?uo=4>© Nordea Bank</a>
**Supported Devices:** iPadThirdGen4G, iPadMini, iPhone6, iPhone6Plus, iPadFourthGen4G, iPhone-3GS, iPhone5c, iPhone5, iPhone4S, iPad2Wifi, iPadFourthGen, iPadMini4G, iPodTouchFifthGen, iPhone5s, iPhone4, iPodTouchFourthGen, iPadThirdGen, iPad23G
**Original Artwork:**
<img src="http://a949.phobos.apple.com/us/r30/Purple1/v4/af/e0/80/afe08000-bedb-9b1a-9546-c671daa4b5a0/pr_source.jpg?downloadKey=1422421897_4a73eb73ac9d37dfb9e3b5a6eb70eee1" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5931274/a1c2fc4e-a69b-11e4-9584-25132026ebfa.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5931274/a1c2fc4e-a69b-11e4-9584-25132026ebfa.png)
https://cloud.githubusercontent.com/assets/10730122/5931274/a1c2fc4e-a69b-11e4-9584-25132026ebfa.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5931281/b639e0ac-a69b-11e4-85d7-15875866dc63.png

**Comment by MagnaMike** [comment]
Icon looks good. :+1: 

For the source, just one thing, after you are done making the icon, scale the icon up so it fills the canvas (so either the width, the height, or both dimensions are 1024 px). Like this:
https://cloud.githubusercontent.com/assets/2236254/5931368/073d6d42-a66b-11e4-9ebb-74ea8825aff0.png

**Comment by Trubbel** [comment]
Ah, fair enough. So you want me to use Ctrl + T and upscale it?

**Comment by MagnaMike** [comment]
Yep, that's what I did.

**Comment by Trubbel** [comment]
I'll keep that in mind, thanks yet again.
