### ISSUE TITLE
Telenor

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5104]
**App Name:** Telenor
**Bundle ID:** com.telenor.sweden.minasidor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446928298">446928298</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/telenor/id446928298?mt=8&uo=4">https://itunes.apple.com/se/app/telenor/id446928298?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Telenor Sverige AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/artist/telenor-sverige-ab/id446928301?uo=4>© Telenor Sverige AB</a>
**Supported Devices:** iPhone5s, iPodTouchFifthGen, iPhone6Plus, iPadMini, iPhone4S, iPadThirdGen4G, iPodTouchFourthGen, iPhone5, iPadMini4G, iPad2Wifi, iPhone-3GS, iPhone5c, iPhone4, iPadFourthGen, iPhone6, iPadFourthGen4G, iPadThirdGen, iPad23G
**Original Artwork:**
<img src="http://a315.phobos.apple.com/us/r30/Purple3/v4/b6/47/50/b6475050-4f02-3540-52c8-3049c4529165/mzl.adhkxush.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5931534/45c6eafa-a69f-11e4-834a-981121526b38.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5931534/45c6eafa-a69f-11e4-834a-981121526b38.png)
https://cloud.githubusercontent.com/assets/10730122/5931534/45c6eafa-a69f-11e4-834a-981121526b38.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5931537/581a4d6e-a69f-11e4-8256-01bc461ea412.png

**Comment by MagnaMike** [comment]
Can you add the details that are on your icon to the source icon?

@dreamnet How are we feeling about the centering icons lately?

**Comment by Trubbel** [comment]
@MagnaMike I basically just used the Polygonal Lasso Tool to cut the image to get some "shadows" when re-sizing the icon and then added the style. I'm not sure it would look so good on the source icon though.

**Comment by MagnaMike** [comment]
@Trubbel That should do just fine. :+1:

**Comment by dreamnet** [comment]
@MagnaMike About centering: We try to get as close as possible to the original. But if it looks better completly centered, it's also no problem.
