### ISSUE TITLE
Tink

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5105]
**App Name:** Tink
**Bundle ID:** se.tink.frontend.mobile.apple
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=649395387">649395387</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/tink/id649395387?mt=8&uo=4">https://itunes.apple.com/se/app/tink/id649395387?mt=8&uo=4</a>
**App Version:** 1.7.0
**Seller:** Tink AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/artist/tink/id649397070?uo=4>© Tink</a>
**Supported Devices:** iPadMini, iPadThirdGen4G, iPadMini4G, iPhone4, iPodTouchFifthGen, iPadFourthGen4G, iPhone4S, iPhone6Plus, iPhone6, iPadFourthGen, iPhone5, iPadThirdGen, iPhone5c, iPad2Wifi, iPad23G, iPhone5s
**Original Artwork:**
<img src="http://a1791.phobos.apple.com/us/r30/Purple1/v4/81/f1/12/81f11204-42b3-8a2a-c928-3f4421061748/mzl.lektcngq.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5932653/2b25c564-a680-11e4-855f-e727127401d9.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5931620/4e83ae20-a6a0-11e4-8cae-1c8b1a3e5e0e.png)
https://cloud.githubusercontent.com/assets/10730122/5931620/4e83ae20-a6a0-11e4-8cae-1c8b1a3e5e0e.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5931628/5c3c3c58-a6a0-11e4-81c4-17ad2f984f9f.png

**Comment by MagnaMike** [comment]
Sorry to be a pain, but make sure your source files fully utilize the 1024x1024 canvas. I took your source file and turned it into the red outline so you can see the difference between it and the proper sized source (the black icon).
![untitled-1](https://cloud.githubusercontent.com/assets/2236254/5932610/3807fe2e-a67f-11e4-97cc-2411666c6c6f.png)

**Comment by MagnaMike** [comment]
Here is a correct source file:
https://cloud.githubusercontent.com/assets/2236254/5932625/b1293a70-a67f-11e4-922e-2e75afd8b295.png

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5932653/2b25c564-a680-11e4-855f-e727127401d9.png)
https://cloud.githubusercontent.com/assets/2236254/5932653/2b25c564-a680-11e4-855f-e727127401d9.png

**Comment by Trubbel** [comment]
You're not being a pain, I messed up and you corrected me. Sorry and thanks!
