### ISSUE TITLE
Handle: To-Dos + Email + Calendar

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5106]
t**App Name:** Handle: To-Dos + Email + Calendar
**Bundle ID:** com.handle.app.mail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=766063605">766063605</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/handle-to-dos-+-email-+-calendar/id766063605?mt=8&uo=4">https://itunes.apple.com/us/app/handle-to-dos-+-email-+-calendar/id766063605?mt=8&uo=4</a>
**App Version:** 1.2.11
**Seller:** handl, inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/handle-inc./id577584263?uo=4>© Handle, Inc.</a>
**Supported Devices:** iPadFourthGen, iPadThirdGen4G, iPadFourthGen4G, iPhone6Plus, iPad2Wifi, iPhone4, iPhone4S, iPhone5, iPhone6, iPad23G, iPadMini4G, iPhone5c, iPodTouchFifthGen, iPadMini, iPadThirdGen, iPhone5s
**Original Artwork:**
<img src="http://a238.phobos.apple.com/us/r30/Purple1/v4/4d/58/e5/4d58e567-78c4-3415-c6fe-9702e9ba2207/mzl.aazpzabd.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5931761/44e6e70e-a6a2-11e4-81d9-9a52f2586ebb.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5931761/44e6e70e-a6a2-11e4-81d9-9a52f2586ebb.png)
https://cloud.githubusercontent.com/assets/10730122/5931761/44e6e70e-a6a2-11e4-81d9-9a52f2586ebb.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5931748/13e9d62a-a6a2-11e4-8757-66f91d0a3832.png

**Comment by MagnaMike** [comment]
@Trubbel See #5105

**Comment by Trubbel** [comment]
Yeah I tried to upscale it as much as I could, however it looked too blurry, that's why I left out some spaces.
Even though I used the Magic Wand Tool to cut it out and then upscaled it.

**Comment by MagnaMike** [comment]
You don't have to, but you may want to consider learning Illustrator if you can. That way you get to work with [vector graphics](http://en.wikipedia.org/wiki/Vector_graphics). Instead of pictures being based on pixels, vector graphics are based on math expressions/equations so you can scale them up and down without losing quality. That's how I did the new source file. I just recently started using Illustrator myself, and it's more complicated then just using Photoshop but you can get better results.

**Comment by Trubbel** [comment]
I would love to start learning myself, however I'm one of those people who learn by watching other people work or by looking at YouTube vidoes, however, I have no clue on what to search for though.

**Comment by MagnaMike** [comment]
I'll try and find a good illustrator tutorial video, I should probably watching them too. :grin:
