### ISSUE TITLE
Replace the Twitch icon?

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5107]
First of all, I mean no disrespect towards the person who made this icon, however, I think it would be more suitable if there actaully were a Twitch icon instead. And/or the Twitch logo.

**Current one:** 
![](http://preview.dreamnet.at/?image=https://raw.githubusercontent.com/glasklart/hd/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/tv.twitch@2x.png)
https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/tv.twitch%402x.png

**Here's a few examples;**

**Twitch**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5945167/dbdde34e-a72c-11e4-9a07-f4af051def12.png)
https://cloud.githubusercontent.com/assets/10730122/5945167/dbdde34e-a72c-11e4-9a07-f4af051def12.png

**Source:**
https://cloud.githubusercontent.com/assets/10730122/5945309/c2f6572a-a72d-11e4-9a59-fdfac757f718.png

**Logo**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5945159/cb5b1212-a72c-11e4-9d03-66e4c2bbda97.png)
https://cloud.githubusercontent.com/assets/10730122/5945159/cb5b1212-a72c-11e4-9d03-66e4c2bbda97.png

**Source:**
https://cloud.githubusercontent.com/assets/10730122/5945315/d5ce3b92-a72d-11e4-8833-dc6c69a9cce7.png

**Twitch+Logo**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5945173/e721ba28-a72c-11e4-8789-c8589f2274f4.png)
https://cloud.githubusercontent.com/assets/10730122/5945173/e721ba28-a72c-11e4-8789-c8589f2274f4.png

**Source:**
https://cloud.githubusercontent.com/assets/10730122/5945330/e6146f3a-a72d-11e4-80e9-170a64115e7d.png

**Wasn't sure where to post this, move if need be.**

**Comment by MagnaMike** [comment]
Can you submit a proper [icon request](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request) and we can go from there. Thanks!

**Comment by MagnaMike** [comment]
Here, I made the issue. #5110
