### ISSUE TITLE
Tailor

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#5109]
**App Name:** Tailor
**Bundle ID:** com.foundry63.tailor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926653095">926653095</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tailor/id926653095?mt=8&uo=4">https://itunes.apple.com/us/app/tailor/id926653095?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Foundry 63, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/foundry-63/id926653094?uo=4>© Foundry 63</a>
**Supported Devices:** iPadMini, iPhone4, iPadThirdGen4G, iPad2Wifi, iPhone5, iPhone6, iPadFourthGen4G, iPodTouchFifthGen, iPhone5c, iPhone6Plus, iPhone5s, iPadFourthGen, iPad23G, iPadMini4G, iPhone4S, iPadThirdGen
**Original Artwork:**
<img src="http://a1408.phobos.apple.com/us/r30/Purple3/v4/12/c2/22/12c222b3-526e-ada6-5348-2af49fe10412/pr_source.png?downloadKey=1422487910_4e25260594ad2a2d85ede708f5159545" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5952176/f73e675e-a73f-11e4-96e9-172fd20fb942.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5952176/f73e675e-a73f-11e4-96e9-172fd20fb942.png)
https://cloud.githubusercontent.com/assets/2236254/5952176/f73e675e-a73f-11e4-96e9-172fd20fb942.png

Source:
https://cloud.githubusercontent.com/assets/2236254/5952177/fa873b52-a73f-11e4-87dd-bcae3eda95a7.png

**Comment by ivanov007** [comment]
@MagnaMike looks great :+1:

**Comment by dreamnet** [comment]
@MagnaMike WOW :open_mouth:  :+1:

**Comment by MagnaMike** [comment]
It took me longer then I care to admit. :blush:

**Comment by dreamnet** [comment]
@MagnaMike :grinning:
