### ISSUE TITLE
Twitch: Live Game Streaming

### ISSUE THREAD

**Issue by MagnaMike** [glasklart/hd#5110]
**App Name:** Twitch: Live Game Streaming
**Bundle ID:** tv.twitch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=460177396">460177396</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/twitch-live-game-streaming/id460177396?uo=4">https://apps.apple.com/us/app/twitch-live-game-streaming/id460177396?uo=4</a>
**App Version:** 8.5.1
**Seller:** Twitch Interactive, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/twitch-interactive-inc/id358612219?uo=4">© Twitch Interactive, Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/60/74/2d/60742d33-aeb4-e928-60b4-2d20cef11d45/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73137754-fbdd3000-405b-11ea-97e8-387ac0bcca84.png)

**Comment by MagnaMike** [comment]
Courtesy of @Trubbel

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5945159/cb5b1212-a72c-11e4-9d03-66e4c2bbda97.png)
https://cloud.githubusercontent.com/assets/10730122/5945159/cb5b1212-a72c-11e4-9d03-66e4c2bbda97.png

**Source:**
https://cloud.githubusercontent.com/assets/10730122/5945315/d5ce3b92-a72d-11e4-8833-dc6c69a9cce7.png

**Comment by Trubbel** [comment]
Sorry I was away and didn't see your message, however, I'm glad you did change it yourself. Thanks!

**Comment by MagnaMike** [comment]
No problem! :+1:

**Comment by Mitchdog27** [comment]
needs an update

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73137754-fbdd3000-405b-11ea-97e8-387ac0bcca84.png)
https://user-images.githubusercontent.com/2068130/73137754-fbdd3000-405b-11ea-97e8-387ac0bcca84.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73137759-0c8da600-405c-11ea-8f4a-ef2a84553cd7.png
