### ISSUE TITLE
Camera-Fotolr

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5111]
**App Name:** Camera-Fotolr
**Bundle ID:** com.tinypiece.fotolrcs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=475591766">475591766</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camera-fotolr/id475591766?mt=8&uo=4">https://itunes.apple.com/us/app/camera-fotolr/id475591766?mt=8&uo=4</a>
**App Version:** 1.2.8
**Seller:** Tiny Piece Co., Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tiny-piece-co.-ltd/id421120865?uo=4>© Tiny Piece Co., Ltd</a>
**Supported Devices:** iPadFourthGen, iPhone6, iPhone4S, iPadMini4G, iPhone-3GS, iPhone6Plus, iPadMini, iPadThirdGen4G, iPad2Wifi, iPodTouchFourthGen, iPhone4, iPhone5c, iPadThirdGen, iPad23G, iPhone5, iPodTouchFifthGen, iPadFourthGen4G, iPhone5s
**Original Artwork:**
<img src="http://a771.phobos.apple.com/us/r30/Purple2/v4/13/07/cd/1307cdbc-b390-7b1a-c039-991b50ba7a0d/mzl.suxajkpm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6087665/b03b77d2-ae4e-11e4-9b7a-d1595731251a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6087665/b03b77d2-ae4e-11e4-9b7a-d1595731251a.png)
https://cloud.githubusercontent.com/assets/2068130/6087665/b03b77d2-ae4e-11e4-9b7a-d1595731251a.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6087671/c106f9e2-ae4e-11e4-83b8-1c8d0225744a.png

**Comment by MagnaMike** [comment]
@dreamnet Tell me your secrets. :astonished:

**Comment by dreamnet** [comment]
@MagnaMike You have to invite me to dinner first. :scream: :laughing:

**Comment by MagnaMike** [comment]
@dreamnet You like steak? :cow2: 

Just kidding. :stuck_out_tongue: 

Nice icon though, I would love to have your skills!
