### ISSUE TITLE
I Dig It

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5112]
**App Name:** I Dig It
**Bundle ID:** com.inmotionsoftware.iDigIt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=314864297">314864297</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/i-dig-it/id314864297?mt=8&uo=4">https://itunes.apple.com/us/app/i-dig-it/id314864297?mt=8&uo=4</a>
**App Version:** 1.11
**Seller:** InMotion Software, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/inmotion-software-llc/id290538274?uo=4>© InMotion Software, LLC</a>
**Supported Devices:** iPhone5s, iPhone-3GS, iPodTouchFifthGen, iPadMini4G, iPhone5c, iPadFourthGen, iPadThirdGen4G, iPhone4S, iPhone6Plus, iPhone5, iPhone4, iPadThirdGen, iPhone6, iPad23G, iPodTouchFourthGen, iPadFourthGen4G, iPad2Wifi, iPadMini
**Original Artwork:**
<img src="http://a679.phobos.apple.com/us/r30/Purple1/v4/95/c3/b8/95c3b890-6381-6ae1-7e56-c6546d2adbe0/pr_source.jpg?downloadKey=1422515439_d417c4c9372a82d917c0b8c9e6ef16ca" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6185229/3d31eaf0-b36c-11e4-8b07-293529cab26d.png)

**Comment by andreolidavide** [comment]
It is difficult, this is the best I managed as of now. I will try to work on it a bit more if you think it's necessary.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6134318/b483f476-b160-11e4-9abf-d09bc0ea347e.png)
https://cloud.githubusercontent.com/assets/10515074/6134318/b483f476-b160-11e4-9abf-d09bc0ea347e.png

Source
https://cloud.githubusercontent.com/assets/10515074/6134351/f7f5165e-b160-11e4-8e6a-3efe17647776.png

**Comment by quantum8** [comment]
looks great to me @andreolidavide !

**Comment by MagnaMike** [comment]
@andreolidavide Would have been nice to have the whole vehicle, but is definitely understandable why not due to complexity. Since no one else has stepped up to the challenge and because it looks good, we will take it. Great work. :+1:

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6154745/5bd1debe-b22e-11e4-97a1-946e059c9922.png)
https://cloud.githubusercontent.com/assets/10515074/6154745/5bd1debe-b22e-11e4-97a1-946e059c9922.png

Source
https://cloud.githubusercontent.com/assets/10515074/6154765/7ee03a40-b22e-11e4-8c4a-cf89c99709af.png

@MagnaMike is this ok? Or should I make those lines a bit wider?

**Comment by dreamnet** [comment]
@andreolidavide Yeah, if you could make the lines of your second icon a bit wider.... :+1:

**Comment by andreolidavide** [comment]
This is the best I could do without losing too many details
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6185229/3d31eaf0-b36c-11e4-8b07-293529cab26d.png)

https://cloud.githubusercontent.com/assets/10515074/6185229/3d31eaf0-b36c-11e4-8b07-293529cab26d.png

Source
https://cloud.githubusercontent.com/assets/10515074/6185239/62c57d5e-b36c-11e4-8310-41593b89eac0.png

**Comment by dreamnet** [comment]
@andreolidavide Looks great! :+1:

**Comment by MagnaMike** [comment]
Yeah, excellent job @andreolidavide!

**Comment by andreolidavide** [comment]
@dreamnet @MagnaMike thanks :smile:
