### ISSUE TITLE
Broken Sword 2 - the Smoking Mirror: Remastered

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5113]
**App Name:** Broken Sword 2 - the Smoking Mirror: Remastered
**Bundle ID:** iSword2English
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395483212">395483212</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/broken-sword-2-smoking-mirror/id395483212?mt=8&uo=4">https://itunes.apple.com/us/app/broken-sword-2-smoking-mirror/id395483212?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Revolution Software Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/revolution/id331733641?uo=4>© Revolution</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/39/b6/a2/39b6a223-d9c4-411c-895e-74d20d7b4d9d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18806782/0bb41cbe-8237-11e6-8ade-6d05089c1735.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5969187/df5cb988-a820-11e4-95e4-925213ebe097.png)
https://cloud.githubusercontent.com/assets/2068130/5969187/df5cb988-a820-11e4-95e4-925213ebe097.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5969192/ef2ec98c-a820-11e4-88b3-3d82a7cabfe3.png

**Comment by MagnaMike** [comment]
@dreamnet Perfect :ok_hand:

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18806782/0bb41cbe-8237-11e6-8ade-6d05089c1735.png)
https://cloud.githubusercontent.com/assets/2068130/18806782/0bb41cbe-8237-11e6-8ade-6d05089c1735.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18806784/1b07328c-8237-11e6-9857-4fbe069e17e9.png
