### ISSUE TITLE
My Currency PRO - Currency & Exchange Rates Converter

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5114]
t**App Name:** My Currency PRO - Currency & Exchange Rates Converter
**Bundle ID:** com.sandrostricker.MyCurrency
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=297582567">297582567</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-currency-pro-currency-exchange/id297582567?mt=8&uo=4">https://itunes.apple.com/us/app/my-currency-pro-currency-exchange/id297582567?mt=8&uo=4</a>
**App Version:** 5.3.1
**Seller:** Sandro Stricker
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sandro-stricker/id296385262?uo=4>© Sandro Stricker</a>
**Supported Devices:** iPodTouchFifthGen, iPadThirdGen, iPhone5s, iPadMini, iPhone6, iPadMini4G, iPhone4S, iPhone5, iPhone6Plus, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPad23G, iPhone4, iPad2Wifi, iPhone5c
**Original Artwork:**
<img src="http://a1544.phobos.apple.com/us/r30/Purple5/v4/37/07/9f/37079fb2-9f3d-ca3b-5bf6-a45ef6def6ac/mzl.ttwdggnz.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5976692/1085c322-a891-11e4-92d7-fcd087519ffe.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5973961/c8d97db0-a86e-11e4-9529-5893f1df7ff0.png)
https://cloud.githubusercontent.com/assets/10730122/5973961/c8d97db0-a86e-11e4-9529-5893f1df7ff0.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5973957/ba51a308-a86e-11e4-82db-de3714260959.png

**Comment by ivanov007** [comment]
@Trubbel yup it looks good, jus one small detail, the cross looks thinner on the source file, can you make it as thick as in the 120px icon?

**Comment by Trubbel** [comment]
Like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5976597/0a2ce3a8-a890-11e4-9da2-2b8c4dd44373.png)

**Comment by Trubbel** [comment]
I edited the cross after I re-sized the source to fit the icon, but I guess it should be something like this;
https://cloud.githubusercontent.com/assets/10730122/5976678/e8349010-a890-11e4-9f20-82c09da4163f.png

I didn't notice the plus sign when I first was done with the icon, so I did it a little bit thicker.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5976692/1085c322-a891-11e4-92d7-fcd087519ffe.png)

**Comment by MagnaMike** [comment]
Here, I edited @Trubbel's source. Should be better now. 
https://cloud.githubusercontent.com/assets/2236254/5978109/577eb3b8-a86b-11e4-82f6-6d753c85b212.png
