### ISSUE TITLE
My Currency Exchange Rates Converter

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5116]
**App Name:** My Currency Exchange Rates Converter
**Bundle ID:** com.sandrostricker.MyCurrency-Lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527378223">527378223</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-currency-exchange-rates/id527378223?mt=8&uo=4">https://itunes.apple.com/us/app/my-currency-exchange-rates/id527378223?mt=8&uo=4</a>
**App Version:** 5.3.1
**Seller:** Sandro Stricker
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sandro-stricker/id296385262?uo=4>© Sandro Stricker</a>
**Supported Devices:** iPad23G, iPhone4S, iPhone6Plus, iPadMini4G, iPadFourthGen, iPad2Wifi, iPhone6, iPodTouchFifthGen, iPadThirdGen, iPhone5, iPadMini, iPadFourthGen4G, iPhone5s, iPadThirdGen4G, iPhone4, iPhone5c
**Original Artwork:**
<img src="http://a922.phobos.apple.com/us/r30/Purple5/v4/25/db/9d/25db9dc4-9882-12a8-bc0a-cb92533107de/mzl.wkppjjsj.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5978536/6637f4ca-a86e-11e4-9bfb-98f39b13d14c.png)

**Comment by dreamnet** [comment]
Refers to #5114.

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5978221/5c376890-a86c-11e4-8f26-541acb5e363a.png)
https://cloud.githubusercontent.com/assets/2236254/5978221/5c376890-a86c-11e4-8f26-541acb5e363a.png

Source:
https://cloud.githubusercontent.com/assets/2236254/5978196/1a1dc38c-a86c-11e4-8b9b-372fc35d3bce.png

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/5978536/6637f4ca-a86e-11e4-9bfb-98f39b13d14c.png)
https://cloud.githubusercontent.com/assets/2236254/5978536/6637f4ca-a86e-11e4-9bfb-98f39b13d14c.png
Source:
https://cloud.githubusercontent.com/assets/2236254/5978539/679bdb4c-a86e-11e4-860e-18f6ab97d883.png
