### ISSUE TITLE
Microsoft Power BI

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5119]
**App Name:** Microsoft Power BI
**Bundle ID:** com.microsoft.powerbimobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=929738808">929738808</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-power-bi/id929738808?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-power-bi/id929738808?mt=8&uo=4</a>
**App Version:** 18.4
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?mt=8&uo=4">© Microsoft Corporation</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/be/03/75/be0375f2-6e92-f3de-3ac4-be38dde1bab5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58765005-8a9db980-856e-11e9-801d-3a1090c9f88c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5975622/2bb8f9c4-a883-11e4-9287-69e0715c5cda.png)
https://cloud.githubusercontent.com/assets/2068130/5975622/2bb8f9c4-a883-11e4-9287-69e0715c5cda.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5975630/3ae52562-a883-11e4-9dd2-6aef1a332756.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58765005-8a9db980-856e-11e9-801d-3a1090c9f88c.png)
https://user-images.githubusercontent.com/20930745/58765005-8a9db980-856e-11e9-801d-3a1090c9f88c.png

Source:
https://user-images.githubusercontent.com/20930745/58765006-8bcee680-856e-11e9-9974-d1be76780a9e.png
