### ISSUE TITLE
Inside BJJ

### ISSUE THREAD

**Issue by richmFTW** [glasklart/hd#512]
**App Name:** Inside BJJ
**Bundle ID:** tv.wizzard.swampd3093
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=396194093">396194093</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inside-bjj/id396194093?mt=8&uo=4">https://itunes.apple.com/us/app/inside-bjj/id396194093?mt=8&uo=4</a>
**App Version:** 2.0.27
**Seller:** Wizzard Software
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wizzard-media/id318848960?uo=4">© Wizzard Media</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/e2/20/29/e2202967-1aab-d032-b186-32e62c416ac4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20240103/6dfe9dc2-a910-11e6-9dc6-4702ffd3511f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20240103/6dfe9dc2-a910-11e6-9dc6-4702ffd3511f.png)
https://cloud.githubusercontent.com/assets/20930745/20240103/6dfe9dc2-a910-11e6-9dc6-4702ffd3511f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20240114/8ab001ae-a910-11e6-9f8a-65d3c208557b.png
