### ISSUE TITLE
NOVOFLEET

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#5120]
**App Name:** NOVOFLEET
**Bundle ID:** NOVOFLEETMobileApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606852907">606852907</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/novofleet/id606852907?mt=8&uo=4">https://itunes.apple.com/us/app/novofleet/id606852907?mt=8&uo=4</a>
**App Version:** 6.1.0
**Seller:** Novofleet GmbH u. Co. KG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/novofleet-gmbh-+-co.-kg/id510759766?uo=4>© NOVOFLEET GmbH + Co. KG</a>
**Supported Devices:** iPadFourthGen, iPhone5s, iPhone6Plus, iPhone5, iPadFourthGen4G, iPadThirdGen4G, iPhone5c, iPadThirdGen, iPodTouchFifthGen, iPadMini4G, iPad23G, iPhone-3GS, iPad2Wifi, iPodTouchFourthGen, iPhone6, iPhone4, iPadMini, iPhone4S
**Original Artwork:**
<img src="http://a1694.phobos.apple.com/us/r30/Purple1/v4/ff/1e/b7/ff1eb715-119e-2bbf-1b23-d767dc0d3b5e/pr_source.jpg?downloadKey=1422701355_6a324bdd306e92761ac8156910774f71" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/5990724/8fb92984-a98d-11e4-94ac-03ea1bac351a.png)

**Comment by dreamnet** [comment]
Hmmm.....
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5989281/62c6619a-a982-11e4-9230-e0d1239747ac.png)
https://cloud.githubusercontent.com/assets/2068130/5989281/62c6619a-a982-11e4-9230-e0d1239747ac.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5989283/71fac5ca-a982-11e4-9398-0c0fa3ad1fa3.png

**Comment by MagnaMike** [comment]
@dreamnet What if you try inverting it?

**Comment by MagnaMike** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/5990724/8fb92984-a98d-11e4-94ac-03ea1bac351a.png)
https://cloud.githubusercontent.com/assets/2236254/5990724/8fb92984-a98d-11e4-94ac-03ea1bac351a.png
Source:
https://cloud.githubusercontent.com/assets/2236254/5990726/a0be94bc-a98d-11e4-9bb3-4cf601f7f945.png

**Comment by kieman** [comment]
the 2nd is nicer, thx

**Comment by dreamnet** [comment]
@kieman @MagnaMike Hmmmm.... Yes. I take the second one. :+1:
