### ISSUE TITLE
MacID for iOS

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5122]
t**App Name:** MacID for iOS
**Bundle ID:** com.kanecheshire.MacID
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=948478740">948478740</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/macid-for-ios/id948478740?mt=8&uo=4">https://itunes.apple.com/us/app/macid-for-ios/id948478740?mt=8&uo=4</a>
**App Version:** 1
**Seller:** Kane Cheshire
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kane-cheshire/id948478739?uo=4>© Kane Cheshire</a>
**Supported Devices:** iPad23G, iPadMini4G, iPadFourthGen4G, iPadFourthGen, iPad2Wifi, iPadMini, iPhone5c, iPodTouchFifthGen, iPhone6, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone6Plus, iPhone5, iPhone5s
**Original Artwork:**
<img src="http://a1398.phobos.apple.com/us/r30/Purple1/v4/c2/1d/62/c21d6293-f0fa-c2dd-355a-bb6f18e20943/pr_source.png?downloadKey=1422721164_70b59c52ab65d39fb70d2e36d3df627a" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5988368/3dbba0ec-a95d-11e4-977d-c89e92e14481.png)

**Comment by Trubbel** [comment]
Tried to change it a bit where you place your finger for the scanner, however I'm not sure it turned out that great, if anyone can do it better, please do!

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5988212/6921c704-a956-11e4-9930-1373b631d74b.png)

Source:
https://cloud.githubusercontent.com/assets/10730122/5988211/5ed81ad2-a956-11e4-8abb-70ee0e0e52ae.png

**Comment by dreamnet** [comment]
@Trubbel Seems you have used transparency for the middle part of the icon witch is not allowed. Here is an alternative:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5988368/3dbba0ec-a95d-11e4-977d-c89e92e14481.png)
https://cloud.githubusercontent.com/assets/2068130/5988368/3dbba0ec-a95d-11e4-977d-c89e92e14481.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5988369/512e852c-a95d-11e4-92bd-64daac8faa54.png

**Comment by Trubbel** [comment]
Okay, I'll keep that in mind, and the icon you made is surely much better!

**Comment by ivanov007** [comment]
@dreamnet don't tell me you used you own fingerprint for this one :wink:

**Comment by dreamnet** [comment]
@ivanov007 Yes, I did. Do you think I have a security problem now? :fearful: :oncoming_police_car: :wink:
