### ISSUE TITLE
Freeletics – functional high-intensity bodyweight workouts

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#5123]
**App Name:** Freeletics – functional high-intensity bodyweight workouts
**Bundle ID:** com.Freeletics.Freeletics-Lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=654810212">654810212</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/freeletics-functional-high/id654810212?mt=8&uo=4">https://itunes.apple.com/us/app/freeletics-functional-high/id654810212?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Freeletics GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/freeletics-gmbh/id579309595?uo=4>© Freeletics GmbH</a>
**Supported Devices:** iPhone4S, iPhone4, iPodTouchFifthGen, iPad23G, iPhone6, iPhone5s, iPhone5c, iPhone5, iPadMini4G, iPadFourthGen, iPadMini, iPadThirdGen4G, iPhone6Plus, iPadThirdGen, iPad2Wifi, iPadFourthGen4G
**Original Artwork:**
<img src="http://a18.phobos.apple.com/us/r30/Purple5/v4/bc/a2/5d/bca25d3a-1d7e-2f77-0747-69a5e0853acc/mzl.kubicwbp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5989158/2647fe58-a97e-11e4-9e4f-71d55f49e30b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5989158/2647fe58-a97e-11e4-9e4f-71d55f49e30b.png)
https://cloud.githubusercontent.com/assets/2068130/5989158/2647fe58-a97e-11e4-9e4f-71d55f49e30b.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5989160/34e90bd2-a97e-11e4-8a42-ba07b8033879.png
