### ISSUE TITLE
GameGem

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5124]
**App Name:** GameGem
**Bundle ID:** com.tyc.MemSearch
**Version:** 0.7
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/7649001/2e1acdc4-fae9-11e4-9691-580ffb1d62f8.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7649348/70c90d0e-faec-11e4-86df-3272e0b6163d.png)

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5992170/1002d4ac-aa1d-11e4-9528-78310ca1a4f9.png)
https://cloud.githubusercontent.com/assets/2068130/5992170/1002d4ac-aa1d-11e4-9528-78310ca1a4f9.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5992173/2a607f34-aa1d-11e4-8afb-590ba7bbd344.png

**Comment by Trubbel** [comment]
The icon has been updated, I tried sending the image from my phone to the computer but it just turns out black. I can't remember what the program is called to fix this.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7649348/70c90d0e-faec-11e4-86df-3272e0b6163d.png)
https://cloud.githubusercontent.com/assets/2068130/7649348/70c90d0e-faec-11e4-86df-3272e0b6163d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7649353/7e33a51c-faec-11e4-987a-a89dbf81f80b.png

**Comment by Trubbel** [comment]
@dreamnet Nice!

**Comment by dreamnet** [comment]
@Trubbel THX!
