### ISSUE TITLE
MI BAND

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#5125]
**App Name:** MI BAND
**Bundle ID:** HM.wristband
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=938688461">938688461</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mi-band/id938688461?mt=8&uo=4">https://itunes.apple.com/us/app/mi-band/id938688461?mt=8&uo=4</a>
**App Version:** 1.0.16
**Seller:** Anhui Huami Information Technology Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/anhui-huami-information-technology/id938688460?uo=4>© Anhui Huami Information Technology Co., Ltd.</a>
**Supported Devices:** iPhone4S, iPadThirdGen, iPhone4, iPadFourthGen4G, iPhone6, iPodTouchFifthGen, iPadMini4G, iPhone5, iPhone5s, iPadThirdGen4G, iPhone6Plus, iPad2Wifi, iPhone5c, iPadMini, iPadFourthGen, iPad23G
**Original Artwork:**
<img src="http://a1383.phobos.apple.com/us/r30/Purple3/v4/fd/19/a0/fd19a02b-d193-486e-d737-a10702b03cc8/mzl.jfremjsl.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5993067/b5b7fac8-aa43-11e4-98d2-61bd915cf39b.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5993067/b5b7fac8-aa43-11e4-98d2-61bd915cf39b.png)
https://cloud.githubusercontent.com/assets/10730122/5993067/b5b7fac8-aa43-11e4-98d2-61bd915cf39b.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5993066/a9456514-aa43-11e4-83b0-d2dac1d8ae36.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
