### ISSUE TITLE
Glitch - Channel Surfing for Twitch

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5126]
**App Name:** Glitch - Channel Surfing for Twitch
**Bundle ID:** so.levi.Glitch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=951051961">951051961</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glitch-channel-surfing-for/id951051961?mt=8&uo=4">https://itunes.apple.com/us/app/glitch-channel-surfing-for/id951051961?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Levi McCallum
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/levi-mccallum/id884255204?uo=4>© Levi McCallum</a>
**Supported Devices:** iPhone5c, iPhone5s, iPodTouchFifthGen, iPhone6Plus, iPadThirdGen4G, iPadFourthGen4G, iPhone4S, iPhone6, iPadFourthGen, iPad23G, iPad2Wifi, iPadMini4G, iPhone5, iPadThirdGen, iPadMini
**Original Artwork:**
<img src="http://a1995.phobos.apple.com/us/r30/Purple1/v4/bf/b7/32/bfb73258-169e-d9a6-bf40-a7996764138f/mzl.wizqqezz.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5993591/3a849a2e-aa56-11e4-95d4-eee6e50ef2ef.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5993591/3a849a2e-aa56-11e4-95d4-eee6e50ef2ef.png)
https://cloud.githubusercontent.com/assets/10730122/5993591/3a849a2e-aa56-11e4-95d4-eee6e50ef2ef.png


Source:
https://cloud.githubusercontent.com/assets/10730122/5993587/2c44dd0c-aa56-11e4-8bf4-bb6c26aedacd.png

**Comment by dreamnet** [comment]
@Trubbel Jup. :+1:
