### ISSUE TITLE
ÖstgötaTrafiken

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5129]
**App Name:** ÖstgötaTrafiken
**Bundle ID:** se.forslerostjerna.OGT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=352212581">352212581</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/am/app/ostgotatrafiken/id352212581?mt=8&uo=4">https://itunes.apple.com/am/app/ostgotatrafiken/id352212581?mt=8&uo=4</a>
**App Version:** 3.4.4
**Seller:** Forsler & Stjerna Konsult
**Developer:** <a target="_blank" href=https://itunes.apple.com/am/artist/forsler-stjerna-konsult/id303155675?mt=8&uo=4>© Forsler & Stjerna Konsult</a>
**Supported Devices:** iPhone4S, iPad23G, iPodTouchFifthGen, iPhone5, iPadMini, iPadWifi, iPodTouchThirdGen, iPadThirdGen4G, iPad3G, iPadThirdGen, iPadFourthGen4G, iPhone6Plus, iPhone5s, iPad2Wifi, iPhone6, iPodTouchFourthGen, iPadMini4G, iPhone-3GS, iPhone5c, iPadFourthGen, iPhone4
**Original Artwork:**
<img src="http://a327.phobos.apple.com/us/r30/Purple5/v4/15/60/10/15601094-1ff5-c237-fb80-c08ff98c6e31/mzl.brjprpbp.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994051/2267cac8-aa66-11e4-9539-48faf8dc695c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994051/2267cac8-aa66-11e4-9539-48faf8dc695c.png)
https://cloud.githubusercontent.com/assets/10730122/5994051/2267cac8-aa66-11e4-9539-48faf8dc695c.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5994048/1d52b3c2-aa66-11e4-8a15-0f286c4d6997.png

**Comment by dreamnet** [comment]
@Trubbel Yessir! :+1:
