### ISSUE TITLE
CS:GO Insider

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5131]
**App Name:** CS:GO Insider
**Bundle ID:** com.xc.CSGOInsider
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=906450052">906450052</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cs-go-insider/id906450052?mt=8&uo=4">https://itunes.apple.com/us/app/cs-go-insider/id906450052?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Ilya Vydrenkov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ilya-vydrenkov/id891736186?uo=4>© Ilya Vydrenkov</a>
**Supported Devices:** iPhone6Plus, iPodTouchFifthGen, iPhone4, iPadFourthGen4G, iPhone5c, iPad2Wifi, iPhone6, iPadThirdGen4G, iPhone4S, iPhone5s, iPadFourthGen, iPadMini4G, iPad23G, iPadThirdGen, iPadMini, iPhone5
**Original Artwork:**
<img src="http://a914.phobos.apple.com/us/r30/Purple3/v4/5f/a9/e5/5fa9e563-bdc7-f8ab-3bc2-992f00cd1ace/mzl.evxudsdi.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994464/a35abfec-aa74-11e4-9b74-53bddbf68181.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994464/a35abfec-aa74-11e4-9b74-53bddbf68181.png)
https://cloud.githubusercontent.com/assets/10730122/5994464/a35abfec-aa74-11e4-9b74-53bddbf68181.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5994462/9744a1aa-aa74-11e4-853e-6772ef9a6f2f.png

**Comment by MagnaMike** [comment]
@Trubbel Looks good. :+1:
