### ISSUE TITLE
Rhombus for reddit

### ISSUE THREAD

**Issue by Pokeclipse** [glasklart/hd#5132]
**App Name:** Rhombus for reddit
**Bundle ID:** com.caliberlabs.rhombus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=917422733">917422733</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rhombus-for-reddit/id917422733?mt=8&uo=4">https://itunes.apple.com/us/app/rhombus-for-reddit/id917422733?mt=8&uo=4</a>
**App Version:** 1.2.8
**Seller:** Caliber Labs LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/caliber-labs-llc/id285971708?uo=4>© Caliber Labs LLC</a>
**Supported Devices:** iPhone4S, iPadMini, iPhone6Plus, iPad23G, iPhone5s, iPadFourthGen4G, iPadFourthGen, iPhone6, iPodTouchFifthGen, iPadThirdGen4G, iPhone5, iPadMini4G, iPhone4, iPad2Wifi, iPhone5c, iPadThirdGen
**Original Artwork:**
<img src="http://a1866.phobos.apple.com/us/r30/Purple5/v4/26/4f/61/264f6188-0213-e035-5f87-4db71b024e47/mzl.iprzxczn.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994747/b212704c-aa7f-11e4-9cc2-9c59bd34703a.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994747/b212704c-aa7f-11e4-9cc2-9c59bd34703a.png)
https://cloud.githubusercontent.com/assets/10730122/5994747/b212704c-aa7f-11e4-9cc2-9c59bd34703a.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5994745/a9eb81ba-aa7f-11e4-9ac2-ae0ef5df06c8.png

**Comment by Pokeclipse** [comment]
@Trubbel Perfect, thanks.
