### ISSUE TITLE
DEVICE 6

### ISSUE THREAD

**Issue by Pokeclipse** [glasklart/hd#5133]
**App Name:** DEVICE 6
**Bundle ID:** com.simogo.devicesix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=680366065">680366065</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/device-6/id680366065?mt=8&uo=4">https://itunes.apple.com/us/app/device-6/id680366065?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Simogo AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/simogo-ab/id404446783?uo=4>© Simogo AB</a>
**Supported Devices:** iPhone4, iPadWifi, iPhone5c, iPad2Wifi, iPhone4S, iPadMini, iPadMini4G, iPodTouchFifthGen, iPadThirdGen, iPadFourthGen4G, iPhone6Plus, iPad3G, iPodTouchFourthGen, iPhone6, iPadThirdGen4G, iPad23G, iPodTouchThirdGen, iPhone5, iPhone5s, iPhone-3GS, iPadFourthGen
**Original Artwork:**
<img src="http://a548.phobos.apple.com/us/r30/Purple/v4/aa/9e/5e/aa9e5e1a-f2ef-5151-cd00-de6f1697f380/mzl.kwmwqgox.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994848/b70f87f2-aa83-11e4-92fb-e9452b85071c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994743/880aea2c-aa7f-11e4-821b-fae6d8a72c78.png)
https://cloud.githubusercontent.com/assets/10730122/5994743/880aea2c-aa7f-11e4-821b-fae6d8a72c78.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5994740/7e611a46-aa7f-11e4-8772-0e8394245c04.png

**Comment by Pokeclipse** [comment]
@Trubbel Great!

**Comment by Trubbel** [comment]
@Pokeclipse @MagnaMike I made another version as well, what do you guys think?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994848/b70f87f2-aa83-11e4-92fb-e9452b85071c.png)
https://cloud.githubusercontent.com/assets/10730122/5994848/b70f87f2-aa83-11e4-92fb-e9452b85071c.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5994856/c2f12d8c-aa83-11e4-83eb-6516237bcd86.png

**Comment by MagnaMike** [comment]
@Trubbel Usually we like to stick as close to the original as possible. That being said, in this case I think the new version is better. :+1:

**Comment by Trubbel** [comment]
@MagnaMike I wasn't really liking how the original icon turned out and I can accept that you usually want us to stick to the original. Thanks for the exception though!

**Comment by ivanov007** [comment]
@Trubbel @MagnaMike agree :+1:
