### ISSUE TITLE
Handy Photo

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5136]
**App Name:** Handy Photo
**Bundle ID:** com.advasoft.handyphoto3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598565205">598565205</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/handy-photo/id598565205?mt=8&uo=4">https://itunes.apple.com/us/app/handy-photo/id598565205?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Maksym Davydov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/adva-soft/id373311255?uo=4>© Adva-Soft</a>
**Supported Devices:** iPhone6Plus, iPhone4S, iPodTouchFifthGen, iPad3G, iPhone5c, iPadThirdGen, iPhone5, iPodTouchThirdGen, iPad2Wifi, iPhone6, iPad23G, iPadThirdGen4G, iPhone4, iPadMini, iPodTouchFourthGen, iPadMini4G, iPadFourthGen, iPadFourthGen4G, iPhone-3GS, iPhone5s, iPadWifi
**Original Artwork:**
<img src="http://a947.phobos.apple.com/us/r30/Purple3/v4/02/ce/ac/02ceac3d-d43a-8f7e-fd07-8791414285d4/mzl.vbylqkws.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994983/a4578f3a-aa86-11e4-89c0-c5a985b200a1.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/5994983/a4578f3a-aa86-11e4-89c0-c5a985b200a1.png)
https://cloud.githubusercontent.com/assets/10730122/5994983/a4578f3a-aa86-11e4-89c0-c5a985b200a1.png

Source:
https://cloud.githubusercontent.com/assets/10730122/5994981/98a2ef5e-aa86-11e4-8055-a40c6c659188.png

**Comment by MagnaMike** [comment]
@Trubbel Yep!

**Comment by dreamnet** [comment]
@Trubbel You are climbing up in our [contributors list](https://github.com/glasklart/hd/graphs/contributors). Good work, keep on!
