### ISSUE TITLE
Barclays US

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5137]
**App Name:** Barclays US
**Bundle ID:** com.barclaycardus.iphonesvc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=425199399">425199399</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/barclays-us/id425199399?mt=8&uo=4">https://itunes.apple.com/us/app/barclays-us/id425199399?mt=8&uo=4</a>
**App Version:** 6.23.4
**Seller:** Barclays Bank of Delaware
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/barclays-bank-delaware/id425199402?uo=4">© Barclays Bank Delaware</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/07/ad/06/07ad0675-8b59-afd0-fa1a-12c731b9523c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/51439010-9ae68380-1cb4-11e9-818f-82c9a454c136.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6030622/c2f923ea-abc6-11e4-9317-5c98d0e65105.png)
https://cloud.githubusercontent.com/assets/2236254/6030622/c2f923ea-abc6-11e4-9317-5c98d0e65105.png
Source:
![Hello to whoever is reading this! :-) ](https://cloud.githubusercontent.com/assets/2236254/6030611/b40c2a26-abc6-11e4-865b-1e1640f79269.png)

**Comment by boxermansr** [comment]
Sweet, that'll work for me :) Thanks.

**Comment by MagnaMike** [comment]
@boxermansr No problem!

**Comment by dreamnet** [comment]
@MagnaMike Great! :+1: @boxermansr Please don't close issues. I will do this when I commit the icons to the master.

**Comment by boxermansr** [comment]
@dreamnet sorry almost sure that I clicked close and comment on accident, instead of just comment. :)

**Comment by dreamnet** [comment]
@boxermansr No problem! THX!

**Comment by MagnaMike** [comment]
@boxermansr I do that quite frequently too. :grin:

**Comment by dreamnet** [comment]
@MagnaMike :laughing:

**Comment by ivanov007** [comment]
@boxermansr @MagnaMike same here, that's why now I use Ctrl+Enter to submit the posts :smile:

**Comment by MagnaMike** [comment]
@ivanov007 Thanks for the tip! Here it goes.... *`Ctrl+Enter`*...

**Comment by XPEric** [comment]
![barclays](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/50730651-512c6380-1120-11e9-8f9e-659462b65d1f.png)
https://user-images.githubusercontent.com/2313873/50730651-512c6380-1120-11e9-8f9e-659462b65d1f.png

___
Source:
https://user-images.githubusercontent.com/2313873/50730650-496cbf00-1120-11e9-8cab-fdfc20e4a88a.png
