### ISSUE TITLE
Video Downloader Pro - Download Manager & Media Player

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5138]
**App Name:** Video Downloader Pro - Download Manager & Media Player
**Bundle ID:** com.devstarapps.videodl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=583307491">583307491</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/video-downloader-pro-download/id583307491?mt=8&uo=4">https://itunes.apple.com/us/app/video-downloader-pro-download/id583307491?mt=8&uo=4</a>
**App Version:** 1.11
**Seller:** NeonStar Devs Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/devstar-apps/id583307494?uo=4>© Devstar Apps</a>
**Supported Devices:** iPadFourthGen4G, iPhone5s, iPhone6, iPhone4S, iPhone4, iPhone5c, iPhone6Plus, iPodTouchFifthGen, iPhone-3GS, iPadFourthGen, iPadThirdGen, iPodTouchFourthGen, iPad2Wifi, iPadThirdGen4G, iPhone5, iPadMini, iPad23G, iPadMini4G
**Original Artwork:**
<img src="http://a1362.phobos.apple.com/us/r30/Purple1/v4/19/07/a7/1907a7c0-5d56-03c6-5b43-425be664e5f6/mzl.sdsnlfwq.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6052709/c7d57f1e-ac9b-11e4-9541-9900df59c9b4.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6052709/c7d57f1e-ac9b-11e4-9541-9900df59c9b4.png)
https://cloud.githubusercontent.com/assets/3090247/6052709/c7d57f1e-ac9b-11e4-9541-9900df59c9b4.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/6052708/c7cda1fe-ac9b-11e4-910b-1e2a724a40ff.png
