### ISSUE TITLE
DEICHMANN

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5139]
**App Name:** DEICHMANN
**Bundle ID:** com.deichmann.deichmannapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=634957574">634957574</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/deichmann/id634957574?mt=8&uo=4">https://itunes.apple.com/gb/app/deichmann/id634957574?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** DeichmannSE
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/artist/deichmann-se/id634957577?uo=4>© Deichmann SE</a>
**Supported Devices:** iPhone6, iPhone5s, iPhone6Plus, iPadWifi, iPadThirdGen, iPad3G, iPadMini4G, iPhone-3GS, iPhone5c, iPodTouchThirdGen, iPodTouchFifthGen, iPadFourthGen, iPadMini, iPad2Wifi, iPad23G, iPhone4, iPodTouchFourthGen, iPadThirdGen4G, iPhone5, iPhone4S, iPadFourthGen4G
**Original Artwork:**
<img src="http://a1705.phobos.apple.com/us/r30/Purple/v4/d7/41/45/d741454f-3754-842f-d83d-d21e89ee2bbc/mzl.mcinbuxa.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6052647/cbd8b92e-ac9a-11e4-8243-c712dd533726.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6052647/cbd8b92e-ac9a-11e4-8243-c712dd533726.png
https://cloud.githubusercontent.com/assets/3090247/6052647/cbd8b92e-ac9a-11e4-8243-c712dd533726.png
---
Source:
https://cloud.githubusercontent.com/assets/3090247/6052648/cbdcba10-ac9a-11e4-9a1f-e1f2ffb82b40.png
