### ISSUE TITLE
Yummly Recipes & Grocery Shopping List

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5142]
**App Name:** Yummly Recipes & Grocery Shopping List
**Bundle ID:** com.yummly.production
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589625334">589625334</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yummly-recipes-grocery-shopping/id589625334?mt=8&uo=4">https://itunes.apple.com/us/app/yummly-recipes-grocery-shopping/id589625334?mt=8&uo=4</a>
**App Version:** 1.8.95
**Seller:** Yummly, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/yummly/id589625337?uo=4>© Yummly</a>
**Supported Devices:** iPhone6, iPodTouchFifthGen, iPhone6Plus, iPadFourthGen4G, iPadMini, iPadThirdGen4G, iPad2Wifi, iPad23G, iPadMini4G, iPhone5s, iPhone5c, iPhone5, iPadThirdGen, iPhone4S, iPadFourthGen, iPhone4
**Original Artwork:**
<img src="http://a955.phobos.apple.com/us/r30/Purple3/v4/f7/6e/c5/f76ec582-52bc-4d8e-280b-615375010a65/mzl.puiowusy.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6069778/02ce530c-ad3c-11e4-909b-61e0105d89ef.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6069778/02ce530c-ad3c-11e4-909b-61e0105d89ef.png
https://cloud.githubusercontent.com/assets/10394552/6069778/02ce530c-ad3c-11e4-909b-61e0105d89ef.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6069769/f899d37a-ad3b-11e4-9ff5-42eac39b20b6.png

**Comment by ivanov007** [comment]
@PolarisBeaver great :+1:
