### ISSUE TITLE
Yonder - Outdoor Adventures

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5143]
**App Name:** Yonder - Outdoor Adventures
**Bundle ID:** com.greenmountain.yonder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=643341612">643341612</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yonder-outdoor-adventures/id643341612?mt=8&uo=4">https://itunes.apple.com/us/app/yonder-outdoor-adventures/id643341612?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Green Mountain Digital LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/green-mountain-digital/id333227389?uo=4>© Green Mountain Digital</a>
**Supported Devices:** iPadFourthGen4G, iPhone5s, iPhone5c, iPad2Wifi, iPadThirdGen, iPadMini4G, iPhone6, iPadMini, iPhone5, iPadFourthGen, iPad23G, iPhone4S, iPhone6Plus, iPhone4, iPodTouchFifthGen, iPadThirdGen4G
**Original Artwork:**
<img src="http://a1570.phobos.apple.com/us/r30/Purple5/v4/2b/6c/34/2b6c34a7-d9c3-3f23-f57b-410d6b269979/pr_source.png?downloadKey=1423183992_34d9451b32e9a617691d33ab56a130db" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6071103/3a341d9e-ad47-11e4-9425-65ee6e7c077c.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6071103/3a341d9e-ad47-11e4-9425-65ee6e7c077c.png)
https://cloud.githubusercontent.com/assets/10394552/6071103/3a341d9e-ad47-11e4-9425-65ee6e7c077c.png


Source File: https://cloud.githubusercontent.com/assets/10394552/6071098/3200e5ee-ad47-11e4-9641-192b714494af.png

**Comment by MagnaMike** [comment]
@PolarisBeaver Yep! :+1:
