### ISSUE TITLE
Quick Attack

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5144]
**App Name:** Quick Attack
**Bundle ID:** com.stefankendall.PokemonTypeEffectiveness
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=730091045">730091045</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quick-attack/id730091045?mt=8&uo=4">https://itunes.apple.com/us/app/quick-attack/id730091045?mt=8&uo=4</a>
**App Version:** 14
**Seller:** Usable Design LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/usable-design-llc/id329676753?uo=4>© Usable Design LLC</a>
**Supported Devices:** iPadThirdGen, iPadFourthGen, iPhone5s, iPadFourthGen4G, iPhone-3GS, iPhone4S, iPad23G, iPhone5c, iPhone6Plus, iPadThirdGen4G, iPhone4, iPhone5, iPodTouchFourthGen, iPhone6, iPadMini4G, iPad2Wifi, iPodTouchFifthGen, iPadMini
**Original Artwork:**
<img src="http://a294.phobos.apple.com/us/r30/Purple1/v4/50/56/ee/5056eeb8-716b-2877-2e67-3c41792ca8fd/mzl.jtxkpext.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6071559/0da24f44-ad4c-11e4-8a5e-023cdd5448ed.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6071559/0da24f44-ad4c-11e4-8a5e-023cdd5448ed.png)
https://cloud.githubusercontent.com/assets/10394552/6071559/0da24f44-ad4c-11e4-8a5e-023cdd5448ed.png


Source File: https://cloud.githubusercontent.com/assets/10394552/6071556/069e3488-ad4c-11e4-8960-83d416705879.png

**Comment by MagnaMike** [comment]
@glasklart/maintainers Should we have it closer to the original? I'm alright with the way @PolarisBeaver has is but what are your thoughts?

**Comment by dreamnet** [comment]
@PolarisBeaver Is there a reason why you made this one round?

**Comment by MagnaMike** [comment]
@dreamnet Pokemon

**Comment by PolarisBeaver** [comment]
The original icon is supposed to represent a Pokeball's colors from the game "Pokemon": https://www.google.com/search?q=pokeball&tbm=isch

Anyone with the theme and this app would recognize it easily, especially since glasklart has no colors in the icons to give clues on the glyphs. :)

**Comment by dreamnet** [comment]
@MagnaMike @PolarisBeaver THX for the explanation. So I take it. :+1:
