### ISSUE TITLE
Safeway Delivery

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5148]
**App Name:** Safeway Delivery
**Bundle ID:** com.safeway.shop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=687460321">687460321</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/safeway-delivery/id687460321?mt=8&uo=4">https://itunes.apple.com/us/app/safeway-delivery/id687460321?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Safeway Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/safeway-inc./id469532552?uo=4>© Safeway Inc.</a>
**Supported Devices:** iPadFourthGen, iPadMini, iPadThirdGen4G, iPodTouchFourthGen, iPadFourthGen4G, iPhone5s, iPadWifi, iPad23G, iPodTouchFifthGen, iPad3G, iPhone5, iPadThirdGen, iPhone4, iPadMini4G, iPhone6Plus, iPad2Wifi, iPhone4S, iPhone6, iPodTouchThirdGen, iPhone5c, iPhone-3GS
**Original Artwork:**
<img src="http://a585.phobos.apple.com/us/r30/Purple5/v4/a9/4a/df/a94adf81-baca-88bd-a436-1baeb41aeb55/mzl.vnuofirg.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6074570/4e6cdab0-ad76-11e4-8479-7f78d27f23c7.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6073226/4b953a0a-ad60-11e4-9f5c-7d5fde1bdfb5.png)
https://cloud.githubusercontent.com/assets/10394552/6073226/4b953a0a-ad60-11e4-9f5c-7d5fde1bdfb5.png


Source File: https://cloud.githubusercontent.com/assets/10394552/6073219/438e8eba-ad60-11e4-9c43-1356ed8a5ae0.png

**Comment by PolarisBeaver** [comment]
@MagnaMike there was a mistake I missed but can't ignore... lol. Could you instead use this?

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6074570/4e6cdab0-ad76-11e4-8479-7f78d27f23c7.png)
https://cloud.githubusercontent.com/assets/10394552/6074570/4e6cdab0-ad76-11e4-8479-7f78d27f23c7.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6074566/47d6e68c-ad76-11e4-951d-777d98994ac5.png

**Comment by MagnaMike** [comment]
@PolarisBeaver Ah, yes. Looks good.
