### ISSUE TITLE
flex:player - Video player for MKV, AVI, WMV, VOB, DivX, Xvid

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5151]
**App Name:** flex:player - Video player for MKV, AVI, WMV, VOB, DivX, Xvid
**Bundle ID:** com.personasoftware.flexplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=451024857">451024857</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flex-player-video-player-for/id451024857?mt=8&uo=4">https://itunes.apple.com/us/app/flex-player-video-player-for/id451024857?mt=8&uo=4</a>
**App Version:** 3.0.6
**Seller:** Persona Software, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/persona-software-llc/id335036890?uo=4>© Persona Software, LLC</a>
**Supported Devices:** iPhone5, iPadFourthGen4G, iPhone5c, iPhone4, iPhone6Plus, iPadThirdGen4G, iPadFourthGen, iPad2Wifi, iPadThirdGen, iPadMini4G, iPad23G, iPhone5s, iPhone4S, iPadMini, iPodTouchFifthGen, iPhone6
**Original Artwork:**
<img src="http://a1292.phobos.apple.com/us/r30/Purple/v4/75/be/dd/75bedd3e-157f-e726-d63c-c814dfc59a99/mzl.tkwckiiw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6073890/953931bc-ad69-11e4-8bbc-5092f8982d82.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6073890/953931bc-ad69-11e4-8bbc-5092f8982d82.png)
https://cloud.githubusercontent.com/assets/10394552/6073890/953931bc-ad69-11e4-8bbc-5092f8982d82.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6073887/8ecfb36e-ad69-11e4-9a1d-41f38f3ced65.png

**Comment by PolarisBeaver** [comment]
By the way I am aware the glyph does not touch the edges. This is on purpose, as the icon would be out of proportion otherwise, way too large. I ensured it is to scale based on its companion app, media:connect

**Comment by MagnaMike** [comment]
@PolarisBeaver Sounds good. :+1: The icons don't always have to fill the entire area.
