### ISSUE TITLE
Super Recorder

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5153]
**App Name:** Super Recorder
 **Bundle ID:** org.hacx.superrecorder
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 ![icon-72 2x](https://cloud.githubusercontent.com/assets/10394552/6080691/7d0b3d4c-adc8-11e4-98e9-7fda55afab1c.png)
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6080728/c396263c-adc8-11e4-8476-84526e6ae37f.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6080728/c396263c-adc8-11e4-8476-84526e6ae37f.png)
https://cloud.githubusercontent.com/assets/10394552/6080728/c396263c-adc8-11e4-8476-84526e6ae37f.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6080723/ba25550a-adc8-11e4-951e-ddf2d7ee39c0.png

**Comment by dreamnet** [comment]
@PolarisBeaver :+1:
