### ISSUE TITLE
Chrome D+

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5154]
**App Name:** Chrome D+
**Bundle ID:** com.ouraigua.chromedownloaderplus
**iTunes ID:** none (Cydia app)
**Original Artwork:**
![](https://cloud.githubusercontent.com/assets/10394552/6080957/797fd23a-adca-11e4-9574-bc01df66f1ea.png)
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6080968/8b9e5914-adca-11e4-84eb-032ae94d7ff0.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6080968/8b9e5914-adca-11e4-84eb-032ae94d7ff0.png)
https://cloud.githubusercontent.com/assets/10394552/6080968/8b9e5914-adca-11e4-84eb-032ae94d7ff0.png
Source File: https://cloud.githubusercontent.com/assets/10394552/6080961/84ffecd0-adca-11e4-84f1-9ace762193eb.png

**Comment by dreamnet** [comment]
@PolarisBeaver Jup! :+1:
