### ISSUE TITLE
TWC TV

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5158]
**App Name:** TWC TV
**Bundle ID:** com.timewarnercable.simulcast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=420455839">420455839</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/twc-tv/id420455839?mt=8&uo=4">https://itunes.apple.com/us/app/twc-tv/id420455839?mt=8&uo=4</a>
**App Version:** 3.7.1
**Seller:** Time Warner Cable Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/time-warner-cable/id396670004?uo=4>© Time Warner Cable</a>
**Supported Devices:** iPhone4S, iPadThirdGen4G, iPadFourthGen4G, iPhone5s, iPhone6, iPhone5c, iPadFourthGen, iPhone6Plus, iPhone4, iPadMini, iPhone5, iPadMini4G, iPad23G, iPadThirdGen, iPad2Wifi, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a722.phobos.apple.com/us/r30/Purple3/v4/66/6f/38/666f389d-7e10-531f-387c-1c7b5202742c/mzl.bcviofrp.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6095177/4131ec60-af14-11e4-8644-d51bd24e37e2.png)

**Comment by boxermansr** [comment]
I imagine the same icon can be made/used for this and My TWC since they both look the same, if it makes it any easier. Wish I wasn't so lazy that I could make my own icons, but fact is, I'm lazy, LOL.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6095177/4131ec60-af14-11e4-8644-d51bd24e37e2.png)
https://cloud.githubusercontent.com/assets/3090247/6095177/4131ec60-af14-11e4-8644-d51bd24e37e2.png
---

Source:
https://cloud.githubusercontent.com/assets/3090247/6095179/5714ddc6-af14-11e4-9d7c-25d3f1f301f6.png

**Comment by ivanov007** [comment]
@boxermansr sure it can be user for both

**Comment by boxermansr** [comment]
@ivanov007 sweet, thanks!
