### ISSUE TITLE
My TWC™

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5159]
**App Name:** My TWC™
**Bundle ID:** com.timewarnercable.mytwc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498008691">498008691</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-twc/id498008691?mt=8&uo=4">https://itunes.apple.com/us/app/my-twc/id498008691?mt=8&uo=4</a>
**App Version:** 5.4.25
**Seller:** Time Warner Cable Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/time-warner-cable/id396670004?uo=4>© Time Warner Cable</a>
**Supported Devices:** iPhone6, iPadMini, iPhone5s, iPadFourthGen, iPadThirdGen, iPhone6Plus, iPhone5, iPadFourthGen4G, iPhone4, iPodTouchFifthGen, iPad23G, iPad2Wifi, iPadMini4G, iPhone4S, iPadThirdGen4G, iPhone5c
**Original Artwork:**
<img src="http://a1660.phobos.apple.com/us/r30/Purple3/v4/3f/03/ee/3f03eed4-8d36-9e5a-b77b-88f9d3db6fcf/mzl.jsusehev.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6095177/4131ec60-af14-11e4-8644-d51bd24e37e2.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6095177/4131ec60-af14-11e4-8644-d51bd24e37e2.png)
https://cloud.githubusercontent.com/assets/3090247/6095177/4131ec60-af14-11e4-8644-d51bd24e37e2.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/6095179/5714ddc6-af14-11e4-9d7c-25d3f1f301f6.png

**Comment by boxermansr** [comment]
@ivanov007 Thanks much appreciated.

**Comment by MagnaMike** [comment]
@ivanov007 You forgot to add it to the original request :wink:
