### ISSUE TITLE
StupidFox: Add Fox and Animal Friends to Your Photos!

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5167]
**App Name:** StupidFox: Add Fox and Animal Friends to Your Photos!
**Bundle ID:** com.brettwhartoninc.stupidFox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=940570426">940570426</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stupidfox-add-fox-animal-friends/id940570426?mt=8&uo=4">https://itunes.apple.com/us/app/stupidfox-add-fox-animal-friends/id940570426?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Brett Wharton Animation, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/brett-wharton-animation-llc/id904529188?uo=4>© Brett Wharton Animation, LLC</a>
**Supported Devices:** iPadThirdGen, iPhone4S, iPhone6Plus, iPhone5s, iPad2Wifi, iPhone6, iPhone5c, iPadMini4G, iPadMini, iPad23G, iPhone5, iPadFourthGen4G, iPhone4, iPadFourthGen, iPadThirdGen4G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a1843.phobos.apple.com/us/r30/Purple3/v4/b5/64/0f/b5640fd7-2517-d3eb-ede9-5ed81fb4ae08/mzl.tczyeyua.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6119887/e2e45d70-b09c-11e4-890c-b8da1d266c33.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6119285/96d0d466-b07b-11e4-95cd-af8d7f62261b.png)
https://cloud.githubusercontent.com/assets/10394552/6119285/96d0d466-b07b-11e4-95cd-af8d7f62261b.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6119283/8eb0daf6-b07b-11e4-932f-c33ee3f90939.png

**Comment by PolarisBeaver** [comment]
I wish there was a better way to handle the two colors of fur.

**Comment by Trubbel** [comment]
I think that is as good as it gets!

**Comment by PolarisBeaver** [comment]
I think you're right, I'm satisfied with it :)

**Comment by MagnaMike** [comment]
Just throwing an alternate into the mix.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6119733/c83a0f12-b09a-11e4-9859-11fb51ace9d8.png)
https://cloud.githubusercontent.com/assets/2236254/6119733/c83a0f12-b09a-11e4-9859-11fb51ace9d8.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6119740/f1b36f0a-b09a-11e4-9e19-48e456b4bd99.png

**Comment by PolarisBeaver** [comment]
Oh man I really like your alternate one, let's go with that!

**Comment by MagnaMike** [comment]
@PolarisBeaver Okay! :+1:
