### ISSUE TITLE
Recreation.gov Camping - Find available campsites

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5168]
**App Name:** Recreation.gov Camping - Find available campsites
**Bundle ID:** com.active.recgovcamp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490668237">490668237</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/recreation.gov-camping-find/id490668237?mt=8&uo=4">https://itunes.apple.com/us/app/recreation.gov-camping-find/id490668237?mt=8&uo=4</a>
**App Version:** 1.6.3
**Seller:** Active Network, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/active-network-llc/id885139029?uo=4>© Active Network, LLC</a>
**Supported Devices:** iPad23G, iPhone5c, iPad2Wifi, iPhone6Plus, iPadMini, iPadMini4G, iPhone6, iPhone5s, iPhone5, iPhone4, iPadFourthGen, iPadThirdGen4G, iPodTouchFifthGen, iPadFourthGen4G, iPadThirdGen, iPhone4S
**Original Artwork:**
<img src="http://a1877.phobos.apple.com/us/r30/Purple6/v4/96/04/4c/96044c62-34e9-9158-e311-bc574c45cf11/mzl.oeslfxzz.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6121624/ce4610e4-b09b-11e4-953e-d1619d984624.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6120364/d7a8934e-b089-11e4-8608-d25ebb5405fe.png)
https://cloud.githubusercontent.com/assets/10394552/6120364/d7a8934e-b089-11e4-8608-d25ebb5405fe.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6120360/d1774934-b089-11e4-8c7d-d4a3d1f506f4.png

**Comment by PolarisBeaver** [comment]
Also I save every icon's vector, if alterations are recommended (such as alt versions), it might save a lot of trouble :)

**Comment by MagnaMike** [comment]
@PolarisBeaver Would be nice to have the mountains in there. Can you try seeing what if would look like with the mountains in and the path cut out from the mountains (transparent)?

**Comment by PolarisBeaver** [comment]
Something like this perhaps?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6121624/ce4610e4-b09b-11e4-953e-d1619d984624.png)
https://cloud.githubusercontent.com/assets/10394552/6121624/ce4610e4-b09b-11e4-953e-d1619d984624.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6121630/ee033cfe-b09b-11e4-8d85-e410590e9e53.png

**Comment by MagnaMike** [comment]
@PolarisBeaver Exactly. :ok_hand:
