### ISSUE TITLE
Carousel by Dropbox

### ISSUE THREAD

**Issue by sughero** [glasklart/hd#5169]
**App Name:** Carousel by Dropbox
**Bundle ID:** com.getdropbox.Carousel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=825931374">825931374</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/carousel-by-dropbox/id825931374?mt=8&uo=4">https://itunes.apple.com/us/app/carousel-by-dropbox/id825931374?mt=8&uo=4</a>
**App Version:** 1.8.1
**Seller:** Dropbox, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dropbox/id327630333?uo=4>© Dropbox</a>
**Supported Devices:** iPadFourthGen4G, iPhone4S, iPadFourthGen, iPodTouchFifthGen, iPadMini, iPhone6Plus, iPhone6, iPadThirdGen, iPad2Wifi, iPhone4, iPadThirdGen4G, iPhone5c, iPhone5s, iPhone5, iPadMini4G, iPad23G
**Original Artwork:**
<img src="http://a70.phobos.apple.com/us/r30/Purple3/v4/c9/bc/f3/c9bcf309-f9e4-c431-83ca-23e1c958d5e5/mzl.ondslkgs.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6137664/ac61ecca-b148-11e4-8678-256a2cdab99d.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6137664/ac61ecca-b148-11e4-8678-256a2cdab99d.png)
https://cloud.githubusercontent.com/assets/2236254/6137664/ac61ecca-b148-11e4-8678-256a2cdab99d.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6137662/a968e316-b148-11e4-83f7-3025678a07a0.png
