### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5170]
**App Name:** Shortcuts
**Bundle ID:** is.workflow.my.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=915249334">915249334</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/shortcuts/id915249334?uo=4">https://apps.apple.com/us/app/shortcuts/id915249334?uo=4</a>
**App Version:** 2.2.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/49/3b/9e/493b9e75-ebd7-f1b3-0d19-18cf5ba02587/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71803063-09585900-3060-11ea-9d55-c49de6419bc8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6194679/a80b7b70-b3c6-11e4-9a0e-cba9bc0549ea.png)
https://cloud.githubusercontent.com/assets/2068130/6194679/a80b7b70-b3c6-11e4-9a0e-cba9bc0549ea.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6194688/b6b5115e-b3c6-11e4-842c-3be5122a2d8c.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Shortcuts
**Bundle ID:** is.workflow.my.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=915249334">915249334</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shortcuts/id915249334?mt=8&uo=4">https://itunes.apple.com/us/app/shortcuts/id915249334?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/99/2c/b1/992cb18d-0069-e553-b828-9c7a2228d7e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49694601-972bf100-fb8d-11e8-8def-c6d29964f31f.png)
https://user-images.githubusercontent.com/2068130/49694601-972bf100-fb8d-11e8-8def-c6d29964f31f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/49694604-a874fd80-fb8d-11e8-8fa1-e46a051a0e5d.png

**Comment by 2Qt2beStr8** [comment]
Bundle ID have changed

**Comment by dreamnet** [comment]
The bundle ID has not changed. It seems, that there two bundle ID's: `is.workflow.my.app` for iOS12 and lower and `com.apple.shortcuts` for iOS13. I'm adding both of them.

**Comment by dreamnet** [comment]
Icon update:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/71803063-09585900-3060-11ea-9d55-c49de6419bc8.png)
https://user-images.githubusercontent.com/2068130/71803063-09585900-3060-11ea-9d55-c49de6419bc8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/71803096-1e34ec80-3060-11ea-8b29-62b953803793.png
