### ISSUE TITLE
Spectral Souls RotEE

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5177]
**App Name:** Spectral Souls RotEE
**Bundle ID:** com.hyperdevbox.spectralsouls
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507382406">507382406</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spectral-souls-rotee/id507382406?mt=8&uo=4">https://itunes.apple.com/us/app/spectral-souls-rotee/id507382406?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** Hyperdevbox Japan, Yugen Kaisha
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hyperdevbox-japan/id304020888?uo=4>© HyperDevbox Japan</a>
**Supported Devices:** iPad23G, iPad3G, iPadThirdGen, iPad2Wifi, iPodTouchThirdGen, iPadFourthGen, iPhone5c, iPhone4S, iPhone5s, iPodTouchFifthGen, iPhone5, iPhone-3GS, iPadFourthGen4G, iPadMini, iPhone6, iPhone4, iPadMini4G, iPhone6Plus, iPodTouchFourthGen, iPadThirdGen4G, iPadWifi
**Original Artwork:**
<img src="http://a1973.phobos.apple.com/us/r30/Purple1/v4/b1/be/d4/b1bed4e1-e847-d9e3-37b3-a1549daf21fe/pr_source.png?downloadKey=1423944625_dd1f4b3383d70ae7e68190ed7e6930d1" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6235522/16eebd80-b6b1-11e4-9478-b774166197f8.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6235522/16eebd80-b6b1-11e4-9478-b774166197f8.png)
https://cloud.githubusercontent.com/assets/10950389/6235522/16eebd80-b6b1-11e4-9478-b774166197f8.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6235542/39c79e6c-b6b1-11e4-933e-29c0f83dbda5.png

**Comment by dreamnet** [comment]
@zmathiasz Great! :+1:
