### ISSUE TITLE
Space Kitty Puzzle — family logical adventure

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5178]
**App Name:** Space Kitty Puzzle — family logical adventure
**Bundle ID:** com.slylamb.spacekittypuzzle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937242587">937242587</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/space-kitty-puzzle-family/id937242587?mt=8&uo=4">https://itunes.apple.com/us/app/space-kitty-puzzle-family/id937242587?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** Alexey Perezhogin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/alexey-perezhogin/id937242586?uo=4>© Alexey Perezhogin</a>
**Supported Devices:** iPhone5s, iPadMini, iPadThirdGen, iPadMini4G, iPodTouchFifthGen, iPadFourthGen4G, iPhone4S, iPhone5c, iPhone6, iPad2Wifi, iPadThirdGen4G, iPhone5, iPad23G, iPadFourthGen, iPhone6Plus
**Original Artwork:**
<img src="http://a877.phobos.apple.com/us/r30/Purple3/v4/0d/e7/13/0de71317-da36-f166-f0cd-e5a39cb788a7/mzl.gpdufjav.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6201866/861051f0-b487-11e4-885e-8295f8d31f2d.png)

**Comment by ivanov007** [comment]
the icon in iTunes is the xmas icon, couldn't find the "normal" icon on a decent size so i'll wait until itunes changes the icon, here's an example of the regular icon:
![icon175x175](https://cloud.githubusercontent.com/assets/3090247/6201648/504dcd42-b47b-11e4-9f83-b103e788e869.jpg)

**Comment by MagnaMike** [comment]
Here:
![1024](https://cloud.githubusercontent.com/assets/2236254/6201738/e2caad36-b488-11e4-88a5-d2d391261995.jpg)

**Comment by ivanov007** [comment]
@MagnaMike wow, were did you get it from?

**Comment by MagnaMike** [comment]
![capture](https://cloud.githubusercontent.com/assets/2236254/6201807/9b46f880-b48c-11e4-86c0-f8c794f7431c.PNG)
![capture 2](https://cloud.githubusercontent.com/assets/2236254/6201808/9b48cfa2-b48c-11e4-80ee-3ed0fdefaea9.PNG)
![caprue 3](https://cloud.githubusercontent.com/assets/2236254/6201809/9b4b8058-b48c-11e4-90cf-b8ff8d6bd07d.PNG)

**Comment by ivanov007** [comment]
:open_mouth: I didn't knew that one, thanks

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6201866/861051f0-b487-11e4-885e-8295f8d31f2d.png)
https://cloud.githubusercontent.com/assets/3090247/6201866/861051f0-b487-11e4-885e-8295f8d31f2d.png
---

Source:
https://cloud.githubusercontent.com/assets/3090247/6201867/8612e2f8-b487-11e4-8c0a-623962b2bad7.png

**Comment by MagnaMike** [comment]
No problem! Icon looks good. :+1:
