### ISSUE TITLE
Runtastic Heart Rate Monitor, Heart Beat & Pulse Tracker PRO

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#5180]
**App Name:** Runtastic Heart Rate Monitor, Heart Beat & Pulse Tracker PRO
**Bundle ID:** com.runtastic.iphone.heartrate.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586956623">586956623</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-heart-rate-monitor/id586956623?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-heart-rate-monitor/id586956623?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/d0/2e/67/d02e6774-5755-350a-5179-9993daa53b93/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100886/b1f6b21a-d541-11e5-85f8-9203e5d2f6b4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6202461/1d06f81a-b4ed-11e4-95d7-57b38dccc166.png)
https://cloud.githubusercontent.com/assets/2068130/6202461/1d06f81a-b4ed-11e4-95d7-57b38dccc166.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6202463/2b7b3212-b4ed-11e4-8bff-cd7a9180abc1.png

**Comment by Trubbel** [comment]
Small update,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13037229/6953840a-d37c-11e5-8fb6-8bad76eab0bc.png)
https://cloud.githubusercontent.com/assets/10730122/13037229/6953840a-d37c-11e5-8fb6-8bad76eab0bc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13037230/69543b52-d37c-11e5-8146-841195c898f0.png

**Comment by dreamnet** [comment]
@Trubbel If we use your icon above, we also have to make the icon for #5181 smaller. So I suggest to use the icon from #5181 for this one and just add the "PRO" to the bottom right corner.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100886/b1f6b21a-d541-11e5-85f8-9203e5d2f6b4.png)
https://cloud.githubusercontent.com/assets/10730122/13100886/b1f6b21a-d541-11e5-85f8-9203e5d2f6b4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100887/b20ff022-d541-11e5-8e2a-637250c6491b.png

**Comment by dreamnet** [comment]
@Trubbel Jup! :+1:
