### ISSUE TITLE
gpSPhone

### ISSUE THREAD

**Issue by kieman** [glasklart/hd#5193]
**App Name:** gpSPhone
 **Bundle ID:**  com.zodttd.gpsphone
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="http://4.bp.blogspot.com/-Or0dQb2gy1g/UuZkQZgqRjI/AAAAAAAABGs/jP2sUYg8bSE/s1600/bsj.png" width="150" height="150" />
 **Accepted Artwork:**
 \#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by kieman** [comment]
but pls without the font "my boy" pls :)

**Comment by MagnaMike** [comment]
I believe this is the same app as in issue #597. The app icon should be themed, please use that other issue if you are having any problems. Thanks!
