### ISSUE TITLE
Line Rider iRide™

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5196]
**App Name:** Line Rider iRide™
**Bundle ID:** com.inXileEntertainment.LineRider
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=290807369">290807369</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/line-rider-iride/id290807369?mt=8&uo=4">https://itunes.apple.com/us/app/line-rider-iride/id290807369?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** inXile Entertainment
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/inxile-entertainment/id290807372?uo=4>© inXile Entertainment</a>
**Supported Devices:** iPadThirdGen4G, iPodTouchFifthGen, iPodTouchFourthGen, iPhone6, iPhone6Plus, iPhone4S, iPhone5c, iPadMini4G, iPadFourthGen4G, iPadThirdGen, iPhone5s, iPadMini, iPadFourthGen, iPhone5, iPad2Wifi, iPhone4, iPhone-3GS, iPad23G
**Original Artwork:**
<img src="http://a417.phobos.apple.com/us/r30/Purple3/v4/90/f5/a3/90f5a325-ab67-cd1c-5cb9-01030e3a0cd2/pr_source.png?downloadKey=1424036203_0257d23b044c5fbb299c4745ff6eb054" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6258237/efb97838-b794-11e4-8bda-12495479751d.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6258237/efb97838-b794-11e4-8bda-12495479751d.png)
https://cloud.githubusercontent.com/assets/2236254/6258237/efb97838-b794-11e4-8bda-12495479751d.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6258238/efb987ec-b794-11e4-9b67-05ea835394ba.png

**Comment by dreamnet** [comment]
@MagnaMike Yes! :+1:
