### ISSUE TITLE
 UPC Phone App

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5198]
**App Name:** UPC Phone App
**Bundle ID:** com.upc.phone.multicountry
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=794447416">794447416</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/nl/app/upc-phone-app/id794447416?mt=8&uo=4">https://itunes.apple.com/nl/app/upc-phone-app/id794447416?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** UPC Broadband Holding BV
**Developer:** <a target="_blank" href=https://itunes.apple.com/nl/artist/upc-broadband-holding-services/id403998620?uo=4>© UPC Broadband Holding Services B.V.</a>
**Supported Devices:** iPodTouchThirdGen, iPadWifi, iPodTouchFourthGen, iPadMini, iPhone4, iPhone5c, iPhone5s, iPadThirdGen4G, iPadMini4G, iPodTouchFifthGen, iPadThirdGen, iPhone-3GS, iPad3G, iPhone6Plus, iPad23G, iPhone4S, iPhone5, iPadFourthGen4G, iPadFourthGen, iPad2Wifi, iPhone6
**Original Artwork:**
<img src="http://a1102.phobos.apple.com/us/r30/Purple3/v4/50/96/a0/5096a0c5-1a4a-b639-1ab1-ba6e167eaf76/mzl.swrlmjbq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6255896/f0e4d2c4-b7b3-11e4-8d4e-3f02e532d8d7.png)

**Comment by powerfull** [comment]
[DUPLICATE of #5198]
**App Name:** UPC Phone App
**Bundle ID:** com.upc.phone.multicountry
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=794447416">794447416</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/nl/app/upc-phone-app/id794447416?mt=8&uo=4">https://itunes.apple.com/nl/app/upc-phone-app/id794447416?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** UPC Broadband Holding BV
**Developer:** <a target="_blank" href=https://itunes.apple.com/nl/artist/upc-broadband-holding-services/id403998620?uo=4>© UPC Broadband Holding Services B.V.</a>
**Supported Devices:** iPhone4, iPadWifi, iPodTouchFourthGen, iPad2Wifi, iPadMini4G, iPhone4S, iPadThirdGen4G, iPodTouchFifthGen, iPad3G, iPhone6, iPhone5, iPhone6Plus, iPadFourthGen4G, iPhone5s, iPadThirdGen, iPhone-3GS, iPadFourthGen, iPhone5c, iPad23G, iPodTouchThirdGen, iPadMini
**Original Artwork:**
<img src="http://a1102.phobos.apple.com/us/r30/Purple3/v4/50/96/a0/5096a0c5-1a4a-b639-1ab1-ba6e167eaf76/mzl.swrlmjbq.png" width="150" height="150" />
**Accepted Artwork:**

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6255896/f0e4d2c4-b7b3-11e4-8d4e-3f02e532d8d7.png)
https://cloud.githubusercontent.com/assets/2068130/6255896/f0e4d2c4-b7b3-11e4-8d4e-3f02e532d8d7.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6255901/028fc588-b7b4-11e4-96a3-a983ff933fc9.png
