### ISSUE TITLE
Measure Map

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5199]
**App Name:** Measure Map
**Bundle ID:** net.victoralonso.measuremap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417622293">417622293</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/measure-map/id417622293?mt=8&uo=4">https://itunes.apple.com/us/app/measure-map/id417622293?mt=8&uo=4</a>
**App Version:** 5.4
**Seller:** Global DPI, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/global-dpi-llc/id407049426?uo=4>© Global DPI, LLC</a>
**Supported Devices:** iPadThirdGen, iPhone6, iPhone-3GS, iPad3G, iPadWifi, iPadFourthGen, iPhone4S, iPad2Wifi, iPadFourthGen4G, iPadMini4G, iPodTouchThirdGen, iPhone6Plus, iPodTouchFourthGen, iPadThirdGen4G, iPhone5s, iPhone5c, iPhone5, iPad23G, iPhone4, iPadMini, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a1724.phobos.apple.com/us/r30/Purple1/v4/6b/9b/de/6b9bde9c-f991-ef13-bd74-fcabeaf77a10/mzl.tvwmfvnz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6320793/227c9a10-bae8-11e4-9b7b-f5852c29fdc2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6320793/227c9a10-bae8-11e4-9b7b-f5852c29fdc2.png)
https://cloud.githubusercontent.com/assets/2068130/6320793/227c9a10-bae8-11e4-9b7b-f5852c29fdc2.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6320794/305ee408-bae8-11e4-9b24-47036714ad99.png
