### ISSUE TITLE
Hållplatsen

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5200]
**App Name:** Hållplatsen
**Bundle ID:** info.kallewallin.hallplatsen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=575356150">575356150</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hallplatsen/id575356150?mt=8&uo=4">https://itunes.apple.com/us/app/hallplatsen/id575356150?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Kalle Wallin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kalle-wallin/id575356153?uo=4>© Kalle Wallin</a>
**Supported Devices:** iPad23G, iPadMini4G, iPadThirdGen4G, iPad3G, iPadFourthGen, iPhone6, iPodTouchFifthGen, iPhone-3GS, iPhone4, iPhone6Plus, iPhone5, iPad2Wifi, iPadFourthGen4G, iPodTouchFourthGen, iPadMini, iPhone5c, iPodTouchThirdGen, iPadWifi, iPhone5s, iPadThirdGen, iPhone4S
**Original Artwork:**
<img src="http://a1975.phobos.apple.com/us/r30/Purple/v4/cd/f3/91/cdf391da-63f5-2cbd-aa3d-77c92a6e6997/mzl.rwtchtlk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6261623/f8bb9ae2-b7b7-11e4-8da0-fdc11638188c.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6260869/9bfb1c46-b7b3-11e4-820b-b02193b4c352.png)
https://cloud.githubusercontent.com/assets/10950389/6260869/9bfb1c46-b7b3-11e4-820b-b02193b4c352.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6260873/abd2b016-b7b3-11e4-8609-5f2ea2a94071.png

**Comment by ivanov007** [comment]
or something like this?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6261623/f8bb9ae2-b7b7-11e4-8da0-fdc11638188c.png)
https://cloud.githubusercontent.com/assets/3090247/6261623/f8bb9ae2-b7b7-11e4-8da0-fdc11638188c.png

---
Source:
![info kallewallin hallplatsen](https://cloud.githubusercontent.com/assets/3090247/6261624/f8bda17a-b7b7-11e4-9c06-cb0fc171a991.png)

**Comment by zmathiasz** [comment]
Yeah.  I like yours better.  :+1:

**Comment by dreamnet** [comment]
Then @ivanov007 's.
