### ISSUE TITLE
Nästa vagn

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5201]
**App Name:** Nästa vagn
**Bundle ID:** se.oops.NastaVagn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448300093">448300093</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nasta-vagn/id448300093?mt=8&uo=4">https://itunes.apple.com/us/app/nasta-vagn/id448300093?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Oops AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/oops-ab/id321481590?uo=4>© Oops AB</a>
**Supported Devices:** iPadFourthGen, iPodTouchFifthGen, iPhone5s, iPad2Wifi, iPhone4, iPadThirdGen, iPadThirdGen4G, iPadFourthGen4G, iPadMini4G, iPhone5, iPadMini, iPad23G, iPhone6, iPhone4S, iPhone5c, iPhone6Plus
**Original Artwork:**
<img src="http://a1651.phobos.apple.com/us/r30/Purple3/v4/a8/00/0f/a8000ff9-bada-c5ab-a310-365aa7f97501/mzl.hwjehyqf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6218266/d866e176-b61c-11e4-89ce-d1d8f0c951f3.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6218047/72ccfac8-b61a-11e4-90e1-7ec6b61b5262.png)
https://cloud.githubusercontent.com/assets/10515074/6218047/72ccfac8-b61a-11e4-90e1-7ec6b61b5262.png
Source
https://cloud.githubusercontent.com/assets/10515074/6218053/8aee4f58-b61a-11e4-9ca2-fb82b9ea8d00.png

**Comment by dreamnet** [comment]
Hm, I think it would be better to make this bigger...?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6218266/d866e176-b61c-11e4-89ce-d1d8f0c951f3.png)
https://cloud.githubusercontent.com/assets/2068130/6218266/d866e176-b61c-11e4-89ce-d1d8f0c951f3.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6218272/e73cb130-b61c-11e4-8c74-2edb8361520f.png

**Comment by andreolidavide** [comment]
@dreamnet yeah, that's good 👍

**Comment by MagnaMike** [comment]
Taking @dreamnet's then
