### ISSUE TITLE
Sleep Cycle power nap

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5202]
**App Name:** Sleep Cycle power nap
**Bundle ID:** com.lexwarelabs.powernap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=813493308">813493308</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sleep-cycle-power-nap/id813493308?mt=8&uo=4">https://itunes.apple.com/us/app/sleep-cycle-power-nap/id813493308?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Northcube AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/northcube-ab/id320606220?uo=4>© Northcube AB</a>
**Supported Devices:** iPodTouchFourthGen, iPhone6, iPhone6Plus, iPhone5c, iPhone4S, iPhone5, iPad2Wifi, iPadMini4G, iPadFourthGen, iPodTouchFifthGen, iPadThirdGen, iPhone-3GS, iPhone4, iPad23G, iPadThirdGen4G, iPadMini, iPadFourthGen4G, iPhone5s
**Original Artwork:**
<img src="http://a619.phobos.apple.com/us/r30/Purple5/v4/10/c3/b9/10c3b985-bf25-f82b-1c9f-d64028ae0ee4/mzl.rgkhrgpd.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6216280/c31a1072-b608-11e4-97c0-62a292a90a57.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6216280/c31a1072-b608-11e4-97c0-62a292a90a57.png)
https://cloud.githubusercontent.com/assets/2068130/6216280/c31a1072-b608-11e4-97c0-62a292a90a57.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6216281/d0732402-b608-11e4-9d1f-06ce819a3eb7.png
