### ISSUE TITLE
Rhythm Sight Reading Trainer

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5203]
**App Name:** Rhythm Sight Reading Trainer
**Bundle ID:** ReadRhythm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=396302174">396302174</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rhythm-sight-reading-trainer/id396302174?mt=8&uo=4">https://itunes.apple.com/us/app/rhythm-sight-reading-trainer/id396302174?mt=8&uo=4</a>
**App Version:** 8.2
**Seller:** Rolf Steenge
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/rolfs-apps/id376191908?uo=4>© Rolfs Apps</a>
**Supported Devices:** iPadWifi, iPhone5c, iPad3G, iPhone-3GS, iPad2Wifi, iPadThirdGen4G, iPad23G, iPhone5, iPodTouchFourthGen, iPhone6Plus, iPhone4S, iPadMini4G, iPadMini, iPhone5s, iPodTouchThirdGen, iPhone6, iPadFourthGen4G, iPodTouchFifthGen, iPadFourthGen, iPhone4, iPadThirdGen
**Original Artwork:**
<img src="http://a669.phobos.apple.com/us/r30/Purple5/v4/b7/1a/f0/b71af08d-9574-9929-3209-0114cd7624bd/mzl.kolchryv.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6260798/0a788ec6-b7b2-11e4-985a-6a83b24d2256.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6260798/0a788ec6-b7b2-11e4-985a-6a83b24d2256.png)
https://cloud.githubusercontent.com/assets/10950389/6260798/0a788ec6-b7b2-11e4-985a-6a83b24d2256.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6260800/1872359a-b7b2-11e4-9bcc-78f3c1c806bb.png

**Comment by ivanov007** [comment]
@zmathiasz nice :+1:
