### ISSUE TITLE
Quiztones

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5204]
**App Name:** Quiztones
**Bundle ID:** com.audiofile.quiztones
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=436707254">436707254</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quiztones/id436707254?mt=8&uo=4">https://itunes.apple.com/us/app/quiztones/id436707254?mt=8&uo=4</a>
**App Version:** 1.7.3
**Seller:** Audiofile Engineering, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/audiofile-engineering-llc/id309378687?uo=4>© Audiofile Engineering, LLC</a>
**Supported Devices:** iPodTouchThirdGen, iPhone4S, iPadWifi, iPadMini4G, iPhone5, iPadMini, iPadFourthGen4G, iPad23G, iPad2Wifi, iPad3G, iPadThirdGen4G, iPhone6Plus, iPadThirdGen, iPhone4, iPadFourthGen, iPhone5c, iPhone5s, iPhone-3GS, iPodTouchFifthGen, iPodTouchFourthGen, iPhone6
**Original Artwork:**
<img src="http://a1402.phobos.apple.com/us/r30/Purple2/v4/b3/4d/43/b34d431b-9bf3-fb06-7dee-7e205979de6b/mzl.ijoybdbl.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6217908/296e254c-b619-11e4-80e6-1c31e139e613.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6217908/296e254c-b619-11e4-80e6-1c31e139e613.png)
https://cloud.githubusercontent.com/assets/10515074/6217908/296e254c-b619-11e4-80e6-1c31e139e613.png
Source
https://cloud.githubusercontent.com/assets/10515074/6217920/49196ece-b619-11e4-8c1a-c5f1efb5611f.png

**Comment by dreamnet** [comment]
@andreolidavide Jup! :+1:
