### ISSUE TITLE
Sweet MIDI Player

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5205]
**App Name:** Sweet MIDI Player
**Bundle ID:** com.ronimusic.SMPiOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=477678002">477678002</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sweet-midi-player/id477678002?mt=8&uo=4">https://itunes.apple.com/us/app/sweet-midi-player/id477678002?mt=8&uo=4</a>
**App Version:** 3.4.2
**Seller:** Roni Music
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/roni-music/id308998721?uo=4>© Roni Music</a>
**Supported Devices:** iPodTouchFifthGen, iPodTouchThirdGen, iPad2Wifi, iPadWifi, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPhone6, iPhone5s, iPhone5c, iPadMini, iPadThirdGen, iPodTouchFourthGen, iPhone6Plus, iPadMini4G, iPhone4, iPhone4S, iPhone5, iPad23G, iPad3G, iPhone-3GS
**Original Artwork:**
<img src="http://a9.phobos.apple.com/us/r30/Purple3/v4/09/df/fa/09dffabc-4618-c44a-ce1c-320d0b0863bb/mzl.gobslhwh.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6336271/a0ad07a8-bba1-11e4-8555-90f1ac908e7a.png)

**Comment by zmathiasz** [comment]
I changed the icon because of poor quality.  It would have been very choppy.  Yes, no?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6321343/e2919fd8-bac7-11e4-81ea-8d63fbced4bc.png)
https://cloud.githubusercontent.com/assets/10950389/6321343/e2919fd8-bac7-11e4-81ea-8d63fbced4bc.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6321345/fa4cc22e-bac7-11e4-97e8-89479e3ba128.png

**Comment by dreamnet** [comment]
Yeah, very poor quality... I did a redraw:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6336271/a0ad07a8-bba1-11e4-8555-90f1ac908e7a.png)
https://cloud.githubusercontent.com/assets/2068130/6336271/a0ad07a8-bba1-11e4-8555-90f1ac908e7a.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6336279/ad2d60d6-bba1-11e4-8652-0783c69718d8.png

**Comment by zmathiasz** [comment]
Yes. Most definitely yours. Original is always better.
