### ISSUE TITLE
Lost Friends for Instagram, Twitter, and Facebook Free

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5206]
**App Name:** Lost Friends for Instagram, Twitter, and Facebook Free
**Bundle ID:** com.michaelorcutt.lostfriendsfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570884529">570884529</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lost-friends-for-instagram/id570884529?mt=8&uo=4">https://itunes.apple.com/us/app/lost-friends-for-instagram/id570884529?mt=8&uo=4</a>
**App Version:** 1.41
**Seller:** Ubermedia, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ubermedia-inc./id396050122?uo=4>© Ubermedia, Inc.</a>
**Supported Devices:** iPadFourthGen4G, iPhone5, iPad2Wifi, iPadMini4G, iPhone6Plus, iPadMini, iPodTouchThirdGen, iPhone5c, iPadWifi, iPodTouchFourthGen, iPhone4S, iPhone4, iPhone5s, iPadFourthGen, iPhone-3GS, iPadThirdGen4G, iPad3G, iPodTouchFifthGen, iPhone6, iPadThirdGen, iPad23G
**Original Artwork:**
<img src="http://a1032.phobos.apple.com/us/r30/Purple/v4/40/6e/ae/406eae0f-7c06-674a-b4ac-9660b0d6ed55/mzl.vslcwfzg.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6218111/1c0f9f96-b61b-11e4-8ffd-79b1d8cbfde3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6218111/1c0f9f96-b61b-11e4-8ffd-79b1d8cbfde3.png)
https://cloud.githubusercontent.com/assets/2068130/6218111/1c0f9f96-b61b-11e4-8ffd-79b1d8cbfde3.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6218124/2b441820-b61b-11e4-9249-fa5a624a5cbf.png
