### ISSUE TITLE
Var är bussen?

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5207]
**App Name:** Var är bussen?
**Bundle ID:** com.vasttrafik.bussen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=821541662">821541662</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/var-ar-bussen/id821541662?mt=8&uo=4">https://itunes.apple.com/us/app/var-ar-bussen/id821541662?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Vasttrafik AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/vasttrafik-ab/id424903086?uo=4>© Västtrafik AB</a>
**Supported Devices:** iPadFourthGen4G, iPhone5s, iPad23G, iPodTouchFourthGen, iPhone4, iPad2Wifi, iPhone6Plus, iPadMini, iPadFourthGen, iPhone5, iPhone4S, iPhone5c, iPadThirdGen, iPhone-3GS, iPodTouchFifthGen, iPhone6, iPadMini4G, iPadThirdGen4G
**Original Artwork:**
<img src="http://a1227.phobos.apple.com/us/r30/Purple5/v4/0a/9a/e8/0a9ae883-00e8-a68c-dde4-05d9fbe38d2a/mzl.aeacvnpp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6216242/4d3f2630-b608-11e4-8bc0-e6a8fe5ba37b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6216242/4d3f2630-b608-11e4-8bc0-e6a8fe5ba37b.png)
https://cloud.githubusercontent.com/assets/2068130/6216242/4d3f2630-b608-11e4-8bc0-e6a8fe5ba37b.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6216247/5ae57c4e-b608-11e4-9c21-9064d38400f4.png
