### ISSUE TITLE
Zoom Zoom Player

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5208]
**App Name:** Zoom Zoom Player
**Bundle ID:** net.dotkoyi.zoomplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416311766">416311766</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zoom-zoom-player/id416311766?mt=8&uo=4">https://itunes.apple.com/us/app/zoom-zoom-player/id416311766?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Xiao Nan Shao
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kyxn/id416311769?uo=4>© kyxn</a>
**Supported Devices:** iPadThirdGen4G, iPadMini, iPhone6Plus, iPad2Wifi, iPadMini4G, iPhone5, iPhone-3GS, iPodTouchFifthGen, iPad23G, iPhone4S, iPhone5c, iPhone4, iPadFourthGen, iPhone5s, iPhone6, iPodTouchFourthGen, iPadThirdGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://a491.phobos.apple.com/us/r30/Purple/v4/62/fc/c5/62fcc5c2-55aa-75ae-3fa5-ff3700496263/mzl.zcctkion.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6277280/56136d52-b85b-11e4-9ef2-7043aed7993a.png)

**Comment by MagnaMike** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6277280/56136d52-b85b-11e4-9ef2-7043aed7993a.png)
https://cloud.githubusercontent.com/assets/2236254/6277280/56136d52-b85b-11e4-9ef2-7043aed7993a.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6277281/561606fc-b85b-11e4-9227-c78396ee692a.png

**Comment by MagnaMike** [comment]
Should be my :three: :zero: :zero: th icon. :boom: :tada:

**Comment by dreamnet** [comment]
@MagnaMike Yiiiiiiihaaaaa! :beer:
