### ISSUE TITLE
Shadowmatic

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#5209]
**App Name:** Shadowmatic
**Bundle ID:** com.triadastudio.Shadowmatic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=775888026">775888026</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shadowmatic/id775888026?mt=8&uo=4">https://itunes.apple.com/us/app/shadowmatic/id775888026?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** TRIADA Studio LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triada-studio/id775888029?uo=4>© TRIADA Studio</a>
**Supported Devices:** iPadThirdGen4G, iPodTouchFourthGen, iPhone4, iPad23G, iPad2Wifi, iPhone5, iPhone-3GS, iPhone4S, iPhone6Plus, iPadMini, iPhone5c, iPadThirdGen, iPadMini4G, iPhone6, iPodTouchFifthGen, iPadFourthGen4G, iPadFourthGen, iPhone5s
**Original Artwork:**
<img src="http://a1413.phobos.apple.com/us/r30/Purple3/v4/78/17/08/781708ca-415d-c5d1-8aa0-5032d2019809/mzl.lnkjzxyr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6217770/c0ce8578-b617-11e4-9954-0a7fd1c835ac.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6217770/c0ce8578-b617-11e4-9954-0a7fd1c835ac.png)
https://cloud.githubusercontent.com/assets/2068130/6217770/c0ce8578-b617-11e4-9954-0a7fd1c835ac.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6217776/d3a3ae94-b617-11e4-80ce-61360e30ae42.png
Doing it this way, because I think it sould be a shadow. Any thoughts?

**Comment by neeldaver** [comment]
I like it.

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6218101/0bcfede8-b61b-11e4-9b48-dd99ff25acd7.png)
https://cloud.githubusercontent.com/assets/10515074/6218101/0bcfede8-b61b-11e4-9b48-dd99ff25acd7.png
Source
https://cloud.githubusercontent.com/assets/10515074/6218109/1af1bfc2-b61b-11e4-8956-531d1e1afff5.png

**Comment by MagnaMike** [comment]
@dreamnet Yeah, lets go with it. :+1:
