### ISSUE TITLE
What Would You Choose? - 400 of the Most Difficult Have You Ever Quiz Questions

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#5210]
**App Name:** What Would You Choose? - 400 of the Most Difficult Have You Ever Quiz Questions
**Bundle ID:** com.lolriffic.choosefatefr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=316788291">316788291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/what-would-you-choose-400/id316788291?mt=8&uo=4">https://itunes.apple.com/us/app/what-would-you-choose-400/id316788291?mt=8&uo=4</a>
**App Version:** 3.8
**Seller:** Adan Vielma
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/lolriffic-stuff/id291014249?uo=4>© LOLriffic Stuff</a>
**Supported Devices:** iPhone4, iPad3G, iPadMini4G, iPad23G, iPhone5c, iPhone6Plus, iPhone4S, iPhone6, iPadMini, iPodTouchThirdGen, iPadFourthGen4G, iPhone5s, iPodTouchFifthGen, iPodTouchFourthGen, iPhone-3GS, iPadThirdGen4G, iPadFourthGen, iPhone5, iPadThirdGen, iPadWifi, iPad2Wifi
**Original Artwork:**
<img src="http://a1580.phobos.apple.com/us/r30/Purple/v4/5d/4b/70/5d4b701f-baaa-6046-efd7-48c11696d6b0/mzl.xthagrll.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6474177/f3034bee-c1fe-11e4-9186-b502badcc804.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6474177/f3034bee-c1fe-11e4-9186-b502badcc804.png)
https://cloud.githubusercontent.com/assets/2068130/6474177/f3034bee-c1fe-11e4-9186-b502badcc804.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6474146/b7b70922-c1fe-11e4-9d32-8305b8d7e5f2.png
:question:

**Comment by MagnaMike** [comment]
@dreamnet Fine with me.
