### ISSUE TITLE
Cube Runner

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#5211]
**App Name:** Cube Runner
**Bundle ID:** com.andyqua.CubeRunner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284596345">284596345</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cube-runner/id284596345?mt=8&uo=4">https://itunes.apple.com/us/app/cube-runner/id284596345?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Andy Qua
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/andy-qua/id284092693?uo=4>© Andy Qua</a>
**Supported Devices:** iPodTouchFourthGen, iPhone5s, iPadThirdGen, iPhone6Plus, iPadThirdGen4G, iPhone6, iPad2Wifi, iPhone4S, iPodTouchFifthGen, iPadFourthGen4G, iPhone4, iPadMini4G, iPad23G, iPhone5c, iPadMini, iPhone5, iPadFourthGen, iPhone-3GS
**Original Artwork:**
<img src="http://a1774.phobos.apple.com/us/r30/Purple/v4/e9/a6/b7/e9a6b7fa-2b57-62bd-9aae-2ccb6c8653ca/mzl.iiphjltj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6277732/9149a220-b891-11e4-953b-ceb4ce5454cb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6277732/9149a220-b891-11e4-953b-ceb4ce5454cb.png)
https://cloud.githubusercontent.com/assets/2068130/6277732/9149a220-b891-11e4-953b-ceb4ce5454cb.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6277735/9ecea65c-b891-11e4-95ee-cab503138129.png

**Comment by MagnaMike** [comment]
@dreamnet Looks good. :+1:
