### ISSUE TITLE
BubbleFREE

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#5212]
**App Name:** BubbleFREE
**Bundle ID:** nz.co.orsome.bubbleWrap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284945681">284945681</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bubblefree/id284945681?mt=8&uo=4">https://itunes.apple.com/us/app/bubblefree/id284945681?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Orsome Software
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/orsome/id284944382?uo=4>© Orsome</a>
**Supported Devices:** iPhone5c, iPadWifi, iPodTouchFourthGen, iPad2Wifi, iPadThirdGen4G, iPadMini4G, iPad3G, iPad23G, iPadFourthGen4G, iPhone4S, iPadThirdGen, iPhone4, iPodTouchThirdGen, iPhone5s, iPhone5, iPhone6Plus, iPadMini, iPhone-3GS, iPodTouchFifthGen, iPadFourthGen, iPhone6
**Original Artwork:**
<img src="http://a1050.phobos.apple.com/us/r30/Purple/v4/ed/08/44/ed0844f0-586d-bbd8-bd39-12f7cc46af2e/mzl.tsxpukwk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6335373/6bb6fc94-bb9b-11e4-9fdb-8e9d36ac8b1a.png)

**Comment by dreamnet** [comment]
Are these condoms? :confused: :laughing:

**Comment by MagnaMike** [comment]
@dreamnet Ha! :laughing: If I just looked at the icon I would have thought so.

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6321928/00364386-bad7-11e4-8bd4-3a19f94ab5a8.png)
https://cloud.githubusercontent.com/assets/10950389/6321928/00364386-bad7-11e4-8bd4-3a19f94ab5a8.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6321930/0e41745a-bad7-11e4-9af8-9e0d5926a26d.png

**Comment by dreamnet** [comment]
@zmathiasz Not bad, not bad... I just did a little cleanup and rounded the corners.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6335373/6bb6fc94-bb9b-11e4-9fdb-8e9d36ac8b1a.png)
https://cloud.githubusercontent.com/assets/2068130/6335373/6bb6fc94-bb9b-11e4-9fdb-8e9d36ac8b1a.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6335397/92b01f7e-bb9b-11e4-886d-19930e457f77.png

**Comment by zmathiasz** [comment]
Looks good. :)
