### ISSUE TITLE
Glow Hockey 2 FREE

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#5213]
**App Name:** Glow Hockey 2 FREE
**Bundle ID:** com.natenai.glowhockeylite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=346453382">346453382</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glow-hockey-2-free/id346453382?mt=8&uo=4">https://itunes.apple.com/us/app/glow-hockey-2-free/id346453382?mt=8&uo=4</a>
**App Version:** 2.2.9
**Seller:** Natenai Ariyatrakool
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/natenai-ariyatrakool/id323816951?uo=4>© Natenai Ariyatrakool</a>
**Supported Devices:** iPhone5s, iPadFourthGen, iPhone4, iPad3G, iPadThirdGen4G, iPhone5c, iPadThirdGen, iPad2Wifi, iPhone4S, iPhone-3GS, iPodTouchFourthGen, iPodTouchFifthGen, iPhone6Plus, iPadFourthGen4G, iPodTouchThirdGen, iPhone6, iPadMini, iPadMini4G, iPadWifi, iPhone5, iPad23G
**Original Artwork:**
<img src="http://a232.phobos.apple.com/us/r30/Purple2/v4/d6/d6/4a/d6d64ad4-b1a2-c745-45cb-ab85e0ea4184/mzl.acbekbuv.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6217570/9e8a1010-b615-11e4-9e61-6d741ca11acb.png)

**Comment by dreamnet** [comment]
Same as for #4237.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6217570/9e8a1010-b615-11e4-9e61-6d741ca11acb.png)
https://cloud.githubusercontent.com/assets/2068130/6217570/9e8a1010-b615-11e4-9e61-6d741ca11acb.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6217580/adfbfa2c-b615-11e4-98e1-40aad6db71c2.png
