### ISSUE TITLE
Fitness Trainer - Exercise & Workout Guide

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5215]
**App Name:** Fitness Trainer - Exercise & Workout Guide
**Bundle ID:** com.eltima.ifitness2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484069067">484069067</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fitness-trainer-exercise-workout/id484069067?mt=8&uo=4">https://itunes.apple.com/us/app/fitness-trainer-exercise-workout/id484069067?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** Vitaliy Golubenko
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/eltima/id422552672?uo=4>© Eltima</a>
**Supported Devices:** iPodTouchFifthGen, iPhone6, iPadThirdGen, iPhone5s, iPadThirdGen4G, iPadFourthGen, iPad2Wifi, iPhone4, iPadMini4G, iPhone5c, iPad23G, iPhone5, iPadFourthGen4G, iPadMini, iPhone6Plus, iPhone4S
**Original Artwork:**
<img src="http://a547.phobos.apple.com/us/r30/Purple1/v4/54/c6/3b/54c63b6b-c3a8-95a6-d9b1-ec81eb8e47b6/mzl.nhjzvwkb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6234496/9a9953a0-b6db-11e4-8126-55d4818d9059.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6234496/9a9953a0-b6db-11e4-8126-55d4818d9059.png)
https://cloud.githubusercontent.com/assets/10515074/6234496/9a9953a0-b6db-11e4-8126-55d4818d9059.png)
Source
https://cloud.githubusercontent.com/assets/10515074/6234507/ac6e380c-b6db-11e4-969b-b6ea3e925f70.png

**Comment by dreamnet** [comment]
@andreolidavide :+1:
