### ISSUE TITLE
Contacts + | Address book & Dialer

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5216]
**App Name:** Contacts + | Address book & Dialer
**Bundle ID:** com.contactspls.ContactsPlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=622367004">622367004</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/contacts-+-address-book-dialer/id622367004?mt=8&uo=4">https://itunes.apple.com/us/app/contacts-+-address-book-dialer/id622367004?mt=8&uo=4</a>
**App Version:** 1.9.4
**Seller:** Gentoo Labs, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/contacts-plus-team/id622367007?uo=4>© Contacts Plus team</a>
**Supported Devices:** iPadMini4G, iPad2Wifi, iPhone6Plus, iPadFourthGen, iPhone6, iPhone4S, iPhone5s, iPhone5, iPhone5c, iPodTouchFourthGen, iPodTouchFifthGen, iPhone4, iPadThirdGen4G, iPadMini, iPadThirdGen, iPad23G, iPadFourthGen4G
**Original Artwork:**
<img src="http://a469.phobos.apple.com/us/r30/Purple6/v4/40/62/91/4062917b-92b2-5ded-ff7c-c6d9830396fd/mzl.hfzokrik.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6234213/3cf5f61a-b6d9-11e4-9741-6d5e6854754c.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6230179/ef8447b2-b6bd-11e4-9205-238eb2f70415.png)
https://cloud.githubusercontent.com/assets/10515074/6230179/ef8447b2-b6bd-11e4-9205-238eb2f70415.png
Source
https://cloud.githubusercontent.com/assets/10515074/6230197/032c0be2-b6be-11e4-8284-6004532bd628.png

**Comment by andreolidavide** [comment]
Or something like this, what do you think?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6234213/3cf5f61a-b6d9-11e4-9741-6d5e6854754c.png)
https://cloud.githubusercontent.com/assets/10515074/6234213/3cf5f61a-b6d9-11e4-9741-6d5e6854754c.png
Source
https://cloud.githubusercontent.com/assets/10515074/6234221/50b2afb8-b6d9-11e4-9afc-76930cb55afc.png

**Comment by MagnaMike** [comment]
@andreolidavide :two: :+1:
