### ISSUE TITLE
Videon - Video Camera and Editor with Zoom, Pause, Effects, Filters

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5217]
**App Name:** Videon - Video Camera and Editor with Zoom, Pause, Effects, Filters
**Bundle ID:** com.iphoneclan.videocamera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=648862644">648862644</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/videon-video-camera-editor/id648862644?mt=8&uo=4">https://itunes.apple.com/us/app/videon-video-camera-editor/id648862644?mt=8&uo=4</a>
**App Version:** 2.11
**Seller:** Sylwester Los
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lucky-clan/id294866851?mt=8&uo=4>© Lucky Clan</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/3e/70/3f/3e703ff4-fa76-bc53-7a4d-8e81bd289507/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19587215/d1b1a83e-975c-11e6-8c4a-b0c090f1f0cc.png)

**Comment by andreolidavide** [comment]
Should I make it a bit bigger?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6230141/9d8620d4-b6bd-11e4-9526-f1e738e55d27.png)

Source
https://cloud.githubusercontent.com/assets/10515074/6230147/aa5e4d7c-b6bd-11e4-86fe-c04a9fed5be4.png

**Comment by katakolo** [comment]
It looks great, thanx very much!

**Comment by MagnaMike** [comment]
@andreolidavide Looks good. Don't forget to add the link to the icon (not just the preview), thanks!

**Comment by Trubbel** [comment]
@dreamnet I'm not really a fan of how small the icon is, don't think it looks good.
What about this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19587215/d1b1a83e-975c-11e6-8c4a-b0c090f1f0cc.png)
https://cloud.githubusercontent.com/assets/10730122/19587215/d1b1a83e-975c-11e6-8c4a-b0c090f1f0cc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19587214/d1b145f6-975c-11e6-90f2-d2749518c951.png
