### ISSUE TITLE
Hyperlapse from Instagram

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5218]
**App Name:** Hyperlapse from Instagram
**Bundle ID:** com.burbn.hyperlapse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=740146917">740146917</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hyperlapse-from-instagram/id740146917?mt=8&uo=4">https://itunes.apple.com/us/app/hyperlapse-from-instagram/id740146917?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Instagram, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/instagram-inc./id389801255?uo=4>© Instagram, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/72/b6/36/72b636d5-83b9-cc7d-0576-abfa67595c84/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15281383/e2f4829a-1b3a-11e6-96b3-7e0300ce6121.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6256142/b0e851a8-b783-11e4-9b0c-afd77800d8cd.png)
https://cloud.githubusercontent.com/assets/10950389/6256142/b0e851a8-b783-11e4-9b0c-afd77800d8cd.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6256148/be46a052-b783-11e4-8258-4f6e0a7c18d9.png

**Comment by dreamnet** [comment]
@zmathiasz Yessir! :+1:

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15281383/e2f4829a-1b3a-11e6-96b3-7e0300ce6121.png)
https://cloud.githubusercontent.com/assets/2068130/15281383/e2f4829a-1b3a-11e6-96b3-7e0300ce6121.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15281388/f1339daa-1b3a-11e6-9357-5c2566b81008.png
