### ISSUE TITLE
CLZ Movies

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5219]
**App Name:** CLZ Movies
**Bundle ID:** com.collectorz.clzmovies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=314588585">314588585</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/clz-movies/id314588585?uo=4">https://apps.apple.com/us/app/clz-movies/id314588585?uo=4</a>
**App Version:** 4.14.5
**Seller:** Bitz & Pixelz BV
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/collectorz-com/id314588588?uo=4">© Collectorz.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/26/44/01/26440122-31a6-7120-1b18-3c24dd050a49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60370769-be49f300-99f7-11e9-8b0d-03100763bef6.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6235110/f05db8f4-b6ad-11e4-849b-acdfb735a9c2.png)
https://cloud.githubusercontent.com/assets/10950389/6235110/f05db8f4-b6ad-11e4-849b-acdfb735a9c2.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6235120/08a8cd86-b6ae-11e4-8f3f-251fe0519c6f.png

**Comment by dreamnet** [comment]
@zmathiasz :+1:

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60370769-be49f300-99f7-11e9-8b0d-03100763bef6.png)
https://user-images.githubusercontent.com/2068130/60370769-be49f300-99f7-11e9-8b0d-03100763bef6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60370809-cd30a580-99f7-11e9-9b96-5929b40e3b84.png
