### ISSUE TITLE
mviewer

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5220]
**App Name:** mviewer
**Bundle ID:** com.dvrdomain.viewer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347189821">347189821</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mviewer/id347189821?mt=8&uo=4">https://itunes.apple.com/us/app/mviewer/id347189821?mt=8&uo=4</a>
**App Version:** 3.3.2
**Seller:** DVRDomain .com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dvrdomain/id347189824?uo=4>© dvrdomain</a>
**Supported Devices:** iPhone-3GS, iPhone6, iPhone6Plus, iPadMini, iPad2Wifi, iPadThirdGen, iPadMini4G, iPhone5s, iPadFourthGen4G, iPodTouchFifthGen, iPhone5c, iPhone5, iPodTouchFourthGen, iPhone4S, iPadFourthGen, iPodTouchThirdGen, iPadThirdGen4G, iPhone4, iPadWifi, iPad23G, iPad3G
**Original Artwork:**
<img src="http://a990.phobos.apple.com/us/r30/Purple1/v4/ee/59/5a/ee595aaf-478d-8314-c5d4-41dcc6202bb3/pr_source.jpg?downloadKey=1424158080_2adaee781d68273a90857e3ae7f7b1a3" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6336940/92008d10-bba6-11e4-8d2f-a489c5104e94.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6321872/d135fdfc-bad5-11e4-8b89-b9852991a79d.png)
https://cloud.githubusercontent.com/assets/10950389/6321872/d135fdfc-bad5-11e4-8b89-b9852991a79d.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6321865/9a039f24-bad5-11e4-94b5-b09c111d6d69.png

**Comment by dreamnet** [comment]
Hm, another try:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6336940/92008d10-bba6-11e4-8d2f-a489c5104e94.png)
https://cloud.githubusercontent.com/assets/2068130/6336940/92008d10-bba6-11e4-8d2f-a489c5104e94.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6336949/a5e33c6a-bba6-11e4-9af1-45db755557a9.png
I don't want to do the world in the middle of the icon, I think let it out for more transparency is better.

**Comment by zmathiasz** [comment]
Makes sense. :)

**Comment by MagnaMike** [comment]
Looks good @dreamnet :+1:
