### ISSUE TITLE
VegasMate - Las Vegas Travel Guide

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5221]
**App Name:** VegasMate - Las Vegas Travel Guide
**Bundle ID:** com.vegasmediagroup.VegasMate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288946782">288946782</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vegasmate-las-vegas-travel/id288946782?mt=8&uo=4">https://itunes.apple.com/us/app/vegasmate-las-vegas-travel/id288946782?mt=8&uo=4</a>
**App Version:** 4.7
**Seller:** Hunter Hillegas
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/vegas-media-group/id288946785?uo=4>© Vegas Media Group</a>
**Supported Devices:** iPhone4S, iPhone5s, iPadFourthGen, iPadThirdGen4G, iPadMini, iPodTouchFifthGen, iPadMini4G, iPhone5c, iPhone5, iPhone6, iPad2Wifi, iPad23G, iPadFourthGen4G, iPhone6Plus, iPadThirdGen
**Original Artwork:**
<img src="http://a71.phobos.apple.com/us/r30/Purple5/v4/b3/85/02/b3850242-09f1-376f-de50-ec2238004d43/mzl.osqronfb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6266726/364cdb20-b80b-11e4-9b01-b169f8c8e96d.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6260341/6960ca7c-b7ab-11e4-8cbc-5a6447077ee4.png)
https://cloud.githubusercontent.com/assets/10950389/6260341/6960ca7c-b7ab-11e4-8cbc-5a6447077ee4.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6260345/787e6e24-b7ab-11e4-89b6-1261da7a2c1b.png

**Comment by ivanov007** [comment]
I think the welcome circle's line should be a little thicker

**Comment by zmathiasz** [comment]
How about so?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6266726/364cdb20-b80b-11e4-9b01-b169f8c8e96d.png)
https://cloud.githubusercontent.com/assets/10950389/6266726/364cdb20-b80b-11e4-9b01-b169f8c8e96d.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6266735/4ae5248e-b80b-11e4-9c48-ee33950aaf5b.png

**Comment by ivanov007** [comment]
@zmathiasz  yup :+1:

**Comment by MagnaMike** [comment]
@dreamnet Now, correct me if I'm wrong, but about icon sources... Isn't the source sizing incorrect on this? Since the icon uses the full 78x78 area on the icon, shouldn't the source use the full 1024x1024?

**Comment by zmathiasz** [comment]
@MagnaMike @dreamnet If that's true I'm ready to fix them!!

**Comment by dreamnet** [comment]
@zmathiasz Yes, that's right - I already corrected it [here](http://glasklarthd.dreamnet.at/index.php?id=7359) (I redo all icon sources when adding them to my website).

**Comment by zmathiasz** [comment]
@dreamnet Okay. I will make sure I'm upscaling when necessary to save you the trouble. :)

**Comment by dreamnet** [comment]
@zmathiasz No problem! :+1:
