### ISSUE TITLE
Virgin Atlantic

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5222]
**App Name:** Virgin Atlantic
**Bundle ID:** com.virginatlantic.flighttracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347564786">347564786</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/virgin-atlantic/id347564786?mt=8&uo=4">https://itunes.apple.com/us/app/virgin-atlantic/id347564786?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Virgin Atlantic Airways Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/virgin-atlantic-airways-limited/id347564789?uo=4>© Virgin Atlantic Airways Limited</a>
**Supported Devices:** iPad2Wifi, iPhone6Plus, iPhone4S, iPhone5s, iPhone5, iPadThirdGen4G, iPadFourthGen, iPadMini4G, iPhone6, iPodTouchFifthGen, iPadThirdGen, iPadMini, iPhone4, iPad23G, iPadFourthGen4G, iPhone5c
**Original Artwork:**
<img src="http://a710.phobos.apple.com/us/r30/Purple3/v4/11/5f/92/115f92ce-8692-7e54-4892-cd47bd76f29e/pr_source.png?downloadKey=1424158232_476c7583393830a1e8bcc1353f23c515" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6234669/b3cd648c-b6aa-11e4-903d-ce024a0e9318.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6234669/b3cd648c-b6aa-11e4-903d-ce024a0e9318.png)
https://cloud.githubusercontent.com/assets/10950389/6234704/f74ac95c-b6aa-11e4-9211-4adef958dd1e.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6234716/087358ca-b6ab-11e4-94f8-b079540183b5.png

**Comment by dreamnet** [comment]
@zmathiasz Yes! :+1:
