### ISSUE TITLE
STANLEY® Level

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5223]
**App Name:** STANLEY® Level
**Bundle ID:** com.stanleyblackanddecker.stanleylevel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=565961826">565961826</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stanley-level/id565961826?mt=8&uo=4">https://itunes.apple.com/us/app/stanley-level/id565961826?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Stanley Black & Decker, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/stanley-black-decker-inc./id414050137?uo=4>© Stanley Black & Decker, Inc.</a>
**Supported Devices:** iPhone4S, iPadFourthGen, iPhone4, iPhone6, iPadFourthGen4G, iPad23G, iPad2Wifi, iPadThirdGen4G, iPadMini4G, iPhone6Plus, iPadThirdGen, iPodTouchFifthGen, iPhone5s, iPhone5c, iPhone5, iPadMini
**Original Artwork:**
<img src="http://a1647.phobos.apple.com/us/r30/Purple3/v4/3e/c7/aa/3ec7aad5-7653-c2eb-928a-9c7291131432/mzl.sfssjqst.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6320631/56067284-bae3-11e4-865a-d77ec1f226dd.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6320061/7c084ffc-baa2-11e4-89e4-eb377eed73d3.png)
https://cloud.githubusercontent.com/assets/10950389/6320061/7c084ffc-baa2-11e4-89e4-eb377eed73d3.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6320065/8c31dcae-baa2-11e4-8206-bb231a9a4f8c.png

**Comment by dreamnet** [comment]
Just made it a bit clearer:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6320631/56067284-bae3-11e4-865a-d77ec1f226dd.png)
https://cloud.githubusercontent.com/assets/2068130/6320631/56067284-bae3-11e4-865a-d77ec1f226dd.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6320634/6317b23a-bae3-11e4-9db0-4430753af56c.png

**Comment by zmathiasz** [comment]
Looks good. I did have a cleaner one but less detail. :)
