### ISSUE TITLE
Gas Guru: Cheap gas prices

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5224]
**App Name:** Gas Guru: Cheap gas prices
**Bundle ID:** com.yellowpages.drive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525588154">525588154</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gas-guru-cheap-gas-prices/id525588154?mt=8&uo=4">https://itunes.apple.com/us/app/gas-guru-cheap-gas-prices/id525588154?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** Yellowpages.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/yellowpages.com-llc/id281970042?uo=4>© YELLOWPAGES.COM LLC</a>
**Supported Devices:** iPadFourthGen4G, iPadThirdGen, iPhone5s, iPhone6, iPodTouchFifthGen, iPad23G, iPhone4, iPhone6Plus, iPad2Wifi, iPadMini, iPadMini4G, iPadThirdGen4G, iPadFourthGen, iPhone4S, iPhone5, iPhone5c
**Original Artwork:**
<img src="http://a320.phobos.apple.com/us/r30/Purple5/v4/db/4c/65/db4c6523-7f56-70b0-dbeb-970cad7b314b/pr_source.png?downloadKey=1424158408_1b4c889bcdeb95855c70b152193d28b5" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6230085/175f33ce-b6bd-11e4-8fce-ba82da4afd93.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6230085/175f33ce-b6bd-11e4-8fce-ba82da4afd93.png)
https://cloud.githubusercontent.com/assets/10515074/6230085/175f33ce-b6bd-11e4-8fce-ba82da4afd93.png
Source
https://cloud.githubusercontent.com/assets/10515074/6230094/2d10a932-b6bd-11e4-88be-78b0a4bc6618.png
