### ISSUE TITLE
Lotto NL

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5225]
**App Name:** Lotto NL
**Bundle ID:** nl.delotto.Lotto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=903801111">903801111</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/nl/app/lotto-nl/id903801111?mt=8&uo=4">https://itunes.apple.com/nl/app/lotto-nl/id903801111?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Stichting de Nationale Sporttotalisator
**Developer:** <a target="_blank" href=https://itunes.apple.com/nl/artist/stichting-nationale-sporttotalisator/id525024534?uo=4>© Stichting de Nationale Sporttotalisator</a>
**Supported Devices:** iPhone5, iPadThirdGen4G, iPodTouchFifthGen, iPad2Wifi, iPad23G, iPadMini4G, iPhone6, iPadFourthGen4G, iPadMini, iPhone5s, iPadFourthGen, iPhone6Plus, iPhone4, iPadThirdGen, iPhone4S, iPhone5c
**Original Artwork:**
<img src="http://a387.phobos.apple.com/us/r30/Purple3/v4/d7/40/46/d74046e1-1276-4707-3c35-63fe221ec4d1/mzl.wusbczms.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6257236/e22c2e34-b7be-11e4-96ed-cf444849ef23.png)

**Comment by MagnaMike** [comment]
Please leave the `### THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. ###` line below *Accepted Artwork:*

Take note of `DO NOT MODIFY`. Thanks!

**Comment by powerfull** [comment]
**App Name:** Lotto NL
**Bundle ID:** nl.delotto.Lotto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=903801111">903801111</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/nl/app/lotto-nl/id903801111?mt=8&uo=4">https://itunes.apple.com/nl/app/lotto-nl/id903801111?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Stichting de Nationale Sporttotalisator
**Developer:** <a target="_blank" href=https://itunes.apple.com/nl/artist/stichting-nationale-sporttotalisator/id525024534?uo=4>© Stichting de Nationale Sporttotalisator</a>
**Supported Devices:** iPhone6, iPad2Wifi, iPad23G, iPhone4, iPhone6Plus, iPadThirdGen, iPadThirdGen4G, iPadMini, iPodTouchFifthGen, iPadMini4G, iPhone4S, iPadFourthGen, iPhone5, iPadFourthGen4G, iPhone5c, iPhone5s
**Original Artwork:**
<img src="http://a387.phobos.apple.com/us/r30/Purple3/v4/d7/40/46/d74046e1-1276-4707-3c35-63fe221ec4d1/mzl.wusbczms.png" width="150" height="150" />
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#
**Accepted Artwork:**

**Comment by MagnaMike** [comment]
No it's okay, I edited your original request.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6257236/e22c2e34-b7be-11e4-96ed-cf444849ef23.png)
https://cloud.githubusercontent.com/assets/2068130/6257236/e22c2e34-b7be-11e4-96ed-cf444849ef23.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6257245/f238b87e-b7be-11e4-8b0a-cf656c22ba94.png
