### ISSUE TITLE
SNL

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5226]
**App Name:** SNL
**Bundle ID:** com.nbcuni.nbc.snl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=949622036">949622036</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snl/id949622036?mt=8&uo=4">https://itunes.apple.com/us/app/snl/id949622036?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** NBCUniversal Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nbcuniversal-media-llc/id303544359?uo=4>© NBCUniversal Media, LLC</a>
**Supported Devices:** iPadThirdGen, iPhone4S, iPhone5, iPadMini, iPodTouchFifthGen, iPhone5c, iPhone6Plus, iPad2Wifi, iPadMini4G, iPhone5s, iPhone6, iPad23G, iPadThirdGen4G, iPadFourthGen4G, iPadFourthGen
**Original Artwork:**
<img src="http://a1609.phobos.apple.com/us/r30/Purple5/v4/f4/d0/f2/f4d0f24c-d6ca-cb99-f95f-d8eba63363d5/mzl.ydygvsko.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6256053/ea0aba76-b782-11e4-811a-101e2ebb06c1.png)

**Comment by andreolidavide** [comment]
If you want the writing a bit bigger just tell me :+1: 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6255020/3e4420a8-b7ad-11e4-88b2-d1db6b5c5395.png)
https://cloud.githubusercontent.com/assets/10515074/6255020/3e4420a8-b7ad-11e4-88b2-d1db6b5c5395.png
Source
https://cloud.githubusercontent.com/assets/10515074/6255031/58f40d50-b7ad-11e4-9387-e9cc964fc483.png

**Comment by MagnaMike** [comment]
@andreolidavide Yeah, can you try bigger? Fill the 78x78 area I guess?

**Comment by andreolidavide** [comment]
@MagnaMike like this?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6255565/33a35a2a-b7b1-11e4-89db-a3c8b063efbb.png)
https://cloud.githubusercontent.com/assets/10515074/6255565/33a35a2a-b7b1-11e4-89db-a3c8b063efbb.png
Source
https://cloud.githubusercontent.com/assets/10515074/6255582/52209f12-b7b1-11e4-9e9d-1a5e258ba6a4.png

**Comment by MagnaMike** [comment]
I ended up putting the normal icon behind the glasklart icon when figuring out the sizing to make it as close as I could to the actual size.

---

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6256053/ea0aba76-b782-11e4-811a-101e2ebb06c1.png)
https://cloud.githubusercontent.com/assets/2236254/6256053/ea0aba76-b782-11e4-811a-101e2ebb06c1.png

https://cloud.githubusercontent.com/assets/2236254/6256061/fed0d01c-b782-11e4-9f28-0ceea0279581.png
Source:

**Comment by andreolidavide** [comment]
Great! I didn't thought of that :disappointed:
