### ISSUE TITLE
FINAL FANTASY VI

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5227]
**App Name:** FINAL FANTASY VI
**Bundle ID:** com.square-enix.FinalFantasy6
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=719401490">719401490</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/final-fantasy-vi/id719401490?mt=8&uo=4">https://itunes.apple.com/us/app/final-fantasy-vi/id719401490?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPad23G, iPadMini4G, iPhone5s, iPodTouchFifthGen, iPadMini, iPadThirdGen, iPhone6Plus, iPad2Wifi, iPhone5c, iPhone4S, iPadFourthGen4G, iPadThirdGen4G, iPhone6, iPadFourthGen, iPhone4, iPhone5
**Original Artwork:**
<img src="http://a714.phobos.apple.com/us/r30/Purple3/v4/3c/25/9c/3c259c5b-3441-2a31-bb4f-49f1f4b67665/mzl.rfifdflp.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997157/4277736a-db7e-11e4-9cbe-c26c2ec01fef.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6256333/4a63bd4e-b785-11e4-810b-2b77b113b5a8.png)
https://cloud.githubusercontent.com/assets/10950389/6256333/4a63bd4e-b785-11e4-810b-2b77b113b5a8.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6256350/658ab1e0-b785-11e4-95ae-14374b60b98f.png

**Comment by zmathiasz** [comment]
I did make sure that this followed the previous FF series icons within the theme.  It is a bit small, but not much I can do to make it bigger.  :D

**Comment by dreamnet** [comment]
@zmathiasz Jup. All good. :+1:

**Comment by zmathiasz** [comment]
@dreamnet 

Updated. Cleaned up the text so it stands out a little better and doesn't blur as much into the image. :smile: 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997157/4277736a-db7e-11e4-9cbe-c26c2ec01fef.png)
https://cloud.githubusercontent.com/assets/10950389/6997157/4277736a-db7e-11e4-9cbe-c26c2ec01fef.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6997159/69cb63f4-db7e-11e4-9fee-978b41ca2d48.png

**Comment by dreamnet** [comment]
@zmathiasz Jup! :+1:
