### ISSUE TITLE
MARVEL Contest of Champions

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5228]
**App Name:** MARVEL Contest of Champions
**Bundle ID:** com.kabam.marvelbattle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=896112560">896112560</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/marvel-contest-of-champions/id896112560?mt=8&uo=4">https://itunes.apple.com/us/app/marvel-contest-of-champions/id896112560?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Kabam Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kabam/id445459903?uo=4>© Kabam</a>
**Supported Devices:** iPadMini, iPhone6Plus, iPhone5c, iPhone5, iPadThirdGen4G, iPhone6, iPhone4, iPodTouchFifthGen, iPadFourthGen4G, iPad2Wifi, iPad23G, iPadMini4G, iPadFourthGen, iPhone5s, iPadThirdGen, iPhone4S
**Original Artwork:**
<img src="http://a384.phobos.apple.com/us/r30/Purple3/v4/6c/a9/e2/6ca9e220-a732-7a71-3188-d8506e977008/mzl.yzgfqqaz.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6268652/73b18e50-b81c-11e4-83bf-519137cfbcb7.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6266452/09eb23b4-b808-11e4-9ce3-488ffabd0891.png)
https://cloud.githubusercontent.com/assets/10950389/6266452/09eb23b4-b808-11e4-9ce3-488ffabd0891.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6266471/326e6508-b808-11e4-9b36-b8933038ba49.png

**Comment by zmathiasz** [comment]
I think I'm going clean up the marvel logo.

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6268576/f16db162-b81b-11e4-8d7e-9355f6346d26.png)
https://cloud.githubusercontent.com/assets/10950389/6268576/f16db162-b81b-11e4-8d7e-9355f6346d26.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6268588/09ed8082-b81c-11e4-89fb-857f96f74554.png

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6268652/73b18e50-b81c-11e4-83bf-519137cfbcb7.png)
https://cloud.githubusercontent.com/assets/10950389/6268652/73b18e50-b81c-11e4-83bf-519137cfbcb7.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6268664/8314f1fc-b81c-11e4-8eea-5c7d7f2c7527.png

**Comment by ivanov007** [comment]
wow a lot of free hand work, it looks very good :+1: and I think the second one will mate it

**Comment by dreamnet** [comment]
@zmathiasz Good work! :+1:
