### ISSUE TITLE
SHADOWGUN: DeadZone

### ISSUE THREAD

**Issue by inBrink** [glasklart/hd#523]
**App Name:** SHADOWGUN: DeadZone
**Bundle ID:** com.madfingergames.deadzone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561048152">561048152</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shadowgun-deadzone/id561048152?mt=8&uo=4">https://itunes.apple.com/us/app/shadowgun-deadzone/id561048152?mt=8&uo=4</a>
**App Version:** 2.6.0
**Seller:** MADFINGER Games, a.s.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/madfinger-games-a.s./id313220894?uo=4">© MADFINGER Games, a.s.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/49/e6/24/49e624c1-c7b1-d711-d68a-97d800a69559/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20184568/68538976-a769-11e6-8a67-f11309407451.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20184568/68538976-a769-11e6-8a67-f11309407451.png)
https://cloud.githubusercontent.com/assets/20930745/20184568/68538976-a769-11e6-8a67-f11309407451.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20184603/8443ab16-a769-11e6-8124-02ccdf485f21.png
