### ISSUE TITLE
Banggood - Shopping With Fun

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5230]
**App Name:** Banggood - Shopping With Fun
**Bundle ID:** banggood.shop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=906268880">906268880</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/banggood-shopping-with-fun/id906268880?mt=8&uo=4">https://itunes.apple.com/us/app/banggood-shopping-with-fun/id906268880?mt=8&uo=4</a>
**App Version:** 1.8.0
**Seller:** Guangzhou Banggood Network Technology Co., Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/banggood-co.-ltd/id906268883?uo=4>© Banggood Co.,Ltd</a>
**Supported Devices:** iPodTouchFifthGen, iPadMini4G, iPhone4S, iPhone6Plus, iPadThirdGen4G, iPhone5s, iPad2Wifi, iPhone5c, iPadFourthGen, iPad23G, iPhone4, iPhone5, iPadFourthGen4G, iPadThirdGen, iPhone6, iPadMini
**Original Artwork:**
<img src="http://a1283.phobos.apple.com/us/r30/Purple1/v4/9d/82/1f/9d821f4d-b6d4-b0e6-3334-5f786345d4b6/mzl.wntaqswe.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6272124/03257642-b82b-11e4-908a-a4875889ca9f.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6272122/0321e50e-b82b-11e4-990d-b535acc3d0d5.png)
https://cloud.githubusercontent.com/assets/3090247/6272122/0321e50e-b82b-11e4-990d-b535acc3d0d5.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6272124/03257642-b82b-11e4-908a-a4875889ca9f.png)
https://cloud.githubusercontent.com/assets/3090247/6272124/03257642-b82b-11e4-908a-a4875889ca9f.png

---
Sources
https://cloud.githubusercontent.com/assets/3090247/6272123/0324a4f6-b82b-11e4-8615-e5553df8dbcf.png)
https://cloud.githubusercontent.com/assets/3090247/6272125/03433efc-b82b-11e4-8180-608ccd310ed0.png

**Comment by dreamnet** [comment]
@ivanov007 Good, I'm taking the second one because we already have icons with very similar shopping charts... :+1:

**Comment by powerfull** [comment]
The second is nice.
Thank you very much.
