### ISSUE TITLE
DemonSouls (action RPG)

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5231]
**App Name:** DemonSouls (action RPG)
**Bundle ID:** com.gameislive.shanhai
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=486677257">486677257</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/demonsouls-action-rpg/id486677257?mt=8&uo=4">https://itunes.apple.com/us/app/demonsouls-action-rpg/id486677257?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** LAKOO GAMES LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/lakoo/id353949069?uo=4>© Lakoo</a>
**Supported Devices:** iPhone5s, iPhone5c, iPadFourthGen4G, iPodTouchFifthGen, iPadMini4G, iPhone4, iPhone6, iPhone5, iPadThirdGen, iPadThirdGen4G, iPhone4S, iPad2Wifi, iPhone6Plus, iPad3G, iPadFourthGen, iPodTouchThirdGen, iPhone-3GS, iPodTouchFourthGen, iPadMini, iPadWifi, iPad23G
**Original Artwork:**
<img src="http://a199.phobos.apple.com/us/r30/Purple6/v4/d5/d1/a3/d5d1a3a3-833d-d269-8262-e74e22212c3f/mzl.afpsalcb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6273892/1d33d0f4-b841-11e4-969c-2fe3527f8e19.png)

**Comment by zmathiasz** [comment]
Even though it is my request should I wait for the valid-icon-request label?  I have it made already.  :D

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6273892/1d33d0f4-b841-11e4-969c-2fe3527f8e19.png)
https://cloud.githubusercontent.com/assets/10950389/6273892/1d33d0f4-b841-11e4-969c-2fe3527f8e19.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6273900/30ce49dc-b841-11e4-9bfd-0ccbaa67626a.png

**Comment by ivanov007** [comment]
@zmathiasz great :+1: you know, when fulfilling your own request you don't need to wait until the request gets validated, you can post the icon right away :smile:

**Comment by zmathiasz** [comment]
Okay. I was wondering that. :). Just wanted to follow procedure. Lol. Like work but more fun.

**Comment by dreamnet** [comment]
@zmathiasz Wow, I really have to say you are doing great work! Keep on! :+1: :+1: :+1:
