### ISSUE TITLE
FINAL FANTASY IV: THE AFTER YEARS

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5232]
**App Name:** FINAL FANTASY IV: THE AFTER YEARS
**Bundle ID:** com.square-enix.FF4AY
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=683029090">683029090</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/final-fantasy-iv-after-years/id683029090?mt=8&uo=4">https://itunes.apple.com/us/app/final-fantasy-iv-after-years/id683029090?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone6Plus, iPadThirdGen4G, iPad23G, iPhone-3GS, iPhone4, iPhone6, iPhone5, iPad3G, iPadFourthGen, iPodTouchFourthGen, iPadWifi, iPadMini4G, iPhone5c, iPhone5s, iPadThirdGen, iPadFourthGen4G, iPodTouchFifthGen, iPadMini, iPodTouchThirdGen, iPad2Wifi, iPhone4S
**Original Artwork:**
<img src="http://a333.phobos.apple.com/us/r30/Purple4/v4/5c/50/2b/5c502bc5-1baa-7c57-91f7-4d5692574781/mzl.uopvuyqb.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6280694/1985c50e-b880-11e4-9e05-70fb91e6dd79.png)

**Comment by zmathiasz** [comment]
As with the other FF series this is small, but unfortunately I think it would take away from the icon to arrange it like the others.  Maybe possible.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6279118/519ad0ac-b86b-11e4-9ce6-cb25f9e957d0.png)
https://cloud.githubusercontent.com/assets/10950389/6279118/519ad0ac-b86b-11e4-9ce6-cb25f9e957d0.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6279132/744b51bc-b86b-11e4-8e5e-88a9b4f0c716.jpg

**Comment by zmathiasz** [comment]
I think I can thicken the border around the Final Fantasy print to make it stand out more.

**Comment by MagnaMike** [comment]
@zmathiasz That's probably a good idea. Let's see what that looks like. Maybe ~10 px border around the letters?

**Comment by zmathiasz** [comment]
How about so?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6280694/1985c50e-b880-11e4-9e05-70fb91e6dd79.png)
https://cloud.githubusercontent.com/assets/10950389/6280694/1985c50e-b880-11e4-9e05-70fb91e6dd79.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6280702/33d91f32-b880-11e4-86e8-2a259c3b2508.png

**Comment by MagnaMike** [comment]
@zmathiasz I prefer that, and I think that's the best the icon can be without changing the design. :+1:
