### ISSUE TITLE
PopKey Animated GIF Keyboard - Add Funny GIFs, LOL memes & stickers to conversations

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5233]
**App Name:** PopKey Animated GIF Keyboard - Add Funny GIFs, LOL memes & stickers to conversations
**Bundle ID:** WorkshopX.PopKey
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=919359310">919359310</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/popkey-animated-gif-keyboard/id919359310?mt=8&uo=4">https://itunes.apple.com/us/app/popkey-animated-gif-keyboard/id919359310?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** WorkshopX Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/workshopx-inc./id919359309?uo=4>© WorkshopX Inc.</a>
**Supported Devices:** iPad23G, iPadThirdGen, iPhone4S, iPhone6Plus, iPadThirdGen4G, iPadFourthGen4G, iPadMini, iPhone5s, iPadFourthGen, iPadMini4G, iPhone5, iPad2Wifi, iPhone5c, iPodTouchFifthGen, iPhone6
**Original Artwork:**
<img src="http://a1765.phobos.apple.com/us/r30/Purple3/v4/3d/99/b0/3d99b0d2-6dbd-b5ee-dddf-0ffcb070fc75/mzl.hzbzmrne.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6277212/14364896-b88d-11e4-946c-b888a0d65faa.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6273793/cd1abfc8-b837-11e4-8a64-5112248acdb1.png)
https://cloud.githubusercontent.com/assets/3090247/6273793/cd1abfc8-b837-11e4-8a64-5112248acdb1.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6273790/cce4b360-b837-11e4-8e8d-b615e75919aa.png)
https://cloud.githubusercontent.com/assets/3090247/6273790/cce4b360-b837-11e4-8e8d-b615e75919aa.png

---
Sources:
https://cloud.githubusercontent.com/assets/3090247/6273792/cce8e9e4-b837-11e4-95fc-d28f15222807.png
https://cloud.githubusercontent.com/assets/3090247/6273791/cce51abc-b837-11e4-8883-d5b889113432.png

**Comment by MagnaMike** [comment]
Alternates.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6277154/4221d226-b85a-11e4-88fe-762441682af1.png)
https://cloud.githubusercontent.com/assets/2236254/6277154/4221d226-b85a-11e4-88fe-762441682af1.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6277155/4221fb7a-b85a-11e4-8c95-28f9a5b0bb93.png.

----

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6277156/42243e80-b85a-11e4-9748-19e280a0a332.png)
https://cloud.githubusercontent.com/assets/2236254/6277156/42243e80-b85a-11e4-9748-19e280a0a332.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6277157/4228e6c4-b85a-11e4-885a-2f6a434f67ed.png

**Comment by dreamnet** [comment]
Or simply this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6277212/14364896-b88d-11e4-946c-b888a0d65faa.png)
https://cloud.githubusercontent.com/assets/2068130/6277212/14364896-b88d-11e4-946c-b888a0d65faa.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6277222/207bb94c-b88d-11e4-9ad9-e1bdb52f5356.png

**Comment by MagnaMike** [comment]
@dreamnet Yep. :+1:
