### ISSUE TITLE
Popcorn Time

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5234]
**App Name:** Popcorn Time
**Bundle ID:**  com.popcorn.time
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://d262ilb51hltx0.cloudfront.net/max/800/1*qDrF5-SSnFkUde7eMvNtNA.jpeg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6313570/c20fceca-b9b3-11e4-83a8-8d588ed12152.png)

**Comment by MagnaMike** [comment]
Isn't this service being shut down?

**Comment by powerfull** [comment]
I don't know for sure but it is still working on my device.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6313570/c20fceca-b9b3-11e4-83a8-8d588ed12152.png)
https://cloud.githubusercontent.com/assets/2068130/6313570/c20fceca-b9b3-11e4-83a8-8d588ed12152.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6313571/d03a17f8-b9b3-11e4-88c2-591ae755c797.png
