### ISSUE TITLE
Super Star® Rewards

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5235]
**App Name:** Super Star® Rewards
**Bundle ID:** com.ckr.happystarrewards
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=408121669">408121669</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-star-rewards/id408121669?mt=8&uo=4">https://itunes.apple.com/us/app/super-star-rewards/id408121669?mt=8&uo=4</a>
**App Version:** 2.0.9
**Seller:** Carl's Jr. and Hardee's
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/carls-jr.-and-hardees/id408121672?uo=4>© Carl's Jr. and Hardee's</a>
**Supported Devices:** iPhone-3GS, iPadMini, iPadFourthGen4G, iPhone4S, iPad23G, iPodTouchFourthGen, iPadThirdGen, iPhone6Plus, iPad2Wifi, iPhone5, iPhone6, iPhone5c, iPodTouchFifthGen, iPhone4, iPadMini4G, iPhone5s, iPadThirdGen4G, iPadFourthGen
**Original Artwork:**
<img src="http://a727.phobos.apple.com/us/r30/Purple3/v4/ed/34/28/ed3428f4-910e-4406-4e85-4ea79f7e0a27/pr_source.jpg?downloadKey=1424405473_72a2b277d26b4da542c8ce671bda398c" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6280505/3848979a-b863-11e4-8023-7e8044211adb.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6280505/3848979a-b863-11e4-8023-7e8044211adb.png)
https://cloud.githubusercontent.com/assets/10394552/6280505/3848979a-b863-11e4-8023-7e8044211adb.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6280502/31f39138-b863-11e4-9cc5-540a9762ae81.png

**Comment by MagnaMike** [comment]
@PolarisBeaver Yep! :+1:
