### ISSUE TITLE
LocationFaker

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5236]
**App Name:** LocationFaker
 **Bundle ID:** com.cunstucks.LocationChanger
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/10394552/6281024/9a36321a-b86c-11e4-9d29-74777149095d.png" width="150" height="150" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6281042/e4f99c06-b86c-11e4-8ab7-1f6f0b3bd549.png)

**Comment by PolarisBeaver** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6281042/e4f99c06-b86c-11e4-8ab7-1f6f0b3bd549.png)
https://cloud.githubusercontent.com/assets/10394552/6281042/e4f99c06-b86c-11e4-8ab7-1f6f0b3bd549.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6281037/ddec9af8-b86c-11e4-9c1b-1eba6a12a8eb.png

**Comment by PolarisBeaver** [comment]
Something seems a little off about this, I dunno.... I still have the vector if anyone has any suggestions. Maybe knocking out the middle arrows? Hmmm....

**Comment by PolarisBeaver** [comment]
I might try making an alt later when I have more patience.

**Comment by MagnaMike** [comment]
@PolarisBeaver If you're going to make an alt, try knocking out the arrows and 'un-knock out' the bottom road. :+1: If you decide not to, that's fine, the icon is 'acceptably fulfilled' with the one you provided in my opinion.

**Comment by PolarisBeaver** [comment]
Might want to add the cydia-app tag too. After thinking it over, I suppose it looks alright after all.
