### ISSUE TITLE
ProTube for YouTube

### ISSUE THREAD

**Issue by arcticsn0w** [glasklart/hd#5241]
**App Name:** ProTube for YouTube
**Bundle ID:** de.j-gessner.protube2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=931201696">931201696</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/protube-for-youtube/id931201696?mt=8&uo=4">https://itunes.apple.com/us/app/protube-for-youtube/id931201696?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Jonas Gessner
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jonas-gessner/id449443984?uo=4>© Jonas Gessner</a>
**Supported Devices:** iPhone6Plus, iPad2Wifi, iPhone4S, iPhone4, iPad23G, iPadFourthGen, iPhone5s, iPadMini4G, iPhone5c, iPodTouchFifthGen, iPadFourthGen4G, iPhone5, iPadMini, iPadThirdGen4G, iPhone6, iPadThirdGen
**Original Artwork:**
<img src="http://a1504.phobos.apple.com/us/r30/Purple3/v4/84/0a/e6/840ae64b-d903-952c-b885-a4c6798e151b/mzl.lwlirxsn.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6343342/d00814e4-bb9b-11e4-92ff-9ca4862dbcf1.png)

**Comment by arcticsn0w** [comment]
Fulfilled my own request.

Not sure if I did a good job. This is my first time, and I'm using this as an opportunity to begin to learn how to use Photoshop. Let me know.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3134360/6321592/4390e3c8-bacf-11e4-8563-103cd8316d6f.png)

![protube2-glasklart](https://cloud.githubusercontent.com/assets/3134360/6321592/4390e3c8-bacf-11e4-8563-103cd8316d6f.png)

Source:

![pt2source](https://cloud.githubusercontent.com/assets/3134360/6321600/76541e38-bacf-11e4-8440-413dfe70bd72.png)

**Comment by PolarisBeaver** [comment]
First off, welcome! A good first attempt, however there were a couple small mistakes with your submission. I hope this detailed explanation will help. Click the images below to make them bigger if needed.

Before saving any source file, be sure it is transparent! A before and after shot:

![step1](https://cloud.githubusercontent.com/assets/10394552/6323017/973ce0ba-bad6-11e4-9a75-f1d0aad8f314.png)


Next, you will need to make your Source File 1024 x 1024 pixels, it is currently 772 x 868. There is a chance the source might be blurred and/or warped if you just boost up the image dimensions so I would suggest just recreating the icon to the new dimensions, considering it is a nice simple design. Notice in my picture that it is not touching the walls, the proportions are maintained that way.

![step2](https://cloud.githubusercontent.com/assets/10394552/6323061/9cfd430e-bad7-11e4-844d-c954a2be883d.png)


You can then scale your image and snap the edges perfectly to the guidelines for an square 1:1 fit!

![step3](https://cloud.githubusercontent.com/assets/10394552/6323065/b650bcd2-bad7-11e4-8b4d-41de6041d45b.png)


Next, you will need to apply the provided Glasklart layer style found in the Sample Icons group in the PSD, as it appears yours was just made white. Here I have shown the action you need to take. Alt + click the fx layer style icon to your new glyph to apply it.

![step4](https://cloud.githubusercontent.com/assets/10394552/6323079/002065ce-bad8-11e4-875e-268ea51447ad.png)

Before:
![old](https://cloud.githubusercontent.com/assets/10394552/6323105/77bdcfcc-bad8-11e4-976b-ae6dffc2232f.png)
After:
![fixed](https://cloud.githubusercontent.com/assets/10394552/6323097/552c760c-bad8-11e4-8b50-65215b1ff870.png)

**Comment by PolarisBeaver** [comment]
Keep in mind I have not rendered any final versions of your icon, I didn't want to steal your first submission from you. Give these instructions a shot! :) :+1:

**Comment by arcticsn0w** [comment]
Will try to redo when I get home.

Just one question; how would I redo the source file so it's 1024x1024? I'm horrible at Photoshop :p

**Comment by ivanov007** [comment]
wow @PolarisBeaver great tutorial, whhat do you think if we add it to the [https://github.com/glasklart/hd/wiki](wiki)?

**Comment by PolarisBeaver** [comment]
@arcticsn0w when you made the icon, just do the same thing you did originally but just on a larger canvas. I'm not sure what tools you used to make it but you start off by creating a new document with a 1024x1024 pixel image size, when prompted on the new file creation. Make sure it's in pixels, not inches.

![2015-02-23 16_20_16-new](https://cloud.githubusercontent.com/assets/10394552/6340788/e55f3ea4-bb77-11e4-804e-d2934f908d4c.png)

**Comment by PolarisBeaver** [comment]
@ivanov007 Sure, however this particular tutorial was catered to filling in the missing steps for this icon, it wouldn't be any trouble to make a more complete start-to-finish tutorial. When I make it, would I be able to upload it to the wiki myself?

**Comment by arcticsn0w** [comment]
I tried my best this time. Let me know if there's any issues; I'm open for criticism.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3134360/6342085/4d7c86bc-bba1-11e4-928c-6742d18e3d26.png)

https://cloud.githubusercontent.com/assets/3134360/6342085/4d7c86bc-bba1-11e4-928c-6742d18e3d26.png

Source:

https://cloud.githubusercontent.com/assets/3134360/6342095/62592ae0-bba1-11e4-83f8-72cbe6436149.png

**Comment by PolarisBeaver** [comment]
I think now I see what happened. Don't stress out about it too much, you did well. In short, Photoshop kept leaving silly little fragments of red around your source file because the magic wand and paint bucket tools do that, so really not your fault here, I didn't realize you were working from the original iTunes icon. Some aliasing happened on the top and bottom edges but I fixed that.

The only major thing here was just making sure the icon was filling the canvas space, ignore what I said about not scaling, I didn't think that step through.

I would like you to have credit for the icon though, even though I corrected the issues.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6343342/d00814e4-bb9b-11e4-92ff-9ca4862dbcf1.png)

https://cloud.githubusercontent.com/assets/10394552/6343342/d00814e4-bb9b-11e4-92ff-9ca4862dbcf1.png

Source (corrected red edges, filled canvas):

https://cloud.githubusercontent.com/assets/10394552/6343339/bac11748-bb9b-11e4-9928-0045faca23b1.png

**Comment by MagnaMike** [comment]
@PolarisBeaver Great stuff! :smile: Even I learned something (the alt click and drag for layer style). As for making a wiki page, I'm not sure if you would be able to unless you are a designated collaborator to the repo (hint hint @dreamnet ?). I don't know though, so [click here](https://github.com/glasklart/hd/wiki), do you see the green new page button at the top right?

**Comment by dreamnet** [comment]
@MagnaMike @PolarisBeaver I can't add new members to [the team](https://github.com/orgs/glasklart/teams). I think only the owners can do this.
I add this icon and close this issue, because I want to push out a new release today. Discussion can go on in #1138.
