### ISSUE TITLE
LEGO® Star Wars™:  The Complete Saga

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5242]
**App Name:** LEGO® Star Wars™:  The Complete Saga
**Bundle ID:** com.wb.LEGOStarWars
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=727420266">727420266</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lego-star-wars-complete-saga/id727420266?mt=8&uo=4">https://itunes.apple.com/us/app/lego-star-wars-complete-saga/id727420266?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Warner Bros. Entertainment
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/warner-bros./id298372283?uo=4>© Warner Bros.</a>
**Supported Devices:** iPadThirdGen, iPadThirdGen4G, iPhone5, iPadFourthGen, iPhone6, iPhone6Plus, iPadMini, iPadFourthGen4G, iPad2Wifi, iPad23G, iPadMini4G, iPhone5s, iPhone4, iPhone5c, iPodTouchFifthGen, iPhone4S, iPodTouchFourthGen
**Original Artwork:**
<img src="http://a227.phobos.apple.com/us/r30/Purple3/v4/c9/29/28/c929285d-bce2-82b5-3246-54463d97d54c/mzl.ddflmtdb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6498424/cbd6db92-c2b9-11e4-9077-667583845888.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6471965/787a949a-c1ef-11e4-97bb-7644a963d9f9.png)
https://cloud.githubusercontent.com/assets/2068130/6471965/787a949a-c1ef-11e4-97bb-7644a963d9f9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6471990/89f5ee86-c1ef-11e4-82f2-e4f7f8361b01.png

**Comment by zmathiasz** [comment]
Looks good to me. :+1:

**Comment by MagnaMike** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6497896/a01d8e34-c2b3-11e4-9a2a-310dbf744bc1.png)
https://cloud.githubusercontent.com/assets/2236254/6497896/a01d8e34-c2b3-11e4-9a2a-310dbf744bc1.png

---
Source: (rough around the edges...)
https://cloud.githubusercontent.com/assets/2236254/6497894/9b908c72-c2b3-11e4-9dd8-63398bdf94c1.png

**Comment by zmathiasz** [comment]
I like it with the Jedi. :)

**Comment by dreamnet** [comment]
@MagnaMike :+1:
