### ISSUE TITLE
Game of War - Fire Age

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5243]
**App Name:** Game of War - Fire Age
**Bundle ID:** com.machinezone.ody0
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=667728512">667728512</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/game-of-war-fire-age/id667728512?mt=8&uo=4">https://itunes.apple.com/us/app/game-of-war-fire-age/id667728512?mt=8&uo=4</a>
**App Version:** 2.12
**Seller:** Machine Zone, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/machine-zone-inc/id299968102?mt=8&uo=4>© Machine Zone, Inc</a>
**Supported Devices:** iPadWifi, iPadThirdGen, iPodTouchThirdGen, iPadFourthGen, iPad23G, iPadMini, iPhone6Plus, iPhone5s, iPadFourthGen4G, iPad2Wifi, iPhone4S, iPad3G, iPodTouchFifthGen, iPadThirdGen4G, iPhone4, iPhone6, iPhone-3GS, iPadMini4G, iPhone5c, iPhone5, iPodTouchFourthGen
**Original Artwork:**
<img src="http://a472.phobos.apple.com/us/r30/Purple3/v4/05/db/6d/05db6dc9-63c5-a332-6255-61fcf43033bf/mzl.hwhtohqa.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6651051/a9ae9486-ca31-11e4-94fb-201ad3b9d1dc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6651051/a9ae9486-ca31-11e4-94fb-201ad3b9d1dc.png)
https://cloud.githubusercontent.com/assets/2068130/6651051/a9ae9486-ca31-11e4-94fb-201ad3b9d1dc.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6651054/bc8d457a-ca31-11e4-92ba-2d58723db2b3.png

**Comment by MagnaMike** [comment]
@dreamnet Well done :+1:
