### ISSUE TITLE
Dawn of Magic

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5244]
**App Name:** Dawn of Magic
**Bundle ID:** com.gameislive.dawn.of.magic.en
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=471677792">471677792</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dawn-of-magic/id471677792?mt=8&uo=4">https://itunes.apple.com/us/app/dawn-of-magic/id471677792?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** LAKOO GAMES LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/lakoo/id353949069?uo=4>© Lakoo</a>
**Supported Devices:** iPadMini4G, iPad23G, iPadFourthGen, iPhone6, iPodTouchFourthGen, iPhone5s, iPhone-3G, iPhone5, iPadFourthGen4G, iPhone4, iPod-touch, iPadThirdGen, iPhone4S, iPad2Wifi, iPodTouchThirdGen, iPadWifi, iPhone-3GS, iPhone, iPod-touch-with-mic, iPhone6Plus, iPhone5c, iPad3G, iPodTouchFifthGen, iPadThirdGen4G, iPadMini
**Original Artwork:**
<img src="http://a1610.phobos.apple.com/us/r30/Purple/v4/60/23/79/602379a6-a83e-0158-afa3-8ee2957c2845/mzl.dllezbgr.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6405703/b2a4cf5e-bdf4-11e4-9b02-735e943e406b.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6385071/16d4c956-bd33-11e4-851e-a25a7cea823a.png)
https://cloud.githubusercontent.com/assets/10950389/6385071/16d4c956-bd33-11e4-851e-a25a7cea823a.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6385074/3a6b8346-bd33-11e4-99fb-83bc98f11e34.png

**Comment by dreamnet** [comment]
@zmathiasz Yeah, looks great, the only thing that disturbs the icon is the logo at the right bottom. I know we alsways say as close as possibe to the original, but I think this icon wold better without the logo.

**Comment by zmathiasz** [comment]
I plan on redoing it this afternoon. Something about it doesn't sit right. LOL.

**Comment by dreamnet** [comment]
Here is a slightly overworked source, but it's still not right....
https://cloud.githubusercontent.com/assets/2068130/6402340/203f74da-be07-11e4-8d18-aeb5ab9aff9e.png

**Comment by zmathiasz** [comment]
I like the added hand. Maybe a tweak on the fingers. The icon does have one buried under the blue magic thingy so that makes sense. :)

**Comment by zmathiasz** [comment]
I expanded her a bit more from some of the other offical artwork that was used for the icon.  I could always zoom in to make her fuller but I like the way it looks.  Input?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6405703/b2a4cf5e-bdf4-11e4-9b02-735e943e406b.png)
https://cloud.githubusercontent.com/assets/10950389/6405703/b2a4cf5e-bdf4-11e4-9b02-735e943e406b.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6405706/bf1e0ade-bdf4-11e4-84be-1a2f0598c7ce.png

**Comment by dreamnet** [comment]
@zmathiasz That's because I am using Adobe Illustrator for the sources. I open the source png with Illustrator, then vectorize it and export it to png.
Your last icon looks great, I take it. :+1:
