### ISSUE TITLE
Doodle God™

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5245]
**App Name:** Doodle God™
**Bundle ID:** com.joybits.iAlchemy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376374689">376374689</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/doodle-god/id376374689?mt=8&uo=4">https://itunes.apple.com/us/app/doodle-god/id376374689?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** JoyBits Co Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/joybits-ltd./id375374774?uo=4>© JoyBits Ltd.</a>
**Supported Devices:** iPhone6, iPadFourthGen, iPodTouchFourthGen, iPhone4S, iPhone4, iPadMini, iPadMini4G, iPhone5c, iPhone5, iPodTouchFifthGen, iPhone5s, iPad2Wifi, iPadThirdGen4G, iPadThirdGen, iPadFourthGen4G, iPad23G, iPhone6Plus, iPhone-3GS
**Original Artwork:**
<img src="http://a2.phobos.apple.com/us/r30/Purple1/v4/3a/c4/b2/3ac4b2d9-2fc6-fbc1-e7c1-51506242318c/pr_source.png?downloadKey=1424670565_634b0ef160155a9e04ddd63790d3f083" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6322197/7a3954c4-badd-11e4-87c4-a1822cb0bce5.png)

**Comment by zmathiasz** [comment]
**Non-Holiday Artwork:**
<img src="https://cloud.githubusercontent.com/assets/10950389/6322174/26550e0c-badd-11e4-9448-a93eef090dad.png" width="150" height="150" />

**Comment by zmathiasz** [comment]
I feel the non-holiday artwork gives it a longer shelf life without having to constantly update the icon within Glasklart.  :+1: 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6322197/7a3954c4-badd-11e4-87c4-a1822cb0bce5.png)
https://cloud.githubusercontent.com/assets/10950389/6322197/7a3954c4-badd-11e4-87c4-a1822cb0bce5.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6322205/9432b7a8-badd-11e4-9422-065f170ab119.png

**Comment by PolarisBeaver** [comment]
Agreed, and looks good!

**Comment by dreamnet** [comment]
@zmathiasz Jup, good! :+1:
