### ISSUE TITLE
SamRemote remote for Samsung TV

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5246]
**App Name:** SamRemote remote for Samsung TV
**Bundle ID:** com.teix.SG
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=838579136">838579136</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/samremote-remote-for-samsung/id838579136?mt=8&uo=4">https://itunes.apple.com/us/app/samremote-remote-for-samsung/id838579136?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** yohan teixeira
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/yohan-teixeira/id488660484?uo=4>© yohan teixeira</a>
**Supported Devices:** iPhone4, iPadFourthGen, iPhone-3GS, iPodTouchFifthGen, iPadMini4G, iPad23G, iPodTouchFourthGen, iPadThirdGen, iPhone6Plus, iPhone5c, iPhone5, iPadThirdGen4G, iPhone4S, iPhone5s, iPhone6, iPadFourthGen4G, iPad2Wifi, iPadMini
**Original Artwork:**
<img src="http://a733.phobos.apple.com/us/r30/Purple3/v4/0c/cb/f0/0ccbf0c3-9d56-abbc-1ed8-81754748f11f/mzl.mylwsgsl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6358688/b935f5b0-bc6d-11e4-9e4e-59d0fcedd03e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6358688/b935f5b0-bc6d-11e4-9e4e-59d0fcedd03e.png)
https://cloud.githubusercontent.com/assets/2068130/6358688/b935f5b0-bc6d-11e4-9e4e-59d0fcedd03e.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6358695/c74ff290-bc6d-11e4-981a-98ae024d4c62.png
