### ISSUE TITLE
Chicago Travel Guide (with Offline Maps) - mTrip

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5247]
**App Name:** Chicago Travel Guide (with Offline Maps) - mTrip
**Bundle ID:** com.mtrip.Chicago
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377136209">377136209</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chicago-travel-guide-offline/id377136209?mt=8&uo=4">https://itunes.apple.com/us/app/chicago-travel-guide-offline/id377136209?mt=8&uo=4</a>
**App Version:** 2.6.1
**Seller:** mTrip Travel Guide
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mtrip-travel-guides/id377126417?uo=4>© mTrip Travel Guides</a>
**Supported Devices:** iPadThirdGen4G, iPhone5c, iPhone5s, iPhone6, iPodTouchFifthGen, iPhone4S, iPad2Wifi, iPadThirdGen, iPhone6Plus, iPad23G, iPadMini, iPadMini4G, iPhone5, iPadFourthGen4G, iPhone4, iPadFourthGen
**Original Artwork:**
<img src="http://a1213.phobos.apple.com/us/r30/Purple3/v4/20/b8/6e/20b86ee7-22fd-2d03-53a7-c750939f0e85/mzl.aabbewjk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7872539/7936ec0a-055e-11e5-8b3e-aa4b2ac5cead.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6358022/0d505e7e-bc69-11e4-9296-3dbae0e1f527.png)
https://cloud.githubusercontent.com/assets/2068130/6358022/0d505e7e-bc69-11e4-9296-3dbae0e1f527.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6358032/1ab404d0-bc69-11e4-9e09-e42e42601b7d.png

**Comment by ivanov007** [comment]
as requested, here's the new icon to match all the other mTrip apps
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7872539/7936ec0a-055e-11e5-8b3e-aa4b2ac5cead.png)
https://cloud.githubusercontent.com/assets/3090247/7872539/7936ec0a-055e-11e5-8b3e-aa4b2ac5cead.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7872540/793eb296-055e-11e5-8d16-fa51c8d7e267.png

**Comment by katakolo** [comment]
Excellent, thanx very much!
