### ISSUE TITLE
Verizon FiOS Mobile

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5248]
**App Name:** Verizon FiOS Mobile
**Bundle ID:** com.verizon.ams.dvr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406387206">406387206</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/verizon-fios-mobile/id406387206?mt=8&uo=4">https://itunes.apple.com/us/app/verizon-fios-mobile/id406387206?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Verizon Services Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/verizon-services-corporation/id663838713?uo=4>© Verizon Services Corporation</a>
**Supported Devices:** iPhone6Plus, iPhone6, iPadFourthGen, iPadThirdGen4G, iPhone5, iPadMini4G, iPad23G, iPodTouchFourthGen, iPadMini, iPadFourthGen4G, iPhone-3GS, iPadThirdGen, iPodTouchFifthGen, iPhone4S, iPad2Wifi, iPhone4, iPhone5c, iPhone5s
**Original Artwork:**
<img src="http://a1485.phobos.apple.com/us/r30/Purple5/v4/7b/bb/c5/7bbbc5f1-fb95-d9b4-130e-e6f6117a039a/mzl.tyotxuis.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6357561/a62f2d04-bc65-11e4-866c-c387ca7b1d1b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6357561/a62f2d04-bc65-11e4-866c-c387ca7b1d1b.png)
https://cloud.githubusercontent.com/assets/2068130/6357561/a62f2d04-bc65-11e4-866c-c387ca7b1d1b.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6357568/b366d5d0-bc65-11e4-855c-8552916b5ab2.png
