### ISSUE TITLE
Ελληνική Τηλεόραση

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5249]
**App Name:** Ελληνική Τηλεόραση
**Bundle ID:** com.krtlivapps.greekccc1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=890458796">890458796</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ellenike-teleorase/id890458796?mt=8&uo=4">https://itunes.apple.com/us/app/ellenike-teleorase/id890458796?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Kyriakos Leivadas
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kyriakos-leivadas/id537179532?uo=4>© Kyriakos Leivadas</a>
**Supported Devices:** iPhone5s, iPodTouchFifthGen, iPadFourthGen, iPadThirdGen, iPadMini, iPhone6, iPadFourthGen4G, iPhone4S, iPhone6Plus, iPadThirdGen4G, iPhone5c, iPad2Wifi, iPad23G, iPadMini4G, iPhone4, iPhone5
**Original Artwork:**
<img src="http://a808.phobos.apple.com/us/r30/Purple5/v4/4f/59/00/4f590029-0089-5b96-5a9e-41005224f4c4/mzl.xwynkldm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6357892/f402793a-bc67-11e4-924a-7f9cb0bf1a92.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6357892/f402793a-bc67-11e4-924a-7f9cb0bf1a92.png)
https://cloud.githubusercontent.com/assets/2068130/6357892/f402793a-bc67-11e4-924a-7f9cb0bf1a92.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6357897/04c7b05a-bc68-11e4-8b6e-9975ceae761b.png
