### ISSUE TITLE
Breathing Zone

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5250]
**App Name:** Breathing Zone
**Bundle ID:** com.breathing-zone.breathing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=369838631">369838631</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/breathing-zone/id369838631?uo=4">https://apps.apple.com/us/app/breathing-zone/id369838631?uo=4</a>
**App Version:** 4.9
**Seller:** Breathing Zone Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/breathing-zone/id369838634?uo=4">© Breathing Zone</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/e4/5a/4b/e45a4b96-12ab-d723-9d49-3b7951ef62bd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981288-68dda280-9601-11e9-9c77-a33f2bf68ba5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6357486/2663b05e-bc65-11e4-8937-7d5a0980bff1.png)
https://cloud.githubusercontent.com/assets/2068130/6357486/2663b05e-bc65-11e4-8937-7d5a0980bff1.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6357490/33d4a720-bc65-11e4-87b9-0f29171d0f8b.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981288-68dda280-9601-11e9-9c77-a33f2bf68ba5.png)
https://user-images.githubusercontent.com/2068130/59981288-68dda280-9601-11e9-9c77-a33f2bf68ba5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59981295-7abf4580-9601-11e9-8601-5b80dc5656f9.png
