### ISSUE TITLE
Zagat - Restaurant reviews, trusted ratings, photos, new places, best-of lists, neighborhood guide

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5251]
**App Name:** Zagat - Restaurant reviews, trusted ratings, photos, new places, best-of lists, neighborhood guide
**Bundle ID:** com.google.zagat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=669821485">669821485</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zagat-restaurant-reviews-trusted/id669821485?mt=8&uo=4">https://itunes.apple.com/us/app/zagat-restaurant-reviews-trusted/id669821485?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/86/2a/e4/862ae47f-a047-0c28-fca8-25081f8bbffe/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268229/4946a436-5625-11e6-9d83-c2870bd5d700.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6357428/b2473542-bc64-11e4-9c2c-d8e921a2f714.png)
https://cloud.githubusercontent.com/assets/2068130/6357428/b2473542-bc64-11e4-9c2c-d8e921a2f714.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6357435/be92a192-bc64-11e4-907c-72e272cb5047.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Zagat - Restaurant reviews, trusted ratings, photos, new places, best-of lists, neighborhood guide
**Bundle ID:** com.google.zagat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=669821485">669821485</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zagat-restaurant-reviews-trusted/id669821485?mt=8&uo=4">https://itunes.apple.com/us/app/zagat-restaurant-reviews-trusted/id669821485?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/86/2a/e4/862ae47f-a047-0c28-fca8-25081f8bbffe/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268229/4946a436-5625-11e6-9d83-c2870bd5d700.png)
https://cloud.githubusercontent.com/assets/2068130/17268229/4946a436-5625-11e6-9d83-c2870bd5d700.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268230/5763380e-5625-11e6-8cf1-03701b332b1d.png
