### ISSUE TITLE
New York Subway MTA Map and Route Planner

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5252]
**App Name:** New York Subway MTA Map and Route Planner
**Bundle ID:** uk.co.mxdata.NewYorkSubwayMap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=369691844">369691844</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-york-subway-mta-map-route/id369691844?mt=8&uo=4">https://itunes.apple.com/us/app/new-york-subway-mta-map-route/id369691844?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** mxData Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mxdata-limited/id320969615?uo=4>© mxData Limited</a>
**Supported Devices:** iPhone5, iPadThirdGen, iPadMini4G, iPadThirdGen4G, iPadFourthGen4G, iPadMini, iPhone6Plus, iPhone4, iPhone6, iPadFourthGen, iPad2Wifi, iPhone4S, iPhone5s, iPodTouchFifthGen, iPhone5c, iPad23G
**Original Artwork:**
<img src="http://a110.phobos.apple.com/us/r30/Purple5/v4/58/cc/28/58cc284c-209f-0de7-0977-07493e4dc4df/mzl.lsrplfiu.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6358221/559622d0-bc6a-11e4-9ac1-9691da01cfa2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6358221/559622d0-bc6a-11e4-9ac1-9691da01cfa2.png)
https://cloud.githubusercontent.com/assets/2068130/6358221/559622d0-bc6a-11e4-9ac1-9691da01cfa2.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6358227/66c6519c-bc6a-11e4-84f6-116e3dd43422.png
