### ISSUE TITLE
Official New York Jets

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5253]
**App Name:** Official New York Jets
**Bundle ID:** com.yinzcam.nfl.nyj
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=460494117">460494117</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/official-new-york-jets/id460494117?mt=8&uo=4">https://itunes.apple.com/us/app/official-new-york-jets/id460494117?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** New York Jets LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/new-york-jets/id413062701?uo=4>© New York Jets</a>
**Supported Devices:** iPadFourthGen4G, iPhone4, iPad2Wifi, iPhone6, iPadMini, iPhone5s, iPadFourthGen, iPadThirdGen4G, iPodTouchFifthGen, iPhone6Plus, iPadThirdGen, iPad23G, iPhone4S, iPhone5c, iPhone5, iPadMini4G
**Original Artwork:**
<img src="http://a1183.phobos.apple.com/us/r30/Purple5/v4/7c/e4/c2/7ce4c2e9-6d81-4ddf-540f-594405267b2e/mzl.spngsfcw.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6357332/f1b8d600-bc63-11e4-96c2-a66f66051c98.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6357256/53dd6086-bc63-11e4-85fa-f3055b86dfb0.png)
https://cloud.githubusercontent.com/assets/2068130/6357256/53dd6086-bc63-11e4-85fa-f3055b86dfb0.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6357266/60f01084-bc63-11e4-8e40-e363721195b3.png
