### ISSUE TITLE
HowAboutWe

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5254]
**App Name:** HowAboutWe
**Bundle ID:** com.howaboutwe.HowAboutWe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=439078709">439078709</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/howaboutwe/id439078709?mt=8&uo=4">https://itunes.apple.com/us/app/howaboutwe/id439078709?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** This Life, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/howaboutwe/id439078712?uo=4>© HowAboutWe</a>
**Supported Devices:** iPad23G, iPadThirdGen4G, iPadFourthGen4G, iPhone6, iPadMini4G, iPhone6Plus, iPhone5s, iPadThirdGen, iPadMini, iPhone5c, iPhone4S, iPhone4, iPad2Wifi, iPhone5, iPodTouchFifthGen, iPadFourthGen
**Original Artwork:**
<img src="http://a63.phobos.apple.com/us/r30/Purple3/v4/56/9b/49/569b4961-fe62-ea0b-7e2c-4a3d4eb31009/mzl.aocmipxf.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6357191/ca25250e-bc62-11e4-90c5-d2f5b74c9cbb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6357191/ca25250e-bc62-11e4-90c5-d2f5b74c9cbb.png)
https://cloud.githubusercontent.com/assets/2068130/6357191/ca25250e-bc62-11e4-90c5-d2f5b74c9cbb.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6357198/d7670d0e-bc62-11e4-9295-0c67309969c8.png
