### ISSUE TITLE
Governor of Poker 2 - Texas Holdem Poker without internet

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5255]
**App Name:** Governor of Poker 2 - Texas Holdem Poker without internet
**Bundle ID:** com.youdagames.gop2free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=532497159">532497159</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/governor-poker-2-texas-holdem/id532497159?mt=8&uo=4">https://itunes.apple.com/us/app/governor-poker-2-texas-holdem/id532497159?mt=8&uo=4</a>
**App Version:** 1.8.7
**Seller:** Youda Games Holding B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/youda-games-holding-b.v./id342462146?uo=4>© Youda Games Holding B.V.</a>
**Supported Devices:** iPadMini, iPadFourthGen, iPadThirdGen4G, iPhone5c, iPad23G, iPadFourthGen4G, iPhone4S, iPad2Wifi, iPhone6Plus, iPhone5s, iPadThirdGen, iPhone4, iPadMini4G, iPhone-3GS, iPodTouchFifthGen, iPhone6, iPhone5, iPodTouchFourthGen
**Original Artwork:**
<img src="http://a1687.phobos.apple.com/us/r30/Purple1/v4/fd/87/aa/fd87aa2d-6f93-aa2f-93da-ed574ff704aa/mzl.capruzjv.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6541246/5fa54fda-c4c6-11e4-9813-0b2047fda780.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6541246/5fa54fda-c4c6-11e4-9813-0b2047fda780.png)
https://cloud.githubusercontent.com/assets/2068130/6541246/5fa54fda-c4c6-11e4-9813-0b2047fda780.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6541248/70454a70-c4c6-11e4-8974-0766f7626a1c.png

**Comment by MagnaMike** [comment]
@dreamnet Nice! :+1:
