### ISSUE TITLE
Airport Madness Challenge

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5256]
**App Name:** Airport Madness Challenge
**Bundle ID:** com.fluik.AirportChallenge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393575110">393575110</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/airport-madness-challenge/id393575110?mt=8&uo=4">https://itunes.apple.com/us/app/airport-madness-challenge/id393575110?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** Fluik Entertainment Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fluik/id341885018?uo=4>© Fluik</a>
**Supported Devices:** iPadMini4G, iPhone5c, iPadFourthGen, iPadMini, iPadFourthGen4G, iPhone5s, iPhone5, iPodTouchFifthGen, iPhone6Plus, iPhone-3GS, iPodTouchFourthGen, iPadThirdGen4G, iPad2Wifi, iPhone6, iPhone4, iPad23G, iPhone4S, iPadThirdGen
**Original Artwork:**
<img src="http://a1205.phobos.apple.com/us/r30/Purple1/v4/7c/aa/99/7caa9984-5fcb-37cb-75d9-daa4d87e2608/mzl.ecowhfxr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6360461/66a3ff10-bc7a-11e4-9799-34265636a2c4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6360461/66a3ff10-bc7a-11e4-9799-34265636a2c4.png)
https://cloud.githubusercontent.com/assets/2068130/6360461/66a3ff10-bc7a-11e4-9799-34265636a2c4.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6360469/743d9096-bc7a-11e4-8eff-9a0e6e69ea70.png
