### ISSUE TITLE
Numerity - Find images in numbers

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5258]
**App Name:** Numerity - Find images in numbers
**Bundle ID:** com.zedarus.numerity
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=687075219">687075219</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/numerity-find-images-in-numbers/id687075219?mt=8&uo=4">https://itunes.apple.com/us/app/numerity-find-images-in-numbers/id687075219?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** Zedarus Entertainment Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/zedarus-entertainment-ltd./id687075222?uo=4>© Zedarus Entertainment Ltd.</a>
**Supported Devices:** iPhone-3GS, iPadFourthGen4G, iPodTouchFifthGen, iPhone5, iPhone6Plus, iPad2Wifi, iPhone5s, iPadThirdGen, iPodTouchFourthGen, iPadMini4G, iPadThirdGen4G, iPhone4S, iPhone6, iPad23G, iPhone4, iPhone5c, iPadFourthGen, iPadMini
**Original Artwork:**
<img src="http://a1925.phobos.apple.com/us/r30/Purple2/v4/16/71/52/16715269-a5dd-1a56-4837-620d34c8c5fb/mzl.xdrgkrxs.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6362204/377b7468-bc50-11e4-87f1-f0b6c7ddd13e.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6362204/377b7468-bc50-11e4-87f1-f0b6c7ddd13e.png)
https://cloud.githubusercontent.com/assets/3090247/6362204/377b7468-bc50-11e4-87f1-f0b6c7ddd13e.png

**Comment by dreamnet** [comment]
@ivanov007 Jup! :+1:
