### ISSUE TITLE
BabyBump Pregnancy Free

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5259]
**App Name:** BabyBump Pregnancy Free
**Bundle ID:** com.alt12.babybumpfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389089619">389089619</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/babybump-pregnancy-free/id389089619?mt=8&uo=4">https://itunes.apple.com/us/app/babybump-pregnancy-free/id389089619?mt=8&uo=4</a>
**App Version:** 7.5.0
**Seller:** Alt12 Apps, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/alt12-apps-llc/id332366278?uo=4>© Alt12 Apps, LLC</a>
**Supported Devices:** iPhone4S, iPhone4, iPadThirdGen4G, iPhone6Plus, iPhone5c, iPadFourthGen, iPadMini4G, iPadThirdGen, iPadFourthGen4G, iPhone5, iPodTouchFifthGen, iPhone6, iPad2Wifi, iPad23G, iPhone5s, iPadMini
**Original Artwork:**
<img src="http://a450.phobos.apple.com/us/r30/Purple3/v4/8c/0b/c8/8c0bc8d5-96e8-60a3-11f9-1e3fc68f36f7/mzl.gptsvrdq.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6362856/d39cefba-bc56-11e4-905a-ccd11d79dabb.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6362856/d39cefba-bc56-11e4-905a-ccd11d79dabb.png)
https://cloud.githubusercontent.com/assets/3090247/6362856/d39cefba-bc56-11e4-905a-ccd11d79dabb.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/6362864/f65d795c-bc56-11e4-9ef5-f4d3ed243864.png

**Comment by dreamnet** [comment]
@ivanov007 Is there something on it's way? :baby: :baby_bottle: :grin:

**Comment by ivanov007** [comment]
haha as a matter of fact... yes :wink:

**Comment by dreamnet** [comment]
Ah! So... I wish you all the very best! :family:

**Comment by ivanov007** [comment]
thanks :smile:
