### ISSUE TITLE
Analytiks - Google Analytics website stats, infographics, social media

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#526]
**App Name:** Analytiks - Google Analytics website stats, infographics, social media
**Bundle ID:** com.stelabouras.analytiks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427268553">427268553</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/analytiks-google-analytics/id427268553?mt=8&uo=4">https://itunes.apple.com/us/app/analytiks-google-analytics/id427268553?mt=8&uo=4</a>
**App Version:** 3.0.7
**Seller:** Moshe Shladov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/moshe-shladov/id1082324250?uo=4>© Moshe Shladov</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/59/e3/cc/59e3cc00-34f4-f09e-0ceb-6237d216cce6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18848274/dc52dcc8-842d-11e6-9478-87e6c3178a79.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18848274/dc52dcc8-842d-11e6-9478-87e6c3178a79.png)
https://cloud.githubusercontent.com/assets/2068130/18848274/dc52dcc8-842d-11e6-9478-87e6c3178a79.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18848290/e9c05a20-842d-11e6-8c99-fbe02f0eb1d2.png
