### ISSUE TITLE
Darkroom – Photo Editor

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5262]
**App Name:** Darkroom – Photo Editor
**Bundle ID:** co.bergen.Darkroom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953286746">953286746</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/darkroom-photo-editor/id953286746?mt=8&uo=4">https://itunes.apple.com/us/app/darkroom-photo-editor/id953286746?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Bergen Co.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bergen-co./id953286745?uo=4>© Bergen Co.</a>
**Supported Devices:** iPodTouchFifthGen, iPadFourthGen, iPhone5c, iPhone6Plus, iPadThirdGen4G, iPhone5, iPad2Wifi, iPhone6, iPad23G, iPhone4S, iPadFourthGen4G, iPadMini, iPadMini4G, iPadThirdGen, iPhone5s
**Original Artwork:**
<img src="http://a657.phobos.apple.com/us/r30/Purple3/v4/e6/89/a4/e689a4c7-d0d9-eb14-5c37-e6acaae8768f/mzl.nbdkkgxu.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6405627/d8a4a0cc-bdf3-11e4-96f7-f8009a8e7c05.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6405618/bf46e270-bdf3-11e4-9815-bd087cb4fb92.png)
https://cloud.githubusercontent.com/assets/2236254/6405618/bf46e270-bdf3-11e4-9815-bd087cb4fb92.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6405619/c0d17cb8-bdf3-11e4-8454-2b135b579799.png
