### ISSUE TITLE
FlashAir

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5263]
**App Name:** FlashAir
**Bundle ID:** jp.co.toshiba.FlashAir
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=630414772">630414772</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flashair/id630414772?mt=8&uo=4">https://itunes.apple.com/us/app/flashair/id630414772?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** TOSHIBA Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/toshiba-corp./id390607984?uo=4>© TOSHIBA Corp.</a>
**Supported Devices:** iPadFourthGen, iPhone4S, iPadThirdGen4G, iPadMini4G, iPhone6, iPadThirdGen, iPhone6Plus, iPadMini, iPhone-3GS, iPodTouchFourthGen, iPhone5, iPhone4, iPodTouchFifthGen, iPad2Wifi, iPhone5s, iPhone5c, iPadFourthGen4G, iPad23G
**Original Artwork:**
<img src="http://a1549.phobos.apple.com/us/r30/Purple3/v4/c8/34/25/c8342588-44c8-a64c-820c-ff437571e775/mzl.pelojsxl.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6405615/ae337f98-bdf3-11e4-937e-299b61c7ec87.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6405609/91dda68e-bdf3-11e4-9bc9-3ec543b6158a.png)
https://cloud.githubusercontent.com/assets/2236254/6405609/91dda68e-bdf3-11e4-9bc9-3ec543b6158a.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6405607/905525b2-bdf3-11e4-826d-70b487e79d05.png
