### ISSUE TITLE
Noodle Box

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5264]
**App Name:** Noodle Box
**Bundle ID:** au.com.noqapps.noodlebox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=816046389">816046389</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/noodle-box/id816046389?mt=8&uo=4">https://itunes.apple.com/us/app/noodle-box/id816046389?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** NoQ Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/noq-pty-ltd/id453650296?uo=4>© NoQ Pty Ltd</a>
**Supported Devices:** iPhone5s, iPadFourthGen, iPad2Wifi, iPadFourthGen4G, iPadThirdGen4G, iPad23G, iPhone6, iPhone6Plus, iPhone-3GS, iPadMini, iPodTouchFifthGen, iPadMini4G, iPhone4, iPhone4S, iPadThirdGen, iPhone5, iPhone5c, iPodTouchFourthGen
**Original Artwork:**
<img src="http://a876.phobos.apple.com/us/r30/Purple3/v4/b5/fc/49/b5fc49ca-8eca-d84a-f88a-9827c275b619/mzl.gnpyaiab.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6405594/65022f86-bdf3-11e4-880e-eee8402be8eb.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6405594/65022f86-bdf3-11e4-880e-eee8402be8eb.png)
https://cloud.githubusercontent.com/assets/2236254/6405594/65022f86-bdf3-11e4-880e-eee8402be8eb.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6405593/62b55bd6-bdf3-11e4-8024-698fde1340e5.png
