### ISSUE TITLE
Alto's Adventure

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5265]
**App Name:** Alto's Adventure
**Bundle ID:** com.snowman.alto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=950812012">950812012</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/altos-adventure/id950812012?mt=8&uo=4">https://itunes.apple.com/us/app/altos-adventure/id950812012?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Snowman
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/snowman/id524873456?uo=4>© Snowman</a>
**Supported Devices:** iPhone5s, iPhone6, iPadFourthGen, iPadThirdGen4G, iPhone4S, iPhone5, iPadMini, iPodTouchFifthGen, iPadMini4G, iPhone4, iPad23G, iPhone5c, iPhone6Plus, iPad2Wifi, iPadThirdGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://a363.phobos.apple.com/us/r30/Purple1/v4/b1/81/06/b18106d2-26f2-c000-1fe6-8c62f0ed4989/pr_source.png?downloadKey=1425006771_690f7ace7f432f251db4888e60606370" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6420648/2c29aa38-bec8-11e4-90f8-264adce06442.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6405766/9ce958fa-bdf5-11e4-8c33-78ed6b173537.png)
https://cloud.githubusercontent.com/assets/2236254/6405766/9ce958fa-bdf5-11e4-8c33-78ed6b173537.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6405770/aaf04bb6-bdf5-11e4-8045-25b33d46270b.png

**Comment by dreamnet** [comment]
Alternative:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6420648/2c29aa38-bec8-11e4-90f8-264adce06442.png)
https://cloud.githubusercontent.com/assets/2068130/6420648/2c29aa38-bec8-11e4-90f8-264adce06442.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6420654/3a8a8296-bec8-11e4-8c39-2d65c487691b.png

**Comment by MagnaMike** [comment]
@dreamnet Sure, let's go with yours. :+1:
