### ISSUE TITLE
Monster Mania TD: First Strike

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5268]
**App Name:** Monster Mania TD: First Strike
**Bundle ID:** com.toccata.technologies.general.TowerDefence02
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=919372024">919372024</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/monster-mania-td-first-strike/id919372024?mt=8&uo=4">https://itunes.apple.com/us/app/monster-mania-td-first-strike/id919372024?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Toccata Technologies Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/toccata-technologies-inc./id329746565?uo=4>© Toccata Technologies Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone5, iPodTouchFourthGen, iPadMini, iPodTouchFifthGen, iPhone5s, iPhone4S, iPad23G, iPhone5c, iPhone4, iPadFourthGen4G, iPadFourthGen, iPadThirdGen, iPhone6Plus, iPadThirdGen4G, iPad2Wifi, iPhone6, iPadMini4G
**Original Artwork:**
<img src="http://a205.phobos.apple.com/us/r30/Purple5/v4/2a/f0/a1/2af0a145-c111-1dab-985e-6fdd6fac37d8/mzl.wsblcvwt.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6886815/aa6b9b88-d64a-11e4-867c-ed3e382c6e56.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6886815/aa6b9b88-d64a-11e4-867c-ed3e382c6e56.png)
https://cloud.githubusercontent.com/assets/2068130/6886815/aa6b9b88-d64a-11e4-867c-ed3e382c6e56.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6886820/b9d0dc6e-d64a-11e4-8132-49894a10caf2.png

**Comment by ivanov007** [comment]
@dreamnet wow nice one :+1: , it was one of those nearly impossible icons, and I though it will be closed that way

**Comment by dreamnet** [comment]
@ivanov007 Yes, this on cost me about one hour to do....
