### ISSUE TITLE
Notebook Wars Saga

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5271]
**App Name:** Notebook Wars Saga
**Bundle ID:** com.matakukos.notebookWars
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=927106188">927106188</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/notebook-wars-saga/id927106188?mt=8&uo=4">https://itunes.apple.com/us/app/notebook-wars-saga/id927106188?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Francisco Ferreres Garcia
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/francisco-ferreres/id447611290?uo=4>© Francisco Ferreres</a>
**Supported Devices:** iPhone5, iPadThirdGen, iPhone5c, iPhone5s, iPadThirdGen4G, iPad2Wifi, iPhone4S, iPadFourthGen4G, iPhone6Plus, iPadFourthGen, iPhone4, iPadMini, iPhone6, iPadMini4G, iPodTouchFifthGen, iPad23G
**Original Artwork:**
<img src="http://a131.phobos.apple.com/us/r30/Purple1/v4/e5/5a/11/e55a113f-e02e-7b4c-474f-17384e5646ba/mzl.rrhmaget.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6424797/3217644e-becd-11e4-817d-d8f075841f16.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6424797/3217644e-becd-11e4-817d-d8f075841f16.png)
https://cloud.githubusercontent.com/assets/3090247/6424797/3217644e-becd-11e4-817d-d8f075841f16.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/6424796/32151dc4-becd-11e4-9b35-b32513f2d97f.png

**Comment by dreamnet** [comment]
@ivanov007 Ummm, that's hard - I'm taking the one with the border.
