### ISSUE TITLE
Ραδιόφωνο

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5272]
**App Name:** Ραδιόφωνο
**Bundle ID:** com.George.RadioFono
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347365225">347365225</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radiophono/id347365225?mt=8&uo=4">https://itunes.apple.com/us/app/radiophono/id347365225?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** GEORGE blu
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/george-blu/id324677530?uo=4>© George Blu</a>
**Supported Devices:** iPhone5, iPodTouchFourthGen, iPhone5c, iPadWifi, iPadThirdGen4G, iPadMini, iPad23G, iPhone4, iPodTouchThirdGen, iPhone-3GS, iPhone6Plus, iPadFourthGen, iPadFourthGen4G, iPhone4S, iPadThirdGen, iPadMini4G, iPodTouchFifthGen, iPhone6, iPad3G, iPad2Wifi, iPhone5s
**Original Artwork:**
<img src="http://a793.phobos.apple.com/us/r30/Purple3/v4/bd/8a/cf/bd8acf0f-c881-cd84-6933-7b90b3b81210/pr_source.png?downloadKey=1425116068_8a239d06b6c9e263eb44f5a1cd9f8f75" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6427636/5169c4b8-bf86-11e4-8d34-5e5e149e4b9f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6427636/5169c4b8-bf86-11e4-8d34-5e5e149e4b9f.png)
https://cloud.githubusercontent.com/assets/2068130/6427636/5169c4b8-bf86-11e4-8d34-5e5e149e4b9f.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6427641/62e0d06a-bf86-11e4-9909-5b148d6f1a32.png
