### ISSUE TITLE
 iFighter 1945

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5273]
**App Name:** iFighter 1945
**Bundle ID:** com.epicforce.ifighter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386456392">386456392</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ifighter-1945/id386456392?mt=8&uo=4">https://itunes.apple.com/us/app/ifighter-1945/id386456392?mt=8&uo=4</a>
**App Version:** 1.15
**Seller:** EpicForce Entertainment Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/epicforce-entertainment-ltd./id323993011?uo=4>© EpicForce Entertainment Ltd.</a>
**Supported Devices:** iPad2Wifi, iPodTouchThirdGen, iPad3G, iPodTouchFourthGen, iPadFourthGen4G, iPadMini, iPadFourthGen, iPadWifi, iPodTouchFifthGen, iPadThirdGen4G, iPhone5, iPhone6, iPad23G, iPhone4, iPhone6Plus, iPhone5s, iPhone5c, iPadThirdGen, iPhone4S, iPadMini4G, iPhone-3GS
**Original Artwork:**
<img src="http://a849.phobos.apple.com/us/r30/Purple/v4/d5/ce/0b/d5ce0b26-a25f-4cfc-5504-dee079b26197/mzl.vcanfhzj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7302538/4fa77d80-e9ea-11e4-8a77-4a098a80c2ae.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/7173269/619ba07c-e42f-11e4-8885-6bec7301cf6d.png)
https://cloud.githubusercontent.com/assets/10008202/7173269/619ba07c-e42f-11e4-8885-6bec7301cf6d.png
**Source**
https://cloud.githubusercontent.com/assets/10008202/7173272/6d7bfd10-e42f-11e4-8a1f-2d43cadba0f5.png

**Comment by dreamnet** [comment]
Because the original icon seems to be impossible to do, here is the game logo:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7262648/9ed8c212-e87b-11e4-9030-97600dd02a71.png)
https://cloud.githubusercontent.com/assets/2068130/7262648/9ed8c212-e87b-11e4-9030-97600dd02a71.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7262656/aae2b3b0-e87b-11e4-8fd4-430066d72cbc.png

**Comment by dreamnet** [comment]
I take my icon for this until someone makes a better one.

**Comment by ivanov007** [comment]
@dreamnet agree :+1:
