### ISSUE TITLE
Grand Defense - Free Defense Games, Apps

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5274]
**App Name:** Grand Defense - Free Defense Games, Apps
**Bundle ID:** com.SBG.GrandDefense
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=437080806">437080806</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grand-defense-free-defense/id437080806?mt=8&uo=4">https://itunes.apple.com/us/app/grand-defense-free-defense/id437080806?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Vera Yeshchanka
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/free-hd-games/id427282043?uo=4>© Free HD Games</a>
**Supported Devices:** iPadThirdGen4G, iPhone-3GS, iPodTouchFifthGen, iPhone5, iPhone4S, iPodTouchThirdGen, iPadFourthGen, iPad23G, iPad3G, iPadMini4G, iPhone5s, iPhone4, iPhone5c, iPodTouchFourthGen, iPadMini, iPhone6, iPhone6Plus, iPadThirdGen, iPadWifi, iPadFourthGen4G, iPad2Wifi
**Original Artwork:**
<img src="http://a1024.phobos.apple.com/us/r30/Purple4/v4/e5/73/e7/e573e7f4-46bf-7df6-e6fb-55c23f82685c/mzl.kjeqfzle.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7708937/cb0ae9f2-fe59-11e4-838d-22d1dd823fd9.png)

**Comment by katakolo** [comment]
Hi,

Can anyone pick this one up please?

**Comment by dreamnet** [comment]
@katakolo Hm, that's in impossible-to-do icon. We need an alternative.

**Comment by katakolo** [comment]
maybe a simple spell out of "Grand Defense" with small letters? or GD?

**Comment by dreamnet** [comment]
Hm, it's a Game about defending some fruits frome ants, so what about his one:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7704488/fc903268-fe3e-11e4-9e8d-ff738a4114cd.png)
https://cloud.githubusercontent.com/assets/2068130/7704488/fc903268-fe3e-11e4-9e8d-ff738a4114cd.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7704491/106b82e2-fe3f-11e4-99b6-42bf75d45d5e.png
Or use only the ant?

**Comment by MagnaMike** [comment]
@dreamnet I always prefer no text when possible. That's my opinion

**Comment by katakolo** [comment]
maybe we leave the ant with no text, the game after all is about ants and other insects

**Comment by dreamnet** [comment]
@katakolo OK, so what about this one?:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7708937/cb0ae9f2-fe59-11e4-838d-22d1dd823fd9.png)
https://cloud.githubusercontent.com/assets/2068130/7708937/cb0ae9f2-fe59-11e4-838d-22d1dd823fd9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7708946/dc30b914-fe59-11e4-828f-fdd7c99ea78c.png

**Comment by katakolo** [comment]
looks great to me

**Comment by dreamnet** [comment]
@katakolo OK, good, we use it.

**Comment by katakolo** [comment]
great, thanx very much!
