### ISSUE TITLE
LIRR TrainTime

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5275]
**App Name:** LIRR TrainTime
**Bundle ID:** org.lirr.portal.TrainTime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=757322195">757322195</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lirr-traintime/id757322195?mt=8&uo=4">https://itunes.apple.com/us/app/lirr-traintime/id757322195?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** The Long Island Rail Road Company
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mta-long-island-rail-road/id757322198?uo=4>© MTA Long Island Rail Road</a>
**Supported Devices:** iPad3G, iPadWifi, iPadFourthGen4G, iPad2Wifi, iPadThirdGen4G, iPhone6Plus, iPhone5, iPadMini, iPodTouchFourthGen, iPhone4S, iPadFourthGen, iPodTouchThirdGen, iPhone-3GS, iPhone6, iPhone5c, iPodTouchFifthGen, iPad23G, iPadThirdGen, iPadMini4G, iPhone4, iPhone5s
**Original Artwork:**
<img src="http://a1134.phobos.apple.com/us/r30/Purple1/v4/5d/1e/77/5d1e7719-7416-a53a-b3a8-00c97a7a76e3/mzl.hqrpxanz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425621/d9c76446-bf31-11e4-89f7-3530434aabba.png)

**Comment by dreamnet** [comment]
I think it looks better without the "LIRR" letters.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425621/d9c76446-bf31-11e4-89f7-3530434aabba.png)
https://cloud.githubusercontent.com/assets/2068130/6425621/d9c76446-bf31-11e4-89f7-3530434aabba.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6425622/e690bfd8-bf31-11e4-81d3-346769394a2d.png
