### ISSUE TITLE
Sport24

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5276]
**App Name:** Sport24
**Bundle ID:** com.24media.sport24
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=662892291">662892291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sport24/id662892291?mt=8&uo=4">https://itunes.apple.com/us/app/sport24/id662892291?mt=8&uo=4</a>
**App Version:** 1.4.4
**Seller:** Lenok Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/lenok-ltd/id662892294?uo=4>© Lenok Ltd</a>
**Supported Devices:** iPadThirdGen4G, iPadThirdGen, iPhone5, iPad2Wifi, iPadFourthGen4G, iPhone4S, iPhone6Plus, iPhone-3GS, iPodTouchThirdGen, iPad23G, iPadFourthGen, iPodTouchFifthGen, iPad3G, iPadWifi, iPhone4, iPhone5c, iPhone5s, iPhone6, iPodTouchFourthGen, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://a1435.phobos.apple.com/us/r30/Purple3/v4/44/90/93/44909388-4082-850d-9a87-6f779a219de0/pr_source.png?downloadKey=1425116213_b3aabb471ec803e6c15c3d607163db9a" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6428248/56679fc4-bf60-11e4-968e-9c7f9a3442bf.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6428248/56679fc4-bf60-11e4-968e-9c7f9a3442bf.png)
https://cloud.githubusercontent.com/assets/3090247/6428248/56679fc4-bf60-11e4-968e-9c7f9a3442bf.png

---
Source:
![com 24media sport24](https://cloud.githubusercontent.com/assets/3090247/6428249/566cd35e-bf60-11e4-8fa4-11db44f5952c.png)
