### ISSUE TITLE
ΣΚΑΪ

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5277]
**App Name:** ΣΚΑΪ
**Bundle ID:** gr.skai.news
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=575928090">575928090</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skai/id575928090?mt=8&uo=4">https://itunes.apple.com/us/app/skai/id575928090?mt=8&uo=4</a>
**App Version:** 4.0.12
**Seller:** EIDISEIS DOT COM S.A
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/eidiseis-dot-com-s.a/id673096331?uo=4>© EIDISEIS DOT COM S.A</a>
**Supported Devices:** iPadThirdGen, iPadWifi, iPhone4, iPhone-3GS, iPhone4S, iPodTouchFifthGen, iPad3G, iPadFourthGen4G, iPad2Wifi, iPodTouchThirdGen, iPadMini, iPhone6, iPodTouchFourthGen, iPhone5c, iPadFourthGen, iPhone5s, iPhone5, iPadThirdGen4G, iPad23G, iPadMini4G, iPhone6Plus
**Original Artwork:**
<img src="http://a1895.phobos.apple.com/us/r30/Purple3/v4/c7/9e/8d/c79e8d4a-40a9-ba1e-a38d-da94ada71704/mzl.mvvaoebm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425598/f937245c-bf30-11e4-86de-cd02bcfd2c04.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425598/f937245c-bf30-11e4-86de-cd02bcfd2c04.png)
https://cloud.githubusercontent.com/assets/2068130/6425598/f937245c-bf30-11e4-86de-cd02bcfd2c04.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6425601/06705382-bf31-11e4-93e1-b5455ba85cb9.png
