### ISSUE TITLE
StarTV mobile

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5278]
**App Name:** StarTV mobile
**Bundle ID:** gr.unisystems.starTV.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=592095126">592095126</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/startv-mobile/id592095126?mt=8&uo=4">https://itunes.apple.com/us/app/startv-mobile/id592095126?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Unisystems Information Systems S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/unisystems-information-systems/id516258395?uo=4>© Unisystems Information Systems S.A.</a>
**Supported Devices:** iPhone-3GS, iPodTouchThirdGen, iPad3G, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5, iPhone4S, iPadWifi, iPodTouchFifthGen, iPad2Wifi, iPadFourthGen, iPadThirdGen, iPhone5c, iPodTouchFourthGen, iPhone4, iPhone6Plus, iPadThirdGen4G, iPhone6, iPhone5s, iPad23G
**Original Artwork:**
<img src="http://a1908.phobos.apple.com/us/r30/Purple2/v4/88/79/2d/88792d36-2212-a5f4-e359-9005da58ff3c/mzl.ttszaqvc.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425378/5aebdea0-bf26-11e4-892b-f702a1acd8d6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425378/5aebdea0-bf26-11e4-892b-f702a1acd8d6.png)
https://cloud.githubusercontent.com/assets/2068130/6425378/5aebdea0-bf26-11e4-892b-f702a1acd8d6.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6425379/6d17ce2c-bf26-11e4-91ed-382b7845548b.png
