### ISSUE TITLE
AEK1924

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5279]
**App Name:** AEK1924
**Bundle ID:** gr.aek1924.aek1924app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=858901482">858901482</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aek1924/id858901482?mt=8&uo=4">https://itunes.apple.com/us/app/aek1924/id858901482?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Theodoros Tassopoulos
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/theodoros-tassopoulos/id858901485?uo=4>© Theodoros Tassopoulos</a>
**Supported Devices:** iPhone4S, iPadMini4G, iPhone5s, iPadThirdGen4G, iPad2Wifi, iPadFourthGen, iPhone-3GS, iPadFourthGen4G, iPhone5, iPhone6Plus, iPhone6, iPad23G, iPodTouchFifthGen, iPhone4, iPadMini, iPhone5c, iPadThirdGen, iPodTouchFourthGen
**Original Artwork:**
<img src="http://a175.phobos.apple.com/us/r30/Purple/v4/d7/ae/28/d7ae2867-0607-8d7d-200a-144a06a8dc0f/mzl.bvmvpbjh.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425356/c0b862e0-bf25-11e4-9025-74cc6fc823e4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425356/c0b862e0-bf25-11e4-9025-74cc6fc823e4.png)
https://cloud.githubusercontent.com/assets/2068130/6425356/c0b862e0-bf25-11e4-9025-74cc6fc823e4.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6425357/cf08cc5e-bf25-11e4-9cce-30338947ab6c.png
