### ISSUE TITLE
iComics

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#528]
**App Name:** iComics - The Comic Reader for iPad and iPhone
**Bundle ID:** com.timoliver.icomics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493845493">493845493</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/icomics-comic-reader-for-ipad/id493845493?mt=8&uo=4">https://itunes.apple.com/us/app/icomics-comic-reader-for-ipad/id493845493?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Timothy Oliver
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tim-oliver/id385531057?uo=4>© Tim Oliver</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/51/7b/b1/517bb1ca-9148-abe2-ea06-6372fbd85e9f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14401871/7840a99c-fe20-11e5-96c0-87edcc2c04bc.png)

**Comment by zmathiasz** [comment]
Updated Icon

**App Name:** iComics - The Comic Reader for iPad and iPhone
**Bundle ID:** com.timoliver.icomics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493845493">493845493</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/icomics-comic-reader-for-ipad/id493845493?mt=8&uo=4">https://itunes.apple.com/us/app/icomics-comic-reader-for-ipad/id493845493?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Timothy Oliver
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tim-oliver/id385531057?uo=4>© Tim Oliver</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/51/7b/b1/517bb1ca-9148-abe2-ea06-6372fbd85e9f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14401871/7840a99c-fe20-11e5-96c0-87edcc2c04bc.png)
https://cloud.githubusercontent.com/assets/2068130/14401871/7840a99c-fe20-11e5-96c0-87edcc2c04bc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14401873/87217bee-fe20-11e5-8b31-e5b222c73fc7.png
