### ISSUE TITLE
MEGA TV

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5280]
**App Name:** MEGA TV
**Bundle ID:** gr.pegasusinteractive.megatv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=729464569">729464569</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gr/app/mega-tv/id729464569?mt=8&uo=4">https://itunes.apple.com/gr/app/mega-tv/id729464569?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Pegasus Interactive S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/gr/artist/pegasus-interactive-s.a./id377381328?uo=4>© Pegasus Interactive S.A.</a>
**Supported Devices:** iPodTouchFourthGen, iPadMini, iPhone4, iPhone6Plus, iPhone-3GS, iPhone5s, iPad2Wifi, iPodTouchFifthGen, iPhone5c, iPadThirdGen, iPadFourthGen4G, iPhone6, iPhone4S, iPadThirdGen4G, iPadMini4G, iPadFourthGen, iPhone5, iPad23G
**Original Artwork:**
<img src="http://a557.phobos.apple.com/us/r30/Purple3/v4/28/62/5a/28625a75-b716-13c0-17b0-c8de242f252e/pr_source.jpg?downloadKey=1425117053_4f34abc5cb7ce173cc6a8dad65204927" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425275/289cadac-bf22-11e4-9ff6-424a2eb6475d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425275/289cadac-bf22-11e4-9ff6-424a2eb6475d.png)
https://cloud.githubusercontent.com/assets/2068130/6425275/289cadac-bf22-11e4-9ff6-424a2eb6475d.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6425278/360aeb70-bf22-11e4-92cb-cee71546ae07.png
