### ISSUE TITLE
Crack & Break it !

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5281]
**App Name:** Crack & Break it !
**Bundle ID:** com.lemondoo.CrackYourScreen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448925179">448925179</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/crack-break-it-!/id448925179?mt=8&uo=4">https://itunes.apple.com/us/app/crack-break-it-!/id448925179?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Lemondo Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/lemondo-entertainment/id406195207?uo=4>© Lemondo Entertainment</a>
**Supported Devices:** iPhone4, iPadThirdGen4G, iPhone6Plus, iPadFourthGen, iPadThirdGen, iPadFourthGen4G, iPodTouchFifthGen, iPhone5s, iPhone5, iPadMini, iPadMini4G, iPad23G, iPad2Wifi, iPhone4S, iPhone6, iPhone5c
**Original Artwork:**
<img src="http://a547.phobos.apple.com/us/r30/Purple3/v4/d9/d4/f2/d9d4f29f-6ac9-7a53-7858-97b4ff65ce7e/pr_source.jpg?downloadKey=1425117307_8fb398145074179a7efca3fda0096d14" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425589/7529e47e-bf30-11e4-92eb-a7d5c0996ad1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6425589/7529e47e-bf30-11e4-92eb-a7d5c0996ad1.png)
https://cloud.githubusercontent.com/assets/2068130/6425589/7529e47e-bf30-11e4-92eb-a7d5c0996ad1.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6425590/81ec7a3c-bf30-11e4-8462-2c781aed43ba.png
