### ISSUE TITLE
London Bus Checker - Live Bus Countdown Times at Every Stop

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5282]
**App Name:** London Bus Checker - Live Bus Countdown Times at Every Stop
**Bundle ID:** com.fatattitude.buschecker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465042992">465042992</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/london-bus-checker-live-bus/id465042992?mt=8&uo=4">https://itunes.apple.com/us/app/london-bus-checker-live-bus/id465042992?mt=8&uo=4</a>
**App Version:** 5.0.4
**Seller:** FatAttitude
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fatattitude/id339540256?uo=4>© FatAttitude</a>
**Supported Devices:** iPadThirdGen, iPhone6Plus, iPhone5, iPhone5c, iPhone4S, iPadMini4G, iPhone6, iPadFourthGen, iPadFourthGen4G, iPadThirdGen4G, iPad23G, iPad2Wifi, iPodTouchFourthGen, iPhone4, iPhone-3GS, iPhone5s, iPadMini, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a852.phobos.apple.com/us/r30/Purple1/v4/6c/33/30/6c33309f-d744-6a4b-4e9e-ecf5f31e6675/mzl.hmynequd.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6432563/d3c69754-c023-11e4-9d79-ceb9bd213155.png)

**Comment by hiemss** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6430263/1a53aa56-bffa-11e4-859e-331049c87f14.png)

**Comment by hiemss** [comment]
src:
https://cloud.githubusercontent.com/assets/11254886/6431097/8f240d72-c01c-11e4-93e9-a1160e9476af.png

**Comment by MagnaMike** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6432563/d3c69754-c023-11e4-9d79-ceb9bd213155.png)
https://cloud.githubusercontent.com/assets/2236254/6432563/d3c69754-c023-11e4-9d79-ceb9bd213155.png

Source:
https://cloud.githubusercontent.com/assets/2236254/6432562/d3c56456-c023-11e4-855a-6449c2db32b2.png
