### ISSUE TITLE
IG Trading – spread betting, CFDs, forex and stockbroking

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5283]
**App Name:** IG Trading – spread betting, CFDs, forex and stockbroking
**Bundle ID:** com.igmarkets.ideal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406492428">406492428</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/ig-trading-spread-betting/id406492428?mt=8&uo=4">https://itunes.apple.com/gb/app/ig-trading-spread-betting/id406492428?mt=8&uo=4</a>
**App Version:** 5.5.37
**Seller:** IG Index Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/artist/ig-group/id377032137?uo=4>© IG Group</a>
**Supported Devices:** iPadThirdGen, iPhone4S, iPad2Wifi, iPhone6, iPhone4, iPodTouchFifthGen, iPadMini, iPhone5, iPhone5s, iPadFourthGen4G, iPhone6Plus, iPadFourthGen, iPadMini4G, iPhone5c, iPad23G, iPadThirdGen4G
**Original Artwork:**
<img src="http://a338.phobos.apple.com/us/r30/Purple1/v4/6e/bb/b1/6ebbb18c-cddb-670c-2bc2-66a2c18086d1/mzl.cqrxikca.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6432569/ffad09f2-c023-11e4-871f-26ef842e2650.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6431275/7c9dbdd2-c022-11e4-9790-2ea19e1e8edc.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6431275/7c9dbdd2-c022-11e4-9790-2ea19e1e8edc.png)

**Comment by hiemss** [comment]
source: 
https://cloud.githubusercontent.com/assets/11254886/6431340/903b0e9c-c024-11e4-91bf-0a359a01a910.png

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6431499/aaeed71e-c029-11e4-87d6-cc1da501e898.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6431499/aaeed71e-c029-11e4-87d6-cc1da501e898.png)

**Comment by hiemss** [comment]
source:
https://cloud.githubusercontent.com/assets/11254886/6431522/12cc1acc-c02a-11e4-9bc3-3c8fe56b13c6.png

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6431549/bcdca298-c02a-11e4-988b-46c13f712398.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6431549/bcdca298-c02a-11e4-988b-46c13f712398.png)

**Comment by hiemss** [comment]
source:
https://cloud.githubusercontent.com/assets/11254886/6431555/efe6e310-c02a-11e4-9e27-d0e9ac7e6ce0.png

**Comment by MagnaMike** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6432569/ffad09f2-c023-11e4-871f-26ef842e2650.png)
https://cloud.githubusercontent.com/assets/2236254/6432569/ffad09f2-c023-11e4-871f-26ef842e2650.png
Source:
https://cloud.githubusercontent.com/assets/2236254/6432568/ff9b45c8-c023-11e4-8edd-c03a32798b67.png
