### ISSUE TITLE
Cost Split - Group Expenses

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5284]
**App Name:** Cost Split - Group Expenses
**Bundle ID:** se.ivstam.costsplit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=524132764">524132764</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cost-split-group-expenses/id524132764?mt=8&uo=4">https://itunes.apple.com/us/app/cost-split-group-expenses/id524132764?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Jacob Ivstam
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jacob-ivstam/id524132767?uo=4>© Jacob Ivstam</a>
**Supported Devices:** iPodTouchFifthGen, iPadMini4G, iPhone6Plus, iPhone5s, iPadThirdGen, iPadFourthGen4G, iPhone4S, iPadMini, iPhone6, iPhone4, iPad2Wifi, iPhone5, iPadFourthGen, iPhone5c, iPadThirdGen4G, iPad23G
**Original Artwork:**
<img src="http://a1057.phobos.apple.com/us/r30/Purple3/v4/3f/00/65/3f006529-04cc-4b21-b0a5-d9777d3b8729/pr_source.png?downloadKey=1425254838_6854e9734d7fab188d9d21ad5c41a3c3" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6448829/da738392-c11c-11e4-9fb6-f5212ddde38e.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6432896/5111f28c-c059-11e4-89da-02070d30f332.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6432896/5111f28c-c059-11e4-89da-02070d30f332.png)

**Comment by hiemss** [comment]
source
https://cloud.githubusercontent.com/assets/11254886/6432900/7919be2c-c059-11e4-8589-4437c84e01aa.png

**Comment by dreamnet** [comment]
@hiemss Not bad, but we need to keep aspect ratio. The icon in the source also must go completley to the edges (but always keep aspect ratio).
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6448829/da738392-c11c-11e4-9fb6-f5212ddde38e.png)
https://cloud.githubusercontent.com/assets/2068130/6448829/da738392-c11c-11e4-9fb6-f5212ddde38e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6448841/f2b14872-c11c-11e4-84dc-9ef4c6c34df8.png
