### ISSUE TITLE
Craft Beer London

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5285]
**App Name:** Craft Beer London
**Bundle ID:** com.craftbeerlondon.www
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=529777025">529777025</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/craft-beer-london/id529777025?mt=8&uo=4">https://itunes.apple.com/us/app/craft-beer-london/id529777025?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Blue Crow Media LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/blue-crow-media/id400916966?uo=4>© Blue Crow Media</a>
**Supported Devices:** iPhone-3GS, iPadMini, iPhone6Plus, iPadThirdGen4G, iPadMini4G, iPhone5s, iPadWifi, iPadFourthGen, iPhone6, iPhone4S, iPad3G, iPadFourthGen4G, iPad23G, iPad2Wifi, iPodTouchFifthGen, iPodTouchThirdGen, iPhone4, iPhone5, iPadThirdGen, iPhone5c, iPodTouchFourthGen
**Original Artwork:**
<img src="http://a1885.phobos.apple.com/us/r30/Purple4/v4/18/47/58/18475862-0346-002d-7149-e0fee561f32d/mzl.zrhbobct.jpeg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6448941/a7519818-c11d-11e4-86c8-84b810d41d4c.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6432942/909db192-c05a-11e4-9206-667700eb1a57.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6432942/909db192-c05a-11e4-9206-667700eb1a57.png)

**Comment by hiemss** [comment]
source: 
https://cloud.githubusercontent.com/assets/11254886/6432946/a28a17c4-c05a-11e4-862b-b53182a40d6d.png

**Comment by dreamnet** [comment]
@hiemss Good, good - the source is not correct, but I give you credits for this anyway. :+1: 

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6448930/950da1ec-c11d-11e4-9480-71b0bee18e08.png

**Comment by hiemss** [comment]
thanks! first time I play with icons on photoshop, still learning but doing my best!

**Comment by dreamnet** [comment]
@hiemss ...and you are doing good so far. :+1: Keep on!
