### ISSUE TITLE
npower

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5286]
**App Name:** npower
**Bundle ID:** com.npower.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=640469810">640469810</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/npower/id640469810?mt=8&uo=4">https://itunes.apple.com/gb/app/npower/id640469810?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** npower Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/artist/npower/id362087152?uo=4>© npower</a>
**Supported Devices:** iPadMini4G, iPhone5c, iPhone5, iPad2Wifi, iPadFourthGen4G, iPhone4S, iPodTouchThirdGen, iPad3G, iPadThirdGen, iPhone-3GS, iPadFourthGen, iPodTouchFourthGen, iPadMini, iPadWifi, iPodTouchFifthGen, iPhone5s, iPhone4, iPadThirdGen4G, iPad23G, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://a802.phobos.apple.com/us/r30/Purple4/v4/ce/64/db/ce64db68-d982-58ff-a806-55607cae0c15/mzl.wijhjrcw.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6449045/5e091b58-c11e-11e4-861e-a20a06786b8a.png)

**Comment by hiemss** [comment]
![com npower app x2](https://cloud.githubusercontent.com/assets/11254886/6432993/cccdeb22-c05b-11e4-9235-4197dd442a20.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6432993/cccdeb22-c05b-11e4-9235-4197dd442a20.png)

**Comment by hiemss** [comment]
source:
https://cloud.githubusercontent.com/assets/11254886/6432995/efa4427c-c05b-11e4-9051-0e26c73d10d5.png

**Comment by dreamnet** [comment]
@hiemss Mh, nope - we need to keep aspect ratio.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6449045/5e091b58-c11e-11e4-861e-a20a06786b8a.png)
https://cloud.githubusercontent.com/assets/2068130/6449045/5e091b58-c11e-11e4-861e-a20a06786b8a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6449067/72322c64-c11e-11e4-8376-9f16ad6a9526.png
