### ISSUE TITLE
Amazon Prime Video

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5287]
**App Name:** Amazon Prime Video
**Bundle ID:** com.lovefilm.watchnow.ipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454468674">454468674</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/amazon-prime-video/id454468674?mt=8&uo=4">https://itunes.apple.com/gb/app/amazon-prime-video/id454468674?mt=8&uo=4</a>
**App Version:** 5.3
**Seller:** Amazon Instant Video Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/amazon-instant-video-limited/id353141815?uo=4">© Amazon Instant Video Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/d1/a7/69/d1a76978-bf23-b1b4-58ad-33222e0e2277/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455543-fd532366-3a79-11e8-999c-6a65ec54d470.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6433306/281b2d58-c063-11e4-85fd-e9eb61107f6a.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6433306/281b2d58-c063-11e4-85fd-e9eb61107f6a.png)

**Comment by hiemss** [comment]
source:
https://cloud.githubusercontent.com/assets/11254886/6433312/417c6b4a-c063-11e4-9fa6-4ad472f9b205.png

**Comment by dreamnet** [comment]
For this we use the same icon as for #4801.
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5330672/47db89e0-7e04-11e4-8e37-facc52ad23c3.png)
https://cloud.githubusercontent.com/assets/2068130/5330672/47db89e0-7e04-11e4-8e37-facc52ad23c3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/5330673/5544d1b8-7e04-11e4-9b65-bc27766383bf.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8.
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455543-fd532366-3a79-11e8-999c-6a65ec54d470.png)
https://user-images.githubusercontent.com/20930745/38455543-fd532366-3a79-11e8-999c-6a65ec54d470.png
--- ---
Source:
https://user-images.githubusercontent.com/20930745/38455548-0c3d0ebe-3a7a-11e8-9e27-85d8b547d4f1.png
