### ISSUE TITLE
MY EE

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5288]
**App Name:** MY EE
**Bundle ID:** uk.co.ee.MyEE
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=567457151">567457151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-ee/id567457151?mt=8&uo=4">https://itunes.apple.com/us/app/my-ee/id567457151?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** EE LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ee-limited/id561959980?uo=4>© EE LIMITED</a>
**Supported Devices:** iPadFourthGen, iPad23G, iPadMini4G, iPhone5s, iPhone4S, iPodTouchFifthGen, iPhone4, iPhone6, iPhone5, iPhone6Plus, iPadFourthGen4G, iPadThirdGen, iPadMini, iPhone5c, iPad2Wifi, iPadThirdGen4G
**Original Artwork:**
<img src="http://a1138.phobos.apple.com/us/r30/Purple5/v4/c1/0e/ff/c10eff0d-eefc-c415-d70b-b0acd679a243/mzl.kuwriqty.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6449480/2fca79d2-c121-11e4-81b6-840723fc0685.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6436694/d81988a6-c0ab-11e4-8edf-328f10142b64.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6436694/d81988a6-c0ab-11e4-8edf-328f10142b64.png)
source: 
https://cloud.githubusercontent.com/assets/11254886/6436704/f66191e6-c0ab-11e4-90d2-c56aff1f210c.png

**Comment by dreamnet** [comment]
@hiemss Ummm - aspect ratio.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6449480/2fca79d2-c121-11e4-81b6-840723fc0685.png)
https://cloud.githubusercontent.com/assets/2068130/6449480/2fca79d2-c121-11e4-81b6-840723fc0685.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6449376/a5b61788-c120-11e4-9a50-7ce349b7a95a.png
