### ISSUE TITLE
Eurostar Trains

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5289]
**App Name:** Eurostar Trains
**Bundle ID:** com.eurostar.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=453671246">453671246</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/eurostar-trains/id453671246?mt=8&uo=4">https://itunes.apple.com/us/app/eurostar-trains/id453671246?mt=8&uo=4</a>
**App Version:** 3.0.2.5
**Seller:** Eurostar International Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/eurostar-international-ltd./id453671249?uo=4>© Eurostar International Ltd.</a>
**Supported Devices:** iPadMini, iPhone5, iPhone5c, iPadThirdGen4G, iPhone-3GS, iPhone5s, iPadFourthGen, iPadThirdGen, iPad23G, iPadMini4G, iPhone6, iPodTouchFourthGen, iPhone4S, iPhone6Plus, iPad2Wifi, iPodTouchFifthGen, iPadFourthGen4G, iPhone4
**Original Artwork:**
<img src="http://a343.phobos.apple.com/us/r30/Purple1/v4/98/7a/3c/987a3cbf-200c-457c-8dd8-c65505877122/mzl.gtuldhsv.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6450367/9babd988-c127-11e4-8b5f-b3c5d37f8717.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6436822/a65c8334-c0ad-11e4-9bd5-8a893e16e41c.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6436822/a65c8334-c0ad-11e4-9bd5-8a893e16e41c.png)
source:
https://cloud.githubusercontent.com/assets/11254886/6436833/c69e63c4-c0ad-11e4-9bc9-7c44336490e8.png

**Comment by dreamnet** [comment]
... a bit more details....
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6450367/9babd988-c127-11e4-8b5f-b3c5d37f8717.png)
https://cloud.githubusercontent.com/assets/2068130/6450367/9babd988-c127-11e4-8b5f-b3c5d37f8717.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6450148/1c4bd1da-c126-11e4-93d9-38357c9cbeef.png

**Comment by hiemss** [comment]
much better indeed! what tool did you use to do that?

**Comment by dreamnet** [comment]
@hiemss I am not using Photoshop, I am using Illustrator for the sources.
