### ISSUE TITLE
GoodReader

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5290]
**App Name:** GoodReader
**Bundle ID:** com.goodiware.goodreader4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=777310222">777310222</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/goodreader/id777310222?mt=8&uo=4">https://itunes.apple.com/us/app/goodreader/id777310222?mt=8&uo=4</a>
**App Version:** 4.9.2
**Seller:** Yuri Selukoff
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/good.iware-ltd./id289191291?uo=4>© Good.iWare Ltd.</a>
**Supported Devices:** iPad2Wifi, iPadFourthGen4G, iPhone5s, iPhone6Plus, iPhone4S, iPhone5, iPhone4, iPadThirdGen4G, iPadMini4G, iPad23G, iPhone5c, iPhone6, iPodTouchFourthGen, iPadFourthGen, iPadThirdGen, iPodTouchFifthGen, iPhone-3GS, iPadMini
**Original Artwork:**
<img src="http://a722.phobos.apple.com/us/r30/Purple3/v4/79/19/21/79192194-5009-1c8c-0205-259f88607601/mzl.slhzyphl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6451733/e0bb4438-c130-11e4-9af8-9f283bb5fcde.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6438178/be0fda42-c0be-11e4-9940-2ab38b6b1e8f.png


![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6438178/be0fda42-c0be-11e4-9940-2ab38b6b1e8f.png)

**Comment by hiemss** [comment]
source:
https://cloud.githubusercontent.com/assets/11254886/6438223/0f5e5e50-c0bf-11e4-9bd8-74d63400c7d1.png

**Comment by dreamnet** [comment]
Just cleaned it up a bit:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6451733/e0bb4438-c130-11e4-9af8-9f283bb5fcde.png)
https://cloud.githubusercontent.com/assets/2068130/6451733/e0bb4438-c130-11e4-9af8-9f283bb5fcde.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6451744/f24fcc00-c130-11e4-8033-03bdfc361428.png
