### ISSUE TITLE
Paris Metro RATP Map and Route Planner

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5291]
**App Name:** Paris Metro RATP Map and Route Planner
**Bundle ID:** uk.co.mxdata.parismetro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527534137">527534137</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paris-metro-ratp-map-route/id527534137?mt=8&uo=4">https://itunes.apple.com/us/app/paris-metro-ratp-map-route/id527534137?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** mxData Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mxdata-limited/id320969615?uo=4>© mxData Limited</a>
**Supported Devices:** iPhone6, iPadThirdGen4G, iPad2Wifi, iPhone4S, iPadFourthGen4G, iPhone5s, iPhone6Plus, iPadFourthGen, iPodTouchFifthGen, iPhone4, iPhone5, iPadThirdGen, iPad23G, iPadMini, iPadMini4G, iPhone5c
**Original Artwork:**
<img src="http://a819.phobos.apple.com/us/r30/Purple3/v4/30/16/eb/3016ebf2-7d8f-3e30-1deb-3a3de10556fe/mzl.zgkvnevq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6471376/b1d32eb4-c1ea-11e4-91f0-9d8a65ea17aa.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6439654/aef05bbe-c0cc-11e4-8e14-28c3c72ecce4.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6439654/aef05bbe-c0cc-11e4-8e14-28c3c72ecce4.png)
source:
https://cloud.githubusercontent.com/assets/11254886/6439662/cb7f6004-c0cc-11e4-8487-e0dcafaef024.png

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6450123/9711be6a-c11d-11e4-9105-4aeca7119093.png
![](http://preview.dreamnet.at/?image=(https://cloud.githubusercontent.com/assets/11254886/6450123/9711be6a-c11d-11e4-9105-4aeca7119093.png)
source: 
https://cloud.githubusercontent.com/assets/11254886/6450156/c023ca6e-c11d-11e4-8434-02f2fc193806.png

**Comment by dreamnet** [comment]
I think this should be done like #5252.

**Comment by MagnaMike** [comment]
@dreamnet Agreed. :+1:

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6471376/b1d32eb4-c1ea-11e4-91f0-9d8a65ea17aa.png)
https://cloud.githubusercontent.com/assets/2068130/6471376/b1d32eb4-c1ea-11e4-91f0-9d8a65ea17aa.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6471385/c0f0d770-c1ea-11e4-8dc8-ec5b46a6f516.png
