### ISSUE TITLE
Best Coffee - cafes guide

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5292]
**App Name:** Best Coffee - cafes guide
**Bundle ID:** co.uk.londonsbestcoffee.www
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=400916958">400916958</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/best-coffee-cafes-guide/id400916958?mt=8&uo=4">https://itunes.apple.com/us/app/best-coffee-cafes-guide/id400916958?mt=8&uo=4</a>
**App Version:** 3.6.5
**Seller:** PACEDCO NO.6 LIMITED
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/best-coffee-guide/id1240189631?uo=4">© Best Coffee Guide</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/7d/53/d6/7d53d6a7-26ed-0c63-566f-9b85a014aba6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626560-b5434d80-a91e-11e8-958e-bcc37c4728f3.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6440092/9a093e5a-c0d1-11e4-9822-5052d621ff32.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6440092/9a093e5a-c0d1-11e4-9822-5052d621ff32.png)
source:
(https://cloud.githubusercontent.com/assets/11254886/6440194/880100de-c0d2-11e4-9d7c-76dbad1d63da.png

**Comment by dreamnet** [comment]
Alternative:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6472503/595aa830-c1f3-11e4-8600-080fcf545c95.png)
https://cloud.githubusercontent.com/assets/2068130/6472503/595aa830-c1f3-11e4-8600-080fcf545c95.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6472519/6ac65e2a-c1f3-11e4-8804-416f0f588d37.png

**Comment by MagnaMike** [comment]
I think @dreamnet will look better, thin lines don't always work so well.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626560-b5434d80-a91e-11e8-958e-bcc37c4728f3.png)
https://user-images.githubusercontent.com/2068130/44626560-b5434d80-a91e-11e8-958e-bcc37c4728f3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44626562-c2f8d300-a91e-11e8-9d33-4bafb451700e.png
