### ISSUE TITLE
Amazon

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5293]
**App Name:** Amazon
**Bundle ID:** com.amazon.AmazonUK
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335187483">335187483</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/amazon/id335187483?mt=8&uo=4">https://itunes.apple.com/gb/app/amazon/id335187483?mt=8&uo=4</a>
**App Version:** 4.4.1
**Seller:** Amazon Eurasia Holdings Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/artist/amazon/id335187486?uo=4>© Amazon</a>
**Supported Devices:** iPadMini, iPhone4, iPadThirdGen, iPadMini4G, iPhone6Plus, iPhone5s, iPadFourthGen, iPhone5c, iPad2Wifi, iPad23G, iPadThirdGen4G, iPhone4S, iPodTouchFifthGen, iPadFourthGen4G, iPhone6, iPhone5
**Original Artwork:**
<img src="http://a1438.phobos.apple.com/us/r30/Purple1/v4/15/c7/ed/15c7edf4-4de0-8b36-3f40-4ea5045f7f0e/mzl.jgupgnlq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6473609/b006dac6-c1fa-11e4-935c-beb3034ae999.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6440551/021050ca-c0d6-11e4-8012-d5f2612e3873.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6440551/021050ca-c0d6-11e4-8012-d5f2612e3873.png)
Source:
https://cloud.githubusercontent.com/assets/11254886/6440561/14a1e53c-c0d6-11e4-8cc0-5221b5c9e27f.png

**Comment by dreamnet** [comment]
@hiemss Yes, but the "amazon" is not centered and I think we need to keep the shopping chart at the bottom to prevent the look of the original.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6473609/b006dac6-c1fa-11e4-935c-beb3034ae999.png)
https://cloud.githubusercontent.com/assets/2068130/6473609/b006dac6-c1fa-11e4-935c-beb3034ae999.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6473469/d013c280-c1f9-11e4-8fd6-6928226b411b.png
I give you credits for this anyway.
