### ISSUE TITLE
Podcaster 7

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5294]
**App Name:** Podcaster 7
**Bundle ID:** fm.podcaster.podcaster4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=595855794">595855794</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/podcaster-7/id595855794?mt=8&uo=4">https://itunes.apple.com/us/app/podcaster-7/id595855794?mt=8&uo=4</a>
**App Version:** 7.5
**Seller:** Alex Sokirynsky
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/alex-sokirynsky/id288446753?uo=4>© Alex Sokirynsky</a>
**Supported Devices:** iPadThirdGen, iPad23G, iPadMini, iPhone5c, iPadFourthGen, iPadFourthGen4G, iPhone5s, iPhone6, iPodTouchFifthGen, iPad2Wifi, iPhone4S, iPhone4, iPadThirdGen4G, iPhone6Plus, iPhone5, iPadMini4G
**Original Artwork:**
<img src="http://a158.phobos.apple.com/us/r30/Purple4/v4/9f/9e/f6/9f9ef694-991a-2e86-fbbb-23d96eeebda1/mzl.njgoicgb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6472242/38d04a36-c1f1-11e4-8ebc-63d2237bab4d.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6442217/f53797fe-c0e5-11e4-90ce-dcbb57220097.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6442217/f53797fe-c0e5-11e4-90ce-dcbb57220097.png)
source:
https://cloud.githubusercontent.com/assets/11254886/6442231/0601c7d0-c0e6-11e4-86fd-55b563d5101d.png

**Comment by dreamnet** [comment]
Ah, no, the other way round...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6472242/38d04a36-c1f1-11e4-8ebc-63d2237bab4d.png)
https://cloud.githubusercontent.com/assets/2068130/6472242/38d04a36-c1f1-11e4-8ebc-63d2237bab4d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6472253/4aebb03e-c1f1-11e4-85ec-00f85d130725.png
