### ISSUE TITLE
ProCam 4 - Manual Camera + RAW

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5295]
**App Name:** ProCam 4 - Manual Camera + RAW
**Bundle ID:** gemini.ProCam-2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=730712409">730712409</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/procam-4-manual-camera-raw/id730712409?mt=8&uo=4">https://itunes.apple.com/us/app/procam-4-manual-camera-raw/id730712409?mt=8&uo=4</a>
**App Version:** 9.0.2
**Seller:** Samer Azzam
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/samer-azzam/id503806808?uo=4">© Samer Azzam</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/57/36/f9/5736f955-1bf4-fa30-7e9f-35842de87b53/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29493424-d2a178aa-8595-11e7-8355-e67ce63c735f.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6443304/edda184e-c0ed-11e4-84a2-9ccafa503640.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6443304/edda184e-c0ed-11e4-84a2-9ccafa503640.png)
source: 
https://cloud.githubusercontent.com/assets/11254886/6443319/07102b46-c0ee-11e4-8ca7-8c21d1b6f197.png

**Comment by dreamnet** [comment]
Alternative:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6474394/a389f444-c200-11e4-8e80-987fdf4a4b84.png)
https://cloud.githubusercontent.com/assets/2068130/6474394/a389f444-c200-11e4-8e80-987fdf4a4b84.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6474403/b28773c2-c200-11e4-98bf-089f2a07edc7.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** ProCam 4 - Manual Camera + RAW
**Bundle ID:** gemini.ProCam-2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=730712409">730712409</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/procam-4-manual-camera-raw/id730712409?mt=8&uo=4">https://itunes.apple.com/us/app/procam-4-manual-camera-raw/id730712409?mt=8&uo=4</a>
**App Version:** 9.0.2
**Seller:** Samer Azzam
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/samer-azzam/id503806808?uo=4">© Samer Azzam</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/57/36/f9/5736f955-1bf4-fa30-7e9f-35842de87b53/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29493424-d2a178aa-8595-11e7-8355-e67ce63c735f.png)
https://user-images.githubusercontent.com/20930745/29493424-d2a178aa-8595-11e7-8355-e67ce63c735f.png

Source:
https://user-images.githubusercontent.com/20930745/29493426-e5378a86-8595-11e7-91ca-a7597c4b256e.png
