### ISSUE TITLE
LinkedIn Sales Navigator

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#5296]
**App Name:** LinkedIn Sales Navigator
**Bundle ID:** com.linkedin.Lighthouse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=910768078">910768078</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/linkedin-sales-navigator/id910768078?mt=8&uo=4">https://itunes.apple.com/us/app/linkedin-sales-navigator/id910768078?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** LinkedIn Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/linkedin-corporation/id288429043?uo=4>© LinkedIn Corporation</a>
**Supported Devices:** iPadFourthGen4G, iPad2Wifi, iPhone6Plus, iPadThirdGen4G, iPodTouchFifthGen, iPhone5, iPadMini4G, iPad23G, iPadThirdGen, iPadMini, iPhone5s, iPhone4, iPhone6, iPhone5c, iPhone4S, iPadFourthGen
**Original Artwork:**
<img src="http://a1828.phobos.apple.com/us/r30/Purple1/v4/86/b2/79/86b27910-209d-5c71-07e1-9863a00181c8/mzl.gzkydgqe.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6451172/f5d752de-c12c-11e4-831d-f2fe14d2fd77.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6451172/f5d752de-c12c-11e4-831d-f2fe14d2fd77.png)
https://cloud.githubusercontent.com/assets/2068130/6451172/f5d752de-c12c-11e4-831d-f2fe14d2fd77.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6451178/0555fe5e-c12d-11e4-8214-39a11274332d.png
