### ISSUE TITLE
National Bank Mobile Banking Solutions

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#5297]
**App Name:** National Bank Mobile Banking Solutions
**Bundle ID:** ca.bnc.BNCMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476651878">476651878</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/national-bank-mobile-banking/id476651878?mt=8&uo=4">https://itunes.apple.com/us/app/national-bank-mobile-banking/id476651878?mt=8&uo=4</a>
**App Version:** 1.10
**Seller:** Banque Nationale Du Canada
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/banque-nationale-du-canada/id476651881?uo=4>© Banque Nationale du Canada</a>
**Supported Devices:** iPad23G, iPadMini, iPhone6Plus, iPhone4, iPodTouchFourthGen, iPhone5s, iPadThirdGen4G, iPhone6, iPodTouchFifthGen, iPhone5, iPhone4S, iPhone-3GS, iPadFourthGen4G, iPadFourthGen, iPhone5c, iPadThirdGen, iPad2Wifi, iPadMini4G
**Original Artwork:**
<img src="http://a990.phobos.apple.com/us/r30/Purple3/v4/58/9c/48/589c48e1-8676-99a4-6b9d-759137f0b001/pr_source.png?downloadKey=1425321100_24e7907df9dde5700be5defd03fdf932" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6452048/3255e4ea-c133-11e4-8769-e13ddda90573.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6452048/3255e4ea-c133-11e4-8769-e13ddda90573.png)
https://cloud.githubusercontent.com/assets/2068130/6452048/3255e4ea-c133-11e4-8769-e13ddda90573.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6452057/4433b232-c133-11e4-868f-239683088dc0.png
