### ISSUE TITLE
Do Note by IFTTT

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#5298]
**App Name:** Do Note by IFTTT
**Bundle ID:** com.ifttt.donote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905998379">905998379</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/do-note-by-ifttt/id905998379?mt=8&uo=4">https://itunes.apple.com/us/app/do-note-by-ifttt/id905998379?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** IFTTT Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ifttt/id660944638?uo=4>© IFTTT</a>
**Supported Devices:** iPadThirdGen4G, iPhone6, iPadThirdGen, iPhone5s, iPadMini, iPhone5c, iPhone6Plus, iPad2Wifi, iPad23G, iPhone4S, iPhone4, iPadFourthGen4G, iPadMini4G, iPadFourthGen, iPodTouchFifthGen, iPhone5
**Original Artwork:**
<img src="http://a1824.phobos.apple.com/us/r30/Purple5/v4/7a/7f/e0/7a7fe0b8-2aaf-db14-acdd-8709ab6c24d3/pr_source.png?downloadKey=1425321154_32fb6f5f0aaee67f8ac607d6032f04d9" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6450841/0f84b372-c12b-11e4-9821-7834318d5a8d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6450841/0f84b372-c12b-11e4-9821-7834318d5a8d.png)
https://cloud.githubusercontent.com/assets/2068130/6450841/0f84b372-c12b-11e4-9821-7834318d5a8d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6450850/20a078c6-c12b-11e4-80a9-7ade905a3768.png
