### ISSUE TITLE
Do Button by IFTTT

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#5299]
**App Name:** Do Button by IFTTT
**Bundle ID:** com.ifttt.dobutton
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905998610">905998610</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/do-button-by-ifttt/id905998610?mt=8&uo=4">https://itunes.apple.com/us/app/do-button-by-ifttt/id905998610?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** IFTTT Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ifttt/id660944638?uo=4>© IFTTT</a>
**Supported Devices:** iPhone6Plus, iPad2Wifi, iPhone6, iPad23G, iPhone5c, iPadMini4G, iPhone4, iPadThirdGen, iPhone5, iPadThirdGen4G, iPadMini, iPhone5s, iPadFourthGen4G, iPadFourthGen, iPodTouchFifthGen, iPhone4S
**Original Artwork:**
<img src="http://a1787.phobos.apple.com/us/r30/Purple1/v4/19/07/f8/1907f877-8766-98a0-8670-d1dd6d188283/pr_source.png?downloadKey=1425321193_a9deb68e4f5c9cf93c0e56ab73c88e5d" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6450750/4cd32ade-c12a-11e4-9119-5a1ce6ba0a49.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6450750/4cd32ade-c12a-11e4-9119-5a1ce6ba0a49.png)
https://cloud.githubusercontent.com/assets/2068130/6450750/4cd32ade-c12a-11e4-9119-5a1ce6ba0a49.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6450757/5d5102be-c12a-11e4-8d31-b2ea938942d7.png
