### ISSUE TITLE
Do Camera by IFTTT

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#5300]
**App Name:** Do Camera by IFTTT
**Bundle ID:** com.ifttt.docamera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905998167">905998167</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/do-camera-by-ifttt/id905998167?mt=8&uo=4">https://itunes.apple.com/us/app/do-camera-by-ifttt/id905998167?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** IFTTT Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ifttt/id660944638?uo=4>© IFTTT</a>
**Supported Devices:** iPadFourthGen, iPhone5, iPhone6, iPad2Wifi, iPadThirdGen, iPodTouchFifthGen, iPhone5s, iPadThirdGen4G, iPadFourthGen4G, iPad23G, iPhone4S, iPhone6Plus, iPadMini, iPhone5c, iPadMini4G, iPhone4
**Original Artwork:**
<img src="http://a1060.phobos.apple.com/us/r30/Purple5/v4/96/a9/e2/96a9e28e-dcc5-4507-9456-7f61bbcc8a87/pr_source.png?downloadKey=1425321256_4ce3b6e40adae42bd8763d7eb2281415" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6450677/cc245e44-c129-11e4-8027-34568dd09a77.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6450677/cc245e44-c129-11e4-8027-34568dd09a77.png)
https://cloud.githubusercontent.com/assets/2068130/6450677/cc245e44-c129-11e4-8027-34568dd09a77.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6450683/db2ef8ae-c129-11e4-8b77-31d64a9f2dcf.png
