### ISSUE TITLE
TIDAL

### ISSUE THREAD

**Issue by djnightlife** [glasklart/hd#5301]
**App Name:** TIDAL
**Bundle ID:** com.aspiro.TIDAL
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=913943275">913943275</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tidal/id913943275?mt=8&uo=4">https://itunes.apple.com/us/app/tidal/id913943275?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Aspiro Music AS
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/aspiro-music-as/id365244402?uo=4>© Aspiro Music AS</a>
**Supported Devices:** iPad23G, iPhone4S, iPhone4, iPadMini, iPhone6, iPadThirdGen, iPhone5s, iPhone6Plus, iPadThirdGen4G, iPadFourthGen4G, iPad2Wifi, iPadMini4G, iPhone5c, iPodTouchFifthGen, iPadFourthGen, iPhone5
**Original Artwork:**
<img src="http://a634.phobos.apple.com/us/r30/Purple1/v4/14/55/50/1455504d-5a3d-b110-7d70-108a02f9fe29/mzl.capuwqjd.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6450827/89bcdaec-c122-11e4-9806-bcdbe5cf0d0e.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6450827/89bcdaec-c122-11e4-9806-bcdbe5cf0d0e.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6450827/89bcdaec-c122-11e4-9806-bcdbe5cf0d0e.png)
source:
https://cloud.githubusercontent.com/assets/11254886/6450834/a0d94f08-c122-11e4-8f10-3fe25a4333e9.png

**Comment by dreamnet** [comment]
@hiemss Great! :+1: I correced your source:
https://cloud.githubusercontent.com/assets/2068130/6451010/fa5d48dc-c12b-11e4-88bf-dc65b470dbdf.png

**Comment by hiemss** [comment]
@dreamnet good to know, thanks ;)
