### ISSUE TITLE
Samsung Smart View

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5302]
**App Name:** Samsung Smart View
**Bundle ID:** com.samsung.smartview2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=858283863">858283863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/samsung-smart-view/id858283863?mt=8&uo=4">https://itunes.apple.com/us/app/samsung-smart-view/id858283863?mt=8&uo=4</a>
**App Version:** 1.5.6
**Seller:** Samsung Electronics
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/samsung-electronics-co.ltd./id359580642?uo=4>© Samsung Electronics CO.LTD.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/af/ef/d2/afefd250-ee7e-83b0-59d3-dcb5605cc803/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17320052/d5cb78dc-5891-11e6-8cb4-1fd563a873e8.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6443913/419948a2-c0f2-11e4-928e-8d096aa681c6.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6443913/419948a2-c0f2-11e4-928e-8d096aa681c6.png)
source:
https://cloud.githubusercontent.com/assets/11254886/6443969/8e5b4a1e-c0f2-11e4-9660-f2c0e597c47e.png

**Comment by dreamnet** [comment]
Done just a little cleanup:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6474614/7bfa3518-c202-11e4-81ea-11a83f96aa85.png)
https://cloud.githubusercontent.com/assets/2068130/6474614/7bfa3518-c202-11e4-81ea-11a83f96aa85.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6474625/8f95ed4c-c202-11e4-9ec1-4bd700575752.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Samsung Smart View
**Bundle ID:** com.samsung.smartview2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=858283863">858283863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/samsung-smart-view/id858283863?mt=8&uo=4">https://itunes.apple.com/us/app/samsung-smart-view/id858283863?mt=8&uo=4</a>
**App Version:** 1.5.6
**Seller:** Samsung Electronics
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/samsung-electronics-co.ltd./id359580642?uo=4>© Samsung Electronics CO.LTD.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/af/ef/d2/afefd250-ee7e-83b0-59d3-dcb5605cc803/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17320052/d5cb78dc-5891-11e6-8cb4-1fd563a873e8.png)
https://cloud.githubusercontent.com/assets/2068130/17320052/d5cb78dc-5891-11e6-8cb4-1fd563a873e8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17320062/e2aa5686-5891-11e6-9f2c-b696df0839a3.png
