### ISSUE TITLE
WordBrain

### ISSUE THREAD

**Issue by hiemss** [glasklart/hd#5303]
**App Name:** WordBrain
**Bundle ID:** com.tailworks.wordbrain
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=708600202">708600202</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wordbrain/id708600202?mt=8&uo=4">https://itunes.apple.com/us/app/wordbrain/id708600202?mt=8&uo=4</a>
**App Version:** 1.3.9
**Seller:** Gaming on the tail AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/gaming-on-the-tail-ab/id920535928?uo=4>© Gaming on the tail AB</a>
**Supported Devices:** iPad2Wifi, iPodTouchFourthGen, iPhone5c, iPadFourthGen4G, iPhone5, iPhone4, iPhone6, iPodTouchFifthGen, iPadMini, iPhone4S, iPhone-3GS, iPadFourthGen, iPad23G, iPhone5s, iPadThirdGen, iPadMini4G, iPadThirdGen4G, iPhone6Plus
**Original Artwork:**
<img src="http://a141.phobos.apple.com/us/r30/Purple5/v4/49/a0/74/49a0743e-3342-4e04-93f7-6968bf9a5bf9/mzl.vdulglxs.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6444631/c23393b0-c0f6-11e4-97a2-893f7dc32553.png)

**Comment by hiemss** [comment]
https://cloud.githubusercontent.com/assets/11254886/6444631/c23393b0-c0f6-11e4-97a2-893f7dc32553.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11254886/6444631/c23393b0-c0f6-11e4-97a2-893f7dc32553.png)
source:
![wordbrain-src](https://cloud.githubusercontent.com/assets/11254886/6444639/d2c00b28-c0f6-11e4-9223-9b7faba9329a.png)

**Comment by dreamnet** [comment]
@hiemss :+1: 
Correct source:
https://cloud.githubusercontent.com/assets/2068130/6451101/809c1d7e-c12c-11e4-91eb-9ff71cad0743.png
