### ISSUE TITLE
Amazon

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5304]
**App Name:** Amazon
**Bundle ID:** com.amazon.AmazonDE
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348712880">348712880</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/amazon/id348712880?mt=8&uo=4">https://itunes.apple.com/de/app/amazon/id348712880?mt=8&uo=4</a>
**App Version:** 4.4.1
**Seller:** Amazon Eurasia Holdings Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/amazon/id335187486?uo=4>© Amazon</a>
**Supported Devices:** iPadFourthGen, iPadFourthGen4G, iPad2Wifi, iPadMini4G, iPhone6Plus, iPhone4, iPodTouchFifthGen, iPhone5s, iPhone4S, iPad23G, iPadThirdGen4G, iPhone5c, iPadThirdGen, iPhone6, iPadMini, iPhone5
**Original Artwork:**
<img src="http://a1616.phobos.apple.com/us/r30/Purple3/v4/b7/6e/76/b76e76b5-3ad8-fd8a-2235-902e8ef4f8ad/mzl.mouvtkqb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6473609/b006dac6-c1fa-11e4-935c-beb3034ae999.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6473609/b006dac6-c1fa-11e4-935c-beb3034ae999.png)
https://cloud.githubusercontent.com/assets/2068130/6473609/b006dac6-c1fa-11e4-935c-beb3034ae999.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6473469/d013c280-c1f9-11e4-8fd6-6928226b411b.png

**Comment by Anuskuss** [comment]
@dreamnet I know we want to replicate the original icon, but I don't like the basket and would appreciate only the **amazon** logo in the middle. What do you think about it?

**Comment by dreamnet** [comment]
@Anuskuss I like it as it is.
