### ISSUE TITLE
EPIX

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5305]
**App Name:** EPIX
**Bundle ID:** com.epix.epixhd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=430018488">430018488</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/epix/id430018488?uo=4">https://apps.apple.com/us/app/epix/id430018488?uo=4</a>
**App Version:** 113.0
**Seller:** EPIX Entertainment LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/epix-entertainment-llc/id430018491?uo=4">© EPIX Entertainment LLC</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/65/fe/a1/65fea1d8-8b75-47c9-53ed-870b0137cbda/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387823-987d2680-9aa9-11e9-8f4d-a782b40a539e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6473019/a7ecbb3e-c1f6-11e4-9738-41bbe188ba78.png)
https://cloud.githubusercontent.com/assets/2068130/6473019/a7ecbb3e-c1f6-11e4-9738-41bbe188ba78.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6473026/b68c3e12-c1f6-11e4-9ed0-8c9978d6b0e3.png

**Comment by boxermansr** [comment]
@dreamnet Thanks :)

**Comment by dreamnet** [comment]
@boxermansr No problem!

**Comment by l8er4now** [comment]
Needs to be resized.

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18616481/69bda30e-7d8a-11e6-80bd-3a193dbfbeb7.png)

https://cloud.githubusercontent.com/assets/3704186/18616481/69bda30e-7d8a-11e6-80bd-3a193dbfbeb7.png

https://cloud.githubusercontent.com/assets/3704186/18616485/721473e8-7d8a-11e6-9ab6-6c7d45bfcfc8.png

**Comment by dreamnet** [comment]
Already in the master.

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387823-987d2680-9aa9-11e9-8f4d-a782b40a539e.png)
https://user-images.githubusercontent.com/20930745/60387823-987d2680-9aa9-11e9-8f4d-a782b40a539e.png

Source:
https://user-images.githubusercontent.com/20930745/60387824-99ae5380-9aa9-11e9-94ac-f106131b3eda.png
