### ISSUE TITLE
Showtime Anytime

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5306]
**App Name:** Showtime Anytime
**Bundle ID:** com.showtime.showtimeanytime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484232467">484232467</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/showtime-anytime/id484232467?mt=8&uo=4">https://itunes.apple.com/us/app/showtime-anytime/id484232467?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Showtime Networks Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/showtime-networks-inc./id315708143?uo=4>© Showtime Networks Inc.</a>
**Supported Devices:** iPhone4, iPadFourthGen, iPadMini, iPadThirdGen, iPad23G, iPad2Wifi, iPadThirdGen4G, iPodTouchFourthGen, iPhone6, iPhone-3GS, iPadMini4G, iPhone5c, iPadFourthGen4G, iPhone6Plus, iPhone4S, iPhone5s, iPodTouchFifthGen, iPhone5
**Original Artwork:**
<img src="http://a144.phobos.apple.com/us/r30/Purple3/v4/40/98/16/40981646-8c33-0230-3378-24191de62d6c/mzl.dhxvbzcf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6472920/031103cc-c1f6-11e4-82ca-024e28304564.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6472920/031103cc-c1f6-11e4-82ca-024e28304564.png)
https://cloud.githubusercontent.com/assets/2068130/6472920/031103cc-c1f6-11e4-82ca-024e28304564.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6472926/11b3c414-c1f6-11e4-81b2-bc85d1fdb9dd.png

**Comment by boxermansr** [comment]
@dreamnet Thanks again :)

**Comment by dreamnet** [comment]
@boxermansr Jup! :smile:
