### ISSUE TITLE
Comedy Central

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5308]
**App Name:** Comedy Central
**Bundle ID:** com.mtvn.ccnetwork
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=799551807">799551807</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/comedy-central/id799551807?mt=8&uo=4">https://itunes.apple.com/us/app/comedy-central/id799551807?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** Viacom International Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/comedy-central/id526772848?uo=4>© Comedy Central</a>
**Supported Devices:** iPhone4, iPadMini, iPadThirdGen4G, iPhone5s, iPadMini4G, iPhone6, iPadThirdGen, iPadFourthGen, iPhone6Plus, iPhone4S, iPodTouchFifthGen, iPhone5, iPad2Wifi, iPad23G, iPadFourthGen4G, iPhone5c
**Original Artwork:**
<img src="http://a212.phobos.apple.com/us/r30/Purple3/v4/6f/c2/5b/6fc25bea-419e-af78-7952-bc870d8b952c/mzl.dnfnvjsa.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6497693/1b736886-c2b1-11e4-946f-871f65d3cb7b.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6490949/f56d347a-c277-11e4-9b3d-02956a015e79.png)
https://cloud.githubusercontent.com/assets/10950389/6490949/f56d347a-c277-11e4-9b3d-02956a015e79.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6490957/001cddbc-c278-11e4-90c9-2aa69667e307.png

**Comment by MagnaMike** [comment]
@zmathiasz Close, but in this case the icon shouldn't actually be centered.

![2x](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6497693/1b736886-c2b1-11e4-946f-871f65d3cb7b.png)
https://cloud.githubusercontent.com/assets/2236254/6497693/1b736886-c2b1-11e4-946f-871f65d3cb7b.png
---
Source:
https://cloud.githubusercontent.com/assets/2236254/6497696/1fdf4ad4-c2b1-11e4-818a-6605c0731918.png

**Comment by zmathiasz** [comment]
Now that you post it I see that. Good catch! :)
