### ISSUE TITLE
Watch truTV

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5309]
**App Name:** Watch truTV
**Bundle ID:** com.turner.truTV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=396972659">396972659</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watch-trutv/id396972659?mt=8&uo=4">https://itunes.apple.com/us/app/watch-trutv/id396972659?mt=8&uo=4</a>
**App Version:** 5.1.1
**Seller:** Turner Broadcasting System, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/trutv/id405623540?uo=4>© truTV</a>
**Supported Devices:** iPhone4S, iPhone4, iPadMini4G, iPadMini, iPadFourthGen, iPadFourthGen4G, iPodTouchFifthGen, iPhone6, iPhone5s, iPhone5c, iPhone6Plus, iPadThirdGen4G, iPhone5, iPadThirdGen, iPad2Wifi, iPad23G
**Original Artwork:**
<img src="http://a1272.phobos.apple.com/us/r30/Purple3/v4/a1/c4/ff/a1c4ffb9-2ca2-5c0e-4be8-084fd3ad6f09/mzl.jsiznjlq.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6490907/97d7bccc-c277-11e4-89b0-66dff225cfaf.png)

**Comment by boxermansr** [comment]
I'd sort of prefer it without the WATCH part, but whatever makes it easiest. Thanks.

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6490882/7483fdd0-c277-11e4-84fe-77a248ef9a69.png)
https://cloud.githubusercontent.com/assets/10950389/6490882/7483fdd0-c277-11e4-84fe-77a248ef9a69.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6490898/823119ea-c277-11e4-9ba1-ccef4f3607c9.png

**Comment by zmathiasz** [comment]
Alternative:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6490907/97d7bccc-c277-11e4-89b0-66dff225cfaf.png)
https://cloud.githubusercontent.com/assets/10950389/6490907/97d7bccc-c277-11e4-89b0-66dff225cfaf.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6490915/a54cf610-c277-11e4-900f-83651945229a.png

**Comment by boxermansr** [comment]
I prefer the one without the WATCH -- in the end I don't have the app on my device anymore since my cable provider doesn't let me access content but I'm sure someone else would like to have it themed.

Thanks.

**Comment by MagnaMike** [comment]
Okay, going with the alternative then @boxermansr :+1:
