### ISSUE TITLE
Spike TV

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5310]
**App Name:** Spike TV
**Bundle ID:** com.mtvn.SPIKE
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=906788127">906788127</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spike-tv/id906788127?mt=8&uo=4">https://itunes.apple.com/us/app/spike-tv/id906788127?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** Viacom International Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/spike-tv/id316796671?mt=8&uo=4>© Spike TV</a>
**Supported Devices:** iPadThirdGen, iPodTouchFifthGen, iPhone6, iPadFourthGen4G, iPadMini, iPhone5, iPhone6Plus, iPhone4S, iPhone5s, iPhone4, iPhone5c, iPad2Wifi, iPad23G, iPadThirdGen4G, iPadFourthGen, iPadMini4G
**Original Artwork:**
<img src="http://a1501.phobos.apple.com/us/r30/Purple1/v4/c6/c7/70/c6c77091-5277-5079-7bc8-b4472e065769/mzl.kchtzvih.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6535216/772c3318-c443-11e4-957b-3258fbcfdef3.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6490787/d4fa79ec-c276-11e4-9dde-3f9ad1f37b65.png)
https://cloud.githubusercontent.com/assets/10950389/6490787/d4fa79ec-c276-11e4-9dde-3f9ad1f37b65.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6490796/e120f1f6-c276-11e4-96bd-a312820f31eb.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6535216/772c3318-c443-11e4-957b-3258fbcfdef3.png)
https://cloud.githubusercontent.com/assets/2068130/6535216/772c3318-c443-11e4-957b-3258fbcfdef3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6535221/8a0937ec-c443-11e4-885e-192d4a9b4a60.png
@zmathiasz Made just some small corrections, credits are going to you.
