### ISSUE TITLE
Printer Pro - print documents, photos, web pages and email attachments

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5311]
**App Name:** Printer Pro - print documents, photos, web pages and email attachments
**Bundle ID:** com.readdle.PrinterPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393313223">393313223</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/printer-pro-print-documents/id393313223?mt=8&uo=4">https://itunes.apple.com/us/app/printer-pro-print-documents/id393313223?mt=8&uo=4</a>
**App Version:** 5.4.0
**Seller:** Igor Zhadanov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/readdle/id285035419?uo=4>© Readdle</a>
**Supported Devices:** iPhone6Plus, iPhone6, iPhone4, iPhone5s, iPad2Wifi, iPadThirdGen, iPadFourthGen4G, iPad23G, iPhone4S, iPhone5, iPadMini, iPadFourthGen, iPadMini4G, iPadThirdGen4G, iPodTouchFifthGen, iPhone5c
**Original Artwork:**
<img src="http://a541.phobos.apple.com/us/r30/Purple3/v4/40/50/a9/4050a966-9cee-857f-05ce-f4ff0df20bbe/mzl.daufmcuo.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6497807/890b4b2e-c2b2-11e4-8f60-6be6cead3d74.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6497807/890b4b2e-c2b2-11e4-8f60-6be6cead3d74.png)
https://cloud.githubusercontent.com/assets/10950389/6497807/890b4b2e-c2b2-11e4-8f60-6be6cead3d74.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6497810/947a761a-c2b2-11e4-893c-4bc2b1fcf1fe.png

**Comment by MagnaMike** [comment]
@zmathiasz :ok_hand:
