### ISSUE TITLE
DRAGON QUEST

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5312]
**App Name:** DRAGON QUEST
**Bundle ID:** com.square-enix.dq1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911201894">911201894</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dragon-quest/id911201894?mt=8&uo=4">https://itunes.apple.com/us/app/dragon-quest/id911201894?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone-3GS, iPadFourthGen4G, iPadMini, iPhone6, iPhone4S, iPodTouchFifthGen, iPhone6Plus, iPadThirdGen4G, iPad23G, iPhone4, iPhone5s, iPodTouchFourthGen, iPadMini4G, iPadThirdGen, iPadWifi, iPad2Wifi, iPodTouchThirdGen, iPad3G, iPadFourthGen, iPhone5c, iPhone5
**Original Artwork:**
<img src="http://a1291.phobos.apple.com/us/r30/Purple5/v4/2f/fa/1c/2ffa1cdd-cb74-6386-a6a2-517cc9e58e40/mzl.mjwgbpev.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6535686/3f60323c-c447-11e4-94ee-b26f89af18d8.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6497886/82add6ec-c2b3-11e4-83c6-f4426ecd9950.png)
https://cloud.githubusercontent.com/assets/10950389/6497886/82add6ec-c2b3-11e4-83c6-f4426ecd9950.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6497890/8f8c3dc2-c2b3-11e4-848b-6f40cb57b67c.png

**Comment by MagnaMike** [comment]
@zmathiasz Great! :+1:

**Comment by dreamnet** [comment]
Just rounded the corners:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6535686/3f60323c-c447-11e4-94ee-b26f89af18d8.png)
https://cloud.githubusercontent.com/assets/2068130/6535686/3f60323c-c447-11e4-94ee-b26f89af18d8.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6535698/4fc42980-c447-11e4-9811-38a2f66145e9.png

**Comment by zmathiasz** [comment]
@dreamnet I'm not sure how to round the corners easily to match the padding. Are there certain dimensions you use? Photoshop only though. :)

**Comment by dreamnet** [comment]
@zmathiasz Well, yes, but I am using illustrator... for the sources, I am using a 1024x1024px rectangle with 180px corner radius, like this:
https://cloud.githubusercontent.com/assets/2068130/6540158/37b2a662-c48f-11e4-8d3c-4436bdec9d7b.png
or inverted:
https://cloud.githubusercontent.com/assets/2068130/6540167/7704bbd4-c48f-11e4-8a45-fad42855cda0.png
Maybe you can use these images to cut out the rounded corners in Photoshop.
