### ISSUE TITLE
DRAGON QUEST II

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5313]
**App Name:** DRAGON QUEST II
**Bundle ID:** com.square-enix.dq2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911205290">911205290</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dragon-quest-ii/id911205290?mt=8&uo=4">https://itunes.apple.com/us/app/dragon-quest-ii/id911205290?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPodTouchThirdGen, iPhone5c, iPad3G, iPadFourthGen, iPhone6, iPhone6Plus, iPodTouchFifthGen, iPad23G, iPhone5, iPhone4S, iPadWifi, iPhone5s, iPad2Wifi, iPhone4, iPhone-3GS, iPadMini, iPadMini4G, iPadThirdGen4G, iPodTouchFourthGen, iPadThirdGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://a589.phobos.apple.com/us/r30/Purple5/v4/43/f3/41/43f3414f-afe6-89a8-2a2a-f90eabc88492/pr_source.png?downloadKey=1425532574_df96be18528a5bdee42453af598d381e" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6535801/0c337076-c448-11e4-82dc-939fa808a13e.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6497923/e3f9f106-c2b3-11e4-9913-1e6f51c0484b.png)
https://cloud.githubusercontent.com/assets/10950389/6497923/e3f9f106-c2b3-11e4-9913-1e6f51c0484b.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6497927/f0c7730e-c2b3-11e4-901f-bfc46acf11d3.png

**Comment by MagnaMike** [comment]
@zmathiasz Yep!

**Comment by dreamnet** [comment]
Also rounded the corners:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6535801/0c337076-c448-11e4-82dc-939fa808a13e.png)
https://cloud.githubusercontent.com/assets/2068130/6535801/0c337076-c448-11e4-82dc-939fa808a13e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6535812/1a36d578-c448-11e4-979e-2e57ce6af08c.png
