### ISSUE TITLE
DRAGON QUEST III

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5314]
**App Name:** DRAGON QUEST III
**Bundle ID:** com.square-enix.dq3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911208088">911208088</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dragon-quest-iii/id911208088?mt=8&uo=4">https://itunes.apple.com/us/app/dragon-quest-iii/id911208088?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone4, iPadFourthGen, iPadWifi, iPodTouchFifthGen, iPad3G, iPad2Wifi, iPhone5, iPadMini, iPhone6Plus, iPhone6, iPhone5s, iPadThirdGen, iPodTouchFourthGen, iPhone5c, iPodTouchThirdGen, iPad23G, iPhone-3GS, iPadFourthGen4G, iPhone4S, iPadThirdGen4G, iPadMini4G
**Original Artwork:**
<img src="http://a1482.phobos.apple.com/us/r30/Purple3/v4/63/88/a4/6388a40e-d44a-f95e-9fa2-26bb4e70af24/mzl.xewlkagh.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6535885/ce2795ea-c448-11e4-8486-4619e48a70d2.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6498715/34f0aaa6-c2bd-11e4-8b9c-3f526164dea0.png)
https://cloud.githubusercontent.com/assets/10950389/6498715/34f0aaa6-c2bd-11e4-8b9c-3f526164dea0.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6498720/4438ce44-c2bd-11e4-848c-1e084466f07b.png

**Comment by dreamnet** [comment]
@zmathiasz Great one. :+1: I did a little cleanup and rounded the corners:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6535885/ce2795ea-c448-11e4-8486-4619e48a70d2.png)
https://cloud.githubusercontent.com/assets/2068130/6535885/ce2795ea-c448-11e4-8486-4619e48a70d2.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6535888/dc5c99d0-c448-11e4-9cdb-44993c94577b.png
