### ISSUE TITLE
DRAGON QUEST IV Chapters of the Chosen

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5315]
**App Name:** DRAGON QUEST IV Chapters of the Chosen
**Bundle ID:** com.square-enix.dq4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=847381935">847381935</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dragon-quest-iv-chapters-chosen/id847381935?mt=8&uo=4">https://itunes.apple.com/us/app/dragon-quest-iv-chapters-chosen/id847381935?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone6Plus, iPad2Wifi, iPadMini4G, iPhone5, iPhone4S, iPad23G, iPhone6, iPhone5s, iPhone5c, iPhone4, iPadMini, iPadFourthGen, iPodTouchFifthGen, iPadThirdGen, iPadThirdGen4G, iPadFourthGen4G
**Original Artwork:**
<img src="http://a148.phobos.apple.com/us/r30/Purple4/v4/ea/91/ae/ea91ae4f-f358-717a-1e60-bd59c9edfe37/mzl.wkspcwiz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6536027/36c8ce06-c44a-11e4-86e6-226a41981892.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6511163/be87d4d0-c338-11e4-9923-186c57a1295e.png)
https://cloud.githubusercontent.com/assets/10950389/6511163/be87d4d0-c338-11e4-9923-186c57a1295e.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6511166/cbb86cbe-c338-11e4-9857-8ba697292d07.png

**Comment by dreamnet** [comment]
@zmathiasz :+1: Rounded corners, little cleanup:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6536027/36c8ce06-c44a-11e4-86e6-226a41981892.png)
https://cloud.githubusercontent.com/assets/2068130/6536027/36c8ce06-c44a-11e4-86e6-226a41981892.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6536039/475e4048-c44a-11e4-9656-efcc02e68ac2.png
