### ISSUE TITLE
DRAGON QUEST V

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5316]
**App Name:** DRAGON QUEST V
**Bundle ID:** com.square-enix.dq5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=933113994">933113994</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dragon-quest-v/id933113994?mt=8&uo=4">https://itunes.apple.com/us/app/dragon-quest-v/id933113994?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPadFourthGen4G, iPhone6Plus, iPadMini, iPhone4, iPad2Wifi, iPodTouchFifthGen, iPadMini4G, iPadThirdGen, iPhone5, iPhone4S, iPad23G, iPadThirdGen4G, iPhone5c, iPhone5s, iPhone6, iPadFourthGen
**Original Artwork:**
<img src="http://a1595.phobos.apple.com/us/r30/Purple5/v4/71/ab/65/71ab6515-17f4-98b8-233f-dd0a33087837/pr_source.png?downloadKey=1425536776_7f9012bb70434cff3c232f552a90c95b" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6536117/15c4ff6c-c44b-11e4-9c39-21971601c35b.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6511385/7c338b4a-c33a-11e4-998d-38d818008675.png)
https://cloud.githubusercontent.com/assets/10950389/6511385/7c338b4a-c33a-11e4-998d-38d818008675.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6511390/8aa27f2e-c33a-11e4-9b1f-ad826668a9f1.png

**Comment by dreamnet** [comment]
@zmathiasz :+1: Rounded corners, little cleanup:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6536117/15c4ff6c-c44b-11e4-9c39-21971601c35b.png)
https://cloud.githubusercontent.com/assets/2068130/6536117/15c4ff6c-c44b-11e4-9c39-21971601c35b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6536124/26c13312-c44b-11e4-8f04-ec58565b5bdd.png
