### ISSUE TITLE
DRAGON QUEST VIII

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5317]
**App Name:** DRAGON QUEST VIII
**Bundle ID:** com.square-enix.dq8
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=862972069">862972069</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dragon-quest-viii/id862972069?mt=8&uo=4">https://itunes.apple.com/us/app/dragon-quest-viii/id862972069?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPadFourthGen, iPhone4S, iPhone4, iPad23G, iPhone6, iPhone5s, iPadFourthGen4G, iPadThirdGen, iPadMini, iPad2Wifi, iPhone6Plus, iPodTouchFourthGen, iPadThirdGen4G, iPadMini4G, iPodTouchFifthGen, iPhone5c, iPhone5
**Original Artwork:**
<img src="http://a598.phobos.apple.com/us/r30/Purple/v4/4c/9e/6d/4c9e6d79-7919-d4f6-5600-4d3907a8af04/mzl.tykdwykc.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6536285/9d01691a-c44c-11e4-95f0-5b38b80c972f.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6511406/a6e29ef8-c33a-11e4-8d2c-30ba45d523ff.png)
https://cloud.githubusercontent.com/assets/10950389/6511406/a6e29ef8-c33a-11e4-8d2c-30ba45d523ff.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6511414/b2a9fdbc-c33a-11e4-8eb7-f61683ea9ab7.png

**Comment by dreamnet** [comment]
@zmathiasz :+1: Rounded corners, little cleanup:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6536285/9d01691a-c44c-11e4-95f0-5b38b80c972f.png)
https://cloud.githubusercontent.com/assets/2068130/6536285/9d01691a-c44c-11e4-95f0-5b38b80c972f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6536293/ad82b744-c44c-11e4-86dc-0579b3dac65b.png
