### ISSUE TITLE
aboalarm

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#5318]
**App Name:** aboalarm
**Bundle ID:** de.aboalarm.kuendigungsmaschine
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409993189">409993189</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/aboalarm/id409993189?mt=8&uo=4">https://itunes.apple.com/de/app/aboalarm/id409993189?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** Aboalarm GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/aboalarm-gmbh/id409993192?uo=4>© Aboalarm GmbH</a>
**Supported Devices:** iPodTouchFourthGen, iPodTouchFifthGen, iPadMini, iPhone5c, iPadThirdGen4G, iPadThirdGen, iPad23G, iPhone6, iPhone4S, iPad2Wifi, iPhone5s, iPhone5, iPhone6Plus, iPadMini4G, iPadFourthGen, iPhone-3GS, iPhone4, iPadFourthGen4G
**Original Artwork:**
<img src="http://a448.phobos.apple.com/us/r30/Purple3/v4/2a/08/d2/2a08d249-44ac-6545-e7ed-f2dd0c3c1c10/mzl.qgqlzatk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6531923/2ce60208-c43d-11e4-98b9-a4ced6b97698.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6531923/2ce60208-c43d-11e4-98b9-a4ced6b97698.png)
https://cloud.githubusercontent.com/assets/2068130/6531923/2ce60208-c43d-11e4-98b9-a4ced6b97698.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6531932/39c37596-c43d-11e4-8533-e1b9e4b070c0.png
