### ISSUE TITLE
BIG direkt

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#5319]
**App Name:** BIG direkt
**Bundle ID:** de.big-direkt.app.mobgs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426961160">426961160</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/big-direkt/id426961160?mt=8&uo=4">https://itunes.apple.com/us/app/big-direkt/id426961160?mt=8&uo=4</a>
**App Version:** 1.10.0
**Seller:** BIG direkt gesund - Bundesinnungskrankenkasse
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/big-direkt-gesund/id426961163?uo=4>© BIG direkt gesund</a>
**Supported Devices:** iPhone5s, iPadMini4G, iPodTouchFourthGen, iPad23G, iPadThirdGen4G, iPad2Wifi, iPadThirdGen, iPhone6, iPhone4, iPadFourthGen, iPhone5c, iPhone5, iPadFourthGen4G, iPhone-3GS, iPhone4S, iPadMini, iPodTouchFifthGen, iPhone6Plus
**Original Artwork:**
<img src="http://a1311.phobos.apple.com/us/r30/Purple/v4/e6/08/4a/e6084a84-c89c-e448-ce98-63ae9ba1c8e6/mzl.fhjegjrv.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6532183/e74afefe-c43e-11e4-980c-63d8ec167b6c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6532183/e74afefe-c43e-11e4-980c-63d8ec167b6c.png)
https://cloud.githubusercontent.com/assets/2068130/6532183/e74afefe-c43e-11e4-980c-63d8ec167b6c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6532193/f47ddc4a-c43e-11e4-8c6f-e13a61281600.png
