### ISSUE TITLE
Brewers Choice

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5320]
**App Name:** BrewersChoice
**Bundle ID:** com.nanosys.Brewers-Choice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=898702839">898702839</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/brewerschoice/id898702839?mt=8&uo=4">https://itunes.apple.com/au/app/brewerschoice/id898702839?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Nanosys Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/artist/nanosys-pty-ltd/id593312277?uo=4>© Nanosys Pty Ltd</a>
**Supported Devices:** iPadFourthGen4G, iPadFourthGen, iPhone5, iPad23G, iPadMini4G, iPhone5s, iPad2Wifi, iPhone6, iPhone4S, iPadMini, iPhone6Plus, iPhone4, iPadThirdGen, iPadThirdGen4G, iPodTouchFifthGen, iPhone5c
**Original Artwork:**
<img src="http://a1447.phobos.apple.com/us/r30/Purple3/v4/e8/2f/3c/e82f3c68-a208-ba35-73e9-f0d5bc88765c/pr_source.png?downloadKey=1425614504_e0ac389e88b82146221ec72add5a471b" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6537083/b70c8266-c453-11e4-9e3b-c6a32b1d990d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6537083/b70c8266-c453-11e4-9e3b-c6a32b1d990d.png)
https://cloud.githubusercontent.com/assets/2068130/6537083/b70c8266-c453-11e4-9e3b-c6a32b1d990d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6537092/c6d1f1d6-c453-11e4-9369-169f4ad66a9f.png
