### ISSUE TITLE
Gym Hero Pro

### ISSUE THREAD

**Issue by yetiboy** [glasklart/hd#5321]
**App Name:** Gym Hero Pro
**Bundle ID:** bigmike.gymheropro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=696695228">696695228</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gym-hero-pro/id696695228?uo=4">https://apps.apple.com/us/app/gym-hero-pro/id696695228?uo=4</a>
**App Version:** 2.27
**Seller:** Big Mike Alright UG haftungsbeschraenkt
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/big-mike-alright/id459595712?uo=4">© Big Mike Alright</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/d4/b1/07/d4b10721-7f8e-21f6-8d9c-6ece7b96c2ad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60465677-fa789000-9c51-11e9-880c-2b30c81a01fa.png)

**Comment by MagnaMike** [comment]
@yetiboy Please use the full title when naming the issue. Thanks!

**Comment by yetiboy** [comment]
Sorry about that. Anything I need to do to fix t or is it good now?

**Comment by MagnaMike** [comment]
@yetiboy No problem, not a big deal - just giving you the heads up. All good now, I changed the title. :+1:

**Comment by yetiboy** [comment]
@MagnaMike All right, thanks.

Any issues with my submitting an icon to my own request?

**Comment by MagnaMike** [comment]
@yetiboy None at all. We like to encourage people to make icons - its a group effort! Just please follow the [guidlines](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon). Feel free to ask any questions if you're stuck on something.

**Comment by yetiboy** [comment]
![gym-hero-pro](https://cloud.githubusercontent.com/assets/11370620/6546375/bf6fa3e0-c587-11e4-8fcd-2cd99a0f1967.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11370620/6546375/bf6fa3e0-c587-11e4-8fcd-2cd99a0f1967.png)

**Comment by MagnaMike** [comment]
@yetiboy Can you try adding more details to the mouth, like the teeth? And also include the 1024px by 1024px source image as outlined in the guidlines, thanks.

**Comment by yetiboy** [comment]
Ah, sorry again - didn't read far enough down the page I guess. I'm on it.

**Comment by yetiboy** [comment]
Hope I did it right this time!

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11370620/6547236/bd0c8c96-c5a8-11e4-94f4-0b8b8178f905.png)

![gym-hero-pro-2](https://cloud.githubusercontent.com/assets/11370620/6547236/bd0c8c96-c5a8-11e4-94f4-0b8b8178f905.png)
![687474703a2f2f61313433352e70686f626f732e6170706c652e636f6d2f75732f7233302f507572706c65332f76342f36612f65632f30642f36616563306432382d616635342d306535382d363464342d3437373835333639306437622f6d7a6c2e686c787762756a782e706e67](https://cloud.githubusercontent.com/assets/11370620/6547237/c289600e-c5a8-11e4-855b-9af1dfc64d79.png)

**Comment by MagnaMike** [comment]
@yetiboy Not quite. This would be an example of a source image:

![](https://cloud.githubusercontent.com/assets/2236254/6544204/cd67123c-c512-11e4-9259-9bbf54bd87e2.png)

What you posted was the original artwork, which is like posting this (the original artwork for the icon source I posted above):
![](https://camo.githubusercontent.com/ee1e0210695f5fbe475d6935a7f865407dce4ee1/687474703a2f2f613939392e70686f626f732e6170706c652e636f6d2f75732f7233302f507572706c65332f76342f35652f65632f64372f35656563643732312d373031342d626264392d306236322d3636313434373539333537302f6d7a6c2e63656d74677962662e706e67)

**Comment by MagnaMike** [comment]
See this this issue, #5322, and my comment as how to post an icon.

**Comment by dreamnet** [comment]
@yetiboy @MagnaMike means something like this:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6547290/3aac4116-c5d4-11e4-96bd-ab994fd0874d.png)
https://cloud.githubusercontent.com/assets/2068130/6547290/3aac4116-c5d4-11e4-96bd-ab994fd0874d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6547262/d0f0af5a-c5d3-11e4-8926-6a25ad625819.png

**Comment by yetiboy** [comment]
Okay, finally get what you mean by source. @dreamnet did a better job anyway :)

**Comment by dreamnet** [comment]
@yetiboy You did a good job anyway. Keep on! :+1:

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60465677-fa789000-9c51-11e9-880c-2b30c81a01fa.png)
https://user-images.githubusercontent.com/2068130/60465677-fa789000-9c51-11e9-880c-2b30c81a01fa.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60465700-0b290600-9c52-11e9-9791-484058d8dbcf.png
