### ISSUE TITLE
Weather Office Free

### ISSUE THREAD

**Issue by yetiboy** [glasklart/hd#5322]
**App Name:** Weather Office Free
**Bundle ID:** com.x2studios.Weather-Office-Free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=381972414">381972414</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-office-free/id381972414?mt=8&uo=4">https://itunes.apple.com/us/app/weather-office-free/id381972414?mt=8&uo=4</a>
**App Version:** 5.0.2
**Seller:** X2 Studios Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/x2-studios/id320586904?uo=4>© X2 Studios</a>
**Supported Devices:** iPodTouchThirdGen, iPhone5, iPadFourthGen, iPadFourthGen4G, iPadThirdGen4G, iPhone4, iPadThirdGen, iPodTouchFourthGen, iPhone6Plus, iPad2Wifi, iPhone5s, iPhone6, iPadMini, iPadWifi, iPadMini4G, iPad23G, iPad3G, iPhone5c, iPodTouchFifthGen, iPhone-3GS, iPhone4S
**Original Artwork:**
<img src="http://a999.phobos.apple.com/us/r30/Purple3/v4/5e/ec/d7/5eecd721-7014-bbd9-0b62-661447593570/mzl.cemtgybf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6544205/d1262d90-c512-11e4-9425-1920010ed293.png)

**Comment by MagnaMike** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2236254/6544205/d1262d90-c512-11e4-9425-1920010ed293.png)
https://cloud.githubusercontent.com/assets/2236254/6544205/d1262d90-c512-11e4-9425-1920010ed293.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6544204/cd67123c-c512-11e4-9259-9bbf54bd87e2.png
