### ISSUE TITLE
WEB.DE Mail

### ISSUE THREAD

**Issue by pishit** [glasklart/hd#5325]
**App Name:** WEB.DE Mail
**Bundle ID:** de.web.mobilenavigator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368948250">368948250</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/web.de-mail/id368948250?mt=8&uo=4">https://itunes.apple.com/us/app/web.de-mail/id368948250?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** 1&1 Mail & Media GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/1-1-mail-media-gmbh/id308299517?uo=4>© 1&1 Mail & Media GmbH</a>
**Supported Devices:** iPhone6, iPhone5s, iPad2Wifi, iPhone4S, iPhone4, iPhone5, iPad23G, iPadThirdGen4G, iPadMini, iPhone5c, iPodTouchFifthGen, iPadFourthGen4G, iPhone6Plus, iPadMini4G, iPadFourthGen, iPadThirdGen
**Original Artwork:**
<img src="http://a1713.phobos.apple.com/us/r30/Purple1/v4/5e/9e/44/5e9e4439-6a96-8900-8556-67635347c20d/mzl.urvrjvka.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6582288/f870aca2-c721-11e4-82c7-94b116fbbc58.png)

**Comment by pishit** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11317341/6576739/789dac56-c739-11e4-98fb-4b856c33ff4e.png)
https://cloud.githubusercontent.com/assets/11317341/6576739/789dac56-c739-11e4-98fb-4b856c33ff4e.png

**Comment by ivanov007** [comment]
@pishit I don't know it looks a little bit stretched, maybe something like this?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6582288/f870aca2-c721-11e4-82c7-94b116fbbc58.png)
https://cloud.githubusercontent.com/assets/3090247/6582288/f870aca2-c721-11e4-82c7-94b116fbbc58.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/6582284/f783b76c-c721-11e4-8e34-68fa657cddfd.png

oh and also you are missing the source file

**Comment by MagnaMike** [comment]
Taking @ivanov007's :+1:
