### ISSUE TITLE
Best Funny Videos - Comedy Jokes, Pictures, and Music For Download

### ISSUE THREAD

**Issue by pishit** [glasklart/hd#5326]
**App Name:** Best Funny Videos - Comedy Jokes, Pictures, and Music For Download
**Bundle ID:** com.sepiasoftware.bestvines
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=715221909">715221909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/best-funny-videos-comedy-jokes/id715221909?mt=8&uo=4">https://itunes.apple.com/us/app/best-funny-videos-comedy-jokes/id715221909?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Sepia Software LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sepia-software-llc/id424779886?uo=4>© Sepia Software LLC</a>
**Supported Devices:** iPhone5, iPadFourthGen4G, iPhone5c, iPhone6, iPhone4, iPadMini, iPadThirdGen, iPad23G, iPhone5s, iPodTouchFifthGen, iPhone4S, iPadFourthGen, iPad2Wifi, iPhone6Plus, iPadThirdGen4G, iPadMini4G
**Original Artwork:**
<img src="http://a73.phobos.apple.com/us/r30/Purple3/v4/97/99/39/979939e2-aa7c-e2f7-17ac-695273c9eb74/mzl.vfekqqcf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6623108/3604d532-c8e1-11e4-86ac-b0c04ba44eae.png)

**Comment by pishit** [comment]
![glasklart_ios7_icon_template - best vines](https://cloud.githubusercontent.com/assets/11317341/6575874/20de956c-c733-11e4-822f-efe8b1665f26.png)

**Comment by ivanov007** [comment]
@pishit I see you posted the icon directly without the preview, also I think you are using layers can you repost the image with the preview link and source link and the icon on one layer flattened?

**Comment by pishit** [comment]
@ivanov007
i dont have the original source anymore but i can recreate it if you want to see it.
i really just used one layer and copied the effects of the sample icons on it and i set the area (or howerver its called in the eng v. of ps) to 0.

**Comment by ivanov007** [comment]
@pishit the source file is needed you can refer to the [wiki](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources) for source examples or this [request](https://github.com/glasklart/hd/issues/5323#issuecomment-77733799)

**Comment by MagnaMike** [comment]
One of the rules of a Glasklart icon is that you can't have gradients. The icon should be solid opaque black when you apply layer style.

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6586964/cdbc9f9c-c754-11e4-8424-75986a20ef92.png)
https://cloud.githubusercontent.com/assets/2236254/6586964/cdbc9f9c-c754-11e4-8424-75986a20ef92.png
---
Source:
https://cloud.githubusercontent.com/assets/2236254/6586963/c9f5c3b6-c754-11e4-8af3-fb4ae4ac8af5.png

**Comment by dreamnet** [comment]
Or maybe inverted?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6623108/3604d532-c8e1-11e4-86ac-b0c04ba44eae.png)
https://cloud.githubusercontent.com/assets/2068130/6623108/3604d532-c8e1-11e4-86ac-b0c04ba44eae.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6623116/44080a64-c8e1-11e4-978e-d32cb50e0c13.png

**Comment by MagnaMike** [comment]
@dreamnet Sure :+1:
