### ISSUE TITLE
TS3 Viewer

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5328]
**App Name:** TS3 Viewer
**Bundle ID:** A67SY596FC.ts3viewer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=898581839">898581839</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ts3-viewer/id898581839?mt=8&uo=4">https://itunes.apple.com/us/app/ts3-viewer/id898581839?mt=8&uo=4</a>
**App Version:** 0.0.5
**Seller:** Filippo Tortomasi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/filippo-tortomasi/id889609708?uo=4>© Filippo Tortomasi</a>
**Supported Devices:** iPadMini, iPadFourthGen, iPodTouchFourthGen, iPadMini4G, iPhone6, iPhone5c, iPad23G, iPad2Wifi, iPadFourthGen4G, iPhone5, iPadThirdGen, iPhone4S, iPhone5s, iPhone6Plus, iPodTouchFifthGen, iPadThirdGen4G, iPhone4, iPhone-3GS
**Original Artwork:**
<img src="http://a1721.phobos.apple.com/us/r30/Purple3/v4/ea/73/a4/ea73a4f4-a753-d9cd-42ab-8f717e68af5a/mzl.xggclihp.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6629641/88447864-c910-11e4-8692-55b147489eb7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6629641/88447864-c910-11e4-8692-55b147489eb7.png)
https://cloud.githubusercontent.com/assets/2068130/6629641/88447864-c910-11e4-8692-55b147489eb7.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6629646/9a7fe9dc-c910-11e4-965c-5a705e8330c7.png

**Comment by ivanov007** [comment]
one of those that looks way better on glasklart :smile:
