### ISSUE TITLE
SmartOffice 2 - Viewer and editor for Microsoft Office Word, Excel and PowerPoint files + annotate PDF on mobile devices

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#533]
**App Name:** SmartOffice 2 - Viewer and editor for Microsoft Office Word, Excel and PowerPoint files + annotate PDF on mobile devices
**Bundle ID:** com.picsel.smartoffice2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504520620">504520620</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartoffice-2-viewer-editor/id504520620?mt=8&uo=4">https://itunes.apple.com/us/app/smartoffice-2-viewer-editor/id504520620?mt=8&uo=4</a>
**App Version:** 2.4.26
**Seller:** Artifex Software Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/artifex/id836935893?uo=4>© Artifex</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/f1/b3/9f/f1b39fbf-d0a3-8e74-9195-30f566e40613/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18451670/2baa732c-7938-11e6-97c7-3ca324b1441b.png)

**Comment by 2Qt2beStr8** [comment]
needs update


**App Name:** SmartOffice 2 - Viewer and editor for Microsoft Office Word, Excel and PowerPoint files + annotate PDF on mobile devices
**Bundle ID:** com.picsel.smartoffice2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504520620">504520620</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartoffice-2-viewer-editor/id504520620?mt=8&uo=4">https://itunes.apple.com/us/app/smartoffice-2-viewer-editor/id504520620?mt=8&uo=4</a>
**App Version:** 2.4.26
**Seller:** Artifex Software Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/artifex/id836935893?uo=4>© Artifex</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/f1/b3/9f/f1b39fbf-d0a3-8e74-9195-30f566e40613/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18451670/2baa732c-7938-11e6-97c7-3ca324b1441b.png)
https://cloud.githubusercontent.com/assets/20930745/18451670/2baa732c-7938-11e6-97c7-3ca324b1441b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18451694/42004bba-7938-11e6-8509-9f89a11b233a.png
