### ISSUE TITLE
MTN

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5331]
**App Name:** MTN
**Bundle ID:** com.trash.mountain
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=891528055">891528055</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mtn/id891528055?mt=8&uo=4">https://itunes.apple.com/us/app/mtn/id891528055?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** David O'Reilly
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/david-oreilly/id891528058?uo=4>© David O'Reilly</a>
**Supported Devices:** iPhone-3GS, iPhone5c, iPadMini4G, iPhone4, iPhone6Plus, iPad2Wifi, iPhone5, iPhone4S, iPadMini, iPadThirdGen, iPhone6, iPadFourthGen, iPad23G, iPadThirdGen4G, iPodTouchFourthGen, iPhone5s, iPodTouchFifthGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://a584.phobos.apple.com/us/r30/Purple3/v4/07/7d/8c/077d8c79-68d4-1ab2-d770-5cca550f5222/mzl.cadqojcw.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6622756/ed59d3de-c8de-11e4-8c66-03c8a5881ebe.png)

**Comment by MagnaMike** [comment]
@icecharger Please use the original `App Name:` as the title of the issue. Thanks!

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6622756/ed59d3de-c8de-11e4-8c66-03c8a5881ebe.png)
https://cloud.githubusercontent.com/assets/2068130/6622756/ed59d3de-c8de-11e4-8c66-03c8a5881ebe.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6622777/10eb96b6-c8df-11e4-8e3a-322839fb54a1.png
