### ISSUE TITLE
Knights of Pen & Paper

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5332]
**App Name:** Knights of Pen & Paper
**Bundle ID:** br.com.beholdstudios.knightspp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=549248038">549248038</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/knights-of-pen-paper/id549248038?mt=8&uo=4">https://itunes.apple.com/us/app/knights-of-pen-paper/id549248038?mt=8&uo=4</a>
**App Version:** 2.20
**Seller:** Paradox North AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/paradox-north/id858598107?uo=4>© Paradox North</a>
**Supported Devices:** iPad23G, iPadWifi, iPodTouchFourthGen, iPhone6Plus, iPhone4S, iPhone6, iPhone-3GS, iPadMini, iPhone5s, iPodTouchThirdGen, iPadThirdGen4G, iPhone5, iPadFourthGen, iPhone4, iPhone5c, iPodTouchFifthGen, iPadFourthGen4G, iPad3G, iPadMini4G, iPad2Wifi, iPadThirdGen
**Original Artwork:**
<img src="http://a1598.phobos.apple.com/us/r30/Purple3/v4/4e/df/f8/4edff88b-546d-365a-7bed-8793c4dbe93b/mzl.pdqoullo.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7221537/f47fbac4-e6ee-11e4-88fc-1deab2d12d50.png)

**Comment by MagnaMike** [comment]
@icecharger Same as #5331. Thanks!

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/7173384/acfa3cf2-e431-11e4-8799-0c4ba84059e3.png)
https://cloud.githubusercontent.com/assets/10008202/7173384/acfa3cf2-e431-11e4-8799-0c4ba84059e3.png
**Source**
https://cloud.githubusercontent.com/assets/10008202/7173389/b7cfa608-e431-11e4-9bf0-fd3a2c65a033.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7221537/f47fbac4-e6ee-11e4-88fc-1deab2d12d50.png)
https://cloud.githubusercontent.com/assets/2068130/7221537/f47fbac4-e6ee-11e4-88fc-1deab2d12d50.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7221546/027d2e90-e6ef-11e4-9ce5-f766f53c3274.png

**Comment by MagnaMike** [comment]
@dreamnet Good :+1:
