### ISSUE TITLE
Inventory Control with Barcode Scanner

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#5333]
**App Name:** Inventory Control with Barcode Scanner
**Bundle ID:** Starkode.Inventory
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=897331188">897331188</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inventory-control-barcode/id897331188?mt=8&uo=4">https://itunes.apple.com/us/app/inventory-control-barcode/id897331188?mt=8&uo=4</a>
**App Version:** 4.6
**Seller:** Alejandro Doto
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/alejandro-doto/id874698946?uo=4>© Alejandro Doto</a>
**Supported Devices:** iPadMini, iPhone4S, iPadMini4G, iPad23G, iPhone4, iPadThirdGen4G, iPadThirdGen, iPad2Wifi, iPhone5c, iPhone5, iPodTouchFifthGen, iPhone6Plus, iPadFourthGen4G, iPadFourthGen, iPhone5s, iPhone6
**Original Artwork:**
<img src="http://a999.phobos.apple.com/us/r30/Purple3/v4/57/78/be/5778be55-b5e6-b44c-2374-eb111e358538/mzl.knwgfjze.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6628675/d09efd22-c907-11e4-98d4-d3683d03ea9d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6628675/d09efd22-c907-11e4-98d4-d3683d03ea9d.png)
https://cloud.githubusercontent.com/assets/2068130/6628675/d09efd22-c907-11e4-98d4-d3683d03ea9d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6628689/e4823be2-c907-11e4-8189-36dda0a37abe.png

**Comment by RemiDeluxe** [comment]
perfect, thank you! :)
