### ISSUE TITLE
HERE - Offline navigation, maps, traffic, public transit

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5334]
**App Name:** HERE - Offline navigation, maps, traffic, public transit
**Bundle ID:** com.here.app.HERESuite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955837609">955837609</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/here-offline-navigation-maps/id955837609?mt=8&uo=4">https://itunes.apple.com/us/app/here-offline-navigation-maps/id955837609?mt=8&uo=4</a>
**App Version:** 1.0.59
**Seller:** Nokia Apps LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nokia-apps-llc/id955837608?uo=4>© Nokia Apps LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen4G, iPodTouchFifthGen, iPadFourthGen, iPhone5c, iPadFourthGen4G, iPhone5, iPhone6Plus, iPadMini4G, iPhone4S, iPhone6, iPhone4, iPadThirdGen, iPadMini, iPhone5s
**Original Artwork:**
<img src="http://a1537.phobos.apple.com/us/r30/Purple3/v4/97/6d/27/976d2715-82ef-a06b-ddb5-b83a7eebee81/pr_source.png?downloadKey=1426369883_1f553883b6e10555110b23aa58f04385" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655068/e7642514-caec-11e4-9349-8fbbb5251ad1.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655068/e7642514-caec-11e4-9349-8fbbb5251ad1.png)
https://cloud.githubusercontent.com/assets/10730122/6655068/e7642514-caec-11e4-9349-8fbbb5251ad1.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6655066/db1a08b4-caec-11e4-9c54-6f32cfc3c651.png
