### ISSUE TITLE
94%

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5335]
**App Name:** 94%
**Bundle ID:** com.scimob.94percent
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=862303071">862303071</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/94/id862303071?mt=8&uo=4">https://itunes.apple.com/us/app/94/id862303071?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** SCIMOB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/scimob/id325822885?uo=4>© Scimob</a>
**Supported Devices:** iPadMini4G, iPadFourthGen4G, iPhone5s, iPadThirdGen, iPadFourthGen, iPhone4, iPhone5, iPhone6, iPodTouchFifthGen, iPad2Wifi, iPadMini, iPhone4S, iPadThirdGen4G, iPad23G, iPhone5c, iPhone6Plus
**Original Artwork:**
<img src="http://a483.phobos.apple.com/us/r30/Purple3/v4/47/44/35/4744353f-9ad3-211a-6c0d-865f1b491fde/mzl.spfqhzbm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655037/5a5e7314-caeb-11e4-830b-565f463c218f.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655037/5a5e7314-caeb-11e4-830b-565f463c218f.png)
https://cloud.githubusercontent.com/assets/10730122/6655037/5a5e7314-caeb-11e4-830b-565f463c218f.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6655042/96d92726-caeb-11e4-826b-6af333ab5661.png

**Comment by dreamnet** [comment]
Hm, I think the circle of the icon needs to be centered:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6673459/9c846950-cc13-11e4-9451-9ec7a4f9ed8b.png)
https://cloud.githubusercontent.com/assets/2068130/6673459/9c846950-cc13-11e4-9451-9ec7a4f9ed8b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6673421/31c57168-cc13-11e4-9c19-8aa6a36e8ae2.png
Anyway, credits are going to @Trubbel .
