### ISSUE TITLE
Blockwick 2

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5336]
**App Name:** Blockwick 2
**Bundle ID:** com.kiefferbros.blockwick2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=945199694">945199694</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blockwick-2/id945199694?mt=8&uo=4">https://itunes.apple.com/us/app/blockwick-2/id945199694?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Kieffer Bros., LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kieffer-bros./id293702721?uo=4>© Kieffer Bros.</a>
**Supported Devices:** iPadThirdGen, iPhone4S, iPadMini, iPhone6Plus, iPhone5s, iPadFourthGen4G, iPadMini4G, iPhone6, iPhone5c, iPadFourthGen, iPadThirdGen4G, iPodTouchFourthGen, iPodTouchFifthGen, iPhone4, iPhone-3GS, iPad2Wifi, iPhone5, iPad23G
**Original Artwork:**
<img src="http://a152.phobos.apple.com/us/r30/Purple5/v4/33/bd/b5/33bdb51d-6e0d-e756-9f34-ede570756434/pr_source.png?downloadKey=1426370228_dabc541d0ca94e43c5e539cff62c2d82" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6659697/76424206-cb61-11e4-9cfb-a7946e438e83.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6659697/76424206-cb61-11e4-9cfb-a7946e438e83.png)
https://cloud.githubusercontent.com/assets/10950389/6659697/76424206-cb61-11e4-9cfb-a7946e438e83.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6659701/83b32554-cb61-11e4-941e-e26159afa493.png
