### ISSUE TITLE
ZigZag

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5337]
**App Name:** ZigZag
**Bundle ID:** com.ketchapp.zigzaggame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=951364656">951364656</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zigzag/id951364656?mt=8&uo=4">https://itunes.apple.com/us/app/zigzag/id951364656?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Ketchapp
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ketchapp/id528065807?uo=4>© Ketchapp</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen4G, iPadWifi, iPhone6, iPhone6Plus, iPadMini, iPhone5c, iPhone4S, iPad3G, iPadMini4G, iPhone5s, iPhone-3GS, iPodTouchThirdGen, iPodTouchFifthGen, iPadFourthGen, iPodTouchFourthGen, iPhone4, iPadFourthGen4G, iPad23G, iPadThirdGen, iPhone5
**Original Artwork:**
<img src="http://a1050.phobos.apple.com/us/r30/Purple1/v4/b0/15/bf/b015bf89-0d6b-c5ac-a2fd-f0b3a88f9fee/mzl.wzfocdgf.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6675253/7e2c5f56-cc1f-11e4-87d3-b8641ed94a58.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6675253/7e2c5f56-cc1f-11e4-87d3-b8641ed94a58.png)
https://cloud.githubusercontent.com/assets/2068130/6675253/7e2c5f56-cc1f-11e4-87d3-b8641ed94a58.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6675268/9298c678-cc1f-11e4-94a5-6c86659ce391.png
