### ISSUE TITLE
Shortcut for WhatsApp and more - Whadget

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5338]
**App Name:** Shortcut for WhatsApp and more - Whadget
**Bundle ID:** Catec.FastCall
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955092895">955092895</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shortcut-for-whatsapp-more/id955092895?mt=8&uo=4">https://itunes.apple.com/us/app/shortcut-for-whatsapp-more/id955092895?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Matheus Cavalca
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/matheus-cavalca/id853017595?uo=4>© Matheus Cavalca</a>
**Supported Devices:** iPad2Wifi, iPadFourthGen4G, iPhone4S, iPhone5c, iPhone5, iPhone6Plus, iPhone5s, iPadMini, iPadMini4G, iPadThirdGen4G, iPad23G, iPadThirdGen, iPhone6, iPodTouchFifthGen, iPadFourthGen
**Original Artwork:**
<img src="http://a246.phobos.apple.com/us/r30/Purple1/v4/4a/e2/1f/4ae21f11-c4ec-97b7-5eaa-b459bf64d7bf/mzl.affcjpew.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655060/848037e4-caec-11e4-8876-bba2c76a0ab4.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655060/848037e4-caec-11e4-8876-bba2c76a0ab4.png)
https://cloud.githubusercontent.com/assets/10730122/6655060/848037e4-caec-11e4-8876-bba2c76a0ab4.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6655059/74a4bdd6-caec-11e4-9d02-50a0d6e5359a.png

**Comment by MagnaMike** [comment]
@Trubbel Yep :+1:
