### ISSUE TITLE
DataRocket - Track Cellular Data Usage Widget

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5339]
**App Name:** DataRocket - Track Cellular Data Usage Widget
**Bundle ID:** com.sz.DataRocket
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=928900090">928900090</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/datarocket-track-cellular/id928900090?mt=8&uo=4">https://itunes.apple.com/us/app/datarocket-track-cellular/id928900090?mt=8&uo=4</a>
**App Version:** 1.22
**Seller:** Fabian Tinsz
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fabian-tinsz/id734367000?uo=4>© Fabian Tinsz</a>
**Supported Devices:** iPhone5s, iPadMini4G, iPadFourthGen4G, iPadThirdGen, iPadFourthGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPhone4S, iPhone5c, iPad23G, iPhone6, iPhone6Plus, iPad2Wifi, iPadMini
**Original Artwork:**
<img src="http://a506.phobos.apple.com/us/r30/Purple3/v4/85/f7/bd/85f7bd3b-ce0e-d0d1-2662-560762bf9527/mzl.zagudpbd.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655081/64e14904-caed-11e4-86e2-df9b51c32bf4.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655081/64e14904-caed-11e4-86e2-df9b51c32bf4.png)
https://cloud.githubusercontent.com/assets/10730122/6655081/64e14904-caed-11e4-86e2-df9b51c32bf4.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6655079/5847c614-caed-11e4-991b-3bbf8542ccd6.png
