### ISSUE TITLE
CoPilot GPS Navigation

### ISSUE THREAD

**Issue by pishit** [glasklart/hd#5341]
**App Name:** CoPilot GPS Navigation
**Bundle ID:** com.alk.copilot9namapviewer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504677517">504677517</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/copilot-gps-navigation/id504677517?uo=4">https://apps.apple.com/us/app/copilot-gps-navigation/id504677517?uo=4</a>
**App Version:** 10.11.1.35
**Seller:** ALK Technologies Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/alk-technologies-ltd/id324327454?uo=4">© ALK Technologies Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/5a/e2/e3/5ae2e34f-fb30-8c7c-e3f5-4be3936912b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60369707-dbc98d80-99f4-11e9-8eec-9fdb91379314.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655101/7a768bde-caee-11e4-808a-f1f27bfaf30a.png)
https://cloud.githubusercontent.com/assets/10730122/6655101/7a768bde-caee-11e4-808a-f1f27bfaf30a.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6655099/6f033504-caee-11e4-91f9-9539d26b9bee.png



![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655111/9a2616a2-caee-11e4-8f5d-5384ee60bf96.png)
https://cloud.githubusercontent.com/assets/10730122/6655111/9a2616a2-caee-11e4-8f5d-5384ee60bf96.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6655105/8e1f5a1c-caee-11e4-9948-9cb6899fdc2e.png

**Comment by MagnaMike** [comment]
@Trubbel Taking the alternate. :+1:

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60369707-dbc98d80-99f4-11e9-8eec-9fdb91379314.png)
https://user-images.githubusercontent.com/2068130/60369707-dbc98d80-99f4-11e9-8eec-9fdb91379314.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60369737-eb48d680-99f4-11e9-9033-198da50225e8.png
