### ISSUE TITLE
iCaughtU Pro

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5342]
**App Name:** iCaughtU Pro
 **Bundle ID:**  com.itaysoft.icaughtuproapp
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://i.imgur.com/eYe0rWb.png" width="150" height="150" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6656721/ef73264e-cb08-11e4-98db-39a79705f953.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6655239/eef3c2e4-caf6-11e4-95a8-5d1709a7228b.png)
https://cloud.githubusercontent.com/assets/10730122/6655239/eef3c2e4-caf6-11e4-95a8-5d1709a7228b.png

Source:
*none, the image quality is too bad - this is the only good I found in the apps own folder.*

Have been looking for a better resolution and tried make one better myself with no luck, if anyone else can do it - it would be really appreciated!

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6656721/ef73264e-cb08-11e4-98db-39a79705f953.png)
https://cloud.githubusercontent.com/assets/2236254/6656721/ef73264e-cb08-11e4-98db-39a79705f953.png

---
Source: (This is where illustrator saves the day)
https://cloud.githubusercontent.com/assets/2236254/6656720/ebbe4966-cb08-11e4-9d7e-30999bc74e9e.png

**Comment by Trubbel** [comment]
Yeah, I think that one looks better!
