### ISSUE TITLE
Grey Cubes

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5345]
**App Name:** Grey Cubes
**Bundle ID:** com.bulkypix.cube
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911407572">911407572</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grey-cubes/id911407572?mt=8&uo=4">https://itunes.apple.com/us/app/grey-cubes/id911407572?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** BULKYPIX
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bulkypix/id304521749?uo=4>© Bulkypix</a>
**Supported Devices:** iPhone5c, iPadThirdGen, iPadThirdGen4G, iPhone5s, iPhone4S, iPadFourthGen4G, iPhone6Plus, iPadMini, iPadMini4G, iPhone6, iPhone4, iPad23G, iPhone5, iPadFourthGen, iPad2Wifi
**Original Artwork:**
<img src="http://a1146.phobos.apple.com/us/r30/Purple3/v4/4a/40/fc/4a40fc8e-99ed-4d78-731b-ceed149eb4da/mzl.erxhkcqt.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6998516/4c05447c-dbe5-11e4-94fa-cd581dab4c0d.png)

**Comment by dreamnet** [comment]
Looks like that's the game logo:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6998516/4c05447c-dbe5-11e4-94fa-cd581dab4c0d.png)
https://cloud.githubusercontent.com/assets/2068130/6998516/4c05447c-dbe5-11e4-94fa-cd581dab4c0d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6998519/58dc5320-dbe5-11e4-9d23-f2f1bf859598.png

**Comment by dreamnet** [comment]
@zmathiasz Can we use this?

**Comment by zmathiasz** [comment]
Yeah that works for me. I couldn't get anything to look good with the original icon. :)
