### ISSUE TITLE
Pool:

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5348]
**App Name:** Pool:
**Bundle ID:** com.botond-fm.iphone.micropool.full
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391467933">391467933</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pool/id391467933?mt=8&uo=4">https://itunes.apple.com/us/app/pool/id391467933?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Botond FM Bt.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/botond-fm-bt./id391467936?uo=4>© Botond FM Bt.</a>
**Supported Devices:** iPhone-3GS, iPhone4S, iPhone6Plus, iPodTouchFourthGen, iPhone6, iPhone4, iPhone5s, iPad2Wifi, iPadMini4G, iPodTouchFifthGen, iPadThirdGen4G, iPadThirdGen, iPadFourthGen, iPhone5, iPhone5c, iPadFourthGen4G, iPad23G, iPadMini
**Original Artwork:**
<img src="http://a32.phobos.apple.com/us/r30/Purple/v4/cb/a3/38/cba338f5-f200-abbd-9066-02e7c108c40f/mzl.lcfgkrva.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6767246/1c235728-d026-11e4-81ff-4ef28e58a706.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6684274/ec6ab934-cc8f-11e4-81ef-8f27605cc81f.png)
https://cloud.githubusercontent.com/assets/10730122/6684274/ec6ab934-cc8f-11e4-81ef-8f27605cc81f.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6684266/df63610a-cc8f-11e4-9dde-424748099f84.png

**Comment by MagnaMike** [comment]
Alternate, Inverted Ball:
[](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6689149/cb35e1d6-cc8e-11e4-89da-317134dd641a.png)
https://cloud.githubusercontent.com/assets/2236254/6689149/cb35e1d6-cc8e-11e4-89da-317134dd641a.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6689148/c857a30a-cc8e-11e4-8aaa-10439dbe199e.png)

**Comment by MagnaMike** [comment]
Alternate Alternate
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6689245/58a21ada-cc8f-11e4-8495-903dd2a4560b.png)
https://cloud.githubusercontent.com/assets/2236254/6689245/58a21ada-cc8f-11e4-8495-903dd2a4560b.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6689253/6531dbf0-cc8f-11e4-8d1f-66a2382a4cb9.png

**Comment by Trubbel** [comment]
Hmm, I think I would prefer the first alternate. What about you?

**Comment by MagnaMike** [comment]
I like the second because I don't usually like text in icons. @dreamnet?

**Comment by Trubbel** [comment]
That is a fair point actually. I don't mind either to be fully honest, so I will leave this up to you guys!

**Comment by dreamnet** [comment]
Well, a tough call. I'm with the one from @MagnaMike, because I also don't like text in icons. But the first alternative from @Trubbel is more like the original. If we finally take the last one from @MagnaMike, I think it should be fully sized up to the guidelines.

**Comment by dreamnet** [comment]
I mean if we don't do the text, we could do it like this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6767246/1c235728-d026-11e4-81ff-4ef28e58a706.png)
https://cloud.githubusercontent.com/assets/2068130/6767246/1c235728-d026-11e4-81ff-4ef28e58a706.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6767249/2a41bad4-d026-11e4-851d-4df89b9db4de.png

**Comment by Trubbel** [comment]
@dreamnet Yeah, I think we should go with that one.
