### ISSUE TITLE
Distant Suns(max): Because half the day is night.

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5351]
**App Name:** Distant Suns(max): Because half the day is night.
**Bundle ID:** com.distantsuns.distantsunsipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=363418936">363418936</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/distant-suns-max-because-half/id363418936?mt=8&uo=4">https://itunes.apple.com/us/app/distant-suns-max-because-half/id363418936?mt=8&uo=4</a>
**App Version:** 3.4.13
**Seller:** Mike Smithwick
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/first-light/id294198918?uo=4>© First Light</a>
**Supported Devices:** iPadFourthGen, iPhone6Plus, iPad2Wifi, iPhone4S, iPadThirdGen4G, iPhone5c, iPadMini, iPadMini4G, iPhone5s, iPhone6, iPhone4, iPodTouchFifthGen, iPad23G, iPhone5, iPadFourthGen4G, iPadThirdGen
**Original Artwork:**
<img src="http://a314.phobos.apple.com/us/r30/Purple1/v4/3f/1f/09/3f1f09bd-1a03-1c34-6052-2030b11156fd/mzl.uuruvles.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6685078/198fafbc-cc97-11e4-94c7-13f94a19de5e.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6685078/198fafbc-cc97-11e4-94c7-13f94a19de5e.png)
https://cloud.githubusercontent.com/assets/10730122/6685078/198fafbc-cc97-11e4-94c7-13f94a19de5e.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6685095/277e0c04-cc97-11e4-87d4-7315cabb5b6c.png

*This was the best I could do*

**Comment by MagnaMike** [comment]
@Trubbel It looks great! :+1:
