### ISSUE TITLE
Icon problems since 4.15.0

### ISSUE THREAD

**Issue by Aktersnurran** [glasklart/hd#5352]
Hi there,

I just updated glasklart through Cydia to 4.15.0 and when I did that, I lost themed icons of Whatsapp, f.lux, Handelsbanken, Swish, Skatteverket, tv.nu and Instasize. Something I can do in iFile or so?

I'd also like to have FL Studio HD and RepCount themed if it's possible. 

Thanks!

**Comment by WaterTrooper** [comment]
I can confirm whatsapp and F.lux. Also the clock seems messed up too. 

I submitted teamspeak viewer and it doesn't seem to show either.

**Comment by andreolidavide** [comment]
Same here, it looks like a lot of icons are missing.

**Comment by dreamnet** [comment]
4.15.0 seems to be broken on modmyi - I will push out 4.15.1 as fast as I can.

**Comment by Aktersnurran** [comment]
Thank you!

**Comment by dreamnet** [comment]
Already pushed it out - now it depends on how long the guys on modmyi are taking to release it.
If somthing is going wrong with release 4.15.1 please comment on #5355
