### ISSUE TITLE
FL Studio Mobile HD

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5354]
**App Name:** FL Studio Mobile HD
**Bundle ID:** com.imageline.FLStudioMobileHD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432850619">432850619</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fl-studio-mobile-hd/id432850619?mt=8&uo=4">https://itunes.apple.com/us/app/fl-studio-mobile-hd/id432850619?mt=8&uo=4</a>
**App Version:** 2.4.2
**Seller:** image-line
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/image-line-software/id432850147?uo=4>© Image Line Software</a>
**Supported Devices:** iPhone4, iPadThirdGen4G, iPadMini4G, iPad2Wifi, iPad23G, iPhone6, iPadFourthGen, iPodTouchFifthGen, iPhone5s, iPadMini, iPhone5c, iPhone4S, iPhone6Plus, iPadFourthGen4G, iPhone5, iPadThirdGen
**Original Artwork:**
<img src="http://a1009.phobos.apple.com/us/r30/Purple3/v4/d4/c2/d5/d4c2d5a7-2ef0-5e32-316a-fb47acbcf507/mzl.iuqypmjl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6725280/6912f622-ce07-11e4-94e2-2ccd7541bc45.png)

**Comment by Trubbel** [comment]
I noticed that the other version of this application (non HD) has the same icon, perhaps we could use that one for this application as well?

![](http://preview.dreamnet.at/?image=https://raw.githubusercontent.com/glasklart/hd/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.imageline.FLStudioMobile@2x.png)
https://raw.githubusercontent.com/glasklart/hd/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.imageline.FLStudioMobile@2x.png

**Comment by MagnaMike** [comment]
@Trubbel No, this icon should be updated because it uses grays (See the leaves), instead of just the layer style.

**Comment by Trubbel** [comment]
@MagnaMike How about this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6720014/6ad3272c-cdbf-11e4-872e-05afdbdcace5.png)
https://cloud.githubusercontent.com/assets/10730122/6720014/6ad3272c-cdbf-11e4-872e-05afdbdcace5.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6720007/62215cde-cdbf-11e4-8967-59a784dc0d14.png

**Comment by dreamnet** [comment]
@Trubbel Yes, I just made it a bit cleaner:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6725280/6912f622-ce07-11e4-94e2-2ccd7541bc45.png)
https://cloud.githubusercontent.com/assets/2068130/6725280/6912f622-ce07-11e4-94e2-2ccd7541bc45.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6725283/76497a8c-ce07-11e4-9641-645805c64252.png
Credit are going to you!
