### ISSUE TITLE
Sleep Cycle heart rate

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5356]
**App Name:** Sleep Cycle heart rate
**Bundle ID:** com.lexwarelabs.heartrate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=813503318">813503318</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sleep-cycle-heart-rate/id813503318?mt=8&uo=4">https://itunes.apple.com/us/app/sleep-cycle-heart-rate/id813503318?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Northcube AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/northcube-ab/id320606220?uo=4>© Northcube AB</a>
**Supported Devices:** iPhone5c, iPodTouchFifthGen, iPhone5s, iPhone5, iPhone6Plus, iPhone4, iPhone6, iPhone4S
**Original Artwork:**
<img src="http://a1758.phobos.apple.com/us/r30/Purple3/v4/8c/51/3a/8c513a7d-6c43-f623-6e66-60b25a7a9cf0/mzl.swlhtpuc.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6715077/6e735d8e-cd9c-11e4-90f6-e57a59b7b70b.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6715077/6e735d8e-cd9c-11e4-90f6-e57a59b7b70b.png)
https://cloud.githubusercontent.com/assets/10730122/6715077/6e735d8e-cd9c-11e4-90f6-e57a59b7b70b.png

Alternate,
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6715107/9b46b892-cd9c-11e4-8d3c-98a17908015f.png)
https://cloud.githubusercontent.com/assets/10730122/6715107/9b46b892-cd9c-11e4-8d3c-98a17908015f.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6715069/62f3c44e-cd9c-11e4-95ea-8aaa6791b8c1.png

**Comment by MagnaMike** [comment]
@Trubbel Just taking the first. :+1:
