### ISSUE TITLE
Sleep Cycle heart rate

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5357]
**App Name:** Sleep Cycle heart rate
**Bundle ID:** com.lexwarelabs.heartrate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=813503318">813503318</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sleep-cycle-heart-rate/id813503318?mt=8&uo=4">https://itunes.apple.com/us/app/sleep-cycle-heart-rate/id813503318?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Northcube AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/northcube-ab/id320606220?uo=4>© Northcube AB</a>
**Supported Devices:** iPhone5c, iPodTouchFifthGen, iPhone5s, iPhone5, iPhone6Plus, iPhone4, iPhone6, iPhone4S
**Original Artwork:**
<img src="http://a1758.phobos.apple.com/us/r30/Purple3/v4/8c/51/3a/8c513a7d-6c43-f623-6e66-60b25a7a9cf0/mzl.swlhtpuc.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by OstGlass** [comment]
My phone seemed to post this one twice. Sorry.

**Comment by ivanov007** [comment]
how do you post it from the phone?
