### ISSUE TITLE
Burrito Bison

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#536]
**App Name:** Burrito Bison
**Bundle ID:** com.ravenousgames.burritobison
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519781433">519781433</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/burrito-bison/id519781433?mt=8&uo=4">https://itunes.apple.com/us/app/burrito-bison/id519781433?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Ravenous Games Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ravenous-games-inc/id344310480?uo=4">© Ravenous Games Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/35/b3/8f/35b38fda-868c-af2e-cafd-104e1caeb0ec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26272485/9f2b576c-3d19-11e7-90e7-fd060540d6ed.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26272485/9f2b576c-3d19-11e7-90e7-fd060540d6ed.png)
https://cloud.githubusercontent.com/assets/2068130/26272485/9f2b576c-3d19-11e7-90e7-fd060540d6ed.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26272486/af20f0fa-3d19-11e7-97af-6d4970461a9c.png
