### ISSUE TITLE
Video Rotate

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#5361]
**App Name:** Video Rotate
**Bundle ID:** com.gadgetjuice.videorotate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=530064563">530064563</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/video-rotate/id530064563?mt=8&uo=4">https://itunes.apple.com/us/app/video-rotate/id530064563?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Gadget Juice
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/gadgetjuice/id530064566?uo=4>© GadgetJuice</a>
**Supported Devices:** iPadThirdGen, iPhone5s, iPadFourthGen4G, iPhone4, iPodTouchFourthGen, iPhone-3GS, iPad23G, iPadMini4G, iPhone5c, iPad2Wifi, iPadFourthGen, iPodTouchFifthGen, iPadThirdGen4G, iPhone4S, iPadMini, iPhone5, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://a827.phobos.apple.com/us/r30/Purple6/v4/47/d4/ea/47d4eab0-c464-61a9-65e2-23dee2a7e6a7/mzl.odzkcfwe.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6715043/328f68b2-cd9c-11e4-9b7f-a3f7ec0bb781.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6715043/328f68b2-cd9c-11e4-9b7f-a3f7ec0bb781.png)
https://cloud.githubusercontent.com/assets/10730122/6715043/328f68b2-cd9c-11e4-9b7f-a3f7ec0bb781.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6714995/f2f87554-cd9b-11e4-8788-a9dfc4143cdc.png
