### ISSUE TITLE
New York Times Crossword

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#5362]
**App Name:** The New York Times Crossword
**Bundle ID:** com.magmic.NYTCrosswords09
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307569751">307569751</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-new-york-times-crossword/id307569751?mt=8&uo=4">https://itunes.apple.com/us/app/the-new-york-times-crossword/id307569751?mt=8&uo=4</a>
**App Version:** 2.4.5
**Seller:** The New York Times Company (iDP)
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/the-new-york-times-company/id284862086?uo=4>© The New York Times Company</a>
**Supported Devices:** iPadFourthGen, iPhone5, iPhone6Plus, iPhone5c, iPhone4S, iPad2Wifi, iPadFourthGen4G, iPhone4, iPadThirdGen, iPadMini4G, iPad23G, iPodTouchFifthGen, iPadMini, iPhone5s, iPhone6, iPadThirdGen4G
**Original Artwork:**
<img src="http://a79.phobos.apple.com/us/r30/Purple6/v4/3f/24/e4/3f24e401-c134-76f1-2779-36eef2e8e71a/mzl.dqheuulx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6744025/feda29a2-ce78-11e4-8ef5-1e9e0091e56c.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6744025/feda29a2-ce78-11e4-8ef5-1e9e0091e56c.png)
https://cloud.githubusercontent.com/assets/10950389/6744025/feda29a2-ce78-11e4-8ef5-1e9e0091e56c.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6744031/161029dc-ce79-11e4-83c4-e9a8cb79d361.png
