### ISSUE TITLE
EpicMix

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#5363]
**App Name:** EpicMix
**Bundle ID:** com.vail.EpicMix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395375487">395375487</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/epicmix/id395375487?mt=8&uo=4">https://itunes.apple.com/us/app/epicmix/id395375487?mt=8&uo=4</a>
**App Version:** 5.3
**Seller:** The Vail Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/vail-resorts/id395375490?uo=4>© Vail Resorts</a>
**Supported Devices:** iPhone6Plus, iPhone5c, iPhone4S, iPadFourthGen, iPadFourthGen4G, iPadThirdGen, iPodTouchFifthGen, iPhone6, iPadMini, iPad2Wifi, iPadThirdGen4G, iPhone5s, iPhone4, iPhone5, iPadMini4G, iPad23G
**Original Artwork:**
<img src="http://a925.phobos.apple.com/us/r30/Purple5/v4/a9/79/07/a97907cf-070c-dd43-bcbc-a37310e72ace/mzl.hnujfsxr.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6740638/faca180c-ce57-11e4-8fd8-f0940724c224.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6720456/61121fa0-cdc3-11e4-83f4-5316094786d0.png)
https://cloud.githubusercontent.com/assets/10730122/6720456/61121fa0-cdc3-11e4-83f4-5316094786d0.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6720449/5403a504-cdc3-11e4-9514-4a5362fb935e.png

**Comment by MagnaMike** [comment]
@Trubbel Looks good, but I think it can be a bit better.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6740638/faca180c-ce57-11e4-8fd8-f0940724c224.png)
https://cloud.githubusercontent.com/assets/2236254/6740638/faca180c-ce57-11e4-8fd8-f0940724c224.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6740637/f6e53870-ce57-11e4-90ba-1ef988dc092b.png
