### ISSUE TITLE
Remoter VNC - Remote Desktop

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#5364]
**App Name:** Remoter VNC - Remote Desktop
**Bundle ID:** com.rafiphoneapps.remoter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=369626098">369626098</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/remoter-vnc-remote-desktop/id369626098?mt=8&uo=4">https://itunes.apple.com/us/app/remoter-vnc-remote-desktop/id369626098?mt=8&uo=4</a>
**App Version:** 4.6.26
**Seller:** Remoter Labs LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/remoter-labs-llc/id326109223?uo=4>© Remoter Labs LLC</a>
**Supported Devices:** iPhone5s, iPad23G, iPhone5, iPad2Wifi, iPhone4S, iPadThirdGen4G, iPhone6, iPodTouchFifthGen, iPadFourthGen4G, iPhone6Plus, iPadThirdGen, iPadMini, iPadFourthGen, iPadMini4G, iPhone5c, iPhone4
**Original Artwork:**
<img src="http://a1554.phobos.apple.com/us/r30/Purple3/v4/37/f2/6d/37f26d2d-96dd-954a-1f13-60e35d1a5272/pr_source.jpg?downloadKey=1426720009_8f1b160dd93e45a1547591125ed4e7b1" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6993857/0fe9bfd2-db03-11e4-87e3-fd727f613cb9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6993857/0fe9bfd2-db03-11e4-87e3-fd727f613cb9.png)
https://cloud.githubusercontent.com/assets/2068130/6993857/0fe9bfd2-db03-11e4-87e3-fd727f613cb9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6993858/1ea77730-db03-11e4-895a-37ea7ec305a4.png
