### ISSUE TITLE
 CamViewer for IP Webcams, with Audio purchase!

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#5365]
**App Name:** CamViewer for IP Webcams, with Audio purchase!
**Bundle ID:** com.johnmckerrell.CamViewer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416551665">416551665</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camviewer-for-ip-webcams-audio/id416551665?mt=8&uo=4">https://itunes.apple.com/us/app/camviewer-for-ip-webcams-audio/id416551665?mt=8&uo=4</a>
**App Version:** 1.9.25
**Seller:** John McKerrell
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/john-mckerrell/id296156552?uo=4>© John McKerrell</a>
**Supported Devices:** iPadThirdGen4G, iPad3G, iPadMini4G, iPhone5s, iPhone5, iPadWifi, iPadFourthGen, iPadFourthGen4G, iPadThirdGen, iPodTouchThirdGen, iPhone4S, iPad2Wifi, iPhone4, iPodTouchFourthGen, iPadMini, iPhone5c, iPhone-3GS, iPhone6Plus, iPad23G, iPodTouchFifthGen, iPhone6
**Original Artwork:**
<img src="http://a1946.phobos.apple.com/us/r30/Purple5/v4/83/18/db/8318db69-0c46-e435-0b02-0d42c4c7e6c1/mzl.bddaaptj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6748160/fbaf62b4-cee2-11e4-854b-a2bb9da421f4.png)

**Comment by zmathiasz** [comment]
I imagine this is supposed to represent the lens with LEDs surrounding it in cameras with low light vision.  The white border is more or less to keep perspective...On a side note...Could be an eye...or a funky prehistoric cave painting sun......or a hieroglyph???  Yah never know.  :low_brightness: :question:  
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6744456/f788ea56-ce7f-11e4-873e-e17db0a9ac3f.png)
https://cloud.githubusercontent.com/assets/10950389/6744456/f788ea56-ce7f-11e4-873e-e17db0a9ac3f.png
Source: 
https://cloud.githubusercontent.com/assets/10950389/6744463/0ce5817a-ce80-11e4-9c8d-643abd821b2e.png

**Comment by zmathiasz** [comment]
Alternate 1:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6744551/5f08dfc8-ce81-11e4-853b-cd0a31d2efd1.png)
https://cloud.githubusercontent.com/assets/10950389/6744551/5f08dfc8-ce81-11e4-853b-cd0a31d2efd1.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6744557/71127c2e-ce81-11e4-8ee6-6af3394e7583.png

**Comment by zmathiasz** [comment]
Alternate 2:
Maybe better smaller?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6744564/9926021c-ce81-11e4-9d73-8f2d3097d762.png)
https://cloud.githubusercontent.com/assets/10950389/6744564/9926021c-ce81-11e4-9d73-8f2d3097d762.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6744561/8d2d0d7a-ce81-11e4-8aa7-d51e04145ea6.png

**Comment by MagnaMike** [comment]
@zmathiasz I think I'm leaning towards Alternate 1 ?? Not sure though, it is weird.
