### ISSUE TITLE
Hidden Sky

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#5366]
**App Name:** Hidden Sky
**Bundle ID:** com.codeorgana.hiddensky
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=363410060">363410060</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hidden-sky/id363410060?mt=8&uo=4">https://itunes.apple.com/us/app/hidden-sky/id363410060?mt=8&uo=4</a>
**App Version:** 1.0.8
**Seller:** Code Organa LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/code-organa/id363410063?uo=4>© Code Organa</a>
**Supported Devices:** iPhone5, iPadWifi, iPad2Wifi, iPadMini4G, iPadThirdGen4G, iPadFourthGen4G, iPad3G, iPhone5c, iPadMini, iPadThirdGen, iPadFourthGen, iPad23G, iPhone6Plus, iPhone6, iPhone-3GS, iPhone5s, iPhone4S, iPhone4
**Original Artwork:**
<img src="http://a1156.phobos.apple.com/us/r30/Purple/v4/a4/03/05/a4030513-ce00-775f-96f4-8a312954698a/mzm.ppfdpyqj.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/6723936/d516e5f6-ce32-11e4-943b-f6e9e7ce10c0.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/6723936/d516e5f6-ce32-11e4-943b-f6e9e7ce10c0.png)
https://cloud.githubusercontent.com/assets/10008202/6723936/d516e5f6-ce32-11e4-943b-f6e9e7ce10c0.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/6723961/29a42282-ce33-11e4-9d0e-c4da61173970.png

**Comment by MagnaMike** [comment]
@iNfeCtGFX Yep! :+1:
