### ISSUE TITLE
XFINITY TV Remote

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#5367]
**App Name:** XFINITY TV Remote
**Bundle ID:** com.comcast.cim.xfinitytv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401629893">401629893</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xfinity-tv-remote/id401629893?mt=8&uo=4">https://itunes.apple.com/us/app/xfinity-tv-remote/id401629893?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Comcast Interactive Media
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/comcast/id298960160?uo=4>© Comcast</a>
**Supported Devices:** iPadThirdGen, iPhone6, iPhone6Plus, iPodTouchFifthGen, iPadThirdGen4G, iPad23G, iPadMini4G, iPhone5s, iPadFourthGen, iPhone5, iPad2Wifi, iPadMini, iPhone4, iPhone5c, iPadFourthGen4G, iPhone4S
**Original Artwork:**
<img src="http://a140.phobos.apple.com/us/r30/Purple5/v4/73/38/cc/7338ccb3-9f44-ba4d-2aea-ec4283c4dc6a/mzl.ppnxpjfm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6767209/8e8c0424-d024-11e4-84e2-426d839c09a4.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6720361/9f548cc2-cdc2-11e4-8bcf-e30890d1cfe8.png)
https://cloud.githubusercontent.com/assets/10730122/6720361/9f548cc2-cdc2-11e4-8bcf-e30890d1cfe8.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6720355/91edca58-cdc2-11e4-8973-1aae13526f1f.png

**Comment by dreamnet** [comment]
Just some small changes:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6767209/8e8c0424-d024-11e4-84e2-426d839c09a4.png)
https://cloud.githubusercontent.com/assets/2068130/6767209/8e8c0424-d024-11e4-84e2-426d839c09a4.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6767210/9ce1315c-d024-11e4-9786-07b22813e8cf.png

**Comment by Sly-Fi** [comment]
This icon is missing from 5.0 release

**Comment by dreamnet** [comment]
@Sly-Fi No, it's [already in the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.comcast.cim.xfinitytv-large.png). ???
