### ISSUE TITLE
JotNot Pro | scan multipage documents to PDF

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#5368]
**App Name:** JotNot Pro | scan multipage documents to PDF
**Bundle ID:** com.mobitech3000.JotNotIPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307868751">307868751</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jotnot-pro-scan-multipage/id307868751?mt=8&uo=4">https://itunes.apple.com/us/app/jotnot-pro-scan-multipage/id307868751?mt=8&uo=4</a>
**App Version:** 4.3.2
**Seller:** MobiTech 3000 LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mobitech-3000-llc/id307868754?uo=4>© MobiTech 3000 LLC</a>
**Supported Devices:** iPadThirdGen4G, iPad23G, iPhone4S, iPadThirdGen, iPhone5s, iPodTouchFourthGen, iPadMini4G, iPhone5c, iPadFourthGen, iPad2Wifi, iPhone-3GS, iPhone6Plus, iPhone6, iPadMini, iPhone5, iPadFourthGen4G, iPhone4, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a868.phobos.apple.com/us/r30/Purple3/v4/de/c5/57/dec557b4-bd0a-268a-1e53-b3a018f80d86/mzl.byvhdjql.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6767371/b19fbffc-d02c-11e4-84ae-bbac708b0ed6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6767371/b19fbffc-d02c-11e4-84ae-bbac708b0ed6.png)
https://cloud.githubusercontent.com/assets/2068130/6767371/b19fbffc-d02c-11e4-84ae-bbac708b0ed6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6767373/c0696948-d02c-11e4-8b5b-4894133c4e3c.png
