### ISSUE TITLE
OnStar RemoteLink

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#5369]
**App Name:** OnStar RemoteLink
**Bundle ID:** com.onstar.mylink
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393584149">393584149</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/onstar-remotelink/id393584149?mt=8&uo=4">https://itunes.apple.com/us/app/onstar-remotelink/id393584149?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** OnStar, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/onstar-llc/id376862825?uo=4>© OnStar, LLC</a>
**Supported Devices:** iPodTouchFourthGen, iPadFourthGen4G, iPadThirdGen, iPadThirdGen4G, iPhone5s, iPad23G, iPhone-3GS, iPad2Wifi, iPhone4, iPadFourthGen, iPhone4S, iPadMini4G, iPhone6, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone6Plus, iPadMini
**Original Artwork:**
<img src="http://a1427.phobos.apple.com/us/r30/Purple3/v4/5f/a6/25/5fa625cb-e570-de6a-1b5f-0921c689c636/mzl.ydqfbwgn.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6720285/e76ea20a-cdc1-11e4-8bc8-5526f8469f8b.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6720285/e76ea20a-cdc1-11e4-8bc8-5526f8469f8b.png)
https://cloud.githubusercontent.com/assets/10730122/6720285/e76ea20a-cdc1-11e4-8bc8-5526f8469f8b.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6720280/d8cf40ce-cdc1-11e4-8df5-7cccfd13c6b6.png

 
Alternate,
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6720269/c4c78aaa-cdc1-11e4-998a-08073206610a.png)
https://cloud.githubusercontent.com/assets/10730122/6720269/c4c78aaa-cdc1-11e4-998a-08073206610a.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6720266/b8914b2c-cdc1-11e4-9e09-e58daac18b41.png

**Comment by MagnaMike** [comment]
@Trubbel :one: :+1:
