### ISSUE TITLE
Distant Suns: The new way to look at the sky

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#5370]
**App Name:** Distant Suns: The new way to look at the sky
**Bundle ID:** com.distantsuns.distantsuns
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=294198915">294198915</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/distant-suns-new-way-to-look/id294198915?mt=8&uo=4">https://itunes.apple.com/us/app/distant-suns-new-way-to-look/id294198915?mt=8&uo=4</a>
**App Version:** 2.4.10
**Seller:** Mike Smithwick
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/first-light/id294198918?uo=4>© First Light</a>
**Supported Devices:** iPadThirdGen4G, iPhone5, iPhone4S, iPadFourthGen4G, iPadMini4G, iPad2Wifi, iPhone5c, iPodTouchFifthGen, iPhone6, iPadMini, iPhone5s, iPhone4, iPad23G, iPhone6Plus, iPadThirdGen, iPadFourthGen
**Original Artwork:**
<img src="http://a150.phobos.apple.com/us/r30/Purple5/v4/3b/85/bf/3b85bf58-0969-5046-0222-d96c5b91c52f/mzl.ccwypzuc.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6887719/6a5a0282-d668-11e4-8c36-7cabba18ebcf.png)

**Comment by MagnaMike** [comment]
Please use the entire `App Name:` please, thanks!

**Comment by dreamnet** [comment]
Like #5351 - just an other background.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6887719/6a5a0282-d668-11e4-8c36-7cabba18ebcf.png)
https://cloud.githubusercontent.com/assets/2068130/6887719/6a5a0282-d668-11e4-8c36-7cabba18ebcf.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6887723/78666e9c-d668-11e4-9720-4249a355c4b9.png

**Comment by Trubbel** [comment]
@dreamnet Nice!

**Comment by dreamnet** [comment]
@Trubbel THX!
