### ISSUE TITLE
Thermodo

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#5371]
**App Name:** Thermodo
**Bundle ID:** com.robocatapps.Thermodo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=739181884">739181884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/thermodo/id739181884?mt=8&uo=4">https://itunes.apple.com/us/app/thermodo/id739181884?mt=8&uo=4</a>
**App Version:** 1.6.3
**Seller:** icelantern
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/robocat/id333195279?uo=4>© Robocat</a>
**Supported Devices:** iPadFourthGen, iPadMini, iPad2Wifi, iPhone5, iPhone4S, iPadMini4G, iPhone5s, iPadThirdGen4G, iPhone4, iPodTouchFifthGen, iPadFourthGen4G, iPhone6Plus, iPhone6, iPad23G, iPadThirdGen, iPhone5c
**Original Artwork:**
<img src="http://a375.phobos.apple.com/us/r30/Purple5/v4/35/a9/9f/35a99f95-59a7-86e2-4e7f-c512124fe381/mzl.rigfpocj.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6719197/4aea2128-cdb9-11e4-933c-c6dcb6ae1d37.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6719197/4aea2128-cdb9-11e4-933c-c6dcb6ae1d37.png)
https://cloud.githubusercontent.com/assets/10730122/6719197/4aea2128-cdb9-11e4-933c-c6dcb6ae1d37.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6719184/3a56e7f6-cdb9-11e4-96a0-2a3b23f71aae.png
