### ISSUE TITLE
Yousician Guitar - The ultimate free guitar tab game with tuner, songs and tutorials

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5373]
**App Name:** Yousician Guitar - The ultimate free guitar tab game with tuner, songs and tutorials
**Bundle ID:** com.yousician.yousician
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=959883039">959883039</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yousician-guitar-ultimate/id959883039?mt=8&uo=4">https://itunes.apple.com/us/app/yousician-guitar-ultimate/id959883039?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Yousician Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/yousician-ltd/id453707541?uo=4>© Yousician Ltd</a>
**Supported Devices:** iPodTouchFifthGen, iPhone5s, iPhone-3GS, iPadThirdGen, iPadFourthGen4G, iPadMini4G, iPad23G, iPodTouchFourthGen, iPhone4S, iPhone6, iPadFourthGen, iPadThirdGen4G, iPhone5, iPhone4, iPhone6Plus, iPad2Wifi, iPadMini, iPhone5c
**Original Artwork:**
<img src="http://a1562.phobos.apple.com/us/r30/Purple3/v4/04/88/98/0488988f-e0df-38cb-87f2-967dbbeb4deb/pr_source.png?downloadKey=1426770837_3ddfdb2574e01084acee5eba5659a1e6" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6734186/e792c5dc-ce56-11e4-8661-9d8adaddbc24.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6728345/80ce19d2-ce29-11e4-86be-15f22372e4b4.png)
https://cloud.githubusercontent.com/assets/10730122/6728345/80ce19d2-ce29-11e4-86be-15f22372e4b4.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6728331/718d427c-ce29-11e4-8102-73d61f5087dd.png

**Comment by dreamnet** [comment]
@Trubbel Nice! :+1:
