### ISSUE TITLE
Soctics League: Online Multiplayer Pocket Football

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5374]
**App Name:** Soctics League: Online Multiplayer Pocket Football
**Bundle ID:** com.bitongo.soctics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507874482">507874482</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/soctics-league-online-multiplayer/id507874482?mt=8&uo=4">https://itunes.apple.com/us/app/soctics-league-online-multiplayer/id507874482?mt=8&uo=4</a>
**App Version:** 1.33
**Seller:** Bitongo Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bitongo-ltd./id294010458?mt=8&uo=4>© Bitongo Ltd.</a>
**Supported Devices:** iPodTouchFifthGen, iPadMini4G, iPodTouchFourthGen, iPhone-3GS, iPhone5s, iPhone4, iPhone5c, iPad23G, iPhone6Plus, iPhone4S, iPadMini, iPad2Wifi, iPhone5, iPadThirdGen4G, iPhone6, iPadFourthGen, iPadThirdGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://a1724.phobos.apple.com/us/r30/Purple6/v4/bd/9b/07/bd9b079e-a521-9a5b-de13-0f847888f6bf/mzl.xxfezeyi.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6748942/a8cf34e4-ceeb-11e4-90c5-a7f1680185ec.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6729739/cdd7d7f2-ce35-11e4-8d08-98ff66f1f8a9.png)
https://cloud.githubusercontent.com/assets/10730122/6729739/cdd7d7f2-ce35-11e4-8d08-98ff66f1f8a9.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6729732/c330566c-ce35-11e4-93a9-fdee5fc23472.png

*I had to draw the lines thicker, and I'm not the best at keeping my hand steady, hah.*

**Comment by dreamnet** [comment]
This should do the trick:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6748942/a8cf34e4-ceeb-11e4-90c5-a7f1680185ec.png)
https://cloud.githubusercontent.com/assets/2068130/6748942/a8cf34e4-ceeb-11e4-90c5-a7f1680185ec.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6748948/b54b680a-ceeb-11e4-9638-21b97ec8fbbe.png
