### ISSUE TITLE
lynda.com

### ISSUE THREAD

**Issue by ianbrk** [glasklart/hd#5375]
**App Name:** lynda.com
**Bundle ID:** com.lyndadotcom.lynda
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=356169777">356169777</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lynda.com/id356169777?mt=8&uo=4">https://itunes.apple.com/us/app/lynda.com/id356169777?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** lynda.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/lynda.com/id356169780?uo=4>© lynda.com</a>
**Supported Devices:** iPadThirdGen, iPadFourthGen, iPhone6Plus, iPadThirdGen4G, iPadMini4G, iPadFourthGen4G, iPad23G, iPhone4, iPad2Wifi, iPhone4S, iPodTouchFifthGen, iPhone6, iPhone5s, iPhone5c, iPhone5, iPadMini
**Original Artwork:**
<img src="http://a1946.phobos.apple.com/us/r30/Purple1/v4/14/57/99/14579948-e17e-b55e-d7b6-4eca532baba5/mzl.cbrqpqpv.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6740760/066e1702-ce59-11e4-9913-02fd3ed7e9f2.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738177/8273a7c4-ce70-11e4-82e5-e9fcb1794c31.png)
https://cloud.githubusercontent.com/assets/10730122/6738177/8273a7c4-ce70-11e4-82e5-e9fcb1794c31.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6738156/6605c676-ce70-11e4-954f-0c5d03f90454.png

**Comment by MagnaMike** [comment]
@Trubbel I made an inverted one. This way the white colour of the original icon matches up with the white of the glasklart layer style.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6740760/066e1702-ce59-11e4-9913-02fd3ed7e9f2.png)
https://cloud.githubusercontent.com/assets/2236254/6740760/066e1702-ce59-11e4-9913-02fd3ed7e9f2.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6740753/fd510454-ce58-11e4-88bd-e08e98dbd925.png

**Comment by Trubbel** [comment]
Yes indeed! Much better!
