### ISSUE TITLE
MINDBODY Connect

### ISSUE THREAD

**Issue by ianbrk** [glasklart/hd#5376]
**App Name:** MINDBODY Connect
**Bundle ID:** com.mindbodyonline.connect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=689501356">689501356</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mindbody-connect/id689501356?mt=8&uo=4">https://itunes.apple.com/us/app/mindbody-connect/id689501356?mt=8&uo=4</a>
**App Version:** 2.7.6
**Seller:** MINDBODY Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mindbody-inc./id348158349?uo=4>© MINDBODY Inc.</a>
**Supported Devices:** iPad23G, iPhone5s, iPadFourthGen, iPhone4, iPhone5c, iPad2Wifi, iPadMini4G, iPhone6Plus, iPhone5, iPadFourthGen4G, iPadMini, iPodTouchFifthGen, iPhone4S, iPadThirdGen4G, iPadThirdGen, iPhone6
**Original Artwork:**
<img src="http://a403.phobos.apple.com/us/r30/Purple3/v4/fe/3a/f9/fe3af9e9-fb2d-818a-fe5e-85eaa52f2ea8/mzl.utuuuczm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738705/0476c0d2-ce74-11e4-95a9-ca5e6adf1c75.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738674/dccec08e-ce73-11e4-8ed3-a050d3b5355e.png)
https://cloud.githubusercontent.com/assets/10730122/6738674/dccec08e-ce73-11e4-8ed3-a050d3b5355e.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6738659/d1096fc4-ce73-11e4-9053-8cb54c8fbb73.png

 
Alternate without the text,
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738705/0476c0d2-ce74-11e4-95a9-ca5e6adf1c75.png)
https://cloud.githubusercontent.com/assets/10730122/6738705/0476c0d2-ce74-11e4-95a9-ca5e6adf1c75.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6738697/fb83de24-ce73-11e4-9258-590597703ad7.png

**Comment by MagnaMike** [comment]
@Trubbel I think the one without the text. The logo seems like it is fairly recognizable.
