### ISSUE TITLE
Molecules by Theodore Gray

### ISSUE THREAD

**Issue by ianbrk** [glasklart/hd#5377]
**App Name:** Molecules by Theodore Gray
**Bundle ID:** com.touchpress.molecules
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923383841">923383841</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/molecules-by-theodore-gray/id923383841?mt=8&uo=4">https://itunes.apple.com/us/app/molecules-by-theodore-gray/id923383841?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Touchpress Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/touchpress-limited/id406795425?mt=8&uo=4>© Touchpress Limited</a>
**Supported Devices:** iPhone6Plus, iPadFourthGen4G, iPadMini4G, iPodTouchFifthGen, iPhone6, iPadFourthGen, iPad2Wifi, iPhone4, iPadThirdGen4G, iPhone5s, iPad23G, iPhone5c, iPhone4S, iPhone5, iPadThirdGen, iPadMini
**Original Artwork:**
<img src="http://a1831.phobos.apple.com/us/r30/Purple3/v4/56/d4/d4/56d4d4cc-c9f2-5ce1-4637-a87d5ca21288/mzl.hrvlgakk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738071/e5ca0e0e-ce6f-11e4-90c8-f71ca8d4fa47.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738071/e5ca0e0e-ce6f-11e4-90c8-f71ca8d4fa47.png)
https://cloud.githubusercontent.com/assets/10730122/6738071/e5ca0e0e-ce6f-11e4-90c8-f71ca8d4fa47.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6738062/da2dff9c-ce6f-11e4-86d1-c8b47616795b.png

**Comment by MagnaMike** [comment]
@Trubbel :+1:
