### ISSUE TITLE
Lyft - Taxi & Bus App Alternative

### ISSUE THREAD

**Issue by ianbrk** [glasklart/hd#5378]
**App Name:** Lyft - Taxi & Bus App Alternative
**Bundle ID:** com.zimride.instant
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=529379082">529379082</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lyft-taxi-bus-app-alternative/id529379082?mt=8&uo=4">https://itunes.apple.com/us/app/lyft-taxi-bus-app-alternative/id529379082?mt=8&uo=4</a>
**App Version:** 2.15.0
**Seller:** Lyft, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/lyft-inc./id523004506?uo=4>© Lyft, Inc.</a>
**Supported Devices:** iPhone4S, iPhone5c, iPhone5, iPhone4, iPodTouchFifthGen, iPhone6, iPhone5s, iPadThirdGen, iPhone6Plus, iPadFourthGen4G, iPadThirdGen4G, iPadMini4G, iPad2Wifi, iPadFourthGen, iPad23G, iPadMini
**Original Artwork:**
<img src="http://a1302.phobos.apple.com/us/r30/Purple5/v4/17/f7/05/17f7052d-1118-78ad-e7f1-0a3e374800bc/mzl.lqblqabd.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6739008/2b91de5c-ce76-11e4-8409-fae3d1d1e49c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738443/70ec0a62-ce72-11e4-82bc-2f39c7d42464.png)
https://cloud.githubusercontent.com/assets/10730122/6738443/70ec0a62-ce72-11e4-82bc-2f39c7d42464.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6738439/685e17a0-ce72-11e4-881d-d705033b42c9.png

**Comment by MagnaMike** [comment]
@Trubbel What's the difference? :eyes:

**Comment by Trubbel** [comment]
@MagnaMike First icon have the text slightly higher up, second one is more in the center (because of the y)

**Comment by MagnaMike** [comment]
@Trubbel Ah I see it now. I like the alternate. :+1:
