### ISSUE TITLE
The Elements in Action by Theodore Gray

### ISSUE THREAD

**Issue by ianbrk** [glasklart/hd#5379]
**App Name:** The Elements in Action by Theodore Gray
**Bundle ID:** com.touchpress.elementsinaction
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=739281034">739281034</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/elements-in-action-by-theodore/id739281034?mt=8&uo=4">https://itunes.apple.com/us/app/elements-in-action-by-theodore/id739281034?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Touchpress Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/touchpress-limited/id406795425?mt=8&uo=4>© Touchpress Limited</a>
**Supported Devices:** iPhone5c, iPadThirdGen4G, iPhone5, iPadFourthGen, iPhone6, iPhone5s, iPodTouchFifthGen, iPadMini4G, iPhone4, iPadFourthGen4G, iPadMini, iPadThirdGen, iPad2Wifi, iPhone4S, iPad23G, iPhone6Plus
**Original Artwork:**
<img src="http://a1369.phobos.apple.com/us/r30/Purple3/v4/8a/c5/2e/8ac52e26-dbbf-082d-2d27-d13eceaea2f4/pr_source.png?downloadKey=1426801014_4644c35879aa29cfac2d46af315fad90" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738840/ee6cf92c-ce74-11e4-893c-ca1421d5bb1d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738840/ee6cf92c-ce74-11e4-893c-ca1421d5bb1d.png)
https://cloud.githubusercontent.com/assets/10730122/6738840/ee6cf92c-ce74-11e4-893c-ca1421d5bb1d.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6738836/e44c39b2-ce74-11e4-8440-abca5e5a19bc.png
