### ISSUE TITLE
The Elements by Theodore Gray

### ISSUE THREAD

**Issue by ianbrk** [glasklart/hd#5380]
**App Name:** The Elements by Theodore Gray
**Bundle ID:** com.elementcollection.elementsipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364147847">364147847</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-elements-by-theodore-gray/id364147847?mt=8&uo=4">https://itunes.apple.com/us/app/the-elements-by-theodore-gray/id364147847?mt=8&uo=4</a>
**App Version:** 2.0.4
**Seller:** Touchpress Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/touchpress-limited/id406795425?mt=8&uo=4>© Touchpress Limited</a>
**Supported Devices:** iPadFourthGen4G, iPhone4, iPadMini4G, iPadMini, iPadThirdGen, iPad23G, iPadThirdGen4G, iPhone5, iPhone6Plus, iPhone5s, iPhone6, iPodTouchFifthGen, iPhone4S, iPhone5c, iPadFourthGen, iPad2Wifi
**Original Artwork:**
<img src="http://a1300.phobos.apple.com/us/r30/Purple5/v4/7e/e9/7c/7ee97c6c-802d-6877-8f3e-dcec55ff5ff5/pr_source.png?downloadKey=1426801264_fff1a042668b8ec8fb8f90c79107fec5" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6766850/22284b4c-d017-11e4-8d86-bbf8ea5f5a37.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738265/3f98f0fc-ce71-11e4-844c-731e1a1c121b.png)
https://cloud.githubusercontent.com/assets/10730122/6738265/3f98f0fc-ce71-11e4-844c-731e1a1c121b.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6738256/35c694e4-ce71-11e4-8a50-3467b48eccae.png

**Comment by dreamnet** [comment]
Did some small corrections (wrong source):
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6766850/22284b4c-d017-11e4-8d86-bbf8ea5f5a37.png)
https://cloud.githubusercontent.com/assets/2068130/6766850/22284b4c-d017-11e4-8d86-bbf8ea5f5a37.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6766853/31849014-d017-11e4-8c7f-4ead05d98139.png
