### ISSUE TITLE
Gorilla Workout: Fitness Aerobic Strength and Exercise Trainer Program on a Budget

### ISSUE THREAD

**Issue by ianbrk** [glasklart/hd#5381]
**App Name:** Gorilla Workout: Fitness Aerobic Strength and Exercise Trainer Program on a Budget
**Bundle ID:** com.gorillaworkoutapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=434101127">434101127</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gorilla-workout-fitness-aerobic/id434101127?mt=8&uo=4">https://itunes.apple.com/us/app/gorilla-workout-fitness-aerobic/id434101127?mt=8&uo=4</a>
**App Version:** 4.5.0
**Seller:** Heckr LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/heckr-llc/id434101130?uo=4>© Heckr LLC</a>
**Supported Devices:** iPadMini, iPodTouchFifthGen, iPadWifi, iPhone6Plus, iPadThirdGen, iPhone-3GS, iPhone5, iPadMini4G, iPad23G, iPadFourthGen4G, iPadFourthGen, iPhone4S, iPhone5c, iPodTouchThirdGen, iPadThirdGen4G, iPodTouchFourthGen, iPad3G, iPhone5s, iPhone4, iPad2Wifi, iPhone6
**Original Artwork:**
<img src="http://a1734.phobos.apple.com/us/r30/Purple5/v4/f0/66/27/f0662799-3595-dfa8-a9a5-00b9851f2df4/mzl.pvltdcie.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6741682/ea16e080-ce89-11e4-95b7-7b68db59ce72.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6741332/e2189bce-ce86-11e4-992d-12d183ef7224.png)
https://cloud.githubusercontent.com/assets/10730122/6741332/e2189bce-ce86-11e4-992d-12d183ef7224.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6741326/d42b77ca-ce86-11e4-81f6-0819602b8bac.png

**Comment by MagnaMike** [comment]
@Trubbel I'm not a fan of the eyes, otherwise looks good. :+1: Try inverting the eyes?

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6741682/ea16e080-ce89-11e4-95b7-7b68db59ce72.png)
https://cloud.githubusercontent.com/assets/10730122/6741682/ea16e080-ce89-11e4-95b7-7b68db59ce72.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6741726/567d4c8c-ce8a-11e4-9045-9e668a7372c3.png

 
Alternate,
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6741748/7f2f2952-ce8a-11e4-81de-eab2495bce73.png)
https://cloud.githubusercontent.com/assets/10730122/6741748/7f2f2952-ce8a-11e4-81de-eab2495bce73.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6741742/6a764cf2-ce8a-11e4-8f1c-e11034955cb1.png


---

Made two versions, there's no huge different between them.

**Comment by MagnaMike** [comment]
@Trubbel First of the second batch. :+1:
