### ISSUE TITLE
Hue Lights

### ISSUE THREAD

**Issue by ianbrk** [glasklart/hd#5382]
**App Name:** Hue Lights
**Bundle ID:** com.lapapps.HueLights
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=762009425">762009425</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hue-lights/id762009425?uo=4">https://apps.apple.com/us/app/hue-lights/id762009425?uo=4</a>
**App Version:** 3.4
**Seller:** LapApps, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/lapapps-llc/id762009431?uo=4">© LapApps, LLC</a>
**Supported Devices:** Watch4-Watch4, iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/ed/a1/97/eda19792-0229-fb9b-5c17-abeaf5fe7028/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62396203-d2db5700-b572-11e9-8c5c-09e6caff349b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6767457/387e9544-d031-11e4-819d-c43f68965ded.png)
https://cloud.githubusercontent.com/assets/2068130/6767457/387e9544-d031-11e4-819d-c43f68965ded.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6767458/49fd2f74-d031-11e4-8686-d989e62fde11.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62396203-d2db5700-b572-11e9-8c5c-09e6caff349b.png)
https://user-images.githubusercontent.com/2068130/62396203-d2db5700-b572-11e9-8c5c-09e6caff349b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62396226-e2f33680-b572-11e9-9b3b-ce3af46518b0.png
