### ISSUE TITLE
Capital One Wallet

### ISSUE THREAD

**Issue by ianbrk** [glasklart/hd#5383]
**App Name:** Capital One Wallet
**Bundle ID:** com.capitalone.wallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=907210949">907210949</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/capital-one-wallet/id907210949?mt=8&uo=4">https://itunes.apple.com/us/app/capital-one-wallet/id907210949?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** Capital One Services, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/capital-one/id339644101?uo=4>© Capital One</a>
**Supported Devices:** iPad23G, iPhone6Plus, iPadThirdGen, iPadMini4G, iPadFourthGen, iPadFourthGen4G, iPhone5s, iPhone4S, iPodTouchFifthGen, iPadMini, iPhone4, iPad2Wifi, iPadThirdGen4G, iPhone5, iPhone5c, iPhone6
**Original Artwork:**
<img src="http://a902.phobos.apple.com/us/r30/Purple5/v4/09/f0/ca/09f0ca82-49c3-9306-41e5-d9f92de6d224/mzl.khlhpcae.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6740949/387402f6-ce5a-11e4-92ff-87d58f872bbe.png)

**Comment by ianbrk** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/1429081/6739065/b4375662-ce4c-11e4-88bc-49c48e13e8e6.png)

Source:
![](https://cloud.githubusercontent.com/assets/1429081/6739066/b6486a22-ce4c-11e4-96b7-4387dde3ede5.png)

**Comment by MagnaMike** [comment]
@ianbrk Glasklart icon glyphs must be 78px by 78px or less (See the guidelines on the icon preview)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6740949/387402f6-ce5a-11e4-92ff-87d58f872bbe.png)
https://cloud.githubusercontent.com/assets/2236254/6740949/387402f6-ce5a-11e4-92ff-87d58f872bbe.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6740946/32fa4e66-ce5a-11e4-9118-bc385d7c6957.png

**Comment by ianbrk** [comment]
Ah, ok. Sorry about that.

Your icon is pretty good as it still is clearly different from the main Capital One app.

**Comment by MagnaMike** [comment]
@ianbrk No problem! Alright I'll take it then.
