### ISSUE TITLE
BoltBus

### ISSUE THREAD

**Issue by ianbrk** [glasklart/hd#5384]
**App Name:** BoltBus
**Bundle ID:** com.boltbus.mobile.BBConsumer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=868213517">868213517</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boltbus/id868213517?mt=8&uo=4">https://itunes.apple.com/us/app/boltbus/id868213517?mt=8&uo=4</a>
**App Version:** 1.7.901
**Seller:** Firstgroup America Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/firstgroup-america-inc/id868213520?uo=4>© Firstgroup America Inc</a>
**Supported Devices:** iPodTouchFifthGen, iPodTouchFourthGen, iPhone5s, iPhone6Plus, iPadThirdGen, iPhone5c, iPadMini4G, iPhone6, iPadFourthGen4G, iPadFourthGen, iPhone-3GS, iPad2Wifi, iPhone4S, iPad23G, iPadMini, iPhone5, iPhone4, iPadThirdGen4G
**Original Artwork:**
<img src="http://a542.phobos.apple.com/us/r30/Purple3/v4/23/b6/88/23b6882e-defe-19f3-1a89-6c79921706da/mzl.cisguvrb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738346/aed7984c-ce71-11e4-99dd-4c860c1882dc.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6738346/aed7984c-ce71-11e4-99dd-4c860c1882dc.png)
https://cloud.githubusercontent.com/assets/10730122/6738346/aed7984c-ce71-11e4-99dd-4c860c1882dc.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6738353/bbf9c96e-ce71-11e4-98dd-71cb11aad7b9.png
