### ISSUE TITLE
My AEK - Official AEK FC App

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5385]
**App Name:** My AEK - Official AEK FC App
**Bundle ID:** gr.aekfc.aekmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=863831300">863831300</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-aek-official-aek-fc-app/id863831300?mt=8&uo=4">https://itunes.apple.com/us/app/my-aek-official-aek-fc-app/id863831300?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** AEK F.C.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/aek-fc/id863831303?uo=4>© AEK FC</a>
**Supported Devices:** iPadFourthGen4G, iPhone4S, iPadFourthGen, iPhone6Plus, iPadMini, iPad2Wifi, iPadThirdGen, iPhone5s, iPhone5c, iPadMini4G, iPad23G, iPadThirdGen4G, iPodTouchFifthGen, iPhone6, iPhone4, iPhone5
**Original Artwork:**
<img src="http://a1340.phobos.apple.com/us/r30/Purple5/v4/ab/a0/68/aba068c5-d32c-3a20-36a0-37b632f36182/mzl.fflmawzm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6740837/7fe43422-ce59-11e4-83d4-9ec386bf737c.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6740837/7fe43422-ce59-11e4-83d4-9ec386bf737c.png)
https://cloud.githubusercontent.com/assets/2236254/6740837/7fe43422-ce59-11e4-83d4-9ec386bf737c.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6740842/82ee96da-ce59-11e4-9b9c-a49ed232f9c6.png

**Comment by dreamnet** [comment]
@MagnaMike Jup! :+1:
