### ISSUE TITLE
New York Travel Guide (with Offline Maps) NYC - mTrip Travel Guides

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5386]
**App Name:** New York Travel Guide (with Offline Maps) NYC - mTrip Travel Guides
**Bundle ID:** com.mtrip.New-York
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377137875">377137875</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-york-travel-guide-offline/id377137875?mt=8&uo=4">https://itunes.apple.com/us/app/new-york-travel-guide-offline/id377137875?mt=8&uo=4</a>
**App Version:** 2.6.1
**Seller:** mTrip Travel Guide
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mtrip-travel-guides/id377126417?uo=4>© mTrip Travel Guides</a>
**Supported Devices:** iPhone4S, iPhone6Plus, iPad23G, iPad2Wifi, iPadMini4G, iPhone4, iPadFourthGen4G, iPadMini, iPadThirdGen, iPhone5c, iPodTouchFifthGen, iPhone5, iPadFourthGen, iPadThirdGen4G, iPhone6, iPhone5s
**Original Artwork:**
<img src="http://a47.phobos.apple.com/us/r30/Purple3/v4/1a/1e/25/1a1e25ab-df65-c3bf-cf1b-219a241e24da/mzl.lwfztbqd.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6741155/aea94e6c-ce5b-11e4-8c72-aaefdf1ac7b1.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6740848/74b9d910-ce83-11e4-9ed6-bb6209ce29ce.png)
https://cloud.githubusercontent.com/assets/10730122/6740848/74b9d910-ce83-11e4-9ed6-bb6209ce29ce.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6740836/67b0b338-ce83-11e4-9be7-4d76503a6360.png

 
Alternate,
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6740831/5ba96af8-ce83-11e4-97f1-9600935be6b1.png)
https://cloud.githubusercontent.com/assets/10730122/6740831/5ba96af8-ce83-11e4-97f1-9600935be6b1.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6740819/4fb27d3e-ce83-11e4-92d4-b191e6c366c1.png

**Comment by MagnaMike** [comment]
@Trubbel I wanted to match the corner radius with the icon baseplate:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6741155/aea94e6c-ce5b-11e4-8c72-aaefdf1ac7b1.png)
https://cloud.githubusercontent.com/assets/2236254/6741155/aea94e6c-ce5b-11e4-8c72-aaefdf1ac7b1.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6741164/be760dee-ce5b-11e4-9d4e-da3376d97452.png
