### ISSUE TITLE
San Francisco Travel Guide (with Offline Maps) - mTrip

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5387]
**App Name:** San Francisco Travel Guide (with Offline Maps) - mTrip
**Bundle ID:** com.mtrip.San-Francisco
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377138967">377138967</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/san-francisco-travel-guide/id377138967?mt=8&uo=4">https://itunes.apple.com/us/app/san-francisco-travel-guide/id377138967?mt=8&uo=4</a>
**App Version:** 2.6.1
**Seller:** mTrip Travel Guide
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mtrip-travel-guides/id377126417?uo=4>© mTrip Travel Guides</a>
**Supported Devices:** iPadThirdGen4G, iPhone4S, iPadThirdGen, iPadFourthGen4G, iPadMini4G, iPhone6Plus, iPad2Wifi, iPhone6, iPhone5s, iPodTouchFifthGen, iPad23G, iPhone5c, iPhone5, iPadMini, iPhone4, iPadFourthGen
**Original Artwork:**
<img src="http://a1460.phobos.apple.com/us/r30/Purple3/v4/eb/27/b6/eb27b6e4-8c2f-e9f4-2cb5-d9d27565d760/mzl.vmbjmwro.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6741127/8919aee4-ce5b-11e4-9f45-d6b9731f9d8f.png)

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6741127/8919aee4-ce5b-11e4-9f45-d6b9731f9d8f.png)
https://cloud.githubusercontent.com/assets/2236254/6741127/8919aee4-ce5b-11e4-9f45-d6b9731f9d8f.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6741115/7d571858-ce5b-11e4-9a4d-93eb04aa5be3.png
