### ISSUE TITLE
Aruba Travel Guide

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5388]
**App Name:** Aruba Travel Guide
**Bundle ID:** com.arubatourism.guide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526111011">526111011</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aruba-travel-guide/id526111011?mt=8&uo=4">https://itunes.apple.com/us/app/aruba-travel-guide/id526111011?mt=8&uo=4</a>
**App Version:** 2.6.2
**Seller:** Aruba Tourism Authority Apps
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/aruba-tourism-authority/id526111014?uo=4>© Aruba Tourism Authority</a>
**Supported Devices:** iPadThirdGen4G, iPodTouchFifthGen, iPad2Wifi, iPadFourthGen, iPadMini4G, iPadMini, iPadThirdGen, iPhone6Plus, iPhone4S, iPhone5, iPadFourthGen4G, iPhone5c, iPhone5s, iPad23G, iPhone6, iPhone4
**Original Artwork:**
<img src="http://a439.phobos.apple.com/us/r30/Purple1/v4/03/bf/f1/03bff1f0-2f43-a419-99ac-d0189819b768/pr_source.png?downloadKey=1426808585_68cdea023d99fd673d803b935110c26e" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6744727/3526e248-ce83-11e4-8fcd-8159694ebb5b.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6744727/3526e248-ce83-11e4-8fcd-8159694ebb5b.png)
https://cloud.githubusercontent.com/assets/10950389/6744727/3526e248-ce83-11e4-8fcd-8159694ebb5b.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6744730/416cc810-ce83-11e4-9288-2e8192ff5dca.png
