### ISSUE TITLE
The Wolf Among Us

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5394]
**App Name:** The Wolf Among Us
**Bundle ID:** com.telltalegames.wau100
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=716238885">716238885</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-wolf-among-us/id716238885?mt=8&uo=4">https://itunes.apple.com/us/app/the-wolf-among-us/id716238885?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Telltale Games
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/telltale-inc/id364177939?uo=4>© Telltale Inc</a>
**Supported Devices:** iPadThirdGen4G, iPhone5c, iPhone-3GS, iPhone5s, iPhone4, iPad23G, iPhone6, iPadMini4G, iPadFourthGen4G, iPodTouchFifthGen, iPadThirdGen, iPadMini, iPhone6Plus, iPhone5, iPadFourthGen, iPad2Wifi, iPodTouchFourthGen, iPhone4S
**Original Artwork:**
<img src="http://a325.phobos.apple.com/us/r30/Purple/v4/f4/f9/96/f4f99687-19c3-b130-458e-99efddd418b3/mzl.edhwanui.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6769167/378099c6-d090-11e4-842d-da432a8b4b1c.png)

**Comment by zmathiasz** [comment]
That is strange.  The icon on my phone is different from the one pulled by the data crawler.  I guess it really doesn't matter in the end. :smile: 

https://cloud.githubusercontent.com/assets/10950389/6744915/953a686a-ce85-11e4-9dec-920693c61b31.jpg)

**Comment by MagnaMike** [comment]
@zmathiasz The one on your phone looks easier to theme, maybe we should just do it off that?

**Comment by zmathiasz** [comment]
That may work.  How about these though?  My first illustrator made icons. :grin: 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6745184/28aa0a5c-ce8a-11e4-8d00-e8977266872c.png)
https://cloud.githubusercontent.com/assets/10950389/6745184/28aa0a5c-ce8a-11e4-8d00-e8977266872c.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6745188/36b8d6a0-ce8a-11e4-88c8-d68b7579236d.png

**Comment by zmathiasz** [comment]
Alternate:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6745198/6c9ba36a-ce8a-11e4-90ad-6e056c164eca.png)
https://cloud.githubusercontent.com/assets/10950389/6745198/6c9ba36a-ce8a-11e4-90ad-6e056c164eca.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6745205/7e724418-ce8a-11e4-8c1d-d962f5117641.png

**Comment by MagnaMike** [comment]
@zmathiasz Nice! I'm just worried that the text won't show up very well, can you try increasing the thickness of the lettering outline?

**Comment by zmathiasz** [comment]
@MagnaMike How about so?  Much cleaner I think and with thicker lines for text...except where it says a telltale games series....much to small to make thicker.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6745548/928ee7e0-ce8e-11e4-8d08-24a369758dad.png)
https://cloud.githubusercontent.com/assets/10950389/6745548/928ee7e0-ce8e-11e4-8d08-24a369758dad.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6745552/a4219746-ce8e-11e4-9867-c0107d78f48f.png

**Comment by zmathiasz** [comment]
Or a simpler choice..which is what the icon looks like on my phone.  :smile: 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6767765/23fe2df6-d01c-11e4-9630-249ad1032c73.png)
https://cloud.githubusercontent.com/assets/10950389/6767765/23fe2df6-d01c-11e4-9630-249ad1032c73.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6767766/312cc94c-d01c-11e4-87a7-1d94b6a12bb5.png

**Comment by dreamnet** [comment]
Here is a combination of the icons from @zmathiasz  above:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6769167/378099c6-d090-11e4-842d-da432a8b4b1c.png)
https://cloud.githubusercontent.com/assets/2068130/6769167/378099c6-d090-11e4-842d-da432a8b4b1c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6769168/5a577e56-d090-11e4-829d-f2ebf4679f9d.png
I take this one - credits are going to @zmathiasz !
