### ISSUE TITLE
AppZapp Notify - Personal Alerts for Apps on Sale & New Apps

### ISSUE THREAD

**Issue by andreolidavide** [glasklart/hd#5395]
**App Name:** AppZapp Notify - Personal Alerts for Apps on Sale & New Apps
**Bundle ID:** net.appzapp.universal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=845046425">845046425</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appzapp-notify-personal-alerts/id845046425?mt=8&uo=4">https://itunes.apple.com/us/app/appzapp-notify-personal-alerts/id845046425?mt=8&uo=4</a>
**App Version:** 6.4
**Seller:** ConIT AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/conit-ag/id375733294?uo=4>© ConIT AG</a>
**Supported Devices:** iPhone6Plus, iPad23G, iPadFourthGen, iPhone6, iPodTouchFifthGen, iPadThirdGen, iPadThirdGen4G, iPhone5s, iPhone4S, iPhone5, iPadMini, iPadMini4G, iPad2Wifi, iPhone4, iPadFourthGen4G, iPhone5c
**Original Artwork:**
<img src="http://a1838.phobos.apple.com/us/r30/Purple3/v4/87/75/d8/8775d827-ee54-e519-5d9f-4032d5216aa3/mzl.qkxlpggc.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6766180/ee5279b6-cffb-11e4-843e-dc6a888ce976.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6752022/e51c5be2-cf0a-11e4-9cd5-12d5c62a7714.png)
https://cloud.githubusercontent.com/assets/10515074/6752022/e51c5be2-cf0a-11e4-9cd5-12d5c62a7714.png
Source
https://cloud.githubusercontent.com/assets/10515074/6752028/f2b60ea6-cf0a-11e4-804c-fbfcedc24272.png

**Comment by ivanov007** [comment]
@andreolidavide great :+1:

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6766180/ee5279b6-cffb-11e4-843e-dc6a888ce976.png)
https://cloud.githubusercontent.com/assets/10730122/6766180/ee5279b6-cffb-11e4-843e-dc6a888ce976.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6766176/da98707e-cffb-11e4-8ac0-a999aeb8c6af.png

--

*I think it would look better if it was as close to the original icon as possible, it's a sonar after all.*

**Comment by ivanov007** [comment]
@Trubbel yup it looks better that way :+1:
