### ISSUE TITLE
ANSA Mobile

### ISSUE THREAD

**Issue by andreolidavide** [glasklart/hd#5396]
**App Name:** ANSA Mobile
**Bundle ID:** it.ansamobile2013.ANSAMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=672672340">672672340</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ansa-mobile/id672672340?mt=8&uo=4">https://itunes.apple.com/us/app/ansa-mobile/id672672340?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Agenzia Ansa sc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/agenzia-ansa-sc/id406184243?uo=4>© Agenzia Ansa sc</a>
**Supported Devices:** iPodTouchThirdGen, iPhone5s, iPhone6Plus, iPadFourthGen, iPhone5c, iPhone5, iPodTouchFourthGen, iPhone4S, iPadFourthGen4G, iPadWifi, iPhone4, iPad3G, iPodTouchFifthGen, iPad23G, iPhone6, iPhone-3GS, iPadMini, iPadThirdGen4G, iPadMini4G, iPad2Wifi, iPadThirdGen
**Original Artwork:**
<img src="http://a1182.phobos.apple.com/us/r30/Purple5/v4/2d/03/27/2d03275f-6758-3b90-de75-cf7f91eeb66b/mzl.wrreyikz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6767102/6a08538a-d021-11e4-9d33-9f11e9e8f9be.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6752048/3b8ec762-cf0b-11e4-8804-55afd2d51a73.png)
Source
https://cloud.githubusercontent.com/assets/10515074/6752057/46c5786a-cf0b-11e4-9d21-cb07c3680956.png



Or this
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/6752065/535d8f04-cf0b-11e4-9969-80bdeb474535.png)
Source
https://cloud.githubusercontent.com/assets/10515074/6752069/5fc2b9f4-cf0b-11e4-9955-5cf3c45914e2.png

**Comment by dreamnet** [comment]
This one:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6767102/6a08538a-d021-11e4-9d33-9f11e9e8f9be.png)
https://cloud.githubusercontent.com/assets/2068130/6767102/6a08538a-d021-11e4-9d33-9f11e9e8f9be.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6767104/7984fc32-d021-11e4-9f7c-cd42bec3d5a7.png
