### ISSUE TITLE
Sky Burger - Build & Match Food Free

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5398]
**App Name:** Sky Burger - Build & Match Food Free
**Bundle ID:** com.eeenmachine.SkyBurger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=311972587">311972587</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sky-burger-build-match-food/id311972587?mt=8&uo=4">https://itunes.apple.com/us/app/sky-burger-build-match-food/id311972587?mt=8&uo=4</a>
**App Version:** 2.2.2
**Seller:** NimbleBit LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nimblebit-llc/id285808572?mt=8&uo=4>© NimbleBit LLC</a>
**Supported Devices:** iPad3G, iPhone5, iPodTouchThirdGen, iPhone6, iPadMini, iPhone4S, iPad23G, iPhone-3GS, iPadMini4G, iPhone5s, iPadFourthGen4G, iPhone6Plus, iPodTouchFourthGen, iPadFourthGen, iPhone5c, iPadThirdGen4G, iPadThirdGen, iPhone4, iPadWifi, iPodTouchFifthGen, iPad2Wifi
**Original Artwork:**
<img src="http://a811.phobos.apple.com/us/r30/Purple3/v4/d2/5a/15/d25a15c6-f417-3d58-9f55-ce609c17b3bb/mzl.ugsnknnq.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6767824/e2ea14a4-d01d-11e4-9b6a-7cbb26182e63.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6767824/e2ea14a4-d01d-11e4-9b6a-7cbb26182e63.png)
https://cloud.githubusercontent.com/assets/10950389/6767824/e2ea14a4-d01d-11e4-9b6a-7cbb26182e63.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6767825/eda77bfc-d01d-11e4-8bfb-10db57bc6881.png

**Comment by dreamnet** [comment]
@zmathiasz :+1:
