### ISSUE TITLE
Slayin

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5399]
**App Name:** Slayin
**Bundle ID:** com.FDGEntertainment.Slayin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=548580856">548580856</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slayin/id548580856?mt=8&uo=4">https://itunes.apple.com/us/app/slayin/id548580856?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** FDG Mobile Games GbR
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fdg-entertainment/id302980375?uo=4>© FDG Entertainment</a>
**Supported Devices:** iPadMini4G, iPhone6, iPadFourthGen4G, iPodTouchFifthGen, iPhone4, iPad23G, iPodTouchThirdGen, iPadFourthGen, iPhone5s, iPhone4S, iPhone6Plus, iPhone-3GS, iPadThirdGen4G, iPhone5c, iPadThirdGen, iPad3G, iPadMini, iPad2Wifi, iPadWifi, iPhone5, iPodTouchFourthGen
**Original Artwork:**
<img src="http://a1799.phobos.apple.com/us/r30/Purple/v4/4c/57/60/4c5760d7-a87e-a9ca-e16a-d0a679a08e63/mzl.kgkroynk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6992419/3ad191e2-dacd-11e4-975f-3f7775535781.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6992419/3ad191e2-dacd-11e4-975f-3f7775535781.png)
https://cloud.githubusercontent.com/assets/2068130/6992419/3ad191e2-dacd-11e4-975f-3f7775535781.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6992422/4b343d14-dacd-11e4-92f6-3ea662c1e6e5.png

**Comment by MagnaMike** [comment]
@dreamnet Nice!
