### ISSUE TITLE
Terraria

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5400]
**App Name:** Terraria
**Bundle ID:** com.505games.terraria
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=640364616">640364616</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/terraria/id640364616?mt=8&uo=4">https://itunes.apple.com/us/app/terraria/id640364616?mt=8&uo=4</a>
**App Version:** 1.2.8498
**Seller:** 505 Games (US), Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/505-games-us-inc./id392990484?uo=4>© 505 Games (US), Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadMini, iPhone6, iPadFourthGen, iPodTouchFifthGen, iPadThirdGen, iPhone5c, iPhone5, iPhone5s, iPadMini4G, iPhone4, iPhone4S, iPadThirdGen4G, iPhone6Plus, iPadFourthGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple2/v4/8c/89/84/8c898476-4b15-429d-9313-9aa3f6715658/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7627629/9e7a962e-fa19-11e4-8c13-d56c31edc3d3.png)

**Comment by iNfeCtGFX** [comment]
I mean, no one has made an attempt, so here goes.
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/7173134/b9e27b4a-e42d-11e4-9042-a2e537c346ff.png)
https://cloud.githubusercontent.com/assets/10008202/7173134/b9e27b4a-e42d-11e4-9042-a2e537c346ff.png
**Source**
https://cloud.githubusercontent.com/assets/10008202/7173137/c70a552c-e42d-11e4-8214-18b7b288803c.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7221468/4f4d1364-e6ec-11e4-8b0e-05dff5b55c22.png)
https://cloud.githubusercontent.com/assets/2068130/7221468/4f4d1364-e6ec-11e4-8b0e-05dff5b55c22.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7221469/5f33befe-e6ec-11e4-800e-9f5d1a1b52fb.png

**Comment by MagnaMike** [comment]
I *think* this might be a seasonal icon though. If that's the case we should try to make the icon for the standard version.

**Comment by dreamnet** [comment]
@MagnaMike You are right.
Mabe this is the standard icon?:
<img src="https://cloud.githubusercontent.com/assets/2068130/7240149/4e56bac8-e7af-11e4-8f6d-b7754fb4df92.png" height="150" width="150">

**Comment by MagnaMike** [comment]
@dreamnet I think it is

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7627629/9e7a962e-fa19-11e4-8c13-d56c31edc3d3.png)
https://cloud.githubusercontent.com/assets/2068130/7627629/9e7a962e-fa19-11e4-8c13-d56c31edc3d3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7627633/b1bc0038-fa19-11e4-8d09-6969765b6b79.png
I think this one is OK....
