### ISSUE TITLE
Star Wars®: Knights of the Old Republic™

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5401]
**App Name:** Star Wars®: Knights of the Old Republic™
**Bundle ID:** com.aspyr.kotor.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=611436052">611436052</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/star-wars-knights-old-republic/id611436052?mt=8&uo=4">https://itunes.apple.com/us/app/star-wars-knights-old-republic/id611436052?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Aspyr Media (iDP)
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/aspyr-media-inc./id296399696?uo=4>© Aspyr Media, Inc.</a>
**Supported Devices:** iPhone5s, iPhone-3GS, iPhone5, iPhone4S, iPadThirdGen4G, iPodTouchFifthGen, iPhone5c, iPad23G, iPadMini4G, iPadFourthGen4G, iPadThirdGen, iPadMini, iPhone4, iPhone6Plus, iPadFourthGen, iPhone6, iPodTouchFourthGen, iPad2Wifi
**Original Artwork:**
<img src="http://a1385.phobos.apple.com/us/r30/Purple1/v4/21/14/d9/2114d919-d1bb-34c5-b4db-09c44ded17c4/mzl.bkojgasa.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6767521/ecd044e2-d00a-11e4-8804-3ed518a9bbb6.png)

**Comment by zmathiasz** [comment]
In the process of learning illustrator.  So many awesome features.  This is fairly basic though.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6767521/ecd044e2-d00a-11e4-8804-3ed518a9bbb6.png)
https://cloud.githubusercontent.com/assets/10950389/6767521/ecd044e2-d00a-11e4-8804-3ed518a9bbb6.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6767523/fa5dd700-d00a-11e4-890c-baaa94a8f5ec.png

**Comment by iNfeCtGFX** [comment]
I inverted the color scheme and cleaned up the edges a bit.

![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/6773216/d195992e-d150-11e4-8b1f-fe9d08562ac9.png)
https://cloud.githubusercontent.com/assets/10008202/6773220/dd1a72f6-d150-11e4-881c-44ad95273ee9.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/6773223/e37c868e-d150-11e4-9056-c5a3caf7449e.png

**Comment by iNfeCtGFX** [comment]
Version 2
![](http://preview.dreamnet.at?image=(https://cloud.githubusercontent.com/assets/10008202/6817617/aadf78c6-d2e6-11e4-90f3-b42827c13b18.png)
https://cloud.githubusercontent.com/assets/10008202/6817617/aadf78c6-d2e6-11e4-90f3-b42827c13b18.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/6817628/d3f96b68-d2e6-11e4-8ef0-cd1e4466a3df.png

**Comment by dreamnet** [comment]
Very hard one - from the ones submitted personally i like te first from @zmathiasz most. I take it.
