### ISSUE TITLE
AppJoy - Watch Game Videos and Movie Trailers For Popular Rewards With AppNana Gift

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5402]
**App Name:** AppJoy - Watch Game Videos and Movie Trailers For Popular Rewards With AppNana Gift
**Bundle ID:** com.appjoy.appstore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=970048488">970048488</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appjoy-watch-game-videos-movie/id970048488?mt=8&uo=4">https://itunes.apple.com/us/app/appjoy-watch-game-videos-movie/id970048488?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Sha Qian
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sha-qian/id970048487?uo=4>© Sha Qian</a>
**Supported Devices:** iPhone5s, iPadMini4G, iPadThirdGen, iPhone4S, iPhone-3GS, iPhone4, iPadMini, iPhone6, iPhone5, iPadThirdGen4G, iPodTouchFourthGen, iPadFourthGen4G, iPadFourthGen, iPad2Wifi, iPhone5c, iPhone6Plus, iPad23G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a718.phobos.apple.com/us/r30/Purple3/v4/05/7b/4c/057b4c43-01ed-c7cd-cb30-24e5fa1512df/pr_source.png?downloadKey=1426976325_6de3232d391a22b8064d7632e4f9eb1b" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6766529/f92beeb0-cfdf-11e4-8209-efc3c05c13dd.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6766489/a9a95d10-cfde-11e4-8ea6-4da84b9e32b8.png)
https://cloud.githubusercontent.com/assets/10950389/6766489/a9a95d10-cfde-11e4-8ea6-4da84b9e32b8.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6766492/ba1cb692-cfde-11e4-809b-0c36d34828b7.png

**Comment by zmathiasz** [comment]
I was gonna say or....lol

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6766529/f92beeb0-cfdf-11e4-8209-efc3c05c13dd.png)
https://cloud.githubusercontent.com/assets/10950389/6766529/f92beeb0-cfdf-11e4-8209-efc3c05c13dd.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6766530/056e59ce-cfe0-11e4-9651-32e93d33c61f.png

**Comment by ivanov007** [comment]
@zmathiasz  mhh the alternate is good too, witch one did you prefer?

**Comment by zmathiasz** [comment]
I like the alt. Looks more like a box as should. :)

**Comment by dreamnet** [comment]
@zmathiasz OK, taken.
