### ISSUE TITLE
Book List - Bookshelf Manager, Collector, Organizer & Inventory Database Buddy

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5403]
**App Name:** Book List - Bookshelf Manager, Collector, Organizer & Inventory Database Buddy
**Bundle ID:** com.sortitapps.books
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476621639">476621639</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/book-list-bookshelf-manager/id476621639?mt=8&uo=4">https://itunes.apple.com/us/app/book-list-bookshelf-manager/id476621639?mt=8&uo=4</a>
**App Version:** 4.9.1
**Seller:** Elizabeth Allen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runner-apps/id477339462?uo=4>© Runner Apps</a>
**Supported Devices:** iPhone-3GS, iPhone4S, iPad2Wifi, iPhone6Plus, iPadFourthGen4G, iPhone5s, iPhone5c, iPadMini, iPhone4, iPad23G, iPadThirdGen, iPadFourthGen, iPadMini4G, iPhone6, iPodTouchFourthGen, iPhone5, iPodTouchFifthGen, iPadThirdGen4G
**Original Artwork:**
<img src="http://a1256.phobos.apple.com/us/r30/Purple5/v4/60/a0/2d/60a02d71-d246-272c-2fb2-8bbc9f60ab14/mzl.jvqkfvxu.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6768932/ece176d4-d084-11e4-90fa-f570c3202ff9.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6767980/b6ffe946-d026-11e4-801b-a23921cccd7b.png)
https://cloud.githubusercontent.com/assets/10950389/6767980/b6ffe946-d026-11e4-801b-a23921cccd7b.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6767981/cf33a2dc-d026-11e4-80a3-dad3ae466a66.png

**Comment by dreamnet** [comment]
@zmathiasz Jes! :+1:
