### ISSUE TITLE
Hotels.com - Hotel booking and last minute hotel deals

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5408]
**App Name:** Hotels.com - Hotel booking and last minute hotel deals
**Bundle ID:** com.hotels.HotelsNearMe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284971959">284971959</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hotels.com-hotel-booking-last/id284971959?mt=8&uo=4">https://itunes.apple.com/us/app/hotels.com-hotel-booking-last/id284971959?mt=8&uo=4</a>
**App Version:** 4.4
**Seller:** Hotels.com, L.P.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hotels.com/id284971962?uo=4>© Hotels.com</a>
**Supported Devices:** iPhone4, iPhone6Plus, iPadThirdGen4G, iPhone5c, iPhone4S, iPadFourthGen4G, iPadMini, iPad23G, iPadMini4G, iPadThirdGen, iPodTouchFifthGen, iPhone6, iPadFourthGen, iPhone5, iPad2Wifi, iPhone5s
**Original Artwork:**
<img src="http://a667.phobos.apple.com/us/r30/Purple3/v4/a4/2e/44/a42e44cd-2f25-6f3c-6998-db89b014d9e2/mzl.emsylakp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6769318/df027ce0-d096-11e4-87d8-11563d6b2cf4.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6768920/3499ef5c-d084-11e4-8c62-61ca72b72ec2.png)
https://cloud.githubusercontent.com/assets/10730122/6768920/3499ef5c-d084-11e4-8c62-61ca72b72ec2.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6768918/2c13b584-d084-11e4-99f2-02e50ea50f32.png

**Comment by dreamnet** [comment]
On second thought, I think doing this in the original size will be better:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6769318/df027ce0-d096-11e4-87d8-11563d6b2cf4.png)
https://cloud.githubusercontent.com/assets/2068130/6769318/df027ce0-d096-11e4-87d8-11563d6b2cf4.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6769322/ed0da1a2-d096-11e4-8d03-cf5021ba7c7d.png

**Comment by Trubbel** [comment]
Yeah, I wasn't really satisfied how it turned out but I tried to follow the guide lines. But that does look better for sure!

**Comment by dreamnet** [comment]
@Trubbel :+1: :wink:
