### ISSUE TITLE
Melodifestivalen

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5409]
**App Name:** Melodifestivalen
**Bundle ID:** se.svt.melodifestivalen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=947860957">947860957</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/melodifestivalen/id947860957?mt=8&uo=4">https://itunes.apple.com/se/app/melodifestivalen/id947860957?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Sveriges Television AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/developer/sveriges-television-ab/id343544217?uo=4>© Sveriges Television AB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/70/80/82/70808246-c9fa-d046-042b-97036b68c18e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13031244/c2f2d6e8-d2c6-11e5-8809-b7c3ef385be4.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6768949/8dd5c4d2-d085-11e4-8ac5-41f7c197c636.png)
https://cloud.githubusercontent.com/assets/10730122/6768949/8dd5c4d2-d085-11e4-8ac5-41f7c197c636.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6768946/81fb1414-d085-11e4-925a-b03a9b735453.png

**Comment by dreamnet** [comment]
@Trubbel Taking the alternate. :+1:

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13031244/c2f2d6e8-d2c6-11e5-8809-b7c3ef385be4.png)
https://cloud.githubusercontent.com/assets/10730122/13031244/c2f2d6e8-d2c6-11e5-8809-b7c3ef385be4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13031243/c2f0e1a8-d2c6-11e5-8cde-61b9795cb24f.png

**Comment by dreamnet** [comment]
@Trubbel Great! :+1:
