### ISSUE TITLE
Launcher with Notification Center Widget

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5410]
**App Name:** Launcher with Notification Center Widget
**Bundle ID:** com.cromulentlabs.Launcher
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905099592">905099592</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/launcher-notification-center/id905099592?mt=8&uo=4">https://itunes.apple.com/us/app/launcher-notification-center/id905099592?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Cromulent Labs, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/cromulent-labs/id769433054?uo=4>© Cromulent Labs</a>
**Supported Devices:** iPhone6, iPhone5s, iPad23G, iPhone5c, iPadThirdGen, iPad2Wifi, iPhone4S, iPhone5, iPadMini, iPadMini4G, iPodTouchFifthGen, iPadFourthGen4G, iPadFourthGen, iPadThirdGen4G, iPhone6Plus
**Original Artwork:**
<img src="http://a1494.phobos.apple.com/us/r30/Purple1/v4/92/71/4e/92714e68-dd40-05d6-3626-ed65c69b3f01/pr_source.png?downloadKey=1427037166_feff48341205116d6c7c272f49414aae" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/6769353/046ac1a8-d098-11e4-9684-9b5de04ab4b5.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6769305/5a4829aa-d096-11e4-8472-f390f6681df0.png)
https://cloud.githubusercontent.com/assets/10730122/6769305/5a4829aa-d096-11e4-8472-f390f6681df0.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6769302/50116bae-d096-11e4-8a94-cc99860936dd.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
