### ISSUE TITLE
SimCity BuildIt

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5411]
**App Name:** SimCity BuildIt
**Bundle ID:** com.ea.simcitymobile.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=913292932">913292932</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/simcity-buildit/id913292932?mt=8&uo=4">https://itunes.apple.com/us/app/simcity-buildit/id913292932?mt=8&uo=4</a>
**App Version:** 1.2.27
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/electronic-arts/id284800461?mt=8&uo=4>© Electronic Arts</a>
**Supported Devices:** iPhone5c, iPadFourthGen4G, iPad23G, iPhone5s, iPhone6Plus, iPhone4S, iPadFourthGen, iPhone5, iPhone6, iPhone4, iPadMini4G, iPadThirdGen, iPad2Wifi, iPadThirdGen4G, iPodTouchFifthGen, iPadMini
**Original Artwork:**
<img src="http://a526.phobos.apple.com/us/r30/Purple3/v4/eb/df/fe/ebdffe9a-4339-093f-8dd7-317e04b86834/mzl.omzlwmug.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6770792/d1bb82ce-d0a1-11e4-8e73-bc58b848f484.png)

**Comment by Trubbel** [comment]
I'm gonna leave this for someone else, I have tried and I have never been satisfied with the outcome.

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6770792/d1bb82ce-d0a1-11e4-8e73-bc58b848f484.png)
https://cloud.githubusercontent.com/assets/10950389/6770792/d1bb82ce-d0a1-11e4-8e73-bc58b848f484.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6770795/e153e17c-d0a1-11e4-93b1-8e2d6a93ec7b.png

**Comment by dreamnet** [comment]
@zmathiasz Jup, I take it. :+1:
