### ISSUE TITLE
Dwelp

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5412]
**App Name:** Dwelp
**Bundle ID:** com.roundabyte.dwelp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935201107">935201107</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dwelp/id935201107?mt=8&uo=4">https://itunes.apple.com/us/app/dwelp/id935201107?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Alex Blaj
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/alex-blaj/id919431329?uo=4>© Alex Blaj</a>
**Supported Devices:** iPhone6, iPad23G, iPhone5s, iPadMini, iPad2Wifi, iPadThirdGen, iPhone4S, iPhone5, iPhone5c, iPhone6Plus, iPodTouchFifthGen, iPadFourthGen, iPadMini4G, iPhone4, iPadFourthGen4G, iPadThirdGen4G
**Original Artwork:**
<img src="http://a86.phobos.apple.com/us/r30/Purple3/v4/84/1d/f2/841df20f-0748-50d2-48c0-7f70c0c7353e/mzl.xddioetf.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6787786/5c2a61f4-d16b-11e4-92ce-1f7c1261840a.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6787786/5c2a61f4-d16b-11e4-92ce-1f7c1261840a.png)
https://cloud.githubusercontent.com/assets/10950389/6787786/5c2a61f4-d16b-11e4-92ce-1f7c1261840a.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6787793/6e8d33e4-d16b-11e4-8b25-c7efd029ab63.png

**Comment by dreamnet** [comment]
@zmathiasz :+1:
