### ISSUE TITLE
Priime

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5414]
**App Name:** Priime
**Bundle ID:** com.priime.Priime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=934587545">934587545</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/priime/id934587545?mt=8&uo=4">https://itunes.apple.com/us/app/priime/id934587545?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Priime, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/priime-inc./id934587544?uo=4>© Priime, Inc.</a>
**Supported Devices:** iPhone4S, iPad23G, iPhone6Plus, iPadMini, iPhone5s, iPhone5, iPadFourthGen4G, iPadThirdGen4G, iPad2Wifi, iPadMini4G, iPhone6, iPadThirdGen, iPadFourthGen, iPhone5c, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a280.phobos.apple.com/us/r30/Purple3/v4/af/2e/64/af2e6427-5bb5-1ce2-7eca-74ca56fbdda7/pr_source.png?downloadKey=1427149422_b5d5e844a3cddf6ed79eb6aa49daa809" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6788648/5bd41960-d171-11e4-9c2e-5e4c471cfc17.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6788648/5bd41960-d171-11e4-9c2e-5e4c471cfc17.png)
https://cloud.githubusercontent.com/assets/10950389/6788648/5bd41960-d171-11e4-9c2e-5e4c471cfc17.png

**Comment by dreamnet** [comment]
@zmathiasz Jep! :+1:
