### ISSUE TITLE
PICSPLAY 2 - Photo Editor & Selfie Retouch

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5415]
**App Name:** PICSPLAY 2 - Photo Editor & Selfie Retouch
**Bundle ID:** com.jellybus.PicsPlay2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942064355">942064355</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/picsplay-2-photo-editor-selfie/id942064355?mt=8&uo=4">https://itunes.apple.com/us/app/picsplay-2-photo-editor-selfie/id942064355?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** JellyBus Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jellybus-inc./id421117479?uo=4>© JellyBus Inc.</a>
**Supported Devices:** iPodTouchFifthGen, iPad2Wifi, iPhone5, iPadThirdGen, iPhone5c, iPadMini4G, iPhone5s, iPadFourthGen4G, iPhone4, iPhone6Plus, iPhone6, iPadFourthGen, iPhone4S, iPadMini, iPad23G, iPadThirdGen4G
**Original Artwork:**
<img src="http://a1464.phobos.apple.com/us/r30/Purple5/v4/76/e8/39/76e83973-b9be-ae5f-a575-9045cfd481e4/pr_source.png?downloadKey=1427149842_5b36becbb2353cc94c8c21ef01254d6b" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6789436/a76b4736-d176-11e4-9fe0-31233d662983.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6789379/32074832-d176-11e4-834e-a168c459bd22.png)
https://cloud.githubusercontent.com/assets/10950389/6789379/32074832-d176-11e4-834e-a168c459bd22.png

**Comment by zmathiasz** [comment]
Alternate:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6789436/a76b4736-d176-11e4-9fe0-31233d662983.png)
https://cloud.githubusercontent.com/assets/10950389/6789436/a76b4736-d176-11e4-9fe0-31233d662983.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6789442/b39826be-d176-11e4-8b1a-8c8e1da5d7a8.png

**Comment by dreamnet** [comment]
@zmathiasz Hmmm... taking the alternate. :+1:

**Comment by zmathiasz** [comment]
@Dreamnet. I agree looks more like a camera / photo editor. :)
