### ISSUE TITLE
PaperKarma

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5416]
**App Name:** PaperKarma
**Bundle ID:** com.readabl.PaperKarma
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=458837823">458837823</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paperkarma/id458837823?mt=8&uo=4">https://itunes.apple.com/us/app/paperkarma/id458837823?mt=8&uo=4</a>
**App Version:** 1.6.4
**Seller:** REPUTATION.COM, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/reputation.com/id835333887?uo=4>© Reputation.com</a>
**Supported Devices:** iPadThirdGen4G, iPhone6Plus, iPad2Wifi, iPhone5, iPhone5s, iPadMini, iPhone5c, iPadFourthGen4G, iPadMini4G, iPadFourthGen, iPhone4, iPad23G, iPadThirdGen, iPhone6, iPodTouchFifthGen, iPhone4S
**Original Artwork:**
<img src="http://a920.phobos.apple.com/us/r30/Purple3/v4/8d/db/52/8ddb5238-9892-787e-546a-1c5c375d9930/mzl.lohcvkkk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6813869/a452628a-d24f-11e4-854b-2f8a6b1b2bed.png)

**Comment by WaterTrooper** [comment]
Thanks in advanced. This is a pretty kewl app if you get snail mail spam.

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6813869/a452628a-d24f-11e4-854b-2f8a6b1b2bed.png)
https://cloud.githubusercontent.com/assets/10950389/6813869/a452628a-d24f-11e4-854b-2f8a6b1b2bed.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6813877/b4cc6ac0-d24f-11e4-972e-22980fed2a3a.png
