### ISSUE TITLE
Tap Titans

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5419]
**App Name:** Tap Titans
**Bundle ID:** com.gamehivecorp.taptitans
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=940596201">940596201</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tap-titans/id940596201?mt=8&uo=4">https://itunes.apple.com/us/app/tap-titans/id940596201?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Game Hive Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/game-hive-corp./id443272129?uo=4>© Game Hive Corp.</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen, iPhone6, iPhone5, iPadMini4G, iPad23G, iPadWifi, iPodTouchFourthGen, iPodTouchThirdGen, iPadMini, iPad3G, iPhone6Plus, iPodTouchFifthGen, iPhone4, iPhone5c, iPhone4S, iPhone5s, iPhone-3GS, iPadFourthGen, iPadThirdGen4G, iPadFourthGen4G
**Original Artwork:**
<img src="http://a1647.phobos.apple.com/us/r30/Purple5/v4/28/06/f5/2806f5c4-4dc5-47c5-7c04-522915988867/mzl.acwmgxle.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16902845/edafb06c-4c6b-11e6-91e1-57d23873f19c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6878729/14f9123c-d4e3-11e4-977c-49f55fb1b6c8.png)
https://cloud.githubusercontent.com/assets/2068130/6878729/14f9123c-d4e3-11e4-977c-49f55fb1b6c8.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6878735/234d759e-d4e3-11e4-873c-ba383c632980.png

**Comment by zmathiasz** [comment]
That looks really good. I like that you kept the body form of the monster. :D

**Comment by Anuskuss** [comment]
@dreamnet Could you make his hair and his scarf solid, and remove those "thunderbolts"? Also I don't like the monsters head... (sorry for the amount of requests but I want it to look perfect :smiley: )

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16902845/edafb06c-4c6b-11e6-91e1-57d23873f19c.png)
https://cloud.githubusercontent.com/assets/2068130/16902845/edafb06c-4c6b-11e6-91e1-57d23873f19c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16902846/fd1b7248-4c6b-11e6-958f-8f0d0a9306f3.png

**Comment by Anuskuss** [comment]
Nice :heart_eyes:
