### ISSUE TITLE
Find A Grave

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5420]
**App Name:** Find A Grave
**Bundle ID:** com.ancestry.FindAGrave
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=732952190">732952190</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/find-a-grave/id732952190?mt=8&uo=4">https://itunes.apple.com/us/app/find-a-grave/id732952190?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Ancestry.com Operations Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ancestry.com/id349554266?uo=4>© Ancestry.com</a>
**Supported Devices:** iPhone6Plus, iPhone4S, iPhone5c, iPadThirdGen, iPadThirdGen4G, iPadFourthGen4G, iPhone6, iPhone4, iPhone5, iPhone5s, iPadMini4G, iPadMini, iPad2Wifi, iPodTouchFifthGen, iPadFourthGen, iPad23G
**Original Artwork:**
<img src="http://a1098.phobos.apple.com/us/r30/Purple/v4/ca/9f/90/ca9f909e-b1de-9042-a69a-a89b6eb490df/mzl.ocxkrvol.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6875692/25cf4fa8-d4c1-11e4-8651-2e533f78ea2c.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6839749/a2cf776e-d343-11e4-8d4c-d6f841bdbda6.png)
https://cloud.githubusercontent.com/assets/10950389/6839749/a2cf776e-d343-11e4-8d4c-d6f841bdbda6.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6839759/b9af4bf8-d343-11e4-96e5-f6e82ea8eba4.png

**Comment by ivanov007** [comment]
what about the inverse?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6871393/ce03a156-d467-11e4-80e9-70de708494b4.png)
https://cloud.githubusercontent.com/assets/3090247/6871393/ce03a156-d467-11e4-80e9-70de708494b4.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/6871394/ce041690-d467-11e4-9ddf-7c769becccdb.png

**Comment by zmathiasz** [comment]
Much better.  Looks great! :+1:

**Comment by dreamnet** [comment]
Did a litte cleanup:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6875692/25cf4fa8-d4c1-11e4-8651-2e533f78ea2c.png)
https://cloud.githubusercontent.com/assets/2068130/6875692/25cf4fa8-d4c1-11e4-8651-2e533f78ea2c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6875699/348e020a-d4c1-11e4-82b5-8d9db229f1ac.png
