### ISSUE TITLE
Sense: Know More. Sleep Better.

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#5426]
**App Name:** Sense: Know More. Sleep Better.
**Bundle ID:** is.hello.Sense
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942698761">942698761</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sense-know-more.-sleep-better./id942698761?mt=8&uo=4">https://itunes.apple.com/us/app/sense-know-more.-sleep-better./id942698761?mt=8&uo=4</a>
**App Version:** 1.0.3.7
**Seller:** Hello Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hello/id942698760?uo=4>© Hello</a>
**Supported Devices:** iPhone6, iPhone5, iPhone6Plus, iPadMini, iPadFourthGen4G, iPadMini4G, iPadThirdGen, iPhone4S, iPadThirdGen4G, iPadFourthGen, iPodTouchFifthGen, iPhone5s, iPhone5c
**Original Artwork:**
<img src="http://a245.phobos.apple.com/us/r30/Purple3/v4/71/e2/d5/71e2d58e-3aeb-c2b9-232f-99e3c491e3fa/mzl.cebkngsf.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6872976/5ffbe3e6-d483-11e4-9b6e-bf3e1660a42b.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6872976/5ffbe3e6-d483-11e4-9b6e-bf3e1660a42b.png)
https://cloud.githubusercontent.com/assets/10950389/6872976/5ffbe3e6-d483-11e4-9b6e-bf3e1660a42b.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6872988/70a21666-d483-11e4-810f-df9923a513f8.png

**Comment by dreamnet** [comment]
@zmathiasz :+1:
