### ISSUE TITLE
Lastronaut

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#5427]
**App Name:** Lastronaut
**Bundle ID:** com.darrinhenein.lastronaut
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=805839157">805839157</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lastronaut/id805839157?mt=8&uo=4">https://itunes.apple.com/us/app/lastronaut/id805839157?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Darrin Henein
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/darrin-henein/id805839160?uo=4>© Darrin Henein</a>
**Supported Devices:** iPhone6, iPadFourthGen, iPodTouchFifthGen, iPhone4S, iPadFourthGen4G, iPhone6Plus, iPad2Wifi, iPhone4, iPadThirdGen, iPad23G, iPadMini, iPhone5s, iPadThirdGen4G, iPhone5c, iPadMini4G, iPhone5
**Original Artwork:**
<img src="http://a1153.phobos.apple.com/us/r30/Purple3/v4/7b/1e/87/7b1e871c-b32e-ccc7-fe5f-bf542afb63c9/mzl.obxuauxm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7074708/d42a97e8-defc-11e4-9c9c-c4375c5b8dc4.png)

**Comment by dreamnet** [comment]
Hmmm...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6878300/1ff64710-d4dc-11e4-94c3-784a96c0a97d.png)
https://cloud.githubusercontent.com/assets/2068130/6878300/1ff64710-d4dc-11e4-94c3-784a96c0a97d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6878306/31939cb6-d4dc-11e4-977f-4d1d8805925c.png

**Comment by zmathiasz** [comment]
That's a great idea for 8-bit icons!  I like it.

**Comment by MagnaMike** [comment]
@dreamnet Try making the black outline connected like the trim around his face?

**Comment by dreamnet** [comment]
Hmmm....
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7074708/d42a97e8-defc-11e4-9c9c-c4375c5b8dc4.png)
https://cloud.githubusercontent.com/assets/2068130/7074708/d42a97e8-defc-11e4-9c9c-c4375c5b8dc4.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7074716/e2ce5fd2-defc-11e4-829a-911e58e74e51.png

**Comment by MagnaMike** [comment]
@dreamnet Tough icon. I don't know, up to you.

**Comment by MagnaMike** [comment]
@dreamnet :question:

**Comment by dreamnet** [comment]
@MagnaMike Yeah, I'm not really happy with it, but I'm taking my last one.
