### ISSUE TITLE
Duet Game

### ISSUE THREAD

**Issue by neeldaver** [glasklart/hd#5428]
**App Name:** Duet Game
**Bundle ID:** com.kumobius.duet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=634235735">634235735</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/duet-game/id634235735?mt=8&uo=4">https://itunes.apple.com/us/app/duet-game/id634235735?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Kumobius Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kumobius/id449069247?uo=4>© Kumobius</a>
**Supported Devices:** iPad3G, iPhone4S, iPad23G, iPodTouchFifthGen, iPadWifi, iPodTouchFourthGen, iPhone6, iPhone-3GS, iPadThirdGen, iPhone5s, iPadFourthGen4G, iPodTouchThirdGen, iPhone5c, iPhone5, iPadThirdGen4G, iPhone4, iPadMini4G, iPadMini, iPhone6Plus, iPad2Wifi, iPadFourthGen
**Original Artwork:**
<img src="http://a1070.phobos.apple.com/us/r30/Purple1/v4/fb/24/e1/fb24e1af-2df6-9173-d5b4-ed5d5808bf94/pr_source.png?downloadKey=1427483887_8c3cef6c64be403df02d1726b8350504" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6877218/404b1048-d4cf-11e4-88de-26e62fbbbc26.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6873185/fb8ba674-d484-11e4-96ac-980f9229b23f.png)
https://cloud.githubusercontent.com/assets/10950389/6873185/fb8ba674-d484-11e4-96ac-980f9229b23f.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6873190/090e8f82-d485-11e4-9a5c-0bcb1218b300.png

**Comment by zmathiasz** [comment]
Alternate:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6873240/56962cb0-d485-11e4-8c68-ef285b686e7c.png)
https://cloud.githubusercontent.com/assets/10950389/6873240/56962cb0-d485-11e4-8c68-ef285b686e7c.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6873252/636af6a0-d485-11e4-8243-15b384357d61.png

**Comment by dreamnet** [comment]
@zmathiasz Great, I like the first one and mad it litte cleaner:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6877218/404b1048-d4cf-11e4-88de-26e62fbbbc26.png)
https://cloud.githubusercontent.com/assets/2068130/6877218/404b1048-d4cf-11e4-88de-26e62fbbbc26.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6877225/55f21cde-d4cf-11e4-9484-1f60a47313a8.png
