### ISSUE TITLE
Bao Moi - Doc bao mien phi

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5435]
**App Name:** Báo Mới - Đọc báo miễn phí
**Bundle ID:** com.jusoft.newibao
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=685277645">685277645</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bao-moi-oc-bao-mien-phi/id685277645?mt=8&uo=4">https://itunes.apple.com/us/app/bao-moi-oc-bao-mien-phi/id685277645?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** thuc hoang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jusoft/id438407231?uo=4>© Jusoft</a>
**Supported Devices:** iPadFourthGen, iPadThirdGen4G, iPodTouchFifthGen, iPadThirdGen, iPhone5s, iPad23G, iPhone6, iPhone6Plus, iPodTouchFourthGen, iPad2Wifi, iPadFourthGen4G, iPadMini4G, iPhone5, iPhone4S, iPadMini, iPhone-3GS, iPhone4, iPhone5c
**Original Artwork:**
<img src="http://a1818.phobos.apple.com/us/r30/Purple6/v4/29/f3/e4/29f3e424-b56d-4727-5680-16429a947834/mzl.ftiwiuom.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6885083/c6c16d42-d610-11e4-9105-7a07b6db0d06.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6885083/c6c16d42-d610-11e4-9105-7a07b6db0d06.png)
https://cloud.githubusercontent.com/assets/2068130/6885083/c6c16d42-d610-11e4-9105-7a07b6db0d06.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6885084/d529c406-d610-11e4-9629-5bf63bb5d272.png

**Comment by Trubbel** [comment]
@dreamnet Looks really good, well done!

**Comment by dreamnet** [comment]
@Trubbel THX! :wink:
