### ISSUE TITLE
EuropaFM Radio

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5437]
**App Name:** EuropaFM Radio
**Bundle ID:** com.antena3.EuropaFM
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=331213753">331213753</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/es/app/europafm-radio/id331213753?uo=4">https://apps.apple.com/es/app/europafm-radio/id331213753?uo=4</a>
**App Version:** 3.0.7
**Seller:** Atresmedia Corporacion de Medios de Comunicacion S.A.
**Developer:** <a target="_blank" href="https://apps.apple.com/es/developer/atresmedia-corporacion-de-medios-de-comunicacion-s-a/id331213756?uo=4">© Atresmedia Corporacion de Medios de Comunicacion S.A.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple127/v4/1b/b1/1d/1bb11d8e-6d2e-4a7d-1d60-91abe0d4aa89/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387955-e21a4100-9aaa-11e9-8670-811660cb36ae.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6884697/37cf706e-d5fe-11e4-87fe-1e914988820a.png)
https://cloud.githubusercontent.com/assets/2068130/6884697/37cf706e-d5fe-11e4-87fe-1e914988820a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6884700/45aeee3a-d5fe-11e4-9d9c-255c5222c1c6.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60387955-e21a4100-9aaa-11e9-8670-811660cb36ae.png)
https://user-images.githubusercontent.com/20930745/60387955-e21a4100-9aaa-11e9-8670-811660cb36ae.png

Source:
https://user-images.githubusercontent.com/20930745/60387957-e3e40480-9aaa-11e9-9e6e-86cd746e51c4.png
