### ISSUE TITLE
Nothelfer

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5439]
**App Name:** Nothelfer
**Bundle ID:** de.adac.Nothelfer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424718854">424718854</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/nothelfer/id424718854?mt=8&uo=4">https://itunes.apple.com/de/app/nothelfer/id424718854?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** ADAC e.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/adac-e.v./id352737584?uo=4>© ADAC e.V.</a>
**Supported Devices:** iPhone4S, iPhone6Plus, iPhone4, iPhone-3GS, iPhone5c, iPhone6, iPhone5s, iPhone5
**Original Artwork:**
<img src="http://a600.phobos.apple.com/us/r30/Purple3/v4/c2/97/82/c2978254-451e-df6b-947a-298a4f8a88ba/mzl.ripozgsn.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6952246/941238d8-d88e-11e4-8ec1-474e1cadfdf9.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6952246/941238d8-d88e-11e4-8ec1-474e1cadfdf9.png)
https://cloud.githubusercontent.com/assets/10950389/6952246/941238d8-d88e-11e4-8ec1-474e1cadfdf9.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6952259/a4996b22-d88e-11e4-8efb-fb4e48431cec.png

**Comment by dreamnet** [comment]
@zmathiasz :+1:
