### ISSUE TITLE
Angry Birds Star Wars

### ISSUE THREAD

**Issue by 26psicivic** [glasklart/hd#544]
**App Name:** Angry Birds Star Wars
**Bundle ID:** com.rovio.angrybirdsstarwars
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=557137623">557137623</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds-star-wars/id557137623?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds-star-wars/id557137623?mt=8&uo=4</a>
**App Version:** 1.5.3
**Seller:** Rovio Entertainment Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rovio-entertainment-ltd/id298910979?uo=4>© Rovio Entertainment Ltd</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/f9/83/31/f98331c5-66a9-24c4-76f3-a01dd354a0e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19002189/20024e7a-874b-11e6-84fe-6f4a5a83788e.png)

**Comment by LaCh0uine** [comment]
don't work on 5.1 need update 
thank you

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19002189/20024e7a-874b-11e6-84fe-6f4a5a83788e.png)
https://cloud.githubusercontent.com/assets/20930745/19002189/20024e7a-874b-11e6-84fe-6f4a5a83788e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19002229/4c473ca2-874b-11e6-8735-53738253703a.png
