### ISSUE TITLE
Off Remote

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5441]
**App Name:** Off Remote
**Bundle ID:** com.HobbyistSoftware.Off
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=312383903">312383903</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/off-remote/id312383903?mt=8&uo=4">https://itunes.apple.com/us/app/off-remote/id312383903?mt=8&uo=4</a>
**App Version:** 3.73
**Seller:** Hobbyist Software Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hobbyist-software-limited/id291218199?uo=4>© Hobbyist Software Limited</a>
**Supported Devices:** iPhone4S, iPhone5s, iPadFourthGen4G, iPad2Wifi, iPadFourthGen, iPhone5, iPad23G, iPadMini4G, iPadThirdGen4G, iPhone-3GS, iPhone6, iPhone6Plus, iPhone5c, iPodTouchFourthGen, iPadThirdGen, iPadMini, iPhone4, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a1170.phobos.apple.com/us/r30/Purple4/v4/74/7b/b8/747bb8af-1069-c0d4-7bfd-51027b5fdfe1/mzl.coxziztx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6886255/99fa9a9c-d636-11e4-92a8-2ac9cdd9187f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6886255/99fa9a9c-d636-11e4-92a8-2ac9cdd9187f.png)
https://cloud.githubusercontent.com/assets/2068130/6886255/99fa9a9c-d636-11e4-92a8-2ac9cdd9187f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6886260/ac0c23f4-d636-11e4-8b2a-6ad11312782a.png
