### ISSUE TITLE
MLG.tv

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5442]
**App Name:** MLG.tv
**Bundle ID:** tv.mlg.player
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=840363884">840363884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mlg.tv/id840363884?mt=8&uo=4">https://itunes.apple.com/us/app/mlg.tv/id840363884?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Major League Gaming, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/major-league-gaming-inc./id840363887?uo=4>© Major League Gaming Inc.</a>
**Supported Devices:** iPadFourthGen4G, iPhone6, iPhone5s, iPadMini, iPhone4S, iPodTouchFifthGen, iPhone4, iPhone5, iPadMini4G, iPhone5c, iPad2Wifi, iPadThirdGen, iPhone6Plus, iPadFourthGen, iPadThirdGen4G, iPad23G
**Original Artwork:**
<img src="http://a307.phobos.apple.com/us/r30/Purple5/v4/75/59/35/75593584-01ef-4b0d-17c9-b66632855548/mzl.qpruwwrz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6886086/cd5ddcf4-d632-11e4-935f-0384c4f36770.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6886086/cd5ddcf4-d632-11e4-935f-0384c4f36770.png)
https://cloud.githubusercontent.com/assets/2068130/6886086/cd5ddcf4-d632-11e4-935f-0384c4f36770.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6886091/dc950292-d632-11e4-91ff-db707b7f8618.png
