### ISSUE TITLE
Google AdSense

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5443]
**App Name:** Google AdSense
**Bundle ID:** com.google.PublisherApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=680739529">680739529</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-adsense/id680739529?mt=8&uo=4">https://itunes.apple.com/us/app/google-adsense/id680739529?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/44/75/25/447525f7-0ebb-7a6e-30f7-b3875f419f8a/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10273462/2abb41aa-6b31-11e5-80df-1c3adaf46fd9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6907891/78ad77ba-d73a-11e4-857e-914f8ff3dc71.png)
https://cloud.githubusercontent.com/assets/2068130/6907891/78ad77ba-d73a-11e4-857e-914f8ff3dc71.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6907912/87936726-d73a-11e4-93c9-13e484dc2a25.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10273462/2abb41aa-6b31-11e5-80df-1c3adaf46fd9.png)
https://cloud.githubusercontent.com/assets/2068130/10273462/2abb41aa-6b31-11e5-80df-1c3adaf46fd9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10273468/38e575b6-6b31-11e5-8866-b46e0d9c91f6.png
