### ISSUE TITLE
Smoopa Shopping: Never Overpay Again

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5444]
**App Name:** Smoopa Shopping: Never Overpay Again
**Bundle ID:** com.smoopa.Smoopa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=517306231">517306231</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smoopa-shopping-never-overpay/id517306231?mt=8&uo=4">https://itunes.apple.com/us/app/smoopa-shopping-never-overpay/id517306231?mt=8&uo=4</a>
**App Version:** 3.84
**Seller:** Smoopa
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/smoopa/id517306234?uo=4>© Smoopa</a>
**Supported Devices:** iPadMini4G, iPhone4, iPodTouchFifthGen, iPadFourthGen, iPhone5c, iPhone6Plus, iPadThirdGen, iPhone5, iPad23G, iPadThirdGen4G, iPadMini, iPhone6, iPadFourthGen4G, iPad2Wifi, iPhone4S, iPhone5s
**Original Artwork:**
<img src="http://a1146.phobos.apple.com/us/r30/Purple5/v4/54/4c/c5/544cc583-dcb4-1465-a90c-c58b38a5795a/mzl.fgzlwgae.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6928909/7c432024-d7f7-11e4-9fb6-453be6d1912e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6928909/7c432024-d7f7-11e4-9fb6-453be6d1912e.png)
https://cloud.githubusercontent.com/assets/2068130/6928909/7c432024-d7f7-11e4-9fb6-453be6d1912e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6928925/8e482d8c-d7f7-11e4-8adf-5b8f4bb4b4da.png
