### ISSUE TITLE
Yahoo News Digest

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5445]
**App Name:** Yahoo News Digest
**Bundle ID:** com.yahoo.atom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=784982356">784982356</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahoo-news-digest/id784982356?mt=8&uo=4">https://itunes.apple.com/us/app/yahoo-news-digest/id784982356?mt=8&uo=4</a>
**App Version:** 1.6.1
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/yahoo/id281970157?mt=8&uo=4>© Yahoo</a>
**Supported Devices:** iPhone4S, iPhone5, iPadMini, iPadFourthGen, iPadMini4G, iPhone5c, iPad2Wifi, iPadFourthGen4G, iPhone4, iPadThirdGen4G, iPhone6Plus, iPadThirdGen, iPhone6, iPodTouchFifthGen, iPhone5s, iPad23G
**Original Artwork:**
<img src="http://a407.phobos.apple.com/us/r30/Purple5/v4/81/86/a3/8186a363-90c1-97f8-e7c5-9cbfd92eac29/mzl.mxfnyydb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6943865/eb8487a6-d84d-11e4-810a-9a6d311ed2c7.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6943865/eb8487a6-d84d-11e4-810a-9a6d311ed2c7.png)
https://cloud.githubusercontent.com/assets/3090247/6943865/eb8487a6-d84d-11e4-810a-9a6d311ed2c7.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/6943934/4eb28d82-d84e-11e4-8b48-a0102ee24671.png

**Comment by dreamnet** [comment]
@ivanov007 Jup! :+1:
