### ISSUE TITLE
GoodNotes 4 - Notes & PDF

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5446]
**App Name:** GoodNotes 4 - Notes & PDF
**Bundle ID:** com.goodnotesapp.goodnotes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=778658393">778658393</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/goodnotes-4-notes-pdf/id778658393?mt=8&uo=4">https://itunes.apple.com/us/app/goodnotes-4-notes-pdf/id778658393?mt=8&uo=4</a>
**App Version:** 4.5.2
**Seller:** Time Base Technology Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/time-base-technology-limited/id424587624?uo=4>© Time Base Technology Limited</a>
**Supported Devices:** iPhone6Plus, iPadMini, iPhone5c, iPadThirdGen, iPhone5, iPodTouchFifthGen, iPhone4S, iPhone5s, iPad23G, iPadFourthGen4G, iPhone6, iPhone4, iPad2Wifi, iPadFourthGen, iPadThirdGen4G, iPadMini4G
**Original Artwork:**
<img src="http://a1876.phobos.apple.com/us/r30/Purple3/v4/00/1f/85/001f854f-bcb3-8de8-99d6-ae8d427b2201/mzl.kgprjtqk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6944267/2f37cfec-d850-11e4-9906-f89c93095d1d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6944267/2f37cfec-d850-11e4-9906-f89c93095d1d.png)
https://cloud.githubusercontent.com/assets/3090247/6944267/2f37cfec-d850-11e4-9906-f89c93095d1d.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/6944268/2f3cdf5a-d850-11e4-8586-3208ef5a0cbb.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
