### ISSUE TITLE
Misfit

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5447]
**App Name:** Misfit
**Bundle ID:** com.misfitwearables.Prometheus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=564157241">564157241</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/misfit/id564157241?mt=8&uo=4">https://itunes.apple.com/us/app/misfit/id564157241?mt=8&uo=4</a>
**App Version:** 1.24.0
**Seller:** MISFIT WEARABLES CORPORATION
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/misfit-wearables-corporation/id525202369?uo=4>© MISFIT WEARABLES CORPORATION</a>
**Supported Devices:** iPhone6, iPadFourthGen, iPadThirdGen4G, iPodTouchFifthGen, iPhone6Plus, iPadFourthGen4G, iPhone4S, iPhone5, iPadMini, iPhone4, iPadThirdGen, iPad2Wifi, iPad23G, iPadMini4G, iPhone5s, iPhone5c
**Original Artwork:**
<img src="http://a1583.phobos.apple.com/us/r30/Purple1/v4/5e/a2/13/5ea21359-23a8-9f84-bcaf-54dbfdb2dca4/mzl.uyfuhwic.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6944347/97232e6c-d850-11e4-94cf-c916b0eb7bbc.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6944347/97232e6c-d850-11e4-94cf-c916b0eb7bbc.png)
https://cloud.githubusercontent.com/assets/3090247/6944347/97232e6c-d850-11e4-94cf-c916b0eb7bbc.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/6944348
/97247e84-d850-11e4-832b-beb54fa60858.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
