### ISSUE TITLE
iTunes Movie Trailers

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5448]
**App Name:** iTunes Movie Trailers
**Bundle ID:** com.apple.movietrailers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=471966214">471966214</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/itunes-movie-trailers/id471966214?mt=8&uo=4">https://itunes.apple.com/us/app/itunes-movie-trailers/id471966214?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/apple/id284417353?mt=12&uo=4>© Apple</a>
**Supported Devices:** iPhone5s, iPhone5, iPhone6Plus, iPad23G, iPadMini4G, iPhone4, iPhone5c, iPhone4S, iPodTouchFifthGen, iPad2Wifi, iPhone6, iPadMini, iPadFourthGen, iPadFourthGen4G, iPadThirdGen, iPadThirdGen4G
**Original Artwork:**
<img src="http://a546.phobos.apple.com/us/r30/Purple4/v4/bf/fe/e1/bffee103-f2bf-411c-fa37-a8810193449e/mzl.hlrtqutp.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6944953/af0d3970-d853-11e4-920b-7a3216d2fd59.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6944952/af09b4d0-d853-11e4-90fd-f2d6a48d3fd2.png)
https://cloud.githubusercontent.com/assets/3090247/6944952/af09b4d0-d853-11e4-90fd-f2d6a48d3fd2.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/6944953/af0d3970-d853-11e4-920b-7a3216d2fd59.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
