### ISSUE TITLE
Star Walk™ 2 - Guide to the Sky Day and Night

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5449]
**App Name:** Star Walk™ 2 - Guide to the Sky Day and Night
**Bundle ID:** com.vitotechnology.StarWalk2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=892279069">892279069</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/star-walk-2-guide-to-sky-day/id892279069?mt=8&uo=4">https://itunes.apple.com/us/app/star-walk-2-guide-to-sky-day/id892279069?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Vito Technology Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/vito-technology-inc./id289641503?uo=4>© Vito Technology Inc.</a>
**Supported Devices:** iPhone5s, iPhone6Plus, iPhone5, iPadMini4G, iPhone6, iPadMini, iPadFourthGen, iPadFourthGen4G, iPodTouchFifthGen, iPad2Wifi, iPad23G, iPadThirdGen4G, iPadThirdGen, iPhone5c, iPhone4S, iPhone4
**Original Artwork:**
<img src="http://a1535.phobos.apple.com/us/r30/Purple5/v4/3f/ec/ea/3fecea50-d092-81b6-0e89-723d2b089908/pr_source.png?downloadKey=1427841173_78a0c52fe19d2feedfb0dd774f4e90b0" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6928218/f5e12476-d7f2-11e4-9a89-32d0a96d62bf.png)

**Comment by ethansinjin** [comment]
The icon for Star Walk 1 can be used for this app.
http://glasklarthd.dreamnet.at/index.php?id=2352
com.vitotechnology.StarWalk
com.vitotechnology.StarWalk@2x.png

**Comment by dreamnet** [comment]
Same icon as for #5452.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6928218/f5e12476-d7f2-11e4-9a89-32d0a96d62bf.png)
https://cloud.githubusercontent.com/assets/2068130/6928218/f5e12476-d7f2-11e4-9a89-32d0a96d62bf.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6928224/0583d478-d7f3-11e4-9e6b-e8999adab778.png
