### ISSUE TITLE
Parallels Access

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5450]
**App Name:** Parallels Access
**Bundle ID:** com.parallels.access
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=655527928">655527928</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parallels-access/id655527928?mt=8&uo=4">https://itunes.apple.com/us/app/parallels-access/id655527928?mt=8&uo=4</a>
**App Version:** 2.5.2
**Seller:** Parallels, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/parallels-inc./id295531453?uo=4>© Parallels, Inc.</a>
**Supported Devices:** iPhone5s, iPhone4S, iPadThirdGen4G, iPad2Wifi, iPodTouchFifthGen, iPadThirdGen, iPadMini, iPadFourthGen, iPadFourthGen4G, iPhone5, iPad23G, iPhone5c, iPhone4, iPhone6Plus, iPhone6, iPadMini4G
**Original Artwork:**
<img src="http://a496.phobos.apple.com/us/r30/Purple1/v4/a3/f9/b7/a3f9b70c-7e98-f9e5-922c-d3cd0f70289b/mzl.vhczrqbl.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6946704/74543d86-d85f-11e4-8b3e-7ca574c9f2d0.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6946702/74444610-d85f-11e4-9f31-5fc9f75ccf75.png)
https://cloud.githubusercontent.com/assets/3090247/6946702/74444610-d85f-11e4-9f31-5fc9f75ccf75.png
or just the cloud
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/6946704/74543d86-d85f-11e4-8b3e-7ca574c9f2d0.png)
https://cloud.githubusercontent.com/assets/3090247/6946704/74543d86-d85f-11e4-8b3e-7ca574c9f2d0.png

---
Sources:
https://cloud.githubusercontent.com/assets/3090247/6946703/7445aaa0-d85f-11e4-8f9a-ec265ec833e5.png
https://cloud.githubusercontent.com/assets/3090247/6946706/761b6ad6-d85f-11e4-9c4b-7306aefaa7f0.png

**Comment by dreamnet** [comment]
@ivanov007 Hm, I'm taking the second one. :+1:
