### ISSUE TITLE
Coca-Cola Freestyle

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5451]
**App Name:** Coca-Cola Freestyle
**Bundle ID:** com.coke.freestyle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=412549442">412549442</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/coca-cola-freestyle/id412549442?mt=8&uo=4">https://itunes.apple.com/us/app/coca-cola-freestyle/id412549442?mt=8&uo=4</a>
**App Version:** 5.1.3
**Seller:** The Coca-Cola Company
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/coca-cola/id320424095?uo=4>© Coca-Cola</a>
**Supported Devices:** iPhone6Plus, iPhone4, iPadThirdGen, iPadMini4G, iPhone4S, iPadMini, iPadFourthGen, iPhone5s, iPodTouchFifthGen, iPhone5, iPadThirdGen4G, iPadFourthGen4G, iPad23G, iPad2Wifi, iPhone5c, iPhone6
**Original Artwork:**
<img src="http://a261.phobos.apple.com/us/r30/Purple5/v4/cf/44/f4/cf44f46b-7565-ab82-c4be-97aeaf7a9b46/mzl.gyssiyjj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6928428/47111c2e-d7f4-11e4-9cb2-c6074e2b4e9f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6928428/47111c2e-d7f4-11e4-9cb2-c6074e2b4e9f.png)
https://cloud.githubusercontent.com/assets/2068130/6928428/47111c2e-d7f4-11e4-9cb2-c6074e2b4e9f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6928440/57492672-d7f4-11e4-9241-7fbc3c0e0fe2.png
