### ISSUE TITLE
Wallapop

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5453]
**App Name:** Wallapop
**Bundle ID:** com.secondhanding.WallaPop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=692753615">692753615</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wallapop/id692753615?mt=8&uo=4">https://itunes.apple.com/us/app/wallapop/id692753615?mt=8&uo=4</a>
**App Version:** 1.8.0
**Seller:** SECONDHANDING NETWORKS SL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/secondhanding-networks-sl/id692753618?uo=4>© SECONDHANDING NETWORKS SL</a>
**Supported Devices:** iPhone5, iPodTouchFifthGen, iPadMini4G, iPhone6, iPhone5c, iPhone5s, iPhone4, iPad2Wifi, iPadThirdGen, iPhone6Plus, iPadMini, iPad23G, iPadFourthGen4G, iPhone4S, iPadThirdGen4G, iPadFourthGen
**Original Artwork:**
<img src="http://a506.phobos.apple.com/us/r30/Purple3/v4/78/28/97/78289765-d015-d144-ac60-bf5d242b7cda/mzl.pfutashb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6952337/39a5e312-d88f-11e4-81fc-f65a43bef2b5.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6952337/39a5e312-d88f-11e4-81fc-f65a43bef2b5.png)
https://cloud.githubusercontent.com/assets/10950389/6952337/39a5e312-d88f-11e4-81fc-f65a43bef2b5.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6952346/46798b5c-d88f-11e4-8c64-6c209a635c00.png

**Comment by ivanov007** [comment]
@zmathiasz :+1:
