### ISSUE TITLE
Pandora Downloader

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5454]
**App Name:** Pandora Downloader
 **Bundle ID:** com.harrisonapps.Pandora-Downloader
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/10950389/6976776/88f7a7d2-d97c-11e4-8fbe-fe5b08cdf422.png" width="150" height="150" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6976811/196b56b0-d97d-11e4-8502-160255847266.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6976811/196b56b0-d97d-11e4-8502-160255847266.png)
https://cloud.githubusercontent.com/assets/10950389/6976811/196b56b0-d97d-11e4-8502-160255847266.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6976815/300043fe-d97d-11e4-9919-6626cff6d254.png

**Comment by dreamnet** [comment]
@zmathiasz :+1:
