### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5455]
**App Name:** Netflix
**Bundle ID:** com.netflix.Netflix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=363590051">363590051</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/netflix/id363590051?mt=8&uo=4">https://itunes.apple.com/us/app/netflix/id363590051?mt=8&uo=4</a>
**App Version:** 8.8.0
**Seller:** Netflix, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/netflix-inc./id363590054?uo=4>© Netflix, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/4e/37/1a/4e371abf-feaf-122a-ccc9-a9d00d9db1a7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16494402/7b896bf2-3ee9-11e6-9ee5-7cb7afec35e9.png)

**Comment by zmathiasz** [comment]
@dreamnet There is an existing icon for this app, I just didn't see an issue on github to post too.

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6976860/79563db4-d97e-11e4-8206-9b2b34aeb226.png)
https://cloud.githubusercontent.com/assets/10950389/6976860/79563db4-d97e-11e4-8206-9b2b34aeb226.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6976866/8dcc376c-d97e-11e4-9b4d-940b735e238a.png

**Comment by dreamnet** [comment]
@zmathiasz Yes, good. :+1:

**Comment by boxermansr** [comment]
Any chance of an update to this, for the new icon released June 28, 2016. Thanks. (If not, no biggie, as folks may like the original/older one, just figured I'd ask) :)

**Comment by Anuskuss** [comment]
I like the old one more but I think it's better to be up to date.

**Comment by boxermansr** [comment]
Whatever people prefer. I'm sure they'll change it to something else next week, and it'll need updated again, lol.

**Comment by dreamnet** [comment]
I also think that the new icon is worth an update.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16494402/7b896bf2-3ee9-11e6-9ee5-7cb7afec35e9.png)
https://cloud.githubusercontent.com/assets/10730122/16494402/7b896bf2-3ee9-11e6-9ee5-7cb7afec35e9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16494403/7ba761de-3ee9-11e6-84f5-2e92cbc4e66a.png
