### ISSUE TITLE
Periscope

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5456]
**App Name:** Periscope
**Bundle ID:** com.bountylabs.periscope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=972909677">972909677</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/periscope/id972909677?mt=8&uo=4">https://itunes.apple.com/us/app/periscope/id972909677?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Twitter, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/twitter-inc./id296415947?uo=4>© Twitter, Inc.</a>
**Supported Devices:** iPhone5s, iPadThirdGen4G, iPadMini4G, iPodTouchFifthGen, iPadThirdGen, iPad2Wifi, iPad23G, iPhone4S, iPhone4, iPadMini, iPhone6, iPhone5, iPadFourthGen, iPhone5c, iPadFourthGen4G, iPhone6Plus
**Original Artwork:**
<img src="http://a1571.phobos.apple.com/us/r30/Purple3/v4/2a/4d/27/2a4d27bc-4f7a-4eee-58ea-e32c17174a9d/mzl.rmjignst.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6987175/d1cb64d0-da44-11e4-9c60-9ab04ae3da32.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6985473/d034dd9c-da01-11e4-9df1-07511d8253d6.png)
https://cloud.githubusercontent.com/assets/10950389/6985473/d034dd9c-da01-11e4-9df1-07511d8253d6.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6985475/d9447ca8-da01-11e4-95bb-7e0a9060330b.png

**Comment by dreamnet** [comment]
Mh, I think this is better in original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6987175/d1cb64d0-da44-11e4-9c60-9ab04ae3da32.png)
https://cloud.githubusercontent.com/assets/2068130/6987175/d1cb64d0-da44-11e4-9c60-9ab04ae3da32.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6987186/ec0343f4-da44-11e4-8f42-b791e49a0dcf.png

**Comment by zmathiasz** [comment]
Works for me. :)
