### ISSUE TITLE
Galileo Offline Maps Pro - OSM based project for hikers & bikers traveling the wilderness

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5457]
**App Name:** Galileo Offline Maps Pro - OSM based project for hikers & bikers traveling the wilderness
**Bundle ID:** com.bodunov.GalileoPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=891362701">891362701</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/galileo-offline-maps-pro-osm/id891362701?mt=8&uo=4">https://itunes.apple.com/us/app/galileo-offline-maps-pro-osm/id891362701?mt=8&uo=4</a>
**App Version:** 3.2.10
**Seller:** Evgen Bodunov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/evgen-bodunov/id321745477?uo=4>© Evgen Bodunov</a>
**Supported Devices:** iPadFourthGen4G, iPhone4S, iPhone6, iPadThirdGen, iPad2Wifi, iPodTouchFourthGen, iPhone4, iPodTouchThirdGen, iPadMini, iPhone5, iPhone5c, iPhone5s, iPodTouchFifthGen, iPadFourthGen, iPhone6Plus, iPadWifi, iPhone-3GS, iPadThirdGen4G, iPad23G, iPadMini4G, iPad3G
**Original Artwork:**
<img src="http://a911.phobos.apple.com/us/r30/Purple1/v4/b2/06/d2/b206d214-e2fa-9da8-78e5-fb0c0cf87798/mzl.hequrwob.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6987283/0c1f78e6-da46-11e4-8ab1-9166971697b6.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6985544/aed4d1f6-da02-11e4-8d98-7ed3ef7bdc67.png)
https://cloud.githubusercontent.com/assets/10950389/6985544/aed4d1f6-da02-11e4-8d98-7ed3ef7bdc67.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6985546/b8938ec6-da02-11e4-931b-5617c06c4a6a.png

**Comment by dreamnet** [comment]
Did some small corrections:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6987283/0c1f78e6-da46-11e4-8ab1-9166971697b6.png)
https://cloud.githubusercontent.com/assets/2068130/6987283/0c1f78e6-da46-11e4-8ab1-9166971697b6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6987291/1bda0b84-da46-11e4-988a-a9107536a2f4.png
