### ISSUE TITLE
Prompt 2

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5458]
**App Name:** Prompt 2
**Bundle ID:** com.panic.Prompt2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=917437289">917437289</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/prompt-2/id917437289?mt=8&uo=4">https://itunes.apple.com/us/app/prompt-2/id917437289?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Panic, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/panic-inc./id403388568?uo=4>© Panic, Inc.</a>
**Supported Devices:** iPhone4S, iPadMini4G, iPadFourthGen4G, iPhone6, iPad2Wifi, iPhone6Plus, iPhone4, iPadThirdGen, iPadMini, iPhone5c, iPadThirdGen4G, iPhone5s, iPad23G, iPadFourthGen, iPodTouchFifthGen, iPhone5
**Original Artwork:**
<img src="http://a1367.phobos.apple.com/us/r30/Purple3/v4/a3/cb/ad/a3cbadf2-64fa-2ff3-e40d-672b6be084fa/mzl.ebkfojcr.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6985623/544942fc-da03-11e4-803b-2f83a36255fb.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6985623/544942fc-da03-11e4-803b-2f83a36255fb.png)
https://cloud.githubusercontent.com/assets/10950389/6985623/544942fc-da03-11e4-803b-2f83a36255fb.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6985627/5de227e8-da03-11e4-9c7f-544a41e1b3d5.png
