### ISSUE TITLE
Star Rover - Stargazing and Night Sky Watching

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5459]
**App Name:** Star Rover - Stargazing and Night Sky Watching
**Bundle ID:** net.eefan.star
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386628906">386628906</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/star-rover-stargazing-night/id386628906?mt=8&uo=4">https://itunes.apple.com/us/app/star-rover-stargazing-night/id386628906?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** Hanfei Yi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/eefan-inc./id326163982?uo=4>© EEFan Inc.</a>
**Supported Devices:** iPhone5, iPhone6, iPadFourthGen, iPhone6Plus, iPhone4, iPadMini4G, iPhone5c, iPhone-3GS, iPadFourthGen4G, iPhone4S, iPadMini, iPodTouchFifthGen, iPad2Wifi, iPad23G, iPadThirdGen, iPodTouchFourthGen, iPhone5s, iPadThirdGen4G
**Original Artwork:**
<img src="http://a547.phobos.apple.com/us/r30/Purple3/v4/b1/87/a6/b187a6cf-cebd-b8a1-e922-22650e67b4c3/mzl.cpkdcdwv.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6985775/e2f6a070-da04-11e4-8d37-1356ca2d37ff.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6985775/e2f6a070-da04-11e4-8d37-1356ca2d37ff.png)
https://cloud.githubusercontent.com/assets/10950389/6985775/e2f6a070-da04-11e4-8d37-1356ca2d37ff.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6985783/ecf7c9be-da04-11e4-9916-b890d1368aee.png

**Comment by dreamnet** [comment]
@zmathiasz :+1:
