### ISSUE TITLE
Adobe Slate — Make your words and images move

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5460]
**App Name:** Adobe Slate — Make your words and images move
**Bundle ID:** com.adobe.slate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=968433730">968433730</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-slate-make-your-words/id968433730?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-slate-make-your-words/id968433730?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPad23G, iPad2Wifi, iPadThirdGen, iPadMini, iPadFourthGen4G, iPadThirdGen4G, iPadFourthGen, iPadMini4G
**Original Artwork:**
<img src="http://a1539.phobos.apple.com/us/r30/Purple5/v4/66/44/bd/6644bd60-457f-6ea4-c882-e6639ee6dcb4/mzl.xguubqkt.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6987524/44c7cb74-da48-11e4-9283-3e5d8c9a46a2.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6986148/8e628cfa-da08-11e4-917e-a7de02b51320.png)
https://cloud.githubusercontent.com/assets/10950389/6986148/8e628cfa-da08-11e4-917e-a7de02b51320.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6986153/983e397c-da08-11e4-9384-14dc454135b2.png

**Comment by dreamnet** [comment]
:question: 
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6987524/44c7cb74-da48-11e4-9283-3e5d8c9a46a2.png)
https://cloud.githubusercontent.com/assets/2068130/6987524/44c7cb74-da48-11e4-9283-3e5d8c9a46a2.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6987538/5860cdb6-da48-11e4-9bb9-f592c4c9e3d6.png

**Comment by Trubbel** [comment]
I don't mind either, but @dreamnet yours look more "cleaner" or how you would put it.

**Comment by dreamnet** [comment]
@Trubbel I'm doing it this way, because I don't like to do a border in a border if it's not really necessary - I think it looks better that way. Also: We have a lot of Adobe app icons themed and none of them have a border. This is a iPad only app, so I don't add this icon to the iPhone theme, but I add it to my iPad theme.

**Comment by zmathiasz** [comment]
Works for me too..:D

**Comment by dreamnet** [comment]
@zmathiasz :+1: :wink:
