### ISSUE TITLE
TTMM - watchfaces for Pebble

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5461]
**App Name:** TTMM - watchfaces for Pebble
**Bundle ID:** eu.ttmm.ttmm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=694623195">694623195</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ttmm-watchfaces-for-pebble/id694623195?mt=8&uo=4">https://itunes.apple.com/us/app/ttmm-watchfaces-for-pebble/id694623195?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Albert Salamon
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/albert-salamon/id432620896?uo=4>© Albert Salamon</a>
**Supported Devices:** iPhone6, iPhone5, iPhone5s, iPhone-3GS, iPhone6Plus, iPadFourthGen4G, iPadMini, iPhone4S, iPodTouchFourthGen, iPad2Wifi, iPadMini4G, iPadThirdGen, iPodTouchFifthGen, iPhone5c, iPhone4, iPadThirdGen4G, iPad23G, iPadFourthGen
**Original Artwork:**
<img src="http://a1740.phobos.apple.com/us/r30/Purple3/v4/88/4f/49/884f490d-2b1a-b7b7-2e81-6198bd59dc50/pr_source.png?downloadKey=1428085320_8daf76021cdb421d185269d17f5595c8" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6986468/ba949982-da3d-11e4-9b7e-210971f11b51.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6986468/ba949982-da3d-11e4-9b7e-210971f11b51.png)
https://cloud.githubusercontent.com/assets/2068130/6986468/ba949982-da3d-11e4-9b7e-210971f11b51.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6986471/ca6d1014-da3d-11e4-9404-ae47c81bbadd.png
