### ISSUE TITLE
TestFlight

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5462]
**App Name:** TestFlight
**Bundle ID:** com.apple.TestFlight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=899247664">899247664</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/testflight/id899247664?mt=8&uo=4">https://itunes.apple.com/us/app/testflight/id899247664?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/99/02/f5/9902f5d1-c0b9-d9b5-5004-cf15f266c885/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31318137-90ebb978-ac4d-11e7-93ba-5555c11a5bd8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6987047/c7e1f098-da43-11e4-8e57-9a4e0f17820f.png)
https://cloud.githubusercontent.com/assets/2068130/6987047/c7e1f098-da43-11e4-8e57-9a4e0f17820f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6987058/d68f555e-da43-11e4-88b5-9648342f5eb9.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31318137-90ebb978-ac4d-11e7-93ba-5555c11a5bd8.png)
https://user-images.githubusercontent.com/2068130/31318137-90ebb978-ac4d-11e7-93ba-5555c11a5bd8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31318141-a2db7a38-ac4d-11e7-8715-5fba7c34a669.png
