### ISSUE TITLE
Maps 3D PRO - GPS Tracks for Bike, Hike, Ski & Outdoor

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5463]
**App Name:** Maps 3D PRO - GPS Tracks for Bike, Hike, Ski & Outdoor
**Bundle ID:** com.movingworld.geoguide3d
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391304000">391304000</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/maps-3d-pro-gps-tracks-for/id391304000?mt=8&uo=4">https://itunes.apple.com/us/app/maps-3d-pro-gps-tracks-for/id391304000?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** movingworld GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/movingworld-gmbh/id391304003?uo=4>© movingworld GmbH</a>
**Supported Devices:** iPhone5, iPadMini4G, iPhone4, iPodTouchFifthGen, iPhone5s, iPadFourthGen, iPhone6, iPad2Wifi, iPadFourthGen4G, iPhone6Plus, iPhone4S, iPad23G, iPadThirdGen, iPhone5c, iPadMini, iPadThirdGen4G
**Original Artwork:**
<img src="http://a1549.phobos.apple.com/us/r30/Purple1/v4/bc/b7/41/bcb74185-f2bc-946f-46b1-c85e3a6c57d6/mzl.tjsmbwhw.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6987823/ef398ad6-da4b-11e4-9d89-333cfab5c0b4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6987823/ef398ad6-da4b-11e4-9d89-333cfab5c0b4.png)
https://cloud.githubusercontent.com/assets/2068130/6987823/ef398ad6-da4b-11e4-9d89-333cfab5c0b4.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6987833/fefe0758-da4b-11e4-8ccd-494725090bcb.png
