### ISSUE TITLE
Bitcoin Ticker

### ISSUE THREAD

**Issue by ethansinjin** [glasklart/hd#5464]
**App Name:** Bitcoin Ticker
**Bundle ID:** com.skjegstad.bitcoin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=440229059">440229059</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bitcoin-ticker/id440229059?mt=8&uo=4">https://itunes.apple.com/us/app/bitcoin-ticker/id440229059?mt=8&uo=4</a>
**App Version:** 1.8.5
**Seller:** XBT Apps Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/xbt-apps-ltd/id575157268?uo=4>© XBT Apps Ltd</a>
**Supported Devices:** iPad2Wifi, iPhone5, iPodTouchFifthGen, iPad23G, iPadThirdGen, iPhone5s, iPhone5c, iPhone4S, iPadMini4G, iPadFourthGen, iPadFourthGen4G, iPhone6Plus, iPadThirdGen4G, iPadMini, iPhone4, iPhone6
**Original Artwork:**
<img src="http://a1353.phobos.apple.com/us/r30/Purple3/v4/e8/66/d0/e866d030-109f-66e8-bf1f-2e13231a64f2/mzl.vcckpabm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6988098/23baee10-da4e-11e4-8254-0ba4eeefb18b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6988098/23baee10-da4e-11e4-8254-0ba4eeefb18b.png)
https://cloud.githubusercontent.com/assets/2068130/6988098/23baee10-da4e-11e4-8254-0ba4eeefb18b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6988103/32fe52fe-da4e-11e4-9961-789466289867.png
