### ISSUE TITLE
Godus

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5465]
**App Name:** Godus
**Bundle ID:** com.mobage.ww.a1913.godusios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=815181808">815181808</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/godus/id815181808?mt=8&uo=4">https://itunes.apple.com/us/app/godus/id815181808?mt=8&uo=4</a>
**App Version:** 1.11
**Seller:** DeNA Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dena-corp./id881149457?uo=4>© DeNA Corp.</a>
**Supported Devices:** iPadMini4G, iPhone6, iPad2Wifi, iPadThirdGen, iPhone5, iPhone4S, iPadFourthGen4G, iPhone5s, iPadMini, iPad23G, iPhone5c, iPadThirdGen4G, iPhone6Plus, iPhone4, iPodTouchFifthGen, iPadFourthGen
**Original Artwork:**
<img src="http://a1972.phobos.apple.com/us/r30/Purple1/v4/82/ca/ac/82caac47-49c2-3d2c-d721-09dc6b2b5409/mzl.asgsmhxy.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6992032/f1a7c8e4-dab6-11e4-90bd-9ccc845d7ebf.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6992032/f1a7c8e4-dab6-11e4-90bd-9ccc845d7ebf.png)
https://cloud.githubusercontent.com/assets/2068130/6992032/f1a7c8e4-dab6-11e4-90bd-9ccc845d7ebf.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6992033/004ef17e-dab7-11e4-8e4c-7d544108c928.png
