### ISSUE TITLE
Walking Dead: The Game - Season 2

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5466]
**App Name:** Walking Dead: The Game - Season 2
**Bundle ID:** com.telltalegames.walkingdead2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=741183306">741183306</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/walking-dead-the-game-season-2/id741183306?mt=8&uo=4">https://itunes.apple.com/us/app/walking-dead-the-game-season-2/id741183306?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Telltale Games
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/telltale-inc/id364177939?uo=4>© Telltale Inc</a>
**Supported Devices:** iPhone4S, iPhone5c, iPadFourthGen, iPadMini, iPadMini4G, iPhone4, iPad23G, iPad2Wifi, iPadFourthGen4G, iPhone6Plus, iPodTouchFifthGen, iPadThirdGen4G, iPhone5, iPadThirdGen, iPhone5s, iPhone6, iPodTouchFourthGen
**Original Artwork:**
<img src="http://a242.phobos.apple.com/us/r30/Purple/v4/76/97/4b/76974bf3-6a9a-c0df-35de-a67b8861aa12/mzl.zrxmzbev.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6986255/5e599e9e-da09-11e4-98e1-78c012bd59e8.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6986255/5e599e9e-da09-11e4-98e1-78c012bd59e8.png)
https://cloud.githubusercontent.com/assets/10950389/6986255/5e599e9e-da09-11e4-98e1-78c012bd59e8.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6986259/69563654-da09-11e4-97d6-c6a125236f16.png

**Comment by dreamnet** [comment]
@zmathiasz :+1:
