### ISSUE TITLE
Mr Jump

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5467]
**App Name:** Mr Jump
**Bundle ID:** com.1button.mrjump
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955157084">955157084</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mr-jump/id955157084?mt=8&uo=4">https://itunes.apple.com/us/app/mr-jump/id955157084?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** 1Button SARL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/1button-sarl/id388888785?uo=4>© 1Button SARL</a>
**Supported Devices:** iPadThirdGen, iPhone5, iPhone6, iPhone4, iPadFourthGen, iPad2Wifi, iPadMini4G, iPadFourthGen4G, iPad23G, iPodTouchFifthGen, iPhone6Plus, iPhone5s, iPadMini, iPhone4S, iPhone5c, iPadThirdGen4G
**Original Artwork:**
<img src="http://a1905.phobos.apple.com/us/r30/Purple3/v4/bc/3e/c2/bc3ec265-ff87-7ce5-cc5b-3ae5796bd813/pr_source.png?downloadKey=1428094622_54b6b13bca5d6145507382caeac2ea18" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6991715/a62f3c82-daa5-11e4-8712-ae4258e4d00b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6991715/a62f3c82-daa5-11e4-8712-ae4258e4d00b.png)
https://cloud.githubusercontent.com/assets/2068130/6991715/a62f3c82-daa5-11e4-8712-ae4258e4d00b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6991719/b90839bc-daa5-11e4-9f2a-34709f8b6160.png
