### ISSUE TITLE
Dark Echo

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5469]
**App Name:** Dark Echo
**Bundle ID:** com.rac7.DarkEcho
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=951177560">951177560</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dark-echo/id951177560?mt=8&uo=4">https://itunes.apple.com/us/app/dark-echo/id951177560?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** RAC7 Games
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/rac7-games/id371411654?uo=4>© RAC7 Games</a>
**Supported Devices:** iPad2Wifi, iPad3G, iPhone4S, iPodTouchFourthGen, iPhone5c, iPadFourthGen4G, iPadWifi, iPhone-3GS, iPadMini, iPodTouchThirdGen, iPhone6, iPhone6Plus, iPhone4, iPadMini4G, iPodTouchFifthGen, iPhone5s, iPhone5, iPadThirdGen, iPadFourthGen, iPadThirdGen4G, iPad23G
**Original Artwork:**
<img src="http://a1305.phobos.apple.com/us/r30/Purple1/v4/7d/9c/7b/7d9c7b7f-c6ce-f838-cd71-d52e7a9508e3/mzl.vjzvtquz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6993708/23b9c340-dafe-11e4-88c9-f9573fe19bd3.png)

**Comment by WaterTrooper** [comment]
This should be interesting to see.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6993708/23b9c340-dafe-11e4-88c9-f9573fe19bd3.png)
https://cloud.githubusercontent.com/assets/2068130/6993708/23b9c340-dafe-11e4-88c9-f9573fe19bd3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6993713/341a1122-dafe-11e4-8cce-c59d15059ba1.png

**Comment by MagnaMike** [comment]
@dreamnet Yeah :+1:
