### ISSUE TITLE
Vectrex

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#547]
**App Name:** Vectrex
**Bundle ID:** com.rantmediagames.vectrexregeneration
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=543152783">543152783</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vectrex/id543152783?mt=8&uo=4">https://itunes.apple.com/us/app/vectrex/id543152783?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Rantmedia Games Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rantmedia-games/id543152786?uo=4">© Rantmedia Games</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/2e/33/fb/2e33fb4e-cabc-c399-c650-4ae57eee89c2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20240016/5f240942-a90e-11e6-851c-31c91c66a47f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20240016/5f240942-a90e-11e6-851c-31c91c66a47f.png)
https://cloud.githubusercontent.com/assets/20930745/20240016/5f240942-a90e-11e6-851c-31c91c66a47f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20240020/7e0d283e-a90e-11e6-9830-34afe8cc1da5.png
