### ISSUE TITLE
Moment App

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5470]
**App Name:** Moment App
**Bundle ID:** co.momentlens.moment
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=927098908">927098908</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moment-app/id927098908?mt=8&uo=4">https://itunes.apple.com/us/app/moment-app/id927098908?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** Moment Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/moment-inc./id927098907?uo=4>© Moment Inc.</a>
**Supported Devices:** iPodTouchFifthGen, iPhone4S, iPhone6, iPhone4, iPhone5c, iPhone5s, iPhone5, iPadFourthGen4G, iPadMini4G, iPadThirdGen4G, iPhone6Plus, iPadThirdGen, iPadMini, iPadFourthGen
**Original Artwork:**
<img src="http://a1973.phobos.apple.com/us/r30/Purple3/v4/f5/6e/4e/f56e4e25-43f2-3d4b-ac9d-c31fbe3699a8/mzl.xvvlfivk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6993741/d6b1a2ec-dafe-11e4-99ad-198badc01178.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6993741/d6b1a2ec-dafe-11e4-99ad-198badc01178.png)
https://cloud.githubusercontent.com/assets/2068130/6993741/d6b1a2ec-dafe-11e4-99ad-198badc01178.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6993743/e413c564-dafe-11e4-8876-4faadeb2f755.png
