### ISSUE TITLE
Alpscapes Meteo

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5471]
**App Name:** Alpscapes Meteo
**Bundle ID:** com.alpscapesmeteo.AlpscapesMeteo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953229635">953229635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alpscapes-meteo/id953229635?mt=8&uo=4">https://itunes.apple.com/us/app/alpscapes-meteo/id953229635?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Alexander Egger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/alexander-egger/id953229634?uo=4>© Alexander Egger</a>
**Supported Devices:** iPadMini, iPhone5, iPadFourthGen, iPhone5c, iPad23G, iPhone5s, iPadMini4G, iPhone6, iPadThirdGen, iPadFourthGen4G, iPhone4, iPadThirdGen4G, iPhone6Plus, iPhone4S, iPad2Wifi, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a399.phobos.apple.com/us/r30/Purple1/v4/58/99/09/58990952-2f12-e468-800f-adffe5f3c929/mzl.fblwhnaj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994149/d5e8284e-db0e-11e4-99bc-a931cb853e61.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994149/d5e8284e-db0e-11e4-99bc-a931cb853e61.png)
https://cloud.githubusercontent.com/assets/2068130/6994149/d5e8284e-db0e-11e4-99bc-a931cb853e61.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994153/e42fc538-db0e-11e4-9c73-d623a4d5b35a.png
