### ISSUE TITLE
UP by Jawbone™ – Free Fitness Tracker, Step Counter, Count Calories, Weight Loss, Diet, Recipes

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5472]
**App Name:** UP by Jawbone™ – Free Fitness Tracker, Step Counter, Count Calories, Weight Loss, Diet, Recipes
**Bundle ID:** com.aliphcom.upopen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916240764">916240764</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/up-by-jawbone-free-fitness/id916240764?mt=8&uo=4">https://itunes.apple.com/us/app/up-by-jawbone-free-fitness/id916240764?mt=8&uo=4</a>
**App Version:** 4.0.3
**Seller:** Aliphcom, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jawbone/id399513210?uo=4>© Jawbone</a>
**Supported Devices:** iPhone5s, iPhone4, iPad23G, iPhone5, iPhone4S, iPadThirdGen, iPhone6, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPhone6Plus, iPad2Wifi, iPadMini, iPodTouchFifthGen, iPadMini4G, iPhone5c
**Original Artwork:**
<img src="http://a1703.phobos.apple.com/us/r30/Purple3/v4/f3/03/ee/f303ee02-cc95-f1fd-d3ae-41d03f5d0190/mzl.xtiadmie.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994286/13bf6e8e-db14-11e4-8fa5-090e03491ec3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994286/13bf6e8e-db14-11e4-8fa5-090e03491ec3.png)
https://cloud.githubusercontent.com/assets/2068130/6994286/13bf6e8e-db14-11e4-8fa5-090e03491ec3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994289/23f3027a-db14-11e4-838e-b13e109dee8b.png
