### ISSUE TITLE
wogibtswas.at - Aktionen, Angebote, Schnäppchen und aktuelle Flugblätter sowie alle Filialen und Öffnungszeiten von Geschäften in Österreich

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5473]
**App Name:** wogibtswas.at - Aktionen, Angebote, Schnäppchen und aktuelle Flugblätter sowie alle Filialen und Öffnungszeiten von Geschäften in Österreich
**Bundle ID:** com.undabot.wogibtswas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=771962700">771962700</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wogibtswas.at-aktionen-angebote/id771962700?mt=8&uo=4">https://itunes.apple.com/us/app/wogibtswas.at-aktionen-angebote/id771962700?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** wogibtswas.at GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/wogibtswas.at/id871081977?uo=4>© wogibtswas.at</a>
**Supported Devices:** iPadThirdGen, iPadMini, iPhone5s, iPadFourthGen, iPodTouchFifthGen, iPhone5c, iPadFourthGen4G, iPadThirdGen4G, iPhone6, iPhone4, iPhone5, iPad23G, iPadMini4G, iPhone6Plus, iPad2Wifi, iPhone4S
**Original Artwork:**
<img src="http://a121.phobos.apple.com/us/r30/Purple1/v4/a1/fe/9a/a1fe9a90-4d52-0125-2059-5e40a05ebe62/mzl.lqpmwueq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6996269/7cc5d184-db7d-11e4-86b0-8cce27667584.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6996219/43b1f4ca-db7a-11e4-8cf4-ef9c1fa0ad9e.png)
https://cloud.githubusercontent.com/assets/2068130/6996219/43b1f4ca-db7a-11e4-8cf4-ef9c1fa0ad9e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6996220/5208e27c-db7a-11e4-94e9-101648a42e79.png
Mh, maybe this should be inverted?
