### ISSUE TITLE
STEIG EIN! Online- App

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5474]
**App Name:** STEIG EIN! Online- App
**Bundle ID:** at.steigein-online.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=623197276">623197276</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/steig-ein!-online-app/id623197276?mt=8&uo=4">https://itunes.apple.com/us/app/steig-ein!-online-app/id623197276?mt=8&uo=4</a>
**App Version:** 1.4.360
**Seller:** Hubert Ebner Verlags GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hubert-ebner-verlags-gmbh/id531747265?uo=4>© Hubert Ebner Verlags GmbH</a>
**Supported Devices:** iPhone5, iPadThirdGen, iPhone4, iPhone5s, iPodTouchFifthGen, iPadMini4G, iPhone6, iPhone6Plus, iPodTouchFourthGen, iPadFourthGen4G, iPhone-3GS, iPadMini, iPad3G, iPadFourthGen, iPad23G, iPad2Wifi, iPhone5c, iPadThirdGen4G, iPhone4S, iPadWifi, iPodTouchThirdGen
**Original Artwork:**
<img src="http://a1583.phobos.apple.com/us/r30/Purple6/v4/04/95/ec/0495ecaa-4f12-4419-f591-999574a85c55/mzl.yapxovgm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6996203/42018376-db79-11e4-872a-b20236d460c5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6996203/42018376-db79-11e4-872a-b20236d460c5.png)
https://cloud.githubusercontent.com/assets/2068130/6996203/42018376-db79-11e4-872a-b20236d460c5.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6996204/5021f7ce-db79-11e4-9fff-035d0c80711c.png
