### ISSUE TITLE
Game of Thrones - A Telltale Games Series

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5475]
**App Name:** Game of Thrones - A Telltale Games Series
**Bundle ID:** com.telltalegames.GOT100
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=906862658">906862658</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/game-thrones-telltale-games/id906862658?mt=8&uo=4">https://itunes.apple.com/us/app/game-thrones-telltale-games/id906862658?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Telltale Games
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/telltale-inc/id364177939?uo=4>© Telltale Inc</a>
**Supported Devices:** iPhone5s, iPhone5c, iPodTouchFifthGen, iPadThirdGen4G, iPhone4S, iPadMini, iPhone4, iPhone6Plus, iPadThirdGen, iPadFourthGen4G, iPad2Wifi, iPad23G, iPhone5, iPadMini4G, iPhone6, iPadFourthGen
**Original Artwork:**
<img src="http://a716.phobos.apple.com/us/r30/Purple3/v4/b3/f4/07/b3f4072c-5463-dec0-0ee9-c894302abf9a/mzl.axrjtbis.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6996185/fcd94ed8-db77-11e4-88aa-b90da65046cf.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6996165/ee5cb8a0-db76-11e4-9b63-17a46a56b312.png)
https://cloud.githubusercontent.com/assets/2068130/6996165/ee5cb8a0-db76-11e4-9b63-17a46a56b312.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6996168/053d7596-db77-11e4-9670-301f6706c068.png
