### ISSUE TITLE
Tangent - Add Geometric Shape, Pattern, Texture, and Frame Overlays and Effects to Your Photos

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5476]
**App Name:** Tangent - Add Geometric Shape, Pattern, Texture, and Frame Overlays and Effects to Your Photos
**Bundle ID:** com.benguerrette.Tangent
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=666406520">666406520</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tangent-add-geometric-shape/id666406520?mt=8&uo=4">https://itunes.apple.com/us/app/tangent-add-geometric-shape/id666406520?mt=8&uo=4</a>
**App Version:** 1.7.4
**Seller:** Pixite LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pixite-llc/id285719021?mt=8&uo=4>© Pixite LLC</a>
**Supported Devices:** iPhone4, iPodTouchFifthGen, iPad23G, iPhone4S, iPadThirdGen, iPadFourthGen, iPhone6, iPad2Wifi, iPhone5, iPhone5s, iPadThirdGen4G, iPadFourthGen4G, iPhone6Plus, iPadMini, iPadMini4G, iPhone5c
**Original Artwork:**
<img src="http://a1561.phobos.apple.com/us/r30/Purple3/v4/d3/69/42/d3694213-8e71-23bb-f0f2-7525d7d23fc7/mzl.buhtoben.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994125/30eb11ee-db0e-11e4-94e8-890bdfbbfe60.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994125/30eb11ee-db0e-11e4-94e8-890bdfbbfe60.png)
https://cloud.githubusercontent.com/assets/2068130/6994125/30eb11ee-db0e-11e4-94e8-890bdfbbfe60.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994128/401f2a38-db0e-11e4-82bf-8d91bb380427.png
