### ISSUE TITLE
Layout from Instagram

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5477]
**App Name:** Layout from Instagram
**Bundle ID:** com.burbn.layouts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967351793">967351793</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/layout-from-instagram/id967351793?mt=8&uo=4">https://itunes.apple.com/us/app/layout-from-instagram/id967351793?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Instagram, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/instagram-inc./id389801255?uo=4>© Instagram, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/59/5c/a1/595ca1d7-5f23-7426-a0e4-5e8401ccf056/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15267695/19810176-19c9-11e6-980b-0b089309487e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6996120/40b6c5bc-db74-11e4-8dea-615a46b81223.png)
https://cloud.githubusercontent.com/assets/2068130/6996120/40b6c5bc-db74-11e4-8dea-615a46b81223.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6996122/4e2c2372-db74-11e4-852d-9fd3ddc158d8.png

**Comment by grkka** [comment]
**App Name:** Layout from Instagram
**Bundle ID:** com.burbn.layouts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967351793">967351793</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/layout-from-instagram/id967351793?mt=8&uo=4">https://itunes.apple.com/us/app/layout-from-instagram/id967351793?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Instagram, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/instagram-inc./id389801255?uo=4>© Instagram, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/59/5c/a1/595ca1d7-5f23-7426-a0e4-5e8401ccf056/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15267695/19810176-19c9-11e6-980b-0b089309487e.png)
https://cloud.githubusercontent.com/assets/2068130/15267695/19810176-19c9-11e6-980b-0b089309487e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15267700/28c0e4bc-19c9-11e6-97f9-b34bac25c4e9.png
