### ISSUE TITLE
Storm by Weather Underground – Radar, Storm Tracking, Lightning & Precipitation Alerts

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5478]
**App Name:** Storm by Weather Underground – Radar, Storm Tracking, Lightning & Precipitation Alerts
**Bundle ID:** com.wunderground.storm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955957721">955957721</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/storm-by-weather-underground/id955957721?mt=8&uo=4">https://itunes.apple.com/us/app/storm-by-weather-underground/id955957721?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Weather Underground, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/weather-underground-llc/id284699897?uo=4>© Weather Underground, LLC</a>
**Supported Devices:** iPhone4, iPhone4S, iPadMini, iPhone5, iPadMini4G, iPadThirdGen4G, iPadFourthGen, iPhone6Plus, iPhone5s, iPadFourthGen4G, iPhone6, iPadThirdGen, iPodTouchFifthGen, iPad2Wifi, iPhone5c, iPad23G
**Original Artwork:**
<img src="http://a1097.phobos.apple.com/us/r30/Purple3/v4/37/e5/c5/37e5c5c5-cecc-d532-fa63-9432b015e9e0/mzl.acrnsumv.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6993954/d9c01286-db06-11e4-94b3-b82132c0d815.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6993954/d9c01286-db06-11e4-94b3-b82132c0d815.png)
https://cloud.githubusercontent.com/assets/2068130/6993954/d9c01286-db06-11e4-94b3-b82132c0d815.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6993955/e85af310-db06-11e4-8ed9-c5aa8ea413b0.png
