### ISSUE TITLE
aa

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5479]
**App Name:** aa
**Bundle ID:** com.aagame.aagame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905852173">905852173</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aa/id905852173?mt=8&uo=4">https://itunes.apple.com/us/app/aa/id905852173?mt=8&uo=4</a>
**App Version:** 1.1.9
**Seller:** General Adaptive Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/general-adaptive-apps-pty-ltd/id937589555?uo=4>© General Adaptive Apps Pty Ltd</a>
**Supported Devices:** iPhone4S, iPhone5, iPadThirdGen, iPhone5s, iPhone6, iPadMini4G, iPadThirdGen4G, iPhone6Plus, iPhone5c, iPodTouchFifthGen, iPad23G, iPadFourthGen4G, iPadFourthGen, iPhone4, iPadMini, iPad2Wifi
**Original Artwork:**
<img src="http://a442.phobos.apple.com/us/r30/Purple3/v4/52/20/db/5220db32-7d76-4265-7543-530a88b25f85/mzl.jlzdhytz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994430/cda7f6c2-db19-11e4-9f08-a1fa44b2596b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994330/27d923c2-db16-11e4-8936-4c4cef431783.png)
https://cloud.githubusercontent.com/assets/2068130/6994330/27d923c2-db16-11e4-8936-4c4cef431783.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994333/39480038-db16-11e4-9ddb-9a93f19e761d.png
