### ISSUE TITLE
uu

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5480]
**App Name:** uu
**Bundle ID:** com.uugame.uugame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=927819165">927819165</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/uu/id927819165?mt=8&uo=4">https://itunes.apple.com/us/app/uu/id927819165?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** General Adaptive Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/general-adaptive-apps-pty-ltd/id937589555?uo=4>© General Adaptive Apps Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPhone5s, iPhone4, iPhone5, iPodTouchFifthGen, iPhone6Plus, iPadThirdGen4G, iPhone5c, iPadThirdGen, iPad23G, iPadMini4G, iPadMini, iPhone4S, iPadFourthGen4G, iPadFourthGen, iPhone6
**Original Artwork:**
<img src="http://a371.phobos.apple.com/us/r30/Purple3/v4/b2/0d/58/b20d58fd-57a0-f3ef-705c-e78e4dd84065/mzl.flqsjfrx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994448/671173ce-db1a-11e4-9280-fc991caf3b89.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994348/9022fc50-db16-11e4-97a5-055681347793.png)
https://cloud.githubusercontent.com/assets/2068130/6994348/9022fc50-db16-11e4-97a5-055681347793.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994350/9e4dfee2-db16-11e4-87de-f8181adde03a.png
