### ISSUE TITLE
ff

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5481]
**App Name:** ff
**Bundle ID:** com.ff.ff
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=927819872">927819872</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ff/id927819872?mt=8&uo=4">https://itunes.apple.com/us/app/ff/id927819872?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** General Adaptive Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/general-adaptive-apps-pty-ltd/id937589555?uo=4>© General Adaptive Apps Pty Ltd</a>
**Supported Devices:** iPadMini, iPodTouchFifthGen, iPadMini4G, iPhone6, iPhone5s, iPhone4S, iPad2Wifi, iPadThirdGen4G, iPhone4, iPadFourthGen4G, iPadThirdGen, iPhone6Plus, iPadFourthGen, iPad23G, iPhone5c, iPhone5
**Original Artwork:**
<img src="http://a1381.phobos.apple.com/us/r30/Purple5/v4/a6/c0/3c/a6c03ce8-5c6f-06f7-dd60-43948a0684bc/mzl.kmcfhont.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994460/dbea9e32-db1a-11e4-9ad0-83f682d04a75.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994381/b477866a-db17-11e4-97bf-4c59fca37c13.png)
https://cloud.githubusercontent.com/assets/2068130/6994381/b477866a-db17-11e4-97bf-4c59fca37c13.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994383/c3e2d406-db17-11e4-9d2b-f74039916138.png
