### ISSUE TITLE
rr

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5482]
**App Name:** rr
**Bundle ID:** com.rrgame.rrgame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=931343017">931343017</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rr/id931343017?mt=8&uo=4">https://itunes.apple.com/us/app/rr/id931343017?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** General Adaptive Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/general-adaptive-apps-pty-ltd/id937589555?uo=4>© General Adaptive Apps Pty Ltd</a>
**Supported Devices:** iPhone6Plus, iPadThirdGen4G, iPhone5c, iPad23G, iPhone5, iPadMini4G, iPadThirdGen, iPhone6, iPhone4, iPodTouchFifthGen, iPadFourthGen, iPad2Wifi, iPadMini, iPhone5s, iPadFourthGen4G, iPhone4S
**Original Artwork:**
<img src="http://a1963.phobos.apple.com/us/r30/Purple3/v4/4e/ac/6c/4eac6c37-36f0-7b0f-f10d-4a6179d95318/mzl.gilrswub.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994470/3e76fece-db1b-11e4-984d-b0c07cc1d836.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994470/3e76fece-db1b-11e4-984d-b0c07cc1d836.png)
https://cloud.githubusercontent.com/assets/2068130/6994470/3e76fece-db1b-11e4-984d-b0c07cc1d836.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994472/4dfc8cb0-db1b-11e4-9f87-c138a8e249d9.png
