### ISSUE TITLE
ao

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5483]
**App Name:** ao
**Bundle ID:** com.aogame.aogame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937945761">937945761</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ao/id937945761?mt=8&uo=4">https://itunes.apple.com/us/app/ao/id937945761?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** General Adaptive Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/general-adaptive-apps-pty-ltd/id937589555?uo=4>© General Adaptive Apps Pty Ltd</a>
**Supported Devices:** iPadFourthGen4G, iPhone4S, iPadMini, iPadMini4G, iPhone5s, iPhone4, iPadThirdGen, iPhone6, iPad23G, iPadThirdGen4G, iPhone6Plus, iPhone5c, iPadFourthGen, iPodTouchFifthGen, iPad2Wifi, iPhone5
**Original Artwork:**
<img src="http://a712.phobos.apple.com/us/r30/Purple1/v4/a9/4e/25/a94e2543-bbad-4c62-708a-3efc91bb5442/mzl.ovczpojo.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994478/c323aadc-db1b-11e4-9231-6051209c932a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994478/c323aadc-db1b-11e4-9231-6051209c932a.png)
https://cloud.githubusercontent.com/assets/2068130/6994478/c323aadc-db1b-11e4-9231-6051209c932a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994481/d3f11eda-db1b-11e4-8533-429912a9c674.png
