### ISSUE TITLE
rl

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5484]
**App Name:** rl
**Bundle ID:** com.rl.rl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937958581">937958581</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rl/id937958581?mt=8&uo=4">https://itunes.apple.com/us/app/rl/id937958581?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** General Adaptive Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/general-adaptive-apps-pty-ltd/id937589555?uo=4>© General Adaptive Apps Pty Ltd</a>
**Supported Devices:** iPadThirdGen4G, iPadMini, iPhone4, iPad23G, iPhone5c, iPadFourthGen4G, iPodTouchFifthGen, iPad2Wifi, iPadThirdGen, iPhone4S, iPhone5s, iPhone6Plus, iPadFourthGen, iPadMini4G, iPhone6, iPhone5
**Original Artwork:**
<img src="http://a1438.phobos.apple.com/us/r30/Purple3/v4/91/68/5e/91685e49-ef23-bf8d-bc21-9f0c8080f238/mzl.pcilkoha.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994488/21de2f48-db1c-11e4-855c-10be8e3ff3b9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994488/21de2f48-db1c-11e4-855c-10be8e3ff3b9.png)
https://cloud.githubusercontent.com/assets/2068130/6994488/21de2f48-db1c-11e4-855c-10be8e3ff3b9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994489/31e08e04-db1c-11e4-9380-ca7b5ce004a5.png
