### ISSUE TITLE
sp

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5485]
**App Name:** sp
**Bundle ID:** com.spgame.spgame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937958671">937958671</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sp/id937958671?mt=8&uo=4">https://itunes.apple.com/us/app/sp/id937958671?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** General Adaptive Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/general-adaptive-apps-pty-ltd/id937589555?uo=4>© General Adaptive Apps Pty Ltd</a>
**Supported Devices:** iPadMini, iPad2Wifi, iPad23G, iPadThirdGen, iPadFourthGen4G, iPadFourthGen, iPhone6, iPhone4, iPadMini4G, iPhone5s, iPhone5c, iPhone6Plus, iPhone5, iPadThirdGen4G, iPhone4S, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a68.phobos.apple.com/us/r30/Purple3/v4/1d/1a/c3/1d1ac3d6-a62c-b4c0-7c0a-a7a04e6b74d3/mzl.buxqzifh.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994496/7ec4ab24-db1c-11e4-8485-a32f121a60b8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994496/7ec4ab24-db1c-11e4-8485-a32f121a60b8.png)
https://cloud.githubusercontent.com/assets/2068130/6994496/7ec4ab24-db1c-11e4-8485-a32f121a60b8.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994497/8e5be6f6-db1c-11e4-94d5-d8ede814c510.png
