### ISSUE TITLE
th

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5486]
**App Name:** th
**Bundle ID:** con.th.th
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937961955">937961955</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/th/id937961955?mt=8&uo=4">https://itunes.apple.com/us/app/th/id937961955?mt=8&uo=4</a>
**App Version:** 1.0.8
**Seller:** General Adaptive Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/general-adaptive-apps-pty-ltd/id937589555?uo=4>© General Adaptive Apps Pty Ltd</a>
**Supported Devices:** iPhone4, iPodTouchFifthGen, iPhone4S, iPadThirdGen4G, iPadMini4G, iPadThirdGen, iPhone6Plus, iPadFourthGen, iPhone5, iPadFourthGen4G, iPad2Wifi, iPadMini, iPhone5s, iPhone6, iPhone5c, iPad23G
**Original Artwork:**
<img src="http://a834.phobos.apple.com/us/r30/Purple3/v4/e3/45/c2/e345c26f-1957-8ec1-6523-39abd6db9f27/mzl.fmdyywyj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994507/ec8f2f62-db1c-11e4-9c89-7ce8e0f3ecb6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994507/ec8f2f62-db1c-11e4-9c89-7ce8e0f3ecb6.png)
https://cloud.githubusercontent.com/assets/2068130/6994507/ec8f2f62-db1c-11e4-9c89-7ce8e0f3ecb6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994511/fca42934-db1c-11e4-81cc-500a2741a9f1.png
