### ISSUE TITLE
au

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5487]
**App Name:** au
**Bundle ID:** com.au.au
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=931199028">931199028</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/au/id931199028?mt=8&uo=4">https://itunes.apple.com/us/app/au/id931199028?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** General Adaptive Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/general-adaptive-apps-pty-ltd/id937589555?uo=4>© General Adaptive Apps Pty Ltd</a>
**Supported Devices:** iPadFourthGen4G, iPadThirdGen, iPad2Wifi, iPhone4, iPadMini, iPadMini4G, iPhone6, iPadFourthGen, iPhone5c, iPhone5, iPadThirdGen4G, iPad23G, iPhone6Plus, iPhone4S, iPodTouchFifthGen, iPhone5s
**Original Artwork:**
<img src="http://a350.phobos.apple.com/us/r30/Purple1/v4/74/24/5f/74245f3c-b1c7-a541-4e51-4de337740919/mzl.ihwxwecg.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994524/8414ec82-db1d-11e4-85b0-0390fa7a8bdf.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994524/8414ec82-db1d-11e4-85b0-0390fa7a8bdf.png)
https://cloud.githubusercontent.com/assets/2068130/6994524/8414ec82-db1d-11e4-85b0-0390fa7a8bdf.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994530/92e350d2-db1d-11e4-95dc-9f27ae5aee68.png
