### ISSUE TITLE
Tips, Tricks and Help - For Godus

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5488]
**App Name:** Tips, Tricks and Help - For Godus
**Bundle ID:** com.mvk.GodusTipsTrick
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=908979544">908979544</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tips-tricks-and-help-for-godus/id908979544?mt=8&uo=4">https://itunes.apple.com/us/app/tips-tricks-and-help-for-godus/id908979544?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Mathias Van Kets
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mathias-van-kets/id886966099?uo=4>© Mathias Van Kets</a>
**Supported Devices:** iPadThirdGen4G, iPad23G, iPhone4, iPhone6Plus, iPadThirdGen, iPadMini4G, iPhone5, iPadMini, iPhone5s, iPodTouchFifthGen, iPhone6, iPadFourthGen4G, iPhone5c, iPad2Wifi, iPadFourthGen, iPhone4S
**Original Artwork:**
<img src="http://a1497.phobos.apple.com/us/r30/Purple5/v4/ed/52/16/ed521627-e4c8-a86c-6d35-69a5be86ad98/mzl.pmpwqdsy.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994106/7b3c1adc-db0d-11e4-8ea4-753d4f0b12a8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994106/7b3c1adc-db0d-11e4-8ea4-753d4f0b12a8.png)
https://cloud.githubusercontent.com/assets/2068130/6994106/7b3c1adc-db0d-11e4-8ea4-753d4f0b12a8.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994110/9027e638-db0d-11e4-9af6-a95906109202.png
