### ISSUE TITLE
Triggertrap: Camera remote for your SLR

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5489]
**App Name:** Triggertrap: Camera remote for your SLR
**Bundle ID:** com.triggertrap.Triggertrap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=517679831">517679831</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/triggertrap-camera-remote/id517679831?mt=8&uo=4">https://itunes.apple.com/au/app/triggertrap-camera-remote/id517679831?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Triggertrap Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/artist/triggertrap/id517679834?uo=4>© Triggertrap</a>
**Supported Devices:** iPad23G, iPadMini4G, iPhone5c, iPhone4S, iPadThirdGen, iPadFourthGen4G, iPhone6, iPhone5, iPhone6Plus, iPhone4, iPadFourthGen, iPodTouchFifthGen, iPadThirdGen4G, iPad2Wifi, iPhone5s, iPadMini
**Original Artwork:**
<img src="http://a1235.phobos.apple.com/us/r30/Purple1/v4/cc/b0/23/ccb0232e-c401-b850-f687-c8ffb4dad22f/mzl.ocvmxixs.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994017/4c4eb918-db09-11e4-89ce-9548a17733dd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6994017/4c4eb918-db09-11e4-89ce-9548a17733dd.png)
https://cloud.githubusercontent.com/assets/2068130/6994017/4c4eb918-db09-11e4-89ce-9548a17733dd.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6994018/5a86f144-db09-11e4-81c9-a1fda5a428d1.png
