### ISSUE TITLE
ArtStudio - Draw and Paint

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#549]
**App Name:** ArtStudio - Draw and Paint
**Bundle ID:** com.iphoneclan.draw
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=354818333">354818333</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/artstudio-draw-and-paint/id354818333?mt=8&uo=4">https://itunes.apple.com/us/app/artstudio-draw-and-paint/id354818333?mt=8&uo=4</a>
**App Version:** 5.94
**Seller:** Sylwester Los
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lucky-clan/id294866851?mt=8&uo=4>© Lucky Clan</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/3a/10/23/3a102398-b3a2-6a29-34f9-720cb58e8e37/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18902260/151b83e6-8552-11e6-8478-32f174a826f2.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18869572/2c48cfc4-84ad-11e6-97a6-4dc9d2b28be3.png)
https://cloud.githubusercontent.com/assets/20930745/18869572/2c48cfc4-84ad-11e6-97a6-4dc9d2b28be3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18869714/d16dbd3e-84ad-11e6-8cf2-806ddaa553dd.png
