### ISSUE TITLE
Schedule Viewer for Untis

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5490]
**App Name:** Schedule Viewer for Untis
**Bundle ID:** com.kaboomprojexs.WebUntis
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=408262715">408262715</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/schedule-viewer-for-untis/id408262715?mt=8&uo=4">https://itunes.apple.com/us/app/schedule-viewer-for-untis/id408262715?mt=8&uo=4</a>
**App Version:** 5.1.1
**Seller:** Lukas Kovar
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kaboomprojexs/id388955116?uo=4>© KaboomProjeXs</a>
**Supported Devices:** iPodTouchFifthGen, iPhone6Plus, iPadFourthGen4G, iPhone5s, iPadFourthGen, iPadThirdGen4G, iPadMini, iPhone4S, iPad23G, iPad2Wifi, iPhone6, iPadMini4G, iPadThirdGen, iPhone5c, iPhone5, iPhone4
**Original Artwork:**
<img src="http://a369.phobos.apple.com/us/r30/Purple3/v4/57/e7/86/57e786e9-7c0c-1637-ae06-1baeb26ad5f2/pr_source.png?downloadKey=1428181882_3b8fa2658c0082ca2b441ba97dd38244" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6993997/bd36f1aa-db08-11e4-9831-e1ffe492190c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6993997/bd36f1aa-db08-11e4-9831-e1ffe492190c.png)
https://cloud.githubusercontent.com/assets/2068130/6993997/bd36f1aa-db08-11e4-9831-e1ffe492190c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6993998/cb090d18-db08-11e4-8e41-5bbc3bc72e52.png
