### ISSUE TITLE
My Verizon

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5502]
**App Name:** My Verizon
**Bundle ID:** com.vzw.hss.myverizon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416023011">416023011</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-verizon/id416023011?mt=8&uo=4">https://itunes.apple.com/us/app/my-verizon/id416023011?mt=8&uo=4</a>
**App Version:** 6.1.0
**Seller:** Verizon Wireless
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/verizon-wireless/id411772703?uo=4">© Verizon Wireless</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/45/84/c1/4584c1c9-7d19-263b-6039-3fdfebc7c04e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38132019-9bc7c208-3409-11e8-9a6e-8db13053be6f.png)

**Comment by zmathiasz** [comment]
Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6995416/587c07ca-db15-11e4-87df-7181e46d6063.png)
https://cloud.githubusercontent.com/assets/10950389/6995416/587c07ca-db15-11e4-87df-7181e46d6063.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6995420/6981a746-db15-11e4-963b-e462f7d2612b.png

**Comment by boxermansr** [comment]
Can we update this one with the new icon from the new app, released today, July 7, 2016. It (to me) looks much better than the older one. 

Thanks!
:)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712463/9cea07f6-4688-11e6-97e5-479fd1b19ed5.png)
https://cloud.githubusercontent.com/assets/2068130/16712463/9cea07f6-4688-11e6-97e5-479fd1b19ed5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712464/aae3a984-4688-11e6-9743-9b121cc9a0f2.png

**Comment by Christian9901** [comment]
Icon has updated

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38132019-9bc7c208-3409-11e8-9a6e-8db13053be6f.png)
https://user-images.githubusercontent.com/2068130/38132019-9bc7c208-3409-11e8-9a6e-8db13053be6f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38132035-ab5e5e0c-3409-11e8-9255-a9b27f600ae3.png
