### ISSUE TITLE
Brushstroke

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5508]
**App Name:** Brushstroke
**Bundle ID:** com.codeorgana.brushstroke
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=824421012">824421012</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/brushstroke/id824421012?mt=8&uo=4">https://itunes.apple.com/us/app/brushstroke/id824421012?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Code Organa LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/code-organa/id363410063?uo=4>© Code Organa</a>
**Supported Devices:** iPodTouchFifthGen, iPadMini4G, iPad2Wifi, iPhone4, iPhone5s, iPad23G, iPadFourthGen4G, iPhone6, iPadThirdGen, iPhone5c, iPhone5, iPadMini, iPhone6Plus, iPhone4S, iPadThirdGen4G, iPadFourthGen
**Original Artwork:**
<img src="http://a363.phobos.apple.com/us/r30/Purple3/v4/22/2e/a6/222ea669-0922-c93f-47b2-383a50415321/mzl.zytruuib.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6997875/f11ade08-dbcd-11e4-8864-60e17bf68a1c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6997875/f11ade08-dbcd-11e4-8864-60e17bf68a1c.png)
https://cloud.githubusercontent.com/assets/2068130/6997875/f11ade08-dbcd-11e4-8864-60e17bf68a1c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6997878/01790112-dbce-11e4-8160-1014e9138fb4.png
