### ISSUE TITLE
FINAL FANTASY TACTICS: THE WAR OF THE LIONS

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5509]
**App Name:** FINAL FANTASY TACTICS: THE WAR OF THE LIONS
**Bundle ID:** com.square-enix.fft
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446760220">446760220</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/final-fantasy-tactics-war/id446760220?mt=8&uo=4">https://itunes.apple.com/us/app/final-fantasy-tactics-war/id446760220?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone4S, iPhone4, iPodTouchThirdGen, iPodTouchFifthGen, iPadWifi, iPod-touch-with-mic, iPadFourthGen4G, iPadThirdGen, iPhone5, iPadFourthGen, iPad3G, iPadMini, iPhone-3GS, iPodTouchFourthGen, iPhone5s, iPad23G, iPhone6Plus, iPhone5c, iPadThirdGen4G, iPad2Wifi, iPhone6, iPadMini4G, iPhone-3G
**Original Artwork:**
<img src="http://a945.phobos.apple.com/us/r30/Purple/v4/e6/2f/89/e62f89c6-647b-917a-a398-89634e41f583/mzl.iszdbgho.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6998128/7e0acac8-dbd6-11e4-823c-f8726f675150.png)

**Comment by zmathiasz** [comment]
This one is a redo on the original icon.  Yes or no, lemme know.  :smile: 

Icon update w/Source and no existing github issue:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997413/6478a89e-db88-11e4-9edd-d0906f2a3ff9.png)
https://cloud.githubusercontent.com/assets/10950389/6997413/6478a89e-db88-11e4-9edd-d0906f2a3ff9.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6997415/754f76ac-db88-11e4-9e65-1134d231a602.png

**Comment by dreamnet** [comment]
@zmathiasz Definitly better than the one we have. :+1:
