### ISSUE TITLE
Hulu Plus

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5510]
**App Name:** Hulu Plus
**Bundle ID:** com.hulu.plus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376510438">376510438</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hulu-plus/id376510438?mt=8&uo=4">https://itunes.apple.com/us/app/hulu-plus/id376510438?mt=8&uo=4</a>
**App Version:** 4.3.1
**Seller:** Hulu, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hulu-llc/id376510441?uo=4>© Hulu, LLC</a>
**Supported Devices:** iPad23G, iPhone5s, iPhone6Plus, iPadMini4G, iPadThirdGen4G, iPadFourthGen4G, iPadThirdGen, iPhone5, iPadFourthGen, iPhone4, iPad2Wifi, iPhone6, iPodTouchFifthGen, iPhone5c, iPhone4S, iPadMini
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/cd/59/56/cd5956bf-3dba-e7b9-6df7-5380ca12af7e/mzl.ssznzthq.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8396138/4f96fcf2-1d99-11e5-95c3-d666b56ffee5.png)

**Comment by zmathiasz** [comment]
Icon update w/Source and no existing github issue:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997482/cb1d0214-db8a-11e4-8bd1-9cf111bc4d7c.png)
https://cloud.githubusercontent.com/assets/10950389/6997482/cb1d0214-db8a-11e4-8bd1-9cf111bc4d7c.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6997486/da83137e-db8a-11e4-88ae-3853faac06d8.png

**Comment by Trubbel** [comment]
Icon has been updated,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8396138/4f96fcf2-1d99-11e5-95c3-d666b56ffee5.png)
https://cloud.githubusercontent.com/assets/10730122/8396138/4f96fcf2-1d99-11e5-95c3-d666b56ffee5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8396135/4b6a172c-1d99-11e5-835d-7ca78a04263e.png
