### ISSUE TITLE
Hinge: Dating & Relationships

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5512]
**App Name:** Hinge: Dating & Relationships
**Bundle ID:** co.hinge.mobile.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=595287172">595287172</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hinge-dating-relationships/id595287172?uo=4">https://apps.apple.com/us/app/hinge-dating-relationships/id595287172?uo=4</a>
**App Version:** 7.4.0
**Seller:** Hinge, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hinge-inc/id595287175?uo=4">© Hinge, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/f4/04/11/f4041117-9084-5b10-2be8-ff4282c91b91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772924-5b461380-a0fd-11e9-9d94-e0a2ea7f58c5.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6997670/b4b02cc4-db92-11e4-9d1c-a53646a96f8d.png)
https://cloud.githubusercontent.com/assets/10950389/6997670/b4b02cc4-db92-11e4-9d1c-a53646a96f8d.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6997673/c152c7b6-db92-11e4-9b84-5d12f3aaff58.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772924-5b461380-a0fd-11e9-9d94-e0a2ea7f58c5.png)
https://user-images.githubusercontent.com/2068130/60772924-5b461380-a0fd-11e9-9d94-e0a2ea7f58c5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60772929-6c8f2000-a0fd-11e9-970d-6ff1cca9ee9f.png
