### ISSUE TITLE
Last Voyage

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5513]
**App Name:** Last Voyage
**Bundle ID:** com.semidome.LastVoyage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=909195466">909195466</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/last-voyage/id909195466?mt=8&uo=4">https://itunes.apple.com/us/app/last-voyage/id909195466?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Semidome Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/semidome-inc./id779855685?uo=4>© Semidome Inc.</a>
**Supported Devices:** iPhone5, iPadFourthGen4G, iPadMini, iPhone5c, iPadThirdGen4G, iPhone4, iPad23G, iPodTouchFifthGen, iPhone5s, iPadFourthGen, iPhone6, iPhone4S, iPadThirdGen, iPhone6Plus, iPad2Wifi, iPadMini4G
**Original Artwork:**
<img src="http://a1873.phobos.apple.com/us/r30/Purple1/v4/25/7b/70/257b7020-758f-be3d-5cf0-2dd4c6870812/mzl.srzhvwwj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6998277/69b57cee-dbdb-11e4-934b-a77e45bcaeb1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6998277/69b57cee-dbdb-11e4-934b-a77e45bcaeb1.png)
https://cloud.githubusercontent.com/assets/2068130/6998277/69b57cee-dbdb-11e4-934b-a77e45bcaeb1.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6998278/78bd1134-dbdb-11e4-9cba-cf84faf91645.png
