### ISSUE TITLE
Nick Jr.

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5514]
**App Name:** Nick Jr.
**Bundle ID:** com.mtvn.nickjr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911115712">911115712</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nick-jr./id911115712?mt=8&uo=4">https://itunes.apple.com/us/app/nick-jr./id911115712?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Viacom International Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nickelodeon/id304682075?mt=8&uo=4>© Nickelodeon</a>
**Supported Devices:** iPadThirdGen, iPadThirdGen4G, iPad2Wifi, iPhone4, iPad23G, iPadFourthGen4G, iPhone5c, iPhone5, iPadMini4G, iPhone6Plus, iPhone4S, iPhone5s, iPadMini, iPodTouchFifthGen, iPhone6, iPadFourthGen
**Original Artwork:**
<img src="http://a1668.phobos.apple.com/us/r30/Purple5/v4/71/28/98/712898aa-544c-212f-9538-670e90d9afad/pr_source.png?downloadKey=1428263815_739d0cfaafc93f7c8a55e65517649985" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6998184/2f3b76c0-dbd8-11e4-9f64-2293b510215a.png)

**Comment by dreamnet** [comment]
Hm, it looks better without the clouds:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6998174/d222b912-dbd7-11e4-903b-ea0199eeca69.png)
https://cloud.githubusercontent.com/assets/2068130/6998174/d222b912-dbd7-11e4-903b-ea0199eeca69.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6998176/e332c0ee-dbd7-11e4-8cc1-b11a099a7dfe.png

**Comment by zmathiasz** [comment]
Looks good!
