### ISSUE TITLE
Acceleread Speed Reading Trainer

### ISSUE THREAD

**Issue by andreolidavide** [glasklart/hd#5516]
**App Name:** Acceleread Speed Reading Trainer
**Bundle ID:** com.bananabox.iapacceleread
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=528963250">528963250</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/acceleread-speed-reading-trainer/id528963250?mt=8&uo=4">https://itunes.apple.com/us/app/acceleread-speed-reading-trainer/id528963250?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** BananaBox Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bananabox-inc./id442618024?uo=4>© BananaBox Inc.</a>
**Supported Devices:** iPhone5c, iPadFourthGen4G, iPadMini, iPadFourthGen, iPadThirdGen, iPhone4, iPadThirdGen4G, iPad2Wifi, iPadMini4G, iPad23G, iPodTouchFifthGen, iPhone4S, iPhone6Plus, iPhone5s, iPhone6, iPhone5
**Original Artwork:**
<img src="http://a1449.phobos.apple.com/us/r30/Purple5/v4/79/62/fe/7962fe5b-ee92-f10b-51ff-3c78cba9dca9/mzl.aolushey.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7100421/39d368fc-e021-11e4-948c-1cbdb849014b.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/7074813/a38f6f40-defd-11e4-8691-abf5cd0a837f.png)
https://cloud.githubusercontent.com/assets/10515074/7074813/a38f6f40-defd-11e4-8691-abf5cd0a837f.png

Source
https://cloud.githubusercontent.com/assets/10515074/7074827/b6b78968-defd-11e4-9bc1-9dad84d3f892.png

**Comment by dreamnet** [comment]
Small update on the rounded corners:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7075143/fcb0395e-deff-11e4-9a06-c2f3d6594d49.png)
https://cloud.githubusercontent.com/assets/2068130/7075143/fcb0395e-deff-11e4-9a06-c2f3d6594d49.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7075155/0e06e1c6-df00-11e4-894f-c029371f6f97.png

**Comment by andreolidavide** [comment]
@dreamnet yeah I saw you did this on the other icon too, what's the radius I have to set in Photoshop to make them right?

**Comment by dreamnet** [comment]
@andreolidavide I am using Illustrator and I am using 180px rounded corners in the 1024x1024px source files. Here are some files:
https://cloud.githubusercontent.com/assets/2068130/7077864/b4ab4ea4-df14-11e4-84d7-42ccf2d27f77.png
https://cloud.githubusercontent.com/assets/2068130/7077877/ba0da54a-df14-11e4-90f5-a0852636fccc.png
