### ISSUE TITLE
The Bot Squad: Puzzle Battles

### ISSUE THREAD

**Issue by andreolidavide** [glasklart/hd#5517]
**App Name:** The Bot Squad: Puzzle Battles
**Bundle ID:** com.ubisoft.strategy.thebotsquad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=747717884">747717884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-bot-squad-puzzle-battles/id747717884?mt=8&uo=4">https://itunes.apple.com/us/app/the-bot-squad-puzzle-battles/id747717884?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Ubisoft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ubisoft/id317644720?uo=4>© Ubisoft</a>
**Supported Devices:** iPadThirdGen, iPhone6, iPadMini, iPhone6Plus, iPad2Wifi, iPhone5c, iPad23G, iPodTouchFourthGen, iPadFourthGen4G, iPhone5, iPadFourthGen, iPadMini4G, iPhone5s, iPodTouchFifthGen, iPadThirdGen4G, iPhone4S, iPhone4
**Original Artwork:**
<img src="http://a172.phobos.apple.com/us/r30/Purple3/v4/16/80/17/168017f0-c796-75ad-fdf9-f6558abb5b77/mzl.ofkhnfdp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7074877/234da7d8-defe-11e4-84d5-8e06420bf134.png)

**Comment by thedrinkeno** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11398992/7016496/6358d35c-dcdd-11e4-8769-e391bd6c534e.png)

Source:
https://cloud.githubusercontent.com/assets/11398992/7016497/635c798a-dcdd-11e4-8f5d-0b1846bc62f6.png

**Comment by andreolidavide** [comment]
What about something like this?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/7022285/66bda0ac-dd2a-11e4-8ef1-3e49b9fb6c8b.png)
https://cloud.githubusercontent.com/assets/10515074/7022285/66bda0ac-dd2a-11e4-8ef1-3e49b9fb6c8b.png

Source
https://cloud.githubusercontent.com/assets/10515074/7022290/7c40c9ae-dd2a-11e4-85f9-63d461479ca2.png

**Comment by thedrinkeno** [comment]
The rounded corners and cleaning up around the eyes definitely looks better :thumbsup:

**Comment by dreamnet** [comment]
@andreolidavide Jep, good work! Taken! :+1: 
@thedrinkeno Also - good work!

**Comment by dreamnet** [comment]
Just rounded the corners a bit more to go along with other icons like this.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7074877/234da7d8-defe-11e4-84d5-8e06420bf134.png)
https://cloud.githubusercontent.com/assets/2068130/7074877/234da7d8-defe-11e4-84d5-8e06420bf134.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7074907/4747c61e-defe-11e4-9393-518c1fdfdde4.png
