### ISSUE TITLE
Stack Exchange

### ISSUE THREAD

**Issue by andreolidavide** [glasklart/hd#5518]
**App Name:** Stack Exchange
**Bundle ID:** com.stackexchange.stackexchange
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=871299723">871299723</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stack-exchange/id871299723?mt=8&uo=4">https://itunes.apple.com/us/app/stack-exchange/id871299723?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Stack Exchange, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/stack-exchange/id871299726?uo=4>© Stack Exchange</a>
**Supported Devices:** iPodTouchFifthGen, iPadThirdGen4G, iPhone4, iPhone6, iPadThirdGen, iPhone5, iPad23G, iPadFourthGen, iPadFourthGen4G, iPhone6Plus, iPhone5c, iPhone4S, iPhone5s, iPad2Wifi, iPadMini4G, iPadMini
**Original Artwork:**
<img src="http://a1149.phobos.apple.com/us/r30/Purple3/v4/a9/b5/83/a9b5839b-1328-8b84-f60e-941e5267443c/mzl.zzgbuxqr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7010774/44bab0fc-dca4-11e4-8b0c-d2c9b1466729.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/7008418/b447fbf8-dc92-11e4-85e8-2c8417f0280f.png)
https://cloud.githubusercontent.com/assets/10515074/7008418/b447fbf8-dc92-11e4-85e8-2c8417f0280f.png

Source

https://cloud.githubusercontent.com/assets/10515074/7008426/c8f75f1c-dc92-11e4-905b-2c92609cfe5e.png

**Comment by dreamnet** [comment]
@andreolidavide Hmmmm....
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7010774/44bab0fc-dca4-11e4-8b0c-d2c9b1466729.png)
https://cloud.githubusercontent.com/assets/2068130/7010774/44bab0fc-dca4-11e4-8b0c-d2c9b1466729.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7010784/53c62568-dca4-11e4-8406-a4491eaa2688.png

**Comment by andreolidavide** [comment]
@dreamnet yeah I didn't know how to do that line, yours looks great +1
