### ISSUE TITLE
Moovit: Live Transit App For Bus, Train & Subway

### ISSUE THREAD

**Issue by andreolidavide** [glasklart/hd#5519]
**App Name:** Moovit: Live Transit App For Bus, Train & Subway
**Bundle ID:** com.tranzmate.tranzmate1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498477945">498477945</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moovit-live-transit-app-for-bus-train-subway/id498477945?mt=8&uo=4">https://itunes.apple.com/us/app/moovit-live-transit-app-for-bus-train-subway/id498477945?mt=8&uo=4</a>
**App Version:** 5.5.2
**Seller:** Moovit App Global LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/moovit-app-global-ltd/id498477948?uo=4">© Moovit App Global LTD</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/02/50/34/025034e2-8bac-0004-f6b4-52ed156efebf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/30343254-0d621f20-97fd-11e7-9037-23687430e8c7.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/7008606/b24ddde8-dc94-11e4-810f-e83eb717cb53.png)
https://cloud.githubusercontent.com/assets/10515074/7008606/b24ddde8-dc94-11e4-810f-e83eb717cb53.png

Source
https://cloud.githubusercontent.com/assets/10515074/7008610/bca89648-dc94-11e4-8f90-c9741fa80f34.png

**Comment by dreamnet** [comment]
Did a litte resize:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7011047/2e5c9c74-dca6-11e4-8402-d257798d4840.png)
https://cloud.githubusercontent.com/assets/2068130/7011047/2e5c9c74-dca6-11e4-8402-d257798d4840.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7011058/3ef4aa90-dca6-11e4-8fce-d292ec31c684.png

**Comment by andreolidavide** [comment]
@dreamnet great +1

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Moovit: Live Transit App For Bus, Train & Subway
**Bundle ID:** com.tranzmate.tranzmate1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498477945">498477945</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moovit-live-transit-app-for-bus-train-subway/id498477945?mt=8&uo=4">https://itunes.apple.com/us/app/moovit-live-transit-app-for-bus-train-subway/id498477945?mt=8&uo=4</a>
**App Version:** 5.5.2
**Seller:** Moovit App Global LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/moovit-app-global-ltd/id498477948?uo=4">© Moovit App Global LTD</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/02/50/34/025034e2-8bac-0004-f6b4-52ed156efebf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/30343254-0d621f20-97fd-11e7-9037-23687430e8c7.png)
https://user-images.githubusercontent.com/2068130/30343254-0d621f20-97fd-11e7-9037-23687430e8c7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/30343267-1d0c2aec-97fd-11e7-8968-73d7859b6fd9.png
