### ISSUE TITLE
MySi di CartaSi

### ISSUE THREAD

**Issue by andreolidavide** [glasklart/hd#5520]
**App Name:** MySi di CartaSi
**Bundle ID:** it.cartasi.mobile.iPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=518695175">518695175</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mysi-di-cartasi/id518695175?mt=8&uo=4">https://itunes.apple.com/us/app/mysi-di-cartasi/id518695175?mt=8&uo=4</a>
**App Version:** 1.3.5
**Seller:** CartaSi S.p.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/cartasi-s.p.a/id432419707?uo=4>© CartaSi S.p.A</a>
**Supported Devices:** iPadMini4G, iPhone6, iPhone4S, iPhone4, iPad2Wifi, iPadThirdGen4G, iPodTouchFourthGen, iPadThirdGen, iPhone5c, iPadFourthGen, iPadMini, iPodTouchFifthGen, iPhone5, iPhone6Plus, iPadFourthGen4G, iPhone5s, iPad23G, iPhone-3GS
**Original Artwork:**
<img src="http://a766.phobos.apple.com/us/r30/Purple3/v4/46/7d/bf/467dbf5d-14a1-3cfb-fbf7-5c76dcf228ee/mzl.zemqcsml.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7006596/be8c8120-dc82-11e4-949e-4fa06ab814bf.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7006153/36f281f4-dc7f-11e4-97df-6488ac7766a3.png)
https://cloud.githubusercontent.com/assets/10730122/7006153/36f281f4-dc7f-11e4-97df-6488ac7766a3.png

Source:
https://cloud.githubusercontent.com/assets/10730122/7006152/2e5ae96e-dc7f-11e4-878e-5454c0617a64.png

**Comment by dreamnet** [comment]
@Trubbel ? Different icons can't have the same source....
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7006596/be8c8120-dc82-11e4-949e-4fa06ab814bf.png)
https://cloud.githubusercontent.com/assets/2068130/7006596/be8c8120-dc82-11e4-949e-4fa06ab814bf.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7006604/d11e0ca0-dc82-11e4-80a1-12fe4e9bb5a4.png

**Comment by Trubbel** [comment]
I didn't like the *i* so I used the same source and re-sized it a little bit more.

**Comment by dreamnet** [comment]
@Trubbel That's OK - our sources looks nearly the same.
