### ISSUE TITLE
devLearn: Coding Made Easy

### ISSUE THREAD

**Issue by andreolidavide** [glasklart/hd#5521]
**App Name:** devLearn: Coding Made Easy
**Bundle ID:** com.devlearnapp.devlearn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=954844025">954844025</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/devlearn-coding-made-easy/id954844025?mt=8&uo=4">https://itunes.apple.com/us/app/devlearn-coding-made-easy/id954844025?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Tim Coy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tim-coy/id954844024?uo=4>© Tim Coy</a>
**Supported Devices:** iPad2Wifi, iPhone6, iPad23G, iPhone6Plus, iPadMini, iPadFourthGen4G, iPodTouchFifthGen, iPadMini4G, iPhone5s, iPadFourthGen, iPhone5, iPadThirdGen, iPhone4, iPadThirdGen4G, iPhone4S, iPhone5c
**Original Artwork:**
<img src="http://a317.phobos.apple.com/us/r30/Purple1/v4/ac/85/93/ac85934a-d8f1-474b-b17a-c078f0231502/pr_source.png?downloadKey=1428320797_f7440d901891d7933bff7806498baa3a" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7006105/b2c6ade2-dc7e-11e4-8858-96859be8a3ba.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7006105/b2c6ade2-dc7e-11e4-8858-96859be8a3ba.png)
https://cloud.githubusercontent.com/assets/10730122/7006105/b2c6ade2-dc7e-11e4-8858-96859be8a3ba.png

Source:
https://cloud.githubusercontent.com/assets/10730122/7006103/ac73d398-dc7e-11e4-9e65-76e78bebde8d.png
