### ISSUE TITLE
AdVenture Capitalist!

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5522]
**App Name:** AdVenture Capitalist!
**Bundle ID:** com.kongregate.mobile.adventurecapitalist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=927006017">927006017</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adventure-capitalist!/id927006017?mt=8&uo=4">https://itunes.apple.com/us/app/adventure-capitalist!/id927006017?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Kongregate, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kongregate/id491569846?uo=4>© Kongregate</a>
**Supported Devices:** iPhone5, iPadThirdGen, iPhone5c, iPhone-3GS, iPad2Wifi, iPhone4, iPadFourthGen4G, iPodTouchFourthGen, iPhone6Plus, iPhone5s, iPhone4S, iPadMini4G, iPad23G, iPadFourthGen, iPodTouchThirdGen, iPodTouchFifthGen, iPad3G, iPadMini, iPhone6, iPadThirdGen4G, iPadWifi
**Original Artwork:**
<img src="http://a1103.phobos.apple.com/us/r30/Purple1/v4/0a/7f/be/0a7fbef6-c506-afa2-bd82-e18416b30310/mzl.lqajrzzj.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7011851/e0ec3826-dcac-11e4-9ed6-6cdaeb864f8f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7011851/e0ec3826-dcac-11e4-9ed6-6cdaeb864f8f.png)
https://cloud.githubusercontent.com/assets/2068130/7011851/e0ec3826-dcac-11e4-9ed6-6cdaeb864f8f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7011856/f07d7f16-dcac-11e4-9a90-c762ba89d63e.png
