### ISSUE TITLE
Flic – Delete & Manage Camera Roll | Easily Delete Photos to Increase Disk Space

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5523]
**App Name:** Flic – Delete & Manage Camera Roll | Easily Delete Photos to Increase Disk Space
**Bundle ID:** com.lifehacklabs.Flic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=918263212">918263212</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flic-delete-manage-camera/id918263212?mt=8&uo=4">https://itunes.apple.com/us/app/flic-delete-manage-camera/id918263212?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** Lifehack Labs, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/lifehack-labs/id918263211?uo=4>© Lifehack Labs</a>
**Supported Devices:** iPadThirdGen, iPadMini, iPadFourthGen4G, iPadThirdGen4G, iPhone5c, iPodTouchFifthGen, iPhone5, iPhone4S, iPad2Wifi, iPad23G, iPhone6, iPadFourthGen, iPadMini4G, iPhone6Plus, iPhone5s
**Original Artwork:**
<img src="http://a1990.phobos.apple.com/us/r30/Purple3/v4/ad/84/ae/ad84ae4c-8ce2-0497-91f1-74e3733731df/mzl.hzdwsnjf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7011204/8055bbcc-dca7-11e4-8a23-e38a7284645a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7011204/8055bbcc-dca7-11e4-8a23-e38a7284645a.png)
https://cloud.githubusercontent.com/assets/2068130/7011204/8055bbcc-dca7-11e4-8a23-e38a7284645a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7011212/8dcdd05a-dca7-11e4-9147-d4068712394b.png
