### ISSUE TITLE
Tayasui Sketches Pro

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5524]
**App Name:** Tayasui Sketches Pro
**Bundle ID:** com.tayasui.sketchespro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=671867510">671867510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tayasui-sketches-pro/id671867510?mt=8&uo=4">https://itunes.apple.com/us/app/tayasui-sketches-pro/id671867510?mt=8&uo=4</a>
**App Version:** 13.1
**Seller:** yann le coroller
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tayasui.com/id359375853?uo=4">© Tayasui.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple19/v4/d3/39/57/d33957c5-552c-d51b-d7f7-b64d7b5581e9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455136/968844ac-ae54-11e6-85bf-3d7af076055d.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/7008490/86b8b730-dc93-11e4-826f-07d3952a5761.png)
https://cloud.githubusercontent.com/assets/10515074/7008490/86b8b730-dc93-11e4-826f-07d3952a5761.png

Source
https://cloud.githubusercontent.com/assets/10515074/7008496/926e53e6-dc93-11e4-8bf2-631db00d809e.png

**Comment by dreamnet** [comment]
@andreolidavide :+1:

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455136/968844ac-ae54-11e6-85bf-3d7af076055d.png)
https://cloud.githubusercontent.com/assets/20930745/20455136/968844ac-ae54-11e6-85bf-3d7af076055d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455140/a5626f02-ae54-11e6-83a0-926543b4da18.png
