### ISSUE TITLE
Allstar Heroes

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5525]
**App Name:** Allstar Heroes
**Bundle ID:** com.allstargames.allstarheroes.en
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=957608545">957608545</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ie/app/allstar-heroes/id957608545?mt=8&uo=4">https://itunes.apple.com/ie/app/allstar-heroes/id957608545?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** KUNLUN EUROPE LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/ie/artist/allstar-games/id957608544?uo=4>© Allstar Games</a>
**Supported Devices:** iPhone5s, iPadThirdGen4G, iPodTouchFourthGen, iPad3G, iPadWifi, iPodTouchFifthGen, iPad2Wifi, iPadMini4G, iPhone4, iPadMini, iPad23G, iPodTouchThirdGen, iPadFourthGen4G, iPadThirdGen, iPhone-3GS, iPadFourthGen, iPhone4S, iPhone5c, iPhone6Plus, iPhone6, iPhone5
**Original Artwork:**
<img src="http://a690.phobos.apple.com/us/r30/Purple3/v4/fc/9d/06/fc9d060d-9647-57c4-d53b-a253b1ca908f/pr_source.jpg?downloadKey=1428347074_4f8f7560bf08b4fcb882fe4b7d7dd5d5" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7219129/d1e5ed60-e691-11e4-9b11-e3e2e6872b01.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7219129/d1e5ed60-e691-11e4-9b11-e3e2e6872b01.png)
https://cloud.githubusercontent.com/assets/2068130/7219129/d1e5ed60-e691-11e4-9b11-e3e2e6872b01.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7219132/e1727a46-e691-11e4-9ac3-6bf4cb128f12.png
That's a pair of the nicest .... eyes I ever seen in an icon. :laughing:

**Comment by Trubbel** [comment]
@dreamnet Haha well said, and nice job with the icon!
