### ISSUE TITLE
Office Lens

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5526]
**App Name:** Office Lens
**Bundle ID:** com.microsoft.officelens
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=975925059">975925059</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/office-lens/id975925059?mt=8&uo=4">https://itunes.apple.com/us/app/office-lens/id975925059?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPadMini, iPhone5s, iPhone5, iPodTouchFifthGen, iPad23G, iPad2Wifi, iPadThirdGen, iPadMini4G, iPhone5c, iPadFourthGen, iPhone6Plus, iPhone6, iPhone4S, iPadThirdGen4G, iPadFourthGen4G
**Original Artwork:**
<img src="http://a951.phobos.apple.com/us/r30/Purple5/v4/ac/a0/5e/aca05efd-9687-1f7f-306a-d959358439fb/pr_source.jpg?downloadKey=1428347299_f1ab946f59f96aab8e3d181469445f22" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/7010479/ef9207ee-dca1-11e4-87f0-8e2bb12df923.png)

**Comment by andreolidavide** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/7008304/7d09d7a2-dc91-11e4-9dfa-64e8255f31be.png)
https://cloud.githubusercontent.com/assets/10515074/7008304/7d09d7a2-dc91-11e4-9dfa-64e8255f31be.png

Source
https://cloud.githubusercontent.com/assets/10515074/7008318/a98c0836-dc91-11e4-8f05-24ef80f968e5.png

**Comment by dreamnet** [comment]
@andreolidavide Yessir! :+1:
