### ISSUE TITLE
Adobe Lightroom

### ISSUE THREAD

**Issue by thedrinkeno** [glasklart/hd#5527]
**App Name:** Adobe Lightroom
**Bundle ID:** com.adobe.lrmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=804177739">804177739</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-lightroom/id804177739?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-lightroom/id804177739?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPadFourthGen, iPadMini4G, iPad2Wifi, iPadThirdGen4G, iPadThirdGen, iPad23G, iPadFourthGen4G, iPadMini
**Original Artwork:**
<img src="http://a629.phobos.apple.com/us/r30/Purple3/v4/a2/57/14/a257140b-c22c-8695-1fb8-98e410ddebf3/mzl.lwjsvpjz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7010926/30b8f8ec-dca5-11e4-8715-6d1c1d134ada.png)

**Comment by dreamnet** [comment]
This is an iPad only app. I do not add this to the official theme - but I add it to the theme on my website.

**Comment by thedrinkeno** [comment]
Noted, thanks!

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7010926/30b8f8ec-dca5-11e4-8715-6d1c1d134ada.png)
https://cloud.githubusercontent.com/assets/2068130/7010926/30b8f8ec-dca5-11e4-8715-6d1c1d134ada.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7010936/3fbd96c2-dca5-11e4-91cd-f6cef127c434.png
