### ISSUE TITLE
Slingshot

### ISSUE THREAD

**Issue by thedrinkeno** [glasklart/hd#5528]
**App Name:** Slingshot
**Bundle ID:** com.facebook.Slingshot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=878681557">878681557</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slingshot/id878681557?mt=8&uo=4">https://itunes.apple.com/us/app/slingshot/id878681557?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/facebook-inc./id284882218?uo=4>© Facebook, Inc.</a>
**Supported Devices:** iPhone5s, iPhone5, iPhone6, iPhone4S, iPadThirdGen4G, iPadMini, iPodTouchFifthGen, iPhone6Plus, iPadMini4G, iPad23G, iPhone4, iPad2Wifi, iPadThirdGen, iPhone5c, iPadFourthGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://a1561.phobos.apple.com/us/r30/Purple1/v4/4d/09/c2/4d09c246-1faa-d37a-c3af-375a24a5119b/mzl.bwuezmhj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7218555/37108ee6-e676-11e4-8042-0157786530bb.png)

**Comment by thedrinkeno** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11398992/7015532/0cfc7d52-dccd-11e4-85fd-6f9b6b9cf67d.png)

Source:
https://cloud.githubusercontent.com/assets/11398992/7015539/21e98a8e-dccd-11e4-85fb-2a6eba6eee19.png

**Comment by MagnaMike** [comment]
Hmmm... tough icon.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7218555/37108ee6-e676-11e4-8042-0157786530bb.png)
https://cloud.githubusercontent.com/assets/2068130/7218555/37108ee6-e676-11e4-8042-0157786530bb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7218556/48c414dc-e676-11e4-967d-ddb3fdff5109.png
:smile: :question:

**Comment by MagnaMike** [comment]
@dreamnet Sure I guess
