### ISSUE TITLE
Shades: A Simple Puzzle Game

### ISSUE THREAD

**Issue by thedrinkeno** [glasklart/hd#5529]
**App Name:** Shades: A Simple Puzzle Game
**Bundle ID:** com.uovo.blocks.shades
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=888683802">888683802</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shades-a-simple-puzzle-game/id888683802?mt=8&uo=4">https://itunes.apple.com/us/app/shades-a-simple-puzzle-game/id888683802?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** UOVO ApS
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/uovo/id653407952?uo=4>© UOVO</a>
**Supported Devices:** iPhone4, iPad23G, iPadThirdGen, iPadThirdGen4G, iPhone5c, iPodTouchFifthGen, iPhone5s, iPhone6Plus, iPhone4S, iPadFourthGen4G, iPadFourthGen, iPad2Wifi, iPadMini, iPhone6, iPadMini4G, iPhone5
**Original Artwork:**
<img src="http://a1076.phobos.apple.com/us/r30/Purple3/v4/9f/be/ae/9fbeaece-bbf3-b6ef-a819-befd4e75cf31/mzl.gtncbcue.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7218412/d698ab1e-e66d-11e4-9a54-75d9d689dff5.png)

**Comment by thedrinkeno** [comment]
I realise that according to guidelines, sources are supposed to be solid black, but having played the game, I think it is important to distinguish the shades of the blocks, so here goes.

The source is a png that has different transparency levels for different shades of blocks.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11398992/7016083/0f784fe4-dcd6-11e4-8b6c-d73e7fcf7818.png)

Source:
https://cloud.githubusercontent.com/assets/11398992/7016084/0f789148-dcd6-11e4-81ea-357a38ebfb3d.png

**Comment by MagnaMike** [comment]
@thedrinkeno Unfortunately we really like to stick to that guidline. Is there another way you can represent the icon? Could try using outlines.

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/7060243/5162b57c-de4b-11e4-95d8-7a223a229e3e.png)
https://cloud.githubusercontent.com/assets/10950389/7060243/5162b57c-de4b-11e4-95d8-7a223a229e3e.png
Source:
https://cloud.githubusercontent.com/assets/10950389/7060249/7235c55a-de4b-11e4-9d0f-3295ebe497cf.png

**Comment by dreamnet** [comment]
Here is my attempt on this one:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7218412/d698ab1e-e66d-11e4-9a54-75d9d689dff5.png)
https://cloud.githubusercontent.com/assets/2068130/7218412/d698ab1e-e66d-11e4-9a54-75d9d689dff5.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7218414/fbdd6c2a-e66d-11e4-8198-9e47150ffa0b.png
I think the lines to imitate grayscales are thick enough too see.
...and I don't think we should round corners, because this is some kind of Tetris game (check the screenshots).

**Comment by ivanov007** [comment]
@dreamnet  do you used shapes for this one?

**Comment by dreamnet** [comment]
@ivanov007 I used Adobe Illustrator.
