### ISSUE TITLE
Bloons TD 5

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#553]
**App Name:** Bloons TD 5
**Bundle ID:** com.ninjakiwi.bloonstd5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=563718995">563718995</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bloons-td-5/id563718995?mt=8&uo=4">https://itunes.apple.com/us/app/bloons-td-5/id563718995?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** Kaiparasoft Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ninja-kiwi/id386241773?uo=4>© Ninja Kiwi</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/59/bd/d8/59bdd839-12b1-91ae-fc67-7f9b37525c13/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18902346/b1157626-8552-11e6-8ebd-90a26f91c276.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18876763/3423758c-84cb-11e6-8412-ce6a752a71ba.png)
https://cloud.githubusercontent.com/assets/20930745/18876763/3423758c-84cb-11e6-8412-ce6a752a71ba.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18876789/4639dbb2-84cb-11e6-92bb-b92d58aca7ff.png
