### ISSUE TITLE
Esurance Mobile

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5530]
**App Name:** Esurance Mobile
**Bundle ID:** com.esurance.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=367762248">367762248</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/esurance-mobile/id367762248?mt=8&uo=4">https://itunes.apple.com/us/app/esurance-mobile/id367762248?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** Esurance
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/esurance/id367762251?uo=4>© Esurance</a>
**Supported Devices:** iPadFourthGen, iPadMini, iPhone4S, iPhone6, iPhone4, iPad23G, iPhone5c, iPadFourthGen4G, iPhone5s, iPhone5, iPhone6Plus, iPadMini4G, iPad2Wifi, iPadThirdGen, iPadThirdGen4G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a1863.phobos.apple.com/us/r30/Purple3/v4/23/45/72/23457238-937c-cbfa-af4e-cf80414cb5b4/mzl.avaesddo.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7078782/c0a0a166-df1c-11e4-85be-9f58111768d0.png)

**Comment by thedrinkeno** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11398992/7015430/9fb6de50-dccb-11e4-8dd5-121704a871bf.png)

Source:
https://cloud.githubusercontent.com/assets/11398992/7015442/e6d75be8-dccb-11e4-8215-979e6ed5b0e4.png

**Comment by boxermansr** [comment]
Think the link to get it is missing? :)

**Comment by dreamnet** [comment]
@thedrinkeno Please always post the direct link to the icon too, just like this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7078782/c0a0a166-df1c-11e4-85be-9f58111768d0.png)
https://cloud.githubusercontent.com/assets/2068130/7078782/c0a0a166-df1c-11e4-85be-9f58111768d0.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7078795/d1ed28fe-df1c-11e4-8013-ea3a01931e29.png
I also think it is better to keep the original size for this icon.
