### ISSUE TITLE
Tucanos Brazilian Grill

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5531]
**App Name:** Tucanos Brazilian Grill
**Bundle ID:** com.punchh.tucanos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=910929998">910929998</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tucanos-brazilian-grill/id910929998?mt=8&uo=4">https://itunes.apple.com/us/app/tucanos-brazilian-grill/id910929998?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Punchh Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/punchh-inc./id386700205?uo=4>© Punchh Inc.</a>
**Supported Devices:** iPadMini4G, iPhone5s, iPadFourthGen4G, iPhone6Plus, iPad23G, iPodTouchFifthGen, iPad2Wifi, iPadMini, iPhone5c, iPhone5, iPhone4, iPhone4S, iPhone6, iPhone-3GS, iPadThirdGen4G, iPadThirdGen, iPodTouchFourthGen, iPadFourthGen
**Original Artwork:**
<img src="http://a1427.phobos.apple.com/us/r30/Purple1/v4/4f/77/58/4f77586b-6113-1cfa-6ed9-f2a57c373096/mzl.jkwksrpp.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7104570/3c3698b0-e0eb-11e4-8fb4-3868774393c0.png)

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7104570/3c3698b0-e0eb-11e4-8fb4-3868774393c0.png)
https://cloud.githubusercontent.com/assets/2068130/7104570/3c3698b0-e0eb-11e4-8fb4-3868774393c0.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7104573/4ee6924e-e0eb-11e4-8afc-29b23bc0b1a4.png

**Comment by MagnaMike** [comment]
@dreamnet That's perfect.

**Comment by dreamnet** [comment]
@MagnaMike THX!
