### ISSUE TITLE
BBC Horizons

### ISSUE THREAD

**Issue by thedrinkeno** [glasklart/hd#5532]
**App Name:** BBC Horizons
**Bundle ID:** com.bbc.horizons
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=871277884">871277884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bbc-horizons/id871277884?mt=8&uo=4">https://itunes.apple.com/us/app/bbc-horizons/id871277884?mt=8&uo=4</a>
**App Version:** 1.01
**Seller:** BBC Worldwide LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bbc-worldwide/id344138454?uo=4>© BBC Worldwide</a>
**Supported Devices:** iPhone6, iPadMini4G, iPhone5c, iPodTouchFifthGen, iPhone4, iPadThirdGen4G, iPad2Wifi, iPhone5s, iPhone4S, iPhone6Plus, iPadFourthGen, iPad23G, iPadMini, iPadFourthGen4G, iPadThirdGen, iPhone5
**Original Artwork:**
<img src="http://a295.phobos.apple.com/us/r30/Purple6/v4/5a/69/a6/5a69a689-bd8a-0b45-9704-711ca48e57da/mzl.lqxnjnoy.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7080629/b36a0d48-df35-11e4-91f7-6e08d0d72b18.png)

**Comment by thedrinkeno** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11398992/7015689/8def24f8-dccf-11e4-98f3-cdad74717266.png)

Source:
https://cloud.githubusercontent.com/assets/11398992/7015690/902e1ab2-dccf-11e4-9bc7-e9a0cd338bcf.png

**Comment by MagnaMike** [comment]
@dreamnet Do you think it will look okay on retina?

**Comment by dreamnet** [comment]
@MagnaMike Hm, maybe the "HORIZONS" is a bit too small.... I give it a try...

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7079249/39d4a8b6-df22-11e4-9086-2c35a329655e.png)
https://cloud.githubusercontent.com/assets/2068130/7079249/39d4a8b6-df22-11e4-9086-2c35a329655e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7079254/491159fa-df22-11e4-8ccc-084be36a0188.png
A bit better?

**Comment by MagnaMike** [comment]
@dreamnet Is that centered properly? Or have my eyes gone funny... :eyes: Otherwise looks good.

**Comment by dreamnet** [comment]
@MagnaMike Good eye! It's matching the original, but I can center it if you think it would look better.

**Comment by MagnaMike** [comment]
@dreamnet Let's do centered I guess.

**Comment by dreamnet** [comment]
@MagnaMike OK!
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7080629/b36a0d48-df35-11e4-91f7-6e08d0d72b18.png)
https://cloud.githubusercontent.com/assets/2068130/7080629/b36a0d48-df35-11e4-91f7-6e08d0d72b18.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7080634/c13f3d80-df35-11e4-8f32-e5039a16c72b.png
