### ISSUE TITLE
Bonza Word Puzzle

### ISSUE THREAD

**Issue by thedrinkeno** [glasklart/hd#5533]
**App Name:** Bonza Word Puzzle
**Bundle ID:** au.com.minimega.bonza
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=662053009">662053009</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bonza-word-puzzle/id662053009?mt=8&uo=4">https://itunes.apple.com/us/app/bonza-word-puzzle/id662053009?mt=8&uo=4</a>
**App Version:** 1.6.7
**Seller:** Minimega PTY LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/minimega-pty-ltd/id453173167?uo=4>© Minimega Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen4G, iPadThirdGen, iPadMini4G, iPadMini, iPhone4S, iPhone-3GS, iPodTouchFifthGen, iPadFourthGen, iPodTouchFourthGen, iPhone6Plus, iPad23G, iPadFourthGen4G, iPhone5, iPhone4, iPhone5c, iPhone5s, iPhone6
**Original Artwork:**
<img src="http://a934.phobos.apple.com/us/r30/Purple3/v4/80/ee/f8/80eef8de-39cc-84d9-d2c9-66fecf17b6d9/mzl.ikxpublq.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11398992/7015868/d3b04c58-dcd2-11e4-8892-b9504c015bc1.png)

**Comment by thedrinkeno** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11398992/7015868/d3b04c58-dcd2-11e4-8892-b9504c015bc1.png)

Source:
https://cloud.githubusercontent.com/assets/11398992/7015867/d3adc316-dcd2-11e4-997a-25a5697ddeb1.png

**Comment by MagnaMike** [comment]
@thedrinkeno Looks good. Don't forget to add a link to the icon itself. [(This one)](https://cloud.githubusercontent.com/assets/11398992/7015868/d3b04c58-dcd2-11e4-8892-b9504c015bc1.png)

**Comment by dreamnet** [comment]
@thedrinkeno If you want to be on the [contributors list](https://github.com/glasklart/hd/graphs/contributors) and get credits for your contributions, please add a public mailadress to your Github account.

**Comment by thedrinkeno** [comment]
@dreamnet added

**Comment by dreamnet** [comment]
@thedrinkeno Jup! :+1:
