### ISSUE TITLE
Cubing Timer

### ISSUE THREAD

**Issue by thedrinkeno** [glasklart/hd#5534]
**App Name:** Cubing Timer
**Bundle ID:** com.xionchannel.cubingtimer.
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306802722">306802722</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cubing-timer/id306802722?mt=8&uo=4">https://itunes.apple.com/us/app/cubing-timer/id306802722?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Yuichi Higuchi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/xionchannel/id306802725?uo=4>© xionchannel</a>
**Supported Devices:** iPodTouchFifthGen, iPad23G, iPadWifi, iPhone6, iPad2Wifi, iPadThirdGen4G, iPodTouchFourthGen, iPad3G, iPhone5c, iPadFourthGen, iPhone5s, iPhone5, iPhone4, iPadFourthGen4G, iPhone6Plus, iPhone-3GS, iPadMini, iPadThirdGen, iPhone4S, iPadMini4G, iPodTouchThirdGen
**Original Artwork:**
<img src="http://a823.phobos.apple.com/us/r30/Purple/98/2d/96/mzl.wqxlqyrm.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7101975/c6675cec-e071-11e4-92ad-7c724846f4cd.png)

**Comment by thedrinkeno** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/11398992/7016751/c0872e5c-dce2-11e4-8b7c-3bf770d456e0.png)

Source:
https://cloud.githubusercontent.com/assets/11398992/7016750/c07238e4-dce2-11e4-929c-c9f96398445d.png

**Comment by MagnaMike** [comment]
I think this should be done with more emphasis on the shape of a Rubik's cube.

**Comment by ivanov007** [comment]
and without shades (grays)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7101975/c6675cec-e071-11e4-92ad-7c724846f4cd.png)
https://cloud.githubusercontent.com/assets/2068130/7101975/c6675cec-e071-11e4-92ad-7c724846f4cd.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7101977/d4f088ce-e071-11e4-9678-1838e7662037.png

**Comment by MagnaMike** [comment]
@dreamnet Perfect!
