### ISSUE TITLE
Emergency +

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5535]
**App Name:** Emergency +
**Bundle ID:** au.gov.triplezero.TripleZero000Emergency
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=691814685">691814685</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/emergency-+/id691814685?mt=8&uo=4">https://itunes.apple.com/au/app/emergency-+/id691814685?mt=8&uo=4</a>
**App Version:** 1.11
**Seller:** National Triple Zero Awareness Work Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/artist/triple-zero-awareness-work/id963596999?uo=4>© Triple Zero Awareness Work Group</a>
**Supported Devices:** iPhone4S, iPhone6, iPhone5, iPhone5s, iPhone-3GS, iPhone4, iPadMini4G, iPadFourthGen4G, iPad3G, iPad23G, iPadThirdGen4G, iPhone5c, iPhone6Plus
**Original Artwork:**
<img src="http://a1544.phobos.apple.com/us/r30/Purple6/v4/38/9d/ca/389dcad1-bf5b-497b-8a3a-4e67e91b5ba3/mzl.agrjwbak.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7019471/eeda40d0-dcd5-11e4-97a0-8224f45acb7b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7019471/eeda40d0-dcd5-11e4-97a0-8224f45acb7b.png)
https://cloud.githubusercontent.com/assets/3090247/7019471/eeda40d0-dcd5-11e4-97a0-8224f45acb7b.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7019472/eedc7c6a-dcd5-11e4-802d-9cbbabccaa81.png

**Comment by MagnaMike** [comment]
@ivanov007 :+1:

**Comment by dreamnet** [comment]
@ivanov007 :+1:
