### ISSUE TITLE
Rewardle

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5536]
**App Name:** Rewardle
**Bundle ID:** com.Rewardle.RewardleApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519685156">519685156</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rewardle/id519685156?mt=8&uo=4">https://itunes.apple.com/us/app/rewardle/id519685156?mt=8&uo=4</a>
**App Version:** 3.7.2
**Seller:** Rewardle Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/rewardle-pty-ltd/id519685159?uo=4>© Rewardle Pty Ltd</a>
**Supported Devices:** iPad23G, iPad2Wifi, iPadMini4G, iPadFourthGen4G, iPodTouchFifthGen, iPadFourthGen, iPhone4S, iPadThirdGen4G, iPadMini, iPhone5s, iPhone5c, iPadThirdGen, iPhone6, iPhone4, iPhone6Plus, iPhone5
**Original Artwork:**
<img src="http://a816.phobos.apple.com/us/r30/Purple1/v4/95/e8/a7/95e8a7e8-7f27-6aee-679a-f11494dc6283/mzl.ddmylybn.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7019133/5e4ee5e6-dcd2-11e4-8ca3-635e389ea1e6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7019133/5e4ee5e6-dcd2-11e4-8ca3-635e389ea1e6.png)
https://cloud.githubusercontent.com/assets/3090247/7019133/5e4ee5e6-dcd2-11e4-8ca3-635e389ea1e6.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7019132/5e2468fc-dcd2-11e4-9833-3e78a5e621d3.png

**Comment by MagnaMike** [comment]
@ivanov007 Yep!

**Comment by dreamnet** [comment]
@ivanov007 Yup!
