### ISSUE TITLE
Back to Bed

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5537]
**App Name:** Back to Bed
**Bundle ID:** com.bedtime.backtobed
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=887878083">887878083</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/back-to-bed/id887878083?mt=8&uo=4">https://itunes.apple.com/us/app/back-to-bed/id887878083?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Surreal Games ApS
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bedtime-digital-games/id887878086?uo=4>© Bedtime Digital Games</a>
**Supported Devices:** iPadFourthGen, iPadFourthGen4G, iPad2Wifi, iPhone4, iPodTouchFifthGen, iPadMini4G, iPad23G, iPhone5, iPadThirdGen4G, iPhone4S, iPhone6Plus, iPhone6, iPadThirdGen, iPhone5s, iPadMini, iPhone5c
**Original Artwork:**
<img src="http://a877.phobos.apple.com/us/r30/Purple5/v4/99/95/91/99959137-941a-e664-44d5-072c3e24ef90/mzl.sbrvxjfl.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/7023349/88f491bc-dd02-11e4-964d-8ab7e3dc86a1.png)

**Comment by zmathiasz** [comment]
Hmmmmm....maybe.. :smile: 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/7023349/88f491bc-dd02-11e4-964d-8ab7e3dc86a1.png)
https://cloud.githubusercontent.com/assets/10950389/7023349/88f491bc-dd02-11e4-964d-8ab7e3dc86a1.png
Source:
https://cloud.githubusercontent.com/assets/10950389/7023359/9460186e-dd02-11e4-85e9-560339216ebc.png

**Comment by MagnaMike** [comment]
@zmathiasz I like it!

**Comment by dreamnet** [comment]
@zmathiasz Me too - good one! :+1:
