### ISSUE TITLE
Mushrooms PRO - NATURE MOBILE - For Safe Enjoyment!

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5538]
**App Name:** Mushrooms PRO - NATURE MOBILE - For Safe Enjoyment!
**Bundle ID:** com.alphablind.mushrooms
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=523607704">523607704</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mushrooms-pro-nature-mobile/id523607704?mt=8&uo=4">https://itunes.apple.com/us/app/mushrooms-pro-nature-mobile/id523607704?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** NATURE MOBILE G.m.b.H.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nature-mobile-g.m.b.h./id964511943?uo=4>© NATURE MOBILE G.m.b.H.</a>
**Supported Devices:** iPadFourthGen, iPadMini, iPhone5s, iPhone6, iPad2Wifi, iPhone4, iPadMini4G, iPhone6Plus, iPhone5, iPad23G, iPhone4S, iPadFourthGen4G, iPodTouchFifthGen, iPodTouchFourthGen, iPhone5c, iPadThirdGen, iPadThirdGen4G, iPhone-3GS
**Original Artwork:**
<img src="http://a281.phobos.apple.com/us/r30/Purple5/v4/dd/30/be/dd30bedc-6009-3c86-86a3-e9cc2c4bdb03/mzl.ytbimcmq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7079299/cf93695a-df22-11e4-85a5-d868ad967bed.png)

**Comment by ivanov007** [comment]
tough one, maybe this will do it :wink: 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7042011/1647c2ae-dda4-11e4-9214-f2f20149847b.png)
https://cloud.githubusercontent.com/assets/3090247/7042011/1647c2ae-dda4-11e4-9214-f2f20149847b.png

**Comment by MagnaMike** [comment]
Haha @ivanov007 :laughing: 

Being serious though, I went to their website and found out this is the icon they use on Android for the same app. Could just make the icon like it:
![mushroom](https://cloud.githubusercontent.com/assets/2236254/7046759/14008a6c-ddd6-11e4-9c68-612e708d331a.PNG)

**Comment by ivanov007** [comment]
@MagnaMike yeah I think that one will look good :+1:

**Comment by dreamnet** [comment]
Something like this: ?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7079299/cf93695a-df22-11e4-85a5-d868ad967bed.png)
https://cloud.githubusercontent.com/assets/2068130/7079299/cf93695a-df22-11e4-85a5-d868ad967bed.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7079313/e6b66a74-df22-11e4-9710-0bf741cc23af.PNG

**Comment by MagnaMike** [comment]
@dreamnet Yeah. :+1:
