### ISSUE TITLE
FTPManager

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5541]
**App Name:** FTPManager
**Bundle ID:** com.skyjos.ftpmanager
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=522627917">522627917</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ftpmanager/id522627917?mt=8&uo=4">https://itunes.apple.com/us/app/ftpmanager/id522627917?mt=8&uo=4</a>
**App Version:** 3.3.0
**Seller:** Steven Zhang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/steven-zhang/id499470116?uo=4>© Steven Zhang</a>
**Supported Devices:** iPhone4, iPadMini, iPhone4S, iPodTouchFifthGen, iPad3G, iPhone6, iPhone5s, iPhone6Plus, iPodTouchFourthGen, iPhone5, iPadFourthGen4G, iPodTouchThirdGen, iPhone-3GS, iPadWifi, iPad2Wifi, iPad23G, iPadFourthGen, iPadThirdGen, iPadMini4G, iPhone5c, iPadThirdGen4G
**Original Artwork:**
<img src="http://a1683.phobos.apple.com/us/r30/Purple3/v4/49/74/3e/49743e73-1e44-edaf-760f-2346b9d96f25/mzl.tqixetqi.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/7058732/c1d79c4a-de33-11e4-9145-04338c06fa95.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/7058732/c1d79c4a-de33-11e4-9145-04338c06fa95.png)
https://cloud.githubusercontent.com/assets/10950389/7058732/c1d79c4a-de33-11e4-9145-04338c06fa95.png
Source:
https://cloud.githubusercontent.com/assets/10950389/7058738/d165521a-de33-11e4-91a1-c5463329f4f3.png

**Comment by dreamnet** [comment]
@zmathiasz :+1:
