### ISSUE TITLE
Quick — add text to photos fast

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5542]
**App Name:** Quick — add text to photos fast
**Bundle ID:** com.gopotluck.overgram
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=574443485">574443485</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quick-add-text-to-photos-fast/id574443485?mt=8&uo=4">https://itunes.apple.com/us/app/quick-add-text-to-photos-fast/id574443485?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Over, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/over/id902390862?uo=4>© Over</a>
**Supported Devices:** iPadThirdGen, iPadFourthGen4G, iPodTouchFifthGen, iPhone4, iPadMini, iPhone5s, iPhone6Plus, iPhone4S, iPadFourthGen, iPhone5, iPhone6, iPadMini4G, iPad2Wifi, iPad23G, iPadThirdGen4G, iPhone5c
**Original Artwork:**
<img src="http://a1070.phobos.apple.com/us/r30/Purple5/v4/7f/ba/5f/7fba5f90-5182-21c5-b754-a625ffecb30d/mzl.cpoyokiv.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7100582/39ce1b40-e02b-11e4-8ec3-ffd55024a8a0.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/7058844/6e0bf7da-de35-11e4-9a19-23af905e9913.png)
https://cloud.githubusercontent.com/assets/10950389/7058844/6e0bf7da-de35-11e4-9a19-23af905e9913.png
Source:
https://cloud.githubusercontent.com/assets/10950389/7058847/77d3e21e-de35-11e4-8554-e90ff1771750.png

**Comment by MagnaMike** [comment]
@zmathiasz Well... you're not *wrong*. But the hatching makes it look like you've used greys. I don't know about this...

@dreamnet :question:

**Comment by dreamnet** [comment]
I would prefer to do this one simply solid:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7100582/39ce1b40-e02b-11e4-8ec3-ffd55024a8a0.png)
https://cloud.githubusercontent.com/assets/2068130/7100582/39ce1b40-e02b-11e4-8ec3-ffd55024a8a0.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7100583/495bee20-e02b-11e4-99d3-a5f99341b181.png
