### ISSUE TITLE
NightShot –x Night Vision Slow Shutter Speed Photography (Photos and Videos in low light)

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5543]
**App Name:** NightShot –x Night Vision Slow Shutter Speed Photography (Photos and Videos in low light)
**Bundle ID:** com.studeo4ios.xnightvision
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=787777915">787777915</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nightshot-x-night-vision-slow/id787777915?mt=8&uo=4">https://itunes.apple.com/us/app/nightshot-x-night-vision-slow/id787777915?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** George Agbalyan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/studeo410/id436761184?uo=4>© Studeo410</a>
**Supported Devices:** iPad2Wifi, iPhone4S, iPhone6Plus, iPhone6, iPodTouchFourthGen, iPadFourthGen4G, iPhone-3GS, iPhone5s, iPadFourthGen, iPhone4, iPhone5, iPadMini4G, iPodTouchFifthGen, iPad23G, iPadThirdGen4G, iPadMini, iPadThirdGen, iPhone5c
**Original Artwork:**
<img src="http://a420.phobos.apple.com/us/r30/Purple/v4/cb/fe/39/cbfe39a8-d659-c3ba-d968-7fd96ebcefc5/mzl.zuzclzuk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7104466/3ece7244-e0e3-11e4-8972-528368032d03.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7102862/9fbb3928-e090-11e4-92ff-cdb2f3bfc937.png)
https://cloud.githubusercontent.com/assets/2068130/7102862/9fbb3928-e090-11e4-92ff-cdb2f3bfc937.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7102868/b085dff6-e090-11e4-8837-c9278ea2f781.png
Pffffhhhhh..... I don't know....

**Comment by Trubbel** [comment]
@dreamnet I think it looks great.

**Comment by MagnaMike** [comment]
Wow @dreamnet!

**Comment by Hack4Life** [comment]
It's awesome @dreamnet!

**Comment by dreamnet** [comment]
@Trubbel @MagnaMike @Hack4Life Thanks!
