### ISSUE TITLE
Camu - Camera for simply perfect pictures

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5544]
**App Name:** Camu - Camera for simply perfect pictures
**Bundle ID:** com.sumoing.gcam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=667415000">667415000</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camu-camera-for-simply-perfect/id667415000?mt=8&uo=4">https://itunes.apple.com/us/app/camu-camera-for-simply-perfect/id667415000?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Sumoing Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sumoing-ltd/id542324637?uo=4>© Sumoing Ltd</a>
**Supported Devices:** iPadThirdGen4G, iPad23G, iPhone4, iPhone6, iPad2Wifi, iPhone4S, iPadMini4G, iPodTouchFifthGen, iPadFourthGen, iPadMini, iPhone6Plus, iPadFourthGen4G, iPhone5s, iPhone5c, iPhone5, iPadThirdGen
**Original Artwork:**
<img src="http://a1453.phobos.apple.com/us/r30/Purple5/v4/d5/31/e4/d531e42f-3f0c-9792-2be7-659e21f8351a/mzl.wdznkdkv.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7100334/3cddc54c-e01c-11e4-94b4-63dc84e03b74.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7100334/3cddc54c-e01c-11e4-94b4-63dc84e03b74.png)
https://cloud.githubusercontent.com/assets/2068130/7100334/3cddc54c-e01c-11e4-94b4-63dc84e03b74.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7100336/4fd8ea14-e01c-11e4-98fa-e426b68472ea.png
