### ISSUE TITLE
Picr - Everyday photo reminder - selfie journal / diary

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5545]
**App Name:** Picr - Everyday photo reminder - selfie journal / diary
**Bundle ID:** com.MobileAppVault.Picr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=778479025">778479025</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/picr-everyday-photo-reminder/id778479025?mt=8&uo=4">https://itunes.apple.com/us/app/picr-everyday-photo-reminder/id778479025?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Marcus Rumbohm
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/marcus-rumbohm/id499051398?uo=4>© Marcus Rumbohm</a>
**Supported Devices:** iPhone5, iPad23G, iPhone4S, iPodTouchFifthGen, iPhone4, iPadMini4G, iPhone5s, iPadThirdGen4G, iPad2Wifi, iPadMini, iPhone6, iPadThirdGen, iPadFourthGen, iPhone5c, iPhone6Plus, iPadFourthGen4G
**Original Artwork:**
<img src="http://a1691.phobos.apple.com/us/r30/Purple4/v4/20/03/8e/20038ea8-d772-2de5-d4ac-2bb14152312c/mzl.erpbmpmi.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7100527/0342ea68-e028-11e4-8561-d8eaaa588f47.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7100527/0342ea68-e028-11e4-8561-d8eaaa588f47.png)
https://cloud.githubusercontent.com/assets/2068130/7100527/0342ea68-e028-11e4-8561-d8eaaa588f47.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7100529/0d37507c-e028-11e4-8b76-fb9196334c35.png
