### ISSUE TITLE
Cineplexx

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5546]
**App Name:** Cineplexx
**Bundle ID:** at.itpm.cineplexx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478265422">478265422</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/cineplexx/id478265422?mt=8&uo=4">https://itunes.apple.com/de/app/cineplexx/id478265422?mt=8&uo=4</a>
**App Version:** 3.1.3
**Seller:** CINEPLEXX Kinobetriebe Gesellschaft m.b.H.
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/cineplexx/id838963491?uo=4>© Cineplexx</a>
**Supported Devices:** iPadThirdGen4G, iPhone5s, iPhone4S, iPadFourthGen4G, iPhone6, iPhone5c, iPadMini, iPhone6Plus, iPodTouchFifthGen, iPadThirdGen, iPodTouchFourthGen, iPhone-3GS, iPadFourthGen, iPadMini4G, iPad23G, iPad2Wifi, iPhone5, iPhone4
**Original Artwork:**
<img src="http://a892.phobos.apple.com/us/r30/Purple3/v4/83/fa/5b/83fa5b7f-02c3-8f3c-98f4-34a2b5aaae35/mzl.pvkknzqg.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/7058908/409dcdcc-de36-11e4-94d2-a80712683475.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/7058908/409dcdcc-de36-11e4-94d2-a80712683475.png)
https://cloud.githubusercontent.com/assets/10950389/7058908/409dcdcc-de36-11e4-94d2-a80712683475.png
Source:
https://cloud.githubusercontent.com/assets/10950389/7058912/4b87ec4a-de36-11e4-9d77-0110251c2c16.png
