### ISSUE TITLE
Brother iPrint&Scan

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5548]
**App Name:** Brother iPrint&Scan
**Bundle ID:** com.brother.iPrint-Scan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382775642">382775642</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/brother-iprint-scan/id382775642?mt=8&uo=4">https://itunes.apple.com/us/app/brother-iprint-scan/id382775642?mt=8&uo=4</a>
**App Version:** 3.8.2
**Seller:** Brother Industries, LTD.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/brother-industries-ltd./id382775645?uo=4>© Brother Industries, LTD.</a>
**Supported Devices:** iPadMini, iPhone4S, iPadFourthGen4G, iPadMini4G, iPad2Wifi, iPhone6, iPadThirdGen, iPhone6Plus, iPadFourthGen, iPhone5s, iPadThirdGen4G, iPodTouchFifthGen, iPhone4, iPad23G, iPhone5, iPhone5c
**Original Artwork:**
<img src="http://a1738.phobos.apple.com/us/r30/Purple3/v4/fe/03/cc/fe03cc4c-a438-e03b-5f72-a33729a84018/mzl.eltuwtgk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7212427/fbc43c4e-e566-11e4-9a7a-0ac88ffb076b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7212427/fbc43c4e-e566-11e4-9a7a-0ac88ffb076b.png)
https://cloud.githubusercontent.com/assets/2068130/7212427/fbc43c4e-e566-11e4-9a7a-0ac88ffb076b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7212432/0d301476-e567-11e4-9693-c57e4b4a794c.png
