### ISSUE TITLE
Mushrooms LITE - NATURE MOBILE - For Safe Enjoyment!

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5549]
**App Name:** Mushrooms LITE - NATURE MOBILE - For Safe Enjoyment!
**Bundle ID:** com.alphablind.mushrooms.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=689909338">689909338</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mushrooms-lite-nature-mobile/id689909338?mt=8&uo=4">https://itunes.apple.com/us/app/mushrooms-lite-nature-mobile/id689909338?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** NATURE MOBILE G.m.b.H.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nature-mobile-g.m.b.h./id964511943?uo=4>© NATURE MOBILE G.m.b.H.</a>
**Supported Devices:** iPadThirdGen, iPhone6, iPhone4S, iPadFourthGen, iPadFourthGen4G, iPad2Wifi, iPadMini4G, iPhone6Plus, iPodTouchFourthGen, iPodTouchFifthGen, iPhone5s, iPhone-3GS, iPhone4, iPhone5, iPadThirdGen4G, iPad23G, iPhone5c, iPadMini
**Original Artwork:**
<img src="http://a995.phobos.apple.com/us/r30/Purple5/v4/e2/d4/d0/e2d4d057-638f-a58d-a53d-c3a68f6ff285/mzl.ogjinyrl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7079299/cf93695a-df22-11e4-85a5-d868ad967bed.png)

**Comment by dreamnet** [comment]
This is the lite version of #5538.

**Comment by MagnaMike** [comment]
@dreamnet's Icon from #5538:

---
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7079299/cf93695a-df22-11e4-85a5-d868ad967bed.png)
https://cloud.githubusercontent.com/assets/2068130/7079299/cf93695a-df22-11e4-85a5-d868ad967bed.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7079313/e6b66a74-df22-11e4-9710-0bf741cc23af.PNG
