### ISSUE TITLE
Elasticam - Warp Melt Deform Photos

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#555]
**App Name:** Elasticam - Warp Melt Deform Photos
**Bundle ID:** com.iphoneclan.elastify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=579803125">579803125</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/elasticam-warp-melt-deform/id579803125?mt=8&uo=4">https://itunes.apple.com/us/app/elasticam-warp-melt-deform/id579803125?mt=8&uo=4</a>
**App Version:** 2.02
**Seller:** Sylwester Los
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lucky-clan/id294866851?mt=8&uo=4>© Lucky Clan</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/85/a4/4e/85a44eaa-ee1f-caad-a968-f6a50289e120/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18746357/2ed9269c-80c7-11e6-8ea4-e2bc5ccaaf26.png)

**Comment by GMVargas** [comment]
Needs update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18746357/2ed9269c-80c7-11e6-8ea4-e2bc5ccaaf26.png)
https://cloud.githubusercontent.com/assets/20930745/18746357/2ed9269c-80c7-11e6-8ea4-e2bc5ccaaf26.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18746365/3fe19780-80c7-11e6-85f3-6e61778c043f.png
