### ISSUE TITLE
Credit Sesame - Your free credit score and free credit monitoring!

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5550]
**App Name:** Credit Sesame - Your free credit score and free credit monitoring!
**Bundle ID:** com.creditsesame.mobile.ios.finance
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476718980">476718980</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/credit-sesame-your-free-credit/id476718980?mt=8&uo=4">https://itunes.apple.com/us/app/credit-sesame-your-free-credit/id476718980?mt=8&uo=4</a>
**App Version:** 2.7.3
**Seller:** Credit Sesame, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/credit-sesame-inc./id476718983?uo=4>© Credit Sesame, Inc.</a>
**Supported Devices:** iPhone5s, iPadFourthGen, iPhone4, iPad2Wifi, iPhone6Plus, iPadMini, iPodTouchFifthGen, iPhone5c, iPhone4S, iPadFourthGen4G, iPadThirdGen4G, iPad23G, iPhone5, iPhone-3GS, iPadThirdGen, iPadMini4G, iPodTouchFourthGen, iPhone6
**Original Artwork:**
<img src="http://a322.phobos.apple.com/us/r30/Purple5/v4/f6/ee/07/f6ee07f3-1ba3-43ec-d321-13f09077b5ad/mzl.ydlysnvr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7079803/2f09dbfc-df29-11e4-84cc-fec3a8989e4e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7079803/2f09dbfc-df29-11e4-84cc-fec3a8989e4e.png)
https://cloud.githubusercontent.com/assets/2068130/7079803/2f09dbfc-df29-11e4-84cc-fec3a8989e4e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7079809/46bbca62-df29-11e4-8ea2-fb52184a8d4a.png
