### ISSUE TITLE
Fresh Air - Beautiful, personalized weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5551]
**App Name:** Fresh Air - Beautiful, personalized weather
**Bundle ID:** com.backcountrystudios.WeatherOrNot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=933439687">933439687</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fresh-air-beautiful-personalized/id933439687?mt=8&uo=4">https://itunes.apple.com/us/app/fresh-air-beautiful-personalized/id933439687?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Backcountry Studios LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/backcountry-studios-llc/id884591437?uo=4>© Backcountry Studios LLC</a>
**Supported Devices:** iPadThirdGen, iPadFourthGen, iPhone6Plus, iPhone5s, iPadFourthGen4G, iPad23G, iPhone6, iPad2Wifi, iPadThirdGen4G, iPadMini4G, iPodTouchFifthGen, iPhone5, iPhone4, iPadMini, iPhone4S, iPhone5c
**Original Artwork:**
<img src="http://a1046.phobos.apple.com/us/r30/Purple1/v4/bb/ea/0c/bbea0cdf-936b-3b03-c805-ee30c99afd3f/mzl.qtwcaqzx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7100478/52dec906-e024-11e4-94be-0fc8c7f0835c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7100461/b06b2656-e023-11e4-8525-e6a6d70c4cab.png)
https://cloud.githubusercontent.com/assets/2068130/7100461/b06b2656-e023-11e4-8525-e6a6d70c4cab.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7100464/c1590f96-e023-11e4-8694-a74364cae24b.png
:question:

**Comment by MagnaMike** [comment]
@dreamnet Not sure, but I can't think of another way to do it...

**Comment by dreamnet** [comment]
@MagnaMike Well... I take it.
