### ISSUE TITLE
Shou

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#5556]
**App Name:** Shou
 **Bundle ID:**  tv.shou.recorder
 **iTunes ID:** none (Cydia app)
 **Original Artwork:** 
<img src="https://cloud.githubusercontent.com/assets/3600371/7102812/a37fccf8-e096-11e4-8984-e2fc5b385d3e.png" width="150" height="150" />
 **Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7102969/c86834ae-e093-11e4-9629-3c0491380bd9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7102959/613cf13e-e093-11e4-847d-9b8be0b434cb.png)
https://cloud.githubusercontent.com/assets/2068130/7102959/613cf13e-e093-11e4-847d-9b8be0b434cb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7102962/70458768-e093-11e4-8250-21582518bc40.png
