### ISSUE TITLE
ZenMate for iOS8 | The best VPN for Privacy, Data Compression, Encryption and Web Proxy

### ISSUE THREAD

**Issue by jasonsmaug** [glasklart/hd#5557]
**App Name:** ZenMate for iOS8 | The best VPN for Privacy, Data Compression, Encryption and Web Proxy
**Bundle ID:** com.zenmate.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=903380113">903380113</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zenmate-for-ios8-best-vpn/id903380113?mt=8&uo=4">https://itunes.apple.com/us/app/zenmate-for-ios8-best-vpn/id903380113?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** ZenGuard GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/zenguard/id859312809?uo=4>© ZenGuard</a>
**Supported Devices:** iPodTouchFifthGen, iPhone5, iPadFourthGen4G, iPhone6Plus, iPhone6, iPadMini4G, iPadThirdGen, iPhone4S, iPadThirdGen4G, iPadMini, iPad2Wifi, iPhone5c, iPad23G, iPadFourthGen, iPhone5s
**Original Artwork:**
<img src="http://a286.phobos.apple.com/us/r30/Purple5/v4/b1/b1/95/b1b1954f-f721-cc67-45af-33ac07f9dcd8/mzl.qxxqoocv.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7104386/b8e356d6-e0dd-11e4-9ed3-ab32f8c21661.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7104386/b8e356d6-e0dd-11e4-9ed3-ab32f8c21661.png)
https://cloud.githubusercontent.com/assets/2068130/7104386/b8e356d6-e0dd-11e4-9ed3-ab32f8c21661.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7104388/c804c938-e0dd-11e4-8bd9-d03d7f558be7.png

**Comment by jasonsmaug** [comment]
Thanks man
How about the ufc tv and cinema 21?
Thats the only icons that not themed in my first page homescreen

**Comment by MagnaMike** [comment]
@jasonsmaug Please submit them as a new individual icon request. Thanks!

**Comment by dreamnet** [comment]
@jasonsmaug We will do it if we find the time. :watch:

**Comment by MagnaMike** [comment]
@dreamnet Yeah time is something I have little of at the moment. Exam time at school! :school:

**Comment by dreamnet** [comment]
@MagnaMike You are a great help anyway - good luck for the exam! :four_leaf_clover:
