### ISSUE TITLE
Cinema 21

### ISSUE THREAD

**Issue by jasonsmaug** [glasklart/hd#5559]
**App Name:** Cinema 21
**Bundle ID:** com.21cineplex.cinema21
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=784387995">784387995</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cinema-21/id784387995?uo=4">https://apps.apple.com/us/app/cinema-21/id784387995?uo=4</a>
**App Version:** 4.0.1
**Seller:** Nusantara Sejahtera Raya, Pt
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nusantara-sejahtera-raya-pt/id1166849797?uo=4">© Nusantara Sejahtera Raya, PT</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/04/33/0f/04330fe1-0fc3-d971-1761-9309411db165/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60372742-f6543480-99fd-11e9-8990-a22a6d3a9742.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7107263/6a9db57e-e160-11e4-9a43-fa20bfe0afe7.png)
https://cloud.githubusercontent.com/assets/2068130/7107263/6a9db57e-e160-11e4-9a43-fa20bfe0afe7.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7107265/7801ca02-e160-11e4-8246-168e9bd63780.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60372742-f6543480-99fd-11e9-8990-a22a6d3a9742.png)
https://user-images.githubusercontent.com/20930745/60372742-f6543480-99fd-11e9-8990-a22a6d3a9742.png

Source:
https://user-images.githubusercontent.com/20930745/60372744-f9e7bb80-99fd-11e9-8f44-f476457ae323.png
