### ISSUE TITLE
iRigs - Carp Fishing Rigs by iAngler

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#556]
**App Name:** iRigs - Carp Fishing Rigs by iAngler
**Bundle ID:** co.uk.i-angler.i-rigs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386764425">386764425</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/irigs-carp-fishing-rigs-by/id386764425?mt=8&uo=4">https://itunes.apple.com/us/app/irigs-carp-fishing-rigs-by/id386764425?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** iAngler LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/iangler/id386764428?uo=4">© iAngler</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/f3/56/86/f356862e-402f-b3f0-d8b9-5862330c6dac/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20239981/75b0c246-a90d-11e6-9b03-570929a4516f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20239981/75b0c246-a90d-11e6-9b03-570929a4516f.png)
https://cloud.githubusercontent.com/assets/20930745/20239981/75b0c246-a90d-11e6-9b03-570929a4516f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20239984/939ca37e-a90d-11e6-87cc-44c89081bcc0.png
