### ISSUE TITLE
BCA Mobile

### ISSUE THREAD

**Issue by jasonsmaug** [glasklart/hd#5560]
**App Name:** BCA mobile
**Bundle ID:** com.bca.bcamobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=551587254">551587254</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bca-mobile/id551587254?mt=8&uo=4">https://itunes.apple.com/us/app/bca-mobile/id551587254?mt=8&uo=4</a>
**App Version:** 1.0.8
**Seller:** PT Bank Central Asia Tbk.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pt.-bank-central-asia-tbk/id551587257?uo=4>© PT. Bank Central Asia Tbk</a>
**Supported Devices:** iPhone5, iPodTouchThirdGen, iPodTouchFifthGen, iPhone6, iPadThirdGen4G, iPhone5s, iPhone4, iPadMini, iPadThirdGen, iPhone5c, iPadFourthGen4G, iPad23G, iPhone-3GS, iPhone6Plus, iPodTouchFourthGen, iPad3G, iPad2Wifi, iPadWifi, iPhone4S, iPadFourthGen, iPadMini4G
**Original Artwork:**
<img src="http://a1583.phobos.apple.com/us/r30/Purple3/v4/ab/e0/4f/abe04f7a-639a-8020-5379-54cbf58d0cc1/mzl.xvehxgkb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7104377/8516ac64-e0dc-11e4-8f1b-c4ee756e9d17.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7104377/8516ac64-e0dc-11e4-8f1b-c4ee756e9d17.png)
https://cloud.githubusercontent.com/assets/2068130/7104377/8516ac64-e0dc-11e4-8f1b-c4ee756e9d17.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7104378/9469afae-e0dc-11e4-9b7e-9c776d2691ea.png
