### ISSUE TITLE
Movreak

### ISSUE THREAD

**Issue by jasonsmaug** [glasklart/hd#5561]
**App Name:** Movreak
**Bundle ID:** com.dycode.MovreakFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=434597770">434597770</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/movreak/id434597770?mt=8&uo=4">https://itunes.apple.com/us/app/movreak/id434597770?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** Dycode Cominfotech Development, PT.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dycode-cominfotech-development/id370800331?uo=4>© Dycode Cominfotech Development, PT.</a>
**Supported Devices:** iPadFourthGen4G, iPhone6Plus, iPad23G, iPadFourthGen, iPodTouchFifthGen, iPhone5, iPhone6, iPadMini, iPad2Wifi, iPodTouchFourthGen, iPadThirdGen, iPhone4, iPadThirdGen4G, iPhone-3GS, iPhone5s, iPhone5c, iPadMini4G, iPhone4S
**Original Artwork:**
<img src="http://a1931.phobos.apple.com/us/r30/Purple6/v4/04/92/1d/04921db1-f752-eb75-0552-443f2cf97691/mzl.ulwojubw.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7107223/c7c4b6aa-e15e-11e4-8530-d22b2ab9c1fc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7107223/c7c4b6aa-e15e-11e4-8530-d22b2ab9c1fc.png)
https://cloud.githubusercontent.com/assets/2068130/7107223/c7c4b6aa-e15e-11e4-8530-d22b2ab9c1fc.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7107225/d559731e-e15e-11e4-9ca9-de7a783621da.png
