### ISSUE TITLE
Acorns - Invest Spare Change into Stocks

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5562]
**App Name:** Acorns - Invest Spare Change into Stocks
**Bundle ID:** com.acorns.investor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=883324671">883324671</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/acorns-invest-spare-change/id883324671?mt=8&uo=4">https://itunes.apple.com/us/app/acorns-invest-spare-change/id883324671?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** Acorns Grow Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/acorns/id883324674?uo=4>© Acorns</a>
**Supported Devices:** iPad23G, iPhone5c, iPhone4, iPodTouchFifthGen, iPadThirdGen4G, iPhone6Plus, iPhone5s, iPadThirdGen, iPadFourthGen, iPadMini, iPad2Wifi, iPadFourthGen4G, iPadMini4G, iPhone6, iPhone5, iPhone4S
**Original Artwork:**
<img src="http://a772.phobos.apple.com/us/r30/Purple3/v4/b0/19/fb/b019fb0f-edcc-4432-0a28-467da40b1974/pr_source.png?downloadKey=1428846022_e7f7d14eab99b64b42329bec12730e4c" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7105822/0d3c7dcc-e12c-11e4-9c3d-07e03532fbcc.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7105822/0d3c7dcc-e12c-11e4-9c3d-07e03532fbcc.png)
https://cloud.githubusercontent.com/assets/10730122/7105822/0d3c7dcc-e12c-11e4-9c3d-07e03532fbcc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7105821/03bafd46-e12c-11e4-9a97-fbe3cb917164.png

**Comment by MagnaMike** [comment]
@Trubbel Yep!
