### ISSUE TITLE
MORTAL KOMBAT X

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5563]
**App Name:** MORTAL KOMBAT X
**Bundle ID:** com.wb.MK.Brawler2015
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=949701151">949701151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mortal-kombat-x/id949701151?mt=8&uo=4">https://itunes.apple.com/us/app/mortal-kombat-x/id949701151?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Warner Bros. Entertainment
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/warner-bros./id298372283?uo=4>© Warner Bros.</a>
**Supported Devices:** iPad23G, iPhone4S, iPadThirdGen4G, iPhone5c, iPodTouchFifthGen, iPadFourthGen, iPodTouchFourthGen, iPadThirdGen, iPhone6Plus, iPhone6, iPhone5, iPad2Wifi, iPadMini, iPhone5s, iPadFourthGen4G, iPadMini4G, iPhone4
**Original Artwork:**
<img src="http://a911.phobos.apple.com/us/r30/Purple1/v4/05/c3/64/05c364c3-8718-106b-0711-d45de51c651d/pr_source.png?downloadKey=1428856976_a2da4050cff18ce037c386b7bbda912f" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7105792/3d8483b8-e12b-11e4-8ad6-4398504be85f.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7105792/3d8483b8-e12b-11e4-8ad6-4398504be85f.png)
https://cloud.githubusercontent.com/assets/10730122/7105792/3d8483b8-e12b-11e4-8ad6-4398504be85f.png
-- --
Source:
https://cloud.githubusercontent.com/assets/10730122/7105790/30a44692-e12b-11e4-816f-a2b634d36e31.png

**Comment by MagnaMike** [comment]
@Trubbel That'll do!
