### ISSUE TITLE
Glass Planner

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5564]
**App Name:** Glass Planner
**Bundle ID:** com.sliderulesoftware.Glass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=902262764">902262764</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glass-planner/id902262764?mt=8&uo=4">https://itunes.apple.com/us/app/glass-planner/id902262764?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Slide Rule Software
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/slide-rule-software/id902262767?uo=4>© Slide Rule Software</a>
**Supported Devices:** iPhone5s, iPadMini4G, iPhone4S, iPhone5, iPhone4, iPodTouchFourthGen, iPadThirdGen, iPhone5c, iPadMini, iPhone-3GS, iPhone6Plus, iPadThirdGen4G, iPadFourthGen, iPhone6, iPad2Wifi, iPadFourthGen4G, iPodTouchFifthGen, iPad23G
**Original Artwork:**
<img src="http://a579.phobos.apple.com/us/r30/Purple3/v4/35/a1/d3/35a1d31c-a8b8-2c59-145f-2491c21ffd11/mzl.jnatqwty.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7105846/5826ab90-e12d-11e4-897f-64af51a96f63.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7105846/5826ab90-e12d-11e4-897f-64af51a96f63.png)
https://cloud.githubusercontent.com/assets/10730122/7105846/5826ab90-e12d-11e4-897f-64af51a96f63.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7105845/4c0ffbea-e12d-11e4-813f-29496e0e72b0.png

**Comment by MagnaMike** [comment]
@Trubbel :+1:
