### ISSUE TITLE
ForeFlight Mobile

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5565]
**App Name:** ForeFlight Mobile
**Bundle ID:** com.foreflight.ForeFlightMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=333252638">333252638</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/foreflight-mobile/id333252638?mt=8&uo=4">https://itunes.apple.com/us/app/foreflight-mobile/id333252638?mt=8&uo=4</a>
**App Version:** 6.8
**Seller:** ForeFlight, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/foreflight/id283512699?uo=4>© ForeFlight</a>
**Supported Devices:** iPadFourthGen, iPadFourthGen4G, iPadThirdGen4G, iPhone6Plus, iPhone5, iPodTouchFifthGen, iPhone4S, iPhone5s, iPad2Wifi, iPadThirdGen, iPad23G, iPhone5c, iPadMini4G, iPhone6, iPadMini
**Original Artwork:**
<img src="http://a672.phobos.apple.com/us/r30/Purple1/v4/20/ec/5e/20ec5ebc-bfb9-6424-c9ff-4d40410a127e/mzl.ctskiliq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7107233/4ba365ca-e15f-11e4-902b-5149b86a6b8c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7107233/4ba365ca-e15f-11e4-902b-5149b86a6b8c.png)
https://cloud.githubusercontent.com/assets/2068130/7107233/4ba365ca-e15f-11e4-902b-5149b86a6b8c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7107234/5997dd14-e15f-11e4-94da-27bd1f9c3ab9.png
