### ISSUE TITLE
Belly - Free Stuff You'll Love - World's Best Rewards Program for Loyal Customers Like You!

### ISSUE THREAD

**Issue by KickBooty** [glasklart/hd#5566]
**App Name:** Belly - Free Stuff You'll Love - World's Best Rewards Program for Loyal Customers Like You!
**Bundle ID:** com.lightbank.bellyflopbeta
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445221346">445221346</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/belly-free-stuff-youll-love/id445221346?mt=8&uo=4">https://itunes.apple.com/us/app/belly-free-stuff-youll-love/id445221346?mt=8&uo=4</a>
**App Version:** 3.2.4
**Seller:** Belly Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/belly-inc./id445221349?uo=4>© Belly Inc.</a>
**Supported Devices:** iPadFourthGen4G, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPhone5s, iPhone5, iPhone6, iPodTouchFifthGen, iPadFourthGen, iPhone5c, iPadThirdGen, iPadThirdGen4G, iPhone6Plus, iPhone-3GS, iPadMini4G, iPhone4, iPadMini
**Original Artwork:**
<img src="http://a47.phobos.apple.com/us/r30/Purple3/v4/55/81/de/5581de9e-e0e0-2ec7-1232-2b9f0e08516c/mzl.emskraji.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7130715/74a05958-e275-11e4-8740-0dbe8853089d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7130715/74a05958-e275-11e4-8740-0dbe8853089d.png)
https://cloud.githubusercontent.com/assets/2068130/7130715/74a05958-e275-11e4-8740-0dbe8853089d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7130720/85ad5804-e275-11e4-998b-54b220f8345e.png

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7131324/426cc58e-e243-11e4-9fe8-73bc0eaf5167.png)
https://cloud.githubusercontent.com/assets/3090247/7131324/426cc58e-e243-11e4-9fe8-73bc0eaf5167.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7131325/426ce73a-e243-11e4-91d1-cc27f4167f7f.png
