### ISSUE TITLE
Legend for Messenger - Send Text in Animated GIF

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5567]
**App Name:** Legend for Messenger - Send Text in Animated GIF
**Bundle ID:** com.stupeflix.legend.messenger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=966974388">966974388</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/legend-for-messenger-send/id966974388?mt=8&uo=4">https://itunes.apple.com/us/app/legend-for-messenger-send/id966974388?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Stupeflix
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/stupeflix/id491145674?uo=4>© Stupeflix</a>
**Supported Devices:** iPhone4S, iPhone6Plus, iPhone5c, iPadFourthGen, iPad23G, iPad2Wifi, iPhone6, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5s, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a165.phobos.apple.com/us/r30/Purple1/v4/91/11/37/911137b5-b857-df57-46a0-e797fcc58486/pr_source.png?downloadKey=1428926379_39415053c4e21e6e75f3115021579307" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7130829/fb10ddfe-e276-11e4-8de9-e1b81a5f5f8f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7130829/fb10ddfe-e276-11e4-8de9-e1b81a5f5f8f.png)
https://cloud.githubusercontent.com/assets/2068130/7130829/fb10ddfe-e276-11e4-8de9-e1b81a5f5f8f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7130836/0c46246c-e277-11e4-8ac9-0790a678c4ef.png
