### ISSUE TITLE
BundleIDs

### ISSUE THREAD

**Issue by jakaspain** [glasklart/hd#5568]
**App Name:** BundleIDs
**Bundle ID:** com.sassoty.bundleids
**iTunes ID:** (Cydia app)
**Repo:** Bigboss
<img src="https://cloud.githubusercontent.com/assets/11922062/7112983/930683f8-e1f9-11e4-986e-6f883884db45.png" width="150" height="150">
 **Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7166707/bdd2c774-e3af-11e4-8efa-4f3b8e361b9b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7166707/bdd2c774-e3af-11e4-8efa-4f3b8e361b9b.png)
https://cloud.githubusercontent.com/assets/2068130/7166707/bdd2c774-e3af-11e4-8efa-4f3b8e361b9b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7166722/d9207670-e3af-11e4-909b-621c5b460b42.png
