### ISSUE TITLE
iModGame

### ISSUE THREAD

**Issue by jakaspain** [glasklart/hd#5569]
**App Name:** iModGame
**Bundle ID:** com.nadis.iModgame.net
**iTunes ID:** (Cydia app)
**Repo:** Cydia.imodgame.net
<img src="https://cloud.githubusercontent.com/assets/2068130/7130994/9fbe49ca-e279-11e4-81eb-43ccb5b2d300.png" width="150" height="150">
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7133754/0a1f8342-e25c-11e4-9bfe-58c322307108.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7133754/0a1f8342-e25c-11e4-9bfe-58c322307108.png)
https://cloud.githubusercontent.com/assets/3090247/7133754/0a1f8342-e25c-11e4-9bfe-58c322307108.png


---
Source:
https://cloud.githubusercontent.com/assets/3090247/7133761/1c13e11a-e25c-11e4-99fd-c239b9734aac.png)

**Comment by dreamnet** [comment]
@ivanov007 Perfect! :+1:
