### ISSUE TITLE
AutoTouch

### ISSUE THREAD

**Issue by jakaspain** [glasklart/hd#5570]
**App Name:** AutoTouch
**Bundle ID:** me.autotouch.AutoTouch.ios8
**iTunes ID:** (Cydia app)
**Repo:**: Bigboss
<img src="https://cloud.githubusercontent.com/assets/11922062/7113092/8cce56e0-e1fa-11e4-9c57-ea9db4a1c23e.png" width="150" height="150">
 **Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/7129247/81e62e4e-e298-11e4-8206-f1f869c508ad.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/7129247/81e62e4e-e298-11e4-8206-f1f869c508ad.png)
https://cloud.githubusercontent.com/assets/10008202/7129247/81e62e4e-e298-11e4-8206-f1f869c508ad.png
**Source**
https://cloud.githubusercontent.com/assets/10008202/7129252/92e7d904-e298-11e4-8c1f-29e83ccf551e.png

**Comment by ivanov007** [comment]
@iNfeCtGFX :+1:

**Comment by zmathiasz** [comment]
@dreamnet Just a correction.  The bundle ID is name wrong in the master.

It is listed as: e.autotouch.AutoTouch.ios8

Should be: me.autotouch.AutoTouch.ios8

**Comment by ivanov007** [comment]
@zmathiasz  nice catch :+1:

**Comment by dreamnet** [comment]
Wups.... :stuck_out_tongue_winking_eye:
