### ISSUE TITLE
Blue Bird Group Taxi Mobile Reservation

### ISSUE THREAD

**Issue by jakaspain** [glasklart/hd#5571]
**App Name:** Blue Bird Group Taxi Mobile Reservation
**Bundle ID:** com.seatechmobile.bluebird.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476533261">476533261</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blue-bird-group-taxi-mobile/id476533261?mt=8&uo=4">https://itunes.apple.com/us/app/blue-bird-group-taxi-mobile/id476533261?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** seatech
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/seatech/id316700071?uo=4>© Seatech</a>
**Supported Devices:** iPhone4, iPad23G, iPadMini, iPhone5s, iPhone5c, iPhone5, iPadMini4G, iPadThirdGen, iPad2Wifi, iPodTouchFourthGen, iPadThirdGen4G, iPadFourthGen4G, iPhone6Plus, iPhone4S, iPhone6, iPhone-3GS, iPodTouchFifthGen, iPadFourthGen
**Original Artwork:**
<img src="http://a1588.phobos.apple.com/us/r30/Purple5/v4/c5/a1/a5/c5a1a54b-0d90-69e9-be50-ef25bbedd18f/pr_source.png?downloadKey=1428928346_f97d8f788f03031c12c2067a1a5c324f" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7130975/46ffe29e-e279-11e4-8ea6-3a4fca8ccdcb.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/7129591/658106c0-e29d-11e4-8427-d5bd3be1f40d.png)
https://cloud.githubusercontent.com/assets/10008202/7129591/658106c0-e29d-11e4-8427-d5bd3be1f40d.png
**Source**
https://cloud.githubusercontent.com/assets/10008202/7129594/71d50ac0-e29d-11e4-8d2c-879eddbcabf3.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7130975/46ffe29e-e279-11e4-8ea6-3a4fca8ccdcb.png)
https://cloud.githubusercontent.com/assets/2068130/7130975/46ffe29e-e279-11e4-8ea6-3a4fca8ccdcb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7130963/ffe0054c-e278-11e4-806c-174ff4ac0da8.png
:question:

**Comment by MagnaMike** [comment]
Taking @dreamnet's. I think it looks good since the white on the original goes to white (glasklart style).
