### ISSUE TITLE
AudioRecorder 2 (iOS 8)

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5572]
**App Name**: AudioRecorder 2 (iOS 8)
**Bundle ID**: net.limneos.AudioRecorder
**iTunes ID**: (Cydia app)
**Repo**: Limneos Repo (http://portal.hack4life.org/cydia/repos.php#17)
<img src="https://cloud.githubusercontent.com/assets/11788789/7121319/132208ae-e214-11e4-8e46-b27384576e8e.PNG" width="150" height="150">
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7164713/79f04a02-e3a2-11e4-82d5-6eed009cf701.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/7129356/4b57ff0e-e29a-11e4-822f-566b669f3403.png)
https://cloud.githubusercontent.com/assets/10008202/7129356/4b57ff0e-e29a-11e4-822f-566b669f3403.png
**Source**
https://cloud.githubusercontent.com/assets/10008202/7129363/58bd591e-e29a-11e4-821d-ebf29c0c66fe.png

**Comment by dreamnet** [comment]
Hmmm, I think the "red button" should be done in the original size.

**Comment by MagnaMike** [comment]
@dreamnet Agreed.

**Comment by dreamnet** [comment]
Here it is:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7164713/79f04a02-e3a2-11e4-82d5-6eed009cf701.png)
https://cloud.githubusercontent.com/assets/2068130/7164713/79f04a02-e3a2-11e4-82d5-6eed009cf701.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7164717/88346044-e3a2-11e4-91c7-910a9bb1ded4.png
