### ISSUE TITLE
Legend - Animate Text in Video & GIF

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5573]
**App Name:** Legend - Animate Text in Video & GIF
**Bundle ID:** com.stupeflix.legend
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=945320876">945320876</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/legend-animate-text-in-video/id945320876?mt=8&uo=4">https://itunes.apple.com/us/app/legend-animate-text-in-video/id945320876?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Stupeflix
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/stupeflix/id491145674?uo=4>© Stupeflix</a>
**Supported Devices:** iPadThirdGen4G, iPadThirdGen, iPadMini4G, iPhone6Plus, iPhone4S, iPhone5c, iPadFourthGen4G, iPhone5s, iPadFourthGen, iPhone6, iPad2Wifi, iPadMini, iPhone5, iPodTouchFifthGen, iPad23G
**Original Artwork:**
<img src="http://a1285.phobos.apple.com/us/r30/Purple3/v4/9f/74/cf/9f74cfbd-7cbe-a543-7c3c-525cbd76f1e1/mzl.zedxooke.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7131396/85fcbf1a-e244-11e4-88b9-e2959f4dab40.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7131396/85fcbf1a-e244-11e4-88b9-e2959f4dab40.png)
https://cloud.githubusercontent.com/assets/3090247/7131396/85fcbf1a-e244-11e4-88b9-e2959f4dab40.png
or
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7131397/8606fe58-e244-11e4-8cc5-e74414bd8c4b.png)
https://cloud.githubusercontent.com/assets/3090247/7131397/8606fe58-e244-11e4-8cc5-e74414bd8c4b.png

---
Sources:
https://cloud.githubusercontent.com/assets/3090247/7131399/860f4b58-e244-11e4-8d46-9146f0e6dff0.png
https://cloud.githubusercontent.com/assets/3090247/7131398/860f256a-e244-11e4-9df9-23bc9b6699d3.png

**Comment by dreamnet** [comment]
@ivanov007 Taking the first one. :+1:
