### ISSUE TITLE
WhiteTerminal

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5574]
**App Name:** WhiteTerminal
**Bundle ID:** com.codehex.whiteterminal.WhiteTerminal
**iTunes ID:** (Cydia app)
**Repo:** BigBoss
**Original Artwork:**
![img_8505](https://cloud.githubusercontent.com/assets/11788789/7134763/48e5f608-e2a0-11e4-822b-1f36c97ff64e.PNG)
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6876039/016f8954-d4c4-11e4-90af-6840cfc30133.png)

**Comment by ivanov007** [comment]
maybe something like this?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7152205/a1b0d918-e2fc-11e4-85c6-21b0edcc6ac7.png)
https://cloud.githubusercontent.com/assets/3090247/7152205/a1b0d918-e2fc-11e4-85c6-21b0edcc6ac7.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7152235/650e5b88-e2fd-11e4-90d0-497ec5b0649b.png

**Comment by MagnaMike** [comment]
@ivanov007 Why don't we just make it like #5429?

**Comment by dreamnet** [comment]
@ivanov007 @MagnaMike I think we can use the icon from #5429 because this apps seems to be nearly the same. - :question:

**Comment by MagnaMike** [comment]
@dreamnet Exactly, yeah.

**Comment by MagnaMike** [comment]
@dreamnet Your icon from #5429 

![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6876039/016f8954-d4c4-11e4-90af-6840cfc30133.png)
https://cloud.githubusercontent.com/assets/2068130/6876039/016f8954-d4c4-11e4-90af-6840cfc30133.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6876047/138a52e0-d4c4-11e4-9e54-bc234fdfc20e.png
