### ISSUE TITLE
[DUPLICATE of #4799]

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5575]
**App Name:** Hearthstone: Heroes of Warcraft
**Bundle ID:** com.blizzard.wtcg.hearthstone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=625257520">625257520</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hearthstone-heroes-warcraft/id625257520?mt=8&uo=4">https://itunes.apple.com/us/app/hearthstone-heroes-warcraft/id625257520?mt=8&uo=4</a>
**App Version:** 2.5.8416
**Seller:** Blizzard Entertainment, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/blizzard-entertainment-inc./id306862900?uo=4>© Blizzard Entertainment, Inc.</a>
**Supported Devices:** iPhone6Plus, iPhone4S, iPodTouchThirdGen, iPhone6, iPodTouchFifthGen, iPadFourthGen, iPadThirdGen4G, iPhone-3GS, iPadMini, iPhone4, iPadFourthGen4G, iPad3G, iPhone5c, iPadWifi, iPad2Wifi, iPad23G, iPadThirdGen, iPodTouchFourthGen, iPadMini4G, iPhone5, iPhone5s
**Original Artwork:**
<img src="http://a1818.phobos.apple.com/us/r30/Purple3/v4/b8/b5/20/b8b5201a-eade-6c21-05b8-12384e39b070/mzl.cwyjzhpr.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
@icecharger We aleady have an issue for this - #4799. It seems that this was an iPad only app and now it's also for iPhone. Anyway, I'm closing this issus and reopen the original one.
