### ISSUE TITLE
iPoll

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5576]
**App Name:** iPoll
**Bundle ID:** com.usamp.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=422370120">422370120</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ipoll/id422370120?mt=8&uo=4">https://itunes.apple.com/us/app/ipoll/id422370120?mt=8&uo=4</a>
**App Version:** 2.36
**Seller:** Instantly, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/instantly-inc./id422370123?uo=4>© Instantly, Inc.</a>
**Supported Devices:** iPhone4, iPhone6, iPhone-3GS, iPhone5, iPadMini4G, iPhone4S, iPadFourthGen4G, iPodTouchFifthGen, iPadMini, iPadFourthGen, iPhone5c, iPodTouchFourthGen, iPad23G, iPadThirdGen4G, iPad2Wifi, iPadThirdGen, iPhone5s, iPhone6Plus
**Original Artwork:**
<img src="http://a95.phobos.apple.com/us/r30/Purple1/v4/6b/cc/a1/6bcca1c2-01fd-a6f7-0908-52dff1cb0300/mzl.teexsdrl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7174392/91a875b0-e407-11e4-8bf1-a563a58b46fb.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/7173862/2ee1cd8c-e439-11e4-9eae-79bbeb6cd069.png)
https://cloud.githubusercontent.com/assets/10008202/7173862/2ee1cd8c-e439-11e4-9eae-79bbeb6cd069.png

**Comment by dreamnet** [comment]
@iNfeCtGFX Why not doing it this way?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7174392/91a875b0-e407-11e4-8bf1-a563a58b46fb.png)
https://cloud.githubusercontent.com/assets/2068130/7174392/91a875b0-e407-11e4-8bf1-a563a58b46fb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7174395/9e4071ec-e407-11e4-9741-175f53ce37e7.png
I'm tending to - when it's possible - make white or brighter colors in the original icon also white in the final Glasklart icon.

**Comment by WaterTrooper** [comment]
I'm tied. They both are kewl.

**Comment by MagnaMike** [comment]
@dreamnet I'm going to have to agree with you. I try to make the main part of the icon in glasklart style, so the P should be in glasklart style (like in your icon), instead of the background/baseplate.
