### ISSUE TITLE
Loopy

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5578]
**App Name:** Loopy
**Bundle ID:** com.tzisoftware.loopy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300257824">300257824</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/loopy/id300257824?mt=8&uo=4">https://itunes.apple.com/us/app/loopy/id300257824?mt=8&uo=4</a>
**App Version:** 2.5.11
**Seller:** A Tasty Pixel
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/a-tasty-pixel/id300257827?uo=4>© A Tasty Pixel</a>
**Supported Devices:** iPhone4, iPadThirdGen4G, iPodTouchFifthGen, iPhone4S, iPadFourthGen, iPhone5s, iPhone6Plus, iPhone6, iPadFourthGen4G, iPadMini, iPadMini4G, iPad2Wifi, iPadThirdGen, iPhone5, iPhone5c, iPad23G
**Original Artwork:**
<img src="http://a1732.phobos.apple.com/us/r30/Purple1/v4/0f/e3/13/0fe31359-c519-696b-42bd-caaca4cc8d22/mzl.iqhwenul.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7190663/035fdfc4-e488-11e4-91c4-90de2dc07b58.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7190663/035fdfc4-e488-11e4-91c4-90de2dc07b58.png)
https://cloud.githubusercontent.com/assets/2068130/7190663/035fdfc4-e488-11e4-91c4-90de2dc07b58.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7190672/110e10f0-e488-11e4-8fa1-c567d7801a97.png
