### ISSUE TITLE
Loopy HD

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5579]
**App Name:** Loopy HD
**Bundle ID:** com.atastypixel.loopy-hd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467923185">467923185</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/loopy-hd/id467923185?mt=8&uo=4">https://itunes.apple.com/us/app/loopy-hd/id467923185?mt=8&uo=4</a>
**App Version:** 1.4.11
**Seller:** A Tasty Pixel
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/a-tasty-pixel/id300257827?uo=4>© A Tasty Pixel</a>
**Supported Devices:** iPhone5s, iPhone4, iPadMini, iPad2Wifi, iPhone4S, iPhone5, iPadFourthGen, iPhone6, iPhone6Plus, iPadThirdGen4G, iPodTouchFifthGen, iPad23G, iPadMini4G, iPadThirdGen, iPhone5c, iPadFourthGen4G
**Original Artwork:**
<img src="http://a1456.phobos.apple.com/us/r30/Purple5/v4/61/fc/23/61fc2312-82aa-0f4f-b692-5eb136446051/mzl.ewruxore.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7190663/035fdfc4-e488-11e4-91c4-90de2dc07b58.png)

**Comment by dreamnet** [comment]
Same icon as for #5578.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7190663/035fdfc4-e488-11e4-91c4-90de2dc07b58.png)
https://cloud.githubusercontent.com/assets/2068130/7190663/035fdfc4-e488-11e4-91c4-90de2dc07b58.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7190672/110e10f0-e488-11e4-8fa1-c567d7801a97.png
