### ISSUE TITLE
Speak & Translate － Live Voice and Text Translator with Speech and Dictionary

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5580]
**App Name:** Speak & Translate － Live Voice and Text Translator with Speech and Dictionary
**Bundle ID:** com.appicfun.translator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=804637783">804637783</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/speak-translate-live-voice/id804637783?mt=8&uo=4">https://itunes.apple.com/us/app/speak-translate-live-voice/id804637783?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** IAC Search & Media Europe Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/apalon-apps/id749046894?uo=4>© Apalon Apps</a>
**Supported Devices:** iPadThirdGen, iPadMini, iPad23G, iPhone5c, iPhone4, iPhone5s, iPhone4S, iPadFourthGen, iPadMini4G, iPodTouchFifthGen, iPhone5, iPadThirdGen4G, iPhone6Plus, iPad2Wifi, iPadFourthGen4G, iPhone6
**Original Artwork:**
<img src="http://a647.phobos.apple.com/us/r30/Purple3/v4/3d/b8/5f/3db85f2f-85c6-244c-08de-52bf1e083fb1/mzl.ekxiuhzk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7189846/27d9e22e-e482-11e4-8e6f-f4596f918f5b.png)

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7189846/27d9e22e-e482-11e4-8e6f-f4596f918f5b.png)
https://cloud.githubusercontent.com/assets/2068130/7189846/27d9e22e-e482-11e4-8e6f-f4596f918f5b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7189856/3d4de9a2-e482-11e4-8759-5582e585cfe0.png
