### ISSUE TITLE
Must

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5581]
**App Name:** Must
**Bundle ID:** com.paul.mustapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926339451">926339451</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/must/id926339451?mt=8&uo=4">https://itunes.apple.com/us/app/must/id926339451?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** GPR Creative Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/must-app/id926325478?uo=4>© Must App</a>
**Supported Devices:** iPadFourthGen4G, iPodTouchFifthGen, iPadMini, iPhone5, iPad23G, iPhone4S, iPadFourthGen, iPhone4, iPadThirdGen, iPhone6, iPhone5s, iPadMini4G, iPhone6Plus, iPadThirdGen4G, iPad2Wifi, iPhone5c
**Original Artwork:**
<img src="http://a1566.phobos.apple.com/us/r30/Purple1/v4/32/d4/21/32d42183-343f-8520-26b4-fd7f851d2872/mzl.apersqsp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7189108/ca769ba4-e47c-11e4-847e-0d9c4bace770.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7189108/ca769ba4-e47c-11e4-847e-0d9c4bace770.png)
https://cloud.githubusercontent.com/assets/2068130/7189108/ca769ba4-e47c-11e4-847e-0d9c4bace770.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7189115/dab18fd8-e47c-11e4-9bdb-c4de49c84be1.png
