### ISSUE TITLE
ProTracker Plus WW Watchers Nutrition and Exercise Value Tracker, Database and Calculator

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5582]
**App Name:** ProTracker Plus WW Watchers Nutrition and Exercise Value Tracker, Database and Calculator
**Bundle ID:** com.christiangossainapps.ProTracker-Plus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=587922128">587922128</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/protracker-plus-ww-watchers/id587922128?mt=8&uo=4">https://itunes.apple.com/us/app/protracker-plus-ww-watchers/id587922128?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Christian Gossain
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/gossain-software-llc/id518214149?uo=4>© Gossain Software LLC</a>
**Supported Devices:** iPadFourthGen, iPodTouchFifthGen, iPhone4S, iPhone4, iPadThirdGen4G, iPhone6Plus, iPhone5c, iPhone5s, iPhone6, iPadFourthGen4G, iPadMini, iPhone5, iPadThirdGen, iPad2Wifi, iPadMini4G, iPad23G
**Original Artwork:**
<img src="http://a1009.phobos.apple.com/us/r30/Purple5/v4/f2/fa/17/f2fa172f-b0ec-b1bd-ee94-7a32360358ab/pr_source.png?downloadKey=1429195370_d78a9f29d12f0ae4d3a854005ad566dd" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7188757/5ed0fd42-e47a-11e4-812e-02f5983394cd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7188757/5ed0fd42-e47a-11e4-812e-02f5983394cd.png)
https://cloud.githubusercontent.com/assets/2068130/7188757/5ed0fd42-e47a-11e4-812e-02f5983394cd.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7188775/707ceb5a-e47a-11e4-8e92-4d668238d302.png
