### ISSUE TITLE
[DUPLICATE of #4814]

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5583]
**App Name:** iAppLock
 **Bundle ID:**  com.thinkyeah.iAppLock
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="http://thinkweb.qiniudn.com/assets/iapplock_v2.png" width="150" height="150" />
 **Accepted Artwork:**
 \#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
@Trubbel We already have an issue for this. If something is going wrong with thi app, please leave a comment on the existing issue #4814.
