### ISSUE TITLE
Bio Inc. - Biomedical Plague and Infection RTS

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5584]
**App Name:** Bio Inc. - Biomedical Plague and Infection RTS
**Bundle ID:** com.dryginstudios.bioincfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=932497563">932497563</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bio-inc.-biomedical-plague/id932497563?mt=8&uo=4">https://itunes.apple.com/us/app/bio-inc.-biomedical-plague/id932497563?mt=8&uo=4</a>
**App Version:** 2.00
**Seller:** 9262-9518 QUEBEC INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/drygin-studios/id530299099?uo=4>© DryGin Studios</a>
**Supported Devices:** iPadMini, iPodTouchFifthGen, iPadFourthGen4G, iPhone6, iPhone4S, iPhone5c, iPhone-3GS, iPad3G, iPhone6Plus, iPad2Wifi, iPadThirdGen4G, iPadWifi, iPhone4, iPodTouchThirdGen, iPadThirdGen, iPhone5, iPadFourthGen, iPodTouchFourthGen, iPhone5s, iPad23G, iPadMini4G
**Original Artwork:**
<img src="http://a597.phobos.apple.com/us/r30/Purple3/v4/fd/23/21/fd2321a9-4497-513b-c8be-8517ccc2e3a0/mzl.hlyvnanb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7191246/6f42b8ca-e48c-11e4-8bd8-102336ba7ac6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7191246/6f42b8ca-e48c-11e4-8bd8-102336ba7ac6.png)
https://cloud.githubusercontent.com/assets/2068130/7191246/6f42b8ca-e48c-11e4-8bd8-102336ba7ac6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7191253/7f2be7b6-e48c-11e4-8d2f-de5cd007f263.png
