### ISSUE TITLE
The Firm

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5585]
**App Name:** The Firm
**Bundle ID:** com.sunnysidegames.thefirm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=883108531">883108531</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-firm/id883108531?mt=8&uo=4">https://itunes.apple.com/us/app/the-firm/id883108531?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Sunnyside SARL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sunnyside-games/id883108534?uo=4>© Sunnyside Games</a>
**Supported Devices:** iPadFourthGen4G, iPhone5, iPad2Wifi, iPodTouchFifthGen, iPhone6, iPodTouchThirdGen, iPadMini4G, iPhone6Plus, iPadMini, iPadThirdGen4G, iPadFourthGen, iPhone4S, iPhone-3GS, iPad23G, iPad3G, iPadThirdGen, iPhone5c, iPodTouchFourthGen, iPadWifi, iPhone5s, iPhone4
**Original Artwork:**
<img src="http://a1964.phobos.apple.com/us/r30/Purple3/v4/16/9a/49/169a497c-bb31-bd8c-e42a-e5c1066f553a/mzl.nvdugjim.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7190416/6e637e54-e486-11e4-9ebe-36874826ce13.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7190416/6e637e54-e486-11e4-9ebe-36874826ce13.png)
https://cloud.githubusercontent.com/assets/2068130/7190416/6e637e54-e486-11e4-9ebe-36874826ce13.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7190427/7eb8b7ba-e486-11e4-8ba2-f2b4f92d5572.png
