### ISSUE TITLE
NoteCeption - The counting note app

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5586]
**App Name:** NoteCeption - The counting note app
**Bundle ID:** com.sirnic.noteception
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=940718490">940718490</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/noteception-counting-note/id940718490?mt=8&uo=4">https://itunes.apple.com/us/app/noteception-counting-note/id940718490?mt=8&uo=4</a>
**App Version:** 1.05
**Seller:** Max Gittel
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/max-gittel/id764787722?uo=4>© Max Gittel</a>
**Supported Devices:** iPhone4S, iPad2Wifi, iPhone6, iPadThirdGen, iPhone5, iPhone5s, iPad23G, iPadMini, iPodTouchFifthGen, iPadFourthGen4G, iPadMini4G, iPadFourthGen, iPhone5c, iPadThirdGen4G, iPhone4, iPhone6Plus
**Original Artwork:**
<img src="http://a163.phobos.apple.com/us/r30/Purple3/v4/7e/2d/41/7e2d4149-1b24-5268-efc0-fd3513f578f4/pr_source.png?downloadKey=1429196977_35fb52e3f4076462fe1accfe0b023542" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7188512/c6a1c188-e478-11e4-8c3d-78f0e619f623.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7188512/c6a1c188-e478-11e4-8c3d-78f0e619f623.png)
https://cloud.githubusercontent.com/assets/2068130/7188512/c6a1c188-e478-11e4-8c3d-78f0e619f623.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7188529/dd30f428-e478-11e4-80aa-948f86934285.png
