### ISSUE TITLE
CSources2

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5587]
**App Name:** CSources2
**Bundle ID:** com.dirtybeans.CSources2
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/7189436/46c57732-e47f-11e4-9292-61a7af738cf4.png" width="150" height="150">
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7211581/75338324-e55c-11e4-8f85-7e4ce8ee9ada.png)

**Comment by WaterTrooper** [comment]
I cannot get the image to show. I uploaded to my Dropbox. Here is the link. https://www.dropbox.com/s/q0wvozmn1m4ms08/csources2.png?dl=0

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7211581/75338324-e55c-11e4-8f85-7e4ce8ee9ada.png)
https://cloud.githubusercontent.com/assets/2068130/7211581/75338324-e55c-11e4-8f85-7e4ce8ee9ada.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7211586/84985ae2-e55c-11e4-95ce-bd4c88dcbe57.png

**Comment by WaterTrooper** [comment]
That's some sexy work.

**Comment by dreamnet** [comment]
@WaterTrooper :laughing:
