### ISSUE TITLE
Binaural Sleep Beats - Insomnia Sounds

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5588]
**App Name:** Binaural Sleep Beats - Insomnia Sounds
**Bundle ID:** binauralsleep
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=683039880">683039880</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/binaural-sleep-beats-insomnia/id683039880?mt=8&uo=4">https://itunes.apple.com/us/app/binaural-sleep-beats-insomnia/id683039880?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** TechBase LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/techbase-llc/id415427378?uo=4>© TechBase LLC</a>
**Supported Devices:** iPhone6Plus, iPadWifi, iPadFourthGen4G, iPhone4, iPadThirdGen4G, iPadFourthGen, iPodTouchFifthGen, iPadMini, iPodTouchThirdGen, iPad2Wifi, iPadMini4G, iPhone-3GS, iPhone5s, iPodTouchFourthGen, iPhone5, iPadThirdGen, iPhone4S, iPad23G, iPad3G, iPhone5c, iPhone6
**Original Artwork:**
<img src="http://a1520.phobos.apple.com/us/r30/Purple4/v4/61/80/d4/6180d477-f247-777b-fa0b-6d3b4cfe3afe/mzl.dcqghzjv.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7208598/74c4cebc-e542-11e4-8f2c-58cb69ac502f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7208598/74c4cebc-e542-11e4-8f2c-58cb69ac502f.png)
https://cloud.githubusercontent.com/assets/2068130/7208598/74c4cebc-e542-11e4-8f2c-58cb69ac502f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7208602/836fb8dc-e542-11e4-9925-879e2fcf46a4.png

**Comment by boxermansr** [comment]
Perfect, thanks.
