### ISSUE TITLE
BackTracker

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5589]
**App Name:** BackTracker
**Bundle ID:** com.backtrackerapp.BackTracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979210947">979210947</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/backtracker/id979210947?mt=8&uo=4">https://itunes.apple.com/us/app/backtracker/id979210947?mt=8&uo=4</a>
**App Version:** 1
**Seller:** BackTracker Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/backtracker-app/id979210946?uo=4>© BackTracker App</a>
**Supported Devices:** iPhone6Plus, iPadFourthGen, iPadThirdGen4G, iPhone5s, iPad2Wifi, iPadMini, iPhone5c, iPhone4S, iPhone6, iPad23G, iPadFourthGen4G, iPodTouchFifthGen, iPhone5, iPadMini4G, iPadThirdGen
**Original Artwork:**
<img src="http://a1976.phobos.apple.com/us/r30/Purple3/v4/30/47/3e/30473e93-ac12-a738-dde7-eecf1f95cf10/pr_source.png?downloadKey=1429384786_dec66ab4b3b4444ad4b4a1f9ce9010ed" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7218130/7277474c-e65b-11e4-9ccf-d98fc262636d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7216240/69451b4e-e5f8-11e4-9f0a-33ed303f0101.png)
https://cloud.githubusercontent.com/assets/10730122/7216240/69451b4e-e5f8-11e4-9f0a-33ed303f0101.png
-- --
Source:
https://cloud.githubusercontent.com/assets/10730122/7216239/60572bee-e5f8-11e4-9292-e1c86f9e1236.png

**Comment by dreamnet** [comment]
@Trubbel Great, I just made the lines a bit thicker:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7218130/7277474c-e65b-11e4-9ccf-d98fc262636d.png)
https://cloud.githubusercontent.com/assets/2068130/7218130/7277474c-e65b-11e4-9ccf-d98fc262636d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7218133/8425de22-e65b-11e4-94cd-482360f3739f.png
