### ISSUE TITLE
Swifty - Learn to code in Swift!

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5591]
**App Name:** Swifty - Learn to code in Swift!
**Bundle ID:** com.joejohannesjoe.swifty
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=886315617">886315617</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swifty-learn-to-code-in-swift!/id886315617?mt=8&uo=4">https://itunes.apple.com/us/app/swifty-learn-to-code-in-swift!/id886315617?mt=8&uo=4</a>
**App Version:** 1.4.6
**Seller:** Johannes Berger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/johannes-berger/id548016918?uo=4>© Johannes Berger</a>
**Supported Devices:** iPhone6, iPadThirdGen4G, iPadThirdGen, iPhone5s, iPhone4, iPhone5c, iPhone5, iPad2Wifi, iPhone6Plus, iPadFourthGen4G, iPadMini, iPodTouchFifthGen, iPad23G, iPadFourthGen, iPadMini4G, iPhone4S
**Original Artwork:**
<img src="http://a984.phobos.apple.com/us/r30/Purple7/v4/e6/a9/2e/e6a92e0f-4c47-de1d-1720-bbf41d03c42f/mzl.tucfsmww.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7218152/ccefd38c-e65c-11e4-896e-483ad6379ba5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7218152/ccefd38c-e65c-11e4-896e-483ad6379ba5.png)
https://cloud.githubusercontent.com/assets/2068130/7218152/ccefd38c-e65c-11e4-896e-483ad6379ba5.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7218154/de08541e-e65c-11e4-895f-fe110b5436c0.png
