### ISSUE TITLE
English Russian Dictionary

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5592]
**App Name:** English Russian Dictionary
**Bundle ID:** la.bab.english.enrudict
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=372385789">372385789</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/english-russian-dictionary/id372385789?mt=8&uo=4">https://itunes.apple.com/us/app/english-russian-dictionary/id372385789?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** bab.la GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bab.la-gmbh/id346185558?uo=4>© bab.la GmbH</a>
**Supported Devices:** iPodTouchThirdGen, iPhone6, iPhone5c, iPadThirdGen4G, iPhone5, iPadFourthGen, iPhone6Plus, iPad3G, iPadFourthGen4G, iPhone4, iPad2Wifi, iPhone4S, iPadMini4G, iPhone5s, iPadThirdGen, iPadWifi, iPhone-3GS, iPadMini, iPodTouchFourthGen, iPad23G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://a1281.phobos.apple.com/us/r30/Purple/v4/ec/e9/01/ece9013d-74bf-cf71-e5b4-cddae422254b/mzl.gaxogegp.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7248505/cd0a6a58-e7d8-11e4-8226-68d423d7a86b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7248505/cd0a6a58-e7d8-11e4-8226-68d423d7a86b.png)
https://cloud.githubusercontent.com/assets/3090247/7248505/cd0a6a58-e7d8-11e4-8226-68d423d7a86b.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7248506/cd0bec20-e7d8-11e4-98bf-42aea9b8c85b.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
