### ISSUE TITLE
iHeartRadio for Auto

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5593]
**App Name:** iHeartRadio for Auto
**Bundle ID:** com.clearchannel.iheartradio.connect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586095930">586095930</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iheartradio-for-auto/id586095930?mt=8&uo=4">https://itunes.apple.com/us/app/iheartradio-for-auto/id586095930?mt=8&uo=4</a>
**App Version:** 1.7.0
**Seller:** iHeartMedia Management Services, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/iheartmedia-management-services/id290638157?uo=4>© iHeartMedia Management Services, Inc.</a>
**Supported Devices:** iPadMini4G, iPhone5s, iPhone5, iPadFourthGen4G, iPhone4S, iPadThirdGen, iPadFourthGen, iPodTouchFifthGen, iPad2Wifi, iPhone6, iPadThirdGen4G, iPadMini, iPhone5c, iPad23G, iPhone4, iPhone6Plus
**Original Artwork:**
<img src="http://a1748.phobos.apple.com/us/r30/Purple1/v4/0d/e1/92/0de1927c-05d7-2999-e007-bf8a676ed623/mzl.ourgumwx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7262906/92b11f14-e87d-11e4-932c-2d3f29aec86a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7262906/92b11f14-e87d-11e4-932c-2d3f29aec86a.png)
https://cloud.githubusercontent.com/assets/2068130/7262906/92b11f14-e87d-11e4-932c-2d3f29aec86a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7262916/a1eb90fe-e87d-11e4-9568-56379b680f74.png
