### ISSUE TITLE
My Om Nom

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5597]
**App Name:** My Om Nom
**Bundle ID:** com.zeptolab.myomnom.paid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942990867">942990867</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-om-nom/id942990867?mt=8&uo=4">https://itunes.apple.com/us/app/my-om-nom/id942990867?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** ZeptoLab UK Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/zeptolab-uk-limited/id450542236?uo=4>© ZeptoLab UK Limited</a>
**Supported Devices:** iPodTouchFifthGen, iPad2Wifi, iPadFourthGen, iPhone5s, iPhone5c, iPad23G, iPadFourthGen4G, iPadMini, iPadMini4G, iPadThirdGen, iPhone4S, iPhone6, iPhone6Plus, iPodTouchFourthGen, iPhone-3GS, iPhone4, iPhone5, iPadThirdGen4G
**Original Artwork:**
<img src="http://a123.phobos.apple.com/us/r30/Purple1/v4/b3/d1/0b/b3d10be0-520b-4ad3-1909-893213c91c76/mzl.rbbgoobq.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7293719/ef8741ce-e96c-11e4-8fe6-d1d2edf8497b.png)

**Comment by ivanov007** [comment]
not sure witch one looks better
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7293718/ef86c046-e96c-11e4-8acc-2a72df4c0917.png)
https://cloud.githubusercontent.com/assets/3090247/7293718/ef86c046-e96c-11e4-8acc-2a72df4c0917.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7293719/ef8741ce-e96c-11e4-8fe6-d1d2edf8497b.png)
https://cloud.githubusercontent.com/assets/3090247/7293719/ef8741ce-e96c-11e4-8fe6-d1d2edf8497b.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7293732/0626f7d0-e96d-11e4-8049-3e63335add34.png
https://cloud.githubusercontent.com/assets/3090247/7293733/062a8d8c-e96d-11e4-95dc-aafcde5e94c0.png

**Comment by dreamnet** [comment]
@ivanov007 Hmmm, I think the second one. :+1:
