### ISSUE TITLE
F.A.Z. Kiosk - App zur Zeitung

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#5598]
**App Name:** F.A.Z. Kiosk - App zur Zeitung
**Bundle ID:** net.faz.FAZiPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=416982402">416982402</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/f-a-z-kiosk-app-zur-zeitung/id416982402?uo=4">https://apps.apple.com/us/app/f-a-z-kiosk-app-zur-zeitung/id416982402?uo=4</a>
**App Version:** 5.13
**Seller:** Frankfurter Allgemeine Zeitung GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/frankfurter-allgemeine-zeitung-gmbh/id375948655?uo=4">© Frankfurter Allgemeine Zeitung GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/56/be/8c/56be8c7c-2007-019c-4c7e-636987c692f4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60392901-bdef4c00-9b0c-11e9-821a-63fc45e720c6.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/7299386/cfa5c4a2-e9d5-11e4-804e-77c662e28bb3.png)
https://cloud.githubusercontent.com/assets/8452321/7299386/cfa5c4a2-e9d5-11e4-804e-77c662e28bb3.png

Source:
https://cloud.githubusercontent.com/assets/8452321/7299421/fb10a878-e9d5-11e4-8f07-7b74baba1fb1.png

**Comment by dreamnet** [comment]
@DerDoktor Yes! :+1:

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60392901-bdef4c00-9b0c-11e9-821a-63fc45e720c6.png)
https://user-images.githubusercontent.com/20930745/60392901-bdef4c00-9b0c-11e9-821a-63fc45e720c6.png

Source:
https://user-images.githubusercontent.com/20930745/60392903-c051a600-9b0c-11e9-991d-45c74c7ef4fa.png
