### ISSUE TITLE
FALTER - Die Wochenzeitung aus Wien

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#5599]
**App Name:** FALTER - Die Wochenzeitung aus Wien
**Bundle ID:** com.falter.Falter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506652286">506652286</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/falter-die-wochenzeitung-aus/id506652286?mt=8&uo=4">https://itunes.apple.com/de/app/falter-die-wochenzeitung-aus/id506652286?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Falter-Verlags-Gesellschaft m.b.H.
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/falter-verlagsgesellschaft/id401226923?uo=4>© Falter Verlagsgesellschaft m.b.H.</a>
**Supported Devices:** iPadThirdGen, iPadMini4G, iPhone5c, iPad2Wifi, iPadMini, iPadThirdGen4G, iPhone6, iPhone6Plus, iPad23G, iPodTouchFifthGen, iPhone4, iPhone5, iPadFourthGen, iPhone4S, iPhone5s, iPadFourthGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/30/78/ea/3078eafd-bc41-6699-92d2-31858197ef35/mzl.mtfeqxst.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/7299445/2dbb44e0-e9d6-11e4-80fc-1a9b8a08a6ed.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/7299445/2dbb44e0-e9d6-11e4-80fc-1a9b8a08a6ed.png)
https://cloud.githubusercontent.com/assets/8452321/7299445/2dbb44e0-e9d6-11e4-80fc-1a9b8a08a6ed.png

Source:
https://cloud.githubusercontent.com/assets/8452321/7299461/46b4679c-e9d6-11e4-99b5-a13994baf648.png

**Comment by dreamnet** [comment]
@DerDoktor Jup! :+1:
