### ISSUE TITLE
Photobucket - Backup & Print Shop

### ISSUE THREAD

**Issue by MagnaMike** [glasklart/hd#560]
**App Name:** Photobucket - Backup & Print Shop
**Bundle ID:** com.photobucket.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=314439840">314439840</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photobucket-backup-print-shop/id314439840?mt=8&uo=4">https://itunes.apple.com/us/app/photobucket-backup-print-shop/id314439840?mt=8&uo=4</a>
**App Version:** 3.3.8
**Seller:** Photobucket.com Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/photobucket.com/id314439843?uo=4>© Photobucket.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/45/8a/00/458a0017-c373-32b6-d457-d6585ef754f8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19235762/ee85fe90-8ef3-11e6-8b5e-ad2bb61c96ca.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19235762/ee85fe90-8ef3-11e6-8b5e-ad2bb61c96ca.png)
https://cloud.githubusercontent.com/assets/20930745/19235762/ee85fe90-8ef3-11e6-8b5e-ad2bb61c96ca.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19235775/ff3e12f4-8ef3-11e6-8642-75ca5a9a8633.png
