### ISSUE TITLE
Screenshot Maker Pro

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#5600]
**App Name:** Screenshot Maker Pro
**Bundle ID:** com.plusblog.smpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=673545271">673545271</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/screenshot-maker-pro/id673545271?mt=8&uo=4">https://itunes.apple.com/us/app/screenshot-maker-pro/id673545271?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Takahiko Hatano
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/takahiko-hatano/id673545274?uo=4>© Takahiko Hatano</a>
**Supported Devices:** iPodTouchFifthGen, iPhone5c, iPad23G, iPhone5, iPadThirdGen, iPhone4, iPhone-3GS, iPodTouchFourthGen, iPhone4S, iPhone6, iPadFourthGen, iPad2Wifi, iPhone6Plus, iPadMini4G, iPadThirdGen4G, iPadFourthGen4G, iPhone5s, iPadMini
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple3/v4/a6/7b/36/a67b3618-d93a-d9e4-bd60-e612d74b34dc/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/7306225/f3dd0bfe-ea03-11e4-8cc0-88e6876199f6.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/7299493/8362ff28-e9d6-11e4-8768-ddc01fa3d48b.png)
https://cloud.githubusercontent.com/assets/8452321/7299493/8362ff28-e9d6-11e4-8768-ddc01fa3d48b.png

Source:
https://cloud.githubusercontent.com/assets/8452321/7299507/9bd68bd8-e9d6-11e4-9033-3bbc6b8ae919.png

**Comment by dreamnet** [comment]
@DerDoktor No - no grayscales allowed. Sorry.

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/7306225/f3dd0bfe-ea03-11e4-8cc0-88e6876199f6.png)
https://cloud.githubusercontent.com/assets/8452321/7306225/f3dd0bfe-ea03-11e4-8cc0-88e6876199f6.png

**Comment by MagnaMike** [comment]
@DerDoktor Using the same source file from version 1?

**Comment by dreamnet** [comment]
@MagnaMike I think it is - I add it to the last post from @DerDoktor .
