### ISSUE TITLE
Cheatsheet — Quick Note Keyboard and Widget

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#5601]
**App Name:** Cheatsheet — Quick Note Keyboard and Widget
**Bundle ID:** com.overdesigned.Cheatsheet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914665829">914665829</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cheatsheet-quick-note-keyboard/id914665829?mt=8&uo=4">https://itunes.apple.com/us/app/cheatsheet-quick-note-keyboard/id914665829?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Christopher Adam Overholtzer
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/christopher-adam-overholtzer/id914665832?uo=4>© Christopher Adam Overholtzer</a>
**Supported Devices:** iPhone4S, iPad2Wifi, iPadThirdGen, iPhone6, iPadMini, iPadMini4G, iPhone5, iPadFourthGen, iPhone5s, iPodTouchFifthGen, iPadFourthGen4G, iPhone6Plus, iPhone5c, iPad23G, iPadThirdGen4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/78/3b/fe/783bfe9d-8292-a8d4-05be-fab2cb49de31/mzl.vlmyexsn.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7302123/7c043650-e9e7-11e4-8597-886056368937.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/7299551/f6fe361e-e9d6-11e4-8cb4-467fb214f6c6.png)
https://cloud.githubusercontent.com/assets/8452321/7299551/f6fe361e-e9d6-11e4-8cb4-467fb214f6c6.png

Source:
https://cloud.githubusercontent.com/assets/8452321/7299564/09057318-e9d7-11e4-984c-aa997c87d01f.png

**Comment by dreamnet** [comment]
@DerDoktor There is a small part missing on the lock - credits are going to you. Good work! :+1: 
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7302123/7c043650-e9e7-11e4-8597-886056368937.png)
https://cloud.githubusercontent.com/assets/2068130/7302123/7c043650-e9e7-11e4-8597-886056368937.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7302132/8d0822cc-e9e7-11e4-8f55-41a764bf3738.png
