### ISSUE TITLE
L.E.D. Torch

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5602]
**App Name:** L.E.D. Torch
**Bundle ID:** 2WQ2PEKNM5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389545091">389545091</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/l.e.d.-torch/id389545091?mt=8&uo=4">https://itunes.apple.com/us/app/l.e.d.-torch/id389545091?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Tyler Bell
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tyler-bell/id389545094?uo=4>© Tyler Bell</a>
**Supported Devices:** iPhone5, iPhone5s, iPodTouchFifthGen, iPhone6, iPhone6Plus, iPhone4, iPhone4S, iPhone5c
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple/51/f5/cc/mzi.muuxvzlf.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7873529/02a694ae-0569-11e5-83be-495e027478e5.png)

**Comment by ivanov007** [comment]
this one is already on master but I think it needs to be remade... or updated? 
![](http://preview.dreamnet.at/?image=https://github.com/glasklart/hd/raw/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/2WQ2PEKNM5%402x.png)

**Comment by MagnaMike** [comment]
Well the flashlight better represents what the app actually does, but it isn't like the original icon ....but how do you make a glasklart icon like that....

**Comment by ivanov007** [comment]
maybe something like this?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7873529/02a694ae-0569-11e5-83be-495e027478e5.png)
https://cloud.githubusercontent.com/assets/3090247/7873529/02a694ae-0569-11e5-83be-495e027478e5.png

---
Source:
![2wq2peknm5](https://cloud.githubusercontent.com/assets/3090247/7873530/02a75236-0569-11e5-80e4-0d0c8f078f8e.png)

**Comment by dreamnet** [comment]
@ivanov007 It's OK for me.... @MagnaMike ?

**Comment by MagnaMike** [comment]
@dreamnet It's the best it can be I guess :neutral_face:
