### ISSUE TITLE
Hours Time Tracking

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5603]
**App Name:** Hours Time Tracking
**Bundle ID:** com.tapity.hours
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=895933956">895933956</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hours-time-tracking/id895933956?mt=8&uo=4">https://itunes.apple.com/us/app/hours-time-tracking/id895933956?mt=8&uo=4</a>
**App Version:** 2.7.1
**Seller:** Hours, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hours-llc/id1050323678?uo=4">© Hours, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/d0/c0/b7/d0c0b718-165e-3e77-ce2b-ea3c543120b5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20464222/5c427c7c-af44-11e6-9dd0-faaa5d50a37f.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7313611/6e9a5104-ea21-11e4-8e40-e1bf41ef27a4.png)
https://cloud.githubusercontent.com/assets/3090247/7313611/6e9a5104-ea21-11e4-8e40-e1bf41ef27a4.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7313623/8568fbec-ea21-11e4-8a9f-ce112871a882.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20464222/5c427c7c-af44-11e6-9dd0-faaa5d50a37f.png)
https://cloud.githubusercontent.com/assets/20930745/20464222/5c427c7c-af44-11e6-9dd0-faaa5d50a37f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20464224/664618f0-af44-11e6-952e-d3126f8a372e.png
