### ISSUE TITLE
GHOSTS'N GOBLINS GOLD KNIGHTS

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5605]
**App Name:** GHOSTS'N GOBLINS GOLD KNIGHTS
**Bundle ID:** jp.co.capcom.makaikus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335708419">335708419</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ghostsn-goblins-gold-knights/id335708419?mt=8&uo=4">https://itunes.apple.com/us/app/ghostsn-goblins-gold-knights/id335708419?mt=8&uo=4</a>
**App Version:** 1.00.08
**Seller:** CAPCOM Co., Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/capcom/id308807391?uo=4>© CAPCOM</a>
**Supported Devices:** iPhone6Plus, iPodTouchThirdGen, iPhone5s, iPhone5c, iPadWifi, iPadFourthGen, iPadMini, iPodTouchFourthGen, iPhone5, iPhone-3GS, iPad23G, iPadFourthGen4G, iPadThirdGen4G, iPadThirdGen, iPodTouchFifthGen, iPhone4S, iPadMini4G, iPad3G, iPad2Wifi, iPhone6, iPhone4
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple/v4/01/85/7a/01857aca-2d75-69f2-2e5f-93f174865bfc/mzl.ffycfldr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7334913/56d1e69a-eba2-11e4-91e7-9f75eb50dadd.png)

**Comment by ivanov007** [comment]
this one needs an update
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7331621/3df7d4a6-eadd-11e4-8fd1-6ca982fcf972.png)
https://cloud.githubusercontent.com/assets/3090247/7331621/3df7d4a6-eadd-11e4-8fd1-6ca982fcf972.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7331625/55f19074-eadd-11e4-9766-8f087f5f7700.png

**Comment by dreamnet** [comment]
Tryed to invert this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7334913/56d1e69a-eba2-11e4-91e7-9f75eb50dadd.png)
https://cloud.githubusercontent.com/assets/2068130/7334913/56d1e69a-eba2-11e4-91e7-9f75eb50dadd.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7334916/6a8cb3ae-eba2-11e4-9180-d526b9447d8f.png
