### ISSUE TITLE
GHOSTS'N GOBLINS GOLD KNIGHTS FREE

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5606]
**App Name:** GHOSTS'N GOBLINS GOLD KNIGHTS FREE
**Bundle ID:** jp.co.capcom.makaik1fusdistribution
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390115263">390115263</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ghostsn-goblins-gold-knights/id390115263?mt=8&uo=4">https://itunes.apple.com/us/app/ghostsn-goblins-gold-knights/id390115263?mt=8&uo=4</a>
**App Version:** 1.00.00
**Seller:** CAPCOM Co., Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/capcom/id308807391?uo=4>© CAPCOM</a>
**Supported Devices:** iPodTouchThirdGen, iPod-touch-with-mic, iPhone4S, iPadMini, iPadMini4G, iPadThirdGen4G, iPhone-3GS, iPadThirdGen, iPhone6Plus, iPhone5s, iPadFourthGen4G, iPhone5c, iPodTouchFourthGen, iPodTouchFifthGen, iPhone4, iPad2Wifi, iPad23G, iPadWifi, iPhone-3G, iPad3G, iPhone6, iPadFourthGen, iPhone5
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple/9d/57/a0/mzi.qxxjwenw.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7334913/56d1e69a-eba2-11e4-91e7-9f75eb50dadd.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7331621/3df7d4a6-eadd-11e4-8fd1-6ca982fcf972.png)
https://cloud.githubusercontent.com/assets/3090247/7331621/3df7d4a6-eadd-11e4-8fd1-6ca982fcf972.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7331625/55f19074-eadd-11e4-9766-8f087f5f7700.png

**Comment by dreamnet** [comment]
Same as for #5605:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7334913/56d1e69a-eba2-11e4-91e7-9f75eb50dadd.png)
https://cloud.githubusercontent.com/assets/2068130/7334913/56d1e69a-eba2-11e4-91e7-9f75eb50dadd.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7334916/6a8cb3ae-eba2-11e4-9180-d526b9447d8f.png
