### ISSUE TITLE
Modizer

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5607]
**App Name:** Modizer
**Bundle ID:** com.yoyofr.modizer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393964792">393964792</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/modizer/id393964792?mt=8&uo=4">https://itunes.apple.com/us/app/modizer/id393964792?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Yohann Magnien
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/yoyofr/id393964795?uo=4>© YoyoFR</a>
**Supported Devices:** iPad2Wifi, iPhone5, iPadFourthGen4G, iPhone4, iPodTouchFourthGen, iPadThirdGen4G, iPadMini4G, iPhone-3GS, iPadFourthGen, iPadWifi, iPodTouchThirdGen, iPodTouchFifthGen, iPhone5s, iPad3G, iPhone6, iPhone5c, iPhone6Plus, iPadThirdGen, iPadMini, iPhone4S, iPad23G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/f8/bf/f8/f8bff89d-3bbf-8977-aa7d-dfa4cc4323b9/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7334685/7172410a-eb9a-11e4-95ce-c78465913c27.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7331722/f7387a2a-eae1-11e4-9ae6-1f6e33b1345d.png)
https://cloud.githubusercontent.com/assets/3090247/7331722/f7387a2a-eae1-11e4-9ae6-1f6e33b1345d.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7331723/0cfc846e-eae2-11e4-9b28-ebd5f49d8f6a.png

**Comment by dreamnet** [comment]
Small update:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7334685/7172410a-eb9a-11e4-95ce-c78465913c27.png)
https://cloud.githubusercontent.com/assets/2068130/7334685/7172410a-eb9a-11e4-95ce-c78465913c27.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7334691/8112fac8-eb9a-11e4-8e25-4473da0287f6.png
