### ISSUE TITLE
Tiki Towers

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5608]
**App Name:** Tiki Towers
**Bundle ID:** com.mrgoodliving.TikiTowers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=298127125">298127125</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tiki-towers/id298127125?mt=8&uo=4">https://itunes.apple.com/us/app/tiki-towers/id298127125?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** RealNetworks, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/gamehouse/id284837569?mt=8&uo=4>© GameHouse</a>
**Supported Devices:** iPadFourthGen, iPhone6Plus, iPodTouchFourthGen, iPod-touch-with-mic, iPad2Wifi, iPhone4S, iPodTouchThirdGen, iPadMini, iPod-touch, iPhone4, iPhone-3G, iPadFourthGen4G, iPad3G, iPodTouchFifthGen, iPadWifi, iPhone, iPadThirdGen4G, iPhone6, iPadThirdGen, iPhone5, iPad23G, iPadMini4G, iPhone-3GS, iPhone5s, iPhone5c
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple/1a/bb/3c/mzi.hrfwughx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7335098/4c691bc8-eba8-11e4-9f0d-a7cce7874e54.png)

**Comment by ivanov007** [comment]
just adding the source for this one

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7331788/8c7fe188-eae5-11e4-8263-fdc1507f2d09.png)
https://cloud.githubusercontent.com/assets/3090247/7331788/8c7fe188-eae5-11e4-8263-fdc1507f2d09.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7331792/abf29d12-eae5-11e4-9230-e609c96669c1.png

**Comment by dreamnet** [comment]
Tryed also to invert this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7335098/4c691bc8-eba8-11e4-9f0d-a7cce7874e54.png)
https://cloud.githubusercontent.com/assets/2068130/7335098/4c691bc8-eba8-11e4-9f0d-a7cce7874e54.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7335106/6085c28c-eba8-11e4-9e38-9306a58f9843.png
