### ISSUE TITLE
Google Maps - Transit & Food

### ISSUE THREAD

**Issue by jimmyt650** [glasklart/hd#561]
**App Name:** Google Maps - Transit & Food
**Bundle ID:** com.google.Maps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=585027354">585027354</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-maps-transit-food/id585027354?uo=4">https://apps.apple.com/us/app/google-maps-transit-food/id585027354?uo=4</a>
**App Version:** 5.37
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/f5/83/e0/f583e0e1-78c7-b302-361f-167d1fcd4be7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74583868-33405c00-4fcc-11ea-8afa-7c0646934f33.png)

**Comment by ivanov007** [comment]
icon have changed, but I don't know if it worth the change
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9781177/048caff2-5757-11e5-847e-1d0a76bdf833.png)
https://cloud.githubusercontent.com/assets/3090247/9781177/048caff2-5757-11e5-847e-1d0a76bdf833.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9781180/049c4f0c-5757-11e5-8616-05bfa1ae22fb.png)
https://cloud.githubusercontent.com/assets/3090247/9781180/049c4f0c-5757-11e5-8616-05bfa1ae22fb.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/9781178/0498e3b2-5757-11e5-81a2-973a187f02ba.png
https://cloud.githubusercontent.com/assets/3090247/9781179/0499cac0-5757-11e5-851d-b41627a26dd8.png

**Comment by dreamnet** [comment]
On a second and a third thought, I think it's better to leave the existing icon as it is.

**Comment by l8er4now** [comment]
Shocker, another google app needs an update.

**App Name:** Google Maps
**Bundle ID:** com.google.Maps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=585027354">585027354</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-maps/id585027354?mt=8&uo=4">https://itunes.apple.com/us/app/google-maps/id585027354?mt=8&uo=4</a>
**App Version:** 4.11.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/2c/13/c8/2c13c824-a40e-042f-a7ec-4ef1ab959e0f/mzl.ddramdge.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10923994/387de832-8284-11e5-91f4-289a6ee971ad.png)
https://cloud.githubusercontent.com/assets/2068130/10923994/387de832-8284-11e5-91f4-289a6ee971ad.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10924002/4601fbe2-8284-11e5-8838-e6c13873e2a9.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Google Maps - Transit & Food
**Bundle ID:** com.google.Maps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=585027354">585027354</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-maps-transit-food/id585027354?uo=4">https://apps.apple.com/us/app/google-maps-transit-food/id585027354?uo=4</a>
**App Version:** 5.37
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/f5/83/e0/f583e0e1-78c7-b302-361f-167d1fcd4be7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74583868-33405c00-4fcc-11ea-8afa-7c0646934f33.png)
https://user-images.githubusercontent.com/20930745/74583868-33405c00-4fcc-11ea-8afa-7c0646934f33.png

Source:
https://user-images.githubusercontent.com/20930745/74583869-35a2b600-4fcc-11ea-8c9b-71867c47883e.png
