### ISSUE TITLE
Deepworld - Sandbox MMORPG Adventure

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5619]
**App Name:** Deepworld - Sandbox MMORPG Adventure
**Bundle ID:** com.bytebin.deepworld-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=574013495">574013495</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deepworld-sandbox-mmorpg-adventure/id574013495?mt=8&uo=4">https://itunes.apple.com/us/app/deepworld-sandbox-mmorpg-adventure/id574013495?mt=8&uo=4</a>
**App Version:** 2.3.4
**Seller:** Bytebin LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bytebin/id562421886?uo=4>© Bytebin</a>
**Supported Devices:** iPadMini4G, iPhone5s, iPad2Wifi, iPadFourthGen4G, iPodTouchFifthGen, iPhone4, iPadFourthGen, iPhone6, iPhone5c, iPhone6Plus, iPadThirdGen4G, iPhone-3GS, iPhone5, iPadMini, iPodTouchFourthGen, iPadThirdGen, iPad23G, iPhone4S
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/25/bb/5a/25bb5a3a-42e4-b675-2f82-dfb72d0560c7/mzl.cwhwzliw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8528874/31536b58-23e4-11e5-98fb-b4fae243cd6b.png)

**Comment by MagnaMike** [comment]
@quantum8 Not a big deal, but please use the full `App Name:`

**Comment by quantum8** [comment]
OK @MagnaMike. I was just going from what's displayed on springboard.

**Comment by zmathiasz** [comment]
Common graphic from site.  Cant get app logo to come out very well.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8528874/31536b58-23e4-11e5-98fb-b4fae243cd6b.png)
https://cloud.githubusercontent.com/assets/10950389/8528874/31536b58-23e4-11e5-98fb-b4fae243cd6b.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8528894/4cc4f064-23e4-11e5-8637-2dfaa2c0dab8.png

Alternate:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8528949/a4b9687c-23e4-11e5-8706-eacdb8cc8535.png)
https://cloud.githubusercontent.com/assets/10950389/8528949/a4b9687c-23e4-11e5-8706-eacdb8cc8535.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8528956/bdd1d8b2-23e4-11e5-99b0-351e0815a4d4.png

**Comment by quantum8** [comment]
Both are great! First one works for me a little better @zmathiasz

**Comment by MagnaMike** [comment]
Okay, taking :one: as per @quantum8 suggestion.
