### ISSUE TITLE
Does not Commute

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5620]
**App Name:** Does not Commute
**Bundle ID:** com.mediocre.commute
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=971756507">971756507</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/does-not-commute/id971756507?mt=8&uo=4">https://itunes.apple.com/us/app/does-not-commute/id971756507?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Mediocre AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mediocre-ab/id431845724?uo=4>© Mediocre AB</a>
**Supported Devices:** iPadThirdGen4G, iPhone5c, iPadFourthGen, iPodTouchFifthGen, iPhone5s, iPadFourthGen4G, iPhone4, iPhone-3GS, iPodTouchFourthGen, iPadThirdGen, iPhone4S, iPhone5, iPad23G, iPadMini, iPhone6, iPhone6Plus, iPad2Wifi, iPadMini4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/52/86/c1/5286c16b-db2f-bfc7-2ad0-af611621ab5e/mzl.kswmyant.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7384862/4739605a-ee3b-11e4-8d29-72b5b2418b6e.png)

**Comment by dreamnet** [comment]
This one looks better inverted...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7384862/4739605a-ee3b-11e4-8d29-72b5b2418b6e.png)
https://cloud.githubusercontent.com/assets/2068130/7384862/4739605a-ee3b-11e4-8d29-72b5b2418b6e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7384869/611aa9f2-ee3b-11e4-859d-4317782fe9ff.png

**Comment by quantum8** [comment]
Sure does, Looks good @dreamnet!
