### ISSUE TITLE
Pushover Notifications

### ISSUE THREAD

**Issue by stonewareslord** [glasklart/hd#5621]
**App Name:** Pushover Notifications
**Bundle ID:** net.superblock.Pushover
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506088175">506088175</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pushover-notifications/id506088175?mt=8&uo=4">https://itunes.apple.com/us/app/pushover-notifications/id506088175?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Superblock, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/superblock/id506088178?uo=4>© Superblock</a>
**Supported Devices:** iPad2Wifi, iPadMini, iPadFourthGen, iPadFourthGen4G, iPhone5, iPhone6Plus, iPadThirdGen, iPadThirdGen4G, iPhone6, iPhone5c, iPhone4S, iPhone4, iPadMini4G, iPhone5s, iPad23G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/3a/36/a8/3a36a842-9b58-dd50-15ec-7d3c422e568f/mzl.iyihkead.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7384596/b0882f18-edfb-11e4-8c00-86126cadb35b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7384577/58fa9a6a-edfb-11e4-90e2-46c0552b4b00.png)
https://cloud.githubusercontent.com/assets/3090247/7384577/58fa9a6a-edfb-11e4-90e2-46c0552b4b00.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7384576/58d087a2-edfb-11e4-83e3-594571e551c4.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
