### ISSUE TITLE
Serverauditor - SSH Shell / Console / Terminal

### ISSUE THREAD

**Issue by stonewareslord** [glasklart/hd#5622]
**App Name:** Serverauditor - SSH Shell / Console / Terminal
**Bundle ID:** com.crystalnix.ServerAuditor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=549039908">549039908</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/serverauditor-ssh-shell-console/id549039908?mt=8&uo=4">https://itunes.apple.com/us/app/serverauditor-ssh-shell-console/id549039908?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** Crystalnix Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/crystalnix/id549040051?uo=4>© Crystalnix</a>
**Supported Devices:** iPhone6, iPhone4S, iPadMini4G, iPad2Wifi, iPhone6Plus, iPodTouchFifthGen, iPadThirdGen, iPhone5c, iPad23G, iPadFourthGen, iPadMini, iPhone4, iPhone5s, iPadFourthGen4G, iPadThirdGen4G, iPhone5
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple3/v4/03/22/89/0322896e-ee7a-b743-a95e-ec285dc17b84/mzl.etoqwbvw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7384507/0f6d1888-edfa-11e4-98e0-3bb7f9f670ef.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7384507/0f6d1888-edfa-11e4-98e0-3bb7f9f670ef.png)
https://cloud.githubusercontent.com/assets/3090247/7384507/0f6d1888-edfa-11e4-98e0-3bb7f9f670ef.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7384505/0f69ee2e-edfa-11e4-8469-01f1a3bef06f.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
