### ISSUE TITLE
OTP Auth

### ISSUE THREAD

**Issue by stonewareslord** [glasklart/hd#5623]
**App Name:** OTP Auth
**Bundle ID:** de.cooperrs.Authenticator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=659877384">659877384</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/otp-auth/id659877384?mt=8&uo=4">https://itunes.apple.com/us/app/otp-auth/id659877384?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Roland Moers
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/roland-moers/id659877387?uo=4>© Roland Moers</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen, iPhone6, iPadThirdGen4G, iPadMini, iPadFourthGen, iPad23G, iPhone5s, iPadMini4G, iPhone6Plus, iPadFourthGen4G, iPhone5c, iPodTouchFifthGen, iPhone4S, iPhone5
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple2/v4/61/1c/0e/611c0e26-e2e8-0b0c-52e6-8f580f78a8f0/mzl.mxziwdvj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7384695/7106acb0-ee38-11e4-8b5e-a0d4dd6a4d72.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7384469/7e6a8e6a-edf9-11e4-9397-5f7339f66f9d.png)
https://cloud.githubusercontent.com/assets/3090247/7384469/7e6a8e6a-edf9-11e4-9397-5f7339f66f9d.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7384470/7e6abca0-edf9-11e4-8311-e9f564077fdd.png

**Comment by dreamnet** [comment]
Resized to the original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7384695/7106acb0-ee38-11e4-8b5e-a0d4dd6a4d72.png)
https://cloud.githubusercontent.com/assets/2068130/7384695/7106acb0-ee38-11e4-8b5e-a0d4dd6a4d72.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7384700/80d265ee-ee38-11e4-8a22-e110ec733a67.png
