### ISSUE TITLE
Icons need themed 

### ISSUE THREAD

**Issue by Mrlobbies** [glasklart/hd#5624]
Wood forest app, youtubetomp3 (on cydia), FF Legacy
Hope to see them themed soon :)

**Comment by dreamnet** [comment]
@Mrlobbies Please read our [WIKI](https://github.com/glasklart/hd/wiki) on [how to submit an icon request](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request) and open a new issue for each app you want to be themed. THX!

**Comment by dreamnet** [comment]
@Mrlobbies Without the iTunes ID's we can't make the icons you are requested above. I'm going to close this in the next 24 hours.
