### ISSUE TITLE
iGameGuardian

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5627]
**App Name:** iGameGuardian
 **Bundle ID:**  Aqua.iGameGuardian
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/2068130/7439979/19da0884-f099-11e4-9433-838888e153a8.png" width="150" height="150" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/7432748/c390003c-eff8-11e4-8ace-75b97809dbad.png)

**Comment by zmathiasz** [comment]
I would consider this a fairly impossible icon.  Source from google search.  Yes, no?:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/7432748/c390003c-eff8-11e4-8ace-75b97809dbad.png)
https://cloud.githubusercontent.com/assets/10950389/7432748/c390003c-eff8-11e4-8ace-75b97809dbad.png

Source:
https://cloud.githubusercontent.com/assets/10950389/7432750/d6b52782-eff8-11e4-8ccb-f3b01cd7d3a6.png

**Comment by ivanov007** [comment]
@zmathiasz I think your icon will do it :+1: 
what do yoou think @glasklart/maintainers?

**Comment by dreamnet** [comment]
@ivanov007 Yes, it's good. We take it.
@zmathiasz :+1:
