### ISSUE TITLE
Ten Large

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5628]
**App Name:** Ten Large
**Bundle ID:** com.frostypop.tenlarge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=959811502">959811502</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ten-large/id959811502?mt=8&uo=4">https://itunes.apple.com/us/app/ten-large/id959811502?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** The Frosty Pop Corps Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/the-frosty-pop-corps-inc./id930758677?uo=4>© The Frosty Pop Corps Inc.</a>
**Supported Devices:** iPadThirdGen, iPhone5c, iPhone6, iPadFourthGen4G, iPhone5, iPad2Wifi, iPhone4S, iPadFourthGen, iPadThirdGen4G, iPad23G, iPadMini4G, iPhone4, iPadMini, iPhone6Plus, iPhone5s, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple3/v4/9a/45/4e/9a454e8e-9e06-4c56-db36-1e1f722bd2a9/mzl.jijngddl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7440149/8f3b5318-f0a2-11e4-9922-9ab7d87eb501.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7440149/8f3b5318-f0a2-11e4-9922-9ab7d87eb501.png)
https://cloud.githubusercontent.com/assets/2068130/7440149/8f3b5318-f0a2-11e4-9922-9ab7d87eb501.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7440150/9ee9452c-f0a2-11e4-9553-5f5be81cffd6.png
