### ISSUE TITLE
Tower Slash

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5629]
**App Name:** Tower Slash
**Bundle ID:** com.marduken.towerslash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=945998991">945998991</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tower-slash/id945998991?mt=8&uo=4">https://itunes.apple.com/us/app/tower-slash/id945998991?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Joao Costa
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/joao-costa/id945998990?uo=4>© Joao Costa</a>
**Supported Devices:** iPhone5, iPad2Wifi, iPodTouchFifthGen, iPhone6, iPhone-3GS, iPhone4, iPhone6Plus, iPadFourthGen, iPhone5c, iPadMini4G, iPhone5s, iPodTouchFourthGen, iPadMini, iPhone4S, iPadThirdGen4G, iPad23G, iPadThirdGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/47/10/2e/47102ebb-2853-975e-42b8-244cca4bb6e8/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8529065/946486d6-23e5-11e5-826e-5311a5792754.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8529065/946486d6-23e5-11e5-826e-5311a5792754.png)
https://cloud.githubusercontent.com/assets/10950389/8529065/946486d6-23e5-11e5-826e-5311a5792754.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8529074/a6c89434-23e5-11e5-8a74-673cc78e8cd7.png

Alternate:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8529281/eb2fb87c-23e6-11e5-96b4-cab56ccaea32.png)
https://cloud.githubusercontent.com/assets/10950389/8529281/eb2fb87c-23e6-11e5-96b4-cab56ccaea32.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8529196/84417ace-23e6-11e5-81d8-a1296ead2878.png

**Comment by dreamnet** [comment]
@zmathiasz The first one is fine - Congratulations, good work! :tada: :+1:
