### ISSUE TITLE
Burn It Down

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5630]
**App Name:** Burn It Down
**Bundle ID:** com.tapinator.burnitdown
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=946927501">946927501</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/burn-it-down/id946927501?mt=8&uo=4">https://itunes.apple.com/us/app/burn-it-down/id946927501?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Tapinator, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tapinator-llc/id605667245?uo=4>© Tapinator,LLC</a>
**Supported Devices:** iPadMini, iPadFourthGen, iPhone-3GS, iPad23G, iPodTouchFifthGen, iPodTouchThirdGen, iPadThirdGen4G, iPodTouchFourthGen, iPhone5, iPhone4, iPad3G, iPhone5c, iPad2Wifi, iPadMini4G, iPhone6, iPadFourthGen4G, iPadThirdGen, iPhone5s, iPhone4S, iPhone6Plus, iPadWifi
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/6c/e0/b5/6ce0b556-e0d0-8820-5295-00691569a5bd/pr_source.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7549024/3906d50c-f625-11e4-9458-d13e4c0a7756.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7549024/3906d50c-f625-11e4-9458-d13e4c0a7756.png)
https://cloud.githubusercontent.com/assets/2068130/7549024/3906d50c-f625-11e4-9458-d13e4c0a7756.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7549026/4929b7c4-f625-11e4-8fb2-3ef94390151d.png
:question:
