### ISSUE TITLE
ONE PIECE TREASURE CRUISE

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5631]
**App Name:** ONE PIECE TREASURE CRUISE
**Bundle ID:** jp.co.bandainamcogames.BNGI0218
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943690848">943690848</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/one-piece-treasure-cruise/id943690848?mt=8&uo=4">https://itunes.apple.com/us/app/one-piece-treasure-cruise/id943690848?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** BANDAI NAMCO Entertainment Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bandai-namco-entertainment/id352305770?uo=4>© BANDAI NAMCO Entertainment Inc.</a>
**Supported Devices:** iPadThirdGen, iPodTouchFifthGen, iPhone5c, iPhone6, iPadFourthGen4G, iPad2Wifi, iPhone-3GS, iPhone4S, iPhone5s, iPadThirdGen4G, iPodTouchFourthGen, iPadMini, iPhone4, iPad23G, iPadFourthGen, iPhone5, iPhone6Plus, iPadMini4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/1a/e3/f5/1ae3f51e-dee8-28ca-5395-368472521e89/mzl.ronsxyxy.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7440486/ba5b59e8-f0b7-11e4-89ab-c1f4c1453d6e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7440486/ba5b59e8-f0b7-11e4-89ab-c1f4c1453d6e.png)
https://cloud.githubusercontent.com/assets/2068130/7440486/ba5b59e8-f0b7-11e4-89ab-c1f4c1453d6e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7440487/c9d17de4-f0b7-11e4-92fb-dc0b6d1c2723.png

**Comment by zmathiasz** [comment]
Yeah. That looks good!

**Comment by dreamnet** [comment]
@zmathiasz THX!
