### ISSUE TITLE
Cars.com

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5632]
**App Name:** Cars.com
**Bundle ID:** com.pointabout.cars
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=353263352">353263352</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cars.com/id353263352?mt=8&uo=4">https://itunes.apple.com/us/app/cars.com/id353263352?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** Cars.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/cars.com/id353263355?uo=4>© Cars.com</a>
**Supported Devices:** iPhone4, iPadFourthGen4G, iPadMini4G, iPhone5c, iPhone5s, iPad2Wifi, iPodTouchFifthGen, iPadMini, iPhone5, iPad23G, iPadFourthGen, iPadThirdGen4G, iPhone6Plus, iPhone4S, iPadThirdGen, iPhone6
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/b0/d8/0e/b0d80e7f-1c2c-dda3-bc2f-9c40c96ed2a0/mzl.xnypvxrl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7440095/ba244ea2-f09f-11e4-8758-262fb83edeb1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7440095/ba244ea2-f09f-11e4-8758-262fb83edeb1.png)
https://cloud.githubusercontent.com/assets/2068130/7440095/ba244ea2-f09f-11e4-8758-262fb83edeb1.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7440098/c7fad622-f09f-11e4-9ba8-3d362dfe086b.png
