### ISSUE TITLE
Pacemaker – Your personal mix. Instantly!

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5633]
**App Name:** Pacemaker – Your personal mix. Instantly!
**Bundle ID:** com.pacemakermusic.pacemaker.001
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=593873080">593873080</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pacemaker-your-personal-mix./id593873080?mt=8&uo=4">https://itunes.apple.com/us/app/pacemaker-your-personal-mix./id593873080?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Pacemaker Music AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pacemaker-music-ab/id593873083?uo=4>© Pacemaker Music AB</a>
**Supported Devices:** iPhone6Plus, iPadThirdGen, iPhone5, iPad2Wifi, iPodTouchFifthGen, iPhone4S, iPadFourthGen, iPadMini, iPadFourthGen4G, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPad23G, iPadThirdGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/a9/b2/c9/a9b2c97e-0c3c-99aa-244d-910f80c873a5/mzl.pxcywbzb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7440049/3c52ceb0-f09d-11e4-87c3-bbe3d18ac722.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7440049/3c52ceb0-f09d-11e4-87c3-bbe3d18ac722.png)
https://cloud.githubusercontent.com/assets/2068130/7440049/3c52ceb0-f09d-11e4-87c3-bbe3d18ac722.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7440050/4b37d68c-f09d-11e4-91d2-ca1520a9c16d.png
