### ISSUE TITLE
MARVEL Future Fight

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5634]
**App Name:** MARVEL Future Fight
**Bundle ID:** com.netmarble.mheros
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955705796">955705796</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/marvel-future-fight/id955705796?mt=8&uo=4">https://itunes.apple.com/us/app/marvel-future-fight/id955705796?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Netmarble Games Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/netmarble-games-corp./id930364579?uo=4>© Netmarble Games Corp.</a>
**Supported Devices:** iPhone4S, iPhone4, iPadMini, iPhone-3GS, iPadFourthGen, iPhone6Plus, iPadThirdGen4G, iPhone5, iPhone5s, iPad23G, iPadMini4G, iPhone5c, iPadThirdGen, iPodTouchFifthGen, iPodTouchFourthGen, iPhone6, iPad2Wifi, iPadFourthGen4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/95/8e/91/958e91e5-385e-65d0-3122-fe400f658b52/mzl.zkhlrbjc.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7802686/6e1aac46-033b-11e5-81a4-f477bb7c9db0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7802686/6e1aac46-033b-11e5-81a4-f477bb7c9db0.png)
https://cloud.githubusercontent.com/assets/2068130/7802686/6e1aac46-033b-11e5-81a4-f477bb7c9db0.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7802688/7d4f5ac2-033b-11e5-888b-a7261de93266.png

**Comment by ivanov007** [comment]
wow, that's insane detail, looks great :+1:

**Comment by dreamnet** [comment]
@ivanov007 THX! I have taken some images from kids coloring books to make this icon... :laughing:
