### ISSUE TITLE
Yo.

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5635]
**App Name:** Yo.
**Bundle ID:** com.yo.yo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834335592">834335592</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yo./id834335592?mt=8&uo=4">https://itunes.apple.com/us/app/yo./id834335592?mt=8&uo=4</a>
**App Version:** 1.6.2
**Seller:** Life Before Us, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/life-before-us-llc/id852376092?uo=4>© Life Before Us, LLC</a>
**Supported Devices:** iPadThirdGen4G, iPadThirdGen, iPhone4, iPadFourthGen, iPhone6, iPhone5, iPad23G, iPodTouchFifthGen, iPadMini, iPad2Wifi, iPadFourthGen4G, iPhone5s, iPhone4S, iPhone5c, iPadMini4G, iPhone6Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/b0/b4/f6/b0b4f6c3-953a-38cc-b83f-72cce7ab793f/mzl.lwqnbqpr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7440246/98cf1692-f0a9-11e4-8436-b3028f91d108.png)

**Comment by Trubbel** [comment]
I have no idea what to do with this icon, would a blank icon suffice?

**Comment by zmathiasz** [comment]
Could use the Yo wiki icon maybe?

http://upload.wikimedia.org/wikipedia/commons/d/dc/Yo_logo.png

**Comment by Trubbel** [comment]
I had no idea that they had a wiki, however I have to go for now, so I'll leave the choice to you if you'd like.

**Comment by dreamnet** [comment]
Well, we don't add a blank icon - I think we can use the logo from the Yo wiki:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7440246/98cf1692-f0a9-11e4-8436-b3028f91d108.png)
https://cloud.githubusercontent.com/assets/2068130/7440246/98cf1692-f0a9-11e4-8436-b3028f91d108.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7440240/561585d4-f0a9-11e4-9c50-c63e50d6a175.png
