### ISSUE TITLE
SceneScope

### ISSUE THREAD

**Issue by KickBooty** [glasklart/hd#5636]
**App Name:** SceneScope
**Bundle ID:** scenescope.scenescope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=870090121">870090121</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scenescope/id870090121?mt=8&uo=4">https://itunes.apple.com/us/app/scenescope/id870090121?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Riley Parsons
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/riley-parsons/id870090124?uo=4>© Riley Parsons</a>
**Supported Devices:** iPadFourthGen4G, iPadMini4G, iPadMini, iPhone5, iPad2Wifi, iPhone5c, iPhone5s, iPadThirdGen4G, iPhone6Plus, iPhone4S, iPhone6, iPodTouchFifthGen, iPadThirdGen, iPadFourthGen, iPad23G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/91/94/08/91940830-1856-8d57-8d2d-318786bd97bf/mzl.plqxofjx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7461216/e0c05488-f2a8-11e4-899c-8d5fa0e73f2b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7461216/e0c05488-f2a8-11e4-899c-8d5fa0e73f2b.png)
https://cloud.githubusercontent.com/assets/2068130/7461216/e0c05488-f2a8-11e4-899c-8d5fa0e73f2b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7461224/efeb7622-f2a8-11e4-8a55-deada15a22a0.png
