### ISSUE TITLE
Australian Taxation Office

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5637]
**App Name:** Australian Taxation Office
**Bundle ID:** au.gov.ato.ATOTax
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=664461825">664461825</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/australian-taxation-office/id664461825?mt=8&uo=4">https://itunes.apple.com/us/app/australian-taxation-office/id664461825?mt=8&uo=4</a>
**App Version:** 5.2.1
**Seller:** Australian Taxation Office
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/australian-taxation-office/id649692098?uo=4>© Australian Taxation Office</a>
**Supported Devices:** iPhone5c, iPhone6, iPad23G, iPadFourthGen4G, iPadThirdGen4G, iPadThirdGen, iPadMini4G, iPhone6Plus, iPhone4S, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPhone5s, iPhone4, iPad2Wifi, iPadMini
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/28/88/38/288838a9-87a5-0e2e-3fb2-72a64567e32a/mzl.ehxrhvuo.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7461127/5e5853c4-f2a8-11e4-98d7-7ef1e6fd22b9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7461127/5e5853c4-f2a8-11e4-98d7-7ef1e6fd22b9.png)
https://cloud.githubusercontent.com/assets/2068130/7461127/5e5853c4-f2a8-11e4-98d7-7ef1e6fd22b9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7461140/71ccb6e8-f2a8-11e4-9e9d-24d8861f42ef.png
