### ISSUE TITLE
Salsas

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5638]
**App Name:** Salsas
**Bundle ID:** au.com.redcat.salsas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=915677179">915677179</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/salsas/id915677179?mt=8&uo=4">https://itunes.apple.com/au/app/salsas/id915677179?mt=8&uo=4</a>
**App Version:** 1.15
**Seller:** RedCat Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/artist/redcat/id429079236?uo=4>© RedCat</a>
**Supported Devices:** iPodTouchFifthGen, iPadMini4G, iPad3G, iPadFourthGen, iPadThirdGen4G, iPhone5c, iPadWifi, iPhone5, iPodTouchFourthGen, iPadThirdGen, iPodTouchThirdGen, iPhone4, iPad2Wifi, iPhone-3GS, iPhone5s, iPhone6, iPhone6Plus, iPadMini, iPhone4S, iPad23G, iPadFourthGen4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/d5/a8/9d/d5a89ddc-db30-dbb5-8de8-a2d425ecc522/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7461043/cabaab58-f2a7-11e4-905e-05b2087686ba.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7461043/cabaab58-f2a7-11e4-905e-05b2087686ba.png)
https://cloud.githubusercontent.com/assets/2068130/7461043/cabaab58-f2a7-11e4-905e-05b2087686ba.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7461059/e00c813e-f2a7-11e4-9663-cdd5951a6cc0.png
