### ISSUE TITLE
FIFA 1904

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5642]
**App Name:** FIFA 1904
**Bundle ID:** com.fifa.fifaweeklyappiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=977986027">977986027</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-fifa-weekly-for-iphone/id977986027?mt=8&uo=4">https://itunes.apple.com/us/app/the-fifa-weekly-for-iphone/id977986027?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** Federation Internationale de Football Association
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fifa/id375974040?uo=4>© FIFA</a>
**Supported Devices:** iPadMini4G, iPodTouchFifthGen, iPad2Wifi, iPadThirdGen, iPhone4S, iPadThirdGen4G, iPadFourthGen, iPhone5s, iPadMini, iPhone6, iPhone6Plus, iPad23G, iPadFourthGen4G, iPhone5c, iPhone5
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60393341-0d854600-9b14-11e9-8742-4bdebbdb48cb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393342-18d87180-9b14-11e9-85a9-33b0fee88106.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7477705/dab359a2-f355-11e4-8800-0bf2f2ec8d30.png)
https://cloud.githubusercontent.com/assets/10730122/7477705/dab359a2-f355-11e4-8800-0bf2f2ec8d30.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7477698/d20ee5a0-f355-11e4-8d5e-f855da2e9b24.png

--

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7477723/00922c98-f356-11e4-88c6-7688ab3d3c4c.png)
https://cloud.githubusercontent.com/assets/10730122/7477723/00922c98-f356-11e4-88c6-7688ab3d3c4c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7477717/f12ee73c-f355-11e4-98c0-7d479fcc6157.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393342-18d87180-9b14-11e9-85a9-33b0fee88106.png)
https://user-images.githubusercontent.com/2068130/60393342-18d87180-9b14-11e9-85a9-33b0fee88106.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60393347-2857ba80-9b14-11e9-8f60-b89df9472b4b.png
