### ISSUE TITLE
Jurassic World™: The Game

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5646]
**App Name:** Jurassic World™: The Game
**Bundle ID:** com.ludia.jurassicworld
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=791211390">791211390</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jurassic-world-the-game/id791211390?mt=8&uo=4">https://itunes.apple.com/us/app/jurassic-world-the-game/id791211390?mt=8&uo=4</a>
**App Version:** 1.1.10
**Seller:** Ludia
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ludia/id293912963?uo=4>© Ludia</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple2/v4/0a/eb/60/0aeb60c3-6f59-7742-5856-e9d31f409532/mzl.qkemsmcw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7486558/a4bebeb0-f36c-11e4-92c7-73c7e4d251ac.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7486519/2ceda23e-f36c-11e4-8b75-5b6fb612f921.png)
https://cloud.githubusercontent.com/assets/3090247/7486519/2ceda23e-f36c-11e4-8b75-5b6fb612f921.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7486520/2d15a57c-f36c-11e4-9a02-5961d006f8c4.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
