### ISSUE TITLE
Fresh Reversi – Othello Like Strategy and Logic Board Game

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5647]
**App Name:** Fresh Reversi – Othello Like Strategy and Logic Board Game
**Bundle ID:** com.alexanderdeplov.Appstore.Fresh-Reversi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=732986215">732986215</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fresh-reversi-othello-like/id732986215?mt=8&uo=4">https://itunes.apple.com/us/app/fresh-reversi-othello-like/id732986215?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** Alexander Deplov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/alexander-deplov/id732986218?uo=4>© Alexander Deplov</a>
**Supported Devices:** iPadThirdGen, iPadThirdGen4G, iPodTouchFifthGen, iPhone6Plus, iPadFourthGen, iPadMini4G, iPhone6, iPadMini, iPadFourthGen4G, iPad23G, iPad2Wifi, iPhone4S, iPhone5, iPhone5s, iPhone4, iPhone5c
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple6/v4/79/90/b4/7990b4f9-a160-5ede-11f2-aa8439a8e375/mzl.hufwgkrk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7548912/c159525a-f61f-11e4-8ddc-9451e67c34b9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7548912/c159525a-f61f-11e4-8ddc-9451e67c34b9.png)
https://cloud.githubusercontent.com/assets/2068130/7548912/c159525a-f61f-11e4-8ddc-9451e67c34b9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7548913/ce6849e2-f61f-11e4-9d9e-7f400fffa1f8.png

**Comment by Trubbel** [comment]
@dreamnet I think that's great!

**Comment by ivanov007** [comment]
me too :+1:
