### ISSUE TITLE
GRE Vocab Genius

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#565]
**App Name:** GRE Vocab Genius
**Bundle ID:** com.brain-scape.sa.c21
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380833751">380833751</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gre-vocab-genius/id380833751?mt=8&uo=4">https://itunes.apple.com/us/app/gre-vocab-genius/id380833751?mt=8&uo=4</a>
**App Version:** 2.20141126
**Seller:** Bold Learning Solutions, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brainscape/id380833754?uo=4>© Brainscape</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/77/89/59/77895931-88c5-c252-45e4-6e4f7c6b5256/mzl.pvxkjggm.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10387621/30678bb0-6e63-11e5-8cef-cb89d0939c75.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10387621/30678bb0-6e63-11e5-8cef-cb89d0939c75.png)
https://cloud.githubusercontent.com/assets/10730122/10387621/30678bb0-6e63-11e5-8cef-cb89d0939c75.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10387618/2d703560-6e63-11e5-99df-25486b35ffe0.png
