### ISSUE TITLE
YoWindow Weather

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5654]
**App Name:** YoWindow Weather
**Bundle ID:** com.repkasoft.yowindow.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606193225">606193225</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yowindow-weather/id606193225?mt=8&uo=4">https://itunes.apple.com/us/app/yowindow-weather/id606193225?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Pavel Repkin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pavel-repkin/id415100913?uo=4">© Pavel Repkin</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/88/a2/d7/88a2d7c6-e9a7-2ee1-87da-e18e67d0e783/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621397-13801a00-a8a6-11e8-813b-c176519826c7.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7524296/40682974-f501-11e4-8b55-95a3ec67141e.png)
https://cloud.githubusercontent.com/assets/10730122/7524296/40682974-f501-11e4-8b55-95a3ec67141e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7524292/355aa69c-f501-11e4-9495-c3ea645f7b92.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621397-13801a00-a8a6-11e8-813b-c176519826c7.png)
https://user-images.githubusercontent.com/2068130/44621397-13801a00-a8a6-11e8-813b-c176519826c7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44621401-2266cc80-a8a6-11e8-81ba-f9ca26892ed8.png
