### ISSUE TITLE
Sensorly–Speedtests & 4G/LTE, CDMA, GSM, Wifi coverage & speed maps

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5655]
**App Name:** Sensorly–Speedtests & 4G/LTE, CDMA, GSM, Wifi coverage & speed maps
**Bundle ID:** com.sensorly.consumer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=544269103">544269103</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sensorly-speedtests-4g-lte/id544269103?mt=8&uo=4">https://itunes.apple.com/us/app/sensorly-speedtests-4g-lte/id544269103?mt=8&uo=4</a>
**App Version:** 3.5.3
**Seller:** Sensorly
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sensorly/id544269106?uo=4>© Sensorly</a>
**Supported Devices:** iPad2Wifi, iPhone4S, iPhone-3GS, iPadFourthGen4G, iPodTouchFifthGen, iPadMini, iPadFourthGen, iPadMini4G, iPad23G, iPhone5, iPhone6, iPadThirdGen4G, iPodTouchFourthGen, iPhone5c, iPhone6Plus, iPhone4, iPadThirdGen, iPhone5s
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/8e/73/19/8e7319c9-e8c1-ac8f-327d-a87ff2dde7a8/mzl.bhrbxdkc.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7545531/2b8325e2-f5d6-11e4-9783-a7a2ae81f8bc.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7545531/2b8325e2-f5d6-11e4-9783-a7a2ae81f8bc.png)
https://cloud.githubusercontent.com/assets/10730122/7545531/2b8325e2-f5d6-11e4-9783-a7a2ae81f8bc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7545525/1cbde11e-f5d6-11e4-940a-22abf298f35c.png

--- ---

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7545557/46ce3ea4-f5d6-11e4-8a0a-1dc95a8ab417.png)
https://cloud.githubusercontent.com/assets/10730122/7545557/46ce3ea4-f5d6-11e4-8a0a-1dc95a8ab417.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7545546/3c0c2332-f5d6-11e4-995f-0961581b4e0f.png

**Comment by ivanov007** [comment]
I kind of like more the first one :+1:

**Comment by dreamnet** [comment]
@Trubbel Please add a public mailadress to your Github account - else I can't make commits in your name.

**Comment by Trubbel** [comment]
@dreamnet Ah, I made it hidden for some reason - it should be public now, thanks.

**Comment by dreamnet** [comment]
@Trubbel :+1:
