### ISSUE TITLE
Awesome Weather YoWindow

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5656]
**App Name:** Awesome Weather YoWindow
**Bundle ID:** com.repkasoft.yowindow.ios.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=799653744">799653744</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/awesome-weather-yowindow/id799653744?mt=8&uo=4">https://itunes.apple.com/us/app/awesome-weather-yowindow/id799653744?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Pavel Repkin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pavel-repkin/id415100913?uo=4">© Pavel Repkin</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/f5/a2/fc/f5a2fc76-07e5-2fb2-554b-7bbf43373e25/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621374-80df7b00-a8a5-11e8-842f-ffb8dbe90a85.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7548907/2c32120c-f61f-11e4-898d-1a3f5a696cc3.png)
https://cloud.githubusercontent.com/assets/2068130/7548907/2c32120c-f61f-11e4-898d-1a3f5a696cc3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7548909/39f14ea8-f61f-11e4-852c-e9d25ca743b4.png

**Comment by dreamnet** [comment]
![-large](https://user-images.githubusercontent.com/2068130/44621374-80df7b00-a8a5-11e8-842f-ffb8dbe90a85.png)
