### ISSUE TITLE
Lifeline...

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5658]
**App Name:** Lifeline...
**Bundle ID:** com.3minutegames.lifeline
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=982354972">982354972</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lifeline.../id982354972?mt=8&uo=4">https://itunes.apple.com/us/app/lifeline.../id982354972?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** 3 Minute Games, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/3-minute-games-llc/id920182716?uo=4>© 3 Minute Games, LLC</a>
**Supported Devices:** iPadMini4G, iPhone6Plus, iPadFourthGen4G, iPhone6, iPhone5s, iPhone5, iPadThirdGen4G, iPadFourthGen, iPadThirdGen, iPadMini, iPad2Wifi, iPad23G, iPodTouchFifthGen, iPhone5c, iPhone4S
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/e9/2d/8b/e92d8bf6-6311-eed0-a4af-7277288e867d/mzl.wuwtkrxp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7665411/90d26c34-fbb5-11e4-925b-738c3d4b1bc0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7665411/90d26c34-fbb5-11e4-925b-738c3d4b1bc0.png)
https://cloud.githubusercontent.com/assets/2068130/7665411/90d26c34-fbb5-11e4-925b-738c3d4b1bc0.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7665420/a13ef9c0-fbb5-11e4-8a25-7da001358362.png
:question:

**Comment by ivanov007** [comment]
:open_mouth: looks great :+1:
