### ISSUE TITLE
Ta Körkort - Körkortsteori för B-körkort

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5659]
**App Name:** Ta Körkort - Körkortsteori för B-körkort
**Bundle ID:** com.part.takorat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=808891775">808891775</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ta-korkort-korkortsteori-for/id808891775?mt=8&uo=4">https://itunes.apple.com/us/app/ta-korkort-korkortsteori-for/id808891775?mt=8&uo=4</a>
**App Version:** 3.0.6
**Seller:** Patrik Jansson
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/patrik-jansson/id808891778?uo=4>© Patrik Jansson</a>
**Supported Devices:** iPadThirdGen4G, iPhone5s, iPodTouchFifthGen, iPadMini4G, iPad23G, iPadFourthGen, iPhone5, iPadFourthGen4G, iPadMini, iPhone6, iPadThirdGen, iPhone5c, iPhone4, iPad2Wifi, iPhone6Plus, iPhone4S
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/b0/2e/5c/b02e5ca3-c5ca-0cc0-9132-c5d329759e96/pr_source.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7648265/58fe4b36-fae1-11e4-9695-01f4c0888482.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7648265/58fe4b36-fae1-11e4-9695-01f4c0888482.png)
https://cloud.githubusercontent.com/assets/10730122/7648265/58fe4b36-fae1-11e4-9695-01f4c0888482.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7648264/4ff2a776-fae1-11e4-9baa-2f0f0e8e32fa.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
