### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#566]
**App Name:** Vimeo
**Bundle ID:** com.vimeo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=425194759">425194759</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vimeo/id425194759?mt=8&uo=4">https://itunes.apple.com/us/app/vimeo/id425194759?mt=8&uo=4</a>
**App Version:** 7.7.0
**Seller:** Vimeo
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vimeo-llc/id425194762?mt=8&uo=4">© Vimeo, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/83/8b/6d/838b6d70-3b31-8738-2018-c09065f4fad1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54511551-8f7ca500-4951-11e9-8074-fbcc4754d0e4.png)

**Comment by dreamnet** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54511551-8f7ca500-4951-11e9-8074-fbcc4754d0e4.png)
(https://user-images.githubusercontent.com/20930745/54511551-8f7ca500-4951-11e9-8074-fbcc4754d0e4.png

Source:
https://user-images.githubusercontent.com/20930745/54511552-90add200-4951-11e9-9ee6-3bfb01d01d9e.png
