### ISSUE TITLE
Opera Coast web browser

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5660]
**App Name:** Opera Coast web browser
**Bundle ID:** com.opera.Coast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=674024845">674024845</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/opera-coast-web-browser/id674024845?mt=8&uo=4">https://itunes.apple.com/us/app/opera-coast-web-browser/id674024845?mt=8&uo=4</a>
**App Version:** 4.21
**Seller:** Opera Software ASA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/opera-software-asa/id363729563?uo=4>© Opera Software ASA</a>
**Supported Devices:** iPadMini4G, iPhone5, iPad2Wifi, iPhone6, iPadThirdGen, iPhone4, iPhone5c, iPodTouchFifthGen, iPhone4S, iPadMini, iPad23G, iPadFourthGen, iPadThirdGen4G, iPadFourthGen4G, iPhone5s, iPhone6Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/46/b3/22/46b32232-04e3-7067-e4d0-4bb0f1ad5d8f/mzl.vsxflofn.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7648375/9c916b70-fae2-11e4-9567-b8a81320a7f9.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7648375/9c916b70-fae2-11e4-9567-b8a81320a7f9.png)
https://cloud.githubusercontent.com/assets/10730122/7648375/9c916b70-fae2-11e4-9567-b8a81320a7f9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7648370/8f0aefda-fae2-11e4-928b-d3dd6e9e3332.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
