### ISSUE TITLE
Dagens Utgifter

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5661]
**App Name:** Dagens Utgifter
**Bundle ID:** se.younger.Dagens-Utgifter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=970000424">970000424</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/dagens-utgifter/id970000424?mt=8&uo=4">https://itunes.apple.com/se/app/dagens-utgifter/id970000424?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Fredrik Christensson
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/artist/fredrik-christensson/id970000423?uo=4>© Fredrik Christensson</a>
**Supported Devices:** iPhone5, iPadFourthGen, iPhone5c, iPhone5s, iPhone4S, iPadMini4G, iPhone6Plus, iPadFourthGen4G, iPadMini, iPad23G, iPadThirdGen, iPhone6, iPadThirdGen4G, iPodTouchFifthGen, iPad2Wifi
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/04/cb/30/04cb3058-a229-0507-f14d-8fa46a0596f2/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7648510/111a0c30-fae4-11e4-93f9-8a88fb0239d5.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7648510/111a0c30-fae4-11e4-93f9-8a88fb0239d5.png)
https://cloud.githubusercontent.com/assets/10730122/7648510/111a0c30-fae4-11e4-93f9-8a88fb0239d5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7648502/ffa41e6e-fae3-11e4-8417-0e9c16a5e999.png

**Comment by dreamnet** [comment]
@Trubbel Jup! :+1:
