### ISSUE TITLE
oPenGP

### ISSUE THREAD

**Issue by stonewareslord** [glasklart/hd#5662]
**App Name:** oPenGP
**Bundle ID:** com.gdescamps.oPenGP
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=414003727">414003727</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/opengp/id414003727?mt=8&uo=4">https://itunes.apple.com/us/app/opengp/id414003727?mt=8&uo=4</a>
**App Version:** 6.0.3
**Seller:** grégory descamps
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/gregory-descamps/id395985835?uo=4>© grégory descamps</a>
**Supported Devices:** iPhone5s, iPhone6Plus, iPad2Wifi, iPad23G, iPadFourthGen, iPadMini, iPhone5, iPhone5c, iPadThirdGen4G, iPadMini4G, iPadFourthGen4G, iPodTouchFifthGen, iPhone4, iPhone6, iPhone4S, iPadThirdGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/07/2c/87/072c8722-c2b7-f521-491e-a7586324ad3b/mzl.zsbmjebz.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7667899/958f3c80-fc1d-11e4-843b-29ecdb79b2d6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7667899/958f3c80-fc1d-11e4-843b-29ecdb79b2d6.png)
https://cloud.githubusercontent.com/assets/2068130/7667899/958f3c80-fc1d-11e4-843b-29ecdb79b2d6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7667903/a32db27c-fc1d-11e4-8306-8d6f6a3bdc42.png
