### ISSUE TITLE
CameraSync

### ISSUE THREAD

**Issue by stonewareslord** [glasklart/hd#5663]
**App Name:** CameraSync
**Bundle ID:** com.homegrownsw.camerasync
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406645727">406645727</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camerasync/id406645727?mt=8&uo=4">https://itunes.apple.com/us/app/camerasync/id406645727?mt=8&uo=4</a>
**App Version:** 1.5.9
**Seller:** Homegrown Software Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/homegrown-software-ltd/id406645730?uo=4>© Homegrown Software Ltd</a>
**Supported Devices:** iPhone-3GS, iPadFourthGen4G, iPodTouchFifthGen, iPhone5c, iPhone5, iPadMini, iPhone4, iPadMini4G, iPhone6Plus, iPad23G, iPodTouchFourthGen, iPad2Wifi, iPhone4S, iPadThirdGen, iPhone5s, iPadThirdGen4G, iPhone6, iPadFourthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/f2/c6/32/f2c63200-9805-3bba-4a6b-7adacbde2674/mzl.xrgctleq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7667843/49e1ce7c-fc1a-11e4-82e8-364bc3d76718.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7667843/49e1ce7c-fc1a-11e4-82e8-364bc3d76718.png)
https://cloud.githubusercontent.com/assets/2068130/7667843/49e1ce7c-fc1a-11e4-82e8-364bc3d76718.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7667844/57b3e0f8-fc1a-11e4-8b34-205ab6e83b0e.png
