### ISSUE TITLE
Map My Walk - GPS Walking and Step Tracking Pedometer for Calories and Weight Loss

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5665]
**App Name:** Map My Walk - GPS Walking and Step Tracking Pedometer for Calories and Weight Loss
**Bundle ID:** Q5AWL8WCY6.iMapMyWalkFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307861492">307861492</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/map-my-walk-gps-walking-step/id307861492?mt=8&uo=4">https://itunes.apple.com/us/app/map-my-walk-gps-walking-step/id307861492?mt=8&uo=4</a>
**App Version:** 5.10.2
**Seller:** MapMyFitness
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mapmyfitness/id291890423?uo=4>© MapMyFitness</a>
**Supported Devices:** iPhone6Plus, iPadMini4G, iPodTouchFifthGen, iPhone6, iPadThirdGen4G, iPhone4S, iPadFourthGen, iPadThirdGen, iPhone5s, iPadMini, iPad2Wifi, iPadFourthGen4G, iPhone4, iPhone5c, iPad23G, iPhone5
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/03/b0/b1/03b0b10f-448d-12f1-3a39-c9a5a8139f75/mzl.txvamsej.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7696110/00819032-fdfa-11e4-92bf-7e410fcfb6a5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7696110/00819032-fdfa-11e4-92bf-7e410fcfb6a5.png)
https://cloud.githubusercontent.com/assets/2068130/7696110/00819032-fdfa-11e4-92bf-7e410fcfb6a5.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7696114/0e6490be-fdfa-11e4-903d-72a95441ba9b.png
