### ISSUE TITLE
World Series of Poker - WSOP Texas Holdem Free Casino

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5666]
**App Name:** World Series of Poker - WSOP Texas Holdem Free Casino
**Bundle ID:** com.playtika.wsop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=719525810">719525810</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/world-series-poker-wsop-texas/id719525810?mt=8&uo=4">https://itunes.apple.com/us/app/world-series-poker-wsop-texas/id719525810?mt=8&uo=4</a>
**App Version:** 2.8.0
**Seller:** Playtika LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/playtika-ltd/id447553567?uo=4>© Playtika LTD</a>
**Supported Devices:** iPhone4, iPadMini, iPhone4S, iPhone6, iPhone6Plus, iPad2Wifi, iPhone5s, iPodTouchFourthGen, iPadThirdGen4G, iPhone-3GS, iPhone5, iPadFourthGen4G, iPhone5c, iPadFourthGen, iPodTouchFifthGen, iPad23G, iPadThirdGen, iPadMini4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/fa/1d/4e/fa1d4ea9-32a3-6fe1-8b0a-50059fc2871c/mzl.cplwvctu.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7797095/e45e2e54-02e7-11e5-8557-409d317ff764.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7797095/e45e2e54-02e7-11e5-8557-409d317ff764.png)
https://cloud.githubusercontent.com/assets/2068130/7797095/e45e2e54-02e7-11e5-8557-409d317ff764.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7797100/f2ff988a-02e7-11e5-98c7-a736f4a4c4ce.png)

**Comment by Trubbel** [comment]
@dreamnet Looks great!

**Comment by dreamnet** [comment]
@Trubbel THX!
