### ISSUE TITLE
American Express Unstaged - Taylor Swift Experience

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5667]
**App Name:** American Express Unstaged - Taylor Swift Experience
**Bundle ID:** com.americanexpress.intl.unstagedapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=939286016">939286016</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/american-express-unstaged/id939286016?mt=8&uo=4">https://itunes.apple.com/gb/app/american-express-unstaged/id939286016?mt=8&uo=4</a>
**App Version:** 1.01
**Seller:** American Express
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/artist/american-express/id362348519?uo=4>© American Express</a>
**Supported Devices:** iPhone5s, iPadFourthGen4G, iPadMini4G, iPhone5c, iPhone5, iPhone4S, iPodTouchFifthGen, iPadThirdGen4G, iPhone4, iPadMini, iPhone6Plus, iPad23G, iPhone6, iPadThirdGen, iPadFourthGen, iPad2Wifi
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/18/3f/9e/183f9e68-4606-e9ff-371e-a16053138890/mzl.okaycmyq.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7696186/d4d809b0-fdfa-11e4-9ee7-46b7e987468d.png)

**Comment by dreamnet** [comment]
@katakolo Why closed?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7696186/d4d809b0-fdfa-11e4-9ee7-46b7e987468d.png)
https://cloud.githubusercontent.com/assets/2068130/7696186/d4d809b0-fdfa-11e4-9ee7-46b7e987468d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7696189/e26462cc-fdfa-11e4-9953-29d9d80cc6e7.png
