### ISSUE TITLE
South Park

### ISSUE THREAD

**Issue by pishit** [glasklart/hd#5669]
**App Name:** South Park
**Bundle ID:** com.comedycentral.southpark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=785272769">785272769</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/south-park/id785272769?mt=8&uo=4">https://itunes.apple.com/de/app/south-park/id785272769?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** VIMN Germany GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/vimn-germany-gmbh/id406495823?uo=4>© VIMN Germany GmbH</a>
**Supported Devices:** iPadThirdGen, iPhone4S, iPad2Wifi, iPadThirdGen4G, iPhone5, iPhone6Plus, iPad23G, iPhone4, iPodTouchFifthGen, iPadFourthGen4G, iPadFourthGen, iPadMini, iPhone5c, iPadMini4G, iPhone6, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/49/07/8a/49078a6a-f50d-ac3e-a1cb-5137c9824c49/mzl.wcyrepyl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7980684/bf575012-0aa9-11e5-9853-6830adf1f6d2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7980684/bf575012-0aa9-11e5-9853-6830adf1f6d2.png)
https://cloud.githubusercontent.com/assets/2068130/7980684/bf575012-0aa9-11e5-9853-6830adf1f6d2.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7980688/ce30977e-0aa9-11e5-87dd-fbebbef36f57.png

**Comment by Trubbel** [comment]
@dreamnet Looks great! :+1:
