### ISSUE TITLE
Amazon Prime Video

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#567]
**App Name:** Amazon Prime Video
**Bundle ID:** com.amazon.aiv.AIVApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=545519333">545519333</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amazon-prime-video/id545519333?mt=8&uo=4">https://itunes.apple.com/us/app/amazon-prime-video/id545519333?mt=8&uo=4</a>
**App Version:** 5.3
**Seller:** AMZN Mobile LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amzn-mobile-llc/id297606954?uo=4">© AMZN Mobile LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/dc/01/ad/dc01ad3c-2302-51d3-885e-92a36b2459b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455543-fd532366-3a79-11e8-999c-6a65ec54d470.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8.
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455543-fd532366-3a79-11e8-999c-6a65ec54d470.png)
https://user-images.githubusercontent.com/20930745/38455543-fd532366-3a79-11e8-999c-6a65ec54d470.png
--- ---
Source:
https://user-images.githubusercontent.com/20930745/38455548-0c3d0ebe-3a7a-11e8-9e27-85d8b547d4f1.png
