### ISSUE TITLE
Jelly Jump

### ISSUE THREAD

**Issue by pishit** [glasklart/hd#5670]
**App Name:** Jelly Jump
**Bundle ID:** com.ketchapp.jellyjump
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955327604">955327604</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jelly-jump/id955327604?mt=8&uo=4">https://itunes.apple.com/us/app/jelly-jump/id955327604?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Ketchapp
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ketchapp/id528065807?uo=4>© Ketchapp</a>
**Supported Devices:** iPadThirdGen, iPadMini4G, iPhone-3GS, iPhone5c, iPhone4S, iPad3G, iPad2Wifi, iPhone6, iPhone4, iPodTouchFourthGen, iPadWifi, iPhone5, iPhone5s, iPad23G, iPhone6Plus, iPadFourthGen, iPadThirdGen4G, iPodTouchThirdGen, iPodTouchFifthGen, iPadMini, iPadFourthGen4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/7a/9c/a4/7a9ca4d4-2c7e-edae-1168-db66682af2f1/mzl.zgflzlxs.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7761513/6a250872-ffec-11e4-8b13-3217e2eae849.png)

**Comment by ivanov007** [comment]
it looks a little weird but here it is:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7761312/e6b156d2-ffe9-11e4-9593-206f53dc33c3.png)
https://cloud.githubusercontent.com/assets/3090247/7761312/e6b156d2-ffe9-11e4-9593-206f53dc33c3.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7761311/e682619c-ffe9-11e4-929a-540b0ff1f26e.png

**Comment by MagnaMike** [comment]
@ivanov007 Nah, I like it. :+1:
