### ISSUE TITLE
iDownloader - Downloads and Download Manager!

### ISSUE THREAD

**Issue by pishit** [glasklart/hd#5671]
**App Name:** iDownloader - Downloads and Download Manager!
**Bundle ID:** com.apps4stars.idlfree3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916222321">916222321</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/idownloader-downloads-download/id916222321?mt=8&uo=4">https://itunes.apple.com/us/app/idownloader-downloads-download/id916222321?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** AP Technologies Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/apps4stars/id585600867?uo=4>© Apps4Stars</a>
**Supported Devices:** iPadThirdGen, iPodTouchFifthGen, iPad23G, iPhone4, iPhone5s, iPhone6, iPadMini, iPhone-3GS, iPadFourthGen, iPadMini4G, iPadThirdGen4G, iPhone5, iPodTouchFourthGen, iPad2Wifi, iPhone6Plus, iPadFourthGen4G, iPhone4S, iPhone5c
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/e5/65/99/e56599d8-a40e-a887-8781-82802ca666d5/mzl.jxrcwmcs.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7760999/7faccf0a-ffe6-11e4-96d9-dbf7169a37b5.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7761000/7fb00242-ffe6-11e4-9c39-2bae3106dcf8.png)
https://cloud.githubusercontent.com/assets/3090247/7761000/7fb00242-ffe6-11e4-9c39-2bae3106dcf8.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7760999/7faccf0a-ffe6-11e4-96d9-dbf7169a37b5.png
