### ISSUE TITLE
Badoo - The Dating App

### ISSUE THREAD

**Issue by pishit** [glasklart/hd#5672]
**App Name:** Badoo - The Dating App
**Bundle ID:** com.badoo.Badoo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=351331194">351331194</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/badoo-the-dating-app/id351331194?mt=8&uo=4">https://itunes.apple.com/us/app/badoo-the-dating-app/id351331194?mt=8&uo=4</a>
**App Version:** 5.75.0
**Seller:** Badoo Software Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/badoo-software-ltd/id351331197?uo=4">© Badoo Software Ltd</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/45/74/a1/4574a18c-fdb9-cc81-c869-e12705908f46/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44625702-eff1b980-a90f-11e8-9824-c58e32457041.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7761124/966d8ce2-ffe7-11e4-8bf6-cf9e88e579d0.png)
https://cloud.githubusercontent.com/assets/3090247/7761124/966d8ce2-ffe7-11e4-8bf6-cf9e88e579d0.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7761123/966bf904-ffe7-11e4-8d55-3774ba3accaf.png

**Comment by Trubbel** [comment]
This application does not get themed for me, and the bundle ID is the same. Any ideas?
