### ISSUE TITLE
LOVOO - People like you. New chat app for interests, photos and live moments of your friends

### ISSUE THREAD

**Issue by pishit** [glasklart/hd#5673]
**App Name:** LOVOO - People like you. New chat app for interests, photos and live moments of your friends
**Bundle ID:** com.kiss2go.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445338486">445338486</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lovoo-people-like-you.-new/id445338486?mt=8&uo=4">https://itunes.apple.com/us/app/lovoo-people-like-you.-new/id445338486?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** LOVOO GmbH apps
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/lovoo-gmbh-apps/id445338489?uo=4>© LOVOO GmbH apps</a>
**Supported Devices:** iPadMini, iPadThirdGen, iPhone4, iPadMini4G, iPad2Wifi, iPhone6, iPhone5s, iPhone5c, iPhone6Plus, iPadFourthGen4G, iPadFourthGen, iPhone4S, iPodTouchFifthGen, iPhone5, iPad23G, iPadThirdGen4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/7c/b9/47/7cb9477b-3e2c-86f7-5992-c8faaa76db43/mzl.hmrcxvwa.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7761476/df42aff2-ffeb-11e4-9ef5-ca1a1924c468.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7761223/dbe57cfc-ffe8-11e4-87b4-33996ef6b581.png)
https://cloud.githubusercontent.com/assets/3090247/7761223/dbe57cfc-ffe8-11e4-87b4-33996ef6b581.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7761224/dbef761c-ffe8-11e4-9394-dabbb5b7ba71.png
