### ISSUE TITLE
NT

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5676]
**App Name:** NT
**Bundle ID:** se.nt.NT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=983931111">983931111</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nt/id983931111?mt=8&uo=4">https://itunes.apple.com/us/app/nt/id983931111?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Norrkoping Tidningars Media AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ntm-ab/id399647256?uo=4>© NTM AB</a>
**Supported Devices:** iPodTouchFifthGen, iPad2Wifi, iPadThirdGen, iPad23G, iPadMini, iPhone6, iPadFourthGen, iPhone4S, iPadThirdGen4G, iPadFourthGen4G, iPhone5c, iPhone6Plus, iPadMini4G, iPhone5, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/42/b1/f3/42b1f351-9216-ec2e-5650-92eea792c70e/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7785178/f9e8feee-0183-11e5-9c7e-33ac8440972b.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7785178/f9e8feee-0183-11e5-9c7e-33ac8440972b.png)
https://cloud.githubusercontent.com/assets/10730122/7785178/f9e8feee-0183-11e5-9c7e-33ac8440972b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7785177/eb23eb12-0183-11e5-9659-449075c87e1e.png

**Comment by MagnaMike** [comment]
@Trubbel :+1:
