### ISSUE TITLE
Squares - Minimal, addictive and extremely challenging.

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#5677]
**App Name:** Squares - Minimal, addictive and extremely challenging.
**Bundle ID:** com.btaylr.squares
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=990570123">990570123</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/squares-minimal-addictive/id990570123?mt=8&uo=4">https://itunes.apple.com/us/app/squares-minimal-addictive/id990570123?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Benji Taylor
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/benji-taylor/id990570122?uo=4>© Benji Taylor</a>
**Supported Devices:** iPhone6, iPad2Wifi, iPhone5c, iPhone5, iPadMini, iPodTouchThirdGen, iPodTouchFifthGen, iPhone5s, iPadThirdGen4G, iPadMini4G, iPhone-3GS, iPhone6Plus, iPad3G, iPodTouchFourthGen, iPadFourthGen, iPad23G, iPadThirdGen, iPhone4S, iPadWifi, iPadFourthGen4G, iPhone4
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/78/86/68/7886682c-1c06-e32e-ba05-fa24c8084cea/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7797160/a71d786e-02e8-11e5-8056-e470ca1e4fb9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7797160/a71d786e-02e8-11e5-8056-e470ca1e4fb9.png)
https://cloud.githubusercontent.com/assets/2068130/7797160/a71d786e-02e8-11e5-8056-e470ca1e4fb9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7797172/b7d845f8-02e8-11e5-9b1f-7d5e53be77fc.png
:question: ...I don't have any other idea... :question:

**Comment by MagnaMike** [comment]
@dreamnet Is fine I think

**Comment by ivanov007** [comment]
yup, that's the best approach :8ball:
