### ISSUE TITLE
Prisjakt

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5678]
**App Name:** Prisjakt
**Bundle ID:** se.prisjakt.prisjakt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=369151774">369151774</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/prisjakt/id369151774?mt=8&uo=4">https://itunes.apple.com/se/app/prisjakt/id369151774?mt=8&uo=4</a>
**App Version:** 3.5.4
**Seller:** Prisjakt Sverige AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/artist/prisjakt/id369151777?uo=4>© Prisjakt</a>
**Supported Devices:** iPad2Wifi, iPadMini, iPhone6, iPadThirdGen4G, iPhone4, iPodTouchFifthGen, iPhone5c, iPadMini4G, iPhone4S, iPadFourthGen4G, iPad23G, iPadFourthGen, iPhone5s, iPadThirdGen, iPhone6Plus, iPhone5
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/21/39/82/2139820e-8b41-6b4f-b7ff-fb27f0a87fe9/mzl.fhmsvwyg.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7786114/848abab8-017c-11e5-8b10-a5086ee5c8d1.png)

**Comment by Trubbel** [comment]
I couldn't find an existing issue for this application, only the image itself from **file finder**, however, the icon has been updated so I decided to make a new issue.

*Current Glasklart icon, 
![](http://preview.dreamnet.at/?image=https://raw.githubusercontent.com/glasklart/hd/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/se.prisjakt.prisjakt%402x.png)
https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/se.prisjakt.prisjakt@2x.png*

**Comment by ivanov007** [comment]
@Trubbel thanks for noticing :+1:

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7786114/848abab8-017c-11e5-8b10-a5086ee5c8d1.png)
https://cloud.githubusercontent.com/assets/3090247/7786114/848abab8-017c-11e5-8b10-a5086ee5c8d1.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7786115/868475fc-017c-11e5-801a-e828562f3878.png

**Comment by Trubbel** [comment]
@ivanov007 :+1:
