### ISSUE TITLE
Smack That Gugl

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#568]
**App Name:** Smack That Gugl
**Bundle ID:** com.hikari.smackthatgugl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=399763903">399763903</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smack-that-gugl/id399763903?mt=8&uo=4">https://itunes.apple.com/us/app/smack-that-gugl/id399763903?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** yann le coroller
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tayasui-com/id359375853?uo=4">© Tayasui.com</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple6/v4/e7/46/34/e746346c-a1eb-2329-5d33-fb31bf662af6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39472902-646d9452-4d4c-11e8-91cc-1d263912b0c8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39472902-646d9452-4d4c-11e8-91cc-1d263912b0c8.png)
https://user-images.githubusercontent.com/2068130/39472902-646d9452-4d4c-11e8-91cc-1d263912b0c8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39472919-74d7b282-4d4c-11e8-9fc3-ee20fe00d4ac.png
