### ISSUE TITLE
Math Racer 3.0 - Addition, Subtraction, Multiplication and Division Tables Speed Game

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5682]
**App Name:** Math Racer 3.0 - Addition, Subtraction, Multiplication and Division Tables Speed Game
**Bundle ID:** com.i4software.mathracer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393772005">393772005</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/math-racer-3.0-addition-subtraction/id393772005?mt=8&uo=4">https://itunes.apple.com/us/app/math-racer-3.0-addition-subtraction/id393772005?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** ESS International Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/i4software/id376546133?uo=4>© i4software</a>
**Supported Devices:** iPhone6Plus, iPadFourthGen4G, iPodTouchThirdGen, iPodTouchFifthGen, iPad23G, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPadFourthGen, iPhone-3GS, iPadMini, iPhone5, iPad3G, iPhone5s, iPadWifi, iPhone4S, iPadMini4G, iPadThirdGen, iPhone5c, iPhone6, iPadThirdGen4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/52/14/cc/5214cc36-b547-406d-422f-df441484a35b/mzl.ouynloyy.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7795648/3f76ab88-02d7-11e5-92d9-adaf01e88599.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7795648/3f76ab88-02d7-11e5-92d9-adaf01e88599.png)
https://cloud.githubusercontent.com/assets/2068130/7795648/3f76ab88-02d7-11e5-92d9-adaf01e88599.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7795661/52bb374a-02d7-11e5-97a5-a7d1d36e0f6f.png
