### ISSUE TITLE
AppEvent - gratis apps

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5683]
**App Name:** AppEvent - gratis apps
**Bundle ID:** Nathan-Sakoetoe-App2.AppEvent
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=530203491">530203491</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appevent-gratis-apps/id530203491?mt=8&uo=4">https://itunes.apple.com/us/app/appevent-gratis-apps/id530203491?mt=8&uo=4</a>
**App Version:** 3.2.1
**Seller:** MCM Publishers
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mcm-publishers/id389743664?uo=4>© MCM Publishers</a>
**Supported Devices:** iPhone6, iPadFourthGen, iPhone4, iPhone5c, iPodTouchFifthGen, iPodTouchFourthGen, iPad2Wifi, iPhone4S, iPadThirdGen4G, iPhone5, iPhone6Plus, iPadMini, iPhone5s, iPhone-3GS, iPadThirdGen, iPadFourthGen4G, iPadMini4G, iPad23G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple/v4/42/98/10/42981044-8934-c50a-3c01-4cbbc284a5ef/mzl.lopsjzuk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7796127/6e037aa8-02dc-11e5-9b51-08d0651b7a04.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7796127/6e037aa8-02dc-11e5-9b51-08d0651b7a04.png)
https://cloud.githubusercontent.com/assets/10730122/7796127/6e037aa8-02dc-11e5-9b51-08d0651b7a04.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7796122/62ff4a06-02dc-11e5-8d11-14a0104f8eda.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
