### ISSUE TITLE
Passible Password Manager. Passwords vault & secure login in 1

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5684]
**App Name:** Passible Password Manager. Passwords vault & secure login in 1
**Bundle ID:** com.heavydutyapps.passiblepro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=793980139">793980139</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/passible-password-manager./id793980139?mt=8&uo=4">https://itunes.apple.com/us/app/passible-password-manager./id793980139?mt=8&uo=4</a>
**App Version:** 3.16
**Seller:** Clear Sky Apps LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/clear-sky-apps-ltd/id383171664?uo=4>© Clear Sky Apps LTD</a>
**Supported Devices:** iPadThirdGen4G, iPhone4, iPhone4S, iPhone5s, iPad23G, iPadFourthGen4G, iPadMini4G, iPhone5c, iPodTouchFifthGen, iPhone6, iPad2Wifi, iPhone6Plus, iPadMini, iPhone5, iPadFourthGen, iPadThirdGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/11/f6/a7/11f6a7cb-ad60-9ecd-5ac7-8b838acadf12/mzl.naraojeo.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7796810/cb4f221e-02e3-11e5-99cc-7fa76fbab624.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7796377/2942ca06-02df-11e5-9df4-e757b568f078.png)
https://cloud.githubusercontent.com/assets/10730122/7796377/2942ca06-02df-11e5-9df4-e757b568f078.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7796371/192255ba-02df-11e5-9acd-7ae520b8a03e.png
--- ---
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7796391/41cc55d8-02df-11e5-88a8-1c36a7e9eec2.png)
https://cloud.githubusercontent.com/assets/10730122/7796391/41cc55d8-02df-11e5-88a8-1c36a7e9eec2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7796384/3613f1c4-02df-11e5-9714-34da13945d6f.png

**Comment by dreamnet** [comment]
...or this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7796583/0306073e-02e1-11e5-9285-7816456c2b1b.png)
https://cloud.githubusercontent.com/assets/2068130/7796583/0306073e-02e1-11e5-9285-7816456c2b1b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7796590/1066e2cc-02e1-11e5-9dbc-2bcc282c49d9.png

**Comment by Trubbel** [comment]
Yeah, yours is much better.

**Comment by dreamnet** [comment]
Added some Details:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7796810/cb4f221e-02e3-11e5-99cc-7fa76fbab624.png)
https://cloud.githubusercontent.com/assets/2068130/7796810/cb4f221e-02e3-11e5-99cc-7fa76fbab624.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7796816/d96e4a50-02e3-11e5-8d4b-7bb05459dc72.png

**Comment by Trubbel** [comment]
@dreamnet :+1:
