### ISSUE TITLE
Calorie Counter by FatSecret

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5685]
**App Name:** Calorie Counter by FatSecret
**Bundle ID:** com.fatsecret.caloriecounter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347184248">347184248</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calorie-counter-by-fatsecret/id347184248?mt=8&uo=4">https://itunes.apple.com/us/app/calorie-counter-by-fatsecret/id347184248?mt=8&uo=4</a>
**App Version:** 6.0.2
**Seller:** Secret Industries Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fatsecret/id347184251?uo=4>© FatSecret</a>
**Supported Devices:** iPhone6Plus, iPadThirdGen, iPhone5c, iPadFourthGen4G, iPhone5, iPadMini4G, iPadThirdGen4G, iPadFourthGen, iPadMini, iPodTouchFifthGen, iPhone4, iPad23G, iPhone6, iPhone4S, iPad2Wifi, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/bd/67/8a/bd678a0e-baf7-3a58-847c-f1f4cf277c98/mzl.ddkzyzbw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7796226/6c2e155c-02dd-11e5-8846-74c7273f7513.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7796203/45746236-02dd-11e5-8a70-869decae04d3.png)
https://cloud.githubusercontent.com/assets/10730122/7796203/45746236-02dd-11e5-8a70-869decae04d3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7796199/347247dc-02dd-11e5-8ac0-45548fe4b9a9.png
--- ---
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7796226/6c2e155c-02dd-11e5-8846-74c7273f7513.png)
https://cloud.githubusercontent.com/assets/10730122/7796226/6c2e155c-02dd-11e5-8846-74c7273f7513.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7796214/5a5cf3c0-02dd-11e5-861a-8de474914a98.png

**Comment by dreamnet** [comment]
@Trubbel Hm, the second one. :+1:
