### ISSUE TITLE
Mumble

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5687]
**App Name:** Mumble
**Bundle ID:** info.mumble.Mumble
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=443472808">443472808</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mumble/id443472808?mt=8&uo=4">https://itunes.apple.com/us/app/mumble/id443472808?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** Mikkel Krautz
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mikkel-krautz/id392493641?uo=4>© Mikkel Krautz</a>
**Supported Devices:** iPhone4S, iPhone6Plus, iPhone5, iPhone6, iPad2Wifi, iPhone4, iPhone5s, iPadMini, iPadFourthGen4G, iPhone-3GS, iPadThirdGen, iPad23G, iPadFourthGen, iPodTouchFifthGen, iPadMini4G, iPadWifi, iPad3G, iPadThirdGen4G, iPodTouchFourthGen, iPhone5c, iPodTouchThirdGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple/v4/e6/e8/be/e6e8be00-60e8-e2fa-69f3-0d654371dba5/mzl.unicbbqr.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7817612/5cd27496-03d6-11e5-9663-38e38676f3d0.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7817612/5cd27496-03d6-11e5-9663-38e38676f3d0.png)
https://cloud.githubusercontent.com/assets/10730122/7817612/5cd27496-03d6-11e5-9663-38e38676f3d0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7817603/541473d6-03d6-11e5-8400-3cce0588d33c.png

**Comment by dreamnet** [comment]
@Trubbel Yessir! :+1:
