### ISSUE TITLE
IBX

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#5688]
**App Name:** IBX
**Bundle ID:** com.ibx.ibxmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=584785907">584785907</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ibx/id584785907?mt=8&uo=4">https://itunes.apple.com/us/app/ibx/id584785907?mt=8&uo=4</a>
**App Version:** 2.8
**Seller:** Independence Blue Cross
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/independence-blue-cross/id431858152?uo=4>© Independence Blue Cross</a>
**Supported Devices:** iPadMini4G, iPhone4, iPhone4S, iPhone5s, iPhone5c, iPadThirdGen4G, iPhone-3GS, iPhone5, iPodTouchFourthGen, iPad23G, iPadFourthGen, iPadThirdGen, iPad2Wifi, iPadMini, iPadFourthGen4G, iPhone6Plus, iPodTouchFifthGen, iPhone6
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/6b/9b/d8/6b9bd881-e928-bcef-5227-6904a616490d/mzl.mhhturih.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7823809/81a6653e-03fe-11e5-8b9d-87b13c5cd97a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7823809/81a6653e-03fe-11e5-8b9d-87b13c5cd97a.png)
https://cloud.githubusercontent.com/assets/2068130/7823809/81a6653e-03fe-11e5-8b9d-87b13c5cd97a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7823818/90ed3036-03fe-11e5-972f-b706a69cc62a.png
