### ISSUE TITLE
WiFi Explorer

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5689]
**App Name:** WiFi Explorer
 **Bundle ID:** com.adriangranados.wifiexplorer.ios
 **Version:** 1.4
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/5791220/7826213/711aae80-045a-11e5-81d5-4b8825d1df59.png" width="150" height="150" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7873277/0242259e-0566-11e5-8393-3530ae6f4724.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7873277/0242259e-0566-11e5-8393-3530ae6f4724.png)
https://cloud.githubusercontent.com/assets/3090247/7873277/0242259e-0566-11e5-8393-3530ae6f4724.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7873278/024342ee-0566-11e5-8818-788aab282db0.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:

**Comment by quantum8** [comment]
The bundle id on this app is reported incorrectly in AppInfo.

Can this please be changed to:
com.adriangranados.wifiexplorer.ios
