### ISSUE TITLE
⋆Solitaire

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#569]
**App Name:** ⋆Solitaire
**Bundle ID:** com.brainiumstudios.solitairefree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479280326">479280326</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/solitaire/id479280326?mt=8&uo=4">https://itunes.apple.com/us/app/solitaire/id479280326?mt=8&uo=4</a>
**App Version:** 1.5.6
**Seller:** Brainium Studios LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/brainium-studios-llc/id300891405?uo=4">© Brainium Studios LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/ee/91/e7/ee91e746-7833-b26f-db6d-ce80d98831cc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/26814759/f914dd5e-4a55-11e7-8e73-7e8de6e93985.png)

**Comment by zmathiasz** [comment]
**App Name:** ⋆Solitaire
**Bundle ID:** com.brainiumstudios.solitairefree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479280326">479280326</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/solitaire/id479280326?mt=8&uo=4">https://itunes.apple.com/us/app/solitaire/id479280326?mt=8&uo=4</a>
**App Version:** 1.5.6
**Seller:** Brainium Studios LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/brainium-studios-llc/id300891405?uo=4">© Brainium Studios LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/ee/91/e7/ee91e746-7833-b26f-db6d-ce80d98831cc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by zmathiasz** [comment]
@dreamnet - Updated icon as I don't see one in this thread or on your site.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/26814759/f914dd5e-4a55-11e7-8e73-7e8de6e93985.png)
https://cloud.githubusercontent.com/assets/10950389/26814759/f914dd5e-4a55-11e7-8e73-7e8de6e93985.png
***
Source:
https://cloud.githubusercontent.com/assets/10950389/26814781/1128e340-4a56-11e7-8f54-e19c90829faa.png

**Comment by dreamnet** [comment]
@zmathiasz Jup, great! 👍
