### ISSUE TITLE
Barcelona Travel Guide (with Offline Maps) - mTrip Travel Guides

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5690]
**App Name:** Barcelona Travel Guide (with Offline Maps) - mTrip Travel Guides
**Bundle ID:** com.mtrip.Barcelona
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377135599">377135599</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/barcelona-travel-guide-offline/id377135599?mt=8&uo=4">https://itunes.apple.com/us/app/barcelona-travel-guide-offline/id377135599?mt=8&uo=4</a>
**App Version:** 2.7.1
**Seller:** mTrip Travel Guide
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mtrip-travel-guides/id377126417?uo=4>© mTrip Travel Guides</a>
**Supported Devices:** iPhone4S, iPodTouchFifthGen, iPhone5s, iPad23G, iPadFourthGen4G, iPhone6Plus, iPad2Wifi, iPadThirdGen, iPhone4, iPadMini4G, iPhone6, iPadFourthGen, iPhone5, iPadMini, iPhone5c, iPadThirdGen4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/c1/73/b4/c173b430-7e21-2915-4141-77893c5473bd/mzl.dvkgfaub.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7872095/d77e886c-055a-11e5-92e4-a71b2a43fa7e.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7849913/86f09954-04a0-11e5-89b3-c10072c07f79.png)
https://cloud.githubusercontent.com/assets/3090247/7849913/86f09954-04a0-11e5-89b3-c10072c07f79.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7849912/86dfbeb8-04a0-11e5-840e-8ee9023ff59c.png

**Comment by katakolo** [comment]
looks great, can you also please take a look at #5247. It's in a different format without the line. Anything you can do about that?

**Comment by ivanov007** [comment]
@katakolo yes I've noticed the tendency on this app series is to have the bold frame so I'll re-do that one and also #3512

**Comment by katakolo** [comment]
absolutely, that's great, thanx very much!
