### ISSUE TITLE
Madrid Travel Guide (with Offline Maps) - mTrip

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5691]
**App Name:** Madrid Travel Guide (with Offline Maps) - mTrip
**Bundle ID:** com.mtrip.Madrid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=383888890">383888890</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/madrid-travel-guide-offline/id383888890?mt=8&uo=4">https://itunes.apple.com/us/app/madrid-travel-guide-offline/id383888890?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** mTrip Travel Guide
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mtrip-travel-guides/id377126417?uo=4>© mTrip Travel Guides</a>
**Supported Devices:** iPhone5, iPhone4S, iPadMini4G, iPhone4, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPhone5s, iPhone6, iPodTouchFifthGen, iPad2Wifi, iPhone5c, iPhone6Plus, iPad23G, iPadMini, iPadFourthGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/81/cc/7d/81cc7d50-5db5-5d96-d970-66b5929123d9/mzl.jihxsokf.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7851008/cb6cc46e-04ae-11e5-91db-0522dbcfe74c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7851008/cb6cc46e-04ae-11e5-91db-0522dbcfe74c.png)
https://cloud.githubusercontent.com/assets/3090247/7851008/cb6cc46e-04ae-11e5-91db-0522dbcfe74c.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7851009/cb73392a-04ae-11e5-968b-f95393c8dad8.png
