### ISSUE TITLE
London Travel Guide (with Offline Maps) - mTrip Travel Guides

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5692]
**App Name:** London Travel Guide (with Offline Maps) - mTrip Travel Guides
**Bundle ID:** com.mtrip.London
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377136748">377136748</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/london-travel-guide-offline/id377136748?mt=8&uo=4">https://itunes.apple.com/us/app/london-travel-guide-offline/id377136748?mt=8&uo=4</a>
**App Version:** 2.7.1
**Seller:** mTrip Travel Guide
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mtrip-travel-guides/id377126417?uo=4>© mTrip Travel Guides</a>
**Supported Devices:** iPad2Wifi, iPhone4S, iPadThirdGen, iPadFourthGen, iPadFourthGen4G, iPodTouchFifthGen, iPadMini, iPhone6, iPhone5c, iPhone6Plus, iPadThirdGen4G, iPhone5s, iPhone5, iPhone4, iPadMini4G, iPad23G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple2/v4/c0/04/e7/c004e753-5835-3986-d4a1-2ef55e29a440/mzl.toaafinr.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7872304/97f72a94-055c-11e5-9c72-474bd46417f2.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7872304/97f72a94-055c-11e5-9c72-474bd46417f2.png)
https://cloud.githubusercontent.com/assets/3090247/7872304/97f72a94-055c-11e5-9c72-474bd46417f2.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7872306/98213154-055c-11e5-9f06-093b11f4a678.png
