### ISSUE TITLE
Geek - Smarter Shopping

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5693]
**App Name:** Geek - Smarter Shopping
**Bundle ID:** com.contextlogic.Geek
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=949697552">949697552</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/geek-smarter-shopping/id949697552?mt=8&uo=4">https://itunes.apple.com/us/app/geek-smarter-shopping/id949697552?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** ContextLogic Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/contextlogic-inc./id530621398?uo=4>© ContextLogic Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/54/7f/d8/547fd8f0-d05f-201d-e73c-216d0c48990f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892503/f781b34a-4b14-11e6-9a42-f432ea01d7f4.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7872670/75d9b56e-055f-11e5-878e-8b76cb025543.png)
https://cloud.githubusercontent.com/assets/3090247/7872670/75d9b56e-055f-11e5-878e-8b76cb025543.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7872671/75de2ce8-055f-11e5-83d1-e954cd3d9e59.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Geek - Smarter Shopping
**Bundle ID:** com.contextlogic.Geek
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=949697552">949697552</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/geek-smarter-shopping/id949697552?mt=8&uo=4">https://itunes.apple.com/us/app/geek-smarter-shopping/id949697552?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** ContextLogic Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/contextlogic-inc./id530621398?uo=4>© ContextLogic Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/54/7f/d8/547fd8f0-d05f-201d-e73c-216d0c48990f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892503/f781b34a-4b14-11e6-9a42-f432ea01d7f4.png)
https://cloud.githubusercontent.com/assets/2068130/16892503/f781b34a-4b14-11e6-9a42-f432ea01d7f4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892507/05e7a1f6-4b15-11e6-98c8-c774b13b6f3a.png
