### ISSUE TITLE
 Blackbox Pro for Dreambox, Vu+, Xtrend, TVHeadend and Others

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5694]
**App Name:** Blackbox Pro for Dreambox, Vu+, Xtrend, TVHeadend and Others
**Bundle ID:** com.rotapp.blackbox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=641623863">641623863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blackbox-pro-for-dreambox/id641623863?mt=8&uo=4">https://itunes.apple.com/us/app/blackbox-pro-for-dreambox/id641623863?mt=8&uo=4</a>
**App Version:** 2.9.0
**Seller:** Marcel Stegmann
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/marcel-stegmann/id641623866?uo=4>© Marcel Stegmann</a>
**Supported Devices:** iPhone5c, iPadMini4G, iPhone6Plus, iPhone-3GS, iPodTouchFifthGen, iPodTouchFourthGen, iPhone4, iPhone5, iPhone5s, iPadFourthGen, iPhone6, iPadMini, iPad23G, iPadThirdGen4G, iPad2Wifi, iPadThirdGen, iPadFourthGen4G, iPhone4S
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/d3/fe/16/d3fe1618-4370-bd06-bd2b-f9b792057db9/mzl.caoftrjz.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7872885/5dfcf026-0561-11e5-9d5a-8f3af17520e4.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7872885/5dfcf026-0561-11e5-9d5a-8f3af17520e4.png)
https://cloud.githubusercontent.com/assets/3090247/7872885/5dfcf026-0561-11e5-9d5a-8f3af17520e4.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7872886/5e0e5230-0561-11e5-8606-cf1748c01d7b.png
