### ISSUE TITLE
Burgernet

### ISSUE THREAD

**Issue by powerfull** [glasklart/hd#5695]
**App Name:** Burgernet
**Bundle ID:** nl.burgernet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=692302637">692302637</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/burgernet/id692302637?mt=8&uo=4">https://itunes.apple.com/us/app/burgernet/id692302637?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** in-pact BV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/burgernet/id692302640?uo=4>© Burgernet</a>
**Supported Devices:** iPhone5c, iPad2Wifi, iPadMini4G, iPhone4, iPadThirdGen, iPhone5s, iPhone5, iPhone6Plus, iPad23G, iPadMini, iPadFourthGen4G, iPhone6, iPhone4S, iPodTouchFifthGen, iPadFourthGen, iPadThirdGen4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/5c/29/2f/5c292f56-84d7-ae05-8632-b772b8176fe8/mzl.zusvdatk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7873012/d872f566-0562-11e5-8353-b5af19ba1277.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7873012/d872f566-0562-11e5-8353-b5af19ba1277.png)
https://cloud.githubusercontent.com/assets/3090247/7873012/d872f566-0562-11e5-8353-b5af19ba1277.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7873013/d8782676-0562-11e5-85b1-cd896923bcce.png
