### ISSUE TITLE
Glide - Live Video Messenger

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5699]
**App Name:** Glide - Live Video Messenger
**Bundle ID:** com.glidetalk.glideapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=588199307">588199307</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/glide-live-video-messenger/id588199307?uo=4">https://apps.apple.com/us/app/glide-live-video-messenger/id588199307?uo=4</a>
**App Version:** 6.3.12
**Seller:** Glide Talk Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/glide/id588199350?uo=4">© Glide</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/05/48/12/054812f3-b4f7-f00f-a466-167362828ac4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60537293-7af9c800-9d08-11e9-921c-587a4b74ba96.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7868648/c6fb101e-057d-11e5-8218-36451c08a277.png)
https://cloud.githubusercontent.com/assets/10730122/7868648/c6fb101e-057d-11e5-8218-36451c08a277.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7868617/bc45e7a2-057d-11e5-83f0-f9ee62b637f5.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60537293-7af9c800-9d08-11e9-921c-587a4b74ba96.png)
https://user-images.githubusercontent.com/20930745/60537293-7af9c800-9d08-11e9-921c-587a4b74ba96.png

Source:
https://user-images.githubusercontent.com/20930745/60537297-7cc38b80-9d08-11e9-8662-c36e18916481.png
