### ISSUE TITLE
Viewster – Free Movies, TV & Anime

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5702]
**App Name:** Viewster – Free Movies, TV & Anime
**Bundle ID:** com.viewster.viewster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=480983669">480983669</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/viewster-free-movies-tv-anime/id480983669?mt=8&uo=4">https://itunes.apple.com/us/app/viewster-free-movies-tv-anime/id480983669?mt=8&uo=4</a>
**App Version:** 4.3.1
**Seller:** Viewster AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/viewster-ag/id480983672?uo=4>© Viewster AG</a>
**Supported Devices:** iPodTouchFifthGen, iPhone5s, iPadMini4G, iPadFourthGen4G, iPadThirdGen4G, iPhone5, iPhone4, iPadFourthGen, iPhone6Plus, iPad23G, iPadThirdGen, iPhone5c, iPhone6, iPhone4S, iPadMini, iPad2Wifi
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/01/1a/bb/011abba9-2737-4c94-e46f-2f9687e55783/mzl.pccstwbn.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7868938/9a63c774-057f-11e5-8b64-f3c530c10c0c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7868938/9a63c774-057f-11e5-8b64-f3c530c10c0c.png)
https://cloud.githubusercontent.com/assets/10730122/7868938/9a63c774-057f-11e5-8b64-f3c530c10c0c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7868933/90608546-057f-11e5-800e-cf08d49e0ffa.png

**Comment by dreamnet** [comment]
@Trubbel Good work at the last icons. THX! :+1:

**Comment by Trubbel** [comment]
@dreamnet Much obliged!
