### ISSUE TITLE
KitCamera.

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5703]
**App Name:** KitCamera.
**Bundle ID:** com.sebastiansshort.kitcamera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=815095229">815095229</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kitcamera./id815095229?mt=8&uo=4">https://itunes.apple.com/us/app/kitcamera./id815095229?mt=8&uo=4</a>
**App Version:** 3.0.8
**Seller:** Sebastian Short
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sebastian-short/id815095232?uo=4>© Sebastian Short</a>
**Supported Devices:** iPhone4, iPadThirdGen4G, iPadFourthGen, iPadThirdGen, iPhone6, iPhone-3GS, iPhone5s, iPadMini, iPad2Wifi, iPadMini4G, iPhone5c, iPodTouchFourthGen, iPhone5, iPhone6Plus, iPhone4S, iPodTouchFifthGen, iPadFourthGen4G, iPad23G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple2/v4/0c/a8/16/0ca8161f-3541-285e-2923-2d1a013b95d6/mzl.pyfbuivz.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8266031/73952dbe-1717-11e5-8428-584180a8960e.png)

**Comment by Trubbel** [comment]
It's a rather detailed icon I'm afraid, I'll leave it to the more experienced ones out there, hah.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8250819/67dc9c1e-1677-11e5-9e29-617ac6c59647.png)
https://cloud.githubusercontent.com/assets/2068130/8250819/67dc9c1e-1677-11e5-9e29-617ac6c59647.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8250828/80d3e5d8-1677-11e5-8dc5-fac78d434c43.png

**Comment by MagnaMike** [comment]
![wow](http://replygif.net/i/95.gif)

**Comment by Trubbel** [comment]
Wow, just... wow - amazing work @dreamnet! :clap:

**Comment by dreamnet** [comment]
Thank's! :bowtie: :relaxed:
