### ISSUE TITLE
Google Cardboard

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5704]
**App Name:** Google Cardboard
**Bundle ID:** com.google.Cardboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=987962261">987962261</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-cardboard/id987962261?mt=8&uo=4">https://itunes.apple.com/us/app/google-cardboard/id987962261?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPadMini, iPhone5c, iPadThirdGen4G, iPadMini4G, iPhone4S, iPhone5, iPhone6Plus, iPadThirdGen, iPad23G, iPad2Wifi, iPhone6, iPadFourthGen4G, iPhone5s, iPodTouchFifthGen, iPadFourthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/0b/50/3d/0b503d59-0a84-606f-8d32-df6416705bab/mzl.priuckti.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7874208/c53012c8-05ac-11e5-847c-fafd114930ad.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7874208/c53012c8-05ac-11e5-847c-fafd114930ad.png)
https://cloud.githubusercontent.com/assets/10730122/7874208/c53012c8-05ac-11e5-847c-fafd114930ad.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7874205/bac30142-05ac-11e5-8636-9a2e7c9955bf.png

 

*It's not the best...*

**Comment by ivanov007** [comment]
@Trubbel I think it's pretty good :+1:

**Comment by MagnaMike** [comment]
I think @dreamnet re-scans every icon in illustrator anyway so the slightly rough edges on the source (the icon itself looks fine) will be smoothed.

**Comment by Trubbel** [comment]
Yeah, that's something I'd really like to learn. Sadly I have no idea what to search for or something like that to find a tutorial.

**Comment by ivanov007** [comment]
@Trubbel are you using photoshop?

**Comment by Trubbel** [comment]
@ivanov007 Yes I am and I use *Ctrl + T* to upscale images, but it doesn't look that great I'm afraid..

**Comment by ivanov007** [comment]
@Trubbel but this image is already 1024x1024px you don't need to upscale
I'm guessing you are using the eraser tool and magic wand that's a good approach but shapes do a better work, you can search for shape tutorials on youtube and you'll see it's quite a difference, also you can make the icons on Illustrator, it have a better vector engine than photoshop, the only downside is that you'll still need photoshop to apply the layer style

**Comment by Trubbel** [comment]
@ivanov007 You don't happen to know any good tutorials?

**Comment by dreamnet** [comment]
Going to close this issue - please continue the discussion in the open thread.
