### ISSUE TITLE
Spark - fast and smart email for your iPhone

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5705]
**App Name:** Spark - fast and smart email for your iPhone
**Bundle ID:** com.readdle.smartemail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=997102246">997102246</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spark-fast-smart-email-for/id997102246?mt=8&uo=4">https://itunes.apple.com/us/app/spark-fast-smart-email-for/id997102246?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Igor Zhadanov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/readdle/id285035419?uo=4>© Readdle</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen4G, iPhone6, iPhone5c, iPodTouchFifthGen, iPhone5s, iPadFourthGen4G, iPadMini, iPadFourthGen, iPadThirdGen, iPadMini4G, iPhone4S, iPhone6Plus, iPhone5, iPad23G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/90/75/da/9075da4c-cc3f-67fc-c757-c67793d649d0/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7899621/e0e015f2-072a-11e5-99cc-28cbe46659a6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7899621/e0e015f2-072a-11e5-99cc-28cbe46659a6.png)
https://cloud.githubusercontent.com/assets/2068130/7899621/e0e015f2-072a-11e5-99cc-28cbe46659a6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7899625/f0213654-072a-11e5-8661-e611780b7e8a.png
