### ISSUE TITLE
Bråvalla Festival 2015

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5706]
**App Name:** Bråvalla Festival 2015
**Bundle ID:** se.bravallafestival
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=657556078">657556078</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bravalla-festival-2015/id657556078?mt=8&uo=4">https://itunes.apple.com/us/app/bravalla-festival-2015/id657556078?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** FKP Scorpio Konzertproduktionen GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fkp-scorpio-konzertproduktionen/id444084220?uo=4>© FKP Scorpio Konzertproduktionen GmbH</a>
**Supported Devices:** iPadThirdGen4G, iPad2Wifi, iPodTouchFifthGen, iPadMini, iPhone4S, iPhone4, iPhone5c, iPhone6, iPhone5s, iPhone6Plus, iPadFourthGen4G, iPadThirdGen, iPhone5, iPad23G, iPadMini4G, iPadFourthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/af/6e/a8/af6ea8de-e5d6-4f80-04a4-3e430ff61c7e/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7899757/db251d96-0730-11e5-9f19-3736289622a6.png)

**Comment by Trubbel** [comment]
The year updates every year (obviously) in the **App Name** so I wasn't sure if I would leave it out or not. Otherwise one would have to update it every year.

**Comment by MagnaMike** [comment]
@Trubbel Should be fine

**Comment by dreamnet** [comment]
@Trubbel As long as the icon dosen't update every year... :smile:

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7899757/db251d96-0730-11e5-9f19-3736289622a6.png)
https://cloud.githubusercontent.com/assets/10730122/7899757/db251d96-0730-11e5-9f19-3736289622a6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7899755/cfc62846-0730-11e5-83a0-8f7c2ec595a7.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
