### ISSUE TITLE
HBO Nordic

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5708]
**App Name:** HBO Nordic
**Bundle ID:** com.hbonordic.hbonordic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571917630">571917630</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hbo-nordic/id571917630?mt=8&uo=4">https://itunes.apple.com/us/app/hbo-nordic/id571917630?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** HBO Nordic AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hbo-nordic/id571917633?uo=4>© HBO Nordic</a>
**Supported Devices:** iPadMini4G, iPadThirdGen, iPhone5c, iPad23G, iPhone6, iPadThirdGen4G, iPhone4S, iPodTouchFifthGen, iPhone4, iPad2Wifi, iPhone5, iPhone6Plus, iPadFourthGen4G, iPadMini, iPadFourthGen, iPhone5s
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/85/39/9a/85399af1-74ac-b4bb-5ab7-00e914159cfa/mzl.wcsjuhvl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7899650/7ab2d894-072c-11e5-8a23-8ca126b7bd13.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7899650/7ab2d894-072c-11e5-8a23-8ca126b7bd13.png)
https://cloud.githubusercontent.com/assets/2068130/7899650/7ab2d894-072c-11e5-8a23-8ca126b7bd13.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7899651/881e9810-072c-11e5-8191-8373f5e887e5.png
