### ISSUE TITLE
Köttguiden

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5709]
**App Name:** Köttguiden
**Bundle ID:** se.wwf.kottguiden
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=992380779">992380779</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kottguiden/id992380779?mt=8&uo=4">https://itunes.apple.com/us/app/kottguiden/id992380779?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Stift Varldsnaturfonden WWF
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/varldsnaturfonden-wwf/id964187991?uo=4>© Världsnaturfonden WWF</a>
**Supported Devices:** iPhone5c, iPhone6Plus, iPad2Wifi, iPhone6, iPadMini4G, iPodTouchFifthGen, iPadThirdGen, iPadFourthGen, iPadThirdGen4G, iPadFourthGen4G, iPhone4S, iPhone4, iPhone5, iPadMini, iPhone5s, iPad23G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/21/1c/b2/211cb209-60a7-3ce7-ee72-beb1c397ffa8/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/7902388/52e159ee-0786-11e5-8e7d-5e721f36165e.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7899727/ec9d5c74-072f-11e5-8416-dbcd943c66fe.png)
https://cloud.githubusercontent.com/assets/10730122/7899727/ec9d5c74-072f-11e5-8416-dbcd943c66fe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7899725/dde8051c-072f-11e5-873a-e467bf3f63af.png

**Comment by dreamnet** [comment]
Na, I think this should be inverted...

**Comment by MagnaMike** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/7902388/52e159ee-0786-11e5-8e7d-5e721f36165e.png)
https://cloud.githubusercontent.com/assets/2236254/7902388/52e159ee-0786-11e5-8e7d-5e721f36165e.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/7902390/5e762ffa-0786-11e5-9e09-2ca1a0475a2d.png)

**Comment by MagnaMike** [comment]
Is this the same app?

https://itunes.apple.com/us/app/wwf-together/id581920331

**Comment by dreamnet** [comment]
@MagnaMike I think it looks great! ..and no, it's not the same app.
Different Developers:
https://itunes.apple.com/us/artist/varldsnaturfonden-wwf/id964187991
and
https://itunes.apple.com/us/artist/world-wildlife-fund/id581920334

**Comment by Trubbel** [comment]
@dreamnet You're right, that looks much better. @MagnaMike Looks good to me!
