### ISSUE TITLE
Convertible - The Best Unit Converter (convert Length, Area, Currency and many other units including non-standard ones!)

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#571]
**App Name:** Convertible - The Best Unit Converter (convert Length, Area, Currency and many other units including non-standard ones!)
**Bundle ID:** com.efecto.convertible
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514233370">514233370</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/convertible-best-unit-converter/id514233370?mt=8&uo=4">https://itunes.apple.com/us/app/convertible-best-unit-converter/id514233370?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Efecto Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/efecto-pty-ltd/id331691709?uo=4>© Efecto Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/9a/46/49/9a46491f-5f8a-2421-2c69-dc1564735967/mzl.vzqwikoq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10712257/71e48d66-7a95-11e5-80e3-f67010ae934d.png)

**Comment by l8er4now** [comment]
Could use an update.

**App Name:** Convertible - The Best Unit Converter (convert Length, Area, Currency and many other units including non-standard ones!)
**Bundle ID:** com.efecto.convertible
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514233370">514233370</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/convertible-best-unit-converter/id514233370?mt=8&uo=4">https://itunes.apple.com/us/app/convertible-best-unit-converter/id514233370?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Efecto Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/efecto-pty-ltd/id331691709?uo=4>© Efecto Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/9a/46/49/9a46491f-5f8a-2421-2c69-dc1564735967/mzl.vzqwikoq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10712257/71e48d66-7a95-11e5-80e3-f67010ae934d.png)
https://cloud.githubusercontent.com/assets/2068130/10712257/71e48d66-7a95-11e5-80e3-f67010ae934d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10712259/81344a68-7a95-11e5-890b-15de567d277e.png
