### ISSUE TITLE
Remote Mouse for Fire TV

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5714]
**App Name:** Remote Mouse for Fire TV
**Bundle ID:** com.guidology.ios.Remote-Mouse-for-Fire-TV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=981405470">981405470</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/remote-mouse-for-fire-tv/id981405470?mt=8&uo=4">https://itunes.apple.com/us/app/remote-mouse-for-fire-tv/id981405470?mt=8&uo=4</a>
**App Version:** 1.05
**Seller:** Jean Alger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jean-alger/id981405469?uo=4>© Jean Alger</a>
**Supported Devices:** iPodTouchFourthGen, iPad23G, iPad2Wifi, iPhone4, iPadThirdGen, iPhone6Plus, iPhone5s, iPhone-3GS, iPhone5c, iPadFourthGen4G, iPadFourthGen, iPhone4S, iPhone5, iPhone6, iPadMini, iPadMini4G, iPadThirdGen4G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/3e/8c/11/3e8c11d7-c612-0c7f-0f39-5b5f2779ec61/mzl.iworqudq.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7903821/3c58cb78-07e8-11e5-95e5-b5599df1fd94.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7903821/3c58cb78-07e8-11e5-95e5-b5599df1fd94.png)
https://cloud.githubusercontent.com/assets/2068130/7903821/3c58cb78-07e8-11e5-95e5-b5599df1fd94.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7903824/4b863090-07e8-11e5-884e-c127ede4f544.png
