### ISSUE TITLE
AG Drive

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5715]
**App Name:** AG Drive
**Bundle ID:** com.zorgentertainment.agdrive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=789356890">789356890</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ag-drive/id789356890?mt=8&uo=4">https://itunes.apple.com/us/app/ag-drive/id789356890?mt=8&uo=4</a>
**App Version:** 1.3.4
**Seller:** ZORG Entertainment Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/zorg/id789356893?uo=4>© ZORG</a>
**Supported Devices:** iPhone4, iPhone6Plus, iPhone5s, iPad2Wifi, iPadMini4G, iPhone5c, iPhone6, iPad23G, iPadFourthGen4G, iPadMini, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadThirdGen4G, iPadThirdGen, iPhone4S
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/f5/38/df/f538dfc0-e219-312c-12ec-0a74e7d5a928/mzl.lrtaalmo.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9023638/7881002e-38a4-11e5-96f5-f7b529e7d780.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9023638/7881002e-38a4-11e5-96f5-f7b529e7d780.png)
https://cloud.githubusercontent.com/assets/2068130/9023638/7881002e-38a4-11e5-96f5-f7b529e7d780.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9023640/870f91b4-38a4-11e5-9e88-3bd5ee265132.png

**Comment by ivanov007** [comment]
:open_mouth: just awesome :+1:

**Comment by Trubbel** [comment]
@dreamnet Wow, that's really well done!

**Comment by dreamnet** [comment]
@ivanov007 @Trubbel THX!
