### ISSUE TITLE
Quetzalcoatl

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5716]
**App Name:** Quetzalcoatl
**Bundle ID:** com.1button.quetzalcoatl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=913483313">913483313</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quetzalcoatl/id913483313?mt=8&uo=4">https://itunes.apple.com/us/app/quetzalcoatl/id913483313?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** 1Button SARL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/1button-sarl/id388888785?uo=4>© 1Button SARL</a>
**Supported Devices:** iPadThirdGen, iPhone6Plus, iPadMini, iPhone4, iPhone5c, iPad2Wifi, iPadFourthGen4G, iPad23G, iPhone5s, iPhone4S, iPadThirdGen4G, iPadMini4G, iPhone5, iPhone6, iPadFourthGen, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/a1/ff/7d/a1ff7df8-9f95-b61f-9824-a2686de0f93b/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7922392/393720e2-08ac-11e5-8779-0b65800573c9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7922392/393720e2-08ac-11e5-8779-0b65800573c9.png)
https://cloud.githubusercontent.com/assets/2068130/7922392/393720e2-08ac-11e5-8779-0b65800573c9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7922403/478b843a-08ac-11e5-9bb8-046e3b412d3f.png
