### ISSUE TITLE
Snake '97: retro phone classic

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5717]
**App Name:** Snake '97: retro phone classic
**Bundle ID:** nl.wmit.snakefree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438052745">438052745</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snake-97-retro-phone-classic/id438052745?mt=8&uo=4">https://itunes.apple.com/us/app/snake-97-retro-phone-classic/id438052745?mt=8&uo=4</a>
**App Version:** 6.0
**Seller:** dsd 164 B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dsd-164/id489465257?uo=4>© dsd 164</a>
**Supported Devices:** iPad2Wifi, iPhone6Plus, iPhone4S, iPadThirdGen4G, iPhone6, iPadThirdGen, iPodTouchFifthGen, iPadFourthGen4G, iPhone5, iPhone5c, iPadMini, iPhone5s, iPhone4, iPad23G, iPadMini4G, iPadFourthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple3/v4/e5/0b/c1/e50bc1d6-ffc3-6502-6775-5037bac3de35/pr_source.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7903918/f8ddccec-07ea-11e5-8f9c-9de12ff4234e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7903918/f8ddccec-07ea-11e5-8f9c-9de12ff4234e.png)
https://cloud.githubusercontent.com/assets/2068130/7903918/f8ddccec-07ea-11e5-8f9c-9de12ff4234e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7903923/088b2ef0-07eb-11e5-9b2f-6635c4e4b77c.png
