### ISSUE TITLE
Snowbunny Web Browser: Free Fast Private Desktop Chrome & Firefox User Agent Mode Browsing

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5718]
**App Name:** Snowbunny Web Browser: Free Fast Private Desktop Chrome & Firefox User Agent Mode Browsing
**Bundle ID:** com.savysoda.snowRabbit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=383835494">383835494</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snowbunny-web-browser-free/id383835494?mt=8&uo=4">https://itunes.apple.com/us/app/snowbunny-web-browser-free/id383835494?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** Savy Soda HK Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/savysoda/id373730331?uo=4>© SavySoda</a>
**Supported Devices:** iPodTouchFourthGen, iPhone5c, iPadThirdGen, iPadFourthGen, iPadMini, iPhone-3GS, iPodTouchThirdGen, iPhone6Plus, iPhone4S, iPadWifi, iPad2Wifi, iPhone5s, iPadThirdGen4G, iPad3G, iPhone5, iPad23G, iPhone6, iPhone4, iPadMini4G, iPodTouchFifthGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple2/v4/9e/e4/bc/9ee4bc3d-10ed-6b27-2674-f18971e8e65a/mzl.kycxvkse.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7927299/7047a336-08de-11e5-954b-e897daf8b7c0.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7927289/54353956-08de-11e5-96b4-15a76e5d0226.png)
https://cloud.githubusercontent.com/assets/10730122/7927289/54353956-08de-11e5-96b4-15a76e5d0226.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7927286/470d8bc0-08de-11e5-90ad-415af74bfa94.png
--- ---
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/7927299/7047a336-08de-11e5-954b-e897daf8b7c0.png)
https://cloud.githubusercontent.com/assets/10730122/7927299/7047a336-08de-11e5-954b-e897daf8b7c0.png)
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/7927296/63acd5c4-08de-11e5-8c45-d867a7d65e28.png

**Comment by ivanov007** [comment]
@Trubbel I think the rounded one looks better :+1:
