### ISSUE TITLE
Hack RUN 2 - Hack ZERO

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#572]
**App Name:** Hack RUN 2 - Hack ZERO
**Bundle ID:** com.i273.hackrunzero
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432778305">432778305</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hack-run-2-hack-zero/id432778305?mt=8&uo=4">https://itunes.apple.com/us/app/hack-run-2-hack-zero/id432778305?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** i273, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/i273-llc/id369230538?uo=4">© i273, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/ed/51/e3/ed51e37e-c230-9199-9a9d-b4bd0a2085fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32403467-6e105754-c13a-11e7-91ae-f28e153d7670.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32403467-6e105754-c13a-11e7-91ae-f28e153d7670.png)
https://user-images.githubusercontent.com/2068130/32403467-6e105754-c13a-11e7-91ae-f28e153d7670.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32403470-7c5ff116-c13a-11e7-9fda-a59cd71ccf1e.png
