### ISSUE TITLE
Google Classroom

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5722]
**App Name:** Google Classroom
**Bundle ID:** com.google.Classroom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=924620788">924620788</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-classroom/id924620788?mt=8&uo=4">https://itunes.apple.com/us/app/google-classroom/id924620788?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPodTouchFifthGen, iPhone5s, iPadFourthGen, iPadThirdGen, iPhone6, iPad2Wifi, iPhone4S, iPadMini4G, iPadThirdGen4G, iPadFourthGen4G, iPadMini, iPhone4, iPad23G, iPhone5c, iPhone5, iPhone6Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/3a/b0/ce/3ab0ce41-e0e2-0218-70bc-a917ad2799e6/mzl.afarqcyu.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8017569/8fd2080e-0bf9-11e5-8b93-f507a5d3530c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8017569/8fd2080e-0bf9-11e5-8b93-f507a5d3530c.png)
https://cloud.githubusercontent.com/assets/10730122/8017569/8fd2080e-0bf9-11e5-8b93-f507a5d3530c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8017566/881f32da-0bf9-11e5-852d-7b91d4fe4581.png

**Comment by ivanov007** [comment]
@Trubbel good :+1:
