### ISSUE TITLE
You Must Build A Boat

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5723]
**App Name:** You Must Build A Boat
**Bundle ID:** com.eightyeightgames.ymbab
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=811397653">811397653</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/you-must-build-a-boat/id811397653?mt=8&uo=4">https://itunes.apple.com/us/app/you-must-build-a-boat/id811397653?mt=8&uo=4</a>
**App Version:** 1.0.1617
**Seller:** EightyEight Games LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/eightyeight-games-ltd/id421396889?uo=4>© EightyEight Games LTD</a>
**Supported Devices:** iPodTouchFourthGen, iPadThirdGen4G, iPad23G, iPhone4S, iPodTouchFifthGen, iPhone4, iPadMini4G, iPhone-3GS, iPad2Wifi, iPadMini, iPadFourthGen4G, iPhone5, iPhone6, iPhone5c, iPhone5s, iPadThirdGen, iPadFourthGen, iPhone6Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/69/b0/9b/69b09bde-f43d-5f64-7d71-ea41217b5b21/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8393720/7bc752e0-1d1c-11e5-8d72-339d5735bb3a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8393720/7bc752e0-1d1c-11e5-8d72-339d5735bb3a.png)
https://cloud.githubusercontent.com/assets/2068130/8393720/7bc752e0-1d1c-11e5-8d72-339d5735bb3a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8393721/89a4ee36-1d1c-11e5-940f-7cd4d7cfbb2e.png
:stuck_out_tongue_winking_eye:

**Comment by ivanov007** [comment]
looks good to me :+1:

**Comment by dreamnet** [comment]
Taken. :wink:
