### ISSUE TITLE
Junk Jack X

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5724]
**App Name:** Junk Jack X
**Bundle ID:** com.pixbits.junkjackx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=601584735">601584735</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/junk-jack-x/id601584735?mt=8&uo=4">https://itunes.apple.com/us/app/junk-jack-x/id601584735?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** Pixbits SRL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pixbits-srl/id436555493?uo=4>© Pixbits SRL</a>
**Supported Devices:** iPadMini4G, iPad3G, iPodTouchFourthGen, iPadThirdGen, iPhone6Plus, iPhone-3GS, iPodTouchThirdGen, iPad23G, iPadMini, iPadFourthGen4G, iPadThirdGen4G, iPadWifi, iPhone4S, iPhone5s, iPhone5, iPhone4, iPodTouchFifthGen, iPhone6, iPad2Wifi, iPadFourthGen, iPhone5c
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/da/8c/4f/da8c4fac-b5a7-1d97-60d0-6084898edc51/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9210429/916678be-407c-11e5-8b13-255ae1e892f6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9023708/548879c4-38a7-11e5-8244-5dc8ae904c57.png)
https://cloud.githubusercontent.com/assets/2068130/9023708/548879c4-38a7-11e5-8244-5dc8ae904c57.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9023711/62924f4a-38a7-11e5-9dd5-8e1c2c86f4a1.png

**Comment by dreamnet** [comment]
Well, I don't think anyone will make a better one, so I take my icon. :wink:
