### ISSUE TITLE
IQ Option - Binary Option Broker

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5725]
**App Name:** IQ Option - Binary Option Broker
**Bundle ID:** com.trading.iqoption
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=871125783">871125783</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/iq-option-binary-option-broker/id871125783?mt=8&uo=4">https://itunes.apple.com/gb/app/iq-option-binary-option-broker/id871125783?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** ALTA VISTA TRADING LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/artist/iq-option/id871125786?uo=4>© IQ Option</a>
**Supported Devices:** iPhone6, iPad2Wifi, iPhone4, iPodTouchFifthGen, iPhone5c, iPad23G, iPadMini, iPadThirdGen4G, iPadFourthGen, iPhone4S, iPhone5s, iPadThirdGen, iPadMini4G, iPhone6Plus, iPhone5, iPadFourthGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/70/42/e0/7042e01a-790a-7ea5-feaa-27fbf0252e58/mzl.eszdncdd.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8017408/3fa391a8-0bf5-11e5-88fd-73081cba83ff.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8017408/3fa391a8-0bf5-11e5-88fd-73081cba83ff.png)
https://cloud.githubusercontent.com/assets/10730122/8017408/3fa391a8-0bf5-11e5-88fd-73081cba83ff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8017405/36f49d90-0bf5-11e5-9ac8-b2c403946944.png

**Comment by ivanov007** [comment]
@Trubbel :+1:
