### ISSUE TITLE
Anime Trakr - Track shows, episodes and seasonal charts!

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5726]
**App Name:** Anime Trakr - Track shows, episodes and seasonal charts!
**Bundle ID:** com.EverFox.AnimeTrakr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=590452826">590452826</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/anime-trakr-track-shows-episodes/id590452826?mt=8&uo=4">https://itunes.apple.com/us/app/anime-trakr-track-shows-episodes/id590452826?mt=8&uo=4</a>
**App Version:** 4.1.5
**Seller:** Paul Chavarria Podoliako
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/paul-j-chavarria-podoliako/id494746953?uo=4>© Paul J Chavarria Podoliako</a>
**Supported Devices:** iPad2Wifi, iPhone5s, iPhone6, iPhone4, iPhone6Plus, iPadThirdGen, iPadMini, iPad23G, iPadMini4G, iPhone4S, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPhone5c, iPadFourthGen4G, iPadThirdGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/dc/db/97/dcdb978a-24ff-5220-044e-966f2defb608/mzl.pxksougx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8017618/4e9a9f84-0bfb-11e5-8cdf-e6eecf514e7c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8017454/52ecaa3c-0bf6-11e5-870d-bf246fd53e0d.png)
https://cloud.githubusercontent.com/assets/10730122/8017454/52ecaa3c-0bf6-11e5-870d-bf246fd53e0d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8017450/48eb2d42-0bf6-11e5-989b-e04c32e2f0bc.png

**Comment by ivanov007** [comment]
mhhh on a second thought maybe the icon will look better if you upscale it to the guideline edges don't you think @Trubbel ?

**Comment by Trubbel** [comment]
Something like this? (using the same source as above)

![mhmmm](https://cloud.githubusercontent.com/assets/10730122/8017618/4e9a9f84-0bfb-11e5-8cdf-e6eecf514e7c.png)

**Comment by ivanov007** [comment]
yeah looks better :+1:
