### ISSUE TITLE
Hola Privacy VPN App & Browser

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5727]
**App Name:** Hola Privacy VPN App & Browser
**Bundle ID:** org.hola.hola
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=903869356">903869356</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hola-privacy-vpn-app-browser/id903869356?mt=8&uo=4">https://itunes.apple.com/us/app/hola-privacy-vpn-app-browser/id903869356?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Hola Networks Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hola/id903869359?uo=4>© hola</a>
**Supported Devices:** iPhone4, iPad23G, iPad2Wifi, iPodTouchFifthGen, iPhone6, iPhone5s, iPhone5, iPadThirdGen, iPhone6Plus, iPhone5c, iPadFourthGen4G, iPhone4S, iPadMini, iPadThirdGen4G, iPadMini4G, iPadFourthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/1c/78/2b/1c782bc4-8a29-77db-3197-7b253f559d1e/mzl.oeqajdmz.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8017502/44197c50-0bf7-11e5-83f9-b22893f37d01.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8017502/44197c50-0bf7-11e5-83f9-b22893f37d01.png)
https://cloud.githubusercontent.com/assets/10730122/8017502/44197c50-0bf7-11e5-83f9-b22893f37d01.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8017500/389fc6ae-0bf7-11e5-80dd-972ca9903da3.png

**Comment by MagnaMike** [comment]
You know, you really shouldn't use Hola.

**Comment by ivanov007** [comment]
so there's a domain just to make bad propaganda of hola... mhhh I think it's a little suspicious, also the statements they do are not fundamented, just to be clear I'm not bowing for hola nor against it, actually I use firewall IP and it's wonderful so just a toght on the quick peek I took to the site :wink:

**Comment by MagnaMike** [comment]
Well I've heard it from multiple places, but you're right you can never know for sure - however better to be safe then sorry I think in this case. I pay for Private Internet Access myself

**Comment by Trubbel** [comment]
I'm not using it nor do I intend to use it, I was just making the icon for those who have it installed, haha.

**Comment by MagnaMike** [comment]
Ah I see
