### ISSUE TITLE
HowStuffWorks

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5728]
**App Name:** HowStuffWorks
**Bundle ID:** com.howstuffworks.hsw
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401986544">401986544</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/howstuffworks/id401986544?mt=8&uo=4">https://itunes.apple.com/us/app/howstuffworks/id401986544?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** HowStuffWorks.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/howstuffworks.com/id330199701?uo=4>© HowStuffWorks.com</a>
**Supported Devices:** iPhone5, iPhone6Plus, iPodTouchFifthGen, iPadThirdGen4G, iPadFourthGen4G, iPadThirdGen, iPad2Wifi, iPadFourthGen, iPhone5s, iPad23G, iPhone5c, iPadMini4G, iPhone4S, iPadMini, iPhone6
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple2/v4/6a/a8/5a/6aa85aa5-9202-7352-1336-bb10ff6a7629/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8017519/004c3a3e-0bf8-11e5-9a29-1830b308d347.png)

**Comment by Trubbel** [comment]
There is an existing icon for this application, however the artwork has been updated to a more fitting one.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8017519/004c3a3e-0bf8-11e5-9a29-1830b308d347.png)
https://cloud.githubusercontent.com/assets/10730122/8017519/004c3a3e-0bf8-11e5-9a29-1830b308d347.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8017517/f75a3700-0bf7-11e5-992a-4a9ed1b7143c.png

**Comment by ivanov007** [comment]
every time I use the github search bar I' get very disappointed, I'm pretty sure I've seen this issue but since I can't either find it we'll go with this one :+1:
