### ISSUE TITLE
Fleksy - The Fast GIF Keyboard

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5734]
**App Name:** Fleksy - The Fast GIF Keyboard
**Bundle ID:** com.syntellia.Fleksy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520337246">520337246</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fleksy-the-fast-gif-keyboard/id520337246?mt=8&uo=4">https://itunes.apple.com/us/app/fleksy-the-fast-gif-keyboard/id520337246?mt=8&uo=4</a>
**App Version:** 9.0
**Seller:** Fleksy, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fleksy-inc/id520337249?uo=4">© Fleksy, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/1e/26/1c/1e261c62-8e46-a1b7-d541-cd638c3efd7f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32176471-0c5397e8-bd88-11e7-9862-afab3da48fe6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8021863/415a3812-0c77-11e5-8a06-6b53e51bb366.png)
https://cloud.githubusercontent.com/assets/3090247/8021863/415a3812-0c77-11e5-8a06-6b53e51bb366.png

---
Source:
![com syntellia fleksy](https://cloud.githubusercontent.com/assets/3090247/8021867/5d132654-0c77-11e5-8577-53c29a46484d.png)

**Comment by Trubbel** [comment]
Icon has been updated.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8587007/c95dd784-25bb-11e5-8102-93cc8026b909.png)
https://cloud.githubusercontent.com/assets/3090247/8587007/c95dd784-25bb-11e5-8102-93cc8026b909.png
--- ---
https://cloud.githubusercontent.com/assets/3090247/8587008/c965edde-25bb-11e5-9156-433305fa187c.png

**Comment by dreamnet** [comment]
@ivanov007 Yeah! :+1:

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Fleksy + GIF Keyboard
**Bundle ID:** com.syntellia.Fleksy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520337246">520337246</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fleksy-gif-keyboard/id520337246?mt=8&uo=4">https://itunes.apple.com/us/app/fleksy-gif-keyboard/id520337246?mt=8&uo=4</a>
**App Version:** 8.3
**Seller:** Fleksy, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fleksy-inc/id520337249?uo=4">© Fleksy, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/0e/09/e2/0e09e288-b6d8-a594-f7be-ac19eea84db1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/30519073-b4b9bc72-9b8d-11e7-9d3a-e02834f8d3c4.png)
https://user-images.githubusercontent.com/2068130/30519073-b4b9bc72-9b8d-11e7-9d3a-e02834f8d3c4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/30519078-c41fbeb4-9b8d-11e7-8602-067fd4b8373d.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Fleksy - The Fast GIF Keyboard
**Bundle ID:** com.syntellia.Fleksy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520337246">520337246</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fleksy-the-fast-gif-keyboard/id520337246?mt=8&uo=4">https://itunes.apple.com/us/app/fleksy-the-fast-gif-keyboard/id520337246?mt=8&uo=4</a>
**App Version:** 9.0
**Seller:** Fleksy, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fleksy-inc/id520337249?uo=4">© Fleksy, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/1e/26/1c/1e261c62-8e46-a1b7-d541-cd638c3efd7f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32176471-0c5397e8-bd88-11e7-9862-afab3da48fe6.png)
https://user-images.githubusercontent.com/20930745/32176471-0c5397e8-bd88-11e7-9862-afab3da48fe6.png

Source:
https://user-images.githubusercontent.com/20930745/32176497-1da105e4-bd88-11e7-9b3d-346d6b6535ba.png
