### ISSUE TITLE
catcheye

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5735]
**App Name:** catcheye
**Bundle ID:** com.bluvis.viewerapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409982068">409982068</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/catcheye/id409982068?mt=8&uo=4">https://itunes.apple.com/us/app/catcheye/id409982068?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** BLUVIS INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bluvis-inc./id409982071?uo=4>© bluvis inc.</a>
**Supported Devices:** iPadThirdGen4G, iPodTouchFifthGen, iPhone6Plus, iPhone5c, iPhone6, iPadMini4G, iPhone-3GS, iPadThirdGen, iPadFourthGen4G, iPhone4S, iPodTouchFourthGen, iPad23G, iPad3G, iPad2Wifi, iPhone4, iPadWifi, iPhone5s, iPodTouchThirdGen, iPadMini, iPadFourthGen, iPhone5
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/ac/04/92/ac049220-5695-99a4-48a3-c1be1d7ab21e/mzl.mupsbhwh.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509202/179f64ac-225c-11e5-9192-c468e921e926.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8393643/3633da26-1d19-11e5-8b0b-cce3f5c7aa94.png)
https://cloud.githubusercontent.com/assets/2068130/8393643/3633da26-1d19-11e5-8b0b-cce3f5c7aa94.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8393645/4414c0b0-1d19-11e5-8cf3-112e1392df58.png
:stuck_out_tongue_winking_eye:

**Comment by MagnaMike** [comment]
...Well, maybe just get rid of the eyelashes and make a slit pupil? :confused:

**Comment by ivanov007** [comment]
maybe something like this?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509151/5b65a7ae-2258-11e5-845f-c70ee5ca3c27.png)
https://cloud.githubusercontent.com/assets/3090247/8509151/5b65a7ae-2258-11e5-845f-c70ee5ca3c27.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8509153/79595314-2258-11e5-8ea9-45d71eadd57a.png

**Comment by dreamnet** [comment]
Well... I like it - What do you think, Mike?

**Comment by MagnaMike** [comment]
Sure I guess.
