### ISSUE TITLE
9CHAT: 9GAG Forum

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5740]
**App Name:** 9CHAT: 9GAG Forum
**Bundle ID:** com.9chat.ios.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967898134">967898134</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/9chat-9gag-forum/id967898134?mt=8&uo=4">https://itunes.apple.com/us/app/9chat-9gag-forum/id967898134?mt=8&uo=4</a>
**App Version:** 6.00.00
**Seller:** 9GAG Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/9gag/id704992959?uo=4">© 9GAG</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/73/93/51/739351f3-80a5-bca3-21af-0f27e8a4d2e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455304-99d7b4e4-3a76-11e8-9afb-379d5f8f2857.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8065159/f4aec026-0edf-11e5-9ba1-6919a69fd530.png)
https://cloud.githubusercontent.com/assets/10730122/8065159/f4aec026-0edf-11e5-9ba1-6919a69fd530.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8065153/e846ab82-0edf-11e5-9446-a2b27a78c199.png

**Comment by dreamnet** [comment]
@Trubbel :+1:

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455304-99d7b4e4-3a76-11e8-9afb-379d5f8f2857.png)
https://user-images.githubusercontent.com/20930745/38455304-99d7b4e4-3a76-11e8-9afb-379d5f8f2857.png

Source:
https://user-images.githubusercontent.com/20930745/38455317-abe598ea-3a76-11e8-9f47-47f65a25e276.png
