### ISSUE TITLE
Clear Browser - Full Screen Browser & QR Scanner

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5741]
**App Name:** Clear Browser - Full Screen Browser & QR Scanner
**Bundle ID:** com.flyingcomma.clear
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=536117231">536117231</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clear-browser-full-screen/id536117231?mt=8&uo=4">https://itunes.apple.com/us/app/clear-browser-full-screen/id536117231?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Flyingcomma, Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/flyingcomma/id459427876?uo=4>© Flyingcomma</a>
**Supported Devices:** iPad2Wifi, iPhone5c, iPhone6, iPhone4, iPhone6Plus, iPadMini, iPhone4S, iPadThirdGen, iPodTouchFourthGen, iPad23G, iPodTouchFifthGen, iPadMini4G, iPhone-3GS, iPhone5, iPadFourthGen4G, iPadFourthGen, iPadThirdGen4G, iPhone5s
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple4/v4/98/1b/b4/981bb4f1-d2c1-5a71-41fb-cd88e514ba25/mzl.bgxvikob.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8118299/55fed2ee-108e-11e5-93d1-3d9e8890c8b2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8118299/55fed2ee-108e-11e5-93d1-3d9e8890c8b2.png)
https://cloud.githubusercontent.com/assets/2068130/8118299/55fed2ee-108e-11e5-93d1-3d9e8890c8b2.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8118308/64c65cc0-108e-11e5-9610-a9d601bf2357.png

**Comment by Trubbel** [comment]
@dreamnet :+1:
