### ISSUE TITLE
Dan Murphy's

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5742]
**App Name:** Dan Murphy's
**Bundle ID:** au.com.danmurphys.Dan-Murphy-s
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=708912408">708912408</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/dan-murphys/id708912408?mt=8&uo=4">https://itunes.apple.com/au/app/dan-murphys/id708912408?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** Woolworths Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/artist/woolworths-limited/id382011091?uo=4>© Woolworths Limited</a>
**Supported Devices:** iPadThirdGen4G, iPhone4S, iPhone5, iPodTouchFourthGen, iPadMini, iPad2Wifi, iPhone4, iPad23G, iPhone6Plus, iPhone5c, iPadMini4G, iPadThirdGen, iPhone-3GS, iPadFourthGen, iPodTouchFifthGen, iPhone5s, iPhone6, iPadFourthGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/0a/86/b3/0a86b30c-3770-d1c5-c9bd-f57d3586152a/pr_source.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8100061/ff1bb08c-1006-11e5-826b-6b8bd5e6dc2c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8100061/ff1bb08c-1006-11e5-826b-6b8bd5e6dc2c.png)
https://cloud.githubusercontent.com/assets/2068130/8100061/ff1bb08c-1006-11e5-826b-6b8bd5e6dc2c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8100065/0e6417b4-1007-11e5-95a9-e352c667ce59.png
