### ISSUE TITLE
WaterMinder® - Water Hydration Reminder & Tracker

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5743]
**App Name:** WaterMinder® - Water Hydration Reminder & Tracker
**Bundle ID:** com.waterminder.waterminder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=653031147">653031147</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/waterminder-water-hydration/id653031147?mt=8&uo=4">https://itunes.apple.com/us/app/waterminder-water-hydration/id653031147?mt=8&uo=4</a>
**App Version:** 1.7.3
**Seller:** Funn Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/funn-media-llc/id646811578?uo=4>© Funn Media, LLC</a>
**Supported Devices:** iPadThirdGen, iPadFourthGen, iPhone5c, iPhone5s, iPad2Wifi, iPadThirdGen4G, iPadMini, iPhone6Plus, iPhone6, iPhone4S, iPhone5, iPadFourthGen4G, iPadMini4G, iPhone4, iPad23G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/eb/c6/46/ebc64640-0387-8043-60e6-84b1a42cddbd/mzl.qextstsw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8106752/67f99924-1044-11e5-91be-36a27f57bda2.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8106752/67f99924-1044-11e5-91be-36a27f57bda2.png)
https://cloud.githubusercontent.com/assets/10730122/8106752/67f99924-1044-11e5-91be-36a27f57bda2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8106741/57508114-1044-11e5-8d4a-ccf9f44b2d2e.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
