### ISSUE TITLE
GTA Junkies - your number one source for GTA

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5744]
**App Name:** GTA Junkies - your number one source for GTA
**Bundle ID:** com.gtajunkies.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=687984352">687984352</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gta-junkies-your-number-one/id687984352?mt=8&uo=4">https://itunes.apple.com/us/app/gta-junkies-your-number-one/id687984352?mt=8&uo=4</a>
**App Version:** 2
**Seller:** Dave Nicholson-Newton
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dave-nicholson-newton/id687984360?uo=4>© Dave Nicholson-Newton</a>
**Supported Devices:** iPodTouchFifthGen, iPhone4S, iPadFourthGen4G, iPadThirdGen, iPhone5, iPad2Wifi, iPad23G, iPadThirdGen4G, iPhone6, iPadMini4G, iPhone5c, iPhone5s, iPhone6Plus, iPadFourthGen, iPadMini
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/d7/57/b1/d757b1c1-fd7b-7a73-8db1-0bbeb0d0dbe2/mzl.hzwudrsb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8111605/0ea74d0c-1063-11e5-93b3-6657c9bc4e42.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8111605/0ea74d0c-1063-11e5-93b3-6657c9bc4e42.png)
https://cloud.githubusercontent.com/assets/10730122/8111605/0ea74d0c-1063-11e5-93b3-6657c9bc4e42.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8111591/034300be-1063-11e5-8ae8-aebef681b383.png

**Comment by dreamnet** [comment]
@Trubbel Jup! :+1:
