### ISSUE TITLE
Speech Jammer

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5746]
**App Name:** Speech Jammer
**Bundle ID:** com.DwightDickinson.SpeechJammer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=597426372">597426372</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/speech-jammer/id597426372?mt=8&uo=4">https://itunes.apple.com/us/app/speech-jammer/id597426372?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Dwight Dickinson
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dwight-dickinson/id449076421?uo=4>© Dwight Dickinson</a>
**Supported Devices:** iPadWifi, iPad2Wifi, iPadThirdGen4G, iPadFourthGen4G, iPhone5s, iPadMini, iPadThirdGen, iPad23G, iPad3G, iPadFourthGen, iPhone-3GS, iPhone5, iPadMini4G, iPodTouchThirdGen, iPhone5c, iPodTouchFourthGen, iPhone4, iPhone4S, iPodTouchFifthGen, iPhone6Plus, iPhone6
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple6/v4/8f/4a/a3/8f4aa3a7-6938-514f-01bb-25152be00688/mzl.jhfeslsn.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8145736/145128d8-1214-11e5-8f28-9ff6a39e5e64.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8145736/145128d8-1214-11e5-8f28-9ff6a39e5e64.png)
https://cloud.githubusercontent.com/assets/2068130/8145736/145128d8-1214-11e5-8f28-9ff6a39e5e64.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8145739/22ca5600-1214-11e5-9fcf-20c131824da8.png
