### ISSUE TITLE
theScore esports

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5749]
**App Name:** theScore esports
**Bundle ID:** com.thescore.esports
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=969154564">969154564</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/thescore-esports/id969154564?mt=8&uo=4">https://itunes.apple.com/us/app/thescore-esports/id969154564?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Score Media Ventures
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/thescore/id669613188?uo=4>© theScore</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/0d/8f/2e/0d8f2e24-18ab-5217-88ac-f34357bfda8b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/14268212/b30ab3ce-fad8-11e5-82b8-b54f7ecf04da.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8219322/790d7596-1549-11e5-80ef-8c38117c5c1f.png)
https://cloud.githubusercontent.com/assets/2068130/8219322/790d7596-1549-11e5-80ef-8c38117c5c1f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8219331/88780b2c-1549-11e5-812a-47f137c2b7ec.png

**Comment by Trubbel** [comment]
Icon has been updated.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/14268212/b30ab3ce-fad8-11e5-82b8-b54f7ecf04da.png)
https://cloud.githubusercontent.com/assets/10730122/14268212/b30ab3ce-fad8-11e5-82b8-b54f7ecf04da.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/14268211/b30ab144-fad8-11e5-82aa-363baec0fb69.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/14268212/b30ab3ce-fad8-11e5-82b8-b54f7ecf04da.png)
https://cloud.githubusercontent.com/assets/10730122/14268212/b30ab3ce-fad8-11e5-82b8-b54f7ecf04da.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/14268211/b30ab144-fad8-11e5-82aa-363baec0fb69.png
