### ISSUE TITLE
Partly Cloudy

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#575]
**App Name:** Partly Cloudy
**Bundle ID:** net.raureif.Partly-Cloudy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=545627378">545627378</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/partly-cloudy/id545627378?mt=8&uo=4">https://itunes.apple.com/us/app/partly-cloudy/id545627378?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** Raureif GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/raureif/id369876253?uo=4">© Raureif</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/76/ac/a8/76aca836-d2cb-0e8e-890c-d892613ed6bf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19920276/19b5df90-a0d8-11e6-9473-083ab69fadc0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19920276/19b5df90-a0d8-11e6-9473-083ab69fadc0.png)
https://cloud.githubusercontent.com/assets/20930745/19920276/19b5df90-a0d8-11e6-9473-083ab69fadc0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19920292/30fdbc7c-a0d8-11e6-94bf-9eedcc231e53.png
