### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5750]
**App Name:** Groups
**Bundle ID:** com.qbix.groups
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407855546">407855546</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/groups/id407855546?mt=8&uo=4">https://itunes.apple.com/us/app/groups/id407855546?mt=8&uo=4</a>
**App Version:** 2.9
**Seller:** Qbix, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/qbix-inc./id406865714?uo=4>© Qbix, Inc.</a>
**Supported Devices:** iPadThirdGen, iPad23G, iPhone5c, iPhone6Plus, iPadThirdGen4G, iPadFourthGen, iPadMini, iPhone6, iPhone4S, iPadFourthGen4G, iPhone5s, iPodTouchFifthGen, iPad2Wifi, iPadMini4G, iPhone4, iPhone5
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/36/9c/a4/369ca433-d85f-ce3d-c7ca-5cd8daae8373/mzl.hzfstoup.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8149957/96b55434-12d7-11e5-977e-cacae707c88c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8149957/96b55434-12d7-11e5-977e-cacae707c88c.png)
https://cloud.githubusercontent.com/assets/2068130/8149957/96b55434-12d7-11e5-977e-cacae707c88c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8149962/a4f5716e-12d7-11e5-98de-5ec889d42bc0.png
