### ISSUE TITLE
Fallout Shelter

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5753]
**App Name:** Fallout Shelter
**Bundle ID:** com.bethsoft.falloutshelter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=991153141">991153141</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/fallout-shelter/id991153141?mt=8&uo=4">https://itunes.apple.com/au/app/fallout-shelter/id991153141?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Bethesda Softworks LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/artist/bethesda-softworks-llc/id547109759?uo=4>© Bethesda Softworks LLC</a>
**Supported Devices:** iPhone5c, iPad23G, iPadFourthGen4G, iPadMini4G, iPad2Wifi, iPhone5s, iPadFourthGen, iPhone6Plus, iPhone4S, iPadMini, iPhone6, iPodTouchFifthGen, iPhone4, iPadThirdGen4G, iPhone5, iPadThirdGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/25/1a/39/251a3989-14b0-9bd5-0d74-2c8cbc400504/mzl.mztblluf.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8153012/eb5e145a-1325-11e5-87ac-b798c1f966ba.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=ttps://cloud.githubusercontent.com/assets/10730122/8153012/eb5e145a-1325-11e5-87ac-b798c1f966ba.png)
https://cloud.githubusercontent.com/assets/10730122/8153012/eb5e145a-1325-11e5-87ac-b798c1f966ba.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8153010/de9af5da-1325-11e5-965a-ca5c47f5491a.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
