### ISSUE TITLE
Nextdoor

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5754]
**App Name:** Nextdoor
**Bundle ID:** com.nextdoor.nextdoor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=640360962">640360962</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nextdoor/id640360962?mt=8&uo=4">https://itunes.apple.com/us/app/nextdoor/id640360962?mt=8&uo=4</a>
**App Version:** 2.9
**Seller:** Nextdoor.com, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nextdoor/id567302921?uo=4>© Nextdoor</a>
**Supported Devices:** iPad23G, iPadMini, iPadMini4G, iPhone5c, iPhone5, iPhone4S, iPhone4, iPodTouchFifthGen, iPad2Wifi, iPadThirdGen, iPadFourthGen4G, iPhone6, iPadFourthGen, iPadThirdGen4G, iPhone5s, iPhone6Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/ba/75/fd/ba75fd2f-f434-e718-3fb2-00bd2731c12a/mzl.yqgdafmk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8198531/79ac0d46-146d-11e5-82ab-fd084da0aae2.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8198531/79ac0d46-146d-11e5-82ab-fd084da0aae2.png)
https://cloud.githubusercontent.com/assets/3090247/8198531/79ac0d46-146d-11e5-82ab-fd084da0aae2.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/8198530/79aade9e-146d-11e5-9a9d-dd79d3960fcb.png
