### ISSUE TITLE
Hitman: Sniper

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5755]
**App Name:** Hitman: Sniper
**Bundle ID:** com.squareenixmontreal.hitmansniper
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=904278510">904278510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hitman-sniper/id904278510?mt=8&uo=4">https://itunes.apple.com/us/app/hitman-sniper/id904278510?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** SQUARE ENIX Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPad23G, iPhone5s, iPhone6, iPadMini, iPadThirdGen, iPadMini4G, iPhone5, iPodTouchFifthGen, iPhone5c, iPadFourthGen4G, iPhone6Plus, iPad2Wifi, iPhone4S, iPadThirdGen4G, iPadFourthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/7e/ec/ab/7eecab1d-601c-3fff-e3d4-b8df7e875f12/mzl.slmgftry.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8219656/e29053d8-154b-11e5-904b-85ccb4255bca.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8219656/e29053d8-154b-11e5-904b-85ccb4255bca.png)
https://cloud.githubusercontent.com/assets/2068130/8219656/e29053d8-154b-11e5-904b-85ccb4255bca.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8219673/f215b33e-154b-11e5-85dd-d41d550a9cad.png
