### ISSUE TITLE
Circular Tiny Planet Editor

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5756]
**App Name:** Circular Tiny Planet Editor
**Bundle ID:** com.brainfevermedia.circular
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=845737955">845737955</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/circular-tiny-planet-editor/id845737955?uo=4">https://apps.apple.com/us/app/circular-tiny-planet-editor/id845737955?uo=4</a>
**App Version:** 3.6
**Seller:** James Grote
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/brainfevermedia/id338517204?uo=4">© BrainFeverMedia</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/f2/c4/fb/f2c4fb8b-5b3d-7b05-8308-014ba18c3857/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380579-566fc880-9a48-11e9-93ec-436e7acd1d76.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8219211/a8de7bc2-1548-11e5-9705-ca2428d7e55c.png)
https://cloud.githubusercontent.com/assets/2068130/8219211/a8de7bc2-1548-11e5-9705-ca2428d7e55c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8219221/b8b3e2a8-1548-11e5-953c-8cda4181eacd.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380579-566fc880-9a48-11e9-93ec-436e7acd1d76.png)
https://user-images.githubusercontent.com/20930745/60380579-566fc880-9a48-11e9-93ec-436e7acd1d76.png

Source:
https://user-images.githubusercontent.com/20930745/60380581-58398c00-9a48-11e9-89d6-e9fd47a49e0b.png
