### ISSUE TITLE
Radiation Island

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5759]
**App Name:** Radiation Island
**Bundle ID:** com.atypicalgames.radiationisland
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923760656">923760656</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radiation-island/id923760656?mt=8&uo=4">https://itunes.apple.com/us/app/radiation-island/id923760656?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** ATYPICAL GAMES LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/atypical-games/id574375383?uo=4>© Atypical Games</a>
**Supported Devices:** iPhone4, iPadThirdGen, iPadMini4G, iPadFourthGen, iPhone5c, iPad23G, iPhone6Plus, iPadFourthGen4G, iPhone5s, iPhone5, iPhone6, iPodTouchFifthGen, iPhone4S, iPadThirdGen4G, iPad2Wifi, iPadMini
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/b2/cc/dd/b2ccdda9-7cc5-7b93-052c-76a652da0cab/mzl.vqsnoptn.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8266199/3e60f88a-1721-11e5-85bc-59af2cc54922.png)

**Comment by dreamnet** [comment]
Suggestion:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8266199/3e60f88a-1721-11e5-85bc-59af2cc54922.png)
https://cloud.githubusercontent.com/assets/2068130/8266199/3e60f88a-1721-11e5-85bc-59af2cc54922.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8266200/4e3e75ca-1721-11e5-99fc-1eae87082289.png

**Comment by MagnaMike** [comment]
Sure
