### ISSUE TITLE
Xenowerk

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#5760]
**App Name:** Xenowerk
**Bundle ID:** se.pixelbite.mutant
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=969447496">969447496</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xenowerk/id969447496?mt=8&uo=4">https://itunes.apple.com/us/app/xenowerk/id969447496?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Pixelbite
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pixelbite/id428934441?uo=4>© Pixelbite</a>
**Supported Devices:** iPodTouchFourthGen, iPhone6Plus, iPhone4, iPadMini4G, iPodTouchFifthGen, iPad23G, iPadFourthGen4G, iPhone5c, iPhone5s, iPhone-3GS, iPhone6, iPadMini, iPad2Wifi, iPadThirdGen4G, iPadThirdGen, iPhone5, iPhone4S, iPadFourthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/75/5a/ca/755aca95-cdcc-2a7d-7496-84b610b18fd8/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9249417/05816a6c-41c5-11e5-8938-af535e09857a.png)

**Comment by ivanov007** [comment]
samus?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9027945/86e6553c-3968-11e5-8667-806d9b3f0dfc.png)
https://cloud.githubusercontent.com/assets/2068130/9027945/86e6553c-3968-11e5-8667-806d9b3f0dfc.png

---
https://cloud.githubusercontent.com/assets/2068130/9027947/9470d31c-3968-11e5-9b92-9bf8c7c66a2d.png
Pffffffhhhhhhhhh...... Almost impossible.

**Comment by dreamnet** [comment]
Updated my icon above - @ivanov007 What do you think? Good enough?

**Comment by ivanov007** [comment]
@dreamnet yup, I don't think anybody could could make it any better :+1:
