### ISSUE TITLE
Expensify - Expense Reports, Receipts, Mileage, Time Entry, Travel

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5761]
**App Name:** Expensify - Expense Reports, Receipts, Mileage, Time Entry, Travel
**Bundle ID:** com.expensify.expensifylite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=471713959">471713959</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/expensify-expense-reports/id471713959?mt=8&uo=4">https://itunes.apple.com/us/app/expensify-expense-reports/id471713959?mt=8&uo=4</a>
**App Version:** 5.1.0
**Seller:** Expensify, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/expensify-inc./id306670112?uo=4>© Expensify, Inc.</a>
**Supported Devices:** iPadFourthGen, iPad2Wifi, iPhone6, iPhone5s, iPadThirdGen4G, iPadMini, iPodTouchFifthGen, iPad23G, iPadMini4G, iPadFourthGen4G, iPhone6Plus, iPhone4, iPhone4S, iPadThirdGen, iPhone5, iPhone5c
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/52/40/7b/52407b43-5481-af35-4843-306c5d171f7c/mzl.wvfhhkqu.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8270999/17f796a6-1800-11e5-8f07-f93c931e1165.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8270999/17f796a6-1800-11e5-8f07-f93c931e1165.png)
https://cloud.githubusercontent.com/assets/2068130/8270999/17f796a6-1800-11e5-8f07-f93c931e1165.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8271003/29a862fe-1800-11e5-8ea0-15970fc8eda3.png
