### ISSUE TITLE
Beatport

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5764]
**App Name:** Beatport
**Bundle ID:** com.sfx.Beatport
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=965353795">965353795</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beatport/id965353795?mt=8&uo=4">https://itunes.apple.com/us/app/beatport/id965353795?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Beatport, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/beatport-llc/id366319648?uo=4>© Beatport, LLC</a>
**Supported Devices:** iPhone5c, iPhone4, iPadMini, iPad2Wifi, iPodTouchFifthGen, iPhone6Plus, iPhone4S, iPadFourthGen, iPadThirdGen, iPadMini4G, iPad23G, iPadFourthGen4G, iPhone5s, iPadThirdGen4G, iPhone6, iPhone5
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/dc/3c/9b/dc3c9bb3-2af5-5a6d-467d-4ec84d473e82/mzl.ajhtvkjc.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8272344/b722598a-183e-11e5-877b-7941f7412122.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8272344/b722598a-183e-11e5-877b-7941f7412122.png)
https://cloud.githubusercontent.com/assets/2068130/8272344/b722598a-183e-11e5-877b-7941f7412122.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8272345/c54ae23e-183e-11e5-97aa-49ef401ae4ba.png
