### ISSUE TITLE
Vim

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#577]
**App Name:** Vim
**Bundle ID:** com.applidium.Vim
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492668168">492668168</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vim/id492668168?mt=8&uo=4">https://itunes.apple.com/us/app/vim/id492668168?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** APPLIDIUM
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/applidium/id308674223?uo=4">© Applidium</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/ea/08/dd/ea08dd8c-6ca2-432e-c485-d632d5ce02a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32403425-69fa83e8-c139-11e7-8803-c41ece23cc82.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32403425-69fa83e8-c139-11e7-8803-c41ece23cc82.png)
https://user-images.githubusercontent.com/2068130/32403425-69fa83e8-c139-11e7-8803-c41ece23cc82.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32403431-7a966b72-c139-11e7-989b-da61e029fd01.png
