### ISSUE TITLE
Flock - Do More Together

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5771]
**App Name:** Flock - Do More Together
**Bundle ID:** com.FivePointsSocial.Flock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=661859783">661859783</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flock-do-more-together/id661859783?mt=8&uo=4">https://itunes.apple.com/us/app/flock-do-more-together/id661859783?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** FivePoints Social LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fivepoints-social-llc/id661859786?uo=4>© FivePoints Social LLC</a>
**Supported Devices:** iPad2Wifi, iPadFourthGen, iPhone6, iPodTouchFifthGen, iPad23G, iPhone5, iPadMini4G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen4G, iPadMini, iPhone4S, iPhone5s, iPhone6Plus, iPhone5c
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/c9/3b/09/c93b09c5-5663-334a-9b11-d4bee391a414/mzl.cjzulacv.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8272216/cb8da446-183a-11e5-92cc-72fba623cc2d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8272117/681aed54-1837-11e5-87b3-ff64a335a258.png)
https://cloud.githubusercontent.com/assets/10730122/8272117/681aed54-1837-11e5-87b3-ff64a335a258.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8272115/5ceca102-1837-11e5-9943-49426de729b0.png

**Comment by dreamnet** [comment]
Hummm... needs to be inverted I think.

**Comment by Trubbel** [comment]
Do you mean like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8272216/cb8da446-183a-11e5-92cc-72fba623cc2d.png)
https://cloud.githubusercontent.com/assets/10730122/8272216/cb8da446-183a-11e5-92cc-72fba623cc2d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8272215/bf6387ee-183a-11e5-8561-e242c7ffbd5d.png

**Comment by dreamnet** [comment]
@Trubbel Jep, exactly! :+1:
