### ISSUE TITLE
Jurassic World Mobile MovieMaker

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5773]
**App Name:** Jurassic World Mobile MovieMaker
**Bundle ID:** com.nbcuni.universal.jurassicworldphoto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=986916196">986916196</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jurassic-world-mobile-moviemaker/id986916196?mt=8&uo=4">https://itunes.apple.com/us/app/jurassic-world-mobile-moviemaker/id986916196?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** NBCUniversal Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nbcuniversal-media-llc/id303544359?uo=4>© NBCUniversal Media, LLC</a>
**Supported Devices:** iPhone5, iPadThirdGen4G, iPhone5c, iPhone4S, iPhone6Plus, iPad23G, iPadThirdGen, iPadFourthGen4G, iPadFourthGen, iPadMini4G, iPad2Wifi, iPodTouchFifthGen, iPhone5s, iPhone6, iPhone4, iPadMini
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/61/0a/48/610a48b5-9257-761a-72ca-c6a5d11f0936/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8393808/7737bf4a-1d20-11e5-835e-97241abf9852.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8393808/7737bf4a-1d20-11e5-835e-97241abf9852.png)
https://cloud.githubusercontent.com/assets/2068130/8393808/7737bf4a-1d20-11e5-835e-97241abf9852.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8393809/849f13ea-1d20-11e5-93aa-e7e8dd2b3588.png

**Comment by MagnaMike** [comment]
@dreamnet Yep! :
