### ISSUE TITLE
Tomorrowland Brasil

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5778]
**App Name:** Tomorrowland Brasil
**Bundle ID:** com.tomorrowland.tomorrowlandbrasil
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=978304215">978304215</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tomorrowland-brasil/id978304215?mt=8&uo=4">https://itunes.apple.com/us/app/tomorrowland-brasil/id978304215?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** ID&T bvba
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tomorrowland/id652141089?uo=4>© Tomorrowland</a>
**Supported Devices:** iPad2Wifi, iPhone-3GS, iPadThirdGen4G, iPhone5c, iPadMini4G, iPad23G, iPhone6, iPadMini, iPhone5s, iPodTouchFourthGen, iPhone6Plus, iPadFourthGen, iPadFourthGen4G, iPhone5, iPhone4S, iPodTouchFifthGen, iPadThirdGen, iPhone4
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/6e/07/05/6e07056a-071d-384b-6fef-fd7b5e12d9a1/mzl.lidbbxqc.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8272656/e6e42a9c-184b-11e5-9a49-55f0b8fd8d11.png)

**Comment by Trubbel** [comment]
Same as #5776,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8272656/e6e42a9c-184b-11e5-9a49-55f0b8fd8d11.png)
https://cloud.githubusercontent.com/assets/10730122/8272656/e6e42a9c-184b-11e5-9a49-55f0b8fd8d11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8272655/db3533b2-184b-11e5-929b-e0c5d8e1919d.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
