### ISSUE TITLE
Adobe Hue CC

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5782]
**App Name:** Adobe Hue CC
**Bundle ID:** com.adobe.hue
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=988496564">988496564</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-hue-cc/id988496564?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-hue-cc/id988496564?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPadMini, iPodTouchFifthGen, iPadMini4G, iPhone6Plus, iPadFourthGen4G, iPhone5, iPhone5s, iPadThirdGen4G, iPad23G, iPad2Wifi, iPadFourthGen, iPhone4S, iPadThirdGen, iPhone6, iPhone5c
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/5f/01/9d/5f019dcd-55e4-d30f-835f-735b8d4af6d6/mzl.gbnssxvs.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8311349/cef629e0-19d5-11e5-80be-ef7ae6bd95e5.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8282844/a160013c-18f3-11e5-8e10-b91dc8d78de5.png)
https://cloud.githubusercontent.com/assets/10730122/8282844/a160013c-18f3-11e5-8e10-b91dc8d78de5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8282836/954d32f2-18f3-11e5-99ba-248bfdc90e3e.png

**Comment by dreamnet** [comment]
Just some small improvements:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8311349/cef629e0-19d5-11e5-80be-ef7ae6bd95e5.png)
https://cloud.githubusercontent.com/assets/2068130/8311349/cef629e0-19d5-11e5-80be-ef7ae6bd95e5.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8311357/ddb6176a-19d5-11e5-8663-9debf15c42e7.png
