### ISSUE TITLE
FirstLetter

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5783]
**App Name:** FirstLetter
**Bundle ID:** se.itatake.oneletter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=976925633">976925633</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/firstletter/id976925633?mt=8&uo=4">https://itunes.apple.com/us/app/firstletter/id976925633?mt=8&uo=4</a>
**App Version:** 1.01
**Seller:** Itatake AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/itatake.com/id464653469?uo=4>© Itatake.com</a>
**Supported Devices:** iPhone4S, iPhone5c, iPhone5s, iPadThirdGen4G, iPad2Wifi, iPad23G, iPadFourthGen4G, iPodTouchFifthGen, iPhone5, iPadMini, iPadFourthGen, iPhone6, iPadMini4G, iPadThirdGen, iPhone6Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/ad/06/f7/ad06f7e7-a111-4dbc-7a6a-4b3f9f46d4d3/mzl.nensffos.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8339843/c598ccaa-1aba-11e5-87dc-5b3fbb8e51ec.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8339843/c598ccaa-1aba-11e5-87dc-5b3fbb8e51ec.png)
https://cloud.githubusercontent.com/assets/10730122/8339843/c598ccaa-1aba-11e5-87dc-5b3fbb8e51ec.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8339832/b7e8107a-1aba-11e5-963c-68253826f2a0.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8339977/bd13ecf8-1abb-11e5-8ef2-390b30f0d466.png)
https://cloud.githubusercontent.com/assets/10730122/8339977/bd13ecf8-1abb-11e5-8ef2-390b30f0d466.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8339984/cbd853f0-1abb-11e5-8830-32675e5eccee.png

**Comment by dreamnet** [comment]
@Trubbel Taking the first one. :+1:
