### ISSUE TITLE
Tokyo Travel Guide (with Offline Maps) - mTrip

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5784]
**App Name:** Tokyo Travel Guide (with Offline Maps) - mTrip
**Bundle ID:** com.mtrip.Tokyo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=402530481">402530481</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tokyo-travel-guide-offline/id402530481?mt=8&uo=4">https://itunes.apple.com/us/app/tokyo-travel-guide-offline/id402530481?mt=8&uo=4</a>
**App Version:** 2.7.4
**Seller:** mTrip Travel Guide
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mtrip-travel-guides/id377126417?uo=4>© mTrip Travel Guides</a>
**Supported Devices:** iPadMini, iPad23G, iPhone6Plus, iPadFourthGen4G, iPhone6, iPad2Wifi, iPadThirdGen, iPadMini4G, iPhone5c, iPhone4, iPhone4S, iPodTouchFifthGen, iPhone5s, iPadThirdGen4G, iPhone5, iPadFourthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/33/e9/95/33e995d4-3064-13e9-bc71-99f5d9ef210b/mzl.zbajhtwr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8370952/2f1647aa-1bd0-11e5-8314-752498364b50.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8370952/2f1647aa-1bd0-11e5-8314-752498364b50.png)
https://cloud.githubusercontent.com/assets/2068130/8370952/2f1647aa-1bd0-11e5-8314-752498364b50.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8370954/3cde8ae6-1bd0-11e5-9e0b-f946d5675d5c.png
