### ISSUE TITLE
Hong Kong Travel Guide (with Offline Maps) - mTrip

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#5785]
**App Name:** Hong Kong Travel Guide (with Offline Maps) - mTrip
**Bundle ID:** com.mtrip.Hong-Kong
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=425729197">425729197</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hong-kong-travel-guide-offline/id425729197?mt=8&uo=4">https://itunes.apple.com/us/app/hong-kong-travel-guide-offline/id425729197?mt=8&uo=4</a>
**App Version:** 2.7.4
**Seller:** mTrip Travel Guide
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mtrip-travel-guides/id377126417?uo=4>© mTrip Travel Guides</a>
**Supported Devices:** iPadMini4G, iPad23G, iPadFourthGen, iPadFourthGen4G, iPhone6, iPhone4S, iPadThirdGen, iPadMini, iPadThirdGen4G, iPhone5, iPhone4, iPad2Wifi, iPodTouchFifthGen, iPhone6Plus, iPhone5s, iPhone5c
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/38/a7/7a/38a77a4f-b5e5-6f67-0f07-30c9d72ea5f4/mzl.ofjwzoeg.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8370999/c0bfab9c-1bd0-11e5-84b4-bcfc4bbe3d28.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8370999/c0bfab9c-1bd0-11e5-84b4-bcfc4bbe3d28.png)
https://cloud.githubusercontent.com/assets/2068130/8370999/c0bfab9c-1bd0-11e5-84b4-bcfc4bbe3d28.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8371007/cfb58df6-1bd0-11e5-9aa2-8ce990088559.png
