### ISSUE TITLE
Bredbandskollen

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5786]
**App Name:** Bredbandskollen
**Bundle ID:** se.bitfield.Bredbandskollen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=296380480">296380480</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bredbandskollen/id296380480?mt=8&uo=4">https://itunes.apple.com/us/app/bredbandskollen/id296380480?mt=8&uo=4</a>
**App Version:** 3.5.2
**Seller:** .SE
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/.se/id296380483?uo=4>© .SE</a>
**Supported Devices:** iPhone5s, iPadFourthGen, iPhone6Plus, iPhone5c, iPodTouchFifthGen, iPadMini, iPhone5, iPhone4S, iPadThirdGen4G, iPad2Wifi, iPadMini4G, iPhone4, iPadFourthGen4G, iPhone6, iPadThirdGen, iPad23G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/aa/09/5d/aa095dbf-3460-92cd-c95b-e57524350a7f/mzl.zcopvkeo.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8346936/113ea2da-1b04-11e5-9336-89139f68e656.png)

**Comment by Trubbel** [comment]
The icon has been updated and I couldn't find an existing issue for this application.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8346936/113ea2da-1b04-11e5-9336-89139f68e656.png)
https://cloud.githubusercontent.com/assets/10730122/8346936/113ea2da-1b04-11e5-9336-89139f68e656.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8346933/fd979ca0-1b03-11e5-8131-6eae26d8d53e.png

**Comment by dreamnet** [comment]
@Trubbel Jup, perfect!
