### ISSUE TITLE
Authy

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#579]
**App Name:** Authy
**Bundle ID:** com.authy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=494168017">494168017</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/authy/id494168017?mt=8&uo=4">https://itunes.apple.com/us/app/authy/id494168017?mt=8&uo=4</a>
**App Version:** 19.2
**Seller:** Authy Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/authy-inc./id494168021?uo=4>© Authy Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/4b/20/42/4b2042e2-2bda-f46d-8604-d4cd8b750f7f/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11012183/09a3bd38-84f1-11e5-9138-a4c0a14f64fc.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11012183/09a3bd38-84f1-11e5-9138-a4c0a14f64fc.png)
https://cloud.githubusercontent.com/assets/10730122/11012183/09a3bd38-84f1-11e5-9138-a4c0a14f64fc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11012182/063d8c28-84f1-11e5-9a1a-647254828ef4.png
