### ISSUE TITLE
Ladda Refill

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5790]
**App Name:** Ladda Refill
**Bundle ID:** com.teliasonera.laddarefill.telia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507969085">507969085</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ladda-refill/id507969085?mt=8&uo=4">https://itunes.apple.com/us/app/ladda-refill/id507969085?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** TeliaSonera Mobile Networks AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/teliasonera/id309706080?uo=4>© TeliaSonera</a>
**Supported Devices:** iPhone5s, iPad2Wifi, iPhone4, iPadThirdGen, iPad23G, iPadMini, iPadThirdGen4G, iPhone6, iPhone6Plus, iPadFourthGen4G, iPhone5, iPhone4S, iPodTouchFifthGen, iPadMini4G, iPhone5c, iPadFourthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/1e/a9/db/1ea9db49-ac59-a41e-8029-7cc9738bff5b/mzl.cbtcwbfr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8365095/377cc792-1b8b-11e5-8b44-eb950d7e215d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8347579/a5afc6da-1b07-11e5-9d70-a97019765019.png)
https://cloud.githubusercontent.com/assets/10730122/8347579/a5afc6da-1b07-11e5-9d70-a97019765019.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8347577/a1adfc3c-1b07-11e5-808c-67b975b66505.png

**Comment by dreamnet** [comment]
Keeping original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8365095/377cc792-1b8b-11e5-8b44-eb950d7e215d.png)
https://cloud.githubusercontent.com/assets/2068130/8365095/377cc792-1b8b-11e5-8b44-eb950d7e215d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8365111/4612e548-1b8b-11e5-8bea-cb5089c498cc.png
Credits are going to @Trubbel anyway.
