### ISSUE TITLE
BuzzFeed News

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5793]
**App Name:** BuzzFeed News
**Bundle ID:** com.buzzfeed.news
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=981609476">981609476</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/buzzfeed-news/id981609476?mt=8&uo=4">https://itunes.apple.com/us/app/buzzfeed-news/id981609476?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** BuzzFeed
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/buzzfeed/id352970000?uo=4>© BuzzFeed</a>
**Supported Devices:** iPhone5c, iPodTouchFifthGen, iPhone5, iPhone4S, iPadThirdGen4G, iPadMini4G, iPhone5s, iPhone6Plus, iPhone6, iPad23G, iPadFourthGen4G, iPadThirdGen, iPadFourthGen, iPad2Wifi, iPadMini
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/f9/98/83/f998831b-c4c3-2fb9-0a6f-c7b54d135afe/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8365393/300b664c-1b8d-11e5-9990-405f0c798ebf.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8347952/1c34a44c-1b0d-11e5-973e-bdcf9346b6f9.png)
https://cloud.githubusercontent.com/assets/10730122/8347952/1c34a44c-1b0d-11e5-973e-bdcf9346b6f9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8347951/1895e666-1b0d-11e5-8abc-f55975b9b8c0.png

**Comment by dreamnet** [comment]
Keeping original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8365393/300b664c-1b8d-11e5-9990-405f0c798ebf.png)
https://cloud.githubusercontent.com/assets/2068130/8365393/300b664c-1b8d-11e5-9990-405f0c798ebf.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8365407/3f9647c6-1b8d-11e5-96de-ba37706517df.png
Credits are goint to @Trubbel anyway.

**Comment by Trubbel** [comment]
@dreamnet Yeah, good thinking!
