### ISSUE TITLE
Downhill Supreme

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5794]
**App Name:** Downhill Supreme
**Bundle ID:** com.artrb.dhs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=648104417">648104417</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/downhill-supreme/id648104417?mt=8&uo=4">https://itunes.apple.com/us/app/downhill-supreme/id648104417?mt=8&uo=4</a>
**App Version:** 2
**Seller:** Reinholds Berzins
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/reinholds-berzins/id648104420?uo=4>© Reinholds Berzins</a>
**Supported Devices:** iPadFourthGen4G, iPhone4, iPhone4S, iPodTouchThirdGen, iPodTouchFifthGen, iPad2Wifi, iPadThirdGen, iPhone6Plus, iPadMini4G, iPhone5, iPadFourthGen, iPad23G, iPhone6, iPadThirdGen4G, iPhone5s, iPadMini, iPad3G, iPhone-3GS, iPodTouchFourthGen, iPadWifi, iPhone5c
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple/v4/ce/30/6c/ce306c47-3500-ed68-1182-1db970c0e7a7/V4HttpAssetRepositoryClient-mzl.qcsdiryj.png-5954008197654050834.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8348437/aff1808c-1b13-11e5-8f21-6a929ac91d37.png)

**Comment by Trubbel** [comment]
Hm, I just realized how old this application was and that it was last updated in 2013.
Delete it or let it be?

**Comment by Trubbel** [comment]
I made the icon before I saw when the application was last updated, however I'll post it anyway and let you to decide to keep it or not. To me it's all the same, I do not mind.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8348437/aff1808c-1b13-11e5-8f21-6a929ac91d37.png)
https://cloud.githubusercontent.com/assets/10730122/8348437/aff1808c-1b13-11e5-8f21-6a929ac91d37.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8348434/a14c7b90-1b13-11e5-9f82-94b76d7e4689.png

**Comment by dreamnet** [comment]
@Trubbel It dosen't matter how old the app is - we theme it anyway. :wink: :+1:
