### ISSUE TITLE
Activator

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#58]
**App Name:** Activator
 **Bundle ID:** libactivator
 **Version:** 1.9.9~beta1
 **iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/14766432/fb1d2df0-0a09-11e6-831f-5503e7de0d4c.png" width="150" height="150">
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14766436/0d7c7082-0a0a-11e6-9ea4-80003889e2bb.png)

**Comment by dreamnet** [comment]
Because Activator is not themeable at the moment, I remove the icon from Bundles.

**Comment by nekholm** [comment]
Here are some posts from reddit/r/jailbreak:

rpetrich (Activator developer): "Your theme isn't setup to theme it correctly. It needs to provide an image for one of icon-72.png, icon-72@2x.png, Icon@2x-iOS7.png, or icon@2x-iOS7.png in the libactivator bundle."

Meeew: "Nope. Not true. Just made a test theme to see how I could theme it and the correct answer was with Icon-Small-modern@2x.png (for Settings icon) and IconGlyph@2x.png (for Springboard icon)."

Another way is to do this, but rpetrich said you're not supposed to do it: 
1. Go to the "/" directory in iFile. 2. Go to the Applications folder. 3. Go to Activator.app. 4. Go to Info.plist, and open with Property List Viewer. 5. Scroll down and swipe left on SBIconClass and tap delete. 6. Respring device and look at newly themed Activator Icon.
Source: https://redd.it/3jsuhu

**Comment by ivanov007** [comment]
I've tried the IconGlyph@2x.png and I get a darker icon, I guess it's
trying to make the gradient thing over the glasklart icon

**Comment by ivanov007** [comment]
I've tried the IconGlyph@2x.png and I get a darker icon, I guess it's
trying to make the gradient thing over the glasklart icon
![img_3382](https://cloud.githubusercontent.com/assets/3090247/9755059/4d7e4a72-5694-11e5-9e73-a49e97b1e9ff.PNG)

**Comment by dreamnet** [comment]
Theming the Activator icon with the Bundles method (`IconGlyph@2x.png`) works when delting the `SBIconClass` key from the `Info.plist` of Activator. But that's a very, very bad way to theme an icon...
https://cloud.githubusercontent.com/assets/2068130/9835840/9a4b3ca8-59fe-11e5-8681-2d98f46c6da6.PNG
So I think it's better to leave it out... :cry:

**Comment by nekholm** [comment]
Why exactly is it so bad to delete the SBIconClass key? What could happen?

**Comment by ivanov007** [comment]
it could leave your activator unusable, but maybe @rpetrich can answer that

**Comment by dreamnet** [comment]
@nekholm I think you can do it, no problem - but we cannot ask the users of Glasklart to edit a `Info.plist` file of an app just to make a icon work...

**Comment by Anuskuss** [comment]
What's the status of Activator? It is unthemed on my device. Also there is a new (?) icon.

**Comment by Trubbel** [comment]
@Anuskuss Still the same deal. _(read above)_

**Comment by Anuskuss** [comment]
@Trubbel Could you create an icon for the people willing to modify their Info.plist and probably searching for this exact issue?

**Comment by dreamnet** [comment]
@Anuskuss I postet an icon above... or [here](http://glasklarthd.dreamnet.at/index.php?id=54).

**Comment by Anuskuss** [comment]
Can't open your link (I know you're currently reconfigurating your server) but is it the same icon as [above](https://camo.githubusercontent.com/8d313e8910f593beec2d11ad618fb448407b2540/687474703a2f2f707265766965772e647265616d6e65742e61743f696d6167653d68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f323036383133302f333834343736392f32303465323432632d316534632d313165342d396130332d3465633631333264343535632e706e67)? Because the icon changed into [this](https://cloud.githubusercontent.com/assets/3090247/3844658/1ef8b926-1e4b-11e4-9342-a25df4100d4d.PNG) one.

**Comment by Trubbel** [comment]
@Anuskuss This is the [icon](https://cloud.githubusercontent.com/assets/2068130/3007695/ccc3dfba-de98-11e3-8aa8-a54dbe170fbd.png), yes.

Did you delete these lines;
`<key>SBIconClass</key>`
`<string>SBActivatorIcon</string>` ...from `Info.plist`?

**Comment by Anuskuss** [comment]
No I meant that the icon doesn't match the current one (without the semicircle inside the circle).

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14766440/2d269b2e-0a0a-11e6-81ec-7a67cae03d26.png)
https://cloud.githubusercontent.com/assets/2068130/14766440/2d269b2e-0a0a-11e6-81ec-7a67cae03d26.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14766441/4a61ae0e-0a0a-11e6-9f16-664905b6d90e.png

**Comment by XPEric** [comment]
There's an issue with Activator not being themed. I've included a screenshot.
![file_001](https://user-images.githubusercontent.com/2313873/43171035-29f160c6-8f76-11e8-8716-f93618a063bf.png)

**Comment by dreamnet** [comment]
@XPEric We know. Have your read the comments above?
