### ISSUE TITLE
Kount.ly : count anything and everything

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#580]
**App Name:** Kount.ly : count anything and everything
**Bundle ID:** com.kountly.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570981515">570981515</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kount.ly-count-anything-everything/id570981515?mt=8&uo=4">https://itunes.apple.com/us/app/kount.ly-count-anything-everything/id570981515?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** Seempl Studio
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/seempl-studio/id662110714?uo=4">© Seempl Studio</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/ac/4b/79/ac4b793a-7b75-98e9-8d9a-440e4cacf819/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19935466/6cb351b8-a11a-11e6-859b-cde0ec306388.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19935466/6cb351b8-a11a-11e6-859b-cde0ec306388.png)
https://cloud.githubusercontent.com/assets/20930745/19935466/6cb351b8-a11a-11e6-859b-cde0ec306388.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19935492/87a7b964-a11a-11e6-98e4-6917c8f8d0f5.png
