### ISSUE TITLE
Checkbook - Spending, Income, Cashflow and Account Tracker

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5800]
**App Name:** Checkbook - Spending, Income, Cashflow and Account Tracker
**Bundle ID:** com.btgs.checkbookfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484000695">484000695</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/checkbook-spending-income/id484000695?mt=8&uo=4">https://itunes.apple.com/us/app/checkbook-spending-income/id484000695?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Appxy Information Technology Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/appxy/id760100924?uo=4>© Appxy</a>
**Supported Devices:** iPhone4, iPadFourthGen, iPadMini, iPhone5s, iPhone6Plus, iPhone4S, iPadFourthGen4G, iPad23G, iPhone5, iPadMini4G, iPhone5c, iPadThirdGen, iPad2Wifi, iPhone6, iPadThirdGen4G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/1b/da/50/1bda5049-c39f-c4c7-00c2-102400149916/mzl.pdonhsmp.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8349224/4b47d138-1b1b-11e5-927f-44ee99e4175c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8349195/2aa8831e-1b1b-11e5-99cf-0ae874bd1797.png)
https://cloud.githubusercontent.com/assets/10730122/8349195/2aa8831e-1b1b-11e5-99cf-0ae874bd1797.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8349194/2634ced2-1b1b-11e5-99e0-8d557a2647bf.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8349224/4b47d138-1b1b-11e5-927f-44ee99e4175c.png)
https://cloud.githubusercontent.com/assets/10730122/8349224/4b47d138-1b1b-11e5-927f-44ee99e4175c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8349208/46ffbe24-1b1b-11e5-9d1e-6cc29629076b.png

**Comment by dreamnet** [comment]
Hum... I like the second one better... @Trubbel :+1:
