### ISSUE TITLE
Checkbook Pro

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5801]
**App Name:** Checkbook Pro
**Bundle ID:** com.btgs.checkbookforipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469331073">469331073</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/checkbook-pro/id469331073?mt=8&uo=4">https://itunes.apple.com/us/app/checkbook-pro/id469331073?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** Appxy Information Technology Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/appxy/id760100924?uo=4>© Appxy</a>
**Supported Devices:** iPhone4S, iPhone5s, iPad2Wifi, iPadMini, iPadFourthGen4G, iPadThirdGen4G, iPadThirdGen, iPodTouchFifthGen, iPad23G, iPhone6, iPadMini4G, iPadFourthGen, iPhone5, iPhone6Plus, iPhone5c, iPhone4
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/25/19/89/251989c1-6854-ca2c-0982-92ce0f9f965f/mzl.mnnxdkao.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8349224/4b47d138-1b1b-11e5-927f-44ee99e4175c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8349195/2aa8831e-1b1b-11e5-99cf-0ae874bd1797.png)
https://cloud.githubusercontent.com/assets/10730122/8349195/2aa8831e-1b1b-11e5-99cf-0ae874bd1797.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8349194/2634ced2-1b1b-11e5-99e0-8d557a2647bf.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8349224/4b47d138-1b1b-11e5-927f-44ee99e4175c.png)
https://cloud.githubusercontent.com/assets/10730122/8349224/4b47d138-1b1b-11e5-927f-44ee99e4175c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8349208/46ffbe24-1b1b-11e5-9d1e-6cc29629076b.png

**Comment by dreamnet** [comment]
Same icon as for #5800.
