### ISSUE TITLE
Personal Capital

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5806]
**App Name:** Personal Capital
**Bundle ID:** com.personalcapital.personalcapital
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504672168">504672168</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/personal-capital/id504672168?mt=8&uo=4">https://itunes.apple.com/us/app/personal-capital/id504672168?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** Personal Capital Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/personal-capital-corporation/id504672331?uo=4">© Personal Capital Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/47/a3/35/47a33551-c621-3723-11b1-22be4895e166/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38433374-dcee42f4-39ca-11e8-9873-7f0e4c02baff.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8349546/24ac8dcc-1b1e-11e5-8377-6e1ec715ce5e.png)
https://cloud.githubusercontent.com/assets/10730122/8349546/24ac8dcc-1b1e-11e5-8377-6e1ec715ce5e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8349540/1fadd51a-1b1e-11e5-8324-bb8c1cb0e25e.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8349555/34bf001e-1b1e-11e5-8d9d-4b82a64cf92b.png)
https://cloud.githubusercontent.com/assets/10730122/8349555/34bf001e-1b1e-11e5-8d9d-4b82a64cf92b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8349540/1fadd51a-1b1e-11e5-8324-bb8c1cb0e25e.png

**Comment by dreamnet** [comment]
@Trubbel It's better too keep the original size, so I'm taking the second one.

**Comment by Trubbel** [comment]
@dreamnet Yeah I thought so as well, I'm not really sure why I included that one haha.

**Comment by dreamnet** [comment]
@Trubbel Thanks for all the great work! :+1: :100:

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Personal Capital
**Bundle ID:** com.personalcapital.personalcapital
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504672168">504672168</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/personal-capital/id504672168?mt=8&uo=4">https://itunes.apple.com/us/app/personal-capital/id504672168?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** Personal Capital Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/personal-capital-corporation/id504672331?uo=4">© Personal Capital Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/47/a3/35/47a33551-c621-3723-11b1-22be4895e166/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38433374-dcee42f4-39ca-11e8-9873-7f0e4c02baff.png)
https://user-images.githubusercontent.com/2068130/38433374-dcee42f4-39ca-11e8-9873-7f0e4c02baff.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38433386-ebb9bcf0-39ca-11e8-8d8d-dfc01d5e6057.png
