### ISSUE TITLE
Qwak

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5807]
**App Name:** Qwak
**Bundle ID:** com.qwakers.qwak
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=374029016">374029016</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qwak/id374029016?mt=8&uo=4">https://itunes.apple.com/us/app/qwak/id374029016?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Mr Qwak Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mr-qwak-limited/id374029019?uo=4>© Mr Qwak Limited</a>
**Supported Devices:** iPhone-3G, iPad3G, iPhone4, iPhone5, iPhone4S, iPodTouchFifthGen, iPadFourthGen, iPad23G, iPod-touch-with-mic, iPhone, iPadWifi, iPhone6, iPhone5s, iPadMini4G, iPad2Wifi, iPodTouchThirdGen, iPadThirdGen4G, iPadMini, iPhone6Plus, iPodTouchFourthGen, iPhone5c, iPod-touch, iPhone-3GS, iPadFourthGen4G, iPadThirdGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple/v4/83/6c/08/836c08f9-618f-9d77-0af3-19d4ee628449/mza_4713179272259699324.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9025915/ab01e110-3919-11e5-86c3-f224f5b0a913.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9025915/ab01e110-3919-11e5-86c3-f224f5b0a913.png)
https://cloud.githubusercontent.com/assets/2068130/9025915/ab01e110-3919-11e5-86c3-f224f5b0a913.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9025917/ba3959b0-3919-11e5-8f39-e6ccbb68827a.png
