### ISSUE TITLE
New Horizons: a NASA Voyage to Pluto

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5808]
**App Name:** New Horizons: a NASA Voyage to Pluto
**Bundle ID:** edu.jhuapl.sd.nhEPO
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=473217882">473217882</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-horizons-nasa-voyage-to/id473217882?mt=8&uo=4">https://itunes.apple.com/us/app/new-horizons-nasa-voyage-to/id473217882?mt=8&uo=4</a>
**App Version:** 1.2.5
**Seller:** Johns Hopkins University Applied Physics Laboratory
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/johns-hopkins-university-applied/id473217885?uo=4>© Johns Hopkins University Applied Physics Laboratory</a>
**Supported Devices:** iPhone4S, iPhone6Plus, iPodTouchFifthGen, iPad2Wifi, iPhone5, iPhone6, iPadFourthGen, iPhone4, iPadFourthGen4G, iPadThirdGen4G, iPad23G, iPadThirdGen, iPhone5c, iPadMini, iPadMini4G, iPhone5s
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/f4/03/64/f4036485-06ae-5ace-a6d4-f4e9d14b06bb/mzl.wlgmjygy.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8393608/411b85ee-1d17-11e5-801b-fee62b691fb8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8393608/411b85ee-1d17-11e5-801b-fee62b691fb8.png)
https://cloud.githubusercontent.com/assets/2068130/8393608/411b85ee-1d17-11e5-801b-fee62b691fb8.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8393610/50f90c34-1d17-11e5-98c2-525a72c2645a.png
:stuck_out_tongue_winking_eye:

**Comment by quantum8** [comment]
:thumbsup:

**Comment by dreamnet** [comment]
@quantum8 Ok, taken....
