### ISSUE TITLE
FAF - Find a Fireteam & LFG Companion for Destiny

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5814]
**App Name:** Find a Fireteam - Matchmaking, LFG Companion App for Destiny
**Bundle ID:** com.soweetapps.findafireteam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=952670325">952670325</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/find-fireteam-matchmaking/id952670325?mt=8&uo=4">https://itunes.apple.com/us/app/find-fireteam-matchmaking/id952670325?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Dark Fish Labs Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/dark-fish-labs-ltd/id758438969?uo=4>© Dark Fish Labs Ltd</a>
**Supported Devices:** iPhone5s, iPad2Wifi, iPhone5, iPadFourthGen, iPhone-3GS, iPhone4, iPadMini, iPhone5c, iPhone6, iPodTouchFifthGen, iPadThirdGen, iPhone4S, iPadFourthGen4G, iPodTouchFourthGen, iPadMini4G, iPadThirdGen4G, iPad23G, iPhone6Plus
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60392988-3c98b900-9b0e-11e9-9b67-8d157f508948.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393012-b03ac600-9b0e-11e9-9fb3-7a773d882797.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8373197/c22f1cc8-1bea-11e5-8576-e3196e6cf7f9.png)
https://cloud.githubusercontent.com/assets/10730122/8373197/c22f1cc8-1bea-11e5-8576-e3196e6cf7f9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8373194/bec73a84-1bea-11e5-95bc-0a3189585853.pn

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393012-b03ac600-9b0e-11e9-9fb3-7a773d882797.png)
https://user-images.githubusercontent.com/2068130/60393012-b03ac600-9b0e-11e9-9fb3-7a773d882797.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60393015-be88e200-9b0e-11e9-89fd-c600f0c0e940.png
