### ISSUE TITLE
Anghami - انغامي

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5818]
**App Name:** Anghami - انغامي
**Bundle ID:** com.anghami.anghami
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=545395155">545395155</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/anghami-%D8%A7%D9%86%D8%BA%D8%A7%D9%85%D9%8A/id545395155?uo=4">https://apps.apple.com/us/app/anghami-%D8%A7%D9%86%D8%BA%D8%A7%D9%85%D9%8A/id545395155?uo=4</a>
**App Version:** 4.5.76
**Seller:** Anghami
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/anghami/id545395158?uo=4">© Anghami</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/3e/d9/22/3ed922a4-c6da-197d-6064-26ebda9c18fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979188-a1bb4e80-95e4-11e9-849d-b946d046eb57.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8374330/cd627a18-1bf4-11e5-81e4-8fd67bd13cff.png)
https://cloud.githubusercontent.com/assets/10730122/8374330/cd627a18-1bf4-11e5-81e4-8fd67bd13cff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8374327/c9e6cec0-1bf4-11e5-8cb1-b74da4994704.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](httsp:((preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979188-a1bb4e80-95e4-11e9-849d-b946d046eb57.png)
https://user-images.githubusercontent.com/2068130/59979188-a1bb4e80-95e4-11e9-849d-b946d046eb57.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979196-b1d32e00-95e4-11e9-9b51-036fcefb7d84.png
