### ISSUE TITLE
ESV Bible

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#582]
**App Name:** ESV Bible
**Bundle ID:** org.crossway.ESVStudyBible
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=361797273">361797273</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/esv-bible/id361797273?mt=8&uo=4">https://itunes.apple.com/us/app/esv-bible/id361797273?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Crossway
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/crossway/id361797276?uo=4>© Crossway</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple2/v4/41/5c/42/415c42bf-7933-53e4-281a-f2623467cac5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19316928/9698e88a-90a3-11e6-8efe-91ae9315857a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19316928/9698e88a-90a3-11e6-8efe-91ae9315857a.png)
https://cloud.githubusercontent.com/assets/20930745/19316928/9698e88a-90a3-11e6-8efe-91ae9315857a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19316951/a6f64b64-90a3-11e6-9908-5a19ffb4371a.png
