### ISSUE TITLE
Betterment: Invest and Save

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5823]
**App Name:** Betterment: Invest and Save
**Bundle ID:** betterment
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393156562">393156562</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/betterment-invest-and-save/id393156562?uo=4">https://apps.apple.com/us/app/betterment-invest-and-save/id393156562?uo=4</a>
**App Version:** 5.13.2
**Seller:** Betterment
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/betterment/id393156565?uo=4">© Betterment</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/14/0f/91/140f9177-0545-b57e-4c9c-ccd3285e3572/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60123665-4cb83d80-9788-11e9-9918-7f736e898d48.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8374971/cd9970c2-1bf9-11e5-90fa-112035e99ebb.png)
https://cloud.githubusercontent.com/assets/10730122/8374971/cd9970c2-1bf9-11e5-90fa-112035e99ebb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8374969/ca819ab8-1bf9-11e5-985d-b9bf4d3891d6.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60123665-4cb83d80-9788-11e9-9918-7f736e898d48.png)
https://user-images.githubusercontent.com/20930745/60123665-4cb83d80-9788-11e9-9918-7f736e898d48.png

Source:
https://user-images.githubusercontent.com/20930745/60123672-504bc480-9788-11e9-81bf-7522a9eabfd8.png
