### ISSUE TITLE
Moven - Smart Finances

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5826]
**App Name:** Moven - Smart Finances
**Bundle ID:** com.movencorp.moven
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=661035659">661035659</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moven-smart-finances/id661035659?mt=8&uo=4">https://itunes.apple.com/us/app/moven-smart-finances/id661035659?mt=8&uo=4</a>
**App Version:** 3.2.3
**Seller:** MOVENCORP INC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/movencorp-inc./id661035662?uo=4>© Movencorp, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple62/v4/ac/ea/f9/aceaf921-6914-bad8-4cb3-7107072f8b4f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18299860/a5a3081a-74c4-11e6-90dc-9b35a447c632.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8377981/29a06bc0-1c16-11e5-8f9a-9bd9545d4960.png)
https://cloud.githubusercontent.com/assets/10730122/8377981/29a06bc0-1c16-11e5-8f9a-9bd9545d4960.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8377978/2642ab82-1c16-11e5-8fda-071da6af726b.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Moven - Smart Finances
**Bundle ID:** com.movencorp.moven
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=661035659">661035659</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moven-smart-finances/id661035659?mt=8&uo=4">https://itunes.apple.com/us/app/moven-smart-finances/id661035659?mt=8&uo=4</a>
**App Version:** 3.2.3
**Seller:** MOVENCORP INC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/movencorp-inc./id661035662?uo=4>© Movencorp, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple62/v4/ac/ea/f9/aceaf921-6914-bad8-4cb3-7107072f8b4f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18288794/de736894-744a-11e6-98f8-0226673d6ce4.png)

https://cloud.githubusercontent.com/assets/3704186/18288794/de736894-744a-11e6-98f8-0226673d6ce4.png

https://cloud.githubusercontent.com/assets/3704186/18288811/e9fd945a-744a-11e6-9c0a-843282f61a9d.png
