### ISSUE TITLE
Earnin - Get Paid Today

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5827]
**App Name:** Earnin - Get Paid Today
**Bundle ID:** com.activehours.Activehours
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=723815926">723815926</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/earnin-get-paid-today/id723815926?uo=4">https://apps.apple.com/us/app/earnin-get-paid-today/id723815926?uo=4</a>
**App Version:** 10.1
**Seller:** Activehours Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/activehours-inc/id723815929?uo=4">© Activehours Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/2c/6c/dd/2c6cddc1-1391-563d-42d9-a3750acec309/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388028-04f92500-9aac-11e9-878e-ca4752f8ed37.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8378046/ac18ae46-1c16-11e5-8177-052805782fb8.png)
https://cloud.githubusercontent.com/assets/10730122/8378046/ac18ae46-1c16-11e5-8177-052805782fb8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8378045/a887d662-1c16-11e5-8172-58123c5a930e.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388028-04f92500-9aac-11e9-878e-ca4752f8ed37.png)
https://user-images.githubusercontent.com/20930745/60388028-04f92500-9aac-11e9-878e-ca4752f8ed37.png

Source:
https://user-images.githubusercontent.com/20930745/60388031-0fb3ba00-9aac-11e9-9a40-c21a941de700.png
