### ISSUE TITLE
Openfolio - Portfolio tracking and peer benchmarks

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5830]
**App Name:** Openfolio - Portfolio tracking and peer benchmarks
**Bundle ID:** com.openfolio.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=920083395">920083395</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/openfolio-portfolio-tracking/id920083395?mt=8&uo=4">https://itunes.apple.com/us/app/openfolio-portfolio-tracking/id920083395?mt=8&uo=4</a>
**App Version:** 1.6.3
**Seller:** Openfolio Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/openfolio-corporation/id920083394?uo=4>© Openfolio Corporation</a>
**Supported Devices:** iPodTouchFifthGen, iPadMini4G, iPadMini, iPadFourthGen4G, iPhone5c, iPhone6Plus, iPadFourthGen, iPad23G, iPhone6, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPad2Wifi, iPhone5s
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/5b/d5/c1/5bd5c1b1-77c5-41d7-df3e-09186fdcd076/mzl.dbdhgczs.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8387519/5dd36652-1c59-11e5-9f03-0899a99ed074.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8378358/09116fd2-1c19-11e5-86fa-bde9f925f854.png)
https://cloud.githubusercontent.com/assets/10730122/8378358/09116fd2-1c19-11e5-86fa-bde9f925f854.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8378356/05c8a32c-1c19-11e5-9541-25c9ec501b95.png

**Comment by dreamnet** [comment]
Original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8387519/5dd36652-1c59-11e5-9f03-0899a99ed074.png)
https://cloud.githubusercontent.com/assets/2068130/8387519/5dd36652-1c59-11e5-9f03-0899a99ed074.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8387525/6d6eb2c4-1c59-11e5-85c8-50808e93b9c8.png
Credits are goint to @Trubbel anyway.
