### ISSUE TITLE
SONIC RUNNERS

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5842]
**App Name:** SONIC RUNNERS
**Bundle ID:** com.sega.SonicRunners
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953019873">953019873</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sonic-runners/id953019873?mt=8&uo=4">https://itunes.apple.com/us/app/sonic-runners/id953019873?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** SEGA CORPORATION
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sega-corporation/id302946768?uo=4>© SEGA CORPORATION</a>
**Supported Devices:** iPhone4S, iPhone6, iPadThirdGen4G, iPadMini4G, iPadThirdGen, iPhone6Plus, iPadFourthGen4G, iPodTouchFifthGen, iPhone5s, iPad23G, iPhone5, iPadFourthGen, iPadMini, iPad2Wifi, iPhone5c
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/24/b0/21/24b02188-d22a-e2d5-f5b1-7d0f89ee5728/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509442/6bb77b7c-2268-11e5-8519-dacad80506c4.png)

**Comment by ivanov007** [comment]
I gave it a shot

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509442/6bb77b7c-2268-11e5-8519-dacad80506c4.png)
https://cloud.githubusercontent.com/assets/3090247/8509442/6bb77b7c-2268-11e5-8519-dacad80506c4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8509441/6a56fbe0-2268-11e5-99da-3cdd4a1aec35.png

**Comment by Trubbel** [comment]
@ivanov007 I like it! :+1:

**Comment by dreamnet** [comment]
@ivanov007 Great one! :+1:
