### ISSUE TITLE
Focus - Time Manager

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5843]
**App Name:** Focus - Time Manager
**Bundle ID:** com.laser-focused.focus-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=975017240">975017240</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/focus-time-manager/id975017240?uo=4">https://apps.apple.com/us/app/focus-time-manager/id975017240?uo=4</a>
**App Version:** 5.2.2
**Seller:** Masterbuilders
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/masterbuilders/id896347016?uo=4">© Masterbuilders</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/4a/8e/b4/4a8eb429-c917-708a-1644-3bc9b96ffe5a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400593-3807eb00-9b76-11e9-9df6-ec3971780fa5.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8397197/4b5d3744-1dc3-11e5-876f-d932afb9706e.png)
https://cloud.githubusercontent.com/assets/10730122/8397197/4b5d3744-1dc3-11e5-876f-d932afb9706e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8397195/477a50c6-1dc3-11e5-8e2d-4a6832352d2c.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400593-3807eb00-9b76-11e9-9df6-ec3971780fa5.png)
https://user-images.githubusercontent.com/20930745/60400593-3807eb00-9b76-11e9-9df6-ec3971780fa5.png

Source:
https://user-images.githubusercontent.com/20930745/60400594-39d1ae80-9b76-11e9-8862-4fd2204ef24d.png
