### ISSUE TITLE
Be Focused - Focus Timer

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5844]
**App Name:** Be Focused - Focus Timer
**Bundle ID:** com.xwavesoft.pomodorolite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=973130201">973130201</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/be-focused-focus-timer/id973130201?mt=8&uo=4">https://itunes.apple.com/us/app/be-focused-focus-timer/id973130201?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** Denys Yevenko
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/denys-yevenko/id427936468?uo=4">© Denys Yevenko</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/a6/28/ab/a628ab0d-1125-b826-6ca6-21396ee71ea7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44625961-714b4b00-a914-11e8-83c7-fe2d557f6042.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8397216/25244c24-1dc4-11e5-8ff5-3f58ebe1b127.png)
https://cloud.githubusercontent.com/assets/10730122/8397216/25244c24-1dc4-11e5-8ff5-3f58ebe1b127.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8397214/21b61f36-1dc4-11e5-9e0e-a63c5e2059cf.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44625961-714b4b00-a914-11e8-83c7-fe2d557f6042.png)
https://user-images.githubusercontent.com/2068130/44625961-714b4b00-a914-11e8-83c7-fe2d557f6042.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44625964-80ca9400-a914-11e8-9f14-1458a60e1b44.png
