### ISSUE TITLE
Google Play Books

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5849]
**App Name:** Google Play Books
**Bundle ID:** com.google.GoogleBooks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=400989007">400989007</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-play-books/id400989007?uo=4">https://apps.apple.com/us/app/google-play-books/id400989007?uo=4</a>
**App Version:** 5.2.3
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/e0/44/af/e044afd9-56ef-2d71-4b90-a232677e58d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60641707-374cae80-9e2d-11e9-950a-9216af5f7672.png)

**Comment by Trubbel** [comment]
I couldn't find the issue for this application, and the icon has changed as well.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8506064/506309fa-21c7-11e5-89bb-84f3d1fe5b7f.png)
https://cloud.githubusercontent.com/assets/3090247/8506064/506309fa-21c7-11e5-89bb-84f3d1fe5b7f.png
--- ----
Source:
https://cloud.githubusercontent.com/assets/3090247/8506065/50647006-21c7-11e5-8123-65392894b237.png

**Comment by dreamnet** [comment]
@ivanov007 Jup! :+1:

**Comment by ivanov007** [comment]
I just downloaded this app and I'm not that comfortable with the icon, so I'm fixing it a little
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9830747/744f926a-58ff-11e5-96dd-959e8d4689c4.png)
https://cloud.githubusercontent.com/assets/3090247/9830747/744f926a-58ff-11e5-96dd-959e8d4689c4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9830748/7475888a-58ff-11e5-8621-586856f7860f.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60641707-374cae80-9e2d-11e9-950a-9216af5f7672.png)
https://user-images.githubusercontent.com/2068130/60641707-374cae80-9e2d-11e9-950a-9216af5f7672.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60641720-4895bb00-9e2d-11e9-8867-bd7911faa492.png
