### ISSUE TITLE
Google Calendar

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5850]
**App Name:** Google Calendar
**Bundle ID:** com.google.calendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=909319292">909319292</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-calendar/id909319292?mt=8&uo=4">https://itunes.apple.com/us/app/google-calendar/id909319292?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen4G, iPadMini, iPhone5s, iPad23G, iPhone4S, iPhone5, iPhone5c, iPadMini4G, iPhone6Plus, iPadFourthGen, iPhone4, iPadThirdGen, iPodTouchFifthGen, iPadFourthGen4G, iPhone6
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple2/v4/0f/50/ed/0f50ed76-9d9e-3601-dd00-46d815a797af/mzl.jopfzbkt.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8436540/99ca34b6-1f1e-11e5-88a9-a054a8250337.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8436540/99ca34b6-1f1e-11e5-88a9-a054a8250337.png)
https://cloud.githubusercontent.com/assets/3090247/8436540/99ca34b6-1f1e-11e5-88a9-a054a8250337.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8436541/99f81cbe-1f1e-11e5-8857-7d729650a38e.png
