### ISSUE TITLE
Google Photos

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5851]
**App Name:** Google Photos
**Bundle ID:** com.google.photos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=962194608">962194608</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-photos/id962194608?uo=4">https://apps.apple.com/us/app/google-photos/id962194608?uo=4</a>
**App Version:** 5.0
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a8/e4/00/a8e400af-a9c0-31fc-92f6-7eb04dfdf11f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86527863-57c9a180-bea3-11ea-8607-5b79b33ef2a8.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8437274/adf51bae-1f23-11e5-9fe4-7952b3291b21.png)
https://cloud.githubusercontent.com/assets/3090247/8437274/adf51bae-1f23-11e5-9fe4-7952b3291b21.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8437277/ae254310-1f23-11e5-98ad-1b8df5a587a5.png

**Comment by alpcinar** [comment]
Needs to be updated.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86527863-57c9a180-bea3-11ea-8607-5b79b33ef2a8.png)
https://user-images.githubusercontent.com/2068130/86527863-57c9a180-bea3-11ea-8607-5b79b33ef2a8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86527884-6d3ecb80-bea3-11ea-8855-f776cdaf83d8.png
