### ISSUE TITLE
Google News

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5852]
**App Name:** Google News
**Bundle ID:** com.google.GoogleDigitalEditions
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=459182288">459182288</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-news/id459182288?mt=8&uo=4">https://itunes.apple.com/us/app/google-news/id459182288?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc/id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/a4/05/0c/a4050c05-9422-bbf2-b07e-96c89eb365b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/40199517-0c5088f8-5a1a-11e8-869a-7ebb2610ade5.png)

**Comment by Trubbel** [comment]
I couldn't find the issue for this application, and the icon has changed as well.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8504809/88f25872-219d-11e5-97df-45a54fc3bed7.png)
https://cloud.githubusercontent.com/assets/3090247/8504809/88f25872-219d-11e5-97df-45a54fc3bed7.png
---- ---
https://cloud.githubusercontent.com/assets/3090247/8504818/a425cf20-219d-11e5-8467-de179fe49955.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:

**Comment by l8er4now** [comment]
Could use an update.

**App Name:** Google Play Newsstand - News & Magazines for you
**Bundle ID:** com.google.GoogleDigitalEditions
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=459182288">459182288</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-play-newsstand-news/id459182288?mt=8&uo=4">https://itunes.apple.com/us/app/google-play-newsstand-news/id459182288?mt=8&uo=4</a>
**App Version:** 3.6
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/80/b5/a3/80b5a316-a68f-6e2c-8bfd-5bb9bb3ff64e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14589810/6d74e56a-04eb-11e6-9ab1-ba8f10355208.png)
https://cloud.githubusercontent.com/assets/2068130/14589810/6d74e56a-04eb-11e6-9ab1-ba8f10355208.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14589814/7c337df0-04eb-11e6-8a5d-51d19b0557f7.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Google News
**Bundle ID:** com.google.GoogleDigitalEditions
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=459182288">459182288</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-news/id459182288?mt=8&uo=4">https://itunes.apple.com/us/app/google-news/id459182288?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc/id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/a4/05/0c/a4050c05-9422-bbf2-b07e-96c89eb365b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/40199517-0c5088f8-5a1a-11e8-869a-7ebb2610ade5.png)
https://user-images.githubusercontent.com/20930745/40199517-0c5088f8-5a1a-11e8-869a-7ebb2610ade5.png

Source:
https://user-images.githubusercontent.com/20930745/40199547-26212de6-5a1a-11e8-96d2-fb1a4fc4fe3f.png
