### ISSUE TITLE
Google News & Weather

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5853]
**App Name:** Google News & Weather
**Bundle ID:** com.google.news
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=913753848">913753848</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-news-weather/id913753848?mt=8&uo=4">https://itunes.apple.com/us/app/google-news-weather/id913753848?mt=8&uo=4</a>
**App Version:** 1.7.434
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPadThirdGen4G, iPadFourthGen, iPhone5s, iPadMini, iPad23G, iPadMini4G, iPhone6, iPhone5, iPadThirdGen, iPadFourthGen4G, iPhone4, iPodTouchFifthGen, iPad2Wifi, iPhone4S, iPhone5c, iPhone6Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/09/5d/e7/095de798-9ae9-e6bc-5307-b2b80a24086f/mzl.tdtgarci.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8497432/8bcd19da-217d-11e5-83a0-952a5e18fa5d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8497432/8bcd19da-217d-11e5-83a0-952a5e18fa5d.png)
https://cloud.githubusercontent.com/assets/2068130/8497432/8bcd19da-217d-11e5-83a0-952a5e18fa5d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8497439/998e7bea-217d-11e5-8c3e-ba610607472f.png

**Comment by Christian9901** [comment]
Icon needs update
