### ISSUE TITLE
Chrome Remote Desktop

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5855]
**App Name:** Chrome Remote Desktop
**Bundle ID:** com.google.ChromeRemoteDesktop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944025852">944025852</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chrome-remote-desktop/id944025852?mt=8&uo=4">https://itunes.apple.com/us/app/chrome-remote-desktop/id944025852?mt=8&uo=4</a>
**App Version:** 1.0.9
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPadThirdGen4G, iPhone5s, iPhone6, iPhone6Plus, iPadFourthGen4G, iPhone5, iPodTouchFifthGen, iPhone4, iPadThirdGen, iPadMini, iPad23G, iPad2Wifi, iPadMini4G, iPhone4S, iPadFourthGen, iPhone5c
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/cf/fe/dc/cffedcdf-88ad-c58c-9ae7-df2705fb82c7/mzl.syahmpxx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8420492/35426ece-1ec3-11e5-80fb-33e65cc2274f.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8420492/35426ece-1ec3-11e5-80fb-33e65cc2274f.png)
https://cloud.githubusercontent.com/assets/10730122/8420492/35426ece-1ec3-11e5-80fb-33e65cc2274f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8420491/3158c178-1ec3-11e5-85ad-553aaf1635ff.png

**Comment by MagnaMike** [comment]
@dreamnet Do you think it would look better if the screen area was glasklart style and the chrome icon was transparent?

**Comment by dreamnet** [comment]
@MagnaMike Hm, no. I think this is OK, because the Chrome icon is like the one we use for the Chrome app.

**Comment by MagnaMike** [comment]
@dreamnet Good point. :+1:
