### ISSUE TITLE
Google My Business

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5856]
**App Name:** Google My Business
**Bundle ID:** com.google.MyBusiness
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=853371601">853371601</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-my-business/id853371601?uo=4">https://apps.apple.com/us/app/google-my-business/id853371601?uo=4</a>
**App Version:** 3.9.0
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/60/9f/d4/609fd41f-856f-b74f-c244-4f5e3afeb44e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60616444-c62bdd80-9dd1-11e9-8f2c-3078b72f9c3c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8420689/8df392da-1ec5-11e5-82db-4ee89064c657.png)
https://cloud.githubusercontent.com/assets/10730122/8420689/8df392da-1ec5-11e5-82db-4ee89064c657.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8420687/892e9754-1ec5-11e5-82ff-4ac0f86b5bd8.png

**Comment by dreamnet** [comment]
Needs an update - the  "G".

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60616444-c62bdd80-9dd1-11e9-8f2c-3078b72f9c3c.png)
https://user-images.githubusercontent.com/2068130/60616444-c62bdd80-9dd1-11e9-8f2c-3078b72f9c3c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60616472-d643bd00-9dd1-11e9-833a-c95f1ff7d2a2.png
