### ISSUE TITLE
Fiber TV

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5858]
**App Name:** Fiber TV
**Bundle ID:** com.google.GFTVMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=613278395">613278395</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fiber-tv/id613278395?uo=4">https://apps.apple.com/us/app/fiber-tv/id613278395?uo=4</a>
**App Version:** 16.0.0
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple111/v4/b4/0a/03/b40a0318-de8b-51f4-16a3-1c6403442ccb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393666-470c8000-9b19-11e9-84b2-829f670d88e8.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8420334/abce8c14-1ec1-11e5-88b3-3590ea0104b3.png)
https://cloud.githubusercontent.com/assets/10730122/8420334/abce8c14-1ec1-11e5-88b3-3590ea0104b3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8420332/a3cb7478-1ec1-11e5-9a6c-29bbfb13fcf0.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393666-470c8000-9b19-11e9-84b2-829f670d88e8.png)
https://user-images.githubusercontent.com/20930745/60393666-470c8000-9b19-11e9-84b2-829f670d88e8.png

Source:
https://user-images.githubusercontent.com/20930745/60393667-48d64380-9b19-11e9-8bb1-ea3a4771eee5.png
