### ISSUE TITLE
Google Admin

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5859]
**App Name:** Google Admin
**Bundle ID:** com.google.Admin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=779592978">779592978</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-admin/id779592978?mt=8&uo=4">https://itunes.apple.com/us/app/google-admin/id779592978?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/5f/85/0f/5f850f95-1d4b-7906-48e2-8c287dac80b3/mzl.bticbxwb.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10301252/a958014a-6c00-11e5-9985-3a60f1a17a6f.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8419808/2acd4a50-1ebd-11e5-96bc-f0ff849f8a14.png)
https://cloud.githubusercontent.com/assets/10730122/8419808/2acd4a50-1ebd-11e5-96bc-f0ff849f8a14.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8419806/26c85c56-1ebd-11e5-9afc-4842c6df9061.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10301252/a958014a-6c00-11e5-9985-3a60f1a17a6f.png)
https://cloud.githubusercontent.com/assets/2068130/10301252/a958014a-6c00-11e5-9985-3a60f1a17a6f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10301257/b7d5b4ba-6c00-11e5-86a5-b5c11c81d020.png
