### ISSUE TITLE
Google Coordinate

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5861]
**App Name:** Google Coordinate
**Bundle ID:** com.google.coordinate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=562220757">562220757</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-coordinate/id562220757?mt=8&uo=4">https://itunes.apple.com/us/app/google-coordinate/id562220757?mt=8&uo=4</a>
**App Version:** 1.9.4
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone-3GS, iPadMini, iPhone6Plus, iPhone6, iPadFourthGen, iPad23G, iPadFourthGen4G, iPhone5c, iPadThirdGen, iPhone4, iPodTouchFourthGen, iPhone5, iPhone5s, iPad2Wifi, iPadThirdGen4G, iPodTouchFifthGen, iPadMini4G, iPhone4S
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/9e/d8/8b/9ed88b58-b11c-0001-90f0-77c33a7557f1/mzl.ldycurbf.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8810326/549fd748-2fbc-11e5-8311-d13312b20224.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8810326/549fd748-2fbc-11e5-8311-d13312b20224.png)
https://cloud.githubusercontent.com/assets/7368317/8810326/549fd748-2fbc-11e5-8311-d13312b20224.png
--- ---
https://cloud.githubusercontent.com/assets/7368317/8810327/55567912-2fbc-11e5-86df-0ebb778a0836.png

**Comment by Teekzilla** [comment]
Updated submission with corrected source file!

**Comment by dreamnet** [comment]
@Teekzilla Jup - great! I dont think we need the background, the icon is recognizable enough.
