### ISSUE TITLE
One Today

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5862]
**App Name:** One Today
**Bundle ID:** com.google.OneToday
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=740270200">740270200</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/one-today/id740270200?mt=8&uo=4">https://itunes.apple.com/us/app/one-today/id740270200?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone6, iPad23G, iPhone5c, iPhone4, iPadThirdGen, iPadFourthGen, iPadMini, iPadFourthGen4G, iPad2Wifi, iPadThirdGen4G, iPhone4S, iPadMini4G, iPhone5, iPhone5s, iPodTouchFifthGen, iPhone6Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/90/15/dd/9015ddb9-79f6-2577-2088-78f3d5907b0d/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8413789/0fe2a88c-1ece-11e5-8e1e-efb6d1a96f6f.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8413789/0fe2a88c-1ece-11e5-8e1e-efb6d1a96f6f.png)
https://cloud.githubusercontent.com/assets/10008202/8413789/0fe2a88c-1ece-11e5-8e1e-efb6d1a96f6f.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/8413799/2947078c-1ece-11e5-9299-999441f993a5.png

**Comment by dreamnet** [comment]
@iNfeCtGFX :+1:
