### ISSUE TITLE
Google Life Sciences Study Kit

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5863]
**App Name:** Google Life Sciences Study Kit
**Bundle ID:** com.google.StudyKit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=960129332">960129332</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-life-sciences-study/id960129332?mt=8&uo=4">https://itunes.apple.com/us/app/google-life-sciences-study/id960129332?mt=8&uo=4</a>
**App Version:** 1.0.689
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPadMini4G, iPadMini, iPadFourthGen, iPhone6Plus, iPhone5, iPadFourthGen4G, iPhone6, iPhone4S, iPadThirdGen4G, iPad23G, iPad2Wifi, iPadThirdGen, iPhone5c, iPodTouchFifthGen, iPhone5s
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/df/eb/27/dfeb2748-9b29-e9a7-42ae-c572ccc8247e/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8413939/46fe485c-1ecf-11e5-8ba6-486a8b007d64.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8413939/46fe485c-1ecf-11e5-8ba6-486a8b007d64.png)
https://cloud.githubusercontent.com/assets/10008202/8413939/46fe485c-1ecf-11e5-8ba6-486a8b007d64.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/8413945/5af70dbc-1ecf-11e5-9192-3fe67826f1f5.png

**Comment by dreamnet** [comment]
@iNfeCtGFX Jep!
