### ISSUE TITLE
Amazon Local – Restaurants, hotels, and beauty offers near you

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5864]
**App Name:** Amazon Local – Restaurants, hotels, and beauty offers near you
**Bundle ID:** com.amazon.AMZNLocal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=548017839">548017839</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amazon-local-restaurants-hotels/id548017839?mt=8&uo=4">https://itunes.apple.com/us/app/amazon-local-restaurants-hotels/id548017839?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** AMZN Mobile LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/amzn-mobile-llc/id297606954?uo=4>© AMZN Mobile LLC</a>
**Supported Devices:** iPhone5s, iPhone5c, iPad2Wifi, iPhone6Plus, iPhone4S, iPadFourthGen4G, iPadThirdGen, iPad23G, iPadMini, iPadMini4G, iPadFourthGen, iPhone6, iPadThirdGen4G, iPhone5, iPhone4, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/d7/64/1c/d7641cf4-6f01-0bb6-4b57-bc67ed9dee47/mzl.jcljdrov.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8473087/fbbc95f4-20a6-11e5-9774-4851e4979e41.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8413672/20580a96-1ecd-11e5-9c53-ad23ea9f76f0.png)
https://cloud.githubusercontent.com/assets/10008202/8413672/20580a96-1ecd-11e5-9c53-ad23ea9f76f0.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/8413693/3d5ebb6c-1ecd-11e5-8774-dbb4ee9a461b.png

**Comment by Trubbel** [comment]
Just some corrections,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8420034/07b4c30c-1ebf-11e5-978e-84d56c9815f3.png)
https://cloud.githubusercontent.com/assets/10730122/8420034/07b4c30c-1ebf-11e5-978e-84d56c9815f3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8420032/02d74df0-1ebf-11e5-98e0-9d3f67b5cb5e.png

**Comment by MagnaMike** [comment]
I like the extra detail. :+1:

**Comment by dreamnet** [comment]
This needs to be pushed to the bottom (the source from @Trubbel is correct):
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8473087/fbbc95f4-20a6-11e5-9774-4851e4979e41.png)
https://cloud.githubusercontent.com/assets/2068130/8473087/fbbc95f4-20a6-11e5-9774-4851e4979e41.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8473092/0a9f2140-20a7-11e5-8665-4150f815f16f.png
