### ISSUE TITLE
Amazon Prime Now

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5865]
**App Name:** Amazon Prime Now
**Bundle ID:** com.amazon.Now
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=947644950">947644950</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amazon-prime-now/id947644950?mt=8&uo=4">https://itunes.apple.com/us/app/amazon-prime-now/id947644950?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** AMZN Mobile LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/amzn-mobile-llc/id297606954?uo=4>© AMZN Mobile LLC</a>
**Supported Devices:** iPodTouchFifthGen, iPadFourthGen, iPadMini4G, iPhone4, iPhone6Plus, iPhone5c, iPhone5s, iPad2Wifi, iPadThirdGen4G, iPadFourthGen4G, iPad23G, iPadMini, iPhone6, iPhone4S, iPhone5, iPadThirdGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/9b/62/2a/9b622a0f-52ba-b277-9f27-ac964c6bfda9/mzl.zjuvjqga.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8412789/3606379c-1ec7-11e5-8adf-2ffcca9152a3.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8412789/3606379c-1ec7-11e5-8adf-2ffcca9152a3.png)
https://cloud.githubusercontent.com/assets/10008202/8412789/3606379c-1ec7-11e5-8adf-2ffcca9152a3.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/8412938/13299416-1ec8-11e5-94bf-1a202b38310a.png

**Comment by dreamnet** [comment]
@iNfeCtGFX Yes! :+1:
