### ISSUE TITLE
JetRadar — Cheap Flights Search

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5866]
**App Name:** JetRadar — Cheap Flights Search
**Bundle ID:** com.jetradar.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606870241">606870241</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jetradar-cheap-flights-search/id606870241?mt=8&uo=4">https://itunes.apple.com/us/app/jetradar-cheap-flights-search/id606870241?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** Go Travel Un Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/go-travel-un-limited/id498958867?uo=4>© Go Travel Un Limited</a>
**Supported Devices:** iPhone4S, iPhone5c, iPad23G, iPhone5, iPad2Wifi, iPadThirdGen, iPadFourthGen, iPadThirdGen4G, iPhone6, iPadMini, iPhone6Plus, iPadFourthGen4G, iPadMini4G, iPhone4, iPodTouchFifthGen, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/23/b6/cc/23b6cc3e-4b1f-aea8-2635-8574722e6173/mzl.zvdjuwcr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8472921/81994eda-20a5-11e5-86b7-e12c47119f1f.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8413411/351002ba-1ecb-11e5-9a65-54723885cd55.png)
https://cloud.githubusercontent.com/assets/10008202/8413411/351002ba-1ecb-11e5-9a65-54723885cd55.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/8413439/63c11dec-1ecb-11e5-8642-35ca19eb0283.png

**Comment by dreamnet** [comment]
@iNfeCtGFX Jessir! :+1:

**Comment by dreamnet** [comment]
Added some details:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8472921/81994eda-20a5-11e5-86b7-e12c47119f1f.png)
https://cloud.githubusercontent.com/assets/2068130/8472921/81994eda-20a5-11e5-86b7-e12c47119f1f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8472928/90293b4a-20a5-11e5-8739-a7066769ab88.png
Credits are going to @iNfeCtGFX anyway.
