### ISSUE TITLE
AnimeHub - An Anime Fan Haven

### ISSUE THREAD

**Issue by iNfeCtGFX** [glasklart/hd#5867]
**App Name:** AnimeHub - An Anime Fan Haven
**Bundle ID:** com.odie.AnimeHub
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=882620151">882620151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/animehub-an-anime-fan-haven/id882620151?mt=8&uo=4">https://itunes.apple.com/us/app/animehub-an-anime-fan-haven/id882620151?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Odie Edo-Osagie
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/odie-edo-osagie/id882620154?uo=4>© Odie Edo-Osagie</a>
**Supported Devices:** iPodTouchFifthGen, iPhone6Plus, iPadMini4G, iPhone5c, iPad23G, iPhone5, iPadFourthGen, iPadMini, iPhone5s, iPad2Wifi, iPhone4S, iPadThirdGen4G, iPadThirdGen, iPadFourthGen4G, iPhone4, iPhone6
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/c1/28/78/c12878b2-e92e-ff4a-84b1-8dedcd417005/mzl.dozxpvdh.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8448348/3fc62482-2001-11e5-8579-1105a727460b.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8413301/8ae2aefa-1eca-11e5-9ad6-1dbcd40a64a0.png)
https://cloud.githubusercontent.com/assets/10008202/8413301/8ae2aefa-1eca-11e5-9ad6-1dbcd40a64a0.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/8413310/99ea9750-1eca-11e5-98b6-c0004b30596b.png

**Comment by dreamnet** [comment]
Hmmm... inverting?

**Comment by MagnaMike** [comment]
@dreamnet Agreed

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8448348/3fc62482-2001-11e5-8579-1105a727460b.png)
https://cloud.githubusercontent.com/assets/10008202/8448348/3fc62482-2001-11e5-8579-1105a727460b.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/8448350/4bdfc1b0-2001-11e5-898e-3c7d2b142d46.png

**Comment by iNfeCtGFX** [comment]
You guys were right, it's much better looking now.

**Comment by MagnaMike** [comment]
@iNfeCtGFX :+1:
