### ISSUE TITLE
Secret Folder Icon FREE

### ISSUE THREAD

**Issue by iNfeCtGFX** [glasklart/hd#5868]
**App Name:** Secret Folder Icon FREE - One folder vault to lock safe and hide secret photo.s video personal contact private note password keep.er to-do audio location secret message plus private browser and downloader
**Bundle ID:** com.iappcreation.folderlockfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=715337334">715337334</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/secret-folder-icon-free-one/id715337334?mt=8&uo=4">https://itunes.apple.com/us/app/secret-folder-icon-free-one/id715337334?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** i-App Creation Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/i-app-creation-co.-ltd./id360704053?uo=4>© i-App Creation Co., Ltd.</a>
**Supported Devices:** iPadMini4G, iPodTouchThirdGen, iPhone6, iPhone-3GS, iPadThirdGen4G, iPadWifi, iPhone5c, iPadMini, iPodTouchFourthGen, iPhone5s, iPhone6Plus, iPad3G, iPodTouchFifthGen, iPadFourthGen4G, iPhone4S, iPad2Wifi, iPadThirdGen, iPad23G, iPhone5, iPhone4, iPadFourthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple4/v4/ad/be/46/adbe4650-b42d-1fa0-cc3e-c3b5fbe53d1b/mzl.fbndshfa.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8414229/80938ce2-1ed1-11e5-8ed3-1a4640f74e73.png)

**Comment by iNfeCtGFX** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10008202/8414229/80938ce2-1ed1-11e5-8ed3-1a4640f74e73.png)
https://cloud.githubusercontent.com/assets/10008202/8414229/80938ce2-1ed1-11e5-8ed3-1a4640f74e73.png
**Source:**
https://cloud.githubusercontent.com/assets/10008202/8414232/91e08748-1ed1-11e5-8106-895c39b1d149.png

**Comment by iNfeCtGFX** [comment]
Would it be possible to include these into the theme? The app opens to a mock folder page and shows colourful icons instead of the Glasklart icons.
animationpage-568h 2x
https://cloud.githubusercontent.com/assets/10008202/8414561/e29f77dc-1ed3-11e5-82af-2e07c992b949.png
animationpage 2xhttps://cloud.githubusercontent.com/assets/10008202/8414572/ed595378-1ed3-11e5-8cbb-36411bc92973.png

**Comment by dreamnet** [comment]
I'm shortenig the title for this issue - this is a horrible long app name.
@iNfeCtGFX I thake a look at it in the next days (I'm very busy these days... and it's summertime where I live :tada:).

**Comment by dreamnet** [comment]
@iNfeCtGFX Hm, played around a while with the app and our theme, but there seems to be no chance to theme the folder page.... :cry:
