### ISSUE TITLE
Clash of Clans

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#587]
**App Name:** Clash of Clans
**Bundle ID:** com.supercell.magic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=529479190">529479190</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clash-of-clans/id529479190?mt=8&uo=4">https://itunes.apple.com/us/app/clash-of-clans/id529479190?mt=8&uo=4</a>
**App Version:** 8.332.16
**Seller:** Supercell Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/supercell/id488106216?uo=4>© Supercell</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/c9/ac/d0/c9acd0c9-417e-ca93-a867-048bbdb88895/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19104615/f2bfd45a-8add-11e6-899d-1d93a6e3296a.png)

**Comment by ivanov007** [comment]
this needs to be updated

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/19023527/cb51ab02-88b5-11e6-95fe-3f2e5708cae5.png)
https://cloud.githubusercontent.com/assets/3090247/19023527/cb51ab02-88b5-11e6-95fe-3f2e5708cae5.png
___
Source:
https://cloud.githubusercontent.com/assets/3090247/19023528/cb5e116c-88b5-11e6-827a-0b9673cc9cc2.png

**Comment by 2Qt2beStr8** [comment]
.. added some details :-)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19079255/4feb014e-8a53-11e6-832a-a530449b531c.png)
https://cloud.githubusercontent.com/assets/20930745/19079255/4feb014e-8a53-11e6-832a-a530449b531c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19079286/6c28fb7c-8a53-11e6-8899-5607cb4965b9.png)

**Comment by dreamnet** [comment]
Overworked some parts:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19104615/f2bfd45a-8add-11e6-899d-1d93a6e3296a.png)
https://cloud.githubusercontent.com/assets/2068130/19104615/f2bfd45a-8add-11e6-899d-1d93a6e3296a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19104627/ff582fe6-8add-11e6-84e5-db7e66c77afb.png
