### ISSUE TITLE
WHERE THE F*** SHOULD I GO TO EAT?

### ISSUE THREAD

**Issue by iNfeCtGFX** [glasklart/hd#5870]
**App Name:** WHERE THE F*** SHOULD I GO TO EAT?
**Bundle ID:** com.coolography
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=537697636">537697636</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/where-f***-should-i-go-to/id537697636?mt=8&uo=4">https://itunes.apple.com/us/app/where-f***-should-i-go-to/id537697636?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** coolography LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/coolography/id501210050?uo=4>© coolography</a>
**Supported Devices:** iPad3G, iPhone6, iPodTouchFourthGen, iPadMini, iPhone5s, iPadFourthGen4G, iPadWifi, iPad23G, iPadThirdGen4G, iPhone5, iPhone6Plus, iPadThirdGen, iPad2Wifi, iPhone4, iPhone-3GS, iPhone4S, iPodTouchThirdGen, iPadFourthGen, iPodTouchFifthGen, iPhone5c, iPadMini4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple/v4/c4/11/fe/c411fe20-4c12-b66b-7967-fe566de35fa0/mzl.rswtmksz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8607220/bb12fd7c-2691-11e5-9c7e-bc7bfcb7ce99.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8607220/bb12fd7c-2691-11e5-9c7e-bc7bfcb7ce99.png)
https://cloud.githubusercontent.com/assets/2068130/8607220/bb12fd7c-2691-11e5-9c7e-bc7bfcb7ce99.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8607227/c95e23b6-2691-11e5-886a-db028e7589a5.png
