### ISSUE TITLE
Matpriskollen - Inköpslistan med alla extrapriser från ICA, Coop, Willys, Hemköp, Lidl, Netto m.fl.

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5872]
**App Name:** Matpriskollen - Inköpslistan med alla extrapriser från ICA, Coop, Willys, Hemköp, Lidl, Netto m.fl.
**Bundle ID:** se.cityweb.easyapp.matpriskollen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484365728">484365728</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/matpriskollen-inkopslistan/id484365728?mt=8&uo=4">https://itunes.apple.com/us/app/matpriskollen-inkopslistan/id484365728?mt=8&uo=4</a>
**App Version:** 2.1.8
**Seller:** Matpriskollen Sverige AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/matpriskollen/id666199968?uo=4>© Matpriskollen</a>
**Supported Devices:** iPhone4, iPadThirdGen4G, iPad2Wifi, iPodTouchFourthGen, iPadThirdGen, iPhone6Plus, iPhone5s, iPhone5c, iPhone-3GS, iPad23G, iPadMini, iPadFourthGen, iPodTouchFifthGen, iPhone6, iPhone4S, iPhone5, iPadFourthGen4G, iPadMini4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/5d/93/27/5d932705-fb0a-9b74-057e-a77ed5f2e4bd/mzl.zullpgeo.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8473728/02fffc34-20ac-11e5-8c6b-921f10ee4613.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8429208/d774d490-1f25-11e5-9c09-a8f676eadb18.png)
https://cloud.githubusercontent.com/assets/10730122/8429208/d774d490-1f25-11e5-9c09-a8f676eadb18.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8429206/d37bd6ea-1f25-11e5-9743-7b311ccf504c.png

**Comment by MagnaMike** [comment]
Maybe it should be inverted? But just a stroke on the outer edge.

**Comment by dreamnet** [comment]
@MagnaMike Agree.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8473728/02fffc34-20ac-11e5-8c6b-921f10ee4613.png)
https://cloud.githubusercontent.com/assets/2068130/8473728/02fffc34-20ac-11e5-8c6b-921f10ee4613.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8473739/177c8a38-20ac-11e5-84a4-1b833a92c50f.png
