### ISSUE TITLE
Pimp Your Sound

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5874]
**App Name:** Pimp Your Sound
**Bundle ID:** com.apalonapps.pysound
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=749109884">749109884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pimp-your-sound/id749109884?mt=8&uo=4">https://itunes.apple.com/us/app/pimp-your-sound/id749109884?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** IAC Search & Media Europe Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/apalon-apps/id749046894?uo=4>© Apalon Apps</a>
**Supported Devices:** iPadMini, iPhone4S, iPadMini4G, iPadThirdGen4G, iPhone5, iPhone4, iPadThirdGen, iPhone6Plus, iPhone6, iPhone5c, iPad2Wifi, iPadFourthGen4G, iPodTouchFifthGen, iPadFourthGen, iPad23G, iPhone5s
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/5b/17/e9/5b17e9bf-f3b0-cd6a-7017-d38dbd366f31/mzl.icqifzqj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8475556/31538c6a-20b9-11e5-8069-70b5e40e223a.png)

**Comment by Trubbel** [comment]
Same as #5873,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8429435/de831fec-1f27-11e5-95a9-ec2f87c4a681.png)
https://cloud.githubusercontent.com/assets/10730122/8429435/de831fec-1f27-11e5-95a9-ec2f87c4a681.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8429431/da883f30-1f27-11e5-8695-508ec5a7d386.png

**Comment by dreamnet** [comment]
@Trubbel Why using the same icon as for #5873? The icon and app is different...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8475556/31538c6a-20b9-11e5-8069-70b5e40e223a.png)
https://cloud.githubusercontent.com/assets/2068130/8475556/31538c6a-20b9-11e5-8069-70b5e40e223a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8475562/40cf4db4-20b9-11e5-9b4d-98c6e5550fb0.png

**Comment by Trubbel** [comment]
@dreamnet I must have overlooked it, thanks for the heads up!
