### ISSUE TITLE
Speak & Translate － Free Live Voice and Text Translator with Speech and Dictionary

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5875]
**App Name:** Speak & Translate － Free Live Voice and Text Translator with Speech and Dictionary
**Bundle ID:** com.appicfun.translatorfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=804641004">804641004</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/speak-translate-free-live/id804641004?mt=8&uo=4">https://itunes.apple.com/us/app/speak-translate-free-live/id804641004?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** IAC Search & Media Europe Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/apalon-apps/id749046894?uo=4>© Apalon Apps</a>
**Supported Devices:** iPadThirdGen4G, iPhone6Plus, iPhone5, iPhone4, iPadFourthGen4G, iPhone5s, iPhone6, iPhone4S, iPad2Wifi, iPadMini, iPhone5c, iPadThirdGen, iPad23G, iPadMini4G, iPodTouchFifthGen, iPadFourthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/ff/04/ae/ff04aebe-0e1b-c469-8af8-953606f9362b/mzl.zxyzunmv.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8429682/5c39fbc0-1f2a-11e5-8ff4-df0c5ab20d8e.png)

**Comment by Trubbel** [comment]
Same as #5580, (credits to @dreamnet)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/7189846/27d9e22e-e482-11e4-8e6f-f4596f918f5b.png)
https://cloud.githubusercontent.com/assets/2068130/7189846/27d9e22e-e482-11e4-8e6f-f4596f918f5b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/7189856/3d4de9a2-e482-11e4-8759-5582e585cfe0.png

**Comment by Trubbel** [comment]
Alternate,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8429682/5c39fbc0-1f2a-11e5-8ff4-df0c5ab20d8e.png)
https://cloud.githubusercontent.com/assets/10730122/8429682/5c39fbc0-1f2a-11e5-8ff4-df0c5ab20d8e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8429679/581e5220-1f2a-11e5-88cc-7c91d883f5ad.png

**Comment by MagnaMike** [comment]
Taking alternate. :+1:
