### ISSUE TITLE
Watch

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5878]
**App Name:** Watch
**Bundle ID:** com.apple.Bridge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1069511734">1069511734</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watch/id1069511734?mt=8&uo=4">https://itunes.apple.com/us/app/watch/id1069511734?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone4S, iPhone5, iPhone5c, iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/d2/df/df/d2dfdf49-7dd5-c6bb-2934-f3df31685e22/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22862125/e872b8a8-f128-11e6-8eeb-65e9930c2a48.png)

**Comment by Trubbel** [comment]
I have no idea how to find out which devices that are supported and the artwork kept changing to a blank black icon when I tried to export it, so I picked one from the net. (Minimum required OS, 8.4)

If you know which device are supported, feel free to change.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8489465/e2986268-211b-11e5-9899-5c17481f7340.png)
https://cloud.githubusercontent.com/assets/10730122/8489465/e2986268-211b-11e5-9899-5c17481f7340.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8489464/dfe1cb5e-211b-11e5-92d9-6a7ef2ffe8cd.png

**Comment by dreamnet** [comment]
@Trubbel Thank's for opening this issue and thank's for finding out the Bundle ID! :clap:

**Comment by Trubbel** [comment]
I updated my post with iTunes ID and such as they are now available.

However should we update this or keep the old one?

Old                                                  New
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22862125/e872b8a8-f128-11e6-8eeb-65e9930c2a48.png) ![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22862124/e857b10c-f128-11e6-9b85-5d7acb0ffd1b.png)

**Comment by dreamnet** [comment]
@Trubbel Whatever you like better.

**Comment by Trubbel** [comment]
@dreamnet Hmm, I can't decide.. :laughing:

**Comment by Trubbel** [comment]
@dreamnet Sure thing!

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.Bridge-large.png). No further action needed.
