### ISSUE TITLE
iQuad

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5879]
**App Name:** iQuad
**Bundle ID:** iQuad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506922559">506922559</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iquad/id506922559?mt=8&uo=4">https://itunes.apple.com/us/app/iquad/id506922559?mt=8&uo=4</a>
**App Version:** 2.1.5
**Seller:** Jean-christophe Duchaine
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/appcom-canada/id497196359?uo=4>© AppCom Canada</a>
**Supported Devices:** iPad3G, iPadMini, iPhone-3GS, iPhone6, iPodTouchThirdGen, iPodTouchFifthGen, iPadFourthGen, iPadMini4G, iPadWifi, iPad2Wifi, iPhone4, iPadThirdGen, iPhone4S, iPadFourthGen4G, iPodTouchFourthGen, iPhone5, iPhone5s, iPhone5c, iPad23G, iPadThirdGen4G, iPhone6Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/24/a4/48/24a4485f-39e0-dd75-f64b-1f8f73bbac5a/mzl.ruiwvxxx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495671/86fcc148-216f-11e5-9bbc-27ced7454693.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495671/86fcc148-216f-11e5-9bbc-27ced7454693.png)
https://cloud.githubusercontent.com/assets/2068130/8495671/86fcc148-216f-11e5-9bbc-27ced7454693.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8495678/9739419e-216f-11e5-8000-f152ea0d049d.png

**Comment by LaCh0uine** [comment]
Omg you fast .. Ready for more ;)

**Comment by dreamnet** [comment]
@LaCh0uine Jup, no problem! :wink:
