### ISSUE TITLE
Nutshell Camera: Instant mini-movies with text and animation.

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5880]
**App Name:** Nutshell Camera: Instant mini-movies with text and animation.
**Bundle ID:** com.prezi.nutshell
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953435157">953435157</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nutshell-camera-instant-mini/id953435157?mt=8&uo=4">https://itunes.apple.com/us/app/nutshell-camera-instant-mini/id953435157?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Prezi Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/prezi-inc./id407759945?uo=4>© Prezi Inc.</a>
**Supported Devices:** iPhone5, iPadFourthGen4G, iPhone6, iPad2Wifi, iPadThirdGen4G, iPodTouchFifthGen, iPhone4S, iPadThirdGen, iPadMini, iPhone5s, iPadMini4G, iPhone5c, iPad23G, iPadFourthGen, iPhone6Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/76/88/cb/7688cb70-da83-e56c-0f50-df03f7a12685/mzl.sjdfmkhi.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495486/4489d5fe-216e-11e5-8ba9-db65b187882e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495486/4489d5fe-216e-11e5-8ba9-db65b187882e.png)
https://cloud.githubusercontent.com/assets/2068130/8495486/4489d5fe-216e-11e5-8ba9-db65b187882e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8495496/54bbde5e-216e-11e5-93aa-c1537de5ec69.png
