### ISSUE TITLE
iAddict v4

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5881]
**App Name:** iAddict v4
**Bundle ID:** com.i2cmedia.iaddict
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=770770046">770770046</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iaddict-v4/id770770046?mt=8&uo=4">https://itunes.apple.com/us/app/iaddict-v4/id770770046?mt=8&uo=4</a>
**App Version:** 4.2.1
**Seller:** Cedric CALISTI
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/calisti-cedric/id395607671?uo=4>© Calisti Cédric</a>
**Supported Devices:** iPhone5, iPhone4S, iPadThirdGen4G, iPadMini, iPad23G, iPhone5c, iPadThirdGen, iPhone4, iPhone6, iPadMini4G, iPad2Wifi, iPadFourthGen, iPhone6Plus, iPodTouchFifthGen, iPhone5s, iPadFourthGen4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/4b/45/44/4b4544cb-fbdb-2077-2702-5dcf5c1f94d0/mzl.bgiwlzep.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495411/c3a6ac14-216d-11e5-81dd-705330b128b6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495411/c3a6ac14-216d-11e5-81dd-705330b128b6.png)
https://cloud.githubusercontent.com/assets/2068130/8495411/c3a6ac14-216d-11e5-81dd-705330b128b6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8495418/d19926f8-216d-11e5-8757-0d815f99d17f.png
