### ISSUE TITLE
Flipp - Circulars, Shopping List, Weekly Ads and Deals

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5882]
**App Name:** Flipp - Circulars, Shopping List, Weekly Ads and Deals
**Bundle ID:** com.wishabi.Flipp-iOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=725097967">725097967</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flipp-circulars-shopping-list/id725097967?mt=8&uo=4">https://itunes.apple.com/us/app/flipp-circulars-shopping-list/id725097967?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Flipp Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/flipp-corporation/id492592159?uo=4>© Flipp Corporation</a>
**Supported Devices:** iPadThirdGen4G, iPhone6Plus, iPhone5c, iPadThirdGen, iPad23G, iPadMini4G, iPhone5, iPad2Wifi, iPhone5s, iPhone4, iPadFourthGen, iPadMini, iPhone4S, iPhone6, iPadFourthGen4G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/7c/8d/c3/7c8dc32c-62ec-383e-ccdd-72e7d99657d6/mzl.pcbwfuxi.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495363/5871ccc6-216d-11e5-81fa-615c9b28d14e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495363/5871ccc6-216d-11e5-81fa-615c9b28d14e.png)
https://cloud.githubusercontent.com/assets/2068130/8495363/5871ccc6-216d-11e5-81fa-615c9b28d14e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8495371/66532cb8-216d-11e5-9d7f-27fb2672e6ff.png
