### ISSUE TITLE
epost from Canada Post

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5883]
**App Name:** epost from Canada Post
**Bundle ID:** com.cpc.iOS.epostiPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=669615867">669615867</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/epost-from-canada-post/id669615867?mt=8&uo=4">https://itunes.apple.com/us/app/epost-from-canada-post/id669615867?mt=8&uo=4</a>
**App Version:** 2.0.6
**Seller:** Canada Post Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/canada-post-corporation/id394391580?uo=4>© Canada Post Corporation</a>
**Supported Devices:** iPadThirdGen, iPhone6Plus, iPadFourthGen, iPhone5c, iPhone6, iPadMini4G, iPhone5, iPad23G, iPhone5s, iPad2Wifi, iPadThirdGen4G, iPhone4, iPhone4S, iPodTouchFifthGen, iPadMini, iPadFourthGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/04/ee/fb/04eefb77-cf74-348b-aeaa-a1052da119bb/mzl.ueejrdcy.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495589/036250e6-216f-11e5-9310-e2c8558d53eb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495589/036250e6-216f-11e5-9310-e2c8558d53eb.png)
https://cloud.githubusercontent.com/assets/2068130/8495589/036250e6-216f-11e5-9310-e2c8558d53eb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8495600/141b2296-216f-11e5-9c60-c89a10c1cc1e.png
