### ISSUE TITLE
Listen: The Gesture Music Player

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5884]
**App Name:** Listen: The Gesture Music Player
**Bundle ID:** com.macpaw.Listen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=768223310">768223310</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/listen-gesture-music-player/id768223310?mt=8&uo=4">https://itunes.apple.com/us/app/listen-gesture-music-player/id768223310?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** MacPaw Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/macpaw-inc./id403752295?uo=4>© MacPaw Inc.</a>
**Supported Devices:** iPadThirdGen4G, iPadMini4G, iPhone4S, iPhone5c, iPad23G, iPhone6, iPhone6Plus, iPad2Wifi, iPhone4, iPadMini, iPhone5, iPadFourthGen4G, iPodTouchFifthGen, iPadThirdGen, iPadFourthGen, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/ca/e8/cf/cae8cf87-f55e-72fc-b81d-464d87d8e880/mzl.lctzokos.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8497125/ec6fb78c-217a-11e5-9900-563f706e4d5a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8497125/ec6fb78c-217a-11e5-9900-563f706e4d5a.png)
https://cloud.githubusercontent.com/assets/2068130/8497125/ec6fb78c-217a-11e5-9900-563f706e4d5a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8497132/fa898352-217a-11e5-87ba-8114c5a709bf.png
