### ISSUE TITLE
St-Hubert

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5886]
**App Name:** St-Hubert
**Bundle ID:** com.st-hubert.com.SH-Mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=451746812">451746812</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/st-hubert/id451746812?mt=8&uo=4">https://itunes.apple.com/ca/app/st-hubert/id451746812?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Les Rotisseries St-Hubert Ltee
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/artist/les-rotisseries-st-hubert/id451746815?uo=4>© Les Rotisseries St-Hubert Ltee</a>
**Supported Devices:** iPodTouchFifthGen, iPhone6, iPadFourthGen4G, iPhone5, iPad2Wifi, iPhone6Plus, iPhone4, iPadMini, iPad23G, iPhone4S, iPadFourthGen, iPhone5s, iPhone5c, iPadThirdGen, iPadMini4G, iPadThirdGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple4/v4/b8/37/3b/b8373b2e-2900-d6b8-c72a-b0a692111780/mzl.kpefsqie.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8505529/59280ea0-21ae-11e5-9e8b-445250b30500.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8505529/59280ea0-21ae-11e5-9e8b-445250b30500.png)
https://cloud.githubusercontent.com/assets/3090247/8505529/59280ea0-21ae-11e5-9e8b-445250b30500.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8505528/586a2214-21ae-11e5-9ee7-c16bc04e2874.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
