### ISSUE TITLE
SAQ (Société des alcools du Québec)

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5887]
**App Name:** SAQ (Société des alcools du Québec)
**Bundle ID:** com.saqmobile.saq2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382431661">382431661</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/saq-societe-des-alcools-du/id382431661?mt=8&uo=4">https://itunes.apple.com/us/app/saq-societe-des-alcools-du/id382431661?mt=8&uo=4</a>
**App Version:** 3.0.7
**Seller:** SAQ
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/saq/id382431664?uo=4>© SAQ</a>
**Supported Devices:** iPhone-3GS, iPadMini4G, iPodTouchFourthGen, iPadFourthGen, iPhone6, iPadMini, iPodTouchFifthGen, iPhone5s, iPadFourthGen4G, iPhone4, iPadThirdGen4G, iPhone5c, iPad2Wifi, iPhone6Plus, iPad23G, iPadThirdGen, iPhone4S, iPhone5
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/be/da/60/beda60c1-24ca-2d74-9a70-ffcc8f21678c/mzl.hwhdjsgs.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495294/c1ca0504-216c-11e5-8139-8fb9c34d06f5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495294/c1ca0504-216c-11e5-8139-8fb9c34d06f5.png)
https://cloud.githubusercontent.com/assets/2068130/8495294/c1ca0504-216c-11e5-8139-8fb9c34d06f5.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8495299/d0d1e648-216c-11e5-96e9-645c891484a4.png
