### ISSUE TITLE
Lotteries of Loto-Québec

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5888]
**App Name:** Lotteries of Loto-Québec
**Bundle ID:** com.ingenio-quebec.LLQ-LEL-01
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527329752">527329752</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/lotteries-of-loto-quebec/id527329752?mt=8&uo=4">https://itunes.apple.com/ca/app/lotteries-of-loto-quebec/id527329752?mt=8&uo=4</a>
**App Version:** 4.11.7
**Seller:** Ingenio, filiale de Loto-Quebec
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/artist/loto-quebec-et-ses-filiales/id445450165?uo=4>© Loto-Québec et ses filiales</a>
**Supported Devices:** iPhone5c, iPadFourthGen4G, iPodTouchFifthGen, iPadMini4G, iPhone-3GS, iPad23G, iPhone5s, iPhone4, iPhone5, iPhone4S, iPodTouchFourthGen, iPhone6, iPhone6Plus, iPadThirdGen4G, iPadMini, iPad2Wifi, iPadThirdGen, iPadFourthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/eb/4f/99/eb4f9972-1a52-ae55-7506-32a63d5c5627/mzl.ssdevuot.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495238/3fb7e3d8-216c-11e5-8ffd-6109021c30d9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495238/3fb7e3d8-216c-11e5-8ffd-6109021c30d9.png)
https://cloud.githubusercontent.com/assets/2068130/8495238/3fb7e3d8-216c-11e5-8ffd-6109021c30d9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8495244/4da0ebd4-216c-11e5-9765-664f5d3e87a5.png
