### ISSUE TITLE
Removing action

### ISSUE THREAD

**Issue by AminaKeldibek** [glasklart/hd#5889]
Hi!

Removing action does not work for some reason: I remove redundant action in the edit section and then it is still present.

**Comment by dreamnet** [comment]
@AminaKeldibek Sorry, I have no idea what you mean...? Remove what?

**Comment by dreamnet** [comment]
Well... no answer from @AminaKeldibek ... Closing.

**Comment by AminaKeldibek** [comment]
Sorry, I did not read that changes go into effect only next week.
