### ISSUE TITLE
TagsDock-Add Hashtags for Instagram from keyboard app

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5890]
**App Name:** TagsDock-Add Hashtags for Instagram from keyboard app
**Bundle ID:** com.harenalabs.TagsDock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=971209113">971209113</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tagsdock-add-hashtags-for/id971209113?mt=8&uo=4">https://itunes.apple.com/us/app/tagsdock-add-hashtags-for/id971209113?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Kevin Rajasekaran
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kevin-rajasekaran/id971209112?uo=4>© Kevin Rajasekaran</a>
**Supported Devices:** iPhone5c, iPad2Wifi, iPadFourthGen, iPhone5, iPhone6, iPadThirdGen, iPodTouchFifthGen, iPadMini, iPadFourthGen4G, iPhone6Plus, iPhone4S, iPad23G, iPhone5s, iPadThirdGen4G, iPadMini4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/08/db/4d/08db4d5d-4bc2-21ed-31f1-1821c38ae3f1/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8502653/5730f9d6-21b3-11e5-9f63-5e64aacbe60b.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8502651/4475c416-21b3-11e5-919e-cca2b22ae471.png)
https://cloud.githubusercontent.com/assets/10730122/8502651/4475c416-21b3-11e5-919e-cca2b22ae471.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8502650/3fb5905a-21b3-11e5-81b9-0e44232253ef.png

**Comment by dreamnet** [comment]
Wrong source size, correcting:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8529827/a090b546-241d-11e5-93ea-8989d3ce27d1.png)
https://cloud.githubusercontent.com/assets/2068130/8529827/a090b546-241d-11e5-93ea-8989d3ce27d1.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8529836/b29d9a88-241d-11e5-803d-59dc4ee3d8cd.png

**Comment by Trubbel** [comment]
@dreamnet So you want the source to be the original size if the icon itself is the same size as the artwork?

**Comment by dreamnet** [comment]
@Trubbel Check [this](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources) out. I hope I wrote it clear enough... :stuck_out_tongue_winking_eye:

**Comment by Trubbel** [comment]
@dreamnet I understand that, but I thought the source had to be scaled to fit the 1024x1024 resolution? I'm only asking because yours isn't. (above)
