### ISSUE TITLE
Trivia Crack (Ad Free)

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5891]
**App Name:** Trivia Crack (Ad Free)
**Bundle ID:** com.etermax.preguntados.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=723795263">723795263</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trivia-crack-ad-free/id723795263?mt=8&uo=4">https://itunes.apple.com/us/app/trivia-crack-ad-free/id723795263?mt=8&uo=4</a>
**App Version:** 2.1.5
**Seller:** Etermax
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/etermax/id286461525?uo=4>© Etermax</a>
**Supported Devices:** iPodTouchFourthGen, iPhone4S, iPadMini, iPhone4, iPodTouchFifthGen, iPhone5s, iPhone6, iPadThirdGen, iPadFourthGen, iPadThirdGen4G, iPad23G, iPadFourthGen4G, iPhone-3GS, iPhone5c, iPhone6Plus, iPhone5, iPad2Wifi, iPadMini4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/78/68/df/7868df2c-1c3b-165b-73ca-4c15e4836334/mzl.espexxjt.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5746463/1ccd1882-9c30-11e4-8b44-004fb4a60fe4.png)

**Comment by LaCh0uine** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5740628/567f29c4-9c05-11e4-9e50-3adc80d0e3b3.png

same of issue #5045

**Comment by Trubbel** [comment]
When contributing an icon, please do like @dreamnet did in the other (#5045) issue. You can just copy the whole post @dreamnet made and it should be good to go.

**Comment by LaCh0uine** [comment]
Sorry don't understand

**Comment by dreamnet** [comment]
@LaCh0uine @Trubbel It's OK, here is my icon for #5045:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5746463/1ccd1882-9c30-11e4-8b44-004fb4a60fe4.png)
https://cloud.githubusercontent.com/assets/2068130/5746463/1ccd1882-9c30-11e4-8b44-004fb4a60fe4.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/5746486/451510c4-9c30-11e4-8c46-ce030f504f4c.png
