### ISSUE TITLE
BeWeather 2 Free - Custom Weather Widget and App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5892]
**App Name:** BeWeather 2 Free - Custom Weather Widget and App
**Bundle ID:** com.bellshareinc.BeWeather2Free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=971333907">971333907</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beweather-2-free-custom-weather/id971333907?mt=8&uo=4">https://itunes.apple.com/us/app/beweather-2-free-custom-weather/id971333907?mt=8&uo=4</a>
**App Version:** 2.1.49
**Seller:** Bellshare Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bellshare-inc/id761415158?uo=4>© Bellshare Inc</a>
**Supported Devices:** iPad2Wifi, iPadFourthGen, iPadThirdGen, iPhone6, iPhone4S, iPodTouchFifthGen, iPadMini4G, iPad23G, iPhone6Plus, iPhone5, iPhone5c, iPadMini, iPhone5s, iPadFourthGen4G, iPadThirdGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/fc/47/91/fc4791ea-c139-7c52-3bbf-4279a5dec84b/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8591114/62fe945e-2626-11e5-8885-0e7db8dd47d1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8591114/62fe945e-2626-11e5-8885-0e7db8dd47d1.png)
https://cloud.githubusercontent.com/assets/2068130/8591114/62fe945e-2626-11e5-8885-0e7db8dd47d1.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8591121/7276d5cc-2626-11e5-834b-c345a87928b5.png
