### ISSUE TITLE
Stocks Widget - Track stock market portfolios and quotes inside the Today notification center

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5894]
**App Name:** Stocks Widget - Track stock market portfolios and quotes inside the Today notification center
**Bundle ID:** co.peeksoft.MyStocks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923544282">923544282</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stocks-widget-track-stock/id923544282?mt=8&uo=4">https://itunes.apple.com/us/app/stocks-widget-track-stock/id923544282?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Peeksoft LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/peeksoft-llc/id877786962?uo=4>© Peeksoft LLC</a>
**Supported Devices:** iPad2Wifi, iPhone5c, iPhone6Plus, iPadThirdGen4G, iPadFourthGen4G, iPhone4S, iPadFourthGen, iPadMini, iPhone5, iPadThirdGen, iPodTouchFifthGen, iPhone5s, iPad23G, iPadMini4G, iPhone6
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/b2/1c/83/b21c8382-a49c-f091-d12e-67ccf5b681bf/mzl.wposdtxl.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8552282/1dbdb5be-24aa-11e5-9727-83515ba13f0e.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8552282/1dbdb5be-24aa-11e5-9727-83515ba13f0e.png)
https://cloud.githubusercontent.com/assets/10950389/8552282/1dbdb5be-24aa-11e5-9727-83515ba13f0e.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8552288/2825a930-24aa-11e5-82dd-85d82df31a65.png

**Comment by dreamnet** [comment]
@zmathiasz Perfect! :+1:
