### ISSUE TITLE
Super Calendar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5895]
**App Name:** Super Calendar
**Bundle ID:** com.ronel.fernandez.Super-Calendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=862281615">862281615</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-calendar/id862281615?mt=8&uo=4">https://itunes.apple.com/us/app/super-calendar/id862281615?mt=8&uo=4</a>
**App Version:** 1.3.5
**Seller:** RONEL FERNANDEZ
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ronel-fernandez/id862281618?uo=4>© RONEL FERNANDEZ</a>
**Supported Devices:** iPhone5c, iPhone6Plus, iPad23G, iPhone5, iPad2Wifi, iPadThirdGen, iPadThirdGen4G, iPhone6, iPodTouchFifthGen, iPhone4S, iPhone4, iPhone5s, iPadFourthGen4G, iPadMini4G, iPadFourthGen, iPadMini
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/4e/3c/20/4e3c204a-dd64-9364-d8c0-718ab0461a85/mzl.bzvsjehz.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8608422/056e6934-269b-11e5-8f2c-6ca73a128cc5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8608422/056e6934-269b-11e5-8f2c-6ca73a128cc5.png)
https://cloud.githubusercontent.com/assets/2068130/8608422/056e6934-269b-11e5-8f2c-6ca73a128cc5.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8608428/141be560-269b-11e5-9dad-6189136bb232.png
