### ISSUE TITLE
FOX Sports The Big Board

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5896]
**App Name:** FOX Sports The Big Board
**Bundle ID:** com.foxsports.Bigboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=964290264">964290264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fox-sports-the-big-board/id964290264?mt=8&uo=4">https://itunes.apple.com/us/app/fox-sports-the-big-board/id964290264?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** FOX Sports Interactive
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fox-sports-interactive/id294056626?uo=4>© FOX Sports Interactive</a>
**Supported Devices:** iPhone6, iPadFourthGen, iPhone5, iPadMini, iPadMini4G, iPhone5c, iPhone4, iPad23G, iPadThirdGen4G, iPadFourthGen4G, iPhone4S, iPhone6Plus, iPhone5s, iPodTouchFifthGen, iPad2Wifi, iPadThirdGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/7c/4f/6f/7c4f6f16-caa0-d19b-8c6a-98082994bb59/mzl.guygkygh.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8543359/646d1774-246a-11e5-96fe-e3d168c76b83.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8543359/646d1774-246a-11e5-96fe-e3d168c76b83.png)
https://cloud.githubusercontent.com/assets/10950389/8543359/646d1774-246a-11e5-96fe-e3d168c76b83.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8543372/6fc854bc-246a-11e5-96b8-d7af3479dd55.png

Alternate:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8543387/7b1eaf00-246a-11e5-96ad-ae4d3cbeb73d.png)
https://cloud.githubusercontent.com/assets/10950389/8543387/7b1eaf00-246a-11e5-96ad-ae4d3cbeb73d.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8543399/83c553c0-246a-11e5-85c4-01699f68d618.png

**Comment by dreamnet** [comment]
Taking the first one. @zmathiasz :+1:
