### ISSUE TITLE
Facebook Mentions

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5897]
**App Name:** Facebook Mentions
**Bundle ID:** com.facebook.Mentions
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=894913642">894913642</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facebook-mentions/id894913642?mt=8&uo=4">https://itunes.apple.com/us/app/facebook-mentions/id894913642?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/facebook-inc./id284882218?uo=4>© Facebook, Inc.</a>
**Supported Devices:** iPodTouchFifthGen, iPhone5, iPhone6Plus, iPadThirdGen, iPad2Wifi, iPadThirdGen4G, iPadMini4G, iPhone5c, iPad23G, iPhone4S, iPhone5s, iPhone4, iPadMini, iPhone6, iPadFourthGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/f5/c2/86/f5c28656-902e-883e-df1c-0642cd4d6dd5/mzl.vmzhfaui.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8508605/68b539a4-223c-11e5-92fe-07e84ee6e7ff.png)

**Comment by ivanov007** [comment]
I think the same icon as #1054 will do it
just updating this icon
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8508605/68b539a4-223c-11e5-92fe-07e84ee6e7ff.png)
https://cloud.githubusercontent.com/assets/3090247/8508605/68b539a4-223c-11e5-92fe-07e84ee6e7ff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8508606/68b8b246-223c-11e5-8304-b1e892a009b7.png

**Comment by Trubbel** [comment]
@ivanov007 Agreed!

**Comment by dreamnet** [comment]
@ivanov007 Also!
