### ISSUE TITLE
Centris.ca

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#5898]
**App Name:** Centris.ca
**Bundle ID:** ca.centris.centris.ca.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=604024675">604024675</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/centris.ca/id604024675?mt=8&uo=4">https://itunes.apple.com/us/app/centris.ca/id604024675?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** CIGM
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/centris.ca/id604024678?uo=4>© Centris.ca®</a>
**Supported Devices:** iPadMini, iPhone5s, iPad23G, iPad2Wifi, iPodTouchFifthGen, iPhone6, iPadFourthGen4G, iPhone5c, iPadMini4G, iPhone6Plus, iPhone4, iPadFourthGen, iPhone5, iPadThirdGen, iPadThirdGen4G, iPhone4S
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/be/7b/3b/be7b3ba5-5e35-e0e2-8065-08f0c7582ca2/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509725/b09cd5f4-227a-11e5-8acf-10c98a62ab71.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509725/b09cd5f4-227a-11e5-8acf-10c98a62ab71.png)
https://cloud.githubusercontent.com/assets/3090247/8509725/b09cd5f4-227a-11e5-8acf-10c98a62ab71.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8509726/b0a26668-227a-11e5-9868-57526a5e8603.png
