### ISSUE TITLE
POLARIS Office 5 - for Microsoft Office Word, Powerpoint, Excel documents

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#5899]
**App Name:** POLARIS Office 5 - for Microsoft Office Word, Powerpoint, Excel documents
**Bundle ID:** kr.co.infraware.polarisoffice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=513188658">513188658</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/polaris-office-5-for-microsoft/id513188658?mt=8&uo=4">https://itunes.apple.com/us/app/polaris-office-5-for-microsoft/id513188658?mt=8&uo=4</a>
**App Version:** 5.0.10
**Seller:** Infraware Co.Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/infraware-co.-ltd/id380275428?uo=4>© Infraware Co.,Ltd</a>
**Supported Devices:** iPhone4, iPhone5c, iPadMini, iPhone6, iPhone5s, iPadThirdGen, iPhone6Plus, iPadFourthGen4G, iPodTouchFifthGen, iPadMini4G, iPad2Wifi, iPad23G, iPadFourthGen, iPhone4S, iPadThirdGen4G, iPhone5
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/39/15/18/391518bf-7dbb-cc3d-38de-ffb5014819f5/mzl.htruhoxh.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509801/6124009a-2281-11e5-8d24-07b0fc7e8749.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509801/6124009a-2281-11e5-8d24-07b0fc7e8749.png)
https://cloud.githubusercontent.com/assets/3090247/8509801/6124009a-2281-11e5-8d24-07b0fc7e8749.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8509802/613021f4-2281-11e5-9629-7e62e088cd1c.png

**Comment by dreamnet** [comment]
@ivanov007 You are an icon-maniac... :wink: :+1:
