### ISSUE TITLE
FWD Sportscard

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#5900]
**App Name:** FWD Sportscard
**Bundle ID:** com.quattriuum.fwdsportscard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=604747777">604747777</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fwd-sportscard/id604747777?mt=8&uo=4">https://itunes.apple.com/us/app/fwd-sportscard/id604747777?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Quattriuum inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/quattriuum/id604747780?uo=4>© Quattriuum</a>
**Supported Devices:** iPhone5s, iPhone5c, iPadFourthGen, iPadFourthGen4G, iPhone4, iPad23G, iPadMini4G, iPodTouchFifthGen, iPhone6, iPadThirdGen4G, iPadMini, iPhone6Plus, iPad2Wifi, iPadThirdGen, iPhone5, iPhone4S
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/d8/f7/ae/d8f7ae17-db7a-65d7-7d80-3f2b29516acf/mzl.zfqkcdwg.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509753/40441454-227d-11e5-9426-46d1602932c7.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509753/40441454-227d-11e5-9426-46d1602932c7.png)
https://cloud.githubusercontent.com/assets/3090247/8509753/40441454-227d-11e5-9426-46d1602932c7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8509754/40503a54-227d-11e5-817c-ac5b38132a6c.png
