### ISSUE TITLE
SurveyMonkey

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#5901]
**App Name:** SurveyMonkey
**Bundle ID:** com.surveymonkey.SurveyMonkey
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=723867634">723867634</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/surveymonkey/id723867634?mt=8&uo=4">https://itunes.apple.com/us/app/surveymonkey/id723867634?mt=8&uo=4</a>
**App Version:** 1.0.920
**Seller:** SURVEYMONKEY INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/surveymonkey/id723867637?uo=4>© SurveyMonkey</a>
**Supported Devices:** iPhone6Plus, iPhone5s, iPhone6, iPodTouchFifthGen, iPad2Wifi, iPadMini4G, iPadThirdGen4G, iPadFourthGen4G, iPhone4S, iPhone5c, iPad23G, iPadMini, iPhone4, iPadThirdGen, iPadFourthGen, iPhone5
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/28/c5/6e/28c56e5a-1ef8-86d9-ecb7-af4fbbc4086e/mzl.jkialwbg.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509698/e2048008-2278-11e5-9a9f-2f0354834c85.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509698/e2048008-2278-11e5-9a9f-2f0354834c85.png)
https://cloud.githubusercontent.com/assets/3090247/8509698/e2048008-2278-11e5-9a9f-2f0354834c85.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8509699/e207ca88-2278-11e5-993a-c33e1ea2fc5f.png
