### ISSUE TITLE
FollowUp.cc

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#5902]
**App Name:** FollowUp.cc
**Bundle ID:** cc.followup.FollowUpCC
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=924023926">924023926</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/followup.cc/id924023926?mt=8&uo=4">https://itunes.apple.com/us/app/followup.cc/id924023926?mt=8&uo=4</a>
**App Version:** 1.2.4
**Seller:** Argon Technologies LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/followup.cc/id970114213?uo=4>© FollowUp.cc</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen4G, iPad23G, iPadFourthGen4G, iPadThirdGen, iPhone6Plus, iPhone4S, iPadMini, iPodTouchFifthGen, iPhone5, iPadMini4G, iPhone4, iPhone5c, iPhone6, iPhone5s, iPadFourthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/45/ee/30/45ee301a-edc5-a184-9d46-29463fc90dca/mzl.wzsdjzwt.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509467/ba542fee-226a-11e5-9f8d-0745741ecd89.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509467/ba542fee-226a-11e5-9f8d-0745741ecd89.png)
https://cloud.githubusercontent.com/assets/3090247/8509467/ba542fee-226a-11e5-9f8d-0745741ecd89.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8509468/ba54e2fe-226a-11e5-972e-6f257626b80e.png
