### ISSUE TITLE
Beecon - Automate Your Home, Office or Business with Beacons

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#5903]
**App Name:** Beecon - Automate Your Home, Office or Business with Beacons
**Bundle ID:** com.beecon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=822251888">822251888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beecon-automate-your-home/id822251888?mt=8&uo=4">https://itunes.apple.com/us/app/beecon-automate-your-home/id822251888?mt=8&uo=4</a>
**App Version:** 6.5
**Seller:** Ribeiro Sa Menezes
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/new-people-on-the-block/id498031512?uo=4>© New People on the Block</a>
**Supported Devices:** iPhone5c, iPhone6, iPhone5s, iPad2Wifi, iPhone5, iPodTouchFifthGen, iPadThirdGen4G, iPhone6Plus, iPadFourthGen, iPadFourthGen4G, iPhone4S, iPadMini, iPad23G, iPadThirdGen, iPadMini4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple3/v4/2e/61/fb/2e61fb27-a7f8-ec57-75a1-877f2592853e/mzl.rdjhiayv.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8583783/b9e6f88e-25d0-11e5-8d3e-9c1773365258.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8509448/39e59876-2269-11e5-94f3-53825ea3fc59.png)
https://cloud.githubusercontent.com/assets/3090247/8509448/39e59876-2269-11e5-94f3-53825ea3fc59.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8509449/3a03d426-2269-11e5-9a26-bea8fee91a47.png

**Comment by dreamnet** [comment]
Original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8583783/b9e6f88e-25d0-11e5-8d3e-9c1773365258.png)
https://cloud.githubusercontent.com/assets/2068130/8583783/b9e6f88e-25d0-11e5-8d3e-9c1773365258.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8583792/c95d3e2c-25d0-11e5-806f-b9d27de3f9de.png
