### ISSUE TITLE
Call Recorder (iOS)

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#5904]
**App Name:** Call Recorder (iOS)
 **Bundle ID:** org.hacx.callrecorder
 **Version:** 1.99
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://dl.dropboxusercontent.com/u/10535485/callrecorder.png" width="150" height="150" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8805849/73ddba28-2fa1-11e5-85bd-5cc6ea3ad88a.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8790467/57226936-2f1c-11e5-9384-1fa087aedd73.png)

**Comment by dreamnet** [comment]
@Teekzilla Good work, I would take it if I only had a 1024x1024px source.....

**Comment by Teekzilla** [comment]
@dreamnet Haha I see the recurring pattern, will get back to you!

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8803192/8918a960-2f93-11e5-81a0-e5ba7b014712.png)

Source: https://cloud.githubusercontent.com/assets/7368317/8803193/89d4f5f2-2f93-11e5-86ca-baf25ab87f9f.png

@dreamnet How does this submission look to you? Redid everything using Paths/Custom Shapes. I also included the 1024 x 1024 source file this time!

**Comment by MagnaMike** [comment]
I'm not @dreamnet but it looks great to me!

**Comment by dreamnet** [comment]
@Teekzilla Jup, fine! :+1:
