### ISSUE TITLE
Horizon 3 - Calendar + Weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5905]
**App Name:** Horizon 3 - Calendar + Weather
**Bundle ID:** com.ApplauseCode.HorizonCalendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=933026631">933026631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/horizon-3-calendar-+-weather/id933026631?mt=8&uo=4">https://itunes.apple.com/us/app/horizon-3-calendar-+-weather/id933026631?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Applause Code, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/applause-code-llc/id415884047?uo=4>© Applause Code, LLC</a>
**Supported Devices:** iPad23G, iPadThirdGen4G, iPhone5, iPadFourthGen, iPodTouchFifthGen, iPhone5c, iPadFourthGen4G, iPadMini4G, iPhone6Plus, iPhone4S, iPhone5s, iPhone6, iPadMini, iPadThirdGen, iPad2Wifi
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/e7/6a/73/e76a73c6-6eee-7e65-f803-257b16602f43/mzl.adcegppy.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8542895/082a2252-2467-11e5-9016-cc3a33784987.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8542895/082a2252-2467-11e5-9016-cc3a33784987.png)
https://cloud.githubusercontent.com/assets/10950389/8542895/082a2252-2467-11e5-9016-cc3a33784987.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8542901/11bb1f4c-2467-11e5-8087-4d7f4e365eb5.png

**Comment by dreamnet** [comment]
@zmathiasz Jup! :+1:
