### ISSUE TITLE
klart.se - Sveriges bästa väder

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5906]
**App Name:** klart.se - Sveriges bästa väder
**Bundle ID:** se.klart.klart
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=352024322">352024322</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/klart.se-sveriges-basta-vader/id352024322?mt=8&uo=4">https://itunes.apple.com/us/app/klart.se-sveriges-basta-vader/id352024322?mt=8&uo=4</a>
**App Version:** 4.4.1
**Seller:** K Lartpunktse Vädertjänster AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/klart-vadertjanster-ab/id638202240?uo=4>© Klart Vädertjänster AB</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple71/v4/6b/93/36/6b9336ad-a021-6084-7ae6-24280d9d42a2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18341990/0494d892-75ad-11e6-949a-c344e0b40f70.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8513435/ab1c56f8-236b-11e5-89b0-226d02116588.png)
https://cloud.githubusercontent.com/assets/10730122/8513435/ab1c56f8-236b-11e5-89b0-226d02116588.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8513434/a756a488-236b-11e5-8ace-2a97b9665461.png

**Comment by Trubbel** [comment]
Alternate,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8513444/c2b60d90-236b-11e5-97e4-f7ebfafae94e.png)
https://cloud.githubusercontent.com/assets/10730122/8513444/c2b60d90-236b-11e5-97e4-f7ebfafae94e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8513443/be3e3940-236b-11e5-97d5-5910ae1b6629.png

**Comment by ivanov007** [comment]
@Trubbel  the alternate looks good :+1:

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18341990/0494d892-75ad-11e6-949a-c344e0b40f70.png)
https://cloud.githubusercontent.com/assets/10730122/18341990/0494d892-75ad-11e6-949a-c344e0b40f70.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18341989/047dd142-75ad-11e6-9303-b6343c294490.png
