### ISSUE TITLE
Fitness

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5908]
**App Name:** Fitness
**Bundle ID:** com.apple.Fitness
**iTunes ID:** N/A
**iTunes URL:** N/A
**App Version:** 1.0
**Seller:** Apple Inc.
**Developer:** Apple Inc.
**Supported Devices:** -
**Original Artwork:**
<img src="https://i.imgur.com/TGsdlx3.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8582661/94c53dac-25c8-11e5-9d75-4bce4928caaa.png)

**Comment by Trubbel** [comment]
This application appears when you pair your Apple Watch, however, I could only find a 180x180 artwork in it's folder. I'm not sure *I* can work with that, I'll leave it to anyone else.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8582661/94c53dac-25c8-11e5-9d75-4bce4928caaa.png)
https://cloud.githubusercontent.com/assets/2068130/8582661/94c53dac-25c8-11e5-9d75-4bce4928caaa.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8582673/a3a88158-25c8-11e5-890d-a8f43d0e4051.png

**Comment by Trubbel** [comment]
@dreamnet Nice!

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31318803-080e0d3a-ac58-11e7-9262-e80014d9dbfc.png)
https://user-images.githubusercontent.com/2068130/31318803-080e0d3a-ac58-11e7-9262-e80014d9dbfc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31318806-1ab2b42c-ac58-11e7-87a5-6577058b2a04.png
