### ISSUE TITLE
Facebook Ads Manager

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5909]
**App Name:** Facebook Ads Manager
**Bundle ID:** com.facebook.MAdMan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=964397083">964397083</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facebook-ads-manager/id964397083?mt=8&uo=4">https://itunes.apple.com/us/app/facebook-ads-manager/id964397083?mt=8&uo=4</a>
**App Version:** 7.0
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/facebook-inc./id284882218?uo=4>© Facebook, Inc.</a>
**Supported Devices:** iPadThirdGen, iPhone5s, iPhone6, iPhone4S, iPad23G, iPadMini4G, iPhone5c, iPhone4, iPad2Wifi, iPadThirdGen4G, iPodTouchFifthGen, iPhone5, iPhone6Plus, iPadFourthGen, iPadFourthGen4G, iPadMini
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/71/79/cb/7179cbf6-c1e9-f856-722d-283f87e0e874/mzl.iopwjguk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8557394/660282fc-24fd-11e5-91ad-e66df9598b8c.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8543177/f51dacea-2468-11e5-8035-6ee68b08321d.png)
https://cloud.githubusercontent.com/assets/10950389/8543177/f51dacea-2468-11e5-8035-6ee68b08321d.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8543186/fe234c0a-2468-11e5-8cd9-2fdefc461d06.png

**Comment by dreamnet** [comment]
Here is my try:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8557394/660282fc-24fd-11e5-91ad-e66df9598b8c.png)
https://cloud.githubusercontent.com/assets/2068130/8557394/660282fc-24fd-11e5-91ad-e66df9598b8c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8557402/746b9fcc-24fd-11e5-9458-4b99ade9b5b5.png

**Comment by zmathiasz** [comment]
The fade does fit the original better. I like it.

**Comment by Trubbel** [comment]
I agree with @zmathiasz. Nicely done @dreamnet!
