### ISSUE TITLE
CloudFlex

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5910]
**App Name:** CloudFlex
 **Bundle ID:** ro.randusoft.CloudFlex
 **Version:** 1.0
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/10730122/8521574/66a73b58-23e5-11e5-86cb-a02ef24471d5.jpg" width="150" height="150" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8537360/63179490-2423-11e5-9eaf-14bf76780c5c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8537360/63179490-2423-11e5-9eaf-14bf76780c5c.png)
https://cloud.githubusercontent.com/assets/3090247/8537360/63179490-2423-11e5-9eaf-14bf76780c5c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8537359/63117c22-2423-11e5-802b-d7c9ddc2ddfb.png

**Comment by Trubbel** [comment]
@ivanov007 Well done! :+1:
