### ISSUE TITLE
Tossup, a Microsoft Garage project

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5914]
**App Name:** Tossup, a Microsoft Garage project
**Bundle ID:** com.microsoft.huddle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=978834606">978834606</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tossup-microsoft-garage-project/id978834606?mt=8&uo=4">https://itunes.apple.com/us/app/tossup-microsoft-garage-project/id978834606?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPad23G, iPadThirdGen4G, iPhone6, iPhone6Plus, iPadMini4G, iPadThirdGen, iPhone4S, iPodTouchFifthGen, iPadMini, iPadFourthGen4G, iPhone5c, iPad2Wifi, iPhone5, iPadFourthGen, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/2d/61/93/2d61933b-42d5-c412-0663-1604e5793b54/mzl.fjptxfys.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8537079/4dc00f9a-241f-11e5-8c5c-2a7fe1911779.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8537079/4dc00f9a-241f-11e5-8c5c-2a7fe1911779.png)
https://cloud.githubusercontent.com/assets/3090247/8537079/4dc00f9a-241f-11e5-8c5c-2a7fe1911779.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8537080/4dc0b6fc-241f-11e5-8099-c8003f77e83d.png)
