### ISSUE TITLE
Posterized - Dribbble Design Inspiration

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5915]
**App Name:** Posterized - Dribbble Design Inspiration
**Bundle ID:** com.totoros.Posterized
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=893458064">893458064</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/posterized-dribbble-design/id893458064?mt=8&uo=4">https://itunes.apple.com/us/app/posterized-dribbble-design/id893458064?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Kenny Chen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/kenny-chen/id893458067?uo=4>© Kenny Chen</a>
**Supported Devices:** iPad2Wifi, iPodTouchFifthGen, iPadFourthGen, iPhone6, iPadMini4G, iPhone5c, iPhone5, iPadMini, iPad23G, iPadFourthGen4G, iPhone4, iPhone4S, iPadThirdGen4G, iPadThirdGen, iPhone6Plus, iPhone5s
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/26/8d/59/268d591d-bedb-714f-896f-aff357f4f36c/mzl.tiyuazfc.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8531680/78932892-2429-11e5-9fef-02efda3e8d35.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8531680/78932892-2429-11e5-9fef-02efda3e8d35.png)
https://cloud.githubusercontent.com/assets/10730122/8531680/78932892-2429-11e5-9fef-02efda3e8d35.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8531678/7413f10c-2429-11e5-806b-477354b2231f.png

**Comment by Trubbel** [comment]
Alternate,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8531701/97f358d8-2429-11e5-8c97-ce3fc89fa069.png)
https://cloud.githubusercontent.com/assets/10730122/8531701/97f358d8-2429-11e5-8c97-ce3fc89fa069.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8531699/9449c47e-2429-11e5-844a-79c406d695c1.png

**Comment by dreamnet** [comment]
I'm taking the first one - it's more like the original.
