### ISSUE TITLE
Dribbboard - client for Dribbble

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5917]
**App Name:** Dribbboard - client for Dribbble
**Bundle ID:** com.sarunw.dribbboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=994079895">994079895</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dribbboard-client-for-dribbble/id994079895?mt=8&uo=4">https://itunes.apple.com/us/app/dribbboard-client-for-dribbble/id994079895?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Sarun Wongpatcharapakorn
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sarun-wongpatcharapakorn/id469774500?uo=4>© Sarun Wongpatcharapakorn</a>
**Supported Devices:** iPadFourthGen4G, iPhone6, iPhone5c, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen4G, iPadFourthGen, iPadMini4G, iPhone6Plus, iPhone5s, iPadMini, iPodTouchFifthGen, iPhone5, iPadThirdGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/cf/9f/55/cf9f55cb-8641-2eb3-9fe6-01e8ce0fa92a/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8893365/d8c544ca-338d-11e5-9bd1-f51fdbb78b9e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8891414/10ed91d2-3329-11e5-9ca9-678116372f0b.png)
https://cloud.githubusercontent.com/assets/2068130/8891414/10ed91d2-3329-11e5-9ca9-678116372f0b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8891416/1fad47da-3329-11e5-90c8-5fdd687b7716.png
???

**Comment by Trubbel** [comment]
@dreamnet :+1:

**Comment by MagnaMike** [comment]
I don't think so. The backboard isn't represented, only the 'box' is. The white area should be glasklart style and the grey area should be transparent See what I mean:
![](https://cloud.githubusercontent.com/assets/2236254/8891450/4ebef1ee-32f8-11e5-82bc-2efff83b9c07.jpg)

**Comment by dreamnet** [comment]
Ah, now I see... The original icon should be a basket case. Man... :confused:

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8893365/d8c544ca-338d-11e5-9bd1-f51fdbb78b9e.png)
https://cloud.githubusercontent.com/assets/2068130/8893365/d8c544ca-338d-11e5-9bd1-f51fdbb78b9e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8893368/e84de1d6-338d-11e5-8100-0c7275119c0b.png
Better?

**Comment by MagnaMike** [comment]
@dreamnet Perfect! :+1:
