### ISSUE TITLE
KultureGeek : l'actu Geek et High-Tech

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5919]
**App Name:** KultureGeek : l'actu Geek et High-Tech
**Bundle ID:** com.i2cmedia.kulturegeek
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=975180029">975180029</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kulturegeek-lactu-geek-et/id975180029?mt=8&uo=4">https://itunes.apple.com/us/app/kulturegeek-lactu-geek-et/id975180029?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Cedric CALISTI
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/calisti-cedric/id395607671?uo=4>© Calisti Cédric</a>
**Supported Devices:** iPhone5, iPhone4, iPodTouchFifthGen, iPhone6, iPhone6Plus, iPad23G, iPadMini, iPadMini4G, iPadThirdGen, iPadFourthGen4G, iPad2Wifi, iPhone4S, iPadFourthGen, iPadThirdGen4G, iPhone5c, iPhone5s
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/ce/e0/1d/cee01d58-7c4d-73db-ed5e-c27c5614153a/mzl.nmvhbrty.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8807423/c6464f92-2fdc-11e5-9142-08878bb202df.png)

**Comment by LaCh0uine** [comment]
Please I have only 4 icons left for complete springboard:) 

Thank you

**Comment by Trubbel** [comment]
I gave it my best shot, if anyone can do a better job, please do.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8807423/c6464f92-2fdc-11e5-9142-08878bb202df.png)
https://cloud.githubusercontent.com/assets/10730122/8807423/c6464f92-2fdc-11e5-9142-08878bb202df.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8807422/c239bfce-2fdc-11e5-8528-d871c942d0fd.png

**Comment by LaCh0uine** [comment]
It's great for me ;)
#5933 #5977 #5998 retry to try the 3 left ;)

**Comment by dreamnet** [comment]
@Trubbel Great one!! :+1: :+1:
