### ISSUE TITLE
Angry Birds Epic

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5920]
**App Name:** Angry Birds Epic
**Bundle ID:** com.rovio.gold
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=767319014">767319014</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds-epic/id767319014?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds-epic/id767319014?mt=8&uo=4</a>
**App Version:** 1.2.7
**Seller:** Rovio Entertainment Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/rovio-entertainment-ltd/id298910979?uo=4>© Rovio Entertainment Ltd</a>
**Supported Devices:** iPhone4, iPhone5s, iPhone6Plus, iPadThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone5c, iPadMini, iPadFourthGen4G, iPadMini4G, iPhone4S, iPhone6, iPhone-3GS, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/58/5f/ae/585fae8e-8b60-e91d-bdc7-603ccd6b4e31/mzl.psooozjx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8536434/ed2f1426-2416-11e5-94c5-d9060dee143f.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8536122/7be2c38e-2412-11e5-9b11-46a608271996.png)

--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8536105/507335e4-2412-11e5-92f9-f5a7b1eaf2f8.png

**Comment by LaCh0uine** [comment]
Very Nice thank you

**Comment by Trubbel** [comment]
@ivanov007 :+1:
