### ISSUE TITLE
My Metro

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5921]
**App Name:** My Metro
**Bundle ID:** ca.metro.appmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=694386842">694386842</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-metro/id694386842?mt=8&uo=4">https://itunes.apple.com/us/app/my-metro/id694386842?mt=8&uo=4</a>
**App Version:** 1.7.0
**Seller:** Metro Richelieu Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/metro-inc./id694386848?uo=4>© Metro Inc.</a>
**Supported Devices:** iPadMini4G, iPhone4S, iPhone5c, iPad2Wifi, iPadFourthGen4G, iPhone6Plus, iPadThirdGen, iPadMini, iPadThirdGen4G, iPhone6, iPodTouchFifthGen, iPhone5, iPad23G, iPadFourthGen, iPhone5s, iPhone4
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/98/bc/c6/98bcc675-262c-78d2-4f6e-4f4a455f9bbc/mzl.fkwkeiya.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8590516/aa120272-2621-11e5-8ef9-38c48037fb7f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8590516/aa120272-2621-11e5-8ef9-38c48037fb7f.png)
https://cloud.githubusercontent.com/assets/2068130/8590516/aa120272-2621-11e5-8ef9-38c48037fb7f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8590527/b8c329c2-2621-11e5-9c33-fa094cee2dbd.png

**Comment by LaCh0uine** [comment]
@dreamnet 👍🏻
