### ISSUE TITLE
McDonald's Canada

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5922]
**App Name:** McDonald's Canada
**Bundle ID:** ca.mcdonalds.McDonalds
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375695000">375695000</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/mcdonalds-canada/id375695000?mt=8&uo=4">https://itunes.apple.com/ca/app/mcdonalds-canada/id375695000?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** McDonald's Restaurants of Canada Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/artist/mcdonalds-restaurants-canada/id375695003?uo=4>© McDonald's Restaurants of Canada Limited</a>
**Supported Devices:** iPhone5c, iPadThirdGen, iPhone-3GS, iPad2Wifi, iPhone4S, iPhone6Plus, iPodTouchFourthGen, iPhone5, iPhone6, iPadMini4G, iPadMini, iPadThirdGen4G, iPodTouchFifthGen, iPadFourthGen4G, iPhone4, iPadFourthGen, iPad23G, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/73/cc/47/73cc479d-3df6-29d3-f71e-d1e416f1be97/mzl.ujshmevd.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8590608/6a4914d6-2622-11e5-96d6-2e85cff7d040.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8590608/6a4914d6-2622-11e5-96d6-2e85cff7d040.png)
https://cloud.githubusercontent.com/assets/2068130/8590608/6a4914d6-2622-11e5-96d6-2e85cff7d040.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8590614/7b23373c-2622-11e5-9ec6-97b25c86d2f9.png

**Comment by LaCh0uine** [comment]
@dreamnet 👍🏻
