### ISSUE TITLE
Overstock - Mobile Shopping

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5923]
**App Name:** Overstock - Mobile Shopping
**Bundle ID:** com.overstock.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=339883869">339883869</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/overstock-mobile-shopping/id339883869?mt=8&uo=4">https://itunes.apple.com/us/app/overstock-mobile-shopping/id339883869?mt=8&uo=4</a>
**App Version:** 3.2.5
**Seller:** Overstock.com Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/overstock.com/id339883872?uo=4>© Overstock.com</a>
**Supported Devices:** iPhone4S, iPadFourthGen, iPhone6, iPad2Wifi, iPhone5s, iPadThirdGen, iPhone5c, iPadThirdGen4G, iPadMini4G, iPhone5, iPadFourthGen4G, iPhone6Plus, iPhone4, iPad23G, iPodTouchFifthGen, iPadMini
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/d9/14/e2/d914e28c-6d78-113a-c063-593b9b248233/mzl.ocnponiy.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8541571/508e552c-245d-11e5-83c7-964ecd6ca155.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8541520/e7319832-245c-11e5-8085-2dfb99a74b79.png)
https://cloud.githubusercontent.com/assets/10950389/8541520/e7319832-245c-11e5-8085-2dfb99a74b79.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8541556/32b0be32-245d-11e5-9253-f3fa5a224dfe.png

Alternate (Bigger):
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8541571/508e552c-245d-11e5-83c7-964ecd6ca155.png)
https://cloud.githubusercontent.com/assets/10950389/8541571/508e552c-245d-11e5-83c7-964ecd6ca155.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8541578/5ee9e0f0-245d-11e5-81b1-5402b91011fa.png

**Comment by dreamnet** [comment]
Hmmmmm... Taking the second one.
