### ISSUE TITLE
CVS Pharmacy

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5924]
**App Name:** CVS Pharmacy
**Bundle ID:** com.cvs.cvspharmacy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395545555">395545555</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cvs-pharmacy/id395545555?uo=4">https://apps.apple.com/us/app/cvs-pharmacy/id395545555?uo=4</a>
**App Version:** 5.7.1
**Seller:** CVS Pharmacy
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/cvs-pharmacy/id395545558?uo=4">© CVS Pharmacy</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/f8/ec/8b/f8ec8bb6-6562-af6c-6bcd-ae4cfd4cc12b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61991676-063e5300-b054-11e9-9c0e-6c5b4e74206c.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8541857/38a255f6-245f-11e5-86e0-5d7b48fe6546.png)
https://cloud.githubusercontent.com/assets/10950389/8541857/38a255f6-245f-11e5-86e0-5d7b48fe6546.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8541866/4699c3a6-245f-11e5-9c9f-75fbccd6efa9.png

**Comment by XPEric** [comment]
Needs update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61991676-063e5300-b054-11e9-9c0e-6c5b4e74206c.png)
https://user-images.githubusercontent.com/2068130/61991676-063e5300-b054-11e9-9c0e-6c5b4e74206c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/61991678-15bd9c00-b054-11e9-8661-6970a77b9b5d.png
