### ISSUE TITLE
Enlight

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5925]
**App Name:** Enlight
**Bundle ID:** com.lightricks.Enlight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=930026670">930026670</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/enlight/id930026670?mt=8&uo=4">https://itunes.apple.com/us/app/enlight/id930026670?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Lightricks Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/lightricks-ltd./id606310584?uo=4>© Lightricks Ltd.</a>
**Supported Devices:** iPhone4S, iPhone6Plus, iPhone5, iPhone5c, iPhone5s, iPhone6, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/c7/af/54/c7af54d2-ea12-3f71-83a4-257be72d98c3/mzl.llnaekwf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8605513/1bb93242-2686-11e5-9c8a-e7082a93dbbb.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8542365/27839984-2463-11e5-83a3-386aac2485b9.png)
https://cloud.githubusercontent.com/assets/10950389/8542365/27839984-2463-11e5-83a3-386aac2485b9.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8542372/35cdf462-2463-11e5-975e-6cc122cc829b.png

**Comment by dreamnet** [comment]
Dis some cleanup and resizing:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8605513/1bb93242-2686-11e5-9c8a-e7082a93dbbb.png)
https://cloud.githubusercontent.com/assets/2068130/8605513/1bb93242-2686-11e5-9c8a-e7082a93dbbb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8605523/2ab98a08-2686-11e5-830d-1d2640b7095d.png
