### ISSUE TITLE
Brave Frontier

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5928]
**App Name:** Brave Frontier
**Bundle ID:** com.gumi.bfsg
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=694609161">694609161</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/brave-frontier/id694609161?mt=8&uo=4">https://itunes.apple.com/us/app/brave-frontier/id694609161?mt=8&uo=4</a>
**App Version:** 1.3.22
**Seller:** gumi Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/gumi-inc./id532518920?uo=4>© gumi Inc.</a>
**Supported Devices:** iPhone4, iPodTouchFifthGen, iPodTouchFourthGen, iPad2Wifi, iPhone6Plus, iPhone4S, iPhone5, iPhone6, iPadWifi, iPodTouchThirdGen, iPhone5s, iPadThirdGen, iPhone-3GS, iPadThirdGen4G, iPadMini4G, iPadMini, iPhone5c, iPadFourthGen4G, iPad3G, iPad23G, iPadFourthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/a6/47/ea/a647ea04-4612-f855-afd5-64e3dd61b4a1/mzl.fdsdrxjg.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8574584/68e79f1c-2565-11e5-956c-c786c2b84456.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8552651/6e5f0c46-24ac-11e5-9587-079a13344f38.png)
https://cloud.githubusercontent.com/assets/10950389/8552651/6e5f0c46-24ac-11e5-9587-079a13344f38.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8552658/78c63182-24ac-11e5-9bec-7f3aefbd6ea0.png

**Comment by zmathiasz** [comment]
Hmm, not sure if I'm happy with it or not.. :question:

**Comment by Trubbel** [comment]
@zmathiasz I think it's alright! :+1:

**Comment by dreamnet** [comment]
@zmathiasz It's great! :+1:

**Comment by zmathiasz** [comment]
I cleaned this up alittle bit.  I feel it looks much better now.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8574584/68e79f1c-2565-11e5-956c-c786c2b84456.png)
https://cloud.githubusercontent.com/assets/10950389/8574584/68e79f1c-2565-11e5-956c-c786c2b84456.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8574594/76c958c8-2565-11e5-9494-f4071a3c5251.png

**Comment by dreamnet** [comment]
@zmathiasz :+1:
