### ISSUE TITLE
Wikia Fan App for: Brave Frontier

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5929]
**App Name:** Wikia Fan App for: Brave Frontier
**Bundle ID:** com.wikia.app.swa.bravefrontier
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=956796965">956796965</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wikia-fan-app-for-brave-frontier/id956796965?mt=8&uo=4">https://itunes.apple.com/us/app/wikia-fan-app-for-brave-frontier/id956796965?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Wikia Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/wikia-inc./id422467077?uo=4>© Wikia, Inc.</a>
**Supported Devices:** iPhone4S, iPadMini4G, iPad23G, iPodTouchFifthGen, iPadFourthGen4G, iPadThirdGen, iPhone5c, iPhone6Plus, iPhone4, iPhone5s, iPadThirdGen4G, iPhone6, iPhone5, iPadMini, iPad2Wifi, iPadFourthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/41/b3/1b/41b31bbd-9320-02da-427a-eccf77cc40e7/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8996958/afedfcbc-371c-11e5-8755-ae187fb47f18.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8996958/afedfcbc-371c-11e5-8755-ae187fb47f18.png)
https://cloud.githubusercontent.com/assets/2068130/8996958/afedfcbc-371c-11e5-8755-ae187fb47f18.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8996966/be8a8574-371c-11e5-8e85-cc6455a0aec4.png
