### ISSUE TITLE
Scalar: the Better Calculator

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5930]
**App Name:** Scalar: the Better Calculator
**Bundle ID:** com.criticalpt.scalar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380168978">380168978</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scalar-the-better-calculator/id380168978?mt=8&uo=4">https://itunes.apple.com/us/app/scalar-the-better-calculator/id380168978?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** Sergey Mikhanov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sergey-mikhanov/id861959898?uo=4>© Sergey Mikhanov</a>
**Supported Devices:** iPhone6, iPodTouchFifthGen, iPadFourthGen, iPhone5, iPhone6Plus, iPhone5s, iPadThirdGen, iPadMini, iPhone5c, iPad2Wifi, iPhone4S, iPadThirdGen4G, iPad23G, iPadMini4G, iPadFourthGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/a4/42/3d/a4423d0f-345e-a8b9-534d-32dc474f1ca5/mzl.bzcaaenh.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8888996/8f92f428-32c5-11e5-987d-41a698fb37d6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8888996/8f92f428-32c5-11e5-987d-41a698fb37d6.png)
https://cloud.githubusercontent.com/assets/2068130/8888996/8f92f428-32c5-11e5-987d-41a698fb37d6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8888997/9e86e624-32c5-11e5-9976-fb2f00eebb17.png
