### ISSUE TITLE
Boximize: Structured note taking, personal database, form builder and organizer!

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5931]
**App Name:** Boximize: Structured note taking, personal database, form builder and organizer!
**Bundle ID:** com.khayalie.personaldatabase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=828889086">828889086</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boximize-structured-note-taking/id828889086?mt=8&uo=4">https://itunes.apple.com/us/app/boximize-structured-note-taking/id828889086?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Mostafa Ashour
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mostafa-ashour/id617382583?uo=4>© Mostafa Ashour</a>
**Supported Devices:** iPadFourthGen4G, iPhone5s, iPadMini4G, iPadThirdGen4G, iPad23G, iPadFourthGen, iPad2Wifi, iPhone4S, iPadThirdGen, iPhone5, iPhone6, iPhone6Plus, iPhone5c, iPhone4, iPodTouchFifthGen, iPadMini
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple3/v4/80/d5/be/80d5be02-615a-124b-b6e1-f5f836eb8243/mzl.rilkdaji.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8575237/ecf1472e-2568-11e5-8f4c-0fc5463a1e78.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8575237/ecf1472e-2568-11e5-8f4c-0fc5463a1e78.png)
https://cloud.githubusercontent.com/assets/10950389/8575237/ecf1472e-2568-11e5-8f4c-0fc5463a1e78.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8575243/f5c035d6-2568-11e5-8f8a-da251f3579e5.png

**Comment by dreamnet** [comment]
@zmathiasz Yeah! :+1:
