### ISSUE TITLE
scan me | PDF Scanner & Optical Character Recognition (OCR), QR Code Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5932]
**App Name:** scan me | PDF Scanner & Optical Character Recognition (OCR), QR Code Reader
**Bundle ID:** me.organice.scan-me2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=925304894">925304894</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scan-me-pdf-scanner-optical/id925304894?mt=8&uo=4">https://itunes.apple.com/us/app/scan-me-pdf-scanner-optical/id925304894?mt=8&uo=4</a>
**App Version:** 1.2.4
**Seller:** organize.me GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/organize.me-gmbh/id757838901?uo=4>© organize.me GmbH</a>
**Supported Devices:** iPhone5s, iPadFourthGen, iPhone5c, iPhone4S, iPadThirdGen, iPhone4, iPadMini4G, iPad23G, iPadThirdGen4G, iPhone6, iPadMini, iPhone5, iPadFourthGen4G, iPad2Wifi, iPodTouchFifthGen, iPhone6Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/5c/f1/b6/5cf1b67b-4d59-8d80-691e-2a1ec8eed7e4/mzl.rfvbukzm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8812842/864132e6-2fcc-11e5-9299-7ec784fdf1ed.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8791922/385eecbe-2f2f-11e5-945a-d56fe4b4fadb.png)

Source: https://cloud.githubusercontent.com/assets/7368317/8791922/385eecbe-2f2f-11e5-945a-d56fe4b4fadb.png

**Comment by dreamnet** [comment]
@Teekzilla Jup, good - do you have a 1024x1024px source file for this?

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8812842/864132e6-2fcc-11e5-9299-7ec784fdf1ed.png)
https://cloud.githubusercontent.com/assets/7368317/8812842/864132e6-2fcc-11e5-9299-7ec784fdf1ed.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8812843/86f8bd8a-2fcc-11e5-956b-c803d586cc6f.png

**Comment by Teekzilla** [comment]
Updated submission with corrected source file!
