### ISSUE TITLE
Siege Hero Wizards

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5933]
**App Name:** Siege Hero Wizards
**Bundle ID:** com.armorgames.sh2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=636486959">636486959</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/siege-hero-wizards/id636486959?mt=8&uo=4">https://itunes.apple.com/us/app/siege-hero-wizards/id636486959?mt=8&uo=4</a>
**App Version:** 1.2.3
**Seller:** Armor Games Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/armor-games-inc/id286413135?uo=4">© Armor Games Inc</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/6f/89/68/6f896868-1efe-5a71-9497-1383864f39cd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20453655/64d7bb5e-ae2c-11e6-9897-b7d2702f60a9.png)

**Comment by LaCh0uine** [comment]
no try for this one :(
please

**Comment by dreamnet** [comment]
@LaCh0uine This is a very hard one - give us some time.

**Comment by dreamnet** [comment]
Progress so far:
https://cloud.githubusercontent.com/assets/2068130/8884491/5dd7dae8-3257-11e5-88cd-3153262ad890.png

**Comment by dreamnet** [comment]
Going on:
https://cloud.githubusercontent.com/assets/2068130/8884678/da3fd97c-3258-11e5-9502-49cb037d6338.png

**Comment by dreamnet** [comment]
Finished:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8885177/b4d77a82-325d-11e5-9ffb-3dde23b96d05.png)
https://cloud.githubusercontent.com/assets/2068130/8885177/b4d77a82-325d-11e5-9ffb-3dde23b96d05.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8885187/c5235488-325d-11e5-9151-a4c0454677b9.png

**Comment by MagnaMike** [comment]
@dreamnet Nicely done. :+1:

**Comment by Trubbel** [comment]
@dreamnet Very nice indeed!

**Comment by LaCh0uine** [comment]
@dreamnet Omg nice work thank you so much

**Comment by dreamnet** [comment]
@MagnaMike @ivanov007 @LaCh0uine Thanks!

**Comment by LaCh0uine** [comment]
@dreamnet icon need update thank you

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20453655/64d7bb5e-ae2c-11e6-9897-b7d2702f60a9.png)
https://cloud.githubusercontent.com/assets/2068130/20453655/64d7bb5e-ae2c-11e6-9897-b7d2702f60a9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20453661/7bf3fd7a-ae2c-11e6-988c-2fc53eab1d4b.png
