### ISSUE TITLE
CalcTape - the Paper Tape Calculator with Notes

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5934]
**App Name:** CalcTape - the Paper Tape Calculator with Notes
**Bundle ID:** de.sfr.ipad.calctape
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525997288">525997288</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calctape-paper-tape-calculator/id525997288?mt=8&uo=4">https://itunes.apple.com/us/app/calctape-paper-tape-calculator/id525997288?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** SFR Software GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sfr-software-gmbh/id299986561?uo=4>© SFR Software GmbH</a>
**Supported Devices:** iPadThirdGen, iPhone5c, iPhone6Plus, iPad2Wifi, iPadFourthGen4G, iPadThirdGen4G, iPhone4S, iPhone4, iPodTouchFifthGen, iPadMini, iPhone5, iPad23G, iPadFourthGen, iPhone5s, iPadMini4G, iPhone6
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/58/1a/b5/581ab568-b5a5-8976-61eb-9180ec729c8c/mzl.kamsxspe.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8607632/a8c43b7e-2694-11e5-9990-b9d8964e5b66.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8607632/a8c43b7e-2694-11e5-9990-b9d8964e5b66.png)
https://cloud.githubusercontent.com/assets/2068130/8607632/a8c43b7e-2694-11e5-9990-b9d8964e5b66.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8607636/b79beb92-2694-11e5-972d-370cc81eda9f.png
