### ISSUE TITLE
YP Yellow Pages Canada

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5935]
**App Name:** YP Yellow Pages Canada
**Bundle ID:** com.ypg.international
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=322964940">322964940</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yp-yellow-pages-canada/id322964940?mt=8&uo=4">https://itunes.apple.com/us/app/yp-yellow-pages-canada/id322964940?mt=8&uo=4</a>
**App Version:** 5.0.2
**Seller:** Yellow Pages Digital & Media Solutions Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/yellow-pages-digital-media/id310063420?uo=4>© Yellow Pages Digital & Media Solutions Limited</a>
**Supported Devices:** iPad23G, iPhone5, iPhone4, iPadThirdGen, iPadFourthGen, iPadMini4G, iPadThirdGen4G, iPhone6Plus, iPhone4S, iPad2Wifi, iPhone6, iPadFourthGen4G, iPadMini, iPodTouchFifthGen, iPhone5s, iPhone5c
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/91/e5/79/91e57996-f696-f0f9-8f88-fe8fe6cd9c8a/mzl.iotpwwiv.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8574954/69be774c-2567-11e5-949d-5214913fbb16.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8574943/575fd46a-2567-11e5-93a7-9788c7ab6421.png)
https://cloud.githubusercontent.com/assets/10950389/8574943/575fd46a-2567-11e5-93a7-9788c7ab6421.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8574951/60761e92-2567-11e5-8555-fcd351c3e595.png

Alternate:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8574954/69be774c-2567-11e5-949d-5214913fbb16.png)
https://cloud.githubusercontent.com/assets/10950389/8574954/69be774c-2567-11e5-949d-5214913fbb16.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8574963/74058a9c-2567-11e5-8b58-f2f35aa6948e.png

**Comment by LaCh0uine** [comment]
I like two version .. But the alternative is more like original and the first one look better ;)

**Comment by dreamnet** [comment]
I take the alternate, because it's more like the original. @zmathiasz :+1:
