### ISSUE TITLE
Koodo Self Serve App

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#5937]
**App Name:** Koodo Self Serve App
**Bundle ID:** com.koodo.selfserveapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=588344930">588344930</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/koodo-self-serve-app/id588344930?mt=8&uo=4">https://itunes.apple.com/us/app/koodo-self-serve-app/id588344930?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Koodo Mobile-Scarborough
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/koodo-mobile/id588344933?uo=4>© Koodo Mobile</a>
**Supported Devices:** iPadMini, iPad2Wifi, iPhone5, iPhone5c, iPhone4S, iPadFourthGen4G, iPhone4, iPhone6Plus, iPadThirdGen, iPad23G, iPhone6, iPodTouchFifthGen, iPadMini4G, iPadFourthGen, iPhone5s, iPadThirdGen4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/41/5e/a5/415ea54c-2643-0100-2562-0dc849077fc7/mzl.cgxtkmmf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8606530/84dc2c9c-268c-11e5-90c4-a4e0430ebb13.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8606530/84dc2c9c-268c-11e5-90c4-a4e0430ebb13.png)
https://cloud.githubusercontent.com/assets/2068130/8606530/84dc2c9c-268c-11e5-90c4-a4e0430ebb13.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8606543/944f226a-268c-11e5-912b-cb4f9d529013.png
