### ISSUE TITLE
CinemaClock

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5944]
**App Name:** CinemaClock
**Bundle ID:** com.cinemaclock.CinemaClock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=588165293">588165293</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/cinemaclock/id588165293?mt=8&uo=4">https://itunes.apple.com/ca/app/cinemaclock/id588165293?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** CinemaClock Canada Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/artist/cinemaclock/id588165296?uo=4>© CinemaClock</a>
**Supported Devices:** iPhone4, iPhone5c, iPadThirdGen4G, iPodTouchThirdGen, iPodTouchFourthGen, iPhone6Plus, iPhone-3GS, iPadMini, iPadThirdGen, iPhone5s, iPadWifi, iPodTouchFifthGen, iPad3G, iPadFourthGen, iPadFourthGen4G, iPhone6, iPad2Wifi, iPadMini4G, iPad23G, iPhone5, iPhone4S
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple/v4/c2/69/e7/c269e7db-0f3e-efc1-ae74-ede56ff884f6/mzl.wizmcbyo.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8606839/e676a886-268e-11e5-812f-d133a88c5c8f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8606839/e676a886-268e-11e5-812f-d133a88c5c8f.png)
https://cloud.githubusercontent.com/assets/2068130/8606839/e676a886-268e-11e5-812f-d133a88c5c8f.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8606849/f59c025c-268e-11e5-8dbc-5ac7cb7c995f.png
