### ISSUE TITLE
FotMob Live Soccer Scores

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5948]
**App Name:** FotMob Live Soccer Scores
**Bundle ID:** com.mobilefootie.fotmobpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=488575683">488575683</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fotmob-live-soccer-scores/id488575683?uo=4">https://apps.apple.com/us/app/fotmob-live-soccer-scores/id488575683?uo=4</a>
**App Version:** 1038.0
**Seller:** NorApps AS
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/norapps-as/id357424099?uo=4">© NorApps AS</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/ed/61/11/ed6111a2-ea8f-d21f-65da-38863d58dad0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400549-b4e69500-9b75-11e9-8832-e6805b12c53f.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8583140/7e2fd298-25cb-11e5-89f4-cd142e97d759.png)
https://cloud.githubusercontent.com/assets/10730122/8583140/7e2fd298-25cb-11e5-89f4-cd142e97d759.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8583136/7abebb4c-25cb-11e5-9495-f58d5d8c91fc.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400549-b4e69500-9b75-11e9-8832-e6805b12c53f.png)
https://user-images.githubusercontent.com/20930745/60400549-b4e69500-9b75-11e9-8832-e6805b12c53f.png

Source:
https://user-images.githubusercontent.com/20930745/60400553-badc7600-9b75-11e9-87a1-1ed88e08d9de.png
