### ISSUE TITLE
DuProprio Mobile

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5955]
**App Name:** DuProprio Mobile
**Bundle ID:** com.duproprio.DuProprioFR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306140559">306140559</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/duproprio-mobile/id306140559?mt=8&uo=4">https://itunes.apple.com/us/app/duproprio-mobile/id306140559?mt=8&uo=4</a>
**App Version:** 2.61
**Seller:** DuProprio.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/duproprio.com/id306136004?uo=4>© DuProprio.com</a>
**Supported Devices:** iPodTouchFourthGen, iPadThirdGen4G, iPhone4, iPhone4S, iPadFourthGen4G, iPadMini4G, iPhone6Plus, iPadMini, iPhone6, iPhone5, iPhone-3GS, iPad23G, iPhone5s, iPodTouchFifthGen, iPadFourthGen, iPad2Wifi, iPadThirdGen, iPhone5c
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/f1/73/33/f17333cb-cb29-e428-3d66-f2f04ce7a726/mzl.bwwllrkx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8599128/5523d472-2624-11e5-8a1a-d62b861ee2d1.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8599128/5523d472-2624-11e5-8a1a-d62b861ee2d1.png)
https://cloud.githubusercontent.com/assets/3090247/8599128/5523d472-2624-11e5-8a1a-d62b861ee2d1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8599129/5558871c-2624-11e5-9df7-f9d9cdd0cc27.png

**Comment by LaCh0uine** [comment]
@ivanov007 👍🏻👍🏻

**Comment by dreamnet** [comment]
@ivanov007 Yes! :+1:
