### ISSUE TITLE
MyRadar Weather Radar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5956]
**App Name:** MyRadar Weather Radar
**Bundle ID:** com.fboweb.MyRadar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=322439990">322439990</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myradar-weather-radar/id322439990?uo=4">https://apps.apple.com/us/app/myradar-weather-radar/id322439990?uo=4</a>
**App Version:** 7.5.1
**Seller:** Aviation Data Systems, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/aviation-data-systems-inc/id294802544?uo=4">© Aviation Data Systems, Inc</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/c4/3c/94/c43c9414-e903-24d9-f5aa-c1d4b6059064/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83335207-5c4ed900-a2ab-11ea-815e-17d5631ae3db.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8896062/1a6953f0-33f0-11e5-8a79-0a4bc2264a9b.png)
https://cloud.githubusercontent.com/assets/2068130/8896062/1a6953f0-33f0-11e5-8a79-0a4bc2264a9b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8896064/29310248-33f0-11e5-84b4-83a62dd689bc.png
Prrrrrrrrrrrrrrrrrrrrrfffffffhhhhhhhhhhh....................

**Comment by MagnaMike** [comment]
@dreamnet I think at this point you should just take it. :laughing:

**Comment by ivanov007** [comment]
yeah, I dont think it can be done any better :+1:

**Comment by dreamnet** [comment]
@MagnaMike @ivanov007 Well, I'm not happy with this, but I think you are right...

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** MyRadar Weather Radar
**Bundle ID:** com.fboweb.MyRadar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=322439990">322439990</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/myradar-weather-radar/id322439990?uo=4">https://apps.apple.com/us/app/myradar-weather-radar/id322439990?uo=4</a>
**App Version:** 7.5.1
**Seller:** Aviation Data Systems, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/aviation-data-systems-inc/id294802544?uo=4">© Aviation Data Systems, Inc</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/c4/3c/94/c43c9414-e903-24d9-f5aa-c1d4b6059064/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83335207-5c4ed900-a2ab-11ea-815e-17d5631ae3db.png)
https://user-images.githubusercontent.com/2068130/83335207-5c4ed900-a2ab-11ea-815e-17d5631ae3db.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83335214-6b358b80-a2ab-11ea-9401-481a64d81b0a.png
