### ISSUE TITLE
MOVIST - Your Personal Movie List

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5957]
**App Name:** MOVIST - Your Personal Movie List
**Bundle ID:** com.linitix.Movist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=840784742">840784742</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/movist-your-personal-movie/id840784742?mt=8&uo=4">https://itunes.apple.com/us/app/movist-your-personal-movie/id840784742?mt=8&uo=4</a>
**App Version:** 1.9.1
**Seller:** LINITIX
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/linitix/id493081066?uo=4>© LINITIX</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen, iPhone6Plus, iPad23G, iPadFourthGen, iPhone6, iPadMini, iPhone5c, iPhone5, iPhone4S, iPadMini4G, iPhone5s, iPadFourthGen4G, iPadThirdGen4G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/69/23/73/692373ac-d8da-d3c9-66e1-79e43083d639/mzl.qjgurzlp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8606441/eb62ff28-268b-11e5-96f2-42a253bdfb4e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8606441/eb62ff28-268b-11e5-96f2-42a253bdfb4e.png)
https://cloud.githubusercontent.com/assets/2068130/8606441/eb62ff28-268b-11e5-96f2-42a253bdfb4e.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8606455/f9656da4-268b-11e5-8cdb-fa82ca48a30d.png
