### ISSUE TITLE
AfterShip Package Tracker

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5958]
**App Name:** AfterShip Package Tracker
**Bundle ID:** com.aftership.AfterShip
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507014023">507014023</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aftership-package-tracker/id507014023?mt=8&uo=4">https://itunes.apple.com/us/app/aftership-package-tracker/id507014023?mt=8&uo=4</a>
**App Version:** 2.0.10
**Seller:** AfterShip Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/aftership-limited/id798551120?uo=4>© AfterShip Limited</a>
**Supported Devices:** iPad23G, iPadThirdGen4G, iPadMini, iPhone6Plus, iPhone5s, iPhone6, iPhone4S, iPadMini4G, iPadFourthGen4G, iPhone4, iPadThirdGen, iPadFourthGen, iPhone5c, iPodTouchFifthGen, iPhone5, iPad2Wifi
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/98/fe/94/98fe94d9-615c-b31d-94fb-c44032c41715/mzl.swpwtdez.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8603455/eaacdd7c-263d-11e5-9580-57a8d85e148b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8603455/eaacdd7c-263d-11e5-9580-57a8d85e148b.png)
https://cloud.githubusercontent.com/assets/3090247/8603455/eaacdd7c-263d-11e5-9580-57a8d85e148b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8603456/eaca09b0-263d-11e5-9f7d-ef464ba179cb.png

**Comment by LaCh0uine** [comment]
Thank you
