### ISSUE TITLE
Swipe Nine Keyboard - Fast Predictive Typing with Autocomplete

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5959]
**App Name:** Swipe Nine Keyboard - Fast Predictive Typing with Autocomplete
**Bundle ID:** com.sixtownshousesharelimited.Swipe-Nine
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=958125769">958125769</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swipe-nine-keyboard-fast-predictive/id958125769?mt=8&uo=4">https://itunes.apple.com/us/app/swipe-nine-keyboard-fast-predictive/id958125769?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** SIXTOWNS HOUSE SHARE LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sixtowns-house-share-ltd/id882565492?uo=4>© SIXTOWNS HOUSE SHARE LTD</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen, iPhone5, iPadFourthGen, iPadThirdGen4G, iPhone5s, iPodTouchFifthGen, iPadFourthGen4G, iPhone6Plus, iPadMini, iPadMini4G, iPhone5c, iPhone6, iPhone4S, iPad23G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/89/fb/b4/89fbb430-443b-5721-b4b3-c57fe231e2ea/mzl.mxdltejz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8607899/8f187cec-2696-11e5-86b5-1c2b793b93b9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8607899/8f187cec-2696-11e5-86b5-1c2b793b93b9.png)
https://cloud.githubusercontent.com/assets/2068130/8607899/8f187cec-2696-11e5-86b5-1c2b793b93b9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8607909/9d2a94b4-2696-11e5-843e-127a5f59ebf0.png
