### ISSUE TITLE
Weather palette for iPhone - Detailed free daily / weekly live forecast

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5960]
**App Name:** Weather palette for iPhone - Detailed free daily / weekly live forecast
**Bundle ID:** com.gamifiedapps.weather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=867311229">867311229</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-palette-for-iphone/id867311229?mt=8&uo=4">https://itunes.apple.com/us/app/weather-palette-for-iphone/id867311229?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** B TO J PTY LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/b-to-j-pty-ltd/id569308231?uo=4>© B TO J PTY LTD</a>
**Supported Devices:** iPodTouchFourthGen, iPadThirdGen, iPodTouchFifthGen, iPad23G, iPadFourthGen4G, iPhone5c, iPhone4, iPad2Wifi, iPadMini, iPhone5, iPhone6Plus, iPhone-3GS, iPhone6, iPhone5s, iPadFourthGen, iPadMini4G, iPhone4S, iPadThirdGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple4/v4/f6/fe/a1/f6fea136-a505-fb09-22ea-02c179548e40/mzl.hbfepblx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8683872/412bde42-2a43-11e5-9a4b-9ef642478762.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8683872/412bde42-2a43-11e5-9a4b-9ef642478762.png)
https://cloud.githubusercontent.com/assets/10950389/8683872/412bde42-2a43-11e5-9a4b-9ef642478762.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8683880/4a62d77c-2a43-11e5-9f5c-bcc06c761be1.png

**Comment by dreamnet** [comment]
@zmathiasz Jup! :+1:
