### ISSUE TITLE
InstaWeb: Web to PDF Converter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5961]
**App Name:** InstaWeb: Web to PDF Converter
**Bundle ID:** com.digiset.instaweb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=581643426">581643426</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instaweb-web-to-pdf-converter/id581643426?mt=8&uo=4">https://itunes.apple.com/us/app/instaweb-web-to-pdf-converter/id581643426?mt=8&uo=4</a>
**App Version:** 4.0.3
**Seller:** DIGISET LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/digiset-llc/id944123342?uo=4">© DIGISET LLC</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/8d/bb/ea/8dbbeae7-1f29-9502-7616-2c395a7c40b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32099117-58302e9a-bb0f-11e7-8a85-162d8f027a91.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8888876/07ad7f6e-32c1-11e5-886d-7dd73d471b7c.png)
https://cloud.githubusercontent.com/assets/2068130/8888876/07ad7f6e-32c1-11e5-886d-7dd73d471b7c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8888878/15e659e8-32c1-11e5-92ce-d7d5267fec7d.png

**Comment by MagnaMike** [comment]
Lol @dreamnet, nice text in the icon. :wink:

**Comment by dreamnet** [comment]
@MagnaMike Ha, you are winning the first price for recognizing it.... :laughing: :trophy:

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** InstaWeb: Web to PDF Converter
**Bundle ID:** com.digiset.instaweb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=581643426">581643426</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instaweb-web-to-pdf-converter/id581643426?mt=8&uo=4">https://itunes.apple.com/us/app/instaweb-web-to-pdf-converter/id581643426?mt=8&uo=4</a>
**App Version:** 4.0.3
**Seller:** DIGISET LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/digiset-llc/id944123342?uo=4">© DIGISET LLC</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/8d/bb/ea/8dbbeae7-1f29-9502-7616-2c395a7c40b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32099117-58302e9a-bb0f-11e7-8a85-162d8f027a91.png)
https://user-images.githubusercontent.com/2068130/32099117-58302e9a-bb0f-11e7-8a85-162d8f027a91.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32099134-6a12c44c-bb0f-11e7-9375-897569d83ec1.png
