### ISSUE TITLE
Agar.io

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5962]
**App Name:** Agar.io
**Bundle ID:** com.miniclip.agar.io
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=995999703">995999703</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/agar.io/id995999703?mt=8&uo=4">https://itunes.apple.com/us/app/agar.io/id995999703?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Miniclip SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/miniclip.com/id337457683?uo=4>© Miniclip.com</a>
**Supported Devices:** iPad23G, iPadMini, iPhone6, iPad2Wifi, iPhone5c, iPhone5s, iPhone-3GS, iPhone6Plus, iPhone4, iPodTouchFourthGen, iPhone4S, iPhone5, iPadMini4G, iPodTouchFifthGen, iPadThirdGen4G, iPadFourthGen4G, iPadThirdGen, iPadFourthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/ce/c9/e5/cec9e5a4-6384-89c7-7e78-d405bd47b795/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8682928/b0855b70-2a3d-11e5-92c1-fab93856eccf.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8682928/b0855b70-2a3d-11e5-92c1-fab93856eccf.png)
https://cloud.githubusercontent.com/assets/10950389/8682928/b0855b70-2a3d-11e5-92c1-fab93856eccf.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8682936/b917bf94-2a3d-11e5-8e21-e0bf3764f870.png

**Comment by Trubbel** [comment]
@zmathiasz Looks good. :+1:
