### ISSUE TITLE
Tradera

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5963]
**App Name:** Tradera
**Bundle ID:** com.tradera.Tradera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427984084">427984084</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tradera/id427984084?mt=8&uo=4">https://itunes.apple.com/us/app/tradera/id427984084?mt=8&uo=4</a>
**App Version:** 2.1.8
**Seller:** eBay Sweden AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ebay-sweden-ab/id427984087?uo=4>© eBay Sweden AB</a>
**Supported Devices:** iPhone5c, iPhone5, iPodTouchFifthGen, iPad2Wifi, iPhone5s, iPad23G, iPadFourthGen4G, iPhone6, iPadThirdGen4G, iPadFourthGen, iPadMini, iPhone4, iPadThirdGen, iPadMini4G, iPhone6Plus, iPhone4S
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/e3/18/e8/e318e833-cf2c-e407-8daa-fec7512b1334/mzl.yzyeotig.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8631582/6cf92848-277a-11e5-983d-0f8a7fd976c7.png)

**Comment by Trubbel** [comment]
The icon has been updated and there were no issues for this application.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8631582/6cf92848-277a-11e5-983d-0f8a7fd976c7.png)
https://cloud.githubusercontent.com/assets/10730122/8631582/6cf92848-277a-11e5-983d-0f8a7fd976c7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8631581/69d1ae6a-277a-11e5-99be-00e4cbe146fb.png

**Comment by ivanov007** [comment]
@Trubbel great, thanks :+1:
