### ISSUE TITLE
Moleskine Timepage – Calendar for iCloud, Google & Exchange

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5965]
**App Name:** Moleskine Timepage – Calendar for iCloud, Google & Exchange
**Bundle ID:** com.moleskine.timeline
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989178902">989178902</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moleskine-timepage-calendar/id989178902?mt=8&uo=4">https://itunes.apple.com/us/app/moleskine-timepage-calendar/id989178902?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Moleskine S.r.l.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/moleskine-srl/id429657258?uo=4>© Moleskine Srl</a>
**Supported Devices:** iPadMini, iPhone5s, iPhone5c, iPad2Wifi, iPhone6Plus, iPadThirdGen4G, iPad23G, iPhone5, iPhone6, iPhone4S, iPodTouchFifthGen, iPadFourthGen, iPadMini4G, iPadThirdGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/63/cc/a0/63cca08b-d4b5-8aca-49cd-c970b1181c01/mzl.xcpxiphv.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8682665/2aadc812-2a3c-11e5-943c-1cbe80dc36dc.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8682665/2aadc812-2a3c-11e5-943c-1cbe80dc36dc.png)
https://cloud.githubusercontent.com/assets/10950389/8682665/2aadc812-2a3c-11e5-943c-1cbe80dc36dc.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8682675/3245ad1a-2a3c-11e5-9dd0-0eed7dbf74e1.png
