### ISSUE TITLE
nShift - Schichtplaner

### ISSUE THREAD

**Issue by kugel-fish** [glasklart/hd#5967]
**App Name:** nShift - Schichtplaner
**Bundle ID:** de.nordsektor.nShift
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=790706326">790706326</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nshift-schichtplaner/id790706326?mt=8&uo=4">https://itunes.apple.com/us/app/nshift-schichtplaner/id790706326?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Frank Frohnert
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/nordsektor/id437529524?uo=4>© nordsektor</a>
**Supported Devices:** iPad23G, iPhone4S, iPadFourthGen, iPadThirdGen4G, iPadMini, iPadMini4G, iPhone5, iPadFourthGen4G, iPhone6, iPhone5c, iPodTouchFifthGen, iPhone5s, iPhone6Plus, iPad2Wifi, iPadThirdGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/8d/53/33/8d5333e5-d7f6-6c2d-55d2-988344eb55e7/mzl.rskndrhc.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8682467/1d825f96-2a3b-11e5-8af2-bf158b057287.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8682467/1d825f96-2a3b-11e5-8af2-bf158b057287.png)
https://cloud.githubusercontent.com/assets/10950389/8682467/1d825f96-2a3b-11e5-8af2-bf158b057287.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8682474/2633cf4e-2a3b-11e5-951a-f371ddeb2816.png
