### ISSUE TITLE
gpSPhone

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#597]
**App Name:** gpSPhone
**Bundle ID:** com.zodttd.gpsphone
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/10394552/6131754/0d5162cc-b103-11e4-8daa-26cfda152b89.png" width="150" height="150" />
**Accepted Artwork:**
![com zodttd gpsphone 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6205279/514ec1ee-b569-11e4-8f83-c32cf19934bd.png)

**Comment by PolarisBeaver** [comment]
There is currently no icon themed for the gpSPhone app, and there are 2 issues for this same app, the other being in #2889

**App Name:** gpSPhone
**Bundle ID:** com.zodttd.gpsphone
**iTunes ID:** none (Cydia app)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/6121671/6dd17a7c-b09c-11e4-9589-81c1bf3d5606.png)
https://cloud.githubusercontent.com/assets/10394552/6121671/6dd17a7c-b09c-11e4-9589-81c1bf3d5606.png

Source File: https://cloud.githubusercontent.com/assets/10394552/6121738/65405580-b09d-11e4-8ade-6c18b259766f.png

**Comment by dreamnet** [comment]
@PolarisBeaver Do you have the origial artwork?

**Comment by PolarisBeaver** [comment]
This is the original icon
![appicon76x76 2x ipad](https://cloud.githubusercontent.com/assets/10394552/6131754/0d5162cc-b103-11e4-8daa-26cfda152b89.png)

**Comment by MagnaMike** [comment]
Alright I added the icon and fulfilled icon to the request.

**Comment by kieman** [comment]
i have a problem with the icon

**Comment by PolarisBeaver** [comment]
Weird... I've done nothing special with this icon compared to all the other ones I've submitted (more than 20) Can you check the Accepted Artwork preview in the first post at the top? Also please give us a screenshot of your homescreen with the problematic icon

**Comment by kieman** [comment]
look at these, all the icons on a white layer look like this

http://s3.amazonaws.com/awesome_screenshot/7413596?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1424035306&Signature=cRXdppru%2BCfw90k4ifT01z6ZaCU%3D

but these icon look like these, lie a little shaddow over there

http://s3.amazonaws.com/awesome_screenshot/7413592?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1424035277&Signature=dJOC34cQiNtYP%2B%2B2gck6tLkO%2Fl0%3D


and here on my phone
[url=http://abload.de/image.php?img=foto15.02.152213556ko6c.png][img]http://abload.de/thumb/foto15.02.152213556ko6c.png[/img][/url]

**Comment by dreamnet** [comment]
@PolarisBeaver Maybe you have applied the Glasklart-effects twice?
Another Try:
![com zodttd gpsphone 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6205279/514ec1ee-b569-11e4-8f83-c32cf19934bd.png)
https://cloud.githubusercontent.com/assets/2068130/6205279/514ec1ee-b569-11e4-8f83-c32cf19934bd.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6205285/9e32e86e-b569-11e4-8c5a-98fea3d0e64c.png

**Comment by MagnaMike** [comment]
@dreamnet I think that must have been it. :+1:

**Comment by kieman** [comment]
Beautiful! Thats it :)

THX

**Comment by dreamnet** [comment]
The icon in the master is correct. No further action needed.
