### ISSUE TITLE
Huuto.net

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#5970]
**App Name:** Huuto.net
**Bundle ID:** fi.sanoma.huutonet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=990172023">990172023</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/huuto-net/id990172023?uo=4">https://apps.apple.com/us/app/huuto-net/id990172023?uo=4</a>
**App Version:** 1.6.1
**Seller:** Sanoma Media Finland
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sanoma-media-finland/id368549040?uo=4">© Sanoma Media Finland</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/30/3f/e4/303fe4ee-2c11-0d5c-1a72-6e2ddc7b5714/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772632-abbb7200-a0f9-11e9-8b73-aa2eebd97998.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8685718/e2bfaa76-2a80-11e5-9f06-18a5943f59f1.png)
https://cloud.githubusercontent.com/assets/2068130/8685718/e2bfaa76-2a80-11e5-9f06-18a5943f59f1.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8685724/f06c904e-2a80-11e5-9402-786525f72ba0.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772632-abbb7200-a0f9-11e9-8b73-aa2eebd97998.png)
https://user-images.githubusercontent.com/2068130/60772632-abbb7200-a0f9-11e9-8b73-aa2eebd97998.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60772637-bb3abb00-a0f9-11e9-9a75-88aec6916d5e.png
