### ISSUE TITLE
MyTransLink

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#5973]
**App Name:** MyTransLink
**Bundle ID:** au.com.translink.my
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=927289966">927289966</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mytranslink/id927289966?mt=8&uo=4">https://itunes.apple.com/us/app/mytranslink/id927289966?mt=8&uo=4</a>
**App Version:** 1.0.519
**Seller:** Department of Transport and Main Roads
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/department-transport-main/id919723337?uo=4>© Department of Transport and Main Roads</a>
**Supported Devices:** iPad2Wifi, iPhone5s, iPhone5c, iPhone5, iPadFourthGen, iPadMini, iPodTouchFifthGen, iPad23G, iPadFourthGen4G, iPadMini4G, iPadThirdGen, iPhone4, iPhone6, iPhone6Plus, iPhone4S, iPadThirdGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple5/v4/30/41/f5/3041f5ae-af33-7a88-22bb-85b1bf651f73/mzl.sxzsfkqx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8736432/ae1f5c78-2c18-11e5-853e-86460f0d9f00.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8736432/ae1f5c78-2c18-11e5-853e-86460f0d9f00.png)
https://cloud.githubusercontent.com/assets/2068130/8736432/ae1f5c78-2c18-11e5-853e-86460f0d9f00.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8736438/bc43f37c-2c18-11e5-8189-52a89b619b02.png
