### ISSUE TITLE
Yatzy Ultimate

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#5974]
**App Name:** Yatzy Ultimate
**Bundle ID:** com.seavus.gaming.Yatzy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=468638702">468638702</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yatzy-ultimate/id468638702?mt=8&uo=4">https://itunes.apple.com/us/app/yatzy-ultimate/id468638702?mt=8&uo=4</a>
**App Version:** 7.7.2
**Seller:** SEAVUS DOOEL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/seavus-dooel/id418295935?uo=4>© Seavus DOOEL</a>
**Supported Devices:** iPhone6Plus, iPadFourthGen, iPadMini4G, iPadThirdGen4G, iPhone6, iPhone4, iPadMini, iPad2Wifi, iPodTouchFifthGen, iPhone5s, iPhone4S, iPadThirdGen, iPhone5, iPhone5c, iPhone-3GS, iPad23G, iPadFourthGen4G, iPodTouchFourthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/f8/cc/18/f8cc18e7-a331-342c-d412-b0c82632f243/mzl.ylqyandw.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8880248/8e0ba1ce-3237-11e5-82e2-f3229aae8866.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8880248/8e0ba1ce-3237-11e5-82e2-f3229aae8866.png)
https://cloud.githubusercontent.com/assets/2068130/8880248/8e0ba1ce-3237-11e5-82e2-f3229aae8866.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8880263/9d0e8894-3237-11e5-8246-3bb0eb336909.png

**Comment by Trubbel** [comment]
@dreamnet Nice!
