### ISSUE TITLE
Garden Plate - healthy vegetarian & gluten free diet recipes

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5975]
**App Name:** Garden Plate - healthy vegetarian & gluten free diet recipes
**Bundle ID:** burleigh-labs.Garden-Plate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=757712938">757712938</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/garden-plate-healthy-vegetarian/id757712938?mt=8&uo=4">https://itunes.apple.com/us/app/garden-plate-healthy-vegetarian/id757712938?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** Burleigh Labs Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/burleigh-labs-pty-ltd/id736545477?uo=4>© Burleigh Labs Pty Ltd</a>
**Supported Devices:** iPad23G, iPodTouchFifthGen, iPadThirdGen, iPadFourthGen4G, iPhone4S, iPhone5s, iPhone6, iPad2Wifi, iPhone5c, iPhone4, iPhone6Plus, iPadMini4G, iPadMini, iPadThirdGen4G, iPadFourthGen, iPhone5
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/0e/a0/1a/0ea01a3c-b2c9-b581-5333-f3ee24fca99b/mzl.mpzqzclm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8705013/11ddcb98-2b27-11e5-8eaa-133fe27b493d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8705013/11ddcb98-2b27-11e5-8eaa-133fe27b493d.png)
https://cloud.githubusercontent.com/assets/10730122/8705013/11ddcb98-2b27-11e5-8eaa-133fe27b493d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8705010/0cc6bc96-2b27-11e5-8cd1-3a598b60fbbe.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
