### ISSUE TITLE
Convertizo 2 - Convert Units and Currency in Style - Imperial & Metric - Angle Area Currency Data Energy Flow Length Power Pressure Speed Temperature Time Volume & Weight

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5976]
**App Name:** Convertizo 2 - Convert Units and Currency in Style - Imperial & Metric - Angle Area Currency Data Energy Flow Length Power Pressure Speed Temperature Time Volume & Weight
**Bundle ID:** com.perfectdimension.convertizo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=792319884">792319884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/convertizo-2-convert-units/id792319884?mt=8&uo=4">https://itunes.apple.com/us/app/convertizo-2-convert-units/id792319884?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Paul Davis
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/perfect-dimension/id448146469?uo=4>© Perfect Dimension</a>
**Supported Devices:** iPadThirdGen4G, iPadFourthGen4G, iPadMini4G, iPadFourthGen, iPad2Wifi, iPodTouchFifthGen, iPhone6, iPhone5, iPhone6Plus, iPhone5s, iPhone4S, iPhone5c, iPadThirdGen, iPhone4, iPadMini, iPad23G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/b9/d9/db/b9d9db28-ad9a-053b-4a65-a061720e37eb/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8711827/bc9fe84e-2b55-11e5-9c28-5d06725f0b92.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8711827/bc9fe84e-2b55-11e5-9c28-5d06725f0b92.png)
https://cloud.githubusercontent.com/assets/10730122/8711827/bc9fe84e-2b55-11e5-9c28-5d06725f0b92.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8711825/b8da7c4c-2b55-11e5-82ff-74f5084cb352.png

**Comment by LaCh0uine** [comment]
@Trubbel 👍🏻
