### ISSUE TITLE
Retrica

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5977]
**App Name:** Retrica
**Bundle ID:** com.bootstlab.retro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=577423493">577423493</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/retrica/id577423493?mt=8&uo=4">https://itunes.apple.com/us/app/retrica/id577423493?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Venticake Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/venticake-inc./id958446752?uo=4>© Venticake Inc.</a>
**Supported Devices:** iPadMini4G, iPhone5s, iPhone4, iPhone4S, iPhone5c, iPadFourthGen, iPadThirdGen, iPadMini, iPhone6Plus, iPodTouchFourthGen, iPhone5, iPodTouchFifthGen, iPhone6, iPadFourthGen4G, iPad23G, iPadThirdGen4G, iPad2Wifi
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/3a/4c/b9/3a4cb9f9-3e48-6b69-a355-e6ffad523154/mzl.cwkefpka.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8888928/30c1d254-32c3-11e5-8ce9-d6eef2a17020.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8888928/30c1d254-32c3-11e5-8ce9-d6eef2a17020.png)
https://cloud.githubusercontent.com/assets/2068130/8888928/30c1d254-32c3-11e5-8ce9-d6eef2a17020.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8888932/3f61535c-32c3-11e5-9dd6-e3c57e0df9bb.png

**Comment by LaCh0uine** [comment]
@dreamnet thank you :)
