### ISSUE TITLE
InFrame Grid

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5978]
**App Name:** InFrame Grid
**Bundle ID:** kr.co.makea.InFrameGrid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=650713223">650713223</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inframe-grid/id650713223?mt=8&uo=4">https://itunes.apple.com/us/app/inframe-grid/id650713223?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** MAKE A
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/make-a/id457885741?uo=4>© MAKE A</a>
**Supported Devices:** iPhone4S, iPhone6Plus, iPadWifi, iPadMini4G, iPad3G, iPadFourthGen, iPodTouchFourthGen, iPhone5s, iPodTouchThirdGen, iPadThirdGen4G, iPadMini, iPhone4, iPhone5c, iPadFourthGen4G, iPhone6, iPhone-3GS, iPad2Wifi, iPadThirdGen, iPhone5, iPodTouchFifthGen, iPad23G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple4/v4/50/8e/da/508eda4c-ca86-89c4-54c8-58dbd29ef585/mzl.jadipwop.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8736288/573d55fa-2c17-11e5-8638-8412774d8460.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8736288/573d55fa-2c17-11e5-8638-8412774d8460.png)
https://cloud.githubusercontent.com/assets/2068130/8736288/573d55fa-2c17-11e5-8638-8412774d8460.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8736297/64a927be-2c17-11e5-8d6a-65984d1f14a3.png
