### ISSUE TITLE
Minuum - The Little Keyboard for Big Fingers: Now with Smart Emoji

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5979]
**App Name:** Minuum - The Little Keyboard for Big Fingers: Now with Smart Emoji
**Bundle ID:** com.whirlscape.Minuum
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914968934">914968934</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minuum-little-keyboard-for/id914968934?mt=8&uo=4">https://itunes.apple.com/us/app/minuum-little-keyboard-for/id914968934?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Whirlscape Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/minuum/id914968937?uo=4>© Minuum</a>
**Supported Devices:** iPhone5c, iPad2Wifi, iPadMini, iPadFourthGen4G, iPadThirdGen4G, iPad23G, iPodTouchFifthGen, iPhone5, iPadMini4G, iPhone6, iPadFourthGen, iPhone5s, iPhone4S, iPadThirdGen, iPhone6Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/78/eb/94/78eb9457-eb69-347a-4dc5-5cdb08509654/mzl.chmptcnx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8711907/93d42618-2b56-11e5-870c-2c083abb9e14.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8711907/93d42618-2b56-11e5-870c-2c083abb9e14.png)
https://cloud.githubusercontent.com/assets/10730122/8711907/93d42618-2b56-11e5-870c-2c083abb9e14.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8711906/902df52a-2b56-11e5-8170-a141b2ce3c89.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8711929/a91a188e-2b56-11e5-95a8-577fc3ee4107.png)
https://cloud.githubusercontent.com/assets/10730122/8711929/a91a188e-2b56-11e5-95a8-577fc3ee4107.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8711922/a352925a-2b56-11e5-87e6-7f187fcd7f8e.png

**Comment by LaCh0uine** [comment]
@Trubbel #1 👍🏻
