### ISSUE TITLE
Truecaller: Number Search & Spam Identification

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#598]
**App Name:** Truecaller: Number Search & Spam Identification
**Bundle ID:** com.truesoftware.TrueCallerOther
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448142450">448142450</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/truecaller-number-search-spam/id448142450?mt=8&uo=4">https://itunes.apple.com/us/app/truecaller-number-search-spam/id448142450?mt=8&uo=4</a>
**App Version:** 7.0
**Seller:** True Software Scandinavia AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/true-software-scandinavia-ab/id336142200?uo=4>© True Software Scandinavia AB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/f7/71/02/f771021a-3bb3-423d-203f-d38aad40cbad/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268704/c9eb8914-5632-11e6-9e99-b7c3eb555341.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Truecaller: Number Search & Spam Identification
**Bundle ID:** com.truesoftware.TrueCallerOther
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448142450">448142450</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/truecaller-number-search-spam/id448142450?mt=8&uo=4">https://itunes.apple.com/us/app/truecaller-number-search-spam/id448142450?mt=8&uo=4</a>
**App Version:** 7.0
**Seller:** True Software Scandinavia AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/true-software-scandinavia-ab/id336142200?uo=4>© True Software Scandinavia AB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/f7/71/02/f771021a-3bb3-423d-203f-d38aad40cbad/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268704/c9eb8914-5632-11e6-9e99-b7c3eb555341.png)
https://cloud.githubusercontent.com/assets/2068130/17268704/c9eb8914-5632-11e6-9e99-b7c3eb555341.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268708/d8f8e05a-5632-11e6-8d47-b3770b2ee9f9.png
