### ISSUE TITLE
ALIVE Movie Maker

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5982]
**App Name:** ALIVE Movie Maker
**Bundle ID:** com.alive-story.ios.ALIVE
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=940018751">940018751</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/alive-movie-maker/id940018751?uo=4">https://apps.apple.com/us/app/alive-movie-maker/id940018751?uo=4</a>
**App Version:** 5.5.5
**Seller:** Maverick Co., Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/alive-inc/id940018750?uo=4">© ALIVE, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/1c/01/5e/1c015e49-0656-50b6-e742-99a4252d1e0b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979396-b5b47f80-95e7-11e9-81c8-4a067d93d7fa.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8736371/3f46dc2c-2c18-11e5-9074-99d85aca6765.png)
https://cloud.githubusercontent.com/assets/2068130/8736371/3f46dc2c-2c18-11e5-9074-99d85aca6765.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8736378/4e81c7b0-2c18-11e5-9984-3b771ddabb51.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979396-b5b47f80-95e7-11e9-81c8-4a067d93d7fa.png)
https://user-images.githubusercontent.com/2068130/59979396-b5b47f80-95e7-11e9-81c8-4a067d93d7fa.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979407-c8c74f80-95e7-11e9-9d78-ac92892fe864.png
