### ISSUE TITLE
Star Wars

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5983]
**App Name:** Star Wars
**Bundle ID:** com.disney.starwarshub
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=960108075">960108075</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/star-wars/id960108075?mt=8&uo=4">https://itunes.apple.com/us/app/star-wars/id960108075?mt=8&uo=4</a>
**App Version:** 1.01
**Seller:** Disney Electronic Content, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/disney/id284888248?mt=8&uo=4>© Disney</a>
**Supported Devices:** iPhone4S, iPadMini4G, iPhone4, iPad23G, iPhone5s, iPadFourthGen, iPadThirdGen, iPodTouchFifthGen, iPhone6, iPhone5, iPadThirdGen4G, iPad2Wifi, iPadFourthGen4G, iPhone5c, iPhone6Plus, iPadMini
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/d7/cc/90/d7cc9081-382a-464b-cb44-3ea27c2e779d/mzl.hwgtwoam.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8736483/1d2c48b0-2c19-11e5-9fdf-142f1400445d.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8714685/ec25f14a-2b45-11e5-9bab-fa61dd9c3f00.png)
https://cloud.githubusercontent.com/assets/10950389/8714685/ec25f14a-2b45-11e5-9bab-fa61dd9c3f00.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8714690/f47f51a6-2b45-11e5-8c63-aa0151f08025.png

**Comment by dreamnet** [comment]
@zmathiasz Full size?

**Comment by zmathiasz** [comment]
Yeah, I'll have another one attached latter today.  :smile:

**Comment by dreamnet** [comment]
@zmathiasz Did it:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8736483/1d2c48b0-2c19-11e5-9fdf-142f1400445d.png)
https://cloud.githubusercontent.com/assets/2068130/8736483/1d2c48b0-2c19-11e5-9fdf-142f1400445d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8736487/2a9a08d4-2c19-11e5-97c7-a280be968470.png
