### ISSUE TITLE
IKEA Store

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5996]
**App Name:** IKEA Store
**Bundle ID:** com.ikea.store
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=976577934">976577934</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ikea-store/id976577934?mt=8&uo=4">https://itunes.apple.com/us/app/ikea-store/id976577934?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** IKEA IT AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ikea/id508738029?uo=4>© IKEA</a>
**Supported Devices:** iPad23G, iPadFourthGen4G, iPadThirdGen4G, iPhone4, iPhone5, iPhone5s, iPad2Wifi, iPhone6Plus, iPadMini, iPadThirdGen, iPhone5c, iPadMini4G, iPodTouchFifthGen, iPadFourthGen, iPhone6, iPhone4S
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/d3/23/90/d3239043-445f-d3f7-2f2b-0d1b1682a0a7/mzl.rzomgkxn.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8736197/ce415648-2c16-11e5-883b-0fbe6829acc9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8736197/ce415648-2c16-11e5-883b-0fbe6829acc9.png)
https://cloud.githubusercontent.com/assets/2068130/8736197/ce415648-2c16-11e5-883b-0fbe6829acc9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8736211/dc3152a8-2c16-11e5-96cf-22dbd6b8eaa0.png

**Comment by LaCh0uine** [comment]
Without lines? Ok ;)

**Comment by Trubbel** [comment]
@LaCh0uine That's just a preview, if  you click on the link under the image, you will see how the icon looks like.

**Comment by dreamnet** [comment]
I think @LaCh0uine means the nearly invisible lines in the background of the original icon - I don't do them.

**Comment by Trubbel** [comment]
@dreamnet Oh I see, yeah, I'm pretty sure it wouldn't look good at all if they were included.

**Comment by LaCh0uine** [comment]
Ok no problem
