### ISSUE TITLE
MeisterTask (task management)

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5997]
**App Name:** MeisterTask (task management)
**Bundle ID:** com.meisterlabs.meistertask
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=918099883">918099883</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/meistertask-task-management/id918099883?mt=8&uo=4">https://itunes.apple.com/us/app/meistertask-task-management/id918099883?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** MeisterLabs
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/meisterlabs/id291226778?uo=4>© MeisterLabs</a>
**Supported Devices:** iPhone4S, iPadThirdGen4G, iPodTouchSixthGen, iPadThirdGen, iPadMini, iPhone6Plus, iPadFourthGen4G, iPhone5c, iPhone5s, iPhone5, iPhone6, iPad2Wifi, iPad23G, iPadMini4G, iPodTouchFifthGen, iPadFourthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/e8/d8/5d/e8d85db4-768f-63c8-4c83-19677376dc29/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8812150/73682700-2fc8-11e5-990c-4271e093b08d.png)

**Comment by Teekzilla** [comment]
Might be too simple?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8812150/73682700-2fc8-11e5-990c-4271e093b08d.png)
https://cloud.githubusercontent.com/assets/7368317/8812150/73682700-2fc8-11e5-990c-4271e093b08d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8812151/7434cf80-2fc8-11e5-96da-7580ba9b0a9a.png

**Comment by Teekzilla** [comment]
Updated submission with corrected source file!
