### ISSUE TITLE
SongPop 2

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5998]
**App Name:** SongPop 2
**Bundle ID:** com.freshplanet.games.SongPop2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=975364678">975364678</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/songpop-2/id975364678?mt=8&uo=4">https://itunes.apple.com/us/app/songpop-2/id975364678?mt=8&uo=4</a>
**App Version:** 2.01.16
**Seller:** FreshPlanet, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/freshplanet-inc./id364257025?uo=4>© FreshPlanet Inc.</a>
**Supported Devices:** iPhone4, iPodTouchFifthGen, iPhone6, iPadMini4G, iPad2Wifi, iPadThirdGen4G, iPhone5, iPhone4S, iPodTouchSixthGen, iPadThirdGen, iPhone5s, iPadFourthGen4G, iPad23G, iPadFourthGen, iPhone5c, iPadMini, iPhone6Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/17/bf/6d/17bf6d62-f552-05c8-9087-e766f429b75b/mzl.qcfwtplm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8836398/a9d38b6a-308e-11e5-88e1-40481ecc26fc.png)

**Comment by Teekzilla** [comment]
@LaCh0uine Only 2 more left... :D

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8809619/d04a166a-2fb7-11e5-9473-770d647dd5cf.png)
https://cloud.githubusercontent.com/assets/7368317/8809619/d04a166a-2fb7-11e5-9473-770d647dd5cf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8809620/d37b2d2e-2fb7-11e5-8428-439d6c90bd8b.png

**Comment by LaCh0uine** [comment]
Nice thank you

**Comment by Teekzilla** [comment]
Updated submission with corrected source file!

**Comment by ivanov007** [comment]
@Teekzilla do you think you can make the likes a little bolder? it'll be hard to see on retina display

**Comment by Teekzilla** [comment]
Yeah as in the spaces between correct? Give me a bit trying to make the Frameographed icon for myself 😁

**Comment by Teekzilla** [comment]
@ivanov007 How's that? I made it a little bolder? More or is that good?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8836117/af0816d4-308c-11e5-9ee5-7ada876e0dee.png)
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8836119/afcc297a-308c-11e5-9b91-ec74ad2726a5.png

**Comment by Teekzilla** [comment]
Wait... I think the Layer Style requires more space... Let me redo it once more.

**Comment by Teekzilla** [comment]
@ivanov007 This?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8836398/a9d38b6a-308e-11e5-88e1-40481ecc26fc.png)
https://cloud.githubusercontent.com/assets/7368317/8836398/a9d38b6a-308e-11e5-88e1-40481ecc26fc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8836399/aa3d04aa-308e-11e5-8e48-f56b3fbbf180.png

**Comment by ivanov007** [comment]
@Teekzilla yup looks good :+1:
