### ISSUE TITLE
SkyView® - Explore the Universe

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5999]
**App Name:** SkyView® - Explore the Universe
**Bundle ID:** com.t11.celeste
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404990064">404990064</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skyview-explore-the-universe/id404990064?mt=8&uo=4">https://itunes.apple.com/us/app/skyview-explore-the-universe/id404990064?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Terminal Eleven LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/terminal-eleven-llc/id378238417?uo=4>© Terminal Eleven LLC</a>
**Supported Devices:** iPhone5s, iPad2Wifi, iPhone5, iPadMini, iPodTouchFifthGen, iPhone6, iPhone4, iPhone5c, iPadFourthGen4G, iPadThirdGen, iPadFourthGen, iPodTouchSixthGen, iPhone6Plus, iPadMini4G, iPad23G, iPhone4S, iPadThirdGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/c8/ef/8c/c8ef8cd4-07a8-dbea-5ef7-e7a8a01e1f97/mzl.ruanpluk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8891014/41a0a60a-3317-11e5-8772-a11ac502fa24.png)

**Comment by dreamnet** [comment]
Not really happy with this, but I don't know a way to make it better:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8889225/93aada10-32d1-11e5-91f1-e998247e2ec6.png)
https://cloud.githubusercontent.com/assets/2068130/8889225/93aada10-32d1-11e5-91f1-e998247e2ec6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8889228/a206e900-32d1-11e5-8f60-743326dfbdc8.png

**Comment by MagnaMike** [comment]
@dreamnet  What does it look like when inverted?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8890880/9ea5fa86-3311-11e5-9c86-e49e2a357c88.png)
https://cloud.githubusercontent.com/assets/2068130/8890880/9ea5fa86-3311-11e5-9c86-e49e2a357c88.png

---
https://cloud.githubusercontent.com/assets/2068130/8890881/bf8b642a-3311-11e5-9a25-9f819cf1b2bd.png

**Comment by MagnaMike** [comment]
@dreamnet I think I like it better - but up to you.

**Comment by Gwai** [comment]
i prefer the inverted too

**Comment by dreamnet** [comment]
I give it another try... wait a view minutes.

**Comment by dreamnet** [comment]
My last try:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8891014/41a0a60a-3317-11e5-8772-a11ac502fa24.png)
https://cloud.githubusercontent.com/assets/2068130/8891014/41a0a60a-3317-11e5-8772-a11ac502fa24.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8891017/5497e188-3317-11e5-817a-5e50168a7a3f.png
@Gwai You decide! :confused:

**Comment by Trubbel** [comment]
@dreamnet I think you nailed it, but that's just me. :smiley:

**Comment by Gwai** [comment]
Wow, I think the last is the best.... Nice work

**Comment by MagnaMike** [comment]
Took :three:, was my favourite too.
