### ISSUE TITLE
Solar : Weather

### ISSUE THREAD

**Issue by braindeadrebel** [glasklart/hd#6]
**App Name:** Solar : Weather
**Bundle ID:** com.solar.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542875991">542875991</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/solar-weather/id542875991?mt=8&uo=4">https://itunes.apple.com/us/app/solar-weather/id542875991?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Hollr, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hollr-inc./id473567295?uo=4>© Hollr, Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/4f/ed/87/4fed872b-0f50-82ff-94e3-cb1ff5af929e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625306/603a90e8-9915-11e6-87f6-c1b1fd375a42.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19625306/603a90e8-9915-11e6-87f6-c1b1fd375a42.png)
https://cloud.githubusercontent.com/assets/20930745/19625306/603a90e8-9915-11e6-87f6-c1b1fd375a42.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19625312/7bff458a-9915-11e6-9351-d4e2978d8220.png
