### ISSUE TITLE
Temple Run

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#60]
**App Name:** Temple Run
**Bundle ID:** com.imangi.templerun
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=420009108">420009108</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/temple-run/id420009108?mt=8&uo=4">https://itunes.apple.com/us/app/temple-run/id420009108?mt=8&uo=4</a>
**App Version:** 1.6.1
**Seller:** Imangi Studios, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/imangi-studios-llc/id284899742?uo=4>© Imangi Studios, LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/b5/14/60/b51460b7-bf31-89d9-812d-bfc85853857d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18908851/91cab7e4-8571-11e6-9955-0b9eb0bcb2ef.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18870799/ad726ed4-84b2-11e6-9507-b36c0c200ba0.png)
https://cloud.githubusercontent.com/assets/20930745/18870799/ad726ed4-84b2-11e6-9507-b36c0c200ba0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18870813/bc80f1fc-84b2-11e6-9015-8b5cc8463beb.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18870914/37a46d64-84b3-11e6-9393-6a1fcf6efaeb.png)
https://cloud.githubusercontent.com/assets/20930745/18870914/37a46d64-84b3-11e6-9393-6a1fcf6efaeb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18870924/47258958-84b3-11e6-8bd7-630ed5169eaa.png
