### ISSUE TITLE
Ski Safari

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#600]
**App Name:** Ski Safari
**Bundle ID:** com.DefiantDev.SkiSafari
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=503092422">503092422</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ski-safari/id503092422?mt=8&uo=4">https://itunes.apple.com/us/app/ski-safari/id503092422?mt=8&uo=4</a>
**App Version:** 1.5.4
**Seller:** Defiant Development Pty.Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/defiant-development/id494163311?uo=4>© Defiant Development</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/b2/9f/63/b29f630e-8ab6-2742-97d8-53d52fef6e4b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19102930/084ab402-8ad4-11e6-94c1-42e244be2a10.png)

**Comment by haen7** [comment]
this needs to be updated

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19090485/04cdd14c-8a7f-11e6-9ce6-39e66043a3f0.png)
https://cloud.githubusercontent.com/assets/20930745/19090485/04cdd14c-8a7f-11e6-9ce6-39e66043a3f0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19090498/1339a2e2-8a7f-11e6-844a-b7702948ab84.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Great work, but I think we should let out the snow at the bottom.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19102930/084ab402-8ad4-11e6-94c1-42e244be2a10.png)
https://cloud.githubusercontent.com/assets/2068130/19102930/084ab402-8ad4-11e6-94c1-42e244be2a10.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19102936/1437383a-8ad4-11e6-96fb-6ee0a4e2bc64.png
