### ISSUE TITLE
WarnWetter

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#6001]
**App Name:** WarnWetter
**Bundle ID:** de.dwd.warnapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=986420993">986420993</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/warnwetter/id986420993?mt=8&uo=4">https://itunes.apple.com/us/app/warnwetter/id986420993?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Deutscher Wetterdienst
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/deutscher-wetterdienst/id633263813?uo=4>© Deutscher Wetterdienst</a>
**Supported Devices:** iPodTouchSixthGen, iPhone5, iPhone-3GS, iPadThirdGen, iPhone5s, iPhone6, iPodTouchFourthGen, iPad23G, iPadMini4G, iPhone5c, iPad2Wifi, iPhone4S, iPadFourthGen, iPadMini, iPhone6Plus, iPadThirdGen4G, iPadFourthGen4G, iPhone4, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/57/54/5d/57545d2c-4703-693c-11a0-bb310906410a/mzl.ckeqorez.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8750284/e13df234-2ca6-11e5-9367-636b2569232a.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8750284/e13df234-2ca6-11e5-9367-636b2569232a.png)
https://cloud.githubusercontent.com/assets/10730122/8750284/e13df234-2ca6-11e5-9367-636b2569232a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8750279/dcf614ae-2ca6-11e5-8d7d-b3d99ceff1f8.png
