### ISSUE TITLE
radioplayer

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#6002]
**App Name:** radioplayer
**Bundle ID:** de.radioplayer.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=934356782">934356782</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/radioplayer/id934356782?mt=8&uo=4">https://itunes.apple.com/de/app/radioplayer/id934356782?mt=8&uo=4</a>
**App Version:** 3.3.2
**Seller:** Radioplayer Deutschland GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/radioplayer-deutschland-gmbh/id934356781?uo=4>© Radioplayer Deutschland GmbH</a>
**Supported Devices:** iPad2Wifi, iPadMini4G, iPhone5c, iPhone4, iPhone6Plus, iPadFourthGen4G, iPadFourthGen, iPadThirdGen4G, iPhone5s, iPadThirdGen, iPodTouchFifthGen, iPad23G, iPhone5, iPhone6, iPhone4S, iPadMini, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/7a/d9/29/7ad929fe-8e2b-8e2e-d806-a4d516628e19/mzl.ziuobjlw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8750166/1989f062-2ca6-11e5-9ef5-997146328ac4.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8750166/1989f062-2ca6-11e5-9ef5-997146328ac4.png)
https://cloud.githubusercontent.com/assets/10730122/8750166/1989f062-2ca6-11e5-9ef5-997146328ac4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8750163/167eef9e-2ca6-11e5-9cd8-0d2650e56b14.png
