### ISSUE TITLE
Mission Impossible: Rogue Nation

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6003]
**App Name:** Mission Impossible: Rogue Nation
**Bundle ID:** com.glu.mi5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=974110790">974110790</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mission-impossible-rogue-nation/id974110790?mt=8&uo=4">https://itunes.apple.com/us/app/mission-impossible-rogue-nation/id974110790?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Glu Games Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/glu-games-inc./id284419051?uo=4>© Glu Games Inc.</a>
**Supported Devices:** iPhone6, iPhone5, iPadMini, iPad23G, iPhone4S, iPadFourthGen4G, iPad2Wifi, iPadMini4G, iPodTouchFourthGen, iPodTouchFifthGen, iPhone5s, iPodTouchSixthGen, iPhone4, iPadFourthGen, iPhone6Plus, iPadThirdGen, iPhone5c, iPadThirdGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/47/b2/80/47b28099-010a-9c93-1cfa-dc2c77999c09/mzl.udyljzmp.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8811518/7872911c-2fc4-11e5-896a-0964373dd27f.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8811518/7872911c-2fc4-11e5-896a-0964373dd27f.png)
https://cloud.githubusercontent.com/assets/7368317/8811518/7872911c-2fc4-11e5-896a-0964373dd27f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8811519/79289b92-2fc4-11e5-96f3-49c95be89b87.png

**Comment by Teekzilla** [comment]
Updated submission with corrected source file!
