### ISSUE TITLE
BURGER KING® App

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6008]
**App Name:** BURGER KING® App
**Bundle ID:** com.emn8.mobilem8.native.bkrewards
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=638323895">638323895</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/burger-king-app/id638323895?mt=8&uo=4">https://itunes.apple.com/us/app/burger-king-app/id638323895?mt=8&uo=4</a>
**App Version:** 2.81
**Seller:** EMN8 Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/emn8-inc/id638323898?uo=4>© EMN8 Inc</a>
**Supported Devices:** iPodTouchThirdGen, iPadMini4G, iPodTouchFifthGen, iPad23G, iPhone5, iPad2Wifi, iPhone5c, iPhone4S, iPodTouchFourthGen, iPadFourthGen, iPadFourthGen4G, iPadWifi, iPadThirdGen4G, iPhone6, iPadThirdGen, iPhone5s, iPad3G, iPhone-3GS, iPadMini, iPhone4, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/ba/a8/84/baa884a7-9bbc-2a20-7bb6-44ca552acc1e/mzl.uccsslls.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761780/edc1771c-2d62-11e5-85b2-05162b89d0b5.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761756/fff6b51a-2d61-11e5-87b2-534ef37d86e8.png)
https://cloud.githubusercontent.com/assets/10730122/8761756/fff6b51a-2d61-11e5-87b2-534ef37d86e8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8761755/fda30cc8-2d61-11e5-9c26-f91735aec83f.png

**Comment by ivanov007** [comment]
@Trubbel  wow burger king fan too? hope you have a good metabolism :wink:

**Comment by Trubbel** [comment]
@ivanov007 Hahaha
