### ISSUE TITLE
McDonald's Türkiye

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6021]
**App Name:** McDonald's Türkiye
**Bundle ID:** CW.McDonald-s
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=545092411">545092411</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mcdonalds-turkiye/id545092411?mt=8&uo=4">https://itunes.apple.com/us/app/mcdonalds-turkiye/id545092411?mt=8&uo=4</a>
**App Version:** 4.4.8
**Seller:** Aritab Bilgi Teknolojileri Ltd. Sti.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/aritab-bilgi-teknolojileri/id545092414?uo=4>© Aritab Bilgi Teknolojileri Ltd. Sti.</a>
**Supported Devices:** iPhone4S, iPhone6, iPhone-3GS, iPhone5s, iPadFourthGen4G, iPadFourthGen, iPhone5, iPodTouchSixthGen, iPhone4, iPodTouchFourthGen, iPadMini, iPhone6Plus, iPad23G, iPadThirdGen, iPodTouchFifthGen, iPadMini4G, iPhone5c, iPad2Wifi, iPadThirdGen4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/c2/89/42/c28942fd-27d5-de1f-2fb9-716d0fd0643e/mzl.jmolhpba.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png)
https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8761834/c42be2c6-2d66-11e5-99cf-e8c30451ac47.png

**Comment by ivanov007** [comment]
@Trubbel so... I'm guessing you are a McDonald's fan right?

**Comment by Trubbel** [comment]
@ivanov007 Haha not really, this is what happens when I'm bored. However, I'm more a sushi fan. :P

**Comment by ivanov007** [comment]
Good for you, I'm also like japanese food :+1:
