### ISSUE TITLE
Realtime for Google Analytics Real-Time

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6036]
**App Name:** Realtime for Google Analytics Real-Time
**Bundle ID:** com.stuartkhall.realtime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=740557474">740557474</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/realtime-for-google-analytics/id740557474?mt=8&uo=4">https://itunes.apple.com/us/app/realtime-for-google-analytics/id740557474?mt=8&uo=4</a>
**App Version:** 1.7.0
**Seller:** Bytesize Systems Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bytesize/id650762528?uo=4>© Bytesize</a>
**Supported Devices:** iPhone6, iPadMini, iPadFourthGen, iPhone5c, iPhone6Plus, iPodTouchFifthGen, iPhone5s, iPadMini4G, iPodTouchSixthGen, iPadFourthGen4G, iPad23G, iPadThirdGen4G, iPhone4, iPadThirdGen, iPhone5, iPad2Wifi, iPhone4S
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/e1/4d/3d/e14d3da4-3e47-62c8-e4cd-69e39540f85d/mzl.igkrefsi.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761985/f827e872-2d6b-11e5-965d-3df487b416b5.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761985/f827e872-2d6b-11e5-965d-3df487b416b5.png)
https://cloud.githubusercontent.com/assets/10730122/8761985/f827e872-2d6b-11e5-965d-3df487b416b5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8761984/f50b019c-2d6b-11e5-8b06-584761ae3f85.png

**Comment by ivanov007** [comment]
@Trubbel wow you are on fire :fire: :fire: :fire: :fire: :fire_engine:
