### ISSUE TITLE
Betsson Casino and Sports

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6038]
**App Name:** Betsson Casino and Sports
**Bundle ID:** com.Techsson.Betsson
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=675620909">675620909</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/cz/app/betsson-casino-and-sports/id675620909?uo=4">https://apps.apple.com/cz/app/betsson-casino-and-sports/id675620909?uo=4</a>
**App Version:** 3.0.10
**Seller:** Betsson Malta Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/cz/developer/bsg/id464237648?uo=4">© BSG</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/0e/29/26/0e292699-17d9-698e-d069-f46f526b83c2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60123949-dff17300-9788-11e9-9597-d3000ac0568a.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8766895/e9aecb9c-2e49-11e5-989c-409668a57f78.png)
https://cloud.githubusercontent.com/assets/10730122/8766895/e9aecb9c-2e49-11e5-989c-409668a57f78.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8766893/e5ac6bd0-2e49-11e5-9ab5-c15815b3cc78.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60123949-dff17300-9788-11e9-9597-d3000ac0568a.png)
https://user-images.githubusercontent.com/20930745/60123949-dff17300-9788-11e9-9597-d3000ac0568a.png

Source:
![betsson](https://user-images.githubusercontent.com/20930745/60123960-e384fa00-9788-11e9-9a94-9216d24cc956.png)
