### ISSUE TITLE
NordicBet Sport

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6039]
**App Name:** NordicBet Sport
**Bundle ID:** com.techsson.nordicBet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=869239502">869239502</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/nordicbet-sport/id869239502?mt=8&uo=4">https://itunes.apple.com/se/app/nordicbet-sport/id869239502?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** Betsson Malta Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/artist/bsg/id464237648?uo=4>© BSG</a>
**Supported Devices:** iPadThirdGen, iPodTouchFifthGen, iPhone4, iPad23G, iPhone4S, iPadFourthGen4G, iPhone5c, iPhone6Plus, iPodTouchSixthGen, iPadThirdGen4G, iPadMini, iPhone6, iPhone5s, iPadFourthGen, iPadMini4G, iPad2Wifi, iPhone5
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/e9/2d/6c/e92d6c2d-45c6-4b7f-2985-98251c414c18/mzl.rfmyhtlm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8766909/4fc6b46c-2e4a-11e5-9cba-669d18547cb7.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8766909/4fc6b46c-2e4a-11e5-9cba-669d18547cb7.png)
https://cloud.githubusercontent.com/assets/10730122/8766909/4fc6b46c-2e4a-11e5-9cba-669d18547cb7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8766908/4c9aa050-2e4a-11e5-8a6c-9d803896d426.png

**Comment by Trubbel** [comment]
I'm not a gambler, I have the worst luck known to man. :laughing:

**Comment by dreamnet** [comment]
@Trubbel :laughing:
