### ISSUE TITLE
Leo Vegas Casino – Live Roulette, Blackjack and Jackpot Slot Games

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6040]
**App Name:** Leo Vegas Casino – Live Roulette, Blackjack and Jackpot Slot Games
**Bundle ID:** com.leovegas.leocasino
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834294342">834294342</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/leo-vegas-casino-live-roulette/id834294342?mt=8&uo=4">https://itunes.apple.com/gb/app/leo-vegas-casino-live-roulette/id834294342?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** LeoVegas Gaming Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/artist/leovegas-gaming-ltd/id834294345?uo=4>© LeoVegas Gaming Ltd</a>
**Supported Devices:** iPadFourthGen, iPhone5c, iPadThirdGen4G, iPhone5s, iPodTouchFourthGen, iPodTouchSixthGen, iPad23G, iPhone4S, iPhone4, iPad2Wifi, iPadMini, iPadMini4G, iPodTouchFifthGen, iPhone6, iPadFourthGen4G, iPhone6Plus, iPhone5, iPhone-3GS, iPadThirdGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple3/v4/b3/da/e7/b3dae7aa-7c20-1435-e327-dc971d2f012d/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8805783/623d9d6a-2fd3-11e5-850f-be789e3dc232.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8768827/a5341316-2e8d-11e5-9f03-4f5a233774aa.png)
https://cloud.githubusercontent.com/assets/10730122/8768827/a5341316-2e8d-11e5-9f03-4f5a233774aa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8768826/a1529f42-2e8d-11e5-9495-597d3541d484.png

**Comment by ivanov007** [comment]
@Trubbel looks good :+1:

**Comment by dreamnet** [comment]
@Trubbel Can you invert this please? :clap:

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8805783/623d9d6a-2fd3-11e5-850f-be789e3dc232.png)
https://cloud.githubusercontent.com/assets/10730122/8805783/623d9d6a-2fd3-11e5-850f-be789e3dc232.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8805778/5e896ea6-2fd3-11e5-8c6f-71e109979033.png

**Comment by ivanov007** [comment]
yup looks better :+1: thanks
