### ISSUE TITLE
Frameographer - Stop Motion & Time-Lapse

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6042]
**App Name:** Frameographer - Stop Motion & Time-Lapse
**Bundle ID:** com.studioneat.frames
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=503347879">503347879</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/frameographer-stop-motion/id503347879?mt=8&uo=4">https://itunes.apple.com/us/app/frameographer-stop-motion/id503347879?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Studio Neat LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/studio-neat/id503347882?uo=4>© Studio Neat</a>
**Supported Devices:** iPadMini4G, iPhone6, iPodTouchFifthGen, iPadThirdGen4G, iPhone6Plus, iPad23G, iPadFourthGen4G, iPodTouchSixthGen, iPhone5, iPhone5s, iPadFourthGen, iPad2Wifi, iPhone4S, iPadMini, iPhone5c, iPadThirdGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/bf/ab/42/bfab4225-562c-96ff-0f98-b830ce731017/mzl.gmswnxts.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8835468/bb12a5a6-3088-11e5-8f92-23e12b32d38a.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8789560/c1449ae2-2f11-11e5-9d30-a337f25aae5e.png)

Source:
https://cloud.githubusercontent.com/assets/7368317/8789560/c1449ae2-2f11-11e5-9d30-a337f25aae5e.png

**Comment by dreamnet** [comment]
@Teekzilla Nice try, but in a Glasklart icon are no layers allowed...

**Comment by Teekzilla** [comment]
@dreamnet I see, I was trying to keep to the original icon, but will redo and submit! 😊

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8835468/bb12a5a6-3088-11e5-8f92-23e12b32d38a.png)
https://cloud.githubusercontent.com/assets/7368317/8835468/bb12a5a6-3088-11e5-8f92-23e12b32d38a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8835469/bbf49dc6-3088-11e5-8148-cc959515006c.png

**Comment by dreamnet** [comment]
@Teekzilla Jup - fine for me! :+1:
