### ISSUE TITLE
Safari Downloader+

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6043]
**App Name:** Safari Downloader+
**Bundle ID:** com.ouraigua.safaridownloaderplus
**iTunes ID:** None (Cydia App)
**App Version:** 3.9-4
**Original Artwork:**
![appicon76x76 2x](https://cloud.githubusercontent.com/assets/7368317/8790274/f6f29150-2f19-11e5-93e6-7b307ce8e89e.png)
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8805663/76d1fea2-2fa0-11e5-80d9-8942ae4bdec4.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8790282/1a9a4c56-2f1a-11e5-8281-971dd59228a1.png)

Source: https://cloud.githubusercontent.com/assets/7368317/8790282/1a9a4c56-2f1a-11e5-8281-971dd59228a1.png

**Comment by dreamnet** [comment]
@Teekzilla The Glasklart icon is perfect, but we need a 1024x1024 px source file as described [here](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources).

**Comment by Teekzilla** [comment]
@dreamnet Gotcha, will redo!

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8804954/a34a2e5e-2f9c-11e5-96fe-306b8fedee99.png)

Source: https://cloud.githubusercontent.com/assets/7368317/8804963/afc1013a-2f9c-11e5-9c34-3a723021464b.png

@dreamnet Will this do?

**Comment by Trubbel** [comment]
@Teekzilla Yes, the source is good. Next time though, can you try to contribute like this? -

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8790282/1a9a4c56-2f1a-11e5-8281-971dd59228a1.png)
https://cloud.githubusercontent.com/assets/7368317/8790282/1a9a4c56-2f1a-11e5-8281-971dd59228a1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8805655/6ba769ae-2fa0-11e5-9d6c-a09c0ec06121.png


*Template*
`![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8790282/1a9a4c56-2f1a-11e5-8281-971dd59228a1.png)`
`https://cloud.githubusercontent.com/assets/7368317/8790282/1a9a4c56-2f1a-11e5-8281-971dd59228a1.png`
`--- ---`
`Source:`
`https://cloud.githubusercontent.com/assets/7368317/8805655/6ba769ae-2fa0-11e5-9d6c-a09c0ec06121.png`

**Comment by Teekzilla** [comment]
@Trubbel As in add the icon source as well under the preview? Will do!

**Comment by Trubbel** [comment]
@Teekzilla I think it looks better with the one with thicker circle, and yeah that's exactly what I meant. Good job! :+1:

**Comment by ivanov007** [comment]
@Teekzilla looks good :+1:

**Comment by PolarisBeaver** [comment]
Might I recommend we use the same icon as https://github.com/glasklart/hd/issues/5154 ?

Reducing redundant icons, etc.

**Comment by Teekzilla** [comment]
@PolarisBeaver Ohhh didn't even see that, and yup might as well use the same. Didn't even realize they had the same icons 😅
