### ISSUE TITLE
Clean Master

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6044]
**App Name:** Clean Master
**Bundle ID:** com.ksmobile.cleanmaster
**iTunes ID:** None (Cydia App)
**App Version:** 1.1
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/8875007/4c901232-3216-11e5-8159-9838afc701d7.png" width="150" height="150">
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8875043/77261974-3216-11e5-9b43-00ef781400ff.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8790354/f9feb800-2f1a-11e5-9726-bd4f82f6cb84.png)

Source: https://cloud.githubusercontent.com/assets/7368317/8790354/f9feb800-2f1a-11e5-9726-bd4f82f6cb84.png

**Comment by Trubbel** [comment]
@Teekzilla Please read the guidelines on how to contribute icons for applications. If you're still unsure, look at the examples at the bottoms. Anyways, good job on making the icons.

**Comment by Teekzilla** [comment]
@Trubbel I have read them. There was nothing about Cydia application included in the format, thus I went to the first page of the Issues where someone requested a Cydia application and the request was labeled valid. I basically just followed that format for the request.

Link to Referred Issue: https://github.com/glasklart/hd/issues/5904

**Comment by Trubbel** [comment]
I'm not talking about making a thread requesting icons, I meant that we use guidelines here on how to contribute an icon to issues.

Take this for example, it's supposed to look like this, https://github.com/glasklart/hd/issues/5938#issuecomment-119699712

**Comment by Teekzilla** [comment]
@Trubbel Could you point me to exactly what part of the submission you're referring to? I've read it all twice and can't see what you're referring to... 😢 I'll fix it in future issues!

**Comment by ivanov007** [comment]
@Teekzilla you just need to add the 1024x0124 black with transparent background png source file

**Comment by Teekzilla** [comment]
@ivanov007 Gotcha, and I see I think I used a different source for the icon originally! But will update and get back to you!

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8875043/77261974-3216-11e5-9b43-00ef781400ff.png)
https://cloud.githubusercontent.com/assets/2068130/8875043/77261974-3216-11e5-9b43-00ef781400ff.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8875055/88e9ce80-3216-11e5-9153-bf090dfe72c2.png
