### ISSUE TITLE
WSU Mobile

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6047]
**App Name:** WSU Mobile
**Bundle ID:** edu.wayne.WSUMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=429907835">429907835</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wsu-mobile/id429907835?mt=8&uo=4">https://itunes.apple.com/us/app/wsu-mobile/id429907835?mt=8&uo=4</a>
**App Version:** 2.0.14
**Seller:** Wayne State University
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/wayne-state-university/id429907838?uo=4>© Wayne State University</a>
**Supported Devices:** iPad2Wifi, iPodTouchFifthGen, iPhone6Plus, iPhone6, iPadThirdGen, iPadFourthGen4G, iPodTouchSixthGen, iPhone5c, iPhone4S, iPadFourthGen, iPhone5s, iPadMini4G, iPadThirdGen4G, iPhone4, iPad23G, iPadMini, iPhone5
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/4c/41/1e/4c411e18-f16d-b86c-d144-726642076811/mzl.nojbnufq.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8810105/b9dfed66-2fba-11e5-9a07-f68fd325e49a.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8810105/b9dfed66-2fba-11e5-9a07-f68fd325e49a.png)
https://cloud.githubusercontent.com/assets/7368317/8810105/b9dfed66-2fba-11e5-9a07-f68fd325e49a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8810106/ba7df36c-2fba-11e5-9a8c-a0078555c1dd.png

**Comment by Trubbel** [comment]
@Teekzilla The source image is supposed to be like this,

https://cloud.githubusercontent.com/assets/10730122/8832449/75f9cd16-30a9-11e5-861c-c4345f5d52c5.png

**Comment by Teekzilla** [comment]
Gotcha, sorry, slowly understanding everything for submission! Thanks for all the help!

**Comment by Trubbel** [comment]
It's all good, I had to learn the "hard" way myself. :wink:

**Comment by Teekzilla** [comment]
Updated submission with corrected source file!

**Comment by ivanov007** [comment]
@Teekzilla looks good :+1:
