### ISSUE TITLE
Akinator the Genie

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#605]
**App Name:** Akinator the Genie
**Bundle ID:** com.elokence.akinator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484090401">484090401</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/akinator-the-genie/id484090401?mt=8&uo=4">https://itunes.apple.com/us/app/akinator-the-genie/id484090401?mt=8&uo=4</a>
**App Version:** 4.6
**Seller:** Elokence.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/elokence/id484090404?uo=4>© Elokence</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/c1/ed/d9/c1edd966-de3c-aee3-a21a-bbe08f6cfce2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19008363/0f8409f6-876b-11e6-9f99-20bfe266bf74.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19008363/0f8409f6-876b-11e6-9f99-20bfe266bf74.png)
https://cloud.githubusercontent.com/assets/2068130/19008363/0f8409f6-876b-11e6-9f99-20bfe266bf74.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19008367/1da3dd5e-876b-11e6-925c-978dc712592d.png
