### ISSUE TITLE
Kolmården Idag

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6051]
**App Name:** Kolmården Idag
**Bundle ID:** com.kolmarden.idag
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989147893">989147893</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kolmarden-idag/id989147893?mt=8&uo=4">https://itunes.apple.com/us/app/kolmarden-idag/id989147893?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Parks and Resorts Scandinavia AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/parks-resorts-scandinavia/id668576868?uo=4>© Parks and Resorts Scandinavia AB</a>
**Supported Devices:** iPodTouchFifthGen, iPad23G, iPhone5s, iPhone4S, iPhone-3GS, iPad2Wifi, iPhone5c, iPadMini4G, iPadMini, iPadThirdGen, iPodTouchFourthGen, iPhone6, iPadThirdGen4G, iPhone6Plus, iPhone5, iPhone4, iPadFourthGen, iPodTouchSixthGen, iPadFourthGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/86/72/23/86722326-eb68-9474-9aa5-00718c50cd37/mzl.vshdmhxm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8839311/9a34d68c-30d4-11e5-869e-a1784a55458b.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8839311/9a34d68c-30d4-11e5-869e-a1784a55458b.png)
https://cloud.githubusercontent.com/assets/10730122/8839311/9a34d68c-30d4-11e5-869e-a1784a55458b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8839309/96e2c3d6-30d4-11e5-9fee-fa728deeb96c.png

**Comment by MagnaMike** [comment]
@Trubbel Good work as always. :wink:
