### ISSUE TITLE
Smith Hotels – boutique, luxury hotels

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6055]
**App Name:** Smith Hotels – boutique, luxury hotels
**Bundle ID:** com.mrandmrssmith.MMS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445834586">445834586</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smith-hotels-boutique-luxury/id445834586?mt=8&uo=4">https://itunes.apple.com/us/app/smith-hotels-boutique-luxury/id445834586?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Mr & Mrs Smith
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mr-mrs-smith/id445834589?uo=4>© Mr & Mrs Smith</a>
**Supported Devices:** iPad23G, iPadThirdGen, iPadFourthGen4G, iPadMini, iPadThirdGen4G, iPadMini4G, iPhone5, iPad2Wifi, iPodTouchFifthGen, iPhone5c, iPadFourthGen, iPhone4S, iPhone6Plus, iPhone4, iPodTouchSixthGen, iPhone5s, iPhone6
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/6b/28/7f/6b287f84-40e8-2039-8502-b3ccabb9325a/mzl.hjsksvsa.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8853558/3e6e5044-3129-11e5-8354-f1c9fa338277.png)

**Comment by Teekzilla** [comment]
![](preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8853558/3e6e5044-3129-11e5-8354-f1c9fa338277.png)
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8853561/3f1f3a3a-3129-11e5-8534-6a3f17344966.png

**Comment by MagnaMike** [comment]
Don't forget to put a direct link to the icon underneath the preview image. This link:

https://cloud.githubusercontent.com/assets/7368317/8853558/3e6e5044-3129-11e5-8354-f1c9fa338277.png
