### ISSUE TITLE
1&1 Online Storage

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#6056]
**App Name:** 1&1 Online Storage
**Bundle ID:** de.1and1.de.officeDrive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=429396710">429396710</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1-1-online-storage/id429396710?mt=8&uo=4">https://itunes.apple.com/us/app/1-1-online-storage/id429396710?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** 1&1 Internet AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/1-1-internet-ag/id392277409?uo=4>© 1&1 Internet AG</a>
**Supported Devices:** iPhone5c, iPadFourthGen, iPad23G, iPadThirdGen, iPadMini, iPhone4, iPadThirdGen4G, iPodTouchFifthGen, iPadFourthGen4G, iPhone4S, iPad2Wifi, iPhone5s, iPhone5, iPhone6, iPhone6Plus, iPadMini4G, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple4/v4/b6/cf/13/b6cf131c-02e3-43d8-ae6c-a7bf577c76cd/mzl.epzkjpyw.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8854783/afdbc56c-312f-11e5-966d-822e3c3b2f42.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8854783/afdbc56c-312f-11e5-966d-822e3c3b2f42.png)
https://cloud.githubusercontent.com/assets/7368317/8854783/afdbc56c-312f-11e5-966d-822e3c3b2f42.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8854785/b07b7dd2-312f-11e5-895a-19f1e6539078.png
