### ISSUE TITLE
1&1 Control-Center

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#6057]
**App Name:** 1&1 Control-Center
**Bundle ID:** com.oneandone.controlcenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=667892191">667892191</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/1-1-control-center/id667892191?mt=8&uo=4">https://itunes.apple.com/de/app/1-1-control-center/id667892191?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** 1&1 Internet AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/artist/1-1-internet-ag/id392277409?uo=4>© 1&1 Internet AG</a>
**Supported Devices:** iPhone4S, iPadMini, iPadFourthGen4G, iPodTouchFifthGen, iPad2Wifi, iPadMini4G, iPhone6, iPadThirdGen, iPadFourthGen, iPhone4, iPadThirdGen4G, iPhone5s, iPhone6Plus, iPhone5c, iPad23G, iPodTouchSixthGen, iPhone5
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/70/25/7f/70257f1a-59d7-acbc-869c-4ee0c1b1da90/mzl.nzdgijic.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8854613/b5a349a8-312e-11e5-91a7-01344a411bb3.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8854613/b5a349a8-312e-11e5-91a7-01344a411bb3.png)
https://cloud.githubusercontent.com/assets/7368317/8854613/b5a349a8-312e-11e5-91a7-01344a411bb3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8854614/b7136e58-312e-11e5-91e1-67c6c9680c7a.png
