### ISSUE TITLE
Map My Run+ - GPS Running and Workout Tracking

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6060]
**App Name:** Map My Run+ - GPS Running and Workout Tracking
**Bundle ID:** Q5AWL8WCY6.iMapMyRunPlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306468004">306468004</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/map-my-run+-gps-running-workout/id306468004?mt=8&uo=4">https://itunes.apple.com/us/app/map-my-run+-gps-running-workout/id306468004?mt=8&uo=4</a>
**App Version:** 16.9.1
**Seller:** MapMyFitness
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/under-armour/id291890423?uo=4>© Under Armour</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/c9/a0/87/c9a08764-a206-fd63-f5df-6f8ceef78e12/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19311657/98cbc80c-908f-11e6-8df2-71235b872148.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8854998/d4bfa3b6-3130-11e5-836f-617db01af2c6.png)
https://cloud.githubusercontent.com/assets/7368317/8854998/d4bfa3b6-3130-11e5-836f-617db01af2c6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8854999/d5b2b54c-3130-11e5-99a3-3393ad2e118f.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19311657/98cbc80c-908f-11e6-8df2-71235b872148.png)
https://cloud.githubusercontent.com/assets/20930745/19311657/98cbc80c-908f-11e6-8df2-71235b872148.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19311674/a89719a8-908f-11e6-993d-c77f0c4e0f46.png
