### ISSUE TITLE
Campaign Monitor

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6064]
**App Name:** Campaign Monitor
**Bundle ID:** com.campaignmonitor.campaign-monitor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=855095172">855095172</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/campaign-monitor/id855095172?mt=8&uo=4">https://itunes.apple.com/us/app/campaign-monitor/id855095172?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Freshview Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/campaign-monitor/id561466702?uo=4>© Campaign Monitor</a>
**Supported Devices:** iPhone5, iPadThirdGen, iPad23G, iPodTouchSixthGen, iPadThirdGen4G, iPhone5s, iPhone4S, iPad2Wifi, iPadFourthGen, iPadFourthGen4G, iPadMini, iPhone6Plus, iPadMini4G, iPhone5c, iPhone6, iPhone4, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/52/04/ff/5204ffa4-807e-2460-1d83-183c22375438/mzl.aheeskmm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8873426/cc67994a-3206-11e5-8d58-96c23c8827ab.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8858418/9bd2b2f4-3177-11e5-9640-468726417603.png)
https://cloud.githubusercontent.com/assets/10730122/8858418/9bd2b2f4-3177-11e5-9640-468726417603.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8858411/9863eb74-3177-11e5-8378-bea59cbd12d8.png

**Comment by dreamnet** [comment]
Original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8873426/cc67994a-3206-11e5-8d58-96c23c8827ab.png)
https://cloud.githubusercontent.com/assets/2068130/8873426/cc67994a-3206-11e5-8d58-96c23c8827ab.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8873434/db0c7394-3206-11e5-9fda-de1d41b9c3d2.png
