### ISSUE TITLE
⋆Spider Solitaire

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#607]
**App Name:** ⋆Spider Solitaire
**Bundle ID:** com.brainiumstudios.spiderfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487025819">487025819</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spider-solitaire/id487025819?mt=8&uo=4">https://itunes.apple.com/us/app/spider-solitaire/id487025819?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** Brainium Studios LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brainium-studios-llc/id300891405?uo=4>© Brainium Studios LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/78/d0/31/78d031de-1631-3fd3-e1d5-8b4ae4be7d99/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19538205/47e7a6f8-9653-11e6-88a9-e387f1fcd342.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19538205/47e7a6f8-9653-11e6-88a9-e387f1fcd342.png)
https://cloud.githubusercontent.com/assets/2068130/19538205/47e7a6f8-9653-11e6-88a9-e387f1fcd342.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19538225/5aa08fc6-9653-11e6-93b3-fb683768ffbd.png
