### ISSUE TITLE
Big Cartel

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6071]
**App Name:** Big Cartel
**Bundle ID:** com.bigcartel.pocketshop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=739285899">739285899</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/big-cartel/id739285899?mt=8&uo=4">https://itunes.apple.com/us/app/big-cartel/id739285899?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Big Cartel, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/big-cartel/id739285902?uo=4>© Big Cartel</a>
**Supported Devices:** iPadThirdGen, iPadFourthGen4G, iPhone6, iPhone5c, iPodTouchSixthGen, iPadFourthGen, iPad23G, iPadMini, iPhone5, iPhone5s, iPadThirdGen4G, iPhone4S, iPodTouchFifthGen, iPad2Wifi, iPhone6Plus, iPadMini4G, iPhone4
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/26/32/f5/2632f570-c543-190a-74e0-f9d70a20d210/mzl.vgsczcil.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8873130/cd1198ee-3203-11e5-8e2b-818537992e49.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8859321/d2368168-317c-11e5-8c49-cf13c8f4e7cf.png)
https://cloud.githubusercontent.com/assets/10730122/8859321/d2368168-317c-11e5-8c49-cf13c8f4e7cf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8859318/ce983312-317c-11e5-81a3-0c4e7ed7e1c6.png

**Comment by dreamnet** [comment]
Original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8873130/cd1198ee-3203-11e5-8e2b-818537992e49.png)
https://cloud.githubusercontent.com/assets/2068130/8873130/cd1198ee-3203-11e5-8e2b-818537992e49.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8873140/dbd0eba0-3203-11e5-9a83-9864b9110e3b.png
