### ISSUE TITLE
Control for Paymill

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6074]
**App Name:** Control for Paymill
**Bundle ID:** co.getcontrol
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=907627741">907627741</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/control-for-paymill/id907627741?mt=8&uo=4">https://itunes.apple.com/us/app/control-for-paymill/id907627741?mt=8&uo=4</a>
**App Version:** 2.19
**Seller:** Control Mobile Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/control-mobile/id907627744?uo=4>© Control Mobile</a>
**Supported Devices:** iPhone5s, iPhone4, iPad23G, iPadFourthGen4G, iPhone6Plus, iPhone6, iPad2Wifi, iPhone5, iPadFourthGen, iPodTouchFifthGen, iPodTouchSixthGen, iPhone4S, iPadMini, iPadMini4G, iPadThirdGen4G, iPhone5c, iPadThirdGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/2c/dc/c8/2cdcc848-6484-3cf5-79cd-bb79b0f3f3e9/mzl.lcnaytyz.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8872949/0b15958e-3202-11e5-8694-f7f00a40b051.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8859562/4eb01da2-317e-11e5-8671-03a2a3471fa9.png)
https://cloud.githubusercontent.com/assets/10730122/8859562/4eb01da2-317e-11e5-8671-03a2a3471fa9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8859554/469ae19c-317e-11e5-9473-ad8dd9e94d88.png

**Comment by dreamnet** [comment]
Original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8872949/0b15958e-3202-11e5-8694-f7f00a40b051.png)
https://cloud.githubusercontent.com/assets/2068130/8872949/0b15958e-3202-11e5-8694-f7f00a40b051.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8872976/1cc118f8-3202-11e5-8fa5-871f1b8109d3.png
