### ISSUE TITLE
HomeBudget with Sync

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6075]
**App Name:** HomeBudget with Sync
**Bundle ID:** com.anishu.homebudget
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306257910">306257910</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/homebudget-with-sync/id306257910?mt=8&uo=4">https://itunes.apple.com/us/app/homebudget-with-sync/id306257910?mt=8&uo=4</a>
**App Version:** 3.1.5
**Seller:** Anishu, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/anishu-inc./id306257913?uo=4>© Anishu, Inc.</a>
**Supported Devices:** iPadThirdGen, iPhone6Plus, iPodTouchFifthGen, iPhone4S, iPad23G, iPadThirdGen4G, iPhone5, iPad2Wifi, iPhone4, iPhone5c, iPhone5s, iPadMini, iPadFourthGen4G, iPadMini4G, iPadFourthGen, iPhone6, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/0c/a8/5b/0ca85ba5-8a61-f5c0-7acc-b9bc23486655/mzl.txowamsa.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8859672/054f5f00-317f-11e5-938c-a24c4e15abfc.png)

**Comment by Trubbel** [comment]
Couldn't find the issue for this application.

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8859672/054f5f00-317f-11e5-938c-a24c4e15abfc.png)
https://cloud.githubusercontent.com/assets/10730122/8859672/054f5f00-317f-11e5-938c-a24c4e15abfc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8859669/015cc13a-317f-11e5-8085-88b3f324e714.png

**Comment by MagnaMike** [comment]
@Trubbel Not all apps have issues - glasklart was started before this github was. Probably why you can't find it.

**Comment by dreamnet** [comment]
Icon is already in the repo. No further action needed.
