### ISSUE TITLE
fabric

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6083]
**App Name:** fabric
**Bundle ID:** com.fabriclondon.fabric
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=510934540">510934540</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fabric/id510934540?mt=8&uo=4">https://itunes.apple.com/us/app/fabric/id510934540?mt=8&uo=4</a>
**App Version:** 1.8.0
**Seller:** fabric
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fabric/id510934543?uo=4>© fabric</a>
**Supported Devices:** iPhone5, iPhone4, iPad2Wifi, iPad23G, iPadMini4G, iPodTouchSixthGen, iPhone6, iPhone5c, iPodTouchFifthGen, iPhone-3GS, iPadMini, iPadThirdGen, iPadFourthGen, iPadFourthGen4G, iPadThirdGen4G, iPhone6Plus, iPhone5s, iPodTouchFourthGen, iPhone4S
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/28/b6/b7/28b6b760-a69e-ebe4-0d93-6dae2114c68c/mzl.zgelsogn.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8860358/9dbf8e64-3183-11e5-9b81-1a9792b1b2cc.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8860358/9dbf8e64-3183-11e5-9b81-1a9792b1b2cc.png)
https://cloud.githubusercontent.com/assets/10730122/8860358/9dbf8e64-3183-11e5-9b81-1a9792b1b2cc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8860356/984ab9f4-3183-11e5-8fc6-33d58135f924.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8860377/b423483a-3183-11e5-81fa-12c95f68028c.png)
https://cloud.githubusercontent.com/assets/10730122/8860377/b423483a-3183-11e5-81fa-12c95f68028c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8860375/b0fdf9d4-3183-11e5-8060-8c817f05c3b7.png

**Comment by MagnaMike** [comment]
Taking :one: :
