### ISSUE TITLE
Spy&Capture

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6085]
**App Name:** Spy&Capture
**Bundle ID:** acwind.net.HideIt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=415592705">415592705</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spy-capture/id415592705?mt=8&uo=4">https://itunes.apple.com/us/app/spy-capture/id415592705?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** JUNYING ZHANG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/junying-zhang/id372593992?uo=4>© JUNYING ZHANG</a>
**Supported Devices:** iPhone5c, iPhone-3GS, iPadThirdGen4G, iPhone5s, iPhone6, iPad2Wifi, iPhone4S, iPadFourthGen4G, iPadMini4G, iPodTouchSixthGen, iPadThirdGen, iPad23G, iPhone5, iPhone4, iPodTouchFourthGen, iPodTouchFifthGen, iPhone-3G, iPadMini, iPadFourthGen, iPhone6Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple/17/0b/ca/mzl.itgsootx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8993352/c554d1d8-3704-11e5-8cd1-4ff1ee09f25a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8993352/c554d1d8-3704-11e5-8cd1-4ff1ee09f25a.png)
https://cloud.githubusercontent.com/assets/2068130/8993352/c554d1d8-3704-11e5-8cd1-4ff1ee09f25a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8993358/d6062cfc-3704-11e5-9de2-6b84741d4279.png

**Comment by Trubbel** [comment]
@dreamnet Very nice!
