### ISSUE TITLE
Face Sketch

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6087]
**App Name:** Face Sketch
**Bundle ID:** com.gilmourgames.sketchstudio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1016231968">1016231968</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/face-sketch/id1016231968?mt=8&uo=4">https://itunes.apple.com/us/app/face-sketch/id1016231968?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Peter Gilmour
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/peter-gilmour/id980891153?uo=4>© Peter Gilmour</a>
**Supported Devices:** iPadMini, iPhone5s, iPhone4S, iPodTouchSixthGen, iPadThirdGen, iPhone-3GS, iPadThirdGen4G, iPodTouchFourthGen, iPodTouchFifthGen, iPhone6Plus, iPadFourthGen, iPhone6, iPhone5c, iPadFourthGen4G, iPhone4, iPad23G, iPad2Wifi, iPadMini4G, iPhone5
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/29/b5/d3/29b5d3ed-618e-75af-fb57-a7fb4b976f6f/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8864463/7d5f4942-31a2-11e5-9d9a-98dc74e0e0b9.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8864463/7d5f4942-31a2-11e5-9d9a-98dc74e0e0b9.png)
https://cloud.githubusercontent.com/assets/10730122/8864463/7d5f4942-31a2-11e5-9d9a-98dc74e0e0b9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8864461/797c368c-31a2-11e5-918f-52121a7aa9a3.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8864474/90fd805e-31a2-11e5-9ba1-9a861aecba00.png)
https://cloud.githubusercontent.com/assets/10730122/8864474/90fd805e-31a2-11e5-9ba1-9a861aecba00.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8864469/8d063176-31a2-11e5-9ae7-bed35cbc8527.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8864511/f58d88f2-31a2-11e5-8077-746630ed4e9d.png)
https://cloud.githubusercontent.com/assets/10730122/8864511/f58d88f2-31a2-11e5-8077-746630ed4e9d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8864510/f14b4d42-31a2-11e5-932d-656aa4b2a155.png

**Comment by dreamnet** [comment]
@Trubbel The first one is fine. :+1:
