### ISSUE TITLE
Mail2Widget-Manage Emails in Lock Screen.Fast.Easy

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6088]
**App Name:** Mail2Widget-Manage Emails in Lock Screen.Fast.Easy
**Bundle ID:** com.Mail.Today
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1003369713">1003369713</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mail2widget-manage-emails/id1003369713?mt=8&uo=4">https://itunes.apple.com/us/app/mail2widget-manage-emails/id1003369713?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Rajesh V
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rajesh-v/id1003369712?uo=4">© Rajesh V</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple22/v4/43/43/ae/4343ae6d-7a7f-ca83-5620-e17c6f013c82/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21015255/98a96c68-bd61-11e6-9c56-1b274beaa347.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8864644/99e38036-31a4-11e5-8aad-cbd836a8d25d.png)
https://cloud.githubusercontent.com/assets/10730122/8864644/99e38036-31a4-11e5-8aad-cbd836a8d25d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8864642/96d9850c-31a4-11e5-98ce-8d57dea6c7a6.png

**Comment by dreamnet** [comment]
Here is one, that is a bit "cleaner":
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8895469/2604ee4a-33dc-11e5-9a17-023723625c3d.png)
https://cloud.githubusercontent.com/assets/2068130/8895469/2604ee4a-33dc-11e5-9a17-023723625c3d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8895470/35b338f6-33dc-11e5-826e-056a5aba194f.png
Dosen't look very different from the one from @Trubbel and I'm also not very satisfied how it looks in general, but I don't think this can be done very different, so I take it.

**Comment by Trubbel** [comment]
Yeah, I don't think there's much more we can do. Also, yours is of course better. Thanks for that! :smile:

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Mail2Widget-Manage Emails in Lock Screen.Fast.Easy
**Bundle ID:** com.Mail.Today
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1003369713">1003369713</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mail2widget-manage-emails/id1003369713?mt=8&uo=4">https://itunes.apple.com/us/app/mail2widget-manage-emails/id1003369713?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Rajesh V
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rajesh-v/id1003369712?uo=4">© Rajesh V</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple22/v4/43/43/ae/4343ae6d-7a7f-ca83-5620-e17c6f013c82/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21015255/98a96c68-bd61-11e6-9c56-1b274beaa347.png)
https://cloud.githubusercontent.com/assets/20930745/21015255/98a96c68-bd61-11e6-9c56-1b274beaa347.png^

Source:
https://cloud.githubusercontent.com/assets/20930745/21015267/a3615ba2-bd61-11e6-8515-a320f778c610.png
