### ISSUE TITLE
Snapster by VK

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6089]
**App Name:** Snapster by VK
**Bundle ID:** com.vk.snapster.production
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1016603298">1016603298</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snapster-by-vk/id1016603298?mt=8&uo=4">https://itunes.apple.com/us/app/snapster-by-vk/id1016603298?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** VKontakte
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/vkontakte/id427948433?uo=4>© VKontakte</a>
**Supported Devices:** iPadMini, iPhone6Plus, iPadMini4G, iPadFourthGen, iPhone5c, iPhone4S, iPhone5, iPadFourthGen4G, iPhone4, iPhone5s, iPodTouchSixthGen, iPadThirdGen4G, iPad2Wifi, iPodTouchFifthGen, iPad23G, iPadThirdGen, iPhone6
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/d6/79/15/d67915bc-9aa6-932a-4a17-91711e42afd5/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8870936/0b84ba32-31f2-11e5-87b8-99e800e6b4d3.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8864674/1f4281fa-31a5-11e5-8b42-7386a6ef2fac.png)
https://cloud.githubusercontent.com/assets/10730122/8864674/1f4281fa-31a5-11e5-8b42-7386a6ef2fac.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8864672/1bbafad0-31a5-11e5-8121-dbf676a1c142.png

**Comment by dreamnet** [comment]
Original Size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8870936/0b84ba32-31f2-11e5-87b8-99e800e6b4d3.png)
https://cloud.githubusercontent.com/assets/2068130/8870936/0b84ba32-31f2-11e5-87b8-99e800e6b4d3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8870940/193c836c-31f2-11e5-939d-91754aedb1fe.png
