### ISSUE TITLE
Sideloader for Fire TV

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#6091]
**App Name:** Sideloader for Fire TV
**Bundle ID:** com.guidology.ios.Sideloader-for-Fire-TV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=983526114">983526114</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sideloader-for-fire-tv/id983526114?mt=8&uo=4">https://itunes.apple.com/us/app/sideloader-for-fire-tv/id983526114?mt=8&uo=4</a>
**App Version:** 1.02
**Seller:** Jean Alger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jean-alger/id981405469?uo=4>© Jean Alger</a>
**Supported Devices:** iPhone5, iPadThirdGen4G, iPadMini, iPhone6, iPadThirdGen, iPhone6Plus, iPodTouchFourthGen, iPodTouchSixthGen, iPodTouchFifthGen, iPad23G, iPadFourthGen, iPadMini4G, iPhone4, iPadFourthGen4G, iPhone4S, iPhone5s, iPhone5c, iPad2Wifi, iPhone-3GS
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/fc/33/c9/fc33c953-a537-51f1-df55-efa45f449ccb/mzl.oczekhda.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8869499/aab8500e-31e4-11e5-86ab-d157cd776dfe.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8869499/aab8500e-31e4-11e5-86ab-d157cd776dfe.png)
https://cloud.githubusercontent.com/assets/2068130/8869499/aab8500e-31e4-11e5-86ab-d157cd776dfe.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8869507/bdba2178-31e4-11e5-883f-0210375b85b6.png
