### ISSUE TITLE
Siege Hero

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6094]
**App Name:** Siege Hero
**Bundle ID:** com.armorgames.isieger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431688122">431688122</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/siege-hero/id431688122?mt=8&uo=4">https://itunes.apple.com/us/app/siege-hero/id431688122?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Armor Games Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/armor-games-inc/id286413135?uo=4>© Armor Games Inc</a>
**Supported Devices:** iPad23G, iPadWifi, iPhone5c, iPadMini4G, iPad3G, iPhone6Plus, iPhone6, iPodTouchThirdGen, iPhone5s, iPhone-3GS, iPhone4, iPadFourthGen4G, iPadThirdGen, iPodTouchFourthGen, iPodTouchFifthGen, iPad2Wifi, iPadFourthGen, iPodTouchSixthGen, iPhone4S, iPhone5, iPadMini, iPadThirdGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/4e/d0/0c/4ed00cd5-269e-7499-712f-4c275b4a0689/mzl.gpzlsfac.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8880072/2fed60b0-3236-11e5-90da-371d356f5c86.png)

**Comment by LaCh0uine** [comment]
Need to be updated ;)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8879948/58e503c0-3235-11e5-8d8e-bf25d89bffe1.png)
https://cloud.githubusercontent.com/assets/10730122/8879948/58e503c0-3235-11e5-8d8e-bf25d89bffe1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8879941/5598d8f4-3235-11e5-8ff0-9a0ab9eda539.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8880014/c846e3d2-3235-11e5-8e22-57548b48fec4.png)
https://cloud.githubusercontent.com/assets/10730122/8880014/c846e3d2-3235-11e5-8e22-57548b48fec4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8880012/c4756c92-3235-11e5-9675-9e7bbb394246.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8880072/2fed60b0-3236-11e5-90da-371d356f5c86.png)
https://cloud.githubusercontent.com/assets/10730122/8880072/2fed60b0-3236-11e5-90da-371d356f5c86.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8880067/29a6a13a-3236-11e5-9867-3e7caeb07476.png

**Comment by dreamnet** [comment]
@Trubbel WOW! Good work! :beer:

**Comment by Trubbel** [comment]
A beer sounds good, thank god it's Friday. :beers:

**Comment by LaCh0uine** [comment]
@Trubbel good job thank you
