### ISSUE TITLE
iGeneration

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6095]
**App Name:** iGeneration
**Bundle ID:** com.macgeneration.macgmobile.freeversion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=346175650">346175650</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/igeneration/id346175650?uo=4">https://apps.apple.com/us/app/igeneration/id346175650?uo=4</a>
**App Version:** 5.6
**Seller:** MacGeneration
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/macgeneration/id346175653?uo=4">© MacGeneration</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/14/e5/03/14e5034b-d492-ed68-10e3-56884dfc08db/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62398018-c6a5c880-b577-11e9-83ac-74373b8d5aec.png)

**Comment by LaCh0uine** [comment]
Need to be updated Ty

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8879613/d06bb90a-3232-11e5-8809-03248c8683bc.png)
https://cloud.githubusercontent.com/assets/10730122/8879613/d06bb90a-3232-11e5-8809-03248c8683bc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8879611/cd7492a8-3232-11e5-8be0-73bbc5be3068.png

**Comment by dreamnet** [comment]
@Trubbel Jup! :+1:

**Comment by LaCh0uine** [comment]
Icon need update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19677891/bda552b8-9a9b-11e6-879c-0142ee825109.png)
https://cloud.githubusercontent.com/assets/20930745/19677891/bda552b8-9a9b-11e6-879c-0142ee825109.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19677885/aefbe128-9a9b-11e6-8481-f8ac3d80ee00.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62398018-c6a5c880-b577-11e9-83ac-74373b8d5aec.png)
https://user-images.githubusercontent.com/2068130/62398018-c6a5c880-b577-11e9-83ac-74373b8d5aec.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62398038-d6251180-b577-11e9-9643-1a4fb41de931.png
