### ISSUE TITLE
Κυπριακή Τηλεόραση

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6096]
**App Name:** Κυπριακή Τηλεόραση
**Bundle ID:** co.coprime.KipriakiTileorasi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=946699893">946699893</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kypriake-teleorase/id946699893?mt=8&uo=4">https://itunes.apple.com/us/app/kypriake-teleorase/id946699893?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Marios Fekkos
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/marios-fekkos/id903887948?uo=4>© Marios Fekkos</a>
**Supported Devices:** iPadThirdGen4G, iPhone4, iPad23G, iPadThirdGen, iPadMini4G, iPhone4S, iPodTouchFifthGen, iPodTouchSixthGen, iPhone5s, iPadFourthGen4G, iPadFourthGen, iPhone5c, iPhone6, iPad2Wifi, iPhone6Plus, iPadMini, iPhone5
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/f4/89/9c/f4899c73-58e7-4af4-4793-bb77a45ad4c1/mzl.cqhvkfxe.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8888657/f6fd93f2-32b6-11e5-8318-bcee08ba44d8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8888657/f6fd93f2-32b6-11e5-8318-bcee08ba44d8.png)
https://cloud.githubusercontent.com/assets/2068130/8888657/f6fd93f2-32b6-11e5-8318-bcee08ba44d8.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8888660/0448d22e-32b7-11e5-86a3-f07f44e3b1df.png
