### ISSUE TITLE
1Limburg

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#6098]
**App Name:** 1Limburg
**Bundle ID:** nl.eenlimburg.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911802784">911802784</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1limburg/id911802784?mt=8&uo=4">https://itunes.apple.com/us/app/1limburg/id911802784?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** 1Limburg BV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/1limburg-bv/id911802787?uo=4>© 1Limburg BV</a>
**Supported Devices:** iPodTouchFifthGen, iPadThirdGen, iPadFourthGen4G, iPad2Wifi, iPad23G, iPhone5c, iPhone4S, iPadMini, iPhone5s, iPadFourthGen, iPhone6, iPhone5, iPodTouchSixthGen, iPadMini4G, iPhone4, iPadThirdGen4G, iPhone6Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/2d/b0/36/2db03626-4aca-ed23-a717-4ac2a13117e4/mzl.pzarqgsr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8889243/619adee8-32d2-11e5-8b9b-1bf56c9adadc.png)

**Comment by 48296** [comment]
i"m making it!

**Comment by 48296** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/4236952/8889212/3b6dd942-32d1-11e5-9e24-81319698d137.png)

https://cloud.githubusercontent.com/assets/4236952/8889217/4cb4da16-32d1-11e5-881d-95260f56a3f7.png

https://cloud.githubusercontent.com/assets/4236952/8889219/506a9f60-32d1-11e5-9df3-5f0c4f5a3fbd.png

**Comment by dreamnet** [comment]
@48296 Almost perfect, but why so small? I wold make it this way:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8889243/619adee8-32d2-11e5-8b9b-1bf56c9adadc.png)
https://cloud.githubusercontent.com/assets/2068130/8889243/619adee8-32d2-11e5-8b9b-1bf56c9adadc.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8889248/7878fff0-32d2-11e5-9f31-1d20f64cae8e.png
That's original size.

**Comment by 48296** [comment]
@ dreamnet,

I don't know? I used the Template, and it came out like that.
I can remember a time when i made an icon which was to big??
[https://github.com/glasklart/hd/issues/2634]
That one is impossible to see on my iphone because it's so small.
It's also better bigger

**Comment by dreamnet** [comment]
@48296 Anyway, it's OK, you are getting credits for this. :+1:

**Comment by 48296** [comment]
no, I like the bigger one! and I agree with you! Maybe it's just a thing a need to get the hang of.

**Comment by dreamnet** [comment]
@48296 Oh, I mean I take the bigger one and give you the credits. All good.
