### ISSUE TITLE
Topo GPS Netherlands

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#6099]
**App Name:** Topo GPS Netherlands
**Bundle ID:** rdzl.Topo-GPS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=578960575">578960575</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/topo-gps-netherlands/id578960575?mt=8&uo=4">https://itunes.apple.com/us/app/topo-gps-netherlands/id578960575?mt=8&uo=4</a>
**App Version:** 3.22
**Seller:** rdzl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/rdzl/id578960578?uo=4>© rdzl</a>
**Supported Devices:** iPodTouchFourthGen, iPhone4, iPad2Wifi, iPhone5s, iPad23G, iPhone-3GS, iPadMini, iPhone5, iPadFourthGen, iPhone4S, iPodTouchFifthGen, iPadFourthGen4G, iPhone6, iPadMini4G, iPhone6Plus, iPadThirdGen4G, iPhone5c, iPodTouchSixthGen, iPadThirdGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/f9/f6/bd/f9f6bd2d-2895-0662-a63f-a88c2aede9b3/mzl.bhvlckfj.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8924339/ee45b828-34fc-11e5-863f-3cfc4adef90a.png)

**Comment by 48296** [comment]
I didn't know if i should keep or leave the small lines?! I don't know how to get those line crisp either.
![](http://preview.dreamnet.at/?image=
![icon - smart object1](https://cloud.githubusercontent.com/assets/4236952/8889353/158accac-32d7-11e5-9f28-9825a55f273d.png)

https://cloud.githubusercontent.com/assets/4236952/8889355/18598518-32d7-11e5-9829-eff8e01528d9.png

https://cloud.githubusercontent.com/assets/4236952/8889346/7fd1f690-32d6-11e5-916a-b09bf3a396db.png

**Comment by MagnaMike** [comment]
@48296 You would have to be working with vector graphics (like with Adobe Illustrator for example) to get smooth lines.

**Comment by dreamnet** [comment]
@48296 Example:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8924339/ee45b828-34fc-11e5-863f-3cfc4adef90a.png)
https://cloud.githubusercontent.com/assets/2068130/8924339/ee45b828-34fc-11e5-863f-3cfc4adef90a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8924343/fee95ae0-34fc-11e5-8212-4fd37e115105.png
