### ISSUE TITLE
Triple Town

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#610]
**App Name:** Triple Town - Fun & addictive puzzle matching game
**Bundle ID:** com.spryfox.tripletown
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490532168">490532168</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/triple-town-fun-addictive-puzzle-matching-game/id490532168?mt=8&uo=4">https://itunes.apple.com/us/app/triple-town-fun-addictive-puzzle-matching-game/id490532168?mt=8&uo=4</a>
**App Version:** 1.90.4
**Seller:** Spry Fox LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/spry-fox-llc/id441192743?uo=4">© Spry Fox, LLC</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/81/25/3e/81253e99-46f8-4ac4-ce62-8833fd7e383d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32403262-c062fea8-c135-11e7-8eb3-99ac640f9d0f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32403262-c062fea8-c135-11e7-8eb3-99ac640f9d0f.png)
https://user-images.githubusercontent.com/2068130/32403262-c062fea8-c135-11e7-8eb3-99ac640f9d0f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32403267-d35b0906-c135-11e7-83ce-d0779b8fb441.png
