### ISSUE TITLE
Buienradar- Update bundle ID

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#6100]
**App Name:** Buienradar
**Bundle ID:** **nl.rtl.buienradar**
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=621542526">621542526</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/buienradar/id621542526?mt=8&uo=4">https://itunes.apple.com/us/app/buienradar/id621542526?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** RTL Nederland Interactief B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/rtl-nederland/id398467676?uo=4>© RTL Nederland</a>
**Supported Devices:** iPad23G, iPadFourthGen, iPadThirdGen, iPadFourthGen4G, iPhone5, iPhone6Plus, iPhone4, iPadMini, iPad2Wifi, iPadThirdGen4G, iPhone6, iPhone4S, iPodTouchFifthGen, iPhone5c, iPodTouchSixthGen, iPadMini4G, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/2f/bc/1d/2fbc1de7-7545-0daf-6ff1-10d52b144225/mzl.fwafzcma.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 48296** [comment]
[https://github.com/glasklart/hd/issues/1306]

**Comment by MagnaMike** [comment]
@48296 Please comment existing issues in cases like this. I will update the original post in #1306 with the new info.
