### ISSUE TITLE
Clips Video Editor

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6101]
**App Name:** Clips Video Editor
**Bundle ID:** com.editonthefly.clips
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937855347">937855347</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clips-video-editor/id937855347?mt=8&uo=4">https://itunes.apple.com/us/app/clips-video-editor/id937855347?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Fly Labs Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fly-labs-inc./id556972595?uo=4>© Fly Labs Inc.</a>
**Supported Devices:** iPodTouchSixthGen, iPadThirdGen4G, iPodTouchFifthGen, iPhone5s, iPadFourthGen, iPadMini, iPadThirdGen, iPhone5, iPad2Wifi, iPhone4S, iPad23G, iPhone6Plus, iPadMini4G, iPadFourthGen4G, iPhone6, iPhone5c
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/40/e4/5d/40e45d2c-503f-83d4-beda-e97e1d3d5de7/mzl.lppxjjwz.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8890261/dfce2a14-32f9-11e5-9f35-9dbad5bce8b2.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8890261/dfce2a14-32f9-11e5-9f35-9dbad5bce8b2.png)
https://cloud.githubusercontent.com/assets/10730122/8890261/dfce2a14-32f9-11e5-9f35-9dbad5bce8b2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8890260/dc73a34e-32f9-11e5-9e79-c62c3bad655e.png

**Comment by LaCh0uine** [comment]
@Trubbel awesome 👍🏻
