### ISSUE TITLE
This War of Mine

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6102]
**App Name:** This War of Mine
**Bundle ID:** com.11bitstudios.twommobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=982175678">982175678</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/this-war-of-mine/id982175678?mt=8&uo=4">https://itunes.apple.com/us/app/this-war-of-mine/id982175678?mt=8&uo=4</a>
**App Version:** 1.3.8
**Seller:** 11 bit studios s.a.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/11-bit-studios-s.a./id427155206?uo=4>© 11 bit studios s.a.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/e1/f1/f3/e1f1f308-95ce-db2c-51ed-10c1a3c2eb46/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12538935/10ed59ee-c2e7-11e5-846c-0d9658f64d62.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8890328/d19ebc48-32fd-11e5-9461-50df70d1cedc.png)
https://cloud.githubusercontent.com/assets/10730122/8890328/d19ebc48-32fd-11e5-9461-50df70d1cedc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8890327/cdf65998-32fd-11e5-9772-2772d1f8d5ea.png

**Comment by Trubbel** [comment]
Ah, just noticed now that it's iPad-only..

**Comment by dreamnet** [comment]
@Trubbel I'm adding it to my website, but not to the master.

**Comment by Grafovich** [comment]
Now it's available for iPhone too. Maybe you'd add this to the theme please?

**Comment by Trubbel** [comment]
Updated the issue and the icon.

**Comment by Grafovich** [comment]
@Trubbel Great. Thank you.
