### ISSUE TITLE
B-Dubs®

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6103]
**App Name:** B-Dubs®
**Bundle ID:** com.buffalowildwings.bdubsapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=501431760">501431760</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/b-dubs/id501431760?mt=8&uo=4">https://itunes.apple.com/us/app/b-dubs/id501431760?mt=8&uo=4</a>
**App Version:** 902
**Seller:** Buffalo Wild Wings, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/buffalo-wild-wings-inc./id501431763?uo=4>© Buffalo Wild Wings, Inc.</a>
**Supported Devices:** iPhone4S, iPadMini, iPhone4, iPodTouchFifthGen, iPadThirdGen, iPadThirdGen4G, iPodTouchSixthGen, iPad2Wifi, iPadMini4G, iPhone5, iPadFourthGen, iPhone5s, iPad23G, iPhone6, iPhone5c, iPhone6Plus, iPadFourthGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple/v4/67/12/05/671205c6-e040-3a6b-e9f5-f2a58bb4eb97/mzl.vabarugy.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8890916/e8209850-3312-11e5-8e96-1c81c0a39ca0.png)

**Comment by Teekzilla** [comment]
Absolutely the most necessary icon IMO...

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8890440/1caa6ce8-32cf-11e5-8fb5-4b856ae83cea.png)
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8890441/1df51a08-32cf-11e5-8ce2-461c392c4ed6.png

**Comment by Trubbel** [comment]
@Teekzilla I think it would look better with the circle border as well, could you try that?

**Comment by Teekzilla** [comment]
Gotcha, away from computer but will do after!

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/8890885/88f4f1c4-32df-11e5-8897-9059c629d88c.png)
https://cloud.githubusercontent.com/assets/7368317/8890885/88f4f1c4-32df-11e5-8897-9059c629d88c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/8890886/89b1964e-32df-11e5-87c0-b82fdef0e533.png

**Comment by dreamnet** [comment]
What about simply doing this?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8890916/e8209850-3312-11e5-8e96-1c81c0a39ca0.png)
https://cloud.githubusercontent.com/assets/2068130/8890916/e8209850-3312-11e5-8e96-1c81c0a39ca0.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8890920/f67159b2-3312-11e5-8f6d-8d1eb05af5be.png

**Comment by MagnaMike** [comment]
@dreamnet That's what I was looking for. :+1:

**Comment by Teekzilla** [comment]
Looks good to me 😁 Just needed an icon for Bdubs, haha favorite place to eat
