### ISSUE TITLE
TELUS Network Experience

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#6104]
**App Name:** TELUS Network Experience
**Bundle ID:** com.telus.tne.prod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=591161109">591161109</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/telus-network-experience/id591161109?mt=8&uo=4">https://itunes.apple.com/ca/app/telus-network-experience/id591161109?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** TELUS Communications Company
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/artist/telus-communications-company/id383253217?uo=4>© TELUS Communications Company</a>
**Supported Devices:** iPadMini4G, iPad23G, iPhone5s, iPhone6Plus, iPodTouchFifthGen, iPodTouchSixthGen, iPadMini, iPadFourthGen4G, iPhone4S, iPhone5, iPhone5c, iPhone6, iPhone4, iPadFourthGen, iPadThirdGen4G, iPadThirdGen, iPad2Wifi
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/94/da/87/94da8767-8e0f-2984-1080-9957e1862bdf/mzl.zhotdyns.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8891052/733650e2-3318-11e5-814d-6e9ac16c08b5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8891052/733650e2-3318-11e5-814d-6e9ac16c08b5.png)
https://cloud.githubusercontent.com/assets/2068130/8891052/733650e2-3318-11e5-814d-6e9ac16c08b5.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8891055/832234b2-3318-11e5-8caf-a1a0a6c58775.png
