### ISSUE TITLE
prkng - Montreal & Quebec - Find a parking spot

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#6105]
**App Name:** prkng - Montreal & Quebec - Find a parking spot
**Bundle ID:** ng.prk.prkng-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=999834216">999834216</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/prkng-montreal-quebec-find/id999834216?mt=8&uo=4">https://itunes.apple.com/us/app/prkng-montreal-quebec-find/id999834216?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Prkng Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/prkng/id999834215?uo=4>© prkng</a>
**Supported Devices:** iPadFourthGen, iPodTouchFifthGen, iPadFourthGen4G, iPhone4S, iPhone5s, iPadThirdGen, iPadMini4G, iPhone5c, iPadMini, iPadThirdGen4G, iPhone4, iPhone6, iPhone6Plus, iPodTouchSixthGen, iPad2Wifi, iPad23G, iPhone5
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/0a/6b/8b/0a6b8b96-f0d2-b6ff-de7e-9cbb2ee07658/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8891082/f7493d94-3319-11e5-94ee-9b4e7ab939d7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8891082/f7493d94-3319-11e5-94ee-9b4e7ab939d7.png)
https://cloud.githubusercontent.com/assets/2068130/8891082/f7493d94-3319-11e5-94ee-9b4e7ab939d7.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8891084/0deec7d0-331a-11e5-823e-2fdd4e67aa61.png
