### ISSUE TITLE
Blue Sky Weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6106]
**App Name:** Blue Sky Weather
**Bundle ID:** mobi.byss.iwmeteo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=978312542">978312542</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blue-sky-weather/id978312542?mt=8&uo=4">https://itunes.apple.com/us/app/blue-sky-weather/id978312542?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** BYSS mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/byss-mobile/id327447624?uo=4>© byss mobile</a>
**Supported Devices:** iPad23G, iPodTouchSixthGen, iPad2Wifi, iPadThirdGen, iPadMini4G, iPadFourthGen4G, iPhone6Plus, iPhone5s, iPhone5, iPadThirdGen4G, iPhone4S, iPhone6, iPadFourthGen, iPadMini, iPhone5c, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/fb/12/ac/fb12acf3-55c4-3520-0df7-2113a7eb8df7/mzl.guxnsudu.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9238490/eeebbdc4-4152-11e5-8e80-807a61e25cdc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9238490/eeebbdc4-4152-11e5-8e80-807a61e25cdc.png)
https://cloud.githubusercontent.com/assets/2068130/9238490/eeebbdc4-4152-11e5-8e80-807a61e25cdc.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9238496/ffa6a192-4152-11e5-80e9-62f39e218f87.png

**Comment by TheRyanKing** [comment]
@dreamnet you are darn good at these lol!

**Comment by dreamnet** [comment]
@TheRyanKing :smiley: :+1:
