### ISSUE TITLE
Weather Nerd - Forecasts & Radar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6107]
**App Name:** Weather Nerd - Forecasts & Radar
**Bundle ID:** com.allstarapps.weathernerd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=958363882">958363882</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-nerd-forecasts-radar/id958363882?mt=8&uo=4">https://itunes.apple.com/us/app/weather-nerd-forecasts-radar/id958363882?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** All Star Apps, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/all-star-apps/id958363881?uo=4>© All Star Apps</a>
**Supported Devices:** iPadFourthGen4G, iPadMini4G, iPhone6, iPodTouchFifthGen, iPadMini, iPhone5c, iPhone5, iPhone6Plus, iPhone4S, iPadThirdGen, iPadFourthGen, iPad2Wifi, iPadThirdGen4G, iPhone5s, iPodTouchSixthGen, iPad23G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/ec/62/7b/ec627bbd-22da-2bee-d3ab-2614b5b4c712/mzl.akgosycn.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8893182/5affc076-3386-11e5-9566-d155927d9bd5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8893182/5affc076-3386-11e5-9566-d155927d9bd5.png)
https://cloud.githubusercontent.com/assets/2068130/8893182/5affc076-3386-11e5-9566-d155927d9bd5.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8893183/6b37628c-3386-11e5-9ebf-800e4dbad2c3.png
