### ISSUE TITLE
Mint Bills & Money

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6108]
**App Name:** Mint Bills & Money
**Bundle ID:** com.pageonce.ionce
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=285056092">285056092</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mint-bills-money/id285056092?mt=8&uo=4">https://itunes.apple.com/us/app/mint-bills-money/id285056092?mt=8&uo=4</a>
**App Version:** 8.21
**Seller:** Intuit Mint Bills, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/intuit-mint-bills-inc./id285056095?uo=4>© Intuit Mint Bills, Inc.</a>
**Supported Devices:** iPodTouchSixthGen, iPhone5s, iPadThirdGen, iPhone6Plus, iPhone5, iPadFourthGen, iPhone4, iPad2Wifi, iPadMini4G, iPhone5c, iPadMini, iPad23G, iPhone6, iPadThirdGen4G, iPadFourthGen4G, iPhone4S, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/d7/b1/86/d7b18628-bfc4-1297-1513-0f0918574a79/mzl.rdwmfhul.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8893067/020bf68e-3380-11e5-9700-08860e869bbb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8893067/020bf68e-3380-11e5-9700-08860e869bbb.png)
https://cloud.githubusercontent.com/assets/2068130/8893067/020bf68e-3380-11e5-9700-08860e869bbb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8893068/13fa0ac0-3380-11e5-950d-97a8e65749e2.png
