### ISSUE TITLE
Weather Underground: Forecasts, Interactive Radar, and Weather Alerts

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6109]
**App Name:** Weather Underground: Forecasts, Interactive Radar, and Weather Alerts
**Bundle ID:** com.wunderground.weatherunderground
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=486154808">486154808</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-underground-forecasts/id486154808?mt=8&uo=4">https://itunes.apple.com/us/app/weather-underground-forecasts/id486154808?mt=8&uo=4</a>
**App Version:** 5.0.1
**Seller:** Weather Underground, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/weather-underground-llc/id284699897?uo=4>© Weather Underground, LLC</a>
**Supported Devices:** iPhone6Plus, iPodTouchFifthGen, iPhone5c, iPhone5s, iPadThirdGen, iPodTouchSixthGen, iPhone5, iPad23G, iPhone4S, iPadMini, iPad2Wifi, iPadFourthGen, iPadFourthGen4G, iPadMini4G, iPhone6, iPadThirdGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple2/v4/37/dc/f0/37dcf0c9-e5d1-6be4-a8c2-b84a87dcfb9b/mzl.xxzirtmx.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8894789/8dadb522-33c3-11e5-8915-93de39523faa.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8894789/8dadb522-33c3-11e5-8915-93de39523faa.png)
https://cloud.githubusercontent.com/assets/10730122/8894789/8dadb522-33c3-11e5-8915-93de39523faa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8894788/8a7c9e2c-33c3-11e5-97e4-2e7ffe5f44ee.png

**Comment by l8er4now** [comment]
Just an FYI, http://glasklarthd.dreamnet.at/ still shows the old icon, not sure if that still impacts the master file.

**Comment by dreamnet** [comment]
@l8er4now Hit refresh in your browser - and no, this will not impact the master.
