### ISSUE TITLE
Foreceipt Receipt Manager - Daily Expense & Incomes Tracker, Personal Financial Planning on google drive

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6112]
**App Name:** Foreceipt Receipt Manager - Daily Expense & Incomes Tracker, Personal Financial Planning on google drive
**Bundle ID:** com.relayin.foreceipt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=721048897">721048897</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/foreceipt-receipt-manager/id721048897?mt=8&uo=4">https://itunes.apple.com/us/app/foreceipt-receipt-manager/id721048897?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Relayin Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/relayin-corporation/id490455559?uo=4>© Relayin Corporation</a>
**Supported Devices:** iPhone5, iPhone4, iPadFourthGen4G, iPodTouchSixthGen, iPadThirdGen, iPhone6, iPadMini4G, iPhone5c, iPhone5s, iPhone6Plus, iPodTouchFifthGen, iPadMini, iPadFourthGen, iPhone4S, iPad23G, iPadThirdGen4G, iPad2Wifi
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/a3/29/6d/a3296d61-27d8-9a1e-d40b-c5fc8c5640ed/mzl.kktmxbax.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8896083/cbd05166-33f0-11e5-8e0f-05c87b0533e0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8896083/cbd05166-33f0-11e5-8e0f-05c87b0533e0.png)
https://cloud.githubusercontent.com/assets/2068130/8896083/cbd05166-33f0-11e5-8e0f-05c87b0533e0.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8896084/dd8526b6-33f0-11e5-9422-8a3190f6ddc2.png
