### ISSUE TITLE
Olympic Air

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6114]
**App Name:** Olympic Air
**Bundle ID:** gr.forthnet.OlympicAir
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382789725">382789725</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/olympic-air/id382789725?mt=8&uo=4">https://itunes.apple.com/us/app/olympic-air/id382789725?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** OLYMPIC AIR S.A. AIR TRANSPORTS
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/olympic-air/id665556991?uo=4>© Olympic Air</a>
**Supported Devices:** iPhone-3GS, iPodTouchSixthGen, iPodTouchFourthGen, iPhone5, iPadMini4G, iPhone6, iPadFourthGen4G, iPhone4, iPad2Wifi, iPhone4S, iPhone5s, iPhone5c, iPadThirdGen, iPodTouchFifthGen, iPhone6Plus, iPad23G, iPadThirdGen4G, iPadFourthGen, iPadMini
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/18/d8/d2/18d8d2f4-e065-22a8-4a92-027f553abd7e/mzl.lmtwyekp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8924166/f20bdd4a-34fa-11e5-8212-d29cba0731cb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8924166/f20bdd4a-34fa-11e5-8212-d29cba0731cb.png)
https://cloud.githubusercontent.com/assets/2068130/8924166/f20bdd4a-34fa-11e5-8212-d29cba0731cb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8924172/01914f52-34fb-11e5-88dd-5f3b80debdb0.png
