### ISSUE TITLE
Aegean Airlines

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6115]
**App Name:** Aegean Airlines
**Bundle ID:** com.aegean.aegean2011
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=470826821">470826821</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aegean-airlines/id470826821?mt=8&uo=4">https://itunes.apple.com/us/app/aegean-airlines/id470826821?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Aegean Airlines S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/aegean-airlines-s.a./id470489029?uo=4>© Aegean Airlines S.A.</a>
**Supported Devices:** iPadFourthGen4G, iPodTouchSixthGen, iPhone5s, iPadFourthGen, iPad23G, iPadMini, iPhone5c, iPhone6Plus, iPodTouchFourthGen, iPhone5, iPhone6, iPadThirdGen4G, iPhone-3GS, iPadThirdGen, iPadMini4G, iPhone4S, iPad2Wifi, iPhone4, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple3/v4/ed/16/75/ed16754e-d43e-6242-1df5-677e605b0688/mzl.hlkwkytf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8896162/c58774d0-33f3-11e5-8a51-457d3f016145.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8896162/c58774d0-33f3-11e5-8a51-457d3f016145.png)
https://cloud.githubusercontent.com/assets/2068130/8896162/c58774d0-33f3-11e5-8a51-457d3f016145.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8896165/d3f97e50-33f3-11e5-9ff2-992d78ce0cca.png
