### ISSUE TITLE
SourceFed

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6117]
**App Name:** SourceFed
**Bundle ID:** com.geekutils.SourceFed
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=777341974">777341974</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sourcefed/id777341974?mt=8&uo=4">https://itunes.apple.com/us/app/sourcefed/id777341974?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Revision3
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/discovery-digital-networks/id723938886?uo=4>© Discovery Digital Networks</a>
**Supported Devices:** iPadFourthGen4G, iPodTouchFifthGen, iPad2Wifi, iPhone4S, iPhone6Plus, iPadThirdGen4G, iPhone4, iPhone5c, iPad23G, iPhone6, iPadMini4G, iPadFourthGen, iPhone5, iPodTouchSixthGen, iPadThirdGen, iPhone5s, iPadMini
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/05/56/52/05565234-6022-7131-633a-728b04dadfe3/mzl.sqnrhfca.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8924559/3bfd9750-34ff-11e5-81a2-eea301699adf.png)

**Comment by Trubbel** [comment]
Leaving this for someone else, not sure what to make of it.

**Comment by dreamnet** [comment]
I suggest something like this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8924559/3bfd9750-34ff-11e5-81a2-eea301699adf.png)
https://cloud.githubusercontent.com/assets/2068130/8924559/3bfd9750-34ff-11e5-81a2-eea301699adf.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8924566/4c0b916a-34ff-11e5-9c3d-1e09bd74f901.png

**Comment by Trubbel** [comment]
@dreamnet Agreed.
