### ISSUE TITLE
International SOS Assistance App

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6119]
**App Name:** International SOS Assistance App
**Bundle ID:** com.internationalsos.membership.isos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465662561">465662561</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/international-sos-assistance/id465662561?mt=8&uo=4">https://itunes.apple.com/us/app/international-sos-assistance/id465662561?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** International SOS Assistance, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/international-sos-assistance/id465662564?uo=4>© International SOS Assistance, Inc.</a>
**Supported Devices:** iPhone5, iPhone4S, iPad2Wifi, iPhone5c, iPhone4, iPadThirdGen, iPhone6, iPodTouchFourthGen, iPhone6Plus, iPodTouchFifthGen, iPadFourthGen, iPad23G, iPodTouchSixthGen, iPhone-3GS, iPadMini, iPhone5s, iPadThirdGen4G, iPadMini4G, iPadFourthGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple3/v4/6d/5f/37/6d5f3744-3168-7a89-ddd1-a1f9779c215d/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8992259/dbd3175a-36fd-11e5-8384-5d5372597c0a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8992259/dbd3175a-36fd-11e5-8384-5d5372597c0a.png)
https://cloud.githubusercontent.com/assets/2068130/8992259/dbd3175a-36fd-11e5-8384-5d5372597c0a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8992270/eada3d1e-36fd-11e5-8818-a11c48b67111.png
