### ISSUE TITLE
Hopster: Kids TV Shows and Educational Games

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6122]
**App Name:** Hopster: Kids TV Shows and Educational Games
**Bundle ID:** tv.platomedia.hopsterapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=689165391">689165391</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/hopster-kids-tv-shows-educational/id689165391?mt=8&uo=4">https://itunes.apple.com/gb/app/hopster-kids-tv-shows-educational/id689165391?mt=8&uo=4</a>
**App Version:** 2.1.22
**Seller:** Plato Media Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/artist/hopster/id689165394?uo=4>© Hopster</a>
**Supported Devices:** iPodTouchFifthGen, iPadFourthGen4G, iPhone4, iPadThirdGen4G, iPodTouchFourthGen, iPhone6Plus, iPadThirdGen, iPhone5s, iPhone5c, iPadFourthGen, iPodTouchSixthGen, iPad2Wifi, iPhone4S, iPhone6, iPhone5, iPad23G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/7f/48/12/7f4812da-7089-3d62-8634-3c537ba29d53/mzl.urqrrzhc.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8991383/96c21d82-36f8-11e5-8553-0d9895edd051.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8991383/96c21d82-36f8-11e5-8553-0d9895edd051.png)
https://cloud.githubusercontent.com/assets/2068130/8991383/96c21d82-36f8-11e5-8553-0d9895edd051.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8991390/a6364e14-36f8-11e5-85d3-80fc9dbdfb95.png

**Comment by Trubbel** [comment]
@dreamnet :+1:
