### ISSUE TITLE
Triposo

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6124]
**App Name:** Triposo
**Bundle ID:** com.triposo.worldguide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467053028">467053028</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/triposo/id467053028?mt=8&uo=4">https://itunes.apple.com/us/app/triposo/id467053028?mt=8&uo=4</a>
**App Version:** 4.8.1
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPhone4, iPadThirdGen, iPhone4S, iPhone5c, iPadThirdGen4G, iPadMini4G, iPhone6Plus, iPadFourthGen, iPodTouchSixthGen, iPhone6, iPadFourthGen4G, iPadMini, iPad23G, iPad2Wifi, iPhone5s, iPodTouchFifthGen, iPhone5
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/45/23/ca/4523ca1e-f4de-3f14-2eb1-4a08c87a57c3/mzl.hhpusagc.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)
https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8971983/04fa70b8-3656-11e5-991e-0169cc50e885.png

**Comment by dreamnet** [comment]
...I'm counting 186 apps from [this developer](https://itunes.apple.com/us/artist/triposo-inc/id415611465) with the same icon... ärks... :tired_face:
