### ISSUE TITLE
Angry Birds 2

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6126]
**App Name:** Angry Birds 2
**Bundle ID:** com.rovio.baba
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=880047117">880047117</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds-2/id880047117?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds-2/id880047117?mt=8&uo=4</a>
**App Version:** 2.9.0
**Seller:** Rovio Entertainment Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rovio-entertainment-ltd/id298910979?uo=4>© Rovio Entertainment Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/17/ce/68/17ce686a-d2f6-c63e-d3ab-a9ce7611578b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18983976/33e652b6-86f0-11e6-8876-5933115c005a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8985291/ca378bb0-36d6-11e5-8954-ba33889343ca.png)
https://cloud.githubusercontent.com/assets/2068130/8985291/ca378bb0-36d6-11e5-8954-ba33889343ca.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8985304/d9e99300-36d6-11e5-9228-6a9816fdb7a8.png

**Comment by LaCh0uine** [comment]
@dreamnet awesome thank you :)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by dreamnet** [comment]
Already in [the repo](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.rovio.baba-large.png). No action needed.

**Comment by LaCh0uine** [comment]
@dreamnet very old icon need update ;)

**Comment by dreamnet** [comment]
Ah, the Artwork has changed... @Anuskuss just mentioned that the icon needs an update for -large method...

**Comment by LaCh0uine** [comment]
@dreamnet anuskuss just repeat the same message;)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18964309/9bf73514-8678-11e6-8d39-95f5a019169f.png)
https://cloud.githubusercontent.com/assets/20930745/18964309/9bf73514-8678-11e6-8d39-95f5a019169f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18964355/d622bf4c-8678-11e6-848f-962b1d95d9a8.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Not bad, but I think we shold go more in the direction of #2172... especially with the eyes and the brows.

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... ok ,,, i will change it

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18983976/33e652b6-86f0-11e6-8876-5933115c005a.png)
https://cloud.githubusercontent.com/assets/20930745/18983976/33e652b6-86f0-11e6-8876-5933115c005a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18984001/4b4262ba-86f0-11e6-8528-eafdf304ef36.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yeah, great! :+1:
