### ISSUE TITLE
One More Dash

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6127]
**App Name:** One More Dash
**Bundle ID:** com.smgstudio.dash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=985923564">985923564</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/one-more-dash/id985923564?mt=8&uo=4">https://itunes.apple.com/us/app/one-more-dash/id985923564?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** SMG STUDIO PTY LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/smg-studio/id832131501?uo=4>© SMG Studio</a>
**Supported Devices:** iPad2Wifi, iPhone6, iPadMini, iPadThirdGen4G, iPadMini4G, iPodTouchFifthGen, iPhone5c, iPhone5, iPhone4S, iPhone5s, iPadFourthGen, iPhone4, iPad23G, iPodTouchSixthGen, iPhone6Plus, iPadFourthGen4G, iPadThirdGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/cd/be/49/cdbe4923-ac02-8fe2-7a12-ec252fec5a32/mzl.qlkoxyuy.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8991918/d021e226-36fb-11e5-9913-5a9987938768.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8991918/d021e226-36fb-11e5-9913-5a9987938768.png)
https://cloud.githubusercontent.com/assets/2068130/8991918/d021e226-36fb-11e5-9913-5a9987938768.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8991929/df8aa068-36fb-11e5-9ca5-0d53e754a004.png

**Comment by LaCh0uine** [comment]
@dreamnet awesome thank you :)
