### ISSUE TITLE
One More Line

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6128]
**App Name:** One More Line
**Bundle ID:** com.smgstudio.onemoreline
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914433115">914433115</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/one-more-line/id914433115?mt=8&uo=4">https://itunes.apple.com/us/app/one-more-line/id914433115?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** SMG STUDIO PTY LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/smg-studio/id832131501?uo=4>© SMG Studio</a>
**Supported Devices:** iPodTouchFourthGen, iPadMini, iPhone-3GS, iPodTouchFifthGen, iPhone4S, iPodTouchSixthGen, iPadMini4G, iPhone5, iPadFourthGen, iPad2Wifi, iPadFourthGen4G, iPadThirdGen4G, iPhone6, iPad23G, iPhone6Plus, iPhone4, iPhone5s, iPadThirdGen, iPhone5c
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/c9/3a/39/c93a3981-63b4-4ab5-18e7-10db26a62550/mzl.bvpglncr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8991632/178576fc-36fa-11e5-8051-a85cde6a4a37.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8991632/178576fc-36fa-11e5-8051-a85cde6a4a37.png)
https://cloud.githubusercontent.com/assets/2068130/8991632/178576fc-36fa-11e5-8051-a85cde6a4a37.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8991643/26d2f4cc-36fa-11e5-928b-d15d5c3ccb55.png

**Comment by LaCh0uine** [comment]
@dreamnet awesome thank you :)
