### ISSUE TITLE
Spaceteam

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#613]
**App Name:** Spaceteam
**Bundle ID:** com.sleepingbeastgames.spaceteam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570510529">570510529</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spaceteam/id570510529?mt=8&uo=4">https://itunes.apple.com/us/app/spaceteam/id570510529?mt=8&uo=4</a>
**App Version:** 2.5.3
**Seller:** Henry Smith
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/henry-smith/id570510532?uo=4">© Henry Smith</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/62/92/13/629213f2-8a6e-94b9-3d8e-a682dea9030b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32403069-13153b06-c132-11e7-8a99-c6b5c20bb3a8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32403069-13153b06-c132-11e7-8a99-c6b5c20bb3a8.png)
https://user-images.githubusercontent.com/2068130/32403069-13153b06-c132-11e7-8a99-c6b5c20bb3a8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32403072-22698e22-c132-11e7-9c55-fd6f28424cc0.png
