### ISSUE TITLE
8fit Workouts & Meal Planner

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6134]
**App Name:** 8fit Workouts & Meal Planner
**Bundle ID:** com.8fit.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=866617777">866617777</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/8fit-workouts-meal-planner/id866617777?mt=8&uo=4">https://itunes.apple.com/us/app/8fit-workouts-meal-planner/id866617777?mt=8&uo=4</a>
**App Version:** 3.1.4
**Seller:** Urbanite Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/urbanite-inc/id866617780?uo=4">© Urbanite Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/21/00/6a/21006a75-666d-2fb0-651b-d90f376dee80/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455267-f9c21116-3a75-11e8-83da-6b7a00327779.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8994597/c0dd918c-370c-11e5-9d11-456d6b4aa962.png)
https://cloud.githubusercontent.com/assets/10730122/8994597/c0dd918c-370c-11e5-9d11-456d6b4aa962.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8994595/bd49b8d4-370c-11e5-9790-b62dc1b8f028.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455267-f9c21116-3a75-11e8-83da-6b7a00327779.png)
https://user-images.githubusercontent.com/20930745/38455267-f9c21116-3a75-11e8-83da-6b7a00327779.png

Source:
https://user-images.githubusercontent.com/20930745/38455275-124002de-3a76-11e8-9ac1-35ab30af481a.png
