### ISSUE TITLE
Abs Workout - Daily Fitness

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6136]
**App Name:** Abs Workout - Daily Fitness
**Bundle ID:** com.passion4profession.8minabslvl1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426364250">426364250</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/abs-workout-daily-fitness/id426364250?mt=8&uo=4">https://itunes.apple.com/us/app/abs-workout-daily-fitness/id426364250?mt=8&uo=4</a>
**App Version:** 6.5.6
**Seller:** Passion4Profession Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/passion4profession-inc/id426364253?uo=4">© Passion4Profession Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple62/v4/37/42/3b/37423b7e-cb6a-6eaf-dc0b-113bef9c84c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455217-6baa42c2-3a75-11e8-9e83-499dfc92a0a1.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8994883/4e4efee2-370e-11e5-892d-6e4d00e1b7e7.png)
https://cloud.githubusercontent.com/assets/10730122/8994883/4e4efee2-370e-11e5-892d-6e4d00e1b7e7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8994881/4af4521a-370e-11e5-81c2-35505ce17e50.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455217-6baa42c2-3a75-11e8-9e83-499dfc92a0a1.png)
https://user-images.githubusercontent.com/20930745/38455217-6baa42c2-3a75-11e8-9e83-499dfc92a0a1.png

Source:
https://user-images.githubusercontent.com/20930745/38455227-7be20e72-3a75-11e8-81e5-5dca8a9aaf4f.png
