### ISSUE TITLE
Chest workout plan

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6137]
**App Name:** Chest workout plan
**Bundle ID:** net.p4p.Chest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=513715684">513715684</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/chest-workout-plan/id513715684?uo=4">https://apps.apple.com/us/app/chest-workout-plan/id513715684?uo=4</a>
**App Version:** 6.6.2
**Seller:** Passion4Profession Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/passion4profession-inc/id426364253?uo=4">© Passion4Profession Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/ec/5c/f2/ec5cf2cf-e237-a06d-fe45-885f044a67af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60373021-f30d7880-99fe-11e9-9d3d-ceed6c68b97d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8994963/d30356b0-370e-11e5-83a3-63a497c36529.png)
https://cloud.githubusercontent.com/assets/10730122/8994963/d30356b0-370e-11e5-83a3-63a497c36529.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8994961/cfd13318-370e-11e5-972f-f43a95f6b5ed.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60373021-f30d7880-99fe-11e9-9d3d-ceed6c68b97d.png)
https://user-images.githubusercontent.com/20930745/60373021-f30d7880-99fe-11e9-9d3d-ceed6c68b97d.png

Source:
https://user-images.githubusercontent.com/20930745/60373028-f6086900-99fe-11e9-9857-dfa5cc4febd2.png
