### ISSUE TITLE
Butt workout plan

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6138]
**App Name:** Butt workout plan
**Bundle ID:** net.p4p.Buttocks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=528570179">528570179</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/butt-workout-plan/id528570179?uo=4">https://apps.apple.com/us/app/butt-workout-plan/id528570179?uo=4</a>
**App Version:** 6.0.9
**Seller:** Passion4Profession Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/passion4profession-inc/id426364253?uo=4">© Passion4Profession Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/37/7b/cc/377bcc3a-09dd-2eb1-8ef0-1ca6a356e663/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981448-b3601e80-9603-11e9-9018-a172da2eabc1.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8995048/4c5b16e2-370f-11e5-9be2-8f75521885c6.png)
https://cloud.githubusercontent.com/assets/10730122/8995048/4c5b16e2-370f-11e5-9be2-8f75521885c6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8995043/49412316-370f-11e5-88c0-14957b66ffc2.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981448-b3601e80-9603-11e9-9018-a172da2eabc1.png)
https://user-images.githubusercontent.com/2068130/59981448-b3601e80-9603-11e9-9018-a172da2eabc1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59981457-c4109480-9603-11e9-9399-5e2edfc40d35.png
