### ISSUE TITLE
Grand Theft Auto: Vice City

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#614]
**App Name:** Grand Theft Auto: Vice City
**Bundle ID:** com.rockstargames.gta3vc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=578448682">578448682</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grand-theft-auto-vice-city/id578448682?mt=8&uo=4">https://itunes.apple.com/us/app/grand-theft-auto-vice-city/id578448682?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Rockstar Games, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rockstar-games/id330049731?uo=4>© Rockstar Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/21/68/aa/2168aa8d-861d-635b-0881-ccffa2448da9/mzl.zmfxxiiv.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10508265/5252e07c-7326-11e5-946e-b97f3f7457c3.png)

**Comment by Trubbel** [comment]
Updating the icon and source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10508265/5252e07c-7326-11e5-946e-b97f3f7457c3.png)
https://cloud.githubusercontent.com/assets/10730122/10508265/5252e07c-7326-11e5-946e-b97f3f7457c3.png

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10508274/605519e2-7326-11e5-9cc3-6780bbb0b64c.png)
https://cloud.githubusercontent.com/assets/10730122/10508274/605519e2-7326-11e5-9cc3-6780bbb0b64c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10508260/43c446c2-7326-11e5-9a76-bdf09f362d0d.png
