### ISSUE TITLE
Numerous — Life’s most important numbers available at a glance

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6141]
**App Name:** Numerous — Life’s most important numbers available at a glance
**Bundle ID:** com.numerousapp.Numerous
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=797642904">797642904</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/numerous-lifes-most-important/id797642904?mt=8&uo=4">https://itunes.apple.com/us/app/numerous-lifes-most-important/id797642904?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Numerous, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/numerous-inc/id797642907?uo=4>© Numerous, Inc</a>
**Supported Devices:** iPodTouchSixthGen, iPadFourthGen, iPadMini, iPhone5s, iPhone5, iPodTouchFifthGen, iPhone5c, iPad2Wifi, iPad23G, iPadThirdGen, iPadFourthGen4G, iPadMini4G, iPhone6, iPhone4S, iPhone6Plus, iPadThirdGen4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/3e/24/07/3e24074f-3333-f9b0-3355-144bf9cdf586/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9007282/7feec3a0-3755-11e5-9912-9797474faef9.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9007282/7feec3a0-3755-11e5-9912-9797474faef9.png)
https://cloud.githubusercontent.com/assets/3090247/9007282/7feec3a0-3755-11e5-9912-9797474faef9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9007283/7ff90a90-3755-11e5-9b4f-283641a176f6.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
