### ISSUE TITLE
Sundial - Sun & Moon Times and Alerts (Sunrise, Sunset, Moonrise, Moonset, Full Moon, and More)

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6142]
**App Name:** Sundial - Sun & Moon Times and Alerts (Sunrise, Sunset, Moonrise, Moonset, Full Moon, and More)
**Bundle ID:** com.tier9digital.sundial
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=976460540">976460540</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sundial-sun-moon-times-alerts/id976460540?mt=8&uo=4">https://itunes.apple.com/us/app/sundial-sun-moon-times-alerts/id976460540?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Tier 9 Digital LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tier-9-digital/id574834387?uo=4>© Tier 9 Digital</a>
**Supported Devices:** iPadMini, iPhone6, iPhone4S, iPadThirdGen4G, iPodTouchSixthGen, iPadThirdGen, iPodTouchFifthGen, iPadFourthGen4G, iPhone5c, iPadFourthGen, iPhone5, iPad2Wifi, iPadMini4G, iPad23G, iPhone5s, iPhone6Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/30/64/b2/3064b22b-1b55-b75d-4505-a3031d3c69e0/mzl.tzivahdl.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9014794/efaad390-37c4-11e5-93da-defb06a77fa0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9014794/efaad390-37c4-11e5-93da-defb06a77fa0.png)
https://cloud.githubusercontent.com/assets/2068130/9014794/efaad390-37c4-11e5-93da-defb06a77fa0.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9014805/fe5ab202-37c4-11e5-8b1d-b40d9da3c7af.png
