### ISSUE TITLE
Massachusetts Travel Guide by Triposo with Boston, Salem, Springfield and more!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6143]
**App Name:** Massachusetts Travel Guide by Triposo with Boston, Salem, Springfield and more!
**Bundle ID:** com.triposo.massachusetts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=624185169">624185169</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/massachusetts-travel-guide/id624185169?mt=8&uo=4">https://itunes.apple.com/us/app/massachusetts-travel-guide/id624185169?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPhone6, iPadThirdGen, iPhone4, iPadMini, iPodTouchSixthGen, iPadFourthGen4G, iPhone4S, iPodTouchFifthGen, iPhone5, iPhone6Plus, iPadFourthGen, iPhone5c, iPad2Wifi, iPad23G, iPadThirdGen4G, iPhone5s, iPadMini4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple4/v4/39/09/da/3909dada-4811-d923-c804-373ddff407a7/mzl.ygoufzat.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)
https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9006868/8c74c18c-3751-11e5-9af1-e29bbb911afe.png

**Comment by dreamnet** [comment]
Same icon as #6124.
