### ISSUE TITLE
New York Travel Guide by Triposo featuring Albany, Buffalo, New York City and more!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6144]
**App Name:** New York Travel Guide by Triposo featuring Albany, Buffalo, New York City and more!
**Bundle ID:** com.triposo.newyork
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=626130167">626130167</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-york-travel-guide-by-triposo/id626130167?mt=8&uo=4">https://itunes.apple.com/us/app/new-york-travel-guide-by-triposo/id626130167?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPodTouchFifthGen, iPadFourthGen4G, iPhone4, iPhone4S, iPadMini, iPad23G, iPhone5, iPadThirdGen, iPadThirdGen4G, iPhone5s, iPad2Wifi, iPhone6Plus, iPodTouchSixthGen, iPhone6, iPhone5c, iPadFourthGen, iPadMini4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple4/v4/8a/33/4f/8a334fa2-7521-2636-6cf0-8c70361d2d9f/mzl.ktnnimwn.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)
https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9006868/8c74c18c-3751-11e5-9af1-e29bbb911afe.png

**Comment by dreamnet** [comment]
Same icon as #6124.
