### ISSUE TITLE
Connecticut Travel Guide by Triposo

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6145]
**App Name:** Connecticut Travel Guide by Triposo
**Bundle ID:** com.triposo.connecticut
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=624002757">624002757</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/connecticut-travel-guide-by/id624002757?mt=8&uo=4">https://itunes.apple.com/us/app/connecticut-travel-guide-by/id624002757?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPhone5, iPhone4S, iPadFourthGen4G, iPodTouchFifthGen, iPhone6Plus, iPhone4, iPhone5c, iPhone5s, iPadMini4G, iPadThirdGen, iPodTouchSixthGen, iPadFourthGen, iPadMini, iPadThirdGen4G, iPad2Wifi, iPhone6, iPad23G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple4/v4/5e/c5/8e/5ec58e49-99a3-e361-b31f-3de1c216b314/mzl.ifxpydia.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)
https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9006868/8c74c18c-3751-11e5-9af1-e29bbb911afe.png

**Comment by dreamnet** [comment]
Same icon as #6124.
