### ISSUE TITLE
Vermont Travel Guide by Triposo featuring Burlingron, Montpelier, Brattleboro and more!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6146]
**App Name:** Vermont Travel Guide by Triposo featuring Burlingron, Montpelier, Brattleboro and more!
**Bundle ID:** com.triposo.vermont
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=626129426">626129426</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vermont-travel-guide-by-triposo/id626129426?mt=8&uo=4">https://itunes.apple.com/us/app/vermont-travel-guide-by-triposo/id626129426?mt=8&uo=4</a>
**App Version:** 4.8.1
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPadThirdGen4G, iPhone6Plus, iPhone4, iPadFourthGen4G, iPhone5, iPadThirdGen, iPhone5s, iPad2Wifi, iPhone4S, iPhone6, iPhone5c, iPad23G, iPadFourthGen, iPadMini, iPodTouchSixthGen, iPodTouchFifthGen, iPadMini4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple5/v4/88/95/a4/8895a42f-9ae8-3e74-64d0-8044ba998403/mzl.dtmsdkcb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)
https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9006868/8c74c18c-3751-11e5-9af1-e29bbb911afe.png

**Comment by dreamnet** [comment]
Same icon as #6124.
