### ISSUE TITLE
Greece Travel Guide by Triposo featuring Athens, Thessaloniki and much more!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6147]
**App Name:** Greece Travel Guide by Triposo featuring Athens, Thessaloniki and much more!
**Bundle ID:** com.triposo.greeceguide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=481656642">481656642</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/greece-travel-guide-by-triposo/id481656642?mt=8&uo=4">https://itunes.apple.com/us/app/greece-travel-guide-by-triposo/id481656642?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPhone4, iPadMini, iPhone5, iPadFourthGen, iPhone5c, iPadFourthGen4G, iPadMini4G, iPodTouchFifthGen, iPhone6Plus, iPad2Wifi, iPad23G, iPhone6, iPadThirdGen, iPodTouchSixthGen, iPhone4S, iPhone5s, iPadThirdGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/20/52/e5/2052e5a5-ad45-010d-6b55-161af7f48a3b/mzl.wvrjezdk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)
https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9006868/8c74c18c-3751-11e5-9af1-e29bbb911afe.png

**Comment by dreamnet** [comment]
Same icon as #6124.
