### ISSUE TITLE
Worms3

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6148]
**App Name:** Worms3
**Bundle ID:** com.team17.worms3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=596677177">596677177</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/worms3/id596677177?mt=8&uo=4">https://itunes.apple.com/us/app/worms3/id596677177?mt=8&uo=4</a>
**App Version:** 1.16
**Seller:** Team17 Software, Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/team17-software-ltd/id321369234?uo=4>© Team17 Software Ltd</a>
**Supported Devices:** iPadFourthGen, iPadWifi, iPodTouchThirdGen, iPad23G, iPodTouchFifthGen, iPad2Wifi, iPadMini, iPhone5, iPhone4, iPad3G, iPhone-3GS, iPadMini4G, iPhone6Plus, iPodTouchSixthGen, iPadThirdGen, iPhone5c, iPhone4S, iPadThirdGen4G, iPhone6, iPodTouchFourthGen, iPhone5s, iPadFourthGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/d2/31/f7/d231f7bb-1b5d-c212-ae29-cffbbc99736c/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9025573/317f2622-390a-11e5-87e3-aac245a1c9e8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9025573/317f2622-390a-11e5-87e3-aac245a1c9e8.png)
https://cloud.githubusercontent.com/assets/2068130/9025573/317f2622-390a-11e5-87e3-aac245a1c9e8.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9025576/40916c4c-390a-11e5-869e-b0a688ff2550.png
Hey, I am the only one here that is trying to fulfill some of the harder icon requests? Com on guys! :construction_worker:

**Comment by LaCh0uine** [comment]
@dreamnet i think yes .. But your are the best for hard one ;)
Thank you again

**Comment by LaCh0uine** [comment]
If you like this game is free for the week ...

**Comment by Trubbel** [comment]
@dreamnet I would, but I'm not on your level yet, haha. :smile:

**Comment by dreamnet** [comment]
@Trubbel Well, keep on trying! :+1:
