### ISSUE TITLE
Centrallo - Lists and Notes with Sharing

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6149]
**App Name:** Centrallo - Lists and Notes with Sharing
**Bundle ID:** com.centrallo.release
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=865110311">865110311</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/centrallo-lists-notes-sharing/id865110311?mt=8&uo=4">https://itunes.apple.com/us/app/centrallo-lists-notes-sharing/id865110311?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Centrallo LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/centrallo-llc/id853000973?uo=4>© Centrallo LLC</a>
**Supported Devices:** iPhone6, iPadMini4G, iPodTouchFifthGen, iPhone5c, iPhone4, iPadThirdGen, iPadMini, iPhone5s, iPad2Wifi, iPadFourthGen, iPad23G, iPhone5, iPhone6Plus, iPodTouchSixthGen, iPhone4S, iPadThirdGen4G, iPadFourthGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple5/v4/a5/a2/1e/a5a21ede-03ce-da87-49b8-b6d058f59c79/mzl.ljwlearb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9020742/f8e6d8e2-381d-11e5-9422-9f8ff5b024fd.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9019704/41bbd5fa-37f0-11e5-8308-63b030946ad6.png)
https://cloud.githubusercontent.com/assets/10730122/9019704/41bbd5fa-37f0-11e5-8308-63b030946ad6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9019700/3ec9958a-37f0-11e5-9bfa-cc25b4b36f07.png

**Comment by dreamnet** [comment]
Little correction:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9020742/f8e6d8e2-381d-11e5-9422-9f8ff5b024fd.png)
https://cloud.githubusercontent.com/assets/2068130/9020742/f8e6d8e2-381d-11e5-9422-9f8ff5b024fd.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9020743/0978cada-381e-11e5-92cf-18c8ad07afcc.png
