### ISSUE TITLE
Optimal Lineups for FanDuel

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6151]
**App Name:** Optimal Lineups for FanDuel
**Bundle ID:** com.socialzoid.FanDuelOptimalLineups
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=933561226">933561226</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/optimal-lineups-for-fanduel/id933561226?mt=8&uo=4">https://itunes.apple.com/us/app/optimal-lineups-for-fanduel/id933561226?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Fantasy Sports Company, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/fantasy-sports-company-llc/id958037739?uo=4>© Fantasy Sports Company, LLC</a>
**Supported Devices:** iPhone4S, iPad2Wifi, iPad23G, iPhone6, iPadMini, iPodTouchSixthGen, iPadThirdGen, iPhone4, iPadMini4G, iPadFourthGen, iPadFourthGen4G, iPadThirdGen4G, iPhone5c, iPhone6Plus, iPhone5s, iPhone5, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/15/01/a4/1501a4fd-aa3c-710f-6b5f-2f0f5ecd4996/mzl.uldalmpx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9023288/5cdb8c4a-3895-11e5-9c59-c923c559f118.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9023288/5cdb8c4a-3895-11e5-9c59-c923c559f118.png)
https://cloud.githubusercontent.com/assets/2068130/9023288/5cdb8c4a-3895-11e5-9c59-c923c559f118.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9023290/6c6e873e-3895-11e5-991a-2f9988237b12.png
