### ISSUE TITLE
DJI GO

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6152]
**App Name:** DJI GO
**Bundle ID:** com.dji.pilot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943780750">943780750</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dji-go/id943780750?mt=8&uo=4">https://itunes.apple.com/us/app/dji-go/id943780750?mt=8&uo=4</a>
**App Version:** 2.4.0
**Seller:** SZ DJI TECHNOLOGY CO., LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dji/id599957686?uo=4>© DJI</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/a3/17/13/a317133e-d3db-5a17-f69d-cf1495589dfb/mzl.gbzymjwy.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9026626/45ebb040-3936-11e5-8b0b-29e1fe4b7671.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9026623/34e793c2-3936-11e5-9497-c3538a2100ca.png)
https://cloud.githubusercontent.com/assets/10730122/9026623/34e793c2-3936-11e5-9497-c3538a2100ca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9026620/32b744da-3936-11e5-93a7-bc48130a3643.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9026626/45ebb040-3936-11e5-8b0b-29e1fe4b7671.png)
https://cloud.githubusercontent.com/assets/10730122/9026626/45ebb040-3936-11e5-8b0b-29e1fe4b7671.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9026624/42b403be-3936-11e5-9d0e-26f1eb75aebc.png

**Comment by dreamnet** [comment]
@Trubbel Taking your first icon, because of the other DJI apps. :+1:

**Comment by Teekzilla** [comment]
The airplane is no longer in their logo.
Just a heads up, if you wanted to update the icon?

In fact it's similar to @Trubbel's second icon.

**Comment by ivanov007** [comment]
@Teekzilla right, I've updated it, and took the one from @Trubbel :+1:
