### ISSUE TITLE
Wallax - The Best Wallpaper App

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6153]
**App Name:** Wallax - The Best Wallpaper App
**Bundle ID:** com.brijit.auxsheelia.Wallax
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=722262021">722262021</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wallax-the-best-wallpaper-app/id722262021?mt=8&uo=4">https://itunes.apple.com/us/app/wallax-the-best-wallpaper-app/id722262021?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** BRIJIT SHEELIA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/brijit-sheelia/id629790554?uo=4>© BRIJIT SHEELIA</a>
**Supported Devices:** iPadMini, iPhone5c, iPadThirdGen4G, iPadFourthGen4G, iPadFourthGen, iPad2Wifi, iPadMini4G, iPhone4S, iPhone5, iPhone5s, iPadThirdGen, iPad23G, iPhone6, iPodTouchFifthGen, iPhone4, iPodTouchSixthGen, iPhone6Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple1/v4/7d/d3/d3/7dd3d3f8-d6c7-307f-0915-9c3fd1c48890/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9232917/9017f10e-4130-11e5-8838-259442a39c4a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9232917/9017f10e-4130-11e5-8838-259442a39c4a.png)
https://cloud.githubusercontent.com/assets/2068130/9232917/9017f10e-4130-11e5-8838-259442a39c4a.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9232929/9ece95a4-4130-11e5-8f78-1f915eed1cb8.png
