### ISSUE TITLE
Google Spotlight Stories

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6154]
**App Name:** Google Spotlight Stories
**Bundle ID:** com.google.atapspotlightstories
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=974739483">974739483</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-spotlight-stories/id974739483?mt=8&uo=4">https://itunes.apple.com/us/app/google-spotlight-stories/id974739483?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone6Plus, iPodTouchSixthGen, iPhone6, iPhone5s
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple4/v4/db/0c/db/db0cdb43-06cf-06d6-63bd-df4f63dfb094/mzl.yzrfsaxf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9232180/86675950-412c-11e5-82f9-f6bbf6b6c346.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9223958/1965a226-40ff-11e5-8239-c6c1e01c5dbb.png)
https://cloud.githubusercontent.com/assets/2068130/9223958/1965a226-40ff-11e5-8239-c6c1e01c5dbb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9223970/277d5f52-40ff-11e5-9a7a-9b5ec097abda.png

**Comment by Trubbel** [comment]
@dreamnet I like it!
