### ISSUE TITLE
Canal Football App

### ISSUE THREAD

**Issue by Ykkris** [glasklart/hd#6155]
**App Name:** Canal Football App
**Bundle ID:** com.canalplus.canalfootballclub.prod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542610274">542610274</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/canal-football-app/id542610274?mt=8&uo=4">https://itunes.apple.com/fr/app/canal-football-app/id542610274?mt=8&uo=4</a>
**App Version:** 8.1.4
**Seller:** GROUPE CANAL+
**Developer:** <a target="_blank" href=https://itunes.apple.com/fr/artist/groupe-canal+/id694580819?uo=4>© GROUPE CANAL+</a>
**Supported Devices:** iPhone4S, iPadFourthGen4G, iPad2Wifi, iPadThirdGen4G, iPad23G, iPhone5s, iPhone5, iPadMini, iPodTouchSixthGen, iPadThirdGen, iPhone4, iPhone5c, iPhone6, iPadMini4G, iPodTouchFifthGen, iPhone6Plus, iPadFourthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/e0/9a/78/e09a785a-7863-b35e-9bf1-d6aafa6153a8/mzl.wkxrvyum.png" width="150" height="150" />
**Accepted Artwork:**
![com canalplus canalfootballclub prod](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9048352/d20db124-3a38-11e5-879f-c8fc1efc1f6c.png)

**Comment by Ykkris** [comment]
I've made my own glasklart style
![com canalplus canalfootballclub prod](https://cloud.githubusercontent.com/assets/13631976/9048320/925b8a42-3a38-11e5-9f67-bf29d295d7ff.png)

**Comment by Ykkris** [comment]
I've made my own glasklart icon
![com canalplus canalfootballclub prod](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9048352/d20db124-3a38-11e5-879f-c8fc1efc1f6c.png)

**Comment by dreamnet** [comment]
@Ykkris Yes, and it looks very good - but we need the icon source file as described [here](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources). Good work anyway! :+1:

**Comment by Ykkris** [comment]
I've added the source on my first comment :)

**Comment by dreamnet** [comment]
@Ykkris Source looks also good - Congratulations, you contributed your first? Glasklart icon! Just one thing: For future contributions, please put a link to the finished icon without the preview also, I correct you post above.

**Comment by Ykkris** [comment]
Yes it's my first contribution ^^

**Comment by dreamnet** [comment]
@Ykkris ...ah, and if you want to be on our [contributors list](https://github.com/glasklart/hd/graphs/contributors), you need to add a public mailaddress to your Github account.

**Comment by Ykkris** [comment]
Ok I did it :)

**Comment by dreamnet** [comment]
@Ykkris Perfect, thanks!
