### ISSUE TITLE
OM (Officiel)

### ISSUE THREAD

**Issue by Ykkris** [glasklart/hd#6156]
**App Name:** OM (Officiel)
**Bundle ID:** com.c4mprod.OM
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=346179130">346179130</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/om-officiel/id346179130?mt=8&uo=4">https://itunes.apple.com/us/app/om-officiel/id346179130?mt=8&uo=4</a>
**App Version:** 4.5.1
**Seller:** OM Medias
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/om-medias/id346179133?uo=4>© OM Medias</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen, iPhone4S, iPadMini, iPhone4, iPadFourthGen4G, iPhone6Plus, iPhone5s, iPadMini4G, iPodTouchSixthGen, iPadThirdGen4G, iPhone6, iPhone5c, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPad23G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/71/0c/a5/710ca51a-10dc-63fa-57fb-99aa4d552902/mzl.ugiwcoih.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9072715/0eeffc9a-3afd-11e5-9b05-5da630a114ea.png)

**Comment by Ykkris** [comment]
Glasklart style

![com c4mprod om](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9048840/91c8465c-3a3c-11e5-8c8f-bd591ea26073.png)

Source : 
https://cloud.githubusercontent.com/assets/13631976/9048847/a0c1c12e-3a3c-11e5-83da-54a9f7ad3f22.png

**Comment by dreamnet** [comment]
@Ykkris Looks fine, but this icon should fill the wohle 78x78px area in the Glasklart icon.

**Comment by dreamnet** [comment]
@Ykkris I mean like this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9072715/0eeffc9a-3afd-11e5-9b05-5da630a114ea.png)
https://cloud.githubusercontent.com/assets/2068130/9072715/0eeffc9a-3afd-11e5-9b05-5da630a114ea.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9072722/1d511b98-3afd-11e5-8244-7ee55388b5f7.png
You are getting credits for this icon anyway. :+1:
