### ISSUE TITLE
Upsie

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6157]
**App Name:** Upsie
**Bundle ID:** com.upsie.Upsie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935434696">935434696</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/upsie/id935434696?mt=8&uo=4">https://itunes.apple.com/us/app/upsie/id935434696?mt=8&uo=4</a>
**App Version:** 1.9.1
**Seller:** Upsie, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/upsie-llc/id935434695?uo=4>© Upsie, LLC</a>
**Supported Devices:** iPodTouchFifthGen, iPadMini, iPad23G, iPadThirdGen, iPad2Wifi, iPhone6, iPadThirdGen4G, iPadFourthGen4G, iPhone5s, iPhone5, iPhone4S, iPadFourthGen, iPhone5c, iPhone4, iPodTouchSixthGen, iPhone6Plus, iPadMini4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple7/v4/e7/c8/68/e7c868f3-c1be-6da3-b565-f400898f27a9/mzl.pnhvfkkm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9072904/338dfd94-3afe-11e5-90a7-bb10bf4831b7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9072904/338dfd94-3afe-11e5-90a7-bb10bf4831b7.png)
https://cloud.githubusercontent.com/assets/2068130/9072904/338dfd94-3afe-11e5-90a7-bb10bf4831b7.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9072914/42686638-3afe-11e5-87b7-60ac224b6ec4.png
