### ISSUE TITLE
Angry Birds Rio

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#616]
**App Name:** Angry Birds Rio
**Bundle ID:** com.rovio.angrybirdsrio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=420635506">420635506</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds-rio/id420635506?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds-rio/id420635506?mt=8&uo=4</a>
**App Version:** 2.6.2
**Seller:** Rovio Entertainment Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rovio-entertainment-ltd/id298910979?uo=4>© Rovio Entertainment Ltd</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/08/c7/82/08c782e0-97b5-ebca-68a5-910307a2fc25/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18990502/9d02e8dc-8712-11e6-9722-45ebc52f6f21.png)

**Comment by LaCh0uine** [comment]
don't work on 5.1 need update 
thank you

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18990502/9d02e8dc-8712-11e6-9722-45ebc52f6f21.png)
https://cloud.githubusercontent.com/assets/20930745/18990502/9d02e8dc-8712-11e6-9722-45ebc52f6f21.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18990521/d31a3948-8712-11e6-992a-708ad60049d4.png
