### ISSUE TITLE
iRec Screen Recorder

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#6160]
**App Name:** iRec Screen Recorder
**Bundle ID:** com.adhoc.iRec
**Version:** 1.2.1
**iTunes ID:** none (Cydia app)
**Original Artwork:**
![irec](https://cloud.githubusercontent.com/assets/3600371/9094438/7d77fe20-3bba-11e5-920a-67f040e798dc.jpg)
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9122537/00e98eca-3c8a-11e5-872d-390fdb76d50d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9122537/00e98eca-3c8a-11e5-872d-390fdb76d50d.png)
https://cloud.githubusercontent.com/assets/2068130/9122537/00e98eca-3c8a-11e5-872d-390fdb76d50d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9122547/0ee25340-3c8a-11e5-8c87-0da0492af854.png
