### ISSUE TITLE
Growth: charts for baby and child tracking

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6161]
**App Name:** Growth: charts for baby and child tracking
**Bundle ID:** com.clafou.growth.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446639811">446639811</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/growth-charts-for-baby-child/id446639811?mt=8&uo=4">https://itunes.apple.com/us/app/growth-charts-for-baby-child/id446639811?mt=8&uo=4</a>
**App Version:** 1.17
**Seller:** Sebastien Molines
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/clafou-apps/id424537553?uo=4>© Clafou Apps</a>
**Supported Devices:** iPad23G, iPhone6Plus, iPadFourthGen4G, iPadThirdGen, iPad2Wifi, iPadMini4G, iPhone4, iPodTouchFifthGen, iPadFourthGen, iPhone5, iPhone4S, iPadMini, iPadThirdGen4G, iPhone5c, iPodTouchSixthGen, iPhone5s, iPhone6
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/e9/3b/81/e93b8144-9bcc-0a19-de1b-5f94826f2115/mzl.gjplsbzk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9234111/251e6408-4137-11e5-904c-bb31688737c2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9234111/251e6408-4137-11e5-904c-bb31688737c2.png)
https://cloud.githubusercontent.com/assets/2068130/9234111/251e6408-4137-11e5-904c-bb31688737c2.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9234122/337bd6ca-4137-11e5-91f7-b38272e3e0c2.png
