### ISSUE TITLE
Puzzle Cards

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6162]
**App Name:** Puzzle Cards
**Bundle ID:** uk.mibaldwin.Puzzle-Cards
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923867667">923867667</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/puzzle-cards/id923867667?mt=8&uo=4">https://itunes.apple.com/us/app/puzzle-cards/id923867667?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Marc Baldwin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/marc-baldwin/id640084769?uo=4>© Marc Baldwin</a>
**Supported Devices:** iPad2Wifi, iPadFourthGen, iPadThirdGen, iPhone4S, iPodTouchSixthGen, iPadThirdGen4G, iPhone5s, iPadMini4G, iPhone6Plus, iPhone5c, iPadFourthGen4G, iPhone5, iPad23G, iPodTouchFifthGen, iPadMini, iPhone6
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/43/fd/51/43fd51bd-ee05-bd18-35c5-f0a1572b1488/mzl.ehmjiork.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9122750/614ef24a-3c8b-11e5-9251-4303917ae32b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9122750/614ef24a-3c8b-11e5-9251-4303917ae32b.png)
https://cloud.githubusercontent.com/assets/2068130/9122750/614ef24a-3c8b-11e5-9251-4303917ae32b.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9122769/7286baca-3c8b-11e5-992e-62bb319a60df.png
