### ISSUE TITLE
Age of Empires: Castle Siege

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6163]
**App Name:** Age of Empires: Castle Siege
**Bundle ID:** com.microsoft.AgeOfEmpiresCastleSiege
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=977905957">977905957</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/age-of-empires-castle-siege/id977905957?mt=8&uo=4">https://itunes.apple.com/us/app/age-of-empires-castle-siege/id977905957?mt=8&uo=4</a>
**App Version:** 1.10
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPhone4, iPhone6, iPhone5s, iPadThirdGen, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPhone5c, iPhone6Plus, iPadMini, iPhone4S, iPodTouchSixthGen, iPad2Wifi, iPadFourthGen4G, iPadMini4G, iPadThirdGen4G, iPad23G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/4c/63/64/4c63646b-3ee8-caa8-22e6-fb3782bf5bef/mzl.hkjdrmiw.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9124001/b150dc74-3c93-11e5-9441-0c19dae88fec.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9124001/b150dc74-3c93-11e5-9441-0c19dae88fec.png)
https://cloud.githubusercontent.com/assets/2068130/9124001/b150dc74-3c93-11e5-9441-0c19dae88fec.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9124008/bf72572e-3c93-11e5-8ed0-eef8c76e334c.png

**Comment by Trubbel** [comment]
@dreamnet Very good! :+1:
