### ISSUE TITLE
Score! Hero

### ISSUE THREAD

**Issue by Ykkris** [glasklart/hd#6164]
**App Name:** Score! Hero
**Bundle ID:** com.firsttouch.story
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=847492141">847492141</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/score!-hero/id847492141?mt=8&uo=4">https://itunes.apple.com/us/app/score!-hero/id847492141?mt=8&uo=4</a>
**App Version:** 1.04
**Seller:** First Touch Games Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/first-touch-games-ltd./id471316020?uo=4>© First Touch Games Ltd.</a>
**Supported Devices:** iPadThirdGen4G, iPadFourthGen, iPhone5s, iPhone6Plus, iPhone4S, iPhone-3GS, iPadThirdGen, iPhone6, iPhone5, iPodTouchFifthGen, iPad2Wifi, iPodTouchSixthGen, iPad23G, iPadMini4G, iPhone4, iPadFourthGen4G, iPadMini, iPhone5c, iPodTouchFourthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/7a/7a/35/7a7a358e-4ecd-2e54-0fec-dd590f1efd39/mzl.norafnpu.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Ykkris** [comment]
![com firsttouch story](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9125968/089121ca-3ca7-11e5-96ba-e525db55b694.png)
https://cloud.githubusercontent.com/assets/13631976/9125968/089121ca-3ca7-11e5-96ba-e525db55b694.png

---
Source : 
https://cloud.githubusercontent.com/assets/13631976/9125988/315df542-3ca7-11e5-9fbc-120ab43daec1.png

PS : Not really proud of my source but I think the render isn't so bad. If it isn't good, I'm sorry :(

**Comment by ivanov007** [comment]
@Ykkris  it looks good, the source needs to be full size, can you resize it up? and juat a little thing, can you make the ball look separated from the body and arm?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9232475/2eb9aeae-412e-11e5-9cc0-4f302e1d01c6.png)
https://cloud.githubusercontent.com/assets/2068130/9232475/2eb9aeae-412e-11e5-9cc0-4f302e1d01c6.png

---
https://cloud.githubusercontent.com/assets/2068130/9232495/56608e64-412e-11e5-88af-cb37ea8f0a27.png
