### ISSUE TITLE
Time Check - Location Bookmarks, ETA and Notifications

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6165]
**App Name:** Time Check - Location Bookmarks, ETA and Notifications
**Bundle ID:** com.glassboxsoftware.mobile.TimeCheck
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1009236436">1009236436</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/time-check-location-bookmarks/id1009236436?mt=8&uo=4">https://itunes.apple.com/us/app/time-check-location-bookmarks/id1009236436?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Glass Box Software
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/glass-box-software/id946885682?uo=4>© Glass Box Software</a>
**Supported Devices:** iPodTouchFifthGen, iPhone4S, iPhone6Plus, iPad2Wifi, iPadFourthGen, iPad23G, iPhone6, iPadThirdGen4G, iPadThirdGen, iPhone5s, iPodTouchSixthGen, iPadFourthGen4G, iPhone5c, iPadMini4G, iPhone5, iPadMini
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/c0/04/c6/c004c6ea-e63a-9761-7730-7cac7f7c11b7/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9210179/0c27b97a-407b-11e5-92bc-313858b45843.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9210179/0c27b97a-407b-11e5-92bc-313858b45843.png)
https://cloud.githubusercontent.com/assets/2068130/9210179/0c27b97a-407b-11e5-92bc-313858b45843.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9210190/185888dc-407b-11e5-94df-4f1cd33023b9.png
