### ISSUE TITLE
SNCF

### ISSUE THREAD

**Issue by Ykkris** [glasklart/hd#6166]
**App Name:** SNCF
**Bundle ID:** com.sncf.appun
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=945434433">945434433</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sncf/id945434433?mt=8&uo=4">https://itunes.apple.com/us/app/sncf/id945434433?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** SNCF
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sncf/id334438200?uo=4>© SNCF</a>
**Supported Devices:** iPad2Wifi, iPhone5s, iPodTouchSixthGen, iPadThirdGen, iPadFourthGen, iPadMini4G, iPhone6Plus, iPhone4, iPadFourthGen4G, iPodTouchFifthGen, iPadThirdGen4G, iPhone6, iPad23G, iPadMini, iPhone5, iPhone5c, iPhone4S
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/76/29/c2/7629c212-31b8-ddfe-88b3-671bf34a0829/mzl.qopetlyc.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9207002/40b9f0aa-406b-11e5-84ce-34b5a01ba059.png)

**Comment by Ykkris** [comment]
![com sncf appun](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9136446/eee07e2c-3d16-11e5-8e96-c5587638c939.png)
https://cloud.githubusercontent.com/assets/13631976/9136446/eee07e2c-3d16-11e5-8e96-c5587638c939.png

---
Source : 
https://cloud.githubusercontent.com/assets/13631976/9136451/fc295d88-3d16-11e5-8070-c8a82c1612df.png

**Comment by ivanov007** [comment]
I don't know if this one will looks better touching the buttom line, what do you think @dreamnet?

**Comment by dreamnet** [comment]
@ivanov007 I think it's OK, in the original the logo is also centered.
@Ykkris :+1:
