### ISSUE TITLE
Fantasy Manager Football 2015

### ISSUE THREAD

**Issue by Ykkris** [glasklart/hd#6167]
**App Name:** FANTASY MANAGER FOOTBALL 2015 - Manage your soccer team
**Bundle ID:** com.fromthebenchgames.fantasymanager.football5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=889854362">889854362</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasy-manager-football-2015/id889854362?mt=8&uo=4">https://itunes.apple.com/us/app/fantasy-manager-football-2015/id889854362?mt=8&uo=4</a>
**App Version:** 5.52
**Seller:** FROM THE BENCH, S.L.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/from-the-bench-sl/id381252618?uo=4>© From The Bench, SL</a>
**Supported Devices:** iPhone4S, iPadFourthGen, iPadThirdGen, iPadFourthGen4G, iPadMini4G, iPhone5, iPadMini, iPodTouchFifthGen, iPhone6Plus, iPad2Wifi, iPad23G, iPhone6, iPadThirdGen4G, iPhone4, iPhone5s, iPodTouchSixthGen, iPhone5c
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple4/v4/c5/31/7c/c5317c9a-a169-f61d-2b72-8e5ba51ec2f1/mzl.ywgldffv.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9207148/063c6a42-406c-11e5-8df7-1aa57b05417c.png)

**Comment by Ykkris** [comment]
![com fromthebenchgames fantasymanager football5](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9136540/c014ea00-3d17-11e5-9405-326c90906464.png)
https://cloud.githubusercontent.com/assets/13631976/9136540/c014ea00-3d17-11e5-9405-326c90906464.png

---
Source : 
https://cloud.githubusercontent.com/assets/13631976/9136552/cf25811c-3d17-11e5-894f-38310b74a8a5.png

**Comment by ivanov007** [comment]
@Ykkris you missed the OO from football, also it looks blurry

**Comment by TheRyanKing** [comment]
![com fromthebenchgames fantasymanager football5 2x](https://cloud.githubusercontent.com/assets/10021829/9201305/47d778b8-401a-11e5-9d0c-4f5919659d66.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9201305/47d778b8-401a-11e5-9d0c-4f5919659d66.png)

**Comment by Trubbel** [comment]
@TheRyanKing You need the icon source as well. See [Icon Sources](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources)

**Comment by TheRyanKing** [comment]
Source: 
https://cloud.githubusercontent.com/assets/10021829/9201740/8a0fa596-401c-11e5-8a05-746bce1c3205.png

**Comment by TheRyanKing** [comment]
@Trubbel Should I re-upload it all as one post or is that satisfactory enough?

**Comment by TheRyanKing** [comment]
![com fromthebenchgames fantasymanager football5 2x](https://cloud.githubusercontent.com/assets/10021829/9201870/2a626538-401d-11e5-889a-2fb0ddc14057.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9201870/2a626538-401d-11e5-889a-2fb0ddc14057.png)

Source:
https://cloud.githubusercontent.com/assets/10021829/9201895/44a13fd2-401d-11e5-86fb-03e58f87b622.png

**Comment by dreamnet** [comment]
Correct icon and source:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9207148/063c6a42-406c-11e5-8df7-1aa57b05417c.png)
https://cloud.githubusercontent.com/assets/2068130/9207148/063c6a42-406c-11e5-8df7-1aa57b05417c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9207157/1523a8a4-406c-11e5-98d2-3d5fa8e1d2b1.png
