### ISSUE TITLE
RATP

### ISSUE THREAD

**Issue by Ykkris** [glasklart/hd#6168]
**App Name:** RATP
**Bundle ID:** com.ratp.ratp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507107090">507107090</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ratp/id507107090?mt=8&uo=4">https://itunes.apple.com/us/app/ratp/id507107090?mt=8&uo=4</a>
**App Version:** 6.3.27
**Seller:** Regie Autonome des Transports Parisien
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ratp/id456989491?uo=4>© RATP</a>
**Supported Devices:** iPhone4, iPadFourthGen, iPodTouchFourthGen, iPhone5, iPhone5s, iPhone6, iPhone6Plus, iPad23G, iPadFourthGen4G, iPhone5c, iPhone4S, iPodTouchFifthGen, iPadThirdGen4G, iPadMini4G, iPadMini, iPodTouchSixthGen, iPad2Wifi, iPhone-3GS, iPadThirdGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/34/11/0d/34110dce-9fe3-8e62-cab6-b862d36f51ab/mzl.jiqfboth.png" width="150" height="150" />
**Accepted Artwork:**
![ratp](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9201858/59210e2e-404f-11e5-8297-183a328eae04.png)

**Comment by Ykkris** [comment]
![com ratp ratp](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9136851/f0c8877c-3d19-11e5-98ca-51e531a38f35.png)
https://cloud.githubusercontent.com/assets/13631976/9136851/f0c8877c-3d19-11e5-98ca-51e531a38f35.png

---
Source : 
https://cloud.githubusercontent.com/assets/13631976/9136859/044cea22-3d1a-11e5-9820-247869a48033.png

**Comment by ivanov007** [comment]
same as the other one, the source needs to be full 1024x1024, also, I don't know why your icon looks a little blurry, are you using the same source for that? or how do you resize it?

**Comment by Ykkris** [comment]
Update : 
![ratp](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9201858/59210e2e-404f-11e5-8297-183a328eae04.png)
https://cloud.githubusercontent.com/assets/13631976/9201858/59210e2e-404f-11e5-8297-183a328eae04.png

---
Source : 
https://cloud.githubusercontent.com/assets/13631976/9201875/7a31a7f4-404f-11e5-82ab-f7b419340514.png
