### ISSUE TITLE
ESL Event

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6172]
**App Name:** ESL Event
**Bundle ID:** com.esl-tech.event
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1000579069">1000579069</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/esl-event/id1000579069?uo=4">https://apps.apple.com/us/app/esl-event/id1000579069?uo=4</a>
**App Version:** 3.12.2
**Seller:** Turtle eSports Technology GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/turtle-esports-technology-gmbh/id965771968?uo=4">© Turtle eSports Technology GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/f2/89/39/f2893928-48f6-c0b2-146c-86faa55e349c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388082-cd3ead00-9aac-11e9-8251-89a09e5e5a3e.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9146947/66102430-3d61-11e5-86b2-f9611d167817.png)
https://cloud.githubusercontent.com/assets/10730122/9146947/66102430-3d61-11e5-86b2-f9611d167817.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9146945/625e01f4-3d61-11e5-9d94-62bf567a5c9a.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388082-cd3ead00-9aac-11e9-8251-89a09e5e5a3e.png)
https://user-images.githubusercontent.com/20930745/60388082-cd3ead00-9aac-11e9-8251-89a09e5e5a3e.png

Source:
https://user-images.githubusercontent.com/20930745/60388083-cf087080-9aac-11e9-86e9-058618432554.png
