### ISSUE TITLE
Kijiji Free Local Classifieds

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6173]
**App Name:** Kijiji Free Local Classifieds
**Bundle ID:** com.kijiji.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=318979520">318979520</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kijiji-free-local-classifieds/id318979520?mt=8&uo=4">https://itunes.apple.com/us/app/kijiji-free-local-classifieds/id318979520?mt=8&uo=4</a>
**App Version:** 4.8.0
**Seller:** Marktplaats BV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/marktplaats-bv/id318979525?uo=4>© Marktplaats BV</a>
**Supported Devices:** iPodTouchSixthGen, iPhone6Plus, iPadFourthGen4G, iPhone5c, iPadThirdGen4G, iPhone5s, iPadThirdGen, iPad2Wifi, iPad23G, iPhone6, iPadMini4G, iPadFourthGen, iPhone5, iPodTouchFifthGen, iPhone4S, iPadMini, iPhone4
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple5/v4/df/cb/9d/dfcb9d19-3486-7732-9fe4-835f8999d22e/mzl.bgcnqgts.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9208030/7fcce936-4071-11e5-910b-4baef8a6e779.png)

**Comment by LaCh0uine** [comment]
Need to be updated;)

**Comment by TheRyanKing** [comment]
![com kijiji iphone 2x](https://cloud.githubusercontent.com/assets/10021829/9200853/e0d053a8-4017-11e5-9021-0e5999b7dd4c.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9200853/e0d053a8-4017-11e5-9021-0e5999b7dd4c.png)

**Comment by TheRyanKing** [comment]
@LaCh0uine Is it a naming problem or does the icon need to be updated? If so, I have included that above.

**Comment by LaCh0uine** [comment]
Just icon need updated .. The naming is ok ;)
Thank you

**Comment by ivanov007** [comment]
@TheRyanKing it just need to be updated the bundle id is the same, as for you icon, you need to add the source file

**Comment by dreamnet** [comment]
Correct icon and source:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9208030/7fcce936-4071-11e5-910b-4baef8a6e779.png)
https://cloud.githubusercontent.com/assets/2068130/9208030/7fcce936-4071-11e5-910b-4baef8a6e779.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9208044/8db52f18-4071-11e5-8c94-34963ee6addb.png

**Comment by TheRyanKing** [comment]
@dreamnet can you just let me know why my icon was incorrect I see that the sizing is different from yours but I am trying to help out as I love this theme, just fill me in and ill be able to adjust, thank you, cheers

**Comment by dreamnet** [comment]
@TheRyanKing Thanks for trying to help us out, we always in need for icon contributors. :+1: 
Please compare your icon above and the one I did - your icon is good, but you need too keep aspect ratio. Also, you need to post a 1024x1024px source file, to see what I mean, just check the source from my post above. You can also read [here](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources). We need icon sources, because it's possible, that Apple changes the icon sizes in the future and then we can't simply resize the existing Glasklart icons, we need to generate them completly new.
Seems you are doing good work, so keep on - and if you have any further questions, please ask.

**Comment by TheRyanKing** [comment]
@dreamnet will do, I will adjust after taking a look at your example, its taking me a little getting used to the correct way of posting but ill get it done and ill be around creating icons, also, what happens if there is a cydia icon not yet themed, but no 1024x1024 source?

**Comment by dreamnet** [comment]
@TheRyanKing Cydia icons are always a problem - you have to connect to your device using e.g. iFunbox, find the right `Info.plist` to find out the bundle identifier and the open a new issue following [this](https://github.com/glasklart/hd/wiki/How-to-Request-a-Cydia-Icon).
If you can't find a 1024x1024px source using Google, please post the highest resolution icon you can find in the app folder on your device.

**Comment by TheRyanKing** [comment]
@dreamnet okay! will do! I'm starting to catch on with the source icons now
