### ISSUE TITLE
New York City Travel Guide by Triposo

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6174]
**App Name:** New York City Travel Guide by Triposo
**Bundle ID:** com.triposo.newyorkcityguide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=462776787">462776787</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-york-city-travel-guide/id462776787?mt=8&uo=4">https://itunes.apple.com/us/app/new-york-city-travel-guide/id462776787?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPodTouchFifthGen, iPhone6, iPadFourthGen4G, iPad23G, iPhone4S, iPadThirdGen, iPodTouchSixthGen, iPhone5, iPadMini4G, iPadFourthGen, iPhone6Plus, iPadThirdGen4G, iPhone5c, iPhone4, iPad2Wifi, iPadMini, iPhone5s
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple2/v4/ce/f4/2c/cef42c3b-d8a1-3fe3-80c7-fc58a6be450e/mzl.qfvaysrm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)

**Comment by Ykkris** [comment]
![mexico-travel](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9156149/7fbfc2a8-3ed0-11e5-85a9-a225699d86fc.png)
https://cloud.githubusercontent.com/assets/13631976/9156149/7fbfc2a8-3ed0-11e5-85a9-a225699d86fc.png

---
Source : 
https://cloud.githubusercontent.com/assets/13631976/9156151/9235b398-3ed0-11e5-8f41-534621923f84.png

**Comment by ivanov007** [comment]
It looks a little blurred, maybe we can use this one #6124 
here's the icon I made for some other apps 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)
https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9006868/8c74c18c-3751-11e5-9af1-e29bbb911afe.png
