### ISSUE TITLE
Mexico Travel Guide by Triposo featuring Mexico City, Puerto Vallarta, Acapulco and more!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6175]
**App Name:** Mexico Travel Guide by Triposo featuring Mexico City, Puerto Vallarta, Acapulco and more!
**Bundle ID:** com.triposo.mexicoguide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467702949">467702949</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mexico-travel-guide-by-triposo/id467702949?mt=8&uo=4">https://itunes.apple.com/us/app/mexico-travel-guide-by-triposo/id467702949?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPhone5, iPadMini, iPhone4, iPodTouchSixthGen, iPadMini4G, iPhone5s, iPodTouchFifthGen, iPhone4S, iPadThirdGen4G, iPad23G, iPadFourthGen4G, iPadFourthGen, iPhone5c, iPadThirdGen, iPhone6Plus, iPad2Wifi, iPhone6
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple4/v4/bb/79/d3/bb79d351-77ff-14b1-0ff0-a0f3146fd8d4/mzl.sqfrfcpd.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)

**Comment by Ykkris** [comment]
![mexico-travel](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9156136/340a175a-3ed0-11e5-84c7-0287c705668c.png)
https://cloud.githubusercontent.com/assets/13631976/9156136/340a175a-3ed0-11e5-84c7-0287c705668c.png

---
Source : 
https://cloud.githubusercontent.com/assets/13631976/9156139/4595f08e-3ed0-11e5-9dac-8d574a075243.png

**Comment by ivanov007** [comment]
It looks a little blurred, maybe we can use this one #6124 
here's the icon I made for some other apps 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png)
https://cloud.githubusercontent.com/assets/3090247/9006835/4d94cd0e-3751-11e5-93d7-a3d04c31fb11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9006868/8c74c18c-3751-11e5-9af1-e29bbb911afe.png
