### ISSUE TITLE
SMDb - Movies & TV Shows

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6176]
**App Name:** SMDb - Movies & TV Shows
**Bundle ID:** com.ernestofndz.G8Movie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=980326058">980326058</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smdb-movies-tv-shows/id980326058?mt=8&uo=4">https://itunes.apple.com/us/app/smdb-movies-tv-shows/id980326058?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Ernesto Fernandez Perez
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ernesto-fernandez-perez/id972015478?uo=4>© Ernesto Fernandez Perez</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/53/52/bd/5352bdc3-5d90-901f-105a-d7291159d1db/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18690855/bc1c6dee-7f90-11e6-8c7a-3ff70e92aa70.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9225121/ae8c509a-4107-11e5-9985-bbcb0fe2ece9.png)
https://cloud.githubusercontent.com/assets/2068130/9225121/ae8c509a-4107-11e5-9985-bbcb0fe2ece9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9225132/be426ec0-4107-11e5-917e-0d1afa6e020c.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** SMDb - Movies & TV Shows
**Bundle ID:** com.ernestofndz.G8Movie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=980326058">980326058</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smdb-movies-tv-shows/id980326058?mt=8&uo=4">https://itunes.apple.com/us/app/smdb-movies-tv-shows/id980326058?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Ernesto Fernandez Perez
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ernesto-fernandez-perez/id972015478?uo=4>© Ernesto Fernandez Perez</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/53/52/bd/5352bdc3-5d90-901f-105a-d7291159d1db/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18690827/9869428c-7f90-11e6-9e42-f6252e61ee74.png)
https://cloud.githubusercontent.com/assets/20930745/18690827/9869428c-7f90-11e6-9e42-f6252e61ee74.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18690848/ac548f68-7f90-11e6-9f93-1cccb8a39630.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18690855/bc1c6dee-7f90-11e6-8c7a-3ff70e92aa70.png)
https://cloud.githubusercontent.com/assets/20930745/18690855/bc1c6dee-7f90-11e6-8c7a-3ff70e92aa70.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18690864/cdec490e-7f90-11e6-9daf-abcb2fc7836f.png
