### ISSUE TITLE
Showtimes, Trailers, Movie Tickets by Marquee

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6177]
**App Name:** Showtimes, Trailers, Movie Tickets by Marquee
**Bundle ID:** com.impekable.marquee
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=954721891">954721891</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/showtimes-trailers-movie-tickets/id954721891?mt=8&uo=4">https://itunes.apple.com/us/app/showtimes-trailers-movie-tickets/id954721891?mt=8&uo=4</a>
**App Version:** 1.14
**Seller:** Impekable, LLC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/impekable-llc/id939974330?uo=4>© Impekable LLC</a>
**Supported Devices:** iPhone4, iPhone6, iPhone5s, iPadThirdGen, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPhone5c, iPhone6Plus, iPadMini, iPhone4S, iPodTouchSixthGen, iPad2Wifi, iPadFourthGen4G, iPadMini4G, iPadThirdGen4G, iPad23G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/db/42/ad/db42ad4c-584f-6445-f240-8d0f3772ded9/mzl.mmlymrui.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9221778/1329a2fc-40ed-11e5-9cdd-386da36abafc.png)

**Comment by Ykkris** [comment]
![showtimes](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13631976/9156096/482f895a-3ecf-11e5-83ad-f9500070bc82.png)
https://cloud.githubusercontent.com/assets/13631976/9156096/482f895a-3ecf-11e5-83ad-f9500070bc82.png

---
Source : 
https://cloud.githubusercontent.com/assets/13631976/9156099/612ca88e-3ecf-11e5-833f-0ac2b276f7a3.png

**Comment by ivanov007** [comment]
@Ykkris looks good, but can you make the corners a little rounder? something like this #6126

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9221778/1329a2fc-40ed-11e5-9cdd-386da36abafc.png)
https://cloud.githubusercontent.com/assets/2068130/9221778/1329a2fc-40ed-11e5-9cdd-386da36abafc.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9221785/21e083a6-40ed-11e5-9edc-8f6e5097d211.png
