### ISSUE TITLE
MacHash News

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#6178]
**App Name:** MacHash News
**Bundle ID:** com.mobileinfocenter.machash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407673940">407673940</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/machash-news/id407673940?mt=8&uo=4">https://itunes.apple.com/us/app/machash-news/id407673940?mt=8&uo=4</a>
**App Version:** 5.5.2
**Seller:** Ryan Kairer
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mobileinfocenter/id391637976?uo=4>© MobileInfocenter</a>
**Supported Devices:** iPad2Wifi, iPhone6, iPhone4S, iPhone4, iPhone5, iPadThirdGen, iPodTouchSixthGen, iPodTouchFifthGen, iPhone6Plus, iPhone5s, iPhone5c, iPadThirdGen4G, iPadFourthGen, iPadMini, iPad23G, iPadMini4G, iPadFourthGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple1/v4/fc/4d/8e/fc4d8e7d-5dc5-ed2f-331e-69c3fe205057/mzl.czyvtoim.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9209043/d84eb780-4074-11e5-8974-043aab281710.png)

**Comment by TheRyanKing** [comment]
![com mobileinfocenter machash 2x](https://cloud.githubusercontent.com/assets/10021829/9198177/49e9c2e4-4008-11e5-8175-5abcb52ecadf.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9198177/49e9c2e4-4008-11e5-8175-5abcb52ecadf.png)

**Comment by TheRyanKing** [comment]
![com mobileinfocenter machash 2x](https://cloud.githubusercontent.com/assets/10021829/9202897/06bc216e-4022-11e5-8a7d-4b5ec7010476.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9202897/06bc216e-4022-11e5-8a7d-4b5ec7010476.png)

Source:
https://cloud.githubusercontent.com/assets/10021829/9202910/1943a5b4-4022-11e5-94bc-5bb4e8edb39e.png

**Comment by dreamnet** [comment]
@TheRyanKing Good work!!!
...only the icon in the source is too small, here is a correct one:
https://cloud.githubusercontent.com/assets/2068130/9209033/c375aeb8-4074-11e5-800a-3e7c0238828b.png
