### ISSUE TITLE
SwiftKit for RuneScape

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#6179]
**App Name:** SwiftKit for RuneScape
**Bundle ID:** net.swiftkit.swiftkitmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=440476684">440476684</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swiftkit-for-runescape/id440476684?mt=8&uo=4">https://itunes.apple.com/us/app/swiftkit-for-runescape/id440476684?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** Tom Parry
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/tom-parry/id437185420?uo=4>© Tom Parry</a>
**Supported Devices:** iPadMini, iPhone-3GS, iPhone6, iPadThirdGen, iPhone4S, iPhone4, iPad23G, iPad2Wifi, iPodTouchFourthGen, iPadFourthGen, iPodTouchSixthGen, iPhone6Plus, iPhone5s, iPadMini4G, iPhone5, iPhone5c, iPodTouchFifthGen, iPadThirdGen4G, iPadFourthGen4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/3f/b6/ed/3fb6ed21-4d8f-8084-f9d7-d37b6b8cdb02/mzl.mczruvqw.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9209775/88eaf6f0-4078-11e5-8e6d-a562572e87c6.png)

**Comment by TheRyanKing** [comment]
![net swiftkit swiftkitmobile 2x](https://cloud.githubusercontent.com/assets/10021829/9198048/3170fb34-4007-11e5-9d71-db05ef78baee.png)

**Comment by TheRyanKing** [comment]
![net swiftkit swiftkitmobile 2x](https://cloud.githubusercontent.com/assets/10021829/9198228/9ea943d6-4008-11e5-8def-3ea702ca73c8.png)
![](http://preview.dreamnet.at/?image=net swiftkit swiftkitmobile 2x](https://cloud.githubusercontent.com/assets/10021829/9198228/9ea943d6-4008-11e5-8def-3ea702ca73c8.png)

**Comment by TheRyanKing** [comment]
![net swiftkit swiftkitmobile 2x](https://cloud.githubusercontent.com/assets/10021829/9198237/bc92e082-4008-11e5-97d3-2068d66caa36.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9198237/bc92e082-4008-11e5-97d3-2068d66caa36.png)

**Comment by TheRyanKing** [comment]
![net swiftkit swiftkitmobile 2x](https://cloud.githubusercontent.com/assets/10021829/9202818/9d5afbdc-4021-11e5-9083-caa0bcafc3b4.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9202818/9d5afbdc-4021-11e5-9083-caa0bcafc3b4.png)

Source:
https://cloud.githubusercontent.com/assets/10021829/9202827/b12a13e6-4021-11e5-87bf-fdaf38ba8938.png

**Comment by dreamnet** [comment]
@TheRyanKing  Corrected source:
https://cloud.githubusercontent.com/assets/2068130/9209744/6b829ffa-4078-11e5-9124-62ef5e054111.png
else, good! :+1:
