### ISSUE TITLE
Type Mail - Email App - Gmail, Exchange, Yahoo, Outlook, Office365

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6180]
**App Name:** Type Mail - Email App - Gmail, Exchange, Yahoo, Outlook, Office365
**Bundle ID:** com.typeapp.ios.comm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979735370">979735370</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/type-mail-email-app-gmail/id979735370?mt=8&uo=4">https://itunes.apple.com/us/app/type-mail-email-app-gmail/id979735370?mt=8&uo=4</a>
**App Version:** 1.6.2
**Seller:** Type App Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/type-app-inc/id979735369?uo=4>© Type App Inc</a>
**Supported Devices:** iPad2Wifi, iPodTouchSixthGen, iPadFourthGen, iPodTouchFifthGen, iPhone5c, iPadMini, iPadMini4G, iPadThirdGen4G, iPhone6Plus, iPadFourthGen4G, iPhone6, iPadThirdGen, iPhone5s, iPhone5, iPhone4S, iPad23G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple1/v4/c9/95/bc/c995bc3c-74af-36e4-2804-91bb269069bf/mzl.htcdzaqw.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9271119/bfbc5c7c-4277-11e5-9307-c5421dd3b27a.png)

**Comment by TheRyanKing** [comment]
![com typeapp ios comm 2x](https://cloud.githubusercontent.com/assets/10021829/9200401/a62be318-4015-11e5-9562-e5216f89729c.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9200401/a62be318-4015-11e5-9562-e5216f89729c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9221622/f5518ad4-40eb-11e5-8fe8-7d64032245a6.png)
https://cloud.githubusercontent.com/assets/2068130/9221622/f5518ad4-40eb-11e5-8fe8-7d64032245a6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9221631/0448b562-40ec-11e5-9d0c-124f0c065db6.png
