### ISSUE TITLE
BaconReader for Reddit

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6182]
**App Name:** BaconReader for Reddit
**Bundle ID:** com.onelouder.BaconReader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=725730936">725730936</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/baconreader-for-reddit/id725730936?mt=8&uo=4">https://itunes.apple.com/us/app/baconreader-for-reddit/id725730936?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** OneLouder
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/onelouder/id455388591?uo=4>© OneLouder</a>
**Supported Devices:** iPhone5, iPhone5s, iPadFourthGen4G, iPhone4, iPhone6Plus, iPodTouchSixthGen, iPadThirdGen4G, iPhone4S, iPad23G, iPodTouchFifthGen, iPadThirdGen, iPhone5c, iPadMini4G, iPad2Wifi, iPadMini, iPadFourthGen, iPhone6
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/fa/16/b1/fa16b16b-a2db-984f-f997-8329a41b2021/mzl.ccfsgwnr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9219761/62828d74-40dd-11e5-87fb-ce7455b82ef9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9219761/62828d74-40dd-11e5-87fb-ce7455b82ef9.png)
https://cloud.githubusercontent.com/assets/2068130/9219761/62828d74-40dd-11e5-87fb-ce7455b82ef9.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9219773/72a9ae26-40dd-11e5-946b-7c16eab02aa0.png
