### ISSUE TITLE
Wildcard - Know the Day in News and Entertainment

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6185]
**App Name:** Wildcard - Know the Day in News and Entertainment
**Bundle ID:** com.trywildcard.wildcard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=930047790">930047790</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wildcard-know-day-in-news/id930047790?mt=8&uo=4">https://itunes.apple.com/us/app/wildcard-know-day-in-news/id930047790?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** COOPKANICS, INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/coopkanics-inc./id930047789?uo=4>© Coopkanics Inc.</a>
**Supported Devices:** iPad23G, iPadMini, iPhone6, iPhone5, iPhone5c, iPadFourthGen, iPad2Wifi, iPhone4S, iPadMini4G, iPadThirdGen, iPhone5s, iPhone6Plus, iPadFourthGen4G, iPodTouchSixthGen, iPadThirdGen4G, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple1/v4/6c/97/68/6c976814-342b-713d-fb4f-d4071aa5b67c/mzl.xbaqttod.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9249522/de6471d0-41c5-11e5-93be-3a927c5a8108.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9249522/de6471d0-41c5-11e5-93be-3a927c5a8108.png)
https://cloud.githubusercontent.com/assets/2068130/9249522/de6471d0-41c5-11e5-93be-3a927c5a8108.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9249525/ec0c60cc-41c5-11e5-9fdb-26f0f713cb55.png
