### ISSUE TITLE
Cydia Impactor

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6186]
**App Name:** Cydia Impactor
 **Bundle ID:** com.saurik.Impactor
 **Version:** 0.9.17
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/10730122/9262991/9e91ca18-4219-11e5-8fa2-a97208c3d659.png" width="150" height="150" />
 **Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9269984/5dc9a65e-426e-11e5-93d3-1b5557b6dffb.png)

**Comment by TheRyanKing** [comment]
![com saurik impactor 2x](https://cloud.githubusercontent.com/assets/10021829/9268181/ac4aba2e-4229-11e5-9488-badcdddb2360.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9268181/ac4aba2e-4229-11e5-9488-badcdddb2360.png)

Source:
https://cloud.githubusercontent.com/assets/10021829/9268192/cac0cc00-4229-11e5-9ef3-f3d071dbd9a8.png

**Comment by dreamnet** [comment]
@TheRyanKing Very good! - I just added a view details:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9269984/5dc9a65e-426e-11e5-93d3-1b5557b6dffb.png)
https://cloud.githubusercontent.com/assets/2068130/9269984/5dc9a65e-426e-11e5-93d3-1b5557b6dffb.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9269991/6e75d176-426e-11e5-8311-bad24df3dd76.png
You are getting credits for this anyway.
