### ISSUE TITLE
Runtastic PRO GPS Running, Walking, Jogging, Fitness Distance Tracker and Marathon Training

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#6187]
**App Name:** Runtastic PRO GPS Running, Walking, Jogging, Fitness Distance Tracker and Marathon Training
**Bundle ID:** at.runtastic.runtastic.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=366626332">366626332</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-pro-gps-running/id366626332?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-pro-gps-running/id366626332?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPadMini4G, iPadMini, iPhone4S, iPadThirdGen4G, iPadThirdGen, iPadFourthGen, iPodTouchSixthGen, iPadFourthGen4G, iPhone4, iPad23G, iPhone5, iPhone5s, iPhone6, iPad2Wifi, iPhone5c, iPhone6Plus, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/89/e0/a6/89e0a699-14ca-12cf-9d18-fb2d06f0c778/mzl.nizojugm.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9273041/85e719f4-4288-11e5-88fe-93a979710b0d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9273041/85e719f4-4288-11e5-88fe-93a979710b0d.png)
https://cloud.githubusercontent.com/assets/2068130/9273041/85e719f4-4288-11e5-88fe-93a979710b0d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9273043/93fe4364-4288-11e5-8ede-4550f5082e37.png

**Comment by TheRyanKing** [comment]
@dreamnet forgive me if this sounds noobish, how do you create the space between, I mean the bit of the curve that is transparent, that adds a layer of separation?

**Comment by dreamnet** [comment]
@TheRyanKing I am using Illustrator to make the sources. With Illustrator it is easy to make a border around the foreground objects and then cut all the background objects along the border, so there is a space between them in the result. Hard to explain, but if you are get experienced with Illustrator you will know what I mean.

**Comment by TheRyanKing** [comment]
@dreamnet ill check it out, thanks for the heads up! still learning here! Really appreciate the insight

**Comment by dreamnet** [comment]
@TheRyanKing No problem, Illustrator can also vectorize images, this can also be very useful - espacially for the simpler icons (up to 16 colors). Try it out on some original artwork images.
