### ISSUE TITLE
McTube and Snapstats icons missing

### ISSUE THREAD

**Issue by coolstar** [glasklart/hd#6188]
Both are apps from the app store; they're missing icons in the latest version from this git repo.

**Comment by ivanov007** [comment]
@coolstar Please read our [WIKI](https://github.com/glasklart/hd/wiki) on [how to submit an icon request](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request) and open a new issue for each app

**Comment by dreamnet** [comment]
@coolstar I will do that for you, because of your great work with Anemone.
