### ISSUE TITLE
Geomaster Plus

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#619]
**App Name:** Geomaster Plus
**Bundle ID:** com.visuamobile.geomaster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=331747091">331747091</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/geomaster-plus/id331747091?mt=8&uo=4">https://itunes.apple.com/us/app/geomaster-plus/id331747091?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Jeremie Engel Engel
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jeremie-engel-engel/id283922362?uo=4">© Jeremie Engel Engel</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/90/43/8e/90438e88-8ec4-bb46-d630-08287dbfb193/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32398667-fb0cc59c-c0f0-11e7-9a58-c5b96216ef8f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32398667-fb0cc59c-c0f0-11e7-9a58-c5b96216ef8f.png)
https://user-images.githubusercontent.com/2068130/32398667-fb0cc59c-c0f0-11e7-9a58-c5b96216ef8f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32398674-0b3714c2-c0f1-11e7-8687-9708eb590c9b.png
