### ISSUE TITLE
Canada Travel Guide by Triposo featuring Toronto, Vancouver, Montreal and more!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6192]
**App Name:** Canada Travel Guide by Triposo featuring Toronto, Vancouver, Montreal and more!
**Bundle ID:** com.triposo.canadaguide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467672006">467672006</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/canada-travel-guide-by-triposo/id467672006?mt=8&uo=4">https://itunes.apple.com/us/app/canada-travel-guide-by-triposo/id467672006?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPodTouchFifthGen, iPadMini, iPhone6, iPadFourthGen, iPhone4S, iPad23G, iPhone4, iPadThirdGen, iPhone5, iPodTouchSixthGen, iPadMini4G, iPhone5c, iPad2Wifi, iPhone5s, iPadThirdGen4G, iPadFourthGen4G, iPhone6Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple4/v4/e9/23/03/e9230346-522a-e37c-6238-0d319ddd7b1c/mzl.irofvlac.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)

**Comment by dreamnet** [comment]
Same icon as for #6124.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)
https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8971983/04fa70b8-3656-11e5-991e-0169cc50e885.png
