### ISSUE TITLE
Nevada Travel Guide by Triposo featuring Las Vegas, Reno, Carson City and more!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6193]
**App Name:** Nevada Travel Guide by Triposo featuring Las Vegas, Reno, Carson City and more!
**Bundle ID:** com.triposo.nevada
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=624258295">624258295</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nevada-travel-guide-by-triposo/id624258295?mt=8&uo=4">https://itunes.apple.com/us/app/nevada-travel-guide-by-triposo/id624258295?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPad23G, iPadFourthGen, iPadMini4G, iPhone5s, iPhone6Plus, iPad2Wifi, iPhone5c, iPodTouchFifthGen, iPadMini, iPadFourthGen4G, iPadThirdGen4G, iPhone4S, iPhone6, iPadThirdGen, iPhone5, iPodTouchSixthGen, iPhone4
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/3f/e8/e5/3fe8e5ea-d382-237b-7e46-3efe37872ddf/mzl.cwfvqqmy.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)

**Comment by dreamnet** [comment]
Same icon as for #6124.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)
https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8971983/04fa70b8-3656-11e5-991e-0169cc50e885.png
