### ISSUE TITLE
WeCal

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6194]
**App Name:** WeCal
**Bundle ID:** im.ecloud.ecalendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=590404570">590404570</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wecal/id590404570?mt=8&uo=4">https://itunes.apple.com/us/app/wecal/id590404570?mt=8&uo=4</a>
**App Version:** 5.2.2
**Seller:** Ecloud Im
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ecloud-im/id590404573?uo=4">© Ecloud Im</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/2a/02/1f/2a021f6e-96f5-8d22-c7d1-259095dc54c8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21484995/465c2a7e-cb9c-11e6-8d2e-2c89dc4db852.png)

**Comment by ivanov007** [comment]
not sure witch one looks better
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9294604/44762b5e-4418-11e5-9773-3a5e499ea8c8.png)
https://cloud.githubusercontent.com/assets/3090247/9294604/44762b5e-4418-11e5-9773-3a5e499ea8c8.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9294606/447a6f0c-4418-11e5-97fb-09a37d68cbf7.png)
https://cloud.githubusercontent.com/assets/3090247/9294606/447a6f0c-4418-11e5-97fb-09a37d68cbf7.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9294605/4478db7e-4418-11e5-8252-b36b63062029.png)
https://cloud.githubusercontent.com/assets/3090247/9294605/4478db7e-4418-11e5-8252-b36b63062029.png

**Comment by dreamnet** [comment]
Hum, about about this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9295444/a9d7303c-446e-11e5-87e7-f123873bc12d.png)
https://cloud.githubusercontent.com/assets/2068130/9295444/a9d7303c-446e-11e5-87e7-f123873bc12d.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9295446/b92dbf88-446e-11e5-849d-3caddf025ea1.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** WeCal
**Bundle ID:** im.ecloud.ecalendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=590404570">590404570</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wecal/id590404570?mt=8&uo=4">https://itunes.apple.com/us/app/wecal/id590404570?mt=8&uo=4</a>
**App Version:** 5.0.1
**Seller:** Ecloud Im
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ecloud-im/id590404573?uo=4>© Ecloud Im</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/c3/80/74/c38074d7-7dd3-077d-89d9-9058d54a6ac8/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892848/085a9b8e-4b22-11e6-8a5a-90d1413eeb7a.png)
https://cloud.githubusercontent.com/assets/2068130/16892848/085a9b8e-4b22-11e6-8a5a-90d1413eeb7a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892851/165df42e-4b22-11e6-8e1a-a14fbeedf5e8.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** WeCal
**Bundle ID:** im.ecloud.ecalendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=590404570">590404570</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wecal/id590404570?mt=8&uo=4">https://itunes.apple.com/us/app/wecal/id590404570?mt=8&uo=4</a>
**App Version:** 5.2.2
**Seller:** Ecloud Im
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ecloud-im/id590404573?uo=4">© Ecloud Im</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/2a/02/1f/2a021f6e-96f5-8d22-c7d1-259095dc54c8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21484995/465c2a7e-cb9c-11e6-8d2e-2c89dc4db852.png)
https://cloud.githubusercontent.com/assets/20930745/21484995/465c2a7e-cb9c-11e6-8d2e-2c89dc4db852.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21485001/543cdefe-cb9c-11e6-82f7-e6ef5d33b0f9.png
