### ISSUE TITLE
OOReader

### ISSUE THREAD

**Issue by pishit** [glasklart/hd#6196]
**App Name:** OOReader
**Bundle ID:** com.bmlsolutions.ooreader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=480844649">480844649</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ooreader/id480844649?mt=8&uo=4">https://itunes.apple.com/us/app/ooreader/id480844649?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** BML Solutions inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bml-solutions-inc./id349426067?uo=4>© BML Solutions Inc.</a>
**Supported Devices:** iPhone-3GS, iPad3G, iPodTouchFifthGen, iPadFourthGen4G, iPhone5, iPhone5s, iPadThirdGen4G, iPhone6Plus, iPhone6, iPad2Wifi, iPhone5c, iPodTouchFourthGen, iPhone4, iPadThirdGen, iPhone4S, iPodTouchThirdGen, iPad23G, iPadFourthGen, iPodTouchSixthGen, iPadWifi, iPadMini4G, iPadMini
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple3/v4/53/f1/4c/53f14cba-deb4-8290-4257-a50c39f6c5d9/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9390240/e2ad27c8-473d-11e5-8f76-ea27fbad7253.png)

**Comment by TheRyanKing** [comment]
(https://cloud.githubusercontent.com/assets/10021829/9389057/f8a2adb6-4736-11e5-9bf4-a27945ffb2ff.png

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9389057/f8a2adb6-4736-11e5-9bf4-a27945ffb2ff.png)

Source:

https://cloud.githubusercontent.com/assets/10021829/9389076/1535b02c-4737-11e5-94f0-430916d1ae59.png

**Comment by TheRyanKing** [comment]
![com bmlsolutions ooreader 2x](https://cloud.githubusercontent.com/assets/10021829/9389130/595909a2-4737-11e5-9658-8ed0180c5f1d.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9389130/595909a2-4737-11e5-9658-8ed0180c5f1d.png)

Source:

![ooreader-source](https://cloud.githubusercontent.com/assets/10021829/9389137/6e2eed1a-4737-11e5-80db-2a59cd48d08e.png)

**Comment by TheRyanKing** [comment]
![com bmlsolutions ooreader 2x](https://cloud.githubusercontent.com/assets/10021829/9390240/e2ad27c8-473d-11e5-8f76-ea27fbad7253.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9390240/e2ad27c8-473d-11e5-8f76-ea27fbad7253.png)

Source:
https://cloud.githubusercontent.com/assets/10021829/9390247/f36b7a9c-473d-11e5-8567-7cdc3eac71f9.png

**Comment by ivanov007** [comment]
@TheRyanKing Looks good :+1:
