### ISSUE TITLE
EWE Service

### ISSUE THREAD

**Issue by pishit** [glasklart/hd#6197]
**App Name:** EWE Service
**Bundle ID:** de.ewe.tk.app.service
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=602572113">602572113</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ewe-service/id602572113?mt=8&uo=4">https://itunes.apple.com/us/app/ewe-service/id602572113?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** EWE Aktiengesellschaft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/ewe-aktiengesellschaft/id478255449?uo=4>© EWE Aktiengesellschaft</a>
**Supported Devices:** iPadThirdGen, iPhone5c, iPhone6Plus, iPadThirdGen4G, iPhone5s, iPadFourthGen, iPad2Wifi, iPadMini4G, iPhone4S, iPhone6, iPhone5, iPodTouchSixthGen, iPadFourthGen4G, iPodTouchFifthGen, iPadMini, iPhone4, iPad23G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple3/v4/67/b6/e1/67b6e188-976c-cd74-6af5-2a81eca44060/mzl.dobaylnl.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9423841/284a0d1a-489b-11e5-95ab-8536c29257ca.png)

**Comment by TheRyanKing** [comment]
Wow this Original Artwork is awful, this is from the App Store? Ewww, just look at the poor quality of the phone.

**Comment by TheRyanKing** [comment]
![de ewe tk app service 2x](https://cloud.githubusercontent.com/assets/10021829/9390103/0c761b88-473d-11e5-9742-0e189a9ef7ae.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9390103/0c761b88-473d-11e5-9742-0e189a9ef7ae.png)

Source:

![ewe-source](https://cloud.githubusercontent.com/assets/10021829/9390120/2cda2716-473d-11e5-93e2-0b623ab1f48e.png)

**Comment by TheRyanKing** [comment]
Source:

https://cloud.githubusercontent.com/assets/10021829/9390188/8c7e1970-473d-11e5-8245-03ea4d746616.png

**Comment by TheRyanKing** [comment]
![de ewe tk app service 2x](https://cloud.githubusercontent.com/assets/10021829/9390200/9f3ba47e-473d-11e5-9298-3e743f87355a.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9390200/9f3ba47e-473d-11e5-9298-3e743f87355a.png)

Source:

https://cloud.githubusercontent.com/assets/10021829/9390209/b210ea32-473d-11e5-9136-0d90c5f8daf7.png

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9423841/284a0d1a-489b-11e5-95ab-8536c29257ca.png)
https://cloud.githubusercontent.com/assets/3090247/9423841/284a0d1a-489b-11e5-95ab-8536c29257ca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9423840/28443728-489b-11e5-8d67-316c5af4c0c4.png

**Comment by dreamnet** [comment]
Hmmm - I prefer the one from @ivanov007.
