### ISSUE TITLE
Facebook Messenger

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#62]
**App Name:** Facebook Messenger
**Bundle ID:** com.facebook.Messenger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454638411">454638411</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facebook-messenger/id454638411?mt=8&uo=4">https://itunes.apple.com/us/app/facebook-messenger/id454638411?mt=8&uo=4</a>
**App Version:** 24.0
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/facebook-inc./id284882218?uo=4>© Facebook, Inc.</a>
**Supported Devices:** iPadThirdGen, iPhone5, iPadMini, iPhone4, iPhone5s, iPadThirdGen4G, iPhone5c, iPhone6, iPhone4S, iPadMini4G, iPad23G, iPad2Wifi, iPadFourthGen, iPodTouchFifthGen, iPadFourthGen4G, iPhone6Plus
**Original Artwork:**
<img src="http://a470.phobos.apple.com/us/r30/Purple3/v4/73/8b/a4/738ba4e0-5996-e621-7c08-a903aed4fed3/mzl.njyyrmru.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7043605/97d3d360-ddb0-11e4-8eea-50f5377d084a.png)

**Comment by ivanov007** [comment]
just updating this one with the source
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7043605/97d3d360-ddb0-11e4-8eea-50f5377d084a.png)
https://cloud.githubusercontent.com/assets/3090247/7043605/97d3d360-ddb0-11e4-8eea-50f5377d084a.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7043604/97bf4bca-ddb0-11e4-8d3e-9f06b187e5d9.png

**Comment by dreamnet** [comment]
Icon is already in the master - no commit needed.
