### ISSUE TITLE
Gumtree Local Ads - Buy & Sell

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#620]
**App Name:** Gumtree Local Ads - Buy & Sell
**Bundle ID:** com.kijiji.gumtreeintlapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336693856">336693856</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gumtree-local-ads-buy-sell/id336693856?uo=4">https://apps.apple.com/us/app/gumtree-local-ads-buy-sell/id336693856?uo=4</a>
**App Version:** 12.4.0
**Seller:** Marktplaats BV
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/marktplaats-bv/id318979525?uo=4">© Marktplaats BV</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/33/6c/6b/336c6b0c-011a-322f-e4ec-19f12fa11ee3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60464604-5988d580-9c4f-11e9-9bff-b2ce9fe669e4.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18746656/f45a71f4-80c8-11e6-9fd6-c0a74031f24c.png)
https://cloud.githubusercontent.com/assets/20930745/18746656/f45a71f4-80c8-11e6-9fd6-c0a74031f24c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18746624/bf391732-80c8-11e6-979d-cb287dcaa61c.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60464604-5988d580-9c4f-11e9-9bff-b2ce9fe669e4.png)
https://user-images.githubusercontent.com/2068130/60464604-5988d580-9c4f-11e9-9bff-b2ce9fe669e4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60464638-6e656900-9c4f-11e9-8274-1cc557d627a0.png
