### ISSUE TITLE
Clone Camera Pro

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6200]
**App Name:** Clone Camera Pro
**Bundle ID:** com.ptsoft.CloneCamera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=557861125">557861125</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clone-camera-pro/id557861125?mt=8&uo=4">https://itunes.apple.com/us/app/clone-camera-pro/id557861125?mt=8&uo=4</a>
**App Version:** 2.3.4
**Seller:** Peta Vision
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/peta-vision/id401432180?uo=4>© Peta Vision</a>
**Supported Devices:** iPodTouchFifthGen, iPadFourthGen4G, iPadMini, iPad2Wifi, iPadMini4G, iPadThirdGen4G, iPadThirdGen, iPhone5c, iPodTouchFourthGen, iPodTouchSixthGen, iPhone6Plus, iPhone4S, iPhone4, iPhone5, iPhone6, iPhone-3GS, iPad23G, iPadFourthGen, iPhone5s
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/cf/a4/95/cfa49556-7c22-70f9-1c5d-62197e5e504c/mzl.eyejlimk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9424031/ed2a2cda-48a2-11e5-965c-331cf0e0d5ae.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9424030/ed1cb140-48a2-11e5-9601-133e03b9ef7d.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9424031/ed2a2cda-48a2-11e5-965c-331cf0e0d5ae.png)
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/9424033/fcb01296-48a2-11e5-89fa-a6187bdc4d6f.png
https://cloud.githubusercontent.com/assets/3090247/9424034/fcd856e8-48a2-11e5-9f21-cb1617544143.png

**Comment by dreamnet** [comment]
@ivanov007 Taking the second one.
