### ISSUE TITLE
Duolingo English Test

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6201]
**App Name:** Duolingo English Test
**Bundle ID:** com.duolingo.TestCenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=929167184">929167184</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/duolingo-test-center-english/id929167184?mt=8&uo=4">https://itunes.apple.com/us/app/duolingo-test-center-english/id929167184?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** Duolingo, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/duolingo/id570060151?uo=4>© Duolingo</a>
**Supported Devices:** iPhone4S, iPhone4, iPhone5, iPhone6Plus, iPadThirdGen4G, iPadThirdGen, iPad2Wifi, iPhone6, iPhone5c, iPadFourthGen4G, iPodTouchFifthGen, iPadFourthGen, iPadMini, iPad23G, iPadMini4G, iPhone5s, iPodTouchSixthGen
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60382791-8fb83080-9a68-11e9-9e7b-2abef2e44eb4.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60382793-9ba3f280-9a68-11e9-87a7-30488fcbc127.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9424092/053fcf08-48a5-11e5-9d0c-68c818ddea6d.png)
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9424094/1c3dd010-48a5-11e5-87db-3510cc834ef8.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60382793-9ba3f280-9a68-11e9-87a7-30488fcbc127.png)
https://user-images.githubusercontent.com/2068130/60382793-9ba3f280-9a68-11e9-87a7-30488fcbc127.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60382797-acecff00-9a68-11e9-9c08-cea6e695c5e2.png
