### ISSUE TITLE
Try Harder

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6204]
**App Name:** Try Harder
**Bundle ID:** com.turner.tryharder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=963759536">963759536</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/try-harder/id963759536?mt=8&uo=4">https://itunes.apple.com/us/app/try-harder/id963759536?mt=8&uo=4</a>
**App Version:** 1.03
**Seller:** Turner Broadcasting System, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adult-swim/id398288427?uo=4>© [adult swim]</a>
**Supported Devices:** iPhone4S, iPadMini, iPadFourthGen4G, iPadThirdGen, iPodTouchSixthGen, iPad23G, iPhone5c, iPhone5, iPodTouchFifthGen, iPhone5s, iPhone6, iPadFourthGen, iPhone6Plus, iPad2Wifi, iPhone4, iPadThirdGen4G, iPadMini4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/pf/us/r30/Purple5/v4/6b/bb/75/6bbb7501-284f-0aa3-56fc-472d6e238749/mzl.jcuxqauu.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9424801/39d0f32c-48bf-11e5-895e-c6113bef0a3d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9424502/501048f0-48b4-11e5-805a-46a89abcc9bb.png)
https://cloud.githubusercontent.com/assets/3090247/9424502/501048f0-48b4-11e5-805a-46a89abcc9bb.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9424501/5003d93a-48b4-11e5-86ac-0fe84e74149d.png)
https://cloud.githubusercontent.com/assets/3090247/9424501/5003d93a-48b4-11e5-86ac-0fe84e74149d.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/9424509/69e2e530-48b4-11e5-91d2-c50b4cdc4f91.png
https://cloud.githubusercontent.com/assets/3090247/9424510/6a0caab4-48b4-11e5-94f2-eda81520c8ce.png

**Comment by ivanov007** [comment]
another try
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9424775/86e14f8c-48be-11e5-96fd-9fa8f42dc7a5.png
https://cloud.githubusercontent.com/assets/3090247/9424775/86e14f8c-48be-11e5-96fd-9fa8f42dc7a5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9424777/966dcb24-48be-11e5-8788-1ac59d462e8c.png

**Comment by dreamnet** [comment]
@ivanov007 I think the last one is great. :+1:
