### ISSUE TITLE
Burst Mode  - High speed camera

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6205]
**App Name:** Burst Mode  - High speed camera
**Bundle ID:** com.cogitap.BurstMode
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393131664">393131664</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/burst-mode-high-speed-camera/id393131664?mt=8&uo=4">https://itunes.apple.com/us/app/burst-mode-high-speed-camera/id393131664?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Cogitap Software
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cogitap-software/id338236702?uo=4>© Cogitap Software</a>
**Supported Devices:** iPodTouchFourthGen, iPadFourthGen, iPadThirdGen4G, iPhone5c, iPad2Wifi, iPad23G, iPhone4S, iPhone6, iPodTouchFifthGen, iPhone5s, iPadMini, iPhone5, iPhone4, iPadFourthGen4G, iPodTouchSixthGen, iPadThirdGen, iPhone-3GS, iPadMini4G, iPhone6Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple4/v4/7e/37/7e/7e377e73-62a5-3d48-bbd3-52834b0f22bd/mzl.bspytigk.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9425394/7ce8053c-48d4-11e5-8147-11d0e70bdab7.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9425393/7cdbf90e-48d4-11e5-85a8-64da120c5e0a.png)
https://cloud.githubusercontent.com/assets/3090247/9425393/7cdbf90e-48d4-11e5-85a8-64da120c5e0a.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9425394/7ce8053c-48d4-11e5-8147-11d0e70bdab7.png)
https://cloud.githubusercontent.com/assets/3090247/9425394/7ce8053c-48d4-11e5-8147-11d0e70bdab7.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/9425396/938d8974-48d4-11e5-8d6d-a0b3aded71fc.png
https://cloud.githubusercontent.com/assets/3090247/9425397/9393b7ea-48d4-11e5-8753-e9796839f8aa.png

**Comment by dreamnet** [comment]
@ivanov007 I take the one without the text.
