### ISSUE TITLE
Bubble Burst HD - FREE

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6207]
**App Name:** Bubble Burst HD - FREE
**Bundle ID:** com.turbofireapps.bubble-burst
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427773943">427773943</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bubble-burst-hd-free/id427773943?mt=8&uo=4">https://itunes.apple.com/us/app/bubble-burst-hd-free/id427773943?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** Turbo Fire Apps Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/turbo-fire/id416868931?uo=4>© Turbo Fire</a>
**Supported Devices:** iPad3G, iPhone4S, iPadWifi, iPodTouchFourthGen, iPhone4, iPhone6Plus, iPod-touch-with-mic, iPhone5c, iPhone5, iPadFourthGen4G, iPodTouchFifthGen, iPhone6, iPhone-3GS, iPadMini, iPadThirdGen, iPadMini4G, iPadThirdGen4G, iPodTouchThirdGen, iPad23G, iPodTouchSixthGen, iPad2Wifi, iPhone-3G, iPhone5s, iPadFourthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple2/v4/51/73/06/517306bb-b7c4-9a65-87e4-3bde5ad46258/mzl.axwjhkqs.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9429951/462b072e-49e2-11e5-8d00-b7cd1f7a7468.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9425519/dc11960a-48d8-11e5-8f75-07c3310192ee.png)
https://cloud.githubusercontent.com/assets/3090247/9425519/dc11960a-48d8-11e5-8f75-07c3310192ee.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9425526/f477a702-48d8-11e5-9685-d43f87eaba00.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9429951/462b072e-49e2-11e5-8d00-b7cd1f7a7468.png)
https://cloud.githubusercontent.com/assets/2068130/9429951/462b072e-49e2-11e5-8d00-b7cd1f7a7468.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9429953/5305f7ce-49e2-11e5-88e5-d19308fdac6c.png
