### ISSUE TITLE
Bumble - Meet New People

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6208]
**App Name:** Bumble - Meet New People
**Bundle ID:** com.moxco.bumble
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=930441707">930441707</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bumble-meet-new-people/id930441707?uo=4">https://apps.apple.com/us/app/bumble-meet-new-people/id930441707?uo=4</a>
**App Version:** 5.118.0
**Seller:** Bumble Holding Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bumble-holding-limited/id1120675060?uo=4">© Bumble Holding Limited</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/17/d4/d3/17d4d3b0-385c-bf14-5b80-8e69c2f743de/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981338-0afd8a80-9602-11e9-8e02-ae7dcea65db6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9429751/3337ccac-49dc-11e5-836b-ff358094cc45.png)
https://cloud.githubusercontent.com/assets/2068130/9429751/3337ccac-49dc-11e5-836b-ff358094cc45.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9429754/40fc4afc-49dc-11e5-9455-9c6d641f7823.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981338-0afd8a80-9602-11e9-8e02-ae7dcea65db6.png)
https://user-images.githubusercontent.com/2068130/59981338-0afd8a80-9602-11e9-8e02-ae7dcea65db6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59981343-1d77c400-9602-11e9-9182-ca60c5a9b611.png
