### ISSUE TITLE
PAC-MAN 256 - Endless Arcade Maze

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6209]
**App Name:** PAC-MAN 256 - Endless Arcade Maze
**Bundle ID:** eu.bandainamcoent.pacman256
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1002340615">1002340615</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pac-man-256-endless-arcade/id1002340615?mt=8&uo=4">https://itunes.apple.com/us/app/pac-man-256-endless-arcade/id1002340615?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** BANDAI NAMCO Entertainment Europe
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bandai-namco-entertainment/id580781332?uo=4>© BANDAI NAMCO Entertainment Europe</a>
**Supported Devices:** iPad23G, iPhone4S, iPhone6Plus, iPad2Wifi, iPadThirdGen, iPhone6, iPhone5, iPodTouchFifthGen, iPhone5c, iPadFourthGen4G, iPhone4, iPhone5s, iPodTouchSixthGen, iPadThirdGen4G, iPadMini4G, iPadMini, iPadFourthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple7/v4/ce/ba/8d/ceba8de3-3ab5-baba-67a4-bbdc714b833b/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9479143/2ff34f16-4b7c-11e5-9c1f-38eda1c54c98.png)

**Comment by TheRyanKing** [comment]
![eu bandainamcoent pacman256 2x](https://cloud.githubusercontent.com/assets/10021829/9447538/e95ab772-4a65-11e5-94d6-7981622d411a.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9447538/e95ab772-4a65-11e5-94d6-7981622d411a.png)

Source:
https://cloud.githubusercontent.com/assets/10021829/9447549/ff7a256a-4a65-11e5-8798-284008fcbbeb.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9479143/2ff34f16-4b7c-11e5-9c1f-38eda1c54c98.png)
https://cloud.githubusercontent.com/assets/2068130/9479143/2ff34f16-4b7c-11e5-9c1f-38eda1c54c98.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9479156/400987bc-4b7c-11e5-85ef-b557834fd878.png

**Comment by TheRyanKing** [comment]
@dreamnet I prefer your rendition over mine. Looks crisper and pops out more. :+1:
