### ISSUE TITLE
Friendly for Facebook

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6210]
**App Name:** Friendly for Facebook
**Bundle ID:** com.oecoway.friendlyLite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=400169658">400169658</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/friendly-for-facebook/id400169658?uo=4">https://apps.apple.com/us/app/friendly-for-facebook/id400169658?uo=4</a>
**App Version:** 7.5.1
**Seller:** Friendly App Studio LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/friendly-app-studio/id639296709?uo=4">© Friendly App Studio</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/3b/ef/fa/3beffac0-7251-bbab-0636-a1b19ef185f3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60394177-825e7d00-9b20-11e9-9bbb-f7cb2e85bab0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9429973/7fc4b6be-49e3-11e5-8b96-af70d6543fc4.png)
https://cloud.githubusercontent.com/assets/2068130/9429973/7fc4b6be-49e3-11e5-8b96-af70d6543fc4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9429977/8ed9ae16-49e3-11e5-8ba1-2f358f1dd1df.png

**Comment by grkka** [comment]
@dreamnet Hello, they are different app. A free and one payment. Thanks. https://itunes.apple.com/us/app/friendly-plus-with-ad-blocker/id382011064?mt=8&ign-mpt=uo%3D4
https://itunes.apple.com/us/app/friendly-for-facebook-+-messenger/id400169658?mt=8&ign-mpt=uo%3D4

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60394177-825e7d00-9b20-11e9-9bbb-f7cb2e85bab0.png)
https://user-images.githubusercontent.com/2068130/60394177-825e7d00-9b20-11e9-9bbb-f7cb2e85bab0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60394179-92765c80-9b20-11e9-930a-3da281d1dfb6.png
