### ISSUE TITLE
TripGo: All your transport modes, in real-time

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6211]
**App Name:** TripGo: All your transport modes, in real-time
**Bundle ID:** com.buzzhives.TripPlanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=533630842">533630842</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tripgo-all-your-transport/id533630842?mt=8&uo=4">https://itunes.apple.com/us/app/tripgo-all-your-transport/id533630842?mt=8&uo=4</a>
**App Version:** 4.7
**Seller:** SkedGo Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/skedgo-pty-ltd/id533630845?uo=4>© SkedGo Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/5a/9e/67/5a9e6779-b1b2-fc8a-4aab-29b5a8fcada8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19087485/73639ea0-8a72-11e6-8704-5befee1a3357.png)

**Comment by TheRyanKing** [comment]
![com buzzhives tripplanner 2x](https://cloud.githubusercontent.com/assets/10021829/9448032/57d50426-4a68-11e5-98a4-fd49468fea89.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/9448032/57d50426-4a68-11e5-98a4-fd49468fea89.png)

Source:
https://cloud.githubusercontent.com/assets/10021829/9448047/68fb4850-4a68-11e5-8484-c01fe6d8f917.png

**Comment by ivanov007** [comment]
@TheRyanKing great :+1:

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** TripGo: All your transport modes, in real-time
**Bundle ID:** com.buzzhives.TripPlanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=533630842">533630842</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tripgo-all-your-transport/id533630842?mt=8&uo=4">https://itunes.apple.com/us/app/tripgo-all-your-transport/id533630842?mt=8&uo=4</a>
**App Version:** 4.7
**Seller:** SkedGo Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/skedgo-pty-ltd/id533630845?uo=4>© SkedGo Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/5a/9e/67/5a9e6779-b1b2-fc8a-4aab-29b5a8fcada8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19087485/73639ea0-8a72-11e6-8704-5befee1a3357.png)
https://cloud.githubusercontent.com/assets/20930745/19087485/73639ea0-8a72-11e6-8704-5befee1a3357.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19087497/7f473cae-8a72-11e6-9305-6777044b8da3.png
