### ISSUE TITLE
Maine Travel Guide by Triposo featuring Portland, Augusta, Freeport and more!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6213]
**App Name:** Maine Travel Guide by Triposo featuring Portland, Augusta, Freeport and more!
**Bundle ID:** com.triposo.maine
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=624163073">624163073</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/maine-travel-guide-by-triposo/id624163073?mt=8&uo=4">https://itunes.apple.com/us/app/maine-travel-guide-by-triposo/id624163073?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPadThirdGen4G, iPodTouchFifthGen, iPhone5s, iPhone4S, iPadThirdGen, iPad23G, iPadFourthGen, iPhone6, iPhone5, iPhone5c, iPodTouchSixthGen, iPhone6Plus, iPad2Wifi, iPadMini, iPadMini4G, iPadFourthGen4G, iPhone4
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/pf/us/r30/Purple4/v4/64/79/6d/64796dbd-59ac-b0ab-1229-349942f1edeb/mzl.ybvnfnoz.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)

**Comment by dreamnet** [comment]
Same icon as for #6124.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)
https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8971983/04fa70b8-3656-11e5-991e-0169cc50e885.png
