### ISSUE TITLE
Portal - WiFi File Transfers

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6215]
**App Name:** Portal - WiFi File Transfers
**Bundle ID:** com.pusbullet.client.Portal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1012025930">1012025930</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/portal-wifi-file-transfers/id1012025930?mt=8&uo=4">https://itunes.apple.com/us/app/portal-wifi-file-transfers/id1012025930?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** PushBullet, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pushbullet/id810352055?uo=4>© Pushbullet</a>
**Supported Devices:** iPadThirdGen4G, iPadFourthGen4G, iPad23G, iPhone6, iPadThirdGen, iPodTouchFifthGen, iPad2Wifi, iPhone6Plus, iPadFourthGen, iPadMini4G, iPodTouchSixthGen, iPhone4S, iPadMini, iPhone5c, iPhone5, iPhone5s
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple7/v4/99/53/ff/9953ffc0-bf61-4560-fae4-114be590ecfc/pr_source.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9501093/665a2572-4c29-11e5-9c37-2019d8863f16.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9501093/665a2572-4c29-11e5-9c37-2019d8863f16.png)
https://cloud.githubusercontent.com/assets/10730122/9501093/665a2572-4c29-11e5-9c37-2019d8863f16.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9501091/63636770-4c29-11e5-8aca-293ccf1e05bd.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
