### ISSUE TITLE
YouTube Gaming

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6216]
**App Name:** YouTube Gaming
**Bundle ID:** com.google.ios.youtubegaming
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1009116743">1009116743</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/youtube-gaming/id1009116743?mt=8&uo=4">https://itunes.apple.com/us/app/youtube-gaming/id1009116743?mt=8&uo=4</a>
**App Version:** 2.05
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc/id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/58/0a/4e/580a4e9d-84a7-1c3e-5d1a-a34dd60973df/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456499-eae6b960-ed97-11e7-9caa-01b6876c9a10.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9503613/5c456164-4c38-11e5-97dc-46b956a85866.png)
https://cloud.githubusercontent.com/assets/10730122/9503613/5c456164-4c38-11e5-97dc-46b956a85866.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9503611/582b599e-4c38-11e5-9f25-25de3f0b5771.png

**Comment by Christian9901** [comment]
Icon needs an update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456499-eae6b960-ed97-11e7-9caa-01b6876c9a10.png)
https://user-images.githubusercontent.com/2068130/34456499-eae6b960-ed97-11e7-9caa-01b6876c9a10.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34456503-fb288ac4-ed97-11e7-8704-66e1a4ce849e.png
