### ISSUE TITLE
Voice Recorder Free - smart Speech and Audio record utility for interviewers and students

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6221]
**App Name:** Voice Recorder Free - smart Speech and Audio record utility for interviewers and students
**Bundle ID:** com.smartloftapps.voicerecorderfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=865981938">865981938</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/voice-recorder-free-smart/id865981938?mt=8&uo=4">https://itunes.apple.com/us/app/voice-recorder-free-smart/id865981938?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** Volgan Shpitz
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/volgan-shpitz/id863033890?uo=4>© Volgan Shpitz</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple60/v4/e7/19/a4/e719a4a7-6cdf-c890-bacc-da83dd63fa8e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18238161/4725c4ac-733a-11e6-9046-3ce83fd30829.png)

**Comment by Trubbel** [comment]
Same icon as #6220,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9505949/63460e3e-4c45-11e5-89c7-4d7ca97a85d1.png)
https://cloud.githubusercontent.com/assets/10730122/9505949/63460e3e-4c45-11e5-89c7-4d7ca97a85d1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9505944/603f3cc4-4c45-11e5-8a3f-666143bb3ea2.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18238161/4725c4ac-733a-11e6-9046-3ce83fd30829.png)
https://cloud.githubusercontent.com/assets/2068130/18238161/4725c4ac-733a-11e6-9046-3ce83fd30829.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18238168/54f3d416-733a-11e6-8f22-bdc1aad265a7.png
