### ISSUE TITLE
Voice Recorder PRО - smart speech & audio record utility for interviewers and students

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6223]
**App Name:** Voice Recorder PRО - smart speech & audio record utility for interviewers and students
**Bundle ID:** com.smartloftapps.voicerecorderpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=863034645">863034645</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/voice-recorder-pro-smart-speech/id863034645?mt=8&uo=4">https://itunes.apple.com/us/app/voice-recorder-pro-smart-speech/id863034645?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Volgan Shpitz
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/volgan-shpitz/id863033890?uo=4>© Volgan Shpitz</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple20/v4/18/2c/4c/182c4c8e-3685-38e2-5f62-dae10a6fa039/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18238161/4725c4ac-733a-11e6-9046-3ce83fd30829.png)

**Comment by Trubbel** [comment]
Same icon as #6220,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9505949/63460e3e-4c45-11e5-89c7-4d7ca97a85d1.png)
https://cloud.githubusercontent.com/assets/10730122/9505949/63460e3e-4c45-11e5-89c7-4d7ca97a85d1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9505944/603f3cc4-4c45-11e5-8a3f-666143bb3ea2.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Voice Recorder PRО - smart speech & audio record utility for interviewers and students
**Bundle ID:** com.smartloftapps.voicerecorderpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=863034645">863034645</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/voice-recorder-pro-smart-speech/id863034645?mt=8&uo=4">https://itunes.apple.com/us/app/voice-recorder-pro-smart-speech/id863034645?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Volgan Shpitz
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/volgan-shpitz/id863033890?uo=4>© Volgan Shpitz</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple20/v4/18/2c/4c/182c4c8e-3685-38e2-5f62-dae10a6fa039/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18238161/4725c4ac-733a-11e6-9046-3ce83fd30829.png)
https://cloud.githubusercontent.com/assets/2068130/18238161/4725c4ac-733a-11e6-9046-3ce83fd30829.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18238168/54f3d416-733a-11e6-8f22-bdc1aad265a7.png
