### ISSUE TITLE
Infestor

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#623]
**App Name:** Infestor
**Bundle ID:** com.ravenousgames.infestor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=577138009">577138009</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/infestor/id577138009?mt=8&uo=4">https://itunes.apple.com/us/app/infestor/id577138009?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Ravenous Games Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ravenous-games-inc./id344310480?uo=4>© Ravenous Games Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple2/v4/81/10/2c/81102c08-1ca4-7565-c674-51e364ed1353/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18907801/61588fa4-856d-11e6-87da-b18cafa809eb.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18872869/e13d2cd6-84bc-11e6-949d-e931b4992f8d.png)
https://cloud.githubusercontent.com/assets/20930745/18872869/e13d2cd6-84bc-11e6-949d-e931b4992f8d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18872883/f1ceea9e-84bc-11e6-8550-69404b0fa049.png
