### ISSUE TITLE
The Path To Luma

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6232]
**App Name:** The Path To Luma
**Bundle ID:** com.NRG.PathToLuma
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1017478824">1017478824</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-path-to-luma/id1017478824?mt=8&uo=4">https://itunes.apple.com/us/app/the-path-to-luma/id1017478824?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** NRG Energy, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nrg-energy-inc./id576806822?uo=4>© NRG Energy, Inc.</a>
**Supported Devices:** iPhone6, iPhone5s, iPodTouchFourthGen, iPhone4S, iPadMini, iPadFourthGen, iPhone-3GS, iPadFourthGen4G, iPodTouchFifthGen, iPadThirdGen4G, iPadMini4G, iPhone6Plus, iPodTouchSixthGen, iPhone5c, iPad2Wifi, iPhone5, iPad23G, iPhone4, iPadThirdGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/40/4b/42/404b42c6-36d7-de14-6ee9-4c382bfc4d06/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9680254/1d040dfa-52bb-11e5-86ba-a814df3ac4ac.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9516446/49a48d7e-4c6e-11e5-883a-81eaa4bed4b4.png
https://cloud.githubusercontent.com/assets/3090247/9516446/49a48d7e-4c6e-11e5-883a-81eaa4bed4b4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9516447/4b6eba94-4c6e-11e5-8954-7c17834236b4.png

**Comment by dreamnet** [comment]
@ivanov007 It's good, but I think we need bigger lines between the main objects... ?

**Comment by ivanov007** [comment]
ok I'll give it another try

**Comment by ivanov007** [comment]
ok here's another try with a little more black
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9680109/0569d3ce-52ba-11e5-8431-f79324fd11fe.png)
https://cloud.githubusercontent.com/assets/3090247/9680109/0569d3ce-52ba-11e5-8431-f79324fd11fe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9680110/056eb4c0-52ba-11e5-806a-e44e0bc0aa47.png

**Comment by dreamnet** [comment]
@ivanov007 Oh yeah - that's great! :+1:
