### ISSUE TITLE
Data Counter - Universal Data Usage Monitor

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6233]
**App Name:** Data Counter - Universal Data Usage Monitor
**Bundle ID:** DataCounter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=397348286">397348286</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/data-counter-universal-data/id397348286?mt=8&uo=4">https://itunes.apple.com/us/app/data-counter-universal-data/id397348286?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Slybees srls
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/slybees/id705864064?uo=4>© Slybees</a>
**Supported Devices:** iPadThirdGen4G, iPodTouchFifthGen, iPhone6, iPhone4S, iPhone4, iPad2Wifi, iPhone5c, iPad23G, iPhone6Plus, iPhone5, iPhone5s, iPodTouchSixthGen, iPadFourthGen4G, iPadThirdGen, iPadFourthGen, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/c2/a3/b4/c2a3b403-121d-163d-f4ef-8e094ee1f7e2/mzl.arafycbm.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9516982/0762ac94-4c72-11e5-99ee-05e2b2fdc43c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9516982/0762ac94-4c72-11e5-99ee-05e2b2fdc43c.png)
https://cloud.githubusercontent.com/assets/3090247/9516982/0762ac94-4c72-11e5-99ee-05e2b2fdc43c.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9516978/05a92e8c-4c72-11e5-966e-b50a7ab22163.png)
https://cloud.githubusercontent.com/assets/3090247/9516978/05a92e8c-4c72-11e5-966e-b50a7ab22163.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9516979/05ad47ba-4c72-11e5-819c-75e266ebc6d2.png)
https://cloud.githubusercontent.com/assets/3090247/9516979/05ad47ba-4c72-11e5-819c-75e266ebc6d2.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/9516997/27f48c2a-4c72-11e5-9dac-36f2e4a00a2c.png
https://cloud.githubusercontent.com/assets/3090247/9516999/2803fc64-4c72-11e5-9ebc-d356cd64d472.png
https://cloud.githubusercontent.com/assets/3090247/9516998/27f9a0e8-4c72-11e5-851f-8c689d956440.png

**Comment by TheRyanKing** [comment]
I vote for the first rendition

**Comment by dreamnet** [comment]
Yup, the first one.
