### ISSUE TITLE
Rhode Island Travel Guide by Triposo featuring Providence, Newport and more!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6237]
**App Name:** Rhode Island Travel Guide by Triposo featuring Providence, Newport and more!
**Bundle ID:** com.triposo.rhodeisland
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=626092889">626092889</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rhode-island-travel-guide/id626092889?mt=8&uo=4">https://itunes.apple.com/us/app/rhode-island-travel-guide/id626092889?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPadFourthGen4G, iPadThirdGen4G, iPodTouchSixthGen, iPodTouchFifthGen, iPhone5s, iPadMini, iPadMini4G, iPadFourthGen, iPhone6Plus, iPhone4, iPhone5, iPad2Wifi, iPad23G, iPhone5c, iPadThirdGen, iPhone6, iPhone4S
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/29/a9/52/29a952ad-d55c-fefc-a79b-6d7d30b62836/mzl.wjuhjbrg.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)

**Comment by ivanov007** [comment]
Same icon as #6124 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)
https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8971983/04fa70b8-3656-11e5-991e-0169cc50e885.png
