### ISSUE TITLE
New Hampshire Travel Guide by Triposo featuring Concord, Portsmouth and more!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6238]
**App Name:** New Hampshire Travel Guide by Triposo featuring Concord, Portsmouth and more!
**Bundle ID:** com.triposo.newhampshire
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=625649152">625649152</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-hampshire-travel-guide/id625649152?mt=8&uo=4">https://itunes.apple.com/us/app/new-hampshire-travel-guide/id625649152?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPhone5s, iPhone5, iPadFourthGen, iPadMini4G, iPodTouchSixthGen, iPhone4S, iPhone4, iPadThirdGen, iPhone5c, iPad2Wifi, iPhone6Plus, iPadThirdGen4G, iPad23G, iPhone6, iPadFourthGen4G, iPadMini, iPodTouchFifthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/c8/55/18/c85518a7-5b01-ae0e-f1ff-de447639901a/mzl.qkcerxpb.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)

**Comment by ivanov007** [comment]
Same icon as #6124 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)
https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8971983/04fa70b8-3656-11e5-991e-0169cc50e885.png
