### ISSUE TITLE
Puffin Browser Plus - Fast & Flash

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6239]
**App Name:** Puffin Browser Plus - Fast & Flash
**Bundle ID:** com.cloudmosa.puffin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406239138">406239138</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/puffin-browser-plus-fast-flash/id406239138?mt=8&uo=4">https://itunes.apple.com/us/app/puffin-browser-plus-fast-flash/id406239138?mt=8&uo=4</a>
**App Version:** 4.5.0
**Seller:** CloudMosa, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cloudmosa-inc./id406239141?uo=4>© CloudMosa, Inc.</a>
**Supported Devices:** iPhone4S, iPodTouchFifthGen, iPhone6Plus, iPadThirdGen4G, iPadThirdGen, iPhone5c, iPhone5s, iPadMini, iPad23G, iPodTouchFourthGen, iPadFourthGen, iPadMini4G, iPhone6, iPhone4, iPadFourthGen4G, iPhone5, iPhone-3GS, iPad2Wifi, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/2a/6f/80/2a6f8040-c857-0911-f3f6-7e2aea4f4814/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9594874/d533e5d6-5026-11e5-8c36-c526e8ab85f1.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9594874/d533e5d6-5026-11e5-8c36-c526e8ab85f1.png)
https://cloud.githubusercontent.com/assets/3090247/9594874/d533e5d6-5026-11e5-8c36-c526e8ab85f1.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9594912/6eb33310-5027-11e5-9089-b96eb25ca8de.png)
https://cloud.githubusercontent.com/assets/3090247/9594912/6eb33310-5027-11e5-9089-b96eb25ca8de.png

--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9594879/eb3d1866-5026-11e5-986f-bdf3e10a41c8.png
https://cloud.githubusercontent.com/assets/3090247/9594880/eb4b7f8c-5026-11e5-8871-64c345c7bb64.png

**Comment by dreamnet** [comment]
@ivanov007 Very good! Taking the first one. :+1:
