### ISSUE TITLE
The Ascension

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6240]
**App Name:** The Ascension
**Bundle ID:** com.bulkypix.up
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1002503656">1002503656</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-ascension/id1002503656?mt=8&uo=4">https://itunes.apple.com/us/app/the-ascension/id1002503656?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** BULKYPIX
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bulkypix/id304521749?uo=4>© Bulkypix</a>
**Supported Devices:** iPadThirdGen4G, iPhone5c, iPhone4, iPodTouchSixthGen, iPhone4S, iPadFourthGen, iPodTouchFifthGen, iPadMini, iPhone5s, iPhone5, iPadFourthGen4G, iPadThirdGen, iPhone6, iPad2Wifi, iPhone-3GS, iPad23G, iPodTouchFourthGen, iPadMini4G, iPhone6Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/2c/b2/fe/2cb2fe37-9f49-85bd-6948-a841fa03a5ef/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9541299/697b881e-4d2c-11e5-9e60-a57f93695804.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9541299/697b881e-4d2c-11e5-9e60-a57f93695804.png)
https://cloud.githubusercontent.com/assets/3090247/9541299/697b881e-4d2c-11e5-9e60-a57f93695804.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9541315/843d9304-4d2c-11e5-9ed5-59415483bb5f.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
