### ISSUE TITLE
Rolando

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6241]
**App Name:** Rolando
**Bundle ID:** com.ngmoco.rolando
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=299461156">299461156</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rolando/id299461156?mt=8&uo=4">https://itunes.apple.com/us/app/rolando/id299461156?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** ngmoco, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ngmoco-llc/id293559501?uo=4>© ngmoco, LLC</a>
**Supported Devices:** iPodTouchThirdGen, iPad2Wifi, iPad23G, iPadThirdGen4G, iPadMini, iPhone6Plus, iPadFourthGen, iPodTouchFourthGen, iPhone5, iPhone-3GS, iPadWifi, iPodTouchFifthGen, iPhone5c, iPhone, iPod-touch-with-mic, iPadThirdGen, iPodTouchSixthGen, iPadMini4G, iPad3G, iPhone5s, iPhone4S, iPhone4, iPhone6, iPod-touch, iPadFourthGen4G, iPhone-3G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/4b/2d/e4/mzl.ebjviiyk.tif/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9542261/e1d64166-4d34-11e5-8921-8e9d6ea43df8.png)

**Comment by ivanov007** [comment]
Icon needs update (Grays)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9542261/e1d64166-4d34-11e5-8921-8e9d6ea43df8.png)
https://cloud.githubusercontent.com/assets/3090247/9542261/e1d64166-4d34-11e5-8921-8e9d6ea43df8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9542290/14e1f992-4d35-11e5-861a-ea543ee33bee.png

**Comment by dreamnet** [comment]
@ivanov007 Source is missing...

**Comment by ivanov007** [comment]
Woops sorry, I'll upload it as soon as I get home
