### ISSUE TITLE
iTrans NYC Subway

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6243]
**App Name:** iTrans NYC Subway
**Bundle ID:** info.itrans.NYC
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=283492923">283492923</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/itrans-nyc-subway/id283492923?mt=8&uo=4">https://itunes.apple.com/us/app/itrans-nyc-subway/id283492923?mt=8&uo=4</a>
**App Version:** 8.0.1
**Seller:** Adam Ernst
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/itrans/id283492926?uo=4>© iTrans</a>
**Supported Devices:** iPadMini, iPodTouchFifthGen, iPadThirdGen4G, iPhone6Plus, iPodTouchSixthGen, iPadThirdGen, iPhone4, iPadFourthGen, iPadMini4G, iPhone5c, iPad23G, iPhone4S, iPhone5, iPadFourthGen4G, iPad2Wifi, iPhone6, iPhone5s
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/74/71/fb/7471fb9d-5697-cb8f-df92-403a1c0fdf9b/mzl.nwbpdswe.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569052/013d811a-4f5e-11e5-9b90-dc594bb355a2.png)

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569052/013d811a-4f5e-11e5-9b90-dc594bb355a2.png)
https://cloud.githubusercontent.com/assets/2068130/9569052/013d811a-4f5e-11e5-9b90-dc594bb355a2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9569054/12762036-4f5e-11e5-9a5d-9217c9c0d006.png

**Comment by dreamnet** [comment]
Icon is already in the repo. No futher action needed.
