### ISSUE TITLE
Clear Currency Converter

### ISSUE THREAD

**Issue by hectorlmeraz** [glasklart/hd#6244]
**App Name:** Clear Currency Converter
**Bundle ID:** com.xadavetech.currencychanger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=946607423">946607423</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clear-currency-converter/id946607423?mt=8&uo=4">https://itunes.apple.com/us/app/clear-currency-converter/id946607423?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Davetech Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/davetech-co.-ltd./id849422948?uo=4>© Davetech Co., Ltd.</a>
**Supported Devices:** iPadFourthGen, iPadMini4G, iPhone5s, iPodTouchSixthGen, iPhone5, iPhone5c, iPadMini, iPadThirdGen, iPhone4S, iPodTouchFifthGen, iPadFourthGen4G, iPhone6Plus, iPad23G, iPhone6, iPad2Wifi, iPadThirdGen4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/3a/21/13/3a211366-be42-9b84-3cbb-b22433d60303/mzl.vjbwlfti.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569426/666fc18a-4f6b-11e5-9b79-93fb3de63f2d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569426/666fc18a-4f6b-11e5-9b79-93fb3de63f2d.png)
https://cloud.githubusercontent.com/assets/2068130/9569426/666fc18a-4f6b-11e5-9b79-93fb3de63f2d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9569428/80213da2-4f6b-11e5-846a-a457218f0a30.png
