### ISSUE TITLE
GalleryVault - Private Photos and Videos Vault (Hide Photos, Lock Videos)

### ISSUE THREAD

**Issue by hectorlmeraz** [glasklart/hd#6245]
**App Name:** GalleryVault - Private Photos and Videos Vault (Hide Photos, Lock Videos)
**Bundle ID:** com.thinkyeah.iGalleryVault
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=899163792">899163792</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/galleryvault-private-photos/id899163792?mt=8&uo=4">https://itunes.apple.com/us/app/galleryvault-private-photos/id899163792?mt=8&uo=4</a>
**App Version:** 1.8.0
**Seller:** Think Yeah
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/think-yeah/id899163795?uo=4>© Think Yeah</a>
**Supported Devices:** iPadMini, iPhone5c, iPodTouchSixthGen, iPadFourthGen4G, iPhone6Plus, iPadMini4G, iPhone5s, iPhone4, iPhone6, iPhone5, iPadThirdGen4G, iPhone4S, iPodTouchFifthGen, iPad2Wifi, iPad23G, iPadThirdGen, iPadFourthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/40/e7/62/40e762e5-d6cf-932c-9cdb-de704937c403/mzl.hsowkmcz.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9596931/f15d49a0-507b-11e5-8a9d-f355e7a5f65f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9596931/f15d49a0-507b-11e5-8a9d-f355e7a5f65f.png)
https://cloud.githubusercontent.com/assets/2068130/9596931/f15d49a0-507b-11e5-8a9d-f355e7a5f65f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9596935/01f3c9ec-507c-11e5-901a-77d6ccbb01c6.png
