### ISSUE TITLE
Dungeon Hunter 5

### ISSUE THREAD

**Issue by hectorlmeraz** [glasklart/hd#6246]
**App Name:** Dungeon Hunter 5
**Bundle ID:** com.gameloft.DungeonHunter5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=885823239">885823239</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dungeon-hunter-5/id885823239?mt=8&uo=4">https://itunes.apple.com/us/app/dungeon-hunter-5/id885823239?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Gameloft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gameloft/id282764297?mt=8&uo=4>© Gameloft</a>
**Supported Devices:** iPhone5c, iPadFourthGen4G, iPhone5s, iPadMini4G, iPadThirdGen4G, iPhone6, iPodTouchFifthGen, iPhone4, iPad23G, iPadThirdGen, iPhone4S, iPadMini, iPhone5, iPadFourthGen, iPhone6Plus, iPad2Wifi, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/90/35/ac/9035ac6c-a003-ccc6-7473-cec6daf91df9/mzl.dgsehruj.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10179412/13b06bea-6706-11e5-9c75-e5e8c1f1b936.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10179412/13b06bea-6706-11e5-9c75-e5e8c1f1b936.png)
https://cloud.githubusercontent.com/assets/2068130/10179412/13b06bea-6706-11e5-9c75-e5e8c1f1b936.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10179420/24399c84-6706-11e5-95a4-3d4e377fc833.png
