### ISSUE TITLE
FIFA 15 Ultimate Team by EA SPORTS

### ISSUE THREAD

**Issue by hectorlmeraz** [glasklart/hd#6247]
**App Name:** FIFA 15 Ultimate Team by EA SPORTS
**Bundle ID:** com.ea.fifa15.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=870794720">870794720</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fifa-15-ultimate-team-by-ea/id870794720?mt=8&uo=4">https://itunes.apple.com/us/app/fifa-15-ultimate-team-by-ea/id870794720?mt=8&uo=4</a>
**App Version:** 1.4.4
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4>© Electronic Arts</a>
**Supported Devices:** iPhone5, iPad23G, iPodTouchFourthGen, iPadMini4G, iPadFourthGen, iPhone4, iPhone4S, iPadMini, iPhone6, iPodTouchSixthGen, iPodTouchFifthGen, iPhone6Plus, iPad2Wifi, iPadThirdGen4G, iPadFourthGen4G, iPhone5s, iPhone5c, iPadThirdGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/03/4c/c2/034cc2f8-1011-c008-ebe2-ef6136602581/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9676456/4930e3ec-52cc-11e5-8fda-e1e9937e9198.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9676456/4930e3ec-52cc-11e5-8fda-e1e9937e9198.png)
https://cloud.githubusercontent.com/assets/2068130/9676456/4930e3ec-52cc-11e5-8fda-e1e9937e9198.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9676462/5de1687a-52cc-11e5-92ce-9867a73c8ca3.png
