### ISSUE TITLE
Modern Combat 5: Blackout

### ISSUE THREAD

**Issue by hectorlmeraz** [glasklart/hd#6248]
**App Name:** Modern Combat 5: Blackout
**Bundle ID:** com.gameloft.ModernCombat5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=656176278">656176278</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/modern-combat-5-blackout/id656176278?mt=8&uo=4">https://itunes.apple.com/us/app/modern-combat-5-blackout/id656176278?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Gameloft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gameloft/id282764297?mt=8&uo=4>© Gameloft</a>
**Supported Devices:** iPhone6, iPhone4S, iPodTouchFifthGen, iPadThirdGen, iPadFourthGen, iPadMini, iPodTouchSixthGen, iPad23G, iPadFourthGen4G, iPad2Wifi, iPhone5, iPadMini4G, iPhone5c, iPadThirdGen4G, iPhone6Plus, iPhone5s, iPhone4
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/b2/ed/ab/b2edab5d-3cb8-b2dd-15a2-e729b20064a0/pr_source.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13030206/899ffb7e-d2a2-11e5-9e2b-65fa18dfa9dc.png)

**Comment by Anuskuss** [comment]
Use the poster as icon
<img src="http://i1.ytimg.com/vi/_Vz8RD9Cyxs/maxresdefault.jpg" width="500" />

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12153561/cf0b9368-b4ba-11e5-98b6-31d6f7372d5d.png)
https://cloud.githubusercontent.com/assets/2068130/12153561/cf0b9368-b4ba-11e5-98b6-31d6f7372d5d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12153581/dd6e6016-b4ba-11e5-866b-7b57636e0041.png

**Comment by Anuskuss** [comment]
Nice 😉

**Comment by Anuskuss** [comment]
Would it be possible to remove **Blackout** out of the icon, because it's to small to be read and this would allow the rest of the icon to be bigger.

**Comment by ivanov007** [comment]
it would be possible, but it will not allow the icon to be any bigger since "modern combat" are touching the borders, the 5 can get a little bigger although, but I don't know if it's worthy

**Comment by Anuskuss** [comment]
@dreamnet Could you provide a version with a bigger **5** and without **BLACKOUT** for me and then we could decide together :3

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12856234/34af728e-cc44-11e5-81fa-78f3c245d35f.png)
https://cloud.githubusercontent.com/assets/2068130/12856234/34af728e-cc44-11e5-81fa-78f3c245d35f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12856248/4489e856-cc44-11e5-9bb2-a401dc14247b.png

**Comment by dreamnet** [comment]
@Anuskuss ?

**Comment by ivanov007** [comment]
I think it looks good :+1:

**Comment by Anuskuss** [comment]
Sorry @dreamnet :disappointed_relieved: 
Yeah, second one looks better. The **5** just a tiny tiny bit smaller and it's perfect :+1: :+1: :+1:

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13030206/899ffb7e-d2a2-11e5-9e2b-65fa18dfa9dc.png)
https://cloud.githubusercontent.com/assets/2068130/13030206/899ffb7e-d2a2-11e5-9e2b-65fa18dfa9dc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13030210/9ac4fada-d2a2-11e5-93fe-89341d6b95bf.png
