### ISSUE TITLE
DVO: Daily Devotionals, Bible Verses and Quotes

### ISSUE THREAD

**Issue by hectorlmeraz** [glasklart/hd#6249]
**App Name:** DVO: Daily Devotionals, Bible Verses and Quotes
**Bundle ID:** com.alphapod.bibleverses
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606099082">606099082</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dvo-daily-devotionals-bible-verses-and-quotes/id606099082?uo=4">https://apps.apple.com/us/app/dvo-daily-devotionals-bible-verses-and-quotes/id606099082?uo=4</a>
**App Version:** 3.0.7
**Seller:** AlphaPod Sdn. Bhd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/alphapod-sdn-bhd/id414179059?uo=4">© AlphaPod Sdn. Bhd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple111/v4/f4/3f/b5/f43fb597-6ea2-52d0-049c-030dcefd0435/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60383193-34893c80-9a6e-11e9-8029-42d89e0e01c5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569311/5010b54c-4f67-11e5-801c-e156cc38a94b.png)
https://cloud.githubusercontent.com/assets/2068130/9569311/5010b54c-4f67-11e5-801c-e156cc38a94b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9569313/5e503d08-4f67-11e5-9739-bd1bde67bcf3.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60383193-34893c80-9a6e-11e9-8029-42d89e0e01c5.png)
https://user-images.githubusercontent.com/20930745/60383193-34893c80-9a6e-11e9-8029-42d89e0e01c5.png

Source:
https://user-images.githubusercontent.com/20930745/60383194-35ba6980-9a6e-11e9-97ec-033af4615096.png
