### ISSUE TITLE
Max Payne Mobile

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#625]
**App Name:** Max Payne Mobile
**Bundle ID:** com.rockstargames.maxpayne
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=512142109">512142109</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/max-payne-mobile/id512142109?mt=8&uo=4">https://itunes.apple.com/us/app/max-payne-mobile/id512142109?mt=8&uo=4</a>
**App Version:** 1.4.3
**Seller:** Rockstar Games, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rockstar-games/id330049731?uo=4">© Rockstar Games</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/f1/1a/5f/f11a5f39-c9ff-6b77-da0d-f7785a5c17c2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32398539-4f34d61a-c0f0-11e7-8be1-4369bf15521f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32398539-4f34d61a-c0f0-11e7-8be1-4369bf15521f.png)
https://user-images.githubusercontent.com/2068130/32398539-4f34d61a-c0f0-11e7-8be1-4369bf15521f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32398554-5f88c986-c0f0-11e7-85d0-9fa967e7b1c5.png
