### ISSUE TITLE
Down The Mountain

### ISSUE THREAD

**Issue by hectorlmeraz** [glasklart/hd#6250]
**App Name:** Down The Mountain
**Bundle ID:** com.umbrella.downthemountain
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=992730639">992730639</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/down-the-mountain/id992730639?mt=8&uo=4">https://itunes.apple.com/us/app/down-the-mountain/id992730639?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** sven magnus
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sven-magnus/id330537789?uo=4>© sven magnus</a>
**Supported Devices:** iPhone4, iPhone6Plus, iPodTouchFifthGen, iPadMini, iPhone6, iPadMini4G, iPodTouchFourthGen, iPad2Wifi, iPadFourthGen, iPodTouchSixthGen, iPadThirdGen4G, iPadThirdGen, iPhone5, iPhone5c, iPhone5s, iPad23G, iPhone-3GS, iPhone4S, iPadFourthGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/20/66/90/2066901f-261c-4c11-6507-ff75cd8dd15b/mzl.iutwjqdi.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10032440/64647938-6183-11e5-8259-68075189eb49.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10032440/64647938-6183-11e5-8259-68075189eb49.png)
https://cloud.githubusercontent.com/assets/2068130/10032440/64647938-6183-11e5-8259-68075189eb49.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10032450/758a7ca8-6183-11e5-978d-7c33bcae18c8.png
