### ISSUE TITLE
The Blockheads

### ISSUE THREAD

**Issue by hectorlmeraz** [glasklart/hd#6251]
**App Name:** The Blockheads
**Bundle ID:** com.majicjungle.blockheads
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519596406">519596406</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-blockheads/id519596406?mt=8&uo=4">https://itunes.apple.com/us/app/the-blockheads/id519596406?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** David Frampton
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/majic-jungle-software/id284896688?uo=4>© Majic Jungle Software</a>
**Supported Devices:** iPodTouchFifthGen, iPodTouchFourthGen, iPad2Wifi, iPhone4S, iPhone4, iPhone6Plus, iPadThirdGen, iPodTouchThirdGen, iPadFourthGen4G, iPhone5s, iPadThirdGen4G, iPhone-3GS, iPhone5, iPadMini4G, iPad23G, iPhone5c, iPadMini, iPhone6, iPadWifi, iPodTouchSixthGen, iPadFourthGen, iPad3G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/76/e6/ca/76e6ca27-6f46-a932-fa61-d0cb5da55fe8/mzl.vtbcmxzq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9677496/07255140-52db-11e5-8459-a8473b4943a0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9677496/07255140-52db-11e5-8459-a8473b4943a0.png)
https://cloud.githubusercontent.com/assets/2068130/9677496/07255140-52db-11e5-8459-a8473b4943a0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9677500/15763778-52db-11e5-8b87-877d0d6906a3.png
