### ISSUE TITLE
SUBWAY®

### ISSUE THREAD

**Issue by hectorlmeraz** [glasklart/hd#6252]
**App Name:** SUBWAY®
**Bundle ID:** com.subway.mobile.subwayapp03
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=901941015">901941015</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/subway/id901941015?mt=8&uo=4">https://itunes.apple.com/us/app/subway/id901941015?mt=8&uo=4</a>
**App Version:** 8.6.0
**Seller:** Doctor's Associates Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/subway-restaurants/id860751246?mt=8&uo=4">© SUBWAY Restaurants</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/1b/bb/63/1bbb632c-58f6-fef5-5337-391dde19b172/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54256579-c8d1a100-455c-11e9-825e-13d0dfe98f6f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569297/e2d5e2ae-4f66-11e5-8ea7-771ec63bdabc.png)
https://cloud.githubusercontent.com/assets/2068130/9569297/e2d5e2ae-4f66-11e5-8ea7-771ec63bdabc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9569298/f12a82a6-4f66-11e5-8a74-6b73e00563ca.png

**Comment by Christian9901** [comment]
needs update

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54256579-c8d1a100-455c-11e9-825e-13d0dfe98f6f.png)
https://user-images.githubusercontent.com/20930745/54256579-c8d1a100-455c-11e9-825e-13d0dfe98f6f.png

Source:
(https://user-images.githubusercontent.com/20930745/54256516-9162f480-455c-11e9-87d9-126014f1e990.png
