### ISSUE TITLE
Camly Pro – Photo Editor & Collage Maker

### ISSUE THREAD

**Issue by hectorlmeraz** [glasklart/hd#6253]
**App Name:** Camly Pro – Photo Editor & Collage Maker
**Bundle ID:** com.camlyapp.CamlyPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=966149642">966149642</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camly-pro-photo-editor-collage/id966149642?mt=8&uo=4">https://itunes.apple.com/us/app/camly-pro-photo-editor-collage/id966149642?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Aleksandr Kobozev
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aleksandr-kobozev/id662575132?uo=4>© Aleksandr Kobozev</a>
**Supported Devices:** iPadThirdGen4G, iPhone4, iPhone5, iPhone6, iPodTouchSixthGen, iPhone5s, iPodTouchFifthGen, iPadFourthGen, iPadMini4G, iPad2Wifi, iPadFourthGen4G, iPhone4S, iPadThirdGen, iPhone6Plus, iPhone5c, iPadMini, iPad23G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/c4/02/ef/c402ef9b-9789-72bd-00cd-343d4cde4236/mzl.eouvjqbs.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9978129/d3548630-5f21-11e5-8a9c-1155188110c1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9978129/d3548630-5f21-11e5-8a9c-1155188110c1.png)
https://cloud.githubusercontent.com/assets/2068130/9978129/d3548630-5f21-11e5-8a9c-1155188110c1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9978133/e699694a-5f21-11e5-81d6-0b8a2b6b6076.png
