### ISSUE TITLE
Urban Engines Maps: Mixed-Mode trip planner (transit, driving, biking), offline maps, real-time transit schedules

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6255]
**App Name:** Urban Engines Maps: Mixed-Mode trip planner (transit, driving, biking), offline maps, real-time transit schedules
**Bundle ID:** com.urbanengines.transit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=852787978">852787978</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/urban-engines-maps-mixed-mode/id852787978?mt=8&uo=4">https://itunes.apple.com/us/app/urban-engines-maps-mixed-mode/id852787978?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Urban Engines, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/urban-engines-inc./id472438053?uo=4>© Urban Engines, Inc.</a>
**Supported Devices:** iPhone6Plus, iPad23G, iPadFourthGen, iPhone5c, iPhone4, iPhone4S, iPadFourthGen4G, iPadMini4G, iPad2Wifi, iPodTouchSixthGen, iPadThirdGen, iPhone6, iPadMini, iPhone5s, iPodTouchFifthGen, iPadThirdGen4G, iPhone5
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/48/cd/00/48cd000a-05b1-b505-4807-774c50e4516b/mzl.selcqfkj.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9563558/d466261e-4e87-11e5-8987-53bd9b02c977.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9563558/d466261e-4e87-11e5-8987-53bd9b02c977.png)
https://cloud.githubusercontent.com/assets/10730122/9563558/d466261e-4e87-11e5-8987-53bd9b02c977.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9563552/d1ab18a8-4e87-11e5-99ab-2ec38e9b4786.png
