### ISSUE TITLE
Edsby

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6256]
**App Name:** Edsby
**Bundle ID:** com.edsby.edsby
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=548642814">548642814</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/edsby/id548642814?uo=4">https://apps.apple.com/us/app/edsby/id548642814?uo=4</a>
**App Version:** 1.1.25
**Seller:** CoreFour Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/corefour-inc/id548642817?uo=4">© CoreFour Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/81/13/05/81130520-165b-b2ab-0d5e-1748e07d4f13/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60389947-e6a32180-9acb-11e9-8f88-af0cc89a3933.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9563513/9c32d77a-4e86-11e5-831a-c81a10d5083d.png)
https://cloud.githubusercontent.com/assets/10730122/9563513/9c32d77a-4e86-11e5-831a-c81a10d5083d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9563512/987a519e-4e86-11e5-8727-379ae5bcee5c.png

---

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9563516/b3bda960-4e86-11e5-9aa4-b355763c4904.png)
https://cloud.githubusercontent.com/assets/10730122/9563516/b3bda960-4e86-11e5-9aa4-b355763c4904.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9563515/b08d1276-4e86-11e5-9c1c-d8deeed5551c.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9563521/d52c35f8-4e86-11e5-8d18-e915999eb347.png)
https://cloud.githubusercontent.com/assets/10730122/9563521/d52c35f8-4e86-11e5-8d18-e915999eb347.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9563520/d1afb5e4-4e86-11e5-94cf-f256320c0bb7.png

---

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9563527/ea02e56c-4e86-11e5-9d1c-2bd967f32253.png)
https://cloud.githubusercontent.com/assets/10730122/9563527/ea02e56c-4e86-11e5-9d1c-2bd967f32253.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9563525/e23f3466-4e86-11e5-8fa5-f8ec033437c4.png

**Comment by dreamnet** [comment]
@Trubbel Taking the last one. :+1:

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60389947-e6a32180-9acb-11e9-8f88-af0cc89a3933.png)
https://user-images.githubusercontent.com/2068130/60389947-e6a32180-9acb-11e9-8f88-af0cc89a3933.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60389950-f6bb0100-9acb-11e9-8c12-df752cb0b786.png
