### ISSUE TITLE
Firehouse Subs App

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6257]
**App Name:** Firehouse Subs App
**Bundle ID:** com.relevantmobile.firehousesubs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=894658475">894658475</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/firehouse-subs-app/id894658475?mt=8&uo=4">https://itunes.apple.com/us/app/firehouse-subs-app/id894658475?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Relevant Mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/relevant/id475337047?uo=4>© Relevant</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple49/v4/ff/24/58/ff24587c-22eb-e445-f09d-b138b8ecdd75/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18245538/1092d872-7366-11e6-9095-6751e4d019fc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569275/5ecd9baa-4f66-11e5-87d1-e0cf6c69e0ce.png)
https://cloud.githubusercontent.com/assets/2068130/9569275/5ecd9baa-4f66-11e5-87d1-e0cf6c69e0ce.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9569278/6d5af8e8-4f66-11e5-986c-31a5efc67d01.png

**Comment by boxermansr** [comment]
Please update for new (updated) -large icons.
Thank you.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18245538/1092d872-7366-11e6-9095-6751e4d019fc.png)
https://cloud.githubusercontent.com/assets/20930745/18245538/1092d872-7366-11e6-9095-6751e4d019fc.png

Source: (from dreamnet)
https://cloud.githubusercontent.com/assets/20930745/18245566/3b5901e4-7366-11e6-908c-6ca7c3451041.png
