### ISSUE TITLE
1010!

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6258]
**App Name:** 1010!
**Bundle ID:** com.gramgames.1010
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911793120">911793120</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1010!/id911793120?mt=8&uo=4">https://itunes.apple.com/us/app/1010!/id911793120?mt=8&uo=4</a>
**App Version:** 9
**Seller:** GG OYUN BILISIM YAZILIM VE PAZARLAMA A S
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gramgames/id582999647?uo=4>© GramGames</a>
**Supported Devices:** iPhone6, iPhone5s, iPhone-3GS, iPodTouchFifthGen, iPhone6Plus, iPad2Wifi, iPadThirdGen, iPadThirdGen4G, iPadFourthGen4G, iPhone5c, iPodTouchSixthGen, iPadFourthGen, iPodTouchFourthGen, iPhone4S, iPhone4, iPhone5, iPadMini, iPad23G, iPadMini4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/cd/7a/46/cd7a4692-52d7-bd99-365c-7f3ca3890edf/mzl.rccbhtgf.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9586466/5e607d56-501d-11e5-967b-43d6cdd2bcd1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9586466/5e607d56-501d-11e5-967b-43d6cdd2bcd1.png)
https://cloud.githubusercontent.com/assets/2068130/9586466/5e607d56-501d-11e5-967b-43d6cdd2bcd1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9586484/6d01e43a-501d-11e5-8d35-63af9bff25c1.png

**Comment by LaCh0uine** [comment]
@dreamnet thank you again :)
