### ISSUE TITLE
AMC - Latest full episodes and extras

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6259]
**App Name:** AMC - Latest full episodes and extras
**Bundle ID:** com.amctve.amcfullepisodes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1025120568">1025120568</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amc-latest-full-episodes-extras/id1025120568?mt=8&uo=4">https://itunes.apple.com/us/app/amc-latest-full-episodes-extras/id1025120568?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** AMC Network Entertainment LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/amc-network-entertainment/id309385037?uo=4>© AMC Network Entertainment LLC</a>
**Supported Devices:** iPhone5c, iPadMini, iPadFourthGen, iPhone6Plus, iPadThirdGen, iPodTouchFifthGen, iPadThirdGen4G, iPadMini4G, iPad2Wifi, iPhone6, iPodTouchSixthGen, iPhone4S, iPhone5, iPad23G, iPhone4, iPhone5s, iPadFourthGen4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/d1/7b/92/d17b9206-add0-a327-f171-6f1217feaa01/mzl.hrwgerhq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569126/cdd3c4a8-4f60-11e5-8817-9123be83a659.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569126/cdd3c4a8-4f60-11e5-8817-9123be83a659.png)
https://cloud.githubusercontent.com/assets/2068130/9569126/cdd3c4a8-4f60-11e5-8817-9123be83a659.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9569129/df534820-4f60-11e5-9fb7-34b379e08f5d.png
