### ISSUE TITLE
Puffin Browser Free - Fast & Flash

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#6260]
**App Name:** Puffin Browser Free - Fast & Flash
**Bundle ID:** com.cloudmosa.PuffinFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=472937654">472937654</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/puffin-browser-free-fast-flash/id472937654?mt=8&uo=4">https://itunes.apple.com/us/app/puffin-browser-free-fast-flash/id472937654?mt=8&uo=4</a>
**App Version:** 4.5.0
**Seller:** CloudMosa, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cloudmosa-inc./id406239141?uo=4>© CloudMosa, Inc.</a>
**Supported Devices:** iPadMini, iPhone4S, iPadMini4G, iPhone5s, iPhone5c, iPhone4, iPad2Wifi, iPad23G, iPhone-3GS, iPhone6Plus, iPodTouchFifthGen, iPadFourthGen4G, iPodTouchFourthGen, iPhone5, iPodTouchSixthGen, iPadThirdGen, iPadThirdGen4G, iPhone6, iPadFourthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/f9/01/b3/f901b30f-796f-a6a4-a0af-d540d1f3dc15/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9594874/d533e5d6-5026-11e5-8c36-c526e8ab85f1.png)

**Comment by dreamnet** [comment]
Refers to #6239.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9594874/d533e5d6-5026-11e5-8c36-c526e8ab85f1.png)
https://cloud.githubusercontent.com/assets/3090247/9594874/d533e5d6-5026-11e5-8c36-c526e8ab85f1.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9594875/d538b7a0-5026-11e5-9563-db78ec2578bf.png)
https://cloud.githubusercontent.com/assets/3090247/9594875/d538b7a0-5026-11e5-9563-db78ec2578bf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9594879/eb3d1866-5026-11e5-986f-bdf3e10a41c8.png
https://cloud.githubusercontent.com/assets/3090247/9594880/eb4b7f8c-5026-11e5-8871-64c345c7bb64.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160870-73bd20f8-34c4-11e8-8854-464b5743db65.png)
https://user-images.githubusercontent.com/2068130/38160870-73bd20f8-34c4-11e8-8854-464b5743db65.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38160877-8a6e7d56-34c4-11e8-89d2-83bf7d715b49.png
