### ISSUE TITLE
Lotto24.de - Ihr Lotto-Kiosk im Internet. Für Lotto 6 aus 49, Eurojackpot und Glücksspirale.

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#6261]
**App Name:** Lotto24.de - Ihr Lotto-Kiosk im Internet. Für Lotto 6 aus 49, Eurojackpot und Glücksspirale.
**Bundle ID:** de.lotto24.lottokiosk.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=784389203">784389203</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/lotto24.de-ihr-lotto-kiosk/id784389203?mt=8&uo=4">https://itunes.apple.com/de/app/lotto24.de-ihr-lotto-kiosk/id784389203?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Lotto24 AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/lotto24-ag/id784389206?uo=4>© Lotto24 AG</a>
**Supported Devices:** iPadFourthGen, iPadMini4G, iPhone5s, iPhone5c, iPhone6Plus, iPadThirdGen4G, iPodTouchFifthGen, iPhone4S, iPad2Wifi, iPadThirdGen, iPadFourthGen4G, iPhone4, iPadMini, iPhone6, iPhone5, iPodTouchSixthGen, iPad23G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/ae/72/94/ae7294c4-37ef-6fb5-b120-feca342c1175/mzl.pqctraet.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569488/4941034c-4f6d-11e5-9389-49c5ded6dd2c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9569488/4941034c-4f6d-11e5-9389-49c5ded6dd2c.png)
https://cloud.githubusercontent.com/assets/2068130/9569488/4941034c-4f6d-11e5-9389-49c5ded6dd2c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9569491/585c7e92-4f6d-11e5-81c1-6abcd64d532b.png
