### ISSUE TITLE
Runtastic Butt Trainer, Daily Exercises & Quick Booty Workouts

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6264]
**App Name:** Runtastic Butt Trainer, Daily Exercises & Quick Booty Workouts
**Bundle ID:** com.runtastic.iphone.butttrainer.lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942435348">942435348</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtastic-butt-trainer-daily/id942435348?mt=8&uo=4">https://itunes.apple.com/us/app/runtastic-butt-trainer-daily/id942435348?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** runtastic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/runtastic/id336599885?uo=4>© runtastic</a>
**Supported Devices:** iPhone4S, iPadThirdGen, iPhone6Plus, iPadFourthGen, iPhone4, iPadMini4G, iPadMini, iPodTouchSixthGen, iPad2Wifi, iPad23G, iPhone5, iPhone5s, iPhone5c, iPhone6, iPadFourthGen4G, iPodTouchFifthGen, iPadThirdGen4G
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/b2/d7/04/b2d704b9-4a05-2891-11c8-511145b71894/mzl.xcutnbgo.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9570312/2fa4686e-4f88-11e5-8fbd-0aac334f6dd5.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9570312/2fa4686e-4f88-11e5-8fbd-0aac334f6dd5.png)
https://cloud.githubusercontent.com/assets/10730122/9570312/2fa4686e-4f88-11e5-8fbd-0aac334f6dd5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9570309/2c53e270-4f88-11e5-92c2-49505f4001d6.png

haha :flushed:

**Comment by ivanov007** [comment]
wow what's next runtastic twerking trainer? LOL :wink:

**Comment by dreamnet** [comment]
:laughing:
