### ISSUE TITLE
Ditty by Zya

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6266]
**App Name:** Ditty by Zya
**Bundle ID:** com.zya.ditty
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=957529556">957529556</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ditty-by-zya/id957529556?mt=8&uo=4">https://itunes.apple.com/us/app/ditty-by-zya/id957529556?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** MUSIC MASTERMIND INC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zya/id931581712?uo=4>© Zya</a>
**Supported Devices:** iPhone6, iPadThirdGen4G, iPadMini4G, iPhone4S, iPhone5s, iPhone4, iPodTouchSixthGen, iPodTouchFifthGen, iPadMini, iPad2Wifi, iPadFourthGen4G, iPad23G, iPhone6Plus, iPadFourthGen, iPhone5c, iPhone5, iPadThirdGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/c5/47/71/c54771d0-eb3c-babf-639d-5f0d2a3e9565/mzl.rradwwdk.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9572617/10f349f6-4fb2-11e5-9621-68cf048652c8.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9570425/ac38f77a-4f8b-11e5-85d1-73cc0f0074c4.png)
https://cloud.githubusercontent.com/assets/10730122/9570425/ac38f77a-4f8b-11e5-85d1-73cc0f0074c4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9570424/a6f96650-4f8b-11e5-86e0-3ff44a4ba519.png

**Comment by dreamnet** [comment]
Centered:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9572617/10f349f6-4fb2-11e5-9621-68cf048652c8.png)
https://cloud.githubusercontent.com/assets/2068130/9572617/10f349f6-4fb2-11e5-9621-68cf048652c8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9572624/1ff2ef56-4fb2-11e5-9722-765fff899e1c.png
