### ISSUE TITLE
PhillyD Official

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6270]
**App Name:** PhillyD Official
**Bundle ID:** VYUFXLR7JT.com.geekutils.PhillyD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=356128776">356128776</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/phillyd-official/id356128776?mt=8&uo=4">https://itunes.apple.com/us/app/phillyd-official/id356128776?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Revision3
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/discovery-digital-networks/id723938886?uo=4>© Discovery Digital Networks</a>
**Supported Devices:** iPhone4, iPhone6Plus, iPhone4S, iPodTouchSixthGen, iPadThirdGen, iPadFourthGen4G, iPad23G, iPadThirdGen4G, iPadMini4G, iPodTouchFifthGen, iPad2Wifi, iPhone6, iPhone5, iPhone5s, iPadFourthGen, iPadMini, iPhone5c
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/8e/27/6a/8e276afc-523f-a4be-11d1-9e8f4c1c6c17/mzl.yscmwfow.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9587304/20440b0a-5022-11e5-9c7a-1efc49342f70.png)

**Comment by Trubbel** [comment]
Adding issue for this icon. However, is it possible that anyone can make a better icon than [the current one](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/VYUFXLR7JT.com.geekutils.PhillyD@2x.png)?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9587304/20440b0a-5022-11e5-9c7a-1efc49342f70.png)
https://cloud.githubusercontent.com/assets/2068130/9587304/20440b0a-5022-11e5-9c7a-1efc49342f70.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9587311/2e7c6514-5022-11e5-968e-6f9bc6e14a93.png

**Comment by ivanov007** [comment]
oh I was also working on this}still here's my contribution
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9587681/5e85e430-4fe9-11e5-8768-0ba1b6481738.png)

**Comment by dreamnet** [comment]
Hmmm... can't say witch one is better.... ?

**Comment by Trubbel** [comment]
I will leave this one up for you guys to decide haha. I don't know either. :smile:

**Comment by dreamnet** [comment]
I'm taking my contribution - I think It's more clear. @ivanov007 You can override me if you want. :wink:
