### ISSUE TITLE
Gametime - sports tickets delivered to your phone

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6272]
**App Name:** Gametime - sports tickets delivered to your phone
**Bundle ID:** com.gametimeunited.gametime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=630687854">630687854</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gametime-sports-tickets-delivered/id630687854?mt=8&uo=4">https://itunes.apple.com/us/app/gametime-sports-tickets-delivered/id630687854?mt=8&uo=4</a>
**App Version:** 5.2.1
**Seller:** Gametime United Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gametime-united-inc./id630687857?uo=4>© Gametime United Inc.</a>
**Supported Devices:** iPhone5s, iPadMini, iPadThirdGen4G, iPadMini4G, iPhone4S, iPadFourthGen4G, iPad23G, iPhone6, iPodTouchFifthGen, iPad2Wifi, iPodTouchSixthGen, iPadFourthGen, iPhone6Plus, iPadThirdGen, iPhone5, iPhone5c
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/d6/48/f0/d648f020-a320-3aa3-edce-a6ff74bcdf40/mzl.arwerrkf.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9572846/1a84b9b6-4fb5-11e5-906c-1f7af3bf3634.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9572846/1a84b9b6-4fb5-11e5-906c-1f7af3bf3634.png)
https://cloud.githubusercontent.com/assets/2068130/9572846/1a84b9b6-4fb5-11e5-906c-1f7af3bf3634.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9572850/2833b648-4fb5-11e5-94e4-b6bb73757e04.png
