### ISSUE TITLE
App Annie - Mobile Performance

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6274]
**App Name:** App Annie - Mobile Performance
**Bundle ID:** com.appannie.app.APIV1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=660004961">660004961</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/app-annie-mobile-performance/id660004961?uo=4">https://apps.apple.com/us/app/app-annie-mobile-performance/id660004961?uo=4</a>
**App Version:** 1.54.0
**Seller:** App Annie Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/app-annie/id660004964?uo=4">© App Annie</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/dc/8f/09/dc8f0901-04d3-3c55-f57c-4601f51844d2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83975506-9f84f980-a8f4-11ea-8057-69771a2bb280.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9583344/1a226ca6-500b-11e5-9025-67a941978de4.png)
https://cloud.githubusercontent.com/assets/10730122/9583344/1a226ca6-500b-11e5-9025-67a941978de4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9583342/17eaa610-500b-11e5-954b-fec94aa2f095.png

**Comment by Trubbel** [comment]
Alternate,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9583363/3394dffc-500b-11e5-81d3-4ab12de6a1bb.png)
https://cloud.githubusercontent.com/assets/10730122/9583363/3394dffc-500b-11e5-81d3-4ab12de6a1bb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9583357/3053f152-500b-11e5-8163-3559bd943d35.png

**Comment by dreamnet** [comment]
@Trubbel Taking your second one with a little change:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9624013/e906c5ba-5148-11e5-81d2-4f8d3a02022e.png)
https://cloud.githubusercontent.com/assets/2068130/9624013/e906c5ba-5148-11e5-81d2-4f8d3a02022e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9624026/f917f1b8-5148-11e5-846b-2548156704f0.png

**Comment by Trubbel** [comment]
@dreamnet :+1:

**Comment by Trubbel** [comment]
The icon has been updated. Not sure if I'm good enough to make it. :relaxed:

**Comment by ivanov007** [comment]
wow everything changed, I think we can keep the actual because the new one is kind of overwhelming, but since you have this app installed do you think the actual icon is representative enough @Trubbel ?

**Comment by Trubbel** [comment]
@ivanov007 I don't mind if we keep the current themed icon at all. :wink:

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** App Annie - Mobile Performance
**Bundle ID:** com.appannie.app.APIV1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=660004961">660004961</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/app-annie-mobile-performance/id660004961?uo=4">https://apps.apple.com/us/app/app-annie-mobile-performance/id660004961?uo=4</a>
**App Version:** 1.54.0
**Seller:** App Annie Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/app-annie/id660004964?uo=4">© App Annie</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/dc/8f/09/dc8f0901-04d3-3c55-f57c-4601f51844d2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83975506-9f84f980-a8f4-11ea-8057-69771a2bb280.png)
https://user-images.githubusercontent.com/2068130/83975506-9f84f980-a8f4-11ea-8057-69771a2bb280.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83975529-ae6bac00-a8f4-11ea-9983-4a218ef9273e.png
