### ISSUE TITLE
Android Wear

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6275]
**App Name:** Android Wear
**Bundle ID:** com.google.Wear
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=986496028">986496028</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/android-wear/id986496028?mt=8&uo=4">https://itunes.apple.com/us/app/android-wear/id986496028?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPadFourthGen4G, iPodTouchSixthGen, iPhone4S, iPadThirdGen4G, iPadMini, iPhone6Plus, iPhone5c, iPhone5s, iPodTouchFifthGen, iPadThirdGen, iPhone6, iPad23G, iPhone5, iPad2Wifi, iPadFourthGen, iPadMini4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/a2/60/82/a2608223-b29a-33e4-1c9e-e3bada6f2449/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9596771/cb4f9918-5079-11e5-9885-0a590f29bc5b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9596771/cb4f9918-5079-11e5-9885-0a590f29bc5b.png)
https://cloud.githubusercontent.com/assets/2068130/9596771/cb4f9918-5079-11e5-9885-0a590f29bc5b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9596775/db2e4302-5079-11e5-94f1-de5ceed6496f.png
