### ISSUE TITLE
Sage Solitaire

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6277]
**App Name:** Sage Solitaire
**Bundle ID:** net.stfj.SiegeSolitaire
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1004646445">1004646445</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sage-solitaire/id1004646445?mt=8&uo=4">https://itunes.apple.com/us/app/sage-solitaire/id1004646445?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Zach Gage
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zach-gage/id294263418?uo=4>© Zach Gage</a>
**Supported Devices:** iPodTouchFifthGen, iPadFourthGen, iPhone6, iPadFourthGen4G, iPhone5s, iPad2Wifi, iPhone4S, iPadMini, iPadThirdGen4G, iPodTouchSixthGen, iPadMini4G, iPhone4, iPadThirdGen, iPad23G, iPhone5, iPodTouchFourthGen, iPhone6Plus, iPhone5c, iPhone-3GS
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/57/84/ea/5784ead6-6749-d018-6268-3079e2f9f085/mzl.hngzsdlj.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9661562/8c02ac08-525b-11e5-8e6b-4f0fe196733f.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9660765/57c83a9c-5225-11e5-87dc-3edb071443af.png)
https://cloud.githubusercontent.com/assets/7368317/9660765/57c83a9c-5225-11e5-87dc-3edb071443af.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9660771/6394bd50-5225-11e5-8141-dfb82fca6734.png

**Comment by Trubbel** [comment]
What about this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9661562/8c02ac08-525b-11e5-8e6b-4f0fe196733f.png)
https://cloud.githubusercontent.com/assets/10730122/9661562/8c02ac08-525b-11e5-8e6b-4f0fe196733f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9661559/8908d2ac-525b-11e5-9094-343b8c2a1841.png

**Comment by dreamnet** [comment]
@Teekzilla Your issue - you decide. :8ball:

**Comment by Teekzilla** [comment]
I like the second one! :+1: 
Nice, @Trubbel, needed just that icon to finish my SpringBoard!
