### ISSUE TITLE
Marriott International

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6278]
**App Name:** Marriott International
**Bundle ID:** com.marriott.iphoneprod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=455004730">455004730</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/marriott-international/id455004730?mt=8&uo=4">https://itunes.apple.com/us/app/marriott-international/id455004730?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** Marriott International
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/marriott-international/id455004733?uo=4>© Marriott International</a>
**Supported Devices:** iPadFourthGen, iPad2Wifi, iPhone4S, iPhone5c, iPhone5s, iPodTouchSixthGen, iPadMini4G, iPodTouchFifthGen, iPhone6Plus, iPad23G, iPadFourthGen4G, iPhone5, iPadMini, iPadThirdGen4G, iPhone6, iPadThirdGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/b9/b6/82/b9b6825b-4537-4340-b516-4e3ee6a547c2/mzl.mmwtucgi.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9661995/a67edd7a-525d-11e5-9205-69139b917569.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9661995/a67edd7a-525d-11e5-9205-69139b917569.png)
https://cloud.githubusercontent.com/assets/10730122/9661995/a67edd7a-525d-11e5-9205-69139b917569.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9661994/a3ce68fc-525d-11e5-98f4-020502088425.png
