### ISSUE TITLE
Resize Image

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6279]
**App Name:** Resize Image
**Bundle ID:** com.jasonpan.ResizeImage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409547517">409547517</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/resize-image/id409547517?mt=8&uo=4">https://itunes.apple.com/us/app/resize-image/id409547517?mt=8&uo=4</a>
**App Version:** 5.5
**Seller:** Jason Pan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jason-pan/id403012935?uo=4>© Jason Pan</a>
**Supported Devices:** iPhone4S, iPhone5, iPhone6, iPadFourthGen4G, iPadFourthGen, iPad2Wifi, iPad23G, iPadThirdGen, iPhone5c, iPhone5s, iPodTouchFifthGen, iPhone6Plus, iPadMini4G, iPadMini, iPadThirdGen4G, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/88/36/48/88364844-d864-3913-289d-6f3a76330ad1/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10128629/42a9cfb0-65b5-11e5-8b6d-1fb2d7c8311a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9977604/3b3c3acc-5f0e-11e5-817c-fc339bd8e202.png)
https://cloud.githubusercontent.com/assets/2068130/9977604/3b3c3acc-5f0e-11e5-817c-fc339bd8e202.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9977605/5135189e-5f0e-11e5-9b0f-65870a298015.png
:smile:

**Comment by ivanov007** [comment]
here's my try
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/10037120/3eb232e0-6177-11e5-8972-4de752592198.png)
https://cloud.githubusercontent.com/assets/3090247/10037120/3eb232e0-6177-11e5-8972-4de752592198.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10037121/3eb35350-6177-11e5-82bd-9953ed73243b.png

**Comment by dreamnet** [comment]
Another try:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10128629/42a9cfb0-65b5-11e5-8b6d-1fb2d7c8311a.png)
https://cloud.githubusercontent.com/assets/2068130/10128629/42a9cfb0-65b5-11e5-8b6d-1fb2d7c8311a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10128634/50f78968-65b5-11e5-88be-ac51c160acf1.png

**Comment by Trubbel** [comment]
@dreamnet The last one looks really good!

**Comment by dreamnet** [comment]
OK - I'm not very happy with it, but I take it.
