### ISSUE TITLE
Flyp: Multiple Phone Numbers

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#6280]
**App Name:** Flyp: Multiple Phone Numbers
**Bundle ID:** com.flyp.Flyp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=940678351">940678351</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/flyp-multiple-phone-numbers/id940678351?uo=4">https://apps.apple.com/us/app/flyp-multiple-phone-numbers/id940678351?uo=4</a>
**App Version:** 2.2.2
**Seller:** Flypsi, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/flypsi-inc/id940678350?uo=4">© Flypsi Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/0c/83/c5/0c83c59d-8416-bf68-14b1-9c93d2faf920/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400512-09d5db80-9b75-11e9-9adb-aaa26bb1215a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9676881/61262524-52d2-11e5-8636-76c07713e6cc.png)
https://cloud.githubusercontent.com/assets/2068130/9676881/61262524-52d2-11e5-8636-76c07713e6cc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9676883/713f8126-52d2-11e5-9487-e7d327d4e53e.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400512-09d5db80-9b75-11e9-9adb-aaa26bb1215a.png)
https://user-images.githubusercontent.com/20930745/60400512-09d5db80-9b75-11e9-9adb-aaa26bb1215a.png

Source_
https://user-images.githubusercontent.com/20930745/60400514-0b070880-9b75-11e9-9b03-8be70bb99fc2.png
