### ISSUE TITLE
Pictophile - meme generator lol pics gif captioner

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6283]
**App Name:** Pictophile - meme generator lol pics gif captioner
**Bundle ID:** com.voodoocoding.lolbucket
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=442786956">442786956</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pictophile-meme-generator/id442786956?mt=8&uo=4">https://itunes.apple.com/us/app/pictophile-meme-generator/id442786956?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Derek Buchanan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/voodoo-coding/id417621631?uo=4>© Voodoo Coding</a>
**Supported Devices:** iPhone4S, iPadThirdGen4G, iPodTouchFourthGen, iPhone6Plus, iPadMini, iPadFourthGen4G, iPhone-3GS, iPhone5c, iPhone4, iPhone5, iPhone6, iPad2Wifi, iPadFourthGen, iPodTouchSixthGen, iPad23G, iPhone5s, iPodTouchFifthGen, iPadThirdGen, iPadMini4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/60/86/2d/60862dc1-4b7e-f26e-611c-2c60d388c40b/mzl.mmdigsxb.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10120176/841b5146-64af-11e5-975c-15221f3a2466.png)

**Comment by dreamnet** [comment]
Hard one...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9976030/2eb3363c-5ed4-11e5-8a01-07ef28a7942e.png)
https://cloud.githubusercontent.com/assets/2068130/9976030/2eb3363c-5ed4-11e5-8a01-07ef28a7942e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9976033/45d8322c-5ed4-11e5-8944-d8f0e1886851.png
