### ISSUE TITLE
Beneath a Steel Sky: Remastered

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6284]
**App Name:** Beneath a Steel Sky: Remastered
**Bundle ID:** bass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=331733638">331733638</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beneath-steel-sky-remastered/id331733638?mt=8&uo=4">https://itunes.apple.com/us/app/beneath-steel-sky-remastered/id331733638?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Revolution Software Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/revolution/id331733641?uo=4>© Revolution</a>
**Supported Devices:** iPadMini4G, iPadFourthGen, iPhone4, iPadThirdGen4G, iPhone5c, iPadFourthGen4G, iPad23G, iPhone4S, iPhone6Plus, iPhone6, iPodTouchFourthGen, iPodTouchFifthGen, iPad2Wifi, iPhone5s, iPadMini, iPadThirdGen, iPhone5, iPodTouchSixthGen, iPhone-3GS
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/66/a4/63/66a463a8-e89b-7047-3be5-4a3c4d648812/mzl.inusjgxt.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9681076/fb325528-52c0-11e5-9b39-ea652e87ea3c.png)

**Comment by ivanov007** [comment]
icon needs a update,
here's my entry
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9681076/fb325528-52c0-11e5-9b39-ea652e87ea3c.png)
https://cloud.githubusercontent.com/assets/3090247/9681076/fb325528-52c0-11e5-9b39-ea652e87ea3c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9681075/fb271992-52c0-11e5-80c5-122cf9f5b7e6.png

**Comment by dreamnet** [comment]
@ivanov007 Great! :+1:
