### ISSUE TITLE
Monster Jobs – Search, Apply & Find New Vacancies

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6288]
**App Name:** Monster Jobs – Search, Apply & Find New Vacancies
**Bundle ID:** com.monster.mobility.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388924653">388924653</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/monster-jobs-search-apply-find-new-vacancies/id388924653?mt=8&uo=4">https://itunes.apple.com/gb/app/monster-jobs-search-apply-find-new-vacancies/id388924653?mt=8&uo=4</a>
**App Version:** 2.12.2
**Seller:** Monster Worldwide
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/monster-worldwide/id388922394?uo=4">© Monster Worldwide</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/77/9a/e1/779ae16a-d198-231f-7a06-cdb05c066947/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27767722-5091694e-5f00-11e7-960a-cf30a2f7a8f6.png)

**Comment by ivanov007** [comment]
icon changed
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9698694/6edd49da-5387-11e5-94df-9c17fae6049b.png)
https://cloud.githubusercontent.com/assets/3090247/9698694/6edd49da-5387-11e5-94df-9c17fae6049b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9698701/87ba5326-5387-11e5-8d37-770749521e5a.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27767722-5091694e-5f00-11e7-960a-cf30a2f7a8f6.png)
https://user-images.githubusercontent.com/2068130/27767722-5091694e-5f00-11e7-960a-cf30a2f7a8f6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27767726-602c8b18-5f00-11e7-98f1-50667d115257.png
