### ISSUE TITLE
NOOK - Read Books, Magazines, Newspapers & Comics

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#6291]
**App Name:** NOOK - Read Books, Magazines, Newspapers & Comics
**Bundle ID:** com.barnesandnoble.B-N-eReader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=373582546">373582546</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nook-read-books-magazines/id373582546?mt=8&uo=4">https://itunes.apple.com/us/app/nook-read-books-magazines/id373582546?mt=8&uo=4</a>
**App Version:** 4.1.0
**Seller:** Barnes&Noble
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/barnes-noble/id320214165?uo=4>© Barnes & Noble</a>
**Supported Devices:** iPad2Wifi, iPhone6Plus, iPadThirdGen4G, iPadMini, iPodTouchFifthGen, iPhone5, iPhone4S, iPadFourthGen4G, iPadFourthGen, iPhone5s, iPadThirdGen, iPhone6, iPodTouchSixthGen, iPad23G, iPhone5c, iPadMini4G, iPhone4
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/3c/4b/24/3c4b2485-2b4e-b343-9eb4-515eeb9b54ee/mzl.yrnzxvte.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9731194/35867a2e-55e1-11e5-8f09-a3a38d0aff0b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9731142/c28226a4-55e0-11e5-811b-cc87370411a4.png)
https://cloud.githubusercontent.com/assets/3090247/9731142/c28226a4-55e0-11e5-811b-cc87370411a4.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9731141/c2810ecc-55e0-11e5-9251-e41e020a68f2.png)
https://cloud.githubusercontent.com/assets/3090247/9731141/c2810ecc-55e0-11e5-9251-e41e020a68f2.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/9731159/e0a414da-55e0-11e5-9ba7-2678a80cef35.png
https://cloud.githubusercontent.com/assets/3090247/9731158/e09f482e-55e0-11e5-94a2-a639e501cddb.png
