### ISSUE TITLE
Worms™ 4

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6292]
**App Name:** Worms™ 4
**Bundle ID:** com.team17.worms4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=981535263">981535263</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/worms-4/id981535263?mt=8&uo=4">https://itunes.apple.com/us/app/worms-4/id981535263?mt=8&uo=4</a>
**App Version:** 1.02
**Seller:** Team17 Software, Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/team17-software-ltd/id321369234?uo=4>© Team17 Software Ltd</a>
**Supported Devices:** iPadFourthGen4G, iPhone5s, iPhone4S, iPadMini, iPhone5c, iPhone6Plus, iPadFourthGen, iPodTouchSixthGen, iPad2Wifi, iPadMini4G, iPhone6, iPadThirdGen, iPadThirdGen4G, iPad23G, iPodTouchFifthGen, iPhone5
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/58/81/17/588117aa-7de2-bab9-5c09-91e5126e780c/mzl.whifzgez.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9730483/6e023c58-55dc-11e5-8677-4352cccae7bc.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9729985/1d482c30-55d9-11e5-9ceb-17cf209308b1.png)
https://cloud.githubusercontent.com/assets/3090247/9729985/1d482c30-55d9-11e5-9ceb-17cf209308b1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9729984/1d47eeaa-55d9-11e5-8efe-e0e261a890e0.png

**Comment by Trubbel** [comment]
@ivanov007 :+1:
