### ISSUE TITLE
Adblock Browser

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6295]
**App Name:** Adblock Browser
**Bundle ID:** org.adblockplus.AdblockBrowser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1015653330">1015653330</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adblock-browser/id1015653330?mt=8&uo=4">https://itunes.apple.com/us/app/adblock-browser/id1015653330?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Eyeo GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eyeo/id1015653329?uo=4>© Eyeo</a>
**Supported Devices:** iPadMini, iPadFourthGen, iPodTouchFifthGen, iPhone6Plus, iPhone6, iPadFourthGen4G, iPhone4S, iPadThirdGen, iPhone5s, iPadThirdGen4G, iPhone5, iPhone5c, iPad23G, iPodTouchSixthGen, iPadMini4G, iPad2Wifi
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/07/7c/d5/077cd5f3-2eab-6511-7d8d-67b247c42d9f/pr_source.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9783733/332c7c88-576c-11e5-8bee-bb63a32d3129.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9783732/3302c474-576c-11e5-932f-6400d2c4a1da.png)
https://cloud.githubusercontent.com/assets/3090247/9783732/3302c474-576c-11e5-932f-6400d2c4a1da.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9783733/332c7c88-576c-11e5-8bee-bb63a32d3129.png)
https://cloud.githubusercontent.com/assets/3090247/9783733/332c7c88-576c-11e5-8bee-bb63a32d3129.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/9783749/4f107616-576c-11e5-9cdc-0a52c2094a4c.png
https://cloud.githubusercontent.com/assets/3090247/9783750/4f161f6c-576c-11e5-97cb-cdea5933d39c.png

**Comment by dreamnet** [comment]
Hm... I take the second one.
