### ISSUE TITLE
Untis Mobile

### ISSUE THREAD

**Issue by Konsti9012** [glasklart/hd#6296]
**App Name:** Untis Mobile
**Bundle ID:** at.grupet.mobile.um
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926186904">926186904</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/untis-mobile/id926186904?mt=8&uo=4">https://itunes.apple.com/us/app/untis-mobile/id926186904?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Gruber and Petters GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gruber-petters-gmbh/id926186903?uo=4>© Gruber & Petters GmbH</a>
**Supported Devices:** iPad2Wifi, iPadThirdGen, iPhone-3GS, iPodTouchFourthGen, iPhone5c, iPhone5s, iPad23G, iPhone6Plus, iPhone4, iPadMini4G, iPodTouchFifthGen, iPadFourthGen, iPadThirdGen4G, iPhone5, iPadMini, iPadFourthGen4G, iPhone6, iPhone4S, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/cc/23/e5/cc23e514-8fa6-c240-2fd2-6a271f85de7b/mzl.hotcwrvc.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9972441/b7993cd2-5e64-11e5-848a-7863a65e6ca1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9972441/b7993cd2-5e64-11e5-848a-7863a65e6ca1.png)
https://cloud.githubusercontent.com/assets/2068130/9972441/b7993cd2-5e64-11e5-848a-7863a65e6ca1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9972449/c68c0224-5e64-11e5-9701-2676489fb672.png
