### ISSUE TITLE
PONS Online Dictionary

### ISSUE THREAD

**Issue by Konsti9012** [glasklart/hd#6297]
**App Name:** PONS Online Dictionary - look up words for free
**Bundle ID:** eu.pons.dictionary
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=577741918">577741918</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pons-online-dictionary-look/id577741918?mt=8&uo=4">https://itunes.apple.com/us/app/pons-online-dictionary-look/id577741918?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** PONS GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pons-gmbh/id577049805?uo=4>© PONS GmbH</a>
**Supported Devices:** iPadThirdGen, iPadMini4G, iPad23G, iPadFourthGen, iPad2Wifi, iPhone5c, iPadFourthGen4G, iPhone5s, iPodTouchFifthGen, iPhone6, iPhone4, iPhone4S, iPhone5, iPadThirdGen4G, iPhone6Plus, iPodTouchSixthGen, iPadMini
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/3d/e7/e3/3de7e37c-3dc7-036b-15da-ff3da9886afb/mzl.trqpbtzz.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/9903195/a72c372e-5c74-11e5-9d4a-70085db743d3.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/9903195/a72c372e-5c74-11e5-9d4a-70085db743d3.png)
https://cloud.githubusercontent.com/assets/8452321/9903195/a72c372e-5c74-11e5-9d4a-70085db743d3.png

Source: 
https://cloud.githubusercontent.com/assets/8452321/9903214/d3002298-5c74-11e5-8acf-22a6bb0fb4ea.png

**Comment by dreamnet** [comment]
@DerDoktor Hmmm... yes, looks good. :+1:
