### ISSUE TITLE
Layer - simple is hard

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6298]
**App Name:** Layer - simple is hard
**Bundle ID:** com.gamenauts.layer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=919383008">919383008</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/layer-simple-is-hard/id919383008?mt=8&uo=4">https://itunes.apple.com/us/app/layer-simple-is-hard/id919383008?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Gamenauts
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gamenauts/id365235182?uo=4>© Gamenauts</a>
**Supported Devices:** iPhone5s, iPad23G, iPadThirdGen, iPhone4, iPadMini, iPadMini4G, iPhone4S, iPhone5c, iPadFourthGen4G, iPadThirdGen4G, iPadFourthGen, iPhone6Plus, iPodTouchFifthGen, iPhone6, iPodTouchSixthGen, iPhone-3GS, iPodTouchFourthGen, iPad2Wifi, iPhone5
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/cb/c7/30/cbc7300e-dcbc-ca10-991c-5712309a092f/mzl.dqhnahdk.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9783449/f1f3e816-5769-11e5-8c10-5666d1d8ab40.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9783449/f1f3e816-5769-11e5-8c10-5666d1d8ab40.png)
https://cloud.githubusercontent.com/assets/3090247/9783449/f1f3e816-5769-11e5-8c10-5666d1d8ab40.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9783450/f1f78782-5769-11e5-8630-92261b1d7b9b.png
