### ISSUE TITLE
BBVA Wallet México

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6300]
**App Name:** BBVA Wallet México
**Bundle ID:** com.bbva.bbvawallet.mx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=970582311">970582311</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bbva-wallet-m%C3%A9xico/id970582311?uo=4">https://apps.apple.com/us/app/bbva-wallet-m%C3%A9xico/id970582311?uo=4</a>
**App Version:** 11.10.190528
**Seller:** BBVA Bancomer, S.A.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bbva-bancomer-s-a/id372650200?uo=4">© BBVA Bancomer, S.A.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/07/3a/c4/073ac4af-e104-51aa-fdfa-0442936e2d77/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60359993-e37c3880-99da-11e9-93c4-0a0b8e4beeb3.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9810456/9444a7a0-5836-11e5-9e3a-51722681d445.png)
https://cloud.githubusercontent.com/assets/3090247/9810456/9444a7a0-5836-11e5-9e3a-51722681d445.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9810466/a8b0ece4-5836-11e5-91c8-ef25481bc1a7.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60357789-dfe5b300-99d4-11e9-83d7-8687cbab267c.png)
https://user-images.githubusercontent.com/2068130/60357789-dfe5b300-99d4-11e9-83d7-8687cbab267c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60357810-ef64fc00-99d4-11e9-87c0-f45342a04228.png
