### ISSUE TITLE
Infinity Blade III

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6301]
**App Name:** Infinity Blade III
**Bundle ID:** com.chairentertainment.IB3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=610003290">610003290</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/infinity-blade-iii/id610003290?mt=8&uo=4">https://itunes.apple.com/us/app/infinity-blade-iii/id610003290?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Chair Entertainment Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chair-entertainment-group/id387428403?uo=4>© Chair Entertainment Group, LLC</a>
**Supported Devices:** iPadWifi, iPad3G, iPodTouchThirdGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/95/a3/95/95a395a5-ea52-946b-2f68-09bb36f215fd/mzl.lpimsmyc.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9841142/bf9ff382-5a61-11e5-9b2c-1a120240cc4d.png)

**Comment by Trubbel** [comment]
It's Apples free App of the Week, y'all better get it if you don't already own it, haha. :wink:

**Comment by ivanov007** [comment]
almost 2 gigs :open_mouth: I have to delete a bunch of stuff

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9839486/a5c30b4a-5a41-11e5-9c62-59e14f0383f6.png)
https://cloud.githubusercontent.com/assets/3090247/9839486/a5c30b4a-5a41-11e5-9c62-59e14f0383f6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9839487/a5c610a6-5a41-11e5-8e18-8c4d633024c3.png
