### ISSUE TITLE
PaceDJ: Music To Drive Your Running Pace

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6302]
**App Name:** PaceDJ: Music To Drive Your Running Pace
**Bundle ID:** com.pacingtechnologies.pacedj
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446225183">446225183</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pacedj-music-to-drive-your/id446225183?mt=8&uo=4">https://itunes.apple.com/us/app/pacedj-music-to-drive-your/id446225183?mt=8&uo=4</a>
**App Version:** 2.1.7
**Seller:** Pacing Technologies, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pacing-technologies-llc/id446225186?uo=4>© Pacing Technologies, LLC</a>
**Supported Devices:** iPadWifi, iPad3G, iPodTouchThirdGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/df/d3/2e/dfd32e34-6046-3c8d-0e12-49e8a6170bdd/mzl.jxpcrpzc.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9813525/82738532-5886-11e5-9e14-24caba1a93d4.png)

**Comment by Trubbel** [comment]
This is the artwork iTunes/App Store shows,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9813505/5bcda70a-5886-11e5-911c-3e6dd9f52161.png)
https://cloud.githubusercontent.com/assets/10730122/9813505/5bcda70a-5886-11e5-911c-3e6dd9f52161.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9813503/590c4080-5886-11e5-8657-81ff09b21e7b.png

**Comment by Trubbel** [comment]
This is how the icon looks like on the SpringBoard,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9813525/82738532-5886-11e5-9e14-24caba1a93d4.png)
https://cloud.githubusercontent.com/assets/10730122/9813525/82738532-5886-11e5-9e14-24caba1a93d4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9813522/7e789896-5886-11e5-98dc-da9811544cff.png

**Comment by Trubbel** [comment]
I didn't know which one to choose, so I did both. Choice is all yours maintainers. :wink:

**Comment by dreamnet** [comment]
@Trubbel I'm taking the one without the text. :+1:
