### ISSUE TITLE
Atomic+

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6305]
**App Name:** Atomic+
**Bundle ID:** com.Amidos.AtomicPlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=773373906">773373906</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/atomic+/id773373906?mt=8&uo=4">https://itunes.apple.com/us/app/atomic+/id773373906?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Ahmed Khalifa
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ahmed-khalifa/id734079228?uo=4>© Ahmed Khalifa</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/e0/23/8a/e0238acd-2be0-ea48-f24a-08039ade1133/mzl.ztjzjqik.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9813781/e2ecd13c-5888-11e5-95f9-cc32f95107f9.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9813781/e2ecd13c-5888-11e5-95f9-cc32f95107f9.png)
https://cloud.githubusercontent.com/assets/10730122/9813781/e2ecd13c-5888-11e5-95f9-cc32f95107f9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9813779/dfdd2776-5888-11e5-9af5-528189c29f03.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9813793/f32abf64-5888-11e5-82c5-c68001389dc4.png)
https://cloud.githubusercontent.com/assets/10730122/9813793/f32abf64-5888-11e5-82c5-c68001389dc4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9813790/f0dc6172-5888-11e5-82f6-52e3e34e572b.png

**Comment by ivanov007** [comment]
I think the first one should do it :+1:
