### ISSUE TITLE
Explore 9/11

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6306]
**App Name:** Explore 9/11
**Bundle ID:** org.national911memorial.tour
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=387986451">387986451</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/explore-9-11/id387986451?mt=8&uo=4">https://itunes.apple.com/us/app/explore-9-11/id387986451?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** National September 11 Memorial & Museum
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/national-september-11-memorial/id387986455?uo=4>© National September 11 Memorial & Museum</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/54/5a/c5/545ac582-62ee-97ad-c269-4ff4b199ec4a/mzl.apvwymil.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9821604/632d2a0e-5889-11e5-8afd-4caa8b183505.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9821604/632d2a0e-5889-11e5-8afd-4caa8b183505.png)
https://cloud.githubusercontent.com/assets/7368317/9821604/632d2a0e-5889-11e5-8afd-4caa8b183505.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9821605/63ecc710-5889-11e5-8a3e-8e609490d66e.png

**Comment by ivanov007** [comment]
what about this one?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9830344/44aaa2fc-58f0-11e5-828e-851067790bb8.png)
https://cloud.githubusercontent.com/assets/3090247/9830344/44aaa2fc-58f0-11e5-828e-851067790bb8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9830345/44d55fd8-58f0-11e5-8a7a-fcb64ead2a1a.png

**Comment by dreamnet** [comment]
I'm tending to get as close as possibe to the original - I take the one from @Teekzilla.
