### ISSUE TITLE
Trip.com Things to do, Restaurant & Hotel Reviews

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6307]
**App Name:** Trip.com Things to do, Restaurant & Hotel Reviews
**Bundle ID:** com.gogobot.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=459590827">459590827</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trip.com-things-to-do-restaurant/id459590827?mt=8&uo=4">https://itunes.apple.com/us/app/trip.com-things-to-do-restaurant/id459590827?mt=8&uo=4</a>
**App Version:** 4.6
**Seller:** Gogobot, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gogobot/id459590830?uo=4">© Gogobot</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/20/ce/02/20ce0212-0401-3f95-0bf0-67a576c1c0f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21286399/e664200e-c452-11e6-961d-334045db7029.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9821735/31932736-588a-11e5-8d65-08790b0c2d6d.png)
https://cloud.githubusercontent.com/assets/7368317/9821735/31932736-588a-11e5-8d65-08790b0c2d6d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9821737/3339b0c8-588a-11e5-9bad-3c6790cd1ea7.png

**Comment by dreamnet** [comment]
@Teekzilla Perfect! :+1:

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Trip.com Things to do, Restaurant & Hotel Reviews
**Bundle ID:** com.gogobot.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=459590827">459590827</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trip.com-things-to-do-restaurant/id459590827?mt=8&uo=4">https://itunes.apple.com/us/app/trip.com-things-to-do-restaurant/id459590827?mt=8&uo=4</a>
**App Version:** 4.6
**Seller:** Gogobot, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gogobot/id459590830?uo=4">© Gogobot</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/20/ce/02/20ce0212-0401-3f95-0bf0-67a576c1c0f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21286399/e664200e-c452-11e6-961d-334045db7029.png)
https://cloud.githubusercontent.com/assets/2068130/21286399/e664200e-c452-11e6-961d-334045db7029.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21286400/f566d8e4-c452-11e6-94b9-97f7a5a924c3.png
