### ISSUE TITLE
Wave Trip

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#631]
**App Name:** Wave Trip
**Bundle ID:** com.luckyframe.wavetrip
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=581914455">581914455</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wave-trip/id581914455?mt=8&uo=4">https://itunes.apple.com/us/app/wave-trip/id581914455?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Lucky Frame Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lucky-frame/id324895778?uo=4">© Lucky Frame</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/f4/58/4f/f4584f29-e485-268e-5780-cbe748575775/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20239491/636f07a2-a901-11e6-961b-fe7380a96eda.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20239491/636f07a2-a901-11e6-961b-fe7380a96eda.png)
https://cloud.githubusercontent.com/assets/20930745/20239491/636f07a2-a901-11e6-961b-fe7380a96eda.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20239496/7afcdee4-a901-11e6-96d3-0244e94514d1.png
