### ISSUE TITLE
DraftKings Fantasy Sports

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6311]
**App Name:** DraftKings Fantasy Sports
**Bundle ID:** com.draftkings.dknativermg
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=710535379">710535379</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/draftkings-fantasy-sports/id710535379?uo=4">https://apps.apple.com/us/app/draftkings-fantasy-sports/id710535379?uo=4</a>
**App Version:** 3.57.0
**Seller:** DRAFTKINGS LLC.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/draftkings/id544448370?uo=4">© DraftKings</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/88/d5/9e/88d59e6e-9855-4427-7ce1-23e23ab2033d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382996-972d0900-9a6b-11e9-9774-4174398ed18e.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9837778/b64ac620-5a4a-11e5-8195-9f4c34e6022a.png)
https://cloud.githubusercontent.com/assets/10730122/9837778/b64ac620-5a4a-11e5-8195-9f4c34e6022a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9837777/b3df36aa-5a4a-11e5-8def-bf9a9da0131a.png

**Comment by ivanov007** [comment]
@Trubbel  looks good :+1:

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382996-972d0900-9a6b-11e9-9774-4174398ed18e.png)
https://user-images.githubusercontent.com/20930745/60382996-972d0900-9a6b-11e9-9774-4174398ed18e.png

Source:
https://user-images.githubusercontent.com/20930745/60383000-a6ac5200-9a6b-11e9-900c-df7594accd7f.png
