### ISSUE TITLE
Password Manager SafeInCloud - Login with Touch ID, Password Generator, Cloud Synchronization & Free Desktop App

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#6312]
**App Name:** Password Manager SafeInCloud - Login with Touch ID, Password Generator, Cloud Synchronization & Free Desktop App
**Bundle ID:** com.safeincloud.Safe-In-Cloud.Free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=895062927">895062927</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/password-manager-safeincloud/id895062927?mt=8&uo=4">https://itunes.apple.com/us/app/password-manager-safeincloud/id895062927?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Andrey Shcherbakov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/andrey-shcherbakov/id448876346?uo=4>© Andrey Shcherbakov</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/b5/d6/95/b5d69512-05b7-0815-99a5-e8fbcf7e5dd9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11308284/e9ba649e-8f82-11e5-8007-f9e735cdaed3.png)

**Comment by dreamnet** [comment]
Refers to #5893.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9839256/f4ff0e2a-5a73-11e5-9e14-f0b1e8eb02aa.png)
https://cloud.githubusercontent.com/assets/2068130/9839256/f4ff0e2a-5a73-11e5-9e14-f0b1e8eb02aa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9839260/0996e07e-5a74-11e5-8c58-4acaad0f7877.png

**Comment by ivanov007** [comment]
icon changed
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11308284/e9ba649e-8f82-11e5-8007-f9e735cdaed3.png)
https://cloud.githubusercontent.com/assets/3090247/11308284/e9ba649e-8f82-11e5-8007-f9e735cdaed3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11308285/ea1cfb54-8f82-11e5-9b89-9e2db1712860.png
