### ISSUE TITLE
PDF Box – simple, clean, and blazingly fast PDF reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6316]
**App Name:** PDF Box – simple, clean, and blazingly fast PDF reader
**Bundle ID:** com.aplekhanov.pdfbox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=647697055">647697055</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pdf-box-simple-clean-blazingly/id647697055?mt=8&uo=4">https://itunes.apple.com/us/app/pdf-box-simple-clean-blazingly/id647697055?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Alexey Plekhanov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alexey-plekhanov/id543015684?uo=4>© Alexey Plekhanov</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/79/93/2d/79932d7c-7388-339b-5e02-4a3f2c4d67d2/mzl.givfajck.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9868582/09d378d8-5b7b-11e5-9a31-0922040a2871.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9868582/09d378d8-5b7b-11e5-9a31-0922040a2871.png)
https://cloud.githubusercontent.com/assets/2068130/9868582/09d378d8-5b7b-11e5-9a31-0922040a2871.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9868585/1b4e7be4-5b7b-11e5-97eb-08435a804747.png
