### ISSUE TITLE
Might & Magic Clash of Heroes

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#632]
**App Name:** Might & Magic Clash of Heroes
**Bundle ID:** UBI.087.WW
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=541590823">541590823</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/might-magic-clash-of-heroes/id541590823?mt=8&uo=4">https://itunes.apple.com/us/app/might-magic-clash-of-heroes/id541590823?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Ubisoft
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ubisoft/id317644720?uo=4">© Ubisoft</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/58/c0/97/58c097f0-22bd-c564-30c6-2c74509524d2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32398222-2bc764a6-c0ee-11e7-97c9-92548f2c89f4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32398222-2bc764a6-c0ee-11e7-97c9-92548f2c89f4.png)
https://user-images.githubusercontent.com/2068130/32398222-2bc764a6-c0ee-11e7-97c9-92548f2c89f4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32398231-3cfed362-c0ee-11e7-851c-85009d60ab96.png
