### ISSUE TITLE
Trick Shot

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#6320]
**App Name:** Trick Shot
**Bundle ID:** com.jonathantopf.trickshot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1016915419">1016915419</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trick-shot/id1016915419?mt=8&uo=4">https://itunes.apple.com/us/app/trick-shot/id1016915419?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** Jonathan Topf
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jonathan-topf/id1016915418?uo=4>© Jonathan Topf</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/6b/0f/53/6b0f5345-1a61-35c1-bc13-59efa2987845/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9944882/548f1e02-5d8a-11e5-9a20-5636f30b55b6.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/9903311/c04abe8c-5c75-11e5-90b7-dfda4d2af981.png)
https://cloud.githubusercontent.com/assets/8452321/9903311/c04abe8c-5c75-11e5-90b7-dfda4d2af981.png

Source:
https://cloud.githubusercontent.com/assets/8452321/9903319/d180fc5c-5c75-11e5-804f-d9a3e66606bb.png

**Comment by dreamnet** [comment]
Just some small changes:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9944882/548f1e02-5d8a-11e5-9a20-5636f30b55b6.png)
https://cloud.githubusercontent.com/assets/2068130/9944882/548f1e02-5d8a-11e5-9a20-5636f30b55b6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9944891/65234d92-5d8a-11e5-86b0-75cb90a0c894.png
