### ISSUE TITLE
Happy Wheels

### ISSUE THREAD

**Issue by DerDoktor** [glasklart/hd#6321]
**App Name:** Happy Wheels
**Bundle ID:** com.fancyforce.happywheels
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=648668184">648668184</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/happy-wheels/id648668184?mt=8&uo=4">https://itunes.apple.com/us/app/happy-wheels/id648668184?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Jim Bonacci
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jim-bonacci/id1032027265?uo=4>© Jim Bonacci</a>
**Supported Devices:** iPadWifi, iPad3G, iPodTouchThirdGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/e1/f3/81/e1f381d7-6cbf-4508-2f76-4e030ea86cc0/mzl.qwddahqf.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9944146/b93603de-5d85-11e5-875c-625a65031f13.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/9903344/054edf4a-5c76-11e5-92e8-2e9656a271a2.png)
https://cloud.githubusercontent.com/assets/8452321/9903344/054edf4a-5c76-11e5-92e8-2e9656a271a2.png

Source:
https://cloud.githubusercontent.com/assets/8452321/9903350/158ff376-5c76-11e5-9b4d-ad56eb1667e5.png

**Comment by dreamnet** [comment]
@DerDoktor Sehr gut! :+1:

**Comment by dreamnet** [comment]
On second thought... Maybe it's better this way:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9944146/b93603de-5d85-11e5-875c-625a65031f13.png)
https://cloud.githubusercontent.com/assets/2068130/9944146/b93603de-5d85-11e5-875c-625a65031f13.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9944172/d74de616-5d85-11e5-824e-e9fe33a51a11.png
