### ISSUE TITLE
ShopStyle - Shop Designer Clothes, Shoes, Accessories & Deals on Fashion Shopping

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6322]
**App Name:** ShopStyle - Shop Designer Clothes, Shoes, Accessories & Deals on Fashion Shopping
**Bundle ID:** com.sugarinc.ShopStyle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=314673827">314673827</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shopstyle-shop-designer-clothes/id314673827?mt=8&uo=4">https://itunes.apple.com/us/app/shopstyle-shop-designer-clothes/id314673827?mt=8&uo=4</a>
**App Version:** 4.6
**Seller:** POPSUGAR Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/popsugar-inc./id314673840?mt=8&uo=4>© POPSUGAR Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/16/5d/e6/165de6f5-c90e-7740-8b47-bf80ab0af3ba/mzl.kheonotq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9945035/42bd8046-5d8b-11e5-9cc5-bffa787e38dc.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9913275/089fb878-5c7a-11e5-89cf-a5df0d930f83.png)
https://cloud.githubusercontent.com/assets/7368317/9913275/089fb878-5c7a-11e5-89cf-a5df0d930f83.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9913274/089f8bc8-5c7a-11e5-88eb-ffa98917fade.png

**Comment by dreamnet** [comment]
Original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9945035/42bd8046-5d8b-11e5-9cc5-bffa787e38dc.png)
https://cloud.githubusercontent.com/assets/2068130/9945035/42bd8046-5d8b-11e5-9cc5-bffa787e38dc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9945049/522be784-5d8b-11e5-8082-011c7e3fcef1.png
