### ISSUE TITLE
Curatum - A decisive guide to curated luxury

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6323]
**App Name:** Curatum - A decisive guide to curated luxury
**Bundle ID:** com.curatum.Curatum
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=982611603">982611603</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/curatum-decisive-guide-to/id982611603?mt=8&uo=4">https://itunes.apple.com/us/app/curatum-decisive-guide-to/id982611603?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Curatum Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/curatum/id982607144?uo=4>© Curatum</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/79/5c/1e/795c1ea2-d9f5-bfea-a853-69343cba53e3/mzl.pshqgkcq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9945131/d5970e0a-5d8b-11e5-9203-9d6fec554eb4.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9913496/19a88c20-5c7b-11e5-9bbb-332d2666e5e4.png)
https://cloud.githubusercontent.com/assets/7368317/9913496/19a88c20-5c7b-11e5-9bbb-332d2666e5e4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9913498/1acfa2c8-5c7b-11e5-93b7-f11f9185f272.png

**Comment by dreamnet** [comment]
Original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9945131/d5970e0a-5d8b-11e5-9203-9d6fec554eb4.png)
https://cloud.githubusercontent.com/assets/2068130/9945131/d5970e0a-5d8b-11e5-9203-9d6fec554eb4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9945141/e4810010-5d8b-11e5-9cdf-7abf9e2d7bc6.png
