### ISSUE TITLE
Chase Pay® | Earn, Save, Order

### ISSUE THREAD

**Issue by Prateek-Prakash** [glasklart/hd#6325]
**App Name:** Chase Pay® | Earn, Save, Order
**Bundle ID:** com.chase.pay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=922631033">922631033</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/chase-pay-earn-save-order/id922631033?uo=4">https://apps.apple.com/us/app/chase-pay-earn-save-order/id922631033?uo=4</a>
**App Version:** 2.402
**Seller:** JPMorgan Chase Bank, NA
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/jpmorgan-chase-co/id298867250?uo=4">© JPMorgan Chase & Co.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/ad/1a/a7/ad1aa7d0-f785-865e-bcae-e74d3d2bd5d1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60373211-b68e4c80-99ff-11e9-9eff-5e4862c26460.png)

**Comment by Teekzilla** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9914230/d3c00c8e-5c7e-11e5-9f76-deaae34684a9.png)
https://cloud.githubusercontent.com/assets/7368317/9914230/d3c00c8e-5c7e-11e5-9f76-deaae34684a9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9914232/d4b7db3a-5c7e-11e5-86b0-0419f8c16b29.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60373166-8050cd00-99ff-11e9-980c-389f0dd95b52.png)
https://user-images.githubusercontent.com/20930745/60373166-8050cd00-99ff-11e9-980c-389f0dd95b52.png

Source:
https://user-images.githubusercontent.com/20930745/60373170-85158100-99ff-11e9-8870-5af66d197aa2.png
