### ISSUE TITLE
Paper by FiftyThree

### ISSUE THREAD

**Issue by Prateek-Prakash** [glasklart/hd#6331]
**App Name:** Paper by FiftyThree
**Bundle ID:** com.fiftythree.paper
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506003812">506003812</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paper-by-fiftythree/id506003812?mt=8&uo=4">https://itunes.apple.com/us/app/paper-by-fiftythree/id506003812?mt=8&uo=4</a>
**App Version:** 4.0.5
**Seller:** FiftyThree, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fiftythree-inc/id485103881?uo=4">© FiftyThree, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/7c/a0/fa/7ca0fa90-2f38-1124-1b40-095af2e89e98/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34393524-6b0c2cde-eb53-11e7-8a20-b0cfa884521d.png)

**Comment by Teekzilla** [comment]
Option 1:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9923344/dc4924f6-5cc1-11e5-8289-75d672b20870.png)
https://cloud.githubusercontent.com/assets/7368317/9923344/dc4924f6-5cc1-11e5-8289-75d672b20870.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9923345/dda8fb50-5cc1-11e5-851a-8a2e6680e3d6.png

Option 2:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9923347/df5341cc-5cc1-11e5-9286-d9d40a589ee9.png)
https://cloud.githubusercontent.com/assets/7368317/9923347/df5341cc-5cc1-11e5-9286-d9d40a589ee9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9923348/e08edcfe-5cc1-11e5-9102-65c2aaf17d23.png

**Comment by dreamnet** [comment]
@Teekzilla  Taking option 1. :+1:

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Paper by FiftyThree
**Bundle ID:** com.fiftythree.paper
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506003812">506003812</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paper-by-fiftythree/id506003812?mt=8&uo=4">https://itunes.apple.com/us/app/paper-by-fiftythree/id506003812?mt=8&uo=4</a>
**App Version:** 4.0.5
**Seller:** FiftyThree, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fiftythree-inc/id485103881?uo=4">© FiftyThree, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/7c/a0/fa/7ca0fa90-2f38-1124-1b40-095af2e89e98/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34393524-6b0c2cde-eb53-11e7-8a20-b0cfa884521d.png)
https://user-images.githubusercontent.com/2068130/34393524-6b0c2cde-eb53-11e7-8a20-b0cfa884521d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34393536-79cab8d0-eb53-11e7-9d5a-851243e05e4a.png
