### ISSUE TITLE
iMods

### ISSUE THREAD

**Issue by coolstar** [glasklart/hd#6333]
**App Name:** iMods
**Bundle ID:** com.Wunderkind.iMods
**iTunes ID:** none (System app)
**App Version:** internal beta
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/1431548/9925714/68461fb2-5cc3-11e5-804e-40f0fa5cf6ff.PNG" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9926107/d7c1b744-5d12-11e5-8c0d-bdfbd16f58a9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9926107/d7c1b744-5d12-11e5-8c0d-bdfbd16f58a9.png)
https://cloud.githubusercontent.com/assets/2068130/9926107/d7c1b744-5d12-11e5-8c0d-bdfbd16f58a9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9926119/ed639ce8-5d12-11e5-90df-2043186f743f.png

**Comment by ivanov007** [comment]
@coolstar do you know how to install this? looks nice, btw I see you (anemone) are getting a lot of attention :+1:
