### ISSUE TITLE
Files - File Manager & Browser

### ISSUE THREAD

**Issue by coolstar** [glasklart/hd#6334]
**App Name:** Files - File Manager & Browser
**Bundle ID:** com.hianzinjong.Downloads-Lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=349275540">349275540</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/files-file-manager-browser/id349275540?mt=8&uo=4">https://itunes.apple.com/us/app/files-file-manager-browser/id349275540?mt=8&uo=4</a>
**App Version:** 6.1.4
**Seller:** Hian Zin Jong
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hian-zin-jong/id298442756?uo=4">© Hian Zin Jong</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/d3/6b/22/d36b22f9-6b13-1b95-2687-cc04209c9bbb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36615650-516c149a-18e1-11e8-8181-51d47dcdc355.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9944509/04f0dda6-5d88-11e5-9164-213bc6b04acf.png)
https://cloud.githubusercontent.com/assets/2068130/9944509/04f0dda6-5d88-11e5-9164-213bc6b04acf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9944523/1533c890-5d88-11e5-893d-5ddd6ed16c97.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36615650-516c149a-18e1-11e8-8181-51d47dcdc355.png)
https://user-images.githubusercontent.com/20930745/36615650-516c149a-18e1-11e8-8181-51d47dcdc355.png

Source:
https://user-images.githubusercontent.com/20930745/36615679-64f33e44-18e1-11e8-81ea-804d88cfbbc1.png)
