### ISSUE TITLE
ManyCam Mobile Source

### ISSUE THREAD

**Issue by coolstar** [glasklart/hd#6335]
**App Name:** ManyCam Mobile Source
**Bundle ID:** com.tomsk.ManyCamMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1009433402">1009433402</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/manycam-mobile-source/id1009433402?mt=8&uo=4">https://itunes.apple.com/us/app/manycam-mobile-source/id1009433402?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Visicom Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/visicom-media/id845197169?uo=4>© Visicom Media</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/12/ca/80/12ca803f-4003-f25e-7f52-556b1b4f9cc6/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9978180/1b1cd584-5f23-11e5-9811-f8614bb34407.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9975340/748de474-5eb9-11e5-9983-c72f95ccd41c.png)
https://cloud.githubusercontent.com/assets/2068130/9975340/748de474-5eb9-11e5-9983-c72f95ccd41c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9975342/82561310-5eb9-11e5-93dc-3a6d001c8cb8.png
