### ISSUE TITLE
Baby Log - Notebook to Track your Newborn's Daily Activities

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6338]
**App Name:** Baby Log - Notebook to Track your Newborn's Daily Activities
**Bundle ID:** com.purpleblue.BabyLog
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=882442328">882442328</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/baby-log-notebook-to-track/id882442328?mt=8&uo=4">https://itunes.apple.com/us/app/baby-log-notebook-to-track/id882442328?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Purpleblue Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/purpleblue.com/id488633131?uo=4>© Purpleblue.com</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/0f/28/80/0f288065-6306-cfbb-a37b-c333fcd9ba39/mzl.cgzgoexo.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9972189/5d4deef0-5e62-11e5-857a-4b0f803542d1.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9932047/ee66b174-5d40-11e5-9b86-9c80c31d2023.png)
https://cloud.githubusercontent.com/assets/10730122/9932047/ee66b174-5d40-11e5-9b86-9c80c31d2023.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9932045/e9a9d0a8-5d40-11e5-9cac-0fa623c24744.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9972189/5d4deef0-5e62-11e5-857a-4b0f803542d1.png)
https://cloud.githubusercontent.com/assets/2068130/9972189/5d4deef0-5e62-11e5-857a-4b0f803542d1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9972195/6d1b5ef8-5e62-11e5-97c6-9de93982900a.png
