### ISSUE TITLE
AquaManager - 熱帯魚・水槽管理アプリ

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6340]
**App Name:** AquaManager - 熱帯魚・水槽管理アプリ
**Bundle ID:** com.kdev.aquamanager
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911240593">911240593</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aquamanager-re-dai-yu-shui/id911240593?mt=8&uo=4">https://itunes.apple.com/us/app/aquamanager-re-dai-yu-shui/id911240593?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** keishi okazaki
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/keishi-okazaki/id502974096?uo=4>© keishi okazaki</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/ed/88/97/ed8897a0-1aa3-e0fb-555f-9e70ee8f894a/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9947551/37d3c810-5d9b-11e5-9796-1081a76e9768.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9932241/78808b0e-5d42-11e5-9473-39f26e6ee435.png)
https://cloud.githubusercontent.com/assets/10730122/9932241/78808b0e-5d42-11e5-9473-39f26e6ee435.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9932238/72ca047e-5d42-11e5-8ed3-0f65f624ab92.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9932255/935d89ae-5d42-11e5-95a5-80b92ed65ff3.png)
https://cloud.githubusercontent.com/assets/10730122/9932255/935d89ae-5d42-11e5-95a5-80b92ed65ff3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9932253/8ff9151c-5d42-11e5-94bb-e955840be751.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9947551/37d3c810-5d9b-11e5-9796-1081a76e9768.png)
https://cloud.githubusercontent.com/assets/2068130/9947551/37d3c810-5d9b-11e5-9796-1081a76e9768.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9947564/47d64120-5d9b-11e5-940c-4d31d8e997d6.png

**Comment by Trubbel** [comment]
@dreamnet :+1:
