### ISSUE TITLE
Flotsm

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6341]
**App Name:** Flotsm
**Bundle ID:** com.flotsm.mobile.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=956910677">956910677</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flotsm/id956910677?mt=8&uo=4">https://itunes.apple.com/us/app/flotsm/id956910677?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Flotsm Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/flotsm-limited/id956645231?uo=4>© Flotsm Limited</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60393689-80dd8680-9b19-11e9-8b92-e88d912b00ee.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393697-92bf2980-9b19-11e9-9110-96dc622b3714.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9932485/8d8ce162-5d44-11e5-98f2-ebf1d6f3e78f.png)
https://cloud.githubusercontent.com/assets/10730122/9932485/8d8ce162-5d44-11e5-98f2-ebf1d6f3e78f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9932483/89d7a5d4-5d44-11e5-84cc-1abd4bf83a75.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393697-92bf2980-9b19-11e9-9110-96dc622b3714.png)
https://user-images.githubusercontent.com/2068130/60393697-92bf2980-9b19-11e9-9110-96dc622b3714.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60393702-a5d1f980-9b19-11e9-893a-1333ccadda76.png
