### ISSUE TITLE
Sidewire

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6342]
**App Name:** Sidewire
**Bundle ID:** com.sidewire.reader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1023491591">1023491591</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sidewire/id1023491591?mt=8&uo=4">https://itunes.apple.com/us/app/sidewire/id1023491591?mt=8&uo=4</a>
**App Version:** 1.00
**Seller:** Sidewire, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sidewire-inc./id1023491590?uo=4>© Sidewire, Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/19/f3/13/19f313f7-6738-4cbf-ad33-60f293e3b55c/mzl.paeozguq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9971840/541d52c4-5e5f-11e5-9998-16298a4e90d4.png)

**Comment by Teekzilla** [comment]
Option 1:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9934692/e33f16d0-5d20-11e5-9c2c-da1fd9662433.png)
https://cloud.githubusercontent.com/assets/7368317/9934692/e33f16d0-5d20-11e5-9c2c-da1fd9662433.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9934693/e3442882-5d20-11e5-929b-fba0dee122bd.png

Option 2:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9934695/e4e1e4ae-5d20-11e5-940d-77975fa0ee3a.png)
https://cloud.githubusercontent.com/assets/7368317/9934695/e4e1e4ae-5d20-11e5-940d-77975fa0ee3a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9934697/e5d72b62-5d20-11e5-8039-b31349c408f2.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9971840/541d52c4-5e5f-11e5-9998-16298a4e90d4.png)
https://cloud.githubusercontent.com/assets/2068130/9971840/541d52c4-5e5f-11e5-9998-16298a4e90d4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9971848/62ee92ae-5e5f-11e5-88fd-c0c89b652034.png
