### ISSUE TITLE
MapQuest: Free Navigation, GPS, Maps & Traffic

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6343]
**App Name:** MapQuest: Free Navigation, GPS, Maps & Traffic
**Bundle ID:** com.aol.mapquest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=316126557">316126557</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mapquest-free-navigation-gps/id316126557?mt=8&uo=4">https://itunes.apple.com/us/app/mapquest-free-navigation-gps/id316126557?mt=8&uo=4</a>
**App Version:** 4.8.4
**Seller:** AOL Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aol-inc./id281704577?uo=4>© AOL Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/de/fa/0b/defa0bb5-7f13-9bf8-bd1f-60e7a23fbc7e/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9946878/8613d6c8-5d96-11e5-8b44-8df3ec61f35e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9946878/8613d6c8-5d96-11e5-8b44-8df3ec61f35e.png)
https://cloud.githubusercontent.com/assets/2068130/9946878/8613d6c8-5d96-11e5-8b44-8df3ec61f35e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9946890/95e23694-5d96-11e5-8041-2b238a280155.png
