### ISSUE TITLE
On Now TV Guide

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6344]
**App Name:** On Now TV Guide
**Bundle ID:** tv.i.itv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=290338603">290338603</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/on-now-tv-guide/id290338603?mt=8&uo=4">https://itunes.apple.com/us/app/on-now-tv-guide/id290338603?mt=8&uo=4</a>
**App Version:** 6.0.3
**Seller:** Yo.TV Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yo.tv/id522539111?uo=4>© YO.TV</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/75/50/27/755027bb-67e2-faec-7ab4-84203851af7b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14063967/4c50383a-f3ed-11e5-9f99-c3f180d6b001.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9947039/5a1d9166-5d97-11e5-862d-14d63e87491c.png)
https://cloud.githubusercontent.com/assets/2068130/9947039/5a1d9166-5d97-11e5-862d-14d63e87491c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9947051/683d6488-5d97-11e5-83c3-9027c85b9671.png

**Comment by l8er4now** [comment]
A bit of an update needed.

**App Name:** On Now TV Guide
**Bundle ID:** tv.i.itv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=290338603">290338603</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/on-now-tv-guide/id290338603?mt=8&uo=4">https://itunes.apple.com/us/app/on-now-tv-guide/id290338603?mt=8&uo=4</a>
**App Version:** 6.0.3
**Seller:** Yo.TV Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yo.tv/id522539111?uo=4>© YO.TV</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/75/50/27/755027bb-67e2-faec-7ab4-84203851af7b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14063967/4c50383a-f3ed-11e5-9f99-c3f180d6b001.png)
https://cloud.githubusercontent.com/assets/2068130/14063967/4c50383a-f3ed-11e5-9f99-c3f180d6b001.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14063969/5da90d82-f3ed-11e5-8143-d632fdf53abf.png
