### ISSUE TITLE
Trove News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6345]
**App Name:** Trove News
**Bundle ID:** com.wapo.ngn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426504578">426504578</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trove-news/id426504578?mt=8&uo=4">https://itunes.apple.com/us/app/trove-news/id426504578?mt=8&uo=4</a>
**App Version:** 4.0.10
**Seller:** Graham Holdings Company
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/trove/id783648725?uo=4>© Trove</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/69/fd/e3/69fde3fe-d103-a3a3-17e6-d9e8962bca70/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9947244/f62e2b78-5d98-11e5-8c5a-c3051c5caf98.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9947126/199f6136-5d98-11e5-8d67-5986248e8f7f.png)
https://cloud.githubusercontent.com/assets/2068130/9947126/199f6136-5d98-11e5-8d67-5986248e8f7f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9947135/2830d14e-5d98-11e5-8de8-bc9fe3a80168.png
