### ISSUE TITLE
Candy Crush Saga

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#635]
**App Name:** Candy Crush Saga
**Bundle ID:** com.midasplayer.apps.candycrushsaga
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=553834731">553834731</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/candy-crush-saga/id553834731?mt=8&uo=4">https://itunes.apple.com/us/app/candy-crush-saga/id553834731?mt=8&uo=4</a>
**App Version:** 1.84
**Seller:** King.com Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/king/id526656015?uo=4>© King</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/52/e0/02/52e002b0-dfc2-acfc-1b62-1206b31740fb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18635342/f7ee0ee8-7e84-11e6-95ca-37f3c54b4c21.png)

**Comment by grkka** [comment]
Needs update to version 5.00.0

**Comment by 2Qt2beStr8** [comment]
@grkka ... sorry, i am not so good in creating game app icons :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18635034/cb7c0aaa-7e83-11e6-972d-305dc863f27f.png)
https://cloud.githubusercontent.com/assets/20930745/18635034/cb7c0aaa-7e83-11e6-972d-305dc863f27f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18635052/de33f612-7e83-11e6-9f1a-5c9fd3a328b8.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18635342/f7ee0ee8-7e84-11e6-95ca-37f3c54b4c21.png)
https://cloud.githubusercontent.com/assets/20930745/18635342/f7ee0ee8-7e84-11e6-95ca-37f3c54b4c21.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18635357/0adeae72-7e85-11e6-88b9-eaeaffdf5b1d.png
