### ISSUE TITLE
YAHTZEE® With Buddies

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6356]
**App Name:** YAHTZEE® With Buddies
**Bundle ID:** com.scopely.yahtzeewithbuddies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967422975">967422975</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahtzee-with-buddies/id967422975?mt=8&uo=4">https://itunes.apple.com/us/app/yahtzee-with-buddies/id967422975?mt=8&uo=4</a>
**App Version:** 4.8.1
**Seller:** Scopely - Top Free Apps and Games LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/scopely/id305003647?uo=4>© Scopely</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/54/a9/55/54a95537-7f52-8aa1-83ac-6abeda42ea07/mzl.cyfedttn.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9975000/d701f0a0-5eaa-11e5-95b3-f9989f8d1121.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9975000/d701f0a0-5eaa-11e5-95b3-f9989f8d1121.png)
https://cloud.githubusercontent.com/assets/2068130/9975000/d701f0a0-5eaa-11e5-95b3-f9989f8d1121.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9975004/e7b9b342-5eaa-11e5-9837-28c84095d6e3.png
