### ISSUE TITLE
Recent News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6357]
**App Name:** Recent News
**Bundle ID:** io.recent.ai-news
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1009026110">1009026110</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/recent-news/id1009026110?mt=8&uo=4">https://itunes.apple.com/us/app/recent-news/id1009026110?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Recent Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/recent-media-inc./id1009026109?uo=4>© Recent Media Inc.</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPadWifi, iPad3G, iPodTouchThirdGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/d5/fd/ce/d5fdcef1-95e2-e1a3-f1bc-40024b6f0173/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9974830/02e6a622-5ea4-11e5-873c-0128604b5365.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9974830/02e6a622-5ea4-11e5-873c-0128604b5365.png)
https://cloud.githubusercontent.com/assets/2068130/9974830/02e6a622-5ea4-11e5-873c-0128604b5365.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9974832/12244428-5ea4-11e5-97e9-e89fafd91e1f.png
