### ISSUE TITLE
Provenance

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6359]
**App Name:** Provenance
**Bundle ID:** com.jamsoftonline.Provenance
**Version:** 1.1.6-1
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/10730122/9977410/27e29c8e-5f07-11e5-9fc9-a5b563a5b0c4.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9977647/75d886da-5f0f-11e5-9b29-d430adb0c91f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9977647/75d886da-5f0f-11e5-9b29-d430adb0c91f.png)
https://cloud.githubusercontent.com/assets/2068130/9977647/75d886da-5f0f-11e5-9b29-d430adb0c91f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9977648/857bbe54-5f0f-11e5-8365-bde1d43870d9.png

**Comment by Trubbel** [comment]
@dreamnet Thanks! :smile:

**Comment by dreamnet** [comment]
@Trubbel :+1:
