### ISSUE TITLE
PostNord Sweden

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6360]
**App Name:** PostNord Sweden
**Bundle ID:** se.posten.SparaForsandelse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=396871673">396871673</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/postnord-sweden/id396871673?mt=8&uo=4">https://itunes.apple.com/us/app/postnord-sweden/id396871673?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** PostNord Group AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/postnord-group-ab/id396871676?uo=4">© PostNord Group AB</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/c2/35/ce/c235ce4b-00b6-258a-15da-311f3920c62c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/20483726/dfe3f786-aff3-11e6-9bcc-751e3182b44e.png)

**Comment by Trubbel** [comment]
Updated icon, no issue as well.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9977431/1564fd8a-5f08-11e5-8b21-137130c0b119.png)
https://cloud.githubusercontent.com/assets/10730122/9977431/1564fd8a-5f08-11e5-8b21-137130c0b119.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9977430/12593a34-5f08-11e5-8b37-9af0ac408e0c.png

**Comment by Trubbel** [comment]
The icon has been updated.. again,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10149669/3816b686-663b-11e5-88b2-ade93c2ffb63.png)
https://cloud.githubusercontent.com/assets/10730122/10149669/3816b686-663b-11e5-88b2-ade93c2ffb63.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10149665/3481ff6c-663b-11e5-9c37-9135bed2edf1.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/20483726/dfe3f786-aff3-11e6-9bcc-751e3182b44e.png)
https://cloud.githubusercontent.com/assets/10730122/20483726/dfe3f786-aff3-11e6-9bcc-751e3182b44e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/20483727/dfff0210-aff3-11e6-93ab-4d65a008d324.png

**Comment by 2Qt2beStr8** [comment]
.... or something like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20493818/a22ec7aa-b01a-11e6-9ccd-de92fcd74425.png)
https://cloud.githubusercontent.com/assets/20930745/20493818/a22ec7aa-b01a-11e6-9ccd-de92fcd74425.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20493831/af4f0cce-b01a-11e6-936f-0b61a178702d.png

**Comment by Trubbel** [comment]
I tried them both and looked at them both on my SpringBoard, but I think I prefer the one I made.
