### ISSUE TITLE
White Noise Recorder

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#637]
**App Name:** White Noise Recorder
**Bundle ID:** com.tmsoft.WhiteNoiseRecorder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=334887224">334887224</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/white-noise-recorder/id334887224?mt=8&uo=4">https://itunes.apple.com/us/app/white-noise-recorder/id334887224?mt=8&uo=4</a>
**App Version:** 5.4.2
**Seller:** TMSOFT
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tmsoft/id288669797?uo=4>© TMSOFT</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple2/v4/8f/29/f0/8f29f0be-e957-73e7-213f-029bb0fc99f6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19529325/acb3a1dc-962f-11e6-8e4b-14548f6984cf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19529325/acb3a1dc-962f-11e6-8e4b-14548f6984cf.png)
https://cloud.githubusercontent.com/assets/20930745/19529325/acb3a1dc-962f-11e6-8e4b-14548f6984cf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19529349/c4d0e400-962f-11e6-8b08-ad0d40b79639.png
