### ISSUE TITLE
Zweet - Grocery Savings & Cash Back, Not Coupons

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6376]
**App Name:** Zweet - Grocery Savings & Cash Back, Not Coupons
**Bundle ID:** com.dynamo.zweet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=785627013">785627013</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zweet-grocery-savings-cash/id785627013?mt=8&uo=4">https://itunes.apple.com/us/app/zweet-grocery-savings-cash/id785627013?mt=8&uo=4</a>
**App Version:** 1.5.4
**Seller:** Zweet inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zweet/id934483493?uo=4>© Zweet</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, 785627013785627013, iPhone6Plus, iPodTouchSixthGen
**Original  
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/d7/09/ef/d709ef0a-ee3b-eece-3b69-209746c17c13/mzl.hbomklnv.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9983580/2d4d53b2-5fcf-11e5-85f4-84613c823a30.png)

**Comment by Teekzilla** [comment]
Personally prefer Option 1...

Option 1:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9983580/2d4d53b2-5fcf-11e5-85f4-84613c823a30.png)
https://cloud.githubusercontent.com/assets/7368317/9983580/2d4d53b2-5fcf-11e5-85f4-84613c823a30.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9983579/2c88fddc-5fcf-11e5-9062-bedae746f24b.png

Option 2:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7368317/9983583/2f7c1b50-5fcf-11e5-886c-1cc9174484b0.png)
https://cloud.githubusercontent.com/assets/7368317/9983583/2f7c1b50-5fcf-11e5-886c-1cc9174484b0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/7368317/9983582/2e4792be-5fcf-11e5-8ca5-3fc16f8d9ae2.png

**Comment by LaCh0uine** [comment]
The one for me too
