### ISSUE TITLE
Today - Smart Calendar for Busy People

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6377]
**App Name:** Today - Smart Calendar for Busy People
**Bundle ID:** com.lightpillar.today
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=975528282">975528282</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/today-smart-calendar-for-busy/id975528282?mt=8&uo=4">https://itunes.apple.com/us/app/today-smart-calendar-for-busy/id975528282?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Light Pillar Software Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/light-pillar-software-ltd/id1027770093?uo=4>© Light Pillar Software Ltd</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/07/e4/6a/07e46a05-5f46-41e0-0f86-7728cefa9806/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10011568/acd7ef60-60fc-11e5-94db-00b8c89ef28f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10011568/acd7ef60-60fc-11e5-94db-00b8c89ef28f.png)
https://cloud.githubusercontent.com/assets/2068130/10011568/acd7ef60-60fc-11e5-94db-00b8c89ef28f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10011573/bcc94086-60fc-11e5-8098-602ef660e3d7.png
