### ISSUE TITLE
Cognito: Brain Training Games

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6385]
**App Name:** Cognito: Brain Training Games
**Bundle ID:** TidePool.TidePoolTwo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=872808619">872808619</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cognito-brain-training-games/id872808619?mt=8&uo=4">https://itunes.apple.com/us/app/cognito-brain-training-games/id872808619?mt=8&uo=4</a>
**App Version:** 2.6.17
**Seller:** TidePool, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tidepool-inc./id691052610?uo=4>© TidePool, Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/96/8c/15/968c159e-89d0-32e9-3444-c131cfc5d138/mzl.euvhyies.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9993726/7b1c924c-6079-11e5-8eef-1fa39c8c6f68.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/9993726/7b1c924c-6079-11e5-8eef-1fa39c8c6f68.png)
https://cloud.githubusercontent.com/assets/10730122/9993726/7b1c924c-6079-11e5-8eef-1fa39c8c6f68.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/9993723/776abc78-6079-11e5-8e00-03b443b59577.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
