### ISSUE TITLE
Whisper

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6386]
**App Name:** Whisper
**Bundle ID:** sh.whisper.whisperapp-urban
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=999134850">999134850</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/whisper/id999134850?mt=8&uo=4">https://itunes.apple.com/au/app/whisper/id999134850?mt=8&uo=4</a>
**App Version:** 5.4.0
**Seller:** WhisperText LLC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/developer/whispertext-llc./id506141840?uo=4>© WhisperText LLC.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/7a/0e/db/7a0edb08-038b-a96c-6375-18301190cc3d/mzl.iggobsmi.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10011299/67af6cfa-60f8-11e5-91db-51e54c89de79.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10011299/67af6cfa-60f8-11e5-91db-51e54c89de79.png)
https://cloud.githubusercontent.com/assets/2068130/10011299/67af6cfa-60f8-11e5-91db-51e54c89de79.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10011307/766130b2-60f8-11e5-9fc6-8079b88051bd.png
