### ISSUE TITLE
In-flight Entertainment by Virgin Australia HD

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6387]
**App Name:** In-flight Entertainment by Virgin Australia HD
**Bundle ID:** com.lhsystems.ife.boardconnect.dj.ipad.daios.ped
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=563516883">563516883</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/in-flight-entertainment-by/id563516883?mt=8&uo=4">https://itunes.apple.com/us/app/in-flight-entertainment-by/id563516883?mt=8&uo=4</a>
**App Version:** 3.4.4.1
**Seller:** Lufthansa Systems Americas Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lufthansa-systems/id413078252?uo=4>© Lufthansa Systems</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/f2/4b/18/f24b184a-89d6-e503-32ef-1a79746ed0c6/mzl.sljwflzc.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10064814/709c369a-6242-11e5-97b2-564f71b05065.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10064814/709c369a-6242-11e5-97b2-564f71b05065.png)
https://cloud.githubusercontent.com/assets/3090247/10064814/709c369a-6242-11e5-97b2-564f71b05065.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10064813/709c3302-6242-11e5-8130-2cf1c041ab74.png

**Comment by dreamnet** [comment]
iPad only app - I'm not adding this icon to the master.

**Comment by quantum8** [comment]
Sorry @dreamnet, I must have accidentally gotten the wrong ID for this. Resubmitted [here] (https://github.com/glasklart/hd/issues/6423)
