### ISSUE TITLE
PC Financial Mobile Banking

### ISSUE THREAD

**Issue by sddevstudio** [glasklart/hd#6388]
**App Name:** PC Financial Mobile Banking
**Bundle ID:** com.cibc.mobilepcf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=581352806">581352806</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pc-financial-mobile-banking/id581352806?mt=8&uo=4">https://itunes.apple.com/us/app/pc-financial-mobile-banking/id581352806?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Canadian Imperial Bank of Commerce
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cibc/id351448956?uo=4>© CIBC</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPadWifi, iPad3G, iPodTouchThirdGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/4e/f6/65/4ef6659d-3e24-9cd6-f6b6-55dfc76f63bd/mzl.krwcumjw.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at? image=https://cloud.githubusercontent.com/assets/2068130/10011418/26b257a6-60fa-11e5-8ea3-0772d35a832a.png)

**Comment by sddevstudio** [comment]
![com cibc mobilepcf 2x](https://cloud.githubusercontent.com/assets/2735760/10011257/b89e5bd8-60b4-11e5-9e50-b67ee952a5a3.png)

**Comment by sddevstudio** [comment]
source: 
https://cloud.githubusercontent.com/assets/2735760/10011425/2cc3ace6-60b7-11e5-8898-af03221411d6.png

**Comment by dreamnet** [comment]
@sddevstudio Yes, jooks great! :+1: 
Contributions should look like this:
![2x](http://preview.dreamnet.at? image=https://cloud.githubusercontent.com/assets/2068130/10011418/26b257a6-60fa-11e5-8ea3-0772d35a832a.png)
https://cloud.githubusercontent.com/assets/2068130/10011418/26b257a6-60fa-11e5-8ea3-0772d35a832a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10011424/3a4f0db8-60fa-11e5-94d8-051f0f2a79ff.png
Your source file also looks good, but the icon in the soure should go to the edges (by keeping aspect ratio, just compare with mine). The 1024x1024px area in the source file "represents" the 78x78py area in the Glasklart icon.
Also: I you want me to give you credits for this contribution, you need to add a public mailaddress to your Github account.

**Comment by sddevstudio** [comment]
Sounds good, I will remember that for next time. I have updated my profile.

**Comment by dreamnet** [comment]
@sddevstudio Perfect! :+1:
