### ISSUE TITLE
BANG! the Official Video Game

### ISSUE THREAD

**Issue by sddevstudio** [glasklart/hd#6389]
**App Name:** BANG! the Official Video Game
**Bundle ID:** com.spinvector.bang
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406634232">406634232</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bang!-the-official-video-game/id406634232?mt=8&uo=4">https://itunes.apple.com/us/app/bang!-the-official-video-game/id406634232?mt=8&uo=4</a>
**App Version:** 2.1.6
**Seller:** SpinVector S.p.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/spinvector-s.p.a./id406634235?uo=4>© SpinVector S.p.A.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/88/db/d8/mzl.ycioxlsy.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10031470/a4c5ba7e-617d-11e5-8a29-2ce6751522d2.png)

**Comment by sddevstudio** [comment]
![com spinvector bang 2x](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2735760/10020340/9616693e-60ff-11e5-8b60-ea2128404d99.png)
https://cloud.githubusercontent.com/assets/2735760/10020340/9616693e-60ff-11e5-8b60-ea2128404d99.png

Source:
https://cloud.githubusercontent.com/assets/2735760/10020355/aa71b622-60ff-11e5-9ac0-ef30ec721fa5.png

**Comment by sddevstudio** [comment]
Tweaked a bit for scaled down icon:
![com spinvector bang 2x](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2735760/10021516/9555e244-6105-11e5-8ba4-a20c75351ac0.png)

**Comment by dreamnet** [comment]
Or something like this?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10031470/a4c5ba7e-617d-11e5-8a29-2ce6751522d2.png)
https://cloud.githubusercontent.com/assets/2068130/10031470/a4c5ba7e-617d-11e5-8a29-2ce6751522d2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10031482/c023732e-617d-11e5-98d2-d0f7c4eb1057.png

**Comment by sddevstudio** [comment]
that one is definitely a little more creative, looks good :)
