### ISSUE TITLE
CocoaTop

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#6390]
**App Name:** CocoaTop
**Bundle ID:** ru.domo.CocoaTop
**Version:** 2.0.0-309
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/7157389/14708785/5b21d35c-07cd-11e6-9fae-5f41fd6fd10b.PNG" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16901465/ede092d0-4c44-11e6-85b6-4051b58e59e5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10038422/45f157ee-61c6-11e5-9349-ce8b54c094ac.png)
https://cloud.githubusercontent.com/assets/2068130/10038422/45f157ee-61c6-11e5-9349-ce8b54c094ac.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10038425/54d91648-61c6-11e5-8709-780e799e01f8.png

**Comment by Anuskuss** [comment]
**App Name:** CocoaTop
**Bundle ID:** ru.domo.CocoaTop
**Version:** 2.0.0-309
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/7157389/14708785/5b21d35c-07cd-11e6-9fae-5f41fd6fd10b.PNG" width="150" height="150" />

**Comment by Anuskuss** [comment]
Update without the grid?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16901465/ede092d0-4c44-11e6-85b6-4051b58e59e5.png)
https://cloud.githubusercontent.com/assets/2068130/16901465/ede092d0-4c44-11e6-85b6-4051b58e59e5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16901466/fcab38f6-4c44-11e6-8e6c-e3c883aed6c2.png

**Comment by Anuskuss** [comment]
Looks good :+1:
