### ISSUE TITLE
Monster Squad

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6392]
**App Name:** Monster Squad
**Bundle ID:** com.nexonm.monstersquad.distribution
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=886424413">886424413</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/monster-squad/id886424413?mt=8&uo=4">https://itunes.apple.com/us/app/monster-squad/id886424413?mt=8&uo=4</a>
**App Version:** 2.00.16664
**Seller:** NEXON M Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nexon-m-inc./id520995277?uo=4>© NEXON M Inc.</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/6d/07/52/6d0752a6-9c77-2226-a99e-417a7fb6796e/mzl.gakcuwxt.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10036440/6ed9cae6-616d-11e5-8559-b59f5f3de6a7.png)

**Comment by Trubbel** [comment]
Best I could do,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10030116/4cd5af06-6176-11e5-953d-c93ca17d268c.png)
https://cloud.githubusercontent.com/assets/10730122/10030116/4cd5af06-6176-11e5-953d-c93ca17d268c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10030112/4a74c1d4-6176-11e5-8fc3-5867dcc4d05c.png

**Comment by ivanov007** [comment]
I think the eye should look better inverted

**Comment by ivanov007** [comment]
something like this
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10036440/6ed9cae6-616d-11e5-8559-b59f5f3de6a7.png)
https://cloud.githubusercontent.com/assets/3090247/10036440/6ed9cae6-616d-11e5-8559-b59f5f3de6a7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10036439/6ed79906-616d-11e5-9f8c-85a2a6924839.png

btw I just modified your source, so the credit is totally yours

**Comment by Trubbel** [comment]
@ivanov007 Yeah that looks better. :+1:
