### ISSUE TITLE
Dependencies to Winterboard and IconBundles

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6393]
Hello, Anemone with Glasklart use, and in the previous update Winterboard not needed, but with the latest update, forcing me back to install IconBundles and Winterboard.

**Comment by dreamnet** [comment]
@grkka Yes, I recognized it for 4.25 #6375 and pushed out 4.26 #6391. I'm sorry for this, but it was not my fault.

**Comment by grkka** [comment]
Hi, no problem. It was only a warning. Thank you for the work. I'm new to GitHub and it makes little use Glasklart. Any way to request new icons is there, I am Spanish and many apps here are not in the subject. Thank you.

Enviado desde mi iPhone


martes, 22 de septiembre de 2015 23:37 +0200 de Günther Kirchmair  <notifications@github.com>:

**Comment by ivanov007** [comment]
@grkka [aqui](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request) puedes ver las instrucciones, voy a actualizar la guia para poder sacar el bundle id de itunes, si tienes alguna duda puedes mandarme correo

**Comment by dreamnet** [comment]
I'm closing this cause I already submitted 4.26 to ModMyi and asked (again) to remove the dependencies.

**Comment by grkka** [comment]
Buenos días, 

Gracias por la información. Estoy intentado solicitar iconos mediante la web, pero o tarda mucho o lo hago mal. Los enlaces los creo como decís en la web, pero lleva como 15 minutos así como te adjunto en la foto y de ahí no pasa. 

Gracias. 

Enviado desde mi iPhone


miércoles, 23 de septiembre de 2015 1:13 +0200 de Ivanov  <notifications@github.com>:
