### ISSUE TITLE
Noodles!

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6394]
**App Name:** Noodles!
**Bundle ID:** com.lummoxlabs.pivot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967624193">967624193</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/noodles!/id967624193?mt=8&uo=4">https://itunes.apple.com/us/app/noodles!/id967624193?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Michael Busheikin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/michael-busheikin/id967624192?uo=4>© Michael Busheikin</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/e7/0a/8c/e70a8c11-a7bf-6cb1-5210-330f7ea4eab7/mzl.lkchwuqz.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10064583/755823fe-623f-11e5-9e77-7d97b0048d98.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10064583/755823fe-623f-11e5-9e77-7d97b0048d98.png)
https://cloud.githubusercontent.com/assets/3090247/10064583/755823fe-623f-11e5-9e77-7d97b0048d98.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10064584/7558ee38-623f-11e5-823e-2911673c7a4e.png
