### ISSUE TITLE
SWISS

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6398]
**App Name:** SWISS
**Bundle ID:** com.swiss.launcher
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=343038584">343038584</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swiss/id343038584?mt=8&uo=4">https://itunes.apple.com/us/app/swiss/id343038584?mt=8&uo=4</a>
**App Version:** 3.2.4
**Seller:** Swiss International Air Lines AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/swiss-international-air-lines/id343038587?uo=4>© Swiss International Air Lines Ltd.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/48/ed/af/48edafd6-d6ed-d97a-a2b0-696f12ce6138/mzl.ppqkppti.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10052772/d7c2a9ea-6228-11e5-8664-5a6e78ead874.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10052772/d7c2a9ea-6228-11e5-8664-5a6e78ead874.png)
https://cloud.githubusercontent.com/assets/10730122/10052772/d7c2a9ea-6228-11e5-8664-5a6e78ead874.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10052770/d53cb350-6228-11e5-9b9b-7d3245e219a5.png

**Comment by ivanov007** [comment]
a different approach
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10064413/ba9b5d8e-623d-11e5-8939-de875520f1b7.png)
https://cloud.githubusercontent.com/assets/3090247/10064413/ba9b5d8e-623d-11e5-8939-de875520f1b7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10064414/ba9e0d86-623d-11e5-8bb1-807fe1cecdca.png

**Comment by Teekzilla** [comment]
I'm liking the first one, and it sticks to the original quite well, but nice on both!
