### ISSUE TITLE
Infinity Blade II

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#64]
**App Name:** Infinity Blade II
**Bundle ID:** com.chairentertainment.IB2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447689011">447689011</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/infinity-blade-ii/id447689011?mt=8&uo=4">https://itunes.apple.com/us/app/infinity-blade-ii/id447689011?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Chair Entertainment Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chair-entertainment-group/id387428403?uo=4>© Chair Entertainment Group, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/13/c5/16/13c516d1-7458-8a1a-b5a7-f4f77e4c3d9f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12768590/e32410f8-ca10-11e5-8374-21fb0e559ba2.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12768590/e32410f8-ca10-11e5-8374-21fb0e559ba2.png)
https://cloud.githubusercontent.com/assets/10730122/12768590/e32410f8-ca10-11e5-8374-21fb0e559ba2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12768591/e325cb50-ca10-11e5-8243-7dc1c2d7847e.png
