### ISSUE TITLE
momit Smart Thermostat

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6407]
**App Name:** momit Smart Thermostat
**Bundle ID:** es.greenmomit.momitST
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=666206909">666206909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/momit-smart-thermostat/id666206909?mt=8&uo=4">https://itunes.apple.com/us/app/momit-smart-thermostat/id666206909?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** GREEN MOMIT SL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/green-momit/id666206912?uo=4>© Green Momit</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/48/63/30/48633002-5b4e-4212-bb32-1dd3a8c1e259/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14398980/36d9005c-fdae-11e5-9d13-f1c410601a8e.png)

**Comment by ivanov007** [comment]
@grkka muy bien, solo ten en cuenta que el nombre del issue debe de ser toda la linea que está despues de `App Name: `

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10091056/18f018fc-62fc-11e5-92cc-c99cd9f52b24.png)
https://cloud.githubusercontent.com/assets/3090247/10091056/18f018fc-62fc-11e5-92cc-c99cd9f52b24.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10091057/18fd06a2-62fc-11e5-8d04-f61d7f35c246.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:

**Comment by grkka** [comment]
You need to upgrade? Or just leave?
**App Name:** momit Smart Thermostat
**Bundle ID:** es.greenmomit.momitST
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=666206909">666206909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/momit-smart-thermostat/id666206909?mt=8&uo=4">https://itunes.apple.com/us/app/momit-smart-thermostat/id666206909?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** GREEN MOMIT SL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/green-momit/id666206912?uo=4>© Green Momit</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/48/63/30/48633002-5b4e-4212-bb32-1dd3a8c1e259/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14398980/36d9005c-fdae-11e5-9d13-f1c410601a8e.png)
https://cloud.githubusercontent.com/assets/3090247/14398980/36d9005c-fdae-11e5-9d13-f1c410601a8e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14398981/36e82bb8-fdae-11e5-997b-0994a4c7338b.png
