### ISSUE TITLE
DNDzgz

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6408]
**App Name:** DNDzgz
**Bundle ID:** net.gimenete.dndzgz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=381727379">381727379</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dndzgz/id381727379?mt=8&uo=4">https://itunes.apple.com/us/app/dndzgz/id381727379?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** LEVEL APPS SL.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/level-apps-sl./id381727382?uo=4>© LEVEL APPS SL.</a>
**Supported Devices:** iPadWifi, iPad3G, iPodTouchThirdGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/ee/14/ee/ee14ee1c-0843-14c3-9fd9-cdae894c82f7/mzl.bgixhszq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10061799/d9fe510c-6221-11e5-8d6f-2210537bf299.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10061799/d9fe510c-6221-11e5-8d6f-2210537bf299.png)
https://cloud.githubusercontent.com/assets/3090247/10061799/d9fe510c-6221-11e5-8d6f-2210537bf299.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10061800/d9fe9522-6221-11e5-8a08-199b5a177701.png
