### ISSUE TITLE
Goles Messenger - Instant live scores and football alerts

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6409]
**App Name:** Goles Messenger - Instant live scores and football alerts
**Bundle ID:** com.fav24.golesmessenger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=546611684">546611684</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/goles-messenger-instant-live/id546611684?mt=8&uo=4">https://itunes.apple.com/us/app/goles-messenger-instant-live/id546611684?mt=8&uo=4</a>
**App Version:** 5.0.0
**Seller:** World Tour Platforms SL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fav24/id353772338?uo=4>© Fav24</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/49/64/47/496447ab-d28f-cdff-0239-1ac7da2113f3/mzl.npdmswds.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10062059/26fcd6e8-6224-11e5-969c-a41ebd83e0ff.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10062059/26fcd6e8-6224-11e5-969c-a41ebd83e0ff.png)
https://cloud.githubusercontent.com/assets/3090247/10062059/26fcd6e8-6224-11e5-969c-a41ebd83e0ff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10062060/26ffd564-6224-11e5-8412-af58bc90bab3.png
