### ISSUE TITLE
Bad Hotel

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#641]
**App Name:** Bad Hotel
**Bundle ID:** com.luckyframe.badHotel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=548665066">548665066</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bad-hotel/id548665066?mt=8&uo=4">https://itunes.apple.com/us/app/bad-hotel/id548665066?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Lucky Frame Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lucky-frame/id324895778?uo=4>© Lucky Frame</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/59/cf/8f/59cf8ff3-3968-255b-7dbf-12172e875333/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19528879/09ee7c84-962e-11e6-8baf-94a134c68529.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19528879/09ee7c84-962e-11e6-8baf-94a134c68529.png)
https://cloud.githubusercontent.com/assets/20930745/19528879/09ee7c84-962e-11e6-8baf-94a134c68529.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19528897/1f4d1ffe-962e-11e6-95bb-74e7053438dc.png
