### ISSUE TITLE
20minutos Noticias

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6410]
**App Name:** 20minutos Noticias
**Bundle ID:** com.20minutos.veinteminutos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=362312530">362312530</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/20minutos-noticias/id362312530?uo=4">https://apps.apple.com/us/app/20minutos-noticias/id362312530?uo=4</a>
**App Version:** 1.28
**Seller:** Grupo 20 Minutos SL
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/grupo-20-minutos-sl/id362312533?uo=4">© Grupo 20 Minutos SL</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/9c/75/79/9c7579cd-05e9-0f9d-668a-f22b794c4bee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973753-233ebc80-95a4-11e9-9dba-b13fa20f63cf.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10062162/636983dc-6225-11e5-8df7-168c2329972c.png)
https://cloud.githubusercontent.com/assets/3090247/10062162/636983dc-6225-11e5-8df7-168c2329972c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10062161/6368606a-6225-11e5-8a10-2652bf06760b.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973753-233ebc80-95a4-11e9-9dba-b13fa20f63cf.png)
(https://user-images.githubusercontent.com/20930745/59973753-233ebc80-95a4-11e9-9dba-b13fa20f63cf.png

Source:
https://user-images.githubusercontent.com/20930745/59973754-25088000-95a4-11e9-90d6-c2cba15a5967.png
