### ISSUE TITLE
Radium ~ Perfect Internet Radio

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6411]
**App Name:** Radium ~ Perfect Internet Radio
**Bundle ID:** com.catpigstudios.Radium-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=684034823">684034823</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radium-perfect-internet-radio/id684034823?mt=8&uo=4">https://itunes.apple.com/us/app/radium-perfect-internet-radio/id684034823?mt=8&uo=4</a>
**App Version:** 1.1.10
**Seller:** CatPig Studios Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/catpig-studios-inc./id413215893?uo=4>© CatPig Studios Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/75/cd/bc/75cdbc83-b395-89d3-e55f-25e71f26cfba/mzl.yasvipgn.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10123563/1b8054b8-653d-11e5-9c56-3b87ac1ac6d2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10123563/1b8054b8-653d-11e5-9c56-3b87ac1ac6d2.png)
https://cloud.githubusercontent.com/assets/2068130/10123563/1b8054b8-653d-11e5-9c56-3b87ac1ac6d2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10123568/2d194f68-653d-11e5-9759-0dbbfb86a6cf.png
