### ISSUE TITLE
 coconutBattery

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6412]
**App Name:** coconutBattery
**Bundle ID:** com.coconut-flavour.coconutBattery.iOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032800414">1032800414</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/coconutbattery/id1032800414?mt=8&uo=4">https://itunes.apple.com/us/app/coconutbattery/id1032800414?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Christoph Sinai
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/christoph-sinai/id1032800413?uo=4>© Christoph Sinai</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/31/ff/1f/31ff1f68-4c0b-43ca-78eb-8f65a5ac9e25/pr_source.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10062301/e6e370e6-6226-11e5-8c2a-20a04a27ac83.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10062300/e6df6abe-6226-11e5-86db-18fb23ba81e4.png)
https://cloud.githubusercontent.com/assets/3090247/10062300/e6df6abe-6226-11e5-86db-18fb23ba81e4.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10062301/e6e370e6-6226-11e5-8c2a-20a04a27ac83.png)
https://cloud.githubusercontent.com/assets/3090247/10062301/e6e370e6-6226-11e5-8c2a-20a04a27ac83.png
--- ---
Sourcess:
https://cloud.githubusercontent.com/assets/3090247/10062302/e6e3b7f4-6226-11e5-8fcf-5aad3c3b45ad.png
https://cloud.githubusercontent.com/assets/3090247/10062299/e6b54bbc-6226-11e5-8078-9a5e53c9cddf.png
