### ISSUE TITLE
TuLotero - Jugar Loterias y Apuestas del Estado, Euromillones, Bonoloto, Primitiva y más

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6413]
**App Name:** TuLotero - Jugar Loterias y Apuestas del Estado, Euromillones, Bonoloto, Primitiva y más
**Bundle ID:** com.tulotero.loterias
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=948041023">948041023</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tulotero-jugar-loterias-y/id948041023?mt=8&uo=4">https://itunes.apple.com/us/app/tulotero-jugar-loterias-y/id948041023?mt=8&uo=4</a>
**App Version:** 1.6.1
**Seller:** TuLotero App, sl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tulotero/id991804857?uo=4>© TuLotero</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/2b/3d/13/2b3d13bb-1910-3e53-c086-b7035d701489/mzl.sicybqkg.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10063238/23872286-6231-11e5-9473-180817e53cea.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10063238/23872286-6231-11e5-9473-180817e53cea.png)
https://cloud.githubusercontent.com/assets/3090247/10063238/23872286-6231-11e5-9473-180817e53cea.png)
---- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/10063239/23acf9f2-6231-11e5-8231-d45d1cea683e.png
