### ISSUE TITLE
Hardcover Pro - Touch ID Protects Your Albums

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6414]
**App Name:** Hardcover Pro - Touch ID Protects Your Albums
**Bundle ID:** com.peta-vision.Album
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914869805">914869805</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hardcover-pro-touch-id-protects/id914869805?mt=8&uo=4">https://itunes.apple.com/us/app/hardcover-pro-touch-id-protects/id914869805?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Peta Vision
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/peta-vision/id401432180?uo=4>© Peta Vision</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/72/68/45/726845ec-8e0e-d59d-8db3-31f092116039/mzl.bbaimgxo.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10063345/46b240b4-6232-11e5-8033-322110f9f834.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10063345/46b240b4-6232-11e5-8033-322110f9f834.png)
https://cloud.githubusercontent.com/assets/3090247/10063345/46b240b4-6232-11e5-8033-322110f9f834.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/10063346/46b8b7fa-6232-11e5-9909-e386a527f4a4.png
