### ISSUE TITLE
Ibercaja

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6415]
**App Name:** Ibercaja
**Bundle ID:** es.ibercaja.ibercajaapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=515972019">515972019</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ibercaja/id515972019?mt=8&uo=4">https://itunes.apple.com/us/app/ibercaja/id515972019?mt=8&uo=4</a>
**App Version:** 1.7.3
**Seller:** IBERCAJA BANCO SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ibercaja/id515972022?uo=4>© Ibercaja</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/65/05/34/6505341d-dd5e-f63a-25fb-ddf03e74b1f2/mzl.xnrsdxcs.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10063496/0d06c662-6234-11e5-8c42-192a6b47ea6a.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10063496/0d06c662-6234-11e5-8c42-192a6b47ea6a.png)
https://cloud.githubusercontent.com/assets/3090247/10063496/0d06c662-6234-11e5-8c42-192a6b47ea6a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10063497/0d5f06ce-6234-11e5-9563-8d058e1e442d.png
