### ISSUE TITLE
Banco Sabadell

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6416]
**App Name:** Banco Sabadell
**Bundle ID:** com.bancosabadell.sabloc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347887638">347887638</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/banco-sabadell/id347887638?mt=8&uo=4">https://itunes.apple.com/us/app/banco-sabadell/id347887638?mt=8&uo=4</a>
**App Version:** 15.7
**Seller:** Banco de Sabadell, S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/banco-de-sabadell-s.a./id347887641?uo=4>© Banco de Sabadell, S.A.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/21/a6/ab/21a6ab1e-9d8e-476a-7a84-69e7c7ebc9a8/mzl.awvxbsiz.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10063699/4681a108-6236-11e5-9551-ad0c3ba44881.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10063658/09bfd96a-6236-11e5-853b-876fd9cd0ce3.png)
https://cloud.githubusercontent.com/assets/3090247/10063658/09bfd96a-6236-11e5-853b-876fd9cd0ce3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10063676/1deb7638-6236-11e5-99f9-6effea8da4c7.png
