### ISSUE TITLE
Inform: Personalized News Discovery

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6417]
**App Name:** Inform: Personalized News Discovery
**Bundle ID:** com.helloreverb.reverb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=602336025">602336025</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inform-personalized-news-discovery/id602336025?mt=8&uo=4">https://itunes.apple.com/us/app/inform-personalized-news-discovery/id602336025?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Reverb Technologies, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/reverb-technologies-inc./id417229073?uo=4>© Reverb Technologies, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/20/63/bd/2063bde5-f07a-079c-f3d2-ab333b65c053/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10083430/c8e39c14-62fe-11e5-92d1-637a63dd7862.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10083430/c8e39c14-62fe-11e5-92d1-637a63dd7862.png)
https://cloud.githubusercontent.com/assets/2068130/10083430/c8e39c14-62fe-11e5-92d1-637a63dd7862.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10083444/d8344a7e-62fe-11e5-97c4-d62d7d8837b2.png
