### ISSUE TITLE
OwnersBox: Score and Player Tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6418]
**App Name:** OwnersBox: Score and Player Tracker
**Bundle ID:** com.ownersbox.spt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935411567">935411567</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ownersbox-score-player-tracker/id935411567?mt=8&uo=4">https://itunes.apple.com/us/app/ownersbox-score-player-tracker/id935411567?mt=8&uo=4</a>
**App Version:** 2.2.5
**Seller:** OwnersBox 2.0 Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ownersbox/id935411566?uo=4>© Ownersbox</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/0a/a6/8e/0aa68ec6-eb04-4b54-2df0-65f08ef83299/mzl.kqlchrjh.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10084260/c274c0b6-6302-11e5-849c-f3d28b4a0f6f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10084260/c274c0b6-6302-11e5-849c-f3d28b4a0f6f.png)
https://cloud.githubusercontent.com/assets/2068130/10084260/c274c0b6-6302-11e5-849c-f3d28b4a0f6f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10084274/d31c0816-6302-11e5-886d-20e49e3ad09a.png
