### ISSUE TITLE
ezPDF Reader: PDF Reader, Annotator & Form Filler

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6420]
**App Name:** ezPDF Reader: PDF Reader, Annotator & Form Filler
**Bundle ID:** kr.co.unidocs.ezPDFReader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=396101792">396101792</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ezpdf-reader-pdf-reader-annotator/id396101792?mt=8&uo=4">https://itunes.apple.com/us/app/ezpdf-reader-pdf-reader-annotator/id396101792?mt=8&uo=4</a>
**App Version:** 2.414
**Seller:** Unidocs Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/unidocs-inc./id396101795?uo=4>© Unidocs Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/35/60/f7/3560f749-cb4d-b447-777b-41b5b81d389f/mzl.mbinblmz.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11328984/4738eb08-915a-11e5-89fa-5524225abea0.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11328984/4738eb08-915a-11e5-89fa-5524225abea0.png)
https://cloud.githubusercontent.com/assets/3090247/11328984/4738eb08-915a-11e5-89fa-5524225abea0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11328985/4773082e-915a-11e5-8b89-1b70cb636a59.png
