### ISSUE TITLE
TSN GO

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6421]
**App Name:** TSN GO
**Bundle ID:** ca.tsn.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347679488">347679488</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tsn-go/id347679488?mt=8&uo=4">https://itunes.apple.com/us/app/tsn-go/id347679488?mt=8&uo=4</a>
**App Version:** 2.32.4
**Seller:** Bell Media Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bell-media-inc/id328082347?uo=4">© Bell Media Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple115/v4/56/8c/13/568c1393-ed61-9468-d224-c4817baa12f2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41167817-54ce9c2e-6b44-11e8-8344-596d6bd36611.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10087135/7ce3947c-6312-11e5-8ec8-4c3e01d1562f.png)
https://cloud.githubusercontent.com/assets/2068130/10087135/7ce3947c-6312-11e5-8ec8-4c3e01d1562f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10087144/8b4ac38c-6312-11e5-92df-3ed3334a59ad.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** TSN GO
**Bundle ID:** ca.tsn.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347679488">347679488</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tsn-go/id347679488?mt=8&uo=4">https://itunes.apple.com/us/app/tsn-go/id347679488?mt=8&uo=4</a>
**App Version:** 2.32.4
**Seller:** Bell Media Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bell-media-inc/id328082347?uo=4">© Bell Media Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple115/v4/56/8c/13/568c1393-ed61-9468-d224-c4817baa12f2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41167817-54ce9c2e-6b44-11e8-8344-596d6bd36611.png)
https://user-images.githubusercontent.com/2068130/41167817-54ce9c2e-6b44-11e8-8344-596d6bd36611.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41167843-64e8b626-6b44-11e8-9cc4-a54ab554cd80.png
