### ISSUE TITLE
Weather On - Push Notification

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6422]
**App Name:** Weather On - Push Notification
**Bundle ID:** com.fantaon.weatheron
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=554438153">554438153</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-on-push-notification/id554438153?mt=8&uo=4">https://itunes.apple.com/us/app/weather-on-push-notification/id554438153?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** fantaon Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fantaon/id554438156?uo=4>© fantaon</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/71/72/d8/7172d867-2336-ed1b-606f-2c13c007afaa/mzl.iyhvhssa.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10123199/e1dcaa4e-6533-11e5-9388-27afafc88cac.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10121876/3d7b003e-64c7-11e5-89b7-a8379127caef.png)
https://cloud.githubusercontent.com/assets/3090247/10121876/3d7b003e-64c7-11e5-89b7-a8379127caef.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10121875/3d79e528-64c7-11e5-8054-6bedb35831f7.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10123199/e1dcaa4e-6533-11e5-9388-27afafc88cac.png)
https://cloud.githubusercontent.com/assets/2068130/10123199/e1dcaa4e-6533-11e5-9388-27afafc88cac.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10123204/f07635c0-6533-11e5-8a15-de6749fcd595.png
