### ISSUE TITLE
In-flight Entertainment by Virgin Australia

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6423]
**App Name:** In-flight Entertainment by Virgin Australia
**Bundle ID:** com.lhsystems.ife.boardconnect.dj.iphone.daios.ped
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=563516237">563516237</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/in-flight-entertainment-by/id563516237?mt=8&uo=4">https://itunes.apple.com/us/app/in-flight-entertainment-by/id563516237?mt=8&uo=4</a>
**App Version:** 3.4.4.1
**Seller:** Lufthansa Systems Americas Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lufthansa-systems/id413078252?uo=4>© Lufthansa Systems</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/4d/2d/38/4d2d38b8-0224-a76f-c69f-59c6ebcc4c4c/mzl.nhbmgdyp.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10064814/709c369a-6242-11e5-97b2-564f71b05065.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10064814/709c369a-6242-11e5-97b2-564f71b05065.png)
https://cloud.githubusercontent.com/assets/3090247/10064814/709c369a-6242-11e5-97b2-564f71b05065.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10064813/709c3302-6242-11e5-8130-2cf1c041ab74.png
