### ISSUE TITLE
BlockQuest

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6425]
**App Name:** BlockQuest
**Bundle ID:** com.wlkzinc.blockQuest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1020587463">1020587463</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blockquest/id1020587463?mt=8&uo=4">https://itunes.apple.com/us/app/blockquest/id1020587463?mt=8&uo=4</a>
**App Version:** 1.22
**Seller:** Wonderland Kazakiri inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wonderland-kazakiri-inc./id962250634?uo=4>© Wonderland Kazakiri inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/de/35/b3/de35b36a-7b7e-8a6c-1816-81f7525b325d/mzl.xicfxlae.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10119588/66b6da9a-649a-11e5-913d-8f3652f339f3.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10101917/e60f9642-639b-11e5-8b32-20d8520b7401.png)
https://cloud.githubusercontent.com/assets/10730122/10101917/e60f9642-639b-11e5-8b32-20d8520b7401.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10101915/e2d3cf70-639b-11e5-883f-f07c6d4d44c4.png

**Comment by dreamnet** [comment]
Hmmm... maybe inverted?

**Comment by Trubbel** [comment]
@dreamnet It's up to you boss! :smiley:

**Comment by dreamnet** [comment]
Ah, always me... OK - then I take mine. :wink:
