### ISSUE TITLE
TextGrabber + Translator: OCR recognize, translate and save editable text from any printed material

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#643]
**App Name:** TextGrabber + Translator: OCR recognize, translate and save editable text from any printed material
**Bundle ID:** com.abbyy.textgrabber
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438475005">438475005</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/textgrabber-+-translator-ocr/id438475005?mt=8&uo=4">https://itunes.apple.com/us/app/textgrabber-+-translator-ocr/id438475005?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** ABBYY USA Software House Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/abbyy/id347345477?uo=4>© ABBYY</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/43/34/13/4334139a-d415-39de-abba-e58b4b0ffcda/mzl.udjocmqh.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10899875/6f26a1c2-81d9-11e5-9822-920e2264e8fb.png)

**Comment by l8er4now** [comment]
Need a quick update.

**App Name:** TextGrabber + Translator: OCR recognize, translate and save editable text from any printed material
**Bundle ID:** com.abbyy.textgrabber
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438475005">438475005</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/textgrabber-+-translator-ocr/id438475005?mt=8&uo=4">https://itunes.apple.com/us/app/textgrabber-+-translator-ocr/id438475005?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** ABBYY USA Software House Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/abbyy/id347345477?uo=4>© ABBYY</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/43/34/13/4334139a-d415-39de-abba-e58b4b0ffcda/mzl.udjocmqh.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10899875/6f26a1c2-81d9-11e5-9822-920e2264e8fb.png)
https://cloud.githubusercontent.com/assets/10730122/10899875/6f26a1c2-81d9-11e5-9822-920e2264e8fb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10899872/6cf41c54-81d9-11e5-886b-c29367f34b4c.png
