### ISSUE TITLE
eBillett

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6435]
**App Name:** eBillett
**Bundle ID:** com.dx.ebillett
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=513025391">513025391</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ebillett/id513025391?uo=4">https://apps.apple.com/us/app/ebillett/id513025391?uo=4</a>
**App Version:** 3.3.7
**Seller:** Dialog eXe AS
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dialog-exe-as/id454500347?uo=4">© Dialog eXe AS</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/04/de/db/04dedbed-33d3-b959-2268-be2d7e139fda/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com dx ebillett-scan-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60386549-85ad2680-9a96-11e9-98d3-d8fbdcfca753.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10103436/3db8cdd4-63a4-11e5-8882-989ba32d5a83.png)
https://cloud.githubusercontent.com/assets/10730122/10103436/3db8cdd4-63a4-11e5-8882-989ba32d5a83.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10103431/3a3122e2-63a4-11e5-88c4-28b76128488b.png

**Comment by dreamnet** [comment]
Suggestion for this one:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10123462/654961be-653a-11e5-99fa-95861e72e63a.png)
https://cloud.githubusercontent.com/assets/2068130/10123462/654961be-653a-11e5-99fa-95861e72e63a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10123466/75a4178e-653a-11e5-82e9-57f4b5494eef.png

**Comment by Trubbel** [comment]
@dreamnet Sure, no problem! :smiley:

**Comment by dreamnet** [comment]
![com dx ebillett-scan-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60386549-85ad2680-9a96-11e9-98d3-d8fbdcfca753.png)
https://user-images.githubusercontent.com/2068130/60386549-85ad2680-9a96-11e9-98d3-d8fbdcfca753.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60386552-9493d900-9a96-11e9-8d91-e85bb45d4c40.png
