### ISSUE TITLE
eBillett Scan

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6436]
**App Name:** eBillett Scan
**Bundle ID:** com.dx.ebillett-scan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498935090">498935090</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ebillett-scan/id498935090?mt=8&uo=4">https://itunes.apple.com/us/app/ebillett-scan/id498935090?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Dialog eXe AS
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dialog-exe-as/id454500347?uo=4>© Dialog eXe AS</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/24/d2/29/24d229dd-4125-f929-427d-3e1502710882/mzl.ngvxeljg.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10103436/3db8cdd4-63a4-11e5-8882-989ba32d5a83.png)

**Comment by Trubbel** [comment]
Same icon as #6435,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10103436/3db8cdd4-63a4-11e5-8882-989ba32d5a83.png)
https://cloud.githubusercontent.com/assets/10730122/10103436/3db8cdd4-63a4-11e5-8882-989ba32d5a83.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10103431/3a3122e2-63a4-11e5-88c4-28b76128488b.png

**Comment by dreamnet** [comment]
#6435 and this are different apps I think.

**Comment by ivanov007** [comment]
indeed, but both have the same Icon and are made by the same developer, so should one of them be inverted to make a noticeable difference?

**Comment by dreamnet** [comment]
@ivanov007 Yes, I think there should be some difference between the two icons.
