### ISSUE TITLE
Matcha - Writing App & Text Processor

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6457]
**App Name:** Matcha - Writing App & Text Processor
**Bundle ID:** com.cocoten.ios.Wisdom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=576774808">576774808</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/matcha-writing-app-text-processor/id576774808?mt=8&uo=4">https://itunes.apple.com/us/app/matcha-writing-app-text-processor/id576774808?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** InterAre, PT
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/interare-pt/id533476636?uo=4>© InterAre, PT</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/9b/cb/fa/9bcbfae0-3a46-6ac0-2505-279a422aed26/pr_source.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10119527/06d4b7ec-6499-11e5-9006-a19c43e9767e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10119527/06d4b7ec-6499-11e5-9006-a19c43e9767e.png)
https://cloud.githubusercontent.com/assets/2068130/10119527/06d4b7ec-6499-11e5-9006-a19c43e9767e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10119531/150df6e8-6499-11e5-80dc-7275b0b80041.png
