### ISSUE TITLE
iCalendar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6458]
**App Name:** iCalendar
**Bundle ID:** com.infinitetiers.calendarapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492076105">492076105</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/icalendar/id492076105?mt=8&uo=4">https://itunes.apple.com/us/app/icalendar/id492076105?mt=8&uo=4</a>
**App Version:** 4.4.2
**Seller:** Symfonies, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/symfonies-inc./id866948270?uo=4>© Symfonies, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/be/5f/89/be5f89c8-8bd0-466b-659a-f45eefad93b4/mzl.wzlsootz.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10119660/4dd1920c-649c-11e5-8bfb-4aae9423425d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10119660/4dd1920c-649c-11e5-8bfb-4aae9423425d.png)
https://cloud.githubusercontent.com/assets/2068130/10119660/4dd1920c-649c-11e5-8bfb-4aae9423425d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10119665/5ee3eb6c-649c-11e5-8499-4d59f62827df.png
