### ISSUE TITLE
FastCall - VIPs contacts in a swipe

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6462]
**App Name:** FastCall - VIPs contacts in a swipe
**Bundle ID:** org.iphonesmartapps.fastcall
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935279227">935279227</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fastcall-vips-contacts-in/id935279227?mt=8&uo=4">https://itunes.apple.com/us/app/fastcall-vips-contacts-in/id935279227?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Elisa Valeria Distefano
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/elisa-valeria-distefano/id326512931?uo=4>© Elisa Valeria Distefano</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/bc/1b/f4/bc1bf4af-2910-873e-996d-633c0ac6fba3/mzl.dusxddyo.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10123086/8a7d65f4-652e-11e5-9e6b-e84d92dc5545.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10123086/8a7d65f4-652e-11e5-9e6b-e84d92dc5545.png)
https://cloud.githubusercontent.com/assets/2068130/10123086/8a7d65f4-652e-11e5-9e6b-e84d92dc5545.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10123089/9c908320-652e-11e5-8c92-d40df47fd8a1.png

**Comment by ivanov007** [comment]
oops I think I forgot to post the fulfillment
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10154707/5fc95086-6630-11e5-8f66-68feb4d1a504.png)
https://cloud.githubusercontent.com/assets/3090247/10154707/5fc95086-6630-11e5-8f66-68feb4d1a504.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10154704/5fbb1f02-6630-11e5-8326-2ec52d55085d.png)
https://cloud.githubusercontent.com/assets/3090247/10154704/5fbb1f02-6630-11e5-8326-2ec52d55085d.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/10154706/5fc91634-6630-11e5-9b42-8b742cd35ab9.png
https://cloud.githubusercontent.com/assets/3090247/10154705/5fc7f876-6630-11e5-83dd-0582d4c5bb67.png

**Comment by dreamnet** [comment]
@ivanov007 Already did it... :wink: :beer:
