### ISSUE TITLE
GIPHY: The GIF Search Engine

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6464]
**App Name:** GIPHY: The GIF Search Engine
**Bundle ID:** com.giphy.giphyformessenger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=974748812">974748812</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/giphy-the-gif-search-engine/id974748812?uo=4">https://apps.apple.com/us/app/giphy-the-gif-search-engine/id974748812?uo=4</a>
**App Version:** 3.6.2
**Seller:** Giphy, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/giphy-inc/id974748811?uo=4">© Giphy, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/89/b2/ee/89b2ee21-921a-1105-e0f7-2805889230c1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60640747-ea66d900-9e28-11e9-9086-52cac6dfc42c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10122202/f76ca9c6-64d5-11e5-9efe-aea01694de67.png)
https://cloud.githubusercontent.com/assets/3090247/10122202/f76ca9c6-64d5-11e5-9efe-aea01694de67.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10122204/f7953bfc-64d5-11e5-93e6-c35802ff9efc.png)
https://cloud.githubusercontent.com/assets/3090247/10122204/f7953bfc-64d5-11e5-93e6-c35802ff9efc.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/10122203/f7953f08-64d5-11e5-981f-39fee14afdb3.png
https://cloud.githubusercontent.com/assets/3090247/10122205/f7972d4a-64d5-11e5-9927-dbd970cee829.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60640747-ea66d900-9e28-11e9-9086-52cac6dfc42c.png)
https://user-images.githubusercontent.com/2068130/60640747-ea66d900-9e28-11e9-9086-52cac6dfc42c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60640757-f94d8b80-9e28-11e9-8697-d55ca4d78882.png
