### ISSUE TITLE
Sleeperbot Fantasy Football Club

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6467]
**App Name:** Sleeperbot Fantasy Football Club
**Bundle ID:** com.blitzstudios.sleeperbot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=987367543">987367543</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sleeperbot-fantasy-football/id987367543?mt=8&uo=4">https://itunes.apple.com/us/app/sleeperbot-fantasy-football/id987367543?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Blitz Studios, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/blitz-studios/id905863487?uo=4>© Blitz Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/21/66/53/216653ca-89eb-6379-3596-1c2339dcf41e/mzl.zopqwzce.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10123133/7ded58f6-6530-11e5-80cf-ccae52817e1e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10123133/7ded58f6-6530-11e5-80cf-ccae52817e1e.png)
https://cloud.githubusercontent.com/assets/2068130/10123133/7ded58f6-6530-11e5-80cf-ccae52817e1e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10123134/8e231e0e-6530-11e5-9bbe-65c1fb18e661.png
