### ISSUE TITLE
Track Kit - GPS Tracker with offline maps

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6469]
**App Name:** Track Kit - GPS Tracker with offline maps
**Bundle ID:** com.lifewaresolutions.TrackKit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=871209106">871209106</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/track-kit-gps-tracker-offline/id871209106?mt=8&uo=4">https://itunes.apple.com/us/app/track-kit-gps-tracker-offline/id871209106?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Natalia Gavrylova
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/natalia-gavrylova/id598938539?uo=4>© Natalia Gavrylova</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple2/v4/09/0b/da/090bda33-ee17-e5f3-0b49-58b0b0ed4b61/mzl.ncvhbxbq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10148630/d9d35d00-6634-11e5-8a66-22246f083317.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10148630/d9d35d00-6634-11e5-8a66-22246f083317.png)
https://cloud.githubusercontent.com/assets/10730122/10148630/d9d35d00-6634-11e5-8a66-22246f083317.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10148624/d6506006-6634-11e5-8dce-a6d54ad2a79b.png

**Comment by Trubbel** [comment]
Thicker circle,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10148650/f8c6cd6e-6634-11e5-8815-bdfd11b428da.png)
https://cloud.githubusercontent.com/assets/10730122/10148650/f8c6cd6e-6634-11e5-8815-bdfd11b428da.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10148648/f4a0ef30-6634-11e5-9755-6b238b505454.png

**Comment by dreamnet** [comment]
@Trubbel The first one is OK, in the original is also a very thin circle.
