### ISSUE TITLE
Millonario Quiz Español

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6490]
**App Name:** Millonario Quiz Español
**Bundle ID:** com.creactive.Millonario-Gratis
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=714981446">714981446</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/millonario-quiz-espanol/id714981446?mt=8&uo=4">https://itunes.apple.com/us/app/millonario-quiz-espanol/id714981446?mt=8&uo=4</a>
**App Version:** 3.6
**Seller:** Marco Batista
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/marco-batista/id577067366?uo=4>© Marco Batista</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/dc/03/8d/dc038d06-5639-a867-59eb-9b1f1f3fa70d/mzl.dsjzyzlc.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10269345/61489e4e-6a9a-11e5-8f50-f62216101ea8.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10269345/61489e4e-6a9a-11e5-8f50-f62216101ea8.png)
https://cloud.githubusercontent.com/assets/3090247/10269345/61489e4e-6a9a-11e5-8f50-f62216101ea8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10269344/61421182-6a9a-11e5-906a-ce72f3838238.png

**Comment by dreamnet** [comment]
@ivanov007 Great! :+1:
