### ISSUE TITLE
ZARA

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6491]
**App Name:** ZARA
**Bundle ID:** com.inditex.zara.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547951480">547951480</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zara/id547951480?mt=8&uo=4">https://itunes.apple.com/us/app/zara/id547951480?mt=8&uo=4</a>
**App Version:** 5.9.4
**Seller:** Industria de Diseno Textil, S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inditex/id341323285?mt=8&uo=4">© INDITEX</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/55/e3/25/55e32552-b634-4412-e1d0-96e770ef1a86/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54822042-448dc500-4ca4-11e9-991e-21b207d6f599.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231041/d06eefd8-6880-11e5-8698-4a11fe05bf5c.png)
https://cloud.githubusercontent.com/assets/2068130/10231041/d06eefd8-6880-11e5-8698-4a11fe05bf5c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10231054/e56c7f72-6880-11e5-838a-3fd5d918d74d.png

**Comment by alpcinar** [comment]
Update for the new logo?

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54822042-448dc500-4ca4-11e9-991e-21b207d6f599.png)
(https://user-images.githubusercontent.com/20930745/54822042-448dc500-4ca4-11e9-991e-21b207d6f599.png

Source:
https://user-images.githubusercontent.com/20930745/54822043-45265b80-4ca4-11e9-916a-e4f9c6563530.png
