### ISSUE TITLE
H&M App

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6492]
**App Name:** H&M App
**Bundle ID:** com.hm.goe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834465911">834465911</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/h-m-app/id834465911?mt=8&uo=4">https://itunes.apple.com/fr/app/h-m-app/id834465911?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** H & M Hennes & Mauritz AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/fr/developer/h-m/id380487412?uo=4>© H&M</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/b5/d9/61/b5d961d8-af86-15eb-9867-b069177167cb/mzl.ftclrcfu.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231170/a038ce0a-6881-11e5-9751-4f9fc81e5ae6.png)

**Comment by dreamnet** [comment]
Refers to #1331.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231170/a038ce0a-6881-11e5-9751-4f9fc81e5ae6.png)
https://cloud.githubusercontent.com/assets/2068130/10231170/a038ce0a-6881-11e5-9751-4f9fc81e5ae6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10231187/b118ad12-6881-11e5-8c81-32f270ac9458.png
