### ISSUE TITLE
Mi Orange

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6493]
**App Name:** Mi Orange
**Bundle ID:** com.orange.sp.miorange
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=379866108">379866108</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/mi-orange/id379866108?mt=8&uo=4">https://itunes.apple.com/es/app/mi-orange/id379866108?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** France Telecom Espana S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/orange-spain/id370553435?uo=4>© Orange Spain</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple2/v4/35/c6/e4/35c6e41d-f9c1-ecb5-a4a6-32ca351c0f59/mzl.jdsworrm.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231559/c616fa96-6883-11e5-8f17-2594ac869fe2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231559/c616fa96-6883-11e5-8f17-2594ac869fe2.png)
https://cloud.githubusercontent.com/assets/2068130/10231559/c616fa96-6883-11e5-8f17-2594ac869fe2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10231573/d6858ac8-6883-11e5-9f46-b9cb15772db9.png
