### ISSUE TITLE
MOVISTAR+

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6494]
**App Name:** MOVISTAR+
**Bundle ID:** com.prisatv.yomvi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540674767">540674767</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/movistar+/id540674767?mt=8&uo=4">https://itunes.apple.com/es/app/movistar+/id540674767?mt=8&uo=4</a>
**App Version:** 3.8.5
**Seller:** DTS DISTRIBUIDORA DE TELEVISION DIGITAL S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/dts-distribuidora-television/id540675310?uo=4>© DTS DISTRIBUIDORA DE TELEVISION DIGITAL S.A.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/8d/68/32/8d6832ec-f776-2bee-7954-44b891fcf7a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18538233/0878a006-7b0c-11e6-8a40-6386d6a15efe.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10264662/94132fdc-69d8-11e5-83f6-5d93055f0346.png)
https://cloud.githubusercontent.com/assets/3090247/10264662/94132fdc-69d8-11e5-83f6-5d93055f0346.png
--- --- 
Source:
https://cloud.githubusercontent.com/assets/3090247/10264663/9434ee38-69d8-11e5-8dfb-24fe0a9af6ca.png

**Comment by grkka** [comment]
Can you upgrade? Thank you.

**App Name:** MOVISTAR+
**Bundle ID:** com.prisatv.yomvi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540674767">540674767</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/movistar+/id540674767?mt=8&uo=4">https://itunes.apple.com/es/app/movistar+/id540674767?mt=8&uo=4</a>
**App Version:** 3.8.5
**Seller:** DTS DISTRIBUIDORA DE TELEVISION DIGITAL S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/dts-distribuidora-television/id540675310?uo=4>© DTS DISTRIBUIDORA DE TELEVISION DIGITAL S.A.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/8d/68/32/8d6832ec-f776-2bee-7954-44b891fcf7a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18529743/b4284070-7ace-11e6-9410-5f50c2962cea.png)
https://cloud.githubusercontent.com/assets/20930745/18529743/b4284070-7ace-11e6-9410-5f50c2962cea.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18529768/c7b1d35e-7ace-11e6-98df-a8ed4f847d86.png

**Comment by dreamnet** [comment]
Hmmmm...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18538233/0878a006-7b0c-11e6-8a40-6386d6a15efe.png)
https://cloud.githubusercontent.com/assets/2068130/18538233/0878a006-7b0c-11e6-8a40-6386d6a15efe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18538238/1784bbd4-7b0c-11e6-8b81-d090a0f43613.png
