### ISSUE TITLE
Heraldo de Aragón

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6495]
**App Name:** Heraldo de Aragón
**Bundle ID:** es.heraldo.noticiasiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336756495">336756495</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/heraldo-de-aragon/id336756495?mt=8&uo=4">https://itunes.apple.com/us/app/heraldo-de-aragon/id336756495?mt=8&uo=4</a>
**App Version:** 3.1.2
**Seller:** Heraldo de Aragon
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/heraldo-de-aragon/id336756498?uo=4>© Heraldo de Aragón</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/79/a3/8c/79a38ce9-4faa-c0fe-0298-791ef6aeef69/mzl.nrtbwkkd.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231380/ae1eb22c-6882-11e5-86a6-c2676c2acbaa.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231380/ae1eb22c-6882-11e5-86a6-c2676c2acbaa.png)
https://cloud.githubusercontent.com/assets/2068130/10231380/ae1eb22c-6882-11e5-86a6-c2676c2acbaa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10231388/bd0599a4-6882-11e5-9a35-5c35cfc1810f.png
