### ISSUE TITLE
Endesa Clientes

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6496]
**App Name:** Endesa Clientes
**Bundle ID:** es.awg.movilidadEOL.iPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=602095382">602095382</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/endesa-clientes/id602095382?mt=8&uo=4">https://itunes.apple.com/us/app/endesa-clientes/id602095382?mt=8&uo=4</a>
**App Version:** 2.11.1
**Seller:** ENDESA SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/endesa-sa/id602095385?uo=4>© Endesa SA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/15/77/6b/15776b0c-f821-c5a2-1370-f1a957389730/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874897/2da9813c-cdde-11e5-9690-5bfa3b2051db.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231911/c47b1bb6-6885-11e5-85e7-c5ba54bdbab6.png)
https://cloud.githubusercontent.com/assets/2068130/10231911/c47b1bb6-6885-11e5-85e7-c5ba54bdbab6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10231919/d32b1526-6885-11e5-86af-396c0a9beea9.png

**Comment by grkka** [comment]
**App Name:** Endesa Clientes
**Bundle ID:** es.awg.movilidadEOL.iPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=602095382">602095382</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/endesa-clientes/id602095382?mt=8&uo=4">https://itunes.apple.com/us/app/endesa-clientes/id602095382?mt=8&uo=4</a>
**App Version:** 2.11.1
**Seller:** ENDESA SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/endesa-sa/id602095385?uo=4>© Endesa SA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/15/77/6b/15776b0c-f821-c5a2-1370-f1a957389730/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by grkka** [comment]
Update, please. Thanks.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874897/2da9813c-cdde-11e5-9690-5bfa3b2051db.png)
https://cloud.githubusercontent.com/assets/2068130/12874897/2da9813c-cdde-11e5-9690-5bfa3b2051db.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12874902/3d874e9a-cdde-11e5-82fb-98a4da31672a.png
