### ISSUE TITLE
My112

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6497]
**App Name:** My112
**Bundle ID:** com.movilforum.my112
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=804779618">804779618</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/my112/id804779618?mt=8&uo=4">https://itunes.apple.com/es/app/my112/id804779618?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Movilforum Programa de Partners
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/movilforum-programa-partners/id453713837?uo=4>© Movilforum Programa de Partners</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/87/20/2c/87202c4b-ff8a-d401-3648-05c47f585c9c/mzl.ymqhjdgo.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231473/36af0498-6883-11e5-9c55-f9c0c3fc6f53.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10231473/36af0498-6883-11e5-9c55-f9c0c3fc6f53.png)
https://cloud.githubusercontent.com/assets/2068130/10231473/36af0498-6883-11e5-9c55-f9c0c3fc6f53.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10231478/45a49a76-6883-11e5-8e23-c9968824c73a.png
