### ISSUE TITLE
AmpMe

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6499]
**App Name:** AmpMe
**Bundle ID:** com.amp.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=986905979">986905979</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ampme/id986905979?mt=8&uo=4">https://itunes.apple.com/us/app/ampme/id986905979?mt=8&uo=4</a>
**App Version:** 7.0.0
**Seller:** Amp Me inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amp-me-inc/id986905978?uo=4">© Amp Me inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/54/01/1d/54011d3d-2dc8-0911-500b-71c547a05596/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38456009-f59f16f6-3a7f-11e8-9483-586485ad2c14.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10251963/cdf5ffd0-6934-11e5-86e7-761d57bd9181.png)
https://cloud.githubusercontent.com/assets/2068130/10251963/cdf5ffd0-6934-11e5-86e7-761d57bd9181.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10251973/d88d4566-6934-11e5-8d8c-4877e62101e9.png

**Comment by LaCh0uine** [comment]
@dreamnet thank you again u awesome :)

**Comment by dreamnet** [comment]
@LaCh0uine :+1:

**Comment by dreamnet** [comment]
Icon needs an update.
