### ISSUE TITLE
ProTube

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#65]
**App Name:** ProTube
 **Bundle ID:** de.j-gessner.ProTube
 **Version:** 1.12.1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/10730122/20821283/9fe69a98-b841-11e6-9aeb-10459d8da5c3.png" width="180" height="180" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/20820984/7e2605da-b83f-11e6-90d7-598e50dc1f28.png)

**Comment by Trubbel** [comment]
Same as #2816,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/20820984/7e2605da-b83f-11e6-90d7-598e50dc1f28.png)
https://cloud.githubusercontent.com/assets/10730122/20820984/7e2605da-b83f-11e6-90d7-598e50dc1f28.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/20820983/7e253876-b83f-11e6-905d-ab2ac8374b2b.png
