### ISSUE TITLE
Ascension: Chronicle of the Godslayer

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#6500]
**App Name:** Ascension: Chronicle of the Godslayer
**Bundle ID:** com.incineratorstudios.Ascension-iPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441838733">441838733</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ascension-chronicle-godslayer/id441838733?mt=8&uo=4">https://itunes.apple.com/us/app/ascension-chronicle-godslayer/id441838733?mt=8&uo=4</a>
**App Version:** 1.10.1
**Seller:** Incinerator Studios
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/playdek/id441838736?uo=4>© Playdek</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/d9/0a/85/d90a85e5-6904-9b65-ad18-4733efbc075e/mzl.hzanknzp.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10261742/58597406-69a6-11e5-9be6-67208a572aeb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10261742/58597406-69a6-11e5-9be6-67208a572aeb.png)
https://cloud.githubusercontent.com/assets/2068130/10261742/58597406-69a6-11e5-9be6-67208a572aeb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10261745/677b7a1a-69a6-11e5-903d-460550098793.png

**Comment by Trubbel** [comment]
@dreamnet Not bad! :+1:

**Comment by dreamnet** [comment]
@Trubbel Thanks, mostly raytracing. :wink:
