### ISSUE TITLE
DeviantArt

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#6501]
**App Name:** DeviantArt
**Bundle ID:** com.deviantart.DeviantArt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=925219396">925219396</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deviantart/id925219396?mt=8&uo=4">https://itunes.apple.com/us/app/deviantart/id925219396?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** deviantART
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/deviantart/id880435124?uo=4>© DeviantArt</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/eb/c8/61/ebc861a3-adb8-5ab6-53e8-6e9d1357e829/mzl.fygnkgnt.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10254520/966b8bba-6944-11e5-9dcc-99caa7f14c85.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10254520/966b8bba-6944-11e5-9dcc-99caa7f14c85.png)
https://cloud.githubusercontent.com/assets/2068130/10254520/966b8bba-6944-11e5-9dcc-99caa7f14c85.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10254534/a6c8bbd6-6944-11e5-8eb7-3202576305c9.png
