### ISSUE TITLE
Settings app crash

### ISSUE THREAD

**Issue by awokenhypnon** [glasklart/hd#6502]
I don't know why but when i enable the glasklart with anemone, the settings app crash. It only happens with glasklart. Other themes are working fine. Is this glasklart issue?

Edit: when cloaky(tweak) and glasklart is enabled, settings app crash

**Comment by awokenhypnon** [comment]
If i enable glasklart with winterboard, it doesnt crash. Looks like anemone issue

**Comment by dreamnet** [comment]
@awokenhypnon Yes, I don't think this crash can be caused by Glasklart.
