### ISSUE TITLE
The Weather Channel and weather.com - local forecasts, radar maps, and storm tracking

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6505]
**App Name:** The Weather Channel and weather.com - local forecasts, radar maps, and storm tracking
**Bundle ID:** com.weather.TWC
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=295646461">295646461</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-channel-weather.com/id295646461?mt=8&uo=4">https://itunes.apple.com/us/app/weather-channel-weather.com/id295646461?mt=8&uo=4</a>
**App Version:** 6.12
**Seller:** The Weather Channel
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/weather-channel-interactive/id295646464?uo=4>© The Weather Channel Interactive</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/94/d9/2c/94d92cf6-efdd-c951-45a1-3cdd295f9f15/mzl.bwuwtowe.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10268802/53d80892-6ac4-11e5-9d7a-15aa12ef6a03.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10268802/53d80892-6ac4-11e5-9d7a-15aa12ef6a03.png)
https://cloud.githubusercontent.com/assets/2068130/10268802/53d80892-6ac4-11e5-9d7a-15aa12ef6a03.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10268805/6174dee4-6ac4-11e5-958c-c55863a7dcac.png
