### ISSUE TITLE
PewDiePie: Legend of the Brofist

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6513]
**App Name:** PewDiePie: Legend of the Brofist
**Bundle ID:** com.outerminds.pewdiepie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1028623510">1028623510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pewdiepie-legend-brofist/id1028623510?mt=8&uo=4">https://itunes.apple.com/us/app/pewdiepie-legend-brofist/id1028623510?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Outerminds Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/outerminds-inc./id921017187?uo=4>© Outerminds Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/e1/c2/15/e1c2151e-894f-abc3-e6d7-14b45e575484/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563750/2054d684-7597-11e5-9fba-e1226aa2f22f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10380110/405b0dea-6e12-11e5-996d-e84c800d5072.png)
https://cloud.githubusercontent.com/assets/2068130/10380110/405b0dea-6e12-11e5-996d-e84c800d5072.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10380122/4f7febec-6e12-11e5-86a9-6bac66fdae81.png

**Comment by dreamnet** [comment]
A bit overworked:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563750/2054d684-7597-11e5-9fba-e1226aa2f22f.png)
https://cloud.githubusercontent.com/assets/2068130/10563750/2054d684-7597-11e5-9fba-e1226aa2f22f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563755/31356c52-7597-11e5-8efa-dab413a1115b.png
I think it's good now.
