### ISSUE TITLE
Google Keep - Your thoughts, wherever you are

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6514]
**App Name:** Google Keep - Your thoughts, wherever you are
**Bundle ID:** com.google.Keep
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1029207872">1029207872</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-keep-your-thoughts/id1029207872?mt=8&uo=4">https://itunes.apple.com/us/app/google-keep-your-thoughts/id1029207872?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/97/6c/10/976c1024-b576-ea2b-c6da-7ee35e774bcb/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10358187/41b29f0a-6d8b-11e5-8b9a-01dfa9ac035f.png)

**Comment by alpcinar** [comment]
Also, as you know, Google updated most of the app logos: https://itunes.apple.com/tr/developer/google-inc./id281956209

**Comment by dreamnet** [comment]
@alpcinar THX for the link, I will check it.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10358187/41b29f0a-6d8b-11e5-8b9a-01dfa9ac035f.png)
https://cloud.githubusercontent.com/assets/2068130/10358187/41b29f0a-6d8b-11e5-8b9a-01dfa9ac035f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10358195/4fdc8f6e-6d8b-11e5-8ce2-d0f7c6a1774f.png
