### ISSUE TITLE
VHS Camcorder

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6515]
**App Name:** VHS Camcorder
**Bundle ID:** com.rarevision.vhs-camcorder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=679454835">679454835</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vhs-camcorder/id679454835?mt=8&uo=4">https://itunes.apple.com/us/app/vhs-camcorder/id679454835?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Rarevision LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rarevision/id464591028?uo=4>© Rarevision</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/df/d7/61/dfd761b7-b690-dfb1-4364-bed8727c5399/mzl.mbzheffd.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12078503/f9c59db8-b214-11e5-85f4-989b7f88b286.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12078503/f9c59db8-b214-11e5-85f4-989b7f88b286.png)
https://cloud.githubusercontent.com/assets/2068130/12078503/f9c59db8-b214-11e5-85f4-989b7f88b286.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12078504/077ead32-b215-11e5-8f18-1f7159798624.png
