### ISSUE TITLE
SLMMSK

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6516]
**App Name:** SLMMSK
**Bundle ID:** com.glitche.ios.slmmsk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=906883816">906883816</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slmmsk/id906883816?mt=8&uo=4">https://itunes.apple.com/us/app/slmmsk/id906883816?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Rambler Internet Holdings LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rambler-internet-holdings/id395455934?uo=4>© Rambler Internet Holdings LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/5d/d6/e1/5dd6e14c-5899-f19b-8d73-a1647bde1c02/mzl.fyjrzeap.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270519/b9bef668-6af4-11e5-817b-fcc22fdcca68.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270519/b9bef668-6af4-11e5-817b-fcc22fdcca68.png)
https://cloud.githubusercontent.com/assets/2068130/10270519/b9bef668-6af4-11e5-817b-fcc22fdcca68.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10270520/c896a078-6af4-11e5-9a3d-22f2f5242b20.png
