### ISSUE TITLE
Glitché

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6517]
**App Name:** Glitché
**Bundle ID:** com.glitche.ios.glitcheapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=634467171">634467171</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glitche/id634467171?mt=8&uo=4">https://itunes.apple.com/us/app/glitche/id634467171?mt=8&uo=4</a>
**App Version:** 1.98.5
**Seller:** Glitche Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/glitche-ltd/id906380865?uo=4>© Glitché Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/02/05/77/020577ce-d8d6-bd66-1627-d18a0eede2c3/mzl.odenfcuq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10292118/bf7cd16a-6bad-11e5-9ac0-51752e28f801.png)

**Comment by dreamnet** [comment]
Well, that's a strange icon... best I can do:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10292118/bf7cd16a-6bad-11e5-9ac0-51752e28f801.png)
https://cloud.githubusercontent.com/assets/2068130/10292118/bf7cd16a-6bad-11e5-9ac0-51752e28f801.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10292128/cf319a32-6bad-11e5-858f-27ff7d2619e8.png
@alpcinar What do you think?

**Comment by alpcinar** [comment]
@dreamnet It's perfect!
