### ISSUE TITLE
PHHHOTO - Moving Pictures

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6518]
**App Name:** PHHHOTO - Moving Pictures
**Bundle ID:** com.hyperhyper.phhhoto-iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=871169596">871169596</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/phhhoto-moving-pictures/id871169596?mt=8&uo=4">https://itunes.apple.com/us/app/phhhoto-moving-pictures/id871169596?mt=8&uo=4</a>
**App Version:** 1.5.4
**Seller:** HYPERHYPER, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hyperhyper/id593309120?uo=4>© HYPERHYPER</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/61/e4/44/61e444e1-f550-5445-da6c-d7b7b3cbfe23/mzl.akhkurqt.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10377918/4514b2e8-6e06-11e5-95f1-54e71186cf1a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10377918/4514b2e8-6e06-11e5-95f1-54e71186cf1a.png)
https://cloud.githubusercontent.com/assets/2068130/10377918/4514b2e8-6e06-11e5-95f1-54e71186cf1a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10377925/53bff8f2-6e06-11e5-9aaf-13b761940404.png
