### ISSUE TITLE
Ello

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6519]
**App Name:** Ello
**Bundle ID:** co.ello.Ello
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953614327">953614327</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ello/id953614327?mt=8&uo=4">https://itunes.apple.com/us/app/ello/id953614327?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** Ello PBC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ello/id952443867?uo=4>© Ello</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/60/c6/8c/60c68c8d-eb33-49ae-bb19-923a0c3666cc/mzl.nirmydhw.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270501/13659f10-6af4-11e5-993b-5ad7db84e88c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270501/13659f10-6af4-11e5-993b-5ad7db84e88c.png)
https://cloud.githubusercontent.com/assets/2068130/10270501/13659f10-6af4-11e5-993b-5ad7db84e88c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10270504/23c92c78-6af4-11e5-9445-d30a6bf11073.png
