### ISSUE TITLE
1967 – Vintage Filters

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6520]
**App Name:** 1967 – Vintage Filters
**Bundle ID:** com.apptimal.1967FilterApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916195181">916195181</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1967-vintage-filters/id916195181?mt=8&uo=4">https://itunes.apple.com/us/app/1967-vintage-filters/id916195181?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** RoadRocks. LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/roadrocks.-llc/id790652989?uo=4>© RoadRocks. LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/b1/77/c2/b177c2eb-49bd-0e99-b72d-e78da91d0128/mzl.daqyjtlj.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10273501/b6796078-6b31-11e5-9c48-1ed7d33d745f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10273501/b6796078-6b31-11e5-9c48-1ed7d33d745f.png)
https://cloud.githubusercontent.com/assets/2068130/10273501/b6796078-6b31-11e5-9c48-1ed7d33d745f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10273508/c9718318-6b31-11e5-898f-f88492254eb7.png
