### ISSUE TITLE
Litely

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6521]
**App Name:** Litely
**Bundle ID:** com.litely.litely
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=850707754">850707754</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/litely/id850707754?mt=8&uo=4">https://itunes.apple.com/us/app/litely/id850707754?mt=8&uo=4</a>
**App Version:** 1.1.5
**Seller:** LITELY LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/litely-llc/id850707757?uo=4>© Litely LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/1b/6a/eb/1b6aeb68-211b-79ba-a7da-9e83ecda2b59/mzl.qsftpnqa.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270549/5e72afd8-6af5-11e5-9feb-06cc52372d5a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270549/5e72afd8-6af5-11e5-9feb-06cc52372d5a.png)
https://cloud.githubusercontent.com/assets/2068130/10270549/5e72afd8-6af5-11e5-9feb-06cc52372d5a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10270555/71bbd8b2-6af5-11e5-8ff8-a7a98e7d7b47.png
