### ISSUE TITLE
Mail to Self • Send notes to your email in a single tap

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6522]
**App Name:** Mail to Self • Send notes to your email in a single tap
**Bundle ID:** com.extrathought.MailToSelfProd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935527163">935527163</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mail-to-self-send-notes-to/id935527163?mt=8&uo=4">https://itunes.apple.com/us/app/mail-to-self-send-notes-to/id935527163?mt=8&uo=4</a>
**App Version:** NCC-0514
**Seller:** Extra Thought Design Consultancy Pte. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/extra-thought/id568459649?uo=4>© Extra Thought</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/a5/ad/7b/a5ad7be5-f6da-9920-3d78-38cc8ba026e2/mzl.ufojfgxt.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10273685/2201676c-6b34-11e5-8a3e-925b258d1811.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10273685/2201676c-6b34-11e5-8a3e-925b258d1811.png)
https://cloud.githubusercontent.com/assets/2068130/10273685/2201676c-6b34-11e5-8a3e-925b258d1811.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10273687/31037d72-6b34-11e5-826a-863aa6e2cfeb.png
