### ISSUE TITLE
sahibinden.com mobil

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6523]
**App Name:** sahibinden.com mobil
**Bundle ID:** com.sahibinden.sahibinden
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418535251">418535251</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sahibinden.com-mobil/id418535251?mt=8&uo=4">https://itunes.apple.com/us/app/sahibinden.com-mobil/id418535251?mt=8&uo=4</a>
**App Version:** 2.5.0
**Seller:** Sahibinden Bilgi Teknolojileri Paz ve Tic A.S
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sahibinden.com/id416523251?uo=4>© sahibinden.com</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/08/65/eb/0865ebf4-1c3b-0bf4-20ac-e8045c1fad83/mzl.gawbmyjb.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270476/14513fb6-6af3-11e5-8abd-e0de4d63fcd5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270476/14513fb6-6af3-11e5-8abd-e0de4d63fcd5.png)
https://cloud.githubusercontent.com/assets/2068130/10270476/14513fb6-6af3-11e5-8abd-e0de4d63fcd5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10270480/29fc72ae-6af3-11e5-9229-f00bb4ce08a8.png
