### ISSUE TITLE
ininal Cüzdan

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6524]
**App Name:** ininal Cüzdan
**Bundle ID:** com.ngier.ininalwallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1029026167">1029026167</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ininal-cuzdan/id1029026167?mt=8&uo=4">https://itunes.apple.com/us/app/ininal-cuzdan/id1029026167?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** EKART ELEKTRONIK KART HIZMETLERI PAZARLAMA A S
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ininal/id929062473?uo=4>© ININAL</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/13/b3/5e/13b35e81-f9bd-74a7-5900-3dfd1d60203a/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270461/99d86b38-6af2-11e5-9945-5fcf769ddaa3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270461/99d86b38-6af2-11e5-9945-5fcf769ddaa3.png)
https://cloud.githubusercontent.com/assets/2068130/10270461/99d86b38-6af2-11e5-9945-5fcf769ddaa3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10270463/aaaffb92-6af2-11e5-93fe-e8cf8d8e4d4e.png
