### ISSUE TITLE
Yemeksepeti

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6525]
**App Name:** Yemeksepeti
**Bundle ID:** yemeksepeti.com.valensas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=373034841">373034841</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yemeksepeti/id373034841?mt=8&uo=4">https://itunes.apple.com/us/app/yemeksepeti/id373034841?mt=8&uo=4</a>
**App Version:** 4.5.2
**Seller:** Valensas Teknoloji
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/valensas/id299470166?uo=4>© Valensas</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/f9/d6/ba/f9d6ba67-b809-b83b-793c-e8ed46f9804d/mzl.bqytzrzm.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270425/3c8a9948-6af1-11e5-8d5b-0fa3b7a4b059.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270425/3c8a9948-6af1-11e5-8d5b-0fa3b7a4b059.png)
https://cloud.githubusercontent.com/assets/2068130/10270425/3c8a9948-6af1-11e5-8d5b-0fa3b7a4b059.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10270428/4cd37ba8-6af1-11e5-928c-3c80e39e0370.png
