### ISSUE TITLE
gnçtrkcll

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6526]
**App Name:** gnçtrkcll
**Bundle ID:** com.turkcell.gnctrkcll
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=894318685">894318685</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gnctrkcll/id894318685?mt=8&uo=4">https://itunes.apple.com/us/app/gnctrkcll/id894318685?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Turkcell Teknoloji
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/turkcell-iletisim-hizmetleri/id305642482?uo=4>© Turkcell Iletisim Hizmetleri A.S.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/96/71/69/9671697d-c86c-b204-d1e8-18e288244a95/mzl.rkxcatpy.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270490/86cb93d4-6af3-11e5-8d89-cf3006b80f20.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10270490/86cb93d4-6af3-11e5-8d89-cf3006b80f20.png)
https://cloud.githubusercontent.com/assets/2068130/10270490/86cb93d4-6af3-11e5-8d89-cf3006b80f20.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10270493/971b3582-6af3-11e5-93ea-ae5f7214a6d0.png
