### ISSUE TITLE
Google Wifi

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#6532]
**App Name:** Google Wifi
**Bundle ID:** com.google.OnHub
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=995373885">995373885</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/google-wifi/id995373885?uo=4">https://apps.apple.com/us/app/google-wifi/id995373885?uo=4</a>
**App Version:** 2.10.0
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/49/39/94/493994eb-d692-4afe-ff63-c020c2fbb430/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60538493-070cef00-9d0b-11e9-97da-24f21e4cb2de.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10271404/95daa5ba-6ad3-11e5-922c-3bc1dd332f0d.png)
https://cloud.githubusercontent.com/assets/3090247/10271404/95daa5ba-6ad3-11e5-922c-3bc1dd332f0d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10271403/95da7022-6ad3-11e5-9381-b7b496463d0f.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60538493-070cef00-9d0b-11e9-97da-24f21e4cb2de.png)
ttps://user-images.githubusercontent.com/20930745/60538493-070cef00-9d0b-11e9-97da-24f21e4cb2de.png

Source:
https://user-images.githubusercontent.com/20930745/60538495-083e1c00-9d0b-11e9-9d08-7f10e5dc1a11.png
