### ISSUE TITLE
Binaural - Pure Binaural Beats

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6533]
**App Name:** Binaural - Pure Binaural Beats
**Bundle ID:** com.giorgiocalderolla.binaural
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=838752522">838752522</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/binaural-pure-binaural-beats/id838752522?mt=8&uo=4">https://itunes.apple.com/us/app/binaural-pure-binaural-beats/id838752522?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Giorgio Calderolla
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/giorgio-calderolla/id379876189?uo=4>© Giorgio Calderolla</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/56/46/68/564668cd-bf57-971d-0f06-2ac57d9254b1/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10378078/249f4e32-6e07-11e5-9503-b57e29268e53.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10378078/249f4e32-6e07-11e5-9503-b57e29268e53.png)
https://cloud.githubusercontent.com/assets/2068130/10378078/249f4e32-6e07-11e5-9503-b57e29268e53.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10378092/34324e62-6e07-11e5-9910-f8c72a6db3e2.png
