### ISSUE TITLE
 Coffitivity

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6534]
**App Name:** Coffitivity
**Bundle ID:** com.coffitivity.coffitivityiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=669576390">669576390</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/coffitivity/id669576390?mt=8&uo=4">https://itunes.apple.com/us/app/coffitivity/id669576390?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Coffitivity, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/coffitivity-llc/id659901395?uo=4>© Coffitivity, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/7b/8d/d2/7b8dd245-0e24-f57e-e8b5-cc37db86f26a/mzl.qpvpkycx.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10300712/72b41b2a-6bfa-11e5-8f00-3e654229417f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10300712/72b41b2a-6bfa-11e5-8f00-3e654229417f.png)
https://cloud.githubusercontent.com/assets/2068130/10300712/72b41b2a-6bfa-11e5-8f00-3e654229417f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10300715/80e4c8e8-6bfa-11e5-8dc7-187ae00c14d6.png

![](https://cloud.githubusercontent.com/assets/2068130/10300712/72b41b2a-6bfa-11e5-8f00-3e654229417f.png---%20---Source:https://cloud.githubusercontent.com/assets/2068130/10300715/80e4c8e8-6bfa-11e5-8dc7-187ae00c14d6.png)
