### ISSUE TITLE
Shooty Skies - Endless Arcade Flyer

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6535]
**App Name:** Shooty Skies - Endless Arcade Flyer
**Bundle ID:** com.mightygamesgroup.shootyskies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=962993853">962993853</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shooty-skies-endless-arcade/id962993853?mt=8&uo=4">https://itunes.apple.com/us/app/shooty-skies-endless-arcade/id962993853?mt=8&uo=4</a>
**App Version:** 1.850
**Seller:** Mighty Games Group Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mighty-games/id807818274?uo=4>© Mighty Games</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/60/62/96/6062961c-922f-9f47-84a8-e89ebb8c7b25/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19020059/387e4216-889e-11e6-861b-eac33258eb70.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19014535/b98dc12e-87ef-11e6-8861-474eb1af72f1.png)
https://cloud.githubusercontent.com/assets/20930745/19014535/b98dc12e-87ef-11e6-8861-474eb1af72f1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19014537/c705630c-87ef-11e6-98ff-a1b2e8f47819.png

**Comment by dreamnet** [comment]
...usahhh, but I'm sorry to say that the icon has changed.... @2Qt2beStr8 I put you icon to the master anyway and let his issue open.

**Comment by 2Qt2beStr8** [comment]
oh nooooooooooooo :-( ... i try to make the new one today

**Comment by 2Qt2beStr8** [comment]
hmmm ... i don't know ... not my best icon ... most of the parts are very small, so it was very hard to do

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19020059/387e4216-889e-11e6-861b-eac33258eb70.png)
https://cloud.githubusercontent.com/assets/20930745/19020059/387e4216-889e-11e6-861b-eac33258eb70.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19020078/9ff49904-889e-11e6-91db-1ac588f54f39.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 I think it looks also good. Taken! :+1:
