### ISSUE TITLE
Net Master - IT Tools & LAN Scanner

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6536]
**App Name:** Net Master - IT Tools & LAN Scanner
**Bundle ID:** com.nutecapps.Net-Master
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=470646694">470646694</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/net-master-it-tools-lan-scanner/id470646694?mt=8&uo=4">https://itunes.apple.com/us/app/net-master-it-tools-lan-scanner/id470646694?mt=8&uo=4</a>
**App Version:** 5.10
**Seller:** Nutec Apps, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nutec-apps-llc/id470646697?uo=4>© Nutec Apps, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/f3/07/e0/f307e098-1b2f-7eab-ad42-ec775d14ad8a/mzl.fpullrmq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10379001/8755c060-6e0c-11e5-8d0c-22d06e3c789a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10379001/8755c060-6e0c-11e5-8d0c-22d06e3c789a.png)
https://cloud.githubusercontent.com/assets/2068130/10379001/8755c060-6e0c-11e5-8d0c-22d06e3c789a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10379010/9741ac64-6e0c-11e5-8fc6-25140444c995.png
