### ISSUE TITLE
wOmp

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6537]
**App Name:** wOmp
**Bundle ID:** com.branchoutmedia.WOMP
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032803627">1032803627</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/womp/id1032803627?mt=8&uo=4">https://itunes.apple.com/us/app/womp/id1032803627?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Branch Out Media Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/branch-out-media-limited/id964624321?uo=4>© Branch Out Media Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/ab/d8/87/abd887fd-11f4-535f-fbed-353a2e5f3cb5/mzl.lxhffpga.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10358069/a5175cb8-6d89-11e5-95ef-37ae73cbf2d5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10358069/a5175cb8-6d89-11e5-95ef-37ae73cbf2d5.png)
https://cloud.githubusercontent.com/assets/2068130/10358069/a5175cb8-6d89-11e5-95ef-37ae73cbf2d5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10358087/b6e0b11a-6d89-11e5-9f27-6778057f3357.png
