### ISSUE TITLE
iTerminal - SSH Tool

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6538]
**App Name:** iTerminal - SSH Tool
**Bundle ID:** com.comcsoft.iTerminal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=581455211">581455211</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iterminal-ssh-tool/id581455211?mt=8&uo=4">https://itunes.apple.com/us/app/iterminal-ssh-tool/id581455211?mt=8&uo=4</a>
**App Version:** 2.02
**Seller:** Comc Soft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/comcsoft/id413971334?uo=4>© ComcSoft</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/03/7d/f4/037df406-aa48-feab-4efb-4e9cfcbc5418/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10358342/7f7e3dd8-6d8d-11e5-86b1-72433a551469.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10358342/7f7e3dd8-6d8d-11e5-86b1-72433a551469.png)
https://cloud.githubusercontent.com/assets/2068130/10358342/7f7e3dd8-6d8d-11e5-86b1-72433a551469.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10358344/8cdd01c6-6d8d-11e5-8015-72bdd85eacf9.png
