### ISSUE TITLE
Houzz Interior Design Ideas

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6541]
**App Name:** Houzz Interior Design Ideas
**Bundle ID:** com.houzz.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=399563465">399563465</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/houzz-interior-design-ideas/id399563465?mt=8&uo=4">https://itunes.apple.com/us/app/houzz-interior-design-ideas/id399563465?mt=8&uo=4</a>
**App Version:** 18.2.1
**Seller:** Houzz Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/houzz-inc/id391273436?uo=4">© Houzz Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/2d/d9/ad/2dd9ad9f-538f-e981-a2cd-91c3a7031e83/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559492-a1651bde-2a27-11e8-91d7-29166f11bd53.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10357889/fa53e2e8-6d87-11e5-8882-06286ab59974.png)
https://cloud.githubusercontent.com/assets/2068130/10357889/fa53e2e8-6d87-11e5-8882-06286ab59974.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10357899/0b1b5390-6d88-11e5-9026-762f3f46a05a.png

**Comment by LaCh0uine** [comment]
@dreamnet 👍🏻

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Houzz Interior Design Ideas
**Bundle ID:** com.houzz.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=399563465">399563465</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/houzz-interior-design-ideas/id399563465?mt=8&uo=4">https://itunes.apple.com/us/app/houzz-interior-design-ideas/id399563465?mt=8&uo=4</a>
**App Version:** 18.2.1
**Seller:** Houzz Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/houzz-inc/id391273436?uo=4">© Houzz Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/2d/d9/ad/2dd9ad9f-538f-e981-a2cd-91c3a7031e83/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559492-a1651bde-2a27-11e8-91d7-29166f11bd53.png)
https://user-images.githubusercontent.com/2068130/37559492-a1651bde-2a27-11e8-91d7-29166f11bd53.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37559495-b0a1e4ce-2a27-11e8-81d5-2bc30f9bbb47.png
