### ISSUE TITLE
Desjardins Insurance

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#6542]
**App Name:** Desjardins Insurance
**Bundle ID:** com.desjardins.ajusto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=958825069">958825069</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/ca/app/desjardins-insurance/id958825069?uo=4">https://apps.apple.com/ca/app/desjardins-insurance/id958825069?uo=4</a>
**App Version:** 3.12
**Seller:** Federation des caisses Desjardins du Quebec
**Developer:** <a target="_blank" href="https://apps.apple.com/ca/developer/desjardins/id386636956?uo=4">© Desjardins</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/20/35/85/2035850c-ba54-8899-7beb-3a5b6ba376fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382290-4adccb80-9a61-11e9-8e33-5b931a371f55.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10377242/8ee60254-6e02-11e5-8988-abf86099ff0f.png)
https://cloud.githubusercontent.com/assets/2068130/10377242/8ee60254-6e02-11e5-8988-abf86099ff0f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10377253/9dc5d9ac-6e02-11e5-9d33-e72b9b825c1b.png

**Comment by LaCh0uine** [comment]
@dreamnet 👍🏻

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382290-4adccb80-9a61-11e9-8e33-5b931a371f55.png)
https://user-images.githubusercontent.com/20930745/60382290-4adccb80-9a61-11e9-8e33-5b931a371f55.png

Source:
https://user-images.githubusercontent.com/20930745/60382291-4ca68f00-9a61-11e9-9fa3-a9de086aa344.png
