### ISSUE TITLE
Trends - The Simple App For What's Trending Now

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6543]
**App Name:** Trends - The Simple App For What's Trending Now
**Bundle ID:** com.menlo.Trends
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1022176717">1022176717</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trends-simple-app-for-whats/id1022176717?mt=8&uo=4">https://itunes.apple.com/us/app/trends-simple-app-for-whats/id1022176717?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** SP Menlo LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sp-menlo-llc/id1022176716?uo=4>© SP Menlo, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/28/ec/f2/28ecf22f-c29a-f4c2-15b6-6b4db1771fd5/mzl.jxymyqwl.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10377614/aed33882-6e04-11e5-8dcd-3bf6d3dc3a28.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10377614/aed33882-6e04-11e5-8dcd-3bf6d3dc3a28.png)
https://cloud.githubusercontent.com/assets/2068130/10377614/aed33882-6e04-11e5-8dcd-3bf6d3dc3a28.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10377628/bd4d1cb6-6e04-11e5-9c58-175498026bca.png
