### ISSUE TITLE
Lookmark

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6544]
**App Name:** Lookmark
**Bundle ID:** io.lookmark.Lookmark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1016517297">1016517297</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lookmark/id1016517297?mt=8&uo=4">https://itunes.apple.com/us/app/lookmark/id1016517297?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Heybox AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/heybox-ab/id668394340?uo=4>© Heybox AB</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/8f/a9/b8/8fa9b885-46de-9249-ea2f-e4f99e0e9d12/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10377168/1fc8e0f8-6e02-11e5-88dd-3fe03907cbcd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10377168/1fc8e0f8-6e02-11e5-88dd-3fe03907cbcd.png)
https://cloud.githubusercontent.com/assets/2068130/10377168/1fc8e0f8-6e02-11e5-88dd-3fe03907cbcd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10377191/2efeecf2-6e02-11e5-8560-8bad8fd06af5.png

**Comment by ivanov007** [comment]
:smile: the original icon looks like toilet paper

**Comment by dreamnet** [comment]
@ivanov007 :laughing: Yeah, that's true...
