### ISSUE TITLE
ScanLotería - Escáner Loterías y Apuestas del Estado. Resultados Primitiva, Euromillones, Bonoloto, Gordo Primitiva y más loterías

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6545]
**App Name:** ScanLotería - Escáner Loterías y Apuestas del Estado. Resultados Primitiva, Euromillones, Bonoloto, Gordo Primitiva y más loterías
**Bundle ID:** com.AlfonsoMerida.ScanLoteri-a
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=688855874">688855874</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scanloteria-escaner-loterias/id688855874?mt=8&uo=4">https://itunes.apple.com/us/app/scanloteria-escaner-loterias/id688855874?mt=8&uo=4</a>
**App Version:** 4.10
**Seller:** Alfonso Merida
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alfonso-merida/id688855877?uo=4>© Alfonso Merida</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/67/d8/a3/67d8a374-79c1-0349-33a9-95d5e3ced34f/mzl.xbktdrzp.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10370802/db3e8e9a-6de0-11e5-9097-1c7c54ed6cd4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10370802/db3e8e9a-6de0-11e5-9097-1c7c54ed6cd4.png)
https://cloud.githubusercontent.com/assets/2068130/10370802/db3e8e9a-6de0-11e5-9097-1c7c54ed6cd4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10370819/eb489c36-6de0-11e5-8940-e1d73b1c6cf0.png
