### ISSUE TITLE
WinterBoard

### ISSUE THREAD

**Issue by MagnaMike** [glasklart/hd#656]
**App Name:** WinterBoard
**Bundle ID:**  com.saurik.WinterBoard
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="http://stat.ameba.jp/user_images/20120330/17/mapleonlyme/00/00/p/o0118012011884037723.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/8891141/45727a64-331d-11e5-8565-5098e22b7c4e.png)

**Comment by dreamnet** [comment]
I'm adding the icon back gain, because it is useful when using a fix...
