### ISSUE TITLE
AP World History Exam Prep +

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6574]
**App Name:** AP World History Exam Prep +
**Bundle ID:** com.brain-scape.sa.c15508
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=850675085">850675085</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ap-world-history-exam-prep/id850675085?mt=8&uo=4">https://itunes.apple.com/us/app/ap-world-history-exam-prep/id850675085?mt=8&uo=4</a>
**App Version:** 3.20180228
**Seller:** Bold Learning Solutions, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/brainscape/id380833754?uo=4">© Brainscape</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/a7/c9/91/a7c991ef-72b0-2e67-318e-25bc64494358/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38457030-b3654f42-3a8b-11e8-8970-4d523549ec4d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10387429/946c2cd0-6e61-11e5-8cfb-64c0b0aa34a3.png)
https://cloud.githubusercontent.com/assets/10730122/10387429/946c2cd0-6e61-11e5-8cfb-64c0b0aa34a3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10387424/910e8484-6e61-11e5-964e-16e6a2faf347.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38457030-b3654f42-3a8b-11e8-8970-4d523549ec4d.png)
https://user-images.githubusercontent.com/20930745/38457030-b3654f42-3a8b-11e8-8970-4d523549ec4d.png

Source:
https://user-images.githubusercontent.com/20930745/38457039-c8628676-3a8b-11e8-8dcc-a2d71e40a389.png
