### ISSUE TITLE
Yahoo Sports - your teams, your scores, your news

### ISSUE THREAD

**Issue by ph03n1x786** [glasklart/hd#658]
**App Name:** Yahoo Sports - your teams, your scores, your news
**Bundle ID:** com.softacular.Sportacular
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=286058814">286058814</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahoo-sports-your-teams-your/id286058814?mt=8&uo=4">https://itunes.apple.com/us/app/yahoo-sports-your-teams-your/id286058814?mt=8&uo=4</a>
**App Version:** 6.2
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4>© Yahoo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple62/v4/46/87/3d/46873d1e-31d7-15b2-b5ad-b00372cbb3d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18231732/86a2b038-728e-11e6-8464-fd9c773d9be0.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** Yahoo Sports - your teams, your scores, your news
**Bundle ID:** com.softacular.Sportacular
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=286058814">286058814</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahoo-sports-your-teams-your/id286058814?mt=8&uo=4">https://itunes.apple.com/us/app/yahoo-sports-your-teams-your/id286058814?mt=8&uo=4</a>
**App Version:** 6.2
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4>© Yahoo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple62/v4/46/87/3d/46873d1e-31d7-15b2-b5ad-b00372cbb3d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18231732/86a2b038-728e-11e6-8464-fd9c773d9be0.png)

https://cloud.githubusercontent.com/assets/3704186/18231732/86a2b038-728e-11e6-8464-fd9c773d9be0.png

https://cloud.githubusercontent.com/assets/3704186/18231734/943219dc-728e-11e6-9340-01e685a47237.png
