### ISSUE TITLE
Pandora - Free Music & Radio

### ISSUE THREAD

**Issue by J3D1-WARR10R** [glasklart/hd#659]
**App Name:** Pandora - Free Music & Radio
**Bundle ID:** com.pandora
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284035177">284035177</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pandora-free-music-radio/id284035177?mt=8&uo=4">https://itunes.apple.com/us/app/pandora-free-music-radio/id284035177?mt=8&uo=4</a>
**App Version:** 7.7
**Seller:** Pandora Media, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pandora-media-inc./id284035180?uo=4>© Pandora Media, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/a8/13/d5/a813d546-c31e-24d9-b2ab-dbc41643bd7d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19343947/9bb24f24-9138-11e6-8d54-5ce9bbb1efed.png)

**Comment by zmathiasz** [comment]
**App Name:** Pandora Radio
**Bundle ID:** com.pandora
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284035177">284035177</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pandora-radio/id284035177?mt=8&uo=4">https://itunes.apple.com/us/app/pandora-radio/id284035177?mt=8&uo=4</a>
**App Version:** 5.8
**Seller:** Pandora Media, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pandora-media-inc./id284035180?uo=4>© Pandora Media, Inc.</a>
**Supported Devices:** iPhone-3GS, iPadThirdGen4G, iPadFourthGen4G, iPodTouchFifthGen, iPhone5s, iPadMini, iPhone4, iPhone4S, iPadThirdGen, iPhone6, iPhone5c, iPhone6Plus, iPad23G, iPadFourthGen, iPadMini4G, iPodTouchFourthGen, iPhone5, iPad2Wifi
**Original Artwork:**
<img src="http://a64.phobos.apple.com/us/r30/Purple5/v4/d2/e3/b0/d2e3b049-d789-1900-48bb-737744cc5e58/mzl.tyioqgoi.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by zmathiasz** [comment]
Hasn't been update for a couple years.  Thought that the new layout would be nice.  :smile: 

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6976621/84037d02-d97a-11e4-8054-c4cb75092a23.png)
https://cloud.githubusercontent.com/assets/10950389/6976621/84037d02-d97a-11e4-8054-c4cb75092a23.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6976630/99f3f894-d97a-11e4-9613-a96a2c4f8590.png

**Comment by dreamnet** [comment]
@zmathiasz Yeah, I update it. :+1:

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Pandora - Free Music & Radio
**Bundle ID:** com.pandora
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284035177">284035177</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pandora-free-music-radio/id284035177?mt=8&uo=4">https://itunes.apple.com/us/app/pandora-free-music-radio/id284035177?mt=8&uo=4</a>
**App Version:** 7.7
**Seller:** Pandora Media, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pandora-media-inc./id284035180?uo=4>© Pandora Media, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/a8/13/d5/a813d546-c31e-24d9-b2ab-dbc41643bd7d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19343947/9bb24f24-9138-11e6-8d54-5ce9bbb1efed.png)
https://cloud.githubusercontent.com/assets/20930745/19343947/9bb24f24-9138-11e6-8d54-5ce9bbb1efed.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19343970/b0008f9a-9138-11e6-8667-30541ef5df4e.png
