### ISSUE TITLE
Steam Mobile

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6591]
**App Name:** Steam Mobile
**Bundle ID:** com.valvesoftware.Steam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=495369748">495369748</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/steam-mobile/id495369748?mt=8&uo=4">https://itunes.apple.com/us/app/steam-mobile/id495369748?mt=8&uo=4</a>
**App Version:** 1.5.6
**Seller:** Valve Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/valve/id495369751?uo=4>© Valve</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/63/12/ac/6312ac60-108e-760f-4e4a-4e26d94c709f/mzl.tqxqencr.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10388607/b84f286e-6e6b-11e5-85e1-b18f40ec3f2f.png)

**Comment by Trubbel** [comment]
Adding issue, updating icon.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10388607/b84f286e-6e6b-11e5-85e1-b18f40ec3f2f.png)
https://cloud.githubusercontent.com/assets/10730122/10388607/b84f286e-6e6b-11e5-85e1-b18f40ec3f2f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10388606/b2b29954-6e6b-11e5-8f7f-f857853611d7.png

**Comment by Trubbel** [comment]
Alternate, _(personally don't like how the new icon is cut in half)_

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10388618/d079a798-6e6b-11e5-8d20-66ed23a21416.png)
https://cloud.githubusercontent.com/assets/10730122/10388618/d079a798-6e6b-11e5-8d20-66ed23a21416.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10388616/cd118602-6e6b-11e5-843d-90dccca941cf.png

**Comment by dreamnet** [comment]
@Trubbel Going with the original...
