### ISSUE TITLE
AppTicker News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6592]
**App Name:** AppTicker News
**Bundle ID:** de.web-xtreme.appTicker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=351887785">351887785</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appticker-news/id351887785?mt=8&uo=4">https://itunes.apple.com/us/app/appticker-news/id351887785?mt=8&uo=4</a>
**App Version:** 5.4.2
**Seller:** Stanislaw Schoenberg
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stanislaw-schoenberg/id333176382?uo=4>© Stanislaw Schoenberg</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/99/20/47/992047aa-9d26-7072-dfd0-763be3d0bb43/mzl.glvmqwir.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10419060/d8e2836c-706b-11e5-9980-432c5bd64d63.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10419060/d8e2836c-706b-11e5-9980-432c5bd64d63.png)
https://cloud.githubusercontent.com/assets/2068130/10419060/d8e2836c-706b-11e5-9980-432c5bd64d63.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10419065/ec214440-706b-11e5-99fa-9c0401d00911.png
