### ISSUE TITLE
FINAL FANTASY VII

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#6593]
**App Name:** FINAL FANTASY VII
**Bundle ID:** com.square-enix.final-fantasy-vii-ww
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1021566244">1021566244</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/final-fantasy-vii/id1021566244?mt=8&uo=4">https://itunes.apple.com/us/app/final-fantasy-vii/id1021566244?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/eb/08/ac/eb08ac8a-dcc0-f176-9c2e-597aba70f9e8/mzl.ajqcnxuf.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/10417972/1898e276-701c-11e5-823d-cd5b4103f9e4.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/10417972/1898e276-701c-11e5-823d-cd5b4103f9e4.png)
https://cloud.githubusercontent.com/assets/10950389/10417972/1898e276-701c-11e5-823d-cd5b4103f9e4.png

Source:
https://cloud.githubusercontent.com/assets/10950389/10417976/229ec966-701c-11e5-9e58-9f36712920b0.png

**Comment by ivanov007** [comment]
@zmathiasz very good :+1: , but 16 bucks I really like this game but I won't pay more than 5
