### ISSUE TITLE
Using Anemone Underlays for baseplate (again)

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#6595]
As someone may have noticed Anemone [has the ability to use Overlays and/or Underlays/Shadows for icons](https://github.com/AnemoneTeam/Anemone/wiki/Icon-Effects). This means we could go back to the "old" method we are using for iOS6, making the icons just blank with only the icon itself and Anemone will add the baseplate to the icon, example:
![01_glasklart_icon_template_ 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10431941/640e157c-7108-11e5-92a1-b625bf78d849.png) **+** ![icon](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10431969/8831d77c-7108-11e5-9418-612c432fffcb.png) **=** ![com gameloft earthworm 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10431981/977c7264-7108-11e5-9857-2a70b3b80059.png)
Using this method again will save us a lot of space for the icons, I think Glasklart could be reduced from about 60MB to ~ 30MB. I can generate the icons without the baseplate from the existing sources by script and I think I can add the old icons from release 3.14, so we won't loose much icons.
Any thoughts?

**Comment by ivanov007** [comment]
wow by half, and doing this will help also to the iphone+ users?

**Comment by dreamnet** [comment]
Well, it's hard to estimate, but I think if we do the above and integrate @3x versions of all icons with source, I think we will land on about 50-60MB again...

**Comment by Teekzilla** [comment]
Woah, this is pretty cool, can't wait to see the results!

**Comment by dreamnet** [comment]
OK, script is finished, now I have 4.333 @2x icons with 21,2MB and 4.333 @3x files with 36,5MB, that makes 57,7MB. If I integrate the @2x icons with no source (3.834) we will get another ~ 20MB, so we will get in the result about ~77MB. Without he @3x icons we will get ~40MB. Hmmmmm.....

**Comment by dreamnet** [comment]
Good, I converted all old icons from release 3.14 to 120x120px (except a view very bad ones) and copied them together with the ones from the above conversion...
I endet up with 9.221 @2x icon files, after png-optmizing windows says they need 44.6MB. So I was a bit too optimistic with the ~30MB I mentioned above, but minus ~15MB is also not bad. If I include the @3x-files, we would get up to ~81MB. Hmmmmmmmmmm..... :thought_balloon:

**Comment by dreamnet** [comment]
Well, that's fun:
![img_0324](https://cloud.githubusercontent.com/assets/2068130/10691408/27ddfa66-7989-11e5-9576-1e57827cfdba.PNG)

**Comment by ivanov007** [comment]
shoul we release a 5.0 with this and the iOS icons updates, like wallet and podcasts?

**Comment by dreamnet** [comment]
@ivanov007 Yes, we could do. I'm currently updating the stock icons on my website to there iOS9 versions.

**Comment by dreamnet** [comment]
@ivanov007 There is one problem left: If I add the baseplate with Anemone [Icon Effects](https://github.com/AnemoneTeam/Anemone/wiki/Icon-Effects), it is also shown as closed folder background, this means I can only add a border or an opaque black background or someting like that to the closed folders - the baseplate will always be there. I will post a view examples.

**Comment by dreamnet** [comment]
@ivanov007 I'm running into some more problems with this - If I remove the baseplate from the icons and add them back with AnemoneIconEffects, the baseplate is not shown on the "mini-icons" in closed folders, so I have to do something like this for the closed folders:
![anemfoldericonbg 2x](https://cloud.githubusercontent.com/assets/2068130/10714697/bb4c169e-7afa-11e5-85c6-9d1e49958cfa.png)
This looks fine if you have nine icons in the folder, but if you have less than 9 icons it shows only a blank baseplate... here is what I mean:
![unbenannt-1](https://cloud.githubusercontent.com/assets/2068130/10714719/7a5aa8ac-7afb-11e5-8361-7a238b716cd2.png)

**Comment by ivanov007** [comment]
mhh yeah, that's an issue, maybe we can wait a little to make the closed folder look good, although the mini-icons options looks good to me even on the folders with less than 9 icons
About Patricia, for me it was just a day and half of rain (not even too heavy rain) and that's all yesterday was a sunny day :smile:

**Comment by ivanov007** [comment]
oh, I just read the underlay post, so that will fix this closed folder issue too?

**Comment by dreamnet** [comment]
@ivanov007 Good to hear that you didnt have problems with Patricia.
No, the newly added underlays are only applyed to outside of springboard, so this affects only the icons in the settings (the settings theme looks very nice now... :smile:). Overlays and/or Shadows are not applied to the "mini-icons" in the closed folders. The solution with putting the baseplate directly in the Glasklart Folders is just a "half-solution", because if it is turned off we have the standard folder look with only the icon and no baseplate...
![unbenannt-1](https://cloud.githubusercontent.com/assets/2068130/10750550/ed2092d0-7c76-11e5-9a99-b180037db684.png)
So I think it's better to wait until Anemone has the ability to show Overlays/Shadows in closed folders. I report this to @coolstar - let's see what he says.

**Comment by Anuskuss** [comment]
Anomone just got updated!

**Comment by dreamnet** [comment]
@Anuskuss Yes, but the above problem is not solved yet.

**Comment by coolstar** [comment]
@dreamnet overlays were always applied in closed folders. Only shadows aren't. The new UnderlaySpringBoard should resolve this issue.

**Comment by coolstar** [comment]
This is my home screen with an overlay applied inside a folder via Anemone.
![image](https://cloud.githubusercontent.com/assets/1431548/11078394/764bfa74-87ba-11e5-8ff1-41aab1e4e196.png)

**Comment by dreamnet** [comment]
@coolstar Had some problems with the calendar icon, but I solved this using a complete blank image.
I was able to get this using `iPhoneUnderlaySpringBoard@2x.png`:
![img_0359](https://cloud.githubusercontent.com/assets/2068130/11085474/297221dc-8847-11e5-9e28-847c651d8b7f.PNG)
All looks fine, but I already need to do some more testing.

**Comment by Teekzilla** [comment]
Just curious, using this method does the share sheet icons also get an Underlay?

From Anemone GitHub: iPhone (retina) (120x120): iPhoneUnderlay@2x.png
This is supposed to "Anemone applies the following underlays underneath icons outside of SpringBoard."

@coolstar

**Comment by coolstar** [comment]
@Teekzilla yes, share sheet icons also get a Underlay

**Comment by LaCh0uine** [comment]
Are you try the new method from anemone with only one size icon for all with "-large" method I thing you save enough space

**Comment by dreamnet** [comment]
@LaCh0uine Yeah, maybe. I have this on my list.

**Comment by dreamnet** [comment]
I am currently in "testing mode" for
- using `-large` for all @3x icons in IconBundles that we have.
- removing the Baseplate from the icons in IconBundles.
- adding the Baseplate to `AnemoneEffects/iPhoneUnderlaySpringboard` icons.
- checking how all this corresponds with the share sheet and the settings icons.
- ckecking if we run into other problems...

If all works fine, 4.40 will be the last release that's using @2x icons and the baseplate in the normal icons. This als means we are dropping the last Winterboard support and we will loose some old icons (btw. the icons with no source files). Anemone will be added as a dependency to Glasklart.

I check back when I have done enough testing.

**Comment by coolstar** [comment]
Sounds good. Let me know if there's any issues that can be resolved on Anemone's end

**Comment by dreamnet** [comment]
@coolstar Thanks for commenting and yes, I think there is an issue. I am just courious :open_mouth: that Anemone resizes the underlays (iPhoneUnderlaySpringboard@2x.png) from 120x120px to 124x124px.
Here is a screeshot from my testing theme:
![img_0460](https://cloud.githubusercontent.com/assets/2068130/18026344/ae3c7a1c-6c43-11e6-8fc0-a9950494eb13.PNG)
Please zoom in to the Anemone icon, there are some markers, the cyan markers are from the underlay, the magenta markers are from the icon. The underlay is made with 120x120px, the icon is made with 180x180px using -large method.
iPhone6, iOS 9.0.2, Anemone 1.1-393.

**Comment by dreamnet** [comment]
@ivanov007 @Trubbel I know one of you have an iPhone 6+...
I have made a test theme - can some of you please download and test it?
Here it is: [Glasklart_5_test.zip](https://github.com/glasklart/hd/files/440633/Glasklart_5_test.zip)
Only some basic icons are in the zip - please tell me how it works for you and please post a unchanged (full size) screenshot, making sure the Anemone icon is in it, because this icon have some special markers.
THANKS!

**Comment by Trubbel** [comment]
@dreamnet 

![..](https://cloud.githubusercontent.com/assets/10730122/18030096/189fd1c6-6cab-11e6-960e-ceeb87b9904f.png)

**Comment by dreamnet** [comment]
@Trubbel Thank's a lot! :+1: 
@coolstar As you can see in the screenshot from @Trubbel's 6+ above, the icons are displayed correct (180x180px), the underlay (iPhoneUnderlaySpringboard@3x.png) is sized up to 186x186px. Is this expected? You can also try the [test theme](https://github.com/glasklart/hd/files/440633/Glasklart_5_test.zip) I posted above.

**Comment by coolstar** [comment]
I'll install the test theme and see what I find.

**Comment by coolstar** [comment]
Fixed in Anemone 1.1-397 ![image](https://cloud.githubusercontent.com/assets/1431548/18031293/b747d480-6c8e-11e6-8c36-4adbd9bdf25e.png)

**Comment by Trubbel** [comment]
Looks good on iPhone 6 Plus as well, thanks!

**Comment by dreamnet** [comment]
Yes, looks good! Problems solved - thanks to @coolstar !
Also thanks to @Trubbel !
