### ISSUE TITLE
AppCake - Icon Update?

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6597]
The icon for AppCake has changed since this icon was made.
The new one is just a start essentially. The layers under isn't there, just wondering if you guys feel the need to update the icon or no?

**Comment by Teekzilla** [comment]
Here's a link to the only other AppCake issue I could find that is closed: https://github.com/glasklart/hd/issues/508

**Comment by dreamnet** [comment]
#508 is the only existing AppCake app i know (Version 4.92), so I reopen the issue and closing this.
