### ISSUE TITLE
Cydia - Icon Update

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6598]
This icon has slightly changed as well from iOS7 I believe.
http://www.ijailbreak.com/wp-content/uploads/2014/06/cydia-ios7-icon.png

Current: http://glasklarthd.dreamnet.at/index.php?id=53

**Comment by dreamnet** [comment]
![icon 2x](https://cloud.githubusercontent.com/assets/2068130/10446967/3d6be4ee-7180-11e5-86b7-1282fbd6776d.png) ![icon-60 2x](https://cloud.githubusercontent.com/assets/2068130/10446968/43337c48-7180-11e5-97bc-6c110e636407.png)
Old and new Cydia logo. The changes are not very significant, I think there is no need to update the Glasklart icon.
