### ISSUE TITLE
Sparkasse+ All bank accounts in one app

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#6599]
**App Name:** Sparkasse+          All bank accounts in one app
**Bundle ID:** de.starfinanz.Banking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=320596872">320596872</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sparkasse+-all-bank-accounts/id320596872?mt=8&uo=4">https://itunes.apple.com/us/app/sparkasse+-all-bank-accounts/id320596872?mt=8&uo=4</a>
**App Version:** 2.7.1
**Seller:** Star Finanz GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/star-finanz-gmbh/id320596875?uo=4>© Star Finanz GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/5a/96/2a/5a962a24-303d-97bf-11da-9f4accddc074/mzl.lzrpcdca.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563937/edd66882-759e-11e5-8b42-fa5fe28ad331.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563937/edd66882-759e-11e5-8b42-fa5fe28ad331.png)
https://cloud.githubusercontent.com/assets/2068130/10563937/edd66882-759e-11e5-8b42-fa5fe28ad331.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563943/00bf8e10-759f-11e5-817d-e27c79dcfeed.png
