### ISSUE TITLE
Mimi Hearing Test

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#6600]
**App Name:** Mimi Hearing Test
**Bundle ID:** io.mimi.TestSuite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=932496645">932496645</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mimi-hearing-test/id932496645?mt=8&uo=4">https://itunes.apple.com/us/app/mimi-hearing-test/id932496645?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Mimi Hearing Technologies GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mimi-hearing-technologies/id855322101?uo=4>© Mimi Hearing Technologies</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/6f/7d/3f/6f7d3fae-d229-d631-7fd0-39f45f2a6e4b/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12637658/4276e87e-c597-11e5-84d7-da1e0a361b11.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10564006/8b9704a2-75a2-11e5-90f4-c5de4ea078f7.png)
https://cloud.githubusercontent.com/assets/2068130/10564006/8b9704a2-75a2-11e5-90f4-c5de4ea078f7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10564009/9b19b532-75a2-11e5-9d45-6dfc536835b7.png

**Comment by Anuskuss** [comment]
@dreamnet If you don't mind, could you make the line thicker? So that it stands out a little bit more.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12637658/4276e87e-c597-11e5-84d7-da1e0a361b11.png)
https://cloud.githubusercontent.com/assets/2068130/12637658/4276e87e-c597-11e5-84d7-da1e0a361b11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12637665/517e9a56-c597-11e5-8169-1f4b429963fd.png

**Comment by Anuskuss** [comment]
Thank you :+1:
