### ISSUE TITLE
Grand Theft Auto: Chinatown Wars

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6602]
**App Name:** Grand Theft Auto: Chinatown Wars
**Bundle ID:** com.rockstargames.gtachinatownwars
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=344186162">344186162</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grand-theft-auto-chinatown/id344186162?mt=8&uo=4">https://itunes.apple.com/us/app/grand-theft-auto-chinatown/id344186162?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** Rockstar Games, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rockstar-games/id330049731?uo=4>© Rockstar Games</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/7d/48/f8/7d48f851-0242-0d37-c005-d8e5dd3fd2ea/mzl.ltostxes.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10509716/f55a4ec4-732e-11e5-9151-8e2ad8c3357f.png)

**Comment by Trubbel** [comment]
Adding issue and updating the icon plus source,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10509716/f55a4ec4-732e-11e5-9151-8e2ad8c3357f.png)
https://cloud.githubusercontent.com/assets/10730122/10509716/f55a4ec4-732e-11e5-9151-8e2ad8c3357f.png

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10509715/f1567bea-732e-11e5-98d2-8adf74e94165.png)
https://cloud.githubusercontent.com/assets/10730122/10509715/f1567bea-732e-11e5-98d2-8adf74e94165.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10509705/ebfa69ae-732e-11e5-80b8-de2f3c8a38f9.png

**Comment by dreamnet** [comment]
@Trubbel Thanks for contributing! there is no need for "double" posting the icons with and without the baseplate, If we decide to change Glasklart to go the "old" way without baseplate, I will add the Baseplate to the preview. I am currently just checking if it's possible go that way, but this needs some time.

**Comment by Trubbel** [comment]
@dreamnet Alright thank you for clearing that up! I probably should have asked. :)

**Comment by dreamnet** [comment]
@Trubbel :+1: :wink:
