### ISSUE TITLE
Adamant

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6606]
**App Name:** Adamant
**Bundle ID:** com.corybohon.adamant
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1029747593">1029747593</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adamant/id1029747593?mt=8&uo=4">https://itunes.apple.com/us/app/adamant/id1029747593?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Cory Bohon
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cory-bohon/id300813039?uo=4>© Cory Bohon</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/e6/2f/0b/e62f0be6-89db-6def-ab2c-8fe401d60fd8/mzl.cwhrkdwq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563378/6479a4b6-7588-11e5-83f8-ddf0e893ec00.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563378/6479a4b6-7588-11e5-83f8-ddf0e893ec00.png)
https://cloud.githubusercontent.com/assets/2068130/10563378/6479a4b6-7588-11e5-83f8-ddf0e893ec00.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563379/739cc482-7588-11e5-8cf2-82a10af7fe10.png
