### ISSUE TITLE
AdBlock for Mobile

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6607]
**App Name:** AdBlock for Mobile
**Bundle ID:** com.betafish.mobile.ios.AdBlock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1036484810">1036484810</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adblock-for-mobile/id1036484810?mt=8&uo=4">https://itunes.apple.com/us/app/adblock-for-mobile/id1036484810?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** BETAFISH INC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/betafish-inc/id1036483275?uo=4>© BETAFISH INC</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/9a/f0/fa/9af0fa8c-1988-9c8b-cf22-9e4e918d0dfa/mzl.rzjbotbu.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563241/2dba9bb6-7582-11e5-9727-a69b69668e2c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563241/2dba9bb6-7582-11e5-9727-a69b69668e2c.png)
https://cloud.githubusercontent.com/assets/2068130/10563241/2dba9bb6-7582-11e5-9727-a69b69668e2c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563242/3cd49f7a-7582-11e5-8743-85c94452fb33.png
