### ISSUE TITLE
Adblock Fast

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6608]
**App Name:** Adblock Fast
**Bundle ID:** com.rocketshipapps.adblockfast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032930802">1032930802</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adblock-fast/id1032930802?mt=8&uo=4">https://itunes.apple.com/us/app/adblock-fast/id1032930802?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** 10x Studio, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/10x/id917526595?uo=4>© 10x</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/2c/33/e7/2c33e704-01ed-abbc-e2e1-c8df5737e27d/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563200/7e4010e6-757f-11e5-9aca-de0278eb16ce.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563200/7e4010e6-757f-11e5-9aca-de0278eb16ce.png)
https://cloud.githubusercontent.com/assets/2068130/10563200/7e4010e6-757f-11e5-9aca-de0278eb16ce.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563202/8c80319a-757f-11e5-9855-5c466fc66f5b.png
