### ISSUE TITLE
AdMop

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6609]
**App Name:** AdMop
**Bundle ID:** ch.iphonso.admop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035458197">1035458197</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/admop/id1035458197?mt=8&uo=4">https://itunes.apple.com/us/app/admop/id1035458197?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** iPhonso GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iphonso-gmbh/id364900630?uo=4>© iPhonso GmbH</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/96/d2/2a/96d22a64-cab1-d3f0-e305-b1588c599c57/mzl.cenutabi.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563178/7a51702a-757e-11e5-8e13-ba5ffbbcf161.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563178/7a51702a-757e-11e5-8e13-ba5ffbbcf161.png)
https://cloud.githubusercontent.com/assets/2068130/10563178/7a51702a-757e-11e5-8e13-ba5ffbbcf161.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563180/88775bd8-757e-11e5-93d5-4e10c787b2d4.png
