### ISSUE TITLE
Blockr - Privacy, Media and Ad Blocker for Safari

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6610]
**App Name:** Blockr - Privacy, Media and Ad Blocker for Safari
**Bundle ID:** de.AT.Blockr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032344361">1032344361</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blockr-privacy-media-ad-blocker/id1032344361?mt=8&uo=4">https://itunes.apple.com/us/app/blockr-privacy-media-ad-blocker/id1032344361?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Tim Pollert
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tim-pollert/id1032344360?uo=4>© Tim Pollert</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/d9/a7/f3/d9a7f322-6f1a-f643-d465-d8951c4b221e/mzl.ghvegagq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563169/ee7021a0-757d-11e5-870c-a93e4520e3e8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563169/ee7021a0-757d-11e5-870c-a93e4520e3e8.png)
https://cloud.githubusercontent.com/assets/2068130/10563169/ee7021a0-757d-11e5-870c-a93e4520e3e8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563171/fce273f0-757d-11e5-9112-fb2d1a085864.png
