### ISSUE TITLE
Crystal - Ad free web browsing. Block ads now!

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6611]
**App Name:** Crystal - Ad free web browsing. Block ads now!
**Bundle ID:** co.MurphyApps.Crystal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1022177308">1022177308</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/crystal-ad-free-web-browsing./id1022177308?mt=8&uo=4">https://itunes.apple.com/us/app/crystal-ad-free-web-browsing./id1022177308?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Dean Murphy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dean-murphy/id552801280?uo=4>© Dean Murphy</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/28/85/26/288526ef-0840-2e5c-e3b6-aa06de33c46e/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563703/093a7276-7595-11e5-852d-ec13d8fd77ea.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563703/093a7276-7595-11e5-852d-ec13d8fd77ea.png)
https://cloud.githubusercontent.com/assets/2068130/10563703/093a7276-7595-11e5-852d-ec13d8fd77ea.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563705/186a9ed8-7595-11e5-8835-a83a63c5a348.png
