### ISSUE TITLE
Freedom - Ad Blocker

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6612]
**App Name:** Freedom - Ad Blocker
**Bundle ID:** com.zachapps.Freedom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1033791657">1033791657</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/freedom-ad-blocker/id1033791657?mt=8&uo=4">https://itunes.apple.com/us/app/freedom-ad-blocker/id1033791657?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Rachel Simone
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zachapps/id548893440?uo=4>© ZachApps</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/0d/62/4f/0d624ffe-55a2-e6fd-a4ee-f29b763200ec/mzl.pvtqdnio.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563128/cb98635a-757c-11e5-8459-2619923584f8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563128/cb98635a-757c-11e5-8459-2619923584f8.png)
https://cloud.githubusercontent.com/assets/2068130/10563128/cb98635a-757c-11e5-8459-2619923584f8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563130/d9f55d86-757c-11e5-94ee-ce591c21a0f4.png
