### ISSUE TITLE
Vivio AdBlocker – Faster Browsing Without Ads

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6613]
**App Name:** Vivio AdBlocker – Faster Browsing Without Ads
**Bundle ID:** cz.jancislinsky.vivio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1033671088">1033671088</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vivio-adblocker-faster-browsing/id1033671088?mt=8&uo=4">https://itunes.apple.com/us/app/vivio-adblocker-faster-browsing/id1033671088?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Jan Cislinsky
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jan-cislinsky/id1033671087?uo=4>© Jan Cislinsky</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/15/17/e5/1517e54e-5695-b168-192c-ff9bd6035f2b/mzl.tvgastvb.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563155/6111e2c6-757d-11e5-921e-3137916eca59.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563155/6111e2c6-757d-11e5-921e-3137916eca59.png)
https://cloud.githubusercontent.com/assets/2068130/10563155/6111e2c6-757d-11e5-921e-3137916eca59.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563156/709b8d00-757d-11e5-9d8e-e2c0653bd4ea.png
