### ISSUE TITLE
1Blocker - Block ads, tracking scripts, anything

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6614]
**App Name:** 1Blocker - Block ads, tracking scripts, anything
**Bundle ID:** com.khanov.Blocker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1025729002">1025729002</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1blocker-block-ads-tracking/id1025729002?mt=8&uo=4">https://itunes.apple.com/us/app/1blocker-block-ads-tracking/id1025729002?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Salavat Khanov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/salavat-khanov/id854494576?uo=4>© Salavat Khanov</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/17/ff/61/17ff61ca-6576-e848-171f-a06365ad24ea/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563766/bdbcdb38-7597-11e5-9f21-216f792d28f0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563766/bdbcdb38-7597-11e5-9f21-216f792d28f0.png)
https://cloud.githubusercontent.com/assets/2068130/10563766/bdbcdb38-7597-11e5-9f21-216f792d28f0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563770/cbae0bb8-7597-11e5-9fe7-6bd8256b711e.png
