### ISSUE TITLE
[DUPLICATE of #6617]

### ISSUE THREAD

**Issue by gunnii713** [glasklart/hd#6616]
App name: Kingdom Rush Origins
Bundle ID: com.ironhidegames.kingdomrush.elves
iTunes URL: https://itunes.apple.com/au/app/kingdom-rush-origins/id904737816?mt=8
App Version: 1.8.1
Seller: Ironhide S.A.
Supported Devices: iPhone, iPad, iPod touch - iOS 7 and above
Original Artwork:
![image](https://cloud.githubusercontent.com/assets/15176876/10562084/8bc4f946-7590-11e5-9a22-ceb33dcfcc7c.jpeg)

**Comment by Teekzilla** [comment]
Dulpicate of #6617

**Comment by gunnii713** [comment]
Sorry, I posted the other one too, but I did it correctly :)
