### ISSUE TITLE
Kingdom Rush Origins

### ISSUE THREAD

**Issue by gunnii713** [glasklart/hd#6617]
**App Name:** Kingdom Rush Origins
**Bundle ID:** com.ironhidegames.kingdomrush.elves
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=904737816">904737816</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kingdom-rush-origins/id904737816?mt=8&uo=4">https://itunes.apple.com/us/app/kingdom-rush-origins/id904737816?mt=8&uo=4</a>
**App Version:** 1.8.1
**Seller:** Ironhide S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ironhide-s.a./id558612918?uo=4>© Ironhide S.A.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/03/0c/36/030c369f-addf-b5d9-664b-70ae4d2d2d17/mzl.quyjkumo.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563357/e464936c-7587-11e5-865c-e0ea246e78c2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563357/e464936c-7587-11e5-865c-e0ea246e78c2.png)
https://cloud.githubusercontent.com/assets/2068130/10563357/e464936c-7587-11e5-865c-e0ea246e78c2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563358/f386254a-7587-11e5-8693-6743524a5498.png

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by dreamnet** [comment]
Already in [the repo](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.ironhidegames.kingdomrush.elves-large.png). No action needed.
