### ISSUE TITLE
Class Timetable

### ISSUE THREAD

**Issue by gunnii713** [glasklart/hd#6618]
**App Name:** Class Timetable
**Bundle ID:** com.icemediacreative.Timetable
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=425121147">425121147</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/class-timetable/id425121147?mt=8&uo=4">https://itunes.apple.com/us/app/class-timetable/id425121147?mt=8&uo=4</a>
**App Version:** 5.5
**Seller:** Jordan Smith
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ice-media-creative/id411412435?uo=4>© Ice Media Creative</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/dd/1e/b3/dd1eb38b-5630-d488-b69d-9b698903519a/mzl.qfqfnxrw.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563448/cd012124-758a-11e5-9646-daa7f13f0c7d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563448/cd012124-758a-11e5-9646-daa7f13f0c7d.png)
https://cloud.githubusercontent.com/assets/2068130/10563448/cd012124-758a-11e5-9646-daa7f13f0c7d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563452/dba77142-758a-11e5-9da3-bed52a479c90.png
