### ISSUE TITLE
Pocket Schedule - Class Schedule, Homework Planner & School Organizer

### ISSUE THREAD

**Issue by gunnii713** [glasklart/hd#6619]
**App Name:** Pocket Schedule - Class Schedule, Homework Planner & School Organizer
**Bundle ID:** com.btgs.pocketschedulelite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=421102532">421102532</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-schedule-class-schedule/id421102532?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-schedule-class-schedule/id421102532?mt=8&uo=4</a>
**App Version:** 3.1.3
**Seller:** Appxy Information Technology Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appxy/id760100924?uo=4>© Appxy</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/77/79/7e/77797efa-6f99-67b3-1ed2-ccbf9fb7d73b/mzl.rrscwfis.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563827/2218f7e0-759a-11e5-8d3e-26f22c1d3d5c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10563827/2218f7e0-759a-11e5-8d3e-26f22c1d3d5c.png)
https://cloud.githubusercontent.com/assets/2068130/10563827/2218f7e0-759a-11e5-8d3e-26f22c1d3d5c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10563832/315c044a-759a-11e5-900d-74a3a7d54de4.png
