### ISSUE TITLE
Flex

### ISSUE THREAD

**Issue by J3D1-WARR10R** [glasklart/hd#662]
I hope i'm doing this right as this is not from the App Store.
Name: Flex
Bundle ID: com.fuyuchi.flex
iTunes ID: NONE
PNG Icon Names: Icon.png | Icon@2x.png | 
Artwork URL: http://imgur.com/7bDp2aw,pgE3lyw

**Comment by dreamnet** [comment]
I'm removing this, because it's for iOS5 and 6 only.
