### ISSUE TITLE
amaysim

### ISSUE THREAD

**Issue by gunnii713** [glasklart/hd#6620]
**App Name:** amaysim
**Bundle ID:** au.com.amaysim.AmaySimiPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479119656">479119656</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amaysim/id479119656?mt=8&uo=4">https://itunes.apple.com/us/app/amaysim/id479119656?mt=8&uo=4</a>
**App Version:** 2.7.0
**Seller:** amaysim Australia Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amaysim-australia-ltd/id479119659?uo=4">© amaysim Australia Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/f4/b1/7d/f4b17d1b-2fa4-75b2-4bd6-61e5b1eb058c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455185-d9d0b17e-3a74-11e8-90c3-064831e49579.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10562886/73ae54f6-7572-11e5-9b36-0cfa118dba85.png)
https://cloud.githubusercontent.com/assets/2068130/10562886/73ae54f6-7572-11e5-9b36-0cfa118dba85.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10562889/83266f5e-7572-11e5-98ec-5b304ca68da6.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455185-d9d0b17e-3a74-11e8-90c3-064831e49579.png)
https://user-images.githubusercontent.com/20930745/38455185-d9d0b17e-3a74-11e8-90c3-064831e49579.png

Source:
https://user-images.githubusercontent.com/20930745/38455188-ea7522c6-3a74-11e8-947f-b489adef701c.png
