### ISSUE TITLE
Italy Travel Guide by Triposo featuring Rome, Florence, Venice, Milan and more!

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6621]
**App Name:** Italy Travel Guide by Triposo featuring Rome, Florence, Venice, Milan and more!
**Bundle ID:** com.triposo.italyguide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447762736">447762736</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/italy-travel-guide-by-triposo/id447762736?mt=8&uo=4">https://itunes.apple.com/us/app/italy-travel-guide-by-triposo/id447762736?mt=8&uo=4</a>
**App Version:** 5.0.3
**Seller:** Triposo Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/triposo-inc/id415611465?uo=4>© Triposo Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/52/60/b3/5260b368-c2dc-e50b-c7ac-a3feb896f38f/mzl.tmzybuns.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)

**Comment by Trubbel** [comment]
Same icon as #6124,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png)
https://cloud.githubusercontent.com/assets/10730122/8971987/0833dcc4-3656-11e5-853b-7b2c85eb8660.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8971983/04fa70b8-3656-11e5-991e-0169cc50e885.png

**Comment by Trubbel** [comment]
I apologize in advance for the upcoming.. "spam" :smile:

**Comment by dreamnet** [comment]
@Trubbel https://www.youtube.com/watch?v=anwy2MPT5RE :wink:

**Comment by Trubbel** [comment]
@dreamnet Haha! :laughing:
