### ISSUE TITLE
Rover: Friends. Interests. Stories.

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6638]
**App Name:** Rover: Friends. Interests. Stories.
**Bundle ID:** com.infoaxe.flipora2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=902092194">902092194</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rover-friends.-interests./id902092194?mt=8&uo=4">https://itunes.apple.com/us/app/rover-friends.-interests./id902092194?mt=8&uo=4</a>
**App Version:** 2.1.81
**Seller:** Infoaxe Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/infoaxe-inc./id902092197?uo=4>© Infoaxe Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/e0/1e/71/e01e71bd-da00-dcc6-ae23-ff93ed2c35f9/mzl.dkxbbhwq.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10564829/70598a78-75c2-11e5-9f47-b466428623b5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10564829/70598a78-75c2-11e5-9f47-b466428623b5.png)
https://cloud.githubusercontent.com/assets/2068130/10564829/70598a78-75c2-11e5-9f47-b466428623b5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10564832/7f03ab08-75c2-11e5-9603-dfe4e18dc69e.png
