### ISSUE TITLE
iDays Lite - Be your companion on every big day !

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6639]
**App Name:** iDays Lite - Be your companion on every big day !
**Bundle ID:** com.gerinn.countdownlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1007007017">1007007017</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/idays-lite-be-your-companion/id1007007017?mt=8&uo=4">https://itunes.apple.com/us/app/idays-lite-be-your-companion/id1007007017?mt=8&uo=4</a>
**App Version:** 3.0.7
**Seller:** Gerinn LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gerinn-llc/id537042831?uo=4>© Gerinn LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/99/d0/73/99d07313-ef25-ca91-9ed4-1799b243499b/mzl.dchabbhx.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10564857/fa0fb698-75c2-11e5-90fe-a3720e33ba46.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10564857/fa0fb698-75c2-11e5-90fe-a3720e33ba46.png)
https://cloud.githubusercontent.com/assets/2068130/10564857/fa0fb698-75c2-11e5-90fe-a3720e33ba46.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10564858/0b0c11e4-75c3-11e5-86ca-f7f3affef2a0.png
