### ISSUE TITLE
Pumped BMX 2

### ISSUE THREAD

**Issue by gunnii713** [glasklart/hd#6644]
**App Name:** Pumped BMX 2
**Bundle ID:** com.yeahus.pumped2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=893141226">893141226</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pumped-bmx-2/id893141226?mt=8&uo=4">https://itunes.apple.com/us/app/pumped-bmx-2/id893141226?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Adam Hunt
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yeah-us!/id527173194?uo=4>© Yeah Us!</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/d2/73/ea/d273eab4-8323-8804-0aec-3ecdbda1a724/mzl.qgjlgifr.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715763/49c7bc08-7b22-11e5-9e7a-b92f1b36827f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715763/49c7bc08-7b22-11e5-9e7a-b92f1b36827f.png)
https://cloud.githubusercontent.com/assets/2068130/10715763/49c7bc08-7b22-11e5-9e7a-b92f1b36827f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715764/57833e58-7b22-11e5-8797-d6c713e418ba.png

**Comment by Trubbel** [comment]
@dreamnet Not bad! :grinning:

**Comment by dreamnet** [comment]
@Trubbel No, it's very good! :laughing:

**Comment by Trubbel** [comment]
@dreamnet It's amazing! :laughing:

**Comment by dreamnet** [comment]
@Trubbel It's hyper-perfect! :heart_eyes: :stuck_out_tongue_winking_eye:

**Comment by ivanov007** [comment]
it does looks great, but it looks like the original icon's son :wink:

**Comment by dreamnet** [comment]
@ivanov007 You are right. Maybe we nwwd to add a beard? :thought_balloon:
