### ISSUE TITLE
Minigore 2: Zombies

### ISSUE THREAD

**Issue by J3D1-WARR10R** [glasklart/hd#665]
**App Name:** Minigore 2: Zombies
**Bundle ID:** ms.games.minigore2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=576939960">576939960</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minigore-2-zombies/id576939960?mt=8&uo=4">https://itunes.apple.com/us/app/minigore-2-zombies/id576939960?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Mountain Sheep
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mountain-sheep/id392924730?uo=4">© Mountain Sheep</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple19/v4/ad/8e/09/ad8e09c5-433a-33cc-08df-897e69d7c131/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21288664/797553e6-c489-11e6-8731-80bf4085d6f4.png)

**Comment by ivanov007** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21288664/797553e6-c489-11e6-8731-80bf4085d6f4.png)
https://cloud.githubusercontent.com/assets/2068130/21288664/797553e6-c489-11e6-8731-80bf4085d6f4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21288669/888211f8-c489-11e6-9eb8-5c78a277f8c1.png
