### ISSUE TITLE
Fidelity Investments

### ISSUE THREAD

**Issue by J3D1-WARR10R** [glasklart/hd#666]
**App Name:** Fidelity Investments
**Bundle ID:** com.fidelity.watchlist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348177453">348177453</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fidelity-investments/id348177453?mt=8&uo=4">https://itunes.apple.com/us/app/fidelity-investments/id348177453?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Fidelity Investments
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fidelity-investments/id348177456?uo=4>© Fidelity Investments</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/ac/0d/53/ac0d533d-5a68-0c86-8894-0a693cde1d45/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19528560/c77dfae2-962c-11e6-96b2-0b4f3a13939f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19528560/c77dfae2-962c-11e6-96b2-0b4f3a13939f.png)
https://cloud.githubusercontent.com/assets/20930745/19528560/c77dfae2-962c-11e6-96b2-0b4f3a13939f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19528580/e17d10d6-962c-11e6-9d31-394b008fca16.png
