### ISSUE TITLE
Global Wallet

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6666]
**App Name:** Global Wallet
**Bundle ID:** com.revworldwide.velocityglobalwallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=655286959">655286959</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/global-wallet/id655286959?mt=8&uo=4">https://itunes.apple.com/us/app/global-wallet/id655286959?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** Rev Worldwide
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rev-worldwide/id509266090?uo=4>© Rev Worldwide</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/2e/e3/c3/2ee3c341-c72a-4b30-87ce-4fb1c7e50b43/mzl.wvigjvew.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10593992/aecebc0e-76c8-11e5-85e1-6e878cdb1ee3.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10593992/aecebc0e-76c8-11e5-85e1-6e878cdb1ee3.png)
https://cloud.githubusercontent.com/assets/10730122/10593992/aecebc0e-76c8-11e5-85e1-6e878cdb1ee3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10593990/ac9a2e0a-76c8-11e5-9211-3138d4f8c274.png
