### ISSUE TITLE
BEME - Share Video. Honestly

### ISSUE THREAD

**Issue by jake-igt** [glasklart/hd#6667]
Request for possible icon in next update. App Icons come in 29x29 , 40x40, 60x60

Bundle ID: com.beme.beme

![appicon29x29 2x](https://cloud.githubusercontent.com/assets/15204107/10593579/069f9272-7693-11e5-9183-77615d5f8955.png)
![appicon29x29 3x](https://cloud.githubusercontent.com/assets/15204107/10593583/06abc8c6-7693-11e5-8faa-149794cbb5b3.png)
![appicon40x40 2x](https://cloud.githubusercontent.com/assets/15204107/10593581/06aa0338-7693-11e5-8f1c-d4c48654c3d9.png)
![appicon40x40 3x](https://cloud.githubusercontent.com/assets/15204107/10593580/06a9cdaa-7693-11e5-8cae-e9bfe8b921f4.png)
![appicon60x60 2x](https://cloud.githubusercontent.com/assets/15204107/10593584/06ad00c4-7693-11e5-905a-b0036d41fbde.png)
![appicon60x60 3x](https://cloud.githubusercontent.com/assets/15204107/10593582/06aa4c80-7693-11e5-8804-474bec6ef22e.png)

**Comment by Trubbel** [comment]
@jake-igt Please follow the [Glasklart guidelines](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request) on how to request an icon.
