### ISSUE TITLE
beme: Share video. Honestly.

### ISSUE THREAD

**Issue by Teekzilla** [glasklart/hd#6668]
**App Name:** beme: Share video. Honestly.
**Bundle ID:** com.beme.beme
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1005178547">1005178547</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beme-share-video.-honestly./id1005178547?mt=8&uo=4">https://itunes.apple.com/us/app/beme-share-video.-honestly./id1005178547?mt=8&uo=4</a>
**App Version:** 0.6.1
**Seller:** BeMe Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/beme/id1005178546?uo=4>© Beme</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/9c/68/a2/9c68a273-a5d6-6e32-4b2e-2af8780476ae/mzl.gfnpgtll.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594100/b74ec576-76c9-11e5-8b12-94626e40b420.png)

**Comment by Teekzilla** [comment]
@jake-igt

**Comment by jake-igt** [comment]
Thank you. Was in the process of compiling this information. I will read the guidelines now, ha!

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594100/b74ec576-76c9-11e5-8b12-94626e40b420.png)
https://cloud.githubusercontent.com/assets/10730122/10594100/b74ec576-76c9-11e5-8b12-94626e40b420.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10594099/b50012ac-76c9-11e5-9cb2-3ef8f5f22ea6.png

**Comment by dreamnet** [comment]
Hmmmmm......
