### ISSUE TITLE
Product Hunt - the best new products, every day

### ISSUE THREAD

**Issue by jake-igt** [glasklart/hd#6669]
**App Name:** Product Hunt - the best new products, every day
**Bundle ID:** com.producthunt.producthuntbundleid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=904658671">904658671</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/product-hunt-best-new-products/id904658671?mt=8&uo=4">https://itunes.apple.com/us/app/product-hunt-best-new-products/id904658671?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** PRODUCT HUNT, INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/product-hunt-inc./id904658674?uo=4>© Product Hunt Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/52/26/da/5226da6f-553f-f52d-3456-0ae152973376/mzl.qxxjgstx.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594519/43d728ae-76ce-11e5-8de8-a1f69d373a33.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594519/43d728ae-76ce-11e5-8de8-a1f69d373a33.png)
https://cloud.githubusercontent.com/assets/10730122/10594519/43d728ae-76ce-11e5-8de8-a1f69d373a33.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10594518/4028e0bc-76ce-11e5-8db6-aefd926d41a9.png

**Comment by jake-igt** [comment]
Thank you
