### ISSUE TITLE
Fun Run - Multiplayer Race

### ISSUE THREAD

**Issue by J3D1-WARR10R** [glasklart/hd#667]
**App Name:** Fun Run - Multiplayer Race
**Bundle ID:** no.dirtybit.funrun
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547201991">547201991</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fun-run-multiplayer-race/id547201991?mt=8&uo=4">https://itunes.apple.com/us/app/fun-run-multiplayer-race/id547201991?mt=8&uo=4</a>
**App Version:** 2.22
**Seller:** DIRTYBIT DA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dirtybit/id484858667?uo=4>© dirtyBit</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/3b/29/94/3b2994a7-f795-2f7d-d40a-3b8e11f0a8ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18622854/8c8a17ea-7e35-11e6-8120-b8e694feda5b.png)

**Comment by Anuskuss** [comment]
Sorry to say that, but I don't really like it. #7161 looks way better. @dreamnet do you want to remake this (without the question mark)?

**Comment by dreamnet** [comment]
@Anuskuss I don't have the time - but if someone else will do it...

**Comment by 2Qt2beStr8** [comment]
@Anuskuss ... not really a good icon - but i can't do it better ... maybe you can use it until someone makes a better on

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18618600/7ba9d7f8-7dea-11e6-93e0-b699f5964cd9.png)
https://cloud.githubusercontent.com/assets/20930745/18618600/7ba9d7f8-7dea-11e6-93e0-b699f5964cd9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18618604/91c07d4e-7dea-11e6-8d9f-c91162245afb.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18618625/f95b474a-7dea-11e6-976f-c578992a4014.png)
https://cloud.githubusercontent.com/assets/20930745/18618625/f95b474a-7dea-11e6-976f-c578992a4014.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18618630/113ca340-7deb-11e6-944a-5531172cdf95.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Great! 👍

**Comment by 2Qt2beStr8** [comment]
sorry Günther ... i forgot the left hand ... can you pls take this icon ;-)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619581/86b46bca-7e00-11e6-8b4e-93c43a099a7d.png)
https://cloud.githubusercontent.com/assets/20930745/18619581/86b46bca-7e00-11e6-8b4e-93c43a099a7d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18619586/a70f5de4-7e00-11e6-9c2f-fe31b5d50388.png

**Comment by ivanov007** [comment]
it's kind of shrinked isn't it?

**Comment by dreamnet** [comment]
@ivanov007 Your are right... but the source is fine:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18622854/8c8a17ea-7e35-11e6-8120-b8e694feda5b.png)
https://cloud.githubusercontent.com/assets/2068130/18622854/8c8a17ea-7e35-11e6-8120-b8e694feda5b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18622859/9c4e1578-7e35-11e6-8b62-de6d30d2b382.png
