### ISSUE TITLE
RVWR

### ISSUE THREAD

**Issue by jake-igt** [glasklart/hd#6670]
**App Name:** RVWR
**Bundle ID:** com.patrickadams.RVWR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=867001352">867001352</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rvwr/id867001352?mt=8&uo=4">https://itunes.apple.com/us/app/rvwr/id867001352?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Patrick Adams
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/patrick-adams/id629292604?uo=4>© Patrick Adams</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/1b/87/af/1b87af80-2588-0742-0542-a3eabaff74a5/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594731/695d3cd8-76d0-11e5-9318-fdfdce09df80.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594731/695d3cd8-76d0-11e5-9318-fdfdce09df80.png)
https://cloud.githubusercontent.com/assets/10730122/10594731/695d3cd8-76d0-11e5-9318-fdfdce09df80.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10594730/65efb422-76d0-11e5-8ea4-9cf7e0fd4977.png

**Comment by Trubbel** [comment]
Alternate,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594741/81de954a-76d0-11e5-85c6-b425255033e3.png)
https://cloud.githubusercontent.com/assets/10730122/10594741/81de954a-76d0-11e5-85c6-b425255033e3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10594736/7dcde83e-76d0-11e5-9160-4e506ef72df8.png

**Comment by jake-igt** [comment]
thank you
