### ISSUE TITLE
Vessel - Early Access to your favorite videos

### ISSUE THREAD

**Issue by jake-igt** [glasklart/hd#6671]
**App Name:** Vessel - Early Access to your favorite videos
**Bundle ID:** com.vessel.monkey
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943718088">943718088</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vessel-early-access-to-your/id943718088?mt=8&uo=4">https://itunes.apple.com/us/app/vessel-early-access-to-your/id943718088?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Vessel Group, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vessel-group-inc/id943713926?uo=4>© Vessel Group, Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/57/79/1e/57791e72-464e-4cc9-52a9-1b6efd0e8c25/mzl.fzuyener.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594559/9a7b7070-76ce-11e5-98e9-7123f8e2726a.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594559/9a7b7070-76ce-11e5-98e9-7123f8e2726a.png)
https://cloud.githubusercontent.com/assets/10730122/10594559/9a7b7070-76ce-11e5-98e9-7123f8e2726a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10594555/94e5a9b4-76ce-11e5-8ee3-cba705d99d98.png
