### ISSUE TITLE
TradeHero

### ISSUE THREAD

**Issue by jake-igt** [glasklart/hd#6672]
**App Name:** TradeHero
**Bundle ID:** com.edenpod.TradeHero
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=572226383">572226383</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tradehero/id572226383?mt=8&uo=4">https://itunes.apple.com/us/app/tradehero/id572226383?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** Edencr8 Pte Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/edenpod/id402399362?uo=4>© edenpod</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/43/a8/d3/43a8d30b-e729-5b01-bc3d-734590b53cd5/mzl.lwyhrljh.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594921/8c84b4b4-76d2-11e5-9068-0fb8a7a9b1c5.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594921/8c84b4b4-76d2-11e5-9068-0fb8a7a9b1c5.png)
https://cloud.githubusercontent.com/assets/10730122/10594921/8c84b4b4-76d2-11e5-9068-0fb8a7a9b1c5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10594920/898fd342-76d2-11e5-8e35-62c106fbffdf.png

**Comment by Trubbel** [comment]
Same as above but with 'eyes',

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594939/a54a3d66-76d2-11e5-858f-4089e4374ccc.png)
https://cloud.githubusercontent.com/assets/10730122/10594939/a54a3d66-76d2-11e5-858f-4089e4374ccc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10594936/a0c916ea-76d2-11e5-9a81-f5fa258931d8.png

**Comment by Trubbel** [comment]
Another alternate,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594951/c9a8bb88-76d2-11e5-958d-8940c922e428.png)
https://cloud.githubusercontent.com/assets/10730122/10594951/c9a8bb88-76d2-11e5-958d-8940c922e428.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10594948/c32e43ea-76d2-11e5-89d0-401d759ee9aa.png

**Comment by dreamnet** [comment]
@Trubbel The first one fits best. :+1:
