### ISSUE TITLE
Longform: A Smart Reader

### ISSUE THREAD

**Issue by jake-igt** [glasklart/hd#6673]
**App Name:** Longform: A Smart Reader
**Bundle ID:** com.professorseagull.longformapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=490437064">490437064</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/longform-a-smart-reader/id490437064?mt=8&uo=4">https://itunes.apple.com/us/app/longform-a-smart-reader/id490437064?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Professor Seagull
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/longform/id490437067?uo=4>© Longform</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/a0/58/59/a0585969-7618-5cb6-3458-8e12e682c4e8/mzl.ikmdkhur.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594594/f05eb0e2-76ce-11e5-9a43-9a21631df992.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594594/f05eb0e2-76ce-11e5-9a43-9a21631df992.png)
https://cloud.githubusercontent.com/assets/10730122/10594594/f05eb0e2-76ce-11e5-9a43-9a21631df992.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10594592/ed73be18-76ce-11e5-9379-e944d7c9100f.png
