### ISSUE TITLE
LoLHistory for League of Legends

### ISSUE THREAD

**Issue by jake-igt** [glasklart/hd#6674]
**App Name:** LoLHistory for League of Legends
**Bundle ID:** com.printandpixel.lolhistory
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926167081">926167081</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lolhistory-for-league-legends/id926167081?mt=8&uo=4">https://itunes.apple.com/us/app/lolhistory-for-league-legends/id926167081?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Oskar Separovic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/oskar-separovic/id1041735097?uo=4>© Oskar Separovic</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/23/bf/c1/23bfc1fa-5541-8be3-afd0-b474e62ad4ac/mzl.phulgkzr.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594629/4b14f8f2-76cf-11e5-80ce-e6e840ec633e.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10594629/4b14f8f2-76cf-11e5-80ce-e6e840ec633e.png)
https://cloud.githubusercontent.com/assets/10730122/10594629/4b14f8f2-76cf-11e5-80ce-e6e840ec633e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10594628/47fbfb02-76cf-11e5-908f-9a5d180403ca.png
