### ISSUE TITLE
Purify Blocker: No Ads. No Tracking. Lightning-Fast Safari.

### ISSUE THREAD

**Issue by jake-igt** [glasklart/hd#6675]
**App Name:** Purify Blocker: No Ads. No Tracking. Lightning-Fast Safari.
**Bundle ID:** com.chrismatic.Purify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1030156203">1030156203</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/purify-blocker-no-ads.-no/id1030156203?mt=8&uo=4">https://itunes.apple.com/us/app/purify-blocker-no-ads.-no/id1030156203?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Chris Aljoudi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chris-aljoudi/id1030156202?uo=4>© Chris Aljoudi</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/14/89/24/148924c1-a248-d38c-dadb-c31b3c4d0af8/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10712186/358b6ee0-7a93-11e5-9485-574ab0913f91.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/10631894/27c7d08c-77e1-11e5-97be-a88e4ccc0d89.png)
https://cloud.githubusercontent.com/assets/8452321/10631894/27c7d08c-77e1-11e5-97be-a88e4ccc0d89.png

Source:
https://cloud.githubusercontent.com/assets/8452321/10631905/3826f70a-77e1-11e5-95ea-40db46d15da1.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10712186/358b6ee0-7a93-11e5-9485-574ab0913f91.png)
https://cloud.githubusercontent.com/assets/2068130/10712186/358b6ee0-7a93-11e5-9485-574ab0913f91.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10712188/45f5f1d8-7a93-11e5-8d9f-f43744119dea.png
