### ISSUE TITLE
FlashScore.de

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6682]
**App Name:** FlashScore.de
**Bundle ID:** eu.livesport.ErgebnisseLive-com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=751549888">751549888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/flashscore.de/id751549888?mt=8&uo=4">https://itunes.apple.com/de/app/flashscore.de/id751549888?mt=8&uo=4</a>
**App Version:** 1.11.0
**Seller:** LiveSport s.r.o.
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/flashscore/id722265281?uo=4>© FlashScore</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/ab/27/6c/ab276c7b-7630-a1ad-228a-7f0e0755f85a/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11016970/42eb6136-8591-11e5-8ceb-eb762d33ce61.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10646647/cf46654a-77f9-11e5-82a3-ade6fa6e9556.png)
https://cloud.githubusercontent.com/assets/3090247/10646647/cf46654a-77f9-11e5-82a3-ade6fa6e9556.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10646644/cd58593c-77f9-11e5-81ea-81d9b89bab20.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:

**Comment by Anuskuss** [comment]
I know this is closed but it bothers me that the icon is off-centered so here is my icon.

**Preview:**
<img src="http://imageshack.com/a/img903/332/RkZ7bm.png" width="150" height="150" />

I'm not a designer but I hopes someone can implement my idea - I'm talking to you @ivanov007 ;)

**Comment by Trubbel** [comment]
@Anuskuss It's the small things... I know what you mean haha. :wink: 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11016970/42eb6136-8591-11e5-8ceb-eb762d33ce61.png)
https://cloud.githubusercontent.com/assets/10730122/11016970/42eb6136-8591-11e5-8ceb-eb762d33ce61.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11016969/3f154982-8591-11e5-9dee-3025a4a9ddf8.png

Modified @ivanov007's source, creds to him.

**Comment by Anuskuss** [comment]
Thank you (:
