### ISSUE TITLE
appgefahren News - tolle Apps entdecken & Punkte sammeln

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6683]
**App Name:** appgefahren News - tolle Apps entdecken & Punkte sammeln
**Bundle ID:** de.appgefahren.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=981053001">981053001</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appgefahren-news-tolle-apps/id981053001?mt=8&uo=4">https://itunes.apple.com/us/app/appgefahren-news-tolle-apps/id981053001?mt=8&uo=4</a>
**App Version:** 6.0.4
**Seller:** appgefahren GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appgefahren-gmbh/id965536066?uo=4>© appgefahren GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/d7/bd/3c/d7bd3c39-0153-4fb8-ea7e-739f876ea7cf/mzl.wnpzjfpy.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10636370/14882b6e-77c5-11e5-8235-13351809dd0c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10636370/14882b6e-77c5-11e5-8235-13351809dd0c.png)
https://cloud.githubusercontent.com/assets/3090247/10636370/14882b6e-77c5-11e5-8235-13351809dd0c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10636369/1483f076-77c5-11e5-9a5a-a84ac09cb1a8.png
