### ISSUE TITLE
AppTicker Push

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6684]
**App Name:** AppTicker Push
**Bundle ID:** de.web-xtreme.appTickerPush
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=356155999">356155999</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appticker-push/id356155999?mt=8&uo=4">https://itunes.apple.com/us/app/appticker-push/id356155999?mt=8&uo=4</a>
**App Version:** 5.0.1
**Seller:** Stanislaw Schoenberg
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stanislaw-schoenberg/id333176382?uo=4>© Stanislaw Schoenberg</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/45/41/6b/45416b93-17dd-fcb9-33ce-4b82f2dda66b/mzm.tvrwkpoo.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715907/19ac2d38-7b27-11e5-86f5-5a872c6fc1ac.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715907/19ac2d38-7b27-11e5-86f5-5a872c6fc1ac.png)
https://cloud.githubusercontent.com/assets/2068130/10715907/19ac2d38-7b27-11e5-86f5-5a872c6fc1ac.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715909/26a8260e-7b27-11e5-8523-bb0e57765627.png
