### ISSUE TITLE
Joyn - Mediathek,TV Livestream

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6685]
**App Name:** Joyn - Mediathek,TV Livestream
**Bundle ID:** de.prosiebensat1digital.seventv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=826510222">826510222</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/de/app/joyn-mediathek-tv-livestream/id826510222?uo=4">https://apps.apple.com/de/app/joyn-mediathek-tv-livestream/id826510222?uo=4</a>
**App Version:** 3.0
**Seller:** Joyn GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/de/developer/joyn-gmbh/id1339620657?uo=4">© Joyn GmbH</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/09/bc/07/09bc0779-8069-7a89-f47f-d6a02daec34d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973827-d7d8de00-95a4-11e9-8adc-02f116a5f405.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/10646395/2aa03478-7833-11e5-8392-fe230e1c7820.png)
https://cloud.githubusercontent.com/assets/8452321/10646395/2aa03478-7833-11e5-8392-fe230e1c7820.png

Source:
https://cloud.githubusercontent.com/assets/8452321/10646408/3811333c-7833-11e5-88ce-6d276449a486.png

**Comment by ivanov007** [comment]
@DerDoktor looks good :+1:

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973827-d7d8de00-95a4-11e9-8adc-02f116a5f405.png)
https://user-images.githubusercontent.com/20930745/59973827-d7d8de00-95a4-11e9-8adc-02f116a5f405.png

Source:
![joyn](https://user-images.githubusercontent.com/20930745/59973830-d90a0b00-95a4-11e9-9ecd-0347dd66766a.png)
