### ISSUE TITLE
Burstio – Animate your burst photos

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6686]
**App Name:** Burstio – Animate your burst photos
**Bundle ID:** cz.michalkos.Burstio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=950387755">950387755</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/burstio-animate-your-burst/id950387755?mt=8&uo=4">https://itunes.apple.com/us/app/burstio-animate-your-burst/id950387755?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Michal Kos
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/michal-kos/id682013284?uo=4>© Michal Kos</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/47/52/8d/47528d31-5d12-efeb-e83d-55bbc57ad0df/mzl.pmebjsmt.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/10631865/fddf1d0c-77e0-11e5-9d4f-3f5f0b8e25c0.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/10631865/fddf1d0c-77e0-11e5-9d4f-3f5f0b8e25c0.png)
https://cloud.githubusercontent.com/assets/8452321/10631865/fddf1d0c-77e0-11e5-9d4f-3f5f0b8e25c0.png

Source:
https://cloud.githubusercontent.com/assets/8452321/10631876/122cabd0-77e1-11e5-864c-9b059e9a35a3.png
