### ISSUE TITLE
pizza.de - Fast food delivery

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6687]
**App Name:** pizza.de - Fast food delivery
**Bundle ID:** de.asco.pizzade
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=374905857">374905857</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pizza-de-fast-food-delivery/id374905857?mt=8&uo=4">https://itunes.apple.com/us/app/pizza-de-fast-food-delivery/id374905857?mt=8&uo=4</a>
**App Version:** 4.14.1
**Seller:** Delivery Hero Germany GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/delivery-hero-germany-gmbh/id1344862009?uo=4">© Delivery Hero Germany GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/bd/b7/f4/bdb7f4ca-ab31-0b15-6c48-ac472afe5af1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36633508-6db9debe-1997-11e8-87d8-ca6c9905065f.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/10631850/dbb154de-77e0-11e5-9c35-96f5de08dfd0.png)
https://cloud.githubusercontent.com/assets/8452321/10631850/dbb154de-77e0-11e5-9c35-96f5de08dfd0.png

Source:
https://cloud.githubusercontent.com/assets/8452321/10631861/eca76aee-77e0-11e5-8f39-029e53a04a86.png

**Comment by Anuskuss** [comment]
Don't know if this icon should get updated.
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/e5/a9/da/e5a9da5d-bcfc-2cd1-8e0d-21fbc4ead0be/source/1024x1024bb.png" width="150" height="150" />

**Comment by dreamnet** [comment]
@Anuskuss Jup, no need to update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36633508-6db9debe-1997-11e8-87d8-ca6c9905065f.png)
https://user-images.githubusercontent.com/20930745/36633508-6db9debe-1997-11e8-87d8-ca6c9905065f.png

Source:
https://user-images.githubusercontent.com/20930745/36633516-823132f2-1997-11e8-983c-34882acbc6ef.png
