### ISSUE TITLE
RetroArch

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6688]
**App Name:** RetroArch
 **Bundle ID:** libretro.RetroArch
 **Version:** 1.0.0.1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="http://imagizer.imageshack.us/a/img905/4264/2PNaxk.png" width="150" height="150" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/10631828/b71aac7e-77e0-11e5-95f1-b0a03580de45.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/10631828/b71aac7e-77e0-11e5-95f1-b0a03580de45.png)
https://cloud.githubusercontent.com/assets/8452321/10631828/b71aac7e-77e0-11e5-95f1-b0a03580de45.png

Source: :-)
https://cloud.githubusercontent.com/assets/8452321/10631837/c6fd4d4a-77e0-11e5-94f6-cb6ce4de2328.png

**Comment by Anuskuss** [comment]
The logo is alright but it isn't themed yet. I'm trying to investigate this problem.

**Comment by dreamnet** [comment]
The bundleID is `libretro.RetroArch`.

**Comment by Anuskuss** [comment]
@dreamnet How do you know? I successfully placed a **com.libretro.RetroArch@2x.png** in IconBundles a RA got themed.

**Comment by dreamnet** [comment]
@Anuskuss Because I downloaded RetroArch version 1.0.0.1 from the ZodTTD repo and checket the Info.plist of RetroArch - it says: `<key>CFBundleIdentifier</key><string>libretro.RetroArch</string>`.
It's interesting that you got it themed with `com.libretro.RetroArch`, it dosen't work for me. Do you have a different version installed?

**Comment by Anuskuss** [comment]
At the time I posted this I was using 1.0.0.1 aswell, but now I'm on the beta ([repo](http://buildbot.libretro.com/repo/cydia/)) the ID was changed. I think when RetroArch will get released, the BundleID would be **com.libretro.RetroArch**

**Comment by dreamnet** [comment]
@Anuskuss Normally we don't go with beta apps, because they are changing there bundleId's fast and just confusing us. But OK, for this one I add the icon under `com.libretro.RetroArch@2x.png` to the master too. Dosen't hurt. :smile:

**Comment by Anuskuss** [comment]
I think when the 1.2.6 RC comes out, nobody will use 1.0.0.1 anyway. But as you say, it doesn't hurt :+1:

**Comment by Anuskuss** [comment]
We have 1.3.0 already, so I think `libretro.RetroArch` is obsolete.

**Comment by BrokenCommander** [comment]
**App Name:** RetroArch
**Bundle ID:** com.libretro.RetroArch
**Version:** 1.3.6

**Comment by BrokenCommander** [comment]
Easy :sunglasses: 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18850509/2c21488e-8438-11e6-8b16-3c30a7ca6a34.png)
https://cloud.githubusercontent.com/assets/22012363/18850509/2c21488e-8438-11e6-8b16-3c30a7ca6a34.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18850505/28502496-8438-11e6-8209-938bf6baba7f.png

**Comment by dreamnet** [comment]
I' opening a new isse for `com.libretro.RetroArch`.
