### ISSUE TITLE
EA SPORTS™ FIFA 16 Companion

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6689]
**App Name:** EA SPORTS™ FIFA 16 Companion
**Bundle ID:** com.ea.fifaultimate.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=554307192">554307192</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/ea-sports-fifa-16-companion/id554307192?mt=8&uo=4">https://itunes.apple.com/gb/app/ea-sports-fifa-16-companion/id554307192?mt=8&uo=4</a>
**App Version:** 16.0.0
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/electronic-arts/id284800461?mt=8&uo=4>© Electronic Arts</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/84/c7/d0/84c7d088-45af-d307-b99c-c9732283b2b6/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/10631787/77dd96a2-77e0-11e5-9fa9-e0b00717cb7b.png)

**Comment by DerDoktor** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/8452321/10631787/77dd96a2-77e0-11e5-9fa9-e0b00717cb7b.png)
https://cloud.githubusercontent.com/assets/8452321/10631787/77dd96a2-77e0-11e5-9fa9-e0b00717cb7b.png

Source:
![fifa16_source](https://cloud.githubusercontent.com/assets/8452321/10631806/96636b74-77e0-11e5-846a-b2602589b896.png)
