### ISSUE TITLE
Shou.TV mobile game streaming!

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6690]
**App Name:** Shou.TV mobile game streaming!
**Bundle ID:** tv.shou.viewer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=946848480">946848480</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shou.tv-mobile-game-streaming!/id946848480?mt=8&uo=4">https://itunes.apple.com/us/app/shou.tv-mobile-game-streaming!/id946848480?mt=8&uo=4</a>
**App Version:** 0.6.4
**Seller:** Shou Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shou-ltd/id946848479?uo=4>© Shou Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/80/8d/d8/808dd835-e987-d2ac-4015-9a0b7847b1c4/mzl.wxcufoky.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10645288/a00e4e8e-77f2-11e5-9c9e-61bb6152a745.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10645288/a00e4e8e-77f2-11e5-9c9e-61bb6152a745.png)
https://cloud.githubusercontent.com/assets/3090247/10645288/a00e4e8e-77f2-11e5-9c9e-61bb6152a745.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10645287/a00c04da-77f2-11e5-9fa6-7c7aa0f81d58.png
