### ISSUE TITLE
Instant Webcam

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6691]
**App Name:** Instant Webcam
**Bundle ID:** org.phoboslab.instantwebcam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=683949930">683949930</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instant-webcam/id683949930?mt=8&uo=4">https://itunes.apple.com/us/app/instant-webcam/id683949930?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Dominic Szablewski
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/phoboslab/id312666931?uo=4>© PhobosLab</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/f7/b9/81/f7b98182-d27f-0896-59de-8dd171d8a150/mzl.gxtdcejt.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715621/0b26fa72-7b1d-11e5-81d5-a75cce848e03.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715621/0b26fa72-7b1d-11e5-81d5-a75cce848e03.png)
https://cloud.githubusercontent.com/assets/2068130/10715621/0b26fa72-7b1d-11e5-81d5-a75cce848e03.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715625/1aad25b6-7b1d-11e5-8986-38e3eb0a892e.png
