### ISSUE TITLE
Boomerang from Instagram

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6692]
**App Name:** Boomerang from Instagram
**Bundle ID:** com.burbn.boomerang
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1041596399">1041596399</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boomerang-from-instagram/id1041596399?mt=8&uo=4">https://itunes.apple.com/us/app/boomerang-from-instagram/id1041596399?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Instagram, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/instagram-inc./id389801255?uo=4>© Instagram, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/f3/39/5a/f3395a43-0e01-8189-394d-4f0fbddfc622/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15281431/7bb8824c-1b3b-11e6-8206-8d9e6d41f758.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10673840/92f6f66c-78bd-11e5-98d5-65fb5dba4888.png)
https://cloud.githubusercontent.com/assets/3090247/10673840/92f6f66c-78bd-11e5-98d5-65fb5dba4888.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10673857/a98b09fe-78bd-11e5-8e40-5ad9f26d3e51.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15281431/7bb8824c-1b3b-11e6-8206-8d9e6d41f758.png)
https://cloud.githubusercontent.com/assets/2068130/15281431/7bb8824c-1b3b-11e6-8206-8d9e6d41f758.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15281437/8b8c829a-1b3b-11e6-9725-b3112e2264d4.png
