### ISSUE TITLE
Super News - News Digest, Wiki, Photo & Video

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6694]
**App Name:** Super News - News Digest, Wiki, Photo & Video
**Bundle ID:** com.star.supernews.simple
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1038231858">1038231858</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-news-news-digest-wiki/id1038231858?mt=8&uo=4">https://itunes.apple.com/us/app/super-news-news-digest-wiki/id1038231858?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Xue Lin Fan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/xue-lin-fan/id889950760?uo=4>© Xue Lin Fan</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/c3/5a/8e/c35a8efb-b37f-b47c-9834-5ad998100ff2/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715578/67342f1c-7b1b-11e5-82fa-50cfa5d8d6b5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715578/67342f1c-7b1b-11e5-82fa-50cfa5d8d6b5.png)
https://cloud.githubusercontent.com/assets/2068130/10715578/67342f1c-7b1b-11e5-82fa-50cfa5d8d6b5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715582/77a434dc-7b1b-11e5-9894-62564b15be06.png
