### ISSUE TITLE
Raindrop.io

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6695]
**App Name:** Raindrop.io
**Bundle ID:** io.raindrop.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1021913807">1021913807</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/raindrop-io/id1021913807?mt=8&uo=4">https://itunes.apple.com/us/app/raindrop-io/id1021913807?mt=8&uo=4</a>
**App Version:** 3.0.9
**Seller:** Rustem Mussabekov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rustem-mussabekov/id739939143?uo=4">© Rustem Mussabekov</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/f6/d5/7a/f6d57abe-91f6-0b96-1e77-c62a0f0de0b7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![io raindrop ios-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34467305-e3399852-eeed-11e7-860b-e45cc3aa7b38.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10705416/12359c5a-79de-11e5-887f-f96aeaa86e3b.png)
https://cloud.githubusercontent.com/assets/2068130/10705416/12359c5a-79de-11e5-887f-f96aeaa86e3b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10705428/2022630c-79de-11e5-8bb4-61a2e2f8aeac.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Raindrop.io
**Bundle ID:** io.raindrop.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1021913807">1021913807</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/raindrop-io/id1021913807?mt=8&uo=4">https://itunes.apple.com/us/app/raindrop-io/id1021913807?mt=8&uo=4</a>
**App Version:** 3.0.9
**Seller:** Rustem Mussabekov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rustem-mussabekov/id739939143?uo=4">© Rustem Mussabekov</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/f6/d5/7a/f6d57abe-91f6-0b96-1e77-c62a0f0de0b7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![io raindrop ios-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34467305-e3399852-eeed-11e7-860b-e45cc3aa7b38.png)
https://user-images.githubusercontent.com/2068130/34467305-e3399852-eeed-11e7-860b-e45cc3aa7b38.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34467306-f2be7194-eeed-11e7-9c28-477a21a0cd1a.png
