### ISSUE TITLE
Breaking News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6696]
**App Name:** Breaking News
**Bundle ID:** com.iavian.breakingnews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398269756">398269756</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/breaking-news/id398269756?mt=8&uo=4">https://itunes.apple.com/us/app/breaking-news/id398269756?mt=8&uo=4</a>
**App Version:** 133.1
**Seller:** Vijay Anand
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vijay-anand/id324758057?mt=8&uo=4">© Vijay Anand</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/4b/95/00/4b950095-6562-2c9c-2c4e-edb0dd0203ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50551943-9caac180-0c89-11e9-8a2c-c62a45586824.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10705523/bdcd59ae-79de-11e5-8430-85292b869521.png)
https://cloud.githubusercontent.com/assets/2068130/10705523/bdcd59ae-79de-11e5-8430-85292b869521.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10705533/cc01002a-79de-11e5-92d9-7ce513fa1475.png

**Comment by l8er4now** [comment]
Needs a minor update.

**App Name:** Breaking News
**Bundle ID:** com.iavian.breakingnews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398269756">398269756</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/breaking-news/id398269756?mt=8&uo=4">https://itunes.apple.com/us/app/breaking-news/id398269756?mt=8&uo=4</a>
**App Version:** 120
**Seller:** Vijay Anand
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vijay-anand/id324758057?mt=8&uo=4">© Vijay Anand</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/72/97/90/729790f0-a07a-2df0-1c40-e26f9e828c3d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20108567/bffdc68e-a5dc-11e6-9d63-814f67ea3c6f.png)
https://cloud.githubusercontent.com/assets/20930745/20108567/bffdc68e-a5dc-11e6-9d63-814f67ea3c6f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20108574/ce20bbb8-a5dc-11e6-882a-6f262a3e8081.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Breaking News
**Bundle ID:** com.iavian.breakingnews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398269756">398269756</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/breaking-news/id398269756?mt=8&uo=4">https://itunes.apple.com/us/app/breaking-news/id398269756?mt=8&uo=4</a>
**App Version:** 133.1
**Seller:** Vijay Anand
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vijay-anand/id324758057?mt=8&uo=4">© Vijay Anand</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/4b/95/00/4b950095-6562-2c9c-2c4e-edb0dd0203ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#
