### ISSUE TITLE
News360: Your Personalized News Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6697]
**App Name:** News360: Your Personalized News Reader
**Bundle ID:** com.news360.news360ipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=420397564">420397564</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/news360-your-personalized/id420397564?mt=8&uo=4">https://itunes.apple.com/us/app/news360-your-personalized/id420397564?mt=8&uo=4</a>
**App Version:** 4.1.3
**Seller:** News360 Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/news360-inc./id959746349?uo=4>© News360 Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/0d/73/5a/0d735a2b-97dc-98dd-cba6-c1e77c6ec19c/mzl.sgwkkpng.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10712146/97693ef0-7a91-11e5-9ecd-3e0ffc54ac53.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10712146/97693ef0-7a91-11e5-9ecd-3e0ffc54ac53.png)
https://cloud.githubusercontent.com/assets/2068130/10712146/97693ef0-7a91-11e5-9ecd-3e0ffc54ac53.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10712150/a5684eb0-7a91-11e5-8344-6f70b3afebe9.png
