### ISSUE TITLE
Hole19 - Golf GPS, Scorecard, Rangefinder & Yardage

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6698]
**App Name:** Hole19 - Golf GPS, Scorecard, Rangefinder & Yardage
**Bundle ID:** com.hole19golf.hole19v2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=794462227">794462227</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hole19-golf-gps-scorecard/id794462227?mt=8&uo=4">https://itunes.apple.com/us/app/hole19-golf-gps-scorecard/id794462227?mt=8&uo=4</a>
**App Version:** 3.0.3
**Seller:** Stat Track Technologies - Servicos Tecnologicos para o Desporto, Lda.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stat-track-technologies-lda./id444501822?uo=4>© Stat Track Technologies Lda.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/13/7c/1a/137c1a1f-2e73-5a00-d594-08e51e14555a/mzl.vmyfrjys.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10710923/da601fa6-7a6b-11e5-881a-16f439d851b4.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10710923/da601fa6-7a6b-11e5-881a-16f439d851b4.png)
https://cloud.githubusercontent.com/assets/10730122/10710923/da601fa6-7a6b-11e5-881a-16f439d851b4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10710922/d6f9864a-7a6b-11e5-84d6-0458cf6ec650.png
