### ISSUE TITLE
MyQuest for Patients

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6699]
**App Name:** MyQuest for Patients
**Bundle ID:** com.questdiagnostics.myquest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=748920931">748920931</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myquest-for-patients/id748920931?mt=8&uo=4">https://itunes.apple.com/us/app/myquest-for-patients/id748920931?mt=8&uo=4</a>
**App Version:** 2.17
**Seller:** Quest Diagnostics, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/quest-diagnostics-inc/id300300771?uo=4">© Quest Diagnostics, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/35/4c/a5/354ca5ca-54b2-0743-007d-5cb91e81cc1b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38174126-03edf4fe-35c9-11e8-97be-d10d17e058f6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10712049/5d1d11d4-7a8e-11e5-81e7-82bccbc0f244.png)
https://cloud.githubusercontent.com/assets/2068130/10712049/5d1d11d4-7a8e-11e5-81e7-82bccbc0f244.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10712053/6d473d8c-7a8e-11e5-8d05-f9eaf0b3314b.png
