### ISSUE TITLE
My Disney Experience - Walt Disney World

### ISSUE THREAD

**Issue by J3D1-WARR10R** [glasklart/hd#670]
**App Name:** My Disney Experience - Walt Disney World
**Bundle ID:** com.disney.MyDisneyExperience
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547436543">547436543</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-disney-experience-walt/id547436543?mt=8&uo=4">https://itunes.apple.com/us/app/my-disney-experience-walt/id547436543?mt=8&uo=4</a>
**App Version:** 3.7
**Seller:** Disney Electronic Content, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/disney/id284888248?mt=8&uo=4>© Disney</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/d2/1c/68/d21c68a9-0de7-3422-88ec-a5f19455f6fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18658799/2d66da42-7f06-11e6-9106-1f43c0379a6c.png)

**Comment by l8er4now** [comment]
Needs to be updated.

**App Name:** My Disney Experience - Walt Disney World
**Bundle ID:** com.disney.MyDisneyExperience
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547436543">547436543</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-disney-experience-walt/id547436543?mt=8&uo=4">https://itunes.apple.com/us/app/my-disney-experience-walt/id547436543?mt=8&uo=4</a>
**App Version:** 3.7
**Seller:** Disney Electronic Content, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/disney/id284888248?mt=8&uo=4>© Disney</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/d2/1c/68/d21c68a9-0de7-3422-88ec-a5f19455f6fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18624572/1cf8872c-7e49-11e6-919c-a74d4ab5c9c1.png)
https://cloud.githubusercontent.com/assets/20930745/18624572/1cf8872c-7e49-11e6-919c-a74d4ab5c9c1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18624580/30d4df20-7e49-11e6-8124-962067883901.png

**Comment by dreamnet** [comment]
With or without the "Disney" sign?
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18658799/2d66da42-7f06-11e6-9106-1f43c0379a6c.png)
https://cloud.githubusercontent.com/assets/2068130/18658799/2d66da42-7f06-11e6-9106-1f43c0379a6c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18658805/3d026e9e-7f06-11e6-8aba-8e1c049d6234.png

**Comment by 2Qt2beStr8** [comment]
.. i like the Disney lettering ... but it's your decide

**Comment by l8er4now** [comment]
I like it without the disney. If you keep the disney, I think it should look closer to the actual icon with a full circle and filled rectangle and hollow disney lettering.

**Comment by Trubbel** [comment]
I believe we can go without the design since we can still see that it is Mickey Mouse.

**Comment by dreamnet** [comment]
I also think that the Mickey Mouse is enough... Sorry @2Qt2beStr8. Sometimes I have to make though decisions... 💭

**Comment by 2Qt2beStr8** [comment]
no problem @dreamnet ... i am not worry about your decision
