### ISSUE TITLE
BiP Mobile

### ISSUE THREAD

**Issue by balraj19991** [glasklart/hd#6700]
**App Name:** BiP Mobile
**Bundle ID:** be.rossel.belgiumiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426360522">426360522</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bip-mobile/id426360522?mt=8&uo=4">https://itunes.apple.com/us/app/bip-mobile/id426360522?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Rossel & Cie
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rossel-cie/id426360525?uo=4>© Rossel & Cie</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/14/a3/70/14a37092-64b6-76dc-5065-38f466eff36b/mzl.rfeunmol.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10714888/84de7c0c-7b02-11e5-8950-094964e37f73.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10714888/84de7c0c-7b02-11e5-8950-094964e37f73.png)
https://cloud.githubusercontent.com/assets/2068130/10714888/84de7c0c-7b02-11e5-8950-094964e37f73.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10714892/93f6d0c2-7b02-11e5-8fa3-59666abbff0f.png
