### ISSUE TITLE
Kinepolis

### ISSUE THREAD

**Issue by balraj19991** [glasklart/hd#6701]
**App Name:** Kinepolis
**Bundle ID:** com.kinepolis.iphone.movieapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368204284">368204284</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kinepolis/id368204284?mt=8&uo=4">https://itunes.apple.com/us/app/kinepolis/id368204284?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Kinepolis Group N.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kinepolis-group-n.v./id368204287?uo=4>© Kinepolis Group N.V.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple4/v4/38/2a/d0/382ad0ac-e39c-3438-461f-e9f557af41bd/mzl.ttjwmrtc.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10714967/1313d7cc-7b05-11e5-8ddb-972bab864f3c.png)

**Comment by dreamnet** [comment]
@balraj19991 With or without the "Kinepolis" text? What do you think?
With:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10714967/1313d7cc-7b05-11e5-8ddb-972bab864f3c.png)
https://cloud.githubusercontent.com/assets/2068130/10714967/1313d7cc-7b05-11e5-8ddb-972bab864f3c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10714972/2c7a2da6-7b05-11e5-8cab-8ae3bdf3c782.png)
Without:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10714981/71910680-7b05-11e5-89be-88f535b4ef6b.png)
https://cloud.githubusercontent.com/assets/2068130/10714981/71910680-7b05-11e5-89be-88f535b4ef6b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10714983/8097b49e-7b05-11e5-9fd3-d54ba1f4f8d1.png

**Comment by balraj19991** [comment]
@dreamnet The upper is good. 
Thanks. 
Do I well get an update on Cydia?

**Comment by dreamnet** [comment]
@balraj19991 OK - what update? Glasklart? The last release was 4.29. We are updating Glasklart every ~ 14 days or about ~ 100 commits.

**Comment by balraj19991** [comment]
@dreamnet Ok. But I meant for the icons. Do I have to add myself?

**Comment by dreamnet** [comment]
@balraj19991 You don't have to add them by yourself, I will add it to the Glasklart master and then they are included in the next release (4.30) of Glasklart on Cydia. Next release is next weekend.

**Comment by balraj19991** [comment]
@dreamnet ok. Btw you are doing an really awesome job

**Comment by dreamnet** [comment]
@balraj19991 Thank you! :+1:
