### ISSUE TITLE
Smartschool

### ISSUE THREAD

**Issue by balraj19991** [glasklart/hd#6702]
**App Name:** Smartschool
**Bundle ID:** be.smartschool.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=440472448">440472448</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartschool/id440472448?mt=8&uo=4">https://itunes.apple.com/us/app/smartschool/id440472448?mt=8&uo=4</a>
**App Version:** 4.6
**Seller:** Smartbit bvba
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/smartschool/id440472451?uo=4>© Smartschool</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/dd/98/52/dd9852cb-9faf-9cb7-8166-30ece75caf71/mzl.kofvrdxi.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10714902/2c1e40e2-7b03-11e5-90b0-32f90431d1f1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10714902/2c1e40e2-7b03-11e5-90b0-32f90431d1f1.png)
https://cloud.githubusercontent.com/assets/2068130/10714902/2c1e40e2-7b03-11e5-90b0-32f90431d1f1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10714905/3e32da90-7b03-11e5-8651-acee2bb12dc5.png
