### ISSUE TITLE
Speed Test SpeedSmart WiFi & Mobile Network Speedtest

### ISSUE THREAD

**Issue by balraj19991** [glasklart/hd#6703]
**App Name:** Speed Test SpeedSmart WiFi & Mobile Network Speedtest
**Bundle ID:** com.veeapps.speedtestxhd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=366593092">366593092</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/speed-test-speedsmart-wifi/id366593092?mt=8&uo=4">https://itunes.apple.com/us/app/speed-test-speedsmart-wifi/id366593092?mt=8&uo=4</a>
**App Version:** 7.2.1
**Seller:** Donovan Lewis
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/veeapps/id301044643?uo=4>© VeeApps</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/c2/08/e6/c208e63c-ae42-8453-9c1e-a7ba3eb27dbd/mzl.wuzljosz.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715110/abe667ea-7b09-11e5-93fc-43289c098f20.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715110/abe667ea-7b09-11e5-93fc-43289c098f20.png)
https://cloud.githubusercontent.com/assets/2068130/10715110/abe667ea-7b09-11e5-93fc-43289c098f20.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715112/b9ed953e-7b09-11e5-8a9c-45dfb6121db8.png
