### ISSUE TITLE
Verisure

### ISSUE THREAD

**Issue by balraj19991** [glasklart/hd#6704]
**App Name:** Verisure
**Bundle ID:** com.securitas-direct.verisure
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=423747572">423747572</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/verisure/id423747572?mt=8&uo=4">https://itunes.apple.com/us/app/verisure/id423747572?mt=8&uo=4</a>
**App Version:** 6.2
**Seller:** Securitas Direct AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/securitas-direct-ab/id423747575?uo=4>© Securitas Direct AB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/0f/30/a9/0f30a9de-c32e-41f7-e339-c9175f7738fd/mzl.xoyiqwpy.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715135/a58afb08-7b0a-11e5-9766-4bbab11e8a8e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715135/a58afb08-7b0a-11e5-9766-4bbab11e8a8e.png)
https://cloud.githubusercontent.com/assets/2068130/10715135/a58afb08-7b0a-11e5-9766-4bbab11e8a8e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715137/b36ad482-7b0a-11e5-898d-c04bb1d5550e.png
