### ISSUE TITLE
My JIM Mobile

### ISSUE THREAD

**Issue by balraj19991** [glasklart/hd#6705]
**App Name:** My JIM Mobile
**Bundle ID:** be.basecompany.jim.myjim
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923333436">923333436</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-jim-mobile/id923333436?mt=8&uo=4">https://itunes.apple.com/us/app/my-jim-mobile/id923333436?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** BASE Company
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/base-company/id552877005?uo=4>© BASE Company</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/bf/17/64/bf176442-c3c9-01c9-fa4a-2b8a56ff4526/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715516/8627cd90-7b19-11e5-9e6e-849d99ffcef7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715516/8627cd90-7b19-11e5-9e6e-849d99ffcef7.png)
https://cloud.githubusercontent.com/assets/2068130/10715516/8627cd90-7b19-11e5-9e6e-849d99ffcef7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715518/938e8532-7b19-11e5-9193-cef5aa0b2b62.png
