### ISSUE TITLE
SNCB/NMBS

### ISSUE THREAD

**Issue by balraj19991** [glasklart/hd#6706]
**App Name:** SNCB/NMBS
**Bundle ID:** com.sncb.traininfo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=403212064">403212064</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sncb-nmbs/id403212064?mt=8&uo=4">https://itunes.apple.com/us/app/sncb-nmbs/id403212064?mt=8&uo=4</a>
**App Version:** 2.1.23
**Seller:** NMBS / SNCB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nmbs-sncb/id403212067?uo=4>© NMBS / SNCB</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/ef/17/d0/ef17d07a-aeaf-617b-0ca3-ebaf376829fd/mzl.nsegbuws.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715462/ea0c4a0e-7b17-11e5-9cc6-a69da6a746ff.png)

**Comment by dreamnet** [comment]
I don't do the orange part at the bottom of the original...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715462/ea0c4a0e-7b17-11e5-9cc6-a69da6a746ff.png)
https://cloud.githubusercontent.com/assets/2068130/10715462/ea0c4a0e-7b17-11e5-9cc6-a69da6a746ff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715466/f93cd638-7b17-11e5-9400-9cf8857bf48b.png

**Comment by balraj19991** [comment]
@dreamnet ok
