### ISSUE TITLE
STIB mobile

### ISSUE THREAD

**Issue by balraj19991** [glasklart/hd#6707]
**App Name:** STIB mobile
**Bundle ID:** be.stib.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432273681">432273681</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stib-mobile/id432273681?mt=8&uo=4">https://itunes.apple.com/us/app/stib-mobile/id432273681?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** STIB-MIVB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stib-mivb/id432273684?uo=4>© STIB-MIVB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/17/6e/95/176e95ac-9e41-9d22-e5eb-833413b1c6c3/mzl.lwyafllu.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715552/a6e768aa-7b1a-11e5-935e-38546f3638e3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715552/a6e768aa-7b1a-11e5-935e-38546f3638e3.png)
https://cloud.githubusercontent.com/assets/2068130/10715552/a6e768aa-7b1a-11e5-935e-38546f3638e3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715555/b49f2e2e-7b1a-11e5-9f65-100bf7fb7a37.png
