### ISSUE TITLE
スシロー

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#6708]
**App Name:** スシロー
**Bundle ID:** jp.co.akindo-sushiro.ay.sushiroApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=551682016">551682016</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sushiro/id551682016?mt=8&uo=4">https://itunes.apple.com/us/app/sushiro/id551682016?mt=8&uo=4</a>
**App Version:** 2.1.12
**Seller:** AKINDO SUSHIRO CO.,LTD.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zhu-shi-hui-sheakindosushiro/id551682020?uo=4>© 株式会社あきんどスシロー</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/56/1d/43/561d439b-9c22-58cb-32c0-80b56b7fc93f/mzl.dczigmmt.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715187/c6ecab0a-7b0c-11e5-998e-7b271ce7a4e7.png)

**Comment by jmaeshawn** [comment]
![jp co akindo-sushiro ay sushiroapp](https://cloud.githubusercontent.com/assets/6907886/10713936/91d241dc-7b16-11e5-97c1-202e3e32c336.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6907886/10713936/91d241dc-7b16-11e5-97c1-202e3e32c336.png)

**Comment by dreamnet** [comment]
@jmaeshawn Nice, but we need the [icon source file](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources).

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715187/c6ecab0a-7b0c-11e5-998e-7b271ce7a4e7.png)
https://cloud.githubusercontent.com/assets/2068130/10715187/c6ecab0a-7b0c-11e5-998e-7b271ce7a4e7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715188/d3beac20-7b0c-11e5-9a7f-a3bc50e6a016.png
