### ISSUE TITLE
Domino’s App − ドミノ・ピザのネット注文

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#6709]
**App Name:** Domino’s App − ドミノ・ピザのネット注文
**Bundle ID:** jp.dominos.DominosPizza
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=355312182">355312182</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/jp/app/dominos-app-domino-pizanonetto/id355312182?mt=8&uo=4">https://itunes.apple.com/jp/app/dominos-app-domino-pizanonetto/id355312182?mt=8&uo=4</a>
**App Version:** 9.02
**Seller:** K.K.HigaIndustries
**Developer:** <a target="_blank" href=https://itunes.apple.com/jp/developer/zhu-shi-hui-shehiga-indasutorizu/id355312185?uo=4>© 株式会社ヒガ・インダストリーズ</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/a4/99/6c/a4996cbe-e05e-aeb4-2ca5-929afb0b9243/mzl.tgacgmnt.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10714807/1aa09256-7aff-11e5-8d50-8acbf82616c2.png)

**Comment by jmaeshawn** [comment]
![jp dominos dominospizza 2x](https://cloud.githubusercontent.com/assets/6907886/10713966/a908ca0a-7b17-11e5-9f7d-c8f00ff1a395.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6907886/10713966/a908ca0a-7b17-11e5-9f7d-c8f00ff1a395.png)

**Comment by dreamnet** [comment]
@jmaeshawn Source is missing - here is a correct contribution:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10714807/1aa09256-7aff-11e5-8d50-8acbf82616c2.png)
https://cloud.githubusercontent.com/assets/2068130/10714807/1aa09256-7aff-11e5-8d50-8acbf82616c2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10714809/2b0560b8-7aff-11e5-875a-c032e75dd225.png
