### ISSUE TITLE
Back to the Future: Flux Capacitor

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#6710]
**App Name:** Back to the Future: Flux Capacitor
**Bundle ID:** com.pocketparadox.iFlux
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391862376">391862376</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/back-to-future-flux-capacitor/id391862376?mt=8&uo=4">https://itunes.apple.com/us/app/back-to-future-flux-capacitor/id391862376?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Pocket Paradox, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pocket-paradox-llc/id391862379?uo=4>© Pocket Paradox, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/37/90/af/3790af66-6215-8c23-65c1-b07909b2b66e/mzl.pyvnnpcz.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715287/aa0bf824-7b11-11e5-8f89-55643dec36f6.png)

**Comment by jmaeshawn** [comment]
![com pocketparadox iflux 2x](https://cloud.githubusercontent.com/assets/6907886/10714002/9fb305e6-7b18-11e5-946e-0cf927df4459.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6907886/10714002/9fb305e6-7b18-11e5-946e-0cf927df4459.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10715287/aa0bf824-7b11-11e5-8f89-55643dec36f6.png)
https://cloud.githubusercontent.com/assets/2068130/10715287/aa0bf824-7b11-11e5-8f89-55643dec36f6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10715290/b745eaea-7b11-11e5-9231-7744839242aa.png
