### ISSUE TITLE
iCloud Drive

### ISSUE THREAD

**Issue by balraj19991** [glasklart/hd#6711]
**App Name:** iCloud Drive
**Bundle ID:** com.apple.iCloudDriveApp
**Version:** 1.0
**iTunes ID:** none (Stock app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/10740298/c38b474e-7c21-11e5-8407-5eb2d814ad20.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10741136/7ca36424-7c26-11e5-87e0-95999511eb11.png)

**Comment by dreamnet** [comment]
@balraj19991 Oh yeah, I missed that one. I will add em.

**Comment by dreamnet** [comment]
@balraj19991 Oh yeah, I missed that one. I will add em.

**Comment by balraj19991** [comment]
@dreamnet yes

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10741136/7ca36424-7c26-11e5-87e0-95999511eb11.png)
https://cloud.githubusercontent.com/assets/2068130/10741136/7ca36424-7c26-11e5-87e0-95999511eb11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10741160/8e60bcde-7c26-11e5-9181-c4d806eca77c.png
@balraj19991 Like it?

**Comment by balraj19991** [comment]
@dreamnet Yeah, it's cool. Thanks

**Comment by dreamnet** [comment]
@balraj19991 OK, will be included in the next release.

**Comment by balraj19991** [comment]
@dreamnet Ok
