### ISSUE TITLE
Antutu Benchmark

### ISSUE THREAD

**Issue by balraj19991** [glasklart/hd#6714]
**App Name:** AnTuTu Benchmark
**Bundle ID:** com.antutu.benchmark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=803837129">803837129</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/antutu-benchmark/id803837129?mt=8&uo=4">https://itunes.apple.com/us/app/antutu-benchmark/id803837129?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** Beijing AnTuTu Technology Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/beijing-antutu-technology/id803837132?uo=4>© Beijing AnTuTu Technology Limited</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/19/4b/15/194b15a3-9f80-ddb8-042a-a383fcaf4d97/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10780367/fe963508-7d3c-11e5-8002-97940dd62548.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10780367/fe963508-7d3c-11e5-8002-97940dd62548.png)
https://cloud.githubusercontent.com/assets/2068130/10780367/fe963508-7d3c-11e5-8002-97940dd62548.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10780373/0f705462-7d3d-11e5-91e9-e7084e328ea5.png
