### ISSUE TITLE
Inside TL;DR - 24/7 Breaking News and Real-Time Video Updates

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6716]
**App Name:** Inside TL;DR - 24/7 Breaking News and Real-Time Video Updates
**Bundle ID:** com.mahalo.inside.tldr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1042749369">1042749369</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inside-tl-dr-24-7-breaking/id1042749369?mt=8&uo=4">https://itunes.apple.com/us/app/inside-tl-dr-24-7-breaking/id1042749369?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Inside.com Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/inside.com-inc./id331140855?uo=4>© Inside.com Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/1b/0b/a9/1b0ba94c-1e73-79b0-eb9f-5b3c81772854/mzl.fnqkgeda.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10922126/b17f517c-8279-11e5-992d-f6e167bd7963.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10922126/b17f517c-8279-11e5-992d-f6e167bd7963.png)
https://cloud.githubusercontent.com/assets/2068130/10922126/b17f517c-8279-11e5-992d-f6e167bd7963.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10922137/bf9eb1ee-8279-11e5-8156-dbaa938a8ca2.png
