### ISSUE TITLE
ReadyCLOUD

### ISSUE THREAD

**Issue by terryg80** [glasklart/hd#6717]
**App Name:** ReadyCLOUD
**Bundle ID:** com.netgear.ReadyCLOUD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=700730254">700730254</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/readycloud/id700730254?mt=8&uo=4">https://itunes.apple.com/us/app/readycloud/id700730254?mt=8&uo=4</a>
**App Version:** 1.5.5
**Seller:** NETGEAR, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/netgear/id394405580?uo=4>© NETGEAR</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/e4/8a/64/e48a64a1-fa20-d5b5-a607-acc257d3b683/mzl.ihcslqrj.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10805737/c06d9254-7d95-11e5-83ae-87f05a4bf135.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10805698/625b1510-7d95-11e5-8540-077e3cb4bd83.png)
https://cloud.githubusercontent.com/assets/3090247/10805698/625b1510-7d95-11e5-8540-077e3cb4bd83.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10805699/625cf218-7d95-11e5-9098-753f3c40b7fd.png
