### ISSUE TITLE
JUST EAT - Comida a domicilio

### ISSUE THREAD

**Issue by outlawesp** [glasklart/hd#6718]
**App Name:** JUST EAT - Comida a domicilio
**Bundle ID:** com.justeat.JUSTEAT.es
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=615238455">615238455</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/just-eat-comida-a-domicilio/id615238455?mt=8&uo=4">https://itunes.apple.com/es/app/just-eat-comida-a-domicilio/id615238455?mt=8&uo=4</a>
**App Version:** 2.17.0
**Seller:** Just-Eat Holdings Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/just-eat.com/id383091095?uo=4>© Just-Eat.com</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/43/ea/46/43ea46bf-3b75-08a5-4376-41a8681c5a6d/mzl.qbectqnm.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834549/82bd3ada-7e9a-11e5-822f-2a296fd4a6aa.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834549/82bd3ada-7e9a-11e5-822f-2a296fd4a6aa.png)
https://cloud.githubusercontent.com/assets/10730122/10834549/82bd3ada-7e9a-11e5-822f-2a296fd4a6aa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10834546/7e623602-7e9a-11e5-927a-a7674b5ff320.png

**Comment by dreamnet** [comment]
Same as #2080.
