### ISSUE TITLE
Mi Guía TV

### ISSUE THREAD

**Issue by outlawesp** [glasklart/hd#6719]
**App Name:** Mi Guía TV
**Bundle ID:** com.miarroba.guiatv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=933136016">933136016</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mi-guia-tv/id933136016?mt=8&uo=4">https://itunes.apple.com/us/app/mi-guia-tv/id933136016?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Miarroba Networks, S.L.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/miarroba/id933136015?uo=4>© Miarroba</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/12/87/e6/1287e6b8-3a9f-3b44-e12d-e56fdd477977/mzl.ysvngfrr.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11252696/28f1aa46-8dfd-11e5-9ee0-cd3c9269c061.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11252696/28f1aa46-8dfd-11e5-9ee0-cd3c9269c061.png)
https://cloud.githubusercontent.com/assets/3090247/11252696/28f1aa46-8dfd-11e5-9ee0-cd3c9269c061.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11252697/298c11c6-8dfd-11e5-9be6-74e4a9f5e308.png
