### ISSUE TITLE
Duolingo - Learn Languages for Free

### ISSUE THREAD

**Issue by zeppeli** [glasklart/hd#672]
**App Name:** Duolingo - Learn Languages for Free
**Bundle ID:** com.duolingo.DuolingoMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570060128">570060128</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/duolingo-learn-languages-for/id570060128?mt=8&uo=4">https://itunes.apple.com/us/app/duolingo-learn-languages-for/id570060128?mt=8&uo=4</a>
**App Version:** 4.10.4
**Seller:** Duolingo, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/duolingo/id570060151?uo=4>© Duolingo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/14/7c/1f/147c1f9d-a5f8-f3cc-5476-0f2912b2b77e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18746954/bc362622-80ca-11e6-834b-75bbf912ddbf.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18746954/bc362622-80ca-11e6-834b-75bbf912ddbf.png)
https://cloud.githubusercontent.com/assets/20930745/18746954/bc362622-80ca-11e6-834b-75bbf912ddbf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18746962/cd0333dc-80ca-11e6-892e-0c58698f49a1.png
