### ISSUE TITLE
 Radar Nomad (antes Avisador de Radares)

### ISSUE THREAD

**Issue by outlawesp** [glasklart/hd#6720]
**App Name:** Radar Nomad (antes Avisador de Radares)
**Bundle ID:** com.dgtnomad.Radares
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=435727321">435727321</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/radar-nomad-antes-avisador/id435727321?mt=8&uo=4">https://itunes.apple.com/es/app/radar-nomad-antes-avisador/id435727321?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** DIGITAL NOMAD S.L
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/digital-nomad-s.l/id430548325?uo=4>© DIGITAL NOMAD S.L</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/6f/bd/36/6fbd36bc-de23-c5ef-1398-f5d1e8f50ddc/mzl.qqyansns.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10922692/d5e5b832-827c-11e5-8e15-fff8a295cf7b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10922568/28b4b154-827c-11e5-8506-160afc3f5b2a.png)
https://cloud.githubusercontent.com/assets/2068130/10922568/28b4b154-827c-11e5-8506-160afc3f5b2a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10922581/38847754-827c-11e5-8203-677263425d38.png
