### ISSUE TITLE
No Crop - Post entire pics & videos for instagram without cropping.

### ISSUE THREAD

**Issue by outlawesp** [glasklart/hd#6721]
**App Name:** No Crop - Post entire pics & videos for instagram without cropping.
**Bundle ID:** com.rcplatform.IOSNoCrop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=878086629">878086629</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/no-crop-post-entire-pics-videos/id878086629?mt=8&uo=4">https://itunes.apple.com/us/app/no-crop-post-entire-pics-videos/id878086629?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Riley Cillian Hong Kong Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/riley-cillian-hong-kong-limited/id878086632?uo=4>© RILEY CILLIAN HONG KONG LIMITED</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/a6/b4/ca/a6b4ca5e-20a0-d650-8c41-227e47cebd8e/mzl.hxmiqyzd.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834778/a5a6dd88-7e9c-11e5-9437-7978b48b7f23.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834778/a5a6dd88-7e9c-11e5-9437-7978b48b7f23.png)
https://cloud.githubusercontent.com/assets/10730122/10834778/a5a6dd88-7e9c-11e5-9437-7978b48b7f23.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10834776/a21d8b30-7e9c-11e5-8957-4b4c9564d4c1.png
