### ISSUE TITLE
wifisfera

### ISSUE THREAD

**Issue by outlawesp** [glasklart/hd#6722]
**App Name:** wifisfera
**Bundle ID:** com.telecable.wifisfera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=890813594">890813594</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wifisfera/id890813594?mt=8&uo=4">https://itunes.apple.com/us/app/wifisfera/id890813594?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Telecable de Asturias S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/telecable-de-asturias-s.a./id582289009?uo=4>© telecable de Asturias, S.A.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/0b/df/54/0bdf5431-939c-4644-cb5d-6f5f4b2d6f61/mzl.evdvxeeo.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834589/e86a285c-7e9a-11e5-8bda-ff54676abd08.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834589/e86a285c-7e9a-11e5-8bda-ff54676abd08.png)
https://cloud.githubusercontent.com/assets/10730122/10834589/e86a285c-7e9a-11e5-8bda-ff54676abd08.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10834588/e572af02-7e9a-11e5-8101-3e91fcf81189.png
