### ISSUE TITLE
iZip Pro - Zip Unzip Unrar Tool

### ISSUE THREAD

**Issue by outlawesp** [glasklart/hd#6723]
**App Name:** iZip Pro - Zip Unzip Unrar Tool
**Bundle ID:** com.comcsoft.izippro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479665601">479665601</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/izip-pro-zip-unzip-unrar-tool/id479665601?mt=8&uo=4">https://itunes.apple.com/us/app/izip-pro-zip-unzip-unrar-tool/id479665601?mt=8&uo=4</a>
**App Version:** 8.32
**Seller:** Comc Soft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/comcsoft/id413971334?uo=4>© ComcSoft</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/ae/6b/9a/ae6b9a5c-c098-59f5-7a0f-9f050913ee5f/mzl.cwhqcpdj.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10839504/06c16ace-7ed5-11e5-9dd7-f2e9acb9507c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10839504/06c16ace-7ed5-11e5-9dd7-f2e9acb9507c.png)
https://cloud.githubusercontent.com/assets/2068130/10839504/06c16ace-7ed5-11e5-9dd7-f2e9acb9507c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10839510/15fe7fd6-7ed5-11e5-9a89-3593a5607353.png
