### ISSUE TITLE
Spreaker Radio and Podcast

### ISSUE THREAD

**Issue by outlawesp** [glasklart/hd#6724]
**App Name:** Spreaker Radio and Podcast
**Bundle ID:** com.spreaker.Spreaker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388449677">388449677</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spreaker-radio-and-podcast/id388449677?mt=8&uo=4">https://itunes.apple.com/us/app/spreaker-radio-and-podcast/id388449677?mt=8&uo=4</a>
**App Version:** 6.5.5
**Seller:** Spreaker Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/spreaker-inc./id875810732?uo=4>© Spreaker Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/16/71/64/16716429-23eb-0668-139a-af9049136406/mzl.seaymqhg.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834637/41d89efa-7e9b-11e5-9f2f-7805199b33ad.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834637/41d89efa-7e9b-11e5-9f2f-7805199b33ad.png)
https://cloud.githubusercontent.com/assets/10730122/10834637/41d89efa-7e9b-11e5-9f2f-7805199b33ad.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10834632/3824b20e-7e9b-11e5-86a8-610c41730ff0.png
