### ISSUE TITLE
iScanner Pro - Mobile PDF Scanner to Scan Documents, Receipts, Biz Cards, Books.

### ISSUE THREAD

**Issue by outlawesp** [glasklart/hd#6725]
**App Name:** iScanner Pro - Mobile PDF Scanner to Scan Documents, Receipts, Biz Cards, Books.
**Bundle ID:** net.iscannerapp.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035331258">1035331258</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iscanner-pro-mobile-pdf-scanner/id1035331258?mt=8&uo=4">https://itunes.apple.com/us/app/iscanner-pro-mobile-pdf-scanner/id1035331258?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Ascella Mobile Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ascella-apps/id1035331257?uo=4>© Ascella Apps</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/68/8a/cd/688acd40-e403-5ce2-f1e8-0adc1c52ec7f/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834737/39294d44-7e9c-11e5-9e13-c09559bcb31b.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834737/39294d44-7e9c-11e5-9e13-c09559bcb31b.png)
https://cloud.githubusercontent.com/assets/10730122/10834737/39294d44-7e9c-11e5-9e13-c09559bcb31b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10834736/362792b8-7e9c-11e5-9cb4-d60ebe8f322b.png
