### ISSUE TITLE
Mi Vodafone

### ISSUE THREAD

**Issue by outlawesp** [glasklart/hd#6726]
**App Name:** Mi Vodafone
**Bundle ID:** es.vodafone.mobile.mivodafone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=455655421">455655421</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/mi-vodafone/id455655421?mt=8&uo=4">https://itunes.apple.com/es/app/mi-vodafone/id455655421?mt=8&uo=4</a>
**App Version:** 3.5.8
**Seller:** VODAFONE ESPANA SAU
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/vodafone-espana-s.a.u/id405005629?uo=4>© Vodafone España S.A.U</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/86/83/ee/8683ee39-314f-82d4-b3eb-5be8a4e99ddc/mzl.koyuzjgi.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10838689/26b3a0d2-7eca-11e5-8ead-6213639be39f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10838689/26b3a0d2-7eca-11e5-8ead-6213639be39f.png)
https://cloud.githubusercontent.com/assets/2068130/10838689/26b3a0d2-7eca-11e5-8ead-6213639be39f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10838691/3586abea-7eca-11e5-96dd-82910f954e93.png
