### ISSUE TITLE
Beats Pill+

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6727]
**App Name:** Beats Pill+
**Bundle ID:** com.apple.bnd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1005829608">1005829608</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beats-pill+/id1005829608?mt=8&uo=4">https://itunes.apple.com/us/app/beats-pill+/id1005829608?mt=8&uo=4</a>
**App Version:** 1.0.8
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4>© Apple</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/3f/84/04/3f8404d0-0150-94e9-56d3-a3446aa57d3b/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834981/5a11fd56-7e9e-11e5-9fcc-c69bae472c56.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10834981/5a11fd56-7e9e-11e5-9fcc-c69bae472c56.png)
https://cloud.githubusercontent.com/assets/10730122/10834981/5a11fd56-7e9e-11e5-9fcc-c69bae472c56.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10834979/56ca0b7a-7e9e-11e5-9ebb-1b093c8727fa.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
