### ISSUE TITLE
Beat the Traffic

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6730]
**App Name:** Beat the Traffic
**Bundle ID:** com.travelersnetwork.travelers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=552637004">552637004</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beat-the-traffic/id552637004?mt=8&uo=4">https://itunes.apple.com/us/app/beat-the-traffic/id552637004?mt=8&uo=4</a>
**App Version:** 3.4.9
**Seller:** Pelmorex Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pelmorex-media-inc./id294356877?mt=8&uo=4>© Pelmorex Media Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/8e/95/85/8e958569-bcda-44e0-0598-89ef75ff82ef/mzl.snyrgrin.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10858947/0cce1064-7f59-11e5-86b2-2813a3338f2c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10858947/0cce1064-7f59-11e5-86b2-2813a3338f2c.png)
https://cloud.githubusercontent.com/assets/2068130/10858947/0cce1064-7f59-11e5-86b2-2813a3338f2c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10858954/209bf7b4-7f59-11e5-9073-18d39edd607c.png
