### ISSUE TITLE
Trak TV Show

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6731]
**App Name:** Trak TV Show
**Bundle ID:** com.monalisapps.traktvshow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=573307473">573307473</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trak-tv-show/id573307473?mt=8&uo=4">https://itunes.apple.com/us/app/trak-tv-show/id573307473?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Samuel Dutouquet
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/samuel-dutouquet/id573307476?uo=4>© Samuel Dutouquet</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/84/95/3b/84953b83-bd24-0248-e8cb-a8cb3c9e2c6f/mzl.trznxjyg.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10923695/c2e4180e-8282-11e5-97fe-12189f95e59f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10923695/c2e4180e-8282-11e5-97fe-12189f95e59f.png)
https://cloud.githubusercontent.com/assets/2068130/10923695/c2e4180e-8282-11e5-97fe-12189f95e59f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10923708/d258a368-8282-11e5-82e0-c3cf037d0625.png
