### ISSUE TITLE
Mercury Web Browser Pro - with powerful Ad Block extension

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6732]
**App Name:** Mercury Web Browser Pro - with powerful Ad Block extension
**Bundle ID:** com.bsn.mercurypro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1000610117">1000610117</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mercury-web-browser-pro-powerful/id1000610117?mt=8&uo=4">https://itunes.apple.com/us/app/mercury-web-browser-pro-powerful/id1000610117?mt=8&uo=4</a>
**App Version:** 10.0.1
**Seller:** Lucy Ding
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lucy-ding/id999772834?uo=4>© Lucy Ding</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/5c/f8/be/5cf8be1b-3b8f-57bc-1914-983b0647025a/mzl.yzgdkmjb.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10860255/3646ceb0-7f66-11e5-87f4-8fde67c385cb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10860255/3646ceb0-7f66-11e5-87f4-8fde67c385cb.png)
https://cloud.githubusercontent.com/assets/2068130/10860255/3646ceb0-7f66-11e5-87f4-8fde67c385cb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10860259/46238bac-7f66-11e5-85f7-897b875831c0.png
