### ISSUE TITLE
Readable

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6735]
**App Name:** Readable
**Bundle ID:** com.joindup.Readable
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=440105585">440105585</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/readable/id440105585?mt=8&uo=4">https://itunes.apple.com/us/app/readable/id440105585?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Joindup Pty. Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/joindup/id440105588?uo=4">© Joindup</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/49/58/d8/4958d8cb-33d8-ba51-c578-7a01ce63d10e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20147267/b8486108-a6a7-11e6-947c-fae14d8ba3e9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10862209/786dc4f4-7f9f-11e5-9c4a-dfb29517b0ad.png)
https://cloud.githubusercontent.com/assets/2068130/10862209/786dc4f4-7f9f-11e5-9c4a-dfb29517b0ad.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10862211/879c3050-7f9f-11e5-80a4-69a2275297fc.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Readable
**Bundle ID:** com.joindup.Readable
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=440105585">440105585</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/readable/id440105585?mt=8&uo=4">https://itunes.apple.com/us/app/readable/id440105585?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Joindup Pty. Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/joindup/id440105588?uo=4">© Joindup</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/49/58/d8/4958d8cb-33d8-ba51-c578-7a01ce63d10e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20147267/b8486108-a6a7-11e6-947c-fae14d8ba3e9.png)
https://cloud.githubusercontent.com/assets/20930745/20147267/b8486108-a6a7-11e6-947c-fae14d8ba3e9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20147308/d96c6d16-a6a7-11e6-954b-0edd8de579ae.png
