### ISSUE TITLE
Pocket Informant - Day Planner with full GTD-style Tasks

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6736]
**App Name:** Pocket Informant - Day Planner with full GTD-style Tasks
**Bundle ID:** pocketinformantiPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380732176">380732176</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-informant-day-planner/id380732176?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-informant-day-planner/id380732176?mt=8&uo=4</a>
**App Version:** 4.72
**Seller:** Web Information Solutions, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/web-information-solutions/id284945003?uo=4>© Web Information Solutions, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/9f/43/22/9f4322d1-947e-8ce0-83aa-aae89458c2af/mzl.kdqyeqex.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10872400/2a95875e-8101-11e5-920d-c38f01d9384b.png)

**Comment by JamieKnuth** [comment]
That would be me at the most important one. I have that in the dock.
Thanx in advance.

**Comment by Trubbel** [comment]
Best I could do, I'm not really satisfied how it looks like so if anyone else can make it better please do,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10872400/2a95875e-8101-11e5-920d-c38f01d9384b.png)
https://cloud.githubusercontent.com/assets/10730122/10872400/2a95875e-8101-11e5-920d-c38f01d9384b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10872398/279afed0-8101-11e5-80b6-bcd725fffc74.png

**Comment by dreamnet** [comment]
@Trubbel I think it looks nice. Good work! :+1:

**Comment by JamieKnuth** [comment]
I find that also. :+1:  Thank you. Awesome
