### ISSUE TITLE
V-Navi

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6737]
**App Name:** V-Navi
**Bundle ID:** de.mapandroute.v-navi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390428733">390428733</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/v-navi/id390428733?mt=8&uo=4">https://itunes.apple.com/us/app/v-navi/id390428733?mt=8&uo=4</a>
**App Version:** 4.0.5
**Seller:** Map and Route GmbH & Co. KG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/map-and-route-gmbh-co.-kg/id390428736?uo=4>© Map and Route GmbH & Co. KG</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/4e/0f/84/4e0f84da-db72-8f86-1262-5f60cca8f1ee/mzl.bzebepff.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10870641/f3a8c868-80cf-11e5-9168-9ba76bc4f5c0.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10866510/50fa3488-8031-11e5-9d30-620e7712922f.png)
https://cloud.githubusercontent.com/assets/10730122/10866510/50fa3488-8031-11e5-9d30-620e7712922f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10866509/4e6f41ae-8031-11e5-8e20-cca7dc488202.png

**Comment by JamieKnuth** [comment]
Thank you, Trubbel. You are my hero. :+1:

**Comment by dreamnet** [comment]
@Trubbel I think we should leave the border out for this... ?

**Comment by Trubbel** [comment]
@dreamnet,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10870641/f3a8c868-80cf-11e5-9168-9ba76bc4f5c0.png)
https://cloud.githubusercontent.com/assets/10730122/10870641/f3a8c868-80cf-11e5-9168-9ba76bc4f5c0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10870639/f0b26fd8-80cf-11e5-8d00-645bcc80d4e6.png

**Comment by dreamnet** [comment]
@Trubbel Jep, perfect. :+1:

**Comment by JamieKnuth** [comment]
yes, its better @Trubbel  :+1:
