### ISSUE TITLE
Das Telefonbuch – Branchenbuch, Dienstleistungen und lokale Auskunft für Adressen und Telefonnummern

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6738]
**App Name:** Das Telefonbuch – Branchenbuch, Dienstleistungen und lokale Auskunft für Adressen und Telefonnummern
**Bundle ID:** de.telefonbuch.Telefonbuch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=313468117">313468117</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/das-telefonbuch-branchenbuch/id313468117?mt=8&uo=4">https://itunes.apple.com/de/app/das-telefonbuch-branchenbuch/id313468117?mt=8&uo=4</a>
**App Version:** 4.80
**Seller:** Das Telefonbuch-Servicegesellschaft mbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/das-telefonbuch-servicegesellschaft/id313468120?uo=4>© Das Telefonbuch-Servicegesellschaft mbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/80/66/6d/80666d78-b250-b847-9812-5f92fc1fd207/mzl.cwzhdltd.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10862175/512c09ce-7f9e-11e5-8a6b-3b9620557f94.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10862175/512c09ce-7f9e-11e5-8a6b-3b9620557f94.png)
https://cloud.githubusercontent.com/assets/2068130/10862175/512c09ce-7f9e-11e5-8a6b-3b9620557f94.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10862178/6295c59c-7f9e-11e5-9d3e-3efc7df3a164.png

**Comment by dreamnet** [comment]
Icon is already in the repo.
