### ISSUE TITLE
UpTo Calendar - Syncs with Google Calendar, iCloud, Outlook and more

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6739]
**App Name:** UpTo Calendar - Syncs with Google Calendar, iCloud, Outlook and more
**Bundle ID:** com.upto.UpTo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504241451">504241451</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/upto-calendar-syncs-google/id504241451?mt=8&uo=4">https://itunes.apple.com/us/app/upto-calendar-syncs-google/id504241451?mt=8&uo=4</a>
**App Version:** 3.2.4
**Seller:** UpTo, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/upto-inc./id504241454?uo=4>© UpTo, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/e5/4d/ef/e54def57-05ad-803a-e2ef-fec7eedc897b/mzl.swywdlha.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10866494/8c8b092e-8030-11e5-9538-0f12fbc08177.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10866491/7dc8938e-8030-11e5-9fbe-abd7e5ed98d1.png)
https://cloud.githubusercontent.com/assets/10730122/10866491/7dc8938e-8030-11e5-9fbe-abd7e5ed98d1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10866488/7b163128-8030-11e5-8133-3e7ed881dfe4.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10866494/8c8b092e-8030-11e5-9538-0f12fbc08177.png)
https://cloud.githubusercontent.com/assets/10730122/10866494/8c8b092e-8030-11e5-9538-0f12fbc08177.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10866493/89c3ddb0-8030-11e5-93c0-059708b5b82c.png

**Comment by dreamnet** [comment]
Taking the second one...
