### ISSUE TITLE
Newsdaily - Top Headlines & Breaking News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6740]
**App Name:** Newsdaily - Top Headlines & Breaking News
**Bundle ID:** com.owletlab.Gnews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=576210200">576210200</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsdaily-top-headlines-breaking-news/id576210200?mt=8&uo=4">https://itunes.apple.com/us/app/newsdaily-top-headlines-breaking-news/id576210200?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Nobuyuki Kondo
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nobuyuki-kondo/id493867854?uo=4">© Nobuyuki Kondo</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/11/2a/b9/112ab941-9563-eb8c-614a-79918bf6db33/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29239028-7226116e-7f43-11e7-9170-ea12ae649277.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10864303/dc4f917e-7fe9-11e5-8fc7-ac6dd27d12f4.png)
https://cloud.githubusercontent.com/assets/2068130/10864303/dc4f917e-7fe9-11e5-8fc7-ac6dd27d12f4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10864304/eb565734-7fe9-11e5-814a-8c297bd6aa79.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Newsdaily - Top Headlines & Breaking News
**Bundle ID:** com.owletlab.Gnews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=576210200">576210200</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsdaily-top-headlines-breaking-news/id576210200?mt=8&uo=4">https://itunes.apple.com/us/app/newsdaily-top-headlines-breaking-news/id576210200?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Nobuyuki Kondo
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nobuyuki-kondo/id493867854?uo=4">© Nobuyuki Kondo</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/11/2a/b9/112ab941-9563-eb8c-614a-79918bf6db33/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29239028-7226116e-7f43-11e7-9170-ea12ae649277.png)
https://user-images.githubusercontent.com/2068130/29239028-7226116e-7f43-11e7-9170-ea12ae649277.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29239036-818dd5a6-7f43-11e7-98a7-0a84e9458a84.png
❓
