### ISSUE TITLE
CBS Sports

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6741]
**App Name:** CBS Sports
**Bundle ID:** H443NM7F8H.CBSSportsApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307184892">307184892</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cbs-sports/id307184892?mt=8&uo=4">https://itunes.apple.com/us/app/cbs-sports/id307184892?mt=8&uo=4</a>
**App Version:** 8.7.4
**Seller:** CBS Mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cbs-interactive/id295669712?mt=8&uo=4>© CBS Interactive</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/a4/52/5d/a4525dde-8bbf-520a-998e-37564956ec15/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12989236/d9559cb8-d104-11e5-84a2-51f7807e6ec0.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10866472/d28417a0-802f-11e5-8cd6-3820a70459a0.png)
https://cloud.githubusercontent.com/assets/10730122/10866472/d28417a0-802f-11e5-8cd6-3820a70459a0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10866471/d011f6d6-802f-11e5-8b54-4cebaf7accbe.png

**Comment by dreamnet** [comment]
@Trubbel Perfect! :+1:

**Comment by l8er4now** [comment]
Could use an update.

**App Name:** CBS Sports
**Bundle ID:** H443NM7F8H.CBSSportsApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307184892">307184892</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cbs-sports/id307184892?mt=8&uo=4">https://itunes.apple.com/us/app/cbs-sports/id307184892?mt=8&uo=4</a>
**App Version:** 8.7.4
**Seller:** CBS Mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cbs-interactive/id295669712?mt=8&uo=4>© CBS Interactive</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/a4/52/5d/a4525dde-8bbf-520a-998e-37564956ec15/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12989236/d9559cb8-d104-11e5-84a2-51f7807e6ec0.png)
https://cloud.githubusercontent.com/assets/2068130/12989236/d9559cb8-d104-11e5-84a2-51f7807e6ec0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12989250/e9d2f7c0-d104-11e5-9ca4-4ecbe96a13b2.png
