### ISSUE TITLE
Stache

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6742]
**App Name:** Stache
**Bundle ID:** com.d3i.stache-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=870671955">870671955</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stache/id870671955?mt=8&uo=4">https://itunes.apple.com/us/app/stache/id870671955?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** d3i Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/d3i-ltd/id347019675?uo=4>© d3i Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/72/91/10/7291105d-9836-1ce0-21a0-dcd0719ffb2f/mzl.sfcchtya.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10864313/6f028544-7fea-11e5-96f7-770714b7e530.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10864313/6f028544-7fea-11e5-96f7-770714b7e530.png)
https://cloud.githubusercontent.com/assets/2068130/10864313/6f028544-7fea-11e5-96f7-770714b7e530.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10864315/7f39db6a-7fea-11e5-800e-859a806d0783.png
