### ISSUE TITLE
WikiLinks 3 - Smart Wikipedia Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6743]
**App Name:** WikiLinks 3 - Smart Wikipedia Reader
**Bundle ID:** net.WikiLinks.2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=990956008">990956008</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wikilinks-3-smart-wikipedia/id990956008?mt=8&uo=4">https://itunes.apple.com/us/app/wikilinks-3-smart-wikipedia/id990956008?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Boris Conforty
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/boris-conforty/id555005653?uo=4>© Boris Conforty</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/3d/09/b5/3d09b56d-ea5e-6f2b-4336-7ac90190dd0d/mzl.ybojxynl.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10870658/5b518d06-80d0-11e5-96d2-09a2bc207812.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10866458/86959ff8-802f-11e5-91da-9e959eb82342.png)
https://cloud.githubusercontent.com/assets/10730122/10866458/86959ff8-802f-11e5-91da-9e959eb82342.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10866457/845a404a-802f-11e5-9d2c-6e43bd7e9eab.png

**Comment by dreamnet** [comment]
@Trubbel Why so small?

**Comment by Trubbel** [comment]
@dreamnet I'm not actually sure haha, and it's alright! :smile:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10870658/5b518d06-80d0-11e5-96d2-09a2bc207812.png)
https://cloud.githubusercontent.com/assets/10730122/10870658/5b518d06-80d0-11e5-96d2-09a2bc207812.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10870654/57dbaff8-80d0-11e5-9c80-397cb9bd5a72.png

**Comment by ivanov007** [comment]
I guess the bigger the better :+1:

**Comment by dreamnet** [comment]
@ivanov007 That's true! :laughing:
