### ISSUE TITLE
Tank-App ・ the modern fuel log for iPhone and iPad

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6744]
**App Name:** Tank-App ・ the modern fuel log for iPhone and iPad
**Bundle ID:** markusMueller.tank-app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514019087">514019087</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tank-app-modern-fuel-log-for/id514019087?mt=8&uo=4">https://itunes.apple.com/us/app/tank-app-modern-fuel-log-for/id514019087?mt=8&uo=4</a>
**App Version:** 1.72
**Seller:** Markus Muller
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/markus-muller/id514019150?uo=4>© Markus Müller</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/d4/0b/5f/d40b5f94-93c5-99c8-2f68-463e2ff7a744/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10871051/83f6671a-80a1-11e5-8b58-4208ccd4e177.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/10871051/83f6671a-80a1-11e5-8b58-4208ccd4e177.png)
https://cloud.githubusercontent.com/assets/3090247/10871051/83f6671a-80a1-11e5-8b58-4208ccd4e177.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/10871052/83f95c54-80a1-11e5-9fb3-f60241bd1d16.png

**Comment by JamieKnuth** [comment]
:+1:  thanx
