### ISSUE TITLE
Vodafone Kabel TV Manager

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6745]
**App Name:** Vodafone Kabel TV Manager
**Bundle ID:** com.kabeldeutschland.kdgepgiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=532675966">532675966</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vodafone-kabel-tv-manager/id532675966?mt=8&uo=4">https://itunes.apple.com/us/app/vodafone-kabel-tv-manager/id532675966?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Vodafone Kabel Deutschland GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vodafone-kabel-deutschland/id532676589?uo=4>© Vodafone Kabel Deutschland GmbH</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/34/3e/e3/343ee3bd-e754-0b1c-9393-ee08db63c312/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10866440/f790c65c-802e-11e5-963d-bfb57d15e001.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10866429/cc377e9c-802e-11e5-9c8b-e3c0dd598aa7.png)
https://cloud.githubusercontent.com/assets/10730122/10866429/cc377e9c-802e-11e5-9c8b-e3c0dd598aa7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10866428/c9969588-802e-11e5-889e-326eb3929ba5.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10866434/e6f693da-802e-11e5-81c0-cd9ecff0d2c5.png)
https://cloud.githubusercontent.com/assets/10730122/10866434/e6f693da-802e-11e5-81c0-cd9ecff0d2c5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10866433/e44aa5b8-802e-11e5-8e63-5e795d2c8b94.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10866440/f790c65c-802e-11e5-963d-bfb57d15e001.png)
https://cloud.githubusercontent.com/assets/10730122/10866440/f790c65c-802e-11e5-963d-bfb57d15e001.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10866439/f3c07194-802e-11e5-9447-dfbacf7f25a2.png

**Comment by dreamnet** [comment]
@Trubbel The last one. :+1:

**Comment by JamieKnuth** [comment]
thany, yes. The last one is the best IMHO

**Comment by dreamnet** [comment]
@JamieKnuth You can wait for the next release of Glasklart - or if you can't wait, you can [add the icon manually](https://github.com/glasklart/hd/wiki/How-to-manually-add-icons) to your device.

**Comment by JamieKnuth** [comment]
thank you so much, great :+1:
