### ISSUE TITLE
Quicken 2014/2015/2016 Money Management

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6746]
**App Name:** Quicken 2014/2015/2016 Money Management
**Bundle ID:** com.intuit.quickencompanion.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=701067522">701067522</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quicken-2014-2015-2016-money/id701067522?mt=8&uo=4">https://itunes.apple.com/us/app/quicken-2014-2015-2016-money/id701067522?mt=8&uo=4</a>
**App Version:** 4.2.2
**Seller:** Quicken Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/quicken-inc./id1071477421?uo=4>© Quicken Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/05/73/8b/05738b91-0bb8-c1d8-b0a6-4685d40d1c5e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093499/3eb2e4e4-148a-11e6-9809-a37037977e67.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10922803/97fafc52-827d-11e5-87cd-844afdbcc808.png)
https://cloud.githubusercontent.com/assets/2068130/10922803/97fafc52-827d-11e5-87cd-844afdbcc808.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10922815/a804dd20-827d-11e5-9198-9733db69a05b.png

**Comment by l8er4now** [comment]
Bit of an update needed.

**App Name:** Quicken 2014/2015/2016 Money Management
**Bundle ID:** com.intuit.quickencompanion.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=701067522">701067522</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quicken-2014-2015-2016-money/id701067522?mt=8&uo=4">https://itunes.apple.com/us/app/quicken-2014-2015-2016-money/id701067522?mt=8&uo=4</a>
**App Version:** 4.2.2
**Seller:** Quicken Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/quicken-inc./id1071477421?uo=4>© Quicken Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/05/73/8b/05738b91-0bb8-c1d8-b0a6-4685d40d1c5e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093499/3eb2e4e4-148a-11e6-9809-a37037977e67.png)
https://cloud.githubusercontent.com/assets/2068130/15093499/3eb2e4e4-148a-11e6-9809-a37037977e67.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15093500/4cff9be6-148a-11e6-9441-d633bc7fb945.png
