### ISSUE TITLE
gMusic:  a Music Player for Google

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6747]
**App Name:** gMusic:  a Music Player for Google
**Bundle ID:** com.youriisolutions.gMusic2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=708727021">708727021</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gmusic-music-player-for-google/id708727021?mt=8&uo=4">https://itunes.apple.com/us/app/gmusic-music-player-for-google/id708727021?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Interactive Innovative Solutions LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iis/id436671227?uo=4>© IIS</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/0f/09/87/0f098751-ccf9-6847-2323-9eb25f0937c5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12775749/b2e58dd2-ca50-11e5-8447-3d7ded87064d.png)

**Comment by Trubbel** [comment]
My best shot,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10900222/805a9152-81dd-11e5-8511-76ab853f0a4f.png)
https://cloud.githubusercontent.com/assets/10730122/10900222/805a9152-81dd-11e5-8511-76ab853f0a4f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10900219/7d9d2664-81dd-11e5-8f64-8013ed8c0adf.png

**Comment by dreamnet** [comment]
@Trubbel Great! :+1:

**Comment by l8er4now** [comment]
Need an update.

**App Name:** gMusic:  a Music Player for Google
**Bundle ID:** com.youriisolutions.gMusic2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=708727021">708727021</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gmusic-music-player-for-google/id708727021?mt=8&uo=4">https://itunes.apple.com/us/app/gmusic-music-player-for-google/id708727021?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Interactive Innovative Solutions LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iis/id436671227?uo=4>© IIS</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/0f/09/87/0f098751-ccf9-6847-2323-9eb25f0937c5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12775749/b2e58dd2-ca50-11e5-8447-3d7ded87064d.png)
https://cloud.githubusercontent.com/assets/2068130/12775749/b2e58dd2-ca50-11e5-8447-3d7ded87064d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12775756/c0c1f350-ca50-11e5-8af5-79b0a5d8f5cd.png
