### ISSUE TITLE
TodoMovies 4

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6748]
**App Name:** TodoMovies 4
**Bundle ID:** com.taphive.todomovies3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=792499896">792499896</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/todomovies-4/id792499896?mt=8&uo=4">https://itunes.apple.com/us/app/todomovies-4/id792499896?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** Taphive GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/taphive-gmbh/id466416247?uo=4>© Taphive GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/41/61/35/4161357c-0914-95c3-c75e-332c09c6f6d4/mzl.jpndjgap.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10901994/04a93bd8-81f8-11e5-91c6-4aadada73e48.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10901994/04a93bd8-81f8-11e5-91c6-4aadada73e48.png)
https://cloud.githubusercontent.com/assets/2068130/10901994/04a93bd8-81f8-11e5-91c6-4aadada73e48.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10901998/133a1b7c-81f8-11e5-84ff-ea138faf39c8.png
