### ISSUE TITLE
AT - Time Progress Widget(Countdown, Reminders)

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6749]
**App Name:** AT - Time Progress Widget(Countdown, Reminders)
**Bundle ID:** Favorie.At
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=976019182">976019182</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/at-time-progress-widget-countdown/id976019182?mt=8&uo=4">https://itunes.apple.com/us/app/at-time-progress-widget-countdown/id976019182?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Favorie, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/favorie-inc./id842529489?uo=4>© Favorie, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/1e/d1/83/1ed18300-4885-1d48-9faa-db9483229174/mzl.sdexdker.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10901810/811c39f2-81f5-11e5-9cb5-775d9ac3c710.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10901810/811c39f2-81f5-11e5-9cb5-775d9ac3c710.png)
https://cloud.githubusercontent.com/assets/2068130/10901810/811c39f2-81f5-11e5-9cb5-775d9ac3c710.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10901814/900a0e4e-81f5-11e5-8828-281863271d65.png
