### ISSUE TITLE
Cycloramic

### ISSUE THREAD

**Issue by kaibooger** [glasklart/hd#675]
**App Name:** Cycloramic
**Bundle ID:** com.cycloramic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=587578368">587578368</a>
**iTunes URL:** https://itunes.apple.com/us/app/cycloramic/id587578368?mt=8&uo=4
**App Version:** 4.9.1
**Seller:** Egos Ventures, Inc.
**Supported Devices:** iPadWifi, iPodTouchourthGen, iPodTouchThirdGen, iPadFourthGen, iPadThirdGen, iPodTouchFifthGen, iPadThirdGen4G, iPadMini4G, iPhone-3GS, iPhone4, iPad2Wifi, iPadFourthGen4G, iPhone4S, iPadMini, iPhone5, iPad3G, iPad23G
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/18797483/69e3db6c-81ce-11e6-8270-910c2a71990e.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18797580/de71f9fa-81ce-11e6-921b-a99b23774ceb.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18797580/de71f9fa-81ce-11e6-921b-a99b23774ceb.png)
https://cloud.githubusercontent.com/assets/2068130/18797580/de71f9fa-81ce-11e6-921b-a99b23774ceb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18797597/f09e501a-81ce-11e6-9d47-c919e3daca88.png
