### ISSUE TITLE
Optimize .png size

### ISSUE THREAD

**Issue by cj81499** [glasklart/hd#6750]
Check this out. https://www.reddit.com/r/iOSthemes/comments/3r4i7b/discussiontool_to_losslessly_optimize_png_images/

**Comment by dreamnet** [comment]
@cj81499 Glasklart icons are highly optimized. I'm running them through png optimzer from time to time.

**Comment by cj81499** [comment]
Got it. I had no idea. Keep up the great work.

**Comment by dreamnet** [comment]
@cj81499 THX! :wink: :+1:
