### ISSUE TITLE
TV Programm TV Pro: Fernsehprogramm für Spielfilm, Movie und Serien mit TV Magazin

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6751]
**App Name:** TV Programm TV Pro: Fernsehprogramm für Spielfilm, Movie und Serien mit TV Magazin
**Bundle ID:** de.livetvgmbh.tvpro2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=773206309">773206309</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tv-programm-tv-pro-fernsehprogramm/id773206309?mt=8&uo=4">https://itunes.apple.com/us/app/tv-programm-tv-pro-fernsehprogramm/id773206309?mt=8&uo=4</a>
**App Version:** 2.4.012
**Seller:** Live TV GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/live-tv-gmbh/id647275632?uo=4>© Live TV GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/2d/01/ed/2d01eda7-d265-4fba-3954-ca6b7da14cce/mzl.hizxixir.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10894581/d6c5358e-81af-11e5-8a19-ce9830718b8c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10894581/d6c5358e-81af-11e5-8a19-ce9830718b8c.png)
https://cloud.githubusercontent.com/assets/2068130/10894581/d6c5358e-81af-11e5-8a19-ce9830718b8c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10894593/e56d77cc-81af-11e5-93be-74e7abd697d5.png

**Comment by JamieKnuth** [comment]
So nice :100:

**Comment by JamieKnuth** [comment]
:+1:

**Comment by dreamnet** [comment]
@JamieKnuth Kein Problem! :wink:
