### ISSUE TITLE
Blood Pressure+Pulse Grapher Lite

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6752]
**App Name:** Blood Pressure+Pulse Grapher Lite
**Bundle ID:** de.heinz.bpChartLite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391363921">391363921</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blood-pressure+pulse-grapher/id391363921?mt=8&uo=4">https://itunes.apple.com/us/app/blood-pressure+pulse-grapher/id391363921?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** michael heinz
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/michael-heinz/id292745639?uo=4>© michael heinz</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/9a/8e/a2/9a8ea218-7c6b-cfd1-0f0e-f16e56535373/mzl.twxccect.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12064871/e0379728-afcd-11e5-8d68-a80549554dad.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12064871/e0379728-afcd-11e5-8d68-a80549554dad.png)
https://cloud.githubusercontent.com/assets/2068130/12064871/e0379728-afcd-11e5-8d68-a80549554dad.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12064877/eea95f08-afcd-11e5-8379-439ff567497d.png

**Comment by JamieKnuth** [comment]
Awesome  +1
