### ISSUE TITLE
Audio Memos Free - The Voice Recorder

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6753]
**App Name:** Audio Memos Free - The Voice Recorder
**Bundle ID:** com.imesart.AudioMemosFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=304075033">304075033</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/audio-memos-free-voice-recorder/id304075033?mt=8&uo=4">https://itunes.apple.com/us/app/audio-memos-free-voice-recorder/id304075033?mt=8&uo=4</a>
**App Version:** 4.5.2
**Seller:** Imesart S.a.r.l.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/imesart-s.a.r.l./id290160983?uo=4>© Imesart S.a.r.l.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/31/4e/29/314e2971-2dbb-b8d7-7cda-e859db9e300c/mzl.smflxbrp.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10923281/70972778-8280-11e5-833f-bf6dfabb3665.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10923281/70972778-8280-11e5-833f-bf6dfabb3665.png)
https://cloud.githubusercontent.com/assets/2068130/10923281/70972778-8280-11e5-833f-bf6dfabb3665.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10923289/7f99ffd4-8280-11e5-9aa3-cbdf933ec2ac.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10923281/70972778-8280-11e5-833f-bf6dfabb3665.png)
https://cloud.githubusercontent.com/assets/2068130/10923281/70972778-8280-11e5-833f-bf6dfabb3665.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10923289/7f99ffd4-8280-11e5-9aa3-cbdf933ec2ac.png
