### ISSUE TITLE
Fake GPS Pro

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6755]
**App Name:** Fake GPS Pro
**Bundle ID:** cn.tinyapps.XGPSPro
**Version:** 1.8
**iTunes ID:** none (Cydia app)
**Original Artwork:** 
<img src="https://cloud.githubusercontent.com/assets/2068130/10921693/45498376-8277-11e5-9520-36d34dc48270.png" width="150" height="150">
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8494466/93c3ab8a-2165-11e5-855a-c1844e480f95.png)

**Comment by dreamnet** [comment]
@boxermansr Link to the original Artwork seems to be broken.

**Comment by boxermansr** [comment]
not sure how to fix it? honestly I just pulled it off my device and attached it, if I click on it it loads on my side.

**Comment by dreamnet** [comment]
@boxermansr Hm, I don't know. Can you try it again?

**Comment by boxermansr** [comment]
![7442d7cc-822c-11e5-8c09-8a8a7dedbcd6](https://cloud.githubusercontent.com/assets/3781692/10921028/83d75f1a-8230-11e5-8568-04a08322caf0.png)

**Comment by boxermansr** [comment]
No idea if that's right, I'm thinking it isn't. If you can give me an idea of what I'm looking for, I can try to do a better job of fixing it.

**Comment by dreamnet** [comment]
@boxermansr Seems you are posting some kind of "encrypted" image, I copyed it from my Windows PC to my iPhone and back and now it is displayed correctly.
Anyway, we are usion the same icon as for #5876 for this one.

**Comment by boxermansr** [comment]
That'll work, thanks. Sorry, still getting the hang of posting "Cydia" apps.

**Comment by dreamnet** [comment]
@boxermansr Well, it's a "bit harder" than just using the crawler... :wink: Don't give up! :+1:
