### ISSUE TITLE
Toca Cars

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6757]
**App Name:** Toca Cars
**Bundle ID:** com.tocaboca.tocacars
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=689936776">689936776</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/toca-cars/id689936776?mt=8&uo=4">https://itunes.apple.com/us/app/toca-cars/id689936776?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Toca Boca AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/toca-boca-ab/id419103351?uo=4>© Toca Boca AB</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/3f/1a/33/3f1a33bb-e3a9-221a-90d7-810d255f07a9/mzl.lugfgszg.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12010928/210d743a-ac80-11e5-9eec-3c9e9605d4b6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12010928/210d743a-ac80-11e5-9eec-3c9e9605d4b6.png)
https://cloud.githubusercontent.com/assets/3090247/12010928/210d743a-ac80-11e5-9eec-3c9e9605d4b6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/12010927/20e50bee-ac80-11e5-8c74-6c75fc60cc48.png

**Comment by JamieKnuth** [comment]
So nice +1

**Comment by dreamnet** [comment]
@ivanov007 :+1:
