### ISSUE TITLE
Respring Logo

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6758]
I really dislike the new Respring logo - it's kinda clunky and I liked the old one more. So I had this idea that we could create a "full-size" image, streching the Glasklart Baseplate and placing a white Apple logo in the middle.

**It would look like this (sorry for bad quality since this is a quick mockup):**
![Preview](http://imagizer.imageshack.us/a/img633/6264/XlveQo.png)

The name would be the same (*apple-logo@2x~iphone.png* & *apple-logo-black@2x~iphone.png*) and the size would be **750x1334** for @2 and **1242x2350** for @3.

If you want to look at my end result (which is confirmed to work on my iPhone 6), you can click [here](http://imagizer.imageshack.us/a/img908/6859/oWCcfq.png).

**Comment by Trubbel** [comment]
@dreamnet I noticed a few days ago that the @3x-theme doesn't use the @2x-respring logos that are included in the theme. Usually when you have a theme that only supports @2x-icons it still uses them. Not in this case however.

@Anuskuss I wasn't really satisfied by the looks either if I'm being honest, I did something familiar as above. But as I don't really have the Glasklart baseplate style, it didn't really turn out that great and then I forgot about it.

Here's how mine looks like if you're interested,
https://cloud.githubusercontent.com/assets/10730122/10929979/32256c72-82ba-11e5-847c-798de8ade6b1.png

**Comment by dreamnet** [comment]
@Anuskuss @Trubbel I understand. I think we can do a full size respring image, I'm only a bit confused about the @3x size, shoulden't it be **1242x2208px** for @3x?
In the old times (iOS6) we used some kind of noised background, here is quickly made full size respring logo for @2x with such a background as a suggestion:
![](https://cloud.githubusercontent.com/assets/2068130/10931293/787ca6ca-82c6-11e5-97a5-fe9bfdc4406d.png)
As I sayed, this is quickly made, I have to do this again much careful, but I think that's the direction we can go.

**Comment by ivanov007** [comment]
I also noticed the boot logo changes between Space Gray and Silver phones (I think golden ones are taken as Silver since the front is white) so it might be nice have a separate logo for white and black

**Comment by Trubbel** [comment]
@dreamnet I'm sure it is **1242x2208px** for **@3x** as well, that's what I use for mine. Could you possibly give me that noised background? If you have it saved that is. I really like how it looks like and I'd like to use it until we're sure what to do about this. :smile: 

@ivanov007 You're right, they do go after the color of your phone. :smiley:

**Comment by dreamnet** [comment]
@Trubbel Here are two noised backgrounds, the first one for @2x (750x1334) and the second one for @3x (1242x2208):
https://cloud.githubusercontent.com/assets/2068130/10949091/584dde30-8331-11e5-8e50-0a498732da11.png
https://cloud.githubusercontent.com/assets/2068130/10949096/5def6afc-8331-11e5-9ce7-3121ab9e3e3d.png

**Comment by dreamnet** [comment]
@ivanov007 Yes, there are two respring files, one is called `apple-logo@2x~iphone.png` (for devices with a dark front) and one is called `apple-logo-black@2x~iphone.png` (for devices with a white front). Both have also a 3x version.
Here are the @2x originals:
![apple-logo 2x iphone](https://cloud.githubusercontent.com/assets/2068130/10955640/8e1eb8e4-8355-11e5-9364-b16de7e3a670.png) ![apple-logo-black 2x iphone](https://cloud.githubusercontent.com/assets/2068130/10955645/91cce704-8355-11e5-84d8-040915755cbc.png)
It would be nice to have different respring logos - but how to do that with the Glasklart-style?
Anyway, I made some fullscreen respring logos.
@2x:
https://cloud.githubusercontent.com/assets/2068130/10955747/67f59ede-8356-11e5-892e-51344e1b4d8d.png
@3x:
https://cloud.githubusercontent.com/assets/2068130/10955755/7492d4cc-8356-11e5-8f7b-461260a2198d.png

**Comment by Anuskuss** [comment]
I think the noise is a nice idea but how can we get it more glasklarty?

**Comment by dreamnet** [comment]
@Anuskuss What do you mean? Take a look at the two images I posted above - the Apple logo has the Glasklart style. Do you want the Glasklart style for the nosied background too? I have no idea how we should do that...

**Comment by JamieKnuth** [comment]
@dreamnet  where does one have to copy that?

**Comment by dreamnet** [comment]
@JamieKnuth To `Library/Themes/Glasklart Icons.theme/Bundles/com.apple.ProgressUI/`.
Filenames are `apple-logo@2x~iphone.png`, `apple-logo-black@2x~iphone.png` for the @2x version and `apple-logo@3x~iphone.png`, `apple-logo-black@3x~iphone.png` for the @3x version.

**Comment by JamieKnuth** [comment]
thanx @dreamnet  :+1:

**Comment by dreamnet** [comment]
Played around with the respring logos and endet up with this:
Devices with white front:
https://cloud.githubusercontent.com/assets/2068130/11014834/a8a5b07a-8547-11e5-83fc-e9bd7c4b2fce.png
https://cloud.githubusercontent.com/assets/2068130/11014837/b0cd116c-8547-11e5-83a2-883a3c9eaa20.png
Devices with black front:
https://cloud.githubusercontent.com/assets/2068130/11014839/c60a5e72-8547-11e5-860c-a8f0cca72d45.png
https://cloud.githubusercontent.com/assets/2068130/11014841/cca83132-8547-11e5-9fff-9a713e03df1f.png
Played around with some gradients to fade the noise out to the edges, but nothing looked good - so these ones are my last version for the fullscreen boot logo - if anyone can do them better, please post.

**Comment by JamieKnuth** [comment]
with me shows only a half screen :-/

**Comment by dreamnet** [comment]
OK, then we have to step back from a fullscreen boot logo to keep backwards compatibility.
@Trubbel Can you please navigate to `//System/Library/PrivateFrameworks/ProgressUI.framework/` on your device and post these two files here: `apple-logo-black@3x~iphone.png` and `apple-logo@3x~iphone.png`? THX!

**Comment by Trubbel** [comment]
@dreamnet 

`apple-logo@3x~iphone.png`
https://cloud.githubusercontent.com/assets/10730122/11016873/0ab173e4-858e-11e5-8546-9eba847df112.png

`apple-logo-black@3x~iphone.png`
https://cloud.githubusercontent.com/assets/10730122/11016875/10c56286-858e-11e5-887c-2c8977ac435c.png

**Comment by dreamnet** [comment]
@Trubbel Thanks!!

**Comment by Anuskuss** [comment]
@JamieKnuth They are describing the same problem on [reddit](https://www.reddit.com/r/iOSthemes/comments/3ejepx/tutorial_iphone_respring_logo_entire_screen/) and the recommandation is to decrease the size.

@dreamnet How about making the respring image with the logo of Glasklart? Maybe it's even time to update the Glasklart logo?

**Comment by dreamnet** [comment]
I'm currently on this one:
![apple-logo 2x iphone](https://cloud.githubusercontent.com/assets/2068130/11018878/74a534a2-85de-11e5-9901-418e2f4c2936.png) ![apple-logo 3x iphone](https://cloud.githubusercontent.com/assets/2068130/11018884/a8d0e794-85de-11e5-88c5-d7970f0bbf51.png)
Update the Glasklart logo? Hm...

**Comment by slipko** [comment]
Wait... what even is the glasklart logo?

**Comment by dreamnet** [comment]
@slipko [click](https://camo.githubusercontent.com/16ba66b147ed905caa2fc4f04497cec7f4199baf/68747470733a2f2f7365637572652e67726176617461722e636f6d2f6176617461722f35356635393537656161383064333130323038373730633035343766363830623f733d34323026643d68747470733a2f2f613234382e652e616b616d61692e6e65742f6173736574732e6769746875622e636f6d253246696d6167657325324667726176617461727325324667726176617461722d6f72672d3432302e706e67)

**Comment by lex325** [comment]
Guys help me out. I'm a glasklart user ever since it came out. Love the theme like all of us do and it keeps getting better. 

I have an iPhone 6 Plus. I was very excited to hear a glasklart respring logo was included in the theme. Problem is I have never seen the respring logo appear on my phone. Am I supposed to do something to make it appear? Sorry for the stupid question but I would like the respring logo and am so confused as to how to make it appear on my device.

**Comment by dreamnet** [comment]
@lex325 Currently, we have only [the @2x version](https://github.com/glasklart/hd/tree/master/Library/Themes/Glasklart%20Icons.theme/Bundles/com.apple.ProgressUI) of the respring logo included, but the 6 Plus needs an @3x version. So you are doing nothing wrong, we just havent included a version of the respring logo for the 6 Plus. It will be in the next release.

**Comment by lex325** [comment]
@dreamnet thanks so much for your reply. Now it makes sense! :) Looking forward to the @3x version!

**Comment by Trubbel** [comment]
@lex325 You can find the **@3x** version here,
http://glasklarthd.dreamnet.at/download.php

**Comment by lex325** [comment]
Awesome! Thanks @Trubbel. Appreciate the help!

**Comment by dreamnet** [comment]
Finally, we have the Glasklart logo back as Respring logo.
