### ISSUE TITLE
appgefahren - gratis Apps, kostenlose Spiele & App-Schnäppchen

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6759]
**App Name:** appgefahren - gratis Apps, kostenlose Spiele & App-Schnäppchen
**Bundle ID:** com.opongo.appgefahren
**iTunes ID:** 560997702
**iTunes URL:** *Deleted*
**App Version:** 5.9.8.2
**Seller:** appgefahren GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/appgefahren-gmbh/id373054427">© opongo.com GmbH & Co. KG</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s
**Original Artwork:**
<img src="http://imagizer.imageshack.us/a/img911/8776/SoInnS.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11139902/26736178-89d5-11e5-917e-1dffc8e9e7b2.png)

**Comment by Anuskuss** [comment]
This app got recently deleted, but I still use it and was able to obtain the original Artwork so it could be themed better.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11139902/26736178-89d5-11e5-917e-1dffc8e9e7b2.png)
https://cloud.githubusercontent.com/assets/2068130/11139902/26736178-89d5-11e5-917e-1dffc8e9e7b2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11139908/365e891e-89d5-11e5-9468-311f5eb9f622.png
