### ISSUE TITLE
Next Keyboard - Beautiful Themes, New Emojis & Stickers

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6760]
**App Name:** Next Keyboard - Beautiful Themes, New Emojis & Stickers
**Bundle ID:** com.tinyhearts.NextKeyboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=920592486">920592486</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/next-keyboard-beautiful-themes/id920592486?mt=8&uo=4">https://itunes.apple.com/us/app/next-keyboard-beautiful-themes/id920592486?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Tiny Hearts Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tiny-hearts-limited/id371273285?uo=4>© Tiny Hearts Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/e7/48/a9/e748a912-4984-3621-e8dd-9f0208b09df3/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10929401/4b1b2480-82b3-11e5-876f-ea1adcddbd7d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10929401/4b1b2480-82b3-11e5-876f-ea1adcddbd7d.png)
https://cloud.githubusercontent.com/assets/10730122/10929401/4b1b2480-82b3-11e5-876f-ea1adcddbd7d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10929400/487dfafe-82b3-11e5-9e72-d9495e74f948.png
