### ISSUE TITLE
DEAD TRIGGER 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6761]
**App Name:** DEAD TRIGGER 2
**Bundle ID:** com.madfingergames.deadtrigger2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=720063540">720063540</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dead-trigger-2/id720063540?mt=8&uo=4">https://itunes.apple.com/us/app/dead-trigger-2/id720063540?mt=8&uo=4</a>
**App Version:** 0.9.9
**Seller:** MADFINGER Games, a.s.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/madfinger-games-a.s./id313220894?uo=4>© MADFINGER Games, a.s.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/e6/ce/22/e6ce22a3-2f46-8d45-37d7-f071f78ee61a/mzl.fbavufhe.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10929541/14b6ad86-82b5-11e5-9fca-e65332c970a7.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10929541/14b6ad86-82b5-11e5-9fca-e65332c970a7.png)
https://cloud.githubusercontent.com/assets/10730122/10929541/14b6ad86-82b5-11e5-9fca-e65332c970a7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10929540/125a3134-82b5-11e5-9b75-ae06b7c79bc1.png
