### ISSUE TITLE
Deus Ex: The Fall

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6762]
**App Name:** Deus Ex: The Fall
**Bundle ID:** com.squareenix.dxm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=633443676">633443676</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deus-ex-the-fall/id633443676?mt=8&uo=4">https://itunes.apple.com/us/app/deus-ex-the-fall/id633443676?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** SQUARE ENIX Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/8c/fb/fe/8cfbfe51-2a8f-5f5f-8791-c3479f2f96e8/mzl.llhqmvmb.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899520/7ffb6ea8-4c07-11e6-8741-4c8d89cb9a14.png)

**Comment by Anuskuss** [comment]
![](http://cdn29.us2.fansshare.com/images/deusexthefall/logo-deus-ex-the-fall-copy-863340045.jpg)

**Comment by Anuskuss** [comment]
I would almost say use the logo, but it would be hard to read the **THE FALL** from it.

![](http://i.neoseeker.com/n/6/deus_ex_the_fall_logo.jpg)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13035796/a5a9db16-d31d-11e5-9898-616b0310ade3.png)
https://cloud.githubusercontent.com/assets/3090247/13035796/a5a9db16-d31d-11e5-9898-616b0310ade3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13035797/a5c5716e-d31d-11e5-9fb5-caf9ecbf032b.png

**Comment by Anuskuss** [comment]
Thanks for trying, but it's indeed unreadable and kinda unrecognizable.

**Comment by Anuskuss** [comment]
If noone want to take the approach, it guess we take @ivanov007's.

**Comment by Trubbel** [comment]
@Anuskuss I'm not sure we can do it any better without changing the icon itself..

**Comment by Anuskuss** [comment]
I don't think I would even look that nice if we try to recreate it, so I guess we should stick with the work mark.
