### ISSUE TITLE
FIFA 16 Ultimate Team™

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6763]
**App Name:** FIFA 16 Ultimate Team™
**Bundle ID:** com.ea.ios.fifaworld
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=940702381">940702381</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fifa-16-ultimate-team/id940702381?mt=8&uo=4">https://itunes.apple.com/us/app/fifa-16-ultimate-team/id940702381?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4>© Electronic Arts</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/b0/cc/37/b0cc3729-1504-be57-0e33-9661c856f47a/mzl.owbtvsrs.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11252515/39f4179e-8dfc-11e5-8dc0-e8dbf005b83d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11252515/39f4179e-8dfc-11e5-8dc0-e8dbf005b83d.png)
https://cloud.githubusercontent.com/assets/3090247/11252515/39f4179e-8dfc-11e5-8dc0-e8dbf005b83d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11252516/3a8d4cfc-8dfc-11e5-8290-32a5a50dbc83.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:

**Comment by Anuskuss** [comment]
I know it says *FIFA 16 ULTIMATE TEAM* but I would like it more without the **ULTIMATE TEAM** in the logo. What do you think @ivanov007?

**Comment by Trubbel** [comment]
I guess that would work since it still has **16** in it, but it's up to @ivanov007. :smiley:

**Comment by ivanov007** [comment]
sure, no problem, also maybe we need to make all fifa icons look alike

**Comment by dreamnet** [comment]
...look alike: http://glasklarthd.dreamnet.at/index.php?search=fifa

**Comment by ivanov007** [comment]
mhhh and there's the companion for 2016 #6689 so I guess is better to leave this as it is
