### ISSUE TITLE
Tomb Raider I

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6764]
**App Name:** Tomb Raider I
**Bundle ID:** com.squareenix.tombraider1classic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=663820495">663820495</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tomb-raider-i/id663820495?mt=8&uo=4">https://itunes.apple.com/us/app/tomb-raider-i/id663820495?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** SQUARE ENIX Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/97/98/33/979833a8-50c1-408c-1d42-c4536cc0c238/mzl.cewwfnuw.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11459798/2a9feed0-96df-11e5-8236-55f2f335e861.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11459798/2a9feed0-96df-11e5-8236-55f2f335e861.png)
https://cloud.githubusercontent.com/assets/2068130/11459798/2a9feed0-96df-11e5-8236-55f2f335e861.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11459800/3abf4b12-96df-11e5-9685-9e80b340cf88.png

**Comment by Anuskuss** [comment]
Better use the word mark
<img src="http://iosapphacks.com/wp-content/uploads/2013/12/tomb-raider.png" width=150>

**Comment by Anuskuss** [comment]
So we will stick with this one?

**Comment by dreamnet** [comment]
@Anuskuss Yes. Also for #7198.
