### ISSUE TITLE
Surgeon Simulator

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6765]
**App Name:** Surgeon Simulator
**Bundle ID:** com.bossastudios.ss13touch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=814977594">814977594</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/surgeon-simulator/id814977594?mt=8&uo=4">https://itunes.apple.com/us/app/surgeon-simulator/id814977594?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Bossa Studios Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bossa-studios-ltd/id595359158?uo=4>© Bossa Studios Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/46/05/29/4605296b-3294-11ce-7829-bab5be7e86aa/mzl.fcjtnvio.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10929638/592b7d1a-82b6-11e5-8554-c96aecf748c9.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10929633/47349254-82b6-11e5-86f2-19657ff7af34.png)
https://cloud.githubusercontent.com/assets/10730122/10929633/47349254-82b6-11e5-86f2-19657ff7af34.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10929630/4458a340-82b6-11e5-92f6-be2c9cac5434.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10929638/592b7d1a-82b6-11e5-8554-c96aecf748c9.png)
https://cloud.githubusercontent.com/assets/10730122/10929638/592b7d1a-82b6-11e5-8554-c96aecf748c9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10929637/56dc4f9e-82b6-11e5-901f-4b59a1e677e4.png

**Comment by dreamnet** [comment]
@Trubbel Hm, second one. :+1:
