### ISSUE TITLE
République

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6766]
**App Name:** République
**Bundle ID:** com.Camouflaj.Republique
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=687888390">687888390</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/republique/id687888390?mt=8&uo=4">https://itunes.apple.com/us/app/republique/id687888390?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Camouflaj LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/camouflaj-llc/id516813528?uo=4>© Camouflaj LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/b2/56/8c/b2568cea-03df-3f1e-7755-1865ce715df5/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11017084/83d4a8da-8594-11e5-8b20-6e409f8f96cf.png)

**Comment by Trubbel** [comment]
I'm pretty sure this icon will be very difficult to make into a Glasklart icon. What about using the games logo instead? @Anuskuss @dreamnet 

Unless someone can do it of course. :smile: 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11017084/83d4a8da-8594-11e5-8b20-6e409f8f96cf.png)
https://cloud.githubusercontent.com/assets/10730122/11017084/83d4a8da-8594-11e5-8b20-6e409f8f96cf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11017083/7e906dc8-8594-11e5-9bab-76a4978ce567.png

**Comment by Anuskuss** [comment]
The last ~10 requests I posted were pretty hard to do, but I think this is a good tradeoff :)

Now let's try [this](https://github.com/glasklart/hd/issues/6768) and [this](https://github.com/glasklart/hd/issues/6763). Good luck :smile:

I don't want to break the rule which only allows 10 request per week, but there are couple of other hard ones hehe

**Comment by dreamnet** [comment]
OK for me...
