### ISSUE TITLE
Neon Shadow

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6767]
**App Name:** Neon Shadow
**Bundle ID:** com.crescentmoongames.neonshadow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=730030512">730030512</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/neon-shadow/id730030512?mt=8&uo=4">https://itunes.apple.com/us/app/neon-shadow/id730030512?mt=8&uo=4</a>
**App Version:** 1.33
**Seller:** Crescent Moon Games LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/crescent-moon-games/id370521012?uo=4>© Crescent Moon Games</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/ce/bb/51/cebb51ab-731d-3dd9-e174-7dd312d8cadc/pr_source.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11133106/1d9f1222-8994-11e5-9194-c68e3c37cddc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11133106/1d9f1222-8994-11e5-9194-c68e3c37cddc.png)
https://cloud.githubusercontent.com/assets/2068130/11133106/1d9f1222-8994-11e5-9194-c68e3c37cddc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11133112/2d261542-8994-11e5-90ef-5f581b5cfc36.png

**Comment by Anuskuss** [comment]
Ehm

**Comment by dreamnet** [comment]
@Anuskuss Ehm? I just thought, this was (part of) the logo of this game....

**Comment by Anuskuss** [comment]
Where did you find this?

**Comment by dreamnet** [comment]
@Anuskuss [Click](https://www.google.at/search?q=Neon+Shadow&tbm=isch)

**Comment by Anuskuss** [comment]
Maybe include the wordmark aswell?

**Comment by dreamnet** [comment]
@Anuskuss Hm, no - it wold be too small...

**Comment by Trubbel** [comment]
I think this will do.
