### ISSUE TITLE
Castle of Illusion Starring Mickey Mouse

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6768]
**App Name:** Castle of Illusion Starring Mickey Mouse
**Bundle ID:** com.disney.castleofillusion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=646489967">646489967</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/castle-illusion-starring-mickey/id646489967?mt=8&uo=4">https://itunes.apple.com/us/app/castle-illusion-starring-mickey/id646489967?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Disney Electronic Content, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/disney/id284888248?mt=8&uo=4>© Disney</a>
**Supported Devices:** iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple4/v4/e9/b0/b3/e9b0b3cf-33a3-09a1-4290-945951a551b7/mzl.wkjhbprs.jpeg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11249545/181e9608-8ded-11e5-91f4-4846ca444432.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11249453/886c15da-8dec-11e5-86a3-4389e195e7be.png)
https://cloud.githubusercontent.com/assets/3090247/11249453/886c15da-8dec-11e5-86a3-4389e195e7be.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11249454/889fc4e8-8dec-11e5-9af1-3b71a8a4490a.png

**Comment by dreamnet** [comment]
@ivanov007 Yeah, great! :+1:
