### ISSUE TITLE
Peel Smart Remote & TV Guide ~ Universal Remote with Pronto hardware

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6769]
**App Name:** Peel Smart Remote & TV Guide ~ Universal Remote with Pronto hardware
**Bundle ID:** com.peel.SmartRemote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=894930703">894930703</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/peel-smart-remote-tv-guide/id894930703?mt=8&uo=4">https://itunes.apple.com/us/app/peel-smart-remote-tv-guide/id894930703?mt=8&uo=4</a>
**App Version:** 2.4.2
**Seller:** Peel Technologies, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/peel-technologies-inc./id384977373?uo=4>© Peel Technologies, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/4e/5f/b1/4e5fb1ff-a545-f120-0fb7-9a977dbdb5ec/mzl.abhxmbma.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![com peel smartremote 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10964699/ff27ce4c-83a8-11e5-9bb7-9f42083b1eaa.png)

**Comment by dreamnet** [comment]
![com peel smartremote 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10964699/ff27ce4c-83a8-11e5-9bb7-9f42083b1eaa.png)
https://cloud.githubusercontent.com/assets/2068130/10964699/ff27ce4c-83a8-11e5-9bb7-9f42083b1eaa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10964715/12986afe-83a9-11e5-8425-c59b099f3ce7.png
