### ISSUE TITLE
Pingdom

### ISSUE THREAD

**Issue by keefetang** [glasklart/hd#677]
**App Name:** Pingdom
**Bundle ID:** pingdom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=298055896">298055896</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pingdom/id298055896?mt=8&uo=4">https://itunes.apple.com/us/app/pingdom/id298055896?mt=8&uo=4</a>
**App Version:** 3.4.4
**Seller:** Pingdom AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pingdom-ab/id298055899?uo=4>© Pingdom AB</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/4d/34/95/4d3495e7-bcab-ae7f-4029-918cd305e1d8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19528296/adbcb996-962b-11e6-9c51-7c6c74944303.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19528296/adbcb996-962b-11e6-9c51-7c6c74944303.png)
https://cloud.githubusercontent.com/assets/20930745/19528296/adbcb996-962b-11e6-9c51-7c6c74944303.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19528323/c721739a-962b-11e6-9b8e-4087f83e017f.png
