### ISSUE TITLE
Parkbud - Parking & Travel Guide

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6770]
**App Name:** Parkbud - Parking & Travel Guide
**Bundle ID:** com.wunderstadt.Parkbud
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432798099">432798099</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parkbud-parking-travel-guide/id432798099?mt=8&uo=4">https://itunes.apple.com/us/app/parkbud-parking-travel-guide/id432798099?mt=8&uo=4</a>
**App Version:** 3.1.2
**Seller:** Wunderstadt GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wunderstadt-gmbh/id432773079?uo=4>© Wunderstadt GmbH</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/34/18/ef/3418ef24-7310-ba3f-c94d-7d991af9a23c/mzl.bkfebutk.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12078154/b6b49d2e-b207-11e5-8a19-a86288ca3a85.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12078154/b6b49d2e-b207-11e5-8a19-a86288ca3a85.png)
https://cloud.githubusercontent.com/assets/2068130/12078154/b6b49d2e-b207-11e5-8a19-a86288ca3a85.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12078158/c503b040-b207-11e5-8f3e-ce8da5ee670f.png

**Comment by JamieKnuth** [comment]
Good work. Thanx

**Comment by dreamnet** [comment]
@JamieKnuth :+1:
