### ISSUE TITLE
Quotes Folder

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6771]
**App Name:** Quotes Folder
**Bundle ID:** Nestor-Borgo.Quotes-Folder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478653149">478653149</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quotes-folder/id478653149?mt=8&uo=4">https://itunes.apple.com/us/app/quotes-folder/id478653149?mt=8&uo=4</a>
**App Version:** 5.7
**Seller:** Nestor Borgo
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nestor-borgo/id478653152?uo=4>© Nestor Borgo</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/fa/2d/06/fa2d06fb-d592-3a8d-fde1-b80e9758ba06/mzl.cvdckdvz.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10944031/71e12c36-8317-11e5-9158-1795828fe09d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10944031/71e12c36-8317-11e5-9158-1795828fe09d.png)
https://cloud.githubusercontent.com/assets/10730122/10944031/71e12c36-8317-11e5-9158-1795828fe09d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10944028/6f432858-8317-11e5-8608-b870d132cc06.png

**Comment by JamieKnuth** [comment]
thanx :+1:

**Comment by dreamnet** [comment]
@JamieKnuth Please don't close issues - I will do that when adding the icons to the master. THX!

**Comment by JamieKnuth** [comment]
oh, sorry

**Comment by dreamnet** [comment]
@JamieKnuth No problem - :+1:
