### ISSUE TITLE
iPeng 8 - Squeezebox Remote Control

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6772]
**App Name:** iPeng 8 - Squeezebox Remote Control
**Bundle ID:** com.penguinlovesmusic.iPeng7
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=767266886">767266886</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ipeng-8-squeezebox-remote/id767266886?mt=8&uo=4">https://itunes.apple.com/us/app/ipeng-8-squeezebox-remote/id767266886?mt=8&uo=4</a>
**App Version:** 9.0
**Seller:** Du!Business GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/penguinlovesmusic.com/id296941579?uo=4>© PenguinLovesMusic.com</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/c6/19/40/c6194031-3e79-ef08-8128-d23d5bca41b0/mzl.phidbfhb.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068964/11001377/e82f455e-8474-11e5-889a-42945670356f.png)

**Comment by slipko** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068964/11001377/e82f455e-8474-11e5-889a-42945670356f.png)

Source: https://cloud.githubusercontent.com/assets/2068964/11001377/e82f455e-8474-11e5-889a-42945670356f.png

**Comment by dreamnet** [comment]
@slipko :+1:
