### ISSUE TITLE
Mobiler Mwst-Rechner

### ISSUE THREAD

**Issue by JamieKnuth** [glasklart/hd#6773]
**App Name:** Mobiler Mwst-Rechner
**Bundle ID:** com.tfnetwork.mwstrechner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375350555">375350555</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/mobiler-mwst-rechner/id375350555?mt=8&uo=4">https://itunes.apple.com/de/app/mobiler-mwst-rechner/id375350555?mt=8&uo=4</a>
**App Version:** 4.9
**Seller:** Jens Dutzi
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/jens-dutzi/id375350558?uo=4>© Jens Dutzi</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/77/72/5a/77725a16-7285-760a-5658-b754046cea91/mzl.xttuzizn.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11459306/eeb98ef4-96d3-11e5-9cbf-93d2eddc0082.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11459306/eeb98ef4-96d3-11e5-9cbf-93d2eddc0082.png)
https://cloud.githubusercontent.com/assets/2068130/11459306/eeb98ef4-96d3-11e5-9cbf-93d2eddc0082.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11459315/fc38cc0c-96d3-11e5-8e4e-d0e991d233fe.png

**Comment by JamieKnuth** [comment]
Fine, thanx. :+1:
