### ISSUE TITLE
Appster

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6774]
**App Name:**  Appster
**Bundle ID:** com.jake0oo0.appster
**Version:** 1.0
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/3781692/10979639/c437f0de-83ba-11e5-92ed-fa85109908cc.png" width="150" height="150">
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10980543/c7c39b48-8402-11e5-829c-900defbb1761.png)

**Comment by boxermansr** [comment]
I'm hoping I got this one right. *fingers crossed*

**Comment by Trubbel** [comment]
@boxermansr Everything looks alright. :wink: 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10980543/c7c39b48-8402-11e5-829c-900defbb1761.png)
https://cloud.githubusercontent.com/assets/10730122/10980543/c7c39b48-8402-11e5-829c-900defbb1761.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10980541/c59a1f4a-8402-11e5-8814-095ec2bebf99.png

**Comment by boxermansr** [comment]
Awesome, I'm learning. Next step figuring out how to make the icons myself, that way I can do the entire process :)

Thanks.

**Comment by Trubbel** [comment]
@boxermansr I'm sure you'll figure out in no-time. :smile: Thanks for letting me know about this application though haha.

**Comment by boxermansr** [comment]
No sweat, was looking for an alternative or similar to Appinfo, and came across this; hopefully it will help others out as well.
