### ISSUE TITLE
Mobiloil Credit Union Mobile Application

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#6777]
**App Name:** Mobiloil Credit Union Mobile Application
**Bundle ID:** com.mobiloilmobile.MobilOil
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=764092332">764092332</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobiloil-credit-union-mobile/id764092332?mt=8&uo=4">https://itunes.apple.com/us/app/mobiloil-credit-union-mobile/id764092332?mt=8&uo=4</a>
**App Version:** 2.5.80000
**Seller:** MOBILOIL FEDERAL CREDIT UNION INC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobiloil-cu/id764092335?uo=4>© Mobiloil CU</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/a2/5c/fa/a25cfa1e-ffa0-8414-e209-706766248008/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068964/11001119/90c3b8f0-8473-11e5-89cd-f99a03a3eb76.png)

**Comment by slipko** [comment]
Its been a long time since creating an icon.... lets see if I'm doing things right

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068964/11001119/90c3b8f0-8473-11e5-89cd-f99a03a3eb76.png)

**Comment by Trubbel** [comment]
@slipko Looks good, however the source is wrong.
Have a look here how the [icon sources](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources) are supposed to be like. :wink:

**Comment by slipko** [comment]
@Trubbel oh crap... i don't know how to do this. I remember this is why i stopped contributing when this first started up a while back. Investigation time

**Comment by Trubbel** [comment]
@slipko The source image should be **1024x1024px** and you basically have to upscale the image so it look something like this,

https://cloud.githubusercontent.com/assets/10730122/11003903/92d95d38-84b5-11e5-9162-efbb6b8b954d.png

Image itself should be black and the background should always be transparent.

**Comment by slipko** [comment]
@Trubbel  
So i can just color it black, but how do i upscale to 1024x1024 without making it all grainy?

**Comment by ivanov007** [comment]
@slipko when you make the icon you start with the 1024x1024 source, so you just need to upscale a little, you can do this with the transform tool, well assuming you are not working with shapes, if you are working with shapes you do can resize it from 78x78 to 1024x1024 without loosing quality

**Comment by slipko** [comment]
The iTunes data crawler tool doesn't have the 1024x1024 px image. I'd have to pull that from the app folder, right? @ivanov007

**Comment by ivanov007** [comment]
ok, in some cases, like this one you will have a 512x512 icon, yo can resize it to 1024x1024 and photoshop will "fix" some of the pixelated parts, then you can work on the 1024x1024 image and save the source in black with transparent background
