### ISSUE TITLE
CalorieKing Food Search

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#6779]
**App Name:** CalorieKing Food Search
**Bundle ID:** com.calorieking.iphone.calorie.counter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454930992">454930992</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calorieking-food-search/id454930992?mt=8&uo=4">https://itunes.apple.com/us/app/calorieking-food-search/id454930992?mt=8&uo=4</a>
**App Version:** 1.6.4
**Seller:** CalorieKing Wellness Solutions
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/calorieking/id454930995?uo=4>© CalorieKing</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/11/32/f3/1132f3a7-0eb2-7da0-cd84-9b5586f83668/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11075944/3c90a3c8-87f8-11e5-9673-37c7aa108fc1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11075944/3c90a3c8-87f8-11e5-9673-37c7aa108fc1.png)
https://cloud.githubusercontent.com/assets/2068130/11075944/3c90a3c8-87f8-11e5-9673-37c7aa108fc1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11075950/4b31aefe-87f8-11e5-937c-be4b89ff6a6e.png
