### ISSUE TITLE
Jelly Defense

### ISSUE THREAD

**Issue by keefetang** [glasklart/hd#678]
**App Name:** Jelly Defense
**Bundle ID:** pl.idreams.JellyDefence
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=436134867">436134867</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jelly-defense/id436134867?mt=8&uo=4">https://itunes.apple.com/us/app/jelly-defense/id436134867?mt=8&uo=4</a>
**App Version:** 1.21
**Seller:** Infinite Dreams
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/infinite-dreams-inc./id306712040?uo=4">© Infinite Dreams Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/92/f9/e0/92f9e03a-9983-a6d5-14a1-ddd6cef2d1db/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19935196/792ccfba-a119-11e6-9255-584cfe37eeca.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19935196/792ccfba-a119-11e6-9255-584cfe37eeca.png)
https://cloud.githubusercontent.com/assets/20930745/19935196/792ccfba-a119-11e6-9255-584cfe37eeca.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19935250/9f91095a-a119-11e6-83f7-c742fcefec81.png
