### ISSUE TITLE
Emojify - Turn Pixels into Emoji Emoticons to make Unique Art Images

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6784]
**App Name:** Emojify - Turn Pixels into Emoji Emoticons to make Unique Art Images
**Bundle ID:** co.voidworks.Emojify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=643521576">643521576</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/emojify-turn-pixels-into-emoji/id643521576?mt=8&uo=4">https://itunes.apple.com/us/app/emojify-turn-pixels-into-emoji/id643521576?mt=8&uo=4</a>
**App Version:** 1.51
**Seller:** VoidWorks Pte. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/voidworks/id643521579?uo=4>© VoidWorks</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/28/8c/8d/288c8dee-1e29-6b47-fec1-f852323ba601/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11139580/b0c01eb0-89d1-11e5-8444-9814ead4156f.png)

**Comment by Trubbel** [comment]
Eehh..

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11012889/f99ffec8-84fb-11e5-9657-459de6575a60.png)
https://cloud.githubusercontent.com/assets/10730122/11012889/f99ffec8-84fb-11e5-9657-459de6575a60.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11012888/f5d417b6-84fb-11e5-8f81-5614634beaa4.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11139580/b0c01eb0-89d1-11e5-8444-9814ead4156f.png)
https://cloud.githubusercontent.com/assets/2068130/11139580/b0c01eb0-89d1-11e5-8444-9814ead4156f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11139589/c02611d4-89d1-11e5-939a-370061760465.png

**Comment by Trubbel** [comment]
@dreamnet Much better!
