### ISSUE TITLE
AppCake 5

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#6785]
**App Name:** AppCake
**Bundle ID:** com.iphonecake.appcake2
**Version:** 5.5.1.2
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/7157389/17686100/eda8288c-6369-11e6-8868-1e1f75442428.PNG" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17707508/09939460-63e1-11e6-8afa-c23e206e87be.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11014465/e20e8f78-8536-11e5-8ddf-45b5b9e74d0c.png)
https://cloud.githubusercontent.com/assets/2068130/11014465/e20e8f78-8536-11e5-8ddf-45b5b9e74d0c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11014466/f03d40bc-8536-11e5-9963-75fd3bf25081.png

**Comment by grkka** [comment]
Hi, I think they've changed the icon Appcake, but not apply an update of Cydia apps. Thank you.

**Comment by dreamnet** [comment]
@grkka Please post the new icon.

**Comment by grkka** [comment]
@dreamnet Sorry, just update Appcake on the iPhone with Glasklart and does not need updating. He had done on the iPad I use another theme and there if needed update. Thank you.

**Comment by Anuskuss** [comment]
I like the old icon more but here is the new one;
<img src="https://cloud.githubusercontent.com/assets/7157389/17686100/eda8288c-6369-11e6-8868-1e1f75442428.PNG" width="150" height="150" />

Also it's not in beta anymore.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17707508/09939460-63e1-11e6-8afa-c23e206e87be.png)
https://cloud.githubusercontent.com/assets/10730122/17707508/09939460-63e1-11e6-8afa-c23e206e87be.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17707509/0993c26e-63e1-11e6-8c91-3902b7c7eab8.png
