### ISSUE TITLE
Reflect Mirror Camera

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#6786]
**App Name:** Reflect Mirror Camera
**Bundle ID:** com.brainfevermedia.reflect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=898143628">898143628</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reflect-mirror-camera/id898143628?mt=8&uo=4">https://itunes.apple.com/us/app/reflect-mirror-camera/id898143628?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** James Grote
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brainfevermedia/id338517204?uo=4>© BrainFeverMedia</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/7a/9b/fa/7a9bfa63-922b-46c9-c469-9f7299c9fc67/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11018949/f22ae6a8-85e1-11e5-9c5b-233728f6550d.png)

**Comment by slipko** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068964/11016388/3e0ae508-854e-11e5-95fd-e8ebebb18460.png)
https://cloud.githubusercontent.com/assets/2068964/11016388/3e0ae508-854e-11e5-95fd-e8ebebb18460.png

Source: https://cloud.githubusercontent.com/assets/2068964/11016390/45ab9c76-854e-11e5-8e6d-6649686bc191.png

**Comment by dreamnet** [comment]
@slipko :+1:

**Comment by slipko** [comment]
@dreamnet Is there a proper way to paste in the object or upscale without losing quality? As of right now I'm just copying the selection from the stock iTunes artwork (after making it solid black) then resizing.

**Comment by dreamnet** [comment]
@slipko As far as I know not - you are always losing quality when upscaling a pixel image. I am using Illustrator for the sources, making vector graphics, so I can scale them without losing quality.

**Comment by Trubbel** [comment]
I use Photoshop most of the time, and when I upscale images I use Ctrl + T and then hold Shift while resizing it. Doing that it doesn't lose much quality.

**Comment by ivanov007** [comment]
@Trubbel upscaling from 78x78 to 1024x1024 always will loose quality, maybe in this icon in particular not that much but in other more detailed you will notice it, as for the vectors photoshop also can handle them as shapes

**Comment by slipko** [comment]
I usually do what @trubbel does. How can I convert pixel to vector?

**Comment by ivanov007** [comment]
there are 2 methods I know

1. With [pen tool] (https://www.youtube.com/watch?v=PVfoMaUk7K8) alone (for this icon works just great)
2. [Making work path] (https://www.youtube.com/watch?v=3Z1nDXM1kQA)

Or you can use Illustrator, is almost the same, just the tools change a little, the downside is that you need photoshop at the end for the layer style
