### ISSUE TITLE
Matter - Add 3D Objects to Photos

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#6787]
**App Name:** Matter - Add 3D Objects to Photos
**Bundle ID:** com.pixite.Matter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=897754160">897754160</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/matter-add-3d-objects-to-photos/id897754160?mt=8&uo=4">https://itunes.apple.com/us/app/matter-add-3d-objects-to-photos/id897754160?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Pixite LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pixite-llc/id285719021?mt=8&uo=4>© Pixite LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/4c/c5/b7/4cc5b75e-95da-805c-f79d-4e3eba0b78cb/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11075746/3b936934-87f7-11e5-9c1b-417a8cc349b7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11075746/3b936934-87f7-11e5-9c1b-417a8cc349b7.png)
https://cloud.githubusercontent.com/assets/2068130/11075746/3b936934-87f7-11e5-9c1b-417a8cc349b7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11075755/4a008060-87f7-11e5-8901-478ea123646a.png
