### ISSUE TITLE
iCalendar Widget - timeline view of iPhone calendar events in notification center

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6789]
**App Name:** iCalendar Widget - timeline view of iPhone calendar events in notification center
**Bundle ID:** com.CraterTechLLC.CalView
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1048513780">1048513780</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/icalendar-widget-timeline/id1048513780?mt=8&uo=4">https://itunes.apple.com/us/app/icalendar-widget-timeline/id1048513780?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Crater Tech LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/crater-tech-llc/id596227696?uo=4>© Crater Tech LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/f8/9e/be/f89ebe51-5259-0e8f-622f-d0d8467e7d6a/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11021387/226a4026-8640-11e5-8a65-c0d259afb2f6.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11021387/226a4026-8640-11e5-8a65-c0d259afb2f6.png)
https://cloud.githubusercontent.com/assets/10730122/11021387/226a4026-8640-11e5-8a65-c0d259afb2f6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11021386/1f73a0d8-8640-11e5-973d-d1ed3bf495e8.png
