### ISSUE TITLE
Tweetings for Twitter (iPhone & iPod touch edition)

### ISSUE THREAD

**Issue by puschelinka** [glasklart/hd#6790]
**App Name:** Tweetings for Twitter (iPhone & iPod touch edition)
**Bundle ID:** net.tweetings.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=705350439">705350439</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tweetings-for-twitter-iphone/id705350439?mt=8&uo=4">https://itunes.apple.com/us/app/tweetings-for-twitter-iphone/id705350439?mt=8&uo=4</a>
**App Version:** 2.17.0
**Seller:** Richard Hyland
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dw-design/id286362413?uo=4>© DW:design</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/26/6f/55/266f556b-9b2e-61b2-1e05-fb0689e77805/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11048320/d3ad47ea-86fc-11e5-9833-984f7a62d0f3.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11048320/d3ad47ea-86fc-11e5-9833-984f7a62d0f3.png)
https://cloud.githubusercontent.com/assets/3090247/11048320/d3ad47ea-86fc-11e5-9833-984f7a62d0f3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11048321/d3b58324-86fc-11e5-81b9-9839b9ca6f97.png
