### ISSUE TITLE
Metapho - Check and remove exif metadata, edit geotag

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#6793]
**App Name:** Metapho - Check and remove exif metadata, edit geotag
**Bundle ID:** com.zininworks.Metapho
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914457352">914457352</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/metapho-check-remove-exif/id914457352?mt=8&uo=4">https://itunes.apple.com/us/app/metapho-check-remove-exif/id914457352?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Zininworks Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zininworks-inc./id431572491?uo=4>© Zininworks Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/96/2e/c1/962ec12a-0de8-9936-654a-521c32fdd7a8/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11131170/96fc075c-8989-11e5-90ce-5e7fa20e3d82.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11104284/5d48c600-888d-11e5-8111-562cc904b135.png)
https://cloud.githubusercontent.com/assets/3090247/11104284/5d48c600-888d-11e5-8111-562cc904b135.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11104285/5dc50210-888d-11e5-82fe-f1afc99b3bdf.png

**Comment by dreamnet** [comment]
A bit overworked:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11131170/96fc075c-8989-11e5-90ce-5e7fa20e3d82.png)
https://cloud.githubusercontent.com/assets/2068130/11131170/96fc075c-8989-11e5-90ce-5e7fa20e3d82.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11131177/a5214978-8989-11e5-8599-78648d8c34b4.png
