### ISSUE TITLE
Socialcast

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6794]
**App Name:** Socialcast
**Bundle ID:** com.socialcast.Socialcast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=334178538">334178538</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/socialcast/id334178538?mt=8&uo=4">https://itunes.apple.com/us/app/socialcast/id334178538?mt=8&uo=4</a>
**App Version:** 3.6.3
**Seller:** VMware, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vmware-inc./id395862876?uo=4>© VMware, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/57/d8/62/57d8629c-08f5-df75-8b5b-6bd80a9d53b1/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11067129/5bf1b8f6-87cb-11e5-9dad-daaf39e3b782.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11067129/5bf1b8f6-87cb-11e5-9dad-daaf39e3b782.png)
https://cloud.githubusercontent.com/assets/2068130/11067129/5bf1b8f6-87cb-11e5-9dad-daaf39e3b782.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11067139/6a96d9ea-87cb-11e5-9efc-144dc1194314.png
