### ISSUE TITLE
Firefox: Private, Safe Browser

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6797]
**App Name:** Firefox: Private, Safe Browser
**Bundle ID:** org.mozilla.ios.Firefox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989804926">989804926</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/firefox-private-safe-browser/id989804926?uo=4">https://apps.apple.com/us/app/firefox-private-safe-browser/id989804926?uo=4</a>
**App Version:** 22.0
**Seller:** Mozilla Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mozilla/id380366936?uo=4">© Mozilla</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/4a/0f/24/4a0f2475-233c-df2b-8893-ee545091f161/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by JamieKnuth** [comment]
Oh cool

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11132307/931802b6-898f-11e5-82a1-996aec5f7f13.png)
https://cloud.githubusercontent.com/assets/2068130/11132307/931802b6-898f-11e5-82a1-996aec5f7f13.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11132322/a4caeb9a-898f-11e5-90a1-ae8328308ed0.png

**Comment by ivanov007** [comment]
:sparkles::astonished::sparkles: at last the wait is over, I really tough this day will never come

**Comment by dreamnet** [comment]
@ivanov007 You mean Firefox for iOS? Yeah, really nice.

**Comment by ivanov007** [comment]
@dreamnet yes I just noticed it's on the app store because of this issue :smile:

**Comment by Christian9901** [comment]
update

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Firefox: Private, Safe Browser
**Bundle ID:** org.mozilla.ios.Firefox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989804926">989804926</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/firefox-private-safe-browser/id989804926?uo=4">https://apps.apple.com/us/app/firefox-private-safe-browser/id989804926?uo=4</a>
**App Version:** 22.0
**Seller:** Mozilla Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mozilla/id380366936?uo=4">© Mozilla</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/4a/0f/24/4a0f2475-233c-df2b-8893-ee545091f161/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
❓ 
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74592670-d8d2ea00-5023-11ea-8f82-4d889a62a6d2.png)
https://user-images.githubusercontent.com/2068130/74592670-d8d2ea00-5023-11ea-8f82-4d889a62a6d2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/74592677-eee0aa80-5023-11ea-8dae-4f52cd785177.png
