### ISSUE TITLE
ParcelTrack - Delivery Tracking for Fedex, UPS, DHL, USPS, OnTrac, Lasership, Landmark and many more

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#6798]
**App Name:** ParcelTrack - Delivery Tracking for Fedex, UPS, DHL, USPS, OnTrac, Lasership, Landmark and many more
**Bundle ID:** com.uberblic.ParcelTrack
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=840216376">840216376</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parceltrack-delivery-tracking/id840216376?mt=8&uo=4">https://itunes.apple.com/us/app/parceltrack-delivery-tracking/id840216376?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Uberblic Labs GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/uberblic-labs/id494535749?uo=4>© Uberblic Labs</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/eb/a4/d3/eba4d3ef-6d67-d0ca-5437-78db7856623e/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11130762/16cf2de0-8987-11e5-85a7-e751a468e8dc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11130762/16cf2de0-8987-11e5-85a7-e751a468e8dc.png)
https://cloud.githubusercontent.com/assets/2068130/11130762/16cf2de0-8987-11e5-85a7-e751a468e8dc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11130775/24f972b8-8987-11e5-978d-878476a1937f.png
