### ISSUE TITLE
CASIO WATCH+

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#6799]
**App Name:** CASIO WATCH+
**Bundle ID:** com.casio.watch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=760165998">760165998</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/casio-watch+/id760165998?mt=8&uo=4">https://itunes.apple.com/us/app/casio-watch+/id760165998?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** CASIO COMPUTER CO., LTD.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/casio-computer-co.-ltd./id456569836?uo=4>© CASIO COMPUTER CO., LTD.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/b4/af/4f/b4af4f02-ecb4-c9e9-3177-2f5c25c45fd1/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11131742/72525458-898c-11e5-8333-caf0d4ee6436.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11131742/72525458-898c-11e5-8333-caf0d4ee6436.png)
https://cloud.githubusercontent.com/assets/2068130/11131742/72525458-898c-11e5-8333-caf0d4ee6436.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11131753/80b8b974-898c-11e5-9fe8-7236c814520b.png
