### ISSUE TITLE
Jetpack Joyride

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#68]
**App Name:** Jetpack Joyride
**Bundle ID:** com.halfbrick.jetpack
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=457446957">457446957</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jetpack-joyride/id457446957?mt=8&uo=4">https://itunes.apple.com/us/app/jetpack-joyride/id457446957?mt=8&uo=4</a>
**App Version:** 1.9.12
**Seller:** Halfbrick
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/halfbrick-studios/id356994313?uo=4>© Halfbrick Studios</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/4d/2e/ee/4d2eeef8-7d87-8215-b7c2-b429fab68629/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19143760/41eac53a-8ba6-11e6-82e1-99ac2fddacf0.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by LaCh0uine** [comment]
icon have updated too

**Comment by dreamnet** [comment]
Icon have updated again.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19012599/b25b5202-87ba-11e6-8160-0a089100951f.png)
https://cloud.githubusercontent.com/assets/2068130/19012599/b25b5202-87ba-11e6-8160-0a089100951f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19012602/c0b25cba-87ba-11e6-830c-2660826e8422.png

**Comment by ivanov007** [comment]
he looks like a little boy without the beard... just a thought

**Comment by dreamnet** [comment]
@ivanov007 Yes, but the icon looks cleaner.

**Comment by dreamnet** [comment]
On second thought, I added the beard...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19143760/41eac53a-8ba6-11e6-82e1-99ac2fddacf0.png)
https://cloud.githubusercontent.com/assets/2068130/19143760/41eac53a-8ba6-11e6-82e1-99ac2fddacf0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19143771/4fe3db18-8ba6-11e6-8246-f9f370dbe1c3.png
