### ISSUE TITLE
bigstopwatch

### ISSUE THREAD

**Issue by keefetang** [glasklart/hd#680]
**App Name:** bigstopwatch
**Bundle ID:** jp.objective-audio.bigstopwatch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=301615836">301615836</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bigstopwatch/id301615836?mt=8&uo=4">https://itunes.apple.com/us/app/bigstopwatch/id301615836?mt=8&uo=4</a>
**App Version:** 2.5.2
**Seller:** Yuki Yasoshima
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yuki-yasoshima/id286550473?uo=4">© Yuki Yasoshima</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/c8/b1/4a/c8b14a1c-fd36-9de6-868f-e62dd5cc47a6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19934770/247b800c-a118-11e6-9728-9dc80540ab66.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19934770/247b800c-a118-11e6-9728-9dc80540ab66.png)
https://cloud.githubusercontent.com/assets/20930745/19934770/247b800c-a118-11e6-9728-9dc80540ab66.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19934795/392ae808-a118-11e6-9238-5a4c9df160c5.png
