### ISSUE TITLE
oh my giraffe

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6801]
**App Name:** oh my giraffe
**Bundle ID:** com.kneeko.oh-my-giraffe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=941920716">941920716</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/oh-my-giraffe/id941920716?mt=8&uo=4">https://itunes.apple.com/us/app/oh-my-giraffe/id941920716?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Nico Prins
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nico-prins/id941920715?uo=4>© Nico Prins</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/50/e2/81/50e2810f-8242-83c2-6acb-02df9186a84d/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11170817/f29bfa7e-8bdf-11e5-9a09-85f14f59d265.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11170817/f29bfa7e-8bdf-11e5-9a09-85f14f59d265.png)
https://cloud.githubusercontent.com/assets/2068130/11170817/f29bfa7e-8bdf-11e5-9a09-85f14f59d265.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11170819/0132e584-8be0-11e5-833e-93fbdb13ded5.png
