### ISSUE TITLE
rop

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6802]
**App Name:** rop
**Bundle ID:** com.mildmania.rop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=970421850">970421850</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rop/id970421850?mt=8&uo=4">https://itunes.apple.com/us/app/rop/id970421850?mt=8&uo=4</a>
**App Version:** 3
**Seller:** MILDMANIA OYUN BILISIM LTD STI
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mildmania/id695042839?uo=4>© MildMania</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/1c/14/0c/1c140cdf-1217-5a5f-a951-16a7a4bf1e97/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11171005/a8a5b7f2-8be4-11e5-9e8b-f9896d0b5b44.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11171005/a8a5b7f2-8be4-11e5-9e8b-f9896d0b5b44.png)
https://cloud.githubusercontent.com/assets/2068130/11171005/a8a5b7f2-8be4-11e5-9e8b-f9896d0b5b44.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11171006/b729d1fa-8be4-11e5-9dcd-e562181a1157.png

**Comment by ivanov007** [comment]
@dreamnet great :+1:
