### ISSUE TITLE
Greenfly

### ISSUE THREAD

**Issue by Meyers09** [glasklart/hd#6803]
**App Name:** Greenfly
**Bundle ID:** com.greenflydigital.myGFapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=819013595">819013595</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/greenfly/id819013595?mt=8&uo=4">https://itunes.apple.com/us/app/greenfly/id819013595?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Greenfly Digital, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/greenfly-digital-llc/id819013598?uo=4>© Greenfly Digital, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/72/36/95/72369528-41b6-2a12-65ce-07215d06cc2c/source/512x512bb.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068964/11168803/3d22f060-8b6e-11e5-9a43-d12be6bba4d3.png)

**Comment by slipko** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068964/11168803/3d22f060-8b6e-11e5-9a43-d12be6bba4d3.png)
https://cloud.githubusercontent.com/assets/2068964/11168803/3d22f060-8b6e-11e5-9a43-d12be6bba4d3.png

Source: https://cloud.githubusercontent.com/assets/2068964/11168809/a972cf74-8b6e-11e5-80e7-e8cca9e4a0a4.png

**Comment by dreamnet** [comment]
@slipko Looks fine! :+1:

**Comment by ivanov007** [comment]
@slipko hey you got the hang of it :+1:
