### ISSUE TITLE
Pokémon Shuffle Mobile

### ISSUE THREAD

**Issue by Meyers09** [glasklart/hd#6804]
**App Name:** Pokémon Shuffle Mobile
**Bundle ID:** jp.pokemon.poketoru
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1014919815">1014919815</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pokemon-shuffle-mobile/id1014919815?mt=8&uo=4">https://itunes.apple.com/us/app/pokemon-shuffle-mobile/id1014919815?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** The Pokemon Company
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/the-pokemon-company/id446737235?uo=4>© The Pokemon Company</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/19/ab/38/19ab3886-6e68-1520-1f80-7346d9b27025/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11257490/684c631a-8e17-11e5-91ea-8ec160037a52.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11257490/684c631a-8e17-11e5-91ea-8ec160037a52.png)
https://cloud.githubusercontent.com/assets/3090247/11257490/684c631a-8e17-11e5-91ea-8ec160037a52.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11257489/6812d7d0-8e17-11e5-8363-8b95a6ad0f5d.png
