### ISSUE TITLE
Desert Golfing

### ISSUE THREAD

**Issue by Meyers09** [glasklart/hd#6805]
**App Name:** Desert Golfing
**Bundle ID:** com.captain-games.desertgolf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=902062673">902062673</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/desert-golfing/id902062673?mt=8&uo=4">https://itunes.apple.com/us/app/desert-golfing/id902062673?mt=8&uo=4</a>
**App Version:** 1.11
**Seller:** Blinkbat Games
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/blinkbat-games/id321414906?uo=4>© Blinkbat Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/3f/6c/70/3f6c70d1-4d3f-33da-1b7d-b9b9deb4cae1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458773/366503e4-96c7-11e5-9029-711195881301.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458773/366503e4-96c7-11e5-9029-711195881301.png)
https://cloud.githubusercontent.com/assets/2068130/11458773/366503e4-96c7-11e5-9029-711195881301.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11458776/4507fa50-96c7-11e5-8576-0bfa4c052c90.png
