### ISSUE TITLE
Hungry Cat Picross

### ISSUE THREAD

**Issue by Meyers09** [glasklart/hd#6806]
**App Name:** Hungry Cat Picross
**Bundle ID:** com.tuesdayquest.logicart
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=737744473">737744473</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hungry-cat-picross/id737744473?mt=8&uo=4">https://itunes.apple.com/us/app/hungry-cat-picross/id737744473?mt=8&uo=4</a>
**App Version:** 1.75.1
**Seller:** Tuesday Quest
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tuesday-quest/id698081587?uo=4>© Tuesday Quest</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/ce/4e/1b/ce4e1bfc-4447-33e9-da27-742b49c85d8f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11248063/c9d0f48a-8de4-11e5-8445-1e5a6c26d5c8.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11248063/c9d0f48a-8de4-11e5-8445-1e5a6c26d5c8.png)
https://cloud.githubusercontent.com/assets/3090247/11248063/c9d0f48a-8de4-11e5-8445-1e5a6c26d5c8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11248059/c980b9c0-8de4-11e5-92b6-91032ddff305.png

**Comment by dreamnet** [comment]
@ivanov007 Jup! :+1:
