### ISSUE TITLE
NJ TRANSIT Mobile App

### ISSUE THREAD

**Issue by Meyers09** [glasklart/hd#6807]
**App Name:** NJ TRANSIT Mobile App
**Bundle ID:** com.njtransit.njtapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589549928">589549928</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nj-transit-mobile-app/id589549928?mt=8&uo=4">https://itunes.apple.com/us/app/nj-transit-mobile-app/id589549928?mt=8&uo=4</a>
**App Version:** 2015.3
**Seller:** NJ TRANSIT
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/new-jersey-transit-corporation/id589549971?uo=4>© NEW JERSEY TRANSIT CORPORATION</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/de/71/41/de714130-d278-843d-30d4-9580cd470433/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11312265/4c1f0886-8fd5-11e5-8e72-0b8015f9f907.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11312265/4c1f0886-8fd5-11e5-8e72-0b8015f9f907.png)
https://cloud.githubusercontent.com/assets/2068130/11312265/4c1f0886-8fd5-11e5-8e72-0b8015f9f907.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11312273/5b6aefee-8fd5-11e5-9bac-8a680f22e135.png
