### ISSUE TITLE
Fragment - Prismatic Photo Effects

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#6812]
**App Name:** Fragment - Prismatic Photo Effects
**Bundle ID:** com.pixite.Fragment
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=767104707">767104707</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fragment-prismatic-photo-effects/id767104707?mt=8&uo=4">https://itunes.apple.com/us/app/fragment-prismatic-photo-effects/id767104707?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Pixite LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pixite-llc/id285719021?mt=8&uo=4>© Pixite LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/6b/75/42/6b7542a6-88cc-21a0-85f1-a422ab366b9a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11264252/79a9b812-8e92-11e5-9281-a16262a8c64f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11264252/79a9b812-8e92-11e5-9281-a16262a8c64f.png)
https://cloud.githubusercontent.com/assets/2068130/11264252/79a9b812-8e92-11e5-9281-a16262a8c64f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11264261/8721ed70-8e92-11e5-91eb-7d485a6226f9.png

**Comment by slipko** [comment]
Awesome! Thank you sir @dreamnet

**Comment by dreamnet** [comment]
@slipko :wink: :+1:
