### ISSUE TITLE
Disneyland®

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6816]
**App Name:** Disneyland®
**Bundle ID:** com.disney.DLR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1022164656">1022164656</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/disneyland/id1022164656?mt=8&uo=4">https://itunes.apple.com/us/app/disneyland/id1022164656?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Disney Electronic Content, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/disney/id284888248?mt=8&uo=4>© Disney</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/de/c0/c7/dec0c7bc-f680-c53b-2562-33964fe31180/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310710/9c721954-8fcb-11e5-9dd4-8fe3caae3213.png)

**Comment by ivanov007** [comment]
@ashley108 the issue name must be the same as the app name

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310710/9c721954-8fcb-11e5-9dd4-8fe3caae3213.png)
https://cloud.githubusercontent.com/assets/2068130/11310710/9c721954-8fcb-11e5-9dd4-8fe3caae3213.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11310731/afa95014-8fcb-11e5-9859-f7fdc83e1ef1.png
