### ISSUE TITLE
Logix Mobile

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6817]
**App Name:** Logix Mobile
**Bundle ID:** com.mshift.lfcu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=449281410">449281410</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/logix-mobile/id449281410?mt=8&uo=4">https://itunes.apple.com/us/app/logix-mobile/id449281410?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Logix Federal Credit Union
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/logix-federal-credit-union/id449281413?uo=4>© Logix Federal Credit Union</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/94/17/ec/9417ec68-cae1-c765-cb9e-57db1a382924/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11352170/1f87d6be-923b-11e5-8e02-73b6e9c6d428.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11352170/1f87d6be-923b-11e5-8e02-73b6e9c6d428.png)
https://cloud.githubusercontent.com/assets/2068130/11352170/1f87d6be-923b-11e5-8e02-73b6e9c6d428.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11352176/2e6e6dbe-923b-11e5-9636-49e31512bccc.png
