### ISSUE TITLE
NFL Sunday Ticket

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6818]
**App Name:** NFL Sunday Ticket
**Bundle ID:** com.directv.mobile.iphone.supercast.production
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327243363">327243363</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nfl-sunday-ticket/id327243363?mt=8&uo=4">https://itunes.apple.com/us/app/nfl-sunday-ticket/id327243363?mt=8&uo=4</a>
**App Version:** 2.5.024
**Seller:** DIRECTV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/directv-inc./id307386353?uo=4>© DIRECTV, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/14/d1/45/14d145fe-ea4f-58b9-f800-69ccdcfed14a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12063494/0c36d802-afb0-11e5-9ba4-ed21ece08493.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12063494/0c36d802-afb0-11e5-9ba4-ed21ece08493.png)
https://cloud.githubusercontent.com/assets/2068130/12063494/0c36d802-afb0-11e5-9ba4-ed21ece08493.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12063499/231d7abc-afb0-11e5-9384-4f773fadad8d.png
