### ISSUE TITLE
ABC7 Los Angeles

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6819]
**App Name:** ABC7 Los Angeles
**Bundle ID:** com.go.abclocal.kabcapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405387506">405387506</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/abc7-los-angeles/id405387506?mt=8&uo=4">https://itunes.apple.com/us/app/abc7-los-angeles/id405387506?mt=8&uo=4</a>
**App Version:** 4.4.0
**Seller:** ABC Digital
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/abc-digital/id333236255?uo=4>© ABC Digital</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/5d/4b/0d/5d4b0d8e-5747-af81-5409-a19e1c3eca04/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310448/f3f7725c-8fc9-11e5-9446-d57fea0e1de1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310448/f3f7725c-8fc9-11e5-9446-d57fea0e1de1.png)
https://cloud.githubusercontent.com/assets/2068130/11310448/f3f7725c-8fc9-11e5-9446-d57fea0e1de1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11310455/02646476-8fca-11e5-8455-c43f860f4467.png
