### ISSUE TITLE
SEEK - Jobs

### ISSUE THREAD

**Issue by keefetang** [glasklart/hd#682]
**App Name:** SEEK - Jobs
**Bundle ID:** com.seek.jobseeker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520400855">520400855</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/seek-jobs/id520400855?mt=8&uo=4">https://itunes.apple.com/us/app/seek-jobs/id520400855?mt=8&uo=4</a>
**App Version:** 1.4.6
**Seller:** SEEK Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/seek-ltd./id520400858?uo=4>© SEEK Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/d4/0d/26/d40d267b-4265-ee0c-0486-dd7ab3ce52d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808827/179af97c-826d-11e6-87dc-51af00a2da9c.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808806/7e5d20d2-826c-11e6-8094-c53f9b0630b6.png)
https://cloud.githubusercontent.com/assets/20930745/18808806/7e5d20d2-826c-11e6-8094-c53f9b0630b6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18808812/a395edd4-826c-11e6-9094-61840a32faae.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808827/179af97c-826d-11e6-87dc-51af00a2da9c.png)
https://cloud.githubusercontent.com/assets/20930745/18808827/179af97c-826d-11e6-87dc-51af00a2da9c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18808831/26546cdc-826d-11e6-924e-1d10de70d0c2.png
