### ISSUE TITLE
Kaiser Permanente

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6820]
**App Name:** Kaiser Permanente
**Bundle ID:** org.kp.m
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493390354">493390354</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kaiser-permanente/id493390354?mt=8&uo=4">https://itunes.apple.com/us/app/kaiser-permanente/id493390354?mt=8&uo=4</a>
**App Version:** 4.6.0
**Seller:** Kaiser Permanente
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kaiser-permanente/id446423714?uo=4>© Kaiser Permanente</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/d2/58/b1/d258b1c1-a3a0-f013-b5bf-a420ce7b59f2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310372/77d4a0f0-8fc9-11e5-81e2-7c9ef14f7fc5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310372/77d4a0f0-8fc9-11e5-81e2-7c9ef14f7fc5.png)
https://cloud.githubusercontent.com/assets/2068130/11310372/77d4a0f0-8fc9-11e5-81e2-7c9ef14f7fc5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11310386/871ea074-8fc9-11e5-901d-a856f31fa963.png
