### ISSUE TITLE
Allstate® Mobile

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6821]
**App Name:** Allstate® Mobile
**Bundle ID:** com.allstate.dev.allstate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364376344">364376344</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/allstate-mobile/id364376344?mt=8&uo=4">https://itunes.apple.com/us/app/allstate-mobile/id364376344?mt=8&uo=4</a>
**App Version:** 12.4.0
**Seller:** Allstate Insurance Company
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/allstate-insurance-company/id318394321?uo=4">© Allstate Insurance Company</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/a9/6e/56/a96e5624-c2ec-b7a3-0c86-c7ae38b9cbbf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621196-fd705a80-a8a1-11e8-9e4f-e47888253025.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11349308/d967da08-922b-11e5-99a7-6c6fc1c55d2c.png)
https://cloud.githubusercontent.com/assets/2068130/11349308/d967da08-922b-11e5-99a7-6c6fc1c55d2c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11349316/eb061e32-922b-11e5-8840-a5471d4de8ee.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621196-fd705a80-a8a1-11e8-9e4f-e47888253025.png)
https://user-images.githubusercontent.com/2068130/44621196-fd705a80-a8a1-11e8-9e4f-e47888253025.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44621202-124cee00-a8a2-11e8-8faa-6d07cc1e9e24.png
