### ISSUE TITLE
Yogurtland

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6822]
**App Name:** Yogurtland
**Bundle ID:** com.yogurtland.yl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=604968321">604968321</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yogurtland/id604968321?mt=8&uo=4">https://itunes.apple.com/us/app/yogurtland/id604968321?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** Yogurtland Franchising Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yogurtland/id604968324?uo=4>© Yogurtland</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/fb/61/22/fb61224c-a1e0-0c09-80cd-15317574c600/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310276/fa755424-8fc8-11e5-8dbb-5b38bf484463.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310276/fa755424-8fc8-11e5-8dbb-5b38bf484463.png)
https://cloud.githubusercontent.com/assets/2068130/11310276/fa755424-8fc8-11e5-8dbb-5b38bf484463.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11310284/0a0a5344-8fc9-11e5-9fb1-147cac454844.png

**Comment by ashley108** [comment]
How do I add them to the theme?

**Comment by dreamnet** [comment]
@ashley108 You can wait for the next release (in about 14 days) or you can add them manually following [this guide](https://github.com/glasklart/hd/wiki/How-to-manually-add-icons).
