### ISSUE TITLE
MouseWait Disneyland Wait Times FREE

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6823]
**App Name:** MouseWait Disneyland Wait Times FREE
**Bundle ID:** com.app316.MouseWait
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=331771613">331771613</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mousewait-disneyland-wait/id331771613?mt=8&uo=4">https://itunes.apple.com/us/app/mousewait-disneyland-wait/id331771613?mt=8&uo=4</a>
**App Version:** 8.3
**Seller:** ALLAuthentic Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/app316.com/id331771616?uo=4>© app316.com</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/8c/2f/05/8c2f05b1-4bf6-f8ef-eb8c-2fa1aff1ed4c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458417/d2e47928-96bf-11e5-9c7d-15071808936d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458417/d2e47928-96bf-11e5-9c7d-15071808936d.png)
https://cloud.githubusercontent.com/assets/2068130/11458417/d2e47928-96bf-11e5-9c7d-15071808936d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11458422/e2401562-96bf-11e5-9f4b-e72ec0f058e5.png
