### ISSUE TITLE
Trivia Crack Kingdoms

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6824]
**App Name:** Trivia Crack Kingdoms
**Bundle ID:** com.etermax.kingdoms
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1002597082">1002597082</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trivia-crack-kingdoms/id1002597082?mt=8&uo=4">https://itunes.apple.com/us/app/trivia-crack-kingdoms/id1002597082?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Etermax
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/etermax/id286461525?uo=4>© Etermax</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/26/9b/de/269bde61-2fc3-c83f-cd4a-50782231f99b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11329155/ab75dec0-915d-11e5-9ac7-439d2f823dc6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11329155/ab75dec0-915d-11e5-9ac7-439d2f823dc6.png)
https://cloud.githubusercontent.com/assets/3090247/11329155/ab75dec0-915d-11e5-9ac7-439d2f823dc6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11329156/abbb8100-915d-11e5-8df5-b5be951487d6.png

**Comment by dreamnet** [comment]
@ivanov007 !!! :+1:
