### ISSUE TITLE
MADDEN NFL Mobile

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6825]
**App Name:** MADDEN NFL Mobile
**Bundle ID:** com.ea.maddenmobile15.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=855627886">855627886</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/madden-nfl-mobile/id855627886?mt=8&uo=4">https://itunes.apple.com/us/app/madden-nfl-mobile/id855627886?mt=8&uo=4</a>
**App Version:** 2.9.3
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4>© Electronic Arts</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/5b/75/4e/5b754e7c-f638-f749-bfb4-fbeb126eb0cd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12079964/f6b0c6c0-b24b-11e5-8bc3-8178e71fbaf9.png)

**Comment by dreamnet** [comment]
Can't do the original...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12079964/f6b0c6c0-b24b-11e5-8bc3-8178e71fbaf9.png)
https://cloud.githubusercontent.com/assets/2068130/12079964/f6b0c6c0-b24b-11e5-8bc3-8178e71fbaf9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12079968/0e50a3b8-b24c-11e5-9ad6-4d88cf192269.png

**Comment by Trubbel** [comment]
Well, at least you can tell what it is on the icon so that's great and the icon itself looks alright to me. :+1:
