### ISSUE TITLE
NewsBlur

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6826]
**App Name:** NewsBlur
**Bundle ID:** com.newsblur.NewsBlur
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=463981119">463981119</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsblur/id463981119?mt=8&uo=4">https://itunes.apple.com/us/app/newsblur/id463981119?mt=8&uo=4</a>
**App Version:** 5.0.1
**Seller:** NewsBlur, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/newsblur-inc./id463981122?uo=4>© NewsBlur, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/c6/e9/6d/c6e96dff-2c47-e12b-b461-9008a3835f20/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310127/167ec98a-8fc8-11e5-8f39-81d5982228b6.png)

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310127/167ec98a-8fc8-11e5-8f39-81d5982228b6.png)
https://cloud.githubusercontent.com/assets/2068130/11310127/167ec98a-8fc8-11e5-8f39-81d5982228b6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11310139/260e9a7e-8fc8-11e5-8d78-1a6fdfda0bfd.png
