### ISSUE TITLE
TheseReads

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6827]
**App Name:** TheseReads
**Bundle ID:** com.thesereads.thesereads
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=977721531">977721531</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/thesereads/id977721531?mt=8&uo=4">https://itunes.apple.com/us/app/thesereads/id977721531?mt=8&uo=4</a>
**App Version:** 20.1
**Seller:** Jiaqi Lin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jiaqi-lin/id977721530?uo=4>© Jiaqi Lin</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/40/55/83/405583a7-91d8-966e-00a7-aed085e7ef93/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310000/6283fe1e-8fc7-11e5-97c3-397018ac98ec.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11310000/6283fe1e-8fc7-11e5-97c3-397018ac98ec.png)
https://cloud.githubusercontent.com/assets/2068130/11310000/6283fe1e-8fc7-11e5-97c3-397018ac98ec.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11310008/71d77bca-8fc7-11e5-93e6-802db2b4fcde.png
