### ISSUE TITLE
Smashy Road: Wanted

### ISSUE THREAD

**Issue by Strxn** [glasklart/hd#6829]
**App Name:** Smashy Road: Wanted
**Bundle ID:** com.rkgames.smashywanted
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1020119327">1020119327</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smashy-road-wanted/id1020119327?mt=8&uo=4">https://itunes.apple.com/us/app/smashy-road-wanted/id1020119327?mt=8&uo=4</a>
**App Version:** 1.1.6
**Seller:** Remco Kortenoever
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/remco-kortenoever/id816320258?uo=4>© Remco Kortenoever</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/5f/c4/a8/5fc4a8cc-dc4e-d027-5908-09f8b002f450/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12063938/8cd8c676-afb7-11e5-8949-87a7a34d2c19.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12063938/8cd8c676-afb7-11e5-8949-87a7a34d2c19.png)
https://cloud.githubusercontent.com/assets/2068130/12063938/8cd8c676-afb7-11e5-8949-87a7a34d2c19.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12063942/9ad9afba-afb7-11e5-8be1-e790496c3933.png
