### ISSUE TITLE
5K Runner, Couch Potato to 5K

### ISSUE THREAD

**Issue by keefetang** [glasklart/hd#683]
**App Name:** 5K Runner, Couch Potato to 5K
**Bundle ID:** com.heavydutyapps.RunC25K
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=439852091">439852091</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/5k-runner-couch-potato-to-5k/id439852091?mt=8&uo=4">https://itunes.apple.com/us/app/5k-runner-couch-potato-to-5k/id439852091?mt=8&uo=4</a>
**App Version:** 7.5
**Seller:** FITNESS22 LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fitness22-ltd/id383171664?uo=4">© FITNESS22 LTD</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/b3/32/dc/b332dc1a-04a7-634e-8a11-4f57fc390107/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39464352-07cd8ea2-4d1d-11e8-9561-e4d4f3e6e141.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39464352-07cd8ea2-4d1d-11e8-9561-e4d4f3e6e141.png)
https://user-images.githubusercontent.com/20930745/39464352-07cd8ea2-4d1d-11e8-9561-e4d4f3e6e141.png

Source:
https://user-images.githubusercontent.com/20930745/39464361-16edc668-4d1d-11e8-8614-2b1b1eb3256f.png
