### ISSUE TITLE
Fallout CHAT

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6831]
**App Name:** Fallout CHAT
**Bundle ID:** com.bethesda.Fallout-CHAT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1017881114">1017881114</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fallout-chat/id1017881114?mt=8&uo=4">https://itunes.apple.com/us/app/fallout-chat/id1017881114?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Bethesda Softworks LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bethesda/id547109759?uo=4>© Bethesda</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/32/a1/1b/32a11ba7-113e-efe1-aaef-c077e69db4b0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11326233/7f74b074-9164-11e5-8961-4c27a20ca6a7.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11326233/7f74b074-9164-11e5-8961-4c27a20ca6a7.png)
https://cloud.githubusercontent.com/assets/10730122/11326233/7f74b074-9164-11e5-8961-4c27a20ca6a7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11326231/7be2ab8c-9164-11e5-8f4c-7fac21ba722c.png

**Comment by dreamnet** [comment]
@Trubbel Nice! :+1:
