### ISSUE TITLE
Blizzard Authenticator

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6832]
**App Name:** Blizzard Authenticator
**Bundle ID:** com.blizzard.Authenticator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306862897">306862897</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/blizzard-authenticator/id306862897?uo=4">https://apps.apple.com/us/app/blizzard-authenticator/id306862897?uo=4</a>
**App Version:** 2.3.0
**Seller:** Blizzard Entertainment, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/blizzard-entertainment-inc/id306862900?uo=4">© Blizzard Entertainment, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/23/e5/8f/23e58fa3-0af2-2c6a-86f7-ed3a9e8637c0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981486-3d0fec00-9604-11e9-8955-ea863f1c0250.png)

**Comment by Trubbel** [comment]
Adding issue, plus updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11326356/c09acca2-9167-11e5-859a-6b32ca8db250.png)
https://cloud.githubusercontent.com/assets/10730122/11326356/c09acca2-9167-11e5-859a-6b32ca8db250.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11326355/bd00e61c-9167-11e5-9fec-709d445838ab.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981486-3d0fec00-9604-11e9-8955-ea863f1c0250.png)
https://user-images.githubusercontent.com/2068130/59981486-3d0fec00-9604-11e9-8955-ea863f1c0250.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59981490-4bf69e80-9604-11e9-91e0-57b01fc46e9b.png
