### ISSUE TITLE
TripRider - Travel Planner and Organizer

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6833]
**App Name:** TripRider - Travel Planner and Organizer
**Bundle ID:** com.minoa.triprider
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=553823952">553823952</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/triprider-travel-planner-organizer/id553823952?mt=8&uo=4">https://itunes.apple.com/us/app/triprider-travel-planner-organizer/id553823952?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** Minoa d.o.o.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/minoa-d.o.o./id490109706?uo=4>© Minoa d.o.o.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/6b/bf/2b/6bbf2b9e-4109-5081-4201-5902758ae66b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11330930/dfcc17c4-91b3-11e5-963b-165aac5de612.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11326392/e1652b0c-9168-11e5-9230-2fe66c41f303.png)
https://cloud.githubusercontent.com/assets/10730122/11326392/e1652b0c-9168-11e5-9230-2fe66c41f303.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11326391/ddb57d36-9168-11e5-9c10-395cfd3c53c2.png

**Comment by dreamnet** [comment]
@Trubbel Uh, only the star should be enough.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11330930/dfcc17c4-91b3-11e5-963b-165aac5de612.png)
https://cloud.githubusercontent.com/assets/2068130/11330930/dfcc17c4-91b3-11e5-963b-165aac5de612.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11330939/ee8cbd54-91b3-11e5-811c-a9177027a409.png
