### ISSUE TITLE
TriNet Mobile

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6834]
**App Name:** TriNet Mobile
**Bundle ID:** com.trinet.hrpmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589217167">589217167</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trinet-mobile/id589217167?mt=8&uo=4">https://itunes.apple.com/us/app/trinet-mobile/id589217167?mt=8&uo=4</a>
**App Version:** 4.83
**Seller:** TriNet Group, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/trinet/id589217270?uo=4>© TriNet</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/7d/d6/2f/7dd62f8d-1897-fcd5-85e6-83a354655d8d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11329013/d585192c-915a-11e5-954d-f06bb42715c7.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11329013/d585192c-915a-11e5-954d-f06bb42715c7.png)
https://cloud.githubusercontent.com/assets/3090247/11329013/d585192c-915a-11e5-954d-f06bb42715c7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11329012/d54e861e-915a-11e5-9f0f-6a3edfecdd8a.png
