### ISSUE TITLE
Thanksgiving: A Bon Appétit Manual

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6835]
**App Name:** Thanksgiving: A Bon Appétit Manual
**Bundle ID:** com.condenet.bonappetit.thanksgiving
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=720808869">720808869</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/thanksgiving-bon-appetit-manual/id720808869?mt=8&uo=4">https://itunes.apple.com/us/app/thanksgiving-bon-appetit-manual/id720808869?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** CondeNet
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/conde-nast-digital/id289380416?mt=8&uo=4>© Condé Nast Digital</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/3b/be/76/3bbe7607-479e-a594-f926-390b31aa2026/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11329903/ced76e10-9167-11e5-8a56-4d7ee7e3795d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11329903/ced76e10-9167-11e5-8a56-4d7ee7e3795d.png)
https://cloud.githubusercontent.com/assets/3090247/11329903/ced76e10-9167-11e5-8a56-4d7ee7e3795d.png
--- ----
Source:
https://cloud.githubusercontent.com/assets/3090247/11329904/cf0d32ca-9167-11e5-92fd-53b8dbd26eaf.png
