### ISSUE TITLE
TWC WiFi Finder

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#6836]
**App Name:** TWC WiFi Finder
**Bundle ID:** com.timewarnercable.wifi-finder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492768487">492768487</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/twc-wifi-finder/id492768487?mt=8&uo=4">https://itunes.apple.com/us/app/twc-wifi-finder/id492768487?mt=8&uo=4</a>
**App Version:** 5.1.15
**Seller:** Time Warner Cable Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/time-warner-cable/id396670004?uo=4>© Time Warner Cable</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/99/7d/9f/997d9f72-265d-0f0a-5d1c-69cd702bd0a5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11328803/198fb2de-9157-11e5-82dc-c43b7b0ba014.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11328803/198fb2de-9157-11e5-82dc-c43b7b0ba014.png)
https://cloud.githubusercontent.com/assets/3090247/11328803/198fb2de-9157-11e5-82dc-c43b7b0ba014.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11328804/19c36a8e-9157-11e5-8d2e-62e109f4ce47.png
