### ISSUE TITLE
Raise - Buy & Sell Gift Cards + Mobile Wallet

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6837]
**App Name:** Raise - Buy & Sell Gift Cards + Mobile Wallet
**Bundle ID:** com.raise.Raise
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=922643195">922643195</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/raise-buy-sell-gift-cards/id922643195?mt=8&uo=4">https://itunes.apple.com/us/app/raise-buy-sell-gift-cards/id922643195?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Raise Marketplace Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/raise-marketplace-inc./id922643194?uo=4>© Raise Marketplace Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/bb/65/a1/bb65a191-1276-0f7b-1e99-867a7734ab11/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11348475/22c18a32-9227-11e5-922a-e463edc368a8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11348475/22c18a32-9227-11e5-922a-e463edc368a8.png)
https://cloud.githubusercontent.com/assets/2068130/11348475/22c18a32-9227-11e5-922a-e463edc368a8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11348491/32848654-9227-11e5-9502-518e474a6a83.png
