### ISSUE TITLE
Spider-Man: Total Mayhem

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#6838]
**App Name:** Spider-Man: Total Mayhem
**Bundle ID:** com.gameloft.SpidermanUS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=360181985">360181985</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spider-man-total-mayhem/id360181985?mt=8&uo=4">https://itunes.apple.com/us/app/spider-man-total-mayhem/id360181985?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Gameloft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gameloft/id282764297?mt=8&uo=4>© Gameloft</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/7d/87/4a/7d874af2-b30a-ec51-fac8-b5ed01637a88/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12077823/32027c50-b1f7-11e5-933d-b9d656b51f6d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12077823/32027c50-b1f7-11e5-933d-b9d656b51f6d.png)
https://cloud.githubusercontent.com/assets/2068130/12077823/32027c50-b1f7-11e5-933d-b9d656b51f6d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12077827/41a12b02-b1f7-11e5-93c3-9ec93bda1bc3.png
