### ISSUE TITLE
Agent RX

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6839]
**App Name:** Agent RX
**Bundle ID:** com.undercover.agentrx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=815591919">815591919</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/agent-rx/id815591919?mt=8&uo=4">https://itunes.apple.com/us/app/agent-rx/id815591919?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Alfred Tay Poh Yi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alfred-tay-poh-yi/id690909258?uo=4>© Alfred Tay Poh Yi</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/f3/e8/4f/f3e84f33-a5f1-4cae-6a2d-748c8fbdc55b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12080204/e7faaa08-b253-11e5-8eaf-d4ba85a2e55f.png)

**Comment by dreamnet** [comment]
@ivanov007 All I can do:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12080204/e7faaa08-b253-11e5-8eaf-d4ba85a2e55f.png)
https://cloud.githubusercontent.com/assets/2068130/12080204/e7faaa08-b253-11e5-8eaf-d4ba85a2e55f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12080205/f65695f8-b253-11e5-901e-07c9ae2c0a38.png

**Comment by ivanov007** [comment]
@dreamnet it's pretty good :+1:

**Comment by Trubbel** [comment]
You can see the resemblance, which is good. :smile:
