### ISSUE TITLE
iA Writer Classic (Legacy Support Edition)

### ISSUE THREAD

**Issue by keefetang** [glasklart/hd#684]
**App Name:** iA Writer Classic (Legacy Support Edition)
**Bundle ID:** jp.informationarchitects.Writer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=392502056">392502056</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ia-writer-classic-legacy-support/id392502056?mt=8&uo=4">https://itunes.apple.com/us/app/ia-writer-classic-legacy-support/id392502056?mt=8&uo=4</a>
**App Version:** 2.1.5
**Seller:** Information Architects Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/information-architects-inc./id386276839?uo=4>© Information Architects Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/40/aa/ae/40aaae13-2184-cb56-662f-fe38f2fc821b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19528063/dd51c396-962a-11e6-977a-04296245f20e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19528063/dd51c396-962a-11e6-977a-04296245f20e.png)
https://cloud.githubusercontent.com/assets/20930745/19528063/dd51c396-962a-11e6-977a-04296245f20e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19528081/f6081c3c-962a-11e6-8341-4b8604ed97ad.png
