### ISSUE TITLE
Blendoku 2

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6840]
**App Name:** Blendoku 2
**Bundle ID:** com.lonelyfew.blendoku2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1017177662">1017177662</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blendoku-2/id1017177662?mt=8&uo=4">https://itunes.apple.com/us/app/blendoku-2/id1017177662?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Lonely Few LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lonely-few-llc/id501819185?uo=4>© Lonely Few LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/6f/07/4a/6f074a82-13e2-5d15-5df6-2b7729a28fb6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458651/a5d8fd50-96c4-11e5-9107-aceb966b8870.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458651/a5d8fd50-96c4-11e5-9107-aceb966b8870.png)
https://cloud.githubusercontent.com/assets/2068130/11458651/a5d8fd50-96c4-11e5-9107-aceb966b8870.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11458654/b4ad70b8-96c4-11e5-952e-64761aba0475.png
