### ISSUE TITLE
Century City

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6841]
**App Name:** Century City
**Bundle ID:** CenturyCity.PineEntertainment.Com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955682952">955682952</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/century-city/id955682952?mt=8&uo=4">https://itunes.apple.com/us/app/century-city/id955682952?mt=8&uo=4</a>
**App Version:** 2.8.8
**Seller:** Pine Entertainment Company Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pine-entertainment/id505916072?uo=4>© Pine Entertainment</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/13/43/60/13436046-7b32-5008-363b-aefe828888aa/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11915163/4c3a82d8-a69a-11e5-9eaa-c816d06bb526.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11915163/4c3a82d8-a69a-11e5-9eaa-c816d06bb526.png)
https://cloud.githubusercontent.com/assets/2068130/11915163/4c3a82d8-a69a-11e5-9eaa-c816d06bb526.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11915165/5b0582e0-a69a-11e5-9c04-e1894cab25c0.png
