### ISSUE TITLE
Fyuse - 3D Photos

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6842]
**App Name:** Fyuse - 3D Photos
**Bundle ID:** com.fyusion.Fyuse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=862863329">862863329</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fyuse-3d-photos/id862863329?uo=4">https://apps.apple.com/us/app/fyuse-3d-photos/id862863329?uo=4</a>
**App Version:** 4.5.2
**Seller:** Fyusion, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fyusion/id862863332?uo=4">© Fyusion</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/3c/a6/d0/3ca6d076-09f0-c631-d19a-5561b8d22a1e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60394945-43362900-9b2c-11e9-8019-a12226eb726b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11447304/91c4132a-9509-11e5-9ded-d2415148e2f6.png)
https://cloud.githubusercontent.com/assets/3090247/11447304/91c4132a-9509-11e5-9ded-d2415148e2f6.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11447305/92080238-9509-11e5-950d-f063e6f762b8.png)
https://cloud.githubusercontent.com/assets/3090247/11447305/92080238-9509-11e5-950d-f063e6f762b8.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/11447307/92835a50-9509-11e5-9a8b-8629728b92b5.png
https://cloud.githubusercontent.com/assets/3090247/11447306/92443244-9509-11e5-9c1d-ac82427b9e66.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60394945-43362900-9b2c-11e9-8019-a12226eb726b.png)
https://user-images.githubusercontent.com/2068130/60394945-43362900-9b2c-11e9-8019-a12226eb726b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60394949-5517cc00-9b2c-11e9-9104-cad217f0f7f4.png
