### ISSUE TITLE
Mighty Switch Force! Hose It Down!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6844]
**App Name:** Mighty Switch Force! Hose It Down!
**Bundle ID:** com.Wayforward.HoseItDown
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=922587565">922587565</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mighty-switch-force!-hose/id922587565?mt=8&uo=4">https://itunes.apple.com/us/app/mighty-switch-force!-hose/id922587565?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** WayForward
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wayforward-technologies-inc./id431535205?uo=4>© WayForward Technologies, Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/72/1f/22/721f2214-958a-9105-3450-496df0f544d2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458591/03907e34-96c3-11e5-973c-a44c72557116.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458591/03907e34-96c3-11e5-973c-a44c72557116.png)
https://cloud.githubusercontent.com/assets/2068130/11458591/03907e34-96c3-11e5-973c-a44c72557116.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11458592/12ef18c2-96c3-11e5-970f-5fd466d7a09a.png
