### ISSUE TITLE
Network Utility for iOS

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6845]
**App Name:** Network Utility for iOS
**Bundle ID:** com.r2lab.UtilityNetwork
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=573021799">573021799</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/network-utility-for-ios/id573021799?mt=8&uo=4">https://itunes.apple.com/us/app/network-utility-for-ios/id573021799?mt=8&uo=4</a>
**App Version:** 4.2.5
**Seller:** Fausto Ristagno
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fausto-ristagno/id482102205?uo=4>© Fausto Ristagno</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/44/b5/b4/44b5b447-2080-c4f6-61d6-594a4c3544c3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458053/c2c91bae-96b8-11e5-9acd-524f6e038be7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458053/c2c91bae-96b8-11e5-9acd-524f6e038be7.png)
https://cloud.githubusercontent.com/assets/2068130/11458053/c2c91bae-96b8-11e5-9acd-524f6e038be7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11458055/d2fba348-96b8-11e5-9419-aba0588d1666.png
