### ISSUE TITLE
Sweat with Kayla

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6846]
**App Name:** Sweat with Kayla
**Bundle ID:** com.PixelForceSystems.SweatWithKayla
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049234587">1049234587</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sweat-with-kayla/id1049234587?mt=8&uo=4">https://itunes.apple.com/us/app/sweat-with-kayla/id1049234587?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** The Bikini Body Training Company Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kayla-itsines/id1049234586?uo=4>© Kayla Itsines</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/27/98/7d/27987dab-56be-dd45-4088-d08f7e236703/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11457997/4c951a1e-96b8-11e5-9fe0-6d7301e9f027.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11457997/4c951a1e-96b8-11e5-9fe0-6d7301e9f027.png)
https://cloud.githubusercontent.com/assets/2068130/11457997/4c951a1e-96b8-11e5-9fe0-6d7301e9f027.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11458002/5bb6fc56-96b8-11e5-99c4-8a85b02ce600.png
