### ISSUE TITLE
Mi Iusacell

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6847]
**App Name:** Mi Iusacell
**Bundle ID:** com.iusacell.miiusacell
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=930786613">930786613</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mi-iusacell/id930786613?mt=8&uo=4">https://itunes.apple.com/us/app/mi-iusacell/id930786613?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Grupo Iusacell, S.A.de C.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iusacell/id868285893?uo=4>© iusacell</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/fc/17/25/fc1725a0-2571-60b4-5943-249451eb386a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458172/4f6968be-96bb-11e5-9392-13a58cc8c72e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458172/4f6968be-96bb-11e5-9392-13a58cc8c72e.png)
https://cloud.githubusercontent.com/assets/2068130/11458172/4f6968be-96bb-11e5-9392-13a58cc8c72e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11458175/5d8d1828-96bb-11e5-89e2-96098bd0c29b.png
