### ISSUE TITLE
Producteev by Jive - Task Management for Teams

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6848]
**App Name:** Producteev by Jive - Task Management for Teams
**Bundle ID:** com.producteev.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306289289">306289289</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/producteev-by-jive-task-management/id306289289?mt=8&uo=4">https://itunes.apple.com/us/app/producteev-by-jive-task-management/id306289289?mt=8&uo=4</a>
**App Version:** 6.4.1
**Seller:** Jive Software
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jive-software/id334929366?uo=4>© Jive Software</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/70/2d/ab/702dab8b-5cf2-7805-cfce-7f8900ff8ff4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11417241/90eef4b4-9415-11e5-8836-0a05f2ee7aa4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11417241/90eef4b4-9415-11e5-8836-0a05f2ee7aa4.png)
https://cloud.githubusercontent.com/assets/2068130/11417241/90eef4b4-9415-11e5-8836-0a05f2ee7aa4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11417246/9e682174-9415-11e5-9940-25bf8a164b12.png
