### ISSUE TITLE
Adventures in the Air - Eagle Attack

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6849]
**App Name:** Adventures in the Air - Eagle Attack
**Bundle ID:** com.toccata.technologies.general.AdventureInAir
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=703369502">703369502</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adventures-in-air-eagle-attack/id703369502?mt=8&uo=4">https://itunes.apple.com/us/app/adventures-in-air-eagle-attack/id703369502?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Toccata Technologies Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/toccata-technologies-inc./id329746565?uo=4>© Toccata Technologies Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/e9/1f/12/e91f12a3-8a4d-9a0c-9c64-0005bdfbcebb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11920021/3a5b9fce-a763-11e5-97e7-1239ea94a8e7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11920021/3a5b9fce-a763-11e5-97e7-1239ea94a8e7.png)
https://cloud.githubusercontent.com/assets/2068130/11920021/3a5b9fce-a763-11e5-97e7-1239ea94a8e7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11920024/48c24d24-a763-11e5-8a0b-a41f559d4681.png
