### ISSUE TITLE
Textever 3 - quick notes, diary, journal, integrates with Evernote

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6851]
**App Name:** Textever 3 - quick notes, diary, journal, integrates with Evernote
**Bundle ID:** com.gosubits.textever3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955342150">955342150</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/textever-3-quick-notes-diary/id955342150?mt=8&uo=4">https://itunes.apple.com/us/app/textever-3-quick-notes-diary/id955342150?mt=8&uo=4</a>
**App Version:** 3.1.3
**Seller:** Andrey BELONOGOV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gosubits/id483855132?uo=4>© Gosubits</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/cf/41/35/cf413565-2bf9-5343-6965-37721d7116f7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11456928/19a10f0a-969a-11e5-9e10-75c97119a369.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11456928/19a10f0a-969a-11e5-9e10-75c97119a369.png)
https://cloud.githubusercontent.com/assets/2068130/11456928/19a10f0a-969a-11e5-9e10-75c97119a369.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11456933/273f18e6-969a-11e5-987c-c6638484b0b1.png
