### ISSUE TITLE
Salon.com

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6852]
**App Name:** Salon.com
**Bundle ID:** com.salon.salonapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=549374205">549374205</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/salon.com/id549374205?mt=8&uo=4">https://itunes.apple.com/us/app/salon.com/id549374205?mt=8&uo=4</a>
**App Version:** 3.1.3
**Seller:** Salon Media Group, Inc. Apps
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/salon-media-group-inc./id549374208?uo=4>© Salon Media Group, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/fc/7b/b1/fc7bb11b-27c1-fc4c-b59d-007674862c28/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416684/681be92a-9410-11e5-8ca9-f3d84f49a151.png)

**Comment by illinikev** [comment]
![salon](https://cloud.githubusercontent.com/assets/16004373/11384521/135f529a-92d6-11e5-9746-753a4c174a90.png)
![salonsource](https://cloud.githubusercontent.com/assets/16004373/11384522/152aed50-92d6-11e5-8568-623eff789878.png)

**Comment by illinikev** [comment]
![salon]((http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11410867/9c17a780-9390-11e5-8558-790f404c04a7.png)

![salonsource](https://cloud.githubusercontent.com/assets/16004373/11410930/15edfc9e-9391-11e5-8473-bd58ac39b889.png)

**Comment by ivanov007** [comment]
@illinikev you still are missing the layer style, also your post should lool like this on the writeboard
`![salon](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11410867/9c17a780-9390-11e5-8558-790f404c04a7.png)
https://cloud.githubusercontent.com/assets/16004373/11410867/9c17a780-9390-11e5-8558-790f404c04a7.png
--- ---
source:
https://cloud.githubusercontent.com/assets/16004373/11410930/15edfc9e-9391-11e5-8473-bd58ac39b889.png`
I've made the change on some of your previous posts

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416684/681be92a-9410-11e5-8ca9-f3d84f49a151.png)
https://cloud.githubusercontent.com/assets/2068130/11416684/681be92a-9410-11e5-8ca9-f3d84f49a151.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11416688/75bcbc80-9410-11e5-9260-d0fdb1c81a7d.png
