### ISSUE TITLE
Chicago Tribune

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6853]
**App Name:** Chicago Tribune
**Bundle ID:** com.apptivateme.chicagotribune
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=383137151">383137151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chicago-tribune/id383137151?mt=8&uo=4">https://itunes.apple.com/us/app/chicago-tribune/id383137151?mt=8&uo=4</a>
**App Version:** 3.5.2
**Seller:** Tribune Company
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tribune-interactive/id290161713?uo=4>© Tribune Interactive</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/fb/6e/e9/fb6ee92e-acf6-80a2-54eb-1f9c85304d02/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416612/da514338-940f-11e5-8001-b9f9e561ba50.png)

**Comment by illinikev** [comment]
![chicago-tribune](https://cloud.githubusercontent.com/assets/16004373/11384516/0b5833c8-92d6-11e5-905e-7a4350d96883.png)
![chicago-tribunesource](https://cloud.githubusercontent.com/assets/16004373/11384517/0cd48166-92d6-11e5-8792-8af9c47f3e8f.png)

**Comment by illinikev** [comment]
![chicago-tribunesource](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11410960/559c79ec-9391-11e5-9371-3fd0cd80b961.png)

![chicago-tribunesource](https://cloud.githubusercontent.com/assets/16004373/11410966/6107a7c0-9391-11e5-9a41-b3a9e2b6b3c4.png)

**Comment by illinikev** [comment]
![chicago-tribune](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11410980/7bf6b7c4-9391-11e5-9f0d-6ec77a958104.png)

![chicago-tribunesource](https://cloud.githubusercontent.com/assets/16004373/11410984/85886d5a-9391-11e5-85c8-e5c4ee324669.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416612/da514338-940f-11e5-8001-b9f9e561ba50.png)
https://cloud.githubusercontent.com/assets/2068130/11416612/da514338-940f-11e5-8001-b9f9e561ba50.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11416617/e8f145f0-940f-11e5-881c-f92d4d12f032.png
