### ISSUE TITLE
NYTimes – Breaking National & World News

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6854]
**App Name:** NYTimes – Breaking National & World News
**Bundle ID:** com.nytimes.NYTimes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284862083">284862083</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nytimes-breaking-national/id284862083?mt=8&uo=4">https://itunes.apple.com/us/app/nytimes-breaking-national/id284862083?mt=8&uo=4</a>
**App Version:** 5.5
**Seller:** The New York Times Company (iDP)
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/the-new-york-times-company/id284862086?uo=4>© The New York Times Company</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/76/8e/f4/768ef459-62d6-0301-55dc-2faea4594e4f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11390247/831c80cc-9348-11e5-8e3b-c21e53bfd2ad.png)

**Comment by illinikev** [comment]
![nytimesnow](https://cloud.githubusercontent.com/assets/16004373/11384511/0262a2ee-92d6-11e5-99ba-fa496aeff236.png)
![nytimesnowsource](https://cloud.githubusercontent.com/assets/16004373/11384512/03ac4cfe-92d6-11e5-8ee9-39caaa8777fe.png)

**Comment by dreamnet** [comment]
This icon is [already in the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.nytimes.NYTimes@2x.png), but it has changed a litte bit. I update it.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11390247/831c80cc-9348-11e5-8e3b-c21e53bfd2ad.png)
https://cloud.githubusercontent.com/assets/2068130/11390247/831c80cc-9348-11e5-8e3b-c21e53bfd2ad.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11390252/92dfaf2a-9348-11e5-8187-5b5676e4108f.png

**Comment by ivanov007** [comment]
@illinikev I just edited your post with the preview template `![](http://preview.dreamnet.at?image=` (this way your icon is not white on white)
I can see you forgot to apply the layer style, you need to do so on future contributions, as for the source file, it's a good size (523x676), but it needs to be the full 1024x1024 to be accepted :smile:
