### ISSUE TITLE
Ventra

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6855]
**App Name:** Ventra
**Bundle ID:** com.ventrachicago.riderapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1005645256">1005645256</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ventra/id1005645256?mt=8&uo=4">https://itunes.apple.com/us/app/ventra/id1005645256?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Chicago Transit Authority
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chicago-transit-authority/id1005645255?uo=4>© Chicago Transit Authority</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/e7/91/b2/e791b26e-bc3d-f68b-6bf3-cf28c676c785/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416368/51478158-940d-11e5-8e40-8edc9c6d43b1.png)

**Comment by illinikev** [comment]
![ventra](https://cloud.githubusercontent.com/assets/16004373/11384494/cebd7a68-92d5-11e5-812a-e63768907345.png)
![ventrasource](https://cloud.githubusercontent.com/assets/16004373/11384495/d00930a6-92d5-11e5-9c16-f1177fdb42b9.png)

**Comment by illinikev** [comment]
![ventra](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11410996/9b7f1a3c-9391-11e5-8273-fd7ed5e17c46.png)

![ventrasource](https://cloud.githubusercontent.com/assets/16004373/11410998/a0504874-9391-11e5-88bc-5bbade019409.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416368/51478158-940d-11e5-8e40-8edc9c6d43b1.png)
https://cloud.githubusercontent.com/assets/2068130/11416368/51478158-940d-11e5-8e40-8edc9c6d43b1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11416374/60203be8-940d-11e5-80f7-0bbd25ff0117.png
