### ISSUE TITLE
AccuRadio - Free Internet Radio

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6856]
**App Name:** AccuRadio - Free Internet Radio
**Bundle ID:** com.accuradio.AccuRadio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=351425453">351425453</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/accuradio-free-internet-radio/id351425453?mt=8&uo=4">https://itunes.apple.com/us/app/accuradio-free-internet-radio/id351425453?mt=8&uo=4</a>
**App Version:** 2.20
**Seller:** AccuRadio LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/accuradio-llc/id351425457?uo=4>© AccuRadio LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/b0/e2/0b/b0e20b98-56e7-2660-af4c-0b5e10eef71b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416322/cf7a7aa4-940c-11e5-9404-64c2f12c6070.png)

**Comment by illinikev** [comment]
![accuradio](https://cloud.githubusercontent.com/assets/16004373/11384487/c59b42da-92d5-11e5-97cb-ebcce4670bd3.png)
![accuradiosource](https://cloud.githubusercontent.com/assets/16004373/11384489/c6d4b974-92d5-11e5-9f24-47f8041ab217.png)

**Comment by illinikev** [comment]
![accuradio](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11411002/acba55b4-9391-11e5-8dd3-093ae36b5e00.png)

![accuradiosource](https://cloud.githubusercontent.com/assets/16004373/11411004/b1edf3c4-9391-11e5-9058-e578b774a120.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416322/cf7a7aa4-940c-11e5-9404-64c2f12c6070.png)
https://cloud.githubusercontent.com/assets/2068130/11416322/cf7a7aa4-940c-11e5-9404-64c2f12c6070.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11416329/dd0cee9a-940c-11e5-8ccb-16c385346234.png
