### ISSUE TITLE
Classic FM

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6857]
**App Name:** Classic FM
**Bundle ID:** com.thisisglobal.ClassicFM
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=297697388">297697388</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/classic-fm/id297697388?mt=8&uo=4">https://itunes.apple.com/us/app/classic-fm/id297697388?mt=8&uo=4</a>
**App Version:** 3.14.0
**Seller:** Global Radio
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/this-is-global/id725598190?uo=4>© This is Global</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/3a/77/ae/3a77ae17-dd85-046d-8c22-dd174d82b209/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416267/5a105022-940c-11e5-8154-c59b437bb54d.png)

**Comment by illinikev** [comment]
![classicfm](https://cloud.githubusercontent.com/assets/16004373/11384481/bd7fd160-92d5-11e5-9dcc-d62e31e9b97e.png)
![classicfmsource](https://cloud.githubusercontent.com/assets/16004373/11384483/bf1971a2-92d5-11e5-849b-f72038deb638.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416267/5a105022-940c-11e5-8154-c59b437bb54d.png)
https://cloud.githubusercontent.com/assets/2068130/11416267/5a105022-940c-11e5-8154-c59b437bb54d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11416273/67ba66cc-940c-11e5-8788-e50d040162fd.png

**Comment by illinikev** [comment]
Was this one with the style added? I did the same style for all the icons I added.

Kevin

**Comment by dreamnet** [comment]
@illinikev You need to copy the layer style from one of the sample icons in the Glasklart template to the new layer you made for the new icon - a Glasklart icon is not just a white icon.
Maybe this screenshots are helping you (i'm using a german version of Photoshop):
https://cloud.githubusercontent.com/assets/2068130/11416556/2970645e-940f-11e5-98ad-03377f804732.png
https://cloud.githubusercontent.com/assets/2068130/11416557/2ea790d2-940f-11e5-8c41-a07d1194e6b2.png
https://cloud.githubusercontent.com/assets/2068130/11416560/3122bd32-940f-11e5-9eaf-92ded29bf003.png

**Comment by illinikev** [comment]
I've done that. I do make the icon white before I apply the style.  Maybe that makes a difference.

Kevin

**Comment by dreamnet** [comment]
@illinikev No, normally not... ?
