### ISSUE TITLE
ESPN FC Soccer

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6858]
**App Name:** ESPN FC Soccer
**Bundle ID:** com.espn.fc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=843848932">843848932</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/espn-fc-soccer/id843848932?mt=8&uo=4">https://itunes.apple.com/us/app/espn-fc-soccer/id843848932?mt=8&uo=4</a>
**App Version:** 4.3.5
**Seller:** ESPN Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/espn/id317469187?uo=4>© ESPN</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/04/b2/34/04b23482-5b9a-3aa4-1f96-0eb07013dbaf/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11399482/5b4d6bce-934d-11e5-81d1-34ddb9a03434.png)

**Comment by illinikev** [comment]
![espn fc](https://cloud.githubusercontent.com/assets/16004373/11384463/a7417f52-92d5-11e5-8297-4a4e0703cc38.png)
![espn fcsource](https://cloud.githubusercontent.com/assets/16004373/11384465/a918fce2-92d5-11e5-96c0-d4b2f2180d5d.png)

**Comment by ivanov007** [comment]
here's the @illinikev icon with the layer template and the corrected size source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11399482/5b4d6bce-934d-11e5-81d1-34ddb9a03434.png)
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11399619/286815f0-934e-11e5-9463-03e664670952.png
all credit goes to @illinikev

**Comment by illinikev** [comment]
Thanks, as a Football fan, I really missed this icon.

I updated all my other requests to conform with source files and preview. I'll submit some more next Tuesday that I need and any easy requests that are open.

I'll help out as long as I have a copy of PhotoShop.

**Comment by ivanov007** [comment]
@illinikev great, help is always welcome :smile: and keep up that good work :+1:
