### ISSUE TITLE
Chicago Sun-Times: E-Paper

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6859]
**App Name:** Chicago Sun-Times: E-Paper
**Bundle ID:** com.NewspaperDirect.ChicagoSunTimes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=611558612">611558612</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chicago-sun-times-e-paper/id611558612?mt=8&uo=4">https://itunes.apple.com/us/app/chicago-sun-times-e-paper/id611558612?mt=8&uo=4</a>
**App Version:** 4.4.2
**Seller:** Sun-Times New Media
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sun-times-media/id341822958?uo=4>© Sun-Times Media</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/07/c5/85/07c58572-d3ab-fe0e-06cb-8d24576e98e4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11390129/2ba111b0-9347-11e5-9d1d-5affb1401094.png)

**Comment by illinikev** [comment]
![chicagosuntimesepaper](https://cloud.githubusercontent.com/assets/16004373/11384448/879f8b12-92d5-11e5-8f3d-225471e1b76d.png)
![chicagosuntimesepapersource](https://cloud.githubusercontent.com/assets/16004373/11384452/8a4e0cb2-92d5-11e5-82a1-c6547152f137.png)

**Comment by dreamnet** [comment]
@illinikev Looks nice :+1:, but if you want to contribute, please follow [this rules](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon). You need to add a preview of the icon, a direct link to the icon and the (1024x1024px) source file, just like this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11390129/2ba111b0-9347-11e5-9d1d-5affb1401094.png)
https://cloud.githubusercontent.com/assets/2068130/11390129/2ba111b0-9347-11e5-9d1d-5affb1401094.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11390141/47ad696c-9347-11e5-8ea4-8a071b459eea.png

**Comment by illinikev** [comment]
Thanks.I updated all my other requests to conform with source files and preview. I'll submit some more next Tuesday for me and any easy ones that are open.  

I don't need to be on the list.  I'll do some and help out when I can, as long as I have a copy of PhotoShop.
