### ISSUE TITLE
Detroit Free Press for iPhone

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6860]
**App Name:** Detroit Free Press for iPhone
**Bundle ID:** com.gannett.news.local.freep
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=904023476">904023476</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/detroit-free-press-for-iphone/id904023476?mt=8&uo=4">https://itunes.apple.com/us/app/detroit-free-press-for-iphone/id904023476?mt=8&uo=4</a>
**App Version:** 2.5.7
**Seller:** Gannett
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gannett/id404843797?uo=4>© Gannett</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/0d/e6/fc/0de6fcf7-b6c4-8894-fe7d-41b662815b72/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416161/500e495e-940b-11e5-9eeb-dfc804b433ad.png)

**Comment by illinikev** [comment]
![detroit free press](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11411026/d7dc7fe2-9391-11e5-9b8d-77efee22dbfc.png)

![detroit free presssource](https://cloud.githubusercontent.com/assets/16004373/11411031/de28ec3c-9391-11e5-9b9c-7997e2bf20f3.png)

**Comment by dreamnet** [comment]
@illinikev Seems you have forgotten to add the Glasklart style to your above contribution and the source is not 1024x1024px. Here is a correct one:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416161/500e495e-940b-11e5-9eeb-dfc804b433ad.png)
https://cloud.githubusercontent.com/assets/2068130/11416161/500e495e-940b-11e5-9eeb-dfc804b433ad.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11416170/5de97544-940b-11e5-8e9f-e17c8a507018.png
