### ISSUE TITLE
SUBWAY® SUBCARD™

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6862]
**App Name:** SUBWAY® SUBCARD™
**Bundle ID:** com.altaine.SUBCARDGermany
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=464702402">464702402</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/subway-subcard/id464702402?mt=8&uo=4">https://itunes.apple.com/de/app/subway-subcard/id464702402?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Altaine Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/altaine-ltd/id314165720?uo=4>© Altaine Ltd</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/81/e9/3a/81e93a30-bf49-0884-e4dc-1608df7c440c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416949/b364173e-9412-11e5-86d6-dd9bf9807279.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416949/b364173e-9412-11e5-86d6-dd9bf9807279.png)
https://cloud.githubusercontent.com/assets/2068130/11416949/b364173e-9412-11e5-86d6-dd9bf9807279.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11416956/c175050e-9412-11e5-95db-e9641ba7af23.png
