### ISSUE TITLE
Phone Drive - iFile Manager & File Browser

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6863]
**App Name:** Phone Drive - File Manager, Browser & Explorer
**Bundle ID:** com.eightythree.iPhoneDrive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431033044">431033044</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/phone-drive-file-manager-browser/id431033044?mt=8&uo=4">https://itunes.apple.com/us/app/phone-drive-file-manager-browser/id431033044?mt=8&uo=4</a>
**App Version:** 6.3.9
**Seller:** Yew Chen Chung
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eightythree-technology/id431033047?uo=4>© Eightythree Technology</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/2f/a2/cd/2fa2cd90-baff-2d66-2808-a94c8b0a9cf4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18926741/5507ad6a-85b9-11e6-8258-f6975fdf789d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416884/19d02554-9412-11e5-9105-ba1434c85a1b.png)
https://cloud.githubusercontent.com/assets/2068130/11416884/19d02554-9412-11e5-9105-ba1434c85a1b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11416893/27cb5e62-9412-11e5-9030-e1dc923439be.png

**Comment by Anuskuss** [comment]
Needs update (maybe).

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18871093/13a9c7be-84b4-11e6-984f-8338457363a1.png)
https://cloud.githubusercontent.com/assets/20930745/18871093/13a9c7be-84b4-11e6-984f-8338457363a1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18871107/23a271e8-84b4-11e6-99a8-d5ca7006c944.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18871295/119997be-84b5-11e6-944d-03997765418c.png)
https://cloud.githubusercontent.com/assets/20930745/18871295/119997be-84b5-11e6-944d-03997765418c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18871305/20c9f5bc-84b5-11e6-92cb-30dae21ac9fb.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18871404/8cdbc190-84b5-11e6-8e29-9dbea8b69e1b.png)
https://cloud.githubusercontent.com/assets/20930745/18871404/8cdbc190-84b5-11e6-8e29-9dbea8b69e1b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18871421/9b9adf9a-84b5-11e6-815f-d9f21c8837d6.png

**Comment by dreamnet** [comment]
Hm, I don't like it with the folder - we keep the old style for this app.
