### ISSUE TITLE
Mach Drive - Cloud File Manager

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6864]
**App Name:** Mach Drive - Cloud File Manager
**Bundle ID:** com.machsoftwaredesign.driveios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=980435179">980435179</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mach-drive-cloud-file-manager/id980435179?mt=8&uo=4">https://itunes.apple.com/us/app/mach-drive-cloud-file-manager/id980435179?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Mach Software Design
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mach-software-design/id327826899?uo=4>© Mach Software Design</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/8e/24/60/8e246036-e4fa-480b-ddd7-c5a45762c039/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416821/9034bb5c-9411-11e5-807e-c0e378bc3dbc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11416821/9034bb5c-9411-11e5-807e-c0e378bc3dbc.png)
https://cloud.githubusercontent.com/assets/2068130/11416821/9034bb5c-9411-11e5-807e-c0e378bc3dbc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11416829/9ede8d0e-9411-11e5-80d0-6d8d63e17fcb.png

**Comment by Trubbel** [comment]
It's a rather catchy name and artwork if I say so myself, haha.

**Comment by dreamnet** [comment]
@Trubbel :laughing:
