### ISSUE TITLE
Total files pro

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6865]
**App Name:** Total files pro
**Bundle ID:** it.appideas.totaldownloader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=522661666">522661666</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/total-files-pro/id522661666?mt=8&uo=4">https://itunes.apple.com/us/app/total-files-pro/id522661666?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** App Ideas S.r.l.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/app-ideas/id522661689?uo=4">© App Ideas</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/82/94/f3/8294f321-8905-6932-4d34-bf9623c69f94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43356938-bd72797e-9279-11e8-872b-4e1af0cd7756.png)

**Comment by Anuskuss** [comment]
If it's possible without the "PRO" because that's the way the app icon is displayed. This way it can also be used for the free version (**it.appideas.totaldownloader-free**).

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11456633/59e149e6-968f-11e5-8423-c63af25a93c8.png)
https://cloud.githubusercontent.com/assets/2068130/11456633/59e149e6-968f-11e5-8423-c63af25a93c8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11456635/67df2496-968f-11e5-9062-061efe1451fe.png

**Comment by l8er4now** [comment]
Needs an update

**App Name:** Total files pro
**Bundle ID:** it.appideas.totaldownloader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=522661666">522661666</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/total-files-pro/id522661666?mt=8&uo=4">https://itunes.apple.com/us/app/total-files-pro/id522661666?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** App Ideas S.r.l.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/app-ideas/id522661689?uo=4">© App Ideas</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/82/94/f3/8294f321-8905-6932-4d34-bf9623c69f94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43356938-bd72797e-9279-11e8-872b-4e1af0cd7756.png)
https://user-images.githubusercontent.com/2068130/43356938-bd72797e-9279-11e8-872b-4e1af0cd7756.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43356942-caa274c8-9279-11e8-87ca-e8bbb08c3dc5.png
