### ISSUE TITLE
Gif Player - with Dropbox Gif viewer and link downloader

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6866]
**App Name:** Gif Player - with Dropbox Gif viewer and link downloader
**Bundle ID:** com.adagissimo.GifBox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=660637680">660637680</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gif-player-dropbox-gif-viewer/id660637680?mt=8&uo=4">https://itunes.apple.com/us/app/gif-player-dropbox-gif-viewer/id660637680?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** Notable Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/notable-group/id646605989?uo=4>© Notable Group</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/52/9e/02/529e02dc-fc05-17d7-5b9d-f0d50a214f61/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11456883/a384fdc8-9698-11e5-915e-1529f98a0c6f.png)

**Comment by Anuskuss** [comment]
Same icon for *Gif Viewer - with camera roll Gif player and web Gif search engine* (**com.adagissimo.GifBoxlite**)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11456883/a384fdc8-9698-11e5-915e-1529f98a0c6f.png)
https://cloud.githubusercontent.com/assets/2068130/11456883/a384fdc8-9698-11e5-915e-1529f98a0c6f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11456886/b23a68c6-9698-11e5-8eac-cb6f1dbee9c1.png
