### ISSUE TITLE
365Scores - Basketball. Soccer, Football Scores & Standings

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6867]
**App Name:** 365Scores - Basketball. Soccer, Football Scores & Standings
**Bundle ID:** com.365scores.365scroesapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571801488">571801488</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/365scores-basketball.-soccer/id571801488?mt=8&uo=4">https://itunes.apple.com/us/app/365scores-basketball.-soccer/id571801488?mt=8&uo=4</a>
**App Version:** 3.6.5
**Seller:** 365Scores LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/365scores/id571801871?uo=4>© 365Scores</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/fd/45/fd/fd45fde5-c5ab-0064-29fc-28025a1e15d4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11456600/8246998c-968e-11e5-9aa9-cba6f6f6e848.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11456600/8246998c-968e-11e5-9aa9-cba6f6f6e848.png)
https://cloud.githubusercontent.com/assets/2068130/11456600/8246998c-968e-11e5-9aa9-cba6f6f6e848.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11456605/90fc341e-968e-11e5-8e48-c99b0be02bf5.png
