### ISSUE TITLE
Awesome Screenshot for Safari

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6868]
**App Name:** Awesome Screenshot for Safari
**Bundle ID:** com.diigo.SafariShot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=918780145">918780145</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/awesome-screenshot-for-safari/id918780145?mt=8&uo=4">https://itunes.apple.com/us/app/awesome-screenshot-for-safari/id918780145?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Diigo
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/diigo-inc./id335006603?uo=4>© Diigo Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/79/74/f5/7974f554-4a8b-75dc-6d29-66be2424806e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16902739/e9a3bea4-4c67-11e6-9349-4e9b3b77ae49.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11458517/e395f3d0-96c1-11e5-8906-60be8287ddf3.png)
https://cloud.githubusercontent.com/assets/2068130/11458517/e395f3d0-96c1-11e5-8906-60be8287ddf3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11458522/f2d9c65a-96c1-11e5-8c4e-e5ee4381b858.png

**Comment by Anuskuss** [comment]
@dreamnet Can you make the lines a bit thicker?

**Comment by dreamnet** [comment]
@Anuskuss Ya know, you are driving me crazy... :imp: 
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16902739/e9a3bea4-4c67-11e6-9349-4e9b3b77ae49.png)
https://cloud.githubusercontent.com/assets/2068130/16902739/e9a3bea4-4c67-11e6-9349-4e9b3b77ae49.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16902770/c8497b44-4c68-11e6-8f4f-c2b1e154b360.png

**Comment by Anuskuss** [comment]
@dreamnet Thanks mate, I appreciate your work and patience. I know you do this on your free time and I'm kind of annoying :stuck_out_tongue:
