### ISSUE TITLE
Weafo - file transfer app to exchange large size video and photo by WiFi sharing

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#6869]
**App Name:** Weafo - file transfer app to exchange large size video and photo by WiFi sharing
**Bundle ID:** com.booltinteam.Weafo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=956868440">956868440</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weafo-file-transfer-app-to/id956868440?mt=8&uo=4">https://itunes.apple.com/us/app/weafo-file-transfer-app-to/id956868440?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** Mohammad Khoman
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mohammad-khoman/id921961117?uo=4>© Mohammad Khoman</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/45/c3/f3/45c3f3e2-d0e0-a4ac-88d3-616acb05fb40/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11417131/4fd52378-9414-11e5-8faf-67732d6b99f9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11417131/4fd52378-9414-11e5-8faf-67732d6b99f9.png)
https://cloud.githubusercontent.com/assets/2068130/11417131/4fd52378-9414-11e5-8faf-67732d6b99f9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11417137/5de0e272-9414-11e5-8e2c-fe961345f6c5.png
