### ISSUE TITLE
Meteogram for iPhone

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6875]
**App Name:** Meteogram for iPhone
**Bundle ID:** se.meteogram.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=410014375">410014375</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/meteogram-for-iphone/id410014375?mt=8&uo=4">https://itunes.apple.com/us/app/meteogram-for-iphone/id410014375?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Michal Frankowski
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/michal-frankowski/id330935779?uo=4>© Michal Frankowski</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/6f/d9/92/6fd9926b-ff00-a7b8-92fc-1a1b17f3724f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11447598/38facfb8-950e-11e5-961a-24f9eeeb358b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11447598/38facfb8-950e-11e5-961a-24f9eeeb358b.png)
https://cloud.githubusercontent.com/assets/3090247/11447598/38facfb8-950e-11e5-961a-24f9eeeb358b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11447597/38bda336-950e-11e5-85d9-bb7c7be725c5.png
