### ISSUE TITLE
Animation Desk™ for iPhone

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6881]
**App Name:** Animation Desk™ for iPhone
**Bundle ID:** com.kdanmobile.AnimationDesk-iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448938192">448938192</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/animation-desk-for-iphone/id448938192?mt=8&uo=4">https://itunes.apple.com/us/app/animation-desk-for-iphone/id448938192?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Kdan Mobile Software LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kdan-mobile-software-ltd/id318936474?uo=4>© Kdan Mobile Software LTD</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/76/53/10/76531059-1e00-1c07-e8bf-73ac626f0dd3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11919255/b2545478-a74d-11e5-9f3c-ee3d24f01aa3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11919255/b2545478-a74d-11e5-9f3c-ee3d24f01aa3.png)
https://cloud.githubusercontent.com/assets/2068130/11919255/b2545478-a74d-11e5-9f3c-ee3d24f01aa3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11919256/c04846f2-a74d-11e5-8c58-1bc0b26fdf41.png
