### ISSUE TITLE
Blend: The Game

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6884]
**App Name:** Blend: The Game
**Bundle ID:** com.broermandesign.blend
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=880961406">880961406</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blend-the-game/id880961406?mt=8&uo=4">https://itunes.apple.com/us/app/blend-the-game/id880961406?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Matthew Broerman
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/matthew-broerman/id474065956?uo=4>© Matthew Broerman</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/45/0a/3c/450a3c54-292d-33c5-bacf-433092c92f32/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553468/38963870-998f-11e5-823e-77995e6a442a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553468/38963870-998f-11e5-823e-77995e6a442a.png)
https://cloud.githubusercontent.com/assets/2068130/11553468/38963870-998f-11e5-823e-77995e6a442a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11553476/4728a562-998f-11e5-9604-63f886eba2ec.png
