### ISSUE TITLE
Bluristic - Pan & Track

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6885]
**App Name:** Bluristic - Pan & Track
**Bundle ID:** com.pytebyte.Bluristic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=879408799">879408799</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bluristic-pan-track/id879408799?mt=8&uo=4">https://itunes.apple.com/us/app/bluristic-pan-track/id879408799?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Johannes Pfahler
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/johannes-pfahler/id725328483?uo=4>© Johannes Pfahler</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/8f/64/91/8f649129-adff-6941-b456-c15fcd2c5c09/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11919483/8be40732-a754-11e5-8d4b-26344806c009.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11919483/8be40732-a754-11e5-8d4b-26344806c009.png)
https://cloud.githubusercontent.com/assets/2068130/11919483/8be40732-a754-11e5-8d4b-26344806c009.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11919484/9acf0c6a-a754-11e5-879c-9947add0e68f.png
:laughing:

**Comment by ivanov007** [comment]
yup, it looks good :+1:
