### ISSUE TITLE
Gameshow Buzz Button

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6886]
**App Name:** Gameshow Buzz Button
**Bundle ID:** com.brennanmoymedia.Buzz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368599059">368599059</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gameshow-buzz-button/id368599059?mt=8&uo=4">https://itunes.apple.com/us/app/gameshow-buzz-button/id368599059?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Brennan Moy Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brennanmoymedia/id319086978?uo=4>© BrennanMoyMedia</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/78/3f/70/783f70d0-8aad-a9fe-a92d-c705eac87ec8/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11583222/bd0e5f56-9a57-11e5-8080-29ac91829cb9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11583222/bd0e5f56-9a57-11e5-8080-29ac91829cb9.png)
https://cloud.githubusercontent.com/assets/2068130/11583222/bd0e5f56-9a57-11e5-8080-29ac91829cb9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11583228/cb7ee290-9a57-11e5-875a-d08b953fc04d.png
