### ISSUE TITLE
Buzzer Panel

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6887]
**App Name:** Buzzer Panel
**Bundle ID:** biz.markus-schneider
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=517511198">517511198</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/buzzer-panel/id517511198?mt=8&uo=4">https://itunes.apple.com/us/app/buzzer-panel/id517511198?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Markus Schneider
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/markus-schneider/id517511201?uo=4>© Markus Schneider</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/c5/e6/8f/c5e68f19-7353-1c88-c64d-0cf129524055/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11913528/2020237a-a667-11e5-920a-17d0943815f3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11793876/5bbd0072-a2ae-11e5-8d86-3d7d99d9188d.png)
https://cloud.githubusercontent.com/assets/2068130/11793876/5bbd0072-a2ae-11e5-8d86-3d7d99d9188d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11793889/70b943fa-a2ae-11e5-8e29-4d8e3abef7ae.png
...maybe?
