### ISSUE TITLE
CALC Swift - The Customizable Calculator

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6888]
**App Name:** CALC Swift - The Customizable Calculator
**Bundle ID:** co.qapps.calc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=878851717">878851717</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calc-swift-customizable-calculator/id878851717?mt=8&uo=4">https://itunes.apple.com/us/app/calc-swift-customizable-calculator/id878851717?mt=8&uo=4</a>
**App Version:** 3.4.16
**Seller:** QApps LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/qapps-llc/id395652397?uo=4>© QApps LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/2e/fb/5d/2efb5dda-c410-076d-83b2-66c9fbbd4138/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553339/0a5ad912-998e-11e5-8e10-c9a91e21b8bd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553339/0a5ad912-998e-11e5-8e10-c9a91e21b8bd.png)
https://cloud.githubusercontent.com/assets/2068130/11553339/0a5ad912-998e-11e5-8e10-c9a91e21b8bd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11553347/18b99c6e-998e-11e5-8db9-4b405ea9d511.png
