### ISSUE TITLE
Draw Calendar - Fun Scheduling and Events

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6889]
**App Name:** Draw Calendar - Fun Scheduling and Events
**Bundle ID:** com.fishingtonstudios.sketchcalendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=815370160">815370160</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/draw-calendar-fun-scheduling/id815370160?mt=8&uo=4">https://itunes.apple.com/us/app/draw-calendar-fun-scheduling/id815370160?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** Fishington Studios
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fishington-studios/id344044425?uo=4>© Fishington Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/e5/79/b7/e579b7ce-29d5-c0f1-e5ce-4077c9f005ca/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553288/852dfa62-998d-11e5-8a80-37be7d735cc3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553288/852dfa62-998d-11e5-8a80-37be7d735cc3.png)
https://cloud.githubusercontent.com/assets/2068130/11553288/852dfa62-998d-11e5-8a80-37be7d735cc3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11553292/9343de78-998d-11e5-9e58-3820018a0413.png
