### ISSUE TITLE
Contacts Call and Message Reminder Pro

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6890]
**App Name:** Contacts Call and Message Reminder Pro
**Bundle ID:** com.domainname.CallMessageReminder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032693930">1032693930</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/contacts-call-message-reminder/id1032693930?mt=8&uo=4">https://itunes.apple.com/us/app/contacts-call-message-reminder/id1032693930?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Giacomo Guglielmi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/giacomo-guglielmi/id507748829?uo=4>© Giacomo Guglielmi</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/8c/4f/8e/8c4f8e44-c02f-258c-43fb-a070e4bec5d4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11766150/13c79092-a179-11e5-8b7b-ed609de19916.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11766150/13c79092-a179-11e5-8b7b-ed609de19916.png)
https://cloud.githubusercontent.com/assets/2068130/11766150/13c79092-a179-11e5-8b7b-ed609de19916.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11766151/2231a10e-a179-11e5-82a1-363aaf18cba9.png
