### ISSUE TITLE
Caroline's Working

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6891]
**App Name:** Caroline's Working
**Bundle ID:** com.soulgame.cw
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1021897571">1021897571</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/carolines-working/id1021897571?mt=8&uo=4">https://itunes.apple.com/us/app/carolines-working/id1021897571?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** SOULGAME INFORMATION CO LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/soulgame-information-co-ltd/id561651780?uo=4>© SOULGAME INFORMATION CO LTD</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/17/e7/65/17e7659b-8798-a485-909a-ae8b9bc7f6f9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11912520/7a7eb95c-a640-11e5-9ed4-61974b68c37b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11912520/7a7eb95c-a640-11e5-9ed4-61974b68c37b.png)
https://cloud.githubusercontent.com/assets/2068130/11912520/7a7eb95c-a640-11e5-9ed4-61974b68c37b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11912522/895c30f8-a640-11e5-803b-c53bffd12165.png
