### ISSUE TITLE
CleanUp Suite – Quickly and easily clean duplicates from your address book

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6893]
**App Name:** CleanUp Suite – Quickly and easily clean duplicates from your address book
**Bundle ID:** cleanupsuite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=570900107">570900107</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cleanup-suite-quickly-easily/id570900107?mt=8&uo=4">https://itunes.apple.com/us/app/cleanup-suite-quickly-easily/id570900107?mt=8&uo=4</a>
**App Version:** 5.0.3
**Seller:** Business Contacts Solutions, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/business-contacts-solutions/id675697151?uo=4>© Business Contacts Solutions, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/df/66/1b/df661bcd-3585-95fd-9daa-0588ef65885e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553014/ea9fa4c0-998a-11e5-8645-179247e339d4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553014/ea9fa4c0-998a-11e5-8645-179247e339d4.png)
https://cloud.githubusercontent.com/assets/2068130/11553014/ea9fa4c0-998a-11e5-8645-179247e339d4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11553023/f9d0c7bc-998a-11e5-89a0-c26bbea6a359.png
