### ISSUE TITLE
GoButler

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6895]
**App Name:** GoButler
**Bundle ID:** com.gobutler.gobutlerios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1033997589">1033997589</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gobutler/id1033997589?mt=8&uo=4">https://itunes.apple.com/us/app/gobutler/id1033997589?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** GoButler, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gobutler-inc./id1033997588?uo=4>© GoButler, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/e7/bc/55/e7bc559f-e045-95dd-9f3f-5621a337bfee/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11523783/94db969a-98c5-11e5-9e42-bed753854165.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11523783/94db969a-98c5-11e5-9e42-bed753854165.png)
https://cloud.githubusercontent.com/assets/2068130/11523783/94db969a-98c5-11e5-9e42-bed753854165.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11523794/a41c6422-98c5-11e5-8158-10ab8f74a618.png
