### ISSUE TITLE
Guvera Music - Free Music Streaming Radio & Playlist Player

### ISSUE THREAD

**Issue by thr-33** [glasklart/hd#6896]
**App Name:** Guvera Music - Free Music Streaming Radio & Playlist Player
**Bundle ID:** guvera.mobile.Guvera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555523050">555523050</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/guvera-music-free-music-streaming/id555523050?mt=8&uo=4">https://itunes.apple.com/us/app/guvera-music-free-music-streaming/id555523050?mt=8&uo=4</a>
**App Version:** 2.7.2
**Seller:** Guvera Australia Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/guvera-australia-pty-ltd/id555523053?uo=4>© Guvera Australia Pty Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/14/aa/5e/14aa5ea2-cacb-9841-0d78-f4cab7ee8385/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11552830/3efcdc1a-9989-11e5-8843-6b04b7ba0332.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11552830/3efcdc1a-9989-11e5-8843-6b04b7ba0332.png)
https://cloud.githubusercontent.com/assets/2068130/11552830/3efcdc1a-9989-11e5-8843-6b04b7ba0332.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11552835/4e0bef20-9989-11e5-8e69-16f2b9845071.png
