### ISSUE TITLE
mydlink Lite

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6897]
**App Name:** mydlink Lite
**Bundle ID:** com.dlink.mydlink
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=372571229">372571229</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mydlink-lite/id372571229?mt=8&uo=4">https://itunes.apple.com/us/app/mydlink-lite/id372571229?mt=8&uo=4</a>
**App Version:** 3.5.1
**Seller:** D-Link Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/d-link-corporation/id372571232?uo=4>© D-Link Corporation</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/ec/32/a4/ec32a4e9-0277-f2e9-d34f-bbafed9c4899/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11552922/4be97036-998a-11e5-89a8-a129ea51c226.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11552922/4be97036-998a-11e5-89a8-a129ea51c226.png)
https://cloud.githubusercontent.com/assets/2068130/11552922/4be97036-998a-11e5-89a8-a129ea51c226.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11552932/5aadb456-998a-11e5-81be-bf33691cb0af.png
