### ISSUE TITLE
HauteLook | Nordstrom Rack

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6898]
**App Name:** HauteLook | Nordstrom Rack
**Bundle ID:** com.hautelook.hautelook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390783984">390783984</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hautelook-nordstrom-rack/id390783984?mt=8&uo=4">https://itunes.apple.com/us/app/hautelook-nordstrom-rack/id390783984?mt=8&uo=4</a>
**App Version:** 3.6.2
**Seller:** HauteLook
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hautelook/id390783987?uo=4>© HauteLook</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/e7/c2/eb/e7c2eb03-84d8-45ae-6025-3b56dd93c837/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11582550/93ab1dc2-9a50-11e5-878c-0ebf788c0c8e.png)

**Comment by illinikev** [comment]
![hautelook](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11577499/9f3784cc-99e3-11e5-9c47-3b31e173f1b2.png)

https://cloud.githubusercontent.com/assets/16004373/11577502/a37b5ad6-99e3-11e5-85fa-e56ef47158c1.png

**Comment by dreamnet** [comment]
@illinikev Very good, there are just some errors in your contribution:
- Seems you have not applied the Glasklart layer style in Photoshop
- You need to add a direct link to the icon
- Source file must be 1024x1024px

Here is how it should be:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11582550/93ab1dc2-9a50-11e5-878c-0ebf788c0c8e.png)
https://cloud.githubusercontent.com/assets/2068130/11582550/93ab1dc2-9a50-11e5-878c-0ebf788c0c8e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11582564/a739697a-9a50-11e5-8e27-99799f2db9a9.png
