### ISSUE TITLE
NBC Sports

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6899]
**App Name:** NBC Sports
**Bundle ID:** com.nbcuni.com.nbcsports.liveextra
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542511686">542511686</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nbc-sports/id542511686?mt=8&uo=4">https://itunes.apple.com/us/app/nbc-sports/id542511686?mt=8&uo=4</a>
**App Version:** 4.7.3
**Seller:** NBCUniversal Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nbcuniversal-media-llc/id303544359?uo=4>© NBCUniversal Media, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/60/d6/5c/60d65cdd-699c-0523-ea3f-7e0f1b150b58/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18808849/9328026a-826d-11e6-93bd-f7e3c2f0554a.png)

**Comment by illinikev** [comment]
![nbcsports](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11577486/8b354982-99e3-11e5-8978-c2e6c46fbc31.png)

https://cloud.githubusercontent.com/assets/16004373/11577488/92434170-99e3-11e5-9514-daef55f79049.png

**Comment by dreamnet** [comment]
Used the source from @illinikev:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11582636/637708c2-9a51-11e5-977f-13304f30153a.png)
https://cloud.githubusercontent.com/assets/2068130/11582636/637708c2-9a51-11e5-977f-13304f30153a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11582639/71da99d8-9a51-11e5-8702-7652af6b31af.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18808849/9328026a-826d-11e6-93bd-f7e3c2f0554a.png)
https://cloud.githubusercontent.com/assets/2068130/18808849/9328026a-826d-11e6-93bd-f7e3c2f0554a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18808852/a2943494-826d-11e6-961d-3cfa9a30a08e.png
