### ISSUE TITLE
Gmail - email from Google

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#69]
**App Name:** Gmail - email from Google
**Bundle ID:** com.google.Gmail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=422689480">422689480</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gmail-email-from-google/id422689480?mt=8&uo=4">https://itunes.apple.com/us/app/gmail-email-from-google/id422689480?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPadFourthGen, iPhone5s, iPadMini4G, iPhone5c, iPadThirdGen4G, iPodTouchFifthGen, iPadThirdGen, iPadMini, iPad23G, iPhone4S, iPad2Wifi, iPhone4, iPhone6Plus, iPhone5, iPhone6, iPadFourthGen4G
**Original Artwork:**
<img src="http://a1290.phobos.apple.com/us/r30/Purple3/v4/6f/06/d6/6f06d6c1-8dd6-73e9-b20e-c85a18f78bd8/pr_source.png?downloadKey=1427274410_0e8223ece0ae7b05ffccf0f2725f8e88" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6814132/64833a50-d252-11e4-87e5-6ed3ab5a0f35.png)

**Comment by zmathiasz** [comment]
@dreamnet On providing an update for iPhone 6+ users, is this how you would like it done?  I was guessing that if your site doesn't have a 3x icon listed that it need a source file.  Or is there a better way to do it?

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6814132/64833a50-d252-11e4-87e5-6ed3ab5a0f35.png)
https://cloud.githubusercontent.com/assets/10950389/6814132/64833a50-d252-11e4-87e5-6ed3ab5a0f35.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6814147/7e09363c-d252-11e4-84c4-ab4bb70326a4.png

**Comment by dreamnet** [comment]
@zmathiasz That's perfect. I reopen the issue, the icon in the Glaklart theme and add a icon to the @3x extra pack. :+1:
