### ISSUE TITLE
ParkChicago

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6900]
**App Name:** ParkChicago
**Bundle ID:** com.passportparking.mobile.chicagometers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=686658594">686658594</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parkchicago/id686658594?mt=8&uo=4">https://itunes.apple.com/us/app/parkchicago/id686658594?mt=8&uo=4</a>
**App Version:** 5.1.4
**Seller:** Passport Parking, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/passport-parking-llc/id501324970?uo=4>© Passport Parking, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/20/e6/7a/20e67a22-5841-0696-b60f-d613dbce961f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553119/f20e636c-998b-11e5-8510-cf59df5d498d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553119/f20e636c-998b-11e5-8510-cf59df5d498d.png)
https://cloud.githubusercontent.com/assets/2068130/11553119/f20e636c-998b-11e5-8510-cf59df5d498d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11553123/0160454c-998c-11e5-9ab8-02788060d883.png
