### ISSUE TITLE
South Shore

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6901]
**App Name:** South Shore
**Bundle ID:** com.NICTD.SouthShore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=868220002">868220002</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/south-shore/id868220002?mt=8&uo=4">https://itunes.apple.com/us/app/south-shore/id868220002?mt=8&uo=4</a>
**App Version:** 1.141
**Seller:** Bytemark, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bytemark-inc./id925346607?uo=4>© Bytemark, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/52/14/98/521498e5-331c-6bce-0a08-b0f220a57044/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![com nictd southshore 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553071/7f83a9e2-998b-11e5-8ea7-5b3fbae0ad1d.png)

**Comment by dreamnet** [comment]
![com nictd southshore 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553071/7f83a9e2-998b-11e5-8ea7-5b3fbae0ad1d.png)
https://cloud.githubusercontent.com/assets/2068130/11553071/7f83a9e2-998b-11e5-8ea7-5b3fbae0ad1d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11553083/8eb5aa64-998b-11e5-9697-d36431278e1b.png
