### ISSUE TITLE
WGN-TV - Chicago Weather Center

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6902]
**App Name:** WGN-TV - Chicago Weather Center
**Bundle ID:** com.wgn.WGN-Weather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447145667">447145667</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wgn-tv-chicago-weather-center/id447145667?mt=8&uo=4">https://itunes.apple.com/us/app/wgn-tv-chicago-weather-center/id447145667?mt=8&uo=4</a>
**App Version:** 3.9.800
**Seller:** TRIBUNE BROADCASTING COMPANY INC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tribune-broadcasting-company/id586932834?uo=4>© Tribune Broadcasting Company</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/e3/26/9e/e3269e7b-15a9-f86a-4480-cd08760df8c0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11582699/24c6cdaa-9a52-11e5-962f-871d13a0af4f.png)

**Comment by illinikev** [comment]
![wgn9weather](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11577431/3e4b4ce8-99e3-11e5-8786-15720d7627e7.png)

https://cloud.githubusercontent.com/assets/16004373/11577436/45ecf8ac-99e3-11e5-9465-33b2f49f2655.png

**Comment by dreamnet** [comment]
Used the source from @illinikev:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11582699/24c6cdaa-9a52-11e5-962f-871d13a0af4f.png)
https://cloud.githubusercontent.com/assets/2068130/11582699/24c6cdaa-9a52-11e5-962f-871d13a0af4f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11582707/34092038-9a52-11e5-9263-282b15c4c567.png
