### ISSUE TITLE
Chicago Sun-Times News

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6903]
**App Name:** Chicago Sun-Times News
**Bundle ID:** com.aggrego.mynetwork.il.chicago
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=930568136">930568136</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/chicago-sun-times-news/id930568136?uo=4">https://apps.apple.com/us/app/chicago-sun-times-news/id930568136?uo=4</a>
**App Version:** 4.29.650039130
**Seller:** Sun-Times New Media
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sun-times-media/id341822958?uo=4">© Sun-Times Media</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/ad/64/c7/ad64c773-999b-1634-f252-b49dc55944d0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60373406-521fbd00-9a00-11e9-9190-c2e34f1d7580.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11553173/71c50ed0-998c-11e5-912c-7b1dc2d8daf8.png)
https://cloud.githubusercontent.com/assets/2068130/11553173/71c50ed0-998c-11e5-912c-7b1dc2d8daf8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11553186/7fcce3d6-998c-11e5-90ca-c0e35c26aae3.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60373406-521fbd00-9a00-11e9-9190-c2e34f1d7580.png)
https://user-images.githubusercontent.com/20930745/60373406-521fbd00-9a00-11e9-9190-c2e34f1d7580.png

Source:
https://user-images.githubusercontent.com/20930745/60373411-564bda80-9a00-11e9-9b1e-6d8072b10862.png
