### ISSUE TITLE
5-0 Radio Police Scanner

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6904]
**App Name:** 5-0 Radio Police Scanner
**Bundle ID:** com.smartestapple.50radiofree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=356336433">356336433</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/5-0-radio-police-scanner/id356336433?mt=8&uo=4">https://itunes.apple.com/us/app/5-0-radio-police-scanner/id356336433?mt=8&uo=4</a>
**App Version:** 39.0
**Seller:** Smartest Apps LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/smartest-apps-llc/id323131781?uo=4>© Smartest Apps LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple2/v4/44/3f/42/443f4264-a025-5fba-9326-632536e033c1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11766530/9c9e353e-a18c-11e5-9632-a8ccdc3e2704.png)

**Comment by illinikev** [comment]
![5-0radiopolicescanner](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11577417/200fe95a-99e3-11e5-859d-71b3143b4182.png)

https://cloud.githubusercontent.com/assets/16004373/11577424/2bf45486-99e3-11e5-9178-5794e67d2a34.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11766530/9c9e353e-a18c-11e5-9632-a8ccdc3e2704.png)
https://cloud.githubusercontent.com/assets/2068130/11766530/9c9e353e-a18c-11e5-9632-a8ccdc3e2704.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11766532/ac9bebf2-a18c-11e5-8ff5-610b250c5261.png

**Comment by Trubbel** [comment]
@dreamnet :open_mouth:
