### ISSUE TITLE
Ai Search - A Smart Search Center

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6905]
**App Name:** Ai Search - A Smart Search Center
**Bundle ID:** com.apix.1search
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=936310061">936310061</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ai-search-smart-search-center/id936310061?mt=8&uo=4">https://itunes.apple.com/us/app/ai-search-smart-search-center/id936310061?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Tao Jiang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tao-jiang/id863909142?uo=4>© Tao Jiang</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/33/89/d6/3389d650-14cb-554f-bd8d-801bee26b03e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764398/f0a8f254-a12d-11e5-988e-fb43c663b0fc.png)

**Comment by illinikev** [comment]
![aisearch](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11577449/57913d84-99e3-11e5-9ca4-75f8685e3d5f.png)

https://cloud.githubusercontent.com/assets/16004373/11577457/5f901a50-99e3-11e5-9df1-ad60460435a5.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764398/f0a8f254-a12d-11e5-988e-fb43c663b0fc.png)
https://cloud.githubusercontent.com/assets/2068130/11764398/f0a8f254-a12d-11e5-988e-fb43c663b0fc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11764401/025bcd78-a12e-11e5-8e25-434999d6f0d1.png
