### ISSUE TITLE
Vidgets

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6906]
**App Name:** Vidgets
**Bundle ID:** com.lesscode.widgetcenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=897374553">897374553</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vidgets/id897374553?mt=8&uo=4">https://itunes.apple.com/us/app/vidgets/id897374553?mt=8&uo=4</a>
**App Version:** 1.2.6
**Seller:** Less Code Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/less-code-ltd/id331433977?uo=4>© Less Code Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/b4/d2/bc/b4d2bc74-f550-dcc8-81a9-10aebf5f5a07/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11583069/1f67664a-9a56-11e5-8290-11f6d9e0401e.png)

**Comment by illinikev** [comment]
![vidgets](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16004373/11577467/6946753a-99e3-11e5-86b8-212d0e843438.png)

https://cloud.githubusercontent.com/assets/16004373/11577472/702fecaa-99e3-11e5-8d7c-9112f0c813d6.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11583069/1f67664a-9a56-11e5-8290-11f6d9e0401e.png)
https://cloud.githubusercontent.com/assets/2068130/11583069/1f67664a-9a56-11e5-8290-11f6d9e0401e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11583076/2db9c08a-9a56-11e5-9b63-27627f3d65dd.png
