### ISSUE TITLE
ViewExif

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6907]
**App Name:** ViewExif
**Bundle ID:** com.skyjos.viewexif
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=945320815">945320815</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/viewexif/id945320815?mt=8&uo=4">https://itunes.apple.com/us/app/viewexif/id945320815?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Steven Zhang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/steven-zhang/id499470116?uo=4>© Steven Zhang</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/88/21/f5/8821f57f-2585-6aac-3e95-8e5c3b41021b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11576068/97953cf6-9a14-11e5-85d8-3ea6c0a12eae.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11576068/97953cf6-9a14-11e5-85d8-3ea6c0a12eae.png)
https://cloud.githubusercontent.com/assets/10730122/11576068/97953cf6-9a14-11e5-85d8-3ea6c0a12eae.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11576060/92f3cd7a-9a14-11e5-98bf-5ae83aad2fe7.png
