### ISSUE TITLE
work in shifts? ShiftWorkingCalendar Free

### ISSUE THREAD

**Issue by kelington** [glasklart/hd#6908]
**App Name:** work in shifts? ShiftWorkingCalendar Free
**Bundle ID:** com.kskys.ShiftCalendarFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=547035346">547035346</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/work-in-shifts-shiftworkingcalendar/id547035346?mt=8&uo=4">https://itunes.apple.com/us/app/work-in-shifts-shiftworkingcalendar/id547035346?mt=8&uo=4</a>
**App Version:** 2.7.0
**Seller:** Kosuke Hamada
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shinpei-studio/id515812363?uo=4>© SHINPEI STUDIO</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/9f/b9/11/9fb9114e-0e5a-9b3e-11af-a38b6ec095f9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764318/75adef5c-a12b-11e5-86aa-26efdb4f55a6.png)

**Comment by dreamnet** [comment]
@kelington Please use our [iTunes Data Crawler](http://getart.dreamnet.at) for [requesting icons](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request). I correct your request above.

**Comment by kelington** [comment]
Thank you! First time here so I was trying to find all the info from my phone.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764318/75adef5c-a12b-11e5-86aa-26efdb4f55a6.png)
https://cloud.githubusercontent.com/assets/2068130/11764318/75adef5c-a12b-11e5-86aa-26efdb4f55a6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11764321/83b31442-a12b-11e5-8145-696ff843aad6.png
