### ISSUE TITLE
Snapchat Log

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6910]
**App Name:** Snapchat Log
 **Bundle ID:** com.tigisoftware.Snapchat-Log
 **Version:** 1.00
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/3090247/11591579/75a893f0-9a5e-11e5-84ec-62885b8c6896.png" width="150" height="150" />
 **Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764252/03d40030-a129-11e5-8823-eec4a1224c74.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764252/03d40030-a129-11e5-8823-eec4a1224c74.png)
https://cloud.githubusercontent.com/assets/2068130/11764252/03d40030-a129-11e5-8823-eec4a1224c74.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11764256/125987b0-a129-11e5-9d9d-cffd9f4f6efb.png
