### ISSUE TITLE
Tiny PDF - PDF Reader, Fill Forms & Annotate PDF

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6912]
**App Name:** Tiny PDF - PDF Reader, Fill Forms & Annotate PDF
**Bundle ID:** com.btgs.pdfmaster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=596655478">596655478</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tiny-pdf-pdf-reader-fill-forms/id596655478?mt=8&uo=4">https://itunes.apple.com/us/app/tiny-pdf-pdf-reader-fill-forms/id596655478?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Appxy Information Technology Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appxy/id760100924?uo=4>© Appxy</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/a1/cb/a1/a1cba15d-4e75-a712-dcdf-536c809bdf4e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764131/627ba458-a124-11e5-9444-9092e3e08592.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764131/627ba458-a124-11e5-9444-9092e3e08592.png)
https://cloud.githubusercontent.com/assets/2068130/11764131/627ba458-a124-11e5-9444-9092e3e08592.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11764135/73774726-a124-11e5-88f0-b23403760e21.png
