### ISSUE TITLE
Time & Sun - World Clock Widget with worldwide sunrise and sunset times

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6913]
**App Name:** Time & Sun - World Clock Widget with worldwide sunrise and sunset times
**Bundle ID:** uk.co.gordiychukandriy.sunrise
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1024201761">1024201761</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/time-sun-world-clock-widget/id1024201761?mt=8&uo=4">https://itunes.apple.com/us/app/time-sun-world-clock-widget/id1024201761?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Andriy Gordiychuk
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/andriy-gordiychuk/id347064284?uo=4>© Andriy Gordiychuk</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/c3/4b/f5/c34bf5a6-823c-bd4c-af78-8f41e9f9867c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764148/f2707e9e-a124-11e5-9f0a-494879547785.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764148/f2707e9e-a124-11e5-9f0a-494879547785.png)
https://cloud.githubusercontent.com/assets/2068130/11764148/f2707e9e-a124-11e5-9f0a-494879547785.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11764151/021e92cc-a125-11e5-9c0d-147205a00d34.png
