### ISSUE TITLE
Write - Notes & Writing

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6914]
**App Name:** Write - Notes & Writing
**Bundle ID:** com.danielvw.Write2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426253668">426253668</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/write-notes-writing/id426253668?mt=8&uo=4">https://itunes.apple.com/us/app/write-notes-writing/id426253668?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** Daniel Widjaja
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/daniel-v.w/id356865981?uo=4>© Daniel V.W</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/3c/89/82/3c898259-9073-1204-6b28-2aeb38e179d7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764087/31e8b4c6-a123-11e5-9447-82604948fecd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764087/31e8b4c6-a123-11e5-9447-82604948fecd.png)
https://cloud.githubusercontent.com/assets/2068130/11764087/31e8b4c6-a123-11e5-9447-82604948fecd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11764091/3ff61aea-a123-11e5-88ae-205f3d77b130.png
