### ISSUE TITLE
Cortana

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6915]
**App Name:** Cortana
**Bundle ID:** com.microsoft.bing.HalseyAssistant
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1054501703">1054501703</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cortana/id1054501703?mt=8&uo=4">https://itunes.apple.com/us/app/cortana/id1054501703?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/9b/fc/cf/9bfccf4f-1c2b-abeb-838b-b2b723d90f71/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764178/1bad0d4e-a126-11e5-9f59-743d9372e746.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764178/1bad0d4e-a126-11e5-9f59-743d9372e746.png)
https://cloud.githubusercontent.com/assets/2068130/11764178/1bad0d4e-a126-11e5-9f59-743d9372e746.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11764181/2ac7d5f2-a126-11e5-88a1-4f345aa43345.png

**Comment by Trubbel** [comment]
@dreamnet Wow, nice one!

**Comment by dreamnet** [comment]
@Trubbel :wink:

**Comment by ivanov007** [comment]
very nice indeed, I will install thins app just to see how it looks :smile:

**Comment by Trubbel** [comment]
@ivanov007 I was gonna do that as well, but apparently it's not available in the Swedish store. :unamused:

**Comment by ivanov007** [comment]
mhhh yeah neither in the mexican store, that's just nice :disappointed:
