### ISSUE TITLE
Firefox Focus: The privacy browser

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6916]
**App Name:** Firefox Focus: The privacy browser
**Bundle ID:** org.mozilla.ios.Focus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1055677337">1055677337</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/firefox-focus-privacy-browser/id1055677337?mt=8&uo=4">https://itunes.apple.com/us/app/firefox-focus-privacy-browser/id1055677337?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Mozilla Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mozilla/id380366936?uo=4">© Mozilla</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/09/e0/e5/09e0e5a0-b68c-6be1-775d-e9fcc415c236/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22629726/39e8249e-ebec-11e6-95b0-075ccb7dbef3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764069/a22d13cc-a122-11e5-8926-93bdaa84af6c.png)
https://cloud.githubusercontent.com/assets/2068130/11764069/a22d13cc-a122-11e5-8926-93bdaa84af6c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11764073/afc9cade-a122-11e5-97ec-44d69c3b117b.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Firefox Focus: The privacy browser
**Bundle ID:** org.mozilla.ios.Focus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1055677337">1055677337</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/firefox-focus-privacy-browser/id1055677337?mt=8&uo=4">https://itunes.apple.com/us/app/firefox-focus-privacy-browser/id1055677337?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Mozilla Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mozilla/id380366936?uo=4">© Mozilla</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/09/e0/e5/09e0e5a0-b68c-6be1-775d-e9fcc415c236/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22629726/39e8249e-ebec-11e6-95b0-075ccb7dbef3.png)
https://cloud.githubusercontent.com/assets/2068130/22629726/39e8249e-ebec-11e6-95b0-075ccb7dbef3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22629728/48cd1a78-ebec-11e6-94ec-4b07006313cc.png
