### ISSUE TITLE
AntRec - HD Screen Recorder

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#6917]
**App Name:** AntRec - HD Screen Recorder
**Bundle ID:** tv.antlive.rec
**Version:** 1.7.0
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://pbs.twimg.com/profile_images/635643343133798400/CSig921F.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764053/0a925d1a-a122-11e5-9a7f-f3bc1ea95a8e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11764053/0a925d1a-a122-11e5-9a7f-f3bc1ea95a8e.png)
https://cloud.githubusercontent.com/assets/2068130/11764053/0a925d1a-a122-11e5-9a7f-f3bc1ea95a8e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11764055/18ffb6b8-a122-11e5-80a0-920924ee8a16.png
