### ISSUE TITLE
Flixster Video

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6918]
**App Name:** Flixster Video
**Bundle ID:** com.flixster.video
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979754239">979754239</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flixster-video/id979754239?mt=8&uo=4">https://itunes.apple.com/us/app/flixster-video/id979754239?mt=8&uo=4</a>
**App Version:** 2.6.0
**Seller:** Flixster, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/flixster-inc./id672117627?uo=4>© Flixster, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/83/26/ea/8326ea44-ee53-47d5-3315-709e93cab169/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11803762/3092c35a-a2fe-11e5-9468-023ce854f7c9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11803762/3092c35a-a2fe-11e5-9468-023ce854f7c9.png)
https://cloud.githubusercontent.com/assets/2068130/11803762/3092c35a-a2fe-11e5-9468-023ce854f7c9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11803767/3fe2b7c0-a2fe-11e5-9600-74e8598afb29.png

**Comment by ivanov007** [comment]
wow :open_mouth:
