### ISSUE TITLE
Super Dangerous Dungeons

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#6919]
**App Name:** Super Dangerous Dungeons
**Bundle ID:** com.adventureislands.dangerousdungeons
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1006111149">1006111149</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-dangerous-dungeons/id1006111149?mt=8&uo=4">https://itunes.apple.com/us/app/super-dangerous-dungeons/id1006111149?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Jussi Simpanen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jussi-simpanen/id904740790?uo=4>© Jussi Simpanen</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/69/27/6d/69276d7b-6aea-b97c-d2ea-d583f3e89dd5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11803423/0de9b4ec-a2fb-11e5-8fc7-37db10bf7658.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11795158/7ab59582-a2b5-11e5-8aaf-d9caacbdb76f.png)
https://cloud.githubusercontent.com/assets/2068130/11795158/7ab59582-a2b5-11e5-8aaf-d9caacbdb76f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11795166/8a9634ac-a2b5-11e5-9007-4dff4b98b94b.png
Also hrmpf... maybe without the background?

**Comment by quantum8** [comment]
What does it look like without the background @dreamnet?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11803423/0de9b4ec-a2fb-11e5-8fc7-37db10bf7658.png)
https://cloud.githubusercontent.com/assets/2068130/11803423/0de9b4ec-a2fb-11e5-8fc7-37db10bf7658.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11803427/1f889fec-a2fb-11e5-837e-796569abc5d6.png

**Comment by ivanov007** [comment]
yup looks better :+1:

**Comment by quantum8** [comment]
definitely better without the back ground! :+1:
