### ISSUE TITLE
Crazy Fish Hero

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6925]
**App Name:** Crazy Fish Hero
**Bundle ID:** com.labyssgame.WaterFish
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1043839211">1043839211</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/crazy-fish-hero/id1043839211?mt=8&uo=4">https://itunes.apple.com/us/app/crazy-fish-hero/id1043839211?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Cabridens Jerome
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cabridens-jerome/id846030098?uo=4>© Cabridens Jerome</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/92/9c/11/929c1185-bc87-eef0-df15-3cb851fa33eb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11795036/bc800426-a2b4-11e5-90b2-2d916a435da1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11795036/bc800426-a2b4-11e5-90b2-2d916a435da1.png)
https://cloud.githubusercontent.com/assets/2068130/11795036/bc800426-a2b4-11e5-90b2-2d916a435da1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11795044/ca4bd8e6-a2b4-11e5-96d1-a6208ff7fdb7.png
Hrmpf....
