### ISSUE TITLE
Cup O Balls: A Precision Game

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6926]
**App Name:** Cup O Balls: A Precision Game
**Bundle ID:** com.appdore.cup
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=892115610">892115610</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cup-o-balls-a-precision-game/id892115610?mt=8&uo=4">https://itunes.apple.com/us/app/cup-o-balls-a-precision-game/id892115610?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Appdore, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appdore-llc/id634809333?uo=4>© Appdore, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/2a/d3/c0/2ad3c02b-4bc2-0a83-9fdf-0ac4d241a2a5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11794338/1c5cd314-a2b1-11e5-9c40-7f640040d1a5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11794338/1c5cd314-a2b1-11e5-9c40-7f640040d1a5.png)
https://cloud.githubusercontent.com/assets/2068130/11794338/1c5cd314-a2b1-11e5-9c40-7f640040d1a5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11794348/2b656998-a2b1-11e5-84e2-c4e819bbc2d7.png
