### ISSUE TITLE
PlayStation®Messages

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6927]
**App Name:** PlayStation®Messages
**Bundle ID:** com.playstation.eu.mobilemessages
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1053285387">1053285387</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/playstation-messages/id1053285387?mt=8&uo=4">https://itunes.apple.com/us/app/playstation-messages/id1053285387?mt=8&uo=4</a>
**App Version:** 3.10.67
**Seller:** PlayStation Mobile Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/playstation-mobile-inc./id912472174?uo=4>© PlayStation Mobile Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/73/be/d8/73bed840-817b-3ba2-95c1-68118ca3bcea/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11833703/a6ed62cc-a3c5-11e5-8a14-8c38b97912fc.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11833703/a6ed62cc-a3c5-11e5-8a14-8c38b97912fc.png)
https://cloud.githubusercontent.com/assets/10730122/11833703/a6ed62cc-a3c5-11e5-8a14-8c38b97912fc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11833701/a308bf76-a3c5-11e5-89d8-45f6b519ff21.png

**Comment by dreamnet** [comment]
@Trubbel Perfect Icon, you should be able to add the "acceptably-fulfilled" label now. You can do this for your own icons and also for other icons if they are good.

**Comment by Trubbel** [comment]
@dreamnet Thanks, will do! :wink:
