### ISSUE TITLE
AS.com

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6928]
**App Name:** AS.com
**Bundle ID:** com.prisacom.AS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=311797767">311797767</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/as.com/id311797767?mt=8&uo=4">https://itunes.apple.com/us/app/as.com/id311797767?mt=8&uo=4</a>
**App Version:** 4.3.9
**Seller:** Diario AS
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/diario-as/id373978449?uo=4>© Diario AS</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/78/a5/65/78a5657f-ed4c-a8bc-b2ca-7015eece2fe6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11839616/7fc8d8dc-a3ef-11e5-8a47-aabd2a816d43.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11839616/7fc8d8dc-a3ef-11e5-8a47-aabd2a816d43.png)
https://cloud.githubusercontent.com/assets/10730122/11839616/7fc8d8dc-a3ef-11e5-8a47-aabd2a816d43.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11839615/7d8d9b7a-a3ef-11e5-9c15-0c51d862c160.png

**Comment by dreamnet** [comment]
@Trubbel Perfect, gut please don't folget to put the icon preview in the first post.

**Comment by Trubbel** [comment]
@dreamnet Oh I totally forgot about that sorry, wont happen again haha.

**Comment by dreamnet** [comment]
@Trubbel No problem! :+1:
