### ISSUE TITLE
MARCA  -  Diario líder deportivo. Noticias, retransmisiones TV y resultados en directo.

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6929]
**App Name:** MARCA  -  Diario líder deportivo. Noticias, retransmisiones TV y resultados en directo.
**Bundle ID:** com.marca.marcador
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=312407627">312407627</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/marca-diario-lider-deportivo./id312407627?mt=8&uo=4">https://itunes.apple.com/us/app/marca-diario-lider-deportivo./id312407627?mt=8&uo=4</a>
**App Version:** 3.9.0
**Seller:** Marca.com .
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/marca.com/id312407630?uo=4>© MARCA.com</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple2/v4/8a/df/cc/8adfccf4-e3f6-f4e1-43c6-0f8b2d1df3d4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11863684/2eb66e76-a496-11e5-8b14-bb1612578106.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11863684/2eb66e76-a496-11e5-8b14-bb1612578106.png)
https://cloud.githubusercontent.com/assets/2068130/11863684/2eb66e76-a496-11e5-8b14-bb1612578106.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11863691/3cadbd5e-a496-11e5-8a4b-42013a1336ed.png
