### ISSUE TITLE
PokerStars Poker – Juegos de Texas Holdem Gratis - ES

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6930]
**App Name:** PokerStars Poker – Juegos de Texas Holdem Gratis - ES
**Bundle ID:** es.pokerstarsmobile.www
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=533787554">533787554</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/pokerstars-poker-juegos-texas/id533787554?mt=8&uo=4">https://itunes.apple.com/es/app/pokerstars-poker-juegos-texas/id533787554?mt=8&uo=4</a>
**App Version:** 1.53.0
**Seller:** Rational Social Projects Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/rational-social-projects-limited/id762400072?uo=4>© Rational Social Projects Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/64/13/e1/6413e1db-5b30-420d-891f-80d5bd7d52a4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11863503/b1b0bf04-a494-11e5-8ad4-805957f1536e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11863503/b1b0bf04-a494-11e5-8ad4-805957f1536e.png)
https://cloud.githubusercontent.com/assets/2068130/11863503/b1b0bf04-a494-11e5-8ad4-805957f1536e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11863514/c000f60a-a494-11e5-9fb5-fbad32735082.png
