### ISSUE TITLE
Snail Bob 2

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6931]
**App Name:** Snail Bob 2
**Bundle ID:** com.hunter-hamster.snailbob2test
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=959390742">959390742</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snail-bob-2/id959390742?mt=8&uo=4">https://itunes.apple.com/us/app/snail-bob-2/id959390742?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** TINYBUILD LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tinybuild-llc/id945888376?uo=4>© tinyBuild LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/72/06/e1/7206e15e-b82f-fbe0-ecb9-fa3a5e870d71/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11912188/795ab8ae-a632-11e5-96dd-9afa3ba09e37.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11912188/795ab8ae-a632-11e5-96dd-9afa3ba09e37.png)
https://cloud.githubusercontent.com/assets/2068130/11912188/795ab8ae-a632-11e5-96dd-9afa3ba09e37.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11912189/8a1b0ebe-a632-11e5-8690-b9292d406991.png
