### ISSUE TITLE
mGifts - Gift List Manager

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6932]
**App Name:** mGifts - Gift List Manager
**Bundle ID:** com.mSeven.mGifts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=297631123">297631123</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mgifts-gift-list-manager/id297631123?mt=8&uo=4">https://itunes.apple.com/us/app/mgifts-gift-list-manager/id297631123?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** mSeven Software, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mseven-software-llc/id292411905?uo=4>© mSeven Software, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/f0/f3/3b/f0f33bb3-b44e-9b5f-94b7-94be865da17f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11882824/1b4c5a5c-a50f-11e5-8bf1-ee4c481619e2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11882824/1b4c5a5c-a50f-11e5-8bf1-ee4c481619e2.png)
https://cloud.githubusercontent.com/assets/2068130/11882824/1b4c5a5c-a50f-11e5-8bf1-ee4c481619e2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11882831/2b674eec-a50f-11e5-96f5-acab38dfcfe9.png
