### ISSUE TITLE
GoDaddy Mobile

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6933]
**App Name:** GoDaddy Mobile
**Bundle ID:** com.godaddy.DomainBuy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=333201813">333201813</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/godaddy-mobile/id333201813?mt=8&uo=4">https://itunes.apple.com/us/app/godaddy-mobile/id333201813?mt=8&uo=4</a>
**App Version:** 5.96
**Seller:** GoDaddy.com, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/godaddy.com-llc/id333201816?uo=4>© GoDaddy.com, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/8c/cf/79/8ccf797e-fa2d-fd36-3880-cd2adca738f1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11882606/ab632adc-a50d-11e5-97bf-c5776b7f8d3f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11882606/ab632adc-a50d-11e5-97bf-c5776b7f8d3f.png)
https://cloud.githubusercontent.com/assets/2068130/11882606/ab632adc-a50d-11e5-97bf-c5776b7f8d3f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11882618/b93acf20-a50d-11e5-8a6e-0ff552476e19.png
