### ISSUE TITLE
LinkedIn Pulse: Daily News, Powered by Your Professional World

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6934]
**App Name:** LinkedIn Pulse: Daily News, Powered by Your Professional World
**Bundle ID:** com.linkedin.pulse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=999935181">999935181</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/linkedin-pulse-daily-news/id999935181?mt=8&uo=4">https://itunes.apple.com/us/app/linkedin-pulse-daily-news/id999935181?mt=8&uo=4</a>
**App Version:** 1.2.3
**Seller:** LinkedIn Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/linkedin-corporation/id288429043?uo=4>© LinkedIn Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/70/43/54/704354b4-83a3-8508-3a4e-d83dec5c248f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11882280/ce06ec06-a50b-11e5-994b-4e1ea4b6322c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11882280/ce06ec06-a50b-11e5-994b-4e1ea4b6322c.png)
https://cloud.githubusercontent.com/assets/2068130/11882280/ce06ec06-a50b-11e5-994b-4e1ea4b6322c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11882292/dea04c06-a50b-11e5-8168-c73ad935e7af.png
