### ISSUE TITLE
Refine - Customizable Ad Blocker for Safari

### ISSUE THREAD

**Issue by Meyers09** [glasklart/hd#6935]
**App Name:** Refine - Customizable Ad Blocker for Safari
**Bundle ID:** com.lukel.Safari-Blocker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1011678834">1011678834</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/refine-customizable-ad-blocker/id1011678834?mt=8&uo=4">https://itunes.apple.com/us/app/refine-customizable-ad-blocker/id1011678834?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Luke Li
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/luke-li/id593384347?uo=4>© Luke Li</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/21/98/50/2198501c-7e65-ce50-2ed2-7721d776e2cb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11882114/fe5f6028-a50a-11e5-8533-97981b5236bd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11882114/fe5f6028-a50a-11e5-8533-97981b5236bd.png)
https://cloud.githubusercontent.com/assets/2068130/11882114/fe5f6028-a50a-11e5-8533-97981b5236bd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11882130/0e2719c4-a50b-11e5-910a-7767dec0e23a.png
