### ISSUE TITLE
Photo Lab PRO HD: Christmas face morth, photos mosaic maker and cartoon yourself!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6936]
**App Name:** Photo Lab PRO HD: Christmas face morth, photos mosaic maker and cartoon yourself!
**Bundle ID:** com.photoprohd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476312888">476312888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photo-lab-pro-hd-christmas/id476312888?mt=8&uo=4">https://itunes.apple.com/us/app/photo-lab-pro-hd-christmas/id476312888?mt=8&uo=4</a>
**App Version:** 2.4.4
**Seller:** VicMan LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vicman-llc/id441457221?uo=4>© VicMan LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/a2/2a/47/a22a4712-1ee1-5f55-d53d-fdb655cb7fbb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11883507/c6832514-a513-11e5-9c65-85162af7f74b.png)

**Comment by ivanov007** [comment]
refers to #2789

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11883507/c6832514-a513-11e5-9c65-85162af7f74b.png)
https://cloud.githubusercontent.com/assets/2068130/11883507/c6832514-a513-11e5-9c65-85162af7f74b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11883515/d4b0d352-a513-11e5-87ab-ffe312563083.png
