### ISSUE TITLE
Adobe Post – Create stunning graphics

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6937]
**App Name:** Adobe Post – Create stunning graphics
**Bundle ID:** com.adobe.post
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1051937863">1051937863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-post-create-stunning/id1051937863?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-post-create-stunning/id1051937863?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/cf/90/4d/cf904d43-5df9-d7c5-1e26-c9a1ac825c59/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11883300/39e561d6-a512-11e5-9fae-4a2658d704f2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11883300/39e561d6-a512-11e5-9fae-4a2658d704f2.png)
https://cloud.githubusercontent.com/assets/2068130/11883300/39e561d6-a512-11e5-9fae-4a2658d704f2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11883312/49485868-a512-11e5-86e3-861dd566daa4.png
