### ISSUE TITLE
Findo.io

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6939]
**App Name:** Findo.io
**Bundle ID:** com.abbyy.findo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1064201343">1064201343</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/findo.io/id1064201343?mt=8&uo=4">https://itunes.apple.com/us/app/findo.io/id1064201343?mt=8&uo=4</a>
**App Version:** 0.1.0
**Seller:** ABBYY USA Software House Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/abbyy/id347345477?uo=4>© ABBYY</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple2/v4/74/5a/d9/745ad9c0-2658-ff41-e432-a0ffd1128973/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11913441/5a3b2dc8-a664-11e5-9d60-0fa1655f286e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11913441/5a3b2dc8-a664-11e5-9d60-0fa1655f286e.png)
https://cloud.githubusercontent.com/assets/2068130/11913441/5a3b2dc8-a664-11e5-9d60-0fa1655f286e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11913445/6982c408-a664-11e5-9b8e-a26e69c406e0.png
