### ISSUE TITLE
Instapaper

### ISSUE THREAD

**Issue by keefetang** [glasklart/hd#694]
**App Name:** Instapaper
**Bundle ID:** com.marcoarment.instapaperpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288545208">288545208</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instapaper/id288545208?mt=8&uo=4">https://itunes.apple.com/us/app/instapaper/id288545208?mt=8&uo=4</a>
**App Version:** 7.2
**Seller:** Instapaper Holdings, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/instapaper-holdings-inc./id284942716?uo=4>© Instapaper Holdings, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/8e/fa/ea/8efaea3d-5507-e7f1-ea4a-521da1efc6d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18946735/7a982f74-8630-11e6-8c18-0ae82e3e0c23.png)

**Comment by l8er4now** [comment]
Needs to be resized.

**App Name:** Instapaper
**Bundle ID:** com.marcoarment.instapaperpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288545208">288545208</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instapaper/id288545208?mt=8&uo=4">https://itunes.apple.com/us/app/instapaper/id288545208?mt=8&uo=4</a>
**App Version:** 7.2
**Seller:** Instapaper Holdings, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/instapaper-holdings-inc./id284942716?uo=4>© Instapaper Holdings, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/8e/fa/ea/8efaea3d-5507-e7f1-ea4a-521da1efc6d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18946735/7a982f74-8630-11e6-8c18-0ae82e3e0c23.png)
https://cloud.githubusercontent.com/assets/20930745/18946735/7a982f74-8630-11e6-8c18-0ae82e3e0c23.png

https://cloud.githubusercontent.com/assets/20930745/18946747/89974082-8630-11e6-8aa4-59b64eafd6d3.png
