### ISSUE TITLE
Unread: RSS News Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6940]
**App Name:** Unread: RSS News Reader
**Bundle ID:** co.supertop.unread
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911364254">911364254</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/unread-rss-news-reader/id911364254?mt=8&uo=4">https://itunes.apple.com/us/app/unread-rss-news-reader/id911364254?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Supertop Software
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/supertop/id723142773?uo=4>© Supertop</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple2/v4/79/6a/08/796a081c-c484-6690-a91f-044524c4aad2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11918830/71fb8912-a740-11e5-8cdf-2ab20526feb1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11918830/71fb8912-a740-11e5-8cdf-2ab20526feb1.png)
https://cloud.githubusercontent.com/assets/2068130/11918830/71fb8912-a740-11e5-8cdf-2ab20526feb1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11918835/8279f800-a740-11e5-83db-3158df296d3b.png
