### ISSUE TITLE
NewsFlash ~ Breaking News & World Headlines

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6942]
**App Name:** NewsFlash ~ Breaking News & World Headlines
**Bundle ID:** com.sollico.newsflash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=472447733">472447733</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsflash-breaking-news-world/id472447733?mt=8&uo=4">https://itunes.apple.com/us/app/newsflash-breaking-news-world/id472447733?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Sollico Software Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sollico-software/id284938958?uo=4>© Sollico Software</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/a5/d5/60/a5d5601e-8361-2d5a-88b1-94c203fa9f47/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11958976/764fbb4a-a890-11e5-9838-0a97a1e0a6d5.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11958976/764fbb4a-a890-11e5-9838-0a97a1e0a6d5.png)
https://cloud.githubusercontent.com/assets/3090247/11958976/764fbb4a-a890-11e5-9838-0a97a1e0a6d5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11958974/75eb1c62-a890-11e5-9e3f-2c2af1746add.png
