### ISSUE TITLE
Angry Birds POP! - Bubble Shooter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6943]
**App Name:** Angry Birds POP! - Bubble Shooter
**Bundle ID:** com.rovio.stellapop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937718942">937718942</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds-pop!-bubble-shooter/id937718942?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds-pop!-bubble-shooter/id937718942?mt=8&uo=4</a>
**App Version:** 2.5.0
**Seller:** Rovio Entertainment Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rovio-entertainment-ltd/id298910979?uo=4>© Rovio Entertainment Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/68/a9/8b/68a98b97-42d3-195c-749f-a778b07aedbb/source/1024x1024sr.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12041862/a143b190-ae75-11e5-84d9-0a88e500d515.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12041862/a143b190-ae75-11e5-84d9-0a88e500d515.png)
https://cloud.githubusercontent.com/assets/2068130/12041862/a143b190-ae75-11e5-84d9-0a88e500d515.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12041873/af4c01b6-ae75-11e5-89d1-0d9fba5c85cc.png
