### ISSUE TITLE
TouchPal Keyboard - Type Fun With Emoji & Themes & Fonts

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6945]
**App Name:** TouchPal Keyboard - Type Fun With Emoji & Themes & Fonts
**Bundle ID:** com.cootek.smartinput
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=909654683">909654683</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touchpal-keyboard-type-fun/id909654683?mt=8&uo=4">https://itunes.apple.com/us/app/touchpal-keyboard-type-fun/id909654683?mt=8&uo=4</a>
**App Version:** 2.8.0
**Seller:** TouchPal HK Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/touchpal-hk-co.-ltd./id945259429?uo=4>© TouchPal HK Co., Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/11972226/a52ea93a-a949-11e5-8ad5-0a97db05e731.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11972217/7f5a76c6-a949-11e5-9c92-bfa6046188d5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11972217/7f5a76c6-a949-11e5-9c92-bfa6046188d5.png)
https://cloud.githubusercontent.com/assets/2068130/11972217/7f5a76c6-a949-11e5-9c92-bfa6046188d5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11972221/8dd255fc-a949-11e5-90cd-03b6dc909a92.png

**Comment by ivanov007** [comment]
this one is not theming
