### ISSUE TITLE
NYT Now—Your Guide to the News

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6946]
**App Name:** NYT Now—Your Guide to the News
**Bundle ID:** com.nytimes.NYTNow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=798993249">798993249</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nyt-now-your-guide-to-the-news/id798993249?mt=8&uo=4">https://itunes.apple.com/us/app/nyt-now-your-guide-to-the-news/id798993249?mt=8&uo=4</a>
**App Version:** 2.0.4
**Seller:** The New York Times Company (iDP)
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/the-new-york-times-company/id284862086?uo=4>© The New York Times Company</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/27/3f/c2/273fc2b9-1a0f-ef71-f238-e19704fb1bba/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11990857/9f0bb8b6-aa13-11e5-8c9f-2b0ba263c2f3.png)

**Comment by illinikev** [comment]
![nytimesnow](https://cloud.githubusercontent.com/assets/16004373/11983936/1aad6e70-a97d-11e5-90a7-bd11c48cc0fa.png)

Source:
https://cloud.githubusercontent.com/assets/16004373/11983958/4212654c-a97d-11e5-8c65-ba11e09ba860.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11990857/9f0bb8b6-aa13-11e5-8c9f-2b0ba263c2f3.png)
https://cloud.githubusercontent.com/assets/2068130/11990857/9f0bb8b6-aa13-11e5-8c9f-2b0ba263c2f3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11990860/ad81c25a-aa13-11e5-9ae1-c082e35a0a39.png

**Comment by ivanov007** [comment]
this isn't theming for me, what about you @illinikev?

**Comment by illinikev** [comment]
Stopped a long time ago.  People not jailbreaking. That's why I'm now a minimalist with Glaskart.

Kevin
