### ISSUE TITLE
Adobe Photoshop Lightroom for iPhone - Capture, Edit, Organize & Share Pictures

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6947]
**App Name:** Adobe Photoshop Lightroom for iPhone - Capture, Edit, Organize & Share Pictures
**Bundle ID:** com.adobe.lrmobilephone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=878783582">878783582</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-photoshop-lightroom/id878783582?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-photoshop-lightroom/id878783582?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/47/45/88/4745884e-29a7-aaf3-21fe-2ba1d229c7b7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11990902/0aa73154-aa14-11e5-8f92-9817b7ec3fd6.png)

**Comment by illinikev** [comment]
![lightroom](https://cloud.githubusercontent.com/assets/16004373/11984008/81f997e8-a97d-11e5-8dcc-383ed6dd6ad8.png)

Source:
https://cloud.githubusercontent.com/assets/16004373/11984012/8a9dd42c-a97d-11e5-9bc7-b78f4bd56bef.png

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11990902/0aa73154-aa14-11e5-8f92-9817b7ec3fd6.png)
https://cloud.githubusercontent.com/assets/2068130/11990902/0aa73154-aa14-11e5-8f92-9817b7ec3fd6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11990907/1b03caa8-aa14-11e5-94c5-0afe8f8652bf.png
