### ISSUE TITLE
Chicago Symphony Orchestra

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6948]
**App Name:** Chicago Symphony Orchestra
**Bundle ID:** com.cloudtix.cso
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417114616">417114616</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chicago-symphony-orchestra/id417114616?mt=8&uo=4">https://itunes.apple.com/us/app/chicago-symphony-orchestra/id417114616?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** CloudTix
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cloudtix/id384256415?uo=4>© CloudTix</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/6c/9c/17/6c9c174c-add6-13a5-4375-ce801786a752/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11990973/03f54aca-aa15-11e5-8ae5-4de09093c1b6.png)

**Comment by illinikev** [comment]
![cso](https://cloud.githubusercontent.com/assets/16004373/11984033/b09ea6d8-a97d-11e5-8826-ee2ac0d38768.png)

Source:
https://cloud.githubusercontent.com/assets/16004373/11984041/c07bd10c-a97d-11e5-8532-67c4c7c0f342.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11990973/03f54aca-aa15-11e5-8ae5-4de09093c1b6.png)
https://cloud.githubusercontent.com/assets/2068130/11990973/03f54aca-aa15-11e5-8ae5-4de09093c1b6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11990978/1471a2a4-aa15-11e5-851c-5f557b88d69f.png
