### ISSUE TITLE
 Collector for ArcGIS

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6949]
**App Name:** Collector for ArcGIS
**Bundle ID:** com.esri.Collector
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589674237">589674237</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/collector-for-arcgis/id589674237?mt=8&uo=4">https://itunes.apple.com/us/app/collector-for-arcgis/id589674237?mt=8&uo=4</a>
**App Version:** 10.3.6
**Seller:** ESRI
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/esri/id379687933?uo=4>© ESRI</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/88/72/f9/8872f960-529e-3241-0708-96302244a6e2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11991026/a1aa9838-aa15-11e5-8382-425e82f65b00.png)

**Comment by illinikev** [comment]
![arccollector](https://cloud.githubusercontent.com/assets/16004373/11984056/d3cce8ae-a97d-11e5-9912-714b37354075.png)

Source:
https://cloud.githubusercontent.com/assets/16004373/11984066/dc6690be-a97d-11e5-9049-0392cd3c0b0d.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11991026/a1aa9838-aa15-11e5-8382-425e82f65b00.png)
https://cloud.githubusercontent.com/assets/2068130/11991026/a1aa9838-aa15-11e5-8382-425e82f65b00.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11991035/b3604abe-aa15-11e5-8081-37c31b8a48e9.png
