### ISSUE TITLE
Digg

### ISSUE THREAD

**Issue by keefetang** [glasklart/hd#695]
**App Name:** Digg
**Bundle ID:** com.digg.Digg
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=362872995">362872995</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/digg/id362872995?mt=8&uo=4">https://itunes.apple.com/us/app/digg/id362872995?mt=8&uo=4</a>
**App Version:** 6.3.0
**Seller:** Digg Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/digg/id331324235?uo=4>© Digg</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/15/5d/1c/155d1cb0-e9c7-00fd-dd3a-899bf9d22030/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19527622/faff5964-9628-11e6-80d0-6e3ff26b468a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19527622/faff5964-9628-11e6-80d0-6e3ff26b468a.png)
https://cloud.githubusercontent.com/assets/20930745/19527622/faff5964-9628-11e6-80d0-6e3ff26b468a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19527648/0fdbb2c4-9629-11e6-8241-3680d575ae4d.png
