### ISSUE TITLE
Evite: Online & Text Invites

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6950]
**App Name:** Evite: Online & Text Invites
**Bundle ID:** com.evite.iphone.core
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431685286">431685286</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/evite-online-text-invites/id431685286?uo=4">https://apps.apple.com/us/app/evite-online-text-invites/id431685286?uo=4</a>
**App Version:** 8.1.0
**Seller:** Evite, Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/evite-inc/id431685290?uo=4">© Evite, Inc</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/c7/f1/b0/c7f1b073-23ec-60ed-0b01-917c2f62c515/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388135-74bbdf80-9aad-11e9-8667-054bbd853a29.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11971846/d6a142bc-a943-11e5-8e21-a7c4a4251806.png)
https://cloud.githubusercontent.com/assets/2068130/11971846/d6a142bc-a943-11e5-8e21-a7c4a4251806.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11971853/eaec8254-a943-11e5-845f-de91036aebff.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388135-74bbdf80-9aad-11e9-8667-054bbd853a29.png)
https://user-images.githubusercontent.com/20930745/60388135-74bbdf80-9aad-11e9-8667-054bbd853a29.png

Source:
https://user-images.githubusercontent.com/20930745/60388138-7b4a5700-9aad-11e9-8e70-ef2f138ecbe1.png
