### ISSUE TITLE
talkSPORT

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6951]
**App Name:** talkSPORT
**Bundle ID:** uk.co.utvgb.talksport
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=373079007">373079007</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/talksport/id373079007?mt=8&uo=4">https://itunes.apple.com/us/app/talksport/id373079007?mt=8&uo=4</a>
**App Version:** 5.5.2
**Seller:** UTV Media plc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/utv-media-plc/id373079010?uo=4>© UTV Media plc</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/05/a6/7f/05a67fdd-d8ea-044d-9d43-502bd481c2c2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11972048/d6077378-a946-11e5-9d79-e3cbda7f71e2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11972048/d6077378-a946-11e5-9d79-e3cbda7f71e2.png)
https://cloud.githubusercontent.com/assets/2068130/11972048/d6077378-a946-11e5-9d79-e3cbda7f71e2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11972052/e441a97c-a946-11e5-8e3d-e0c069371b72.png
