### ISSUE TITLE
RideScout - Real-time transit and transportation options

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6952]
**App Name:** RideScout - Real-time transit and transportation options
**Bundle ID:** com.ridescoutapp.ridescout
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=574125726">574125726</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ridescout-real-time-transit/id574125726?mt=8&uo=4">https://itunes.apple.com/us/app/ridescout-real-time-transit/id574125726?mt=8&uo=4</a>
**App Version:** 1.8.23
**Seller:** GoingMyWay, LLC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ridescout-llc/id574125749?uo=4>© RideScout LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/95/a2/5a/95a25a1d-0605-958c-44de-4bd144c17dcf/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11991124/bc62b510-aa16-11e5-82d8-1d910ec33dd6.png)

**Comment by illinikev** [comment]
![ridescout](https://cloud.githubusercontent.com/assets/16004373/11984074/ee2a71c6-a97d-11e5-9f76-01d01c47e5db.png)

Source:
https://cloud.githubusercontent.com/assets/16004373/11984077/f4dd3a9e-a97d-11e5-993d-ee54bd41ee9a.png

**Comment by ivanov007** [comment]
@illinikev you need to add the `![](http://preview.dreamnet.at/?image=` code to your contribution icons (I'm fixing it on this issue), as for the icon sources they need to be the full 1024x1024 pixels

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11991124/bc62b510-aa16-11e5-82d8-1d910ec33dd6.png)
https://cloud.githubusercontent.com/assets/2068130/11991124/bc62b510-aa16-11e5-82d8-1d910ec33dd6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11991128/cc0895ca-aa16-11e5-94ea-b225ca64713a.png
