### ISSUE TITLE
VICE News

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#6955]
**App Name:** VICE News
**Bundle ID:** com.vice.news.VICE-News
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=918321010">918321010</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vice-news/id918321010?mt=8&uo=4">https://itunes.apple.com/us/app/vice-news/id918321010?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** VICE Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vice-media-inc./id473560951?uo=4>© Vice Media, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/ff/a6/33/ffa633f5-8f79-765c-d34d-6e12a494744c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11991158/2750cd8a-aa17-11e5-9116-cdc52a1d30b1.png)

**Comment by illinikev** [comment]
![vicenews](https://cloud.githubusercontent.com/assets/16004373/11984083/04aa1906-a97e-11e5-9d4e-8b7252ff6abe.png)

Source:
https://cloud.githubusercontent.com/assets/16004373/11984085/0be7ffee-a97e-11e5-89cf-68b322ec67f1.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11991158/2750cd8a-aa17-11e5-9116-cdc52a1d30b1.png)
https://cloud.githubusercontent.com/assets/2068130/11991158/2750cd8a-aa17-11e5-9116-cdc52a1d30b1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11991164/37cdb128-aa17-11e5-82cc-63434b038b19.png
