### ISSUE TITLE
MusicPeek - Music Player Widget for Notification Center

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6956]
**App Name:** MusicPeek - Music Player Widget for Notification Center
**Bundle ID:** com.Last.Minute.Project.Next
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=970113282">970113282</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/musicpeek-music-player-widget/id970113282?mt=8&uo=4">https://itunes.apple.com/us/app/musicpeek-music-player-widget/id970113282?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Satrio Budiarto
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/satrio-budiarto/id923465922?uo=4>© Satrio Budiarto</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/fc/81/99/fc81990c-1223-564b-d962-b9f5d6cb69fc/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12008521/ddad5252-ac05-11e5-9e57-50d5b9c581f9.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12008521/ddad5252-ac05-11e5-9e57-50d5b9c581f9.png)
https://cloud.githubusercontent.com/assets/3090247/12008521/ddad5252-ac05-11e5-9e57-50d5b9c581f9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/12008523/f456d118-ac05-11e5-890b-629bb9a66a7a.png
