### ISSUE TITLE
DropZap

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6958]
**App Name:** DropZap
**Bundle ID:** com.dropzap.DropZap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338490375">338490375</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dropzap/id338490375?mt=8&uo=4">https://itunes.apple.com/us/app/dropzap/id338490375?mt=8&uo=4</a>
**App Version:** 3.6.2
**Seller:** Amir Michail
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/amir-michail/id312424715?uo=4>© Amir Michail</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/36/a9/9c/36a99c10-7666-ddf8-263c-c755c202965a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12077923/9c0dadf0-b1fb-11e5-926f-13af12d7fe39.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12077923/9c0dadf0-b1fb-11e5-926f-13af12d7fe39.png)
https://cloud.githubusercontent.com/assets/2068130/12077923/9c0dadf0-b1fb-11e5-926f-13af12d7fe39.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12077925/aaebe9d6-b1fb-11e5-826e-c91e8dd43832.png
