### ISSUE TITLE
Fair Enough

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6961]
**App Name:** Fair Enough
**Bundle ID:** com.leonspok.Fair-Enough
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032535685">1032535685</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fair-enough/id1032535685?mt=8&uo=4">https://itunes.apple.com/us/app/fair-enough/id1032535685?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Igor Savelev
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/igor-savelev/id1032535174?uo=4>© Igor Savelev</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/96/86/9b/96869b29-4274-cc5b-4965-9fcc89071b21/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11984643/8f294058-a982-11e5-8278-d868d2c4324f.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11984643/8f294058-a982-11e5-8278-d868d2c4324f.png)
https://cloud.githubusercontent.com/assets/3090247/11984643/8f294058-a982-11e5-8278-d868d2c4324f.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11984644/8f29e198-a982-11e5-9490-8c94421d42c9.png)
https://cloud.githubusercontent.com/assets/3090247/11984644/8f29e198-a982-11e5-9490-8c94421d42c9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/11984642/8f290b1a-a982-11e5-813b-9eade09feb2a.png
https://cloud.githubusercontent.com/assets/3090247/11984641/8f28efc2-a982-11e5-9536-4e0b4b1e3dc3.png

**Comment by dreamnet** [comment]
@ivanov007 Taking the one with original size. :+1:
