### ISSUE TITLE
File Transfer – Exchange files between multiple devices seamlessly

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6962]
**App Name:** File Transfer – Exchange files between multiple devices seamlessly
**Bundle ID:** com.delitestudio.filetransfer.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=584806191">584806191</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/file-transfer-exchange-files/id584806191?mt=8&uo=4">https://itunes.apple.com/us/app/file-transfer-exchange-files/id584806191?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Delite Studio S.r.l.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/delite-studio-s.r.l./id473939554?uo=4>© Delite Studio S.r.l.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/21/37/17/21371711-86cd-b4f4-5d76-17fae3f62a25/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11984527/8ac81dc8-a981-11e5-8658-dc348fe4dc81.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11984528/8ac8c2fa-a981-11e5-8a65-d9deb1c7bbc9.png)
https://cloud.githubusercontent.com/assets/3090247/11984528/8ac8c2fa-a981-11e5-8a65-d9deb1c7bbc9.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/11984527/8ac81dc8-a981-11e5-8658-dc348fe4dc81.png)
https://cloud.githubusercontent.com/assets/3090247/11984527/8ac81dc8-a981-11e5-8658-dc348fe4dc81.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/11984525/8ac70596-a981-11e5-9676-432b5f889ed8.png)
https://cloud.githubusercontent.com/assets/3090247/11984526/8ac77eb8-a981-11e5-9894-1a2785af1368.png)

**Comment by dreamnet** [comment]
@ivanov007 Again, the one wit original size. :+1:
