### ISSUE TITLE
Fraction Calculator Plus Free

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6963]
**App Name:** Fraction Calculator Plus Free
**Bundle ID:** com.digitalchemy.calculator.fractionfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=580778301">580778301</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fraction-calculator-plus-free/id580778301?mt=8&uo=4">https://itunes.apple.com/us/app/fraction-calculator-plus-free/id580778301?mt=8&uo=4</a>
**App Version:** 3.8
**Seller:** DigitAlchemy LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/digitalchemy-llc/id376971628?uo=4>© DigitAlchemy LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/e8/79/d5/e879d544-9281-18f9-5ccd-d8dcdde5d9f5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12029779/82a7aec6-adf3-11e5-8240-3e65f6306454.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12029779/82a7aec6-adf3-11e5-8240-3e65f6306454.png)
https://cloud.githubusercontent.com/assets/2068130/12029779/82a7aec6-adf3-11e5-8240-3e65f6306454.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12029782/9181a032-adf3-11e5-9414-31b09565678c.png
