### ISSUE TITLE
Free Graphing Calculator

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6964]
**App Name:** Free Graphing Calculator
**Bundle ID:** com.jockusch.calculatorfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378009553">378009553</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/free-graphing-calculator/id378009553?mt=8&uo=4">https://itunes.apple.com/us/app/free-graphing-calculator/id378009553?mt=8&uo=4</a>
**App Version:** 7.7
**Seller:** William Jockusch
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/william-jockusch/id342126227?uo=4>© William Jockusch</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/e6/af/27/e6af2711-0618-6bb7-0977-3edc646cebda/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11992219/45187c9e-aa23-11e5-80c6-838c1fcd7d7e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11992219/45187c9e-aa23-11e5-80c6-838c1fcd7d7e.png)
https://cloud.githubusercontent.com/assets/2068130/11992219/45187c9e-aa23-11e5-80c6-838c1fcd7d7e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11992221/51d2c5a2-aa23-11e5-9119-741d1b0c645a.png
