### ISSUE TITLE
Galaxy Legend

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6965]
**App Name:** Galaxy Legend
**Bundle ID:** com.tap4fun.galaxyempire2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=599877646">599877646</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/galaxy-legend/id599877646?mt=8&uo=4">https://itunes.apple.com/us/app/galaxy-legend/id599877646?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** Kevin Yang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tap4fun/id446315550?uo=4>© Tap4Fun</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple2/v4/c1/53/21/c1532102-24fc-43f5-b125-c19ccc557047/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18031164/4546db92-6cd4-11e6-84ea-b08694007937.png)

**Comment by Trubbel** [comment]
What about the games logo? Didn't turn out that well.. don't know what else to do with this one.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18031164/4546db92-6cd4-11e6-84ea-b08694007937.png)
https://cloud.githubusercontent.com/assets/10730122/18031164/4546db92-6cd4-11e6-84ea-b08694007937.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18031165/45614dba-6cd4-11e6-9bbb-8680ae4be7ae.png

**Comment by dreamnet** [comment]
@Trubbel We take it until someone makes a better one.
