### ISSUE TITLE
GREG - A Mathematical Puzzle Game To Train Your Brain Skills

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6966]
**App Name:** GREG - A Mathematical Puzzle Game To Train Your Brain Skills
**Bundle ID:** com.marcotorretta.Greg
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=895726517">895726517</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/greg-mathematical-puzzle-game/id895726517?mt=8&uo=4">https://itunes.apple.com/us/app/greg-mathematical-puzzle-game/id895726517?mt=8&uo=4</a>
**App Version:** 3.1.3
**Seller:** Marco Torretta
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/marco-torretta/id560750786?uo=4>© Marco Torretta</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/a0/2e/e8/a02ee849-a3bf-dc80-85e5-9a49a5605853/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11992101/1f69639c-aa22-11e5-95c6-bd4c8d0c32bd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11992101/1f69639c-aa22-11e5-95c6-bd4c8d0c32bd.png)
https://cloud.githubusercontent.com/assets/2068130/11992101/1f69639c-aa22-11e5-95c6-bd4c8d0c32bd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11992105/2c94b0bc-aa22-11e5-9266-7ef45e4cca71.png
