### ISSUE TITLE
Git Up - What's Hot on GitHub

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6968]
**App Name:** Git Up - What's Hot on GitHub
**Bundle ID:** de.dennisreimann.GitUp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=727039913">727039913</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/git-up-whats-hot-on-github/id727039913?mt=8&uo=4">https://itunes.apple.com/us/app/git-up-whats-hot-on-github/id727039913?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Dennis Reimann
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dennis-reimann/id298851383?uo=4>© Dennis Reimann</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/ea/42/1c/ea421c63-7b33-3c98-6d13-80bf88f501c9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11992060/85907558-aa21-11e5-839b-1961b28747e4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11992060/85907558-aa21-11e5-839b-1961b28747e4.png)
https://cloud.githubusercontent.com/assets/2068130/11992060/85907558-aa21-11e5-839b-1961b28747e4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11992063/93a86aec-aa21-11e5-9b45-6dadda2616a3.png
