### ISSUE TITLE
Glow Lamp

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6969]
**App Name:** Glow Lamp
**Bundle ID:** com.kaufmania.glowLampX
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967821302">967821302</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glow-lamp/id967821302?mt=8&uo=4">https://itunes.apple.com/us/app/glow-lamp/id967821302?mt=8&uo=4</a>
**App Version:** 2.05
**Seller:** Michael Kaufman
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/michael-kaufman/id967821301?uo=4>© Michael Kaufman</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/38/31/2c/38312ca6-7487-a691-6f91-0cc64dbf9acb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12021780/db005bd2-ad89-11e5-91c3-70b0fe8e6e00.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12021780/db005bd2-ad89-11e5-91c3-70b0fe8e6e00.png)
https://cloud.githubusercontent.com/assets/2068130/12021780/db005bd2-ad89-11e5-91c3-70b0fe8e6e00.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12021789/e8fe3722-ad89-11e5-954d-2c732d12084f.png
