### ISSUE TITLE
Guía SKY

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6970]
**App Name:** Guía SKY
**Bundle ID:** mx.com.sky.guiaSKY
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=455969918">455969918</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/guia-sky/id455969918?mt=8&uo=4">https://itunes.apple.com/us/app/guia-sky/id455969918?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** CORPORACION NOVAVISION S. DE R.L  DE C.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sky-mexico/id455969921?uo=4>© SKY México</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/4c/92/b6/4c92b69e-cbb1-9a41-7c58-e35d1bfa130e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11992025/1815ab06-aa21-11e5-8c65-f31827910ad3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11992025/1815ab06-aa21-11e5-8c65-f31827910ad3.png)
https://cloud.githubusercontent.com/assets/2068130/11992025/1815ab06-aa21-11e5-8c65-f31827910ad3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11992028/269e4890-aa21-11e5-94e7-78ba8f01bdfa.png
