### ISSUE TITLE
PDF Max 5 Pro - Read, Annotate, Sign, Fill out Forms & Edit PDFs

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6973]
**App Name:** PDF Max 5 Pro - Read, Annotate, Sign, Fill out Forms & Edit PDFs
**Bundle ID:** com.mbr.camelliapro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=552664144">552664144</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pdf-max-5-pro-read-annotate/id552664144?mt=8&uo=4">https://itunes.apple.com/us/app/pdf-max-5-pro-read-annotate/id552664144?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** Mobeera Co., Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobeera/id540572076?uo=4>© Mobeera</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/bc/44/04/bc4404d2-9366-790d-5e43-330dc302a4d5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12010641/6f3d12c0-ac74-11e5-9610-2c7d29a787d5.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12010641/6f3d12c0-ac74-11e5-9610-2c7d29a787d5.png)
https://cloud.githubusercontent.com/assets/3090247/12010641/6f3d12c0-ac74-11e5-9610-2c7d29a787d5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/12010640/6f3a6d72-ac74-11e5-88ff-31d3f659e96a.png
