### ISSUE TITLE
LensFX Epic Photo Effects

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6978]
**App Name:** LensFX Epic Photo Effects
**Bundle ID:** com.BrainFeverMedia.LensFX
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=698448636">698448636</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lensfx-epic-photo-effects/id698448636?mt=8&uo=4">https://itunes.apple.com/us/app/lensfx-epic-photo-effects/id698448636?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** James Grote
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brainfevermedia/id338517204?uo=4>© BrainFeverMedia</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/25/d3/ae/25d3ae72-d00c-b655-c6dc-afbfc386f49c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12022562/322ddd92-ad91-11e5-83b0-707e416c1082.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12022562/322ddd92-ad91-11e5-83b0-707e416c1082.png)
https://cloud.githubusercontent.com/assets/2068130/12022562/322ddd92-ad91-11e5-83b0-707e416c1082.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12022568/41150a38-ad91-11e5-9f08-4e967645d24b.png
