### ISSUE TITLE
Songkick Concerts

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6979]
**App Name:** Songkick Concerts
**Bundle ID:** com.songkick.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438690886">438690886</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/songkick-concerts/id438690886?mt=8&uo=4">https://itunes.apple.com/us/app/songkick-concerts/id438690886?mt=8&uo=4</a>
**App Version:** 5.4
**Seller:** Songkick.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/songkick/id438690889?uo=4>© Songkick</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/fe/3a/89/fe3a89d8-9727-ab83-86e8-86d38e274c05/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12021852/7ca45bc8-ad8a-11e5-95df-79b973faed2f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12021852/7ca45bc8-ad8a-11e5-95df-79b973faed2f.png)
https://cloud.githubusercontent.com/assets/2068130/12021852/7ca45bc8-ad8a-11e5-95df-79b973faed2f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12021857/8ac6b214-ad8a-11e5-8c1d-807c1f588d90.png
