### ISSUE TITLE
I LIKE RADIO

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#6980]
**App Name:** I LIKE RADIO
**Bundle ID:** se.mtgradio.ILIKERADIO
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=891286267">891286267</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/i-like-radio/id891286267?mt=8&uo=4">https://itunes.apple.com/us/app/i-like-radio/id891286267?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** MTG AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mtg-ab/id430848835?uo=4>© MTG AB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/39/42/5e/39425e85-3c10-283e-0408-dc436e466889/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12021927/3d91c366-ad8b-11e5-927b-f6489a7281a0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12021927/3d91c366-ad8b-11e5-927b-f6489a7281a0.png)
https://cloud.githubusercontent.com/assets/2068130/12021927/3d91c366-ad8b-11e5-927b-f6489a7281a0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12021933/4be80984-ad8b-11e5-8d86-e1de95e1f586.png
