### ISSUE TITLE
Timpik - Play your favorite sports

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6981]
**App Name:** Timpik - Play your favorite sports
**Bundle ID:** com.timpik.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=433422542">433422542</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/timpik-play-your-favorite/id433422542?mt=8&uo=4">https://itunes.apple.com/us/app/timpik-play-your-favorite/id433422542?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Francisco Cuenca Montilla
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fcapp/id296439931?uo=4>© FCApp</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/32/45/8f/32458fb6-0ce8-aaac-fb7f-90aca212590b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12036633/1e7365c6-ae48-11e5-9edd-4174dfb0625f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12036633/1e7365c6-ae48-11e5-9edd-4174dfb0625f.png)
https://cloud.githubusercontent.com/assets/2068130/12036633/1e7365c6-ae48-11e5-9edd-4174dfb0625f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12036641/2f0495f4-ae48-11e5-86b6-2325b74e8141.png
