### ISSUE TITLE
Mi Livebox

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6982]
**App Name:** Mi Livebox
**Bundle ID:** com.orange.sp.milivebox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447058694">447058694</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/mi-livebox/id447058694?mt=8&uo=4">https://itunes.apple.com/es/app/mi-livebox/id447058694?mt=8&uo=4</a>
**App Version:** 3.0.9
**Seller:** France Telecom Espana S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/orange-spain/id370553435?uo=4>© Orange Spain</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/f9/fc/5e/f9fc5e8c-7705-51b7-4980-be7812967210/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12036719/e789fb14-ae48-11e5-8336-872d80bb0535.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12036719/e789fb14-ae48-11e5-8336-872d80bb0535.png)
https://cloud.githubusercontent.com/assets/2068130/12036719/e789fb14-ae48-11e5-8336-872d80bb0535.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12036722/f444fcbe-ae48-11e5-8696-0c6a6fe222d9.png
