### ISSUE TITLE
La Liga - Spanish Football League Official

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6983]
**App Name:** La Liga - Spanish Football League Official
**Bundle ID:** com.generamobile.lfpiPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=545609647">545609647</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/la-liga-spanish-football-league/id545609647?mt=8&uo=4">https://itunes.apple.com/us/app/la-liga-spanish-football-league/id545609647?mt=8&uo=4</a>
**App Version:** 3.5.1
**Seller:** La Liga Nacional de Futbol Profesional
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/liga-de-futbol-profesional/id512997931?uo=4>© Liga de Futbol Profesional</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/07/b6/ab/07b6abbc-3ecf-c2ba-b6ae-c48a28e2bd20/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12036768/6196b352-ae49-11e5-8ea2-cbef3ccb2d8f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12036768/6196b352-ae49-11e5-8ea2-cbef3ccb2d8f.png)
https://cloud.githubusercontent.com/assets/2068130/12036768/6196b352-ae49-11e5-8ea2-cbef3ccb2d8f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12036777/6ef3497a-ae49-11e5-93d2-a1fb9303d944.png
