### ISSUE TITLE
I’m Expecting Pregnancy App and Baby Guide

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6984]
**App Name:** I’m Expecting Pregnancy App and Baby Guide
**Bundle ID:** org.medhelp.ImExpecting
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=383565674">383565674</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/im-expecting-pregnancy-app/id383565674?mt=8&uo=4">https://itunes.apple.com/us/app/im-expecting-pregnancy-app/id383565674?mt=8&uo=4</a>
**App Version:** 2.5.0
**Seller:** Medhelp
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/medhelp/id335875914?uo=4>© MedHelp</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/1b/9a/e9/1b9ae97e-3de3-cae8-0585-05416170f18b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12048490/058cf75e-aedc-11e5-9f72-5376910142aa.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12048490/058cf75e-aedc-11e5-9f72-5376910142aa.png)
https://cloud.githubusercontent.com/assets/2068130/12048490/058cf75e-aedc-11e5-9f72-5376910142aa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12048497/1356b5d2-aedc-11e5-9ac6-90451b61db08.png
