### ISSUE TITLE
LocalCast for Chromecast streams local & webvideos

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6985]
**App Name:** LocalCast for Chromecast streams local & webvideos
**Bundle ID:** de.stefanpledl.localcast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=969804264">969804264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/localcast-for-chromecast-streams-local-webvideos/id969804264?mt=8&uo=4">https://itunes.apple.com/us/app/localcast-for-chromecast-streams-local-webvideos/id969804264?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Stefan Pledl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/stefan-pledl/id969804263?uo=4">© Stefan Pledl</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/de/ab/3e/deab3e7d-72dd-2861-012f-b85e551ad4c1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25754286/f1ed5650-31be-11e7-9759-87a94ce9dc37.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12048849/8e8a436e-aee0-11e5-91b5-1c856aa2114a.png)
https://cloud.githubusercontent.com/assets/2068130/12048849/8e8a436e-aee0-11e5-91b5-1c856aa2114a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12048854/9f08cb8e-aee0-11e5-9ce8-d9608ab41c4e.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** LocalCast for Chromecast streams local & webvideos
**Bundle ID:** de.stefanpledl.localcast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=969804264">969804264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/localcast-for-chromecast-streams-local-webvideos/id969804264?mt=8&uo=4">https://itunes.apple.com/us/app/localcast-for-chromecast-streams-local-webvideos/id969804264?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Stefan Pledl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/stefan-pledl/id969804263?uo=4">© Stefan Pledl</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/de/ab/3e/deab3e7d-72dd-2861-012f-b85e551ad4c1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25746653/c643245e-31a4-11e7-866a-d76503556436.png)
https://cloud.githubusercontent.com/assets/20930745/25746653/c643245e-31a4-11e7-866a-d76503556436.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25746676/d9525664-31a4-11e7-894d-2470a2d2adc3.png
