### ISSUE TITLE
Lowe's Creative Ideas Magazine

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6986]
**App Name:** Lowe's Creative Ideas Magazine
**Bundle ID:** com.pixelmags.reader.managed.lowes-creative-idea
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487473473">487473473</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lowes-creative-ideas-magazine/id487473473?mt=8&uo=4">https://itunes.apple.com/us/app/lowes-creative-ideas-magazine/id487473473?mt=8&uo=4</a>
**App Version:** 4.4.10
**Seller:** Lowe's Companie's, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lowes-companies-inc./id457954784?uo=4>© Lowe's Companies, Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/37/6b/f0/376bf00c-61cd-97a3-9206-550b3db3925c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12049000/4992f36c-aee2-11e5-853f-e37f5561e3c2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12049000/4992f36c-aee2-11e5-853f-e37f5561e3c2.png)
https://cloud.githubusercontent.com/assets/2068130/12049000/4992f36c-aee2-11e5-853f-e37f5561e3c2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12049005/587e79f0-aee2-11e5-9e99-7cb6a7b40209.png
