### ISSUE TITLE
Mastermind Pro - Code Breaker (Premium)

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#6987]
**App Name:** Mastermind Pro - Code Breaker (Premium)
**Bundle ID:** com.nBorg.Mastermind-Pro-Premium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=998543383">998543383</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mastermind-pro-code-breaker/id998543383?mt=8&uo=4">https://itunes.apple.com/us/app/mastermind-pro-code-breaker/id998543383?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Nestor Borgo
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nestor-borgo/id478653152?uo=4>© Nestor Borgo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/4f/8d/26/4f8d269d-219b-9739-2425-b22fcd455ac9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12048428/616aceb2-aedb-11e5-8789-d31631fef95c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12048428/616aceb2-aedb-11e5-8789-d31631fef95c.png)
https://cloud.githubusercontent.com/assets/2068130/12048428/616aceb2-aedb-11e5-8789-d31631fef95c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12048435/6fc46752-aedb-11e5-9d68-0ada2b41f5fb.png
