### ISSUE TITLE
Invoice2go Invoice & Estimate

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#6995]
**App Name:** Invoice2go Invoice & Estimate
**Bundle ID:** com.invoice2go.plus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540236748">540236748</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/invoice2go-invoice-estimate/id540236748?uo=4">https://apps.apple.com/us/app/invoice2go-invoice-estimate/id540236748?uo=4</a>
**App Version:** 10.85.0
**Seller:** Invoice2go.com
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/invoice2go-com/id322773085?uo=4">© Invoice2go.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/95/a7/28/95a7281c-1268-9ffd-ff68-584a05895d36/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62397678-cb1db180-b576-11e9-9cd4-9ed328491f52.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12050170/4aafdc92-aef1-11e5-8720-8a561e931373.png)
https://cloud.githubusercontent.com/assets/2068130/12050170/4aafdc92-aef1-11e5-8720-8a561e931373.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12050176/59074546-aef1-11e5-9c1b-6571acc0f149.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62397678-cb1db180-b576-11e9-9cd4-9ed328491f52.png)
https://user-images.githubusercontent.com/2068130/62397678-cb1db180-b576-11e9-9cd4-9ed328491f52.png
--- ---
Source:
![com invoice2go plus_orig_big-01](https://user-images.githubusercontent.com/2068130/62397690-db359100-b576-11e9-8a25-6cc0530378a0.png)
