### ISSUE TITLE
NewsPlus: Stories for you

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#6998]
**App Name:** NewsPlus: Stories for you
**Bundle ID:** com.veooz.Veooz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942885631">942885631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsplus-stories-for-you/id942885631?mt=8&uo=4">https://itunes.apple.com/us/app/newsplus-stories-for-you/id942885631?mt=8&uo=4</a>
**App Version:** 7.1
**Seller:** Veooz Labs Private Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/veooz-labs-private-limited/id939530454?uo=4">© Veooz Labs Private Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/6e/7e/b3/6e7eb384-0e67-4118-fcae-19a2040caba4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/37921412-0f99d532-312a-11e8-994a-2a72c9d2155a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12070056/9b4d5122-b05c-11e5-9aa8-6f463ca82579.png)
https://cloud.githubusercontent.com/assets/2068130/12070056/9b4d5122-b05c-11e5-9aa8-6f463ca82579.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12070057/aca21c28-b05c-11e5-80ba-e200385fc133.png

**Comment by l8er4now** [comment]
Need a quick update. Thanks.

**App Name:** Veooz:  Personalized News
**Bundle ID:** com.veooz.Veooz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942885631">942885631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/veooz-personalized-news/id942885631?mt=8&uo=4">https://itunes.apple.com/us/app/veooz-personalized-news/id942885631?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Veooz Labs Private Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/veooz-labs-private-limited/id939530454?uo=4>© Veooz Labs Private Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/25/09/d2/2509d29b-57d6-b919-935d-b4eabcff0587/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13265426/2a7862f2-da73-11e5-898b-5b6e6627e06d.png)
https://cloud.githubusercontent.com/assets/2068130/13265426/2a7862f2-da73-11e5-898b-5b6e6627e06d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13265444/3cf4f4d6-da73-11e5-8b45-7420431362ec.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** NewsPlus: Stories for you
**Bundle ID:** com.veooz.Veooz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942885631">942885631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsplus-stories-for-you/id942885631?mt=8&uo=4">https://itunes.apple.com/us/app/newsplus-stories-for-you/id942885631?mt=8&uo=4</a>
**App Version:** 7.1
**Seller:** Veooz Labs Private Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/veooz-labs-private-limited/id939530454?uo=4">© Veooz Labs Private Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/6e/7e/b3/6e7eb384-0e67-4118-fcae-19a2040caba4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37921412-0f99d532-312a-11e8-994a-2a72c9d2155a.png)
https://user-images.githubusercontent.com/20930745/37921412-0f99d532-312a-11e8-994a-2a72c9d2155a.png

Source:
https://user-images.githubusercontent.com/20930745/37921442-20ada66e-312a-11e8-8ddb-3f9a65e36842.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37921457-31e29f5c-312a-11e8-928c-8d5373a05230.png)
https://user-images.githubusercontent.com/20930745/37921457-31e29f5c-312a-11e8-928c-8d5373a05230.png

Source:
https://user-images.githubusercontent.com/20930745/37921480-42490250-312a-11e8-9e4d-a81b000e368c.png
