### ISSUE TITLE
AltaMail

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#6999]
**App Name:** AltaMail
**Bundle ID:** com.eurosmartz.mobile.altamail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=328890658">328890658</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/altamail/id328890658?mt=8&uo=4">https://itunes.apple.com/us/app/altamail/id328890658?mt=8&uo=4</a>
**App Version:** 5.8
**Seller:** EuroSmartz Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eurosmartz-ltd/id299105918?uo=4>© EuroSmartz Ltd</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/ed/b1/39/edb1395e-6dde-01fb-ff3e-2ddcd35d377a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12070154/0879dc1e-b064-11e5-82ff-530567d594ef.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12070154/0879dc1e-b064-11e5-82ff-530567d594ef.png)
https://cloud.githubusercontent.com/assets/2068130/12070154/0879dc1e-b064-11e5-82ff-530567d594ef.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12070156/16f89ec4-b064-11e5-93b8-9ccbd6139141.png
