### ISSUE TITLE
Dark Sky - Hyperlocal Weather, Radar, and Storm Alerts

### ISSUE THREAD

**Issue by braindeadrebel** [glasklart/hd#7]
**App Name:** Dark Sky - Hyperlocal Weather, Radar, and Storm Alerts
**Bundle ID:** com.jackadam.darksky
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=517329357">517329357</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dark-sky-hyperlocal-weather/id517329357?mt=8&uo=4">https://itunes.apple.com/us/app/dark-sky-hyperlocal-weather/id517329357?mt=8&uo=4</a>
**App Version:** 5.0.6
**Seller:** jackadam
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jackadam/id461812081?uo=4>© Jackadam</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/d7/ce/6f/d7ce6f5c-5667-c5c9-6ca8-849cc2e07b79/mzl.lxnjmgyk.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10789700/44ffb5d6-7d7f-11e5-9d37-82a9afdae8ad.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10789700/44ffb5d6-7d7f-11e5-9d37-82a9afdae8ad.png)
https://cloud.githubusercontent.com/assets/10730122/10789700/44ffb5d6-7d7f-11e5-9d37-82a9afdae8ad.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10789696/41d655d6-7d7f-11e5-955b-7856018d45c2.png
