### ISSUE TITLE
iAdministrator

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7001]
**App Name:** iAdministrator
**Bundle ID:** com.synnyg.iAdministrator
**Version:** 1.0.4
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="http://imageshack.com/a/img905/306/CYVCCW.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12215344/0086081a-b6b9-11e5-8f90-efbf27fc32d6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12215344/0086081a-b6b9-11e5-8f90-efbf27fc32d6.png)
https://cloud.githubusercontent.com/assets/2068130/12215344/0086081a-b6b9-11e5-8f90-efbf27fc32d6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12215345/0f2280f6-b6b9-11e5-8884-e720dd485e64.png

**Comment by Anuskuss** [comment]
I'm sorry but Appster gave me a wrong Bundle ID. The real ID is `com.synnyg.iAdministrator`
