### ISSUE TITLE
Multiplexer (Tutorial)

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7002]
**App Name:** Multiplexer (Tutorial)
**Bundle ID:** com.andrewabosh.Multiplexer
**Version:** 1.0
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="http://imageshack.com/a/img911/2590/OMb4fk.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12211023/8c17359e-b65e-11e5-99c7-5612fc890932.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12211023/8c17359e-b65e-11e5-99c7-5612fc890932.png)
https://cloud.githubusercontent.com/assets/2068130/12211023/8c17359e-b65e-11e5-99c7-5612fc890932.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12211029/9b5cf890-b65e-11e5-83b5-e9795bd39f5c.png

**Comment by Anuskuss** [comment]
I'm sorry but Appster gave me a wrong Bundle ID. The real ID is `com.andrewabosh.Multiplexer`
