### ISSUE TITLE
netKillUIbeta

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7003]
**App Name:** netKillUIbeta
**Bundle ID:** eu.teggers.netKillUI
**Version:** 0.2.1-1
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="http://imageshack.com/a/img908/8136/yuyeFp.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10730122/12756486/428c0a60-c9d4-11e5-8235-b3a764ee790b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12211432/4d0b9fd6-b661-11e5-8761-76595bbd4df0.png)
https://cloud.githubusercontent.com/assets/2068130/12211432/4d0b9fd6-b661-11e5-8761-76595bbd4df0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12211453/5bc18ba8-b661-11e5-85dc-728383214890.png

**Comment by Anuskuss** [comment]
I'm sorry but Appster gave me a wrong Bundle ID. The real ID is `eu.teggers.netKillUI`

**Comment by Anuskuss** [comment]
@dreamnet Would it be possible to make the circle "whiter" since it looks kinda grey on my iPhone (in comparison to the [BytaFont 2 logo](https://github.com/glasklart/hd/issues/3937))?

**Comment by Trubbel** [comment]
@Anuskuss, Something like this?

![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10730122/12756486/428c0a60-c9d4-11e5-8235-b3a764ee790b.png)
https://cloud.githubusercontent.com/assets/10730122/12756486/428c0a60-c9d4-11e5-8235-b3a764ee790b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12756487/428bf66a-c9d4-11e5-992b-3e91d1ca94f1.png

**Comment by Anuskuss** [comment]
Thank you :+1:
