### ISSUE TITLE
Mirmir

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7004]
**App Name:** Mirmir
**Bundle ID:** com.cortexdevteam.wingedgudda
**Version:** 1.2
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="http://imageshack.com/a/img633/2269/JkztJC.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12210770/b7289bf8-b65c-11e5-9dbc-6e2078d542cf.png)

**Comment by Anuskuss** [comment]
**Mirmir** is a tweak which allows windowed multitasking on iOS devices. However this tweak doesn't actually install an app in /Application but rather all its files are in
    /Library/Application Support/Lamo
I don't know how to theme this icon (it doesn't have a name on the springboard either) so if someone could install this and test it so we could find a way to theme it.

**Comment by Trubbel** [comment]
Unfortunately it seems like I can't help you out here since `iOS 9.0.2` is not supported and it's also a paid tweak. `$3.99`

**Comment by Anuskuss** [comment]
Do you know where to put the icon (without just placing it in the *Application Support*-Folder)? I could test it.

**Comment by ivanov007** [comment]
try to install appster from cydia, maybe you could get a little more info with this app, or at least it will help you find the install folder if you have iFile installed

**Comment by dreamnet** [comment]
Here is an icon:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12210770/b7289bf8-b65c-11e5-9dbc-6e2078d542cf.png)
https://cloud.githubusercontent.com/assets/2068130/12210770/b7289bf8-b65c-11e5-9dbc-6e2078d542cf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12210782/ce62fd7c-b65c-11e5-84b6-34c4aa9badd8.png

**Comment by dreamnet** [comment]
@Anuskuss What happens if you save the [above icon](https://cloud.githubusercontent.com/assets/2068130/12210770/b7289bf8-b65c-11e5-9dbc-6e2078d542cf.png), rename it to `com.cortexdevteam.wingedgudda@2x.png` and simply copy it to `/Library/Themes/Glasklart Icons.theme/IconBundles`? Don't forget to respring (with Anemone).

**Comment by Anuskuss** [comment]
###### Appster Export
**Package:** com.cortexdevteam.wingedgudda
**Version:** 1.2
**Depends:** firmware (>=8.0), mobilesubstrate
**Icon:** /Library/Appcation Support/Lamo/icon-small@2x.png
**Installed Files:**

    /Library/Application Support/Lamo/*
    /Library/MobileSubstrate/DynamicLibraries/Lamo*

I already tried to put the correctly named icon in `/Library/Themes/Glasklart Icons.theme/IconBundles` but it doesn't theme it.

I don't want to encourage piracy, but for the sake of theming this icon I'll provide the [.deb](http://www4.zippyshare.com/v/arBTQT4Y/file.html). Just make sure to delete it afterwards and buy it if you like it.

**Comment by dreamnet** [comment]
@Anuskuss Can't help, because my iPhone 6 is on iOS 9.02 and If I install the .deb you provided, I simply see nothing - no icon is shown... Mirmir seems to be not compatible with iOS 9.
Have you also tryed to theme the app with the Bundles method?

**Comment by Anuskuss** [comment]
Just tried it. Copied an icon from IconBundles, renamed it after every icon*.png from Lamo/, placed it in Glasklart/Bundles/{id} but still no success.

**Comment by dreamnet** [comment]
@Anuskuss Try `com.cortexdevteam.lamo` as BundleID (with the IconBundles and with the Bundles method). Browsed the source code and found this BundleID a lot of times.

**Comment by Anuskuss** [comment]
Still no result.
I think this tweak injects a icon into springboard without an Info.plist so it's unthemeble.

**Comment by dreamnet** [comment]
@Anuskuss I think you are right... grmph. :cry: So maybe the only way to theme this is to overwrite `Icon@2x.png` in `/Library/Application Support/Lamo/` with the icon I [posted above](https://cloud.githubusercontent.com/assets/2068130/12210770/b7289bf8-b65c-11e5-9dbc-6e2078d542cf.png) directly. I'm going to close this issue... unthemable.

**Comment by Anuskuss** [comment]
I successfully placed a Icon@2x.png into `Lamo` and its finally themed. I know it's sad that we cannot theme it (yet), but for the people who a reading this, it's a workaround.

Anyways, thanks for providing an icon. If something about this situation is changed (eg an update), I will inform you.
