### ISSUE TITLE
Play!

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7006]
**App Name:** Play!
**Bundle ID:** com.virtualapplications.play
**Version:** 20160103
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="http://imageshack.com/a/img905/2760/mURA23.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12209764/8a7a5e18-b655-11e5-8a05-737220bfe1ae.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12209764/8a7a5e18-b655-11e5-8a05-737220bfe1ae.png)
https://cloud.githubusercontent.com/assets/2068130/12209764/8a7a5e18-b655-11e5-8a05-737220bfe1ae.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12209773/9934c380-b655-11e5-9b6d-a393462b9ee9.png
