### ISSUE TITLE
iNDS

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7007]
**App Name:** iNDS
**Bundle ID:** com.ApprenticeMediaLLC.iNDS
**Version:** 1.3.4
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="http://imageshack.com/a/img907/595/H18o41.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12210093/e8252302-b657-11e5-9f02-47952c4fffab.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12210093/e8252302-b657-11e5-9f02-47952c4fffab.png)
https://cloud.githubusercontent.com/assets/2068130/12210093/e8252302-b657-11e5-9f02-47952c4fffab.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12210106/f6798416-b657-11e5-8d8b-facb7c9ff1aa.png

**Comment by Anuskuss** [comment]
I'm sorry but Appster gave me a wrong Bundle ID. The real ID is `com.ApprenticeMediaLLC.iNDS`
