### ISSUE TITLE
Moonlight Game Streaming

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7008]
**App Name:** Moonlight Game Streaming
**Bundle ID:** com.moonlight-stream.Moonlight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1000551566">1000551566</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moonlight-game-streaming/id1000551566?mt=8&uo=4">https://itunes.apple.com/us/app/moonlight-game-streaming/id1000551566?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Diego Waxemberg
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/diego-waxemberg/id931958450?uo=4>© Diego Waxemberg</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/ed/3b/3b/ed3b3bcd-683a-bb77-8e0a-0787117fa895/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12210425/24e479bc-b65a-11e5-8d54-af004077a4a2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12210425/24e479bc-b65a-11e5-8d54-af004077a4a2.png)
https://cloud.githubusercontent.com/assets/2068130/12210425/24e479bc-b65a-11e5-8d54-af004077a4a2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12210430/330ef080-b65a-11e5-8751-a9ca242f21ce.png
