### ISSUE TITLE
BarMagnet

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7009]
**App Name:** BarMagnet
**Bundle ID:** Quarter.BarMagnet
**Version:** 1.8-1
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="http://imageshack.com/a/img903/5329/96OLhJ.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18861533/3ed3a578-8486-11e6-8939-a2b7812c3fb4.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12131903/d9340126-b416-11e5-94c1-01483f7df84d.png)
https://cloud.githubusercontent.com/assets/10730122/12131903/d9340126-b416-11e5-94c1-01483f7df84d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12131900/d502f2ba-b416-11e5-826b-179bf9db913e.png

**Comment by Anuskuss** [comment]
I'm sorry but Appster gave me a wrong Bundle ID. The real ID is `Quarter.BarMagnet`.

**Comment by Trubbel** [comment]
@dreamnet, @Anuskuss Yes you are right. I updated the issue with the correct Bundle ID.

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by dreamnet** [comment]
Icon from @Trubbel 
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18861533/3ed3a578-8486-11e6-8939-a2b7812c3fb4.png)
https://cloud.githubusercontent.com/assets/2068130/18861533/3ed3a578-8486-11e6-8939-a2b7812c3fb4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18861539/502c9db6-8486-11e6-8667-005aaca8a3bf.png
