### ISSUE TITLE
Weather Live

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7010]
**App Name:** Weather Live
**Bundle ID:** com.apalonapps.wl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=749078962">749078962</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-live/id749078962?mt=8&uo=4">https://itunes.apple.com/us/app/weather-live/id749078962?mt=8&uo=4</a>
**App Version:** 4.7
**Seller:** IAC Search & Media Europe Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apalon-apps/id749046894?uo=4>© Apalon Apps</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/3c/36/29/3c362997-a6cc-43cf-0264-b515f4e31e2d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/12135548/cd4ff7ac-b402-11e5-957f-7c0c5c823fbe.png)

**Comment by dreamnet** [comment]
Icon by @ivanov007.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12135324/b51fafe0-b3ff-11e5-81af-47a10023afe8.png)
https://cloud.githubusercontent.com/assets/3090247/12135324/b51fafe0-b3ff-11e5-81af-47a10023afe8.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12135495/2168b0dc-b402-11e5-9230-539f3f848265.png)
https://cloud.githubusercontent.com/assets/3090247/12135495/2168b0dc-b402-11e5-9230-539f3f848265.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12135548/cd4ff7ac-b402-11e5-957f-7c0c5c823fbe.png)
https://cloud.githubusercontent.com/assets/3090247/12135548/cd4ff7ac-b402-11e5-957f-7c0c5c823fbe.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12135549/cda14558-b402-11e5-84d5-d28c30ea54e7.png)
https://cloud.githubusercontent.com/assets/3090247/12135549/cda14558-b402-11e5-84d5-d28c30ea54e7.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/12135488/169799ac-b402-11e5-9429-19fb8c329bc6.png)
https://cloud.githubusercontent.com/assets/3090247/12135500/3235ce54-b402-11e5-92ab-9a505b7c7265.png
https://cloud.githubusercontent.com/assets/3090247/12135578/36a2f5e2-b403-11e5-9dfd-6cbcc3651fcf.png
https://cloud.githubusercontent.com/assets/3090247/12135579/36a7b686-b403-11e5-9e7a-dabc34241305.png
