### ISSUE TITLE
Horizon Chase - World Tour

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7011]
**App Name:** Horizon Chase - World Tour
**Bundle ID:** com.aquiris.horizonchase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=991018252">991018252</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/horizon-chase-world-tour/id991018252?mt=8&uo=4">https://itunes.apple.com/us/app/horizon-chase-world-tour/id991018252?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Aquiris Realidade Virtual LTDA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/aquiris-game-studio/id379776017?uo=4">© Aquiris Game Studio</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/07/33/23/073323bf-c6c7-58a7-0f7c-e810b408edff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23251533/0735773e-f9ae-11e6-916a-9a7bcf056bf7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23251533/0735773e-f9ae-11e6-916a-9a7bcf056bf7.png)
https://cloud.githubusercontent.com/assets/2068130/23251533/0735773e-f9ae-11e6-916a-9a7bcf056bf7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23251545/15853392-f9ae-11e6-91de-c06e6b878c1a.png
