### ISSUE TITLE
Please, Don't Touch Anything

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7012]
**App Name:** Please, Don't Touch Anything
**Bundle ID:** com.bulkypix.pleasedonttouchanything
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1002503055">1002503055</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/please-dont-touch-anything/id1002503055?mt=8&uo=4">https://itunes.apple.com/us/app/please-dont-touch-anything/id1002503055?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** BULKYPIX
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bulkypix/id304521749?uo=4>© Bulkypix</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/5e/c7/70/5ec77088-d553-7231-0312-4edce802d5a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19073975/26ad9798-8a3e-11e6-84df-bf903c25c612.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19073975/26ad9798-8a3e-11e6-84df-bf903c25c612.png)
https://cloud.githubusercontent.com/assets/20930745/19073975/26ad9798-8a3e-11e6-84df-bf903c25c612.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19073989/344bc23a-8a3e-11e6-9ea9-029ec390dbe5.png
