### ISSUE TITLE
JustWatch - Movies & TV Shows

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7013]
**App Name:** JustWatch - Movies & TV Shows
**Bundle ID:** com.justwatch.justwatch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979227482">979227482</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/justwatch-movies-tv-shows/id979227482?mt=8&uo=4">https://itunes.apple.com/us/app/justwatch-movies-tv-shows/id979227482?mt=8&uo=4</a>
**App Version:** 0.3.91
**Seller:** Moviecycle GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/justwatch-movies-tv-shows/id979227481?uo=4>© JustWatch - Movies & TV Shows</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/66/7d/2d/667d2d55-f5c3-7a46-8852-b807fe17d7a2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721934/8e4d7568-e835-11e5-8258-1284d9a53698.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12184321/d319e63c-b594-11e5-9e66-2ad0cb03a089.png)
https://cloud.githubusercontent.com/assets/2068130/12184321/d319e63c-b594-11e5-9e66-2ad0cb03a089.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12184328/e18db5a4-b594-11e5-8ea3-29f38a30f476.png

**Comment by Anuskuss** [comment]
@dreamnet Could you make the font a little bit thicker?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721934/8e4d7568-e835-11e5-8258-1284d9a53698.png)
https://cloud.githubusercontent.com/assets/2068130/13721934/8e4d7568-e835-11e5-8258-1284d9a53698.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13721938/9eee20ac-e835-11e5-9d68-b6cc874ae91b.png
