### ISSUE TITLE
Pixel Picker - Image Color Picker

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7014]
**App Name:** Pixel Picker - Image Color Picker
**Bundle ID:** com.musevisions.iOS.ColorPicker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=930804327">930804327</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pixel-picker-image-color-picker/id930804327?mt=8&uo=4">https://itunes.apple.com/us/app/pixel-picker-image-color-picker/id930804327?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Andrea Bizzotto
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/andrea-bizzotto/id539165502?uo=4>© Andrea Bizzotto</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/cb/b8/ba/cbb8ba71-2709-9341-4606-726a108154f0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12899402/77b318be-ceb1-11e5-9c44-9173c764703f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12899402/77b318be-ceb1-11e5-9c44-9173c764703f.png)
https://cloud.githubusercontent.com/assets/2068130/12899402/77b318be-ceb1-11e5-9c44-9173c764703f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12899415/85fe74c2-ceb1-11e5-931f-cb98a3713626.png

**Comment by Anuskuss** [comment]
I'm wondering if the icon would (still) look good/better if we just keep the "picker".

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721722/4ef50422-e82f-11e5-896d-375e186ee1e6.png)
https://cloud.githubusercontent.com/assets/2068130/13721722/4ef50422-e82f-11e5-896d-375e186ee1e6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13721724/5ea5cfb4-e82f-11e5-89ef-e68cdaab57a5.png
@Anuskuss Your choice....

**Comment by Anuskuss** [comment]
@dreamnet Maybe keep the size of the original?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13726681/661df2f4-e8d3-11e5-8380-d7a104390b01.png)
https://cloud.githubusercontent.com/assets/2068130/13726681/661df2f4-e8d3-11e5-8380-d7a104390b01.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13726686/76a8836e-e8d3-11e5-8f94-8f9ad302ee1e.png

**Comment by Anuskuss** [comment]
@dreamnet Your choice.

**Comment by dreamnet** [comment]
@Anuskuss No, your icon, you choice.

**Comment by ivanov007** [comment]
I think it looks good with the color swatcher

**Comment by dreamnet** [comment]
We leave it as it is.
