### ISSUE TITLE
3DMark Ice Storm Benchmark

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7015]
**App Name:** 3DMark Ice Storm Benchmark
**Bundle ID:** com.futuremark.3DMark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=642839144">642839144</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/3dmark-ice-storm-benchmark/id642839144?uo=4">https://apps.apple.com/us/app/3dmark-ice-storm-benchmark/id642839144?uo=4</a>
**App Version:** 1.4.978
**Seller:** Underwriters Laboratories Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/underwriters-laboratories-inc/id341275025?uo=4">© Underwriters Laboratories, Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple18/v4/99/07/fa/9907fa38-7dec-d5f8-5b3e-748ccb922675/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59973759-2df95180-95a4-11e9-8203-1bffe651ec45.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12184231/59652860-b594-11e5-94ed-5e2cf5f3a3dd.png)
https://cloud.githubusercontent.com/assets/2068130/12184231/59652860-b594-11e5-94ed-5e2cf5f3a3dd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12184238/6772441a-b594-11e5-9f86-10e2b2e47ce0.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59973759-2df95180-95a4-11e9-8203-1bffe651ec45.png)
https://user-images.githubusercontent.com/2068130/59973759-2df95180-95a4-11e9-8203-1bffe651ec45.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59973765-3f425e00-95a4-11e9-85d2-45c16a5f359d.png
