### ISSUE TITLE
JDAnywhere for JDownloader

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7016]
**App Name:** JDAnywhere for JDownloader
**Bundle ID:** de.fundevil.jdanywhere
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=683222457">683222457</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/jdanywhere-fur-jdownloader/id683222457?mt=8&uo=4">https://itunes.apple.com/de/app/jdanywhere-fur-jdownloader/id683222457?mt=8&uo=4</a>
**App Version:** 1.2.6
**Seller:** Oliver Fuerst
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/oliver-fuerst/id683222460?uo=4>© Oliver Fuerst</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://imageshack.com/a/img910/3043/PKZ51L.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12875768/63f70b5c-cdf1-11e5-81ee-49c3e7739f31.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12209071/11b11dcc-b651-11e5-8583-ecf5b6b23789.png)
https://cloud.githubusercontent.com/assets/2068130/12209071/11b11dcc-b651-11e5-8583-ecf5b6b23789.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12209081/21a93ba6-b651-11e5-82d8-d5c1f4576743.png

**Comment by Anuskuss** [comment]
I know this is the official icon for JDAnywhere but it looks bad because there are already "Play"-Icons for other apps. I don't know if the original JDownloader icon would fit better.
<img src="http://orig00.deviantart.net/78c1/f/2009/299/3/8/jdownloader_reflective_icon_by_wagner00.png" width="150" height="150" />

**Comment by Anuskuss** [comment]
Anyone want to work on this?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12875768/63f70b5c-cdf1-11e5-81ee-49c3e7739f31.png)
https://cloud.githubusercontent.com/assets/2068130/12875768/63f70b5c-cdf1-11e5-81ee-49c3e7739f31.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12875770/7ab43022-cdf1-11e5-92cc-ce6f10ec3abc.png

**Comment by Trubbel** [comment]
It seems like this application has been removed from the App Store, can anyone else confirm?

**Comment by dreamnet** [comment]
@Trubbel Yes... but I think we can theme it anyway.
