### ISSUE TITLE
Fantastic Library

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7017]
**App Name:** Fantastic Library
**Bundle ID:** com.lightapps.fantasticlibrary
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=425218953">425218953</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantastic-library/id425218953?mt=8&uo=4">https://itunes.apple.com/us/app/fantastic-library/id425218953?mt=8&uo=4</a>
**App Version:** 4.0.3
**Seller:** Sebastian Klaus
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lightapps/id425218956?uo=4>© LightApps</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/14/fb/7a/14fb7aee-64e1-acf8-a949-f0962168c828/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12191911/0ed597bc-b5da-11e5-9231-57fbf6204ea2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12191911/0ed597bc-b5da-11e5-9231-57fbf6204ea2.png)
https://cloud.githubusercontent.com/assets/2068130/12191911/0ed597bc-b5da-11e5-9231-57fbf6204ea2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12191918/1f7aca06-b5da-11e5-8ed6-acb5d09674cd.png
