### ISSUE TITLE
Futhead

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7018]
**App Name:** Futhead
**Bundle ID:** com.curse.futheadmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943024000">943024000</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/futhead/id943024000?mt=8&uo=4">https://itunes.apple.com/us/app/futhead/id943024000?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Curse, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/curse-inc./id935720217?uo=4>© Curse, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/22/71/07/22710736-08cf-ee94-69f4-3bbc1149c0ce/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12184152/da4893dc-b593-11e5-8b5b-aa3165e3abd3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12184152/da4893dc-b593-11e5-8b5b-aa3165e3abd3.png)
https://cloud.githubusercontent.com/assets/2068130/12184152/da4893dc-b593-11e5-8b5b-aa3165e3abd3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12184160/e8215bb0-b593-11e5-87c0-4e073f3b30bf.png
