### ISSUE TITLE
15 Coins

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7019]
**App Name:** 15 Coins
**Bundle ID:** com.EngagingGames.15Coins
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=812850082">812850082</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/15-coins/id812850082?mt=8&uo=4">https://itunes.apple.com/us/app/15-coins/id812850082?mt=8&uo=4</a>
**App Version:** 1.02
**Seller:** Engaging Games LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/engaging-games-llc/id493207688?uo=4>© Engaging Games LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/0d/25/8b/0d258bc1-a1ea-9f7a-b115-47f2d7dbb8f0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12184089/6689e608-b593-11e5-80a9-9a4054a49b97.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12184089/6689e608-b593-11e5-80a9-9a4054a49b97.png)
https://cloud.githubusercontent.com/assets/2068130/12184089/6689e608-b593-11e5-80a9-9a4054a49b97.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12184097/741a0474-b593-11e5-9080-c9267b312ab3.png
