### ISSUE TITLE
Atom Run

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7022]
**App Name:** Atom Run
**Bundle ID:** net.fingerlab.elgo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598232243">598232243</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/atom-run/id598232243?mt=8&uo=4">https://itunes.apple.com/us/app/atom-run/id598232243?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Fingerlab SARL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fingerlab/id412786610?uo=4>© Fingerlab</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/77/46/0d/77460d2a-6bb1-fd1f-5be7-b85a18ab4b4f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17037851/2674331c-4f93-11e6-9d3f-687327903139.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17037851/2674331c-4f93-11e6-9d3f-687327903139.png)
https://cloud.githubusercontent.com/assets/2068130/17037851/2674331c-4f93-11e6-9d3f-687327903139.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17037860/34922e9a-4f93-11e6-85d8-aae341928574.png

**Comment by Anuskuss** [comment]
Hmm :no_mouth: I don't dislike it, but I don't know how to improve it either.

**Comment by dreamnet** [comment]
I take it .
