### ISSUE TITLE
BEAT DRIFT

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7023]
**App Name:** BEAT DRIFT
**Bundle ID:** LunarPixelGames
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=771771926">771771926</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beat-drift/id771771926?mt=8&uo=4">https://itunes.apple.com/us/app/beat-drift/id771771926?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Digital Uzu, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/digital-uzu-llc/id828759509?uo=4">© Digital Uzu, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/8f/b2/b1/8fb2b1f5-2e55-d885-86e9-e984b0c3db86/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20236381/ca369782-a8b3-11e6-9c29-93a1b1b0cfb3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20236381/ca369782-a8b3-11e6-9c29-93a1b1b0cfb3.png)
https://cloud.githubusercontent.com/assets/2068130/20236381/ca369782-a8b3-11e6-9c29-93a1b1b0cfb3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20236387/db0d29ae-a8b3-11e6-8f9b-ffc1e1952842.png
