### ISSUE TITLE
Beyond Gravity

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7024]
**App Name:** Beyond Gravity
**Bundle ID:** com.qwiboo.beyondgravity
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=714612428">714612428</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beyond-gravity/id714612428?mt=8&uo=4">https://itunes.apple.com/us/app/beyond-gravity/id714612428?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Qwiboo Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/qwiboo-ltd/id323503765?uo=4>© Qwiboo Ltd</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/fa/48/38/fa4838fd-de88-fa61-2ad9-3b36f5274c5f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721511/1f00f780-e82a-11e5-974a-de0d05ea9614.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13556918/82b403e2-e3e5-11e5-8f22-1ccd8c6b319f.png)
https://cloud.githubusercontent.com/assets/2068130/13556918/82b403e2-e3e5-11e5-8f22-1ccd8c6b319f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13556920/91c5e21a-e3e5-11e5-8ea2-166a4a174b78.png

**Comment by Anuskuss** [comment]
@dreamnet Is the empty space in his face necessary?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721511/1f00f780-e82a-11e5-974a-de0d05ea9614.png)
https://cloud.githubusercontent.com/assets/2068130/13721511/1f00f780-e82a-11e5-974a-de0d05ea9614.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13721516/34c51420-e82a-11e5-8ede-962e84f13132.png

**Comment by Anuskuss** [comment]
@dreamnet And if you remove it completely (make it white)?

**Comment by ivanov007** [comment]
the original icon have it so I think the last version looks good
