### ISSUE TITLE
Boom!

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7025]
**App Name:** Boom!
**Bundle ID:** com.happysprites.boom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=579338458">579338458</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boom!/id579338458?mt=8&uo=4">https://itunes.apple.com/us/app/boom!/id579338458?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** Happy Sprites SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/happy-sprites/id515372540?uo=4>© Happy Sprites</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://a1164.phobos.apple.com/us/r1000/053/Purple4/v4/96/bd/7a/96bd7aa4-02ff-cae0-3a85-857331be1e6d/mzl.hniyjmgd.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899279/c9d79532-4bfe-11e6-8f60-c77847d3d57c.png)

**Comment by Trubbel** [comment]
Best I could do, :stuck_out_tongue_winking_eye:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12376575/cd38bd6a-bcfb-11e5-99a2-cd91db1e2207.png)
https://cloud.githubusercontent.com/assets/10730122/12376575/cd38bd6a-bcfb-11e5-99a2-cd91db1e2207.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12376576/cd3bb6a0-bcfb-11e5-8cfe-8ce431b09911.png

**Comment by dreamnet** [comment]
@Trubbel WOOW! It's great! :+1: :+1:

**Comment by ivanov007** [comment]
@Trubbel yup it looks good but I think this is a holiday icon, the "normal" icon looks like this:
![](http://vignette2.wikia.nocookie.net/boomhappysprites/images/b/be/121441.jpg/revision/latest?cb=20130820052841)

**Comment by Trubbel** [comment]
@ivanov007 Ah, I wasn't thinking that far.. :relaxed:

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12378576/7c79ca08-bd42-11e5-93e4-51394d84fd38.png)
https://cloud.githubusercontent.com/assets/10730122/12378576/7c79ca08-bd42-11e5-93e4-51394d84fd38.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12378577/7c7b1cbe-bd42-11e5-8f65-a440aeab54d7.png

**Comment by dreamnet** [comment]
@Trubbel Also: great! :+1:

**Comment by Anuskuss** [comment]
@Trubbel What do you think about removing the frame and resize that character?

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16897742/89bceb08-4bba-11e6-9296-c1acbb2d35c5.png)
https://cloud.githubusercontent.com/assets/10730122/16897742/89bceb08-4bba-11e6-9296-c1acbb2d35c5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16897743/89bf65a4-4bba-11e6-9e2a-d4f2701d138d.png

**Comment by Anuskuss** [comment]
I like it :+1: 
Just one small thing: You forgot (?) to delete the sparkle on his right arm.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899279/c9d79532-4bfe-11e6-8f60-c77847d3d57c.png)
https://cloud.githubusercontent.com/assets/2068130/16899279/c9d79532-4bfe-11e6-8f60-c77847d3d57c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16899284/fd3f84f2-4bfe-11e6-8785-503216c4e092.png
Credits to @Trubbel.

**Comment by Anuskuss** [comment]
Perfect, thanks guys :sunglasses:
