### ISSUE TITLE
Borderline - Life On The Line

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7026]
**App Name:** Borderline - Life On The Line
**Bundle ID:** com.crazylabs.linebound
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=924870826">924870826</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/borderline-life-on-the-line/id924870826?mt=8&uo=4">https://itunes.apple.com/us/app/borderline-life-on-the-line/id924870826?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** CRAZY LABS BY TABTALE , G.P.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/crazy-labs/id721307559?uo=4>© Crazy Labs</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/03/ed/52/03ed5252-7ba4-e865-84a7-5302919979ba/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12191657/a16ab90c-b5d7-11e5-80e8-402a5f52b048.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12191657/a16ab90c-b5d7-11e5-80e8-402a5f52b048.png)
https://cloud.githubusercontent.com/assets/2068130/12191657/a16ab90c-b5d7-11e5-80e8-402a5f52b048.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12191662/b073c4e8-b5d7-11e5-9702-feada3624de6.png

**Comment by ivanov007** [comment]
@dreamnet wow you are on fire :fire: :fire_engine: :fire:
