### ISSUE TITLE
Defend The Dam - Active Lane Defense

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7027]
**App Name:** Defend The Dam - Active Lane Defense
**Bundle ID:** com.dragonarmy.defendthedam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=839652763">839652763</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/defend-dam-active-lane-defense/id839652763?mt=8&uo=4">https://itunes.apple.com/us/app/defend-dam-active-lane-defense/id839652763?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Dragon Army Apps LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dragon-army/id720239517?uo=4>© Dragon Army</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/09/ba/6c/09ba6c7a-b9f3-3c35-2125-b6d963e53df0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13036472/7a40fdba-d368-11e5-962b-2f2bc8bb0861.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13036472/7a40fdba-d368-11e5-962b-2f2bc8bb0861.png)
https://cloud.githubusercontent.com/assets/2068130/13036472/7a40fdba-d368-11e5-962b-2f2bc8bb0861.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13036474/8b0d31fe-d368-11e5-8924-be05cdd94f5b.png
