### ISSUE TITLE
Double Juggle

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7031]
**App Name:** Double Juggle
**Bundle ID:** com.cherrypickgames.doublejuggle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1003706384">1003706384</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/double-juggle/id1003706384?mt=8&uo=4">https://itunes.apple.com/us/app/double-juggle/id1003706384?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Cherry Pick Games Sp. zo.o.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cherrypick-games/id914892983?uo=4>© cherrypick games</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://imageshack.com/a/img903/2775/v6b7AG.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/16168537/adb63d72-34cf-11e6-82a6-23ee26d2aafd.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/16168537/adb63d72-34cf-11e6-82a6-23ee26d2aafd.png)
https://cloud.githubusercontent.com/assets/3090247/16168537/adb63d72-34cf-11e6-82a6-23ee26d2aafd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/16168538/adb8a2ec-34cf-11e6-91f4-5457b8b890c6.png
