### ISSUE TITLE
Devious Dungeon 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7032]
**App Name:** Devious Dungeon 2
**Bundle ID:** com.ravenousgames.deviousdungeon2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967082741">967082741</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/devious-dungeon-2/id967082741?mt=8&uo=4">https://itunes.apple.com/us/app/devious-dungeon-2/id967082741?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Ravenous Games Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ravenous-games-inc./id344310480?uo=4>© Ravenous Games Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/02/90/a7/0290a7cd-e7a9-859f-4cb4-c905e2ddc9a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19147629/47cb7c48-8bb9-11e6-8e82-25fa461452e8.png)

**Comment by 2Qt2beStr8** [comment]
... i don't know how to do it in a other way :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19072735/1a7f9900-8a37-11e6-81a4-3fd55f047340.png)
https://cloud.githubusercontent.com/assets/20930745/19072735/1a7f9900-8a37-11e6-81a4-3fd55f047340.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19072750/3717874e-8a37-11e6-9543-94aa3351f7b0.png

**Comment by 2Qt2beStr8** [comment]
@anuskuss .... tell me how i should make it?

**Comment by Anuskuss** [comment]
@2Qt2beStr8 I don't know man, I'm not an artist :sob:

**Comment by 2Qt2beStr8** [comment]
hmm ... do you like this?


![featured4](https://cloud.githubusercontent.com/assets/20930745/19091193/d1d366aa-8a81-11e6-9a3a-7b9fa6e440bb.png)

**Comment by Anuskuss** [comment]
If you feel more confident, do it.

**Comment by 2Qt2beStr8** [comment]
you must like it .. i have no game apps on my iphone ... i can make the first one in a other style - or the second one if you like it more ...

**Comment by Anuskuss** [comment]
I can live with the latter :smiley:

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19147629/47cb7c48-8bb9-11e6-8e82-25fa461452e8.png)
https://cloud.githubusercontent.com/assets/20930745/19147629/47cb7c48-8bb9-11e6-8e82-25fa461452e8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19147643/559b5d84-8bb9-11e6-8484-2e3b50369549.png
