### ISSUE TITLE
Earn to Die 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7033]
**App Name:** Earn to Die 2
**Bundle ID:** com.notdoppler.EarntoDie2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=891194610">891194610</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/earn-to-die-2/id891194610?mt=8&uo=4">https://itunes.apple.com/us/app/earn-to-die-2/id891194610?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Not Doppler Pty Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/not-doppler/id554937502?uo=4>© Not Doppler</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/f7/ff/df/f7ffdf5e-716f-4735-1ebd-5cf333b4a50f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12183978/af6e09ae-b592-11e5-977a-805e1d77c221.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12183978/af6e09ae-b592-11e5-977a-805e1d77c221.png)
https://cloud.githubusercontent.com/assets/2068130/12183978/af6e09ae-b592-11e5-977a-805e1d77c221.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12183990/c195179e-b592-11e5-8e76-ee64e6e58259.png
