### ISSUE TITLE
FastBall 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7034]
**App Name:** FastBall 2
**Bundle ID:** klikgames.fastball.v2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376575858">376575858</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fastball-2/id376575858?mt=8&uo=4">https://itunes.apple.com/us/app/fastball-2/id376575858?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Ozden Irmak
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/klik!-games/id355522899?uo=4>© Klik! Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/2f/dc/84/2fdc8485-ba67-071e-90d8-e0331a345bb6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16968041/9fb0cca0-4e0c-11e6-9f2b-f049199c3edb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13550042/505e0158-e314-11e5-8803-881a5214e422.png)
https://cloud.githubusercontent.com/assets/2068130/13550042/505e0158-e314-11e5-8803-881a5214e422.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13550045/5ff1d32e-e314-11e5-9b91-c59332dfe9dc.png

**Comment by Anuskuss** [comment]
@dreamnet Could you make the ball solid and remove the velocity lines?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16968041/9fb0cca0-4e0c-11e6-9f2b-f049199c3edb.png)
https://cloud.githubusercontent.com/assets/2068130/16968041/9fb0cca0-4e0c-11e6-9f2b-f049199c3edb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16968047/af851f5a-4e0c-11e6-8fdf-63447656d32b.png

**Comment by Anuskuss** [comment]
@dreamnet Thanks for your icon. So I guess you want to keep the velocity lines? I was looking for a cleaner look but if you like them, I'm okay with that.

**Comment by dreamnet** [comment]
@Anuskuss I just removed the velocity lines just from the ball as you asked for. Removing all other velocity lines will change the "sense" of the icon too much I think.
