### ISSUE TITLE
Flappy Golf

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7035]
**App Name:** Flappy Golf
**Bundle ID:** com.noodlecake.ssgflap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=833756002">833756002</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flappy-golf/id833756002?mt=8&uo=4">https://itunes.apple.com/us/app/flappy-golf/id833756002?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Noodlecake Studios Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/noodlecake-studios-inc/id370828169?uo=4>© Noodlecake Studios Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/96/50/90/965090d7-a899-b0fd-ecba-bd15f25233d1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14470872/70074392-00b1-11e6-853f-ab19883fe3dc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13035697/25be81d4-d356-11e5-9660-405ddc7c7401.png)
https://cloud.githubusercontent.com/assets/2068130/13035697/25be81d4-d356-11e5-9660-405ddc7c7401.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13035702/369db2e0-d356-11e5-96a1-05840220fd06.png
???

**Comment by Anuskuss** [comment]
@dreamnet Sorry to say this, but tbh I don't like it :person_frowning:

**Comment by dreamnet** [comment]
@Anuskuss Me too... :disappointed: :wink:

**Comment by Anuskuss** [comment]
I tried it myself but it just looks like a potato :cry:

**Comment by ivanov007** [comment]
@Anuskuss well the original icon looks like a cheese so, it doesn't makes too much difference :wink:

**Comment by ivanov007** [comment]
maybe something like this:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14470872/70074392-00b1-11e6-853f-ab19883fe3dc.png)
https://cloud.githubusercontent.com/assets/3090247/14470872/70074392-00b1-11e6-853f-ab19883fe3dc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14470873/700b1ecc-00b1-11e6-8dcf-f97aa979847b.png

**Comment by dreamnet** [comment]
I take it, we have to go on with the open requests.... and I think this can't be done better.
