### ISSUE TITLE
Fragger 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7036]
**App Name:** Fragger 2
**Bundle ID:** com.hbrenes.Fragger2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=978187346">978187346</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fragger-2/id978187346?mt=8&uo=4">https://itunes.apple.com/us/app/fragger-2/id978187346?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Harold Brenes
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/harold-brenes/id867202499?uo=4>© Harold Brenes</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/88/06/5d/88065d00-11df-0515-3c59-1b1df9e5646e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17032951/0da8e6aa-4f7c-11e6-8979-7c6ea662fb24.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13035870/dbfaa448-d359-11e5-9a9e-51aa4cc36751.png)
https://cloud.githubusercontent.com/assets/2068130/13035870/dbfaa448-d359-11e5-9a9e-51aa4cc36751.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13035872/eae93dfc-d359-11e5-8f40-3cad768a844f.png

**Comment by Anuskuss** [comment]
@dreamnet Can you make the **2** solid?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17032951/0da8e6aa-4f7c-11e6-8979-7c6ea662fb24.png)
https://cloud.githubusercontent.com/assets/2068130/17032951/0da8e6aa-4f7c-11e6-8979-7c6ea662fb24.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17032962/1cf2f506-4f7c-11e6-8101-78b32cb3b797.png
