### ISSUE TITLE
Hardest Game Ever 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7037]
**App Name:** Hardest Game Ever 2
**Bundle ID:** com.orangenose.hard2.sd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606080169">606080169</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hardest-game-ever-2/id606080169?mt=8&uo=4">https://itunes.apple.com/us/app/hardest-game-ever-2/id606080169?mt=8&uo=4</a>
**App Version:** 9.0
**Seller:** Chien Ming Liang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/orangenose-studios/id484852242?uo=4>© Orangenose Studios</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/21/b5/70/21b570c7-d8d9-1460-1dd6-f2d506e3032d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14942736/6e4ccfee-0fc6-11e6-867b-10920db105ff.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12879851/e655170e-ce39-11e5-9607-5f538c23bd28.png)
https://cloud.githubusercontent.com/assets/2068130/12879851/e655170e-ce39-11e5-9607-5f538c23bd28.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12879857/f440397a-ce39-11e5-8b9b-ad48ec01e9ee.png

**Comment by Anuskuss** [comment]
Could you remove the extra hairlines?
![](https://cloud.githubusercontent.com/assets/7157389/14708521/d7548534-07cb-11e6-9a3a-b7a5999b12ec.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14769663/fdc910f6-0a5d-11e6-8c43-ad84232f79ab.png)
https://cloud.githubusercontent.com/assets/2068130/14769663/fdc910f6-0a5d-11e6-8c43-ad84232f79ab.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14769664/0cf09950-0a5e-11e6-914a-b0c41f2eb6a6.png

**Comment by Anuskuss** [comment]
@dreamnet First of all, thank you for listening. In my question there're two more lines which I don't like (on the bottom). Do you like them or want to remove them?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14942736/6e4ccfee-0fc6-11e6-867b-10920db105ff.png)
https://cloud.githubusercontent.com/assets/2068130/14942736/6e4ccfee-0fc6-11e6-867b-10920db105ff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14942741/7d234cbe-0fc6-11e6-8062-ab5d14c5e05e.png

**Comment by Anuskuss** [comment]
@dreamnet T

**Comment by Anuskuss** [comment]
@dreamnet Thank you!
