### ISSUE TITLE
iMimic Says: 80's Vintage Electronic Retro Classic Memory Game HD Retina

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7038]
**App Name:** iMimic Says: 80's Vintage Electronic Retro Classic Memory Game HD Retina
**Bundle ID:** com.bitwiz.game.imimic.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=412842007">412842007</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/imimic-says-80s-vintage-electronic/id412842007?mt=8&uo=4">https://itunes.apple.com/us/app/imimic-says-80s-vintage-electronic/id412842007?mt=8&uo=4</a>
**App Version:** 1.41
**Seller:** Fernando Sciessere
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fernando-sciessere/id366268787?uo=4>© Fernando Sciessere</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/aa/83/25/aa8325dc-e5fc-e9a8-aa40-b4381c70390e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18992976/5ff8657a-8721-11e6-8969-3fd5c1b3e7d4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18992976/5ff8657a-8721-11e6-8969-3fd5c1b3e7d4.png)
https://cloud.githubusercontent.com/assets/20930745/18992976/5ff8657a-8721-11e6-8969-3fd5c1b3e7d4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18993007/7ac26978-8721-11e6-9f39-79cb9b5c034d.png
