### ISSUE TITLE
iStunt 2 - Insane Hills

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7039]
**App Name:** iStunt 2 - Insane Hills
**Bundle ID:** com.miniclip.istunt2free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427633070">427633070</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/istunt-2-insane-hills/id427633070?mt=8&uo=4">https://itunes.apple.com/us/app/istunt-2-insane-hills/id427633070?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Miniclip SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/miniclip.com/id337457683?uo=4>© Miniclip.com</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/c3/ed/27/c3ed27d8-40e8-e096-505c-add87e22b2aa/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871453/87e3e83e-cd7c-11e5-9480-22d0fa0d3c72.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12182625/87269b5e-b589-11e5-8b37-67a162c40d0d.png)
https://cloud.githubusercontent.com/assets/2068130/12182625/87269b5e-b589-11e5-8b37-67a162c40d0d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12182633/9492af6c-b589-11e5-995a-fb32cceabbb0.png

**Comment by Anuskuss** [comment]
@dreamnet Could you add an **IH** or **Insane Hills** somewhere in the icon, because on my iPhone they have the same name and it's hard to seperate them.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12869314/84a6acc6-cd1b-11e5-88bb-db09e06cb516.png)
https://cloud.githubusercontent.com/assets/10730122/12869314/84a6acc6-cd1b-11e5-88bb-db09e06cb516.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12869315/84a86cfa-cd1b-11e5-80e7-63eee13d07b6.png

**Comment by dreamnet** [comment]
Just some small corrections:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871453/87e3e83e-cd7c-11e5-9480-22d0fa0d3c72.png)
https://cloud.githubusercontent.com/assets/2068130/12871453/87e3e83e-cd7c-11e5-9480-22d0fa0d3c72.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12871455/95c597fe-cd7c-11e5-87e2-d1c1cb9ed464.png
