### ISSUE TITLE
Lep's World Plus

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7040]
**App Name:** Lep's World Plus
**Bundle ID:** at.ner.superjumpPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487250856">487250856</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/leps-world-plus/id487250856?mt=8&uo=4">https://itunes.apple.com/us/app/leps-world-plus/id487250856?mt=8&uo=4</a>
**App Version:** 2.5.0
**Seller:** nerByte GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nerbyte-gmbh/id326478818?uo=4>© nerByte GmbH</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple2/v4/b1/5b/30/b15b306e-6deb-bc1a-5fc7-3f2ba2ea11ce/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12217781/1f4f225c-b70b-11e5-8e7f-e05a3ea9287c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12217781/1f4f225c-b70b-11e5-8e7f-e05a3ea9287c.png)
https://cloud.githubusercontent.com/assets/2068130/12217781/1f4f225c-b70b-11e5-8e7f-e05a3ea9287c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12217783/2e6d4aac-b70b-11e5-8c73-0f8bef630362.png
Icon by @ivanov007.
