### ISSUE TITLE
Lep's World 2 Plus

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7041]
**App Name:** Lep's World 2 Plus
**Bundle ID:** at.ner.lepsWorld2Plus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=529096824">529096824</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/leps-world-2-plus/id529096824?mt=8&uo=4">https://itunes.apple.com/us/app/leps-world-2-plus/id529096824?mt=8&uo=4</a>
**App Version:** 2.5.0
**Seller:** nerByte GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nerbyte-gmbh/id326478818?uo=4>© nerByte GmbH</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/b5/60/c0/b560c025-3a77-1338-c3c8-983d025bfcf2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12217811/5f5bec30-b70c-11e5-8793-92a18c61b5fd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12217811/5f5bec30-b70c-11e5-8793-92a18c61b5fd.png)
https://cloud.githubusercontent.com/assets/2068130/12217811/5f5bec30-b70c-11e5-8793-92a18c61b5fd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12217819/8c547360-b70c-11e5-864f-8bade8d246c3.png
Icon by @ivanov007.
