### ISSUE TITLE
LIMBO

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7042]
**App Name:** LIMBO
**Bundle ID:** com.playdeadgames.limbo.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=656951157">656951157</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/limbo/id656951157?mt=8&uo=4">https://itunes.apple.com/us/app/limbo/id656951157?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** LIMBO ApS / Playdead ApS
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/playdead/id481629893?uo=4>© Playdead</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/4f/34/31/4f343122-2dc2-ca61-4055-3423a0330d1e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12139850/77295222-b463-11e5-98e1-9e2388acb11f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12139850/77295222-b463-11e5-98e1-9e2388acb11f.png)
https://cloud.githubusercontent.com/assets/2068130/12139850/77295222-b463-11e5-98e1-9e2388acb11f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12139866/86e928a4-b463-11e5-9766-875ca886814a.png
