### ISSUE TITLE
Line Runner

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7043]
**App Name:** Line Runner
**Bundle ID:** com.rsz.LineRunner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=414014326">414014326</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/line-runner/id414014326?mt=8&uo=4">https://itunes.apple.com/us/app/line-runner/id414014326?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** Djinnworks GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/djinnworks-gmbh/id302877209?mt=8&uo=4>© Djinnworks GmbH</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/35/a8/76/35a87674-b70f-246f-5184-fb2cefd4ccf9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12180962/c49a9800-b57f-11e5-9848-8dad5329bde7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12180962/c49a9800-b57f-11e5-9848-8dad5329bde7.png)
https://cloud.githubusercontent.com/assets/2068130/12180962/c49a9800-b57f-11e5-9848-8dad5329bde7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12180967/d2636e8a-b57f-11e5-9e44-b069ff1b0ce9.png
