### ISSUE TITLE
Line Runner 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7044]
**App Name:** Line Runner 2
**Bundle ID:** com.rsz.LineRunner2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=591745483">591745483</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/line-runner-2/id591745483?mt=8&uo=4">https://itunes.apple.com/us/app/line-runner-2/id591745483?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Djinnworks GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/djinnworks-gmbh/id302877209?mt=8&uo=4>© Djinnworks GmbH</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/cb/58/4c/cb584ca9-78d9-9bef-c7e8-2f4791b79a75/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13040727/08f7600c-d3b0-11e5-8396-b07d10465037.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13036192/ec91a728-d360-11e5-99f7-9c5b60082914.png)
https://cloud.githubusercontent.com/assets/2068130/13036192/ec91a728-d360-11e5-99f7-9c5b60082914.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13036197/faa980e2-d360-11e5-87ba-8748dd7b1ea1.png

**Comment by Anuskuss** [comment]
@dreamnet Make the **2** bigger and remove the corners of the box.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13040727/08f7600c-d3b0-11e5-8396-b07d10465037.png)
https://cloud.githubusercontent.com/assets/2068130/13040727/08f7600c-d3b0-11e5-8396-b07d10465037.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13040732/18f906c2-d3b0-11e5-8ae6-45935c6851fa.png
