### ISSUE TITLE
Loop Drive : Crash Race

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7045]
**App Name:** Loop Drive : Crash Race
**Bundle ID:** mobi.gameguru.loopdrive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=992442150">992442150</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/loop-drive-crash-race/id992442150?mt=8&uo=4">https://itunes.apple.com/us/app/loop-drive-crash-race/id992442150?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Gameguru Advertisement FZC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gameguru/id978359163?uo=4>© Gameguru</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/46/5d/ed/465ded1b-2e25-3f7f-21a0-2afc046a335b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12896453/6dc2d2c2-cea2-11e5-9081-6b07c90565cd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12896453/6dc2d2c2-cea2-11e5-9081-6b07c90565cd.png)
https://cloud.githubusercontent.com/assets/2068130/12896453/6dc2d2c2-cea2-11e5-9081-6b07c90565cd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12896472/7c194c20-cea2-11e5-9f26-33ef8a05a6da.png
