### ISSUE TITLE
Nobody Said It Was Easy

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7046]
**App Name:** Nobody Said It Was Easy
**Bundle ID:** NobodySaid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=904689303">904689303</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nobody-said-it-was-easy/id904689303?mt=8&uo=4">https://itunes.apple.com/us/app/nobody-said-it-was-easy/id904689303?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Joseph Rothenberg
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/joseph-rothenberg/id837012898?uo=4>© Joseph Rothenberg</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/39/19/44/391944fd-4e94-8b6f-22e1-8256217ccdac/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12139726/9f2bcfda-b462-11e5-81ad-ece64284b6d3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12139726/9f2bcfda-b462-11e5-81ad-ece64284b6d3.png)
https://cloud.githubusercontent.com/assets/2068130/12139726/9f2bcfda-b462-11e5-81ad-ece64284b6d3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12139730/b03c7a7c-b462-11e5-8a9a-613d1ddd3d6f.png
