### ISSUE TITLE
Doodle Nosebreaker

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7047]
**App Name:** Doodle Nosebreaker
**Bundle ID:** com.clintongugrel.doodle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=499372344">499372344</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/doodle-nosebreaker/id499372344?mt=8&uo=4">https://itunes.apple.com/us/app/doodle-nosebreaker/id499372344?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Clinton Gugrel
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/clinton-gugrel/id388857283?uo=4>© Clinton Gugrel</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/33/33/9e/33339e79-f733-9dd8-293e-00739e05fbd9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12181887/2132e2fc-b585-11e5-8d97-5edeb73c458d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12181887/2132e2fc-b585-11e5-8d97-5edeb73c458d.png)
https://cloud.githubusercontent.com/assets/2068130/12181887/2132e2fc-b585-11e5-8d97-5edeb73c458d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12181901/34e07d78-b585-11e5-8748-5beb31a6d9a6.png
