### ISSUE TITLE
Paint it Back

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7048]
**App Name:** Paint it Back
**Bundle ID:** com.CasualLabs.PaintItBack
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=675183907">675183907</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paint-it-back/id675183907?mt=8&uo=4">https://itunes.apple.com/us/app/paint-it-back/id675183907?mt=8&uo=4</a>
**App Version:** 1.31
**Seller:** Casual Labs LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/casual-labs-llc/id497276198?uo=4>© Casual Labs LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/f6/a6/e8/f6a6e8a9-73d9-7422-ba28-72b77ddd1cd5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12182325/c4d8a1a6-b587-11e5-9e42-b0ab583dff0c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12182325/c4d8a1a6-b587-11e5-9e42-b0ab583dff0c.png)
https://cloud.githubusercontent.com/assets/2068130/12182325/c4d8a1a6-b587-11e5-9e42-b0ab583dff0c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12182335/d48be5b8-b587-11e5-9ae6-a4ec5fd19db8.png
