### ISSUE TITLE
Pursuit of Light

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7049]
**App Name:** Pursuit of Light
**Bundle ID:** jamgame.light
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955298998">955298998</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pursuit-of-light/id955298998?mt=8&uo=4">https://itunes.apple.com/us/app/pursuit-of-light/id955298998?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** ZHIPENG WANG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zhipeng-wang/id884737211?uo=4>© ZHIPENG WANG</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple2/v4/68/fb/2a/68fb2a89-81e9-e874-ef35-7750edfb966f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13506247/848ad0d4-e17d-11e5-9b56-60a3437948d4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12895384/7574580c-ce9c-11e5-9a17-feceb688800d.png)
https://cloud.githubusercontent.com/assets/2068130/12895384/7574580c-ce9c-11e5-9a17-feceb688800d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12895402/8793704a-ce9c-11e5-8800-09ac672b1fc2.png

**Comment by Trubbel** [comment]
@dreamnet Nice! :+1:

**Comment by Anuskuss** [comment]
@dreamnet Could you remove the border?

**Comment by dreamnet** [comment]
@Anuskuss Yes, I am also not a fan of all this borders... 
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13506247/848ad0d4-e17d-11e5-9b56-60a3437948d4.png)
https://cloud.githubusercontent.com/assets/2068130/13506247/848ad0d4-e17d-11e5-9b56-60a3437948d4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13506278/ae39dc2c-e17d-11e5-9e1a-762bae37b1e0.png
Jup, looks better without.

**Comment by Anuskuss** [comment]
My plan is to have a Glasklart Glyph theme when Glasklart 5.0 is out :smiling_imp:
