### ISSUE TITLE
QuBe ™

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7050]
**App Name:** QuBe ™
**Bundle ID:** com.fatfish.cube
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=869885212">869885212</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qube/id869885212?mt=8&uo=4">https://itunes.apple.com/us/app/qube/id869885212?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Fat Fish Games Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fat-fish-games-ltd/id720681354?uo=4>© Fat Fish Games Ltd</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/dd/65/ac/dd65ac7c-67af-70e3-66e1-eb7889cb4064/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12182062/3b5a349a-b586-11e5-8b69-67c569bc7cc5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12182062/3b5a349a-b586-11e5-8b69-67c569bc7cc5.png)
https://cloud.githubusercontent.com/assets/2068130/12182062/3b5a349a-b586-11e5-8b69-67c569bc7cc5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12182072/498f7dea-b586-11e5-9c8a-40347ab91e6b.png
