### ISSUE TITLE
Random Heroes

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7051]
**App Name:** Random Heroes
**Bundle ID:** com.ravenousgames.randomheroes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540353158">540353158</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/random-heroes/id540353158?mt=8&uo=4">https://itunes.apple.com/us/app/random-heroes/id540353158?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Ravenous Games Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ravenous-games-inc./id344310480?uo=4>© Ravenous Games Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple2/v4/b0/73/1e/b0731e4d-c406-ce3e-f233-79e7c519802f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16902058/0c0ca294-4c54-11e6-920c-ce65ac0bd0d8.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14407330/2a3b46e8-fe8a-11e5-99b6-8fc29f27c20b.png)
https://cloud.githubusercontent.com/assets/3090247/14407330/2a3b46e8-fe8a-11e5-99b6-8fc29f27c20b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14407331/2a3f3adc-fe8a-11e5-88b7-a5a8f381e768.png

**Comment by Anuskuss** [comment]
@ivanov007 Thanks for you work. Do you mind removing the hair line for me?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16902058/0c0ca294-4c54-11e6-920c-ce65ac0bd0d8.png)
https://cloud.githubusercontent.com/assets/2068130/16902058/0c0ca294-4c54-11e6-920c-ce65ac0bd0d8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16902061/1a2ecd98-4c54-11e6-8b2c-cae353ce3618.png

**Comment by Anuskuss** [comment]
Thanks to both of you.

**Comment by ivanov007** [comment]
but now I can't tell if it's Abraham Lincoln or someone else, besides it looks kind of chubby cheeks, I personally like it better with the sideburns

**Comment by Anuskuss** [comment]
@ivanov007 The beard line was too thin anyway and without it, it makes for a cleaner look.
