### ISSUE TITLE
Random Heroes 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7052]
**App Name:** Random Heroes 2
**Bundle ID:** com.ravenousgames.randomheroes2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=581496229">581496229</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/random-heroes-2/id581496229?mt=8&uo=4">https://itunes.apple.com/us/app/random-heroes-2/id581496229?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Ravenous Games Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ravenous-games-inc./id344310480?uo=4>© Ravenous Games Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/e7/df/2b/e7df2ba4-0a25-6ecf-c04c-46c5947f5532/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14435770/147d5796-ffdf-11e5-9f05-698b97168868.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14435770/147d5796-ffdf-11e5-9f05-698b97168868.png)
https://cloud.githubusercontent.com/assets/3090247/14435770/147d5796-ffdf-11e5-9f05-698b97168868.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14435769/147bd056-ffdf-11e5-875c-728fdef9e9c1.png

**Comment by Anuskuss** [comment]
@ivanov007 Thanks for you work. Do you mind removing the hair and the bear line for me (only make a block for the mouth)?

**Comment by ivanov007** [comment]
it will make no sense
