### ISSUE TITLE
Random Heroes 3

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7053]
**App Name:** Random Heroes 3
**Bundle ID:** com.ravenousgames.randomheroes3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=921379745">921379745</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/random-heroes-3/id921379745?mt=8&uo=4">https://itunes.apple.com/us/app/random-heroes-3/id921379745?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Ravenous Games Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ravenous-games-inc./id344310480?uo=4>© Ravenous Games Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/32/88/6f/32886f59-6b6d-c04f-e921-87219c44a253/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14436495/913ed1d0-ffe2-11e5-95c3-9ab7d8a8ac34.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14436495/913ed1d0-ffe2-11e5-95c3-9ab7d8a8ac34.png)
https://cloud.githubusercontent.com/assets/3090247/14436495/913ed1d0-ffe2-11e5-95c3-9ab7d8a8ac34.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14436496/913f5f1a-ffe2-11e5-815e-8cedd2c7fa60.png

**Comment by Anuskuss** [comment]
@ivanov007 Thanks for you work. Do you mind removing the hair line for me (and make the red hair "black")?

**Comment by ivanov007** [comment]
I think it looks good, I have it installed on my device and those lines mark the difference between the air and the bald part, on my device it looks just good
