### ISSUE TITLE
Robots Love Ice Cream™

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7054]
**App Name:** Robots Love Ice Cream™
**Bundle ID:** com.ayopagames.robotsloveicecream
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=840151571">840151571</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/robots-love-ice-cream/id840151571?mt=8&uo=4">https://itunes.apple.com/us/app/robots-love-ice-cream/id840151571?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Ayopa Games LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ayopa-games-llc/id470423001?uo=4>© Ayopa Games LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/7d/0c/66/7d0c66bc-2b32-7c8b-7108-1c08ed077e16/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12154725/80f0c494-b4c1-11e5-835b-9712362b6124.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12154725/80f0c494-b4c1-11e5-835b-9712362b6124.png)
https://cloud.githubusercontent.com/assets/2068130/12154725/80f0c494-b4c1-11e5-835b-9712362b6124.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12154732/8f7fd57c-b4c1-11e5-988f-3dfedd4992f8.png
