### ISSUE TITLE
Schlag den Raab – Das Spiel

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7055]
**App Name:** Schlag den Raab – Das Spiel
**Bundle ID:** com.brainpool.SDR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=600860858">600860858</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/schlag-den-raab-das-spiel/id600860858?mt=8&uo=4">https://itunes.apple.com/us/app/schlag-den-raab-das-spiel/id600860858?mt=8&uo=4</a>
**App Version:** 1.44
**Seller:** Raab TV-Produktion GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/raab-tv-produktion-gmbh/id600860861?uo=4>© Raab TV-Produktion GmbH</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/a0/8f/38/a08f3823-19e8-eaf7-4e16-8083398fc641/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12897616/b1cc4f2e-cea8-11e5-9545-5bc9573ec3dc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12897616/b1cc4f2e-cea8-11e5-9545-5bc9573ec3dc.png)
https://cloud.githubusercontent.com/assets/2068130/12897616/b1cc4f2e-cea8-11e5-9545-5bc9573ec3dc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12897627/c116bdc0-cea8-11e5-9848-a6ead69c9c13.png
