### ISSUE TITLE
Sheep Frenzy!

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7056]
**App Name:** Sheep Frenzy!
**Bundle ID:** mobi.SheepFrenzy.SheepFrenzy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=968981113">968981113</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sheep-frenzy!/id968981113?mt=8&uo=4">https://itunes.apple.com/us/app/sheep-frenzy!/id968981113?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** Adam Zurek
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adam-zurek/id927881994?uo=4>© Adam Zurek</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/2f/74/b3/2f74b3cc-402e-f83c-31d0-feae1b5be978/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19163799/b519006a-8bfd-11e6-869e-17f666ae34aa.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19163477/6c0ff7a8-8bfc-11e6-896a-9b59007a4bd8.png)
https://cloud.githubusercontent.com/assets/20930745/19163477/6c0ff7a8-8bfc-11e6-896a-9b59007a4bd8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19163502/86ddbbce-8bfc-11e6-9c81-300d154b07f6.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19163799/b519006a-8bfd-11e6-869e-17f666ae34aa.png)
https://cloud.githubusercontent.com/assets/20930745/19163799/b519006a-8bfd-11e6-869e-17f666ae34aa.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19163819/c69f0f6e-8bfd-11e6-90e1-f960c56a9135.png
