### ISSUE TITLE
Super Lemonade Factory Part Two

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7057]
**App Name:** Super Lemonade Factory Part Two
**Bundle ID:** com.initialscommand.SLFPart2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=727504536">727504536</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-lemonade-factory-part/id727504536?mt=8&uo=4">https://itunes.apple.com/us/app/super-lemonade-factory-part/id727504536?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Shane Brouwer
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shane-brouwer/id423090282?uo=4>© Shane Brouwer</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/3a/de/16/3ade16b0-5d65-2dff-a7c3-0a3658e1192f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12255773/c3931150-b8f7-11e5-9716-93c1bf546df8.png)

**Comment by Anuskuss** [comment]
There is also this icon
<img src="http://imageshack.com/a/img905/6374/bgYORR.png" width="150" height="150" />

**Comment by dreamnet** [comment]
@Anuskuss Check this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12228402/4c134c7e-b83b-11e5-9126-4740522025af.png)
If this is OK for you, I just do some corner rounding and that's it.

**Comment by Anuskuss** [comment]
Maybe only display the guy and the girl in front to look more like SLF1?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12245384/74d7a50c-b8a8-11e5-962a-e87691bda66d.png)
@Anuskuss Better?

**Comment by ivanov007** [comment]
@dreamnet :+1:

**Comment by Anuskuss** [comment]
Excellent 👌🏼

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12255773/c3931150-b8f7-11e5-9716-93c1bf546df8.png)
https://cloud.githubusercontent.com/assets/2068130/12255773/c3931150-b8f7-11e5-9716-93c1bf546df8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12255787/d66fc6ce-b8f7-11e5-8f08-0d063dcd27b3.png
