### ISSUE TITLE
Smove

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7058]
**App Name:** Smove
**Bundle ID:** com.sm.pockets
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=968818637">968818637</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smove/id968818637?mt=8&uo=4">https://itunes.apple.com/us/app/smove/id968818637?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Simple Machine, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/simple-machine-llc/id440559596?uo=4>© Simple Machine, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/95/f6/07/95f60799-48d7-8ab9-726e-b056533d4e6e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13026848/13ceb8ba-d237-11e5-87a5-58f7622efff0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12180766/c893b9b0-b57e-11e5-9606-a545202adea0.png)
https://cloud.githubusercontent.com/assets/2068130/12180766/c893b9b0-b57e-11e5-9606-a545202adea0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12180785/dc113fa8-b57e-11e5-8cc1-40a394671c42.png

**Comment by Anuskuss** [comment]
@dreamnet The lines are too thin, please make them thicker or "whiter".

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13026848/13ceb8ba-d237-11e5-87a5-58f7622efff0.png)
https://cloud.githubusercontent.com/assets/2068130/13026848/13ceb8ba-d237-11e5-87a5-58f7622efff0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13026851/219b7870-d237-11e5-9b04-243052e47a38.png
