### ISSUE TITLE
Snake 2k

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7059]
**App Name:** Snake 2k
**Bundle ID:** com.dsd164.snake2k
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527862914">527862914</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snake-2k/id527862914?mt=8&uo=4">https://itunes.apple.com/us/app/snake-2k/id527862914?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** dsd 164 B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dsd-164/id489465257?uo=4>© dsd 164</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/43/17/29/43172974-4b27-4d9e-a9fd-a8317cef1fb1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12154525/56a04ae4-b4c0-11e5-9432-494e4f73a944.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12154525/56a04ae4-b4c0-11e5-9432-494e4f73a944.png)
https://cloud.githubusercontent.com/assets/2068130/12154525/56a04ae4-b4c0-11e5-9432-494e4f73a944.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12154536/66b1149a-b4c0-11e5-8d20-27245dac7c36.png
