### ISSUE TITLE
Sonic The Hedgehog

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7060]
**App Name:** Sonic The Hedgehog
**Bundle ID:** com.sega.sonic1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=316025912">316025912</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sonic-the-hedgehog/id316025912?mt=8&uo=4">https://itunes.apple.com/us/app/sonic-the-hedgehog/id316025912?mt=8&uo=4</a>
**App Version:** 2.0.8
**Seller:** Sega America
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sega/id281966698?mt=8&uo=4>© SEGA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/dc/c4/92/dcc49221-f3d2-d3e9-7281-e1345d0ad7cd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12208873/e6d37d6c-b64f-11e5-88f4-4ce1e564f112.png)

**Comment by dreamnet** [comment]
Icon exists, but needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12208873/e6d37d6c-b64f-11e5-88f4-4ce1e564f112.png)
https://cloud.githubusercontent.com/assets/2068130/12208873/e6d37d6c-b64f-11e5-88f4-4ce1e564f112.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12208882/fa68b1da-b64f-11e5-8660-32db89c0e973.png
