### ISSUE TITLE
Stealth Inc.

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7061]
**App Name:** Stealth Inc.
**Bundle ID:** com.curvedigitalgames.stealthinc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=660730799">660730799</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stealth-inc./id660730799?mt=8&uo=4">https://itunes.apple.com/us/app/stealth-inc./id660730799?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Angel VGD LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/curve-digital-games/id660730802?uo=4>© Curve Digital Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/e5/d6/87/e5d68784-015d-610e-b7d9-ef33d76a2889/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12207674/48a5bb5c-b648-11e5-83e8-97441f6eb8ae.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12207674/48a5bb5c-b648-11e5-83e8-97441f6eb8ae.png)
https://cloud.githubusercontent.com/assets/2068130/12207674/48a5bb5c-b648-11e5-83e8-97441f6eb8ae.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12207705/764a061c-b648-11e5-8b08-f19c826a07e6.png

**Comment by Trubbel** [comment]
@dreamnet Nice one! :+1:

**Comment by dreamnet** [comment]
@Trubbel THX!
