### ISSUE TITLE
Steampunk Tower

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7062]
**App Name:** Steampunk Tower
**Bundle ID:** com.chillingo.steampunktower
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=703474367">703474367</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/steampunk-tower/id703474367?mt=8&uo=4">https://itunes.apple.com/us/app/steampunk-tower/id703474367?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** Chillingo Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chillingo-ltd/id286038741?uo=4">© Chillingo Ltd</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/f6/92/f7/f692f78f-2c2c-fdbc-5a58-49ad9ce0955b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26287038/e7f1032a-3e72-11e7-9439-63964bd0c627.png)

**Comment by 2Qt2beStr8** [comment]
too many small Details to create a good looking icon

???
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24577838/fca1b4f0-16d5-11e7-901e-ec7ed13f9c5e.png)
https://cloud.githubusercontent.com/assets/20930745/24577838/fca1b4f0-16d5-11e7-901e-ec7ed13f9c5e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24577841/16df927e-16d6-11e7-876a-8e5e0e5e0913.png

**Comment by dreamnet** [comment]
...getting bored of this... 😪 
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26287038/e7f1032a-3e72-11e7-9439-63964bd0c627.png)
https://cloud.githubusercontent.com/assets/2068130/26287038/e7f1032a-3e72-11e7-9439-63964bd0c627.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26287042/f61fae60-3e72-11e7-92c0-c05323ec2e1d.png
