### ISSUE TITLE
Steam Punks

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7063]
**App Name:** Steam Punks
**Bundle ID:** com.ashtmj.gs.steampunks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=669596633">669596633</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/steam-punks/id669596633?mt=8&uo=4">https://itunes.apple.com/us/app/steam-punks/id669596633?mt=8&uo=4</a>
**App Version:** 7.7.7
**Seller:** ashley jackson
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ashley-jackson/id456784068?uo=4>© ashley jackson</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/a5/15/1f/a5151f0a-ba33-6e7b-92dc-0880a9f2540a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12139470/046175e6-b461-11e5-89ae-0f7ffc9950a9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12139470/046175e6-b461-11e5-89ae-0f7ffc9950a9.png)
https://cloud.githubusercontent.com/assets/2068130/12139470/046175e6-b461-11e5-89ae-0f7ffc9950a9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12139483/16057f72-b461-11e5-93d8-ead7e4b10055.png
