### ISSUE TITLE
Swing Copters

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7064]
**App Name:** Swing Copters
**Bundle ID:** com.dotgears.swing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905639750">905639750</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swing-copters/id905639750?mt=8&uo=4">https://itunes.apple.com/us/app/swing-copters/id905639750?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** DOTGEARS COMPANY LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/.gears/id1056258060?uo=4>© .GEARS</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/b4/e8/88/b4e888ce-8698-77d1-83fc-b02562e96eed/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12153778/17a49f9c-b4bc-11e5-999e-a049b5b373cd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12153778/17a49f9c-b4bc-11e5-999e-a049b5b373cd.png)
https://cloud.githubusercontent.com/assets/2068130/12153778/17a49f9c-b4bc-11e5-999e-a049b5b373cd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12153787/257beb84-b4bc-11e5-8887-dd8c4c659adc.png
