### ISSUE TITLE
The Room Two

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7065]
**App Name:** The Room Two
**Bundle ID:** com.FireproofStudios.TheRoom2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=667362389">667362389</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-room-two/id667362389?mt=8&uo=4">https://itunes.apple.com/us/app/the-room-two/id667362389?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Fireproof Studios Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fireproof-games/id552039499?uo=4>© Fireproof Games</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/28/53/09/2853097d-c8a3-a87a-ef56-19c49d9ffff2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12138283/031f698a-b458-11e5-9a03-f45d9182122e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12138283/031f698a-b458-11e5-9a03-f45d9182122e.png)
https://cloud.githubusercontent.com/assets/2068130/12138283/031f698a-b458-11e5-9a03-f45d9182122e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12138293/14714578-b458-11e5-9c18-d208450406c6.png
