### ISSUE TITLE
Tiny Striker

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7066]
**App Name:** Tiny Striker
**Bundle ID:** com.fatfish.striker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=868365169">868365169</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tiny-striker/id868365169?mt=8&uo=4">https://itunes.apple.com/us/app/tiny-striker/id868365169?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Fat Fish Games Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fat-fish-games-ltd/id720681354?uo=4>© Fat Fish Games Ltd</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/92/e3/b3/92e3b361-f96e-5967-de14-490fd2c0be48/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12191340/c551517c-b5d3-11e5-804f-d155575442da.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12154197/714f5be8-b4be-11e5-943c-72ebca16f64a.png)
https://cloud.githubusercontent.com/assets/2068130/12154197/714f5be8-b4be-11e5-943c-72ebca16f64a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12154204/8099e01e-b4be-11e5-96f6-209d850f62db.png

**Comment by Anuskuss** [comment]
Without the lines/seperators?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12163799/c12edba0-b510-11e5-9d6d-19fb84cefda5.png)
https://cloud.githubusercontent.com/assets/2068130/12163799/c12edba0-b510-11e5-9d6d-19fb84cefda5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12163809/d060ffd6-b510-11e5-8e77-6f6569cc9a57.png

**Comment by Anuskuss** [comment]
I'm not a designer but I started to draw a character in a 20x20 box. Then I resized it with *Nearest-neighbor interpolation* and added the effects from the samples.

<img src="http://imageshack.com/a/img908/51/pO0dDs.png" width="150" height="150" />

Here is the [.psd](http://www72.zippyshare.com/v/SrHa92Ib/file.html) if you want to look into it and improve it.

**Comment by dreamnet** [comment]
@Anuskuss Oh jeah, that's a good idea - here is the result:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12191340/c551517c-b5d3-11e5-804f-d155575442da.png)
https://cloud.githubusercontent.com/assets/2068130/12191340/c551517c-b5d3-11e5-804f-d155575442da.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12191347/de0ad44a-b5d3-11e5-9fee-78e9f64c099b.png
I think we can use it.
