### ISSUE TITLE
Toilet Time - Mini Games to Play in the Bathroom

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7067]
**App Name:** Toilet Time - Mini Games to Play in the Bathroom
**Bundle ID:** br.com.tapps.toilettime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=736787261">736787261</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/toilet-time-mini-games-to/id736787261?mt=8&uo=4">https://itunes.apple.com/us/app/toilet-time-mini-games-to/id736787261?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** Tapps Tecnologia da Informacao LTDA.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tapps-tecnologia-da-informacao/id444343830?uo=4>© Tapps Tecnologia da Informação Ltda.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/96/6f/24/966f248b-eaac-2ca6-9cae-244ed35acdbe/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12138984/4a72bac6-b45d-11e5-95fb-d945b2035385.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12138984/4a72bac6-b45d-11e5-95fb-d945b2035385.png)
https://cloud.githubusercontent.com/assets/2068130/12138984/4a72bac6-b45d-11e5-95fb-d945b2035385.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12138994/59dce4aa-b45d-11e5-9819-56420a4fb961.png
