### ISSUE TITLE
Virtual Table Tennis

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7068]
**App Name:** Virtual Table Tennis
**Bundle ID:** com.sensedevil.VTTiPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=440650698">440650698</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/virtual-table-tennis/id440650698?mt=8&uo=4">https://itunes.apple.com/us/app/virtual-table-tennis/id440650698?mt=8&uo=4</a>
**App Version:** 4.4.2
**Seller:** SENSEDEVIL GAMES LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sensedevil-games/id440650701?uo=4>© SenseDevil Games</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/91/87/a2/9187a2c2-1b02-f148-9d07-ecd90db267e6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12856476/6b9a831e-cc45-11e5-9616-cc9ec9419046.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12209533/e19db84a-b653-11e5-9550-c9a4f7137af3.png)
https://cloud.githubusercontent.com/assets/2068130/12209533/e19db84a-b653-11e5-9550-c9a4f7137af3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12209538/efc3eec6-b653-11e5-8195-c9ab1a8cf4a9.png

**Comment by Anuskuss** [comment]
@dreamnet Could you simplify this icon a bit? So that the wood part looks more solid.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12856476/6b9a831e-cc45-11e5-9616-cc9ec9419046.png)
https://cloud.githubusercontent.com/assets/10730122/12856476/6b9a831e-cc45-11e5-9616-cc9ec9419046.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12856475/6b98469e-cc45-11e5-82dc-da409588832d.png

**Comment by 2Qt2beStr8** [comment]
same icon for iPad please

**Bundle ID:** com.sensedevil.VTTiPad

**Comment by dreamnet** [comment]
@2Qt2beStr8 You need to open a new issue. I do it for you.
