### ISSUE TITLE
Mr. Square

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7069]
**App Name:** Mr. Square
**Bundle ID:** com.ludicside.mrsquare
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1033690781">1033690781</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mr.-square/id1033690781?mt=8&uo=4">https://itunes.apple.com/us/app/mr.-square/id1033690781?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Daniel Moreira
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/daniel-moreira/id704507184?uo=4>© Daniel Moreira</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://imageshack.com/a/img903/5886/NhRPgU.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12218263/9cc723f6-b71a-11e5-8869-1590549d20f0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12218263/9cc723f6-b71a-11e5-8869-1590549d20f0.png)
https://cloud.githubusercontent.com/assets/2068130/12218263/9cc723f6-b71a-11e5-8869-1590549d20f0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12218266/aef9815e-b71a-11e5-95c4-d6fe989f097d.png
