### ISSUE TITLE
Muffin Knight

### ISSUE THREAD

**Issue by RizzlaXD** [glasklart/hd#707]
**App Name:** Muffin Knight
**Bundle ID:** com.angrymobgames.muffinknight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447610616">447610616</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/muffin-knight/id447610616?mt=8&uo=4">https://itunes.apple.com/us/app/muffin-knight/id447610616?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** 24seven3D
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/angry-mob-games/id365349650?uo=4>© Angry Mob Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/7e/60/e4/7e60e429-b4ad-5ced-e821-c42bd1a973a3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15417190/4e9b632c-1e53-11e6-9070-2205817fe18c.png)

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by Trubbel** [comment]
Not really liking it how it turned out...

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/14573663/aa9d7db2-0356-11e6-9e84-08d88096c1e1.png)
https://cloud.githubusercontent.com/assets/10730122/14573663/aa9d7db2-0356-11e6-9e84-08d88096c1e1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/14573664/aaa2d910-0356-11e6-94b2-e1c3f7dc7d73.png

**Comment by ivanov007** [comment]
@Trubbel maybe if you remove the eyebrows and the pupil

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15417190/4e9b632c-1e53-11e6-9070-2205817fe18c.png)
https://cloud.githubusercontent.com/assets/10730122/15417190/4e9b632c-1e53-11e6-9070-2205817fe18c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/15417189/4e9af7f2-1e53-11e6-9727-5ce742431150.png
