### ISSUE TITLE
Pop the Lock

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7070]
**App Name:** Pop the Lock
**Bundle ID:** com.sm.popTheLock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979100082">979100082</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pop-the-lock/id979100082?mt=8&uo=4">https://itunes.apple.com/us/app/pop-the-lock/id979100082?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Simple Machine, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/simple-machine-llc/id440559596?uo=4>© Simple Machine, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://imageshack.com/a/img903/1186/Y2sJvN.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12138900/b1bacd6e-b45c-11e5-8fdd-8fcf90bb9bcf.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12138900/b1bacd6e-b45c-11e5-8fdd-8fcf90bb9bcf.png)
https://cloud.githubusercontent.com/assets/2068130/12138900/b1bacd6e-b45c-11e5-8fdd-8fcf90bb9bcf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12138906/bf7f367e-b45c-11e5-87a7-77538f131da8.png
