### ISSUE TITLE
Tap Tap Dash

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7071]
**App Name:** Tap Tap Dash
**Bundle ID:** com.secondarm.taptapdash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1034630958">1034630958</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tap-tap-dash/id1034630958?mt=8&uo=4">https://itunes.apple.com/us/app/tap-tap-dash/id1034630958?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** Second Arm Pty Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/second-arm/id1034630957?uo=4>© Second Arm</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/bd/f5/ed/bdf5edfa-9e4c-293d-fc68-338ce5a59979/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12140146/cbff22de-b465-11e5-9dcd-547e6bc8acb1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12140146/cbff22de-b465-11e5-9dcd-547e6bc8acb1.png)
https://cloud.githubusercontent.com/assets/2068130/12140146/cbff22de-b465-11e5-9dcd-547e6bc8acb1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12140151/dba29f36-b465-11e5-9b51-9717bc7a7a02.png
