### ISSUE TITLE
Trambo

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7072]
**App Name:** Trambo
**Bundle ID:** com.robotegames.trambo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=796329480">796329480</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trambo/id796329480?mt=8&uo=4">https://itunes.apple.com/us/app/trambo/id796329480?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** Juha Pennanen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/juha-pennanen/id796329483?uo=4>© Juha Pennanen</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/7f/69/88/7f69888f-1d39-fa6c-2c05-5ab7037a6a58/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13381865/d1d16cd2-de66-11e5-8352-f409440a7f4e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12379778/5e28fc80-bd61-11e5-9dde-1191491b35f2.png)
https://cloud.githubusercontent.com/assets/2068130/12379778/5e28fc80-bd61-11e5-9dde-1191491b35f2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12379782/6e2cbf40-bd61-11e5-938a-268585b78b16.png

**Comment by Anuskuss** [comment]
I'll try to make an icon tomorrow.

**Comment by Anuskuss** [comment]
"Tommorow"

Really the only draft which doesn't look garbage:
![trambo](https://cloud.githubusercontent.com/assets/7157389/12499711/3d3eb6aa-c0ad-11e5-986c-c0eb1c716e45.png)

It's up to you if you improve [it](http://www70.zippyshare.com/v/pzQMpE9S/file.html), or make a own icon. Since as you can tell, I'm not a designer...

**Comment by Trubbel** [comment]
@Anuskuss I like the icon, however it's up to @dreamnet. :smiley:

**Comment by dreamnet** [comment]
@Anuskuss Yeah, looks good - I will overwork it an make a Glasklart icon in a view hours.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12529091/8bd217bc-c1ac-11e5-8e35-3a6a4136c83e.png)
https://cloud.githubusercontent.com/assets/2068130/12529091/8bd217bc-c1ac-11e5-8e35-3a6a4136c83e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12529093/9a28ab00-c1ac-11e5-843a-48e5a6023875.png

**Comment by Anuskuss** [comment]
@dreamnet Could we make the character a little bit smaller? It seems a bit blown up.

**Comment by Trubbel** [comment]
@Anuskuss Something like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12856259/53dcf91a-cc44-11e5-9326-bc6808739257.png)
https://cloud.githubusercontent.com/assets/10730122/12856259/53dcf91a-cc44-11e5-9326-bc6808739257.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12856260/53e268fa-cc44-11e5-841c-673b144cf14a.png

**Comment by Anuskuss** [comment]
@Trubbel I don't know if it would make sense to also include the floor like in the original icon? What do you think?

**Comment by Trubbel** [comment]
@Anuskuss,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100174/57e151a6-d53a-11e5-9f47-7e7ba13bfb98.png)
https://cloud.githubusercontent.com/assets/10730122/13100174/57e151a6-d53a-11e5-9f47-7e7ba13bfb98.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100175/57e4e3f2-d53a-11e5-83a7-8b79092fa78d.png

**Comment by Anuskuss** [comment]
Do you like it @Trubbel?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13381865/d1d16cd2-de66-11e5-8352-f409440a7f4e.png)
https://cloud.githubusercontent.com/assets/2068130/13381865/d1d16cd2-de66-11e5-8352-f409440a7f4e.png
--- ---
https://cloud.githubusercontent.com/assets/2068130/13381867/e2d9648a-de66-11e5-965e-27ba62d3bdba.png
Finally. I don't change this icon anymore.
