### ISSUE TITLE
LEVEL 22

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7073]
**App Name:** LEVEL 22
**Bundle ID:** com.Noego.Level22
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=659295644">659295644</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/level-22/id659295644?mt=8&uo=4">https://itunes.apple.com/us/app/level-22/id659295644?mt=8&uo=4</a>
**App Version:** 1.04
**Seller:** Noego
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/noego/id659295647?uo=4>© Noego</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s
**Original Artwork:**
<img src="http://imageshack.com/a/img908/5120/kpWK81.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13381427/53f86a04-de5c-11e5-825d-986eccb9c95a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13381427/53f86a04-de5c-11e5-825d-986eccb9c95a.png)
https://cloud.githubusercontent.com/assets/2068130/13381427/53f86a04-de5c-11e5-825d-986eccb9c95a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13381430/640d09ae-de5c-11e5-8ce7-99d970f96495.png
