### ISSUE TITLE
Speedify Bonding VPN

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7074]
**App Name:** Speedify Bonding VPN
**Bundle ID:** com.connectify.Speedify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=999025824">999025824</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/speedify-bonding-vpn/id999025824?mt=8&uo=4">https://itunes.apple.com/us/app/speedify-bonding-vpn/id999025824?mt=8&uo=4</a>
**App Version:** 6.3.6
**Seller:** Connectify, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/connectify-inc/id999025823?uo=4">© Connectify, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/11/ac/46/11ac4656-0f3e-6858-ccdf-6951b4822570/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621024-5985af80-a89f-11e8-910e-2d0fe39a2385.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12138548/217c6fe8-b45a-11e5-80dc-b45ede88d69b.png)
https://cloud.githubusercontent.com/assets/2068130/12138548/217c6fe8-b45a-11e5-80dc-b45ede88d69b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12138558/307d717c-b45a-11e5-8603-5a0c539253cd.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621024-5985af80-a89f-11e8-910e-2d0fe39a2385.png)
https://user-images.githubusercontent.com/2068130/44621024-5985af80-a89f-11e8-910e-2d0fe39a2385.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44621028-6904f880-a89f-11e8-80df-b99c1dcc1729.png
