### ISSUE TITLE
Infinite Power

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7077]
**App Name:** Infinite Power
**Bundle ID:** com.bosch.infinitepower1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=915748826">915748826</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/infinite-power/id915748826?mt=8&uo=4">https://itunes.apple.com/us/app/infinite-power/id915748826?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** Robert Bosch GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/robert-bosch-gmbh/id397121518?uo=4>© Robert Bosch GmbH</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/1e/b3/83/1eb38320-aa5e-1a75-2687-786d7c36ad2c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12218217/97db95c6-b719-11e5-8cef-1497cad9b59a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12218217/97db95c6-b719-11e5-8cef-1497cad9b59a.png)
https://cloud.githubusercontent.com/assets/2068130/12218217/97db95c6-b719-11e5-8cef-1497cad9b59a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12218221/a8699276-b719-11e5-8b77-7cf59e9850b5.png
:laughing:
