### ISSUE TITLE
KONAMI Slots - Play Free Vegas Casino Slot Machines and More!

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7078]
**App Name:** KONAMI Slots - Play Free Vegas Casino Slot Machines and More!
**Bundle ID:** com.playstudios.mykonami
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1040172229">1040172229</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/konami-slots-play-free-vegas/id1040172229?mt=8&uo=4">https://itunes.apple.com/us/app/konami-slots-play-free-vegas/id1040172229?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Playstudios, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/playstudios/id624795774?uo=4>© PlayStudios</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/3f/ff/ba/3fffba54-54cf-45ca-7091-c3165260715d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12218080/e2856cb4-b714-11e5-9998-11b6dcd00e23.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12218080/e2856cb4-b714-11e5-9998-11b6dcd00e23.png)
https://cloud.githubusercontent.com/assets/2068130/12218080/e2856cb4-b714-11e5-9998-11b6dcd00e23.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12218081/f51adeea-b714-11e5-9bd3-2850e64a92b1.png
