### ISSUE TITLE
Atresmedia Conecta

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7079]
**App Name:** Atresmedia Conecta
**Bundle ID:** com.antena3.lamoderna
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=495188347">495188347</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/atresmedia-conecta/id495188347?mt=8&uo=4">https://itunes.apple.com/us/app/atresmedia-conecta/id495188347?mt=8&uo=4</a>
**App Version:** 3.1.6
**Seller:** Antena 3 Television
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/antena-3-television/id331213756?uo=4>© Antena 3 Television</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/18/d9/fc/18d9fcd7-cffd-0fe2-fb3f-48e86a3755c4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12206741/e220bbca-b642-11e5-87b6-643e82e33a14.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12206741/e220bbca-b642-11e5-87b6-643e82e33a14.png)
https://cloud.githubusercontent.com/assets/2068130/12206741/e220bbca-b642-11e5-87b6-643e82e33a14.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12206758/f11fd71e-b642-11e5-9746-65d41dcf33b8.png
