### ISSUE TITLE
Cubitos Aragón

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7080]
**App Name:** Cubitos Aragón
**Bundle ID:** com.cubitosaragon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1042520351">1042520351</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/cubitos-aragon/id1042520351?mt=8&uo=4">https://itunes.apple.com/es/app/cubitos-aragon/id1042520351?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Jorge Leal
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/jorge-leal/id798721118?uo=4>© Jorge Leal</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/ee/c7/ab/eec7ab25-2092-315f-b6f9-5a64967de60f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12217703/ed1dc3f8-b708-11e5-828f-e84761ff5ee9.png)

**Comment by dreamnet** [comment]
...wayyy too small....
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12217703/ed1dc3f8-b708-11e5-828f-e84761ff5ee9.png)
https://cloud.githubusercontent.com/assets/2068130/12217703/ed1dc3f8-b708-11e5-828f-e84761ff5ee9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12217707/ff9407cc-b708-11e5-8e34-db0f73fde767.png
