### ISSUE TITLE
MOVISTAR+ FÚTBOL APP

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7081]
**App Name:** MOVISTAR+ FÚTBOL APP
**Bundle ID:** com.prisatv.futbolapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=922099968">922099968</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/movistar+-futbol-app/id922099968?mt=8&uo=4">https://itunes.apple.com/es/app/movistar+-futbol-app/id922099968?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** DTS DISTRIBUIDORA DE TELEVISION DIGITAL S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/canal+yomvi/id540675310?uo=4>© CANAL+YOMVI</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/2f/97/9c/2f979c38-a70f-3650-c888-7a1ebebb6c71/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12206098/5671a876-b63f-11e5-9dac-596b92eeb678.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12206098/5671a876-b63f-11e5-9dac-596b92eeb678.png)
https://cloud.githubusercontent.com/assets/2068130/12206098/5671a876-b63f-11e5-9dac-596b92eeb678.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12206119/6e43184a-b63f-11e5-8729-88df96724040.png
