### ISSUE TITLE
Dibip

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7082]
**App Name:** Dibip
**Bundle ID:** co.dibip
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923835679">923835679</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dibip/id923835679?mt=8&uo=4">https://itunes.apple.com/us/app/dibip/id923835679?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Multisoluciones Arag�n sl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dibip/id988334703?uo=4>© Dibip</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/cc/9a/e1/cc9ae177-e56d-e296-887b-e8207b0c97c2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12215519/4db2b56e-b6c0-11e5-9093-5ae49e6ed8d0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12215519/4db2b56e-b6c0-11e5-9093-5ae49e6ed8d0.png)
https://cloud.githubusercontent.com/assets/2068130/12215519/4db2b56e-b6c0-11e5-9093-5ae49e6ed8d0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12215523/5bac71e6-b6c0-11e5-9639-5a6b474dd578.png
