### ISSUE TITLE
Infuse Pro

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7086]
**App Name:** Infuse Pro
**Bundle ID:** com.firecore.infuse.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=893249751">893249751</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/infuse-pro/id893249751?mt=8&uo=4">https://itunes.apple.com/us/app/infuse-pro/id893249751?mt=8&uo=4</a>
**App Version:** 3.6.2
**Seller:** FireCore, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/firecore-llc/id577130089?uo=4>© FireCore, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/6e/32/5b/6e325b08-a060-e76d-26e0-924c8298af11/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12286862/32a8ae44-b9c8-11e5-9fb2-cba7808952c1.png)

**Comment by dreamnet** [comment]
Same icon as for #4001.
Icon by @ivanov007.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12286862/32a8ae44-b9c8-11e5-9fb2-cba7808952c1.png)
https://cloud.githubusercontent.com/assets/2068130/12286862/32a8ae44-b9c8-11e5-9fb2-cba7808952c1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12286865/448662d2-b9c8-11e5-879e-16f7b07dd682.png
