### ISSUE TITLE
BattleHand

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7088]
**App Name:** BattleHand
**Bundle ID:** com.kongregate.mobile.battlehand
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1043318628">1043318628</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/battlehand/id1043318628?mt=8&uo=4">https://itunes.apple.com/us/app/battlehand/id1043318628?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Kongregate, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kongregate/id491569846?uo=4>© Kongregate</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/d1/83/29/d1832991-1723-5a3f-cfd4-7d439234e1b8/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12251786/d92bfde0-b8d1-11e5-917e-7176e94b42af.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12225627/e7608a98-b80e-11e5-8fb6-305bbe9341ed.png)
https://cloud.githubusercontent.com/assets/10730122/12225627/e7608a98-b80e-11e5-8fb6-305bbe9341ed.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12225626/e76001d6-b80e-11e5-90be-ceb4158b97c3.png

Ummm...

**Comment by dreamnet** [comment]
@Trubbel Very good, but I think the inner part (the skull) should be inverted...?

**Comment by Trubbel** [comment]
@dreamnet,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12251786/d92bfde0-b8d1-11e5-917e-7176e94b42af.png)
https://cloud.githubusercontent.com/assets/10730122/12251786/d92bfde0-b8d1-11e5-917e-7176e94b42af.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12251787/d92c1ab4-b8d1-11e5-9fe0-51a1b239def6.png

**Comment by dreamnet** [comment]
@Trubbel Yes, yes! :+1:
