### ISSUE TITLE
Monster vs Sheep

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7089]
**App Name:** Monster vs Sheep
**Bundle ID:** com.GoonStudios.MonsterVsSheep
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953904916">953904916</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/monster-vs-sheep/id953904916?mt=8&uo=4">https://itunes.apple.com/us/app/monster-vs-sheep/id953904916?mt=8&uo=4</a>
**App Version:** 1.0.02
**Seller:** Goon Studios LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/goon-studios-llc/id541769693?uo=4>© Goon Studios LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/7b/0b/38/7b0b38e9-0ec3-be1e-4bcc-448ddbdb2a05/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12529389/3990c298-c1b4-11e5-82bb-cca50824d863.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12529389/3990c298-c1b4-11e5-82bb-cca50824d863.png)
https://cloud.githubusercontent.com/assets/2068130/12529389/3990c298-c1b4-11e5-82bb-cca50824d863.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12529393/486bb23c-c1b4-11e5-8e97-29e58e059841.png
