### ISSUE TITLE
Procraster - Overcome Procrastination

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7090]
**App Name:** Procraster - Overcome Procrastination
**Bundle ID:** com.simensolbakken.procraster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=654662054">654662054</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/procraster-overcome-procrastination/id654662054?mt=8&uo=4">https://itunes.apple.com/us/app/procraster-overcome-procrastination/id654662054?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Simen Solbakken
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/simen-solbakken/id654662057?uo=4>© Simen Solbakken</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/05/88/cf/0588cf60-2eee-d4c4-cb2d-3930e1d08dc7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12227680/952096ac-b830-11e5-8bf5-583b65cd5eb9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12227680/952096ac-b830-11e5-8bf5-583b65cd5eb9.png)
https://cloud.githubusercontent.com/assets/2068130/12227680/952096ac-b830-11e5-8bf5-583b65cd5eb9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12227681/a897c0b6-b830-11e5-94de-ec6d2366658e.png
