### ISSUE TITLE
Crowman & Wolfboy

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7092]
**App Name:** Crowman & Wolfboy
**Bundle ID:** com.Wither.CrowmanWolfboy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=703247992">703247992</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/crowman-wolfboy/id703247992?mt=8&uo=4">https://itunes.apple.com/us/app/crowman-wolfboy/id703247992?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Wither Studios, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wither-studios-llc/id703247995?uo=4>© Wither Studios, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/93/7b/80/937b80d0-8308-cb70-74d9-1ea03b24e6d4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12256551/31dc6d7c-b8fe-11e5-878d-7a2094645ffe.png)

**Comment by Trubbel** [comment]
Eh..

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12252372/efeccdf2-b8d6-11e5-9d89-e77d78324fcc.png)
https://cloud.githubusercontent.com/assets/10730122/12252372/efeccdf2-b8d6-11e5-9d89-e77d78324fcc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12252371/efebe05e-b8d6-11e5-8ed5-804f019376b2.png

**Comment by dreamnet** [comment]
Another possibility:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12256551/31dc6d7c-b8fe-11e5-878d-7a2094645ffe.png)
https://cloud.githubusercontent.com/assets/2068130/12256551/31dc6d7c-b8fe-11e5-878d-7a2094645ffe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12256555/420d013e-b8fe-11e5-94da-0402224c7ef6.png

**Comment by Trubbel** [comment]
@dreamnet I like it! :+1:

**Comment by dreamnet** [comment]
@Trubbel You can accept the one you like.
