### ISSUE TITLE
DX

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7093]
**App Name:** DX
**Bundle ID:** com.epro.dxiPhoneApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=950139832">950139832</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dx/id950139832?mt=8&uo=4">https://itunes.apple.com/us/app/dx/id950139832?mt=8&uo=4</a>
**App Version:** 3.2.2
**Seller:** EPRO TECHNOLOGY LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/epro-technology-ltd/id629947962?uo=4>© EPRO TECHNOLOGY LTD</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/25/b7/02/25b70214-1981-06d9-0c5d-db9ced34aff4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12277968/a95b56d0-b97e-11e5-8e71-4addbdc5ed84.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12277968/a95b56d0-b97e-11e5-8e71-4addbdc5ed84.png)
https://cloud.githubusercontent.com/assets/2068130/12277968/a95b56d0-b97e-11e5-8e71-4addbdc5ed84.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12277979/b8dd1e4a-b97e-11e5-9a8a-db9a63f0924e.png
