### ISSUE TITLE
7-Eleven Sverige

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7094]
**App Name:** 7-Eleven Sverige
**Bundle ID:** se.pressbyran.7-Eleven
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=643573717">643573717</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/7-eleven-sverige/id643573717?mt=8&uo=4">https://itunes.apple.com/se/app/7-eleven-sverige/id643573717?mt=8&uo=4</a>
**App Version:** 2.03
**Seller:** Reitan Servicehandel Sverige AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/developer/reitan-servicehandel-sverige/id375767064?uo=4>© Reitan Servicehandel Sverige AB</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/f2/66/fd/f266fd39-8f42-1ca3-dc42-86ed0de98879/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12284251/951e530e-b9ae-11e5-9248-35daafe372d3.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12284251/951e530e-b9ae-11e5-9248-35daafe372d3.png)
https://cloud.githubusercontent.com/assets/10730122/12284251/951e530e-b9ae-11e5-9248-35daafe372d3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12284250/951c5fcc-b9ae-11e5-811d-e73fca2a9eba.png

**Comment by Trubbel** [comment]
Alternate,
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12284277/f5701dd2-b9ae-11e5-82fd-d0d215c901ff.png)
https://cloud.githubusercontent.com/assets/10730122/12284277/f5701dd2-b9ae-11e5-82fd-d0d215c901ff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12284276/f56cdad2-b9ae-11e5-9772-c6a52f7f3231.png

**Comment by dreamnet** [comment]
@Trubbel The first one is :+1:.
