### ISSUE TITLE
Everlist - task manager

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7101]
**App Name:** Everlist - task manager
**Bundle ID:** com.everlist.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1066258250">1066258250</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/everlist-task-manager/id1066258250?mt=8&uo=4">https://itunes.apple.com/us/app/everlist-task-manager/id1066258250?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Appalachian Ventures Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appalachian-ventures-inc./id766121043?uo=4>© Appalachian Ventures Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/9a/df/82/9adf82c0-9d12-18f9-27b3-c714551d625e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12605204/0525b90c-c4c3-11e5-95ad-e107689ac130.png)

**Comment by Trubbel** [comment]
Not sure what to do with this,
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12292954/a094e170-b9f0-11e5-91ac-8b3f017a2070.png)
https://cloud.githubusercontent.com/assets/10730122/12292954/a094e170-b9f0-11e5-91ac-8b3f017a2070.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12292953/a094238e-b9f0-11e5-8b53-f696abc53126.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12605204/0525b90c-c4c3-11e5-95ad-e107689ac130.png)
https://cloud.githubusercontent.com/assets/2068130/12605204/0525b90c-c4c3-11e5-95ad-e107689ac130.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12605212/15775df6-c4c3-11e5-960c-1ec5a029d171.png
Maybe something like this?

**Comment by Trubbel** [comment]
@dreamnet Sure! :+1:
