### ISSUE TITLE
RCN2Go

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7102]
**App Name:** RCN2Go
**Bundle ID:** com.rcn.RCN2Go
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=886758566">886758566</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rcn2go/id886758566?mt=8&uo=4">https://itunes.apple.com/us/app/rcn2go/id886758566?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** RCN Telecom Services, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rcn-telecom-services-llc/id610411417?uo=4>© RCN Telecom Services, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/c1/95/f1/c195f181-fefe-a1cd-577b-b7983183503e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12346419/619ede8e-bb54-11e5-9542-c8eed5590308.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12346419/619ede8e-bb54-11e5-9542-c8eed5590308.png)
https://cloud.githubusercontent.com/assets/10730122/12346419/619ede8e-bb54-11e5-9542-c8eed5590308.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12346420/61a02cf8-bb54-11e5-9067-3efaeb70f567.png
