### ISSUE TITLE
AAA Mobile

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7103]
**App Name:** AAA Mobile
**Bundle ID:** com.aaa.iphone.discounts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=310730297">310730297</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aaa-mobile/id310730297?mt=8&uo=4">https://itunes.apple.com/us/app/aaa-mobile/id310730297?mt=8&uo=4</a>
**App Version:** 3.8.1
**Seller:** American Automobile Association
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aaa/id310730300?mt=8&uo=4>© AAA</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/4c/09/55/4c0955d8-2d6a-4a2d-19c6-094e613ce81d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12346488/0d0e4660-bb55-11e5-8ae5-ab3d3521ef4c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12346488/0d0e4660-bb55-11e5-8ae5-ab3d3521ef4c.png)
https://cloud.githubusercontent.com/assets/10730122/12346488/0d0e4660-bb55-11e5-8ae5-ab3d3521ef4c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12346489/0d110daa-bb55-11e5-965b-0a9c25d6b308.png
