### ISSUE TITLE
Clover

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7105]
**App Name:** Clover
**Bundle ID:** com.getperka.customer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=428620381">428620381</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/clover/id428620381?uo=4">https://apps.apple.com/us/app/clover/id428620381?uo=4</a>
**App Version:** 5.1.1
**Seller:** Perka Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/perka-inc/id428620384?uo=4">© Perka Inc.</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/13/e4/77/13e4774a-4d42-d29c-d31e-6199855f3696/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60371310-2947f980-99f9-11e9-8cf8-80e6ff6d906d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12346613/456e17be-bb56-11e5-9683-f3c26264fc3b.png)
https://cloud.githubusercontent.com/assets/10730122/12346613/456e17be-bb56-11e5-9683-f3c26264fc3b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12346612/4556ac32-bb56-11e5-9082-0334efd9adc3.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60371310-2947f980-99f9-11e9-8cf8-80e6ff6d906d.png)
https://user-images.githubusercontent.com/2068130/60371310-2947f980-99f9-11e9-8cf8-80e6ff6d906d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60371331-38c74280-99f9-11e9-95e5-78c51b7098b6.png
