### ISSUE TITLE
Truck Trackr

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7106]
**App Name:** Truck Trackr
**Bundle ID:** com.jkrantz.foodtrucker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=933063687">933063687</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/truck-trackr/id933063687?mt=8&uo=4">https://itunes.apple.com/us/app/truck-trackr/id933063687?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Jeff Krantz
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jeff-krantz/id836452901?uo=4>© Jeff Krantz</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/f4/3a/ba/f43aba33-c9d8-5734-6f98-175b9ce54656/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12378963/f39201e4-bd4e-11e5-9609-6ed2d72a5b53.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12378874/817d58de-bd11-11e5-8ad5-8e53c0f9d796.png)
https://cloud.githubusercontent.com/assets/3090247/12378874/817d58de-bd11-11e5-8ad5-8e53c0f9d796.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/12378875/8180d46e-bd11-11e5-866c-8994fbaa4c34.png

**Comment by dreamnet** [comment]
Better inverted?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12378963/f39201e4-bd4e-11e5-9609-6ed2d72a5b53.png)
https://cloud.githubusercontent.com/assets/2068130/12378963/f39201e4-bd4e-11e5-9609-6ed2d72a5b53.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12378966/03d5faf6-bd4f-11e5-897f-03f9b30530fc.png

**Comment by illinikev** [comment]
Yes.  Good job.  I did it the other way.

Kevin
