### ISSUE TITLE
Panera Bread

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7107]
**App Name:** Panera Bread
**Bundle ID:** com.panerabread.mobile.minneapolis
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=692365393">692365393</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/panera-bread/id692365393?mt=8&uo=4">https://itunes.apple.com/us/app/panera-bread/id692365393?mt=8&uo=4</a>
**App Version:** 1.48.0
**Seller:** Panera, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/panera-bread/id692365396?uo=4>© Panera Bread</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/3d/85/c0/3d85c0d9-4b7b-66f7-24e8-fbcbe98e0597/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12346771/cefe9070-bb57-11e5-9813-709e87442581.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12346771/cefe9070-bb57-11e5-9813-709e87442581.png)
https://cloud.githubusercontent.com/assets/10730122/12346771/cefe9070-bb57-11e5-9813-709e87442581.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12346770/cee7676a-bb57-11e5-8767-6a490723f67a.png
