### ISSUE TITLE
Zomato - Food & Restaurant Finder

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7108]
**App Name:** Zomato - Food & Restaurant Finder
**Bundle ID:** com.zomato.zomato
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=434613896">434613896</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zomato-food-restaurant-finder/id434613896?mt=8&uo=4">https://itunes.apple.com/us/app/zomato-food-restaurant-finder/id434613896?mt=8&uo=4</a>
**App Version:** 9.1
**Seller:** Zomato Media Pvt. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zomato-media-pvt.-ltd./id434613899?uo=4>© Zomato Media Pvt. Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/9e/58/9d/9e589d12-1550-de11-a2cc-150a34bf2add/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12346896/c44f94fc-bb58-11e5-9573-7922a31db2ee.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12346896/c44f94fc-bb58-11e5-9573-7922a31db2ee.png)
https://cloud.githubusercontent.com/assets/10730122/12346896/c44f94fc-bb58-11e5-9573-7922a31db2ee.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12346895/c4395458-bb58-11e5-9968-c15b4c0fd4ac.png
