### ISSUE TITLE
 Wireless Mobile Utility

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7109]
**App Name:** Wireless Mobile Utility
**Bundle ID:** com.nikon-image.WirelessMobileAdapterUtility
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=554157010">554157010</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wireless-mobile-utility/id554157010?mt=8&uo=4">https://itunes.apple.com/us/app/wireless-mobile-utility/id554157010?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** NIKON CORPORATION
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nikon-corporation/id299293370?uo=4>© Nikon Corporation</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/b2/0a/45/b20a450a-3c72-7c4c-5982-63f9e67ac36e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12347003/c570fc30-bb59-11e5-9cb0-c76459044cc3.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12347003/c570fc30-bb59-11e5-9cb0-c76459044cc3.png)
https://cloud.githubusercontent.com/assets/10730122/12347003/c570fc30-bb59-11e5-9cb0-c76459044cc3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12347002/c559f18e-bb59-11e5-8b6f-d1fc2449a392.png
