### ISSUE TITLE
Flick Kick Football

### ISSUE THREAD

**Issue by RizzlaXD** [glasklart/hd#711]
**App Name:** Flick Kick Football
**Bundle ID:** com.sidheinteractive.sif.FKS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376481969">376481969</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flick-kick-football/id376481969?mt=8&uo=4">https://itunes.apple.com/us/app/flick-kick-football/id376481969?mt=8&uo=4</a>
**App Version:** 1.11.0
**Seller:** Prodigy Design Limited T/A Sidhe Interactive
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/prodigy-design-limited-t-sidhe/id323296229?uo=4>© Prodigy Design Limited T/A Sidhe Interactive</a>
**Supported Devices:** iPad23G, iPadMini4G, iPodTouchSixthGen, iPhone5c, iPhone4, iPadThirdGen, iPhone6Plus, iPhone4S, iPodTouchFifthGen, iPadFourthGen, iPadThirdGen4G, iPhone5, iPhone6, iPhone5s, iPad2Wifi, iPadFourthGen4G, iPadMini
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/16/f7/d4/16f7d4c0-9a2c-6624-0fcf-8b20ec94a9a1/mzl.rjbnrcnh.jpg/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9781811/d10e8374-575d-11e5-925e-43ad73c12663.png)

**Comment by ivanov007** [comment]
this icon's source is missing, also I think the ball should be inverted, something like this:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9781811/d10e8374-575d-11e5-925e-43ad73c12663.png)
Source:
https://cloud.githubusercontent.com/assets/3090247/9781811/d10e8374-575d-11e5-925e-43ad73c12663.png
