### ISSUE TITLE
Rick and Morty: Pocket Mortys

### ISSUE THREAD

**Issue by Meyers09** [glasklart/hd#7110]
**App Name:** Rick and Morty: Pocket Mortys
**Bundle ID:** com.turner.pocketmorties
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=992640880">992640880</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rick-and-morty-pocket-mortys/id992640880?mt=8&uo=4">https://itunes.apple.com/us/app/rick-and-morty-pocket-mortys/id992640880?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Turner Broadcasting System, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adult-swim/id398288427?uo=4>© [adult swim]</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/35/c2/42/35c2423a-34d8-2aec-3633-80c45258909c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19143366/b0d52074-8ba3-11e6-8391-605bf3c4c5d4.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12348729/158aa40e-bb6a-11e5-9285-d74e7dbf01d1.png)
https://cloud.githubusercontent.com/assets/10730122/12348729/158aa40e-bb6a-11e5-9285-d74e7dbf01d1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12348730/158a9db0-bb6a-11e5-8f42-ae6456366881.png

**Comment by alpcinar** [comment]
Icon updated.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19143366/b0d52074-8ba3-11e6-8391-605bf3c4c5d4.png)
