### ISSUE TITLE
Punch Club

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7111]
**App Name:** Punch Club
**Bundle ID:** com.tinybuildgames.punchclub
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1024951378">1024951378</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/punch-club/id1024951378?mt=8&uo=4">https://itunes.apple.com/us/app/punch-club/id1024951378?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** TINYBUILD LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tinybuild-llc/id945888376?uo=4>© tinyBuild LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/08/1b/85/081b85d1-fb0f-a4f7-02fd-796f622eae19/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12348574/d5f71fa8-bb68-11e5-9c33-a1bbcad26736.png)

**Comment by Trubbel** [comment]
Hmm...
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12348574/d5f71fa8-bb68-11e5-9c33-a1bbcad26736.png)
https://cloud.githubusercontent.com/assets/10730122/12348574/d5f71fa8-bb68-11e5-9c33-a1bbcad26736.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12348573/d5f543d6-bb68-11e5-803c-94daedec296f.png

**Comment by dreamnet** [comment]
@Trubbel Great one! :+1:
