### ISSUE TITLE
Doodle: Schedule Maker

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7112]
**App Name:** Doodle: Schedule Maker
**Bundle ID:** com.doodle.Doodle-App
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=938182547">938182547</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/doodle-schedule-maker/id938182547?mt=8&uo=4">https://itunes.apple.com/us/app/doodle-schedule-maker/id938182547?mt=8&uo=4</a>
**App Version:** 3.9.1
**Seller:** Doodle AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/doodle-ag/id938069764?uo=4>© Doodle AG</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/56/60/bc/5660bc29-e1c7-9097-6e36-6ab92f9ed422/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12372999/061e75d8-bc30-11e5-9ddc-bf48e35f3aa5.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12372999/061e75d8-bc30-11e5-9ddc-bf48e35f3aa5.png)
https://cloud.githubusercontent.com/assets/3090247/12372999/061e75d8-bc30-11e5-9ddc-bf48e35f3aa5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/12372998/061cf032-bc30-11e5-8402-10542fb110c4.png
