### ISSUE TITLE
iFlipClock Plus HD - Retro Flip Clock and Music Alarm Clock

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7113]
**App Name:** iFlipClock Plus HD - Retro Flip Clock and Music Alarm Clock
**Bundle ID:** us.exedria.iFlipClock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=292874823">292874823</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iflipclock-plus-hd-retro-flip/id292874823?mt=8&uo=4">https://itunes.apple.com/us/app/iflipclock-plus-hd-retro-flip/id292874823?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Antonio Celona
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/exedria/id290570161?uo=4>© Exedria</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/4c/4d/e5/4c4de555-7f83-145d-1b34-938e128d7b4c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12606051/8feec4d2-c4ca-11e5-8778-7f2a83537400.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12606051/8feec4d2-c4ca-11e5-8778-7f2a83537400.png)
https://cloud.githubusercontent.com/assets/2068130/12606051/8feec4d2-c4ca-11e5-8778-7f2a83537400.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12606065/9dfd2398-c4ca-11e5-9ea5-22230c337186.png

**Comment by Trubbel** [comment]
@dreamnet What about a line across the image in the middle?

**Comment by illinikev** [comment]
Not needed in my opinion.  When I started work on it, I had the line but took it out.

Kevin

**Comment by dreamnet** [comment]
I also think it is not needed...
