### ISSUE TITLE
widget weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7114]
**App Name:** widget weather
**Bundle ID:** TRApps.widget-weather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=908649054">908649054</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/widget-weather/id908649054?mt=8&uo=4">https://itunes.apple.com/us/app/widget-weather/id908649054?mt=8&uo=4</a>
**App Version:** 2.4.2
**Seller:** Trond Rossvoll
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/trond-rossvoll/id571419518?uo=4">© Trond Rossvoll</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/07/38/dd/0738dd83-64ec-f6dd-0e0c-1e09225ee188/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49688013-31e3eb80-fb0c-11e8-9407-11741a9c77c2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12433762/4aac5e92-bf03-11e5-9ef7-75e644c04286.png)
https://cloud.githubusercontent.com/assets/2068130/12433762/4aac5e92-bf03-11e5-9ef7-75e644c04286.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12433773/58b04d14-bf03-11e5-9f79-11881c9aab37.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** widget weather
**Bundle ID:** TRApps.widget-weather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=908649054">908649054</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/widget-weather/id908649054?mt=8&uo=4">https://itunes.apple.com/us/app/widget-weather/id908649054?mt=8&uo=4</a>
**App Version:** 2.4.2
**Seller:** Trond Rossvoll
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/trond-rossvoll/id571419518?uo=4">© Trond Rossvoll</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/07/38/dd/0738dd83-64ec-f6dd-0e0c-1e09225ee188/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49688013-31e3eb80-fb0c-11e8-9407-11741a9c77c2.png)
https://user-images.githubusercontent.com/2068130/49688013-31e3eb80-fb0c-11e8-9407-11741a9c77c2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/49688017-41fbcb00-fb0c-11e8-983f-42b1ecb4d39d.png
