### ISSUE TITLE
Musiverse

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7115]
**App Name:** Musiverse
**Bundle ID:** com.pocketgames.musiverse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=485936811">485936811</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/musiverse/id485936811?mt=8&uo=4">https://itunes.apple.com/us/app/musiverse/id485936811?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** Pocket Games Kft.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pocket-games/id485936814?uo=4>© Pocket Games</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/85/35/b8/8535b8db-b7ac-e2f4-972f-1d99b2d553c7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13381708/fb18756c-de62-11e5-8692-785b370fb168.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13381708/fb18756c-de62-11e5-8692-785b370fb168.png)
https://cloud.githubusercontent.com/assets/2068130/13381708/fb18756c-de62-11e5-8692-785b370fb168.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13381710/0bda2274-de63-11e5-8cc4-faf3cfd7291e.png
