### ISSUE TITLE
Rust Bucket

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7116]
**App Name:** Rust Bucket
**Bundle ID:** com.nitrome.rustbucket
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1040158406">1040158406</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rust-bucket/id1040158406?mt=8&uo=4">https://itunes.apple.com/us/app/rust-bucket/id1040158406?mt=8&uo=4</a>
**App Version:** 2
**Seller:** Nitrome
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nitrome/id568079484?uo=4>© Nitrome</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/61/62/32/616232c7-2241-b1bd-3d8c-f174ad326028/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12432052/336c4224-bef9-11e5-8bf3-321a7aa383fc.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12410452/acae3a9a-be75-11e5-84b9-771782537f26.png)
https://cloud.githubusercontent.com/assets/10730122/12410452/acae3a9a-be75-11e5-84b9-771782537f26.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12410453/acaeee2c-be75-11e5-9817-53169f48f3b1.png

**Comment by dreamnet** [comment]
Round corners at the bottom... ?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12432052/336c4224-bef9-11e5-8bf3-321a7aa383fc.png)
https://cloud.githubusercontent.com/assets/2068130/12432052/336c4224-bef9-11e5-8bf3-321a7aa383fc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12432073/5b72560a-bef9-11e5-90fb-220334924b53.png

**Comment by Trubbel** [comment]
@dreamnet Yeah that looks better!
