### ISSUE TITLE
Brisbane Bin and Recycling

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7118]
**App Name:** Brisbane Bin and Recycling
**Bundle ID:** com.ImpactEnvironmental.BrisbaneWasteinfo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=930353192">930353192</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/brisbane-bin-and-recycling/id930353192?mt=8&uo=4">https://itunes.apple.com/us/app/brisbane-bin-and-recycling/id930353192?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Impact Apps Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/impact-apps-pty-ltd/id930353191?uo=4>© Impact Apps Pty Ltd</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple2/v4/a7/42/01/a742013e-a024-c90d-5d0f-88988a0933a2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12529720/6cf57b48-c1c2-11e5-8fe1-daa6f1469aaf.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12529720/6cf57b48-c1c2-11e5-8fe1-daa6f1469aaf.png)
https://cloud.githubusercontent.com/assets/2068130/12529720/6cf57b48-c1c2-11e5-8fe1-daa6f1469aaf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12529722/7ab457fe-c1c2-11e5-81db-b039881c0335.png
