### ISSUE TITLE
GFXBench GL

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7119]
**App Name:** GFXBench GL
**Bundle ID:** com.glbenchmark.glb27
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=627547197">627547197</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gfxbench-gl/id627547197?mt=8&uo=4">https://itunes.apple.com/us/app/gfxbench-gl/id627547197?mt=8&uo=4</a>
**App Version:** 4.0.5
**Seller:** Kishonti
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kishonti-informatics/id344093482?uo=4>© Kishonti Informatics</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/5d/7a/57/5d7a573a-7568-46ca-095a-09442d1df8ae/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12528930/633094b4-c1a7-11e5-968c-fe2ded845f33.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12528930/633094b4-c1a7-11e5-968c-fe2ded845f33.png)
https://cloud.githubusercontent.com/assets/2068130/12528930/633094b4-c1a7-11e5-968c-fe2ded845f33.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12528932/72308050-c1a7-11e5-9069-c49457dfbacd.png
