### ISSUE TITLE
GFXBench Metal

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7120]
**App Name:** GFXBench Metal
**Bundle ID:** net.kishonti.gfxbench.metal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989080902">989080902</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gfxbench-metal/id989080902?mt=8&uo=4">https://itunes.apple.com/us/app/gfxbench-metal/id989080902?mt=8&uo=4</a>
**App Version:** 3.1.3
**Seller:** Kishonti
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kishonti-informatics/id344093482?uo=4>© Kishonti Informatics</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/06/68/fb/0668fb11-7dc2-61bd-e920-701dd76f37f3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12528910/ea6062f8-c1a6-11e5-90c4-3bc21e9799b9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12528910/ea6062f8-c1a6-11e5-90c4-3bc21e9799b9.png)
https://cloud.githubusercontent.com/assets/2068130/12528910/ea6062f8-c1a6-11e5-90c4-3bc21e9799b9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12528912/f9a37660-c1a6-11e5-861e-feed80d3d8b9.png
