### ISSUE TITLE
Face Swap Live

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7121]
**App Name:** Face Swap Live
**Bundle ID:** com.labs.laan.Face-Swap-Live
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1042987645">1042987645</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/face-swap-live/id1042987645?uo=4">https://apps.apple.com/us/app/face-swap-live/id1042987645?uo=4</a>
**App Version:** 2.2.3
**Seller:** Laan Consulting Corp
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/laan-labs/id310916919?uo=4">© Laan Labs</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/94/e5/8a/94e58a29-b462-f811-092e-78ffcf3a72db/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60452688-6269af00-9c2f-11e9-8745-9da22a4a3ac3.png)

**Comment by Anuskuss** [comment]
Maybe use the loading image instead
[!](http://imageshack.com/a/img907/7623/wHjnx6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12529000/c446c956-c1a9-11e5-96d6-ebc71c06c1cf.png)
https://cloud.githubusercontent.com/assets/2068130/12529000/c446c956-c1a9-11e5-96d6-ebc71c06c1cf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12529001/d2c4893c-c1a9-11e5-96a2-9e2a598b78f7.png

**Comment by Anuskuss** [comment]
Without the loading circle?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12531524/738d0d82-c1fd-11e5-8478-d3f2fc81ad4e.png)
https://cloud.githubusercontent.com/assets/2068130/12531524/738d0d82-c1fd-11e5-8478-d3f2fc81ad4e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12531526/83de47e6-c1fd-11e5-8d01-502c57f26064.png

**Comment by Anuskuss** [comment]
Better 👍

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60392942-3eae4800-9b0d-11e9-9064-1d378c91dc57.png)
https://user-images.githubusercontent.com/20930745/60392942-3eae4800-9b0d-11e9-9064-1d378c91dc57.png

Source:
https://user-images.githubusercontent.com/20930745/60392944-3fdf7500-9b0d-11e9-82c7-de04766a0fb2.png

**Comment by 2Qt2beStr8** [comment]
? or:
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60392991-576b2d80-9b0e-11e9-90bd-06c7e651479f.png)
https://user-images.githubusercontent.com/20930745/60392991-576b2d80-9b0e-11e9-90bd-06c7e651479f.png

Source:
https://user-images.githubusercontent.com/20930745/60392992-5934f100-9b0e-11e9-92bd-0fe715b04c1b.png

**Comment by dreamnet** [comment]
❓ 
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60452688-6269af00-9c2f-11e9-8745-9da22a4a3ac3.png)
https://user-images.githubusercontent.com/2068130/60452688-6269af00-9c2f-11e9-8745-9da22a4a3ac3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60452714-72818e80-9c2f-11e9-8f36-e86da86e137f.png
