### ISSUE TITLE
Weather - Radar - Storm with Morecast App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7122]
**App Name:** Weather - Radar - Storm with Morecast App
**Bundle ID:** com.morecast.weather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942413257">942413257</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-radar-storm-morecast/id942413257?mt=8&uo=4">https://itunes.apple.com/us/app/weather-radar-storm-morecast/id942413257?mt=8&uo=4</a>
**App Version:** 3.0.4
**Seller:** UBIMET GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ubimet/id486824097?uo=4>© UBIMET</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/02/52/9f/02529f61-bd94-f82c-ab06-909e56774ec6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18813227/33023e10-82f3-11e6-8dac-ff1a87520f5a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12528964/743fcaee-c1a8-11e5-97d3-7a7df157794b.png)
https://cloud.githubusercontent.com/assets/2068130/12528964/743fcaee-c1a8-11e5-97d3-7a7df157794b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12528965/83a5efd6-c1a8-11e5-8b0a-6ed001350673.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Weather - Radar - Storm with Morecast App
**Bundle ID:** com.morecast.weather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=942413257">942413257</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-radar-storm-morecast/id942413257?mt=8&uo=4">https://itunes.apple.com/us/app/weather-radar-storm-morecast/id942413257?mt=8&uo=4</a>
**App Version:** 3.0.4
**Seller:** UBIMET GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ubimet/id486824097?uo=4>© UBIMET</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/02/52/9f/02529f61-bd94-f82c-ab06-909e56774ec6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18811782/010c8504-82bd-11e6-982a-7c93371836a5.png)
https://cloud.githubusercontent.com/assets/20930745/18811782/010c8504-82bd-11e6-982a-7c93371836a5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18811784/11b14c0a-82bd-11e6-9a25-752360ebccf6.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18811789/773c06fa-82bd-11e6-8c70-57fa282b8ec0.png)
https://cloud.githubusercontent.com/assets/20930745/18811789/773c06fa-82bd-11e6-8c70-57fa282b8ec0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18811791/88be6f94-82bd-11e6-8b8d-40ab6e5e8292.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18813227/33023e10-82f3-11e6-8dac-ff1a87520f5a.png)
https://cloud.githubusercontent.com/assets/2068130/18813227/33023e10-82f3-11e6-8dac-ff1a87520f5a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18813232/45d94d62-82f3-11e6-8827-6672fb39aa99.png
I just did some corner rounding and centered the text. Credits to @2Qt2beStr8.
