### ISSUE TITLE
phonetrait – Smart Contacts Launcher

### ISSUE THREAD

**Issue by pres** [glasklart/hd#7123]
**App Name:** phonetrait – Smart Contacts Launcher
**Bundle ID:** de.paulsteinhilber.Caller
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479472176">479472176</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/phonetrait-smart-contacts/id479472176?mt=8&uo=4">https://itunes.apple.com/us/app/phonetrait-smart-contacts/id479472176?mt=8&uo=4</a>
**App Version:** 3.11.4
**Seller:** Paul Steinhilber
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/paul-steinhilber/id315226816?uo=4>© Paul Steinhilber</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/fb/ed/49/fbed4912-cdaf-1d1f-bddc-c93782e45e53/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12528777/75210e60-c1a2-11e5-81df-50673e37eb70.png)

**Comment by pres** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/877023/12517944/c622d518-c135-11e5-82ff-379fe4859241.png)

https://cloud.githubusercontent.com/assets/877023/12517944/c622d518-c135-11e5-82ff-379fe4859241.png

Source
https://cloud.githubusercontent.com/assets/877023/12518015/32d76fd4-c136-11e5-966e-064ccc63ac98.png

**Comment by dreamnet** [comment]
@pres Wohhooo, good work! :astonished: All fine, except the icon in the source is too small - to see what I mean, just compare your source with mine:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12528777/75210e60-c1a2-11e5-81df-50673e37eb70.png)
https://cloud.githubusercontent.com/assets/2068130/12528777/75210e60-c1a2-11e5-81df-50673e37eb70.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12528779/969a205e-c1a2-11e5-907f-3d081205f406.png
If you want to be on the [contributors list](https://github.com/glasklart/hd/graphs/contributors), you need to add a public mailadress to your Github account.
As I sayed, good work, keep on! :+1: :+1: :+1:
