### ISSUE TITLE
АйДаПрикол :)

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7127]
**App Name:** АйДаПрикол :)
**Bundle ID:** ru.flysoft.idaprikol
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=412412148">412412148</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ajdaprikol/id412412148?mt=8&uo=4">https://itunes.apple.com/us/app/ajdaprikol/id412412148?mt=8&uo=4</a>
**App Version:** 2.5.2
**Seller:** Okrujnost'
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/okrujnost/id322267865?uo=4>© Okrujnost'</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/a9/37/e5/a937e5ef-f2b5-98db-ce5a-d5b607c39948/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12544276/f648313e-c338-11e5-8891-a2bff6a26ac9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12544276/f648313e-c338-11e5-8891-a2bff6a26ac9.png)
https://cloud.githubusercontent.com/assets/2068130/12544276/f648313e-c338-11e5-8891-a2bff6a26ac9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12544282/04b02e52-c339-11e5-9682-cef9c23f9d6f.png
