### ISSUE TITLE
Fotor HDR – HDR Camera & High Resolution Images Creator

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7128]
**App Name:** Fotor HDR – HDR Camera & High Resolution Images Creator
**Bundle ID:** com.everimaging.fotorhdr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=694981416">694981416</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fotor-hdr-hdr-camera-high/id694981416?mt=8&uo=4">https://itunes.apple.com/us/app/fotor-hdr-hdr-camera-high/id694981416?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** Chengdu Everimaging Science and Technology Co., Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chengdu-everimaging-science/id412537783?uo=4>© Chengdu Everimaging Science and Technology Co., Ltd</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/a5/8c/30/a58c30ea-b9e7-199a-6ac6-e5183f0b2f60/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12605435/61186e92-c4c5-11e5-8037-172b1167963b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12605435/61186e92-c4c5-11e5-8037-172b1167963b.png)
https://cloud.githubusercontent.com/assets/2068130/12605435/61186e92-c4c5-11e5-8037-172b1167963b.png
--- ---
https://cloud.githubusercontent.com/assets/2068130/12605440/6e134c98-c4c5-11e5-830c-60ab7f930546.png

**Comment by Grafovich** [comment]
👍
