### ISSUE TITLE
Zombify - Turn yourself into a Zombie

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7129]
**App Name:** Zombify - Turn yourself into a Zombie
**Bundle ID:** Apptly.Zombify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=907217406">907217406</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zombify-turn-yourself-into/id907217406?mt=8&uo=4">https://itunes.apple.com/us/app/zombify-turn-yourself-into/id907217406?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** Apptly LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apptly-llc/id480016024?uo=4>© Apptly LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/e9/83/03/e98303bd-1974-fb9c-e0b8-f4a9e18b9c89/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12574275/bdcd9a22-c402-11e5-8e75-0e8655861912.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12574275/bdcd9a22-c402-11e5-8e75-0e8655861912.png)
https://cloud.githubusercontent.com/assets/2068130/12574275/bdcd9a22-c402-11e5-8e75-0e8655861912.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12574283/cc6deb9a-c402-11e5-8aab-b658cecf20e2.png
Maybe...

**Comment by Grafovich** [comment]
👍
