### ISSUE TITLE
Cortex Camera

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7130]
**App Name:** Cortex Camera
**Bundle ID:** CortexCamera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=517488939">517488939</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cortex-camera/id517488939?mt=8&uo=4">https://itunes.apple.com/us/app/cortex-camera/id517488939?mt=8&uo=4</a>
**App Version:** 1.96
**Seller:** John Corcoran
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/whimsical-productions/id517488942?uo=4>© Whimsical Productions</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/78/76/54/78765434-25cd-2bfa-1e9f-72d967eeb29d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19102559/7392502e-8ad1-11e6-9601-05e6a60b9681.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19071242/5aaeaeba-8a2f-11e6-9fdd-f4423b1122be.png)
https://cloud.githubusercontent.com/assets/20930745/19071242/5aaeaeba-8a2f-11e6-9fdd-f4423b1122be.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19071273/854d810a-8a2f-11e6-930e-b0049a9de0e2.png)

**Comment by dreamnet** [comment]
Small addition:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19102559/7392502e-8ad1-11e6-9601-05e6a60b9681.png)
https://cloud.githubusercontent.com/assets/2068130/19102559/7392502e-8ad1-11e6-9601-05e6a60b9681.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19102567/813300e8-8ad1-11e6-9b8e-e5cbb1851f3e.png
