### ISSUE TITLE
Librika

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7131]
**App Name:** Librika
**Bundle ID:** me.librika.Librika
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955240757">955240757</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/librika/id955240757?mt=8&uo=4">https://itunes.apple.com/us/app/librika/id955240757?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Alexandra Mitrofava
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alexandra-mitrofava/id955240756?uo=4>© Alexandra Mitrofava</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/0c/6d/d2/0c6dd2d5-7a24-ebc7-65c9-a1925bee1217/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543900/987d7888-c334-11e5-85c1-4fbdf7cb4c28.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543900/987d7888-c334-11e5-85c1-4fbdf7cb4c28.png)
https://cloud.githubusercontent.com/assets/2068130/12543900/987d7888-c334-11e5-85c1-4fbdf7cb4c28.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12543903/a61770ca-c334-11e5-9a5d-92aabca5f996.png
