### ISSUE TITLE
Mixlr - Social Live Audio

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7132]
**App Name:** Mixlr - Social Live Audio
**Bundle ID:** com.mixlr.mixlr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=583705714">583705714</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mixlr-social-live-audio/id583705714?mt=8&uo=4">https://itunes.apple.com/us/app/mixlr-social-live-audio/id583705714?mt=8&uo=4</a>
**App Version:** 2.10.2
**Seller:** Mixlr Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mixlr/id583705717?uo=4>© Mixlr</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/23/d3/b2/23d3b21d-7300-f5f3-4c0a-cda719f90d73/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543649/d065f0a2-c331-11e5-995b-58bb4f1a4f8c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543649/d065f0a2-c331-11e5-995b-58bb4f1a4f8c.png)
https://cloud.githubusercontent.com/assets/2068130/12543649/d065f0a2-c331-11e5-995b-58bb4f1a4f8c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12543652/dee77196-c331-11e5-88d2-1302f2daa572.png
