### ISSUE TITLE
PROGOROD navigator

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7134]
**App Name:** PROGOROD navigator
**Bundle ID:** com.cdcom.progorod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448172248">448172248</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/progorod-navigator/id448172248?mt=8&uo=4">https://itunes.apple.com/us/app/progorod-navigator/id448172248?mt=8&uo=4</a>
**App Version:** 2.0.3319
**Seller:** NFB Investment Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nfb-investment-corp./id672288952?uo=4>© NFB Investment Corp.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/77/4b/ee/774beee7-ff98-1ee7-4f90-63fcef94bc74/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543575/f50dd90c-c330-11e5-9c3d-8c88a5b7f789.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543575/f50dd90c-c330-11e5-9c3d-8c88a5b7f789.png)
https://cloud.githubusercontent.com/assets/2068130/12543575/f50dd90c-c330-11e5-9c3d-8c88a5b7f789.png
--- ---
https://cloud.githubusercontent.com/assets/2068130/12543578/02ab99be-c331-11e5-9e84-73bd7d4933a5.png
Looks better without the border in the image.
