### ISSUE TITLE
Объявления Avito

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7135]
**App Name:** Объявления Avito
**Bundle ID:** ru.avito.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417281773">417281773</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ru/app/ob-avlenia-avito/id417281773?mt=8&uo=4">https://itunes.apple.com/ru/app/ob-avlenia-avito/id417281773?mt=8&uo=4</a>
**App Version:** 3.7
**Seller:** KEH eCommerce, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/ru/developer/keh-ecommerce-llc/id417281776?uo=4>© KEH eCommerce, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/1b/ba/d3/1bbad388-92f7-520f-9c2b-2f83d35b773d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543476/3169215a-c330-11e5-82c4-e48d70dbf2fc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543476/3169215a-c330-11e5-82c4-e48d70dbf2fc.png)
https://cloud.githubusercontent.com/assets/2068130/12543476/3169215a-c330-11e5-82c4-e48d70dbf2fc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12543484/3f8f31a2-c330-11e5-81ec-e2157d79a221.png
