### ISSUE TITLE
Суши WOK

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7136]
**App Name:** Суши WOK
**Bundle ID:** ru.sushiwok.sushiwok
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=673954325">673954325</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/susi-wok/id673954325?mt=8&uo=4">https://itunes.apple.com/us/app/susi-wok/id673954325?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Aleksandr Laseev
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aleksandr-laseev/id519000369?uo=4>© Aleksandr Laseev</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/d4/d2/72/d4d272da-adb6-804a-8cb6-07aed3791352/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543414/90d84a72-c32f-11e5-990a-df17234be520.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543246/d9d3a0f2-c32d-11e5-8a7b-b880e481ff63.png)
https://cloud.githubusercontent.com/assets/2068130/12543246/d9d3a0f2-c32d-11e5-8a7b-b880e481ff63.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12543250/e83b2c00-c32d-11e5-9b58-6154dd50f84a.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455161-3e65ffc8-3a74-11e8-8153-358308447818.png)
https://user-images.githubusercontent.com/20930745/38455161-3e65ffc8-3a74-11e8-8153-358308447818.png

Source:
https://user-images.githubusercontent.com/20930745/38455163-4f76da3a-3a74-11e8-9f42-3c518ea21afb.png
