### ISSUE TITLE
Мосэнергосбыт

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7137]
**App Name:** Мосэнергосбыт
**Bundle ID:** ru.tii.lkkios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=544123637">544123637</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mosenergosbyt/id544123637?mt=8&uo=4">https://itunes.apple.com/us/app/mosenergosbyt/id544123637?mt=8&uo=4</a>
**App Version:** 2.8.4
**Seller:** Integrator IT LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/oao-mosenergobyt/id544123640?uo=4>© ОАО «Мосэнергобыт»</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/90/d1/fb/90d1fb96-bf3f-3525-4547-3301c912c415/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12573637/87b9f306-c3fb-11e5-9339-2ae0059fae51.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12573637/87b9f306-c3fb-11e5-9339-2ae0059fae51.png)
https://cloud.githubusercontent.com/assets/2068130/12573637/87b9f306-c3fb-11e5-9339-2ae0059fae51.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12573643/96ca6bdc-c3fb-11e5-9a82-83879ce9c9ea.png

**Comment by Grafovich** [comment]
👍 veery nice
