### ISSUE TITLE
Афиша (Afisha) - гид по развлечениям Москвы и России

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7138]
**App Name:** Афиша (Afisha) - гид по развлечениям Москвы и России
**Bundle ID:** ru.afisha.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=323214038">323214038</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/afisa-afisha-gid-po-razvleceniam/id323214038?mt=8&uo=4">https://itunes.apple.com/us/app/afisa-afisha-gid-po-razvleceniam/id323214038?mt=8&uo=4</a>
**App Version:** 3.0.3
**Seller:** Rambler Internet Holdings LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rambler-internet-holdings/id395455934?uo=4>© Rambler Internet Holdings LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/ba/91/9f/ba919f78-1d3c-7f5d-f3b7-5c6f16e6d03b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539264/d94aa2be-c2ee-11e5-8a4d-af315ca8ae90.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539264/d94aa2be-c2ee-11e5-8a4d-af315ca8ae90.png)
https://cloud.githubusercontent.com/assets/2068130/12539264/d94aa2be-c2ee-11e5-8a4d-af315ca8ae90.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12539267/e99e0714-c2ee-11e5-9a05-6594a1742913.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455130-b37c3be8-3a73-11e8-9fa9-f80416456649.png)
https://user-images.githubusercontent.com/20930745/38455130-b37c3be8-3a73-11e8-9fa9-f80416456649.png

Source:
https://user-images.githubusercontent.com/20930745/38455134-c6ab9074-3a73-11e8-9d5a-6303853f1cd8.png
