### ISSUE TITLE
«МегаФон» Личный кабинет

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7139]
**App Name:** «МегаФон» Личный кабинет
**Bundle ID:** ru.megafon.lk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=778681735">778681735</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/megafon-licnyj-kabinet/id778681735?mt=8&uo=4">https://itunes.apple.com/us/app/megafon-licnyj-kabinet/id778681735?mt=8&uo=4</a>
**App Version:** 2.3.0
**Seller:** PJSC MegaFon
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pjsc-megafon/id409303413?uo=4>© PJSC MegaFon</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/02/4d/6c/024d6ce1-2de9-1b24-b6a9-5f38956a948a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543135/7cc5a4e2-c32c-11e5-89cc-54adda4f7b1d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543135/7cc5a4e2-c32c-11e5-89cc-54adda4f7b1d.png)
https://cloud.githubusercontent.com/assets/2068130/12543135/7cc5a4e2-c32c-11e5-89cc-54adda4f7b1d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12543141/8b5d040a-c32c-11e5-8d8a-b8047ab002c4.png
