### ISSUE TITLE
Объявления на Auto.ru — купить или продать подержанные автомобили в Москве, Санкт-Петербурге и других городах России

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7140]
**App Name:** Объявления на Auto.ru — купить или продать подержанные автомобили в Москве, Санкт-Петербурге и других городах России
**Bundle ID:** ru.AutoRu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507760450">507760450</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ob-avlenia-na-auto.ru-kupit/id507760450?mt=8&uo=4">https://itunes.apple.com/us/app/ob-avlenia-na-auto.ru-kupit/id507760450?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** AUTO.RU LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/auto.ru-holding/id507760453?uo=4>© AUTO.RU Holding</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/72/32/8c/72328cfa-f587-b3f4-811d-3a816672013a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539202/43703728-c2ed-11e5-8122-a7c41fed3798.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539202/43703728-c2ed-11e5-8122-a7c41fed3798.png)
https://cloud.githubusercontent.com/assets/2068130/12539202/43703728-c2ed-11e5-8122-a7c41fed3798.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12539203/51b6146a-c2ed-11e5-81af-be30bc730f77.png
