### ISSUE TITLE
Объявления Из рук в руки

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7141]
**App Name:** Объявления Из рук в руки
**Bundle ID:** ru.irr.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=419109009">419109009</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ob-avlenia-iz-ruk-v-ruki/id419109009?mt=8&uo=4">https://itunes.apple.com/us/app/ob-avlenia-iz-ruk-v-ruki/id419109009?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** Pronto-Moscow LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pronto-moscow-llc/id419109012?uo=4>© Pronto-Moscow LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/d7/20/8e/d7208e73-42ed-8932-cd88-6a0ad116bb48/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539221/c44c3cf2-c2ed-11e5-9886-33e8d7276715.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539221/c44c3cf2-c2ed-11e5-9886-33e8d7276715.png)
https://cloud.githubusercontent.com/assets/2068130/12539221/c44c3cf2-c2ed-11e5-9886-33e8d7276715.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12539224/d31084a0-c2ed-11e5-8f99-dee3455c7f07.png
