### ISSUE TITLE
Мой М.Видео

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7142]
**App Name:** Мой М.Видео
**Bundle ID:** com.redmadrobot.mvideo-retail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1063701270">1063701270</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moj-m.video/id1063701270?mt=8&uo=4">https://itunes.apple.com/us/app/moj-m.video/id1063701270?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** REDMADROBOT LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/redmadrobot/id319716479?uo=4>© REDMADROBOT</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/c1/16/c3/c116c307-bc5c-f689-b694-3ea1e180075c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539181/dcc31a0e-c2ec-11e5-9e54-29471cc6cd9b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539181/dcc31a0e-c2ec-11e5-9e54-29471cc6cd9b.png)
https://cloud.githubusercontent.com/assets/2068130/12539181/dcc31a0e-c2ec-11e5-9e54-29471cc6cd9b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12539182/eb3550ac-c2ec-11e5-9922-3f8e071161cf.png
