### ISSUE TITLE
Мой ОнЛайм

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7143]
**App Name:** Мой ОнЛайм
**Bundle ID:** development.OnLime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=787237917">787237917</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moj-onlajm/id787237917?mt=8&uo=4">https://itunes.apple.com/us/app/moj-onlajm/id787237917?mt=8&uo=4</a>
**App Version:** 8.1
**Seller:** Rostelecom
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/oao-rostelecom/id428474472?uo=4>© OAO "Rostelecom"</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/b8/c8/9f/b8c89fc5-8dee-cfd9-34e6-75a2d4874c3c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543085/e9c1e91c-c32b-11e5-8dd2-e96a6cece0b9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543085/e9c1e91c-c32b-11e5-8dd2-e96a6cece0b9.png)
https://cloud.githubusercontent.com/assets/2068130/12543085/e9c1e91c-c32b-11e5-8dd2-e96a6cece0b9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12543090/f87f2f5a-c32b-11e5-8e6f-f0161cef2146.png
