### ISSUE TITLE
EMIAS.INFO

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7144]
**App Name:** EMIAS.INFO
**Bundle ID:** P-C-H.EMIAS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=949484366">949484366</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/emias-info/id949484366?uo=4">https://apps.apple.com/us/app/emias-info/id949484366?uo=4</a>
**App Version:** 4.21
**Seller:** P-C-H OOO
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/p-c-h-ooo/id949484365?uo=4">© P-C-H OOO</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/69/df/a8/69dfa8a5-7a88-8b5b-d38a-efdbfe6c4c33/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388191-29560100-9aae-11e9-8720-0f5a8cb54cc5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539243/54b59d1a-c2ee-11e5-8b9d-5678ca31a66d.png)
https://cloud.githubusercontent.com/assets/2068130/12539243/54b59d1a-c2ee-11e5-8b9d-5678ca31a66d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12539246/63c8d2c2-c2ee-11e5-9b54-b252460ca506.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388191-29560100-9aae-11e9-8720-0f5a8cb54cc5.png)
https://user-images.githubusercontent.com/20930745/60388191-29560100-9aae-11e9-8720-0f5a8cb54cc5.png

Source:
https://user-images.githubusercontent.com/20930745/60388194-2d821e80-9aae-11e9-85bd-1a64ba8d8eec.png
