### ISSUE TITLE
Gorky Park

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7145]
**App Name:** Gorky Park
**Bundle ID:** com.akzia.apps.gorkypark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=549152154">549152154</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gorky-park/id549152154?mt=8&uo=4">https://itunes.apple.com/us/app/gorky-park/id549152154?mt=8&uo=4</a>
**App Version:** 1.6.5
**Seller:** Akzia.Media LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/akzia.media-llc/id549152157?uo=4>© Akzia.Media LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/a7/47/70/a747701c-aef8-5027-8587-a27e06540747/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539282/5787157c-c2ef-11e5-87d9-8fdf8afa5088.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539282/5787157c-c2ef-11e5-87d9-8fdf8afa5088.png)
https://cloud.githubusercontent.com/assets/2068130/12539282/5787157c-c2ef-11e5-87d9-8fdf8afa5088.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12539285/66112308-c2ef-11e5-9b9b-b0a94a6d7457.png
