### ISSUE TITLE
Скидки на электронику

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7146]
**App Name:** Скидки на электронику
**Bundle ID:** com.igoodprice.ruelectronics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=982745178">982745178</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skidki-na-elektroniku/id982745178?mt=8&uo=4">https://itunes.apple.com/us/app/skidki-na-elektroniku/id982745178?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Sergey Devitsyn
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sergey-devitsyn/id982745177?uo=4>© Sergey Devitsyn</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/18/44/e1/1844e1a3-de84-185d-36d6-fb073480f246/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543713/91bf0626-c332-11e5-83af-ee138b5ce0bc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12543713/91bf0626-c332-11e5-83af-ee138b5ce0bc.png)
https://cloud.githubusercontent.com/assets/2068130/12543713/91bf0626-c332-11e5-83af-ee138b5ce0bc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12543717/a1cf0b9c-c332-11e5-9a64-c51ae29a4573.png
