### ISSUE TITLE
ПДД 2016 с иллюстрациями и комментариями

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7147]
**App Name:** ПДД 2016 с иллюстрациями и комментариями
**Bundle ID:** com.emperorlab.PDD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=732804591">732804591</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pdd-2016-s-illustraciami-i/id732804591?mt=8&uo=4">https://itunes.apple.com/us/app/pdd-2016-s-illustraciami-i/id732804591?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** EMPEROR LAB LLP
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/emperor-lab-llp/id449462371?uo=4>© Emperor Lab LLP</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/ba/0e/5e/ba0e5e9c-fb52-cdb6-72ee-6804df984a06/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12605714/c869664e-c4c7-11e5-957d-0b5bd81ad6c2.png)

**Comment by dreamnet** [comment]
@Grafovich Can't read Cyrillic...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12605714/c869664e-c4c7-11e5-957d-0b5bd81ad6c2.png)
https://cloud.githubusercontent.com/assets/2068130/12605714/c869664e-c4c7-11e5-957d-0b5bd81ad6c2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12605721/d733c2e6-c4c7-11e5-9925-51bf5234d299.png
Is this OK?

**Comment by Grafovich** [comment]
@dreamnet Oh yeah, absolutely! Gorgeous! 😉
