### ISSUE TITLE
Ярмарка Мастеров (livemaster.ru)

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7148]
**App Name:** Ярмарка Мастеров (livemaster.ru)
**Bundle ID:** ru.livemaster.Livemaster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=808640777">808640777</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/armarka-masterov-livemaster.ru/id808640777?mt=8&uo=4">https://itunes.apple.com/us/app/armarka-masterov-livemaster.ru/id808640777?mt=8&uo=4</a>
**App Version:** 2.4.6
**Seller:** Sergey Cherkasov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sergey-cherkasov/id808640780?uo=4>© Sergey Cherkasov</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/ab/fc/60/abfc60af-8555-ad16-a2e7-789b6f1d5b10/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539143/216846e4-c2ec-11e5-9e3c-bba402430fa4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12539143/216846e4-c2ec-11e5-9e3c-bba402430fa4.png)
https://cloud.githubusercontent.com/assets/2068130/12539143/216846e4-c2ec-11e5-9e3c-bba402430fa4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12539147/300c7bd4-c2ec-11e5-88e6-eb4addb9870a.png

**Comment by Grafovich** [comment]
@dreamnet I am so sorry, I accidentally missed that I can request only 10 icons per week. I'll wait until next week to add more. Thank you very much for your work, I appreciate it! ;)

**Comment by dreamnet** [comment]
@Grafovich :+1:
