### ISSUE TITLE
WatchNotes - Display notes on watch face

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7149]
**App Name:** WatchNotes - Display notes on watch face
**Bundle ID:** com.MB.WatchNotes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1067458275">1067458275</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watchnotes-display-notes-on/id1067458275?mt=8&uo=4">https://itunes.apple.com/us/app/watchnotes-display-notes-on/id1067458275?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Michael Bischof
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/michael-bischof/id921500750?uo=4>© Michael Bischof</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/3a/f0/2b/3af02bdd-053f-40f6-dfec-1ac070a69d4e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12875255/55780d16-cde6-11e5-8812-f9fbf7b87762.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12875255/55780d16-cde6-11e5-8812-f9fbf7b87762.png)
https://cloud.githubusercontent.com/assets/2068130/12875255/55780d16-cde6-11e5-8812-f9fbf7b87762.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12875262/66fb81f8-cde6-11e5-9414-05ecfe556370.png
