### ISSUE TITLE
Sonic the Hedgehog

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7150]
**App Name:** Sonic the Hedgehog
**Bundle ID:** com.sega.sonic1international
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=316050001">316050001</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/sonic-the-hedgehog/id316050001?mt=8&uo=4">https://itunes.apple.com/gb/app/sonic-the-hedgehog/id316050001?mt=8&uo=4</a>
**App Version:** 2.0.8
**Seller:** Sega America
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/sega/id281966698?mt=8&uo=4>© SEGA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/9d/56/36/9d56367d-25f6-8721-31c7-be8ffb84caa2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Anuskuss** [comment]
Same icon as [US Version](https://github.com/glasklart/hd/issues/7060)

**Comment by Trubbel** [comment]
Icon by @dreamnet. (#7060)

![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12208873/e6d37d6c-b64f-11e5-88f4-4ce1e564f112.png)
https://cloud.githubusercontent.com/assets/2068130/12208873/e6d37d6c-b64f-11e5-88f4-4ce1e564f112.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12208882/fa68b1da-b64f-11e5-8660-32db89c0e973.png
