### ISSUE TITLE
Sonic the Hedgehog 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7151]
**App Name:** Sonic the Hedgehog 2
**Bundle ID:** com.sega.Sonic2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347411942">347411942</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sonic-the-hedgehog-2/id347411942?mt=8&uo=4">https://itunes.apple.com/us/app/sonic-the-hedgehog-2/id347411942?mt=8&uo=4</a>
**App Version:** 3.1.4
**Seller:** Sega America
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sega/id281966698?mt=8&uo=4>© SEGA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/81/bf/3c/81bf3c53-75a3-e36a-01fd-badc7497471e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13029328/9198c54a-d289-11e5-87e3-e1b4e744f717.png)

**Comment by Anuskuss** [comment]
Icon exists but should be updated. Also should look more like [Sonic The Hedgehog](https://github.com/glasklart/hd/issues/7060)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13029328/9198c54a-d289-11e5-87e3-e1b4e744f717.png)
https://cloud.githubusercontent.com/assets/2068130/13029328/9198c54a-d289-11e5-87e3-e1b4e744f717.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13029331/9fc18148-d289-11e5-8126-11d7fcd4cc4c.png

**Comment by Anuskuss** [comment]
Interesting... where do you got the idea?

**Comment by dreamnet** [comment]
@Anuskuss Google (search therm "Sonic coloring"). :grinning:

**Comment by Anuskuss** [comment]
@dreamnet I like the idea that the peace symbol represents that it's the second installment of Sonic the Hedgehog :+1: 
So no need to place a **2** anywhere?

**Comment by dreamnet** [comment]
@Anuskuss No, I don't think so - Look at #7060 - there is just one finger...

**Comment by Anuskuss** [comment]
:open_mouth: OMG I JUST REALIZED

**Comment by dreamnet** [comment]
We will get problems with the release of Sonic 11.... :grin:
