### ISSUE TITLE
Sonic the Hedgehog 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7152]
**App Name:** Sonic the Hedgehog 2
**Bundle ID:** com.sega.Sonic2International
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347415188">347415188</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/sonic-the-hedgehog-2/id347415188?mt=8&uo=4">https://itunes.apple.com/gb/app/sonic-the-hedgehog-2/id347415188?mt=8&uo=4</a>
**App Version:** 3.1.4
**Seller:** Sega America
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/sega/id281966698?mt=8&uo=4>© SEGA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/ca/bb/75/cabb755a-1210-383c-9073-4ce4daf76f58/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13029328/9198c54a-d289-11e5-87e3-e1b4e744f717.png)

**Comment by Anuskuss** [comment]
Same icon as [US Version](https://github.com/glasklart/hd/issues/7152)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13029328/9198c54a-d289-11e5-87e3-e1b4e744f717.png)
https://cloud.githubusercontent.com/assets/2068130/13029328/9198c54a-d289-11e5-87e3-e1b4e744f717.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13029331/9fc18148-d289-11e5-8126-11d7fcd4cc4c.png
