### ISSUE TITLE
3DMark Sling Shot Benchmark

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7153]
**App Name:** 3DMark Sling Shot Benchmark
**Bundle ID:** com.futuremark.3DMarkSlingShot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1015301759">1015301759</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/3dmark-sling-shot-benchmark/id1015301759?uo=4">https://apps.apple.com/us/app/3dmark-sling-shot-benchmark/id1015301759?uo=4</a>
**App Version:** 1.0.785
**Seller:** Underwriters Laboratories Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/underwriters-laboratories-inc/id341275025?uo=4">© Underwriters Laboratories, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/d9/8a/ab/d98aab69-bfb7-3855-0575-040d134eb135/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59973784-96e0c980-95a4-11e9-87be-3ddba9abfdee.png)

**Comment by Anuskuss** [comment]
Replace **3DMARK** with **Sling Shot**.
Font: [Eurostile Bold Extended Font](http://www21.zippyshare.com/v/Epkeftah/file.html
)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12875097/f4253e7e-cde2-11e5-9997-5110a65c5a8f.png)
https://cloud.githubusercontent.com/assets/2068130/12875097/f4253e7e-cde2-11e5-9997-5110a65c5a8f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12875098/02759e4c-cde3-11e5-85b2-94041a22eed9.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59973784-96e0c980-95a4-11e9-87be-3ddba9abfdee.png)
https://user-images.githubusercontent.com/2068130/59973784-96e0c980-95a4-11e9-87be-3ddba9abfdee.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59973790-a8c26c80-95a4-11e9-9f5b-1f866bcf62fe.png
