### ISSUE TITLE
3DMark API Overhead Feature Test

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7154]
**App Name:** 3DMark API Overhead Feature Test
**Bundle ID:** com.futuremark.3DMarkAPIOverhead
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1015302310">1015302310</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/3dmark-api-overhead-feature-test/id1015302310?uo=4">https://apps.apple.com/us/app/3dmark-api-overhead-feature-test/id1015302310?uo=4</a>
**App Version:** 1.0.147
**Seller:** Underwriters Laboratories Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/underwriters-laboratories-inc/id341275025?uo=4">© Underwriters Laboratories, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple69/v4/91/6a/22/916a224a-5e18-b3c8-2ec0-a7693add87aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59973838-f4751600-95a4-11e9-9fc0-d271080a95e1.png)

**Comment by Anuskuss** [comment]
Replace **3DMARK** with **API Overhead**.
Font: [Eurostile Bold Extended Font](http://www21.zippyshare.com/v/Epkeftah/file.html
)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12875080/8e0e293e-cde2-11e5-89b0-215c30e34af1.png)
https://cloud.githubusercontent.com/assets/2068130/12875080/8e0e293e-cde2-11e5-89b0-215c30e34af1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12875082/9ee26a5e-cde2-11e5-8ca8-2b23acb14cc4.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59973838-f4751600-95a4-11e9-9fc0-d271080a95e1.png)
https://user-images.githubusercontent.com/2068130/59973838-f4751600-95a4-11e9-9fc0-d271080a95e1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59973846-048cf580-95a5-11e9-8ed7-5471fa60bbe6.png
