### ISSUE TITLE
Feature - Rewards from your favorite brands

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7155]
**App Name:** Feature - Rewards from your favorite brands
**Bundle ID:** co.featureapp.featureapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035429587">1035429587</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/feature-rewards-from-your/id1035429587?mt=8&uo=4">https://itunes.apple.com/us/app/feature-rewards-from-your/id1035429587?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** 2401260 Ontario Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/feature/id1035429586?uo=4>© Feature</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/d5/3f/90/d53f9073-b8dc-b200-e034-01cbcac17bd4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12875000/c9ca2696-cde0-11e5-9c1c-fd356a7c1bd0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12875000/c9ca2696-cde0-11e5-9c1c-fd356a7c1bd0.png)
https://cloud.githubusercontent.com/assets/2068130/12875000/c9ca2696-cde0-11e5-9c1c-fd356a7c1bd0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12875002/d7019baa-cde0-11e5-972a-15a0142ec1e6.png
