### ISSUE TITLE
Acapella from PicPlayPost

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7156]
**App Name:** Acapella from PicPlayPost
**Bundle ID:** co.mixcord.acapella
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=924635678">924635678</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/acapella-from-picplaypost/id924635678?mt=8&uo=4">https://itunes.apple.com/us/app/acapella-from-picplaypost/id924635678?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Mixcord Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mixcord-inc./id336456537?uo=4>© Mixcord Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/71/88/06/718806c9-32d3-e6bc-f16f-26b7c077f968/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874971/0e305fcc-cde0-11e5-8a6a-1d391b5f3cd2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874971/0e305fcc-cde0-11e5-8a6a-1d391b5f3cd2.png)
https://cloud.githubusercontent.com/assets/2068130/12874971/0e305fcc-cde0-11e5-8a6a-1d391b5f3cd2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12874974/1b818534-cde0-11e5-85a6-43aab1c69003.png
