### ISSUE TITLE
YouNow: Live Stream Video Chat

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7157]
**App Name:** YouNow: Live Stream Video Chat
**Bundle ID:** com.younow.YouNowMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=471347413">471347413</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/younow-live-stream-video-chat/id471347413?mt=8&uo=4">https://itunes.apple.com/us/app/younow-live-stream-video-chat/id471347413?mt=8&uo=4</a>
**App Version:** 10.3.0
**Seller:** YouNow, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/younow-inc./id471347416?uo=4>© YouNow, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/f1/ff/4e/f1ff4e65-533b-d7c5-1f08-2a3e918b127f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12797158/25083b8a-ca88-11e5-85df-f81c4e771a90.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12797158/25083b8a-ca88-11e5-85df-f81c4e771a90.png)
--- ---
Sourcce:
https://cloud.githubusercontent.com/assets/3090247/12797159/2515cf5c-ca88-11e5-905b-133966250a3c.png
