### ISSUE TITLE
Bouncy Pong ●

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7159]
**App Name:** Bouncy Pong ●
**Bundle ID:** com.bulkypix.bouncypong
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1062825160">1062825160</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bouncy-pong/id1062825160?mt=8&uo=4">https://itunes.apple.com/us/app/bouncy-pong/id1062825160?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** BULKYPIX
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bulkypix/id304521749?uo=4>© Bulkypix</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple2/v4/6f/2a/a5/6f2aa521-b158-3109-5be1-60e75e4359fd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13029892/cc78937a-d298-11e5-8c61-e701f48cfdce.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12869228/8801dd2a-cd19-11e5-8f86-306d50487c9e.png)
https://cloud.githubusercontent.com/assets/10730122/12869228/8801dd2a-cd19-11e5-8f86-306d50487c9e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12869227/88015c92-cd19-11e5-81b4-ed8710108888.png

**Comment by Anuskuss** [comment]
@Trubbel Without the background?

**Comment by dreamnet** [comment]
Alternate:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12875141/e724eb42-cde3-11e5-8a44-92c35081fe69.png)
https://cloud.githubusercontent.com/assets/2068130/12875141/e724eb42-cde3-11e5-8a44-92c35081fe69.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12875145/f87fd99c-cde3-11e5-9565-18ca4dc7bc35.png

**Comment by Trubbel** [comment]
@dreamnet Yeah I like yours better. Thoughts @Anuskuss?

**Comment by ivanov007** [comment]
![](httppreview.dreamnet.atimage=https://cloud.githubusercontent.com/assets/3090247/12929203/1fb5f22c-cf37-11e5-8a80-636386a9df15.png)
https://cloud.githubusercontent.com/assets/3090247/12929203/1fb5f22c-cf37-11e5-8a80-636386a9df15.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/12929204/1fb8a030-cf37-11e5-9cc5-9df34d3da947.png

**Comment by dreamnet** [comment]
@Anuskuss Your choice!

**Comment by Anuskuss** [comment]
Sorry for not responding :disappointed:
How about only the ball with it's "flying curve"?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13029892/cc78937a-d298-11e5-8c61-e701f48cfdce.png)
https://cloud.githubusercontent.com/assets/2068130/13029892/cc78937a-d298-11e5-8c61-e701f48cfdce.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13029893/da586696-d298-11e5-94cf-b04f66bd82f9.png

**Comment by Anuskuss** [comment]
@dreamnet Weeeeell, I don't know. What version do you personally like the most (asking you too @Trubbel?)

**Comment by dreamnet** [comment]
I prefer the second one.

**Comment by Anuskuss** [comment]
I downloaded both versions and I tend to like the 4th a bit more. But it's your work, you're the designer :sunglasses:

**Comment by dreamnet** [comment]
@Anuskuss That's OK, I take number 4.

**Comment by Anuskuss** [comment]
![img_8375](https://cloud.githubusercontent.com/assets/7157389/13030222/16b13604-d2a3-11e5-9ea5-ffa536662946.PNG)
