### ISSUE TITLE
Foursquare - Find Places to Eat, Drink, and Visit

### ISSUE THREAD

**Issue by allliee** [glasklart/hd#716]
**App Name:** Foursquare - Find Places to Eat, Drink, and Visit
**Bundle ID:** com.naveenium.foursquare
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306934924">306934924</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/foursquare-find-places-to/id306934924?mt=8&uo=4">https://itunes.apple.com/us/app/foursquare-find-places-to/id306934924?mt=8&uo=4</a>
**App Version:** 9.30
**Seller:** Foursquare Labs, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/foursquare-labs-inc./id293619800?mt=8&uo=4>© Foursquare Labs, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/e3/dd/41/e3dd41a8-701d-dcd0-2e4f-78eb36f082af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18105136/99ca9380-6efe-11e6-91bd-d637eba33544.png)

**Comment by alpcinar** [comment]
I think centered version would look better.

**Comment by dreamnet** [comment]
The original icon is also not centered... hm.

**Comment by ivanov007** [comment]
agree, no change needed

**Comment by alpcinar** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13483942/18027051/6487a41e-6c61-11e6-8165-842e3377ec19.png)
https://cloud.githubusercontent.com/assets/13483942/18027051/6487a41e-6c61-11e6-8165-842e3377ec19.png
Source:
https://cloud.githubusercontent.com/assets/13483942/18027054/7945608a-6c61-11e6-9d2d-716447555515.png

**Comment by Trubbel** [comment]
@dreamnet Looks like they updated their artwork, it's now centered.

**Comment by dreamnet** [comment]
@Trubbel Ah, thanks for the info! In this cas @alpcinar 's icon is fine, I'm just cleaning it up a bit.
