### ISSUE TITLE
Color Switch

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7160]
**App Name:** Color Switch
**Bundle ID:** com.fortafygames.colorswitch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1053533457">1053533457</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/color-switch/id1053533457?mt=8&uo=4">https://itunes.apple.com/us/app/color-switch/id1053533457?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Samuel Ratumaitavuki
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/samuel-ratumaitavuki/id1053533456?uo=4>© Samuel Ratumaitavuki</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/ec/e8/43/ece843a1-0df6-2b22-ad51-532b88924488/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12863713/2298a3a4-cc7b-11e5-8f61-9c0f1599faee.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12863713/2298a3a4-cc7b-11e5-8f61-9c0f1599faee.png)
https://cloud.githubusercontent.com/assets/10730122/12863713/2298a3a4-cc7b-11e5-8f61-9c0f1599faee.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12863712/2294f862-cc7b-11e5-85a5-4b5fc181ea83.png

**Comment by dreamnet** [comment]
@Trubbel :+1:
