### ISSUE TITLE
Fun Run 2 - Multiplayer Race

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7161]
**App Name:** Fun Run 2 - Multiplayer Race
**Bundle ID:** com.dirtybit.funrun2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=920482331">920482331</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fun-run-2-multiplayer-race/id920482331?mt=8&uo=4">https://itunes.apple.com/us/app/fun-run-2-multiplayer-race/id920482331?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** DIRTYBIT DA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dirtybit/id484858667?uo=4>© dirtyBit</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/eb/a6/27/eba627d0-aca5-3919-205e-2ff7325d3f14/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374917/3c75f86c-dd92-11e5-99dd-25a4fe7045c5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374917/3c75f86c-dd92-11e5-99dd-25a4fe7045c5.png)
https://cloud.githubusercontent.com/assets/2068130/13374917/3c75f86c-dd92-11e5-99dd-25a4fe7045c5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13374919/4a339176-dd92-11e5-821c-7142f639fc72.png

**Comment by Anuskuss** [comment]
I think we should include that question mark box so that it looks more like [Fun Run (1)](https://github.com/glasklart/hd/issues/667)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13486533/27fbb9de-e112-11e5-9563-5ea522e6f58a.png)
https://cloud.githubusercontent.com/assets/2068130/13486533/27fbb9de-e112-11e5-9563-5ea522e6f58a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13486540/3e78db9c-e112-11e5-8af7-c1a76f31a522.png

**Comment by Anuskuss** [comment]
@dreamnet Sorry for the mood swings but I think the first one looked definitely better.
