### ISSUE TITLE
Yandex.Navigator

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7162]
**App Name:** Yandex.Navigator
**Bundle ID:** ru.yandex.mobile.navigator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=474500851">474500851</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex.navigator/id474500851?mt=8&uo=4">https://itunes.apple.com/us/app/yandex.navigator/id474500851?mt=8&uo=4</a>
**App Version:** 1.72
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/8e/29/75/8e297536-aec9-e922-9667-d5c23cb819f4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874439/3d3037d6-cdd4-11e5-8bbf-851c3e3ea077.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874439/3d3037d6-cdd4-11e5-8bbf-851c3e3ea077.png)
https://cloud.githubusercontent.com/assets/2068130/12874439/3d3037d6-cdd4-11e5-8bbf-851c3e3ea077.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12874446/4d2ddc74-cdd4-11e5-9716-32c6892258c8.png
