### ISSUE TITLE
Yandex.Translate - free offline dictionary and translator across 60+ languages

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7163]
**App Name:** Yandex.Translate - free offline dictionary and translator across 60+ languages
**Bundle ID:** ru.yandex.mobile.translate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=584291439">584291439</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex.translate-free-offline/id584291439?mt=8&uo=4">https://itunes.apple.com/us/app/yandex.translate-free-offline/id584291439?mt=8&uo=4</a>
**App Version:** 2.81
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/c1/b5/72/c1b572c1-9823-2041-98cf-371f0bf4765d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874357/d8b2973c-cdd2-11e5-9b24-5e2a09f96d76.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874357/d8b2973c-cdd2-11e5-9b24-5e2a09f96d76.png)
https://cloud.githubusercontent.com/assets/2068130/12874357/d8b2973c-cdd2-11e5-9b24-5e2a09f96d76.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12874365/eaa437c0-cdd2-11e5-8eae-eb9869c1f5c2.png
