### ISSUE TITLE
Яндекс.Транспорт — автобусы, трамваи, троллейбусы и маршрутки на карте онлайн. Маршруты и остановки общественного транспорта.

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7164]
**App Name:** Яндекс.Транспорт — автобусы, трамваи, троллейбусы и маршрутки на карте онлайн. Маршруты и остановки общественного транспорта.
**Bundle ID:** ru.yandex.mobile.transport
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=826358136">826358136</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/andeks.transport-avtobusy/id826358136?mt=8&uo=4">https://itunes.apple.com/us/app/andeks.transport-avtobusy/id826358136?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple2/v4/70/2c/1d/702c1d57-b8a3-1e39-fc22-276593dc1b8a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874310/088a1418-cdd2-11e5-8489-1552ebc2864d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874310/088a1418-cdd2-11e5-8489-1552ebc2864d.png)
https://cloud.githubusercontent.com/assets/2068130/12874310/088a1418-cdd2-11e5-8489-1552ebc2864d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12874315/16bd05d6-cdd2-11e5-9271-eb0020c0b2a1.png
