### ISSUE TITLE
Yandex.City - best places nearby, recommendations, and reviews for Moscow, St. Petersburg, Minsk and other cities

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7165]
**App Name:** Yandex.City - best places nearby, recommendations, and reviews for Moscow, St. Petersburg, Minsk and other cities
**Bundle ID:** ru.yandex.mobile.city
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=881459877">881459877</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex.city-best-places-nearby/id881459877?mt=8&uo=4">https://itunes.apple.com/us/app/yandex.city-best-places-nearby/id881459877?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/8d/8f/b0/8d8fb062-a386-f3ff-77f1-22e3fcf5853a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874276/fe429ff8-cdd0-11e5-9d8f-05b0be3b3a5f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874276/fe429ff8-cdd0-11e5-9d8f-05b0be3b3a5f.png)
https://cloud.githubusercontent.com/assets/2068130/12874276/fe429ff8-cdd0-11e5-9d8f-05b0be3b3a5f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12874279/0d7431e4-cdd1-11e5-9b40-5ebd87642d8a.png
