### ISSUE TITLE
Яндекс.Маркет: сравните цены

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7166]
**App Name:** Яндекс.Маркет: сравните цены
**Bundle ID:** ru.yandex.ymarket
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=425354015">425354015</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%82-%D1%81%D1%80%D0%B0%D0%B2%D0%BD%D0%B8%D1%82%D0%B5-%D1%86%D0%B5%D0%BD%D1%8B/id425354015?uo=4">https://apps.apple.com/us/app/%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%82-%D1%81%D1%80%D0%B0%D0%B2%D0%BD%D0%B8%D1%82%D0%B5-%D1%86%D0%B5%D0%BD%D1%8B/id425354015?uo=4</a>
**App Version:** 6.1
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yandex-llc/id308094652?uo=4">© Yandex LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/92/a6/38/92a63838-1d2c-e628-ff94-ea3b66c43379/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973956-626e0d00-95a6-11e9-8631-6fd936fa9ca3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871917/1dbf308a-cd90-11e5-8ad1-9c5af7e0d0d2.png)
https://cloud.githubusercontent.com/assets/2068130/12871917/1dbf308a-cd90-11e5-8ad1-9c5af7e0d0d2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12871918/2ac02cb2-cd90-11e5-9236-663aa659fc86.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59973956-626e0d00-95a6-11e9-8631-6fd936fa9ca3.png)
https://user-images.githubusercontent.com/20930745/59973956-626e0d00-95a6-11e9-8631-6fd936fa9ca3.png

Source:
![einkaufswagen](https://user-images.githubusercontent.com/20930745/59973957-639f3a00-95a6-11e9-882c-da40d3eac8c4.png)
