### ISSUE TITLE
Yandex.Jobs – search for jobs without a resume

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7167]
**App Name:** Yandex.Jobs – search for jobs without a resume
**Bundle ID:** ru.yandex.mobile.rabota
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=961663271">961663271</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex.jobs-search-for-jobs/id961663271?mt=8&uo=4">https://itunes.apple.com/us/app/yandex.jobs-search-for-jobs/id961663271?mt=8&uo=4</a>
**App Version:** 1.04
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/19/8a/1e/198a1e2a-8da5-c4e0-057d-8be668a7df68/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871899/9173aca0-cd8f-11e5-83b9-eaacb6b64337.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871899/9173aca0-cd8f-11e5-83b9-eaacb6b64337.png)
https://cloud.githubusercontent.com/assets/2068130/12871899/9173aca0-cd8f-11e5-83b9-eaacb6b64337.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12871901/9efaa4dc-cd8f-11e5-9982-822ca9c908ca.png
