### ISSUE TITLE
Yandex.Music for iPhone

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7168]
**App Name:** Yandex.Music for iPhone
**Bundle ID:** ru.yandex.mobile.music
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520797969">520797969</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex.music-for-iphone/id520797969?mt=8&uo=4">https://itunes.apple.com/us/app/yandex.music-for-iphone/id520797969?mt=8&uo=4</a>
**App Version:** 3.6
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/08/52/e6/0852e639-2dce-1957-04bc-d251d03af8ab/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871420/25ae95f8-cd7a-11e5-8c32-1324c7aff455.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871420/25ae95f8-cd7a-11e5-8c32-1324c7aff455.png)
https://cloud.githubusercontent.com/assets/2068130/12871420/25ae95f8-cd7a-11e5-8c32-1324c7aff455.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12871421/36b84d3a-cd7a-11e5-8ed7-93aefea4ff51.png
