### ISSUE TITLE
Яндекс.Штрафы — поиск и уплата штрафов ГИБДД

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7169]
**App Name:** Яндекс.Штрафы — поиск и уплата штрафов ГИБДД
**Bundle ID:** ru.yandex.mobile.fines
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=887514299">887514299</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/andeks.strafy-poisk-i-uplata/id887514299?mt=8&uo=4">https://itunes.apple.com/us/app/andeks.strafy-poisk-i-uplata/id887514299?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/71/37/8d/71378d51-c44a-013e-8361-0bbe446b0d8f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871385/fbaeb06e-cd77-11e5-8d61-e12d865b68e1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871385/fbaeb06e-cd77-11e5-8d61-e12d865b68e1.png)
https://cloud.githubusercontent.com/assets/2068130/12871385/fbaeb06e-cd77-11e5-8d61-e12d865b68e1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12871386/09afd4d6-cd78-11e5-86d1-b194884537c2.png
