### ISSUE TITLE
MeetMe - Chat and Meet New People

### ISSUE THREAD

**Issue by tmhstoner** [glasklart/hd#717]
**App Name:** MeetMe - Chat and Meet New People
**Bundle ID:** com.myYearbook.MyYearbook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=372648912">372648912</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/meetme-chat-meet-new-people/id372648912?mt=8&uo=4">https://itunes.apple.com/us/app/meetme-chat-meet-new-people/id372648912?mt=8&uo=4</a>
**App Version:** 11.5.0
**Seller:** MeetMe, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/meetme-inc./id372648915?uo=4>© MeetMe, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/24/76/0b/24760b6d-2a09-d840-394b-7eb83757189b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19527417/3d5a42ac-9628-11e6-9753-c6655c3d827b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19527417/3d5a42ac-9628-11e6-9753-c6655c3d827b.png)
https://cloud.githubusercontent.com/assets/20930745/19527417/3d5a42ac-9628-11e6-9753-c6655c3d827b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19527449/56813de4-9628-11e6-9ca3-b112aff456c6.png
