### ISSUE TITLE
Yandex.News

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7170]
**App Name:** Yandex.News
**Bundle ID:** ru.yandex.mobile.news
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=891626263">891626263</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex.news/id891626263?mt=8&uo=4">https://itunes.apple.com/us/app/yandex.news/id891626263?mt=8&uo=4</a>
**App Version:** 1.30
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/1c/f2/c4/1cf2c4d3-afd3-e03f-f49e-198466f093c6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12763540/3c1e4190-c9f5-11e5-9376-56208ef97945.png)

**Comment by Trubbel** [comment]
@dreamnet, Not sure how I should go with this..

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12763540/3c1e4190-c9f5-11e5-9376-56208ef97945.png)
https://cloud.githubusercontent.com/assets/10730122/12763540/3c1e4190-c9f5-11e5-9376-56208ef97945.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12763541/3c20b236-c9f5-11e5-8194-de358487b95b.png

--
 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12763613/9eeef0a8-c9f5-11e5-87a6-837a9255a1f6.png)
https://cloud.githubusercontent.com/assets/10730122/12763613/9eeef0a8-c9f5-11e5-87a6-837a9255a1f6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12763612/9ee84aa0-c9f5-11e5-8646-fa9d1c183ecd.png

**Comment by dreamnet** [comment]
Hmmm, another option:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12865359/d3a29e74-cca9-11e5-823a-4c3da990c8aa.png)
https://cloud.githubusercontent.com/assets/2068130/12865359/d3a29e74-cca9-11e5-823a-4c3da990c8aa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12865362/e1dce0bc-cca9-11e5-92e7-cf7e8bd8e0ba.png

**Comment by Grafovich** [comment]
Guys, i liked the first icon (https://cloud.githubusercontent.com/assets/10730122/12763540/3c1e4190-c9f5-11e5-9376-56208ef97945.png), by the way. I Think this arrow style could be used in all icons by "Yandex" ? I do not insist, all on your taste ;)

**Comment by dreamnet** [comment]
@Grafovich Jep, OK, perfect!
