### ISSUE TITLE
Yandex.Disk

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7171]
**App Name:** Yandex.Disk
**Bundle ID:** ru.yandex.disk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=553266487">553266487</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex.disk/id553266487?mt=8&uo=4">https://itunes.apple.com/us/app/yandex.disk/id553266487?mt=8&uo=4</a>
**App Version:** 1.70
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/25/fb/4f/25fb4f8b-2e71-4c13-b3e2-8be298a2c6e1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871368/1f338d76-cd77-11e5-973f-eed866fcb5cb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871368/1f338d76-cd77-11e5-973f-eed866fcb5cb.png)
https://cloud.githubusercontent.com/assets/2068130/12871368/1f338d76-cd77-11e5-973f-eed866fcb5cb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12871369/2ebabb98-cd77-11e5-80d7-826da0616921.png
