### ISSUE TITLE
Basket Fall - Endless Dunking Sim

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7172]
**App Name:** Basket Fall - Basketball Dunking Sim
**Bundle ID:** com.kumobius.basketfall
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1036088441">1036088441</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/basket-fall-basketball-dunking/id1036088441?mt=8&uo=4">https://itunes.apple.com/us/app/basket-fall-basketball-dunking/id1036088441?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Kumobius Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kumobius/id449069247?uo=4>© Kumobius</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/1a/7c/a5/1a7ca5a9-cc68-6e2d-35be-dee99eea6534/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809474/84ba4e5e-827c-11e6-8243-fb221f86c726.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12871313/3385a816-cd74-11e5-9ca0-c28143a9ab15.png)
https://cloud.githubusercontent.com/assets/2068130/12871313/3385a816-cd74-11e5-9ca0-c28143a9ab15.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12871316/427255ae-cd74-11e5-891e-327928309b99.png

**Comment by Anuskuss** [comment]
Needs update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809474/84ba4e5e-827c-11e6-8243-fb221f86c726.png)
https://cloud.githubusercontent.com/assets/20930745/18809474/84ba4e5e-827c-11e6-8243-fb221f86c726.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18809480/96ba8538-827c-11e6-9fc7-ee58417e2a75.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Great one!
