### ISSUE TITLE
About Love, Hate and the other ones

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7173]
**App Name:** About Love, Hate and the other ones
**Bundle ID:** com.blackpants.LoveAndHateHD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=558459510">558459510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/about-love-hate-other-ones/id558459510?mt=8&uo=4">https://itunes.apple.com/us/app/about-love-hate-other-ones/id558459510?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** Black Pants Studio GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/black-pants-studio-gmbh/id558459513?uo=4>© Black Pants Studio GmbH</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/70/a5/82/70a58228-4bd2-9179-a943-433575850d16/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12865527/e1587886-ccae-11e5-9caf-ba16d36cc795.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12865527/e1587886-ccae-11e5-9caf-ba16d36cc795.png)
https://cloud.githubusercontent.com/assets/2068130/12865527/e1587886-ccae-11e5-9caf-ba16d36cc795.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12865529/ef86884e-ccae-11e5-8d65-50af8af45a04.png
