### ISSUE TITLE
Parallels

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7174]
**App Name:** Parallels
**Bundle ID:** com.appsolutegames.parallels
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1043607606">1043607606</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parallels/id1043607606?mt=8&uo=4">https://itunes.apple.com/us/app/parallels/id1043607606?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Appsolute Games LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appsolute-games-llc/id602062365?uo=4>© Appsolute Games LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/75/fe/1d/75fe1d0d-b0c8-37e6-5c07-44703a0355f9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874660/02925600-cdd8-11e5-881e-e5a39cded1f9.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12863571/13439e66-cc78-11e5-93cd-dbdb3f37a65c.png)
https://cloud.githubusercontent.com/assets/10730122/12863571/13439e66-cc78-11e5-93cd-dbdb3f37a65c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12863570/13429eda-cc78-11e5-990c-3ac0109a2ca7.png

**Comment by Anuskuss** [comment]
@Trubbel I would say without the seperator in the bottom part...

**Comment by Trubbel** [comment]
@Anuskuss The separator is there to make the "3D" effect the original icon have.
Personally I would stay with the separator...

`Original`
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12863571/13439e66-cc78-11e5-93cd-dbdb3f37a65c.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12868628/81ad9a90-cd0a-11e5-906a-5a9d025c223d.png)
<kbd>[source](https://cloud.githubusercontent.com/assets/10730122/12868694/f612b59a-cd0b-11e5-808b-b9afb22efe5f.png)</kbd>

...or it could be thinner,
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12868668/689f1afa-cd0b-11e5-8b39-85aa22c7cb64.png)
<kbd>[source](https://cloud.githubusercontent.com/assets/10730122/12868675/ce082968-cd0b-11e5-873a-1984cfbbb133.png)</kbd>

@dreamnet What do you think?

**Comment by Anuskuss** [comment]
@Trubbel Tbh I like the second version more but it's up to you.

**Comment by dreamnet** [comment]
The first one was just perfect for me - for a compromise we can use the last one with the thinner line... ?

**Comment by dreamnet** [comment]
OK, I decide an I take the last one:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874660/02925600-cdd8-11e5-881e-e5a39cded1f9.png)
https://cloud.githubusercontent.com/assets/2068130/12874660/02925600-cdd8-11e5-881e-e5a39cded1f9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12874662/111b56f4-cdd8-11e5-9632-5024d617a0e4.png
