### ISSUE TITLE
Piano Tiles 2 (Don't Tap The White Tile 2)

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7175]
**App Name:** Piano Tiles 2 (Don't Tap The White Tile 2)
**Bundle ID:** com.cmplay.tiles2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1027688889">1027688889</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/piano-tiles-2-dont-tap-white/id1027688889?mt=8&uo=4">https://itunes.apple.com/us/app/piano-tiles-2-dont-tap-white/id1027688889?mt=8&uo=4</a>
**App Version:** 1.1.9
**Seller:** cheetah technology corporation limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cheetah-technology-corporation/id949821679?uo=4>© Cheetah Technology Corporation Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/42/c6/f5/42c6f556-3c33-40ae-de1f-e0e2f089b55a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12856333/b30f7962-cc44-11e5-8c05-0de3483690dd.png)

**Comment by Anuskuss** [comment]
#4299 with a *2* in the top left corner.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12831798/89088a4a-cb96-11e5-9a11-c9571688b2ec.png)
https://cloud.githubusercontent.com/assets/2068130/12831798/89088a4a-cb96-11e5-9a11-c9571688b2ec.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12831811/99123d14-cb96-11e5-9f83-9423930ff2d1.png

**Comment by Anuskuss** [comment]
Can I have to **2** without the "gloss"?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12856333/b30f7962-cc44-11e5-8c05-0de3483690dd.png)
https://cloud.githubusercontent.com/assets/2068130/12856333/b30f7962-cc44-11e5-8c05-0de3483690dd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12856347/c7c3ff5e-cc44-11e5-950d-afebb786d70a.png

**Comment by Anuskuss** [comment]
Thank you :+1

**Comment by Anuskuss** [comment]
Thank you :+1:

**Comment by dreamnet** [comment]
@Anuskuss :+1:
