### ISSUE TITLE
Rolling Sky

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7176]
**App Name:** Rolling Sky
**Bundle ID:** com.turbochilli.rollingsky
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1036661603">1036661603</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rolling-sky/id1036661603?mt=8&uo=4">https://itunes.apple.com/us/app/rolling-sky/id1036661603?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Turbo Chilli Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/turbo-chilli-pty-ltd/id574324031?uo=4>© Turbo Chilli Pty Ltd</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple2/v4/3c/6f/f6/3c6ff67d-8a26-76ff-83f2-b12bf37cf9ee/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721751/bea3f1ba-e830-11e5-93ed-90bab262f8bc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874837/8be243d0-cddc-11e5-8ac1-e5b12b12e661.png)
https://cloud.githubusercontent.com/assets/2068130/12874837/8be243d0-cddc-11e5-8ac1-e5b12b12e661.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12874839/9a52bdd2-cddc-11e5-9b2a-7d447060f8c0.png

**Comment by Anuskuss** [comment]
@dreamnet Could you remove the background (the lines)?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721751/bea3f1ba-e830-11e5-93ed-90bab262f8bc.png)
https://cloud.githubusercontent.com/assets/2068130/13721751/bea3f1ba-e830-11e5-93ed-90bab262f8bc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13721752/ce31c0b2-e830-11e5-8479-52163b77277a.png
...now it looks like a crystal ball...

**Comment by Anuskuss** [comment]
Small update.

**Comment by dreamnet** [comment]
@Anuskuss The update looks bad and is not worth to do.
