### ISSUE TITLE
Sky Chasers

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7177]
**App Name:** Sky Chasers
**Bundle ID:** com.luckykat.skychasers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1038866266">1038866266</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sky-chasers/id1038866266?mt=8&uo=4">https://itunes.apple.com/us/app/sky-chasers/id1038866266?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Lucky Kat Studios
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lucky-kat-studios/id498980984?uo=4>© Lucky Kat Studios</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/30/72/b5/3072b5e4-0daf-2cdb-3b4d-9f2e1279f18f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721877/144f5b7e-e834-11e5-8e65-250b41ddd140.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13552964/754b7406-e377-11e5-9b50-62cc9a000aa7.png)
https://cloud.githubusercontent.com/assets/2068130/13552964/754b7406-e377-11e5-9b50-62cc9a000aa7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13552966/8391f7ba-e377-11e5-9bae-898a8e4e7f0a.png

**Comment by Anuskuss** [comment]
@dreamnet Could you remove the white (acceleration) lines?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721877/144f5b7e-e834-11e5-8e65-250b41ddd140.png)
https://cloud.githubusercontent.com/assets/2068130/13721877/144f5b7e-e834-11e5-8e65-250b41ddd140.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13721881/2391f614-e834-11e5-9579-4a62e9aa16af.png

**Comment by Anuskuss** [comment]
@dreamnet Perfect :+1:
