### ISSUE TITLE
Bike Baron

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7178]
**App Name:** Bike Baron
**Bundle ID:** ms.games.bikebaron
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=433847884">433847884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bike-baron/id433847884?mt=8&uo=4">https://itunes.apple.com/us/app/bike-baron/id433847884?mt=8&uo=4</a>
**App Version:** 3.9.1
**Seller:** Mountain Sheep
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mountain-sheep/id392924730?uo=4">© Mountain Sheep</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/78/ae/26/78ae26c2-b6e1-99ae-3bc5-913d5e1e72ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563706/f4977f68-ce84-11e6-89dd-78ba26c0ce9f.png)

**Comment by Anuskuss** [comment]
Icon exists, but needs an update.

**Comment by Anuskuss** [comment]
Another update.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563706/f4977f68-ce84-11e6-89dd-78ba26c0ce9f.png)
https://cloud.githubusercontent.com/assets/2068130/21563706/f4977f68-ce84-11e6-89dd-78ba26c0ce9f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21563717/0553a0e8-ce85-11e6-9008-69bd0b37f7f3.png
