### ISSUE TITLE
News Pro: Your Work News Brief

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7179]
**App Name:** News Pro: Your Work News Brief
**Bundle ID:** com.microsoft.bing.newspro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1071935844">1071935844</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/news-pro-your-work-news-brief/id1071935844?mt=8&uo=4">https://itunes.apple.com/us/app/news-pro-your-work-news-brief/id1071935844?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/c5/85/65/c58565c0-1696-d971-4344-aacf06f286d4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12734904/cf65513a-c943-11e5-9f09-8cf9ecd67ae7.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12734904/cf65513a-c943-11e5-9f09-8cf9ecd67ae7.png)
https://cloud.githubusercontent.com/assets/10730122/12734904/cf65513a-c943-11e5-9f09-8cf9ecd67ae7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12734905/cf7ef946-c943-11e5-8a7a-0d27ac4819a1.png
