### ISSUE TITLE
Pocket Frogs

### ISSUE THREAD

**Issue by allliee** [glasklart/hd#718]
**App Name:** Pocket Frogs
**Bundle ID:** com.eeenmachine.pocketfrogs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386644958">386644958</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-frogs/id386644958?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-frogs/id386644958?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** NimbleBit LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nimblebit-llc/id285808572?mt=8&uo=4">© NimbleBit LLC</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/37/ea/24/37ea2429-d77e-e011-1b4b-7a40d565f691/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39944641-b44a2404-5567-11e8-8ab7-b123cff070f9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39944641-b44a2404-5567-11e8-8ab7-b123cff070f9.png)
https://user-images.githubusercontent.com/2068130/39944641-b44a2404-5567-11e8-8ab7-b123cff070f9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39944668-c4cacb1c-5567-11e8-93b9-9323d5623bbe.png
