### ISSUE TITLE
iSeries - Track all your favorite TV shows, sync with trakt!

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7182]
**App Name:** iSeries - Track all your favorite TV shows, sync with trakt!
**Bundle ID:** com.AnyTap.TraktTV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=957601977">957601977</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iseries-track-all-your-favorite/id957601977?mt=8&uo=4">https://itunes.apple.com/us/app/iseries-track-all-your-favorite/id957601977?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Paul Chavarria Podoliako
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/paul-j-chavarria-podoliako/id494746953?uo=4>© Paul J Chavarria Podoliako</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/00/c8/32/00c832f3-4bb8-c3c9-c2da-27802c20f628/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12756662/07facd18-c9d5-11e5-9e8b-d97c7cd74965.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12756662/07facd18-c9d5-11e5-9e8b-d97c7cd74965.png)
https://cloud.githubusercontent.com/assets/10730122/12756662/07facd18-c9d5-11e5-9e8b-d97c7cd74965.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12756663/07fcbaf6-c9d5-11e5-8bb3-c15b05c18c2b.png
