### ISSUE TITLE
iShows TV - The definitive TV Show Tracker powered by Trakt.tv

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7183]
**App Name:** iShows TV - The definitive TV Show Tracker powered by Trakt.tv
**Bundle ID:** com.ishows.ishows2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=992387872">992387872</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ishows-tv-definitive-tv-show/id992387872?mt=8&uo=4">https://itunes.apple.com/us/app/ishows-tv-definitive-tv-show/id992387872?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Luis Recuenco
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/luis-recuenco/id666021155?uo=4>© Luis Recuenco</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/9e/91/3e/9e913e83-e4bf-4d3f-27de-dd3c3b4bcff8/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12756993/6c75fe88-c9d6-11e5-8526-7d5e17eacb44.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12756978/59875844-c9d6-11e5-8232-646fe31e93f4.png)
https://cloud.githubusercontent.com/assets/10730122/12756978/59875844-c9d6-11e5-8232-646fe31e93f4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12756977/5984f626-c9d6-11e5-8a1f-cf191192886c.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12756993/6c75fe88-c9d6-11e5-8526-7d5e17eacb44.png)
https://cloud.githubusercontent.com/assets/10730122/12756993/6c75fe88-c9d6-11e5-8526-7d5e17eacb44.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12756992/6c743d78-c9d6-11e5-96a0-43c9160e098f.png
