### ISSUE TITLE
Neko Atsume: Kitty Collector

### ISSUE THREAD

**Issue by nitsujb** [glasklart/hd#7184]
**App Name:** Neko Atsume: Kitty Collector
**Bundle ID:** jp.co.hit-point.nekoatsume
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923917775">923917775</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/neko-atsume-kitty-collector/id923917775?mt=8&uo=4">https://itunes.apple.com/us/app/neko-atsume-kitty-collector/id923917775?mt=8&uo=4</a>
**App Version:** 1.5.5
**Seller:** Hit-Point Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hit-point-co.-ltd./id495637387?uo=4>© Hit-Point Co., Ltd.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/c1/5b/00/c15b0041-763e-1361-cce4-399608061713/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12865599/f76fe40e-ccb0-11e5-889f-b1d65abb896f.png)

**Comment by nitsujb** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/17033627/12807503/5dcd3dc6-cac4-11e5-95c5-45987c9bfe00.png)
https://cloud.githubusercontent.com/assets/17033627/12807503/5dcd3dc6-cac4-11e5-95c5-45987c9bfe00.png
Source:
https://cloud.githubusercontent.com/assets/17033627/12807430/fbe820da-cac3-11e5-9664-296f2b83637c.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12865599/f76fe40e-ccb0-11e5-889f-b1d65abb896f.png)
https://cloud.githubusercontent.com/assets/2068130/12865599/f76fe40e-ccb0-11e5-889f-b1d65abb896f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12865602/0585ab00-ccb1-11e5-9acd-141a439ee712.png
