### ISSUE TITLE
Norwegian Travel Assistant

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7189]
**App Name:** Norwegian Travel Assistant
**Bundle ID:** com.norwegian.travelassistant
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=534487502">534487502</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/norwegian-travel-assistant/id534487502?mt=8&uo=4">https://itunes.apple.com/us/app/norwegian-travel-assistant/id534487502?mt=8&uo=4</a>
**App Version:** 2.0.4
**Seller:** Norwegian Air Shuttle ASA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/norwegian-air-shuttle-asa/id522331965?uo=4>© Norwegian Air Shuttle ASA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/4a/3e/51/4a3e5122-1747-8569-5098-aeac42d38b73/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12857212/280558c8-cc49-11e5-84b0-04f09b355ed7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12857212/280558c8-cc49-11e5-84b0-04f09b355ed7.png)
https://cloud.githubusercontent.com/assets/2068130/12857212/280558c8-cc49-11e5-84b0-04f09b355ed7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12857225/36e06a04-cc49-11e5-8714-6c4bb47b3217.png
