### ISSUE TITLE
Scribblenauts Remix

### ISSUE THREAD

**Issue by allliee** [glasklart/hd#719]
**App Name:** Scribblenauts Remix
**Bundle ID:** com.wb.Scribblenauts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444844790">444844790</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scribblenauts-remix/id444844790?mt=8&uo=4">https://itunes.apple.com/us/app/scribblenauts-remix/id444844790?mt=8&uo=4</a>
**App Version:** 7.3
**Seller:** Warner Bros. Entertainment
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/warner-bros/id298372283?uo=4">© Warner Bros.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/85/1c/94/851c9495-13e8-13a4-a1d0-985728a2684b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39466939-b804b062-4d2b-11e8-8d1c-051e53383fc6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39466939-b804b062-4d2b-11e8-8d1c-051e53383fc6.png)
https://user-images.githubusercontent.com/2068130/39466939-b804b062-4d2b-11e8-8d1c-051e53383fc6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39466950-c822b804-4d2b-11e8-8743-e150fa7d0fbe.png
