### ISSUE TITLE
HANGMAN - The Classic Word Game

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7191]
**App Name:** HANGMAN - The Classic Word Game
**Bundle ID:** com.apprope.a47
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=718951908">718951908</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hangman-the-classic-word-game/id718951908?mt=8&uo=4">https://itunes.apple.com/us/app/hangman-the-classic-word-game/id718951908?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** Apprope AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apprope/id509306834?uo=4>© Apprope</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/9b/0e/ee/9b0eee2c-a97d-70f5-e4b3-afa30d40f97b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12830648/aeed1358-cb90-11e5-9df9-025a5554371e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12830648/aeed1358-cb90-11e5-9df9-025a5554371e.png)
https://cloud.githubusercontent.com/assets/2068130/12830648/aeed1358-cb90-11e5-9df9-025a5554371e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12830660/bf4b5b42-cb90-11e5-8b8f-9308c51ac381.png
