### ISSUE TITLE
Res i STHLM: SL journey planner

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7192]
**App Name:** Res i STHLM: SL journey planner
**Bundle ID:** com.yeah.isl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=296171628">296171628</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/res-i-sthlm-sl-journey-planner/id296171628?mt=8&uo=4">https://itunes.apple.com/us/app/res-i-sthlm-sl-journey-planner/id296171628?mt=8&uo=4</a>
**App Version:** 3.0.9
**Seller:** Nobina AB (Publ)
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nobina/id973474051?uo=4>© Nobina</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/36/a8/0f/36a80f29-96a8-5a9e-b670-a18a9462eb45/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12803755/4802bd12-caed-11e5-8241-a779403ede96.png)

**Comment by Trubbel** [comment]
Icon exists, however it needs to be updated.

**Comment by Trubbel** [comment]
Best I could do,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12803755/4802bd12-caed-11e5-8241-a779403ede96.png)
https://cloud.githubusercontent.com/assets/10730122/12803755/4802bd12-caed-11e5-8241-a779403ede96.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12803756/48040eec-caed-11e5-94f8-abe0f455c978.png

**Comment by dreamnet** [comment]
@Trubbel Looks fine to me. :+1:
