### ISSUE TITLE
N26 – The Mobile Bank

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7197]
**App Name:** N26 – The Mobile Bank
**Bundle ID:** de.no26.Number26
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=956857223">956857223</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/n26-the-mobile-bank/id956857223?mt=8&uo=4">https://itunes.apple.com/us/app/n26-the-mobile-bank/id956857223?mt=8&uo=4</a>
**App Version:** 3.15
**Seller:** N26 GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/n26-gmbh/id897464435?uo=4">© N26 GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/7b/4d/be/7b4dbe26-b45e-b3fe-db22-db4b6c6067e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45929340-930a1300-bf50-11e8-8a69-ffea58eb6f36.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12831250/913c60ea-cb93-11e5-8f84-02f53f34e907.png)
https://cloud.githubusercontent.com/assets/2068130/12831250/913c60ea-cb93-11e5-8f84-02f53f34e907.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12831262/a030f958-cb93-11e5-9f2e-1f0e5b05a3bb.png

**Comment by Anuskuss** [comment]
I like this icon, but it just has changed.

**Comment by ivanov007** [comment]
@Anuskuss right, I think we can keep it, I just updated everything else

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45929340-930a1300-bf50-11e8-8a69-ffea58eb6f36.png)
https://user-images.githubusercontent.com/2068130/45929340-930a1300-bf50-11e8-8a69-ffea58eb6f36.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45929346-a1582f00-bf50-11e8-9003-fa5afd387e7c.png
