### ISSUE TITLE
Tomb Raider II

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7198]
**App Name:** Tomb Raider II
**Bundle ID:** com.squareenix.tombraider2classic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=871235562">871235562</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tomb-raider-ii/id871235562?mt=8&uo=4">https://itunes.apple.com/us/app/tomb-raider-ii/id871235562?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** SQUARE ENIX Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/9b/f5/79/9bf579ab-cda3-8a1f-9843-847119ed6a60/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13378800/624616a0-de12-11e5-8f18-7830a2ea76f5.png)

**Comment by dreamnet** [comment]
Still some parts missing, but slowly it's getting a shape:
![tomb_raider_ii-01](https://cloud.githubusercontent.com/assets/2068130/13378532/ec1b8670-de09-11e5-915f-71b26ff3d9a0.png)

**Comment by dreamnet** [comment]
OK, finished:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13378800/624616a0-de12-11e5-8f18-7830a2ea76f5.png)
https://cloud.githubusercontent.com/assets/2068130/13378800/624616a0-de12-11e5-8f18-7830a2ea76f5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13378808/7a2cf20c-de12-11e5-9ae0-90053edfbd68.png

**Comment by Trubbel** [comment]
@dreamnet Wow! :+1:

**Comment by dreamnet** [comment]
@Trubbel THX!
