### ISSUE TITLE
Bio Inc. Platinum - Biomedical Plague

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7199]
**App Name:** Bio Inc. Platinum - Biomedical Plague
**Bundle ID:** com.dryginstudios.bioinc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=890479211">890479211</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bio-inc.-platinum-biomedical/id890479211?mt=8&uo=4">https://itunes.apple.com/us/app/bio-inc.-platinum-biomedical/id890479211?mt=8&uo=4</a>
**App Version:** 2.01
**Seller:** 9262-9518 QUEBEC INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/drygin-studios/id530299099?uo=4>© DryGin Studios</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/cf/a9/c8/cfa9c86d-1c22-066a-4047-0e2764d6563d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7191246/6f42b8ca-e48c-11e4-8bd8-102336ba7ac6.png)

**Comment by Trubbel** [comment]
Same icon as <kbd>[#5584](https://github.com/glasklart/hd/issues/5584)</kbd>,

![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7191246/6f42b8ca-e48c-11e4-8bd8-102336ba7ac6.png)
https://cloud.githubusercontent.com/assets/2068130/7191246/6f42b8ca-e48c-11e4-8bd8-102336ba7ac6.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7191253/7f2be7b6-e48c-11e4-8d2f-de5cd007f263.png

**Comment by dreamnet** [comment]
@Trubbel Great one! :+1:
