### ISSUE TITLE
PINK Nation

### ISSUE THREAD

**Issue by allliee** [glasklart/hd#720]
**App Name:** PINK Nation
**Bundle ID:** com.victoriassecret.pinknation
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=463630399">463630399</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pink-nation/id463630399?mt=8&uo=4">https://itunes.apple.com/us/app/pink-nation/id463630399?mt=8&uo=4</a>
**App Version:** 4.10.2
**Seller:** Victoria's Secret Stores Brand Management, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/victorias-secret-pink/id463630402?uo=4>© Victoria's Secret PINK</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/e3/14/72/e3147249-8fb9-702b-1fb9-a7c6f5facb20/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19344492/b4650ea6-913a-11e6-9a67-ff974dda4cbe.png)

**Comment by ashley108** [comment]
can you please update this please ID463630399

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19344492/b4650ea6-913a-11e6-9a67-ff974dda4cbe.png)
https://cloud.githubusercontent.com/assets/20930745/19344492/b4650ea6-913a-11e6-9a67-ff974dda4cbe.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19344514/c25a765e-913a-11e6-8f43-d16de1e75ed2.png
