### ISSUE TITLE
QR Code Reader and Scanner

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7200]
**App Name:** QR Code Reader and Scanner
**Bundle ID:** com.biggu.qrcodereader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388175979">388175979</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qr-code-reader-and-scanner/id388175979?mt=8&uo=4">https://itunes.apple.com/us/app/qr-code-reader-and-scanner/id388175979?mt=8&uo=4</a>
**App Version:** 3.3.5.0
**Seller:** ShopSavvy, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shopsavvy-inc./id327762559?uo=4>© ShopSavvy, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/e6/63/d6/e663d696-0946-9cd7-248e-7e1ae9643e55/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874717/87039510-cdd9-11e5-93ee-73917384bf64.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12869371/8e5d0182-cd1d-11e5-9d76-f3768d18295d.png)
https://cloud.githubusercontent.com/assets/10730122/12869371/8e5d0182-cd1d-11e5-9d76-f3768d18295d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12869370/8e5cf75a-cd1d-11e5-8667-fd6680db3652.png

**Comment by dreamnet** [comment]
I think this would be better without the border....

**Comment by dreamnet** [comment]
@Trubbel What about this: ?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12874717/87039510-cdd9-11e5-93ee-73917384bf64.png)
https://cloud.githubusercontent.com/assets/2068130/12874717/87039510-cdd9-11e5-93ee-73917384bf64.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12874718/95de7dac-cdd9-11e5-9d50-2d2e24eb3e49.png

**Comment by Trubbel** [comment]
@dreamnet Oh yeah, that looks so much better! :+1:
