### ISSUE TITLE
Smart Search & Web Browser – fast and easy to use app for surfing Web

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7201]
**App Name:** Smart Search & Web Browser – fast and easy to use app for surfing Web
**Bundle ID:** ru.reactivephone.MobileSearch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555717978">555717978</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smart-search-web-browser-fast/id555717978?mt=8&uo=4">https://itunes.apple.com/us/app/smart-search-web-browser-fast/id555717978?mt=8&uo=4</a>
**App Version:** 1.9.3
**Seller:** Reactive Phone Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/reactive-phone-ltd./id407204784?uo=4>© Reactive Phone Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/47/ac/5e/47ac5e36-aced-78f6-62b8-ea06fbe08b1f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12949150/27b8dde6-cfcc-11e5-90bc-876d1a0ab877.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12949148/27872260-cfcc-11e5-9e14-320538d2d29b.png)
https://cloud.githubusercontent.com/assets/3090247/12949148/27872260-cfcc-11e5-9e14-320538d2d29b.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12949150/27b8dde6-cfcc-11e5-90bc-876d1a0ab877.png)
https://cloud.githubusercontent.com/assets/3090247/12949150/27b8dde6-cfcc-11e5-90bc-876d1a0ab877.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/12949151/27bddd0a-cfcc-11e5-8096-b2bdff1ad8cc.png
https://cloud.githubusercontent.com/assets/3090247/12949149/27b83a3a-cfcc-11e5-802c-89f46d904ae6.png
