### ISSUE TITLE
Now Tapped

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7202]
**App Name:** Now Tapped
**Bundle ID:** com.nowtapped.user
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=886986437">886986437</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/now-tapped/id886986437?mt=8&uo=4">https://itunes.apple.com/us/app/now-tapped/id886986437?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Angus Bremner
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/angus-bremner/id856686434?uo=4>© Angus Bremner</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/95/da/ee/95daeec8-64cc-fa77-a8f0-c0c26f1ff072/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12931811/346960ec-cf45-11e5-9018-a386b4e11f43.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12931785/0bdd2a3c-cf45-11e5-865c-5eab20b8138a.png)
https://cloud.githubusercontent.com/assets/3090247/12931785/0bdd2a3c-cf45-11e5-865c-5eab20b8138a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/12931786/0be03b82-cf45-11e5-9e0c-ebfbc419c841.png
