### ISSUE TITLE
2ch browser

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7203]
**App Name:** 2ch browser
**Bundle ID:** com.8of.dvach-browser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=929022093">929022093</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/2ch-browser/id929022093?mt=8&uo=4">https://itunes.apple.com/us/app/2ch-browser/id929022093?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Andrey Konstantinov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/andrey-konstantinov/id926035381?uo=4>© Andrey Konstantinov</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/1e/85/06/1e850694-67ce-609e-de6b-dc5c0a2afdb4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12948904/a2dae426-cfca-11e5-804e-c2a630dfe01f.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12948904/a2dae426-cfca-11e5-804e-c2a630dfe01f.png)
https://cloud.githubusercontent.com/assets/3090247/12948904/a2dae426-cfca-11e5-804e-c2a630dfe01f.png
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12948900/a241b6de-cfca-11e5-8750-76f52055adfa.png)
https://cloud.githubusercontent.com/assets/3090247/12948900/a241b6de-cfca-11e5-8750-76f52055adfa.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/12948901/a24393d2-cfca-11e5-84cf-6fc679159fac.png
https://cloud.githubusercontent.com/assets/3090247/12948902/a249eda4-cfca-11e5-93aa-c2684507821b.png
