### ISSUE TITLE
Yandex.Taxi

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7204]
**App Name:** Yandex.Taxi
**Bundle ID:** ru.yandex.ytaxi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=472650686">472650686</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex.taxi/id472650686?mt=8&uo=4">https://itunes.apple.com/us/app/yandex.taxi/id472650686?mt=8&uo=4</a>
**App Version:** 3.41
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/77/4a/d2/774ad23c-0ca2-183e-3ada-79e09fc96dab/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12989138/3a22184c-d104-11e5-9d6d-b04bb694d110.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12989138/3a22184c-d104-11e5-9d6d-b04bb694d110.png)
https://cloud.githubusercontent.com/assets/2068130/12989138/3a22184c-d104-11e5-9d6d-b04bb694d110.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12989148/48ba2c96-d104-11e5-82e8-02372cc16bb4.png
