### ISSUE TITLE
Яндекс.Парковки

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7205]
**App Name:** Яндекс.Парковки
**Bundle ID:** ru.yandex.mobile.parkings
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=897018695">897018695</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/andeks.parkovki/id897018695?mt=8&uo=4">https://itunes.apple.com/us/app/andeks.parkovki/id897018695?mt=8&uo=4</a>
**App Version:** 1.48
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/c2/20/59/c2205940-3636-d930-4ff9-6938584c9e40/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12988952/616923a6-d103-11e5-8cbd-79ee7539cd2c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12988952/616923a6-d103-11e5-8cbd-79ee7539cd2c.png)
https://cloud.githubusercontent.com/assets/2068130/12988952/616923a6-d103-11e5-8cbd-79ee7539cd2c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12988971/6fcd7258-d103-11e5-9ca4-f514cfdfbd3c.png
