### ISSUE TITLE
MoneyWiz 2 - Personal Finance (Money Management, Bills, Budgets Planning, Spending/Expense Tracking, Checkbook Register)

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7206]
**App Name:** MoneyWiz 2 - Personal Finance (Money Management, Bills, Budgets Planning, Spending/Expense Tracking, Checkbook Register)
**Bundle ID:** com.moneywiz.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=936248215">936248215</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moneywiz-2-personal-finance/id936248215?mt=8&uo=4">https://itunes.apple.com/us/app/moneywiz-2-personal-finance/id936248215?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** SilverWiz Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/silverwiz-ltd/id380335247?uo=4>© SilverWiz Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/d7/34/c3/d734c37d-1f18-f378-993f-5bee12a02bc1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13026495/8b24eb86-d229-11e5-92ad-b258214aef98.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13026495/8b24eb86-d229-11e5-92ad-b258214aef98.png)
https://cloud.githubusercontent.com/assets/2068130/13026495/8b24eb86-d229-11e5-92ad-b258214aef98.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13026499/9c2ea03e-d229-11e5-9a3a-047a0dc85c4e.png
