### ISSUE TITLE
Сбербанк Онлайн

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7207]
**App Name:** Сбербанк Онлайн
**Bundle ID:** ru.sberbank.onlineiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492224193">492224193</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sberbank-onlajn/id492224193?mt=8&uo=4">https://itunes.apple.com/us/app/sberbank-onlajn/id492224193?mt=8&uo=4</a>
**App Version:** 7.0.1
**Seller:** Sberbank of Russia
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sberbank-rossii/id434391126?uo=4>© Сбербанк России</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/7a/28/6d/7a286d33-17c6-5092-4dff-926ce9678ca7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12987918/924b3860-d0fe-11e5-84b7-0155a0f1209e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12987918/924b3860-d0fe-11e5-84b7-0155a0f1209e.png)
https://cloud.githubusercontent.com/assets/2068130/12987918/924b3860-d0fe-11e5-84b7-0155a0f1209e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12987926/a0fe0d6a-d0fe-11e5-9b08-aa88a7a06b7b.png
