### ISSUE TITLE
Кукуруза

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7208]
**App Name:** Кукуруза
**Bundle ID:** ru.euroset.kykyryza
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=738918402">738918402</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kukuruza/id738918402?mt=8&uo=4">https://itunes.apple.com/us/app/kukuruza/id738918402?mt=8&uo=4</a>
**App Version:** 1.16
**Seller:** LLC Euroset-Retail
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/evroset/id738918405?uo=4>© Евросеть</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/94/3b/35/943b35f5-f80f-c459-016c-0d08b7c13dbd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12987793/04359cbe-d0fe-11e5-9f4f-33c5b87d15ae.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12987793/04359cbe-d0fe-11e5-9f4f-33c5b87d15ae.png)
https://cloud.githubusercontent.com/assets/2068130/12987793/04359cbe-d0fe-11e5-9f4f-33c5b87d15ae.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12987806/11b7481a-d0fe-11e5-868d-a6ce4e928d2f.png
