### ISSUE TITLE
Yandex.Money

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7209]
**App Name:** Yandex.Money
**Bundle ID:** ru.yandex.mobile.money
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=468731698">468731698</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex.money/id468731698?mt=8&uo=4">https://itunes.apple.com/us/app/yandex.money/id468731698?mt=8&uo=4</a>
**App Version:** 4.3.0
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4>© Yandex LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/17/3d/9c/173d9c83-9995-2fd3-5955-0d6ae25b7ba3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12988796/cdc131ca-d102-11e5-80d2-d59c3c5008d3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12988796/cdc131ca-d102-11e5-80d2-d59c3c5008d3.png)
https://cloud.githubusercontent.com/assets/2068130/12988796/cdc131ca-d102-11e5-80d2-d59c3c5008d3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12988819/e04f559c-d102-11e5-9891-32c8d51daf9e.png
