### ISSUE TITLE
Private Photo Vault - Keep Pictures+Videos Safe

### ISSUE THREAD

**Issue by allliee** [glasklart/hd#721]
**App Name:** Private Photo Vault - Keep Pictures+Videos Safe
**Bundle ID:** com.enchantedcloud.photovault
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417571834">417571834</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/private-photo-vault-keep-pictures+videos/id417571834?mt=8&uo=4">https://itunes.apple.com/us/app/private-photo-vault-keep-pictures+videos/id417571834?mt=8&uo=4</a>
**App Version:** 8.5
**Seller:** Legendary Software Labs LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/legendary-software-labs-llc/id456797862?uo=4>© Legendary Software Labs LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/32/30/e7/3230e7bf-cddc-2c10-c72a-63042c1cbf10/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19716817/082bbe18-9b5e-11e6-9778-5097ea8a7bfc.png)

**Comment by quantum8** [comment]
This icon needs an update please.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19716817/082bbe18-9b5e-11e6-9778-5097ea8a7bfc.png)
https://cloud.githubusercontent.com/assets/2068130/19716817/082bbe18-9b5e-11e6-9778-5097ea8a7bfc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19716831/17007ce4-9b5e-11e6-85f3-2301fccaefa9.png
