### ISSUE TITLE
Телеканал НТВ: новости, видео, передачи, сериалы и кинофильмы

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7210]
**App Name:** Телеканал НТВ: новости, видео, передачи, сериалы и кинофильмы
**Bundle ID:** com.ntv.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=720725187">720725187</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/telekanal-ntv-novosti-video/id720725187?mt=8&uo=4">https://itunes.apple.com/us/app/telekanal-ntv-novosti-video/id720725187?mt=8&uo=4</a>
**App Version:** 3.5.1
**Seller:** Telekompaniya NTV AO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/telekompaniya-ntv-ao/id720725190?uo=4>© Telekompaniya NTV AO</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/21/89/a6/2189a617-64e4-3dda-c20e-ce68954a25b5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12987704/8cdac87e-d0fd-11e5-8c32-5d7c0ef1ad05.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12987704/8cdac87e-d0fd-11e5-8c32-5d7c0ef1ad05.png)
https://cloud.githubusercontent.com/assets/2068130/12987704/8cdac87e-d0fd-11e5-8c32-5d7c0ef1ad05.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12987719/9b1b90f8-d0fd-11e5-9b9e-63be33456a0a.png
