### ISSUE TITLE
Яблык

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7211]
**App Name:** Яблык
**Bundle ID:** ru.lwts.yablyk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=964232441">964232441</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ablyk/id964232441?mt=8&uo=4">https://itunes.apple.com/us/app/ablyk/id964232441?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Dima Mikhnevich
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dima-mikhnevich/id964232440?uo=4>© Dima Mikhnevich</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/6b/6f/48/6b6f481d-e190-da80-fa75-6c6389eb1bd3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/12987596/09cb3112-d0fd-11e5-8de2-f712d2d21fa9.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12950124/3b6b024c-cfd1-11e5-8843-8d73cedafdc7.png)
https://cloud.githubusercontent.com/assets/3090247/12950124/3b6b024c-cfd1-11e5-8843-8d73cedafdc7.png
--- ---
Sopurce:
https://cloud.githubusercontent.com/assets/3090247/12950125/3b70ed1a-cfd1-11e5-9e62-6d99326a8464.png
