### ISSUE TITLE
Politrussia.com - общественно-политический интернет журнал

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7212]
**App Name:** Politrussia.com - общественно-политический интернет журнал
**Bundle ID:** com.politrussia.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=974508698">974508698</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/politrussia.com-obsestvenno/id974508698?mt=8&uo=4">https://itunes.apple.com/us/app/politrussia.com-obsestvenno/id974508698?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** PolitRussia OOO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/politrussia-llc/id974508697?uo=4>© PolitRussia, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/c4/7d/d3/c47dd328-f7d6-ea9a-237f-95d6adf19d95/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12987409/43a12190-d0fc-11e5-95c1-d22573cbc089.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/12949993/8a62c4c6-cfd0-11e5-9347-1ae4621ae2ab.png)
https://cloud.githubusercontent.com/assets/3090247/12949993/8a62c4c6-cfd0-11e5-9347-1ae4621ae2ab.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/12949994/8a65324c-cfd0-11e5-9ee7-e2cedaafafa9.png

**Comment by dreamnet** [comment]
Uh, on second thought, I think it's better to do this icon in original size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/12987409/43a12190-d0fc-11e5-95c1-d22573cbc089.png)
https://cloud.githubusercontent.com/assets/2068130/12987409/43a12190-d0fc-11e5-95c1-d22573cbc089.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/12987426/5203e20e-d0fc-11e5-9c25-896de3301aa4.png
