### ISSUE TITLE
These Lumps - Adventure Time

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7213]
**App Name:** These Lumps - Adventure Time
**Bundle ID:** com.turner.theselumps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=874328329">874328329</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/these-lumps-adventure-time/id874328329?mt=8&uo=4">https://itunes.apple.com/us/app/these-lumps-adventure-time/id874328329?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Turner Broadcasting System, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cartoon-network/id300726272?mt=8&uo=4>© Cartoon Network</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/25/75/51/25755187-bddb-6e3f-c058-8018c8d6ecb5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12998379/82093dd6-d143-11e5-8004-a699d476a3eb.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12998379/82093dd6-d143-11e5-8004-a699d476a3eb.png)
https://cloud.githubusercontent.com/assets/10730122/12998379/82093dd6-d143-11e5-8004-a699d476a3eb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12998380/820978dc-d143-11e5-8698-8c08bd1275f6.png

**Comment by Anuskuss** [comment]
@Trubbel I would say without the border but it's up to you ;)
