### ISSUE TITLE
Quartz • News in a whole new way

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7214]
**App Name:** Quartz • News in a whole new way
**Bundle ID:** com.qzmedia.app.jasper
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1076683233">1076683233</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quartz-news-in-a-whole-new-way/id1076683233?mt=8&uo=4">https://itunes.apple.com/us/app/quartz-news-in-a-whole-new-way/id1076683233?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Quartz Media LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/quartz/id1076683232?uo=4>© Quartz</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/8e/0a/3e/8e0a3ee2-ce66-4eec-6e3c-bcc095047663/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13025480/b7025598-d208-11e5-8cf9-a4763480a973.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13025480/b7025598-d208-11e5-8cf9-a4763480a973.png)
https://cloud.githubusercontent.com/assets/10730122/13025480/b7025598-d208-11e5-8cf9-a4763480a973.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13025479/b7012f92-d208-11e5-87a3-b718fff7f6c2.png
