### ISSUE TITLE
Ticketmaster Suomi

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7215]
**App Name:** Ticketmaster Suomi
**Bundle ID:** fi.lippupalvelu.ticketmaster-suomi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1002572423">1002572423</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fi/app/ticketmaster-suomi/id1002572423?mt=8&uo=4">https://itunes.apple.com/fi/app/ticketmaster-suomi/id1002572423?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** TICKETMASTER U K LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/fi/developer/ticketmaster-international/id1002567081?uo=4>© Ticketmaster International</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/69/a9/d4/69a9d427-63ac-4f49-9cae-6d7cf4286c4e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13025419/39dd1662-d207-11e5-9bbc-7104c684a47a.png)

**Comment by Trubbel** [comment]
Same icon as #6090,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13025419/39dd1662-d207-11e5-9bbc-7104c684a47a.png)
https://cloud.githubusercontent.com/assets/10730122/13025419/39dd1662-d207-11e5-9bbc-7104c684a47a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13025418/39c485fc-d207-11e5-87e8-fced283239a3.png
