### ISSUE TITLE
Log-Log

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7216]
**App Name:** Log-Log
**Bundle ID:** com.SLooneyDev.iOS.LogLog
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1027636372">1027636372</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/log-log/id1027636372?mt=8&uo=4">https://itunes.apple.com/us/app/log-log/id1027636372?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Stephen Looney
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stephen-looney/id1027636371?uo=4>© Stephen Looney</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/5c/6a/d7/5c6ad746-9c57-feb3-5485-80401bba2ec3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13026422/c303b8d6-d227-11e5-935b-703fd6770d02.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13026422/c303b8d6-d227-11e5-935b-703fd6770d02.png)
https://cloud.githubusercontent.com/assets/2068130/13026422/c303b8d6-d227-11e5-935b-703fd6770d02.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13026423/d065c3fc-d227-11e5-8c4b-345ecb7bd69c.png
