### ISSUE TITLE
Little Alchemist

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7219]
**App Name:** Little Alchemist
**Bundle ID:** com.chinzilla.littleAlchemist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586470098">586470098</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/little-alchemist/id586470098?mt=8&uo=4">https://itunes.apple.com/us/app/little-alchemist/id586470098?mt=8&uo=4</a>
**App Version:** 1.33.41
**Seller:** Kongregate, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kongregate/id491569846?uo=4>© Kongregate</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/f4/9f/35/f49f35d2-719d-298b-bfb7-f8fb1cf18c27/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13035112/fa4db640-d347-11e5-9c30-e8817ccf1d8e.png)

**Comment by Trubbel** [comment]
Best I could do,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13030542/ffd7183e-d2ae-11e5-92c3-f126b14063bc.png)
https://cloud.githubusercontent.com/assets/10730122/13030542/ffd7183e-d2ae-11e5-92c3-f126b14063bc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13030541/ffbdbb3c-d2ae-11e5-85db-262c239ef0d0.png

**Comment by Anuskuss** [comment]
@Trubbel Make the character solo (aka remove the border). Anyway, good job :+1:

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13035112/fa4db640-d347-11e5-9c30-e8817ccf1d8e.png)
https://cloud.githubusercontent.com/assets/2068130/13035112/fa4db640-d347-11e5-9c30-e8817ccf1d8e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13035115/092b5b0e-d348-11e5-97cb-ca93beebafa7.png
Credits are going to @Trubbel.

**Comment by Anuskuss** [comment]
Beautiful :+1: 
You are the kings!
