### ISSUE TITLE
Pinterest

### ISSUE THREAD

**Issue by allliee** [glasklart/hd#722]
**App Name:** Pinterest
**Bundle ID:** pinterest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=429047995">429047995</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pinterest/id429047995?mt=8&uo=4">https://itunes.apple.com/us/app/pinterest/id429047995?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** Pinterest, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/pinterest-inc./id328135727?uo=4>© Pinterest, Inc.</a>
**Supported Devices:** iPhone4S, iPadMini, iPhone6Plus, iPadMini4G, iPodTouchFifthGen, iPadThirdGen4G, iPadFourthGen4G, iPad2Wifi, iPad23G, iPadFourthGen, iPhone4, iPhone6, iPhone5s, iPhone5, iPhone5c, iPadThirdGen
**Original Artwork:**
<img src="http://a624.phobos.apple.com/us/r30/Purple5/v4/1a/6f/72/1a6f72a0-1456-377e-21ef-f73c49d3b43f/mzl.iqtbhefe.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6995433/1ec0d6f4-db16-11e4-8954-992ce25dfc69.png)

**Comment by zmathiasz** [comment]
@dreamnet 

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6995433/1ec0d6f4-db16-11e4-8954-992ce25dfc69.png)
https://cloud.githubusercontent.com/assets/10950389/6995433/1ec0d6f4-db16-11e4-8954-992ce25dfc69.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6995435/3b0b314c-db16-11e4-93e8-2b6af571afa5.png
