### ISSUE TITLE
Red Onion - Tor-powered web browser for anonymous browsing and darknet

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7220]
**App Name:** Red Onion - Tor-powered web browser for anonymous browsing and darknet
**Bundle ID:** com.gplexdb.azulbrowse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=829739720">829739720</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/red-onion-tor-powered-web/id829739720?mt=8&uo=4">https://itunes.apple.com/us/app/red-onion-tor-powered-web/id829739720?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Omar Mody
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/omar-mody/id297279263?uo=4>© Omar Mody</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/93/24/40/93244001-c8f8-5556-d53c-db6df9b48854/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13037415/c10e71a6-d380-11e5-95bc-06cec941a599.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13035027/9f14d65c-d345-11e5-842d-010564be3ea7.png)
https://cloud.githubusercontent.com/assets/2068130/13035027/9f14d65c-d345-11e5-842d-010564be3ea7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13035029/ae86de28-d345-11e5-88e0-b5539a0a3959.png

**Comment by Anuskuss** [comment]
I think you should only include the onion.

And make it look like the official tor logo:
![](http://thatstheish.com/wp-content/uploads/2015/05/tor-logo1-300x336.jpg)

**Comment by Trubbel** [comment]
We usually make icon as close to the original artwork as possible, however there can be some exceptions. I see nothing wrong with the original artwork though.

Anyway, here's the alternate,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13037415/c10e71a6-d380-11e5-95bc-06cec941a599.png)
https://cloud.githubusercontent.com/assets/10730122/13037415/c10e71a6-d380-11e5-95bc-06cec941a599.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13037414/c10e3f88-d380-11e5-90cc-53c5824e261d.png

**Comment by Anuskuss** [comment]
I think the original one looks kinda bulky, but it's your choice.

**Comment by Trubbel** [comment]
I'll leave the choice to @dreamnet. :sweat_smile:

**Comment by dreamnet** [comment]
OK...
