### ISSUE TITLE
Verbrechen - echte Polizeifälle aus Deiner Umgebung

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7221]
**App Name:** Verbrechen - echte Polizeifälle aus Deiner Umgebung
**Bundle ID:** de.berlitec.crimeradar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=413246702">413246702</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/verbrechen-echte-polizeifalle/id413246702?mt=8&uo=4">https://itunes.apple.com/us/app/verbrechen-echte-polizeifalle/id413246702?mt=8&uo=4</a>
**App Version:** 2.0.13
**Seller:** BerliTec GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/berlitec-gmbh/id370384917?uo=4>© BerliTec GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/2a/d8/16/2ad81633-e39f-5d3f-3548-2da65e84ddb5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721653/848bddce-e82d-11e5-9f13-9592104a9fb2.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13031080/590d79e2-d2bf-11e5-8262-fae5be5902f1.png)
https://cloud.githubusercontent.com/assets/10730122/13031080/590d79e2-d2bf-11e5-8262-fae5be5902f1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13031081/5910668e-d2bf-11e5-89ce-1e90f1960d78.png

**Comment by Anuskuss** [comment]
@Trubbel Could you remove the border of the pin/pointer?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721653/848bddce-e82d-11e5-9f13-9592104a9fb2.png)
https://cloud.githubusercontent.com/assets/2068130/13721653/848bddce-e82d-11e5-9f13-9592104a9fb2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13721655/9406c836-e82d-11e5-9453-b54ea97b7eff.png

**Comment by Anuskuss** [comment]
@dreamnet Thanks :+1:
