### ISSUE TITLE
Halo: Spartan Strike

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7222]
**App Name:** Halo: Spartan Strike
**Bundle ID:** com.microsoft.spartanstrike
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=940249281">940249281</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/halo-spartan-strike/id940249281?mt=8&uo=4">https://itunes.apple.com/us/app/halo-spartan-strike/id940249281?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/25/a2/49/25a249b9-2085-a3b4-2de4-7c214c9a343c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13031047/2c4ca41a-d2be-11e5-8b60-e48f8dd942db.png)

**Comment by Anuskuss** [comment]
Without the **HALO** so it looks more like #7223

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13031047/2c4ca41a-d2be-11e5-8b60-e48f8dd942db.png)
https://cloud.githubusercontent.com/assets/10730122/13031047/2c4ca41a-d2be-11e5-8b60-e48f8dd942db.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13031046/2c490742-d2be-11e5-8b41-8fc0e77d97b9.png
