### ISSUE TITLE
Halo: Spartan Assault

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7223]
**App Name:** Halo: Spartan Assault
**Bundle ID:** com.microsoft.spartanassault
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=895875773">895875773</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/halo-spartan-assault/id895875773?mt=8&uo=4">https://itunes.apple.com/us/app/halo-spartan-assault/id895875773?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/12/0d/aa/120daae8-ca72-5c2a-3bb1-eb56286f87da/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13031053/73623d24-d2be-11e5-9f67-58bd5cce641d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13031053/73623d24-d2be-11e5-9f67-58bd5cce641d.png)
https://cloud.githubusercontent.com/assets/10730122/13031053/73623d24-d2be-11e5-9f67-58bd5cce641d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13031054/73630196-d2be-11e5-8f93-e698bc69840b.png
