### ISSUE TITLE
C More

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7228]
**App Name:** C More
**Bundle ID:** se.cmore.CMore2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=970506336">970506336</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/se/app/c-more/id970506336?uo=4">https://apps.apple.com/se/app/c-more/id970506336?uo=4</a>
**App Version:** 3.36
**Seller:** C More Entertainment AB
**Developer:** <a target="_blank" href="https://apps.apple.com/se/developer/c-more-entertainment-ab/id368589902?uo=4">© C More Entertainment AB</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/ee/c5/8e/eec58e23-909b-444d-f753-42bc9038ec85/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380153-10fbcd00-9a41-11e9-8693-38d7f47a04c1.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13073855/48f00028-d4a1-11e5-9999-7d31e5840333.png)
https://cloud.githubusercontent.com/assets/10730122/13073855/48f00028-d4a1-11e5-9999-7d31e5840333.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13073854/48ef9f2a-d4a1-11e5-9557-4f557b7940e1.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380153-10fbcd00-9a41-11e9-8693-38d7f47a04c1.png)
https://user-images.githubusercontent.com/20930745/60380153-10fbcd00-9a41-11e9-8693-38d7f47a04c1.png

Source:
https://user-images.githubusercontent.com/20930745/60380154-12c59080-9a41-11e9-8549-65f928bbb222.png
