### ISSUE TITLE
MSQRD — Live Filters for Video and Photo Selfies

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7231]
**App Name:** MSQRD — Live Filters for Video and Photo Selfies
**Bundle ID:** me.msqrd.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1065249424">1065249424</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/msqrd-live-filters-for-video/id1065249424?mt=8&uo=4">https://itunes.apple.com/us/app/msqrd-live-filters-for-video/id1065249424?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Masquerade Technologies, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/masquerade-technologies-inc/id1082640171?uo=4>© Masquerade Technologies, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/4e/9c/01/4e9c0116-b2ab-0c66-98af-ac23f0929d65/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100261/868a3512-d53b-11e5-8d23-3563c6c575c2.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100261/868a3512-d53b-11e5-8d23-3563c6c575c2.png)
https://cloud.githubusercontent.com/assets/10730122/13100261/868a3512-d53b-11e5-8d23-3563c6c575c2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100262/86a25b2e-d53b-11e5-8734-b0aa3b0f4365.png)
