### ISSUE TITLE
5SecondsApp - Animated GIF Create & Search

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7232]
**App Name:** 5SecondsApp - Animated GIF Create & Search
**Bundle ID:** com.ericmarschner.5s
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555789561">555789561</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/5secondsapp-animated-gif-create/id555789561?mt=8&uo=4">https://itunes.apple.com/us/app/5secondsapp-animated-gif-create/id555789561?mt=8&uo=4</a>
**App Version:** 1.9.0
**Seller:** Eric Marschner
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eric-marschner/id319178159?uo=4>© Eric Marschner</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/14/b4/5c/14b45c8c-e7e0-6517-bed5-249c0497d5cb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100273/a4cf404e-d53b-11e5-942e-05efc1c504fc.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100273/a4cf404e-d53b-11e5-942e-05efc1c504fc.png)
https://cloud.githubusercontent.com/assets/10730122/13100273/a4cf404e-d53b-11e5-942e-05efc1c504fc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100271/a4b6bc54-d53b-11e5-8cb2-9ca724806f22.png
