### ISSUE TITLE
VNC Viewer

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7233]
**App Name:** VNC Viewer
**Bundle ID:** com.realvnc.VNCViewer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=352019548">352019548</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vnc-viewer/id352019548?mt=8&uo=4">https://itunes.apple.com/us/app/vnc-viewer/id352019548?mt=8&uo=4</a>
**App Version:** 2.4.2
**Seller:** RealVNC Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/realvnc/id352019552?uo=4>© RealVNC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/20/09/53/20095368-5ba6-4647-9541-cf63fbe24dbc/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100068/4739b4ac-d539-11e5-9e9a-605f8c996da5.png)

**Comment by Grafovich** [comment]
Already done
https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.realvnc.VNCViewer@2x.png

**Comment by Trubbel** [comment]
@Grafovich The icon is mission from the **@3x**-theme.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100068/4739b4ac-d539-11e5-9e9a-605f8c996da5.png)
https://cloud.githubusercontent.com/assets/10730122/13100068/4739b4ac-d539-11e5-9e9a-605f8c996da5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100067/473892de-d539-11e5-87af-1d74a479e601.png
