### ISSUE TITLE
Госуслуги

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7234]
**App Name:** Госуслуги
**Bundle ID:** com.rostelecom.gosuslugi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=502487330">502487330</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gosuslugi/id502487330?mt=8&uo=4">https://itunes.apple.com/us/app/gosuslugi/id502487330?mt=8&uo=4</a>
**App Version:** 2.2.0.11
**Seller:** Rostelecom
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/oao-rostelecom/id428474472?uo=4>© OAO "Rostelecom"</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/7b/3d/56/7b3d56d5-b00b-ce17-ff25-6b4923939f85/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100430/451464a2-d53d-11e5-95d6-aca018b37671.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100430/451464a2-d53d-11e5-95d6-aca018b37671.png)
https://cloud.githubusercontent.com/assets/10730122/13100430/451464a2-d53d-11e5-95d6-aca018b37671.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100431/45163354-d53d-11e5-8b6a-09cf242be7a7.png
