### ISSUE TITLE
Наш город

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7235]
**App Name:** Наш город
**Bundle ID:** ru.mos.eReception
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=560451628">560451628</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nas-gorod/id560451628?mt=8&uo=4">https://itunes.apple.com/us/app/nas-gorod/id560451628?mt=8&uo=4</a>
**App Version:** 3.7
**Seller:** Elektronnaya Moskva OAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pravitel-stvo-moskvy/id543871760?uo=4>© Правительство Москвы</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple2/v4/67/a0/fd/67a0fd34-e3c6-bc5d-993b-e2d34379554f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100444/678b7534-d53d-11e5-9f2a-bb156cf4cd51.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100444/678b7534-d53d-11e5-9f2a-bb156cf4cd51.png)
https://cloud.githubusercontent.com/assets/10730122/13100444/678b7534-d53d-11e5-9f2a-bb156cf4cd51.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100445/678d5c1e-d53d-11e5-8175-9eb9ef32b331.png
