### ISSUE TITLE
Госуслуги Москвы

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7236]
**App Name:** Госуслуги Москвы
**Bundle ID:** ru.mos.pgu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=566254786">566254786</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gosuslugi-moskvy/id566254786?mt=8&uo=4">https://itunes.apple.com/us/app/gosuslugi-moskvy/id566254786?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** Elektronnaya Moskva OAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pravitel-stvo-moskvy/id543871760?uo=4>© Правительство Москвы</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/8a/22/3b/8a223bdf-bb7b-f143-a4ec-8a708c7467a3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100454/876ed850-d53d-11e5-93f1-086a93eea93b.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100454/876ed850-d53d-11e5-93f1-086a93eea93b.png)
https://cloud.githubusercontent.com/assets/10730122/13100454/876ed850-d53d-11e5-93f1-086a93eea93b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100453/876ed18e-d53d-11e5-922d-6d2c78da27c2.png
