### ISSUE TITLE
Активный Гражданин

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7237]
**App Name:** Активный Гражданин
**Bundle ID:** iSuperCitizen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=873648765">873648765</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aktivnyj-grazdanin/id873648765?mt=8&uo=4">https://itunes.apple.com/us/app/aktivnyj-grazdanin/id873648765?mt=8&uo=4</a>
**App Version:** 1.9.5
**Seller:** Elektronnaya Moskva OAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pravitel-stvo-moskvy/id543871760?uo=4>© Правительство Москвы</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/25/de/36/25de3669-7f1c-a3fe-d750-538e6d370ae3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191344/4c5b65b2-d763-11e5-8749-d14ee68bdeff.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191344/4c5b65b2-d763-11e5-8749-d14ee68bdeff.png)
https://cloud.githubusercontent.com/assets/2068130/13191344/4c5b65b2-d763-11e5-8749-d14ee68bdeff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13191351/5aa8cd4e-d763-11e5-93ce-e8260038f5e5.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455091-09f79932-3a73-11e8-932e-ca1d76d874db.png)
https://user-images.githubusercontent.com/20930745/38455091-09f79932-3a73-11e8-932e-ca1d76d874db.png

Source:
https://user-images.githubusercontent.com/20930745/38455098-1dbab328-3a73-11e8-91fd-85b7ae7a43f7.png
