### ISSUE TITLE
Discover Moscow

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7238]
**App Name:** Discover Moscow
**Bundle ID:** DiscoverMoscow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=643324519">643324519</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/discover-moscow/id643324519?mt=8&uo=4">https://itunes.apple.com/us/app/discover-moscow/id643324519?mt=8&uo=4</a>
**App Version:** 3.7.7
**Seller:** Elektronnaya Moskva OAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pravitel-stvo-moskvy/id543871760?uo=4>© Правительство Москвы</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/6d/7c/e6/6d7ce64f-3aac-115a-f4b0-251edc7a3ae3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191744/28470c28-d766-11e5-87cf-0bf4b411d46f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191744/28470c28-d766-11e5-87cf-0bf4b411d46f.png)
https://cloud.githubusercontent.com/assets/2068130/13191744/28470c28-d766-11e5-87cf-0bf4b411d46f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13191754/36fd7720-d766-11e5-88cd-34fb2149d264.png
