### ISSUE TITLE
ЖКХ Москвы

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7239]
**App Name:** ЖКХ Москвы
**Bundle ID:** ru.mos.jkh
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=578889199">578889199</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zkh-moskvy/id578889199?mt=8&uo=4">https://itunes.apple.com/us/app/zkh-moskvy/id578889199?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Elektronnaya Moskva OAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pravitel-stvo-moskvy/id543871760?uo=4>© Правительство Москвы</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/f8/cc/0a/f8cc0a0d-d3dc-5aeb-a85f-c417a90c3828/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100641/96fcbaa6-d53f-11e5-8008-21221005a232.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100641/96fcbaa6-d53f-11e5-8008-21221005a232.png)
https://cloud.githubusercontent.com/assets/10730122/13100641/96fcbaa6-d53f-11e5-8008-21221005a232.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100642/96fe579e-d53f-11e5-814b-d4d4b30a9404.png
