### ISSUE TITLE
Adobe Acrobat Reader for PDF

### ISSUE THREAD

**Issue by mixad** [glasklart/hd#724]
**App Name:** Adobe Acrobat Reader for PDF
**Bundle ID:** com.adobe.Adobe-Reader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469337564">469337564</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/adobe-acrobat-reader-for-pdf/id469337564?uo=4">https://apps.apple.com/us/app/adobe-acrobat-reader-for-pdf/id469337564?uo=4</a>
**App Version:** 20.06.00
**Seller:** Adobe Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/adobe-inc/id331646274?uo=4">© Adobe Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/7f/ca/fd/7fcafd7f-96c2-6b56-b55e-7f5ed4a44c61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86528305-0a4f3380-bea7-11ea-9027-ce227582f261.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19588068/70c7a346-9763-11e6-9892-cbeddc66ec7d.png)
https://cloud.githubusercontent.com/assets/10730122/19588068/70c7a346-9763-11e6-9892-cbeddc66ec7d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19588069/70c7c24a-9763-11e6-978d-9221d818447a.png

**Comment by alpcinar** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://previeww.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86528305-0a4f3380-bea7-11ea-9027-ce227582f261.png)
https://user-images.githubusercontent.com/2068130/86528305-0a4f3380-bea7-11ea-9027-ce227582f261.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86528312-19ce7c80-bea7-11ea-9c57-d7bd4cd1940b.png
