### ISSUE TITLE
ЕМИАС города Москвы

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7240]
**App Name:** ЕМИАС города Москвы
**Bundle ID:** ru.mos.emias
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=997430168">997430168</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/emias-goroda-moskvy/id997430168?mt=8&uo=4">https://itunes.apple.com/us/app/emias-goroda-moskvy/id997430168?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Elektronnaya Moskva OAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pravitel-stvo-moskvy/id543871760?uo=4>© Правительство Москвы</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/3d/3d/3d/3d3d3dc6-5e7c-5554-4b4e-ed55fd85dde2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100654/b622199e-d53f-11e5-862b-53121545e2eb.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100654/b622199e-d53f-11e5-862b-53121545e2eb.png)
https://cloud.githubusercontent.com/assets/10730122/13100654/b622199e-d53f-11e5-862b-53121545e2eb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100653/b6221caa-d53f-11e5-94a2-8027c978c8b5.png
