### ISSUE TITLE
Электронный атлас Москвы

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7241]
**App Name:** Электронный атлас Москвы
**Bundle ID:** mos.MoscowAtlas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989236861">989236861</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/elektronnyj-atlas-moskvy/id989236861?mt=8&uo=4">https://itunes.apple.com/us/app/elektronnyj-atlas-moskvy/id989236861?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Elektronnaya Moskva OAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pravitel-stvo-moskvy/id543871760?uo=4>© Правительство Москвы</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/84/03/e2/8403e26f-b141-a541-19ff-f5b9b7a3dec1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13101919/92c981a2-d54a-11e5-9830-4d41114a8546.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13101919/92c981a2-d54a-11e5-9830-4d41114a8546.png)
https://cloud.githubusercontent.com/assets/2068130/13101919/92c981a2-d54a-11e5-9830-4d41114a8546.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13101937/a7b9d0b2-d54a-11e5-82a8-f0601a390a1d.png
