### ISSUE TITLE
Moscow Parking

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7242]
**App Name:** Moscow Parking
**Bundle ID:** ru.mos.parking.full.appstore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=569503630">569503630</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moscow-parking/id569503630?mt=8&uo=4">https://itunes.apple.com/us/app/moscow-parking/id569503630?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Elektronnaya Moskva OAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pravitel-stvo-moskvy/id543871760?uo=4>© Правительство Москвы</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/f8/e6/4b/f8e64b42-3590-1592-4c1e-10c3b40457b9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100664/d25da0ec-d53f-11e5-8187-4b70b0f86bfa.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13100664/d25da0ec-d53f-11e5-8187-4b70b0f86bfa.png)
https://cloud.githubusercontent.com/assets/10730122/13100664/d25da0ec-d53f-11e5-8187-4b70b0f86bfa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13100663/d2465090-d53f-11e5-9634-4e1035933e13.png

**Comment by dreamnet** [comment]
@Trubbel Great work on the last icons! THX! :+1:
