### ISSUE TITLE
Мобильный туристический портал города Москвы

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7243]
**App Name:** Мобильный туристический портал города Москвы
**Bundle ID:** mos.tourist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=566258269">566258269</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobil-nyj-turisticeskij-portal/id566258269?mt=8&uo=4">https://itunes.apple.com/us/app/mobil-nyj-turisticeskij-portal/id566258269?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Elektronnaya Moskva OAO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pravitel-stvo-moskvy/id543871760?uo=4>© Правительство Москвы</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/a2/05/ee/a205eeff-c4b1-29fd-0e5e-4950c8494118/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13375085/d5d37aa8-dd96-11e5-8d06-9e04c6281d6e.png)

**Comment by Grafovich** [comment]
I think just the map and pin would be enough. And much easier to create i think :)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13375085/d5d37aa8-dd96-11e5-8d06-9e04c6281d6e.png)
https://cloud.githubusercontent.com/assets/2068130/13375085/d5d37aa8-dd96-11e5-8d06-9e04c6281d6e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13375090/e484fe50-dd96-11e5-9753-c4447cf115ee.png

**Comment by Grafovich** [comment]
@dreamnet :+1:
