### ISSUE TITLE
Gif Viewer - with camera roll Gif player and web Gif search engine

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7244]
**App Name:** Gif Viewer - with camera roll Gif player and web Gif search engine
**Bundle ID:** com.adagissimo.GifBoxlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=660683772">660683772</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gif-viewer-camera-roll-gif/id660683772?mt=8&uo=4">https://itunes.apple.com/us/app/gif-viewer-camera-roll-gif/id660683772?mt=8&uo=4</a>
**App Version:** 8.1
**Seller:** Notable Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/notable-group/id646605989?uo=4>© Notable Group</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/d6/07/ec/d607ec2b-75de-40a1-e4cb-490bd761c721/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11456883/a384fdc8-9698-11e5-915e-1529f98a0c6f.png)

**Comment by Anuskuss** [comment]
Same icon as #6866

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11456883/a384fdc8-9698-11e5-915e-1529f98a0c6f.png)
https://cloud.githubusercontent.com/assets/2068130/11456883/a384fdc8-9698-11e5-915e-1529f98a0c6f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11456886/b23a68c6-9698-11e5-8eac-cb6f1dbee9c1.png
