### ISSUE TITLE
Spider Solitaire ∙ Card Game

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7245]
**App Name:** Spider Solitaire ∙ Card Game
**Bundle ID:** com.greenpanda.spidersolitairefree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=686420990">686420990</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spider-solitaire-card-game/id686420990?mt=8&uo=4">https://itunes.apple.com/us/app/spider-solitaire-card-game/id686420990?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** GREEN PANDA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/green-panda-games/id669978473?uo=4>© Green Panda Games</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/9e/eb/05/9eeb05a2-7e19-d7de-a711-a91bc113ddf9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374423/d94c84fc-dd84-11e5-957f-008dba145772.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374423/d94c84fc-dd84-11e5-957f-008dba145772.png)
https://cloud.githubusercontent.com/assets/2068130/13374423/d94c84fc-dd84-11e5-957f-008dba145772.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13374425/e77ed6c4-dd84-11e5-9816-3c4c771dd25a.png
