### ISSUE TITLE
Trafico NO! Pro, con precio de la gasolina y avisador de radares

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7246]
**App Name:** Trafico NO! Pro, con precio de la gasolina y avisador de radares
**Bundle ID:** com.littlemousesoftware.traficono
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=429739397">429739397</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/trafico-no!-pro-con-precio/id429739397?mt=8&uo=4">https://itunes.apple.com/es/app/trafico-no!-pro-con-precio/id429739397?mt=8&uo=4</a>
**App Version:** 10.2.1
**Seller:** Raul Martin Carbonell
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/little-mouse-software/id429739400?uo=4>© Little Mouse Software</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/37/86/8e/37868e1f-b296-ee18-0b8c-b1131a1ced12/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191078/8e33cbac-d761-11e5-9cbc-73d192a694b3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191078/8e33cbac-d761-11e5-9cbc-73d192a694b3.png)
https://cloud.githubusercontent.com/assets/2068130/13191078/8e33cbac-d761-11e5-9cbc-73d192a694b3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13191084/9c24f75e-d761-11e5-8183-67b9df643943.png
