### ISSUE TITLE
Maxima Fm Radio

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7247]
**App Name:** Maxima Fm Radio
**Bundle ID:** com.ericsson.maximaFM
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448303330">448303330</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/maxima-fm-radio/id448303330?mt=8&uo=4">https://itunes.apple.com/us/app/maxima-fm-radio/id448303330?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Union Radio
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/union-radio/id344892385?uo=4>© Union Radio</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/3f/44/fe/3f44fee5-dc54-310b-20bd-50a41a5b33b4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191009/074146b0-d761-11e5-99f5-8b984edc0eb3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191009/074146b0-d761-11e5-99f5-8b984edc0eb3.png)
https://cloud.githubusercontent.com/assets/2068130/13191009/074146b0-d761-11e5-99f5-8b984edc0eb3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13191023/1d11e8d2-d761-11e5-846f-0173d323dea2.png
