### ISSUE TITLE
Atresplayer

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7248]
**App Name:** Atresplayer
**Bundle ID:** com.antena3.atresplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=694169089">694169089</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/atresplayer/id694169089?mt=8&uo=4">https://itunes.apple.com/us/app/atresplayer/id694169089?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Antena 3 Television
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/antena-3-television/id331213756?uo=4>© Antena 3 Television</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/bf/5d/35/bf5d353f-70ee-58df-107c-2400077a9f7b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13190301/b0a63904-d75c-11e5-8666-6431d5565715.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13190301/b0a63904-d75c-11e5-8666-6431d5565715.png)
https://cloud.githubusercontent.com/assets/2068130/13190301/b0a63904-d75c-11e5-8666-6431d5565715.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13190313/c0029366-d75c-11e5-84af-9282f4efed82.png
