### ISSUE TITLE
el Periodico de Aragón

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7249]
**App Name:** el Periodico de Aragón
**Bundle ID:** com.zetadigital.elperiodicoAragon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=419106730">419106730</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/el-periodico-de-aragon/id419106730?mt=8&uo=4">https://itunes.apple.com/us/app/el-periodico-de-aragon/id419106730?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Zeta Digital SL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zeta-digital-sl/id407970193?uo=4>© Zeta Digital SL</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/dd/11/e7/dd11e7d5-fde0-3861-16da-ed70e0268c5c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13190826/e6cb9a9e-d75f-11e5-896b-59017ed07dd7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13190826/e6cb9a9e-d75f-11e5-896b-59017ed07dd7.png)
https://cloud.githubusercontent.com/assets/2068130/13190826/e6cb9a9e-d75f-11e5-896b-59017ed07dd7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13190833/f4e2d6ec-d75f-11e5-82a8-3a4811f71231.png
