### ISSUE TITLE
Harry's Laptimer PRO

### ISSUE THREAD

**Issue by mixad** [glasklart/hd#725]
**App Name:** Harry's LapTimer Petrolhead
**Bundle ID:** com.harrys.LapTimerPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338257907">338257907</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/harrys-laptimer-petrolhead/id338257907?mt=8&uo=4">https://itunes.apple.com/us/app/harrys-laptimer-petrolhead/id338257907?mt=8&uo=4</a>
**App Version:** 21.1.0
**Seller:** Harald Schlangmann
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/harald-schlangmann/id307688601?uo=4">© Harald Schlangmann</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/36/b2/9c/36b29ca3-cc92-d0c4-65f2-9dc264fc29ed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32360605-ce7792f8-c057-11e7-8b5e-622ce4c6b1ed.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32360605-ce7792f8-c057-11e7-8b5e-622ce4c6b1ed.png)
https://user-images.githubusercontent.com/2068130/32360605-ce7792f8-c057-11e7-8b5e-622ce4c6b1ed.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32360613-e1a1e09a-c057-11e7-9e01-b4b1286a90dc.png
