### ISSUE TITLE
Mi Fibra Ono

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7250]
**App Name:** Mi Fibra Ono
**Bundle ID:** es.ono.miOno
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=921499728">921499728</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mi-fibra-ono/id921499728?mt=8&uo=4">https://itunes.apple.com/us/app/mi-fibra-ono/id921499728?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Cableuropa SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ono/id366482646?uo=4>© ONO</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/fe/bc/64/febc6475-015d-5908-b020-0e5788b9bd1a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13190475/9705641a-d75d-11e5-8fc4-f1dfc6e8d34b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13190475/9705641a-d75d-11e5-8fc4-f1dfc6e8d34b.png)
https://cloud.githubusercontent.com/assets/2068130/13190475/9705641a-d75d-11e5-8fc4-f1dfc6e8d34b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13190485/a60437e8-d75d-11e5-9800-56768cd86f01.png
