### ISSUE TITLE
ABA English - Learn English

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7251]
**App Name:** ABA English - Learn English
**Bundle ID:** com.abaenglish
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=859243872">859243872</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/aba-english-learn-english/id859243872?uo=4">https://apps.apple.com/us/app/aba-english-learn-english/id859243872?uo=4</a>
**App Version:** 3.11.1
**Seller:** English Worldwide, S.L.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/aba-english/id859243875?uo=4">© ABA English</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/a3/75/04/a3750465-4127-01df-c190-b4dfd4f9dff7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979716-6bcd9880-95eb-11e9-8bc5-07bb3b458280.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374335/da34f2e4-dd81-11e5-8524-26b4f9be57c8.png)
https://cloud.githubusercontent.com/assets/2068130/13374335/da34f2e4-dd81-11e5-8524-26b4f9be57c8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13374336/e7d25bda-dd81-11e5-8569-4fde23092c97.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979716-6bcd9880-95eb-11e9-8bc5-07bb3b458280.png)
https://user-images.githubusercontent.com/2068130/59979716-6bcd9880-95eb-11e9-8bc5-07bb3b458280.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979718-7ab44b00-95eb-11e9-90d6-ee3e7921df53.png
