### ISSUE TITLE
HitFM Radio

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7252]
**App Name:** HitFM Radio
**Bundle ID:** Hit-FM.Hit-Fm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=742040144">742040144</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hitfm-radio/id742040144?mt=8&uo=4">https://itunes.apple.com/us/app/hitfm-radio/id742040144?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Jorge Jimenez Santos
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jorge-jimenez-santos/id742040147?uo=4>© Jorge Jimenez Santos</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/14/6d/83/146d8336-8cab-a1b2-3df2-b045fe1a48d8/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374219/8071fd5e-dd7e-11e5-9360-7e043e3a5721.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374219/8071fd5e-dd7e-11e5-9360-7e043e3a5721.png)
https://cloud.githubusercontent.com/assets/2068130/13374219/8071fd5e-dd7e-11e5-9360-7e043e3a5721.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13374223/8f5568ce-dd7e-11e5-85d5-04e2b0243273.png
