### ISSUE TITLE
SocialDrive

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7253]
**App Name:** SocialDrive
**Bundle ID:** rge.tech.socialdrive.es
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=895759753">895759753</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/socialdrive/id895759753?mt=8&uo=4">https://itunes.apple.com/es/app/socialdrive/id895759753?mt=8&uo=4</a>
**App Version:** 3.7
**Seller:** SD APPS SL
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/socialdrive/id895759756?uo=4>© SocialDrive</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/83/85/28/838528f8-b902-335c-4d4b-1ae994d7ddfb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191217/7bdfe372-d762-11e5-9418-18de937df96d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191217/7bdfe372-d762-11e5-9418-18de937df96d.png)
https://cloud.githubusercontent.com/assets/2068130/13191217/7bdfe372-d762-11e5-9418-18de937df96d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13191223/8a0b9dce-d762-11e5-9233-9ac7269beabf.png
