### ISSUE TITLE
sport TV Live - Sport Television Channels

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7254]
**App Name:** sport TV Live - Sport Television Channels
**Bundle ID:** com.readerwill.sport
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1013584317">1013584317</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sport-tv-live-sport-television/id1013584317?mt=8&uo=4">https://itunes.apple.com/us/app/sport-tv-live-sport-television/id1013584317?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** AppsVilla Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appsvilla-inc./id673558127?uo=4>© AppsVilla Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/a1/32/7a/a1327ab9-a0ec-3be2-732c-ac7a89dfb909/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191572/041278fc-d765-11e5-8a77-72dcb976cd06.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191572/041278fc-d765-11e5-8a77-72dcb976cd06.png)
https://cloud.githubusercontent.com/assets/2068130/13191572/041278fc-d765-11e5-8a77-72dcb976cd06.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13191581/12915e02-d765-11e5-9fee-42032dcfaead.png
