### ISSUE TITLE
Glimpse - Webpages for your Watch and Notification Center

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7255]
**App Name:** Glimpse - Webpages for your Watch and Notification Center
**Bundle ID:** APPenzeller.WebLook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=925765624">925765624</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glimpse-webpages-for-your/id925765624?mt=8&uo=4">https://itunes.apple.com/us/app/glimpse-webpages-for-your/id925765624?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Arno Appenzeller
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/arno-appenzeller/id515339331?uo=4>© Arno Appenzeller</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/9a/6d/86/9a6d866c-6657-4db6-12d1-05d4d057ff21/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191435/ee6bc022-d763-11e5-963b-f8fd708cb299.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13191435/ee6bc022-d763-11e5-963b-f8fd708cb299.png)
https://cloud.githubusercontent.com/assets/2068130/13191435/ee6bc022-d763-11e5-963b-f8fd708cb299.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13191440/fea8ae64-d763-11e5-86b1-80ecd9084056.png
