### ISSUE TITLE
Data Widget

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7258]
**App Name:** Data Widget
**Bundle ID:** com.tianpinsoft.DataWidget
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=915632592">915632592</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/data-widget/id915632592?mt=8&uo=4">https://itunes.apple.com/us/app/data-widget/id915632592?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** JI DASHENG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jerry-jee/id320513564?uo=4>© Jerry Jee</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/02/6a/ef/026aef5e-7a33-5d6e-9bf5-7230462c7560/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13266013/4629e40a-da76-11e5-8c34-6906d57dde0b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13266013/4629e40a-da76-11e5-8c34-6906d57dde0b.png)
https://cloud.githubusercontent.com/assets/2068130/13266013/4629e40a-da76-11e5-8c34-6906d57dde0b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13266025/5596dfb0-da76-11e5-975d-3db43a21ea65.png
