### ISSUE TITLE
Undead Clicker!

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7259]
**App Name:** Undead Clicker!
**Bundle ID:** com.trinitistars.undeadclicker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1063965338">1063965338</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/undead-clicker!/id1063965338?mt=8&uo=4">https://itunes.apple.com/us/app/undead-clicker!/id1063965338?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Triniti Stars Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/triniti-stars/id1063225127?uo=4>© Triniti stars</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/e0/13/17/e01317ef-85f8-4223-1c05-5da08591790d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13511358/5464870c-e195-11e5-9031-304875e64f0e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13336671/997ac190-dc17-11e5-9c31-bd87f8a373b1.png)
https://cloud.githubusercontent.com/assets/2068130/13336671/997ac190-dc17-11e5-9c31-bd87f8a373b1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13336677/a6977828-dc17-11e5-8eb6-553532602001.png
Omg! - Waaaayyy too small... :disappointed:

**Comment by Trubbel** [comment]
@dreamnet I think it looks good, but what about removing the moon?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13511358/5464870c-e195-11e5-9031-304875e64f0e.png)
https://cloud.githubusercontent.com/assets/2068130/13511358/5464870c-e195-11e5-9031-304875e64f0e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13511376/64325a24-e195-11e5-94eb-53030cf6406e.png

**Comment by ivanov007** [comment]
yeah looks better :+1:

**Comment by Trubbel** [comment]
@ivanov007 Agreed.
@dreamnet :+1:
