### ISSUE TITLE
Vine

### ISSUE THREAD

**Issue by keefetang** [glasklart/hd#726]
**App Name:** Vine
**Bundle ID:** com.vine.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=592447445">592447445</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vine/id592447445?mt=8&uo=4">https://itunes.apple.com/us/app/vine/id592447445?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** VINE LABS INC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/vine-labs-inc./id592447448?uo=4>© Vine Labs, Inc.</a>
**Supported Devices:** iPhone5, iPhone6Plus, iPad23G, iPadThirdGen, iPhone4, iPadFourthGen, iPhone5c, iPhone5s, iPodTouchFifthGen, iPhone4S, iPadFourthGen4G, iPadMini4G, iPadThirdGen4G, iPad2Wifi, iPadMini, iPhone6
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/8b/4f/ac/8b4fac41-0445-dcf3-d538-bb34235de52a/mzl.siqpmclu.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8529461/ac33e16e-241a-11e5-8b43-210ab39f6bbb.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8513483/2c71bdbe-236d-11e5-8ab3-75b08cd7908a.png)
https://cloud.githubusercontent.com/assets/10730122/8513483/2c71bdbe-236d-11e5-8ab3-75b08cd7908a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8513482/28ad8fe6-236d-11e5-8ee2-24f5c2b0f9a2.png

**Comment by dreamnet** [comment]
Correcting the size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8529339/904f7d24-2419-11e5-9180-0bfa0db60f79.png)
https://cloud.githubusercontent.com/assets/2068130/8529339/904f7d24-2419-11e5-9180-0bfa0db60f79.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8529350/9ff0b1c6-2419-11e5-8e7c-45332767a372.png
