### ISSUE TITLE
РЕБУСЫ+

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7262]
**App Name:** РЕБУСЫ+
**Bundle ID:** rebuses.com.jutiful
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=640483745">640483745</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rebusy+/id640483745?mt=8&uo=4">https://itunes.apple.com/us/app/rebusy+/id640483745?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Jutiful Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jutiful/id582966637?uo=4>© Jutiful</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/bc/e2/88/bce2888b-fdf3-64cc-15c6-82e8beba41ee/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13265799/3b9c2bd4-da75-11e5-8f52-551d6c3fb0cf.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13265799/3b9c2bd4-da75-11e5-8f52-551d6c3fb0cf.png)
https://cloud.githubusercontent.com/assets/2068130/13265799/3b9c2bd4-da75-11e5-8f52-551d6c3fb0cf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13265813/49bb0668-da75-11e5-8ff3-0f991187dda8.png
