### ISSUE TITLE
БРЕДУСЫ

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7263]
**App Name:** БРЕДУСЫ
**Bundle ID:** breduses.com.jutiful
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=862540988">862540988</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bredusy/id862540988?mt=8&uo=4">https://itunes.apple.com/us/app/bredusy/id862540988?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Jutiful Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jutiful/id582966637?uo=4>© Jutiful</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/80/72/9a/80729a93-848e-8d3d-f713-2b26e4b887e8/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13265872/93b1df94-da75-11e5-8c59-bfb1451c41b5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13265872/93b1df94-da75-11e5-8c59-bfb1451c41b5.png)
https://cloud.githubusercontent.com/assets/2068130/13265872/93b1df94-da75-11e5-8c59-bfb1451c41b5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13265883/a1ccb874-da75-11e5-8a26-2d25aa00f47f.png
