### ISSUE TITLE
MyPocket: Personal document organizer

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7264]
**App Name:** MyPocket: Personal document organizer
**Bundle ID:** me.vkarmane
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=639393959">639393959</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mypocket-personal-document/id639393959?mt=8&uo=4">https://itunes.apple.com/us/app/mypocket-personal-document/id639393959?mt=8&uo=4</a>
**App Version:** 2.8
**Seller:** VKarmane OOO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vkarmane-ooo/id638695506?uo=4>© VKarmane OOO</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/11/e8/66/11e866d7-e62c-a407-a2f3-326bf3123cf2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13265645/5006b7e8-da74-11e5-993d-3082ec5669ae.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13265645/5006b7e8-da74-11e5-993d-3082ec5669ae.png)
https://cloud.githubusercontent.com/assets/2068130/13265645/5006b7e8-da74-11e5-993d-3082ec5669ae.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13265656/5d9ffd4c-da74-11e5-8f4b-4adf05d6b1e3.png
