### ISSUE TITLE
1Gb mobile

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7265]
**App Name:** 1Gb mobile
**Bundle ID:** onegbmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=568686110">568686110</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1gb-mobile/id568686110?mt=8&uo=4">https://itunes.apple.com/us/app/1gb-mobile/id568686110?mt=8&uo=4</a>
**App Version:** 1.0.18
**Seller:** Evgenii Lepikhin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/evgenii-lepikhin/id568686113?uo=4>© Evgenii Lepikhin</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/2e/0e/21/2e0e219a-aebc-f1df-1cb5-42f6433acbb4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13372148/4fdb94e6-dd3a-11e5-86a0-15ca3ec9fc23.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13372148/4fdb94e6-dd3a-11e5-86a0-15ca3ec9fc23.png)
https://cloud.githubusercontent.com/assets/2068130/13372148/4fdb94e6-dd3a-11e5-86a0-15ca3ec9fc23.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13372151/5dd65252-dd3a-11e5-8298-e00f3fbf47ab.png
