### ISSUE TITLE
JD.RU

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7267]
**App Name:** JD.RU
**Bundle ID:** ru.jd.JD.RU
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1070047683">1070047683</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jd.ru/id1070047683?mt=8&uo=4">https://itunes.apple.com/us/app/jd.ru/id1070047683?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** JD.com International Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jd.com-international-limited/id1070047682?uo=4>© JD.com International Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/f4/87/5a/f4875a85-a096-5bcd-63d1-f580e6f46abc/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13336266/714d98f2-dc15-11e5-970c-975439c414d0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13336266/714d98f2-dc15-11e5-970c-975439c414d0.png)
https://cloud.githubusercontent.com/assets/2068130/13336266/714d98f2-dc15-11e5-970c-975439c414d0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13336282/80921810-dc15-11e5-8f83-ac4f7b32d4ea.png
