### ISSUE TITLE
Live Crop for Live Photo, Video and GIF

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7268]
**App Name:** Live Crop for Live Photo, Video and GIF
**Bundle ID:** com.mobilab.livecrop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1083853203">1083853203</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/live-crop-for-live-photo-video/id1083853203?mt=8&uo=4">https://itunes.apple.com/us/app/live-crop-for-live-photo-video/id1083853203?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** MobiLab Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobilab-co.-ltd./id417565025?uo=4>© MobiLab Co., Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/72/76/90/7276901d-66a6-9980-f6cc-f63850b59353/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13336407/17dfc58c-dc16-11e5-933c-1e4fdb35602d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13336407/17dfc58c-dc16-11e5-933c-1e4fdb35602d.png)
https://cloud.githubusercontent.com/assets/2068130/13336407/17dfc58c-dc16-11e5-933c-1e4fdb35602d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13336420/2707ccf8-dc16-11e5-8f7e-933d4f51307f.png
