### ISSUE TITLE
Matcha 3 - Notes, Journal, and Word Processor

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7269]
**App Name:** Matcha 3 - Notes, Journal, and Word Processor
**Bundle ID:** com.interare.ios.Matcha.Smoothie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1031220415">1031220415</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/matcha-3-notes-journal-word/id1031220415?mt=8&uo=4">https://itunes.apple.com/us/app/matcha-3-notes-journal-word/id1031220415?mt=8&uo=4</a>
**App Version:** 3.0.3
**Seller:** InterAre, PT
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/interare-pt/id533476636?uo=4>© InterAre, PT</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/fc/f4/e6/fcf4e6f9-0490-afa8-9c95-012fb5257db5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13371997/54819e3c-dd35-11e5-8fae-54b97a66d008.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13371997/54819e3c-dd35-11e5-8fae-54b97a66d008.png)
https://cloud.githubusercontent.com/assets/2068130/13371997/54819e3c-dd35-11e5-8fae-54b97a66d008.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13371999/6397f01a-dd35-11e5-9f8b-052e12eac167.png
