### ISSUE TITLE
Sports News, Scores & Stats: Personalized by Chat Sports

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7272]
**App Name:** Sports News, Scores & Stats: Personalized by Chat Sports
**Bundle ID:** com.chatsports.chatsportsapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=819629553">819629553</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sports-news-scores-stats-personalized/id819629553?mt=8&uo=4">https://itunes.apple.com/us/app/sports-news-scores-stats-personalized/id819629553?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Chat Sports
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chat-sports/id819629556?uo=4>© Chat Sports</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/41/3c/30/413c302e-2b1d-250b-df0d-7867e89cc634/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374305/f0ac3dd0-dd80-11e5-81fe-15be9b1d36a0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374305/f0ac3dd0-dd80-11e5-81fe-15be9b1d36a0.png)
https://cloud.githubusercontent.com/assets/2068130/13374305/f0ac3dd0-dd80-11e5-81fe-15be9b1d36a0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13374306/fe4bc35c-dd80-11e5-9783-b77db4cbb6e9.png
