### ISSUE TITLE
CBS Sports Fantasy Football, Baseball, Basketball & Hockey

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7273]
**App Name:** CBS Sports Fantasy Football, Baseball, Basketball & Hockey
**Bundle ID:** com.cbssports.fantasy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=658308834">658308834</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cbs-sports-fantasy-football/id658308834?mt=8&uo=4">https://itunes.apple.com/us/app/cbs-sports-fantasy-football/id658308834?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** CBS Mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cbs-interactive/id295669712?mt=8&uo=4>© CBS Interactive</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/1d/c2/d6/1dc2d633-ce79-8b2c-848d-a58179da8fc9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374291/4bb1bf3a-dd80-11e5-91e1-8dd10f625421.png)

**Comment by dreamnet** [comment]
Refers to #6741.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13374291/4bb1bf3a-dd80-11e5-91e1-8dd10f625421.png)
https://cloud.githubusercontent.com/assets/2068130/13374291/4bb1bf3a-dd80-11e5-91e1-8dd10f625421.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13374292/595a5660-dd80-11e5-81c7-fce6f13f7b3d.png
