### ISSUE TITLE
Polaris Office - Docs, PDF Reader & Editor

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7275]
**App Name:** Polaris Office - Docs, PDF Reader & Editor
**Bundle ID:** kr.co.infraware.office.link
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=698070860">698070860</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/polaris-office-docs-pdf-reader-editor/id698070860?mt=8&uo=4">https://itunes.apple.com/us/app/polaris-office-docs-pdf-reader-editor/id698070860?mt=8&uo=4</a>
**App Version:** 7.3.23
**Seller:** Infraware Co.Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/infraware-co-ltd/id380275428?uo=4">© Infraware Co.,Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/ab/b6/3b/abb63bf3-cef2-a366-2c09-440a0422676d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/30343771-f650d41e-97fe-11e7-88b9-060ac57a9f6d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13380423/53227160-de43-11e5-8f80-c8961b596f51.png)
https://cloud.githubusercontent.com/assets/2068130/13380423/53227160-de43-11e5-8f80-c8961b596f51.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13380426/61660a0c-de43-11e5-91b1-ddbd5bd1aef9.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Polaris Office - Docs, PDF Reader & Editor
**Bundle ID:** kr.co.infraware.office.link
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=698070860">698070860</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/polaris-office-docs-pdf-reader-editor/id698070860?mt=8&uo=4">https://itunes.apple.com/us/app/polaris-office-docs-pdf-reader-editor/id698070860?mt=8&uo=4</a>
**App Version:** 7.3.23
**Seller:** Infraware Co.Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/infraware-co-ltd/id380275428?uo=4">© Infraware Co.,Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/ab/b6/3b/abb63bf3-cef2-a366-2c09-440a0422676d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/30343771-f650d41e-97fe-11e7-88b9-060ac57a9f6d.png)
https://user-images.githubusercontent.com/2068130/30343771-f650d41e-97fe-11e7-88b9-060ac57a9f6d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/30343786-0530502c-97ff-11e7-8317-5100f50a3ebc.png
