### ISSUE TITLE
Alto - Organize Your Email

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7277]
**App Name:** Alto - Organize Your Email
**Bundle ID:** com.aol.mobile.altomail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1043210141">1043210141</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alto-organize-your-email/id1043210141?mt=8&uo=4">https://itunes.apple.com/us/app/alto-organize-your-email/id1043210141?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** AOL Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aol-inc./id281704577?uo=4>© AOL Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/9c/a2/8f/9ca28f86-6ab1-8f36-c799-dc84246bcf80/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13379899/936ad2b8-de33-11e5-9adf-a652e14761cd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13379899/936ad2b8-de33-11e5-9adf-a652e14761cd.png)
https://cloud.githubusercontent.com/assets/2068130/13379899/936ad2b8-de33-11e5-9adf-a652e14761cd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13379900/a2de3cda-de33-11e5-97a0-505350d32349.png
