### ISSUE TITLE
Mailburn — email client for Gmail with unsubscribe from newsletters

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7278]
**App Name:** Mailburn — email client for Gmail with unsubscribe from newsletters
**Bundle ID:** com.mailburn.mailburn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=938405668">938405668</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mailburn-email-client-for/id938405668?mt=8&uo=4">https://itunes.apple.com/us/app/mailburn-email-client-for/id938405668?mt=8&uo=4</a>
**App Version:** 1.6.1
**Seller:** Mailburn Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mailburn-inc./id938405667?uo=4>© Mailburn Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/86/bc/ca/86bccaed-332a-1ea0-fb11-b557a322bf74/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13379919/644f028c-de34-11e5-9941-74655e3acdff.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13379919/644f028c-de34-11e5-9941-74655e3acdff.png)
https://cloud.githubusercontent.com/assets/2068130/13379919/644f028c-de34-11e5-9941-74655e3acdff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13379921/768cae04-de34-11e5-8507-2b00ab28249f.png
