### ISSUE TITLE
Inbox by Zendesk - Work together on shared email

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7279]
**App Name:** Inbox by Zendesk - Work together on shared email
**Bundle ID:** com.zendesk.inbox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937437086">937437086</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inbox-by-zendesk-work-together/id937437086?mt=8&uo=4">https://itunes.apple.com/us/app/inbox-by-zendesk-work-together/id937437086?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Zendesk, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zendesk/id368796010?uo=4>© Zendesk</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/3a/64/e0/3a64e0c0-e93b-8d15-8504-e6516c77c4aa/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13379935/f6777b94-de34-11e5-839c-ecf0b2b26629.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13379935/f6777b94-de34-11e5-839c-ecf0b2b26629.png)
https://cloud.githubusercontent.com/assets/2068130/13379935/f6777b94-de34-11e5-839c-ecf0b2b26629.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13379937/04b86b00-de35-11e5-878a-4be4e60f17a8.png
