### ISSUE TITLE
Chase Mobile℠

### ISSUE THREAD

**Issue by thatsoaustin** [glasklart/hd#728]
**App Name:** Chase Mobile℠
**Bundle ID:** com.chase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=298867247">298867247</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chase-mobilesm/id298867247?mt=8&uo=4">https://itunes.apple.com/us/app/chase-mobilesm/id298867247?mt=8&uo=4</a>
**App Version:** 2.420
**Seller:** JPMorgan Chase Bank, NA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jpmorgan-chase-co./id298867250?uo=4>© JPMorgan Chase & Co.</a>
**Supported Devices:** iPhone4, iPadMini, iPhone5c, iPadFourthGen4G, iPad2Wifi, iPadThirdGen4G, iPad23G, iPodTouchFifthGen, iPadFourthGen, iPhone4S, iPhone6, iPadThirdGen, iPhone6Plus, iPhone5s, iPhone5, iPadMini4G
**Original Artwork:**
<img src="http://a8.phobos.apple.com/us/r30/Purple3/v4/e2/6b/56/e26b5656-b94b-5851-20d9-522d74ac4c5d/mzl.pivfbuer.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6986350/64170a64-da0a-11e4-8af6-7451b82f9667.png)

**Comment by zmathiasz** [comment]
**App Name:** Chase Mobile℠
**Bundle ID:** com.chase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=298867247">298867247</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chase-mobilesm/id298867247?mt=8&uo=4">https://itunes.apple.com/us/app/chase-mobilesm/id298867247?mt=8&uo=4</a>
**App Version:** 2.420
**Seller:** JPMorgan Chase Bank, NA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/jpmorgan-chase-co./id298867250?uo=4>© JPMorgan Chase & Co.</a>
**Supported Devices:** iPhone5s, iPad23G, iPhone4S, iPhone6, iPadMini4G, iPhone4, iPodTouchFifthGen, iPadThirdGen, iPadMini, iPad2Wifi, iPhone6Plus, iPadThirdGen4G, iPadFourthGen4G, iPadFourthGen, iPhone5, iPhone5c
**Original Artwork:**
<img src="http://a8.phobos.apple.com/us/r30/Purple3/v4/e2/6b/56/e26b5656-b94b-5851-20d9-522d74ac4c5d/mzl.pivfbuer.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by zmathiasz** [comment]
@dreamnet 

Icon update w/Source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6986350/64170a64-da0a-11e4-8af6-7451b82f9667.png)
https://cloud.githubusercontent.com/assets/10950389/6986350/64170a64-da0a-11e4-8af6-7451b82f9667.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6986354/6def3304-da0a-11e4-91b9-2946ff7357c0.png
