### ISSUE TITLE
Почта России

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7282]
**App Name:** Почта России
**Bundle ID:** ru.russianpost.Russian-Post
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=771700826">771700826</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocta-rossii/id771700826?mt=8&uo=4">https://itunes.apple.com/us/app/pocta-rossii/id771700826?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Federal State Unitary Enterprise Russian Post
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/russian-post/id771700829?uo=4>© Russian Post</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/4f/4d/41/4f4d4160-4f0a-f665-9764-a3b0f4f885f4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419728/c76eac12-df80-11e5-9104-a84fd1604c2f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419728/c76eac12-df80-11e5-9104-a84fd1604c2f.png)
https://cloud.githubusercontent.com/assets/2068130/13419728/c76eac12-df80-11e5-9104-a84fd1604c2f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13419738/d6de32bc-df80-11e5-81b5-743796a47d8c.png
