### ISSUE TITLE
PayPal

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7284]
**App Name:** PayPal
**Bundle ID:** com.yourcompany.PPClient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=283646709">283646709</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paypal/id283646709?mt=8&uo=4">https://itunes.apple.com/us/app/paypal/id283646709?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** PayPal, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/paypal-inc./id283646712?uo=4>© PayPal, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/78/77/46/78774630-23c0-6fec-c909-34ddec819c2d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13510842/d8e02c32-e192-11e5-8422-5166ca1a1fe9.png)

**Comment by Trubbel** [comment]
Adding issue, icon exists but needs an update.

**Comment by Trubbel** [comment]
Adding issue, icon exists but needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13510842/d8e02c32-e192-11e5-8422-5166ca1a1fe9.png)
https://cloud.githubusercontent.com/assets/2068130/13510842/d8e02c32-e192-11e5-8422-5166ca1a1fe9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13510859/e84bca00-e192-11e5-8865-8b152f233a5a.png
