### ISSUE TITLE
DART Around

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7288]
**App Name:** DART Around
**Bundle ID:** com.bazscott.DARTingAround
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=730876626">730876626</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dart-around/id730876626?mt=8&uo=4">https://itunes.apple.com/us/app/dart-around/id730876626?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Peer Assembly Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/peer-assembly/id331884363?uo=4>© Peer Assembly</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/cd/da/67/cdda6772-f96c-3e9b-874a-505a505d9bf5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13510629/b6800d02-e191-11e5-8856-88d431c89ab8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13510629/b6800d02-e191-11e5-8856-88d431c89ab8.png)
https://cloud.githubusercontent.com/assets/2068130/13510629/b6800d02-e191-11e5-8856-88d431c89ab8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13510647/c6089230-e191-11e5-813c-60cd1cf28b6f.png
