### ISSUE TITLE
FR24Premium

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7289]
**App Name:** FR24Premium
**Bundle ID:** com.flightradar24.FR24Premium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=766375562">766375562</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fr24premium/id766375562?mt=8&uo=4">https://itunes.apple.com/us/app/fr24premium/id766375562?mt=8&uo=4</a>
**App Version:** 6.6.0
**Seller:** Flightradar24 AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/flightradar24-ab/id726928879?uo=4>© Flightradar24 AB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/02/3c/88/023c88fa-8313-d7b4-6291-3b955490bcd4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13418738/7321e320-df78-11e5-8aeb-8d884d6827d4.png)

**Comment by Trubbel** [comment]
Same icon as #3654.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13418738/7321e320-df78-11e5-8aeb-8d884d6827d4.png)
https://cloud.githubusercontent.com/assets/2068130/13418738/7321e320-df78-11e5-8aeb-8d884d6827d4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13418749/8893f1d0-df78-11e5-9d8c-85b7d4e0cfdc.png
