### ISSUE TITLE
Nyan Cat: Lost In Space

### ISSUE THREAD

**Issue by forsterino** [glasklart/hd#729]
**App Name:** Nyan Cat: Lost In Space
**Bundle ID:** com.istomgames.nyan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=433592592">433592592</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nyan-cat-lost-in-space/id433592592?mt=8&uo=4">https://itunes.apple.com/us/app/nyan-cat-lost-in-space/id433592592?mt=8&uo=4</a>
**App Version:** 8.8
**Seller:** Istom Games Kft.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/istom-games-kft./id333561719?uo=4>© Istom Games Kft.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple41/v4/09/af/42/09af4292-f106-9b68-3179-105e8b6568d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18798782/7138325e-81d4-11e6-847f-19c2f38b6286.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18798782/7138325e-81d4-11e6-847f-19c2f38b6286.png)
https://cloud.githubusercontent.com/assets/2068130/18798782/7138325e-81d4-11e6-847f-19c2f38b6286.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18798793/7f688d92-81d4-11e6-993c-5823d1b84219.png
❓
