### ISSUE TITLE
Dublin Airport (Official)

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7292]
**App Name:** Dublin Airport (Official)
**Bundle ID:** com.dublinairportcom.dublinairport.PRODUCTNAMErfc1034identifier
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=411482375">411482375</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dublin-airport-official/id411482375?uo=4">https://apps.apple.com/us/app/dublin-airport-official/id411482375?uo=4</a>
**App Version:** 5.1.83
**Seller:** Dublin Airport Authority
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dublin-airport-authority/id411482378?uo=4">© Dublin Airport Authority</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/f3/ae/2c/f3ae2c50-426c-ae8e-45a8-8095b60017ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60386374-572e4c00-9a94-11e9-96e4-99e10bb02e68.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13412966/34b2a236-df47-11e5-903f-45ca723c68ad.png)
https://cloud.githubusercontent.com/assets/10730122/13412966/34b2a236-df47-11e5-903f-45ca723c68ad.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13412967/34c90ce2-df47-11e5-9935-5dcdb6be83af.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60386374-572e4c00-9a94-11e9-96e4-99e10bb02e68.png)
https://user-images.githubusercontent.com/2068130/60386374-572e4c00-9a94-11e9-96e4-99e10bb02e68.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60386381-67dec200-9a94-11e9-87fb-825e243a67f6.png
