### ISSUE TITLE
Dancing Evolution

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7295]
**App Name:** Dancing Evolution
**Bundle ID:** com.cff.dancerevolution
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=881185944">881185944</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dancing-evolution/id881185944?mt=8&uo=4">https://itunes.apple.com/us/app/dancing-evolution/id881185944?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Tuyen Pham
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tuyen-pham/id825701053?uo=4>© Tuyen Pham</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/51/1b/4a/511b4a09-43be-4f5e-6ecb-aee3a307176b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13519669/e9f8abe2-e1d9-11e5-8227-f19da93a74b3.png)

**Comment by dreamnet** [comment]
Oh, made also one...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13519669/e9f8abe2-e1d9-11e5-8227-f19da93a74b3.png)
https://cloud.githubusercontent.com/assets/2068130/13519669/e9f8abe2-e1d9-11e5-8227-f19da93a74b3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13519677/fa3cf5b2-e1d9-11e5-8f41-47498b918488.png

**Comment by Trubbel** [comment]
@dreamnet Yours definitely looks better!
