### ISSUE TITLE
My sizes - all sizes of clothes in your phone

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7297]
**App Name:** My sizes - all sizes of clothes in your phone
**Bundle ID:** com.victorsharov.mysizes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=990780687">990780687</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-sizes-all-sizes-clothes/id990780687?mt=8&uo=4">https://itunes.apple.com/us/app/my-sizes-all-sizes-clothes/id990780687?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Viktor Sharov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/viktor-sharov/id623238345?uo=4>© Viktor Sharov</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/5e/82/ea/5e82ea71-b3f2-ad28-433f-dac54c005855/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419653/24b91020-df80-11e5-8b86-3e878c9292cd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419653/24b91020-df80-11e5-8b86-3e878c9292cd.png)
https://cloud.githubusercontent.com/assets/2068130/13419653/24b91020-df80-11e5-8b86-3e878c9292cd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13419661/32e3f890-df80-11e5-8c58-306edfe03c75.png
