### ISSUE TITLE
My eyes - gymnastics and exercise for your eyes, train your vision

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7298]
**App Name:** My eyes - gymnastics and exercise for your eyes, train your vision
**Bundle ID:** com.ictorsharov.eyes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1030999687">1030999687</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-eyes-gymnastics-exercise/id1030999687?mt=8&uo=4">https://itunes.apple.com/us/app/my-eyes-gymnastics-exercise/id1030999687?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Viktor Sharov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/viktor-sharov/id623238345?uo=4>© Viktor Sharov</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/15/c7/a0/15c7a07e-0dde-85ca-2d05-87459b9b56b0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419598/af2f2c22-df7f-11e5-9ba2-c66d95503635.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419598/af2f2c22-df7f-11e5-9ba2-c66d95503635.png)
https://cloud.githubusercontent.com/assets/2068130/13419598/af2f2c22-df7f-11e5-9ba2-c66d95503635.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13419603/bf4553b6-df7f-11e5-8297-8bf10d1cfe71.png
