### ISSUE TITLE
Let's go! is a pedometer. The calculation of the walked distance: walking, running.

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7299]
**App Name:** Let's go! is a pedometer. The calculation of the walked distance: walking, running.
**Bundle ID:** com.victorsharov.letsgo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1019146718">1019146718</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lets-go!-is-pedometer.-calculation/id1019146718?mt=8&uo=4">https://itunes.apple.com/us/app/lets-go!-is-pedometer.-calculation/id1019146718?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Viktor Sharov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/viktor-sharov/id623238345?uo=4>© Viktor Sharov</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/95/c0/2b/95c02b56-a56b-5800-94ce-1c88fb46d608/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419529/21fe21aa-df7f-11e5-955e-9b76ca518ad8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419529/21fe21aa-df7f-11e5-955e-9b76ca518ad8.png)
https://cloud.githubusercontent.com/assets/2068130/13419529/21fe21aa-df7f-11e5-955e-9b76ca518ad8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13419537/3453bd06-df7f-11e5-8db6-304d64d7930f.png
