### ISSUE TITLE
Shoppi - your shopping list

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7300]
**App Name:** Shoppi - your shopping list
**Bundle ID:** com.victorsharov.whatbuy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=980908751">980908751</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shoppi-your-shopping-list/id980908751?mt=8&uo=4">https://itunes.apple.com/us/app/shoppi-your-shopping-list/id980908751?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Viktor Sharov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/viktor-sharov/id623238345?uo=4>© Viktor Sharov</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/9e/5f/44/9e5f440e-fd1a-689b-e227-4d56e15a2fd5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419442/9beae9fe-df7e-11e5-83d5-f28dd88d7734.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419442/9beae9fe-df7e-11e5-83d5-f28dd88d7734.png)
https://cloud.githubusercontent.com/assets/2068130/13419442/9beae9fe-df7e-11e5-83d5-f28dd88d7734.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13419454/abf1f2d4-df7e-11e5-9b9b-5792f7907de4.png
