### ISSUE TITLE
Super Sharp

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7301]
**App Name:** Super Sharp
**Bundle ID:** com.1button.supersharp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1033873301">1033873301</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-sharp/id1033873301?mt=8&uo=4">https://itunes.apple.com/us/app/super-sharp/id1033873301?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** 1Button SARL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/1button-sarl/id388888785?uo=4>© 1Button SARL</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/52/2f/34/522f3446-9fb4-2565-b464-480d8153e922/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419395/0cfd5042-df7e-11e5-95b3-2741dc39a1bc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419395/0cfd5042-df7e-11e5-95b3-2741dc39a1bc.png)
https://cloud.githubusercontent.com/assets/2068130/13419395/0cfd5042-df7e-11e5-95b3-2741dc39a1bc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13419399/1b83f38c-df7e-11e5-8fff-9c6dd1ce0532.png
