### ISSUE TITLE
Reshopper

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7302]
**App Name:** Reshopper
**Bundle ID:** com.reshopper.reshopper
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=551998942">551998942</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/reshopper/id551998942?mt=8&uo=4">https://itunes.apple.com/se/app/reshopper/id551998942?mt=8&uo=4</a>
**App Version:** 1.7.3
**Seller:** Reshopper ApS
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/developer/reshopper-aps/id551998945?uo=4>© Reshopper ApS</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/17/7c/8d/177c8d7a-15f9-e06b-1f0e-c98c3072e275/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13550108/211234c6-e316-11e5-9a9f-4a1c7105b33e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13519335/0169b9d6-e1d7-11e5-8d2f-9ded0f23d270.png)
https://cloud.githubusercontent.com/assets/2068130/13519335/0169b9d6-e1d7-11e5-8d2f-9ded0f23d270.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13519337/0f54d7ba-e1d7-11e5-8c02-760c34086a76.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13550108/211234c6-e316-11e5-9a9f-4a1c7105b33e.png)
https://cloud.githubusercontent.com/assets/2068130/13550108/211234c6-e316-11e5-9a9f-4a1c7105b33e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13550112/34816220-e316-11e5-8def-51879e08ab73.png
