### ISSUE TITLE
Quik - Free Video Editor - Make a quick music edit

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7304]
**App Name:** Quik - Free Video Editor - Make a quick music edit
**Bundle ID:** com.stupeflix.studio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=694164275">694164275</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quik-free-video-editor-make/id694164275?mt=8&uo=4">https://itunes.apple.com/us/app/quik-free-video-editor-make/id694164275?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** GoPro, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gopro-inc./id561350523?uo=4">© GoPro, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/4a/40/48/4a4048b6-f1ee-5228-abd1-02f9be8297a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/20045513/1957e02a-a4a2-11e6-8090-9b6700f4e739.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13433572/b1f17e62-dfd2-11e5-87cf-5c66e27d6e7d.png)
https://cloud.githubusercontent.com/assets/2068130/13433572/b1f17e62-dfd2-11e5-87cf-5c66e27d6e7d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13433583/c22741ea-dfd2-11e5-902e-9af4a9e4cf66.png

**Comment by dreamnet** [comment]
Icon is [already in the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.stupeflix.studio@2x.png). No further action needed.
