### ISSUE TITLE
HOUND - Voice Search & Assistant, hands-free speech recognition

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7306]
**App Name:** HOUND - Voice Search & Assistant, hands-free speech recognition
**Bundle ID:** com.hound.hound
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032432287">1032432287</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hound-voice-search-assistant/id1032432287?mt=8&uo=4">https://itunes.apple.com/us/app/hound-voice-search-assistant/id1032432287?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** SoundHound, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/soundhound-inc./id284973001?uo=4>© SoundHound, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/29/20/1e/29201e44-23c3-68be-e71b-546abf76cc79/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13510163/a3a17d44-e18f-11e5-8f30-ab086eb8d441.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13510163/a3a17d44-e18f-11e5-8f30-ab086eb8d441.png)
https://cloud.githubusercontent.com/assets/2068130/13510163/a3a17d44-e18f-11e5-8f30-ab086eb8d441.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13510176/b5847b74-e18f-11e5-89ee-143c4f3e1a5d.png
