### ISSUE TITLE
Facely HD for Facebook + Social Apps Browser

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7309]
**App Name:** Facely HD for Facebook + Social Apps Browser
**Bundle ID:** com.gwhizzapps.facebooktouchhd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=392550341">392550341</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facely-hd-for-facebook-+-social/id392550341?mt=8&uo=4">https://itunes.apple.com/us/app/facely-hd-for-facebook-+-social/id392550341?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** G-Whizz! Apps, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/g-whizz!-apps-llc/id332640794?uo=4>© G-Whizz! Apps, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/c5/d5/fb/c5d5fbd8-6fe4-d5f8-5e0d-20d8d3b1f1a9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13466488/72dcbe44-e09a-11e5-9580-3cab01cd2aee.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13466488/72dcbe44-e09a-11e5-9580-3cab01cd2aee.png)
https://cloud.githubusercontent.com/assets/10730122/13466488/72dcbe44-e09a-11e5-9580-3cab01cd2aee.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13466487/72dbf0ae-e09a-11e5-9ede-00b0fd00ec4b.png
