### ISSUE TITLE
Barstool Sports

### ISSUE THREAD

**Issue by jchotniks** [glasklart/hd#7310]
**App Name:** Barstool Sports
**Bundle ID:** com.Design-Menace.Barstool-Sports
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=456805313">456805313</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/barstool-sports/id456805313?mt=8&uo=4">https://itunes.apple.com/us/app/barstool-sports/id456805313?mt=8&uo=4</a>
**App Version:** 27.1.0
**Seller:** Barstool Sports Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/barstool-sports/id951911081?uo=4>© Barstool Sports</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/b9/73/93/b97393ec-ce36-bd5b-1d24-362d506a059c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13507767/774675b6-e184-11e5-90bc-d670ab7c6def.png)

**Comment by Trubbel** [comment]
@jchotniks There is no need to include "Icon Request" in the title of a new issue. Just include the name of the application (which you can find after "**App Name:**")

**Comment by jchotniks** [comment]
Yea sorry man, my first time and I'm not fantastic w those kinds of sites. I figured it out after I hit submit on the fourth one, which, I also think is already an "issue" and I just failed to find it.Apologies for that as well if that's the case. Seeking Alpha I think.                                                                                                                                                                                                                                                                                                                                        Best,Jeremy G. CohenRegistered RepresentativeIndependent Financial Group99 Summer Street, 13th FloorBoston, MA 02110Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: JimmySent: Wednesday, March 2, 2016 7:36 PMTo: glasklart/hdReply To: glasklart/hdCc: jchotniksSubject: Re: [hd] Barstool Sports (#7310)@jchotniks There is no need to include "Icon Request" in the title of a new issue. Just include the name of the application (which you can find after "App Name:")

—Reply to this email directly or view it on GitHub.

**Comment by Trubbel** [comment]
@jchotniks No worries, we all make mistakes - I'm glad you figured it out though. :smile:

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13507767/774675b6-e184-11e5-90bc-d670ab7c6def.png)
https://cloud.githubusercontent.com/assets/2068130/13507767/774675b6-e184-11e5-90bc-d670ab7c6def.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13507776/84be349a-e184-11e5-949e-adf12557a68d.png
