### ISSUE TITLE
mbtaGo - Boston MBTA Tracker, Finder, Schedule Assistant, and Alerts

### ISSUE THREAD

**Issue by jchotniks** [glasklart/hd#7311]
**App Name:** mbtaGo - Boston MBTA Tracker, Finder, Schedule Assistant, and Alerts
**Bundle ID:** com.lyker.transit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=983342044">983342044</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mbtago-boston-mbta-tracker/id983342044?mt=8&uo=4">https://itunes.apple.com/us/app/mbtago-boston-mbta-tracker/id983342044?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Steven Tso
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/steven-tso/id891194494?uo=4>© Steven Tso</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/ae/05/b2/ae05b29b-230a-cfcc-233a-d28b3723d3a1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13511409/e369392e-e15a-11e5-933c-94a6cd5a8a8b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13511409/e369392e-e15a-11e5-933c-94a6cd5a8a8b.png)
https://cloud.githubusercontent.com/assets/3090247/13511409/e369392e-e15a-11e5-933c-94a6cd5a8a8b.png
--- ---
https://cloud.githubusercontent.com/assets/3090247/13511410/e36ec9de-e15a-11e5-8309-d8dbce5e7bc9.png
