### ISSUE TITLE
Seeking Alpha Portfolio

### ISSUE THREAD

**Issue by jchotniks** [glasklart/hd#7312]
**App Name:** Seeking Alpha Portfolio
**Bundle ID:** com.seekingalpha.SeekingAlpha
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=552799694">552799694</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/seeking-alpha-portfolio/id552799694?mt=8&uo=4">https://itunes.apple.com/us/app/seeking-alpha-portfolio/id552799694?mt=8&uo=4</a>
**App Version:** 3.2.6
**Seller:** Seeking Alpha Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/seeking-alpha-ltd./id552799697?uo=4>© Seeking Alpha Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/ec/d0/f8/ecd0f822-86a2-6e5e-8721-11258d8b17e5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13486620/d3b21354-e112-11e5-9aff-7f989fb9bd4a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13486620/d3b21354-e112-11e5-9aff-7f989fb9bd4a.png)
https://cloud.githubusercontent.com/assets/2068130/13486620/d3b21354-e112-11e5-9aff-7f989fb9bd4a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13486626/e10e4180-e112-11e5-8587-bbc6538d25db.png
