### ISSUE TITLE
ParkBoston

### ISSUE THREAD

**Issue by jchotniks** [glasklart/hd#7313]
**App Name:** ParkBoston
**Bundle ID:** com.passportparking.mobile.parkboston
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953579075">953579075</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parkboston/id953579075?mt=8&uo=4">https://itunes.apple.com/us/app/parkboston/id953579075?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Passport Parking, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/passport-parking-llc/id501324970?uo=4>© Passport Parking, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/2c/74/3e/2c743edc-303d-150b-c812-77b0c914faaf/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13506607/3105ad92-e17f-11e5-8961-82290624dd7b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13506607/3105ad92-e17f-11e5-8961-82290624dd7b.png)
https://cloud.githubusercontent.com/assets/2068130/13506607/3105ad92-e17f-11e5-8961-82290624dd7b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13506617/40462976-e17f-11e5-8cda-8dd2574f5d34.png
