### ISSUE TITLE
Ibercaja Pay

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7314]
**App Name:** Ibercaja Pay
**Bundle ID:** es.cecabank.ealia2085appstore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1080621381">1080621381</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ibercaja-pay/id1080621381?mt=8&uo=4">https://itunes.apple.com/us/app/ibercaja-pay/id1080621381?mt=8&uo=4</a>
**App Version:** 1.0.16
**Seller:** IBERCAJA BANCO SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ibercaja/id515972022?uo=4>© Ibercaja</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/c7/97/52/c797525b-f03c-8fea-c667-f730488b34c0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13506481/9d652be4-e17e-11e5-9c71-e33a99d4af24.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13506481/9d652be4-e17e-11e5-9c71-e33a99d4af24.png)
https://cloud.githubusercontent.com/assets/2068130/13506481/9d652be4-e17e-11e5-9c71-e33a99d4af24.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13506490/ac1b73d2-e17e-11e5-9d19-27cacca17ef6.png
