### ISSUE TITLE
[the Sequence]

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7315]
**App Name:** [the Sequence]
**Bundle ID:** com.onemanband.thesequence
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035217840">1035217840</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-sequence/id1035217840?mt=8&uo=4">https://itunes.apple.com/us/app/the-sequence/id1035217840?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Maxim Urusov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/maxim-urusov/id827886412?uo=4>© Maxim Urusov</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/09/eb/ea/09ebeafd-47f7-90e9-cf72-90de1e408f9e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13504788/9ff2dbe2-e13b-11e5-8645-7f485ad6912d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13504788/9ff2dbe2-e13b-11e5-8645-7f485ad6912d.png)
https://cloud.githubusercontent.com/assets/3090247/13504788/9ff2dbe2-e13b-11e5-8645-7f485ad6912d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13504789/a00dde60-e13b-11e5-888e-52f16e2c0716.png

**Comment by dreamnet** [comment]
@ivanov007 :+1:
