### ISSUE TITLE
Merriam-Webster Dictionary & Thesaurus

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7317]
**App Name:** Merriam-Webster Dictionary & Thesaurus
**Bundle ID:** com.m-w.dictionary-premium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478126577">478126577</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/merriam-webster-dictionary/id478126577?mt=8&uo=4">https://itunes.apple.com/us/app/merriam-webster-dictionary/id478126577?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** Merriam-Webster, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/merriam-webster-inc./id399452290?uo=4>© Merriam-Webster, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/ed/87/3c/ed873c05-fca1-989c-48d8-1a92ff9b99f7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13547136/c659348a-e2c5-11e5-81fd-522eaebf08cf.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13547136/c659348a-e2c5-11e5-81fd-522eaebf08cf.png)
https://cloud.githubusercontent.com/assets/2068130/13547136/c659348a-e2c5-11e5-81fd-522eaebf08cf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13547138/d5eae402-e2c5-11e5-880a-17e638926429.png
