### ISSUE TITLE
TeamViewer QuickSupport

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7318]
**App Name:** TeamViewer QuickSupport
**Bundle ID:** com.teamviewer.teamviewerQS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=661649585">661649585</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/teamviewer-quicksupport/id661649585?mt=8&uo=4">https://itunes.apple.com/us/app/teamviewer-quicksupport/id661649585?mt=8&uo=4</a>
**App Version:** 10.0.50063
**Seller:** TeamViewer GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/teamviewer/id357051969?uo=4>© TeamViewer</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/55/0f/40/550f408d-e2a9-679c-829c-5b459018c90c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18817234/24b7e95e-835c-11e6-96ca-17df36289c9e.png)

**Comment by 2Qt2beStr8** [comment]
only a try ... but not perfect :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18730201/53d38400-8055-11e6-90f2-f9161bd6a5b2.png)
https://cloud.githubusercontent.com/assets/20930745/18730201/53d38400-8055-11e6-90f2-f9161bd6a5b2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18730242/85258b0c-8055-11e6-949e-f6556dd912c3.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Not bad, but the separation lines needs to be stronger.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18817234/24b7e95e-835c-11e6-96ca-17df36289c9e.png)
https://cloud.githubusercontent.com/assets/2068130/18817234/24b7e95e-835c-11e6-96ca-17df36289c9e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18817236/33621ce0-835c-11e6-9b46-aa2f3d674701.png
