### ISSUE TITLE
МГТС

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7319]
**App Name:** МГТС
**Bundle ID:** ru.mgts.lk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032406664">1032406664</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mgts/id1032406664?mt=8&uo=4">https://itunes.apple.com/us/app/mgts/id1032406664?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Mobile TeleSystems Public Joint Stock Company
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobile-telesystems-public/id406999351?uo=4>© Mobile TeleSystems Public Joint Stock Company</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/54/6a/c4/546ac4fb-4f3f-7eff-2b5a-4ca5fc4cae70/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13545850/aed29828-e299-11e5-83e2-da10513893df.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13545850/aed29828-e299-11e5-83e2-da10513893df.png)
https://cloud.githubusercontent.com/assets/2068130/13545850/aed29828-e299-11e5-83e2-da10513893df.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13545854/bd257b3e-e299-11e5-8188-7812fe48f9a0.png
