### ISSUE TITLE
Forecast Bar - Weather Powered by Forecast.io

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7320]
**App Name:** Forecast Bar - Weather Powered by Forecast.io
**Bundle ID:** com.rcg.forecastbarios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1057030968">1057030968</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/forecast-bar-weather-powered/id1057030968?mt=8&uo=4">https://itunes.apple.com/us/app/forecast-bar-weather-powered/id1057030968?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Real Casual Games, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/real-casual-games-llc/id495581007?uo=4>© Real Casual Games, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/fd/72/31/fd723124-cfb4-de0a-ce72-2f7939c09859/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13545805/496ccb44-e298-11e5-9703-7910208fed4c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13545805/496ccb44-e298-11e5-9703-7910208fed4c.png)
https://cloud.githubusercontent.com/assets/2068130/13545805/496ccb44-e298-11e5-9703-7910208fed4c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13545808/574b1ae0-e298-11e5-947a-8024fd2f7fa9.png
