### ISSUE TITLE
Whink

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7321]
**App Name:** Whink
**Bundle ID:** com.fluidtouch.whink
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1008546049">1008546049</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/whink/id1008546049?mt=8&uo=4">https://itunes.apple.com/us/app/whink/id1008546049?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Rama Krishna
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rama-krishna/id1008546048?uo=4>© Rama Krishna</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/03/ab/7c/03ab7c91-cb12-18b2-7568-f20523e3040b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13548738/89b01b66-e2f7-11e5-8de4-837eb52311c4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13548738/89b01b66-e2f7-11e5-8de4-837eb52311c4.png)
https://cloud.githubusercontent.com/assets/2068130/13548738/89b01b66-e2f7-11e5-8de4-837eb52311c4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13548742/98797f0c-e2f7-11e5-92d0-2ab4341d002d.png
