### ISSUE TITLE
Convertizo 3 - Convert Units and Currency in Style

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7322]
**App Name:** Convertizo 3 - Convert Units and Currency in Style
**Bundle ID:** com.perfectdimension.Convertizo-3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049725915">1049725915</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/convertizo-3-convert-units/id1049725915?mt=8&uo=4">https://itunes.apple.com/us/app/convertizo-3-convert-units/id1049725915?mt=8&uo=4</a>
**App Version:** 1.02
**Seller:** Paul Davis
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/perfect-dimension/id448146469?uo=4>© Perfect Dimension</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/b0/49/5e/b0495ef9-40d6-1b09-cb28-364e21260c71/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13548701/8c788c1c-e2f6-11e5-9e79-32f17206b028.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13548701/8c788c1c-e2f6-11e5-9e79-32f17206b028.png)
https://cloud.githubusercontent.com/assets/2068130/13548701/8c788c1c-e2f6-11e5-9e79-32f17206b028.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13548703/99eadbd4-e2f6-11e5-949b-b583be507a67.png
