### ISSUE TITLE
Read It Quick

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7323]
**App Name:** Read It Quick
**Bundle ID:** fr.indri.readitquick
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=962603085">962603085</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/read-it-quick/id962603085?mt=8&uo=4">https://itunes.apple.com/us/app/read-it-quick/id962603085?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Florent Crivello
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/florent-crivello/id470710844?uo=4>© Florent Crivello</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/1a/2c/3b/1a2c3bb2-91b4-5246-f0d0-5cde316193ec/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13548684/276cb690-e2f6-11e5-9b67-ce573577f34e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13548684/276cb690-e2f6-11e5-9b67-ce573577f34e.png)
https://cloud.githubusercontent.com/assets/2068130/13548684/276cb690-e2f6-11e5-9b67-ce573577f34e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13548690/353d85d8-e2f6-11e5-8fcb-51de8eaa99b8.png
