### ISSUE TITLE
QR Code Reader - QuickMark Barcode Scanner

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7324]
**App Name:** QR Code Reader - QuickMark Barcode Scanner
**Bundle ID:** tw.com.simpleact.quickmark4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=384883554">384883554</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qr-code-reader-quickmark-barcode/id384883554?mt=8&uo=4">https://itunes.apple.com/us/app/qr-code-reader-quickmark-barcode/id384883554?mt=8&uo=4</a>
**App Version:** 4.8.3
**Seller:** SimpleAct, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/simpleact-inc./id308650616?uo=4>© SimpleAct Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/b6/5e/fc/b65efc2b-0703-8d43-9fab-6783593be124/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13827688/8c939ea4-eb83-11e5-8fdb-c79e9fe29c0b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13827655/64464c6c-eb83-11e5-99ef-3a3fad7541a0.png)
https://cloud.githubusercontent.com/assets/3090247/13827655/64464c6c-eb83-11e5-99ef-3a3fad7541a0.png
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13827656/64474770-eb83-11e5-931d-45d76bc8e31e.png)
https://cloud.githubusercontent.com/assets/3090247/13827656/64474770-eb83-11e5-931d-45d76bc8e31e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13827658/64499e4e-eb83-11e5-9f3c-d179a1cb934e.png
https://cloud.githubusercontent.com/assets/3090247/13827657/6447701a-eb83-11e5-9646-52e6e179c144.png
