### ISSUE TITLE
ping4alerts!

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7325]
**App Name:** ping4alerts!
**Bundle ID:** com.ping4.ping4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=501990409">501990409</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ping4alerts!/id501990409?mt=8&uo=4">https://itunes.apple.com/us/app/ping4alerts!/id501990409?mt=8&uo=4</a>
**App Version:** 5.3.0
**Seller:** Ping4 Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ping4-inc./id468650046?uo=4>© Ping4 Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/f4/63/de/f463dec0-8c5c-d5d3-17f4-a42b57062662/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13724271/292d59a8-e846-11e5-901c-626dbd63f0c2.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13724271/292d59a8-e846-11e5-901c-626dbd63f0c2.png)
https://cloud.githubusercontent.com/assets/3090247/13724271/292d59a8-e846-11e5-901c-626dbd63f0c2.png
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13724272/294b8c16-e846-11e5-9546-a21833a3cd56.png)
https://cloud.githubusercontent.com/assets/3090247/13724272/294b8c16-e846-11e5-9546-a21833a3cd56.png
-- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13724273/29509738-e846-11e5-96c8-8f1aeced2af3.png
https://cloud.githubusercontent.com/assets/3090247/13724274/29526d74-e846-11e5-877b-26793bc19e43.png
