### ISSUE TITLE
FotoSwipe: File Phone Transfer

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7328]
**App Name:** FotoSwipe: File Phone Transfer
**Bundle ID:** com.fotoswipe.FotoSwipe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=828636068">828636068</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fotoswipe-file-phone-transfer/id828636068?uo=4">https://apps.apple.com/us/app/fotoswipe-file-phone-transfer/id828636068?uo=4</a>
**App Version:** 3.5.4
**Seller:** FOTOSWIPE INC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fotoswipe-inc/id921528306?uo=4">© FotoSwipe, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/4d/9a/86/4d9a863f-b96f-50d1-f11c-a56d8f59276d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60395097-9dd08480-9b2e-11e9-9b54-1d4cf409708b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13556617/bfdc70da-e3de-11e5-89d0-7fb93122300e.png)
https://cloud.githubusercontent.com/assets/2068130/13556617/bfdc70da-e3de-11e5-89d0-7fb93122300e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13556618/ce413e76-e3de-11e5-9222-5434f5d74e25.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60395097-9dd08480-9b2e-11e9-9b54-1d4cf409708b.png)
https://user-images.githubusercontent.com/2068130/60395097-9dd08480-9b2e-11e9-9b54-1d4cf409708b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60395104-ac1ea080-9b2e-11e9-9b08-4d65826b3e80.png
