### ISSUE TITLE
Thingthing Keyboard – Share your photos, documents, calendar and more without ever switching apps

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7329]
**App Name:** Thingthing Keyboard – Share your photos, documents, calendar and more without ever switching apps
**Bundle ID:** com.lateralinnovation.thingthing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=987945974">987945974</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/thingthing-keyboard-share/id987945974?mt=8&uo=4">https://itunes.apple.com/us/app/thingthing-keyboard-share/id987945974?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Thingthing LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/thingthing-ltd/id987945973?uo=4>© Thingthing LTD</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/34/31/6e/34316e35-dc0f-b3bd-b2d0-9d028b5bb8a0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14374358/12901d88-fd55-11e5-97bc-047700b24323.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14374358/12901d88-fd55-11e5-97bc-047700b24323.png)
https://cloud.githubusercontent.com/assets/2068130/14374358/12901d88-fd55-11e5-97bc-047700b24323.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14374361/20f29a7c-fd55-11e5-9670-6d32349464b1.png
