### ISSUE TITLE
Tuenti: Superpowers for your cell phone

### ISSUE THREAD

**Issue by alderz** [glasklart/hd#733]
**App Name:** Tuenti: Superpowers for your cell phone
**Bundle ID:** com.tuenti.nativeiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=349705795">349705795</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tuenti-superpowers-for-your/id349705795?mt=8&uo=4">https://itunes.apple.com/us/app/tuenti-superpowers-for-your/id349705795?mt=8&uo=4</a>
**App Version:** 8.1
**Seller:** Tuenti Technologies SL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tuenti-technologies-sl/id349705798?uo=4">© Tuenti Technologies SL</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/ec/c4/15/ecc4155a-c551-01d3-c4bb-919503cd5fe0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19967395/57dc123c-a1d0-11e6-9dd6-eb464132d17f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19967395/57dc123c-a1d0-11e6-9dd6-eb464132d17f.png)
https://cloud.githubusercontent.com/assets/20930745/19967395/57dc123c-a1d0-11e6-9dd6-eb464132d17f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19967425/6d091d08-a1d0-11e6-8817-f6b7134376e4.png
