### ISSUE TITLE
Jodel

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7330]
**App Name:** Jodel
**Bundle ID:** com.go-tellm.tellm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=789870026">789870026</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/hk/app/jodel/id789870026?mt=8&uo=4">https://itunes.apple.com/hk/app/jodel/id789870026?mt=8&uo=4</a>
**App Version:** 3.8
**Seller:** The Jodel Venture GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/hk/developer/the-jodel-venture-gmbh/id789870029?uo=4>© The Jodel Venture GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/6d/cc/b5/6dccb5f4-7f51-ae16-0f4e-625a15c23f8d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13556650/69b3685c-e3df-11e5-80fe-8061f4d2833d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13556650/69b3685c-e3df-11e5-80fe-8061f4d2833d.png)
https://cloud.githubusercontent.com/assets/2068130/13556650/69b3685c-e3df-11e5-80fe-8061f4d2833d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13556652/7a0445aa-e3df-11e5-91ca-ab95e36e1925.png
