### ISSUE TITLE
Anytime car

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7332]
**App Name:** Anytime car
**Bundle ID:** ru.anytimecar.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=633791132">633791132</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/anytime-car/id633791132?mt=8&uo=4">https://itunes.apple.com/us/app/anytime-car/id633791132?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Adv.Engine Group LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adv.engine-group-llc/id633791135?uo=4>© Adv.Engine Group LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/32/6c/60/326c6029-ba33-5342-2642-876016b7b8ce/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13722321/cab86efc-e841-11e5-8782-7f242e12dfd6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13722321/cab86efc-e841-11e5-8782-7f242e12dfd6.png)
https://cloud.githubusercontent.com/assets/2068130/13722321/cab86efc-e841-11e5-8782-7f242e12dfd6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13722323/d88bbae8-e841-11e5-8551-0ba7e8b04fc7.png
