### ISSUE TITLE
Social Square

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7333]
**App Name:** Social Square
**Bundle ID:** MySocialrfc1034identifier
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=687623816">687623816</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/social-square/id687623816?mt=8&uo=4">https://itunes.apple.com/us/app/social-square/id687623816?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Chase Giles
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chase-giles/id687549414?uo=4>© Chase Giles</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/8a/f2/e4/8af2e441-71c2-6c56-cfb0-1b1d335f1295/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13724499/4d480a0c-e84d-11e5-9c16-bb6a303f25bc.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13724499/4d480a0c-e84d-11e5-9c16-bb6a303f25bc.png)
https://cloud.githubusercontent.com/assets/3090247/13724499/4d480a0c-e84d-11e5-9c16-bb6a303f25bc.png
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13724500/4d4b8178-e84d-11e5-93e6-2e5b2315edc2.png)
https://cloud.githubusercontent.com/assets/3090247/13724500/4d4b8178-e84d-11e5-93e6-2e5b2315edc2.png
--- ---
Sources:
https://cloud.githubusercontent.com/assets/3090247/13724501/4d50cd36-e84d-11e5-919d-62d2c9fb7865.png
https://cloud.githubusercontent.com/assets/3090247/13724502/4d53976e-e84d-11e5-96e3-086329900342.png

**Comment by Anuskuss** [comment]
First one :+1:
