### ISSUE TITLE
Oloro

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7334]
**App Name:** Oloro
**Bundle ID:** com.mallowyn.olorogame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1086393047">1086393047</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/oloro/id1086393047?mt=8&uo=4">https://itunes.apple.com/us/app/oloro/id1086393047?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Regner Legacy LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mallowyn/id1086393046?uo=4>© Mallowyn</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/8b/a7/e1/8ba7e183-74d6-b6e9-fddc-a5c8d854b93c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13766235/63e7512c-ea60-11e5-93a3-8bc8ad9228b5.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13766235/63e7512c-ea60-11e5-93a3-8bc8ad9228b5.png)
https://cloud.githubusercontent.com/assets/10730122/13766235/63e7512c-ea60-11e5-93a3-8bc8ad9228b5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13766234/63e695d4-ea60-11e5-840e-dbd2d631af3b.png

**Comment by Anuskuss** [comment]
@Trubbel Why not fill the circles?
