### ISSUE TITLE
Stack

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7335]
**App Name:** Stack
**Bundle ID:** com.ketchapp.stack
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1080487957">1080487957</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stack/id1080487957?mt=8&uo=4">https://itunes.apple.com/us/app/stack/id1080487957?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Ketchapp
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ketchapp/id528065807?uo=4>© Ketchapp</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/06/54/b1/0654b160-8482-a3b9-5d6e-49d20f8de2fa/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13724791/ef035f60-e855-11e5-9366-1b01472bac0e.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13724732/3c0b4d10-e854-11e5-8058-fef635633ba8.png)
https://cloud.githubusercontent.com/assets/3090247/13724732/3c0b4d10-e854-11e5-8058-fef635633ba8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13724733/3c1694e0-e854-11e5-8381-0f20ab4e92fb.png

**Comment by dreamnet** [comment]
@ivanov007 :+1: Taking the second one.

**Comment by Anuskuss** [comment]
@ivanov007 Would it be possible to create the shades just like the original one?

**Comment by dreamnet** [comment]
@Anuskuss No. [Click.](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources)
