### ISSUE TITLE
WordWise by Memorado

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7336]
**App Name:** WordWise by Memorado
**Bundle ID:** com.memorado.words
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1059788922">1059788922</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wordwise-by-memorado/id1059788922?mt=8&uo=4">https://itunes.apple.com/us/app/wordwise-by-memorado/id1059788922?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Memorado GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/memorado/id897062512?uo=4>© Memorado</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/99/e8/5d/99e85dd8-a8f6-ba93-37a1-23cf04202374/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13722307/6026cdfe-e841-11e5-897d-dc64271cedea.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13722307/6026cdfe-e841-11e5-897d-dc64271cedea.png)
https://cloud.githubusercontent.com/assets/2068130/13722307/6026cdfe-e841-11e5-897d-dc64271cedea.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13722309/6de2a576-e841-11e5-8af6-3ce78c826a1d.png
