### ISSUE TITLE
GBA4iOS

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7337]
**App Name:** GBA4iOS
**Bundle ID:** com.rileytestut.enterprise.GBA4iOS
**Version:** 2.1
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/3090247/10578286/d20d5938-7636-11e5-87ab-6d905fe0bb84.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13726711/7aa851e6-e8d4-11e5-8860-c83a488a5b03.png)

**Comment by Anuskuss** [comment]
Same icon as #4150

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13726711/7aa851e6-e8d4-11e5-8860-c83a488a5b03.png)
https://cloud.githubusercontent.com/assets/2068130/13726711/7aa851e6-e8d4-11e5-8860-c83a488a5b03.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13726713/8dbfd196-e8d4-11e5-9000-f040e14c396f.png
