### ISSUE TITLE
Battery Life: check internal battery statistics

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7338]
**App Name:** Battery Life: check internal battery statistics
**Bundle ID:** com.rbtdigital.Battery-Life
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1080930585">1080930585</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/battery-life-check-internal/id1080930585?mt=8&uo=4">https://itunes.apple.com/us/app/battery-life-check-internal/id1080930585?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Robert Tkotzyk
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/robert-tkotzyk/id393534616?uo=4>© Robert Tkotzyk</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/6c/ee/6c/6cee6c0f-4adc-230c-25d0-9e7f35616ff3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13726915/97be6410-e8a1-11e5-8f90-67d19ca6005c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13726915/97be6410-e8a1-11e5-8f90-67d19ca6005c.png)
https://cloud.githubusercontent.com/assets/3090247/13726915/97be6410-e8a1-11e5-8f90-67d19ca6005c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13726916/98474744-e8a1-11e5-8543-90f6282dd4c3.png
