### ISSUE TITLE
Clash Royale

### ISSUE THREAD

**Issue by Meyers09** [glasklart/hd#7339]
**App Name:** Clash Royale
**Bundle ID:** com.supercell.scroll
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1053012308">1053012308</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clash-royale/id1053012308?mt=8&uo=4">https://itunes.apple.com/us/app/clash-royale/id1053012308?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Supercell Oy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/supercell/id488106216?uo=4">© Supercell</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/34/e0/ce/34e0ced0-117c-50d2-cae9-6ce7b896763a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20037570/7a9bed7a-a422-11e6-8ac8-0d6760943264.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20037570/7a9bed7a-a422-11e6-8ac8-0d6760943264.png)
https://cloud.githubusercontent.com/assets/2068130/20037570/7a9bed7a-a422-11e6-8ac8-0d6760943264.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20037572/87ffaa24-a422-11e6-86b3-4721ea015c6c.png
