### ISSUE TITLE
BADLAND 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7341]
**App Name:** BADLAND 2
**Bundle ID:** com.frogmindgames.badland2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1007120869">1007120869</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/badland-2/id1007120869?mt=8&uo=4">https://itunes.apple.com/us/app/badland-2/id1007120869?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Frogmind Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/frogmind/id535176912?uo=4>© Frogmind</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/6c/f5/70/6cf57066-d5b0-6f16-b8cd-d73286239534/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18031042/d50d3254-6cce-11e6-982d-01ee8faeadd1.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13765806/0dda70fa-ea5d-11e5-83f4-e6165643290b.png)
https://cloud.githubusercontent.com/assets/10730122/13765806/0dda70fa-ea5d-11e5-83f4-e6165643290b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13765807/0ddc20e4-ea5d-11e5-8639-bb0eeac9df3a.png

**Comment by Anuskuss** [comment]
@Trubbel Could you correct this little irregularities?
![](https://cloud.githubusercontent.com/assets/7157389/14052554/79c09ef4-f2cb-11e5-97ca-344e0d7d38d7.png)

**Comment by ivanov007** [comment]
@Anuskuss those irregularities are on the original artwork, so I don't think they need to be corrected

**Comment by Anuskuss** [comment]
Needs an update.

**Comment by Trubbel** [comment]
Don't know what else to do with this one..

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18031042/d50d3254-6cce-11e6-982d-01ee8faeadd1.png)
https://cloud.githubusercontent.com/assets/10730122/18031042/d50d3254-6cce-11e6-982d-01ee8faeadd1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18031043/d5113480-6cce-11e6-8f62-a3518db5bdac.png

**Comment by Anuskuss** [comment]
@Trubbel Looks good :+1:
