### ISSUE TITLE
Hilton Honors: Book Hotels

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7342]
**App Name:** Hilton Honors: Book Hotels
**Bundle ID:** com.hilton.hhonors
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=635150066">635150066</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hilton-honors-book-hotels/id635150066?uo=4">https://apps.apple.com/us/app/hilton-honors-book-hotels/id635150066?uo=4</a>
**App Version:** 3.21.0
**Seller:** Hilton Worldwide, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hilton-worldwide-inc/id337935129?uo=4">© Hilton Worldwide, Inc.</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/89/ae/4c/89ae4cb9-96a3-0427-da8b-2aa0733b5983/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772956-d7d8f200-a0fd-11e9-9e58-b36dee7be82b.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13826066/46c76cbe-eb7b-11e5-8b3d-c4848a3870bf.png)
https://cloud.githubusercontent.com/assets/3090247/13826066/46c76cbe-eb7b-11e5-8b3d-c4848a3870bf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13826067/46cf2238-eb7b-11e5-8905-ac6e58acfc5a.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772956-d7d8f200-a0fd-11e9-9e58-b36dee7be82b.png)
https://user-images.githubusercontent.com/2068130/60772956-d7d8f200-a0fd-11e9-9e58-b36dee7be82b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60772960-e7f0d180-a0fd-11e9-8def-f1ef58579be1.png
