### ISSUE TITLE
Almost Impossible!

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7345]
**App Name:** Almost Impossible!
**Bundle ID:** com.dancounsell.almostimpossible
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1045976470">1045976470</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/almost-impossible!/id1045976470?mt=8&uo=4">https://itunes.apple.com/us/app/almost-impossible!/id1045976470?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Daniel Counsell
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/daniel-counsell/id1045976469?uo=4>© Daniel Counsell</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/69/c8/e2/69c8e2da-0ae4-cf07-f23e-503954ab04a4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13766085/29cc831e-ea5f-11e5-909d-cf87cfb4409d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/13766085/29cc831e-ea5f-11e5-909d-cf87cfb4409d.png)
https://cloud.githubusercontent.com/assets/10730122/13766085/29cc831e-ea5f-11e5-909d-cf87cfb4409d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/13766084/29a7ab7a-ea5f-11e5-8104-3f016aeae3c6.png

**Comment by Anuskuss** [comment]
@Trubbel Could you remove the shadow lines and make the diagonal line in the boxes solid?
