### ISSUE TITLE
TomTom GO Mobile

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7346]
**App Name:** TomTom GO Mobile
**Bundle ID:** com.tomtom.itunes.navapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=884963367">884963367</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tomtom-go-mobile/id884963367?mt=8&uo=4">https://itunes.apple.com/us/app/tomtom-go-mobile/id884963367?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** TomTom
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tomtom/id326055452?uo=4>© TomTom</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/c8/ee/f2/c8eef2b2-123e-c975-adf5-e1608f080a54/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11011987/4304d736-84ee-11e5-8c57-221ae9f0a718.png)

**Comment by dreamnet** [comment]
Same as #6776.
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11011987/4304d736-84ee-11e5-8c57-221ae9f0a718.png)
https://cloud.githubusercontent.com/assets/2068130/11011987/4304d736-84ee-11e5-8c57-221ae9f0a718.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11011998/56bb3f68-84ee-11e5-88d9-4d18f9aa2a3b.png

**Comment by Anuskuss** [comment]
@dreamnet Wouldn't it be better to include the **TOMTOM** aswell? Since know it's just a car...

**Comment by dreamnet** [comment]
@Anuskuss No. Check this out: http://glasklarthd.dreamnet.at/index.php?search=tomtom&page=1 (there are currently 29 TomTom apps in the theme).

**Comment by Anuskuss** [comment]
@dreamnet Yeah I know, but since they're all using the same logo, you could edit the source and apply it to all of those apps. In my opinion it would look better if you include **TOMTOM**, but it's up to you.
