### ISSUE TITLE
Manything home security webcam with motion detector, alerts, and remote presence

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7347]
**App Name:** Manything home security webcam with motion detector, alerts, and remote presence
**Bundle ID:** com.manything.manything
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=639672976">639672976</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/manything-home-security-webcam/id639672976?mt=8&uo=4">https://itunes.apple.com/us/app/manything-home-security-webcam/id639672976?mt=8&uo=4</a>
**App Version:** 4.2.0
**Seller:** Manything Systems Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/manything/id639672979?uo=4>© Manything</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/15/7f/bc/157fbc65-b180-145a-6f82-122d90711a4c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13825875/545f5374-eb7a-11e5-8d16-432543a8fe09.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13825875/545f5374-eb7a-11e5-8d16-432543a8fe09.png)
https://cloud.githubusercontent.com/assets/3090247/13825875/545f5374-eb7a-11e5-8d16-432543a8fe09.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13825874/545b43f6-eb7a-11e5-9441-bf655bc25ad4.png
