### ISSUE TITLE
Alarm Clock 4 Free

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7348]
**App Name:** Alarm Clock 4 Free
**Bundle ID:** com.alarmclockcompany.alarmclock4free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406141511">406141511</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alarm-clock-4-free/id406141511?mt=8&uo=4">https://itunes.apple.com/us/app/alarm-clock-4-free/id406141511?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** Impala Studios B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/impala-studios/id1063279743?uo=4>© Impala Studios</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/bc/8e/2a/bc8e2a04-e68b-0631-7716-b7d3ef3400f3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18557292/adb4204c-7b6e-11e6-92d6-64cbf8e46936.png)

**Comment by 2Qt2beStr8** [comment]
only a try ... i can't do it better

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18557292/adb4204c-7b6e-11e6-92d6-64cbf8e46936.png)
https://cloud.githubusercontent.com/assets/20930745/18557292/adb4204c-7b6e-11e6-92d6-64cbf8e46936.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18557323/c2d3ffba-7b6e-11e6-95e9-3b0d5d9ffd25.png
