### ISSUE TITLE
PasswordWallet - Password Manager

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7349]
**App Name:** PasswordWallet - Password Manager
**Bundle ID:** GUEEHE5BYE.com.selznick.iPhone.PasswordWallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=295999660">295999660</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/passwordwallet-password-manager/id295999660?mt=8&uo=4">https://itunes.apple.com/us/app/passwordwallet-password-manager/id295999660?mt=8&uo=4</a>
**App Version:** 4.8.4
**Seller:** Selznick Scientific Software, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/selznick-scientific-software/id295999663?uo=4>© Selznick Scientific Software, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/c7/ba/52/c7ba5263-688b-b2c3-a95d-eadf94b3482a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14066240/81f87338-f444-11e5-89b7-c59d12a92aeb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14066240/81f87338-f444-11e5-89b7-c59d12a92aeb.png)
https://cloud.githubusercontent.com/assets/2068130/14066240/81f87338-f444-11e5-89b7-c59d12a92aeb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14066243/918b4b04-f444-11e5-8dde-fc3ab15b6b92.png
