### ISSUE TITLE
⋆FreeCell

### ISSUE THREAD

**Issue by allliee** [glasklart/hd#735]
**App Name:** ⋆FreeCell
**Bundle ID:** com.brainiumstudios.freecellfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504368649">504368649</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/freecell/id504368649?mt=8&uo=4">https://itunes.apple.com/us/app/freecell/id504368649?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Brainium Studios LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brainium-studios-llc/id300891405?uo=4>© Brainium Studios LLC</a>
**Supported Devices:** iPadThirdGen4G, iPhone5s, iPhone5, iPhone6Plus, iPadThirdGen, iPodTouchFifthGen, iPadMini4G, iPodTouchSixthGen, iPhone5c, iPad2Wifi, iPhone6, iPadFourthGen4G, iPadFourthGen, iPhone4, iPhone4S, iPhone-3GS, iPad23G, iPadMini, iPodTouchFourthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/f7/88/95/f788958a-ded8-8f88-80d2-2c6c90cc98c6/mzl.spvqfalz.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9513654/9f594dd0-4c92-11e5-9477-1cc9c85f573a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9513654/9f594dd0-4c92-11e5-9477-1cc9c85f573a.png)
https://cloud.githubusercontent.com/assets/2068130/9513654/9f594dd0-4c92-11e5-9477-1cc9c85f573a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9513659/ae88e536-4c92-11e5-83b0-22bfd3056cde.png
