### ISSUE TITLE
PlanetPootWaddle

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7350]
**App Name:** PlanetPootWaddle
**Bundle ID:** com.pooty
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=860116910">860116910</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/planetpootwaddle/id860116910?mt=8&uo=4">https://itunes.apple.com/us/app/planetpootwaddle/id860116910?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Frank Smith
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/frank-smith/id844331749?uo=4>© Frank Smith</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/74/d0/04/74d0044d-2b1f-a3d2-28c0-36bad94eb72e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18813768/18eb2c18-8306-11e6-9173-d5509fa344ec.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18813768/18eb2c18-8306-11e6-9173-d5509fa344ec.png)
https://cloud.githubusercontent.com/assets/20930745/18813768/18eb2c18-8306-11e6-9173-d5509fa344ec.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18813774/3003cdf6-8306-11e6-9572-31f6cc76bf20.png
