### ISSUE TITLE
Theodolite

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7352]
**App Name:** Theodolite
**Bundle ID:** com.hunter.theodolite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=339393884">339393884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/theodolite/id339393884?mt=8&uo=4">https://itunes.apple.com/us/app/theodolite/id339393884?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** Craig Hunter
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hunter-research-technology/id286743884?uo=4>© Hunter Research and Technology, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/13/ed/4e/13ed4ea2-b6dd-9274-51d6-d1cbee2be572/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19221597/d1788fa0-8e46-11e6-930d-4176c844182d.png)

**Comment by 2Qt2beStr8** [comment]
... whats about somethink like this? 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19221597/d1788fa0-8e46-11e6-930d-4176c844182d.png)
https://cloud.githubusercontent.com/assets/20930745/19221597/d1788fa0-8e46-11e6-930d-4176c844182d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19221608/0496ed14-8e47-11e6-820d-8bca18c872aa.png

**Comment by Sly-Fi** [comment]
I like it...

**Comment by dreamnet** [comment]
OK, Taken!
