### ISSUE TITLE
HotPads Rentals - Find Apartments & Homes for Rent

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7353]
**App Name:** HotPads Rentals - Find Apartments & Homes for Rent
**Bundle ID:** com.hotpads.hotpadsapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=345957475">345957475</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hotpads-rentals-find-apartments/id345957475?mt=8&uo=4">https://itunes.apple.com/us/app/hotpads-rentals-find-apartments/id345957475?mt=8&uo=4</a>
**App Version:** 3.9.8
**Seller:** Hotpads.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hotpads.com/id345957478?uo=4>© Hotpads.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/77/d5/cf/77d5cf15-fe1d-a490-aa18-01cd6da55c28/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13825709/7c6fe7da-eb79-11e5-8474-6c41e74f6a7d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13825709/7c6fe7da-eb79-11e5-8474-6c41e74f6a7d.png)
https://cloud.githubusercontent.com/assets/3090247/13825709/7c6fe7da-eb79-11e5-8474-6c41e74f6a7d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13825710/7c723c24-eb79-11e5-8da3-8beb64ce62af.png
