### ISSUE TITLE
BBVA Compass Mobile Banking

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7354]
**App Name:** BBVA Compass Mobile Banking
**Bundle ID:** com.bbvacompass.mobilebank
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=969671652">969671652</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bbva-compass-mobile-banking/id969671652?mt=8&uo=4">https://itunes.apple.com/us/app/bbva-compass-mobile-banking/id969671652?mt=8&uo=4</a>
**App Version:** 4.4
**Seller:** BBVA Compass
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bbva-compass/id319844004?uo=4>© BBVA Compass</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/12/24/6b/12246ba6-166b-e922-aa51-03366fd7467a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13825538/9d99d110-eb78-11e5-96d0-9dd544f518d7.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/13825538/9d99d110-eb78-11e5-96d0-9dd544f518d7.png)
https://cloud.githubusercontent.com/assets/3090247/13825538/9d99d110-eb78-11e5-96d0-9dd544f518d7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/13825539/9d9b7178-eb78-11e5-8f8c-586c440c8d85.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44625803-eec18c00-a911-11e8-876c-f4f8bb2c6ef6.png)
https://user-images.githubusercontent.com/2068130/44625803-eec18c00-a911-11e8-876c-f4f8bb2c6ef6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44625813-fda83e80-a911-11e8-8d4f-b8e88770480e.png
