### ISSUE TITLE
PulseMe

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7355]
**App Name:** PulseMe
**Bundle ID:** com.rambletta.ltd.PulseMe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=947343957">947343957</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pulseme/id947343957?mt=8&uo=4">https://itunes.apple.com/us/app/pulseme/id947343957?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Rambletta Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rambletta-ltd./id648854824?uo=4>© Rambletta Ltd.</a>
**Supported Devices:** iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/66/9d/26/669d26d7-a100-ddc1-ff55-5cf8fb6196df/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14030371/92a024ea-f207-11e5-9cf9-00d3b02b046d.png)

**Comment by TheRyanKing** [comment]
![com rambletta ltd pulseme 2x]

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/13799916/51a57fbc-eafa-11e5-9d8e-6bdfb942fce4.png)

![pulsemesource](https://cloud.githubusercontent.com/assets/10021829/13799935/78bfbfa4-eafa-11e5-88fc-bf6ec9143e54.png)

**Comment by TheRyanKing** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/13799944/8cfbcf76-eafa-11e5-83d4-62d77c13df78.png)

Source:
(https://cloud.githubusercontent.com/assets/10021829/13799953/9a710d6a-eafa-11e5-8ff8-d005b10c6943.png)

**Comment by ivanov007** [comment]
@TheRyanKing hey nice to see you back here, there's just one small detail with you source, the inside part of the 78x78 icon needs to be the full 1024x1024 pixels

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14030371/92a024ea-f207-11e5-9cf9-00d3b02b046d.png)
https://cloud.githubusercontent.com/assets/2068130/14030371/92a024ea-f207-11e5-9cf9-00d3b02b046d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14030380/a1f9d710-f207-11e5-8e0b-37388623e06e.png
