### ISSUE TITLE
Topo Maps

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7356]
**App Name:** Topo Maps
**Bundle ID:** org.chezphil.topomaps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306014271">306014271</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/topo-maps/id306014271?mt=8&uo=4">https://itunes.apple.com/us/app/topo-maps/id306014271?mt=8&uo=4</a>
**App Version:** 1.16
**Seller:** Philip Endecott
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/phil-endecott/id298854054?uo=4>© Phil Endecott</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/5c/4d/49/5c4d491e-073f-d4d5-7eb7-8d1f550db5ca/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18626267/2edf7c24-7e54-11e6-854b-10fb4cd014e6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18626267/2edf7c24-7e54-11e6-854b-10fb4cd014e6.png)
https://cloud.githubusercontent.com/assets/20930745/18626267/2edf7c24-7e54-11e6-854b-10fb4cd014e6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18626281/491e3e4a-7e54-11e6-8e7d-8ca737043001.png
