### ISSUE TITLE
По музеям

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7357]
**App Name:** По музеям
**Bundle ID:** su.bnet.MuseumEaters
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=877968704">877968704</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/po-muzeam/id877968704?mt=8&uo=4">https://itunes.apple.com/us/app/po-muzeam/id877968704?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** VLADISLAV KARPACHEV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vladislav-karpachev/id667567954?uo=4>© VLADISLAV KARPACHEV</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/74/82/55/7482552e-2445-7b42-875b-b333231e6a5b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13868019/2a3a20be-ecc5-11e5-9a34-5ff10d69706b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13868019/2a3a20be-ecc5-11e5-9a34-5ff10d69706b.png)
https://cloud.githubusercontent.com/assets/2068130/13868019/2a3a20be-ecc5-11e5-9a34-5ff10d69706b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13868024/39bca494-ecc5-11e5-9d7d-057b1b29b4a8.png
