### ISSUE TITLE
8bitWar: Apokalyps

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7358]
**App Name:** 8bitWar: Apokalyps
**Bundle ID:** com.emilzeilon.apps.8bitDragons
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937788787">937788787</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/8bitwar-apokalyps/id937788787?mt=8&uo=4">https://itunes.apple.com/us/app/8bitwar-apokalyps/id937788787?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Emil Zeilon
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/emil-zeilon/id591646413?uo=4>© Emil Zeilon</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/b6/7a/84/b67a8440-6269-7853-6ab2-0f4cd343f19d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14061335/48106520-f37e-11e5-9f93-68d33ddc1e17.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14061335/48106520-f37e-11e5-9f93-68d33ddc1e17.png)
https://cloud.githubusercontent.com/assets/2068130/14061335/48106520-f37e-11e5-9f93-68d33ddc1e17.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14061338/5674c002-f37e-11e5-8e14-bc0fc3652d3c.png
