### ISSUE TITLE
8bitWar: Necropolis

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7359]
**App Name:** 8bitWar: Necropolis
**Bundle ID:** com.emilzeilon.apps.8bitNecropolis
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=972045237">972045237</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/8bitwar-necropolis/id972045237?mt=8&uo=4">https://itunes.apple.com/us/app/8bitwar-necropolis/id972045237?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Emil Zeilon
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/emil-zeilon/id591646413?uo=4>© Emil Zeilon</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/22/00/9a/22009a0a-a4ed-19bc-6f34-31ac53391742/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14061288/c1cf119c-f37c-11e5-8072-b94538a52e04.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14061288/c1cf119c-f37c-11e5-8072-b94538a52e04.png)
https://cloud.githubusercontent.com/assets/2068130/14061288/c1cf119c-f37c-11e5-8072-b94538a52e04.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14061289/cf9791d2-f37c-11e5-92b2-1976d4608261.png
