### ISSUE TITLE
Feedly - your work newsfeed

### ISSUE THREAD

**Issue by nosoberty** [glasklart/hd#736]
**App Name:** Feedly - your work newsfeed
**Bundle ID:** com.devhd.feedly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=396069556">396069556</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/feedly-your-work-newsfeed/id396069556?mt=8&uo=4">https://itunes.apple.com/us/app/feedly-your-work-newsfeed/id396069556?mt=8&uo=4</a>
**App Version:** 36.0.0
**Seller:** DevHD Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/devhd/id396069559?uo=4>© DevHD</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple41/v4/ca/60/40/ca604006-4a10-d4c5-8cd1-1d80e7dd5883/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18747244/8393d038-80cc-11e6-8269-6594f4f59e1c.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18747244/8393d038-80cc-11e6-8269-6594f4f59e1c.png)
https://cloud.githubusercontent.com/assets/20930745/18747244/8393d038-80cc-11e6-8269-6594f4f59e1c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18747254/94618c3e-80cc-11e6-8b60-5c4a8d2482df.png

**Comment by 2Qt2beStr8** [comment]
if someone like it centered

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18747277/b939baea-80cc-11e6-877d-3c343fe570c2.png)
https://cloud.githubusercontent.com/assets/20930745/18747277/b939baea-80cc-11e6-877d-3c343fe570c2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18747291/cf66063e-80cc-11e6-9f31-f1e4bc15da5c.png

**Comment by dreamnet** [comment]
I go with the original.
