### ISSUE TITLE
BugSplosion

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7360]
**App Name:** BugSplosion
**Bundle ID:** com.emilzeilon.apps.bugsplosion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=634860812">634860812</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bugsplosion/id634860812?mt=8&uo=4">https://itunes.apple.com/us/app/bugsplosion/id634860812?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Emil Zeilon
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/emil-zeilon/id591646413?uo=4>© Emil Zeilon</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple2/v4/e1/1b/ee/e11beec8-20fe-ff80-8e17-485c58561ad7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13868127/21f54c70-ecc6-11e5-916c-fef421a79aa5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13868127/21f54c70-ecc6-11e5-916c-fef421a79aa5.png)
https://cloud.githubusercontent.com/assets/2068130/13868127/21f54c70-ecc6-11e5-916c-fef421a79aa5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13868134/34cf9e68-ecc6-11e5-8df7-5c63f45a6f79.png
