### ISSUE TITLE
8bitWar: Origins

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7361]
**App Name:** 8bitWar: Origins
**Bundle ID:** com.emilzeilon.apps.8bitwar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=890932971">890932971</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/8bitwar-origins/id890932971?mt=8&uo=4">https://itunes.apple.com/us/app/8bitwar-origins/id890932971?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Emil Zeilon
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/emil-zeilon/id591646413?uo=4>© Emil Zeilon</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/79/60/00/79600070-8b5e-486c-d1fc-ab07be39bbf1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14061143/fa56cec8-f378-11e5-9baf-d9d4115e9239.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14061143/fa56cec8-f378-11e5-9baf-d9d4115e9239.png)
https://cloud.githubusercontent.com/assets/2068130/14061143/fa56cec8-f378-11e5-9baf-d9d4115e9239.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14061145/08d7ef18-f379-11e5-9897-4f11f34fa7f2.png
