### ISSUE TITLE
8bitWar: Netherworld

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7362]
**App Name:** 8bitWar: Netherworld
**Bundle ID:** com.emilzeilon.apps.ReadySetTap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=827101160">827101160</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/8bitwar-netherworld/id827101160?mt=8&uo=4">https://itunes.apple.com/us/app/8bitwar-netherworld/id827101160?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Emil Zeilon
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/emil-zeilon/id591646413?uo=4>© Emil Zeilon</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/57/21/50/572150ff-af4d-7b49-d23f-1ceb1c57f653/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14060635/1330d65e-f36b-11e5-8057-bd821c816aff.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14060635/1330d65e-f36b-11e5-8057-bd821c816aff.png)
https://cloud.githubusercontent.com/assets/2068130/14060635/1330d65e-f36b-11e5-8057-bd821c816aff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14060637/20f00f6c-f36b-11e5-8ddf-5a6e0cfc7bc7.png
