### ISSUE TITLE
8bitWar: Steampunk

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7363]
**App Name:** 8bitWar: Steampunk
**Bundle ID:** com.emilzeilon.apps.8bitAsgard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=969791191">969791191</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/8bitwar-steampunk/id969791191?mt=8&uo=4">https://itunes.apple.com/us/app/8bitwar-steampunk/id969791191?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Emil Zeilon
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/emil-zeilon/id591646413?uo=4>© Emil Zeilon</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/5e/d9/0f/5ed90f58-83a6-69f5-a95f-c01f6875e2c2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14059105/f27f1106-f337-11e5-92dc-0fcd3e5d473c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14059105/f27f1106-f337-11e5-92dc-0fcd3e5d473c.png)
https://cloud.githubusercontent.com/assets/2068130/14059105/f27f1106-f337-11e5-92dc-0fcd3e5d473c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14059107/022d2638-f338-11e5-9004-5e8c70886112.png
