### ISSUE TITLE
Calvertr2 - Calculator with Converter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7364]
**App Name:** Calvertr2 - Calculator with Converter
**Bundle ID:** com.r3app.calvertr2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1046473926">1046473926</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calvertr2-calculator-converter/id1046473926?mt=8&uo=4">https://itunes.apple.com/us/app/calvertr2-calculator-converter/id1046473926?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** ReasonX, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/reasonx-inc./id814917963?uo=4>© ReasonX, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/6f/76/83/6f768399-0da6-ddd9-34c9-0170e3e8794e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14030260/10b43250-f207-11e5-8884-063ba79e991a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14030260/10b43250-f207-11e5-8884-063ba79e991a.png)
https://cloud.githubusercontent.com/assets/2068130/14030260/10b43250-f207-11e5-8884-063ba79e991a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14030275/2088b7a0-f207-11e5-8b61-fc685bc0aaf2.png
