### ISSUE TITLE
Beam - Real Time News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7365]
**App Name:** Beam - Real Time News
**Bundle ID:** com.stratoray.BeamNews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1044875603">1044875603</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beam-real-time-news/id1044875603?mt=8&uo=4">https://itunes.apple.com/us/app/beam-real-time-news/id1044875603?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Stratoray OOD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stratoray/id1044875602?uo=4>© Stratoray</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/8e/ab/b4/8eabb452-ff4a-5390-0124-5583253791a9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14030141/61d91200-f206-11e5-8dce-7c25433aac22.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14030141/61d91200-f206-11e5-8dce-7c25433aac22.png)
https://cloud.githubusercontent.com/assets/2068130/14030141/61d91200-f206-11e5-8dce-7c25433aac22.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14030150/7111f520-f206-11e5-8429-84c9603ee400.png
