### ISSUE TITLE
Algo: Real-time news

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7366]
**App Name:** Algo: Real-time news
**Bundle ID:** com.skygrid.skygrid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364187929">364187929</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/algo-real-time-news/id364187929?mt=8&uo=4">https://itunes.apple.com/us/app/algo-real-time-news/id364187929?mt=8&uo=4</a>
**App Version:** 3.1.8
**Seller:** Algo, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/algo-llc/id364187932?uo=4>© Algo, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple71/v4/98/2d/10/982d10c2-8707-9666-7fd5-7dcdcbdb12fd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193619/aad0a9d4-70df-11e6-8d40-5b26e4d832f1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14029767/4e03ca74-f204-11e5-9936-e0a4ef18a884.png)
https://cloud.githubusercontent.com/assets/2068130/14029767/4e03ca74-f204-11e5-9936-e0a4ef18a884.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14029781/5db48cba-f204-11e5-8e6b-19dbfa1665ba.png

**Comment by l8er4now** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193619/aad0a9d4-70df-11e6-8d40-5b26e4d832f1.png)
https://cloud.githubusercontent.com/assets/2068130/18193619/aad0a9d4-70df-11e6-8d40-5b26e4d832f1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18193623/baf72cca-70df-11e6-955e-eb2e968946dc.png
