### ISSUE TITLE
Neweer

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7367]
**App Name:** Neweer
**Bundle ID:** com.Alexandr-Rubin.Neweer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916548745">916548745</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/neweer/id916548745?mt=8&uo=4">https://itunes.apple.com/us/app/neweer/id916548745?mt=8&uo=4</a>
**App Version:** 1.2.5
**Seller:** Alexandr Rubin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alexandr-rubin/id846818916?uo=4>© Alexandr Rubin</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/e1/38/d2/e138d224-c3e4-6813-39b4-848475f01a4e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14029667/b21b4f56-f203-11e5-9cdd-ba7377b754b7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14029667/b21b4f56-f203-11e5-9cdd-ba7377b754b7.png)
https://cloud.githubusercontent.com/assets/2068130/14029667/b21b4f56-f203-11e5-9cdd-ba7377b754b7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14029674/c13b0526-f203-11e5-9714-6ab84dfc57ac.png
