### ISSUE TITLE
Foxit PDF - PDF reader, editor with Office doc and txt preview

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7368]
**App Name:** Foxit PDF - PDF reader, editor with Office doc and txt preview
**Bundle ID:** com.foxitcorporation.reader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507040546">507040546</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/foxit-pdf-pdf-reader-editor/id507040546?mt=8&uo=4">https://itunes.apple.com/us/app/foxit-pdf-pdf-reader-editor/id507040546?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Foxit Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/foxit-corporation/id386527261?uo=4>© Foxit Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/d8/da/67/d8da6743-5f92-10ff-fd19-410d9801ebc8/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14063996/8f0e31d0-f3ee-11e5-931d-2979327479c6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14063996/8f0e31d0-f3ee-11e5-931d-2979327479c6.png)
https://cloud.githubusercontent.com/assets/2068130/14063996/8f0e31d0-f3ee-11e5-931d-2979327479c6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14064001/9f8730ac-f3ee-11e5-9df9-542989517c8d.png
