### ISSUE TITLE
VOX – Music Player for FLAC & MP3, SoundCloud, YouTube

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7369]
**App Name:** VOX – Music Player for FLAC & MP3, SoundCloud, YouTube
**Bundle ID:** com.coppertino.VoxMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916215494">916215494</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vox-music-player-for-flac/id916215494?mt=8&uo=4">https://itunes.apple.com/us/app/vox-music-player-for-flac/id916215494?mt=8&uo=4</a>
**App Version:** 1.6.1
**Seller:** Coppertino Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/coppertino-inc./id410801091?uo=4>© Coppertino Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple22/v4/f3/01/83/f3018362-ec40-5d02-5901-d15dafc05685/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18104292/ca2e3ecc-6efa-11e6-83aa-758100dc9b49.png)

**Comment by alpcinar** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13483942/18027257/df20d410-6c67-11e6-82de-4048bd231f43.png)
https://cloud.githubusercontent.com/assets/13483942/18027257/df20d410-6c67-11e6-82de-4048bd231f43.png

Source:
https://cloud.githubusercontent.com/assets/13483942/18027261/ed7ee7cc-6c67-11e6-95c8-b451b4cda8d2.png
