### ISSUE TITLE
Letterboxd – The social network for film lovers

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7370]
**App Name:** Letterboxd – The social network for film lovers
**Bundle ID:** com.letterboxd.LetterboxdApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1054271011">1054271011</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/letterboxd-social-network/id1054271011?mt=8&uo=4">https://itunes.apple.com/us/app/letterboxd-social-network/id1054271011?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Letterboxd Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/letterboxd/id1054271010?uo=4>© Letterboxd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/4e/f8/ba/4ef8bab3-05d9-5804-3774-3a81d43849fe/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14066116/0fabb29c-f442-11e5-9fd2-b4d910349b97.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14066116/0fabb29c-f442-11e5-9fd2-b4d910349b97.png)
https://cloud.githubusercontent.com/assets/2068130/14066116/0fabb29c-f442-11e5-9fd2-b4d910349b97.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14066121/200e6580-f442-11e5-865d-71bd819a9348.png
