### ISSUE TITLE
Berry News - Today News, World & Trend News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7371]
**App Name:** Berry News - Today News, World & Trend News
**Bundle ID:** com.news.berry
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1087786486">1087786486</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/berry-news-today-news-world-trend-news/id1087786486?mt=8&uo=4">https://itunes.apple.com/us/app/berry-news-today-news-world-trend-news/id1087786486?mt=8&uo=4</a>
**App Version:** 1.8.0
**Seller:** Taner Parcali
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/timix-app-studio/id451039173?uo=4">© Timix App Studio</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple122/v4/4d/1d/0b/4d1d0bbd-ed5d-f0cc-a6a8-cdb56f4a6c97/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626470-4a454700-a91d-11e8-8292-7cfe30b199b9.png)

**Comment by l8er4now** [comment]
Icon has been updated.

**App Name:** Berry News - Breaking National, World News, Rss Reader
**Bundle ID:** com.news.berry
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1087786486">1087786486</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/berry-news-breaking-national/id1087786486?mt=8&uo=4">https://itunes.apple.com/us/app/berry-news-breaking-national/id1087786486?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** Taner Parcali
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/timix-app-studio/id451039173?uo=4>© Timix App Studio</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/fa/fb/e4/fafbe499-db3b-c62f-46d3-198a03d329c4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14374492/a8ff4860-fd56-11e5-937e-f552975fa1cd.png)
https://cloud.githubusercontent.com/assets/2068130/14374492/a8ff4860-fd56-11e5-937e-f552975fa1cd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14374499/b7ecc640-fd56-11e5-9953-2980fa75bc87.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626470-4a454700-a91d-11e8-8292-7cfe30b199b9.png)
https://user-images.githubusercontent.com/2068130/44626470-4a454700-a91d-11e8-8292-7cfe30b199b9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44626475-58936300-a91d-11e8-996a-e3a9eb7dcedd.png
