### ISSUE TITLE
PipSpin

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7372]
**App Name:** PipSpin
**Bundle ID:** com.MatthewBurton.PipSpin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1071705747">1071705747</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pipspin/id1071705747?mt=8&uo=4">https://itunes.apple.com/us/app/pipspin/id1071705747?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Matthew Burton
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/matthew-burton/id953832108?uo=4>© Matthew Burton</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/ff/e6/5f/ffe65f44-32dd-2aac-29cb-3aa9071a083d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14064024/33d0ad96-f3f0-11e5-9cca-07db49a70036.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14064024/33d0ad96-f3f0-11e5-9cca-07db49a70036.png)
https://cloud.githubusercontent.com/assets/2068130/14064024/33d0ad96-f3f0-11e5-9cca-07db49a70036.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14064025/49f020e8-f3f0-11e5-8c2d-2f1562827528.png
