### ISSUE TITLE
ecobee

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7374]
**App Name:** ecobee
**Bundle ID:** com.ecobee.athenamobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916985674">916985674</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ecobee/id916985674?uo=4">https://apps.apple.com/us/app/ecobee/id916985674?uo=4</a>
**App Version:** 7.32.0
**Seller:** ecobee
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ecobee/id339159188?uo=4">© ecobee</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/15/3a/b4/153ab477-0c23-ade4-6eac-9c4e5f07a3fb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632745-8e740380-8161-11ea-8df9-33b4503c9c02.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14063980/dd01920c-f3ed-11e5-8be5-45373d9053da.png)
https://cloud.githubusercontent.com/assets/2068130/14063980/dd01920c-f3ed-11e5-8be5-45373d9053da.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14063983/efbca1c0-f3ed-11e5-8c77-22e64e9bfd39.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** ecobee
**Bundle ID:** com.ecobee.athenamobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916985674">916985674</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ecobee/id916985674?uo=4">https://apps.apple.com/us/app/ecobee/id916985674?uo=4</a>
**App Version:** 7.32.0
**Seller:** ecobee
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ecobee/id339159188?uo=4">© ecobee</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/15/3a/b4/153ab477-0c23-ade4-6eac-9c4e5f07a3fb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/79632745-8e740380-8161-11ea-8df9-33b4503c9c02.png)
https://user-images.githubusercontent.com/2068130/79632745-8e740380-8161-11ea-8df9-33b4503c9c02.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/79632761-9d5ab600-8161-11ea-94b1-fbdab0dc86b1.png
