### ISSUE TITLE
Yidio: TV Show & Movie Guide

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7375]
**App Name:** Yidio: TV Show & Movie Guide
**Bundle ID:** com.yidio.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=664306931">664306931</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yidio-tv-show-movie-guide/id664306931?mt=8&uo=4">https://itunes.apple.com/us/app/yidio-tv-show-movie-guide/id664306931?mt=8&uo=4</a>
**App Version:** 2.6.19
**Seller:** Yidio LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yidio-llc/id664306934?uo=4>© Yidio LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/16/ba/eb/16baeb8a-0208-eb49-6786-031cf372ac6c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14224568/83a91db6-f8a1-11e5-9510-6831851e5ce0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14224568/83a91db6-f8a1-11e5-9510-6831851e5ce0.png)
https://cloud.githubusercontent.com/assets/2068130/14224568/83a91db6-f8a1-11e5-9510-6831851e5ce0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14224569/93528068-f8a1-11e5-88eb-fb65162c8b7a.png
