### ISSUE TITLE
Ezzi Home: Control for HomeKit-connected devices

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7376]
**App Name:** Ezzi Home: Control for HomeKit-connected devices
**Bundle ID:** com.abrt.homekit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1039845950">1039845950</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ezzi-home-control-for-homekit/id1039845950?mt=8&uo=4">https://itunes.apple.com/us/app/ezzi-home-control-for-homekit/id1039845950?mt=8&uo=4</a>
**App Version:** 0.9.3
**Seller:** WAYD LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wayd-llc/id1064283002?uo=4>© WAYD LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/74/44/36/74443640-2f84-c0de-5ca2-4d6b4e4f3b90/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14066155/e48a68b4-f442-11e5-83a7-0848b5f38efe.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14066155/e48a68b4-f442-11e5-83a7-0848b5f38efe.png)
https://cloud.githubusercontent.com/assets/2068130/14066155/e48a68b4-f442-11e5-83a7-0848b5f38efe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14066159/f538815a-f442-11e5-9e7d-8e091e057ab5.png
