### ISSUE TITLE
Chicago Works 311 - Report Potholes, Graffiti and other Non-Emergency Issues to your City

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7377]
**App Name:** Chicago Works 311 - Report Potholes, Graffiti and other Non-Emergency Issues to your City
**Bundle ID:** com.2pensmedia.ChicagoWorks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=385798918">385798918</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chicago-works-311-report-potholes/id385798918?mt=8&uo=4">https://itunes.apple.com/us/app/chicago-works-311-report-potholes/id385798918?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** 2pensmedia Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/2pensmedia-inc./id320588044?uo=4>© 2pensmedia Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/e8/66/d2/e866d278-80a8-c611-1527-fd0ea9443456/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19007548/d3330af6-8765-11e6-8942-d32fd3a89865.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19007548/d3330af6-8765-11e6-8942-d32fd3a89865.png)
https://cloud.githubusercontent.com/assets/20930745/19007548/d3330af6-8765-11e6-8942-d32fd3a89865.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19007586/08c2abfe-8766-11e6-8a4a-21f678ccfeed.png
