### ISSUE TITLE
Rolo Calendar - a different perspective on life

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7378]
**App Name:** Rolo Calendar - a different perspective on life
**Bundle ID:** com.rebelminds.rolo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1042011386">1042011386</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rolo-calendar-different-perspective/id1042011386?mt=8&uo=4">https://itunes.apple.com/us/app/rolo-calendar-different-perspective/id1042011386?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Rebel Minds Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rebel-minds/id1042011385?uo=4>© Rebel Minds</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/1a/1d/bd/1a1dbd29-0dc6-5046-68c7-737d4fd68132/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14231254/40f80e74-f97c-11e5-9d2b-b90d4cf52212.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14231254/40f80e74-f97c-11e5-9d2b-b90d4cf52212.png)
https://cloud.githubusercontent.com/assets/2068130/14231254/40f80e74-f97c-11e5-9d2b-b90d4cf52212.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14231256/4fa50d64-f97c-11e5-8ae0-8e5782dae5c6.png
