### ISSUE TITLE
Epic Rap Battles

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7379]
**App Name:** Epic Rap Battles
**Bundle ID:** com.maker.erb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=604268050">604268050</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/epic-rap-battles/id604268050?mt=8&uo=4">https://itunes.apple.com/us/app/epic-rap-battles/id604268050?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Maker Studios, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/maker-studios/id434023774?uo=4>© Maker Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/b2/b3/7c/b2b37cfc-1e34-f4b7-2652-9c1e2c660f1b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14231202/d41dbade-f97a-11e5-9862-7f39aaae333a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14231202/d41dbade-f97a-11e5-9862-7f39aaae333a.png)
https://cloud.githubusercontent.com/assets/2068130/14231202/d41dbade-f97a-11e5-9862-7f39aaae333a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14231206/e29dde9a-f97a-11e5-87e0-c5ea1d6be536.png
