### ISSUE TITLE
WorldCard Mobile - business card reader & business card scanner

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7380]
**App Name:** WorldCard Mobile - business card reader & business card scanner
**Bundle ID:** com.penpower.worldcardmobileen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=333211045">333211045</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/worldcard-mobile-business/id333211045?mt=8&uo=4">https://itunes.apple.com/us/app/worldcard-mobile-business/id333211045?mt=8&uo=4</a>
**App Version:** 7.1.0
**Seller:** Penpower Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/penpower-technology-ltd./id333211048?uo=4>© Penpower Technology Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/dd/58/73/dd5873ed-7dd0-1616-8f41-058f47827261/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18761218/588edb02-8104-11e6-8e81-70a8d65cd95a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18761218/588edb02-8104-11e6-8e81-70a8d65cd95a.png)
https://cloud.githubusercontent.com/assets/20930745/18761218/588edb02-8104-11e6-8e81-70a8d65cd95a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18761233/69193a9e-8104-11e6-861f-bc1d4712acc5.png
