### ISSUE TITLE
NCAA March Madness Live

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7381]
**App Name:** NCAA March Madness Live
**Bundle ID:** com.turner.mmod2011temp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=423246594">423246594</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ncaa-march-madness-live/id423246594?mt=8&uo=4">https://itunes.apple.com/us/app/ncaa-march-madness-live/id423246594?mt=8&uo=4</a>
**App Version:** 6.0.3
**Seller:** Turner Sports
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ncaa-digital/id423855728?uo=4>© NCAA Digital</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/74/18/47/7418477b-5dbc-2bfe-676e-839165f2e5b1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14334755/36ccf926-fc1c-11e5-8764-e23632724f6e.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14334755/36ccf926-fc1c-11e5-8764-e23632724f6e.png)
https://cloud.githubusercontent.com/assets/3090247/14334755/36ccf926-fc1c-11e5-8764-e23632724f6e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14334756/36cd7446-fc1c-11e5-99da-427bda6c7f92.png
