### ISSUE TITLE
Пунктуация

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7382]
**App Name:** Пунктуация
**Bundle ID:** com.prismalogic.punctuation
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=565697609">565697609</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/punktuacia/id565697609?mt=8&uo=4">https://itunes.apple.com/us/app/punktuacia/id565697609?mt=8&uo=4</a>
**App Version:** 1.7.3
**Seller:** Stanislav Smagin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/prismalogic/id565697612?uo=4>© Prismalogic</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/b2/35/33/b235330c-75f2-f864-f9a6-8f775f65a401/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14230626/50af74cc-f960-11e5-925b-25914eed74cc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14230626/50af74cc-f960-11e5-925b-25914eed74cc.png)
https://cloud.githubusercontent.com/assets/2068130/14230626/50af74cc-f960-11e5-925b-25914eed74cc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14230628/5f1cbeca-f960-11e5-81df-2d5c23c41d83.png
