### ISSUE TITLE
Орфогрaфия

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7383]
**App Name:** Орфогрaфия
**Bundle ID:** com.prismalogic.spellingGame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586448083">586448083</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/orfografia/id586448083?mt=8&uo=4">https://itunes.apple.com/us/app/orfografia/id586448083?mt=8&uo=4</a>
**App Version:** 3.3.5
**Seller:** Stanislav Smagin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/prismalogic/id565697612?uo=4>© Prismalogic</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple2/v4/ac/e3/34/ace334fe-98aa-4bd2-9a90-75ecf891d163/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14230689/bc92cf4e-f961-11e5-9041-57bbeb60a8d2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14230689/bc92cf4e-f961-11e5-9041-57bbeb60a8d2.png)
https://cloud.githubusercontent.com/assets/2068130/14230689/bc92cf4e-f961-11e5-9041-57bbeb60a8d2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14230691/d1e516b8-f961-11e5-9964-99e847f1f61a.png
