### ISSUE TITLE
Грамотей! -викторина орфографии

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7384]
**App Name:** Грамотей! -викторина орфографии
**Bundle ID:** ru.allyteam.gramotei
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=662552813">662552813</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gramotej!-viktorina-orfografii/id662552813?mt=8&uo=4">https://itunes.apple.com/us/app/gramotej!-viktorina-orfografii/id662552813?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** Nekhoroshev Ilya
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nekhoroshev-ilya/id662552816?uo=4>© Nekhoroshev Ilya</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/c3/10/1e/c3101e8f-47d9-14cd-044b-61931ef559a3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18404059/9bed5c00-76e8-11e6-958e-005087dd1714.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18404059/9bed5c00-76e8-11e6-958e-005087dd1714.png)
https://cloud.githubusercontent.com/assets/20930745/18404059/9bed5c00-76e8-11e6-958e-005087dd1714.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18404067/af467ade-76e8-11e6-9d14-5069f8c62555.png
