### ISSUE TITLE
MonsterKill

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7385]
**App Name:** MonsterKill
**Bundle ID:** com.Origin8.MonsterKill
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=329505049">329505049</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/monsterkill/id329505049?mt=8&uo=4">https://itunes.apple.com/us/app/monsterkill/id329505049?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** Origin8 Technologies Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/origin8/id294810422?uo=4>© Origin8</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/d7/04/dd/d704ddea-59a2-e10e-4d8a-c5eb964afd52/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14224708/792a819a-f8a6-11e5-8018-01cc70fae935.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14224708/792a819a-f8a6-11e5-8018-01cc70fae935.png)
https://cloud.githubusercontent.com/assets/2068130/14224708/792a819a-f8a6-11e5-8018-01cc70fae935.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14224709/86cfc968-f8a6-11e5-9f26-9b0d47e1b5ee.png

**Comment by Grafovich** [comment]
:+1:
