### ISSUE TITLE
Miitomo

### ISSUE THREAD

**Issue by Meyers09** [glasklart/hd#7386]
**App Name:** Miitomo
**Bundle ID:** com.nintendo.zaaa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1073816197">1073816197</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/miitomo/id1073816197?mt=8&uo=4">https://itunes.apple.com/us/app/miitomo/id1073816197?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Nintendo Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nintendo-co.-ltd./id1062496488?uo=4>© Nintendo Co., Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/7b/11/f0/7b11f0f5-885f-0ae6-7ada-fad1bd0e4970/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14231168/c369dc46-f979-11e5-92c2-1638c7e2a9ce.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14231168/c369dc46-f979-11e5-92c2-1638c7e2a9ce.png)
https://cloud.githubusercontent.com/assets/2068130/14231168/c369dc46-f979-11e5-92c2-1638c7e2a9ce.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14231171/d33b7aa8-f979-11e5-98f3-fcfd3f39ce81.png
