### ISSUE TITLE
Qantas Entertainment

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7387]
**App Name:** Qantas Entertainment
**Bundle ID:** au.com.qantas.public.Q-Streaming
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=968906181">968906181</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qantas-entertainment/id968906181?mt=8&uo=4">https://itunes.apple.com/us/app/qantas-entertainment/id968906181?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Qantas Airways Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/qantas-airways-limited/id394287136?uo=4>© Qantas Airways Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/66/b2/d6/66b2d69e-26e5-d686-8611-005dd74715be/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14224583/f7a515da-f8a1-11e5-9e10-65e69301de9e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14224583/f7a515da-f8a1-11e5-9e10-65e69301de9e.png)
https://cloud.githubusercontent.com/assets/2068130/14224583/f7a515da-f8a1-11e5-9e10-65e69301de9e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14224585/0747d5b8-f8a2-11e5-812c-d27425b8238d.png
