### ISSUE TITLE
Radiot.fi - Suomen virallinen nettiradio

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7388]
**App Name:** Radiot.fi - Suomen virallinen nettiradio
**Bundle ID:** fi.radiosoitinsuomi.radiotfi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=886117418">886117418</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radiot.fi-suomen-virallinen/id886117418?mt=8&uo=4">https://itunes.apple.com/us/app/radiot.fi-suomen-virallinen/id886117418?mt=8&uo=4</a>
**App Version:** 1.17.2
**Seller:** Radiosoitin Suomi Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/radiosoitin-suomi/id886117421?uo=4>© Radiosoitin Suomi</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/a6/6d/93/a66d93ac-2114-8d8d-b4a9-c52f454dd471/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/14268048/fe24db5c-fad6-11e5-9e73-a7165c3e4428.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/14268048/fe24db5c-fad6-11e5-9e73-a7165c3e4428.png)
https://cloud.githubusercontent.com/assets/10730122/14268048/fe24db5c-fad6-11e5-9e73-a7165c3e4428.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/14268047/fe218d4e-fad6-11e5-97ad-b6457a966fab.png
