### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7389]
**App Name:** Maven
**Bundle ID:** io.getmaven.maven
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1086400155">1086400155</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/maven/id1086400155?mt=8&uo=4">https://itunes.apple.com/us/app/maven/id1086400155?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Maven News, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/maven-news-inc./id1086400154?uo=4>© Maven News, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/7d/06/55/7d0655c0-8f49-3a04-ba46-ff8ec670c633/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14373749/8fa2cfda-fd4d-11e5-8146-25da5c360e61.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14373749/8fa2cfda-fd4d-11e5-8146-25da5c360e61.png)
https://cloud.githubusercontent.com/assets/2068130/14373749/8fa2cfda-fd4d-11e5-8146-25da5c360e61.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14373756/a09f0862-fd4d-11e5-8c9c-c1c19fac9f86.png
