### ISSUE TITLE
Reddit: The Official App

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#7391]
**App Name:** Reddit: The Official App
**Bundle ID:** com.reddit.Reddit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1064216828">1064216828</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reddit-the-official-app/id1064216828?mt=8&uo=4">https://itunes.apple.com/us/app/reddit-the-official-app/id1064216828?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** REDDIT, INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/reddit/id808295587?uo=4>© reddit</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/26/4f/aa/264faa2a-bf86-0363-f7cf-eaec6c396cfd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/14357874/bc32d274-fcea-11e5-829b-5915bd5a7767.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/14357874/bc32d274-fcea-11e5-829b-5915bd5a7767.png)
https://cloud.githubusercontent.com/assets/10730122/14357874/bc32d274-fcea-11e5-829b-5915bd5a7767.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/14357873/bc3287f6-fcea-11e5-9a3c-3cd6a48e3afe.png
