### ISSUE TITLE
DC Comics

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#7392]
**App Name:** DC Comics
**Bundle ID:** com.dccomics.comics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378080432">378080432</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dc-comics/id378080432?uo=4">https://apps.apple.com/us/app/dc-comics/id378080432?uo=4</a>
**App Version:** 3.11.7
**Seller:** DC Entertainment
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dc-entertainment/id378080435?uo=4">© DC Entertainment</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/7a/60/21/7a602130-83d1-b159-2000-aaca3a9343a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382124-db65dc80-9a5e-11e9-9472-d999fcbe59ee.png)

**Comment by zmathiasz** [comment]
Existing icon.  No current issue.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14464167/69a4bf0c-0093-11e6-9218-b297921fe35c.png)
https://cloud.githubusercontent.com/assets/3090247/14464167/69a4bf0c-0093-11e6-9218-b297921fe35c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14464166/699f5de6-0093-11e6-8a1a-903ca1c4ed9f.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382124-db65dc80-9a5e-11e9-9472-d999fcbe59ee.png)
(https://user-images.githubusercontent.com/20930745/60382124-db65dc80-9a5e-11e9-9472-d999fcbe59ee.png

Source:
https://user-images.githubusercontent.com/20930745/60382127-ddc83680-9a5e-11e9-8f94-ac8841b581e4.png
