### ISSUE TITLE
Manga by Crunchyroll

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#7393]
**App Name:** Manga by Crunchyroll
**Bundle ID:** com.crunchyroll.ios.manga
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=617048063">617048063</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/manga-by-crunchyroll/id617048063?mt=8&uo=4">https://itunes.apple.com/us/app/manga-by-crunchyroll/id617048063?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Crunchyroll Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/crunchyroll-inc./id329913457?uo=4>© Crunchyroll, Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/2f/57/54/2f5754db-370a-457c-42c5-4d8f64cbaf40/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14408629/ee8aa526-fefc-11e5-989e-5b78c98d3c69.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14408629/ee8aa526-fefc-11e5-989e-5b78c98d3c69.png)
https://cloud.githubusercontent.com/assets/2068130/14408629/ee8aa526-fefc-11e5-989e-5b78c98d3c69.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14408630/fce2e98a-fefc-11e5-8d59-b506afe98fdc.png
