### ISSUE TITLE
Chromatic Souls

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#7394]
**App Name:** Chromatic Souls
**Bundle ID:** com.gamevil.valkyrie.ios.apple.global.normal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=883907160">883907160</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chromatic-souls/id883907160?mt=8&uo=4">https://itunes.apple.com/us/app/chromatic-souls/id883907160?mt=8&uo=4</a>
**App Version:** 1.4.4
**Seller:** GAMEVIL Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gamevil-inc./id646209316?uo=4">© GAMEVIL Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/da/f5/13/daf5134e-0b2d-4553-3245-e5f566610514/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20641672/634ca02a-b3fd-11e6-89d4-fa61288fdfaf.png)

**Comment by dreamnet** [comment]
Ommmm....
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20641672/634ca02a-b3fd-11e6-89d4-fa61288fdfaf.png)
https://cloud.githubusercontent.com/assets/2068130/20641672/634ca02a-b3fd-11e6-89d4-fa61288fdfaf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20641678/71f5a090-b3fd-11e6-9851-812514ff7807.png
