### ISSUE TITLE
FINAL FANTASY Ⅸ

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#7395]
**App Name:** FINAL FANTASY Ⅸ
**Bundle ID:** com.square-enix.final-fantasy-ix-ww
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1041260001">1041260001</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/final-fantasy-ix/id1041260001?mt=8&uo=4">https://itunes.apple.com/us/app/final-fantasy-ix/id1041260001?mt=8&uo=4</a>
**App Version:** 1.0.9
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/7a/1f/4c/7a1f4c14-2bde-015e-b410-9d1f36db4eb5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14406301/c9ae2e78-fe69-11e5-8cd1-f8215d4b2057.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14406301/c9ae2e78-fe69-11e5-8cd1-f8215d4b2057.png)
https://cloud.githubusercontent.com/assets/3090247/14406301/c9ae2e78-fe69-11e5-8cd1-f8215d4b2057.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14406302/c9b61e58-fe69-11e5-87e6-19121f37f9a5.png
