### ISSUE TITLE
Secret of Mana

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#7396]
**App Name:** Secret of Mana
**Bundle ID:** com.square-enix.sk2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407949800">407949800</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/secret-of-mana/id407949800?mt=8&uo=4">https://itunes.apple.com/us/app/secret-of-mana/id407949800?mt=8&uo=4</a>
**App Version:** 3.2.0
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/e0/ab/43/e0ab4395-4dcc-5aaa-6e8c-f6b9473b5a6d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19065840/3a88dd68-8a16-11e6-947b-17dbcd8339da.png)

**Comment by 2Qt2beStr8** [comment]
.. i think it's not possible to do the original icon - so i used the lettering from the www

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19065840/3a88dd68-8a16-11e6-947b-17dbcd8339da.png)
https://cloud.githubusercontent.com/assets/20930745/19065840/3a88dd68-8a16-11e6-947b-17dbcd8339da.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19065852/4fbe9eca-8a16-11e6-92ce-78a959964368.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Jup!
