### ISSUE TITLE
Adventures of Mana

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#7397]
**App Name:** Adventures of Mana
**Bundle ID:** com.square-enix.sk1ww
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1048629983">1048629983</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adventures-of-mana/id1048629983?mt=8&uo=4">https://itunes.apple.com/us/app/adventures-of-mana/id1048629983?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/square-enix-inc/id300186801?mt=8&uo=4">© SQUARE ENIX INC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/e7/74/69/e77469e3-0e3e-9e27-8bde-39ccbf1c3a80/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21562799/036ffcc6-ce7c-11e6-99d3-e3e15bb779f8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21562799/036ffcc6-ce7c-11e6-99d3-e3e15bb779f8.png)
https://cloud.githubusercontent.com/assets/2068130/21562799/036ffcc6-ce7c-11e6-99d3-e3e15bb779f8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21562815/14cb28ba-ce7c-11e6-9efc-5bb68056fff3.png
