### ISSUE TITLE
Feeddler RSS Reader for iPad and iPhone

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7399]
**App Name:** Feeddler RSS Reader for iPad and iPhone
**Bundle ID:** com.chebinliu.FeeddlerRSS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364873582">364873582</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/feeddler-rss-reader-for-ipad/id364873582?mt=8&uo=4">https://itunes.apple.com/us/app/feeddler-rss-reader-for-ipad/id364873582?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Che-Bin Liu
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/c.b.-liu/id320928493?uo=4>© C.B. Liu</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/a1/8a/b9/a18ab91b-1de4-6493-a922-870259e9842d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14571014/b3d6d788-030c-11e6-8431-582009717388.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14571014/b3d6d788-030c-11e6-8431-582009717388.png)
https://cloud.githubusercontent.com/assets/3090247/14571014/b3d6d788-030c-11e6-8431-582009717388.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14571013/b3d2e8bc-030c-11e6-8a3b-e26f9ca0f15f.png
