### ISSUE TITLE
1Password - Password Manager and Secure Wallet

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#740]
**App Name:** 1Password - Password Manager and Secure Wallet
**Bundle ID:** com.agilebits.onepassword-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=568903335">568903335</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1password-password-manager/id568903335?mt=8&uo=4">https://itunes.apple.com/us/app/1password-password-manager/id568903335?mt=8&uo=4</a>
**App Version:** 5.4.1
**Seller:** AgileBits Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/agilebits-inc./id285897621?uo=4>© AgileBits Inc.</a>
**Supported Devices:** iPadMini, iPhone6, iPhone5, iPodTouchFifthGen, iPadMini4G, iPadFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadFourthGen4G, iPhone6Plus, iPadThirdGen, iPhone5c, iPhone5s, iPadThirdGen4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple7/v4/cb/a6/4e/cba64e07-a160-8a7d-c5c2-f8c71900c2f3/mzl.atgjkokf.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7801028/c33487e6-031e-11e5-9ef7-ec67e6a64468.png)

**Comment by Trubbel** [comment]
The icon have been updated, it's basically the same as the old one but the newer one kind of looks better.

**Comment by dreamnet** [comment]
How's this: :question: 
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/7801028/c33487e6-031e-11e5-9ef7-ec67e6a64468.png)
https://cloud.githubusercontent.com/assets/2068130/7801028/c33487e6-031e-11e5-9ef7-ec67e6a64468.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/7801039/f07b0108-031e-11e5-8d15-b9981028a0fd.png

**Comment by Trubbel** [comment]
@dreamnet Looks good! :+1:

**Comment by dreamnet** [comment]
@Trubbel OK!
