### ISSUE TITLE
WWF Together

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7401]
**App Name:** WWF Together
**Bundle ID:** org.worldwildlife.together
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=581920331">581920331</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wwf-together/id581920331?mt=8&uo=4">https://itunes.apple.com/us/app/wwf-together/id581920331?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** World Wildlife Fund, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/world-wildlife-fund/id581920334?uo=4>© World Wildlife Fund</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/65/21/60/652160b5-b58c-5809-cfd5-977ec9a65ec7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/7902388/52e159ee-0786-11e5-8e7d-5e721f36165e.png)

**Comment by Trubbel** [comment]
@dreamnet Perhaps we could use the same icon as #5709?

**Comment by dreamnet** [comment]
@Trubbel Yes, would be OK for me.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/7902388/52e159ee-0786-11e5-8e7d-5e721f36165e.png)
https://cloud.githubusercontent.com/assets/2236254/7902388/52e159ee-0786-11e5-8e7d-5e721f36165e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2236254/7902399/920b0dea-0786-11e5-9c54-ff0a27c6d7b0.png

Credit goes to @MagnaMike
