### ISSUE TITLE
Adobe Premiere Clip - Create, edit & share videos

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7403]
**App Name:** Adobe Premiere Clip - Create, edit & share videos
**Bundle ID:** com.adobe.premiereclip
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=919399401">919399401</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-premiere-clip-create/id919399401?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-premiere-clip-create/id919399401?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/d7/72/71/d7727172-2ade-25fd-eb2b-31be61ce96d6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14575467/93fb4d98-0327-11e6-8bbb-51ff08019c8c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14575415/4b9f5472-0327-11e6-8d59-9a121acc0beb.png)
https://cloud.githubusercontent.com/assets/3090247/14575415/4b9f5472-0327-11e6-8d59-9a121acc0beb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14575416/4be8fa82-0327-11e6-878e-e5e3246a2420.png

**Comment by dreamnet** [comment]
@ivanov007 Good work - taking the one in original size.
