### ISSUE TITLE
Adobe Fill & Sign – Easy PDF form filler

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7407]
**App Name:** Adobe Fill & Sign – Easy PDF form filler
**Bundle ID:** com.adobe.FillAndSign
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=950099951">950099951</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-fill-sign-easy-pdf-form/id950099951?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-fill-sign-easy-pdf-form/id950099951?mt=8&uo=4</a>
**App Version:** 15.0.4
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/87/de/d6/87ded61b-52c3-3854-ef21-f8b040aa2abe/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14589567/5beef976-04e5-11e6-8407-901126fed1b8.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14579066/0677821c-0362-11e6-853d-07a2cd44b1c5.png)
https://cloud.githubusercontent.com/assets/3090247/14579066/0677821c-0362-11e6-853d-07a2cd44b1c5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14579068/068c6574-0362-11e6-9f5a-d06f9df57fd2.png

**Comment by dreamnet** [comment]
@ivanov007 Original size?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14589567/5beef976-04e5-11e6-8407-901126fed1b8.png)
https://cloud.githubusercontent.com/assets/2068130/14589567/5beef976-04e5-11e6-8407-901126fed1b8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14589568/6b9af078-04e5-11e6-8822-2b709a7f27ef.png

**Comment by ivanov007** [comment]
@dreamnet yup, looks good
