### ISSUE TITLE
FrontierTV

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7408]
**App Name:** FrontierTV
**Bundle ID:** com.frontier.frontiertv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926446025">926446025</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/frontiertv/id926446025?mt=8&uo=4">https://itunes.apple.com/us/app/frontiertv/id926446025?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** Frontier Communications Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/frontier-communications/id898149096?uo=4>© Frontier Communications</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/d1/56/5f/d1565fd9-a2aa-f513-b96b-2a4e40b13071/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14581673/142b45e6-03b8-11e6-8af9-07719788125f.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14581673/142b45e6-03b8-11e6-8af9-07719788125f.png)
https://cloud.githubusercontent.com/assets/3090247/14581673/142b45e6-03b8-11e6-8af9-07719788125f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14581674/1435244e-03b8-11e6-98ae-85fd97afd803.png

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14581673/142b45e6-03b8-11e6-8af9-07719788125f.png)
https://cloud.githubusercontent.com/assets/3090247/14581673/142b45e6-03b8-11e6-8af9-07719788125f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14581674/1435244e-03b8-11e6-98ae-85fd97afd803.png
