### ISSUE TITLE
Noizio

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7409]
**App Name:** Noizio
**Bundle ID:** com.imicrothink.NatureSounds
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=960716999">960716999</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/noizio/id960716999?mt=8&uo=4">https://itunes.apple.com/us/app/noizio/id960716999?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Kyrylo Kovalin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kyrylo-kovalin/id928871588?uo=4>© Kyrylo Kovalin</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/db/0b/b8/db0bb887-f6cd-c4ff-70d8-fca1c8e9ce17/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14589610/5d1f9ee4-04e6-11e6-9ee1-549c9cf7a16b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14589610/5d1f9ee4-04e6-11e6-9ee1-549c9cf7a16b.png)
https://cloud.githubusercontent.com/assets/2068130/14589610/5d1f9ee4-04e6-11e6-9ee1-549c9cf7a16b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14589612/6c151bfe-04e6-11e6-926e-a29a8ff72bc1.png
