### ISSUE TITLE
Smart Cycle Alarm PRO

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7410]
**App Name:** Smart Cycle Alarm PRO
**Bundle ID:** com.blake.smartalarm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=906692291">906692291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smart-cycle-alarm-pro/id906692291?mt=8&uo=4">https://itunes.apple.com/us/app/smart-cycle-alarm-pro/id906692291?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** XSALGOLD UNIVERSAL LP
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/xsalgold-universal-lp/id975592284?uo=4>© XSALGOLD UNIVERSAL LP</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/b0/d6/ff/b0d6ffeb-10f9-c505-5deb-e93da01ff37f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14609187/4dda6a1e-054e-11e6-9d7b-d1f892fba11f.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14609187/4dda6a1e-054e-11e6-9d7b-d1f892fba11f.png)
https://cloud.githubusercontent.com/assets/3090247/14609187/4dda6a1e-054e-11e6-9d7b-d1f892fba11f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14609189/4e034d80-054e-11e6-967b-df2d285ca3c5.png
