### ISSUE TITLE
ProShot

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7411]
**App Name:** ProShot
**Bundle ID:** com.riseupgames.ProShot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=924438909">924438909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/proshot/id924438909?mt=8&uo=4">https://itunes.apple.com/us/app/proshot/id924438909?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** Edward Kezeli
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/edward-kezeli/id923703769?uo=4>© Edward Kezeli</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/19/02/a5/1902a516-f834-5659-7178-cf4198a2e9ae/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/14660847/cb274bf8-0676-11e6-9362-a64016c3f5f7.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/14660847/cb274bf8-0676-11e6-9362-a64016c3f5f7.png)
https://cloud.githubusercontent.com/assets/10950389/14660847/cb274bf8-0676-11e6-9362-a64016c3f5f7.png
***
Source:
https://cloud.githubusercontent.com/assets/10950389/14660896/4f17eaf8-0677-11e6-9906-2f186a159eb8.png
