### ISSUE TITLE
Done - manage your life with ease

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7412]
**App Name:** Done - manage your life with ease
**Bundle ID:** com.guxiu.Note
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1038311450">1038311450</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/done-manage-your-life-ease/id1038311450?mt=8&uo=4">https://itunes.apple.com/us/app/done-manage-your-life-ease/id1038311450?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Alex Zhu
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alex-zhu/id1038311449?uo=4>© Alex Zhu</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/a6/72/d8/a672d870-0a9e-fd87-7f81-5cd3b7135b14/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14592303/bb2af5fa-04e2-11e6-901c-c97165837a19.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14592303/bb2af5fa-04e2-11e6-901c-c97165837a19.png)
https://cloud.githubusercontent.com/assets/3090247/14592303/bb2af5fa-04e2-11e6-901c-c97165837a19.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14592319/dde8d332-04e2-11e6-94d4-50022e39d9c7.png
