### ISSUE TITLE
Clippo - Clipboard manager with a taste

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7413]
**App Name:** Clippo - Clipboard manager with a taste
**Bundle ID:** org.iphonesmartapps.Clipo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1092865336">1092865336</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clippo-clipboard-manager-taste/id1092865336?mt=8&uo=4">https://itunes.apple.com/us/app/clippo-clipboard-manager-taste/id1092865336?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Elisa Valeria Distefano
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/elisa-valeria-distefano/id326512931?uo=4>© Elisa Valeria Distefano</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/a8/49/07/a8490755-e52c-d676-1858-b042d2708159/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14592904/96f788e0-04e9-11e6-853d-fc469df5d02e.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14592904/96f788e0-04e9-11e6-853d-fc469df5d02e.png)
https://cloud.githubusercontent.com/assets/3090247/14592904/96f788e0-04e9-11e6-853d-fc469df5d02e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14592905/9711dd94-04e9-11e6-8e57-1938d5258225.png
