### ISSUE TITLE
GO Keyboard Pro - 60+ Languages, 1000+ Emoji, 10000+ Themes

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7414]
**App Name:** GO Keyboard Pro - 60+ Languages, 1000+ Emoji, 10000+ Themes
**Bundle ID:** com.jb.gokeyboardpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1087369723">1087369723</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/go-keyboard-pro-60+-languages/id1087369723?mt=8&uo=4">https://itunes.apple.com/us/app/go-keyboard-pro-60+-languages/id1087369723?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Sungy Mobile Limited.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/go-dev-team/id941551387?uo=4>© GO Dev Team</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/83/a1/53/83a15342-82a5-c5be-e364-d3ae21013774/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14592649/9186bb04-04e6-11e6-9f24-5c9428a9f4c8.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14592649/9186bb04-04e6-11e6-9f24-5c9428a9f4c8.png)
https://cloud.githubusercontent.com/assets/3090247/14592649/9186bb04-04e6-11e6-9f24-5c9428a9f4c8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14592650/91a3f6ba-04e6-11e6-89f5-8a8b7236aec8.png

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14592649/9186bb04-04e6-11e6-9f24-5c9428a9f4c8.png)
https://cloud.githubusercontent.com/assets/3090247/14592649/9186bb04-04e6-11e6-9f24-5c9428a9f4c8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14592650/91a3f6ba-04e6-11e6-89f5-8a8b7236aec8.png
