### ISSUE TITLE
Display Recorder

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7417]
**App Name:** Display Recorder
**Bundle ID:** com.booleanmagic.displayrecorder
**Version:** 1.3.20
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/7157389/14705878/f56f5ae0-07bb-11e6-9563-362623e65bde.PNG" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15083822/c5fc799e-13cf-11e6-9f0f-22294a138642.png)

**Comment by Anuskuss** [comment]
Icon exists, but I think someone should make a more mordern version (without the shine effect).

**Comment by dreamnet** [comment]
Here is the existing icon:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14723624/51a93e2e-0812-11e6-95a4-a52a1da86c8d.png)
https://cloud.githubusercontent.com/assets/2068130/14723624/51a93e2e-0812-11e6-95a4-a52a1da86c8d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14723643/63069f22-0812-11e6-930f-1c151a8380b1.png

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14766557/4f63110e-0a0f-11e6-8bc0-8fa5b200ca06.png)
https://cloud.githubusercontent.com/assets/2068130/14766557/4f63110e-0a0f-11e6-8bc0-8fa5b200ca06.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14766560/5f04ddb8-0a0f-11e6-908f-73e6090a84c5.png

**Comment by Anuskuss** [comment]
Can you make the "ring" more opaque?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15083822/c5fc799e-13cf-11e6-9f0f-22294a138642.png)
https://cloud.githubusercontent.com/assets/2068130/15083822/c5fc799e-13cf-11e6-9f0f-22294a138642.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15083831/d429a2f8-13cf-11e6-916a-ab222291132a.png
