### ISSUE TITLE
Geometry Wars 3: Dimensions Evolved

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7418]
**App Name:** Geometry Wars 3: Dimensions Evolved
**Bundle ID:** com.activision.gw3.dimensions
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=917463360">917463360</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/geometry-wars-3-dimensions/id917463360?mt=8&uo=4">https://itunes.apple.com/us/app/geometry-wars-3-dimensions/id917463360?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** Activision Publishing, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/activision-publishing-inc./id285005466?mt=8&uo=4>© Activision Publishing, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/64/d0/ba/64d0bae3-2d84-78e9-d15f-fe296efa8537/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19093565/e902cffa-8a8b-11e6-8558-70b5c1295fa6.png)

**Comment by 2Qt2beStr8** [comment]
.. what's about something like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19078525/b77a386e-8a50-11e6-8f9a-ff009f14a35e.png)
https://cloud.githubusercontent.com/assets/20930745/19078525/b77a386e-8a50-11e6-8f9a-ff009f14a35e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19078554/d6f609ac-8a50-11e6-8020-6ea25840fa3c.png

**Comment by Anuskuss** [comment]
@2Qt2beStr8 It's not a shape, it's a flying object.

**Comment by 2Qt2beStr8** [comment]
mines is a flying object too ... but only stylized

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19093565/e902cffa-8a8b-11e6-8558-70b5c1295fa6.png)
https://cloud.githubusercontent.com/assets/2068130/19093565/e902cffa-8a8b-11e6-8558-70b5c1295fa6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19093584/f806e536-8a8b-11e6-9b89-3b028244e62a.png
