### ISSUE TITLE
imgapp for imgur

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#742]
**App Name:** imgapp for imgur
**Bundle ID:** com.devinandalmas.imgur
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=501416446">501416446</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/imgapp-for-imgur/id501416446?mt=8&uo=4">https://itunes.apple.com/us/app/imgapp-for-imgur/id501416446?mt=8&uo=4</a>
**App Version:** 3.26
**Seller:** Devin Shively
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/d-s-software/id501416669?uo=4">© D & S Software</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/59/a9/7f/59a97fd4-cf03-3472-ee76-17725c8db194/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19967139/44351338-a1cf-11e6-9aa4-c118f33b06c4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19967139/44351338-a1cf-11e6-9aa4-c118f33b06c4.png)
https://cloud.githubusercontent.com/assets/20930745/19967139/44351338-a1cf-11e6-9aa4-c118f33b06c4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19967159/6369bde4-a1cf-11e6-8809-55952112b14e.png
