### ISSUE TITLE
TwistedWave Recorder

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7420]
**App Name:** TwistedWave Recorder
**Bundle ID:** com.twistedwave.TwistedWaveRecorder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=690359266">690359266</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/twistedwave-recorder/id690359266?mt=8&uo=4">https://itunes.apple.com/us/app/twistedwave-recorder/id690359266?mt=8&uo=4</a>
**App Version:** 1.14
**Seller:** Thomas Thiriez
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/twistedwave/id401438499?uo=4>© TwistedWave</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/92/7b/27/927b272f-b077-1254-2c95-7499596aa96b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15096270/e85d2006-14f1-11e6-80b5-e4e57147bff1.png)

**Comment by Anuskuss** [comment]
Same icon as #7419.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15096270/e85d2006-14f1-11e6-80b5-e4e57147bff1.png)
https://cloud.githubusercontent.com/assets/2068130/15096270/e85d2006-14f1-11e6-80b5-e4e57147bff1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15096273/f64f2fba-14f1-11e6-9d42-65084a02ed26.png
