### ISSUE TITLE
Milkeddit

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7421]
**App Name:** Milkeddit
**Bundle ID:** com.shi.Milkeddit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1052514694">1052514694</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/milkeddit/id1052514694?mt=8&uo=4">https://itunes.apple.com/us/app/milkeddit/id1052514694?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Shihab Mehboob
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shihab-mehboob/id1012903170?uo=4>© Shihab Mehboob</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/06/a3/b3/06a3b3a0-5f13-b0af-58a2-9832b811be28/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14730256/72e9c4a8-080a-11e6-95c4-8dad91dafe54.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14730256/72e9c4a8-080a-11e6-95c4-8dad91dafe54.png)
https://cloud.githubusercontent.com/assets/3090247/14730256/72e9c4a8-080a-11e6-95c4-8dad91dafe54.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14730257/72ebfbb0-080a-11e6-8ab5-d073c751f69c.png
