### ISSUE TITLE
Math 42

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7422]
**App Name:** Math 42
**Bundle ID:** com.cogeon.math42
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=664457128">664457128</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/math-42/id664457128?mt=8&uo=4">https://itunes.apple.com/us/app/math-42/id664457128?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** Cogeon Gesellschaft für intelligente Lösungen mbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cogeon-gmbh/id664457131?uo=4>© Cogeon GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/22/11/ac/2211ac6d-376a-1048-f36b-8f0e9935227a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14916267/34be92ce-0dde-11e6-84fe-a7da95c52c84.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/14914235/b964bb96-0e08-11e6-9dce-eb4926f2490d.png)
https://cloud.githubusercontent.com/assets/10730122/14914235/b964bb96-0e08-11e6-9dce-eb4926f2490d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/14914236/b9663a0c-0e08-11e6-9a9e-a67da65946df.png

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/14916267/34be92ce-0dde-11e6-84fe-a7da95c52c84.png)
https://cloud.githubusercontent.com/assets/3090247/14916267/34be92ce-0dde-11e6-84fe-a7da95c52c84.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14916268/34c9c572-0dde-11e6-9dbf-a40d77940c72.png
