### ISSUE TITLE
Ultimate Briefcase

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7423]
**App Name:** Ultimate Briefcase
**Bundle ID:** com.nitrome.ultimatebriefcase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1047666264">1047666264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ultimate-briefcase/id1047666264?mt=8&uo=4">https://itunes.apple.com/us/app/ultimate-briefcase/id1047666264?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** Nitrome
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nitrome/id568079484?uo=4>© Nitrome</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/3a/1f/83/3a1f8359-55ac-7bbb-13f2-91b1d3413a45/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18815004/a0b514d4-8323-11e6-9796-9a93f9c8105c.png)

**Comment by ivanov007** [comment]
@Anuskuss are you able to play this? it´s crashing on my device

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14730066/e8d2fc4a-0808-11e6-8618-76cd24ffed14.png)
https://cloud.githubusercontent.com/assets/3090247/14730066/e8d2fc4a-0808-11e6-8618-76cd24ffed14.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14730065/e8d05d96-0808-11e6-8ed7-5a667b8f89eb.png

**Comment by Anuskuss** [comment]
@ivanov007 Yes I can play it (I'm on 8.4). Btw the shadow on his hair looks weird, do you want to repaint it white or do you like it as it is?

**Comment by Anuskuss** [comment]
@ivanov007 ?

**Comment by ivanov007** [comment]
ok, here's the alternative
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17196698/27c55fdc-542c-11e6-85d6-fa171ba920d2.png)
https://cloud.githubusercontent.com/assets/3090247/17196698/27c55fdc-542c-11e6-85d6-fa171ba920d2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17196699/27c9665e-542c-11e6-97af-f1073d7fdafc.png

**Comment by Anuskuss** [comment]
@ivanov007 I meant the top of his hair, which is transparent, should be white in my opinion.

**Comment by ivanov007** [comment]
well, that's the briefcase shadow, so I think it looks good like that
