### ISSUE TITLE
Hexavoid

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7424]
**App Name:** Hexavoid
**Bundle ID:** com.nanovationlabs.hexavoid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1088625279">1088625279</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hexavoid/id1088625279?mt=8&uo=4">https://itunes.apple.com/us/app/hexavoid/id1088625279?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Nanovation, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nanovation/id876536274?uo=4>© Nanovation</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/30/09/f5/3009f5d4-a521-a621-1377-d84b20ab4365/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712581/d4b6fe48-468b-11e6-8ef8-b7cc7be5311d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15090470/2979b29e-1429-11e6-8b5d-6c99e15c5ff0.png)
https://cloud.githubusercontent.com/assets/2068130/15090470/2979b29e-1429-11e6-8b5d-6c99e15c5ff0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15090472/384b9bfc-1429-11e6-92f8-6d7dd0172ca0.png

**Comment by Anuskuss** [comment]
@dreamnet Could you make the lines a bit thicker? I'm asking this because Hexavoid and [Huemory](#7425) are next to each other on my device and I'd like the lines to be more consistent.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712581/d4b6fe48-468b-11e6-8ef8-b7cc7be5311d.png)
https://cloud.githubusercontent.com/assets/2068130/16712581/d4b6fe48-468b-11e6-8ef8-b7cc7be5311d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712582/e4173d3a-468b-11e6-9ed0-488fccfa3a82.png

**Comment by Anuskuss** [comment]
Thank you :+1:
