### ISSUE TITLE
Huemory

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7425]
**App Name:** Huemory
**Bundle ID:** com.pixelapestudios.huemory
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1025382928">1025382928</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/huemory/id1025382928?mt=8&uo=4">https://itunes.apple.com/us/app/huemory/id1025382928?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** MKART TECHNOLOGIES
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mkart-technologies/id1072175133?uo=4>© MKART TECHNOLOGIES</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/0f/50/d3/0f50d3dd-9933-db70-cc9a-087940b1562d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15090522/7ee91ea8-142a-11e6-9203-0ab78f1370a6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15090522/7ee91ea8-142a-11e6-9203-0ab78f1370a6.png)
https://cloud.githubusercontent.com/assets/2068130/15090522/7ee91ea8-142a-11e6-9203-0ab78f1370a6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15090524/8ccfed1c-142a-11e6-8550-27bb77091ac5.png
