### ISSUE TITLE
YAMGUN

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7426]
**App Name:** YAMGUN
**Bundle ID:** ch.digitalkingdom.yamgun
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1041702683">1041702683</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yamgun/id1041702683?mt=8&uo=4">https://itunes.apple.com/us/app/yamgun/id1041702683?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Digital Kingdom Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/digital-kingdom/id1021536225?uo=4>© Digital Kingdom</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/ef/af/3f/efaf3fe3-f1dd-116b-1027-c664f33ac3b6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14728603/de777d6e-07fb-11e6-977d-fba62358ca38.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14728603/de777d6e-07fb-11e6-977d-fba62358ca38.png)
https://cloud.githubusercontent.com/assets/3090247/14728603/de777d6e-07fb-11e6-977d-fba62358ca38.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14728602/de760f7e-07fb-11e6-8daf-1f8043a0dcc1.png
