### ISSUE TITLE
Endless Sky

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7427]
**App Name:** Endless Sky
**Bundle ID:** com.ketchapp.sky
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032997004">1032997004</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/endless-sky/id1032997004?mt=8&uo=4">https://itunes.apple.com/us/app/endless-sky/id1032997004?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Ketchapp
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ketchapp/id528065807?uo=4>© Ketchapp</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/1b/08/7d/1b087d51-7cc0-71af-fbc4-b7862c0c01e5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18795589/8ffaf05a-81c5-11e6-8f9f-55f17adfdc19.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18795589/8ffaf05a-81c5-11e6-8f9f-55f17adfdc19.png)
https://cloud.githubusercontent.com/assets/20930745/18795589/8ffaf05a-81c5-11e6-8f9f-55f17adfdc19.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18795658/dea54048-81c5-11e6-8ac6-3d110cb0fbb4.png
