### ISSUE TITLE
Textastic Code Editor 8

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7428]
**App Name:** Textastic Code Editor 8
**Bundle ID:** com.textasticapp.textastic-universal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049254261">1049254261</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/textastic-code-editor-8/id1049254261?uo=4">https://apps.apple.com/us/app/textastic-code-editor-8/id1049254261?uo=4</a>
**App Version:** 8.0.1
**Seller:** Alexander Blach
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/alexander-blach/id303486870?uo=4">© Alexander Blach</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/ed/dd/44/eddd44d7-3a66-086e-dd99-40efaee0d8a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62011266-4ac20f80-b176-11e9-871c-3546fe8125f5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14723932/b40d7a66-0813-11e6-9608-ea0f2afeaee2.png)
https://cloud.githubusercontent.com/assets/2068130/14723932/b40d7a66-0813-11e6-9608-ea0f2afeaee2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14723946/c846156a-0813-11e6-8334-566980c5efbc.png

**Comment by dreamnet** [comment]
Original Size:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14766419/7c24b0ea-0a09-11e6-9109-633366b67b76.png)
https://cloud.githubusercontent.com/assets/2068130/14766419/7c24b0ea-0a09-11e6-9109-633366b67b76.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14766421/90fc9280-0a09-11e6-836e-81c9c1e79393.png

**Comment by Anuskuss** [comment]
@dreamnet I think it safe to say that we don't need the iPad version of this icon anymore (`com.textasticapp.textastic`)

**Comment by dreamnet** [comment]
@Anuskuss OK, thanks!

**Comment by dreamnet** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62011266-4ac20f80-b176-11e9-871c-3546fe8125f5.png)
https://user-images.githubusercontent.com/2068130/62011266-4ac20f80-b176-11e9-871c-3546fe8125f5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62011270-6200fd00-b176-11e9-8d61-a6d11667e450.png
