### ISSUE TITLE
Chameleon Run

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7429]
**App Name:** Chameleon Run
**Bundle ID:** com.noodlecake.chameleonrun
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1084860489">1084860489</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chameleon-run/id1084860489?mt=8&uo=4">https://itunes.apple.com/us/app/chameleon-run/id1084860489?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Noodlecake Studios Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/noodlecake-studios-inc/id370828169?uo=4>© Noodlecake Studios Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/0d/72/c5/0d72c5f3-6f02-1440-714e-d2111a3d5aab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18848518/03892116-842f-11e6-9f54-3fb9b101e38d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18848518/03892116-842f-11e6-9f54-3fb9b101e38d.png)
https://cloud.githubusercontent.com/assets/20930745/18848518/03892116-842f-11e6-9f54-3fb9b101e38d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18848535/16b2f640-842f-11e6-8307-8b32a161b54d.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yeah! 👍
