### ISSUE TITLE
Deer Hunter 2016

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7430]
**App Name:** Deer Hunter 2016
**Bundle ID:** com.glu.deerhunt16
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=893372761">893372761</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deer-hunter-2016/id893372761?mt=8&uo=4">https://itunes.apple.com/us/app/deer-hunter-2016/id893372761?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Glu Games Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/glu-games-inc/id284419051?uo=4>© Glu Games Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/c8/17/04/c817045f-6d1a-88fc-71e8-f2c3c855de22/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16163337/f564b9e2-34d8-11e6-92ad-dbf8d4659145.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16163337/f564b9e2-34d8-11e6-92ad-dbf8d4659145.png)
https://cloud.githubusercontent.com/assets/10730122/16163337/f564b9e2-34d8-11e6-92ad-dbf8d4659145.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16163378/305a2820-34d9-11e6-97ee-be83566f498d.png
