### ISSUE TITLE
Windy - wind forecast application for windguru, kitesurfers, windsurfers and wind-addicted people.

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7431]
**App Name:** Windy - wind forecast application for windguru, kitesurfers, windsurfers and wind-addicted people.
**Bundle ID:** co.windyapp.Windy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=997079492">997079492</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/windy-wind-forecast-application/id997079492?mt=8&uo=4">https://itunes.apple.com/us/app/windy-wind-forecast-application/id997079492?mt=8&uo=4</a>
**App Version:** 2.2.8
**Seller:** Igor Kamenev
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/igor-kamenev/id910687200?uo=4>© Igor Kamenev</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/f4/1c/37/f41c3774-9eb3-7919-7c69-255a8729f82e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14769905/8f2ed59e-0a63-11e6-94cb-2dd4c80d5211.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14769905/8f2ed59e-0a63-11e6-94cb-2dd4c80d5211.png)
https://cloud.githubusercontent.com/assets/2068130/14769905/8f2ed59e-0a63-11e6-94cb-2dd4c80d5211.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14769907/9fd201e6-0a63-11e6-9bd0-c1f9c4635d09.png
