### ISSUE TITLE
FOX Sports Mobile

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7432]
**App Name:** FOX Sports Mobile
**Bundle ID:** com.uie.foxsports
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=294056623">294056623</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fox-sports-mobile/id294056623?mt=8&uo=4">https://itunes.apple.com/us/app/fox-sports-mobile/id294056623?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** FOX Sports Interactive
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fox-sports-interactive/id294056626?uo=4>© FOX Sports Interactive</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/85/82/ad/8582ad1c-df05-a3d7-4f39-520953c5451f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14767151/29ef6480-0a1f-11e6-847f-3589bf321396.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14767151/29ef6480-0a1f-11e6-847f-3589bf321396.png)
https://cloud.githubusercontent.com/assets/2068130/14767151/29ef6480-0a1f-11e6-847f-3589bf321396.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14767153/3a39b6e2-0a1f-11e6-8041-651b444a68b1.png
