### ISSUE TITLE
Aktia Kortti

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7433]
**App Name:** Aktia Kortti
**Bundle ID:** com.evry.cardcompanion.aktia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1100143567">1100143567</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aktia-kortti/id1100143567?mt=8&uo=4">https://itunes.apple.com/us/app/aktia-kortti/id1100143567?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Aktia Bank Abp
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aktia-bank-abp/id1100143566?uo=4>© Aktia Bank Abp</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/8f/c2/9a/8fc29a0e-9df7-6665-a327-b960f8ad580a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14767167/b0e3433a-0a1f-11e6-899b-8d660a1dd076.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14767167/b0e3433a-0a1f-11e6-899b-8d660a1dd076.png)
https://cloud.githubusercontent.com/assets/2068130/14767167/b0e3433a-0a1f-11e6-899b-8d660a1dd076.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14767169/bfa8e4ba-0a1f-11e6-9a4b-ffd54bf21989.png
