### ISSUE TITLE
Kasa for Mobile

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#7434]
**App Name:** Kasa for Mobile
**Bundle ID:** com.tplink.kasa-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1034035493">1034035493</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kasa-for-mobile/id1034035493?mt=8&uo=4">https://itunes.apple.com/us/app/kasa-for-mobile/id1034035493?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** TP-LINK Research America Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tp-link-research-america/id1034035492?uo=4>© TP-LINK Research America</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/1b/39/82/1b3982ed-e271-e2b0-79ca-0ef3c309f522/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14769515/93a4d974-0a5a-11e6-8a2e-3d5b9ac51f8c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14769515/93a4d974-0a5a-11e6-8a2e-3d5b9ac51f8c.png)
https://cloud.githubusercontent.com/assets/2068130/14769515/93a4d974-0a5a-11e6-8a2e-3d5b9ac51f8c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14769518/a5355eac-0a5a-11e6-902c-b97fbd55935e.png
