### ISSUE TITLE
ΣΚΑΪ.gr

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#7435]
**App Name:** ΣΚΑΪ.gr
**Bundle ID:** com.skaigr.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1076335165">1076335165</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skai.gr/id1076335165?mt=8&uo=4">https://itunes.apple.com/us/app/skai.gr/id1076335165?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** EIDISEIS DOT COM S.A
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eidiseis-dot-com-s.a/id673096331?uo=4>© EIDISEIS DOT COM S.A</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/6b/63/fe/6b63fe78-1408-af8e-769a-7614033d6f75/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14767197/68c30ce2-0a20-11e6-9f96-3026cc75e8e0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14767197/68c30ce2-0a20-11e6-9f96-3026cc75e8e0.png)
https://cloud.githubusercontent.com/assets/2068130/14767197/68c30ce2-0a20-11e6-9f96-3026cc75e8e0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14767203/77331c2c-0a20-11e6-8ba9-c94344e78a83.png
