### ISSUE TITLE
PAC-MAN Lite

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7438]
**App Name:** PAC-MAN Lite
**Bundle ID:** com.namconetworks.pacmanlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=293778748">293778748</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pac-man-lite/id293778748?mt=8&uo=4">https://itunes.apple.com/us/app/pac-man-lite/id293778748?mt=8&uo=4</a>
**App Version:** 6.1.0
**Seller:** BANDAI NAMCO Entertainment America Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bandai-namco-entertainment/id281656478?mt=8&uo=4>© BANDAI NAMCO Entertainment America Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/ef/57/0b/ef570bc2-3c08-9146-2091-77ed2fa9e9c3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14963083/aa31bfb4-1067-11e6-8eb3-5c57eb98b713.png)

**Comment by Anuskuss** [comment]
Existing icon should be updated.

**Comment by dreamnet** [comment]
Refers to #1160.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14963083/aa31bfb4-1067-11e6-8eb3-5c57eb98b713.png)
https://cloud.githubusercontent.com/assets/3090247/14963083/aa31bfb4-1067-11e6-8eb3-5c57eb98b713.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14963097/b59b55a4-1067-11e6-94a2-3cb55fc6a036.png
