### ISSUE TITLE
PAC-MAN DASH!

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7439]
**App Name:** PAC-MAN DASH!
**Bundle ID:** jp.co.bandainamcogames.NBGI0141
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=660127957">660127957</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pac-man-dash!/id660127957?mt=8&uo=4">https://itunes.apple.com/us/app/pac-man-dash!/id660127957?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** BANDAI NAMCO Entertainment Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bandai-namco-entertainment/id352305770?uo=4>© BANDAI NAMCO Entertainment Inc.</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/f3/a9/b5/f3a9b546-dcd1-65eb-9d24-f7d7258bdd94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19044661/8bff1800-8995-11e6-8f0e-9507d6bf25dc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19037761/455d163a-8978-11e6-888b-4b5385c319b7.png)
https://cloud.githubusercontent.com/assets/20930745/19037761/455d163a-8978-11e6-888b-4b5385c319b7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19037772/54078d32-8978-11e6-975c-baefaff5bd3a.png

**Comment by ivanov007** [comment]
@2Qt2beStr8 maybe no eyebows?

**Comment by 2Qt2beStr8** [comment]
... like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19044661/8bff1800-8995-11e6-8f0e-9507d6bf25dc.png)
https://cloud.githubusercontent.com/assets/20930745/19044661/8bff1800-8995-11e6-8f0e-9507d6bf25dc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19044677/9a643696-8995-11e6-9333-5f948c8e0694.png
