### ISSUE TITLE
Nabu

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#7440]
**App Name:** Nabu
**Bundle ID:** com.razerzone.nabu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=895754325">895754325</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nabu/id895754325?mt=8&uo=4">https://itunes.apple.com/us/app/nabu/id895754325?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Razer USA Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/razer/id860552677?uo=4>© Razer</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/ba/1a/d0/ba1ad06a-b0bd-1a08-8b43-d8f67969b758/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14941498/b91f2f3a-0f9e-11e6-807b-fcd1def324f4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14941498/b91f2f3a-0f9e-11e6-807b-fcd1def324f4.png)
https://cloud.githubusercontent.com/assets/2068130/14941498/b91f2f3a-0f9e-11e6-807b-fcd1def324f4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14941499/c82ad826-0f9e-11e6-8440-d8e623665b92.png
