### ISSUE TITLE
Tasker: To Do List | Task Manager

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7441]
**App Name:** Tasker: To Do List | Task Manager
**Bundle ID:** com.vacata.Tasker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1023951385">1023951385</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tasker-to-do-list-task-manager/id1023951385?mt=8&uo=4">https://itunes.apple.com/us/app/tasker-to-do-list-task-manager/id1023951385?mt=8&uo=4</a>
**App Version:** 1.2.5
**Seller:** Vacata AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vacata-ag/id675290767?uo=4>© Vacata AG</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/95/b1/d8/95b1d852-2618-cb97-255e-ed8e2295cb9c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15073674/1d3e2b42-139b-11e6-8b3d-69e263dadff7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15073674/1d3e2b42-139b-11e6-8b3d-69e263dadff7.png)
https://cloud.githubusercontent.com/assets/2068130/15073674/1d3e2b42-139b-11e6-8b3d-69e263dadff7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15073682/2bd8fbf0-139b-11e6-83eb-836b60def71a.png
