### ISSUE TITLE
Evermusic Pro - offline music

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7442]
**App Name:** Evermusic Pro - offline music
**Bundle ID:** com.leshko.cloudplayerpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905746421">905746421</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/evermusic-pro-offline-music/id905746421?mt=8&uo=4">https://itunes.apple.com/us/app/evermusic-pro-offline-music/id905746421?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Artem Meleshko
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/artem-meleshko/id885367201?uo=4">© Artem Meleshko</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/be/d2/10/bed2100a-1769-58b0-987e-1a6abcea9101/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44160838-f4220980-a0bb-11e8-8b4f-ea0af0f75cde.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14941481/f456e224-0f9d-11e6-95b1-5488e7b1d3a8.png)
https://cloud.githubusercontent.com/assets/2068130/14941481/f456e224-0f9d-11e6-95b1-5488e7b1d3a8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14941482/05f16734-0f9e-11e6-8fd8-094c2399f815.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Evermusic Pro - offline music
**Bundle ID:** com.leshko.cloudplayerpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905746421">905746421</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/evermusic-pro-offline-music/id905746421?mt=8&uo=4">https://itunes.apple.com/us/app/evermusic-pro-offline-music/id905746421?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Artem Meleshko
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/artem-meleshko/id885367201?uo=4">© Artem Meleshko</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple125/v4/da/9c/3c/da9c3c2f-c713-d0e0-d52d-4ce2625dcf8d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41805682-3c7ddaec-76af-11e8-8703-2bd0d45b2086.png)
https://user-images.githubusercontent.com/2068130/41805682-3c7ddaec-76af-11e8-8703-2bd0d45b2086.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41805683-4bcf1a74-76af-11e8-909d-f74515358c92.png

**Comment by l8er4now** [comment]
Needs an update

**App Name:** Evermusic Pro - offline music
**Bundle ID:** com.leshko.cloudplayerpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905746421">905746421</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/evermusic-pro-offline-music/id905746421?mt=8&uo=4">https://itunes.apple.com/us/app/evermusic-pro-offline-music/id905746421?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Artem Meleshko
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/artem-meleshko/id885367201?uo=4">© Artem Meleshko</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/be/d2/10/bed2100a-1769-58b0-987e-1a6abcea9101/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44160838-f4220980-a0bb-11e8-8b4f-ea0af0f75cde.png)
https://user-images.githubusercontent.com/2068130/44160838-f4220980-a0bb-11e8-8b4f-ea0af0f75cde.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44160868-02702580-a0bc-11e8-9d07-3bdd0e6789d6.png
