### ISSUE TITLE
Safari Page Translate PRO - Browser Widget (Professional version)

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7443]
**App Name:** Safari Page Translate PRO - Browser Widget (Professional version)
**Bundle ID:** com.midnight.safaripagetranslate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1097547040">1097547040</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/safari-page-translate-pro/id1097547040?mt=8&uo=4">https://itunes.apple.com/us/app/safari-page-translate-pro/id1097547040?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Gaina Roman
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gaina-roman/id1003743093?uo=4>© Gaina Roman</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/5e/94/90/5e949099-b4e8-c4a3-af97-3159cfa488cf/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15090308/6d040f32-1424-11e6-8731-6b07c6d03c31.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15090308/6d040f32-1424-11e6-8731-6b07c6d03c31.png)
https://cloud.githubusercontent.com/assets/2068130/15090308/6d040f32-1424-11e6-8731-6b07c6d03c31.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15090312/7c610610-1424-11e6-9e9d-d09934c4a7f3.png
