### ISSUE TITLE
WikiExplorer for Wikipedia

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7444]
**App Name:** WikiExplorer for Wikipedia
**Bundle ID:** com.animaonline.wikiexplorer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1023141634">1023141634</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wikiexplorer-for-wikipedia/id1023141634?mt=8&uo=4">https://itunes.apple.com/us/app/wikiexplorer-for-wikipedia/id1023141634?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Roman Alifanov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/roman-alifanov/id1023141633?uo=4>© Roman Alifanov</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/50/e3/c5/50e3c5eb-d81f-7635-ab4c-c19f1eed7034/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14943640/87b2ed2a-0fde-11e6-8cbc-809c5cc93504.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/14943640/87b2ed2a-0fde-11e6-8cbc-809c5cc93504.png)
https://cloud.githubusercontent.com/assets/2068130/14943640/87b2ed2a-0fde-11e6-8cbc-809c5cc93504.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/14943646/984afccc-0fde-11e6-989a-62460086a10a.png
