### ISSUE TITLE
PDF WordSmith - Convert PDF to Word, HTML and TXT

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7445]
**App Name:** PDF WordSmith - Convert PDF to Word, HTML and TXT
**Bundle ID:** com.kdanmobile.pdfwordsmith-ipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=738227573">738227573</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pdf-wordsmith-convert-pdf/id738227573?mt=8&uo=4">https://itunes.apple.com/us/app/pdf-wordsmith-convert-pdf/id738227573?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Kdan Mobile Software LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kdan-mobile-software-ltd/id318936474?uo=4>© Kdan Mobile Software LTD</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/88/2b/07/882b077f-f98d-7dce-23c9-c259b0f6c0ee/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15054279/d2b17988-1306-11e6-9f70-bba876935008.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15054279/d2b17988-1306-11e6-9f70-bba876935008.png)
https://cloud.githubusercontent.com/assets/2068130/15054279/d2b17988-1306-11e6-9f70-bba876935008.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15054289/e24bf0da-1306-11e6-93c5-0d7aaf25695b.png
