### ISSUE TITLE
Daily News - Smarter Reader on National & World News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7446]
**App Name:** Daily News - Smarter Reader on National & World News
**Bundle ID:** com.gopassionstudio.streamy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=949788086">949788086</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/daily-news-smarter-reader/id949788086?mt=8&uo=4">https://itunes.apple.com/us/app/daily-news-smarter-reader/id949788086?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** Ha Nguyen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ha-nguyen/id1122369564?uo=4>© Ha Nguyen</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/55/88/39/55883956-72b8-8dfa-9edd-05e8bd301d6f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17321052/e29a0790-5896-11e6-9d81-2ba421d5aa71.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15090203/3ba8c1ae-141e-11e6-921c-204ed5d78d92.png)
https://cloud.githubusercontent.com/assets/2068130/15090203/3ba8c1ae-141e-11e6-921c-204ed5d78d92.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15090209/4fb04226-141e-11e6-99c2-8a0edc47c3e9.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Daily News - Smarter Reader on National & World News
**Bundle ID:** com.gopassionstudio.streamy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=949788086">949788086</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/daily-news-smarter-reader/id949788086?mt=8&uo=4">https://itunes.apple.com/us/app/daily-news-smarter-reader/id949788086?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** Ha Nguyen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ha-nguyen/id1122369564?uo=4>© Ha Nguyen</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/55/88/39/55883956-72b8-8dfa-9edd-05e8bd301d6f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17321052/e29a0790-5896-11e6-9d81-2ba421d5aa71.png)
https://cloud.githubusercontent.com/assets/2068130/17321052/e29a0790-5896-11e6-9d81-2ba421d5aa71.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17321064/f0cc4ae4-5896-11e6-8670-a2c914ea4482.png
