### ISSUE TITLE
Fantasy Labs - Daily Fantasy Player Ratings, Rankings, Optimal Lineups for DraftKings (DK) and FanDuel (FD)

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7447]
**App Name:** Fantasy Labs - Daily Fantasy Player Ratings, Rankings, Optimal Lineups for DraftKings (DK) and FanDuel (FD)
**Bundle ID:** com.fantasylabs.FantasyLabs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1034983254">1034983254</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasy-labs-daily-fantasy/id1034983254?mt=8&uo=4">https://itunes.apple.com/us/app/fantasy-labs-daily-fantasy/id1034983254?mt=8&uo=4</a>
**App Version:** 1.1.6
**Seller:** Fantasy Labs, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fantasy-labs-llc/id1034983253?uo=4>© Fantasy Labs, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/23/2b/c1/232bc17a-33a2-f424-55ed-67e105f4fb8f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14961827/64f51f50-1061-11e6-8c51-73b8198ce260.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14961827/64f51f50-1061-11e6-8c51-73b8198ce260.png)
https://cloud.githubusercontent.com/assets/3090247/14961827/64f51f50-1061-11e6-8c51-73b8198ce260.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14961826/64f31426-1061-11e6-860e-774ee2477406.png
