### ISSUE TITLE
slither.io

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7448]
**App Name:** slither.io
**Bundle ID:** com.hypah.io.slither
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1091944550">1091944550</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slither.io/id1091944550?mt=8&uo=4">https://itunes.apple.com/us/app/slither.io/id1091944550?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Steve Howse
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/steve-howse/id867992583?uo=4>© Steve Howse</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/55/82/bc/5582bc4d-708e-a4f9-976d-acc18e2e984d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15053206/bf99ac76-1301-11e6-9906-3209301aa716.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15053206/bf99ac76-1301-11e6-9906-3209301aa716.png)
https://cloud.githubusercontent.com/assets/2068130/15053206/bf99ac76-1301-11e6-9906-3209301aa716.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15053215/cdf09b90-1301-11e6-9708-5ce040e81343.png
