### ISSUE TITLE
Space Marshals

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7449]
**App Name:** Space Marshals
**Bundle ID:** se.pixelbite.Backspaced
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834315918">834315918</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/space-marshals/id834315918?mt=8&uo=4">https://itunes.apple.com/us/app/space-marshals/id834315918?mt=8&uo=4</a>
**App Version:** 1.2.3
**Seller:** Pixelbite
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pixelbite/id428934441?uo=4>© Pixelbite</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/f6/98/48/f69848ff-b664-b6a2-5bb0-839604f2eff7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19171146/a1634828-8c1b-11e6-9e48-4c27df22cf46.png)

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... maybe you can "pimp it up" a little bit .. i can't do it better

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19023038/e5d7a024-88e4-11e6-8ad3-03467311b1b7.png)
https://cloud.githubusercontent.com/assets/20930745/19023038/e5d7a024-88e4-11e6-8ad3-03467311b1b7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19023047/18efe96c-88e5-11e6-800b-f5431c8caeb6.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19109706/c9c008cc-8af6-11e6-847c-0db8a7c50607.png)
https://cloud.githubusercontent.com/assets/20930745/19109706/c9c008cc-8af6-11e6-847c-0db8a7c50607.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19109723/e707003e-8af6-11e6-9003-6244654df98d.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Sorry, had no time for overworking... maybe in the evening.

**Comment by dreamnet** [comment]
OK, finally I did only some small corrections.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19171146/a1634828-8c1b-11e6-9e48-4c27df22cf46.png)
https://cloud.githubusercontent.com/assets/2068130/19171146/a1634828-8c1b-11e6-9e48-4c27df22cf46.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19171163/aefdd1a6-8c1b-11e6-8b55-b250ee2ca53f.png
