### ISSUE TITLE
Weather 2x

### ISSUE THREAD

**Issue by odysseydla** [glasklart/hd#745]
**App Name:** Weather 2x
**Bundle ID:** com.mcleanmobile.weather2x
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=512607963">512607963</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-2x/id512607963?mt=8&uo=4">https://itunes.apple.com/us/app/weather-2x/id512607963?mt=8&uo=4</a>
**App Version:** 2.01
**Seller:** McLean Mobile Solutions, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mclean-mobile-solutions-inc./id293879782?uo=4">© McLean Mobile Solutions, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/46/b0/55/46b055e8-fd7a-a094-e4c2-f0b133b7988b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19966890/12892424-a1ce-11e6-8bd2-bc6df57475ba.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19966890/12892424-a1ce-11e6-8bd2-bc6df57475ba.png)
https://cloud.githubusercontent.com/assets/20930745/19966890/12892424-a1ce-11e6-8bd2-bc6df57475ba.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19966939/4c8a9f7c-a1ce-11e6-87bd-b44c7977c0e7.png
