### ISSUE TITLE
G2A

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#7450]
**App Name:** G2A
**Bundle ID:** com.g2a
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=895515193">895515193</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/g2a/id895515193?mt=8&uo=4">https://itunes.apple.com/us/app/g2a/id895515193?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** G2A.Com Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/g2a.com/id1105384536?uo=4>© G2A.COM</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/b0/12/6b/b0126b8e-4ff6-7e68-3cc3-90bac95e17ad/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14984522/c4b5c6a4-1108-11e6-9501-7876935107ae.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14984522/c4b5c6a4-1108-11e6-9501-7876935107ae.png)
https://cloud.githubusercontent.com/assets/3090247/14984522/c4b5c6a4-1108-11e6-9501-7876935107ae.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14984521/c4b1925a-1108-11e6-9cf3-dddf801b4c0b.png
