### ISSUE TITLE
MeinProspekt - lokale Angebote

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#7451]
**App Name:** MeinProspekt - lokale Angebote
**Bundle ID:** de.meinprospekt.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1031838771">1031838771</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/meinprospekt-lokale-angebote/id1031838771?mt=8&uo=4">https://itunes.apple.com/de/app/meinprospekt-lokale-angebote/id1031838771?mt=8&uo=4</a>
**App Version:** 6.8.0
**Seller:** MeinProspekt
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/meinprospekt-gmbh/id901369373?uo=4>© MeinProspekt GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/bb/9c/83/bb9c835a-25a8-5124-2567-57a5b1ccd9da/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14988782/07761860-111b-11e6-8fe4-3fb045bc51a1.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14988782/07761860-111b-11e6-8fe4-3fb045bc51a1.png)
https://cloud.githubusercontent.com/assets/3090247/14988782/07761860-111b-11e6-8fe4-3fb045bc51a1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14988783/0777cc6e-111b-11e6-8dd6-66f26aed8b7f.png
