### ISSUE TITLE
Saturn Deutschland

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#7452]
**App Name:** Saturn Deutschland
**Bundle ID:** com.sapient.Saturn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=557562682">557562682</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/saturn-deutschland/id557562682?mt=8&uo=4">https://itunes.apple.com/de/app/saturn-deutschland/id557562682?mt=8&uo=4</a>
**App Version:** 3.9
**Seller:** Saturn Management GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/saturn-online-gmbh/id397751598?uo=4>© Saturn Online GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple18/v4/36/ca/13/36ca13bb-43dc-101c-075a-1785dc56a3e5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14984722/cbb5e56e-1109-11e6-90b5-04d7f2a35827.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14984722/cbb5e56e-1109-11e6-90b5-04d7f2a35827.png)
https://cloud.githubusercontent.com/assets/3090247/14984722/cbb5e56e-1109-11e6-90b5-04d7f2a35827.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14984723/cbbae726-1109-11e6-8e4e-3f5c28c8965f.png
