### ISSUE TITLE
plentymarkets

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#7454]
**App Name:** plentymarkets
**Bundle ID:** eu.plentymarkets.apps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=957702618">957702618</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/plentymarkets/id957702618?mt=8&uo=4">https://itunes.apple.com/us/app/plentymarkets/id957702618?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** plentymarkets GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/plentymarkets-gmbh/id957702617?uo=4>© plentymarkets GmbH</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/f3/c3/c4/f3c3c46f-cf55-40c4-b100-3e2f93d0beaa/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14984887/a2e32010-110a-11e6-9276-1fb6f06f5954.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14984887/a2e32010-110a-11e6-9276-1fb6f06f5954.png)
https://cloud.githubusercontent.com/assets/3090247/14984887/a2e32010-110a-11e6-9276-1fb6f06f5954.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14984886/a2d473b2-110a-11e6-99b6-f2ad2201c9bf.png
