### ISSUE TITLE
Joe Dever's Lone Wolf

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#7455]
**App Name:** Joe Dever's Lone Wolf
**Bundle ID:** com.bulkypix.lonewolf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=670180785">670180785</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/joe-devers-lone-wolf/id670180785?mt=8&uo=4">https://itunes.apple.com/us/app/joe-devers-lone-wolf/id670180785?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** BULKYPIX
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bulkypix/id304521749?uo=4>© Bulkypix</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/08/30/93/08309385-16a1-332b-9b1b-95d502e6c718/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15068866/55b3c340-137a-11e6-9c57-8cd9343e78cd.png)

**Comment by RemiDeluxe** [comment]
I think it would look great without the "cube" logo :)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15068866/55b3c340-137a-11e6-9c57-8cd9343e78cd.png)
https://cloud.githubusercontent.com/assets/2068130/15068866/55b3c340-137a-11e6-9c57-8cd9343e78cd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15068873/64dbf496-137a-11e6-8250-07a1e8d327dc.png
:cold_sweat:
