### ISSUE TITLE
Train Conductor World: European Railway

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7457]
**App Name:** Train Conductor World
**Bundle ID:** com.thevoxelagents.tc3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=932228293">932228293</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/train-conductor-world/id932228293?mt=8&uo=4">https://itunes.apple.com/us/app/train-conductor-world/id932228293?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** The Voxel Agents
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-voxel-agents/id318770095?uo=4">© The Voxel Agents</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/41/f5/78/41f5788a-d16a-de2b-5fe5-2ebe536950db/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20641810/54882066-b400-11e6-93a2-bc85baef08ab.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20641810/54882066-b400-11e6-93a2-bc85baef08ab.png)
https://cloud.githubusercontent.com/assets/2068130/20641810/54882066-b400-11e6-93a2-bc85baef08ab.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20641814/633fbbd2-b400-11e6-98a7-0e736d605d16.png
