### ISSUE TITLE
SpectrumView

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7458]
**App Name:** SpectrumView
**Bundle ID:** com.oxfordwaveresearch.SpectrumView
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=472662922">472662922</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spectrumview/id472662922?mt=8&uo=4">https://itunes.apple.com/us/app/spectrumview/id472662922?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Oxford Wave Research Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/oxford-wave-research-ltd./id472662925?uo=4>© Oxford Wave Research Ltd.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/ca/f6/04/caf60486-91b0-e35b-ba24-d4d995015164/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15052179/a69653be-12fc-11e6-9e3f-b8acf82a4765.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15052179/a69653be-12fc-11e6-9e3f-b8acf82a4765.png)
https://cloud.githubusercontent.com/assets/2068130/15052179/a69653be-12fc-11e6-9e3f-b8acf82a4765.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15052201/bab934ba-12fc-11e6-9ec3-099286a0fe0a.png
Can't do the background...

**Comment by quantum8** [comment]
Looks great to me without the background @dreamnet!
