### ISSUE TITLE
Spectrum Analyzer

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7459]
**App Name:** Spectrum Analyzer
**Bundle ID:** mobi.musicparadise.SpectrumAnalyzermps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=981810895">981810895</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spectrum-analyzer/id981810895?mt=8&uo=4">https://itunes.apple.com/us/app/spectrum-analyzer/id981810895?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Music Paradise, OOO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/music-paradise-llc/id941070953?uo=4>© Music Paradise, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/b3/f5/e2/b3f5e201-f34d-8962-90b2-74bbead1bdaa/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16902108/3dd581f0-4c55-11e6-93e9-7f5fa00db5f2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15054075/fc7c181e-1305-11e6-97a8-4d6410490130.png)
https://cloud.githubusercontent.com/assets/2068130/15054075/fc7c181e-1305-11e6-97a8-4d6410490130.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15054082/0e61b890-1306-11e6-9f07-ed09e6772640.png

**Comment by Anuskuss** [comment]
@dreamnet How about removing the grid?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16902108/3dd581f0-4c55-11e6-93e9-7f5fa00db5f2.png)
https://cloud.githubusercontent.com/assets/2068130/16902108/3dd581f0-4c55-11e6-93e9-7f5fa00db5f2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16902112/4cc0fd20-4c55-11e6-815a-497dfd72a430.png

**Comment by Anuskuss** [comment]
Definitely second one :+1:

**Comment by ivanov007** [comment]
I don't know, I liked the grid, it looked more like the original

**Comment by dreamnet** [comment]
I have no feelings about this... @ivanov007 You can reopen the issue if you want.
