### ISSUE TITLE
MOOYAH Rewards

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7460]
**App Name:** MOOYAH Rewards
**Bundle ID:** com.olo.mooyah
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=545273337">545273337</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mooyah-rewards/id545273337?mt=8&uo=4">https://itunes.apple.com/us/app/mooyah-rewards/id545273337?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Punchh Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/punchh-inc./id386700205?uo=4>© Punchh Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/88/0d/c2/880dc2ac-903d-6ab1-b8ff-a2636199bf43/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14987655/04fc7c32-1116-11e6-8f16-63c3c582fdb0.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14987655/04fc7c32-1116-11e6-8f16-63c3c582fdb0.png)
https://cloud.githubusercontent.com/assets/3090247/14987655/04fc7c32-1116-11e6-8f16-63c3c582fdb0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14987654/04f74e42-1116-11e6-95b3-2be2a02a24a4.png

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/14987655/04fc7c32-1116-11e6-8f16-63c3c582fdb0.png)
https://cloud.githubusercontent.com/assets/3090247/14987655/04fc7c32-1116-11e6-8f16-63c3c582fdb0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/14987654/04f74e42-1116-11e6-95b3-2be2a02a24a4.png
