### ISSUE TITLE
BBVA Send

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7464]
**App Name:** BBVA Send
**Bundle ID:** com.bancomer.bbva.Nexodistribucion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1044879220">1044879220</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bbva-send/id1044879220?uo=4">https://apps.apple.com/us/app/bbva-send/id1044879220?uo=4</a>
**App Version:** 11.75
**Seller:** BBVA Bancomer, S.A.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bbva-bancomer-s-a/id372650200?uo=4">© BBVA Bancomer, S.A.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/3d/47/5f/3d475f82-b597-26fb-1322-9d1d717a671d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59990334-fdb4c000-9642-11e9-896b-a41391992634.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/15054435/196e1762-12cd-11e6-9045-8e606c8610c3.png)
https://cloud.githubusercontent.com/assets/3090247/15054435/196e1762-12cd-11e6-9045-8e606c8610c3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/15054436/19a2e604-12cd-11e6-86d9-5cd174a97314.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59990334-fdb4c000-9642-11e9-896b-a41391992634.png)
https://user-images.githubusercontent.com/2068130/59990334-fdb4c000-9642-11e9-896b-a41391992634.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59990346-0c02dc00-9643-11e9-990c-d46d75e3abef.png
