### ISSUE TITLE
newsAnglr

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7467]
**App Name:** newsAnglr
**Bundle ID:** com.Anglr.NewsAnglr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1059990440">1059990440</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsanglr/id1059990440?mt=8&uo=4">https://itunes.apple.com/us/app/newsanglr/id1059990440?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Continuum Consulting NV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/continuum-consulting-nv/id1085462165?uo=4>© Continuum Consulting NV</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/e1/47/82/e1478269-d9a2-4172-ef47-97bb5c41c416/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093647/f877b49c-148d-11e6-9dd7-72922e1aed2a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093647/f877b49c-148d-11e6-9dd7-72922e1aed2a.png)
https://cloud.githubusercontent.com/assets/2068130/15093647/f877b49c-148d-11e6-9dd7-72922e1aed2a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15093648/08076038-148e-11e6-9322-8b5bf9f75b6e.png
