### ISSUE TITLE
Email - EasilyDo Mail

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7468]
**App Name:** Email - EasilyDo Mail
**Bundle ID:** com.easilydo.mail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=922793622">922793622</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/email-easilydo-mail/id922793622?mt=8&uo=4">https://itunes.apple.com/us/app/email-easilydo-mail/id922793622?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Easilydo Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/easilydo-inc./id481881468?uo=4>© Easilydo Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/1f/50/ff/1f50ffbf-bd1d-9213-fc07-e4a394b3ec0e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093744/ca2833a2-1490-11e6-990d-cb64243ad4c0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093744/ca2833a2-1490-11e6-990d-cb64243ad4c0.png)
https://cloud.githubusercontent.com/assets/2068130/15093744/ca2833a2-1490-11e6-990d-cb64243ad4c0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15093748/dbda48ce-1490-11e6-8a72-23879bbc4a12.png
