### ISSUE TITLE
Record by Under Armour - Exercise Smarter, Feel Better, Live Longer, connects with UA HealthBox

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7469]
**App Name:** Record by Under Armour - Exercise Smarter, Feel Better, Live Longer, connects with UA HealthBox
**Bundle ID:** com.ua.record
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=895425891">895425891</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/record-by-under-armour-exercise/id895425891?mt=8&uo=4">https://itunes.apple.com/us/app/record-by-under-armour-exercise/id895425891?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** MapMyFitness
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/under-armour/id291890423?uo=4>© Under Armour</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/e8/d5/0c/e8d50ce8-f294-900a-51a2-4a08656cad2d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093551/0052ed32-148c-11e6-833e-7050e36d85ec.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093551/0052ed32-148c-11e6-833e-7050e36d85ec.png)
https://cloud.githubusercontent.com/assets/2068130/15093551/0052ed32-148c-11e6-833e-7050e36d85ec.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15093553/0f0a7b6a-148c-11e6-96d3-072b18edaed2.png
