### ISSUE TITLE
Fit Heart

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7470]
**App Name:** Fit Heart
**Bundle ID:** com.apptechies.averageheart
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1076620163">1076620163</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fit-heart/id1076620163?mt=8&uo=4">https://itunes.apple.com/us/app/fit-heart/id1076620163?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Brandon Lehner
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brandon-lehner/id578144185?uo=4>© Brandon Lehner</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/c1/e0/f8/c1e0f85d-7b0c-d5f5-1bca-70a5477d0f91/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093537/8f0b768a-148b-11e6-8601-bef59827186a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093537/8f0b768a-148b-11e6-8601-bef59827186a.png)
https://cloud.githubusercontent.com/assets/2068130/15093537/8f0b768a-148b-11e6-8601-bef59827186a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15093541/9d59671a-148b-11e6-864c-e6b052add279.png
