### ISSUE TITLE
Watch My Health

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7471]
**App Name:** Watch My Health
**Bundle ID:** com.evan-devrieze.Watch-My-Health
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1045023671">1045023671</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watch-my-health/id1045023671?mt=8&uo=4">https://itunes.apple.com/us/app/watch-my-health/id1045023671?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** Evan DeVrieze
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/evan-devrieze/id842259200?uo=4>© Evan DeVrieze</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/84/de/51/84de5160-55a2-cd31-191e-d795c769bd8b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093519/0bb35550-148b-11e6-8adb-afacc2a75dc4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093519/0bb35550-148b-11e6-8adb-afacc2a75dc4.png)
https://cloud.githubusercontent.com/assets/2068130/15093519/0bb35550-148b-11e6-8adb-afacc2a75dc4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15093521/198da428-148b-11e6-8a1b-8c6ce9d6e5d4.png
