### ISSUE TITLE
Mun Moi

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7472]
**App Name:** Mun Moi
**Bundle ID:** com.mobileoperator.paha
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1108009762">1108009762</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fi/app/mun-moi/id1108009762?mt=8&uo=4">https://itunes.apple.com/fi/app/mun-moi/id1108009762?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** European Mobile Operator Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/fi/developer/moi-mobiili-oy/id1108009761?uo=4>© Moi Mobiili Oy</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/4a/71/1b/4a711b11-96b9-52af-c160-7231a7ff7a38/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093575/990beb3c-148c-11e6-953d-852e1580f2e6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15093575/990beb3c-148c-11e6-953d-852e1580f2e6.png)
https://cloud.githubusercontent.com/assets/2068130/15093575/990beb3c-148c-11e6-953d-852e1580f2e6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15093580/a7123682-148c-11e6-8d27-f4c980b4b429.png
