### ISSUE TITLE
Opera VPN: Free unlimited ad blocking VPN

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7476]
**App Name:** Opera VPN: Free unlimited ad blocking VPN
**Bundle ID:** com.opera.vpn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1080756781">1080756781</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/opera-vpn-free-unlimited-ad/id1080756781?mt=8&uo=4">https://itunes.apple.com/us/app/opera-vpn-free-unlimited-ad/id1080756781?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Opera Software ASA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/opera-software-asa/id363729563?uo=4>© Opera Software ASA</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/95/cd/b6/95cdb681-1381-aacc-94ff-ae6531a10c6f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15267860/e052e1a8-19cd-11e6-908e-abd52b5cb20e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15267860/e052e1a8-19cd-11e6-908e-abd52b5cb20e.png)
https://cloud.githubusercontent.com/assets/2068130/15267860/e052e1a8-19cd-11e6-908e-abd52b5cb20e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15267863/eed35f1e-19cd-11e6-912b-7a1b668bc3d7.png
