### ISSUE TITLE
Pin - Clipboard Extension

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7478]
**App Name:** Pin - Clipboard Extension
**Bundle ID:** app.cyan.pin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1039643846">1039643846</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pin-clipboard-extension/id1039643846?mt=8&uo=4">https://itunes.apple.com/us/app/pin-clipboard-extension/id1039643846?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** YING ZHONG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ying-zhong/id928924733?uo=4>© YING ZHONG</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/6b/0e/32/6b0e32eb-9833-69d7-d4e1-9c750f5d81b6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15267798/437d69da-19cc-11e6-807f-584933fd75a0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15267798/437d69da-19cc-11e6-807f-584933fd75a0.png)
https://cloud.githubusercontent.com/assets/2068130/15267798/437d69da-19cc-11e6-807f-584933fd75a0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15267799/52028972-19cc-11e6-8310-f78ebc6c4862.png
