### ISSUE TITLE
Walking Day

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7479]
**App Name:** Walking Day
**Bundle ID:** com.coldyam.kangaroo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967812592">967812592</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/walking-day/id967812592?mt=8&uo=4">https://itunes.apple.com/us/app/walking-day/id967812592?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** WEI JEN TU
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wei-jen-tu/id937948184?uo=4>© WEI JEN TU</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/3c/2e/c4/3c2ec4f6-f03f-bfd4-07d1-71e0ade22b60/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15267766/0f4b9aac-19cb-11e6-9b29-caac4ec49968.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15267766/0f4b9aac-19cb-11e6-9b29-caac4ec49968.png)
https://cloud.githubusercontent.com/assets/2068130/15267766/0f4b9aac-19cb-11e6-9b29-caac4ec49968.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15267769/1ded60ae-19cb-11e6-8a44-5c1a2a091f60.png
