### ISSUE TITLE
OpenTable - Restaurant Reservations

### ISSUE THREAD

**Issue by rentiak** [glasklart/hd#748]
**App Name:** OpenTable - Restaurant Reservations
**Bundle ID:** com.contextoptional.OpenTable
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=296581815">296581815</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/opentable-restaurant-reservations/id296581815?mt=8&uo=4">https://itunes.apple.com/us/app/opentable-restaurant-reservations/id296581815?mt=8&uo=4</a>
**App Version:** 10.0.2
**Seller:** OpenTable, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/opentable-inc./id296581818?uo=4>© OpenTable, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/c0/17/a6/c017a639-db81-c7f7-fa2e-d5afd560fdc5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18928883/5e2f2036-85c2-11e6-8d56-e0fdf24102f7.png)

**Comment by illinikev** [comment]
Update needed.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18928883/5e2f2036-85c2-11e6-8d56-e0fdf24102f7.png)
https://cloud.githubusercontent.com/assets/20930745/18928883/5e2f2036-85c2-11e6-8d56-e0fdf24102f7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18928896/6c86184c-85c2-11e6-9958-fee0033faa3b.png
