### ISSUE TITLE
Pillow: The sleep cycle alarm clock for sleep tracking

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7480]
**App Name:** Pillow: The sleep cycle alarm clock for sleep tracking
**Bundle ID:** com.neybox.Pillow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=878691772">878691772</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pillow-sleep-cycle-alarm-clock/id878691772?mt=8&uo=4">https://itunes.apple.com/us/app/pillow-sleep-cycle-alarm-clock/id878691772?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Panos Spiliotis
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/panos-spiliotis/id624507369?uo=4>© Panos Spiliotis</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/ab/4a/02/ab4a028e-7f6c-092f-b302-209d76dfb7c2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15283502/62d402fa-1b4b-11e6-83a1-3197f7db3be0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15283502/62d402fa-1b4b-11e6-83a1-3197f7db3be0.png)
https://cloud.githubusercontent.com/assets/2068130/15283502/62d402fa-1b4b-11e6-83a1-3197f7db3be0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15283513/7318c0ba-1b4b-11e6-9f8a-2356a18f1357.png
