### ISSUE TITLE
Gboard — Search. GIFs. Emojis & more. Right from your keyboard.

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7482]
**App Name:** Gboard — Search. GIFs. Emojis & more. Right from your keyboard.
**Bundle ID:** com.google.keyboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1091700242">1091700242</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gboard-search.-gifs.-emojis/id1091700242?mt=8&uo=4">https://itunes.apple.com/us/app/gboard-search.-gifs.-emojis/id1091700242?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/59/1c/a8/591ca862-9cff-fddf-49ca-cc064fb83b1d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15282375/2f77a626-1b43-11e6-977e-ce913d40e2f2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15282375/2f77a626-1b43-11e6-977e-ce913d40e2f2.png)
https://cloud.githubusercontent.com/assets/2068130/15282375/2f77a626-1b43-11e6-977e-ce913d40e2f2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15282384/3e281822-1b43-11e6-9a05-c11641747231.png

**Comment by Christian9901** [comment]
rename

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160926-a583d0f4-34c5-11e8-8fc8-8335cf4df371.png)
https://user-images.githubusercontent.com/2068130/38160926-a583d0f4-34c5-11e8-8fc8-8335cf4df371.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38160931-b80439ee-34c5-11e8-8c65-e71c1b28b9e3.png
