### ISSUE TITLE
Amber Weather - free 7x24 weather forecast & current weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7483]
**App Name:** Amber Weather - free 7x24 weather forecast & current weather
**Bundle ID:** com.amberMobile.amberWeather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1105321112">1105321112</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amber-weather-free-7x24-weather/id1105321112?mt=8&uo=4">https://itunes.apple.com/us/app/amber-weather-free-7x24-weather/id1105321112?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Amber Mobile Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/amber-mobile-limited/id1105321111?uo=4>© Amber Mobile Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple18/v4/91/60/28/916028ba-d6a8-4ad3-ef74-bef372b1aecc/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18646329/53d22eca-7eb1-11e6-9f72-8edb46f51ab1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18632903/15212834-7e7a-11e6-8233-da8cc1bf6204.png)
https://cloud.githubusercontent.com/assets/20930745/18632903/15212834-7e7a-11e6-8233-da8cc1bf6204.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18632920/2d5e0fd4-7e7a-11e6-970a-7610679232f3.png

**Comment by dreamnet** [comment]
Just some corner rounding:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18646329/53d22eca-7eb1-11e6-9f72-8edb46f51ab1.png)
https://cloud.githubusercontent.com/assets/2068130/18646329/53d22eca-7eb1-11e6-9f72-8edb46f51ab1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18646346/64be3f4e-7eb1-11e6-866b-c77e1f81bbee.png
