### ISSUE TITLE
Cinemark Theatres

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7484]
**App Name:** Cinemark Theatres
**Bundle ID:** com.cinemark.cinemarkapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=435965836">435965836</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cinemark-theatres/id435965836?mt=8&uo=4">https://itunes.apple.com/us/app/cinemark-theatres/id435965836?mt=8&uo=4</a>
**App Version:** 2.7.0
**Seller:** Cinemark Holdings, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cinemark-usa/id435965839?uo=4>© Cinemark USA</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/67/aa/a4/67aaa455-a6f0-3cc3-0e77-8c7ecc081d25/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15272020/1f67daea-1a66-11e6-9c08-41c72624cda9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15272020/1f67daea-1a66-11e6-9c08-41c72624cda9.png)
https://cloud.githubusercontent.com/assets/2068130/15272020/1f67daea-1a66-11e6-9c08-41c72624cda9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15272021/2eff2ed6-1a66-11e6-8524-f6c13f169418.png
