### ISSUE TITLE
MobyPlanner - Personal Assistant

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7486]
**App Name:** MobyPlanner - Personal Assistant
**Bundle ID:** biz.cadario.MobyPlanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=709249948">709249948</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobyplanner-personal-assistant/id709249948?mt=8&uo=4">https://itunes.apple.com/us/app/mobyplanner-personal-assistant/id709249948?mt=8&uo=4</a>
**App Version:** 2.0.6
**Seller:** MobyPlanner srl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobyplanner-srl/id845371420?uo=4>© MobyPlanner srl</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/a7/9e/ef/a79eefe6-d154-2614-91c9-122cbd8adb53/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/15324071/81b7ac70-1c0a-11e6-8cff-c72626b903ca.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/15324071/81b7ac70-1c0a-11e6-8cff-c72626b903ca.png)
https://cloud.githubusercontent.com/assets/3090247/15324071/81b7ac70-1c0a-11e6-8cff-c72626b903ca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/15324064/74c0d0fa-1c0a-11e6-8458-ff6f909652c1.png
