### ISSUE TITLE
iWidgetApp

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7489]
**App Name:** iWidgetApp
 **Bundle ID:** com.junesiphone.iwidgetapp
 **Version:** 1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:** 
<img src="https://cloud.githubusercontent.com/assets/3781692/15372816/921a4a78-1cff-11e6-92bb-ea8ab957e5e3.PNG" width="150" height="150"> 
 **Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15797877/2cbc1ccc-2a26-11e6-9516-b402bfef5313.png)

**Comment by boxermansr** [comment]
I'm like 100% sure I did this wrong, as far as the icon image. I only see a few .png files and none of them seem to "look" right.. sorry. I still can't get the hang of this cydia app/icon submission stuff :(

**Comment by Anuskuss** [comment]
Save the photo to your Camera Roll first and then upload it to GitHub.

**Comment by boxermansr** [comment]
Thanks - hoping that was done right this time. Once I get it down once I'll be a pro :)

**Comment by Anuskuss** [comment]
@boxermansr You forgot to delete something in your thread (right above **Accepted Artwork:**) :stuck_out_tongue_winking_eye:

**Comment by boxermansr** [comment]
@Anuskuss did that fix it?

**Comment by Anuskuss** [comment]
Almost

**Comment by boxermansr** [comment]
what am I missing, lol.

**Comment by ivanov007** [comment]
@boxermansr there, you were missing part of the text at the end, I fixed it

**Comment by boxermansr** [comment]
No dice getting this one done? Only oddball icon/app on my device now =(

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15797877/2cbc1ccc-2a26-11e6-9516-b402bfef5313.png)
https://cloud.githubusercontent.com/assets/2068130/15797877/2cbc1ccc-2a26-11e6-9516-b402bfef5313.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15797878/3ae7d87c-2a26-11e6-9a96-16f45068eaf0.png
