### ISSUE TITLE
KAMI

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7491]
**App Name:** KAMI
**Bundle ID:** com.stateofplaygames.kami
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=710724007">710724007</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kami/id710724007?mt=8&uo=4">https://itunes.apple.com/us/app/kami/id710724007?mt=8&uo=4</a>
**App Version:** 1.3.4
**Seller:** State of Play Games Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/state-of-play-games/id494615574?uo=4>© State of Play Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/4d/c9/19/4dc919fc-c5fe-ce21-9e2e-b48be1b8676f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16965656/8d1c46b0-4e01-11e6-9f1a-bff26a4abd7a.png)

**Comment by Anuskuss** [comment]
How about only the letters?

**Comment by dreamnet** [comment]
@Anuskuss Something like this?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16898970/8455c38c-4bf2-11e6-83de-666cb028a65c.png)
https://cloud.githubusercontent.com/assets/2068130/16898970/8455c38c-4bf2-11e6-83de-666cb028a65c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16898976/a88bdf5c-4bf2-11e6-9500-66073cd8ead1.png

**Comment by Anuskuss** [comment]
@dreamnet Can I see it without the backround?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16902681/95547a6a-4c66-11e6-9296-3d8ac4d4f85c.png)
https://cloud.githubusercontent.com/assets/2068130/16902681/95547a6a-4c66-11e6-9296-3d8ac4d4f85c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16902686/a4768f38-4c66-11e6-875d-c92e89fde506.png

**Comment by Anuskuss** [comment]
@dreamnet What do you think about tiles?
![](https://cloud.githubusercontent.com/assets/7157389/16904429/4dbcf5f8-4c96-11e6-8b6f-ff44072b730a.png)

**Comment by dreamnet** [comment]
Would be OK for me.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16965656/8d1c46b0-4e01-11e6-9f1a-bff26a4abd7a.png)
https://cloud.githubusercontent.com/assets/2068130/16965656/8d1c46b0-4e01-11e6-9f1a-bff26a4abd7a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16965666/9bc58d5c-4e01-11e6-9b88-7137ae240438.png

**Comment by Anuskuss** [comment]
@dreamnet Well I can't decide which I like more: the plain but empty looking first one or the playful but not so accurate second one. I tend to the second one but if you really dislike it you can choose the first one.

Btw is it just me or is the **K** background whiter that the **I** background (or was this intended)?

**Comment by dreamnet** [comment]
@Anuskuss The last one is fine for me. The effect you mean is intended. This happens when the icon is resized from 1024x1024px to 78x78px and the Glasklart effect is applied. Hard to describe, but to avoid this effect we have to make the 1024x1024px source in a way, that the 78x78px resized image will be pixel-perfect witch is nearly impossible (btw taked too much time).
Check the screenshot, that's the source file from above resized to 78x78px and zoomed in:
https://cloud.githubusercontent.com/assets/2068130/17032462/bbc8246a-4f79-11e6-809c-9ec3ce2a0249.png
