### ISSUE TITLE
OfficeSuite Pro (Mobile Office)

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7492]
**App Name:** OfficeSuite Pro (Mobile Office)
**Bundle ID:** com.mobisystems.OfficeSuite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=675054186">675054186</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/officesuite-pro-mobile-office/id675054186?mt=8&uo=4">https://itunes.apple.com/us/app/officesuite-pro-mobile-office/id675054186?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** MobiSystems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobisystems-inc./id289579214?uo=4>© MobiSystems, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/0d/60/5f/0d605fb8-c9b1-ddb5-b24b-8333c84c8f20/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15798074/07162f42-2a2d-11e6-8fee-d9082aa5156a.png)

**Comment by dreamnet** [comment]
Same as for #7498 (I don't think we need the "pro" in the icon.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15798074/07162f42-2a2d-11e6-8fee-d9082aa5156a.png)
https://cloud.githubusercontent.com/assets/2068130/15798074/07162f42-2a2d-11e6-8fee-d9082aa5156a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15798076/15bc2088-2a2d-11e6-9e49-335276043c67.png
