### ISSUE TITLE
Adguard - Adblock and Privacy Protection for the Web

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7493]
**App Name:** Adguard - Adblock and Privacy Protection for the Web
**Bundle ID:** com.adguard.AdguardExtension
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1047223162">1047223162</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adguard-adblock-privacy-protection/id1047223162?mt=8&uo=4">https://itunes.apple.com/us/app/adguard-adblock-privacy-protection/id1047223162?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** Performiks OOO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/performix/id1047223161?uo=4>© Performix</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/7b/70/12/7b701245-befb-e234-a5a2-8352a5e9c018/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15598723/550eeff0-23dd-11e6-8cc6-d93eb9551915.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15598723/550eeff0-23dd-11e6-8cc6-d93eb9551915.png)
https://cloud.githubusercontent.com/assets/2068130/15598723/550eeff0-23dd-11e6-8cc6-d93eb9551915.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15598734/62a98a30-23dd-11e6-95b2-b5aa600b8e98.png
