### ISSUE TITLE
Boxer For Gmail, Outlook, Hotmail, and IMAP Email - Lite

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7495]
**App Name:** Boxer For Gmail, Outlook, Hotmail, and IMAP Email - Lite
**Bundle ID:** com.getboxer.BoxerFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=695900302">695900302</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boxer-for-gmail-outlook-hotmail/id695900302?mt=8&uo=4">https://itunes.apple.com/us/app/boxer-for-gmail-outlook-hotmail/id695900302?mt=8&uo=4</a>
**App Version:** 6.0.4
**Seller:** Bodkin Software Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/taskbox/id561712086?uo=4>© Taskbox</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/8c/ba/9b/8cba9b9d-d5ed-8f77-2ff7-a82675a51144/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9025634/a3e350ec-390c-11e5-8cff-65cd76be7ae3.png)

**Comment by ivanov007** [comment]
same icon as #2822 here's @dreamnet icon:

Alternate Version:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9025634/a3e350ec-390c-11e5-8cff-65cd76be7ae3.png)
https://cloud.githubusercontent.com/assets/2068130/9025634/a3e350ec-390c-11e5-8cff-65cd76be7ae3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9025635/b261167c-390c-11e5-853f-1e9f2fee8d46.png
