### ISSUE TITLE
Battery Percentage - Your Device Doctor

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7496]
**App Name:** Battery Percentage - Your Device Doctor
**Bundle ID:** com.ubg.batterylife
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1095552310">1095552310</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/battery-percentage-your-device/id1095552310?mt=8&uo=4">https://itunes.apple.com/us/app/battery-percentage-your-device/id1095552310?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Tran Manh Quan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tran-manh-quan/id950930269?uo=4>© Tran Manh Quan</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/e2/7e/e0/e27ee006-aacb-d705-9019-ad110722acfd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15797934/e6bc1338-2a27-11e6-813c-f65ffe4e4b50.png)

**Comment by dreamnet** [comment]
Same as #3890. Icon by @n0mar.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15797934/e6bc1338-2a27-11e6-813c-f65ffe4e4b50.png)
https://cloud.githubusercontent.com/assets/2068130/15797934/e6bc1338-2a27-11e6-813c-f65ffe4e4b50.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15797935/f759e2ce-2a27-11e6-904d-b1e4ed8a5fc0.png
