### ISSUE TITLE
Battery Life - Your Device Doctor

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7497]
**App Name:** Battery Life - Your Device Doctor
**Bundle ID:** com.bachle.battery
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1116547088">1116547088</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/battery-life-your-device-doctor/id1116547088?mt=8&uo=4">https://itunes.apple.com/us/app/battery-life-your-device-doctor/id1116547088?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Bach Le
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bach-le/id1116547087?uo=4>© Bach Le</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/01/1b/c8/011bc864-36c2-5c65-d35e-c66c4a942b1a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15798197/11ae5368-2a31-11e6-8648-61bacf20b581.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15798197/11ae5368-2a31-11e6-8648-61bacf20b581.png)
https://cloud.githubusercontent.com/assets/2068130/15798197/11ae5368-2a31-11e6-8648-61bacf20b581.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15798199/257072fa-2a31-11e6-8cdd-e7dedfaa7f8f.png
