### ISSUE TITLE
Webabit

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7499]
**App Name:** Webabit
**Bundle ID:** com.okko.widgetbrowse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955690119">955690119</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/webabit/id955690119?mt=8&uo=4">https://itunes.apple.com/us/app/webabit/id955690119?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** Kyoko Matsuyama
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kyoko-matsuyama/id849254237?uo=4>© Kyoko Matsuyama</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/f6/6a/3a/f66a3a9b-b9aa-6dfc-0b69-cea1ce14eb38/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16360966/c6f915a2-3b7d-11e6-8755-ea057349be54.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16360966/c6f915a2-3b7d-11e6-8755-ea057349be54.png)
https://cloud.githubusercontent.com/assets/2068130/16360966/c6f915a2-3b7d-11e6-8755-ea057349be54.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16360969/d51d24fc-3b7d-11e6-9b63-76d82fd2fcdc.png
