### ISSUE TITLE
Aeris Pulse Weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7500]
**App Name:** Aeris Pulse Weather
**Bundle ID:** com.hamweather.AerisPulse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=925056174">925056174</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aeris-pulse-weather/id925056174?mt=8&uo=4">https://itunes.apple.com/us/app/aeris-pulse-weather/id925056174?mt=8&uo=4</a>
**App Version:** 1.2.3
**Seller:** Media Logic Group, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/media-logic-group-llc/id925056173?uo=4>© Media Logic Group, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/7c/d5/9a/7cd59a8f-25d7-54fc-129d-9c8df0edb0b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18648828/a49d2f20-7ebc-11e6-8e24-11f094ba37d9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18625706/8c8e8a94-7e50-11e6-9cd8-de0a9c251997.png)
https://cloud.githubusercontent.com/assets/20930745/18625706/8c8e8a94-7e50-11e6-9cd8-de0a9c251997.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18625722/a16750b8-7e50-11e6-885e-3b00396ab2f4.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18648828/a49d2f20-7ebc-11e6-8e24-11f094ba37d9.png)
https://cloud.githubusercontent.com/assets/2068130/18648828/a49d2f20-7ebc-11e6-8e24-11f094ba37d9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18648846/b4351f1a-7ebc-11e6-85e0-76f060ac489f.png
