### ISSUE TITLE
Folklor - Discover and recommend movies, tv shows, videos, books or games

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7501]
**App Name:** Folklor - Discover and recommend movies, tv shows, videos, books or games
**Bundle ID:** it.folklor.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1073578964">1073578964</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/folklor-discover-recommend/id1073578964?mt=8&uo=4">https://itunes.apple.com/us/app/folklor-discover-recommend/id1073578964?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Nexa Company Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nexa/id1073578963?uo=4>© Nexa</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/ff/fa/d9/fffad981-9ea6-7e34-3333-7c61dbca991f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15971309/c1b8886c-2f38-11e6-9192-2849ffe1342a.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15971309/c1b8886c-2f38-11e6-9192-2849ffe1342a.png)
https://cloud.githubusercontent.com/assets/10730122/15971309/c1b8886c-2f38-11e6-9192-2849ffe1342a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/15971310/c1b8e97e-2f38-11e6-84a6-20a40af0aaa8.png
