### ISSUE TITLE
Arrival - GPS assistant: ETA, travel time and directions to your favorite locations

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7502]
**App Name:** Arrival - GPS assistant: ETA, travel time and directions to your favorite locations
**Bundle ID:** com.janniklasfreundt.arrivalios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1016288594">1016288594</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/arrival-gps-assistant-eta/id1016288594?mt=8&uo=4">https://itunes.apple.com/us/app/arrival-gps-assistant-eta/id1016288594?mt=8&uo=4</a>
**App Version:** 1.10.2
**Seller:** Jan-Niklas FREUNDT
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jan-niklas-freundt/id420182691?uo=4>© Jan-Niklas FREUNDT</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/2c/fe/2a/2cfe2a6b-7734-b8bc-0cbb-01ad106f0fbd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17277518/15a44612-5745-11e6-9bcc-29552675d715.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17277518/15a44612-5745-11e6-9bcc-29552675d715.png)
https://cloud.githubusercontent.com/assets/2068130/17277518/15a44612-5745-11e6-9bcc-29552675d715.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17277520/2b96a2f8-5745-11e6-939d-53d9023fe1b7.png
