### ISSUE TITLE
International Calling App | KeepCalling - Call abroad over WiFi and 3G/4G at great rates

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7503]
**App Name:** International Calling App | KeepCalling - Call abroad over WiFi and 3G/4G at great rates
**Bundle ID:** com.keepcalling.KeepCalling
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=518708790">518708790</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/international-calling-app/id518708790?mt=8&uo=4">https://itunes.apple.com/us/app/international-calling-app/id518708790?mt=8&uo=4</a>
**App Version:** 2.5.3
**Seller:** Miron Enterprises, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/miron-enterprises-llc/id518708793?uo=4>© Miron Enterprises, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/bc/33/d9/bc33d950-f668-0035-47cf-081a95afa6b6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15971283/a594b3f4-2f38-11e6-921b-4229b137a7b3.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15971283/a594b3f4-2f38-11e6-921b-4229b137a7b3.png)
https://cloud.githubusercontent.com/assets/10730122/15971283/a594b3f4-2f38-11e6-921b-4229b137a7b3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/15971282/a59063b2-2f38-11e6-8782-7eac31d95f27.png
