### ISSUE TITLE
Create Animation Gif from Burst Photo / Video - GifMov

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7504]
**App Name:** Create Animation Gif from Burst Photo / Video - GifMov
**Bundle ID:** net.reafo.app.B-Compo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049226541">1049226541</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/create-animation-gif-from/id1049226541?mt=8&uo=4">https://itunes.apple.com/us/app/create-animation-gif-from/id1049226541?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** REAFO CO., LTD.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/reafo-co.-ltd./id622345531?uo=4>© REAFO CO., LTD.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/85/83/06/858306f9-2d91-6dca-32a9-9d07eadc2f15/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15971520/be285f5a-2f39-11e6-8c8a-a6b3cbf0851f.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15971520/be285f5a-2f39-11e6-8c8a-a6b3cbf0851f.png)
https://cloud.githubusercontent.com/assets/10730122/15971520/be285f5a-2f39-11e6-8c8a-a6b3cbf0851f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/15971521/be2b0886-2f39-11e6-8f5b-4229da2b7504.png
