### ISSUE TITLE
CBS

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7505]
**App Name:** CBS
**Bundle ID:** com.cbsvideo.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=530168168">530168168</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cbs/id530168168?mt=8&uo=4">https://itunes.apple.com/us/app/cbs/id530168168?mt=8&uo=4</a>
**App Version:** 4.7.1
**Seller:** CBS Mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cbs-interactive/id295669712?mt=8&uo=4>© CBS Interactive</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/10/2a/28/102a28aa-7aac-0718-1727-0b74db264adb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18616470/327bc844-7d8a-11e6-98ec-bfc79f9eec61.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15971225/6c3cfbd4-2f38-11e6-90c1-0d73cd920530.png)
https://cloud.githubusercontent.com/assets/10730122/15971225/6c3cfbd4-2f38-11e6-90c1-0d73cd920530.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/15971226/6c570b00-2f38-11e6-8ba0-e946efd69efd.png

**Comment by l8er4now** [comment]
Needs to be resized.

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18616470/327bc844-7d8a-11e6-98ec-bfc79f9eec61.png)

https://cloud.githubusercontent.com/assets/3704186/18616470/327bc844-7d8a-11e6-98ec-bfc79f9eec61.png

https://cloud.githubusercontent.com/assets/3704186/18616472/39d262d8-7d8a-11e6-8bcd-3ec4878fbd07.png
