### ISSUE TITLE
OpinionAPP

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7506]
**App Name:** OpinionAPP
**Bundle ID:** com.cint.panelistportal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1053900409">1053900409</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/opinionapp/id1053900409?mt=8&uo=4">https://itunes.apple.com/us/app/opinionapp/id1053900409?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** Cint AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cint-ab/id1053900408?uo=4>© Cint AB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/e3/c9/54/e3c954ad-edcf-838a-5094-6ebb55bb041f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356951/d6c59540-3ae8-11e6-8447-4f8ea0d8f3cb.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356951/d6c59540-3ae8-11e6-8447-4f8ea0d8f3cb.png)
https://cloud.githubusercontent.com/assets/10730122/16356951/d6c59540-3ae8-11e6-8447-4f8ea0d8f3cb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16356952/d6e1b0b8-3ae8-11e6-8a5c-ebdaa13213e8.png
