### ISSUE TITLE
Cardiogram - Watch your Heart Rate

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7509]
**App Name:** Cardiogram - Watch your Heart Rate
**Bundle ID:** com.cardiogram.ios.heart
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1000017994">1000017994</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cardiogram-watch-your-heart/id1000017994?mt=8&uo=4">https://itunes.apple.com/us/app/cardiogram-watch-your-heart/id1000017994?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Cardiogram Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cardiogram-inc./id1000017993?uo=4>© Cardiogram, Inc.</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/b4/22/b5/b422b5c1-0145-6ea1-21d0-d0fd376e4cf0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19693594/63c69054-9adc-11e6-9582-7fe4b448edd7.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16357072/7c4e135e-3aec-11e6-9fff-2671d9cf0453.png)
https://cloud.githubusercontent.com/assets/10730122/16357072/7c4e135e-3aec-11e6-9fff-2671d9cf0453.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16357071/7c4de456-3aec-11e6-9bb2-2875aec5869f.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Cardiogram - Watch your Heart Rate
**Bundle ID:** com.cardiogram.ios.heart
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1000017994">1000017994</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cardiogram-watch-your-heart/id1000017994?mt=8&uo=4">https://itunes.apple.com/us/app/cardiogram-watch-your-heart/id1000017994?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Cardiogram Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cardiogram-inc./id1000017993?uo=4>© Cardiogram, Inc.</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/b4/22/b5/b422b5c1-0145-6ea1-21d0-d0fd376e4cf0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19693594/63c69054-9adc-11e6-9582-7fe4b448edd7.png)
https://cloud.githubusercontent.com/assets/20930745/19693594/63c69054-9adc-11e6-9582-7fe4b448edd7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19693618/7346562c-9adc-11e6-9c6a-2ab1952f057c.png
