### ISSUE TITLE
[DUPLICATE of #3690]

### ISSUE THREAD

**Issue by rentiak** [glasklart/hd#751]
**App Name:** Calorie Counter & Diet Tracker by MyFitnessPal
**Bundle ID:** com.myfitnesspal.mfp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=341232718">341232718</a>
**iPhone Icon Name:** MFP_app_icon_114x114.png
**Icon Names:** MFP_app_icon_57x57.png | MFP_app_icon_114x114.png | MFP_app_icon_120x120.png
**iTunes URL:** https://itunes.apple.com/us/app/calorie-counter-diet-tracker/id341232718?mt=8&uo=4
**App Version:** 4.0.2
**Seller:** MyFitnessPal LLc
**Supported Devices:** iPhone4S, iPhone5, iPadFourthGen, iPhone-3GS, iPad2Wifi, iPad23G, iPadThirdGen4G, iPadMini, iPodTouchourthGen, iPhone4, iPadMini4G, iPhone5s, iPadFourthGen4G, iPadWifi, iPhone5c, iPodTouchThirdGen, iPodTouchFifthGen, iPad3G, iPadThirdGen
**Original Artwork:**
<img src="http://a984.phobos.apple.com/us/r30/Purple/v4/16/e5/de/16e5deb9-73c0-34af-284a-cebbb82a3194/mzl.wbaxntvm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=http://i.imgur.com/vNe9Z0f.png)

**Comment by XPEric** [comment]
Needs update.
