### ISSUE TITLE
Gadget Flow

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7510]
**App Name:** Gadget Flow
**Bundle ID:** com.CloudieNetwork.GadgetFlow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=625707695">625707695</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gadget-flow/id625707695?mt=8&uo=4">https://itunes.apple.com/us/app/gadget-flow/id625707695?mt=8&uo=4</a>
**App Version:** 5.4.6
**Seller:** Gadget Flow Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gadget-flow-inc/id394616534?uo=4">© Gadget Flow Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple117/v4/0e/fa/d6/0efad67d-5655-2eca-d876-a9ec3954bb78/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27511193-490f591a-591f-11e7-95ea-4abf7c0b6514.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16158817/7372a4ee-34bf-11e6-99ae-09fbfd65f05a.png)
https://cloud.githubusercontent.com/assets/10730122/16158817/7372a4ee-34bf-11e6-99ae-09fbfd65f05a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16158818/7372da04-34bf-11e6-885c-e2e59563b6d6.png

**Comment by l8er4now** [comment]
Needs an update

**App Name:** Gadget Flow
**Bundle ID:** com.CloudieNetwork.GadgetFlow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=625707695">625707695</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gadget-flow/id625707695?mt=8&uo=4">https://itunes.apple.com/us/app/gadget-flow/id625707695?mt=8&uo=4</a>
**App Version:** 5.4.6
**Seller:** Gadget Flow Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gadget-flow-inc/id394616534?uo=4">© Gadget Flow Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple117/v4/0e/fa/d6/0efad67d-5655-2eca-d876-a9ec3954bb78/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27511193-490f591a-591f-11e7-95ea-4abf7c0b6514.png)
https://user-images.githubusercontent.com/2068130/27511193-490f591a-591f-11e7-95ea-4abf7c0b6514.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27511199-5971a5ec-591f-11e7-8f2d-23edfda1f940.png
