### ISSUE TITLE
Tap Tycoon - Country vs Country

### ISSUE THREAD

**Issue by Meyers09** [glasklart/hd#7511]
**App Name:** Tap Tycoon - Country vs Country
**Bundle ID:** com.gamehivecorp.tapmoney
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1058709520">1058709520</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tap-tycoon-country-vs-country/id1058709520?mt=8&uo=4">https://itunes.apple.com/us/app/tap-tycoon-country-vs-country/id1058709520?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Game Hive Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/game-hive-corp./id443272129?uo=4>© Game Hive Corp.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/24/c7/08/24c708d7-5791-cfc9-8ff8-917399a02c1a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16282142/b6d86ca8-38c7-11e6-9436-f3c9e4568985.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16282142/b6d86ca8-38c7-11e6-9436-f3c9e4568985.png)
https://cloud.githubusercontent.com/assets/2068130/16282142/b6d86ca8-38c7-11e6-9436-f3c9e4568985.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16282154/c41e7d8a-38c7-11e6-9628-ffb46153990a.png
