### ISSUE TITLE
TopBuzz - Free & funny video, GIF & news

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7512]
**App Name:** TopBuzz - Free & funny video, GIF & news
**Bundle ID:** com.alex.NewsMaster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049682098">1049682098</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/topbuzz-free-funny-video-gif/id1049682098?mt=8&uo=4">https://itunes.apple.com/us/app/topbuzz-free-funny-video-gif/id1049682098?mt=8&uo=4</a>
**App Version:** 2.6.0
**Seller:** Matrix Decomposing Ad Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/topbuzz/id1152332967?uo=4">© TopBuzz</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/9c/6f/44/9c6f4479-13ad-69bf-2bfe-4ce141cc56c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19979887/53ee57a8-a1fc-11e6-8626-ad87a9ef0a28.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16158709/c97f6620-34be-11e6-97d5-2191bded785c.png)
https://cloud.githubusercontent.com/assets/10730122/16158709/c97f6620-34be-11e6-97d5-2191bded785c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16158708/c97de9b2-34be-11e6-999b-62bb5d993755.png

**Comment by l8er4now** [comment]
Needs a bit of an update.

**App Name:** News Master
**Bundle ID:** com.alex.NewsMaster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049682098">1049682098</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/news-master/id1049682098?mt=8&uo=4">https://itunes.apple.com/us/app/news-master/id1049682098?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** heng shi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/heng-shi/id976480240?uo=4>© heng shi</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/c3/23/bc/c323bc8c-afbd-586d-faa7-6274905bf827/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712493/6778a0d6-4689-11e6-9e65-cb9b73920ac5.png)
https://cloud.githubusercontent.com/assets/2068130/16712493/6778a0d6-4689-11e6-9e65-cb9b73920ac5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712496/7921a7b0-4689-11e6-895f-9d56b57a0051.png

**Comment by l8er4now** [comment]
Needs another update.

**App Name:** TopBuzz - Free & funny video, GIF & news
**Bundle ID:** com.alex.NewsMaster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049682098">1049682098</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/topbuzz-free-funny-video-gif/id1049682098?mt=8&uo=4">https://itunes.apple.com/us/app/topbuzz-free-funny-video-gif/id1049682098?mt=8&uo=4</a>
**App Version:** 2.6.0
**Seller:** Matrix Decomposing Ad Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/topbuzz/id1152332967?uo=4">© TopBuzz</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/9c/6f/44/9c6f4479-13ad-69bf-2bfe-4ce141cc56c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19979887/53ee57a8-a1fc-11e6-8626-ad87a9ef0a28.png)
https://cloud.githubusercontent.com/assets/2068130/19979887/53ee57a8-a1fc-11e6-8626-ad87a9ef0a28.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19979914/656d6622-a1fc-11e6-91b3-934f5426c71f.png
