### ISSUE TITLE
AZZL

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7513]
**App Name:** AZZL
**Bundle ID:** com.jutiful.azzl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=640484311">640484311</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/azzl/id640484311?mt=8&uo=4">https://itunes.apple.com/us/app/azzl/id640484311?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Jutiful Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jutiful/id582966637?uo=4">© Jutiful</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple30/v4/70/6b/85/706b8537-6275-d5e2-8f82-d46491aedb47/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38458993-7dca6598-3aa4-11e8-98a4-f8f28a64aba1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16280702/41f7b8ae-38c1-11e6-99e0-c822ea4ed1d4.png)
https://cloud.githubusercontent.com/assets/2068130/16280702/41f7b8ae-38c1-11e6-99e0-c822ea4ed1d4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16280716/4f7735d6-38c1-11e6-81fd-3f910c173951.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38458993-7dca6598-3aa4-11e8-98a4-f8f28a64aba1.png)
https://user-images.githubusercontent.com/2068130/38458993-7dca6598-3aa4-11e8-98a4-f8f28a64aba1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38459000-8f293d1e-3aa4-11e8-8694-6c0a87702950.png
