### ISSUE TITLE
Lieferservice.de

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7514]
**App Name:** Lieferservice.de
**Bundle ID:** Lieferservice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=333213927">333213927</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/lieferservice-de/id333213927?uo=4">https://apps.apple.com/us/app/lieferservice-de/id333213927?uo=4</a>
**App Version:** 4.22.0
**Seller:** Takeaway.com
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/takeaway-com/id329472762?uo=4">© Takeaway.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/5c/44/d4/5c44d468-48b8-efc4-fbe8-b596ef3602ec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680988-c093cd80-9e8d-11e9-9d18-93707a7fc508.png)

**Comment by Anuskuss** [comment]
Same as #6113

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8896032/4fc9de6c-33ef-11e5-9834-8c03f1202978.png)
https://cloud.githubusercontent.com/assets/10730122/8896032/4fc9de6c-33ef-11e5-9834-8c03f1202978.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16158582/12b35d02-34be-11e6-9d88-bcefc93f1e1b.png

**Comment by dreamnet** [comment]
Small update.
Icon by @2Qt2beStr8 
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60680988-c093cd80-9e8d-11e9-9d18-93707a7fc508.png)
https://user-images.githubusercontent.com/20930745/60680988-c093cd80-9e8d-11e9-9d18-93707a7fc508.png

Source:
https://user-images.githubusercontent.com/20930745/60680990-c1c4fa80-9e8d-11e9-9041-6507db6dfafe.png
