### ISSUE TITLE
Rotare!

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7515]
**App Name:** Rotare!
**Bundle ID:** com.appsolutegames.rotare
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1099511409">1099511409</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rotare!/id1099511409?mt=8&uo=4">https://itunes.apple.com/us/app/rotare!/id1099511409?mt=8&uo=4</a>
**App Version:** 1.12
**Seller:** Appsolute Games LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appsolute-games-llc/id602062365?uo=4>© Appsolute Games LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/89/fe/ad/89fead14-9b18-4488-80e6-30f65aa7ec07/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16277136/f0f4d5ae-38b1-11e6-9d9e-5bebcedf2cb7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16277136/f0f4d5ae-38b1-11e6-9d9e-5bebcedf2cb7.png)
https://cloud.githubusercontent.com/assets/2068130/16277136/f0f4d5ae-38b1-11e6-9d9e-5bebcedf2cb7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16277147/febaa448-38b1-11e6-9316-22f1d2f040a7.png
