### ISSUE TITLE
Fantasy Football: NFL News, Picks & Rankings

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7516]
**App Name:** Fantasy Football: NFL News, Picks & Rankings
**Bundle ID:** com.playerline.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324319768">324319768</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasy-football-nfl-news/id324319768?mt=8&uo=4">https://itunes.apple.com/us/app/fantasy-football-nfl-news/id324319768?mt=8&uo=4</a>
**App Version:** 6.0
**Seller:** Playerline
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/playerline/id324319771?uo=4>© Playerline</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple18/v4/dc/02/89/dc0289d5-2fa1-91af-e529-e5b0698ccd94/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16158527/d3ef82f8-34bd-11e6-9177-92a98466e2b8.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16158527/d3ef82f8-34bd-11e6-9177-92a98466e2b8.png)
https://cloud.githubusercontent.com/assets/10730122/16158527/d3ef82f8-34bd-11e6-9177-92a98466e2b8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16158528/d3f113f2-34bd-11e6-9dbd-b5453b2aaaa9.png

**Comment by l8er4now** [comment]
Needs a minor update.

**App Name:** Fantasy Football: News, Picks & Rankings
**Bundle ID:** com.playerline.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324319768">324319768</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasy-football-news-picks/id324319768?mt=8&uo=4">https://itunes.apple.com/us/app/fantasy-football-news-picks/id324319768?mt=8&uo=4</a>
**App Version:** 6.1.3
**Seller:** Playerline
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/playerline/id324319771?uo=4>© Playerline</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple71/v4/68/d3/d1/68d3d1d5-2fe0-bfaa-98ed-0bf4371c1a38/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
@l8er4now How does the icon on the device look?

**Comment by l8er4now** [comment]
The p is smaller and the word fantasy is under the p. On well.

**Comment by dreamnet** [comment]
@l8er4now Can you extract the icon from your devive or post a screenshot?
