### ISSUE TITLE
Hesburger

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7517]
**App Name:** Hesburger
**Bundle ID:** fi.hesburger.Hesburger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1062839905">1062839905</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fi/app/hesburger/id1062839905?mt=8&uo=4">https://itunes.apple.com/fi/app/hesburger/id1062839905?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Burger-In Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/fi/developer/hesburger/id1062839904?uo=4>© Hesburger</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/c9/3b/c8/c93bc885-bbb0-bcd5-14d6-c13a611cb887/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/16177703/62d8c802-35fa-11e6-9290-024ac5d58ac2.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=(https://cloud.githubusercontent.com/assets/3090247/16177703/62d8c802-35fa-11e6-9290-024ac5d58ac2.png)
(https://cloud.githubusercontent.com/assets/3090247/16177703/62d8c802-35fa-11e6-9290-024ac5d58ac2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/16177702/62d8ad86-35fa-11e6-8691-fae110c1fb86.png
