### ISSUE TITLE
K-ruoka

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7518]
**App Name:** K-ruoka
**Bundle ID:** fi.ruokakesko.k-ruoka
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1012903895">1012903895</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fi/app/k-ruoka/id1012903895?mt=8&uo=4">https://itunes.apple.com/fi/app/k-ruoka/id1012903895?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** App-Hallinta Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/fi/developer/ruokakesko/id520821403?uo=4>© Ruokakesko</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/0a/92/09/0a9209dc-831f-b376-7be5-00e77d6c16cb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/16177749/5d25e132-35fb-11e6-8e21-61cd654bfb7f.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/16177749/5d25e132-35fb-11e6-8e21-61cd654bfb7f.png)
https://cloud.githubusercontent.com/assets/3090247/16177749/5d25e132-35fb-11e6-8e21-61cd654bfb7f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/16177750/5d266544-35fb-11e6-93d4-674b942bc44d.png)
