### ISSUE TITLE
Hertz Car Rentals

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7519]
**App Name:** Hertz Car Rentals
**Bundle ID:** com.hertz.Hertz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=352114300">352114300</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/hertz-car-rentals/id352114300?uo=4">https://apps.apple.com/gb/app/hertz-car-rentals/id352114300?uo=4</a>
**App Version:** 5.33
**Seller:** The Hertz Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/the-hertz-corporation/id352114303?uo=4">© The Hertz Corporation</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/da/24/37/da243763-26e9-ed58-3ed5-6e9c6544c2d0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62393219-ddddb980-b569-11e9-8915-792665dd1cf3.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16208276/9df9b558-3731-11e6-985e-a40aba1fd111.png)
https://cloud.githubusercontent.com/assets/10730122/16208276/9df9b558-3731-11e6-985e-a40aba1fd111.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16208275/9de0e532-3731-11e6-8b8b-db4ef2ff6ffe.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62393219-ddddb980-b569-11e9-8915-792665dd1cf3.png)
https://user-images.githubusercontent.com/20930745/62393219-ddddb980-b569-11e9-8915-792665dd1cf3.png

Source:
https://user-images.githubusercontent.com/20930745/62393223-dfa77d00-b569-11e9-8aa7-e5a0a869e3a6.png

**Comment by Sly-Fi** [comment]
They seem to have changed the app name to "Hertz Car Rental" with the new **Bundle ID:** com.hertz.HertzDigital 
I am over my limit so can't open a new issue for this if one should be required

**Comment by dreamnet** [comment]
@Sly-Fi I think you are talking about a different app. For this one nothing has changed. Please check the iTunes ID (1456169098 ?) and open a new issue.
