### ISSUE TITLE
Temple Run 2

### ISSUE THREAD

**Issue by alderz** [glasklart/hd#752]
**App Name:** Temple Run 2
**Bundle ID:** com.imangi.templerun2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=572395608">572395608</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/temple-run-2/id572395608?mt=8&uo=4">https://itunes.apple.com/us/app/temple-run-2/id572395608?mt=8&uo=4</a>
**App Version:** 1.28
**Seller:** Imangi Studios, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/imangi-studios-llc/id284899742?uo=4>© Imangi Studios, LLC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/e2/69/32/e269329f-e2da-8bb0-8bb4-9b5f3b779c73/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18999718/578d535a-873f-11e6-8414-06df24db79f5.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18999718/578d535a-873f-11e6-8414-06df24db79f5.png)
https://cloud.githubusercontent.com/assets/20930745/18999718/578d535a-873f-11e6-8414-06df24db79f5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18999748/70c95774-873f-11e6-8e36-15a5233e4d30.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Fine! 👍
