### ISSUE TITLE
Ultimate Calendar - Complete Calendar Solution

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7522]
**App Name:** Ultimate Calendar - Complete Calendar Solution
**Bundle ID:** com.ronelfernandez.ultimate.calendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1109246776">1109246776</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ultimate-calendar-complete/id1109246776?mt=8&uo=4">https://itunes.apple.com/us/app/ultimate-calendar-complete/id1109246776?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** RONEL FERNANDEZ
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ronel-fernandez/id862281618?uo=4>© RONEL FERNANDEZ</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/7c/70/3b/7c703b88-eac8-81b9-b99b-ba176e75a3f6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16275964/baea54fc-38ac-11e6-81e4-0cdc4544e89b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16275964/baea54fc-38ac-11e6-81e4-0cdc4544e89b.png)
https://cloud.githubusercontent.com/assets/2068130/16275964/baea54fc-38ac-11e6-81e4-0cdc4544e89b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16275973/c9e60e38-38ac-11e6-8557-14fba2b61ccb.png
