### ISSUE TITLE
T-Mobile Tuesdays

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7523]
**App Name:** T-Mobile Tuesdays
**Bundle ID:** com.tmobile.tuesdays
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1111876388">1111876388</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/t-mobile-tuesdays/id1111876388?mt=8&uo=4">https://itunes.apple.com/us/app/t-mobile-tuesdays/id1111876388?mt=8&uo=4</a>
**App Version:** 5.3.0
**Seller:** T-Mobile USA, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/t-mobile/id525560781?uo=4">© T-Mobile</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/af/62/1d/af621dd1-fc44-ed14-0dcd-9b4822575280/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/51438651-3aa11300-1caf-11e9-80d0-f1296cca8f44.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16291611/218f2a6e-3909-11e6-9e04-9ece833b8618.png)
https://cloud.githubusercontent.com/assets/10730122/16291611/218f2a6e-3909-11e6-9e04-9ece833b8618.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16291612/21a74522-3909-11e6-9dd0-55edfc67a8b9.png

**Comment by dreamnet** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/51438651-3aa11300-1caf-11e9-80d0-f1296cca8f44.png)
https://user-images.githubusercontent.com/2068130/51438651-3aa11300-1caf-11e9-80d0-f1296cca8f44.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/51438656-50aed380-1caf-11e9-86a1-ff6bd2102e7c.png
