### ISSUE TITLE
Stringify

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7524]
**App Name:** Stringify
**Bundle ID:** com.stringify.stringify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1012539039">1012539039</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stringify/id1012539039?mt=8&uo=4">https://itunes.apple.com/us/app/stringify/id1012539039?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** Stringify
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stringify-inc./id1009413901?uo=4>© Stringify, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/1b/0c/43/1b0c43db-417d-905e-4268-e04f84f09c1b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16310950/d5961de6-396e-11e6-80b6-a4abd2b85cf5.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16310950/d5961de6-396e-11e6-80b6-a4abd2b85cf5.png)
https://cloud.githubusercontent.com/assets/10730122/16310950/d5961de6-396e-11e6-80b6-a4abd2b85cf5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16311089/6a5f1bee-396f-11e6-8fb9-d89c406df73b.png
