### ISSUE TITLE
Zillow Digs - Interior Design, Project Costs, and Paint Visualizer

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7525]
**App Name:** Zillow Digs - Interior Design, Project Costs, and Paint Visualizer
**Bundle ID:** com.zillow.digs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=591141063">591141063</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zillow-digs-interior-design/id591141063?mt=8&uo=4">https://itunes.apple.com/us/app/zillow-digs-interior-design/id591141063?mt=8&uo=4</a>
**App Version:** 3.3.42
**Seller:** Zillow, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zillow.com/id310738698?uo=4>© Zillow.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/30/08/fb/3008fb44-656c-6aee-b08d-568b8d7d323f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/16324716/84524af0-397c-11e6-86a9-d284c470c2b8.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/16324716/84524af0-397c-11e6-86a9-d284c470c2b8.png)
https://cloud.githubusercontent.com/assets/3090247/16324716/84524af0-397c-11e6-86a9-d284c470c2b8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/16324717/8458d596-397c-11e6-8a9d-d848f58c329c.png)
