### ISSUE TITLE
Combo Heroes

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7527]
**App Name:** Combo Heroes
**Bundle ID:** com.trinitistars.comboheroes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1063632259">1063632259</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/combo-heroes/id1063632259?mt=8&uo=4">https://itunes.apple.com/us/app/combo-heroes/id1063632259?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** tabasco game, inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tabasco-game/id1063225127?uo=4>© tabasco game</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/5a/d0/22/5ad02235-df41-0e28-6757-779ec5438204/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18030906/e341724a-6cc9-11e6-971e-7f30d6c2685d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/16326858/0ade8012-3990-11e6-8d32-80522f69a4d2.png)
https://cloud.githubusercontent.com/assets/3090247/16326858/0ade8012-3990-11e6-8d32-80522f69a4d2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/16326859/0aec6132-3990-11e6-8adb-967b6659796c.png

**Comment by Anuskuss** [comment]
@ivanov007 Where is his left arm? Btw really nice icon.

**Comment by ivanov007** [comment]
is holding the sword, and it is a nice source, you should check it out

**Comment by Anuskuss** [comment]
@ivanov007 Yeah I know, but why did you keep it transparent? Imo it would look better if you make it white so it connects.

**Comment by ivanov007** [comment]
oh ok I got you, well since the sleeve is black I left ot transparent, I can make the lines thicker though

**Comment by Anuskuss** [comment]
@ivanov007 I would like it in solid white so it blends in but it's your icon,

**Comment by Trubbel** [comment]
@Anuskuss Will this do?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18030906/e341724a-6cc9-11e6-971e-7f30d6c2685d.png)
https://cloud.githubusercontent.com/assets/10730122/18030906/e341724a-6cc9-11e6-971e-7f30d6c2685d.png
--- ---
Source: @ivanov007 
https://cloud.githubusercontent.com/assets/10730122/18030905/e33d46fc-6cc9-11e6-89d1-5b4002dfcff3.png

**Comment by dreamnet** [comment]
I think it's perfect. :+1:
