### ISSUE TITLE
FXNOW

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7529]
**App Name:** FXNOW
**Bundle ID:** com.fxnetworks.ios.FXNOW
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=767268733">767268733</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fxnow/id767268733?mt=8&uo=4">https://itunes.apple.com/us/app/fxnow/id767268733?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** FX Networks LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fx-networks-llc/id353068598?uo=4>© FX Networks LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/a0/84/11/a084112c-0222-cee7-57d9-27b62f867af3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356849/3feba9f4-3ae6-11e6-8d8c-749d48b062da.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356849/3feba9f4-3ae6-11e6-8d8c-749d48b062da.png)
https://cloud.githubusercontent.com/assets/10730122/16356849/3feba9f4-3ae6-11e6-8d8c-749d48b062da.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16356848/3fd2f22e-3ae6-11e6-82ce-51a19f8a9e31.png
