### ISSUE TITLE
STARZ

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7530]
**App Name:** STARZ
**Bundle ID:** com.starz.starzplay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=550221096">550221096</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/starz/id550221096?mt=8&uo=4">https://itunes.apple.com/us/app/starz/id550221096?mt=8&uo=4</a>
**App Version:** 3.0.6
**Seller:** Starz Entertainment
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/starz-entertainment-llc/id550221102?uo=4>© Starz Entertainment, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/5d/c8/f7/5dc8f731-e4b0-b387-143d-5556915c5765/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356875/d5387bd6-3ae6-11e6-950d-7a260bd24dbd.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356875/d5387bd6-3ae6-11e6-950d-7a260bd24dbd.png)
https://cloud.githubusercontent.com/assets/10730122/16356875/d5387bd6-3ae6-11e6-950d-7a260bd24dbd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16356874/d538226c-3ae6-11e6-893d-959276df7bcd.png
