### ISSUE TITLE
USA NOW

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7531]
**App Name:** USA NOW
**Bundle ID:** com.nbcuni.usanetwork.tve
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=661695783">661695783</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/usa-now/id661695783?mt=8&uo=4">https://itunes.apple.com/us/app/usa-now/id661695783?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** NBCUniversal Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nbcuniversal-media-llc/id303544359?uo=4>© NBCUniversal Media, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/73/ab/6c/73ab6c98-e19b-b7ce-deba-60a9aad8f512/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356893/49629ce4-3ae7-11e6-9901-4ce50787af03.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356893/49629ce4-3ae7-11e6-9901-4ce50787af03.png)
https://cloud.githubusercontent.com/assets/10730122/16356893/49629ce4-3ae7-11e6-9901-4ce50787af03.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16356894/4963a260-3ae7-11e6-9e4e-1aab9c4d633b.png
