### ISSUE TITLE
Watch TBS

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7532]
**App Name:** Watch TBS
**Bundle ID:** com.turner.TBS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=462780547">462780547</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watch-tbs/id462780547?mt=8&uo=4">https://itunes.apple.com/us/app/watch-tbs/id462780547?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Turner Broadcasting System, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/turner-broadcasting-system/id289550996?mt=8&uo=4>© Turner Broadcasting System, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/49/db/ab/49dbabeb-7c1c-c754-3d9c-cda3d84b413e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356909/bef89eb8-3ae7-11e6-8256-750ec93af4cc.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356909/bef89eb8-3ae7-11e6-8256-750ec93af4cc.png)
https://cloud.githubusercontent.com/assets/10730122/16356909/bef89eb8-3ae7-11e6-8256-750ec93af4cc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16356910/beffbb1c-3ae7-11e6-8cd4-6e0851e2d019.png
