### ISSUE TITLE
Watch TNT

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7533]
**App Name:** Watch TNT
**Bundle ID:** com.turner.TNT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=460494135">460494135</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watch-tnt/id460494135?mt=8&uo=4">https://itunes.apple.com/us/app/watch-tnt/id460494135?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Turner Broadcasting System, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tnt/id379316861?uo=4>© TNT</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/2c/82/b2/2c82b2b0-4fcb-92b5-e162-754421c94082/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356924/2729f31a-3ae8-11e6-9776-9dcbcd916d4d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16356924/2729f31a-3ae8-11e6-9776-9dcbcd916d4d.png)
https://cloud.githubusercontent.com/assets/10730122/16356924/2729f31a-3ae8-11e6-9776-9dcbcd916d4d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16356923/27299f5a-3ae8-11e6-97b7-8e8227966aeb.png
