### ISSUE TITLE
Universe of Movies And TV

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7534]
**App Name:** Universe of Movies And TV
**Bundle ID:** com.SpicyGames.UMAT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1076556393">1076556393</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/universe-of-movies-and-tv/id1076556393?mt=8&uo=4">https://itunes.apple.com/us/app/universe-of-movies-and-tv/id1076556393?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Henrik Nielsen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/henrik-nielsen/id670404937?uo=4>© Henrik Nielsen</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/28/1d/89/281d89d4-4c9f-551d-8f01-2799cfe7020c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16361021/4bb011cc-3b80-11e6-9397-e64df1f88505.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16361021/4bb011cc-3b80-11e6-9397-e64df1f88505.png)
https://cloud.githubusercontent.com/assets/2068130/16361021/4bb011cc-3b80-11e6-9397-e64df1f88505.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16361023/5b92afa0-3b80-11e6-8311-ae37406f0471.png
