### ISSUE TITLE
Relight - Better Photos

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7535]
**App Name:** Relight - Better Photos
**Bundle ID:** com.codeorgana.relight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1055538670">1055538670</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/relight-better-photos/id1055538670?mt=8&uo=4">https://itunes.apple.com/us/app/relight-better-photos/id1055538670?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Code Organa LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/code-organa/id363410063?uo=4>© Code Organa</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/db/5d/e0/db5de0ed-8ade-781c-9501-a8a72a8d58e5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16600105/ed5a88cc-4305-11e6-84bd-ec24e764e1de.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16600105/ed5a88cc-4305-11e6-84bd-ec24e764e1de.png)
https://cloud.githubusercontent.com/assets/2068130/16600105/ed5a88cc-4305-11e6-84bd-ec24e764e1de.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16600120/fb8c70ae-4305-11e6-879e-9128081350e5.png
