### ISSUE TITLE
Moments – Get the photos you didn't take

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7536]
**App Name:** Moments – Get the photos you didn't take
**Bundle ID:** com.facebook.Moments
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=991346515">991346515</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moments-get-photos-you-didnt/id991346515?mt=8&uo=4">https://itunes.apple.com/us/app/moments-get-photos-you-didnt/id991346515?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/facebook-inc./id284882218?uo=4>© Facebook, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/93/1d/ff/931dffec-63b9-fbfc-6ff5-e27878311bde/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18030961/7a0511ea-6ccb-11e6-807c-e0b640184149.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18030961/7a0511ea-6ccb-11e6-807c-e0b640184149.png)
https://cloud.githubusercontent.com/assets/10730122/18030961/7a0511ea-6ccb-11e6-807c-e0b640184149.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18030960/7a04ba92-6ccb-11e6-9189-d3a8da3d0a17.png
