### ISSUE TITLE
Rodeo Stampede - Sky Zoo Safari

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7538]
**App Name:** Rodeo Stampede - Sky Zoo Safari
**Bundle ID:** com.featherweightgames.stampede
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1047961826">1047961826</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rodeo-stampede-sky-zoo-safari/id1047961826?mt=8&uo=4">https://itunes.apple.com/us/app/rodeo-stampede-sky-zoo-safari/id1047961826?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Featherweight Games Pty Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/featherweight-games-pty-limited/id914400752?uo=4>© Featherweight Games Pty Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/fd/67/7f/fd677f07-c51f-536e-f16c-d0accf597b6a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19005838/02891a92-875d-11e6-815d-438290a0e1fa.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19005838/02891a92-875d-11e6-815d-438290a0e1fa.png)
https://cloud.githubusercontent.com/assets/20930745/19005838/02891a92-875d-11e6-815d-438290a0e1fa.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19005884/3095ae8c-875d-11e6-995a-60cfebd1a9c1.png
