### ISSUE TITLE
Prism Bills & Personal Finance - schedule payments, track balances, budget, pay bills

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7539]
**App Name:** Prism Bills & Personal Finance - schedule payments, track balances, budget, pay bills
**Bundle ID:** com.mobilligy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=522138897">522138897</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/prism-bills-personal-finance/id522138897?mt=8&uo=4">https://itunes.apple.com/us/app/prism-bills-personal-finance/id522138897?mt=8&uo=4</a>
**App Version:** 2.5.17
**Seller:** Mobilligy, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobilligy/id522138900?uo=4>© Mobilligy</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/d3/88/50/d3885068-e5e5-8032-b752-ce6761b40ed4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16894788/61ac7ad2-4b62-11e6-8bb1-a927b21d9ffe.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16894788/61ac7ad2-4b62-11e6-8bb1-a927b21d9ffe.png)
https://cloud.githubusercontent.com/assets/2068130/16894788/61ac7ad2-4b62-11e6-8bb1-a927b21d9ffe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16894790/7587c89a-4b62-11e6-9b19-e65a59f7cfcf.png
