### ISSUE TITLE
aTimeLogger

### ISSUE THREAD

**Issue by alderz** [glasklart/hd#754]
**App Name:** aTimeLogger
**Bundle ID:** net.zaplitny.atimelogger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=358979305">358979305</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/atimelogger/id358979305?mt=8&uo=4">https://itunes.apple.com/us/app/atimelogger/id358979305?mt=8&uo=4</a>
**App Version:** 1.9.10
**Seller:** Sergei Zaplitny
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sergei-zaplitny/id358979308?uo=4">© Sergei Zaplitny</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/d4/50/41/d450417d-b439-273c-25e5-9918904586c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20181718/8c8d4584-a75f-11e6-9f41-99285f5495c3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20181718/8c8d4584-a75f-11e6-9f41-99285f5495c3.png)
https://cloud.githubusercontent.com/assets/20930745/20181718/8c8d4584-a75f-11e6-9f41-99285f5495c3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20181817/f3341880-a75f-11e6-8ded-8e42482c5266.png
