### ISSUE TITLE
Sportle・Live Sports, Streams, Scores, and Schedules

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7540]
**App Name:** Sportle・Live Sports, Streams, Scores, and Schedules
**Bundle ID:** tv.sportle.Sportle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1059500655">1059500655</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sportle-live-sports-streams/id1059500655?mt=8&uo=4">https://itunes.apple.com/us/app/sportle-live-sports-streams/id1059500655?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Sportle, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sportle/id1059500654?uo=4>© Sportle</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/f1/4d/e1/f14de10a-f6a0-668f-d4d4-6c9a7a295dfa/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16598982/b3700376-4300-11e6-95aa-eb0621e29f0c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16598982/b3700376-4300-11e6-95aa-eb0621e29f0c.png)
https://cloud.githubusercontent.com/assets/2068130/16598982/b3700376-4300-11e6-95aa-eb0621e29f0c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16598990/c1e9430e-4300-11e6-9d89-a8b2fe613aae.png
