### ISSUE TITLE
FINAL FANTASY BRAVE EXVIUS

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7541]
**App Name:** FINAL FANTASY BRAVE EXVIUS
**Bundle ID:** com.square-enix.ffbeww
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1078553808">1078553808</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/final-fantasy-brave-exvius/id1078553808?mt=8&uo=4">https://itunes.apple.com/se/app/final-fantasy-brave-exvius/id1078553808?mt=8&uo=4</a>
**App Version:** 0.1.6
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/developer/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/b3/6f/fb/b36ffb80-ca5f-9649-5e4e-5007afc805ed/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/16537293/0996d5fe-3fcd-11e6-8dda-cc92d5b415d2.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16414067/cf3bc0fc-3d35-11e6-9197-1b00ffd7fa54.png)
https://cloud.githubusercontent.com/assets/10730122/16414067/cf3bc0fc-3d35-11e6-9197-1b00ffd7fa54.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16414066/cf29fdae-3d35-11e6-94bc-72c1b21fc2e7.png

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/16537293/0996d5fe-3fcd-11e6-8dda-cc92d5b415d2.png)
https://cloud.githubusercontent.com/assets/10950389/16537293/0996d5fe-3fcd-11e6-8dda-cc92d5b415d2.png

---
Source:
https://cloud.githubusercontent.com/assets/10950389/16537301/33678108-3fcd-11e6-907a-17a6a8a6a8ba.png

**Comment by dreamnet** [comment]
Taking the one from @zmathiasz to go with the other Final Fantasy icons.
