### ISSUE TITLE
Tipico Classic

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7542]
**App Name:** Tipico Classic
**Bundle ID:** com.tipico.classic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1051329602">1051329602</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/tipico-classic/id1051329602?mt=8&uo=4">https://itunes.apple.com/de/app/tipico-classic/id1051329602?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Tipico Co. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/tipico/id1036816283?uo=4>© Tipico</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple2/v4/52/03/4d/52034d2f-a965-5514-acf9-d24c00e4c3fb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/16537501/c2c074a0-3fd1-11e6-9f8a-30201882c6f6.png)

**Comment by Anuskuss** [comment]
Same as #4036 (no need for the **CLASSIC**)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/16537473/19f25e92-3fd1-11e6-838c-71c101aafb3a.png)
https://cloud.githubusercontent.com/assets/10950389/16537473/19f25e92-3fd1-11e6-838c-71c101aafb3a.png

---
Source:
https://cloud.githubusercontent.com/assets/10950389/16537492/8e3b5ae2-3fd1-11e6-96d3-53e8faa6bbcb.png

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/16537501/c2c074a0-3fd1-11e6-9f8a-30201882c6f6.png)
https://cloud.githubusercontent.com/assets/10950389/16537501/c2c074a0-3fd1-11e6-9f8a-30201882c6f6.png

---
Source:
https://cloud.githubusercontent.com/assets/10950389/16537504/d068aab4-3fd1-11e6-8539-d1ce9f41f795.png

**Comment by zmathiasz** [comment]
Hmm.  Not sure why my linking is broken.  Double...no...triple checked it and then some.  Anyone else having this issue right now? @dreamnet
