### ISSUE TITLE
lippu.fi

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7543]
**App Name:** lippu.fi
**Bundle ID:** fi.lippupiste.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=702817086">702817086</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lippu.fi/id702817086?mt=8&uo=4">https://itunes.apple.com/us/app/lippu.fi/id702817086?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Lippupiste Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lippupiste-oy/id642347942?uo=4>© Lippupiste Oy</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/a7/ea/18/a7ea1829-d988-6019-01c1-c3120eb89338/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/16537362/c09fd09c-3fce-11e6-89e2-cc1f68051ca9.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/16537362/c09fd09c-3fce-11e6-89e2-cc1f68051ca9.png)
https://cloud.githubusercontent.com/assets/10950389/16537362/c09fd09c-3fce-11e6-89e2-cc1f68051ca9.png

---
Source:
https://cloud.githubusercontent.com/assets/10950389/16537365/ccc1996e-3fce-11e6-9d36-633779124fda.png
