### ISSUE TITLE
CSR Racing 2

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7544]
**App Name:** CSR Racing 2
**Bundle ID:** com.naturalmotion.customstreetracer2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=887947640">887947640</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/csr-racing-2/id887947640?mt=8&uo=4">https://itunes.apple.com/us/app/csr-racing-2/id887947640?mt=8&uo=4</a>
**App Version:** 1.4.4
**Seller:** NaturalMotion Games Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/naturalmotion/id330281898?uo=4>© NaturalMotion</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/6a/be/45/6abe45de-ecbf-7de1-1fe8-87a7b66b5feb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16523759/577e0da0-3fa5-11e6-93e3-b350f5631beb.png)

**Comment by Trubbel** [comment]
We can perhaps use the games logo?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/16523759/577e0da0-3fa5-11e6-93e3-b350f5631beb.png)
https://cloud.githubusercontent.com/assets/10730122/16523759/577e0da0-3fa5-11e6-93e3-b350f5631beb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/16523760/577e3a64-3fa5-11e6-98b9-7aad6fdd72b3.png

**Comment by dreamnet** [comment]
@Trubbel Jup! :+1:
