### ISSUE TITLE
Wrapp

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7545]
**App Name:** Wrapp
**Bundle ID:** com.wrapp.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=458640944">458640944</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/wrapp/id458640944?mt=8&uo=4">https://itunes.apple.com/se/app/wrapp/id458640944?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Bohemian Wrappsody AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/developer/bohemian-wrappsody-ab/id458640947?uo=4>© Bohemian Wrappsody AB</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/f4/1d/5e/f41d5ed5-b1ef-1249-176d-ea10297a3756/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17086701/2be6de0e-51f9-11e6-9b82-308d32ea0a07.png)\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17086701/2be6de0e-51f9-11e6-9b82-308d32ea0a07.png)
https://cloud.githubusercontent.com/assets/2068130/17086701/2be6de0e-51f9-11e6-9b82-308d32ea0a07.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17086705/3bf6f522-51f9-11e6-903f-b8a577a54d33.png
