### ISSUE TITLE
Allrecipes Dinner Spinner

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7546]
**App Name:** Allrecipes Dinner Spinner
**Bundle ID:** com.allrecipes.dinnerspinner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=299515267">299515267</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/allrecipes-dinner-spinner/id299515267?uo=4">https://apps.apple.com/us/app/allrecipes-dinner-spinner/id299515267?uo=4</a>
**App Version:** 6.6.7
**Seller:** All Recipes
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/all-recipes-inc/id299515270?uo=4">© All Recipes, Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/32/af/75/32af7559-ce1e-ccf8-3f52-75730c81c227/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/81198563-e7e18c80-8fc1-11ea-88c4-b3e0c4bed137.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16599598/610a6010-4303-11e6-9a02-799e37cc2c72.png)
https://cloud.githubusercontent.com/assets/2068130/16599598/610a6010-4303-11e6-9a02-799e37cc2c72.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16599606/6f025a24-4303-11e6-9cc5-c10f3ae1882b.png

**Comment by l8er4now** [comment]
Needs bit of an update.

**App Name:** Allrecipes Dinner Spinner
**Bundle ID:** com.allrecipes.dinnerspinner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=299515267">299515267</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/allrecipes-dinner-spinner/id299515267?uo=4">https://apps.apple.com/us/app/allrecipes-dinner-spinner/id299515267?uo=4</a>
**App Version:** 6.6.7
**Seller:** All Recipes
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/all-recipes-inc/id299515270?uo=4">© All Recipes, Inc.</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/32/af/75/32af7559-ce1e-ccf8-3f52-75730c81c227/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/81198563-e7e18c80-8fc1-11ea-88c4-b3e0c4bed137.png)
https://user-images.githubusercontent.com/2068130/81198563-e7e18c80-8fc1-11ea-88c4-b3e0c4bed137.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/81198602-f760d580-8fc1-11ea-8c63-f1cf95a4dacc.png
