### ISSUE TITLE
Yum-Yum! 1000+ Free Recipes with Step-by-Step Photos & Grocery Shopping List

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7547]
**App Name:** Yum-Yum! 1000+ Free Recipes with Step-by-Step Photos & Grocery Shopping List
**Bundle ID:** com.ideanomix.cookinginter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=962021085">962021085</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yum-yum!-1000+-free-recipes/id962021085?mt=8&uo=4">https://itunes.apple.com/us/app/yum-yum!-1000+-free-recipes/id962021085?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Publishing House "Eksmo", LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/publishing-house-eksmo-llc/id450167471?uo=4>© Publishing House Eksmo, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/fc/96/95/fc969521-7948-e6df-4871-3297f249e749/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16598851/27363312-4300-11e6-834f-18666dc6f51e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16598851/27363312-4300-11e6-834f-18666dc6f51e.png)
https://cloud.githubusercontent.com/assets/2068130/16598851/27363312-4300-11e6-834f-18666dc6f51e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16598863/34fa035c-4300-11e6-9c8d-d6da9a2db3f0.png
