### ISSUE TITLE
NYT Cooking - Recipes from The New York Times

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7548]
**App Name:** NYT Cooking - Recipes from The New York Times
**Bundle ID:** com.nytimes.cooking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911422904">911422904</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nyt-cooking-recipes-from-new/id911422904?mt=8&uo=4">https://itunes.apple.com/us/app/nyt-cooking-recipes-from-new/id911422904?mt=8&uo=4</a>
**App Version:** 2.12.1
**Seller:** The New York Times Company (iDP)
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-new-york-times-company/id284862086?uo=4">© The New York Times Company</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple19/v4/6e/cc/02/6ecc0269-67ea-de78-8708-f5b20d50be17/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21041330/95fae2d8-bdea-11e6-82a8-a737a4d405b0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16599509/ec0e8868-4302-11e6-96a0-4a61a81fb32c.png)
https://cloud.githubusercontent.com/assets/2068130/16599509/ec0e8868-4302-11e6-96a0-4a61a81fb32c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16599524/faa2bf5c-4302-11e6-8905-fb41d6cca7be.png

**Comment by l8er4now** [comment]
Needs an update

**App Name:** NYT Cooking - Recipes from The New York Times
**Bundle ID:** com.nytimes.cooking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911422904">911422904</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nyt-cooking-recipes-from-new/id911422904?mt=8&uo=4">https://itunes.apple.com/us/app/nyt-cooking-recipes-from-new/id911422904?mt=8&uo=4</a>
**App Version:** 2.12.0
**Seller:** The New York Times Company (iDP)
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-new-york-times-company/id284862086?uo=4">© The New York Times Company</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/32/47/77/324777ed-65a0-7fcd-4b33-fe0637a1abb3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21041330/95fae2d8-bdea-11e6-82a8-a737a4d405b0.png)
https://cloud.githubusercontent.com/assets/2068130/21041330/95fae2d8-bdea-11e6-82a8-a737a4d405b0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21041346/a859bbe8-bdea-11e6-8892-f0eb3619006f.png
