### ISSUE TITLE
Food Network Kitchen

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7549]
**App Name:** Food Network Kitchen
**Bundle ID:** com.sni.iphone.applications.ITKApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=399072152">399072152</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/food-network-kitchen/id399072152?uo=4">https://apps.apple.com/us/app/food-network-kitchen/id399072152?uo=4</a>
**App Version:** 6.0.2
**Seller:** Discovery Digital Ventures, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/discovery-digital-ventures-llc/id1480870856?uo=4">© Discovery Digital Ventures, LLC</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/82/17/bc/8217bc38-2f52-50ef-7ee5-0ade7a24ec86/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68027436-a7bbed00-fcb2-11e9-822e-9eec3ee09ce7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16598767/b488903a-42ff-11e6-9387-b283814aa3f6.png)
https://cloud.githubusercontent.com/assets/2068130/16598767/b488903a-42ff-11e6-9387-b283814aa3f6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16598777/c2bb6556-42ff-11e6-98bb-50d31866623e.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Food Network Kitchen
**Bundle ID:** com.sni.iphone.applications.ITKApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=399072152">399072152</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/food-network-kitchen/id399072152?uo=4">https://apps.apple.com/us/app/food-network-kitchen/id399072152?uo=4</a>
**App Version:** 6.0.2
**Seller:** Discovery Digital Ventures, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/discovery-digital-ventures-llc/id1480870856?uo=4">© Discovery Digital Ventures, LLC</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/82/17/bc/8217bc38-2f52-50ef-7ee5-0ade7a24ec86/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68027436-a7bbed00-fcb2-11e9-822e-9eec3ee09ce7.png)
https://user-images.githubusercontent.com/20930745/68027436-a7bbed00-fcb2-11e9-822e-9eec3ee09ce7.png

Source:
https://user-images.githubusercontent.com/20930745/68027440-a8ed1a00-fcb2-11e9-885e-97c5726129c4.png
