### ISSUE TITLE
WordReference Dictionary

### ISSUE THREAD

**Issue by alderz** [glasklart/hd#755]
**App Name:** WordReference Dictionary
**Bundle ID:** com.wordreference.WordReferenceDictionary
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=515127233">515127233</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wordreference-dictionary/id515127233?mt=8&uo=4">https://itunes.apple.com/us/app/wordreference-dictionary/id515127233?mt=8&uo=4</a>
**App Version:** 5.0.8
**Seller:** WordReference.com, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wordreference.com-llc/id296878902?uo=4">© WordReference.com, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/28/07/24/28072493-d4e1-df2d-0228-4d49b22004d1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028547/1fb5bb72-a335-11e6-8c08-fdcafacf111b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20028547/1fb5bb72-a335-11e6-8c08-fdcafacf111b.png)
https://cloud.githubusercontent.com/assets/20930745/20028547/1fb5bb72-a335-11e6-8c08-fdcafacf111b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20028551/3ce14e14-a335-11e6-9a97-3865ff2f5b46.png
