### ISSUE TITLE
Food.com – Recipes, Shopping Lists & Meal Plans

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7550]
**App Name:** Food.com – Recipes, Shopping Lists & Meal Plans
**Bundle ID:** 554UNEM3C7
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418971697">418971697</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/food.com-recipes-shopping/id418971697?mt=8&uo=4">https://itunes.apple.com/us/app/food.com-recipes-shopping/id418971697?mt=8&uo=4</a>
**App Version:** 4.2.8
**Seller:** Television Food Network G.P.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/television-food-network-g.p./id332170285?uo=4>© Television Food Network G.P.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/a4/dd/bf/a4ddbf58-4c43-62bb-cd96-5748ca37bd4c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17086621/37b4f114-51f7-11e6-8a3f-ef5562932f5a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17086621/37b4f114-51f7-11e6-8a3f-ef5562932f5a.png)
https://cloud.githubusercontent.com/assets/2068130/17086621/37b4f114-51f7-11e6-8a3f-ef5562932f5a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17086622/4731f0b0-51f7-11e6-86b8-055e21252555.png
