### ISSUE TITLE
iTriage - Health, Doctor, Symptoms and Healthcare search

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7551]
**App Name:** iTriage - Health, Doctor, Symptoms and Healthcare search
**Bundle ID:** com.yourcompany.iTriage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=304696939">304696939</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/itriage-health-doctor-symptoms/id304696939?mt=8&uo=4">https://itunes.apple.com/us/app/itriage-health-doctor-symptoms/id304696939?mt=8&uo=4</a>
**App Version:** 5.29
**Seller:** iTriage LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/itriage-llc/id892424634?uo=4>© iTriage LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/dc/f9/6b/dcf96b0d-c5ae-7a26-2b27-7dae27530e00/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16600017/7ba5df4c-4305-11e6-88b6-12cc7f43f384.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16600017/7ba5df4c-4305-11e6-88b6-12cc7f43f384.png)
https://cloud.githubusercontent.com/assets/2068130/16600017/7ba5df4c-4305-11e6-88b6-12cc7f43f384.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16600031/8aadc4be-4305-11e6-9204-3e08b6b361d9.png
