### ISSUE TITLE
Glitch Wizard - Distort Photos to Trippy GIFs

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7553]
**App Name:** Glitch Wizard - Distort Photos to Trippy GIFs
**Bundle ID:** com.glitchwizard.glitchwizard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=904640439">904640439</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glitch-wizard-distort-photos/id904640439?mt=8&uo=4">https://itunes.apple.com/us/app/glitch-wizard-distort-photos/id904640439?mt=8&uo=4</a>
**App Version:** 2.600
**Seller:** Allan Lavell
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/allan-lavell/id400754298?uo=4>© Allan Lavell</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/f6/fd/e8/f6fde8c5-d06e-0a1a-efbd-c5954675f51e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16599218/9ca596fa-4301-11e6-8059-75c3f00c0b08.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16599218/9ca596fa-4301-11e6-8059-75c3f00c0b08.png)
https://cloud.githubusercontent.com/assets/2068130/16599218/9ca596fa-4301-11e6-8059-75c3f00c0b08.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16599229/ab181ed8-4301-11e6-80b6-5b3eb62ec14f.png
