### ISSUE TITLE
Catch App: Your Daily dose of mobile

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7554]
**App Name:** Catch App: Your Daily dose of mobile
**Bundle ID:** com.catchapp.catchapp-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1070021633">1070021633</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/catch-app-your-daily-dose/id1070021633?mt=8&uo=4">https://itunes.apple.com/us/app/catch-app-your-daily-dose/id1070021633?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Blinding Lights
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/blinding-lights/id1060811763?uo=4>© Blinding Lights</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/60381943-1b779000-9a5c-11e9-9d51-41178f07cc01.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60381968-888b2580-9a5c-11e9-8be5-d56f98fec95b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16598631/3cbc4696-42ff-11e6-9baf-043a4f78545b.png)
https://cloud.githubusercontent.com/assets/2068130/16598631/3cbc4696-42ff-11e6-9baf-043a4f78545b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16598650/4d1ea984-42ff-11e6-818f-a2bfe2e4f247.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60381968-888b2580-9a5c-11e9-8be5-d56f98fec95b.png)
https://user-images.githubusercontent.com/2068130/60381968-888b2580-9a5c-11e9-8be5-d56f98fec95b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60381973-993b9b80-9a5c-11e9-9e69-53b51cfbe6b3.png
