### ISSUE TITLE
Bejeweled Stars

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7555]
**App Name:** Bejeweled Stars
**Bundle ID:** com.ea.ios.bejeweledskies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=974135847">974135847</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bejeweled-stars/id974135847?mt=8&uo=4">https://itunes.apple.com/us/app/bejeweled-stars/id974135847?mt=8&uo=4</a>
**App Version:** 2.0.7
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4>© Electronic Arts</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/c2/cd/7b/c2cd7bca-828d-2d86-4817-880fb43a77e1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18343548/1642004a-75b4-11e6-91ce-827ce462b60a.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18343482/dc52be56-75b3-11e6-9cae-8cf51fa84e19.png)
https://cloud.githubusercontent.com/assets/10730122/18343482/dc52be56-75b3-11e6-9cae-8cf51fa84e19.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18343483/dc54e780-75b3-11e6-8aae-4f3633e31ad1.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18343548/1642004a-75b4-11e6-91ce-827ce462b60a.png)
https://cloud.githubusercontent.com/assets/10730122/18343548/1642004a-75b4-11e6-91ce-827ce462b60a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18343547/16405308-75b4-11e6-811a-86cbd6bfeb55.png

**Comment by dreamnet** [comment]
@Trubbel Your issue - you decide. :thought_balloon:

**Comment by Trubbel** [comment]
@dreamnet I personally don't like how the diamond looks like, couldn't do it better - so perhaps just the text itself then.
