### ISSUE TITLE
Pizza Hut

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7556]
**App Name:** Pizza Hut
**Bundle ID:** com.imc2.iHut
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=321560858">321560858</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pizza-hut/id321560858?mt=8&uo=4">https://itunes.apple.com/us/app/pizza-hut/id321560858?mt=8&uo=4</a>
**App Version:** 3.1.10
**Seller:** Pizza Hut, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pizza-hut-inc./id436374259?uo=4>© Pizza Hut, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/35/29/26/352926f8-f4e9-3a56-e480-184b1435b6f6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17086581/7a58b5b0-51f6-11e6-9648-3f8b585cfcda.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17086581/7a58b5b0-51f6-11e6-9648-3f8b585cfcda.png)
https://cloud.githubusercontent.com/assets/2068130/17086581/7a58b5b0-51f6-11e6-9648-3f8b585cfcda.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17086587/89efe926-51f6-11e6-8212-cf03c16258bc.png
