### ISSUE TITLE
Chilis

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7557]
**App Name:** Chilis
**Bundle ID:** com.chilistogo.prod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=464383246">464383246</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chilis/id464383246?mt=8&uo=4">https://itunes.apple.com/us/app/chilis/id464383246?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** Brinker International Payroll Company, L.P
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brinker-international-payroll/id464383249?uo=4>© Brinker International Payroll Company, L.P</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/ee/2b/51/ee2b517d-5377-7070-d9e9-ebabda91a384/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892731/aa59f1dc-4b1d-11e6-9d6f-7d0a124f2da6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892731/aa59f1dc-4b1d-11e6-9d6f-7d0a124f2da6.png)
https://cloud.githubusercontent.com/assets/2068130/16892731/aa59f1dc-4b1d-11e6-9d6f-7d0a124f2da6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892732/b9a0d476-4b1d-11e6-99ca-03936c56e34c.png
