### ISSUE TITLE
Vurb - Find and Save Anything

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7558]
**App Name:** Vurb - Find and Save Anything
**Bundle ID:** com.vurb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=959127584">959127584</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vurb-find-and-save-anything/id959127584?mt=8&uo=4">https://itunes.apple.com/us/app/vurb-find-and-save-anything/id959127584?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** Verbify Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/verbify-inc./id867172887?uo=4>© Verbify Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/f2/83/9d/f2839dd2-9fe7-173c-02c4-fdfe46e54d26/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17038227/fe8faa78-4f94-11e6-87c8-efc451e102de.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17038227/fe8faa78-4f94-11e6-87c8-efc451e102de.png)
https://cloud.githubusercontent.com/assets/2068130/17038227/fe8faa78-4f94-11e6-87c8-efc451e102de.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17038240/1588bf76-4f95-11e6-95e4-763592425151.png
