### ISSUE TITLE
MaxCurve - Curve tool & image editor for pro photography

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7559]
**App Name:** MaxCurve - Curve tool & image editor for pro photography
**Bundle ID:** com.maxcurve
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1048026594">1048026594</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/maxcurve-curve-tool-image/id1048026594?mt=8&uo=4">https://itunes.apple.com/us/app/maxcurve-curve-tool-image/id1048026594?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Xiaodong Wang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/xiaodong-wang/id1083287354?uo=4>© Xiaodong Wang</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/e1/95/92/e1959269-3d9d-593e-ab3e-20a7a999b009/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712834/2b66c60e-4693-11e6-8359-b7bb0127ef5d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712834/2b66c60e-4693-11e6-8359-b7bb0127ef5d.png)
https://cloud.githubusercontent.com/assets/2068130/16712834/2b66c60e-4693-11e6-8359-b7bb0127ef5d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712836/393c29f4-4693-11e6-87f3-9e1135040ab7.png
