### ISSUE TITLE
Food Network

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7560]
**App Name:** Food Network
**Bundle ID:** com.foodnetwork.tveverywhere
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=642410271">642410271</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/food-network/id642410271?uo=4">https://apps.apple.com/us/app/food-network/id642410271?uo=4</a>
**App Version:** 7.4.0
**Seller:** Television Food Network G.P.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/television-food-network-g-p/id332170285?uo=4">© Television Food Network G.P.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/51/e5/18/51e518a0-3fc0-1929-9ae4-60a64aa75f09/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com sni iphone applications ITKApp-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393908-b59f0d00-9b1c-11e9-9110-f8a40455eac3.png)

**Comment by alpcinar** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13483942/18027301/3429bf70-6c69-11e6-8f95-0c639576bc0a.png)
https://cloud.githubusercontent.com/assets/13483942/18027301/3429bf70-6c69-11e6-8f95-0c639576bc0a.png

Source:
https://cloud.githubusercontent.com/assets/13483942/18027308/41225b10-6c69-11e6-8c10-c63eb15d83ac.png

**Comment by alpcinar** [comment]
Not perfect. :/

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18254452/348d5f3a-739e-11e6-9289-57f16b7aea05.png)
https://cloud.githubusercontent.com/assets/20930745/18254452/348d5f3a-739e-11e6-9289-57f16b7aea05.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18254458/4b05c202-739e-11e6-8a75-736af18ca4d3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18625340/4f481ef4-7e4e-11e6-8841-9a2205f804d9.png)
https://cloud.githubusercontent.com/assets/20930745/18625340/4f481ef4-7e4e-11e6-8841-9a2205f804d9.png

Source:
(https://cloud.githubusercontent.com/assets/20930745/18625353/66dc544a-7e4e-11e6-9f25-8b5e3957e831.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![com sni iphone applications ITKApp-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60393908-b59f0d00-9b1c-11e9-9110-f8a40455eac3.png)
https://user-images.githubusercontent.com/2068130/60393908-b59f0d00-9b1c-11e9-9110-f8a40455eac3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60393913-c485bf80-9b1c-11e9-967a-a6c4ad0eda90.png
