### ISSUE TITLE
RadarScope

### ISSUE THREAD

**Issue by jpokorny2** [glasklart/hd#7561]
**App Name:** RadarScope
**Bundle ID:** com.basevelocity.RadarScope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288419283">288419283</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radarscope/id288419283?mt=8&uo=4">https://itunes.apple.com/us/app/radarscope/id288419283?mt=8&uo=4</a>
**App Version:** 3.0.4
**Seller:** Base Velocity, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/base-velocity-llc/id288419286?uo=4>© Base Velocity, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/3b/c6/a9/3bc6a911-1238-9394-367c-9c44f1c51add/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18988224/f01eb06c-8705-11e6-9713-4c5899965294.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18988224/f01eb06c-8705-11e6-9713-4c5899965294.png)
https://cloud.githubusercontent.com/assets/20930745/18988224/f01eb06c-8705-11e6-9713-4c5899965294.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18988236/02764770-8706-11e6-8dd0-fd309c1f3df1.png
