### ISSUE TITLE
Unified Remote

### ISSUE THREAD

**Issue by jpokorny2** [glasklart/hd#7562]
**App Name:** Unified Remote
**Bundle ID:** com.unified.UR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=825534179">825534179</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/unified-remote/id825534179?mt=8&uo=4">https://itunes.apple.com/us/app/unified-remote/id825534179?mt=8&uo=4</a>
**App Version:** 1.4.4
**Seller:** Unified Intents AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/unified-intents/id793898900?uo=4>© Unified Intents</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/95/b7/59/95b759ff-ca19-62d4-dbac-5c26c56a9fd8/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712369/cab3d8e0-4685-11e6-99be-b488d952ecdc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712369/cab3d8e0-4685-11e6-99be-b488d952ecdc.png)
https://cloud.githubusercontent.com/assets/2068130/16712369/cab3d8e0-4685-11e6-99be-b488d952ecdc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712373/d9293d66-4685-11e6-8b67-9ddf8370064d.png
