### ISSUE TITLE
Sky Force Reloaded

### ISSUE THREAD

**Issue by jpokorny2** [glasklart/hd#7563]
**App Name:** Sky Force Reloaded
**Bundle ID:** pl.idreams.SkyForceReloaded2015
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=976116090">976116090</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sky-force-reloaded/id976116090?mt=8&uo=4">https://itunes.apple.com/us/app/sky-force-reloaded/id976116090?mt=8&uo=4</a>
**App Version:** 1.10
**Seller:** Infinite Dreams
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/infinite-dreams-inc./id306712040?uo=4>© Infinite Dreams Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/6e/ff/a7/6effa763-a17b-a8e4-b599-745074a265d6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16901517/d07f6e76-4c46-11e6-91f2-0d04aadcfa66.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712446/e9cf271e-4687-11e6-8920-40fa96910df0.png)
https://cloud.githubusercontent.com/assets/2068130/16712446/e9cf271e-4687-11e6-8920-40fa96910df0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712448/f9d447c0-4687-11e6-8358-b4524f28a971.png

**Comment by Anuskuss** [comment]
@dreamnet Would it look better if you remove the border?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16901517/d07f6e76-4c46-11e6-91f2-0d04aadcfa66.png)
https://cloud.githubusercontent.com/assets/2068130/16901517/d07f6e76-4c46-11e6-91f2-0d04aadcfa66.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16901526/eb2e5c5a-4c46-11e6-8b32-1cb9d189bfd6.png

**Comment by Anuskuss** [comment]
Borderless :+1:
