### ISSUE TITLE
flok - get rewarded

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7564]
**App Name:** flok - get rewarded
**Bundle ID:** com.loyalblocks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=376560037">376560037</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flok-get-rewarded/id376560037?mt=8&uo=4">https://itunes.apple.com/us/app/flok-get-rewarded/id376560037?mt=8&uo=4</a>
**App Version:** 6.8
**Seller:** Eran Kirshenboim
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/loyalblocks/id376560040?uo=4>© LoyalBlocks</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/54/51/6f/54516fa1-d780-1210-f660-6f5831085b3b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712402/a07286de-4686-11e6-9e46-364a0b05ab6b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712402/a07286de-4686-11e6-9e46-364a0b05ab6b.png)
https://cloud.githubusercontent.com/assets/2068130/16712402/a07286de-4686-11e6-9e46-364a0b05ab6b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712403/aedd8610-4686-11e6-9483-a4c4b434f2c5.png
