### ISSUE TITLE
GoFinance for Google Finance App: Stock Portfolio & Stock Screener with Realtime Stock Quote

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7565]
**App Name:** GoFinance for Google Finance App: Stock Portfolio & Stock Screener with Realtime Stock Quote
**Bundle ID:** com.GoPassionStudio.GoFinance
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=884935599">884935599</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gofinance-for-google-finance/id884935599?mt=8&uo=4">https://itunes.apple.com/us/app/gofinance-for-google-finance/id884935599?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Truong Hoang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/truong-hoang/id785127119?uo=4>© Truong Hoang</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/54/c6/06/54c606c1-3253-1f03-b547-a5f59029d449/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712350/3e03e868-4685-11e6-9311-bb3c695573bb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712350/3e03e868-4685-11e6-9311-bb3c695573bb.png)
https://cloud.githubusercontent.com/assets/2068130/16712350/3e03e868-4685-11e6-9311-bb3c695573bb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712354/4b7e0b2c-4685-11e6-9686-67626521a1a2.png
