### ISSUE TITLE
Bleacher Report Live

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7566]
**App Name:** Bleacher Report Live
**Bundle ID:** com.catchsports.catchsports
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1098201243">1098201243</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bleacher-report-live/id1098201243?mt=8&uo=4">https://itunes.apple.com/us/app/bleacher-report-live/id1098201243?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** Bleacher Report
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bleacher-report/id418075938?uo=4">© Bleacher Report</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/22/d8/09/22d80936-e771-90c1-7e81-86e58fc2a344/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38265502-66c986ca-3776-11e8-995c-076c8a61ef03.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892890/dd11d526-4b23-11e6-85ae-6c119742c0ac.png)
https://cloud.githubusercontent.com/assets/2068130/16892890/dd11d526-4b23-11e6-85ae-6c119742c0ac.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892894/ec014fa8-4b23-11e6-8767-d33a4c4871e6.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Bleacher Report Live
**Bundle ID:** com.catchsports.catchsports
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1098201243">1098201243</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bleacher-report-live/id1098201243?mt=8&uo=4">https://itunes.apple.com/us/app/bleacher-report-live/id1098201243?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** Bleacher Report
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bleacher-report/id418075938?uo=4">© Bleacher Report</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/22/d8/09/22d80936-e771-90c1-7e81-86e58fc2a344/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38265502-66c986ca-3776-11e8-995c-076c8a61ef03.png)
https://user-images.githubusercontent.com/2068130/38265502-66c986ca-3776-11e8-995c-076c8a61ef03.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38265529-76ecf618-3776-11e8-85d5-d1f8d99c68ed.png
