### ISSUE TITLE
Cinch for Chromecast - Music, Photo, and Video Streaming

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7567]
**App Name:** Cinch for Chromecast - Music, Photo, and Video Streaming
**Bundle ID:** com.touchbound.cinch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=931225847">931225847</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cinch-for-chromecast-music/id931225847?mt=8&uo=4">https://itunes.apple.com/us/app/cinch-for-chromecast-music/id931225847?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Thomas Devoy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/thomas-devoy/id931225846?uo=4>© Thomas Devoy</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/d0/07/5b/d0075b47-2815-f691-c99e-2171a6330752/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712340/b4bcdb32-4684-11e6-9dd7-ac690e0891c4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712340/b4bcdb32-4684-11e6-9dd7-ac690e0891c4.png)
https://cloud.githubusercontent.com/assets/2068130/16712340/b4bcdb32-4684-11e6-9dd7-ac690e0891c4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712342/c37d543a-4684-11e6-9b40-0972c9772d2f.png
