### ISSUE TITLE
Geared & Geared 2

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7568]
Both of these apps doesn't exist anymore, but I still use them and would like to get a little redesign so that they look more similar.

**com.bryandev.Geared**
![Geared](https://cloud.githubusercontent.com/assets/7157389/16671941/d61b87e4-44a2-11e6-8858-838945651ec3.PNG)

**com.playfulart.Geared2**
![Geared 2](https://cloud.githubusercontent.com/assets/7157389/16671954/ec7e490e-44a2-11e6-8ba1-8be6d179e8f6.PNG)

**Comment by ivanov007** [comment]
@Anuskuss you need to post them separated also we need more information, are they cydia or apple apps?

**Comment by Anuskuss** [comment]
They are Apple apps and they ain't in the App Store anymore, so I can't find their iTunes URL etc.

**Comment by ivanov007** [comment]
still they need to be on different issues, and you can post what's on appster?

**Comment by Anuskuss** [comment]
Both icons already exists in Glasklart, and I could look into `Info.plist` and `iTunesMetadata.plist` to get some more info but I hoped it could be as simple as swapping then newly created icons with the old ones.

**Comment by dreamnet** [comment]
@Anuskuss Serach for "Geared" on my website.
