### ISSUE TITLE
Critical Ops

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7569]
**App Name:** Critical Ops
**Bundle ID:** com.criticalforceentertainment.criticalops
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1017717218">1017717218</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/critical-ops/id1017717218?mt=8&uo=4">https://itunes.apple.com/gb/app/critical-ops/id1017717218?mt=8&uo=4</a>
**App Version:** 0.5.3
**Seller:** Critical Force Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/critical-force-oy/id497663725?uo=4>© Critical Force Oy</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/77/36/6f/77366fb3-b50a-e7f4-6f26-7b59919f2180/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16898891/79f6b7b6-4bed-11e6-824b-df7fc87fc424.png)

**Comment by Anuskuss** [comment]
The **C-OPS** will do.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16898891/79f6b7b6-4bed-11e6-824b-df7fc87fc424.png)
https://cloud.githubusercontent.com/assets/2068130/16898891/79f6b7b6-4bed-11e6-824b-df7fc87fc424.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16898894/92297fe4-4bed-11e6-80d5-052e9c00331b.png
