### ISSUE TITLE
TikTok - Real Short Videos

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7570]
**App Name:** TikTok - Real Short Videos
**Bundle ID:** com.zhiliaoapp.musically
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=835599320">835599320</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tiktok-real-short-videos/id835599320?uo=4">https://apps.apple.com/us/app/tiktok-real-short-videos/id835599320?uo=4</a>
**App Version:** 12.5.0
**Seller:** musical.ly inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/musical-ly-inc/id1039610913?uo=4">© musical.ly Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/05/f2/c1/05f2c188-3361-4bdb-a04e-ec5079bf7cb0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838007-b75d0400-bc76-11e9-8894-77633c8b1fa4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712282/bca3afb2-4682-11e6-84d7-e9d8a28cc6eb.png)
https://cloud.githubusercontent.com/assets/2068130/16712282/bca3afb2-4682-11e6-84d7-e9d8a28cc6eb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712283/ca888166-4682-11e6-81f7-8d7b16cfcf78.png

**Comment by Anuskuss** [comment]
Invert it?

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892413/417c07dc-4b12-11e6-9610-013d078acff7.png)
https://cloud.githubusercontent.com/assets/2068130/16892413/417c07dc-4b12-11e6-9610-013d078acff7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892414/520f55ea-4b12-11e6-8f90-97f56083d7d9.png

**Comment by Anuskuss** [comment]
Second :+1:

**Comment by Christian9901** [comment]
needs an update

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62838007-b75d0400-bc76-11e9-8894-77633c8b1fa4.png)
https://user-images.githubusercontent.com/2068130/62838007-b75d0400-bc76-11e9-8894-77633c8b1fa4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62838012-c9d73d80-bc76-11e9-9493-4681d9168510.png
