### ISSUE TITLE
FUTWIZ

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7571]
**App Name:** FUTWIZ
**Bundle ID:** FUTWIZ
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=579253659">579253659</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/futwiz/id579253659?uo=4">https://apps.apple.com/us/app/futwiz/id579253659?uo=4</a>
**App Version:** 4.0.5
**Seller:** Webeast Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/webeast-ltd/id579253662?uo=4">© Webeast Ltd</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/84/d1/82/84d18214-5d21-cb04-8de2-6b1c2c98507b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60394988-b770cc80-9b2c-11e9-87f4-b39133f4562a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712236/5514f636-4681-11e6-86c2-1b8f3a713ec4.png)
https://cloud.githubusercontent.com/assets/2068130/16712236/5514f636-4681-11e6-86c2-1b8f3a713ec4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712237/658dfec2-4681-11e6-92d5-e511882a90f9.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60394988-b770cc80-9b2c-11e9-87f4-b39133f4562a.png)
https://user-images.githubusercontent.com/2068130/60394988-b770cc80-9b2c-11e9-87f4-b39133f4562a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60394991-c6577f00-9b2c-11e9-883c-b0ca56a2b5f8.png
