### ISSUE TITLE
YaPSNapp : Yet Another PlayStation App

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7572]
**App Name:** YaPSNapp : Yet Another PlayStation App
**Bundle ID:** com.drakfly.YaPSNapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469800848">469800848</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yapsnapp-yet-another-playstation/id469800848?mt=8&uo=4">https://itunes.apple.com/us/app/yapsnapp-yet-another-playstation/id469800848?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** JEAN-FRANCOIS LORMEAU
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/drakfly/id469800991?uo=4>© Drakfly</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/14/1f/06/141f06cb-6470-34f9-aa6f-7e6d80177e88/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712257/f780ae38-4681-11e6-9935-585816344483.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712257/f780ae38-4681-11e6-9935-585816344483.png)
https://cloud.githubusercontent.com/assets/2068130/16712257/f780ae38-4681-11e6-9935-585816344483.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712260/05ca548a-4682-11e6-9b77-537bf98c391d.png
