### ISSUE TITLE
Slip Away

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7573]
**App Name:** Slip Away
**Bundle ID:** com.nanovationlabs.slipaway
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1103278932">1103278932</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slip-away/id1103278932?mt=8&uo=4">https://itunes.apple.com/us/app/slip-away/id1103278932?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Nanovation, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nanovation/id876536274?uo=4>© Nanovation</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/f3/67/30/f3673097-ee3a-591c-af84-bc25fd5f9dfd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16966850/bc45c966-4e06-11e6-87d3-b40fe636f442.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16902643/bb8a796a-4c65-11e6-88c8-a5f7b378bc22.png)
https://cloud.githubusercontent.com/assets/2068130/16902643/bb8a796a-4c65-11e6-88c8-a5f7b378bc22.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16902647/caaba892-4c65-11e6-8b58-46980ec494e0.png

**Comment by Anuskuss** [comment]
@dreamnet Can you remove the face details and the shine (I promise this is my last request for now).

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16966850/bc45c966-4e06-11e6-87d3-b40fe636f442.png)
https://cloud.githubusercontent.com/assets/2068130/16966850/bc45c966-4e06-11e6-87d3-b40fe636f442.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16966863/ca858868-4e06-11e6-89cd-212a6ace2fc1.png
