### ISSUE TITLE
System and Security Info

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7574]
**App Name:** System and Security Info
**Bundle ID:** de.sektioneins.sysinfo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1080681261">1080681261</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/system-and-security-info/id1080681261?mt=8&uo=4">https://itunes.apple.com/us/app/system-and-security-info/id1080681261?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** SektionEins GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/developer/sektioneins-gmbh/id1039821610?uo=4>© SektionEins GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/7157389/16695872/57d04cb2-4542-11e6-878e-3050fe976bb5.PNG" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712600/690d6e4c-468c-11e6-95a0-e8052aa78725.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16712600/690d6e4c-468c-11e6-95a0-e8052aa78725.png)
https://cloud.githubusercontent.com/assets/2068130/16712600/690d6e4c-468c-11e6-95a0-e8052aa78725.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16712602/77b9e0c4-468c-11e6-87e5-f83ee7a058e1.png
