### ISSUE TITLE
GC4iOS

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7575]
**App Name:** GC4iOS
**Bundle ID:** com.WilliamCobb.GC4iOS
**Version:** 0.1.3
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/7157389/16696038/4901fd56-4543-11e6-980e-c40ac833275f.PNG" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19012843/e3e2117a-87c0-11e6-892f-13e3947ae771.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19012843/e3e2117a-87c0-11e6-892f-13e3947ae771.png)
https://cloud.githubusercontent.com/assets/20930745/19012843/e3e2117a-87c0-11e6-892f-13e3947ae771.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19012847/f680963a-87c0-11e6-8678-ea824830e60b.png
