### ISSUE TITLE
Jobs by CareerBuilder

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7576]
**App Name:** Jobs by CareerBuilder
**Bundle ID:** com.cb.Kepler
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=524123670">524123670</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jobs-by-careerbuilder/id524123670?mt=8&uo=4">https://itunes.apple.com/us/app/jobs-by-careerbuilder/id524123670?mt=8&uo=4</a>
**App Version:** 1.19.1
**Seller:** CareerBuilder, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/careerbuilder-llc/id284803625?uo=4>© CareerBuilder, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/56/7e/d0/567ed093-1452-6843-10b3-108362911e6d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18230501/7c1a07f6-729d-11e6-9acc-209a5a3231e6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18230501/7c1a07f6-729d-11e6-9acc-209a5a3231e6.png)
https://cloud.githubusercontent.com/assets/20930745/18230501/7c1a07f6-729d-11e6-9acc-209a5a3231e6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18230506/91450d1a-729d-11e6-9487-9470c1f5960a.png
