### ISSUE TITLE
Polymail - Simple, Beautiful, Powerful Email

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7577]
**App Name:** Polymail - Simple, Beautiful, Powerful Email
**Bundle ID:** io.polymail.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1082058386">1082058386</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/polymail-simple-beautiful/id1082058386?mt=8&uo=4">https://itunes.apple.com/us/app/polymail-simple-beautiful/id1082058386?mt=8&uo=4</a>
**App Version:** 1.19
**Seller:** Polymail, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/polymail-inc./id1082058385?uo=4>© Polymail, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/c8/ef/52/c8ef52bb-e3ab-2d09-ee6f-b682faa47c7b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892638/3431ae8a-4b1a-11e6-8774-7d2c4e542b4f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892555/a5881c62-4b16-11e6-81e9-2a7ed04831b3.png)
https://cloud.githubusercontent.com/assets/2068130/16892555/a5881c62-4b16-11e6-81e9-2a7ed04831b3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892556/b55b9646-4b16-11e6-8c36-7d94acbaedcb.png
