### ISSUE TITLE
Notifyr

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7578]
**App Name:** Notifyr
**Bundle ID:** net.techimpulse.notifyr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1109178805">1109178805</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/notifyr/id1109178805?mt=8&uo=4">https://itunes.apple.com/us/app/notifyr/id1109178805?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Notifyr Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/notifyr-inc./id1109178804?uo=4>© Notifyr Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/d7/ba/38/d7ba3830-e6f8-b953-c880-7b8ff521f4bf/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892879/5030ea84-4b23-11e6-8bdb-4ef203d1f540.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892879/5030ea84-4b23-11e6-8bdb-4ef203d1f540.png)
https://cloud.githubusercontent.com/assets/2068130/16892879/5030ea84-4b23-11e6-8bdb-4ef203d1f540.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892881/5e7cf54c-4b23-11e6-8a3e-51c0127064be.png
