### ISSUE TITLE
CameraSharp - Anti Shake, Burst, Time Lapse, Self Timer Camera

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7579]
**App Name:** CameraSharp - Anti Shake, Burst, Time Lapse, Self Timer Camera
**Bundle ID:** com.screensmudge.CameraSharp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=442142280">442142280</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camerasharp-anti-shake-burst/id442142280?mt=8&uo=4">https://itunes.apple.com/us/app/camerasharp-anti-shake-burst/id442142280?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** screensmudge LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/screensmudge/id337437937?uo=4>© screensmudge</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/a5/9d/b6/a59db61e-26fd-26f0-e0c5-f2b83307872d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16893070/61b62082-4b2b-11e6-968f-663dd8995170.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16893070/61b62082-4b2b-11e6-968f-663dd8995170.png)
https://cloud.githubusercontent.com/assets/2068130/16893070/61b62082-4b2b-11e6-968f-663dd8995170.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16893071/6fcae64e-4b2b-11e6-8d53-530d13d58dfd.png
