### ISSUE TITLE
Juxtaposer

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7580]
**App Name:** Juxtaposer
**Bundle ID:** com.hkueck.juxtaposer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=292628469">292628469</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/juxtaposer/id292628469?mt=8&uo=4">https://itunes.apple.com/us/app/juxtaposer/id292628469?mt=8&uo=4</a>
**App Version:** 3.7.1
**Seller:** Pocket Pixels Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pocket-pixels-inc./id292628472?uo=4>© Pocket Pixels Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/56/87/ee/5687ee8f-06c8-169f-3793-da59d4748499/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17086514/47585b0e-51f4-11e6-8e66-6b2615bc3a71.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17086514/47585b0e-51f4-11e6-8e66-6b2615bc3a71.png)
https://cloud.githubusercontent.com/assets/2068130/17086514/47585b0e-51f4-11e6-8e66-6b2615bc3a71.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17086516/581b87ea-51f4-11e6-85c8-1b066004479d.png
