### ISSUE TITLE
Toast - Photo Editor & Create stylish photos!

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7581]
**App Name:** Toast - Photo Editor & Create stylish photos!
**Bundle ID:** kr.co.geeklab.PhotoArtist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=820734685">820734685</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/toast-photo-editor-create/id820734685?mt=8&uo=4">https://itunes.apple.com/us/app/toast-photo-editor-create/id820734685?mt=8&uo=4</a>
**App Version:** 3.8.1
**Seller:** Junghyeon Kim
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/junghyeon-kim/id491853187?uo=4>© Junghyeon Kim</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/14/f8/7c/14f87c47-5993-a22b-ef0a-0101ad06f4f7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17086551/b0f250d2-51f5-11e6-867e-b70fb483257e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17086551/b0f250d2-51f5-11e6-867e-b70fb483257e.png)
https://cloud.githubusercontent.com/assets/2068130/17086551/b0f250d2-51f5-11e6-867e-b70fb483257e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17086553/c007a11c-51f5-11e6-9f89-12b48e12ebb5.png
