### ISSUE TITLE
Zippy

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7582]
**App Name:** Zippy
**Bundle ID:** com.Zippy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=799559265">799559265</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/zippy/id799559265?mt=8&uo=4">https://itunes.apple.com/au/app/zippy/id799559265?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** BDS.com.au Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/au/developer/bds-pty-ltd/id799559268?uo=4>© BDS Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/94/3f/4d/943f4d6d-a68b-98d4-ab23-1568df6625e0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892478/f119ab80-4b13-11e6-8003-07f08befe1ca.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892478/f119ab80-4b13-11e6-8003-07f08befe1ca.png)
https://cloud.githubusercontent.com/assets/2068130/16892478/f119ab80-4b13-11e6-8003-07f08befe1ca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892482/ff5f34c6-4b13-11e6-9a6d-22f8663e41f9.png
