### ISSUE TITLE
WiFiFoFum Pro

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7583]
**App Name:** WiFiFoFum Pro
**Bundle ID:** com.dynamicallyloaded.WiFiFoFumProJB
 **Version:** 1.1.1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
![appiconpro76x76 1](https://cloud.githubusercontent.com/assets/5791220/16759735/b046dd86-485b-11e6-981c-eddafb814f3b.png)
 **Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16893175/e0a5f012-4b2f-11e6-984b-e2702cab2c45.png)

**Comment by ivanov007** [comment]
@quantum8  this one actually works? do you have the repo? I miss the old one that only worked win iOS 7 and below

**Comment by quantum8** [comment]
Yeah it's working for me on my device running 8.4. Otherwise I use wifiexplorer.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16893175/e0a5f012-4b2f-11e6-984b-e2702cab2c45.png)
https://cloud.githubusercontent.com/assets/2068130/16893175/e0a5f012-4b2f-11e6-984b-e2702cab2c45.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16893183/ef634686-4b2f-11e6-950b-c6ba6d243005.png

**Comment by dreamnet** [comment]
@quantum8 I think the bundle ID is `com.dynamicallyloaded.wififofumpro`? [Click.](http://modmyi.com/cydia/package.php?id=68286)

**Comment by Anuskuss** [comment]
@dreamnet Just downloaded, it's `com.dynamicallyloaded.WiFiFoFumProJB`.
