### ISSUE TITLE
Pokémon GO

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7584]
**App Name:** Pokémon GO
**Bundle ID:** com.nianticlabs.pokemongo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1094591345">1094591345</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pokemon-go/id1094591345?mt=8&uo=4">https://itunes.apple.com/us/app/pokemon-go/id1094591345?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Niantic, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/niantic-inc./id1037205060?uo=4>© Niantic, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/3e/ab/dd/3eabdd93-db13-558a-980d-c1972b0f440b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16884956/8de40a52-4acc-11e6-964e-87ca7b935eed.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16884956/8de40a52-4acc-11e6-964e-87ca7b935eed.png)
https://cloud.githubusercontent.com/assets/2068130/16884956/8de40a52-4acc-11e6-964e-87ca7b935eed.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16884968/9c72d5ee-4acc-11e6-8626-145ee9acbb03.png
