### ISSUE TITLE
Breaking News +

### ISSUE THREAD

**Issue by jpokorny2** [glasklart/hd#7585]
**App Name:** Breaking News +
**Bundle ID:** com.msnbc.breakingnews.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=394533293">394533293</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/breaking-news-+/id394533293?mt=8&uo=4">https://itunes.apple.com/us/app/breaking-news-+/id394533293?mt=8&uo=4</a>
**App Version:** 3.9.2
**Seller:** NBC News Digital, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nbc-news-digital-llc/id393196223?uo=4>© NBC News Digital, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple18/v4/b4/b9/97/b4b99748-565c-d1a6-98fb-c1c0020079e3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892426/e8905186-4b12-11e6-81cb-f186e751bb6d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892426/e8905186-4b12-11e6-81cb-f186e751bb6d.png)
https://cloud.githubusercontent.com/assets/2068130/16892426/e8905186-4b12-11e6-81cb-f186e751bb6d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892429/f8158720-4b12-11e6-8dcb-6973081ca25a.png
