### ISSUE TITLE
Pinball Tristan

### ISSUE THREAD

**Issue by jpokorny2** [glasklart/hd#7586]
**App Name:** Pinball Tristan
**Bundle ID:** com.littlewingpinball.Pinball-Tristan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431632510">431632510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pinball-tristan/id431632510?mt=8&uo=4">https://itunes.apple.com/us/app/pinball-tristan/id431632510?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** LittleWing Co. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/littlewing/id431632518?uo=4>© LittleWing</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/a9/6c/fc/a96cfc3a-049b-a152-eeaf-0f0a94bc6a18/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892950/0e67ead2-4b26-11e6-8c87-78336973959f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892950/0e67ead2-4b26-11e6-8c87-78336973959f.png)
https://cloud.githubusercontent.com/assets/2068130/16892950/0e67ead2-4b26-11e6-8c87-78336973959f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892951/1ca19580-4b26-11e6-827d-f40c98b61f6d.png
