### ISSUE TITLE
Paprika Recipe Manager - Get your recipes organized!

### ISSUE THREAD

**Issue by jpokorny2** [glasklart/hd#7587]
**App Name:** Paprika Recipe Manager - Get your recipes organized!
**Bundle ID:** com.hindsightlabs.paprika.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=392408028">392408028</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paprika-recipe-manager-get/id392408028?mt=8&uo=4">https://itunes.apple.com/us/app/paprika-recipe-manager-get/id392408028?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Hindsight Labs LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hindsight-labs-llc/id392408031?uo=4>© Hindsight Labs LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/9f/54/27/9f542709-26a9-8e2b-cfe8-04643e9df44a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18095909/c799f010-6ed8-11e6-9858-1d06065e1578.png)

**Comment by alpcinar** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13483942/18029799/071ac05a-6cab-11e6-97dc-cc4dff2d34b9.png)
https://cloud.githubusercontent.com/assets/13483942/18029799/071ac05a-6cab-11e6-97dc-cc4dff2d34b9.png
Source:
https://cloud.githubusercontent.com/assets/13483942/18029800/0dc4b622-6cab-11e6-97a2-f754505872fd.png

**Comment by dreamnet** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18030006/aaf77432-6ca8-11e6-94b7-2c228c7d8c12.png)
https://cloud.githubusercontent.com/assets/2068130/18030006/aaf77432-6ca8-11e6-94b7-2c228c7d8c12.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18030010/bcf9f754-6ca8-11e6-9b4d-77798f7c5d2d.png
@alpcinar Did you use more than one layer for the Glasklart icon? - That's not allowed. Also: Source is wrong, please compare with the source I made.
