### ISSUE TITLE
Weather Radio by WDT

### ISSUE THREAD

**Issue by jpokorny2** [glasklart/hd#7589]
**App Name:** Weather Radio by WDT
**Bundle ID:** com.wdtinc.mwr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=413511993">413511993</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-radio-by-wdt/id413511993?mt=8&uo=4">https://itunes.apple.com/us/app/weather-radio-by-wdt/id413511993?mt=8&uo=4</a>
**App Version:** 3.0.5
**Seller:** Weather Decision Technologies, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/weather-decision-technologies/id323711285?uo=4>© Weather Decision Technologies, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/64/a0/5a/64a05ac1-4b31-ce44-9267-4abaf9c2346a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16885848/e5c911be-4ad0-11e6-9d42-25bc16a6176f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16885848/e5c911be-4ad0-11e6-9d42-25bc16a6176f.png)
https://cloud.githubusercontent.com/assets/2068130/16885848/e5c911be-4ad0-11e6-9d42-25bc16a6176f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16885864/f3fd8ac6-4ad0-11e6-8dbf-683bc00cd52e.png
