### ISSUE TITLE
Outread – Speed Reading

### ISSUE THREAD

**Issue by jpokorny2** [glasklart/hd#7590]
**App Name:** Outread – Speed Reading
**Bundle ID:** pl.holko.ReadFaster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=778846279">778846279</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/outread-speed-reading/id778846279?mt=8&uo=4">https://itunes.apple.com/us/app/outread-speed-reading/id778846279?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Arkadiusz Holko
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/arkadiusz-holko/id683846458?uo=4>© Arkadiusz Holko</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/c3/9b/1b/c39b1bbd-a200-e03f-200e-5eef6e289ddc/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16885187/b59c1ef8-4acd-11e6-8864-94b28a3abef3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16885187/b59c1ef8-4acd-11e6-8864-94b28a3abef3.png)
https://cloud.githubusercontent.com/assets/2068130/16885187/b59c1ef8-4acd-11e6-8864-94b28a3abef3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16885200/c409f1cc-4acd-11e6-902c-10cf1af87352.png
