### ISSUE TITLE
HealthView - Your Health & Fitness Data Dashboard

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7591]
**App Name:** HealthView - Your Health & Fitness Data Dashboard
**Bundle ID:** com.funnmedia.HealthMinder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1020452064">1020452064</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/healthview-your-health-fitness/id1020452064?mt=8&uo=4">https://itunes.apple.com/us/app/healthview-your-health-fitness/id1020452064?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Funn Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/funn-media-llc/id646811578?uo=4>© Funn Media, LLC</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/11/71/71/1171713c-e9ed-ba3e-d8c8-97f5b2688398/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899658/30f24994-4c0c-11e6-8a9c-94e33ed11da4.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899658/30f24994-4c0c-11e6-8a9c-94e33ed11da4.png)
https://cloud.githubusercontent.com/assets/2068130/16899658/30f24994-4c0c-11e6-8a9c-94e33ed11da4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16899659/3e1204a2-4c0c-11e6-9c4e-eb97b95533b2.png
