### ISSUE TITLE
Pedometer by StepsApp: Step Counter - Activity & Fitness Tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7592]
**App Name:** StepsApp Pedometer - Step Counter Activity Tracker
**Bundle ID:** com.gunthermarktl.stepapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1037595083">1037595083</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stepsapp-pedometer-step-counter-activity-tracker/id1037595083?mt=8&uo=4">https://itunes.apple.com/us/app/stepsapp-pedometer-step-counter-activity-tracker/id1037595083?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** StepsApp GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/stepsapp-gmbh/id1018640589?uo=4">© StepsApp GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/ff/47/f3/ff47f3d2-d76e-488f-b8a0-8084b5523afc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25956081/1c0ba058-366b-11e7-9180-62edff1892ab.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899692/af4eb286-4c0d-11e6-966b-6b634b265502.png)
https://cloud.githubusercontent.com/assets/2068130/16899692/af4eb286-4c0d-11e6-966b-6b634b265502.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16899695/c1097d62-4c0d-11e6-996f-48823e03b2fb.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** StepsApp Pedometer - Step Counter Activity Tracker
**Bundle ID:** com.gunthermarktl.stepapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1037595083">1037595083</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stepsapp-pedometer-step-counter-activity-tracker/id1037595083?mt=8&uo=4">https://itunes.apple.com/us/app/stepsapp-pedometer-step-counter-activity-tracker/id1037595083?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** StepsApp GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/stepsapp-gmbh/id1018640589?uo=4">© StepsApp GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/ff/47/f3/ff47f3d2-d76e-488f-b8a0-8084b5523afc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25956081/1c0ba058-366b-11e7-9180-62edff1892ab.png)
https://cloud.githubusercontent.com/assets/20930745/25956081/1c0ba058-366b-11e7-9180-62edff1892ab.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25956134/35622a18-366b-11e7-9c79-8eace91db5b6.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25956486/281289e2-366c-11e7-8322-9b3daf75be4c.png)
https://cloud.githubusercontent.com/assets/20930745/25956486/281289e2-366c-11e7-8322-9b3daf75be4c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25956518/3bc5eccc-366c-11e7-9268-8aca16af2a2a.png
