### ISSUE TITLE
Roadtrippers - Road Trip Planner Map & Travel Guides

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7593]
**App Name:** Roadtrippers - Road Trip Planner Map & Travel Guides
**Bundle ID:** com.roadtrippers.roadtrippersinc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944060491">944060491</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/roadtrippers-road-trip-planner/id944060491?mt=8&uo=4">https://itunes.apple.com/us/app/roadtrippers-road-trip-planner/id944060491?mt=8&uo=4</a>
**App Version:** 3.4.8
**Seller:** Roadtrippers LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/roadtrippers/id573012553?uo=4>© Roadtrippers</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/b8/7a/d9/b87ad9b4-5da8-b5ca-aea2-705093a146f4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899098/9fce1006-4bf7-11e6-957e-3442a7d67bb0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899098/9fce1006-4bf7-11e6-957e-3442a7d67bb0.png)
https://cloud.githubusercontent.com/assets/2068130/16899098/9fce1006-4bf7-11e6-957e-3442a7d67bb0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16899100/b11fde66-4bf7-11e6-8ab5-59b715987f7b.png

**Comment by dreamnet** [comment]
@Anuskuss No, the original has also a shadow.
