### ISSUE TITLE
AdBlock

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7594]
**App Name:** AdBlock
**Bundle ID:** com.futuremind.adblock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=691121579">691121579</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adblock/id691121579?mt=8&uo=4">https://itunes.apple.com/us/app/adblock/id691121579?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** Future Mind, Sp. z o.o.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/futuremind/id392259659?uo=4>© FutureMind</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/3a/4f/95/3a4f959a-16b8-13f6-3f83-6704dae440fd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16966267/0da26240-4e04-11e6-8513-3db92e47ad70.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16898920/6256a4fc-4bef-11e6-9e56-c86f173e6cd9.png)
https://cloud.githubusercontent.com/assets/2068130/16898920/6256a4fc-4bef-11e6-9e56-c86f173e6cd9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16898922/728a6c50-4bef-11e6-9f22-4db96293a209.png

**Comment by Anuskuss** [comment]
@dreamnet Ehm, can you, you know, make the **ADBLOCK** border a bit thicker :cold_sweat:

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16966267/0da26240-4e04-11e6-8513-3db92e47ad70.png)
https://cloud.githubusercontent.com/assets/2068130/16966267/0da26240-4e04-11e6-8513-3db92e47ad70.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16966284/1bf39bde-4e04-11e6-9d43-3c5f912e1c65.png
