### ISSUE TITLE
Fruit Ninja

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7595]
**App Name:** Fruit Ninja
**Bundle ID:** com.Halfbrick.Fruit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=362949845">362949845</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fruit-ninja/id362949845?mt=8&uo=4">https://itunes.apple.com/us/app/fruit-ninja/id362949845?mt=8&uo=4</a>
**App Version:** 2.3.4
**Seller:** Halfbrick
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/halfbrick-studios/id356994313?uo=4>© Halfbrick Studios</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/1b/9f/a2/1b9fa24e-9670-a927-fe5f-be1fc8127313/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19012523/cbfea9fe-87b8-11e6-9657-a8170b2a95cb.png)

**Comment by Anuskuss** [comment]
Icon exists, but could need some small corrections.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19012523/cbfea9fe-87b8-11e6-9657-a8170b2a95cb.png)
https://cloud.githubusercontent.com/assets/20930745/19012523/cbfea9fe-87b8-11e6-9657-a8170b2a95cb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19012525/d795d5da-87b8-11e6-80c4-57af611316d4.png
