### ISSUE TITLE
Doodle Jump

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7596]
**App Name:** Doodle Jump
**Bundle ID:** com.yourcompany.DoodleJump
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307727765">307727765</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/doodle-jump/id307727765?mt=8&uo=4">https://itunes.apple.com/us/app/doodle-jump/id307727765?mt=8&uo=4</a>
**App Version:** 3.16
**Seller:** Lima Sky
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lima-sky/id285874818?uo=4>© Lima Sky</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/ad/f0/12/adf01224-5f3d-cf09-67a5-6fdf369a1926/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16967772/10082db0-4e0b-11e6-82ad-df493601febb.png)

**Comment by Anuskuss** [comment]
Icon exists, but I would like to have a more "modern" version of this icon.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16899056/e2ee26de-4bf5-11e6-80d6-3336524a0350.png)
https://cloud.githubusercontent.com/assets/2068130/16899056/e2ee26de-4bf5-11e6-80d6-3336524a0350.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16899060/f1901058-4bf5-11e6-83a5-372517fcf347.png

**Comment by Anuskuss** [comment]
@dreamnet I like your structure, and I used it for my (ugly) mockup. What do you think about going in a direction like this:
![](https://cloud.githubusercontent.com/assets/7157389/16904098/c0f5bbf6-4c8f-11e6-93c1-12f8dbf57922.png)

I just painted a bit white over the lines and filled some parts.

**Comment by dreamnet** [comment]
@Anuskuss Fine for me.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16967772/10082db0-4e0b-11e6-82ad-df493601febb.png)
https://cloud.githubusercontent.com/assets/2068130/16967772/10082db0-4e0b-11e6-82ad-df493601febb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16967783/1e639d4a-4e0b-11e6-89ac-a5653cd4c92d.png

**Comment by Anuskuss** [comment]
I've created a second one and I can't decide which looks better so I rely on your trained eyes :relieved:
![doodledreamnet](https://cloud.githubusercontent.com/assets/7157389/17071578/b61a3f32-5062-11e6-9f8d-206a2174863c.png) ![doodle3](https://cloud.githubusercontent.com/assets/7157389/17071581/b74b8866-5062-11e6-8508-367301236070.png)

**Comment by ivanov007** [comment]
well I think the second one has too much white

**Comment by dreamnet** [comment]
@ivanov007 Agree.
