### ISSUE TITLE
Cut the Rope

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7597]
**App Name:** Cut the Rope
**Bundle ID:** com.zeptolab.cuttherope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1024505111">1024505111</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cut-the-rope/id1024505111?mt=8&uo=4">https://itunes.apple.com/us/app/cut-the-rope/id1024505111?mt=8&uo=4</a>
**App Version:** 2.7.1
**Seller:** ZeptoLab UK Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zeptolab-uk-limited/id450542236?uo=4>© ZeptoLab UK Limited</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/fc/e5/29/fce5298c-9ccd-542f-37f5-1e8339448712/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18942764/6d920814-861b-11e6-9031-a62e875d9c51.png)

**Comment by Anuskuss** [comment]
I don't know why they deleted the old app and created this look-a-like (maybe double payment?).

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/16974504/d4335902-4e02-11e6-8838-0f6d7405b01c.png)
https://cloud.githubusercontent.com/assets/3090247/16974504/d4335902-4e02-11e6-8838-0f6d7405b01c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/16974505/d45200aa-4e02-11e6-9ee5-3dbbc89b809d.png

**Comment by dreamnet** [comment]
@ivanov007 Wow! Looks great to me! :+1:

**Comment by LaCh0uine** [comment]
don't work on 5.1 need update 
thank you

**Comment by dreamnet** [comment]
@LaCh0uine Are you sure you have the right iTunes ID? This icon is already in [the repo](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.zeptolab.cuttherope-large.png).

**Comment by LaCh0uine** [comment]
@dreamnet you have reason I have the original.. not this version :(

**Comment by LaCh0uine** [comment]
My version is edited by chilligo ltd .. now is zeptolab :/

**Comment by dreamnet** [comment]
@LaCh0uine We need the iTunes ID and if the app dosen't exist anymore the bundle ID. Here is [how you can find out the iTunes ID](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request#finding-the-itunes-id-on-the-itunes-app-store-pc). The bundle ID is stored in the `Info.plist` of the app on your device (assuming something like `com.chillingo.cuttherope`).

**Comment by LaCh0uine** [comment]
I look tonight my iPhone 7 is not jailbreaked ;)
Thank you

**Comment by dreamnet** [comment]
@LaCh0uine All fine, I got it. I open a new issue for Cut the Rope Original.
