### ISSUE TITLE
Weblock - AdBlock for apps and websites

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7598]
**App Name:** Weblock - AdBlock for apps and websites
**Bundle ID:** com.futuremind.wpad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=558818638">558818638</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weblock-adblock-for-apps-websites/id558818638?mt=8&uo=4">https://itunes.apple.com/us/app/weblock-adblock-for-apps-websites/id558818638?mt=8&uo=4</a>
**App Version:** 4.3.1
**Seller:** Future Mind, Sp. z o.o.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/futuremind/id392259659?uo=4>© FutureMind</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/64/a6/57/64a65706-4866-fe29-3180-7244f623be51/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16898910/abcff97c-4bee-11e6-8f1f-97ca380b7e12.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16898910/abcff97c-4bee-11e6-8f1f-97ca380b7e12.png)
https://cloud.githubusercontent.com/assets/2068130/16898910/abcff97c-4bee-11e6-8f1f-97ca380b7e12.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16898912/bdaa1fc4-4bee-11e6-891c-2d7d7103b1b7.png
