### ISSUE TITLE
Ridge Racer Slipstream

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7599]
**App Name:** Ridge Racer Slipstream
**Bundle ID:** com.namcobandaigames.ridgeracermobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=725879978">725879978</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ridge-racer-slipstream/id725879978?mt=8&uo=4">https://itunes.apple.com/us/app/ridge-racer-slipstream/id725879978?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** BANDAI NAMCO Entertainment America Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bandai-namco-entertainment/id281656478?mt=8&uo=4">© BANDAI NAMCO Entertainment America Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/06/6a/a6/066aa6e7-af0c-b504-0963-94f66d90517b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20638092/41bdd052-b39c-11e6-935f-f164b5ae9d3d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20638092/41bdd052-b39c-11e6-935f-f164b5ae9d3d.png)
https://cloud.githubusercontent.com/assets/2068130/20638092/41bdd052-b39c-11e6-935f-f164b5ae9d3d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20638096/52f74b00-b39c-11e6-9b08-249eb549481e.png
