### ISSUE TITLE
Geared 2!

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7601]
**App Name:** Geared 2!
**Bundle ID:** com.playfulart.Geared2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405759718">405759718</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/geared-2/id405759718?mt=8&uo=4">https://itunes.apple.com/us/app/geared/id405759718?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Bryan Mitchell
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bryan-mitchell/id306554397?uo=4>© Bryan Mitchell</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://glasklarthd.dreamnet.at/theicons/569/com.playfulart.Geared2_orig_big.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18814894/6092af86-8320-11e6-94b6-9ec511a33164.png)

**Comment by Anuskuss** [comment]
See #7568

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18814894/6092af86-8320-11e6-94b6-9ec511a33164.png)
https://cloud.githubusercontent.com/assets/2068130/18814894/6092af86-8320-11e6-94b6-9ec511a33164.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18814895/6f5f848a-8320-11e6-905c-bfc25de3f858.png
