### ISSUE TITLE
My Cicis

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7602]
**App Name:** My Cicis
**Bundle ID:** com.ChowNow.CicisPizza
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=582852042">582852042</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-cicis/id582852042?mt=8&uo=4">https://itunes.apple.com/us/app/my-cicis/id582852042?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Punchh Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/punchh-inc./id386700205?uo=4>© Punchh Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/14/5e/65/145e6576-08c7-4df2-158e-4b1dec42756f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085362/469e8f8a-51d6-11e6-8619-4a1a0ff7034d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085362/469e8f8a-51d6-11e6-8619-4a1a0ff7034d.png)
https://cloud.githubusercontent.com/assets/2068130/17085362/469e8f8a-51d6-11e6-8619-4a1a0ff7034d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17085366/556dbafe-51d6-11e6-9e05-1be3abd74d82.png
