### ISSUE TITLE
Tradewise (formerly ‘Trdr’) - intelligent stock portfolio alerts for E*TRADE, Schwab, TD Ameritrade, and Fidelity traders

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7603]
**App Name:** Tradewise (formerly ‘Trdr’) - intelligent stock portfolio alerts for E*TRADE, Schwab, TD Ameritrade, and Fidelity traders
**Bundle ID:** io.trdr.trdr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=983611490">983611490</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tradewise-formerly-trdr-intelligent/id983611490?mt=8&uo=4">https://itunes.apple.com/us/app/tradewise-formerly-trdr-intelligent/id983611490?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** TRDR, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/trdr-inc./id983611489?uo=4>© TRDR, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/db/a7/56/dba756e1-f80f-9d2d-cc93-b301330d2243/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085279/c0055dce-51d4-11e6-8045-61deba0b832b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085279/c0055dce-51d4-11e6-8045-61deba0b832b.png)
https://cloud.githubusercontent.com/assets/2068130/17085279/c0055dce-51d4-11e6-8045-61deba0b832b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17085282/cf1009ea-51d4-11e6-9778-45a4feaf6156.png
