### ISSUE TITLE
Summit - Summarized News Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7604]
**App Name:** Summit - Summarized News Reader
**Bundle ID:** com.varunnshenoy.summit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1106793298">1106793298</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/summit-summarized-news-reader/id1106793298?mt=8&uo=4">https://itunes.apple.com/us/app/summit-summarized-news-reader/id1106793298?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** Shaila Shenoy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shaila-shenoy/id1106793297?uo=4>© Shaila Shenoy</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/bf/06/81/bf068138-d392-929d-62de-28f4da2d80e4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085102/1ce8aa6e-51d0-11e6-9564-aad1498b0903.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085102/1ce8aa6e-51d0-11e6-9564-aad1498b0903.png)
https://cloud.githubusercontent.com/assets/2068130/17085102/1ce8aa6e-51d0-11e6-9564-aad1498b0903.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17085105/301a25e0-51d0-11e6-97df-021b0c5c0c15.png
