### ISSUE TITLE
Dials Calendar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7605]
**App Name:** Dials Calendar
**Bundle ID:** com.dialsapp.gc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1095827323">1095827323</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dials-calendar/id1095827323?mt=8&uo=4">https://itunes.apple.com/us/app/dials-calendar/id1095827323?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** DayDials, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/daydials-inc./id982837759?uo=4>© DayDials, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/78/05/ca/7805ca9d-4e3f-fdc4-ca68-4ebc1c2d3fa4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085550/85fa0650-51db-11e6-8092-fcd2bd4a128b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085550/85fa0650-51db-11e6-8092-fcd2bd4a128b.png)
https://cloud.githubusercontent.com/assets/2068130/17085550/85fa0650-51db-11e6-8092-fcd2bd4a128b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17085554/95838542-51db-11e6-9369-1d079f45b3f6.png
