### ISSUE TITLE
Pen and Paper

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7606]
**App Name:** Pen and Paper
**Bundle ID:** com.mexircus.penandpaper
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=425893570">425893570</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pen-and-paper/id425893570?mt=8&uo=4">https://itunes.apple.com/us/app/pen-and-paper/id425893570?mt=8&uo=4</a>
**App Version:** 1.8.3
**Seller:** Jens Egeblad
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vivid-apps/id291793754?mt=8&uo=4>© Vivid Apps</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/93/63/41/9363412d-c0e5-2fd1-17dc-6c7244c4bbcf/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085066/3d5b3862-51cf-11e6-8097-2b21f321699a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17085066/3d5b3862-51cf-11e6-8097-2b21f321699a.png)
https://cloud.githubusercontent.com/assets/2068130/17085066/3d5b3862-51cf-11e6-8097-2b21f321699a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17085070/4b73660e-51cf-11e6-8e9e-f677d61887f5.png
