### ISSUE TITLE
Dunkers

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7607]
**App Name:** Dunkers
**Bundle ID:** com.stencyl.dunkers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1110480334">1110480334</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dunkers/id1110480334?mt=8&uo=4">https://itunes.apple.com/us/app/dunkers/id1110480334?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Colin Lane
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/colin-lane/id899921557?uo=4>© Colin Lane</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple18/v4/63/ad/87/63ad87d2-78da-bf38-4b18-bce28949f0d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18234539/b24ecc1e-7309-11e6-81cc-c5bc76744d92.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17085033/564c1044-5193-11e6-9c4b-3a50bd3180f9.png)
https://cloud.githubusercontent.com/assets/3090247/17085033/564c1044-5193-11e6-9c4b-3a50bd3180f9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17085032/564b9498-5193-11e6-8057-77e861a757e4.png

**Comment by dreamnet** [comment]
@ivanov007 Fine! :+1:

**Comment by Anuskuss** [comment]
@ivanov007 I tried different version with fewer details and I liked the one with no details the most. What do you think?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/17085033/564c1044-5193-11e6-9c4b-3a50bd3180f9.png) ![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/17273177/5ce52df0-56ac-11e6-9822-95af1c4bd29e.png) ![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/17273179/6b0e77e2-56ac-11e6-871c-b8906d8f2408.png) ![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/17273183/756e522a-56ac-11e6-8b70-71f8bfec8f08.png)

**Comment by Anuskuss** [comment]
Removed some detail:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18234539/b24ecc1e-7309-11e6-81cc-c5bc76744d92.png)
https://cloud.githubusercontent.com/assets/7157389/18234539/b24ecc1e-7309-11e6-81cc-c5bc76744d92.png


___

Source:
https://cloud.githubusercontent.com/assets/7157389/18234547/d5621774-7309-11e6-8d0c-1f04c20eedef.png
