### ISSUE TITLE
Truebill: Find, Track, and Manage Your Paid Subscriptions and Recurring Bills

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7608]
**App Name:** Truebill: Find, Track, and Manage Your Paid Subscriptions and Recurring Bills
**Bundle ID:** com.truebill.truebillnative
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1130616675">1130616675</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/truebill-find-track-manage/id1130616675?mt=8&uo=4">https://itunes.apple.com/us/app/truebill-find-track-manage/id1130616675?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Truebill, LLC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/truebill/id1130616674?uo=4>© Truebill</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/35/8e/16/358e16cc-fdc0-193e-540d-78769e4f8e14/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17199336/ba21da80-5441-11e6-8940-c1448c275ad3.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17199336/ba21da80-5441-11e6-8940-c1448c275ad3.png)
https://cloud.githubusercontent.com/assets/3090247/17199336/ba21da80-5441-11e6-8940-c1448c275ad3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17199337/ba307c70-5441-11e6-8351-6c6f0dacbf5a.png
