### ISSUE TITLE
CPlus for Craigslist app - mobile classifieds

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7609]
**App Name:** CPlus for Craigslist app - mobile classifieds
**Bundle ID:** YanFlex.CPlus.Craigslist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955286870">955286870</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cplus-for-craigslist-app-mobile-classifieds/id955286870?mt=8&uo=4">https://itunes.apple.com/us/app/cplus-for-craigslist-app-mobile-classifieds/id955286870?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** YanFlex Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yanflex-inc/id435351159?uo=4">© YanFlex Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/6b/e6/93/6be6930f-0162-bc8c-6c92-d9c7a7728713/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28419133-bce1ca18-6d23-11e7-81f4-5f3b37660ad5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268576/2ae478e8-562e-11e6-9bae-455b1d67c574.png)
https://cloud.githubusercontent.com/assets/2068130/17268576/2ae478e8-562e-11e6-9bae-455b1d67c574.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268577/39004a4c-562e-11e6-9c51-e6e8891bf2d0.png

**Comment by l8er4now** [comment]
Needs a bit of an update.

**App Name:** CPlus for Craigslist app - mobile classifieds
**Bundle ID:** YanFlex.CPlus.Craigslist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955286870">955286870</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cplus-for-craigslist-app-mobile/id955286870?mt=8&uo=4">https://itunes.apple.com/us/app/cplus-for-craigslist-app-mobile/id955286870?mt=8&uo=4</a>
**App Version:** 2.3.8
**Seller:** YanFlex Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yanflex-inc./id435351159?uo=4>© YanFlex Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/e2/4a/bc/e24abcbd-367e-3171-a6d6-154834707bb6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18926375/dc8cefae-85b7-11e6-8f29-cc43291103e2.png)
https://cloud.githubusercontent.com/assets/20930745/18926375/dc8cefae-85b7-11e6-8f29-cc43291103e2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18926394/ea080402-85b7-11e6-9f16-e747a88339c1.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** CPlus for Craigslist app - mobile classifieds
**Bundle ID:** YanFlex.CPlus.Craigslist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955286870">955286870</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cplus-for-craigslist-app-mobile-classifieds/id955286870?mt=8&uo=4">https://itunes.apple.com/us/app/cplus-for-craigslist-app-mobile-classifieds/id955286870?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** YanFlex Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yanflex-inc/id435351159?uo=4">© YanFlex Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/6b/e6/93/6be6930f-0162-bc8c-6c92-d9c7a7728713/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28419133-bce1ca18-6d23-11e7-81f4-5f3b37660ad5.png)
https://user-images.githubusercontent.com/3090247/28419133-bce1ca18-6d23-11e7-81f4-5f3b37660ad5.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/28419134-bcfb9b0a-6d23-11e7-92a6-e26981d3db34.png
