### ISSUE TITLE
Microsoft Pix

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7610]
**App Name:** Microsoft Pix
**Bundle ID:** com.microsoft.pix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1127910488">1127910488</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-pix/id1127910488?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-pix/id1127910488?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple18/v4/8e/31/b4/8e31b4a6-47c8-bd7b-ebba-572fc297ac2b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268518/ad472418-562c-11e6-8b24-22a80377dbdb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268518/ad472418-562c-11e6-8b24-22a80377dbdb.png)
https://cloud.githubusercontent.com/assets/2068130/17268518/ad472418-562c-11e6-8b24-22a80377dbdb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268519/bb66d994-562c-11e6-883b-9c1fbc4af414.png
