### ISSUE TITLE
numberFire Fantasy Sports - News, Projections for Football / Basketball / Hockey

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7611]
**App Name:** numberFire Fantasy Sports - News, Projections for Football / Basketball / Hockey
**Bundle ID:** com.numberFire.numberFire
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=907642513">907642513</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/numberfire-fantasy-sports/id907642513?mt=8&uo=4">https://itunes.apple.com/us/app/numberfire-fantasy-sports/id907642513?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** numberFire, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/numberfire/id907642516?uo=4>© numberFire</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/df/fb/3e/dffb3e82-2703-c3e1-31db-085c8c28199d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268634/4572ef9e-5630-11e6-99f9-eb37bc1d9f4b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268634/4572ef9e-5630-11e6-99f9-eb37bc1d9f4b.png)
https://cloud.githubusercontent.com/assets/2068130/17268634/4572ef9e-5630-11e6-99f9-eb37bc1d9f4b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268635/53fd5f68-5630-11e6-95ff-4a554b00687d.png
