### ISSUE TITLE
Fantasy News by FantasyPros

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7612]
**App Name:** Fantasy News by FantasyPros
**Bundle ID:** com.fantasypros.news
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967102422">967102422</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasy-news-by-fantasypros/id967102422?mt=8&uo=4">https://itunes.apple.com/us/app/fantasy-news-by-fantasypros/id967102422?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Marzen Media LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marzen-media-llc/id892964104?uo=4">© Marzen Media LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/95/10/a3/9510a3af-c536-b5ee-ef25-c754a47f7739/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/3090247/32850232-37cb0a16-c9f7-11e7-9014-78a2d05c4517.png)

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18855195/3e004c26-8451-11e6-9f1d-99af8db38d1f.png)
https://cloud.githubusercontent.com/assets/22012363/18855195/3e004c26-8451-11e6-9f1d-99af8db38d1f.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18855197/42aeeb38-8451-11e6-988a-fc6f12f54e51.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Fantasy News by FantasyPros
**Bundle ID:** com.fantasypros.news
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967102422">967102422</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasy-news-by-fantasypros/id967102422?mt=8&uo=4">https://itunes.apple.com/us/app/fantasy-news-by-fantasypros/id967102422?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Marzen Media LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marzen-media-llc/id892964104?uo=4">© Marzen Media LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/95/10/a3/9510a3af-c536-b5ee-ef25-c754a47f7739/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/3090247/32850232-37cb0a16-c9f7-11e7-9014-78a2d05c4517.png)
https://user-images.githubusercontent.com/3090247/32850232-37cb0a16-c9f7-11e7-9014-78a2d05c4517.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/32850233-381148be-c9f7-11e7-842f-192b2b3ed4d7.png
