### ISSUE TITLE
VPN Unlimited - Encrypted, Secure & Private Internet Connection for Anonymous Web Surfing

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#7613]
**App Name:** VPN Unlimited - Encrypted, Secure & Private Internet Connection for Anonymous Web Surfing
**Bundle ID:** com.simplexsolutionsinc.vpnguard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=694633015">694633015</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vpn-unlimited-encrypted-secure/id694633015?mt=8&uo=4">https://itunes.apple.com/us/app/vpn-unlimited-encrypted-secure/id694633015?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** KeepSolid Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/keepsolid-inc./id674978021?uo=4>© KeepSolid Inc.</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/26/72/f2/2672f2d3-6eee-b2e3-a2ac-c3b14183fb02/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268472/dc70b684-562a-11e6-86b0-62e6bbfeb948.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268472/dc70b684-562a-11e6-86b0-62e6bbfeb948.png)
https://cloud.githubusercontent.com/assets/2068130/17268472/dc70b684-562a-11e6-86b0-62e6bbfeb948.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268479/eaa7a6e0-562a-11e6-9df6-b6767f6adcd7.png
