### ISSUE TITLE
Contaqs - the Contact Manager

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#7614]
**App Name:** Contaqs - the Contact Manager
**Bundle ID:** de.entwicklungsschmiede.Contaqs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=584703364">584703364</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/contaqs-the-contact-manager/id584703364?mt=8&uo=4">https://itunes.apple.com/us/app/contaqs-the-contact-manager/id584703364?mt=8&uo=4</a>
**App Version:** 2.8.2
**Seller:** entwicklungsschmiede UG (haftungsbeschraenkt) & Co. KG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/entwicklungsschmiede-ug-co/id322660753?uo=4>© entwicklungsschmiede UG & Co KG</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/8b/ad/75/8bad75f7-7bbc-b03b-cd58-34081980cb69/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268545/9e1074bc-562d-11e6-97cc-3dd178cb26be.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268545/9e1074bc-562d-11e6-97cc-3dd178cb26be.png)
https://cloud.githubusercontent.com/assets/2068130/17268545/9e1074bc-562d-11e6-97cc-3dd178cb26be.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268548/b02b692c-562d-11e6-87ec-303646c07fda.png
