### ISSUE TITLE
freenet Mail

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#7615]
**App Name:** freenet Mail
**Bundle ID:** de.freenet.mail2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=796903132">796903132</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/freenet-mail/id796903132?uo=4">https://apps.apple.com/us/app/freenet-mail/id796903132?uo=4</a>
**App Version:** 3.5.4
**Seller:** freenet.de GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/freenet-de-gmbh/id367623899?uo=4">© freenet.de GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/08/65/89/086589e4-99ad-eea1-5781-622fa4e46e27/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400471-5ec52200-9b74-11e9-9d72-9dc58ecd667f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268678/ee1991d8-5631-11e6-8474-67b6e8b9a02d.png)
https://cloud.githubusercontent.com/assets/2068130/17268678/ee1991d8-5631-11e6-8474-67b6e8b9a02d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268681/fc1e3ed2-5631-11e6-9e51-28d482adfef9.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400471-5ec52200-9b74-11e9-9d72-9dc58ecd667f.png)
https://user-images.githubusercontent.com/20930745/60400471-5ec52200-9b74-11e9-9d72-9dc58ecd667f.png

Source:
https://user-images.githubusercontent.com/20930745/60400473-5ff64f00-9b74-11e9-9d42-dfeadaf54a20.png
