### ISSUE TITLE
Kaufland – Angebote und mehr

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#7616]
**App Name:** Kaufland – Angebote und mehr
**Bundle ID:** com.kaufland.iosapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1087780386">1087780386</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/kaufland-angebote-und-mehr/id1087780386?mt=8&uo=4">https://itunes.apple.com/de/app/kaufland-angebote-und-mehr/id1087780386?mt=8&uo=4</a>
**App Version:** 1.0.9
**Seller:** Kaufland Informationssysteme GmbH & Co. KG
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/kaufland-informationssysteme/id1070239293?uo=4>© Kaufland Informationssysteme GmbH & Co. KG</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/ee/b3/94/eeb394cf-9c41-6927-561f-1969cb751624/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268438/42a91154-562a-11e6-8702-80980d31ce7a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268438/42a91154-562a-11e6-8702-80980d31ce7a.png)
https://cloud.githubusercontent.com/assets/2068130/17268438/42a91154-562a-11e6-8702-80980d31ce7a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268439/50ced674-562a-11e6-8539-8410f31b4ab0.png
