### ISSUE TITLE
PegelAlarm Wasserstand-Überwachung

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#7617]
**App Name:** PegelAlarm Wasserstand-Überwachung
**Bundle ID:** at.sobos.ios-pegelalarm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1022182982">1022182982</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/pegelalarm-wasserstand-uberwachung/id1022182982?mt=8&uo=4">https://itunes.apple.com/de/app/pegelalarm-wasserstand-uberwachung/id1022182982?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Guenter Oeller
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/guenter-oeller/id1022171905?uo=4>© Guenter Oeller</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/a6/a8/d6/a6a8d6f2-bada-a09e-65d3-fedd460b87a4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18253429/e28aa35e-7394-11e6-8598-2124ada06485.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18253429/e28aa35e-7394-11e6-8598-2124ada06485.png)
https://cloud.githubusercontent.com/assets/20930745/18253429/e28aa35e-7394-11e6-8598-2124ada06485.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18253445/fcb49690-7394-11e6-9963-b7ac32fb3c8f.png
