### ISSUE TITLE
GSE SMART IPTV PRO

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#7618]
**App Name:** GSE SMART IPTV PRO
**Bundle ID:** com.gsetech.GSE-IPTV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1028734023">1028734023</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gse-smart-iptv-pro/id1028734023?mt=8&uo=4">https://itunes.apple.com/us/app/gse-smart-iptv-pro/id1028734023?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** GSE TECHNOLOGY LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/droidvision/id996274944?uo=4>© droidvision</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/58/31/39/58313977-548e-891b-4ed4-4f710fea933f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268168/3e414666-5622-11e6-9441-4015ed80b667.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268168/3e414666-5622-11e6-9441-4015ed80b667.png)
https://cloud.githubusercontent.com/assets/2068130/17268168/3e414666-5622-11e6-9441-4015ed80b667.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268171/4cfa4dce-5622-11e6-858c-c7ad14773119.png
