### ISSUE TITLE
YouTV - german TV library and television EPG

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#7619]
**App Name:** YouTV - german TV library and television EPG
**Bundle ID:** com.youtv.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1066864143">1066864143</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/youtv-german-tv-library-television/id1066864143?mt=8&uo=4">https://itunes.apple.com/us/app/youtv-german-tv-library-television/id1066864143?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** NETlantic Gesellschaft fr moderne Kommunikation mbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/netlantic-gmbh/id1065500511?uo=4>© NETlantic GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/ce/b9/60/ceb96098-f136-698b-fbd7-d2e42fd1f6cd/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268097/dc480006-561e-11e6-87c8-705440039576.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268097/dc480006-561e-11e6-87c8-705440039576.png)
https://cloud.githubusercontent.com/assets/2068130/17268097/dc480006-561e-11e6-87c8-705440039576.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268101/eb343ba2-561e-11e6-842c-885991ce4645.png
