### ISSUE TITLE
Concur - Travel, Receipts, Expense Reports

### ISSUE THREAD

**Issue by rentiak** [glasklart/hd#762]
**App Name:** Concur - Travel, Receipts, Expense Reports
**Bundle ID:** com.concur.concurmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335023774">335023774</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/concur-travel-receipts-expense/id335023774?mt=8&uo=4">https://itunes.apple.com/us/app/concur-travel-receipts-expense/id335023774?mt=8&uo=4</a>
**App Version:** 9.38.0
**Seller:** Concur
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/concur/id335023777?uo=4">© Concur</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/14/93/39/149339eb-56c1-b00f-a204-710e564c669a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19966301/6cf07532-a1cb-11e6-9c6e-164589601425.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19966301/6cf07532-a1cb-11e6-9c6e-164589601425.png)
https://cloud.githubusercontent.com/assets/20930745/19966301/6cf07532-a1cb-11e6-9c6e-164589601425.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19966314/81b62f84-a1cb-11e6-9c0a-db71260799fb.png
