### ISSUE TITLE
NINA

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#7620]
**App Name:** NINA
**Bundle ID:** de.materna.bbk.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=949360949">949360949</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nina/id949360949?mt=8&uo=4">https://itunes.apple.com/us/app/nina/id949360949?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Bundesamt fuer Bevoelkerungsschutz und Katastrophenhilfe
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bundesamt-fuer-bevoelkerungsschutz/id949360948?uo=4>© Bundesamt fuer Bevoelkerungsschutz und Katastrophenhilfe</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/4b/f3/64/4bf364dd-40e2-36e7-fe5b-6326a085cc82/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268392/b572fc46-5629-11e6-84e0-6e202a72fad7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268392/b572fc46-5629-11e6-84e0-6e202a72fad7.png)
https://cloud.githubusercontent.com/assets/2068130/17268392/b572fc46-5629-11e6-84e0-6e202a72fad7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268394/c5444c60-5629-11e6-8101-748de27e7873.png
