### ISSUE TITLE
Meine Pegel

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#7621]
**App Name:** Meine Pegel
**Bundle ID:** de.hochwasserzentralen.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1008115337">1008115337</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/meine-pegel/id1008115337?mt=8&uo=4">https://itunes.apple.com/de/app/meine-pegel/id1008115337?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Umweltministerium Baden-Württemberg
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/umweltministerium-baden-wurttemberg/id681272143?uo=4>© Umweltministerium Baden-Württemberg</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/98/22/4b/98224b5c-6047-8b37-310b-ec886f213a0f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272521/9079cfd6-5698-11e6-9d76-e978fe27373c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272521/9079cfd6-5698-11e6-9d76-e978fe27373c.png)
https://cloud.githubusercontent.com/assets/2068130/17272521/9079cfd6-5698-11e6-9d76-e978fe27373c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17272522/9ec722a0-5698-11e6-8305-8246c3661d86.png
