### ISSUE TITLE
Databox: Business Analytics

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#7623]
**App Name:** Databox: Business Analytics
**Bundle ID:** com.zepppelin.databoxenterprise
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=940584421">940584421</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/databox-business-analytics/id940584421?uo=4">https://apps.apple.com/us/app/databox-business-analytics/id940584421?uo=4</a>
**App Version:** 2.3.58
**Seller:** Databox, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/databox-inc/id637991025?uo=4">© Databox, Inc.</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/d3/01/8b/d3018b98-70d9-491b-1b40-c84220e203a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382261-ddc93600-9a60-11e9-96c0-5d78e2514f1f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268047/f1dec032-561c-11e6-9a67-bbeebf4861d4.png)
https://cloud.githubusercontent.com/assets/2068130/17268047/f1dec032-561c-11e6-9a67-bbeebf4861d4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268050/012da3d2-561d-11e6-8d7a-ed3d97a6cb60.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382162-9e4e1a00-9a5f-11e9-8f67-1080ca9250da.png)
https://user-images.githubusercontent.com/20930745/60382162-9e4e1a00-9a5f-11e9-8f67-1080ca9250da.png

Source:
![databox](https://user-images.githubusercontent.com/20930745/60382163-a017dd80-9a5f-11e9-977a-5af3769aef9d.png)

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382261-ddc93600-9a60-11e9-96c0-5d78e2514f1f.png)
https://user-images.githubusercontent.com/20930745/60382261-ddc93600-9a60-11e9-96c0-5d78e2514f1f.png

Source:
https://user-images.githubusercontent.com/20930745/60382262-df92f980-9a60-11e9-94e3-9b12b9974390.png
