### ISSUE TITLE
GoGogate2

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7624]
**App Name:** GoGogate2
**Bundle ID:** com.gogogate2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=964757967">964757967</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gogogate2/id964757967?mt=8&uo=4">https://itunes.apple.com/us/app/gogogate2/id964757967?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** Joan  Llopart Masana
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/v2fe/id525277631?uo=4>© V2FE</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple18/v4/5e/3a/79/5e3a7993-ff5f-695f-8dbd-36ee3c4514c2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268381/25957432-5629-11e6-9602-dc5701e712ed.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268381/25957432-5629-11e6-9602-dc5701e712ed.png)
https://cloud.githubusercontent.com/assets/2068130/17268381/25957432-5629-11e6-9602-dc5701e712ed.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268382/34a7da8c-5629-11e6-87df-22070aa3e6fb.png
