### ISSUE TITLE
PandaDoc - Electronic signing and document management

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7625]
**App Name:** PandaDoc - Electronic signing and document management
**Bundle ID:** com.pandadoc.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=882713690">882713690</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pandadoc-electronic-signing/id882713690?mt=8&uo=4">https://itunes.apple.com/us/app/pandadoc-electronic-signing/id882713690?mt=8&uo=4</a>
**App Version:** 2.2.5
**Seller:** Quote Roller Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/quote-roller-inc./id873627169?uo=4>© Quote Roller Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/23/f8/86/23f886fb-16d3-0fce-e91b-60373e60268d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17267992/bc24b1c4-561a-11e6-92b1-f0c569751ca0.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17267992/bc24b1c4-561a-11e6-92b1-f0c569751ca0.png)
https://cloud.githubusercontent.com/assets/2068130/17267992/bc24b1c4-561a-11e6-92b1-f0c569751ca0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17267994/d0083602-561a-11e6-9a5c-f3ac92e3c8f6.png
