### ISSUE TITLE
Tangerine Mobile Banking

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7626]
**App Name:** Tangerine Mobile Banking
**Bundle ID:** ca.tangerine.clients.banking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=847844097">847844097</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tangerine-mobile-banking/id847844097?mt=8&uo=4">https://itunes.apple.com/us/app/tangerine-mobile-banking/id847844097?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Tangerine Bank
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tangerine-bank-banque-tangerine/id847844100?uo=4>© Tangerine Bank / Banque Tangerine</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/95/13/03/95130393-4a23-f1c6-15e6-2aa517f51e4a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268011/9578994a-561b-11e6-86cd-744910ae01de.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268011/9578994a-561b-11e6-86cd-744910ae01de.png)
https://cloud.githubusercontent.com/assets/2068130/17268011/9578994a-561b-11e6-86cd-744910ae01de.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268013/a5bf4948-561b-11e6-96c5-ab274d4a4f2b.png
