### ISSUE TITLE
Dream mPOS

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7627]
**App Name:** Dream mPOS
**Bundle ID:** com.dreampayments.mPOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=928309489">928309489</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/dream-mpos/id928309489?mt=8&uo=4">https://itunes.apple.com/ca/app/dream-mpos/id928309489?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** Dream Payments Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/developer/dream-payments-corp./id928309488?uo=4>© Dream Payments Corp.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/c5/48/b4/c548b4e1-c6d8-510c-af7f-4f1d054c58e6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268263/10ebf072-5626-11e6-97b3-846cbc6c8f68.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268263/10ebf072-5626-11e6-97b3-846cbc6c8f68.png)
https://cloud.githubusercontent.com/assets/2068130/17268263/10ebf072-5626-11e6-97b3-846cbc6c8f68.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268267/1ee658a2-5626-11e6-8631-f6f59b0e0e27.png
