### ISSUE TITLE
Zipwhip Text Messaging

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7628]
**App Name:** Zipwhip Text Messaging
**Bundle ID:** com.zipwhip.messaging
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=665341624">665341624</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zipwhip-text-messaging/id665341624?mt=8&uo=4">https://itunes.apple.com/us/app/zipwhip-text-messaging/id665341624?mt=8&uo=4</a>
**App Version:** 2.21.3
**Seller:** Zipwhip
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zipwhip-inc./id546187600?uo=4>© Zipwhip, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/10/4b/7d/104b7d1e-2ea6-5b6b-8b0c-9a5e35037e3c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268338/c1ae561a-5627-11e6-9790-af6a6ccc02ba.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268338/c1ae561a-5627-11e6-9790-af6a6ccc02ba.png)
https://cloud.githubusercontent.com/assets/2068130/17268338/c1ae561a-5627-11e6-9790-af6a6ccc02ba.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268340/d0412e0a-5627-11e6-9203-3c4e41894450.png
