### ISSUE TITLE
ChocoFan by Chocolats Favoris! Enjoy the sweet taste of victory, one chocolate at a time!

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7629]
**App Name:** ChocoFan by Chocolats Favoris! Enjoy the sweet taste of victory, one chocolate at a time!
**Bundle ID:** com.chocolatsfavoris.fidelite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1120179425">1120179425</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/chocofan-by-chocolats-favoris!/id1120179425?mt=8&uo=4">https://itunes.apple.com/ca/app/chocofan-by-chocolats-favoris!/id1120179425?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Chocolats Favoris Inc, Les
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/developer/les-chocolats-favoris-inc./id1120179424?uo=4>© Les Chocolats Favoris inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/27/0c/d5/270cd55b-c4db-128c-f961-b5eec5a48dbe/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268278/a3997804-5626-11e6-8bc3-9121218c0529.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268278/a3997804-5626-11e6-8bc3-9121218c0529.png)
https://cloud.githubusercontent.com/assets/2068130/17268278/a3997804-5626-11e6-8bc3-9121218c0529.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268280/b22b1198-5626-11e6-8e50-13a4a132d659.png
