### ISSUE TITLE
Network Analyzer - ping, traceroute, whois, DNS, net speed, port & wifi scanner

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7630]
**App Name:** Network Analyzer - ping, traceroute, whois, DNS, net speed, port & wifi scanner
**Bundle ID:** net.techet.netanalyzer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=557405467">557405467</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/network-analyzer-ping-traceroute/id557405467?mt=8&uo=4">https://itunes.apple.com/us/app/network-analyzer-ping-traceroute/id557405467?mt=8&uo=4</a>
**App Version:** 7.0
**Seller:** Jiri Techet
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/techet/id401457168?uo=4>© Techet</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/ed/f5/a7/edf5a7ae-3634-9fea-1656-b15157fb9f02/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268659/5130eb8c-5631-11e6-97b2-268624bcefd6.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268659/5130eb8c-5631-11e6-97b2-268624bcefd6.png)
https://cloud.githubusercontent.com/assets/2068130/17268659/5130eb8c-5631-11e6-97b2-268624bcefd6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268661/5eca729a-5631-11e6-90a2-9ced6232a3da.png
