### ISSUE TITLE
Petro-Canada Mobile

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7631]
**App Name:** Petro-Canada Mobile
**Bundle ID:** com.petro-canada.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=792882134">792882134</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/petro-canada-mobile/id792882134?mt=8&uo=4">https://itunes.apple.com/us/app/petro-canada-mobile/id792882134?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Petro-Canada
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/petro-canada/id792882138?uo=4>© Petro-Canada</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/57/e1/2d/57e12dad-db81-208b-67cc-af179ea92de0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268359/5f948192-5628-11e6-925c-9dce5da5540e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268359/5f948192-5628-11e6-925c-9dce5da5540e.png)
https://cloud.githubusercontent.com/assets/2068130/17268359/5f948192-5628-11e6-925c-9dce5da5540e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268363/6f811714-5628-11e6-8a62-ecbbf1a95167.png
