### ISSUE TITLE
Philips Hue

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7632]
**App Name:** Philips Hue
**Bundle ID:** com.philips.lighting.hue2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1055281310">1055281310</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/philips-hue/id1055281310?mt=8&uo=4">https://itunes.apple.com/us/app/philips-hue/id1055281310?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** Philips Lighting B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/philips-lighting-bv/id979064009?uo=4>© Philips Lighting BV</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/10/93/c8/1093c8d3-e550-e0c5-bfbf-86b247a313f7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272257/eab281f2-5691-11e6-805a-d40cab728b38.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272257/eab281f2-5691-11e6-805a-d40cab728b38.png)
https://cloud.githubusercontent.com/assets/2068130/17272257/eab281f2-5691-11e6-805a-d40cab728b38.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17272260/f7d02d80-5691-11e6-86ba-32f9360b5f32.png
