### ISSUE TITLE
BlueJeans

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7633]
**App Name:** BlueJeans
**Bundle ID:** com.bluejeansnet.Blue-Jeans
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=560788314">560788314</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bluejeans/id560788314?mt=8&uo=4">https://itunes.apple.com/us/app/bluejeans/id560788314?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** Blue Jeans Network, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/blue-jeans-network/id560788317?uo=4>© Blue Jeans Network</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/95/26/ca/9526cae7-5873-199f-ec56-464fa160bbfb/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17267979/d3b9c0e6-5619-11e6-9dae-7c160c60f3e1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17267979/d3b9c0e6-5619-11e6-9dae-7c160c60f3e1.png)
https://cloud.githubusercontent.com/assets/2068130/17267979/d3b9c0e6-5619-11e6-9dae-7c160c60f3e1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17267980/e8013d18-5619-11e6-84a7-2fff3b533aa8.png
