### ISSUE TITLE
Flic App

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#7634]
**App Name:** Flic App
**Bundle ID:** com.shortcutlabs.flic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=977593793">977593793</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/flic-app/id977593793?uo=4">https://apps.apple.com/us/app/flic-app/id977593793?uo=4</a>
**App Version:** 3.3.7
**Seller:** Shortcut Labs AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shortcut-labs/id977593792?uo=4">© Shortcut Labs</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/c3/d0/91/c3d091c1-7261-b290-d6a4-f0b978cdd562/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393620-a027e400-9b18-11e9-9401-390858f55cba.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17267958/39f7d0f6-5619-11e6-9fdf-aa909fa37cc6.png)
https://cloud.githubusercontent.com/assets/2068130/17267958/39f7d0f6-5619-11e6-9fdf-aa909fa37cc6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17267962/4a637e22-5619-11e6-9dbd-ed914dc38d22.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393620-a027e400-9b18-11e9-9401-390858f55cba.png)
https://user-images.githubusercontent.com/20930745/60393620-a027e400-9b18-11e9-9401-390858f55cba.png

Source:
https://user-images.githubusercontent.com/20930745/60393622-a1591100-9b18-11e9-9cce-8d52736f0d2f.png
