### ISSUE TITLE
Disqus

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#7635]
**App Name:** Disqus
**Bundle ID:** com.disqus.Disqus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1006908426">1006908426</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/disqus/id1006908426?mt=8&uo=4">https://itunes.apple.com/us/app/disqus/id1006908426?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Disqus, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/disqus-inc./id1006908425?uo=4>© Disqus, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/5d/a2/b8/5da2b8ad-6f53-9e3f-e0e8-d09036e4efa6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17267867/684837dc-5616-11e6-91fd-66b7793b711a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17267867/684837dc-5616-11e6-91fd-66b7793b711a.png)
https://cloud.githubusercontent.com/assets/2068130/17267867/684837dc-5616-11e6-91fd-66b7793b711a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17267869/76d621f6-5616-11e6-9d2e-74663508a025.png
