### ISSUE TITLE
USA TODAY

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7636]
**App Name:** USA TODAY
**Bundle ID:** com.usatoday.iPhone20
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504631398">504631398</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/usa-today/id504631398?mt=8&uo=4">https://itunes.apple.com/us/app/usa-today/id504631398?mt=8&uo=4</a>
**App Version:** 4.3.0
**Seller:** USA TODAY
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/usa-today/id364257179?uo=4>© USA TODAY</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/d3/fd/80/d3fd80a2-0d27-58d0-21fb-000866818225/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272270/95c08f58-5692-11e6-9c08-85ca375b1947.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272270/95c08f58-5692-11e6-9c08-85ca375b1947.png)
https://cloud.githubusercontent.com/assets/2068130/17272270/95c08f58-5692-11e6-9c08-85ca375b1947.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17272272/a6a7ca8e-5692-11e6-8d09-856a337c82b5.png
