### ISSUE TITLE
Real Estate by Estately - Search Homes, Condos & Town Houses for Sale (MLS)

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7637]
**App Name:** Real Estate by Estately - Search Homes, Condos & Town Houses for Sale (MLS)
**Bundle ID:** com.estately.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=764642939">764642939</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/real-estate-by-estately-search/id764642939?mt=8&uo=4">https://itunes.apple.com/us/app/real-estate-by-estately-search/id764642939?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Estately Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/estately/id764642942?uo=4>© Estately</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/18/a3/e6/18a3e6cf-a5e8-e4d8-8309-9fae45e89f85/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272165/c3b4e740-568f-11e6-865e-e01aab5763ff.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272165/c3b4e740-568f-11e6-865e-e01aab5763ff.png)
https://cloud.githubusercontent.com/assets/2068130/17272165/c3b4e740-568f-11e6-865e-e01aab5763ff.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17272167/d3c7cbd4-568f-11e6-8440-8c584d63c6f8.png
