### ISSUE TITLE
Homesnap Real Estate & Rentals

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7638]
**App Name:** Homesnap Real Estate & Rentals
**Bundle ID:** Sawbuck.HomeSnap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506563991">506563991</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/homesnap-real-estate-rentals/id506563991?mt=8&uo=4">https://itunes.apple.com/us/app/homesnap-real-estate-rentals/id506563991?mt=8&uo=4</a>
**App Version:** 4.2.2
**Seller:** Sawbuck Realty, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sawbuck/id414314881?uo=4>© Sawbuck</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/35/85/87/35858716-a32a-608b-bc40-7352d050b003/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272149/51869330-568f-11e6-9174-39281cd23286.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272149/51869330-568f-11e6-9174-39281cd23286.png)
https://cloud.githubusercontent.com/assets/2068130/17272149/51869330-568f-11e6-9174-39281cd23286.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17272151/5fc3dd2c-568f-11e6-8226-96e194d3bb1a.png
