### ISSUE TITLE
Real Estate App by Redfin – Search Homes, Condos & Town Houses For Sale - Buy or Sell a Home

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7639]
**App Name:** Real Estate App by Redfin – Search Homes, Condos & Town Houses For Sale - Buy or Sell a Home
**Bundle ID:** com.redfin.redfin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327962480">327962480</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/real-estate-app-by-redfin/id327962480?mt=8&uo=4">https://itunes.apple.com/us/app/real-estate-app-by-redfin/id327962480?mt=8&uo=4</a>
**App Version:** 116.0.0.2005
**Seller:** Redfin Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/redfin/id327962483?uo=4>© Redfin</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/6b/25/b1/6b25b107-6f69-4c3a-2676-4e8856afc48d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272124/df4ead66-568e-11e6-99b5-b03e8cd11bc2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272124/df4ead66-568e-11e6-99b5-b03e8cd11bc2.png)
https://cloud.githubusercontent.com/assets/2068130/17272124/df4ead66-568e-11e6-99b5-b03e8cd11bc2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17272126/ee37c358-568e-11e6-8480-bca4f065e36a.png
