### ISSUE TITLE
Mr Mood

### ISSUE THREAD

**Issue by alderz** [glasklart/hd#764]
**App Name:** Mr Mood
**Bundle ID:** com.nuagetouch.moodoscope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=557107386">557107386</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mr-mood/id557107386?mt=8&uo=4">https://itunes.apple.com/us/app/mr-mood/id557107386?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** 1Button SARL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/1button-sarl/id388888785?uo=4>© 1Button SARL</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple4/v4/ee/5e/64/ee5e64d6-3c87-b5e7-7f0d-c00ea0f41c1d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617968/c112b68e-983e-11e6-992b-675334b06adc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617968/c112b68e-983e-11e6-992b-675334b06adc.png)
https://cloud.githubusercontent.com/assets/20930745/19617968/c112b68e-983e-11e6-992b-675334b06adc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617970/d65346d0-983e-11e6-8d3d-51b19069dee3.png
