### ISSUE TITLE
Homes.com Homes for Sale, Rent & Home Values - Search Real Estate

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7640]
**App Name:** Homes.com Homes for Sale, Rent & Home Values - Search Real Estate
**Bundle ID:** com.homes.com.homes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306423353">306423353</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/homes.com-homes-for-sale-rent/id306423353?mt=8&uo=4">https://itunes.apple.com/us/app/homes.com-homes-for-sale-rent/id306423353?mt=8&uo=4</a>
**App Version:** 8.8.0
**Seller:** Homes.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/homes.com/id306423356?uo=4>© Homes.com</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/07/05/b0/0705b0c0-499b-b0a0-7749-c54b363a6864/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272103/1213d2cc-568e-11e6-9f60-1698f7837df3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272103/1213d2cc-568e-11e6-9f60-1698f7837df3.png)
https://cloud.githubusercontent.com/assets/2068130/17272103/1213d2cc-568e-11e6-9f60-1698f7837df3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17272105/21a1c24e-568e-11e6-9055-354bde6f64f3.png
