### ISSUE TITLE
BrightNest – Home Organization, Cleaning Schedule, DIY Crafts, Home Tips and Home Maintenance

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7641]
**App Name:** BrightNest – Home Organization, Cleaning Schedule, DIY Crafts, Home Tips and Home Maintenance
**Bundle ID:** com.brightnest.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=609754293">609754293</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/brightnest-home-organization/id609754293?mt=8&uo=4">https://itunes.apple.com/us/app/brightnest-home-organization/id609754293?mt=8&uo=4</a>
**App Version:** 1.2.8
**Seller:** SmartHabitat Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/brightnest/id609754296?uo=4>© BrightNest</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/43/c0/88/43c088ea-9c6c-a1d6-12c1-b21aa13aaf61/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272195/80884416-5690-11e6-866b-096188e62502.png)

**Comment by dreamnet** [comment]
I think it looks better without the line at the bottom.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272195/80884416-5690-11e6-866b-096188e62502.png)
https://cloud.githubusercontent.com/assets/2068130/17272195/80884416-5690-11e6-866b-096188e62502.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17272200/8f8fd730-5690-11e6-9a9f-a8f70d6bc7d5.png
