### ISSUE TITLE
nextPDF Pro - Premium PDF Reader, Annotator & Form-Filler

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7642]
**App Name:** nextPDF Pro - Premium PDF Reader, Annotator & Form-Filler
**Bundle ID:** com.nt.nitrospdfpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=981014613">981014613</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nextpdf-pro-premium-pdf-reader/id981014613?mt=8&uo=4">https://itunes.apple.com/us/app/nextpdf-pro-premium-pdf-reader/id981014613?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Truong Nguyen Ngoc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/truong-nguyen-ngoc/id419336556?uo=4>© Truong Nguyen Ngoc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/07/e7/ca/07e7cadd-a153-0692-764c-68817096b078/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272080/7fb004be-568d-11e6-9abc-47096fda2bac.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17272080/7fb004be-568d-11e6-9abc-47096fda2bac.png)
https://cloud.githubusercontent.com/assets/2068130/17272080/7fb004be-568d-11e6-9abc-47096fda2bac.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17272083/91ac6e78-568d-11e6-8b5d-d52079285282.png
