### ISSUE TITLE
Heroes Reborn: Enigma

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7643]
**App Name:** Heroes Reborn: Enigma
**Bundle ID:** com.Phosphor.Traveler
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923032178">923032178</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/heroes-reborn-enigma/id923032178?mt=8&uo=4">https://itunes.apple.com/us/app/heroes-reborn-enigma/id923032178?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Phosphor Games, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/phosphor-games-studio-llc/id452823335?uo=4">© Phosphor Games Studio, LLC</a>
**Supported Devices:** iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/38/9d/3a/389d3a52-e0ce-62e0-bb7a-73e1b5146b5b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21562759/b4287c42-ce7b-11e6-822a-276c14bbe6d8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21562759/b4287c42-ce7b-11e6-822a-276c14bbe6d8.png)
https://cloud.githubusercontent.com/assets/2068130/21562759/b4287c42-ce7b-11e6-822a-276c14bbe6d8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21562769/c4f7014c-ce7b-11e6-9a71-469ad2b24d2e.png
Can't think of any other way to do this icon....
