### ISSUE TITLE
Warhammer 40,000: Freeblade

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7645]
**App Name:** Warhammer 40,000: Freeblade
**Bundle ID:** com.PixelToys.W40kFreeblade
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1043640363">1043640363</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/warhammer-40-000-freeblade/id1043640363?mt=8&uo=4">https://itunes.apple.com/us/app/warhammer-40-000-freeblade/id1043640363?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** Pixel Toys Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pixel-toys/id692788184?uo=4">© Pixel Toys</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/b5/48/44/b548447d-14bf-9b36-f4d1-300e2d6c7f16/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23317699/cb4cd79e-facf-11e6-8023-8fd2c365bb23.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23317699/cb4cd79e-facf-11e6-8023-8fd2c365bb23.png)
https://cloud.githubusercontent.com/assets/2068130/23317699/cb4cd79e-facf-11e6-8023-8fd2c365bb23.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23317710/d9665bb6-facf-11e6-8583-eefb3f9520c5.png
