### ISSUE TITLE
KIMOJI

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7647]
**App Name:** KIMOJI
**Bundle ID:** com.whalerock.Snaps-Kimoji-Keyboard-Dev
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1068019093">1068019093</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kimoji/id1068019093?mt=8&uo=4">https://itunes.apple.com/us/app/kimoji/id1068019093?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Whalerock Digital Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/whalerock-digital-media-llc/id547516007?uo=4>© Whalerock Digital Media, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/41/93/96/419396e1-f82d-8d68-a7cf-d37917fdc2ff/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19171661/32c1bb7c-8c1e-11e6-8854-3fd94bdd56ea.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19012363/5da91458-87b3-11e6-929a-d3f4689f48fc.png)
https://cloud.githubusercontent.com/assets/20930745/19012363/5da91458-87b3-11e6-929a-d3f4689f48fc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19012365/7b7872f8-87b3-11e6-95ea-c30fa03ba5b9.png

**Comment by dreamnet** [comment]
Made the same way as #8198.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19171661/32c1bb7c-8c1e-11e6-8854-3fd94bdd56ea.png)
https://cloud.githubusercontent.com/assets/2068130/19171661/32c1bb7c-8c1e-11e6-8854-3fd94bdd56ea.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19171676/49c2dc7a-8c1e-11e6-8376-b8db28b0136b.png

**Comment by 2Qt2beStr8** [comment]
... wow .,.. really amazing ...
