### ISSUE TITLE
Block Ad for Free by NeverAds | The Best Ad Blocker Extension for Safari, Fast Browsing

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7648]
**App Name:** Block Ad for Free by NeverAds | The Best Ad Blocker Extension for Safari, Fast Browsing
**Bundle ID:** com.betternet.contentblocker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1041969188">1041969188</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/block-ad-for-free-by-neverads/id1041969188?mt=8&uo=4">https://itunes.apple.com/us/app/block-ad-for-free-by-neverads/id1041969188?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Betternet Technologies Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/betternet-technologies-inc./id975476381?uo=4>© Betternet Technologies Inc.</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/3f/8d/2a/3f8d2a57-d9a9-686d-f791-fcfc18069835/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17636893/7ff09bac-60e0-11e6-9012-b93178e198da.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17636893/7ff09bac-60e0-11e6-9012-b93178e198da.png)
https://cloud.githubusercontent.com/assets/2068130/17636893/7ff09bac-60e0-11e6-9012-b93178e198da.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17636909/8eaeb73c-60e0-11e6-9e96-415827925b1f.png
