### ISSUE TITLE
Soul Hunters - Ezio from Assassin's Creed joins the battle

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7649]
**App Name:** Soul Hunters - Ezio from Assassin's Creed joins the battle
**Bundle ID:** us.kick9.k3000000013c3201000001
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=982119760">982119760</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/soul-hunters-ezio-from-assassins/id982119760?mt=8&uo=4">https://itunes.apple.com/us/app/soul-hunters-ezio-from-assassins/id982119760?mt=8&uo=4</a>
**App Version:** 2.4.28
**Seller:** LilithGame Co., Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lilith-games/id982119759?uo=4>© Lilith Games</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/cd/3e/91/cd3e91fa-63cd-5782-3166-7631828c1a4b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17836135/1e7e41fe-6788-11e6-8770-864e850c47eb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17836135/1e7e41fe-6788-11e6-8770-864e850c47eb.png)
https://cloud.githubusercontent.com/assets/2068130/17836135/1e7e41fe-6788-11e6-8770-864e850c47eb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17836140/2dc8f1a4-6788-11e6-94cd-6ecab534c30d.png
