### ISSUE TITLE
Chorma for Chores

### ISSUE THREAD

**Issue by alderz** [glasklart/hd#765]
**App Name:** Chorma for Chores
**Bundle ID:** com.pebbl.Chorma
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=590954566">590954566</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chorma-for-chores/id590954566?mt=8&uo=4">https://itunes.apple.com/us/app/chorma-for-chores/id590954566?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** Stephen Bennett
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stephen-bennett/id590954749?uo=4>© Stephen Bennett</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/55/65/5c/55655c00-98b2-2370-6850-0a6c02ca0176/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618026/db1a7192-983f-11e6-90fc-3b96eecefddb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19618026/db1a7192-983f-11e6-90fc-3b96eecefddb.png)
https://cloud.githubusercontent.com/assets/20930745/19618026/db1a7192-983f-11e6-90fc-3b96eecefddb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19618044/f5b95568-983f-11e6-9485-ea3af2990292.png
