### ISSUE TITLE
Transformers: Earth Wars

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7650]
**App Name:** Transformers: Earth Wars
**Bundle ID:** com.backflipstudios.transformersearthwars
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1058526204">1058526204</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/transformers-earth-wars/id1058526204?mt=8&uo=4">https://itunes.apple.com/us/app/transformers-earth-wars/id1058526204?mt=8&uo=4</a>
**App Version:** 1.27.1
**Seller:** Backflip Studios
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/backflip-studios/id315282170?uo=4>© Backflip Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple18/v4/26/50/9b/26509b96-aa8d-b70e-000a-8d82eece9142/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19048334/34f94146-89a6-11e6-9301-bc764b9e88e1.png)

**Comment by 2Qt2beStr8** [comment]
... after two hours i give up ... i can't do this icon :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19044105/255f6034-8993-11e6-9ecc-102a42ddd8c7.png)
https://cloud.githubusercontent.com/assets/20930745/19044105/255f6034-8993-11e6-9ecc-102a42ddd8c7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19044116/3258b830-8993-11e6-9ee0-6d493bc5e035.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 I think it's OK. 👍
