### ISSUE TITLE
Microsoft Flow

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7651]
**App Name:** Microsoft Flow
**Bundle ID:** com.microsoft.procsimo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1094928825">1094928825</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-flow/id1094928825?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-flow/id1094928825?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/9b/e4/f4/9be4f4f7-7c0e-9d74-a563-1adbac7b2bfc/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17282668/d8c06324-576d-11e6-85ef-bcf8cb2cbae3.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17282668/d8c06324-576d-11e6-85ef-bcf8cb2cbae3.png)
https://cloud.githubusercontent.com/assets/3090247/17282668/d8c06324-576d-11e6-85ef-bcf8cb2cbae3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17282669/d8c5c800-576d-11e6-9ff7-1b586d58d48e.png
