### ISSUE TITLE
Foresee: Your Personal Activity Forecast

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7652]
**App Name:** Foresee: Your Personal Activity Forecast
**Bundle ID:** com.borderleap.foresee2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=934906611">934906611</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/foresee-your-personal-activity/id934906611?mt=8&uo=4">https://itunes.apple.com/us/app/foresee-your-personal-activity/id934906611?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** BorderLeap, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/borderleap-llc/id546937507?uo=4>© BorderLeap, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/53/90/b0/5390b009-a494-985c-48a1-24001d5c8f64/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17459887/b2468a04-5c4d-11e6-88b8-b0393a61de0b.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17459887/b2468a04-5c4d-11e6-88b8-b0393a61de0b.png)
https://cloud.githubusercontent.com/assets/10730122/17459887/b2468a04-5c4d-11e6-88b8-b0393a61de0b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17459888/b249a838-5c4d-11e6-844b-4aeb8276fc2b.png
