### ISSUE TITLE
18Birdies: Golf GPS, Scorecard & Stats

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7653]
**App Name:** 18Birdies: Golf GPS, Scorecard & Stats
**Bundle ID:** com.osmgolf.18Birdies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=892700751">892700751</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/18birdies-golf-gps-scorecard/id892700751?mt=8&uo=4">https://itunes.apple.com/us/app/18birdies-golf-gps-scorecard/id892700751?mt=8&uo=4</a>
**App Version:** 3.8.0
**Seller:** 18Birdies LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/18birdies-llc/id955324369?uo=4>© 18Birdies LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple18/v4/4b/da/d7/4bdad7a1-aa5b-d379-43f5-977a228acba5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17545864/6bf557e4-5edf-11e6-975e-f37aa5c3cda0.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17459880/1a8c5a90-5c4d-11e6-916e-2bf3f65a830f.png)
https://cloud.githubusercontent.com/assets/10730122/17459880/1a8c5a90-5c4d-11e6-916e-2bf3f65a830f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17459881/1a8d9c02-5c4d-11e6-9ac5-c5de215c9b2d.png

**Comment by ivanov007** [comment]
looks very nice, but can you invert the colors just to see how it looks?

**Comment by dreamnet** [comment]
Simply inverted:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17545864/6bf557e4-5edf-11e6-975e-f37aa5c3cda0.png)
https://cloud.githubusercontent.com/assets/2068130/17545864/6bf557e4-5edf-11e6-975e-f37aa5c3cda0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17545873/87d37be4-5edf-11e6-92c8-419a938e23ee.png

**Comment by Trubbel** [comment]
@ivanov007 @dreamnet Yeah it looks way better like that!
