### ISSUE TITLE
Comma - read your email newsletters in peace

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7654]
**App Name:** Comma - read your email newsletters in peace
**Bundle ID:** com.Startup.NewslettersAPP
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1044945181">1044945181</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/comma-read-your-email-newsletters/id1044945181?mt=8&uo=4">https://itunes.apple.com/us/app/comma-read-your-email-newsletters/id1044945181?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Pink Elephant Labs LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pink-elephant-labs-llc/id1085190481?uo=4>© Pink Elephant Labs LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/3b/9d/62/3b9d62f2-3996-2042-e845-c3f3302a80df/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17547442/8efdb5b2-5ee7-11e6-9389-fdea87cf5064.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17547442/8efdb5b2-5ee7-11e6-9389-fdea87cf5064.png)
https://cloud.githubusercontent.com/assets/2068130/17547442/8efdb5b2-5ee7-11e6-9389-fdea87cf5064.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17547460/9d8a0310-5ee7-11e6-93a4-1127e703ec78.png
