### ISSUE TITLE
Rush - More than Mail

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7655]
**App Name:** Rush - More than Mail
**Bundle ID:** com.rushapp.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1093107576">1093107576</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rush-more-than-mail/id1093107576?mt=8&uo=4">https://itunes.apple.com/us/app/rush-more-than-mail/id1093107576?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** Wish Wood Holdings Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wish-wood-holdings-limited/id1013694145?uo=4>© Wish Wood Holdings Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/ce/96/0d/ce960d8f-0a75-6f52-2319-805ece422cf6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17833721/ecee012c-6725-11e6-98b0-1def4d3d1e44.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17833721/ecee012c-6725-11e6-98b0-1def4d3d1e44.png)
https://cloud.githubusercontent.com/assets/2068130/17833721/ecee012c-6725-11e6-98b0-1def4d3d1e44.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17833724/fc9dfe4c-6725-11e6-8aeb-21cf1a40f554.png
