### ISSUE TITLE
Morning Mail

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7656]
**App Name:** Morning Mail
**Bundle ID:** com.morningmail.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=975347004">975347004</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/morning-mail/id975347004?mt=8&uo=4">https://itunes.apple.com/us/app/morning-mail/id975347004?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Andrey Usoltsev
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/andrey-usoltsev/id972799843?uo=4>© Andrey Usoltsev</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/41/c5/34/41c534ed-f1f5-64bc-4518-b771e62fa31a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17287292/0cc13fe8-57cf-11e6-89bc-81fdb79eed04.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17287292/0cc13fe8-57cf-11e6-89bc-81fdb79eed04.png)
https://cloud.githubusercontent.com/assets/2068130/17287292/0cc13fe8-57cf-11e6-89bc-81fdb79eed04.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17287305/1c5c134c-57cf-11e6-97ea-1b0961ba1ef4.png
