### ISSUE TITLE
iPad mini 4 9.3.3 clock & calendar color issue

### ISSUE THREAD

**Issue by 96gator** [glasklart/hd#7657]
Good day fellow Glasklarters!
I have just JB'd with Pangu, and I am having a few issues with my iPad mini 4.
My iPhone SE is working great with Anemone, but the iPad with the same theme is not theming the calendar color (no biggie really), and the clock is not right despite many tricks i have tried in the past.
On another note, I can't get Pangu app to theme, as well is HIP4U, and associated apps from them.

Any help would be mega!!!
Thank you all!

![img_9173](https://cloud.githubusercontent.com/assets/9626791/17282466/0f88f474-5774-11e6-981f-cd36bee78f55.jpg)

**Comment by dreamnet** [comment]
@96gator Glasklart is NOT compatible with iPad. I am also just having an iPad Pro here, with is not Jailbreaked, so I can't help you much.

**Comment by dreamnet** [comment]
Hurray, got it running on my (now jailbroken) iPad Pro after changing some graphics and overwoking the Info.plist's.
![img_0019](https://cloud.githubusercontent.com/assets/2068130/17306070/4af79dde-582e-11e6-9096-0007eb5c0221.PNG)
...but I don't think this will run on iPad mini without some changes.

**Comment by 96gator** [comment]
i got the clock to theme by using my iPhone theme that was working properly. 
Do you have the info list you used to help,with my calendar, and maybe even post your entire theme for Downloading.... 🙏
![image](https://cloud.githubusercontent.com/assets/9626791/17306858/2e810b82-5800-11e6-8563-ea4b6d864c9d.png)

Also, still can't get pangu or HiP4U to theme, any thoughts? 
Thank you so much.

**Comment by ivanov007** [comment]
pangu for 9.3 ave not yet submitted for theme, and even if it were submitted there's have not being a release since the new jailbreak came out

**Comment by dreamnet** [comment]
@96gator No chance to get the Calendar themed without Anemone. The `Info.plist` is [here](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/Info.plist).
I used the chinese version to jailbreak, so I don't have Pangu #4683 or HiP4U on my device, just two apps with chinese characters, that I can't read. I think one of them is PPHelper (BundleID `com.teiron.pphelperns`).
