### ISSUE TITLE
POP! Slots - Play Real Las Vegas Casino Games with Friends for Free!

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7658]
**App Name:** POP! Slots - Play Real Las Vegas Casino Games with Friends for Free!
**Bundle ID:** com.playstudios.popslots
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1065980436">1065980436</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pop!-slots-play-real-las-vegas/id1065980436?mt=8&uo=4">https://itunes.apple.com/us/app/pop!-slots-play-real-las-vegas/id1065980436?mt=8&uo=4</a>
**App Version:** 2.28.0
**Seller:** Playstudios, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/playstudios/id624795774?uo=4">© PlayStudios</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/86/1a/be/861abe5d-46f2-d87e-011e-4016bebc3731/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20641227/d7e92796-b3f3-11e6-9bea-3ec5055b8306.png)

**Comment by boxermansr** [comment]
Anyone? :) Guess I need to stop being lazy and figure out how to do these myself, so I can contribute :)

**Comment by dreamnet** [comment]
@boxermansr Jep, that would ne nice... :wink:

**Comment by boxermansr** [comment]
😭

**Comment by 2Qt2beStr8** [comment]
@boxermansr ... maybe you want use this icon until someone makes the original one

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19132023/0f718336-8b52-11e6-9426-8d6732bd078d.png)
https://cloud.githubusercontent.com/assets/20930745/19132023/0f718336-8b52-11e6-9426-8d6732bd078d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19132063/3807dc00-8b52-11e6-843d-04bb132d40ac.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20641227/d7e92796-b3f3-11e6-9bea-3ec5055b8306.png)
https://cloud.githubusercontent.com/assets/2068130/20641227/d7e92796-b3f3-11e6-9bea-3ec5055b8306.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20641230/e981fca8-b3f3-11e6-910c-2d1e3b62a034.png
