### ISSUE TITLE
IS Supersää

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7659]
**App Name:** IS Supersää
**Bundle ID:** fi.iltasanomat.saa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=657765123">657765123</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/is-supersaa/id657765123?mt=8&uo=4">https://itunes.apple.com/us/app/is-supersaa/id657765123?mt=8&uo=4</a>
**App Version:** 2.3.4
**Seller:** Sanoma Media Finland
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sanoma-media-finland/id368549040?uo=4>© Sanoma Media Finland</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/7b/62/bb/7b62bbc7-7e43-7eae-e147-f062f6eae871/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17459863/32984bae-5c4c-11e6-82d4-ea41fb44affc.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17459863/32984bae-5c4c-11e6-82d4-ea41fb44affc.png)
https://cloud.githubusercontent.com/assets/10730122/17459863/32984bae-5c4c-11e6-82d4-ea41fb44affc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17459862/3280f580-5c4c-11e6-8034-44dbc3683af2.png
