### ISSUE TITLE
Parkmobile - Parking made easy with mobile app

### ISSUE THREAD

**Issue by rentiak** [glasklart/hd#766]
**App Name:** Parkmobile - Parking made easy with mobile app
**Bundle ID:** us.parkmobile.ParkMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=365399299">365399299</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parkmobile-parking-made-easy/id365399299?mt=8&uo=4">https://itunes.apple.com/us/app/parkmobile-parking-made-easy/id365399299?mt=8&uo=4</a>
**App Version:** 4.5.4
**Seller:** Parkmobile USA, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/parkmobile-usa-inc./id365399302?uo=4>© Parkmobile USA, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/1a/32/83/1a3283f4-ed43-32e8-79ee-f846b342d931/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617918/ce2604f8-983d-11e6-8a38-0d56d6d176ce.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617918/ce2604f8-983d-11e6-8a38-0d56d6d176ce.png)
https://cloud.githubusercontent.com/assets/20930745/19617918/ce2604f8-983d-11e6-8a38-0d56d6d176ce.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617926/ec430594-983d-11e6-8ce1-3b12e25ba325.png
