### ISSUE TITLE
GameFly

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7664]
**App Name:** GameFly
**Bundle ID:** com.gamefly.gamecenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335503017">335503017</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gamefly/id335503017?mt=8&uo=4">https://itunes.apple.com/us/app/gamefly/id335503017?mt=8&uo=4</a>
**App Version:** 3.40
**Seller:** GameFly
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gamefly/id335503020?uo=4>© GameFly</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/42/61/94/426194fe-552a-ef73-d0cc-153b31e8e8d1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17546973/eba53ab8-5ee4-11e6-9e8f-853e52e39a7b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17546973/eba53ab8-5ee4-11e6-9e8f-853e52e39a7b.png)
https://cloud.githubusercontent.com/assets/2068130/17546973/eba53ab8-5ee4-11e6-9e8f-853e52e39a7b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17546984/fc0c5a8a-5ee4-11e6-940e-a75dd9592dd5.png
