### ISSUE TITLE
Orderly - To-do Lists, Location Based Reminders

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7665]
**App Name:** Orderly - To-do Lists, Location Based Reminders
**Bundle ID:** com.tektontek.orderly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506632088">506632088</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/orderly-to-do-lists-location/id506632088?mt=8&uo=4">https://itunes.apple.com/us/app/orderly-to-do-lists-location/id506632088?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Tekton Technologies (P) Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tekton-technologies-p-ltd./id343534621?uo=4">© Tekton Technologies (P) Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/02/ee/15/02ee150c-6bd1-25d4-b652-f66f36119a6e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22625552/629f275e-eb9a-11e6-8f27-4b70286d32a8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17637582/c4509064-60e4-11e6-88a1-23fe83d91c15.png)
https://cloud.githubusercontent.com/assets/2068130/17637582/c4509064-60e4-11e6-88a1-23fe83d91c15.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17637586/d301c86c-60e4-11e6-9a12-afa48e3ac1aa.png

**Comment by l8er4now** [comment]
needs an update

**App Name:** Orderly - To-do Lists, Location Based Reminders
**Bundle ID:** com.tektontek.orderly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506632088">506632088</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/orderly-to-do-lists-location/id506632088?mt=8&uo=4">https://itunes.apple.com/us/app/orderly-to-do-lists-location/id506632088?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Tekton Technologies (P) Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tekton-technologies-p-ltd./id343534621?uo=4">© Tekton Technologies (P) Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/02/ee/15/02ee150c-6bd1-25d4-b652-f66f36119a6e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22625552/629f275e-eb9a-11e6-8f27-4b70286d32a8.png)
https://cloud.githubusercontent.com/assets/20930745/22625552/629f275e-eb9a-11e6-8f27-4b70286d32a8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22625557/6eef4bec-eb9a-11e6-9ae4-fa8436267d68.png
