### ISSUE TITLE
FeedNews: AI curated social news for productivity

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7667]
**App Name:** FeedNews: AI curated social news for productivity
**Bundle ID:** com.opera.iNews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1128377569">1128377569</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/feednews-ai-curated-social/id1128377569?mt=8&uo=4">https://itunes.apple.com/us/app/feednews-ai-curated-social/id1128377569?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Opera Software ASA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/opera-software-asa/id363729563?uo=4>© Opera Software ASA</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/55/51/fa/5551faf0-54fe-8e4b-8d10-3cb8013bf278/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17545588/3439703e-5ede-11e6-8027-e2df9fad7853.png)

**Comment by Trubbel** [comment]
I don't know about this one..

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17466374/4250d962-5d0f-11e6-9670-33d21487cdf8.png)
https://cloud.githubusercontent.com/assets/10730122/17466374/4250d962-5d0f-11e6-9670-33d21487cdf8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17466375/4250d796-5d0f-11e6-946b-69376b06ad14.png

**Comment by ivanov007** [comment]
@Trubbel can you invert it?

**Comment by dreamnet** [comment]
What about doing just the ***F*** ?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17545588/3439703e-5ede-11e6-8027-e2df9fad7853.png)
https://cloud.githubusercontent.com/assets/2068130/17545588/3439703e-5ede-11e6-8027-e2df9fad7853.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17545598/432898ae-5ede-11e6-8d67-f6d1f51b0c2c.png

**Comment by Trubbel** [comment]
I like just the ***F***.
