### ISSUE TITLE
Chick-fil-A

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7668]
**App Name:** Chick-fil-A
**Bundle ID:** com.engauge.Chick-fil-A
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=488818252">488818252</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/chick-fil-a/id488818252?uo=4">https://apps.apple.com/us/app/chick-fil-a/id488818252?uo=4</a>
**App Version:** 6.1.10
**Seller:** Chick-fil-A, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/chick-fil-a-inc/id529598543?uo=4">© Chick-fil-A, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/2f/6f/07/2f6f0796-9c82-04ba-4ece-57b177b53774/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380197-b31bb500-9a41-11e9-956d-1521424c3ff2.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17458575/78b836d0-5c15-11e6-85f2-41c216b1562e.png)
https://cloud.githubusercontent.com/assets/10730122/17458575/78b836d0-5c15-11e6-85f2-41c216b1562e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17458574/78a047b4-5c15-11e6-9718-00e283f1535e.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380197-b31bb500-9a41-11e9-956d-1521424c3ff2.png)
https://user-images.githubusercontent.com/20930745/60380197-b31bb500-9a41-11e9-956d-1521424c3ff2.png

Source:
https://user-images.githubusercontent.com/20930745/60380198-b4e57880-9a41-11e9-911d-2c9cb59117b8.png
