### ISSUE TITLE
Socioball

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7669]
**App Name:** Socioball
**Bundle ID:** com.yellowmonkeystudios.socioball
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=928965297">928965297</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/socioball/id928965297?mt=8&uo=4">https://itunes.apple.com/us/app/socioball/id928965297?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Yellow  Monkey Studios Pvt. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yellow-monkey-studios-pvt./id376818871?uo=4>© Yellow Monkey Studios Pvt. Ltd.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple71/v4/f7/81/28/f78128fc-9475-95fa-0bd0-6d5ceeaea881/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18234836/d915006e-7310-11e6-887a-273915cb402a.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17465600/eb0b87aa-5cfb-11e6-8039-19322281b49d.png)
https://cloud.githubusercontent.com/assets/10730122/17465600/eb0b87aa-5cfb-11e6-8039-19322281b49d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17465601/eb0cbe04-5cfb-11e6-9008-c58184746e25.png

**Comment by Anuskuss** [comment]
@Trubbel Can you make a solid ring under the ball (and remove the cross)?

**Comment by Anuskuss** [comment]
@Trubbel How do you like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18234836/d915006e-7310-11e6-887a-273915cb402a.png)
https://cloud.githubusercontent.com/assets/7157389/18234836/d915006e-7310-11e6-887a-273915cb402a.png

___

Source:
https://cloud.githubusercontent.com/assets/7157389/18234840/e5917f52-7310-11e6-9e13-db338e9a5722.png

**Comment by Trubbel** [comment]
@Anuskuss @dreamnet Up to you guys, I don't mind it. :smile:

**Comment by dreamnet** [comment]
@Trubbel OK, I take the one from @Anuskuss.
