### ISSUE TITLE
Amazon Music

### ISSUE THREAD

**Issue by rentiak** [glasklart/hd#767]
**App Name:** Amazon Music
**Bundle ID:** com.amazon.mp3.AmazonCloudPlayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=510855668">510855668</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amazon-music/id510855668?mt=8&uo=4">https://itunes.apple.com/us/app/amazon-music/id510855668?mt=8&uo=4</a>
**App Version:** 7.5.2
**Seller:** AMZN Mobile LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amzn-mobile-llc/id297606954?uo=4">© AMZN Mobile LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/16/0c/a1/160ca1fa-a46d-2baa-afb2-6049fdec3459/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38288393-d367111c-37d0-11e8-932d-141b216a1169.png)

**Comment by Trubbel** [comment]
Icon has been updated.

**Comment by ivanov007** [comment]
here's the old icon, I thin it's @rentiak's work
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8418941/ef5551fc-1e7b-11e5-9f3b-76d0e0c750eb.png)

**Comment by dreamnet** [comment]
Here is the actual icon from the master - needs an update,
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8419532/bd446da8-1eba-11e5-9fd7-70cab78fac11.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8495734/1a2fe33c-2170-11e5-8642-8e551f5fb000.png)
https://cloud.githubusercontent.com/assets/2068130/8495734/1a2fe33c-2170-11e5-8642-8e551f5fb000.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8495741/27a968bc-2170-11e5-8eb3-13d91762ebeb.png

**Comment by Christian9901** [comment]
update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38288393-d367111c-37d0-11e8-932d-141b216a1169.png)
https://user-images.githubusercontent.com/2068130/38288393-d367111c-37d0-11e8-932d-141b216a1169.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38288400-e39e1062-37d0-11e8-8a0d-a5ac53a4e3be.png
