### ISSUE TITLE
Raiffeisen ELBA

### ISSUE THREAD

**Issue by Konsti9012** [glasklart/hd#7670]
**App Name:** Raiffeisen ELBA
**Bundle ID:** at.racon.elbamobil
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=437426300">437426300</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/raiffeisen-elba/id437426300?mt=8&uo=4">https://itunes.apple.com/us/app/raiffeisen-elba/id437426300?mt=8&uo=4</a>
**App Version:** 7.9.0
**Seller:** Raiffeisen e-force GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/raiffeisen-e-force-gmbh/id434810783?uo=4>© Raiffeisen e-force GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/5f/81/20/5f8120d5-2456-b2c7-8309-ee2ce2c5e8d4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18237494/68d37412-7332-11e6-99bc-c301c73a83e7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229884/0ff04af8-728a-11e6-8aab-c63b1918f0da.png)
https://cloud.githubusercontent.com/assets/20930745/18229884/0ff04af8-728a-11e6-8aab-c63b1918f0da.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18229887/241a32dc-728a-11e6-8966-f497905b1345.png

**Comment by Anuskuss** [comment]
@2Qt2beStr8 whitout the border?

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18237494/68d37412-7332-11e6-99bc-c301c73a83e7.png)
https://cloud.githubusercontent.com/assets/2068130/18237494/68d37412-7332-11e6-99bc-c301c73a83e7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18237500/7c26e26a-7332-11e6-84db-26745291100f.png
