### ISSUE TITLE
RaiffeisenClub

### ISSUE THREAD

**Issue by Konsti9012** [glasklart/hd#7671]
**App Name:** RaiffeisenClub
**Bundle ID:** com.raiffeisen.mobileclub
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=451963866">451963866</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/raiffeisenclub/id451963866?mt=8&uo=4">https://itunes.apple.com/us/app/raiffeisenclub/id451963866?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** Raiffeisen Zentralbank Oesterreich AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zentrale-raiffeisenwerbung/id451963869?uo=4>© Zentrale Raiffeisenwerbung</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/d3/f5/73/d3f57396-1f2b-02c5-4617-af19386bacff/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17636128/a2a3a928-60db-11e6-9fec-63b59063456c.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17636128/a2a3a928-60db-11e6-9fec-63b59063456c.png)
https://cloud.githubusercontent.com/assets/2068130/17636128/a2a3a928-60db-11e6-9fec-63b59063456c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17636136/b1efd3b6-60db-11e6-9f7e-5a75805b4ee7.png
