### ISSUE TITLE
Adblock Pro Safari

### ISSUE THREAD

**Issue by Konsti9012** [glasklart/hd#7672]
**App Name:** AdBlock Pro Safari
**Bundle ID:** com.samuellaska.AdBuster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1018301773">1018301773</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adblock-pro-safari/id1018301773?mt=8&uo=4">https://itunes.apple.com/us/app/adblock-pro-safari/id1018301773?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Samuel Laska
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/samuel-laska/id980289004?uo=4>© Samuel Laska</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/80/84/00/80840063-faf3-c3e3-2aaf-b67c4c25fc87/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17546659/90e33fae-5ee3-11e6-889f-f68dddce5ebc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17546659/90e33fae-5ee3-11e6-889f-f68dddce5ebc.png)
https://cloud.githubusercontent.com/assets/2068130/17546659/90e33fae-5ee3-11e6-889f-f68dddce5ebc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17546675/9f99c5f4-5ee3-11e6-9ede-21e45cd59945.png
