### ISSUE TITLE
Iron Maiden: Legacy of the Beast

### ISSUE THREAD

**Issue by Konsti9012** [glasklart/hd#7673]
**App Name:** Iron Maiden: Legacy of the Beast
**Bundle ID:** com.roadhousegames.lotb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1098307964">1098307964</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iron-maiden-legacy-beast/id1098307964?mt=8&uo=4">https://itunes.apple.com/us/app/iron-maiden-legacy-beast/id1098307964?mt=8&uo=4</a>
**App Version:** 2.02
**Seller:** Roadhouse Games Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/roadhouse-games-ltd./id858196067?uo=4>© Roadhouse Games Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/8e/c5/72/8ec5728c-e3bd-85f3-14f8-9aa21246d6d3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17550026/5bb27ce0-5ef3-11e6-9d0f-4fdb157b3ebe.png)

**Comment by dreamnet** [comment]
Ah, good old Eddie... :heart_eyes: 
Here is my try:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17550026/5bb27ce0-5ef3-11e6-9d0f-4fdb157b3ebe.png)
https://cloud.githubusercontent.com/assets/2068130/17550026/5bb27ce0-5ef3-11e6-9d0f-4fdb157b3ebe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17550044/69cdab7e-5ef3-11e6-8ad1-6485c35f9098.png
