### ISSUE TITLE
Fairway Solitaire

### ISSUE THREAD

**Issue by Konsti9012** [glasklart/hd#7674]
**App Name:** Fairway Solitaire
**Bundle ID:** com.bigfishgames.fairwaysolitaireuniversalf2p
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=887640616">887640616</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fairway-solitaire/id887640616?mt=8&uo=4">https://itunes.apple.com/us/app/fairway-solitaire/id887640616?mt=8&uo=4</a>
**App Version:** 1.11.1
**Seller:** Big Fish Games, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/big-fish-games-inc/id292594310?uo=4>© Big Fish Games, Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/b4/c1/2e/b4c12e9b-caaf-ca41-bf73-539e64fd1d6e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18833423/d859eb58-83f0-11e6-86d0-ff1d0f6770b9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18833423/d859eb58-83f0-11e6-86d0-ff1d0f6770b9.png)
https://cloud.githubusercontent.com/assets/20930745/18833423/d859eb58-83f0-11e6-86d0-ff1d0f6770b9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18833466/15704d8e-83f1-11e6-8388-b0ce579cb433.png
