### ISSUE TITLE
Forge of Empires

### ISSUE THREAD

**Issue by Konsti9012** [glasklart/hd#7675]
**App Name:** Forge of Empires
**Bundle ID:** com.innogames.iforge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=711455226">711455226</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/forge-of-empires/id711455226?mt=8&uo=4">https://itunes.apple.com/us/app/forge-of-empires/id711455226?mt=8&uo=4</a>
**App Version:** 1.81.0
**Seller:** InnoGames GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/innogames/id435365770?uo=4>© InnoGames</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/7b/38/e2/7b38e2b7-341d-49fc-84b0-74e36a9a9128/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19038936/1e224814-897e-11e6-9490-94a2e0c5bfec.png)

**Comment by 2Qt2beStr8** [comment]
.... can't do the original .... 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19038936/1e224814-897e-11e6-9490-94a2e0c5bfec.png)
https://cloud.githubusercontent.com/assets/20930745/19038936/1e224814-897e-11e6-9490-94a2e0c5bfec.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19038970/463fcc86-897e-11e6-85e5-65df67435c20.png

**Comment by dreamnet** [comment]
Jup, the original seems to be impossible...
