### ISSUE TITLE
Winter Fugitives 2: Chronicles

### ISSUE THREAD

**Issue by Konsti9012** [glasklart/hd#7676]
**App Name:** Winter Fugitives 2: Chronicles
**Bundle ID:** com.heavyboat.wf2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1102448236">1102448236</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/winter-fugitives-2-chronicles/id1102448236?mt=8&uo=4">https://itunes.apple.com/us/app/winter-fugitives-2-chronicles/id1102448236?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** HEAVYBOAT S.R.L.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/heavyboat-srl/id569857327?uo=4>© HeavyBoat SRL</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/b0/27/44/b02744cd-4a24-670e-bef8-2a7117c8523e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18810635/dee3be14-829b-11e6-912f-3400a69d43ee.png)

**Comment by dreamnet** [comment]
My first **real** handdrawn icon (Apple Pencil)... don't beat me! 😆 
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18810635/dee3be14-829b-11e6-912f-3400a69d43ee.png)
https://cloud.githubusercontent.com/assets/2068130/18810635/dee3be14-829b-11e6-912f-3400a69d43ee.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18810642/f271c32c-829b-11e6-8475-51f6bfc7d3c9.png
