### ISSUE TITLE
Winter Fugitives - a stealth prison break game

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7677]
**App Name:** Winter Fugitives - a stealth prison break game
**Bundle ID:** com.heavyboat.stealth
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=992200649">992200649</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/winter-fugitives-stealth-prison/id992200649?mt=8&uo=4">https://itunes.apple.com/us/app/winter-fugitives-stealth-prison/id992200649?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** HEAVYBOAT S.R.L.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/heavyboat-srl/id569857327?uo=4>© HeavyBoat SRL</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/11/e2/e6/11e2e62d-c55f-f917-d57b-018c03810de6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17582428/e9475f54-5fab-11e6-880c-090de96912d1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17582428/e9475f54-5fab-11e6-880c-090de96912d1.png)
https://cloud.githubusercontent.com/assets/2068130/17582428/e9475f54-5fab-11e6-880c-090de96912d1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17582440/f77cc1b8-5fab-11e6-9e0c-fbc012e18bac.png
