### ISSUE TITLE
Calc 2M - Scientific Calculator

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7680]
**App Name:** Calc 2M - Scientific Calculator
**Bundle ID:** com.inkOfPixel.Calc2m
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492563960">492563960</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calc-2m-scientific-calculator/id492563960?mt=8&uo=4">https://itunes.apple.com/us/app/calc-2m-scientific-calculator/id492563960?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** inkOfPixel srl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/inkofpixel-srl/id492563963?uo=4>© inkOfPixel srl</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/57/12/9b/57129b40-5310-f932-48b7-2bd20d8462b4/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17635051/b73154ea-60d5-11e6-9a33-b457eaa9d85d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17635051/b73154ea-60d5-11e6-9a33-b457eaa9d85d.png)
https://cloud.githubusercontent.com/assets/2068130/17635051/b73154ea-60d5-11e6-9a33-b457eaa9d85d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17635063/c6cad7d2-60d5-11e6-8281-d6fd824cb118.png
