### ISSUE TITLE
Ticker : Stocks Portfolio Manager for Investors on the move

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7681]
**App Name:** Ticker : Stocks Portfolio Manager for Investors on the move
**Bundle ID:** com.innopage.ticker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=680270408">680270408</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ticker-stocks-portfolio-manager/id680270408?mt=8&uo=4">https://itunes.apple.com/us/app/ticker-stocks-portfolio-manager/id680270408?mt=8&uo=4</a>
**App Version:** 3.19
**Seller:** Innopage Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/innopage-ltd/id361950817?uo=4>© Innopage Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/d8/2e/ab/d82eabda-50a1-0df7-5c79-ba11a0597f34/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17635215/763fc7c2-60d6-11e6-97e5-e77f520aeba9.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17635215/763fc7c2-60d6-11e6-97e5-e77f520aeba9.png)
https://cloud.githubusercontent.com/assets/2068130/17635215/763fc7c2-60d6-11e6-97e5-e77f520aeba9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17635232/84f33e66-60d6-11e6-823f-921b558e4d84.png
