### ISSUE TITLE
Remote File Manager

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7682]
**App Name:** Remote File Manager
**Bundle ID:** com.quickapps.quickexplorer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=608738784">608738784</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/remote-file-manager/id608738784?uo=4">https://apps.apple.com/us/app/remote-file-manager/id608738784?uo=4</a>
**App Version:** 4.0.0
**Seller:** Jane Zhang
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/jane-zhang/id608738787?uo=4">© Jane Zhang</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/69/0b/29/690b29fd-4484-43be-8969-a078f021b26d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68184015-3de76000-ff9e-11e9-99f4-014f30ec2026.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18231641/3e2c3d48-72bf-11e6-9609-2b43ec48021d.png)
https://cloud.githubusercontent.com/assets/20930745/18231641/3e2c3d48-72bf-11e6-9609-2b43ec48021d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18231648/56695850-72bf-11e6-8770-ce88a2c862ad.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18231731/ce952380-72c0-11e6-93f5-d5a5b17ba555.png)
https://cloud.githubusercontent.com/assets/20930745/18231731/ce952380-72c0-11e6-93f5-d5a5b17ba555.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18231736/e4601eae-72c0-11e6-9ab1-3ef7400e7850.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Hm... OK.

**Comment by l8er4now** [comment]
Needs an update

**App Name:** Remote File Manager
**Bundle ID:** com.quickapps.quickexplorer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=608738784">608738784</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/remote-file-manager/id608738784?uo=4">https://apps.apple.com/us/app/remote-file-manager/id608738784?uo=4</a>
**App Version:** 4.0.0
**Seller:** Jane Zhang
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/jane-zhang/id608738787?uo=4">© Jane Zhang</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/69/0b/29/690b29fd-4484-43be-8969-a078f021b26d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/68184015-3de76000-ff9e-11e9-99f4-014f30ec2026.png)
https://user-images.githubusercontent.com/2068130/68184015-3de76000-ff9e-11e9-99f4-014f30ec2026.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/68184044-4d66a900-ff9e-11e9-9397-ba59d0390a68.png
