### ISSUE TITLE
Xender - File Transfer & Sharing.

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7683]
**App Name:** Xender - File Transfer & Sharing
**Bundle ID:** cn.shanchuan.shanchuan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=898129576">898129576</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xender-file-transfer-sharing/id898129576?mt=8&uo=4">https://itunes.apple.com/us/app/xender-file-transfer-sharing/id898129576?mt=8&uo=4</a>
**App Version:** 3.4.5
**Seller:** Beijing AnQiZhiLian Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/beijing-anqi-zhilian-technology/id898129579?uo=4>© Beijing Anqi Zhilian Technology Co. Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple19/v4/55/0c/27/550c27d1-9fc5-1e3d-4f0f-eea72be6423e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19832027/87346e9a-9e19-11e6-83cd-0a68e6bf9e77.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17634946/2d9b56b8-60d5-11e6-89bb-92257748d93d.png)
https://cloud.githubusercontent.com/assets/2068130/17634946/2d9b56b8-60d5-11e6-89bb-92257748d93d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17634964/3c7b8b8a-60d5-11e6-9e27-7405b3ec3419.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Xender - File Transfer & Sharing
**Bundle ID:** cn.shanchuan.shanchuan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=898129576">898129576</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xender-file-transfer-sharing/id898129576?mt=8&uo=4">https://itunes.apple.com/us/app/xender-file-transfer-sharing/id898129576?mt=8&uo=4</a>
**App Version:** 3.4.5
**Seller:** Beijing AnQiZhiLian Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/beijing-anqi-zhilian-technology/id898129579?uo=4>© Beijing Anqi Zhilian Technology Co. Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple19/v4/55/0c/27/550c27d1-9fc5-1e3d-4f0f-eea72be6423e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19832027/87346e9a-9e19-11e6-83cd-0a68e6bf9e77.png)
https://cloud.githubusercontent.com/assets/2068130/19832027/87346e9a-9e19-11e6-83cd-0a68e6bf9e77.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19832031/9933cc1c-9e19-11e6-9c2e-2a0adab6d209.png
