### ISSUE TITLE
File Manager Pro - Advance File Manager and Document Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7684]
**App Name:** File Manager Pro - Advance File Manager and Document Reader
**Bundle ID:** com.livebird.FileDesk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=600550320">600550320</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/file-manager-pro-advance-file/id600550320?mt=8&uo=4">https://itunes.apple.com/us/app/file-manager-pro-advance-file/id600550320?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** LiveBird Technologies Private Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/livebird-technologies-private/id551521372?uo=4>© LiveBird Technologies Private Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/82/b0/ad/82b0adac-5c15-3473-dcfc-a19e12608eb3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17633474/be3aebbe-60cd-11e6-8c4f-6c283243db32.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17633474/be3aebbe-60cd-11e6-8c4f-6c283243db32.png)
https://cloud.githubusercontent.com/assets/2068130/17633474/be3aebbe-60cd-11e6-8c4f-6c283243db32.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17633484/ce0f02e6-60cd-11e6-9892-bf7aac0535d8.png
