### ISSUE TITLE
Netatmo Weather

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7685]
**App Name:** Netatmo Weather
**Bundle ID:** com.netatmo.netatmo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=532538499">532538499</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/netatmo-weather/id532538499?uo=4">https://apps.apple.com/us/app/netatmo-weather/id532538499?uo=4</a>
**App Version:** 3.1.1
**Seller:** Netatmo
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/netatmo/id532538502?uo=4">© Netatmo</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/24/ef/84/24ef849f-e260-dbe6-72ed-e75f2769837a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118389518-9fc06580-b62a-11eb-9f9b-cce8423bc6c6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833770/7a971a66-66ec-11e6-95d4-0332fc9f0632.png)
https://cloud.githubusercontent.com/assets/3090247/17833770/7a971a66-66ec-11e6-95d4-0332fc9f0632.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17833769/7a8a2cac-66ec-11e6-9f1d-2b6868802e45.png

**Comment by 2Qt2beStr8** [comment]
Thank you 👍🏻

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20107681/b09b105a-a5d9-11e6-92c5-fe7d0f81927a.png)
https://cloud.githubusercontent.com/assets/20930745/20107681/b09b105a-a5d9-11e6-92c5-fe7d0f81927a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20107717/cc722a5c-a5d9-11e6-9de8-99ac8728e8ce.png

**Comment by 2Qt2beStr8** [comment]
Needs update

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/118389518-9fc06580-b62a-11eb-9f9b-cce8423bc6c6.png)
https://user-images.githubusercontent.com/2068130/118389518-9fc06580-b62a-11eb-9f9b-cce8423bc6c6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/118389534-b1097200-b62a-11eb-8193-c1b2c47cd709.png
