### ISSUE TITLE
MAX! eQ-3

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7686]
**App Name:** MAX! eQ-3
**Bundle ID:** com.eq-3.max-eq3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=482014734">482014734</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/max!-eq-3/id482014734?mt=8&uo=4">https://itunes.apple.com/us/app/max!-eq-3/id482014734?mt=8&uo=4</a>
**App Version:** 3.2.0
**Seller:** eQ-3 AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eq-3-ag/id481997950?uo=4>© eQ-3 AG</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple1/v4/ff/e8/36/ffe83602-693e-3ebc-a9a4-da7a25758ca7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18031082/f9e4be16-6ccf-11e6-8659-e4d48adc4fe6.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18031073/dc17c57c-6ccf-11e6-8272-f433fee42567.png)
https://cloud.githubusercontent.com/assets/10730122/18031073/dc17c57c-6ccf-11e6-8272-f433fee42567.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18031072/dc154a40-6ccf-11e6-8aef-c8f57a4f02b4.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18031082/f9e4be16-6ccf-11e6-8659-e4d48adc4fe6.png)
https://cloud.githubusercontent.com/assets/10730122/18031082/f9e4be16-6ccf-11e6-8659-e4d48adc4fe6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18031081/f9e452aa-6ccf-11e6-88ad-4fc6989bfca0.png

**Comment by dreamnet** [comment]
Taking version 2.
