### ISSUE TITLE
PlanetRomeo – Gay Dating, Chat & Meet Guys

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7687]
**App Name:** PlanetRomeo – Gay Dating, Chat & Meet Guys
**Bundle ID:** com.planetromeo.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404386888">404386888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/planetromeo-gay-dating-chat/id404386888?mt=8&uo=4">https://itunes.apple.com/us/app/planetromeo-gay-dating-chat/id404386888?mt=8&uo=4</a>
**App Version:** 2.13.2
**Seller:** PlanetRomeo B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/planetromeo-bv/id404386891?uo=4>© PlanetRomeo BV</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/c3/7d/8a/c37d8aaf-8483-daa1-f925-52c95f3cc931/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17634672/1384e006-60d4-11e6-8147-627d62c04d00.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17634672/1384e006-60d4-11e6-8147-627d62c04d00.png)
https://cloud.githubusercontent.com/assets/2068130/17634672/1384e006-60d4-11e6-8147-627d62c04d00.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17634680/22be31ee-60d4-11e6-8df1-8dc24905ff6a.png
