### ISSUE TITLE
Mein mobilcom-debitel - Kostencheck und Kundenservice App

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7688]
**App Name:** Mein mobilcom-debitel - Kostencheck und Kundenservice App
**Bundle ID:** de.md.meinmd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=582955183">582955183</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/mein-mobilcom-debitel-kostencheck/id582955183?mt=8&uo=4">https://itunes.apple.com/de/app/mein-mobilcom-debitel-kostencheck/id582955183?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** Freenet AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/mobilcom-debitel/id405954758?uo=4>© mobilcom-debitel</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/ed/1f/08/ed1f089e-0789-913b-9991-1c544c2981f3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17634567/8f950bd6-60d3-11e6-8a20-ca140d4307db.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17634567/8f950bd6-60d3-11e6-8a20-ca140d4307db.png)
https://cloud.githubusercontent.com/assets/2068130/17634567/8f950bd6-60d3-11e6-8a20-ca140d4307db.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17634575/9d362aae-60d3-11e6-83be-8ac5ddf05474.png
