### ISSUE TITLE
GayRoyal - Dating & Chat

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7689]
**App Name:** GayRoyal - Dating & Chat
**Bundle ID:** com.bangster.bangsterapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=901795746">901795746</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gayroyal-dating-chat/id901795746?uo=4">https://apps.apple.com/us/app/gayroyal-dating-chat/id901795746?uo=4</a>
**App Version:** 3.0.1
**Seller:** 42pixels
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/42pixels/id399663014?uo=4">© 42pixels</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/26/48/9d/26489d60-24d5-3489-6e58-534fd32a853c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63653418-b21ab180-c76c-11e9-99ae-93a2781a4f6f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17634468/075ce860-60d3-11e6-9fad-81a1065de38b.png)
https://cloud.githubusercontent.com/assets/2068130/17634468/075ce860-60d3-11e6-9fad-81a1065de38b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17634478/15bc9c84-60d3-11e6-9c47-99e32e0337be.png

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63653418-b21ab180-c76c-11e9-99ae-93a2781a4f6f.png)
https://user-images.githubusercontent.com/20930745/63653418-b21ab180-c76c-11e9-99ae-93a2781a4f6f.png

Source:
https://user-images.githubusercontent.com/20930745/63653419-b3e47500-c76c-11e9-9600-f8e6c504311f.png
