### ISSUE TITLE
SCRUFF: Gay app for chat, dating, and social networking with guys worldwide

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7690]
**App Name:** SCRUFF: Gay app for chat, dating, and social networking with guys worldwide
**Bundle ID:** com.appspot.scruffapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380015247">380015247</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scruff-gay-app-for-chat-dating/id380015247?mt=8&uo=4">https://itunes.apple.com/us/app/scruff-gay-app-for-chat-dating/id380015247?mt=8&uo=4</a>
**App Version:** 5.0115
**Seller:** Perry Street Software, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/perry-street-software-inc/id359579430?uo=4>© Perry Street Software, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/23/28/aa/2328aa3d-cdb5-677b-39cf-b253b9a239c2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17634170/9044aef8-60d1-11e6-8006-bb7224a58bca.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17634170/9044aef8-60d1-11e6-8006-bb7224a58bca.png)
https://cloud.githubusercontent.com/assets/2068130/17634170/9044aef8-60d1-11e6-8006-bb7224a58bca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17634182/9f7ff08a-60d1-11e6-97ee-b76121268c7a.png
