### ISSUE TITLE
GROWLr: Gay Bear Social Network

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7691]
**App Name:** GROWLr: Gay Bear Social Network
**Bundle ID:** com.initechapps.growlr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393402212">393402212</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/growlr-gay-bear-social-network/id393402212?mt=8&uo=4">https://itunes.apple.com/us/app/growlr-gay-bear-social-network/id393402212?mt=8&uo=4</a>
**App Version:** 9.54
**Seller:** Initech, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/initech-llc/id339590843?uo=4>© Initech LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/32/bc/d3/32bcd363-0a05-9d13-8cfa-5e77655ada24/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17637116/bf590012-60e1-11e6-8c9c-98c884ba310f.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17637116/bf590012-60e1-11e6-8c9c-98c884ba310f.png)
https://cloud.githubusercontent.com/assets/2068130/17637116/bf590012-60e1-11e6-8c9c-98c884ba310f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17637128/cf23f628-60e1-11e6-8291-621d00e5b729.png
