### ISSUE TITLE
DownTime

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7692]
**App Name:** DownTime
**Bundle ID:** com.lingonikorg.DownTime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=286794722">286794722</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/downtime/id286794722?mt=8&uo=4">https://itunes.apple.com/us/app/downtime/id286794722?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Oskar Lissheim
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/oskar-lissheim/id286794726?uo=4>© Oskar Lissheim</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/24/84/0c/24840cbf-d7bc-6104-0f6d-1c7bc77bfd55/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17633694/e0ae361e-60ce-11e6-9258-8a6b34f89340.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17633694/e0ae361e-60ce-11e6-9258-8a6b34f89340.png)
https://cloud.githubusercontent.com/assets/2068130/17633694/e0ae361e-60ce-11e6-9258-8a6b34f89340.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17633702/ef233b54-60ce-11e6-9051-8203259c807c.png
