### ISSUE TITLE
VR-Banking

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7693]
**App Name:** VR-Banking
**Bundle ID:** de.fiducia.iphone.vrbanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375341021">375341021</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vr-banking/id375341021?mt=8&uo=4">https://itunes.apple.com/us/app/vr-banking/id375341021?mt=8&uo=4</a>
**App Version:** 16.10.01
**Seller:** Fiducia & GAD IT  AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fiducia-gad-it-ag/id375341024?uo=4>© Fiducia & GAD IT AG</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/c7/79/92/c7799246-7956-6e1b-f46d-777fdfe1c674/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17833794/d00a8498-6727-11e6-8b02-fc3bee06a918.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833707/f40e0104-66ea-11e6-9d6f-00abba88de65.png)
https://cloud.githubusercontent.com/assets/3090247/17833707/f40e0104-66ea-11e6-9d6f-00abba88de65.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17833708/f4126aaa-66ea-11e6-8b37-a3486ed10eee.png

**Comment by dreamnet** [comment]
Or inverted?
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17833794/d00a8498-6727-11e6-8b02-fc3bee06a918.png)
https://cloud.githubusercontent.com/assets/2068130/17833794/d00a8498-6727-11e6-8b02-fc3bee06a918.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17833795/de9c19cc-6727-11e6-81e2-883ef12b36bc.png

**Comment by 2Qt2beStr8** [comment]
Thank you very much! I prefer the inverted one
