### ISSUE TITLE
ebase mobile viewer

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7694]
**App Name:** ebase mobile viewer
**Bundle ID:** com.ebase.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398333410">398333410</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ebase-mobile-viewer/id398333410?mt=8&uo=4">https://itunes.apple.com/us/app/ebase-mobile-viewer/id398333410?mt=8&uo=4</a>
**App Version:** 1.12
**Seller:** European Bank for Financial Services GmbH (ebase)
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/european-bank-for-financial/id398332578?uo=4>© European Bank for Financial Services GmbH (ebase)</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/39/21/3c/39213c9a-6c6e-053d-f42d-e06adcc86dc5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17633897/12140926-60d0-11e6-99a0-77eb3bf594e2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17633897/12140926-60d0-11e6-99a0-77eb3bf594e2.png)
https://cloud.githubusercontent.com/assets/2068130/17633897/12140926-60d0-11e6-99a0-77eb3bf594e2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17633906/20fb8cf2-60d0-11e6-8541-0a163cf0ae40.png
