### ISSUE TITLE
Club Carlson

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7695]
**App Name:** Club Carlson
**Bundle ID:** com.carlson.ClubCarlson
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427744285">427744285</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/club-carlson/id427744285?mt=8&uo=4">https://itunes.apple.com/us/app/club-carlson/id427744285?mt=8&uo=4</a>
**App Version:** 2.8.1
**Seller:** Carlson
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/carlson-hotels/id427744288?uo=4>© Carlson Hotels</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/85/b2/0a/85b20ad2-28fc-ca1f-2a2f-6b43ec9cba39/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17634060/fb7fc44c-60d0-11e6-8093-eaf79e88b3ce.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17634060/fb7fc44c-60d0-11e6-8093-eaf79e88b3ce.png)
https://cloud.githubusercontent.com/assets/2068130/17634060/fb7fc44c-60d0-11e6-8093-eaf79e88b3ce.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17634068/09d4b520-60d1-11e6-973a-5d91ec276a66.png

**Comment by boxermansr** [comment]
Sweet, thanks! Now if only my other request got filled, device looks silly with in-themed icons :)
👍

**Comment by dreamnet** [comment]
@boxermansr It seems that I'm currently doing 95% of the icons here and I'm also busy with other things, so I don't have the time to do the harder icons. :cry:  We are in need for some talented icon-makers at the moment....

**Comment by boxermansr** [comment]
@dreamnet  understood, and your work is very very much appreciated. If I had the time, and the patience I'd be contributing myself, but I bounce around so much these days, that I rarely have time to think, lol. :)
