### ISSUE TITLE
Cydia Eraser

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7696]
**App Name:** Cydia Eraser
**Bundle ID:** com.saurik.Eraser
**Version:** 0.9.32
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/17636281/70f03d50-60dc-11e6-9140-ec161aa1058e.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17830961/f975b898-66dc-11e6-93d8-fdb9d56e2e15.png)

**Comment by dreamnet** [comment]
@boxermansr We need the original artwork, as big as possible.

**Comment by boxermansr** [comment]
@dreamnet I mega suck at this to begin with, and even more so with Cydia apps. I'm pretty sure, as always when it comes to Cydia requests, that I did it wrong, but hoping that maybe I got lucky this time.

**Comment by dreamnet** [comment]
@boxermansr Check the [Wiki](https://github.com/glasklart/hd/wiki/How-to-submit-an-icon-request-for-a-Cydia-app). Also: I don't get it, why should we theme [this app](https://cydia.saurik.com/package/com.saurik.impactor/)?

**Comment by boxermansr** [comment]
Because this likely will be on a decent amount of devices now, as it allows you to restore your device to your current version of IOS (in an in-jailbroken form) and the icon (as stock) is ugly as heck.

**Comment by dreamnet** [comment]
@boxermansr OK, I think I understand. We already need the original artwork.

**Comment by 2Qt2beStr8** [comment]
Hallo Günther,
ich habe dir die Dateien per Email geschickt.

**Comment by dreamnet** [comment]
@2Qt2beStr8 Danke Jürgen, ich seh's mir an.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17830961/f975b898-66dc-11e6-93d8-fdb9d56e2e15.png)
https://cloud.githubusercontent.com/assets/2068130/17830961/f975b898-66dc-11e6-93d8-fdb9d56e2e15.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17830962/0866f592-66dd-11e6-9bd3-4bc22b2865f9.png
