### ISSUE TITLE
File Pro - Ultimate File Manager & PDF Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7698]
**App Name:** File Pro - Ultimate File Manager & PDF Reader
**Bundle ID:** com.perceptionsystem.ourreader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=537623975">537623975</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/file-pro-ultimate-file-manager/id537623975?mt=8&uo=4">https://itunes.apple.com/us/app/file-pro-ultimate-file-manager/id537623975?mt=8&uo=4</a>
**App Version:** 5.8.1
**Seller:** Perception System
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/perception-system/id320752004?uo=4>© Perception System</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/b1/01/47/b1014735-66bb-512c-d27d-d68b2a880c7d/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17833053/9f9aca52-6713-11e6-8f6f-857e8ffc0312.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17833053/9f9aca52-6713-11e6-8f6f-857e8ffc0312.png)
https://cloud.githubusercontent.com/assets/2068130/17833053/9f9aca52-6713-11e6-8f6f-857e8ffc0312.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17833059/ae0950f4-6713-11e6-9e04-29d85af389d3.png
