### ISSUE TITLE
Cloud Files by Olive Toast

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7699]
**App Name:** Cloud Files by Olive Toast
**Bundle ID:** com.olivetoast.cloudfiles
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=522366430">522366430</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cloud-files-by-olive-toast/id522366430?mt=8&uo=4">https://itunes.apple.com/us/app/cloud-files-by-olive-toast/id522366430?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Olive Toast Software Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/olive-toast-software-ltd/id285578663?uo=4>© Olive Toast Software Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/b8/b6/ed/b8b6ed76-2788-0725-c1ec-125b3e13ab4b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17678025/bdee5488-6335-11e6-8fef-c88ee3393d0e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17678025/bdee5488-6335-11e6-8fef-c88ee3393d0e.png)
https://cloud.githubusercontent.com/assets/2068130/17678025/bdee5488-6335-11e6-8fef-c88ee3393d0e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17678046/cf372c10-6335-11e6-90a5-b6372dc01be2.png
