### ISSUE TITLE
RTÉ News Now

### ISSUE THREAD

**Issue by ButtersScotch** [glasklart/hd#77]
**App Name:** RTÉ News Now
**Bundle ID:** ie.adforce.rtenewsireland
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=355836123">355836123</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rt%C3%A9-news-now/id355836123?mt=8&uo=4">https://itunes.apple.com/us/app/rt%C3%A9-news-now/id355836123?mt=8&uo=4</a>
**App Version:** 5.1.13
**Seller:** RTE
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rt%C3%A9/id417236883?uo=4">© RTÉ</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/0d/34/a8/0d34a88a-b324-7b7a-c3b0-be9910491a01/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreament.at?image=https://user-images.githubusercontent.com/2068130/32692659-5e3c253c-c71c-11e7-9305-8ec48405c9d4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreament.at?image=https://user-images.githubusercontent.com/2068130/32692659-5e3c253c-c71c-11e7-9305-8ec48405c9d4.png)
https://user-images.githubusercontent.com/2068130/32692659-5e3c253c-c71c-11e7-9305-8ec48405c9d4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692662-6d230bba-c71c-11e7-8e8b-418c6af117a4.png
