### ISSUE TITLE
Nationwide Mobile Banking

### ISSUE THREAD

**Issue by xapher19** [glasklart/hd#770]
**App Name:** Nationwide Mobile Banking
**Bundle ID:** co.uk.Nationwide.MobileBanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542355130">542355130</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/nationwide-mobile-banking/id542355130?mt=8&uo=4">https://itunes.apple.com/gb/app/nationwide-mobile-banking/id542355130?mt=8&uo=4</a>
**App Version:** 3.18.32
**Seller:** Nationwide Building Society
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/nationwide-building-society/id540377479?uo=4>© Nationwide Building Society</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/ed/0e/87/ed0e87c3-4b02-3620-6b43-3a8fd19c9406/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617888/cfd1a880-983c-11e6-85ab-1ccd2b8d1f30.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19617888/cfd1a880-983c-11e6-85ab-1ccd2b8d1f30.png)
https://cloud.githubusercontent.com/assets/20930745/19617888/cfd1a880-983c-11e6-85ab-1ccd2b8d1f30.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19617890/e825dc8a-983c-11e6-9a99-ff6be5e243db.png
