### ISSUE TITLE
iFiles 2 - File Manager, Cloud Storage, PDF Reader with Annotate

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7700]
**App Name:** iFiles 2 - File Manager, Cloud Storage, PDF Reader with Annotate
**Bundle ID:** com.imagam.ifiles2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1104795347">1104795347</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ifiles-2-file-manager-cloud/id1104795347?mt=8&uo=4">https://itunes.apple.com/us/app/ifiles-2-file-manager-cloud/id1104795347?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** Tom Biel
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/imagam.com/id313140599?uo=4>© Imagam.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/5b/0c/12/5b0c12b9-3aff-fa42-9c69-91188bbbd148/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17833005/c6922e1c-6712-11e6-8e03-1f1a7f2030c1.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17833005/c6922e1c-6712-11e6-8e03-1f1a7f2030c1.png)
https://cloud.githubusercontent.com/assets/2068130/17833005/c6922e1c-6712-11e6-8e03-1f1a7f2030c1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17833010/db74abca-6712-11e6-83c3-0c48b0c4b004.png
