### ISSUE TITLE
Notebook - Take Notes, Sync across devices

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7701]
**App Name:** Notebook - Take Notes, Sync across devices
**Bundle ID:** com.zoho.notebook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=973801089">973801089</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/notebook-take-notes-sync-across/id973801089?mt=8&uo=4">https://itunes.apple.com/us/app/notebook-take-notes-sync-across/id973801089?mt=8&uo=4</a>
**App Version:** 1.0.8
**Seller:** Zoho Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zoho-corporation/id388384807?uo=4>© Zoho Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/f4/7f/19/f47f1937-b321-203a-e965-5e8022109e2a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17678489/9c6e09f0-6337-11e6-9cc1-ad005d64831d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17678489/9c6e09f0-6337-11e6-9cc1-ad005d64831d.png)
https://cloud.githubusercontent.com/assets/2068130/17678489/9c6e09f0-6337-11e6-9cc1-ad005d64831d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17678504/ad34a6fe-6337-11e6-872b-69998448e1f0.png
