### ISSUE TITLE
Folder & Note : neat notepad

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7702]
**App Name:** Folder & Note : neat notepad
**Bundle ID:** ent.goya.foldpad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1086535856">1086535856</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/folder-note-neat-notepad/id1086535856?mt=8&uo=4">https://itunes.apple.com/us/app/folder-note-neat-notepad/id1086535856?mt=8&uo=4</a>
**App Version:** 1.12
**Seller:** Goya Entertainment
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/goya-entertainment/id922400109?uo=4>© Goya entertainment</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/99/4a/cb/994acbf0-04f2-220c-7470-3e3c2c0fcb66/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17677918/2ae8a616-6335-11e6-9884-ffb558502615.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17677918/2ae8a616-6335-11e6-9884-ffb558502615.png)
https://cloud.githubusercontent.com/assets/2068130/17677918/2ae8a616-6335-11e6-9884-ffb558502615.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17677925/3be6707e-6335-11e6-9a35-ea61337cfa20.png
