### ISSUE TITLE
LOOX Fitness Planer

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7703]
**App Name:** LOOX Fitness Planer
**Bundle ID:** com.loox.fitness-planer.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=732003576">732003576</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/loox-fitness-planer/id732003576?mt=8&uo=4">https://itunes.apple.com/us/app/loox-fitness-planer/id732003576?mt=8&uo=4</a>
**App Version:** 4.5.0
**Seller:** LOOX Sports GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/loox-sports-gmbh/id728270909?uo=4>© LOOX Sports GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/ff/16/88/ff16886e-f8e5-46a6-b5a4-41b9be0abf08/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17677775/a0dbc8ae-6334-11e6-86f8-c90e00069114.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17677775/a0dbc8ae-6334-11e6-86f8-c90e00069114.png)
https://cloud.githubusercontent.com/assets/2068130/17677775/a0dbc8ae-6334-11e6-86f8-c90e00069114.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17677794/b45a6782-6334-11e6-8f53-7bf5b67df7df.png
