### ISSUE TITLE
BR-Radio

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7704]
**App Name:** BR-Radio
**Bundle ID:** de.br.brradio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=516572185">516572185</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/br-radio/id516572185?mt=8&uo=4">https://itunes.apple.com/us/app/br-radio/id516572185?mt=8&uo=4</a>
**App Version:** 1.31
**Seller:** Bayerischer Rundfunk
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bayerischer-rundfunk/id359096163?uo=4>© Bayerischer Rundfunk</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/7c/19/d2/7c19d203-96d0-9d46-a69e-1a25aecc06b5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17677657/1923bb4c-6334-11e6-87cf-e476339f1878.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17677657/1923bb4c-6334-11e6-87cf-e476339f1878.png)
https://cloud.githubusercontent.com/assets/2068130/17677657/1923bb4c-6334-11e6-87cf-e476339f1878.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17677672/2866a3b2-6334-11e6-848f-bfaefde1e426.png
