### ISSUE TITLE
inthespirit easy cocktails

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7705]
**App Name:** inthespirit easy cocktails
**Bundle ID:** uk.co.madeyoulook.www
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=343663917">343663917</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inthespirit-easy-cocktails/id343663917?mt=8&uo=4">https://itunes.apple.com/us/app/inthespirit-easy-cocktails/id343663917?mt=8&uo=4</a>
**App Version:** 1.01
**Seller:** madeyoulook
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/madeyoulook/id343663920?uo=4>© madeyoulook</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/b5/b8/91/b5b8914e-5dbe-9d5a-353a-350ef0877331/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833682/380a409e-66ea-11e6-9c5a-819ac0ef91a1.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833682/380a409e-66ea-11e6-9c5a-819ac0ef91a1.png)
https://cloud.githubusercontent.com/assets/3090247/17833682/380a409e-66ea-11e6-9c5a-819ac0ef91a1.png
Source:
https://cloud.githubusercontent.com/assets/3090247/17833681/380460a2-66ea-11e6-9c40-504cefe9e7ec.png

**Comment by dreamnet** [comment]
@ivanov007 Jup! :+1:
