### ISSUE TITLE
German English Dictionary & Translator  Free / Wörterbuch & Übersetzer Englisch Deutsch Gratis - Bravolol

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7706]
**App Name:** German English Dictionary & Translator  Free / Wörterbuch & Übersetzer Englisch Deutsch Gratis - Bravolol
**Bundle ID:** com.bravolang.dictionary.german
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=568041778">568041778</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/german-english-dictionary/id568041778?mt=8&uo=4">https://itunes.apple.com/us/app/german-english-dictionary/id568041778?mt=8&uo=4</a>
**App Version:** 8.1
**Seller:** Bravolol Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bravolol-limited/id449112802?uo=4>© Bravolol Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple18/v4/d9/24/c7/d924c7ed-1019-b3fd-9007-02a601d291bc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809773/487d537e-8285-11e6-9a58-0a70a469aa71.png)

**Comment by 2Qt2beStr8** [comment]
not my best work ... but no idea how to make it better :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18669021/2eced76c-7f39-11e6-89b0-3a72dcdc74a9.png)
https://cloud.githubusercontent.com/assets/20930745/18669021/2eced76c-7f39-11e6-89b0-3a72dcdc74a9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18669078/88c08388-7f39-11e6-8eab-a573279373b8.png

**Comment by 2Qt2beStr8** [comment]
i think this one is a little bit better 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809773/487d537e-8285-11e6-9a58-0a70a469aa71.png)
https://cloud.githubusercontent.com/assets/20930745/18809773/487d537e-8285-11e6-9a58-0a70a469aa71.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18809776/6857baf4-8285-11e6-8b96-4f29d19e93a3.png
