### ISSUE TITLE
M's Dictionary - German English

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7707]
**App Name:** M's Dictionary - German English
**Bundle ID:** de.mt-apps.ms-dictionary-de-en
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417392721">417392721</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ms-dictionary-german-english/id417392721?mt=8&uo=4">https://itunes.apple.com/us/app/ms-dictionary-german-english/id417392721?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Michael Tartsch
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/michael-tartsch/id417392724?uo=4>© Michael Tartsch</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/ae/60/68/ae6068a4-93d5-baf8-8d43-2f027237e88b/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18671081/fb1fe23a-7f42-11e6-9b12-f0a9d9d60070.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18671081/fb1fe23a-7f42-11e6-9b12-f0a9d9d60070.png)
https://cloud.githubusercontent.com/assets/20930745/18671081/fb1fe23a-7f42-11e6-9b12-f0a9d9d60070.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18671103/0fa0bb4e-7f43-11e6-8956-f9e87038ec70.png
