### ISSUE TITLE
iHandy Translator Free

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7708]
**App Name:** iHandy Translator Free
**Bundle ID:** com.ihandysoft.translator.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386272641">386272641</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ihandy-translator-free/id386272641?mt=8&uo=4">https://itunes.apple.com/us/app/ihandy-translator-free/id386272641?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** iHandy Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ihandy-inc./id291242250?mt=8&uo=4>© iHandy Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/a2/24/92/a2249251-22a3-16e4-68f6-5270bc94c8e7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808685/3a697a9a-8269-11e6-99ed-a301ac2c707b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18807684/d9353fc2-824d-11e6-90b2-112ef05e9f1e.png)
https://cloud.githubusercontent.com/assets/20930745/18807684/d9353fc2-824d-11e6-90b2-112ef05e9f1e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18807686/e9d08b48-824d-11e6-805c-de301bc828c3.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Great icon! 🎆

**Comment by 2Qt2beStr8** [comment]
noooooo ... one separation line is missing :-((((((

**Comment by dreamnet** [comment]
Wups... 😁

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808685/3a697a9a-8269-11e6-99ed-a301ac2c707b.png)
https://cloud.githubusercontent.com/assets/20930745/18808685/3a697a9a-8269-11e6-99ed-a301ac2c707b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18808687/4d9c0362-8269-11e6-9313-7bded20b5608.png
