### ISSUE TITLE
MyŠKODA

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7709]
**App Name:** MyŠKODA
**Bundle ID:** cz.skoda-auto.service
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555311924">555311924</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/myskoda/id555311924?mt=8&uo=4">https://itunes.apple.com/gb/app/myskoda/id555311924?mt=8&uo=4</a>
**App Version:** 5.1.2
**Seller:** SKODA  AUTO a.s.
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/skoda-auto-a.s./id420627878?uo=4">© Skoda Auto a.s.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/70/8e/19/708e1968-b255-a50c-c9c6-beb1feb289a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20018947/522bb824-a2ca-11e6-83a4-0fd03b1ac91a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17677144/c509bf0e-6331-11e6-8b9c-90df0027a207.png)
https://cloud.githubusercontent.com/assets/2068130/17677144/c509bf0e-6331-11e6-8b9c-90df0027a207.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17677157/d49fed26-6331-11e6-8983-a8d6efe26dec.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20018947/522bb824-a2ca-11e6-83a4-0fd03b1ac91a.png)
https://cloud.githubusercontent.com/assets/20930745/20018947/522bb824-a2ca-11e6-83a4-0fd03b1ac91a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20018972/68be1e42-a2ca-11e6-9fa7-2f00bb8b935d.png
