### ISSUE TITLE
Spritmonitor

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7710]
**App Name:** Spritmonitor
**Bundle ID:** de.spritmonitor.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=616137163">616137163</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spritmonitor/id616137163?mt=8&uo=4">https://itunes.apple.com/us/app/spritmonitor/id616137163?mt=8&uo=4</a>
**App Version:** 2.6.3
**Seller:** Fisch und Fischl GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fisch-und-fischl-gmbh/id616137166?uo=4>© Fisch und Fischl GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/dc/64/42/dc64424e-0b33-73f1-efcd-5fe216989aca/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17676893/bdc4b470-6330-11e6-8ae6-efad12c60881.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17676893/bdc4b470-6330-11e6-8ae6-efad12c60881.png)
https://cloud.githubusercontent.com/assets/2068130/17676893/bdc4b470-6330-11e6-8ae6-efad12c60881.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17676911/cd09ccc2-6330-11e6-83ef-e68b752266b3.png
