### ISSUE TITLE
Vueling Airlines - Cheap Flights

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7711]
**App Name:** Vueling Airlines - Cheap Flights
**Bundle ID:** com.vueling.Vueling
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=445818820">445818820</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vueling-airlines-cheap-flights/id445818820?mt=8&uo=4">https://itunes.apple.com/us/app/vueling-airlines-cheap-flights/id445818820?mt=8&uo=4</a>
**App Version:** 7.4
**Seller:** Vueling Airlines
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vueling-airlines-s.a./id445818823?uo=4>© Vueling Airlines S.A.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/5c/41/92/5c41929a-09ab-13db-dbca-b000d3ebf993/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17787774/e14d59e0-658a-11e6-91c3-0c0923b8f3bf.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17787774/e14d59e0-658a-11e6-91c3-0c0923b8f3bf.png)
https://cloud.githubusercontent.com/assets/10730122/17787774/e14d59e0-658a-11e6-91c3-0c0923b8f3bf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17787775/e1671bfa-658a-11e6-971a-2f4ed9bba122.png
