### ISSUE TITLE
Hyperion Remote

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7712]
**App Name:** Hyperion Remote
**Bundle ID:** de.chaosspace.Hyperion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943635503">943635503</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hyperion-remote/id943635503?mt=8&uo=4">https://itunes.apple.com/us/app/hyperion-remote/id943635503?mt=8&uo=4</a>
**App Version:** 1.10.0
**Seller:** Andreas Ganske
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/andreas-ganske/id434907508?uo=4>© Andreas Ganske</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/45/2f/32/452f32a3-0048-404f-d99a-bf9f02f8606b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18811428/26e77b2a-82af-11e6-9393-ecce5dfea84d.png)

**Comment by 2Qt2beStr8** [comment]
no idea how to make this icon :-/

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18409455/c0c7a364-7747-11e6-8eb2-3734ce1c1016.png)
https://cloud.githubusercontent.com/assets/20930745/18409455/c0c7a364-7747-11e6-8eb2-3734ce1c1016.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18409463/fb3a09a6-7747-11e6-943e-3ee4947de05c.png

**Comment by dreamnet** [comment]
Yeah... :thought_balloon: :confused:

**Comment by dreamnet** [comment]
Maybe...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18811428/26e77b2a-82af-11e6-9393-ecce5dfea84d.png)
https://cloud.githubusercontent.com/assets/2068130/18811428/26e77b2a-82af-11e6-9393-ecce5dfea84d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18811433/3a867eba-82af-11e6-92d0-7225a17b9a23.png
