### ISSUE TITLE
Guitar Hero® Live

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7713]
**App Name:** Guitar Hero® Live
**Bundle ID:** com.activision.guitarhero.live.game
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1024764676">1024764676</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/guitar-hero-live/id1024764676?mt=8&uo=4">https://itunes.apple.com/us/app/guitar-hero-live/id1024764676?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Activision Publishing, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/activision-publishing-inc./id285005466?mt=8&uo=4>© Activision Publishing, Inc.</a>
**Supported Devices:** iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/4a/6e/ed/4a6eed55-1a79-98c6-c307-e6f8d88778f9/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17677554/9d78b330-6333-11e6-82f6-1dc949654b6d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17677554/9d78b330-6333-11e6-82f6-1dc949654b6d.png)
https://cloud.githubusercontent.com/assets/2068130/17677554/9d78b330-6333-11e6-82f6-1dc949654b6d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17677572/acf2c918-6333-11e6-9ea9-a959c9dbf503.png
