### ISSUE TITLE
Mars: Mars

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7714]
**App Name:** Mars: Mars
**Bundle ID:** com.pomelogames.MarsGame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1108964305">1108964305</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mars-mars/id1108964305?mt=8&uo=4">https://itunes.apple.com/us/app/mars-mars/id1108964305?mt=8&uo=4</a>
**App Version:** 5
**Seller:** Outbox SRL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pomelo-games/id899606172?uo=4>© Pomelo Games</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple71/v4/bd/81/b2/bd81b268-7ff1-8014-deba-af85c3ff3edc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18234569/aa77ee5c-730a-11e6-8dfd-ad66446d509f.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833643/299f285a-66e8-11e6-9398-c4be2230774b.png)
https://cloud.githubusercontent.com/assets/3090247/17833643/299f285a-66e8-11e6-9398-c4be2230774b.png
Source:
https://cloud.githubusercontent.com/assets/3090247/17833642/29821a76-66e8-11e6-89a6-f45117e120ca.png

**Comment by dreamnet** [comment]
@ivanov007 Yes! :+1:

**Comment by Anuskuss** [comment]
@ivanov007 I like the icon, but how about making the glas of the helmet transparent? There's too much white for me :blush:

**Comment by Anuskuss** [comment]
Transparent helmet panel:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18234569/aa77ee5c-730a-11e6-8dfd-ad66446d509f.png)
https://cloud.githubusercontent.com/assets/7157389/18234569/aa77ee5c-730a-11e6-8dfd-ad66446d509f.png



___

Source:
https://cloud.githubusercontent.com/assets/7157389/18234572/c11e149c-730a-11e6-8001-b0ec36302aee.png
