### ISSUE TITLE
New Dunkin’ Donuts

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#7715]
**App Name:** New Dunkin’ Donuts
**Bundle ID:** com.dunkinbrands.otgo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1056813463">1056813463</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/new-dunkin-donuts/id1056813463?mt=8&uo=4">https://itunes.apple.com/us/app/new-dunkin-donuts/id1056813463?mt=8&uo=4</a>
**App Version:** 4.2.2
**Seller:** Dunkin' Donuts
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dunkin-donuts/id318953209?uo=4>© Dunkin' Donuts</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/0a/e7/de/0ae7de9d-0095-d4ac-0e9c-0b9a3f2e476f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832591/14c91a34-6707-11e6-8af1-f024bf4bbc7e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832591/14c91a34-6707-11e6-8af1-f024bf4bbc7e.png)
https://cloud.githubusercontent.com/assets/2068130/17832591/14c91a34-6707-11e6-8af1-f024bf4bbc7e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17832593/245e645e-6707-11e6-8d6f-72b0538f5637.png
