### ISSUE TITLE
Weber® Grills

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#7716]
**App Name:** Weber® Grills
**Bundle ID:** com.weberstephen.freeapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=540468068">540468068</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weber-grills/id540468068?mt=8&uo=4">https://itunes.apple.com/us/app/weber-grills/id540468068?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Weber-Stephen Products Co.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/weber-stephen-products-co./id321412326?uo=4>© Weber-Stephen Products Co.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/b2/3c/d5/b23cd5a0-8246-dd8b-d8b4-8aa0eb8c079f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17676767/3d8a6430-6330-11e6-81ec-e7617eb0a625.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17676767/3d8a6430-6330-11e6-81ec-e7617eb0a625.png)
https://cloud.githubusercontent.com/assets/2068130/17676767/3d8a6430-6330-11e6-81ec-e7617eb0a625.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17676787/4e68f582-6330-11e6-8f54-1c0b649e300a.png
