### ISSUE TITLE
MTA eTix

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#7717]
**App Name:** MTA eTix
**Bundle ID:** com.mta.mobileapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1104885987">1104885987</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mta-etix/id1104885987?mt=8&uo=4">https://itunes.apple.com/us/app/mta-etix/id1104885987?mt=8&uo=4</a>
**App Version:** 3.1.12
**Seller:** MTA/New York City Transit
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/metropolitan-transportation/id528916105?uo=4>© Metropolitan Transportation Authority</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/d3/49/85/d34985f1-9c34-4750-ab80-930206c915a6/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17676607/a5de2fea-632f-11e6-882c-97764e3392ab.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17676607/a5de2fea-632f-11e6-882c-97764e3392ab.png)
https://cloud.githubusercontent.com/assets/2068130/17676607/a5de2fea-632f-11e6-882c-97764e3392ab.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17676613/b5db7f7e-632f-11e6-93f2-1839a6cfe283.png
