### ISSUE TITLE
Transferable PRO - wifi photo transfer!

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#7718]
**App Name:** Transferable PRO - wifi photo transfer!
**Bundle ID:** uk.co.bewhere.transferable.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=518154149">518154149</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/transferable-pro-wifi-photo/id518154149?mt=8&uo=4">https://itunes.apple.com/us/app/transferable-pro-wifi-photo/id518154149?mt=8&uo=4</a>
**App Version:** 7.0
**Seller:** Portable Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/portable-ltd/id377800228?uo=4>© Portable Ltd</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/ae/6f/d2/ae6fd281-7edd-246d-2886-e0d592118624/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17675443/15e2f1be-632a-11e6-9c66-607bd9394848.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17675443/15e2f1be-632a-11e6-9c66-607bd9394848.png)
https://cloud.githubusercontent.com/assets/2068130/17675443/15e2f1be-632a-11e6-9c66-607bd9394848.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17675458/25080364-632a-11e6-83ac-d79f92a9c8bd.png
