### ISSUE TITLE
ScoreBig

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#7719]
**App Name:** ScoreBig
**Bundle ID:** com.scorebig.tickets
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1028142265">1028142265</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scorebig/id1028142265?mt=8&uo=4">https://itunes.apple.com/us/app/scorebig/id1028142265?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** ScoreBig, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/scorebig-inc./id515331805?uo=4>© ScoreBig, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/06/5c/9b/065c9b28-9693-0632-9207-74eae4bd621c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17707999/2d048038-63e3-11e6-96da-c6def7fce1c9.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17707999/2d048038-63e3-11e6-96da-c6def7fce1c9.png)
https://cloud.githubusercontent.com/assets/10730122/17707999/2d048038-63e3-11e6-96da-c6def7fce1c9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17707998/2ceb23e0-63e3-11e6-8d18-a18c2900bab6.png
