### ISSUE TITLE
Flow Free: Bridges

### ISSUE THREAD

**Issue by xapher19** [glasklart/hd#772]
**App Name:** Flow Free: Bridges
**Bundle ID:** com.bigduckgames.flow.bridges
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=569322760">569322760</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flow-free-bridges/id569322760?mt=8&uo=4">https://itunes.apple.com/us/app/flow-free-bridges/id569322760?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Big Duck Games LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/big-duck-games-llc/id435664937?uo=4">© Big Duck Games LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/50/b2/92/50b292ad-3565-6f2f-5ec4-6c913c4c8482/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20217011/1905df1c-a81e-11e6-96d3-7f137b829d35.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20217011/1905df1c-a81e-11e6-96d3-7f137b829d35.png)
https://cloud.githubusercontent.com/assets/20930745/20217011/1905df1c-a81e-11e6-96d3-7f137b829d35.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20217026/2e2b23b6-a81e-11e6-954a-29566acd3cc5.png
