### ISSUE TITLE
mViewer-Pro

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#7720]
**App Name:** mViewer-Pro
**Bundle ID:** com.dvrdomain.imviewerpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1062237708">1062237708</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mviewer-pro/id1062237708?mt=8&uo=4">https://itunes.apple.com/us/app/mviewer-pro/id1062237708?mt=8&uo=4</a>
**App Version:** 1.00.04
**Seller:** DVRDomain .com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dvrdomain/id347189824?uo=4>© dvrdomain</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple7/v4/58/57/fd/5857fd24-32de-d7b9-4170-ff8c1f1e5436/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18237416/6fa07c3c-7331-11e6-879b-f0e3f3a57203.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832976/ffcf9b0c-6711-11e6-8977-a9ad561db1c5.png)
https://cloud.githubusercontent.com/assets/2068130/17832976/ffcf9b0c-6711-11e6-8977-a9ad561db1c5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17832977/0e9760f2-6712-11e6-9d37-6cb3734a8ef3.png

**Comment by Anuskuss** [comment]
@dreamnet Ehm, why did you leave the middle line transparent and make the top and bottom white? Wouldn't it make more sense (for this icon) to do the opposite?

**Comment by dreamnet** [comment]
@Anuskuss Because that's like the original is. Doing this icon in the oposite way would look like this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17835412/789fefb0-676b-11e6-8edc-aa60a024ecb5.png)

**Comment by Anuskuss** [comment]
@dreamnet Why not both?
![](https://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/7157389/18227776/131bde68-7230-11e6-8657-bb83cb5c3967.png)


I know this doesn't make sense as for color -> transparent but I looks better in my eyes. Tell me your opinion.

**Comment by dreamnet** [comment]
@Anuskuss Source?

**Comment by Anuskuss** [comment]
@dreamnet Didn't think you would like it, so I deleted it :smile: 

Give me a sec, I'll recreate it.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18237416/6fa07c3c-7331-11e6-879b-f0e3f3a57203.png)
https://cloud.githubusercontent.com/assets/2068130/18237416/6fa07c3c-7331-11e6-879b-f0e3f3a57203.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18237420/894be8a6-7331-11e6-9f16-7af95eacdf6d.png
