### ISSUE TITLE
i-FlashDrive HD

### ISSUE THREAD

**Issue by katakolo** [glasklart/hd#7721]
**App Name:** i-FlashDrive HD
**Bundle ID:** tw.photofast.i-flashdrive-hd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525386291">525386291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/i-flashdrive-hd/id525386291?mt=8&uo=4">https://itunes.apple.com/us/app/i-flashdrive-hd/id525386291?mt=8&uo=4</a>
**App Version:** 2.6.11
**Seller:** PhotoFast Co. Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/photofast-co.-ltd/id379389417?uo=4>© PhotoFast Co. Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/26/0c/74/260c7407-e44c-0cb3-877f-7850c15dc068/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17675277/5da322a4-6329-11e6-9dab-200c040a1d38.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17675277/5da322a4-6329-11e6-9dab-200c040a1d38.png)
https://cloud.githubusercontent.com/assets/2068130/17675277/5da322a4-6329-11e6-9dab-200c040a1d38.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17675290/6d2ab732-6329-11e6-9cea-d5cabf233f09.png
