### ISSUE TITLE
DSCO by VSCO

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7723]
**App Name:** DSCO by VSCO
**Bundle ID:** co.visualsupply.DSCO
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1038318658">1038318658</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dsco-by-vsco/id1038318658?mt=8&uo=4">https://itunes.apple.com/us/app/dsco-by-vsco/id1038318658?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Visual Supply Company
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/visual-supply-company/id513526768?uo=4>© Visual Supply Company</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/6d/6c/47/6d6c47f7-fc8b-4f2a-ec97-c3a32752a7e8/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17675172/e581a35e-6328-11e6-88d9-e05ec67b8a34.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17675172/e581a35e-6328-11e6-88d9-e05ec67b8a34.png)
https://cloud.githubusercontent.com/assets/2068130/17675172/e581a35e-6328-11e6-88d9-e05ec67b8a34.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17675184/f381d460-6328-11e6-8116-d62ba2a2697d.png
