### ISSUE TITLE
Tiendeo - Deals & Weekly Ads

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7724]
**App Name:** Tiendeo - Deals & Weekly Ads
**Bundle ID:** com.tiendeo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489822377">489822377</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tiendeo-deals-weekly-ads/id489822377?mt=8&uo=4">https://itunes.apple.com/us/app/tiendeo-deals-weekly-ads/id489822377?mt=8&uo=4</a>
**App Version:** 5.0.2
**Seller:** Tiendeo Web Marketing S.L.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tiendeo-web-marketing-s-l/id489822380?uo=4">© Tiendeo Web Marketing S.L.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/e3/80/06/e3800674-04e7-8b88-878f-df754125124a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40588114-d9da397a-61d8-11e8-8b3a-43dc09d53f71.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17678622/2a2ee868-6338-11e6-86b7-bf94950da700.png)
https://cloud.githubusercontent.com/assets/2068130/17678622/2a2ee868-6338-11e6-86b7-bf94950da700.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17678635/3a8c07d6-6338-11e6-8485-03e174aa6f31.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Tiendeo - Deals & Weekly Ads
**Bundle ID:** com.tiendeo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489822377">489822377</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tiendeo-deals-weekly-ads/id489822377?mt=8&uo=4">https://itunes.apple.com/us/app/tiendeo-deals-weekly-ads/id489822377?mt=8&uo=4</a>
**App Version:** 5.0.2
**Seller:** Tiendeo Web Marketing S.L.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tiendeo-web-marketing-s-l/id489822380?uo=4">© Tiendeo Web Marketing S.L.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/e3/80/06/e3800674-04e7-8b88-878f-df754125124a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40588114-d9da397a-61d8-11e8-8b3a-43dc09d53f71.png)
https://user-images.githubusercontent.com/2068130/40588114-d9da397a-61d8-11e8-8b3a-43dc09d53f71.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/40588120-e77bda02-61d8-11e8-94ff-17b1737be9dc.png
