### ISSUE TITLE
Gas Tycoon 3 - pipe puzzle mania!

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7726]
**App Name:** Gas Tycoon 3 - pipe puzzle mania!
**Bundle ID:** biz.kalinin.gastycoon3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484110908">484110908</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gas-tycoon-3-pipe-puzzle-mania!/id484110908?mt=8&uo=4">https://itunes.apple.com/us/app/gas-tycoon-3-pipe-puzzle-mania!/id484110908?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Aleksey Kalinin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aleksey-kalinin/id308809673?uo=4>© Aleksey Kalinin</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/b9/58/af/b958af27-4b90-9ad2-6c0d-1698d832ae0e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832655/71cbfe30-6708-11e6-82b1-8bcdfc9660eb.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832655/71cbfe30-6708-11e6-82b1-8bcdfc9660eb.png)
https://cloud.githubusercontent.com/assets/2068130/17832655/71cbfe30-6708-11e6-82b1-8bcdfc9660eb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17832659/80c1ef3a-6708-11e6-89a6-68e25c52a349.png
