### ISSUE TITLE
Rotoworld Fantasy News & Draft Guides

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7727]
**App Name:** Rotoworld Fantasy News & Draft Guides
**Bundle ID:** com.nbcuni.nbcsports.rotoworld
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382669268">382669268</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rotoworld-fantasy-news-draft/id382669268?mt=8&uo=4">https://itunes.apple.com/us/app/rotoworld-fantasy-news-draft/id382669268?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** NBCUniversal Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nbcuniversal-media-llc/id303544359?uo=4>© NBCUniversal Media, LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/bc/c1/2a/bcc12add-4b52-3120-8dc8-7f84f8ee43d1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17707839/807d8cce-63e2-11e6-9169-802205c533c1.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17707839/807d8cce-63e2-11e6-9169-802205c533c1.png)
https://cloud.githubusercontent.com/assets/10730122/17707839/807d8cce-63e2-11e6-9169-802205c533c1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17707840/80833200-63e2-11e6-9092-4987b33c2c4b.png
