### ISSUE TITLE
inRoute Route Planner, GPS Navigation & Severe Weather Alerts

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7728]
**App Name:** inRoute Route Planner, GPS Navigation & Severe Weather Alerts
**Bundle ID:** com.CarobApps.inRoute
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=703796787">703796787</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inroute-route-planner-gps/id703796787?mt=8&uo=4">https://itunes.apple.com/us/app/inroute-route-planner-gps/id703796787?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** Carob Apps, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/carob-apps-llc/id387597632?uo=4>© Carob Apps, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/38/f2/2d/38f22d14-1d7b-cab5-3a45-ab8efb57c0a3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832897/32552996-670f-11e6-86e6-40200815954e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832897/32552996-670f-11e6-86e6-40200815954e.png)
https://cloud.githubusercontent.com/assets/2068130/17832897/32552996-670f-11e6-86e6-40200815954e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17832899/40fc9614-670f-11e6-8b55-3a44598de559.png
