### ISSUE TITLE
Favorites Widget - Call & Text from the Notification Center

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7729]
**App Name:** Favorites Widget - Call & Text from the Notification Center
**Bundle ID:** com.gubi.Favorites-Widget
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=909578530">909578530</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/favorites-widget-call-text/id909578530?mt=8&uo=4">https://itunes.apple.com/us/app/favorites-widget-call-text/id909578530?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Guy Gubi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/guy-gubi/id332505557?mt=8&uo=4>© Guy Gubi</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple32/v4/38/f8/74/38f8742d-23e8-42c3-aa15-fe293fd4d068/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17787613/238c320a-658a-11e6-9b61-e6dc11090eab.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/17787613/238c320a-658a-11e6-9b61-e6dc11090eab.png)
https://cloud.githubusercontent.com/assets/10730122/17787613/238c320a-658a-11e6-9b61-e6dc11090eab.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/17787612/236fb2f6-658a-11e6-8e57-3a39d93b13f7.png
