### ISSUE TITLE
Pixel Cup Soccer 16

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7730]
**App Name:** Pixel Cup Soccer 16
**Bundle ID:** com.batovi.soccer2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1092276838">1092276838</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pixel-cup-soccer-16/id1092276838?mt=8&uo=4">https://itunes.apple.com/us/app/pixel-cup-soccer-16/id1092276838?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** ODT S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/odt-s.a./id499893740?uo=4>© ODT S.A.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/90/04/43/900443b5-ffcd-1a34-46cc-7a611c129c1c/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17826389/917923ae-6670-11e6-939b-28e8ef031358.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17826389/917923ae-6670-11e6-939b-28e8ef031358.png)
https://cloud.githubusercontent.com/assets/2068130/17826389/917923ae-6670-11e6-939b-28e8ef031358.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17826395/a0b92e72-6670-11e6-862a-61f9c06c317c.png
