### ISSUE TITLE
Persistence - Goal and Habit Tracker and Motivator

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7731]
**App Name:** Persistence - Goal and Habit Tracker and Motivator
**Bundle ID:** com.junderoo.ShapeUp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=789890932">789890932</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/persistence-goal-habit-tracker/id789890932?mt=8&uo=4">https://itunes.apple.com/us/app/persistence-goal-habit-tracker/id789890932?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Samuel Clark
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/samuel-clark/id720920026?uo=4>© Samuel Clark</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/1a/f7/ae/1af7ae8f-4ec7-4d99-2524-06fa2212dfda/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17825241/41fbe36a-6667-11e6-82bb-4af496e46834.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17825241/41fbe36a-6667-11e6-82bb-4af496e46834.png)
https://cloud.githubusercontent.com/assets/2068130/17825241/41fbe36a-6667-11e6-82bb-4af496e46834.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17825249/51149176-6667-11e6-9f76-3b9053350d31.png
