### ISSUE TITLE
Zoho Sheet - Spreadsheet App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7733]
**App Name:** Zoho Sheet - Spreadsheet App
**Bundle ID:** com.zoho.zohosheet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1081348290">1081348290</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/zoho-sheet-spreadsheet-app/id1081348290?uo=4">https://apps.apple.com/us/app/zoho-sheet-spreadsheet-app/id1081348290?uo=4</a>
**App Version:** 2.97
**Seller:** Zoho Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/zoho-corporation/id388384807?uo=4">© Zoho Corporation</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/89/5d/03/895d0388-6c44-3f16-97d0-0d6b5e2a6490/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74584349-b1533180-4fd1-11ea-996d-ee6496805ec5.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17825097/1e601b3e-6666-11e6-802d-bf9ab0c8a488.png)
https://cloud.githubusercontent.com/assets/2068130/17825097/1e601b3e-6666-11e6-802d-bf9ab0c8a488.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17825106/2d63877e-6666-11e6-8e98-2a8046afd4aa.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Zoho Sheet - Spreadsheet App
**Bundle ID:** com.zoho.zohosheet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1081348290">1081348290</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/zoho-sheet-spreadsheet-app/id1081348290?uo=4">https://apps.apple.com/us/app/zoho-sheet-spreadsheet-app/id1081348290?uo=4</a>
**App Version:** 2.97
**Seller:** Zoho Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/zoho-corporation/id388384807?uo=4">© Zoho Corporation</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/89/5d/03/895d0388-6c44-3f16-97d0-0d6b5e2a6490/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74584349-b1533180-4fd1-11ea-996d-ee6496805ec5.png)
https://user-images.githubusercontent.com/20930745/74584349-b1533180-4fd1-11ea-996d-ee6496805ec5.png

Source:
https://user-images.githubusercontent.com/20930745/74584354-b3b58b80-4fd1-11ea-8e00-71774a7edeaf.png
