### ISSUE TITLE
WriteRight: enjoy writing

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7734]
**App Name:** WriteRight: enjoy writing
**Bundle ID:** com.wordmagicsoft.writeRight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=671844532">671844532</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/writeright-enjoy-writing/id671844532?mt=8&uo=4">https://itunes.apple.com/us/app/writeright-enjoy-writing/id671844532?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** Word Magic Software Ltda.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/word-magic-software/id416216400?uo=4>© Word Magic Software</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/3b/83/90/3b839058-4f53-ff4c-6590-cfae4e59f248/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832567/6572335e-6706-11e6-9eff-e3bacb795556.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832567/6572335e-6706-11e6-9eff-e3bacb795556.png)
https://cloud.githubusercontent.com/assets/2068130/17832567/6572335e-6706-11e6-9eff-e3bacb795556.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17832569/74bdde12-6706-11e6-9aac-e6a1f2bddbe7.png
