### ISSUE TITLE
WorldMate Travel Plans & Flight Tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7735]
**App Name:** WorldMate Travel Plans & Flight Tracker
**Bundle ID:** com.mobimate.worldmategold
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=317821764">317821764</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/worldmate-travel-plans-flight/id317821764?mt=8&uo=4">https://itunes.apple.com/us/app/worldmate-travel-plans-flight/id317821764?mt=8&uo=4</a>
**App Version:** 7.3
**Seller:** WorldMate, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/worldmate-inc./id317821767?uo=4>© WorldMate, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/28/70/e0/2870e07c-4351-197c-29d3-c9013d5001ac/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833105/66755be0-66da-11e6-8f89-7400e5cc9a89.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832832/4ae950b0-670d-11e6-8aef-cdd39c117125.png)
https://cloud.githubusercontent.com/assets/2068130/17832832/4ae950b0-670d-11e6-8aef-cdd39c117125.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17832833/5c025414-670d-11e6-88a1-558209ccdcba.png

**Comment by ivanov007** [comment]
an alternative
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833105/66755be0-66da-11e6-8f89-7400e5cc9a89.png)
https://cloud.githubusercontent.com/assets/3090247/17833105/66755be0-66da-11e6-8f89-7400e5cc9a89.png
Source:
https://cloud.githubusercontent.com/assets/3090247/17833106/6676fd38-66da-11e6-86e5-11fa1b82c057.png

**Comment by dreamnet** [comment]
@ivanov007 Jup, fine! :+1:
