### ISSUE TITLE
Aero Tour - Inflight Map + Guide

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7736]
**App Name:** Aero Tour - Inflight Map + Guide
**Bundle ID:** com.amdaris.aero-tour
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935635865">935635865</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aero-tour-inflight-map-+-guide/id935635865?mt=8&uo=4">https://itunes.apple.com/us/app/aero-tour-inflight-map-+-guide/id935635865?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Amdaris LLP
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/amdaris-llp/id894991395?uo=4>© AMDARIS LLP</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/29/1f/43/291f430f-1850-332e-a42d-53cb0be39ed3/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832541/c2521f86-6705-11e6-8ff8-a67936251a6d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832541/c2521f86-6705-11e6-8ff8-a67936251a6d.png)
https://cloud.githubusercontent.com/assets/2068130/17832541/c2521f86-6705-11e6-8ff8-a67936251a6d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17832544/d0c946f2-6705-11e6-9eaa-2b44802c8047.png
