### ISSUE TITLE
Instacall - The Best Smart Dialer (T9 Search, Speed Dial, Widget, Watch, Group Message)

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7737]
**App Name:** Instacall - The Best Smart Dialer (T9 Search, Speed Dial, Widget, Watch, Group Message)
**Bundle ID:** com.hbull.Instacall
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=800013306">800013306</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instacall-best-smart-dialer/id800013306?mt=8&uo=4">https://itunes.apple.com/us/app/instacall-best-smart-dialer/id800013306?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** 동현 hwang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hbull/id493849479?uo=4>© hbull</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/83/c3/7e/83c37eea-19ea-6c9b-73cd-39346c97d6a0/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832520/0fe146e2-6705-11e6-84b7-eddf6acff59b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832520/0fe146e2-6705-11e6-84b7-eddf6acff59b.png)
https://cloud.githubusercontent.com/assets/2068130/17832520/0fe146e2-6705-11e6-84b7-eddf6acff59b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17832523/1ebd2cbc-6705-11e6-997a-2eafb91ff2e2.png

**Comment by Anuskuss** [comment]
@dreamnet Why no circle?

**Comment by dreamnet** [comment]
@Anuskuss White = white. Dark = transparent.
