### ISSUE TITLE
Release v4.39.0 - BROKEN! - Please don't download!

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#7738]
**!! ATTENTION !!** This release of Glasklart uses Anemone **!! ATTENTION !!**

To use this version of Glasklart, please install `Anemone`. `Winterboard`, `IconBundles` and `ThemeLib` are not needed anymore.
--- ---
Changes:
- 150 icons added.
- 50 icons updated.
- ShareSheet Theme added.
- Settings theme updated.

--- ---
Known Bugs:
- None so far.

--- ---
Thanks to @ivanov007, @Trubbel & @zmathiasz!

--- ---
Full changelog is [here](https://github.com/glasklart/hd/compare/release/v4.38.0...release/v4.39.0).

--- ---
Will be available on Cydia in two or three days. Hopefully.

**Comment by quantum8** [comment]
Fantastic, keep up the awesome work! :+1:

**Comment by grkka** [comment]
![asset](https://cloud.githubusercontent.com/assets/14794477/18002978/63d67cce-6b8b-11e6-8738-151a4b1181ef.PNG)
???

**Comment by boxermansr** [comment]
Some apps are no longer themed (boxcar 2 is one) and calendar icon is a bit... Un pretty (red and black)... Is this normal?

**Comment by dreamnet** [comment]
@boxermansr No. I'm checking.

**Comment by dreamnet** [comment]
OK, just downloaded 4.39 from Cydia and it seems that **a lot of files are simply missing** in this release. I don't know what happened - I submittes 4.39 normally to Cydia.

**To everyone: This is a buggy release. Please stay on 4.38 or if you already have 4.39 please downgrade to 4.38. 4.40 will be submitted as fast as possible to Cydia.**
---

**Comment by grkka** [comment]
@dreamnet I have not been able to download version 4.38

**Comment by dreamnet** [comment]
@grkka Woops - I see. 2 options: Wait for 4.40 or download the actual master and manually copy the "Glasklart"-Folders in it to `Library/Themes/` on your device.

**Comment by grkka** [comment]
@dreamnet No problem. I have the saved version 4.33. I installed that. Thank you. I hope also to the version 4.40.

**Comment by dreamnet** [comment]
4.40 is on Cydia. Seems to be fine. Closing this.
