### ISSUE TITLE
ClassDojo

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7739]
**App Name:** ClassDojo
**Bundle ID:** com.ClassDojo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=552602056">552602056</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/classdojo/id552602056?mt=8&uo=4">https://itunes.apple.com/us/app/classdojo/id552602056?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** Class Twist Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/class-twist-inc./id552602059?uo=4>© Class Twist Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/10/70/a5/1070a522-ac74-5aa3-27a8-9010dc47e795/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832784/a8f74fb0-670b-11e6-8abb-b5d34a8ff683.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832784/a8f74fb0-670b-11e6-8abb-b5d34a8ff683.png)
https://cloud.githubusercontent.com/assets/2068130/17832784/a8f74fb0-670b-11e6-8abb-b5d34a8ff683.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17832787/b9d972fe-670b-11e6-94b8-a3201987d66d.png

**Comment by Anuskuss** [comment]
@dreamnet No cirle please :angel:

**Comment by dreamnet** [comment]
@Anuskuss Take a look at the original, the "green Monster" comes out of the circle, so the circle must be part of the icon.
