### ISSUE TITLE
Fantasy Football My Playbook by FantasyPros

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7740]
**App Name:** Fantasy Football My Playbook by FantasyPros
**Bundle ID:** com.fantasypros.mpb-nfl-2016
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1141119371">1141119371</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasy-football-my-playbook/id1141119371?mt=8&uo=4">https://itunes.apple.com/us/app/fantasy-football-my-playbook/id1141119371?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Marzen Media LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/marzen-media-llc/id892964104?uo=4>© Marzen Media LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple22/v4/91/3f/76/913f760e-4436-10ce-543c-86eddc4b5104/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832687/0a90f9f4-6709-11e6-9a38-820acc0d80dd.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17832687/0a90f9f4-6709-11e6-9a38-820acc0d80dd.png)
https://cloud.githubusercontent.com/assets/2068130/17832687/0a90f9f4-6709-11e6-9a38-820acc0d80dd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17832689/197bb5c6-6709-11e6-95f5-2abbf2b6ab17.png
