### ISSUE TITLE
Converter — The Amazing Unit Converter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7741]
**App Name:** Converter — The Amazing Unit Converter
**Bundle ID:** com.tapisfun.converter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=496789167">496789167</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/converter-amazing-unit-converter/id496789167?mt=8&uo=4">https://itunes.apple.com/us/app/converter-amazing-unit-converter/id496789167?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** RITESH RANJAN
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tap-is-fun/id353995404?uo=4>© Tap is Fun</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/83/1a/53/831a530a-80b8-7aa5-f211-8ff9ab17e9dc/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17835486/b878a142-676e-11e6-9cda-8a930c52b7c4.png)

**Comment by dreamnet** [comment]
@l8er4now How may apps do you have installed??? :open_mouth:

**Comment by l8er4now** [comment]
Right at this moment, 553.

**Comment by dreamnet** [comment]
@l8er4now Phhhhh...... :sweat:

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17835486/b878a142-676e-11e6-9cda-8a930c52b7c4.png)
https://cloud.githubusercontent.com/assets/2068130/17835486/b878a142-676e-11e6-9cda-8a930c52b7c4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17835487/cbe3a6e6-676e-11e6-84e5-7a1b969588dd.png
