### ISSUE TITLE
Remindify - Simple Way to Create Reminders

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7742]
**App Name:** Remindify - Simple Way to Create Reminders
**Bundle ID:** com.teammvc.remindify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1084185967">1084185967</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/remindify-simple-way-to-create/id1084185967?mt=8&uo=4">https://itunes.apple.com/us/app/remindify-simple-way-to-create/id1084185967?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** MCV Consulting, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mcv-consulting-llc/id349894405?uo=4>© MCV Consulting, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/cd/fd/b3/cdfdb3d4-b8b2-1b31-c9ed-59d1f537f162/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833789/17b8549a-66ed-11e6-95ce-c85383339cc0.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833789/17b8549a-66ed-11e6-95ce-c85383339cc0.png)
https://cloud.githubusercontent.com/assets/3090247/17833789/17b8549a-66ed-11e6-95ce-c85383339cc0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17833790/17b8c7ea-66ed-11e6-9a17-9be9620cf75a.png

**Comment by Anuskuss** [comment]
@ivanov007 Why no circle?

**Comment by dreamnet** [comment]
@Anuskuss White = white. Dark = transparent.
