### ISSUE TITLE
Find&Save - Cash Back for Shopping at Local Retail Stores, Coupons, Weekly Ads

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7743]
**App Name:** Find&Save - Cash Back for Shopping at Local Retail Stores, Coupons, Weekly Ads
**Bundle ID:** com.wanderful.iPhoneGeo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=740204829">740204829</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/find-save-cash-back-for-shopping/id740204829?mt=8&uo=4">https://itunes.apple.com/us/app/find-save-cash-back-for-shopping/id740204829?mt=8&uo=4</a>
**App Version:** 2.10.0
**Seller:** Wanderful Media
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wanderful-media/id695339974?uo=4>© Wanderful Media</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/53/02/1f/53021fa1-5fcf-9c30-a738-800612afe232/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833825/531b1bb6-66ee-11e6-8b0c-8b7953d3b898.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17833825/531b1bb6-66ee-11e6-8b0c-8b7953d3b898.png)
https://cloud.githubusercontent.com/assets/3090247/17833825/531b1bb6-66ee-11e6-8b0c-8b7953d3b898.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17833826/531b7d4a-66ee-11e6-9e89-1a41111d3584.png
