### ISSUE TITLE
Find Near Me - Nearby & Around

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7744]
**App Name:** Find Near Me - Nearby & Around
**Bundle ID:** com.xlabz.BanksIndia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=353369769">353369769</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/find-near-me-nearby-around/id353369769?uo=4">https://apps.apple.com/us/app/find-near-me-nearby-around/id353369769?uo=4</a>
**App Version:** 6.2.0
**Seller:** XLabz Technologies Pvt. Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/xlabz-technologies-pvt-ltd/id353369772?uo=4">© XLabz Technologies Pvt. Ltd.</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/8e/cf/0d/8ecf0d83-6c33-d255-efc7-1a62bf70404c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393579-12e48f80-9b18-11e9-8f5d-3bc25448df2b.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17833950/20501968-672d-11e6-8e10-bcdc10734204.png)
https://cloud.githubusercontent.com/assets/2068130/17833950/20501968-672d-11e6-8e10-bcdc10734204.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17833952/2fb01ab6-672d-11e6-800a-5daebf103b48.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Find Near Me for iPhone- Places Nearby & Around Me
**Bundle ID:** com.xlabz.BanksIndia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=353369769">353369769</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/find-near-me-for-iphone-places-nearby-around-me/id353369769?mt=8&uo=4">https://itunes.apple.com/us/app/find-near-me-for-iphone-places-nearby-around-me/id353369769?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** XLabz Technologies Pvt. Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/xlabz-technologies-pvt-ltd/id353369772?uo=4">© XLabz Technologies Pvt. Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/86/a4/ab/86a4ab20-e257-7111-d1bb-68f373ac617c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32213939-8e84ec0e-be1d-11e7-83ac-c07b798524f1.png)
https://user-images.githubusercontent.com/20930745/32213939-8e84ec0e-be1d-11e7-83ac-c07b798524f1.png

Source:
https://user-images.githubusercontent.com/20930745/32213964-a2b421a4-be1d-11e7-9bfc-7e53b15f848b.png

**Comment by dreamnet** [comment]
@l8er4now ??

**Comment by l8er4now** [comment]
Sure

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393579-12e48f80-9b18-11e9-8f5d-3bc25448df2b.png)
https://user-images.githubusercontent.com/20930745/60393579-12e48f80-9b18-11e9-8f5d-3bc25448df2b.png

Source:
https://user-images.githubusercontent.com/20930745/60393580-1415bc80-9b18-11e9-8b80-e08f05db8332.png
