### ISSUE TITLE
FlightTrack 5

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7745]
**App Name:** FlightTrack 5
**Bundle ID:** com.mobiata.FlightTrack
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=716913565">716913565</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flighttrack-5/id716913565?mt=8&uo=4">https://itunes.apple.com/us/app/flighttrack-5/id716913565?mt=8&uo=4</a>
**App Version:** 5.3.2
**Seller:** Mobiata LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobiata/id324473927?uo=4>© Mobiata</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple7/v4/b3/ce/6c/b3ce6c28-daca-6adb-e452-e2549059377a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18362420/f7783380-7605-11e6-87d0-b83ff267cd9d.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17834003/acb8900a-672e-11e6-934f-f0521baf058a.png)
https://cloud.githubusercontent.com/assets/2068130/17834003/acb8900a-672e-11e6-934f-f0521baf058a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17834005/bd834ff6-672e-11e6-961f-4b47ae59c303.png

**Comment by Anuskuss** [comment]
@dreamnet Hey buddy, could you :grin:

**Comment by dreamnet** [comment]
@Anuskuss What?

**Comment by Anuskuss** [comment]
@dreamnet ...make the lines thicker :innocent:

**Comment by 2Qt2beStr8** [comment]
@Anuskuss like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18362420/f7783380-7605-11e6-87d0-b83ff267cd9d.png)
https://cloud.githubusercontent.com/assets/20930745/18362420/f7783380-7605-11e6-87d0-b83ff267cd9d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18362448/0f5b807e-7606-11e6-8174-8c644dfb61e7.png
