### ISSUE TITLE
NetSnips - Follow Web Pages

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7746]
**App Name:** NetSnips - Follow Web Pages
**Bundle ID:** erschbamer.johannes.NetSnips
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507888242">507888242</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/netsnips-follow-web-pages/id507888242?mt=8&uo=4">https://itunes.apple.com/us/app/netsnips-follow-web-pages/id507888242?mt=8&uo=4</a>
**App Version:** 3.3.2
**Seller:** Johannes Erschbamer
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/johannes-erschbamer/id507888245?uo=4>© Johannes Erschbamer</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/74/e9/6b/74e96bd0-5b9c-c3a4-9f32-fb3cef7f7409/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17834079/7a58a6b0-6731-11e6-9445-6a83396c141a.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17834079/7a58a6b0-6731-11e6-9445-6a83396c141a.png)
https://cloud.githubusercontent.com/assets/2068130/17834079/7a58a6b0-6731-11e6-9445-6a83396c141a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17834082/8a5fd3d0-6731-11e6-8be8-774fb890e5d4.png
