### ISSUE TITLE
Soon - The Everyday Bucket List

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7747]
**App Name:** Soon - The Everyday Bucket List
**Bundle ID:** ab.beginner.Soon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=939751975">939751975</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/soon-the-everyday-bucket-list/id939751975?mt=8&uo=4">https://itunes.apple.com/us/app/soon-the-everyday-bucket-list/id939751975?mt=8&uo=4</a>
**App Version:** 3.0.8
**Seller:** Beginner AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/beginner-ab/id939751974?uo=4">© Beginner AB</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/58/16/6a/58166a3e-bad6-17c9-00ba-077fd352383d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/30062058-72efb454-920f-11e7-8b45-5e3dab9ab2b8.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17833930/644cae0c-672c-11e6-8003-aa3be82e62e1.png)
https://cloud.githubusercontent.com/assets/2068130/17833930/644cae0c-672c-11e6-8003-aa3be82e62e1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17833931/7319e328-672c-11e6-972c-61b00af70f35.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Soon - The Everyday Bucket List
**Bundle ID:** ab.beginner.Soon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=939751975">939751975</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/soon-the-everyday-bucket-list/id939751975?mt=8&uo=4">https://itunes.apple.com/us/app/soon-the-everyday-bucket-list/id939751975?mt=8&uo=4</a>
**App Version:** 3.0.8
**Seller:** Beginner AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/beginner-ab/id939751974?uo=4">© Beginner AB</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/58/16/6a/58166a3e-bad6-17c9-00ba-077fd352383d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/30062058-72efb454-920f-11e7-8b45-5e3dab9ab2b8.png)
https://user-images.githubusercontent.com/3090247/30062058-72efb454-920f-11e7-8b45-5e3dab9ab2b8.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/30062059-72f5c34e-920f-11e7-8e1b-95ad45ca0605.png
