### ISSUE TITLE
Fantasy Football Draft Wizard 2017 by FantasyPros

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7748]
**App Name:** Fantasy Football Draft Wizard 2017 by FantasyPros
**Bundle ID:** com.fantasypros.NFL-Draft-Wizard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1132708558">1132708558</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasy-football-draft-wizard-2017-by-fantasypros/id1132708558?mt=8&uo=4">https://itunes.apple.com/us/app/fantasy-football-draft-wizard-2017-by-fantasypros/id1132708558?mt=8&uo=4</a>
**App Version:** 2.1.4
**Seller:** Marzen Media LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marzen-media-llc/id892964104?uo=4">© Marzen Media LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/3e/37/d3/3e37d3e9-e9fa-791b-5300-45929786e410/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29238765-75aea70e-7f3b-11e7-97bb-ed98b63776cc.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17834052/947b3b30-6730-11e6-9971-0c238e19319f.png)
https://cloud.githubusercontent.com/assets/2068130/17834052/947b3b30-6730-11e6-9971-0c238e19319f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17834053/a3aded3c-6730-11e6-8889-7a0b13f5e5a2.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Fantasy Football Draft Wizard 2017 by FantasyPros
**Bundle ID:** com.fantasypros.NFL-Draft-Wizard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1132708558">1132708558</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasy-football-draft-wizard-2017-by-fantasypros/id1132708558?mt=8&uo=4">https://itunes.apple.com/us/app/fantasy-football-draft-wizard-2017-by-fantasypros/id1132708558?mt=8&uo=4</a>
**App Version:** 2.1.4
**Seller:** Marzen Media LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marzen-media-llc/id892964104?uo=4">© Marzen Media LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/3e/37/d3/3e37d3e9-e9fa-791b-5300-45929786e410/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29238765-75aea70e-7f3b-11e7-97bb-ed98b63776cc.png)
https://user-images.githubusercontent.com/2068130/29238765-75aea70e-7f3b-11e7-97bb-ed98b63776cc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29238767-875f2528-7f3b-11e7-895d-f97dc7b0f5af.png
