### ISSUE TITLE
FantasyPros Who Do I Start?

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7749]
**App Name:** FantasyPros Who Do I Start?
**Bundle ID:** com.fantasypros.wsi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1013018896">1013018896</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasypros-who-do-i-start/id1013018896?mt=8&uo=4">https://itunes.apple.com/us/app/fantasypros-who-do-i-start/id1013018896?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Marzen Media LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/marzen-media-llc/id892964104?uo=4>© Marzen Media LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/e4/a7/3c/e4a73c7f-1cf9-5bf4-b69b-3f15d6871330/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18755510/d7150162-80ec-11e6-803d-6b869a82e773.png)

**Comment by Trubbel** [comment]
Eh..

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18755510/d7150162-80ec-11e6-803d-6b869a82e773.png)
https://cloud.githubusercontent.com/assets/10730122/18755510/d7150162-80ec-11e6-803d-6b869a82e773.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18755510/d7150162-80ec-11e6-803d-6b869a82e773.png

**Comment by dreamnet** [comment]
@Trubbel Whoops... Source is missing.

**Comment by Trubbel** [comment]
@dreamnet :sweat_smile: Updated with source.
