### ISSUE TITLE
Mutility – Life Counter for Magic: The Gathering, MTG

### ISSUE THREAD

**Issue by CouleeApps** [glasklart/hd#7750]
**App Name:** Mutility – Life Counter for Magic: The Gathering, MTG
**Bundle ID:** Mutility
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=741336884">741336884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mutility-life-counter-for/id741336884?mt=8&uo=4">https://itunes.apple.com/us/app/mutility-life-counter-for/id741336884?mt=8&uo=4</a>
**App Version:** 1.5.5
**Seller:** Kevin Sliech
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kevin-sliech/id741336887?uo=4>© Kevin Sliech</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/85/74/64/85746425-0910-be94-55b3-b9971de511fc/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/17840656/e08a80f8-67da-11e6-9221-378ed5865223.png)

**Comment by ivanov007** [comment]
@CouleeApps you need to read [this](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#previewing-icons) to make the preview of your icon, also you need to post the [icon source](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources)

**Comment by dreamnet** [comment]
@CouleeApps Great work :+1:, we can accept it if you can post the [source file](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources).

**Comment by CouleeApps** [comment]
Ah. My bad. Here's the source: 
https://cloud.githubusercontent.com/assets/711973/17864086/7cad6966-686a-11e6-9ed4-060cced72b48.png

**Comment by ivanov007** [comment]
@CouleeApps great, thanks :+1:

**Comment by dreamnet** [comment]
@CouleeApps Great work, we always need talented icon contributors here - we hope, too see more from you.
