### ISSUE TITLE
Mathematics with PocketCAS Pro - Symbolic Graphing Calculator for Calculus, (Linear) Algebra and More!

### ISSUE THREAD

**Issue by CouleeApps** [glasklart/hd#7751]
**App Name:** Mathematics with PocketCAS Pro - Symbolic Graphing Calculator for Calculus, (Linear) Algebra and More!
**Bundle ID:** info.eurocomp.PocketCAS3pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=517250782">517250782</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mathematics-pocketcas-pro/id517250782?mt=8&uo=4">https://itunes.apple.com/us/app/mathematics-pocketcas-pro/id517250782?mt=8&uo=4</a>
**App Version:** 3.8.2
**Seller:** Thomas Osthege und Daniel Alm
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/thomas-osthege-und-daniel-alm/id333261118?uo=4>© Thomas Osthege und Daniel Alm</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/c6/15/f0/c615f021-e40b-c425-d346-da28e215e6fe/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![pocketcas](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/17870752/b37f3a02-6886-11e6-8507-a52695e4ab48.png)

**Comment by CouleeApps** [comment]
![pocketcas](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/17870752/b37f3a02-6886-11e6-8507-a52695e4ab48.png)
https://cloud.githubusercontent.com/assets/711973/17870752/b37f3a02-6886-11e6-8507-a52695e4ab48.png
Source: https://cloud.githubusercontent.com/assets/711973/17870754/ba12c83e-6886-11e6-98e0-33b0166ab522.png

**Comment by dreamnet** [comment]
@CouleeApps Yeah! :+1:
