### ISSUE TITLE
Fitness Point Pro - Workout Exercise Journal & Personal Trainer + Body Tracker

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7752]
**App Name:** Fitness Point Pro - Workout Exercise Journal & Personal Trainer + Body Tracker
**Bundle ID:** com.mosesyan.ilya.fitnesspointpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=573916046">573916046</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fitness-point-pro-workout/id573916046?mt=8&uo=4">https://itunes.apple.com/us/app/fitness-point-pro-workout/id573916046?mt=8&uo=4</a>
**App Version:** 6.4.4
**Seller:** ZERO ONE GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zero-one-gmbh/id467595016?uo=4>© ZERO ONE GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple18/v4/c9/85/90/c98590f4-7fa9-a7de-1078-bd48e998a7c2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17995023/511b3782-6b5e-11e6-9ec2-573739319e58.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17995023/511b3782-6b5e-11e6-9ec2-573739319e58.png)
https://cloud.githubusercontent.com/assets/2068130/17995023/511b3782-6b5e-11e6-9ec2-573739319e58.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17995030/60a6d1f2-6b5e-11e6-9a5f-2d507ef8b53f.png
