### ISSUE TITLE
Transmit

### ISSUE THREAD

**Issue by CouleeApps** [glasklart/hd#7753]
**App Name:** Transmit
**Bundle ID:** com.panic.iOS.Transmit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=917432930">917432930</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/transmit/id917432930?mt=8&uo=4">https://itunes.apple.com/us/app/transmit/id917432930?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** Panic, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/panic-inc./id403388568?uo=4>© Panic, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/61/6b/78/616b784b-402f-96b0-c8f1-51ce41a18198/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![transmit](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/17872177/da017dd8-688c-11e6-99c7-8456cfcd1e44.png)

**Comment by CouleeApps** [comment]
![transmit](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/17871091/142a5854-6888-11e6-8ae7-3aa1668a91cf.png)
https://cloud.githubusercontent.com/assets/711973/17871091/142a5854-6888-11e6-8ae7-3aa1668a91cf.png
Source: https://cloud.githubusercontent.com/assets/711973/17871097/1a8ee43a-6888-11e6-8211-211e6135c0c1.png

**Comment by ivanov007** [comment]
I think the road would look good

**Comment by CouleeApps** [comment]
So like this?
![transmit](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/17872177/da017dd8-688c-11e6-99c7-8456cfcd1e44.png)
https://cloud.githubusercontent.com/assets/711973/17872177/da017dd8-688c-11e6-99c7-8456cfcd1e44.png
Source: https://cloud.githubusercontent.com/assets/711973/17872213/0a6ad9b0-688d-11e6-8642-b09e38ca3c91.png

**Comment by ivanov007** [comment]
@CouleeApps yup great :+1:
