### ISSUE TITLE
Graphing Calculator

### ISSUE THREAD

**Issue by CouleeApps** [glasklart/hd#7755]
**App Name:** Graphing Calculator
**Bundle ID:** com.gnagy.graphingcalculator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=289940142">289940142</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/graphing-calculator/id289940142?mt=8&uo=4">https://itunes.apple.com/us/app/graphing-calculator/id289940142?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** Appcylon LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appcylon-llc/id289940145?uo=4>© Appcylon LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/2f/af/65/2faf65db-bfc1-933f-f4d5-a38c553ac973/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![graphcalc](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/18028760/8c3ac94e-6c54-11e6-9397-ea30156ea6a5.png)

**Comment by CouleeApps** [comment]
![graphcalc](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/17871673/9b9c5a6a-688a-11e6-8db3-a60c5b032c55.png)
https://cloud.githubusercontent.com/assets/711973/17871673/9b9c5a6a-688a-11e6-8db3-a60c5b032c55.png
Source: https://cloud.githubusercontent.com/assets/711973/17871699/b39f9190-688a-11e6-999a-f6045c750751.png

**Comment by ivanov007** [comment]
the bold lines looks good, but I think they need some separation from the axis, something like #6964

**Comment by CouleeApps** [comment]
How about this?
![graphcalc](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/17914592/6a3e9522-6971-11e6-8619-5dbce12adea5.png)
https://cloud.githubusercontent.com/assets/711973/17914592/6a3e9522-6971-11e6-8619-5dbce12adea5.png
Source: https://cloud.githubusercontent.com/assets/711973/17914571/42cefb3a-6971-11e6-9878-1c0f70e86add.png

**Comment by ivanov007** [comment]
@CouleeApps I mean the other way around, the axis on the back and the graphics on top, something like this
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17971587/0a48aaa0-6aa1-11e6-8826-1094b4363403.png)
https://cloud.githubusercontent.com/assets/3090247/17971587/0a48aaa0-6aa1-11e6-8826-1094b4363403.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17971585/09c69de4-6aa1-11e6-88b9-b5298779cce8.png

**Comment by CouleeApps** [comment]
I'm a big fan of much thicker lines, makes it clearer:
![graphcalc](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/18028760/8c3ac94e-6c54-11e6-9397-ea30156ea6a5.png)
https://cloud.githubusercontent.com/assets/711973/18028760/8c3ac94e-6c54-11e6-9397-ea30156ea6a5.png
Source: https://cloud.githubusercontent.com/assets/711973/18028763/99fd563c-6c54-11e6-8427-afcd9583f694.png

**Comment by ivanov007** [comment]
@CouleeApps yes, perfect :+1:
