### ISSUE TITLE
News Break - Personal & Local

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7756]
**App Name:** News Break - Personal & Local
**Bundle ID:** com.particlenews.newsbreak
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1132762804">1132762804</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/news-break-personal-local/id1132762804?mt=8&uo=4">https://itunes.apple.com/us/app/news-break-personal-local/id1132762804?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Particle Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/particle-media-inc./id1013476412?uo=4>© Particle Media Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/46/b8/e0/46b8e033-7bd4-05eb-f8b4-7e99c02c4a25/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17994605/44f1107a-6b5a-11e6-81cf-32ab880f83a3.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17994605/44f1107a-6b5a-11e6-81cf-32ab880f83a3.png)
https://cloud.githubusercontent.com/assets/2068130/17994605/44f1107a-6b5a-11e6-81cf-32ab880f83a3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17994612/53ee8a26-6b5a-11e6-90e4-5935df7f68dc.png
