### ISSUE TITLE
Notes Writer - Notes, PDF Annotate & Write Documents

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7757]
**App Name:** Notes Writer - Notes, PDF Annotate & Write Documents
**Bundle ID:** com.knowtilus.rteipadfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=577142302">577142302</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/notes-writer-notes-pdf-annotate/id577142302?mt=8&uo=4">https://itunes.apple.com/us/app/notes-writer-notes-pdf-annotate/id577142302?mt=8&uo=4</a>
**App Version:** 8.1.2
**Seller:** Umanify
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/knowtilus/id392596678?uo=4>© knowtilus</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/94/e8/3c/94e83cda-988b-1901-abcb-85dc283dbf10/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18247343/4725271c-7372-11e6-819a-78a77cbf8dc5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18247343/4725271c-7372-11e6-819a-78a77cbf8dc5.png)
https://cloud.githubusercontent.com/assets/20930745/18247343/4725271c-7372-11e6-819a-78a77cbf8dc5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18247362/59f40b24-7372-11e6-838b-2ec09abac193.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Great! :+1:

**Comment by l8er4now** [comment]
Can we use this same icon for **com.knowtilus.rteipad**, it's the paid version of this app and the icon is the same but the bottom right is a plus sign, this one just looks better (consistent)?
