### ISSUE TITLE
Timeglass - Workout & kitchen timer - Set multiple stopwatch & countdown timers

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7758]
**App Name:** Timeglass - Workout & kitchen timer - Set multiple stopwatch & countdown timers
**Bundle ID:** io.CosmicTeapot.TickTock
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1138584627">1138584627</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/timeglass-workout-kitchen/id1138584627?mt=8&uo=4">https://itunes.apple.com/us/app/timeglass-workout-kitchen/id1138584627?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** COSMIC TEAPOT PTY. LTD.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cosmic-teapot/id1138584626?uo=4>© Cosmic Teapot</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/f8/e6/7a/f8e67ac0-307e-a8be-9b85-fe1935ed287e/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17919331/08f486bc-69cd-11e6-9317-5d6742f3eaf7.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17919331/08f486bc-69cd-11e6-9317-5d6742f3eaf7.png)
https://cloud.githubusercontent.com/assets/2068130/17919331/08f486bc-69cd-11e6-9317-5d6742f3eaf7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17919341/18b8f420-69cd-11e6-9168-98255e9921e9.png
