### ISSUE TITLE
WLPPR — breathtaking images from above

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7759]
**App Name:** WLPPR — breathtaking images from above
**Bundle ID:** com.wlppr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=991182525">991182525</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wlppr-breathtaking-images/id991182525?mt=8&uo=4">https://itunes.apple.com/us/app/wlppr-breathtaking-images/id991182525?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Konstantin Kiselyov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/konstantin-kiselyov/id942568917?uo=4>© Konstantin Kiselyov</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/f8/e1/06/f8e1065e-40d5-ec33-141e-8dd82501cfce/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18618517/a9b81210-7de8-11e6-83e6-b9f5c76f053b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18618517/a9b81210-7de8-11e6-83e6-b9f5c76f053b.png)
https://cloud.githubusercontent.com/assets/20930745/18618517/a9b81210-7de8-11e6-83e6-b9f5c76f053b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18618528/df1f5242-7de8-11e6-83f0-76b85b256d50.png
