### ISSUE TITLE
Papers.co - HD Wallpaper for iPhone and iPad

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7760]
**App Name:** Papers.co - HD Wallpaper for iPhone and iPad
**Bundle ID:** co.papers.Papers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=963687014">963687014</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/papers.co-hd-wallpaper-for/id963687014?mt=8&uo=4">https://itunes.apple.com/us/app/papers.co-hd-wallpaper-for/id963687014?mt=8&uo=4</a>
**App Version:** 2.0.8
**Seller:** Jude H
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jude-h/id963687013?uo=4>© Jude H</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple49/v4/3d/9a/bd/3d9abdad-9307-31fd-e570-e16b6b1d86b1/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18698776/109c4eca-7fcd-11e6-9b67-2ed8abae4ae8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18246919/49d83146-736f-11e6-9d85-36c99be99130.png)
https://cloud.githubusercontent.com/assets/20930745/18246919/49d83146-736f-11e6-9d85-36c99be99130.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18246932/5c419692-736f-11e6-9b22-4cb4fac73a41.png

**Comment by dreamnet** [comment]
Jsust some corner rounding...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18698776/109c4eca-7fcd-11e6-9b67-2ed8abae4ae8.png)
https://cloud.githubusercontent.com/assets/2068130/18698776/109c4eca-7fcd-11e6-9b67-2ed8abae4ae8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18698778/1eb6198c-7fcd-11e6-884b-0726f1ea8760.png
