### ISSUE TITLE
Bundlr

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7761]
**App Name:** Bundlr
 **Bundle ID:** com.cpdigitaldarkroom.bundlr
 **Version:** 0.0.2
 **iTunes ID:** none (Cydia app)
 **Original Artwork:** 
 <img src="http://i.imgur.com/bitTyf8.png" width="150" height="150" />
 **Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17982407/f8269992-6b07-11e6-9000-8e2cdd8a386e.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17982407/f8269992-6b07-11e6-9000-8e2cdd8a386e.png)
https://cloud.githubusercontent.com/assets/2068130/17982407/f8269992-6b07-11e6-9000-8e2cdd8a386e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17982419/071a57cc-6b08-11e6-9221-b293fe3e38b8.png
