### ISSUE TITLE
Free VPN Proxy by Betternet | Unlimited VPN for Wifi Hotspot Security | Best VPN to Secure and Protect Privacy

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7762]
**App Name:** Free VPN Proxy by Betternet | Unlimited VPN for Wifi Hotspot Security | Best VPN to Secure and Protect Privacy
**Bundle ID:** com.betternet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=946659216">946659216</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/free-vpn-proxy-by-betternet/id946659216?mt=8&uo=4">https://itunes.apple.com/us/app/free-vpn-proxy-by-betternet/id946659216?mt=8&uo=4</a>
**App Version:** 3.3.1
**Seller:** Betternet Technologies Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/betternet-technologies-inc./id975476381?uo=4>© Betternet Technologies Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/6e/fc/05/6efc0542-9e78-000b-6ceb-e7bf99229c61/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13483942/18021330/4fd2f540-6bef-11e6-84ea-985d9a1c7055.png)

**Comment by alpcinar** [comment]
![betternet](https://cloud.githubusercontent.com/assets/13483942/18021330/4fd2f540-6bef-11e6-84ea-985d9a1c7055.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13483942/18021330/4fd2f540-6bef-11e6-84ea-985d9a1c7055.png)

**Comment by dreamnet** [comment]
@alpcinar Jup, fine for me. :+1:
