### ISSUE TITLE
Background Eraser - SuperImpose Photo Editor & Cut Out Image Outline

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7763]
**App Name:** Background Eraser - SuperImpose Photo Editor & Cut Out Image Outline
**Bundle ID:** kr.co.noonus.BackgroundEraser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=815072622">815072622</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/background-eraser-superimpose/id815072622?mt=8&uo=4">https://itunes.apple.com/us/app/background-eraser-superimpose/id815072622?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** SUNWOONG JANG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sunwoong-jang/id515224445?uo=4>© SUNWOONG JANG</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple69/v4/e4/f5/ca/e4f5cae4-1512-146f-01d8-4f12d48e72e3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18408569/8e15fa06-7733-11e6-8abd-e23de9ae24bf.png)

**Comment by 2Qt2beStr8** [comment]
... only a try ... someone have to make a better one 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18246727/d1306778-736d-11e6-8014-ffaa79be5479.png)
https://cloud.githubusercontent.com/assets/20930745/18246727/d1306778-736d-11e6-8014-ffaa79be5479.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18246740/e97e2bee-736d-11e6-93d4-2a9aabaace3b.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 That's not so bad... I wait a view days and if no one does a better one, I take it.

**Comment by Anuskuss** [comment]
@dreamnet Not trying to be an Arschloch but it's **few** not **view** :smile:

**Comment by dreamnet** [comment]
@Anuskuss Ups... :laughing:

**Comment by 2Qt2beStr8** [comment]
Ich hab es trotzdem verstanden :-)

**Comment by ivanov007** [comment]
@2Qt2beStr8 I think yours are ok, just try to make the eraser's lines a little thicker

**Comment by 2Qt2beStr8** [comment]
I tried my best , but it is not better :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18408451/7afddd9c-7730-11e6-831e-0484b5e1114e.png)
https://cloud.githubusercontent.com/assets/20930745/18408451/7afddd9c-7730-11e6-831e-0484b5e1114e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18408455/936986d8-7730-11e6-9175-81f550c43301.png

**Comment by dreamnet** [comment]
Just some small changes:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18408569/8e15fa06-7733-11e6-8abd-e23de9ae24bf.png)
https://cloud.githubusercontent.com/assets/2068130/18408569/8e15fa06-7733-11e6-8abd-e23de9ae24bf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18408572/9eeb2540-7733-11e6-9a5f-9212beeaddf3.png
@2Qt2beStr8 Good work! :+1:
