### ISSUE TITLE
vSSH Lite

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7764]
**App Name:** vSSH Lite
**Bundle ID:** com.velestar.vssh.lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=535055496">535055496</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vssh-lite/id535055496?mt=8&uo=4">https://itunes.apple.com/us/app/vssh-lite/id535055496?mt=8&uo=4</a>
**App Version:** 1.11.1
**Seller:** Velestar Private Enterprise
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/velestar-private-enterprise/id356280337?uo=4>© Velestar Private Enterprise</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple49/v4/c0/e6/a8/c0e6a82b-6353-43da-99bf-9281d4fe9143/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17994062/d74b1272-6b55-11e6-852f-58071cbaf445.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17994062/d74b1272-6b55-11e6-852f-58071cbaf445.png)
https://cloud.githubusercontent.com/assets/2068130/17994062/d74b1272-6b55-11e6-852f-58071cbaf445.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17994071/e5460ada-6b55-11e6-9171-84c97eb5916c.png
