### ISSUE TITLE
TOR-Powered Onion Browser - For Anonymous Browsing

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#7765]
**App Name:** TOR-Powered Onion Browser - For Anonymous Browsing
**Bundle ID:** com.juwel.TorBrowser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1125965631">1125965631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tor-powered-onion-browser/id1125965631?mt=8&uo=4">https://itunes.apple.com/us/app/tor-powered-onion-browser/id1125965631?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Md. Khairul Islam Bhuiyan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/md.-khairul-islam-bhuiyan/id1108435105?uo=4>© Md. Khairul Islam Bhuiyan</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/4b/26/ae/4b26aeb5-32dd-b295-ae37-d6ed298eb942/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229854/33acd63e-7288-11e6-8c35-ca9bf915ad76.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229854/33acd63e-7288-11e6-8c35-ca9bf915ad76.png)
https://cloud.githubusercontent.com/assets/20930745/18229854/33acd63e-7288-11e6-8c35-ca9bf915ad76.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18229851/fc158d60-7287-11e6-8263-2d058b7470b9.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229866/fe8e90b8-7288-11e6-8db8-6679cf5b521d.png)
https://cloud.githubusercontent.com/assets/20930745/18229866/fe8e90b8-7288-11e6-8db8-6679cf5b521d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18229867/14e7f8c2-7289-11e6-9440-97c61e8753a1.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 First one is fine. :+1:
