### ISSUE TITLE
Lookout – Security, Backup and Missing Device

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7768]
**App Name:** Lookout – Security, Backup and Missing Device
**Bundle ID:** com.flexilis.security
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=434893913">434893913</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lookout-security-backup-missing/id434893913?mt=8&uo=4">https://itunes.apple.com/us/app/lookout-security-backup-missing/id434893913?mt=8&uo=4</a>
**App Version:** 4.4.8
**Seller:** Lookout, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lookout-inc./id433698101?uo=4>© Lookout, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple62/v4/21/cc/79/21cc79d5-6887-799c-98ab-b2d7236d7a48/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13483942/18022426/8117a562-6bf7-11e6-9433-f5d2ede92299.png)

**Comment by alpcinar** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/13483942/18022426/8117a562-6bf7-11e6-9433-f5d2ede92299.png)

https://cloud.githubusercontent.com/assets/13483942/18022426/8117a562-6bf7-11e6-9433-f5d2ede92299.png

Source:
https://cloud.githubusercontent.com/assets/13483942/18022432/94fda220-6bf7-11e6-8434-7709daa0f60d.png

**Comment by boxermansr** [comment]
wow that was fast, thanks :) one of the two remaindered unthemed apps on my device now themed.
