### ISSUE TITLE
Gravity Swap

### ISSUE THREAD

**Issue by CouleeApps** [glasklart/hd#7769]
**App Name:** Gravity Swap
**Bundle ID:** com.Technospirits.pop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=715737529">715737529</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gravity-swap/id715737529?mt=8&uo=4">https://itunes.apple.com/us/app/gravity-swap/id715737529?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Technospirits LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/technospirits/id379836863?uo=4>© Technospirits</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple6/v4/52/46/ff/5246ffcb-ad72-664e-af07-44aa08c71f0a/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18399819/428ce2e4-76d3-11e6-838c-d81e6607f7cc.png)

**Comment by CouleeApps** [comment]
Really at a loss with this one. I've tried these:
![gravityswap1](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/18028998/ed92bb5c-6c59-11e6-9f98-5c243f42e3e6.png)
https://cloud.githubusercontent.com/assets/711973/18028998/ed92bb5c-6c59-11e6-9f98-5c243f42e3e6.png
Source: https://cloud.githubusercontent.com/assets/711973/18029001/ed96cb16-6c59-11e6-8258-65afb8d20e42.png

![gravityswap2](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/18028997/ed926864-6c59-11e6-992b-8f7ee815ab55.png)
https://cloud.githubusercontent.com/assets/711973/18028997/ed926864-6c59-11e6-992b-8f7ee815ab55.png
Source: https://cloud.githubusercontent.com/assets/711973/18028999/ed9657e4-6c59-11e6-8aa4-2498766046b2.png

![gravityswap3](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/18029000/ed9692fe-6c59-11e6-940f-6ad57d325677.png)
https://cloud.githubusercontent.com/assets/711973/18029000/ed9692fe-6c59-11e6-940f-6ad57d325677.png
Source: https://cloud.githubusercontent.com/assets/711973/18029002/ed9edacc-6c59-11e6-92f0-2e6e33c825ef.png

**Comment by ivanov007** [comment]
@CouleeApps maybe the middle one but just one of the corners white, also can you make the corners round (there's a round corner shape layer on the template file)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18246111/b82efe28-7369-11e6-95e5-d95e32f7510b.png)
https://cloud.githubusercontent.com/assets/20930745/18246111/b82efe28-7369-11e6-95e5-d95e32f7510b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18246128/cd0949c0-7369-11e6-8110-853217578d11.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18256353/853ecd68-73b4-11e6-8c70-c0c8e9fa9d64.png)
https://cloud.githubusercontent.com/assets/2068130/18256353/853ecd68-73b4-11e6-8c70-c0c8e9fa9d64.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18256355/953dafd6-73b4-11e6-9657-6ec68ff05aed.png
Strange to do icon... :thought_balloon:

**Comment by Trubbel** [comment]
What about just the arrow then?

**Comment by dreamnet** [comment]
@Trubbel Yes, I think that's the best idea. :bulb: :+1: 
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18399819/428ce2e4-76d3-11e6-838c-d81e6607f7cc.png)
https://cloud.githubusercontent.com/assets/2068130/18399819/428ce2e4-76d3-11e6-838c-d81e6607f7cc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18399829/5231087e-76d3-11e6-8568-10cf260c380f.png
