### ISSUE TITLE
Couple - Relationship App for Two

### ISSUE THREAD

**Issue by xapher19** [glasklart/hd#777]
**App Name:** Couple - Relationship App for Two
**Bundle ID:** com.tenthbit.Juliet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=503663173">503663173</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/couple-relationship-app-for/id503663173?mt=8&uo=4">https://itunes.apple.com/us/app/couple-relationship-app-for/id503663173?mt=8&uo=4</a>
**App Version:** 1.9.9
**Seller:** TenthBit Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tenthbit-inc./id503663176?uo=4>© TenthBit Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/12/61/a2/1261a245-b28e-9db0-ca33-d3d2f40944ff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408704/218e6f4c-92c4-11e6-8a97-f7b21af50161.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408704/218e6f4c-92c4-11e6-8a97-f7b21af50161.png)
https://cloud.githubusercontent.com/assets/20930745/19408704/218e6f4c-92c4-11e6-8a97-f7b21af50161.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19408711/302b9214-92c4-11e6-8e39-b18c83a91c3d.png
