### ISSUE TITLE
Grid Dash

### ISSUE THREAD

**Issue by CouleeApps** [glasklart/hd#7770]
**App Name:** Grid Dash
**Bundle ID:** com.Technospirits.geometryrun
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=847698810">847698810</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grid-dash/id847698810?mt=8&uo=4">https://itunes.apple.com/us/app/grid-dash/id847698810?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Technospirits LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/technospirits/id379836863?uo=4>© Technospirits</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple/v4/21/c0/ff/21c0ffab-6b1c-745a-5644-f1b72ad4625d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18227305/452fcd0c-7220-11e6-8aca-01c291bad979.png)

**Comment by CouleeApps** [comment]
![griddash](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/711973/18029086/66984362-6c5c-11e6-9a85-f928cca406f1.png)
https://cloud.githubusercontent.com/assets/711973/18029086/66984362-6c5c-11e6-9a85-f928cca406f1.png
Original: https://cloud.githubusercontent.com/assets/711973/18029085/669038ca-6c5c-11e6-8b67-7c4a56e1c95a.png

**Comment by dreamnet** [comment]
@CouleeApps Looks fine, but maybe it's better to do just the pyramid without the background. Good work anyway. :+1:

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18227305/452fcd0c-7220-11e6-8aca-01c291bad979.png)
https://cloud.githubusercontent.com/assets/20930745/18227305/452fcd0c-7220-11e6-8aca-01c291bad979.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18227308/60cdc776-7220-11e6-96bf-b361e828e965.png

**Comment by CouleeApps** [comment]
I would have gone for thicker lines but this works
