### ISSUE TITLE
Tubex

### ISSUE THREAD

**Issue by coolstar** [glasklart/hd#7771]
**App Name**: Tubex -  Videos and Music for YouTube
**Bundle ID**: com.baslas.tubex
**iTunes ID**: 939906112
**iTunes URL**: https://itunes.apple.com/us/app/tubex-videos-music-for-youtube/id939906112?mt=8
**App Version**: 2.91
**Seller**: Baslas Lian
**Supported Devices**: All devices running iOS 7.0 or later (iPhone, iPad, iPod touch)
**Original Artwork**: 
![image](https://cloud.githubusercontent.com/assets/1431548/18029441/e9a6cb44-6c4c-11e6-9663-8a5938c58fd6.png)

Accepted Artwork:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18030446/7fa6b640-6cb6-11e6-9074-5561a58e9a90.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18030446/7fa6b640-6cb6-11e6-9074-5561a58e9a90.png)
https://cloud.githubusercontent.com/assets/10730122/18030446/7fa6b640-6cb6-11e6-9074-5561a58e9a90.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18030445/7f90213c-6cb6-11e6-8fb9-4f2ca64d56a8.png

**Comment by dreamnet** [comment]
@Trubbel Oh yeah! :+1:
