### ISSUE TITLE
No new icon commits to master until this issue is closed

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#7772]
@glasklart/feature-contributors Because I'm checking if we can use Anemone's -large method for Glasklart, there will be no new icon commits to the master until I'm closing this issue.

If all runs fine, there will be a new icon template (180x180px, drawing area 118x118px, **without baseplate**). There will also be a new, 180x180px icon preview. 

All looks good at the moment (beside a small glitch in Anemone that is very hard to recognize), but I need to do some more testing.

In the meanwhile, contributions can be made as usual.

**Comment by coolstar** [comment]
Test theme looked good here, after a small update to anemone  (1.1-397) to fix the underlay sizing

**Comment by dreamnet** [comment]
@coolstar Yes, all fine now - Thanks a lot! :+1:

**Comment by dreamnet** [comment]
All commits for 5.0 are made - Closing.
