### ISSUE TITLE
Super VoiceMail

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7773]
**App Name:** Super VoiceMail
 **Bundle ID:** org.hacx.supervoicemail
 **Version:** 1.11
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/10730122/18030244/696b694a-6caf-11e6-8f2c-d9e6eb73c243.png" width="180" height="180" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18594059/735a0378-7c3e-11e6-87f1-c1564532ffcb.png)

**Comment by Trubbel** [comment]
Not sure I like my attempt on this one, but here's a [higher resolution](https://cloud.githubusercontent.com/assets/10730122/18030278/921b77e4-6cb0-11e6-96a5-07847e209778.png) if anyone else wanna give it a shot.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18030288/c2fa5d94-6cb0-11e6-826f-9d5c809de32e.png)
https://cloud.githubusercontent.com/assets/10730122/18030288/c2fa5d94-6cb0-11e6-826f-9d5c809de32e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18030289/c2fe70be-6cb0-11e6-9c36-068f27916096.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18593994/2fbea33a-7c3e-11e6-9632-1c5e773ebc98.png)
https://cloud.githubusercontent.com/assets/20930745/18593994/2fbea33a-7c3e-11e6-9632-1c5e773ebc98.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18594011/40a8b730-7c3e-11e6-8767-2e27326131fd.png

**Comment by Trubbel** [comment]
@2Qt2beStr8 I like it. :+1:

**Comment by 2Qt2beStr8** [comment]
@Trubbel thank you :-)
