### ISSUE TITLE
Getting ready for Release 5.0

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#7774]
Now I have done enough testing on iPhone 6 and 6+ and I think I can say that we can go up to version 5.0 of Glasklart. 5.0 will use 180x180px icons that will automatically resized to the correct size using Anemone's -large method.

The Good's:
- Theme size will be reduced to ~ 50MB.
- The baseplate will be automatically added to the icons (as in the old times).
- iPhone 6 Plus is supported out of the box.

The Bad's:
- We will loose ~ 3750 (older) icons where we have no source - but this is also some kind of "cleanup".

@glasklart/maintainers Any other thoughts?

**Comment by Trubbel** [comment]
I'm just glad that I don't have to download the **@3x** from the website now. :smiley: 
I think it's pretty good as well that we get rid of these icons without any sources, most of them are probably out of date as well. I'm also sure we will get those 3,000 icons back in no time!

**Comment by quantum8** [comment]
A cleanup will be good for sure. Any missing ones can be recreated through the issue system, or users can install the old version as a stopgap.

**Comment by alpcinar** [comment]
Do we have the list of older icons?

**Comment by dreamnet** [comment]
@alpcinar Puh, I have to write a scipt for that... let's see...

**Comment by CouleeApps** [comment]
You could probably salvage a lot with an automated svg converter. Just a thought

**Comment by dreamnet** [comment]
@alpcinar Here it is: [Missing_Sources.txt](https://github.com/glasklart/hd/files/440892/Missing_Sources.txt)
@CouleeApps How should this work?

**Comment by CouleeApps** [comment]
Not certain on what you'd use, but i know there are tools that create a reasonable svg out of a bitmap. With some imagemagick you could strip the baseplate from the source missing icons and then pipe that into an svg creator. Probably would have to manually review icons to make sure the svgs actually look reasonable, but the script part doesn't sound too bad.

**Comment by dreamnet** [comment]
@CouleeApps I am using Adobe Illustrator - no chance to get a nice looking svg from a 120x120px Glasklart icon. But if someone else would give it a try.....

**Comment by dreamnet** [comment]
OK, we definitly do this - Closing.
