### ISSUE TITLE
Icon Template v5.02

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#7775]
When using Anemone's -large metod, we need a new Glasklart icon template.
So here it is: **[Glasklart_Icon_Template_v5.02.zip](https://github.com/glasklart/hd/files/457354/Glasklart_Icon_Template_v5.02.zip)**

The template has now 180x180px, the icon area in the center is 118x118px. **The baseplate is not needed anymore**, it will be added automatically on the device.

The preview script is ready for use with the new template.

Example:
![v5.02](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18284583/d6ae8bbe-746a-11e6-9e56-267c7a2ba023.png)
https://cloud.githubusercontent.com/assets/2068130/18284583/d6ae8bbe-746a-11e6-9e56-267c7a2ba023.png

**Comment by dreamnet** [comment]
@ all icon contributors: There where some small "glitches" in the icon template v5.0 - please download v5.01 (above).
Don't worry about the icons you already made, I correct them.

**Comment by Trubbel** [comment]
Alright. :+1:

**Comment by dreamnet** [comment]
New icon template can be downloaded in the future from [the WIKI](https://github.com/glasklart/hd/wiki/Icon-Creation-Resources).

**Comment by Anuskuss** [comment]
@dreamnet Two ideas:
1. Why didn't you include a glas underlay in the PSD? It would help visualize your icon.
2. When I drop my source in the smart object, it actually scales to 99.99% and X/Y of 513px. It should be 100% and 512px. I don't know if it's my image or your smart object which is wrong (source is 1024px).

**Comment by dreamnet** [comment]
@Anuskuss 
1. I have revoved der baseplate from the template to not confuse people - but adding it to the preview layer is a good idea.
2. Nothing is wrong. That's the way Photoshop works or if you wan't a Photoshop issue. As far as i know, there is no way to  automatically resize and center the source in the smart object. You have to do this manually - but that's not a lot of work.

**Comment by dreamnet** [comment]
Icon template updated to v5.0.2. Nothing has changed, except the preview background - I have added the baseplate to it.

**Comment by ivanov007** [comment]
@dreamnet also it will be nice to have a rounded corners shape template, I always end up adding it to the templates I download as a new layer

**Comment by dreamnet** [comment]
@ivanov007 I am not 100% sure if I understand what you mean, but corner rounding should be done in the source file (180px radius in a 1024x1024px image), not in the template.
Do you have an example for me? Also, please keep in mind that the templates should be as simple as possible.

**Comment by Trubbel** [comment]
I do it this way as well, I upscale the source files with **Illustrator** and then import it to **Photoshop** to use the rounded corner shape template _(if needed)_, mostly because I have no idea how to do it in **Illustrator** but it have worked so far for me.

**Comment by dreamnet** [comment]
@Trubbel You mean something like this:
[Glasklart_Icon_Template_v5.02_Smart_test.zip](https://github.com/glasklart/hd/files/457555/Glasklart_Icon_Template_v5.02_Smart_test.zip)
:question:

**Comment by Trubbel** [comment]
Oh no, I misunderstood. I thought we were talking about this, 
https://www.dropbox.com/s/7hejzazac9qcbhn/source_template.psd?dl=0

Sorry haha.. :laughing:

**Comment by ivanov007** [comment]
well in the end both are the same, just different way to do it, I've used both with no problem, I just say that this will save some time since what I normally do is save the template just the psd template with the new icons and not the source files
