### ISSUE TITLE
Things to do for Release 5.0

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#7776]
- [x] Generate 180x180px Glasklart icons from the existing icon sources. 
- [x] Overwork `iPhoneUnderlay` and `iPhoneUnderlaySpringBoard` images in `Glasklart Icons.theme/AnemoneEffects`.
- [x] Remade `ClockIconBackgrounds` in `Glasklart Icons.theme/Bundles/com.apple.springboard`.
- [x] Remove all @2x icons and add the created 180x180px icons with -large.png.
- [x] Remove obsolete (Winterboard and ThemeLib) code from `Glasklart Icons.theme/Info.plist`.
- [x] Remove obsolete (Winterboard and ThemeLib) code from the Badges `Info.plist`'s.
- [x] Make a new Glasklart Icon Template (v5.01).
- [x] Overwork the Folders theme.
- [x] Do all the commits.
- [x] Drink an ice cold beer. :beer:
- [x] Try to find the answer to the ultimate question of life, the universe and everything (got it, it's 42). :laughing:
- [x] Overwork the Folders theme (not happy with it) :thought_balloon: 
- [x] Test the master.
- [x] Update [my website](https://glasklarthd.dreamnet.at).
- [x] Drink another ice cold beer and smoke a cigarette. :beers: :smoking:
- [x] Release 5.0.
- [x] Be happy. :stuck_out_tongue_winking_eye:

**Comment by lex325** [comment]
Just updated glasklart to newest version. Now my theme is all screwed up. I lost so many themed icons. And my calendar icon is messed up. What happened??  Please fix this!! It looks terrible!

**Comment by dreamnet** [comment]
@lex325 I know. Please check #7738.

**Comment by dreamnet** [comment]
@glasklart/maintainers Can someone please test the actual master on iPhone 6 Plus? Please tell me what you think and pleas post a screenshot of an open folder. THX!

**Comment by Trubbel** [comment]
@dreamnet The theme looks good for me as far as I can tell right now.

Screenshot of an opened [folder](https://cloud.githubusercontent.com/assets/10730122/18035594/eec569e8-6d58-11e6-9c3b-ed0aa5f1c308.png).

**Comment by dreamnet** [comment]
@Trubbel Thank you, I check the share sheet.

**Comment by dreamnet** [comment]
@Trubbel Share sheet updated, should be fine now.

**Comment by Trubbel** [comment]
@dreamnet Yes, looks good now! :beers:

**Comment by dreamnet** [comment]
@Trubbel Thanks, testing should be done.

**Comment by dreamnet** [comment]
Uh, I think I have to remade all -large icons and commit them again... tomorrow. :sleeping: :zzz:

**Comment by dreamnet** [comment]
All -large icons are updated and commited.

**Comment by Trubbel** [comment]
@dreamnet What was the issue?

**Comment by dreamnet** [comment]
@Trubbel Little changes in the Glasklart effect in the icon template.

**Comment by lex325** [comment]
Hi guys...

I downloaded the new update today but my folder theme is still messed up. It starts with the theme but the vanishes. I'm using an iPhone 6 Plus. 

I have included pictures. 

This is normal before update:



This is now after update:



Does anyone have any idea what is wrong??

**Comment by Trubbel** [comment]
@lex325 I don't see any images?

**Comment by dreamnet** [comment]
@lex325 This is for Release 5.0, please comment in #7767.

**Comment by lex325** [comment]
This is the view I get when using the newest version of glasklart 4.40 with an open folder. Something is wrong. I have iPhone 6 Plus. I have share sheet selected. Am I doing something wrong?
![image](https://cloud.githubusercontent.com/assets/10226407/18109645/92607cf2-6f0a-11e6-98c6-fb16a9b4b54d.png)

It used to look like this using glasklart folders option before the 4.40 update:

![image](https://cloud.githubusercontent.com/assets/10226407/18109693/d232edba-6f0a-11e6-8f77-9b60fea6f193.png)

**Comment by l8er4now** [comment]
I know I submit a shit ton of requests and have been going through my stuff and noticed some of the older submissions aren't updated to -large is there a plan to get those updated or is it going to be submit a request to update the icon?

**Comment by boxermansr** [comment]
Ok, I think I've got the hang of the 5.0 build now. I got the hd-master and have it on my device, however as @l8er4now states, there are a few icons that are not themed anymore -- with that said, do we update the older issue/requests for those apps, or submit them as new? I've got a total of 12 at present that are no longer themed.

Thanks for all the hard work, it's much appreciated, in case you're not told this often enough (to everyone who contributes - I would, but I'm lazy, and also just don't have time) =(

**Comment by l8er4now** [comment]
With the recent news of Apple removing dead apps and actually cleaning up the store, my suggestion is just submit new requests as needed. There are going to be tons of apps removed and no sense in spending time updating icons for apps that are going to exist. 

How icons are in the collection now that no longer exist?

**Comment by boxermansr** [comment]
All of the ones that I have missing are still active ones. I submitted new requests for the ones that didn't have an issue already open, and the ones that are/were already posted as an issue (a few were a few years old), I wasn't sure if I needed to post in that thread, requesting an update or not.

**Comment by l8er4now** [comment]
That's exactly what I've done so far. If the issue exists for it if been commenting with the new icon and that it needs updating and if the issue doesn't exist creating a new. 

I've been going through everything and have done 15 or 20 so far, but got a bunch more to go through.

**Comment by boxermansr** [comment]
I guess I'll do the same with the ones that already have opened issues. I only had six that weren't submitted at all, and another 6 that had older/closed/inactive posts (but still active and available apps).

**Comment by l8er4now** [comment]
My problem is that I hoard apps and have 620+ installed and have a large number that either aren't made or need updating and don't want to flood the issues. Going to be a while before I get everything posted.

**Comment by boxermansr** [comment]
Wow, that's a ton of apps, lol. I think I have about 60ish or so -- and I could probably get rid of 1/4 of them, but I use them a couple of times, and then if I delete them have to end up downloading them again when I do need them, so I just keep them around, hah. 

I updated the threads for the whooping six apps that need to be updated; funny that they weren't already included as they're updated frequently.

**Comment by lex325** [comment]
Wow! I thought I was bad. I have 265 themes and 87 not themes for a total of 352. 

With 620+, I think you got us all beat! That's amazing! :)

**Comment by Anuskuss** [comment]
@dreamnet I would feel safer if we solve the remaining issues before we release 5.0 and get a broken release.

For me, everything works fine with 4.40 except for this folder bug:
[**Rename .txt to .mov**](https://github.com/glasklart/hd/files/454115/glasbug.txt)

**Device:** iPhone 6 - iOS 8.4

**Comment by dreamnet** [comment]
@Anuskuss The folder bug will be better in 5.0 (I played around hours with the folder background radius). But this is mainly an Anemone bug.

**Comment by Anuskuss** [comment]
Can you give me a file which will fix it or do we have to wait for coolstar?

**Comment by dreamnet** [comment]
@Anuskuss Can't give you a file... you can [compare the changes I made between release 4.40 and the actual master](https://github.com/glasklart/hd/commit/7e6c5bb33b90281c420f0b8de10f88279bc9fb95)...
But the folder icon still flashes if you close an open folder. I think this can only fixed by @coolstar.

**Comment by dreamnet** [comment]
@Trubbel You have a 6 Plus, right? If so, can you do me a favor?
I need the original native iOS9 app icons in 180x180px - I have only a iPhone 6, with contains only the 120x120px icons...
I need them for my Website - for this (native) apps:
- [ ] AppStore (iOS9)
- [ ] Calculator (iOS9)
- [ ] Camera (iOS9)
- [ ] Compass (iOS9)
- [ ] Game Center (iOS9)
- [ ] Weather (iOS9)
- [ ] Preferences (iOS9)
- [ ] Safari (iOS9)
- [ ] Phone (iOS9)
- [ ] Mail (iOS9)
- [ ] Photos (iOS9)
- [ ] VoiceMemos (iOS9)
- [ ] Clock (iOS9)
- [ ] Calendar (iOS9)
- [ ] Stocks (iOS9)
- [ ] Notes (iOS9)
- [ ] Messages (iOS9)
- [ ] Contacts (iOS9)
- [ ] Reminders (iOS9)
- [ ] Videos (iOS9)
- [ ] Music (iOS9)
- [ ] Facetime (iOS9)
- [ ] Wallet (iOS9) - Passbook on iOS7+8
- [ ] Health (iOS9)
- [ ] Pangu
- [ ] Tips (iOS9)
- [ ] Apple Watch
- [ ] Fitness (iOS9)
- [ ] News (iOS9)
- [ ] HomeKit (iOS9)
- [ ] iCloud Drive (iOS9)
- [ ] Feedback Assistant
Maybe you can extract them from your device and send it to me per mail or put them on the Dropbox?
Thank's a lot!

**Comment by Trubbel** [comment]
@dreamnet [Here](https://www.dropbox.com/s/4rnwzbi9on5snkn/iOS9.rar?dl=0) you go, let me know if I missed anything.

I'm gonna go get some :zzz: now.

**Comment by dreamnet** [comment]
@Trubbel Loos fine! 👍 😄

**Comment by dreamnet** [comment]
Version 5.0 will be submitted this weekend to the modmyi repo. Await a big ammout of icon request in the next weeks. 😅

**Comment by Trubbel** [comment]
Wish I could "react" to your comment with a beer. :smiley:

**Comment by dreamnet** [comment]
5.0 is in the pipeline... 😸
