### ISSUE TITLE
Magic Mansion

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7778]
**App Name:** Magic Mansion
**Bundle ID:** com.nitrome.magicmansion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1123605369">1123605369</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/magic-mansion/id1123605369?mt=8&uo=4">https://itunes.apple.com/us/app/magic-mansion/id1123605369?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Nitrome
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nitrome/id568079484?uo=4>© Nitrome</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple60/v4/7c/70/3b/7c703b5b-d39d-1565-c9a4-5254cb3fe9c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18036949/969458ea-6d78-11e6-878c-029226d6d288.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18036194/a6a1e6bc-6d64-11e6-9b76-4a2a0292c6b5.png)
https://cloud.githubusercontent.com/assets/10730122/18036194/a6a1e6bc-6d64-11e6-9b76-4a2a0292c6b5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18036195/a6a482fa-6d64-11e6-842e-db044ea98775.png

**Comment by dreamnet** [comment]
@Trubbel Wohoho! :+1:
