### ISSUE TITLE
Proven Job Search

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7779]
**App Name:** Proven Job Search
**Bundle ID:** com.proven.candidates
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=804849890">804849890</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/proven-job-search/id804849890?mt=8&uo=4">https://itunes.apple.com/us/app/proven-job-search/id804849890?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** TicTasks, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/proven.com/id542747676?uo=4>© Proven.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple71/v4/2b/71/fa/2b71fae5-5f91-7dd7-76ef-589376b57e41/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18194088/75e1c1d2-70e3-11e6-8e1a-ff438ad7ad64.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193801/3fcca42e-70e1-11e6-89ad-e761c9a58784.png)
https://cloud.githubusercontent.com/assets/2068130/18193801/3fcca42e-70e1-11e6-89ad-e761c9a58784.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18193805/509c2252-70e1-11e6-8822-2fedaa970185.png
