### ISSUE TITLE
Record Keeper - Time Logger, Personal Time Tracker & Time Sheet

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7780]
**App Name:** Record Keeper - Time Logger, Personal Time Tracker & Time Sheet
**Bundle ID:** jp.co.picup.Log-24
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1090728028">1090728028</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/record-keeper-time-logger/id1090728028?mt=8&uo=4">https://itunes.apple.com/us/app/record-keeper-time-logger/id1090728028?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Picup Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/picup-inc./id955448004?uo=4>© Picup Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple71/v4/bf/d6/35/bfd635ca-89e1-7649-adff-106e29188232/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18233870/30ec36f8-72f4-11e6-842e-2a4033c96ca4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229788/e2bf58c0-7285-11e6-812a-44bd95fb67eb.png)
https://cloud.githubusercontent.com/assets/20930745/18229788/e2bf58c0-7285-11e6-812a-44bd95fb67eb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18229793/04552bcc-7286-11e6-8cb7-5b0b733c4c99.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18233870/30ec36f8-72f4-11e6-842e-2a4033c96ca4.png)
https://cloud.githubusercontent.com/assets/2068130/18233870/30ec36f8-72f4-11e6-842e-2a4033c96ca4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18233871/40183366-72f4-11e6-8859-95afb1dc695b.png
