### ISSUE TITLE
picTrove Pro - image search across multiple services

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7781]
**App Name:** picTrove Pro - image search across multiple services
**Bundle ID:** com.traversient.pixellentpro.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=433016309">433016309</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pictrove-pro-image-search/id433016309?mt=8&uo=4">https://itunes.apple.com/us/app/pictrove-pro-image-search/id433016309?mt=8&uo=4</a>
**App Version:** 1.8.15
**Seller:** Traversient Tech LLP
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/traversient-tech-llp/id963653269?uo=4>© Traversient Tech LLP</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple18/v4/1e/06/6f/1e066f45-8ac4-2641-ef6b-2ffdc7aee76a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18378584/1bcf0a5c-766e-11e6-8bcc-7be12c06139f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18231143/c9781b60-72b0-11e6-93c1-6f28e62153d2.png)
https://cloud.githubusercontent.com/assets/20930745/18231143/c9781b60-72b0-11e6-93c1-6f28e62153d2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18231148/dd7df828-72b0-11e6-988b-d23a3e9baa69.png

**Comment by Trubbel** [comment]
I like it, just fixed it up a bit. Good job though!

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18378584/1bcf0a5c-766e-11e6-8bcc-7be12c06139f.png)
https://cloud.githubusercontent.com/assets/10730122/18378584/1bcf0a5c-766e-11e6-8bcc-7be12c06139f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18378583/1bb5f440-766e-11e6-88ee-3a476af65df9.png
