### ISSUE TITLE
Urlaubspiraten

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7782]
**App Name:** Urlaubspiraten
**Bundle ID:** com.holidaypirates.urlaubspiraten
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=564850309">564850309</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/urlaubspiraten/id564850309?mt=8&uo=4">https://itunes.apple.com/us/app/urlaubspiraten/id564850309?mt=8&uo=4</a>
**App Version:** 2.0.16
**Seller:** Holidaypirates GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/holidaypirates-gmbh/id564850312?uo=4>© Holidaypirates GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple20/v4/b4/f1/f8/b4f1f847-2429-40ae-8752-6ffd741281d8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18256258/23f2ab16-73b3-11e6-895c-5b5edf7d43e3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18252244/da2e5838-738d-11e6-97e4-5a5d4972622d.png)
https://cloud.githubusercontent.com/assets/20930745/18252244/da2e5838-738d-11e6-97e4-5a5d4972622d.png


Source:
https://cloud.githubusercontent.com/assets/20930745/18252168/9932bf68-738d-11e6-989e-55d00fa5e10b.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18256258/23f2ab16-73b3-11e6-895c-5b5edf7d43e3.png)
https://cloud.githubusercontent.com/assets/2068130/18256258/23f2ab16-73b3-11e6-895c-5b5edf7d43e3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18256262/32c84cb8-73b3-11e6-9729-d94b8454ecf4.png
