### ISSUE TITLE
GoEuro – train, bus, flight

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7785]
**App Name:** GoEuro – train, bus, flight
**Bundle ID:** com.goeuro.ios.ronald
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=885372509">885372509</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/goeuro-train-bus-flight/id885372509?mt=8&uo=4">https://itunes.apple.com/us/app/goeuro-train-bus-flight/id885372509?mt=8&uo=4</a>
**App Version:** 1.7.2
**Seller:** GoEuro Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/goeuro/id885372512?uo=4>© GoEuro</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple22/v4/55/60/fb/5560fbf2-e66e-0728-8d80-f782f7ab00e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18117429/1308e954-6f4f-11e6-99bf-a8ca736b6cf8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18117429/1308e954-6f4f-11e6-99bf-a8ca736b6cf8.png)
https://cloud.githubusercontent.com/assets/2068130/18117429/1308e954-6f4f-11e6-99bf-a8ca736b6cf8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18117433/23a99c04-6f4f-11e6-9730-b11c7479fc69.png
