### ISSUE TITLE
WiFi FTP

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7786]
**App Name:** WiFi FTP
**Bundle ID:** com.savysoda.WiFiFTP
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338206448">338206448</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wifi-ftp/id338206448?mt=8&uo=4">https://itunes.apple.com/us/app/wifi-ftp/id338206448?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Savy Soda Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/savy-soda/id295726257?uo=4>© Savy Soda</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple/v4/89/9b/35/899b3508-1fde-c113-d197-0cf3839852d2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18608509/8484629e-7ceb-11e6-83c2-1932f1f273d2.png)

**Comment by 2Qt2beStr8** [comment]
not perfect ... but i can't do it better :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18608509/8484629e-7ceb-11e6-83c2-1932f1f273d2.png)
https://cloud.githubusercontent.com/assets/20930745/18608509/8484629e-7ceb-11e6-83c2-1932f1f273d2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18608531/2b44530a-7cec-11e6-9858-2ee9e5d0f738.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Looks fine! 👍
