### ISSUE TITLE
Scoopshot

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7788]
**App Name:** Scoopshot
**Bundle ID:** com.scoopshot.Scoopshot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417797386">417797386</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scoopshot/id417797386?mt=8&uo=4">https://itunes.apple.com/us/app/scoopshot/id417797386?mt=8&uo=4</a>
**App Version:** 5.0.5
**Seller:** P2S Media Group Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/p2s-media-group-inc./id417797389?uo=4>© P2S Media Group Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple7/v4/06/5f/d2/065fd2e4-9d98-52e6-e89d-63546d386793/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416213/c8720c8c-780d-11e6-9f58-7182328461b6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18231011/88894434-72ac-11e6-8d19-e06a05eacf56.png)
https://cloud.githubusercontent.com/assets/20930745/18231011/88894434-72ac-11e6-8d19-e06a05eacf56.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18231015/a01f2a3c-72ac-11e6-887e-e75fa0f6e0c6.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18231030/645053cc-72ad-11e6-927d-2259a8f10dd7.png)
https://cloud.githubusercontent.com/assets/20930745/18231030/645053cc-72ad-11e6-927d-2259a8f10dd7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18231031/7a2edc54-72ad-11e6-9849-6b5e8e7aac65.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18408976/55cc1cd8-773e-11e6-9bab-71e54a0a2d07.png)
https://cloud.githubusercontent.com/assets/20930745/18408976/55cc1cd8-773e-11e6-9bab-71e54a0a2d07.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18408980/6a09d96a-773e-11e6-9381-6389d8304efd.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Like it! Just removed the litte black part in the middle of the lens.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18416213/c8720c8c-780d-11e6-9f58-7182328461b6.png)
https://cloud.githubusercontent.com/assets/2068130/18416213/c8720c8c-780d-11e6-9f58-7182328461b6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18416216/d827b73a-780d-11e6-862e-ea124294d34f.png
