### ISSUE TITLE
GAY FM

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7789]
**App Name:** GAY FM
**Bundle ID:** com.liquidairlab.gayfm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=320238575">320238575</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gay-fm/id320238575?mt=8&uo=4">https://itunes.apple.com/us/app/gay-fm/id320238575?mt=8&uo=4</a>
**App Version:** 9.3.0
**Seller:** Silvacast GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/silvacast-gmbh/id718080489?uo=4>© Silvacast GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple20/v4/96/91/a5/9691a514-08db-fcba-e560-693a79a4856a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193546/ec2cc918-70de-11e6-9610-d29018c45d9c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193546/ec2cc918-70de-11e6-9610-d29018c45d9c.png)
https://cloud.githubusercontent.com/assets/2068130/18193546/ec2cc918-70de-11e6-9610-d29018c45d9c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18193554/fa3b0808-70de-11e6-981d-7f329aa8231d.png
