### ISSUE TITLE
Quick Drafts - Notes, Errands and Shopping List

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#779]
**App Name:** Quick Drafts - Notes, Errands and Shopping List
**Bundle ID:** Quick-Drafts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=569838247">569838247</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quick-drafts-notes-errands/id569838247?mt=8&uo=4">https://itunes.apple.com/us/app/quick-drafts-notes-errands/id569838247?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Sebastian Obentheuer
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/sebastian-obentheuer/id569838250?uo=4>© Sebastian Obentheuer</a>
**Supported Devices:** iPadThirdGen, iPhone5, iPadThirdGen4G, iPadMini4G, iPadMini, iPhone5s, iPhone6Plus, iPad23G, iPhone5c, iPadFourthGen, iPhone4, iPhone4S, iPadFourthGen4G, iPhone6, iPodTouchFifthGen, iPad2Wifi
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple3/v4/75/e4/c5/75e4c567-ec56-8944-e12e-bc8a09617194/mzl.yynmddzn.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8394263/f350d4f4-1d2f-11e5-98f0-a55cb8924bf2.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8394263/f350d4f4-1d2f-11e5-98f0-a55cb8924bf2.png)
https://cloud.githubusercontent.com/assets/2068130/8394263/f350d4f4-1d2f-11e5-98f0-a55cb8924bf2.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8394265/027552ca-1d30-11e5-8c6f-bf309a6ea34c.png
