### ISSUE TITLE
Wifi Passwords List

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7792]
**App Name:** Wifi Passwords List
**Bundle ID:** com.ashapps.wifipasswordslist
**Version:** 1,0.1-1
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/21006428/18099419/bbe61808-6ee6-11e6-994c-93bfd1317c93.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18233772/43485272-72f0-11e6-8921-bc9395ce49e2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18233772/43485272-72f0-11e6-8921-bc9395ce49e2.png)
https://cloud.githubusercontent.com/assets/2068130/18233772/43485272-72f0-11e6-8921-bc9395ce49e2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18233773/54c8d490-72f0-11e6-8f1b-d58a46b7c9bf.png
