### ISSUE TITLE
SPB TV

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7793]
**App Name:** SPB TV
**Bundle ID:** com.spbtv.tv.SPB-TV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=480952101">480952101</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spb-tv/id480952101?mt=8&uo=4">https://itunes.apple.com/us/app/spb-tv/id480952101?mt=8&uo=4</a>
**App Version:** 5.9
**Seller:** MobiWorld Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/spb-tv/id480952104?uo=4>© SPB TV</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple62/v4/54/75/5d/54755db6-a39c-5764-0d55-eb3dc558b014/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18233528/f72d48d0-72e9-11e6-9be8-41fdc04f96cc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18231371/9d29f1e8-72b8-11e6-8b82-580702e10b61.png)
https://cloud.githubusercontent.com/assets/20930745/18231371/9d29f1e8-72b8-11e6-8b82-580702e10b61.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18231378/b34ef306-72b8-11e6-9319-1324a1780716.png
