### ISSUE TITLE
Emergency Call

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7794]
**App Name:** Emergency Call
**Bundle ID:** com.yourcompany.Notruf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=325778554">325778554</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/emergency-call/id325778554?mt=8&uo=4">https://itunes.apple.com/us/app/emergency-call/id325778554?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Solid Apps GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/solid-apps-gmbh/id291237871?uo=4>© Solid Apps GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple69/v4/8e/68/d0/8e68d04e-70b6-95cd-08f9-992d1eb465b0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193486/64a48c42-70de-11e6-9380-772b289877dc.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193486/64a48c42-70de-11e6-9380-772b289877dc.png)
https://cloud.githubusercontent.com/assets/2068130/18193486/64a48c42-70de-11e6-9380-772b289877dc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18193494/74122ff4-70de-11e6-8981-04046af8b857.png
