### ISSUE TITLE
Cocktails - The Original 

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7795]
**App Name:** Cocktails - The Original
**Bundle ID:** com.swissDevelopment.icocktails
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=287329476">287329476</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/cocktails-the-original/id287329476?uo=4">https://apps.apple.com/us/app/cocktails-the-original/id287329476?uo=4</a>
**App Version:** 4.5.6
**Seller:** Swiss-Development GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/swiss-development-gmbh/id287329479?uo=4">© Swiss-Development GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/10/fc/4c/10fc4c3e-1cfc-18e4-b716-881714284443/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60370573-411e7e00-99f7-11e9-85f2-cc5ceee59f49.png)

**Comment by 2Qt2beStr8** [comment]
i don't like the original icon 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18608182/bd5080ca-7ce2-11e6-8340-6fdfd46f15cd.png)
https://cloud.githubusercontent.com/assets/20930745/18608182/bd5080ca-7ce2-11e6-8340-6fdfd46f15cd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18608186/d407a6fe-7ce2-11e6-8e8a-97e5b8deb3ce.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Me too. Good work! 👍

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60370573-411e7e00-99f7-11e9-85f2-cc5ceee59f49.png)
https://user-images.githubusercontent.com/2068130/60370573-411e7e00-99f7-11e9-85f2-cc5ceee59f49.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60370599-51cef400-99f7-11e9-966c-456a605dfa6c.png
