### ISSUE TITLE
MONIN Ultimate Cocktails

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7796]
**App Name:** MONIN Ultimate Cocktails
**Bundle ID:** com.monin.Monin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=410273477">410273477</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/monin-ultimate-cocktails/id410273477?mt=8&uo=4">https://itunes.apple.com/us/app/monin-ultimate-cocktails/id410273477?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Georges Monin SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/monin/id410273480?uo=4>© MONIN</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple3/v4/8c/00/09/8c000999-fbed-f705-7420-4fba835cc212/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18608024/fbee31e2-7cdd-11e6-85c1-578990349053.png)

**Comment by 2Qt2beStr8** [comment]
.. i think this looks better than the original icon ;-)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18608024/fbee31e2-7cdd-11e6-85c1-578990349053.png)
https://cloud.githubusercontent.com/assets/20930745/18608024/fbee31e2-7cdd-11e6-85c1-578990349053.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18608028/121b8aa0-7cde-11e6-8f53-8cdb2b31906f.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes, it looks defintly better...
@Deti1959 What do you think?

**Comment by Deti1959** [comment]
I like it! It looks really nice 👍

**Comment by dreamnet** [comment]
@Deti1959 @2Qt2beStr8 OK, Taken!
