### ISSUE TITLE
apodiscounter Apotheke

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7797]
**App Name:** apodiscounter Apotheke
**Bundle ID:** de.apodiscounter.ApoDis
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=383562236">383562236</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/apodiscounter-apotheke/id383562236?mt=8&uo=4">https://itunes.apple.com/us/app/apodiscounter-apotheke/id383562236?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** Apologistics GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apologistics-gmbh/id383562239?uo=4>© Apologistics GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple20/v4/62/1d/90/621d90eb-5eba-1c8e-6133-9280e1b2f6c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10730122/18135190/534edcba-6fa1-11e6-8038-12f81053253a.png)

**Comment by Trubbel** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10730122/18135190/534edcba-6fa1-11e6-8038-12f81053253a.png)
https://cloud.githubusercontent.com/assets/10730122/18135190/534edcba-6fa1-11e6-8038-12f81053253a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18135189/5335e0b6-6fa1-11e6-80eb-7841bde33b1f.png
