### ISSUE TITLE
Favored Recipes: Baking

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7798]
**App Name:** Favored Recipes: Baking
**Bundle ID:** com.apollo.backen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519041827">519041827</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/favored-recipes-baking/id519041827?mt=8&uo=4">https://itunes.apple.com/us/app/favored-recipes-baking/id519041827?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Apollo Medien GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apollo-medien-gmbh/id371989915?uo=4>© Apollo Medien GmbH</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple/v4/d9/04/c2/d904c20d-30cf-5e0b-c96a-a899697f3ad4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18255805/9c9ced48-73ad-11e6-9f28-a8ab64137fea.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18251763/5398295e-738b-11e6-9fc5-079ef35c1827.png)
https://cloud.githubusercontent.com/assets/20930745/18251763/5398295e-738b-11e6-9fc5-079ef35c1827.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18251774/6c536594-738b-11e6-9dff-7b30c0f029d2.png
