### ISSUE TITLE
Programm Manager

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7799]
**App Name:** Programm Manager
**Bundle ID:** de.telekom.Programm-Manager
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327915934">327915934</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/programm-manager/id327915934?mt=8&uo=4">https://itunes.apple.com/de/app/programm-manager/id327915934?mt=8&uo=4</a>
**App Version:** 3.0.14
**Seller:** Telekom Deutschland GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/telekom-deutschland-gmbh/id930125248?uo=4>© Telekom Deutschland GmbH</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/d3/95/b3/d395b38b-e8ae-8b72-712e-01f9776492b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18379200/78481a64-7671-11e6-9068-36ee877df92c.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18379200/78481a64-7671-11e6-9068-36ee877df92c.png)
https://cloud.githubusercontent.com/assets/10730122/18379200/78481a64-7671-11e6-9068-36ee877df92c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18379199/78457cf0-7671-11e6-91a3-22f2fff5b7d0.png
