### ISSUE TITLE
FooDDB

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7800]
**App Name:** FooDDB
**Bundle ID:** de.triphoenix.fddb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444464364">444464364</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fooddb/id444464364?mt=8&uo=4">https://itunes.apple.com/us/app/fooddb/id444464364?mt=8&uo=4</a>
**App Version:** 1.5.3
**Seller:** Dennis Bliefernicht
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dennis-bliefernicht/id444464367?uo=4>© Dennis Bliefernicht</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple5/v4/d3/c6/57/d3c657cc-7551-718d-2061-fbfa90f0b0a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18233911/4e9999c4-72f5-11e6-8433-18b833d40cb3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18233911/4e9999c4-72f5-11e6-8433-18b833d40cb3.png)
https://cloud.githubusercontent.com/assets/20930745/18233911/4e9999c4-72f5-11e6-8433-18b833d40cb3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18233913/620c965a-72f5-11e6-816a-1d0fe8107b13.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Jup, like it. :+1:
