### ISSUE TITLE
Fluege.de – günstig buchen

### ISSUE THREAD

**Issue by Deti1959** [glasklart/hd#7801]
**App Name:** Fluege.de – günstig buchen
**Bundle ID:** de.unister.fluege
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=665795633">665795633</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fluege-de-g%C3%BCnstig-buchen/id665795633?uo=4">https://apps.apple.com/us/app/fluege-de-g%C3%BCnstig-buchen/id665795633?uo=4</a>
**App Version:** 4.6.0
**Seller:** Invia Flights Germany GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/invia-flights-germany-gmbh/id1225625268?uo=4">© Invia Flights Germany GmbH</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/78/9e/e5/789ee54d-839a-219b-352d-c60749824c6a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400401-9384a980-9b73-11e9-9b07-c3d876608364.png)

**Comment by Trubbel** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10730122/18135022/b71cb9b6-6fa0-11e6-9916-61de992eb9e7.png)
https://cloud.githubusercontent.com/assets/10730122/18135022/b71cb9b6-6fa0-11e6-9916-61de992eb9e7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18135021/b7008caa-6fa0-11e6-8476-3e98e8105a19.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400401-9384a980-9b73-11e9-9b07-c3d876608364.png)
https://user-images.githubusercontent.com/20930745/60400401-9384a980-9b73-11e9-9b07-c3d876608364.png

Source:
https://user-images.githubusercontent.com/20930745/60400402-941d4000-9b73-11e9-94ea-173cf39f88c9.png
