### ISSUE TITLE
Folder problems with the new update (v4.40)

### ISSUE THREAD

**Issue by lex325** [glasklart/hd#7802]
Hi guys. I'm going to try and resubmit my pictures. Here's the one before the update 4.40. The folder looks great. This is what I am used to seeing:
![image](https://cloud.githubusercontent.com/assets/10226407/18099852/6664512a-6ee0-11e6-92c0-cd29cd2d0656.png)

Now I am seeing it like this after updating to 4.40:
![image](https://cloud.githubusercontent.com/assets/10226407/18099891/8bf46100-6ee0-11e6-9d48-c920dc919c33.png)

Is there a fix for this? I am using glasklart for years since the beginning. I am now on iPhone 6 Plus.

**Comment by dreamnet** [comment]
@lex325 Hm, seems to happen only on 6 Plus.
Please copy [this file](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Folders.theme/Bundles/com.apple.springboard/ANEMFolderBackground%403x.png) to `Library/Themes/Glasklart Folders.theme/com.apple.springboard` (overwrite existing file) and tell me if this helps.

**Comment by lex325** [comment]
Thank you for trying to help. I really appreciate it. Unfortunately, I am currently on vacation in northern Portugal. I have very limited wifi capability here. 

I get back home in the USA on September 9. I'll have to try your file overwrite idea only then unless a fix comes along. Thanks for all your hard work! Love this theme as we all do!

**Comment by lex325** [comment]
Another issue now. It seems like this is never ending. I just downloaded and installed the newest anemone update. After the update my folders change from "glasklart color" and the to black in one second. And all my themed fonts are missing. I was using BytaFont3. Please look at comparison pictures above. 

I don't know what the heck is happening! Can anyone help? Can I revert anemone to a previous version? And if I can revert to a previous version, then how would I do it? This is very frustrating guys. 
![image](https://cloud.githubusercontent.com/assets/10226407/18123260/0c6f00b8-6f65-11e6-8053-c9c5ce29fa1b.png)

**Comment by 2Qt2beStr8** [comment]
Hi,
you can downgrade Anemone in Cydia ... press change and now you can klick to downgrade. 
![image](https://cloud.githubusercontent.com/assets/20930745/18124771/f12d42ba-6f73-11e6-89fa-67638ce505ac.png)

**Comment by dreamnet** [comment]
@lex325 Glasklart does (and will) not theme any fonts. Bytafont conflicts with Anemone. Check [here](https://github.com/AnemoneTeam/Anemone/issues/131).
The open folder background problem is strange - I can't test it, because I don't have a 6 Plus.
@Trubbel Can you help? Does the suggestion I made [above](https://github.com/glasklart/hd/issues/7802#issuecomment-243550533) work?

**Comment by lex325** [comment]
@dreamnet I know Glasklart does not theme any fonts. I've been a  Glasklart user since the very beginning. 

I just found it odd that when upgrading Anemone all my Bytafont fonts got uninstalled. Thank you for the conflict explanation between Bytafont and Anemone. That was something I did not know. I appreciate all the hard work you guys do to the Glasklart theme. I fear it would not exist without you. 

Regarding the folder problem, it opens like normal and then the background just vanishes within a second or less. (This is without the Anenome upgrade)

With the Anemone upgrade the same happens. However instead of vanishing, it turns black. 

Again, I have iPhone 6 Plus in zoomed mode.

**Comment by Trubbel** [comment]
@lex325 You can now install fonts with Anemone.

@dreamnet I use **Small** on **Display Zoom Mode** and this is how the folders look for me with the fix,

![file 31-08-16 17 01 38](https://cloud.githubusercontent.com/assets/10730122/18133912/b110809c-6f9c-11e6-8815-3643354e4d40.png)

**Comment by lex325** [comment]
@Trubbel thank you for the fonts repo. I appreciate it. I'm going to check it out.

**Comment by dreamnet** [comment]
@lex325 @Trubbel Please delete the file `FolderMask@3x.png` in `Library/Themes/Glasklart Folders.theme/Bundles/com.apple.springboard`, respring and tell me if this helps.

**Comment by lex325** [comment]
Just tried it. It did not help

**Comment by Trubbel** [comment]
@dreamnet No difference,

![file 01-09-16 16 23 34](https://cloud.githubusercontent.com/assets/10730122/18170953/81f8a644-7060-11e6-9bac-ff67e5ba409c.png)

**Comment by dreamnet** [comment]
OK, I'm giving up on this. We can discuss futher after the release of version 5.0.
