### ISSUE TITLE
Geekbench 4

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7803]
**App Name:** Geekbench 4
**Bundle ID:** com.primatelabs.geekbench4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1130770356">1130770356</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/geekbench-4/id1130770356?mt=8&uo=4">https://itunes.apple.com/us/app/geekbench-4/id1130770356?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** Primate Labs Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/primate-labs-inc./id683676890?uo=4>© Primate Labs Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple22/v4/61/f1/61/61f16173-8301-7476-562c-fb3b1992b9cf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10730122/18134827/0d0aeb0a-6fa0-11e6-91a9-8c1803eb1465.png)

**Comment by Trubbel** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/10730122/18134827/0d0aeb0a-6fa0-11e6-91a9-8c1803eb1465.png)
https://cloud.githubusercontent.com/assets/10730122/18134827/0d0aeb0a-6fa0-11e6-91a9-8c1803eb1465.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18134826/0cf62800-6fa0-11e6-9a7d-0599afdaee47.png

**Comment by boxermansr** [comment]
Thanks -- for some reason this looks odd on my device (its not grey like the rest of the icons -- its black).. Any ideas?

![ss](https://cloud.githubusercontent.com/assets/3781692/18135255/8a8d083e-6f5e-11e6-86f0-3348d4a9cdcd.PNG)

**Comment by dreamnet** [comment]
@boxermansr That's because we are working on version 5.0 of Glasklart, and for v5.0 we have changed the way Glasklart icons are made (now they are 180x180px, have no baseplate and they are using Anemone's -large method). If you can't wait for Version 5.0, use this icon:
![2x](https://cloud.githubusercontent.com/assets/2068130/18156248/3633c64e-7015-11e6-8ea4-9e87a4286ca6.png)

**Comment by boxermansr** [comment]
Got it. So will the new release have the icons showing as this one does (black with a clear background - if so that, to me looks mega cooler), or will they all still have the greyish background to them?

Thanks!

**Comment by dreamnet** [comment]
@boxermansr They will still have the baseplate, but in v5.0 and up the baseplate will be added automatic on the device. That's Glasklart.
