### ISSUE TITLE
Imaging Edge Mobile

### ISSUE THREAD

**Issue by DoctorDri** [glasklart/hd#7804]
**App Name:** Imaging Edge Mobile
**Bundle ID:** jp.co.sony.playmemoriesmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489191124">489191124</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/imaging-edge-mobile/id489191124?uo=4">https://apps.apple.com/us/app/imaging-edge-mobile/id489191124?uo=4</a>
**App Version:** 7.1.0
**Seller:** Sony Imaging Products & Solutions Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sony-imaging-products-solutions-inc/id1291827132?uo=4">© Sony Imaging Products & Solutions Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/7f/2d/a4/7f2da4de-fc1d-d68c-4a25-6d88d4a90e41/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60618413-6dab0f00-9dd6-11e9-978f-684272e7cc99.png)

**Comment by dreamnet** [comment]
@DoctorDri Please read our WIKI on [how to submit an icon request](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request). I'm correcting your request above.

**Comment by DoctorDri** [comment]
Hi! It wasn't a request, I was uploading the finished icon.

**Comment by Trubbel** [comment]
@DoctorDri You are suppose to follow the guidelines on how to submit an icon request and then post separate post with your icon submission. See [this](https://github.com/glasklart/hd/issues/5753) - and if we like your icon we _(the Glasklart maintainers)_ edit your issue with the icon.

**Comment by DoctorDri** [comment]
OK. I have technical doubts about how to create the icon correctly. My icons are more whitey than the ones on the theme. I'm using the iPhone 6 Plus template and the old guide for old icons, but the result is very brilliant white compared to other icons. Is there any updated guide o tips about how to do them?

**Comment by dreamnet** [comment]
@DoctorDri Please download the latest [icon template](https://github.com/glasklart/hd/wiki/Icon-Creation-Resources). Check also our [WIKI](https://github.com/glasklart/hd/wiki) on how to [contribute an icon](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon). If you have any further questions, feel free to ask.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18233786/a2bb8530-72f0-11e6-8076-25f3075b03d3.png)
https://cloud.githubusercontent.com/assets/20930745/18233786/a2bb8530-72f0-11e6-8076-25f3075b03d3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18233789/bd8ee2f8-72f0-11e6-81c1-cbe78291ce60.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Hmm... Yes.

**Comment by 2Qt2beStr8** [comment]
@dreamnet maybe someone other can make a better one

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes - I take your icon for this time - we can always reopen this issue if someone sumbmits a better icon.

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60618413-6dab0f00-9dd6-11e9-978f-684272e7cc99.png)
https://user-images.githubusercontent.com/2068130/60618413-6dab0f00-9dd6-11e9-978f-684272e7cc99.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60618440-7d2a5800-9dd6-11e9-8175-229707377350.png
