### ISSUE TITLE
ran | Bundesliga, NFL, Boxen & Sport News + Videos

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7805]
**App Name:** ran | Bundesliga, NFL, Boxen & Sport News + Videos
**Bundle ID:** de.sevenoneintermedia.ran
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=332534830">332534830</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/ran-bundesliga-nfl-boxen-sport/id332534830?mt=8&uo=4">https://itunes.apple.com/de/app/ran-bundesliga-nfl-boxen-sport/id332534830?mt=8&uo=4</a>
**App Version:** 5.7.4
**Seller:** ProSiebenSat.1 Digital GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/prosiebensat.1-digital-gmbh/id293225283?uo=4>© ProSiebenSat.1 Digital GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple60/v4/bd/ec/e1/bdece1ae-4b35-a469-a386-b498c6591d7c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193263/22f64062-70dc-11e6-84b0-e08f138e5819.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193263/22f64062-70dc-11e6-84b0-e08f138e5819.png)
https://cloud.githubusercontent.com/assets/2068130/18193263/22f64062-70dc-11e6-84b0-e08f138e5819.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18193277/34852da2-70dc-11e6-8503-1ffde5704488.png
