### ISSUE TITLE
ProSieben – Kostenloses Live TV Programm mit Stars, Shows, Hollywood Blockbustern, Serien und großer Mediathek

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7806]
**App Name:** ProSieben – Kostenloses Live TV Programm mit Stars, Shows, Hollywood Blockbustern, Serien und großer Mediathek
**Bundle ID:** de.prosiebensat1digital.prosieben
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1123546533">1123546533</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/prosieben-kostenloses-live/id1123546533?mt=8&uo=4">https://itunes.apple.com/de/app/prosieben-kostenloses-live/id1123546533?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** ProSiebenSat.1 Digital GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/prosiebensat.1-digital-gmbh/id293225283?uo=4>© ProSiebenSat.1 Digital GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple71/v4/dc/67/33/dc673339-5428-4438-3d6f-e154e035ccad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18231258/e84db654-72b4-11e6-948a-d5ffe06e28a8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18226898/202d73bc-7214-11e6-8b3f-1f5f8bc4eb1b.png)
https://cloud.githubusercontent.com/assets/20930745/18226898/202d73bc-7214-11e6-8b3f-1f5f8bc4eb1b.png


Source:
https://cloud.githubusercontent.com/assets/20930745/18226899/386e5de2-7214-11e6-90d1-6c28874163d9.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18231258/e84db654-72b4-11e6-948a-d5ffe06e28a8.png)
https://cloud.githubusercontent.com/assets/20930745/18231258/e84db654-72b4-11e6-948a-d5ffe06e28a8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18231260/fe43156c-72b4-11e6-9953-c1d627279eb7.png
