### ISSUE TITLE
Galileo

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7807]
**App Name:** Galileo
**Bundle ID:** de.sevenoneintermedia.galileovideolexikon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=436765197">436765197</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/galileo/id436765197?mt=8&uo=4">https://itunes.apple.com/de/app/galileo/id436765197?mt=8&uo=4</a>
**App Version:** 3.1.5
**Seller:** ProSiebenSat.1 Digital GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/prosiebensat.1-digital-gmbh/id293225283?uo=4>© ProSiebenSat.1 Digital GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple20/v4/0e/32/6d/0e326d6c-8428-ae3d-3071-ac639008383e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18361238/62d27d52-7601-11e6-8550-58791ba26a24.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229923/1cd19e88-728b-11e6-9173-5471d6cfc28d.png)
https://cloud.githubusercontent.com/assets/20930745/18229923/1cd19e88-728b-11e6-9173-5471d6cfc28d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18229925/2fa38440-728b-11e6-8a97-a320d2cf6a90.png

**Comment by 2Qt2beStr8** [comment]
or this one ... but it's not really perfect

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18230363/6f7c5ae4-7298-11e6-922c-4b6be5f95b75.png)
https://cloud.githubusercontent.com/assets/20930745/18230363/6f7c5ae4-7298-11e6-922c-4b6be5f95b75.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18230367/873973a6-7298-11e6-8dd5-e9b9366db58a.png

**Comment by Anuskuss** [comment]
Hmm :thought_balloon:

**Comment by 2Qt2beStr8** [comment]
@Anuskuss what hmm?

**Comment by Anuskuss** [comment]
@2Qt2beStr8 Can't decide which I like more...

**Comment by dreamnet** [comment]
I think the word "Galileo" should be white.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18361238/62d27d52-7601-11e6-8550-58791ba26a24.png)
https://cloud.githubusercontent.com/assets/20930745/18361238/62d27d52-7601-11e6-8550-58791ba26a24.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18361261/75d6eda2-7601-11e6-9fc5-f548dbc426a5.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Nice! :+1:
