### ISSUE TITLE
SAT.1 – Kostenloses Live TV mit Crime Serien, Filmen, Shows, Comedy, großer Mediathek und aktuellen Service-Themen

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7808]
**App Name:** SAT.1 – Kostenloses Live TV mit Crime Serien, Filmen, Shows, Comedy, großer Mediathek und aktuellen Service-Themen
**Bundle ID:** de.prosiebensat1digital.sat1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1123550029">1123550029</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/sat.1-kostenloses-live-tv/id1123550029?mt=8&uo=4">https://itunes.apple.com/de/app/sat.1-kostenloses-live-tv/id1123550029?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** ProSiebenSat.1 Digital GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/prosiebensat.1-digital-gmbh/id293225283?uo=4>© ProSiebenSat.1 Digital GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/a8/99/c2/a899c2a1-2355-e56b-22d4-2693b8514cee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18233646/ff5310e6-72ec-11e6-9564-60c1097dd5b4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18230725/dd86ae48-72a4-11e6-9ad1-0b2e2c48286b.png)
https://cloud.githubusercontent.com/assets/20930745/18230725/dd86ae48-72a4-11e6-9ad1-0b2e2c48286b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18230726/f33794e6-72a4-11e6-836c-8db14ffa7f95.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Too big, else good work!
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18233646/ff5310e6-72ec-11e6-9564-60c1097dd5b4.png)
https://cloud.githubusercontent.com/assets/2068130/18233646/ff5310e6-72ec-11e6-9564-60c1097dd5b4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18233648/0d04f01a-72ed-11e6-8436-016caa39bf96.png
