### ISSUE TITLE
ProSieben MAXX – Kostenloses Live TV Programm mit Anime, Sport Entertainment, Dokus, Grill Specials und großer Mediathek

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7809]
**App Name:** ProSieben MAXX – Kostenloses Live TV Programm mit Anime, Sport Entertainment, Dokus, Grill Specials und großer Mediathek
**Bundle ID:** de.prosiebensat1digital.prosiebenmaxx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1123552103">1123552103</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/prosieben-maxx-kostenloses/id1123552103?mt=8&uo=4">https://itunes.apple.com/de/app/prosieben-maxx-kostenloses/id1123552103?mt=8&uo=4</a>
**App Version:** 1.4.4
**Seller:** ProSiebenSat.1 Digital GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/prosiebensat.1-digital-gmbh/id293225283?uo=4>© ProSiebenSat.1 Digital GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple30/v4/a3/00/a2/a300a284-ed31-1e5c-2a5b-f868ae20a6cc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18233571/1a88344c-72eb-11e6-9e08-0f8ff4759213.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18230628/fc69d4fa-72a1-11e6-901c-b253d370d570.png)
https://cloud.githubusercontent.com/assets/20930745/18230628/fc69d4fa-72a1-11e6-901c-b253d370d570.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18230630/146f5002-72a2-11e6-86ea-11a681d9455f.png
