### ISSUE TITLE
kabel eins – Kostenloses Live TV Programm mit Magazinen, Reportagen, Filmen, Serien, Food Sendungen und großer Mediathek

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7810]
**App Name:** kabel eins – Kostenloses Live TV Programm mit Magazinen, Reportagen, Filmen, Serien, Food Sendungen und großer Mediathek
**Bundle ID:** de.prosiebensat1digital.kabeleins
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1123551260">1123551260</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/kabel-eins-kostenloses-live/id1123551260?mt=8&uo=4">https://itunes.apple.com/de/app/kabel-eins-kostenloses-live/id1123551260?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** ProSiebenSat.1 Digital GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/prosiebensat.1-digital-gmbh/id293225283?uo=4>© ProSiebenSat.1 Digital GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple71/v4/08/fa/13/08fa138a-c9ac-6a75-7e69-7148cb68a29e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18225827/fbe31490-71c2-11e6-8391-b791f5805353.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18212278/e7cd8244-7107-11e6-9ad3-4a229e31471c.png)
https://cloud.githubusercontent.com/assets/3090247/18212278/e7cd8244-7107-11e6-9ad3-4a229e31471c.png
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18212280/e7d6d434-7107-11e6-8151-6a984cf38a90.png)
https://cloud.githubusercontent.com/assets/3090247/18212280/e7d6d434-7107-11e6-8151-6a984cf38a90.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18212279/e7d3a994-7107-11e6-8e77-6af1729f3c54.png
https://cloud.githubusercontent.com/assets/3090247/18212277/e7cbb194-7107-11e6-9905-d2d7cd1a2ba7.png

**Comment by Anuskuss** [comment]
@ivanov007 Hmm, normally I try to avoid borders... How about the size of the latter without the border?

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18225827/fbe31490-71c2-11e6-8391-b791f5805353.png)
https://cloud.githubusercontent.com/assets/3090247/18225827/fbe31490-71c2-11e6-8391-b791f5805353.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18225828/fbf30e54-71c2-11e6-96bd-20b193bc7ef3.png

**Comment by Anuskuss** [comment]
I'd take the second one
