### ISSUE TITLE
sixx – Kostenloses Live TV Programm mit Serien, Shows rund um Tattoo, Backen und Kochen, Star-News und großer Mediathek

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7811]
**App Name:** sixx – Kostenloses Live TV Programm mit Serien, Shows rund um Tattoo, Backen und Kochen, Star-News und großer Mediathek
**Bundle ID:** de.prosiebensat1digital.sixx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1123551272">1123551272</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/sixx-kostenloses-live-tv-programm/id1123551272?mt=8&uo=4">https://itunes.apple.com/de/app/sixx-kostenloses-live-tv-programm/id1123551272?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** ProSiebenSat.1 Digital GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/prosiebensat.1-digital-gmbh/id293225283?uo=4>© ProSiebenSat.1 Digital GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple41/v4/78/fa/ef/78faef95-e132-83a3-5318-32f7ff513ce0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193198/8deffcc4-70db-11e6-80ba-012f94f7239f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193198/8deffcc4-70db-11e6-80ba-012f94f7239f.png)
https://cloud.githubusercontent.com/assets/2068130/18193198/8deffcc4-70db-11e6-80ba-012f94f7239f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18193206/9d4e9158-70db-11e6-8f29-0d79c0bf3a7a.png
