### ISSUE TITLE
SAT.1 Gold – Kostenloses Live TV Programm mit Serien- und Filmklassikern, Emotionen und großer Mediathek

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7812]
**App Name:** SAT.1 Gold – Kostenloses Live TV Programm mit Serien- und Filmklassikern, Emotionen und großer Mediathek
**Bundle ID:** de.prosiebensat1digital.sat1gold
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1123553205">1123553205</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/sat.1-gold-kostenloses-live/id1123553205?mt=8&uo=4">https://itunes.apple.com/de/app/sat.1-gold-kostenloses-live/id1123553205?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** ProSiebenSat.1 Digital GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/prosiebensat.1-digital-gmbh/id293225283?uo=4>© ProSiebenSat.1 Digital GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/c4/cc/6c/c4cc6c68-2170-0b6a-71b7-d75c166787d2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18209709/8e0577f6-70fa-11e6-8fd4-483eda3b5a35.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18209709/8e0577f6-70fa-11e6-8fd4-483eda3b5a35.png)
https://cloud.githubusercontent.com/assets/3090247/18209709/8e0577f6-70fa-11e6-8fd4-483eda3b5a35.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18209708/8e0217dc-70fa-11e6-976e-c7eea3229ac4.png
