### ISSUE TITLE
Urbanspoon - Restaurant & Food Reviews

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7813]
**App Name:** Urbanspoon - Restaurant & Food Reviews
**Bundle ID:** com.urbanspoon.urbanspin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284708449">284708449</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/urbanspoon-restaurant-food/id284708449?mt=8&uo=4">https://itunes.apple.com/us/app/urbanspoon-restaurant-food/id284708449?mt=8&uo=4</a>
**App Version:** 3.6
**Seller:** Zomato Media Pvt. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zomato-media-pvt.-ltd./id434613899?uo=4>© Zomato Media Pvt. Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple71/v4/73/70/14/7370144d-64c1-3149-a6e9-cb9a770902b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193019/daba1758-70d9-11e6-8d34-b36b8f42234b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18193019/daba1758-70d9-11e6-8d34-b36b8f42234b.png)
https://cloud.githubusercontent.com/assets/2068130/18193019/daba1758-70d9-11e6-8d34-b36b8f42234b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18193025/e8d9ce0a-70d9-11e6-83f9-1ab44407b4a4.png
