### ISSUE TITLE
iHeartRadio – Free Music & Radio Stations

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7814]
**App Name:** iHeartRadio – Free Music & Radio Stations
**Bundle ID:** com.clearchannel.iheartradio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=290638154">290638154</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iheartradio-free-music-radio/id290638154?mt=8&uo=4">https://itunes.apple.com/us/app/iheartradio-free-music-radio/id290638154?mt=8&uo=4</a>
**App Version:** 6.5.0
**Seller:** iHeartMedia Management Services, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iheartmedia-management-services/id290638157?uo=4>© iHeartMedia Management Services, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple32/v4/9e/ee/ac/9eeeaca4-946c-186b-52aa-5c843b17343f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18192684/bd35b118-70d6-11e6-82d5-ce4f50e406d5.png)

**Comment by l8er4now** [comment]
The one in the collection needs resizing.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18192684/bd35b118-70d6-11e6-82d5-ce4f50e406d5.png)
https://cloud.githubusercontent.com/assets/2068130/18192684/bd35b118-70d6-11e6-82d5-ce4f50e406d5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18192690/cb8ae2ba-70d6-11e6-8a49-fe4ea2116b64.png
