### ISSUE TITLE
Flipboard: Your Social News Magazine

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7815]
**App Name:** Flipboard: Your Social News Magazine
**Bundle ID:** com.flipboard.flipboard-ipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=358801284">358801284</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flipboard-your-social-news/id358801284?mt=8&uo=4">https://itunes.apple.com/us/app/flipboard-your-social-news/id358801284?mt=8&uo=4</a>
**App Version:** 3.3.24
**Seller:** Flipboard, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/flipboard-inc./id358801287?uo=4>© Flipboard Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple19/v4/fe/70/89/fe708913-c77c-5976-d5c2-d62e9ac5c291/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18192850/1a06435c-70d8-11e6-8328-aa2d0e645d40.png)

**Comment by l8er4now** [comment]
The one in the collection needs to be resized.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18192850/1a06435c-70d8-11e6-8328-aa2d0e645d40.png)
https://cloud.githubusercontent.com/assets/2068130/18192850/1a06435c-70d8-11e6-8328-aa2d0e645d40.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18192859/28573ff6-70d8-11e6-9545-c53306caae7d.png
