### ISSUE TITLE
InWallet

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7817]
**App Name:** InWallet
**Bundle ID:** com.inditex.inwallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=613156232">613156232</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/inwallet/id613156232?mt=8&uo=4">https://itunes.apple.com/es/app/inwallet/id613156232?mt=8&uo=4</a>
**App Version:** 2.2.8
**Seller:** Industria de Diseno Textil, S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/es/developer/inditex/id341323285?uo=4>© INDITEX</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple62/v4/98/16/9c/98169c2c-d7ca-6e5a-83f4-795a26c9d437/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18213582/8e65b53a-710e-11e6-8e80-f9a554d43be6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18213582/8e65b53a-710e-11e6-8e80-f9a554d43be6.png)
https://cloud.githubusercontent.com/assets/3090247/18213582/8e65b53a-710e-11e6-8e80-f9a554d43be6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18213583/8e6c3748-710e-11e6-9cb3-6e610b9fa287.png)
