### ISSUE TITLE
Bank of America - Mobile Banking

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7818]
**App Name:** Bank of America - Mobile Banking
**Bundle ID:** com.bankofamerica.BofA
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284847138">284847138</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bank-america-mobile-banking/id284847138?mt=8&uo=4">https://itunes.apple.com/us/app/bank-america-mobile-banking/id284847138?mt=8&uo=4</a>
**App Version:** 7.0.2
**Seller:** Bank of America
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bank-of-america/id284847141?uo=4>© Bank of America</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple18/v4/83/0c/dc/830cdc29-5ad3-45dd-b1ac-23a6d8110f3e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2068130/18232907/e9f6e82a-72d9-11e6-95c6-b52987a18ecd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18223927/76b08948-71c6-11e6-9f44-f000e883562d.png)

Source:
https://cloud.githubusercontent.com/assets/20930745/18223932/8edc7838-71c6-11e6-8531-926b50f01b8e.png

**Comment by boxermansr** [comment]
I think this is missing something (link/source wise)?

**Comment by 2Qt2beStr8** [comment]
Sorry, now you can see the link. 
But i think the Icon is not perfect and someone makes a better one.

**Comment by boxermansr** [comment]
Thanks, the other two (I think) you did were missing the link as well. BTW, looks fine to me, and thanks.

**Comment by 2Qt2beStr8** [comment]
Now all the links are visible:-)

**Comment by ivanov007** [comment]
@2Qt2beStr8 just one thing, your source has white background, it should be transparent

**Comment by 2Qt2beStr8** [comment]
@ivanov007 sorry, this was a mistake ... i changed it

**Comment by dreamnet** [comment]
@2Qt2beStr8 :+1:
