### ISSUE TITLE
Colloquy - IRC Client

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7819]
**App Name:** Colloquy - IRC Client
**Bundle ID:** info.colloquy.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=302000478">302000478</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/colloquy-irc-client/id302000478?mt=8&uo=4">https://itunes.apple.com/us/app/colloquy-irc-client/id302000478?mt=8&uo=4</a>
**App Version:** 1.8.10
**Seller:** Jane Lee
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/colloquy-project/id302000481?uo=4>© Colloquy Project</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple18/v4/d4/48/c0/d448c07d-32ba-52fc-a857-159553b54d11/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18225793/cf801ebc-71c1-11e6-88ec-44f73666f4b9.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18225793/cf801ebc-71c1-11e6-88ec-44f73666f4b9.png)
https://cloud.githubusercontent.com/assets/3090247/18225793/cf801ebc-71c1-11e6-88ec-44f73666f4b9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18225792/cf7ee948-71c1-11e6-8d73-7301cab8a5b1.png
