### ISSUE TITLE
[DUPLICATE of #7820]

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#782]
**Name:** GasBuddy - Find Cheap Gas Prices
**Bundle ID:** com.gasbuddymobile.gasbuddy
**iTunes ID:** 406719683
**Icon Name:** Icon.png | Icon@2x.png
**Artwork URL:** http://i.imgur.com/wDNyl5c.png

I'd greatly appreciate it if someone could fill this request. Thanks!

**Comment by boxermansr** [comment]
new icon as of 9/13/2016.
