### ISSUE TITLE
Capital One Mobile

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7821]
**App Name:** Capital One Mobile
**Bundle ID:** com.capitalone.enterprisemobilebanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407558537">407558537</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/capital-one-mobile/id407558537?mt=8&uo=4">https://itunes.apple.com/us/app/capital-one-mobile/id407558537?mt=8&uo=4</a>
**App Version:** 5.12.0
**Seller:** Capital One Services, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/capital-one/id339644101?uo=4>© Capital One</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple42/v4/7f/07/f7/7f07f712-ae4c-8897-7ffb-0cedb9b16c89/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18225604/081758ea-71bc-11e6-9ae7-a35b5d65cb09.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/18225604/081758ea-71bc-11e6-9ae7-a35b5d65cb09.png)
https://cloud.githubusercontent.com/assets/3090247/18225604/081758ea-71bc-11e6-9ae7-a35b5d65cb09.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/18225605/081a0874-71bc-11e6-9926-e78284e4fc81.png
