### ISSUE TITLE
Citi Mobile®

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7822]
**App Name:** Citi Mobile®
**Bundle ID:** com.citigroup.citimobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=301724680">301724680</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/citi-mobile/id301724680?mt=8&uo=4">https://itunes.apple.com/us/app/citi-mobile/id301724680?mt=8&uo=4</a>
**App Version:** 7.9
**Seller:** Citibank, N.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/citibank/id301724683?uo=4>© Citibank</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple42/v4/87/a6/ad/87a6ad21-7420-2c70-cc12-ca8588a6b5b7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18223786/540095fe-71c2-11e6-857e-2df4f2dd3572.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18223786/540095fe-71c2-11e6-857e-2df4f2dd3572.png)

Source:
https://cloud.githubusercontent.com/assets/20930745/18223792/6572c442-71c2-11e6-85b3-496015bbc082.png
