### ISSUE TITLE
Wells Fargo Mobile

### ISSUE THREAD

**Issue by boxermansr** [glasklart/hd#7823]
**App Name:** Wells Fargo Mobile
**Bundle ID:** com.wf.mobilebanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=311548709">311548709</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wells-fargo-mobile/id311548709?mt=8&uo=4">https://itunes.apple.com/us/app/wells-fargo-mobile/id311548709?mt=8&uo=4</a>
**App Version:** 3.25
**Seller:** Wells Fargo Bank
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wells-fargo/id311548712?uo=4>© Wells Fargo</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple60/v4/0c/92/9c/0c929c9a-4f35-3618-743a-ae46bbefab9f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18223849/4fe7733c-71c4-11e6-8a08-47099e62c04a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18223849/4fe7733c-71c4-11e6-8a08-47099e62c04a.png)

Source:
https://cloud.githubusercontent.com/assets/20930745/18223852/62188e7e-71c4-11e6-8a62-cd7d964faa08.png

**Comment by ivanov007** [comment]
@2Qt2beStr8 gr8 :+1:
