### ISSUE TITLE
The Executive Free

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#7826]
**App Name:** The Executive Free
**Bundle ID:** com.paulstevens.theexecutivefree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=962627697">962627697</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-executive-free/id962627697?mt=8&uo=4">https://itunes.apple.com/us/app/the-executive-free/id962627697?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Riverman Media LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/riverman-media-llc/id396772114?uo=4>© Riverman Media LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple60/v4/63/7a/cb/637acbf2-5c1e-d52f-99be-84be46c58231/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18606489/4a3257d8-7cb2-11e6-90eb-5a3d96148c04.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18606489/4a3257d8-7cb2-11e6-90eb-5a3d96148c04.png)
https://cloud.githubusercontent.com/assets/2068130/18606489/4a3257d8-7cb2-11e6-90eb-5a3d96148c04.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18606491/5d1c386e-7cb2-11e6-82ba-28ac654fd22f.png
