### ISSUE TITLE
Ygolite

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7827]
**App Name:** Ygolite
**Bundle ID:** co.ygopro.Ygolite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1099613981">1099613981</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ygolite/id1099613981?mt=8&uo=4">https://itunes.apple.com/us/app/ygolite/id1099613981?mt=8&uo=4</a>
**App Version:** 1.4.13
**Seller:** Joshua Ennew
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/joshua-ennew/id928862885?uo=4>© Joshua Ennew</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple20/v4/47/f9/66/47f96694-4e94-32c4-9c13-da09028d673d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229380/b016614c-7277-11e6-8f54-de28f074ece3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229380/b016614c-7277-11e6-8f54-de28f074ece3.png)
https://cloud.githubusercontent.com/assets/20930745/18229380/b016614c-7277-11e6-8f54-de28f074ece3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18229385/c685dbec-7277-11e6-9ddd-c1dfbcd69e5a.png
