### ISSUE TITLE
Ygorpo

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7828]
**App Name:** Ygorpo
**Bundle ID:** co.ygopro.Ygopro
**Version:** 1.01
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/7157389/18228223/14ca4e48-7244-11e6-92af-dad37acd919b.jpeg" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Anuskuss** [comment]
**Bigger image:**
<img src="https://cloud.githubusercontent.com/assets/7157389/18228223/14ca4e48-7244-11e6-92af-dad37acd919b.jpeg" width="150" height="150" />

**Comment by dreamnet** [comment]
@Anuskuss Where to get this app? - and what if we use the artwork for [Ygolite](https://itunes.apple.com/at/app/ygolite/id1099613981?mt=8) for it?

**Comment by Anuskuss** [comment]
I lost my jailbreak a while ago (reason why I'm not posting anymore) and I can't remember for sure. I think it was from iEmulators or something - you can decide it. If I have time I will look it up and see if Ygopro even exist anymore.

**Comment by dreamnet** [comment]
OK, So I'm closing this issue - we can always reopen it if we need to add an icon for this app.
