### ISSUE TITLE
Mimo: Learn how to code through interactive tutorials and quizzes!

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7829]
**App Name:** Mimo: Learn how to code through interactive tutorials and quizzes!
**Bundle ID:** com.getmimo.mimo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1133960732">1133960732</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mimo-learn-how-to-code-through/id1133960732?mt=8&uo=4">https://itunes.apple.com/us/app/mimo-learn-how-to-code-through/id1133960732?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Johannes Berger
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/johannes-berger/id548016918?uo=4>© Johannes Berger</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple42/v4/91/10/f1/9110f10e-3375-a6e4-0d4c-d11f77139053/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229409/03341cb0-7279-11e6-8a5e-b836cf0c7a8f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229409/03341cb0-7279-11e6-8a5e-b836cf0c7a8f.png)
https://cloud.githubusercontent.com/assets/20930745/18229409/03341cb0-7279-11e6-8a5e-b836cf0c7a8f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18229411/180003c0-7279-11e6-9a6c-425983549b3a.png
