### ISSUE TITLE
Universal Video Downloader Plus

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7830]
**App Name:** Universal Video Downloader Plus
**Bundle ID:** com.spatrickapps.Universal-Video-Downloader-Plus
**Version:** 2.1.3
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/18233274/ba9d5844-72e2-11e6-955a-ca66b390daae.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18234783/dc4bd7cc-730f-11e6-969d-3203c4a82601.png)

**Comment by 2Qt2beStr8** [comment]
@Anuskuss the original artwork is to small to create a glasklart icon - so i use a other one

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18230604/fddf0072-72a0-11e6-98a8-01d9486dc7ce.png)
https://cloud.githubusercontent.com/assets/20930745/18230604/fddf0072-72a0-11e6-98a8-01d9486dc7ce.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18230609/1145ba16-72a1-11e6-9d3d-672dd4212e27.png

**Comment by Anuskuss** [comment]
@2Qt2beStr8 It's a bit stretched.

**Comment by Anuskuss** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18234783/dc4bd7cc-730f-11e6-969d-3203c4a82601.png) ![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18234789/f18558ca-730f-11e6-88c5-ef44be686c67.png) 
https://cloud.githubusercontent.com/assets/7157389/18234783/dc4bd7cc-730f-11e6-969d-3203c4a82601.png
https://cloud.githubusercontent.com/assets/7157389/18234789/f18558ca-730f-11e6-88c5-ef44be686c67.png

___

Source:
https://cloud.githubusercontent.com/assets/7157389/18234792/09d48aea-7310-11e6-9ad3-0e1079505446.png
https://cloud.githubusercontent.com/assets/7157389/18234795/10487724-7310-11e6-823c-1985e217ac5b.png
