### ISSUE TITLE
paysafecard – pay cash online

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7831]
**App Name:** paysafecard – pay cash online
**Bundle ID:** com.paysafecard.paysafecard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=588324792">588324792</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paysafecard-pay-cash-online/id588324792?mt=8&uo=4">https://itunes.apple.com/us/app/paysafecard-pay-cash-online/id588324792?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** paysafecard.com Wertkarten GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/paysafecard.com-wertkarten/id588324795?uo=4>© paysafecard.com Wertkarten GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple60/v4/42/e6/a7/42e6a7a5-0cd1-4294-37c3-f730e676a028/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229320/2915088a-7275-11e6-921f-fcea8cf175bf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18229320/2915088a-7275-11e6-921f-fcea8cf175bf.png)
https://cloud.githubusercontent.com/assets/20930745/18229320/2915088a-7275-11e6-921f-fcea8cf175bf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18229321/3c506598-7275-11e6-8abf-1037c0e8501a.png
