### ISSUE TITLE
Sabadell Wallet

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#7839]
**App Name:** Sabadell Wallet
**Bundle ID:** com.bancosabadell.SabadellWallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1067226384">1067226384</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sabadell-wallet/id1067226384?mt=8&uo=4">https://itunes.apple.com/us/app/sabadell-wallet/id1067226384?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Banco de Sabadell, S.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/banco-de-sabadell-s.a./id347887641?uo=4>© Banco de Sabadell, S.A.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple49/v4/cb/2d/ce/cb2dce90-fbd9-b15f-da13-aa61c6cc05ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18245766/6113f190-7367-11e6-9bf5-d06fcd47f7b1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18244561/fa4b3636-7360-11e6-87dd-037fcedc6f08.png)
https://cloud.githubusercontent.com/assets/20930745/18244561/fa4b3636-7360-11e6-87dd-037fcedc6f08.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18244578/12eb0f72-7361-11e6-9ec9-2501b3474a91.png

**Comment by dreamnet** [comment]
@grkka OK for you?

**Comment by 2Qt2beStr8** [comment]
or this one:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18245766/6113f190-7367-11e6-9bf5-d06fcd47f7b1.png)
https://cloud.githubusercontent.com/assets/20930745/18245766/6113f190-7367-11e6-9bf5-d06fcd47f7b1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18245783/74944256-7367-11e6-8e00-7c96365b8f72.png

**Comment by grkka** [comment]
Better the second icon, since there is another app from the bank that has the same icon without the word "wallet"
hd/Library/Themes/Glasklart Icons.theme/IconBundles/com.bancosabadell.sabloc-large.png
Thanks! @2Qt2beStr8 @dreamnet

**Comment by dreamnet** [comment]
@grkka Jup, OK.

**Comment by 2Qt2beStr8** [comment]
@dreamnet thank you ... i do my best :-)
