### ISSUE TITLE
Battery Memory System Status Monitor

### ISSUE THREAD

**Issue by allliee** [glasklart/hd#784]
**App Name:** Battery Memory System Status Monitor
**Bundle ID:** com.cactosapp.aai
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=497937231">497937231</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/battery-memory-system-status/id497937231?mt=8&uo=4">https://itunes.apple.com/us/app/battery-memory-system-status/id497937231?mt=8&uo=4</a>
**App Version:** 1.1.7
**Seller:** CHAN UK JEON
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cactos-app/id497937234?uo=4>© Cactos App</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/34/d4/87/34d4872d-89ca-f649-b2ec-f749cf159f4d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19021772/22e09d98-88c9-11e6-93ac-c505d63edd4e.png)

**Comment by Sly-Fi** [comment]
Icon missing from version 5...

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19021772/22e09d98-88c9-11e6-93ac-c505d63edd4e.png)
https://cloud.githubusercontent.com/assets/2068130/19021772/22e09d98-88c9-11e6-93ac-c505d63edd4e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19021776/34761fec-88c9-11e6-9a77-af337ce36443.png
