### ISSUE TITLE
Calculator Pro Elite

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7840]
**App Name:** Calculator Pro Elite
**Bundle ID:** com.cidersoftware.Calculator-Pro-Elite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=782873188">782873188</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calculator-pro-elite/id782873188?mt=8&uo=4">https://itunes.apple.com/us/app/calculator-pro-elite/id782873188?mt=8&uo=4</a>
**App Version:** 3.1.2
**Seller:** Cider Software LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cider-software-llc/id465180756?uo=4>© Cider Software LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/7e/0d/a0/7e0da08f-fbe9-ac1d-aecc-5cc5315ab219/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18251271/9224d2ce-7388-11e6-811e-f5f10431e932.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18251271/9224d2ce-7388-11e6-811e-f5f10431e932.png)
https://cloud.githubusercontent.com/assets/20930745/18251271/9224d2ce-7388-11e6-811e-f5f10431e932.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18251288/a940ff46-7388-11e6-9897-01c7df2b6487.png
