### ISSUE TITLE
Stocktwits

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7841]
**App Name:** Stocktwits
**Bundle ID:** com.stocktwits.StockTwits
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389157776">389157776</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stocktwits/id389157776?uo=4">https://apps.apple.com/us/app/stocktwits/id389157776?uo=4</a>
**App Version:** 4.9.1
**Seller:** StockTwits, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/stocktwits-inc/id389157779?uo=4">© StockTwits Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/23/c8/80/23c8809b-c6a9-4fa8-8fdf-69bf9e9c062f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62837754-934bf380-bc73-11e9-88d1-61f5ececaf76.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18247384/396c2670-7340-11e6-8afe-683e3e4f23b3.png)

https://cloud.githubusercontent.com/assets/3704186/18247384/396c2670-7340-11e6-8afe-683e3e4f23b3.png

https://cloud.githubusercontent.com/assets/3704186/18247386/432a8cba-7340-11e6-8b36-6b40b999ff22.png

**Comment by l8er4now** [comment]
Needs an update

**App Name:** Stocktwits
**Bundle ID:** com.stocktwits.StockTwits
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389157776">389157776</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/stocktwits/id389157776?uo=4">https://apps.apple.com/us/app/stocktwits/id389157776?uo=4</a>
**App Version:** 4.9.0
**Seller:** StockTwits, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/stocktwits-inc/id389157779?uo=4">© StockTwits Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/38/d8/13/38d813ce-4b85-aa15-3ff0-9dd02351903c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62837754-934bf380-bc73-11e9-88d1-61f5ececaf76.png)
https://user-images.githubusercontent.com/2068130/62837754-934bf380-bc73-11e9-88d1-61f5ececaf76.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62837760-a5c62d00-bc73-11e9-96fa-b630b6ffd018.png
