### ISSUE TITLE
Spin Zone: Pro Football News and Fantasy Football Discussion, for NFL Fans

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7843]
**App Name:** Spin Zone: Pro Football News and Fantasy Football Discussion, for NFL Fans
**Bundle ID:** com.fansided.nflspinzone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032085289">1032085289</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spin-zone-pro-football-news/id1032085289?mt=8&uo=4">https://itunes.apple.com/us/app/spin-zone-pro-football-news/id1032085289?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** FanSided LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fansided/id553311969?uo=4>© FanSided</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple18/v4/da/34/2a/da342a14-3040-6e79-362e-109853868964/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18433595/d24575b0-78e8-11e6-9fa0-684de52d0f9b.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18433595/d24575b0-78e8-11e6-9fa0-684de52d0f9b.png)
https://cloud.githubusercontent.com/assets/10730122/18433595/d24575b0-78e8-11e6-9fa0-684de52d0f9b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18433596/d245eb8a-78e8-11e6-9ad9-59d5677cf8d3.png
