### ISSUE TITLE
MyQ Smart Garage Control

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7844]
**App Name:** MyQ Smart Garage Control
**Bundle ID:** com.chamberlain.myq.chamberlain
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=636030203">636030203</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myq-smart-garage-control/id636030203?mt=8&uo=4">https://itunes.apple.com/us/app/myq-smart-garage-control/id636030203?mt=8&uo=4</a>
**App Version:** 3.111
**Seller:** The Chamberlain Group, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-chamberlain-group-inc/id456282562?uo=4">© The Chamberlain Group, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/01/d3/e3/01d3e3f1-ad01-8e38-6e49-ddc5040016b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43989625-050e167e-9d4e-11e8-8058-367afd3b4e78.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18247508/f0c57934-7340-11e6-929e-a5f326d87763.png)

https://cloud.githubusercontent.com/assets/3704186/18247508/f0c57934-7340-11e6-929e-a5f326d87763.png

https://cloud.githubusercontent.com/assets/3704186/18247515/f809329e-7340-11e6-83b4-208621ef050a.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** MyQ Smart Garage Control
**Bundle ID:** com.chamberlain.myq.chamberlain
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=636030203">636030203</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myq-smart-garage-control/id636030203?mt=8&uo=4">https://itunes.apple.com/us/app/myq-smart-garage-control/id636030203?mt=8&uo=4</a>
**App Version:** 3.111
**Seller:** The Chamberlain Group, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-chamberlain-group-inc/id456282562?uo=4">© The Chamberlain Group, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/01/d3/e3/01d3e3f1-ad01-8e38-6e49-ddc5040016b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43989625-050e167e-9d4e-11e8-8058-367afd3b4e78.png)
https://user-images.githubusercontent.com/2068130/43989625-050e167e-9d4e-11e8-8058-367afd3b4e78.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43989626-13439296-9d4e-11e8-8234-c577465fd713.png
