### ISSUE TITLE
Devices – Control for HomeKit

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7845]
**App Name:** Devices – Control for HomeKit
**Bundle ID:** com.linkdesk.ios.Devices
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=966877433">966877433</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/devices-control-for-homekit/id966877433?mt=8&uo=4">https://itunes.apple.com/us/app/devices-control-for-homekit/id966877433?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** LinkDesk GmbH & Co. KG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/linkdesk/id960476804?uo=4">© LinkDesk</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/8f/91/37/8f913761-4283-630f-76b6-86adc7fd0c8d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38471255-ae16d5b8-3b6e-11e8-89bc-5a093e28679c.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18247556/3884de72-7341-11e6-97b3-3e4d76aedb49.png)

https://cloud.githubusercontent.com/assets/3704186/18247556/3884de72-7341-11e6-97b3-3e4d76aedb49.png

https://cloud.githubusercontent.com/assets/3704186/18247557/401fe730-7341-11e6-9d30-75a24091d556.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Devices – Control for HomeKit
**Bundle ID:** com.linkdesk.ios.Devices
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=966877433">966877433</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/devices-control-for-homekit/id966877433?mt=8&uo=4">https://itunes.apple.com/us/app/devices-control-for-homekit/id966877433?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** LinkDesk GmbH & Co. KG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/linkdesk/id960476804?uo=4">© LinkDesk</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/8f/91/37/8f913761-4283-630f-76b6-86adc7fd0c8d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38471255-ae16d5b8-3b6e-11e8-89bc-5a093e28679c.png)
https://user-images.githubusercontent.com/2068130/38471255-ae16d5b8-3b6e-11e8-89bc-5a093e28679c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38471259-bccd7116-3b6e-11e8-9623-0fb5e03cf181.png
