### ISSUE TITLE
MagicalPad: Notes, Mind Maps, Outlines and Tasks - All in one

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7846]
**App Name:** MagicalPad: Notes, Mind Maps, Outlines and Tasks - All in one
**Bundle ID:** magicalpad.com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=463731782">463731782</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/magicalpad-notes-mind-maps/id463731782?mt=8&uo=4">https://itunes.apple.com/us/app/magicalpad-notes-mind-maps/id463731782?mt=8&uo=4</a>
**App Version:** 3.4.7
**Seller:** MagicalPad, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/magicalpad/id463731785?uo=4>© MagicalPad</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple6/v4/76/ac/7a/76ac7a68-077f-4512-4173-8aae04c5325b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19091763/2b556668-8a84-11e6-8af2-0920aed9d15a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19024038/1187a392-88fc-11e6-841f-1dbf7f637c6b.png)
https://cloud.githubusercontent.com/assets/20930745/19024038/1187a392-88fc-11e6-841f-1dbf7f637c6b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19024048/33d3ae14-88fc-11e6-8341-75ce98403259.png

**Comment by dreamnet** [comment]
Hm, that's hard...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19091763/2b556668-8a84-11e6-8af2-0920aed9d15a.png)
https://cloud.githubusercontent.com/assets/2068130/19091763/2b556668-8a84-11e6-8af2-0920aed9d15a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19091776/3ff733c6-8a84-11e6-9998-fc3431705031.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... this icon looks great ... take it ...
