### ISSUE TITLE
Opera Mini web browser

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7849]
**App Name:** Opera Mini web browser
**Bundle ID:** com.opera.OperaMini
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=363729560">363729560</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/opera-mini-web-browser/id363729560?mt=8&uo=4">https://itunes.apple.com/us/app/opera-mini-web-browser/id363729560?mt=8&uo=4</a>
**App Version:** 14.0.0
**Seller:** Opera Software ASA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/opera-software-asa/id363729563?uo=4>© Opera Software ASA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple18/v4/83/1d/d9/831dd93f-6345-d029-c6d8-ea77b507022d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18282737/ba51ac92-7462-11e6-8a08-01170bd1ffdb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18254214/bf586054-739b-11e6-9e31-2da65c3de18f.png)
https://cloud.githubusercontent.com/assets/20930745/18254214/bf586054-739b-11e6-9e31-2da65c3de18f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18254233/d9ae3b86-739b-11e6-91a0-c76d58eec89e.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes! :+1:

**Comment by dreamnet** [comment]
Ups, no - source is bad.

**Comment by 2Qt2beStr8** [comment]
@dreamnet i know ... I had accidentally deleted the original sourcefile before uploading :-(
The new one is bad... i try to make a new one tomorrow

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18282737/ba51ac92-7462-11e6-8a08-01170bd1ffdb.png)
https://cloud.githubusercontent.com/assets/2068130/18282737/ba51ac92-7462-11e6-8a08-01170bd1ffdb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18282750/c9cca2f8-7462-11e6-9141-f8ee2a8f02fe.png
