### ISSUE TITLE
Bustle: News, Entertainment, & Lifestyle for Women

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7852]
**App Name:** Bustle: News, Entertainment, & Lifestyle for Women
**Bundle ID:** com.bustle.Bustle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=791604919">791604919</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bustle-news-entertainment/id791604919?mt=8&uo=4">https://itunes.apple.com/us/app/bustle-news-entertainment/id791604919?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** BDG Media, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bustle/id791604922?uo=4>© Bustle</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/34/74/97/347497c8-560e-efdb-0a9f-d97adf31dc01/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18975043/9ba359d8-86a7-11e6-8cd5-291476722d2f.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18256924/df68447a-7389-11e6-9233-7cff8788d807.png)

https://cloud.githubusercontent.com/assets/3704186/18256924/df68447a-7389-11e6-9233-7cff8788d807.png

https://cloud.githubusercontent.com/assets/3704186/18256930/e76b86be-7389-11e6-8780-3e4ff9f9e882.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Bustle: News, Entertainment, & Lifestyle for Women
**Bundle ID:** com.bustle.Bustle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=791604919">791604919</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bustle-news-entertainment/id791604919?mt=8&uo=4">https://itunes.apple.com/us/app/bustle-news-entertainment/id791604919?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** BDG Media, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bustle/id791604922?uo=4>© Bustle</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/34/74/97/347497c8-560e-efdb-0a9f-d97adf31dc01/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Anuskuss** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/18974982/43b01bee-86a7-11e6-9785-2fb3adb73960.png)
https://cloud.githubusercontent.com/assets/7157389/18974982/43b01bee-86a7-11e6-9785-2fb3adb73960.png
___
Source:
https://cloud.githubusercontent.com/assets/7157389/18974983/43b11922-86a7-11e6-94dc-b1e67c86ec28.png

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18975043/9ba359d8-86a7-11e6-8cd5-291476722d2f.png)
https://cloud.githubusercontent.com/assets/22012363/18975043/9ba359d8-86a7-11e6-8cd5-291476722d2f.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18975042/9ba1dfc2-86a7-11e6-9712-6abc83e123db.png
