### ISSUE TITLE
Awesome Calendar Lite

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7855]
**App Name:** Awesome Calendar Lite
**Bundle ID:** com.yunatechnology.awesomecalendarliteversion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484829437">484829437</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/awesome-calendar-lite/id484829437?mt=8&uo=4">https://itunes.apple.com/us/app/awesome-calendar-lite/id484829437?mt=8&uo=4</a>
**App Version:** 5.3.1
**Seller:** YunaSoft Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yunasoft-inc./id453184622?uo=4>© YunaSoft Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple71/v4/4e/c0/44/4ec0442e-6ff3-0b1d-533c-5497b1f1a8d4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18261894/083f3e3a-73fd-11e6-9328-b73c53739519.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18257502/ff1c5532-73c4-11e6-985d-b622557007e5.png)
https://cloud.githubusercontent.com/assets/20930745/18257502/ff1c5532-73c4-11e6-985d-b622557007e5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18257507/1213c472-73c5-11e6-8a23-e722f294933a.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Just a litte radius correction, else fine for me! :+1: 
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18261894/083f3e3a-73fd-11e6-9328-b73c53739519.png)
https://cloud.githubusercontent.com/assets/2068130/18261894/083f3e3a-73fd-11e6-9328-b73c53739519.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18261908/16fc1e3e-73fd-11e6-937f-4301f044eb6c.png
