### ISSUE TITLE
Calendarique

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7856]
**App Name:** Calendarique
**Bundle ID:** imagetasks.ios.Calendarique
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1043218729">1043218729</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calendarique/id1043218729?mt=8&uo=4">https://itunes.apple.com/us/app/calendarique/id1043218729?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Andrey Tsarkov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/andrey-tsarkov/id450316587?uo=4>© Andrey Tsarkov</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/be/62/1c/be621c61-99eb-eeb6-79f3-232c73cc1faf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19219652/568110b0-8e19-11e6-9366-52a0c87a6176.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18257356/88916972-73c2-11e6-8e66-576263c27828.png)
https://cloud.githubusercontent.com/assets/20930745/18257356/88916972-73c2-11e6-8e66-576263c27828.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18257362/a166e5d0-73c2-11e6-9c35-2d27958c30c8.png

**Comment by dreamnet** [comment]
Inverted version:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18262022/0f508462-73fe-11e6-9027-8c840ef96b6b.png)
https://cloud.githubusercontent.com/assets/2068130/18262022/0f508462-73fe-11e6-9027-8c840ef96b6b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18262030/26ab6dd4-73fe-11e6-8a4c-2726671c8078.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Calendarique
**Bundle ID:** imagetasks.ios.Calendarique
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1043218729">1043218729</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calendarique/id1043218729?mt=8&uo=4">https://itunes.apple.com/us/app/calendarique/id1043218729?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Andrey Tsarkov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/andrey-tsarkov/id450316587?uo=4>© Andrey Tsarkov</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/be/62/1c/be621c61-99eb-eeb6-79f3-232c73cc1faf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19152361/ea2ee944-8bd1-11e6-8f19-6e0ed27ec6ff.png)
https://cloud.githubusercontent.com/assets/20930745/19152361/ea2ee944-8bd1-11e6-8f19-6e0ed27ec6ff.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19152374/f988fab0-8bd1-11e6-83f1-dedd91f220dc.png
