### ISSUE TITLE
WidgetCal-The Fast and Powerful Calendar Widget

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7857]
**App Name:** WidgetCal-The Fast and Powerful Calendar Widget
**Bundle ID:** com.yunatechnology.WidgetCal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=919048459">919048459</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/widgetcal-the-fast-and-powerful-calendar-widget/id919048459?mt=8&uo=4">https://itunes.apple.com/us/app/widgetcal-the-fast-and-powerful-calendar-widget/id919048459?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** YunaSoft Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yunasoft-inc/id453184622?uo=4">© YunaSoft Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/e4/0e/f1/e40ef137-55b5-02c7-6d73-9e032ce06256/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29493757-ee46bff0-859c-11e7-92bc-6d4def22883c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18359407/1696751c-75fa-11e6-9240-ef78c9f1f49c.png)
https://cloud.githubusercontent.com/assets/20930745/18359407/1696751c-75fa-11e6-9240-ef78c9f1f49c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18359423/2b9fbda6-75fa-11e6-8820-8c3ab20d120e.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18689748/00280670-7f8b-11e6-96cd-e8d702ac5093.png)
https://cloud.githubusercontent.com/assets/20930745/18689748/00280670-7f8b-11e6-96cd-e8d702ac5093.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18689759/16ea9300-7f8b-11e6-89ac-da333e0b0eaa.png

**Comment by dreamnet** [comment]
Hmmmm... @2Qt2beStr8 Both icons are fine, but that's all lines are so fine - no chance too see this on retina display...

**Comment by 2Qt2beStr8** [comment]
@dreamnet .... what do you think about this one? i know, it's not 100 % original ... but the lines are thicker :-)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18791133/c9ba106e-81b1-11e6-8620-8585e21d1e22.png)
https://cloud.githubusercontent.com/assets/20930745/18791133/c9ba106e-81b1-11e6-8620-8585e21d1e22.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18791154/dc4599e2-81b1-11e6-8d0e-5240c24390e2.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes, taken! 👍

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** WidgetCal(Notification Calendar/Reminder)
**Bundle ID:** com.yunatechnology.WidgetCal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=919048459">919048459</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/widgetcal-notification-calendar/id919048459?mt=8&uo=4">https://itunes.apple.com/us/app/widgetcal-notification-calendar/id919048459?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** YunaSoft Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yunasoft-inc./id453184622?uo=4>© YunaSoft Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple19/v4/95/fb/5a/95fb5af1-2484-689c-c372-9e3b052b498f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19624925/3076b9be-990a-11e6-9e0f-612bb13afe2f.png)
https://cloud.githubusercontent.com/assets/20930745/19624925/3076b9be-990a-11e6-9e0f-612bb13afe2f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19624926/47cd008c-990a-11e6-872f-2f835c37bbc1.png

**Comment by ivanov007** [comment]
the last one looks better :+1:

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** WidgetCal-The Fast and Powerful Calendar Widget
**Bundle ID:** com.yunatechnology.WidgetCal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=919048459">919048459</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/widgetcal-the-fast-and-powerful-calendar-widget/id919048459?mt=8&uo=4">https://itunes.apple.com/us/app/widgetcal-the-fast-and-powerful-calendar-widget/id919048459?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** YunaSoft Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yunasoft-inc/id453184622?uo=4">© YunaSoft Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/e4/0e/f1/e40ef137-55b5-02c7-6d73-9e032ce06256/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29493757-ee46bff0-859c-11e7-92bc-6d4def22883c.png)
https://user-images.githubusercontent.com/20930745/29493757-ee46bff0-859c-11e7-92bc-6d4def22883c.png

Source:

https://user-images.githubusercontent.com/20930745/29493762-fe408e68-859c-11e7-87e8-c6abc7422570.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29493771-16ec5e60-859d-11e7-8c0b-4e4f3b89ae9c.png)
https://user-images.githubusercontent.com/20930745/29493771-16ec5e60-859d-11e7-8c0b-4e4f3b89ae9c.png

Source:
https://user-images.githubusercontent.com/20930745/29493774-2acd1fe6-859d-11e7-94d9-c6055112af34.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29493800-c8b8728c-859d-11e7-9791-737ca71f018a.png)
https://user-images.githubusercontent.com/20930745/29493800-c8b8728c-859d-11e7-9791-737ca71f018a.png

Source:
https://user-images.githubusercontent.com/20930745/29493805-dee08a22-859d-11e7-8113-e7ce87aa3407.png

**Comment by dreamnet** [comment]
@l8er4now You decide! 😄

**Comment by l8er4now** [comment]
I like the first one, too much white on the other
