### ISSUE TITLE
Pythonista

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#786]
**App Name:** Pythonista
**Bundle ID:** com.omz-software.Pythonista
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=528579881">528579881</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pythonista/id528579881?mt=8&uo=4">https://itunes.apple.com/us/app/pythonista/id528579881?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Ole Zorn
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/omz-software/id285608316?uo=4>© omz:software</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/45/b5/f2/45b5f220-c3d8-ffc2-cac2-98bc58358e16/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222877/f7ea4fc2-8e62-11e6-94d9-6128b101b01e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222877/f7ea4fc2-8e62-11e6-94d9-6128b101b01e.png)
https://cloud.githubusercontent.com/assets/2068130/19222877/f7ea4fc2-8e62-11e6-94d9-6128b101b01e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19222878/098c6166-8e63-11e6-991a-c61a02b551e0.png
