### ISSUE TITLE
Делимобиль

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7860]
**App Name:** Делимобиль
**Bundle ID:** my.Carharing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1038254296">1038254296</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/delimobil/id1038254296?mt=8&uo=4">https://itunes.apple.com/us/app/delimobil/id1038254296?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Karshering Russiya OOO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ooo-karsering-russia/id1138384777?uo=4>© ООО "Каршеринг Руссия"</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple20/v4/15/f2/7d/15f27d01-91a0-d0b7-9f9f-68ccd5afd688/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18287510/bf85fd2a-7477-11e6-8382-25e400bd8868.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18287510/bf85fd2a-7477-11e6-8382-25e400bd8868.png)
https://cloud.githubusercontent.com/assets/2068130/18287510/bf85fd2a-7477-11e6-8382-25e400bd8868.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18287535/cdf23dba-7477-11e6-9d93-8a623b0af330.png
