### ISSUE TITLE
Free Video - Music Video Player and Streamer for Yоutube

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7861]
**App Name:** Free Video - Music Video Player and Streamer for Yоutube
**Bundle ID:** com.petuhov.freemf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1083079670">1083079670</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/free-video-music-video-player/id1083079670?mt=8&uo=4">https://itunes.apple.com/us/app/free-video-music-video-player/id1083079670?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Vitalii Petuhov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vitalii-petuhov/id1066193301?uo=4>© Vitalii Petuhov</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple69/v4/d3/20/a7/d320a7f7-456b-7abf-3184-fcc7aa11c6e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18531658/b2fe6bc6-7ad7-11e6-89be-96c9a83a4e43.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18309751/28a4b674-74fb-11e6-8dfb-23f4496ab84d.png)
https://cloud.githubusercontent.com/assets/20930745/18309751/28a4b674-74fb-11e6-8dfb-23f4496ab84d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18309781/475c681e-74fb-11e6-879d-c4b8d0eea928.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18531658/b2fe6bc6-7ad7-11e6-89be-96c9a83a4e43.png)
https://cloud.githubusercontent.com/assets/20930745/18531658/b2fe6bc6-7ad7-11e6-89be-96c9a83a4e43.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18531674/c607ba7e-7ad7-11e6-95a5-02f00856a931.png
