### ISSUE TITLE
InFood

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7862]
**App Name:** InFood
**Bundle ID:** com.denisalfa.supplements
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=642144967">642144967</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/infood/id642144967?mt=8&uo=4">https://itunes.apple.com/us/app/infood/id642144967?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** Denis Alfa
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/denis-alfa/id603672511?uo=4>© Denis Alfa</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple18/v4/1b/7d/d1/1b7dd160-92d2-c3ec-ec44-3187984d2a46/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18287819/e9d7afd2-7478-11e6-85eb-a91141d3373b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18287819/e9d7afd2-7478-11e6-85eb-a91141d3373b.png)
https://cloud.githubusercontent.com/assets/2068130/18287819/e9d7afd2-7478-11e6-85eb-a91141d3373b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18287833/f8cf3dac-7478-11e6-927d-4eeaa1cca8ee.png
