### ISSUE TITLE
Помощник Москвы

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7863]
**App Name:** Помощник Москвы
**Bundle ID:** ru.mos.helper
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1023672049">1023672049</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pomosnik-moskvy/id1023672049?mt=8&uo=4">https://itunes.apple.com/us/app/pomosnik-moskvy/id1023672049?mt=8&uo=4</a>
**App Version:** 1.2.5
**Seller:** Department of Transportation, Moscow
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/departament-transporta-moskvy/id575331173?uo=4>© Департамент транспорта Москвы</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple71/v4/22/4c/68/224c6818-19ab-5d38-aa8b-24999725c8b5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18309828/8cd39926-74fb-11e6-8fb2-e3abe7adb3bb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18309828/8cd39926-74fb-11e6-8fb2-e3abe7adb3bb.png)
https://cloud.githubusercontent.com/assets/20930745/18309828/8cd39926-74fb-11e6-8fb2-e3abe7adb3bb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18309843/a22bc71c-74fb-11e6-980b-a6bf019c4c4a.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18310013/92f0323c-74fc-11e6-9439-4445f2bff2c5.png)
https://cloud.githubusercontent.com/assets/20930745/18310013/92f0323c-74fc-11e6-9439-4445f2bff2c5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18310030/a6d71c98-74fc-11e6-91e8-efd0f2f353fe.png
