### ISSUE TITLE
Human Resource Machine

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7864]
**App Name:** Human Resource Machine
**Bundle ID:** com.tomorrowcorporation.humanresourcemachine
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1005098334">1005098334</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/human-resource-machine/id1005098334?mt=8&uo=4">https://itunes.apple.com/us/app/human-resource-machine/id1005098334?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Experimental Gameplay Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/experimental-gameplay-group/id423269933?uo=4>© Experimental Gameplay Group</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple62/v4/23/f1/84/23f18426-c049-4eed-4fbb-94e900177a19/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18848500/fe196f1a-842e-11e6-89b0-0d330757f087.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18767825/c2ebdd70-8121-11e6-8dbb-01253a09d7ea.png)
https://cloud.githubusercontent.com/assets/20930745/18767825/c2ebdd70-8121-11e6-8dbb-01253a09d7ea.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18767870/f9974d00-8121-11e6-9f7f-a94fd174d482.png)

**Comment by dreamnet** [comment]
@2Qt2beStr8 Nice! Made just some small corrections to make things come out clearer:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18773917/fdc81d5a-8153-11e6-9b43-53cd5b4a4d48.png)
https://cloud.githubusercontent.com/assets/2068130/18773917/fdc81d5a-8153-11e6-9b43-53cd5b4a4d48.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18773919/0d6c803e-8154-11e6-8161-b42f6e6498be.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... next time i make it better ... game app icons are very difficulty for me at the moment

**Comment by dreamnet** [comment]
@2Qt2beStr8 All fine - just made the seperation lines a bit thicker. Good work! 👍

**Comment by BrokenCommander** [comment]
Cleaner:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18848500/fe196f1a-842e-11e6-89b0-0d330757f087.png)
https://cloud.githubusercontent.com/assets/22012363/18848500/fe196f1a-842e-11e6-89b0-0d330757f087.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18848477/e0dec058-842e-11e6-9ae0-47fd8832bf5b.png
