### ISSUE TITLE
Пасьянсы (Паук, Косынка, Свободная ячейка)!

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7865]
**App Name:** Пасьянсы (Паук, Косынка, Свободная ячейка)!
**Bundle ID:** com.bakhram.solitareIphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=467940593">467940593</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pas-ansy-pauk-kosynka-svobodnaa/id467940593?mt=8&uo=4">https://itunes.apple.com/us/app/pas-ansy-pauk-kosynka-svobodnaa/id467940593?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** BetterWorld Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/better-world/id430518906?uo=4>© Better World</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple/v4/58/44/90/5844905c-f494-03c6-d2ba-96bc2a29288e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18285782/3a2d88c0-7470-11e6-9183-29eb136d0d6a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18285782/3a2d88c0-7470-11e6-9183-29eb136d0d6a.png)
https://cloud.githubusercontent.com/assets/2068130/18285782/3a2d88c0-7470-11e6-9183-29eb136d0d6a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18285803/488a58b2-7470-11e6-8273-932c92a850b8.png
