### ISSUE TITLE
Prune

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7866]
**App Name:** Prune
**Bundle ID:** com.Polyculture.Prune
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=972319818">972319818</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/prune/id972319818?mt=8&uo=4">https://itunes.apple.com/us/app/prune/id972319818?mt=8&uo=4</a>
**App Version:** 1.0.61
**Seller:** Joel McDonald
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/joel-mcdonald/id972319817?uo=4>© Joel McDonald</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/f9/07/be/f907be80-a5da-d19b-4b90-0048a47a25d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18398401/d9d72fb2-76cc-11e6-979c-a6d03bb971e8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18359726/7ff514cc-75fb-11e6-8abd-40e2b344b3d5.png)
https://cloud.githubusercontent.com/assets/20930745/18359726/7ff514cc-75fb-11e6-8abd-40e2b344b3d5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18359742/96a2b86e-75fb-11e6-8f7c-d19e3ae315d6.png

**Comment by dreamnet** [comment]
Little corrections:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18398401/d9d72fb2-76cc-11e6-979c-a6d03bb971e8.png)
https://cloud.githubusercontent.com/assets/2068130/18398401/d9d72fb2-76cc-11e6-979c-a6d03bb971e8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18398414/e7ec66ee-76cc-11e6-9aae-133a50c21ee3.png
