### ISSUE TITLE
Hopi – Onlarca Markadan Sana Özel Kampanya ve Fırsatlar Yakala, Alışveriş Yaparken Kazan

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7867]
**App Name:** Hopi – Onlarca Markadan Sana Özel Kampanya ve Fırsatlar Yakala, Alışveriş Yaparken Kazan
**Bundle ID:** com.boynergrup.hopi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=983886691">983886691</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hopi-onlarca-markadan-sana/id983886691?mt=8&uo=4">https://itunes.apple.com/us/app/hopi-onlarca-markadan-sana/id983886691?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** BOYNER HOLDING ANONIM SIRKETI
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/boyner-holding/id983886690?uo=4>© Boyner Holding</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple20/v4/e7/05/48/e705483a-1d76-6810-2470-250f91ae80bd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18402834/bd9564e4-76e1-11e6-8359-b297513f7e86.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18339846/24f3f24a-75a2-11e6-9f8d-5eb79778ee62.png)
https://cloud.githubusercontent.com/assets/20930745/18339846/24f3f24a-75a2-11e6-9f8d-5eb79778ee62.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18339858/3c2aa45e-75a2-11e6-813c-71526b0868d8.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18402834/bd9564e4-76e1-11e6-8359-b297513f7e86.png)
https://cloud.githubusercontent.com/assets/2068130/18402834/bd9564e4-76e1-11e6-8359-b297513f7e86.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18402847/cc5faa02-76e1-11e6-8239-ac2421ed48a7.png
