### ISSUE TITLE
Ziraat Mobil

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7868]
**App Name:** Ziraat Mobil
**Bundle ID:** com.ziraatbank.ZiraatMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=885993234">885993234</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ziraat-mobil/id885993234?mt=8&uo=4">https://itunes.apple.com/us/app/ziraat-mobil/id885993234?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** TURKIYE CUMHURIYETI ZIRAAT BANKASI A S
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/t.c.-ziraat-bankas-a.s./id885993237?uo=4>© T.C. Ziraat Bankası A.Ş.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple22/v4/73/b1/1d/73b11dc7-d687-d1f8-bf98-ba532783b7fb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18337337/e46b4e1a-758f-11e6-8c49-a32adbf0beb8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18337337/e46b4e1a-758f-11e6-8c49-a32adbf0beb8.png)
https://cloud.githubusercontent.com/assets/2068130/18337337/e46b4e1a-758f-11e6-8c49-a32adbf0beb8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18337343/f47a92e8-758f-11e6-86df-ee53d01ab9b2.png
