### ISSUE TITLE
Adana Büyükşehir Belediyesi - Akıllı Kent Uygulaması

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7869]
**App Name:** Adana Büyükşehir Belediyesi - Akıllı Kent Uygulaması
**Bundle ID:** com.AdanaBB.AkilliKentUygulamasi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1012282129">1012282129</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adana-buyuksehir-belediyesi/id1012282129?mt=8&uo=4">https://itunes.apple.com/us/app/adana-buyuksehir-belediyesi/id1012282129?mt=8&uo=4</a>
**App Version:** 3.02
**Seller:** abb bilgi islem
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/abb-bilgi-islem/id1012282128?uo=4>© abb bilgi islem</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple41/v4/da/5c/39/da5c39e7-4ba0-ba1b-86b6-7df9743d7cb2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18789654/0c878b3e-81ac-11e6-8f80-12644dd67bb2.png)

**Comment by 2Qt2beStr8** [comment]
only a try ... i think one from the older contributors can do it better

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18789654/0c878b3e-81ac-11e6-8f80-12644dd67bb2.png)
https://cloud.githubusercontent.com/assets/20930745/18789654/0c878b3e-81ac-11e6-8f80-12644dd67bb2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18789677/227e5f76-81ac-11e6-872c-8fc2b7ecb9f7.png

**Comment by ivanov007** [comment]
@2Qt2beStr8 I thinkk it looks good :+1:

**Comment by dreamnet** [comment]
@ivanov007 If you accept an icon, please also markt the issue as `acceptably-fulfilled` - this saves me a lot of time. THX!

**Comment by ivanov007** [comment]
@dreamnet sorry I missed this one
