### ISSUE TITLE
Toroslar 186

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7870]
**App Name:** Toroslar 186
**Bundle ID:** enerjisa.toroslar.dagitim.ariza
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953841267">953841267</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/toroslar-186/id953841267?mt=8&uo=4">https://itunes.apple.com/us/app/toroslar-186/id953841267?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** Toroslar Elektrik Dagitim A.S.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/toroslar-elektrik-dagitim/id953841266?uo=4>© Toroslar Elektrik Dagitim A.S.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple30/v4/8b/e0/a3/8be0a36c-7243-4abf-e202-bc4197c281c7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18698693/7e82a0c0-7fcc-11e6-9073-8094fe74ed99.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18349324/1a4b7474-75d1-11e6-846b-619beaaf1421.png)
https://cloud.githubusercontent.com/assets/20930745/18349324/1a4b7474-75d1-11e6-846b-619beaaf1421.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18349337/2dfaf3f0-75d1-11e6-8c8a-433005326ef2.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18349349/3f35d7fc-75d1-11e6-9ca3-9ec40d75ce3f.png)
https://cloud.githubusercontent.com/assets/20930745/18349349/3f35d7fc-75d1-11e6-9ca3-9ec40d75ce3f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18349361/538af516-75d1-11e6-87d6-adb7c39b0cc1.png

**Comment by dreamnet** [comment]
Annoying icon... I'm not a fan of a border in a border, so I'm unsing this one:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18698693/7e82a0c0-7fcc-11e6-9073-8094fe74ed99.png)
https://cloud.githubusercontent.com/assets/2068130/18698693/7e82a0c0-7fcc-11e6-9073-8094fe74ed99.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18698700/8bb5680e-7fcc-11e6-98f9-8e54634e081d.png
