### ISSUE TITLE
Penguen

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#7871]
**App Name:** Penguen
**Bundle ID:** com.komikburo.penguen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1137534946">1137534946</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/penguen/id1137534946?mt=8&uo=4">https://itunes.apple.com/us/app/penguen/id1137534946?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** KOMIKBURO MEDYA LIMITED SIRKETI
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/komik-buro/id1137534945?uo=4>© Komik Büro</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple60/v4/fb/f7/84/fbf784b7-23fb-b058-811a-87605a971a4e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18557022/903c9b94-7b6d-11e6-96c8-2f596d2e0804.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18357562/c0467570-75f1-11e6-9b7d-ea9c2ee8f544.png)
https://cloud.githubusercontent.com/assets/20930745/18357562/c0467570-75f1-11e6-9b7d-ea9c2ee8f544.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18357592/d784fa36-75f1-11e6-8fc7-15a6de2e4dd1.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18357821/b225d944-75f2-11e6-91e5-34eb2c0c94f6.png)
https://cloud.githubusercontent.com/assets/20930745/18357821/b225d944-75f2-11e6-91e5-34eb2c0c94f6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18357848/c99dc78a-75f2-11e6-832e-9fbef2f06bc4.png

**Comment by 2Qt2beStr8** [comment]
last try

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18554620/0f6398f4-7b65-11e6-8b40-a0cd745ded6a.png)
https://cloud.githubusercontent.com/assets/20930745/18554620/0f6398f4-7b65-11e6-8b40-a0cd745ded6a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18554641/28beb518-7b65-11e6-829e-33f00487887f.png

**Comment by Trubbel** [comment]
The last one looks good to me, just a minor change.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18557022/903c9b94-7b6d-11e6-96c8-2f596d2e0804.png)
https://cloud.githubusercontent.com/assets/10730122/18557022/903c9b94-7b6d-11e6-96c8-2f596d2e0804.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18557021/90232510-7b6d-11e6-9004-72902707e247.png

**Comment by dreamnet** [comment]
@Trubbel @2Qt2beStr8 Good work! 👍
