### ISSUE TITLE
Mein E.ON

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7873]
**App Name:** Mein E.ON
**Bundle ID:** com.eonnavi.navihvp02
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=691972021">691972021</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mein-e.on/id691972021?mt=8&uo=4">https://itunes.apple.com/us/app/mein-e.on/id691972021?mt=8&uo=4</a>
**App Version:** 4.0.18
**Seller:** E.ON AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/e.on-energy-limited/id419138166?uo=4>© E.ON Energy Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple30/v4/10/2a/5d/102a5d15-cd59-25c3-ede7-6d367db1dfc4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18386513/f1512308-7697-11e6-8ecd-bab33e490e94.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18356553/73ce363c-75ed-11e6-8ae4-87ea207d4b6f.png)
https://cloud.githubusercontent.com/assets/20930745/18356553/73ce363c-75ed-11e6-8ae4-87ea207d4b6f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18356578/92d03fd0-75ed-11e6-9128-d33f09b019ca.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Great work! :+1: There are just some small errors:
- The 1024x1024px source file represents the 118x118px area in the Glasklart icon - so your drawing in the source file is too small. Just compare your source with mine.
- Please always keep aspect ratio - your finished icon seems to be skewed. I copy my icon directly to the right side of yours, so you can see what I mean.

![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18386513/f1512308-7697-11e6-8ecd-bab33e490e94.png)
https://cloud.githubusercontent.com/assets/2068130/18386513/f1512308-7697-11e6-8ecd-bab33e490e94.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18386543/0628aada-7698-11e6-8997-6df11d5bd53b.png
