### ISSUE TITLE
The Photo Cookbook - Baking

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7876]
**App Name:** The Photo Cookbook – Baking
**Bundle ID:** net.ditter.PhotoCookbookBaking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405959208">405959208</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-photo-cookbook-baking/id405959208?mt=8&uo=4">https://itunes.apple.com/us/app/the-photo-cookbook-baking/id405959208?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** ditter.projektagentur GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ditter.projektagentur-gmbh/id331451478?uo=4>© ditter.projektagentur GmbH</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple6/v4/f0/b8/18/f0b8185b-522f-1e03-5e6e-a96eefc332ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18667328/6b2ffe92-7f30-11e6-8e6d-2b694f9dce06.png)

**Comment by 2Qt2beStr8** [comment]
.. i don't like the original icon from this app .... maybe we can use this on?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18667328/6b2ffe92-7f30-11e6-8e6d-2b694f9dce06.png)
https://cloud.githubusercontent.com/assets/20930745/18667328/6b2ffe92-7f30-11e6-8e6d-2b694f9dce06.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18667361/7dba2fe2-7f30-11e6-861f-1e1927b95f7e.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Your issue, you decide! 👍
