### ISSUE TITLE
EAT SMARTER - Rezepte, Low Carb, Vegetarisch, Vegan, Einkaufsliste und Kochbuch

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7878]
**App Name:** EAT SMARTER - Rezepte, Low Carb, Vegetarisch, Vegan, Einkaufsliste und Kochbuch
**Bundle ID:** de.eatsmarter.eatsmarter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432046905">432046905</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/eat-smarter-rezepte-low-carb/id432046905?mt=8&uo=4">https://itunes.apple.com/us/app/eat-smarter-rezepte-low-carb/id432046905?mt=8&uo=4</a>
**App Version:** 2.2.14
**Seller:** EAT SMARTER GmbH & Co. KG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eat-smarter-gmbh-co.-kg/id380303929?uo=4>© EAT SMARTER GmbH & Co. KG</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple41/v4/94/dd/9c/94dd9ce8-a112-eaf2-c636-9040bd41995a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18397139/22f9a5ea-76c7-11e6-8ae9-6c5c1552a270.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18387814/286fbf82-769f-11e6-85b5-5dec3916b6d9.png)
https://cloud.githubusercontent.com/assets/20930745/18387814/286fbf82-769f-11e6-85b5-5dec3916b6d9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18387835/39f0ebf0-769f-11e6-86f3-58b64b028bcf.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18388019/1eeccfda-76a0-11e6-98e9-78378fe5fa2b.png)
https://cloud.githubusercontent.com/assets/20930745/18388019/1eeccfda-76a0-11e6-98e9-78378fe5fa2b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18388038/2f5ca66a-76a0-11e6-9c3f-5bb952063ad7.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18388623/9e6b7d86-76a2-11e6-8b59-e7fa66451f61.png)
https://cloud.githubusercontent.com/assets/20930745/18388623/9e6b7d86-76a2-11e6-8b59-e7fa66451f61.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18388640/b032a288-76a2-11e6-80ac-c1c8214e6543.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 In Deutsch, weil's so einfacher ist: Um die Ecken im source file abzurunden, in Illustrator das "Abgerundetes-Ecken-Werkzeug" auswählen und ein neues, "abgerundetes Rechteck" mit 1024px Breite und 1024px Höhe erzeugen. Der Eckenradius ist **180px**. Danach das Rechteck zentrieren und die darunterliegenden Objekte aufteilen. Dann die abgerundeten Ecken löschen.
Sonst gute Arbeit, Du wirst immer besser! :+1:

**Comment by 2Qt2beStr8** [comment]
@dreamnet danke für den Tipp Günther ... ich werde es mal versuchen, wobei ich mit dem Illustrator noch nicht so anfreunden kann. Ich gelobe aber Besserung .... und danke für das Lob :-)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18397139/22f9a5ea-76c7-11e6-8ae9-6c5c1552a270.png)
https://cloud.githubusercontent.com/assets/2068130/18397139/22f9a5ea-76c7-11e6-8ae9-6c5c1552a270.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18397156/347cc266-76c7-11e6-831d-9e889b058666.png
