### ISSUE TITLE
Cam Watcher for Foscam

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7879]
**App Name:** Cam Watcher for Foscam
**Bundle ID:** com.colorfuldrop.foscamstationfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=541467280">541467280</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cam-watcher-for-foscam/id541467280?mt=8&uo=4">https://itunes.apple.com/us/app/cam-watcher-for-foscam/id541467280?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** CHANGHUNG CHANG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/colorful-drop/id482507022?uo=4>© Colorful Drop</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple4/v4/76/01/ae/7601aecc-1047-d2ec-62b1-d4da9d27a790/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18585289/583fd464-7c16-11e6-864f-bfb34fdffaa6.png)

**Comment by 2Qt2beStr8** [comment]
I don't like the original icon from this app ... so i use this one

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18585289/583fd464-7c16-11e6-864f-bfb34fdffaa6.png)
https://cloud.githubusercontent.com/assets/20930745/18585289/583fd464-7c16-11e6-864f-bfb34fdffaa6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18585306/6c0ae452-7c16-11e6-82e5-0bd58967fa8c.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Fine for me! 👍
