### ISSUE TITLE
Remote Desktop - RDP Lite

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7882]
**App Name:** Remote Desktop - RDP Lite
**Bundle ID:** dk.mochasoft.rdplite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288362576">288362576</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/remote-desktop-rdp-lite/id288362576?mt=8&uo=4">https://itunes.apple.com/us/app/remote-desktop-rdp-lite/id288362576?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** Jan Frydendal
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mochasoft/id284741182?uo=4>© MochaSoft</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple49/v4/26/72/e2/2672e2a8-155f-d73c-adb2-8506b8c42ca4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18408616/fb80f9be-7734-11e6-990d-63f28de1c04d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18388330/81c09640-76a1-11e6-8ea2-9c65fb5d9894.png)
https://cloud.githubusercontent.com/assets/20930745/18388330/81c09640-76a1-11e6-8ea2-9c65fb5d9894.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18388344/93e8ffec-76a1-11e6-9e17-00ba5f681b42.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18408616/fb80f9be-7734-11e6-990d-63f28de1c04d.png)
https://cloud.githubusercontent.com/assets/2068130/18408616/fb80f9be-7734-11e6-990d-63f28de1c04d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18408624/0b5f072c-7735-11e6-9b1c-c8519651c591.png
