### ISSUE TITLE
Foscam  Viewer

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7883]
**App Name:** Foscam  Viewer
**Bundle ID:** com.foscam.foscamviewer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=740126713">740126713</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/foscam-viewer/id740126713?mt=8&uo=4">https://itunes.apple.com/us/app/foscam-viewer/id740126713?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** ShenZhen Foscam Intelligent Technology co., Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shenzhen-foscam-intelligent/id924381687?uo=4>© ShenZhen Foscam Intelligent Technology Co., Ltd.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple69/v4/12/d3/62/12d36264-9e6a-eedd-f1e1-6c32fbd0a75b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18712503/03bf4418-800f-11e6-823b-95314d11ef6b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18712503/03bf4418-800f-11e6-823b-95314d11ef6b.png)
https://cloud.githubusercontent.com/assets/20930745/18712503/03bf4418-800f-11e6-823b-95314d11ef6b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18712548/4483a8f4-800f-11e6-8bcf-68518451ec56.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Jup! 👍
