### ISSUE TITLE
Guardian Protection

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7884]
**App Name:** Guardian Protection
**Bundle ID:** com.guardianprotection.Guardian
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=976757777">976757777</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/guardian-protection/id976757777?uo=4">https://apps.apple.com/us/app/guardian-protection/id976757777?uo=4</a>
**App Version:** 4.10.4
**Seller:** GUARDIAN PROTECTION SERVICES, INC.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/guardian-protection-services/id976757776?uo=4">© Guardian Protection Services</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/51/dc/d3/51dcd337-cf65-0984-56d2-1f3896bdf0a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60539009-0b85d780-9d0c-11e9-8d9d-45c24ffc3218.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18394452/0f2b1b6e-7688-11e6-93c5-c4a4ff2184c9.png)

https://cloud.githubusercontent.com/assets/3704186/18394452/0f2b1b6e-7688-11e6-93c5-c4a4ff2184c9.png

https://cloud.githubusercontent.com/assets/3704186/18394459/177a380e-7688-11e6-9934-856083c96987.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60539009-0b85d780-9d0c-11e9-8d9d-45c24ffc3218.png)
https://user-images.githubusercontent.com/20930745/60539009-0b85d780-9d0c-11e9-8d9d-45c24ffc3218.png

Source:
https://user-images.githubusercontent.com/20930745/60539018-0d4f9b00-9d0c-11e9-964a-997cc8ee5346.png
