### ISSUE TITLE
Trigger - Real time alerts & trading

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7889]
**App Name:** Trigger - Real time alerts & trading
**Bundle ID:** com.triggerfinance.triggerapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1073152901">1073152901</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trigger-real-time-alerts-trading/id1073152901?mt=8&uo=4">https://itunes.apple.com/us/app/trigger-real-time-alerts-trading/id1073152901?mt=8&uo=4</a>
**App Version:** 0.2.28
**Seller:** Trigger Finance, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/trigger-finance-inc./id1073152000?uo=4>© Trigger Finance, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/e4/4b/5c/e44b5c50-f2c3-4f92-bf9e-17e5e1a16be9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18402708/f6294b96-76e0-11e6-8850-126e1c99f66d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18402410/81ab47de-76df-11e6-9f8b-18642a32615e.png)
https://cloud.githubusercontent.com/assets/20930745/18402410/81ab47de-76df-11e6-9f8b-18642a32615e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18402421/952d2e9e-76df-11e6-8719-6127af2c8d72.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18402708/f6294b96-76e0-11e6-8850-126e1c99f66d.png)
https://cloud.githubusercontent.com/assets/2068130/18402708/f6294b96-76e0-11e6-8850-126e1c99f66d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18402716/067101ec-76e1-11e6-9bdf-3db26e2f991a.png
