### ISSUE TITLE
Leonardo - Photo Editor with Layer, Selection and Mask

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7890]
**App Name:** Leonardo - Photo Editor with Layer, Selection and Mask
**Bundle ID:** com.beltola.leonardo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=656090065">656090065</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/leonardo-photo-editor-layer/id656090065?mt=8&uo=4">https://itunes.apple.com/us/app/leonardo-photo-editor-layer/id656090065?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Pankaj Goswami
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pankaj-goswami/id370833327?uo=4>© Pankaj Goswami</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/91/18/3a/91183a77-fd69-d841-4573-e68481079e37/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18401983/9b8817e2-76dd-11e6-87eb-3a3d24c3eec4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18401983/9b8817e2-76dd-11e6-87eb-3a3d24c3eec4.png)
https://cloud.githubusercontent.com/assets/20930745/18401983/9b8817e2-76dd-11e6-87eb-3a3d24c3eec4.png

Source:
(https://cloud.githubusercontent.com/assets/20930745/18401985/ac2c05ea-76dd-11e6-975f-ad21722e6d56.png
