### ISSUE TITLE
iExit Interstate Exit Guide

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7896]
**App Name:** iExit Interstate Exit Guide
**Bundle ID:** com.metrocket.iexit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401746066">401746066</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iexit-interstate-exit-guide/id401746066?mt=8&uo=4">https://itunes.apple.com/us/app/iexit-interstate-exit-guide/id401746066?mt=8&uo=4</a>
**App Version:** 9.0.1
**Seller:** Metrocket, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/metrocket-llc/id315566212?uo=4>© Metrocket, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple41/v4/22/85/9f/22859f9a-3f66-906a-8657-9b96311d3cef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18401730/3707a446-76dc-11e6-8981-b5fb5d9bdc82.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18400055/32732b74-76a2-11e6-8c63-2a5d62f1868d.png)

https://cloud.githubusercontent.com/assets/3704186/18400055/32732b74-76a2-11e6-8c63-2a5d62f1868d.png

https://cloud.githubusercontent.com/assets/3704186/18400068/3d410594-76a2-11e6-9213-c89a8c0e2542.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18401730/3707a446-76dc-11e6-8981-b5fb5d9bdc82.png)
https://cloud.githubusercontent.com/assets/20930745/18401730/3707a446-76dc-11e6-8981-b5fb5d9bdc82.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18401748/580e412c-76dc-11e6-8f41-07db47e30fb9.png
