### ISSUE TITLE
Agenda: Widget+

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7898]
**App Name:** Agenda: Widget+
**Bundle ID:** jeeeyul.Agenda
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=978267867">978267867</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/agenda-widget+/id978267867?mt=8&uo=4">https://itunes.apple.com/us/app/agenda-widget+/id978267867?mt=8&uo=4</a>
**App Version:** 1.3.10
**Seller:** Jeeeyul Lee
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jeeeyul-lee/id917932611?uo=4>© Jeeeyul Lee</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple60/v4/bb/1d/1e/bb1d1ecb-8f34-c704-1a4e-e668621a5d91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18402960/7280cf10-76e2-11e6-91df-0e0ec63527f5.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18402808/4f490216-76af-11e6-8dc7-ed49aafb15a1.png)

https://cloud.githubusercontent.com/assets/3704186/18402808/4f490216-76af-11e6-8dc7-ed49aafb15a1.png

https://cloud.githubusercontent.com/assets/3704186/18402810/55bfce54-76af-11e6-8070-343e664172ce.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18402960/7280cf10-76e2-11e6-91df-0e0ec63527f5.png)
https://cloud.githubusercontent.com/assets/2068130/18402960/7280cf10-76e2-11e6-91df-0e0ec63527f5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18402971/81255932-76e2-11e6-9634-7f47c20af752.png
