### ISSUE TITLE
Events Widget - Events on Today tab of the Notification Center

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7899]
**App Name:** Events Widget - Events on Today tab of the Notification Center (일정 위젯)
**Bundle ID:** com.lomohome.eventsList
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=470828213">470828213</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/events-widget-events-on-today/id470828213?mt=8&uo=4">https://itunes.apple.com/us/app/events-widget-events-on-today/id470828213?mt=8&uo=4</a>
**App Version:** 6.0
**Seller:** GEUN WON MO
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mo-geunwon-mo/id470828216?uo=4>© MO (Geunwon,Mo)</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/e6/e9/c0/e6e9c08a-83b7-149d-0638-99726def368f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18403279/12ebcaf8-76e4-11e6-9724-3ce0897d7070.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18403279/12ebcaf8-76e4-11e6-9724-3ce0897d7070.png)
https://cloud.githubusercontent.com/assets/2068130/18403279/12ebcaf8-76e4-11e6-9724-3ce0897d7070.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18403292/2413a47c-76e4-11e6-96df-ba0128995817.png
