### ISSUE TITLE
Future – Calendar events around the clock

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7900]
**App Name:** Future – Calendar events around the clock
**Bundle ID:** MMU.Future
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1037464013">1037464013</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/future-calendar-events-around/id1037464013?mt=8&uo=4">https://itunes.apple.com/us/app/future-calendar-events-around/id1037464013?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Matic Leban
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/matic-leban/id1037464012?uo=4>© Matic Leban</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple2/v4/c7/89/e2/c789e238-1d58-71d6-7bff-f4b70b7c9de8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18408479/3096bc1e-7731-11e6-8e81-238958cb1354.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18408479/3096bc1e-7731-11e6-8e81-238958cb1354.png)
https://cloud.githubusercontent.com/assets/2068130/18408479/3096bc1e-7731-11e6-8e81-238958cb1354.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18408486/40495f04-7731-11e6-82c0-25929ee8d4e3.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18408561/61021130-7733-11e6-9bfd-71b64e7a2024.png)
https://cloud.githubusercontent.com/assets/20930745/18408561/61021130-7733-11e6-9bfd-71b64e7a2024.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18408565/748c6520-7733-11e6-832b-4952ec5523fc.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 :grin:
