### ISSUE TITLE
LifeOn

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7901]
**App Name:** LifeOn
**Bundle ID:** The-Life.LifeOn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=761997217">761997217</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lifeon/id761997217?mt=8&uo=4">https://itunes.apple.com/us/app/lifeon/id761997217?mt=8&uo=4</a>
**App Version:** 4.5.0
**Seller:** KyuHo Nam
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kyuho-nam/id761997220?uo=4">© KyuHo Nam</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/1e/43/2f/1e432fa4-cec7-a807-7758-f2998f485481/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38469598-a390f720-3b57-11e8-8582-d63838ea4b20.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18403014/b13971ee-76e2-11e6-8288-daa7c7b1cb9f.png)
https://cloud.githubusercontent.com/assets/20930745/18403014/b13971ee-76e2-11e6-8288-daa7c7b1cb9f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18403025/c20d6854-76e2-11e6-8b8a-1273622f4fd2.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** LifeOn
**Bundle ID:** The-Life.LifeOn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=761997217">761997217</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lifeon/id761997217?mt=8&uo=4">https://itunes.apple.com/us/app/lifeon/id761997217?mt=8&uo=4</a>
**App Version:** 4.5.0
**Seller:** KyuHo Nam
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kyuho-nam/id761997220?uo=4">© KyuHo Nam</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/1e/43/2f/1e432fa4-cec7-a807-7758-f2998f485481/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38469598-a390f720-3b57-11e8-8582-d63838ea4b20.png)
https://user-images.githubusercontent.com/20930745/38469598-a390f720-3b57-11e8-8582-d63838ea4b20.png

Source:
https://user-images.githubusercontent.com/20930745/38469604-bcbec272-3b57-11e8-9d3d-eabece3b6354.png
