### ISSUE TITLE
FRITZ!App Fon

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7905]
**App Name:** FRITZ!App Fon
**Bundle ID:** de.avm.FRITZApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=372184475">372184475</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fritz-app-fon/id372184475?uo=4">https://apps.apple.com/us/app/fritz-app-fon/id372184475?uo=4</a>
**App Version:** 4.1.2
**Seller:** AVM GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/avm-gmbh/id372184478?uo=4">© AVM GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/c8/72/81/c872819b-4a5f-71a6-c286-678ee6a49fe5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60396092-61585500-9b3d-11e9-84d9-f8a9b1083545.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18417223/171d79cc-782a-11e6-8dd9-3bfcde35d477.png)
https://cloud.githubusercontent.com/assets/2068130/18417223/171d79cc-782a-11e6-8dd9-3bfcde35d477.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18417224/25ad9120-782a-11e6-9b4f-65830cd33360.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60396092-61585500-9b3d-11e9-84d9-f8a9b1083545.png)
https://user-images.githubusercontent.com/2068130/60396092-61585500-9b3d-11e9-84d9-f8a9b1083545.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60396096-6f0dda80-9b3d-11e9-89a4-7af45f0be6cc.png
