### ISSUE TITLE
TankenApp mit Benzinpreistrend

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7908]
**App Name:** TankenApp mit Benzinpreistrend
**Bundle ID:** de.telekom.FuelCompanion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=627468788">627468788</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/tankenapp-mit-benzinpreistrend/id627468788?mt=8&uo=4">https://itunes.apple.com/de/app/tankenapp-mit-benzinpreistrend/id627468788?mt=8&uo=4</a>
**App Version:** 1.6.9
**Seller:** Digital Media Products GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/digital-media-products-gmbh/id1055130538?uo=4>© Digital Media Products GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple41/v4/d8/73/1a/d8731aaa-0f6c-c47e-1319-d7c0c5b15448/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18417171/d10705c6-7828-11e6-8636-d5f028279d03.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18417171/d10705c6-7828-11e6-8636-d5f028279d03.png)
https://cloud.githubusercontent.com/assets/2068130/18417171/d10705c6-7828-11e6-8636-d5f028279d03.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18417172/de051c40-7828-11e6-875f-b84e5cd5c6c9.png
