### ISSUE TITLE
Das Örtliche Telefonbuch & Auskunft in Deutschland

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7909]
**App Name:** Das Örtliche Telefonbuch & Auskunft in Deutschland
**Bundle ID:** de.dasoertliche.DasOertliche
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=330158440">330158440</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/das-ortliche-telefonbuch-auskunft/id330158440?mt=8&uo=4">https://itunes.apple.com/de/app/das-ortliche-telefonbuch-auskunft/id330158440?mt=8&uo=4</a>
**App Version:** 7.6
**Seller:** Das Oertliche Service- und Marketing GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/das-oertliche-service-und/id330158444?uo=4>© Das Oertliche Service- und Marketing GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/3b/15/37/3b1537fd-9421-8b8f-8016-f518e23b5e8f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18415513/1bb62fc2-77f5-11e6-88d9-61c3ed71cd43.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18415513/1bb62fc2-77f5-11e6-88d9-61c3ed71cd43.png)
https://cloud.githubusercontent.com/assets/20930745/18415513/1bb62fc2-77f5-11e6-88d9-61c3ed71cd43.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18415518/31f5cb12-77f5-11e6-8997-cbfe1720a954.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18415517/2ce3663e-77f5-11e6-8983-b6cd591c067e.png)
https://cloud.githubusercontent.com/assets/10730122/18415517/2ce3663e-77f5-11e6-8983-b6cd591c067e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18415516/2ccfe546-77f5-11e6-8547-d859949a0b36.png
