### ISSUE TITLE
MusicID

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7910]
**App Name:** MusicID
**Bundle ID:** com.gravitymobile.MusicIDWorld
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=358838909">358838909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/musicid/id358838909?mt=8&uo=4">https://itunes.apple.com/us/app/musicid/id358838909?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** Gravity Mobile
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gravity-mobile/id320029868?uo=4>© Gravity Mobile</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/8c/51/be/8c51be71-9249-ad14-eccd-d13a7f3ebf11/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18413494/aaffec3c-77a9-11e6-8a0b-7d3aead7c4fd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18413494/aaffec3c-77a9-11e6-8a0b-7d3aead7c4fd.png)
https://cloud.githubusercontent.com/assets/2068130/18413494/aaffec3c-77a9-11e6-8a0b-7d3aead7c4fd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18413496/bb4c99f0-77a9-11e6-823e-7e7c77b97979.png
