### ISSUE TITLE
SUPER MARIO RUN

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7911]
**App Name:** SUPER MARIO RUN
**Bundle ID:** com.nintendo.zara
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1145275343">1145275343</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-mario-run/id1145275343?mt=8&uo=4">https://itunes.apple.com/us/app/super-mario-run/id1145275343?mt=8&uo=4</a>
**App Version:** 0.1
**Seller:** Nintendo Co., Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nintendo-co.-ltd./id1062496488?uo=4>© Nintendo Co., Ltd.</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple22/v4/a5/f8/50/a5f850dc-a1cb-30da-d981-515ba85a458b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18606831/37147b0a-7cbb-11e6-873c-03e1510ed61e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18606831/37147b0a-7cbb-11e6-873c-03e1510ed61e.png)
https://cloud.githubusercontent.com/assets/2068130/18606831/37147b0a-7cbb-11e6-873c-03e1510ed61e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18606833/45e1fb26-7cbb-11e6-99ed-395c44762847.png

**Comment by Trubbel** [comment]
@dreamnet Holy... Nicely done. :smiley:
