### ISSUE TITLE
Юла: объявления рядом

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#7912]
**App Name:** Юла: объявления рядом
**Bundle ID:** com.allgoritm.Youla
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1016489154">1016489154</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/%D1%8E%D0%BB%D0%B0-%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%80%D1%8F%D0%B4%D0%BE%D0%BC/id1016489154?uo=4">https://apps.apple.com/us/app/%D1%8E%D0%BB%D0%B0-%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%80%D1%8F%D0%B4%D0%BE%D0%BC/id1016489154?uo=4</a>
**App Version:** 3.15
**Seller:** Mail.Ru
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/mail-ru/id335315533?uo=4">© Mail.Ru</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a5/02/fc/a502fc3a-450f-1000-929d-264e1ad98329/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59974590-4ff7d180-95ae-11e9-9e2d-1af324615221.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18415458/604bfa06-77f3-11e6-9d71-6ecc509e7d34.png)
https://cloud.githubusercontent.com/assets/20930745/18415458/604bfa06-77f3-11e6-9d71-6ecc509e7d34.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18415459/ac93a17a-77f3-11e6-8fdd-391016ad23a7.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59974590-4ff7d180-95ae-11e9-9e2d-1af324615221.png)
https://user-images.githubusercontent.com/2068130/59974590-4ff7d180-95ae-11e9-9e2d-1af324615221.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59974596-5e45ed80-95ae-11e9-86a9-97c4ec5be600.png
