### ISSUE TITLE
Having touble with the Latest Template to help contribute icons.

### ISSUE THREAD

**Issue by MrAbuser** [glasklart/hd#7915]
I downloaded the latest template v5.02 to help contribute icons to this amazing theme and when I used the template properly(I think :p) my icon turns out to look like this. It's the PIA VPN Icon. It has no background like the other icons for some reason. I have tried both the smart and normal template and tried using them in different ways but I can't seem to get the background on it. Can someone help? 
Thank you :D
![2016_09_11_img_0179](https://cloud.githubusercontent.com/assets/10276688/18420162/bbf112e2-7820-11e6-834b-b3543d627256.JPG)

**Comment by dreamnet** [comment]
@MrAbuser That's because we are getting ready for release v5.0. In v5.0 the background (baseplate) is not needed anymore. All icons will also be sized up to 180x180px. That's why the templates are updated.
Check #7775 and #7776.

**Comment by MrAbuser** [comment]
Oh, okay. Thank makes sense now :)
I appreciate the quick reply. So once 5.0 is out the icon I made should have a baseplate automatically right?
Also do you have the old template still so I can theme some icons that aren't themed on my device temporarily?
Thank you!

**Comment by dreamnet** [comment]
@MrAbuser Yes, when v5.0 comes out, the icon you made will have a baseplate automatically.
Here are the old templates: [Glasklart_Icon_Template_4.0.zip](https://github.com/glasklart/hd/files/466237/Glasklart_Icon_Template_4.0.zip)
