### ISSUE TITLE
ING-DiBa Banking + Brokerage

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7916]
**App Name:** ING-DiBa Banking + Brokerage
**Bundle ID:** de.ingdiba.ingdibaibanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=357028392">357028392</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ing-diba-banking-+-brokerage/id357028392?mt=8&uo=4">https://itunes.apple.com/us/app/ing-diba-banking-+-brokerage/id357028392?mt=8&uo=4</a>
**App Version:** 4.2.8
**Seller:** ING-DiBa AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ing-diba-ag/id357028395?uo=4>© ING-DiBa AG</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/01/f3/10/01f310eb-8b5e-ee0d-a325-a9fcb8ef990e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18602598/d3802ab2-7c6a-11e6-9752-65ce042674c5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18420619/ff53c646-7876-11e6-8136-f5933ebecca2.png)
https://cloud.githubusercontent.com/assets/20930745/18420619/ff53c646-7876-11e6-8136-f5933ebecca2.png

Source:
(https://cloud.githubusercontent.com/assets/20930745/18420626/1558bb86-7877-11e6-9f58-9016982dbb52.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18579436/eb5ef80e-7bf5-11e6-93b8-1f8adf581dc2.png)
https://cloud.githubusercontent.com/assets/20930745/18579436/eb5ef80e-7bf5-11e6-93b8-1f8adf581dc2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18579450/fb928c5e-7bf5-11e6-83f0-9897aa563b0a.png

**Comment by Trubbel** [comment]
@2Qt2beStr8 Could you try to make the outline borders a little bit thicker?

**Comment by 2Qt2beStr8** [comment]
@Trubbel ... i think it's not really better ... maybe someone other can make a better one ... or i try it again ;-)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18583946/128d43a0-7c0e-11e6-981d-c7174c220ffd.png)
https://cloud.githubusercontent.com/assets/20930745/18583946/128d43a0-7c0e-11e6-981d-c7174c220ffd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18583964/24b219ac-7c0e-11e6-8f6c-1a664ffd963d.png

**Comment by 2Qt2beStr8** [comment]
better Sourcefile:

https://cloud.githubusercontent.com/assets/20930745/18584657/89cee7a8-7c12-11e6-86dc-020d3141d465.png

**Comment by dreamnet** [comment]
Alternative:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18602598/d3802ab2-7c6a-11e6-9752-65ce042674c5.png)
https://cloud.githubusercontent.com/assets/2068130/18602598/d3802ab2-7c6a-11e6-9752-65ce042674c5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18602608/e1567ea2-7c6a-11e6-8ec6-559a2f4b28d5.png
😸

**Comment by 2Qt2beStr8** [comment]
@dreamnet you can take your Icon and close this issue

**Comment by dreamnet** [comment]
@2Qt2beStr8 OK.
