### ISSUE TITLE
i-nigma QR Code, Data Matrix and 1D barcode reader

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7919]
**App Name:** i-nigma QR Code, Data Matrix and 1D barcode reader
**Bundle ID:** com.3gvision.inigmaOS4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388923203">388923203</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/i-nigma-qr-code-data-matrix/id388923203?mt=8&uo=4">https://itunes.apple.com/us/app/i-nigma-qr-code-data-matrix/id388923203?mt=8&uo=4</a>
**App Version:** 3.19.01
**Seller:** 3GVision LTD.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/3gvision/id331895427?uo=4>© 3GVision</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/b1/c0/f1/b1c0f1b1-b65a-6f1e-6ca6-ec1bdd6f8918/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18420786/0faec3fc-787b-11e6-823c-f6b01d713bee.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18420786/0faec3fc-787b-11e6-823c-f6b01d713bee.png)
https://cloud.githubusercontent.com/assets/20930745/18420786/0faec3fc-787b-11e6-823c-f6b01d713bee.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18420788/2260f2fe-787b-11e6-9d9c-5b2d48983c63.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18427697/24536c8c-78ca-11e6-85a2-c2a59cd97b20.png)
https://cloud.githubusercontent.com/assets/20930745/18427697/24536c8c-78ca-11e6-85a2-c2a59cd97b20.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18427717/360ae2ca-78ca-11e6-9ab5-8c39ac7832d8.png

**Comment by ivanov007** [comment]
I think first one :+1:

**Comment by 2Qt2beStr8** [comment]
I like both - so it's your decision
