### ISSUE TITLE
Untappd - Discover Beer

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#792]
**App Name:** Untappd - Discover Beer
**Bundle ID:** com.untappdllc.com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=449141888">449141888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/untappd-discover-beer/id449141888?mt=8&uo=4">https://itunes.apple.com/us/app/untappd-discover-beer/id449141888?mt=8&uo=4</a>
**App Version:** 2.6.2
**Seller:** Untappd, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/untappd-inc/id449141891?uo=4>© Untappd, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple41/v4/a3/48/81/a348810a-c534-2894-950a-0384585d43db/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18747462/cc71719c-80cd-11e6-93ac-d97504ba57d1.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18747462/cc71719c-80cd-11e6-93ac-d97504ba57d1.png)
https://cloud.githubusercontent.com/assets/20930745/18747462/cc71719c-80cd-11e6-93ac-d97504ba57d1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18747474/d9fc7bcc-80cd-11e6-8388-d8d05685ada1.png
