### ISSUE TITLE
iCab Mobile (Web Browser)

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7920]
**App Name:** iCab Mobile (Web Browser)
**Bundle ID:** de.icab.iCabMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=308111628">308111628</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/icab-mobile-web-browser/id308111628?mt=8&uo=4">https://itunes.apple.com/us/app/icab-mobile-web-browser/id308111628?mt=8&uo=4</a>
**App Version:** 9.5.1
**Seller:** Alexander Clauss
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alexander-clauss/id286091996?uo=4>© Alexander Clauss</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/59/8c/ae/598cae22-6e2d-cedd-39ec-2a56564b1a47/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18420827/5234da08-787c-11e6-8338-08f00382fad5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18420827/5234da08-787c-11e6-8338-08f00382fad5.png)
https://cloud.githubusercontent.com/assets/20930745/18420827/5234da08-787c-11e6-8338-08f00382fad5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18420823/1df0a902-787c-11e6-88dc-9779ccb9a4cf.png

**Comment by Anuskuss** [comment]
@2Qt2beStr8 **iCab Mobile** is themed for me (see #908)

**Comment by 2Qt2beStr8** [comment]
@Anuskuss .. auf deutsch weils einfacher ist :-) ... ich habe mir heute mal die v5 master gezogen und auf meinem iPhone aktiviert - alle Icons die ich gestern noch gepostet habe wurden nicht umgewandelt und im iTunes Data Crawler wurde mir auch nicht angezeigt das es dazu bereits ein Issue gibt.
