### ISSUE TITLE
QR Reader for iPhone

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7928]
**App Name:** QR Reader for iPhone
**Bundle ID:** com.TapMediaLtd.QRReader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368494609">368494609</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qr-reader-for-iphone/id368494609?mt=8&uo=4">https://itunes.apple.com/us/app/qr-reader-for-iphone/id368494609?mt=8&uo=4</a>
**App Version:** 5.9.1
**Seller:** TapMedia Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tapmedia-ltd/id359632753?uo=4>© TapMedia Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/30/c6/9d/30c69da9-dc75-55ad-c1f0-d436f5bdd528/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18450417/37235c00-7933-11e6-9d97-57402c33bb0e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18436177/34bf23a4-78f7-11e6-916e-674c8770d5f0.png)
https://cloud.githubusercontent.com/assets/20930745/18436177/34bf23a4-78f7-11e6-916e-674c8770d5f0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18436267/c4db57e6-78f7-11e6-89fb-b87611999175.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 I think it's better without the border:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18450417/37235c00-7933-11e6-9d97-57402c33bb0e.png)
https://cloud.githubusercontent.com/assets/2068130/18450417/37235c00-7933-11e6-9d97-57402c33bb0e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18450434/52133ce2-7933-11e6-8479-14f25df913fd.png
