### ISSUE TITLE
iRemoteDesktop Free

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7929]
**App Name:** iRemoteDesktop Free
**Bundle ID:** com.hanajobs.iremotedesktopfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=394062949">394062949</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iremotedesktop-free/id394062949?mt=8&uo=4">https://itunes.apple.com/us/app/iremotedesktop-free/id394062949?mt=8&uo=4</a>
**App Version:** 1.2.8
**Seller:** Hana Mobile LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hana-mobile/id306576922?uo=4>© Hana Mobile</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/ca/12/06/ca1206f1-d814-5765-37f4-da7283bbe958/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18433166/60fed146-78e6-11e6-8325-5425d40d9383.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18433166/60fed146-78e6-11e6-8325-5425d40d9383.png)
https://cloud.githubusercontent.com/assets/10730122/18433166/60fed146-78e6-11e6-8325-5425d40d9383.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18433167/61196dd0-78e6-11e6-8fa3-b9767e1a7642.png
