### ISSUE TITLE
iTunes Remote

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7930]
**App Name:** iTunes Remote
**Bundle ID:** com.apple.Remote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284417350">284417350</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/itunes-remote/id284417350?uo=4">https://apps.apple.com/us/app/itunes-remote/id284417350?uo=4</a>
**App Version:** 4.4.3
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/95/fe/92/95fe9214-548b-deca-6485-58fc895c0425/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69465249-e52b0c00-0d80-11ea-85bd-3c17775e2d24.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18426823/acf8dba4-78c4-11e6-9eb9-28217607238b.png)
https://cloud.githubusercontent.com/assets/20930745/18426823/acf8dba4-78c4-11e6-9eb9-28217607238b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18426917/312e717c-78c5-11e6-9638-4a7283f78b07.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69465249-e52b0c00-0d80-11ea-85bd-3c17775e2d24.png)
https://user-images.githubusercontent.com/2068130/69465249-e52b0c00-0d80-11ea-85bd-3c17775e2d24.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/69465269-f96f0900-0d80-11ea-9ba5-0eaad8778b73.png
