### ISSUE TITLE
Rezepte

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7931]
**App Name:** Rezepte
**Bundle ID:** de.alexanderblach.Rezepte
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=310307605">310307605</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rezepte/id310307605?mt=8&uo=4">https://itunes.apple.com/us/app/rezepte/id310307605?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Alexander Blach
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alexander-blach/id303486870?uo=4>© Alexander Blach</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/9a/d6/d8/9ad6d8dc-e8e3-d0ac-e16e-49a847f4d46a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18564833/a854c768-7b8d-11e6-9c09-01256c5bdeb1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18449652/4460ae0c-7930-11e6-89c0-6bc84cc871b3.png)
https://cloud.githubusercontent.com/assets/20930745/18449652/4460ae0c-7930-11e6-89c0-6bc84cc871b3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18449668/56063096-7930-11e6-9f38-9c362a9554d9.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18555426/1cfa59b4-7b68-11e6-9d31-30faeb1b3c26.png)
https://cloud.githubusercontent.com/assets/20930745/18555426/1cfa59b4-7b68-11e6-9d31-30faeb1b3c26.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18555368/eb1a7e60-7b67-11e6-86b1-61d6d66e51d7.png

**Comment by dreamnet** [comment]
This needs some details, I don't know, maybe something like this...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18564833/a854c768-7b8d-11e6-9c09-01256c5bdeb1.png)
https://cloud.githubusercontent.com/assets/2068130/18564833/a854c768-7b8d-11e6-9c09-01256c5bdeb1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18564871/c79e4b30-7b8d-11e6-9a4c-7011eddeb797.png
P.S.: This is made from a stock image found in the internet.

**Comment by 2Qt2beStr8** [comment]
This looks very good. Can we take it?

**Comment by dreamnet** [comment]
@2Qt2beStr8 Jup!

**Comment by 2Qt2beStr8** [comment]
👍🏻 i think it's better if i make in the future only the easier icons

**Comment by dreamnet** [comment]
@2Qt2beStr8 No, you are doing fine work. Keep on!

**Comment by Trubbel** [comment]
@2Qt2beStr8 I think you are doing great as well, this is indeed a tough icon to recreate. There is no harm in trying. :smile:
