### ISSUE TITLE
TADAA – HD Pro Camera

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7934]
**App Name:** TADAA – HD Pro Camera
**Bundle ID:** net.tadaa.tadaa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=410005685">410005685</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tadaa-hd-pro-camera/id410005685?mt=8&uo=4">https://itunes.apple.com/us/app/tadaa-hd-pro-camera/id410005685?mt=8&uo=4</a>
**App Version:** 5.4.2
**Seller:** menschmaschine Publishing GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/menschmaschine-publishing/id410005688?uo=4>© menschmaschine Publishing GmbH</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/17/7a/21/177a2141-8abb-7f70-3602-c5350ef60362/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18449697/7ae0cd72-7930-11e6-9922-29115a8aa635.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18426296/db42666e-78c0-11e6-89e8-c7019c47f453.png)
https://cloud.githubusercontent.com/assets/20930745/18426296/db42666e-78c0-11e6-89e8-c7019c47f453.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18426307/ef387154-78c0-11e6-8a36-39eb6fc1e3ca.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Strange...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18449697/7ae0cd72-7930-11e6-9922-29115a8aa635.png)
https://cloud.githubusercontent.com/assets/2068130/18449697/7ae0cd72-7930-11e6-9922-29115a8aa635.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18449707/8a9fccea-7930-11e6-9a05-35597756a372.png
