### ISSUE TITLE
Tagesschau

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7935]
**App Name:** Tagesschau
**Bundle ID:** de.tagesschau.Tagesschau
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=401644893">401644893</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tagesschau/id401644893?mt=8&uo=4">https://itunes.apple.com/us/app/tagesschau/id401644893?mt=8&uo=4</a>
**App Version:** 1.8.1
**Seller:** ARD-aktuell
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ard-aktuell/id401644896?uo=4>© ARD-aktuell</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/22/ee/d3/22eed326-784c-105b-d2c0-6768bb75a09a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18454154/13f85b9e-7943-11e6-951a-be458693e294.png)

**Comment by 2Qt2beStr8** [comment]
... i know, it is not perfect ... maybe someone can make a better one

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18454154/13f85b9e-7943-11e6-951a-be458693e294.png)
https://cloud.githubusercontent.com/assets/20930745/18454154/13f85b9e-7943-11e6-951a-be458693e294.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18454324/ea5e6ec6-7943-11e6-8ef8-a895226be2c9.png

**Comment by ivanov007** [comment]
I think is very good :+1:
