### ISSUE TITLE
 TuneWiki - Lyrics with Music

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7936]
**App Name:** TuneWiki - Lyrics with Music
**BundleID:** com.tunewiki.mediaplayer
**iTunes ID:** 320088832
**Original Artwork:**
<img src="https://glasklarthd.dreamnet.at/theicons/462/com.tunewiki.mediaplayer_orig_big.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18614050/f940c604-7d86-11e6-8c8a-c676714e37d4.png)

**Comment by dreamnet** [comment]
Not on iTunes anymore.

**Comment by Anuskuss** [comment]
@dreamnet You can find all the information for a complete request in the `Info.plist` and `iTunesMetadata.plist`.

**Comment by dreamnet** [comment]
@Anuskuss I don't have this app.

**Comment by 2Qt2beStr8** [comment]
i used the older original icon

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18614050/f940c604-7d86-11e6-8c8a-c676714e37d4.png)
https://cloud.githubusercontent.com/assets/20930745/18614050/f940c604-7d86-11e6-8c8a-c676714e37d4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18614057/0dc3f75e-7d87-11e6-98d2-63b8fcffa9b5.png
