### ISSUE TITLE
iHandy Level Free

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7937]
**App Name:** iHandy Level Free
**Bundle ID:** com.ihandysoft.carpenter.level
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=299852753">299852753</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ihandy-level-free/id299852753?mt=8&uo=4">https://itunes.apple.com/us/app/ihandy-level-free/id299852753?mt=8&uo=4</a>
**App Version:** 1.70.2
**Seller:** iHandy Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ihandy-inc./id291242250?mt=8&uo=4>© iHandy Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/a2/60/ff/a260ff2d-e794-bfdc-78f4-80259dad0535/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18587028/35732422-7c20-11e6-8c28-ddef8b7809e2.png)

**Comment by 2Qt2beStr8** [comment]
i have this icon completle redisigned ... i don't know if you like it

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18587028/35732422-7c20-11e6-8c28-ddef8b7809e2.png)
https://cloud.githubusercontent.com/assets/20930745/18587028/35732422-7c20-11e6-8c28-ddef8b7809e2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18587054/4afaa5b8-7c20-11e6-9728-5d2bf6236f53.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Jup! 👍
