### ISSUE TITLE
Christmas Cookies - Heavenly Recipes Made by Angels

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#7938]
**App Name:** Christmas Cookies - Heavenly Recipes Made by Angels
**Bundle ID:** de.bruns.xmasplatzchen10
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=397746749">397746749</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/christmas-cookies-heavenly/id397746749?mt=8&uo=4">https://itunes.apple.com/us/app/christmas-cookies-heavenly/id397746749?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Joachim Bruns
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/joachim-bruns/id377073260?uo=4>© Joachim Bruns</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/31/c4/b0/31c4b052-bc6d-8369-4ed6-644f8544e68e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18431669/5a2abc84-78de-11e6-9513-8d6c9fb460e3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18431669/5a2abc84-78de-11e6-9513-8d6c9fb460e3.png)
https://cloud.githubusercontent.com/assets/20930745/18431669/5a2abc84-78de-11e6-9513-8d6c9fb460e3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18431684/6b19b36a-78de-11e6-934d-0ccd52e223ec.png

**Comment by ivanov007** [comment]
great :+1:, also if you want to be on the [contributors list](https://github.com/glasklart/hd/graphs/contributors), please add a public mail address to your Github account.

**Comment by 2Qt2beStr8** [comment]
@ivanov007 done :-)
