### ISSUE TITLE
MetaTrader 5

### ISSUE THREAD

**Issue by haen7** [glasklart/hd#7939]
**App Name:** MetaTrader 5
**Bundle ID:** net.metaquotes.MetaTrader5Terminal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=413251709">413251709</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/metatrader-5/id413251709?mt=8&uo=4">https://itunes.apple.com/us/app/metatrader-5/id413251709?mt=8&uo=4</a>
**App Version:** 5.0.1371
**Seller:** MetaQuotes Software Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/metaquotes-software-corp./id413251712?uo=4>© MetaQuotes Software Corp.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/7a/ee/ba/7aeebaad-0fb7-033c-464a-48188b32b73d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19022476/d2a31f3e-88d9-11e6-9bbc-e29a7c00e002.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19021814/df9e61c2-88c9-11e6-825a-71963875511f.png)
https://cloud.githubusercontent.com/assets/20930745/19021814/df9e61c2-88c9-11e6-825a-71963875511f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19021819/edfab478-88c9-11e6-9483-b20b9b789283.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 What about inverting the people?
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19022476/d2a31f3e-88d9-11e6-9bbc-e29a7c00e002.png)
https://cloud.githubusercontent.com/assets/2068130/19022476/d2a31f3e-88d9-11e6-9bbc-e29a7c00e002.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19022480/e39f7224-88d9-11e6-88ed-95515727d781.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... i like it 👍
