### ISSUE TITLE
nPlayer Plus - The best media player

### ISSUE THREAD

**Issue by haen7** [glasklart/hd#7940]
**App Name:** nPlayer Plus - The best media player
**Bundle ID:** com.newin.nplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=539397400">539397400</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nplayer-plus-best-media-player/id539397400?mt=8&uo=4">https://itunes.apple.com/us/app/nplayer-plus-best-media-player/id539397400?mt=8&uo=4</a>
**App Version:** 3.4.4
**Seller:** Newin Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/newin-inc./id428837240?uo=4>© Newin Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple32/v4/2e/56/e9/2e56e9ca-25b8-db09-742d-0d3f107a8059/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18448920/4a2480c8-792d-11e6-8413-a4ffbfe8881a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18436791/6192c5cc-78fa-11e6-87d9-bb3bbd6c3ac8.png)
https://cloud.githubusercontent.com/assets/20930745/18436791/6192c5cc-78fa-11e6-87d9-bb3bbd6c3ac8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18436812/7520416e-78fa-11e6-9ace-adc4b2aae27a.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18447584/93ee446a-7927-11e6-93cf-77969c805057.png)
https://cloud.githubusercontent.com/assets/20930745/18447584/93ee446a-7927-11e6-93cf-77969c805057.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18447683/01a98168-7928-11e6-9503-9ce4cd708172.png

**Comment by dreamnet** [comment]
On second thought - it looks off-centered and in the wrong size:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18448920/4a2480c8-792d-11e6-8413-a4ffbfe8881a.png)
https://cloud.githubusercontent.com/assets/2068130/18448920/4a2480c8-792d-11e6-8413-a4ffbfe8881a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18448940/58fc612e-792d-11e6-8430-316fd9751584.png
