### ISSUE TITLE
A Doodle Fly - Fly to Mars

### ISSUE THREAD

**Issue by Bonfi97** [glasklart/hd#7941]
**App Name:** A Doodle Fly - Fly to Mars
**Bundle ID:** com.j2developer.ADoodleFly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=339980057">339980057</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/a-doodle-fly-fly-to-mars/id339980057?mt=8&uo=4">https://itunes.apple.com/us/app/a-doodle-fly-fly-to-mars/id339980057?mt=8&uo=4</a>
**App Version:** 7.15
**Seller:** Jerry Lee
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/j2sighte/id309192476?uo=4>© j2sighte</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/c6/ab/ac/c6abac50-9490-891e-e5a7-e355f0b58f41/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18483654/487f1e82-79e5-11e6-9630-e77da3fb5b70.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18483654/487f1e82-79e5-11e6-9630-e77da3fb5b70.png)
https://cloud.githubusercontent.com/assets/2068130/18483654/487f1e82-79e5-11e6-9630-e77da3fb5b70.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18483672/5a776626-79e5-11e6-9672-c706e74a7aee.png
