### ISSUE TITLE
Rasta Monkey!

### ISSUE THREAD

**Issue by Bonfi97** [glasklart/hd#7942]
**App Name:** Rasta Monkey!
**Bundle ID:** com.Nitako.RastaMonkey
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307225367">307225367</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rasta-monkey!/id307225367?mt=8&uo=4">https://itunes.apple.com/us/app/rasta-monkey!/id307225367?mt=8&uo=4</a>
**App Version:** 1.6.5
**Seller:** Nitako LTD.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nitako-ltd./id583704896?uo=4>© Nitako LTD.</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/32/e7/c7/32e7c7a8-2e73-96db-9762-dfc01cb8afc9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18715928/42680cc0-801b-11e6-95ad-00370f6914d6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18715928/42680cc0-801b-11e6-95ad-00370f6914d6.png)
https://cloud.githubusercontent.com/assets/20930745/18715928/42680cc0-801b-11e6-95ad-00370f6914d6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18715945/53017986-801b-11e6-9f30-8a83c43973e0.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Great!
