### ISSUE TITLE
MysticalColors

### ISSUE THREAD

**Issue by Bonfi97** [glasklart/hd#7943]
**App Name:** MysticalColors
**Bundle ID:** com.gaujg.MysticalColors
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=352263594">352263594</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mysticalcolors/id352263594?mt=8&uo=4">https://itunes.apple.com/us/app/mysticalcolors/id352263594?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Biao Zhang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/biao-zhang/id328952151?uo=4>© Biao Zhang</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/ae/fd/7c/aefd7c44-72e5-77db-fcb0-bbdb12115748/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18809341/396755b2-8279-11e6-979f-c6e18d260242.png)

**Comment by 2Qt2beStr8** [comment]
... i am not really happy with this icon ... but the sourcefile is small and bad :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809042/ca5496fe-8272-11e6-87df-106ded8c2d2e.png)
https://cloud.githubusercontent.com/assets/20930745/18809042/ca5496fe-8272-11e6-87df-106ded8c2d2e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18809045/de323320-8272-11e6-890c-30f9ec5338dc.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes... but I think your icon is fine.
