### ISSUE TITLE
Rope'n'Fly 2

### ISSUE THREAD

**Issue by Bonfi97** [glasklart/hd#7944]
**App Name:** Rope'n'Fly 2
**Bundle ID:** com.rsz.RopeFly2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=330976703">330976703</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ropenfly-2/id330976703?mt=8&uo=4">https://itunes.apple.com/us/app/ropenfly-2/id330976703?mt=8&uo=4</a>
**App Version:** 4.9
**Seller:** Djinnworks GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/djinnworks-gmbh/id302877209?mt=8&uo=4>© Djinnworks GmbH</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/2d/c6/11/2dc61131-330b-fd70-0823-fb44200e8a63/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18606878/83588988-7cbc-11e6-8850-ec6c13c708c8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18606878/83588988-7cbc-11e6-8850-ec6c13c708c8.png)
https://cloud.githubusercontent.com/assets/2068130/18606878/83588988-7cbc-11e6-8850-ec6c13c708c8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18606880/9281e4e0-7cbc-11e6-9367-8e3df3cbaa0b.png
❔
