### ISSUE TITLE
RocketBird For Kids

### ISSUE THREAD

**Issue by Bonfi97** [glasklart/hd#7945]
**App Name:** RocketBird For Kids
**Bundle ID:** com.betomorrow.RocketBird
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=332073405">332073405</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rocketbird-for-kids/id332073405?mt=8&uo=4">https://itunes.apple.com/us/app/rocketbird-for-kids/id332073405?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** BETOMORROW
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/betomorrow/id303956224?uo=4>© BeTomorrow</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/49/8e/34/498e343b-2004-6584-cf87-27d79f176b6d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18878899/aa75a168-84d2-11e6-950d-edaeb3559345.png)

**Comment by BrokenCommander** [comment]
@Bonfi97 Just a draft, if you like the base idea I can refine it.
Would also like to get some feedback from @dreamnet since I'm kinda new to Glasklart. I don't like the icon very much since it's too much white for my eyes.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18852581/6185d338-8441-11e6-9dbd-fbf32926e79f.png)

**Comment by Bonfi97** [comment]
You can try to remove the white background leaving only the chick and the text.
PS: you also need to post the link to the source image in order to make the icon approved.

**Comment by dreamnet** [comment]
@BrokenCommander Not bad, but as @Bonfi97 says, you need to do more someting like this:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18878899/aa75a168-84d2-11e6-950d-edaeb3559345.png)
https://cloud.githubusercontent.com/assets/2068130/18878833/6717eb92-84d2-11e6-9378-3f984acfe200.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18878854/75f785fa-84d2-11e6-9887-610fe6a4636c.png
Just a quick try.
