### ISSUE TITLE
Bust-A-Move

### ISSUE THREAD

**Issue by Bonfi97** [glasklart/hd#7946]
**App Name:** Bust-A-Move
**Bundle ID:** jp.co.taito.BustAMove
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=326144884">326144884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bust-a-move/id326144884?mt=8&uo=4">https://itunes.apple.com/us/app/bust-a-move/id326144884?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** TAITO Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/taito-corporation/id305608085?uo=4>© TAITO Corporation</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/ee/c2/12/eec212d7-b74d-1f9a-9340-696fb0fc7a61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18599689/eee2d91e-7c59-11e6-9686-50aea36fff49.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18560887/c494dbe4-7b7d-11e6-9b2c-73458dc7eb81.png)
https://cloud.githubusercontent.com/assets/20930745/18560887/c494dbe4-7b7d-11e6-9b2c-73458dc7eb81.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18560901/d4afc12e-7b7d-11e6-8365-90758a83d2c7.png

**Comment by ivanov007** [comment]
@2Qt2beStr8 maybe inverted?

**Comment by 2Qt2beStr8** [comment]
.... like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18582474/ad60943a-7c05-11e6-9b99-e0e249ab84be.png)
https://cloud.githubusercontent.com/assets/20930745/18582474/ad60943a-7c05-11e6-9b99-e0e249ab84be.png

Source:
(https://cloud.githubusercontent.com/assets/20930745/18582487/bf55504a-7c05-11e6-8135-87e667e484f7.png

**Comment by some1563** [comment]
Maybe like this one. It's Puzzle Bobble's icon, but it's in low resolution, so someone must remake it.
![img_0782](https://cloud.githubusercontent.com/assets/20641528/18583169/31c40272-7c09-11e6-89df-dbd1398a212b.PNG)

**Comment by dreamnet** [comment]
Heeeeeerrrre we go....
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18599689/eee2d91e-7c59-11e6-9686-50aea36fff49.png)
https://cloud.githubusercontent.com/assets/2068130/18599689/eee2d91e-7c59-11e6-9686-50aea36fff49.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18599696/fd32a1c0-7c59-11e6-8e4f-86fd6550dc2f.png
