### ISSUE TITLE
iSource Browse

### ISSUE THREAD

**Issue by Bonfi97** [glasklart/hd#7947]
**App Name:** iSource Browser
**Bundle ID:** iSourceBrowser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=370764473">370764473</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/isource-browser/id370764473?mt=8&uo=4">https://itunes.apple.com/us/app/isource-browser/id370764473?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Nicholas  Conolly
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/gamu-apps/id366786599?uo=4>© Gamu apps</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple42/v4/68/7d/0e/687d0e14-0c9b-77c4-ec6c-5bc43652a42c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18447941/0a9b5246-7929-11e6-9a23-d2dcfe637232.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18447941/0a9b5246-7929-11e6-9a23-d2dcfe637232.png)
https://cloud.githubusercontent.com/assets/20930745/18447941/0a9b5246-7929-11e6-9a23-d2dcfe637232.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18447967/264b6fa8-7929-11e6-99ad-712baf6c4393.png
