### ISSUE TITLE
SneakABoo - Uploader

### ISSUE THREAD

**Issue by some1563** [glasklart/hd#7948]
**App Name:** SneakABoo - Uploader
**Bundle ID:** com.sneakaboo.uploader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1126002719">1126002719</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sneakaboo-uploader/id1126002719?mt=8&uo=4">https://itunes.apple.com/us/app/sneakaboo-uploader/id1126002719?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Georgina Craig-Murray
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/georgina-craig-murray/id1126002718?uo=4>© Georgina Craig-Murray</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/1f/15/1b/1f151bd8-763a-b865-0da6-ab44b0281046/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18449252/c33445f6-792e-11e6-9810-9a7efba7f826.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18448584/0290685e-792c-11e6-9a6f-1309ff19f01a.png)
https://cloud.githubusercontent.com/assets/20930745/18448584/0290685e-792c-11e6-9a6f-1309ff19f01a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18448859/f8ea11b4-792c-11e6-9ec9-aedec3b25545.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18449252/c33445f6-792e-11e6-9810-9a7efba7f826.png)
https://cloud.githubusercontent.com/assets/2068130/18449252/c33445f6-792e-11e6-9810-9a7efba7f826.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18449270/d31ff3c0-792e-11e6-87d5-278f4394c5eb.png
