### ISSUE TITLE
Cardboard Camera

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#7949]
**App Name:** Cardboard Camera
**Bundle ID:** com.google.Cyclops
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1095487294">1095487294</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cardboard-camera/id1095487294?mt=8&uo=4">https://itunes.apple.com/us/app/cardboard-camera/id1095487294?mt=8&uo=4</a>
**App Version:** 1.01
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/0a/dc/cb/0adccb09-88cd-61e7-fa61-3562599c0852/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18454105/d07bc414-7942-11e6-839d-5615906bfe92.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18453878/866ce8cc-7941-11e6-87bd-fa90827bdf44.png)
https://cloud.githubusercontent.com/assets/20930745/18453878/866ce8cc-7941-11e6-87bd-fa90827bdf44.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18453909/b1e90f76-7941-11e6-8c74-69e43c45fbf0.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18454105/d07bc414-7942-11e6-839d-5615906bfe92.png)
https://cloud.githubusercontent.com/assets/20930745/18454105/d07bc414-7942-11e6-839d-5615906bfe92.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18454119/e662d9c0-7942-11e6-9573-5a5b1d892031.png
