### ISSUE TITLE
SHAREit - Connect & Transfer

### ISSUE THREAD

**Issue by haen7** [glasklart/hd#7950]
**App Name:** SHAREit - Connect & Transfer
**Bundle ID:** com.lenovo.anyshare
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=725215120">725215120</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/hk/app/shareit-connect-transfer/id725215120?mt=8&uo=4">https://itunes.apple.com/hk/app/shareit-connect-transfer/id725215120?mt=8&uo=4</a>
**App Version:** 2.4.90
**Seller:** SHAREit Technologies Co. Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/hk/developer/shareit-technologies-co.-ltd/id976567949?uo=4>© SHAREit Technologies Co. Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/1b/33/30/1b333038-99e2-d251-78f2-7a55a290d46f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18483094/0d093ab0-79e3-11e6-8d55-2a07ddae0312.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18465506/6574a83e-7997-11e6-9e2f-b7c1c732cac9.png)
https://cloud.githubusercontent.com/assets/20930745/18465506/6574a83e-7997-11e6-9e2f-b7c1c732cac9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18465518/7a43dabe-7997-11e6-984d-f98bdd457f88.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18465669/262402fa-7998-11e6-802b-065c12a0a7e3.png)
https://cloud.githubusercontent.com/assets/20930745/18465669/262402fa-7998-11e6-802b-065c12a0a7e3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18465678/38b5ee38-7998-11e6-950c-a94d7a3083c0.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18483094/0d093ab0-79e3-11e6-8d55-2a07ddae0312.png)
https://cloud.githubusercontent.com/assets/2068130/18483094/0d093ab0-79e3-11e6-8d55-2a07ddae0312.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18483108/1b9fbaf4-79e3-11e6-9db8-855be2aecac8.png

**Comment by dreamnet** [comment]
@haen7 What's your favorite❔

**Comment by haen7** [comment]
> What's your favorite❔

@dreamnet this one looks good :thumbsup:

<img src="https://camo.githubusercontent.com/51c9a0b814f4c3262e88939fa882ae5f30f7f33d/687474703a2f2f707265766965772e647265616d6e65742e61743f696d6167653d68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f323036383133302f31383438333039342f30643039336162302d373965332d313165362d386435352d3261303764646165303331322e706e67" width="180" height="180" />

https://cloud.githubusercontent.com/assets/2068130/18483108/1b9fbaf4-79e3-11e6-9db8-855be2aecac8.png

**Comment by Anuskuss** [comment]
I like it without the circle (but with the smaller size).
