### ISSUE TITLE
Telkussa

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#7951]
**App Name:** Telkussa
**Bundle ID:** com.tokavuh.telkussa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=292921322">292921322</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/telkussa/id292921322?mt=8&uo=4">https://itunes.apple.com/us/app/telkussa/id292921322?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Tokavuh Technologies oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tokavuh-technologies-oy/id292921325?uo=4>© Tokavuh Technologies oy</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/42/fb/df/42fbdfae-ab3c-31ff-9b92-b9b3864806cf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18488386/6ad713cc-79f9-11e6-9464-b5b6fe89af7e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18486822/ed6eb99a-79f2-11e6-9872-9d5cd86b73c6.png)
https://cloud.githubusercontent.com/assets/20930745/18486822/ed6eb99a-79f2-11e6-9872-9d5cd86b73c6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18486909/77c1655c-79f3-11e6-8ad2-fcaf51ce590c.png
