### ISSUE TITLE
FineScanner Pro scan & recognize doc to PDF or JPG

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#7952]
**App Name:** FineScanner Pro scan & recognize doc to PDF or JPG
**Bundle ID:** com.abbyy.finescanner-pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=946930094">946930094</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/finescanner-pro-scan-recognize/id946930094?mt=8&uo=4">https://itunes.apple.com/us/app/finescanner-pro-scan-recognize/id946930094?mt=8&uo=4</a>
**App Version:** 5.6
**Seller:** ABBYY USA Software House Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/abbyy/id347345477?uo=4>© ABBYY</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/82/d0/41/82d04142-f080-8208-9254-d1863f303f30/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18575475/70b477a4-7bd8-11e6-86c9-de64c5964335.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18566481/590cd72a-7b94-11e6-92b0-91b30a668296.png)

![com abbyy finescanner-pro-large](https://cloud.githubusercontent.com/assets/16171251/18566481/590cd72a-7b94-11e6-92b0-91b30a668296.png)

![com abbyy finescanner-pro](https://cloud.githubusercontent.com/assets/16171251/18566513/7442a04c-7b94-11e6-8344-bbbd25113bac.png)

**Comment by ivanov007** [comment]
free version has the icon, and since I don't think anyone willl have both installed at the same time, @Checkit23  can you remove the "PRO" text?

**Comment by Checkit23** [comment]
Year, that makes sense. Here's a new icon.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18567048/b91c94dc-7b96-11e6-9e16-c5cfa9b0ab37.png)

https://cloud.githubusercontent.com/assets/16171251/18567048/b91c94dc-7b96-11e6-9e16-c5cfa9b0ab37.png

https://cloud.githubusercontent.com/assets/16171251/18567067/d23711c2-7b96-11e6-92b2-b102dc5b5bf9.png

**Comment by dreamnet** [comment]
Here is the icon from #4656 
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18575475/70b477a4-7bd8-11e6-86c9-de64c5964335.png)
https://cloud.githubusercontent.com/assets/2068130/18575475/70b477a4-7bd8-11e6-86c9-de64c5964335.png
--- ---
https://cloud.githubusercontent.com/assets/2068130/18575482/81f9a458-7bd8-11e6-8f9c-b4470d4c6ce6.png
I think we should use this one for both apps.
