### ISSUE TITLE
XFINITY TV

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7955]
**App Name:** XFINITY TV
**Bundle ID:** com.comcast.cim.x2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=731629156">731629156</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xfinity-tv/id731629156?mt=8&uo=4">https://itunes.apple.com/us/app/xfinity-tv/id731629156?mt=8&uo=4</a>
**App Version:** 3.8.1
**Seller:** Comcast Interactive Media
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/comcast/id298960160?uo=4>© Comcast</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/50/34/a5/5034a575-a677-5124-cd93-020b25d11b6a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18588775/286123a8-7c28-11e6-888d-07c7f4a5784d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18588775/286123a8-7c28-11e6-888d-07c7f4a5784d.png)
https://cloud.githubusercontent.com/assets/20930745/18588775/286123a8-7c28-11e6-888d-07c7f4a5784d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18588792/3e72c3b8-7c28-11e6-88a4-8ba5587f5a49.png)
