### ISSUE TITLE
XFINITY My Account

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7956]
**App Name:** XFINITY My Account
**Bundle ID:** com.comcast.cim.myaccount
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=776010987">776010987</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xfinity-my-account/id776010987?mt=8&uo=4">https://itunes.apple.com/us/app/xfinity-my-account/id776010987?mt=8&uo=4</a>
**App Version:** 1.20.0
**Seller:** Comcast Interactive Media
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/comcast/id298960160?uo=4>© Comcast</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/3f/7d/4e/3f7d4ecf-4a59-de0d-5b22-4216aa60e9b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18600192/bd6446ea-7c5c-11e6-80cf-b15304a569cb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18589663/0692c606-7c2c-11e6-8ba5-045764a1fcca.png)
https://cloud.githubusercontent.com/assets/20930745/18589663/0692c606-7c2c-11e6-8ba5-045764a1fcca.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18589678/18bc39d4-7c2c-11e6-84d4-dbb4dcc22dc2.png

**Comment by dreamnet** [comment]
Keep original size.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18600192/bd6446ea-7c5c-11e6-80cf-b15304a569cb.png)
https://cloud.githubusercontent.com/assets/2068130/18600192/bd6446ea-7c5c-11e6-80cf-b15304a569cb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18600206/cecc5864-7c5c-11e6-93b7-9564287ae1ce.png
