### ISSUE TITLE
Alarm Clock HD - Free

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7957]
**App Name:** Alarm Clock HD - Free
**Bundle ID:** com.alarmclockcompany.alarmclockhdfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=476555713">476555713</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alarm-clock-hd-free/id476555713?mt=8&uo=4">https://itunes.apple.com/us/app/alarm-clock-hd-free/id476555713?mt=8&uo=4</a>
**App Version:** 3.0.0
**Seller:** Impala Studios B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/impala-studios/id1063279743?uo=4>© Impala Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/a4/34/c5/a434c5ee-6a97-db05-b125-2200596d5ab8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18610997/529a9816-7d2c-11e6-95bb-e5fd38281bbc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18610971/863b59fe-7d2b-11e6-8bc1-b66088dc0ac0.png)
https://cloud.githubusercontent.com/assets/20930745/18610971/863b59fe-7d2b-11e6-8bc1-b66088dc0ac0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18610973/9c971102-7d2b-11e6-99f1-a87084894be9.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18610997/529a9816-7d2c-11e6-95bb-e5fd38281bbc.png)
https://cloud.githubusercontent.com/assets/20930745/18610997/529a9816-7d2c-11e6-95bb-e5fd38281bbc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18610998/639e99f0-7d2c-11e6-8545-d53cdcef655e.png
