### ISSUE TITLE
App for Craigslist Free - Search Classified Ads

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7958]
**App Name:** App for Craigslist Free - Search Classified Ads
**Bundle ID:** com.shoppingsoftware.craigslist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=962368305">962368305</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/app-for-craigslist-free-search/id962368305?mt=8&uo=4">https://itunes.apple.com/us/app/app-for-craigslist-free-search/id962368305?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Impala Studios B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/impala-studios/id1063279743?uo=4>© Impala Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/cc/1d/d5/cc1dd567-3526-486b-a1b9-52145938d69c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18600551/851ab3f8-7c5e-11e6-9d63-ec6a279c18b8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18588496/f7e0bafa-7c26-11e6-91a7-15492a22cb75.png)
https://cloud.githubusercontent.com/assets/20930745/18588496/f7e0bafa-7c26-11e6-91a7-15492a22cb75.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18588512/0885d00c-7c27-11e6-9c09-524e089ce2a6.png

**Comment by Anuskuss** [comment]
@2Qt2beStr8 I'd say you make it smaller and put it in the corner.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18600551/851ab3f8-7c5e-11e6-9d63-ec6a279c18b8.png)
https://cloud.githubusercontent.com/assets/2068130/18600551/851ab3f8-7c5e-11e6-9d63-ec6a279c18b8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18600563/92c457e8-7c5e-11e6-8c0d-23803c54fc49.png
