### ISSUE TITLE
Other

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7959]
**App Name:** Other
**Bundle ID:** com.jellystyle.Other
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1090792031">1090792031</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/other/id1090792031?mt=8&uo=4">https://itunes.apple.com/us/app/other/id1090792031?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Daniel Farrelly
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/daniel-farrelly/id406941815?uo=4>© Daniel Farrelly</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/f5/00/c3/f500c30a-bbd5-b491-bfe0-fb31c6e6c19b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18587215/1881fe28-7c21-11e6-8b32-57ca7f70a5a0.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18587215/1881fe28-7c21-11e6-8b32-57ca7f70a5a0.png)

https://cloud.githubusercontent.com/assets/16171251/18587215/1881fe28-7c21-11e6-8b32-57ca7f70a5a0.png

https://cloud.githubusercontent.com/assets/16171251/18587231/2b3c6a3a-7c21-11e6-9873-a9b71655b254.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18587313/ae5114fc-7c21-11e6-9ce2-f12c93bc636b.png)
https://cloud.githubusercontent.com/assets/20930745/18587313/ae5114fc-7c21-11e6-9ce2-f12c93bc636b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18587345/c45dd6ae-7c21-11e6-93e6-dffeedb5b607.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18587525/ce4efe12-7c22-11e6-9de3-a9afb24bb046.png)
https://cloud.githubusercontent.com/assets/20930745/18587525/ce4efe12-7c22-11e6-9de3-a9afb24bb046.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18587539/e15bb95a-7c22-11e6-96c4-3b18f4765818.png
