### ISSUE TITLE
The New Yorker Magazine

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7960]
**App Name:** The New Yorker Magazine
**Bundle ID:** com.condenet.newyorker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=370614765">370614765</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-new-yorker-magazine/id370614765?mt=8&uo=4">https://itunes.apple.com/us/app/the-new-yorker-magazine/id370614765?mt=8&uo=4</a>
**App Version:** 4.6.9
**Seller:** CondeNet
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/conde-nast-digital/id289380416?mt=8&uo=4>© Condé Nast Digital</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/3e/9e/7a/3e9e7a7c-49cb-4dec-3043-0130eef3f0e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18607616/4c61b1be-7cd2-11e6-846b-8ce326d0ce44.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18606849/a1a89a8c-7cbb-11e6-8d09-e99dedb0b790.png)
https://cloud.githubusercontent.com/assets/2068130/18606849/a1a89a8c-7cbb-11e6-8d09-e99dedb0b790.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18606851/b362e728-7cbb-11e6-8feb-30ad28d45861.png

**Comment by 2Qt2beStr8** [comment]
what do you think about this? but i had to make some little corrections

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18607119/d0a8f25c-7cc3-11e6-8c44-cd4a5363c252.png)
https://cloud.githubusercontent.com/assets/20930745/18607119/d0a8f25c-7cc3-11e6-8c44-cd4a5363c252.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18607121/dec3b7d2-7cc3-11e6-9866-e268aec5ea07.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Nice, but I'm already not happy with it, white, red and grey should be white and the hat should be as you made it....

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18607616/4c61b1be-7cd2-11e6-846b-8ce326d0ce44.png)
https://cloud.githubusercontent.com/assets/20930745/18607616/4c61b1be-7cd2-11e6-846b-8ce326d0ce44.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18607619/5e250e28-7cd2-11e6-9bcb-23af89a77c93.png
