### ISSUE TITLE
Slate.com

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7961]
**App Name:** Slate.com
**Bundle ID:** com.pointabout.Slate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=357555242">357555242</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slate.com/id357555242?mt=8&uo=4">https://itunes.apple.com/us/app/slate.com/id357555242?mt=8&uo=4</a>
**App Version:** 4.4.2
**Seller:** The Slate Group, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/the-slate-group-llc/id796274625?uo=4>© The Slate Group, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/ea/2e/e3/ea2ee3a9-f7ac-507c-0fd2-9c2c0270f24d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18589967/511450b8-7c2d-11e6-8ecf-5c0f57098f3a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18589967/511450b8-7c2d-11e6-8ecf-5c0f57098f3a.png)
https://cloud.githubusercontent.com/assets/20930745/18589967/511450b8-7c2d-11e6-8ecf-5c0f57098f3a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18589981/61cfb8f2-7c2d-11e6-9871-d1c76ed8ac0a.png
