### ISSUE TITLE
Barometer and Altimeter

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7962]
**App Name:** Barometer and Altimeter
**Bundle ID:** com.plaincode.Barometer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=922859877">922859877</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/barometer-and-altimeter/id922859877?mt=8&uo=4">https://itunes.apple.com/us/app/barometer-and-altimeter/id922859877?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Peter Breitling
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/peter-breitling/id286215120?uo=4>© Peter Breitling</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/21/ae/08/21ae08f2-a231-2f8c-ce56-fa37058d87b0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18588221/d527a18c-7c25-11e6-9ca5-2278b00cf411.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18588221/d527a18c-7c25-11e6-9ca5-2278b00cf411.png)
https://cloud.githubusercontent.com/assets/20930745/18588221/d527a18c-7c25-11e6-9ca5-2278b00cf411.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18588233/e6a8fc12-7c25-11e6-8707-852e226ebedd.png
