### ISSUE TITLE
Barometer & Altimeter for iPhone/iPad

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7963]
**App Name:** Barometer & Altimeter for iPhone/iPad
**Bundle ID:** de.steffenbauereiss.Barometer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923043780">923043780</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/barometer-altimeter-for-iphone/id923043780?mt=8&uo=4">https://itunes.apple.com/us/app/barometer-altimeter-for-iphone/id923043780?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Steffen Bauereiss
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/steffen-bauereiss/id918473002?uo=4>© Steffen Bauereiss</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/44/6e/44/446e44ce-deef-edd8-5fc8-1a9afb8beb6c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18745599/0c9588a4-80c3-11e6-942b-3409902724dc.png)

**Comment by 2Qt2beStr8** [comment]
.. the scala and the numbers are very small and so the icon is not really good ... maybe we should take a other artwork for this icon?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18607849/519d38b8-7cd9-11e6-8408-6e12bb0ec79a.png)
https://cloud.githubusercontent.com/assets/20930745/18607849/519d38b8-7cd9-11e6-8408-6e12bb0ec79a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18607851/69d78654-7cd9-11e6-9fb2-aba81756b96b.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 ...yes... 💭

**Comment by 2Qt2beStr8** [comment]
.... maybe something like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18745599/0c9588a4-80c3-11e6-942b-3409902724dc.png)
https://cloud.githubusercontent.com/assets/20930745/18745599/0c9588a4-80c3-11e6-942b-3409902724dc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18745757/cbec5e08-80c3-11e6-81f6-5d9445af4d9e.png)

**Comment by dreamnet** [comment]
@2Qt2beStr8 Looks great!
