### ISSUE TITLE
Barograph: A barometer and altimeter

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#7964]
**App Name:** Barograph: A barometer and altimeter
**Bundle ID:** com.jackson-myers.Barograph
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926055907">926055907</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/barograph-barometer-altimeter/id926055907?mt=8&uo=4">https://itunes.apple.com/us/app/barograph-barometer-altimeter/id926055907?mt=8&uo=4</a>
**App Version:** 1.27
**Seller:** Jackson Myers
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jackson-myers/id412342440?uo=4>© Jackson Myers</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/a3/fa/96/a3fa9661-a2ce-aa77-9068-0a1924746220/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18594382/03871a98-7c40-11e6-85e4-c1076e62c450.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18587946/a855ba3c-7c24-11e6-978f-cdd4d08398de.png)
https://cloud.githubusercontent.com/assets/20930745/18587946/a855ba3c-7c24-11e6-978f-cdd4d08398de.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18587967/bf263f84-7c24-11e6-9eb4-f61ea1c75522.png

**Comment by Trubbel** [comment]
@2Qt2beStr8 Good work, however I'm not a fan of how the original artwork look like. Looks kind of out of shape.

What about this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18594382/03871a98-7c40-11e6-85e4-c1076e62c450.png)
https://cloud.githubusercontent.com/assets/10730122/18594382/03871a98-7c40-11e6-85e4-c1076e62c450.png
--- ---
Source: _(I used your source, credit is yours)_
https://cloud.githubusercontent.com/assets/10730122/18594381/0384685c-7c40-11e6-8af6-846cee5a02c7.png

**Comment by 2Qt2beStr8** [comment]
@Trubbel  yes, i am with you ... it looks really better
