### ISSUE TITLE
Munich App

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#7967]
**App Name:** Munich App
**Bundle ID:** de.muenchen.muenchen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=478729527">478729527</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/munich-app/id478729527?mt=8&uo=4">https://itunes.apple.com/us/app/munich-app/id478729527?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Portal Muenchen Betriebs-GmbH & Co. KG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/portal-munchen-betriebs-gmbh/id478730490?uo=4>© Portal München Betriebs-GmbH & Co. KG</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/7d/2f/6d/7d2f6d50-0c5a-7a95-a4af-9bea01e9946b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18598880/9fdff4f4-7c55-11e6-874c-fb1205bc8354.png)

**Comment by Checkit23** [comment]
That's what I came up with, but to be honest, I don't really like it.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18597504/a7d12f04-7c4e-11e6-9767-444b4b309a7c.png)

https://cloud.githubusercontent.com/assets/16171251/18597504/a7d12f04-7c4e-11e6-9767-444b4b309a7c.png

![de muenchen muenchen](https://cloud.githubusercontent.com/assets/16171251/18597529/c76f7456-7c4e-11e6-985b-67cbe3f90ef6.png)

**Comment by 2Qt2beStr8** [comment]
... and whats about this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18597715/7a4831ee-7c4f-11e6-9d5d-6ccebde9c6d9.png)
https://cloud.githubusercontent.com/assets/20930745/18597715/7a4831ee-7c4f-11e6-9d5d-6ccebde9c6d9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18597729/8e3803fa-7c4f-11e6-8e72-6b648f678e0d.png

**Comment by Checkit23** [comment]
Year, it does look better, but I still prefer the older artwork used for this app. I've made an icon for it some time ago, but I didn't upload it as I wasn't fully satisfied with the quality, plus I don't have the mask anymore:-(

![de muenchen muenchen-large](https://cloud.githubusercontent.com/assets/16171251/18598145/ad6e5fc4-7c51-11e6-9825-30877d2dc16c.png)

Artwork: https://cloud.githubusercontent.com/assets/16171251/18598155/b60ce9a2-7c51-11e6-8a5d-5087a91e0aec.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18598766/d55b5976-7c54-11e6-85dd-086e74187ad3.png)
https://cloud.githubusercontent.com/assets/20930745/18598766/d55b5976-7c54-11e6-85dd-086e74187ad3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18598779/ebd61c86-7c54-11e6-958a-3ba1f1bf47d4.png

**Comment by 2Qt2beStr8** [comment]
do you like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18598880/9fdff4f4-7c55-11e6-874c-fb1205bc8354.png)
https://cloud.githubusercontent.com/assets/20930745/18598880/9fdff4f4-7c55-11e6-874c-fb1205bc8354.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18598892/b213c72c-7c55-11e6-9c6d-848d217bafdf.png

**Comment by Checkit23** [comment]
Looks great 👍
