### ISSUE TITLE
NOAA World Radar - Rain & Weather Forecast + Hurricane Tracker

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#7972]
**App Name:** NOAA World Radar - Rain & Weather Forecast + Hurricane Tracker
**Bundle ID:** com.itwcalculator.worldradar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=649246860">649246860</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/noaa-world-radar-rain-weather/id649246860?mt=8&uo=4">https://itunes.apple.com/us/app/noaa-world-radar-rain-weather/id649246860?mt=8&uo=4</a>
**App Version:** 3.1.8
**Seller:** Impala Studios B.V.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/impala-studios/id1063279743?uo=4>© Impala Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/7f/96/f6/7f96f665-fb2d-5174-8e71-0ae3a5b4386d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18607498/5b3dfd72-7cce-11e6-8dc9-e5bf4c541a7e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18607255/e4456ecc-7cc7-11e6-84e8-50d9fd79ebf5.png)
https://cloud.githubusercontent.com/assets/20930745/18607255/e4456ecc-7cc7-11e6-84e8-50d9fd79ebf5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18607260/0866ce5e-7cc8-11e6-819b-36b3dae03b2e.png

**Comment by Checkit23** [comment]
Nice work :-)

**Comment by dreamnet** [comment]
Just rounded the corners...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18607498/5b3dfd72-7cce-11e6-8dc9-e5bf4c541a7e.png)
https://cloud.githubusercontent.com/assets/2068130/18607498/5b3dfd72-7cce-11e6-8dc9-e5bf4c541a7e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18607501/6b1deb4e-7cce-11e6-8dc2-8a9a0638b7e8.png
