### ISSUE TITLE
Scanner Pro 7 - PDF scanner with OCR

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#7973]
**App Name:** Scanner Pro 7 - PDF scanner with OCR
**Bundle ID:** com.readdle.Scanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=333710667">333710667</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scanner-pro-7-pdf-scanner/id333710667?mt=8&uo=4">https://itunes.apple.com/us/app/scanner-pro-7-pdf-scanner/id333710667?mt=8&uo=4</a>
**App Version:** 7.1
**Seller:** Igor Zhadanov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/readdle/id285035419?uo=4>© Readdle</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/30/ad/d8/30add891-d86d-6e32-8eca-a1453263792f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18599731/1daf5920-7c5a-11e6-9b46-b0dfcb55b6c7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18599731/1daf5920-7c5a-11e6-9b46-b0dfcb55b6c7.png)
https://cloud.githubusercontent.com/assets/20930745/18599731/1daf5920-7c5a-11e6-9b46-b0dfcb55b6c7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18599746/2f8a55c8-7c5a-11e6-9c6b-6f003f96b198.png
