### ISSUE TITLE
Rollit

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#7974]
**App Name:** Rollit, photo transfer app
**Bundle ID:** com.yamanjaiouch.rollit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=741790426">741790426</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rollit-photo-transfer-app/id741790426?mt=8&uo=4">https://itunes.apple.com/us/app/rollit-photo-transfer-app/id741790426?mt=8&uo=4</a>
**App Version:** 1.2.5
**Seller:** chaman chlach
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chaman-chlach/id907477610?uo=4>© chaman chlach</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/8a/b3/68/8ab36875-525a-ed55-1c23-b3c22568d579/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18601052/1228f942-7c61-11e6-961c-d7061752041e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18601052/1228f942-7c61-11e6-961c-d7061752041e.png)
https://cloud.githubusercontent.com/assets/20930745/18601052/1228f942-7c61-11e6-961c-d7061752041e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18601075/2dad7166-7c61-11e6-8553-76b0bd810a77.png
