### ISSUE TITLE
Tresorit

### ISSUE THREAD

**Issue by GMVargas** [glasklart/hd#7975]
**App Name:** Tresorit
**Bundle ID:** com.tresorit.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=722163232">722163232</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tresorit/id722163232?mt=8&uo=4">https://itunes.apple.com/us/app/tresorit/id722163232?mt=8&uo=4</a>
**App Version:** 3.0.601.507
**Seller:** Tresorit Kft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tresorit/id722163235?uo=4>© Tresorit</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/07/6b/12/076b1270-5693-e110-e0ef-0181c14c4527/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18603610/70e53af6-7c73-11e6-9fc2-b08d8c9e6dbe.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18603610/70e53af6-7c73-11e6-9fc2-b08d8c9e6dbe.png)
https://cloud.githubusercontent.com/assets/2068130/18603610/70e53af6-7c73-11e6-9fc2-b08d8c9e6dbe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18603617/7e5c13bc-7c73-11e6-9a27-3e565205265b.png
