### ISSUE TITLE
Authenticator

### ISSUE THREAD

**Issue by GMVargas** [glasklart/hd#7976]
**App Name:** Authenticator
**Bundle ID:** me.mattrubin.authenticator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=766157276">766157276</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/authenticator/id766157276?mt=8&uo=4">https://itunes.apple.com/us/app/authenticator/id766157276?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Matt Rubin
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/matt-rubin/id766157279?uo=4>© Matt Rubin</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/df/f0/67/dff06789-a9dc-ed24-5b18-3a7618b7e96c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18602986/057fe81a-7c6e-11e6-884a-90570ac26967.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18602986/057fe81a-7c6e-11e6-884a-90570ac26967.png)
https://cloud.githubusercontent.com/assets/10730122/18602986/057fe81a-7c6e-11e6-884a-90570ac26967.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18602987/05803e6e-7c6e-11e6-8e8c-3d023aca4855.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18602998/1c69ced8-7c6e-11e6-9e01-bd071df25466.png)
https://cloud.githubusercontent.com/assets/10730122/18602998/1c69ced8-7c6e-11e6-9e01-bd071df25466.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18602999/1c810378-7c6e-11e6-99e3-33c00e8be252.png

**Comment by dreamnet** [comment]
@Trubbel First one is just fine. 👍
