### ISSUE TITLE
Circle Pay

### ISSUE THREAD

**Issue by GMVargas** [glasklart/hd#7978]
**App Name:** Circle Pay
**Bundle ID:** com.circle.CircleApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=920164002">920164002</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/circle-pay/id920164002?mt=8&uo=4">https://itunes.apple.com/us/app/circle-pay/id920164002?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Circle Internet Financial, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/circle-internet-financial/id920164001?uo=4>© Circle Internet Financial, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/c8/00/06/c8000607-504b-dfd1-05bf-ac7a0bdac208/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18603490/39796ed0-7c72-11e6-8f3c-7406b66e7983.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18603490/39796ed0-7c72-11e6-8f3c-7406b66e7983.png)
https://cloud.githubusercontent.com/assets/2068130/18603490/39796ed0-7c72-11e6-8f3c-7406b66e7983.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18603496/47d94482-7c72-11e6-8a7e-988a35ea6b27.png
