### ISSUE TITLE
Symbolab - Calculator with steps

### ISSUE THREAD

**Issue by GMVargas** [glasklart/hd#7979]
**App Name:** Symbolab - Calculator with steps
**Bundle ID:** com.symbolab.symbolab
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=876942533">876942533</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/symbolab-calculator-steps/id876942533?mt=8&uo=4">https://itunes.apple.com/us/app/symbolab-calculator-steps/id876942533?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Eqsquest Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/symbolab/id876942536?uo=4>© Symbolab</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/d3/a8/e5/d3a8e548-51fb-2c52-6c1d-19bcb25d52f9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18603361/0dd28826-7c71-11e6-9b29-b6a53cb4a700.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18603361/0dd28826-7c71-11e6-9b29-b6a53cb4a700.png)
https://cloud.githubusercontent.com/assets/2068130/18603361/0dd28826-7c71-11e6-9b29-b6a53cb4a700.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18603371/1c3938f6-7c71-11e6-9fce-f99ebeca10dd.png
