### ISSUE TITLE
Transmission: Connect to communicate

### ISSUE THREAD

**Issue by GMVargas** [glasklart/hd#7981]
**App Name:** Transmission: Connect to communicate
**Bundle ID:** com.lojugames.games.transmission
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=917778256">917778256</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/transmission-connect-to-communicate/id917778256?mt=8&uo=4">https://itunes.apple.com/us/app/transmission-connect-to-communicate/id917778256?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** SCMG Enterprises Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/science-museum/id917778255?uo=4>© Science Museum</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/e4/39/a4/e439a492-9a13-c353-7c7f-9de8e06f7c31/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18606139/bf24253c-7ca6-11e6-9bf1-86640f48c43b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18606139/bf24253c-7ca6-11e6-9bf1-86640f48c43b.png)
https://cloud.githubusercontent.com/assets/2068130/18606139/bf24253c-7ca6-11e6-9bf1-86640f48c43b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18606142/cea0a558-7ca6-11e6-9492-a3d5f6829733.png
