### ISSUE TITLE
Telepaint

### ISSUE THREAD

**Issue by GMVargas** [glasklart/hd#7982]
**App Name:** Telepaint
**Bundle ID:** acidnerve.telepaint
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1031530508">1031530508</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/telepaint/id1031530508?mt=8&uo=4">https://itunes.apple.com/us/app/telepaint/id1031530508?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Acid Nerve Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/acid-nerve/id1031530507?uo=4>© Acid Nerve</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/8c/24/1c/8c241c91-dae9-6d3f-f09f-8529f707b211/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18607353/6c2554ea-7cca-11e6-83af-5f95e26e8ac0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18607353/6c2554ea-7cca-11e6-83af-5f95e26e8ac0.png)
https://cloud.githubusercontent.com/assets/20930745/18607353/6c2554ea-7cca-11e6-83af-5f95e26e8ac0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18607359/80692a80-7cca-11e6-9062-7d18c41fb15a.png
