### ISSUE TITLE
PrintCentral Pro

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7984]
**App Name:** PrintCentral Pro
**Bundle ID:** com.eurosmartz.mobile.printcentralpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426362921">426362921</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/printcentral-pro/id426362921?mt=8&uo=4">https://itunes.apple.com/us/app/printcentral-pro/id426362921?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** EuroSmartz Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eurosmartz-ltd/id299105918?uo=4>© EuroSmartz Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/cc/d4/8a/ccd48ace-9736-218a-458e-72db7dee80f3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18659629/1b486afa-7f0c-11e6-9b26-f6cb2a7b508b.png)

**Comment by dreamnet** [comment]
Refers to #1437.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18659629/1b486afa-7f0c-11e6-9b26-f6cb2a7b508b.png)
https://cloud.githubusercontent.com/assets/20930745/18659629/1b486afa-7f0c-11e6-9b26-f6cb2a7b508b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18659644/2e2010ec-7f0c-11e6-8f5b-86e25ca99587.png
