### ISSUE TITLE
QuickScanner: OCR PDF Scanner & Printer for Documents Emails Receipts

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7985]
**App Name:** QuickScanner: OCR PDF Scanner & Printer for Documents Emails Receipts
**Bundle ID:** com.saphiretech.quickscanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1143343713">1143343713</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quickscanner-ocr-pdf-scanner/id1143343713?mt=8&uo=4">https://itunes.apple.com/us/app/quickscanner-ocr-pdf-scanner/id1143343713?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Guyverson Junior Vernous
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/guyverson-junior-vernous/id961400952?uo=4>© Guyverson Junior Vernous</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/bf/28/cd/bf28cd4b-0a42-47d9-fe67-e6cc9e725061/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18610020/f890d558-7d10-11e6-9136-b57f2cfb5c85.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18610020/f890d558-7d10-11e6-9136-b57f2cfb5c85.png)
https://cloud.githubusercontent.com/assets/20930745/18610020/f890d558-7d10-11e6-9136-b57f2cfb5c85.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18610022/0a131f8e-7d11-11e6-981b-f3c6dc46ef4b.png
