### ISSUE TITLE
Stack –  Read smarter: News, Blogs and Articles Daily

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7988]
**App Name:** Stack –  Read smarter: News, Blogs and Articles Daily
**Bundle ID:** io.fusetech.getstack
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1140196914">1140196914</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stack-read-smarter-news-blogs/id1140196914?mt=8&uo=4">https://itunes.apple.com/us/app/stack-read-smarter-news-blogs/id1140196914?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** FUSE MOBILE TECHNOLOGIES LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stack-ltd/id1140196913?uo=4>© Stack Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/9f/dc/15/9fdc15b7-a17c-094d-1ee1-e9b5c6bdbf20/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18610480/c8573fdc-7d1d-11e6-8a01-49e014ef83f3.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18609944/933a30ca-7cdc-11e6-90fa-1f3bb6f661dd.png)

https://cloud.githubusercontent.com/assets/3704186/18609944/933a30ca-7cdc-11e6-90fa-1f3bb6f661dd.png

https://cloud.githubusercontent.com/assets/3704186/18609947/9ab539a8-7cdc-11e6-978e-45a44823026f.png

**Comment by 2Qt2beStr8** [comment]
I think it's too big ;-)

**Comment by l8er4now** [comment]
Yeah after I posted it I realized it, if you want to update it, be my guest, I'll get to it later today.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18610480/c8573fdc-7d1d-11e6-8a01-49e014ef83f3.png)
https://cloud.githubusercontent.com/assets/2068130/18610480/c8573fdc-7d1d-11e6-8a01-49e014ef83f3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18610482/d8270be0-7d1d-11e6-8281-e76d3e5acf4e.png
