### ISSUE TITLE
Trade Rumors - Baseball, Football, Basketball, Hockey News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7990]
**App Name:** Trade Rumors - Baseball, Football, Basketball, Hockey News
**Bundle ID:** com.traderumors.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=891722241">891722241</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trade-rumors-baseball-football/id891722241?mt=8&uo=4">https://itunes.apple.com/us/app/trade-rumors-baseball-football/id891722241?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Dierkes Information Services, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dierkes-information-services/id396443102?uo=4>© Dierkes Information Services, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple22/v4/01/a0/9b/01a09b32-b791-38fd-44ce-61075a631ac3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18666874/6556cf52-7f2e-11e6-8fc9-5462ca2ae4b5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18666728/a6fa4994-7f2d-11e6-8cd3-46a6e58537a4.png)
https://cloud.githubusercontent.com/assets/20930745/18666728/a6fa4994-7f2d-11e6-8cd3-46a6e58537a4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18666747/b9d8eb74-7f2d-11e6-834b-95f8b7ad451a.png)

**Comment by dreamnet** [comment]
@2Qt2beStr8 Wohooooo.... 😱 🎆 The result looks like grescyles, but the source is ok.... 👍

**Comment by 2Qt2beStr8** [comment]
i know it is not perfect ... but it was the best result of many attempts

**Comment by dreamnet** [comment]
@2Qt2beStr8 Well, I think that's great work!
