### ISSUE TITLE
Vitalbook - Health and Fitness

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7991]
**App Name:** Vitalbook - Health and Fitness
**Bundle ID:** com.amuser.vitalkitlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=885185987">885185987</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vitalbook-health-and-fitness/id885185987?mt=8&uo=4">https://itunes.apple.com/us/app/vitalbook-health-and-fitness/id885185987?mt=8&uo=4</a>
**App Version:** 1.4.23
**Seller:** Naoya Araki
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/naoya-araki/id435849505?uo=4>© Naoya Araki</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/e0/07/fa/e007fa54-8411-fb36-957f-ad2182dcbb17/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18611458/1bde454e-7d3a-11e6-8a3a-281d788bc347.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18611458/1bde454e-7d3a-11e6-8a3a-281d788bc347.png)
https://cloud.githubusercontent.com/assets/20930745/18611458/1bde454e-7d3a-11e6-8a3a-281d788bc347.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18611461/2dfa821a-7d3a-11e6-8f87-474ef4aef9cf.png
