### ISSUE TITLE
Next Episode - Track the TV Shows and Movies You Watch

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7994]
**App Name:** Next Episode - Track the TV Shows and Movies You Watch
**Bundle ID:** net.funforcell.nextepisode
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347009526">347009526</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/next-episode-track-tv-shows/id347009526?mt=8&uo=4">https://itunes.apple.com/us/app/next-episode-track-tv-shows/id347009526?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** Nikolay Nachev
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nikolay-nachev/id306581292?uo=4>© Nikolay Nachev</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/fb/10/fa/fb10fa69-17d6-5c66-ecac-5fadff98e664/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18684774/c1b673dc-7f75-11e6-9c01-b258a2b55cc3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18613700/2abee320-7d80-11e6-95c0-b8429b54c4bc.png)
https://cloud.githubusercontent.com/assets/20930745/18613700/2abee320-7d80-11e6-95c0-b8429b54c4bc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18613716/70642b60-7d80-11e6-84b8-0a1f4a54e7d3.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18664434/cfe1b474-7f22-11e6-95bf-73ff026e27c3.png)
https://cloud.githubusercontent.com/assets/20930745/18664434/cfe1b474-7f22-11e6-95bf-73ff026e27c3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18664453/e88877ce-7f22-11e6-9970-8b0cd469fcf2.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 The last one is great, but I think we need to get rid of the shadow...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18684774/c1b673dc-7f75-11e6-9c01-b258a2b55cc3.png)
https://cloud.githubusercontent.com/assets/2068130/18684774/c1b673dc-7f75-11e6-9c01-b258a2b55cc3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18684793/d0b471cc-7f75-11e6-9378-88fab06607aa.png
