### ISSUE TITLE
Redbox

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7995]
**App Name:** Redbox
**Bundle ID:** com.redbox.m
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=339532909">339532909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/redbox/id339532909?mt=8&uo=4">https://itunes.apple.com/us/app/redbox/id339532909?mt=8&uo=4</a>
**App Version:** 5.32.0
**Seller:** redbox
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/redbox/id339532912?uo=4">© redbox</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/8f/15/5f/8f155f90-5ce2-8a23-c4e0-d599f2ac2ba0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32146697-b5d8ba1c-bcdb-11e7-8b4f-02c5ec6e732c.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18611126/c2bcb3d2-7cfe-11e6-982d-f56042c4527e.png)

https://cloud.githubusercontent.com/assets/3704186/18611126/c2bcb3d2-7cfe-11e6-982d-f56042c4527e.png

https://cloud.githubusercontent.com/assets/3704186/18611127/c9f04a1a-7cfe-11e6-917b-c2e9bf03be9c.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Redbox
**Bundle ID:** com.redbox.m
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=339532909">339532909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/redbox/id339532909?mt=8&uo=4">https://itunes.apple.com/us/app/redbox/id339532909?mt=8&uo=4</a>
**App Version:** 5.32.0
**Seller:** redbox
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/redbox/id339532912?uo=4">© redbox</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/8f/15/5f/8f155f90-5ce2-8a23-c4e0-d599f2ac2ba0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32146697-b5d8ba1c-bcdb-11e7-8b4f-02c5ec6e732c.png)
https://user-images.githubusercontent.com/2068130/32146697-b5d8ba1c-bcdb-11e7-8b4f-02c5ec6e732c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32146702-c4f79a2c-bcdb-11e7-9c90-4e0399995f72.png
