### ISSUE TITLE
AliExpress Shopping App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7998]
**App Name:** AliExpress Shopping App
**Bundle ID:** com.alibaba.iAliexpress
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=436672029">436672029</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aliexpress-shopping-app/id436672029?mt=8&uo=4">https://itunes.apple.com/us/app/aliexpress-shopping-app/id436672029?mt=8&uo=4</a>
**App Version:** 5.0.3
**Seller:** Alibaba.com Singapore E-Commerce Private Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/alibaba/id744923901?uo=4>© Alibaba</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/ff/d6/9d/ffd69db9-1a52-f97f-0d1a-f9b96beaf624/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18617036/9ec6b418-7dc7-11e6-82c8-a646325f19dc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18616052/6fd7b79a-7db5-11e6-8036-66d53e30a8cb.png)
https://cloud.githubusercontent.com/assets/20930745/18616052/6fd7b79a-7db5-11e6-8036-66d53e30a8cb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18616066/a8275f2e-7db5-11e6-9c13-44fdb4d295c2.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18617036/9ec6b418-7dc7-11e6-82c8-a646325f19dc.png)
https://cloud.githubusercontent.com/assets/2068130/18617036/9ec6b418-7dc7-11e6-82c8-a646325f19dc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18617043/afbaeafa-7dc7-11e6-8e6d-cb7a251daed0.png
