### ISSUE TITLE
Delivered! – Package Tracking Made Simple

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#7999]
**App Name:** Delivered! – Package Tracking Made Simple
**Bundle ID:** com.madeatsampa.Delivered
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=700693743">700693743</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/delivered!-package-tracking/id700693743?mt=8&uo=4">https://itunes.apple.com/us/app/delivered!-package-tracking/id700693743?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** Fernando Saragoca
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fernando-saragoca/id351110518?uo=4>© Fernando Saragoca</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/18/1c/04/181c04f1-b541-5e2d-f672-45cf1d1a76b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18615944/1cca3f98-7db3-11e6-8feb-4c5673708df8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18615892/07126424-7db2-11e6-9fc9-a73711e73c73.png)

https://cloud.githubusercontent.com/assets/20930745/18615892/07126424-7db2-11e6-9fc9-a73711e73c73.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18615903/389ca00e-7db2-11e6-8027-823e4cce5499.png
