### ISSUE TITLE
Doodle Buddy - Paint, Draw, Scribble, Sketch - It's Addictive!

### ISSUE THREAD

**Issue by slipko** [glasklart/hd#8]
**App Name:** Doodle Buddy - Paint, Draw, Scribble, Sketch - It's Addictive!
**Bundle ID:** com.pinger.chalktalk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=313232441">313232441</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/doodle-buddy-paint-draw-scribble-sketch-its-addictive/id313232441?mt=8&uo=4">https://itunes.apple.com/us/app/doodle-buddy-paint-draw-scribble-sketch-its-addictive/id313232441?mt=8&uo=4</a>
**App Version:** 1.60
**Seller:** Dinopilot
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dinopilot/id1012073844?uo=4">© Dinopilot</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/51/20/e8/5120e888-914f-a3f9-10a6-ddb19d7adbe8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468481-11e42330-031f-11e8-9c19-a62ded4f98b4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468481-11e42330-031f-11e8-9c19-a62ded4f98b4.png)
https://user-images.githubusercontent.com/2068130/35468481-11e42330-031f-11e8-9c19-a62ded4f98b4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/35468484-23d5a7b2-031f-11e8-8668-f11e1f82adfa.png
