### ISSUE TITLE
PhotoLink - widget for photo and web pages

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8002]
**App Name:** PhotoLink - widget for photo and web pages
**Bundle ID:** com.plumit.widgetnotes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1046238794">1046238794</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photolink-widget-for-photo/id1046238794?mt=8&uo=4">https://itunes.apple.com/us/app/photolink-widget-for-photo/id1046238794?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Ianis Plumit
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ianis-plumit/id984165260?uo=4>© Ianis Plumit</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/45/09/c8/4509c840-de2c-0043-24b4-8497c0d86691/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18615467/f2df06b0-7d75-11e6-88cb-26fb578d65ab.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18615467/f2df06b0-7d75-11e6-88cb-26fb578d65ab.png)

https://cloud.githubusercontent.com/assets/3704186/18615467/f2df06b0-7d75-11e6-88cb-26fb578d65ab.png

https://cloud.githubusercontent.com/assets/3704186/18615469/fb51d534-7d75-11e6-8f20-fe205d473bf2.png

**Comment by 2Qt2beStr8** [comment]
:-)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18616278/4a2d5690-7db9-11e6-9ac1-f81728583d59.png)
https://cloud.githubusercontent.com/assets/20930745/18616278/4a2d5690-7db9-11e6-9ac1-f81728583d59.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18616283/6ea3ecd2-7db9-11e6-87cb-696e19050243.png

**Comment by dreamnet** [comment]
First one is just fine.
