### ISSUE TITLE
ReaderView - Reader Mode for Safari

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8003]
**App Name:** ReaderView - Reader Mode for Safari
**Bundle ID:** com.appblit.readerapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=954343811">954343811</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/readerview-reader-mode-for/id954343811?mt=8&uo=4">https://itunes.apple.com/us/app/readerview-reader-mode-for/id954343811?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** AppBlit LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appblit-llc/id295536769?uo=4>© AppBlit LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/18/21/71/18217159-3d3a-bc21-15bd-f3b5c26ce23b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18616126/93c995aa-7db6-11e6-8530-9c57574997d5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18616126/93c995aa-7db6-11e6-8530-9c57574997d5.png)
https://cloud.githubusercontent.com/assets/20930745/18616126/93c995aa-7db6-11e6-8530-9c57574997d5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18616132/aa3ed0ca-7db6-11e6-9951-15959793b278.png
