### ISSUE TITLE
iNet Pro - Network Scanner

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8012]
**App Name:** iNet Pro - Network Scanner
**Bundle ID:** com.bananaglue.iNet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=305242949">305242949</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inet-pro-network-scanner/id305242949?mt=8&uo=4">https://itunes.apple.com/us/app/inet-pro-network-scanner/id305242949?mt=8&uo=4</a>
**App Version:** 2.2.10
**Seller:** BananaGlue GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bananaglue-gmbh/id298348769?uo=4>© BananaGlue GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/e3/11/e0/e311e07d-9471-beaa-3fb0-8054134fac2b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18618086/6c45908c-7ddf-11e6-8707-c2df026d96b0.png)

**Comment by dreamnet** [comment]
Refers to #3248.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18618086/6c45908c-7ddf-11e6-8707-c2df026d96b0.png)
https://cloud.githubusercontent.com/assets/2068130/18618086/6c45908c-7ddf-11e6-8707-c2df026d96b0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18618090/7a4e8986-7ddf-11e6-9de5-d6c4b209e3d8.png

**Comment by Sly-Fi** [comment]
This icon is missing from 5.0.0 release

**Comment by Trubbel** [comment]
@Sly-Fi This icon was recently added to the master, you have to wait until the next release of Glasklart.
