### ISSUE TITLE
Multiframe — Photo Collage Maker and Picture Editor

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8014]
**App Name:** Multiframe — Photo Collage Maker and Picture Editor
**Bundle ID:** com.apalonapps.frames
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=749169888">749169888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/multiframe-photo-collage-maker/id749169888?mt=8&uo=4">https://itunes.apple.com/us/app/multiframe-photo-collage-maker/id749169888?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** IAC Search & Media Europe Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apalon-apps/id749046894?uo=4>© Apalon Apps</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/72/87/6f/72876f0e-2c08-694d-f375-1f2b7ab544ad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18628567/338cdd04-7e61-11e6-8996-f108d82405e8.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18618173/6ff7b442-7de1-11e6-94de-e7b5405124c2.png)
https://cloud.githubusercontent.com/assets/10730122/18618173/6ff7b442-7de1-11e6-94de-e7b5405124c2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18618172/6ff6a584-7de1-11e6-86e9-65e12bf582c9.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18624358/644530d2-7e47-11e6-8c1b-4419083689a0.png)
https://cloud.githubusercontent.com/assets/20930745/18624358/644530d2-7e47-11e6-8c1b-4419083689a0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18624367/7bfd8d50-7e47-11e6-9c3c-61f370028bcd.png

**Comment by Trubbel** [comment]
Yeah now when I look at my icon I don't really know what I was thinking. :laughing: 

@2Qt2beStr8 I like your icon, just fixing some minor things,
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18628567/338cdd04-7e61-11e6-8996-f108d82405e8.png)
https://cloud.githubusercontent.com/assets/10730122/18628567/338cdd04-7e61-11e6-8996-f108d82405e8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18628568/33915c58-7e61-11e6-8659-605dfb9a0ee0.png
