### ISSUE TITLE
LEGO® TV

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8015]
**App Name:** LEGO® TV
**Bundle ID:** com.lego.legotv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=659284915">659284915</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lego-tv/id659284915?mt=8&uo=4">https://itunes.apple.com/us/app/lego-tv/id659284915?mt=8&uo=4</a>
**App Version:** 2.1.9
**Seller:** LEGO Systems, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lego-systems-inc/id347363505?uo=4>© LEGO Systems, Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/41/d1/e9/41d1e912-1999-b96c-e869-e94087ce8e15/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18626577/3610a14c-7e56-11e6-9dad-2abb32ee6afd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18626577/3610a14c-7e56-11e6-9dad-2abb32ee6afd.png)
https://cloud.githubusercontent.com/assets/20930745/18626577/3610a14c-7e56-11e6-9dad-2abb32ee6afd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18626597/4c93b788-7e56-11e6-8026-35765941232f.png
