### ISSUE TITLE
Chronicle - Bill Management & Reminders

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8017]
**App Name:** Chronicle - Bill Management & Reminders
**Bundle ID:** com.LittleFin.Chronicle-Touch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=572561420">572561420</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chronicle-bill-management/id572561420?mt=8&uo=4">https://itunes.apple.com/us/app/chronicle-bill-management/id572561420?mt=8&uo=4</a>
**App Version:** 6.5.0
**Seller:** LittleFin LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/littlefin-llc/id402352690?uo=4>© LittleFin LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/d5/43/1a/d5431ac9-4a58-2902-431c-d33767461787/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18618576/fd9fedb6-7de9-11e6-9cea-535b572df37d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18618576/fd9fedb6-7de9-11e6-9cea-535b572df37d.png)
https://cloud.githubusercontent.com/assets/20930745/18618576/fd9fedb6-7de9-11e6-9cea-535b572df37d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18618583/12097916-7dea-11e6-903b-7cc8581c38de.png
