### ISSUE TITLE
Bankin’ - Best App to manage my finances

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#802]
**App Name:** Bankin’ - Best App to manage my finances
**Bundle ID:** com.perspecteev.app2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447040033">447040033</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bankin-best-app-to-manage/id447040033?mt=8&uo=4">https://itunes.apple.com/us/app/bankin-best-app-to-manage/id447040033?mt=8&uo=4</a>
**App Version:** 3.2.1
**Seller:** Perspecteev
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/perspecteev/id447040036?uo=4>© Perspecteev</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/17/13/d0/1713d096-8a3f-1931-438b-25146ca0ac7c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408741/e7eca5d2-92c4-11e6-85a5-e7ac05b07b8c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408741/e7eca5d2-92c4-11e6-85a5-e7ac05b07b8c.png)
https://cloud.githubusercontent.com/assets/20930745/19408741/e7eca5d2-92c4-11e6-85a5-e7ac05b07b8c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19408746/f63e96f4-92c4-11e6-9432-edef04ea7fff.png
