### ISSUE TITLE
Camera+

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8020]
**App Name:** Camera+
**Bundle ID:** com.taptaptap.CameraPlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=329670577">329670577</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camera+/id329670577?mt=8&uo=4">https://itunes.apple.com/us/app/camera+/id329670577?mt=8&uo=4</a>
**App Version:** 8.0.2
**Seller:** tap tap tap LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tap-tap-tap/id325758143?uo=4>© tap tap tap</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple18/v4/58/ee/e0/58eee05a-aa22-9f5c-7786-4f6ef5217a69/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18618846/55dfb858-7def-11e6-9cce-8dd9b8dc4054.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18618846/55dfb858-7def-11e6-9cce-8dd9b8dc4054.png)
https://cloud.githubusercontent.com/assets/20930745/18618846/55dfb858-7def-11e6-9cce-8dd9b8dc4054.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18618847/6d795294-7def-11e6-82dd-8269fdcdf923.png
