### ISSUE TITLE
Planes Live - Flight Status Tracker and Aircraft Radar

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8021]
**App Name:** Planes Live - Flight Status Tracker and Aircraft Radar
**Bundle ID:** com.apalonapps.flightradartracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1064962398">1064962398</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/planes-live-flight-status/id1064962398?mt=8&uo=4">https://itunes.apple.com/us/app/planes-live-flight-status/id1064962398?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** IAC Search & Media Europe Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apalon-apps/id749046894?uo=4>© Apalon Apps</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/83/80/97/838097a2-af11-2d27-512b-228342073711/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18618850/8a48d5e8-7def-11e6-996d-ec620e9c63fe.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18618757/62c83efc-7ded-11e6-99c7-6fd54470d5db.png)

https://cloud.githubusercontent.com/assets/16171251/18618757/62c83efc-7ded-11e6-99c7-6fd54470d5db.png

https://cloud.githubusercontent.com/assets/16171251/18618763/6c5f991a-7ded-11e6-9e8c-a83607c1ed91.png

**Comment by dreamnet** [comment]
Just added a small line in the middle of the plane.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18618850/8a48d5e8-7def-11e6-996d-ec620e9c63fe.png)
https://cloud.githubusercontent.com/assets/2068130/18618850/8a48d5e8-7def-11e6-996d-ec620e9c63fe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18618854/9944e230-7def-11e6-8a16-6d5d583020d7.png
