### ISSUE TITLE
Find My Car - GPS Auto Parking Location Finder, Reminder & Vehicle Tracking App

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8022]
**App Name:** Find My Car - GPS Auto Parking Location Finder, Reminder & Vehicle Tracking App
**Bundle ID:** com.appcelerate.FindMyCar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=815542507">815542507</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/find-my-car-gps-auto-parking/id815542507?mt=8&uo=4">https://itunes.apple.com/us/app/find-my-car-gps-auto-parking/id815542507?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Dennis Donner
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dennis-donner/id815542510?uo=4>© Dennis Donner</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/be/2f/1a/be2f1a80-21bf-50f0-729f-45d732b30709/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18618825/e8fd0ff6-7dee-11e6-838d-48ef83f3f390.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18618785/f4541f8a-7ded-11e6-87fd-aea8ae023600.png)

https://cloud.githubusercontent.com/assets/16171251/18618785/f4541f8a-7ded-11e6-87fd-aea8ae023600.png

https://cloud.githubusercontent.com/assets/16171251/18618783/e7eec8e4-7ded-11e6-9883-a5c4fa6c9274.png

**Comment by Trubbel** [comment]
@Checkit23 What about this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18618825/e8fd0ff6-7dee-11e6-838d-48ef83f3f390.png)
https://cloud.githubusercontent.com/assets/10730122/18618825/e8fd0ff6-7dee-11e6-838d-48ef83f3f390.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18618824/e8e644ba-7dee-11e6-8dfe-61f21b5c40ca.png
