### ISSUE TITLE
Wikibot 2 — A Wikipedia Articles Reader

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8023]
**App Name:** Wikibot 2 — A Wikipedia Articles Reader
**Bundle ID:** com.avocadohills.wikibot2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=807214214">807214214</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wikibot-2-wikipedia-articles/id807214214?mt=8&uo=4">https://itunes.apple.com/us/app/wikibot-2-wikipedia-articles/id807214214?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Avocado Hills, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/avocado-hills-inc./id375619086?uo=4>© Avocado Hills, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/dd/82/99/dd829947-6e02-aaaa-de2d-9b88133d4c7c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18618945/094a5884-7df1-11e6-9322-e4e95ee1a24f.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18618835/1945f146-7def-11e6-94b8-c87e30afcfb4.png)

https://cloud.githubusercontent.com/assets/16171251/18618835/1945f146-7def-11e6-94b8-c87e30afcfb4.png

https://cloud.githubusercontent.com/assets/16171251/18618842/37962670-7def-11e6-92ae-82ee651eedc7.png

**Comment by dreamnet** [comment]
Needs to be off-centered like the original.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18618945/094a5884-7df1-11e6-9322-e4e95ee1a24f.png)
https://cloud.githubusercontent.com/assets/2068130/18618945/094a5884-7df1-11e6-9322-e4e95ee1a24f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18618949/18f9db10-7df1-11e6-9d8f-b6cf46e8dd11.png
