### ISSUE TITLE
Good Morning - Alarm Clock

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8027]
**App Name:** Good Morning - Alarm Clock
**Bundle ID:** com.apalonapps.smartalarm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989254177">989254177</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/good-morning-alarm-clock/id989254177?uo=4">https://apps.apple.com/us/app/good-morning-alarm-clock/id989254177?uo=4</a>
**App Version:** 1.7
**Seller:** IAC Search & Media Europe Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apalon-apps/id749046894?uo=4">© Apalon Apps</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/8b/83/6f/8b836ff7-afb9-02ab-eecd-fe482e68a206/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60626791-3cd5d480-9dec-11e9-94b3-8e9e40c8977b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619208/e5a5b274-7df6-11e6-8915-6ff8215deb7d.png)
https://cloud.githubusercontent.com/assets/20930745/18619208/e5a5b274-7df6-11e6-8915-6ff8215deb7d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18619216/4d66f04e-7df7-11e6-9176-afce4bd2d892.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619310/758be73a-7df9-11e6-8326-e3b49b3b947b.png)
https://cloud.githubusercontent.com/assets/20930745/18619310/758be73a-7df9-11e6-8326-e3b49b3b947b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18619321/930d5352-7df9-11e6-9b9b-59b544fe3fc2.png

**Comment by Trubbel** [comment]
Or something like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18619395/44181faa-7dfb-11e6-85d0-3cbd4aff5100.png)
https://cloud.githubusercontent.com/assets/10730122/18619395/44181faa-7dfb-11e6-85d0-3cbd4aff5100.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18619394/44169f40-7dfb-11e6-8b24-3f893125e729.png

**Comment by 2Qt2beStr8** [comment]
perfect!

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60626791-3cd5d480-9dec-11e9-94b3-8e9e40c8977b.png)
https://user-images.githubusercontent.com/2068130/60626791-3cd5d480-9dec-11e9-94b3-8e9e40c8977b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60626812-4bbc8700-9dec-11e9-856e-06a140a690c9.png
