### ISSUE TITLE
FlightBoard – Live Flight Departure and Arrival Status

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8028]
**App Name:** FlightBoard – Live Flight Departure and Arrival Status
**Bundle ID:** com.mobiata.FlightBoard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390553006">390553006</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flightboard-live-flight-departure/id390553006?mt=8&uo=4">https://itunes.apple.com/us/app/flightboard-live-flight-departure/id390553006?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** Mobiata LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mobiata/id324473927?uo=4>© Mobiata</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/e2/dc/31/e2dc3129-44d0-3031-7a9a-f2ddff74bdc1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619060/29d8d8ee-7df3-11e6-85e1-ed5b2b8300d9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619060/29d8d8ee-7df3-11e6-85e1-ed5b2b8300d9.png)
https://cloud.githubusercontent.com/assets/20930745/18619060/29d8d8ee-7df3-11e6-85e1-ed5b2b8300d9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18619072/5f52766a-7df3-11e6-8b9a-b563543a95dc.png
