### ISSUE TITLE
PinPark App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8029]
**App Name:** PinPark App
**Bundle ID:** com.singularex.PinPark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=945859658">945859658</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pinpark-app/id945859658?mt=8&uo=4">https://itunes.apple.com/us/app/pinpark-app/id945859658?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Nikita Leonov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nikita-leonov/id945859657?uo=4>© Nikita Leonov</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/d5/69/0f/d5690f31-144c-7e17-3f5b-9ad8d68cba5f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619143/3c5928c8-7df5-11e6-95fa-cd29232c3a9c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619143/3c5928c8-7df5-11e6-95fa-cd29232c3a9c.png)
https://cloud.githubusercontent.com/assets/20930745/18619143/3c5928c8-7df5-11e6-95fa-cd29232c3a9c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18619149/539bd6e8-7df5-11e6-8acf-287e15bb1a65.png

**Comment by dreamnet** [comment]
Um... I think it would be better without the border.

**Comment by 2Qt2beStr8** [comment]
hmmm ... but i like the detail where the "P" touch the border :-)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18623866/5ad273c0-7e42-11e6-90a7-6913a6a022e6.png)
https://cloud.githubusercontent.com/assets/20930745/18623866/5ad273c0-7e42-11e6-90a7-6913a6a022e6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18623877/74fdfd46-7e42-11e6-9cd0-9200b8227a74.png

**Comment by dreamnet** [comment]
...on second thought... to go on with this, I take the first one.
