### ISSUE TITLE
BFMTV : l'info en continu

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#803]
**App Name:** BFMTV : l'info en continu
**Bundle ID:** com.nextradiotv.bfmtv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=325658560">325658560</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bfmtv-linfo-en-continu/id325658560?mt=8&uo=4">https://itunes.apple.com/us/app/bfmtv-linfo-en-continu/id325658560?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** NextradioTV
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nextradiotv/id325658563?uo=4>© NextRadioTV</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/c7/4e/f1/c74ef1cb-296e-2ead-c0da-5ccbb1d821a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408809/278f9e32-92c6-11e6-92e9-85e6a86c733b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408809/278f9e32-92c6-11e6-92e9-85e6a86c733b.png)
https://cloud.githubusercontent.com/assets/20930745/19408809/278f9e32-92c6-11e6-92e9-85e6a86c733b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19408813/37c39498-92c6-11e6-92f7-636a55aaaa3a.png
