### ISSUE TITLE
MobileData - Monitor your mobile data usage with Today Widget

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8030]
**App Name:** MobileData - Monitor your mobile data usage with Today Widget
**Bundle ID:** com.elaborateapps.MobileData
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944693166">944693166</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobiledata-monitor-your-mobile/id944693166?mt=8&uo=4">https://itunes.apple.com/us/app/mobiledata-monitor-your-mobile/id944693166?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Florian Walter
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/florian-walter/id617514867?uo=4>© Florian Walter</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/ec/23/0c/ec230c0e-5e13-928e-e5dd-d81d08eed09d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18622725/7c2235a6-7e33-11e6-8a00-3220bd89fd1e.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18618927/b007796e-7df0-11e6-83ca-d203c9d7e688.png)

https://cloud.githubusercontent.com/assets/16171251/18618927/b007796e-7df0-11e6-83ca-d203c9d7e688.png

Source: https://cloud.githubusercontent.com/assets/16171251/18618924/a01a0292-7df0-11e6-9da4-00e13f558f36.png

**Comment by dreamnet** [comment]
Centered like the original:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18622725/7c2235a6-7e33-11e6-8a00-3220bd89fd1e.png)
https://cloud.githubusercontent.com/assets/2068130/18622725/7c2235a6-7e33-11e6-8a00-3220bd89fd1e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18622728/8acf66c8-7e33-11e6-991c-de1ecf88d63d.png
