### ISSUE TITLE
Clip It! - Crop a portion of your favorite webpages and get live updates

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8031]
**App Name:** Clip It! - Crop a portion of your favorite webpages and get live updates
**Bundle ID:** com.rdamato.webclip
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1012562443">1012562443</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clip-it!-crop-portion-your/id1012562443?mt=8&uo=4">https://itunes.apple.com/us/app/clip-it!-crop-portion-your/id1012562443?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Raffaele D'Amato
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/raffaele-damato/id529947655?uo=4>© Raffaele D'Amato</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/e1/be/52/e1be5233-d98f-5672-1bc1-ba678534a197/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619434/7e9bc5f4-7dfc-11e6-8b92-2384c738fce6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619434/7e9bc5f4-7dfc-11e6-8b92-2384c738fce6.png)
https://cloud.githubusercontent.com/assets/20930745/18619434/7e9bc5f4-7dfc-11e6-8b92-2384c738fce6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18619439/9774e83a-7dfc-11e6-9375-c40f641c84a4.png
