### ISSUE TITLE
HP Smart

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8033]
**App Name:** HP Smart
**Bundle ID:** com.hp.printer.control
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469284907">469284907</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hp-smart/id469284907?uo=4">https://apps.apple.com/us/app/hp-smart/id469284907?uo=4</a>
**App Version:** 6.2.1
**Seller:** HP Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hp-inc/id299531650?uo=4">© HP Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/13/5b/a9/135ba991-23eb-dcbe-b4d8-dc332feee502/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60773248-09a08780-a103-11e9-8617-b779a19d1259.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18618982/a1454ed2-7df1-11e6-977b-d17b5929ea51.png)

https://cloud.githubusercontent.com/assets/16171251/18618982/a1454ed2-7df1-11e6-977b-d17b5929ea51.png

Source: https://cloud.githubusercontent.com/assets/16171251/18618975/8d3529f8-7df1-11e6-8e84-fd97951f8910.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60773248-09a08780-a103-11e9-8617-b779a19d1259.png)
https://user-images.githubusercontent.com/2068130/60773248-09a08780-a103-11e9-8617-b779a19d1259.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60773252-18873a00-a103-11e9-89bf-ee3505bc7a92.png
