### ISSUE TITLE
Omnistat - System Status & Activity Monitor

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8034]
**App Name:** Omnistat - System Status & Activity Monitor
**Bundle ID:** com.mathieubolard.omnistat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=898245825">898245825</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/omnistat-system-status-activity/id898245825?mt=8&uo=4">https://itunes.apple.com/us/app/omnistat-system-status-activity/id898245825?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Mathieu Bolard
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mathieu-bolard/id355839736?uo=4>© Mathieu Bolard</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/28/aa/af/28aaafac-5bd8-eb3d-72fd-67fd125a92ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18622876/fec70642-7e35-11e6-89a0-279a7d8b01bc.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18618997/06b9ef98-7df2-11e6-8a9e-e54c86798c61.png)

https://cloud.githubusercontent.com/assets/16171251/18618997/06b9ef98-7df2-11e6-8a9e-e54c86798c61.png

Source: https://cloud.githubusercontent.com/assets/16171251/18619001/136f8d38-7df2-11e6-9782-f87ba70840ed.png

**Comment by dreamnet** [comment]
Just pushing it to the bottom:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18622876/fec70642-7e35-11e6-89a0-279a7d8b01bc.png)
https://cloud.githubusercontent.com/assets/2068130/18622876/fec70642-7e35-11e6-89a0-279a7d8b01bc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18622879/0d635854-7e36-11e6-91dd-d429735c3662.png
