### ISSUE TITLE
Busradar - Intercity Bus App

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8038]
**App Name:** Busradar - Intercity Bus App
**Bundle ID:** de.busliniensuche.busliniensuche
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=805591188">805591188</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/busradar-intercity-bus-app/id805591188?uo=4">https://apps.apple.com/us/app/busradar-intercity-bus-app/id805591188?uo=4</a>
**App Version:** 3.3
**Seller:** Green Parrot GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/green-parrot-gmbh/id799455300?uo=4">© Green Parrot GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/ff/b6/7a/ffb67ad9-a849-c44f-2988-3ff843b34d75/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981409-2c12ab00-9603-11e9-93f0-578e229d9155.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18619160/b9218a62-7df5-11e6-8d65-b193368b399e.png)

https://cloud.githubusercontent.com/assets/16171251/18619160/b9218a62-7df5-11e6-8d65-b193368b399e.png

Source: https://cloud.githubusercontent.com/assets/16171251/18619167/cd984f76-7df5-11e6-8952-01294e94982c.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59981409-2c12ab00-9603-11e9-93f0-578e229d9155.png)
https://user-images.githubusercontent.com/2068130/59981409-2c12ab00-9603-11e9-93f0-578e229d9155.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59981413-3a60c700-9603-11e9-81d1-ae0ab5083abb.png
