### ISSUE TITLE
Canvas by Instructure

### ISSUE THREAD

**Issue by GMVargas** [glasklart/hd#8039]
**App Name:** Canvas by Instructure
**Bundle ID:** com.instructure.icanvas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=480883488">480883488</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/canvas-by-instructure/id480883488?mt=8&uo=4">https://itunes.apple.com/us/app/canvas-by-instructure/id480883488?mt=8&uo=4</a>
**App Version:** 3.14.2
**Seller:** Instructure, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/instructure-inc./id418441198?uo=4>© Instructure Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple19/v4/86/00/50/86005073-247a-fb81-427d-1e36b337d4eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619336/2e5f5a94-7dfa-11e6-94df-fc42243a6814.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18619336/2e5f5a94-7dfa-11e6-94df-fc42243a6814.png)
https://cloud.githubusercontent.com/assets/20930745/18619336/2e5f5a94-7dfa-11e6-94df-fc42243a6814.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18619341/43dd0038-7dfa-11e6-88cc-d1c3f16da609.png
