### ISSUE TITLE
Simple - Better Banking

### ISSUE THREAD

**Issue by lxsdr** [glasklart/hd#804]
**App Name:** Simple - Better Banking
**Bundle ID:** com.simple.Simple
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479317486">479317486</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/simple-better-banking/id479317486?mt=8&uo=4">https://itunes.apple.com/us/app/simple-better-banking/id479317486?mt=8&uo=4</a>
**App Version:** 2.9.0
**Seller:** Simple Finance Technology Corp.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/simple-finance/id479317769?uo=4>© Simple Finance</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/c9/b5/54/c9b55420-688a-980e-ac9f-15a633f3e96c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408881/c5968554-92c7-11e6-8fdd-fc0bb33b859b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408881/c5968554-92c7-11e6-8fdd-fc0bb33b859b.png)
https://cloud.githubusercontent.com/assets/20930745/19408881/c5968554-92c7-11e6-8fdd-fc0bb33b859b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19408882/d279f7b0-92c7-11e6-9310-6c5b3ca7fb1b.png
