### ISSUE TITLE
Movies by Flixster, with Rotten Tomatoes

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8042]
**App Name:** Movies by Flixster, with Rotten Tomatoes
**Bundle ID:** com.jeffreygrossman.moviesapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=284235722">284235722</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/movies-by-flixster-rotten/id284235722?mt=8&uo=4">https://itunes.apple.com/us/app/movies-by-flixster-rotten/id284235722?mt=8&uo=4</a>
**App Version:** 7.13.1
**Seller:** Flixster, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/flixster-inc./id672117627?uo=4>© Flixster, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple41/v4/16/ff/9d/16ff9d33-101f-2559-a7ee-e7e11276d70f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18647616/1246a43a-7eb7-11e6-9356-c975d3c70cd3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18647616/1246a43a-7eb7-11e6-9356-c975d3c70cd3.png)
https://cloud.githubusercontent.com/assets/2068130/18647616/1246a43a-7eb7-11e6-9356-c975d3c70cd3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18647628/21c833ec-7eb7-11e6-88a8-2aebe44c7260.png
