### ISSUE TITLE
Weather °F

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8043]
**App Name:** Weather °F
**Bundle ID:** com.itwcalculator.fahrenheit2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426939660">426939660</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-f/id426939660?mt=8&uo=4">https://itunes.apple.com/us/app/weather-f/id426939660?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** Impala Studios B.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/impala-studios/id1063279743?uo=4">© Impala Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple19/v4/9a/ae/d6/9aaed673-9cc2-b3c3-bf92-53cd5100cab4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21015666/2b50472a-bd63-11e6-9313-aa25600bf891.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18658997/0b6cff8c-7f08-11e6-9a47-fabf8e7e3f69.png)
https://cloud.githubusercontent.com/assets/20930745/18658997/0b6cff8c-7f08-11e6-9a47-fabf8e7e3f69.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18659015/2441fe68-7f08-11e6-91a8-21637f361a44.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18663719/f1497bc2-7f1f-11e6-9507-992e1dc22a62.png)
https://cloud.githubusercontent.com/assets/20930745/18663719/f1497bc2-7f1f-11e6-9507-992e1dc22a62.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18663736/0630dc42-7f20-11e6-85ec-41a9fe733c40.png

**Comment by l8er4now** [comment]
I don't think you include the badge and center the now.

**Comment by 2Qt2beStr8** [comment]
which icon you mean? first or second?

**Comment by l8er4now** [comment]
The first, the fill on the second is just too much.

**Comment by 2Qt2beStr8** [comment]
... you mean like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18670358/cf09fe2c-7f3f-11e6-93ae-5350d3fa0b79.png)
https://cloud.githubusercontent.com/assets/20930745/18670358/cf09fe2c-7f3f-11e6-93ae-5350d3fa0b79.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18670370/debcccfa-7f3f-11e6-9ee5-e0112f6c3c2c.png

**Comment by l8er4now** [comment]
Yeah that's better, not sure if you can make it a bit bolder?

**Comment by l8er4now** [comment]
I guess the Celsius version of this app doesn't have the now centered, probably should follow suite with it.

For reference
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18674124/20f634d6-7f1c-11e6-9a2f-41125ca916ce.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18682410/66b342e8-7f6c-11e6-87e3-e30c3747f8a1.png)
https://cloud.githubusercontent.com/assets/20930745/18682410/66b342e8-7f6c-11e6-87e3-e30c3747f8a1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18682431/771380a8-7f6c-11e6-8ce0-5dbd01fc0135.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Weather °F
**Bundle ID:** com.itwcalculator.fahrenheit2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=426939660">426939660</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-f/id426939660?mt=8&uo=4">https://itunes.apple.com/us/app/weather-f/id426939660?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** Impala Studios B.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/impala-studios/id1063279743?uo=4">© Impala Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple19/v4/9a/ae/d6/9aaed673-9cc2-b3c3-bf92-53cd5100cab4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21015666/2b50472a-bd63-11e6-9313-aa25600bf891.png)
https://cloud.githubusercontent.com/assets/20930745/21015666/2b50472a-bd63-11e6-9313-aa25600bf891.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21015705/5149c67c-bd63-11e6-915a-747236320f7b.png
