### ISSUE TITLE
Solar Lunar Widget

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8045]
**App Name:** Solar Lunar Widget
**Bundle ID:** appBakery.Sunrise-Sunset-Widget
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955327657">955327657</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/solar-lunar-widget/id955327657?mt=8&uo=4">https://itunes.apple.com/us/app/solar-lunar-widget/id955327657?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** Bjorn Jenssen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bjorn-jenssen/id590354152?uo=4>© Bjorn Jenssen</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/2d/54/aa/2d54aa83-ab12-ea22-ba76-d8afc4d797ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18658855/a7f13cb2-7f06-11e6-9053-c965782a3f35.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18658855/a7f13cb2-7f06-11e6-9053-c965782a3f35.png)
https://cloud.githubusercontent.com/assets/20930745/18658855/a7f13cb2-7f06-11e6-9053-c965782a3f35.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18658872/c9db6e56-7f06-11e6-9985-59465d6e9af6.png
