### ISSUE TITLE
My Hurricane Tracker - Tornados & Tropical Storms!

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8047]
**App Name:** My Hurricane Tracker - Tornados & Tropical Storms!
**Bundle ID:** com.jrustonapps.My-Hurricane-Tracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1020486515">1020486515</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-hurricane-tracker-tornados/id1020486515?mt=8&uo=4">https://itunes.apple.com/us/app/my-hurricane-tracker-tornados/id1020486515?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** Jake Ruston
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jruston-apps/id549019599?uo=4>© jRuston Apps</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple19/v4/ff/08/89/ff0889d4-1701-60e2-2978-26e5e01ae118/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18649331/4a404d5c-7ebf-11e6-92ed-7982b7156e2f.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18649186/1e2a2a04-7e8c-11e6-89b2-2ba15fdcaf8c.png)

https://cloud.githubusercontent.com/assets/3704186/18649186/1e2a2a04-7e8c-11e6-89b2-2ba15fdcaf8c.png

https://cloud.githubusercontent.com/assets/3704186/18649193/29282a46-7e8c-11e6-97d7-02e51c59295a.png

**Comment by dreamnet** [comment]
@l8er4now Too big...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18649331/4a404d5c-7ebf-11e6-92ed-7982b7156e2f.png)
https://cloud.githubusercontent.com/assets/2068130/18649331/4a404d5c-7ebf-11e6-92ed-7982b7156e2f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18649344/5959fce8-7ebf-11e6-83b1-afc02eab3c38.png

**Comment by l8er4now** [comment]
Sorry about that, thanks for correcting!
