### ISSUE TITLE
TVShows - Free TV Series Calendar Watch Tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8049]
**App Name:** TVShows - Free TV Series Calendar Watch Tracker
**Bundle ID:** ru.persapps.TVSeries
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1046485800">1046485800</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tvshows-free-tv-series-calendar/id1046485800?mt=8&uo=4">https://itunes.apple.com/us/app/tvshows-free-tv-series-calendar/id1046485800?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Sergey Astakhov
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sergey-astakhov/id350555478?uo=4>© Sergey Astakhov</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/c1/71/5f/c1715f4b-92be-76a9-03aa-a96c9b19ef05/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18649527/3e3ea8fe-7ec0-11e6-8665-283d2e1a31ca.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18649527/3e3ea8fe-7ec0-11e6-8665-283d2e1a31ca.png)
https://cloud.githubusercontent.com/assets/2068130/18649527/3e3ea8fe-7ec0-11e6-8665-283d2e1a31ca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18649536/4cefae02-7ec0-11e6-879e-ff2d0199a0e4.png
