### ISSUE TITLE
Liberation

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#805]
**App Name:** Liberation
**Bundle ID:** fr.liberation.liberationapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336173383">336173383</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/liberation/id336173383?mt=8&uo=4">https://itunes.apple.com/us/app/liberation/id336173383?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** LIBERATION sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/liberation/id333549393?uo=4>© Liberation</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple42/v4/22/95/61/2295612b-b8ac-8d51-9bcc-5ee8fcfa22e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408981/2ce75ec0-92ca-11e6-9678-602ad68db75e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19408981/2ce75ec0-92ca-11e6-9678-602ad68db75e.png)
https://cloud.githubusercontent.com/assets/20930745/19408981/2ce75ec0-92ca-11e6-9678-602ad68db75e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19408986/3c6010b8-92ca-11e6-8a30-31754d33eb83.png
