### ISSUE TITLE
Thuuz Sports

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8050]
**App Name:** Thuuz Sports
**Bundle ID:** com.thuuz.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=459465949">459465949</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/thuuz-sports/id459465949?mt=8&uo=4">https://itunes.apple.com/us/app/thuuz-sports/id459465949?mt=8&uo=4</a>
**App Version:** 6.5.7
**Seller:** Thuuz Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/thuuz-inc./id459465952?uo=4>© Thuuz Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/5a/4a/2a/5a4a2a2c-d274-510f-4aae-ac0152b7c665/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18657870/88e0f978-7efe-11e6-9196-8efc4d9c0f0e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18657870/88e0f978-7efe-11e6-9196-8efc4d9c0f0e.png)
https://cloud.githubusercontent.com/assets/2068130/18657870/88e0f978-7efe-11e6-9196-8efc4d9c0f0e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18657879/9c05bc82-7efe-11e6-9342-2aed1133ddd1.png
