### ISSUE TITLE
Yahoo Search

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8051]
**App Name:** Yahoo Search
**Bundle ID:** com.yahoo.search2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=361071600">361071600</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/yahoo-search/id361071600?uo=4">https://apps.apple.com/us/app/yahoo-search/id361071600?uo=4</a>
**App Version:** 7.9.0
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yahoo/id281970157?uo=4">© Yahoo</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/65/18/2d/65182d03-8903-0913-da17-1147f5e4cc42/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67358251-22249880-f560-11e9-9dc5-0f760855e9c8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18657974/56280642-7eff-11e6-8244-fac6e45b4743.png)
https://cloud.githubusercontent.com/assets/2068130/18657974/56280642-7eff-11e6-8244-fac6e45b4743.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18657986/6d6ed84e-7eff-11e6-85d6-d2627aafb2b9.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Yahoo Search
**Bundle ID:** com.yahoo.search2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=361071600">361071600</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/yahoo-search/id361071600?uo=4">https://apps.apple.com/us/app/yahoo-search/id361071600?uo=4</a>
**App Version:** 7.9.0
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/yahoo/id281970157?uo=4">© Yahoo</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/65/18/2d/65182d03-8903-0913-da17-1147f5e4cc42/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67358251-22249880-f560-11e9-9dc5-0f760855e9c8.png)
https://user-images.githubusercontent.com/2068130/67358251-22249880-f560-11e9-9dc5-0f760855e9c8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/67358273-323c7800-f560-11e9-8685-15d20d14e7cb.png
