### ISSUE TITLE
Bloomberg

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8052]
**App Name:** Bloomberg
**Bundle ID:** com.bloomberg.Bloomberg
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=281941097">281941097</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bloomberg/id281941097?mt=8&uo=4">https://itunes.apple.com/us/app/bloomberg/id281941097?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** Bloomberg Finance LP
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bloomberg-finance-lp/id281941100?uo=4">© Bloomberg Finance LP</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/55/76/6a/55766a5b-280c-7871-7883-0ab024ba7eef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21485045/ed639c58-cb9c-11e6-9d41-fdd03121fbc0.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18672825/9d17f2a2-7f17-11e6-83b0-71cdd7d77aa7.png)

https://cloud.githubusercontent.com/assets/3704186/18672825/9d17f2a2-7f17-11e6-83b0-71cdd7d77aa7.png

https://cloud.githubusercontent.com/assets/3704186/18672830/a34ac7e4-7f17-11e6-9f4b-72a3ba63cf28.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Bloomberg
**Bundle ID:** com.bloomberg.Bloomberg
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=281941097">281941097</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bloomberg/id281941097?mt=8&uo=4">https://itunes.apple.com/us/app/bloomberg/id281941097?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** Bloomberg Finance LP
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bloomberg-finance-lp/id281941100?uo=4">© Bloomberg Finance LP</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/55/76/6a/55766a5b-280c-7871-7883-0ab024ba7eef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21485045/ed639c58-cb9c-11e6-9d41-fdd03121fbc0.png)
https://cloud.githubusercontent.com/assets/20930745/21485045/ed639c58-cb9c-11e6-9d41-fdd03121fbc0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21485051/fdac166c-cb9c-11e6-85c1-00a5f5183f06.png
