### ISSUE TITLE
Branches – for GitHub, GitLab and Bitbucket

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8053]
**App Name:** Branches – for GitHub, GitLab and Bitbucket
**Bundle ID:** org.kalliope.Branches
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979057459">979057459</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/branches-for-github-gitlab/id979057459?mt=8&uo=4">https://itunes.apple.com/us/app/branches-for-github-gitlab/id979057459?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Jesper Christensen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jesper-christensen/id871144428?uo=4>© Jesper Christensen</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/c6/73/a3/c673a387-4a30-a552-9431-0486a85802eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18681872/30f5cd80-7f6a-11e6-95b8-752fd2a79d13.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18681872/30f5cd80-7f6a-11e6-95b8-752fd2a79d13.png)
https://cloud.githubusercontent.com/assets/20930745/18681872/30f5cd80-7f6a-11e6-95b8-752fd2a79d13.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18681889/409f0bd4-7f6a-11e6-98fc-9f82bb61ea16.png
