### ISSUE TITLE
MagicPlan CSI

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8054]
**App Name:** MagicPlan CSI
**Bundle ID:** com.sensopia.magicplan.csi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=480247904">480247904</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/magicplan-csi/id480247904?mt=8&uo=4">https://itunes.apple.com/us/app/magicplan-csi/id480247904?mt=8&uo=4</a>
**App Version:** 5.7
**Seller:** Sensopia Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sensopia/id402516206?uo=4>© Sensopia</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/39/cc/c9/39ccc9ed-0b8b-9416-e05a-8e184941a349/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18687236/6eb2e198-7f7f-11e6-883f-e8e7741138e2.png)

**Comment by ivanov007** [comment]
#2731

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18687236/6eb2e198-7f7f-11e6-883f-e8e7741138e2.png)
https://cloud.githubusercontent.com/assets/20930745/18687236/6eb2e198-7f7f-11e6-883f-e8e7741138e2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18687265/8da4aafa-7f7f-11e6-8e86-7c7d6cefde95.png
