### ISSUE TITLE
Comic Zeal Comic Book Reader

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8055]
**App Name:** Comic Zeal Comic Book Reader
**Bundle ID:** Ff2lqVpcZ2.ComicZeal4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=363990983">363990983</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/comic-zeal-comic-book-reader/id363990983?mt=8&uo=4">https://itunes.apple.com/us/app/comic-zeal-comic-book-reader/id363990983?mt=8&uo=4</a>
**App Version:** 9.1.3
**Seller:** Bitolithic Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bitolithic-pty-ltd/id288016884?uo=4>© Bitolithic Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/cf/cf/b1/cfcfb129-9a25-1695-fb1e-0ea0778823f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18691026/a7b6f95e-7f91-11e6-902d-8233232515ed.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18691026/a7b6f95e-7f91-11e6-902d-8233232515ed.png)
https://cloud.githubusercontent.com/assets/20930745/18691026/a7b6f95e-7f91-11e6-902d-8233232515ed.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18691043/b762fc5e-7f91-11e6-87c0-2136baca2efb.png
