### ISSUE TITLE
MeteoEarth

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8056]
**App Name:** MeteoEarth
**Bundle ID:** de.meteogroup.meteoearthsd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=619814752">619814752</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/meteoearth/id619814752?mt=8&uo=4">https://itunes.apple.com/us/app/meteoearth/id619814752?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** MeteoGroup Deutschland GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/meteogroup-deutschland-gmbh/id294631162?uo=4>© MeteoGroup Deutschland GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/06/13/6f/06136f39-8e03-8c02-f760-76494187cb6c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19022103/50fae1f0-88d0-11e6-8bc0-0b78ddb477e5.png)

**Comment by 2Qt2beStr8** [comment]
1. attempt ... only lettering

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19020622/85e9851e-88ae-11e6-8399-2c70ecf8bf31.png)
https://cloud.githubusercontent.com/assets/20930745/19020622/85e9851e-88ae-11e6-8399-2c70ecf8bf31.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19020627/afeae45c-88ae-11e6-8033-9bbaa23d4ac7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19020816/3d1d6b2a-88b3-11e6-8ef3-98f5824fedd6.png)
https://cloud.githubusercontent.com/assets/20930745/19020816/3d1d6b2a-88b3-11e6-8ef3-98f5824fedd6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19020823/5bc1afb4-88b3-11e6-9f0e-d18624216bfc.png

**Comment by dreamnet** [comment]
Just a small addition:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19022103/50fae1f0-88d0-11e6-8bc0-0b78ddb477e5.png)
https://cloud.githubusercontent.com/assets/2068130/19022103/50fae1f0-88d0-11e6-8bc0-0b78ddb477e5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19022105/5f316370-88d0-11e6-96c1-9a4711d7d9d7.png

**Comment by 2Qt2beStr8** [comment]
.. oh yes ... i forgot the star :-(
