### ISSUE TITLE
NOAA Radar Pro – Weather Alerts & Forecast

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8057]
**App Name:** NOAA Radar Pro – Weather Alerts & Forecast
**Bundle ID:** com.apalonapps.radar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=749133301">749133301</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/noaa-radar-pro-weather-alerts/id749133301?mt=8&uo=4">https://itunes.apple.com/us/app/noaa-radar-pro-weather-alerts/id749133301?mt=8&uo=4</a>
**App Version:** 3.15
**Seller:** IAC Search & Media Europe Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/apalon-apps/id749046894?uo=4>© Apalon Apps</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/db/a0/b7/dba0b75b-49df-dbf3-4d60-ebc7056a4cc0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18742105/d120b100-80b2-11e6-9cee-bbde88d8b17a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18741805/5eb1b5ac-80b1-11e6-86cb-93b5a8489db7.png)
https://cloud.githubusercontent.com/assets/20930745/18741805/5eb1b5ac-80b1-11e6-86cb-93b5a8489db7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18741824/7099d5f6-80b1-11e6-8365-159dd79e50ad.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18742105/d120b100-80b2-11e6-9cee-bbde88d8b17a.png)
https://cloud.githubusercontent.com/assets/20930745/18742105/d120b100-80b2-11e6-9cee-bbde88d8b17a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18742124/e3994fb8-80b2-11e6-8fba-f2d10ee0dadb.png
