### ISSUE TITLE
Radar Cast Elite - NOAA Hi-Def FutureCast, Push Notifications, Driving Directions, Lightning Strikes & Weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8058]
**App Name:** Radar Cast Elite - NOAA Hi-Def FutureCast, Push Notifications, Driving Directions, Lightning Strikes & Weather
**Bundle ID:** com.geoterrestrial.radarcast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=601606659">601606659</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radar-cast-elite-noaa-hi-def/id601606659?mt=8&uo=4">https://itunes.apple.com/us/app/radar-cast-elite-noaa-hi-def/id601606659?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** WeatherSphere
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/weathersphere/id379847497?uo=4>© WeatherSphere</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/d4/04/8d/d4048df4-884e-fe36-5149-e4334c72fff5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18741587/47ce2a9c-80b0-11e6-975f-bdc35b6df00d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18741587/47ce2a9c-80b0-11e6-975f-bdc35b6df00d.png)
https://cloud.githubusercontent.com/assets/20930745/18741587/47ce2a9c-80b0-11e6-975f-bdc35b6df00d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18741602/588345f2-80b0-11e6-981b-a198c0a4b3e9.png
