### ISSUE TITLE
NPR News

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8059]
**App Name:** NPR News
**Bundle ID:** org.npr.nprnews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324906251">324906251</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/npr-news/id324906251?mt=8&uo=4">https://itunes.apple.com/us/app/npr-news/id324906251?mt=8&uo=4</a>
**App Version:** 3.9.10
**Seller:** NPR
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/npr/id324906254?mt=8&uo=4>© NPR</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple18/v4/bd/50/dc/bd50dcb3-7705-0a01-f1c6-e4039ad817fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18716678/ef770edc-801d-11e6-80ed-6557b747eaa4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18716678/ef770edc-801d-11e6-80ed-6557b747eaa4.png)
https://cloud.githubusercontent.com/assets/20930745/18716678/ef770edc-801d-11e6-80ed-6557b747eaa4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18716697/02734208-801e-11e6-97b1-72765ede3e27.png
