### ISSUE TITLE
SoundCloud - Music & Audio

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#806]
**App Name:** SoundCloud - Music & Audio
**Bundle ID:** com.soundcloud.TouchApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336353151">336353151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/soundcloud-music-audio/id336353151?mt=8&uo=4">https://itunes.apple.com/us/app/soundcloud-music-audio/id336353151?mt=8&uo=4</a>
**App Version:** 3.13.0
**Seller:** SoundCloud Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/soundcloud-ltd./id336353154?uo=4>© SoundCloud Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/31/79/b5/3179b59e-900e-0371-1e56-008b2682336b/mzl.nyeqprdh.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10386148/655489e6-6e53-11e5-8628-8299be1d6f56.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/10386148/655489e6-6e53-11e5-8628-8299be1d6f56.png)
https://cloud.githubusercontent.com/assets/10730122/10386148/655489e6-6e53-11e5-8628-8299be1d6f56.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10386147/6185be98-6e53-11e5-9428-b0d53154585e.png
