### ISSUE TITLE
checkTrakt

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8060]
**App Name:** checkTrakt
**Bundle ID:** com.tobiasarends.checktrakt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=590227780">590227780</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/checktrakt/id590227780?mt=8&uo=4">https://itunes.apple.com/us/app/checktrakt/id590227780?mt=8&uo=4</a>
**App Version:** 3.7.3
**Seller:** Tobias Arends
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tobias-arends/id590227783?uo=4>© Tobias Arends</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/f8/3e/b2/f83eb27b-8218-2fc1-af61-35e0a67847e3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18716942/d63778a2-801e-11e6-9cc5-5db54ca66634.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18716942/d63778a2-801e-11e6-9cc5-5db54ca66634.png)
https://cloud.githubusercontent.com/assets/20930745/18716942/d63778a2-801e-11e6-9cc5-5db54ca66634.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18716961/e6a3adfa-801e-11e6-9a00-62fc5a8c2d70.png
