### ISSUE TITLE
Lara Croft GO

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8061]
**App Name:** Lara Croft GO
**Bundle ID:** com.squareenixmontreal.lcgo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=971304016">971304016</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lara-croft-go/id971304016?mt=8&uo=4">https://itunes.apple.com/us/app/lara-croft-go/id971304016?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** SQUARE ENIX Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/square-enix-inc/id300186801?mt=8&uo=4>© SQUARE ENIX INC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/90/38/a8/9038a8a6-15ac-5cd2-2ea1-77bf6904e8b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18811609/17e18074-82b6-11e6-828d-b3809804b217.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18811609/17e18074-82b6-11e6-828d-b3809804b217.png)
https://cloud.githubusercontent.com/assets/2068130/18811609/17e18074-82b6-11e6-828d-b3809804b217.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18811610/271b3260-82b6-11e6-9329-d0db297c9b8e.png
