### ISSUE TITLE
FlightAware Flight Tracker

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8062]
**App Name:** FlightAware Flight Tracker
**Bundle ID:** com.flightaware.iphone.live-flight-tracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=316793974">316793974</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flightaware-flight-tracker/id316793974?mt=8&uo=4">https://itunes.apple.com/us/app/flightaware-flight-tracker/id316793974?mt=8&uo=4</a>
**App Version:** 5.2.1
**Seller:** FlightAware
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/flightaware/id316793977?uo=4>© FlightAware</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/fb/58/dc/fb58dc69-4c38-999d-35ac-bc2a329ca1fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18723143/c4241d3c-8037-11e6-8416-bd7d1c6a482c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18723143/c4241d3c-8037-11e6-8416-bd7d1c6a482c.png)
https://cloud.githubusercontent.com/assets/20930745/18723143/c4241d3c-8037-11e6-8416-bd7d1c6a482c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18723170/d422d2f0-8037-11e6-9986-911d72df74d7.png
