### ISSUE TITLE
myAT&T

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8063]
**App Name:** myAT&T
**Bundle ID:** com.att.osd.myWireless
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=309172177">309172177</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myat-t/id309172177?mt=8&uo=4">https://itunes.apple.com/us/app/myat-t/id309172177?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** AT&T Services, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/at-t-services-inc./id290854684?uo=4>© AT&T Services, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/af/4d/78/af4d78d9-870a-b9b3-3ec2-19ae423c5d65/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18723302/442305e8-8038-11e6-996b-812988d98047.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18723302/442305e8-8038-11e6-996b-812988d98047.png)
https://cloud.githubusercontent.com/assets/20930745/18723302/442305e8-8038-11e6-996b-812988d98047.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18723319/54ce6590-8038-11e6-9051-94651969bcf7.png
