### ISSUE TITLE
The Calculator Free

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8064]
**App Name:** The Calculator Free
**Bundle ID:** com.itwcalculator.calculatorforipadfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398129933">398129933</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-calculator-free/id398129933?mt=8&uo=4">https://itunes.apple.com/us/app/the-calculator-free/id398129933?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** International Travel Weather Calculator
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/international-travel-weather/id396082456?uo=4>© International Travel Weather Calculator</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/15/b5/91/15b59141-af05-216f-8406-255e52c0c431/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18727132/9d0830d4-8047-11e6-8e9d-4db69e5439a9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18727132/9d0830d4-8047-11e6-8e9d-4db69e5439a9.png)
![sourcecalculatorfree](https://cloud.githubusercontent.com/assets/20930745/18727181/d1c543ca-8047-11e6-86d8-d6876a2b992e.png)

Source:
https://cloud.githubusercontent.com/assets/20930745/18727132/9d0830d4-8047-11e6-8e9d-4db69e5439a9.png
