### ISSUE TITLE
DataFlow - Track network data usage

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8065]
**App Name:** DataFlow - Track network data usage
**Bundle ID:** co.crazycode.DataFlow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955447159">955447159</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dataflow-track-network-data/id955447159?mt=8&uo=4">https://itunes.apple.com/us/app/dataflow-track-network-data/id955447159?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** Feng Mi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/feng-mi/id829410500?uo=4>© Feng Mi</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/d6/02/c5/d602c535-08a4-d67e-49e6-647d16d73e1b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18809716/ea8eccc6-8283-11e6-9d0e-965b0896dd9e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18723569/62649b1a-8039-11e6-9d96-b8a5d35d8e1e.png)
https://cloud.githubusercontent.com/assets/20930745/18723569/62649b1a-8039-11e6-9d96-b8a5d35d8e1e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18723588/7ad90bea-8039-11e6-8e5d-28479156b516.png

**Comment by Anuskuss** [comment]
@2Qt2beStr8 Too big

**Comment by 2Qt2beStr8** [comment]
@Anuskuss  .. thank you ..

**Comment by Checkit23** [comment]
What about adding the circles to the icon as well, maybe seperated by thin lines?!

**Comment by 2Qt2beStr8** [comment]
... like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18727892/29313116-804b-11e6-896c-09bbdf9e6dac.png)
https://cloud.githubusercontent.com/assets/20930745/18727892/29313116-804b-11e6-896c-09bbdf9e6dac.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18727907/3883c32c-804b-11e6-925b-36d962fc0e85.png

**Comment by Anuskuss** [comment]
@Checkit23 I'd say smaller size without circles

**Comment by 2Qt2beStr8** [comment]
i have changed already the size from the first icon

**Comment by Checkit23** [comment]
I was thinking about something like this, which resembles the circles in the background (quick and dirty sketch).

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18731594/226f9c3e-805d-11e6-8af3-c8c2ea21112e.png)

**Comment by dreamnet** [comment]
I decide... 😱 
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18809716/ea8eccc6-8283-11e6-9d0e-965b0896dd9e.png)
https://cloud.githubusercontent.com/assets/2068130/18809716/ea8eccc6-8283-11e6-9d0e-965b0896dd9e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18809723/fb59abe8-8283-11e6-9675-64725485fc39.png
