### ISSUE TITLE
Ringtone Maker - Make free ringtones from your music!

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8066]
**App Name:** Ringtone Maker - Make free ringtones from your music!
**Bundle ID:** com.zentertain.ringmakerfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390929278">390929278</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ringtone-maker-make-free-ringtones/id390929278?mt=8&uo=4">https://itunes.apple.com/us/app/ringtone-maker-make-free-ringtones/id390929278?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Zentertain Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zentertain-ltd./id371114041?uo=4>© Zentertain Ltd.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/43/0b/fc/430bfc79-60e2-1eca-afe3-494f6e02f309/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18724868/44f543d6-803e-11e6-9d64-c7caf8cbf7a3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18724868/44f543d6-803e-11e6-9d64-c7caf8cbf7a3.png)
https://cloud.githubusercontent.com/assets/20930745/18724868/44f543d6-803e-11e6-9d64-c7caf8cbf7a3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18724891/5a36eaba-803e-11e6-9380-e852e559204c.png
