### ISSUE TITLE
Ringtone Maker Free – create ringtones with your music

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8067]
**App Name:** Ringtone Maker Free – create ringtones with your music
**Bundle ID:** gogoapps.ringtone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1078875275">1078875275</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ringtone-maker-free-create/id1078875275?mt=8&uo=4">https://itunes.apple.com/us/app/ringtone-maker-free-create/id1078875275?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** JINMIN ZHOU
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jinmin-zhou/id1018840273?uo=4>© JINMIN ZHOU</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/02/5a/c3/025ac321-102f-0cce-05c8-34e369c9682e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18724664/8d037cde-803d-11e6-90f9-e5ef04feb563.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18724664/8d037cde-803d-11e6-90f9-e5ef04feb563.png)
https://cloud.githubusercontent.com/assets/20930745/18724664/8d037cde-803d-11e6-90f9-e5ef04feb563.png)

Source:
https://cloud.githubusercontent.com/assets/20930745/18724701/a00c0288-803d-11e6-9335-cdb5a35b1b62.png
