### ISSUE TITLE
If Found Lock Screen 2

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8068]
**App Name:** If Found Lock Screen 2
**Bundle ID:** com.iosproapps.If-Found-Lock-Screen-02
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1141408678">1141408678</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/if-found-lock-screen-2/id1141408678?mt=8&uo=4">https://itunes.apple.com/us/app/if-found-lock-screen-2/id1141408678?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Out of Web Site! LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/out-of-web-site!/id398340791?uo=4>© Out of Web Site!</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple22/v4/b3/86/f7/b386f77c-9545-94f9-e1e1-3a8a3b8b13fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18726646/b77e9d9c-8045-11e6-9466-8f081199dca2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18726646/b77e9d9c-8045-11e6-9466-8f081199dca2.png)
https://cloud.githubusercontent.com/assets/20930745/18726646/b77e9d9c-8045-11e6-9466-8f081199dca2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18726660/c61f0972-8045-11e6-9afe-4e6669169aaf.png
