### ISSUE TITLE
Orbitz Flights, Hotels, Cars & Activities

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8069]
**App Name:** Orbitz Flights, Hotels, Cars & Activities
**Bundle ID:** com.orbitz.iphoneprod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=403546234">403546234</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/orbitz-flights-hotels-cars/id403546234?mt=8&uo=4">https://itunes.apple.com/us/app/orbitz-flights-hotels-cars/id403546234?mt=8&uo=4</a>
**App Version:** 7.4
**Seller:** Orbitz Worldwide, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/orbitz/id400774818?uo=4>© Orbitz</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/87/4f/b8/874fb8d7-2c25-6f12-dca5-b96a87ce56f1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18724426/a9fd1846-803c-11e6-979f-d8ace597cbe8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18724426/a9fd1846-803c-11e6-979f-d8ace597cbe8.png)
https://cloud.githubusercontent.com/assets/20930745/18724426/a9fd1846-803c-11e6-979f-d8ace597cbe8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18724446/be10c120-803c-11e6-88f3-590e5fd94e00.png
