### ISSUE TITLE
Roku

### ISSUE THREAD

**Issue by rowdielou** [glasklart/hd#807]
**App Name:** Roku
**Bundle ID:** com.roku.ios.roku
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=482066631">482066631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/roku/id482066631?mt=8&uo=4">https://itunes.apple.com/us/app/roku/id482066631?mt=8&uo=4</a>
**App Version:** 3.5.6
**Seller:** ROKU INC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/roku-inc/id482066634?uo=4>© ROKU INC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/b7/1c/df/b71cdfad-d460-d04b-c07d-e602944106aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18970715/a9d434ec-8692-11e6-85a3-3e011719ba02.png)

**Comment by illinikev** [comment]
Update needed.

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18970715/a9d434ec-8692-11e6-85a3-3e011719ba02.png)
https://cloud.githubusercontent.com/assets/22012363/18970715/a9d434ec-8692-11e6-85a3-3e011719ba02.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18970714/a9cc99a8-8692-11e6-8150-886d63ffc244.png
