### ISSUE TITLE
 Wi-Fi SweetSpots

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8070]
**App Name:** Wi-Fi SweetSpots
**Bundle ID:** com.assiainc.cloudcheck.wifisweetspots
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=855457383">855457383</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wi-fi-sweetspots/id855457383?mt=8&uo=4">https://itunes.apple.com/us/app/wi-fi-sweetspots/id855457383?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** ASSIA Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/assia-inc/id722428566?uo=4>© ASSIA-Inc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/75/52/84/755284b5-15db-2fd8-6b38-8de2925d12e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18724148/a5a95530-803b-11e6-87b7-148702b8f55f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18724148/a5a95530-803b-11e6-87b7-148702b8f55f.png)
https://cloud.githubusercontent.com/assets/20930745/18724148/a5a95530-803b-11e6-87b7-148702b8f55f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18724209/d98d1508-803b-11e6-9aae-b6e58c29a0b7.png
