### ISSUE TITLE
RainToday - HD Radar

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8074]
**App Name:** RainToday - HD Radar
**Bundle ID:** de.meteogroup.RainToday
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=326461840">326461840</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/raintoday-hd-radar/id326461840?mt=8&uo=4">https://itunes.apple.com/gb/app/raintoday-hd-radar/id326461840?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** MeteoGroup Deutschland GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/meteogroup-deutschland-gmbh/id294631162?uo=4>© MeteoGroup Deutschland GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/da/f1/11/daf1110b-3f19-57a9-cd38-bd190147a9a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18726921/ddda01a6-8046-11e6-8288-75ede56f69ca.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/18725650/722482ec-8041-11e6-8132-74478953f066.png)

https://cloud.githubusercontent.com/assets/16171251/18725650/722482ec-8041-11e6-8132-74478953f066.png

Source:
https://cloud.githubusercontent.com/assets/16171251/18725634/606d3116-8041-11e6-8dda-5d9060d9d0b6.png

**Comment by 2Qt2beStr8** [comment]
@Checkit23  what do you think about this one:

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18726921/ddda01a6-8046-11e6-8288-75ede56f69ca.png)
https://cloud.githubusercontent.com/assets/20930745/18726921/ddda01a6-8046-11e6-8288-75ede56f69ca.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18726943/f0ec9cc2-8046-11e6-962d-ff58bfc37053.png

**Comment by Checkit23** [comment]
I like yours better:-)

**Comment by 2Qt2beStr8** [comment]
thank you :-)
