### ISSUE TITLE
ABC

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8079]
**App Name:** ABC
**Bundle ID:** au.net.abc.ABC
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=306583229">306583229</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/abc/id306583229?uo=4">https://apps.apple.com/us/app/abc/id306583229?uo=4</a>
**App Version:** 6.1.0
**Seller:** Australian Broadcasting Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/australian-broadcasting-corporation/id306583232?uo=4">© Australian Broadcasting Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/eb/88/c1/eb88c15a-83e9-8834-5da1-6de2018c5a03/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979533-75ee9780-95e9-11e9-8831-01eafe2a5802.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18739330/1b7d8346-80a3-11e6-9f2c-9bec5fecc25e.png)
https://cloud.githubusercontent.com/assets/20930745/18739330/1b7d8346-80a3-11e6-9f2c-9bec5fecc25e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18739277/af626262-80a2-11e6-9ed6-5ca2d638d6c9.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979533-75ee9780-95e9-11e9-8831-01eafe2a5802.png)
https://user-images.githubusercontent.com/2068130/59979533-75ee9780-95e9-11e9-8831-01eafe2a5802.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979536-84d54a00-95e9-11e9-80aa-c23f91e74b0a.png
