### ISSUE TITLE
Google Allo — smart messaging

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8080]
**App Name:** Google Allo — smart messaging
**Bundle ID:** com.google.fireball
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1096801294">1096801294</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-allo-smart-messaging/id1096801294?mt=8&uo=4">https://itunes.apple.com/us/app/google-allo-smart-messaging/id1096801294?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/42/6f/88/426f8855-fe71-9d8f-6c6a-b45fe113bd56/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18739501/592c228c-80a4-11e6-9c55-ad5050b7f86d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18739501/592c228c-80a4-11e6-9c55-ad5050b7f86d.png)
https://cloud.githubusercontent.com/assets/20930745/18739501/592c228c-80a4-11e6-9c55-ad5050b7f86d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18739508/69cda0ac-80a4-11e6-8dbe-f9a994334cf8.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18743842/41c8746c-80bb-11e6-8bef-44f39787d392.png)
https://cloud.githubusercontent.com/assets/20930745/18743842/41c8746c-80bb-11e6-8bef-44f39787d392.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18743861/57a83da8-80bb-11e6-9989-c29b60f3e0ce.png
