### ISSUE TITLE
NBC – Watch Now and Stream Full TV Episodes

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8081]
**App Name:** NBC – Watch Now and Stream Full TV Episodes
**Bundle ID:** com.nbcuni.nbc.portal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=442839435">442839435</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nbc-watch-now-stream-full/id442839435?mt=8&uo=4">https://itunes.apple.com/us/app/nbc-watch-now-stream-full/id442839435?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** NBCUniversal Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nbcuniversal-media-llc/id303544359?uo=4>© NBCUniversal Media, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/86/2a/ac/862aac5e-b8d0-3418-30e0-1d61d71e664b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18808832/28211a42-826d-11e6-82ce-7c8b12a97ffe.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18739779/48ed3f80-80a6-11e6-96a5-bda5fcbbd125.png)
https://cloud.githubusercontent.com/assets/20930745/18739779/48ed3f80-80a6-11e6-96a5-bda5fcbbd125.png

Source:
![sourcenbcwatch](https://cloud.githubusercontent.com/assets/20930745/18739807/6fca1aec-80a6-11e6-9ae8-5a2cadd0610b.png)

**Comment by 2Qt2beStr8** [comment]
.... or witch lettering

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18807755/dd281292-824f-11e6-9572-1ce5619b75d7.png)
https://cloud.githubusercontent.com/assets/20930745/18807755/dd281292-824f-11e6-9572-1ce5619b75d7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18807776/6ee1505e-8250-11e6-96fc-2f04e75a9fa2.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18808832/28211a42-826d-11e6-82ce-7c8b12a97ffe.png)
https://cloud.githubusercontent.com/assets/2068130/18808832/28211a42-826d-11e6-82ce-7c8b12a97ffe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18808833/361a8c5a-826d-11e6-99a8-ce0b2b8eeb78.png
