### ISSUE TITLE
NBC Sports Scores

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8082]
**App Name:** NBC Sports Scores
**Bundle ID:** com.nbcsports.news
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1123078102">1123078102</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nbc-sports-scores/id1123078102?mt=8&uo=4">https://itunes.apple.com/us/app/nbc-sports-scores/id1123078102?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** NBCUniversal Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nbcuniversal-media-llc/id303544359?uo=4>© NBCUniversal Media, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/a8/fd/8b/a8fd8b20-0eec-df50-42d9-0018855f27df/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18808815/bc18e7da-826c-11e6-91cf-dd4f0116164d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18739916/19b5f49a-80a7-11e6-871e-c04bf3770b01.png)
https://cloud.githubusercontent.com/assets/20930745/18739916/19b5f49a-80a7-11e6-871e-c04bf3770b01.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18739939/3a08c2c2-80a7-11e6-85f0-db5ddab4fe9f.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18740079/0d172f0a-80a8-11e6-91d5-b2872c6a16bd.png)
https://cloud.githubusercontent.com/assets/20930745/18740079/0d172f0a-80a8-11e6-91d5-b2872c6a16bd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18740111/2edf14f4-80a8-11e6-9003-895c23b9a268.png

**Comment by ivanov007** [comment]
@2Qt2beStr8 mhhh I don't know, I like the first one and it looks like #6899 but on the other hand there's #8081, I guess we need to make them all look alike

**Comment by dreamnet** [comment]
Ok, I'm trying to make all NBC icons look alike, here is the first one:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18808815/bc18e7da-826c-11e6-91cf-dd4f0116164d.png)
https://cloud.githubusercontent.com/assets/2068130/18808815/bc18e7da-826c-11e6-91cf-dd4f0116164d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18808817/cb0debbe-826c-11e6-93aa-9386176099cd.png
