### ISSUE TITLE
Evernote - stay organized

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8083]
**App Name:** Evernote - stay organized
**Bundle ID:** com.evernote.iPhone.Evernote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=281796108">281796108</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/evernote-stay-organized/id281796108?mt=8&uo=4">https://itunes.apple.com/us/app/evernote-stay-organized/id281796108?mt=8&uo=4</a>
**App Version:** 7.17.1
**Seller:** Evernote
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/evernote/id281796111?uo=4>© Evernote</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/bb/c7/c8/bbc7c861-d3a6-9b65-3f10-c8cd01c99c72/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18749259/46550642-80d6-11e6-8a8e-b9f2deb6a4a4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18749259/46550642-80d6-11e6-8a8e-b9f2deb6a4a4.png)
https://cloud.githubusercontent.com/assets/20930745/18749259/46550642-80d6-11e6-8a8e-b9f2deb6a4a4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18749289/7bff8ff6-80d6-11e6-8503-63321f52b0de.png

**Comment by ivanov007** [comment]
wow, that was fast :car:  :dash:
