### ISSUE TITLE
Hubbly Search

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8085]
**App Name:** Hubbly Search
**Bundle ID:** com.lucaiaconelli.Searchr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=876331631">876331631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hubbly-search/id876331631?mt=8&uo=4">https://itunes.apple.com/us/app/hubbly-search/id876331631?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** Luca Iaconelli
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/luca-iaconelli/id876331634?uo=4">© Luca Iaconelli</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/7e/44/81/7e448173-507b-9cc6-4a95-251746909fa6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49687810-d6642e80-fb08-11e8-8b69-2708fd310808.png)

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18753156/80ea9d54-80b2-11e6-9008-d860e5b138ff.png)

https://cloud.githubusercontent.com/assets/3704186/18753156/80ea9d54-80b2-11e6-9008-d860e5b138ff.png

https://cloud.githubusercontent.com/assets/3704186/18753166/869f3d22-80b2-11e6-80e9-95ea17b447c1.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Hubbly Search
**Bundle ID:** com.lucaiaconelli.Searchr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=876331631">876331631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hubbly-search/id876331631?mt=8&uo=4">https://itunes.apple.com/us/app/hubbly-search/id876331631?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** Luca Iaconelli
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/luca-iaconelli/id876331634?uo=4">© Luca Iaconelli</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/7e/44/81/7e448173-507b-9cc6-4a95-251746909fa6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49687810-d6642e80-fb08-11e8-8b69-2708fd310808.png)
https://user-images.githubusercontent.com/2068130/49687810-d6642e80-fb08-11e8-8b69-2708fd310808.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/49687816-e714a480-fb08-11e8-96a3-ba4a80ab130c.png
