### ISSUE TITLE
FOX Soccer 2Go

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8087]
**App Name:** FOX Soccer 2Go
**Bundle ID:** com.foxsoccerchannel.foxsoccer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395478916">395478916</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fox-soccer-2go/id395478916?mt=8&uo=4">https://itunes.apple.com/us/app/fox-soccer-2go/id395478916?mt=8&uo=4</a>
**App Version:** 2.3.6
**Seller:** Fox Soccer Channel
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fox-sports-channel/id395478919?uo=4>© FOX Sports Channel</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/27/bd/a2/27bda255-e577-468e-4318-ac78aba8606d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18757233/4644c328-80f3-11e6-90ba-c68ad59d408f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18757233/4644c328-80f3-11e6-90ba-c68ad59d408f.png)
https://cloud.githubusercontent.com/assets/20930745/18757233/4644c328-80f3-11e6-90ba-c68ad59d408f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18757250/62078096-80f3-11e6-8b26-c0967cd4c686.png
