### ISSUE TITLE
Ping Analyzer - Graphical Network Ping

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8088]
**App Name:** Ping Analyzer - Graphical Network Ping
**Bundle ID:** Pingin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406772587">406772587</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ping-analyzer-graphical-network/id406772587?mt=8&uo=4">https://itunes.apple.com/us/app/ping-analyzer-graphical-network/id406772587?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Adrian Granados-Murillo
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adrian-granados-murillo/id337359044?uo=4>© Adrian Granados-Murillo</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/75/21/8c/75218ccf-10cd-cc74-32de-a93a172e2014/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18757024/62ffcd2e-80f2-11e6-8586-884fef8ed159.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18757024/62ffcd2e-80f2-11e6-8586-884fef8ed159.png)
https://cloud.githubusercontent.com/assets/20930745/18757024/62ffcd2e-80f2-11e6-8586-884fef8ed159.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18757037/7236e8f4-80f2-11e6-8642-b6be79aff254.png
