### ISSUE TITLE
Julian Day

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8089]
**App Name:** Julian Day
**Bundle ID:** org.layton.julianday
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327766750">327766750</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/julian-day/id327766750?mt=8&uo=4">https://itunes.apple.com/us/app/julian-day/id327766750?mt=8&uo=4</a>
**App Version:** 1.42
**Seller:** Neal Layton
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/neal-layton/id310957519?uo=4>© Neal Layton</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/ae/e0/0a/aee00ae5-b699-be13-e04b-812f4d658c26/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808892/c98347f6-826e-11e6-899d-46cdcfc45c44.png)

**Comment by 2Qt2beStr8** [comment]
hmmm ... i am not really happy with this icon ... but no other idea :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18781111/b6d24e3e-8180-11e6-815e-e7e0b84f9258.png)
https://cloud.githubusercontent.com/assets/20930745/18781111/b6d24e3e-8180-11e6-815e-e7e0b84f9258.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18781131/c9e3db50-8180-11e6-9088-75ac2e7a1960.png

**Comment by ivanov007** [comment]
@2Qt2beStr8 maybe inverted?

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18793219/0a00748a-81ba-11e6-97fb-4ac9d933e1a9.png)
https://cloud.githubusercontent.com/assets/20930745/18793219/0a00748a-81ba-11e6-97fb-4ac9d933e1a9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18793242/1b9574a2-81ba-11e6-8d8a-a92096439a2a.png

**Comment by 2Qt2beStr8** [comment]
with thicker separation lines

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808892/c98347f6-826e-11e6-899d-46cdcfc45c44.png)
https://cloud.githubusercontent.com/assets/20930745/18808892/c98347f6-826e-11e6-899d-46cdcfc45c44.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18808894/dd92b34e-826e-11e6-9795-78edb082a843.png

**Comment by dreamnet** [comment]
Jup. I like the last one.
