### ISSUE TITLE
insTuner Free - Chromatic Tuner

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8091]
**App Name:** insTuner Free - Chromatic Tuner
**Bundle ID:** com.xiaoyixiang.instunerlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=603425027">603425027</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instuner-free-chromatic-tuner/id603425027?mt=8&uo=4">https://itunes.apple.com/us/app/instuner-free-chromatic-tuner/id603425027?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Xanin Technology GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eumlab-of-xanin-tech.-gmbh/id854557987?uo=4>© EUMLab of Xanin Tech. GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/9e/37/84/9e3784bc-ebe2-adf0-60da-a93867cfa334/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18763580/510a8be2-810e-11e6-9286-c0b6ac6da643.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18763580/510a8be2-810e-11e6-9286-c0b6ac6da643.png)
https://cloud.githubusercontent.com/assets/20930745/18763580/510a8be2-810e-11e6-9286-c0b6ac6da643.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18763598/6352ed3a-810e-11e6-8294-d4cf4df333fc.png
