### ISSUE TITLE
HindiWriter

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8092]
**App Name:** HindiWriter
**Bundle ID:** com.anujinfotech.hindiwriter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406646709">406646709</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hindiwriter/id406646709?mt=8&uo=4">https://itunes.apple.com/us/app/hindiwriter/id406646709?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Devendra Parakh
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/devendra-parakh/id395893149?uo=4>© Devendra Parakh</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/90/49/9d/90499df9-18b4-b70f-cfc0-b7c1917f465d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18763230/af685fea-810c-11e6-9ee3-cec3f76a0963.png)

**Comment by 2Qt2beStr8** [comment]
why is the artwork so small?

**Comment by Trubbel** [comment]
@2Qt2beStr8 Probably because the application was last updated back in 2011.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/18763234/b117baa2-810c-11e6-81e4-368013964f15.png)
https://cloud.githubusercontent.com/assets/10730122/18763234/b117baa2-810c-11e6-81e4-368013964f15.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/18763235/b118c30c-810c-11e6-87a1-75002241f128.png

**Comment by 2Qt2beStr8** [comment]
i am not sure if you like it .. i used a other artwork from the www

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18763230/af685fea-810c-11e6-9ee3-cec3f76a0963.png)
https://cloud.githubusercontent.com/assets/20930745/18763230/af685fea-810c-11e6-9ee3-cec3f76a0963.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18763322/1f7a57fc-810d-11e6-82a5-14c75e7e2b71.png

**Comment by Sly-Fi** [comment]
That is pretty! - Nice "A" अ

**Comment by dreamnet** [comment]
@2Qt2beStr8 Wow, just a view weeks and you are [Number 7](https://github.com/glasklart/hd/graphs/contributors)... Great!

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... thank you ... i do my best :-)
