### ISSUE TITLE
Devanagari QuickRef

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8093]
**App Name:** Devanagari QuickRef
**Bundle ID:** com.rdbell.DvngriQR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338191331">338191331</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/devanagari-quickref/id338191331?mt=8&uo=4">https://itunes.apple.com/us/app/devanagari-quickref/id338191331?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Ronald Bell
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ronald-bell/id288820101?uo=4>© Ronald Bell</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/6a/03/58/6a035864-a1f1-fe4d-1a85-bd7c518584b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18759974/50cb1d72-80ff-11e6-9029-9f725549af9f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18759974/50cb1d72-80ff-11e6-9029-9f725549af9f.png)
https://cloud.githubusercontent.com/assets/20930745/18759974/50cb1d72-80ff-11e6-9029-9f725549af9f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18759991/6868c79a-80ff-11e6-9ea5-6445116cdfa7.png
