### ISSUE TITLE
Grand Theft Auto V: The Manual

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#8099]
**App Name:** Grand Theft Auto V: The Manual
**Bundle ID:** com.rockstargames.gtavmanual
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=699032795">699032795</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grand-theft-auto-v-the-manual/id699032795?mt=8&uo=4">https://itunes.apple.com/us/app/grand-theft-auto-v-the-manual/id699032795?mt=8&uo=4</a>
**App Version:** 5.0.1
**Seller:** Rockstar Games, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rockstar-games/id330049731?uo=4>© Rockstar Games</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/11/7d/b8/117db8a2-3c8e-a0ed-6651-383e3cfd7229/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18784945/d32db27a-8195-11e6-8248-cb67ae5d4bd6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18784945/d32db27a-8195-11e6-8248-cb67ae5d4bd6.png)
https://cloud.githubusercontent.com/assets/20930745/18784945/d32db27a-8195-11e6-8248-cb67ae5d4bd6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18784956/e4a7f9c0-8195-11e6-9a1e-e6522e590125.png
