### ISSUE TITLE
Pixplit - Social Photos

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#810]
Name: Pixplit - Social Photos
Bundle ID: com.pixplit.pixplit
iTunes ID: 537572752
PNG Icon Names: icon.png | icon@2x.png
Artwork URL: http://i.imgur.com/qTFhaT8.png
![150px Preview](http://i.imgur.com/OFfz9vE.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409046/ec398d9c-92cb-11e6-9184-f3520e53d00d.png)
https://cloud.githubusercontent.com/assets/20930745/19409046/ec398d9c-92cb-11e6-9184-f3520e53d00d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409049/fdb86ebc-92cb-11e6-8cdb-6766eea4430a.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409090/384cc7c0-92cd-11e6-8d7f-04ca6704bb33.png)
https://cloud.githubusercontent.com/assets/20930745/19409090/384cc7c0-92cd-11e6-8d7f-04ca6704bb33.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409095/4a64393e-92cd-11e6-8bf1-5d5576b7c83d.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Are you using this app? It dosen't seem to exist anymore....

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... no ... i forget to check it  ... sorry

**Comment by dreamnet** [comment]
@2Qt2beStr8 OK, then this stays closed until we get a request to add it.
