### ISSUE TITLE
LastPass – Free Password Manager & Secure Vault with Private Notes & Passcode Generator

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#8100]
**App Name:** LastPass – Free Password Manager & Secure Vault with Private Notes & Passcode Generator
**Bundle ID:** com.lastpass.ilastpass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324613447">324613447</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lastpass-free-password-manager/id324613447?mt=8&uo=4">https://itunes.apple.com/us/app/lastpass-free-password-manager/id324613447?mt=8&uo=4</a>
**App Version:** 4.0.8
**Seller:** Marvasol, Inc DBA LastPass
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/marvasol-inc-dba-lastpass/id324613450?uo=4>© Marvasol, Inc DBA LastPass</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/99/a2/ae/99a2ae32-4f96-8406-310f-3ee2eab62a9f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18785078/787a92e8-8196-11e6-9c49-47ca79ef591c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18785078/787a92e8-8196-11e6-9c49-47ca79ef591c.png)
https://cloud.githubusercontent.com/assets/20930745/18785078/787a92e8-8196-11e6-9c49-47ca79ef591c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18785090/8b400b4c-8196-11e6-9ed6-e9c1c4ace193.png
