### ISSUE TITLE
UnlimTones

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#8101]
**App Name:** UnlimTones
**Bundle ID:** com.unlimapps.UnlimTones
**Version:** 4.8.3
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/96/cf/1a/96cf1ab6-e8d4-7a05-2997-4de3facea478/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18785277/a5d371e6-8197-11e6-9694-554f75b1b2f1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18785277/a5d371e6-8197-11e6-9694-554f75b1b2f1.png)
https://cloud.githubusercontent.com/assets/20930745/18785277/a5d371e6-8197-11e6-9694-554f75b1b2f1.png


Source:
https://cloud.githubusercontent.com/assets/20930745/18785376/28175c4e-8198-11e6-99fe-dfbdaf97f720.png

**Comment by ivanov007** [comment]
@2Qt2beStr8 you are on fire :fire: :fire_engine: :fire:
