### ISSUE TITLE
Oz Weather Plus - Australia

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8102]
**App Name:** Oz Weather Plus - Australia
**Bundle ID:** com.ajnaware.OzWeatherPlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=731781859">731781859</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/oz-weather-plus-australia/id731781859?mt=8&uo=4">https://itunes.apple.com/us/app/oz-weather-plus-australia/id731781859?mt=8&uo=4</a>
**App Version:** 2.8
**Seller:** Ajnaware Pty Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ozpda/id295147488?uo=4>© ozPDA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/0e/79/78/0e797858-6839-578d-d982-fedc0f3bdf61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18806749/29e13ce0-8236-11e6-84e6-bbb4e3a9d6e7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18806749/29e13ce0-8236-11e6-84e6-bbb4e3a9d6e7.png)
https://cloud.githubusercontent.com/assets/20930745/18806749/29e13ce0-8236-11e6-84e6-bbb4e3a9d6e7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18806755/3f56c39c-8236-11e6-8dbf-ecefe8ddeffc.png
