### ISSUE TITLE
Angry Birds Seasons

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8103]
**App Name:** Angry Birds Seasons
**Bundle ID:** com.rovio.AngryBirdsHalloween
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398157641">398157641</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds-seasons/id398157641?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds-seasons/id398157641?mt=8&uo=4</a>
**App Version:** 6.3.1
**Seller:** Rovio Entertainment Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rovio-entertainment-ltd/id298910979?uo=4>© Rovio Entertainment Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/cc/a9/81/cca9811e-bbbb-46bf-d038-22ac33928f03/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18813490/0701bde6-82fc-11e6-8c16-b411c65bdbb7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18813490/0701bde6-82fc-11e6-8c16-b411c65bdbb7.png)
https://cloud.githubusercontent.com/assets/2068130/18813490/0701bde6-82fc-11e6-8c16-b411c65bdbb7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18813492/14618d72-82fc-11e6-9402-b6fac66f2075.png
