### ISSUE TITLE
Australia Post Mobile

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8104]
**App Name:** Australia Post Mobile
**Bundle ID:** com.auspost.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380897313">380897313</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/australia-post-mobile/id380897313?mt=8&uo=4">https://itunes.apple.com/us/app/australia-post-mobile/id380897313?mt=8&uo=4</a>
**App Version:** 3.8.1
**Seller:** Australia Post
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/australia-post/id380897316?uo=4>© Australia Post</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/28/7a/c5/287ac592-4a3a-5c66-f09f-133f2f38260f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18806660/8e0d5eea-8233-11e6-9d73-77a2cdc7f3c7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18806660/8e0d5eea-8233-11e6-9d73-77a2cdc7f3c7.png)
https://cloud.githubusercontent.com/assets/20930745/18806660/8e0d5eea-8233-11e6-9d73-77a2cdc7f3c7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18806661/aa7ead54-8233-11e6-9d4b-452f265a36c9.png
