### ISSUE TITLE
Event Cinemas

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8105]
**App Name:** Event Cinemas
**Bundle ID:** au.com.greaterunion.PocketCinema
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=299120285">299120285</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/hk/app/event-cinemas/id299120285?uo=4">https://apps.apple.com/hk/app/event-cinemas/id299120285?uo=4</a>
**App Version:** 7.10.6
**Seller:** Amalgamated Holdings Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/hk/developer/event-cinemas/id684074593?uo=4">© Event Cinemas</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/23/21/54/23215471-b0d1-09e2-4a93-f5eb1c603126/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388264-36272480-9aaf-11e9-9a11-27188a6d8e6d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18806717/27a801bc-8235-11e6-971b-118543676db7.png)
https://cloud.githubusercontent.com/assets/20930745/18806717/27a801bc-8235-11e6-971b-118543676db7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18806719/40e5e108-8235-11e6-9259-5b70bb92b0b0.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388264-36272480-9aaf-11e9-9a11-27188a6d8e6d.png)
https://user-images.githubusercontent.com/20930745/60388264-36272480-9aaf-11e9-9a11-27188a6d8e6d.png

Source:
https://user-images.githubusercontent.com/20930745/60388265-38897e80-9aaf-11e9-9bb6-8dad9a686507.png
