### ISSUE TITLE
Parkopedia Parking

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8107]
**App Name:** Parkopedia Parking
**Bundle ID:** com.parkopedia.parkopediaworldwide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409340361">409340361</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parkopedia-parking/id409340361?mt=8&uo=4">https://itunes.apple.com/us/app/parkopedia-parking/id409340361?mt=8&uo=4</a>
**App Version:** 2.0.21
**Seller:** Parkopedia
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/parkopedia-ltd/id365260105?uo=4>© Parkopedia Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/0d/8e/f2/0d8ef207-72a4-c9fa-9b2b-6e38c935dd3c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808516/d95a9ed6-8264-11e6-8ba7-4ef372c2f634.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18808516/d95a9ed6-8264-11e6-8ba7-4ef372c2f634.png)
https://cloud.githubusercontent.com/assets/20930745/18808516/d95a9ed6-8264-11e6-8ba7-4ef372c2f634.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18808523/f759059e-8264-11e6-9499-7c2d66a94e86.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Whoahhh... 😮

**Comment by 2Qt2beStr8** [comment]
@dreamnet ...  i am proud to me if you like it :-)
