### ISSUE TITLE
Hill Climb Racing

### ISSUE THREAD

**Issue by Ardauq** [glasklart/hd#811]
**App Name:** Hill Climb Racing
**Bundle ID:** com.fingersoft.hillclimbracing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=564540143">564540143</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hill-climb-racing/id564540143?mt=8&uo=4">https://itunes.apple.com/us/app/hill-climb-racing/id564540143?mt=8&uo=4</a>
**App Version:** 1.30.3
**Seller:** Fingersoft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fingersoft/id514034278?uo=4>© Fingersoft</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/dd/d4/64/ddd464f5-f358-1151-e162-1cae44282937/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19013152/65aabd76-87c9-11e6-9efa-d56bcd6bbb6f.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
... only a try ... i don't like it ... 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18913307/704efeca-8587-11e6-951b-4249a91fb04d.png)
https://cloud.githubusercontent.com/assets/20930745/18913307/704efeca-8587-11e6-951b-4249a91fb04d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18913349/a76cdb70-8587-11e6-9606-2a6b664b7b7d.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19013152/65aabd76-87c9-11e6-9efa-d56bcd6bbb6f.png)
https://cloud.githubusercontent.com/assets/2068130/19013152/65aabd76-87c9-11e6-9efa-d56bcd6bbb6f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19013156/74ed9e8e-87c9-11e6-878c-b8075ee5b829.png
