### ISSUE TITLE
WebWatch - The Web for Apple Watch

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8110]
**App Name:** WebWatch - The Web for Apple Watch
**Bundle ID:** com.komocode.WebWatch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=987165656">987165656</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/webwatch-web-for-apple-watch/id987165656?mt=8&uo=4">https://itunes.apple.com/us/app/webwatch-web-for-apple-watch/id987165656?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** NICHOLAS C CHAN
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/komocode/id376553676?uo=4>© Komocode</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/17/f7/13/17f713fd-9fe1-8892-8bb9-305161973127/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809529/fcba2aae-827d-11e6-8c37-9f0df20d4bf4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18809529/fcba2aae-827d-11e6-8c37-9f0df20d4bf4.png)
https://cloud.githubusercontent.com/assets/20930745/18809529/fcba2aae-827d-11e6-8c37-9f0df20d4bf4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18809533/0c5b9204-827e-11e6-8622-e9b971f1645e.png
