### ISSUE TITLE
Digits app icon request

### ISSUE THREAD

**Issue by lex325** [glasklart/hd#8111]
Hi there may I submit an icon request for "Digits"? It is a calculator app. I'm not sure I am submitting the correct way

**Comment by 2Qt2beStr8** [comment]
Hi @lex325 

Here is the "How to"

https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request

**Comment by dreamnet** [comment]
@lex325 Already done in #1330. The icon will be in release v5.01.
