### ISSUE TITLE
Solar Walk™ - Planets System, Orbits, Moons & Size

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8112]
**App Name:** Solar Walk™ - Planets System, Orbits, Moons & Size
**Bundle ID:** com.vitotechnology.SolarWalk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347546771">347546771</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/solar-walk-planets-system/id347546771?mt=8&uo=4">https://itunes.apple.com/us/app/solar-walk-planets-system/id347546771?mt=8&uo=4</a>
**App Version:** 2.3.7
**Seller:** Vito Technology Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vito-technology-inc./id289641503?uo=4>© Vito Technology Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/ef/09/14/ef09142f-7116-b769-c12d-26d5b4c54ff7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19020562/ca2edd98-88ac-11e6-8479-7c451953e3d2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19020375/ea161960-88a6-11e6-81aa-24b698206f51.png)
https://cloud.githubusercontent.com/assets/20930745/19020375/ea161960-88a6-11e6-81aa-24b698206f51.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19020376/0a7f37ae-88a7-11e6-95ca-79925920c1f9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19020562/ca2edd98-88ac-11e6-8479-7c451953e3d2.png)
https://cloud.githubusercontent.com/assets/20930745/19020562/ca2edd98-88ac-11e6-8479-7c451953e3d2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19020563/e2bc7c1c-88ac-11e6-84e1-0bdae0fbe660.png
