### ISSUE TITLE
Toshl Finance - expense tracker & budget manager

### ISSUE THREAD

**Issue by lightness90** [glasklart/hd#8113]
**App Name:** Toshl Finance - expense tracker & budget manager
**Bundle ID:** com.toshl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=921590251">921590251</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/toshl-finance-expense-tracker/id921590251?mt=8&uo=4">https://itunes.apple.com/us/app/toshl-finance-expense-tracker/id921590251?mt=8&uo=4</a>
**App Version:** 2.0.10
**Seller:** Toshl Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/toshl-inc./id921590250?uo=4>© Toshl Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple30/v4/01/a6/5d/01a65d76-89de-3bae-276a-da1d8119eb94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18817662/8869f636-8366-11e6-9963-5c5983248af8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18817662/8869f636-8366-11e6-9963-5c5983248af8.png)
https://cloud.githubusercontent.com/assets/20930745/18817662/8869f636-8366-11e6-9963-5c5983248af8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18817667/9858a36c-8366-11e6-8806-621c12b8da31.png

**Comment by Trubbel** [comment]
@lightness90 Please don't close your own issues, we _(the Glasklart maintainers)_ will close this issue once the icon is accepted and added to the master.

**Comment by lightness90** [comment]
Sorry, thanks for letting me know.

**Comment by Trubbel** [comment]
@lightness90 No harm done, I once made the same mistake. :smile:
