### ISSUE TITLE
Fantasy Alarm

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8115]
**App Name:** Fantasy Alarm
**Bundle ID:** com.fantasyalarm.fantasyalarmnfl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=536441782">536441782</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/fantasy-alarm/id536441782?uo=4">https://apps.apple.com/us/app/fantasy-alarm/id536441782?uo=4</a>
**App Version:** 223
**Seller:** FantasyAlarm.com, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fantasyalarm-com/id458639792?uo=4">© FantasyAlarm.com</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/1d/15/60/1d156050-c242-88e3-8ec9-b3c472125c0c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393526-1cb9c300-9b17-11e9-9424-ebbc4600bef4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18829694/bf492948-83dd-11e6-8b73-545ffa19a159.png)
https://cloud.githubusercontent.com/assets/20930745/18829694/bf492948-83dd-11e6-8b73-545ffa19a159.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18829738/e51a0a5c-83dd-11e6-8a2f-7858b5269d08.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18830148/bb76d6c4-83df-11e6-9baf-5ff40f37dc5c.png)
https://cloud.githubusercontent.com/assets/20930745/18830148/bb76d6c4-83df-11e6-9baf-5ff40f37dc5c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18830157/d1c50018-83df-11e6-851c-fdf49dcdec9c.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60393526-1cb9c300-9b17-11e9-9424-ebbc4600bef4.png)
https://user-images.githubusercontent.com/20930745/60393526-1cb9c300-9b17-11e9-9424-ebbc4600bef4.png

Source:
https://user-images.githubusercontent.com/20930745/60393527-1deaf000-9b17-11e9-8234-7f9c2d8d0341.png
