### ISSUE TITLE
Bitmoji - Your Personal Emoji

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8116]
**App Name:** Bitmoji - Your Personal Emoji
**Bundle ID:** com.bitstrips.imoji
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=868077558">868077558</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bitmoji-your-personal-emoji/id868077558?mt=8&uo=4">https://itunes.apple.com/us/app/bitmoji-your-personal-emoji/id868077558?mt=8&uo=4</a>
**App Version:** 9.39.1
**Seller:** Bitstrips Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bitstrips/id694701217?uo=4>© Bitstrips</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/26/44/d4/2644d4d3-9f4f-c2e4-d012-f93bb2690ecc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18828940/6e6003ba-83da-11e6-81c7-94a8fba8cf37.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18823922/8d61046a-83be-11e6-9cb0-1ed287260c5e.png)
https://cloud.githubusercontent.com/assets/20930745/18823922/8d61046a-83be-11e6-9cb0-1ed287260c5e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18823931/9fdfeac0-83be-11e6-9be2-9dbbc3c2a206.png

**Comment by 2Qt2beStr8** [comment]
I forgot to round the corners. I correct it as soon as possible- i am not at home at the moment
