### ISSUE TITLE
The Anchoring

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8117]
**App Name:** The Anchoring
**Bundle ID:** com.terrillo.ios.anchoring
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1141690431">1141690431</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-anchoring/id1141690431?mt=8&uo=4">https://itunes.apple.com/us/app/the-anchoring/id1141690431?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Terrillo Walls
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/terrillo-walls/id1102067646?uo=4>© Terrillo Walls</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/44/96/7c/44967cf4-ad20-0d77-1d6f-a15e3339c72c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18830396/ce6302e8-83e0-11e6-9c98-df2640ac6f71.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18830951/7383b144-83e3-11e6-827c-9279f2df3b9d.png)
https://cloud.githubusercontent.com/assets/20930745/18830951/7383b144-83e3-11e6-827c-9279f2df3b9d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18830976/8c4b6e9c-83e3-11e6-814f-e70a32a0505c.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18831175/a00d5ad4-83e4-11e6-911d-8a64c352e4bd.png)
https://cloud.githubusercontent.com/assets/20930745/18831175/a00d5ad4-83e4-11e6-911d-8a64c352e4bd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18831198/b44dc61e-83e4-11e6-99a0-f23339598387.png

**Comment by ivanov007** [comment]
first one :+1:
