### ISSUE TITLE
GPS Navigation, Maps & Traffic - Scout

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8127]
**App Name:** GPS Navigation, Maps & Traffic - Scout
**Bundle ID:** SkobblerDACH
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=329349116">329349116</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/gps-navigation-maps-traffic/id329349116?mt=8&uo=4">https://itunes.apple.com/de/app/gps-navigation-maps-traffic/id329349116?mt=8&uo=4</a>
**App Version:** 7.2
**Seller:** Telenav GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/telenav-gmbh/id329340714?uo=4>© Telenav GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/06/91/78/0691781f-7c27-ca57-73de-646676f7560a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18902728/0613f448-8555-11e6-81e2-f9bfb4a12958.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18865261/9854e3e6-849a-11e6-8dc1-fab9555cee90.png)
https://cloud.githubusercontent.com/assets/20930745/18865261/9854e3e6-849a-11e6-8dc1-fab9555cee90.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18865282/aef84052-849a-11e6-94f4-1c9b9a7307f2.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18865388/4c123fdc-849b-11e6-9f94-1026ef89900c.png)
https://cloud.githubusercontent.com/assets/20930745/18865388/4c123fdc-849b-11e6-9f94-1026ef89900c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18865399/5db533c0-849b-11e6-976f-9f6e65ec3f33.png
