### ISSUE TITLE
Plex

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8128]
**App Name:** Plex
**Bundle ID:** com.plexapp.plex
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=383457673">383457673</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/plex/id383457673?mt=8&uo=4">https://itunes.apple.com/us/app/plex/id383457673?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** Plex Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/plex-inc./id383457676?uo=4>© Plex Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/bb/fc/8e/bbfc8ea8-1e30-93f9-9992-cdf9a495d739/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18908651/bef1a120-8570-11e6-9ac0-1f460f362458.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18864108/109a1070-8495-11e6-88aa-de76f021e916.png)
https://cloud.githubusercontent.com/assets/20930745/18864108/109a1070-8495-11e6-88aa-de76f021e916.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18864196/782d0ed6-8495-11e6-92bf-19ab61c39597.png
