### ISSUE TITLE
Call of Duty: Black Ops Zombies

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8129]
**App Name:** Call of Duty: Black Ops Zombies
**Bundle ID:** com.activision.callofduty.blackopszombies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=471063940">471063940</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/call-of-duty-black-ops-zombies/id471063940?mt=8&uo=4">https://itunes.apple.com/us/app/call-of-duty-black-ops-zombies/id471063940?mt=8&uo=4</a>
**App Version:** 1.3.5
**Seller:** Activision Publishing, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/activision-publishing-inc./id285005466?mt=8&uo=4>© Activision Publishing, Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple2/v4/b3/16/48/b31648c7-78d4-67cb-cd28-f4f20605aae7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18902497/a9165804-8553-11e6-8744-531e3411e4a1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18865664/b43fc4ca-849c-11e6-8a27-0faaa8b2b2cd.png)
https://cloud.githubusercontent.com/assets/20930745/18865664/b43fc4ca-849c-11e6-8a27-0faaa8b2b2cd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18865819/64781a4a-849d-11e6-8982-c29fb62dcd44.png
