### ISSUE TITLE
ESPN Streak for the Cash

### ISSUE THREAD

**Issue by Gyella1** [glasklart/hd#813]
**App Name:** ESPN Streak for the Cash
**Bundle ID:** com.espn.ESPN-SFTC
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=340058356">340058356</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/espn-streak-for-the-cash/id340058356?mt=8&uo=4">https://itunes.apple.com/us/app/espn-streak-for-the-cash/id340058356?mt=8&uo=4</a>
**App Version:** 3.2.0
**Seller:** ESPN Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/espn/id317469187?uo=4>© ESPN</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/a1/d9/dd/a1d9ddf6-7e3c-055d-bd60-6833ac9ba10f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409144/71b1ab60-92ce-11e6-8285-bf918f411347.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409144/71b1ab60-92ce-11e6-8285-bf918f411347.png)
https://cloud.githubusercontent.com/assets/20930745/19409144/71b1ab60-92ce-11e6-8285-bf918f411347.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409148/7f41f780-92ce-11e6-902e-e7a3fea9ae74.png
