### ISSUE TITLE
Cut the Rope: Experiments

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8131]
**App Name:** Cut the Rope: Experiments
**Bundle ID:** com.zeptolab.ctrexperiments
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=450542233">450542233</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cut-the-rope-experiments/id450542233?mt=8&uo=4">https://itunes.apple.com/us/app/cut-the-rope-experiments/id450542233?mt=8&uo=4</a>
**App Version:** 1.7.6
**Seller:** ZeptoLab UK Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zeptolab-uk-limited/id450542236?uo=4>© ZeptoLab UK Limited</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple6/v4/1f/8f/59/1f8f5989-9c89-10ce-fb3b-e644e8298322/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18902581/3439cbdc-8554-11e6-8873-52470196424c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18873851/9e648ecc-84c1-11e6-8948-b172f60f6d13.png)
https://cloud.githubusercontent.com/assets/20930745/18873851/9e648ecc-84c1-11e6-8948-b172f60f6d13.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18873864/b0465bac-84c1-11e6-8d71-a02078a8f7e5.png
