### ISSUE TITLE
Guitar Hero

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8132]
**App Name:** Guitar Hero
**Bundle ID:** com.activision.guitarhero
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=374801345">374801345</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/apple-store/id374801345?mt=8">https://itunes.apple.com/us/app/apple-store/id374801345?mt=8</a>
**App Version:** 2.1.0
**Seller:** Activision Publishing, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/activision-publishing-inc./id285005466?mt=8&uo=4>© Activision Publishing, Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPhone4S, iPhone5, iPhone5c, iPhone5s, iPodTouchFifthGen, iPodTouchThirdGen, iPodTouchourthGen, iPad23G, iPad2Wifi, iPad3G, iPadFourthGen, iPadFourthGen4G, iPadThirdGen, iPadThirdGen4G, iPadWifi, iPadMini, iPadMini4G
**Original Artwork:**
<img src="https://glasklarthd.dreamnet.at/theicons/1662/com.activision.guitarhero_orig_big.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18902904/432a4cc8-8556-11e6-8fbf-1b30075e95c7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18867061/fb1f39a6-84a2-11e6-9680-bcad488dda9d.png)
https://cloud.githubusercontent.com/assets/20930745/18867061/fb1f39a6-84a2-11e6-9680-bcad488dda9d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18867089/1a027a22-84a3-11e6-90a8-ab4cd0a32ba1.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18867294/f59f0e1a-84a3-11e6-9ba1-e6ca71c891ce.png)
https://cloud.githubusercontent.com/assets/20930745/18867294/f59f0e1a-84a3-11e6-9ba1-e6ca71c891ce.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18867306/04f487c8-84a4-11e6-904e-33685a499b83.png
