### ISSUE TITLE
Jenga

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8133]
**App Name:** Jenga
**Bundle ID:** com.naturalmotion.j3n64
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=392915994">392915994</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jenga/id392915994?mt=8&uo=4">https://itunes.apple.com/us/app/jenga/id392915994?mt=8&uo=4</a>
**App Version:** 1.7.6
**Seller:** NaturalMotion Games Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/naturalmotion/id330281898?uo=4>© NaturalMotion</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/28/8f/77/288f77f6-b19a-5096-a5c4-669d2d58115b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18907918/db4462de-856d-11e6-81c4-3a3973c849ee.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18866507/92c80a24-84a0-11e6-85a3-bbcb56189b2f.png)
https://cloud.githubusercontent.com/assets/20930745/18866507/92c80a24-84a0-11e6-85a3-bbcb56189b2f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18866525/a6e1c2e8-84a0-11e6-8e8a-c87582e0b3a9.png
