### ISSUE TITLE
Monster Dash

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8134]
**App Name:** Monster Dash
**Bundle ID:** com.Halfbrick.Monster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=370070561">370070561</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/monster-dash/id370070561?mt=8&uo=4">https://itunes.apple.com/us/app/monster-dash/id370070561?mt=8&uo=4</a>
**App Version:** 2.6.0
**Seller:** Halfbrick
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/halfbrick-studios/id356994313?uo=4>© Halfbrick Studios</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/60/34/6d/60346dd4-89cc-51e0-60f9-0808e1b86967/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19143439/41933204-8ba4-11e6-9245-1d2fee402ced.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19126279/88b2a7ce-8b3a-11e6-9335-29bbca1adcdd.png)
https://cloud.githubusercontent.com/assets/20930745/19126279/88b2a7ce-8b3a-11e6-9335-29bbca1adcdd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19126366/e6e258da-8b3a-11e6-88a9-872e8ea83b98.png

**Comment by Anuskuss** [comment]
@2Qt2beStr8 I think this version is only seasonal (winter update). I will try to get the normal artwork.

**Comment by 2Qt2beStr8** [comment]
and why did you tell me this after i spent over 1 hour for this Icon ?

**Comment by Anuskuss** [comment]
@2Qt2beStr8 I'm not sure man I'm just checking if a "normal" icon even exists. Sorry bout that :disappointed_relieved:

**Comment by Anuskuss** [comment]
2.5.0 | 2.3.0 | Reference
--- | --- | --- | ---
![](https://cloud.githubusercontent.com/assets/7157389/19129145/86ff0966-8b46-11e6-943e-4cbeeecb6831.png) | ![](https://cloud.githubusercontent.com/assets/7157389/19129144/86fd934c-8b46-11e6-9630-500a824b4c44.png) | ![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/7157389/19129142/86fb2f80-8b46-11e6-9bcb-e0bf2cd387e8.png)

The icon didn't change much except for the cap, so it shouldn't be *that* difficult to adjust.

**Comment by dreamnet** [comment]
Thats the same guy as in #68. So I took the whole head from there, did a little resizing and placed it in the icon from @2Qt2beStr8. Result:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19143439/41933204-8ba4-11e6-9245-1d2fee402ced.png)
https://cloud.githubusercontent.com/assets/2068130/19143439/41933204-8ba4-11e6-9245-1d2fee402ced.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19143450/507ceb16-8ba4-11e6-9b4d-f1455bbb8336.png
@2Qt2beStr8 You did great work, all credits for this icon are going to you.

**Comment by 2Qt2beStr8** [comment]
hmm ... my last post is missed :-(

i have a version with dark eyebrowes

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19146222/e32c52ea-8bb2-11e6-8814-d44fcf8df56a.png)
https://cloud.githubusercontent.com/assets/20930745/19146222/e32c52ea-8bb2-11e6-8814-d44fcf8df56a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19146246/fb74b266-8bb2-11e6-9ddc-df7c7ec17986.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 I have no feelings about the eyebrowes, but they should made the same way as in #68.
