### ISSUE TITLE
UNO

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8135]
**App Name:** UNO
**Bundle ID:** com.gameloft.uno
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=286287605">286287605</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/uno/id286287605?mt=8&uo=4">https://itunes.apple.com/us/app/uno/id286287605?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Gameloft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/gameloft/id282764297?mt=8&uo=4>© Gameloft</a>
**Supported Devices:** iPhone4, iPhone4S, iPhone5, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchFifthGen, iPad23G, iPad2Wifi, iPadFourthGen, iPadFourthGen4G, iPadThirdGen, iPadThirdGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="https://glasklarthd.dreamnet.at/theicons/454/com.gameloft.uno_orig_big.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19002342/e9b32596-874b-11e6-9e2d-eb61fde155c0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18986984/d02da7be-86ff-11e6-96c2-b2cb69fd5306.png)
https://cloud.githubusercontent.com/assets/20930745/18986984/d02da7be-86ff-11e6-96c2-b2cb69fd5306.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18987208/e3ebacdc-8700-11e6-89ef-820768e4b05a.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18987240/104261a4-8701-11e6-8741-559beecb74a6.png)
https://cloud.githubusercontent.com/assets/20930745/18987240/104261a4-8701-11e6-8741-559beecb74a6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18987254/213358e2-8701-11e6-90f7-0b394a045a7a.png

**Comment by dreamnet** [comment]
Just some small corrections:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19002342/e9b32596-874b-11e6-9e2d-eb61fde155c0.png)
https://cloud.githubusercontent.com/assets/2068130/19002342/e9b32596-874b-11e6-9e2d-eb61fde155c0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19002355/f88eab76-874b-11e6-9476-7e8ba96fd408.png
