### ISSUE TITLE
Snake Rewind

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8136]
**App Name:** Snake Rewind
**Bundle ID:** com.rumilusdesign.snake
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=915939754">915939754</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snake-rewind/id915939754?mt=8&uo=4">https://itunes.apple.com/us/app/snake-rewind/id915939754?mt=8&uo=4</a>
**App Version:** 1.1.0.1
**Seller:** Rumilus Design Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rumilus-design/id588784978?uo=4>© Rumilus Design</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/5b/d7/84/5bd78429-01b0-6f0e-6274-72760c075d1c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18908772/41558b5e-8571-11e6-95f8-93b4aa17bae1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18864467/c60a9b4a-8496-11e6-8a96-0b1032f9eb5f.png)
https://cloud.githubusercontent.com/assets/20930745/18864467/c60a9b4a-8496-11e6-8a96-0b1032f9eb5f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18864480/d61ff2b4-8496-11e6-9f76-cdc50b68301c.png
