### ISSUE TITLE
Either Free

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8138]
**App Name:** Either Free
**Bundle ID:** com.onemightyroar.YouRatherFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=494408835">494408835</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/either-free/id494408835?mt=8&uo=4">https://itunes.apple.com/us/app/either-free/id494408835?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** One Mighty Roar, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/one-mighty-roar/id494407422?uo=4>© One Mighty Roar</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/08/10/6b/08106bc3-32f7-bb25-995e-d78ff448d46c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18887147/4871b26a-84f3-11e6-9238-79c30344c19c.png)

**Comment by dreamnet** [comment]
Refers to #8137.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18863893/fafe7c16-8493-11e6-8a9f-b11a4d9adde2.png)
https://cloud.githubusercontent.com/assets/20930745/18863893/fafe7c16-8493-11e6-8a9f-b11a4d9adde2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18863920/12df3d48-8494-11e6-9df3-209d77ba6e60.png
