### ISSUE TITLE
ZOLT: Summaries of the latest news

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8141]
**App Name:** ZOLT: Summaries of the latest news
**Bundle ID:** com.zoltapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1077946687">1077946687</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zolt-summaries-latest-news/id1077946687?mt=8&uo=4">https://itunes.apple.com/us/app/zolt-summaries-latest-news/id1077946687?mt=8&uo=4</a>
**App Version:** 2.8
**Seller:** Zolt Media Private Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zolt-media/id1077946686?uo=4>© Zolt Media</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/24/90/d2/2490d248-2c30-e466-7f8f-b981826f9edd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18935412/27bd50a4-85e0-11e6-8316-926ce08d1c2a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18884356/64a794d8-84e7-11e6-8294-b0e9d8148a01.png)
https://cloud.githubusercontent.com/assets/20930745/18884356/64a794d8-84e7-11e6-8294-b0e9d8148a01.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18884395/8477fca8-84e7-11e6-9664-6c1abbfbefa7.png

**Comment by BrokenCommander** [comment]
Cleaner:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18893089/a3cb326c-850c-11e6-9cb5-5c648242c8a5.png)
https://cloud.githubusercontent.com/assets/22012363/18893089/a3cb326c-850c-11e6-9cb5-5c648242c8a5.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18893084/a119f21a-850c-11e6-97da-b0a891c49542.png

**Comment by 2Qt2beStr8** [comment]
@BrokenCommander ... your "Z" is too small ... you must keep the original size
