### ISSUE TITLE
MyChart

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#8142]
**App Name:** MyChart
**Bundle ID:** com.epic.mychart
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382952264">382952264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mychart/id382952264?mt=8&uo=4">https://itunes.apple.com/us/app/mychart/id382952264?mt=8&uo=4</a>
**App Version:** 4.6
**Seller:** Epic Systems Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/epic/id348308666?uo=4>© Epic</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/0d/7e/56/0d7e56c2-8b75-d1c1-eb90-ae662fa80a4d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18885774/61767f62-84ed-11e6-9314-e85d039f2ae6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18885774/61767f62-84ed-11e6-9314-e85d039f2ae6.png)
https://cloud.githubusercontent.com/assets/20930745/18885774/61767f62-84ed-11e6-9314-e85d039f2ae6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18885915/f5d6de40-84ed-11e6-8a5c-5e384e85bd6f.png
