### ISSUE TITLE
BCBSIL

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#8143]
**App Name:** BCBSIL
**Bundle ID:** A6K4972J7H.com.bcbsil.providerfinder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571088532">571088532</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bcbsil/id571088532?mt=8&uo=4">https://itunes.apple.com/us/app/bcbsil/id571088532?mt=8&uo=4</a>
**App Version:** 2.6.4
**Seller:** Blue Cross and Blue Shield of Illinois
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/blue-cross-blue-shield-illinois/id571088535?uo=4>© Blue Cross and Blue Shield of Illinois</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/a9/db/22/a9db22bc-f092-e339-21c6-8dcb4ec22587/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18888182/92c6623a-84f7-11e6-9e85-a0d6d0c6bfa8.png)

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18888182/92c6623a-84f7-11e6-9e85-a0d6d0c6bfa8.png)
https://cloud.githubusercontent.com/assets/22012363/18888182/92c6623a-84f7-11e6-9e85-a0d6d0c6bfa8.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18888178/8ee5494c-84f7-11e6-8090-bc08c9cd91ce.png

**Comment by 2Qt2beStr8** [comment]
... or something like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18888505/ecb414e4-84f8-11e6-85af-5814109c13fe.png)

https://cloud.githubusercontent.com/assets/20930745/18888505/ecb414e4-84f8-11e6-85af-5814109c13fe.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18888531/0744b200-84f9-11e6-9a9b-a4c41e32a52f.png

**Comment by dreamnet** [comment]
For this one I think it's better to keep the "ILLINOIS".
