### ISSUE TITLE
Google Trips

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#8144]
**App Name:** Google Trips
**Bundle ID:** com.google.Trips
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1081561570">1081561570</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-trips/id1081561570?mt=8&uo=4">https://itunes.apple.com/us/app/google-trips/id1081561570?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/0a/94/64/0a9464a9-11a9-daee-3556-a10add79b5b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18970851/44503ad4-8693-11e6-9e09-6871bcc9e340.png)

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18886674/24170ab6-84f1-11e6-997f-7592edec4a61.png)
https://cloud.githubusercontent.com/assets/22012363/18886674/24170ab6-84f1-11e6-997f-7592edec4a61.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18886670/203fee3a-84f1-11e6-9615-6e558aab926f.png

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18886697/3aeceb34-84f1-11e6-9ce9-b0a5138e8254.png)
https://cloud.githubusercontent.com/assets/22012363/18886697/3aeceb34-84f1-11e6-9ce9-b0a5138e8254.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18886691/3664d446-84f1-11e6-808f-2880e66364fd.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18925615/f4d493bc-85b4-11e6-80d3-c8caed5e7c13.png)
https://cloud.githubusercontent.com/assets/20930745/18925615/f4d493bc-85b4-11e6-80d3-c8caed5e7c13.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18925631/06ddeb8a-85b5-11e6-8a4b-888159b686a4.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18970851/44503ad4-8693-11e6-9e09-6871bcc9e340.png)
https://cloud.githubusercontent.com/assets/2068130/18970851/44503ad4-8693-11e6-9e09-6871bcc9e340.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18970874/54f6c150-8693-11e6-91b1-a528136618c0.png
