### ISSUE TITLE
Rainews

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#8145]
**App Name:** Rainews
**Bundle ID:** it.rainet.rainews24
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=455029565">455029565</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rainews/id455029565?mt=8&uo=4">https://itunes.apple.com/us/app/rainews/id455029565?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** RAINET SpA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rai-net/id378456083?uo=4>© Rai Net</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/b6/30/9c/b6309c3e-d898-f29a-8add-2434fa216f80/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18887921/91e2a99c-84f6-11e6-8bf9-4b8db3b74032.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18887921/91e2a99c-84f6-11e6-8bf9-4b8db3b74032.png)
https://cloud.githubusercontent.com/assets/20930745/18887921/91e2a99c-84f6-11e6-8bf9-4b8db3b74032.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18887959/af78b762-84f6-11e6-8944-0887f4108833.png
