### ISSUE TITLE
Costco

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#8146]
**App Name:** Costco
**Bundle ID:** com.costco.costco
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=535509415">535509415</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/costco/id535509415?mt=8&uo=4">https://itunes.apple.com/us/app/costco/id535509415?mt=8&uo=4</a>
**App Version:** 2.13
**Seller:** Costco Wholesale Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/costco-wholesale-corporation/id535509418?uo=4>© Costco Wholesale Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/90/e8/bd/90e8bd89-5edf-0af9-391d-9565c0da6a47/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18925889/f45dee1e-85b5-11e6-9da5-d86a282f9731.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18886233/5d84790c-84ef-11e6-9b34-91eab34cda89.png)
https://cloud.githubusercontent.com/assets/20930745/18886233/5d84790c-84ef-11e6-9b34-91eab34cda89.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18886267/7c4ab838-84ef-11e6-886f-c29967828d36.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18925889/f45dee1e-85b5-11e6-9da5-d86a282f9731.png)
https://cloud.githubusercontent.com/assets/20930745/18925889/f45dee1e-85b5-11e6-9da5-d86a282f9731.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18925907/026fae5c-85b6-11e6-9518-802da22677b6.png

**Comment by LaCh0uine** [comment]
@2Qt2beStr8 i find look better only letter

**Comment by 2Qt2beStr8** [comment]
@LaCh0uine ... your issue  ... your decision :-)

**Comment by LaCh0uine** [comment]
@2Qt2beStr8 Not mine ;)
