### ISSUE TITLE
ooVoo – Free Video Call, Text and Voice

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#8147]
**App Name:** ooVoo – Free Video Call, Text and Voice
**Bundle ID:** com.oovoo.iphone.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=428845974">428845974</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/oovoo-free-video-call-text/id428845974?mt=8&uo=4">https://itunes.apple.com/us/app/oovoo-free-video-call-text/id428845974?mt=8&uo=4</a>
**App Version:** 2.9.3
**Seller:** oovoo LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/oovoo-llc/id422303841?uo=4>© ooVoo LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/d1/84/a2/d184a274-7bd2-8a8c-379d-0a2ff07a996a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18887666/4cfa91f6-84f5-11e6-871e-ee003e0f722d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18887666/4cfa91f6-84f5-11e6-871e-ee003e0f722d.png)
https://cloud.githubusercontent.com/assets/20930745/18887666/4cfa91f6-84f5-11e6-871e-ee003e0f722d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18887677/644478fe-84f5-11e6-9cb3-efd48ba2a05b.png
