### ISSUE TITLE
Binny's Mobile

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#8148]
**App Name:** Binny's Mobile
**Bundle ID:** com.binnys.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=759013884">759013884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/binnys-mobile/id759013884?mt=8&uo=4">https://itunes.apple.com/us/app/binnys-mobile/id759013884?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Gold Standard Enterprises, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/binnys/id759013887?uo=4>© Binny's</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/c6/bb/e3/c6bbe37f-b7c3-e18d-c506-49cf0cbf2f73/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18887314/d463a0d0-84f3-11e6-98a8-6f4140628922.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18887314/d463a0d0-84f3-11e6-98a8-6f4140628922.png)
https://cloud.githubusercontent.com/assets/20930745/18887314/d463a0d0-84f3-11e6-98a8-6f4140628922.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18887419/5459db06-84f4-11e6-9748-327dc942948c.png
