### ISSUE TITLE
Windfinder

### ISSUE THREAD

**Issue by Gyella1** [glasklart/hd#815]
**App Name:** Windfinder
**Bundle ID:** net.windfinder.windfinderapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=336829635">336829635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/windfinder/id336829635?mt=8&uo=4">https://itunes.apple.com/us/app/windfinder/id336829635?mt=8&uo=4</a>
**App Version:** 3.5.5
**Seller:** Windfinder.com
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/windfinder/id336829638?uo=4>© Windfinder</a>
**Supported Devices:** iPadFourthGen, iPadThirdGen, iPad2Wifi, iPhone5c, iPodTouchFifthGen, iPad23G, iPhone6, iPadFourthGen4G, iPadMini, iPhone6Plus, iPhone4, iPhone4S, iPhone5s, iPadThirdGen4G, iPodTouchSixthGen, iPhone5, iPadMini4G, iPhone-3GS, iPodTouchFourthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/pf/us/r30/Purple2/v4/df/c7/97/dfc79746-5e3f-ef1d-0a8c-bce45bec26be/mzl.yyobideg.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
Icon update:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9486174/eb8007dc-4bc3-11e5-9ddd-e1722bdadd7a.png)
https://cloud.githubusercontent.com/assets/2068130/9486174/eb8007dc-4bc3-11e5-9ddd-e1722bdadd7a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9486178/faf9f376-4bc3-11e5-8d01-738d108594ac.png
