### ISSUE TITLE
Live Scores & Sports Results SofaScore

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8150]
**App Name:** Live Scores & Sports Results SofaScore
**Bundle ID:** com.SofaScore.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=535471635">535471635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/live-scores-sports-results/id535471635?mt=8&uo=4">https://itunes.apple.com/us/app/live-scores-sports-results/id535471635?mt=8&uo=4</a>
**App Version:** 5.6.1
**Seller:** BAREAL LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bareal-ltd/id518091255?uo=4>© BAREAL LTD</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/d8/f6/ba/d8f6bae2-6aea-4de3-1b33-15ed1d745614/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18910143/fa0314be-8576-11e6-90be-324ba6bd95c7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18910143/fa0314be-8576-11e6-90be-324ba6bd95c7.png)
https://cloud.githubusercontent.com/assets/20930745/18910143/fa0314be-8576-11e6-90be-324ba6bd95c7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18910106/cc6b48d2-8576-11e6-8aae-f176a16b0d1d.png
