### ISSUE TITLE
JScore - Livescore

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8151]
**App Name:** JScore - Livescore
**Bundle ID:** com.ojground.jscore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598876628">598876628</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jscore-livescore/id598876628?mt=8&uo=4">https://itunes.apple.com/us/app/jscore-livescore/id598876628?mt=8&uo=4</a>
**App Version:** 2.7.16
**Seller:** BreezeValley Co., Ltd.,
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/breezevalley-co.-ltd./id518561866?uo=4>© BreezeValley Co., Ltd.,</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/76/52/08/76520879-d187-8c6d-cb54-9dfd3e676154/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18918838/54bad5b6-859c-11e6-8b48-073673373bbd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18918618/b170bde4-859b-11e6-98e2-5f8569bda91f.png)
https://cloud.githubusercontent.com/assets/20930745/18918618/b170bde4-859b-11e6-98e2-5f8569bda91f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18918644/c7076b44-859b-11e6-87f8-627b7db70f93.png
