### ISSUE TITLE
JODownloader

### ISSUE THREAD

**Issue by haen7** [glasklart/hd#8152]
**App Name:** JODownloader
 **Bundle ID:** com.ouraigua.jodownloader
 **Version:** 1.0.0
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 
![appicon60x60 3x](https://cloud.githubusercontent.com/assets/20773117/18908440/6e4131d0-857c-11e6-9842-f9de903caa3e.png)

 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18910879/438f52ca-857a-11e6-8849-97def15c1227.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18910879/438f52ca-857a-11e6-8849-97def15c1227.png)
https://cloud.githubusercontent.com/assets/20930745/18910879/438f52ca-857a-11e6-8849-97def15c1227.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18910895/502c4dd0-857a-11e6-81c8-70e6ac149d40.png
