### ISSUE TITLE
Micro Machines

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8153]
**App Name:** Micro Machines
**Bundle ID:** com.chillingo.micromachines
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1044286515">1044286515</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/micro-machines/id1044286515?mt=8&uo=4">https://itunes.apple.com/us/app/micro-machines/id1044286515?mt=8&uo=4</a>
**App Version:** 1.1.7
**Seller:** Chillingo Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chillingo-ltd/id286038741?uo=4>© Chillingo Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/43/d3/6f/43d36f63-b34d-7dd4-189e-699d35dec89d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18954070/8eb480fe-8651-11e6-84ea-b9f4bb37aa9c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18954070/8eb480fe-8651-11e6-84ea-b9f4bb37aa9c.png)
https://cloud.githubusercontent.com/assets/20930745/18954070/8eb480fe-8651-11e6-84ea-b9f4bb37aa9c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18954096/a5ddb1ec-8651-11e6-9044-474773d6d948.png

**Comment by LaCh0uine** [comment]
Good job 👍🏻
