### ISSUE TITLE
CSR Classics

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8154]
**App Name:** CSR Classics
**Bundle ID:** com.naturalmotion.csrclassics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598603610">598603610</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/csr-classics/id598603610?mt=8&uo=4">https://itunes.apple.com/us/app/csr-classics/id598603610?mt=8&uo=4</a>
**App Version:** 1.16.0
**Seller:** NaturalMotion Games Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/naturalmotion/id330281898?uo=4>© NaturalMotion</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple22/v4/1b/b7/81/1bb7818a-9be1-2143-3bb5-45724b1fca1a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18954309/abf42024-8652-11e6-83aa-4885148adf56.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18954309/abf42024-8652-11e6-83aa-4885148adf56.png)
https://cloud.githubusercontent.com/assets/20930745/18954309/abf42024-8652-11e6-83aa-4885148adf56.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18954328/c9d6856e-8652-11e6-9c15-fa56f11802e7.png

**Comment by LaCh0uine** [comment]
Good job 👍🏻👍🏻
