### ISSUE TITLE
Couche-Tard

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8155]
**App Name:** Couche-Tard
**Bundle ID:** com.couche-tard.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=663345373">663345373</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/couche-tard/id663345373?mt=8&uo=4">https://itunes.apple.com/us/app/couche-tard/id663345373?mt=8&uo=4</a>
**App Version:** 2.2.9
**Seller:** Alimentation Couche-Tard inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/couche-tard/id663345376?uo=4>© Couche-Tard</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/40/7d/80/407d8052-31ae-9dc1-ea9f-cc6089469fb5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18953403/9af853e8-864e-11e6-8816-d23cac9f4a09.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18931198/76b32f68-85cb-11e6-9db3-5091e88ebc30.png)
https://cloud.githubusercontent.com/assets/20930745/18931198/76b32f68-85cb-11e6-9db3-5091e88ebc30.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18931220/8701ccda-85cb-11e6-9ed7-200b36b088e2.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18931418/61787cba-85cc-11e6-8379-c118049653c3.png)
https://cloud.githubusercontent.com/assets/20930745/18931418/61787cba-85cc-11e6-8379-c118049653c3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18931431/6ed1ae86-85cc-11e6-8d82-da01412b139c.png

**Comment by LaCh0uine** [comment]
The second one 👍🏻 Thank you

**Comment by 2Qt2beStr8** [comment]
@LaCh0uine ... i think the outlines are too thin ... what do you think about this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18953403/9af853e8-864e-11e6-8816-d23cac9f4a09.png)
https://cloud.githubusercontent.com/assets/20930745/18953403/9af853e8-864e-11e6-8816-d23cac9f4a09.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18953414/ac35baa6-864e-11e6-8792-9f494d961060.png

**Comment by LaCh0uine** [comment]
Yeah better look like this 👍🏻 Thank you
