### ISSUE TITLE
Prisma: Free Photo Editor, Art Filters Pic Effects

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8156]
**App Name:** Prisma: Free Photo Editor, Art Filters Pic Effects
**Bundle ID:** com.prisma-ai.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1122649984">1122649984</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/prisma-free-photo-editor-art/id1122649984?mt=8&uo=4">https://itunes.apple.com/us/app/prisma-free-photo-editor-art/id1122649984?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Prisma labs, inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/prisma-labs-inc./id1122649983?uo=4>© Prisma labs, inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/3b/75/ea/3b75ea1e-9514-12b7-1fd2-60616815c8ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18930989/941edb02-85ca-11e6-9236-4acc47ac2bf8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18930989/941edb02-85ca-11e6-9236-4acc47ac2bf8.png)
https://cloud.githubusercontent.com/assets/20930745/18930989/941edb02-85ca-11e6-9236-4acc47ac2bf8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18931008/a4a65e0a-85ca-11e6-8653-8ac381785c54.png

**Comment by LaCh0uine** [comment]
Good job 👍🏻👍🏻
