### ISSUE TITLE
Kitchen Stories Recipes

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8157]
**App Name:** Kitchen Stories Recipes
**Bundle ID:** com.AJNSNewMedia.KitchenStories
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=771068291">771068291</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/kitchen-stories-recipes/id771068291?uo=4">https://apps.apple.com/us/app/kitchen-stories-recipes/id771068291?uo=4</a>
**App Version:** 14.1
**Seller:** AJNS New Media GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ajns-new-media/id771068294?uo=4">© AJNS New Media</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/84/7e/c5/847ec5af-b08b-13d5-25a9-3232324f5947/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65357192-a64cce80-dbf6-11e9-8347-018dad9f8ddf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18946446/2d06dc20-862f-11e6-9da9-43186e5c1f5d.png)
https://cloud.githubusercontent.com/assets/20930745/18946446/2d06dc20-862f-11e6-9da9-43186e5c1f5d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18946460/3b6b3842-862f-11e6-8c51-02eeea0facee.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Kitchen Stories - recipes, baking, healthy cooking
**Bundle ID:** com.AJNSNewMedia.KitchenStories
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=771068291">771068291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kitchen-stories-recipes-baking/id771068291?mt=8&uo=4">https://itunes.apple.com/us/app/kitchen-stories-recipes-baking/id771068291?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** AJNS New Media GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ajns-new-media/id771068294?uo=4">© AJNS New Media</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple82/v4/09/1f/d8/091fd880-32e1-0e35-6658-0fe04db6b84a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285345/0967af16-c436-11e6-9072-2897eb07f4eb.png)
https://cloud.githubusercontent.com/assets/20930745/21285345/0967af16-c436-11e6-9072-2897eb07f4eb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21285348/172b0d5a-c436-11e6-955c-5ee161a51771.png

**Comment by l8er4now** [comment]
Needs an update

**App Name:** Kitchen Stories Recipes
**Bundle ID:** com.AJNSNewMedia.KitchenStories
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=771068291">771068291</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/kitchen-stories-recipes/id771068291?uo=4">https://apps.apple.com/us/app/kitchen-stories-recipes/id771068291?uo=4</a>
**App Version:** 14.1
**Seller:** AJNS New Media GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ajns-new-media/id771068294?uo=4">© AJNS New Media</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/84/7e/c5/847ec5af-b08b-13d5-25a9-3232324f5947/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65357192-a64cce80-dbf6-11e9-8347-018dad9f8ddf.png)
https://user-images.githubusercontent.com/2068130/65357192-a64cce80-dbf6-11e9-8347-018dad9f8ddf.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65357213-b5cc1780-dbf6-11e9-81ff-397ee84a885c.png
