### ISSUE TITLE
Cut the Rope Original™

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8158]
**App Name:** Cut the Rope Original™
**Bundle ID:** com.chillingo.cuttherope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=380293530">380293530</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/app/id380293530">https://itunes.apple.com/app/id380293530</a>
**App Version:** 2.6
**Seller:** <a href="http://www.chillingo.com/">Chillingo Ltd</a>
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chillingo-ltd/id286038741?uo=4>© Chillingo Ltd</a>
**Supported Devices:** iPhone®, iPhone 3G®, iPhone4S®, iPhone5®, iPhone5c®, iPhone5s®, iPhone6®, iPhone6Plus®, iPod-touch®, iPod-touch-with-mic®, iPodTouchFifthGen®, iPodTouchSixthGen®, iPodTouchThirdGen®, iPad23G®, iPad2Wifi®, iPad3G®, iPadFourthGen®, iPadFourthGen4G®, iPadThirdGen®, iPadThirdGen4G®, iPadWifi®, iPadMini™, iPadMini4G™
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/18969026/b265e30a-868b-11e6-8aee-b35a8d4f37ad.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18969070/e233b2e2-868b-11e6-813b-450fb0c412ed.png)

**Comment by dreamnet** [comment]
Refers to #7597. Icon by @ivanov007.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18969070/e233b2e2-868b-11e6-813b-450fb0c412ed.png)
https://cloud.githubusercontent.com/assets/2068130/18969070/e233b2e2-868b-11e6-813b-450fb0c412ed.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18969084/f6950178-868b-11e6-9acb-225597ba3a04.png

**Comment by LaCh0uine** [comment]
Thank You :)
