### ISSUE TITLE
WindAlert

### ISSUE THREAD

**Issue by Gyella1** [glasklart/hd#816]
**App Name:** WindAlert
**Bundle ID:** com.weatherflow.windalert
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=317992025">317992025</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/windalert/id317992025?mt=8&uo=4">https://itunes.apple.com/us/app/windalert/id317992025?mt=8&uo=4</a>
**App Version:** 2.82
**Seller:** WeatherFlow
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/weatherflow/id317992028?uo=4>© WeatherFlow</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/be/89/5e/be895e06-21d7-8f3f-7446-fee327585dfe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410032/f74af610-92e1-11e6-8731-4de0d05be21c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410032/f74af610-92e1-11e6-8731-4de0d05be21c.png)
https://cloud.githubusercontent.com/assets/20930745/19410032/f74af610-92e1-11e6-8731-4de0d05be21c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19410035/03f77938-92e2-11e6-9d87-c367fff066a5.png
