### ISSUE TITLE
"klocki"

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8160]
**App Name:** "klocki"
**Bundle ID:** com.klockigame.klocki
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1105390093">1105390093</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/klocki/id1105390093?mt=8&uo=4">https://itunes.apple.com/us/app/klocki/id1105390093?mt=8&uo=4</a>
**App Version:** 1.01
**Seller:** Maciej Targoni
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/maciej-targoni/id495165602?uo=4>© Maciej Targoni</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/b0/0b/88/b00b88d7-8933-b104-3372-0d0c29b4e949/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19002129/e0e32fde-874a-11e6-8a70-c92148460e51.png)

**Comment by 2Qt2beStr8** [comment]
@dreamnet  ... can you pls take a look ... i am not sure how to create this icon ... this is only a dirty sketch 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18985388/ec74d5c6-86f7-11e6-88df-85d8c703948f.png)
https://cloud.githubusercontent.com/assets/20930745/18985388/ec74d5c6-86f7-11e6-88df-85d8c703948f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18985404/fcd43614-86f7-11e6-8b4c-bc9955e0a7a1.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... yes, looks nice .... very clean .. i like it
