### ISSUE TITLE
kabel eins Doku – Kostenloses Live TV, Mediathek

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8161]
**App Name:** kabel eins Doku – Kostenloses Live TV, Mediathek
**Bundle ID:** de.prosiebensat1digital.kabeleinsdoku
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1123553225">1123553225</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/kabel-eins-doku-kostenloses/id1123553225?mt=8&uo=4">https://itunes.apple.com/de/app/kabel-eins-doku-kostenloses/id1123553225?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** ProSiebenSat.1 Digital GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/de/developer/prosiebensat.1-digital-gmbh/id293225283?uo=4>© ProSiebenSat.1 Digital GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/0b/08/9f/0b089fc3-93d7-e22c-d30c-7717d50bd5bb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18972329/027b0318-8699-11e6-9d9b-a444a812a265.png)

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18972329/027b0318-8699-11e6-9d9b-a444a812a265.png)
https://cloud.githubusercontent.com/assets/22012363/18972329/027b0318-8699-11e6-9d9b-a444a812a265.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18972328/02655e0a-8699-11e6-88bd-d73e93b6a9ca.png
