### ISSUE TITLE
Angry Birds

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8162]
**App Name:** Angry Birds
**Bundle ID:** com.clickgamer.AngryBirds
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=343200656">343200656</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds/id343200656?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds/id343200656?mt=8&uo=4</a>
**App Version:** 6.1.5
**Seller:** Rovio Entertainment Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rovio-entertainment-ltd/id298910979?uo=4>© Rovio Entertainment Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/6e/2e/c3/6e2ec311-a3b4-7986-a8be-527cac341802/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18985978/06187c64-86fb-11e6-835d-4e8b99a1b963.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18982566/73f84322-86e7-11e6-9712-961f8026b2ef.png)
https://cloud.githubusercontent.com/assets/20930745/18982566/73f84322-86e7-11e6-9712-961f8026b2ef.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18982582/87220154-86e7-11e6-841e-f8a611f03675.png
