### ISSUE TITLE
BallHawk: Fantasy Football Companion

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8163]
**App Name:** BallHawk: Fantasy Football Companion
**Bundle ID:** com.enjoywatermelon.BallHawk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1122904015">1122904015</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ballhawk-fantasy-football/id1122904015?mt=8&uo=4">https://itunes.apple.com/us/app/ballhawk-fantasy-football/id1122904015?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Watermelon, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/watermelon-llc/id1122904014?uo=4>© Watermelon, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/df/2f/f6/df2ff649-a312-594a-85f4-ce06435f9190/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18998158/ae6c61d2-8737-11e6-9b9d-1e82cf4ed268.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18998158/ae6c61d2-8737-11e6-9b9d-1e82cf4ed268.png)
https://cloud.githubusercontent.com/assets/20930745/18998158/ae6c61d2-8737-11e6-9b9d-1e82cf4ed268.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18998176/c3649a32-8737-11e6-87e5-35d5672a0f04.png
