### ISSUE TITLE
Crisp Weather Widget

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8164]
**App Name:** Crisp Weather Widget
**Bundle ID:** com.nickvdp.CrispWeather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=984948957">984948957</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/crisp-weather-widget/id984948957?mt=8&uo=4">https://itunes.apple.com/us/app/crisp-weather-widget/id984948957?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Nicholas van der Ploeg
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nicholas-van-der-ploeg/id320474461?uo=4>© Nicholas van der Ploeg</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/cc/97/12/cc971254-ba38-c9fa-b9b5-f1a868cbcfc2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18997948/e2b33732-8736-11e6-8b72-622a7f7de23f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18997948/e2b33732-8736-11e6-8b72-622a7f7de23f.png)
https://cloud.githubusercontent.com/assets/20930745/18997948/e2b33732-8736-11e6-8b72-622a7f7de23f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18997956/edb7a1ea-8736-11e6-9f46-438c395cf4e0.png
