### ISSUE TITLE
Boulder Valley School District

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8165]
**App Name:** Boulder Valley School District
**Bundle ID:** com.relianceco.cma.bouldervalley
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=980295092">980295092</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boulder-valley-school-district/id980295092?mt=8&uo=4">https://itunes.apple.com/us/app/boulder-valley-school-district/id980295092?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Reliance Communications, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/custom-school-apps/id592390683?uo=4>© Custom School Apps</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/27/52/33/27523341-08d6-03c9-4e20-31522ed79b9a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015019/1628b766-87fc-11e6-9a61-9df2946c8b95.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19014996/97768c9a-87fb-11e6-9780-e3a9c6d61fa2.png)
https://cloud.githubusercontent.com/assets/20930745/19014996/97768c9a-87fb-11e6-9780-e3a9c6d61fa2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19014998/a43e2e92-87fb-11e6-8684-bbc9e221191a.png
