### ISSUE TITLE
SeatGeek – Tickets to Sports, Concerts & Broadway

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8166]
**App Name:** SeatGeek – Tickets to Sports, Concerts & Broadway
**Bundle ID:** com.seatgeek.SeatGeek
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=582790430">582790430</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/seatgeek-tickets-to-sports/id582790430?mt=8&uo=4">https://itunes.apple.com/us/app/seatgeek-tickets-to-sports/id582790430?mt=8&uo=4</a>
**App Version:** 3.9.0
**Seller:** SeatGeek, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/seatgeek/id582790433?uo=4>© SeatGeek</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/f9/f2/b4/f9f2b475-430f-ae3d-364f-32664269b327/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015262/260c6c22-8801-11e6-8948-7ce995c47fa9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015262/260c6c22-8801-11e6-8948-7ce995c47fa9.png)
https://cloud.githubusercontent.com/assets/20930745/19015262/260c6c22-8801-11e6-8948-7ce995c47fa9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19015264/32ff4918-8801-11e6-9683-2a8a773df93e.png
