### ISSUE TITLE
StubHub - Sports, Concert & Theatre Tickets

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8167]
**App Name:** StubHub - Sports, Concert & Theatre Tickets
**Bundle ID:** com.stubhub.stubhub
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=366562751">366562751</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stubhub-sports-concert-theatre/id366562751?mt=8&uo=4">https://itunes.apple.com/us/app/stubhub-sports-concert-theatre/id366562751?mt=8&uo=4</a>
**App Version:** 6.2.0
**Seller:** Stubhub, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/stubhub-inc./id366562754?uo=4>© StubHub Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/f5/0f/ab/f50fabbf-2ae5-8351-062a-50da48b61a6d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015208/68180c76-8800-11e6-84d2-390abd7beac3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015208/68180c76-8800-11e6-84d2-390abd7beac3.png)
https://cloud.githubusercontent.com/assets/20930745/19015208/68180c76-8800-11e6-84d2-390abd7beac3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19015210/76cc93ea-8800-11e6-89fb-fe1c382fbd1b.png
