### ISSUE TITLE
Flash Seats

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8168]
**App Name:** Flash Seats
**Bundle ID:** com.flashseats.v2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=679164752">679164752</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flash-seats/id679164752?mt=8&uo=4">https://itunes.apple.com/us/app/flash-seats/id679164752?mt=8&uo=4</a>
**App Version:** 1.9.50
**Seller:** Flash Seats, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/veritix/id679164755?uo=4>© Veritix</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/ef/cd/4f/efcd4fa0-810d-7913-6f3c-9a36ce6f6894/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015141/b50aa0c2-87fe-11e6-965d-0a224cc504c4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015141/b50aa0c2-87fe-11e6-965d-0a224cc504c4.png)
https://cloud.githubusercontent.com/assets/20930745/19015141/b50aa0c2-87fe-11e6-965d-0a224cc504c4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19015144/ce557ef8-87fe-11e6-8d51-fd580049336b.png
