### ISSUE TITLE
OrderAhead

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8169]
**App Name:** OrderAhead
**Bundle ID:** com.kineticfarm.orderahead
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=464652978">464652978</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/orderahead/id464652978?mt=8&uo=4">https://itunes.apple.com/us/app/orderahead/id464652978?mt=8&uo=4</a>
**App Version:** 1.11.6
**Seller:** Kinetic Farm, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kinetic-farm-inc./id464652981?uo=4>© Kinetic Farm, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple41/v4/54/a6/81/54a681a2-2a00-88b6-6d82-7d651ab4e45d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015175/9c41761e-87ff-11e6-80bc-3ceb040418c6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015175/9c41761e-87ff-11e6-80bc-3ceb040418c6.png)
https://cloud.githubusercontent.com/assets/20930745/19015175/9c41761e-87ff-11e6-80bc-3ceb040418c6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19015178/ac45789e-87ff-11e6-8d8c-0999c4b9684f.png
