### ISSUE TITLE
BancFirst Mobile

### ISSUE THREAD

**Issue by Gyella1** [glasklart/hd#817]
**App Name:** BancFirst Mobile
**Bundle ID:** com.intuit.mobilebanking05362
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489601445">489601445</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bancfirst-mobile/id489601445?mt=8&uo=4">https://itunes.apple.com/us/app/bancfirst-mobile/id489601445?mt=8&uo=4</a>
**App Version:** 5.2.5
**Seller:** BancFirst Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bancfirst-corporation/id489601448?uo=4>© BancFirst Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple18/v4/67/da/ae/67daae36-3b18-d4cb-abea-ed8bd861e8ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418105/7221c9b4-93bd-11e6-9975-2a9a415ea52e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19418105/7221c9b4-93bd-11e6-9975-2a9a415ea52e.png)
https://cloud.githubusercontent.com/assets/20930745/19418105/7221c9b4-93bd-11e6-9975-2a9a415ea52e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19418108/9ccaed9e-93bd-11e6-8a97-b249852750aa.png
