### ISSUE TITLE
iSeismometer

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8170]
**App Name:** iSeismometer
**Bundle ID:** com.objectgraph.iSeismometer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=304190739">304190739</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iseismometer/id304190739?mt=8&uo=4">https://itunes.apple.com/us/app/iseismometer/id304190739?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** ObjectGraph LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/objectgraph-llc/id284700705?uo=4>© ObjectGraph LLC</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/c8/8b/09/c88b096e-549a-6e79-7fae-852a58ed53c7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19019279/5096a724-8882-11e6-96a7-e5eaa4ae4450.png)
https://cloud.githubusercontent.com/assets/2068130/19019279/5096a724-8882-11e6-96a7-e5eaa4ae4450.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19019281/6182c964-8882-11e6-98d0-f7aff54e3631.png
