### ISSUE TITLE
AT&T Passport℠

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8171]
**App Name:** AT&T Passport℠
**Bundle ID:** com.att.AccuRoam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=552594442">552594442</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/at-t-passportsm/id552594442?mt=8&uo=4">https://itunes.apple.com/us/app/at-t-passportsm/id552594442?mt=8&uo=4</a>
**App Version:** 5.1.84
**Seller:** AT&T Services, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/at-t-services-inc./id290854684?uo=4>© AT&T Services, Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/5b/f9/a3/5bf9a38e-197c-a5fa-adb5-b264b58d134c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015468/2c5fa374-8805-11e6-8e98-df01cd9ed1cf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015468/2c5fa374-8805-11e6-8e98-df01cd9ed1cf.png)
https://cloud.githubusercontent.com/assets/20930745/19015468/2c5fa374-8805-11e6-8e98-df01cd9ed1cf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19015480/54908cdc-8805-11e6-9ec1-7e52cbc51e11.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015541/df564996-8806-11e6-8ad3-916dad873d15.png)
https://cloud.githubusercontent.com/assets/20930745/19015541/df564996-8806-11e6-8ad3-916dad873d15.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19015553/129f9820-8807-11e6-9534-10b2ab24874a.png
