### ISSUE TITLE
Univision Deportes: Liga MX, MLS, Fútbol En Vivo

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8172]
**App Name:** Univision Deportes: Liga MX, MLS, Fútbol En Vivo
**Bundle ID:** com.Univision.Futbol
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=353665650">353665650</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/univision-deportes-liga-mx/id353665650?mt=8&uo=4">https://itunes.apple.com/us/app/univision-deportes-liga-mx/id353665650?mt=8&uo=4</a>
**App Version:** 5.2.7
**Seller:** Univision
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/univision-interactive-media/id353665653?uo=4>© Univision Interactive Media, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/08/da/83/08da83c8-e7d3-1494-5d28-467f024866ff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015310/6445a4c6-8802-11e6-88fd-8eb0631544d3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015310/6445a4c6-8802-11e6-88fd-8eb0631544d3.png)
https://cloud.githubusercontent.com/assets/20930745/19015310/6445a4c6-8802-11e6-88fd-8eb0631544d3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19015318/7311dae2-8802-11e6-95bb-f2a0620380af.png

**Comment by ivanov007** [comment]
@Sly-Fi does this app really works?

**Comment by Sly-Fi** [comment]
@ivanov007 ¡Si señor, funciona muy bien!
