### ISSUE TITLE
Net Status - remote server monitor

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8173]
**App Name:** Net Status - remote server monitor
**Bundle ID:** com.paully.netstatus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=325166405">325166405</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/net-status-remote-server-monitor/id325166405?mt=8&uo=4">https://itunes.apple.com/us/app/net-status-remote-server-monitor/id325166405?mt=8&uo=4</a>
**App Version:** 1.9.13
**Seller:** Pavel Ahafonau
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pavel-ahafonau/id319585607?uo=4>© Pavel Ahafonau</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/44/c9/34/44c934dd-11bf-2b35-ad11-ebe0e4832b47/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015339/f09abe3e-8802-11e6-8ce7-9aa94c791d65.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19015339/f09abe3e-8802-11e6-8ce7-9aa94c791d65.png)
https://cloud.githubusercontent.com/assets/20930745/19015339/f09abe3e-8802-11e6-8ce7-9aa94c791d65.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19015345/00276a96-8803-11e6-978a-663cc2a9a87d.png
