### ISSUE TITLE
Flyover Country

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8174]
**App Name:** Flyover Country
**Bundle ID:** com.ionicframework.app303739
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1059886913">1059886913</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flyover-country/id1059886913?mt=8&uo=4">https://itunes.apple.com/us/app/flyover-country/id1059886913?mt=8&uo=4</a>
**App Version:** 0.4.0
**Seller:** Regents of the University of Minnesota
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/regents-university-minnesota/id455216626?uo=4>© Regents of the University of Minnesota</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/c2/04/3a/c2043ac1-9b47-b51a-b91e-1406c6dac92e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19021974/cb0506c2-88cd-11e6-82a6-9d2c2befd6b6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19021888/b5ab2664-88cb-11e6-9bcd-f62068ee89a4.png)
https://cloud.githubusercontent.com/assets/20930745/19021888/b5ab2664-88cb-11e6-9bcd-f62068ee89a4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19021892/c3aa1842-88cb-11e6-904c-ddf479a0ab3b.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19021974/cb0506c2-88cd-11e6-82a6-9d2c2befd6b6.png)
https://cloud.githubusercontent.com/assets/20930745/19021974/cb0506c2-88cd-11e6-82a6-9d2c2befd6b6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19021977/def02694-88cd-11e6-80e6-6e4c485af3cb.png
