### ISSUE TITLE
Seat Alerts - Airplane Seat Monitoring and Alerting

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8175]
**App Name:** Seat Alerts - Airplane Seat Monitoring and Alerting
**Bundle ID:** com.expertflyer.seatalerts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=533533342">533533342</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/seat-alerts-airplane-seat/id533533342?mt=8&uo=4">https://itunes.apple.com/us/app/seat-alerts-airplane-seat/id533533342?mt=8&uo=4</a>
**App Version:** 1.91.25
**Seller:** Expert Travel Services, LLC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/expertflyer.com/id533533345?uo=4>© ExpertFlyer.com</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/a6/11/88/a61188a5-4274-23e2-92d2-77d0e373403c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/19039250/cd90ab22-8944-11e6-8193-f0e172ce7916.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19022046/36f52c26-88cf-11e6-8fd0-9f564e27e685.png)
https://cloud.githubusercontent.com/assets/20930745/19022046/36f52c26-88cf-11e6-8fd0-9f564e27e685.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19022053/47e39676-88cf-11e6-8969-9f603d571a5a.png

**Comment by 2Qt2beStr8** [comment]
... or very clean

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19022082/c8053f8a-88cf-11e6-9010-34ede9e6e91c.png)
https://cloud.githubusercontent.com/assets/20930745/19022082/c8053f8a-88cf-11e6-9010-34ede9e6e91c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19022087/d4a9b73e-88cf-11e6-8e79-a8aea269bc4d.png

**Comment by dreamnet** [comment]
Hm... @Sly-Fi What do you prefer?

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/19039250/cd90ab22-8944-11e6-8193-f0e172ce7916.png)
https://cloud.githubusercontent.com/assets/3090247/19039250/cd90ab22-8944-11e6-8193-f0e172ce7916.png
___
Source:
https://cloud.githubusercontent.com/assets/3090247/19039251/cd960e78-8944-11e6-9b4b-9ef319fb53d8.png
