### ISSUE TITLE
My Flights

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8176]
**App Name:** My Flights
**Bundle ID:** com.schofs.myflights
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327067451">327067451</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-flights/id327067451?mt=8&uo=4">https://itunes.apple.com/us/app/my-flights/id327067451?mt=8&uo=4</a>
**App Version:** 3.1.13
**Seller:** Chris Schofield
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/chris-schofield/id327067454?uo=4>© Chris Schofield</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/1b/70/9c/1b709c12-ee36-da69-db5c-34100c12cf0f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19021847/a2499d4a-88ca-11e6-9d6e-52e8859fd5d7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19021847/a2499d4a-88ca-11e6-9d6e-52e8859fd5d7.png)
https://cloud.githubusercontent.com/assets/2068130/19021847/a2499d4a-88ca-11e6-9d6e-52e8859fd5d7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19021855/b36de388-88ca-11e6-885d-05f43b62725f.png
