### ISSUE TITLE
eTown

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8177]
**App Name:** eTown
**Bundle ID:** com.ragedigital.eTown
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=562166247">562166247</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/etown/id562166247?mt=8&uo=4">https://itunes.apple.com/us/app/etown/id562166247?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Rage Digital Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rage-digital-inc./id325209725?uo=4>© Rage Digital Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/a0/de/60/a0de6033-a27d-23ab-126b-4c40d095b8a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19022620/7f03f83c-88dc-11e6-90a1-e4d39a222c3f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19022620/7f03f83c-88dc-11e6-90a1-e4d39a222c3f.png)
https://cloud.githubusercontent.com/assets/2068130/19022620/7f03f83c-88dc-11e6-90a1-e4d39a222c3f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19022625/8cdc5904-88dc-11e6-8eb7-0d2cc7b4ee35.png
