### ISSUE TITLE
Sensor Play - Accelerometer and Gyroscope data recorder.

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8178]
**App Name:** Sensor Play - Accelerometer and Gyroscope data recorder.
**Bundle ID:** com.philipbroder.Senso
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=921385514">921385514</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sensor-play-accelerometer/id921385514?mt=8&uo=4">https://itunes.apple.com/us/app/sensor-play-accelerometer/id921385514?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Philip Broder
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/philip-broder/id921385513?uo=4>© Philip Broder</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/74/03/c7/7403c7da-0033-0e5a-b6d6-7e11ed8a2ab0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19085602/28470fda-8a6b-11e6-9cd7-28ccfb0569fb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19023251/29734d9c-88ea-11e6-928b-7d7cdd0db30a.png)
https://cloud.githubusercontent.com/assets/20930745/19023251/29734d9c-88ea-11e6-928b-7d7cdd0db30a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19023254/3789eada-88ea-11e6-9ab1-12d1d84f02b3.png

**Comment by dreamnet** [comment]
Small corrections and a bit bolder text.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19085602/28470fda-8a6b-11e6-9cd7-28ccfb0569fb.png)
https://cloud.githubusercontent.com/assets/2068130/19085602/28470fda-8a6b-11e6-9cd7-28ccfb0569fb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19085614/376285f8-8a6b-11e6-9069-28dd5bcde9e9.png
