### ISSUE TITLE
Photo Editor by Aviary

### ISSUE THREAD

**Issue by thatsoaustin** [glasklart/hd#818]
**App Name:** Photo Editor by Aviary
**Bundle ID:** com.aviary.Photo-Editor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527445936">527445936</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photo-editor-by-aviary/id527445936?mt=8&uo=4">https://itunes.apple.com/us/app/photo-editor-by-aviary/id527445936?mt=8&uo=4</a>
**App Version:** 4.2.0
**Seller:** Aviary, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/aviary/id457044869?uo=4>© Aviary</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/82/a3/63/82a36336-c3a7-a823-c40d-989023c39d7f/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17402067/cf49fec6-5a16-11e6-8e49-8117fecdf5c3.png)

**Comment by Anuskuss** [comment]
Needs little update.

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/17402067/cf49fec6-5a16-11e6-8e49-8117fecdf5c3.png)
https://cloud.githubusercontent.com/assets/3090247/17402067/cf49fec6-5a16-11e6-8e49-8117fecdf5c3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/17402068/cf4d9e8c-5a16-11e6-8cc5-2292886fffb4.png
