### ISSUE TITLE
Curse

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8180]
**App Name:** Curse
**Bundle ID:** com.curse.highwind
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935720218">935720218</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/curse/id935720218?mt=8&uo=4">https://itunes.apple.com/us/app/curse/id935720218?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Curse, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/curse-inc./id935720217?uo=4>© Curse, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/32/bb/a8/32bba8d6-1c9b-1c63-5408-76caf4f940f2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19082802/fa0b876e-8a5f-11e6-9d56-b836e1abb8c0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19032705/adf4dfec-895b-11e6-9da1-cb81d9408a28.png)
https://cloud.githubusercontent.com/assets/20930745/19032705/adf4dfec-895b-11e6-9da1-cb81d9408a28.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19032716/ba80659c-895b-11e6-8f33-146a0c04e96c.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19032810/24b1fc82-895c-11e6-8bf2-b6630f5a6048.png)
https://cloud.githubusercontent.com/assets/20930745/19032810/24b1fc82-895c-11e6-8bf2-b6630f5a6048.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19032824/335c5ba6-895c-11e6-9d35-1f558c85f6fd.png

**Comment by dreamnet** [comment]
Did some small corrections.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19082802/fa0b876e-8a5f-11e6-9d56-b836e1abb8c0.png)
https://cloud.githubusercontent.com/assets/2068130/19082802/fa0b876e-8a5f-11e6-9d56-b836e1abb8c0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19082825/0a5c49be-8a60-11e6-8482-0b0f12919719.png
