### ISSUE TITLE
Next  – Fashion shopping for Women, Men, Girls, Boys, Home and Label

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8181]
**App Name:** Next  – Fashion shopping for Women, Men, Girls, Boys, Home and Label
**Bundle ID:** uk.co.next.v1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348364305">348364305</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/next-fashion-shopping-for/id348364305?mt=8&uo=4">https://itunes.apple.com/us/app/next-fashion-shopping-for/id348364305?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** Next Retail Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/next-retail-limited/id348364308?uo=4>© Next Retail Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/7e/2e/0f/7e2e0faa-c512-35c1-fc96-3447d6e798f7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19081103/6ebd4aa4-8a59-11e6-9783-9d3d3fb2e154.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19064992/40d6e138-8a11-11e6-9275-24335882a71f.png)
https://cloud.githubusercontent.com/assets/20930745/19064992/40d6e138-8a11-11e6-9275-24335882a71f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19065006/51145b20-8a11-11e6-9bf8-15a493a96807.png

**Comment by 2Qt2beStr8** [comment]
... or inverted

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19065241/b9028986-8a12-11e6-8ef0-f4f77c901718.png)
https://cloud.githubusercontent.com/assets/20930745/19065241/b9028986-8a12-11e6-8ef0-f4f77c901718.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19065255/ca61ae14-8a12-11e6-92fe-0da1d9e4b59e.png

**Comment by dreamnet** [comment]
First one is OK, just made the text a bit bolder:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19081103/6ebd4aa4-8a59-11e6-9783-9d3d3fb2e154.png)
https://cloud.githubusercontent.com/assets/2068130/19081103/6ebd4aa4-8a59-11e6-9783-9d3d3fb2e154.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19081142/8abca948-8a59-11e6-9178-55b5c43bd523.png
