### ISSUE TITLE
AccorHotels: hotel booking in over 95 countries

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8182]
**App Name:** AccorHotels: hotel booking in over 95 countries
**Bundle ID:** fr.accor.push
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=489472613">489472613</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/accorhotels-hotel-booking/id489472613?mt=8&uo=4">https://itunes.apple.com/us/app/accorhotels-hotel-booking/id489472613?mt=8&uo=4</a>
**App Version:** 8.9.1
**Seller:** ACCOR
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/accor/id489472616?uo=4>© ACCOR</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple42/v4/e8/b0/f2/e8b0f22e-240e-058e-46a7-22fc201581ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19064910/b3497c86-8a10-11e6-9e91-ee53f4d9b216.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19064910/b3497c86-8a10-11e6-9e91-ee53f4d9b216.png)
https://cloud.githubusercontent.com/assets/20930745/19064910/b3497c86-8a10-11e6-9e91-ee53f4d9b216.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19064921/c11d0878-8a10-11e6-9ec5-e936b9026a82.png
