### ISSUE TITLE
Ice Lakes

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8183]
**App Name:** Ice Lakes
**Bundle ID:** com.iceflakestudios.icelakes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916685607">916685607</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ice-lakes/id916685607?mt=8&uo=4">https://itunes.apple.com/us/app/ice-lakes/id916685607?mt=8&uo=4</a>
**App Version:** 1.53.1
**Seller:** Iceflake Studios Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iceflake-studios/id586020555?uo=4>© Iceflake Studios</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/c5/bb/1a/c5bb1a12-0b11-63db-f450-a19a022acf59/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19115557/be60b88e-8b12-11e6-8101-b94cb54b413a.png)

**Comment by 2Qt2beStr8** [comment]
not really perfect :-( ... this icon is to realistic for me

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19115557/be60b88e-8b12-11e6-8101-b94cb54b413a.png)
https://cloud.githubusercontent.com/assets/20930745/19115557/be60b88e-8b12-11e6-8101-b94cb54b413a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19115586/dc913090-8b12-11e6-828b-98eba89ceb18.png

**Comment by ivanov007** [comment]
wow I think it's perfect :+1:
