### ISSUE TITLE
Motorsport Manager

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8184]
**App Name:** Motorsport Manager
**Bundle ID:** com.game.motorsportmanager
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=776865453">776865453</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/motorsport-manager/id776865453?mt=8&uo=4">https://itunes.apple.com/us/app/motorsport-manager/id776865453?mt=8&uo=4</a>
**App Version:** 1.1.5
**Seller:** Christian West
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/christian-west/id690401307?uo=4>© Christian West</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/fd/44/0a/fd440a6c-191d-4f29-4115-e5a8d59530d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19107985/0b47e790-8aef-11e6-845b-cbb97c60b4ae.png)

**Comment by dreamnet** [comment]
Not the original, but...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19107985/0b47e790-8aef-11e6-845b-cbb97c60b4ae.png)
https://cloud.githubusercontent.com/assets/2068130/19107985/0b47e790-8aef-11e6-845b-cbb97c60b4ae.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19107992/1753141a-8aef-11e6-8c6e-02a7a5f451ab.png
