### ISSUE TITLE
iClarified

### ISSUE THREAD

**Issue by haen7** [glasklart/hd#8185]
**App Name:** iClarified
**Bundle ID:** com.iclarified.iclarified
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388040325">388040325</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iclarified/id388040325?mt=8&uo=4">https://itunes.apple.com/us/app/iclarified/id388040325?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Shalom Levytam
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iclarified/id388040328?uo=4>© iClarified</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple3/v4/9e/9e/c3/9e9ec3af-d26b-d71e-d9f0-5015734408c1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19087759/9081f30a-8a73-11e6-8870-7ff726ec437f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19087759/9081f30a-8a73-11e6-8870-7ff726ec437f.png)
https://cloud.githubusercontent.com/assets/20930745/19087759/9081f30a-8a73-11e6-8870-7ff726ec437f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19087771/9a2817b8-8a73-11e6-9cf7-cfc54f7e08f4.png
