### ISSUE TITLE
Skylanders Battlecast

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8186]
**App Name:** Skylanders Battlecast
**Bundle ID:** com.activision.skylanders.battlecast.sl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1051927783">1051927783</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skylanders-battlecast/id1051927783?mt=8&uo=4">https://itunes.apple.com/us/app/skylanders-battlecast/id1051927783?mt=8&uo=4</a>
**App Version:** 1.4.3613
**Seller:** Activision Publishing, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/activision-publishing-inc./id285005466?mt=8&uo=4>© Activision Publishing, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple19/v4/2c/35/d8/2c35d877-2957-97c7-fef2-bdd45e12fb2a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19210680/3ba6fa10-8d2a-11e6-95bc-4554c6891f52.png)

**Comment by ivanov007** [comment]
This is the actual springboard icon:
![image](https://cloud.githubusercontent.com/assets/3090247/19089317/5e20427e-8a3f-11e6-97c1-68c7f70398ce.png)

**Comment by dreamnet** [comment]
That's hard. I only can do the logo...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19210680/3ba6fa10-8d2a-11e6-95bc-4554c6891f52.png)
https://cloud.githubusercontent.com/assets/2068130/19210680/3ba6fa10-8d2a-11e6-95bc-4554c6891f52.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19210681/4ccae96e-8d2a-11e6-8f6d-74a5f7d55dfd.png
