### ISSUE TITLE
File Manager Plus

### ISSUE THREAD

**Issue by BrokenCommander** [glasklart/hd#8187]
**App Name:** File Manager Plus
**Bundle ID:** com.appisan.filerepo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1072729245">1072729245</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/file-manager-plus/id1072729245?mt=8&uo=4">https://itunes.apple.com/us/app/file-manager-plus/id1072729245?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Sin Yee Fan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sin-yee-fan/id1072729244?uo=4>© Sin Yee Fan</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/f6/0b/ad/f60badc8-546c-afc1-c34a-d9d1a338fe75/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19091481/1d1a7bac-8a83-11e6-80e0-dc2fe79474f8.png)

**Comment by BrokenCommander** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/19090701/db1b3cd0-8a7f-11e6-94b5-fc11566f6089.png)
https://cloud.githubusercontent.com/assets/22012363/19090701/db1b3cd0-8a7f-11e6-94b5-fc11566f6089.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/19090702/db2062a0-8a7f-11e6-9608-3b2fc0694926.png

**Comment by 2Qt2beStr8** [comment]
@BrokenCommander .... to big ;-)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19091481/1d1a7bac-8a83-11e6-80e0-dc2fe79474f8.png)
https://cloud.githubusercontent.com/assets/20930745/19091481/1d1a7bac-8a83-11e6-80e0-dc2fe79474f8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19091495/2d040e0c-8a83-11e6-8913-22be46a53b2f.png
