### ISSUE TITLE
Yahoo Bots

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8188]
**App Name:** Yahoo Bots
**Bundle ID:** com.yahoo.argo3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1152016678">1152016678</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahoo-bots/id1152016678?mt=8&uo=4">https://itunes.apple.com/us/app/yahoo-bots/id1152016678?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4>© Yahoo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/6a/ad/79/6aad79b3-3704-fc6f-a64b-74f01c0d4b94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19693960/cf6ed84c-9add-11e6-894e-9096d71cd310.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19101943/8291d428-8acc-11e6-8e07-88b960c382df.png)
https://cloud.githubusercontent.com/assets/2068130/19101943/8291d428-8acc-11e6-8e07-88b960c382df.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19101952/91203386-8acc-11e6-9d8e-532f616d2a36.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Yahoo Bots
**Bundle ID:** com.yahoo.argo3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1152016678">1152016678</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahoo-bots/id1152016678?mt=8&uo=4">https://itunes.apple.com/us/app/yahoo-bots/id1152016678?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4>© Yahoo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/6a/ad/79/6aad79b3-3704-fc6f-a64b-74f01c0d4b94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19693960/cf6ed84c-9add-11e6-894e-9096d71cd310.png)
https://cloud.githubusercontent.com/assets/20930745/19693960/cf6ed84c-9add-11e6-894e-9096d71cd310.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19694003/f0a1c4ca-9add-11e6-9ac5-e0eb8913e509.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19694155/8445fd4a-9ade-11e6-92f7-87b8e4cc29af.png)
https://cloud.githubusercontent.com/assets/20930745/19694155/8445fd4a-9ade-11e6-92f7-87b8e4cc29af.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19694172/92f3fd88-9ade-11e6-8c31-b517e0c7ebc3.png
