### ISSUE TITLE
Cheetah Note - Watch & Widget Note

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8189]
**App Name:** Cheetah Note - Watch & Widget Note
**Bundle ID:** com.jasonnam.QuickNote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=956698820">956698820</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cheetah-note-watch-widget/id956698820?mt=8&uo=4">https://itunes.apple.com/us/app/cheetah-note-watch-widget/id956698820?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Seokhyeon Nam
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/seokhyeon-nam/id956698819?uo=4>© Seokhyeon Nam</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/f0/5f/41/f05f413d-67ef-6001-51b9-7cffed40fa67/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19102074/9a335a06-8acd-11e6-9c39-d0c721b4f836.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19102074/9a335a06-8acd-11e6-9c39-d0c721b4f836.png)
https://cloud.githubusercontent.com/assets/2068130/19102074/9a335a06-8acd-11e6-9c39-d0c721b4f836.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19102082/a94b4486-8acd-11e6-801b-a9f5585359a9.png
