### ISSUE TITLE
IKEA Catalog

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#819]
**App Name:** IKEA Catalog
**Bundle ID:** com.ikea.ikeacatalogue2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=386592716">386592716</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ikea-catalog/id386592716?mt=8&uo=4">https://itunes.apple.com/us/app/ikea-catalog/id386592716?mt=8&uo=4</a>
**App Version:** 17.02
**Seller:** Inter IKEA Systems B.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inter-ikea-systems-b.v./id339722471?uo=4">© Inter IKEA Systems B.V.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/fa/15/ec/fa15ecf9-efbb-b6e2-e05d-fc363f46dfdb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078288/cc999c0a-bf69-11e6-8ca8-cc090bb8298b.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078288/cc999c0a-bf69-11e6-8ca8-cc090bb8298b.png)
https://cloud.githubusercontent.com/assets/2068130/21078288/cc999c0a-bf69-11e6-8ca8-cc090bb8298b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21078292/dabb8992-bf69-11e6-8e3d-eb66b3b9b3d5.png
