### ISSUE TITLE
Assistant+

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8192]
**App Name:** Assistant+
 **Bundle ID:** com.assistantplus.app
 **Version:** 1.2.0-1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/10730122/19111020/970fcb40-8afd-11e6-9183-b1e2e595ae87.png" width="180" height="180" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19114690/56c57438-8b0f-11e6-8186-09b5681de397.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19114134/fd3ae7ce-8b0c-11e6-8d25-93ae7590e408.png)
https://cloud.githubusercontent.com/assets/20930745/19114134/fd3ae7ce-8b0c-11e6-8d25-93ae7590e408.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19114157/111f3952-8b0d-11e6-9fc7-b5464fa53d1f.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19114690/56c57438-8b0f-11e6-8186-09b5681de397.png)
https://cloud.githubusercontent.com/assets/20930745/19114690/56c57438-8b0f-11e6-8186-09b5681de397.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19114710/7125698c-8b0f-11e6-88cd-3dddc0bb29f4.png
