### ISSUE TITLE
Dropbox Paper

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8193]
**App Name:** Dropbox Paper
**Bundle ID:** com.dropbox.paper
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1126623662">1126623662</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dropbox-paper/id1126623662?mt=8&uo=4">https://itunes.apple.com/us/app/dropbox-paper/id1126623662?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Dropbox, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dropbox/id327630333?uo=4>© Dropbox</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/88/92/91/8892919d-ecce-cc52-e8fa-e576a55a7963/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19113340/73cb13c2-8b09-11e6-883d-c71a4e5ef3ef.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19113340/73cb13c2-8b09-11e6-883d-c71a4e5ef3ef.png)
https://cloud.githubusercontent.com/assets/20930745/19113340/73cb13c2-8b09-11e6-883d-c71a4e5ef3ef.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19113360/82b575e4-8b09-11e6-9052-b1b7ae568937.png
