### ISSUE TITLE
Yahoo Newsroom: News, Finance, Sports and more

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8194]
**App Name:** Newsroom - News worth sharing
**Bundle ID:** com.yahoo.frontpage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=304158842">304158842</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsroom-news-worth-sharing/id304158842?mt=8&uo=4">https://itunes.apple.com/us/app/newsroom-news-worth-sharing/id304158842?mt=8&uo=4</a>
**App Version:** 9.1.2
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4">© Yahoo</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/34/0e/0f/340e0f69-621b-ee91-05df-9e90f0e0201b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34455444-c1a247da-ed7f-11e7-8de0-b8e83e7a9331.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19113147/9d82256c-8b08-11e6-9062-0103318e9b82.png)
https://cloud.githubusercontent.com/assets/20930745/19113147/9d82256c-8b08-11e6-9062-0103318e9b82.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19113162/aabf7b30-8b08-11e6-8058-eea564b7498a.png

**Comment by Christian9901** [comment]
Icon needs an update

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34455444-c1a247da-ed7f-11e7-8de0-b8e83e7a9331.png)
https://user-images.githubusercontent.com/2068130/34455444-c1a247da-ed7f-11e7-8de0-b8e83e7a9331.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34455445-d0a76d46-ed7f-11e7-88ba-b85126c52281.png
