### ISSUE TITLE
PewDiePie's Tuber Simulator

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8195]
**App Name:** PewDiePie's Tuber Simulator
**Bundle ID:** com.outerminds.tubular
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1093190533">1093190533</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pewdiepies-tuber-simulator/id1093190533?mt=8&uo=4">https://itunes.apple.com/us/app/pewdiepies-tuber-simulator/id1093190533?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Outerminds Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/outerminds-inc./id921017187?uo=4>© Outerminds Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/ac/de/45/acde4572-6d77-2578-b7bb-982009564c16/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19169816/4293f5a4-8c16-11e6-8554-f79830562c19.png)

**Comment by 2Qt2beStr8** [comment]
... this kind of icons are horrible ... no idea how to create a icon that looks good :-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19133223/7c984576-8b57-11e6-86e3-89a0c348d39f.png)
https://cloud.githubusercontent.com/assets/20930745/19133223/7c984576-8b57-11e6-86e3-89a0c348d39f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19133298/d0381b2a-8b57-11e6-8ad7-5369b15c4d64.png

**Comment by dreamnet** [comment]
Yes, these pixelated icons are a nightmare. 😱 Just a try:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19169816/4293f5a4-8c16-11e6-8554-f79830562c19.png)
https://cloud.githubusercontent.com/assets/2068130/19169816/4293f5a4-8c16-11e6-8554-f79830562c19.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19169832/50d9ae10-8c16-11e6-9513-cb7a5f1b6dbc.png
