### ISSUE TITLE
Animation Throwdown: The Quest for Cards

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8196]
**App Name:** Animation Throwdown: The Quest for Cards
**Bundle ID:** com.kongregate.mobile.throwdown
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1080816579">1080816579</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/animation-throwdown-quest/id1080816579?mt=8&uo=4">https://itunes.apple.com/us/app/animation-throwdown-quest/id1080816579?mt=8&uo=4</a>
**App Version:** 1.0.9
**Seller:** Kongregate, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kongregate/id491569846?uo=4>© Kongregate</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/d2/1d/ec/d21dec3c-54f1-01d7-7e62-06d06f991dde/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19167248/14d1a946-8c0b-11e6-80f8-8dab3f30cc85.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19146115/590f873a-8bb2-11e6-8ad3-0fbe7fb55140.png)
https://cloud.githubusercontent.com/assets/20930745/19146115/590f873a-8bb2-11e6-8ad3-0fbe7fb55140.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19146130/66a273d0-8bb2-11e6-84bb-4e2d1e0941f6.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Fine. Did some corner rounding.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19167248/14d1a946-8c0b-11e6-80f8-8dab3f30cc85.png)
https://cloud.githubusercontent.com/assets/2068130/19167248/14d1a946-8c0b-11e6-80f8-8dab3f30cc85.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19167260/237efd18-8c0b-11e6-82ae-3bdff01ea49d.png

**Comment by 2Qt2beStr8** [comment]
sorry @dreamnet .... i forget sometimes to round the corners .... i will do it better in the future
