### ISSUE TITLE
Futurama: Game of Drones

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8197]
**App Name:** Futurama: Game of Drones
**Bundle ID:** net.wooga.futurama
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1009200976">1009200976</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/futurama-game-of-drones/id1009200976?mt=8&uo=4">https://itunes.apple.com/us/app/futurama-game-of-drones/id1009200976?mt=8&uo=4</a>
**App Version:** 1.9.0
**Seller:** wooga gmbh
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wooga/id461402737?uo=4>© wooga</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/f2/d6/55/f2d65523-f061-268d-60eb-bfd1bba15eb0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19132514/1ced2d9c-8b54-11e6-991f-898db9efc992.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19132514/1ced2d9c-8b54-11e6-991f-898db9efc992.png)
https://cloud.githubusercontent.com/assets/20930745/19132514/1ced2d9c-8b54-11e6-991f-898db9efc992.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19132532/2e5f9812-8b54-11e6-8590-f6de8e226ff1.png
