### ISSUE TITLE
Calvino Noir

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8198]
**App Name:** Calvino Noir
**Bundle ID:** org.mcro.calvinonoir
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=921527450">921527450</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calvino-noir/id921527450?mt=8&uo=4">https://itunes.apple.com/us/app/calvino-noir/id921527450?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Calvino Noir Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/calvino-noir-ltd/id921527449?uo=4>© Calvino Noir Ltd</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/f3/dd/1b/f3dd1bdb-8e9b-14cb-85c0-faeedb5e5bfb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19166974/119bcbea-8c0a-11e6-9887-645d4b587148.png)

**Comment by 2Qt2beStr8** [comment]
... can't do the original ... maybe you like this one?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19150349/a0ac76c0-8bc6-11e6-94b5-cd1580efc2a8.png)
https://cloud.githubusercontent.com/assets/20930745/19150349/a0ac76c0-8bc6-11e6-94b5-cd1580efc2a8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19150379/d1b7e07e-8bc6-11e6-8cf8-7b6e7a299801.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19166974/119bcbea-8c0a-11e6-9887-645d4b587148.png)
https://cloud.githubusercontent.com/assets/2068130/19166974/119bcbea-8c0a-11e6-9887-645d4b587148.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19166993/2090533c-8c0a-11e6-893f-da088995f95c.png
Don't ask me how I did this. 😜

**Comment by 2Qt2beStr8** [comment]
@dreamnet .. wow ... how have you made this? :-)

**Comment by dreamnet** [comment]
@2Qt2beStr8 😁 I remembered the raster effect of photos in old newspapers... you can get this effect in Photoshop. Here is a [little Screencast](http://glasklarthd.dreamnet.at/tmp/Photoshop_Bitmap_Raster.mp4).

**Comment by 2Qt2beStr8** [comment]
... ah ... nice ... i have made it with Illustrator ... but yours is much better

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19168341/00f1fc6e-8c10-11e6-8338-cd3be34f8ce4.png)
https://cloud.githubusercontent.com/assets/20930745/19168341/00f1fc6e-8c10-11e6-8338-cd3be34f8ce4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19168376/3278975c-8c10-11e6-9ec6-d8fe39851c44.png

**Comment by Trubbel** [comment]
@dreamnet Wow.. :open_mouth:
