### ISSUE TITLE
Magic Launcher Pro - Launch anything Instantly

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8199]
**App Name:** Magic Launcher Pro - Launch anything Instantly
**Bundle ID:** com.roxwin.launcherpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1121523480">1121523480</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/magic-launcher-pro-launch/id1121523480?mt=8&uo=4">https://itunes.apple.com/us/app/magic-launcher-pro-launch/id1121523480?mt=8&uo=4</a>
**App Version:** 4.2.2
**Seller:** Roxwin Vietnam Technologies Company Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/roxwin-vietnam-technologies/id1077249023?uo=4>© Roxwin Vietnam Technologies Company Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/4e/25/b1/4e25b197-43aa-2ddf-7c9c-e55a92fe6634/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19133796/86188f9a-8b5a-11e6-9ed7-83ff5bd1c2ad.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19133796/86188f9a-8b5a-11e6-9ed7-83ff5bd1c2ad.png)
https://cloud.githubusercontent.com/assets/20930745/19133796/86188f9a-8b5a-11e6-9ed7-83ff5bd1c2ad.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19133817/9ee96b5c-8b5a-11e6-9d77-8b84086ec8f0.png
