### ISSUE TITLE
Amazon FR

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#820]
**App Name:** Amazon FR
**Bundle ID:** com.amazon.AmazonFR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=358861688">358861688</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/amazon-fr/id358861688?mt=8&uo=4">https://itunes.apple.com/fr/app/amazon-fr/id358861688?mt=8&uo=4</a>
**App Version:** 4.4.1
**Seller:** Amazon Eurasia Holdings Sarl
**Developer:** <a target="_blank" href=https://itunes.apple.com/fr/artist/amazon/id335187486?uo=4>© Amazon</a>
**Supported Devices:** iPad23G, iPadFourthGen4G, iPhone4S, iPadFourthGen, iPhone6, iPodTouchFifthGen, iPad2Wifi, iPhone5s, iPadMini, iPhone5c, iPhone5, iPhone6Plus, iPadMini4G, iPadThirdGen, iPadThirdGen4G, iPhone4
**Original Artwork:**
<img src="http://a909.phobos.apple.com/us/r30/Purple3/v4/74/86/d8/7486d895-8d67-633d-71a0-5f3f25f98601/mzl.iowdmrju.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6473609/b006dac6-c1fa-11e4-935c-beb3034ae999.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6473609/b006dac6-c1fa-11e4-935c-beb3034ae999.png)
https://cloud.githubusercontent.com/assets/2068130/6473609/b006dac6-c1fa-11e4-935c-beb3034ae999.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6473469/d013c280-c1f9-11e4-8fd6-6928226b411b.png
