### ISSUE TITLE
ACDSee Camera Pro

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8200]
**App Name:** ACDSee Camera Pro
**Bundle ID:** com.acmi.acdsee-camera-pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1122899052">1122899052</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/acdsee-camera-pro/id1122899052?mt=8&uo=4">https://itunes.apple.com/us/app/acdsee-camera-pro/id1122899052?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** ACDSee.com Mobile Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/acdsee.com-mobile-inc./id909222897?uo=4>© ACDSee.com Mobile Inc.</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/ad/e4/b5/ade4b539-fdba-1e13-ebee-9f590f1a09a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19151788/f5dbfeec-8bce-11e6-9255-5751155d53e6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19151788/f5dbfeec-8bce-11e6-9255-5751155d53e6.png)
https://cloud.githubusercontent.com/assets/20930745/19151788/f5dbfeec-8bce-11e6-9255-5751155d53e6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19151792/02485446-8bcf-11e6-9d52-3f1999efb6d0.png
