### ISSUE TITLE
ProtonMail - Encrypted Email

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8201]
**App Name:** ProtonMail - Encrypted Email
**Bundle ID:** ch.protonmail.protonmail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979659905">979659905</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/protonmail-encrypted-email/id979659905?mt=8&uo=4">https://itunes.apple.com/us/app/protonmail-encrypted-email/id979659905?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Proton Technologies AG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/protonmail/id979659484?uo=4>© ProtonMail</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/c4/c6/e7/c4c6e740-6253-db45-93f9-62c585830075/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19168736/da0bf33c-8c11-11e6-877a-f837dbffbc3b.png)

**Comment by Checkit23** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/16171251/19168457/81090d66-8c10-11e6-8f2e-83d3801c80f1.png)

https://cloud.githubusercontent.com/assets/16171251/19168457/81090d66-8c10-11e6-8f2e-83d3801c80f1.png

Source:
https://cloud.githubusercontent.com/assets/16171251/19168465/87a2c18a-8c10-11e6-8251-6c027db30509.png

**Comment by 2Qt2beStr8** [comment]
@Checkit23  ... yours is to big

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19168736/da0bf33c-8c11-11e6-877a-f837dbffbc3b.png)
https://cloud.githubusercontent.com/assets/20930745/19168736/da0bf33c-8c11-11e6-877a-f837dbffbc3b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19168746/eb5fbbbe-8c11-11e6-82b2-30d388c9b887.png
