### ISSUE TITLE
Star Trek Timelines

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8202]
**App Name:** Star Trek Timelines
**Bundle ID:** com.disruptorbeam.StarTrekTimelines
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1001250333">1001250333</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/star-trek-timelines/id1001250333?mt=8&uo=4">https://itunes.apple.com/us/app/star-trek-timelines/id1001250333?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Disruptor Beam, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/disruptor-beam/id501830754?uo=4>© Disruptor Beam</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/19/7d/e1/197de158-68d8-59f4-e3bf-317f69aa4b81/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19538144/03b689c2-9653-11e6-8eb2-a6f74c660b4d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19188607/22ee2544-8c93-11e6-961b-5f9cfdd7204c.png)
https://cloud.githubusercontent.com/assets/20930745/19188607/22ee2544-8c93-11e6-961b-5f9cfdd7204c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19188626/43d83bd2-8c93-11e6-9991-4bd1f4643feb.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 We should use the way I showed you in #8198 only for fotorealistic icons - not for icons like this.

**Comment by 2Qt2beStr8** [comment]
@dreamnet  Ok 👍

**Comment by 2Qt2beStr8** [comment]
i tryed the original icon, but i looks not really good ;-(

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19538144/03b689c2-9653-11e6-8eb2-a6f74c660b4d.png)
https://cloud.githubusercontent.com/assets/20930745/19538144/03b689c2-9653-11e6-8eb2-a6f74c660b4d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19538164/1bc4c29a-9653-11e6-9943-8f72c6e958a6.png

**Comment by 2Qt2beStr8** [comment]
so i created two alternatives

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19538191/35ee5348-9653-11e6-884b-9232b861254a.png)
https://cloud.githubusercontent.com/assets/20930745/19538191/35ee5348-9653-11e6-884b-9232b861254a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19538203/443f1ffe-9653-11e6-80a3-bba954cad6c0.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19538213/502cf660-9653-11e6-9e50-bebd358b67bc.png)
https://cloud.githubusercontent.com/assets/20930745/19538213/502cf660-9653-11e6-9e50-bebd358b67bc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19538227/5e39d3ae-9653-11e6-9d66-4824e0a14f1d.png

**Comment by Checkit23** [comment]
Well, I like the icon with the space ship on it. Adding a star field in the background might improve it some more. Using Spock's hand as the icon is a funny idea :-D 

So year, I think both icons would fit quite well.

**Comment by 2Qt2beStr8** [comment]
@Checkit23 ... i created a icon for you with some stars at the background .. but i think we should not use this icon for the glasklart theme 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19596968/ee53f6e2-9791-11e6-9746-5562f39035dc.png)
https://cloud.githubusercontent.com/assets/20930745/19596968/ee53f6e2-9791-11e6-9746-5562f39035dc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19596986/01ed96d6-9792-11e6-9915-76230f5f30b4.png

**Comment by dreamnet** [comment]
I think the second one from @2Qt2beStr8 is just fine.
