### ISSUE TITLE
Sky Gamblers: Storm Raiders

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8203]
**App Name:** Sky Gamblers: Storm Raiders
**Bundle ID:** com.atypicalgames.sgsr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=574375380">574375380</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sky-gamblers-storm-raiders/id574375380?mt=8&uo=4">https://itunes.apple.com/us/app/sky-gamblers-storm-raiders/id574375380?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** ATYPICAL GAMES LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/atypical-games/id574375383?uo=4">© Atypical Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/f9/37/39/f93739a1-3c19-6be1-08fa-9d911f70e586/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20617672/1ef1e27c-b2eb-11e6-9a7e-d75fe9985f43.png)

**Comment by dreamnet** [comment]
Not the original....
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20617672/1ef1e27c-b2eb-11e6-9a7e-d75fe9985f43.png)
https://cloud.githubusercontent.com/assets/2068130/20617672/1ef1e27c-b2eb-11e6-9a7e-d75fe9985f43.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20617692/38c47e76-b2eb-11e6-8cc2-025805254079.png
