### ISSUE TITLE
Rummy

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8204]
**App Name:** Rummy
**Bundle ID:** com.eryodsoft.rummy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=790729888">790729888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rummy/id790729888?mt=8&uo=4">https://itunes.apple.com/us/app/rummy/id790729888?mt=8&uo=4</a>
**App Version:** 3.3.2
**Seller:** Eryod Soft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eryod-soft/id375196975?uo=4>© Eryod Soft</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/16/ef/4e/16ef4ef6-5f68-3a00-1958-f42efa8da14c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19170469/d9e2f700-8c18-11e6-8aad-307ea0f381a2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19170469/d9e2f700-8c18-11e6-8aad-307ea0f381a2.png)
https://cloud.githubusercontent.com/assets/20930745/19170469/d9e2f700-8c18-11e6-8aad-307ea0f381a2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19170508/fd1cf496-8c18-11e6-8594-2c23478b7e55.png)
