### ISSUE TITLE
Riptide GP2

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8205]
**App Name:** Riptide GP2
**Bundle ID:** com.vectorunit.red
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=662569685">662569685</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/riptide-gp2/id662569685?mt=8&uo=4">https://itunes.apple.com/us/app/riptide-gp2/id662569685?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Vector Unit Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vector-unit/id469610085?uo=4">© Vector Unit</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/f0/b2/76/f0b2765e-350c-d22c-083f-beaff1f2780d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21562842/55ff4ae6-ce7c-11e6-91cd-f8489c203865.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21562842/55ff4ae6-ce7c-11e6-91cd-f8489c203865.png)
https://cloud.githubusercontent.com/assets/2068130/21562842/55ff4ae6-ce7c-11e6-91cd-f8489c203865.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21562845/664f5576-ce7c-11e6-8804-39a75eae9e84.png
