### ISSUE TITLE
Microsoft SharePoint

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#8206]
**App Name:** Microsoft SharePoint
**Bundle ID:** com.microsoft.sharepoint
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1091505266">1091505266</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-sharepoint/id1091505266?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-sharepoint/id1091505266?mt=8&uo=4</a>
**App Version:** 4.10.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?mt=8&uo=4">© Microsoft Corporation</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/96/f9/3d/96f93d70-a8bd-2e49-3694-8bfc4a24ad6f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com microsoft sharepoint-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58777166-5ad1ce80-85cd-11e9-9d5c-2633f9a849b9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19191744/006ce08a-8ca4-11e6-80eb-54381b909e5a.png)
https://cloud.githubusercontent.com/assets/20930745/19191744/006ce08a-8ca4-11e6-80eb-54381b909e5a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19191755/1139c202-8ca4-11e6-879c-f3098994eac9.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58765198-84a8d800-8570-11e9-895f-91d792bf8543.png)
(https://user-images.githubusercontent.com/20930745/58765198-84a8d800-8570-11e9-895f-91d792bf8543.png

Source:
https://user-images.githubusercontent.com/20930745/58765200-85da0500-8570-11e9-9fd0-e30e37a200d6.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Great!! - To be "consistent", the other Microsoft-Issues I reopened need to be done in the same way.

**Comment by dreamnet** [comment]
![com microsoft sharepoint-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58777166-5ad1ce80-85cd-11e9-9d5c-2633f9a849b9.png)
https://user-images.githubusercontent.com/2068130/58777166-5ad1ce80-85cd-11e9-9d5c-2633f9a849b9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58777173-69b88100-85cd-11e9-946b-9592358466b0.png
