### ISSUE TITLE
ParkWhiz: Parking Deals - Daily, Monthly, & Events

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#8207]
**App Name:** ParkWhiz: Parking Deals - Daily, Monthly, & Events
**Bundle ID:** com.parkwhiz.ParkWhiz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=595743376">595743376</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parkwhiz-parking-deals-daily/id595743376?mt=8&uo=4">https://itunes.apple.com/us/app/parkwhiz-parking-deals-daily/id595743376?mt=8&uo=4</a>
**App Version:** 5.2.5
**Seller:** ParkWhiz, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/parkwhiz-inc./id457125323?uo=4>© ParkWhiz, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple41/v4/39/1a/13/391a1306-945a-b58a-f2c1-c80bc23ea22e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19191984/e0313b3a-8ca4-11e6-9021-a9d89c54b1c5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19191984/e0313b3a-8ca4-11e6-9021-a9d89c54b1c5.png)
https://cloud.githubusercontent.com/assets/20930745/19191984/e0313b3a-8ca4-11e6-9021-a9d89c54b1c5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19191999/eea2ca1c-8ca4-11e6-805f-1898e4b9d3e1.png
