### ISSUE TITLE
Tweety - Twitter Widget for the Notification Center

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8208]
**App Name:** Tweety - Twitter Widget for the Notification Center
**Bundle ID:** com.roxwin.tweety
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1116596608">1116596608</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tweety-twitter-widget-for/id1116596608?mt=8&uo=4">https://itunes.apple.com/us/app/tweety-twitter-widget-for/id1116596608?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Roxwin Vietnam Technologies Company Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/roxwin-vietnam-technologies/id1077249023?uo=4>© Roxwin Vietnam Technologies Company Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/92/cc/9d/92cc9dcb-4dec-a949-6589-8ed3070f77c4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19197251/1250d454-8cb9-11e6-8b88-2e440f867c30.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19195451/096bd1a6-8cb2-11e6-8152-cdc647db97b5.png)
https://cloud.githubusercontent.com/assets/20930745/19195451/096bd1a6-8cb2-11e6-8152-cdc647db97b5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19195470/17bd1a94-8cb2-11e6-854b-392ae8676dd4.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19197251/1250d454-8cb9-11e6-8b88-2e440f867c30.png)
https://cloud.githubusercontent.com/assets/2068130/19197251/1250d454-8cb9-11e6-8b88-2e440f867c30.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19197266/1f7a257c-8cb9-11e6-859c-55639852ec7b.png
