### ISSUE TITLE
OpenGo - Find places that are open now

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8209]
**App Name:** OpenGo - Find places that are open now
**Bundle ID:** com.opengo.ui.OpenGo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=610183631">610183631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/opengo-find-places-that-are/id610183631?mt=8&uo=4">https://itunes.apple.com/us/app/opengo-find-places-that-are/id610183631?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Go Software, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/go-software-llc/id610183635?uo=4>© Go Software, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/8c/ca/af/8ccaaf32-16a0-3bd9-f107-e4d13129f193/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19195325/6d4aa8ec-8cb1-11e6-916d-ba81c2f30755.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19195325/6d4aa8ec-8cb1-11e6-916d-ba81c2f30755.png)
https://cloud.githubusercontent.com/assets/20930745/19195325/6d4aa8ec-8cb1-11e6-916d-ba81c2f30755.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19195337/7b43c1cc-8cb1-11e6-96fb-973729346e00.png
