### ISSUE TITLE
Newsbot: News you care about, no nonsense

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8210]
**App Name:** Newsbot: News you care about, no nonsense
**Bundle ID:** com.shellanoo.newsbot.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1132973112">1132973112</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsbot-news-you-care-about/id1132973112?mt=8&uo=4">https://itunes.apple.com/us/app/newsbot-news-you-care-about/id1132973112?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Shellanoo Group Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/shellanoo-group-ltd/id1048447299?uo=4>© Shellanoo Group Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/41/59/fb/4159fb51-7c17-8d3d-34a6-191346e0119b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19195085/44f44a52-8cb0-11e6-9444-d374f1561ae2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19195085/44f44a52-8cb0-11e6-9444-d374f1561ae2.png)
https://cloud.githubusercontent.com/assets/2068130/19195085/44f44a52-8cb0-11e6-9444-d374f1561ae2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19195100/52f27ae8-8cb0-11e6-823d-60ffe90e1be2.png
