### ISSUE TITLE
White Noise

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8211]
**App Name:** White Noise
**Bundle ID:** com.tmsoft.WhiteNoise
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=289894882">289894882</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/white-noise/id289894882?mt=8&uo=4">https://itunes.apple.com/us/app/white-noise/id289894882?mt=8&uo=4</a>
**App Version:** 7.0.2
**Seller:** TMSOFT
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tmsoft/id288669797?uo=4>© TMSOFT</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/6f/e5/b1/6fe5b1aa-6dab-ea1a-0f0b-f2eda9c06417/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19200125/a024ab8a-8cc7-11e6-84f4-5d17a0c701ab.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19200125/a024ab8a-8cc7-11e6-84f4-5d17a0c701ab.png)
https://cloud.githubusercontent.com/assets/20930745/19200125/a024ab8a-8cc7-11e6-84f4-5d17a0c701ab.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19200132/afca9982-8cc7-11e6-8a7f-47d376f2e1cf.png
