### ISSUE TITLE
LivePhish

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8212]
**App Name:** LivePhish
**Bundle ID:** com.livephish.livephish
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=374048661">374048661</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/livephish/id374048661?mt=8&uo=4">https://itunes.apple.com/us/app/livephish/id374048661?mt=8&uo=4</a>
**App Version:** 2.8
**Seller:** nugs.net enterprises, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nugs.net-enterprises-llc/id327248667?uo=4>© nugs.net enterprises, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/0a/44/27/0a44275a-e390-14a4-3f28-db26d2de6d2f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19202709/08f3644c-8cd4-11e6-95be-f749c76ebcc9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19200230/4315fad8-8cc8-11e6-9a68-ffa08012b715.png)
https://cloud.githubusercontent.com/assets/20930745/19200230/4315fad8-8cc8-11e6-9a68-ffa08012b715.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19200261/53835780-8cc8-11e6-83b5-274dd2ec8d11.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19202709/08f3644c-8cd4-11e6-95be-f749c76ebcc9.png)
https://cloud.githubusercontent.com/assets/20930745/19202709/08f3644c-8cd4-11e6-95be-f749c76ebcc9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19202734/18a3acb2-8cd4-11e6-8526-29441531c0a1.png
