### ISSUE TITLE
AmpKit+ - Guitar amps and effects recording studio with backing tracks, tuner and metronome

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8213]
**App Name:** AmpKit+ - Guitar amps and effects recording studio with backing tracks, tuner and metronome
**Bundle ID:** com.agilepartners.ampkitplus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=385758778">385758778</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ampkit+-guitar-amps-effects/id385758778?mt=8&uo=4">https://itunes.apple.com/us/app/ampkit+-guitar-amps-effects/id385758778?mt=8&uo=4</a>
**App Version:** 2.2.7
**Seller:** Agile Partners Technologies, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/agile-partners/id284962371?uo=4>© Agile Partners</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/97/40/3b/97403bce-5b52-415f-bf6b-2c53a6654032/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19220232/e97deb22-8e28-11e6-99ea-50ae5a3dd12e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19220232/e97deb22-8e28-11e6-99ea-50ae5a3dd12e.png)
https://cloud.githubusercontent.com/assets/2068130/19220232/e97deb22-8e28-11e6-99ea-50ae5a3dd12e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19220236/f78273d2-8e28-11e6-9f8c-c2d8ca88e7d6.png
