### ISSUE TITLE
Music Center - Music Widget Lock Screen

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8214]
**App Name:** Music Center - Music Widget Lock Screen
**Bundle ID:** com.Saltb0xApps.Music-Center
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=941041243">941041243</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/music-center-music-widget/id941041243?mt=8&uo=4">https://itunes.apple.com/us/app/music-center-music-widget/id941041243?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** DREAM BITS STUDIOS LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/dream-bits-studios-limited/id446698637?uo=4>© DREAM BITS STUDIOS LIMITED</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple41/v4/46/1a/d8/461ad838-281c-fd65-a6d9-273f4630ef74/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19201965/75c2681a-8cd0-11e6-906c-ebff3bf204dd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19201874/088e132a-8cd0-11e6-8af5-c16a5dc4be31.png)
https://cloud.githubusercontent.com/assets/20930745/19201874/088e132a-8cd0-11e6-8af5-c16a5dc4be31.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19201891/1b7c091a-8cd0-11e6-9d59-7f5900529eb4.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19201965/75c2681a-8cd0-11e6-906c-ebff3bf204dd.png)
https://cloud.githubusercontent.com/assets/20930745/19201965/75c2681a-8cd0-11e6-906c-ebff3bf204dd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19202127/18eb7748-8cd1-11e6-9457-cdbf0927f246.png
