### ISSUE TITLE
NPR One

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8215]
**App Name:** NPR One
**Bundle ID:** org.npr.one
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=874498884">874498884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/npr-one/id874498884?mt=8&uo=4">https://itunes.apple.com/us/app/npr-one/id874498884?mt=8&uo=4</a>
**App Version:** 1.6.14
**Seller:** NPR
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/npr/id324906254?mt=8&uo=4>© NPR</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple22/v4/95/cd/a1/95cda1af-5674-024f-6618-f74b7fb28c04/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19201420/0f58a140-8cce-11e6-9e76-061dce26da81.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19201420/0f58a140-8cce-11e6-9e76-061dce26da81.png)
https://cloud.githubusercontent.com/assets/20930745/19201420/0f58a140-8cce-11e6-9e76-061dce26da81.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19201443/1f3e4c0e-8cce-11e6-8834-09b4ef6b572f.png
