### ISSUE TITLE
Mobile POD - Guitar Amps and Effects

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8216]
**App Name:** Mobile POD - Guitar Amps and Effects
**Bundle ID:** com.line6.iggy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=475002772">475002772</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobile-pod-guitar-amps-effects/id475002772?mt=8&uo=4">https://itunes.apple.com/us/app/mobile-pod-guitar-amps-effects/id475002772?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Line 6, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/line-6/id356473190?uo=4>© Line 6</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/cc/8f/46/cc8f46ab-deea-d33f-966f-4e28557ae9f7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19200568/03ee6e24-8cca-11e6-8a6a-cb0aea366a70.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19200568/03ee6e24-8cca-11e6-8a6a-cb0aea366a70.png)
https://cloud.githubusercontent.com/assets/20930745/19200568/03ee6e24-8cca-11e6-8a6a-cb0aea366a70.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19200576/1132a55a-8cca-11e6-85bc-4b953c497532.png
