### ISSUE TITLE
AUS Rain Radar - Bom radar and weather forecast

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8217]
**App Name:** AUS Rain Radar - Bom radar and weather forecast
**Bundle ID:** com.touchyfeely.ausrainradar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=993445822">993445822</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aus-rain-radar-bom-radar-weather/id993445822?mt=8&uo=4">https://itunes.apple.com/us/app/aus-rain-radar-bom-radar-weather/id993445822?mt=8&uo=4</a>
**App Version:** 3.3.2
**Seller:** Leon Calcutt
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/leon-calcutt/id951395157?uo=4>© Leon Calcutt</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/66/e3/a3/66e3a3de-b6aa-8be0-e1e5-51386194535c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19210836/3a963380-8d2e-11e6-9668-7e098e1bf8b2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19210836/3a963380-8d2e-11e6-9668-7e098e1bf8b2.png)
https://cloud.githubusercontent.com/assets/2068130/19210836/3a963380-8d2e-11e6-9668-7e098e1bf8b2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19210842/4b457ce0-8d2e-11e6-9e34-d092ee16e804.png
