### ISSUE TITLE
Virgin Australia

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8218]
**App Name:** Virgin Australia
**Bundle ID:** com.virginaustralia.vaffa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1060472593">1060472593</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/virgin-australia/id1060472593?mt=8&uo=4">https://itunes.apple.com/us/app/virgin-australia/id1060472593?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** VIRGIN AUSTRALIA HOLDINGS PTY LIMITED
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/virgin-australia-holdings/id531032504?uo=4>© VIRGIN AUSTRALIA HOLDINGS PTY LIMITED</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/7d/cb/07/7dcb07a8-af5e-ea5f-3240-7323547e3c59/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19210885/a09e4cb6-8d2f-11e6-9711-3ce20bf61664.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19210885/a09e4cb6-8d2f-11e6-9711-3ce20bf61664.png)
https://cloud.githubusercontent.com/assets/2068130/19210885/a09e4cb6-8d2f-11e6-9711-3ce20bf61664.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19210890/ae67d9ca-8d2f-11e6-8f0e-a53d4af2f842.png
