### ISSUE TITLE
Qantas Airways

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8219]
**App Name:** Qantas Airways
**Bundle ID:** com.qantas.Qantas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=640437525">640437525</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qantas-airways/id640437525?mt=8&uo=4">https://itunes.apple.com/us/app/qantas-airways/id640437525?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Qantas Airways Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/qantas-airways-limited/id394287136?uo=4>© Qantas Airways Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/0b/93/a8/0b93a83e-8536-7915-a859-4388a8708ee1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19210863/ce176b60-8d2e-11e6-8c39-894354c271e4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19210863/ce176b60-8d2e-11e6-8c39-894354c271e4.png)
https://cloud.githubusercontent.com/assets/2068130/19210863/ce176b60-8d2e-11e6-8c39-894354c271e4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19210865/dc43c742-8d2e-11e6-8e93-c5b99c63c106.png
