### ISSUE TITLE
Gauge - Game

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#822]
**App Name:** Gauge - Game
**Bundle ID:** com.gameatelier.gauge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=512206751">512206751</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gauge-game/id512206751?mt=8&uo=4">https://itunes.apple.com/us/app/gauge-game/id512206751?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** The Game Atelier
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/game-atelier/id403533761?uo=4">© Game Atelier</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/a8/69/43/a869434e-7f63-f663-1339-7b08bf88cc64/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36950022-74823336-1ff0-11e8-85a5-b737f872ed49.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36950022-74823336-1ff0-11e8-85a5-b737f872ed49.png)
https://user-images.githubusercontent.com/2068130/36950022-74823336-1ff0-11e8-85a5-b737f872ed49.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36950024-8290df9a-1ff0-11e8-858b-d6f3870a4768.png
