### ISSUE TITLE
Widget Calendar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8221]
**App Name:** Widget Calendar
**Bundle ID:** com.Waak.Widget-Calendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=922436277">922436277</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/widget-calendar/id922436277?mt=8&uo=4">https://itunes.apple.com/us/app/widget-calendar/id922436277?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** yoon sik kang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yoon-sik-kang/id724211619?uo=4>© yoon sik kang</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/ad/be/3e/adbe3e2a-edaf-5f5f-b714-b00b8e328211/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19215079/0387f584-8d94-11e6-83bf-c7fcf92e200b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19215079/0387f584-8d94-11e6-83bf-c7fcf92e200b.png)
https://cloud.githubusercontent.com/assets/20930745/19215079/0387f584-8d94-11e6-83bf-c7fcf92e200b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19215080/26e0fdf0-8d94-11e6-996c-0062ea578e2e.png
