### ISSUE TITLE
Speed PRO+

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8222]
**App Name:** Speed PRO+
**Bundle ID:** com.johnnytucker.speedprohd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=510776298">510776298</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/speed-pro+/id510776298?mt=8&uo=4">https://itunes.apple.com/us/app/speed-pro+/id510776298?mt=8&uo=4</a>
**App Version:** 2.01
**Seller:** Mother Tucker LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mother-tucker-llc/id309226345?mt=8&uo=4>© Mother Tucker LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/18/f4/77/18f477b7-af72-458b-ce96-3e436c311da3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19215479/bbb34e14-8d9f-11e6-8e78-df66d05ee460.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19215479/bbb34e14-8d9f-11e6-8e78-df66d05ee460.png)
https://cloud.githubusercontent.com/assets/20930745/19215479/bbb34e14-8d9f-11e6-8e78-df66d05ee460.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19215482/cc325622-8d9f-11e6-942a-4e8d20ab29df.png
