### ISSUE TITLE
Converter Pro - Units & Currency Converter & Calculator

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8223]
**App Name:** Converter Pro - Units & Currency Converter & Calculator
**Bundle ID:** com.cidersoftware.converterpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=741771917">741771917</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/converter-pro-units-currency/id741771917?mt=8&uo=4">https://itunes.apple.com/us/app/converter-pro-units-currency/id741771917?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Cider Software LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cider-software-llc/id465180756?uo=4>© Cider Software LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/28/8c/c6/288cc6b3-f247-3848-b5d3-331ef72b9924/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19215514/b8969cda-8da0-11e6-9bb7-2828ea1621c0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19215514/b8969cda-8da0-11e6-9bb7-2828ea1621c0.png)
https://cloud.githubusercontent.com/assets/20930745/19215514/b8969cda-8da0-11e6-9bb7-2828ea1621c0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19215516/c7101cd2-8da0-11e6-8f9c-b622c80bd790.png
