### ISSUE TITLE
Go Radar - Live Map for Pokémon GO

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8224]
**App Name:** Go Radar - Live Map for Pokémon GO
**Bundle ID:** io.goradar.radar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1139995553">1139995553</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/go-radar-live-map-for-pokemon/id1139995553?mt=8&uo=4">https://itunes.apple.com/us/app/go-radar-live-map-for-pokemon/id1139995553?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** GO Radar LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/go-radar-llc/id1142735512?uo=4>© GO Radar LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple41/v4/32/51/69/325169ec-72ef-f002-b2a2-f356fa35230c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19215530/30c45c2e-8da1-11e6-9802-3650ba6bdd3d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19215530/30c45c2e-8da1-11e6-9802-3650ba6bdd3d.png)
https://cloud.githubusercontent.com/assets/20930745/19215530/30c45c2e-8da1-11e6-9802-3650ba6bdd3d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19215531/3f6f0008-8da1-11e6-9943-20c301bd9417.png
