### ISSUE TITLE
Costco Canada

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8225]
**App Name:** Costco Canada
**Bundle ID:** com.costco.costco-ca
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=909080321">909080321</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/costco-canada/id909080321?mt=8&uo=4">https://itunes.apple.com/ca/app/costco-canada/id909080321?mt=8&uo=4</a>
**App Version:** 2.13
**Seller:** Costco Wholesale Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/developer/costco-wholesale-corporation/id535509418?uo=4>© Costco Wholesale Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/aa/f9/fb/aaf9fba2-caaa-a4e8-fce1-74261ff65e2a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18925889/f45dee1e-85b5-11e6-9da5-d86a282f9731.png)

**Comment by LaCh0uine** [comment]
Just use the same icon from 
https://github.com/glasklart/hd/issues/8146

Thank You

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18925889/f45dee1e-85b5-11e6-9da5-d86a282f9731.png)
https://cloud.githubusercontent.com/assets/20930745/18925889/f45dee1e-85b5-11e6-9da5-d86a282f9731.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18925907/026fae5c-85b6-11e6-9518-802da22677b6.png
