### ISSUE TITLE
Moto Hero

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8226]
**App Name:** Moto Hero
**Bundle ID:** com.tophotapp.motogo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=574246571">574246571</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moto-hero/id574246571?mt=8&uo=4">https://itunes.apple.com/us/app/moto-hero/id574246571?mt=8&uo=4</a>
**App Version:** 2.06
**Seller:** YUZHI MA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yuzhi-ma/id574246574?uo=4>© YUZHI MA</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/d7/a4/a4/d7a4a4f2-ab8c-6b95-8632-fa988787be93/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19216273/5259214e-8db5-11e6-9402-9c719b0fe57e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19216273/5259214e-8db5-11e6-9402-9c719b0fe57e.png)
https://cloud.githubusercontent.com/assets/20930745/19216273/5259214e-8db5-11e6-9402-9c719b0fe57e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19216274/62c6612c-8db5-11e6-9865-19a1f44d31c8.png

**Comment by LaCh0uine** [comment]
Good job
