### ISSUE TITLE
Sprint Zone

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#823]
**App Name:** Sprint Zone
**Bundle ID:** com.sprint.psd.zone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=491126018">491126018</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sprint-zone/id491126018?mt=8&uo=4">https://itunes.apple.com/us/app/sprint-zone/id491126018?mt=8&uo=4</a>
**App Version:** 5.6.4
**Seller:** Sprint Nextel Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sprint/id490227820?uo=4>© Sprint</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/0b/ab/54/0bab5450-4671-d7a2-98bc-12136a937d57/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409299/4156ff94-92d1-11e6-9c0f-e9a96d079ed1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409299/4156ff94-92d1-11e6-9c0f-e9a96d079ed1.png)
https://cloud.githubusercontent.com/assets/20930745/19409299/4156ff94-92d1-11e6-9c0f-e9a96d079ed1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409306/555ab454-92d1-11e6-8d80-d73f81398edd.png
