### ISSUE TITLE
AIR MILES® Reward Program

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8230]
**App Name:** AIR MILES® Reward Program
**Bundle ID:** com.loyaltyone.airmiles
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388705262">388705262</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/air-miles-reward-program/id388705262?mt=8&uo=4">https://itunes.apple.com/ca/app/air-miles-reward-program/id388705262?mt=8&uo=4</a>
**App Version:** 2.900
**Seller:** LoyaltyOne Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/ca/developer/loyaltyone/id388705266?uo=4>© LoyaltyOne</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/cc/0e/d6/cc0ed6a4-f47c-1fd3-aae0-8e58ed0da22d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19220922/023920fe-8e39-11e6-86d6-3d4c484ebd1c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220760/00658d52-8e35-11e6-811f-ca98d95db550.png)
https://cloud.githubusercontent.com/assets/20930745/19220760/00658d52-8e35-11e6-811f-ca98d95db550.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19220765/11cfe862-8e35-11e6-8852-2e69605d4041.png

**Comment by Trubbel** [comment]
@2Qt2beStr8 What about without the background?

**Comment by 2Qt2beStr8** [comment]
i make two versions :-)... second is still on work

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220885/0df0e414-8e38-11e6-9004-670baf3a4ada.png)
https://cloud.githubusercontent.com/assets/20930745/19220885/0df0e414-8e38-11e6-9004-670baf3a4ada.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19220890/26f49fdc-8e38-11e6-974f-8fe7ac5953e1.png

**Comment by Trubbel** [comment]
Modified your source, keeping the original size.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19220922/023920fe-8e39-11e6-86d6-3d4c484ebd1c.png)
https://cloud.githubusercontent.com/assets/10730122/19220922/023920fe-8e39-11e6-86d6-3d4c484ebd1c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19220921/021e2a7e-8e39-11e6-8b41-06ff01c841a9.png

**Comment by LaCh0uine** [comment]
Yeah better without background but I don't see the difference of the @Trudel version

**Comment by 2Qt2beStr8** [comment]
Trubbel's version is only smaller ... i don't know why i createt the wrong size ... i made all icons on the same way

**Comment by LaCh0uine** [comment]
Ok anyway both is good, your choice now

**Comment by Trubbel** [comment]
@LaCh0uine I made the icon centered, so it will look better on your SpringBoard.

![asdasdasd](https://cloud.githubusercontent.com/assets/10730122/19221401/2a5eb2ba-8e43-11e6-9c9c-af3b6536b4fc.png)

**Comment by LaCh0uine** [comment]
If it's better that good body ;)
I have anemone on my old iPhone anyway I just help the old theme I use some years
