### ISSUE TITLE
TekstiTV Finland

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8231]
**App Name:** TekstiTV Finland
**Bundle ID:** fi.jhi.TekstiTV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=858895178">858895178</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tekstitv-finland/id858895178?mt=8&uo=4">https://itunes.apple.com/us/app/tekstitv-finland/id858895178?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Joni Hietala
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/joni-hietala/id748613972?uo=4>© Joni Hietala</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/ef/96/2a/ef962a94-bfd9-a96c-d9f6-d6cc1e74441c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220561/59c29d18-8e30-11e6-931b-6362f319108d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220561/59c29d18-8e30-11e6-931b-6362f319108d.png)
https://cloud.githubusercontent.com/assets/20930745/19220561/59c29d18-8e30-11e6-931b-6362f319108d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19220565/6b231420-8e30-11e6-9111-255f1b1582d9.png
