### ISSUE TITLE
Discount Calculator

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8232]
**App Name:** Discount Calculator
**Bundle ID:** com.rocknrollabs.Discount-Calculator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=768615294">768615294</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/discount-calculator/id768615294?mt=8&uo=4">https://itunes.apple.com/us/app/discount-calculator/id768615294?mt=8&uo=4</a>
**App Version:** 1
**Seller:** Pablo Verd Gallego
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pablo-verd-gallego/id501402908?uo=4>© Pablo Verd Gallego</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/fa/7d/39/fa7d398e-066f-5471-c572-14376bf16c40/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220582/ffad1f82-8e30-11e6-9b9e-87e5563df79f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220582/ffad1f82-8e30-11e6-9b9e-87e5563df79f.png)
https://cloud.githubusercontent.com/assets/20930745/19220582/ffad1f82-8e30-11e6-9b9e-87e5563df79f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19220587/0f0e4000-8e31-11e6-9883-fb90d34a6c88.png
