### ISSUE TITLE
Matkakortti

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8233]
**App Name:** Matkakortti
**Bundle ID:** im.teemu.matkakortti
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=977912434">977912434</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fi/app/matkakortti/id977912434?mt=8&uo=4">https://itunes.apple.com/fi/app/matkakortti/id977912434?mt=8&uo=4</a>
**App Version:** 1.2.4
**Seller:** Teemu Harju
**Developer:** <a target="_blank" href=https://itunes.apple.com/fi/developer/teemu-harju/id977912433?uo=4>© Teemu Harju</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/9a/d0/b1/9ad0b17e-e996-c740-360a-3d83d2be8bf5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220613/9a5e823c-8e31-11e6-96ab-7b82acc1f72f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220613/9a5e823c-8e31-11e6-96ab-7b82acc1f72f.png)
https://cloud.githubusercontent.com/assets/20930745/19220613/9a5e823c-8e31-11e6-96ab-7b82acc1f72f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19220618/a96b0bf6-8e31-11e6-9384-21ae3c1c8b00.png
