### ISSUE TITLE
MobilePay FI

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8234]
**App Name:** MobilePay FI
**Bundle ID:** com.danskebank.mobilepay.fi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=768172577">768172577</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobilepay-fi/id768172577?mt=8&uo=4">https://itunes.apple.com/us/app/mobilepay-fi/id768172577?mt=8&uo=4</a>
**App Version:** 2.14.0
**Seller:** Danske Bank Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/danske-bank-group/id388423465?uo=4>© Danske Bank Group</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/b2/99/84/b2998407-4e45-b6f1-1971-ed19ac6f201a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220637/10b4e534-8e32-11e6-8925-7ea17a276054.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220637/10b4e534-8e32-11e6-8925-7ea17a276054.png)
https://cloud.githubusercontent.com/assets/20930745/19220637/10b4e534-8e32-11e6-8925-7ea17a276054.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19220641/208b7f68-8e32-11e6-8726-81452b8a989e.png
