### ISSUE TITLE
LiveTulokset.com

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8235]
**App Name:** LiveTulokset.com
**Bundle ID:** eu.livesport.LiveTulokset-com
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=767384328">767384328</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/cz/app/livetulokset.com/id767384328?mt=8&uo=4">https://itunes.apple.com/cz/app/livetulokset.com/id767384328?mt=8&uo=4</a>
**App Version:** 2.7.1
**Seller:** Livesport s.r.o.
**Developer:** <a target="_blank" href=https://itunes.apple.com/cz/developer/livesport-s.r.o./id722265281?uo=4>© Livesport s.r.o.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/7a/b8/61/7ab86131-cce7-7811-24ed-9f029d613520/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19221722/0b17b342-8e49-11e6-8a33-7db6bb611e57.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220675/4a62e9e2-8e33-11e6-9e37-de28c949e7e8.png)
https://cloud.githubusercontent.com/assets/20930745/19220675/4a62e9e2-8e33-11e6-9e37-de28c949e7e8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19220679/5f17161a-8e33-11e6-8a37-965c223b3cd4.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19221678/70c31458-8e48-11e6-8553-5a0058a4a30a.png)
https://cloud.githubusercontent.com/assets/20930745/19221678/70c31458-8e48-11e6-8553-5a0058a4a30a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19221681/7dc76e60-8e48-11e6-8667-37f02dbc3685.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 First one is OK, I'm just centering it (like #8230):
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19221722/0b17b342-8e49-11e6-8a33-7db6bb611e57.png)
https://cloud.githubusercontent.com/assets/2068130/19221722/0b17b342-8e49-11e6-8a33-7db6bb611e57.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19221731/1a96c95c-8e49-11e6-92f4-2bc1be0de5fa.png

**Comment by Anuskuss** [comment]
Same icon as #6682?

**Comment by dreamnet** [comment]
@Anuskuss Yes...

**Comment by Anuskuss** [comment]
@dreamnet Why not use the same source then?

**Comment by dreamnet** [comment]
@Anuskuss OK.
