### ISSUE TITLE
iUutiset

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8236]
**App Name:** iUutiset
**Bundle ID:** com.pointabout.43071
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=379866161">379866161</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/iuutiset/id379866161?mt=8&uo=4">https://itunes.apple.com/us/app/iuutiset/id379866161?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Esmes Digital Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/esmes-digital-oy/id379866164?uo=4>© Esmes Digital Oy</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/91/ed/ae/91edae14-f153-c381-6259-7f9000c7bd75/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220697/c28c433c-8e33-11e6-9f94-56cd2215d5b0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19220697/c28c433c-8e33-11e6-9f94-56cd2215d5b0.png)
https://cloud.githubusercontent.com/assets/20930745/19220697/c28c433c-8e33-11e6-9f94-56cd2215d5b0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19220700/d22e44f2-8e33-11e6-8715-8368e729378c.png
