### ISSUE TITLE
Air Matters: Global Air Quality & Pollen Data

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8238]
**App Name:** Air Matters: Global Air Quality & Pollen Data
**Bundle ID:** fresh-ideas.DirtyBeijing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=477700080">477700080</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/air-matters-global-air-quality/id477700080?mt=8&uo=4">https://itunes.apple.com/us/app/air-matters-global-air-quality/id477700080?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** Bin Zhang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/freshideas-studio/id477700083?uo=4>© FreshIdeas Studio</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/1b/3e/1b/1b3e1bd7-3c9e-a6f5-02ad-f337f7167b18/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19221247/e8969346-8e3f-11e6-9c9e-e3ff9721a09b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19221247/e8969346-8e3f-11e6-9c9e-e3ff9721a09b.png)
https://cloud.githubusercontent.com/assets/20930745/19221247/e8969346-8e3f-11e6-9c9e-e3ff9721a09b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19221248/f69007a2-8e3f-11e6-9c1f-2830602848f4.png
