### ISSUE TITLE
DK Live – Fantasy Sports Play by Play and News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8242]
**App Name:** DK Live – Fantasy Sports Play by Play and News
**Bundle ID:** com.draftkings.DKLiveApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1142334232">1142334232</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dk-live-fantasy-sports-play/id1142334232?mt=8&uo=4">https://itunes.apple.com/us/app/dk-live-fantasy-sports-play/id1142334232?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** DRAFTKINGS LLC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/draftkings/id544448370?uo=4>© DraftKings</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/10/f1/72/10f17234-a27b-05f0-c586-08287eead6ad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19223178/be503de2-8e69-11e6-9af1-83d87c72d058.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19223178/be503de2-8e69-11e6-9af1-83d87c72d058.png)
https://cloud.githubusercontent.com/assets/20930745/19223178/be503de2-8e69-11e6-9af1-83d87c72d058.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19223179/cfae8f30-8e69-11e6-95c1-a7395d4095ae.png
