### ISSUE TITLE
Kinsa Smart Thermometer & Health Tracker

### ISSUE THREAD

**Issue by spiroscc** [glasklart/hd#8246]
**App Name:** Kinsa Smart Thermometer & Health Tracker
**Bundle ID:** com.kinsahealth.kinsa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=788719884">788719884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kinsa-smart-thermometer-health/id788719884?mt=8&uo=4">https://itunes.apple.com/us/app/kinsa-smart-thermometer-health/id788719884?mt=8&uo=4</a>
**App Version:** 4.2.1
**Seller:** Transform Health Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kinsa/id685593253?uo=4>© Kinsa</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/e4/71/04/e4710401-77ed-280f-8c75-c0b9595b7ac0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19228745/5a558f18-8ec8-11e6-9c43-03e0553104f1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19228745/5a558f18-8ec8-11e6-9c43-03e0553104f1.png)
https://cloud.githubusercontent.com/assets/20930745/19228745/5a558f18-8ec8-11e6-9c43-03e0553104f1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19228748/6915bb22-8ec8-11e6-9efe-f56a2b3f0e2a.png
