### ISSUE TITLE
Polaroid Swing

### ISSUE THREAD

**Issue by spiroscc** [glasklart/hd#8247]
**App Name:** Polaroid Swing
**Bundle ID:** io.polaroid.Polaroid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035142291">1035142291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/polaroid-swing/id1035142291?mt=8&uo=4">https://itunes.apple.com/us/app/polaroid-swing/id1035142291?mt=8&uo=4</a>
**App Version:** 1.2.4
**Seller:** Grasscrown, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/polaroid/id1035142290?uo=4>© Polaroid</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/01/65/3c/01653c83-e529-8a82-fcdf-9a7fad611b62/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19228674/bd56a9d6-8ec7-11e6-8c08-818f501fdd69.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19228674/bd56a9d6-8ec7-11e6-8c08-818f501fdd69.png)
https://cloud.githubusercontent.com/assets/20930745/19228674/bd56a9d6-8ec7-11e6-8c08-818f501fdd69.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19228683/cf80b7dc-8ec7-11e6-817c-16d92368913d.png
