### ISSUE TITLE
Caesars Rewards

### ISSUE THREAD

**Issue by spiroscc** [glasklart/hd#8248]
**App Name:** Caesars Rewards
**Bundle ID:** com.caesars.playbytr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=720839830">720839830</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/caesars-rewards/id720839830?uo=4">https://apps.apple.com/us/app/caesars-rewards/id720839830?uo=4</a>
**App Version:** 6.0.4
**Seller:** Caesars Entertainment Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/caesars-entertainment-corporation/id330346954?uo=4">© Caesars Entertainment Corporation</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/f5/19/ba/f519baea-9dac-5586-fb87-096c2a0eb1dc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380380-faf00b80-9a44-11e9-9e01-7c7baf898805.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19228531/6fa423f4-8ec6-11e6-82c3-e0be66c58201.png)
https://cloud.githubusercontent.com/assets/20930745/19228531/6fa423f4-8ec6-11e6-82c3-e0be66c58201.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19228542/82df0510-8ec6-11e6-83a0-653f62368a9c.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380380-faf00b80-9a44-11e9-9e01-7c7baf898805.png)
https://user-images.githubusercontent.com/20930745/60380380-faf00b80-9a44-11e9-9e01-7c7baf898805.png

Source:
https://user-images.githubusercontent.com/20930745/60380381-fdeafc00-9a44-11e9-8d7e-9d694216d75f.png
