### ISSUE TITLE
StudyBlue - Online Flashcards and Study Guide App

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#825]
**App Name:** StudyBlue - Online Flashcards and Study Guide App
**Bundle ID:** com.yourcompany.StudyBlue
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=323887414">323887414</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/studyblue-online-flashcards/id323887414?mt=8&uo=4">https://itunes.apple.com/us/app/studyblue-online-flashcards/id323887414?mt=8&uo=4</a>
**App Version:** 23.1
**Seller:** StudyBlue, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/studyblue-inc./id323887417?uo=4>© StudyBlue, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/b5/b4/d4/b5b4d459-904c-5dde-3b54-62c13a1fb563/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409365/d5253348-92d2-11e6-8f78-80f36f98792b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409365/d5253348-92d2-11e6-8f78-80f36f98792b.png)
https://cloud.githubusercontent.com/assets/20930745/19409365/d5253348-92d2-11e6-8f78-80f36f98792b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409367/e6939fac-92d2-11e6-9fae-520a4c082f42.png
