### ISSUE TITLE
CBC Radio

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8250]
**App Name:** CBC Radio
**Bundle ID:** ca.cbc.CBCRadio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=325946767">325946767</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cbc-radio/id325946767?mt=8&uo=4">https://itunes.apple.com/us/app/cbc-radio/id325946767?mt=8&uo=4</a>
**App Version:** 3.1.7
**Seller:** CANADIAN BROADCASTING CORPORATION
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cbc/id325946770?uo=4>© CBC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/1d/0e/bc/1d0ebc6a-88bd-f0a9-d02b-2ad58f8b448e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19234040/85290d70-8ee9-11e6-8edf-5f9f5e2db149.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19234040/85290d70-8ee9-11e6-8edf-5f9f5e2db149.png)
https://cloud.githubusercontent.com/assets/20930745/19234040/85290d70-8ee9-11e6-8edf-5f9f5e2db149.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19234066/9eafd1d4-8ee9-11e6-8536-82aa280be119.png

**Comment by dreamnet** [comment]
Same as #8120.
