### ISSUE TITLE
INKS.

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8252]
**App Name:** INKS.
**Bundle ID:** com.stateofplaygames.inkball
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1081847121">1081847121</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inks./id1081847121?mt=8&uo=4">https://itunes.apple.com/us/app/inks./id1081847121?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** State of Play Games Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/state-of-play-games/id494615574?uo=4>© State of Play Games</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/ce/9d/81/ce9d81ae-38f0-0542-2c4d-8b2bc15587bd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19314109/39b9641e-9099-11e6-9f46-b35c6bf66792.png)

**Comment by 2Qt2beStr8** [comment]
@LaCh0uine ... i have no idea how to create this icon ... what do you think about something like this ... or have you any other ideas?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19314109/39b9641e-9099-11e6-9f46-b35c6bf66792.png)
https://cloud.githubusercontent.com/assets/20930745/19314109/39b9641e-9099-11e6-9f46-b35c6bf66792.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19314124/4a2d0152-9099-11e6-8d76-79a6cf3f6878.png

**Comment by LaCh0uine** [comment]
I like it 👍🏻👍🏻
