### ISSUE TITLE
CAMARAD - Speed radars and red light cameras alert

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8253]
**App Name:** CAMARAD - Speed radars and red light cameras alert
**Bundle ID:** com.qgpradier.camarad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1128904595">1128904595</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camarad-speed-radars-red-light/id1128904595?mt=8&uo=4">https://itunes.apple.com/us/app/camarad-speed-radars-red-light/id1128904595?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Patrick Boulay
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/patrick-boulay/id1128904594?uo=4>© Patrick Boulay</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/4c/9f/06/4c9f0644-0da8-c595-c6fd-82a7bcb4f9ca/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19235294/29e21abc-8ef1-11e6-9f4e-f1feb9ecad03.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19235294/29e21abc-8ef1-11e6-9f4e-f1feb9ecad03.png)
https://cloud.githubusercontent.com/assets/20930745/19235294/29e21abc-8ef1-11e6-9f4e-f1feb9ecad03.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19235306/39c34b40-8ef1-11e6-9eba-395a4b42b54c.png
