### ISSUE TITLE
1010 Cool World!

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8254]
**App Name:** 1010 Cool World!
**Bundle ID:** com.puzzle1010
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1028789191">1028789191</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1010-cool-world!/id1028789191?mt=8&uo=4">https://itunes.apple.com/us/app/1010-cool-world!/id1028789191?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Bo XiaoNi
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bo-xiaoni/id824146232?uo=4>© Bo XiaoNi</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/03/70/18/03701859-8ca8-eb2c-71ea-fb2bfd45905b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19416046/e3872474-9385-11e6-83fc-fab703bddc3a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19416046/e3872474-9385-11e6-83fc-fab703bddc3a.png)
https://cloud.githubusercontent.com/assets/2068130/19416046/e3872474-9385-11e6-83fc-fab703bddc3a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19416048/f2584992-9385-11e6-9290-6074b3c71eb9.png
