### ISSUE TITLE
Bria iPhone Edition - VoIP Softphone SIP Client

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8259]
**App Name:** Bria iPhone Edition - VoIP Softphone SIP Client
**Bundle ID:** com.counterpath.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=373968636">373968636</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bria-iphone-edition-voip-softphone/id373968636?mt=8&uo=4">https://itunes.apple.com/us/app/bria-iphone-edition-voip-softphone/id373968636?mt=8&uo=4</a>
**App Version:** 3.7.2
**Seller:** CounterPath Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/counterpath-corporation/id371558066?uo=4>© CounterPath Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/6d/5e/40/6d5e40d3-37c3-2274-256d-1ff449ad9800/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19236171/59c1ed5c-8ef6-11e6-8911-896212714b78.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19236273/bebc5350-8ef6-11e6-9c4e-343c949191a0.png)
https://cloud.githubusercontent.com/assets/20930745/19236273/bebc5350-8ef6-11e6-9c4e-343c949191a0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19236286/ce976af8-8ef6-11e6-94cc-e6fbeb2edc7e.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Fist one is just fine! 👍
