### ISSUE TITLE
Première Cinéma – Retrouvez toute l’actualité ciné, les horaires des séances et les bandes-annonces des films à ne pas rater !

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#826]
**App Name:** Première Cinéma – Retrouvez toute l’actualité ciné, les horaires des séances et les bandes-annonces des films à ne pas rater !
**Bundle ID:** com.lagardere.premiere
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=298662968">298662968</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/premiere-cinema-retrouvez/id298662968?mt=8&uo=4">https://itunes.apple.com/us/app/premiere-cinema-retrouvez/id298662968?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** PREMIERE 1 3
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/premiere-sas/id997747556?uo=4>© Première SAS</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/cc/c3/31/ccc33127-b6ce-5507-c2ef-3a88dc288249/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409450/1986ca6e-92d4-11e6-9134-99fcfef14e6b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409441/f9f5e90a-92d3-11e6-83db-c7e262e60590.png)
https://cloud.githubusercontent.com/assets/20930745/19409441/f9f5e90a-92d3-11e6-83db-c7e262e60590.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409446/0ad6f052-92d4-11e6-9615-b4007f8a3506.png
