### ISSUE TITLE
Echofon Pro for Twitter

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8263]
**App Name:** Echofon Pro for Twitter
**Bundle ID:** net.naan.TwitterFonPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=315577859">315577859</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/echofon-pro-for-twitter/id315577859?mt=8&uo=4">https://itunes.apple.com/us/app/echofon-pro-for-twitter/id315577859?mt=8&uo=4</a>
**App Version:** 10.0.2
**Seller:** Ubermedia, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ubermedia-inc./id396050122?uo=4>© Ubermedia, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/c8/d8/20/c8d82085-46b7-1fb7-6bc8-573a367bf838/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18618879/b9c69576-7dbd-11e6-8a74-0989fb3962c0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19236998/b728f0ae-8efa-11e6-971d-46003ed9176a.png)
https://cloud.githubusercontent.com/assets/20930745/19236998/b728f0ae-8efa-11e6-971d-46003ed9176a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19237010/c5e04f52-8efa-11e6-8a5a-c35ceecfff89.png

**Comment by Trubbel** [comment]
Same as #8025.
