### ISSUE TITLE
ComicGlass [ComicReader]

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#827]
**App Name:** ComicGlass [ComicReader]
**Bundle ID:** net.ryusuke.comicglass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=363992049">363992049</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/comicglass-comicreader/id363992049?mt=8&uo=4">https://itunes.apple.com/us/app/comicglass-comicreader/id363992049?mt=8&uo=4</a>
**App Version:** 9.05
**Seller:** Ryusuke Hotta
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rr-soft/id363992052?uo=4>© RR Soft</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/f8/4e/25/f84e2557-da74-f329-2dd8-3e1805e9acd4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409527/99dd6064-92d5-11e6-93c1-527c5231cce3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409517/74e73d2a-92d5-11e6-9fa4-9df43ca88102.png)
https://cloud.githubusercontent.com/assets/20930745/19409517/74e73d2a-92d5-11e6-9fa4-9df43ca88102.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409523/8a04e5f4-92d5-11e6-9ebd-678f3cf74565.png
