### ISSUE TITLE
Hotham

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8271]
**App Name:** Hotham
**Bundle ID:** com.resortstapped.HothamTapped
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438107304">438107304</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hotham/id438107304?mt=8&uo=4">https://itunes.apple.com/us/app/hotham/id438107304?mt=8&uo=4</a>
**App Version:** 6.1
**Seller:** Resorts Tapped LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/resorts-tapped-llc/id306904495?uo=4>© Resorts Tapped LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/7b/60/2e/7b602e48-7377-c46b-5bef-056b177755f9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19239061/b56267e6-8f04-11e6-9d28-c591ab302463.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19239061/b56267e6-8f04-11e6-9d28-c591ab302463.png)
https://cloud.githubusercontent.com/assets/20930745/19239061/b56267e6-8f04-11e6-9d28-c591ab302463.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19239075/c32bd538-8f04-11e6-9615-be1eb169fa45.png

**Comment by LaCh0uine** [comment]
why you don't keep the name inside?

**Comment by 2Qt2beStr8** [comment]
... because the name of the app is visible under the icon on your springboard

**Comment by LaCh0uine** [comment]
@2Qt2beStr8 maybe you, not me if my phone is jailbreaked ;)
with a theme like Glasklart sometime is good have name in icon everything is gray lol

**Comment by 2Qt2beStr8** [comment]
@LaCh0uine ... if you want this icon with the name inside, i will make it for you

**Comment by LaCh0uine** [comment]
I just find it better like original.. I don't use this app anyway .. just give my opinion that's it
