### ISSUE TITLE
Tacts: Smart Contact Manager, Group Text & Email and Favorites

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8274]
**App Name:** Tacts: Smart Contact Manager, Group Text & Email and Favorites
**Bundle ID:** com.terntek.TactsGM
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=381051998">381051998</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tacts-smart-contact-manager/id381051998?mt=8&uo=4">https://itunes.apple.com/us/app/tacts-smart-contact-manager/id381051998?mt=8&uo=4</a>
**App Version:** 1.6.1
**Seller:** May Art Collections Enterprises Co., Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/terntek-mayart/id381052001?uo=4>© TernTek MayArt</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/7e/fa/2d/7efa2d5d-a715-0aee-6e4f-e1ed94cce5e4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19243530/43367e32-8f18-11e6-9ec3-8f24df6a531e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19243530/43367e32-8f18-11e6-9ec3-8f24df6a531e.png)
https://cloud.githubusercontent.com/assets/20930745/19243530/43367e32-8f18-11e6-9ec3-8f24df6a531e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19243554/545ba3a4-8f18-11e6-9451-8b63c0337da4.png

**Comment by xbliss** [comment]
Is there a way to still get this App?

**Comment by dreamnet** [comment]
@xbliss You can try to get it with AppCake.
