### ISSUE TITLE
Facebook Local

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8281]
**App Name:** Facebook Local
**Bundle ID:** com.facebook.Socal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1153443320">1153443320</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facebook-local/id1153443320?mt=8&uo=4">https://itunes.apple.com/us/app/facebook-local/id1153443320?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/facebook-inc/id284882218?uo=4">© Facebook, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/5b/e3/5a/5be35af6-f2ef-5267-8c5f-f091415f20e1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34391911-05612470-eb49-11e7-9092-e117336a653a.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19251828/a62a5a6c-8f41-11e6-97f2-ee413c96d760.png)
https://cloud.githubusercontent.com/assets/10730122/19251828/a62a5a6c-8f41-11e6-97f2-ee413c96d760.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19251827/a62846f0-8f41-11e6-9f0c-dc86ce2e75e5.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19251844/bbd43180-8f41-11e6-918e-52da612a17cc.png)
https://cloud.githubusercontent.com/assets/10730122/19251844/bbd43180-8f41-11e6-918e-52da612a17cc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19251843/bbba5422-8f41-11e6-92b8-d3a8aabbb481.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Facebook Local
**Bundle ID:** com.facebook.Socal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1153443320">1153443320</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facebook-local/id1153443320?mt=8&uo=4">https://itunes.apple.com/us/app/facebook-local/id1153443320?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** Facebook, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/facebook-inc/id284882218?uo=4">© Facebook, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/5b/e3/5a/5be35af6-f2ef-5267-8c5f-f091415f20e1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34391911-05612470-eb49-11e7-9092-e117336a653a.png)
https://user-images.githubusercontent.com/2068130/34391911-05612470-eb49-11e7-9092-e117336a653a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34391914-1343951e-eb49-11e7-956b-0d628171ec64.png
