### ISSUE TITLE
Apps Manager

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#8282]
**App Name:** [Apps Manager](http://modmyi.com/cydia/package.php?id=79320)
**Bundle ID:** com.tigisoftware.ADManager
**Version:** 1.0.2-1
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cydia.saurik.com/icon@2x/com.tigisoftware.appdatamanager.png" width="180" height="180">
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19283631/f2adaf72-8ff2-11e6-85d7-f89bc05b4758.png)

**Comment by 2Qt2beStr8** [comment]
the original artwork was to small for me - so i have created this icon by my self


![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19283631/f2adaf72-8ff2-11e6-85d7-f89bc05b4758.png)
https://cloud.githubusercontent.com/assets/20930745/19283631/f2adaf72-8ff2-11e6-85d7-f89bc05b4758.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19283650/027758c2-8ff3-11e6-8e0d-881a3f8b20bf.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Perfetto! 👍

**Comment by Checkit23** [comment]
The BundleID you guys used is incorrect, it's actually com.tigisoftware.ADManager
