### ISSUE TITLE
Appie van Albert Heijn

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8286]
**App Name:** Appie van Albert Heijn
**Bundle ID:** nl.ah.Appie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=327535329">327535329</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/appie-van-albert-heijn/id327535329?uo=4">https://apps.apple.com/us/app/appie-van-albert-heijn/id327535329?uo=4</a>
**App Version:** 6.12
**Seller:** Albert Heijn B.V.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/albert-heijn/id542198840?uo=4">© Albert Heijn</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/b4/f8/04/b4f804f4-1809-3e42-e26e-f1911d52e6f7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979146-0f1aaf80-95e4-11e9-881c-8fa3cecd88d7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19280350/c0be9024-8fe5-11e6-80d2-b6ce442ae3cd.png)
https://cloud.githubusercontent.com/assets/20930745/19280350/c0be9024-8fe5-11e6-80d2-b6ce442ae3cd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19280362/d09520da-8fe5-11e6-9a0b-f1c743c6c51b.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979146-0f1aaf80-95e4-11e9-881c-8fa3cecd88d7.png)
https://user-images.githubusercontent.com/2068130/59979146-0f1aaf80-95e4-11e9-881c-8fa3cecd88d7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979149-1d68cb80-95e4-11e9-926e-4c10d7088874.png
