### ISSUE TITLE
Arclight Cinemas

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#829]
**App Name:** Arclight Cinemas
**Bundle ID:** nz.co.vista.VistaAppArclight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417329910">417329910</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/arclight-cinemas/id417329910?mt=8&uo=4">https://itunes.apple.com/us/app/arclight-cinemas/id417329910?mt=8&uo=4</a>
**App Version:** 4.5.5.1
**Seller:** ARCLIGHT CINEMA COMPANY
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/arclight-cinema-company/id1101460841?uo=4>© Arclight Cinema Company</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/ab/a0/41/aba0414f-bfaf-9207-6ebe-d854e36967d4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409586/41dc341a-92d7-11e6-96b2-031c658a4566.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409586/41dc341a-92d7-11e6-96b2-031c658a4566.png)
https://cloud.githubusercontent.com/assets/20930745/19409586/41dc341a-92d7-11e6-96b2-031c658a4566.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409587/4f89c6ae-92d7-11e6-8578-bd46a3239033.png
