### ISSUE TITLE
Kelda

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8290]
**App Name:** Kelda
**Bundle ID:** se.arla.KeldaFemtonMinRecept
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=351886387">351886387</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/kelda/id351886387?mt=8&uo=4">https://itunes.apple.com/se/app/kelda/id351886387?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Nils Andersson
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/developer/arla-foods/id351886390?uo=4>© Arla Foods</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/5a/8b/3b/5a8b3bab-e7f7-a82d-4340-b2429c76f1af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19300468/b6a7ec0a-905a-11e6-923e-b70c7176fece.png)

**Comment by dreamnet** [comment]
@2Qt2beStr8 Um, this one needs to be pushed to the bottom like the original icon.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19300441/91468818-905a-11e6-87b6-2bf16cb64978.png


Source:
https://cloud.githubusercontent.com/assets/20930745/19300424/84758e86-905a-11e6-80ea-db2c2a391d83.png
