### ISSUE TITLE
Bleacher Report: Sports news, scores, & highlights

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8291]
**App Name:** Bleacher Report: Sports news, scores, & highlights
**Bundle ID:** com.bleacherreport.TeamStream
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418075935">418075935</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bleacher-report-sports-news-scores-highlights/id418075935?mt=8&uo=4">https://itunes.apple.com/us/app/bleacher-report-sports-news-scores-highlights/id418075935?mt=8&uo=4</a>
**App Version:** 5.4.1
**Seller:** Bleacher Report
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bleacher-report/id418075938?uo=4">© Bleacher Report</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/1b/ea/e7/1beae7d5-a1f5-c81e-3f40-dc08eddc8444/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29771043-2dfa8f04-8bf2-11e7-92ce-bee7d3f33428.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19286894/d10719f0-8fff-11e6-983c-47123f1cbdc0.png)
https://cloud.githubusercontent.com/assets/20930745/19286894/d10719f0-8fff-11e6-983c-47123f1cbdc0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19286910/e0a40594-8fff-11e6-8448-ea6fc1a30526.png

**Comment by l8er4now** [comment]
Needs to be updated.

**App Name:** Bleacher Report: Sports news, scores, & highlights
**Bundle ID:** com.bleacherreport.TeamStream
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418075935">418075935</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bleacher-report-sports-news-scores-highlights/id418075935?mt=8&uo=4">https://itunes.apple.com/us/app/bleacher-report-sports-news-scores-highlights/id418075935?mt=8&uo=4</a>
**App Version:** 5.4.1
**Seller:** Bleacher Report
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bleacher-report/id418075938?uo=4">© Bleacher Report</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/1b/ea/e7/1beae7d5-a1f5-c81e-3f40-dc08eddc8444/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29771043-2dfa8f04-8bf2-11e7-92ce-bee7d3f33428.png)
https://user-images.githubusercontent.com/20930745/29771043-2dfa8f04-8bf2-11e7-92ce-bee7d3f33428.png

Source:
https://user-images.githubusercontent.com/20930745/29771059-42ca6454-8bf2-11e7-8b51-a3eed768a56f.png
