### ISSUE TITLE
Hesperus

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8292]
**App Name:** Hesperus
**Bundle ID:** org.oltica.Hesperus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=969348892">969348892</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hesperus/id969348892?mt=8&uo=4">https://itunes.apple.com/us/app/hesperus/id969348892?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Tian Zhang
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/oltica/id432739189?uo=4>© Oltica</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/e7/7f/12/e77f12ad-de93-69ec-228d-c8227e8a9ff9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19287664/fe3c18aa-9002-11e6-9364-0731b9b3d0bb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19287664/fe3c18aa-9002-11e6-9364-0731b9b3d0bb.png)
https://cloud.githubusercontent.com/assets/20930745/19287664/fe3c18aa-9002-11e6-9364-0731b9b3d0bb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19287674/0a375d54-9003-11e6-979d-6bde67dc8890.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... why i can't find this app on your website?

**Comment by dreamnet** [comment]
@2Qt2beStr8 Because It's not added yet. You can add it if you want (The Icons -> Add App, Copy the iTunes ID to the iTues ID field on the right side and klick on "Grab App Data". Don't forget to enter the issue number. Then click on "Save app data".).
