### ISSUE TITLE
Moonpig USA - Send Personalized Greeting Cards

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8293]
**App Name:** Moonpig USA - Send Personalized Greeting Cards
**Bundle ID:** com.commonagency.moonpigus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431088320">431088320</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moonpig-usa-send-personalized/id431088320?mt=8&uo=4">https://itunes.apple.com/us/app/moonpig-usa-send-personalized/id431088320?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** Moonpig.com Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/moonpig.com/id895116922?uo=4>© Moonpig.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/35/b8/a0/35b8a0f9-49a6-87e7-86d4-c1739de4a8b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19289351/9a9db53a-900a-11e6-948c-d302c09a007b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19289351/9a9db53a-900a-11e6-948c-d302c09a007b.png)
https://cloud.githubusercontent.com/assets/20930745/19289351/9a9db53a-900a-11e6-948c-d302c09a007b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19289368/aa5316be-900a-11e6-8801-151be831b5ac.png

**Comment by dreamnet** [comment]
Same as #1760.
