### ISSUE TITLE
RemoteX Premium - Control 18 Media Players and Your PC.

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8294]
**App Name:** RemoteX Premium - Control 18 Media Players and Your PC.
**Bundle ID:** com.peepleware.remotex
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405831259">405831259</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/remotex-premium-control-18/id405831259?mt=8&uo=4">https://itunes.apple.com/us/app/remotex-premium-control-18/id405831259?mt=8&uo=4</a>
**App Version:** 3.2.1
**Seller:** PEEPLEware
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/peepleware/id395878392?uo=4>© Peepleware</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/e2/60/e3/e260e38a-e66a-628b-e46c-7de9d28a7bb7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19305163/06ee3894-9070-11e6-9deb-bb7dcfb17547.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19305163/06ee3894-9070-11e6-9deb-bb7dcfb17547.png)
https://cloud.githubusercontent.com/assets/20930745/19305163/06ee3894-9070-11e6-9deb-bb7dcfb17547.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19305194/244d6d2e-9070-11e6-9937-a0974024ee64.png
