### ISSUE TITLE
CarPlay iOS

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8296]
**App Name:** CarPlay iOS
 **Bundle ID:** com.j290.CarPlay
 **Version:** 2.0.1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://pbs.twimg.com/profile_images/731065446397558784/HqAvmWZG.jpg" width="180" height="180" />
 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19309629/75b663ee-9086-11e6-9c05-0c7385315a06.png)

**Comment by Anonyymikko** [comment]
https://pbs.twimg.com/profile_images/731065446397558784/HqAvmWZG.jpg

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19309629/75b663ee-9086-11e6-9c05-0c7385315a06.png)
https://cloud.githubusercontent.com/assets/20930745/19309629/75b663ee-9086-11e6-9c05-0c7385315a06.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19309642/877ceb8e-9086-11e6-88e3-4e15e050a923.png
