### ISSUE TITLE
112 Suomi

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8297]
**App Name:** 112 Suomi
**Bundle ID:** fi.digia.suomi112
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=998281396">998281396</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/112-suomi/id998281396?mt=8&uo=4">https://itunes.apple.com/us/app/112-suomi/id998281396?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** Digia Plc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/digia-plc/id300197821?uo=4>© Digia Plc</a>
**Supported Devices:** iPhone-3GS, iPad3G, iPhone4, iPad23G, iPhone4S, iPadThirdGen4G, iPhone5, iPadFourthGen4G, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple32/v4/3a/1e/58/3a1e5837-2a66-2544-6cf4-598cebae7708/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19306052/18e1f53c-9074-11e6-97c4-5d7159c667f5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19306052/18e1f53c-9074-11e6-97c4-5d7159c667f5.png)
https://cloud.githubusercontent.com/assets/20930745/19306052/18e1f53c-9074-11e6-97c4-5d7159c667f5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19306059/27dff8ae-9074-11e6-841f-0e9c04c37d86.png
