### ISSUE TITLE
Ruutu

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8298]
**App Name:** Ruutu
**Bundle ID:** com.sanomaentertainment.ruutu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=439840557">439840557</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/se/app/ruutu/id439840557?mt=8&uo=4">https://itunes.apple.com/se/app/ruutu/id439840557?mt=8&uo=4</a>
**App Version:** 5.2.1
**Seller:** Sanoma Media Finland
**Developer:** <a target="_blank" href=https://itunes.apple.com/se/developer/sanoma-media-finland/id368549040?uo=4>© Sanoma Media Finland</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/7e/31/c8/7e31c8c9-16f3-3f17-84a7-d63775ceba9b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19306225/f0bb4d1e-9074-11e6-9593-f50f33098abc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19306225/f0bb4d1e-9074-11e6-9593-f50f33098abc.png)
https://cloud.githubusercontent.com/assets/20930745/19306225/f0bb4d1e-9074-11e6-9593-f50f33098abc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19306251/13cb33a0-9075-11e6-80c7-fa87e486e411.png
