### ISSUE TITLE
MTV Katsomo

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8299]
**App Name:** MTV Katsomo
**Bundle ID:** fi.mtvkatsomo.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=778585708">778585708</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mtv-katsomo/id778585708?mt=8&uo=4">https://itunes.apple.com/us/app/mtv-katsomo/id778585708?mt=8&uo=4</a>
**App Version:** 3.1.2
**Seller:** MTV Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mtv3/id437805344?uo=4>© MTV3</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/90/2c/8e/902c8ebb-c854-2293-9385-08b4e5f69d4b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19308070/16c23690-907e-11e6-90a1-7d5786c77a4a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19308070/16c23690-907e-11e6-90a1-7d5786c77a4a.png)
https://cloud.githubusercontent.com/assets/20930745/19308070/16c23690-907e-11e6-90a1-7d5786c77a4a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19308107/3674dede-907e-11e6-9b95-055ce2d7334e.png
