### ISSUE TITLE
Hertz 24/7®

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#830]
**App Name:** Hertz 24/7®
**Bundle ID:** com.hertz.HertzOnDemand
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=536499953">536499953</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/hertz-24-7/id536499953?mt=8&uo=4">https://itunes.apple.com/gb/app/hertz-24-7/id536499953?mt=8&uo=4</a>
**App Version:** 2.10.2
**Seller:** The Hertz Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/the-hertz-corporation/id352114303?uo=4>© The Hertz Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/0b/56/40/0b56407e-b6ea-1356-e744-42f22bb9ca41/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409609/db1881b0-92d7-11e6-95d2-53e6b8dcac5c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409609/db1881b0-92d7-11e6-95d2-53e6b8dcac5c.png)
https://cloud.githubusercontent.com/assets/20930745/19409609/db1881b0-92d7-11e6-95d2-53e6b8dcac5c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409612/edbdb4ac-92d7-11e6-8848-7983c3080084.png
