### ISSUE TITLE
FOX Play

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8300]
**App Name:** FOX Play
**Bundle ID:** com.fic.foxplayeu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935379178">935379178</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fi/app/fox-play/id935379178?mt=8&uo=4">https://itunes.apple.com/fi/app/fox-play/id935379178?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Fox International Channels (UK) Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/fi/developer/fox-international-channels/id411653300?uo=4>© Fox International Channels (UK) Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/c2/1c/96/c21c960c-b4fc-c6fc-0459-7c7f7e5b3085/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19308430/d362c872-907f-11e6-8d43-a50bb42d5d2a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19308430/d362c872-907f-11e6-8d43-a50bb42d5d2a.png)
https://cloud.githubusercontent.com/assets/20930745/19308430/d362c872-907f-11e6-8d43-a50bb42d5d2a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19308449/e428a302-907f-11e6-941b-1715477fe54c.png
