### ISSUE TITLE
Pivo

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8301]
**App Name:** Pivo
**Bundle ID:** fi.pivolompakko
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=624558872">624558872</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pivo/id624558872?mt=8&uo=4">https://itunes.apple.com/us/app/pivo/id624558872?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** OP Ryhmae
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/op-ryhmae/id422607671?uo=4>© OP Ryhmae</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/e5/d9/ec/e5d9ecee-ffe8-f031-fe8a-1ba03e493921/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19307258/cc20bca0-9079-11e6-9136-352ed39ce8da.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19307258/cc20bca0-9079-11e6-9136-352ed39ce8da.png)
https://cloud.githubusercontent.com/assets/20930745/19307258/cc20bca0-9079-11e6-9136-352ed39ce8da.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19307270/d82f64a6-9079-11e6-8011-c59891e01bb3.png
