### ISSUE TITLE
EasyPark

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8302]
**App Name:** EasyPark
**Bundle ID:** net.easypark.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=449594317">449594317</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/easypark/id449594317?mt=8&uo=4">https://itunes.apple.com/us/app/easypark/id449594317?mt=8&uo=4</a>
**App Version:** 5.7.1
**Seller:** Easy Park AS
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/easypark/id449594320?uo=4>© EasyPark</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/4e/84/61/4e846124-c12b-05b1-2d0f-cd4bb6577c60/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19307389/7226ed40-907a-11e6-88d0-a62bc6d2e522.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19307389/7226ed40-907a-11e6-88d0-a62bc6d2e522.png)
https://cloud.githubusercontent.com/assets/20930745/19307389/7226ed40-907a-11e6-88d0-a62bc6d2e522.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19307395/816967e2-907a-11e6-9b58-cee09f03b31c.png
