### ISSUE TITLE
Commuter - Reittiopas ja Aikataulut

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8303]
**App Name:** Commuter - Reittiopas ja Aikataulut
**Bundle ID:** reitti.aikatauluApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=861274235">861274235</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/commuter-reittiopas-ja-aikataulut/id861274235?mt=8&uo=4">https://itunes.apple.com/us/app/commuter-reittiopas-ja-aikataulut/id861274235?mt=8&uo=4</a>
**App Version:** 5.2.1
**Seller:** Anteneh Sahledengel
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/antenehseifu/id549082184?uo=4>© AntenehSeifu</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple41/v4/4b/ae/21/4bae211b-b8cb-e987-cba1-ed21550a663b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19307881/2f620366-907d-11e6-96a2-48f5993da028.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19307881/2f620366-907d-11e6-96a2-48f5993da028.png)
https://cloud.githubusercontent.com/assets/20930745/19307881/2f620366-907d-11e6-96a2-48f5993da028.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19307905/4d7fb866-907d-11e6-9598-7a0c3fc25213.png)
