### ISSUE TITLE
Cardu

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8304]
**App Name:** Cardu
**Bundle ID:** com.mcardeurope.iPhoneClient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446737859">446737859</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cardu/id446737859?mt=8&uo=4">https://itunes.apple.com/us/app/cardu/id446737859?mt=8&uo=4</a>
**App Version:** 5.1.10
**Seller:** Sunduka Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sunduka-oy/id446737862?uo=4> © Sunduka Oy </a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/59/6d/5e/596d5ee9-0631-1c54-1d1c-ccb2bbcebbad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19896294/16f9b71a-a054-11e6-8175-d42c77edd816.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19307648/e24f00a2-907b-11e6-9a12-763e5b0691b3.png)
https://cloud.githubusercontent.com/assets/20930745/19307648/e24f00a2-907b-11e6-9a12-763e5b0691b3.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19307655/f0fbe14c-907b-11e6-80b4-7b432847805f.png

**Comment by ivanov007** [comment]
too thin isn't it?

**Comment by 2Qt2beStr8** [comment]
.. it's like the original one .. but i think you are right - it would be better if it is a little bit thicker

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19896294/16f9b71a-a054-11e6-8175-d42c77edd816.png)
https://cloud.githubusercontent.com/assets/20930745/19896294/16f9b71a-a054-11e6-8175-d42c77edd816.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19896316/2944a272-a054-11e6-84ff-8331cdf812eb.png

**Comment by 2Qt2beStr8** [comment]
@ivanov007 ... you like it better?

**Comment by ivanov007** [comment]
yes looks good :+1:
