### ISSUE TITLE
MTV Uutiset

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8305]
**App Name:** MTV Uutiset
**Bundle ID:** fi.mtv3.iphone.Whitelabel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=437805341">437805341</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mtv-uutiset/id437805341?mt=8&uo=4">https://itunes.apple.com/us/app/mtv-uutiset/id437805341?mt=8&uo=4</a>
**App Version:** 2.15.0
**Seller:** MTV Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/mtv3/id437805344?uo=4>© MTV3</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/84/61/60/84616057-8b86-b84a-73ae-01dcfa0b259a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19307512/27dc97a2-907b-11e6-851b-947ef46ba36c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19307512/27dc97a2-907b-11e6-851b-947ef46ba36c.png)
https://cloud.githubusercontent.com/assets/20930745/19307512/27dc97a2-907b-11e6-851b-947ef46ba36c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19307517/35365870-907b-11e6-9aa8-43c38c08dab4.png
