### ISSUE TITLE
SportLocker | Stats, Comparisons, Fantasy and More

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8306]
**App Name:** SportLocker | Stats, Comparisons, Fantasy and More
**Bundle ID:** com.sportlocker.sportlocker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=964394894">964394894</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sportlocker-stats-comparisons/id964394894?mt=8&uo=4">https://itunes.apple.com/us/app/sportlocker-stats-comparisons/id964394894?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Simplified Sports Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/simplified-sports/id964394893?uo=4>© Simplified Sports</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple22/v4/26/80/45/268045c9-71be-57cd-6ca9-c2e32ed3a5c8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19311851/54a4db40-9090-11e6-870f-aab8862c60bd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19311851/54a4db40-9090-11e6-870f-aab8862c60bd.png)
https://cloud.githubusercontent.com/assets/20930745/19311851/54a4db40-9090-11e6-870f-aab8862c60bd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19311873/650c4d88-9090-11e6-995e-1e5edc8a276b.png
