### ISSUE TITLE
DeskConnect

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8308]
**App Name:** DeskConnect
**Bundle ID:** com.deskconnect.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=642218244">642218244</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deskconnect/id642218244?mt=8&uo=4">https://itunes.apple.com/us/app/deskconnect/id642218244?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** DeskConnect, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/deskconnect-inc./id642218247?uo=4>© DeskConnect, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/88/6d/7a/886d7a11-7b62-85d7-a64c-dbf2e8657c7a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19327291/7d055004-90ce-11e6-99be-8e664c447c2a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19327291/7d055004-90ce-11e6-99be-8e664c447c2a.png)
https://cloud.githubusercontent.com/assets/20930745/19327291/7d055004-90ce-11e6-99be-8e664c447c2a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19327308/931ae412-90ce-11e6-8549-b11ec14f887b.png
