### ISSUE TITLE
Constitution for iPhone and iPod Touch

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8309]
**App Name:** Constitution for iPhone and iPod Touch
**Bundle ID:** com.cbagwellconsulting.Constitution
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=288657710">288657710</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/constitution-for-iphone-ipod/id288657710?mt=8&uo=4">https://itunes.apple.com/us/app/constitution-for-iphone-ipod/id288657710?mt=8&uo=4</a>
**App Version:** 1.5.6
**Seller:** Clint Bagwell Consulting
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/clint-bagwell-consulting/id282796386?uo=4>© Clint Bagwell Consulting</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/81/f6/ee/81f6ee36-92c2-49dd-fef6-0880dcb86b2a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19347481/47bcfeb2-9149-11e6-8fc6-725a8576cb0e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19347481/47bcfeb2-9149-11e6-8fc6-725a8576cb0e.png)
https://cloud.githubusercontent.com/assets/20930745/19347481/47bcfeb2-9149-11e6-8fc6-725a8576cb0e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19347492/5a823314-9149-11e6-8496-a3ea2b2af932.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19353425/adffaef8-9163-11e6-854f-9e177b4e189e.png)
https://cloud.githubusercontent.com/assets/20930745/19353425/adffaef8-9163-11e6-854f-9e177b4e189e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19353454/c21e9f8e-9163-11e6-90db-73cb84de5bd4.png

**Comment by 2Qt2beStr8** [comment]
@Sly-Fi .... i think both icons are not really good, but i can't do it better ... maybe someone other

**Comment by Sly-Fi** [comment]
@2Qt2beStr8 - I really like the first one!
