### ISSUE TITLE
OfferUp - Buy. Sell. Simple.

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#8310]
**App Name:** OfferUp - Buy. Sell. Simple.
**Bundle ID:** com.offerup.iphone.consumer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=468996152">468996152</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/offerup-buy.-sell.-simple./id468996152?mt=8&uo=4">https://itunes.apple.com/us/app/offerup-buy.-sell.-simple./id468996152?mt=8&uo=4</a>
**App Version:** 2.9.5
**Seller:** OfferUp Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/offerup-inc./id414140125?uo=4>© OfferUp Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/12/19/6d/12196d18-b6d6-d22f-7552-8ffceb7289f3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19343647/5cb6ad3e-9137-11e6-830a-d71a089aa54e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19343647/5cb6ad3e-9137-11e6-830a-d71a089aa54e.png)
https://cloud.githubusercontent.com/assets/20930745/19343647/5cb6ad3e-9137-11e6-830a-d71a089aa54e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19343659/6b7f7a30-9137-11e6-96d9-6bb1a987a8e5.png
