### ISSUE TITLE
Just The Tips - The Best Tip Tracker for Members of the Service Industry

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#8311]
**App Name:** Just The Tips - The Best Tip Tracker for Members of the Service Industry
**Bundle ID:** JTT.JustTheTips
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937297529">937297529</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/just-tips-best-tip-tracker/id937297529?mt=8&uo=4">https://itunes.apple.com/us/app/just-tips-best-tip-tracker/id937297529?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** JAKETEKLD, INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/jaketekld/id937297528?uo=4>© Jaketekld</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/83/aa/94/83aa9406-b575-b9fc-b352-ae535c86cf7d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19345915/08bbff68-9141-11e6-9fea-daa067aaf0db.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19345915/08bbff68-9141-11e6-9fea-daa067aaf0db.png)
https://cloud.githubusercontent.com/assets/20930745/19345915/08bbff68-9141-11e6-9fea-daa067aaf0db.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19345927/1875922a-9141-11e6-819b-724c5843762d.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19346494/ead19d34-9143-11e6-9bcc-d8c49a2f4b4b.png)
https://cloud.githubusercontent.com/assets/20930745/19346494/ead19d34-9143-11e6-9bcc-d8c49a2f4b4b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19346503/f8f32ae0-9143-11e6-8f06-de9731895cc3.png
