### ISSUE TITLE
Logix Mobile Banking

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#8312]
**App Name:** Logix Mobile Banking
**Bundle ID:** com.logixbanking.smartclient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1066019955">1066019955</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/logix-mobile-banking/id1066019955?mt=8&uo=4">https://itunes.apple.com/us/app/logix-mobile-banking/id1066019955?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Logix Federal Credit Union
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/logix-federal-credit-union/id449281413?uo=4>© Logix Federal Credit Union</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/3a/76/0a/3a760a44-c796-adb9-0e9f-3d1e17897323/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19621918/52c6ccd8-989d-11e6-8255-587833506038.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19621918/52c6ccd8-989d-11e6-8255-587833506038.png)
https://cloud.githubusercontent.com/assets/2068130/19621918/52c6ccd8-989d-11e6-8255-587833506038.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19621919/61516952-989d-11e6-9a0d-e7d6f5b8de2e.png
