### ISSUE TITLE
Bowling King

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#8313]
**App Name:** Bowling King
**Bundle ID:** com.pnixgames.bowlingking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=769737983">769737983</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bowling-king/id769737983?mt=8&uo=4">https://itunes.apple.com/us/app/bowling-king/id769737983?mt=8&uo=4</a>
**App Version:** 1.40.9
**Seller:** Miniclip SA
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/miniclip.com/id337457683?uo=4>© Miniclip.com</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/ba/74/b0/ba74b088-b226-6e5e-71f3-ebb1d1ff26ee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19353013/521a3db6-9162-11e6-8e97-1122c5b8ccc5.png)

**Comment by 2Qt2beStr8** [comment]
@ashley108 ... i am not sure if you like it .. maybe some other can make a better one

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19353013/521a3db6-9162-11e6-8e97-1122c5b8ccc5.png)
https://cloud.githubusercontent.com/assets/20930745/19353013/521a3db6-9162-11e6-8e97-1122c5b8ccc5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19353030/62f9e672-9162-11e6-87e7-90ebe441b362.png

**Comment by ashley108** [comment]
It's nice thanks :)
