### ISSUE TITLE
Vivid Seats - Tickets: Sports, Concerts, Theater

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#8314]
**App Name:** Vivid Seats – Tickets: Sports, Concerts, Theater
**Bundle ID:** com.vividseats.VividSeatsMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=963355757">963355757</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vivid-seats-tickets-sports/id963355757?mt=8&uo=4">https://itunes.apple.com/us/app/vivid-seats-tickets-sports/id963355757?mt=8&uo=4</a>
**App Version:** 2.2.4
**Seller:** Vivid Seats Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/vivid-seats/id963355756?uo=4>© Vivid Seats</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/d7/84/76/d784769c-4473-7263-d07c-eca67e3bbcb9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19342470/465cf638-9132-11e6-823d-2e1b9aaa8000.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19342470/465cf638-9132-11e6-823d-2e1b9aaa8000.png)
https://cloud.githubusercontent.com/assets/20930745/19342470/465cf638-9132-11e6-823d-2e1b9aaa8000.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19342485/568cf8be-9132-11e6-98ba-3347ad3a39d7.png
