### ISSUE TITLE
Kirkland's Spin to Win

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#8315]
**App Name:** Kirkland's Spin to Win
**Bundle ID:** com.kirklands.SpinToWin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=556027347">556027347</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kirklands-spin-to-win/id556027347?mt=8&uo=4">https://itunes.apple.com/us/app/kirklands-spin-to-win/id556027347?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** KIRKLAND'S, INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/kirklands/id556027371?uo=4>© Kirkland's</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/ec/4e/13/ec4e13fa-d860-f1ae-2a21-94a5e2d33ff3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19342585/ac20e2ae-9132-11e6-9ad1-87ada5f9e0da.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19342585/ac20e2ae-9132-11e6-9ad1-87ada5f9e0da.png)
https://cloud.githubusercontent.com/assets/20930745/19342585/ac20e2ae-9132-11e6-9ad1-87ada5f9e0da.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19342608/c1013e80-9132-11e6-8cc6-dc6abda0e1eb.png

**Comment by ashley108** [comment]
Thank you. How do I add them to the theme?

**Comment by 2Qt2beStr8** [comment]
1. Download the icon and rename it to "com.kirklands.SpinToWin"
2. Copy this file to following path: /Library/Themes/Glasklart.Icons.theme/IconBundles
3. make a respring and the icon changes

**Comment by ashley108** [comment]
The icons are coming out very large

**Comment by 2Qt2beStr8** [comment]
com.kirklands.SpinToWin-large.png is the right name

**Comment by 2Qt2beStr8** [comment]
don't forget the "-large.png" at the end from the filename
