### ISSUE TITLE
Uber Eats: Food Delivery

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#8316]
**App Name:** Uber Eats: Food Delivery
**Bundle ID:** com.ubercab.UberEats
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1058959277">1058959277</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/uber-eats-food-delivery/id1058959277?mt=8&uo=4">https://itunes.apple.com/us/app/uber-eats-food-delivery/id1058959277?mt=8&uo=4</a>
**App Version:** 1.171.10000
**Seller:** Uber Technologies, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/uber-technologies-inc/id368677371?uo=4">© Uber Technologies, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/57/38/0a/57380a74-840b-2b2c-21f1-91a71c263a2c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/51438983-0714b780-1cb4-11e9-9b6f-1362a73eb2f8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19342652/f850919c-9132-11e6-8ef2-4669676d1957.png)
https://cloud.githubusercontent.com/assets/20930745/19342652/f850919c-9132-11e6-8ef2-4669676d1957.png

https://cloud.githubusercontent.com/assets/20930745/19342671/09343216-9133-11e6-9d4a-85d01631192a.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/51438983-0714b780-1cb4-11e9-9b6f-1362a73eb2f8.png)
https://user-images.githubusercontent.com/2068130/51438983-0714b780-1cb4-11e9-9b6f-1362a73eb2f8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/51438987-172c9700-1cb4-11e9-8aba-8bd227b60d2f.png
