### ISSUE TITLE
Home - Design & Decor Shopping

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#8317]
**App Name:** Home - Design & Decor Shopping
**Bundle ID:** com.contextlogic.Home
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035837482">1035837482</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/home-design-decor-shopping/id1035837482?mt=8&uo=4">https://itunes.apple.com/us/app/home-design-decor-shopping/id1035837482?mt=8&uo=4</a>
**App Version:** 1.2.9
**Seller:** ContextLogic Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/contextlogic-inc./id530621398?uo=4>© ContextLogic Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/ea/33/6e/ea336e26-38c4-9e52-86bb-c4eb8853e9c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19342724/4ad32a24-9133-11e6-8582-b8af85a24f4a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19342724/4ad32a24-9133-11e6-8582-b8af85a24f4a.png)
https://cloud.githubusercontent.com/assets/20930745/19342724/4ad32a24-9133-11e6-8582-b8af85a24f4a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19342734/5bf286e2-9133-11e6-869f-c67cfe9eb1f5.png
