### ISSUE TITLE
Zumper Apartment Finder - Search & Rent Apartments

### ISSUE THREAD

**Issue by ashley108** [glasklart/hd#8318]
**App Name:** Zumper Apartment Finder - Search & Rent Apartments
**Bundle ID:** com.zumper.Rentals
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=678683201">678683201</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zumper-apartment-finder-search/id678683201?mt=8&uo=4">https://itunes.apple.com/us/app/zumper-apartment-finder-search/id678683201?mt=8&uo=4</a>
**App Version:** 2.8.4
**Seller:** Zumper, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/zumper-inc./id625594035?uo=4>© Zumper, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/54/8a/61/548a61a3-9c92-ac8d-fcf6-cd288474161b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19342790/98d6c23a-9133-11e6-8561-bf90278348b5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19342790/98d6c23a-9133-11e6-8561-bf90278348b5.png)
https://cloud.githubusercontent.com/assets/20930745/19342790/98d6c23a-9133-11e6-8561-bf90278348b5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19342800/ab89efd8-9133-11e6-85cb-f5f77cb478fc.png
