### ISSUE TITLE
Eventbrite

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#832]
**App Name:** Eventbrite
**Bundle ID:** com.eventbrite.attendee
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487922291">487922291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/eventbrite/id487922291?mt=8&uo=4">https://itunes.apple.com/us/app/eventbrite/id487922291?mt=8&uo=4</a>
**App Version:** 6.1.1
**Seller:** Eventbrite
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/eventbrite/id368260524?uo=4">© Eventbrite</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/66/70/bd/6670bdcb-ac0f-14ab-c401-7a29a53b3fc2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49687342-ea586200-fb01-11e8-8adb-abf969978356.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Eventbrite - Local Events & Fun Things To Do Near Me
**Bundle ID:** com.eventbrite.attendee
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487922291">487922291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/eventbrite-local-events-fun/id487922291?mt=8&uo=4">https://itunes.apple.com/us/app/eventbrite-local-events-fun/id487922291?mt=8&uo=4</a>
**App Version:** 4.3.3
**Seller:** Eventbrite
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/eventbrite/id368260524?uo=4>© Eventbrite</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/a4/f4/f0/a4f4f0be-327d-4ac9-bb16-0054adee30ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by l8er4now** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3704186/18400007/fabad0f6-76a1-11e6-8269-3b2dfccfb4aa.png)

https://cloud.githubusercontent.com/assets/3704186/18400007/fabad0f6-76a1-11e6-8269-3b2dfccfb4aa.png

https://cloud.githubusercontent.com/assets/3704186/18400014/0318a43a-76a2-11e6-9df8-22dc8bf6928f.png

**Comment by dreamnet** [comment]
@l8er4now Waaay too big...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18400427/230ae846-76d6-11e6-8ce6-08bf682d4bca.png)
https://cloud.githubusercontent.com/assets/2068130/18400427/230ae846-76d6-11e6-8ce6-08bf682d4bca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18400440/3181b968-76d6-11e6-85bc-0616754702c4.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Eventbrite
**Bundle ID:** com.eventbrite.attendee
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487922291">487922291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/eventbrite/id487922291?mt=8&uo=4">https://itunes.apple.com/us/app/eventbrite/id487922291?mt=8&uo=4</a>
**App Version:** 6.1.1
**Seller:** Eventbrite
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/eventbrite/id368260524?uo=4">© Eventbrite</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/66/70/bd/6670bdcb-ac0f-14ab-c401-7a29a53b3fc2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/49687342-ea586200-fb01-11e8-8adb-abf969978356.png)
https://user-images.githubusercontent.com/2068130/49687342-ea586200-fb01-11e8-8adb-abf969978356.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/49687356-fcd29b80-fb01-11e8-83f1-5b01bf297d91.png
