### ISSUE TITLE
AccuWeather Platinum - Weather for Life

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8325]
**App Name:** AccuWeather Platinum - Weather for Life
**Bundle ID:** 6KBJ338UQ6.com.accuweather.simpleweather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348618445">348618445</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/accuweather-platinum-weather/id348618445?mt=8&uo=4">https://itunes.apple.com/us/app/accuweather-platinum-weather/id348618445?mt=8&uo=4</a>
**App Version:** 10.0.1
**Seller:** AccuWeather International, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/accuweather-international/id300048140?uo=4>© AccuWeather International, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/be/27/2b/be272b7b-ff74-9a9c-cdad-38a6daca6981/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19384787/66bdcd38-920b-11e6-9e81-e2b2a611ca47.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19384787/66bdcd38-920b-11e6-9e81-e2b2a611ca47.png)
https://cloud.githubusercontent.com/assets/20930745/19384787/66bdcd38-920b-11e6-9e81-e2b2a611ca47.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19384803/7dad12e2-920b-11e6-8df5-df41e00d01d5.png

**Comment by dreamnet** [comment]
Same as #2543.
