### ISSUE TITLE
Pinger Textfree: Free Texting, Free Calling App

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8329]
**App Name:** Pinger Textfree: Free Texting, Free Calling App
**Bundle ID:** com.pinger.pingerphone2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444741112">444741112</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pinger-textfree-free-texting/id444741112?mt=8&uo=4">https://itunes.apple.com/us/app/pinger-textfree-free-texting/id444741112?mt=8&uo=4</a>
**App Version:** 9.9
**Seller:** Pinger, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pinger-inc./id299102705?uo=4>© Pinger, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/68/2f/d8/682fd8a0-d983-badd-dfb1-a213a15491ce/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/19412455/40aa1044-92dc-11e6-9230-22d6e18b6fff.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410989/e77abf74-92f8-11e6-9092-0f3b3d1d5f82.png)
https://cloud.githubusercontent.com/assets/20930745/19410989/e77abf74-92f8-11e6-9092-0f3b3d1d5f82.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19410985/cb580b12-92f8-11e6-8a4f-c4fcf0ed6ba2.png

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/19412455/40aa1044-92dc-11e6-9230-22d6e18b6fff.png)
https://cloud.githubusercontent.com/assets/3090247/19412455/40aa1044-92dc-11e6-9230-22d6e18b6fff.png
Source:
https://cloud.githubusercontent.com/assets/3090247/19412456/40ac0caa-92dc-11e6-9a22-4e841e94b39a.png
