### ISSUE TITLE
Breeding Guide for DragonVale

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#833]
**App Name:** Breeding Guide for DragonVale
**Bundle ID:** com.letitguide.dragonvalebreed
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=511945342">511945342</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/breeding-guide-for-dragonvale/id511945342?mt=8&uo=4">https://itunes.apple.com/us/app/breeding-guide-for-dragonvale/id511945342?mt=8&uo=4</a>
**App Version:** 1.8.4
**Seller:** The Next Flow, S.L.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/the-next-flow/id611112376?uo=4>© The Next Flow</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/64/35/67/64356754-ee9c-9cdb-0a99-5fbf7d0a95f2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409663/2d277802-92d9-11e6-898e-652023b59c79.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409663/2d277802-92d9-11e6-898e-652023b59c79.png)
https://cloud.githubusercontent.com/assets/20930745/19409663/2d277802-92d9-11e6-898e-652023b59c79.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409666/3bfb1406-92d9-11e6-8e8f-d41367f7ea46.png
