### ISSUE TITLE
Lists - Create Bright and Colorful Tasks and Checklists

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8331]
**App Name:** Lists - Create Bright and Colorful Tasks and Checklists
**Bundle ID:** com.ravendesktechnologies.lists2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035448962">1035448962</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lists-create-bright-colorful/id1035448962?mt=8&uo=4">https://itunes.apple.com/us/app/lists-create-bright-colorful/id1035448962?mt=8&uo=4</a>
**App Version:** 2.3.0
**Seller:** Ravendesk Technologies LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ravendesk-technologies/id871848278?uo=4>© Ravendesk Technologies</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/29/d1/16/29d1164b-d5f2-30da-bad7-10371b13bb77/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419654/68ca6d3e-93dc-11e6-9d23-eebb2f3bc7af.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419654/68ca6d3e-93dc-11e6-9d23-eebb2f3bc7af.png)
https://cloud.githubusercontent.com/assets/20930745/19419654/68ca6d3e-93dc-11e6-9d23-eebb2f3bc7af.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19419675/c761f3bc-93dc-11e6-96a0-96c2385219bb.png
