### ISSUE TITLE
Loyalive - Live Loyalty Cards, Points & Rewards

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8332]
**App Name:** Loyalive - Live Loyalty Cards, Points & Rewards
**Bundle ID:** com.loyalive.loyalive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1009310671">1009310671</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/loyalive-live-loyalty-cards/id1009310671?mt=8&uo=4">https://itunes.apple.com/us/app/loyalive-live-loyalty-cards/id1009310671?mt=8&uo=4</a>
**App Version:** 1.9.5
**Seller:** Loyalive Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/loyalive-ltd/id1009310670?uo=4>© Loyalive Ltd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/d6/29/e4/d629e4b9-844e-5c1e-8052-11b6f48bb526/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419250/df58df5c-93d3-11e6-9b2b-b57e415da6cc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19419250/df58df5c-93d3-11e6-9b2b-b57e415da6cc.png)
https://cloud.githubusercontent.com/assets/20930745/19419250/df58df5c-93d3-11e6-9b2b-b57e415da6cc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19419254/f305bb88-93d3-11e6-813c-1d7bedd1ca02.png
