### ISSUE TITLE
ScoreStream - High School & College Sports Scores

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8334]
**App Name:** ScoreStream - High School & College Sports Scores
**Bundle ID:** com.scorestream.scorestream-mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=514772744">514772744</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scorestream-high-school-college/id514772744?mt=8&uo=4">https://itunes.apple.com/us/app/scorestream-high-school-college/id514772744?mt=8&uo=4</a>
**App Version:** 2.2.70
**Seller:** CrowdScores, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/crowdscores-inc./id514772747?uo=4>© CrowdScores, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/3e/87/43/3e87430b-ebc8-5cc7-5845-394f5ca63f22/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19451808/8697557a-94ae-11e6-918e-62495f640f7f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19451808/8697557a-94ae-11e6-918e-62495f640f7f.png)
https://cloud.githubusercontent.com/assets/20930745/19451808/8697557a-94ae-11e6-918e-62495f640f7f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19451843/a80bb4bc-94ae-11e6-99fc-901e9a12d6fd.png
