### ISSUE TITLE
Perkd - Loyalty & Reward Cards

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8335]
**App Name:** Perkd - Loyalty & Reward Cards
**Bundle ID:** me.perkd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=483062554">483062554</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/perkd-loyalty-reward-cards/id483062554?mt=8&uo=4">https://itunes.apple.com/us/app/perkd-loyalty-reward-cards/id483062554?mt=8&uo=4</a>
**App Version:** 3.3.8
**Seller:** Perkd Pte. Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/perkd/id483062557?uo=4>© Perkd</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/ec/39/7e/ec397e9e-e408-5a5a-a6f9-9cbde172f4da/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19451023/fd1adbde-94ab-11e6-82ba-5e8f13e316c8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19451023/fd1adbde-94ab-11e6-82ba-5e8f13e316c8.png)
https://cloud.githubusercontent.com/assets/20930745/19451023/fd1adbde-94ab-11e6-82ba-5e8f13e316c8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19451106/4db29a3c-94ac-11e6-874d-b732be09317a.png
