### ISSUE TITLE
Sports Scores - Customized Scores at your Fingertips

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8336]
**App Name:** Sports Scores - Customized Scores at your Fingertips
**Bundle ID:** com.toddbrady.sportsscores
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=521366178">521366178</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sports-scores-customized-scores/id521366178?mt=8&uo=4">https://itunes.apple.com/us/app/sports-scores-customized-scores/id521366178?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** Todd Brady
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/todd-brady/id488536508?uo=4>© Todd Brady</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple30/v4/2c/61/a9/2c61a91a-d2bb-36cf-89cf-a3f39fbe4e6d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19453628/584a6ce0-94b6-11e6-8d64-81e0ca2c666a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19453628/584a6ce0-94b6-11e6-8d64-81e0ca2c666a.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19453628/584a6ce0-94b6-11e6-8d64-81e0ca2c666a.png)

Source:
https://cloud.githubusercontent.com/assets/20930745/19453647/6c72a048-94b6-11e6-9323-f6d729ab2e30.png
