### ISSUE TITLE
AppAdvice

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8338]
**App Name:** AppAdvice
**Bundle ID:** com.appadvice.AppAdvice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364906378">364906378</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appadvice/id364906378?mt=8&uo=4">https://itunes.apple.com/us/app/appadvice/id364906378?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** App Advice
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/appadvice.com/id305663481?uo=4>© AppAdvice.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/a5/32/d0/a532d091-5ac8-e905-8308-7709a416efce/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19568976/1abd4894-96f4-11e6-94a6-c93f664a6e62.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19568976/1abd4894-96f4-11e6-94a6-c93f664a6e62.png)
https://cloud.githubusercontent.com/assets/10730122/19568976/1abd4894-96f4-11e6-94a6-c93f664a6e62.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19568975/1abb631c-96f4-11e6-8738-f6729990a393.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... for information ... this app is not available in the app store ... but i think @l8er4now is using this app

**Comment by l8er4now** [comment]
They finally updated the app after 4 years and now it looks like it got yanked. I'm sure it will be back. FYI, it did require 9.3 as a minimum to install.
