### ISSUE TITLE
MiniHack - Hacker News Client

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8340]
**App Name:** MiniHack - Hacker News Client
**Bundle ID:** com.42mini.MiniHack
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=631108846">631108846</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minihack-hacker-news-client/id631108846?mt=8&uo=4">https://itunes.apple.com/us/app/minihack-hacker-news-client/id631108846?mt=8&uo=4</a>
**App Version:** 2.9.6
**Seller:** Cai GuangShao
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cai-guangshao/id631108889?uo=4>© Cai GuangShao</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/24/42/36/24423641-a788-7d00-eb84-14f71b1fa149/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19596232/d6c6e47a-978d-11e6-898f-ab6c6b7e6052.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19587014/1fd8fb86-975b-11e6-8342-0270dcc27042.png)
https://cloud.githubusercontent.com/assets/10730122/19587014/1fd8fb86-975b-11e6-8342-0270dcc27042.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19587013/1fd57b64-975b-11e6-828a-fe8dbba5b4ee.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19587039/4a2adddc-975b-11e6-9ea9-3c38cefc3aca.png)
https://cloud.githubusercontent.com/assets/10730122/19587039/4a2adddc-975b-11e6-9ea9-3c38cefc3aca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19587040/4a425728-975b-11e6-9b9a-0bcce36d70a1.png

**Comment by 2Qt2beStr8** [comment]
3rd version :-)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19596232/d6c6e47a-978d-11e6-898f-ab6c6b7e6052.png)
https://cloud.githubusercontent.com/assets/20930745/19596232/d6c6e47a-978d-11e6-898f-ab6c6b7e6052.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19596236/e761903c-978d-11e6-88de-173055fffb5e.png

**Comment by 2Qt2beStr8** [comment]
@Trubbel which one we should take? your issue, your choise ;-)

**Comment by Trubbel** [comment]
@2Qt2beStr8 I can't decide haha, @dreamnet what do you think?

**Comment by dreamnet** [comment]
The last one.
