### ISSUE TITLE
Night Cam!

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8345]
**App Name:** Night Cam!
**Bundle ID:** com.iphoneclan.nightcam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=890834350">890834350</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/night-cam/id890834350?mt=8&uo=4">https://itunes.apple.com/us/app/night-cam/id890834350?mt=8&uo=4</a>
**App Version:** 1.10
**Seller:** Sylwester Los
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lucky-clan/id294866851?mt=8&uo=4">© Lucky Clan</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/11/5c/cf/115ccf2f-65e6-cc04-60dc-1ec1e485ee5e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32123208-a725ef9a-bb63-11e7-888b-e0518436c095.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19587377/4b3b5528-975e-11e6-97d0-6531b3134e30.png)
https://cloud.githubusercontent.com/assets/10730122/19587377/4b3b5528-975e-11e6-97d0-6531b3134e30.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19587376/4b3a6d66-975e-11e6-8863-7626a0c5ce54.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Night Cam!
**Bundle ID:** com.iphoneclan.nightcam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=890834350">890834350</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/night-cam/id890834350?mt=8&uo=4">https://itunes.apple.com/us/app/night-cam/id890834350?mt=8&uo=4</a>
**App Version:** 1.10
**Seller:** Sylwester Los
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lucky-clan/id294866851?mt=8&uo=4">© Lucky Clan</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/11/5c/cf/115ccf2f-65e6-cc04-60dc-1ec1e485ee5e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32123208-a725ef9a-bb63-11e7-888b-e0518436c095.png)
https://user-images.githubusercontent.com/20930745/32123208-a725ef9a-bb63-11e7-888b-e0518436c095.png

Source:
https://user-images.githubusercontent.com/20930745/32123262-cdd2e3e6-bb63-11e7-8984-032952ef93d5.png
