### ISSUE TITLE
Slow Shutter!

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8346]
**App Name:** Slow Shutter!
**Bundle ID:** com.iphoneclan.slowshutter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=616728746">616728746</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slow-shutter/id616728746?mt=8&uo=4">https://itunes.apple.com/us/app/slow-shutter/id616728746?mt=8&uo=4</a>
**App Version:** 2.8
**Seller:** Sylwester Los
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lucky-clan/id294866851?mt=8&uo=4">© Lucky Clan</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/bf/2c/96/bf2c9629-7f7b-ad08-299a-2e59136eaf6f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32123433-6f4120b2-bb64-11e7-95bb-c26f861c6362.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19587405/6f889ba2-975e-11e6-95c0-16a58be8894f.png)
https://cloud.githubusercontent.com/assets/10730122/19587405/6f889ba2-975e-11e6-95c0-16a58be8894f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19587404/6f70e336-975e-11e6-93d8-0f26b95fa538.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Slow Shutter!
**Bundle ID:** com.iphoneclan.slowshutter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=616728746">616728746</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/slow-shutter/id616728746?mt=8&uo=4">https://itunes.apple.com/us/app/slow-shutter/id616728746?mt=8&uo=4</a>
**App Version:** 2.8
**Seller:** Sylwester Los
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lucky-clan/id294866851?mt=8&uo=4">© Lucky Clan</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/bf/2c/96/bf2c9629-7f7b-ad08-299a-2e59136eaf6f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32123433-6f4120b2-bb64-11e7-95bb-c26f861c6362.png)
https://user-images.githubusercontent.com/20930745/32123433-6f4120b2-bb64-11e7-95bb-c26f861c6362.png

Source:
https://user-images.githubusercontent.com/20930745/32123452-88343e56-bb64-11e7-93d0-5ee21c61bc2e.png
