### ISSUE TITLE
Post

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8348]
**App Name:** Post
**Bundle ID:** at.post.privat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=879020660">879020660</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/post/id879020660?mt=8&uo=4">https://itunes.apple.com/us/app/post/id879020660?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Oesterreichische Post AG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/post-ag/id375721271?uo=4">© Post AG</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/33/20/88/332088c0-a518-7743-1d1a-9bd4b8a819d0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19956441/d4091fb0-a18c-11e6-9591-1d5ae7ad9ebe.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/19587726/e29ef5e4-9760-11e6-9868-3f2f76523b8c.png)
https://cloud.githubusercontent.com/assets/10730122/19587726/e29ef5e4-9760-11e6-9868-3f2f76523b8c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/19587725/e28712bc-9760-11e6-9cc1-20127a3bb881.png

**Comment by dreamnet** [comment]
Looks strange on my device, so here is an icon update:
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19956441/d4091fb0-a18c-11e6-9591-1d5ae7ad9ebe.png)
https://cloud.githubusercontent.com/assets/2068130/19956441/d4091fb0-a18c-11e6-9591-1d5ae7ad9ebe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19956446/e6b410ca-a18c-11e6-9768-0767fc874f94.png
