### ISSUE TITLE
Jurassic Park™ Builder

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#835]
**App Name:** Jurassic Park™ Builder
**Bundle ID:** com.ludia.jurassicpark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=499250722">499250722</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jurassic-park-builder/id499250722?mt=8&uo=4">https://itunes.apple.com/us/app/jurassic-park-builder/id499250722?mt=8&uo=4</a>
**App Version:** 4.9.0
**Seller:** Ludia
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ludia/id293912963?uo=4">© Ludia</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/74/98/e2/7498e25c-0351-d99a-27fe-9f3ca421d023/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20465470/31a30896-af5e-11e6-91d7-3a37d92666ca.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20465470/31a30896-af5e-11e6-91d7-3a37d92666ca.png)
https://cloud.githubusercontent.com/assets/2068130/20465470/31a30896-af5e-11e6-91d7-3a37d92666ca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20465475/3fab83f0-af5e-11e6-9af0-6c0449569df9.png
