### ISSUE TITLE
SongShift: Simple Playlist Transfers

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#8355]
**App Name:** SongShift: Simple Playlist Transfers
**Bundle ID:** com.cpdigitaldarkroom.SongShift
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1097974566">1097974566</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/songshift-simple-playlist/id1097974566?mt=8&uo=4">https://itunes.apple.com/us/app/songshift-simple-playlist/id1097974566?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Juan Carlos Perez
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/juan-carlos-perez/id931213788?uo=4>© Juan Carlos Perez</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/49/d8/46/49d84630-309f-f798-a0f6-97af4ea3bb06/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19616912/eca5d9ca-9820-11e6-987b-4960ec454f5c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19616912/eca5d9ca-9820-11e6-987b-4960ec454f5c.png)
https://cloud.githubusercontent.com/assets/20930745/19616912/eca5d9ca-9820-11e6-987b-4960ec454f5c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19616918/15264cae-9821-11e6-8622-29d2c5fdd4f0.png
