### ISSUE TITLE
ServerSports Competitions

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#8356]
**App Name:** ServerSports Competitions
**Bundle ID:** com.serversports.competitions
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=910982530">910982530</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/serversports-competitions/id910982530?mt=8&uo=4">https://itunes.apple.com/us/app/serversports-competitions/id910982530?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** INET QUALITY SERVICES SL
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/inet-quality-services/id910982533?uo=4>© INET QUALITY SERVICES</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/e4/85/c4/e485c4d6-14af-9232-253d-80fdc6e30622/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19616943/f61dea82-9821-11e6-8018-1f8ff91a9d87.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19616943/f61dea82-9821-11e6-8018-1f8ff91a9d87.png)
https://cloud.githubusercontent.com/assets/20930745/19616943/f61dea82-9821-11e6-8018-1f8ff91a9d87.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19616953/1db84cfe-9822-11e6-8048-fe1e9853aba2.png
