### ISSUE TITLE
NOTE'd

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#836]
**App Name:** NOTE'd
**Bundle ID:** net.suxxexx.noted
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=507362852">507362852</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/noted/id507362852?mt=8&uo=4">https://itunes.apple.com/us/app/noted/id507362852?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Dong Wook Kim
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/suxxexx/id507362855?uo=4>© Suxxexx</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/ad/e5/1d/ade51dfc-076e-dccf-7d77-3b664324783e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409560/86c250ec-92d6-11e6-8041-662b7ff72c22.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409560/86c250ec-92d6-11e6-8041-662b7ff72c22.png)
https://cloud.githubusercontent.com/assets/20930745/19409560/86c250ec-92d6-11e6-8041-662b7ff72c22.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409565/9900fd6c-92d6-11e6-8462-a198bdec9c82.png
