### ISSUE TITLE
KHL - Kontinental hockey league

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8373]
**App Name:** KHL - Kontinental hockey league
**Bundle ID:** ru.khl.khl-app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=455938766">455938766</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/khl-kontinental-hockey-league/id455938766?mt=8&uo=4">https://itunes.apple.com/us/app/khl-kontinental-hockey-league/id455938766?mt=8&uo=4</a>
**App Version:** 4.2.1
**Seller:** KHL-Marketing LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/khl-marketing-llc/id416318099?uo=4>© KHL-Marketing LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/5f/a4/ea/5fa4eab4-2137-34ba-3a51-4a88b3957d80/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19628758/3222f1aa-9965-11e6-8faf-9eb1021ee5bf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19628758/3222f1aa-9965-11e6-8faf-9eb1021ee5bf.png)
https://cloud.githubusercontent.com/assets/20930745/19628758/3222f1aa-9965-11e6-8faf-9eb1021ee5bf.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19628766/45109678-9965-11e6-84ba-dcac79aef88d.png
