### ISSUE TITLE
CHL 2016 / 2017

### ISSUE THREAD

**Issue by Anonyymikko** [glasklart/hd#8374]
**App Name:** CHL 2016 / 2017
**Bundle ID:** com.iihf.chl2016
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1125360169">1125360169</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chl-2016-2017/id1125360169?mt=8&uo=4">https://itunes.apple.com/us/app/chl-2016-2017/id1125360169?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** International Ice Hockey Federation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/iihf/id489872657?uo=4>© IIHF</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/92/ec/f2/92ecf2cf-df3b-4f94-ef4e-560442db97ca/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19628821/b0830be2-9966-11e6-9769-1e1c1d6ffcad.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19628807/30ac8a9c-9966-11e6-987f-fb9cbbda3900.png)
https://cloud.githubusercontent.com/assets/20930745/19628807/30ac8a9c-9966-11e6-987f-fb9cbbda3900.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19628808/3e77119c-9966-11e6-824f-ee1895416b97.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19628821/b0830be2-9966-11e6-9769-1e1c1d6ffcad.png)
https://cloud.githubusercontent.com/assets/20930745/19628821/b0830be2-9966-11e6-9769-1e1c1d6ffcad.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19628822/bcb6ed3e-9966-11e6-9dff-f593df6480c1.png
