### ISSUE TITLE
Avis Car Rental – Introducing Avis Now

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#840]
**App Name:** Avis Car Rental – Introducing Avis Now
**Bundle ID:** com.roundarch.aviscarreservation
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=308342527">308342527</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/avis-car-rental-introducing/id308342527?mt=8&uo=4">https://itunes.apple.com/us/app/avis-car-rental-introducing/id308342527?mt=8&uo=4</a>
**App Version:** 11.3
**Seller:** AVIS BUDGET GROUP, INC.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/avis-budget-group/id537981451?uo=4>© Avis Budget Group</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/20/aa/3a/20aa3a80-6726-ae47-91d1-bd875fa9db4c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409701/4407f0aa-92da-11e6-99f0-ba8d6746092d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409701/4407f0aa-92da-11e6-99f0-ba8d6746092d.png)
https://cloud.githubusercontent.com/assets/20930745/19409701/4407f0aa-92da-11e6-99f0-ba8d6746092d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409704/569d17a4-92da-11e6-96c6-5f92b7540dc6.png
