### ISSUE TITLE
cab4me - Get a Taxi. Anywhere.

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8418]
**App Name:** cab4me - Get a Taxi. Anywhere.
**Bundle ID:** com.skycoders.cab4me
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=318077823">318077823</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/cab4me-get-a-taxi-anywhere/id318077823?uo=4">https://apps.apple.com/gb/app/cab4me-get-a-taxi-anywhere/id318077823?uo=4</a>
**App Version:** 5.5
**Seller:** Seibt & Straub GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/seibt-straub-gmbh/id1294577422?uo=4">© Seibt & Straub GmbH</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/b3/40/8a/b3408a49-f243-44ed-2cf8-95b01f809f0b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380343-62f22200-9a44-11e9-90c5-b1e9ca08bf30.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19680671/f9df1efc-9aa6-11e6-9360-a3b66d756e70.png)
https://cloud.githubusercontent.com/assets/20930745/19680671/f9df1efc-9aa6-11e6-9360-a3b66d756e70.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19680710/16544d1e-9aa7-11e6-9ca7-c8202795be94.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380343-62f22200-9a44-11e9-90c5-b1e9ca08bf30.png)
https://user-images.githubusercontent.com/20930745/60380343-62f22200-9a44-11e9-90c5-b1e9ca08bf30.png

Source:
https://user-images.githubusercontent.com/20930745/60380344-6685a900-9a44-11e9-80ca-779b5182f49c.png
