### ISSUE TITLE
BarcodeTray

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8427]
**App Name:** BarcodeTray
**Bundle ID:** com.xuico.barcodetray.BarcodeTray
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1078738560">1078738560</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/barcodetray/id1078738560?mt=8&uo=4">https://itunes.apple.com/us/app/barcodetray/id1078738560?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Xuico Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/xuico-inc/id1078738559?uo=4>© Xuico Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/6c/b6/9e/6cb69e4e-758a-4887-ce3a-407dc370e72a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19685535/74b8d454-9abd-11e6-9a14-00857ade0fd9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19685535/74b8d454-9abd-11e6-9a14-00857ade0fd9.png)
https://cloud.githubusercontent.com/assets/20930745/19685535/74b8d454-9abd-11e6-9a14-00857ade0fd9.png

Source:
(https://cloud.githubusercontent.com/assets/20930745/19685566/9d5b9536-9abd-11e6-887d-39ec4ace5683.png
