### ISSUE TITLE
NETGEAR Genie

### ISSUE THREAD

**Issue by cclloyd** [glasklart/hd#843]
**App Name:** NETGEAR Genie
**Bundle ID:** com.netgear.GenieiPhoneiPod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498133627">498133627</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/netgear-genie/id498133627?mt=8&uo=4">https://itunes.apple.com/us/app/netgear-genie/id498133627?mt=8&uo=4</a>
**App Version:** 2.4.24
**Seller:** NETGEAR, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/netgear/id394405580?uo=4>© NETGEAR</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/bf/e6/dd/bfe6ddd1-39a5-4598-7e4e-888b7ac8f503/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18927891/1002d474-85be-11e6-8f4f-be48c8c2ec77.png)

**Comment by illinikev** [comment]
Update needed

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18927891/1002d474-85be-11e6-8f4f-be48c8c2ec77.png)
https://cloud.githubusercontent.com/assets/20930745/18927891/1002d474-85be-11e6-8f4f-be48c8c2ec77.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18927909/20deef26-85be-11e6-9d63-8cfd73dd857b.png
