### ISSUE TITLE
SIMON - Malls, Mills & Premium Outlets Shopping

### ISSUE THREAD

**Issue by cclloyd** [glasklart/hd#844]
**App Name:** SIMON - Malls, Mills & Premium Outlets Shopping
**Bundle ID:** com.simon.simonmallsapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395128180">395128180</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/simon-malls-mills-premium/id395128180?mt=8&uo=4">https://itunes.apple.com/us/app/simon-malls-mills-premium/id395128180?mt=8&uo=4</a>
**App Version:** 3.71
**Seller:** Simon Property Group
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/simon-property-group/id395128183?uo=4>© Simon Property Group</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/18/0d/40/180d40cf-ebd0-3d6e-6f6f-d3dc1a82fd72/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409008/077df170-92cb-11e6-9d25-7d7906c956a8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409008/077df170-92cb-11e6-9d25-7d7906c956a8.png)
https://cloud.githubusercontent.com/assets/20930745/19409008/077df170-92cb-11e6-9d25-7d7906c956a8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409012/1611563c-92cb-11e6-9f7b-6f02b84741fe.png
