### ISSUE TITLE
LINER: Highlighter for Web

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8451]
**App Name:** LINER: Highlighter for Web
**Bundle ID:** com.aurumplanet.Liner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955395198">955395198</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/liner-highlighter-for-web/id955395198?mt=8&uo=4">https://itunes.apple.com/us/app/liner-highlighter-for-web/id955395198?mt=8&uo=4</a>
**App Version:** 5.0.0
**Seller:** Aurumplanet Co. Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/liner/id955395197?uo=4">© Liner</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple115/v4/22/44/6d/22446d70-45ae-31e4-a308-1cd031323572/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41805859-7ec28194-76b1-11e8-9a82-0376cc5c9765.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19756663/9b7d3d84-9c1e-11e6-9b46-eb575cf049a1.png)
https://cloud.githubusercontent.com/assets/20930745/19756663/9b7d3d84-9c1e-11e6-9b46-eb575cf049a1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19756674/a84868e0-9c1e-11e6-9fbf-3079a9f134d3.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** LINER: Highlighter for Web
**Bundle ID:** com.aurumplanet.Liner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955395198">955395198</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/liner-highlighter-for-web/id955395198?mt=8&uo=4">https://itunes.apple.com/us/app/liner-highlighter-for-web/id955395198?mt=8&uo=4</a>
**App Version:** 5.0.0
**Seller:** Aurumplanet Co. Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/liner/id955395197?uo=4">© Liner</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple115/v4/22/44/6d/22446d70-45ae-31e4-a308-1cd031323572/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41805859-7ec28194-76b1-11e8-9a82-0376cc5c9765.png)
https://user-images.githubusercontent.com/2068130/41805859-7ec28194-76b1-11e8-9a82-0376cc5c9765.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41805862-8e384366-76b1-11e8-957a-c18d0a8474c2.png
