### ISSUE TITLE
Adobe Photoshop Fix

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8476]
**App Name:** Adobe Photoshop Fix
**Bundle ID:** com.adobe.photoshop.fix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1033713849">1033713849</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-photoshop-fix/id1033713849?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-photoshop-fix/id1033713849?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/85/0c/5f/850c5fa1-e34d-c215-d960-3183648ba853/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19798097/4c1d9b4a-9cef-11e6-87fa-920e5e1e565a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19798097/4c1d9b4a-9cef-11e6-87fa-920e5e1e565a.png)
https://cloud.githubusercontent.com/assets/2068130/19798097/4c1d9b4a-9cef-11e6-87fa-920e5e1e565a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19798106/5a9c5c1a-9cef-11e6-946a-675d86d67587.png
