### ISSUE TITLE
Adobe Connect Mobile

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8477]
**App Name:** Adobe Connect Mobile
**Bundle ID:** com.adobe.connect.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=430437503">430437503</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-connect-mobile/id430437503?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-connect-mobile/id430437503?mt=8&uo=4</a>
**App Version:** 2.5.4
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/72/5a/f5/725af532-5907-a002-fb7c-89958380c94f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19771259/9be29bae-9c62-11e6-8910-e43ead4b2ac2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19771259/9be29bae-9c62-11e6-8910-e43ead4b2ac2.png)
https://cloud.githubusercontent.com/assets/20930745/19771259/9be29bae-9c62-11e6-8910-e43ead4b2ac2.png

Source:
(https://cloud.githubusercontent.com/assets/20930745/19771271/a762bc02-9c62-11e6-8cd9-50530d5a2a7e.png
