### ISSUE TITLE
Adobe Sign – Form Filler

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8479]
**App Name:** Adobe Sign – Form Filler
**Bundle ID:** com.adobe.echosign.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=481082197">481082197</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/adobe-sign-form-filler/id481082197?uo=4">https://apps.apple.com/us/app/adobe-sign-form-filler/id481082197?uo=4</a>
**App Version:** 3.23.1
**Seller:** Adobe Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/adobe-inc/id331646274?uo=4">© Adobe Inc.</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/16/63/e2/1663e23c-8953-3c80-da71-ca39b1301695/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86528599-e04b4080-bea9-11ea-90aa-6d49dbec4aba.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19770952/7d925f14-9c61-11e6-955e-1249f7977291.png)
https://cloud.githubusercontent.com/assets/20930745/19770952/7d925f14-9c61-11e6-955e-1249f7977291.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19770964/8bb8e36a-9c61-11e6-804e-ed4bbe5f771a.png

**Comment by alpcinar** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/86528599-e04b4080-bea9-11ea-90aa-6d49dbec4aba.png)
https://user-images.githubusercontent.com/2068130/86528599-e04b4080-bea9-11ea-90aa-6d49dbec4aba.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/86528605-efca8980-bea9-11ea-8e1d-a719dfb615da.png
