### ISSUE TITLE
MovieTickets.com - Showtimes and Tickets

### ISSUE THREAD

**Issue by cclloyd** [glasklart/hd#848]
**App Name:** MovieTickets.com - Showtimes and Tickets
**Bundle ID:** com.movietickets.MovieTickets
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=402114309">402114309</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/movietickets.com-showtimes/id402114309?mt=8&uo=4">https://itunes.apple.com/us/app/movietickets.com-showtimes/id402114309?mt=8&uo=4</a>
**App Version:** 2.8.2
**Seller:** MovieTickets.com Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/movietickets.com-inc/id402114312?uo=4>© MovieTickets.com, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/12/b7/8c/12b78c43-997f-058a-8a8b-63146ffb1fe7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409736/0282f674-92db-11e6-949f-31605f6ce40c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409736/0282f674-92db-11e6-949f-31605f6ce40c.png)
https://cloud.githubusercontent.com/assets/20930745/19409736/0282f674-92db-11e6-949f-31605f6ce40c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409737/1140c3d0-92db-11e6-963e-14e7e6a42115.png
