### ISSUE TITLE
Adobe Digital Editions

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8480]
**App Name:** Adobe Digital Editions
**Bundle ID:** com.adobe.ADE
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=952977781">952977781</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-digital-editions/id952977781?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-digital-editions/id952977781?mt=8&uo=4</a>
**App Version:** 4.5.2
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/d1/55/1b/d1551b80-4d19-7259-7958-a2a0f833e5b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19771985/090d6612-9c65-11e6-8894-f2b07f78ebfe.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19771985/090d6612-9c65-11e6-8894-f2b07f78ebfe.png)
https://cloud.githubusercontent.com/assets/20930745/19771985/090d6612-9c65-11e6-8894-f2b07f78ebfe.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19772008/1ac03c86-9c65-11e6-9cb0-76d1cea041ad.png
