### ISSUE TITLE
MAX. The Creativity Conference.

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8482]
**App Name:** MAX. The Creativity Conference.
**Bundle ID:** com.adobe.conference.maxcompanion2011
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=464954940">464954940</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/max.-creativity-conference./id464954940?mt=8&uo=4">https://itunes.apple.com/us/app/max.-creativity-conference./id464954940?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/42/4d/4a/424d4a97-2311-549a-bd17-7aa067833eec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19797009/969039dc-9ce8-11e6-813d-1e163e1fba84.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19796990/779d76de-9ce8-11e6-854c-5244a7b86c52.png)
https://cloud.githubusercontent.com/assets/20930745/19796990/779d76de-9ce8-11e6-854c-5244a7b86c52.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19796998/83e4ea62-9ce8-11e6-92b8-f02119e5cac3.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19797009/969039dc-9ce8-11e6-813d-1e163e1fba84.png)
https://cloud.githubusercontent.com/assets/20930745/19797009/969039dc-9ce8-11e6-813d-1e163e1fba84.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19797020/a0fa1f82-9ce8-11e6-92f5-ae9599fde1da.png

**Comment by dreamnet** [comment]
@Trubbel ❓

**Comment by Trubbel** [comment]
I guess we can go with the second one.
