### ISSUE TITLE
Adobe Experience Design

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8483]
**App Name:** Adobe Experience Design
**Bundle ID:** com.adobe.xd.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1146597773">1146597773</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-experience-design/id1146597773?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-experience-design/id1146597773?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/bd/8b/03/bd8b038c-7532-27e6-c3b1-313e695c84bd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19772179/acecad6a-9c65-11e6-8ee0-fcece358affa.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19772179/acecad6a-9c65-11e6-8ee0-fcece358affa.png)
https://cloud.githubusercontent.com/assets/20930745/19772179/acecad6a-9c65-11e6-8ee0-fcece358affa.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19772191/ba7295da-9c65-11e6-98de-fb5c46cbc1f7.png
