### ISSUE TITLE
Adobe Scout

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8484]
**App Name:** Adobe Scout
**Bundle ID:** com.adobe.monocle.companion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=562450748">562450748</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adobe-scout/id562450748?mt=8&uo=4">https://itunes.apple.com/us/app/adobe-scout/id562450748?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/adobe/id331646274?uo=4>© Adobe</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/1c/14/fb/1c14fbd0-388c-6f80-32e1-0cf4b683ac8e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19772342/2b004b80-9c66-11e6-83bf-8f1470f05990.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19772342/2b004b80-9c66-11e6-83bf-8f1470f05990.png)
https://cloud.githubusercontent.com/assets/20930745/19772342/2b004b80-9c66-11e6-83bf-8f1470f05990.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19772360/37ab4e52-9c66-11e6-9905-1bad4f88c80b.png
