### ISSUE TITLE
PhoneGap Developer

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8485]
**App Name:** PhoneGap Developer
**Bundle ID:** com.adobe.phonegap.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=843536693">843536693</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/phonegap-developer/id843536693?mt=8&uo=4">https://itunes.apple.com/us/app/phonegap-developer/id843536693?mt=8&uo=4</a>
**App Version:** 1.7.2
**Seller:** Adobe Systems, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/adobe/id331646274?uo=4">© Adobe</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple41/v4/d2/3e/b4/d23eb44a-6432-5446-96f1-ba1766afa9f1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20028990/902c88f8-a340-11e6-93c0-046b5d0c2845.png)

**Comment by 2Qt2beStr8** [comment]
?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19797608/83b29874-9cec-11e6-952e-09804dbcfdc5.png)
https://cloud.githubusercontent.com/assets/20930745/19797608/83b29874-9cec-11e6-952e-09804dbcfdc5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19797646/ac8c5730-9cec-11e6-8184-153a3e594e6c.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20028990/902c88f8-a340-11e6-93c0-046b5d0c2845.png)
https://cloud.githubusercontent.com/assets/2068130/20028990/902c88f8-a340-11e6-93c0-046b5d0c2845.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20028991/9df420a4-a340-11e6-84c5-6e9f07f26531.png
