### ISSUE TITLE
Leafs Mobile

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8492]
**App Name:** Leafs Mobile
**Bundle ID:** com.torontomapleleafs.MapleLeafs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571767665">571767665</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/leafs-mobile/id571767665?mt=8&uo=4">https://itunes.apple.com/us/app/leafs-mobile/id571767665?mt=8&uo=4</a>
**App Version:** 17.1
**Seller:** Maple Leaf Sports & Entertainment
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/maple-leaf-sports-entertainment/id475848715?uo=4>© Maple Leaf Sports & Entertainment</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/ec/09/67/ec096796-5565-166f-36ab-ffd5efd664a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19803101/3145fb88-9d07-11e6-8e10-1c0a8554ed16.png)

**Comment by dreamnet** [comment]
Icon [exists](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.torontomapleleafs.MapleLeafs-large.png), but needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19803101/3145fb88-9d07-11e6-8e10-1c0a8554ed16.png)
https://cloud.githubusercontent.com/assets/20930745/19803101/3145fb88-9d07-11e6-8e10-1c0a8554ed16.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19803115/443cbfe2-9d07-11e6-97cb-b83708a2d563.png
