### ISSUE TITLE
tramTRACKER

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8518]
**App Name:** tramTRACKER
**Bundle ID:** au.com.yarratrams.tramtracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=317312510">317312510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tramtracker/id317312510?mt=8&uo=4">https://itunes.apple.com/us/app/tramtracker/id317312510?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** Yarra Trams
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yarra-trams/id317312513?uo=4>© Yarra Trams</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/bd/21/1e/bd211ea1-ef9d-c75d-7413-83fd6eb499ff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19828595/a3fc440c-9dca-11e6-80a2-170df9e6a13b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19809384/6c2f194c-9d29-11e6-9e44-d2b81a916790.png)
https://cloud.githubusercontent.com/assets/20930745/19809384/6c2f194c-9d29-11e6-9e44-d2b81a916790.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19809393/79d2ded0-9d29-11e6-92a4-7558fe480ca0.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Hm. Maybe inverted...
