### ISSUE TITLE
Bragi

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8526]
**App Name:** Bragi
**Bundle ID:** com.bragi.dash.consumer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1038828258">1038828258</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bragi/id1038828258?mt=8&uo=4">https://itunes.apple.com/us/app/bragi/id1038828258?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** BRAGI GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/bragi-gmbh/id1038828257?uo=4>© BRAGI GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/ea/c3/ab/eac3abc1-5fde-af3d-7443-1967c225c541/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19813844/c6899cb6-9d3b-11e6-8760-6acde2d8e16b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19813844/c6899cb6-9d3b-11e6-8760-6acde2d8e16b.png)
https://cloud.githubusercontent.com/assets/20930745/19813844/c6899cb6-9d3b-11e6-8760-6acde2d8e16b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19813861/dd6243de-9d3b-11e6-89f3-11fa5261e133.png
