### ISSUE TITLE
Sonic CD

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8527]
**App Name:** Sonic CD
**Bundle ID:** com.sega.soniccd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454316134">454316134</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sonic-cd/id454316134?mt=8&uo=4">https://itunes.apple.com/us/app/sonic-cd/id454316134?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Sega America
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/sega/id281966698?mt=8&uo=4>© SEGA</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/7c/d8/68/7cd86897-f076-9486-f793-68e1384731c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20032694/733dafa6-a390-11e6-9804-969274a30a37.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20030185/0ff5d8c2-a360-11e6-8b64-7b2714a7a6ef.png)
https://cloud.githubusercontent.com/assets/2068130/20030185/0ff5d8c2-a360-11e6-8b64-7b2714a7a6ef.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20030189/1eba99a6-a360-11e6-8449-b83b8a9daefb.png
