### ISSUE TITLE
Stringly - Micro Memos and Personal Thought Collector

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8533]
**App Name:** Stringly - Micro Memos and Personal Thought Collector
**Bundle ID:** com.fishingtonstudios.ijournaliphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=435000020">435000020</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stringly-micro-memos-personal/id435000020?mt=8&uo=4">https://itunes.apple.com/us/app/stringly-micro-memos-personal/id435000020?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Fishington Studios
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fishington-studios/id344044425?uo=4>© Fishington Studios</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/bf/bf/b8/bfbfb8d8-36df-cad1-fd0a-41038d7a8f8a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19822591/8af5973a-9d64-11e6-9bba-920fb374d189.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19822486/02762ab4-9d64-11e6-94fd-32f1c2952cdc.png)
https://cloud.githubusercontent.com/assets/20930745/19822486/02762ab4-9d64-11e6-94fd-32f1c2952cdc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19822501/1938c374-9d64-11e6-9557-584af4cb0c81.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19822591/8af5973a-9d64-11e6-9bba-920fb374d189.png)
https://cloud.githubusercontent.com/assets/20930745/19822591/8af5973a-9d64-11e6-9bba-920fb374d189.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19822596/97eeaf26-9d64-11e6-965f-734b9d953ec8.png
