### ISSUE TITLE
MyWeather - 10-Day Weather Forecast

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8534]
**App Name:** MyWeather - 10-Day Weather Forecast
**Bundle ID:** com.chii.MyWeather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1003715695">1003715695</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myweather-10-day-weather-forecast/id1003715695?mt=8&uo=4">https://itunes.apple.com/us/app/myweather-10-day-weather-forecast/id1003715695?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Yiming Shen
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yiming-shen/id364264742?uo=4>© Yiming Shen</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/02/79/13/02791342-2174-7208-0f08-a6bf6b5f97f3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19832487/dce0ae0c-9e24-11e6-9ada-e36bec473e3f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19832487/dce0ae0c-9e24-11e6-9ada-e36bec473e3f.png)
https://cloud.githubusercontent.com/assets/2068130/19832487/dce0ae0c-9e24-11e6-9ada-e36bec473e3f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19832493/ec4bcb9c-9e24-11e6-8389-0daa79654c35.png
