### ISSUE TITLE
XFINITY TV  X1 Remote

### ISSUE THREAD

**Issue by cclloyd** [glasklart/hd#855]
**App Name:** XFINITY TV  X1 Remote
**Bundle ID:** com.comcast.cim.X1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527726789">527726789</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xfinity-tv-x1-remote/id527726789?mt=8&uo=4">https://itunes.apple.com/us/app/xfinity-tv-x1-remote/id527726789?mt=8&uo=4</a>
**App Version:** 1.4.3
**Seller:** Comcast Interactive Media
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/comcast/id298960160?uo=4>© Comcast</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/b8/a7/0a/b8a70a30-abc3-a744-c4d7-3d4e18008ee0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18742741/2875bbbe-80b6-11e6-9ce9-1007c6ca0433.png)

**Comment by Sly-Fi** [comment]
This icon is missing from 5.0 release

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18722633/c5d2ea34-8035-11e6-992d-a96986ade6e0.png)
https://cloud.githubusercontent.com/assets/20930745/18722633/c5d2ea34-8035-11e6-992d-a96986ade6e0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18722657/db68c6f2-8035-11e6-979b-7eea2f427976.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18742741/2875bbbe-80b6-11e6-9ce9-1007c6ca0433.png)
https://cloud.githubusercontent.com/assets/20930745/18742741/2875bbbe-80b6-11e6-9ce9-1007c6ca0433.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18742807/69de9fee-80b6-11e6-8610-f969d48f5d4b.png

**Comment by ivanov007** [comment]
yes I think the second one will do it since there are several apps like this
