### ISSUE TITLE
Ticketfly - Buy tickets for live events near you

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8550]
**App Name:** Ticketfly - Buy tickets for live events near you
**Bundle ID:** com.ticketfly.attendeeapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943114354">943114354</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ticketfly-buy-tickets-for/id943114354?mt=8&uo=4">https://itunes.apple.com/us/app/ticketfly-buy-tickets-for/id943114354?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** Ticketfly, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ticketfly/id535255555?uo=4">© Ticketfly</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/c5/4f/8f/c54f8f1f-4c17-c72c-9239-a543794e828c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19984834/5d9dd1ac-a210-11e6-870c-554a7b813a8b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19984834/5d9dd1ac-a210-11e6-870c-554a7b813a8b.png)
https://cloud.githubusercontent.com/assets/20930745/19984834/5d9dd1ac-a210-11e6-870c-554a7b813a8b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19984869/7a21420a-a210-11e6-8623-b167d499a209.png
