### ISSUE TITLE
Abercrombie & Fitch

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8551]
**App Name:** Abercrombie & Fitch
**Bundle ID:** com.abercrombie.anfiphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=339041767">339041767</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/abercrombie-fitch/id339041767?uo=4">https://apps.apple.com/us/app/abercrombie-fitch/id339041767?uo=4</a>
**App Version:** 4.24.0
**Seller:** Abercrombie & Fitch
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/abercrombie-fitch/id339041770?uo=4">© Abercrombie & Fitch</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/85/ba/d1/85bad1a0-ca4f-f44b-8f4a-f8bcaba6945c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979600-3aa09880-95ea-11e9-8782-5c5c7aa6a02b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19985856/e2d0be4e-a214-11e6-8add-fa67dc143593.png)
https://cloud.githubusercontent.com/assets/20930745/19985856/e2d0be4e-a214-11e6-8add-fa67dc143593.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19985893/fd2e0d6e-a214-11e6-9709-c7bf9f6378c5.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38454988-b7c173aa-3a71-11e8-9caf-569392954611.png)
https://user-images.githubusercontent.com/20930745/38454988-b7c173aa-3a71-11e8-9caf-569392954611.png

Source:
https://user-images.githubusercontent.com/20930745/38454994-c8ac35d8-3a71-11e8-9487-9633da99d8fa.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19985856/e2d0be4e-a214-11e6-8add-fa67dc143593.png)
https://cloud.githubusercontent.com/assets/20930745/19985856/e2d0be4e-a214-11e6-8add-fa67dc143593.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19985893/fd2e0d6e-a214-11e6-9709-c7bf9f6378c5.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Huh... a bit too big?
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979600-3aa09880-95ea-11e9-8782-5c5c7aa6a02b.png)
https://user-images.githubusercontent.com/2068130/59979600-3aa09880-95ea-11e9-8782-5c5c7aa6a02b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979603-48eeb480-95ea-11e9-9c3d-07f1279f06b8.png
