### ISSUE TITLE
 Flowing ~ Meditation & Mindfulness

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8563]
**App Name:** Flowing ~ Meditation & Mindfulness
**Bundle ID:** com.taptanium.flowy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1132992868">1132992868</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flowing-meditation-mindfulness/id1132992868?mt=8&uo=4">https://itunes.apple.com/us/app/flowing-meditation-mindfulness/id1132992868?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Franz Bruckhoff
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/franz-bruckhoff/id399345216?uo=4">© Franz Bruckhoff</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/3f/08/84/3f08843e-588d-18e1-3b2d-3d6d4d012470/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19996076/483e5942-a25d-11e6-9e64-3a2a384134e4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19996076/483e5942-a25d-11e6-9e64-3a2a384134e4.png)
https://cloud.githubusercontent.com/assets/2068130/19996076/483e5942-a25d-11e6-9e64-3a2a384134e4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19996086/583bea6c-a25d-11e6-8ae9-eb35b874f2a9.png
