### ISSUE TITLE
Icon Project (Home Screen Icon)

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#858]
**App Name:** Icon Project (Home Screen Icon)
**Bundle ID:** com.fmproject.iconfactory
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=434277910">434277910</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/icon-project-home-screen-icon/id434277910?mt=8&uo=4">https://itunes.apple.com/us/app/icon-project-home-screen-icon/id434277910?mt=8&uo=4</a>
**App Version:** 1.31
**Seller:** FMPROJECT
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fmproject/id373494128?uo=4">© FMPROJECT</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/c0/e3/8c/c0e38c2d-c7bf-aaf8-1cf9-6bfd34b2535b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20215337/cad430a0-a813-11e6-8cbd-252613975d94.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20215337/cad430a0-a813-11e6-8cbd-252613975d94.png)
https://cloud.githubusercontent.com/assets/20930745/20215337/cad430a0-a813-11e6-8cbd-252613975d94.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20215361/f0c90d1c-a813-11e6-826a-898764401c74.png
