### ISSUE TITLE
Edge

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8584]
**App Name:** Edge
**Bundle ID:** net.mobigame.Edge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300896018">300896018</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/edge/id300896018?mt=8&uo=4">https://itunes.apple.com/us/app/edge/id300896018?mt=8&uo=4</a>
**App Version:** 2.20
**Seller:** Mobigame
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mobigame/id300896021?uo=4">© Mobigame</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/a7/b3/5c/a7b35c20-fd22-296c-1919-4eec0bf3d1e3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20012750/cc1e12ea-a2b0-11e6-93c2-c80c50b50f02.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20012750/cc1e12ea-a2b0-11e6-93c2-c80c50b50f02.png)
https://cloud.githubusercontent.com/assets/20930745/20012750/cc1e12ea-a2b0-11e6-93c2-c80c50b50f02.png)


Source:
https://cloud.githubusercontent.com/assets/20930745/20012778/e6c6033c-a2b0-11e6-8c76-f82a6d58044f.png

**Comment by dreamnet** [comment]
Same as #2639.
