### ISSUE TITLE
Grand Theft Auto III: Deutsche Version

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8586]
**App Name:** Grand Theft Auto III: Deutsche Version
**Bundle ID:** com.rockstargames.gta3gerios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487339330">487339330</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/grand-theft-auto-iii-deutsche/id487339330?mt=8&uo=4">https://itunes.apple.com/de/app/grand-theft-auto-iii-deutsche/id487339330?mt=8&uo=4</a>
**App Version:** 1.3.5
**Seller:** Rockstar Games, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/rockstar-games/id330049731?uo=4">© Rockstar Games</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/e2/9f/21/e29f218c-8666-aa27-0c91-9020ad86f7ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20013360/1d9054ce-a2b3-11e6-8e97-ed8bfffb847c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20013389/3aa95e7a-a2b3-11e6-9af0-af6d5b20cac9.png)
https://cloud.githubusercontent.com/assets/20930745/20013389/3aa95e7a-a2b3-11e6-9af0-af6d5b20cac9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20013400/46a56af2-a2b3-11e6-84c9-52901d9d3a05.png

**Comment by dreamnet** [comment]
Same as #293.
