### ISSUE TITLE
Syfy Now

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#859]
**App Name:** Syfy Now
**Bundle ID:** com.nbcuni.syfy.syfychannel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378092432">378092432</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/syfy-now/id378092432?mt=8&uo=4">https://itunes.apple.com/us/app/syfy-now/id378092432?mt=8&uo=4</a>
**App Version:** 5.3.0
**Seller:** NBCUniversal Media, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/nbcuniversal-media-llc/id303544359?uo=4>© NBCUniversal Media, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/51/35/9a/51359a52-3362-c02d-1e09-fd3f03eb7c9f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409797/810723a2-92dc-11e6-84d6-26466698b155.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409761/c6cf46ae-92db-11e6-94ea-bfda5565b3cc.png)
https://cloud.githubusercontent.com/assets/20930745/19409761/c6cf46ae-92db-11e6-94ea-bfda5565b3cc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409764/d4343ef8-92db-11e6-85ae-3665b651997c.png
