### ISSUE TITLE
CLZ Games

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8594]
**App Name:** CLZ Games
**Bundle ID:** com.collectorz.clzgames
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=319036253">319036253</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/clz-games/id319036253?uo=4">https://apps.apple.com/us/app/clz-games/id319036253?uo=4</a>
**App Version:** 4.14.2
**Seller:** Bitz & Pixelz BV
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/collectorz-com/id314588588?uo=4">© Collectorz.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/12/f4/a6/12f4a69b-64be-6d25-5238-3af7c2513134/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60370957-2b5d8880-99f8-11e9-8ab9-97b2b22e1a3b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20017524/5311066e-a2c4-11e6-8661-207fa8c2538d.png)
https://cloud.githubusercontent.com/assets/20930745/20017524/5311066e-a2c4-11e6-8661-207fa8c2538d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20017547/6be14f00-a2c4-11e6-8781-3bdb7087dc6b.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60370957-2b5d8880-99f8-11e9-8ab9-97b2b22e1a3b.png)
https://user-images.githubusercontent.com/2068130/60370957-2b5d8880-99f8-11e9-8ab9-97b2b22e1a3b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60370978-3d3f2b80-99f8-11e9-805c-ddd9b93ca825.png
