### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#860]
**App Name:** Money
**Bundle ID:** com.ibearsoft.money5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=408818815">408818815</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/money/id408818815?mt=8&uo=4">https://itunes.apple.com/us/app/money/id408818815?mt=8&uo=4</a>
**App Version:** 6.6.12
**Seller:** iBear LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ibear-llc/id347886453?uo=4">© iBear LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/0c/e7/0e/0ce70ed3-33f7-8f81-1fc1-4fec439605be/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37567883-af5ddf22-2acd-11e8-9266-b66bfa2d7480.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37567883-af5ddf22-2acd-11e8-9266-b66bfa2d7480.png)
https://user-images.githubusercontent.com/2068130/37567883-af5ddf22-2acd-11e8-9266-b66bfa2d7480.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37567887-bd79745e-2acd-11e8-96e4-863eff1c15f4.png
