### ISSUE TITLE
Copied

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8623]
**App Name:** Copied
**Bundle ID:** com.udoncode.copied
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1015767349">1015767349</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/copied/id1015767349?uo=4">https://apps.apple.com/us/app/copied/id1015767349?uo=4</a>
**App Version:** 3.0.7
**Seller:** Kevin Chang
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kevin-chang/id1015767348?uo=4">© Kevin Chang</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/88/6f/af/886faf95-b7f9-9824-719f-5d81464d1c23/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60380584-638cb780-9a48-11e9-90cb-6e3f2217055c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20108245/ab5c1fa6-a5db-11e6-9810-40fe41b91d9d.png)
https://cloud.githubusercontent.com/assets/20930745/20108245/ab5c1fa6-a5db-11e6-9810-40fe41b91d9d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20108265/b97cc9dc-a5db-11e6-8fbd-8584f8a58efd.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60380584-638cb780-9a48-11e9-90cb-6e3f2217055c.png)
https://user-images.githubusercontent.com/2068130/60380584-638cb780-9a48-11e9-90cb-6e3f2217055c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60380590-72736a00-9a48-11e9-917b-d7039795aa3e.png
