### ISSUE TITLE
iStatistica

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8624]
**App Name:** iStatistica
**Bundle ID:** imagetasks.ios.iStatistica
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1126874522">1126874522</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/istatistica/id1126874522?mt=8&uo=4">https://itunes.apple.com/us/app/istatistica/id1126874522?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Andrey Tsarkov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/andrey-tsarkov/id450316587?uo=4">© Andrey Tsarkov</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/b4/11/22/b41122fe-4c95-8894-df79-b254918c5068/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20108017/f3b5eb98-a5da-11e6-9157-c40b4783a27c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20108017/f3b5eb98-a5da-11e6-9157-c40b4783a27c.png)
https://cloud.githubusercontent.com/assets/20930745/20108017/f3b5eb98-a5da-11e6-9157-c40b4783a27c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20108041/06952c2e-a5db-11e6-88cc-23a2949d767b.png
