### ISSUE TITLE
World Time Clock Widget - For Timezones

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8625]
**App Name:** World Time Clock Widget - For Timezones
**Bundle ID:** com.lasmit.World-Time
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=912698955">912698955</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/world-time-clock-widget-for/id912698955?mt=8&uo=4">https://itunes.apple.com/us/app/world-time-clock-widget-for/id912698955?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Lewis Smith
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lasmit/id535281397?uo=4">© Lasmit</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/fd/70/c5/fd70c5e6-d2ca-fbbb-54d9-be7813c4560b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20134005/114555ba-a66a-11e6-9951-152da613d8e1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20134005/114555ba-a66a-11e6-9951-152da613d8e1.png)
https://cloud.githubusercontent.com/assets/20930745/20134005/114555ba-a66a-11e6-9951-152da613d8e1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20134022/1fdef8d8-a66a-11e6-8db5-e77c189bbc03.png
