### ISSUE TITLE
Nitrado Server Manager

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8626]
**App Name:** Nitrado Server Manager
**Bundle ID:** net.nitrado.server
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=495161830">495161830</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nitrado-server-manager/id495161830?mt=8&uo=4">https://itunes.apple.com/us/app/nitrado-server-manager/id495161830?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** marbis GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nitrado/id1039794090?uo=4">© Nitrado</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple5/v4/fe/8d/ed/fe8ded80-e71e-f2c7-a5df-6778363eac63/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20133324/678298a0-a667-11e6-9889-951d3ccc5245.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20133324/678298a0-a667-11e6-9889-951d3ccc5245.png)
https://cloud.githubusercontent.com/assets/20930745/20133324/678298a0-a667-11e6-9889-951d3ccc5245.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20133363/8b0abfb4-a667-11e6-8563-f26c646fd323.png
