### ISSUE TITLE
Uber

### ISSUE THREAD

**Issue by rentiak** [glasklart/hd#864]
**App Name:** Uber
**Bundle ID:** com.ubercab.UberClient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=368677368">368677368</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/uber/id368677368?mt=8&uo=4">https://itunes.apple.com/us/app/uber/id368677368?mt=8&uo=4</a>
**App Version:** 3.317.10003
**Seller:** Uber Technologies, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/uber-technologies-inc/id368677371?uo=4">© Uber Technologies, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/79/66/c0/7966c050-6b23-17a7-5621-e9835bace4d7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45944905-1af12b00-bfec-11e8-91e1-aeffb6cd1c3d.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11248526/d3d353be-8e21-11e5-9f42-4b76297c01af.png)
https://cloud.githubusercontent.com/assets/10730122/11248526/d3d353be-8e21-11e5-9f42-4b76297c01af.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11248521/d0c73d02-8e21-11e5-8a46-86dfed2019ff.png

**Comment by Trubbel** [comment]
Icon needs to be updated.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13556733/5d0d688a-e3e1-11e5-8cf9-a0b7ef0ba4f1.png)
https://cloud.githubusercontent.com/assets/2068130/13556733/5d0d688a-e3e1-11e5-8cf9-a0b7ef0ba4f1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13556734/6cbf492e-e3e1-11e5-9c0d-c977ccd23e49.png

**Comment by Anuskuss** [comment]
@dreamnet Yet again, could you remove those lines for me :smile:

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13721478/0de8b128-e829-11e5-9c0c-8fcac3204863.png)
https://cloud.githubusercontent.com/assets/2068130/13721478/0de8b128-e829-11e5-9c0c-8fcac3204863.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13721479/1dcd1e58-e829-11e5-920e-6cc4ce677d38.png

**Comment by Anuskuss** [comment]
@dreamnet I like it better, and you?

**Comment by dreamnet** [comment]
@Anuskuss Yes, it's better without the lines in the background.

**Comment by XPEric** [comment]
Needs update.
