### ISSUE TITLE
Marvel Unlimited Comics

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8641]
**App Name:** Marvel Unlimited Comics
**Bundle ID:** com.marvel.unlimited
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=607205403">607205403</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/marvel-unlimited-comics/id607205403?mt=8&uo=4">https://itunes.apple.com/us/app/marvel-unlimited-comics/id607205403?mt=8&uo=4</a>
**App Version:** 2.9.3
**Seller:** Marvel Entertainment
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marvel-entertainment/id350027742?uo=4">© Marvel Entertainment</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/fa/c0/71/fac071c7-eb05-d8c9-6602-cbd96e24c079/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20225500/0b4d909c-a844-11e6-962e-1e12d2456528.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20225500/0b4d909c-a844-11e6-962e-1e12d2456528.png)
https://cloud.githubusercontent.com/assets/20930745/20225500/0b4d909c-a844-11e6-962e-1e12d2456528.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20225510/1829918a-a844-11e6-8266-d242a65704df.png
