### ISSUE TITLE
Bershka

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8642]
**App Name:** Bershka
**Bundle ID:** com.inditex.bershka
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=427769832">427769832</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bershka/id427769832?mt=8&uo=4">https://itunes.apple.com/us/app/bershka/id427769832?mt=8&uo=4</a>
**App Version:** 7.5.0
**Seller:** Industria de Diseno Textil, S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inditex/id341323285?uo=4">© INDITEX</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/32/14/37/3214370e-122c-c604-2e7b-735cd8c50379/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20225131/0a185380-a842-11e6-8884-1a280dc9fa39.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20225131/0a185380-a842-11e6-8884-1a280dc9fa39.png)
https://cloud.githubusercontent.com/assets/20930745/20225131/0a185380-a842-11e6-8884-1a280dc9fa39.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20225153/20ef0b8a-a842-11e6-902d-436d85681b02.png
