### ISSUE TITLE
Oysho

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8643]
**App Name:** Oysho
**Bundle ID:** com.inditex.oysho
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=464273021">464273021</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/oysho/id464273021?mt=8&uo=4">https://itunes.apple.com/us/app/oysho/id464273021?mt=8&uo=4</a>
**App Version:** 7.2
**Seller:** Industria de Diseno Textil, S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inditex/id341323285?uo=4">© INDITEX</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/08/a2/4a/08a24a3f-e223-610a-c32e-eb19e9397818/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20236180/de81659e-a8ab-11e6-8951-395be22bc59c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20236180/de81659e-a8ab-11e6-8951-395be22bc59c.png)
https://cloud.githubusercontent.com/assets/2068130/20236180/de81659e-a8ab-11e6-8951-395be22bc59c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20236181/ec5f90dc-a8ab-11e6-84de-9515f852c746.png
