### ISSUE TITLE
Uterqüe Shop Online

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8644]
**App Name:** Uterqüe Shop Online
**Bundle ID:** com.inditex.ecommerce.uterque
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465315324">465315324</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/uterq%C3%BCe-shop-online/id465315324?mt=8&uo=4">https://itunes.apple.com/us/app/uterq%C3%BCe-shop-online/id465315324?mt=8&uo=4</a>
**App Version:** 7.0.6
**Seller:** Industria de Diseno Textil, S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inditex/id341323285?mt=8&uo=4">© INDITEX</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/9b/78/4f/9b784f38-dae0-04a0-58ff-f9eaccde5cc6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54822479-51f77f00-4ca5-11e9-8e43-d825e8b3b2f3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20228248/c3f5f524-a850-11e6-9e3f-6a7bc258fcca.png)
https://cloud.githubusercontent.com/assets/20930745/20228248/c3f5f524-a850-11e6-9e3f-6a7bc258fcca.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20228263/d1a17478-a850-11e6-83aa-aa6a38ec274b.png

**Comment by alpcinar** [comment]
Needs update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54822479-51f77f00-4ca5-11e9-8e43-d825e8b3b2f3.png)
https://user-images.githubusercontent.com/20930745/54822479-51f77f00-4ca5-11e9-8e43-d825e8b3b2f3.png

Source:
https://user-images.githubusercontent.com/20930745/54822482-53c14280-4ca5-11e9-9918-cb444d5f3a1e.png
