### ISSUE TITLE
Stradivarius

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8645]
**App Name:** Stradivarius
**Bundle ID:** com.inditex.stradivarius
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=421874087">421874087</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stradivarius/id421874087?mt=8&uo=4">https://itunes.apple.com/us/app/stradivarius/id421874087?mt=8&uo=4</a>
**App Version:** 7.5
**Seller:** Industria de Diseno Textil, S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inditex/id341323285?uo=4">© INDITEX</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/e1/d5/94/e1d5942c-426f-4fbe-ca6b-ed8399eabc97/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20224965/3fa8812e-a841-11e6-88f0-d11bf3d3430f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20224965/3fa8812e-a841-11e6-88f0-d11bf3d3430f.png)
https://cloud.githubusercontent.com/assets/20930745/20224965/3fa8812e-a841-11e6-88f0-d11bf3d3430f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20224985/57930002-a841-11e6-813a-98969245e850.png
