### ISSUE TITLE
Massimo Dutti

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8646]
**App Name:** Massimo Dutti
**Bundle ID:** com.inditex.massimodutti
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=373282826">373282826</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/massimo-dutti/id373282826?mt=8&uo=4">https://itunes.apple.com/us/app/massimo-dutti/id373282826?mt=8&uo=4</a>
**App Version:** 9.5.1
**Seller:** Industria de Diseno Textil, S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inditex/id341323285?mt=8&uo=4">© INDITEX</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/ec/c9/fa/ecc9fa6c-414f-a12d-6ac7-36f508f52449/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54822803-0ee9db80-4ca6-11e9-9797-3411383f78bd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20225318/0a4f295e-a843-11e6-9ddb-1d2c1f163751.png)
https://cloud.githubusercontent.com/assets/20930745/20225318/0a4f295e-a843-11e6-9ddb-1d2c1f163751.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20225337/1840f2cc-a843-11e6-927c-886efdab2b7e.png

**Comment by alpcinar** [comment]
Needs update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54822803-0ee9db80-4ca6-11e9-9797-3411383f78bd.png)
(https://user-images.githubusercontent.com/20930745/54822803-0ee9db80-4ca6-11e9-9797-3411383f78bd.png

Source:
https://user-images.githubusercontent.com/20930745/54822805-101b0880-4ca6-11e9-8d81-ecc4ef5455aa.png
