### ISSUE TITLE
MANGO MNG

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8647]
**App Name:** MANGO MNG
**Bundle ID:** com.mango.2010
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=372216941">372216941</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mango-mng/id372216941?mt=8&uo=4">https://itunes.apple.com/us/app/mango-mng/id372216941?mt=8&uo=4</a>
**App Version:** 3.17
**Seller:** Punto Fa, S.L.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mango/id372216944?uo=4">© Mango</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/00/b5/86/00b58679-816a-e330-f2d1-c560c88d16a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20228122/11cbe638-a850-11e6-8b85-54667dd45ae1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20228122/11cbe638-a850-11e6-8b85-54667dd45ae1.png)
https://cloud.githubusercontent.com/assets/20930745/20228122/11cbe638-a850-11e6-8b85-54667dd45ae1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20228128/1e9e3a96-a850-11e6-9044-ced527c8030d.png
