### ISSUE TITLE
ZaraHome Shop Online

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8648]
**App Name:** ZaraHome Shop Online
**Bundle ID:** com.inditex.ecommerce.zarahome
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=474175190">474175190</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zarahome-shop-online/id474175190?mt=8&uo=4">https://itunes.apple.com/us/app/zarahome-shop-online/id474175190?mt=8&uo=4</a>
**App Version:** 5.7
**Seller:** Industria de Diseno Textil, S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inditex/id341323285?uo=4">© INDITEX</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/17/c7/15/17c715a6-966e-64db-5383-be96d3bbe274/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20228018/9a051a20-a84f-11e6-8672-ab6e0a37ec24.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20228018/9a051a20-a84f-11e6-8672-ab6e0a37ec24.png)
https://cloud.githubusercontent.com/assets/20930745/20228018/9a051a20-a84f-11e6-8672-ab6e0a37ec24.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20228034/ad2c03ac-a84f-11e6-87a7-2aab00dcc0e3.png
