### ISSUE TITLE
Aeternum Compatible?

### ISSUE THREAD

**Issue by Insomniacxx** [glasklart/hd#8649]
Please find a way to make this amazing theme compatible with Aeternum Hives. I've always adored this theme, and it would really complete my jailbreak :) I could donate to help find a way.

**Comment by dreamnet** [comment]
@Insomniacxx It seems to me, that Aeternum Hives is [**not** compatible with the IconBundles method](https://www.reddit.com/r/iOSthemes/comments/2ow0xh/help_bought_aeternum_but_my_theme_isnt_applying/) btw. with [Anemone's -large feature](https://github.com/AnemoneTeam/Anemone/wiki/Home-Screen-Icons). If this is true, we can't do anything to make the theme compatible.
I think the only thing you can do is to write the author of Aeternum Hives. Maybe he can solve this.

**Comment by dreamnet** [comment]
No reaction from @Insomniacxx for one week - closing.
