### ISSUE TITLE
PinOut!

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8653]
**App Name:** PinOut!
**Bundle ID:** com.mediocre.pinout
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1108417718">1108417718</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pinout!/id1108417718?mt=8&uo=4">https://itunes.apple.com/us/app/pinout!/id1108417718?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Mediocre AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mediocre-ab/id431845724?uo=4">© Mediocre AB</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/c0/6c/e1/c06ce158-76ad-700e-311c-314838919546/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20245814/4f5eaee0-a9a9-11e6-91aa-486bf3b7bbde.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20244736/899a44c8-a98d-11e6-99cb-86dea5f4957b.png)
https://cloud.githubusercontent.com/assets/20930745/20244736/899a44c8-a98d-11e6-99cb-86dea5f4957b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20244737/946bc9a8-a98d-11e6-8790-470431f16398.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20245814/4f5eaee0-a9a9-11e6-91aa-486bf3b7bbde.png)
https://cloud.githubusercontent.com/assets/2068130/20245814/4f5eaee0-a9a9-11e6-91aa-486bf3b7bbde.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20245818/5ec938a0-a9a9-11e6-8222-8b9364245f2d.png

**Comment by LaCh0uine** [comment]
I think the version dreamnet is the good one
