### ISSUE TITLE
Lineup Puzzle

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#8654]
**App Name:** Lineup Puzzle
**Bundle ID:** com.wildsnake.lineupT
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1083024864">1083024864</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lineup-puzzle/id1083024864?mt=8&uo=4">https://itunes.apple.com/us/app/lineup-puzzle/id1083024864?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** ANDREY NOVIKOV
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/andrey-novikov/id418898717?uo=4">© ANDREY NOVIKOV</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/47/e8/4d/47e84d33-ed2e-86d9-dc49-d0aba684f673/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20244326/3b3e1b0c-a97d-11e6-94cc-9bc16707f941.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20244326/3b3e1b0c-a97d-11e6-94cc-9bc16707f941.png)
https://cloud.githubusercontent.com/assets/20930745/20244326/3b3e1b0c-a97d-11e6-94cc-9bc16707f941.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20244329/50d9360e-a97d-11e6-8393-152195736672.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20244331/5ee97a38-a97d-11e6-8126-48f9c4e8ca37.png)
https://cloud.githubusercontent.com/assets/20930745/20244331/5ee97a38-a97d-11e6-8126-48f9c4e8ca37.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20244332/6c821dda-a97d-11e6-9cd3-7f7835725487.png

**Comment by LaCh0uine** [comment]
Yeah the first one 👍🏻👍🏻
Thank you

**Comment by dreamnet** [comment]
@LaCh0uine OK!
