### ISSUE TITLE
Fitbit

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#866]
**App Name:** Fitbit
**Bundle ID:** com.fitbit.FitbitMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=462638897">462638897</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fitbit/id462638897?mt=8&uo=4">https://itunes.apple.com/us/app/fitbit/id462638897?mt=8&uo=4</a>
**App Version:** 2.28
**Seller:** Fitbit, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/fitbit-inc./id462638900?uo=4>© Fitbit, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/56/1a/01/561a01c4-8789-50e0-9d92-ff71385e0225/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19321392/2ea1693e-90b5-11e6-9e29-715a3cea1e27.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19321392/2ea1693e-90b5-11e6-9e29-715a3cea1e27.png)
https://cloud.githubusercontent.com/assets/20930745/19321392/2ea1693e-90b5-11e6-9e29-715a3cea1e27.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19321417/3dc1a514-90b5-11e6-9c2b-d09e6f64403c.png
