### ISSUE TITLE
TETRIS®[inc]

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8660]
**App Name:** TETRIS®
**Bundle ID:** com.ea.tetris2011.inc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479943969">479943969</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tetris/id479943969?mt=8&uo=4">https://itunes.apple.com/us/app/tetris/id479943969?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** Electronic Arts Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple7/v4/30/9e/48/309e4840-ed07-9bf4-96d6-a53aaf22cac1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20276864/884d5dfa-aa9e-11e6-930c-5ff70ad26a72.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20276864/884d5dfa-aa9e-11e6-930c-5ff70ad26a72.png)
https://cloud.githubusercontent.com/assets/20930745/20276864/884d5dfa-aa9e-11e6-930c-5ff70ad26a72.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20276881/93d4389c-aa9e-11e6-8814-47898a0a1a22.png
