### ISSUE TITLE
PhotoScan - scanner by Google Photos

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#8662]
**App Name:** PhotoScan - scanner by Google Photos
**Bundle ID:** com.google.photosscanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1165525994">1165525994</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photoscan-scanner-by-google/id1165525994?mt=8&uo=4">https://itunes.apple.com/us/app/photoscan-scanner-by-google/id1165525994?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/ba/2e/a3/ba2ea3f1-b237-84bb-4f42-ddb57b129863/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20399226/77bcc8be-acf0-11e6-8c09-0f79e601e0ae.png)

**Comment by BBenC** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23527161/20398240/8b867d1a-ace4-11e6-8663-eb6cc57bbc74.png)
https://cloud.githubusercontent.com/assets/23527161/20398240/8b867d1a-ace4-11e6-8663-eb6cc57bbc74.png
Source:
https://cloud.githubusercontent.com/assets/23527161/20398266/aa8ecf96-ace4-11e6-883d-2f89bcb35ec2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20399226/77bcc8be-acf0-11e6-8c09-0f79e601e0ae.png)
https://cloud.githubusercontent.com/assets/20930745/20399226/77bcc8be-acf0-11e6-8c09-0f79e601e0ae.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20399254/8427ed9a-acf0-11e6-88b6-23df8c716ba8.png
