### ISSUE TITLE
BBC News

### ISSUE THREAD

**Issue by BBenC** [glasklart/hd#8664]
**App Name:** BBC News
**Bundle ID:** uk.co.bbc.newsuk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377382255">377382255</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/bbc-news/id377382255?mt=8&uo=4">https://itunes.apple.com/gb/app/bbc-news/id377382255?mt=8&uo=4</a>
**App Version:** 3.9.6
**Seller:** BBC Media Applications Technologies Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/bbc-media-applications-technologies/id377382258?uo=4">© BBC Media Applications Technologies Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/b7/89/d9/b789d918-0545-1360-af5e-048128337bf4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20453423/c00bb62c-ae24-11e6-9eda-5f9d6f3acd46.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20453423/c00bb62c-ae24-11e6-9eda-5f9d6f3acd46.png)
https://cloud.githubusercontent.com/assets/2068130/20453423/c00bb62c-ae24-11e6-9eda-5f9d6f3acd46.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20453425/cee4206c-ae24-11e6-95cf-9cdc14c5305b.png
