### ISSUE TITLE
Tab Pro

### ISSUE THREAD

**Issue by BBenC** [glasklart/hd#8665]
**App Name:** Tab Pro: learn, hear & play multitrack guitar tabs
**Bundle ID:** com.ultimateguitar.tabproipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=535076358">535076358</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tab-pro-learn-hear-play-multitrack/id535076358?mt=8&uo=4">https://itunes.apple.com/us/app/tab-pro-learn-hear-play-multitrack/id535076358?mt=8&uo=4</a>
**App Version:** 2.0.8
**Seller:** Ultimate Guitar
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ultimate-guitar/id337516725?uo=4">© Ultimate Guitar</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/b8/41/4e/b8414e7f-cea9-acd8-1c1d-ac59d919f1f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20453613/4b139da6-ae2b-11e6-8386-29c78f8ecb5a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20453613/4b139da6-ae2b-11e6-8386-29c78f8ecb5a.png)
https://cloud.githubusercontent.com/assets/20930745/20453613/4b139da6-ae2b-11e6-8386-29c78f8ecb5a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20453615/60c8bd34-ae2b-11e6-9c03-30db71e475a3.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20453618/6ff760f8-ae2b-11e6-8d2b-ab9718d88409.png)
https://cloud.githubusercontent.com/assets/20930745/20453618/6ff760f8-ae2b-11e6-8d2b-ab9718d88409.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20453619/7f2bc41a-ae2b-11e6-9684-ed205bb7dd27.png
