### ISSUE TITLE
Gumtree

### ISSUE THREAD

**Issue by BBenC** [glasklart/hd#8666]
**App Name:** Gumtree Classifieds: Buy and Sell items locally
**Bundle ID:** com.gumtreeuk2.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=487946174">487946174</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gumtree-classifieds-buy-sell/id487946174?mt=8&uo=4">https://itunes.apple.com/us/app/gumtree-classifieds-buy-sell/id487946174?mt=8&uo=4</a>
**App Version:** 5.4.0
**Seller:** Gumtree.com Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gumtree.com/id487946177?uo=4">© Gumtree.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple19/v4/ef/c5/86/efc5862f-7f0d-2a84-c15f-a0f5e0e871a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20453412/2bcf4c76-ae24-11e6-8f7e-7d0dd4aa7f26.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20453412/2bcf4c76-ae24-11e6-8f7e-7d0dd4aa7f26.png)
https://cloud.githubusercontent.com/assets/2068130/20453412/2bcf4c76-ae24-11e6-8f7e-7d0dd4aa7f26.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20453413/3a5a0ba0-ae24-11e6-9a90-97405736a678.png
