### ISSUE TITLE
MY ASICS Run Training

### ISSUE THREAD

**Issue by BBenC** [glasklart/hd#8667]
**App Name:** MY ASICS Run Training
**Bundle ID:** com.asics.myasics
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=466664337">466664337</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-asics-run-training/id466664337?mt=8&uo=4">https://itunes.apple.com/us/app/my-asics-run-training/id466664337?mt=8&uo=4</a>
**App Version:** 2.6.1
**Seller:** ASICS Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/asics-corporation/id466664340?uo=4">© ASICS Corporation</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/a1/cf/21/a1cf2179-756b-5101-d9fe-28dc43293b5f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20453676/ce2d32e6-ae2c-11e6-925c-05a43b62a144.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20453676/ce2d32e6-ae2c-11e6-925c-05a43b62a144.png)
https://cloud.githubusercontent.com/assets/20930745/20453676/ce2d32e6-ae2c-11e6-925c-05a43b62a144.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20453680/dd745996-ae2c-11e6-9e0e-998fa17a9cfc.png
