### ISSUE TITLE
Asana Rebel: Yoga and Fitness

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8668]
**App Name:** Asana Rebel: Yoga and Fitness
**Bundle ID:** com.asanayoga.asanarebel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1067860796">1067860796</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/asana-rebel-yoga-and-fitness/id1067860796?mt=8&uo=4">https://itunes.apple.com/us/app/asana-rebel-yoga-and-fitness/id1067860796?mt=8&uo=4</a>
**App Version:** 3.21.3
**Seller:** Asana Rebel GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/asana-rebel-gmbh/id1067860795?uo=4">© Asana Rebel GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/57/34/2a/57342a0a-c25b-dc80-7336-e30d6477b7aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455779-475074b6-3a7d-11e8-9aba-9cd55e60b47a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455071/c61d9e58-ae52-11e6-9625-c793d315f5e7.png)
https://cloud.githubusercontent.com/assets/20930745/20455071/c61d9e58-ae52-11e6-9625-c793d315f5e7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455073/d42c8856-ae52-11e6-8c9b-561038377c85.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455779-475074b6-3a7d-11e8-9aba-9cd55e60b47a.png)
https://user-images.githubusercontent.com/20930745/38455779-475074b6-3a7d-11e8-9aba-9cd55e60b47a.png

Source:
https://user-images.githubusercontent.com/20930745/38455804-58e86fe4-3a7d-11e8-8d89-701e25944cd6.png
