### ISSUE TITLE
Titan Brawl

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8669]
**App Name:** Titan Brawl
**Bundle ID:** com.omnidrone.lanes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1041951266">1041951266</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/titan-brawl/id1041951266?mt=8&uo=4">https://itunes.apple.com/us/app/titan-brawl/id1041951266?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Omnidrone SL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/omnidrone/id847363140?uo=4">© Omnidrone</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/9f/dc/e5/9fdce528-f3f0-0e6e-2038-2b6750839753/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455105/9ee945ac-ae53-11e6-8e0e-0c15b819439c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455105/9ee945ac-ae53-11e6-8e0e-0c15b819439c.png)
https://cloud.githubusercontent.com/assets/20930745/20455105/9ee945ac-ae53-11e6-8e0e-0c15b819439c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455106/b03ef068-ae53-11e6-8755-1191837542c3.png
