### ISSUE TITLE
First Aid: American Red Cross

### ISSUE THREAD

**Issue by rentiak** [glasklart/hd#867]
**App Name:** First Aid: American Red Cross
**Bundle ID:** com.americanredcross.firstaid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=529160691">529160691</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/first-aid-american-red-cross/id529160691?mt=8&uo=4">https://itunes.apple.com/us/app/first-aid-american-red-cross/id529160691?mt=8&uo=4</a>
**App Version:** 2.5.0
**Seller:** American Red Cross
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/american-red-cross/id529160694?uo=4">© American Red Cross</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/5d/b7/d6/5db7d62d-2cc7-aaa3-7a00-44ea7364d6ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38208541-b5c00954-36b1-11e8-9eb4-1dce904e254d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38208541-b5c00954-36b1-11e8-9eb4-1dce904e254d.png)
https://user-images.githubusercontent.com/2068130/38208541-b5c00954-36b1-11e8-9eb4-1dce904e254d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38208557-c40ee4b2-36b1-11e8-9bb6-76f33585f1d3.png
