### ISSUE TITLE
Tayasui Sketches: Draw and paint like on paper!

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8670]
**App Name:** Tayasui Sketches: Draw and paint like on paper!
**Bundle ID:** com.tayasui.sketches
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=641900855">641900855</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tayasui-sketches-draw-paint/id641900855?mt=8&uo=4">https://itunes.apple.com/us/app/tayasui-sketches-draw-paint/id641900855?mt=8&uo=4</a>
**App Version:** 13.1
**Seller:** yann le coroller
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tayasui.com/id359375853?uo=4">© Tayasui.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/ac/d1/65/acd165da-43c7-5981-aa3a-2489ecd8a9a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455136/968844ac-ae54-11e6-85bf-3d7af076055d.png)

**Comment by dreamnet** [comment]
Refers to #5524.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455136/968844ac-ae54-11e6-85bf-3d7af076055d.png)
https://cloud.githubusercontent.com/assets/20930745/20455136/968844ac-ae54-11e6-85bf-3d7af076055d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455140/a5626f02-ae54-11e6-83a0-926543b4da18.png
