### ISSUE TITLE
Artsy –– Collect and Bid on Fine Art & Design

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8671]
**App Name:** Artsy –– Collect and Bid on Fine Art & Design
**Bundle ID:** net.artsy.artsy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=703796080">703796080</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/artsy-collect-bid-on-fine/id703796080?mt=8&uo=4">https://itunes.apple.com/us/app/artsy-collect-bid-on-fine/id703796080?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Art.sy Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/art.sy-inc./id504862167?uo=4">© Art.sy Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/40/56/17/405617d5-b80d-8cc0-887d-29007aa5cb1d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455150/138ac722-ae55-11e6-8332-de6e29d8bd34.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455150/138ac722-ae55-11e6-8332-de6e29d8bd34.png)
https://cloud.githubusercontent.com/assets/20930745/20455150/138ac722-ae55-11e6-8332-de6e29d8bd34.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455151/21aadb12-ae55-11e6-9fd8-d38a1510a8fe.png
