### ISSUE TITLE
BeCasso Photo Editor

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8672]
**App Name:** BeCasso Photo Editor
**Bundle ID:** com.digitalmasterpieces.DigitalArtist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1125534178">1125534178</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/becasso-photo-editor/id1125534178?mt=8&uo=4">https://itunes.apple.com/us/app/becasso-photo-editor/id1125534178?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** DigitalMasterpieces GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/digitalmasterpieces-gmbh/id874345609?uo=4">© DigitalMasterpieces GmbH</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/0a/59/09/0a5909fd-f84f-a14d-f320-ea906f7a5f5c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626147-0ef44980-a918-11e8-9c6c-8f9af586d388.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455444/80d19f52-ae5c-11e6-99ea-3322081720db.png)
https://cloud.githubusercontent.com/assets/20930745/20455444/80d19f52-ae5c-11e6-99ea-3322081720db.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455451/90213c7e-ae5c-11e6-98ed-c15dea77c8a9.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626147-0ef44980-a918-11e8-9c6c-8f9af586d388.png)
https://user-images.githubusercontent.com/2068130/44626147-0ef44980-a918-11e8-9c6c-8f9af586d388.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44626154-1ddafc00-a918-11e8-8901-dd79d001c1f3.png
