### ISSUE TITLE
Velocireader - Speed Reading for Ebooks

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8673]
**App Name:** Velocireader - Speed Reading for Ebooks
**Bundle ID:** com.karanvasudeva.Velocireader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=635707909">635707909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/velocireader-speed-reading/id635707909?mt=8&uo=4">https://itunes.apple.com/us/app/velocireader-speed-reading/id635707909?mt=8&uo=4</a>
**App Version:** 1.4.4
**Seller:** Karan Vasudeva
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/noisy-typing/id560852076?uo=4">© Noisy Typing</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/19/12/09/19120994-b85b-1d63-8037-ec50c5a1221c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455175/c742a578-ae55-11e6-91b1-ae134213747d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455175/c742a578-ae55-11e6-91b1-ae134213747d.png)
https://cloud.githubusercontent.com/assets/20930745/20455175/c742a578-ae55-11e6-91b1-ae134213747d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455183/d43f8d90-ae55-11e6-9c34-49d4f3bf7bd3.png
