### ISSUE TITLE
Brainscape - Smart Flashcards

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8674]
**App Name:** Brainscape - Smart Flashcards
**Bundle ID:** com.brain-scape.sa.portal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=442415567">442415567</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/brainscape-smart-flashcards/id442415567?mt=8&uo=4">https://itunes.apple.com/us/app/brainscape-smart-flashcards/id442415567?mt=8&uo=4</a>
**App Version:** 3.20160930
**Seller:** Bold Learning Solutions, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/brainscape/id380833754?uo=4">© Brainscape</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/9b/97/e4/9b97e45e-3d62-0f67-8d23-2508e947a5ad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455210/b60a08a4-ae56-11e6-99eb-e0cc30c3b8de.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455210/b60a08a4-ae56-11e6-99eb-e0cc30c3b8de.png)
https://cloud.githubusercontent.com/assets/20930745/20455210/b60a08a4-ae56-11e6-99eb-e0cc30c3b8de.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455212/c5d5c7c8-ae56-11e6-88e6-bf15e1ec8cd1.png
