### ISSUE TITLE
Downwell

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8675]
**App Name:** Downwell
**Bundle ID:** com.devolver.downwell
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1032708262">1032708262</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/downwell/id1032708262?mt=8&uo=4">https://itunes.apple.com/us/app/downwell/id1032708262?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** GHI Media, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/devolver-digital/id457410262?uo=4">© Devolver Digital</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple19/v4/07/e8/94/07e89430-7851-9efd-f215-bdc5c9500a91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455225/355a9966-ae57-11e6-831b-778df8500dcc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455225/355a9966-ae57-11e6-831b-778df8500dcc.png)
https://cloud.githubusercontent.com/assets/20930745/20455225/355a9966-ae57-11e6-831b-778df8500dcc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455229/4533aa62-ae57-11e6-86a0-66ff28a2117c.png
