### ISSUE TITLE
Tomb of the Mask

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8676]
**App Name:** Tomb of the Mask
**Bundle ID:** com.happymagenta.fromcore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1057889290">1057889290</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tomb-of-the-mask/id1057889290?mt=8&uo=4">https://itunes.apple.com/us/app/tomb-of-the-mask/id1057889290?mt=8&uo=4</a>
**App Version:** 1.1.13
**Seller:** Happymagenta UAB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/happymagenta-uab/id1105393733?uo=4">© Happymagenta UAB</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/43/1a/a7/431aa73c-8fca-8193-badd-f68463eae952/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455243/c02e15f4-ae57-11e6-8d31-5a9ea03f102a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455243/c02e15f4-ae57-11e6-8d31-5a9ea03f102a.png)
https://cloud.githubusercontent.com/assets/20930745/20455243/c02e15f4-ae57-11e6-8d31-5a9ea03f102a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455247/cbffe8a8-ae57-11e6-8131-a086c053c61a.png
