### ISSUE TITLE
Inspire Free — Create Art, Paint, Draw, Sketch

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8677]
**App Name:** Inspire Free — Create Art, Paint, Draw, Sketch
**Bundle ID:** com.kiwipixel.inspirefree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465244091">465244091</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inspire-free-create-art-paint/id465244091?mt=8&uo=4">https://itunes.apple.com/us/app/inspire-free-create-art-paint/id465244091?mt=8&uo=4</a>
**App Version:** 4.2.4
**Seller:** snowCanoe
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/snowcanoe/id315556631?uo=4">© snowCanoe</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/5a/a8/e9/5aa8e91e-ba2d-8234-9040-90b745e2bc3f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455388/5c5d0b3a-ae5b-11e6-8187-1f4e327151fe.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455388/5c5d0b3a-ae5b-11e6-8187-1f4e327151fe.png)
https://cloud.githubusercontent.com/assets/20930745/20455388/5c5d0b3a-ae5b-11e6-8187-1f4e327151fe.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455391/676cb2d2-ae5b-11e6-8c6b-40b30750047c.png
