### ISSUE TITLE
Inspire — Create Art, Paint, Draw & Sketch

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8678]
**App Name:** Inspire — Create Art, Paint, Draw & Sketch
**Bundle ID:** com.kiwipixel.inspire
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=315556628">315556628</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/inspire-create-art-paint-draw/id315556628?mt=8&uo=4">https://itunes.apple.com/us/app/inspire-create-art-paint-draw/id315556628?mt=8&uo=4</a>
**App Version:** 4.2.4
**Seller:** snowCanoe
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/snowcanoe/id315556631?uo=4">© snowCanoe</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/ae/a0/4d/aea04d15-f560-abd4-bf04-e45cbd013234/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455388/5c5d0b3a-ae5b-11e6-8187-1f4e327151fe.png)

**Comment by dreamnet** [comment]
Same as #8677.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455388/5c5d0b3a-ae5b-11e6-8187-1f4e327151fe.png)
https://cloud.githubusercontent.com/assets/20930745/20455388/5c5d0b3a-ae5b-11e6-8187-1f4e327151fe.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455391/676cb2d2-ae5b-11e6-8c6b-40b30750047c.png
