### ISSUE TITLE
Swift Playgrounds

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8679]
**App Name:** Swift Playgrounds
**Bundle ID:** com.apple.Playgrounds
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=908519492">908519492</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swift-playgrounds/id908519492?mt=8&uo=4">https://itunes.apple.com/us/app/swift-playgrounds/id908519492?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** 
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/0d/f1/42/0df14273-ad39-7009-46c4-6af3658c63d7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455276/572fce5c-ae58-11e6-9917-efad3e5f0b86.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455276/572fce5c-ae58-11e6-9917-efad3e5f0b86.png)
https://cloud.githubusercontent.com/assets/20930745/20455276/572fce5c-ae58-11e6-9917-efad3e5f0b86.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455277/66a30d4a-ae58-11e6-8be0-3669c48ff4d0.png

**Comment by ivanov007** [comment]
this is iPad only app, and it just work with iOS 10.0+ so until next jailbreak comes out there's no point to add this to master

**Comment by dreamnet** [comment]
@ivanov007 Ah, interesting... I remove it from the master. THX!

**Comment by dreamnet** [comment]
I'm going to re-add this to the master.
