### ISSUE TITLE
Quazer - Die echte Alternative zum TV

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8680]
**App Name:** Quazer - Die echte Alternative zum TV
**Bundle ID:** com.quazer.appstore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1092624000">1092624000</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quazer-die-echte-alternative/id1092624000?mt=8&uo=4">https://itunes.apple.com/us/app/quazer-die-echte-alternative/id1092624000?mt=8&uo=4</a>
**App Version:** 1.85
**Seller:** Magic Internet Holding GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/magic-internet-gmbh/id1078885831?uo=4">© Magic Internet GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/96/82/28/9682280a-40fc-0063-6a17-39c02301853b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455312/5834ad30-ae59-11e6-8871-f2acec84f374.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455312/5834ad30-ae59-11e6-8871-f2acec84f374.png)
https://cloud.githubusercontent.com/assets/20930745/20455312/5834ad30-ae59-11e6-8871-f2acec84f374.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455324/7d5a3a1c-ae59-11e6-8832-8bc5a9f72245.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20455332/ad441324-ae59-11e6-9a4e-c5d816135a2d.png)
https://cloud.githubusercontent.com/assets/20930745/20455332/ad441324-ae59-11e6-9a4e-c5d816135a2d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20455338/bf7f9d06-ae59-11e6-835a-a2d5a53c31af.png
