### ISSUE TITLE
Brain Journey - Train your brain with fun games

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8681]
**App Name:** Brain Journey - Train your brain with fun games
**Bundle ID:** com.memorado.brainjourney
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1168546716">1168546716</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/brain-journey-train-your-brain/id1168546716?mt=8&uo=4">https://itunes.apple.com/us/app/brain-journey-train-your-brain/id1168546716?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Memorado GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/memorado/id897062512?uo=4">© Memorado</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/6a/1a/cc/6a1acc8d-fbfd-c656-8e99-2dca161e4818/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462434/467dd754-af1e-11e6-8c92-53bba9fd6390.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462434/467dd754-af1e-11e6-8c92-53bba9fd6390.png)
https://cloud.githubusercontent.com/assets/20930745/20462434/467dd754-af1e-11e6-8c92-53bba9fd6390.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462441/535a9ca0-af1e-11e6-8c80-c5d58d268d97.png
