### ISSUE TITLE
Today - Habit tracker for goals & routines

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8682]
**App Name:** Today - Habit tracker for goals & routines
**Bundle ID:** com.neybox.Today
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1055295863">1055295863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/today-habit-tracker-for-goals/id1055295863?mt=8&uo=4">https://itunes.apple.com/us/app/today-habit-tracker-for-goals/id1055295863?mt=8&uo=4</a>
**App Version:** 1.2.3
**Seller:** Neybox Digital Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/neybox-digital-ltd./id624507369?uo=4">© Neybox Digital Ltd.</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/5e/61/b7/5e61b7ed-5843-28cb-69be-3749f85a5932/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462468/d05df85a-af1e-11e6-8719-d162fa1d1eff.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462468/d05df85a-af1e-11e6-8719-d162fa1d1eff.png)
https://cloud.githubusercontent.com/assets/20930745/20462468/d05df85a-af1e-11e6-8719-d162fa1d1eff.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462473/dda527d6-af1e-11e6-9a7c-a22ae3144907.png
