### ISSUE TITLE
ZenDots 2 - One Dot’s Journey

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8683]
**App Name:** ZenDots 2 - One Dot’s Journey
**Bundle ID:** com.LittleWhiteBearStudios.ZenDots2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1161836152">1161836152</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zendots-2-one-dots-journey/id1161836152?mt=8&uo=4">https://itunes.apple.com/us/app/zendots-2-one-dots-journey/id1161836152?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Little White Bear Studios, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/little-white-bear-studios-llc/id286331903?uo=4">© Little White Bear Studios, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/14/f3/e3/14f3e3ac-ab57-c9c9-e212-7167d83e5222/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462486/51b6a208-af1f-11e6-90e5-83fe7a71be3f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462486/51b6a208-af1f-11e6-90e5-83fe7a71be3f.png)
https://cloud.githubusercontent.com/assets/20930745/20462486/51b6a208-af1f-11e6-90e5-83fe7a71be3f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462489/5b532908-af1f-11e6-99a8-ae410613d197.png
