### ISSUE TITLE
Beams.

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8684]
**App Name:** Beams.
**Bundle ID:** com.appsolutegames.pulsars
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1161267000">1161267000</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beams./id1161267000?mt=8&uo=4">https://itunes.apple.com/us/app/beams./id1161267000?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Appsolute Games LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/appsolute-games-llc/id602062365?uo=4">© Appsolute Games LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/1b/b6/90/1bb690df-e6ab-b18a-c120-b0ffc1c42cff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462547/0e2a1220-af21-11e6-8422-569f349fb2b7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462521/512db906-af20-11e6-8ffa-9ffc47bd371c.png)
https://cloud.githubusercontent.com/assets/20930745/20462521/512db906-af20-11e6-8ffa-9ffc47bd371c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462524/5b31f354-af20-11e6-8646-c15cf57e2a89.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462547/0e2a1220-af21-11e6-8422-569f349fb2b7.png)
https://cloud.githubusercontent.com/assets/20930745/20462547/0e2a1220-af21-11e6-8422-569f349fb2b7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462551/22f0e274-af21-11e6-9360-ad83fea80575.png
