### ISSUE TITLE
Asymmetric

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8685]
**App Name:** Asymmetric
**Bundle ID:** at.klemensstrasser.Asymmetric
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1020657631">1020657631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/asymmetric/id1020657631?mt=8&uo=4">https://itunes.apple.com/us/app/asymmetric/id1020657631?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Klemens Strasser
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/klemens-strasser/id889417671?uo=4">© Klemens Strasser</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple19/v4/2e/1d/53/2e1d5325-529e-5a91-e4c4-a933b6bb33ed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20464695/6a13c916-af4c-11e6-9f0e-d0b6b9c52330.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20464695/6a13c916-af4c-11e6-9f0e-d0b6b9c52330.png)
https://cloud.githubusercontent.com/assets/20930745/20464695/6a13c916-af4c-11e6-9f0e-d0b6b9c52330.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20464698/7c5f1454-af4c-11e6-906f-78ca806635be.png
