### ISSUE TITLE
Join The Dots

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8686]
**App Name:** Join The Dots
**Bundle ID:** com.ezone.dots
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1154862635">1154862635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/join-the-dots/id1154862635?mt=8&uo=4">https://itunes.apple.com/us/app/join-the-dots/id1154862635?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Ezone.com
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ezone.com/id283905453?uo=4">© Ezone.com</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/e6/de/b4/e6deb425-6042-8aa3-ec0c-f966f94004b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462580/ec1d1550-af21-11e6-879f-a59362c809d0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462580/ec1d1550-af21-11e6-879f-a59362c809d0.png)
https://cloud.githubusercontent.com/assets/20930745/20462580/ec1d1550-af21-11e6-879f-a59362c809d0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462584/fce23aaa-af21-11e6-8c5c-ef14087b6493.png
