### ISSUE TITLE
Record Bird – Never Miss a Music Release

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8687]
**App Name:** Record Bird – Never Miss a Music Release
**Bundle ID:** com.recordbird.recordbird
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1116690598">1116690598</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/record-bird-never-miss-music/id1116690598?mt=8&uo=4">https://itunes.apple.com/us/app/record-bird-never-miss-music/id1116690598?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Record Bird GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/record-bird-gmbh/id1116690597?uo=4">© Record Bird GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/76/e6/78/76e6787b-16ae-31ba-b80c-246097111f74/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20464504/b0df3cd0-af48-11e6-9eec-431473b04151.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462610/9a0bfafa-af22-11e6-8206-06486bfb1a35.png)
https://cloud.githubusercontent.com/assets/20930745/20462610/9a0bfafa-af22-11e6-8206-06486bfb1a35.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462615/ab3a650a-af22-11e6-8d2c-cc2df47f013e.png

**Comment by dreamnet** [comment]
Uh, ah , no - the other way round. 😉 
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20464504/b0df3cd0-af48-11e6-9eec-431473b04151.png)
https://cloud.githubusercontent.com/assets/2068130/20464504/b0df3cd0-af48-11e6-9eec-431473b04151.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20464508/c06d6e6a-af48-11e6-9eec-046971616c8c.png
