### ISSUE TITLE
Blinkist - Nonfiction Book Notes in Audio & Text

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8688]
**App Name:** Blinkist - Nonfiction Book Notes in Audio & Text
**Bundle ID:** com.blinkslabs.Blinkist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=568839295">568839295</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/blinkist-nonfiction-book-notes/id568839295?mt=8&uo=4">https://itunes.apple.com/us/app/blinkist-nonfiction-book-notes/id568839295?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** Blinks Labs GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/blinks-labs/id568839298?uo=4">© Blinks Labs</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/ff/d1/30/ffd130a9-3150-c58a-3261-531cbf515c82/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462663/ff56fb8e-af23-11e6-8cd4-62aed5d88bf1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462663/ff56fb8e-af23-11e6-8cd4-62aed5d88bf1.png)
https://cloud.githubusercontent.com/assets/20930745/20462663/ff56fb8e-af23-11e6-8cd4-62aed5d88bf1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462670/12ecc9e4-af24-11e6-9f03-c933c3689625.png
