### ISSUE TITLE
Invoice by Alto - Pro Invoicing & Estimates

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8689]
**App Name:** Invoice by Alto - Pro Invoicing & Estimates
**Bundle ID:** com.lifelikeux.altoinvoicing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1077525643">1077525643</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/invoice-by-alto-pro-invoicing/id1077525643?mt=8&uo=4">https://itunes.apple.com/us/app/invoice-by-alto-pro-invoicing/id1077525643?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Lifelike UX Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lifelike-ux-limited/id799642938?uo=4">© Lifelike UX Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/56/ab/ce/56abceb0-263b-e1c2-6a3c-baeb841cf3e3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20464237/889b3cdc-af44-11e6-95e8-ee946fd94b69.png)

**Comment by 2Qt2beStr8** [comment]
???

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462895/257c02c4-af28-11e6-97b1-d3f0867567c2.png)
https://cloud.githubusercontent.com/assets/20930745/20462895/257c02c4-af28-11e6-97b1-d3f0867567c2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462897/34a1cc20-af28-11e6-8237-c3338770f519.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20464237/889b3cdc-af44-11e6-95e8-ee946fd94b69.png)
https://cloud.githubusercontent.com/assets/2068130/20464237/889b3cdc-af44-11e6-95e8-ee946fd94b69.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20464241/9731308a-af44-11e6-8543-48204044f9fd.png
