### ISSUE TITLE
Into the Dead

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#869]
**App Name:** Into the Dead
**Bundle ID:** com.sidheinteractive.sif.DR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=535609266">535609266</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/into-the-dead/id535609266?mt=8&uo=4">https://itunes.apple.com/us/app/into-the-dead/id535609266?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Prodigy Design Limited T/A Sidhe Interactive
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pikpok/id323296229?uo=4>© PikPok</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple20/v4/6c/7a/5e/6c7a5e9b-62e2-62f5-95de-df902958a0b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18914100/e8a9a0d8-858b-11e6-8381-f009b0c13729.png)

**Comment by Anuskuss** [comment]
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18914100/e8a9a0d8-858b-11e6-8381-f009b0c13729.png)
https://cloud.githubusercontent.com/assets/20930745/18914100/e8a9a0d8-858b-11e6-8381-f009b0c13729.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18914115/01a44412-858c-11e6-9c35-cb45a0b015ce.png
