### ISSUE TITLE
TalentHero - Ausbildung finden leicht gemacht!

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8691]
**App Name:** TalentHero - Ausbildung finden leicht gemacht!
**Bundle ID:** de.meinestadt.talenthero
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1122620439">1122620439</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/talenthero-ausbildung-finden/id1122620439?mt=8&uo=4">https://itunes.apple.com/us/app/talenthero-ausbildung-finden/id1122620439?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** meinestadt.de GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/meinestadt.de-gmbh/id304666356?uo=4">© meinestadt.de GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/27/b1/51/27b15105-6b4c-3c54-6561-6c6066309c78/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462761/9e3fdc10-af25-11e6-9904-1bd6c32d5e58.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462761/9e3fdc10-af25-11e6-9904-1bd6c32d5e58.png)
https://cloud.githubusercontent.com/assets/20930745/20462761/9e3fdc10-af25-11e6-9904-1bd6c32d5e58.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462765/adbfa38c-af25-11e6-878f-2b560cb19f93.png
