### ISSUE TITLE
Productive habits & daily goals tracker

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8692]
**App Name:** Productive habits & daily goals tracker
**Bundle ID:** com.beHappy.Productive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=983826477">983826477</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/productive-habits-daily-goals/id983826477?mt=8&uo=4">https://itunes.apple.com/us/app/productive-habits-daily-goals/id983826477?mt=8&uo=4</a>
**App Version:** 1.3.4
**Seller:** Jaidev Soin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jaidev-soin/id590615830?uo=4">© Jaidev Soin</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/41/e9/38/41e938b0-b2b7-eb76-31c5-27354e347c1e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462801/6687a658-af26-11e6-861d-fcb8baedbe79.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20462801/6687a658-af26-11e6-861d-fcb8baedbe79.png)
https://cloud.githubusercontent.com/assets/20930745/20462801/6687a658-af26-11e6-861d-fcb8baedbe79.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20462803/709ffee2-af26-11e6-9b3f-329ce0e12321.png
