### ISSUE TITLE
One More Bounce

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#8693]
**App Name:** One More Bounce
**Bundle ID:** com.smgstudio.onemorebounce
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=963037888">963037888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/one-more-bounce/id963037888?mt=8&uo=4">https://itunes.apple.com/us/app/one-more-bounce/id963037888?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** SMG STUDIO PTY LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/smg-studio/id832131501?uo=4">© SMG Studio</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/a7/4f/22/a74f22c0-83a8-bc99-c76f-2b7547537f9b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20464381/b38c2094-af46-11e6-8434-25c2e6fa83a7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20464122/1f6da9ea-af42-11e6-8fbb-e3396497b31b.png)
https://cloud.githubusercontent.com/assets/20930745/20464122/1f6da9ea-af42-11e6-8fbb-e3396497b31b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20464124/2a393d1c-af42-11e6-89d6-782c3f59ccff.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Mhmm... I don't think we need the border on this.

**Comment by 2Qt2beStr8** [comment]
@dreamnet ... ok, i fix it

**Comment by dreamnet** [comment]
Already done. 😃 
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20464381/b38c2094-af46-11e6-8434-25c2e6fa83a7.png)
https://cloud.githubusercontent.com/assets/2068130/20464381/b38c2094-af46-11e6-8434-25c2e6fa83a7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20464384/c1cb7056-af46-11e6-8870-578d26c382b9.png
