### ISSUE TITLE
Fantasy Sports Player Tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8694]
**App Name:** Fantasy Sports Player Tracker
**Bundle ID:** com.ownersbox.fspt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1114830183">1114830183</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fantasy-sports-player-tracker/id1114830183?mt=8&uo=4">https://itunes.apple.com/us/app/fantasy-sports-player-tracker/id1114830183?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** OwnersBox 2.0 Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ownersbox/id935411566?uo=4">© Ownersbox</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/ec/36/6d/ec366da3-cf58-8402-13f0-a3b05a9d6a9a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20465126/ae880df0-af56-11e6-943e-15e0e2365536.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20465126/ae880df0-af56-11e6-943e-15e0e2365536.png)
https://cloud.githubusercontent.com/assets/2068130/20465126/ae880df0-af56-11e6-943e-15e0e2365536.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20465132/bcaa37d2-af56-11e6-8cb4-c23ee5749d9b.png
