### ISSUE TITLE
Bebot - Robot Synth

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8697]
**App Name:** Bebot - Robot Synth
**Bundle ID:** com.normalware.Bebot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300309944">300309944</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bebot-robot-synth/id300309944?mt=8&uo=4">https://itunes.apple.com/us/app/bebot-robot-synth/id300309944?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Russell Black
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/normalware/id300309947?uo=4">© Normalware</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/32/8d/e4/328de4b7-56d8-ef38-b5db-018f006c08c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20616418/8a27c13c-b2e2-11e6-9677-e1190a83fa55.png)

**Comment by 2Qt2beStr8** [comment]
???

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20466136/89a2dce2-af6d-11e6-9f9b-9b1bde9b20e6.png)
https://cloud.githubusercontent.com/assets/20930745/20466136/89a2dce2-af6d-11e6-9f9b-9b1bde9b20e6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20466139/977d360a-af6d-11e6-834e-4de83c400acf.png

**Comment by dreamnet** [comment]
More simple... ?
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20616418/8a27c13c-b2e2-11e6-9677-e1190a83fa55.png)
https://cloud.githubusercontent.com/assets/2068130/20616418/8a27c13c-b2e2-11e6-9677-e1190a83fa55.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20616430/9bed0d32-b2e2-11e6-8ea1-213a9d6a9522.png
