### ISSUE TITLE
FocusList: daily planner & focus timer based on timeboxing and pomodoro technique

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8698]
**App Name:** FocusList: daily planner & focus timer based on timeboxing and pomodoro technique
**Bundle ID:** rinik.FocusList
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1083376166">1083376166</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/focuslist-daily-planner-focus/id1083376166?mt=8&uo=4">https://itunes.apple.com/us/app/focuslist-daily-planner-focus/id1083376166?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Vojtech Rinik
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vojto-rinik/id415832065?uo=4">© Vojto Rinik</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/1b/23/9d/1b239d47-b61a-d7f6-a2ce-458b8265d8fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20492943/1e79e6ae-b017-11e6-944e-5f50c473ff82.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20492943/1e79e6ae-b017-11e6-944e-5f50c473ff82.png)
https://cloud.githubusercontent.com/assets/20930745/20492943/1e79e6ae-b017-11e6-944e-5f50c473ff82.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20492976/41b16930-b017-11e6-8fb9-8e759b3019da.png
