### ISSUE TITLE
Attenborough Story of Life

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8699]
**App Name:** Attenborough Story of Life
**Bundle ID:** com.bbc.attenboroughstoryoflife
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1124476992">1124476992</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/attenborough-story-of-life/id1124476992?mt=8&uo=4">https://itunes.apple.com/us/app/attenborough-story-of-life/id1124476992?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** BBC Worldwide LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bbc-worldwide/id344138454?uo=4">© BBC Worldwide</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/4d/2e/c1/4d2ec1c3-d34b-fbab-c311-3c201abe040d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20491957/50cb4fe8-b013-11e6-9fc0-81c092f18f02.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20491957/50cb4fe8-b013-11e6-9fc0-81c092f18f02.png)
https://cloud.githubusercontent.com/assets/20930745/20491957/50cb4fe8-b013-11e6-9fc0-81c092f18f02.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20491975/60442b66-b013-11e6-963a-383740420593.png
