### ISSUE TITLE
Instant Heart Rate+: Heart Rate & Pulse Monitor

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#870]
**App Name:** Instant Heart Rate+: Heart Rate & Pulse Monitor
**Bundle ID:** si.modula.instantheartrate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=395042892">395042892</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instant-heart-rate+-heart/id395042892?mt=8&uo=4">https://itunes.apple.com/us/app/instant-heart-rate+-heart/id395042892?mt=8&uo=4</a>
**App Version:** 5.36
**Seller:** AZUMIO, inovacije v elektroniki in informacijskih tehnologijah d.o.o.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/azumio-inc./id439290207?mt=8&uo=4>© Azumio Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple18/v4/6f/ac/50/6fac5015-6db2-cf63-580a-39afb85e8e1e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18934704/902af254-85db-11e6-9943-2e19d5ef5779.png)

**Comment by JamieKnuth** [comment]
Hello, I missed that Icon in Glaskart 5.1. How can I change it?

**Comment by 2Qt2beStr8** [comment]
@JamieKnuth  .... look here https://github.com/glasklart/hd/issues/3247
the icon exists for the free version from this app ... so you can use this icon

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18934704/902af254-85db-11e6-9943-2e19d5ef5779.png)
https://cloud.githubusercontent.com/assets/20930745/18934704/902af254-85db-11e6-9943-2e19d5ef5779.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18934720/a11eaa38-85db-11e6-840b-acfb8d02191d.png)

**Comment by JamieKnuth** [comment]
Thanks, but (I forget :-/) how (what) must I do to change that? @

**Comment by 2Qt2beStr8** [comment]
if the "Bundl ID" haven't changed ... you have to download this icon and rename it to "si.modula.instantheartrate-large.png"
Copy this file to this folder from your iPhone: -> Library/Themes/Glasklart Icons.theme/Icon Bundles/

than make a respring and the icon have changed

**Comment by JamieKnuth** [comment]
@2Qt2beStr8  thank you so much *kisses*

**Comment by 2Qt2beStr8** [comment]
@JamieKnuth  .... you are welcome :-)
