### ISSUE TITLE
Selfie Editor: face tune, beauty cam photo makeup

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8701]
**App Name:** Selfie Editor: face tune, beauty cam photo makeup
**Bundle ID:** com.tapstar.best.selfie.editor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1056521360">1056521360</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/selfie-editor-face-tune-beauty/id1056521360?mt=8&uo=4">https://itunes.apple.com/us/app/selfie-editor-face-tune-beauty/id1056521360?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** AKM Masuduzzaman
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/akm-masuduzzaman/id392879324?uo=4">© AKM Masuduzzaman</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/b2/25/9f/b2259f58-7697-7f32-15eb-92d52e01f755/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20596993/88beb810-b241-11e6-8ccb-eef24d41c3b1.png)

**Comment by BBenC** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23527161/20531123/a88bbd3e-b0cd-11e6-91d3-4e14e47569dd.png)
Source:
https://cloud.githubusercontent.com/assets/23527161/20531120/a432dc9a-b0cd-11e6-843c-3dc1fbc48198.png

Source is awful, an attempt though lol :)

**Comment by dreamnet** [comment]
@BBenC Not a bad try... 👍 
Here is one with a cleaner and correct sized source:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20596993/88beb810-b241-11e6-8ccb-eef24d41c3b1.png)
https://cloud.githubusercontent.com/assets/2068130/20596993/88beb810-b241-11e6-8ccb-eef24d41c3b1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20597008/983a3c24-b241-11e6-9894-7e83d5ae0b69.png)
