### ISSUE TITLE
Add Music to Music Video Maker

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8702]
**App Name:** Add Music to Music Video Maker
**Bundle ID:** com.tapstar.add.background.music.on.video
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1072337393">1072337393</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/add-music-to-music-video-maker/id1072337393?mt=8&uo=4">https://itunes.apple.com/us/app/add-music-to-music-video-maker/id1072337393?mt=8&uo=4</a>
**App Version:** 1.8.1
**Seller:** TapStar Interactive Software Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tapstar-interactive-software-limited/id392879324?uo=4">© TapStar Interactive Software Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/64/0f/91/640f917e-afe4-0ce4-ef21-cdc28bb1f7b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38463942-32a3a334-3b05-11e8-9954-cc33a77cc77a.png)

**Comment by BBenC** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23527161/20529274/8c4bb6ca-b0c7-11e6-815e-e23172e3681b.png)
Source:
https://cloud.githubusercontent.com/assets/23527161/20529303/a0f9998e-b0c7-11e6-8fb8-32ecb5ad6ea2.png

**Comment by dreamnet** [comment]
?
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20616323/a9b48806-b2e1-11e6-982c-6f84656b71b1.png)
https://cloud.githubusercontent.com/assets/2068130/20616323/a9b48806-b2e1-11e6-982c-6f84656b71b1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20616332/b9f37fba-b2e1-11e6-9b9e-dc5e8f5133bc.png

**Comment by dreamnet** [comment]
Icon needs an update.
