### ISSUE TITLE
Spines now

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#8703]
**App Name:** Spines now
**Bundle ID:** me.spines.mobile.now
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1001928546">1001928546</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spines-now/id1001928546?mt=8&uo=4">https://itunes.apple.com/us/app/spines-now/id1001928546?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** LIHUEN HUB SOCIEDAD LIMITADA.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lihuen-hub-s.l./id1001928545?uo=4">© Lihuen Hub S.L.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/8e/f9/36/8ef93697-82f6-0f65-23a7-69b84af7a68b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20577214/a4ed9950-b1c1-11e6-90a2-a904a0e0a12a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20577214/a4ed9950-b1c1-11e6-90a2-a904a0e0a12a.png)
https://cloud.githubusercontent.com/assets/20930745/20577214/a4ed9950-b1c1-11e6-90a2-a904a0e0a12a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20577233/bdd346f4-b1c1-11e6-852a-e376080951ee.png
