### ISSUE TITLE
360 Flight

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8704]
**App Name:** 360 Flight
**Bundle ID:** com.360.360Flight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1107233534">1107233534</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/360-flight/id1107233534?mt=8&uo=4">https://itunes.apple.com/us/app/360-flight/id1107233534?mt=8&uo=4</a>
**App Version:** 6.1.0
**Seller:** LE WEI TECHNOLOGY (HK) LIMITED
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/le-wei-technology-hk-limited/id492007961?uo=4">© Le Wei Technology(HK) Limited</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/91/bc/79/91bc79cc-1899-035d-e881-32a71eb0f011/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20637881/7b9f37fe-b395-11e6-8479-2e8e698124cd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/20637881/7b9f37fe-b395-11e6-8479-2e8e698124cd.png)
https://cloud.githubusercontent.com/assets/2068130/20637881/7b9f37fe-b395-11e6-8479-2e8e698124cd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/20637883/8ae962de-b395-11e6-97a7-79e0987757c5.png
