### ISSUE TITLE
DEAD TRIGGER

### ISSUE THREAD

**Issue by silvermajra** [glasklart/hd#871]
**App Name:** DEAD TRIGGER
**Bundle ID:** com.madfingergames.deadtrigger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=533079551">533079551</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dead-trigger/id533079551?mt=8&uo=4">https://itunes.apple.com/us/app/dead-trigger/id533079551?mt=8&uo=4</a>
**App Version:** 1.9.0
**Seller:** MADFINGER Games, a.s.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/madfinger-games-a.s./id313220894?uo=4>© MADFINGER Games, a.s.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple1/v4/ba/6f/49/ba6f492a-b025-314e-030e-f899408437b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409870/33db2892-92de-11e6-9879-aa30394f94e2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409870/33db2892-92de-11e6-9879-aa30394f94e2.png)
https://cloud.githubusercontent.com/assets/20930745/19409870/33db2892-92de-11e6-9879-aa30394f94e2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409876/431e7480-92de-11e6-8fb4-438493300a2e.png
