### ISSUE TITLE
ingogo - Fixed Fares for Taxis

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8713]
**App Name:** ingogo - Fixed Fares for Taxis
**Bundle ID:** mobi.ingogo.passenger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=463995190">463995190</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/ingogo-fixed-fares-for-taxis/id463995190?mt=8&uo=4">https://itunes.apple.com/au/app/ingogo-fixed-fares-for-taxis/id463995190?mt=8&uo=4</a>
**App Version:** 4.3.9
**Seller:** Ingogo Pty Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/au/developer/ingogo/id463995193?uo=4">© ingogo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/a2/3c/d4/a23cd459-12d1-02cd-2a22-a91f43c57b67/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20724050/165cdfa6-b66d-11e6-9eba-21bb269f6f10.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20724050/165cdfa6-b66d-11e6-9eba-21bb269f6f10.png)
https://cloud.githubusercontent.com/assets/20930745/20724050/165cdfa6-b66d-11e6-9eba-21bb269f6f10.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20724064/27a3cdce-b66d-11e6-95bb-23419eecc4f3.png
