### ISSUE TITLE
Boost Mobile

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8714]
**App Name:** Boost Mobile
**Bundle ID:** au.com.boost.BoostApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=999702795">999702795</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boost-mobile/id999702795?mt=8&uo=4">https://itunes.apple.com/us/app/boost-mobile/id999702795?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Boost Tel Pty Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/boost-tel-pty-limited/id999702794?uo=4">© Boost Tel Pty Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple6/v4/4d/8f/a6/4d8fa6ad-e99d-73d3-d19c-076799ba8fe8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20724221/ad055b5e-b66d-11e6-90c6-cbf7fe031c08.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20724221/ad055b5e-b66d-11e6-90c6-cbf7fe031c08.png)
https://cloud.githubusercontent.com/assets/20930745/20724221/ad055b5e-b66d-11e6-90c6-cbf7fe031c08.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20724236/bd642afc-b66d-11e6-8e5f-794fc0990e68.png
