### ISSUE TITLE
Couchsurfing Travel App

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8715]
**App Name:** Couchsurfing Travel App
**Bundle ID:** com.couchsurfing.CouchSurfing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525642917">525642917</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/couchsurfing-travel-app/id525642917?mt=8&uo=4">https://itunes.apple.com/us/app/couchsurfing-travel-app/id525642917?mt=8&uo=4</a>
**App Version:** 5.6
**Seller:** CouchSurfing International Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/couchsurfing-international/id525642921?uo=4">© CouchSurfing International Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/c4/c3/16/c4c316f6-e82c-8eeb-c563-0a372a44e59d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20724524/e3d5a890-b66e-11e6-879e-badbec4c8a71.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20724524/e3d5a890-b66e-11e6-879e-badbec4c8a71.png)
https://cloud.githubusercontent.com/assets/20930745/20724524/e3d5a890-b66e-11e6-879e-badbec4c8a71.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20724541/fa03bd82-b66e-11e6-9e18-a4442dd53211.png
