### ISSUE TITLE
Ribs & Burgers

### ISSUE THREAD

**Issue by quantum8** [glasklart/hd#8716]
**App Name:** Ribs & Burgers
**Bundle ID:** com.mobi2go.Ribs---Burgers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1008612491">1008612491</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ribs-burgers/id1008612491?mt=8&uo=4">https://itunes.apple.com/us/app/ribs-burgers/id1008612491?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Mobi2Go Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mobi2go/id661514525?uo=4">© Mobi2Go</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/5e/47/5f/5e475f59-f938-2dab-1fe8-04d6302c13b2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20724765/ca127ef0-b66f-11e6-8083-13da665463b0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20724765/ca127ef0-b66f-11e6-8083-13da665463b0.png)
https://cloud.githubusercontent.com/assets/20930745/20724765/ca127ef0-b66f-11e6-8083-13da665463b0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20724779/d85165e4-b66f-11e6-8a4a-d0e2fb438bec.png
