### ISSUE TITLE
Nexar - AI Dashcam

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8717]
**App Name:** Nexar - AI Dashcam
**Bundle ID:** mobi.nexar.Nexar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=996931497">996931497</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nexar-ai-dashcam/id996931497?mt=8&uo=4">https://itunes.apple.com/us/app/nexar-ai-dashcam/id996931497?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Nexar Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nexar-inc./id996931496?uo=4">© Nexar Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/53/88/41/5388410f-df75-134e-fc8f-3685f3cd3ed0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20725090/0c529bb4-b671-11e6-8c68-ca5eedbd6c02.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20725090/0c529bb4-b671-11e6-8c68-ca5eedbd6c02.png)
https://cloud.githubusercontent.com/assets/20930745/20725090/0c529bb4-b671-11e6-8c68-ca5eedbd6c02.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20725103/18bfc9a8-b671-11e6-8b25-3da20c4643b2.png
