### ISSUE TITLE
Warhammer 40,000: Deathwatch - Tyranid Invasion

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8719]
**App Name:** Warhammer 40,000: Deathwatch - Tyranid Invasion
**Bundle ID:** uk.co.rodeogames.deathwatch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=791134629">791134629</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/warhammer-40-000-deathwatch/id791134629?mt=8&uo=4">https://itunes.apple.com/us/app/warhammer-40-000-deathwatch/id791134629?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Rodeo Games
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rodeo-games/id415278463?uo=4">© Rodeo Games</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple2/v4/d6/71/cf/d671cf65-b2ed-51da-7449-e380c1f31c89/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21044859/36ca01ae-bdfe-11e6-8240-7a2e2a3fdb1e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21044859/36ca01ae-bdfe-11e6-8240-7a2e2a3fdb1e.png)
https://cloud.githubusercontent.com/assets/2068130/21044859/36ca01ae-bdfe-11e6-8240-7a2e2a3fdb1e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21044872/4472a518-bdfe-11e6-98b3-2ed4108557f6.png

**Comment by ivanov007** [comment]
@dreamnet wow looks great 👍
