### ISSUE TITLE
Kinetic Damage

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8720]
**App Name:** Kinetic Damage
**Bundle ID:** com.n0mad.KineticDamage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=653222766">653222766</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kinetic-damage/id653222766?mt=8&uo=4">https://itunes.apple.com/us/app/kinetic-damage/id653222766?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Benjamin Marchand
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/benjamin-marchand/id335590595?uo=4">© Benjamin Marchand</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple2/v4/9f/19/78/9f1978ea-22f9-19a5-e0b7-37845c4c3cc3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23135755/18ab0fc6-f79a-11e6-8ba2-aebeb7f592ca.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23135755/18ab0fc6-f79a-11e6-8ba2-aebeb7f592ca.png)
https://cloud.githubusercontent.com/assets/2068130/23135755/18ab0fc6-f79a-11e6-8ba2-aebeb7f592ca.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23135766/27bc7f22-f79a-11e6-82cc-6df9eaad2aab.png
❓
