### ISSUE TITLE
Lost Souls: Timeless Fables

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8721]
**App Name:** Lost Souls: Timeless Fables
**Bundle ID:** com.g5e.lostsouls2.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1021995859">1021995859</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lost-souls-timeless-fables/id1021995859?mt=8&uo=4">https://itunes.apple.com/us/app/lost-souls-timeless-fables/id1021995859?mt=8&uo=4</a>
**App Version:** 1.0.8
**Seller:** G5 Entertainment AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/g5-entertainment/id305426797?uo=4">© G5 Entertainment</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/d9/13/91/d91391e1-6f9f-4a21-4e91-d41f882ed292/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563303/406c0480-ce81-11e6-8730-7d7cd67ec45f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563303/406c0480-ce81-11e6-8730-7d7cd67ec45f.png)
https://cloud.githubusercontent.com/assets/2068130/21563303/406c0480-ce81-11e6-8730-7d7cd67ec45f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21563308/504d1a2e-ce81-11e6-869e-6130fa54e38a.png
