### ISSUE TITLE
Dark Arcana: The Carnival

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8722]
**App Name:** Dark Arcana: The Carnival
**Bundle ID:** com.g5e.carnival.free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561405613">561405613</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dark-arcana-the-carnival/id561405613?mt=8&uo=4">https://itunes.apple.com/us/app/dark-arcana-the-carnival/id561405613?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** G5 Entertainment AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/g5-entertainment/id305426797?uo=4">© G5 Entertainment</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/2c/62/b6/2c62b6d7-2179-23f8-a315-296af05e4377/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563461/ff670d02-ce82-11e6-88e7-3a8a95b7e669.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563461/ff670d02-ce82-11e6-88e7-3a8a95b7e669.png)
https://cloud.githubusercontent.com/assets/2068130/21563461/ff670d02-ce82-11e6-88e7-3a8a95b7e669.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21563467/0ed8b8e4-ce83-11e6-9835-d46996650d1b.png
