### ISSUE TITLE
Dark Arcana: The Carnival HD (Full)

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8723]
**App Name:** Dark Arcana: The Carnival HD (Full)
**Bundle ID:** com.g5e.carnival.hd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561405659">561405659</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dark-arcana-carnival-hd-full/id561405659?mt=8&uo=4">https://itunes.apple.com/us/app/dark-arcana-carnival-hd-full/id561405659?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** G5 Entertainment AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/g5-entertainment/id305426797?uo=4">© G5 Entertainment</a>
**Supported Devices:** iPadWifi, iPad3G, iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/b5/2d/6c/b52d6cf2-5ecc-404c-aec9-d604eef9dcf6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563461/ff670d02-ce82-11e6-88e7-3a8a95b7e669.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563461/ff670d02-ce82-11e6-88e7-3a8a95b7e669.png)
https://cloud.githubusercontent.com/assets/2068130/21563461/ff670d02-ce82-11e6-88e7-3a8a95b7e669.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21563467/0ed8b8e4-ce83-11e6-9835-d46996650d1b.png
