### ISSUE TITLE
Currency Today - Global Currency Convertor Widget

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8725]
**App Name:** Currency Today - Global Currency Convertor Widget
**Bundle ID:** uk.co.bewhere.currency.today
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=920780997">920780997</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/currency-today-global-currency/id920780997?mt=8&uo=4">https://itunes.apple.com/us/app/currency-today-global-currency/id920780997?mt=8&uo=4</a>
**App Version:** 2.01
**Seller:** Portable Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/portable-ltd/id377800228?uo=4">© Portable Ltd</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/c4/bb/99/c4bb99f2-8282-7001-abec-e610e9de0876/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21040794/5ee69d26-bde7-11e6-94c0-37ad729eb46c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20866723/e8eec5d2-ba33-11e6-846e-850e8dd3a2ab.png)
https://cloud.githubusercontent.com/assets/20930745/20866723/e8eec5d2-ba33-11e6-846e-850e8dd3a2ab.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20866733/18f592e2-ba34-11e6-8847-c77d7570b5bf.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20866758/d3ce4a78-ba34-11e6-90b0-6117ddbc7e25.png)
https://cloud.githubusercontent.com/assets/20930745/20866758/d3ce4a78-ba34-11e6-90b0-6117ddbc7e25.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20866761/e3acf930-ba34-11e6-8c2e-5b908f241450.png

**Comment by dreamnet** [comment]
Small addition:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21040794/5ee69d26-bde7-11e6-94c0-37ad729eb46c.png)
https://cloud.githubusercontent.com/assets/2068130/21040794/5ee69d26-bde7-11e6-94c0-37ad729eb46c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21040799/6d827daa-bde7-11e6-9712-c3245dd7e8e8.png
Credits to @2Qt2beStr8.
