### ISSUE TITLE
Scores app

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8726]
**App Name:** Scores app
**Bundle ID:** com.SofaScore.iOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1176147574">1176147574</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scores-app/id1176147574?mt=8&uo=4">https://itunes.apple.com/us/app/scores-app/id1176147574?mt=8&uo=4</a>
**App Version:** 6.0.0
**Seller:** SofaScore LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sofascore/id1176147573?uo=4">© SofaScore</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/59/9f/20/599f201f-6f84-fa4e-e29e-cf3e274792be/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21015912/f9154390-bd63-11e6-8e94-b7de2c2cab2b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21015912/f9154390-bd63-11e6-8e94-b7de2c2cab2b.png)
https://cloud.githubusercontent.com/assets/20930745/21015912/f9154390-bd63-11e6-8e94-b7de2c2cab2b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21015923/05780dde-bd64-11e6-803d-53df78412e9f.png
