### ISSUE TITLE
SkyBell HD

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8727]
**App Name:** SkyBell HD
**Bundle ID:** com.skybell.doorbell
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035457926">1035457926</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skybell-hd/id1035457926?mt=8&uo=4">https://itunes.apple.com/us/app/skybell-hd/id1035457926?mt=8&uo=4</a>
**App Version:** 3.3.4
**Seller:** SkyBell Technologies, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/skybell-technologies-inc./id778872211?uo=4">© SkyBell Technologies, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple19/v4/1b/61/03/1b610339-a3f0-643e-90f8-c9d79a7c1bfd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21041021/bc880e78-bde8-11e6-9ece-a8145c442748.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21041021/bc880e78-bde8-11e6-9ece-a8145c442748.png)
https://cloud.githubusercontent.com/assets/2068130/21041021/bc880e78-bde8-11e6-9ece-a8145c442748.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21041034/cf36d248-bde8-11e6-94f6-ea93f05ea2b6.png
