### ISSUE TITLE
Starbucks Turkey

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8729]
**App Name:** Starbucks Turkey
**Bundle ID:** com.starbucks.tr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1100698915">1100698915</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/tr/app/starbucks-turkey/id1100698915?mt=8&uo=4">https://itunes.apple.com/tr/app/starbucks-turkey/id1100698915?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Starbucks Coffee Company
**Developer:** <a target="_blank" href="https://itunes.apple.com/tr/developer/starbucks-coffee-company/id331177718?uo=4">© Starbucks Coffee Company</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/57/78/67/57786702-4ec2-e41c-5dbf-1f83ddd6bac0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21131896/8adc58c6-c111-11e6-926b-23371659b2f2.png)

**Comment by dreamnet** [comment]
@alpcinar Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.starbucks.mystarbucks-large.png). Is it not themed on your device?

**Comment by alpcinar** [comment]
@dreamnet Checked the ID from BundleIDs app and the correct ID is "com.starbucks.tr"
Regional App is not themed, updated my first comment.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21131896/8adc58c6-c111-11e6-926b-23371659b2f2.png)
https://cloud.githubusercontent.com/assets/2068130/21131896/8adc58c6-c111-11e6-926b-23371659b2f2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21131907/9d569a8e-c111-11e6-82b2-170ae5b20164.png
