### ISSUE TITLE
Health Mate - Steps tracker & Life coach by Withings

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#873]
**App Name:** Health Mate - Steps tracker & Life coach by Withings
**Bundle ID:** com.withings.wiScaleNG
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542701020">542701020</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/health-mate-steps-tracker/id542701020?mt=8&uo=4">https://itunes.apple.com/us/app/health-mate-steps-tracker/id542701020?mt=8&uo=4</a>
**App Version:** 2.15.2
**Seller:** Withings
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/withings/id298933045?uo=4>© Withings</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple62/v4/df/10/5c/df105ce6-2dd9-26de-39c4-55d4742494a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18192602/260a2bc0-70d6-11e6-9e36-46ad838b7b0f.png)

**Comment by l8er4now** [comment]
Needs an update to the one that exists.

**App Name:** Health Mate - Steps tracker & Life coach by Withings
**Bundle ID:** com.withings.wiScaleNG
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542701020">542701020</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/health-mate-steps-tracker/id542701020?mt=8&uo=4">https://itunes.apple.com/us/app/health-mate-steps-tracker/id542701020?mt=8&uo=4</a>
**App Version:** 2.15.2
**Seller:** Withings
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/withings/id298933045?uo=4>© Withings</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple62/v4/df/10/5c/df105ce6-2dd9-26de-39c4-55d4742494a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18192602/260a2bc0-70d6-11e6-9e36-46ad838b7b0f.png)
https://cloud.githubusercontent.com/assets/2068130/18192602/260a2bc0-70d6-11e6-9e36-46ad838b7b0f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/18192613/344d7df4-70d6-11e6-8ef5-e12ec694767e.png
