### ISSUE TITLE
IKEA Mobil

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8730]
**App Name:** IKEA Mobil
**Bundle ID:** com.magiclick.ikea
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1147147196">1147147196</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/tr/app/ikea-mobil/id1147147196?mt=8&uo=4">https://itunes.apple.com/tr/app/ikea-mobil/id1147147196?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** MagiClick Digital Solutions
**Developer:** <a target="_blank" href="https://itunes.apple.com/tr/developer/magiclick-digital-solutions/id331557524?uo=4">© MagiClick Digital Solutions</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/ff/ed/7a/ffed7a1e-9bb7-6d62-2d25-04dd68fc77b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078355/3bba825a-bf6c-11e6-8186-32595ce9acac.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078355/3bba825a-bf6c-11e6-8186-32595ce9acac.png)
https://cloud.githubusercontent.com/assets/2068130/21078355/3bba825a-bf6c-11e6-8186-32595ce9acac.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21078356/4a7965cc-bf6c-11e6-9712-05fac6edcc44.png
