### ISSUE TITLE
Cleaner for Instagram - Mass unfollow block tool

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8731]
**App Name:** Cleaner for Instagram - Mass unfollow block tool
**Bundle ID:** ro.novasoft.cleanerig
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1019607006">1019607006</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cleaner-for-instagram-mass/id1019607006?mt=8&uo=4">https://itunes.apple.com/us/app/cleaner-for-instagram-mass/id1019607006?mt=8&uo=4</a>
**App Version:** 3.8
**Seller:** Robert Neagu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/robert-neagu/id303515455?uo=4">© Robert Neagu</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/a7/90/2e/a7902e1d-f587-1c6a-5ad2-496032302085/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078221/c9dc6e5e-bf67-11e6-9339-805b52e08a70.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078221/c9dc6e5e-bf67-11e6-9339-805b52e08a70.png)
https://cloud.githubusercontent.com/assets/2068130/21078221/c9dc6e5e-bf67-11e6-9339-805b52e08a70.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21078222/d9177c7e-bf67-11e6-8871-1d46896a0db0.png
