### ISSUE TITLE
MobilDeniz

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8732]
**App Name:** MobilDeniz
**Bundle ID:** com.veripark.denizbankiphon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484930816">484930816</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobildeniz/id484930816?mt=8&uo=4">https://itunes.apple.com/us/app/mobildeniz/id484930816?mt=8&uo=4</a>
**App Version:** 3.4.3
**Seller:** Denizbank A.S.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/denizbank-a.s./id434814150?uo=4">© DenizBank A.Ş.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/89/ac/85/89ac85a2-a2a1-b0c6-8e30-a268bdcb437f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21287051/aa58245a-c463-11e6-84db-4c1c571dd9fc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21287006/c7331edc-c462-11e6-8bbb-4a2fe3142746.png)
https://cloud.githubusercontent.com/assets/20930745/21287006/c7331edc-c462-11e6-8bbb-4a2fe3142746.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21287010/d4d5d430-c462-11e6-9b1b-441d2780043e.png
