### ISSUE TITLE
Turkcell Hesabım

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#8733]
**App Name:** Turkcell Hesabım
**Bundle ID:** com.turkcell.CSI
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=335162906">335162906</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/turkcell-hesab-m/id335162906?mt=8&uo=4">https://itunes.apple.com/us/app/turkcell-hesab-m/id335162906?mt=8&uo=4</a>
**App Version:** 5.4
**Seller:** Turkcell Teknoloji
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/turkcell-iletisim-hizmetleri/id305642482?uo=4">© Turkcell Iletisim Hizmetleri A.S.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/13/b4/81/13b481a3-3a8c-61e6-5a37-6aed6733d592/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078397/c0e47fde-bf6d-11e6-8665-c915c7b36354.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078397/c0e47fde-bf6d-11e6-8665-c915c7b36354.png)
https://cloud.githubusercontent.com/assets/2068130/21078397/c0e47fde-bf6d-11e6-8665-c915c7b36354.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21078398/d12e2f20-bf6d-11e6-9dac-bc01689d02ff.png

**Comment by alpcinar** [comment]
Needs update, I guess.

**Comment by ivanov007** [comment]
is the same icon, I will update the request but won't reopen the issue
