### ISSUE TITLE
Price Tag - Find best apps

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8734]
**App Name:** Price Tag - Find best apps
**Bundle ID:** io.seedlab.pricetag
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1166819590">1166819590</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/price-tag-find-best-apps/id1166819590?mt=8&uo=4">https://itunes.apple.com/us/app/price-tag-find-best-apps/id1166819590?mt=8&uo=4</a>
**App Version:** 2.3.6
**Seller:** Liu Yi
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/liu-yi/id784494589?uo=4">© Liu Yi</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/24/62/e8/2462e83b-dea4-1e31-dc3d-e609b9ffe8b4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37731792-6f1e6b34-2d43-11e8-8b89-8ec2b0a624d9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078164/58b11d52-bf66-11e6-86e0-177cfb9d0c38.png)
https://cloud.githubusercontent.com/assets/2068130/21078164/58b11d52-bf66-11e6-86e0-177cfb9d0c38.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21078166/68c4bdca-bf66-11e6-9776-ab4022fa39f9.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Price Tag - Find best apps
**Bundle ID:** io.seedlab.pricetag
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1166819590">1166819590</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/price-tag-find-best-apps/id1166819590?mt=8&uo=4">https://itunes.apple.com/us/app/price-tag-find-best-apps/id1166819590?mt=8&uo=4</a>
**App Version:** 2.3.6
**Seller:** Liu Yi
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/liu-yi/id784494589?uo=4">© Liu Yi</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/24/62/e8/2462e83b-dea4-1e31-dc3d-e609b9ffe8b4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37731792-6f1e6b34-2d43-11e8-8b89-8ec2b0a624d9.png)
https://user-images.githubusercontent.com/20930745/37731792-6f1e6b34-2d43-11e8-8b89-8ec2b0a624d9.png

Source:
https://user-images.githubusercontent.com/20930745/37731812-84c4f2b4-2d43-11e8-9db6-c9e4d339d472.png
