### ISSUE TITLE
ClutchPoints - Unlock Your Sports World

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8735]
**App Name:** ClutchPoints - Unlock Your Sports World
**Bundle ID:** com.clutchpoints.ClutchPoints
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1044413150">1044413150</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clutchpoints-unlock-your-sports/id1044413150?mt=8&uo=4">https://itunes.apple.com/us/app/clutchpoints-unlock-your-sports/id1044413150?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Memeco, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/memeco-llc/id1044413149?uo=4">© Memeco, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/4e/7f/c7/4e7fc71b-a948-5653-d6d1-4cdaf9b61ce6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078145/5aace524-bf65-11e6-9b78-100f9d6c4edd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21078145/5aace524-bf65-11e6-9b78-100f9d6c4edd.png)
https://cloud.githubusercontent.com/assets/2068130/21078145/5aace524-bf65-11e6-9b78-100f9d6c4edd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21078146/6b4759d2-bf65-11e6-844d-94eafd4462ff.png
