### ISSUE TITLE
iDisplayMate

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8736]
**App Name:** iDisplayMate
**Bundle ID:** kr.mobilesoft.iDisplayMate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1142145644">1142145644</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/idisplaymate/id1142145644?mt=8&uo=4">https://itunes.apple.com/us/app/idisplaymate/id1142145644?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** yongxu jin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yongxu-jin/id366755580?uo=4">© yongxu jin</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/c9/40/67/c9406709-0dcf-7028-97f2-5ea84846a004/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284872/c2d6a7e4-c428-11e6-95b7-078c7ae1c5d5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284872/c2d6a7e4-c428-11e6-95b7-078c7ae1c5d5.png)
https://cloud.githubusercontent.com/assets/20930745/21284872/c2d6a7e4-c428-11e6-95b7-078c7ae1c5d5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21284873/cf281b22-c428-11e6-9241-fd39d660fbbb.png
