### ISSUE TITLE
Air Dialer - Fastest Dial Phone Widget

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8737]
**App Name:** Air Dialer - Fastest Dial Phone Widget
**Bundle ID:** com.bonbon.airdialer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1183703953">1183703953</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/air-dialer-fastest-dial-phone/id1183703953?mt=8&uo=4">https://itunes.apple.com/us/app/air-dialer-fastest-dial-phone/id1183703953?mt=8&uo=4</a>
**App Version:** 1.1.7
**Seller:** Hieu Bui
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hieu-bui/id1178961843?uo=4">© Hieu Bui</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/50/fa/41/50fa4175-2063-7692-413d-4de3b0a2eb6a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284746/bb6a5f58-c425-11e6-98aa-fe13e21ec170.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284746/bb6a5f58-c425-11e6-98aa-fe13e21ec170.png)
https://cloud.githubusercontent.com/assets/20930745/21284746/bb6a5f58-c425-11e6-98aa-fe13e21ec170.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21284748/d6f1743c-c425-11e6-879c-2aaccff078bb.png
