### ISSUE TITLE
Keep! - Save web site pages to PDF for archiving and sharing

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8738]
**App Name:** Keep! - Save web site pages to PDF for archiving and sharing
**Bundle ID:** com.timfoster.KeepSave
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=911012246">911012246</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/keep!-save-web-site-pages/id911012246?mt=8&uo=4">https://itunes.apple.com/us/app/keep!-save-web-site-pages/id911012246?mt=8&uo=4</a>
**App Version:** 1.25
**Seller:** Tim Foster
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tim-foster/id414662309?uo=4">© Tim Foster</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/37/6d/ad/376dadf1-8cd5-30b2-c766-b61f417517ed/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285271/1aa61f62-c434-11e6-965e-05dc7551c886.png)

**Comment by 2Qt2beStr8** [comment]
???

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285271/1aa61f62-c434-11e6-965e-05dc7551c886.png)
https://cloud.githubusercontent.com/assets/20930745/21285271/1aa61f62-c434-11e6-965e-05dc7551c886.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21285273/2692d464-c434-11e6-8567-d78a97a3bba0.png
