### ISSUE TITLE
Vantage Calendar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8739]
**App Name:** Vantage Calendar
**Bundle ID:** slickerthanmost.overview
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=777313686">777313686</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/vantage-calendar/id777313686?uo=4">https://apps.apple.com/us/app/vantage-calendar/id777313686?uo=4</a>
**App Version:** 3.1.6
**Seller:** Fortyfour AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fortyfour-ab/id452146266?uo=4">© Fortyfour AB</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/94/03/57/9403575c-abe6-6152-999e-f80c394d3a0b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59294822-98e08980-8c82-11e9-8c6f-9a84af343e69.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284772/861b0cc0-c426-11e6-8073-1e38dda62526.png)
https://cloud.githubusercontent.com/assets/20930745/21284772/861b0cc0-c426-11e6-8073-1e38dda62526.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21284775/9356ee18-c426-11e6-9bd5-182e02454ad3.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Vantage Calendar
**Bundle ID:** slickerthanmost.overview
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=777313686">777313686</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/vantage-calendar/id777313686?uo=4">https://apps.apple.com/us/app/vantage-calendar/id777313686?uo=4</a>
**App Version:** 3.1.6
**Seller:** Fortyfour AB
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/fortyfour-ab/id452146266?uo=4">© Fortyfour AB</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/94/03/57/9403575c-abe6-6152-999e-f80c394d3a0b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59294822-98e08980-8c82-11e9-8c6f-9a84af343e69.png)
https://user-images.githubusercontent.com/2068130/59294822-98e08980-8c82-11e9-8c6f-9a84af343e69.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59294848-abf35980-8c82-11e9-960e-e26d1c016065.png
