### ISSUE TITLE
True Weight

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#874]
**App Name:** True Weight
**Bundle ID:** com.madeupsoftware.TrueWeight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=287941226">287941226</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/true-weight/id287941226?mt=8&uo=4">https://itunes.apple.com/us/app/true-weight/id287941226?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Rory O'Bryan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/made-up-software/id287941229?uo=4>© made-up software</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple2/v4/da/b0/bb/dab0bb94-d6e9-46ac-a6c2-5814dccf71e5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409899/04c37338-92df-11e6-8bfc-0518b0484b2d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409899/04c37338-92df-11e6-8bfc-0518b0484b2d.png)
https://cloud.githubusercontent.com/assets/20930745/19409899/04c37338-92df-11e6-8bfc-0518b0484b2d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409903/16170fa0-92df-11e6-8e8d-3f39180f290e.png
