### ISSUE TITLE
weekflow 2 – the visual calendar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8740]
**App Name:** weekflow 2 – the visual calendar
**Bundle ID:** com.allthirds.weekflow-2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=976947039">976947039</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weekflow-2-visual-calendar/id976947039?mt=8&uo=4">https://itunes.apple.com/us/app/weekflow-2-visual-calendar/id976947039?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Frank Anton Mayet, Ralf Mayet, Alexander Mayet GbR
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/allthirds/id593443556?uo=4">© allthirds</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/7e/14/a5/7e14a5d2-b40e-e2bd-aede-6ef0e95e355a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284928/3d089292-c42a-11e6-9911-51ab6b8513d5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284916/ed659ece-c429-11e6-9a3f-68c8bd37b928.png)
https://cloud.githubusercontent.com/assets/20930745/21284916/ed659ece-c429-11e6-9a3f-68c8bd37b928.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21284921/02d5bb22-c42a-11e6-881c-d4f2c5b0e2b8.png
