### ISSUE TITLE
Editorial

### ISSUE THREAD

**Issue by ukhf-jm** [glasklart/hd#8741]
**App Name:** Editorial
**Bundle ID:** com.omz-software.Editorial
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=673907758">673907758</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/editorial/id673907758?mt=8&uo=4">https://itunes.apple.com/us/app/editorial/id673907758?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Ole Zorn
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/omz-software/id285608316?uo=4">© omz:software</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple1/v4/87/36/3f/87363f8d-1db0-899a-b53c-91e853835911/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284950/53892062-c42b-11e6-89c2-64002a32d647.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284950/53892062-c42b-11e6-89c2-64002a32d647.png)
https://cloud.githubusercontent.com/assets/20930745/21284950/53892062-c42b-11e6-89c2-64002a32d647.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21284962/63a382e4-c42b-11e6-84a8-4d44b723ae06.png
