### ISSUE TITLE
Monzo

### ISSUE THREAD

**Issue by ukhf-jm** [glasklart/hd#8742]
**App Name:** Monzo
**Bundle ID:** io.b2a.BankProd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1052238659">1052238659</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/monzo/id1052238659?mt=8&uo=4">https://itunes.apple.com/us/app/monzo/id1052238659?mt=8&uo=4</a>
**App Version:** 1.9.0
**Seller:** Monzo Bank Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/monzo-bank-limited/id995273047?uo=4">© Monzo Bank Limited</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/ee/10/d5/ee10d502-5c9c-c57d-3ee9-e07701f4a890/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285018/206ac9c2-c42d-11e6-871b-279bd0a70e73.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285018/206ac9c2-c42d-11e6-871b-279bd0a70e73.png)
https://cloud.githubusercontent.com/assets/20930745/21285018/206ac9c2-c42d-11e6-871b-279bd0a70e73.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21285020/2f874caa-c42d-11e6-905d-66ba5fa4302b.png
