### ISSUE TITLE
Hook Champ

### ISSUE THREAD

**Issue by ukhf-jm** [glasklart/hd#8743]
**App Name:** Hook Champ
**Bundle ID:** com.rocketcat.HookChamp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=334626134">334626134</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hook-champ/id334626134?mt=8&uo=4">https://itunes.apple.com/us/app/hook-champ/id334626134?mt=8&uo=4</a>
**App Version:** 1.60
**Seller:** Rocketcat LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rocketcat-llc/id305576988?uo=4">© Rocketcat LLC</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/b3/d9/cc/b3d9ccbe-cf79-4b42-5ecd-4f7830491215/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21292482/8bdf4cfc-c507-11e6-9a7a-c5c3c8483770.png)

**Comment by dreamnet** [comment]
?
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21292482/8bdf4cfc-c507-11e6-9a7a-c5c3c8483770.png)
https://cloud.githubusercontent.com/assets/2068130/21292482/8bdf4cfc-c507-11e6-9a7a-c5c3c8483770.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21292483/9d33837e-c507-11e6-99f1-abe4cc15b4da.png

**Comment by ukhf-jm** [comment]
I think that looks fine, thanks.
