### ISSUE TITLE
Minigore

### ISSUE THREAD

**Issue by ukhf-jm** [glasklart/hd#8745]
**App Name:** Minigore
**Bundle ID:** com.chillingo.minigore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324016249">324016249</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minigore/id324016249?mt=8&uo=4">https://itunes.apple.com/us/app/minigore/id324016249?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** Mountain Sheep
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mountain-sheep/id392924730?uo=4">© Mountain Sheep</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/3e/07/93/3e079381-e12a-b2fa-a602-b003f5e70290/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21292385/7f1bebbe-c503-11e6-87f5-9df26c319431.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21292385/7f1bebbe-c503-11e6-87f5-9df26c319431.png)
https://cloud.githubusercontent.com/assets/2068130/21292385/7f1bebbe-c503-11e6-87f5-9df26c319431.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21292388/8e10a5e2-c503-11e6-8754-b7e8f84eddb9.png
