### ISSUE TITLE
R-TYPE

### ISSUE THREAD

**Issue by ukhf-jm** [glasklart/hd#8746]
**App Name:** R.TYPE
**Bundle ID:** com.dotemu.rtypeios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=657336473">657336473</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/r.type/id657336473?mt=8&uo=4">https://itunes.apple.com/us/app/r.type/id657336473?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** DotEmu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dotemu/id329185054?uo=4">© DotEmu</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/0c/5a/1a/0c5a1ab2-697e-9aab-fef6-cd37a416fb78/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21286554/9448211c-c457-11e6-977b-dc2a512cbbf8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21286554/9448211c-c457-11e6-977b-dc2a512cbbf8.png)
https://cloud.githubusercontent.com/assets/2068130/21286554/9448211c-c457-11e6-977b-dc2a512cbbf8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21286557/a47dee72-c457-11e6-8654-77913cc9bc65.png
