### ISSUE TITLE
R-TYPE II

### ISSUE THREAD

**Issue by ukhf-jm** [glasklart/hd#8747]
**App Name:** R-TYPE II
**Bundle ID:** com.dotemu.rtype2ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=787148904">787148904</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/r-type-ii/id787148904?mt=8&uo=4">https://itunes.apple.com/us/app/r-type-ii/id787148904?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** DotEmu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dotemu/id329185054?uo=4">© DotEmu</a>
**Supported Devices:** iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/ef/4c/e2/ef4ce2af-dd9f-ad51-c848-1cdbb206e558/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21286544/587775b6-c457-11e6-9e56-54b188107bb3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21286544/587775b6-c457-11e6-9e56-54b188107bb3.png)
https://cloud.githubusercontent.com/assets/2068130/21286544/587775b6-c457-11e6-9e56-54b188107bb3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21286545/67a6071e-c457-11e6-8384-3adc4a66bee1.png
