### ISSUE TITLE
Redactor

### ISSUE THREAD

**Issue by ukhf-jm** [glasklart/hd#8748]
**App Name:** Redactor
**Bundle ID:** org.christopherstoll.Redactor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=960293582">960293582</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/redactor/id960293582?mt=8&uo=4">https://itunes.apple.com/us/app/redactor/id960293582?mt=8&uo=4</a>
**App Version:** 0.3.4
**Seller:** Christopher Stoll
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/christopher-stoll/id730372259?uo=4">© Christopher Stoll</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/7e/e6/cd/7ee6cd5a-05ad-8a2e-2fa1-5a04f5027cea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284827/b6cf9a1a-c427-11e6-894b-a6468755ab8b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21284827/b6cf9a1a-c427-11e6-894b-a6468755ab8b.png)
https://cloud.githubusercontent.com/assets/20930745/21284827/b6cf9a1a-c427-11e6-894b-a6468755ab8b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21284829/c4095c48-c427-11e6-9388-cecbd1d31f3b.png
