### ISSUE TITLE
The Last Rocket

### ISSUE THREAD

**Issue by ukhf-jm** [glasklart/hd#8749]
**App Name:** The Last Rocket
**Bundle ID:** com.shauninman.lastrocket
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=429747672">429747672</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-last-rocket/id429747672?mt=8&uo=4">https://itunes.apple.com/us/app/the-last-rocket/id429747672?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Shaun Inman
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/shaun-inman/id303753397?uo=4">© Shaun Inman</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/95/82/a3/9582a3b4-331f-0017-1421-635d7a658958/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21288794/6d6c2162-c48c-11e6-9563-73c168a4b5b5.png)

**Comment by dreamnet** [comment]
?
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21288794/6d6c2162-c48c-11e6-9563-73c168a4b5b5.png)
https://cloud.githubusercontent.com/assets/2068130/21288794/6d6c2162-c48c-11e6-9563-73c168a4b5b5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21288798/7d7ac0ea-c48c-11e6-98f6-38df8049976f.png

**Comment by ukhf-jm** [comment]
Looks good, thanks @dreamnet
