### ISSUE TITLE
Map My Ride - GPS Cycling & Route Tracker

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#875]
**App Name:** Map My Ride - GPS Cycling & Route Tracker
**Bundle ID:** Q5AWL8WCY6.iMapMyRide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=292223170">292223170</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/map-my-ride-gps-cycling-route/id292223170?mt=8&uo=4">https://itunes.apple.com/us/app/map-my-ride-gps-cycling-route/id292223170?mt=8&uo=4</a>
**App Version:** 16.10.1
**Seller:** MapMyFitness
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/under-armour/id291890423?uo=4>© Under Armour</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/17/6a/8f/176a8fad-40fc-b115-5a16-1f48768aca49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19849627/97a1974e-9f54-11e6-8765-f9fa2eac281d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19849627/97a1974e-9f54-11e6-8765-f9fa2eac281d.png)
https://cloud.githubusercontent.com/assets/20930745/19849627/97a1974e-9f54-11e6-8765-f9fa2eac281d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19849650/ad59d826-9f54-11e6-9072-81a64af4bab9.png
