### ISSUE TITLE
ChuChu Rocket!

### ISSUE THREAD

**Issue by ukhf-jm** [glasklart/hd#8750]
**App Name:** ChuChu Rocket!
**Bundle ID:** com.sega.chuchu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=392785292">392785292</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chuchu-rocket!/id392785292?mt=8">https://itunes.apple.com/us/app/chuchu-rocket!/id392785292?mt=8</a>
**App Version:** 1.1.2
**Seller:** SEGA
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/sega/id281966698?mt=8">© SEGA</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://a1825.phobos.apple.com/us/r30/Purple/v4/c4/aa/ca/c4aaca40-00ca-86fa-2fce-c62ac4ac96f0/icon1024x1024.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21286302/7aefd16c-c450-11e6-83d2-390cff5b8eb9.png)

**Comment by ukhf-jm** [comment]
NOTE: This is a dead app that can no longer be purchased new on the App Store. It can still be redownloaded by anyone who purchased it prior to removal. I have tried to fill out the info manually as best as I can with viewing the iTunesMetadata.plist file and with information obtained via Google.

**Comment by ivanov007** [comment]
thanks for the clarification, nice job filling up the template

**Comment by Anuskuss** [comment]
@ukhf-jm It would help the designers if you upload a bigger image. Can you upload the 1024x1024px version of your icon from `/var/mobile/Containers/Bundle/Application/*/iTunesArtwork(.png)`

**Comment by Trubbel** [comment]
It seems like this application only have 512 × 512px resolution. Most likely because it came out in 2010.

**Comment by ukhf-jm** [comment]
Interesting...the link that I used was for 1024x1024.png but it just provides a 512x512 file. Sorry but I don't have a 1024x1024. Checking the iTunesArtwork file only shows a 512x512 file as well.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21286302/7aefd16c-c450-11e6-83d2-390cff5b8eb9.png)
https://cloud.githubusercontent.com/assets/2068130/21286302/7aefd16c-c450-11e6-83d2-390cff5b8eb9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21286305/8887111e-c450-11e6-80ca-cf1e385de83d.png
