### ISSUE TITLE
MarginNote Pro - Efficient study PDF & EPUB books

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8751]
**App Name:** MarginNote Pro - Efficient study PDF & EPUB books
**Bundle ID:** QReader.MarginNote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=723205553">723205553</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/marginnote-pro-efficient-study/id723205553?mt=8&uo=4">https://itunes.apple.com/us/app/marginnote-pro-efficient-study/id723205553?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Sun Min
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sun-min/id723205556?uo=4">© Sun Min</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/ea/b5/00/eab5001b-0778-ebd1-5c23-30a30a51b358/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285039/2b4ce842-c42e-11e6-993d-98887534b84d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285039/2b4ce842-c42e-11e6-993d-98887534b84d.png)
https://cloud.githubusercontent.com/assets/20930745/21285039/2b4ce842-c42e-11e6-993d-98887534b84d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21285040/3856da16-c42e-11e6-9edb-a4046562303e.png
