### ISSUE TITLE
Disney World Maps, Wait Times, Touring Plans Free

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8752]
**App Name:** Disney World Maps, Wait Times, Touring Plans Free
**Bundle ID:** com.phunware.utorlando.lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=385303379">385303379</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/disney-world-maps-wait-times/id385303379?mt=8&uo=4">https://itunes.apple.com/us/app/disney-world-maps-wait-times/id385303379?mt=8&uo=4</a>
**App Version:** 3.2.1
**Seller:** InsiderGuide.com, LC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/undercovertourist.com/id453801858?uo=4">© UndercoverTourist.com</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/1e/57/17/1e57174a-e493-8fe2-a6fb-be7f6a86941f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21286638/eedb03d6-c459-11e6-92b3-952caa1d69fe.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21286638/eedb03d6-c459-11e6-92b3-952caa1d69fe.png)
https://cloud.githubusercontent.com/assets/2068130/21286638/eedb03d6-c459-11e6-92b3-952caa1d69fe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21286641/fc48794a-c459-11e6-8f34-af8d2c112ee8.png
