### ISSUE TITLE
Yahoo Answers Now

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8753]
**App Name:** Yahoo Answers Now
**Bundle ID:** com.yahoo.cxshb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1111749046">1111749046</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahoo-answers-now/id1111749046?mt=8&uo=4">https://itunes.apple.com/us/app/yahoo-answers-now/id1111749046?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4">© Yahoo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/ca/6a/2a/ca6a2a1d-5cc0-6e81-6e08-9720300f140a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285080/3ae3bf96-c42f-11e6-8343-a340162e821d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285080/3ae3bf96-c42f-11e6-8343-a340162e821d.png)
https://cloud.githubusercontent.com/assets/20930745/21285080/3ae3bf96-c42f-11e6-8343-a340162e821d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21285084/4b85d85c-c42f-11e6-973a-5e42f2b2cf93.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21285107/ba9f054c-c42f-11e6-9ba3-7187ae7546af.png)
https://cloud.githubusercontent.com/assets/20930745/21285107/ba9f054c-c42f-11e6-9ba3-7187ae7546af.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21285108/cb275234-c42f-11e6-8535-cce184ae96c1.png
