### ISSUE TITLE
Air Display 3

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8755]
**App Name:** Air Display 3
**Bundle ID:** com.avatron.Air-Display3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=967502646">967502646</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/air-display-3/id967502646?mt=8&uo=4">https://itunes.apple.com/us/app/air-display-3/id967502646?mt=8&uo=4</a>
**App Version:** 3.0.3
**Seller:** Avatron Software, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/avatron-software-inc./id289943358?uo=4">© Avatron Software, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple2/v4/ae/af/13/aeaf130c-14eb-c8f9-aace-c015fd6d3ef3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21325510/03dde914-c627-11e6-9ccb-8fa3c2ea6a6e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21325510/03dde914-c627-11e6-9ccb-8fa3c2ea6a6e.png)
https://cloud.githubusercontent.com/assets/20930745/21325510/03dde914-c627-11e6-9ccb-8fa3c2ea6a6e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21325699/d99031de-c627-11e6-88ef-ca79fe25a69a.png
