### ISSUE TITLE
Santander Wallet

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#8756]
**App Name:** Santander Wallet
**Bundle ID:** es.santander.wallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979216560">979216560</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/santander-wallet/id979216560?mt=8&uo=4">https://itunes.apple.com/us/app/santander-wallet/id979216560?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Banco Santander SA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/banco-santander/id373170918?uo=4">© Banco Santander</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/bf/3b/95/bf3b95eb-6e6a-a0d3-a046-8309fd56ab8a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21325961/f74cbeda-c628-11e6-9fab-9577ac278ae0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21325961/f74cbeda-c628-11e6-9fab-9577ac278ae0.png)
https://cloud.githubusercontent.com/assets/20930745/21325961/f74cbeda-c628-11e6-9fab-9577ac278ae0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21325976/035cecf4-c629-11e6-8073-b443833f876e.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21326327/6d11ff9e-c62a-11e6-9371-3fdcbaefd945.png)
https://cloud.githubusercontent.com/assets/20930745/21326327/6d11ff9e-c62a-11e6-9371-3fdcbaefd945.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21326347/8182e664-c62a-11e6-90ff-1fe9551fbeb7.png

**Comment by dreamnet** [comment]
@grkka What version do you prefer?

**Comment by grkka** [comment]
@2Qt2beStr8 @dreamnet The first option. Thanks!
