### ISSUE TITLE
Mint:Personal Finance & Money

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8757]
**App Name:** Mint:Personal Finance & Money
**Bundle ID:** com.mint.internal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300238550">300238550</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mint-personal-finance-money/id300238550?mt=8&uo=4">https://itunes.apple.com/us/app/mint-personal-finance-money/id300238550?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** Mint.com
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mint-com/id300238553?uo=4">© Mint.com</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/82/96/fb/8296fb85-57e0-0ed6-3610-7002af2daf33/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com mint internal-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45231670-0f53f380-b2cd-11e8-8784-5a8af177ea51.png)

**Comment by dreamnet** [comment]
Icon exists, but needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21484960/a20c3536-cb9b-11e6-8044-c69e97a34868.png)
https://cloud.githubusercontent.com/assets/20930745/21484960/a20c3536-cb9b-11e6-8044-c69e97a34868.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21484963/afcb2718-cb9b-11e6-9ba1-6a33237d67e1.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Mint:Personal Finance & Money
**Bundle ID:** com.mint.internal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300238550">300238550</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mint-personal-finance-money/id300238550?mt=8&uo=4">https://itunes.apple.com/us/app/mint-personal-finance-money/id300238550?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** Mint.com
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mint-com/id300238553?uo=4">© Mint.com</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/82/96/fb/8296fb85-57e0-0ed6-3610-7002af2daf33/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![com mint internal-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45231670-0f53f380-b2cd-11e8-8784-5a8af177ea51.png)
https://user-images.githubusercontent.com/2068130/45231670-0f53f380-b2cd-11e8-8784-5a8af177ea51.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45231682-1f6bd300-b2cd-11e8-9fac-93927036fd01.png
