### ISSUE TITLE
Health Tracking by Gyroscope

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8758]
**App Name:** Health Tracking by Gyroscope
**Bundle ID:** com.gyroscope.gyroscope
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1104085053">1104085053</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/health-tracking-by-gyroscope/id1104085053?mt=8&uo=4">https://itunes.apple.com/us/app/health-tracking-by-gyroscope/id1104085053?mt=8&uo=4</a>
**App Version:** 1.8.3
**Seller:** Gyroscope Innovations, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gyroscope-innovations/id1038793581?uo=4">© Gyroscope Innovations</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/0b/f9/36/0bf93649-16a5-5538-c2d9-65460d97b5b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21484751/32e99840-cb98-11e6-9b5e-8e60a08285ef.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21484751/32e99840-cb98-11e6-9b5e-8e60a08285ef.png)
https://cloud.githubusercontent.com/assets/20930745/21484751/32e99840-cb98-11e6-9b5e-8e60a08285ef.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21484757/3e47c68a-cb98-11e6-9de2-884152708527.png
