### ISSUE TITLE
Mobile Passport - Officially Authorized by CBP

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8759]
**App Name:** Mobile Passport - Officially Authorized by CBP
**Bundle ID:** us.mobilepassport.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=907024887">907024887</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mobile-passport-officially/id907024887?mt=8&uo=4">https://itunes.apple.com/us/app/mobile-passport-officially/id907024887?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Airside Mobile LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/airside-mobile-llc/id345202566?uo=4">© Airside Mobile LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/f6/c2/5e/f6c25e50-ed78-4d44-aa69-29f1b986278e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21484678/13c96928-cb97-11e6-81ef-ceaac97e5162.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21484678/13c96928-cb97-11e6-81ef-ceaac97e5162.png)
https://cloud.githubusercontent.com/assets/20930745/21484678/13c96928-cb97-11e6-81ef-ceaac97e5162.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21484684/21c2ec34-cb97-11e6-8192-14f3f635ec76.png
