### ISSUE TITLE
Precision Pulse

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#876]
**App Name:** Precision Pulse
**Bundle ID:** com.hrvfit.HRM
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=381116330">381116330</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/precision-pulse/id381116330?mt=8&uo=4">https://itunes.apple.com/us/app/precision-pulse/id381116330?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** HRV Fit Ltd.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/hrv-fit-ltd./id331348948?uo=4>© HRV Fit Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/2a/e9/28/2ae928b1-a48e-fb6a-bf86-4474874be375/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19645916/6eca1ae2-99f7-11e6-8652-aeeddfca1d35.png)

**Comment by dreamnet** [comment]
Same as #8384. Icon by @2Qt2beStr8.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19645916/6eca1ae2-99f7-11e6-8652-aeeddfca1d35.png)
https://cloud.githubusercontent.com/assets/20930745/19645916/6eca1ae2-99f7-11e6-8652-aeeddfca1d35.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/20930745/19645947/91337ace-99f7-11e6-82c3-c45f6daf6b5d.png
