### ISSUE TITLE
FIFA Mobile Soccer

### ISSUE THREAD

**Issue by illinikev** [glasklart/hd#8764]
**App Name:** FIFA Mobile Soccer
**Bundle ID:** com.ea.ios.fifamobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1094930513">1094930513</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fifa-mobile-soccer/id1094930513?mt=8&uo=4">https://itunes.apple.com/us/app/fifa-mobile-soccer/id1094930513?mt=8&uo=4</a>
**App Version:** 3.2.1
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/a9/77/ff/a977ff43-c177-58a6-cc59-86536db475f7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21552672/83388e24-ce03-11e6-960c-7c62da1c3c02.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21552672/83388e24-ce03-11e6-960c-7c62da1c3c02.png)
https://cloud.githubusercontent.com/assets/2068130/21552672/83388e24-ce03-11e6-960c-7c62da1c3c02.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21552685/92596e00-ce03-11e6-9f8a-fae1d7346edc.png
