### ISSUE TITLE
WunderStation – Weather from your neighborhood

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8765]
**App Name:** WunderStation – Weather from your neighborhood
**Bundle ID:** com.wunderground.wunderstation
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=906099986">906099986</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wunderstation-weather-from/id906099986?mt=8&uo=4">https://itunes.apple.com/us/app/wunderstation-weather-from/id906099986?mt=8&uo=4</a>
**App Version:** 1.2.4
**Seller:** Weather Underground, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/weather-underground-llc/id284699897?uo=4">© Weather Underground, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/e8/97/9d/e8979d7e-c02c-6a8a-4d1e-f413803039b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23035958/5aa6a046-f481-11e6-8313-6997280a7068.png)

**Comment by Sly-Fi** [comment]
I just discovered that this is an "iPad only" app, so unless there will be a Glasklart for iPad, this issue may be deleted.  Thanks!

**Comment by dreamnet** [comment]
@Sly-Fi Glasklart acually works fine on iPad using Anemone. There is just a small issue with the size of the folder icons on iPad Pro and you have to rename the `Info.plist` files.
![image](https://cloud.githubusercontent.com/assets/2068130/21596888/fee9a4a4-d141-11e6-8068-e86d05ba47a2.png)

**Comment by Sly-Fi** [comment]
Wow, I didn't know that.  What do I name the Info.plist file(s)? Sorry, I am not finding a post with instructions.  I will reopen the issue then.

I'm excited to have my iPad air 2 looking good!

**Comment by dreamnet** [comment]
@Sly-Fi 
- Navigate to `/Library/Themes/` on your device.
- In this folder you find the varoius [Glasklart folders](https://github.com/glasklart/hd/tree/master/Library/Themes).
- In the Glasklart folders you will find two files, `Info.plist` and `iPad.Info.plist`.
- Rename the file `Info.plist` to something else and
- rename the file `iPad.Info.plist` to `Info.plist`.
- Do this for each Glasklart folder.
--- ---
I hope tis works on the iPad Air 2 - I have only tested it on iPad Pro.
--- ---
P.S.: It would be nice if you can post a screenshot of your iPad Air 2, containing the Calendar icon, because the main main thing that the `Info.plist` does is changing the font of the "live" Calendar icon.

**Comment by Sly-Fi** [comment]
Thanks @dreamnet !  I had been waiting for 5.43 to appear on Cydia but I gave up and loaded manually instead.  As you can see it looks great on iPad Air 2 - I used "Bigify" to make the icons slightly bigger.  There seem to be several icons on my iPad that aren't themed but that are on my iPhone - I will go through them and see if I need to make new requests for this.
![img_0735](https://cloud.githubusercontent.com/assets/11544849/22138497/27098b52-de9e-11e6-818e-a5a34002f9aa.jpg)

**Comment by dreamnet** [comment]
@Sly-Fi Jup, looks fine - except for the Calendar icon, the weekday and the date seems to be too big. This is a problem with the values for `FontSize` and `TextYoffset` in the `Info.plist`. If you want to be smaller, you have to play around with these values.

**Comment by Sly-Fi** [comment]
@dreamnet Hmm, I hadn't really noticed that the calendar icon wasn't quite right, but now that you said so it is bothering me, so I will play with those values when I have some time :)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23035958/5aa6a046-f481-11e6-8313-6997280a7068.png)
https://cloud.githubusercontent.com/assets/2068130/23035958/5aa6a046-f481-11e6-8313-6997280a7068.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23035978/68cd304a-f481-11e6-9b13-da9d8d8022ee.png
