### ISSUE TITLE
Coordinates Converter

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8766]
**App Name:** Coordinates Converter
**Bundle ID:** com.kasamasoft.coordinateconverter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=297562041">297562041</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/coordinates-converter/id297562041?mt=8&uo=4">https://itunes.apple.com/us/app/coordinates-converter/id297562041?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Narut Sutakawatin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/masaka-inc./id297562044?uo=4">© MASAKA Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/df/44/64/df44647f-c8ea-99df-26c3-9a018cbad674/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21565023/07504276-ce93-11e6-8efd-820a084eb672.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21565023/07504276-ce93-11e6-8efd-820a084eb672.png)
https://cloud.githubusercontent.com/assets/2068130/21565023/07504276-ce93-11e6-8efd-820a084eb672.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21565026/1640c8fa-ce93-11e6-99f2-28f13bfd773a.png
