### ISSUE TITLE
Pass2U Wallet - Put cards into Apple Wallet

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8767]
**App Name:** Pass2U Wallet - Put cards into Apple Wallet
**Bundle ID:** net.pass2u.wallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1142473931">1142473931</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pass2u-wallet-put-cards-into/id1142473931?mt=8&uo=4">https://itunes.apple.com/us/app/pass2u-wallet-put-cards-into/id1142473931?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** MicroMacro Mobile Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/micromacro-mobile-inc./id471259807?uo=4">© MicroMacro Mobile Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple91/v4/35/3d/de/353dde3b-68e7-1c9b-6cf7-23d856a03fd1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21564245/93973b34-ce8b-11e6-9f08-d10b9dad6190.png)#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21564245/93973b34-ce8b-11e6-9f08-d10b9dad6190.png)
https://cloud.githubusercontent.com/assets/2068130/21564245/93973b34-ce8b-11e6-9f08-d10b9dad6190.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21564250/a03c6a26-ce8b-11e6-8d2a-da44e0dde841.png
