### ISSUE TITLE
TweeTopi - Powerful Search & Share for Twitter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8769]
**App Name:** TweeTopi - Powerful Search & Share for Twitter
**Bundle ID:** jp.co.itmedia.TweeTopi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=533346597">533346597</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tweetopi-powerful-search-share/id533346597?mt=8&uo=4">https://itunes.apple.com/us/app/tweetopi-powerful-search-share/id533346597?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** ITmedia Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/itmedia-inc./id397942451?uo=4">© ITmedia Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/6e/c5/68/6ec568a2-b527-c3e4-8bb0-5850dccb947c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21552831/96570caa-ce04-11e6-97a5-96d4a8df28ce.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21552831/96570caa-ce04-11e6-97a5-96d4a8df28ce.png)
https://cloud.githubusercontent.com/assets/2068130/21552831/96570caa-ce04-11e6-97a5-96d4a8df28ce.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21552835/a42694a4-ce04-11e6-94c2-f3894b1e3f98.png
