### ISSUE TITLE
Target WEIGHT for Adults (Personal Daily Weight Tracker & BMI)

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#877]
**App Name:** Target WEIGHT for Adults (Personal Daily Weight Tracker & BMI)
**Bundle ID:** com.TactioSoft.targetweight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338889966">338889966</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/target-weight-for-adults-personal/id338889966?mt=8&uo=4">https://itunes.apple.com/us/app/target-weight-for-adults-personal/id338889966?mt=8&uo=4</a>
**App Version:** 1.13.23
**Seller:** Tactio Software International Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tactio-health-group-inc./id338889969?uo=4>© Tactio Health Group Inc.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple2/v4/8f/c1/ef/8fc1efa5-4dd7-95c0-740e-ec5b2179d5b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19850199/80fd1f6a-9f57-11e6-8f5f-906f64601868.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19850199/80fd1f6a-9f57-11e6-8f5f-906f64601868.png)
https://cloud.githubusercontent.com/assets/20930745/19850199/80fd1f6a-9f57-11e6-8f5f-906f64601868.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19850214/9e4c6b98-9f57-11e6-8489-215b90308414.png
