### ISSUE TITLE
Sylfeed

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8770]
**App Name:** Sylfeed
**Bundle ID:** net.gacha.Sylfeed
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=403879490">403879490</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sylfeed/id403879490?mt=8&uo=4">https://itunes.apple.com/us/app/sylfeed/id403879490?mt=8&uo=4</a>
**App Version:** 3.6.1
**Seller:** GACHANET
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gachanet/id403879493?uo=4">© GACHANET</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/27/70/bc/2770bc0e-95e8-5ded-80f4-1a28e1a6a7be/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21553006/ff89349a-ce05-11e6-816a-b4e3b643ad4a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21553006/ff89349a-ce05-11e6-816a-b4e3b643ad4a.png)
https://cloud.githubusercontent.com/assets/2068130/21553006/ff89349a-ce05-11e6-816a-b4e3b643ad4a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21553023/0e4a9078-ce06-11e6-9f25-40680b9731f6.png
