### ISSUE TITLE
Aktia Wallet

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#8772]
**App Name:** Aktia Wallet
**Bundle ID:** com.aktia.wallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1154413529">1154413529</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/aktia-wallet/id1154413529?uo=4">https://apps.apple.com/us/app/aktia-wallet/id1154413529?uo=4</a>
**App Version:** 5.1.0
**Seller:** Aktia Bank Abp
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/aktia-bank-abp/id1100143566?uo=4">© Aktia Bank Abp</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/82/6b/71/826b718e-fd91-903b-1a31-50dde8da82ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979351-04ade500-95e7-11e9-9a64-32499de3105d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21577570/063bab78-cf60-11e6-993a-d52db7990e86.png)
https://cloud.githubusercontent.com/assets/2068130/21577570/063bab78-cf60-11e6-993a-d52db7990e86.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21577574/170f5472-cf60-11e6-8dd1-adba54bdf8d7.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979351-04ade500-95e7-11e9-9a64-32499de3105d.png)
https://user-images.githubusercontent.com/2068130/59979351-04ade500-95e7-11e9-9a64-32499de3105d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979354-14c5c480-95e7-11e9-9fe4-293919b49f49.png
