### ISSUE TITLE
Magic Guide for Disney World: Wait Times & Dining

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8774]
**App Name:** Magic Guide for Disney World: Wait Times & Dining
**Bundle ID:** com.versaedge.iphone.WDWMagicGuide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=365817457">365817457</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/magic-guide-for-disney-world/id365817457?mt=8&uo=4">https://itunes.apple.com/us/app/magic-guide-for-disney-world/id365817457?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** VersaEdge Software, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/versaedge-software-llc/id301294952?uo=4">© VersaEdge Software, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/7d/5f/88/7d5f88d0-cff3-3dc3-ed91-9f6c7d101985/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21753094/51a233e4-d5e5-11e6-94ad-e930dd2cf9a1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21753094/51a233e4-d5e5-11e6-94ad-e930dd2cf9a1.png)
https://cloud.githubusercontent.com/assets/2068130/21753094/51a233e4-d5e5-11e6-94ad-e930dd2cf9a1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21753096/5ed39904-d5e5-11e6-8e0d-d577e8cf8c61.png
😄
