### ISSUE TITLE
My Parking - Find Car Park

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8776]
**App Name:** My Parking - Find Car Park
**Bundle ID:** it.eRaff.MyParking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=995771836">995771836</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-parking-find-car-park/id995771836?mt=8&uo=4">https://itunes.apple.com/us/app/my-parking-find-car-park/id995771836?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Raffaele Di Marzo
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/raffaele-di-marzo/id667928946?uo=4">© Raffaele Di Marzo</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/20/93/c5/2093c5d4-86a7-263b-d96a-7a2f64defe55/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21616272/1fe22204-d1e1-11e6-80db-28f5e0e20889.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21616272/1fe22204-d1e1-11e6-80db-28f5e0e20889.png)
https://cloud.githubusercontent.com/assets/20930745/21616272/1fe22204-d1e1-11e6-80db-28f5e0e20889.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21616294/2c7ad880-d1e1-11e6-85be-2b4811ff6bd4.png
