### ISSUE TITLE
Busch Gardens Discovery Guide

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8777]
**App Name:** Busch Gardens Discovery Guide
**Bundle ID:** com.seaworld.BuschGardens
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=452815667">452815667</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/busch-gardens-discovery-guide/id452815667?mt=8&uo=4">https://itunes.apple.com/us/app/busch-gardens-discovery-guide/id452815667?mt=8&uo=4</a>
**App Version:** 5.10.7
**Seller:** SeaWorld Parks & Entertainment Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/seaworld-parks-entertainment/id393159818?uo=4">© SeaWorld Parks & Entertainment Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/99/9f/14/999f1444-aa6f-fa54-2670-6317044d0885/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21617724/c35402e4-d1e7-11e6-8eb0-9c6d7f7bbb8b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21617724/c35402e4-d1e7-11e6-8eb0-9c6d7f7bbb8b.png)
https://cloud.githubusercontent.com/assets/20930745/21617724/c35402e4-d1e7-11e6-8eb0-9c6d7f7bbb8b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21617742/d3eeb1e4-d1e7-11e6-9729-4c116a3e205b.png
