### ISSUE TITLE
Time Buddy - Visual World Clock & Time Converter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8778]
**App Name:** Time Buddy - Visual World Clock & Time Converter
**Bundle ID:** com.helloka.worldtimebuddy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=719765848">719765848</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/time-buddy-visual-world-clock/id719765848?mt=8&uo=4">https://itunes.apple.com/us/app/time-buddy-visual-world-clock/id719765848?mt=8&uo=4</a>
**App Version:** 1.19
**Seller:** HELLOKA, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/helloka/id718495372?uo=4">© Helloka</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/c8/0d/58/c80d5889-c73d-84e9-0201-8e76bd372111/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21726004/15e9ab3a-d43b-11e6-85fc-443e7afc74b2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21726004/15e9ab3a-d43b-11e6-85fc-443e7afc74b2.png)
https://cloud.githubusercontent.com/assets/20930745/21726004/15e9ab3a-d43b-11e6-85fc-443e7afc74b2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21726029/3846bb46-d43b-11e6-85f7-85fc2561d8d7.png
