### ISSUE TITLE
Teamup Calendar

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8779]
**App Name:** Teamup Calendar
**Bundle ID:** com.teamup.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1065897968">1065897968</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/teamup-calendar/id1065897968?mt=8&uo=4">https://itunes.apple.com/us/app/teamup-calendar/id1065897968?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** Teamup Solutions AG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/teamup-solutions-ag/id1065897967?uo=4">© Teamup Solutions AG</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/87/e9/4a/87e94af7-610d-d6b8-73ac-bc102a9a0279/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21649440/0bc4e876-d2a2-11e6-9b4b-6080224d4f00.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21649440/0bc4e876-d2a2-11e6-9b4b-6080224d4f00.png)
https://cloud.githubusercontent.com/assets/20930745/21649440/0bc4e876-d2a2-11e6-9b4b-6080224d4f00.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21649485/2a5304d0-d2a2-11e6-99cb-c4bfa8ce6a29.png
