### ISSUE TITLE
TrainingPeaks -Triathlon, Cycling, and Running App

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#878]
**App Name:** TrainingPeaks -Triathlon, Cycling, and Running App
**Bundle ID:** com.peaksware.trainingpeaks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=408047715">408047715</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trainingpeaks-triathlon-cycling/id408047715?mt=8&uo=4">https://itunes.apple.com/us/app/trainingpeaks-triathlon-cycling/id408047715?mt=8&uo=4</a>
**App Version:** 7.9
**Seller:** Peaksware, LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/peaksware-llc/id408047718?uo=4>© Peaksware, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/fc/d3/03/fcd30344-0895-6385-a5d0-1079fc51a24e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409828/42ebe6f6-92dd-11e6-9b8b-7544a172248c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409828/42ebe6f6-92dd-11e6-9b8b-7544a172248c.png)
https://cloud.githubusercontent.com/assets/20930745/19409828/42ebe6f6-92dd-11e6-9b8b-7544a172248c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409829/4f9ee3bc-92dd-11e6-86fc-a2231a1bb75e.png
