### ISSUE TITLE
Hill Climb Racing 2

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8781]
**App Name:** Hill Climb Racing 2
**Bundle ID:** com.fingersoft.hillclimbracing2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1146465836">1146465836</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hill-climb-racing-2/id1146465836?mt=8&uo=4">https://itunes.apple.com/us/app/hill-climb-racing-2/id1146465836?mt=8&uo=4</a>
**App Version:** 1.1.8
**Seller:** Fingersoft
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fingersoft/id514034278?uo=4">© Fingersoft</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/e3/ef/ee/e3efeedf-afaf-af2b-1711-5832bb05f86e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23152608/5499e0a2-f803-11e6-8779-32baa99f22ae.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23152608/5499e0a2-f803-11e6-8779-32baa99f22ae.png)
https://cloud.githubusercontent.com/assets/2068130/23152608/5499e0a2-f803-11e6-8779-32baa99f22ae.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23152620/651df36e-f803-11e6-848e-da580400c628.png
