### ISSUE TITLE
Taps to Riches

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8782]
**App Name:** Taps to Riches
**Bundle ID:** com.gamecircus.tycoon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1069160488">1069160488</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/taps-to-riches/id1069160488?mt=8&uo=4">https://itunes.apple.com/us/app/taps-to-riches/id1069160488?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Game Circus LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/game-circus-llc/id366761192?uo=4">© Game Circus LLC</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/b6/64/2a/b6642ac3-9d9b-ab7f-b368-582c436636a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23179254/8446e272-f86d-11e6-91a5-2a4a11372abd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23179254/8446e272-f86d-11e6-91a5-2a4a11372abd.png)
https://cloud.githubusercontent.com/assets/2068130/23179254/8446e272-f86d-11e6-91a5-2a4a11372abd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23179268/93a23352-f86d-11e6-9420-0f3b2aad41ca.png
❓
