### ISSUE TITLE
Tower Madness 2: #1 in Great Strategy TD Games

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8783]
**App Name:** Tower Madness 2: #1 in Great Strategy TD Games
**Bundle ID:** com.limbic.tm2-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=648977182">648977182</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tower-madness-2-1-in-great/id648977182?mt=8&uo=4">https://itunes.apple.com/us/app/tower-madness-2-1-in-great/id648977182?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Limbic Software, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/limbic-software/id316491621?uo=4">© Limbic Software</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/3a/9c/c6/3a9cc60b-17b8-4d28-92f3-32d7e7b1b8af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/23095409/d4b2f00e-f609-11e6-9db4-cfc6ebf5221e.png)

**Comment by Trubbel** [comment]
What about the [logo](https://cloud.githubusercontent.com/assets/10730122/23095407/d48cbb78-f609-11e6-9d7b-b57e78c995ee.png)?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/23095409/d4b2f00e-f609-11e6-9db4-cfc6ebf5221e.png)
https://cloud.githubusercontent.com/assets/10730122/23095409/d4b2f00e-f609-11e6-9db4-cfc6ebf5221e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/23095408/d4ace3a8-f609-11e6-93b2-6ecf07e2c924.png

**Comment by Gwai** [comment]
Would be okay if there is no chance to design the original icon.

**Comment by dreamnet** [comment]
Yup, no chance to do the original.
