### ISSUE TITLE
MMX Hill Climb — Off-Road Racing

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8784]
**App Name:** MMX Hill Climb — Off-Road Racing
**Bundle ID:** com.hutchgames.hillclimb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1057961675">1057961675</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mmx-hill-climb-off-road-racing/id1057961675?mt=8&uo=4">https://itunes.apple.com/us/app/mmx-hill-climb-off-road-racing/id1057961675?mt=8&uo=4</a>
**App Version:** 1.0.3871
**Seller:** Hutch Games Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hutch-games-ltd/id480956507?uo=4">© Hutch Games Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/bd/6b/c6/bd6bc621-e3a2-b8d9-cf9f-9b3fa8874030/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21649942/a9865990-d2a3-11e6-81ce-496ffce62666.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21649942/a9865990-d2a3-11e6-81ce-496ffce62666.png)
https://cloud.githubusercontent.com/assets/20930745/21649942/a9865990-d2a3-11e6-81ce-496ffce62666.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21649954/b49aa37c-d2a3-11e6-8b95-d2ea45b327c2.png
