### ISSUE TITLE
パズル＆ドラゴンズ

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#8785]
**App Name:** パズル＆ドラゴンズ
**Bundle ID:** jp.gungho.pad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493470467">493470467</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/jp/app/pazuru-doragonzu/id493470467?mt=8&uo=4">https://itunes.apple.com/jp/app/pazuru-doragonzu/id493470467?mt=8&uo=4</a>
**App Version:** 9.6.0
**Seller:** GungHo Online Entertainment, INC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/jp/developer/gungho-online-entertainment/id403963903?uo=4">© GungHo Online Entertainment, Inc.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/71/24/2a/71242a05-e414-7892-a2af-d09c0c22fa96/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22921804/6a59a6ec-f29b-11e6-82b3-ee5761659bfe.png)

**Comment by dreamnet** [comment]
Same as #8852.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22921804/6a59a6ec-f29b-11e6-82b3-ee5761659bfe.png)
https://cloud.githubusercontent.com/assets/2068130/22921804/6a59a6ec-f29b-11e6-82b3-ee5761659bfe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22921823/7986076e-f29b-11e6-8345-ebc46c20fea3.png
