### ISSUE TITLE
LUMINES パズル&ミュージック NEO

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#8786]
**App Name:** LUMINES パズル&ミュージック NEO
**Bundle ID:** com.mobcast.lpm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1146671383">1146671383</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/jp/app/lumines-pazuru-myujikku-neo/id1146671383?mt=8&uo=4">https://itunes.apple.com/jp/app/lumines-pazuru-myujikku-neo/id1146671383?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** mobcast inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/jp/developer/mobcast-inc./id309565868?uo=4">© mobcast inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/fd/b5/e2/fdb5e234-54b4-c258-f61b-51dc112202cf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22625594/ab3b6bca-eb9b-11e6-838e-1c7bdc717273.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22625594/ab3b6bca-eb9b-11e6-838e-1c7bdc717273.png)
https://cloud.githubusercontent.com/assets/20930745/22625594/ab3b6bca-eb9b-11e6-838e-1c7bdc717273.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22625601/cbdb0660-eb9b-11e6-92bb-acb6cf25f48a.png
