### ISSUE TITLE
Simeji - Japanese Keyboard with Emoticons

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#8787]
**App Name:** Simeji - Japanese Keyboard with Emoticons
**Bundle ID:** com.baidujp.Simeji
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=899997582">899997582</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/simeji-japanese-keyboard-emoticons/id899997582?mt=8&uo=4">https://itunes.apple.com/us/app/simeji-japanese-keyboard-emoticons/id899997582?mt=8&uo=4</a>
**App Version:** 5.7
**Seller:** Baidu Japan Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/baidu-japan-inc./id382165332?uo=4">© Baidu Japan Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/58/9a/97/589a975e-cd8e-d557-93dc-76605615c563/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21714977/159b3736-d402-11e6-9654-a9967b992592.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21714977/159b3736-d402-11e6-9654-a9967b992592.png)
https://cloud.githubusercontent.com/assets/20930745/21714977/159b3736-d402-11e6-9654-a9967b992592.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21714981/25303124-d402-11e6-922f-b495bd94b0cc.png
