### ISSUE TITLE
QRコードリーダー for iPhone - 無料で使えるQRコード読み取り用アプリ

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#8788]
**App Name:** QRコードリーダー for iPhone - 無料で使えるQRコード読み取り用アプリ
**Bundle ID:** com.anonymous-apps.QRCam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=794278407">794278407</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qrkodorida-for-iphone-wu-liaode/id794278407?mt=8&uo=4">https://itunes.apple.com/us/app/qrkodorida-for-iphone-wu-liaode/id794278407?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** YUTA MURAOKA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yuta-muraoka/id794278410?uo=4">© YUTA MURAOKA</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/a1/dd/45/a1dd45b7-9cca-8634-ce90-bebe16611e4d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21725042/faf7f5f6-d436-11e6-80b2-38d9c05eea14.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21725042/faf7f5f6-d436-11e6-80b2-38d9c05eea14.png)
https://cloud.githubusercontent.com/assets/20930745/21725042/faf7f5f6-d436-11e6-80b2-38d9c05eea14.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21725057/08b7b668-d437-11e6-8f9e-4fc128a82f6d.png
