### ISSUE TITLE
VIP Access for iPhone

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#8789]
**App Name:** VIP Access for iPhone
**Bundle ID:** com.verisign.mvip.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307658513">307658513</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vip-access-for-iphone/id307658513?mt=8&uo=4">https://itunes.apple.com/us/app/vip-access-for-iphone/id307658513?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** Symantec
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/symantec/id355033599?uo=4">© Symantec</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/ba/9d/ca/ba9dcac5-21d8-1c30-3e64-1c0848037a59/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21715458/e9b6d316-d404-11e6-816a-ca9f4f57f4dc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21715458/e9b6d316-d404-11e6-816a-ca9f4f57f4dc.png)
https://cloud.githubusercontent.com/assets/20930745/21715458/e9b6d316-d404-11e6-816a-ca9f4f57f4dc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21715469/f8b1c36c-d404-11e6-82a3-5745324a233c.png
