### ISSUE TITLE
Wahoo Utility

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#879]
**App Name:** Wahoo Utility
**Bundle ID:** com.WahooFitness.FisicaUtility
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=359225351">359225351</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wahoo-utility/id359225351?mt=8&uo=4">https://itunes.apple.com/us/app/wahoo-utility/id359225351?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Wahoo Fitness L.L.C.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wahoo-fitness/id359225354?uo=4>© Wahoo Fitness</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/55/bf/d0/55bfd018-a3ee-69f9-3074-69f2b68d383c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409948/3f71e1ee-92e0-11e6-87b7-34878c921920.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19409948/3f71e1ee-92e0-11e6-87b7-34878c921920.png)
https://cloud.githubusercontent.com/assets/20930745/19409948/3f71e1ee-92e0-11e6-87b7-34878c921920.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19409951/4d38642e-92e0-11e6-96a4-c38d12a9e234.png
