### ISSUE TITLE
Ace Attorney: Phoenix Wright Trilogy HD

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8790]
**App Name:** Ace Attorney: Phoenix Wright Trilogy HD
**Bundle ID:** jp.co.capcom.gyakusaisetus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=365681816">365681816</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ace-attorney-phoenix-wright/id365681816?mt=8&uo=4">https://itunes.apple.com/us/app/ace-attorney-phoenix-wright/id365681816?mt=8&uo=4</a>
**App Version:** 1.00.06
**Seller:** CAPCOM Co., Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/capcom/id308807391?uo=4">© CAPCOM</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/dd/91/d8/dd91d8e4-af4e-4e95-69b5-f6fa5c1721d1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23152169/73bc7c36-f800-11e6-8609-5ffd8001a448.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23152169/73bc7c36-f800-11e6-8609-5ffd8001a448.png)
https://cloud.githubusercontent.com/assets/2068130/23152169/73bc7c36-f800-11e6-8609-5ffd8001a448.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23152180/8486ae56-f800-11e6-8705-10554cde67f2.png
