### ISSUE TITLE
Mr.AahH!!

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8791]
**App Name:** Mr.AahH!!
**Bundle ID:** com.ponos.mraahh
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=326819173">326819173</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mr.aahh!!/id326819173?mt=8&uo=4">https://itunes.apple.com/us/app/mr.aahh!!/id326819173?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** ponos corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ponos/id297248421?uo=4">© PONOS</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple/v4/09/83/2e/09832e50-03ae-4ccf-b506-11858e535f7b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22625751/26196d9a-eb9e-11e6-8f9d-5f94b2281fb1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22625751/26196d9a-eb9e-11e6-8f9d-5f94b2281fb1.png)
https://cloud.githubusercontent.com/assets/20930745/22625751/26196d9a-eb9e-11e6-8f9d-5f94b2281fb1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22625755/35d47450-eb9e-11e6-96fe-29483b7f40fe.png
