### ISSUE TITLE
Pix'n Love Rush

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8792]
**App Name:** Pix'n Love Rush
**Bundle ID:** com.bulkypix.pixnloverush
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=373962521">373962521</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pixn-love-rush/id373962521?mt=8&uo=4">https://itunes.apple.com/us/app/pixn-love-rush/id373962521?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** BULKYPIX
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bulkypix/id304521749?uo=4">© Bulkypix</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/99/28/94/992894a6-1180-6f84-dc15-c3e8e18c95bb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21724822/25464dd6-d436-11e6-8f0b-91b57795528c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21724822/25464dd6-d436-11e6-8f0b-91b57795528c.png)
https://cloud.githubusercontent.com/assets/20930745/21724822/25464dd6-d436-11e6-8f0b-91b57795528c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21724844/34828d14-d436-11e6-973e-22a399f475ba.png
