### ISSUE TITLE
SmartGo Player

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8793]
**App Name:** SmartGo Player
**Bundle ID:** B4E8E4Q2PL
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=314506629">314506629</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartgo-player/id314506629?mt=8&uo=4">https://itunes.apple.com/us/app/smartgo-player/id314506629?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** Smart Go, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/smart-go-inc./id290948289?uo=4">© Smart Go, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple19/v4/39/c0/0f/39c00f95-bad4-af2d-c7ac-b570a92681c8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23131132/35af9332-f789-11e6-8d85-d84aac50478f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23131132/35af9332-f789-11e6-8d85-d84aac50478f.png)
https://cloud.githubusercontent.com/assets/2068130/23131132/35af9332-f789-11e6-8d85-d84aac50478f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23131146/46228e7c-f789-11e6-8ffb-cd9dd754d1ec.png
