### ISSUE TITLE
Hook Worlds

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8794]
**App Name:** Hook Worlds
**Bundle ID:** com.rocketcat.HookWorld
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407526767">407526767</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hook-worlds/id407526767?mt=8&uo=4">https://itunes.apple.com/us/app/hook-worlds/id407526767?mt=8&uo=4</a>
**App Version:** 1.20
**Seller:** Rocketcat LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rocketcat-llc/id305576988?uo=4">© Rocketcat LLC</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/e9/b7/84/e9b784c8-2b1a-432c-8561-f047a6fa0eeb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/23365732/bc7e0a52-fcc9-11e6-9cf1-a8ee7489dc6c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/23365732/bc7e0a52-fcc9-11e6-9cf1-a8ee7489dc6c.png)
https://cloud.githubusercontent.com/assets/3090247/23365732/bc7e0a52-fcc9-11e6-9cf1-a8ee7489dc6c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/23365731/bc594370-fcc9-11e6-8bfb-d8de9e882a6d.png

**Comment by dreamnet** [comment]
@ivanov007 👍
