### ISSUE TITLE
Wayward Souls

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8795]
**App Name:** Wayward Souls
**Bundle ID:** com.rocketcat.WaywardSouls
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=857555369">857555369</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wayward-souls/id857555369?mt=8&uo=4">https://itunes.apple.com/us/app/wayward-souls/id857555369?mt=8&uo=4</a>
**App Version:** 1.34
**Seller:** Rocketcat LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rocketcat-llc/id305576988?uo=4">© Rocketcat LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/86/94/43/86944326-0e25-d62f-b2a2-111dec81a30b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25065469/e367ee3c-2210-11e7-8683-2d9e72c277e5.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25065469/e367ee3c-2210-11e7-8683-2d9e72c277e5.png)
https://cloud.githubusercontent.com/assets/2068130/25065469/e367ee3c-2210-11e7-8683-2d9e72c277e5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25065474/f232239c-2210-11e7-9bed-aee719b2ec69.png
❓
