### ISSUE TITLE
Mage Gauntlet

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8796]
**App Name:** Mage Gauntlet
**Bundle ID:** com.rocketcat.MageGauntlet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=460697573">460697573</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mage-gauntlet/id460697573?mt=8&uo=4">https://itunes.apple.com/us/app/mage-gauntlet/id460697573?mt=8&uo=4</a>
**App Version:** 1.32
**Seller:** Rocketcat LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rocketcat-llc/id305576988?uo=4">© Rocketcat LLC</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/1a/82/55/1a8255a2-c5f9-4df4-350b-ea9debc9bb5e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23136356/a5d00346-f79c-11e6-9b8e-e2689dd69b03.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23136356/a5d00346-f79c-11e6-9b8e-e2689dd69b03.png)
https://cloud.githubusercontent.com/assets/2068130/23136356/a5d00346-f79c-11e6-9b8e-e2689dd69b03.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23136369/b6ff63fa-f79c-11e6-9d1a-23cb9308124f.png
❓
