### ISSUE TITLE
circuit_strike.one

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8797]
**App Name:** circuit_strike.one
**Bundle ID:** com.chillingo.csone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=313665457">313665457</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/circuit-strike.one/id313665457?mt=8&uo=4">https://itunes.apple.com/us/app/circuit-strike.one/id313665457?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** h.grenade games
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/h.grenade/id355821824?uo=4">© h.grenade</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple41/v4/da/7d/de/da7dde3f-a911-0da9-0fee-0bbb93f46df2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21752559/c6d4cbf0-d5da-11e6-9edb-f38734467e10.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21752559/c6d4cbf0-d5da-11e6-9edb-f38734467e10.png)
https://cloud.githubusercontent.com/assets/2068130/21752559/c6d4cbf0-d5da-11e6-9edb-f38734467e10.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21752564/d6d22cf0-d5da-11e6-9333-9995b55450da.png
