### ISSUE TITLE
Dropship

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8798]
**App Name:** Dropship
**Bundle ID:** com.ngmoco.Dropship
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=299427316">299427316</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dropship/id299427316?mt=8&uo=4">https://itunes.apple.com/us/app/dropship/id299427316?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** ngmoco, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewArtist?id=293559501">ngmoco, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://a744.phobos.apple.com/us/r30/Purple/v4/31/33/5f/31335f2f-6290-4fc6-1de6-acf356440313/icon1024x1024.jpeg" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22991651/4f30b932-f3bd-11e6-8e4a-5e6aa797a1a9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22991651/4f30b932-f3bd-11e6-8e4a-5e6aa797a1a9.png)
https://cloud.githubusercontent.com/assets/2068130/22991651/4f30b932-f3bd-11e6-8e4a-5e6aa797a1a9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22991662/5d2e6548-f3bd-11e6-8a87-e31582acffb6.png
