### ISSUE TITLE
Space Out

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8799]
**App Name:** Space Out
**Bundle ID:** com.binarysquare.SpaceOut
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=285915267">285915267</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/space-out/id285915267?mt=8&uo=4">https://itunes.apple.com/us/app/space-out/id285915267?mt=8&uo=4</a>
**App Version:** 3.4.3
**Seller:** Kranky Robot, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kranky-robot/id937983638?uo=4">© Kranky Robot</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/e0/72/d2/e072d266-dfd5-1223-892e-f8f9b8c223fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21715741/88716f38-d406-11e6-9b9f-e9d9cbcc572b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21715741/88716f38-d406-11e6-9b9f-e9d9cbcc572b.png)
https://cloud.githubusercontent.com/assets/20930745/21715741/88716f38-d406-11e6-9b9f-e9d9cbcc572b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21715750/9317d5b2-d406-11e6-85c9-1864b1c5397c.png
