### ISSUE TITLE
Vector Ball 3D

### ISSUE THREAD

**Issue by MenaceInc** [glasklart/hd#8800]
**App Name:** Vector Ball 3D
**Bundle ID:** com.gyrocade.VectorBallUltimate
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=581417149">581417149</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vector-ball-3d/id581417149?mt=8&uo=4">https://itunes.apple.com/us/app/vector-ball-3d/id581417149?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Webspire, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gyrocade/id285465870?uo=4">© Gyrocade</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/ce/92/f3/ce92f37f-50b2-4e06-ba64-ccaeab681dc8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23314844/e21a4d00-fac3-11e6-97e7-22ebef029f8d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23314844/e21a4d00-fac3-11e6-97e7-22ebef029f8d.png)
https://cloud.githubusercontent.com/assets/2068130/23314844/e21a4d00-fac3-11e6-97e7-22ebef029f8d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23314858/f061e364-fac3-11e6-9883-2ed24a6cc17f.png
