### ISSUE TITLE
WatchWeb - The Web Browser for your Apple Watch

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8801]
**App Name:** WatchWeb - The Web Browser for your Apple Watch
**Bundle ID:** com.ConiferApps.WatchWeb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1003528220">1003528220</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watchweb-web-browser-for-your/id1003528220?mt=8&uo=4">https://itunes.apple.com/us/app/watchweb-web-browser-for-your/id1003528220?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Warren Wulff
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/warren-wulff/id735607888?uo=4">© Warren Wulff</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/25/93/69/2593698d-60b2-7707-2863-6f82830a95c5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21752270/a3536cf4-d5d5-11e6-8ab7-7e8a86600582.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21752270/a3536cf4-d5d5-11e6-8ab7-7e8a86600582.png)
https://cloud.githubusercontent.com/assets/2068130/21752270/a3536cf4-d5d5-11e6-8ab7-7e8a86600582.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21752284/b12f0a54-d5d5-11e6-90b4-1f763cd7e180.png
