### ISSUE TITLE
Sportlobster - Fuel Your Passion For Sport

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8802]
**App Name:** Sportlobster - Fuel Your Passion For Sport
**Bundle ID:** com.sportlobster.Sportlobster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=726335461">726335461</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sportlobster-fuel-your-passion/id726335461?mt=8&uo=4">https://itunes.apple.com/us/app/sportlobster-fuel-your-passion/id726335461?mt=8&uo=4</a>
**App Version:** 5.12.0
**Seller:** Lobster Media Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sportlobster-ltd./id726335464?uo=4">© Sportlobster Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/42/80/e0/4280e0cd-44be-2df4-cac3-2ab2e5d9e6c0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21752188/666cf68a-d5d4-11e6-8cbf-589331d97a83.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21752188/666cf68a-d5d4-11e6-8cbf-589331d97a83.png)
https://cloud.githubusercontent.com/assets/2068130/21752188/666cf68a-d5d4-11e6-8cbf-589331d97a83.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21752197/742da418-d5d4-11e6-9990-f62cda2a70bb.png
