### ISSUE TITLE
SportScoop

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8803]
**App Name:** SportScoop
**Bundle ID:** com.coseur.sportscoop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035164619">1035164619</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sportscoop/id1035164619?mt=8&uo=4">https://itunes.apple.com/us/app/sportscoop/id1035164619?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Coseur LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/coseur-llc/id1035164618?uo=4">© Coseur LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple20/v4/5f/10/cf/5f10cf34-bc20-6179-1b9b-fa206ae407c8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21817022/a5a121ca-d762-11e6-809d-4f2b54917b26.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21817022/a5a121ca-d762-11e6-809d-4f2b54917b26.png)
https://cloud.githubusercontent.com/assets/20930745/21817022/a5a121ca-d762-11e6-809d-4f2b54917b26.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21817070/cc5a92a6-d762-11e6-95fd-8393f7cfe3de.png
