### ISSUE TITLE
ROBLOX

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8804]
**App Name:** ROBLOX
**Bundle ID:** com.roblox.robloxmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431946152">431946152</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/roblox/id431946152?mt=8&uo=4">https://itunes.apple.com/us/app/roblox/id431946152?mt=8&uo=4</a>
**App Version:** 2.318.168780
**Seller:** Roblox Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/roblox-corporation/id431946155?uo=4">© Roblox Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/35/ae/18/35ae18dc-bc0e-7be3-9d17-b18b036d35fb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34357177-16e254ee-ea45-11e7-8725-98a203da8e51.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22154763/18c81a7e-df2d-11e6-819a-16aef3ed951a.png)
https://cloud.githubusercontent.com/assets/20930745/22154763/18c81a7e-df2d-11e6-819a-16aef3ed951a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22154771/238a07ce-df2d-11e6-803f-e7b9d683165a.png

**Comment by Christian9901** [comment]
Hey, can someone update this with the new logo? Thanks

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34357177-16e254ee-ea45-11e7-8725-98a203da8e51.png)
https://user-images.githubusercontent.com/20930745/34357177-16e254ee-ea45-11e7-8725-98a203da8e51.png

Source:
https://user-images.githubusercontent.com/20930745/34357181-290d54f2-ea45-11e7-835e-a3a0e19c2045.png

**Comment by Christian9901** [comment]
Thanks!
