### ISSUE TITLE
Angry Birds Blast

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8805]
**App Name:** Angry Birds Blast
**Bundle ID:** com.rovio.blast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1122444037">1122444037</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/angry-birds-blast/id1122444037?mt=8&uo=4">https://itunes.apple.com/us/app/angry-birds-blast/id1122444037?mt=8&uo=4</a>
**App Version:** 1.2.5
**Seller:** Rovio Entertainment Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rovio-entertainment-ltd/id298910979?uo=4">© Rovio Entertainment Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/98/8b/7e/988b7e3e-9e23-6e8d-3e28-db70321c73c8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22994764/64cc0e30-f3c8-11e6-8e38-25d144afc317.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22994764/64cc0e30-f3c8-11e6-8e38-25d144afc317.png)
https://cloud.githubusercontent.com/assets/2068130/22994764/64cc0e30-f3c8-11e6-8e38-25d144afc317.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22994783/73a96434-f3c8-11e6-9148-168bbd35137d.png
