### ISSUE TITLE
Weather Gods

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8806]
**App Name:** Weather Gods
**Bundle ID:** com.meyume.WeatherGods
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1041512978">1041512978</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-gods/id1041512978?mt=8&uo=4">https://itunes.apple.com/us/app/weather-gods/id1041512978?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** MEYUME LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/meyume-ltd/id834440552?uo=4">© Meyume Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/0b/38/9b/0b389bb5-cb53-4774-de4b-3a493a454684/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21816626/06c010da-d761-11e6-9ff2-aa5066e93a10.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21816626/06c010da-d761-11e6-9ff2-aa5066e93a10.png)
https://cloud.githubusercontent.com/assets/20930745/21816626/06c010da-d761-11e6-9ff2-aa5066e93a10.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21816659/309222c2-d761-11e6-93e2-7671f71b668d.png
