### ISSUE TITLE
VRPlayer : 2D & 3D & 360° Video Player for VR

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8807]
**App Name:** VRPlayer : 2D & 3D & 360° Video Player for VR
**Bundle ID:** com.mobixn.vrplayer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1058724046">1058724046</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vrplayer-2d-3d-360-video-player/id1058724046?mt=8&uo=4">https://itunes.apple.com/us/app/vrplayer-2d-3d-360-video-player/id1058724046?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** LEE DONG WON
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lee-dong-won/id666182402?uo=4">© LEE DONG WON</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/d6/61/51/d6615174-b7bc-c040-c49a-dc68aec7bb1f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21815619/a0eddfb0-d75d-11e6-8f73-897caa154173.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21815619/a0eddfb0-d75d-11e6-8f73-897caa154173.png)
https://cloud.githubusercontent.com/assets/20930745/21815619/a0eddfb0-d75d-11e6-8f73-897caa154173.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21815629/ac2870de-d75d-11e6-80f0-c9fc9120c199.png
