### ISSUE TITLE
AnkiMobile Flashcards

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#8809]
**App Name:** AnkiMobile Flashcards
**Bundle ID:** net.ichi2.anki
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=373493387">373493387</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ankimobile-flashcards/id373493387?mt=8&uo=4">https://itunes.apple.com/us/app/ankimobile-flashcards/id373493387?mt=8&uo=4</a>
**App Version:** 2.0.27
**Seller:** Ankitects Pty Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ankitects-pty-ltd/id373493390?uo=4">© Ankitects Pty Ltd</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/5d/da/58/5dda5804-5b5a-7931-1ecd-dc61b96c8555/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21814816/d7d17ecc-d75a-11e6-9e6a-0af1a1d10c3c.png)

**Comment by jmaeshawn** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/6907886/21792155/94df93b0-d69c-11e6-880c-ae1a5bc9bed8.png)

Source:
https://cloud.githubusercontent.com/assets/6907886/21792146/84722bc8-d69c-11e6-85f8-c2c707e8068b.png

**Comment by ivanov007** [comment]
I think it will look better without the frame

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/21814816/d7d17ecc-d75a-11e6-9e6a-0af1a1d10c3c.png)
https://cloud.githubusercontent.com/assets/20930745/21814816/d7d17ecc-d75a-11e6-9e6a-0af1a1d10c3c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/21814828/e570888e-d75a-11e6-9b79-c8b7771bb2da.png
