### ISSUE TITLE
Jungle - Video Downloader

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#8810]
**App Name:** Jungle - Video Downloader
**Bundle ID:** com.kobisnir.Jungle
**Version:** 2.0
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/3600371/21901428/5bae62d6-d900-11e6-8f8f-257bdbeb68ca.png" width="180" height="180">
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22037449/773ed3aa-dcf7-11e6-9c8a-0a6d883cd31b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22037449/773ed3aa-dcf7-11e6-9c8a-0a6d883cd31b.png)
https://cloud.githubusercontent.com/assets/2068130/22037449/773ed3aa-dcf7-11e6-9c8a-0a6d883cd31b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22037465/84887eee-dcf7-11e6-8704-148890c251d9.png

**Comment by nekholm** [comment]
Just noticed it's Jungle with a capital J, so the bundle ID should be `com.kobisnir.Jungle`.
