### ISSUE TITLE
Feedlix

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8811]
**App Name:** Feedlix
**Bundle ID:** com.appeloper.channels
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1063166549">1063166549</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/feedlix/id1063166549?mt=8&uo=4">https://itunes.apple.com/us/app/feedlix/id1063166549?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** Elsa Mourato
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/elsa-mourato/id534256803?uo=4">© Elsa Mourato</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple30/v4/ee/30/40/ee3040f7-0ced-69e5-bcca-c6476edf52e9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22036671/9b915398-dcf4-11e6-8798-885ba4eb0f7c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22036671/9b915398-dcf4-11e6-8798-885ba4eb0f7c.png)
https://cloud.githubusercontent.com/assets/2068130/22036671/9b915398-dcf4-11e6-8798-885ba4eb0f7c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22036696/ab40733c-dcf4-11e6-9eb6-7dd0eec1726e.png
