### ISSUE TITLE
Actions - Fast forward everyday tasks

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8812]
**App Name:** Actions - Fast forward everyday tasks
**Bundle ID:** com.supertecnoboff.qckacs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=993488068">993488068</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/actions-fast-forward-everyday/id993488068?mt=8&uo=4">https://itunes.apple.com/us/app/actions-fast-forward-everyday/id993488068?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Daniel Sadjadian
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/daniel-sadjadian/id866781649?uo=4">© Daniel Sadjadian</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/b8/f8/42/b8f84299-6682-2220-ef9f-655a31a76af0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21954924/ad0ecf5c-da5f-11e6-9403-b6b9905abd16.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21954924/ad0ecf5c-da5f-11e6-9403-b6b9905abd16.png)
https://cloud.githubusercontent.com/assets/2068130/21954924/ad0ecf5c-da5f-11e6-9403-b6b9905abd16.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21954926/b9eec1f0-da5f-11e6-8253-a2b3b54a6c18.png
