### ISSUE TITLE
iMark · Image Annotation Tool

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8813]
**App Name:** iMark · Image Annotation Tool
**Bundle ID:** com.chii.imark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1174741369">1174741369</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/imark-image-annotation-tool/id1174741369?mt=8&uo=4">https://itunes.apple.com/us/app/imark-image-annotation-tool/id1174741369?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Yiming Shen
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yiming-shen/id364264742?uo=4">© Yiming Shen</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/72/1f/8e/721f8ee2-5885-4856-607b-588dbc82d0f3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22154478/fe0f95be-df2b-11e6-94e4-f0a9d1e92277.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22154478/fe0f95be-df2b-11e6-94e4-f0a9d1e92277.png)
https://cloud.githubusercontent.com/assets/20930745/22154478/fe0f95be-df2b-11e6-94e4-f0a9d1e92277.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22154491/0f249ca0-df2c-11e6-8ff8-5385aa79ffa1.png
