### ISSUE TITLE
PDF Viewer - Read, Review, and Annotate

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8814]
**App Name:** PDF Viewer - Read, Review, and Annotate
**Bundle ID:** com.pspdfkit.viewer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1120099014">1120099014</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pdf-viewer-read-review-annotate/id1120099014?mt=8&uo=4">https://itunes.apple.com/us/app/pdf-viewer-read-review-annotate/id1120099014?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** PSPDFKit GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pspdfkit-gmbh/id966931428?uo=4">© PSPDFKit GmbH</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/4f/12/1d/4f121d17-98a8-7283-16ea-72e77686b4d2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/22030720/228af0f8-dca4-11e6-86d6-d82f51ca7de5.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/22030552/8cf55240-dca3-11e6-9754-629acc2cdea8.png)
https://cloud.githubusercontent.com/assets/3090247/22030552/8cf55240-dca3-11e6-9754-629acc2cdea8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/22030553/8cfc5932-dca3-11e6-8450-1dd38adfd699.png
