### ISSUE TITLE
Top Story: breaking news of local and the world

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8815]
**App Name:** Top Story: breaking news of local and the world
**Bundle ID:** io.topstory.news.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=993549323">993549323</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/top-story-breaking-news-local/id993549323?mt=8&uo=4">https://itunes.apple.com/us/app/top-story-breaking-news-local/id993549323?mt=8&uo=4</a>
**App Version:** 2.41
**Seller:** MOBOTAP INC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mobotap-inc./id433626481?uo=4">© MoboTap Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/10/67/1e/10671eb0-8d70-dd52-6405-49c9a44e08d2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22036110/a822352a-dcf2-11e6-962e-a491a20c8085.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22036110/a822352a-dcf2-11e6-962e-a491a20c8085.png)
https://cloud.githubusercontent.com/assets/2068130/22036110/a822352a-dcf2-11e6-962e-a491a20c8085.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22036125/b749c644-dcf2-11e6-9f08-5dda8132a3d6.png
