### ISSUE TITLE
名探偵コナン公式アプリ -無料で毎日漫画が読める-

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#8816]
**App Name:** 名探偵コナン公式アプリ -無料で毎日漫画が読める-
**Bundle ID:** jp.co.shogakukan.conanportal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1071044561">1071044561</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/jp/app/ming-tan-zhenkonan-gong-shiapuri/id1071044561?mt=8&uo=4">https://itunes.apple.com/jp/app/ming-tan-zhenkonan-gong-shiapuri/id1071044561?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** SHOGAKUKAN INC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/jp/developer/shogakukan-inc./id297431334?uo=4">© SHOGAKUKAN INC.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/c2/5e/ec/c25eec3f-00b5-0089-fefe-209168632825/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22995847/c100d8bc-f3cc-11e6-88b2-e03aafcf6189.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22995847/c100d8bc-f3cc-11e6-88b2-e03aafcf6189.png)
https://cloud.githubusercontent.com/assets/2068130/22995847/c100d8bc-f3cc-11e6-88b2-e03aafcf6189.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22995861/d02e2df8-f3cc-11e6-9b76-4b38389e79a4.png
