### ISSUE TITLE
CARROT Weather Free - Powered by Dark Sky

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8820]
**App Name:** CARROT Weather Free - Powered by Dark Sky
**Bundle ID:** com.grailr.CARROTweatherFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1194070905">1194070905</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/carrot-weather-free-powered/id1194070905?mt=8&uo=4">https://itunes.apple.com/us/app/carrot-weather-free-powered/id1194070905?mt=8&uo=4</a>
**App Version:** 3.1.2
**Seller:** Grailr LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/grailr-llc/id556706923?uo=4">© Grailr LLC</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/c3/d4/c9/c3d4c9e8-4b4f-3878-d533-655a76a6fff4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22216628/2616d8f8-e1a0-11e6-88bd-973c62fb1ba8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22215948/6a336bda-e19d-11e6-910b-f0adda85eb58.png)
https://cloud.githubusercontent.com/assets/20930745/22215948/6a336bda-e19d-11e6-910b-f0adda85eb58.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22215963/785adac2-e19d-11e6-8bf6-9c7e7744fec2.png

**Comment by Trubbel** [comment]
@2Qt2beStr8 I like the first one, however are you able to fix those zeroes?

**Comment by 2Qt2beStr8** [comment]
yes i can :-) 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22216628/2616d8f8-e1a0-11e6-88bd-973c62fb1ba8.png)
https://cloud.githubusercontent.com/assets/20930745/22216628/2616d8f8-e1a0-11e6-88bd-973c62fb1ba8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22216667/4373cb68-e1a0-11e6-86a5-54d687b95ec8.png

**Comment by Trubbel** [comment]
I like it, what do you think, @l8er4now?

**Comment by l8er4now** [comment]
Yep, looks good to me.

**Comment by jbmagination** [comment]
Hey there! Would love to know if you still have this app somewhere / if you're maybe able to get an IPA? I'd greatly appreciate it :)
