### ISSUE TITLE
Check Reviews

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8821]
**App Name:** Check Reviews
**Bundle ID:** com.lanorkin.reviews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=974973099">974973099</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/check-reviews/id974973099?mt=8&uo=4">https://itunes.apple.com/us/app/check-reviews/id974973099?mt=8&uo=4</a>
**App Version:** 1.01
**Seller:** Vladimir Vedeneev
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vladimir-vedeneev/id889004894?uo=4">© Vladimir Vedeneev</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/6e/6e/96/6e6e962f-4cc1-adfd-3a5c-0b7737b4ecc4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22153838/43a99e88-df29-11e6-84af-275c0d411931.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22153838/43a99e88-df29-11e6-84af-275c0d411931.png)
https://cloud.githubusercontent.com/assets/20930745/22153838/43a99e88-df29-11e6-84af-275c0d411931.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22153851/509d49c8-df29-11e6-92b4-a9510179030f.png
