### ISSUE TITLE
MEDION LifeStream II

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8822]
**App Name:** MEDION LifeStream II
**Bundle ID:** com.medion.lifestreamv2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1053393241">1053393241</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/medion-lifestream-ii/id1053393241?mt=8&uo=4">https://itunes.apple.com/us/app/medion-lifestream-ii/id1053393241?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** MEDION AG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/medion/id447112577?uo=4">© MEDION</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/2c/36/2d/2c362d81-4ea4-a2dc-14ba-a7301f1ffa3c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22153693/9e6942ca-df28-11e6-9c08-4538ef3cadc6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22153693/9e6942ca-df28-11e6-9c08-4538ef3cadc6.png)
https://cloud.githubusercontent.com/assets/20930745/22153693/9e6942ca-df28-11e6-9c08-4538ef3cadc6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22153705/aac5bb3e-df28-11e6-9d0a-5edd4e5f8a32.png
