### ISSUE TITLE
Advisory Weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8823]
**App Name:** Advisory Weather
**Bundle ID:** com.tenback.AdvisoryWeather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1132501743">1132501743</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/advisory-weather/id1132501743?mt=8&uo=4">https://itunes.apple.com/us/app/advisory-weather/id1132501743?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Marco Tenback
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marco-tenback/id417771492?uo=4">© Marco Tenback</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/be/5d/bd/be5dbdbd-0276-e208-87fd-e1926086ccca/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22215433/aaf12a10-e19b-11e6-85f0-fa300dab8a69.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22215433/aaf12a10-e19b-11e6-85f0-fa300dab8a69.png)
https://cloud.githubusercontent.com/assets/20930745/22215433/aaf12a10-e19b-11e6-85f0-fa300dab8a69.png)


Source:
https://cloud.githubusercontent.com/assets/20930745/22215445/b53aa5fa-e19b-11e6-8a68-f57097643505.png
