### ISSUE TITLE
Reverse Image Search Free

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8824]
**App Name:** Reverse Image Search Free
**Bundle ID:** com.ipopapp.imagesearchfree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1003144513">1003144513</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reverse-image-search-free/id1003144513?mt=8&uo=4">https://itunes.apple.com/us/app/reverse-image-search-free/id1003144513?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Yajing Qian
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yajing-qian/id566517066?uo=4">© Yajing Qian</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/bd/cb/b0/bdcbb065-4c03-4a7e-2289-6cdb2f003f0f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22215250/f0e055a6-e19a-11e6-81f4-82bc45302289.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22215250/f0e055a6-e19a-11e6-81f4-82bc45302289.png)
https://cloud.githubusercontent.com/assets/20930745/22215250/f0e055a6-e19a-11e6-81f4-82bc45302289.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22215266/fd5c3a3e-e19a-11e6-8753-12aeb01f2637.png
