### ISSUE TITLE
Pizza-online.fi

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#8825]
**App Name:** Pizza-online.fi
**Bundle ID:** com.slm.po
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=703574232">703574232</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pizza-online.fi/id703574232?mt=8&uo=4">https://itunes.apple.com/us/app/pizza-online.fi/id703574232?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** SLM Finland Oy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/slm-finland-oy/id554919293?uo=4">© SLM Finland Oy</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple19/v4/38/7d/75/387d7550-518e-4001-39c0-6fe7d96f1680/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22926814/8b098318-f2ae-11e6-9430-bddb93a16036.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22926814/8b098318-f2ae-11e6-9430-bddb93a16036.png)
https://cloud.githubusercontent.com/assets/2068130/22926814/8b098318-f2ae-11e6-9430-bddb93a16036.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22926838/9c6ed7fc-f2ae-11e6-9ee2-0d97873f3de7.png
