### ISSUE TITLE
Space War HD

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8826]
**App Name:** Space War HD
**Bundle ID:** com.virtualgs.spacewarhd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=363486833">363486833</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/space-war-hd/id363486833?mt=8&uo=4">https://itunes.apple.com/us/app/space-war-hd/id363486833?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** Thye Chean Lim
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/virtual-gs/id302652687?uo=4">© Virtual GS</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/54/32/5f/54325f58-9abc-7de7-ce4c-658d3c8fee8d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25780953/2335bbac-3332-11e7-9237-121dc19ef712.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25780953/2335bbac-3332-11e7-9237-121dc19ef712.png)
https://cloud.githubusercontent.com/assets/20930745/25780953/2335bbac-3332-11e7-9237-121dc19ef712.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25780957/37e29a48-3332-11e7-8246-88f465bafa5b.png
