### ISSUE TITLE
Smartisan Calendar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8827]
**App Name:** Smartisan Calendar
**Bundle ID:** com.smartisan.calendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944154964">944154964</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartisan-calendar/id944154964?mt=8&uo=4">https://itunes.apple.com/us/app/smartisan-calendar/id944154964?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Smartisan Technology Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/smartisan-technology-co.-ltd./id828812914?uo=4">© Smartisan Technology Co., Ltd.</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple49/v4/c7/05/8a/c7058a78-2de0-4487-1bf6-6bab6edeee10/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618779/f14048fe-eae5-11e6-8155-8d93510c3141.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618779/f14048fe-eae5-11e6-8155-8d93510c3141.png)
https://cloud.githubusercontent.com/assets/20930745/22618779/f14048fe-eae5-11e6-8155-8d93510c3141.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618781/fd8b4d7a-eae5-11e6-997f-225d83e3eef3.png
