### ISSUE TITLE
Smartisan Notes

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8828]
**App Name:** Smartisan Notes
**Bundle ID:** com.smartisan.notes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=867934588">867934588</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartisan-notes/id867934588?mt=8&uo=4">https://itunes.apple.com/us/app/smartisan-notes/id867934588?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Smartisan Technology Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/smartisan-technology-co.-ltd./id828812914?uo=4">© Smartisan Technology Co., Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/de/d7/8c/ded78cee-36db-9d21-743b-47c85652df84/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22861074/0ad2753c-f110-11e6-9425-fed77f47795b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22861074/0ad2753c-f110-11e6-9425-fed77f47795b.png)
https://cloud.githubusercontent.com/assets/2068130/22861074/0ad2753c-f110-11e6-9425-fed77f47795b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22861075/1c813cb4-f110-11e6-82a4-b4f98ef30d0e.png
