### ISSUE TITLE
CaloryGuard Pro - Track calories, lose weight

### ISSUE THREAD

**Issue by jerok** [glasklart/hd#8829]
**App Name:** CaloryGuard Pro - Track calories, lose weight
**Bundle ID:** de.bluebamboo.CaloryGuardPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=502778111">502778111</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/caloryguard-pro-track-calories/id502778111?mt=8&uo=4">https://itunes.apple.com/us/app/caloryguard-pro-track-calories/id502778111?mt=8&uo=4</a>
**App Version:** 3.92.0
**Seller:** Falko Buttler
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bluebamboo.de-falko-buttler/id285599850?uo=4">© BlueBamboo.de Falko Buttler</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/b7/b2/24/b7b224d3-33fa-6ae8-36f3-ce15ebdab435/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22918900/147ec9b8-f28d-11e6-95f2-fef597d9dfb3.png)

**Comment by jerok** [comment]
- Icon-request -

**Comment by jerok** [comment]
„CaloryGuard Pro - Kalorien überwachen & abnehmen“ von BlueBamboo.de Falko Buttler
https://appsto.re/de/_J89D.i

**Comment by Trubbel** [comment]
@jerok Please follow this guide on how to submit an icon request.
https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22918900/147ec9b8-f28d-11e6-95f2-fef597d9dfb3.png)
https://cloud.githubusercontent.com/assets/2068130/22918900/147ec9b8-f28d-11e6-95f2-fef597d9dfb3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22918910/24950560-f28d-11e6-97a0-f7487d99e35e.png
