### ISSUE TITLE
Newsify RSS Reader

### ISSUE THREAD

**Issue by neostrifeX** [glasklart/hd#883]
**App Name:** Newsify RSS Reader
**Bundle ID:** com.synsion.Newsify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=510153374">510153374</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsify-rss-reader/id510153374?mt=8&uo=4">https://itunes.apple.com/us/app/newsify-rss-reader/id510153374?mt=8&uo=4</a>
**App Version:** 4.9
**Seller:** Ben Alexander
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ben-alexander/id510153377?uo=4">© Ben Alexander</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/fe/fa/47/fefa477c-efc8-8991-6363-69c20f5bf35c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32095130-66d894b2-bb02-11e7-9daf-114f1323c95f.png)

**Comment by l8er4now** [comment]
Could use an updated.

**App Name:** Newsify: Your News, Blog & RSS Feed Reader
**Bundle ID:** com.synsion.Newsify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=510153374">510153374</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsify-your-news-blog-rss/id510153374?mt=8&uo=4">https://itunes.apple.com/us/app/newsify-your-news-blog-rss/id510153374?mt=8&uo=4</a>
**App Version:** 4.2
**Seller:** Ben Alexander
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ben-alexander/id510153377?uo=4>© Ben Alexander</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/b0/d3/ff/b0d3ff9e-ec44-64f7-e260-305b490ddcaf/mzl.ddyjrprl.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11075176/32395414-87f4-11e5-9934-999f4dba3e3e.png)
https://cloud.githubusercontent.com/assets/2068130/11075176/32395414-87f4-11e5-9934-999f4dba3e3e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11075188/4096f70a-87f4-11e5-9235-d7e35213bd6a.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Newsify RSS Reader
**Bundle ID:** com.synsion.Newsify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=510153374">510153374</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newsify-rss-reader/id510153374?mt=8&uo=4">https://itunes.apple.com/us/app/newsify-rss-reader/id510153374?mt=8&uo=4</a>
**App Version:** 4.9
**Seller:** Ben Alexander
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ben-alexander/id510153377?uo=4">© Ben Alexander</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/fe/fa/47/fefa477c-efc8-8991-6363-69c20f5bf35c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32095130-66d894b2-bb02-11e7-9daf-114f1323c95f.png)
https://user-images.githubusercontent.com/2068130/32095130-66d894b2-bb02-11e7-9daf-114f1323c95f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32095140-76268456-bb02-11e7-8abe-2a6101487391.png
