### ISSUE TITLE
KenKen Classic

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8830]
**App Name:** KenKen Classic
**Bundle ID:** com.kenkenpuzzle.kenkeniphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=485694706">485694706</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kenken-classic/id485694706?mt=8&uo=4">https://itunes.apple.com/us/app/kenken-classic/id485694706?mt=8&uo=4</a>
**App Version:** 1.96
**Seller:** KenKen Puzzle, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kenken-puzzle/id485694769?uo=4">© KenKen Puzzle</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/71/9c/da/719cdadf-1e47-14ad-00d1-5cafa9031c1a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22334660/d97709c6-e3db-11e6-80d7-c29fbdb4c982.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22334660/d97709c6-e3db-11e6-80d7-c29fbdb4c982.png)
https://cloud.githubusercontent.com/assets/10730122/22334660/d97709c6-e3db-11e6-80d7-c29fbdb4c982.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/22334659/d9761eb2-e3db-11e6-87a9-4753204f7b3b.png
