### ISSUE TITLE
Teachers Federal Credit Union Mobile Banking

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8831]
**App Name:** Teachers Federal Credit Union Mobile Banking
**Bundle ID:** org.teachersfcu.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542382888">542382888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/teachers-federal-credit-union/id542382888?mt=8&uo=4">https://itunes.apple.com/us/app/teachers-federal-credit-union/id542382888?mt=8&uo=4</a>
**App Version:** 2.2463
**Seller:** Teachers Federal Credit Union
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/teachers-federal-credit-union/id542383251?uo=4">© Teachers Federal Credit Union</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/2c/58/19/2c581933-fa99-f7b9-ae17-c36614aca1f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618700/c7e56a86-eae3-11e6-85c0-2d8945ae6c26.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618700/c7e56a86-eae3-11e6-85c0-2d8945ae6c26.png)
https://cloud.githubusercontent.com/assets/20930745/22618700/c7e56a86-eae3-11e6-85c0-2d8945ae6c26.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618701/d4cfc32c-eae3-11e6-8964-7810bf73e403.png
