### ISSUE TITLE
NYTimes - Breaking Election, National & World News

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8832]
**App Name:** NYTimes - Breaking Election, National & World News
**Bundle ID:** com.nytimes.editorschoice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=357066198">357066198</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nytimes-breaking-election/id357066198?mt=8&uo=4">https://itunes.apple.com/us/app/nytimes-breaking-election/id357066198?mt=8&uo=4</a>
**App Version:** 3.17
**Seller:** The New York Times Company (iDP)
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-new-york-times-company/id284862086?uo=4">© The New York Times Company</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/d3/2e/3d/d32e3d5a-fac7-02fd-0fa4-4d8032849615/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22627246/89b55aaa-ebbf-11e6-8452-522211a62127.png)

**Comment by ivanov007** [comment]
I think we can use the @dreamnet's icon from #6854
This icon is [already in the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.nytimes.NYTimes@2x.png), but it has changed a litte bit. I update it.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11390247/831c80cc-9348-11e5-8e3b-c21e53bfd2ad.png)
https://cloud.githubusercontent.com/assets/2068130/11390247/831c80cc-9348-11e5-8e3b-c21e53bfd2ad.png

---

Source:
https://cloud.githubusercontent.com/assets/2068130/11390252/92dfaf2a-9348-11e5-8187-5b5676e4108f.png
