### ISSUE TITLE
NPR for iPad

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8833]
**App Name:** NPR for iPad
**Bundle ID:** org.npr.nprpad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364183644">364183644</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/npr-for-ipad/id364183644?mt=8&uo=4">https://itunes.apple.com/us/app/npr-for-ipad/id364183644?mt=8&uo=4</a>
**App Version:** 2.5.3
**Seller:** NPR
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/npr/id324906254?mt=8&uo=4">© NPR</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/d0/5c/0c/d05c0c92-54e8-6860-7382-1f20cc26e9d6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618661/bff12208-eae2-11e6-8408-173fe960fcf1.png)

**Comment by Sly-Fi** [comment]
This is the iPad version of the iPhone app that is in the master from issue #8059

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618661/bff12208-eae2-11e6-8408-173fe960fcf1.png)
https://cloud.githubusercontent.com/assets/20930745/22618661/bff12208-eae2-11e6-8408-173fe960fcf1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618665/d30eb24c-eae2-11e6-8a0d-4a041ed3d3fd.png
