### ISSUE TITLE
NPR Music

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8834]
**App Name:** NPR Music
**Bundle ID:** org.npr.nprmusic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378195188">378195188</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/npr-music/id378195188?mt=8&uo=4">https://itunes.apple.com/us/app/npr-music/id378195188?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** NPR
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/npr/id324906254?mt=8&uo=4">© NPR</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple4/v4/71/dd/78/71dd78b8-8482-b974-3480-382d77e168c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618628/7b5872fa-eae1-11e6-81ce-c9a61f8837d4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618628/7b5872fa-eae1-11e6-81ce-c9a61f8837d4.png)
https://cloud.githubusercontent.com/assets/20930745/22618628/7b5872fa-eae1-11e6-81ce-c9a61f8837d4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618632/96c1db80-eae1-11e6-8bd9-3fcfa12b10e2.png
