### ISSUE TITLE
U.S. Bank (TM)

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8835]
**App Name:** U.S. Bank (TM)
**Bundle ID:** com.usbank.icmobilebankingipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=515328530">515328530</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/u.s.-bank-tm/id515328530?mt=8&uo=4">https://itunes.apple.com/us/app/u.s.-bank-tm/id515328530?mt=8&uo=4</a>
**App Version:** 2.15.8
**Seller:** U.S. Bancorp
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/u.s.-bancorp/id458734630?uo=4">© U.S. Bancorp</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/4b/0f/06/4b0f063d-7891-b0df-d0e1-93b059aafce0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618578/5494ff9a-eae0-11e6-9e88-0055db127bbd.png)

**Comment by Sly-Fi** [comment]
This is the iPad version of the iPhone app that is in the master from issue #2262

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618578/5494ff9a-eae0-11e6-9e88-0055db127bbd.png)
https://cloud.githubusercontent.com/assets/20930745/22618578/5494ff9a-eae0-11e6-9e88-0055db127bbd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618580/625c6e74-eae0-11e6-9292-de4843bde7db.png
