### ISSUE TITLE
My Flights HD

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8836]
**App Name:** My Flights HD
**Bundle ID:** com.schofs.myflightshd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405104115">405104115</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-flights-hd/id405104115?mt=8&uo=4">https://itunes.apple.com/us/app/my-flights-hd/id405104115?mt=8&uo=4</a>
**App Version:** 3.1.5
**Seller:** Chris Schofield
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chris-schofield/id327067454?uo=4">© Chris Schofield</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/d4/3d/4d/d43d4d93-5fa0-00e6-805d-e2a850802996/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618566/1722235e-eae0-11e6-899b-a7eeac1183d4.png)

**Comment by Sly-Fi** [comment]
This is the iPad version of the iPhone app that is in the master from issue #8176

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618566/1722235e-eae0-11e6-899b-a7eeac1183d4.png)
https://cloud.githubusercontent.com/assets/20930745/22618566/1722235e-eae0-11e6-899b-a7eeac1183d4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618567/218f9a06-eae0-11e6-95a8-70e043aee4e7.png
