### ISSUE TITLE
GPS Kit HD

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8837]
**App Name:** GPS Kit HD
**Bundle ID:** com.garafa.GPSKitHD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418662204">418662204</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gps-kit-hd/id418662204?mt=8&uo=4">https://itunes.apple.com/us/app/gps-kit-hd/id418662204?mt=8&uo=4</a>
**App Version:** 7.0.1
**Seller:** Garafa, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/garafa-llc/id284829377?uo=4">© Garafa, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple6/v4/4a/43/ac/4a43acfd-c439-f7cf-b214-30d1b754de9e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18818106/79e1bc4c-8371-11e6-9814-773d64bb5f2b.png)

**Comment by ivanov007** [comment]
the icon can be the same @dreamnet ported for #2247
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18818106/79e1bc4c-8371-11e6-9814-773d64bb5f2b.png)
https://cloud.githubusercontent.com/assets/2068130/18818106/79e1bc4c-8371-11e6-9814-773d64bb5f2b.png

---

Source:
https://cloud.githubusercontent.com/assets/2068130/18818110/88a54b40-8371-11e6-9431-1899705c4935.png
