### ISSUE TITLE
Skype for iPad

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8838]
**App Name:** Skype for iPad
**Bundle ID:** com.skype.SkypeForiPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=442012681">442012681</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skype-for-ipad/id442012681?mt=8&uo=4">https://itunes.apple.com/us/app/skype-for-ipad/id442012681?mt=8&uo=4</a>
**App Version:** 6.30
**Seller:** Skype Communications S.a.r.l
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/skype-communications-s.a.r.l/id304219585?mt=8&uo=4">© Skype Communications S.a.r.l</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/1c/a1/13/1ca113d9-f77e-2f0c-57d2-1b37db4a9b45/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22377121/ee2e3030-e4b0-11e6-8070-fa11b9929d68.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22377121/ee2e3030-e4b0-11e6-8070-fa11b9929d68.png)
https://cloud.githubusercontent.com/assets/20930745/22377121/ee2e3030-e4b0-11e6-8070-fa11b9929d68.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22377137/fd72d69a-e4b0-11e6-9edf-03b4c0e13aa7.png

**Comment by dreamnet** [comment]
Same icon as for #6920.
