### ISSUE TITLE
Epicentral+

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8839]
**App Name:** Epicentral+
**Bundle ID:** com.ammon.Epicentral-Plus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469822724">469822724</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/epicentral+/id469822724?mt=8&uo=4">https://itunes.apple.com/us/app/epicentral+/id469822724?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** Charles Ammon
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/charles-j.-ammon/id297487706?uo=4">© Charles J. Ammon</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPadThirdGen, iPadThirdGen4G, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/22/4a/92/224a92b6-8bb1-6933-c64c-518c95a38352/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23091764/e01f6072-f5bd-11e6-8093-8905443a332b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23091764/e01f6072-f5bd-11e6-8093-8905443a332b.png)
https://cloud.githubusercontent.com/assets/2068130/23091764/e01f6072-f5bd-11e6-8093-8905443a332b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23091769/ef9a3ec8-f5bd-11e6-904a-38162e93850e.png
