### ISSUE TITLE
MonkeyMote 4 foobar2000

### ISSUE THREAD

**Issue by neostrifeX** [glasklart/hd#884]
**App Name:** MonkeyMote 4 foobar2000
**Bundle ID:** com.obsidium.monkeymote4foobar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=409693155">409693155</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/monkeymote-4-foobar2000/id409693155?mt=8&uo=4">https://itunes.apple.com/us/app/monkeymote-4-foobar2000/id409693155?mt=8&uo=4</a>
**App Version:** 2.6.4
**Seller:** Martin Tofall
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/martin-tofall/id406419205?uo=4>© Martin Tofall</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/b8/1a/00/b81a00e8-d138-9674-0785-b6334abcb14b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411434/1fa182e4-9302-11e6-95d8-30e0bc0b17bd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411381/eb54aa30-9300-11e6-9293-c07340f5cd4c.png)
https://cloud.githubusercontent.com/assets/20930745/19411381/eb54aa30-9300-11e6-9293-c07340f5cd4c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411385/f91ffe8a-9300-11e6-8010-1cedb7f79769.png
