### ISSUE TITLE
Epicentral

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8840]
**App Name:** Epicentral
**Bundle ID:** com.ammon.Epicentral
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=297487703">297487703</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/epicentral/id297487703?mt=8&uo=4">https://itunes.apple.com/us/app/epicentral/id297487703?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Charles Ammon
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/charles-j.-ammon/id297487706?uo=4">© Charles J. Ammon</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/3c/a1/32/3ca13238-0a7c-0bd3-98ab-c873ad60314d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23091764/e01f6072-f5bd-11e6-8093-8905443a332b.png)

**Comment by dreamnet** [comment]
Refers to #8839.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23091764/e01f6072-f5bd-11e6-8093-8905443a332b.png)
https://cloud.githubusercontent.com/assets/2068130/23091764/e01f6072-f5bd-11e6-8093-8905443a332b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23091769/ef9a3ec8-f5bd-11e6-904a-38162e93850e.png
❓
