### ISSUE TITLE
CaloryGuard - Track calories, lose weight

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8841]
**App Name:** CaloryGuard - Track calories, lose weight
**Bundle ID:** de.bluebamboo.caloryguard-premium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=673531087">673531087</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/caloryguard-track-calories/id673531087?mt=8&uo=4">https://itunes.apple.com/us/app/caloryguard-track-calories/id673531087?mt=8&uo=4</a>
**App Version:** 3.92.0
**Seller:** Falko Buttler
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bluebamboo.de-falko-buttler/id285599850?uo=4">© BlueBamboo.de Falko Buttler</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/36/25/9c/36259c67-f139-d401-5358-163ca756abd4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22918900/147ec9b8-f28d-11e6-95f2-fef597d9dfb3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22918900/147ec9b8-f28d-11e6-95f2-fef597d9dfb3.png)
https://cloud.githubusercontent.com/assets/2068130/22918900/147ec9b8-f28d-11e6-95f2-fef597d9dfb3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22918910/24950560-f28d-11e6-97a0-f7487d99e35e.png
