### ISSUE TITLE
Beam for reddit

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8842]
**App Name:** Beam for reddit
**Bundle ID:** com.madeawkward.beam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937987469">937987469</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/beam-for-reddit/id937987469?mt=8&uo=4">https://itunes.apple.com/us/app/beam-for-reddit/id937987469?mt=8&uo=4</a>
**App Version:** 2.5.2
**Seller:** Awkward BV
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/awkward/id708358190?uo=4">© Awkward</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/06/b2/df/06b2dff5-1edc-9887-827d-86b9c314ad6b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23117306/5e5fd24a-f74f-11e6-8403-8e9ae143efc4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23117306/5e5fd24a-f74f-11e6-8403-8e9ae143efc4.png)
https://cloud.githubusercontent.com/assets/2068130/23117306/5e5fd24a-f74f-11e6-8403-8e9ae143efc4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23117315/6d06a530-f74f-11e6-828a-d013dd4ffbf4.png
