### ISSUE TITLE
Master Caster: Cast Podcasts and Web Videos

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8843]
**App Name:** Master Caster: Cast Podcasts and Web Videos
**Bundle ID:** com.hollylabs.Master-Caster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1029651642">1029651642</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/master-caster-cast-podcasts/id1029651642?mt=8&uo=4">https://itunes.apple.com/us/app/master-caster-cast-podcasts/id1029651642?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** Miles Hollingsworth
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/miles-hollingsworth/id903085290?uo=4">© Miles Hollingsworth</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/44/bc/a0/44bca013-316f-354f-fff7-c12800c0a698/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618551/ae73d5a0-eadf-11e6-96bd-c0ecdf158c47.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618551/ae73d5a0-eadf-11e6-96bd-c0ecdf158c47.png)
https://cloud.githubusercontent.com/assets/20930745/22618551/ae73d5a0-eadf-11e6-96bd-c0ecdf158c47.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618553/b93ecd64-eadf-11e6-930c-363bcf4f06d0.png
