### ISSUE TITLE
LaMetric Time

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8844]
**App Name:** LaMetric Time
**Bundle ID:** com.smartatoms.lametric
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=987445829">987445829</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lametric-time/id987445829?mt=8&uo=4">https://itunes.apple.com/us/app/lametric-time/id987445829?mt=8&uo=4</a>
**App Version:** 1.7.5
**Seller:** Smart Atoms Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/smart-atoms-limited/id1042231653?uo=4">© Smart Atoms Limited</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/35/e2/b0/35e2b04c-2e43-a266-0b55-10f0443ea2b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23091738/1f9b9136-f5bd-11e6-9f07-e4677bcb390f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23091738/1f9b9136-f5bd-11e6-9f07-e4677bcb390f.png)
https://cloud.githubusercontent.com/assets/2068130/23091738/1f9b9136-f5bd-11e6-9f07-e4677bcb390f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23091743/2ed78eca-f5bd-11e6-87ce-3490a1659ab7.png
❓
