### ISSUE TITLE
Yu-Gi-Oh! Duel Links

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#8846]
**App Name:** Yu-Gi-Oh! Duel Links
**Bundle ID:** jp.konami.yugiohmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1068378177">1068378177</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yu-gi-oh!-duel-links/id1068378177?mt=8&uo=4">https://itunes.apple.com/us/app/yu-gi-oh!-duel-links/id1068378177?mt=8&uo=4</a>
**App Version:** 1.2.0
**Seller:** Konami Digital Entertainment Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/konami/id299580230?mt=8&uo=4">© KONAMI</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/7e/2b/77/7e2b77bc-b356-060f-67b9-a37158b07c18/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23036921/d8a5bb0a-f484-11e6-9ddb-fa3ac54498c8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23036921/d8a5bb0a-f484-11e6-9ddb-fa3ac54498c8.png)
https://cloud.githubusercontent.com/assets/2068130/23036921/d8a5bb0a-f484-11e6-9ddb-fa3ac54498c8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23036934/e9036916-f484-11e6-8454-ba5494a9e112.png

**Comment by TheRyanKing** [comment]
This looks awesome!
