### ISSUE TITLE
Infuse 6

### ISSUE THREAD

**Issue by sern19** [glasklart/hd#8847]
**App Name:** Infuse 6
**Bundle ID:** com.firecore.infuse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1136220934">1136220934</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/infuse-6/id1136220934?uo=4">https://apps.apple.com/us/app/infuse-6/id1136220934?uo=4</a>
**App Version:** 6.3
**Seller:** Firecore, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/firecore-llc/id577130089?uo=4">© Firecore, LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/c3/47/ff/c347ff54-e711-ab98-a39b-e03371c9ce2d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74558209-29820e80-4f62-11ea-9776-3015d256c618.png)

**Comment by sern19** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/22561169/60abf398-e977-11e6-9b50-bf87795eb56e.png)
Source:
https://cloud.githubusercontent.com/assets/23708258/22561177/69922ebe-e977-11e6-979c-71cb478625a4.png

**Comment by 2Qt2beStr8** [comment]
same as #4001

**Comment by dreamnet** [comment]
Icon by @ivanov007.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22629628/b8da8c5e-ebe9-11e6-8477-158338f30103.png)
https://cloud.githubusercontent.com/assets/2068130/22629628/b8da8c5e-ebe9-11e6-8477-158338f30103.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22629631/cd89b83c-ebe9-11e6-8ced-73f96852b5e0.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Infuse 6
**Bundle ID:** com.firecore.infuse
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1136220934">1136220934</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/infuse-6/id1136220934?uo=4">https://apps.apple.com/us/app/infuse-6/id1136220934?uo=4</a>
**App Version:** 6.3
**Seller:** Firecore, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/firecore-llc/id577130089?uo=4">© Firecore, LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/c3/47/ff/c347ff54-e711-ab98-a39b-e03371c9ce2d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74558209-29820e80-4f62-11ea-9776-3015d256c618.png)
https://user-images.githubusercontent.com/20930745/74558209-29820e80-4f62-11ea-9776-3015d256c618.png

Source:
https://user-images.githubusercontent.com/20930745/74558215-2b4bd200-4f62-11ea-86d1-087dd59e54f7.png
