### ISSUE TITLE
Bank Pekao

### ISSUE THREAD

**Issue by sern19** [glasklart/hd#8848]
**App Name:** Bank Pekao
**Bundle ID:** pl.pekao.pekaosa.pekaosa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484502613">484502613</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bank-pekao/id484502613?mt=8&uo=4">https://itunes.apple.com/us/app/bank-pekao/id484502613?mt=8&uo=4</a>
**App Version:** 5.0.0
**Seller:** Bank Polska Kasa Opieki Spolka Akcyjna
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bank-pekao-sa/id484502616?uo=4">© Bank Pekao SA</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/2b/3b/12/2b3b1266-a9dd-69bf-fb08-216b9a0e44e9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621545-2d226100-a8a8-11e8-9312-5be0d8c8ff26.png)

**Comment by sern19** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/22563307/53f47252-e980-11e6-89fa-488bd1b22054.png)
Source:
https://cloud.githubusercontent.com/assets/23708258/22563317/625c626e-e980-11e6-89fb-78ebaea63b66.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621545-2d226100-a8a8-11e8-9312-5be0d8c8ff26.png)
https://user-images.githubusercontent.com/2068130/44621545-2d226100-a8a8-11e8-9312-5be0d8c8ff26.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44621548-3c091380-a8a8-11e8-945a-36c5f8952de6.png
