### ISSUE TITLE
GlobeConvert - Currency & Units Converter

### ISSUE THREAD

**Issue by neostrifeX** [glasklart/hd#885]
**App Name:** GlobeConvert - Currency & Units Converter
**Bundle ID:** com.globefamilyapps.globeconvert
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=462208752">462208752</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/globeconvert-currency-units/id462208752?mt=8&uo=4">https://itunes.apple.com/us/app/globeconvert-currency-units/id462208752?mt=8&uo=4</a>
**App Version:** 1.7.5
**Seller:** Ivan Karpan
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ivan-karpan-evgeniy-lebed/id329676067?uo=4>© Ivan Karpan & Evgeniy Lebed</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple6/v4/95/d4/95/95d49584-07fb-2635-6c77-60a81bc43dcb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19013861/9014db78-87dd-11e6-829c-7d1c2a3eb5a4.png)

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8 
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19013861/9014db78-87dd-11e6-829c-7d1c2a3eb5a4.png)
https://cloud.githubusercontent.com/assets/20930745/19013861/9014db78-87dd-11e6-829c-7d1c2a3eb5a4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19013866/9f9108f6-87dd-11e6-958d-fe17ac010387.png
