### ISSUE TITLE
McDonald's Polska

### ISSUE THREAD

**Issue by sern19** [glasklart/hd#8850]
**App Name:** McDonald's Polska
**Bundle ID:** pl.tribalddb.mcdonalds.app.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=820210761">820210761</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mcdonalds-polska/id820210761?mt=8&uo=4">https://itunes.apple.com/us/app/mcdonalds-polska/id820210761?mt=8&uo=4</a>
**App Version:** 1.2.7
**Seller:** McDonald's Polska Sp. z o.o.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mcdonalds-polska/id591375775?uo=4">© McDonald's Polska</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/0f/93/a1/0f93a14b-17c8-5467-1b51-7c60a2c8c7ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/22431852/999cafc2-e6d8-11e6-9068-6e67edf9f335.png)

**Comment by sern19** [comment]
Same icon as in issue #110

**Comment by ivanov007** [comment]
@Trubbel icon:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png)
https://cloud.githubusercontent.com/assets/10730122/8761835/c68e24a2-2d66-11e5-99f1-2fe9095a7f08.png

---

Source:
https://cloud.githubusercontent.com/assets/10730122/8761834/c42be2c6-2d66-11e5-99cf-e8c30451ac47.png

**Comment by ivanov007** [comment]
@Trubbel icon (just converted to the new template)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/22431852/999cafc2-e6d8-11e6-9068-6e67edf9f335.png)
https://cloud.githubusercontent.com/assets/3090247/22431852/999cafc2-e6d8-11e6-9068-6e67edf9f335.png
---
Source:
https://cloud.githubusercontent.com/assets/10730122/8761834/c42be2c6-2d66-11e5-99cf-e8c30451ac47.png
