### ISSUE TITLE
Play24

### ISSUE THREAD

**Issue by sern19** [glasklart/hd#8851]
**App Name:** Play24
**Bundle ID:** com.p4.play24
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498473583">498473583</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/play24/id498473583?mt=8&uo=4">https://itunes.apple.com/us/app/play24/id498473583?mt=8&uo=4</a>
**App Version:** 4.3.1
**Seller:** P4 sp. z o.o. (Play)
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/p4-sp.-z-o.o.-operator-sieci/id498456114?uo=4">© P4 sp. z o.o. operator sieci Play</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/ca/0a/3b/ca0a3b8e-44ad-6522-9436-19926d224499/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/22547116/69e2b802-e940-11e6-8e94-500586550ace.png)

**Comment by sern19** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/22547116/69e2b802-e940-11e6-8e94-500586550ace.png)
Source:
https://cloud.githubusercontent.com/assets/23708258/22547211/f0fded20-e940-11e6-9559-28a835d5aa42.png

**Comment by dreamnet** [comment]
@sern19 Good work, if you want to be on the [contributors list](https://github.com/glasklart/hd/graphs/contributors), you need to add a public mailadress to your Github account.
