### ISSUE TITLE
WoW Legion Companion

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#8853]
**App Name:** WoW Legion Companion
**Bundle ID:** com.blizzard.wowcompanion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1125608061">1125608061</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wow-legion-companion/id1125608061?mt=8&uo=4">https://itunes.apple.com/us/app/wow-legion-companion/id1125608061?mt=8&uo=4</a>
**App Version:** 1.1.5
**Seller:** Blizzard Entertainment, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/blizzard-entertainment-inc./id306862900?uo=4">© Blizzard Entertainment, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/40/fd/36/40fd3693-c3d9-6398-0ff9-cd8164ddc20b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22940915/c949349a-f2e3-11e6-98e9-39488aaad784.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22940915/c949349a-f2e3-11e6-98e9-39488aaad784.png)
https://cloud.githubusercontent.com/assets/2068130/22940915/c949349a-f2e3-11e6-98e9-39488aaad784.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22940929/d96694b2-f2e3-11e6-8020-7ce6519f05c0.png
