### ISSUE TITLE
Titan Quest

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#8854]
**App Name:** Titan Quest
**Bundle ID:** com.dotemu.TitanQuest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035690802">1035690802</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/titan-quest/id1035690802?mt=8&uo=4">https://itunes.apple.com/us/app/titan-quest/id1035690802?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** DotEmu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dotemu/id329185054?uo=4">© DotEmu</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/6a/84/9a/6a849ae1-5ae9-5c7e-fa0a-2773d009399e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22625475/61cb8e3c-eb98-11e6-9538-f5bd08175cd8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22625475/61cb8e3c-eb98-11e6-9538-f5bd08175cd8.png)
https://cloud.githubusercontent.com/assets/20930745/22625475/61cb8e3c-eb98-11e6-9538-f5bd08175cd8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22625479/70fac788-eb98-11e6-9fac-7621fea29a5a.png
