### ISSUE TITLE
The Battle of Polytopia

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#8855]
**App Name:** The Battle of Polytopia
**Bundle ID:** com.felixrum.supertribes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1006393168">1006393168</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-battle-of-polytopia/id1006393168?mt=8&uo=4">https://itunes.apple.com/us/app/the-battle-of-polytopia/id1006393168?mt=8&uo=4</a>
**App Version:** 1.6.1
**Seller:** Midjiwan AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/midjiwan-ab/id609071967?uo=4">© Midjiwan AB</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/71/88/ec/7188ecb2-312f-78d2-981a-e8ae9ed3737a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23161787/b845ece0-f82b-11e6-9e18-2c9fdc9287c4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23154645/39972cb8-f80f-11e6-982e-eeae4875e670.png)
https://cloud.githubusercontent.com/assets/2068130/23154645/39972cb8-f80f-11e6-982e-eeae4875e670.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23154663/480b5472-f80f-11e6-973c-1689a1fdb482.png
❓
