### ISSUE TITLE
Mr.Patrol

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#8856]
**App Name:** Mr.Patrol
**Bundle ID:** com.RNCNetwork.MrPatrol
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=871645884">871645884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mr.patrol/id871645884?mt=8&uo=4">https://itunes.apple.com/us/app/mr.patrol/id871645884?mt=8&uo=4</a>
**App Version:** 2.2.0.2019
**Seller:** RNC Network
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rnc-network/id871645887?uo=4">© RNC Network</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/e8/28/69/e8286926-8f7a-fc50-99a9-841da1958235/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22861682/62e4ca7c-f11f-11e6-842f-38df549dd28d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22861682/62e4ca7c-f11f-11e6-842f-38df549dd28d.png)
https://cloud.githubusercontent.com/assets/2068130/22861682/62e4ca7c-f11f-11e6-842f-38df549dd28d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22861683/71eea830-f11f-11e6-8a49-6f3cdc19624f.png
