### ISSUE TITLE
Grades for Parents and Students

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#8857]
**App Name:** Grades for Parents and Students
**Bundle ID:** com.adrientruong.Grades
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=947291514">947291514</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grades-for-parents-students/id947291514?mt=8&uo=4">https://itunes.apple.com/us/app/grades-for-parents-students/id947291514?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Vinh Truong
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vinh-truong/id452568411?uo=4">© Vinh Truong</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/21/55/ff/2155ff35-d0ab-44b2-2a7c-2a01f5ae1431/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618466/3e1ec99c-eadd-11e6-884e-6205262e1343.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618466/3e1ec99c-eadd-11e6-884e-6205262e1343.png)
https://cloud.githubusercontent.com/assets/20930745/22618466/3e1ec99c-eadd-11e6-884e-6205262e1343.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618473/55f42224-eadd-11e6-9bc2-9ec05048bdde.png
