### ISSUE TITLE
Wahoo Fitness – Bluetooth Powered Cycling and Running Workout Tracker

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#886]
**App Name:** Wahoo Fitness – Bluetooth Powered Cycling and Running Workout Tracker
**Bundle ID:** com.WahooFitness.FisicaFitness
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391599899">391599899</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wahoo-fitness-bluetooth-powered/id391599899?mt=8&uo=4">https://itunes.apple.com/us/app/wahoo-fitness-bluetooth-powered/id391599899?mt=8&uo=4</a>
**App Version:** 5.8.1
**Seller:** Wahoo Fitness L.L.C.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/wahoo-fitness/id359225354?uo=4>© Wahoo Fitness</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/69/36/e7/6936e7dc-bbe1-a676-1cb1-661d3ad951bb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410072/eccde570-92e2-11e6-9bad-3bdf1552ebe2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410072/eccde570-92e2-11e6-9bad-3bdf1552ebe2.png)
https://cloud.githubusercontent.com/assets/20930745/19410072/eccde570-92e2-11e6-9bad-3bdf1552ebe2.png

Source:
(https://cloud.githubusercontent.com/assets/20930745/19410074/fc0cefe0-92e2-11e6-8c62-8bce71b38e79.png
