### ISSUE TITLE
Enjin - Community for Gamers

### ISSUE THREAD

**Issue by goalreadymc** [glasklart/hd#8860]
**App Name:** Enjin - Community for Gamers
**Bundle ID:** com.enjin.enjinmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1103331595">1103331595</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/enjin-community-for-gamers/id1103331595?mt=8&uo=4">https://itunes.apple.com/us/app/enjin-community-for-gamers/id1103331595?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Enjin PTE LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/enjin-pte-ltd/id1103331594?uo=4">© Enjin PTE LTD</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/3f/7a/eb/3f7aebd4-bf03-241a-d382-95effb627c61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22939586/76036e94-f2df-11e6-9ff0-9b60cd55b0f1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22939586/76036e94-f2df-11e6-9ff0-9b60cd55b0f1.png)
https://cloud.githubusercontent.com/assets/2068130/22939586/76036e94-f2df-11e6-9ff0-9b60cd55b0f1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22939604/863b45e8-f2df-11e6-9ae2-6b53ffcfe10f.png
