### ISSUE TITLE
Zalo

### ISSUE THREAD

**Issue by jcolkeng** [glasklart/hd#8861]
**App Name:** Zalo
**Bundle ID:** vn.com.vng.zingalo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=579523206">579523206</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zalo/id579523206?mt=8&uo=4">https://itunes.apple.com/us/app/zalo/id579523206?mt=8&uo=4</a>
**App Version:** 5.13
**Seller:** VNG ONLINE CO.,LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zalo-group/id822220029?uo=4">© Zalo Group</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/6f/13/39/6f1339c6-7872-80a8-4794-2f8a8c0ae333/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618420/eb052db0-eadb-11e6-9f7c-2e4350c9d14a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618407/96c49510-eadb-11e6-88b2-87b0162ec54b.png)
https://cloud.githubusercontent.com/assets/20930745/22618407/96c49510-eadb-11e6-88b2-87b0162ec54b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618410/a99fddc0-eadb-11e6-89c1-c2d48ed26bf7.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618420/eb052db0-eadb-11e6-9f7c-2e4350c9d14a.png)
https://cloud.githubusercontent.com/assets/20930745/22618420/eb052db0-eadb-11e6-9f7c-2e4350c9d14a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618422/fa13adfe-eadb-11e6-87e6-7ace8b7938e1.png
