### ISSUE TITLE
Premier League - Official App

### ISSUE THREAD

**Issue by jcolkeng** [glasklart/hd#8862]
**App Name:** Premier League - Official App
**Bundle ID:** com.premierleague.main
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1138895159">1138895159</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/premier-league-official-app/id1138895159?mt=8&uo=4">https://itunes.apple.com/us/app/premier-league-official-app/id1138895159?mt=8&uo=4</a>
**App Version:** 1.0.17
**Seller:** The Football Association Premier League Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/premier-league/id763098914?uo=4">© Premier League</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/68/ba/e8/68bae85a-5ff2-11c8-33de-5de1d513d3c8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22630074/ff7d5a8e-ebf2-11e6-8a13-d7b69ad7ddb6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618381/eda06144-eada-11e6-8c67-3370366abd80.png)
https://cloud.githubusercontent.com/assets/20930745/22618381/eda06144-eada-11e6-8c67-3370366abd80.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618383/fafe2998-eada-11e6-992c-06eb69e82159.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22630074/ff7d5a8e-ebf2-11e6-8a13-d7b69ad7ddb6.png)
https://cloud.githubusercontent.com/assets/2068130/22630074/ff7d5a8e-ebf2-11e6-8a13-d7b69ad7ddb6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22630079/0f5665a4-ebf3-11e6-9343-e568f687ebf7.png
