### ISSUE TITLE
medizinfuchs - Preisvergleich für Medikamente

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8863]
**App Name:** medizinfuchs - Preisvergleich für Medikamente
**Bundle ID:** com.mf.medizinfuchs
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=549109456">549109456</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/medizinfuchs-preisvergleich/id549109456?mt=8&uo=4">https://itunes.apple.com/de/app/medizinfuchs-preisvergleich/id549109456?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** medizinfuchs GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/medizinfuchs-gmbh/id549099517?uo=4">© medizinfuchs GmbH</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/8a/83/50/8a8350c0-f13d-9a85-49b9-1af247592029/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22625517/7c574c4a-eb99-11e6-852d-2d1a5f369b28.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22625517/7c574c4a-eb99-11e6-852d-2d1a5f369b28.png)
https://cloud.githubusercontent.com/assets/20930745/22625517/7c574c4a-eb99-11e6-852d-2d1a5f369b28.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22625520/8a9c2a32-eb99-11e6-9c7b-cb6695b7febb.png
