### ISSUE TITLE
View Source – HTML, JavaScript and CSS

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8864]
**App Name:** View Source – HTML, JavaScript and CSS
**Bundle ID:** com.hudzillagames.viewsource
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=917660039">917660039</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/view-source-html-javascript/id917660039?mt=8&uo=4">https://itunes.apple.com/us/app/view-source-html-javascript/id917660039?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Paul Hudson
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/paul-hudson/id333613446?uo=4">© Paul Hudson</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple3/v4/5b/e5/8f/5be58f3d-b711-2473-89c9-d8226fa5640c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618353/603aacc4-eada-11e6-8fa1-b0f9658c8b33.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618353/603aacc4-eada-11e6-8fa1-b0f9658c8b33.png)
https://cloud.githubusercontent.com/assets/20930745/22618353/603aacc4-eada-11e6-8fa1-b0f9658c8b33.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618357/6deb568e-eada-11e6-9684-c436f92cb96b.png
