### ISSUE TITLE
PDF it All: Scanner, PDF Printer and Converter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8865]
**App Name:** PDF it All Document Converter
**Bundle ID:** com.digiset.pdfit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=627640657">627640657</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pdf-it-all-document-converter/id627640657?uo=4">https://apps.apple.com/us/app/pdf-it-all-document-converter/id627640657?uo=4</a>
**App Version:** 4.2
**Seller:** DIGISET LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/digiset-llc/id944123342?uo=4">© DIGISET LLC</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/8e/8d/23/8e8d235c-2250-fca8-93c5-125d436c83b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334527-74245e00-a2a7-11ea-93fb-0f3cf5d44c3b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618251/b4280eec-ead7-11e6-83ed-2a053cd6f501.png)
https://cloud.githubusercontent.com/assets/20930745/22618251/b4280eec-ead7-11e6-83ed-2a053cd6f501.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618255/c086beae-ead7-11e6-8e4a-2342ee48e376.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618309/92879c10-ead9-11e6-92be-cafd5af666f1.png)
https://cloud.githubusercontent.com/assets/20930745/22618309/92879c10-ead9-11e6-92be-cafd5af666f1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618315/a115e16a-ead9-11e6-8cf1-e66b4e34d476.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618331/f06edd52-ead9-11e6-823e-28f04f77b5ec.png)
https://cloud.githubusercontent.com/assets/20930745/22618331/f06edd52-ead9-11e6-823e-28f04f77b5ec.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618332/fd8b97e6-ead9-11e6-9f0f-4e5525286874.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618435/4f41ece6-eadc-11e6-9cb2-1d4faf260ba4.png)
https://cloud.githubusercontent.com/assets/20930745/22618435/4f41ece6-eadc-11e6-9cb2-1d4faf260ba4.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618440/5fcc471e-eadc-11e6-867d-c3f59c53027b.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22630029/2d013526-ebf2-11e6-96b7-6d49f1422607.png)
https://cloud.githubusercontent.com/assets/2068130/22630029/2d013526-ebf2-11e6-96b7-6d49f1422607.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22630032/3c1a4796-ebf2-11e6-8586-858aed240a7a.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** PDF it All Document Converter
**Bundle ID:** com.digiset.pdfit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=627640657">627640657</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pdf-it-all-document-converter/id627640657?uo=4">https://apps.apple.com/us/app/pdf-it-all-document-converter/id627640657?uo=4</a>
**App Version:** 4.1.2
**Seller:** DIGISET LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/digiset-llc/id944123342?uo=4">© DIGISET LLC</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/3d/6c/13/3d6c1371-b441-919f-1b52-0950ce6d8077/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83334527-74245e00-a2a7-11ea-93fb-0f3cf5d44c3b.png)
https://user-images.githubusercontent.com/2068130/83334527-74245e00-a2a7-11ea-93fb-0f3cf5d44c3b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83334534-84d4d400-a2a7-11ea-909f-c1450ea23e24.png
