### ISSUE TITLE
My Forecasts: Outdoor Activities And Weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8866]
**App Name:** My Forecasts: Outdoor Activities And Weather
**Bundle ID:** net.vestasoftware.myforecast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=698124406">698124406</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-forecasts-outdoor-activities/id698124406?mt=8&uo=4">https://itunes.apple.com/us/app/my-forecasts-outdoor-activities/id698124406?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Vesta Software LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vesta-software-llc/id382162686?uo=4">© Vesta Software, LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/10/0e/04/100e0405-e80b-11fd-25df-fc7390a60bc2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618196/f5ffa6c8-ead6-11e6-916e-15b3ba199bdd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618186/ca53c25c-ead6-11e6-8dfe-b7a3356fad0a.png)
https://cloud.githubusercontent.com/assets/20930745/22618186/ca53c25c-ead6-11e6-8dfe-b7a3356fad0a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618191/da73f648-ead6-11e6-84e6-6de5972d888b.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22618196/f5ffa6c8-ead6-11e6-916e-15b3ba199bdd.png)
https://cloud.githubusercontent.com/assets/20930745/22618196/f5ffa6c8-ead6-11e6-916e-15b3ba199bdd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22618199/017c2be8-ead7-11e6-8463-217a5677d9d4.png
