### ISSUE TITLE
Dominos MX

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#8868]
**App Name:** Dominos MX
**Bundle ID:** mx.com.dominos.Dominos-MX
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049204901">1049204901</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/mx/app/dominos-mx/id1049204901?mt=8&uo=4">https://itunes.apple.com/mx/app/dominos-mx/id1049204901?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Alsea S.A.B, de C.V.
**Developer:** <a target="_blank" href="">© Alsea</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/fa/35/e4/fa35e4e3-d8e7-bb29-7594-0ac267298457/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22629429/5442fb62-ebe6-11e6-8dbb-a58866a08ce6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22629416/16a06092-ebe6-11e6-8910-0b442e9202ae.png)
https://cloud.githubusercontent.com/assets/20930745/22629416/16a06092-ebe6-11e6-8910-0b442e9202ae.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22629422/2c61ea9a-ebe6-11e6-8e20-670b8fada431.png

**Comment by dreamnet** [comment]
Same as #3276.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22629429/5442fb62-ebe6-11e6-8dbb-a58866a08ce6.png)
https://cloud.githubusercontent.com/assets/2068130/22629429/5442fb62-ebe6-11e6-8dbb-a58866a08ce6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22629433/62af6492-ebe6-11e6-8e35-f5dc81fa8e1a.png
