### ISSUE TITLE
CDJapan App

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#8869]
**App Name:** CDJapan App
**Bundle ID:** jp.co.cdjapan.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1058711820">1058711820</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cdjapan-app/id1058711820?mt=8&uo=4">https://itunes.apple.com/us/app/cdjapan-app/id1058711820?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Neowing Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/neowing/id573827166?uo=4">© Neowing</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/d7/7f/85/d77f8592-1b03-61ae-e02d-220c34655a20/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22629497/7955c294-ebe7-11e6-88b2-c5e80f8becdb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22629497/7955c294-ebe7-11e6-88b2-c5e80f8becdb.png)
https://cloud.githubusercontent.com/assets/20930745/22629497/7955c294-ebe7-11e6-88b2-c5e80f8becdb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22629503/8e1556ea-ebe7-11e6-92a6-71a6105689cb.png
