### ISSUE TITLE
RSA SecurID Software Token

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#887]
**App Name:** RSA SecurID Software Token
**Bundle ID:** com.rsa.securid.iphone.SecurID
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=318038618">318038618</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rsa-securid-software-token/id318038618?mt=8&uo=4">https://itunes.apple.com/us/app/rsa-securid-software-token/id318038618?mt=8&uo=4</a>
**App Version:** 2.2.2
**Seller:** RSA Security
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/rsa-security-division-emc/id318038621?mt=8&uo=4>© RSA, The Security Division of EMC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple18/v4/d9/77/e1/d977e1ec-3372-b41b-9650-5cff7fbfe5c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410346/1a4f5f86-92ea-11e6-9bc6-de131e87597b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410346/1a4f5f86-92ea-11e6-9bc6-de131e87597b.png)
https://cloud.githubusercontent.com/assets/20930745/19410346/1a4f5f86-92ea-11e6-9bc6-de131e87597b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19410351/354ce574-92ea-11e6-9f9e-fe47f8a2edb4.png
