### ISSUE TITLE
ラブライブ！スクールアイドルフェスティバル

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#8870]
**App Name:** ラブライブ！スクールアイドルフェスティバル
**Bundle ID:** jp.klab.lovelive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=626776655">626776655</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/jp/app/raburaibu!sukuruaidorufesutibaru/id626776655?mt=8&uo=4">https://itunes.apple.com/jp/app/raburaibu!sukuruaidorufesutibaru/id626776655?mt=8&uo=4</a>
**App Version:** 4.2.1
**Seller:** KLab Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/jp/developer/klab-inc./id302647750?uo=4">© KLab Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/47/62/54/4762540b-2a73-09fc-ade7-522cb76c78fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22971990/094d0a00-f378-11e6-9de5-df24c65dbe5f.png)

**Comment by Trubbel** [comment]
Refers to #4287.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22971990/094d0a00-f378-11e6-9de5-df24c65dbe5f.png)
https://cloud.githubusercontent.com/assets/2068130/22971990/094d0a00-f378-11e6-9de5-df24c65dbe5f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22972003/179c68f8-f378-11e6-8a28-22478abde818.png
