### ISSUE TITLE
8bit Nyan Cat: Lost In Space

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#8871]
**App Name:** 8bit Nyan Cat: Lost In Space
**Bundle ID:** com.istomgames.nyan8bit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586236223">586236223</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/8bit-nyan-cat-lost-in-space/id586236223?mt=8&uo=4">https://itunes.apple.com/us/app/8bit-nyan-cat-lost-in-space/id586236223?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Istom Games Kft.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/istom-games-kft./id333561719?uo=4">© Istom Games Kft.</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple/v4/c5/bb/f3/c5bbf324-4a3a-da3e-b9fe-7329af2870f6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23091676/ae39d3a0-f5bb-11e6-9fbe-1dead35d618d.png)

**Comment by TheRyanKing** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/23025990/bfbb7956-f42d-11e6-8d93-f4b6ed231f1b.png)

(https://cloud.githubusercontent.com/assets/10021829/23025999/c937ac5c-f42d-11e6-8efc-499a59466062.png)

(https://cloud.githubusercontent.com/assets/10021829/23026008/d32bd062-f42d-11e6-9cb6-2cb182ce473f.png)

**Comment by ivanov007** [comment]
@TheRyanKing I think it needs to be inverted, something like #729

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23091676/ae39d3a0-f5bb-11e6-9fbe-1dead35d618d.png)
https://cloud.githubusercontent.com/assets/2068130/23091676/ae39d3a0-f5bb-11e6-9fbe-1dead35d618d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23091677/bb6ae15e-f5bb-11e6-8a25-7ae96c8b93b0.png
