### ISSUE TITLE
Dot Live!

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#8872]
**App Name:** Dot Live!
**Bundle ID:** DDish.DotLive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=933759187">933759187</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dot-live!/id933759187?mt=8&uo=4">https://itunes.apple.com/us/app/dot-live!/id933759187?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Jung Minsu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jung-minsu/id933759186?uo=4">© Jung Minsu</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/f3/11/c0/f311c04c-89a3-c435-543a-36e1d8a592a5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23302785/93f17ea6-fa90-11e6-9826-4424020fc206.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23302785/93f17ea6-fa90-11e6-9826-4424020fc206.png)
https://cloud.githubusercontent.com/assets/2068130/23302785/93f17ea6-fa90-11e6-9826-4424020fc206.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23302795/a13c9bb8-fa90-11e6-8515-9123a77e810d.png
❓
