### ISSUE TITLE
Dot Live! Sunshine!!

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#8873]
**App Name:** Dot Live! Sunshine!!
**Bundle ID:** DDish.DotliveSunshine
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1151824374">1151824374</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dot-live!-sunshine!!/id1151824374?mt=8&uo=4">https://itunes.apple.com/us/app/dot-live!-sunshine!!/id1151824374?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Jung Minsu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jung-minsu/id933759186?uo=4">© Jung Minsu</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/ef/3b/cc/ef3bccf1-21fb-1005-4171-0d72e263936e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23302141/c795eff6-fa8d-11e6-83c0-2693a44da09b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23302141/c795eff6-fa8d-11e6-83c0-2693a44da09b.png)
https://cloud.githubusercontent.com/assets/2068130/23302141/c795eff6-fa8d-11e6-83c0-2693a44da09b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23302155/d9a0f362-fa8d-11e6-9e5b-6fd287571fdb.png
❓
