### ISSUE TITLE
Liga Bancomer MX App Oficial

### ISSUE THREAD

**Issue by dengler9** [glasklart/hd#8874]
**App Name:** Liga Bancomer MX App Oficial
**Bundle ID:** com.futbolx.ligamx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926515829">926515829</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/liga-bancomer-mx-app-oficial/id926515829?mt=8&uo=4">https://itunes.apple.com/us/app/liga-bancomer-mx-app-oficial/id926515829?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** AppCentral S.A.P.I. de C.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/appcentral-s.a.p.i.-de-c.v./id983625684?uo=4">© AppCentral S.A.P.I. de C.V.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/30/35/89/3035890b-ae30-b71c-6cd0-a16399d657e1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22832384/19527c32-efae-11e6-8cbd-3bb05611f598.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22832384/19527c32-efae-11e6-8cbd-3bb05611f598.png)
https://cloud.githubusercontent.com/assets/20930745/22832384/19527c32-efae-11e6-8cbd-3bb05611f598.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22832391/25867f58-efae-11e6-9c60-3ff1f8f70060.png
