### ISSUE TITLE
BMW Connected

### ISSUE THREAD

**Issue by icecharger** [glasklart/hd#8875]
**App Name:** BMW Connected
**Bundle ID:** de.bmw.connected.na
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1087277146">1087277146</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bmw-connected/id1087277146?mt=8&uo=4">https://itunes.apple.com/us/app/bmw-connected/id1087277146?mt=8&uo=4</a>
**App Version:** 4.1
**Seller:** BMW NORTH AMERICA, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bmw/id505168748?uo=4">© BMW</a>
**Supported Devices:** iPad23G, iPhone4S, iPadThirdGen4G, iPhone5, iPadFourthGen4G, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/94/30/b7/9430b72e-dccb-44cf-ea73-b92ca854e6b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22969950/95afedda-f370-11e6-8955-f626dcaab553.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22969950/95afedda-f370-11e6-8955-f626dcaab553.png)
https://cloud.githubusercontent.com/assets/2068130/22969950/95afedda-f370-11e6-8955-f626dcaab553.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22969963/a4c78832-f370-11e6-8391-702de033a977.png
