### ISSUE TITLE
README.md is on / when installed on device.

### ISSUE THREAD

**Issue by coolstar** [glasklart/hd#8876]
README.md is placed in / when the theme is installed off Cydia. Looks like the files aren't cleaned up properly before packaging...

**Comment by dreamnet** [comment]
@coolstar Yes. I'm just using Github's release function and submitting the link to the .zip to modmyi. They are making the package. Does the README.md hurt?

**Comment by coolstar** [comment]
@dreamnet yes, if another package on Cydia also has a README.md at /, that package will conflict with Glasklart due to both trying to write over the same file

**Comment by dreamnet** [comment]
… I hope, I have done this right ... :wink:

**Comment by tonehud** [comment]
Hi,

Thank you so much for the icons!!!!

Anthony Barrett
