### ISSUE TITLE
All  4

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8877]
**App Name:** All 4
**Bundle ID:** uk.co.channel4.ios.4od
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432494037">432494037</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/all-4/id432494037?uo=4">https://apps.apple.com/gb/app/all-4/id432494037?uo=4</a>
**App Version:** 8.3.1
**Seller:** Channel 4
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/channel-4/id385532930?uo=4">© Channel 4</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/17/5c/5e/175c5e84-7e70-06fd-2baa-b6646c1b1d01/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979307-5f930c80-95e6-11e9-9852-02ce00b9e28f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23036471/3aec6554-f483-11e6-8f83-2581902fab74.png)
https://cloud.githubusercontent.com/assets/2068130/23036471/3aec6554-f483-11e6-8f83-2581902fab74.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23036486/4d632fa6-f483-11e6-972e-9eb9dd1ebcc9.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979307-5f930c80-95e6-11e9-9852-02ce00b9e28f.png)
https://user-images.githubusercontent.com/2068130/59979307-5f930c80-95e6-11e9-9852-02ce00b9e28f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979314-7174af80-95e6-11e9-812d-e0233c7ab354.png
