### ISSUE TITLE
BT TV

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8879]
**App Name:** BT TV
**Bundle ID:** com.bt.tve
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=929166502">929166502</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/bt-tv/id929166502?mt=8&uo=4">https://itunes.apple.com/gb/app/bt-tv/id929166502?mt=8&uo=4</a>
**App Version:** 2.3.0
**Seller:** British Telecommunications plc
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/british-telecommunications/id373567642?uo=4">© British Telecommunications plc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/1f/33/22/1f332251-e26f-ea76-b0a6-381240a6c847/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22990881/dc917b2a-f3ba-11e6-8556-505fc10f4350.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22990881/dc917b2a-f3ba-11e6-8556-505fc10f4350.png)
https://cloud.githubusercontent.com/assets/2068130/22990881/dc917b2a-f3ba-11e6-8556-505fc10f4350.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22990894/ea7f29b2-f3ba-11e6-811e-dd8ff529071d.png
