### ISSUE TITLE
VideoBrowser

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8880]
**App Name:** VideoBrowser
**Bundle ID:** com.walnutsoft.VideoBrowser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=413488819">413488819</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/videobrowser/id413488819?mt=8&uo=4">https://itunes.apple.com/us/app/videobrowser/id413488819?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** Mahmut Akcay
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/walnutsoft/id340837683?uo=4">© WalnutSoft</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/5a/6b/d6/5a6bd686-97d7-728c-e26e-311ff2956ba4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23033233/966087c8-f477-11e6-8f3c-202012cd69cb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23033233/966087c8-f477-11e6-8f3c-202012cd69cb.png)
https://cloud.githubusercontent.com/assets/20930745/23033233/966087c8-f477-11e6-8f3c-202012cd69cb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23033257/a830c026-f477-11e6-8ed4-0b5f7ba5d50c.png
