### ISSUE TITLE
Redshift - Astronomy

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8881]
**App Name:** Redshift - Astronomy
**Bundle ID:** com.usm.redshift
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=390436752">390436752</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/redshift-astronomy/id390436752?mt=8&uo=4">https://itunes.apple.com/us/app/redshift-astronomy/id390436752?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** United Soft Media Verlag GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/usm/id330111789?uo=4">© USM</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/b8/3b/cb/b83bcb45-bb44-07b4-595e-914adae368c7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23028954/2b768510-f469-11e6-97f9-d993c063c77f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23028954/2b768510-f469-11e6-97f9-d993c063c77f.png)
https://cloud.githubusercontent.com/assets/2068130/23028954/2b768510-f469-11e6-97f9-d993c063c77f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23028974/3a231ee8-f469-11e6-870e-718d65d534ba.png
