### ISSUE TITLE
Met Office Weather Forecast

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8882]
**App Name:** Met Office Weather Forecast
**Bundle ID:** uk.gov.metoffice.weathercloud
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1068146838">1068146838</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/met-office-weather-forecast/id1068146838?mt=8&uo=4">https://itunes.apple.com/us/app/met-office-weather-forecast/id1068146838?mt=8&uo=4</a>
**App Version:** 1.8.1
**Seller:** Met Office
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/met-office/id331122089?uo=4">© Met Office</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/c0/ac/78/c0ac7871-2d30-fc34-19cd-3d61a4dd8aa1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22794621/15a70c16-eef4-11e6-9028-c323735dfc0b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22794621/15a70c16-eef4-11e6-9028-c323735dfc0b.png)
https://cloud.githubusercontent.com/assets/20930745/22794621/15a70c16-eef4-11e6-9028-c323735dfc0b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22794636/23714b4a-eef4-11e6-8664-e828144ccf03.png
