### ISSUE TITLE
BT Cloud

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8883]
**App Name:** BT Cloud
**Bundle ID:** com.bt.btcloud
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=595947986">595947986</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/bt-cloud/id595947986?mt=8&uo=4">https://itunes.apple.com/gb/app/bt-cloud/id595947986?mt=8&uo=4</a>
**App Version:** 15.2.82
**Seller:** British Telecommunications plc
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/british-telecommunications/id373567642?uo=4">© British Telecommunications plc</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/81/af/a1/81afa100-36a0-f415-2826-b8027e699834/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22794429/764e7186-eef3-11e6-9047-5c77ea14bd8c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22794429/764e7186-eef3-11e6-9047-5c77ea14bd8c.png)
https://cloud.githubusercontent.com/assets/20930745/22794429/764e7186-eef3-11e6-9047-5c77ea14bd8c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22794443/82522e64-eef3-11e6-8372-b83a27e3ec74.png
