### ISSUE TITLE
TopCashback (UK)

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8884]
**App Name:** TopCashback (UK)
**Bundle ID:** uk.co.topcashback.topcashback
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=408175694">408175694</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/topcashback-uk/id408175694?mt=8&uo=4">https://itunes.apple.com/gb/app/topcashback-uk/id408175694?mt=8&uo=4</a>
**App Version:** 7.8.310
**Seller:** TopCashback Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/topcashback-ltd./id408175697?uo=4">© TopCashback Ltd.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/25/e5/e6/25e5e69e-3596-f4fa-2f61-bfd76aeb0948/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22831221/dc2132d0-efa9-11e6-8e19-726a55bca454.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22830691/c201f2d8-efa7-11e6-8f8e-dba4ef2138d1.png)
https://cloud.githubusercontent.com/assets/20930745/22830691/c201f2d8-efa7-11e6-8f8e-dba4ef2138d1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22830710/d11399fc-efa7-11e6-87f9-d325f68033ea.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22831221/dc2132d0-efa9-11e6-8e19-726a55bca454.png)
https://cloud.githubusercontent.com/assets/20930745/22831221/dc2132d0-efa9-11e6-8e19-726a55bca454.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22831233/e7ba1544-efa9-11e6-89c1-b8dd5311a8d2.png
