### ISSUE TITLE
MTB Project

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8885]
**App Name:** MTB Project
**Bundle ID:** com.mtbproject.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=622364906">622364906</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mtb-project/id622364906?mt=8&uo=4">https://itunes.apple.com/us/app/mtb-project/id622364906?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Recreational Equipment, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/recreational-equipment-inc/id404849390?uo=4">© Recreational Equipment, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/d1/08/92/d1089217-f42d-0b23-476b-dfb4f68abfa1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22794186/9266bece-eef2-11e6-8ef5-f2cb64eb8a35.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22794186/9266bece-eef2-11e6-8ef5-f2cb64eb8a35.png)
https://cloud.githubusercontent.com/assets/20930745/22794186/9266bece-eef2-11e6-8ef5-f2cb64eb8a35.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22794203/a8225ab6-eef2-11e6-85a6-925b4dcb6c6b.png
