### ISSUE TITLE
OS Maps

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8886]
**App Name:** OS Maps
**Bundle ID:** uk.os.osmaps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=978307846">978307846</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/os-maps/id978307846?mt=8&uo=4">https://itunes.apple.com/us/app/os-maps/id978307846?mt=8&uo=4</a>
**App Version:** 1.8.0
**Seller:** Ordnance Survey
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ordnance-survey/id569517411?uo=4">© Ordnance Survey</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/27/db/99/27db9943-2201-b128-afd3-9abf5e535558/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22856478/30cd7c6a-f092-11e6-92d3-9b33de590531.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22793974/c23dcb34-eef1-11e6-894c-95f0704fa77d.png)
https://cloud.githubusercontent.com/assets/20930745/22793974/c23dcb34-eef1-11e6-894c-95f0704fa77d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22793983/cd6c495e-eef1-11e6-82a2-50a685505d75.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22830495/ff69d434-efa6-11e6-9f62-8d711a34c902.png)
https://cloud.githubusercontent.com/assets/20930745/22830495/ff69d434-efa6-11e6-9f62-8d711a34c902.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22830506/0dc78e4a-efa7-11e6-812d-c1660ae50531.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22856478/30cd7c6a-f092-11e6-92d3-9b33de590531.png)
https://cloud.githubusercontent.com/assets/2068130/22856478/30cd7c6a-f092-11e6-92d3-9b33de590531.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22856480/4642bf38-f092-11e6-9795-7c8578d2b3cb.png
