### ISSUE TITLE
My BT

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8887]
**App Name:** My BT
**Bundle ID:** com.bt.mybt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979618672">979618672</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/my-bt/id979618672?mt=8&uo=4">https://itunes.apple.com/gb/app/my-bt/id979618672?mt=8&uo=4</a>
**App Version:** 2.2.15
**Seller:** British Telecommunications plc
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/british-telecommunications/id373567642?uo=4">© British Telecommunications plc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/2a/62/09/2a62090a-00be-1104-24d4-93e65cf43d4e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22793421/120606d8-eef0-11e6-82b8-6ebc17a46c42.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22793421/120606d8-eef0-11e6-82b8-6ebc17a46c42.png)
https://cloud.githubusercontent.com/assets/20930745/22793421/120606d8-eef0-11e6-82b8-6ebc17a46c42.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22793435/1c9ede6c-eef0-11e6-9a8e-444ccc2afc3c.png
