### ISSUE TITLE
iON Camera

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8888]
*App Name:** iON Camera
**Bundle ID:** com.iontheaction.ActionCam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=501307356">501307356</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ion-camera/id501307356?mt=8&uo=4">https://itunes.apple.com/us/app/ion-camera/id501307356?mt=8&uo=4</a>
**App Version:** 4.4
**Seller:** WORLD WIDE LICENSES LIMITED
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ion-worldwide/id501287575?uo=4">© ION WorldWide</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/39/b4/66/39b46661-16c3-32dd-f987-d734e36cd4a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22793225/827c6250-eeef-11e6-9ff8-ffe976194e0c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22793225/827c6250-eeef-11e6-9ff8-ffe976194e0c.png)
https://cloud.githubusercontent.com/assets/20930745/22793225/827c6250-eeef-11e6-9ff8-ffe976194e0c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22793243/8fc8124c-eeef-11e6-84c4-fbcc524e95f6.png
