### ISSUE TITLE
Canon Camera Connect

### ISSUE THREAD

**Issue by tonehud** [glasklart/hd#8889]
**App Name:** Canon Camera Connect
**Bundle ID:** jp.co.canon.ic.cameraconnect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944097177">944097177</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/canon-camera-connect/id944097177?mt=8&uo=4">https://itunes.apple.com/us/app/canon-camera-connect/id944097177?mt=8&uo=4</a>
**App Version:** 2.0.12
**Seller:** Canon Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/canon-inc./id331269954?uo=4">© Canon Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/34/48/6c/34486c73-84a9-f423-c403-425aabc3210f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22989688/20abfe38-f3b7-11e6-9e54-79c7d1ddbd45.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22989688/20abfe38-f3b7-11e6-9e54-79c7d1ddbd45.png)
https://cloud.githubusercontent.com/assets/2068130/22989688/20abfe38-f3b7-11e6-9e54-79c7d1ddbd45.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22989704/2feaaa70-f3b7-11e6-8cd0-7edd33fdf154.png
