### ISSUE TITLE
My5 - Channel 5

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#889]
**App Name:** My5 - Channel 5
**Bundle ID:** com.channel5.demand5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=456000021">456000021</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/my5-channel-5/id456000021?mt=8&uo=4">https://itunes.apple.com/gb/app/my5-channel-5/id456000021?mt=8&uo=4</a>
**App Version:** 4.1.4
**Seller:** Channel 5 Broadcasting Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/channel-five/id391087841?uo=4>© Channel Five</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/ef/eb/34/efeb34ff-3ec5-778c-7847-9d666a5ca1f7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410378/25520fea-92eb-11e6-81d9-209beb4ffb02.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410378/25520fea-92eb-11e6-81d9-209beb4ffb02.png)
https://cloud.githubusercontent.com/assets/20930745/19410378/25520fea-92eb-11e6-81d9-209beb4ffb02.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19410382/3524c2f0-92eb-11e6-9018-8e6c7644ee88.png
