### ISSUE TITLE
All Hours

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8890]
**App Name:** All Hours
**Bundle ID:** com.northernspark.allhours
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1000983835">1000983835</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/all-hours/id1000983835?mt=8&uo=4">https://itunes.apple.com/us/app/all-hours/id1000983835?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Joe Barbour
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jbdesign/id360173956?uo=4">© JBDesign</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/22/df/07/22df07b8-bc49-083d-8d1b-de8d92df1a27/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22856556/005d2bc8-f094-11e6-81da-7ddbf514fafa.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22795004/5f1a783c-eef5-11e6-8bcb-faaff4d77751.png)
https://cloud.githubusercontent.com/assets/20930745/22795004/5f1a783c-eef5-11e6-8bcb-faaff4d77751.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22795018/6bace59e-eef5-11e6-8e15-0c609270bc99.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22856556/005d2bc8-f094-11e6-81da-7ddbf514fafa.png)
https://cloud.githubusercontent.com/assets/2068130/22856556/005d2bc8-f094-11e6-81da-7ddbf514fafa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22856560/1075df6e-f094-11e6-90a0-2864c43f14fd.png
