### ISSUE TITLE
LINE WEBTOON - Free digital comics

### ISSUE THREAD

**Issue by theyellingmute** [glasklart/hd#8891]
**App Name:** LINE WEBTOON - Free digital comics
**Bundle ID:** com.naver.linewebtoon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=894546091">894546091</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/line-webtoon-free-digital/id894546091?mt=8&uo=4">https://itunes.apple.com/us/app/line-webtoon-free-digital/id894546091?mt=8&uo=4</a>
**App Version:** 1.5.3
**Seller:** NAVER Corp.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/naver-corp./id311867731?uo=4">© NAVER Corp.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/b3/af/5a/b3af5ae1-6c41-4b4f-14b5-17f68bd3c58b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22792971/babde61c-eeee-11e6-8c99-fac96e9489c0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/22792971/babde61c-eeee-11e6-8c99-fac96e9489c0.png)
https://cloud.githubusercontent.com/assets/20930745/22792971/babde61c-eeee-11e6-8c99-fac96e9489c0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/22793004/cc245b02-eeee-11e6-8b6f-d9c3c87bd3b8.png
