### ISSUE TITLE
CSULB

### ISSUE THREAD

**Issue by theyellingmute** [glasklart/hd#8892]
**App Name:** CSULB
**Bundle ID:** com.desire2learn.directory.branded.campuslife.csulb.edu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=574018799">574018799</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/csulb/id574018799?uo=4">https://apps.apple.com/us/app/csulb/id574018799?uo=4</a>
**App Version:** 5.2.49
**Seller:** DUBLABS, LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dublabs-llc/id690921583?uo=4">© DUBLABS, LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/17/54/32/1754326f-b2e9-dbee-010f-c5517c1cb338/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60369290-6c9f6980-99f3-11e9-8470-c3652213dd40.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22856722/cfac36fa-f097-11e6-89c9-481c40287424.png)
https://cloud.githubusercontent.com/assets/2068130/22856722/cfac36fa-f097-11e6-89c9-481c40287424.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22856728/e0d75b6c-f097-11e6-84e6-8a9152b2c715.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60369290-6c9f6980-99f3-11e9-8470-c3652213dd40.png)
https://user-images.githubusercontent.com/2068130/60369290-6c9f6980-99f3-11e9-8470-c3652213dd40.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60369310-7b861c00-99f3-11e9-8ef0-61cf66b5f6d5.png
