### ISSUE TITLE
OTRLocation

### ISSUE THREAD

**Issue by sern19** [glasklart/hd#8893]
**App Name:** OTRLocation
**Bundle ID:** net.85819.ios.OTRLocation
**iTunes ID:** none (Cydia app)
**App Version:** 3.5.0
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/2068130/22856764/8dc20994-f098-11e6-8124-532e383fdfdd.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22856824/e0e2c0b8-f099-11e6-8d0c-5fbdf9a4bcf8.png)

**Comment by sern19** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/22792828/5e7d374a-eeee-11e6-8417-89265d7a9cd0.png)

Source:
https://cloud.githubusercontent.com/assets/23708258/22792798/424be468-eeee-11e6-8d3e-995a0392ccaf.png

**Comment by dreamnet** [comment]
@sern19 Just a little correction:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22856824/e0e2c0b8-f099-11e6-8d0c-5fbdf9a4bcf8.png)
https://cloud.githubusercontent.com/assets/2068130/22856824/e0e2c0b8-f099-11e6-8d0c-5fbdf9a4bcf8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22856825/f17dea60-f099-11e6-8b72-9e232e4981ac.png
Else: Great work!! 👍
