### ISSUE TITLE
Lords of the Fallen

### ISSUE THREAD

**Issue by sern19** [glasklart/hd#8894]
**App Name:** Lords of the Fallen
**Bundle ID:** com.cigames.lotfbof
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1176867432">1176867432</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lords-of-the-fallen/id1176867432?mt=8&uo=4">https://itunes.apple.com/us/app/lords-of-the-fallen/id1176867432?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** CI Games S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ci-games-s.a/id1176867431?uo=4">© CI GAMES S.A</a>
**Supported Devices:** iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/82/67/fa/8267fa68-e619-96ab-54dd-04b519e3c621/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23021020/1aa84b70-f44a-11e6-9b1a-6bab92254521.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23021020/1aa84b70-f44a-11e6-9b1a-6bab92254521.png)
https://cloud.githubusercontent.com/assets/2068130/23021020/1aa84b70-f44a-11e6-9b1a-6bab92254521.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23021025/28d06926-f44a-11e6-9f9b-fd75719075a3.png
