### ISSUE TITLE
Apple News

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8895]
**App Name:** Apple News
**Bundle ID:** com.apple.news
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1066498020">1066498020</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/apple-news/id1066498020?mt=8&uo=4">https://itunes.apple.com/us/app/apple-news/id1066498020?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/b0/ee/a7/b0eea7b3-e341-5f73-7546-b1c21e8f9525/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22860407/2b4dc7f2-f0fd-11e6-8b18-baf0f5837d78.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22860407/2b4dc7f2-f0fd-11e6-8b18-baf0f5837d78.png)
https://cloud.githubusercontent.com/assets/2068130/22860407/2b4dc7f2-f0fd-11e6-8b18-baf0f5837d78.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22860409/39adcb1c-f0fd-11e6-8ef4-ed705d8982e4.png
