### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8896]
**App Name:** Home
**Bundle ID:** com.apple.Home
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1110145103">1110145103</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/home/id1110145103?mt=8&uo=4">https://itunes.apple.com/us/app/home/id1110145103?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/21/e9/b0/21e9b002-80bd-8f58-e10d-4f7f1ee4ed2b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22860064/157f025c-f0f2-11e6-8554-02e16c77ced8.png)

**Comment by TheRyanKing** [comment]
![glasklart home icon](https://cloud.githubusercontent.com/assets/10021829/22859764/f1b727fa-f0b5-11e6-85a6-67fed681d2ab.png)

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/22859757/c38ba036-f0b5-11e6-82df-9365836c93ac.png)

![source home icon](https://cloud.githubusercontent.com/assets/10021829/22859767/fd0ab07c-f0b5-11e6-825b-c4c2a538552e.png)

**Comment by dreamnet** [comment]
...on second thought, the Glasklart icon needs to be pushed up a bit, just like the original:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22860064/157f025c-f0f2-11e6-8554-02e16c77ced8.png)
https://cloud.githubusercontent.com/assets/2068130/22860064/157f025c-f0f2-11e6-8554-02e16c77ced8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22860066/268145ce-f0f2-11e6-88a4-4f2d733f2070.png
Credits are going to @TheRyanKing anyway.
