### ISSUE TITLE
iTunes Store

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8898]
**App Name:** iTunes Store
**Bundle ID:** com.apple.MobileStore
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=915061235">915061235</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/itunes-store/id915061235?mt=8&uo=4">https://itunes.apple.com/us/app/itunes-store/id915061235?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/32/8d/3b/328d3b6f-5f16-090b-54be-c9afcaa934a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31316042-4d1a5678-ac25-11e7-8e83-2dd875dab870.png)

**Comment by dreamnet** [comment]
![com apple mobilestore-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864117/ca9e7b00-f14b-11e6-97c1-195c82b771f0.png)
https://cloud.githubusercontent.com/assets/2068130/22864117/ca9e7b00-f14b-11e6-97c1-195c82b771f0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864119/dc6642e6-f14b-11e6-8d4f-cb17b924557a.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.MobileStore-large.png). No further action needed.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31316042-4d1a5678-ac25-11e7-8e83-2dd875dab870.png)
https://user-images.githubusercontent.com/2068130/31316042-4d1a5678-ac25-11e7-8e83-2dd875dab870.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31316045-5d2a273c-ac25-11e7-87e0-e1de0c201ce8.png
