### ISSUE TITLE
Apple TV

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8899]
**App Name:** Apple TV
**Bundle ID:** com.apple.tv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1174078549">1174078549</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/apple-tv/id1174078549?uo=4">https://apps.apple.com/us/app/apple-tv/id1174078549?uo=4</a>
**App Version:** 1.3.9
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/db/da/f9/dbdaf99a-94f3-169d-0816-55ae405c9f07/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69466429-50c2a880-0d84-11ea-8489-efae3aba7b17.png)

**Comment by TheRyanKing** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10021829/22865685/66f76440-f137-11e6-85c2-578b21077de8.png

https://cloud.githubusercontent.com/assets/10021829/22865687/7334a3bc-f137-11e6-9050-650be783ecf2.png

https://cloud.githubusercontent.com/assets/10021829/22865691/7b542888-f137-11e6-9b45-95a1d7418fed.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/69466429-50c2a880-0d84-11ea-8489-efae3aba7b17.png)
https://user-images.githubusercontent.com/2068130/69466429-50c2a880-0d84-11ea-8489-efae3aba7b17.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/69466460-620bb500-0d84-11ea-8c82-f5996bd9d3bc.png
