### ISSUE TITLE
Eurosport Player

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#890]
**App Name:** Eurosport Player
**Bundle ID:** com.eurosport.player
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=339708430">339708430</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/eurosport-player/id339708430?uo=4">https://apps.apple.com/gb/app/eurosport-player/id339708430?uo=4</a>
**App Version:** 6.5.2
**Seller:** Eurosport SA
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/eurosport/id324021129?uo=4">© Eurosport</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/3b/a8/d7/3ba8d7aa-8122-4bc7-a6ef-ff99cf169b57/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60386938-7204be80-9a9c-11e9-8b6f-bafb216abce8.png)

**Comment by Trubbel** [comment]
Icon has been updated.

**Comment by ivanov007** [comment]
@Trubbel wow I don't know how you managed to find this issue since it had so few details, but thanks, I've updated the description so it shows the new original artwork

**Comment by Trubbel** [comment]
@ivanov007 It was the artwork crawler that helped me.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8145674/bb1e6214-1211-11e5-9b29-37343d47e19c.png)
https://cloud.githubusercontent.com/assets/2068130/8145674/bb1e6214-1211-11e5-9b29-37343d47e19c.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8145676/ce55e618-1211-11e5-84d8-5b309040d411.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60386938-7204be80-9a9c-11e9-8b6f-bafb216abce8.png)
https://user-images.githubusercontent.com/2068130/60386938-7204be80-9a9c-11e9-8b6f-bafb216abce8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60386941-821c9e00-9a9c-11e9-87f1-2953716e0292.png
