### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8900]
**App Name:** Maps
**Bundle ID:** com.apple.Maps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=915056765">915056765</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/maps/id915056765?mt=8&uo=4">https://itunes.apple.com/us/app/maps/id915056765?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/16/a1/83/16a1839a-958f-7ca6-acd1-6473ee88a386/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple maps-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864192/1ef3149e-f14d-11e6-8c79-a16bf21990f7.png)

**Comment by dreamnet** [comment]
![com apple maps-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864192/1ef3149e-f14d-11e6-8c79-a16bf21990f7.png)
https://cloud.githubusercontent.com/assets/2068130/22864192/1ef3149e-f14d-11e6-8c79-a16bf21990f7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864197/32665680-f14d-11e6-853d-2fe5e8961ab9.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.Maps-large.png). No further action needed.
