### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8901]
**App Name:** Compass
**Bundle ID:** com.apple.compass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1067456176">1067456176</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/compass/id1067456176?mt=8&uo=4">https://itunes.apple.com/us/app/compass/id1067456176?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone4S, iPhone5, iPhone5c, iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/77/c5/aa/77c5aadf-090b-7fd5-eb14-95cc6b79c03a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple compass-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864211/a014290a-f14d-11e6-9661-63e33e2761fb.png)

**Comment by dreamnet** [comment]
![com apple compass-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864211/a014290a-f14d-11e6-9661-63e33e2761fb.png)
https://cloud.githubusercontent.com/assets/2068130/22864211/a014290a-f14d-11e6-9661-63e33e2761fb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864215/b30871b0-f14d-11e6-8524-76791eac09ee.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.compass-large.png). No further action needed.
