### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8903]
**App Name:** Calculator
**Bundle ID:** com.apple.calculator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1069511488">1069511488</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calculator/id1069511488?mt=8&uo=4">https://itunes.apple.com/us/app/calculator/id1069511488?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone5-iPhone5, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/6c/e2/4a/6ce24a11-0286-b7a8-f168-341b44641328/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31318924-7ea5a2b2-ac5a-11e7-90a8-b995e533b6ad.png)

**Comment by dreamnet** [comment]
![com apple calculator-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864361/5ff18e78-f150-11e6-9a65-289eafed637f.png)
https://cloud.githubusercontent.com/assets/2068130/22864361/5ff18e78-f150-11e6-9a65-289eafed637f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864367/6f20b248-f150-11e6-98cd-23a1c7728c66.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.calculator-large.png). No further action needed.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31318924-7ea5a2b2-ac5a-11e7-90a8-b995e533b6ad.png)
https://user-images.githubusercontent.com/2068130/31318924-7ea5a2b2-ac5a-11e7-90a8-b995e533b6ad.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31318927-8d36a218-ac5a-11e7-90bc-cbfc45807731.png
