### ISSUE TITLE
Voice Memos

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8904]
**App Name:** Voice Memos
**Bundle ID:** com.apple.VoiceMemos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1069512134">1069512134</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/voice-memos/id1069512134?mt=8&uo=4">https://itunes.apple.com/us/app/voice-memos/id1069512134?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/2d/e9/c2/2de9c2ac-b3de-d4b2-6d07-0525267d66fd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple voicememos-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864399/1b4526b2-f151-11e6-93f9-9991b7da0d0e.png)

**Comment by dreamnet** [comment]
![com apple voicememos-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864399/1b4526b2-f151-11e6-93f9-9991b7da0d0e.png)
https://cloud.githubusercontent.com/assets/2068130/22864399/1b4526b2-f151-11e6-93f9-9991b7da0d0e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864404/2ded9cf4-f151-11e6-8aad-e01118627a1d.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.VoiceMemos-large.png). No further action needed.
