### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8905]
**App Name:** Contacts
**Bundle ID:** com.apple.MobileAddressBook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1069512615">1069512615</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/contacts/id1069512615?uo=4">https://apps.apple.com/us/app/contacts/id1069512615?uo=4</a>
**App Version:** 1.3.3
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/3c/c4/49/3cc4496b-7ed0-ccd9-3b5c-e543c5c744bf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68886876-46673580-0718-11ea-9dbe-51ae986d29f4.png)

**Comment by dreamnet** [comment]
![com apple mobileaddressbook-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864431/a6509886-f151-11e6-82de-2b4cfaf4246e.png)
https://cloud.githubusercontent.com/assets/2068130/22864431/a6509886-f151-11e6-82de-2b4cfaf4246e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864437/b9591868-f151-11e6-95c4-100c437c4531.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.MobileAddressBook-large.png). No further action needed.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31318979-6b2017da-ac5b-11e7-8e9b-7dc9c8592273.png)
https://user-images.githubusercontent.com/2068130/31318979-6b2017da-ac5b-11e7-8e9b-7dc9c8592273.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31318986-7a1f1704-ac5b-11e7-9963-201322fb2ddf.png

**Comment by 2Qt2beStr8** [comment]
iOS 13 Contacts Icon

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/68886876-46673580-0718-11ea-9dbe-51ae986d29f4.png)
https://user-images.githubusercontent.com/20930745/68886876-46673580-0718-11ea-9dbe-51ae986d29f4.png

Source:
https://user-images.githubusercontent.com/20930745/68886879-48c98f80-0718-11ea-89f0-3e6f95e2487a.png
