### ISSUE TITLE
Stocks

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8906]
**App Name:** Stocks
**Bundle ID:** com.apple.stocks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1069512882">1069512882</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stocks/id1069512882?mt=8&uo=4">https://itunes.apple.com/us/app/stocks/id1069512882?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/09/98/aa/0998aa6a-b5e6-61a2-ac36-628b5c87ed46/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple stocks-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864454/2b0f7a4c-f152-11e6-9862-f03719c5f6dc.png)

**Comment by dreamnet** [comment]
![com apple stocks-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864454/2b0f7a4c-f152-11e6-9862-f03719c5f6dc.png)
https://cloud.githubusercontent.com/assets/2068130/22864454/2b0f7a4c-f152-11e6-9862-f03719c5f6dc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864457/3cb12e3a-f152-11e6-9716-b4b8421088f8.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.stocks-large.png). No further action needed.
