### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8907]
**App Name:** Weather
**Bundle ID:** com.apple.weather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1069513131">1069513131</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather/id1069513131?mt=8&uo=4">https://itunes.apple.com/us/app/weather/id1069513131?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPhone4S, iPhone5, iPodTouchFifthGen, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/ab/da/5a/abda5aff-2ae1-e1c4-1cf5-5b34245a987c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple weather-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864480/9e5b1e3e-f152-11e6-88a0-8dc13e1abf94.png)

**Comment by dreamnet** [comment]
![com apple weather-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864480/9e5b1e3e-f152-11e6-88a0-8dc13e1abf94.png)
https://cloud.githubusercontent.com/assets/2068130/22864480/9e5b1e3e-f152-11e6-88a0-8dc13e1abf94.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864486/b0d9567a-f152-11e6-859a-3a2f04ecab81.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.weather-large.png). No further action needed.
