### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8908]
**App Name:** Mail
**Bundle ID:** com.apple.mobilemail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1108187098">1108187098</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mail/id1108187098?mt=8&uo=4">https://itunes.apple.com/us/app/mail/id1108187098?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple41/v4/d4/6c/35/d46c354f-eadf-f551-d167-138ef278feb6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple mobilemail-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864512/1def0df4-f153-11e6-892c-c63e7c5108a3.png)

**Comment by dreamnet** [comment]
![com apple mobilemail-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864512/1def0df4-f153-11e6-892c-c63e7c5108a3.png)
https://cloud.githubusercontent.com/assets/2068130/22864512/1def0df4-f153-11e6-892c-c63e7c5108a3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864517/2fb927f4-f153-11e6-9985-82b19970a6e3.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.mobilemail-large.png). No further action needed.
