### ISSUE TITLE
Apple Music

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8909]
**App Name:** Apple Music
**Bundle ID:** com.apple.Music
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1108187390">1108187390</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/apple-music/id1108187390?mt=8&uo=4">https://itunes.apple.com/us/app/apple-music/id1108187390?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/48/f1/a4/48f1a476-1d2f-9e25-ac16-89ffbc1c5331/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple music-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864538/ae9b6d84-f153-11e6-818e-492f968db77c.png)

**Comment by dreamnet** [comment]
![com apple music-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864538/ae9b6d84-f153-11e6-818e-492f968db77c.png)
https://cloud.githubusercontent.com/assets/2068130/22864538/ae9b6d84-f153-11e6-818e-492f968db77c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864543/c1680e86-f153-11e6-8ff5-8b1e35d98ced.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.Music-large.png). No further action needed.
