### ISSUE TITLE
tivizen DVB-T Wi-Fi

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#891]
**App Name:** tivizen DVB-T Wi-Fi
**Bundle ID:** com.valups.dvbt-e-wifi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=461760628">461760628</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tivizen-dvb-t-wi-fi/id461760628?mt=8&uo=4">https://itunes.apple.com/us/app/tivizen-dvb-t-wi-fi/id461760628?mt=8&uo=4</a>
**App Version:** 1.0.6108
**Seller:** Aprotech Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/aprotech-co.-ltd./id931374150?uo=4">© Aprotech Co., Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple6/v4/e6/bc/c4/e6bcc4d2-859b-f4a0-0b9f-2e73726bdbe6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19901768/8c0c5ca6-a068-11e6-9bb3-482f9cd64ff1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19901768/8c0c5ca6-a068-11e6-9bb3-482f9cd64ff1.png)
![](https://cloud.githubusercontent.com/assets/20930745/19901768/8c0c5ca6-a068-11e6-9bb3-482f9cd64ff1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19901822/baa243be-a068-11e6-9cf7-e8e2f0091531.png
