### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8910]
**App Name:** Reminders
**Bundle ID:** com.apple.reminders
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1108187841">1108187841</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reminders/id1108187841?mt=8&uo=4">https://itunes.apple.com/us/app/reminders/id1108187841?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/ed/3a/dc/ed3adc31-175e-3eee-619c-50eadd14c0d2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple reminders-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864568/2e41e2d4-f154-11e6-8abd-ee958a9e0e62.png)

**Comment by dreamnet** [comment]
![com apple reminders-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864568/2e41e2d4-f154-11e6-8abd-ee958a9e0e62.png)
https://cloud.githubusercontent.com/assets/2068130/22864568/2e41e2d4-f154-11e6-8abd-ee958a9e0e62.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864575/40448a36-f154-11e6-86c2-a4d356a2c4ac.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.reminders-large.png). No further action needed.
