### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8911]
**App Name:** Videos
**Bundle ID:** com.apple.videos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1108188158">1108188158</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/videos/id1108188158?mt=8&uo=4">https://itunes.apple.com/us/app/videos/id1108188158?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/c1/57/1b/c1571b24-996b-1ecf-9661-3ceeed075bc8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple videos-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864595/a13993b8-f154-11e6-9779-b71d1ad664f2.png)

**Comment by dreamnet** [comment]
![com apple videos-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864595/a13993b8-f154-11e6-9779-b71d1ad664f2.png)
https://cloud.githubusercontent.com/assets/2068130/22864595/a13993b8-f154-11e6-9779-b71d1ad664f2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864597/b264be60-f154-11e6-8a13-9d62f7033616.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.videos-large.png). No further action needed.
