### ISSUE TITLE
FaceTime

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8912]
**App Name:** FaceTime
**Bundle ID:** com.apple.facetime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1110145091">1110145091</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/facetime/id1110145091?mt=8&uo=4">https://itunes.apple.com/us/app/facetime/id1110145091?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple42/v4/ee/45/f9/ee45f975-ea48-b1c0-a150-ddcb40efc50f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple facetime-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864617/13593b10-f155-11e6-90f6-7440677ac89b.png)

**Comment by dreamnet** [comment]
![com apple facetime-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864617/13593b10-f155-11e6-90f6-7440677ac89b.png)
https://cloud.githubusercontent.com/assets/2068130/22864617/13593b10-f155-11e6-90f6-7440677ac89b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864620/24e8f528-f155-11e6-9747-0de40258c750.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.facetime-large.png). No further action needed.
