### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8913]
**App Name:** Notes
**Bundle ID:** com.apple.mobilenotes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1110145109">1110145109</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/notes/id1110145109?mt=8&uo=4">https://itunes.apple.com/us/app/notes/id1110145109?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Apple Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apple/id284417353?mt=12&uo=4">© Apple</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/69/7f/4f/697f4f73-cca1-e080-5851-08f96114269f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com apple mobilenotes-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864640/a1a4094a-f155-11e6-9dfd-8645d348fb98.png)

**Comment by TheRyanKing** [comment]
Icon: (https://cloud.githubusercontent.com/assets/10021829/22863431/e35c48f4-f10d-11e6-9b37-76c3ab07f1a4.png)

![](http://preview.dreamnet.at/?image=
![notes glasklart](https://cloud.githubusercontent.com/assets/10021829/22863435/ea4c0956-f10d-11e6-828b-fb116088f57b.png)

Source: (https://cloud.githubusercontent.com/assets/10021829/22863442/f660ef40-f10d-11e6-925d-f3d7a2e6ddf1.png)

**Comment by dreamnet** [comment]
![com apple mobilenotes-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/22864640/a1a4094a-f155-11e6-9dfd-8645d348fb98.png)
https://cloud.githubusercontent.com/assets/2068130/22864640/a1a4094a-f155-11e6-9dfd-8645d348fb98.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/22864645/b2aae6f0-f155-11e6-8ccd-cbd5fa0b23e5.png

**Comment by dreamnet** [comment]
Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.apple.mobilenotes-large.png). No further action needed.
