### ISSUE TITLE
Tapatalk Pro

### ISSUE THREAD

**Issue by bepebe** [glasklart/hd#892]
**App Name:** Tapatalk Pro
**Bundle ID:** com.quoord.Tapatalk2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=585178888">585178888</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tapatalk-pro/id585178888?mt=8&uo=4">https://itunes.apple.com/us/app/tapatalk-pro/id585178888?mt=8&uo=4</a>
**App Version:** 6.2
**Seller:** Tapatalk, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/tapatalk/id717545832?uo=4>© Tapatalk</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/68/6b/b4/686bb453-a14a-6e99-1b15-1b6ac60c2751/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19384628/77ff2d2c-920a-11e6-9006-5314aa202999.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19384628/77ff2d2c-920a-11e6-9006-5314aa202999.png)
https://cloud.githubusercontent.com/assets/20930745/19384628/77ff2d2c-920a-11e6-9006-5314aa202999.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19384642/89c955c8-920a-11e6-9a31-7f0e09387236.png
