### ISSUE TITLE
CertRemainTime

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8924]
**App Name:** CertRemainTime
 **Bundle ID:** fr.lululombard.certremaintime
 **Version:** 2.1.1
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/10730122/22905189/b4adc63a-f23f-11e6-99cf-733173fa86bd.jpg" width="180" height="180" />
 **Accepted Artwork:**
 ![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22955873/e83cdb3c-f31e-11e6-9483-4c30a4d0f502.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22955798/76742fd2-f31e-11e6-8415-dc09e99ec497.png)
https://cloud.githubusercontent.com/assets/10730122/22955798/76742fd2-f31e-11e6-8415-dc09e99ec497.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/22955797/7659462c-f31e-11e6-972d-c544df345617.png

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22955873/e83cdb3c-f31e-11e6-9483-4c30a4d0f502.png)
https://cloud.githubusercontent.com/assets/10730122/22955873/e83cdb3c-f31e-11e6-9483-4c30a4d0f502.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/22955871/e821c734-f31e-11e6-8e00-5727e1c1d442.png

**Comment by TheRyanKing** [comment]
@Trubbel How do you create the transparent stroke around the ribbon? To separate the paper from the ribbon?

**Comment by Trubbel** [comment]
@TheRyanKing I basically just duplicated the artwork and used the `Magic Wand Tool` and selected the yellow part of the ribbon then pressed `Ctrl+Shift+I` to inverse the selection and deleted the selected part, which leaves you with just the yellow part.

After that you go to `Blending Options` > `Stroke` changed the stroke size to 8 and the position to outside.
Then press the `Blending Options tab` *(same window)* and set the `Fill Opacity` to `0`. Press OK.

Right click on Layer 2 in the bottom right window and press `Rasterize Layer Style`.
Now click on Layer 1 and then hold down `Ctrl` and left click Layer 2s thumbnail *(the image window)* and press `Delete`.

Now you can just delete the yellow ribbon part you cut out.

**Comment by ivanov007** [comment]
@Trubbel @TheRyanKing I do something like that but without duplicating, I guess it's a little simpler:
with the `Magic Wand Tool (W)` select the yellow part of the ribbon then with the marquee tool (M) right click on the working area and click `Stroke`(or `Edit` > `Stroke...`) change stroke size to 8 and `Location` to outside, on `Blending` Mode: Normal Opacity:100%
again with the `Magic Wand Tool (W)` select the stroke just created, press `Delete` and you will have the space between the ribbon and the paper, also you can play with the `Location` option, sometimes center look better than outside

**Comment by Trubbel** [comment]
@ivanov007 I have never thought about doing it that way before, but yeah that's much more simple than the way I'm doing it.
