### ISSUE TITLE
ZEDGE™ Wallpapers

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8925]
**App Name:** ZEDGE™ Wallpapers
**Bundle ID:** net.zedge.wallpapers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1086101495">1086101495</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zedge-wallpapers/id1086101495?mt=8&uo=4">https://itunes.apple.com/us/app/zedge-wallpapers/id1086101495?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Zedge Holdings Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zedge/id584485874?uo=4">© ZEDGE</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple82/v4/79/59/8c/79598cc8-190d-fa95-e16c-7443aa900917/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22905677/75e5fef2-f241-11e6-800f-3d837de92bea.png)

**Comment by Trubbel** [comment]
@dreamnet Should we use the same icon as #2129?

**Comment by dreamnet** [comment]
@Trubbel Your icon, your decision. I have no feelings about this, becuse I don't use these apps. You can mark the icons with an R and an W if you want, or write the words Ringtones and Wallpapers in it.....

**Comment by Trubbel** [comment]
I guess we can go with #2129 then.
Because their names on SpringBoard are literally `Ringtones` and `Wallpapers`. *[How it looks like](https://cloud.githubusercontent.com/assets/10730122/22956320/9699501e-f321-11e6-874a-67137848d5f8.png)*

So it would be redundant to have it look like this *(mock-up)*;
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22956345/c0fb5ad2-f321-11e6-970f-880ce806fa01.png) ![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22956346/c0fbe510-f321-11e6-9b91-0654a38988da.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/22905677/75e5fef2-f241-11e6-800f-3d837de92bea.png)
https://cloud.githubusercontent.com/assets/10730122/22905677/75e5fef2-f241-11e6-800f-3d837de92bea.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/10384354/4776a7e2-6e3a-11e5-9b11-5b1c41a21652.png
