### ISSUE TITLE
Sears – Download Now, Shop Online & Pick Up Today!

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8927]
**App Name:** Sears – Download Now, Shop Online & Pick Up Today!
**Bundle ID:** com.sears.Sears2go
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=305449194">305449194</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sears-download-now-shop-online/id305449194?mt=8&uo=4">https://itunes.apple.com/us/app/sears-download-now-shop-online/id305449194?mt=8&uo=4</a>
**App Version:** 13.1
**Seller:** Sears Holdings Management Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sears/id295864004?uo=4">© Sears</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/eb/af/ae/ebafaecc-62dc-bcee-4177-0fbda2065e6b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011611/41a76e72-f422-11e6-8511-dd60c5062849.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011611/41a76e72-f422-11e6-8511-dd60c5062849.png)
https://cloud.githubusercontent.com/assets/2068130/23011611/41a76e72-f422-11e6-8511-dd60c5062849.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23011621/554d1a6c-f422-11e6-96a6-0342f51f5412.png
