### ISSUE TITLE
Q&A Hotel

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8928]
**App Name:** Q&A Hotel
**Bundle ID:** com.intelitycorp.iceios.qanda-residential
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1049447246">1049447246</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/q-a-hotel/id1049447246?mt=8&uo=4">https://itunes.apple.com/us/app/q-a-hotel/id1049447246?mt=8&uo=4</a>
**App Version:** 3.5.1
**Seller:** Intelity
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/intelity-solutions/id366153476?uo=4">© Intelity Solutions</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/03/90/d3/0390d303-2ffc-5be0-b632-cd0f9a2a2de0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011863/8211a9fe-f423-11e6-9147-33c4ff7084cd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011863/8211a9fe-f423-11e6-9147-33c4ff7084cd.png)
https://cloud.githubusercontent.com/assets/2068130/23011863/8211a9fe-f423-11e6-9147-33c4ff7084cd.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23011872/8f666676-f423-11e6-8968-801dd45b12ab.png
