### ISSUE TITLE
Krazy Coupon Lady | Grocery Coupons & Deals

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8929]
**App Name:** Krazy Coupon Lady | Grocery Coupons & Deals
**Bundle ID:** com.thekrazycouponlady.Krazy-Coupon-Lady
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=962133447">962133447</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/krazy-coupon-lady-grocery/id962133447?mt=8&uo=4">https://itunes.apple.com/us/app/krazy-coupon-lady-grocery/id962133447?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** Krazy Coupon Lady LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/krazy-coupon-ladies/id616079866?uo=4">© Krazy Coupon Ladies</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/cf/90/40/cf9040f8-8cdb-25cc-5929-2da7e1393df4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011955/08308dde-f424-11e6-8adb-12b7c1f34a7c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011955/08308dde-f424-11e6-8adb-12b7c1f34a7c.png)
https://cloud.githubusercontent.com/assets/2068130/23011955/08308dde-f424-11e6-8adb-12b7c1f34a7c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23011962/1636ea0e-f424-11e6-8e3a-53caedb38b22.png
