### ISSUE TITLE
1-800-Flowers.com: Gifts & Flowers Delivery

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8930]
**App Name:** 1-800-Flowers.com: Gifts & Flowers Delivery
**Bundle ID:** com.1800flowers.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=457699767">457699767</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1-800-flowers.com-gifts-flowers/id457699767?mt=8&uo=4">https://itunes.apple.com/us/app/1-800-flowers.com-gifts-flowers/id457699767?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** 1800 Flowers
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/flowers/id457699770?uo=4">© Flowers</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/f1/8d/d7/f18dd77c-d612-a722-f7b9-02a4d9ea8f3d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011213/fe0cdfaa-f41f-11e6-810a-ab7a77f389b3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011213/fe0cdfaa-f41f-11e6-810a-ab7a77f389b3.png)
https://cloud.githubusercontent.com/assets/2068130/23011213/fe0cdfaa-f41f-11e6-810a-ab7a77f389b3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23011219/0d361fa0-f420-11e6-9aa0-93aabfc9b265.png
