### ISSUE TITLE
Woot: Shop daily deals and have a laugh

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8931]
**App Name:** Woot: Shop daily deals and have a laugh
**Bundle ID:** com.woot.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571457538">571457538</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/woot-shop-daily-deals-have/id571457538?mt=8&uo=4">https://itunes.apple.com/us/app/woot-shop-daily-deals-have/id571457538?mt=8&uo=4</a>
**App Version:** 3.4.3
**Seller:** Woot Mobile LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/woot-mobile-llc/id571457541?uo=4">© Woot Mobile LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/fb/31/06/fb310677-d22b-908f-c810-785f1b5143ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011286/71e5a4c0-f420-11e6-9df2-fdd52db850c9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011286/71e5a4c0-f420-11e6-9df2-fdd52db850c9.png)
https://cloud.githubusercontent.com/assets/2068130/23011286/71e5a4c0-f420-11e6-9df2-fdd52db850c9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23011301/8064006e-f420-11e6-9798-8cd0fbd05d4b.png
