### ISSUE TITLE
Hiatus: Bill and Money Manager

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8932]
**App Name:** Hiatus: Bill and Money Manager
**Bundle ID:** com.TG.hiatus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=977040079">977040079</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hiatus-bill-and-money-manager/id977040079?uo=4">https://apps.apple.com/us/app/hiatus-bill-and-money-manager/id977040079?uo=4</a>
**App Version:** 3.2.7
**Seller:** Hiatus LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hiatus-llc/id977040078?uo=4">© Hiatus LLC</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/84/2f/6e/842f6e3e-166b-a882-0f9b-8c4a99b1c48f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772986-5fbefc00-a0fe-11e9-86c7-834d732e4766.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011732/e3a5a4d2-f422-11e6-8cfb-c33611e619a4.png)
https://cloud.githubusercontent.com/assets/2068130/23011732/e3a5a4d2-f422-11e6-8cfb-c33611e619a4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23011740/f49b4dd2-f422-11e6-9b3a-531fbd37b407.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60772986-5fbefc00-a0fe-11e9-86c7-834d732e4766.png)
https://user-images.githubusercontent.com/2068130/60772986-5fbefc00-a0fe-11e9-86c7-834d732e4766.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60772990-6fd6db80-a0fe-11e9-998d-56e1c9db5ffd.png
