### ISSUE TITLE
Weight GURUS

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8933]
**App Name:** Weight GURUS
**Bundle ID:** com.gurus.weight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526207936">526207936</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weight-gurus/id526207936?mt=8&uo=4">https://itunes.apple.com/us/app/weight-gurus/id526207936?mt=8&uo=4</a>
**App Version:** 2.13.1
**Seller:** Design Maufacture Distribution, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gurus/id526207939?uo=4">© GURUS</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/06/36/12/0636125c-5137-5804-8ff4-1e19084e9036/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011493/9153ed7a-f421-11e6-8195-168c2bbd65e8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011493/9153ed7a-f421-11e6-8195-168c2bbd65e8.png)
https://cloud.githubusercontent.com/assets/2068130/23011493/9153ed7a-f421-11e6-8195-168c2bbd65e8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23011503/9efeb590-f421-11e6-9ade-5aabdb239827.png
