### ISSUE TITLE
Lovense Remote

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8934]
**App Name:** Lovense Remote
**Bundle ID:** com.lovense.wear
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1027312824">1027312824</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/lovense-remote/id1027312824?uo=4">https://apps.apple.com/us/app/lovense-remote/id1027312824?uo=4</a>
**App Version:** 3.4.7
**Seller:** Hytto
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hytto-ltd/id424428586?uo=4">© Hytto Ltd.</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/ad/bc/05/adbc0593-576c-e2eb-b835-660724355b7a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62441894-3f627b80-b756-11e9-8158-62a064bca603.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23011390/0ade20e4-f421-11e6-9be9-6869b22cf334.png)
https://cloud.githubusercontent.com/assets/2068130/23011390/0ade20e4-f421-11e6-9be9-6869b22cf334.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23011406/183329a6-f421-11e6-99f1-ff90d7933433.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/62441894-3f627b80-b756-11e9-8158-62a064bca603.png)
https://user-images.githubusercontent.com/2068130/62441894-3f627b80-b756-11e9-8158-62a064bca603.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/62441915-4ee1c480-b756-11e9-94db-17fdfafef629.png
