### ISSUE TITLE
Body Chat

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8935]
**App Name:** Body Chat
**Bundle ID:** com.lovense.couple
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=726879092">726879092</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/body-chat/id726879092?mt=8&uo=4">https://itunes.apple.com/us/app/body-chat/id726879092?mt=8&uo=4</a>
**App Version:** 2.9.3
**Seller:** Hytto
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hytto-ltd./id424428586?uo=4">© Hytto Ltd.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/11/15/c4/1115c4b8-e3ca-e03c-d0fe-06be6d1fb6e1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23010692/28d91846-f41d-11e6-9b11-a0aa51438cd2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23010692/28d91846-f41d-11e6-9b11-a0aa51438cd2.png)
https://cloud.githubusercontent.com/assets/2068130/23010692/28d91846-f41d-11e6-9b11-a0aa51438cd2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23010705/376b1e9a-f41d-11e6-948f-661fa49f8e8e.png
