### ISSUE TITLE
Paribus - Rebates When Prices Drop

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8936]
**App Name:** Paribus - Rebates When Prices Drop
**Bundle ID:** paribus.Paribus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943587620">943587620</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paribus-rebates-when-prices/id943587620?mt=8&uo=4">https://itunes.apple.com/us/app/paribus-rebates-when-prices/id943587620?mt=8&uo=4</a>
**App Version:** 2.7.2
**Seller:** Paribus Co
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/paribus-co/id943587619?uo=4">© Paribus Co</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/7a/34/24/7a34245e-f6a4-57e4-4ba0-bb49501c224a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23012513/e9de4698-f426-11e6-8f70-a86c558a7f19.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23012513/e9de4698-f426-11e6-8f70-a86c558a7f19.png)
https://cloud.githubusercontent.com/assets/2068130/23012513/e9de4698-f426-11e6-8f70-a86c558a7f19.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23012523/f7e2e00a-f426-11e6-8082-9ac02e05bef3.png
