### ISSUE TITLE
Bubble Level FREE for iPhone

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8937]
**App Name:** Bubble Level FREE for iPhone
**Bundle ID:** com.lemondoo.BubbleLevel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=465613917">465613917</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bubble-level-free-for-iphone/id465613917?mt=8&uo=4">https://itunes.apple.com/us/app/bubble-level-free-for-iphone/id465613917?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Lemondo Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lemondo-entertainment/id406195207?uo=4">© Lemondo Entertainment</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/58/65/33/58653334-1fc7-0429-61c1-b0b8ff4f8afb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23020282/9c52db58-f446-11e6-9707-2a36b507c5f1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23020282/9c52db58-f446-11e6-9707-2a36b507c5f1.png)
https://cloud.githubusercontent.com/assets/2068130/23020282/9c52db58-f446-11e6-9707-2a36b507c5f1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23020292/aa8fd81a-f446-11e6-96c4-64b938fe5252.png
