### ISSUE TITLE
Pricerazzi – Keeping Track For Money Back

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8938]
**App Name:** Pricerazzi – Keeping Track For Money Back
**Bundle ID:** com.pricerazzi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035433941">1035433941</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pricerazzi-keeping-track-for/id1035433941?mt=8&uo=4">https://itunes.apple.com/us/app/pricerazzi-keeping-track-for/id1035433941?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Pricerazzi Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pricerazzi-inc./id1035433940?uo=4">© Pricerazzi Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/eb/5a/75/eb5a756b-45d1-be1f-05f1-5f5480dc393c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23012777/1dc24742-f428-11e6-8d05-f98e3b454e9c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23012777/1dc24742-f428-11e6-8d05-f98e3b454e9c.png)
https://cloud.githubusercontent.com/assets/2068130/23012777/1dc24742-f428-11e6-8d05-f98e3b454e9c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23012789/2c773e64-f428-11e6-8901-875328f130b5.png
