### ISSUE TITLE
SmoothParking

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8939]
**App Name:** SmoothParking
**Bundle ID:** com.smoothparking.SmoothPark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=615418863">615418863</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smoothparking/id615418863?mt=8&uo=4">https://itunes.apple.com/us/app/smoothparking/id615418863?mt=8&uo=4</a>
**App Version:** 3.9
**Seller:** SMOOTHPARKING INC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/smoothparking-inc/id615418866?uo=4">© SmoothParking Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/8d/41/99/8d4199dc-d176-9d90-ab8d-7140cb17cc4f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23020865/5b21f92c-f449-11e6-8bdc-5268dcad9651.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23020865/5b21f92c-f449-11e6-8bdc-5268dcad9651.png)
https://cloud.githubusercontent.com/assets/2068130/23020865/5b21f92c-f449-11e6-8bdc-5268dcad9651.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23020870/6871e948-f449-11e6-9b4e-f2bb1ad52de2.png
