### ISSUE TITLE
Turo - Rent Better Cars, Courtesy of Local Owners

### ISSUE THREAD

**Issue by TheRyanKing** [glasklart/hd#8940]
**App Name:** Turo - Rent Better Cars, Courtesy of Local Owners
**Bundle ID:** com.relayrides.ios.RelayRides
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555063314">555063314</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/turo-rent-better-cars-courtesy/id555063314?mt=8&uo=4">https://itunes.apple.com/us/app/turo-rent-better-cars-courtesy/id555063314?mt=8&uo=4</a>
**App Version:** 17.6
**Seller:** Turo Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/turo-inc./id555063317?uo=4">© Turo Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/9b/d7/e7/9bd7e7b2-f1c0-f804-1946-75ce748a92b7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23013009/1d556180-f429-11e6-948f-955202982e3a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23013009/1d556180-f429-11e6-948f-955202982e3a.png)
https://cloud.githubusercontent.com/assets/2068130/23013009/1d556180-f429-11e6-948f-955202982e3a.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23013024/2b979858-f429-11e6-949d-f11437e1f4c8.png
