### ISSUE TITLE
Fire Emblem Heroes

### ISSUE THREAD

**Issue by Eltalite27** [glasklart/hd#8941]
**App Name:** Fire Emblem Heroes
**Bundle ID:** com.nintendo.zaba
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1181774280">1181774280</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fire-emblem-heroes/id1181774280?mt=8&uo=4">https://itunes.apple.com/us/app/fire-emblem-heroes/id1181774280?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Nintendo Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nintendo-co-ltd/id1062496488?uo=4">© Nintendo Co., Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/dc/ec/0b/dcec0b55-b4f3-74ce-b0cf-885858d9e39c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23115445/314213e0-f745-11e6-8a04-4473553e6aef.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23071135/a775c058-f52d-11e6-9301-2c80be0cae3a.png)
https://cloud.githubusercontent.com/assets/2068130/23071135/a775c058-f52d-11e6-9301-2c80be0cae3a.png
Source:
https://cloud.githubusercontent.com/assets/2068130/23071239/ebf5c4bc-f52d-11e6-9bca-8c2540bee372.png
❓

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23103341/6906f25e-f6ba-11e6-8a71-29109b932e61.png)
https://cloud.githubusercontent.com/assets/2068130/23103341/6906f25e-f6ba-11e6-8a71-29109b932e61.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23103344/775321a2-f6ba-11e6-9a9e-e6262adba846.png
❓
