### ISSUE TITLE
League of Legends Friends

### ISSUE THREAD

**Issue by Eltalite27** [glasklart/hd#8942]
**App Name:** League of Legends Friends
**Bundle ID:** com.riotgames.mobile.leagueconnect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1077150310">1077150310</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/league-of-legends-friends/id1077150310?mt=8&uo=4">https://itunes.apple.com/us/app/league-of-legends-friends/id1077150310?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** Riot Games
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/riot-games/id346988044?uo=4">© Riot Games</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/ad/06/82/ad06827a-c28f-9b2d-8b04-df94fd5363e4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23070764/7a7fe782-f52c-11e6-8532-555352ebbba9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23070764/7a7fe782-f52c-11e6-8532-555352ebbba9.png)
https://cloud.githubusercontent.com/assets/2068130/23070764/7a7fe782-f52c-11e6-8532-555352ebbba9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23070786/892abdd4-f52c-11e6-8e3c-e7fc268f1fbd.png
