### ISSUE TITLE
Rukkus Tickets- Concerts, Sports, & Theater

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8943]
**App Name:** Rukkus Tickets- Concerts, Sports, & Theater
**Bundle ID:** com.rukkus.Rukkus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=788998201">788998201</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rukkus-tickets-concerts-sports-theater/id788998201?mt=8&uo=4">https://itunes.apple.com/us/app/rukkus-tickets-concerts-sports-theater/id788998201?mt=8&uo=4</a>
**App Version:** 7.23
**Seller:** Rukkus Inc.,
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rukkus-inc/id717016900?uo=4">© Rukkus Inc.,</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/8d/13/96/8d139689-008c-2bd1-9ace-502d829de5a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23070174/7860040c-f52a-11e6-9f6c-160c284c2217.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23070174/7860040c-f52a-11e6-9f6c-160c284c2217.png)
https://cloud.githubusercontent.com/assets/2068130/23070174/7860040c-f52a-11e6-9f6c-160c284c2217.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23070184/870eceb6-f52a-11e6-8988-fb46e007ec26.png
