### ISSUE TITLE
Leave Now — Departure Notifications, Right On Time

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8944]
**App Name:** Leave Now — Departure Notifications, Right On Time
**Bundle ID:** com.tetherpad.leavenow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=558070615">558070615</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/leave-now-departure-notifications-right-on-time/id558070615?mt=8&uo=4">https://itunes.apple.com/us/app/leave-now-departure-notifications-right-on-time/id558070615?mt=8&uo=4</a>
**App Version:** 1.5.14
**Seller:** Tetherpad, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tetherpad/id558070618?uo=4">© Tetherpad</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/ff/7c/cd/ff7ccdce-545d-69da-c8de-a998247b52a6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23070022/f9767cde-f529-11e6-88fe-746c8d384a91.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23070022/f9767cde-f529-11e6-88fe-746c8d384a91.png)
https://cloud.githubusercontent.com/assets/2068130/23070022/f9767cde-f529-11e6-88fe-746c8d384a91.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23070038/07bd8292-f52a-11e6-8dbf-9337bc793845.png
