### ISSUE TITLE
Dealflicks Movie Tickets - Showtimes, Deals

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8945]
**App Name:** Dealflicks Movie Tickets - Showtimes, Deals
**Bundle ID:** com.dealflicks.Dealflicks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606999556">606999556</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dealflicks-movie-tickets-showtimes-deals/id606999556?mt=8&uo=4">https://itunes.apple.com/us/app/dealflicks-movie-tickets-showtimes-deals/id606999556?mt=8&uo=4</a>
**App Version:** 2.9.1
**Seller:** Dealflicks, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dealflicks/id606999559?uo=4">© Dealflicks</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/f9/ec/e3/f9ece3dd-8fba-2197-b7c2-6d762e7b3a1c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23069899/7942f52e-f529-11e6-8443-422f995880f1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23069899/7942f52e-f529-11e6-8443-422f995880f1.png)
https://cloud.githubusercontent.com/assets/2068130/23069899/7942f52e-f529-11e6-8443-422f995880f1.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23069912/86f36492-f529-11e6-9d42-21e30cf0159a.png
