### ISSUE TITLE
yalu102

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#8949]
**App Name:** yalu102
**Bundle ID:** kim.cracksby.yalu102
**App Version:** 10.2
**Original Artwork:**
<img src="https://cloud.githubusercontent.com/assets/10730122/23092316/28eb6350-f5c8-11e6-85c5-36f33f67de55.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23099647/565a6f26-f66c-11e6-8472-38438ea1bf8e.png)

**Comment by Trubbel** [comment]
Not sure what else to add since it's not really a Cydia, nor an App Store application. Feel free to edit if you think something is missing.

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/23092351/de5595b2-f5c8-11e6-8c86-fc554f98f6d2.png)
https://cloud.githubusercontent.com/assets/10730122/23092351/de5595b2-f5c8-11e6-8c86-fc554f98f6d2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/23092352/de5622ac-f5c8-11e6-8b8c-c245b65fb5dc.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23099647/565a6f26-f66c-11e6-8472-38438ea1bf8e.png)
https://cloud.githubusercontent.com/assets/2068130/23099647/565a6f26-f66c-11e6-8472-38438ea1bf8e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23099649/69a9be24-f66c-11e6-9d8a-3c8ff4a815a7.png

**Comment by Trubbel** [comment]
@dreamnet I like it.
