### ISSUE TITLE
Amazon Alexa

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8950]
**App Name:** Amazon Alexa
**Bundle ID:** com.amazon.echo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944011620">944011620</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amazon-alexa/id944011620?mt=8&uo=4">https://itunes.apple.com/us/app/amazon-alexa/id944011620?mt=8&uo=4</a>
**App Version:** 2.0.2429
**Seller:** AMZN Mobile LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amzn-mobile-llc/id297606954?uo=4">© AMZN Mobile LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/03/48/38/0348384b-9cce-7bd5-9c15-99408eed4790/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25956782/ef1d6728-366c-11e7-9cf4-f069ecb47896.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/23094573/d0f8d4b4-f5fb-11e6-9860-9ca82833ca96.png)
https://cloud.githubusercontent.com/assets/10730122/23094573/d0f8d4b4-f5fb-11e6-9860-9ca82833ca96.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/23094572/d0f5bb12-f5fb-11e6-81ef-6159a27d5897.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Amazon Alexa
**Bundle ID:** com.amazon.echo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944011620">944011620</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amazon-alexa/id944011620?mt=8&uo=4">https://itunes.apple.com/us/app/amazon-alexa/id944011620?mt=8&uo=4</a>
**App Version:** 2.0.2429
**Seller:** AMZN Mobile LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amzn-mobile-llc/id297606954?uo=4">© AMZN Mobile LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/03/48/38/0348384b-9cce-7bd5-9c15-99408eed4790/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25956782/ef1d6728-366c-11e7-9cf4-f069ecb47896.png)
https://cloud.githubusercontent.com/assets/20930745/25956782/ef1d6728-366c-11e7-9cf4-f069ecb47896.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25956805/01ca6a24-366d-11e7-8726-f259fe0807e4.png
