### ISSUE TITLE
Reverb for Amazon Alexa

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8951]
**App Name:** Reverb for Amazon Alexa
**Bundle ID:** agency.rain.reverb-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1144695621">1144695621</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reverb-for-amazon-alexa/id1144695621?mt=8&uo=4">https://itunes.apple.com/us/app/reverb-for-amazon-alexa/id1144695621?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Rain Interactive
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rain/id334062172?uo=4">© Rain</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/66/a3/00/66a3005d-3222-9123-8aea-72c8302ea679/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23115827/a59e338e-f747-11e6-9bd3-083f75dd26ec.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23115827/a59e338e-f747-11e6-9bd3-083f75dd26ec.png)
https://cloud.githubusercontent.com/assets/2068130/23115827/a59e338e-f747-11e6-9bd3-083f75dd26ec.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23115841/b3a82700-f747-11e6-9e65-b45ef05761ab.png
