### ISSUE TITLE
PadGuide for Puzzle & Dragons

### ISSUE THREAD

**Issue by Eltalite27** [glasklart/hd#8952]
**App Name:** PadGuide for Puzzle & Dragons
**Bundle ID:** com.coolx.Panda
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=651949209">651949209</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/padguide-for-puzzle-dragons/id651949209?mt=8&uo=4">https://itunes.apple.com/us/app/padguide-for-puzzle-dragons/id651949209?mt=8&uo=4</a>
**App Version:** 2.7.4
**Seller:** Kim Hyowon
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/d-tech7-inc/id314785526?uo=4">© D&Tech7, Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/20/e8/1c/20e81cda-0e4f-6428-d82e-623f3e66be0d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23122063/144ba4ae-f763-11e6-8084-96d86a40ddc2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23122063/144ba4ae-f763-11e6-8084-96d86a40ddc2.png)
https://cloud.githubusercontent.com/assets/2068130/23122063/144ba4ae-f763-11e6-8084-96d86a40ddc2.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23122096/23fe4906-f763-11e6-8b94-d161669a7f3d.png
