### ISSUE TITLE
Solar Walk ™ 2 - Space Missions & Solar System

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8953]
**App Name:** Solar Walk ™ 2 - Space Missions & Solar System
**Bundle ID:** com.vitotechnology.SolarWalk2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1031155880">1031155880</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/solar-walk-2-space-missions-solar-system/id1031155880?mt=8&uo=4">https://itunes.apple.com/us/app/solar-walk-2-space-missions-solar-system/id1031155880?mt=8&uo=4</a>
**App Version:** 1.4.1
**Seller:** Vito Technology Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vito-technology-inc/id289641503?uo=4">© Vito Technology Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/c3/43/3c/c3433c73-1fc8-7f8c-9ebc-2df6e354588f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/23133074/6a6374d8-f755-11e6-96ae-5019bc880e98.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/23133074/6a6374d8-f755-11e6-96ae-5019bc880e98.png)
https://cloud.githubusercontent.com/assets/3090247/23133074/6a6374d8-f755-11e6-96ae-5019bc880e98.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/23133075/6a63bdb2-f755-11e6-9cc6-fca7cd94adc7.png

**Comment by dreamnet** [comment]
Same as #8954.
