### ISSUE TITLE
FLIR Cloud

### ISSUE THREAD

**Issue by asimcard** [glasklart/hd#8956]
**App Name:** FLIR Cloud
**Bundle ID:** com.flir.consumer.flir.cloud
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=873295084">873295084</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flir-cloud/id873295084?mt=8&uo=4">https://itunes.apple.com/us/app/flir-cloud/id873295084?mt=8&uo=4</a>
**App Version:** 2.1.38
**Seller:** FLIR Systems INC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/flir-systems/id873295087?uo=4">© FLIR Systems</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/e5/a5/2c/e5a52c19-3132-b2e9-f052-66717aede878/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23150964/cb543942-f7f7-11e6-855b-c30c1441cafc.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23150306/f5969c86-f7f2-11e6-8787-86b21bf96e7e.png)
https://cloud.githubusercontent.com/assets/2068130/23150306/f5969c86-f7f2-11e6-8787-86b21bf96e7e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23150323/0871c45c-f7f3-11e6-9453-ef9540d9f917.png
