### ISSUE TITLE
Blackboard

### ISSUE THREAD

**Issue by asimcard** [glasklart/hd#8957]
**App Name:** Blackboard
**Bundle ID:** com.Blackbeard.student
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=950424861">950424861</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/blackboard/id950424861?uo=4">https://apps.apple.com/us/app/blackboard/id950424861?uo=4</a>
**App Version:** 4.3.3
**Seller:** Blackboard Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/blackboard-inc/id306716521?uo=4">© Blackboard Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/13/9f/48/139f481b-68a7-ff87-7a51-3479d4c23cfb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61991820-f32c8280-b055-11e9-8229-808de79c166d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23150858/403e8948-f7f7-11e6-9dde-15aedd8bc63b.png)
https://cloud.githubusercontent.com/assets/2068130/23150858/403e8948-f7f7-11e6-9dde-15aedd8bc63b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23150864/4ebd68ae-f7f7-11e6-8377-17360089cf4b.png

**Comment by XPEric** [comment]
Needs update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/61991820-f32c8280-b055-11e9-8229-808de79c166d.png)
https://user-images.githubusercontent.com/2068130/61991820-f32c8280-b055-11e9-8229-808de79c166d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/61991829-050e2580-b056-11e9-9fba-aeaceb18e3ce.png
