### ISSUE TITLE
Intel® ARK (Product Specs)

### ISSUE THREAD

**Issue by asimcard** [glasklart/hd#8958]
**App Name:** Intel® ARK (Product Specs)
**Bundle ID:** com.intel.ark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=587995732">587995732</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/intel-ark-product-specs/id587995732?mt=8&uo=4">https://itunes.apple.com/us/app/intel-ark-product-specs/id587995732?mt=8&uo=4</a>
**App Version:** 2.1.3
**Seller:** Intel
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/intel-corporation/id388859709?uo=4">© Intel Corporation</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/11/c1/91/11c1915e-9419-dbd9-fdb3-638dc0c6a9c7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23150422/afe9c0f4-f7f3-11e6-9d81-68ef939c4949.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23150422/afe9c0f4-f7f3-11e6-9d81-68ef939c4949.png)
https://cloud.githubusercontent.com/assets/2068130/23150422/afe9c0f4-f7f3-11e6-9d81-68ef939c4949.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23150431/bfca3d50-f7f3-11e6-8bee-bc159f216eca.png
