### ISSUE TITLE
Vellum - Artistic Wallpapers and Backgrounds

### ISSUE THREAD

**Issue by asimcard** [glasklart/hd#8959]
**App Name:** Vellum - Artistic Wallpapers and Backgrounds
**Bundle ID:** com.merekdavis.vellum
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1095068317">1095068317</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vellum-artistic-wallpapers-and-backgrounds/id1095068317?mt=8&uo=4">https://itunes.apple.com/us/app/vellum-artistic-wallpapers-and-backgrounds/id1095068317?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** MEREK DAVIS COM, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/merek-davis-com-llc/id650415567?uo=4">© MEREK DAVIS COM, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/6f/6b/e0/6f6be010-05ee-0259-9c37-e71587da4aff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23150579/c138a608-f7f4-11e6-9519-d1700b00ae51.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23150579/c138a608-f7f4-11e6-9519-d1700b00ae51.png)
https://cloud.githubusercontent.com/assets/2068130/23150579/c138a608-f7f4-11e6-9519-d1700b00ae51.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23150589/d3b372e0-f7f4-11e6-9b5c-967bffabe9d8.png
