### ISSUE TITLE
Freeview

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#896]
**App Name:** Freeview
**Bundle ID:** com.thegrandunion.freeview
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=353765787">353765787</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/gb/app/freeview/id353765787?uo=4">https://apps.apple.com/gb/app/freeview/id353765787?uo=4</a>
**App Version:** 4.2.4
**Seller:** DTV Services Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/gb/developer/dtv-services-ltd/id481332918?uo=4">© DTV Services Ltd</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/f7/0f/21/f70f21bb-a6f7-1b9e-6d66-b18ee908780a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60412172-6fa38100-9bd0-11e9-9f5a-15c1c202f1b1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410395/c1ce32fe-92eb-11e6-938d-0005e84dab15.png)
https://cloud.githubusercontent.com/assets/20930745/19410395/c1ce32fe-92eb-11e6-938d-0005e84dab15.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19410399/d2a5d14a-92eb-11e6-8993-c224c7554822.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60412172-6fa38100-9bd0-11e9-9f5a-15c1c202f1b1.png)
https://user-images.githubusercontent.com/2068130/60412172-6fa38100-9bd0-11e9-9f5a-15c1c202f1b1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60412185-7df19d00-9bd0-11e9-9353-99c41bb2fb6b.png
