### ISSUE TITLE
Nike+ Training Club - Workouts & Fitness Plans

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#8960]
**App Name:** Nike+ Training Club - Workouts & Fitness Plans
**Bundle ID:** com.nike.niketrainingclub
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=301521403">301521403</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nike-training-club-workouts-fitness-plans/id301521403?mt=8&uo=4">https://itunes.apple.com/us/app/nike-training-club-workouts-fitness-plans/id301521403?mt=8&uo=4</a>
**App Version:** 5.3.1
**Seller:** Nike, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nike-inc/id301521406?uo=4">© Nike, Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/48/bb/19/48bb1901-755d-f34c-f92f-2818219993a3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23205827/90d8f010-f8eb-11e6-880b-536938063181.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23205827/90d8f010-f8eb-11e6-880b-536938063181.png)
https://cloud.githubusercontent.com/assets/2068130/23205827/90d8f010-f8eb-11e6-880b-536938063181.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23205837/9f9e5f40-f8eb-11e6-8ce5-7006ee05973e.png
