### ISSUE TITLE
Stormfall: Rise of Balur

### ISSUE THREAD

**Issue by xDevlinx21** [glasklart/hd#8961]
**App Name:** Stormfall: Rise of Balur
**Bundle ID:** com.plarium.stormfallrob
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916728593">916728593</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stormfall-rise-of-balur/id916728593?mt=8&uo=4">https://itunes.apple.com/us/app/stormfall-rise-of-balur/id916728593?mt=8&uo=4</a>
**App Version:** 1.83
**Seller:** Plarium Global Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/plarium-global-ltd/id489487383?uo=4">© Plarium Global Ltd</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/43/e9/db/43e9dba7-396a-e943-ede6-529e8e517625/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24542795/52d59f14-15fd-11e7-8852-fca1c2f18be7.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24542606/926d6fcc-15fc-11e7-96cb-43813dc29c81.png)
https://cloud.githubusercontent.com/assets/20930745/24542606/926d6fcc-15fc-11e7-96cb-43813dc29c81.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24542648/b5691af8-15fc-11e7-9f79-52ddf7650ffc.png

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24542795/52d59f14-15fd-11e7-8852-fca1c2f18be7.png)
https://cloud.githubusercontent.com/assets/20930745/24542795/52d59f14-15fd-11e7-8852-fca1c2f18be7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24542831/73172d7e-15fd-11e7-8ba1-8ec2353baccb.png
