### ISSUE TITLE
SWORD ART ONLINE:Memory Defrag

### ISSUE THREAD

**Issue by xDevlinx21** [glasklart/hd#8962]
**App Name:** SWORD ART ONLINE:Memory Defrag
**Bundle ID:** jp.co.bandainamcoent.BNEI0292
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1192559270">1192559270</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sword-art-online-memory-defrag/id1192559270?mt=8&uo=4">https://itunes.apple.com/us/app/sword-art-online-memory-defrag/id1192559270?mt=8&uo=4</a>
**App Version:** 1.9.0
**Seller:** BANDAI NAMCO Entertainment Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bandai-namco-entertainment-inc/id352305770?uo=4">© BANDAI NAMCO Entertainment Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/99/08/5f/99085f82-cf61-8571-a188-cb4c2bb9513b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23274443/07f8eb56-fa03-11e6-930d-4b0a0774d830.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23274443/07f8eb56-fa03-11e6-930d-4b0a0774d830.png)
https://cloud.githubusercontent.com/assets/2068130/23274443/07f8eb56-fa03-11e6-930d-4b0a0774d830.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23274459/16c1eb88-fa03-11e6-8b79-8961b976e3cc.png
