### ISSUE TITLE
Summon Rush!

### ISSUE THREAD

**Issue by xDevlinx21** [glasklart/hd#8963]
**App Name:** Summon Rush!
**Bundle ID:** com.mobirix.rush
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1133067102">1133067102</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/summon-rush/id1133067102?mt=8&uo=4">https://itunes.apple.com/us/app/summon-rush/id1133067102?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** MOBIRIX
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mobirix/id349276666?uo=4">© MOBIRIX</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/80/e3/41/80e34153-1157-a22a-a9b7-f0529fcf20e4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23294642/a4ce312a-fa6c-11e6-915a-2c73713f456f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23294642/a4ce312a-fa6c-11e6-915a-2c73713f456f.png)
https://cloud.githubusercontent.com/assets/2068130/23294642/a4ce312a-fa6c-11e6-915a-2c73713f456f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23294649/b309aac6-fa6c-11e6-8d19-881b0a1c794b.png
