### ISSUE TITLE
YouTube Music

### ISSUE THREAD

**Issue by asimcard** [glasklart/hd#8969]
**App Name:** YouTube Music
**Bundle ID:** com.google.ios.youtubemusic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1017492454">1017492454</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/youtube-music/id1017492454?mt=8&uo=4">https://itunes.apple.com/us/app/youtube-music/id1017492454?mt=8&uo=4</a>
**App Version:** 2.04
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc/id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/8b/87/ec/8b87ec2e-6f73-74d3-c616-20bd03fd0a87/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/23708258/32101610-2e365f6a-bb19-11e7-929e-be93d3203f27.png)

**Comment by sern19** [comment]
Maybe something like that?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/23342135/1db01a7e-fc55-11e6-87b7-7df602e26319.png)
https://cloud.githubusercontent.com/assets/23708258/23342135/1db01a7e-fc55-11e6-87b7-7df602e26319.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/23708258/23342143/40edaaba-fc55-11e6-872c-2562b190da38.png

**Comment by sern19** [comment]
Alternatively:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/23342185/0fcaa95a-fc56-11e6-8e7d-d3cd9619dc51.png)
https://cloud.githubusercontent.com/assets/23708258/23342185/0fcaa95a-fc56-11e6-8e7d-d3cd9619dc51.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/23708258/23342188/1f50ea06-fc56-11e6-8bd9-78e0e1b8d070.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** YouTube Music
**Bundle ID:** com.google.ios.youtubemusic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1017492454">1017492454</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/youtube-music/id1017492454?mt=8&uo=4">https://itunes.apple.com/us/app/youtube-music/id1017492454?mt=8&uo=4</a>
**App Version:** 2.04
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc/id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/8b/87/ec/8b87ec2e-6f73-74d3-c616-20bd03fd0a87/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by sern19** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/23708258/32101610-2e365f6a-bb19-11e7-929e-be93d3203f27.png)
https://user-images.githubusercontent.com/23708258/32101610-2e365f6a-bb19-11e7-929e-be93d3203f27.png
--- ---
Source:
https://user-images.githubusercontent.com/23708258/32101635-445085a0-bb19-11e7-9625-019f5d206fa0.png
