### ISSUE TITLE
HomeAway & VRBO Vacation Rentals

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8971]
**App Name:** HomeAway & VRBO Vacation Rentals
**Bundle ID:** com.homeaway.HAMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=642441300">642441300</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/homeaway-vrbo-vacation-rentals/id642441300?mt=8&uo=4">https://itunes.apple.com/us/app/homeaway-vrbo-vacation-rentals/id642441300?mt=8&uo=4</a>
**App Version:** 2017.02
**Seller:** HomeAway.com, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/homeaway-com-inc/id416091680?uo=4">© HomeAway.com, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/5f/be/84/5fbe84ed-f657-2c44-cdaa-a27aa69be435/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/23401832/6509f35e-fda9-11e6-822c-677b16d641ff.png)

**Comment by sern19** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/23401832/6509f35e-fda9-11e6-822c-677b16d641ff.png)
https://cloud.githubusercontent.com/assets/23708258/23401832/6509f35e-fda9-11e6-822c-677b16d641ff.png

--- ---
Source:
https://cloud.githubusercontent.com/assets/23708258/23401820/5c033b44-fda9-11e6-9c05-16362a42a80f.png
