### ISSUE TITLE
TrackR - Find Lost Keys, Wallets, Pets and Phones

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#8972]
**App Name:** TrackR - Find Lost Keys, Wallets, Pets and Phones
**Bundle ID:** com.phonehalo.PhTrackR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=588363491">588363491</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trackr-find-lost-keys-wallets-pets-and-phones/id588363491?mt=8&uo=4">https://itunes.apple.com/us/app/trackr-find-lost-keys-wallets-pets-and-phones/id588363491?mt=8&uo=4</a>
**App Version:** 5.3.1
**Seller:** Phone Halo, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/phonehalo/id521000592?uo=4">© PhoneHalo</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/f5/e2/00/f5e20041-9d96-1e68-2b67-42dfcd5cd337/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/23440621/3c0523d8-fe1d-11e6-9b84-9c48924c87f4.png)

**Comment by sern19** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/23440621/3c0523d8-fe1d-11e6-9b84-9c48924c87f4.png)
https://cloud.githubusercontent.com/assets/23708258/23440621/3c0523d8-fe1d-11e6-9b84-9c48924c87f4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/23708258/23440614/34934792-fe1d-11e6-8de2-ba16f3bddcb7.png
