### ISSUE TITLE
GoalAlert Football Live Scores

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8973]
**App Name:** GoalAlert Football Live Scores
**Bundle ID:** com.eisterhues-media.TorAlarm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=484990052">484990052</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/goalalert-football-live-scores/id484990052?mt=8&uo=4">https://itunes.apple.com/us/app/goalalert-football-live-scores/id484990052?mt=8&uo=4</a>
**App Version:** 4.0.4
**Seller:** TorAlarm GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/toralarm-gmbh/id899516981?uo=4">© TorAlarm GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/2f/85/05/2f850597-97bc-2d28-4f59-d33f9cc79b80/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23477657/f9b05a5a-febe-11e6-8b95-b2e45ffe6d2e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23477657/f9b05a5a-febe-11e6-8b95-b2e45ffe6d2e.png)
https://cloud.githubusercontent.com/assets/20930745/23477657/f9b05a5a-febe-11e6-8b95-b2e45ffe6d2e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23477678/12c008ce-febf-11e6-82e3-a4d7e19cec18.png
