### ISSUE TITLE
YouPickIt - Angebote, Prospekte, Einkaufsliste

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8974]
**App Name:** YouPickIt - Angebote, Prospekte, Einkaufsliste
**Bundle ID:** de.youpickit.YouPickIt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=918079312">918079312</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/youpickit-angebote-prospekte-einkaufsliste/id918079312?mt=8&uo=4">https://itunes.apple.com/de/app/youpickit-angebote-prospekte-einkaufsliste/id918079312?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** YouPickIt GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/youpickit-gmbh/id918079311?uo=4">© YouPickIt GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/64/ee/f8/64eef896-6734-b51e-7130-8774a7dbce11/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23478147/a8ea4bb0-fec0-11e6-8b1e-a74b36cd559f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23478147/a8ea4bb0-fec0-11e6-8b1e-a74b36cd559f.png)
https://cloud.githubusercontent.com/assets/20930745/23478147/a8ea4bb0-fec0-11e6-8b1e-a74b36cd559f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23478166/b694c83a-fec0-11e6-9f1e-9e4c84aead1f.png
