### ISSUE TITLE
FileHub Plus

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8975]
**App Name:** FileHub Plus
**Bundle ID:** com.hootoo.filehubplus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955296910">955296910</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/filehub-plus/id955296910?mt=8&uo=4">https://itunes.apple.com/us/app/filehub-plus/id955296910?mt=8&uo=4</a>
**App Version:** 2.0.036
**Seller:** HOOTOO.COM INC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hootoo-com-inc/id658692926?uo=4">© HooToo.com Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/32/2d/94/322d94d6-4a9c-9891-b9be-b85497c92726/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23478520/e838b620-fec1-11e6-8702-486071b771db.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23478520/e838b620-fec1-11e6-8702-486071b771db.png)
https://cloud.githubusercontent.com/assets/20930745/23478520/e838b620-fec1-11e6-8702-486071b771db.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23478544/fa9c9dd6-fec1-11e6-99d2-35621ed1a674.png
