### ISSUE TITLE
HeartWatch. Heart & Activity Monitor for Watch

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#8976]
**App Name:** HeartWatch. Heart & Activity Monitor for Watch
**Bundle ID:** com.tantsissa.Heartbeat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1062745479">1062745479</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/heartwatch-heart-activity-monitor-for-watch/id1062745479?mt=8&uo=4">https://itunes.apple.com/us/app/heartwatch-heart-activity-monitor-for-watch/id1062745479?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** TANTSISSA HOLDINGS PTY LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tantsissa/id861650887?uo=4">© Tantsissa</a>
**Supported Devices:** iPhone4S-iPhone4S, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/b7/a9/a3/b7a9a391-8960-5e9b-fb2f-e848a38ee438/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23479086/95f8867c-fec3-11e6-9907-268b17ec6260.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23479033/6aea1b94-fec3-11e6-9443-4585e988bcc2.png)
https://cloud.githubusercontent.com/assets/20930745/23479021/63781a82-fec3-11e6-87fc-6b17bb28e02e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23479065/809ec930-fec3-11e6-9d3a-f70dc5a8330d.png
