### ISSUE TITLE
BirdId - Garden Birds of Germany

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8977]
**App Name:** BirdId - Garden Birds of Germany
**Bundle ID:** com.sunbird.vogelid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=493273346">493273346</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/birdid-garden-birds-of-germany/id493273346?mt=8&uo=4">https://itunes.apple.com/us/app/birdid-garden-birds-of-germany/id493273346?mt=8&uo=4</a>
**App Version:** 8.03
**Seller:** Mullen & Pohland GbR
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mullen-pohland-gbr/id408400848?uo=4">© Mullen & Pohland GbR</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/b6/f8/4e/b6f84e32-d6fc-09d7-be3e-3d61540cb80b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23521565/d6542caa-ff7f-11e6-9618-e267ef72340e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23521565/d6542caa-ff7f-11e6-9618-e267ef72340e.png)
https://cloud.githubusercontent.com/assets/2068130/23521565/d6542caa-ff7f-11e6-9618-e267ef72340e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23521582/e60d573e-ff7f-11e6-84ce-85dfb29644d5.png
