### ISSUE TITLE
Spiegel.TV

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8978]
**App Name:** SPIEGEL.TV
**Bundle ID:** tv.spiegel.ios.sptv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=544287406">544287406</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spiegel-tv/id544287406?mt=8&uo=4">https://itunes.apple.com/us/app/spiegel-tv/id544287406?mt=8&uo=4</a>
**App Version:** 2.8.4
**Seller:** SPIEGEL TV GmbH Deutschland
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/spiegel-tv-gmbh/id544287409?uo=4">© SPIEGEL TV GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/bd/e4/42/bde442f4-a1f7-ee4f-5e0e-e8185f959c26/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23521956/85bcdcf4-ff81-11e6-9503-8add11a2db5c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23521956/85bcdcf4-ff81-11e6-9503-8add11a2db5c.png)
https://cloud.githubusercontent.com/assets/2068130/23521956/85bcdcf4-ff81-11e6-9503-8add11a2db5c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23521970/963cee66-ff81-11e6-9281-cc759153bef2.png
