### ISSUE TITLE
Filer

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8979]
**App Name:** Filer
**Bundle ID:** com.hammockdistrict.downloader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=318884764">318884764</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/filer/id318884764?mt=8&uo=4">https://itunes.apple.com/us/app/filer/id318884764?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Dan Leehr L.L.C.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dan-leehr-l-l-c/id318884767?uo=4">© Dan Leehr L.L.C.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/eb/64/b9/eb64b919-32ce-91a8-4dfb-9563a4b9ad5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23479949/7941abbe-fec6-11e6-8ddf-0340be2fc74a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23479949/7941abbe-fec6-11e6-8ddf-0340be2fc74a.png)
https://cloud.githubusercontent.com/assets/20930745/23479949/7941abbe-fec6-11e6-8ddf-0340be2fc74a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23479966/862b9ab0-fec6-11e6-8d3f-66e521f1498e.png
