### ISSUE TITLE
Pocket Anatomy - Interactive 3D Human Anatomy and Physiology.

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8981]
**App Name:** Pocket Anatomy - Interactive 3D Human Anatomy and Physiology.
**Bundle ID:** com.emedia.PocketBodyMusclesiPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388633565">388633565</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-anatomy-interactive-3d-human-anatomy-physiology/id388633565?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-anatomy-interactive-3d-human-anatomy-physiology/id388633565?mt=8&uo=4</a>
**App Version:** 6.0
**Seller:** eMedia
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pocket-anatomy/id330292122?uo=4">© Pocket Anatomy</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/78/42/a3/7842a36f-e908-a74a-f1dc-ce1000540ee2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23522369/fe4f1dc0-ff82-11e6-99ef-4e77a88a5011.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23522369/fe4f1dc0-ff82-11e6-99ef-4e77a88a5011.png)
https://cloud.githubusercontent.com/assets/2068130/23522369/fe4f1dc0-ff82-11e6-99ef-4e77a88a5011.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23522385/1291fd48-ff83-11e6-9ce3-66ac318e1509.png
