### ISSUE TITLE
PhotoPills

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8982]
**App Name:** PhotoPills
**Bundle ID:** com.photopills.photopills
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=596026805">596026805</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photopills/id596026805?mt=8&uo=4">https://itunes.apple.com/us/app/photopills/id596026805?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** PhotoPills S.L.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/photopills-s-l/id596026808?uo=4">© PhotoPills S.L.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple91/v4/51/de/0a/51de0af3-8854-606c-f35f-a501445a562b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23480428/2162b9e0-fec8-11e6-98e9-769f3dd70bcd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23480428/2162b9e0-fec8-11e6-98e9-769f3dd70bcd.png)
https://cloud.githubusercontent.com/assets/20930745/23480428/2162b9e0-fec8-11e6-98e9-769f3dd70bcd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23480440/2e572384-fec8-11e6-8b2d-a47321c12c8d.png
