### ISSUE TITLE
Dark Sky Finder

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8983]
**App Name:** Dark Sky Finder
**Bundle ID:** com.skidmoreapps.darkskyfinder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=546529400">546529400</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dark-sky-finder/id546529400?mt=8&uo=4">https://itunes.apple.com/us/app/dark-sky-finder/id546529400?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Skidmore Properties, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/skidmore-properties-llc/id289637803?uo=4">© Skidmore Properties, LLC</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple7/v4/a7/96/27/a796277b-73bb-df16-84ad-b6c34b1a9516/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/23488319/359078c0-feec-11e6-9e9e-fe7a6d43915f.png)

**Comment by sern19** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/23488319/359078c0-feec-11e6-9e9e-fe7a6d43915f.png)
https://cloud.githubusercontent.com/assets/23708258/23488319/359078c0-feec-11e6-9e9e-fe7a6d43915f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/23708258/23488313/2c67a7e6-feec-11e6-9065-858c4780efdb.png

**Comment by sern19** [comment]
Alternatively inverted version:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23708258/23488669/66edaf8a-feee-11e6-8c4c-53c5a30fd727.png)
https://cloud.githubusercontent.com/assets/23708258/23488669/66edaf8a-feee-11e6-8c4c-53c5a30fd727.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/23708258/23488657/5f2622d2-feee-11e6-8510-7fc8326b0c5d.png

**Comment by ivanov007** [comment]
nice work, first one will do it 👍
