### ISSUE TITLE
FabFocus - portraits with depth and bokeh

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8984]
**App Name:** FabFocus - portraits with depth and bokeh
**Bundle ID:** com.secondverse.fabfocus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1080434313">1080434313</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fabfocus-portraits-with-depth-and-bokeh/id1080434313?mt=8&uo=4">https://itunes.apple.com/us/app/fabfocus-portraits-with-depth-and-bokeh/id1080434313?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** Secondverse LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/secondverse/id935754325?uo=4">© Secondverse</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/4f/81/d8/4f81d8bf-6d72-640e-f73e-51262178b538/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23480654/016018b2-fec9-11e6-9b97-2cb537ae737c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23480654/016018b2-fec9-11e6-9b97-2cb537ae737c.png)
https://cloud.githubusercontent.com/assets/20930745/23480654/016018b2-fec9-11e6-9b97-2cb537ae737c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23480684/132fc948-fec9-11e6-88c3-6d5f2f79fb4b.png
