### ISSUE TITLE
Period Tracker Deluxe

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#8985]
**App Name:** Period Tracker Deluxe
**Bundle ID:** com.gpapps.ptracker
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=289084315">289084315</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/period-tracker-deluxe/id289084315?mt=8&uo=4">https://itunes.apple.com/us/app/period-tracker-deluxe/id289084315?mt=8&uo=4</a>
**App Version:** 9.5.1
**Seller:** GP International LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gp-apps/id289078803?uo=4">© GP Apps</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple60/v4/1d/43/22/1d43221d-8cb6-317b-a48d-c3cd4347b9a6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23520833/d0ea8960-ff7c-11e6-849c-7dbf330c9f72.png)

**Comment by dreamnet** [comment]
Refers to #8980.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23520833/d0ea8960-ff7c-11e6-849c-7dbf330c9f72.png)
https://cloud.githubusercontent.com/assets/2068130/23520833/d0ea8960-ff7c-11e6-849c-7dbf330c9f72.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23520852/e13d4afa-ff7c-11e6-8dd0-d3974f6ec81e.png
