### ISSUE TITLE
DB Streckenagent

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8986]
**App Name:** DB Streckenagent
**Bundle ID:** com.deutschebahn.streckenagent
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1096074746">1096074746</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/db-streckenagent/id1096074746?mt=8&uo=4">https://itunes.apple.com/us/app/db-streckenagent/id1096074746?mt=8&uo=4</a>
**App Version:** 2.0.4
**Seller:** Deutsche Bahn
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/deutsche-bahn/id343555249?uo=4">© Deutsche Bahn</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/73/2e/5f/732e5ff5-16a7-3eef-4fcf-44957538dd2b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23563767/5ef70faa-0048-11e7-91ff-de890077161e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23563767/5ef70faa-0048-11e7-91ff-de890077161e.png)
https://cloud.githubusercontent.com/assets/2068130/23563767/5ef70faa-0048-11e7-91ff-de890077161e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23563774/700faca2-0048-11e7-9bdc-615e55de4d16.png
