### ISSUE TITLE
Cesium Music Player

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8987]
**App Name:** Cesium Music Player
**Bundle ID:** com.michaelclay.Cesium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=924491991">924491991</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cesium-music-player/id924491991?mt=8&uo=4">https://itunes.apple.com/us/app/cesium-music-player/id924491991?mt=8&uo=4</a>
**App Version:** 3.8.3
**Seller:** Mike Clay
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mike-clay/id924491990?uo=4">© Mike Clay</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/0b/c3/5d/0bc35d64-471e-1e8f-a8cf-7043cd8f8d85/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23564689/2fc0b2d8-004b-11e7-9c82-c2dc9890108d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23564689/2fc0b2d8-004b-11e7-9c82-c2dc9890108d.png)
https://cloud.githubusercontent.com/assets/2068130/23564689/2fc0b2d8-004b-11e7-9c82-c2dc9890108d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23564702/4118f784-004b-11e7-89f4-b2c5007465e4.png
