### ISSUE TITLE
Scanner for Me - PDF Scanner for Documents

### ISSUE THREAD

**Issue by Checkit23** [glasklart/hd#8988]
**App Name:** Scanner for Me - PDF Scanner for Documents
**Bundle ID:** com.apalonapps.pdfscanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=978697315">978697315</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scanner-for-me-pdf-scanner-for-documents/id978697315?mt=8&uo=4">https://itunes.apple.com/us/app/scanner-for-me-pdf-scanner-for-documents/id978697315?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** IAC Search & Media Europe Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/apalon-apps/id749046894?uo=4">© Apalon Apps</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/03/15/5e/03155e0e-705f-9658-fb64-911c0eb9119a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23565910/dcba28d0-004f-11e7-8a63-6f6ab32232c8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23565910/dcba28d0-004f-11e7-8a63-6f6ab32232c8.png)
https://cloud.githubusercontent.com/assets/2068130/23565910/dcba28d0-004f-11e7-8a63-6f6ab32232c8.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23565921/eab9bc0c-004f-11e7-9bc5-e08f392aa3c5.png
