### ISSUE TITLE
VLC Streamer Free

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#899]
**App Name:** VLC Streamer Free
**Bundle ID:** com.HobbyistSoftware.VLCStreamerFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=410036516">410036516</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vlc-streamer-free/id410036516?mt=8&uo=4">https://itunes.apple.com/us/app/vlc-streamer-free/id410036516?mt=8&uo=4</a>
**App Version:** 4.12
**Seller:** Hobbyist Software Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/hobbyist-software-limited/id291218199?uo=4>© Hobbyist Software Limited</a>
**Supported Devices:** iPadThirdGen, iPhone-3GS, iPhone4S, iPodTouchourthGen, iPadMini, iPadMini4G, iPhone5c, iPadFourthGen, iPhone4, iPadFourthGen4G, iPad23G, iPodTouchFifthGen, iPad2Wifi, iPhone5s, iPadThirdGen4G, iPhone5
**Original Artwork:**
<img src="http://a411.phobos.apple.com/us/r30/Purple5/v4/a5/8d/c0/a58dc06b-eda7-3c9a-d1d6-6948d921ef8e/pr_source.png?downloadKey=1420119925_1c0cab281e57899bc973cc232a069b29" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5592023/29dcb43a-91ac-11e4-907a-5bd4573246c3.png)

**Comment by dominicPereira** [comment]
hi i tried to used this for my iphone 6+ theme but it does not work......

**Comment by dreamnet** [comment]
@dominicPereira I have updated the original issue above. What's the exact problem?

**Comment by dominicPereira** [comment]
once i added it to winterbored icon bundle and respring it does no show the glasklart icon.

**Comment by dominicPereira** [comment]
mine just says VLC  Streamer which is a paid app not the free one

**Comment by dreamnet** [comment]
@dominicPereira [iTunes ID](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request#step-1-of-2-find-the-itunes-id)?? Maybe 410031728 ?

**Comment by dominicPereira** [comment]
Yup it's iTunes ID 410031728 

Does not work for the iPhone 6+ 8.1

**Comment by dominicPereira** [comment]
What's the bundle ID ?

**Comment by dreamnet** [comment]
@dominicPereira So that's not the app we are talking about. I reopen #313 and closing this.
