### ISSUE TITLE
HealthPeek Dashboard for HealthKit

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8990]
**App Name:** HealthPeek Dashboard for HealthKit
**Bundle ID:** com.pvieito.InstaFlash
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1190121252">1190121252</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/healthpeek-dashboard-for-healthkit/id1190121252?mt=8&uo=4">https://itunes.apple.com/us/app/healthpeek-dashboard-for-healthkit/id1190121252?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Pedro Jose Pereira Vieito
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pedro-jose-pereira-vieito/id931232010?uo=4">© Pedro Jose Pereira Vieito</a>
**Supported Devices:** iPhone4S-iPhone4S, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/05/e0/f7/05e0f7c1-06ae-1caf-e151-8c09f70239be/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23670877/7e1fc2cc-0369-11e7-86e1-205e62d67c23.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23670877/7e1fc2cc-0369-11e7-86e1-205e62d67c23.png)
https://cloud.githubusercontent.com/assets/20930745/23670877/7e1fc2cc-0369-11e7-86e1-205e62d67c23.png

Source::
https://cloud.githubusercontent.com/assets/20930745/23670909/9c532e46-0369-11e7-9f84-8384d207bb0c.png
