### ISSUE TITLE
Pocket Files: Photo Lock+Vault

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8991]
**App Name:** Pocket Files: Photo Lock+Vault
**Bundle ID:** com.rambax.pocketfiles
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=645754521">645754521</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-files-photo-lock-vault/id645754521?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-files-photo-lock-vault/id645754521?mt=8&uo=4</a>
**App Version:** 5.1.1
**Seller:** Rambax, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rambax-llc/id315377119?uo=4">© Rambax, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/a0/f8/30/a0f8306f-7a6c-8a8f-5895-fea72f722dc0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46156026-e2b24c80-c278-11e8-8b54-f504cf96fb0f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23671405/65ae6c28-036b-11e7-9956-7a0653d67f74.png)
https://cloud.githubusercontent.com/assets/20930745/23671405/65ae6c28-036b-11e7-9956-7a0653d67f74.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23671438/8678e9ce-036b-11e7-9c4e-a2ed4a121dae.png)

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Pocket Files: Photo Lock+Vault
**Bundle ID:** com.rambax.pocketfiles
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=645754521">645754521</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-files-photo-lock-vault/id645754521?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-files-photo-lock-vault/id645754521?mt=8&uo=4</a>
**App Version:** 5.1.1
**Seller:** Rambax, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rambax-llc/id315377119?uo=4">© Rambax, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/a0/f8/30/a0f8306f-7a6c-8a8f-5895-fea72f722dc0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46156026-e2b24c80-c278-11e8-8b54-f504cf96fb0f.png)
https://user-images.githubusercontent.com/20930745/46156026-e2b24c80-c278-11e8-8b54-f504cf96fb0f.png

Source:
https://user-images.githubusercontent.com/20930745/46156065-f52c8600-c278-11e8-84e8-5360f1319e52.png
