### ISSUE TITLE
Lumi News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8992]
**App Name:** Lumi News
**Bundle ID:** do.lumi.lumios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1082400645">1082400645</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lumi-news/id1082400645?mt=8&uo=4">https://itunes.apple.com/us/app/lumi-news/id1082400645?mt=8&uo=4</a>
**App Version:** 2.0.15
**Seller:** Semion Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lumi-do/id1082400644?uo=4">© Lumi.do</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/b9/f5/27/b9f5275b-0b97-b29c-8e48-67b6a7842715/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23671850/070314ba-036d-11e7-9ad7-92c2c4408b36.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23671850/070314ba-036d-11e7-9ad7-92c2c4408b36.png)
https://cloud.githubusercontent.com/assets/20930745/23671850/070314ba-036d-11e7-9ad7-92c2c4408b36.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23671875/1e1b46e0-036d-11e7-8733-8c3ddb2bffac.png)
