### ISSUE TITLE
TheGrint - All Golf. One App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#8993]
**App Name:** TheGrint - All Golf. One App
**Bundle ID:** com.thegrint.grint
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=532085262">532085262</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/thegrint-all-golf-one-app/id532085262?mt=8&uo=4">https://itunes.apple.com/us/app/thegrint-all-golf-one-app/id532085262?mt=8&uo=4</a>
**App Version:** 6.5.2
**Seller:** GRINT LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/grint-llc/id532085265?uo=4">© Grint LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/aa/3c/9c/aa3c9cb0-9aaa-4423-3575-32397571ee0b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/23710407/4360aa1a-03e2-11e7-85f4-97cda9f9e42d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/23710407/4360aa1a-03e2-11e7-85f4-97cda9f9e42d.png)
https://cloud.githubusercontent.com/assets/3090247/23710407/4360aa1a-03e2-11e7-85f4-97cda9f9e42d.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/23710408/43624eb0-03e2-11e7-9181-b2c21303281f.png
