### ISSUE TITLE
Quoka classifieds Flea market

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8994]
**App Name:** Quoka classifieds Flea market
**Bundle ID:** de.QUOKA.Kleinanzeigen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347248168">347248168</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quoka-classifieds-flea-market/id347248168?mt=8&uo=4">https://itunes.apple.com/us/app/quoka-classifieds-flea-market/id347248168?mt=8&uo=4</a>
**App Version:** 6.4.2
**Seller:** Quoka GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/quoka-gmbh/id347248171?uo=4">© Quoka GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/0c/19/08/0c190870-021a-b7b4-86fc-8ea83f99f189/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23821136/dbee651c-0629-11e7-9880-707db23db7ea.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23821136/dbee651c-0629-11e7-9880-707db23db7ea.png)
https://cloud.githubusercontent.com/assets/20930745/23821136/dbee651c-0629-11e7-9880-707db23db7ea.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23821150/024e8d40-062a-11e7-9c69-491a0b73dec2.png
