### ISSUE TITLE
Dive Planet

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8995]
**App Name:** Dive Planet
**Bundle ID:** ch.edv-busin.diveworld
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=504607535">504607535</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dive-planet/id504607535?mt=8&uo=4">https://itunes.apple.com/us/app/dive-planet/id504607535?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** Adrian Busin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/edv-busin/id504607538?uo=4">© edv-busin</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/d7/c0/5e/d7c05eaa-4ce2-9bf6-95bb-66fe05243b57/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25065377/4bb0a80a-220f-11e7-9c93-f84d8dfa4afa.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25065377/4bb0a80a-220f-11e7-9c93-f84d8dfa4afa.png)
https://cloud.githubusercontent.com/assets/2068130/25065377/4bb0a80a-220f-11e7-9c93-f84d8dfa4afa.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25065383/5b828cd0-220f-11e7-9ec7-924e7d1104cc.png
