### ISSUE TITLE
Diviac - Scuba diving logbook

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8996]
**App Name:** Diviac - Scuba diving logbook
**Bundle ID:** com.diviac.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=930068909">930068909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/diviac-scuba-diving-logbook/id930068909?mt=8&uo=4">https://itunes.apple.com/us/app/diviac-scuba-diving-logbook/id930068909?mt=8&uo=4</a>
**App Version:** 0.4.1
**Seller:** Diviac AG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/diviac-ag/id929595293?uo=4">© Diviac AG</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple7/v4/75/ea/04/75ea04a3-b86a-81f1-1737-0c94117b3a19/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23821012/2c333c08-0627-11e7-857a-bfb8ee4f5b65.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23821012/2c333c08-0627-11e7-857a-bfb8ee4f5b65.png)
https://cloud.githubusercontent.com/assets/20930745/23821012/2c333c08-0627-11e7-857a-bfb8ee4f5b65.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23821015/4cd48b1a-0627-11e7-9fa0-96d49651f24b.png
