### ISSUE TITLE
FischFinder – Wordwide Fish ID, Fish Guide and Reef Guide

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8997]
**App Name:** FischFinder – Wordwide Fish ID, Fish Guide and Reef Guide
**Bundle ID:** com.thomasfleischer.ff.FischFinder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=818679384">818679384</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fischfinder-wordwide-fish-id-fish-guide-and-reef-guide/id818679384?mt=8&uo=4">https://itunes.apple.com/us/app/fischfinder-wordwide-fish-id-fish-guide-and-reef-guide/id818679384?mt=8&uo=4</a>
**App Version:** 1.4.2
**Seller:** Thomas Fleischer
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/thomas-fleischer/id818679387?uo=4">© Thomas Fleischer</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple4/v4/a4/4b/af/a44bafc0-178a-e5e9-f311-d91e0eb4d7e0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23830756/90cf3c20-0712-11e7-9f05-72d3242a6fb6.png)

**Comment by ivanov007** [comment]
@myristica13 issue name should be exact the same as App Name

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23830756/90cf3c20-0712-11e7-9f05-72d3242a6fb6.png)
https://cloud.githubusercontent.com/assets/2068130/23830756/90cf3c20-0712-11e7-9f05-72d3242a6fb6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23830764/a1e7845e-0712-11e7-9929-401821b0a71a.png
