### ISSUE TITLE
 Dive Signals

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8998]
**App Name:** Dive Signals
**Bundle ID:** de.ok2dive.DiveSignals
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=331024725">331024725</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dive-signals/id331024725?mt=8&uo=4">https://itunes.apple.com/us/app/dive-signals/id331024725?mt=8&uo=4</a>
**App Version:** 2.02
**Seller:** ok2dive UG (haftungsbeschraenkt)
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ok2dive-ug/id331024728?uo=4">© ok2dive UG</a>
**Supported Devices:** iPodTouchSecondGen-iPod-touch-with-mic, iPhone3G-iPhone-3G, iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple/v4/b6/55/3a/b6553aed-0e6c-c7bc-4e72-30e99b049abc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23821244/a12a50d2-062c-11e7-949a-bbe7ac0a1bcc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23821244/a12a50d2-062c-11e7-949a-bbe7ac0a1bcc.png)
https://cloud.githubusercontent.com/assets/20930745/23821244/a12a50d2-062c-11e7-949a-bbe7ac0a1bcc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23821248/bc130a56-062c-11e7-9555-359776c6816b.png
