### ISSUE TITLE
To-Fu Fury

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#8999]
**App Name:** To-Fu Fury
**Bundle ID:** com.agsd.games.TofuFury
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=980132410">980132410</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/to-fu-fury/id980132410?mt=8&uo=4">https://itunes.apple.com/us/app/to-fu-fury/id980132410?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Amazon Game Studios Distribution, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amazon-game-studios/id980060502?uo=4">© Amazon Game Studios</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/42/24/52/422452b4-9e22-08ee-b3db-62cdcbe1904b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23829950/bd69fc8e-06fe-11e7-8037-d2e2d4638be6.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23829950/bd69fc8e-06fe-11e7-8037-d2e2d4638be6.png)
https://cloud.githubusercontent.com/assets/20930745/23829950/bd69fc8e-06fe-11e7-8037-d2e2d4638be6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23829952/d742dc16-06fe-11e7-9f1e-d20014c091bf.png
