### ISSUE TITLE
Betfair Exchange – Sports Betting Online

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#900]
**App Name:** Betfair Exchange – Sports Betting Online
**Bundle ID:** com.betfair.research.BetfairClient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=347621336">347621336</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/betfair-exchange-sports-betting/id347621336?mt=8&uo=4">https://itunes.apple.com/gb/app/betfair-exchange-sports-betting/id347621336?mt=8&uo=4</a>
**App Version:** 4.5.1
**Seller:** Betfair LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/betfair/id347621339?uo=4>© Betfair</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/83/48/73/83487313-03c4-5c91-e11e-0f88cc6b1bda/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410458/52857d42-92ed-11e6-8fa4-2c5f157e0252.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410458/52857d42-92ed-11e6-8fa4-2c5f157e0252.png)
![](https://cloud.githubusercontent.com/assets/20930745/19410458/52857d42-92ed-11e6-8fa4-2c5f157e0252.png


Source:
https://cloud.githubusercontent.com/assets/20930745/19410463/6bde5084-92ed-11e6-859c-08c0e1bd2c1b.png
