### ISSUE TITLE
Six!

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#9000]
**App Name:** Six!
**Bundle ID:** com.gramgames.toppletap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1137673647">1137673647</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/six/id1137673647?mt=8&uo=4">https://itunes.apple.com/us/app/six/id1137673647?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** Gram Games Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gram-games/id1202264615?uo=4">© Gram Games</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/7a/95/89/7a9589fb-60c5-88de-fe35-aaf850467c30/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/23801772/f0e85544-0576-11e7-8e9d-fb07341a8b11.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/23801772/f0e85544-0576-11e7-8e9d-fb07341a8b11.png)
https://cloud.githubusercontent.com/assets/3090247/23801772/f0e85544-0576-11e7-8e9d-fb07341a8b11.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/23801771/f0e67d6e-0576-11e7-948e-db41f455ba76.png
