### ISSUE TITLE
Windy ~ Sleep Relax Meditate & white noise sounds

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#9001]
**App Name:** Windy ~ Sleep Relax Meditate & white noise sounds
**Bundle ID:** com.taptanium.windy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=841377297">841377297</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/windy-sleep-relax-meditate-white-noise-sounds/id841377297?mt=8&uo=4">https://itunes.apple.com/us/app/windy-sleep-relax-meditate-white-noise-sounds/id841377297?mt=8&uo=4</a>
**App Version:** 4.2.3
**Seller:** Franz Bruckhoff
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/franz-bruckhoff/id399345216?uo=4">© Franz Bruckhoff</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/d3/72/28/d37228e4-b2e6-41a8-a3b4-b205a99ddda1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23830054/59aa402a-0701-11e7-8136-1efcc47bca95.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23830054/59aa402a-0701-11e7-8136-1efcc47bca95.png)
https://cloud.githubusercontent.com/assets/20930745/23830054/59aa402a-0701-11e7-8136-1efcc47bca95.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23830056/7074a66a-0701-11e7-90b2-034621bcaa8b.png)

**Comment by dreamnet** [comment]
@2Qt2beStr8 Accepting it, because there will be no other way to do this. 👍
