### ISSUE TITLE
Roofbot: Puzzler On The Roof

### ISSUE THREAD

**Issue by myristica13** [glasklart/hd#9002]
**App Name:** Roofbot: Puzzler On The Roof
**Bundle ID:** com.dcoc.roofbot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1148435076">1148435076</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/roofbot-puzzler-on-the-roof/id1148435076?mt=8&uo=4">https://itunes.apple.com/us/app/roofbot-puzzler-on-the-roof/id1148435076?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Double Coconut LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/double-coconut-llc/id538478177?uo=4">© Double Coconut LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple82/v4/0d/5a/bb/0d5abb3f-cfd8-e1cf-ed57-e33a957d9d5f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23830789/17b6d2fc-0713-11e7-8a97-032a0a6f6d7c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23830789/17b6d2fc-0713-11e7-8a97-032a0a6f6d7c.png)
https://cloud.githubusercontent.com/assets/20930745/23830789/17b6d2fc-0713-11e7-8a97-032a0a6f6d7c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23830795/3866cc6e-0713-11e7-89cb-5df2be02011b.png
