### ISSUE TITLE
Swish - Sports Highlights

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9005]
**App Name:** Swish - Sports Highlights
**Bundle ID:** io.swish.SwishRN
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1045276497">1045276497</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swish-sports-highlights/id1045276497?mt=8&uo=4">https://itunes.apple.com/us/app/swish-sports-highlights/id1045276497?mt=8&uo=4</a>
**App Version:** 2.7.1
**Seller:** Swish Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/swish/id980385652?uo=4">© Swish</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/d5/b3/c3/d5b3c3e9-521e-71f0-d2fe-f379f1450387/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23826888/26c9c91e-06a7-11e7-925f-7fc079b40282.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23826888/26c9c91e-06a7-11e7-925f-7fc079b40282.png)
https://cloud.githubusercontent.com/assets/2068130/23826888/26c9c91e-06a7-11e7-925f-7fc079b40282.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23826895/36f5ab78-06a7-11e7-9db2-20d4cef7d64c.png
