### ISSUE TITLE
Patch - Local News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9006]
**App Name:** Patch - Local News
**Bundle ID:** com.patch.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=430049632">430049632</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/patch-local-news/id430049632?mt=8&uo=4">https://itunes.apple.com/us/app/patch-local-news/id430049632?mt=8&uo=4</a>
**App Version:** 6.1
**Seller:** Planck, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/patch-media/id1088403234?uo=4">© Patch Media</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/f0/2f/5b/f02f5b7d-d82d-53be-d625-1c4836f1fa83/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634776-213503bc-19aa-11e8-9e2e-4266d5af319f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23829738/2841b33a-06fa-11e7-92c0-138045ee5015.png)
https://cloud.githubusercontent.com/assets/20930745/23829738/2841b33a-06fa-11e7-92c0-138045ee5015.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23829747/3f30b244-06fa-11e7-8c10-531ad304e17f.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23829774/d5ccc80a-06fa-11e7-8805-53ac5849ff4f.png)
https://cloud.githubusercontent.com/assets/20930745/23829774/d5ccc80a-06fa-11e7-8805-53ac5849ff4f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23829784/f403d908-06fa-11e7-8dad-d72052e9c5c9.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 First one! 👍

**Comment by l8er4now** [comment]
Needs an update

**App Name:** Patch - Local News
**Bundle ID:** com.patch.iphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=430049632">430049632</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/patch-local-news/id430049632?mt=8&uo=4">https://itunes.apple.com/us/app/patch-local-news/id430049632?mt=8&uo=4</a>
**App Version:** 6.1
**Seller:** Planck, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/patch-media/id1088403234?uo=4">© Patch Media</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/f0/2f/5b/f02f5b7d-d82d-53be-d625-1c4836f1fa83/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634776-213503bc-19aa-11e8-9e2e-4266d5af319f.png)
https://user-images.githubusercontent.com/20930745/36634776-213503bc-19aa-11e8-9e2e-4266d5af319f.png

Source:
https://user-images.githubusercontent.com/20930745/36634781-32d5ad38-19aa-11e8-8e29-f6a5157d0c57.png
