### ISSUE TITLE
Search By Image Extension – Find Reverse Picture

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9007]
**App Name:** Search By Image Extension – Find Reverse Picture
**Bundle ID:** gs.SearchByImage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1199066779">1199066779</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/search-by-image-extension-find-reverse-picture/id1199066779?mt=8&uo=4">https://itunes.apple.com/us/app/search-by-image-extension-find-reverse-picture/id1199066779?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Gregory Strigunov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gregory-strigunov/id1118406318?uo=4">© Gregory Strigunov</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/44/92/70/449270c4-af2b-ad66-00ed-3cae34f2686e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23826842/4b3b947c-06a6-11e7-817d-11195f14f1a3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23826842/4b3b947c-06a6-11e7-817d-11195f14f1a3.png)
https://cloud.githubusercontent.com/assets/2068130/23826842/4b3b947c-06a6-11e7-817d-11195f14f1a3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23826844/5ba52350-06a6-11e7-8efd-64f8ec784d18.png
