### ISSUE TITLE
大馬頭條–馬來西亞時事資訊&新聞，最新最熱視頻

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9008]
**App Name:** 大馬頭條–馬來西亞時事資訊&新聞，最新最熱視頻
**Bundle ID:** com.felink.news
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1144886049">1144886049</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/hk/app/%E5%A4%A7%E9%A6%AC%E9%A0%AD%E6%A2%9D-%E9%A6%AC%E4%BE%86%E8%A5%BF%E4%BA%9E%E6%99%82%E4%BA%8B%E8%B3%87%E8%A8%8A-%E6%96%B0%E8%81%9E-%E6%9C%80%E6%96%B0%E6%9C%80%E7%86%B1%E8%A6%96%E9%A0%BB/id1144886049?mt=8&uo=4">https://itunes.apple.com/hk/app/%E5%A4%A7%E9%A6%AC%E9%A0%AD%E6%A2%9D-%E9%A6%AC%E4%BE%86%E8%A5%BF%E4%BA%9E%E6%99%82%E4%BA%8B%E8%B3%87%E8%A8%8A-%E6%96%B0%E8%81%9E-%E6%9C%80%E6%96%B0%E6%9C%80%E7%86%B1%E8%A6%96%E9%A0%BB/id1144886049?mt=8&uo=4</a>
**App Version:** 2.8.0
**Seller:** yu hua
**Developer:** <a target="_blank" href="https://itunes.apple.com/hk/developer/yu-hua/id1144886048?uo=4">© yu hua</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/73/f0/ed/73f0ed7d-72f1-a80c-8ba8-64c38526b9cc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38463777-50cc2a8c-3b02-11e8-90e1-21e5c407a487.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23829641/8ef84132-06f7-11e7-8ae3-40df82aeead5.png)
https://cloud.githubusercontent.com/assets/20930745/23829641/8ef84132-06f7-11e7-8ae3-40df82aeead5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23829647/b3416500-06f7-11e7-97e8-baaa92d6de6b.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23829674/ae27fdbc-06f8-11e7-925e-1bd4c623bce0.png)
https://cloud.githubusercontent.com/assets/20930745/23829674/ae27fdbc-06f8-11e7-925e-1bd4c623bce0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23829682/cc9e9abc-06f8-11e7-9077-3cfaf6efe578.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Second one! 👍

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38463777-50cc2a8c-3b02-11e8-90e1-21e5c407a487.png)
https://user-images.githubusercontent.com/20930745/38463777-50cc2a8c-3b02-11e8-90e1-21e5c407a487.png

Source:
https://user-images.githubusercontent.com/20930745/38463782-6c884652-3b02-11e8-9006-a96c36214669.png
