### ISSUE TITLE
UC San Diego (UCSD)

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#9009]
**App Name:** UC San Diego (UCSD)
**Bundle ID:** edu.ucsd.ucsandiego
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=318646412">318646412</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/uc-san-diego-ucsd/id318646412?mt=8&uo=4">https://itunes.apple.com/us/app/uc-san-diego-ucsd/id318646412?mt=8&uo=4</a>
**App Version:** 4.1.3
**Seller:** University of California, San Diego (Business Affairs)
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/university-of-california-san-diego-business-affairs/id318646415?uo=4">© University of California, San Diego (Business Affairs)</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/53/ca/b4/53cab4d9-5909-47d7-8c92-6e28bbac251a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23834220/0f9d7a4a-0753-11e7-90b7-c1fa933c5acf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23830980/82aaac6a-0717-11e7-91d8-68839a11270e.png)
https://cloud.githubusercontent.com/assets/20930745/23830980/82aaac6a-0717-11e7-91d8-68839a11270e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23830984/9b36f0ae-0717-11e7-82b9-2a39f3f200f6.png

**Comment by dreamnet** [comment]
Hmmmm...
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23834220/0f9d7a4a-0753-11e7-90b7-c1fa933c5acf.png)
https://cloud.githubusercontent.com/assets/2068130/23834220/0f9d7a4a-0753-11e7-90b7-c1fa933c5acf.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23834226/2294239c-0753-11e7-87d5-3f1bf00d57fa.png
