### ISSUE TITLE
Family Guy- Another Freakin' Mobile Game

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#9010]
**App Name:** Family Guy- Another Freakin' Mobile Game
**Bundle ID:** com.sgn.familyguy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1139342866">1139342866</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/au/app/family-guy-another-freakin-mobile-game/id1139342866?mt=8&uo=4">https://itunes.apple.com/au/app/family-guy-another-freakin-mobile-game/id1139342866?mt=8&uo=4</a>
**App Version:** 1.2.6
**Seller:** Jam City, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/au/developer/jam-city-inc/id290671617?uo=4">© Jam City, Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/fb/e8/30/fbe8302b-b8e8-ff2e-8a03-a3770e569834/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23865699/c4696560-0816-11e7-9ecf-1bc4807348ae.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/23865699/c4696560-0816-11e7-9ecf-1bc4807348ae.png)
https://cloud.githubusercontent.com/assets/2068130/23865699/c4696560-0816-11e7-9ecf-1bc4807348ae.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/23865716/d2f4b74c-0816-11e7-83f0-708c6e11c7dd.png
