### ISSUE TITLE
Alpify

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9011]
**App Name:** Alpify
**Bundle ID:** com.alpify.Alpify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=622546357">622546357</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alpify/id622546357?mt=8&uo=4">https://itunes.apple.com/us/app/alpify/id622546357?mt=8&uo=4</a>
**App Version:** 3.1.3
**Seller:** Grup Basera SL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/grup-basera-sl/id622546360?uo=4">© Grup Basera SL</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/8f/02/f5/8f02f5a4-5c5c-982a-dc4f-7b554766989e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23960415/33c91076-09a8-11e7-9014-6a38a368daba.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/23960415/33c91076-09a8-11e7-9014-6a38a368daba.png)
https://cloud.githubusercontent.com/assets/20930745/23960415/33c91076-09a8-11e7-9014-6a38a368daba.png

Source:
https://cloud.githubusercontent.com/assets/20930745/23960470/5e291d70-09a8-11e7-8373-2a3f3aa11d2a.png
