### ISSUE TITLE
 Cửu Âm - Võ Lâm Chí Tôn

### ISSUE THREAD

**Issue by koimc** [glasklart/hd#9013]
**App Name:** Cửu Âm - Võ Lâm Chí Tôn
**Bundle ID:** vn.vng.cuuamchankinh
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1089824208">1089824208</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/vn/app/c%E1%BB%ADu-%C3%A2m-v%C3%B5-l%C3%A2m-ch%C3%AD-t%C3%B4n/id1089824208?mt=8&uo=4">https://itunes.apple.com/vn/app/c%E1%BB%ADu-%C3%A2m-v%C3%B5-l%C3%A2m-ch%C3%AD-t%C3%B4n/id1089824208?mt=8&uo=4</a>
**App Version:** 3.2.0
**Seller:** La Thang
**Developer:** <a target="_blank" href="https://itunes.apple.com/vn/developer/la-thang/id1056490891?uo=4">© La Thang</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/ed/85/9e/ed859e61-f777-3682-4679-4a2684d6d8d1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24576044/b663a460-16b4-11e7-867d-1ca267096465.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24576044/b663a460-16b4-11e7-867d-1ca267096465.png)
https://cloud.githubusercontent.com/assets/20930745/24576044/b663a460-16b4-11e7-867d-1ca267096465.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24576048/c95e8166-16b4-11e7-9a4b-0a5d262eac2d.png
