### ISSUE TITLE
Drippler - Updates, Apps & Tips for Your Phone

### ISSUE THREAD

**Issue by stardusted** [glasklart/hd#9014]
**App Name:** Drippler - Updates, Apps & Tips for Your Phone
**Bundle ID:** com.Drippler.Drippler
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=619307903">619307903</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/drippler-updates-apps-tips-for-your-phone/id619307903?mt=8&uo=4">https://itunes.apple.com/us/app/drippler-updates-apps-tips-for-your-phone/id619307903?mt=8&uo=4</a>
**App Version:** 1.5.3
**Seller:** Drippler Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/drippler-ltd/id499542587?uo=4">© Drippler Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/71/4d/04/714d047b-7942-df09-d13c-3765d0c3f956/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/24262194/a27da96c-0ff9-11e7-8441-41281cadb8f4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/24262194/a27da96c-0ff9-11e7-8441-41281cadb8f4.png)
https://cloud.githubusercontent.com/assets/2068130/24262194/a27da96c-0ff9-11e7-8441-41281cadb8f4.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/24262209/b4575a7a-0ff9-11e7-977f-965d0ff1f974.png
