### ISSUE TITLE
TV Guide App - TV Shows, Movies and News by Zeen

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9016]
**App Name:** TV Guide App - TV Shows, Movies and News by Zeen
**Bundle ID:** com.zeen.one
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1138853627">1138853627</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tv-guide-app-tv-shows-movies-and-news-by-zeen/id1138853627?mt=8&uo=4">https://itunes.apple.com/us/app/tv-guide-app-tv-shows-movies-and-news-by-zeen/id1138853627?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Zeen, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zeen-inc/id1138853626?uo=4">© Zeen, Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/bb/93/37/bb9337ec-f5cb-3cfe-043e-0cf1bbf0f5dd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24416745/12a78a4c-13e6-11e7-8775-373b83a62335.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24416745/12a78a4c-13e6-11e7-8775-373b83a62335.png)
https://cloud.githubusercontent.com/assets/20930745/24416745/12a78a4c-13e6-11e7-8775-373b83a62335.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24416779/328869d0-13e6-11e7-9021-61d4878b6bc3.png
