### ISSUE TITLE
Popcorn: discover your new favourite movie

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9017]
**App Name:** Popcorn: discover your new favourite movie
**Bundle ID:** io.mobula.popcorn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1204478983">1204478983</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/popcorn-discover-your-new-favourite-movie/id1204478983?mt=8&uo=4">https://itunes.apple.com/us/app/popcorn-discover-your-new-favourite-movie/id1204478983?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Grabble Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/grabble-apps/id909415816?uo=4">© Grabble Apps</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple91/v4/c9/a2/3b/c9a23be7-d7fe-8f6f-e9c3-899c4a6c0b67/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24417151/89962e5a-13e7-11e7-9f98-3834b0ceb635.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24417151/89962e5a-13e7-11e7-9f98-3834b0ceb635.png)
https://cloud.githubusercontent.com/assets/20930745/24417151/89962e5a-13e7-11e7-9f98-3834b0ceb635.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24417176/a5d2a184-13e7-11e7-82e7-2e8fec388589.png
