### ISSUE TITLE
Glovo - Delivery from any restaurant or store

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9018]
**App Name:** Glovo - Delivery from any restaurant or store
**Bundle ID:** com.glovo.glovo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=951812684">951812684</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/glovo-delivery-from-any-restaurant-or-store/id951812684?mt=8&uo=4">https://itunes.apple.com/us/app/glovo-delivery-from-any-restaurant-or-store/id951812684?mt=8&uo=4</a>
**App Version:** 4.3.4
**Seller:** Glovoapp 23 SL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/glovoapp-23-sl/id951812683?uo=4">© Glovoapp 23 SL</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/52/90/4b/52904bc2-3b8c-ba7f-0f66-2467895da3fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24517590/35c861dc-157f-11e7-9e35-a7f2fa276c94.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24517590/35c861dc-157f-11e7-9e35-a7f2fa276c94.png)
https://cloud.githubusercontent.com/assets/20930745/24517590/35c861dc-157f-11e7-9e35-a7f2fa276c94.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24517618/4e552082-157f-11e7-98cc-33baead5a5ff.png
