### ISSUE TITLE
Turkcell TV+

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#9019]
**App Name:** Turkcell TV+
**Bundle ID:** com.turkcell.tv.iphone.tint
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=835880015">835880015</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/turkcell-tv/id835880015?mt=8&uo=4">https://itunes.apple.com/us/app/turkcell-tv/id835880015?mt=8&uo=4</a>
**App Version:** 4.8
**Seller:** TURKCELL INTERAKTIF DIJITAL PLATFORM VE ICERIK HIZMETLERI ANONIM SIRKETI
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/turkcell-interaktif-dijital-platform-ve-icerik-hizmetleri/id780468698?mt=8&uo=4">© Turkcell Interaktif Dijital Platform ve Icerik Hizmetleri A.S.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/ba/c5/43/bac543f1-e221-8222-3308-52ceb227a6bf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54823032-db5b8100-4ca6-11e9-9ff0-ca82684e60d3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24620043/8719eb26-189c-11e7-8c35-13db4423dd21.png)
https://cloud.githubusercontent.com/assets/20930745/24620043/8719eb26-189c-11e7-8c35-13db4423dd21.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24620095/ae6e2002-189c-11e7-91ba-b1b4df5294fc.png

**Comment by alpcinar** [comment]
Needs update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54823032-db5b8100-4ca6-11e9-9ff0-ca82684e60d3.png)
https://user-images.githubusercontent.com/20930745/54823032-db5b8100-4ca6-11e9-9ff0-ca82684e60d3.png

Source:
https://user-images.githubusercontent.com/20930745/54823035-dc8cae00-4ca6-11e9-8e57-bd95ba1a6c8d.png
