### ISSUE TITLE
Calm: Meditation to Relax, Focus & Sleep Better

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#9020]
**App Name:** Calm: Meditation to Relax, Focus & Sleep Better
**Bundle ID:** com.calm.calmapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571800810">571800810</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calm-meditation-to-relax-focus-sleep-better/id571800810?mt=8&uo=4">https://itunes.apple.com/us/app/calm-meditation-to-relax-focus-sleep-better/id571800810?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Calm.com, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/calm-com/id571800813?uo=4">© Calm.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/b0/f4/4f/b0f44f88-56ac-45f8-8eb6-76235d7b776f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24620359/b4227f7e-189d-11e7-97d5-e9ba82a5ce7e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24620359/b4227f7e-189d-11e7-97d5-e9ba82a5ce7e.png)
https://cloud.githubusercontent.com/assets/20930745/24620359/b4227f7e-189d-11e7-97d5-e9ba82a5ce7e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24620380/caaa0d84-189d-11e7-8ea8-af5720c0b7a1.png
