### ISSUE TITLE
Runtasty - Healthy Recipes & Cooking Videos

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9021]
**App Name:** Runtasty - Healthy Recipes & Cooking Videos
**Bundle ID:** com.runtastic.iphone.runtasty.lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1183746476">1183746476</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/runtasty-healthy-recipes-cooking-videos/id1183746476?mt=8&uo=4">https://itunes.apple.com/us/app/runtasty-healthy-recipes-cooking-videos/id1183746476?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** runtastic
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/runtastic/id336599885?uo=4">© runtastic</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/7e/46/6c/7e466cbf-0218-6837-24fd-95899d84917a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24868786/6c0608e0-1e11-11e7-9c05-213fd8e12fc5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24809215/207e96c0-1bbf-11e7-8a32-ee4ee93fc0e2.png)
https://cloud.githubusercontent.com/assets/20930745/24809215/207e96c0-1bbf-11e7-8a32-ee4ee93fc0e2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24809252/38d64c68-1bbf-11e7-8db0-678d1c437127.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24809317/65a36690-1bbf-11e7-8cf2-b847466f9c51.png)
https://cloud.githubusercontent.com/assets/20930745/24809317/65a36690-1bbf-11e7-8cf2-b847466f9c51.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24809346/7ad59aba-1bbf-11e7-815d-8ac6088522c4.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24809487/f064a4c4-1bbf-11e7-9263-a6cc0354288e.png)
https://cloud.githubusercontent.com/assets/20930745/24809487/f064a4c4-1bbf-11e7-9263-a6cc0354288e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24809512/0421f264-1bc0-11e7-8924-230355ded9fe.png

**Comment by dreamnet** [comment]
@grkka ❓

**Comment by 2Qt2beStr8** [comment]
@grkka  or do you like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24868358/103d61f8-1e10-11e7-8670-1337efc4d12b.png)
https://cloud.githubusercontent.com/assets/20930745/24868358/103d61f8-1e10-11e7-8670-1337efc4d12b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24868383/2524842a-1e10-11e7-9ea7-1fbe2a9a7b1b.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24868678/13e9c548-1e11-11e7-860a-ddec0b557953.png)
https://cloud.githubusercontent.com/assets/20930745/24868678/13e9c548-1e11-11e7-860a-ddec0b557953.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24868701/29d93ece-1e11-11e7-97af-2fd2c019d243.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/24868786/6c0608e0-1e11-11e7-9c05-213fd8e12fc5.png)
https://cloud.githubusercontent.com/assets/20930745/24868786/6c0608e0-1e11-11e7-9c05-213fd8e12fc5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/24868800/7f75396e-1e11-11e7-85f3-af53d8a25db6.png
