### ISSUE TITLE
Ring - Always Home

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9022]
**App Name:** Ring - Always Home
**Bundle ID:** com.ring
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926252661">926252661</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ring-always-home/id926252661?mt=8&uo=4">https://itunes.apple.com/us/app/ring-always-home/id926252661?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** Bot Home Automation, INC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ring-com/id926252660?uo=4">© Ring.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/26/7f/52/267f5238-9314-460d-e963-c1536f4d9b53/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32913044-6c3e4798-cb11-11e7-8c80-7f55b7fab31c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/24825852/8948e76e-1c28-11e7-9732-b4c425830545.png)
https://cloud.githubusercontent.com/assets/2068130/24825852/8948e76e-1c28-11e7-9732-b4c425830545.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/24825860/99b4e6c0-1c28-11e7-8d02-55aefca6cd2c.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Ring - Always Home
**Bundle ID:** com.ring
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926252661">926252661</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ring-always-home/id926252661?mt=8&uo=4">https://itunes.apple.com/us/app/ring-always-home/id926252661?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** Bot Home Automation, INC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ring-com/id926252660?uo=4">© Ring.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/26/7f/52/267f5238-9314-460d-e963-c1536f4d9b53/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/3090247/32850576-2e149dec-c9f8-11e7-827e-ee763f701a5f.png)
https://user-images.githubusercontent.com/3090247/32850576-2e149dec-c9f8-11e7-827e-ee763f701a5f.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/32850577-2e94794a-c9f8-11e7-8fba-87487f912073.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32913044-6c3e4798-cb11-11e7-8c80-7f55b7fab31c.png)
https://user-images.githubusercontent.com/20930745/32913044-6c3e4798-cb11-11e7-8c80-7f55b7fab31c.png

Source:
https://user-images.githubusercontent.com/20930745/32913076-81700bb0-cb11-11e7-88de-1cd6063f3063.png
