### ISSUE TITLE
Florida Roads - Traffic Conditions & Cameras

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9037]
**App Name:** Florida Roads - Traffic Conditions & Cameras
**Bundle ID:** com.AndrewSinclair.FLRoads
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1219672589">1219672589</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/florida-roads-traffic-conditions-cameras/id1219672589?mt=8&uo=4">https://itunes.apple.com/us/app/florida-roads-traffic-conditions-cameras/id1219672589?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Katerina Antonopoulou
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/katerina-antonopoulou/id396216597?uo=4">© Katerina Antonopoulou</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/75/93/b8/7593b885-5573-50ee-0d96-6c91c5617a58/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25011186/d36de810-206c-11e7-8369-e2ea86a5fc23.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25011186/d36de810-206c-11e7-8369-e2ea86a5fc23.png)
https://cloud.githubusercontent.com/assets/20930745/25011186/d36de810-206c-11e7-8369-e2ea86a5fc23.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25011214/e61011d2-206c-11e7-8880-9edb5d49ac8a.png
