### ISSUE TITLE
Health Data Importer

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9038]
**App Name:** Health Data Importer
**Bundle ID:** com.lionheartsw.HealthImporter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1158733998">1158733998</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/health-data-importer/id1158733998?mt=8&uo=4">https://itunes.apple.com/us/app/health-data-importer/id1158733998?mt=8&uo=4</a>
**App Version:** 1.0.11
**Seller:** Lionheart Software LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lionheart-software-llc/id548052593?uo=4">© Lionheart Software LLC</a>
**Supported Devices:** iPhone4S-iPhone4S, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple91/v4/17/31/8b/17318b6d-8464-3641-b5c5-6aee2442bfc2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25010923/e5fafece-206b-11e7-8137-10f3684ef947.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25010923/e5fafece-206b-11e7-8137-10f3684ef947.png)
https://cloud.githubusercontent.com/assets/20930745/25010923/e5fafece-206b-11e7-8137-10f3684ef947.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25010951/fded3bf0-206b-11e7-9197-08328d5d38d5.png
