### ISSUE TITLE
Sonos S1 Controller

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#9045]
**App Name:** Sonos S1 Controller
**Bundle ID:** com.sonos.SonosController
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=293523031">293523031</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sonos-s1-controller/id293523031?uo=4">https://apps.apple.com/us/app/sonos-s1-controller/id293523031?uo=4</a>
**App Version:** 11.2
**Seller:** Sonos, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sonos-inc/id293523034?uo=4">© Sonos, Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/39/df/43/39df4308-8618-fc48-59de-e14fc57ee09d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84327630-1da90080-ab80-11ea-9e12-c131c3481724.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25073015/71f13344-22dd-11e7-9d15-db5354ea4049.png)
https://cloud.githubusercontent.com/assets/2068130/25073015/71f13344-22dd-11e7-9d15-db5354ea4049.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25073018/80f4966a-22dd-11e7-9cc3-34ff504c189f.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Sonos S1 Controller
**Bundle ID:** com.sonos.SonosController
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=293523031">293523031</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/sonos-s1-controller/id293523031?uo=4">https://apps.apple.com/us/app/sonos-s1-controller/id293523031?uo=4</a>
**App Version:** 11.2
**Seller:** Sonos, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sonos-inc/id293523034?uo=4">© Sonos, Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/39/df/43/39df4308-8618-fc48-59de-e14fc57ee09d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/84327630-1da90080-ab80-11ea-9e12-c131c3481724.png)
https://user-images.githubusercontent.com/2068130/84327630-1da90080-ab80-11ea-9e12-c131c3481724.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/84327659-2ef20d00-ab80-11ea-97c7-c9b5088a21bc.png
