### ISSUE TITLE
Virgin TV Anywhere

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#905]
**App Name:** Virgin TV Anywhere
**Bundle ID:** com.virginmedia.quicksilvervm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=477143650">477143650</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/virgin-tv-anywhere/id477143650?mt=8&uo=4">https://itunes.apple.com/gb/app/virgin-tv-anywhere/id477143650?mt=8&uo=4</a>
**App Version:** 3.1.4
**Seller:** Virgin Media Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/virgin-media/id449156077?uo=4>© Virgin Media</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple7/v4/fd/12/72/fd12720e-711d-9081-808b-f66b615bf23e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410504/9f3d4ede-92ee-11e6-8bf4-fc1a6ef11a1e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410504/9f3d4ede-92ee-11e6-8bf4-fc1a6ef11a1e.png)
https://cloud.githubusercontent.com/assets/20930745/19410504/9f3d4ede-92ee-11e6-8bf4-fc1a6ef11a1e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19410505/ae5a05d8-92ee-11e6-90a6-b9e1a803885f.png
