### ISSUE TITLE
Prizmo Go - Instant Text Capture

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9083]
**App Name:** Prizmo Go - Instant Text Capture
**Bundle ID:** com.creaceed.iprizmogo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1183367390">1183367390</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/prizmo-go-instant-text-capture/id1183367390?mt=8&uo=4">https://itunes.apple.com/us/app/prizmo-go-instant-text-capture/id1183367390?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Creaceed SPRL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/creaceed-sprl/id291683889?uo=4">© Creaceed SPRL</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/14/a5/e9/14a5e9e5-9724-0dbd-200d-64444f79ab2d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25627377/a5536a68-2f62-11e7-939a-e01f3eea55b5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25627377/a5536a68-2f62-11e7-939a-e01f3eea55b5.png)
https://cloud.githubusercontent.com/assets/20930745/25627377/a5536a68-2f62-11e7-939a-e01f3eea55b5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25627398/bba2efbe-2f62-11e7-953d-5428f74cb697.png
