### ISSUE TITLE
Smart newsreader and daily news digest

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9084]
**App Name:** NewsTab - Smart newsreader and daily news digest
**Bundle ID:** com.newstab
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1200774745">1200774745</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newstab-smart-newsreader-and-daily-news-digest/id1200774745?mt=8&uo=4">https://itunes.apple.com/us/app/newstab-smart-newsreader-and-daily-news-digest/id1200774745?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Skyter Technologies Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/skyter-com/id1005613257?uo=4">© skyter.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/30/23/d8/3023d803-bddd-7024-cb01-a416903b53a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25778144/8f88ad42-32f5-11e7-8168-d60593958144.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25770434/857ffa46-3235-11e7-9a0a-ea432f5274a7.png)
https://cloud.githubusercontent.com/assets/20930745/25770434/857ffa46-3235-11e7-9a0a-ea432f5274a7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25770436/9cbba886-3235-11e7-9bd9-14f5f4f1dcae.png

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25770472/64fb5670-3236-11e7-9717-66c29b3a7374.png)
https://cloud.githubusercontent.com/assets/20930745/25770472/64fb5670-3236-11e7-9717-66c29b3a7374.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25770473/68f96afa-3236-11e7-8220-7d58adb440ab.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 The newspaper looks fine, but I think the top section needs to be inverted (and the corners rounded).

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25774949/d1494996-3299-11e7-81b2-1fe5de3231c8.png)
https://cloud.githubusercontent.com/assets/20930745/25774949/d1494996-3299-11e7-81b2-1fe5de3231c8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25774937/8ddb2eb8-3299-11e7-8864-7dc07cdd0f58.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Great work, just some details added:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25778144/8f88ad42-32f5-11e7-8168-d60593958144.png)
https://cloud.githubusercontent.com/assets/2068130/25778144/8f88ad42-32f5-11e7-8168-d60593958144.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25778146/a1921b2c-32f5-11e7-9777-e945c159be35.png
