### ISSUE TITLE
CheapCharts - iTunes Deals for Movies, TV, Apps...

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9087]
**App Name:** CheapCharts - iTunes Deals for Movies, TV, Apps...
**Bundle ID:** com.lollipapp.cheapcharts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=772046134">772046134</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cheapcharts-itunes-deals-for-movies-tv-apps/id772046134?mt=8&uo=4">https://itunes.apple.com/us/app/cheapcharts-itunes-deals-for-movies-tv-apps/id772046134?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** LollipApp GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lollipapp-gmbh/id772046137?uo=4">© LollipApp GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/f1/28/32/f1283205-f828-fed1-880f-25f73e5f0146/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25710428/8baa0866-30ec-11e7-906c-a65999d9cd42.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25710428/8baa0866-30ec-11e7-906c-a65999d9cd42.png)
https://cloud.githubusercontent.com/assets/20930745/25710428/8baa0866-30ec-11e7-906c-a65999d9cd42.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25710468/a066e882-30ec-11e7-9996-60b87c76181b.png
