### ISSUE TITLE
Truecaller - Spam Identification & Block

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9088]
**App Name:** Truecaller - Spam Identification & Block
**Bundle ID:** com.truesoftware.TrueCallerOther
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=448142450">448142450</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/truecaller-spam-identification-block/id448142450?mt=8&uo=4">https://itunes.apple.com/us/app/truecaller-spam-identification-block/id448142450?mt=8&uo=4</a>
**App Version:** 7.45
**Seller:** True Software Scandinavia AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/true-software-scandinavia-ab/id336142200?uo=4">© True Software Scandinavia AB</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/63/41/e9/6341e94e-89e9-77b8-a264-d110e904172e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25710991/237c2614-30ee-11e7-8026-a080b24155aa.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25710991/237c2614-30ee-11e7-8026-a080b24155aa.png)
https://cloud.githubusercontent.com/assets/20930745/25710991/237c2614-30ee-11e7-8026-a080b24155aa.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25711024/3a0f5dba-30ee-11e7-9d00-0e68676d49ef.png
