### ISSUE TITLE
Pana - Travel Itinerary & Assistant

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9089]
**App Name:** Pana - Travel Itinerary & Assistant
**Bundle ID:** com.tivonahaug.geneva
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=957978459">957978459</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pana-travel-itinerary-assistant/id957978459?mt=8&uo=4">https://itunes.apple.com/us/app/pana-travel-itinerary-assistant/id957978459?mt=8&uo=4</a>
**App Version:** 3.0.7
**Seller:** Tivona & Haug, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tivona-haug/id913681014?uo=4">© Tivona & Haug</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/5d/f7/10/5df7104d-310b-4395-1f20-3d45ecd6198e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25710704/4e056bb2-30ed-11e7-9554-0442b8bcaac9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25710704/4e056bb2-30ed-11e7-9554-0442b8bcaac9.png)
https://cloud.githubusercontent.com/assets/20930745/25710704/4e056bb2-30ed-11e7-9554-0442b8bcaac9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25710734/65bbeaf6-30ed-11e7-853b-0a6f2a6d5f2a.png
