### ISSUE TITLE
Dergilik

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#9090]
**App Name:** Dergilik
**Bundle ID:** com.turkcell.dergilik
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=432514382">432514382</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dergilik/id432514382?mt=8&uo=4">https://itunes.apple.com/us/app/dergilik/id432514382?mt=8&uo=4</a>
**App Version:** 3.6.1
**Seller:** TURKTELL BILISIM SERVISLERI A S
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/turktell-bilisim-servisleri-a-s/id877589107?uo=4">© TURKTELL BILISIM SERVISLERI A S</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/4f/44/7d/4f447da1-6f70-cfcb-3e76-b4cf8ee76127/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25782943/d273c93a-3353-11e7-8e5e-0fc650ea615e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/25782943/d273c93a-3353-11e7-8e5e-0fc650ea615e.png)
https://cloud.githubusercontent.com/assets/2068130/25782943/d273c93a-3353-11e7-8e5e-0fc650ea615e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/25782948/e0ef6410-3353-11e7-8e52-c1456056bb67.png
