### ISSUE TITLE
Trove - AI for Email

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9092]
**App Name:** Trove - AI for Email
**Bundle ID:** com.notion.mail
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=981989351">981989351</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trove-ai-for-email/id981989351?mt=8&uo=4">https://itunes.apple.com/us/app/trove-ai-for-email/id981989351?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** Notion AI, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/notion-ai-inc/id981989350?uo=4">© Notion AI, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/b5/3d/07/b53d0777-7dfd-41c7-795a-3351e84f8227/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25907258/4287bb96-35a7-11e7-8c55-13f1ce15fe3b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25907258/4287bb96-35a7-11e7-8c55-13f1ce15fe3b.png)
https://cloud.githubusercontent.com/assets/20930745/25907258/4287bb96-35a7-11e7-8c55-13f1ce15fe3b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25907293/55dbd682-35a7-11e7-9f54-26c5840ea461.png
