### ISSUE TITLE
UVLens - UV Index

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9093]
**App Name:** UVLens - UV Index
**Bundle ID:** com.spark64.uvlens.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1060878359">1060878359</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/uvlens-uv-index/id1060878359?mt=8&uo=4">https://itunes.apple.com/us/app/uvlens-uv-index/id1060878359?mt=8&uo=4</a>
**App Version:** 2.1.3
**Seller:** Spark Sixty Four Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/spark-64-ltd/id931762478?uo=4">© Spark 64 Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/e0/bc/c2/e0bcc270-e19f-158b-c60b-116df820c757/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25908052/7a30ce0a-35a9-11e7-9537-9a80318d197e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25908052/7a30ce0a-35a9-11e7-9537-9a80318d197e.png)
https://cloud.githubusercontent.com/assets/20930745/25908052/7a30ce0a-35a9-11e7-9537-9a80318d197e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25908074/8d6dbba4-35a9-11e7-9671-a65bde3ecf7f.png
