### ISSUE TITLE
Twitget - Widget for Twitter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9094]
**App Name:** Twitget - Widget for Twitter
**Bundle ID:** RLE.Twitget
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1207721460">1207721460</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/twitget-widget-for-twitter/id1207721460?mt=8&uo=4">https://itunes.apple.com/us/app/twitget-widget-for-twitter/id1207721460?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Erdei Robert
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/erdei-robert/id1207721459?uo=4">© Erdei Robert</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple127/v4/c5/c2/af/c5c2afc9-9518-b23f-c412-cbd653a398fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25908300/1e703370-35aa-11e7-8a88-d86b8cc2b99d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25908300/1e703370-35aa-11e7-8a88-d86b8cc2b99d.png)
https://cloud.githubusercontent.com/assets/20930745/25908300/1e703370-35aa-11e7-8a88-d86b8cc2b99d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25908340/396e4a90-35aa-11e7-9998-957985bd093c.png
