### ISSUE TITLE
FancyDays: Light Pro - Event Countdown

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9095]
**App Name:** FancyDays: Light Pro - Event Countdown
**Bundle ID:** co.crazycode.fancydays3pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1093873895">1093873895</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fancydays-light-pro-event-countdown/id1093873895?mt=8&uo=4">https://itunes.apple.com/us/app/fancydays-light-pro-event-countdown/id1093873895?mt=8&uo=4</a>
**App Version:** 3.3
**Seller:** Feng Mi
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/feng-mi/id829410500?uo=4">© Feng Mi</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/62/9b/ed/629beded-9423-f335-5724-3e59f16987d5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25908756/4b67d238-35ab-11e7-9383-975e03bd6f22.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25908756/4b67d238-35ab-11e7-9383-975e03bd6f22.png)
https://cloud.githubusercontent.com/assets/20930745/25908756/4b67d238-35ab-11e7-9383-975e03bd6f22.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25908777/60997bfc-35ab-11e7-88b3-75ee222b5ff9.png
