### ISSUE TITLE
Color Name - identifier, picker and matcher tool

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9096]
**App Name:** Color Name - identifier, picker and matcher tool
**Bundle ID:** com.colornameapp.Color-Name
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=904152346">904152346</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/color-name-identifier-picker-and-matcher-tool/id904152346?mt=8&uo=4">https://itunes.apple.com/us/app/color-name-identifier-picker-and-matcher-tool/id904152346?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Vlad Polyanskiy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vlad-polyanskiy/id438646985?uo=4">© Vlad Polyanskiy</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/de/9b/32/de9b322f-d6ca-c7ef-4f8f-619ba6de5e61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25909055/40adf1e6-35ac-11e7-9c19-e031895a2fac.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/25909055/40adf1e6-35ac-11e7-9c19-e031895a2fac.png)
https://cloud.githubusercontent.com/assets/20930745/25909055/40adf1e6-35ac-11e7-9c19-e031895a2fac.png

Source:
https://cloud.githubusercontent.com/assets/20930745/25909084/55c9a994-35ac-11e7-803e-0f6f08efd88a.png
