### ISSUE TITLE
The Google Assistant -- get help anytime, anywhere

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9107]
**App Name:** The Google Assistant -- get help anytime, anywhere
**Bundle ID:** com.google.OPA
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1220976145">1220976145</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-google-assistant-get-help-anytime-anywhere/id1220976145?mt=8&uo=4">https://itunes.apple.com/us/app/the-google-assistant-get-help-anytime-anywhere/id1220976145?mt=8&uo=4</a>
**App Version:** 1.0.609
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc/id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPadFourthGen4G-iPadFourthGen4G, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAirCellular-iPadAirCellular, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2Cellular-iPadAir2Cellular, iPadMini3Cellular-iPadMini3Cellular, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4Cellular-iPadMini4Cellular, iPadProCellular-iPadProCellular, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple127/v4/19/6a/f1/196af1a8-be39-0cc8-70fb-9c25adb7538f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26272237/c7f0c17e-3d13-11e7-91d2-5adbc8a686ef.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/3090247/26248629/be7f3af4-3c68-11e7-8109-501ad5a8c3be.png)
https://cloud.githubusercontent.com/assets/3090247/26248629/be7f3af4-3c68-11e7-8109-501ad5a8c3be.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/26248628/be7f2dca-3c68-11e7-99a7-dbd5b82513f0.png

**Comment by dreamnet** [comment]
Original size:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26272237/c7f0c17e-3d13-11e7-91d2-5adbc8a686ef.png)
https://cloud.githubusercontent.com/assets/2068130/26272237/c7f0c17e-3d13-11e7-91d2-5adbc8a686ef.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26272239/d74ae8f2-3d13-11e7-8e1b-7a0337158a53.png
