### ISSUE TITLE
Showrunner - The smart way to track TV Shows

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9109]
**App Name:** Showrunner - The smart way to track TV Shows
**Bundle ID:** com.nostalgika.ShowRunner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1200309550">1200309550</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/showrunner-the-smart-way-to-track-tv-shows/id1200309550?mt=8&uo=4">https://itunes.apple.com/us/app/showrunner-the-smart-way-to-track-tv-shows/id1200309550?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Nostalgika LTDA - ME
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nostalgika-ltda-me/id512781212?uo=4">© Nostalgika LTDA - ME</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple127/v4/4d/04/0d/4d040d9f-4621-77e8-7b81-fe2bdce922b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26311190/af35bbfc-3f03-11e7-9465-8d283d813229.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26311190/af35bbfc-3f03-11e7-9465-8d283d813229.png)
https://cloud.githubusercontent.com/assets/20930745/26311190/af35bbfc-3f03-11e7-9465-8d283d813229.png

Source::
https://cloud.githubusercontent.com/assets/20930745/26311216/caa9f36c-3f03-11e7-9f8b-cef641e0bfe9.png
