### ISSUE TITLE
Empower: Money, Budget and Savings Management App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9110]
**App Name:** Empower: Money, Budget and Savings Management App
**Bundle ID:** com.empower.finance
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1136397354">1136397354</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/empower-money-budget-and-savings-management-app/id1136397354?mt=8&uo=4">https://itunes.apple.com/us/app/empower-money-budget-and-savings-management-app/id1136397354?mt=8&uo=4</a>
**App Version:** 1.02
**Seller:** Empower Finance, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/empower-finance/id1126168232?uo=4">© Empower Finance</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple117/v4/a8/a2/2c/a8a22c33-0a37-1c78-d51e-7700e7a4977a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26311461/ae32fc78-3f04-11e7-8039-5db2ae7178c5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26311461/ae32fc78-3f04-11e7-8039-5db2ae7178c5.png)
https://cloud.githubusercontent.com/assets/20930745/26311461/ae32fc78-3f04-11e7-8039-5db2ae7178c5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26311487/be94ed56-3f04-11e7-9896-23dd599bace6.png
