### ISSUE TITLE
Ballz

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9111]
**App Name:** Ballz
**Bundle ID:** com.ketchapp.ballz
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1139609950">1139609950</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ballz/id1139609950?mt=8&uo=4">https://itunes.apple.com/us/app/ballz/id1139609950?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Ketchapp
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ketchapp/id528065807?uo=4">© Ketchapp</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/b5/53/fa/b553fabb-64db-d0f5-600a-8bec98d706a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26311729/9a4c0190-3f05-11e7-84f5-8a400871ce71.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26311729/9a4c0190-3f05-11e7-84f5-8a400871ce71.png)
https://cloud.githubusercontent.com/assets/20930745/26311729/9a4c0190-3f05-11e7-84f5-8a400871ce71.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26311754/ad802bce-3f05-11e7-8b18-867642db5a28.png
