### ISSUE TITLE
4 Fotos 1 Palabra

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9116]
**App Name:** 4 Fotos 1 Palabra
**Bundle ID:** de.lotum.4pics1wordes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598945891">598945891</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/4-fotos-1-palabra/id598945891?mt=8&uo=4">https://itunes.apple.com/us/app/4-fotos-1-palabra/id598945891?mt=8&uo=4</a>
**App Version:** 7.2.1
**Seller:** LOTUM GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lotum-gmbh/id459029666?uo=4">© LOTUM GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/de/a7/ab/dea7abf2-2ad7-8618-9ec3-68eb9a056613/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26436674/6f7ae0ac-4118-11e7-85d1-ffeacb4c8b7e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26436674/6f7ae0ac-4118-11e7-85d1-ffeacb4c8b7e.png)
https://cloud.githubusercontent.com/assets/2068130/26436674/6f7ae0ac-4118-11e7-85d1-ffeacb4c8b7e.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26436685/7e076186-4118-11e7-9764-1ec9ca64ee7b.png
