### ISSUE TITLE
Avast SecureLine VPN Proxy

### ISSUE THREAD

**Issue by catalyst7even** [glasklart/hd#9118]
**App Name:** Avast SecureLine VPN Proxy
**Bundle ID:** com.avast.ios.secureline2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=793096595">793096595</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/avast-secureline-vpn-proxy/id793096595?uo=4">https://apps.apple.com/us/app/avast-secureline-vpn-proxy/id793096595?uo=4</a>
**App Version:** 5.6.0
**Seller:** AVAST Software a.s.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/avast-software/id568017534?uo=4">© AVAST Software</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/4a/03/a2/4a03a2fc-8ec7-07f4-4a8b-f7bc12545a2b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59978886-76833000-95e1-11e9-95be-1cb138d0c518.png)

**Comment by catalyst7even** [comment]
![com avast ios secureline2 3x](https://cloud.githubusercontent.com/assets/28825533/26478744/fcaa45c8-4193-11e7-9e03-1ed276286f51.png)
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/28825533/26478744/fcaa45c8-4193-11e7-9e03-1ed276286f51.png)
https://cloud.githubusercontent.com/assets/28825533/26478733/e0e0de60-4193-11e7-9bbf-888a11bfa477.png

**Comment by dreamnet** [comment]
@catalyst7even Good work 👍, but you need to keep original size and aspect ratio - here is a correct contribution, just compare:
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26483120/b1afdbca-41eb-11e7-9b9b-9862ed55c210.png)
https://cloud.githubusercontent.com/assets/2068130/26483120/b1afdbca-41eb-11e7-9b9b-9862ed55c210.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26483137/c396a9c2-41eb-11e7-8a3a-f5ac9a4213f8.png

**Comment by catalyst7even** [comment]
Sorry. I originally had it that way but truly got confused clicking from one instruction link to another. One mentioned to stretch the created black source image out to the 1024 px border. Thanks for clarifying!

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?ìmage=https://user-images.githubusercontent.com/2068130/59978886-76833000-95e1-11e9-95be-1cb138d0c518.png)
https://user-images.githubusercontent.com/2068130/59978886-76833000-95e1-11e9-95be-1cb138d0c518.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59978891-89960000-95e1-11e9-8f6f-db16feb3cf17.png
