### ISSUE TITLE
WorkTimes - Time Tracking with Overtime Calculation

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9137]
**App Name:** WorkTimes - Time Tracking with Overtime Calculation
**Bundle ID:** com.madefm.worktimes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=337769011">337769011</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/worktimes-time-tracking-with-overtime-calculation/id337769011?mt=8&uo=4">https://itunes.apple.com/us/app/worktimes-time-tracking-with-overtime-calculation/id337769011?mt=8&uo=4</a>
**App Version:** 5.2
**Seller:** Florian Mielke
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/florian-mielke/id337769014?uo=4">© Florian Mielke</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple18/v4/bd/8a/fe/bd8afea6-eb12-719b-417b-f4aab9c32f0e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26524560/21b55c6e-4337-11e7-8772-41344b9c1dc9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26524560/21b55c6e-4337-11e7-8772-41344b9c1dc9.png)
https://cloud.githubusercontent.com/assets/20930745/26524560/21b55c6e-4337-11e7-8772-41344b9c1dc9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26524564/40afeb48-4337-11e7-80f9-a9125753160d.png
