### ISSUE TITLE
gTasks Pro - Tasks for Google, Todo & Reminders

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9138]
**App Name:** gTasks Pro - Tasks for Google, Todo & Reminders
**Bundle ID:** com.katans.adam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=672241079">672241079</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gtasks-pro-tasks-for-google-todo-reminders/id672241079?mt=8&uo=4">https://itunes.apple.com/us/app/gtasks-pro-tasks-for-google-todo-reminders/id672241079?mt=8&uo=4</a>
**App Version:** 4.9.7
**Seller:** Yaniv Katan
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yaniv-katan/id427694580?uo=4">© Yaniv Katan</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/b2/ac/a5/b2aca56f-a131-6949-5113-25af96312089/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26524578/e4f3d11a-4337-11e7-8e61-bea3e8b449c7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26524578/e4f3d11a-4337-11e7-8e61-bea3e8b449c7.png)
https://cloud.githubusercontent.com/assets/20930745/26524578/e4f3d11a-4337-11e7-8e61-bea3e8b449c7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26524583/f64bca44-4337-11e7-93a2-10d57d025990.png
