### ISSUE TITLE
ICICI Bank Mobile Banking - iMobile

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9139]
**App Name:** ICICI Bank Mobile Banking - iMobile
**Bundle ID:** com.icicibank.imobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375276006">375276006</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/icici-bank-mobile-banking-imobile/id375276006?mt=8&uo=4">https://itunes.apple.com/us/app/icici-bank-mobile-banking-imobile/id375276006?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** ICICI Bank Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/icici-bank-ltd/id375276009?uo=4">© ICICI Bank Ltd.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/50/ad/14/50ad14c7-0283-e47a-f5f1-b16c33609754/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26687950/8f036852-46f1-11e7-982b-71c61ab0b586.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26687950/8f036852-46f1-11e7-982b-71c61ab0b586.png)
https://cloud.githubusercontent.com/assets/20930745/26687950/8f036852-46f1-11e7-982b-71c61ab0b586.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26687974/a1c765ec-46f1-11e7-800b-6143a2ae5cbe.png
