### ISSUE TITLE
Gitter - Chat for communities

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9140]
**App Name:** Gitter - Chat for communities
**Bundle ID:** com.gitter.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=886185078">886185078</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gitter-chat-for-communities/id886185078?mt=8&uo=4">https://itunes.apple.com/us/app/gitter-chat-for-communities/id886185078?mt=8&uo=4</a>
**App Version:** 4.2.0
**Seller:** Troupe Technology Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/troupe-technology-limited/id480528943?uo=4">© Troupe Technology Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/11/25/dd/1125dd76-05fa-613c-a1de-d6e142c545ef/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26688142/28b8241a-46f2-11e7-9e06-fba415088ae9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26688142/28b8241a-46f2-11e7-9e06-fba415088ae9.png)
https://cloud.githubusercontent.com/assets/20930745/26688142/28b8241a-46f2-11e7-9e06-fba415088ae9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26688158/3ac48f40-46f2-11e7-87b9-4ba783748125.png
