### ISSUE TITLE
Hotstar TV Movies Live Cricket

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9141]
**App Name:** Hotstar TV Movies Live Cricket
**Bundle ID:** in.startv.hotstar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=934459219">934459219</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/in/app/hotstar-tv-movies-live-cricket/id934459219?mt=8&uo=4">https://itunes.apple.com/in/app/hotstar-tv-movies-live-cricket/id934459219?mt=8&uo=4</a>
**App Version:** 5.14.2
**Seller:** Novi Digital Entertainment Pvt. Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/in/developer/novi-digital-entertainment-pvt-ltd/id440687246?uo=4">© Novi Digital Entertainment Pvt. Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple127/v4/70/1f/4e/701f4e17-b401-f50a-dc38-1f0851ef5eec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26739350/c4e72d9c-47d1-11e7-82c7-fa45a832d572.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26739350/c4e72d9c-47d1-11e7-82c7-fa45a832d572.png)
https://cloud.githubusercontent.com/assets/2068130/26739350/c4e72d9c-47d1-11e7-82c7-fa45a832d572.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26739373/d49321ec-47d1-11e7-9161-a59ac8cbd100.png
