### ISSUE TITLE
Saavn Music & Radio

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9142]
**App Name:** Saavn Music & Radio
**Bundle ID:** com.Saavn.Saavn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=441813332">441813332</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/saavn-music-radio/id441813332?mt=8&uo=4">https://itunes.apple.com/us/app/saavn-music-radio/id441813332?mt=8&uo=4</a>
**App Version:** 5.8
**Seller:** Saavn
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/saavn/id441813335?uo=4">© Saavn</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple127/v4/b5/53/0f/b5530faf-0ac6-aa0a-7047-a4dbeafaee01/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26688356/af3a6ce6-46f2-11e7-828e-68861a5feac9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26688356/af3a6ce6-46f2-11e7-828e-68861a5feac9.png)
https://cloud.githubusercontent.com/assets/20930745/26688356/af3a6ce6-46f2-11e7-828e-68861a5feac9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26688376/c2915dd6-46f2-11e7-8c56-afb82bd92cd4.png
