### ISSUE TITLE
Alarmy (Sleep If U Can)- Alarm clock

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9143]
**App Name:** Alarmy (Sleep If U Can)- Alarm clock
**Bundle ID:** droom.sleepIfUCanFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1163786766">1163786766</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alarmy-sleep-if-u-can-alarm-clock/id1163786766?mt=8&uo=4">https://itunes.apple.com/us/app/alarmy-sleep-if-u-can-alarm-clock/id1163786766?mt=8&uo=4</a>
**App Version:** 4.1.7
**Seller:** Delight Room Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/delight-room-co-ltd/id609598561?uo=4">© Delight Room Co., Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/65/76/b8/6576b820-e431-6f70-9738-9d2e75f13bbc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26688555/411964c8-46f3-11e7-814f-d1e21db5edb2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26688555/411964c8-46f3-11e7-814f-d1e21db5edb2.png)
https://cloud.githubusercontent.com/assets/20930745/26688555/411964c8-46f3-11e7-814f-d1e21db5edb2.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26688582/56ec4ae0-46f3-11e7-85ec-feb5e7b579a2.png
