### ISSUE TITLE
Golf Clash

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9144]
**App Name:** Golf Clash
**Bundle ID:** com.playdemic.golf
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1089225191">1089225191</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/golf-clash/id1089225191?mt=8&uo=4">https://itunes.apple.com/us/app/golf-clash/id1089225191?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Playdemic Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/playdemic/id505151958?uo=4">© Playdemic</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple117/v4/9f/78/32/9f78328a-e555-5da4-eda3-f4e0102df21e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26743347/bf786bcc-47e1-11e7-915a-416932299ad0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26743347/bf786bcc-47e1-11e7-915a-416932299ad0.png)
https://cloud.githubusercontent.com/assets/2068130/26743347/bf786bcc-47e1-11e7-915a-416932299ad0.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26743363/ce66c160-47e1-11e7-9c16-50ab287a77a7.png
