### ISSUE TITLE
Medium

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9145]
**App Name:** Medium
**Bundle ID:** com.medium.reader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=828256236">828256236</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/medium/id828256236?mt=8&uo=4">https://itunes.apple.com/us/app/medium/id828256236?mt=8&uo=4</a>
**App Version:** 2.54
**Seller:** A Medium Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/a-medium-corporation/id828256239?uo=4">© A Medium Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple127/v4/0f/e9/7d/0fe97dfd-dfc0-c167-7ef7-7062ab5e6969/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26689791/281088cc-46f7-11e7-81b6-2144218dc943.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26689791/281088cc-46f7-11e7-81b6-2144218dc943.png)
https://cloud.githubusercontent.com/assets/20930745/26689791/281088cc-46f7-11e7-81b6-2144218dc943.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26689807/3dab6e4a-46f7-11e7-81f1-d3824ec114c8.png
