### ISSUE TITLE
CamScanner Free| PDF Document Scanner and OCR

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9146]
**App Name:** CamScanner Free| PDF Document Scanner and OCR
**Bundle ID:** com.intsig.CamScannerLite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=388627783">388627783</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camscanner-free-pdf-document-scanner-and-ocr/id388627783?mt=8&uo=4">https://itunes.apple.com/us/app/camscanner-free-pdf-document-scanner-and-ocr/id388627783?mt=8&uo=4</a>
**App Version:** 4.4.2
**Seller:** INTSIG Information Co.,Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/intsig-information-co-ltd/id344077850?uo=4">© INTSIG Information Co.,Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple117/v4/09/ed/88/09ed884c-9c54-f2b3-bb8d-d3634475609d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26688780/e949dbb4-46f3-11e7-980c-0c88e8dfbb98.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26688780/e949dbb4-46f3-11e7-980c-0c88e8dfbb98.png)
https://cloud.githubusercontent.com/assets/20930745/26688780/e949dbb4-46f3-11e7-980c-0c88e8dfbb98.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26688816/fe7a46fe-46f3-11e7-97c2-07c16b0b88f6.png
