### ISSUE TITLE
My Airtel-Recharge, Pay Bill, Payments Bank

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9147]
**App Name:** My Airtel-Recharge, Pay Bill, Payments Bank
**Bundle ID:** com.BhartiMobile.myairtel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=543184334">543184334</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-airtel-recharge-pay-bill-payments-bank/id543184334?mt=8&uo=4">https://itunes.apple.com/us/app/my-airtel-recharge-pay-bill-payments-bank/id543184334?mt=8&uo=4</a>
**App Version:** 4.4.4
**Seller:** Bharti Airtel Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bharti-airtel-ltd/id440691295?uo=4">© Bharti Airtel Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/7b/a2/cb/7ba2cb95-e985-abc8-24c3-55ded071d41c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26688982/780cd78e-46f4-11e7-8067-dddfb0d44461.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26688982/780cd78e-46f4-11e7-8067-dddfb0d44461.png)
https://cloud.githubusercontent.com/assets/20930745/26688982/780cd78e-46f4-11e7-8067-dddfb0d44461.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26689009/8f5228fe-46f4-11e7-9c09-32ee8e0cc973.png
