### ISSUE TITLE
Paytm - Payments, Wallet & Recharges

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9148]
**App Name:** Paytm - Payments, Wallet & Recharges
**Bundle ID:** com.one97.paytm
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=473941634">473941634</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paytm-payments-wallet-recharges/id473941634?mt=8&uo=4">https://itunes.apple.com/us/app/paytm-payments-wallet-recharges/id473941634?mt=8&uo=4</a>
**App Version:** 5.10.2
**Seller:** PayTM Mobile Solutions Private Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/paytm-mobile-solutions/id473941637?uo=4">© Paytm Mobile Solutions</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/9d/a4/9c/9da49c83-7474-e1e7-910a-bbd7919d1aa6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26689293/7c5cfe3a-46f5-11e7-9d36-0f06f9bf3db9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26689293/7c5cfe3a-46f5-11e7-9d36-0f06f9bf3db9.png)
https://cloud.githubusercontent.com/assets/20930745/26689293/7c5cfe3a-46f5-11e7-9d36-0f06f9bf3db9.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26689318/92043e6a-46f5-11e7-8cd1-190282dccfb5.png
