### ISSUE TITLE
Newspad - The most simple and readable news reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9149]
**App Name:** Newspad - The most simple and readable news reader
**Bundle ID:** me.newspad.Newspad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=946644892">946644892</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/newspad-the-most-simple-and-readable-news-reader/id946644892?mt=8&uo=4">https://itunes.apple.com/us/app/newspad-the-most-simple-and-readable-news-reader/id946644892?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Kojiro Futamura
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gumob/id380413101?uo=4">© Gumob</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple127/v4/25/42/ac/2542ac64-68da-42fd-459a-3d0ad4a93063/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26733019/dfa36780-47b9-11e7-8d47-0b1d7d6d8275.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26733019/dfa36780-47b9-11e7-8d47-0b1d7d6d8275.png)
https://cloud.githubusercontent.com/assets/20930745/26733019/dfa36780-47b9-11e7-8d47-0b1d7d6d8275.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26733056/f702de10-47b9-11e7-8e5d-af7932e2a73a.png
