### ISSUE TITLE
EXIF Viewer by Fluntro - View, Remove GPS Metadata

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9150]
**App Name:** EXIF Viewer by Fluntro - View, Remove GPS Metadata
**Bundle ID:** com.fluntro.exif
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944118456">944118456</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/exif-viewer-by-fluntro-view-remove-gps-metadata/id944118456?mt=8&uo=4">https://itunes.apple.com/us/app/exif-viewer-by-fluntro-view-remove-gps-metadata/id944118456?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Mohith km
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fluntro/id497684641?uo=4">© Fluntro</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple127/v4/46/1d/1c/461d1c32-ef52-a407-a7d2-ae4f10d72c01/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26733420/1122519e-47bb-11e7-8fae-5c838fe74e98.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26733420/1122519e-47bb-11e7-8fae-5c838fe74e98.png)
https://cloud.githubusercontent.com/assets/20930745/26733420/1122519e-47bb-11e7-8fae-5c838fe74e98.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26733451/27bb4b9a-47bb-11e7-958f-5eaa124f91c5.png
