### ISSUE TITLE
TVist - TV Guide & Listings

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9151]
**App Name:** TVist - TV Guide & Listings
**Bundle ID:** com.ardourlabs.Mizzle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1232203457">1232203457</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tvist-tv-guide-listings/id1232203457?mt=8&uo=4">https://itunes.apple.com/us/app/tvist-tv-guide-listings/id1232203457?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Ardour Labs Private Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ardour-labs-private-limited/id1227412349?uo=4">© Ardour Labs Private Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/4e/54/49/4e5449d8-68ad-3fae-6f7d-e9b52bc33752/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145203-d387ef9a-bcc4-11e7-93b9-934c0b7aee26.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26733616/a7a4c232-47bb-11e7-8284-aaabb2216046.png)
https://cloud.githubusercontent.com/assets/20930745/26733616/a7a4c232-47bb-11e7-8284-aaabb2216046.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26733638/b9e47cee-47bb-11e7-8c7a-2238aeecc2a0.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Mizzle - your TV Guide, Listings, Tracker
**Bundle ID:** com.ardourlabs.Mizzle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1232203457">1232203457</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mizzle-your-tv-guide-listings-tracker/id1232203457?mt=8&uo=4">https://itunes.apple.com/us/app/mizzle-your-tv-guide-listings-tracker/id1232203457?mt=8&uo=4</a>
**App Version:** 0.11
**Seller:** Ardour Labs Private Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ardour-labs-private-limited/id1227412349?uo=4">© Ardour Labs Private Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/92/67/22/926722b3-463c-69ba-9e59-7c3ccb0abde9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29238879-6eb67ab4-7f3e-11e7-9da8-eac01e3f1793.png)
https://user-images.githubusercontent.com/2068130/29238879-6eb67ab4-7f3e-11e7-9da8-eac01e3f1793.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29238884-7dbc0286-7f3e-11e7-9c1a-7510779b243a.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** TVist - TV Guide & Listings
**Bundle ID:** com.ardourlabs.Mizzle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1232203457">1232203457</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tvist-tv-guide-listings/id1232203457?mt=8&uo=4">https://itunes.apple.com/us/app/tvist-tv-guide-listings/id1232203457?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Ardour Labs Private Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ardour-labs-private-limited/id1227412349?uo=4">© Ardour Labs Private Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/4e/54/49/4e5449d8-68ad-3fae-6f7d-e9b52bc33752/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145203-d387ef9a-bcc4-11e7-93b9-934c0b7aee26.png)
https://user-images.githubusercontent.com/20930745/32145203-d387ef9a-bcc4-11e7-93b9-934c0b7aee26.png

Source:
https://user-images.githubusercontent.com/20930745/32145209-e7efbfc6-bcc4-11e7-809f-ff00aeb0a82f.png
