### ISSUE TITLE
Microsoft To-Do

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9152]
**App Name:** Microsoft To-Do
**Bundle ID:** com.microsoft.to-do
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1212616790">1212616790</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-to-do/id1212616790?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-to-do/id1212616790?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4">© Microsoft Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/ff/20/cb/ff20cbad-61e1-b217-ddea-6312bcb3f46e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26733835/5ebe8566-47bc-11e7-858d-246cc1b0654e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26733835/5ebe8566-47bc-11e7-858d-246cc1b0654e.png)
https://cloud.githubusercontent.com/assets/20930745/26733835/5ebe8566-47bc-11e7-858d-246cc1b0654e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26733865/71ba93f8-47bc-11e7-9407-2e3926d216ba.png
