### ISSUE TITLE
AutoZone

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#9156]
**App Name:** AutoZone
**Bundle ID:** com.autozone.mobileapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=375381161">375381161</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/autozone/id375381161?mt=8&uo=4">https://itunes.apple.com/us/app/autozone/id375381161?mt=8&uo=4</a>
**App Version:** 2.3.3
**Seller:** AutoZone, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/autozone-inc/id375381164?uo=4">© AutoZone, Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/07/04/69/0704695e-2312-3427-22d6-646687d4c955/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26760276/a89ec3f4-4914-11e7-913b-0cb3addcd247.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26760168/1cd2dc7c-4912-11e7-942b-0a1e103a1047.png)
https://cloud.githubusercontent.com/assets/20930745/26760168/1cd2dc7c-4912-11e7-942b-0a1e103a1047.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26760171/314f868c-4912-11e7-989e-ea560d537f61.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26760276/a89ec3f4-4914-11e7-913b-0cb3addcd247.png)
https://cloud.githubusercontent.com/assets/20930745/26760276/a89ec3f4-4914-11e7-913b-0cb3addcd247.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26760282/bcf0c60e-4914-11e7-9224-2e8f9fb585dc.png
