### ISSUE TITLE
CARFAX Find Used Cars for Sale

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#9159]
**App Name:** CARFAX Find Used Cars for Sale
**Bundle ID:** com.carfax.ConsumerApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479267592">479267592</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/carfax-find-used-cars-for-sale/id479267592?uo=4">https://apps.apple.com/us/app/carfax-find-used-cars-for-sale/id479267592?uo=4</a>
**App Version:** 4.20.1
**Seller:** CARFAX, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/carfax-inc/id414553622?uo=4">© CARFAX, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/27/85/87/27858792-1aa8-3a9d-d2a4-a66f60219325/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380291-a730f280-9a43-11e9-96bd-4f0fd00e4e20.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26775287/8692baac-49d4-11e7-90fb-c94663b01ad7.png)
https://cloud.githubusercontent.com/assets/2068130/26775287/8692baac-49d4-11e7-90fb-c94663b01ad7.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26775295/9489a5ee-49d4-11e7-81ce-39e32df916a4.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380291-a730f280-9a43-11e9-96bd-4f0fd00e4e20.png)
https://user-images.githubusercontent.com/20930745/60380291-a730f280-9a43-11e9-96bd-4f0fd00e4e20.png

Source:
https://user-images.githubusercontent.com/20930745/60380292-a9934c80-9a43-11e9-9c49-c3356f6c76f0.png
