### ISSUE TITLE
Musemage - Get that cinematic look

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#9163]
**App Name:** Musemage - Get that cinematic look
**Bundle ID:** com.Paraken.Musemage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=951615851">951615851</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/musemage-get-that-cinematic-look/id951615851?mt=8&uo=4">https://itunes.apple.com/us/app/musemage-get-that-cinematic-look/id951615851?mt=8&uo=4</a>
**App Version:** 3.0.7
**Seller:** Chengdu Pingxingshiye Technology Co., Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/paraken-technology-co-ltd/id951615850?uo=4">© Paraken Technology Co., Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/1c/92/48/1c92489b-4e28-a552-7ae6-715008d37409/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26760244/aa990094-4913-11e7-9f61-f54615887b62.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26760244/aa990094-4913-11e7-9f61-f54615887b62.png)
https://cloud.githubusercontent.com/assets/20930745/26760244/aa990094-4913-11e7-9f61-f54615887b62.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26760250/bc190508-4913-11e7-85e3-7a97d1aa4b95.png
