### ISSUE TITLE
BillionGraves Camera App

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#9164]
**App Name:** BillionGraves Camera App
**Bundle ID:** com.och.BillionGraves
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=602792141">602792141</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/billiongraves-camera-app/id602792141?mt=8&uo=4">https://itunes.apple.com/us/app/billiongraves-camera-app/id602792141?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** Otter Creek Holdings, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/otter-creek-holdings-llc/id602792144?uo=4">© Otter Creek Holdings, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/47/7a/12/477a12e2-42e3-8bcb-0869-05f5c1737fda/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27167942-c05ae9c2-51a3-11e7-8113-17e39adc4fed.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27167942-c05ae9c2-51a3-11e7-8113-17e39adc4fed.png)
https://user-images.githubusercontent.com/2068130/27167942-c05ae9c2-51a3-11e7-8113-17e39adc4fed.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27167957-d2e7fe5e-51a3-11e7-82ef-4f404112ce7b.png
