### ISSUE TITLE
ObitFinder

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#9165]
**App Name:** ObitFinder
**Bundle ID:** com.legacy.ObitFinder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=464840275">464840275</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/obitfinder/id464840275?mt=8&uo=4">https://itunes.apple.com/us/app/obitfinder/id464840275?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Legacy.com, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/legacy-com/id464840278?uo=4">© Legacy.com®</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple22/v4/c8/2d/64/c82d64f4-3877-0f2f-9187-e23f7322c041/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26760189/984882f8-4912-11e7-8218-4371ecc44b5a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26760189/984882f8-4912-11e7-8218-4371ecc44b5a.png)
https://cloud.githubusercontent.com/assets/20930745/26760189/984882f8-4912-11e7-8218-4371ecc44b5a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26760193/a781cdce-4912-11e7-844b-611754b42a81.png
