### ISSUE TITLE
efood.gr

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9166]
**App Name:** efood.gr
**Bundle ID:** gr.invoke.eshop.e-food-gr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=621353976">621353976</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/efood-gr/id621353976?uo=4">https://apps.apple.com/us/app/efood-gr/id621353976?uo=4</a>
**App Version:** 3.0.0
**Seller:** OFD Online Food Delivery Services Ltd.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/e-food-gr/id703477158?uo=4">© e-food.gr</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/34/41/74/34417411-c947-4d70-9daa-258bf9fc7037/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388320-e4cb6500-9aaf-11e9-89f7-8f76f71dcf0c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26771677/92f50322-49c0-11e7-84e6-763f45ff7ccc.png)
https://cloud.githubusercontent.com/assets/2068130/26771677/92f50322-49c0-11e7-84e6-763f45ff7ccc.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26771681/a179b6a4-49c0-11e7-8a49-751717868846.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388320-e4cb6500-9aaf-11e9-89f7-8f76f71dcf0c.png)
https://user-images.githubusercontent.com/20930745/60388320-e4cb6500-9aaf-11e9-89f7-8f76f71dcf0c.png

Source:
https://user-images.githubusercontent.com/20930745/60388322-e7c65580-9aaf-11e9-89e2-8506cf605b5d.png
