### ISSUE TITLE
Bank of Cyprus - Τράπεζα Κύπρου

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9167]
**App Name:** Bank of Cyprus - Τράπεζα Κύπρου
**Bundle ID:** com.bankofcyprus.bankofcyprus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=518802910">518802910</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bank-of-cyprus-%CF%84%CF%81%CE%AC%CF%80%CE%B5%CE%B6%CE%B1-%CE%BA%CF%8D%CF%80%CF%81%CE%BF%CF%85/id518802910?mt=8&uo=4">https://itunes.apple.com/us/app/bank-of-cyprus-%CF%84%CF%81%CE%AC%CF%80%CE%B5%CE%B6%CE%B1-%CE%BA%CF%8D%CF%80%CF%81%CE%BF%CF%85/id518802910?mt=8&uo=4</a>
**App Version:** 3.2.6
**Seller:** Bank of Cyprus Public Company Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bank-of-cyprus-public-company-ltd/id497720237?uo=4">© Bank of Cyprus Public Company Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/3e/9f/65/3e9f6551-ba04-9f1b-f402-f3f7c996cd9c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26771738/33e3be4a-49c1-11e7-9862-f9a23184a6d5.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26771738/33e3be4a-49c1-11e7-9862-f9a23184a6d5.png)
https://cloud.githubusercontent.com/assets/2068130/26771738/33e3be4a-49c1-11e7-9862-f9a23184a6d5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26771744/41c685e2-49c1-11e7-811d-d5a829ffa847.png
