### ISSUE TITLE
My CU

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9168]
**App Name:** My CU
**Bundle ID:** vodafone.VodafoneCU
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=940514074">940514074</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gr/app/my-cu/id940514074?mt=8&uo=4">https://itunes.apple.com/gr/app/my-cu/id940514074?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Vodafone-Panafon S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/gr/developer/vodafone-greece/id375967694?uo=4">© Vodafone Greece</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple127/v4/77/36/36/7736360c-e420-56ed-15ec-a1e2a58bf0aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26772300/e5a4db98-49c4-11e7-9410-91ae623523fe.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26772300/e5a4db98-49c4-11e7-9410-91ae623523fe.png)
https://cloud.githubusercontent.com/assets/2068130/26772300/e5a4db98-49c4-11e7-9410-91ae623523fe.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26772309/f9be5000-49c4-11e7-835a-ef214b055fb0.png
