### ISSUE TITLE
PATRAS Bus

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9169]
**App Name:** PATRAS Bus
**Bundle ID:** com.threepi.adep-info
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=988405273">988405273</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/patras-bus/id988405273?mt=8&uo=4">https://itunes.apple.com/us/app/patras-bus/id988405273?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** 3PI INFORMATION SYSTEMS SOLE SHAREHOLDER CO. LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/3pi-information-systems/id703327712?uo=4">© 3pi Information Systems</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/07/da/82/07da8225-68ce-254e-91ff-5dfdd2b5eaec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26772120/e411a956-49c3-11e7-95d4-77cb668a5b48.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/26772120/e411a956-49c3-11e7-95d4-77cb668a5b48.png)
https://cloud.githubusercontent.com/assets/2068130/26772120/e411a956-49c3-11e7-95d4-77cb668a5b48.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/26772129/f2b6d76a-49c3-11e7-936f-0c6410bd6f77.png
