### ISSUE TITLE
Television Time

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9172]
**App Name:** Television Time
**Bundle ID:** com.litteral.TVShows
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=969714962">969714962</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/television-time/id969714962?mt=8&uo=4">https://itunes.apple.com/us/app/television-time/id969714962?mt=8&uo=4</a>
**App Version:** 1.3.6
**Seller:** Maximilian Litteral
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/maximilian-litteral/id467232088?uo=4">© Maximilian Litteral</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/1d/ab/d3/1dabd356-bbf0-7e0c-da5c-f7b4ad021b8f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26777545/e9c78c2a-49dd-11e7-9e6f-830bad115bbb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26777545/e9c78c2a-49dd-11e7-9e6f-830bad115bbb.png)
https://cloud.githubusercontent.com/assets/20930745/26777545/e9c78c2a-49dd-11e7-9e6f-830bad115bbb.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26777564/fea7989c-49dd-11e7-9449-32377b07da91.png
