### ISSUE TITLE
Fridays Cyprus - Rewards

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9173]
**App Name:** Fridays Cyprus - Rewards
**Bundle ID:** com.punchh.tgifcy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1185437459">1185437459</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/fridays-cyprus-rewards/id1185437459?mt=8&uo=4">https://itunes.apple.com/gb/app/fridays-cyprus-rewards/id1185437459?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Punchh Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/punchh-inc/id386700205?uo=4">© Punchh Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/d0/82/8e/d0828e06-99a1-96f3-2fb6-5ef37a7fc855/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26777768/aeacdbe4-49de-11e7-8fd1-bb8371477ea7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26777768/aeacdbe4-49de-11e7-8fd1-bb8371477ea7.png)
https://cloud.githubusercontent.com/assets/20930745/26777768/aeacdbe4-49de-11e7-8fd1-bb8371477ea7.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26777781/c1d2c198-49de-11e7-9c1f-f45766772529.png
