### ISSUE TITLE
Gearbest Online Shopping

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9174]
**App Name:** Gearbest Online Shopping
**Bundle ID:** com.globalegrow.gearbest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1131090631">1131090631</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gearbest-online-shopping/id1131090631?uo=4">https://apps.apple.com/us/app/gearbest-online-shopping/id1131090631?uo=4</a>
**App Version:** 4.3.0
**Seller:** TJ198 Network Technology(HK) Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tj198-network-technology-hk-limited/id1038278986?uo=4">© TJ198 Network Technology(HK) Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/21/9f/d5/219fd531-755a-2bed-1b96-709aaa136784/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60539281-923ab480-9d0c-11e9-8dd5-5b8f6c6c1b44.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26777928/6cfe87dc-49df-11e7-8edc-7d4957ae749f.png)
https://cloud.githubusercontent.com/assets/20930745/26777928/6cfe87dc-49df-11e7-8edc-7d4957ae749f.png)


Source:
https://cloud.githubusercontent.com/assets/20930745/26777953/7f3c0e42-49df-11e7-8f9b-9f34347f2cc3.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60539281-923ab480-9d0c-11e9-8dd5-5b8f6c6c1b44.png)
https://user-images.githubusercontent.com/20930745/60539281-923ab480-9d0c-11e9-8dd5-5b8f6c6c1b44.png

Source:
https://user-images.githubusercontent.com/20930745/60539282-936be180-9d0c-11e9-9bcd-fff061062308.png
