### ISSUE TITLE
ΔΕΗ

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9175]
**App Name:** ΔΕΗ
**Bundle ID:** com.ogilvyone.dei
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=978348079">978348079</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%CE%B4%CE%B5%CE%B7/id978348079?mt=8&uo=4">https://itunes.apple.com/us/app/%CE%B4%CE%B5%CE%B7/id978348079?mt=8&uo=4</a>
**App Version:** 1.8.2
**Seller:** PUBLIC POWER CORPORATION S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/%CE%B4%CE%B5%CE%B7/id978348078?uo=4">© ΔΕΗ</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/0e/34/30/0e34307e-0ac0-8f17-3839-acd77874620c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26778130/4ced8a78-49e0-11e7-8795-cc3fde0b6066.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26778130/4ced8a78-49e0-11e7-8795-cc3fde0b6066.png)
https://cloud.githubusercontent.com/assets/20930745/26778130/4ced8a78-49e0-11e7-8795-cc3fde0b6066.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26778148/5fcce8e6-49e0-11e7-8f6f-a2b3721b605e.png
