### ISSUE TITLE
Alpha Bank Mobile Banking

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9176]
**App Name:** Alpha Bank Mobile Banking
**Bundle ID:** gr.alpha.iphonebanking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=378674531">378674531</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alpha-bank-mobile-banking/id378674531?mt=8&uo=4">https://itunes.apple.com/us/app/alpha-bank-mobile-banking/id378674531?mt=8&uo=4</a>
**App Version:** 3.4.1
**Seller:** Alpha Bank
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alpha-bank-a-e/id378674534?uo=4">© Alpha Bank A.E.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/f3/6b/b1/f36bb1de-00d3-c51b-ed8c-407c30df5261/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38455611-e7bfcc6a-3a7a-11e8-9f14-9fe597642d89.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/26778464/a5dbc9dc-49e1-11e7-943a-4324a6167e03.png)
https://cloud.githubusercontent.com/assets/20930745/26778464/a5dbc9dc-49e1-11e7-943a-4324a6167e03.png

Source:
https://cloud.githubusercontent.com/assets/20930745/26778481/baa9cd00-49e1-11e7-9f54-406a3d31b92d.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38455611-e7bfcc6a-3a7a-11e8-9f14-9fe597642d89.png)
https://user-images.githubusercontent.com/20930745/38455611-e7bfcc6a-3a7a-11e8-9f14-9fe597642d89.png

Source:
https://user-images.githubusercontent.com/20930745/38455617-f69620ae-3a7a-11e8-8d69-58bd7e9c2997.png
