### ISSUE TITLE
ROMANCING SAGA 2

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#9177]
**App Name:** ROMANCING SAGA 2
**Bundle ID:** com.square-enix.romancingsaga2w
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1083835330">1083835330</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/romancing-saga-2/id1083835330?mt=8&uo=4">https://itunes.apple.com/us/app/romancing-saga-2/id1083835330?mt=8&uo=4</a>
**App Version:** 1.01
**Seller:** SQUARE ENIX Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/square-enix-inc/id300186801?mt=8&uo=4">© SQUARE ENIX INC</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple20/v4/33/0b/de/330bdeb0-7471-8b46-7044-d3fb0b1570b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/26813418/041af940-4a4c-11e7-9ac8-7499f7871d13.png)

**Comment by zmathiasz** [comment]
I'm considering this the quick version.  I could possibly get the art behind the text, but that would take some considerable time and patience.  If anyone is up for trying have at it! 😃 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/26813418/041af940-4a4c-11e7-9ac8-7499f7871d13.png)
https://cloud.githubusercontent.com/assets/10950389/26813418/041af940-4a4c-11e7-9ac8-7499f7871d13.png
***
Source:
https://cloud.githubusercontent.com/assets/10950389/26813421/10e8814c-4a4c-11e7-87b7-4146c8d7c680.png

**Comment by dreamnet** [comment]
@zmathiasz I think it's fine as it is. 👍
