### ISSUE TITLE
Halide Camera

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#9181]
**App Name:** Halide Camera
**Bundle ID:** com.chromanoir.Zeit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=885697368">885697368</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/halide-camera/id885697368?uo=4">https://apps.apple.com/us/app/halide-camera/id885697368?uo=4</a>
**App Version:** 1.12.2
**Seller:** Chroma Noir LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/chroma-noir-llc/id885697371?uo=4">© Chroma Noir LLC</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/18/e9/c0/18e9c087-bc51-99b2-2f16-af7b072b126c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60640004-4c254400-9e25-11e9-854a-0aca34d6222f.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/10950389/26888721-e778e6e2-4b79-11e7-845e-dcf08c480927.png)
https://user-images.githubusercontent.com/10950389/26888721-e778e6e2-4b79-11e7-845e-dcf08c480927.png
***
Source:
https://user-images.githubusercontent.com/10950389/26888734-f23710a4-4b79-11e7-89da-34b76b72f3be.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60640004-4c254400-9e25-11e9-854a-0aca34d6222f.png)
https://user-images.githubusercontent.com/2068130/60640004-4c254400-9e25-11e9-854a-0aca34d6222f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60640017-5f381400-9e25-11e9-921e-324e4e4d6bd5.png
