### ISSUE TITLE
Accompany

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#9183]
**App Name:** Accompany
**Bundle ID:** com.accompani.Accompany
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1094470218">1094470218</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/accompany/id1094470218?mt=8&uo=4">https://itunes.apple.com/us/app/accompany/id1094470218?mt=8&uo=4</a>
**App Version:** 0.0.499
**Seller:** Accompani Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/accompany/id1094470217?uo=4">© Accompany</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple117/v4/65/8f/c2/658fc227-776a-71d3-a6d9-bd574af56b04/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/26927447-8650a352-4c17-11e7-92ee-f146904b5609.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/10950389/26889457-411d7fd0-4b7c-11e7-9d5f-871ef976385f.png)
https://user-images.githubusercontent.com/10950389/26889457-411d7fd0-4b7c-11e7-9d5f-871ef976385f.png
***
Source:
https://user-images.githubusercontent.com/10950389/26889468-4a3dc764-4b7c-11e7-8985-29cfbd6306c4.png

**Comment by ivanov007** [comment]
maybe something like this:
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/26927335-11d5a64e-4c17-11e7-8492-edfcd738320b.png)
https://user-images.githubusercontent.com/3090247/26927335-11d5a64e-4c17-11e7-8492-edfcd738320b.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/26927337-1235a1de-4c17-11e7-9126-aef98c0b946b.png)

**Comment by dreamnet** [comment]
@zmathiasz Good icon 👍, but it looks like the fox (or dog?) has a big open mouth... - so I take the one from @ivanov007.
