### ISSUE TITLE
WeMo

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9186]
**App Name:** WeMo
**Bundle ID:** com.belkin.plugin
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=511376996">511376996</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wemo/id511376996?mt=8&uo=4">https://itunes.apple.com/us/app/wemo/id511376996?mt=8&uo=4</a>
**App Version:** 1.18
**Seller:** Belkin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/belkin-international-inc/id329875380?uo=4">© Belkin International, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/d7/9d/7f/d79d7f15-8e3d-3dbf-317f-5de7f3f5df47/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27034493-8c7ae128-4f43-11e7-98ce-e5432c3960b4.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27034493-8c7ae128-4f43-11e7-98ce-e5432c3960b4.png)
https://user-images.githubusercontent.com/3090247/27034493-8c7ae128-4f43-11e7-98ce-e5432c3960b4.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27034494-8c7fb982-4f43-11e7-8258-cac665b35690.png
