### ISSUE TITLE
SPOX

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9187]
**App Name:** SPOX
**Bundle ID:** com.spox.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=420639764">420639764</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/spox/id420639764?mt=8&uo=4">https://itunes.apple.com/us/app/spox/id420639764?mt=8&uo=4</a>
**App Version:** 2.0.7
**Seller:** SPOX Media GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/spox-media-gmbh/id420639767?uo=4">© SPOX Media GmbH</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/5e/16/dc/5e16dc9b-401a-175f-e440-6574f02ac5e4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27034644-112954b8-4f44-11e7-8091-8650666a3655.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27034644-112954b8-4f44-11e7-8091-8650666a3655.png)
https://user-images.githubusercontent.com/3090247/27034644-112954b8-4f44-11e7-8091-8650666a3655.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27034645-112d6378-4f44-11e7-929d-cffc1e980837.png

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27034644-112954b8-4f44-11e7-8091-8650666a3655.png)
https://user-images.githubusercontent.com/3090247/27034644-112954b8-4f44-11e7-8091-8650666a3655.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27034645-112d6378-4f44-11e7-929d-cffc1e980837.png
