### ISSUE TITLE
Stocks Market - Realtime stock quotes and news

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9189]
**App Name:** Stocks Market - Realtime stock quotes and news
**Bundle ID:** com.stocks666.stocks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1198414824">1198414824</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stocks-market-realtime-stock-quotes-and-news/id1198414824?mt=8&uo=4">https://itunes.apple.com/us/app/stocks-market-realtime-stock-quotes-and-news/id1198414824?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Ustock Broker Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ustock-limited/id1198414823?uo=4">© Ustock Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple127/v4/b1/2f/eb/b12febe5-a5d3-9a26-9a8e-c5410d3c02c7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27088936-59e39e5a-5059-11e7-9103-cd63be193807.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27088936-59e39e5a-5059-11e7-9103-cd63be193807.png)
https://user-images.githubusercontent.com/20930745/27088936-59e39e5a-5059-11e7-9103-cd63be193807.png

Source:
https://user-images.githubusercontent.com/20930745/27088983-6fadb950-5059-11e7-99ed-7654292ebbe8.png
