### ISSUE TITLE
Chiltern Railways

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#919]
**App Name:** Chiltern Railways
**Bundle ID:** uk.co.chilternrailways.railtickets
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424250547">424250547</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/chiltern-railways/id424250547?mt=8&uo=4">https://itunes.apple.com/gb/app/chiltern-railways/id424250547?mt=8&uo=4</a>
**App Version:** 1.94.02
**Seller:** The Chiltern Railways Company Limited
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/chiltern-railways/id424250550?uo=4>© Chiltern Railways</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple18/v4/80/ea/1c/80ea1ca0-37d5-5188-c58a-02eee99358d1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410636/73119fd8-92f1-11e6-9299-8d602e7007f5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410636/73119fd8-92f1-11e6-9299-8d602e7007f5.png)
https://cloud.githubusercontent.com/assets/20930745/19410636/73119fd8-92f1-11e6-9299-8d602e7007f5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19410642/825a09f8-92f1-11e6-8331-5b3153b18969.png
