### ISSUE TITLE
RainMachine

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9190]
**App Name:** RainMachine
**Bundle ID:** com.greenelectronics.sprinkler
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=647589286">647589286</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rainmachine/id647589286?mt=8&uo=4">https://itunes.apple.com/us/app/rainmachine/id647589286?mt=8&uo=4</a>
**App Version:** 4.3.108
**Seller:** Green Electronics LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rainmachine/id647589469?uo=4">© RainMachine</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/af/ce/3b/afce3b78-1aeb-621f-0927-13258d4a94e4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27090052-68018a76-505c-11e7-8018-5d986175f753.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27090052-68018a76-505c-11e7-8018-5d986175f753.png)
https://user-images.githubusercontent.com/20930745/27090052-68018a76-505c-11e7-8018-5d986175f753.png

Source:
https://user-images.githubusercontent.com/20930745/27090077-7d3560d4-505c-11e7-8c0d-76d4b546e756.png
