### ISSUE TITLE
Yellfy Sports - Your Teams Live Scores, News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9191]
**App Name:** Yellfy Sports - Your Teams Live Scores, News
**Bundle ID:** com.yellfy.yingit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=971987537">971987537</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yellfy-sports-your-teams-live-scores-news/id971987537?mt=8&uo=4">https://itunes.apple.com/us/app/yellfy-sports-your-teams-live-scores-news/id971987537?mt=8&uo=4</a>
**App Version:** 1.4.5
**Seller:** Yingit Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yingit-inc/id971987536?uo=4">© Yingit Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple127/v4/8f/cc/d3/8fccd363-1b68-b302-3c7b-28b05ac93761/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27089359-6ea7b5dc-505a-11e7-85c7-b1de4743bb92.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27089309-4e299c6c-505a-11e7-9747-836f1ff4fff6.png)
https://user-images.githubusercontent.com/20930745/27089309-4e299c6c-505a-11e7-9747-836f1ff4fff6.png

Sourc:e:
https://user-images.githubusercontent.com/20930745/27089340-63a65472-505a-11e7-987f-2487c473d276.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27089359-6ea7b5dc-505a-11e7-85c7-b1de4743bb92.png)
https://user-images.githubusercontent.com/20930745/27089359-6ea7b5dc-505a-11e7-85c7-b1de4743bb92.png

Source:
https://user-images.githubusercontent.com/20930745/27089395-84616558-505a-11e7-880e-b9d09650de52.png
