### ISSUE TITLE
Sams Club México

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9192]
**App Name:** Sams Club México
**Bundle ID:** com.Walmart.CuponeraSams
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=841032565">841032565</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sams-club-m%C3%A9xico/id841032565?mt=8&uo=4">https://itunes.apple.com/us/app/sams-club-m%C3%A9xico/id841032565?mt=8&uo=4</a>
**App Version:** 4.3.7
**Seller:** Wal-Mart de Mexico S.A.B de C.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wal-mart-mexico-inc/id488741711?uo=4">© Wal-Mart Mexico, Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple117/v4/90/de/32/90de322c-9707-9ac6-443d-6edd8b2f66dc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27034925-1c9e8344-4f45-11e7-8f52-0cdccb4b6e0e.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27034925-1c9e8344-4f45-11e7-8f52-0cdccb4b6e0e.png)
https://user-images.githubusercontent.com/3090247/27034925-1c9e8344-4f45-11e7-8f52-0cdccb4b6e0e.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27034926-1ccc6d86-4f45-11e7-8954-612ad8c59568.png

**Comment by dreamnet** [comment]
@ivanov007 Same as #9188?

**Comment by ivanov007** [comment]
@dreamnet same icon yes
