### ISSUE TITLE
Monument Valley 2

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9193]
**App Name:** Monument Valley 2
**Bundle ID:** com.ustwo.monumentvalley2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1187265767">1187265767</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/monument-valley-2/id1187265767?mt=8&uo=4">https://itunes.apple.com/us/app/monument-valley-2/id1187265767?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** ustwo Games Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ustwo-games-ltd/id297468910?uo=4">© ustwo Games Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple117/v4/4d/24/8f/4d248f2a-1077-3e6c-2be8-136c4a280206/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27507087-66595978-58c8-11e7-8f8c-a82e3984bcc2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27507087-66595978-58c8-11e7-8f8c-a82e3984bcc2.png)
https://user-images.githubusercontent.com/2068130/27507087-66595978-58c8-11e7-8f8c-a82e3984bcc2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27507093-750f5e18-58c8-11e7-96e7-5efc6145a276.png
