### ISSUE TITLE
PerformanceTest Mobile

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9194]
**App Name:** PerformanceTest Mobile
**Bundle ID:** PerformanceTestMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=494438360">494438360</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/performancetest-mobile/id494438360?mt=8&uo=4">https://itunes.apple.com/us/app/performancetest-mobile/id494438360?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** PassMark Software Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/passmark-software-inc/id494438363?uo=4">© PassMark Software Inc</a>
**Supported Devices:** iPhoneFirstGen-iPhone, iPodTouchFirstGen-iPod-touch, iPodTouchSecondGen-iPod-touch-with-mic, iPhone3G-iPhone-3G, iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/2e/9e/58/2e9e5804-2677-c1e8-597f-35f5495ece6b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27769627-53e92144-5f2e-11e7-863f-f8cf6cfcf6e2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27769627-53e92144-5f2e-11e7-863f-f8cf6cfcf6e2.png)
https://user-images.githubusercontent.com/20930745/27769627-53e92144-5f2e-11e7-863f-f8cf6cfcf6e2.png

Source:
https://user-images.githubusercontent.com/20930745/27769629-66a30502-5f2e-11e7-911b-e465c5090f46.png
