### ISSUE TITLE
Shoot The Birds

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9195]
**App Name:** Shoot The Birds
**Bundle ID:** pl.idreams.Birds
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=451945358">451945358</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shoot-the-birds/id451945358?mt=8&uo=4">https://itunes.apple.com/us/app/shoot-the-birds/id451945358?mt=8&uo=4</a>
**App Version:** 1.03
**Seller:** Infinite Dreams
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/infinite-dreams-inc/id306712040?uo=4">© Infinite Dreams Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple/v4/16/d9/ac/16d9ace5-a972-c77d-a511-7467ad7846da/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29246929-18f8b6ea-8007-11e7-9789-41e34743e470.png)

**Comment by dreamnet** [comment]
Can't do the original, so here is the game logo:
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29246929-18f8b6ea-8007-11e7-9789-41e34743e470.png)
https://user-images.githubusercontent.com/2068130/29246929-18f8b6ea-8007-11e7-9789-41e34743e470.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29246930-293bca6a-8007-11e7-8bfa-3f5c3588ad53.png
❓

**Comment by Grafovich** [comment]
It's ok 👌Looks nice. Thx!
