### ISSUE TITLE
Балда: Игра В Слова

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9196]
**App Name:** Балда: Игра В Слова
**Bundle ID:** com.Balda2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=768330758">768330758</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%D0%B1%D0%B0%D0%BB%D0%B4%D0%B0-%D0%B8%D0%B3%D1%80%D0%B0-%D0%B2-%D1%81%D0%BB%D0%BE%D0%B2%D0%B0/id768330758?mt=8&uo=4">https://itunes.apple.com/us/app/%D0%B1%D0%B0%D0%BB%D0%B4%D0%B0-%D0%B8%D0%B3%D1%80%D0%B0-%D0%B2-%D1%81%D0%BB%D0%BE%D0%B2%D0%B0/id768330758?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Andrei Mankevich
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/andrei-mankevich/id768330761?uo=4">© Andrei Mankevich</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/df/1c/91/df1c9172-59ef-8f8a-efbf-40547fbac2f0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27769675-eba4d590-5f2f-11e7-9f41-480bf6750c19.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27769675-eba4d590-5f2f-11e7-9f41-480bf6750c19.png)
https://user-images.githubusercontent.com/20930745/27769675-eba4d590-5f2f-11e7-9f41-480bf6750c19.png

Source:
https://user-images.githubusercontent.com/20930745/27769679-fca3cd24-5f2f-11e7-8362-f327c5b875b9.png
