### ISSUE TITLE
BelkaCar

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9197]
**App Name:** BelkaCar
**Bundle ID:** ru.belkacar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1113709902">1113709902</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/belkacar/id1113709902?mt=8&uo=4">https://itunes.apple.com/us/app/belkacar/id1113709902?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** KARSHERING, AO
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/carsharing-jsc/id1113709901?uo=4">© Carsharing JSC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple127/v4/1a/43/8b/1a438bec-1dfb-bbe4-b1ec-9ead24819ad1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27135494-34f43ad4-50de-11e7-8e03-8fa80c6993c8.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27135494-34f43ad4-50de-11e7-8e03-8fa80c6993c8.png)
https://user-images.githubusercontent.com/3090247/27135494-34f43ad4-50de-11e7-8e03-8fa80c6993c8.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27135493-34f095aa-50de-11e7-9319-aa6b4dbb1938.png
