### ISSUE TITLE
Learn to Code with Java - Sololearn

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9198]
**App Name:** Learn to Code with Java
**Bundle ID:** com.sololearn.java
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=961615044">961615044</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/learn-to-code-with-java/id961615044?mt=8&uo=4">https://itunes.apple.com/us/app/learn-to-code-with-java/id961615044?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** SoloLearn Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sololearn-inc/id933957049?uo=4">© Sololearn Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple127/v4/63/40/0d/63400d73-eb31-c9c1-16a1-9017cc81ca5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27135318-d7935140-50dd-11e7-8a17-e828aa76277c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27135318-d7935140-50dd-11e7-8a17-e828aa76277c.png)
https://user-images.githubusercontent.com/3090247/27135318-d7935140-50dd-11e7-8a17-e828aa76277c.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27135316-d74016e2-50dd-11e7-98da-cc2ba3d29c85.png
