### ISSUE TITLE
Learn to Code with C++ - Sololearn

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9199]
**App Name:** Learn to Code with C++
**Bundle ID:** com.sololearn.cpp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=960646346">960646346</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/learn-to-code-with-c/id960646346?mt=8&uo=4">https://itunes.apple.com/us/app/learn-to-code-with-c/id960646346?mt=8&uo=4</a>
**App Version:** 4.0
**Seller:** SoloLearn Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sololearn-inc/id933957049?uo=4">© Sololearn Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple117/v4/69/02/55/690255c5-c641-4e82-d85d-8a9fa3cc3161/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27135073-38c688fc-50dd-11e7-987b-156c8cd35fa8.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27135073-38c688fc-50dd-11e7-987b-156c8cd35fa8.png)
https://user-images.githubusercontent.com/3090247/27135073-38c688fc-50dd-11e7-987b-156c8cd35fa8.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27135074-3943099a-50dd-11e7-9738-3d4d21ce1989.png
