### ISSUE TITLE
Learn to Code with SQL - Sololearn

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9200]
**App Name:** Learn to Code with SQL
**Bundle ID:** com.sololearn.sql
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953775305">953775305</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/learn-to-code-with-sql/id953775305?mt=8&uo=4">https://itunes.apple.com/us/app/learn-to-code-with-sql/id953775305?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** SoloLearn Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sololearn-inc/id933957049?uo=4">© Sololearn Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/92/9f/5f/929f5ff1-8f59-6552-a2cb-ecf4dc1810f2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27134884-b721c7b2-50dc-11e7-80c8-c1d8a193cd6c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27134884-b721c7b2-50dc-11e7-80c8-c1d8a193cd6c.png)
https://user-images.githubusercontent.com/3090247/27134884-b721c7b2-50dc-11e7-80c8-c1d8a193cd6c.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27134882-b6442952-50dc-11e7-915b-93aabd349c40.png
