### ISSUE TITLE
Learn Programming with Swift

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9201]
**App Name:** Learn Programming with Swift
**Bundle ID:** com.sololearn.swift
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1029910748">1029910748</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/learn-programming-with-swift/id1029910748?mt=8&uo=4">https://itunes.apple.com/us/app/learn-programming-with-swift/id1029910748?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** SoloLearn Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sololearn-inc/id933957049?uo=4">© Sololearn Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/6e/7a/5c/6e7a5c82-bc9c-511b-97c0-71fec0edf790/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27134727-0916fe44-50dc-11e7-914c-10aa1f8e7bb6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27134727-0916fe44-50dc-11e7-914c-10aa1f8e7bb6.png)
https://user-images.githubusercontent.com/3090247/27134727-0916fe44-50dc-11e7-914c-10aa1f8e7bb6.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27134726-091634aa-50dc-11e7-9cac-19284d5ed445.png
