### ISSUE TITLE
Learn to Code with PHP - Sololearn

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9202]
**App Name:** Learn to Code with PHP
**Bundle ID:** com.sololearn.php
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953933919">953933919</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/learn-to-code-with-php/id953933919?mt=8&uo=4">https://itunes.apple.com/us/app/learn-to-code-with-php/id953933919?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** SoloLearn Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sololearn-inc/id933957049?uo=4">© Sololearn Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple117/v4/f2/29/8c/f2298c7b-112d-1390-2781-740f62facfba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27134055-fc35133e-50d9-11e7-8232-e933ac7c9dc9.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27134055-fc35133e-50d9-11e7-8232-e933ac7c9dc9.png)
https://user-images.githubusercontent.com/3090247/27134055-fc35133e-50d9-11e7-8232-e933ac7c9dc9.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27134054-fb238c82-50d9-11e7-887a-04fc7feb984d.png
