### ISSUE TITLE
 Learn to Code with C# - Sololearn

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9203]
**App Name:** Learn to Code with C#
**Bundle ID:** com.sololearn.csharp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1097601341">1097601341</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/learn-to-code-with-c/id1097601341?mt=8&uo=4">https://itunes.apple.com/us/app/learn-to-code-with-c/id1097601341?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** SoloLearn Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sololearn-inc/id933957049?uo=4">© Sololearn Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple127/v4/fa/f0/60/faf06059-a241-169e-5d62-5ac7aef5ec80/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27134264-aa61dd34-50da-11e7-9b76-86d56cf56a07.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27134264-aa61dd34-50da-11e7-9b76-86d56cf56a07.png)
https://user-images.githubusercontent.com/3090247/27134264-aa61dd34-50da-11e7-9b76-86d56cf56a07.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27134265-aa67ce9c-50da-11e7-84f4-71a9e3b3a87c.png
