### ISSUE TITLE
Learn to Code with Ruby

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9204]
**App Name:** Learn to Code with Ruby
**Bundle ID:** com.sololearn.ruby
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1171339023">1171339023</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/learn-to-code-with-ruby/id1171339023?mt=8&uo=4">https://itunes.apple.com/us/app/learn-to-code-with-ruby/id1171339023?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** SoloLearn Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sololearn-inc/id933957049?uo=4">© Sololearn Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple117/v4/5c/c9/b7/5cc9b733-b886-a8cc-3801-45eff8b38211/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27135745-fc1b9936-50de-11e7-9499-aa7d02d2489d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27135745-fc1b9936-50de-11e7-9499-aa7d02d2489d.png)
https://user-images.githubusercontent.com/3090247/27135745-fc1b9936-50de-11e7-9499-aa7d02d2489d.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27135746-fc2fd068-50de-11e7-85a4-ab57f362ebdc.png
