### ISSUE TITLE
Sant Kabir Ke Dohe

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9206]
**App Name:** Sant Kabir Ke Dohe
**Bundle ID:** Rikunj.BookSantKabirKeDohe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1138242337">1138242337</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sant-kabir-ke-dohe/id1138242337?mt=8&uo=4">https://itunes.apple.com/us/app/sant-kabir-ke-dohe/id1138242337?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Patel Rikunj
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/patel-rikunj/id1118655704?uo=4">© Patel Rikunj</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple30/v4/e0/21/1f/e0211f63-0eea-cad4-ed39-a2f3b6ac1406/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32142345-e1f020d6-bc95-11e7-8fc8-fd384ed173a1.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32142345-e1f020d6-bc95-11e7-8fc8-fd384ed173a1.png)
https://user-images.githubusercontent.com/20930745/32142345-e1f020d6-bc95-11e7-8fc8-fd384ed173a1.png

Source:
https://user-images.githubusercontent.com/20930745/32142349-f7c15da8-bc95-11e7-92e4-35dfb3fe20c1.png

**Comment by dreamnet** [comment]
@mohitnandwani ???
