### ISSUE TITLE
Hyperburner

### ISSUE THREAD

**Issue by mohitnandwani** [glasklart/hd#9207]
**App Name:** Hyperburner
**Bundle ID:** com.badpotion.hyperburner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=982763237">982763237</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hyperburner/id982763237?mt=8&uo=4">https://itunes.apple.com/us/app/hyperburner/id982763237?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Patrick Cook
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/patrick-cook/id687051817?uo=4">© Patrick Cook</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple60/v4/63/53/00/635300ea-ac57-9f2a-198d-731f17e3f625/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29322297-07977fe4-81ab-11e7-9598-ec632223a2db.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29322297-07977fe4-81ab-11e7-9598-ec632223a2db.png)
https://user-images.githubusercontent.com/3090247/29322297-07977fe4-81ab-11e7-9598-ec632223a2db.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29322298-07a0b2f8-81ab-11e7-8466-0ae25c9a260f.png
