### ISSUE TITLE
dote

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#9214]
**App Name:** dote
**Bundle ID:** com.dote.Dote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=908818458">908818458</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dote/id908818458?uo=4">https://apps.apple.com/us/app/dote/id908818458?uo=4</a>
**App Version:** 5.68
**Seller:** Dote Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dote-inc/id908818461?uo=4">© Dote Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/49/9b/09/499b09d1-dfac-fe1d-b77f-30b9c6c4a3c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60383145-97c69f00-9a6d-11e9-8e40-9ff9123652d6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27259178-fa40e2e8-540c-11e7-8c23-d7bd00c4fc1a.png)
https://user-images.githubusercontent.com/2068130/27259178-fa40e2e8-540c-11e7-8c23-d7bd00c4fc1a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27259188-0ca990d8-540d-11e7-9634-06255b82f4f1.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60383145-97c69f00-9a6d-11e9-8e40-9ff9123652d6.png)
https://user-images.githubusercontent.com/20930745/60383145-97c69f00-9a6d-11e9-8e40-9ff9123652d6.png

Source:
https://user-images.githubusercontent.com/20930745/60383146-9a28f900-9a6d-11e9-8ed8-fe5fd11fd249.png
