### ISSUE TITLE
Metropolitan

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9217]
**App Name:** Metropolitan
**Bundle ID:** com.Metropolitan.Metropolitan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=563504939">563504939</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/metropolitan/id563504939?mt=8&uo=4">https://itunes.apple.com/us/app/metropolitan/id563504939?mt=8&uo=4</a>
**App Version:** 1.4.3
**Seller:** METROPOLITAN SPAIN, S.L.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/metropolitan-spain-s-l/id563504942?uo=4">© METROPOLITAN SPAIN, S.L.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple127/v4/a6/7f/ed/a67fedbf-f1cd-d5fc-28a5-bd700781a174/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27490283-fabb2d02-583d-11e7-938b-f5c1b3ab9fc4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27490283-fabb2d02-583d-11e7-938b-f5c1b3ab9fc4.png)
https://user-images.githubusercontent.com/20930745/27490283-fabb2d02-583d-11e7-938b-f5c1b3ab9fc4.png

Source:
https://user-images.githubusercontent.com/20930745/27490299-0ab74e70-583e-11e7-8ea7-8168124e6616.png
