### ISSUE TITLE
Metropolitan Training

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9218]
**App Name:** Metropolitan Training
**Bundle ID:** com.trainingym.metropolitantraining
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1236459423">1236459423</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/metropolitan-training/id1236459423?mt=8&uo=4">https://itunes.apple.com/us/app/metropolitan-training/id1236459423?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** iNTELINOVA SOFTWARE SOCIEDAD LIMITADA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/intelinova-software-sociedad-limitada/id598249675?uo=4">© iNTELINOVA SOFTWARE SOCIEDAD LIMITADA</a>
**Supported Devices:** iPhone4S-iPhone4S, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple127/v4/8e/0c/fa/8e0cfa57-7cd2-c1b0-c88e-287e5987be9f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27490143-75a31404-583d-11e7-96d3-f2ed2ec26023.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27490143-75a31404-583d-11e7-96d3-f2ed2ec26023.png)
https://user-images.githubusercontent.com/20930745/27490143-75a31404-583d-11e7-96d3-f2ed2ec26023.png

Source:
https://user-images.githubusercontent.com/20930745/27490168-8917ed70-583d-11e7-8377-c1ae9084abb1.png
