### ISSUE TITLE
Apteka.RU

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9219]
**App Name:** Apteka.RU
**Bundle ID:** com.picom.apteka
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916258897">916258897</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ru/app/apteka-ru/id916258897?mt=8&uo=4">https://itunes.apple.com/ru/app/apteka-ru/id916258897?mt=8&uo=4</a>
**App Version:** 2.12
**Seller:** Scientific production company Katren CJSC
**Developer:** <a target="_blank" href="https://itunes.apple.com/ru/developer/%D0%B0%D0%BE-%D0%BD%D0%BF%D0%BA-%D0%BA%D0%B0%D1%82%D1%80%D0%B5%D0%BD/id929032004?uo=4">© АО НПК Катрен</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple127/v4/21/a6/7e/21a67e15-07ec-0334-a1ab-7357374c8763/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27489921-a0f230c8-583c-11e7-8e83-f7d9b850f710.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27489921-a0f230c8-583c-11e7-8e83-f7d9b850f710.png)
https://user-images.githubusercontent.com/20930745/27489921-a0f230c8-583c-11e7-8e83-f7d9b850f710.png

Source:
https://user-images.githubusercontent.com/20930745/27489945-b3a09ae8-583c-11e7-9193-8100b8a09239.png
