### ISSUE TITLE
AppHop - Handy App for Developers, Bloggers and Marketers

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9220]
**App Name:** AppHop - Handy App for Developers, Bloggers and Marketers
**Bundle ID:** com.waplestuff.apphop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=887052210">887052210</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/apphop-handy-app-for-developers-bloggers-and-marketers/id887052210?mt=8&uo=4">https://itunes.apple.com/us/app/apphop-handy-app-for-developers-bloggers-and-marketers/id887052210?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Raja V
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/waplestuff/id562575890?uo=4">© WapleStuff</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple5/v4/85/73/0d/85730de9-4b35-342a-145c-3616e78cabfa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27511103-23a67b8c-591e-11e7-9237-6789c099690a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27511103-23a67b8c-591e-11e7-9237-6789c099690a.png)
https://user-images.githubusercontent.com/2068130/27511103-23a67b8c-591e-11e7-9237-6789c099690a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27511111-33430efc-591e-11e7-8f0c-7161b2546142.png
