### ISSUE TITLE
Altered Beast

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9221]
**App Name:** Altered Beast
**Bundle ID:** com.sega.alteredbeast
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407812054">407812054</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/altered-beast/id407812054?mt=8&uo=4">https://itunes.apple.com/us/app/altered-beast/id407812054?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** Sega America
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sega/id281966698?mt=8&uo=4">© SEGA</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple117/v4/ae/db/70/aedb7013-b68e-25b8-2738-2524d4b8c8aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27772044-512868b6-5f5b-11e7-92b5-3f41c498b6fe.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27772044-512868b6-5f5b-11e7-92b5-3f41c498b6fe.png)
https://user-images.githubusercontent.com/2068130/27772044-512868b6-5f5b-11e7-92b5-3f41c498b6fe.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27772049-73dbb37c-5f5b-11e7-8fda-728bd443c5a7.png
