### ISSUE TITLE
MyMTN Cyprus

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9222]
**App Name:** MyMTN Cyprus
**Bundle ID:** com.mtncyprus.mymtn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1054879177">1054879177</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mymtn-cyprus/id1054879177?mt=8&uo=4">https://itunes.apple.com/us/app/mymtn-cyprus/id1054879177?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** MTN Cyprus Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mtn-cyprus-limited/id894001411?uo=4">© MTN Cyprus Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple127/v4/10/22/d8/1022d835-afa0-7f04-f92e-30aa8094f8a0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27699036-90672d22-5cbe-11e7-8cd9-30c6a0fa547e.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27699036-90672d22-5cbe-11e7-8cd9-30c6a0fa547e.png)
https://user-images.githubusercontent.com/3090247/27699036-90672d22-5cbe-11e7-8cd9-30c6a0fa547e.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27699030-8e7624e6-5cbe-11e7-9b2d-ebb2d2121fb2.png
