### ISSUE TITLE
TunnelBear Free VPN - Unlimited Secure VPN Proxy

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9223]
**App Name:** TunnelBear Free VPN - Unlimited Secure VPN Proxy
**Bundle ID:** com.tunnelbear.ios.TunnelBear
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=564842283">564842283</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tunnelbear-free-vpn-unlimited-secure-vpn-proxy/id564842283?mt=8&uo=4">https://itunes.apple.com/us/app/tunnelbear-free-vpn-unlimited-secure-vpn-proxy/id564842283?mt=8&uo=4</a>
**App Version:** 2.6.3
**Seller:** TunnelBear, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tunnelbear-inc/id555344986?uo=4">© TunnelBear, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/1f/73/02/1f7302d2-9053-5d58-f150-eff83d0ee653/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27769455-a441a76a-5f29-11e7-962e-001c88cd67e8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27769455-a441a76a-5f29-11e7-962e-001c88cd67e8.png)
https://user-images.githubusercontent.com/20930745/27769455-a441a76a-5f29-11e7-962e-001c88cd67e8.png

Source:
https://user-images.githubusercontent.com/20930745/27769461-b44f560c-5f29-11e7-944b-abb23862501a.png
