### ISSUE TITLE
WinZip Pro - The Leading Zip, Unzip & RAR Tool

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9224]
**App Name:** WinZip Pro - The Leading Zip, Unzip & RAR Tool
**Bundle ID:** com.winzip.wzstd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=669835030">669835030</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/winzip-pro-the-leading-zip-unzip-rar-tool/id669835030?mt=8&uo=4">https://itunes.apple.com/us/app/winzip-pro-the-leading-zip-unzip-rar-tool/id669835030?mt=8&uo=4</a>
**App Version:** 4.7.3
**Seller:** WinZip Computing LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/winzip-computing-llc/id389735097?uo=4">© WinZip Computing LLC</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple117/v4/e6/c6/88/e6c6883c-f446-e8f3-4cc9-00e7a205fc4e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27555807-7c45f966-5ab3-11e7-9752-56d14d9252e1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27555807-7c45f966-5ab3-11e7-9752-56d14d9252e1.png)
https://user-images.githubusercontent.com/20930745/27555807-7c45f966-5ab3-11e7-9752-56d14d9252e1.png

Source:
https://user-images.githubusercontent.com/20930745/27555839-9a1c83f6-5ab3-11e7-9351-5e61b1875510.png
