### ISSUE TITLE
BuzzFeed Video

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9225]
**App Name:** BuzzFeed Video
**Bundle ID:** com.buzzfeed.video
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1060266198">1060266198</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/buzzfeed-video/id1060266198?mt=8&uo=4">https://itunes.apple.com/us/app/buzzfeed-video/id1060266198?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** BuzzFeed
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/buzzfeed/id352970000?uo=4">© BuzzFeed</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/82/b0/d4/82b0d4fb-74e0-2119-7af6-bc3467f687fd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27555592-91a3c348-5ab2-11e7-8a82-dc082dcb2dc4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27555592-91a3c348-5ab2-11e7-8a82-dc082dcb2dc4.png)
https://user-images.githubusercontent.com/20930745/27555592-91a3c348-5ab2-11e7-8a82-dc082dcb2dc4.png

Source:
https://user-images.githubusercontent.com/20930745/27555615-a46f5ec4-5ab2-11e7-8117-ba8bc290ebf8.png
