### ISSUE TITLE
Hydra - Amazing Photography

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9226]
**App Name:** Hydra - Amazing Photography
**Bundle ID:** com.creaceed.ihydra
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=947824428">947824428</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hydra-amazing-photography/id947824428?mt=8&uo=4">https://itunes.apple.com/us/app/hydra-amazing-photography/id947824428?mt=8&uo=4</a>
**App Version:** 1.3.4
**Seller:** Creaceed SPRL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/creaceed-sprl/id291683889?uo=4">© Creaceed SPRL</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/76/95/f7/7695f7ff-d60d-6046-570b-669c340465e0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27556865-bd599576-5ab7-11e7-8c90-327fe24cc05d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27556865-bd599576-5ab7-11e7-8c90-327fe24cc05d.png)
https://user-images.githubusercontent.com/20930745/27556865-bd599576-5ab7-11e7-8c90-327fe24cc05d.png

Source:
https://user-images.githubusercontent.com/20930745/27556913-e6b3973c-5ab7-11e7-8c24-6a2fa5c26803.png
