### ISSUE TITLE
Tadaa SLR

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9227]
**App Name:** Tadaa SLR
**Bundle ID:** net.tadaa.tadaaslr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=724662909">724662909</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tadaa-slr/id724662909?mt=8&uo=4">https://itunes.apple.com/us/app/tadaa-slr/id724662909?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** menschmaschine Publishing GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/menschmaschine-publishing-gmbh/id410005688?uo=4">© menschmaschine Publishing GmbH</a>
**Supported Devices:** iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple7/v4/e5/38/0d/e5380d7a-946d-3ffe-2a0b-ef3e33b5c3f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27555456-10f23054-5ab2-11e7-9a7d-893bfd2ce305.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27555456-10f23054-5ab2-11e7-9a7d-893bfd2ce305.png)
https://user-images.githubusercontent.com/20930745/27555456-10f23054-5ab2-11e7-9a7d-893bfd2ce305.png

Source:
https://user-images.githubusercontent.com/20930745/27555472-213be202-5ab2-11e7-8cae-05b996142315.png
