### ISSUE TITLE
Cinemagraph Pro

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9228]
**App Name:** Cinemagraph Pro
**Bundle ID:** com.flixel.cinemagraphpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=642139481">642139481</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cinemagraph-pro/id642139481?mt=8&uo=4">https://itunes.apple.com/us/app/cinemagraph-pro/id642139481?mt=8&uo=4</a>
**App Version:** 5.2.2
**Seller:** Flixel Photos Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/flixel-photos-inc/id496885366?uo=4">© Flixel Photos Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple127/v4/d5/7b/83/d57b83a9-7ba2-481f-d0a2-fe5082fab079/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27557619-88e9c3bc-5aba-11e7-996e-dfd16c294e4b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27557619-88e9c3bc-5aba-11e7-996e-dfd16c294e4b.png)
https://user-images.githubusercontent.com/20930745/27557619-88e9c3bc-5aba-11e7-996e-dfd16c294e4b.png

Source:
https://user-images.githubusercontent.com/20930745/27557670-ae634582-5aba-11e7-86ab-4eac70a449dc.png
