### ISSUE TITLE
LightX

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9229]
**App Name:** LightX
**Bundle ID:** com.andor.lightX
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1110639444">1110639444</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lightx/id1110639444?mt=8&uo=4">https://itunes.apple.com/us/app/lightx/id1110639444?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Andor Communications Private Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/andor-communications-private-limited/id1110639443?uo=4">© Andor Communications Private Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple127/v4/77/c4/84/77c48441-b3be-0853-18b4-568911cb00fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27771700-6a309c90-5f54-11e7-8ae1-f2b7fb4d7017.png)

**Comment by dreamnet** [comment]
Without the spark...
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27771700-6a309c90-5f54-11e7-8ae1-f2b7fb4d7017.png)
https://user-images.githubusercontent.com/2068130/27771700-6a309c90-5f54-11e7-8ae1-f2b7fb4d7017.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27771705-82f01238-5f54-11e7-8857-a7067f1e2fab.png
