### ISSUE TITLE
Live Traffic Info

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#923]
**App Name:** Live Traffic Info
**Bundle ID:** com.thisisaim.highwaysagency
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=354106594">354106594</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/live-traffic-info/id354106594?mt=8&uo=4">https://itunes.apple.com/us/app/live-traffic-info/id354106594?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Highways England Company Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/highways-england/id1087324684?uo=4">© Highways England</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/6d/10/3f/6d103f7e-7167-4977-e77a-035c6734bb2d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20219222/af1add40-a828-11e6-8f06-9b2321697754.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20219222/af1add40-a828-11e6-8f06-9b2321697754.png)
https://cloud.githubusercontent.com/assets/20930745/20219222/af1add40-a828-11e6-8f06-9b2321697754.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20219248/d5e17f1a-a828-11e6-90da-52600f3b7845.png
