### ISSUE TITLE
RollWorld - Tiny Planet Photos And More

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9230]
**App Name:** RollWorld - Tiny Planet Photos And More
**Bundle ID:** com.LiW.RollWorld
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=867960225">867960225</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rollworld-tiny-planet-photos-and-more/id867960225?mt=8&uo=4">https://itunes.apple.com/us/app/rollworld-tiny-planet-photos-and-more/id867960225?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Li Wang
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/li-wang/id847994919?uo=4">© Li Wang</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple49/v4/72/42/e7/7242e7d6-009e-fde3-1e6b-360fb5362f8b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27555180-413a9c48-5ab1-11e7-9dab-536720306458.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27555180-413a9c48-5ab1-11e7-9dab-536720306458.png)
https://user-images.githubusercontent.com/20930745/27555180-413a9c48-5ab1-11e7-9dab-536720306458.png

Source:
https://user-images.githubusercontent.com/20930745/27555209-57736562-5ab1-11e7-9229-40122a4df887.png
