### ISSUE TITLE
Boom: Best Equalizer & Magical Surround Sound

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9231]
**App Name:** Boom: Best Equalizer & Magical Surround Sound
**Bundle ID:** com.globaldelight.iBoom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1065511007">1065511007</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boom-best-equalizer-magical-surround-sound/id1065511007?mt=8&uo=4">https://itunes.apple.com/us/app/boom-best-equalizer-magical-surround-sound/id1065511007?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Global Delight Technologies Pvt. Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/global-delight-technologies-pvt-ltd/id307372311?uo=4">© Global Delight Technologies Pvt. Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/c8/39/4b/c8394bd7-175b-9164-c6fd-2b2b152d0e2d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27556241-12fe99b6-5ab5-11e7-8767-ca6c3bf529d2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27556241-12fe99b6-5ab5-11e7-8767-ca6c3bf529d2.png)
https://user-images.githubusercontent.com/20930745/27556241-12fe99b6-5ab5-11e7-8767-ca6c3bf529d2.png

Source:
https://user-images.githubusercontent.com/20930745/27556262-27082706-5ab5-11e7-8de4-8bbf5bdb3aeb.png
