### ISSUE TITLE
All Documents — documents and cards storage

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9233]
**App Name:** All Documents — documents and cards storage
**Bundle ID:** com.gmail-shookup.MyDocuments
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=836987275">836987275</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/all-documents-documents-and-cards-storage/id836987275?mt=8&uo=4">https://itunes.apple.com/us/app/all-documents-documents-and-cards-storage/id836987275?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Vladimir Shutyuk
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vladimir-shutyuk/id650858899?uo=4">© Vladimir Shutyuk</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple117/v4/d2/cb/99/d2cb9917-d4e6-bbbf-ed60-9709a784159e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27761956-e8ffa5b8-5e67-11e7-9598-0736fe94323c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27761956-e8ffa5b8-5e67-11e7-9598-0736fe94323c.png)
https://user-images.githubusercontent.com/20930745/27761956-e8ffa5b8-5e67-11e7-9598-0736fe94323c.png

Source:
https://user-images.githubusercontent.com/20930745/27761962-fbca5be8-5e67-11e7-885c-262cd02d2abc.png
