### ISSUE TITLE
Monster Job Search

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9234]
**App Name:** Monster Job Search
**Bundle ID:** com.jobrapp.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=870221491">870221491</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/monster-job-search/id870221491?mt=8&uo=4">https://itunes.apple.com/us/app/monster-job-search/id870221491?mt=8&uo=4</a>
**App Version:** 5.2.4
**Seller:** Jobr, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jobr-inc/id870221494?uo=4">© Jobr, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple127/v4/b7/45/18/b74518a1-2a28-8b0b-18c2-457395fda429/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27767722-5091694e-5f00-11e7-960a-cf30a2f7a8f6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27742581-d6d73840-5d7e-11e7-840a-906d0746cb6b.png)
https://user-images.githubusercontent.com/3090247/27742581-d6d73840-5d7e-11e7-840a-906d0746cb6b.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27742580-d6372eea-5d7e-11e7-901d-8ed0fa4563ba.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27767722-5091694e-5f00-11e7-960a-cf30a2f7a8f6.png)
https://user-images.githubusercontent.com/2068130/27767722-5091694e-5f00-11e7-960a-cf30a2f7a8f6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27767726-602c8b18-5f00-11e7-98f1-50667d115257.png
