### ISSUE TITLE
Laserlike – Search and follow your interests

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9235]
**App Name:** Laserlike – Search and follow your interests
**Bundle ID:** com.laserlike.laserlike
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1097783265">1097783265</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/laserlike-search-and-follow-your-interests/id1097783265?mt=8&uo=4">https://itunes.apple.com/us/app/laserlike-search-and-follow-your-interests/id1097783265?mt=8&uo=4</a>
**App Version:** 1.0.23
**Seller:** Laserlike Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/laserlike-inc/id1097783264?uo=4">© Laserlike Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple127/v4/16/3b/ed/163bed6a-f2b2-f8d3-db24-894f48a0c1a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27762209-e3143c26-5e6d-11e7-9416-6d6f65c87158.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27762209-e3143c26-5e6d-11e7-9416-6d6f65c87158.png)
https://user-images.githubusercontent.com/20930745/27762209-e3143c26-5e6d-11e7-9416-6d6f65c87158.png

Source:
https://user-images.githubusercontent.com/20930745/27762213-f70b28b6-5e6d-11e7-888f-cfdb49eb409b.png
