### ISSUE TITLE
Today Weather - Forecast, Radar & Severe Alert

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9236]
**App Name:** Today Weather - Forecast, Radar & Severe Alert
**Bundle ID:** mobi.lockdown.todayweather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1214962662">1214962662</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/today-weather-forecast-radar-severe-alert/id1214962662?mt=8&uo=4">https://itunes.apple.com/us/app/today-weather-forecast-radar-severe-alert/id1214962662?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Tho Tran
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tho-tran/id1110817755?uo=4">© Tho Tran</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple127/v4/30/cf/03/30cf0377-5a69-aa6b-1d4c-76a070d72b5c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27742751-5ca32704-5d7f-11e7-8f27-cf0a4c5638ff.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27742751-5ca32704-5d7f-11e7-8f27-cf0a4c5638ff.png)
https://user-images.githubusercontent.com/3090247/27742751-5ca32704-5d7f-11e7-8f27-cf0a4c5638ff.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27742773-6ed95e16-5d7f-11e7-9208-01ecc01e1b37.png
