### ISSUE TITLE
KAYAK Flights, Hotels & Cars

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9237]
**App Name:** KAYAK Flights, Hotels & Cars
**Bundle ID:** com.kayak.travel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=305204535">305204535</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kayak-flights-hotels-cars/id305204535?mt=8&uo=4">https://itunes.apple.com/us/app/kayak-flights-hotels-cars/id305204535?mt=8&uo=4</a>
**App Version:** 63.0.0
**Seller:** Kayak Software Corp
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kayak-com/id305204538?uo=4">© kayak.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple117/v4/d2/32/41/d23241c9-92d7-b6ae-1dd3-57bceab2ffa7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27767636-02d2f7ec-5efe-11e7-970c-46f7c7226f57.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27742848-c84e2684-5d7f-11e7-8b27-333c5d0fb624.png)
https://user-images.githubusercontent.com/3090247/27742848-c84e2684-5d7f-11e7-8b27-333c5d0fb624.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27742849-c871ec86-5d7f-11e7-8321-4bfd243c9610.png

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/27742848-c84e2684-5d7f-11e7-8b27-333c5d0fb624.png)
https://user-images.githubusercontent.com/3090247/27742848-c84e2684-5d7f-11e7-8b27-333c5d0fb624.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/27742849-c871ec86-5d7f-11e7-8321-4bfd243c9610.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27767636-02d2f7ec-5efe-11e7-970c-46f7c7226f57.png)
https://user-images.githubusercontent.com/2068130/27767636-02d2f7ec-5efe-11e7-970c-46f7c7226f57.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27767637-125b8f58-5efe-11e7-9cd6-741dc7a9e626.png
