### ISSUE TITLE
nPerf speed test: network performance for wifi and mobile internet connection

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9238]
**App Name:** nPerf speed test: network performance for wifi and mobile internet connection
**Bundle ID:** com.fhsarl.nPerfSpedtest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=916797048">916797048</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nperf-speed-test-network-performance-for-wifi-mobile/id916797048?mt=8&uo=4">https://itunes.apple.com/us/app/nperf-speed-test-network-performance-for-wifi-mobile/id916797048?mt=8&uo=4</a>
**App Version:** 2.2.6
**Seller:** France Hardware
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/degrouptest/id496048829?uo=4">© DegroupTest</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/09/f1/04/09f104b9-1625-54db-e853-ee1cb68b81e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27762016-f3f2e27c-5e68-11e7-84bc-db5dd56fe941.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27762016-f3f2e27c-5e68-11e7-84bc-db5dd56fe941.png)
https://user-images.githubusercontent.com/20930745/27762016-f3f2e27c-5e68-11e7-84bc-db5dd56fe941.png

Source:
https://user-images.githubusercontent.com/20930745/27762022-06b48faa-5e69-11e7-8e89-2e58c7f6eb2c.png
