### ISSUE TITLE
AIFit

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9239]
**App Name:** AIFit
**Bundle ID:** com.pingwang.GreatBody
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=975487343">975487343</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aifit/id975487343?mt=8&uo=4">https://itunes.apple.com/us/app/aifit/id975487343?mt=8&uo=4</a>
**App Version:** 2.2.5
**Seller:** Shenzhen inet Mobile Internet Technology Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/shenzhen-inet-mobile-internet-technology-co-ltd/id1116895059?uo=4">© Shenzhen inet Mobile Internet Technology Co., Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple127/v4/89/3b/67/893b670e-a406-5953-ab63-edaa70073258/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27762052-c6ce515e-5e69-11e7-956e-43d24b8da866.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27762052-c6ce515e-5e69-11e7-956e-43d24b8da866.png)
https://user-images.githubusercontent.com/20930745/27762052-c6ce515e-5e69-11e7-956e-43d24b8da866.png

Source:
https://user-images.githubusercontent.com/20930745/27762061-dc18f32a-5e69-11e7-8ff0-150eea21af92.png
