### ISSUE TITLE
checkfelix - Flüge & mehr

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#9240]
**App Name:** checkfelix - Flüge & mehr
**Bundle ID:** com.kayak.checkfelix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=492728058">492728058</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/checkfelix-fl%C3%BCge-mehr/id492728058?uo=4">https://apps.apple.com/us/app/checkfelix-fl%C3%BCge-mehr/id492728058?uo=4</a>
**App Version:** 111.0.0
**Seller:** Kayak Software Corp
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/kayak/id305204538?uo=4">© KAYAK</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/04/18/f5/0418f54b-a42f-5ba3-2400-e49c1295dcad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380254-b95e6100-9a42-11e9-9dec-0c24d70fcf44.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/27768006-7fd1db1e-5f08-11e7-8a5d-e6c4b85d2eb8.png)
https://user-images.githubusercontent.com/2068130/27768006-7fd1db1e-5f08-11e7-8a5d-e6c4b85d2eb8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/27768009-8e73b3ae-5f08-11e7-8264-c17c340dbbdb.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60380254-b95e6100-9a42-11e9-9dec-0c24d70fcf44.png)
https://user-images.githubusercontent.com/20930745/60380254-b95e6100-9a42-11e9-9dec-0c24d70fcf44.png

Source:
https://user-images.githubusercontent.com/20930745/60380255-bb282480-9a42-11e9-8790-1ccd62382095.png
