### ISSUE TITLE
Go VR Player- Virtual Reality 3D Video Player

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9242]
**App Name:** Go VR Player- Virtual Reality 3D Video Player
**Bundle ID:** com.mojing.govr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1137830833">1137830833</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/go-vr-player-virtual-reality-3d-video-player/id1137830833?mt=8&uo=4">https://itunes.apple.com/us/app/go-vr-player-virtual-reality-3d-video-player/id1137830833?mt=8&uo=4</a>
**App Version:** 1.5.5
**Seller:** Beijing Baofengmojing Technologies Co., Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/%E5%8C%97%E4%BA%AC%E6%9A%B4%E9%A3%8E%E9%AD%94%E9%95%9C%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/id1053237135?uo=4">© 北京暴风魔镜科技有限公司</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/e2/ae/0f/e2ae0f00-180e-a71f-e51a-bf6abf0f46eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27837102-b5e7f0cc-60e2-11e7-8be5-93c09387738c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27837102-b5e7f0cc-60e2-11e7-8be5-93c09387738c.png)
https://user-images.githubusercontent.com/20930745/27837102-b5e7f0cc-60e2-11e7-8be5-93c09387738c.png

Source:
https://user-images.githubusercontent.com/20930745/27837124-c93931a4-60e2-11e7-930f-98e4f5f92081.png
