### ISSUE TITLE
UpNext: Daily Calendar, Schedule Planner, Reminder

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9243]
**App Name:** UpNext: Daily Calendar, Schedule Planner, Reminder
**Bundle ID:** com.500labs.UpNext
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1139294203">1139294203</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/upnext-daily-calendar-schedule-planner-reminder/id1139294203?mt=8&uo=4">https://itunes.apple.com/us/app/upnext-daily-calendar-schedule-planner-reminder/id1139294203?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Z1, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/500-labs/id1139294202?uo=4">© 500 Labs</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple127/v4/60/c8/1e/60c81ee5-558e-a459-60fe-b3936f753476/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27956021-0d1daa12-6318-11e7-86b7-608b70c57c1e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27956021-0d1daa12-6318-11e7-86b7-608b70c57c1e.png)
https://user-images.githubusercontent.com/20930745/27956021-0d1daa12-6318-11e7-86b7-608b70c57c1e.png

Source:
https://user-images.githubusercontent.com/20930745/27956038-1d76e5cc-6318-11e7-87b6-8d552d55a94e.png
