### ISSUE TITLE
Storm Radar with NOAA Weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9244]
**App Name:** Storm Radar with NOAA Weather
**Bundle ID:** com.weather.TWCRadar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1216396545">1216396545</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/storm-radar-with-noaa-weather/id1216396545?mt=8&uo=4">https://itunes.apple.com/us/app/storm-radar-with-noaa-weather/id1216396545?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** The Weather Channel
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-weather-channel-interactive/id295646464?uo=4">© The Weather Channel Interactive</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple127/v4/bb/48/62/bb486242-6657-ff53-4dcf-4c7d390c6560/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27956196-f78b67f6-6318-11e7-8435-5acd6b68bddb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/27956196-f78b67f6-6318-11e7-8435-5acd6b68bddb.png)
https://user-images.githubusercontent.com/20930745/27956196-f78b67f6-6318-11e7-8435-5acd6b68bddb.png

Source:
https://user-images.githubusercontent.com/20930745/27956210-0793abe0-6319-11e7-8731-a0f8ebf9677e.png
