### ISSUE TITLE
Parker Planner - Calendar, To-do, Notes All in One

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9246]
**App Name:** Parker Planner - Calendar, To-do, Notes All in One
**Bundle ID:** com.parkerplanners.parkerplanner3in1free
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=875164786">875164786</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parker-planner-calendar-to-do-notes-all-in-one/id875164786?mt=8&uo=4">https://itunes.apple.com/us/app/parker-planner-calendar-to-do-notes-all-in-one/id875164786?mt=8&uo=4</a>
**App Version:** 2.3.2
**Seller:** Parker Planners, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/parker-planners-llc/id469530809?uo=4">© Parker Planners, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/83/ff/36/83ff36a6-49cc-6249-9071-d7782547c54a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28074844-3ef5b0d4-661f-11e7-8c74-37302699ccc6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28074844-3ef5b0d4-661f-11e7-8c74-37302699ccc6.png)
https://user-images.githubusercontent.com/3090247/28074844-3ef5b0d4-661f-11e7-8c74-37302699ccc6.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/28074845-3f3e51a4-661f-11e7-9540-ad6be6b885cf.png
