### ISSUE TITLE
Parker Planner Classic (old version)

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9247]
**App Name:** Parker Planner Classic (old version)
**Bundle ID:** com.parkerplanners.parkerplanner3in1
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=505750841">505750841</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parker-planner-classic-old-version/id505750841?mt=8&uo=4">https://itunes.apple.com/us/app/parker-planner-classic-old-version/id505750841?mt=8&uo=4</a>
**App Version:** 1.7.8
**Seller:** Parker Planners, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/parker-planners-llc/id469530809?uo=4">© Parker Planners, LLC</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/02/52/68/025268bb-d8d2-def5-7cfc-5ec4e6560740/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28074844-3ef5b0d4-661f-11e7-8c74-37302699ccc6.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28074844-3ef5b0d4-661f-11e7-8c74-37302699ccc6.png)
https://user-images.githubusercontent.com/3090247/28074844-3ef5b0d4-661f-11e7-8c74-37302699ccc6.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/28074845-3f3e51a4-661f-11e7-9540-ad6be6b885cf.png

**Comment by dreamnet** [comment]
Same as #9246.
