### ISSUE TITLE
Dice Careers: Tech Jobs, Skills & Salary

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9251]
**App Name:** Dice Careers: Tech Jobs, Skills & Salary
**Bundle ID:** com.dice.Dice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=794201100">794201100</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dice-careers-tech-jobs-skills-salary/id794201100?mt=8&uo=4">https://itunes.apple.com/us/app/dice-careers-tech-jobs-skills-salary/id794201100?mt=8&uo=4</a>
**App Version:** 3.3.9
**Seller:** DHI Group, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dhi-group-inc/id444470345?uo=4">© DHI Group, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/0d/d6/94/0dd69464-64ad-484f-b159-7891ce7ffc49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28418594-d853e54e-6d21-11e7-81e8-f285a525375c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28418594-d853e54e-6d21-11e7-81e8-f285a525375c.png)
https://user-images.githubusercontent.com/3090247/28418594-d853e54e-6d21-11e7-81e8-f285a525375c.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/28418595-d857e25c-6d21-11e7-8adc-4b5cec187e5b.png
