### ISSUE TITLE
Awareness! The Headphone App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9252]
**App Name:** Awareness! The Headphone App
**Bundle ID:** com.essency.awarenessheadphoneapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389245456">389245456</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/awareness-the-headphone-app/id389245456?mt=8&uo=4">https://itunes.apple.com/us/app/awareness-the-headphone-app/id389245456?mt=8&uo=4</a>
**App Version:** 2.9.2
**Seller:** Essency
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/essency/id389245459?uo=4">© Essency</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/01/20/9c/01209c55-0a99-31f1-42d0-cae740fa2211/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28418796-ac8baa9a-6d22-11e7-9543-8bb72e110ce4.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28418796-ac8baa9a-6d22-11e7-9543-8bb72e110ce4.png)
https://user-images.githubusercontent.com/3090247/28418796-ac8baa9a-6d22-11e7-9543-8bb72e110ce4.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/28418795-ac8a26de-6d22-11e7-8f55-2022f36b11f8.png
