### ISSUE TITLE
RoadAhead Highway Exit Finder

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9253]
**App Name:** RoadAhead Highway Exit Finder
**Bundle ID:** com.RoadAhead.RoadAhead
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=434432510">434432510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/roadahead-highway-exit-finder/id434432510?mt=8&uo=4">https://itunes.apple.com/us/app/roadahead-highway-exit-finder/id434432510?mt=8&uo=4</a>
**App Version:** 3.21
**Seller:** RoadAhead Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/roadahead-inc/id434432513?uo=4">© RoadAhead Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/63/84/31/638431fd-c277-045e-215d-6f0d52c2592e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28418946-336016c8-6d23-11e7-8f04-797770841009.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28418946-336016c8-6d23-11e7-8f04-797770841009.png)
https://user-images.githubusercontent.com/3090247/28418946-336016c8-6d23-11e7-8f04-797770841009.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/28418947-336088ec-6d23-11e7-8d2d-d7dc472159d3.png
