### ISSUE TITLE
Teachers FCU

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9255]
**App Name:** Teachers FCU
**Bundle ID:** com.vsoft.teachersfcu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=591881064">591881064</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/teachers-fcu/id591881064?mt=8&uo=4">https://itunes.apple.com/us/app/teachers-fcu/id591881064?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** VSoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vsoft-corporation/id378981988?uo=4">© VSoft Corporation</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple3/v4/74/02/9a/74029a19-cd3d-5561-660a-2653c07c2ab9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/28834582-e6d1808e-76e2-11e7-8fd5-3cedda0e74f6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/28834582-e6d1808e-76e2-11e7-8fd5-3cedda0e74f6.png)
https://user-images.githubusercontent.com/20930745/28834582-e6d1808e-76e2-11e7-8fd5-3cedda0e74f6.png

Source:
https://user-images.githubusercontent.com/20930745/28834608-fdcc1506-76e2-11e7-9734-bb60cb6acbc5.png
