### ISSUE TITLE
AccelMeter - 3D Vector Accelerometer (free level)

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9257]
**App Name:** AccelMeter - 3D Vector Accelerometer (free level)
**Bundle ID:** com.plaincode.AccelMeter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=346525189">346525189</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/accelmeter-3d-vector-accelerometer-free-level/id346525189?mt=8&uo=4">https://itunes.apple.com/us/app/accelmeter-3d-vector-accelerometer-free-level/id346525189?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** Peter Breitling
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/peter-breitling/id286215120?uo=4">© Peter Breitling</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple19/v4/9c/ba/3d/9cba3d79-2be9-3126-3242-952ff81ad3ec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29246732-b72d5dba-8003-11e7-887f-c10d8c1b5b60.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29246732-b72d5dba-8003-11e7-887f-c10d8c1b5b60.png)
https://user-images.githubusercontent.com/2068130/29246732-b72d5dba-8003-11e7-887f-c10d8c1b5b60.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29246737-c751062e-8003-11e7-9dd5-d77a5b7628dd.png
