### ISSUE TITLE
ColorSnap® Visualizer for iPhone

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9258]
**App Name:** ColorSnap® Visualizer for iPhone
**Bundle ID:** com.resource.ColorSnap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=316256242">316256242</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/colorsnap-visualizer-for-iphone/id316256242?mt=8&uo=4">https://itunes.apple.com/us/app/colorsnap-visualizer-for-iphone/id316256242?mt=8&uo=4</a>
**App Version:** 4.7.5
**Seller:** The Sherwin-Williams Company
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-sherwin-williams-company/id708335816?uo=4">© The Sherwin-Williams Company</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple127/v4/4b/bb/a3/4bbba365-b860-32d4-c710-48c2991956a7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/28535338-4b1c9730-70a4-11e7-9cae-d3935b19038e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/28535338-4b1c9730-70a4-11e7-9cae-d3935b19038e.png)
https://user-images.githubusercontent.com/20930745/28535338-4b1c9730-70a4-11e7-9cae-d3935b19038e.png

Source:
https://user-images.githubusercontent.com/20930745/28535358-5f33ce3c-70a4-11e7-82fd-baf7c591f7fb.png
