### ISSUE TITLE
VPN Proxy Master - Unlimited WiFi security VPN

### ISSUE THREAD

**Issue by nekholm** [glasklart/hd#9259]
**App Name:** VPN Proxy Master - Unlimited WiFi security VPN
**Bundle ID:** co.allconnected.vpnmaster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1025707485">1025707485</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vpn-proxy-master-unlimited-wifi-security-vpn/id1025707485?mt=8&uo=4">https://itunes.apple.com/us/app/vpn-proxy-master-unlimited-wifi-security-vpn/id1025707485?mt=8&uo=4</a>
**App Version:** 2.5.5
**Seller:** All Connected Co., Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/all-connected-co-ltd/id994788580?uo=4">© ALL Connected Co.,Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/03/cc/98/03cc986c-178a-11dc-96ea-fbeb9df52bf2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28791398-f105e1cc-75f1-11e7-92e2-c58f6d0c6c64.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/28791398-f105e1cc-75f1-11e7-92e2-c58f6d0c6c64.png)
https://user-images.githubusercontent.com/3090247/28791398-f105e1cc-75f1-11e7-92e2-c58f6d0c6c64.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/28791397-f10313d4-75f1-11e7-8fae-5bf341cd3453.png
