### ISSUE TITLE
The Binding of Isaac: Rebirth

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9263]
**App Name:** The Binding of Isaac: Rebirth
**Bundle ID:** com.Nicalis.Isaac-iOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1069549814">1069549814</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-binding-of-isaac-rebirth/id1069549814?mt=8&uo=4">https://itunes.apple.com/us/app/the-binding-of-isaac-rebirth/id1069549814?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Nicalis, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nicalis-inc/id356341688?uo=4">© Nicalis, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple82/v4/4b/8e/99/4b8e9989-4b23-5ead-a43e-4ad4fb3ed1ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29239260-e9b00f8a-7f4a-11e7-9ce5-59aaa8ffe814.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29239260-e9b00f8a-7f4a-11e7-9ce5-59aaa8ffe814.png)
https://user-images.githubusercontent.com/2068130/29239260-e9b00f8a-7f4a-11e7-9ce5-59aaa8ffe814.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29239264-fb5b709e-7f4a-11e7-8be6-b0d7a24e8fdf.png
