### ISSUE TITLE
Hello Weather

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9266]
**App Name:** Hello Weather
**Bundle ID:** hello-weather-app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=978393692">978393692</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hello-weather/id978393692?mt=8&uo=4">https://itunes.apple.com/us/app/hello-weather/id978393692?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Pop State Co
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pop-state-co/id1122168340?uo=4">© Pop State Co</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/ee/b8/6c/eeb86cb7-5cd4-b65a-4d17-5b5c9e70f50f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29004088-505dfc34-7ac2-11e7-8a7c-8953a146c717.png)
https://user-images.githubusercontent.com/2068130/29004088-505dfc34-7ac2-11e7-8a7c-8953a146c717.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29004093-60060ec4-7ac2-11e7-9776-f904274be59b.png
