### ISSUE TITLE
Xodo PDF Pro - Annotate, sign & more

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9267]
**App Name:** Xodo PDF Pro - Annotate, sign & more
**Bundle ID:** com.Xodo.pdf.reader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=805075929">805075929</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xodo-pdf-pro-annotate-sign-more/id805075929?mt=8&uo=4">https://itunes.apple.com/us/app/xodo-pdf-pro-annotate-sign-more/id805075929?mt=8&uo=4</a>
**App Version:** 2.4.3
**Seller:** Xodo Technologies Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/xodo-technologies-inc/id805075932?uo=4">© Xodo Technologies Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/73/18/46/731846dc-9861-b88b-e714-92222d3d9a6f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29004142-490ef2c0-7ac3-11e7-97d4-2f1a673578a2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29004142-490ef2c0-7ac3-11e7-97d4-2f1a673578a2.png)
https://user-images.githubusercontent.com/2068130/29004142-490ef2c0-7ac3-11e7-97d4-2f1a673578a2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29004147-57f2ccee-7ac3-11e7-9a2b-8ffe6c379fd2.png
