### ISSUE TITLE
Flight Board

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9268]
**App Name:** Flight Board
**Bundle ID:** com.iaftt.flightboardpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=690568297">690568297</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flight-board/id690568297?mt=8&uo=4">https://itunes.apple.com/us/app/flight-board/id690568297?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Impala Studios B.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/impala-studios/id1063279743?uo=4">© Impala Studios</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/56/48/04/56480449-0e7c-caf0-4575-c50835753561/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29004182-c0fde37c-7ac3-11e7-94f3-31a21f6acde0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29004182-c0fde37c-7ac3-11e7-94f3-31a21f6acde0.png)
https://user-images.githubusercontent.com/2068130/29004182-c0fde37c-7ac3-11e7-94f3-31a21f6acde0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29004187-cffae79e-7ac3-11e7-9404-abf758e65a07.png
