### ISSUE TITLE
Amount Plus - Unit And Currency Converter

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9269]
**App Name:** Amount Plus - Unit And Currency Converter
**Bundle ID:** com.marcotorretta.Amount
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1031021466">1031021466</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amount-plus-unit-and-currency-converter/id1031021466?mt=8&uo=4">https://itunes.apple.com/us/app/amount-plus-unit-and-currency-converter/id1031021466?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Marco Torretta
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marco-torretta/id560750786?uo=4">© Marco Torretta</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple20/v4/b3/a9/9c/b3a99c23-dec4-c57b-f6f8-6c4f086fb353/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29045713-34ce5efa-7b8a-11e7-98f2-9ff6e12c0782.png)

**Comment by ivanov007** [comment]
same as #2053
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13135308/beb7806e-d60f-11e5-8c56-f2992ed21915.png)
https://cloud.githubusercontent.com/assets/2068130/13135308/beb7806e-d60f-11e5-8c56-f2992ed21915.png

---

Source:
https://cloud.githubusercontent.com/assets/2068130/13135321/ce2d37d2-d60f-11e5-85ee-e37717fcecb9.png
