### ISSUE TITLE
AirFile - Cloud Manager for Dropbox and OneDrive

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#927]
**App Name:** AirFile - Cloud Manager for Dropbox and OneDrive
**Bundle ID:** com.getairfile.ios.AirFile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=560145740">560145740</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/airfile-cloud-manager-for/id560145740?mt=8&uo=4">https://itunes.apple.com/us/app/airfile-cloud-manager-for/id560145740?mt=8&uo=4</a>
**App Version:** 2.8.5
**Seller:** Tuyen Dinh
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tuyen-dinh/id560145743?uo=4">© Tuyen Dinh</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/be/7b/12/be7b1204-306a-4101-babd-ea3de7656563/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20066636/848f647e-a512-11e6-8bb4-d8ad14ad723d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20066636/848f647e-a512-11e6-8bb4-d8ad14ad723d.png)
https://cloud.githubusercontent.com/assets/20930745/20066636/848f647e-a512-11e6-8bb4-d8ad14ad723d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20066665/a939edee-a512-11e6-87e0-c0b22c4415a7.png
