### ISSUE TITLE
Nintendo Switch Online

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9270]
**App Name:** Nintendo Switch Online
**Bundle ID:** com.nintendo.znca
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1234806557">1234806557</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nintendo-switch-online/id1234806557?mt=8&uo=4">https://itunes.apple.com/us/app/nintendo-switch-online/id1234806557?mt=8&uo=4</a>
**App Version:** 1.0.4
**Seller:** Nintendo Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nintendo-co-ltd/id1062496488?uo=4">© Nintendo Co., Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/5d/57/ef/5d57ef28-bc74-130b-0631-202f62447da0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29140462-2e4d980c-7d10-11e7-969f-daf408844361.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29140462-2e4d980c-7d10-11e7-969f-daf408844361.png)
https://user-images.githubusercontent.com/3090247/29140462-2e4d980c-7d10-11e7-969f-daf408844361.png
--- ---
Source:
![com nintendo znca](https://user-images.githubusercontent.com/3090247/29140463-2e4e7c2c-7d10-11e7-8fd0-1fd6fac91fc7.png)
