### ISSUE TITLE
Nintendo Switch Parental Controls

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9271]
**App Name:** Nintendo Switch Parental Controls
**Bundle ID:** com.nintendo.znma
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1190074407">1190074407</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nintendo-switch-parental-controls/id1190074407?mt=8&uo=4">https://itunes.apple.com/us/app/nintendo-switch-parental-controls/id1190074407?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Nintendo Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nintendo-co-ltd/id1062496488?uo=4">© Nintendo Co., Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/cd/72/bb/cd72bb89-775c-f25b-2184-80d995ef18ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29215809-145f298e-7e72-11e7-835d-8093f1f79816.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29215809-145f298e-7e72-11e7-835d-8093f1f79816.png)
https://user-images.githubusercontent.com/3090247/29215809-145f298e-7e72-11e7-835d-8093f1f79816.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29215810-14625e7e-7e72-11e7-89a1-93f0ef95ecc4.png
