### ISSUE TITLE
B.tv mobile

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9272]
**App Name:** B.tv mobile
**Bundle ID:** com.bouyguestelecom.btv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=739824309">739824309</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/b-tv-mobile/id739824309?mt=8&uo=4">https://itunes.apple.com/fr/app/b-tv-mobile/id739824309?mt=8&uo=4</a>
**App Version:** 8.3.8
**Seller:** Bouygues Telecom
**Developer:** <a target="_blank" href="https://itunes.apple.com/fr/developer/bouygues-telecom/id316348393?uo=4">© Bouygues Telecom</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/6f/5a/24/6f5a24ee-f3d0-e37e-f137-4e6987c62c87/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621485-6efed780-a8a7-11e8-9fe9-fbb6505b2141.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29141125-84027f86-7d12-11e7-8f8d-854d4bbae408.png)
https://user-images.githubusercontent.com/3090247/29141125-84027f86-7d12-11e7-8f8d-854d4bbae408.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29141126-847ae746-7d12-11e7-9d2e-a6131d68bebd.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44621485-6efed780-a8a7-11e8-9fe9-fbb6505b2141.png)
https://user-images.githubusercontent.com/2068130/44621485-6efed780-a8a7-11e8-9fe9-fbb6505b2141.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44621493-7e7e2080-a8a7-11e8-8077-89cf502204d6.png
