### ISSUE TITLE
Espace Client Bouygues Telecom

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9273]
**App Name:** Espace Client Bouygues Telecom
**Bundle ID:** fr.bouyguestelecom.espaceclient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=422590767">422590767</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/espace-client-bouygues-telecom/id422590767?mt=8&uo=4">https://itunes.apple.com/fr/app/espace-client-bouygues-telecom/id422590767?mt=8&uo=4</a>
**App Version:** 6.5.5
**Seller:** Bouygues Telecom
**Developer:** <a target="_blank" href="https://itunes.apple.com/fr/developer/bouygues-telecom/id316348393?uo=4">© Bouygues Telecom</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/f7/68/fb/f768fbab-7cd3-26bb-e45d-457b49b39d94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29215293-0b29b426-7e70-11e7-835c-8d0a0e0ec88d.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29215293-0b29b426-7e70-11e7-835c-8d0a0e0ec88d.png)
https://user-images.githubusercontent.com/3090247/29215293-0b29b426-7e70-11e7-835c-8d0a0e0ec88d.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29215294-0b2e477a-7e70-11e7-8a68-8fca84a35e7a.png
