### ISSUE TITLE
World & YOU

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9274]
**App Name:** World & YOU
**Bundle ID:** fr.bouyguestelecom.worldandyou
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=657368068">657368068</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/world-you/id657368068?mt=8&uo=4">https://itunes.apple.com/us/app/world-you/id657368068?mt=8&uo=4</a>
**App Version:** 7.6.0
**Seller:** Bouygues Telecom
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bouygues-telecom/id316348393?uo=4">© Bouygues Telecom</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple127/v4/f5/f3/2f/f5f32fac-f3c8-4556-54af-40f8720c6c90/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29140607-ad4af24e-7d10-11e7-9e0f-7284ee350b88.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29140607-ad4af24e-7d10-11e7-9e0f-7284ee350b88.png)
https://user-images.githubusercontent.com/3090247/29140607-ad4af24e-7d10-11e7-9e0f-7284ee350b88.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29140608-ad542544-7d10-11e7-9770-3fc1ac0abee3.png
