### ISSUE TITLE
Micromania

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9275]
**App Name:** Micromania
**Bundle ID:** fr.micromania.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943004296">943004296</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/micromania/id943004296?mt=8&uo=4">https://itunes.apple.com/us/app/micromania/id943004296?mt=8&uo=4</a>
**App Version:** 4.3.5
**Seller:** Game On Line
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/micromania/id921586575?uo=4">© Micromania</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple117/v4/6e/46/b6/6e46b6c5-d5e3-89b0-9af7-cc9255a74271/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29140789-4c0e5150-7d11-11e7-84e8-ef9d2988ff5a.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29140789-4c0e5150-7d11-11e7-84e8-ef9d2988ff5a.png)
https://user-images.githubusercontent.com/3090247/29140789-4c0e5150-7d11-11e7-84e8-ef9d2988ff5a.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29140788-4c0e2d1a-7d11-11e7-898e-e10d6e12bead.png
