### ISSUE TITLE
Bitdefender Central

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9276]
**App Name:** Bitdefender Central
**Bundle ID:** com.bitdefender.connect.mgmt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=969933082">969933082</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bitdefender-central/id969933082?mt=8&uo=4">https://itunes.apple.com/us/app/bitdefender-central/id969933082?mt=8&uo=4</a>
**App Version:** 2.24
**Seller:** Bitdefender SRL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bitdefender-srl/id384899757?uo=4">© Bitdefender SRL</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/ff/14/be/ff14be91-1b25-31b4-2751-78b15c7b9e23/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29140881-b1d88960-7d11-11e7-8feb-10f5c6ab7cb2.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29140881-b1d88960-7d11-11e7-8feb-10f5c6ab7cb2.png)
https://user-images.githubusercontent.com/3090247/29140881-b1d88960-7d11-11e7-8feb-10f5c6ab7cb2.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29140880-b1d87dc6-7d11-11e7-9d62-d149a08a9697.png
