### ISSUE TITLE
CGR Cinémas

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9277]
**App Name:** CGR Cinémas
**Bundle ID:** fr.cotecine.cgr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=379252473">379252473</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ch/app/cgr-cin%C3%A9mas/id379252473?mt=8&uo=4">https://itunes.apple.com/ch/app/cgr-cin%C3%A9mas/id379252473?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** cote cine
**Developer:** <a target="_blank" href="https://itunes.apple.com/ch/developer/c%C3%B4t%C3%A9-cin%C3%A9/id379252479?uo=4">© Côté Ciné</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/c6/04/9f/c6049fce-27f0-6b73-2c38-cbd037e6a253/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29141011-1dd633e2-7d12-11e7-95a4-11ad92a75314.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29141011-1dd633e2-7d12-11e7-95a4-11ad92a75314.png)
https://user-images.githubusercontent.com/3090247/29141011-1dd633e2-7d12-11e7-95a4-11ad92a75314.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29141010-1dd4ad24-7d12-11e7-862b-e4575a49033a.png
