### ISSUE TITLE
Athan Pro Muslim: Azan Prayer Times Quran & Qibla

### ISSUE THREAD

**Issue by Feeriix** [glasklart/hd#9278]
**App Name:** Athan Pro Muslim: Azan Prayer Times Quran & Qibla
**Bundle ID:** Quanticapps.Athan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=743843090">743843090</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/athan-pro-muslim-azan-prayer-times-quran-qibla/id743843090?mt=8&uo=4">https://itunes.apple.com/us/app/athan-pro-muslim-azan-prayer-times-quran-qibla/id743843090?mt=8&uo=4</a>
**App Version:** 5.5
**Seller:** Quanticapps Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/quanticapps-ltd/id511757906?uo=4">© Quanticapps Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple127/v4/a3/93/c9/a393c921-d0ab-0e23-6f7b-dd114f4ffc75/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/6758392/29168621-e54e7f7a-7dcf-11e7-9816-617b04a8dd04.png)

**Comment by Feeriix** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/6758392/29168621-e54e7f7a-7dcf-11e7-9816-617b04a8dd04.png)
https://user-images.githubusercontent.com/6758392/29168621-e54e7f7a-7dcf-11e7-9816-617b04a8dd04.png

<hr>

Source:
https://user-images.githubusercontent.com/6758392/29168649-18654d44-7dd0-11e7-9754-a1f7e155710e.png

**Comment by dreamnet** [comment]
@Feeriix Great work 👍 - if you wish to receive credit for icons you submit and be listed on the [contributors page](https://github.com/glasklart/hd/graphs/contributors) you must have a public email address attatched to your Github profile.

**Comment by dreamnet** [comment]
@Feeriix ...well, I am gainig the credits... 😉
