### ISSUE TITLE
Fancy Units & Currency Converter Offline - Plus!

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9281]
**App Name:** Fancy Units & Currency Converter Offline - Plus!
**Bundle ID:** com.fancyinteractive.converter.paid
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=939222566">939222566</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fancy-units-currency-converter-offline-plus/id939222566?mt=8&uo=4">https://itunes.apple.com/us/app/fancy-units-currency-converter-offline-plus/id939222566?mt=8&uo=4</a>
**App Version:** 1.5.6
**Seller:** Ievgenii Lebid
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ievgenii-lebid/id850306142?uo=4">© Ievgenii Lebid</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/28/f4/7f/28f47f94-c2a1-3e10-304d-62e82243c1ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29252738-0792d05a-806d-11e7-8bf4-9a308974177f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29252715-80504cb2-806c-11e7-9d94-b8dbf5b0764d.png)
https://user-images.githubusercontent.com/2068130/29252715-80504cb2-806c-11e7-9d94-b8dbf5b0764d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29252717-9016426e-806c-11e7-9de6-69be3306b52b.png
