### ISSUE TITLE
Calvertr - Pro converter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9282]
**App Name:** Calvertr - Pro converter
**Bundle ID:** com.r3app.calvertr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=920041144">920041144</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calvertr-pro-converter/id920041144?mt=8&uo=4">https://itunes.apple.com/us/app/calvertr-pro-converter/id920041144?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** ReasonX, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/reasonx-inc/id814917963?uo=4">© ReasonX, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/ba/6c/72/ba6c72cf-77ad-ddf3-7848-a5b8b65ffcc8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29243413-a38ee856-7f9e-11e7-9247-6a45c9eccecd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29243413-a38ee856-7f9e-11e7-9247-6a45c9eccecd.png)
https://user-images.githubusercontent.com/2068130/29243413-a38ee856-7f9e-11e7-9247-6a45c9eccecd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29243417-b2e58be8-7f9e-11e7-8a6a-83f25ba7b702.png
