### ISSUE TITLE
Box for iPhone and iPad

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9283]
**App Name:** Box for iPhone and iPad
**Bundle ID:** net.box.BoxNet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=290853822">290853822</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/box-for-iphone-and-ipad/id290853822?mt=8&uo=4">https://itunes.apple.com/us/app/box-for-iphone-and-ipad/id290853822?mt=8&uo=4</a>
**App Version:** 4.1.4
**Seller:** Box, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/box-inc/id290853825?uo=4">© Box, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple127/v4/32/15/75/321575a4-2564-5b5e-9b9b-dee0d4e99fd0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29243356-6f1c5cda-7f9d-11e7-89a3-9431a730b820.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29243356-6f1c5cda-7f9d-11e7-89a3-9431a730b820.png)
https://user-images.githubusercontent.com/2068130/29243356-6f1c5cda-7f9d-11e7-89a3-9431a730b820.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29243362-80929dbc-7f9d-11e7-8a77-08a2320e6655.png
