### ISSUE TITLE
Drei TV

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#9287]
**App Name:** Drei TV
**Bundle ID:** at.drei.tv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1159362898">1159362898</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/drei-tv/id1159362898?uo=4">https://apps.apple.com/us/app/drei-tv/id1159362898?uo=4</a>
**App Version:** 1.3.2
**Seller:** Hutchison Drei Austria GmbH
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/hutchison-drei-austria-gmbh/id404154555?uo=4">© Hutchison Drei Austria GmbH</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/c6/4f/37/c64f374c-9555-acb0-eed0-a2e58da41c5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382908-48cb3a80-9a6a-11e9-9a95-a99f6e96c43c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29251579-7aebe4e4-8057-11e7-8ac0-dbe8f7ce649c.png)
https://user-images.githubusercontent.com/2068130/29251579-7aebe4e4-8057-11e7-8ac0-dbe8f7ce649c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29251583-8995749c-8057-11e7-9da2-b09402230fb1.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382908-48cb3a80-9a6a-11e9-9a95-a99f6e96c43c.png)
https://user-images.githubusercontent.com/20930745/60382908-48cb3a80-9a6a-11e9-9a95-a99f6e96c43c.png

Source:
https://user-images.githubusercontent.com/20930745/60382909-49fc6780-9a6a-11e9-8d6a-3d4dbd125b86.png
