### ISSUE TITLE
Mi Heart rate continuous monitoring - be fit

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9298]
**App Name:** Mi Heart rate continuous monitoring - be fit
**Bundle ID:** InUmbra.MiHR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1074341151">1074341151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mi-heart-rate-continuous-monitoring-be-fit/id1074341151?mt=8&uo=4">https://itunes.apple.com/us/app/mi-heart-rate-continuous-monitoring-be-fit/id1074341151?mt=8&uo=4</a>
**App Version:** 1.8.2
**Seller:** Hubert Wilczynski
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hubert-wilczynski/id790398888?uo=4">© Hubert Wilczynski</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple117/v4/ec/8a/26/ec8a2661-e88a-23a2-ffae-c51262eb424e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29322076-4ddd6a46-81aa-11e7-8031-2cd1051f94d7.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29322076-4ddd6a46-81aa-11e7-8031-2cd1051f94d7.png)
https://user-images.githubusercontent.com/3090247/29322076-4ddd6a46-81aa-11e7-8031-2cd1051f94d7.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29322109-6353364e-81aa-11e7-9917-d3440b49ead8.png
