### ISSUE TITLE
RENTMEE - российский каршеринг

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9299]
**App Name:** RENTMEE - российский каршеринг
**Bundle ID:** rentmee.club.carsharing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1142193212">1142193212</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ru/app/rentmee-%D1%80%D0%BE%D1%81%D1%81%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9-%D0%BA%D0%B0%D1%80%D1%88%D0%B5%D1%80%D0%B8%D0%BD%D0%B3/id1142193212?mt=8&uo=4">https://itunes.apple.com/ru/app/rentmee-%D1%80%D0%BE%D1%81%D1%81%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9-%D0%BA%D0%B0%D1%80%D1%88%D0%B5%D1%80%D0%B8%D0%BD%D0%B3/id1142193212?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Erast Kadagidze
**Developer:** <a target="_blank" href="https://itunes.apple.com/ru/developer/erast-kadagidze/id1142193211?uo=4">© Erast Kadagidze</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/d6/04/b5/d604b557-c4ea-9858-e326-1fa64cc503ff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29395327-494c65d8-8310-11e7-8cc6-0889c619775d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29395327-494c65d8-8310-11e7-8cc6-0889c619775d.png)
https://user-images.githubusercontent.com/2068130/29395327-494c65d8-8310-11e7-8cc6-0889c619775d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29395335-59742a90-8310-11e7-9c7c-d7b5e3e98deb.png
