### ISSUE TITLE
All Carsharing

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9300]
**App Name:** All Carsharing
**Bundle ID:** com.allcarsharing
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1084180222">1084180222</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/all-carsharing/id1084180222?mt=8&uo=4">https://itunes.apple.com/us/app/all-carsharing/id1084180222?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** Vladislav Zrazhevsky
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vladislav-zrazhevsky/id1084180221?uo=4">© Vladislav Zrazhevsky</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/a4/8c/87/a48c87f5-607f-d6fb-2977-181392340c2b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29395558-f51aa6da-8311-11e7-83c6-14cdba5617c5.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29395558-f51aa6da-8311-11e7-83c6-14cdba5617c5.png)
https://user-images.githubusercontent.com/2068130/29395558-f51aa6da-8311-11e7-83c6-14cdba5617c5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29395570-058b8d54-8312-11e7-8f1d-0af43fee76c0.png
